### ISSUE TITLE
issues with samples

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#15337]
1. Under &quot;Searching files for content&quot;
   it should say &quot;files and directories&quot; not &quot;file and directories&quot;.

   That is, make &quot;file&quot; plural.

2. The Try It links for &quot;working with JSON&quot; and &quot;fetching data dynamically&quot; link into the tutorial. These should link to READMEs with the deployed apps instead.
3. The Try It page for the requestAnimationFrame sample displays a warning in the console:

   The page at https://www.dartlang.org/samples/raf/ displayed insecure content from http://1-ps.googleusercontent.com/x/s.html5rocks-hrd.appspot.com/www.html5r…com/en/tutorials/speed/animations/particle.png.pagespeed.ce.jWkhaHzlBa.png.

4. The Geolocation sample has an exception, with a stack trace:

    ```
   Uncaught Error: NullError: Cannot call &quot;get$coords&quot; on null 
   collection_dev_patch.dart:21
   Stack Trace: 
   TypeError: Cannot call method 'get$coords' of null
   at Object.J.get$coords$x (https://www.dartlang.org/samples/geolocation/example/trip_meter.dart.js:5920:39)
   at main_closure1.call$1 (https://www.dartlang.org/samples/geolocation/example/trip_meter.dart.js:5720:55)
   at Object.rootRunUnary (https://www.dartlang.org/samples/geolocation/example/tripmeter.dart.js:2660:14)
   at RootZone.runUnary$2 (https://www.dartlang.org/samples/geolocation/example/tripmeter.dart.js:3772:14)
   at RootZone.BaseZone.runUnaryGuarded$2 (https://www.dartlang.org/samples/geolocation/example/trip_meter.dart.js:3702:17)
   at ControllerSubscription.BufferingStreamSubscription.sendData$1 (https://www.dartlang.org/samples/geolocation/example/tripmeter.dart.js:3516:16)
   at ControllerSubscription.BufferingStreamSubscription.async$add$1 (https://www.dartlang.org/samples/geolocation/example/trip_meter.dart.js:3473:12)
   at SyncStreamControllerDispatch.sendData$1 (https://www.dartlang.org/samples/geolocation/example/trip_meter.dart.js:3307:30)
   at SyncStreamController.StreamController.async$add$1 (https://www.dartlang.org/samples/geolocation/example/trip_meter.dart.js:3253:12)
   at Geolocation_watchPosition__closure.call$1 (https://www.dartlang.org/samples/geolocation/example/trip_meter.dart.js:5441:8)
   collection_dev_patch.dart:21
   Uncaught NullError: Cannot call &quot;get$coords&quot; on null js_helper.dart:834
   ```

**Comment by srawlins** [comment]
I don't think these pages exist any more. The site has been redesigned a few times since this was opened. Close?
