### ISSUE TITLE
Mips debug failure on test_runner_test

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#20351]
test_runner_test fails in debug mode on mips hardware, but not in release mode.  It fails on different subtests each time, timing out instead of getting the right result.  Rarely, it passes.  Marking as Skip in the status file.

**Comment by whesse** [comment]
The test_runner_test is now failing on debug x64 vm.  The passing subtest, which should just start up the dart executable with the test script and the command line argument "pass", which should then just exit, returning 0, is instead timing out flakily.

Example of a failure is below. Notice it only takes 25 seconds to fail, which may indicate that the subtest timeout is too fast.  I am trying an increase of the timeout from 10 to 20 seconds, which may fix the flaky subtest timeouts.

FAILED: none-vm debug_x64 standalone/io/test_runner_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:
stdout:
stdout = []
stderr = []
stderr:
Unhandled exception:
Test case pass failed, result == Timeout
#0      TestController.processCompletedTest (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/tests/standalone/io/test_runner_test.dart:54:9)
#1      EventListener.done (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/tests/standalone/io/test_runner_test.dart:139:20)
#2      ProcessQueue.eventFinishedTestCase (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/tools/testing/dart/test_runner.dart:3126:16)
#3      ProcessQueue.ProcessQueue.setupForRunning.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/tools/testing/dart/test_runner.dart:3090:11)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#6      _DelayedData.perform (dart:async/stream_impl.dart:590)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:666)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/tests/standalone/io/test_runner_test.dart
Took 0:00:25.931757
