### ISSUE TITLE
misleading error when library-root is wrong

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23599]
When using an incorrect library-root:
```bash
./sdk/bin/dart2js --library-root=/tmp/ foo.dart 
```

We get an error message indicating that core.dart is not found, but the exception shown afterwards is very noisy and misleading:

```
/tmp/lib/core/core.dart:
Error: Error reading '/tmp/lib/core/core.dart' (No such file or directory)
simple.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: The null object does not have a getter 'sourcePosition'.

NoSuchMethodError: method not found: 'sourcePosition'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      Compiler.spanFromElement (file:///path-to-dart2js/src/compiler.dart:1959:17)
#3      Compiler.spanFromSpannable (file:///path-to-dart2js/src/compiler.dart:1187:14)
#4      Compiler.reportDiagnostic (file:///path-to-dart2js/src/apiimpl.dart:359:27)
#5      Compiler.reportDiagnosticInternal (file:///path-to-dart2js/src/compiler.dart:1904:5)
#6      Compiler.internalError (file:///path-to-dart2js/src/compiler.dart:1149:5)
#7      Compiler.initializeCoreClasses (file:///path-to-dart2js/src/compiler.dart:1456:7)
#8      Compiler.onLibraryScanned (file:///path-to-dart2js/src/compiler.dart:1282:7)
#9      _LibraryLoaderTask.processLibraryTags.<anonymous closure> (file:///path-to-dart2js/src/library_loader.dart:411:23)
#10     _RootZone.runUnary (dart:async/zone.dart:1166)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#13     _Future._complete (dart:async/future_impl.dart:358)
#14     Future.doWhile.<anonymous closure> (dart:async/future.dart:364)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#16     _RootZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1133)
#17     _RootZone.runUnary (dart:async/zone.dart:1166)
#18     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#19     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#20     _Future._completeWithValue (dart:async/future_impl.dart:368)
#21     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#23     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by sigmundch** [comment]
I've created https://codereview.chromium.org/1157433014/ to avoid a crash in the compiler. The output after that change is not perfect though, I'd rather have an error that just says to verify that the sdk libraries are in the right place.

The new error looks like:
```
/tmp/lib/core/core.dart:
Error: Error reading '/tmp/lib/core/core.dart' (No such file or directory)
Internal Error: dart:core library does not contain required classes: [Object, bool, num, int, double, String, Function, List, Type, Map, Null, StackTrace, Iterable, Symbol]
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Internal Error: dart:core library does not contain required classes: [Object, bool, num, int, double, String, Function, List, Type, Map, Null, StackTrace, Iterable, Symbol]
#0      Compiler.internalError (file:///path-to-dart2js/src/compiler.dart:1151:5)
#1      Compiler.initializeCoreClasses (file:///path-to-dart2js/src/compiler.dart:1456:7)
#2      Compiler.onLibraryScanned (file:///path-to-dart2js/src/compiler.dart:1282:7)
#3      _LibraryLoaderTask.processLibraryTags.<anonymous closure> (file:///path-to-dart2js/src/library_loader.dart:411:23)
#4      _RootZone.runUnary (dart:async/zone.dart:1166)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#7      _Future._complete (dart:async/future_impl.dart:358)
#8      Future.doWhile.<anonymous closure> (dart:async/future.dart:364)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#10     _RootZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1133)
#11     _RootZone.runUnary (dart:async/zone.dart:1166)
#12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#13     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#14     _Future._completeWithValue (dart:async/future_impl.dart:368)
#15     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#17     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```
