### ISSUE TITLE
crash when using @MirrorsUsed

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23625]
Here is a simplified example:

``` dart
import 'package:di/di.dart';

@MirrorsUsed(targets: const [Base], override: '*')
import 'dart:mirrors';

class I implements Injectable {
  final Function module;
  const I({this.module});
}

class Base {}

@I(module: M.foo)
class M extends Base {
  static void foo(_) {}
}

main() {
  new ModuleInjector([new Module()]).get(M);
}
```

this produces this error:

```
test.dart:16:19:
Internal Error: The compiler crashed when compiling this element.
      static void foo(_) {}
                  ^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: The null object does not have a getter 'isParameter'.

NoSuchMethodError: method not found: 'isParameter'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ClosureTranslator.visitFunctionExpression .../compiler/lib/src/closure.dart:1062:17)
```

**Comment by sigmundch** [comment]
Here is a reduced example without any package dependencies:

```dart
import 'b.dart';

@MirrorsUsed(targets: const [Base], override: '*')
import 'dart:mirrors';

class I {
  final Function method;
  const I(this.method);
}

class Base {}

@I(M.foo)
class M extends Base {
  static void foo(_) {}
}

main() => generateFactory(M);
```

**b.dart**:
```dart
import 'dart:mirrors';

generateFactory(Type type) => reflectClass(type).newInstance;
```

(this example was reduced from an angular example that used `@Component(module: ...)`)

**Comment by sigmundch** [comment]
A simple workaround for those who run into this would be to define separate a constant with the static function. Basically rewrite **a.dart(( as follows:
```
@MirrorsUsed(targets: const [B], override: '*')
import 'dart:mirrors';
import 'b.dart';

class B {}

const foo = C.m;
@Annot(foo)
class C extends B {
  static void m(_) {}
}


main() => generateFactory(C);
```

**Comment by sigmundch** [comment]
before I jump in and investigate, @floitschG let me know if you have any hunches or clues for possible causes for this.

**Comment by matanlurey** [comment]
Safe to say this is stale now.
