### ISSUE TITLE
Analyzer crash in IntelliJ

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#23670]
Running IntelliJ IDEA 14.1.3, the analyzer crashes after a while.  Sometimes it's a matter of minutes, sometimes days.  The initial Java exception is below.  After that, the analyzer is dead and all operations time out after a second.  This makes IntelliJ unusable and it has to be restarted.  Stack trace:

```
[249645638]  ERROR - n.impl.GeneralHighlightingPass - null 
java.util.ConcurrentModificationException
	at gnu.trove.THashIterator.nextIndex(THashIterator.java:84)
	at gnu.trove.TIterator.moveToNextIndex(TIterator.java:88)
	at gnu.trove.THashIterator.next(THashIterator.java:68)
	at com.jetbrains.lang.dart.util.DartGenericSpecialization.clone(DartGenericSpecialization.java:33)
	at com.jetbrains.lang.dart.util.DartClassResolveResult.clone(DartClassResolveResult.java:32)
	at com.jetbrains.lang.dart.util.DartClassResolveResult.create(DartClassResolveResult.java:65)
	at com.jetbrains.lang.dart.util.DartResolveUtil.getDartClassResolveResult(DartResolveUtil.java:774)
	at com.jetbrains.lang.dart.util.DartResolveUtil.tryFindTypeAndResolveClass(DartResolveUtil.java:965)
	at com.jetbrains.lang.dart.util.DartResolveUtil.getDartClassResolveResult(DartResolveUtil.java:777)
	at com.jetbrains.lang.dart.util.DartResolveUtil.getDartClassResolveResult(DartResolveUtil.java:770)
	at com.jetbrains.lang.dart.psi.impl.DartReferenceImpl.resolveDartClass(DartReferenceImpl.java:148)
	at com.jetbrains.lang.dart.resolve.DartResolver.resolve(DartResolver.java:59)
	at com.jetbrains.lang.dart.resolve.DartResolver.resolve(DartResolver.java:22)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:213)
	at com.jetbrains.lang.dart.psi.impl.DartReferenceImpl.multiResolve(DartReferenceImpl.java:115)
	at com.jetbrains.lang.dart.psi.impl.DartReferenceImpl.resolve(DartReferenceImpl.java:105)
	at com.jetbrains.lang.dart.ide.annotator.DartColorAnnotator.highlightReference(DartColorAnnotator.java:118)
	at com.jetbrains.lang.dart.ide.annotator.DartColorAnnotator.highlightIfDeclarationOrReference(DartColorAnnotator.java:96)
	at com.jetbrains.lang.dart.ide.annotator.DartColorAnnotator.annotate(DartColorAnnotator.java:84)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:159)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:340)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:205)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
[249645642]  ERROR - n.impl.GeneralHighlightingPass - IntelliJ IDEA 14.1.3  Build #IC-141.1010.3 
[249645642]  ERROR - n.impl.GeneralHighlightingPass - Last Action: EditorEnter 
```

**Comment by kmillikin** [comment]
Actually, that stack trace might be a red herring.  More commonly I get a failure to complete 'analysis_updateContent' like this:

```
[ 248661]  ERROR - yzer.DartAnalysisServerService - Operation didn't finish in 1000 ms: analysis_updateContent(/usr/local/[redacted]/dart.git/sdk/pkg/compiler/lib/src/cps_ir/cps_ir_builder_task.dart) 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.runInPooledThreadAndWait(DartAnalysisServerService.java:788)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.updateFilesContent(DartAnalysisServerService.java:266)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerAnnotator.collectInformation(DartAnalysisServerAnnotator.java:100)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerAnnotator.collectInformation(DartAnalysisServerAnnotator.java:37)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectInformationWithProgress(ExternalToolPass.java:99)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
[ 248664]  ERROR - yzer.DartAnalysisServerService - IntelliJ IDEA 14.1.3  Build #IC-141.1010.3 
[ 248665]  ERROR - yzer.DartAnalysisServerService - OS: Linux 
[ 248665]  ERROR - yzer.DartAnalysisServerService - Last Action: EditorBackSpace 
[ 248665]  ERROR - yzer.DartAnalysisServerService - Current Command: Backspace 
[ 249666]  ERROR - yzer.DartAnalysisServerService - Operation didn't finish in 1000 ms: server_shutdown() 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.runInPooledThreadAndWait(DartAnalysisServerService.java:788)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.stopServer(DartAnalysisServerService.java:706)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.updateFilesContent(DartAnalysisServerService.java:274)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerAnnotator.collectInformation(DartAnalysisServerAnnotator.java:100)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerAnnotator.collectInformation(DartAnalysisServerAnnotator.java:37)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectInformationWithProgress(ExternalToolPass.java:99)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
[ 249667]  ERROR - yzer.DartAnalysisServerService - IntelliJ IDEA 14.1.3  Build #IC-141.1010.3 
[ 249667]  ERROR - yzer.DartAnalysisServerService - OS: Linux 
[ 249667]  ERROR - yzer.DartAnalysisServerService - Last Action: EditorBackSpace 
[ 249667]  ERROR - yzer.DartAnalysisServerService - Current Command: Backspace 
```

**Comment by bwilkerson** [comment]
Jaime,

These stack traces are from the IntelliJ plugin. Could you either move this to the IntelliJ issue tracker or get us stack traces from the Dart code? Thanks.

**Comment by alexander-doroshko** [comment]
The error from this issue description (ERROR - n.impl.GeneralHighlightingPass - null 
java.util.ConcurrentModificationException) should be filed to https://youtrack.jetbrains.com/issues/WEB?q=%23dart.

**Comment by kmillikin** [comment]
Sorry @alexander-doroshko, I was on vacation!  Filed https://youtrack.jetbrains.com/issue/WEB-17574.
