### ISSUE TITLE
NSM watching for file changes

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#23671]
NoSuchMethodError: method not found: 'getSourcesWithFullName'
Receiver: null
Arguments: ["/usr/local/google/home/bak/IdeaProjects/Kalle/.idea/workspace.xml"]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ContextManager._handleWatchEvent (package:analysis_server/src/context_manager.dart:614)
#3      ContextManager._createContext.<anonymous closure> (package:analysis_server/src/context_manager.dart:448)

**Comment by danrubel** [comment]
I'm already working in this area, so I'll look into this.
