### ISSUE TITLE
Non-actionable error message in test output "compiled output might require a preamble file"

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#23875]
With CL https://codereview.chromium.org//1244733002 dart2js started failing tests it should pass with the non-actionable error message below.

From http://build.chromium.org/p/client.dart/builders/dart2js-linux-release-minified-1-5-be/builds/11603/steps/dart2js-d8%20tests%20--minified%20--dart2js-batch%20failures/logs/stdio

FAILED: dart2js-d8 release_ia32 isolate/error_at_spawn_test
Expected: Pass 
Actual: Fail
CommandOutput[dart2js]:

stdout:
Hint: When run on the command-line, the compiled output might require a preamble file located in:
  <sdk>/lib/_internal/js_runtime/lib/preambles.

CommandOutput[d8]:

stdout:
unittest-suite-wait-for-done
Invalid argument(s): fast error
Invalid argument(s): fast error
    at dart.d (/mnt/data/b/build/slave/dart2js-linux-release-minified-1-5-be/build/sdk/out/ReleaseIA32/generated_compilations/dart2js-minified-sdk/tests_isolate_error_at_spawn_test/out.js:1122:3)
    at dart.fm (/mnt/data/b/build/slave/dart2js-linux-release-minified-1-5-be/build/sdk/out/ReleaseIA32/generated_compilations/dart2js-minified-sdk/tests_isolate_error_at_spawn_test/out.js:3119:25)
    at cM.dart.cM.$0 (/mnt/data/b/build/slave/dart2js-linux-release-minified-1-5-be/build/sdk/out/ReleaseIA32/generated_compilations/dart2js-minified-sdk/tests_isolate_error_at_spawn_test/out.js:796:23)
    at dart.bq (/mnt/data/b/build/slave/dart2js-linux-release-minified-1-5-be/build/sdk/out/ReleaseIA32/generated_compilations/dart2js-minified-sdk/tests_isolate_error_at_spawn_test/out.js:573:62)
    at cO.dart.cO.$0 (/mnt/data/b/build/slave/dart2js-linux-release-minified-1-5-be/build/sdk/out/ReleaseIA32/generated_compilations/dart2js-minified-sdk/tests_isolate_error_at_spawn_test/out.js:791:3)
    at aC.dart.aC.a4 (/mnt/data/b/build/slave/dart2js-linux-release-minified-1-5-be/build/sdk/out/ReleaseIA32/generated_compilations/dart2js-minified-sdk/tests_isolate_error_at_spawn_test/out.js:674:9)
    at a_.dart.a_.cQ (/mnt/data/b/build/slave/dart2js-linux-release-minified-1-5-be/build/sdk/out/ReleaseIA32/generated_compilations/dart2js-minified-sdk/tests_isolate_error_at_spawn_test/out.js:765:10)
    at dV.dart.dV.by (/mnt/data/b/build/slave/dart2js-linux-release-minified-1-5-be/build/sdk/out/ReleaseIA32/generated_compilations/dart2js-minified-sdk/tests_isolate_error_at_spawn_test/out.js:743:32)
    at dV.dart.dV.bg (/mnt/data/b/build/slave/dart2js-linux-release-minified-1-5-be/build/sdk/out/ReleaseIA32/generated_compilations/dart2js-minified-sdk/tests_isolate_error_at_spawn_test/out.js:746:16)
    at dV.dart.dV.a8 (/mnt/data/b/build/slave/dart2js-linux-release-minified-1-5-be/build/sdk/out/ReleaseIA32/generated_compilations/dart2js-minified-sdk/tests_isolate_error_at_spawn_test/out.js:748:33)

**Comment by sigmundch** [comment]
@iposva-google  - could you clarify a bit? I'm not sure I follow what you are requesting here (besides for what's already covered in #23876).

Note that the logs show that the compiler didn't fail. True - the compiler produces a hint that is not relevant to the test failure, but we always produce that hint when the code uses features that require the preamble file before you run them in d8. As for the d8 failure, I believe that's covered by #23876.

**Comment by yjbanov** [comment]
I actually see it output a warning, not a hint. I therefore cannot use the `--fatal-warnings` option on isolate code, which is perfectly legal (AFAICT).

```
[Warning from Dart2JS on playground|web/src/web_workers/todo/background_index.dart]:
When run on the command-line, the compiled output might require a preamble file located in:
  <sdk>/lib/_internal/js_runtime/lib/preambles.
```

**Comment by sigmundch** [comment]
@yjbanov - I believe that is a mislabeling when pub invokes dart2js during pub-build: pub doesn't have a logging level for "hints", so it provides the messages as warnings even though they are not. It shouldn't affect the `--fatal-warnings` flag (which is internally handled by dart2js).

I just did a small test to verify, but let me know if that is giving you issues.
