### ISSUE TITLE
Investigate code_test.dart on windows: Invalid radix-10 number

### ISSUE THREAD

**Issue by turnidge** [dart-lang/sdk#24038]
FAILED: none-vm release_ia32 service/code_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching build\ReleaseIA32\dart.exe --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=build/ReleaseIA32/packages/ --enable-vm-service:0 E:\b\build\slave\vm-win32-release-be\build\sdk\runtime\observatory\tests\service\code_test.dart --testee-mode
Observatory listening on http://127.0.0.1:52485
** Signaled to run test queries on 52485

Running code_test.dart [1/2]
Breakpoint reached
Running code_test.dart [2/2]
Frame(funcB)
** Killing script
Unexpected exception in service tests: FormatException: Invalid radix-10 number
036FEEA0 #0      int._throwFormatException (dart:core-patch/integers_patch.dart:111)
#1      int._parse (dart:core-patch/integers_patch.dart:101)
#2      int.parse (dart:core-patch/integers_patch.dart:58)
#3      Code._processDisassembly (package:observatory/src/service/object.dart:3353:23)
#4      Code._update (package:observatory/src/service/object.dart:3279:7)
#5      ServiceObject.update (package:observatory/src/service/object.dart:350:5)
#6      ServiceObject.reload.<anonymous closure> (package:observatory/src/service/object.dart:307:11)
#7      _rootRunUnary (dart:async/zone.dart:911)
#8      _CustomZone.runUnary (dart:async/zone.dart:811)
#9      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#11     _Future._completeWithValue (dart:async/future_impl.dart:368)
#12     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#13     _rootRun (dart:async/zone.dart:904)
#14     _CustomZone.run (dart:async/zone.dart:803)
#15     _CustomZone.runGuarded (dart:async/zone.dart:709)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#18     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

stderr:
Unhandled exception:
Uncaught Error: FormatException: Invalid radix-10 number
036FEEA0
Stack Trace:
#0      int._throwFormatException (dart:core-patch/integers_patch.dart:111)
#1      int._parse (dart:core-patch/integers_patch.dart:101)
#2      int.parse (dart:core-patch/integers_patch.dart:58)
#3      Code._processDisassembly (package:observatory/src/service/object.dart:3353:23)
#4      Code._update (package:observatory/src/service/object.dart:3279:7)
#5      ServiceObject.update (package:observatory/src/service/object.dart:350:5)
#6      ServiceObject.reload.<anonymous closure> (package:observatory/src/service/object.dart:307:11)
#7      _rootRunUnary (dart:async/zone.dart:911)
#8      _CustomZone.runUnary (dart:async/zone.dart:811)
#9      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#11     _Future._completeWithValue (dart:async/future_impl.dart:368)
#12     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#13     _rootRun (dart:async/zone.dart:904)
#14     _CustomZone.run (dart:async/zone.dart:803)
#15     _CustomZone.runGuarded (dart:async/zone.dart:709)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#18     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Command[vm]: set DART_CONFIGURATION=ReleaseIA32 & build\ReleaseIA32\dart.exe --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=build/ReleaseIA32/packages/ E:\b\build\slave\vm-win32-release-be\build\sdk\runtime\observatory\tests\service\code_test.dart
Took 0:00:01.170000

Short reproduction command (experimental):
    python tools/test.py -mrelease --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t60 service/code_test

**Comment by turnidge** [comment]
Fixed in cc981c8246e28e21fe84b8ec00b7a2eac9719102.
