### ISSUE TITLE
`Isolate.spawnUri` with a `package:` URI doesn't work if there are no `package:` imports

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24058]
Currently, `Isolate.spawnUri` *mostly* supports spawning isolates against `package:` URIs. However, this fails with a confusing error if there aren't any `package:` imports in the code doing the spawning. For example:

```dart
import 'dart:isolate';

void main() {
  Isolate.spawnUri(Uri.parse('package:path/path.dart'), [], null);
}
```

If you run this script next to a `packages/` directory with a link for `path` or a `.packages` file with an entry for `path`, it produces this error:

```
Unhandled exception:
Uncaught Error: IsolateSpawnException: Unhandled exception:
Unsupported scheme used to locate .packages file: 'package:path/path.dart'.
#0      _handlePackagesReply (dart:_builtin:416)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
Stack Trace:
#0      Isolate._spawnUri (dart:isolate-patch/isolate_patch.dart:364)
#1      Isolate.spawnUri (dart:isolate-patch/isolate_patch.dart:317)
#2      main (file:///usr/local/google/home/nweiz/goog/dart/sdk/test.dart:6:11)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by nex3** [comment]
Note that this also only fails if no `--package-root` or `--packages` parameter is explicitly supplied.

**Comment by lrhn** [comment]
Looks like a VM bug. My guess, from looking at the symptoms, is that if the VM doesn't see any package: import, it doesn't initialize the package resolution (no loading of .packages or finding packages/, which is a perfectly fine optimization). Then it spawns another isolate which inherits the (missing) package resolution and *that* triggers it to try to do package resolution relative to the package:path/path.dart URI script. That fails (you can't find a .packages relative to a packages: URI, that's as specified).

It should probably recognize that the script URI is a package:-URI and initialize package resolution at that point if it hasn't been initialized before, and do that before creating trying to start the new isolate or finding a .packages file for the script.

**Comment by zanderso** [comment]
This issue is a bit old, and I haven't been able to reproduce the error, so I'll go ahead and close it. Please reopen with updated repro instructions if this can still happen. Thanks!

**Comment by nex3** [comment]
I can reproduce this with 1.17.0, but only in a directory where automatic detection of a `packages/` directory or a `.packages` file fails—for example, in `/tmp`.

**Comment by zanderso** [comment]
@nex3 Sorry, I'm a bit confused. If you could be super explicit about the directory layout and command line that cause the error that'd be a big help. Thanks!

**Comment by nex3** [comment]
Here's exactly what I'm running:

```
$ cat >> /tmp/test.dart
import 'dart:isolate';

void main() {
  Isolate.spawnUri(Uri.parse('package:path/path.dart'), [], null);
}
$ dart --version
Dart VM version: 1.17.0 (Mon Jun  6 14:22:45 2016) on "linux_x64"
$ dart /tmp/test.dart 
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: Unhandled exception:
Could not load "package:path/path.dart": Unsupported scheme used to locate .packages file: 'package:path/path.dart'.
#0      _asyncLoadErrorCallback (dart:_builtin:169)
#1      _asyncLoadError (dart:_builtin:597)
#2      _loadPackage (dart:_builtin:638)
#3      _loadPackage.<anonymous closure> (dart:_builtin:654)
#4      _handlePackagesReply (dart:_builtin:495)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
#0      Isolate.spawnUri.<spawnUri_async_body> (dart:isolate-patch/isolate_patch.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _RootZone.runBinary (dart:async/zone.dart:1210)
#3      _FutureListener.handleError (dart:async/future_impl.dart:146)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#6      _Future._completeError (dart:async/future_impl.dart:485)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:56)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      Isolate._spawnCommon.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:439)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by zanderso** [comment]
What is the behavior that you expect in this situation?

**Comment by nex3** [comment]
I'd expect an error message that describes the actual error—something like "Could not resolve a package location for base at file:///tmp/test.dart".
