### ISSUE TITLE
dart2js: internal broken invariant about constant computation

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#24148]
This test crashes with a broken invariant when running the vm in checked mode:
```bash
python tools/test.py --host-checked -mrelease -cdart2js -rd8 -t960 language/deferred_constraints_constants_test/default_argument1
```

The error is:
```
FAILED: dart2js-d8 release_ia32 language/deferred_constraints_constants_test/default_argument1
Expected: Pass 
Actual: Crash
Compile-time error expected.
CommandOutput[dart2js]:

stdout:
out/ReleaseIA32/generated_tests/language/deferred_constraints_constants_test_default_argument1.dart:
Warning: 
****************************************************************
* WARNING: dart:mirrors support in dart2js is experimental,
*          and not recommended.
*          This implementation of mirrors is incomplete,
*          and often greatly increases the size of the generated
*          JavaScript code.
*
* Your app imports dart:mirrors via:
*   deferred_constraints_constants_test_default_argument1.dart => dart:mirrors
*
* You can disable this message by using the --enable-experimental-mirrors
* command-line flag.
*
* To learn what to do next, please visit:
*    http://dartlang.org/dart2js-reflection
****************************************************************


out/ReleaseIA32/generated_tests/language/deferred_constraints_constants_test_default_argument1.dart:23:3:
Error: A deferred class cannot be used to create a compile-time constant.
  const lib.Const() /// default_argument1: compile-time error
  ^^^^^^^^^^^^^^^^^
out/ReleaseIA32/generated_tests/language/deferred_constraints_constants_test_default_argument1.dart:23:3:
Error: A deferred class cannot be used to create a compile-time constant.
  const lib.Const() /// default_argument1: compile-time error
  ^^^^^^^^^^^^^^^^^
out/ReleaseIA32/generated_tests/language/deferred_constraints_constants_test_default_argument1.dart:22:10:
Internal Error: Constant has already been computed for parameter(f1#a). Existing constant: const Const(), New constant: .
void f1({a:
         ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Assertion failure: Constant has already been computed for parameter(f1#a). Existing constant: const Const(), New constant: .
#0      invariant (/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:56:5)
#1      FormalElementX&PatchMixin&ConstantVariableMixin.constant= (/sdk/pkg/compiler/lib/src/elements/modelx.dart:1256:12)
#2      ResolverVisitor.setupFunction.<anonymous closure>.<anonymous closure> (/sdk/pkg/compiler/lib/src/resolution/members.dart:491:19)
#3      List.forEach (dart:core-patch/array.dart:77)
#4      FunctionSignatureCommon.forEachOptionalParameter (/sdk/pkg/compiler/lib/src/elements/common.dart:448:24)
#5      ResolverVisitor.setupFunction.<anonymous closure> (/sdk/pkg/compiler/lib/src/resolution/members.dart:489:26)
#6      Compiler.withCurrentElement (/sdk/pkg/compiler/lib/src/compiler.dart:386:15)
#7      ResolutionEnqueuer.emptyDeferredTaskQueue (/sdk/pkg/compiler/lib/src/enqueue.dart:873:16)
#8      ResolutionEnqueuer.onQueueEmpty (/sdk/pkg/compiler/lib/src/enqueue.dart:866:5)
#9      Enqueuer.forEach (/sdk/pkg/compiler/lib/src/enqueue.dart:699:12)
#10     Compiler.processQueue (/sdk/pkg/compiler/lib/src/compiler.dart:1213:11)
#11     Compiler.compileLoadedLibraries (/sdk/pkg/compiler/lib/src/compiler.dart:1081:5)
#12     Compiler.runCompiler.<anonymous closure> (/sdk/pkg/compiler/lib/src/compiler.dart:990:7)
#13     _RootZone.runUnary (dart:async/zone.dart:1165)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#16     _Future._completeWithValue (dart:async/future_impl.dart:376)
#17     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#19     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)



Command[dart2js]: DART_CONFIGURATION=ReleaseIA32 sdk/bin/dart2js_developer --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --package-root=out/ReleaseIA32/packages/ sdk/out/ReleaseIA32/generated_tests/language/deferred_constraints_constants_test_default_argument1.dart --out=sdk/out/ReleaseIA32/generated_compilations/dart2js/multitest_language_deferred_constraints_constants_test_default_argument1/out.js
Took 0:00:04.438000

Short reproduction command (experimental):
    python tools/test.py --host-checked -mrelease -cdart2js -rd8 -t960 language/deferred_constraints_constants_test/default_argument1



===
=== 1 test failed
===


[00:06 | 100% | +    0 | -    1]

```

**Comment by sigmundch** [comment]
@johnniwinther could you take a look? I'm guessing you'd have a good idea of where this could be coming from

**Comment by johnniwinther** [comment]
I'll look into it.

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org//1336303002
