### ISSUE TITLE
InterfaceTypeSuggestionBuilder exception

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24270]
Dart analysis server, SDK version 1.12.0-dev.5.10, server version 1.9.0, FATAL error: The null object does not have a getter 'library'.

NoSuchMethodError: method not found: 'library'
…

Receiver: null
Arguments: []
#0 Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1 Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2 InterfaceTypeSuggestionBuilder.suggestionsFor (package:analysis_server/src/services/completion/suggestion_builder.dart:422)
#3 _PrefixedIdentifierSuggestionBuilder.visitVariableElement (package:analysis_server/src/services/completion/prefixed_element_contributor.dart:435)
#4 GeneralizingElementVisitor.visitLocalElement (package:analyzer/src/generated/element.dart:5625)
#5 GeneralizingElementVisitor.visitParameterElement (package:analyzer/src/generated/element.dart:5646)
#6 ParameterElementImpl.accept (package:analyzer/src/generated/element.dart:8783)
#7 _PrefixedIdentifierSuggestionBuilder.computeFull (package:analysis_server/src/services/completion/prefixed_element_contributor.dart:372)
#8 PrefixedElementContributor.computeFull (package:analysis_server/src/services/completion/prefixed_element_contributor.dart:48)
#9 DartCompletionManager.computeFull.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:204)
#10 CompletionPerformance.logElapseTime (package:analysis_server/src/services/completion/completion_manager.dart:167)
#11 DartCompletionManager.computeFull.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:203)
#12 List.forEach (dart:core-patch/growable_array.dart:234)
#13 DartCompletionManager.computeFull.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:199)
#14 CompletionPerformance.logElapseTime (package:analysis_server/src/services/completion/completion_manager.dart:167)
#15 DartCompletionManager.computeFull.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:193)

**Comment by danrubel** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/24630
