### ISSUE TITLE
Exception thrown when making getVM vmservice RPC

### ISSUE THREAD

**Issue by austincummings** [dart-lang/sdk#24301]
When using the vmservice with DartVM version 1.12.0 on Linux 64-bit and executing the following code I get the exception shown below in the target VM. I also can't seem to make any more RPC requests after the exception is thrown.

### Code
```dart
logger.info('Connecting to VM service');
var socket = await WebSocket.connect(uri);
logger.info('Connected $socket');
rpcClient = new rpc.Client(socket);
rpcClient.listen();

logger.info('Created $rpcClient');
logger.info('sending getVersion request');
var response = await rpcClient.sendRequest('getVersion');
logger.info(response);

logger.info('sending getVM request');
response = await rpcClient.sendRequest('getVM'); // Exception is thrown in the target VM after this call
logger.info(response);
```

### Exception
```
vm-service: Error: Unhandled exception:
Uncaught Error: type 'List' is not a subtype of type 'Map' of 'other'.
Stack Trace:
#0      _HashVMBase&MapMixin.addAll (dart:collection/maps.dart:57)
#1      Message.Message.fromJsonRpc (message.dart:40:14)
#2      WebSocketClient.onWebSocketMessage (server.dart:36:29)
#3      WebSocketClient.WebSocketClient.<anonymous closure> (server.dart:15:32)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#7      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:736)
#8      _StreamController._add (dart:async/stream_controller.dart:608)
#9      _StreamController.add (dart:async/stream_controller.dart:554)
#10     _WebSocketImpl._WebSocketImpl._fromSocket.<anonymous closure> (dart:io/websocket_impl.dart:871)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#14     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#15     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#16     _WebSocketProtocolTransformer._messageFrameEnd (dart:io/websocket_impl.dart:289)
#17     _WebSocketProtocolTransformer.add (dart:io/websocket_impl.dart:189)
#18     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#19     _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#22     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:736)
#23     _StreamController._add (dart:async/stream_controller.dart:608)
#24     _StreamController.add (dart:async/stream_controller.dart:554)
#25     _Socket._onData (dart:io-patch/socket_patch.dart:1793)
#26     _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#29     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:736)
#30     _StreamController._add (dart:async/stream_controller.dart:608)
#31     _StreamController.add (dart:async/stream_controller.dart:554)
#32     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1344)
#33     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:728)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#35     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by austincummings** [comment]
Found out why this was happening. Turns out I should've been passing a `Map` in as the params rather than a `List`.
