### ISSUE TITLE
dart2js: assert_with_message_test fails in minified code

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#24393]
The minified interceptor name for JSNull is being rejected, leading to the evaluation of null.constructor.
This happens in the formatting of the TypeError for a failed boolean conversion for the case when the assertion expression evaluates to non-bool.
The null deref is trapped an converted to a NullError.

Seems related to: https://github.com/dart-lang/sdk/issues/19137

----
@@@BUILD_STEP dart2js_extra-drt tests --minified --dart2js-batch --csp --checked failures@@@

FAILED: dart2js-drt-checked release_ia32 dart2js_extra/assert_with_message_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[dart2js]:
CommandOutput[content_shell]:

stdout:
#READY
CONSOLE MESSAGE: line 78: {
  "type": "debug",
  "value": "test_controller.js started",
  "timestamp": 0
}
CONSOLE MESSAGE: line 78: {
  "type": "print",
  "value": "dart-calling-main",
  "timestamp": 0.064
}
CONSOLE MESSAGE: line 78: {
  "type": "sync_exception",
  "value": "Exception: Expect.isTrue(false, 'name: <<NullError: method not found: 'constructor' on null>> (F) is TypeError') fails.\nStack: Expect.isTrue(false, 'name: <<NullError: method not found: 'constructor' on null>> (F) is TypeError') fails.\n    at dart.d (http://127.0.0.1:41436/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:682:3)\n    at dart.aB (http://127.0.0.1:41436/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1510:24)\n    at dart.aC (http://127.0.0.1:41436/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1509:3)\n    at ak.dart.ak.$2 (http://127.0.0.1:41436/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1295:3)\n    at dart.c5 (http://127.0.0.1:41436/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1242:3)\n    at dart.bw (http://127.0.0.1:41436/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1266:3)\n    at dartMainRunner (http://127.0.0.1:41436/root_dart/tools/testing/dart/test_controller.js:311:5)\n    at http://127.0.0.1:41436/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1638:55\n    at init.currentScript (http://127.0.0.1:41436/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1634:55)\n    at http://127.0.0.1:41436/root_build/generated_compilations/dart2js-checked-minified-csp-sdk/tests_compiler_dart2js_extra_assert_with_message_test/test.js:1637:84",
  "timestamp": 0.092
}

**Comment by rakudrama** [comment]
Fixed: https://github.com/dart-lang/sdk/commit/5612c202a02e2f39dec8914aa74661d813a92ce5
