### ISSUE TITLE
LocalReferenceContributor exception

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24509]
Dart analysis server, SDK version 1.13.0-edge.0b01edac173d9e10422ce1ef530482e9d1ab1bd3, server version 1.9.0, 
```
FATAL error: RangeError: Invalid value: Not in range 0..5489, inclusive: 6012 
#0 _StringBase.startsWith (dart:core-patch/string_patch.dart:305) 
#1 _LocalVisitor._LocalVisitor (package:analysis_server/src/services/completion/local_reference_contributor.dart:362) 
#2 LocalReferenceContributor.computeFast (package:analysis_server/src/services/completion/local_reference_contributor.dart:35) 
#3 DartCompletionManager.computeFast. . .  (package:analysis_server/src/services/completion/dart_completion_manager.dart:180) 
#4 CompletionPerformance.logElapseTime (package:analysis_server/src/services/completion/completion_manager.dart:165) 
#5 DartCompletionManager.computeFast. .  (package:analysis_server/src/services/completion/dart_completion_manager.dart:179) 
#6 ListMixin._filter (dart:collection/list.dart:282) 
#7 Object&ListMixin.removeWhere (dart:collection/list.dart:268) 
#8 DartCompletionManager.computeFast.  (package:analysis_server/src/services/completion/dart_completion_manager.dart:178) 
#9 CompletionPerformance.logElapseTime (package:analysis_server/src/services/completion/completion_manager.dart:165) 
#10 DartCompletionManager.computeFast (package:analysis_server/src/services/completion/dart_completion_manager.dart:146) 
```

**Comment by danrubel** [comment]
It appears that the replacement offset for the requested completion is outside the current source range, meaning that what the client and server do not agree on what content is being edited. One possibility is that the client requested a code completion before updating the buffer content. I'll add guard code to ensure that the replacement range and offset is within the source bounds, but this does not address the underlying problem.

**Comment by danrubel** [comment]
Strike that. It appears I'm using the wrong API to get the source. Fixing.
