### ISSUE TITLE
SplitIndexStore.aboutToIndex(context, object) is given null context sometimes

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24629]
This probably happens when CompilationUnitElement of the CompilationUnit is null.
But we should index only fully resolved units.

Possible reasons:

1. We try to index a not fully resolved unit.
2. At the time when we add index operation the unit is fully resolved, but by the time when we begin indexing it, resolution information is removed.

For now https://codereview.chromium.org/1418513002/ adds a null check.

**Comment by alexander-doroshko** [comment]
I've seen the related exception as well. It happened after closing one WebStorm project and opening another one.
```
Dart analysis server, SDK version 1.13.0-dev.7.3, server version 1.12.0, error: The null object does not have a getter 'isDisposed'.

NoSuchMethodError: method not found: 'isDisposed'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      SplitIndexStore.aboutToIndex (package:analysis_server/src/services/index/store/split_store.dart:816)
#3      LocalIndex.index (package:analysis_server/src/services/index/local_index.dart:71)
#4      _DartIndexOperation.perform.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:464)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:149)
#6      _DartIndexOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:460)
#7      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:790)
#8      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#9      _rootRun (dart:async/zone.dart:903)
#10     _CustomZone.run (dart:async/zone.dart:802)
#11     _CustomZone.runGuarded (dart:async/zone.dart:708)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#13     _rootRun (dart:async/zone.dart:907)
#14     _CustomZone.run (dart:async/zone.dart:802)
#15     _CustomZone.runGuarded (dart:async/zone.dart:708)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

**Comment by scheglov** [comment]
I tried to close and open projects many times, but I was not able to reproduce it.
Must have been fixed by one of the other fixes we have applied over the several previous days.
