### ISSUE TITLE
Exceptions in Analyzer in WebStorm (latest EAP)

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#24639]
If you can't make anything of this stack trace just close the issue.
I don't know exact steps to reproduce but had this already earlier today.

```
15:53:28 Throwable: Dart analysis server, SDK version 1.13.0-edge.9f02e64578d0e7d849e3a24abdfe90e60bc89487, server version 1.12.0, FATAL error: The null object does not have a method 'setState'.

NoSuchMethodError: method not found: 'setState'
Receiver: null
Arguments: [Instance of 'ListResultDescriptorImpl', Instance of 'CacheState']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      HtmlWorkManager._invalidateAllLocalResolutionInformation (package:analyzer/src/task/html_work_manager.dart:235)
#3      HtmlWorkManager.onAnalysisOptionsChanged (package:analyzer/src/task/html_work_manager.dart:160)
#4      AnalysisContextImpl.analysisOptions= (package:analyzer/src/context/context.dart:289)
#5      ContextManagerImpl.processOptionsForContext (package:analysis_server/src/context_manager.dart:515)
#6      ContextManagerImpl._checkForAnalysisOptionsUpdate (package:analysis_server/src/context_manager.dart:7... (show balloon)
15:54:39 JetBrains IDE Support extension for Dartium: Please ensure that JetBrains IDE Support extension is installed and enabled in Dartium.
15:57:40 Throwable: Dart analysis server, SDK version 1.13.0-edge.9f02e64578d0e7d849e3a24abdfe90e60bc89487, server version 1.12.0, FATAL error: The null object does not have a method 'setState'.

NoSuchMethodError: method not found: 'setState'
Receiver: null
Arguments: [Instance of 'ListResultDescriptorImpl', Instance of 'CacheState']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      HtmlWorkManager._invalidateAllLocalResolutionInformation (package:analyzer/src/task/html_work_manager.dart:235)
#3      HtmlWorkManager.onSourceFactoryChanged (package:analyzer/src/task/html_work_manager.dart:180)
#4      AnalysisContextImpl.sourceFactory= (package:analyzer/src/context/context.dart:414)
#5      ServerContextManagerCallbacks.updateContextPackageUriResolver (package:analysis_server/src/analysis_server.dart:1482)
#6      ContextManagerImpl._checkForPackagespecUpdate (package:analysis_server/src/context_man... (show balloon)
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/1414733006

**Comment by scheglov** [comment]
Fixed.
https://github.com/dart-lang/sdk/commit/58937b50ef2f81f441318f1dcdadf5a107b33533

**Comment by scheglov** [comment]
Merge request.
https://github.com/dart-lang/sdk/issues/24640
