### ISSUE TITLE
Precompilation: crash on language/issue21159_test.dart on simulators

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#24659]
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xf716eb40 (LWP 17239)]
dart::Simulator::GetShiftRm (this=0x89cda58, instr=0xf716f468, carry_out=0xf70ef0b0)
    at runtime/vm/simulator_arm.cc:1260
1260	int32_t Simulator::GetShiftRm(Instr* instr, bool* carry_out) {
(gdb) bt
#0  dart::Simulator::GetShiftRm (this=0x89cda58, instr=0xf716f468, carry_out=0xf70ef0b0)
    at runtime/vm/simulator_arm.cc:1260
#1  0x083e84c4 in dart::Simulator::DecodeType01 (this=this@entry=0x89cda58, instr=instr@entry=0xf716f468)
    at runtime/vm/simulator_arm.cc:2043
#2  0x083e1774 in dart::Simulator::InstructionDecode (this=this@entry=0x89cda58, instr=0xf716f468)
    at runtime/vm/simulator_arm.cc:3610
#3  0x083e9abc in dart::Simulator::Execute (this=this@entry=0x89cda58) at runtime/vm/simulator_arm.cc:3664
#4  0x083e9c60 in dart::Simulator::Call (this=0x89cda58, entry=entry@entry=-149490608, 
    parameter0=parameter0@entry=-152060224, parameter1=parameter1@entry=-152060232, 
    parameter2=parameter2@entry=-152060240, parameter3=parameter3@entry=-153090968, 
    fp_return=fp_return@entry=false, fp_args=fp_args@entry=false) at runtime/vm/simulator_arm.cc:3788
#5  0x081f6adc in dart::DartEntry::InvokeFunction (function=..., arguments=..., arguments_descriptor=...)
    at runtime/vm/dart_entry.cc:109
#6  0x081f7862 in dart::DartEntry::InvokeFunction (function=..., arguments=...)
    at runtime/vm/dart_entry.cc:29
#7  0x081f84de in dart::DartEntry::InvokeClosure (arguments=..., arguments_descriptor=...)
    at runtime/vm/dart_entry.cc:175
#8  0x081f8579 in dart::DartEntry::InvokeClosure (arguments=..., arguments_descriptor=...)
    at runtime/vm/dart_entry.cc:182
#9  0x081f8579 in dart::DartEntry::InvokeClosure (arguments=..., arguments_descriptor=...)
    at runtime/vm/dart_entry.cc:182
#10 0x081f8579 in dart::DartEntry::InvokeClosure (arguments=..., arguments_descriptor=...)
    at runtime/vm/dart_entry.cc:182
#11 0x081f8579 in dart::DartEntry::InvokeClosure (arguments=..., arguments_descriptor=...)
    at runtime/vm/dart_entry.cc:182
#12 0x081f8579 in dart::DartEntry::InvokeClosure (arguments=..., arguments_descriptor=...)
    at runtime/vm/dart_entry.cc:182
#13 0x081f8579 in dart::DartEntry::InvokeClosure (arguments=..., arguments_descriptor=...)
    at runtime/vm/dart_entry.cc:182
#14 0x081f8579 in dart::DartEntry::InvokeClosure (arguments=..., arguments_descriptor=...)
    at runtime/vm/dart_entry.cc:182
#15 0x081f8579 in dart::DartEntry::InvokeClosure (arguments=..., arguments_descriptor=...)
...

**Comment by rmacnak-google** [comment]
5111482ab9bfac1f3e27124efb182ae7068a1b94, 1481dde8624043fa0e230bcd1d9cd6fcef2c95bc
