### ISSUE TITLE
Precompilation: crash on language/large_class_declaration_test

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#24673]
runtime/vm/assembler_mips.h:67: error: expected: Utils::IsInt(kImmBits, offset_)
[New Thread 0xf726fb40 (LWP 29633)]
[New Thread 0xf7c8db40 (LWP 29632)]

Program received signal SIGABRT, Aborted.
0xf7fdb440 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fdb440 in __kernel_vsyscall ()
#1  0xf7cbf607 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7cc2a33 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x081d6755 in dart::DynamicAssertionHelper::Fail (this=this@entry=0xffffb954, 
    format=format@entry=0x8763928 "expected: %s") at runtime/platform/assert.cc:41
#4  0x0829f730 in encoding (this=0xffffb9b4) at runtime/vm/assembler_mips.h:67
#5  dart::Assembler::EmitLoadStore (this=0xffffbbb0, opcode=dart::LW, rt=dart::R2, addr=...)
    at runtime/vm/assembler_mips.h:1673
#6  0x0829786e in lw (addr=..., rt=dart::R2, this=<optimized out>) at runtime/vm/assembler_mips.h:672
#7  dart::FlowGraphCompiler::GenerateInlinedGetter (this=this@entry=0xffffbcc8, offset=80004)
    at runtime/vm/flow_graph_compiler_mips.cc:967
#8  0x0828c573 in dart::FlowGraphCompiler::TryIntrinsify (this=this@entry=0xffffbcc8)
    at runtime/vm/flow_graph_compiler.cc:1050
#9  0x08297e7c in dart::FlowGraphCompiler::CompileGraph (this=this@entry=0xffffbcc8)
    at runtime/vm/flow_graph_compiler_mips.cc:1043

**Comment by rmacnak-google** [comment]
7c44ffb0cd737916faa5cf33f764c50c185b2828
