### ISSUE TITLE
Precompilation: standalone/io/web_socket_test failing

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#24674]
Unhandled exception:
Expect.equals(expected: <1005>, actual: <null>) fails.
#0      Expect._fail (package:expect/expect.dart:385:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      SecurityConfiguration.checkCloseStatus (file:///usr/local/google/home/rmacnak/dart1/sdk/tests/standalone/io/web_socket_test.dart:56:12)
#3      SecurityConfiguration.testRequestResponseClientCloses.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/rmacnak/dart1/sdk/tests/standalone/io/web_socket_test.dart:100:17)

**Comment by whesse** [comment]
See also #26814
