### ISSUE TITLE
RangeError in local reference contributor

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24718]
Dart analysis server, SDK version 1.13.0-edge.76b7203c198dbfbd34dc57829fdbc7d687143c2c, server version 1.12.0, FATAL error: RangeError: Invalid value: Not in range 0..2687, inclusive: 2740
```
#0      _StringBase.startsWith (dart:core-patch/string_patch.dart:305)
#1      _LocalVisitor._LocalVisitor (package:analysis_server/src/services/completion/local_reference_contributor.dart:362)
#2      LocalReferenceContributor.computeFast (package:analysis_server/src/services/completion/local_reference_contributor.dart:35)
#3      DartCompletionManager.computeFast.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:181)
#4      CompletionPerformance.logElapseTime (package:analysis_server/src/services/completion/completion_manager.dart:165)
#5      DartCompletionManager.computeFast.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:180)
#6      ListMixin._filter (dart:collection/list.dart:282)
#7      Object&ListMixin.removeWhere (dart:collection/list.dart:268)
#8      DartCompletionManager.computeFast.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:179)
#9      CompletionPerformance.logElapseTime (package:analysis_server/src/services/completion/completion_manager.dart:165)
#10     DartCompletionManager.computeFast (package:analysis_server/src/services/completion/dart_completion_manager.dart:147)
#11     DartCompletionManager.computeSuggestions.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:240)
#12     CompletionPerformance.logElapseTime (package:analysis_server/src/services/completion/completion_manager.dart:165)
#13     DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart_completion_manager.dart:239)
#14     CompletionManager.results.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/completion/completion_manager.dart:108)
#15     _rootRun (dart:async/zone.dart:903)
#16     _CustomZone.run (dart:async/zone.dart:802)
#17     _CustomZone.runGuarded (dart:async/zone.dart:708)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#19     _rootRun (dart:async/zone.dart:907)
#20     _CustomZone.run (dart:async/zone.dart:802)
#21     _CustomZone.runGuarded (dart:async/zone.dart:708)
#22     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#24     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by danrubel** [comment]
Fixed in [LocalReferenceContributor](https://github.com/dart-lang/sdk/blob/1.14.0-dev.6.0/pkg/analysis_server/lib/src/services/completion/dart/local_reference_contributor.dart#L97) as part of move to new completion API
