### ISSUE TITLE
exception from analysis server

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24719]
This exception was reported by the AS over its logging mechanism:

```
NoSuchMethodError: method not found: 'isDisposed'
Receiver: null
Arguments: []
C:\projects\dartlang\web\entry.dart.js:49964 warning • analysis-server: #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      SplitIndexStore.aboutToIndex (package:analysis_server/src/services/index/store/split_store.dart:816)
#3      LocalIndex.index (package:analysis_server/src/services/index/local_index.dart:71)
#4      _DartIndexOperation.perform.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:464)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:149)
#6      _DartIndexOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:460)
#7      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:790)
#8      Future.Future.<anonymous closure> (dart:async/future.dart:118)
```

I saw several instances of this exception over a few minutes. This is for the latest dev sdk release (`1.13.0-dev.7.3`), on windows.

**Comment by scheglov** [comment]
Already fixed.
 https://codereview.chromium.org/1418513002
