### ISSUE TITLE
standalone/io/http_proxy_configuration_test failing with --noopt

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24787]
FAILED: none-vm release_x64 standalone/io/http_proxy_configuration_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.equals(at index 0: Expected <DIRECT>, Found: <PROXY www.p...>) fails.
#0      Expect._fail (package:expect/expect.dart:385:5)
#1      Expect.equals (package:expect/expect.dart:99:9)
#2      expectDirect (file:///media/SSD/dartgit2/sdk/tests/standalone/io/http_proxy_configuration_test.dart:15:10)
#3      main (file:///media/SSD/dartgit2/sdk/tests/standalone/io/http_proxy_configuration_test.dart:152:3)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --noopt --ignore-unrecognized-flags --package-root=out/ReleaseX64/packages/ /media/SSD/dartgit2/sdk/tests/standalone/io/http_proxy_configuration_test.dart
Took 0:00:01.155000

Short reproduction command (experimental):
    python tools/test.py -mrelease --noopt --exclude-suite pkg -t60 standalone/io/http_proxy_configuration_test

**Comment by fsc8000** [comment]
Duplicate of #24789
