### ISSUE TITLE
exception from analysis server

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24790]
This exception was reported by the analysis server:

```
The null object does not have a method 'getValue'.

NoSuchMethodError: method not found: 'getValue'
Receiver: null
Arguments: [Instance of 'ResultDescriptorImpl']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      AnalysisContextImpl.isServerLibrary (package:analyzer/src/context/context.dart:1052)
#3      ExecutionDomainHandler._fileAnalyzed.<anonymous closure> (package:analysis_server/src/domain_execution.dart:177)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
```

**Comment by devoncarew** [comment]
(from the latest dev channel release: Dart VM version: 1.13.0-dev.7.4)

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1426943005/
