### ISSUE TITLE
Exception when associating an existing element model with an AST

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#24831]
We have seen an exception when associating an existing element model with an AST:

NoSuchMethodError: method not found: 'accessors'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      DeclarationResolver.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:2127)

The line number is wrong, but the exception is being thrown on this line:

        PropertyAccessorElement accessor =
            _findIdentifier(_enclosingClass.accessors, methodName);

It appears that when we visited the class we didn't find an element for it:

      _enclosingClass = _findIdentifier(_enclosingUnit.types, className);

I can think of two possibilities:
1. We might have an element model in the cache that doesn't correspond to the structure of the AST. This could happen if we are not invalidating the cache correctly.
2. The element model might not have gotten it's offsets updated when the content of the file was modified. This could happen if incremental resolution didn't get the element model's offsets updated.

**Comment by bwilkerson** [comment]
The DeclarationResolver has been re-worked so that this kind of error will result in marking sources as being in ERROR so that (a) server won't crash and (b) they will be re-analyzed the next time the file changes.
