### ISSUE TITLE
Exceptions during constant evaluation and validation

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#24863]
The following 2 exceptions were reported by @MikeMitterer. It appears that the analysis server stops sending navigation and completion information after these exceptions have occurred (which might be a separate issue).

Unexpected exception while performing ComputeConstantValueTask for element dynamic _BYTES_PER_WORD in
source /Users/mikemitterer/.pub-cache/hosted/pub.dartlang.org/crypto-0.9.0/lib/src/hash_utils.dart
#0 AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1 AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2 AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4 AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1098)
#5 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:366)
#8 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:793)
#9 Future.Future. (dart:async/future.dart:118)
#10 _rootRun (dart:async/zone.dart:903)
#11 _CustomZone.run (dart:async/zone.dart:802)
#12 _CustomZone.runGuarded (dart:async/zone.dart:708)
#13 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#14 _rootRun (dart:async/zone.dart:907)
#15 _CustomZone.run (dart:async/zone.dart:802)
#16 _CustomZone.runGuarded (dart:async/zone.dart:708)
#17 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#18 Timer._createTimer. (dart:async-patch/timer_patch.dart:16)
#19 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
Caused by The null object does not have a getter 'declaredVariables'. NoSuchMethodError: method not found:
'declaredVariables' Receiver: null Arguments: []
#0 Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1 Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2 ComputeConstantValueTask.internalPerform (package:analyzer/src/task/dart.dart:1705)
#3 AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#4 AnalysisTask.perform (package:analyzer/task/model.dart:210)
#5 AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#6 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#7 AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1098)
#8 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#9 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#10 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:366)
#11 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:793)
#12 Future.Future. (dart:async/future.dart:118)
#13 _rootRun (dart:async/zone.dart:903)
#14 _CustomZone.run (dart:async/zone.dart:802)
#15 _CustomZone.runGuarded (dart:async/zone.dart:708)
#16 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#17 _rootRun (dart:async/zone.dart:907)
#18 _CustomZone.run (dart:async/zone.dart:802)
#19 _CustomZone.runGuarded (dart:async/zone.dart:708)
#20 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#21 Timer._createTimer. (dart:async-patch/timer_patch.dart:16)
#22 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#23 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

Unexpected exception while performing VerifyUnitTask for source /Users/mikemitterer/.pub-
cache/hosted/pub.dartlang.org/intl-0.11.12/lib/src/intl/bidi_formatter.dart
#0 AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1 AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2 AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4 AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1098)
#5 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:366)
#8 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:793)
#9 Future.Future. (dart:async/future.dart:118)
#10 _rootRun (dart:async/zone.dart:903)
#11 _CustomZone.run (dart:async/zone.dart:802)
#12 _CustomZone.runGuarded (dart:async/zone.dart:708)
#13 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#14 _rootRun (dart:async/zone.dart:907)
#15 _CustomZone.run (dart:async/zone.dart:802)
#16 _CustomZone.runGuarded (dart:async/zone.dart:708)
#17 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#18 Timer._createTimer. (dart:async-patch/timer_patch.dart:16)
#19 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
Caused by The null object does not have a getter 'context'. NoSuchMethodError: method not found: 'context'
Receiver: null Arguments: []
#0 Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1 Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2 ConstantVerifier.ConstantVerifier (package:analyzer/src/generated/resolver.dart:896)
#3 VerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:4603)
#4 AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#5 AnalysisTask.perform (package:analyzer/task/model.dart:210)
#6 AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#7 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#8 AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1098)
#9 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#10 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#11 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:366)
#12 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:793)
#13 Future.Future. (dart:async/future.dart:118)
#14 _rootRun (dart:async/zone.dart:903)
#15 _CustomZone.run (dart:async/zone.dart:802)
#16 _CustomZone.runGuarded (dart:async/zone.dart:708)
#17 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#18 _rootRun (dart:async/zone.dart:907)
#19 _CustomZone.run (dart:async/zone.dart:802)
#20 _CustomZone.runGuarded (dart:async/zone.dart:708)
#21 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#22 Timer._createTimer. (dart:async-patch/timer_patch.dart:16)
#23 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#24 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

**Comment by bwilkerson** [comment]
Didn't realize the e-mail I got this from was another issue.
