### ISSUE TITLE
Exception during .analysis_option analysis

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24911]
See https://github.com/JetBrains/intellij-plugins/pull/297#issuecomment-156424921 for the context.

```
Dart analysis server, SDK version 1.13.0-edge.50aa43569d892b3e395a812cdb2a42e66069c1be, server version 1.12.0, error: Error processing .analysis_options
OptionsFormatException: Expected ':'., <_FileSpan: from <FileLocation: 25 unknown source:3:10> to <FileLocation: 25 unknown source:3:10> "">
#0      AnalysisOptionsProvider.getOptionsFromString (package:analyzer/source/analysis_options_provider.dart:42)
#1      AnalysisOptionsProvider.getOptions (package:analyzer/source/analysis_options_provider.dart:20)
#2      ContextManagerImpl.processOptionsForContext (package:analysis_server/src/context_manager.dart:472)
#3      ContextManagerImpl._checkForAnalysisOptionsUpdate (package:analysis_server/src/context_manager.dart:736)
#4      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1169)
```

**Comment by pq** [comment]
Thanks!

In the absence of a way to annotate options files with their own errors, in our first cut we were capturing parse errors as logged exceptions.  Now that we have a discrete task that collects and reports such errors, this reporting is (at best) redundant and certainly a bit misleading and confusing.  I'll follow-up with a CL to remove that logging.

**Comment by pq** [comment]
Fixed w/ https://github.com/dart-lang/sdk/commit/a8ef8cf84ea0bee8b57f7a37e032af95dd09ea08.
