### ISSUE TITLE
Exception in linter: method not found: 'root'

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24947]
```
2015-11-16 09:55:18,623 [1268999]  ERROR - yzer.DartAnalysisServerService - IntelliJ IDEA 15.0.1  Build #IU-143.382.35 
2015-11-16 09:55:18,623 [1268999]  ERROR - yzer.DartAnalysisServerService - JDK: 1.8.0_45-internal 
2015-11-16 09:55:18,623 [1268999]  ERROR - yzer.DartAnalysisServerService - VM: OpenJDK 64-Bit Server VM 
2015-11-16 09:55:18,623 [1268999]  ERROR - yzer.DartAnalysisServerService - Vendor: Oracle Corporation 
2015-11-16 09:55:18,623 [1268999]  ERROR - yzer.DartAnalysisServerService - OS: Linux 
2015-11-16 09:55:18,623 [1268999]  ERROR - yzer.DartAnalysisServerService - Last Action: ReplaceInPath 
2015-11-16 09:55:18,731 [1269107]   INFO - yzer.DartAnalysisServerService - analysis_getErrors() took too long for file /usr/local/google/home/xxxxx/src/github/bwu_bind_html/lib/bwu_bind_html.dart, restarting daemon 
2015-11-16 09:55:18,753 [1269129]   INFO - yzer.DartAnalysisServerService - analysis_getErrors() took too long for file /usr/local/google/home/xxxxx/src/github/bwu_bind_html/lib/bwu_bind_html.dart, restarting daemon 
2015-11-16 09:55:55,577 [1305953]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: editor for id: editor.preferences.import 
2015-11-16 09:55:55,577 [1305953]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: build for id: gradle.compiler 
2015-11-16 09:57:02,362 [1372738]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.13.0-dev.7.12, server version 1.12.0, error: Task failed: GenerateLintsTask for source /usr/local/google/home/xxxxx/src/github/bwu_bind_html/lib/bwu_bind_html.dart
Unexpected exception while performing GenerateLintsTask for source /usr/local/google/home/xxxxx/src/github/bwu_bind_html/lib/bwu_bind_html.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

Caused by The null object does not have a getter 'root'.

NoSuchMethodError: method not found: 'root'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      Visitor.visitLibraryDirective (package:linter/src/rules/package_prefixed_library_names.dart:86)
#3      DelegatingAstVisitor.visitLibraryDirective.<anonymous closure> (package:analyzer/src/generated/visitors.dart:440)
#4      Iterable.forEach (dart:core/iterable.dart:217)
#5      DelegatingAstVisitor.visitLibraryDirective (package:analyzer/src/generated/visitors.dart:440)
#6      LibraryDirective.accept (package:analyzer/src/generated/ast.dart:11622)
#7      NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#8      CompilationUnit.visitChildren (package:analyzer/src/generated/ast.dart:4974)
#9      DelegatingAstVisitor.visitCompilationUnit (package:analyzer/src/generated/visitors.dart:144)
#10     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968)
#11     GenerateLintsTask.internalPerform (package:analyzer/src/task/dart.dart:2659)
#12     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#13     AnalysisTask.perform (package:analyzer/task/model.dart:210)
#14     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#15     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#16     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#18     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#19     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#20     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#21     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#22     _rootRun (dart:async/zone.dart:903)
#23     _CustomZone.run (dart:async/zone.dart:802)
#24     _CustomZone.runGuarded (dart:async/zone.dart:708)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#26     _rootRun (dart:async/zone.dart:907)
#27     _CustomZone.run (dart:async/zone.dart:802)
#28     _CustomZone.runGuarded (dart:async/zone.dart:708)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#30     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)


#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:196)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)
```

**Comment by pq** [comment]
Thanks!  I've got a quick workaround in place [here](https://codereview.chromium.org/1447123002/) and a bug to track a better long-term fix.  Once this change lands I'll re-publish linter and update `DEPS`.

As a short term, the user should be advised to remove `package_prefixed_library_names` from their list of enabled lints.

**Comment by scheglov** [comment]
@jwren FYI

**Comment by pq** [comment]
Fixed in head; cherry pick request: https://github.com/dart-lang/sdk/issues/24952.
