### ISSUE TITLE
Exception in linter: method not found: 'isApi'

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24949]
```
Caused by The null object does not have a method 'isApi'. NoSuchMethodError: method not found: 'isApi' Receiver: null Arguments: [Instance of 'ClassElementImpl']

#0 Object._noSuchMethod (dart:core-patch/object_patch.dart:42) 
#1 Object.noSuchMethod (dart:core-patch/object_patch.dart:45) 
#2 Visitor.check (package:linter/src/rules/package_api_docs.dart:91:17) 
#3 Visitor.visitCompilationUnitMember (package:linter/src/rules/package_api_docs.dart:116:5) 
#4 GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/src/generated/ast.dart:9051:7) 
#5 GeneralizingAstVisitor.visitClassDeclaration (package:analyzer/src/generated/ast.dart:8855:7) 
#6 DelegatingAstVisitor.visitClassDeclaration. (package:analyzer/src/generated/visitors.dart:115:47) 
#7 Iterable.forEach (dart:core/iterable.dart:217) 
#8 DelegatingAstVisitor.visitClassDeclaration (package:analyzer/src/generated/visitors.dart:115:16) 
#9 ClassDeclaration.accept (package:analyzer/src/generated/ast.dart:4349:41) 
#10 NodeList.accept (package:analyzer/src/generated/ast.dart:12777:20) 
#11 CompilationUnit.visitChildren (package:analyzer/src/generated/ast.dart:4975:21) 
#12 DelegatingAstVisitor.visitCompilationUnit (package:analyzer/src/generated/visitors.dart:144:10) 
#13 CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968:41) 
#14 GenerateLintsTask.internalPerform (package:analyzer/src/task/dart.dart:2667:10) 
#15 AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310:9) 
#16 AnalysisTask.perform (package:analyzer/task/model.dart:210:7) 
#17 AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272:10) 
#18 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247:9) 
#19 AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1105:27) 
#20 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188:15) 
#21 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1103:49) 
#22 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367:37) 
#23 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798:17) 
#24 Future.Future. (dart:async/future.dart:118) 
#25 _rootRun (dart:async/zone.dart:903) 
#26 _CustomZone.run (dart:async/zone.dart:802) 
#27 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#28 _CustomZone.bindCallback. (dart:async/zone.dart:733) 
#29 _rootRun (dart:async/zone.dart:907) 
#30 _CustomZone.run (dart:async/zone.dart:802) 
#31 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#32 _CustomZone.bindCallback. (dart:async/zone.dart:733) 
#33 Timer._createTimer. (dart:async-patch/timer_patch.dart:16) 
#34 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385) 
#35 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

**Comment by pq** [comment]
Fixed in head; cherry pick request: https://github.com/dart-lang/sdk/issues/24952.
