### ISSUE TITLE
Consider communicating when the Analysis Server has crashed/stopped?

### ISSUE THREAD

**Issue by davenotik** [dart-lang/sdk#24982]
It just remains white.

SDK 1.13, WebStorm 11.0.1

See: http://d.pr/i/1hU7W

**Comment by davenotik** [comment]
I chose Reanalyze Dart Sources from the Dart Analysis tab (http://d.pr/i/QCD) and now all my files have gone to white (no analysis).

**Comment by zoechi** [comment]
Do you get any exceptions in the WebStorm event log (red icon at the bottom-right)

**Comment by davenotik** [comment]
No red icon. Opened Event Log manually. Empty. http://d.pr/i/1k117

**Comment by alexander-doroshko** [comment]
Red icon is disabled by default in WebStorm / IntelliJ IDEA release builds. It is enabled in EAPs only. It is possible to enable it by editing `bin/idea.properties` file in IDE installation (`idea.fatal.error.notification=enabled`). Or you can look for exceptions in `idea.log` file (Help | Show Log).

**Comment by davenotik** [comment]
Ok, I'm going to chalk this up to homebrew issues. I returned to my desk this morning and noticed WebStorm reporting that the Dart SDK wasn't configured for the project. In preferences, I noticed the path to the Dart SDK was no longer there. I checked the physical path and lo and behold it no longer existed. I `brew install dart` again and the rest is pasted:

```
DaveMac:woven-app dave$ brew install dart
Warning: dart-lang/dart/dart-1.13.0 already installed, it's just not linked
DaveMac:woven-app dave$ brew link dart
Linking /usr/local/Cellar/dart/1.13.0... 
Error: Could not symlink bin/content_shell
Target /usr/local/bin/content_shell
is a symlink belonging to dartium. You can unlink it:
  brew unlink dartium

To force the link and overwrite all conflicting files:
  brew link --overwrite dart

To list all files that would be deleted:
  brew link --overwrite --dry-run dart
DaveMac:woven-app dave$ brew link --overwrite dart
Linking /usr/local/Cellar/dart/1.13.0... 8 symlinks created
DaveMac:woven-app dave$ brew install dart
Warning: dart-lang/dart/dart-1.13.0 already installed
```
So I had to somehow fix my links. Then the path was there, I told WebStorm about it, and the Analyzer started indexing again.

Here are a few messages from the log, if it helps:
```
2015-11-19 01:57:26,494 [101860694]  ERROR - yzer.DartAnalysisServerService - WebStorm 11.0.1  Build #WS-143.382.36 
2015-11-19 01:57:26,494 [101860694]  ERROR - yzer.DartAnalysisServerService - JDK: 1.8.0_40-release 
2015-11-19 01:57:26,494 [101860694]  ERROR - yzer.DartAnalysisServerService - VM: OpenJDK 64-Bit Server VM 
2015-11-19 01:57:26,494 [101860694]  ERROR - yzer.DartAnalysisServerService - Vendor: JetBrains s.r.o 
2015-11-19 01:57:26,494 [101860694]  ERROR - yzer.DartAnalysisServerService - OS: Mac OS X 
2015-11-19 01:57:26,494 [101860694]  ERROR - yzer.DartAnalysisServerService - Last Action: EditorBackSpace 
2015-11-19 01:57:26,826 [101861026]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.13.0-dev.7.12, server version 1.12.0, error: Failed to handle completion domain request: {clientRequestTime: 1447916246816, params: {file: /Users/dave/Sites/woven-app/tool/crawler.dart, offset: 1611}, method: completion.getSuggestions, id: 15389}
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      TypeProviderImpl._initializeFrom (package:analyzer/src/generated/resolver.dart:14071)
#3      TypeProviderImpl.TypeProviderImpl.forNamespaces (package:analyzer/src/generated/resolver.dart:13935)
#4      BuildTypeProviderTask.internalPerform (package:analyzer/src/task/dart.dart:1546)
#5      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#6      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#7      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#8      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#9      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#11     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#12     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#13     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#14     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#15     _rootRun (dart:async/zone.dart:903)
#16     _CustomZone.run (dart:async/zone.dart:802)
#17     _CustomZone.runGuarded (dart:async/zone.dart:708)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#19     _rootRun (dart:async/zone.dart:907)
#20     _CustomZone.run (dart:async/zone.dart:802)
#21     _CustomZone.runGuarded (dart:async/zone.dart:708)
#22     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#23     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
#0      AnalysisFutureHelper.computeAsync.<anonymous closure> (package:analyzer/src/context/context.dart:1988)
#1      PendingFuture.evaluate (package:analyzer/src/context/context.dart:2093)
#2      AnalysisFutureHelper.computeAsync (package:analyzer/src/context/context.dart:1994)
#3      AnalysisContextImpl.computeResolvedCompilationUnitAsync (package:analyzer/src/context/context.dart:650)
#4      DartCompletionManager.waitForAnalysis (package:analysis_server/src/services/completion/dart_completion_manager.dart:278)
#5      DartCompletionManager.computeFull (package:analysis_server/src/services/completion/dart_completion_manager.dart:202)
#6      DartCompletionManager.computeSuggestions.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:245)
#7      CompletionPerformance.logElapseTime (package:analysis_server/src/services/completion/completion_manager.dart:165)
#8      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart_completion_manager.dart:242)
#9      CompletionManager.results.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/completion/completion_manager.dart:108)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#19     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:192)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)
```

and others like:

```
...
2015-11-19 02:00:34,062 [102048262]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.13.0-dev.7.12, server version 1.12.0, error: Exception from assist contributor: DefaultAssistContributor
Cannot compute RESOLVED_UNIT for /Users/dave/Sites/woven-app/tool/crawler.dart in /Users/dave/Sites/woven-app/tool/crawler.dart
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:666)
...
```

**Comment by davenotik** [comment]
What's odd is the Dart Analysis tab remained. And choosing to analyze brought me those blank results I mentioned. I'll leave this task open, as it'd be nice if the DAS said something like "Dart Analysis Server has crashed. Are you sure you've configured the path to the Dart SDK?", or maybe just disappear? Maybe this is on the Jetbrains side?

**Comment by jwren** [comment]
Filed issue here: https://youtrack.jetbrains.com/issue/WEB-19181

And closing this issue.

**Comment by alexander-doroshko** [comment]
Do DAS exceptions pasted above worth attention?

**Comment by jwren** [comment]
Good question, Konstantin/Brian?
