### ISSUE TITLE
Analysis stuck and reporting old errors even when that code stripped out

### ISSUE THREAD

**Issue by davenotik** [dart-lang/sdk#25012]
I was like what the hell am I doing wrong: http://d.pr/i/1kPze

Lo and behold: http://d.pr/i/i9kp

I had to restart WebStorm to resolve that.

SDK 1.13, WebStorm 11.0.1. I'm sorry, I did not look at the Event Log at the time.

**Comment by alexander-doroshko** [comment]
idea.log may help (Help | Show Log)

**Comment by alexander-doroshko** [comment]
BTW how big is the project? How many pubspec.yaml files? Do you see long 'Dart Analysis...' progress in the IDE status bar?

**Comment by davenotik** [comment]
1 pubspec. Mid-size. Not very big. http://d.pr/i/2XED

This is probably to do w/ it:

```
2015-11-19 18:10:59,055 [  67001]   INFO - yzer.DartAnalysisServerService - analysis_getErrors() took too long for file /Users/dave/Sites/woven-app/lib/src/server/crawler/image_info.dart, restarting daemon 
2015-11-19 18:10:59,057 [  67003]   INFO - yzer.DartAnalysisServerService - analysis_getErrors() took too long for file /Users/dave/Sites/woven-app/lib/src/server/crawler/image_info.dart, restarting daemon 
2015-11-19 18:10:59,057 [  67003]   INFO - yzer.DartAnalysisServerService - analysis_getErrors() took too long for file /Users/dave/Sites/woven-app/lib/src/server/crawler/image_info.dart, restarting daemon 
2015-11-19 18:10:59,057 [  67003]   INFO - yzer.DartAnalysisServerService - analysis_getErrors() took too long for file /Users/dave/Sites/woven-app/lib/src/server/crawler/image_info.dart, restarting daemon 
```

I noticed similar today too, when working in another file:

```
2015-11-20 00:53:50,826 [24238772]   INFO - yzer.DartAnalysisServerService - analysis_getErrors() took too long for file /Users/dave/Sites/woven-app/lib/src/shared/util.dart, restarting daemon 
2015-11-20 00:53:50,826 [24238772]   INFO - yzer.DartAnalysisServerService - analysis_getErrors() took too long for file /Users/dave/Sites/woven-app/lib/src/shared/util.dart, restarting daemon 
2015-11-20 00:57:00,429 [24428375]   INFO - openapi.editor.impl.EditorImpl - Cache hits:12288, total requests:32932,file:///Users/dave/Sites/woven-app/lib/src/shared/util.dart 
```

**Comment by alexander-doroshko** [comment]
'analysis_getErrors() took too long...' is an expected log output, do not worry about it. Any exceptions in log (Help | Show Log)?

**Comment by davenotik** [comment]
Not sure if these are related but I see errors like the below.

I think at least the second one occurs as I'm manually typing out a package path like `import 'package:wo...` sometimes with or without the quotes or the package part (hoping the IDE finds and auto-completes it like it often does for third-party packages.)

```
2015-11-19 15:58:48,812 [152343012]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.13.0, server version 1.12.0, error: Exception from fix contributor: DefaultFixContributor
#2      FixProcessor._addFix_createGetter (package:analysis_server/src/services/correction/fix_internal.dart:1009)
#3      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:177)
#4      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:52)
#5      DartFixContributor.computeFixes (package:analysis_server/plugin/edit/fix/fix_dart.dart:37)
#6      computeFixes (package:analysis_server/src/services/correction/fix.dart:27)
#7      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:164)
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:195)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:690)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:686)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:685)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#2      FixProcessor._addFix_createGetter (package:analysis_server/src/services/correction/fix_internal.dart:1009)
#3      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:177)
#4      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:52)
#5      DartFixContributor.computeFixes (package:analysis_server/plugin/edit/fix/fix_dart.dart:37)
#6      computeFixes (package:analysis_server/src/services/correction/fix.dart:27)
#7      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:164)
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:195)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:690)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:686)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:685)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:192)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)
```

```
2015-11-19 02:00:44,671 [102058871]  ERROR - yzer.DartAnalysisServerService - WebStorm 11.0.1  Build #WS-143.382.36 
2015-11-19 02:00:44,671 [102058871]  ERROR - yzer.DartAnalysisServerService - JDK: 1.8.0_40-release 
2015-11-19 02:00:44,671 [102058871]  ERROR - yzer.DartAnalysisServerService - VM: OpenJDK 64-Bit Server VM 
2015-11-19 02:00:44,671 [102058871]  ERROR - yzer.DartAnalysisServerService - Vendor: JetBrains s.r.o 
2015-11-19 02:00:44,671 [102058871]  ERROR - yzer.DartAnalysisServerService - OS: Mac OS X 
2015-11-19 02:00:44,671 [102058871]  ERROR - yzer.DartAnalysisServerService - Last Action: EditorBackSpace 
2015-11-19 02:00:45,273 [102059473]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.13.0-dev.7.12, server version 1.12.0, error: Exception from assist contributor: DefaultAssistContributor
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:666)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1196)
#2      DartAssistContributor.computeAssists (package:analysis_server/plugin/edit/assist/assist_dart.dart:30)
#3      computeAssists (package:analysis_server/src/services/correction/assist.dart:26)
#4      EditDomainHandler.getAssists (package:analysis_server/src/edit/edit_domain.dart:140)
#5      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:191)
#6      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:690)
#8      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:686)
#13     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:685)
#14     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#16     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#17     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#5      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#6      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#7      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#8      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#9      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#11     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#12     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#13     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:666)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1196)
#2      DartAssistContributor.computeAssists (package:analysis_server/plugin/edit/assist/assist_dart.dart:30)
#3      computeAssists (package:analysis_server/src/services/correction/assist.dart:26)
#4      EditDomainHandler.getAssists (package:analysis_server/src/edit/edit_domain.dart:140)
#5      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:191)
#6      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:690)
#8      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:686)
#13     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:685)
#14     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#16     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#17     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:192)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)
```

**Comment by scheglov** [comment]
It's strange that the exceptions don't have all the information I'd expect they would have.
For example there are no the line with the cause, and lines 0 and 1 here:
```
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#2      FixProcessor._addFix_createGetter (package:analysis_server/src/services/correction/fix_internal.dart:1009)
```

Did you remove it to prevent leaking some information about your project or is it not in the log?

@alexander-doroshko is it possible that DAS sends these lines, but IDEA does not put them in the log by some reason - special characters, too long, etc?

**Comment by alexander-doroshko** [comment]
As I see [this code](https://github.com/JetBrains/intellij-plugins/blob/ac271c892563b6fdef7cc8c5944d7b6439f67f4f/Dart/src/com/jetbrains/lang/dart/analyzer/DartAnalysisServerService.java#L195) IDE logs everything it gets.

**Comment by scheglov** [comment]
@alexander-doroshko Yes, I realize that its gets as is to the `LOG.error()` invocation. I just wonder if it is possible that the logger itself may somehow decide to drop some parts of the message. Not that I believe in this, just looking for an explanation why we could get such incomplete stack traces.

It could be just anything: VM, DAS preparing it incorrectly, JSON encoder, IDEA logger, user.

**Comment by alexander-doroshko** [comment]
I never heard about IDEA logger loosing information. Log looks strange indeed.

**Comment by davenotik** [comment]
Oh, could that be because I did a search? I was searching for errors and cut and pasted from that, which apparently shows by line. I thought I was being careful, but yes let me see if there's a way to click once found to get to the full message.

**Comment by scheglov** [comment]
Could you please configure DAS to start diagnostic HTTP server as described in https://docs.google.com/document/d/1s4PTof1x7RyxXYX1yO31ByvZsQoDMM7edFIW1SKP25U ? See `--port` description.

Specifically I'd look to see if there are exceptions.

Another possible problem is inconsistency between IDEA editor file content and DAS overlays.
See `http://127.0.0.1:8182/overlays?` Are there any files which you saved, but they are still listed on the page? Does content of the overlay equal to the content of the editor?
![image](https://cloud.githubusercontent.com/assets/384794/11407730/6c98cad8-9369-11e5-87a2-95b99dd38955.png)

**Comment by davenotik** [comment]
0 files on that page: http://d.pr/i/1f1oi

I also enabled the red icon in WebStorm so errors might be more visible. I'll let you know if I notice anything else. HTH!

**Comment by scheglov** [comment]
Not reproduced, don't know if solved.
