### ISSUE TITLE
Analysis Server throws an error when analyzing compile_time_constant_checked5_test.dart file

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25050]
Reproduced both with SDK 1.13.0 and `Dart VM version: 1.14.0-edge.ca9082332a192382bbe331d2fd54b67d0d73d862 (Wed Nov 25 15:53:44 2015) on "windows_x64"`
Presence of [this file](https://github.com/dart-lang/sdk/blob/master/tests/language/compile_time_constant_checked5_test.dart) in the project causes an error (2 traces below for different SDKs):
```
Dart analysis server, SDK version 1.13.0, server version 1.12.0, error: Task failed: VerifyUnitTask for source C:\dart_projects\untitled1\bin\main.dart
Unexpected exception while performing VerifyUnitTask for source C:\dart_projects\untitled1\bin\main.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

Caused by The null object does not have a getter 'value'.

NoSuchMethodError: method not found: 'value'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/generated/constant.dart:708)
#3      ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:958)
#4      InstanceCreationExpression.accept (package:analyzer/src/generated/ast.dart:11139)
#5      NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#6      ArgumentList.visitChildren (package:analyzer/src/generated/ast.dart:501)
#7      RecursiveAstVisitor.visitArgumentList (package:analyzer/src/generated/ast.dart:15085)
#8      ArgumentList.accept (package:analyzer/src/generated/ast.dart:466)
#9      AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#10     MethodInvocation.visitChildren (package:analyzer/src/generated/ast.dart:12376)
#11     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/src/generated/ast.dart:15463)
#12     MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12369)
#13     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#14     ExpressionStatement.visitChildren (package:analyzer/src/generated/ast.dart:7202)
#15     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/src/generated/ast.dart:15277)
#16     ExpressionStatement.accept (package:analyzer/src/generated/ast.dart:7198)
#17     NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#18     Block.visitChildren (package:analyzer/src/generated/ast.dart:3598)
#19     RecursiveAstVisitor.visitBlock (package:analyzer/src/generated/ast.dart:15121)
#20     Block.accept (package:analyzer/src/generated/ast.dart:3594)
#21     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#22     BlockFunctionBody.visitChildren (package:analyzer/src/generated/ast.dart:3677)
#23     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/src/generated/ast.dart:15127)
#24     BlockFunctionBody.accept (package:analyzer/src/generated/ast.dart:3673)
#25     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#26     FunctionExpression.visitChildren (package:analyzer/src/generated/ast.dart:8425)
#27     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/src/generated/ast.dart:15331)
#28     ConstantVerifier.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:941)
#29     FunctionExpression.accept (package:analyzer/src/generated/ast.dart:8419)
#30     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#31     FunctionDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:8256)
#32     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/src/generated/ast.dart:15319)
#33     FunctionDeclaration.accept (package:analyzer/src/generated/ast.dart:8249)
#34     NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#35     CompilationUnit.visitChildren (package:analyzer/src/generated/ast.dart:4975)
#36     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/src/generated/ast.dart:15181)
#37     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968)
#38     VerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:4605)
#39     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#40     AnalysisTask.perform (package:analyzer/task/model.dart:210)
#41     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#42     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#43     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#44     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#45     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#46     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#47     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#48     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#49     _rootRun (dart:async/zone.dart:903)
#50     _CustomZone.run (dart:async/zone.dart:802)
#51     _CustomZone.runGuarded (dart:async/zone.dart:708)
#52     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#53     _rootRun (dart:async/zone.dart:907)
#54     _CustomZone.run (dart:async/zone.dart:802)
#55     _CustomZone.runGuarded (dart:async/zone.dart:708)
#56     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#57     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#58     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#59     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)


#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:198)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)
```

```
Dart analysis server, SDK version 1.14.0-edge.6db18cbbd8a68abe1b42715110943cc4f2c65190, server version 1.12.0, error: Task failed: VerifyUnitTask for source C:\dart_projects\untitled1\bin\main.dart
Unexpected exception while performing VerifyUnitTask for source C:\dart_projects\untitled1\bin\main.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1116)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1114)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:797)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'value'.

NoSuchMethodError: method not found: 'value'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/generated/constant.dart:709)
#3      ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1090)
#4      InstanceCreationExpression.accept (package:analyzer/src/generated/ast.dart:11139)
#5      NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#6      ArgumentList.visitChildren (package:analyzer/src/generated/ast.dart:501)
#7      RecursiveAstVisitor.visitArgumentList (package:analyzer/src/generated/ast.dart:15085)
#8      ArgumentList.accept (package:analyzer/src/generated/ast.dart:466)
#9      AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#10     MethodInvocation.visitChildren (package:analyzer/src/generated/ast.dart:12376)
#11     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/src/generated/ast.dart:15463)
#12     MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12369)
#13     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#14     ExpressionStatement.visitChildren (package:analyzer/src/generated/ast.dart:7202)
#15     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/src/generated/ast.dart:15277)
#16     ExpressionStatement.accept (package:analyzer/src/generated/ast.dart:7198)
#17     NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#18     Block.visitChildren (package:analyzer/src/generated/ast.dart:3598)
#19     RecursiveAstVisitor.visitBlock (package:analyzer/src/generated/ast.dart:15121)
#20     Block.accept (package:analyzer/src/generated/ast.dart:3594)
#21     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#22     BlockFunctionBody.visitChildren (package:analyzer/src/generated/ast.dart:3677)
#23     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/src/generated/ast.dart:15127)
#24     BlockFunctionBody.accept (package:analyzer/src/generated/ast.dart:3673)
#25     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#26     FunctionExpression.visitChildren (package:analyzer/src/generated/ast.dart:8425)
#27     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/src/generated/ast.dart:15331)
#28     ConstantVerifier.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:1073)
#29     FunctionExpression.accept (package:analyzer/src/generated/ast.dart:8419)
#30     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#31     FunctionDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:8256)
#32     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/src/generated/ast.dart:15319)
#33     FunctionDeclaration.accept (package:analyzer/src/generated/ast.dart:8249)
#34     NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#35     CompilationUnit.visitChildren (package:analyzer/src/generated/ast.dart:4975)
#36     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/src/generated/ast.dart:15181)
#37     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968)
#38     VerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:5112)
#39     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#40     AnalysisTask.perform (package:analyzer/task/model.dart:210)
#41     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#42     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247)
#43     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1116)
#44     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#45     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1114)
#46     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#47     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:797)
#48     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#49     _rootRun (dart:async/zone.dart:903)
#50     _CustomZone.run (dart:async/zone.dart:802)
#51     _CustomZone.runGuarded (dart:async/zone.dart:708)
#52     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#53     _rootRun (dart:async/zone.dart:907)
#54     _CustomZone.run (dart:async/zone.dart:802)
#55     _CustomZone.runGuarded (dart:async/zone.dart:708)
#56     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#57     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#58     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:198)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)
```

**Comment by scheglov** [comment]
Thank you for the reproducible report!

https://codereview.chromium.org/1493833003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/f12da4d00c2134b9d60d9657a77d4263c197271a
