### ISSUE TITLE
Type 'VoidTypeImpl' is not a subtype of type 'FunctionType' in type cast.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#25069]
@jmesserly 

```
Dart analysis server, SDK version 1.14.0-dev.1.0, server version 1.12.0, error: Exception from assist contributor: DefaultAssistContributor
Cannot compute RESOLVED_UNIT for C:\Users\ginn\dart\libSamovar\src\ems\muxer.dart in C:\Users\ginn\dart\libSamovar\lib_samovar.dart
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:679)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1214)
#2      DartAssistContributor.computeAssists (package:analysis_server/plugin/edit/assist/assist_dart.dart:30)
#3      computeAssists (package:analysis_server/src/services/correction/assist.dart:26)
#4      EditDomainHandler.getAssists (package:analysis_server/src/edit/edit_domain.dart:140)
#5      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:191)
#6      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:685)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#8      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:681)
#9      _rootRun (dart:async/zone.dart:907)
#10     _CustomZone.run (dart:async/zone.dart:802)
#11     _CustomZone.runGuarded (dart:async/zone.dart:708)
#12     runZoned (dart:async/zone.dart:1243)
#13     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:680)
#14     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#16     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#17     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#18     _rootRunUnary (dart:async/zone.dart:914)
#19     _CustomZone.runUnary (dart:async/zone.dart:810)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#26     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127)
#27     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102)
#28     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#29     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#31     _rootRunUnary (dart:async/zone.dart:914)
#32     _CustomZone.runUnary (dart:async/zone.dart:810)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#44     _rootRunUnary (dart:async/zone.dart:914)
#45     _CustomZone.runUnary (dart:async/zone.dart:810)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#49     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#50     _StreamController._add (dart:async/stream_controller.dart:616)
#51     _StreamController.add (dart:async/stream_controller.dart:562)
#52     _Socket._onData (dart:io-patch/socket_patch.dart:1646)
#53     _rootRunUnary (dart:async/zone.dart:918)
#54     _CustomZone.runUnary (dart:async/zone.dart:810)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#58     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#59     _StreamController._add (dart:async/stream_controller.dart:616)
#60     _StreamController.add (dart:async/stream_controller.dart:562)
#61     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1215)
#62     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#63     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#64     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#65     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Caused by Unexpected exception while performing StrongModeVerifyUnitTask for source C:\Users\ginn\dart\libSamovar\src\ems\muxer.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1116)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1114)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:797)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by type 'VoidTypeImpl' is not a subtype of type 'FunctionType' in type cast.
#0      Object._as (dart:core-patch/object_patch.dart:70)
#1      TypeRules.isSubTypeOf (package:analyzer/src/task/strong/rules.dart:367)
#2      TypeRules._coerceTo (package:analyzer/src/task/strong/rules.dart:383)
#3      TypeRules.checkAssignment (package:analyzer/src/task/strong/rules.dart:418)
#4      CodeChecker.checkAssignment (package:analyzer/src/task/strong/checker.dart:837)
#5      CodeChecker.checkArgument (package:analyzer/src/task/strong/checker.dart:525)
#6      CodeChecker.checkArgumentList (package:analyzer/src/task/strong/checker.dart:515)
#7      CodeChecker.checkFunctionApplication (package:analyzer/src/task/strong/checker.dart:535)
#8      CodeChecker.visitMethodInvocation (package:analyzer/src/task/strong/checker.dart:561)
#9      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12369)
#10     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#11     ExpressionStatement.visitChildren (package:analyzer/src/generated/ast.dart:7202)
#12     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/src/generated/ast.dart:15277)
#13     ExpressionStatement.accept (package:analyzer/src/generated/ast.dart:7198)
#14     NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#15     Block.visitChildren (package:analyzer/src/generated/ast.dart:3598)
#16     RecursiveAstVisitor.visitBlock (package:analyzer/src/generated/ast.dart:15121)
#17     Block.accept (package:analyzer/src/generated/ast.dart:3594)
#18     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#19     BlockFunctionBody.visitChildren (package:analyzer/src/generated/ast.dart:3677)
#20     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/src/generated/ast.dart:15127)
#21     BlockFunctionBody.accept (package:analyzer/src/generated/ast.dart:3673)
#22     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#23     ConstructorDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:5734)
#24     CodeChecker.visitConstructorDeclaration (package:analyzer/src/task/strong/checker.dart:391)
#25     ConstructorDeclaration.accept (package:analyzer/src/generated/ast.dart:5724)
#26     NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#27     ClassDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:4419)
#28     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/src/generated/ast.dart:15157)
#29     CodeChecker.visitClassDeclaration (package:analyzer/src/task/strong/checker.dart:373)
#30     ClassDeclaration.accept (package:analyzer/src/generated/ast.dart:4349)
#31     NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#32     CompilationUnit.visitChildren (package:analyzer/src/generated/ast.dart:4975)
#33     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/src/generated/ast.dart:15181)
#34     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968)
#35     StrongModeVerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:4530)
#36     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#37     AnalysisTask.perform (package:analyzer/task/model.dart:210)
#38     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#39     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247)
#40     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1116)
#41     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#42     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1114)
#43     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#44     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:797)
#45     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#46     _rootRun (dart:async/zone.dart:903)
#47     _CustomZone.run (dart:async/zone.dart:802)
#48     _CustomZone.runGuarded (dart:async/zone.dart:708)
#49     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#50     _rootRun (dart:async/zone.dart:907)
#51     _CustomZone.run (dart:async/zone.dart:802)
#52     _CustomZone.runGuarded (dart:async/zone.dart:708)
#53     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#54     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#55     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:679)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1214)
#2      DartAssistContributor.computeAssists (package:analysis_server/plugin/edit/assist/assist_dart.dart:30)
#3      computeAssists (package:analysis_server/src/services/correction/assist.dart:26)
#4      EditDomainHandler.getAssists (package:analysis_server/src/edit/edit_domain.dart:140)
#5      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:191)
#6      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:685)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#8      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:681)
#9      _rootRun (dart:async/zone.dart:907)
#10     _CustomZone.run (dart:async/zone.dart:802)
#11     _CustomZone.runGuarded (dart:async/zone.dart:708)
#12     runZoned (dart:async/zone.dart:1243)
#13     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:680)
#14     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#16     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#17     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#18     _rootRunUnary (dart:async/zone.dart:914)
#19     _CustomZone.runUnary (dart:async/zone.dart:810)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#26     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127)
#27     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102)
#28     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#29     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#31     _rootRunUnary (dart:async/zone.dart:914)
#32     _CustomZone.runUnary (dart:async/zone.dart:810)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#44     _rootRunUnary (dart:async/zone.dart:914)
#45     _CustomZone.runUnary (dart:async/zone.dart:810)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#49     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#50     _StreamController._add (dart:async/stream_controller.dart:616)
#51     _StreamController.add (dart:async/stream_controller.dart:562)
#52     _Socket._onData (dart:io-patch/socket_patch.dart:1646)
#53     _rootRunUnary (dart:async/zone.dart:918)
#54     _CustomZone.runUnary (dart:async/zone.dart:810)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#58     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#59     _StreamController._add (dart:async/stream_controller.dart:616)
#60     _StreamController.add (dart:async/stream_controller.dart:562)
#61     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1215)
#62     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#63     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#64     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#65     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by jmesserly** [comment]
I think this is more likely to be in Leaf's area of expertise.

IMHO, we should get rid of TypeRules (package:analyzer/src/task/strong/rules.dart) entirely, it duplicates code in StrongTypeSystemImpl

**Comment by jmesserly** [comment]
CC @leafpetersen
