### ISSUE TITLE
Exception in StrongModeVerifyUnitTask

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#25071]
@jmesserly 

```
Dart analysis server, SDK version 1.13.0-dev.7.12, server version 1.12.0, error: Failed to handle completion domain request: {clientRequestTime: 1448063494303, params: {file: /Users/aholmgren/Projects/dart/innovation/benchwarmer/lib/model/model.dart, offset: 4152}, method: completion.getSuggestions, id: 11858}
Unexpected exception while performing StrongModeVerifyUnitTask for source /Users/aholmgren/Projects/dart/innovation/benchwarmer/lib/model/model.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

Caused by The null object does not have a getter 'type'.

NoSuchMethodError: method not found: 'type'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      CodeChecker.visitRedirectingConstructorInvocation (package:analyzer/src/task/strong/checker.dart:558)
#3      RedirectingConstructorInvocation.accept (package:analyzer/src/generated/ast.dart:15812)
#4      NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#5      ConstructorDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:5732)
#6      CodeChecker.visitConstructorDeclaration (package:analyzer/src/task/strong/checker.dart:374)
#7      ConstructorDeclaration.accept (package:analyzer/src/generated/ast.dart:5724)
#8      NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#9      ClassDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:4419)
#10     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/src/generated/ast.dart:15157)
#11     CodeChecker.visitClassDeclaration (package:analyzer/src/task/strong/checker.dart:356)
#12     ClassDeclaration.accept (package:analyzer/src/generated/ast.dart:4349)
#13     NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#14     CompilationUnit.visitChildren (package:analyzer/src/generated/ast.dart:4975)
#15     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/src/generated/ast.dart:15181)
#16     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968)
#17     StrongModeVerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:4519)
#18     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#19     AnalysisTask.perform (package:analyzer/task/model.dart:210)
#20     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#21     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#22     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#24     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#25     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#26     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#27     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#28     _rootRun (dart:async/zone.dart:903)
#29     _CustomZone.run (dart:async/zone.dart:802)
#30     _CustomZone.runGuarded (dart:async/zone.dart:708)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#32     _rootRun (dart:async/zone.dart:907)
#33     _CustomZone.run (dart:async/zone.dart:802)
#34     _CustomZone.runGuarded (dart:async/zone.dart:708)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)


#0      AnalysisFutureHelper.computeAsync.<anonymous closure> (package:analyzer/src/context/context.dart:1988)
#1      PendingFuture.evaluate (package:analyzer/src/context/context.dart:2093)
#2      AnalysisFutureHelper.computeAsync (package:analyzer/src/context/context.dart:1994)
#3      AnalysisContextImpl.computeResolvedCompilationUnitAsync (package:analyzer/src/context/context.dart:650)
#4      DartCompletionManager.waitForAnalysis (package:analysis_server/src/services/completion/dart_completion_manager.dart:278)
#5      DartCompletionManager.computeFull (package:analysis_server/src/services/completion/dart_completion_manager.dart:202)
#6      DartCompletionManager.computeSuggestions.<anonymous closure> (package:analysis_server/src/services/completion/dart_completion_manager.dart:245)
#7      CompletionPerformance.logElapseTime (package:analysis_server/src/services/completion/completion_manager.dart:165)
#8      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart_completion_manager.dart:242)
#9      CompletionManager.results.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/completion/completion_manager.dart:108)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#19     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by jmesserly** [comment]
reassigning to @leafpetersen who might be have a better idea about CodeChecker
