### ISSUE TITLE
Exception in StaticTypeAnalyzer._matchGeneric 

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#25070]
@jmesserly 
It seems that the method `_matchGeneric` was removed since then.
I wonder if the problem might have been fixed.

```
Dart analysis server, SDK version 1.13.0-dev.7.12, server version 1.12.0, error: Task failed: ResolveUnitTask for source /Users/blah/.pub-cache/hosted/pub.dartlang.org/scheduled_test-0.12.4/lib/src/utils.dart
Unexpected exception while performing ResolveUnitTask for source /Users/blah/.pub-cache/hosted/pub.dartlang.org/scheduled_test-0.12.4/lib/src/utils.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

Caused by The null object does not have a getter 'element'.

NoSuchMethodError: method not found: 'element'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      StaticTypeAnalyzer._matchGeneric (package:analyzer/src/generated/static_type_analyzer.dart:1904)
#3      StaticTypeAnalyzer._inferMethodInvocationGeneric (package:analyzer/src/generated/static_type_analyzer.dart:1697)
#4      StaticTypeAnalyzer._inferMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:1688)
#5      StaticTypeAnalyzer.visitMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:635)
#6      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12369)
#7      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:11296)
#8      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12369)
#9      AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#10     ReturnStatement.visitChildren (package:analyzer/src/generated/ast.dart:15947)
#11     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11302)
#12     UnifyingAstVisitor.visitReturnStatement (package:analyzer/src/generated/ast.dart:19913)
#13     ReturnStatement.accept (package:analyzer/src/generated/ast.dart:15943)
#14     NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#15     Block.visitChildren (package:analyzer/src/generated/ast.dart:3598)
#16     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11302)
#17     UnifyingAstVisitor.visitBlock (package:analyzer/src/generated/ast.dart:19685)
#18     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:12200)
#19     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:12603)
#20     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:11225)
#21     IfStatement.accept (package:analyzer/src/generated/ast.dart:9442)
#22     NodeList.accept (package:analyzer/src/generated/ast.dart:12777)
#23     Block.visitChildren (package:analyzer/src/generated/ast.dart:3598)
#24     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11302)
#25     UnifyingAstVisitor.visitBlock (package:analyzer/src/generated/ast.dart:19685)
#26     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:12200)
#27     Block.accept (package:analyzer/src/generated/ast.dart:3594)
#28     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#29     BlockFunctionBody.visitChildren (package:analyzer/src/generated/ast.dart:3677)
#30     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11302)
#31     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/src/generated/ast.dart:19688)
#32     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:12212)
#33     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:10726)
#34     BlockFunctionBody.accept (package:analyzer/src/generated/ast.dart:3673)
#35     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#36     FunctionExpression.visitChildren (package:analyzer/src/generated/ast.dart:8425)
#37     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11302)
#38     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/src/generated/ast.dart:19793)
#39     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:12487)
#40     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:11167)
#41     FunctionExpression.accept (package:analyzer/src/generated/ast.dart:8419)
#42     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#43     FunctionDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:8256)
#44     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11302)
#45     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/src/generated/ast.dart:19786)
#46     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:12476)
#47     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:11153)
#48     FunctionDeclaration.accept (package:analyzer/src/generated/ast.dart:8249)
#49     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:10843)
#50     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968)
#51     ResolveUnitTask.internalPerform (package:analyzer/src/task/dart.dart:4149)
#52     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#53     AnalysisTask.perform (package:analyzer/task/model.dart:210)
#54     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#55     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#56     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#57     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#58     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#59     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#60     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#61     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#62     _rootRun (dart:async/zone.dart:903)
#63     _CustomZone.run (dart:async/zone.dart:802)
#64     _CustomZone.runGuarded (dart:async/zone.dart:708)
#65     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#66     _rootRun (dart:async/zone.dart:907)
#67     _CustomZone.run (dart:async/zone.dart:802)
#68     _CustomZone.runGuarded (dart:async/zone.dart:708)
#69     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#70     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#71     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#72     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)


#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

**Comment by jmesserly** [comment]
Yup, this function no longer exists. Assumed to be stale.
