### ISSUE TITLE
Opening isolate_patch.dart file in the IDE causes Analysis Server exception

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25101]
Reproducible both with today's SDK `1.14.0-edge.e1f6fc7c95c9506d137f950078fb108a3014a206` and with `1.13.0`.
- clone https://github.com/dart-lang/sdk project and open it in the IDE
- open [isolate_patch.dart](https://github.com/dart-lang/sdk/blob/71b3d5aba894daeaf04165f10f0fd302251d6b4a/runtime/lib/isolate_patch.dart) file

I can attach my `--instrumentation-log-file`, but I think you'll be able to reproduce the same yourselves.
```
Dart analysis server, SDK version 1.14.0-edge.e1f6fc7c95c9506d137f950078fb108a3014a206, server version 1.12.0, error: Task failed: PartiallyResolveUnitReferencesTask for source C:\dart_projects\dart-lang\sdk\runtime\lib\isolate_patch.dart
Unexpected exception while performing PartiallyResolveUnitReferencesTask for source C:\dart_projects\dart-lang\sdk\runtime\lib\isolate_patch.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:681)
#5      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1223)
#6      AnalysisServer._getResolvedCompilationUnitToResendNotification.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1329)
#7      runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:36)
#8      AnalysisServer._getResolvedCompilationUnitToResendNotification (package:analysis_server/src/analysis_server.dart:1328)
#9      AnalysisServer.setAnalysisSubscriptions.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1003)
#10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#11     AnalysisServer.setAnalysisSubscriptions (package:analysis_server/src/analysis_server.dart:968)
#12     AnalysisDomainHandler.setSubscriptions (package:analysis_server/src/domain_analysis.dart:281)
#13     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:207)
#14     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:685)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#16     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:681)
#17     _rootRun (dart:async/zone.dart:907)
#18     _CustomZone.run (dart:async/zone.dart:802)
#19     _CustomZone.runGuarded (dart:async/zone.dart:708)
#20     runZoned (dart:async/zone.dart:1243)
#21     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:680)
#22     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#26     _rootRunUnary (dart:async/zone.dart:914)
#27     _CustomZone.runUnary (dart:async/zone.dart:810)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#37     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#39     _rootRunUnary (dart:async/zone.dart:914)
#40     _CustomZone.runUnary (dart:async/zone.dart:810)
#41     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#44     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#45     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#46     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#47     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#48     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#49     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#50     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#51     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#52     _rootRunUnary (dart:async/zone.dart:914)
#53     _CustomZone.runUnary (dart:async/zone.dart:810)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#57     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#58     _StreamController._add (dart:async/stream_controller.dart:616)
#59     _StreamController.add (dart:async/stream_controller.dart:562)
#60     _Socket._onData (dart:io-patch/socket_patch.dart:1646)
#61     _rootRunUnary (dart:async/zone.dart:918)
#62     _CustomZone.runUnary (dart:async/zone.dart:810)
#63     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#66     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#67     _StreamController._add (dart:async/stream_controller.dart:616)
#68     _StreamController.add (dart:async/stream_controller.dart:562)
#69     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1215)
#70     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#71     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#72     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#73     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Caused by The null object does not have a getter 'initializer'.

NoSuchMethodError: method not found: 'initializer'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:11963)
#3      VariableDeclaration.accept (package:analyzer/src/generated/ast.dart:20331)
#4      NodeList.accept (package:analyzer/src/generated/ast.dart:12778)
#5      VariableDeclarationList.visitChildren (package:analyzer/src/generated/ast.dart:20444)
#6      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11845)
#7      PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10020)
#8      UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/src/generated/ast.dart:20072)
#9      ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:11986)
#10     VariableDeclarationList.accept (package:analyzer/src/generated/ast.dart:20438)
#11     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
#12     TopLevelVariableDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:18075)
#13     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:11845)
#14     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10020)
#15     UnifyingAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/src/generated/ast.dart:20050)
#16     ResolverVisitor.visitTopLevelVariableDeclaration (package:analyzer/src/generated/resolver.dart:11945)
#17     PartialResolverVisitor.visitTopLevelVariableDeclaration (package:analyzer/src/generated/resolver.dart:10027)
#18     TopLevelVariableDeclaration.accept (package:analyzer/src/generated/ast.dart:18070)
#19     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:11263)
#20     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4968)
#21     PartiallyResolveUnitReferencesTask.internalPerform (package:analyzer/src/task/dart.dart:3605)
#22     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#23     AnalysisTask.perform (package:analyzer/task/model.dart:210)
#24     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#25     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110)
#26     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:681)
#27     AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1223)
#28     AnalysisServer._getResolvedCompilationUnitToResendNotification.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1329)
#29     runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:36)
#30     AnalysisServer._getResolvedCompilationUnitToResendNotification (package:analysis_server/src/analysis_server.dart:1328)
#31     AnalysisServer.setAnalysisSubscriptions.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1003)
#32     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#33     AnalysisServer.setAnalysisSubscriptions (package:analysis_server/src/analysis_server.dart:968)
#34     AnalysisDomainHandler.setSubscriptions (package:analysis_server/src/domain_analysis.dart:281)
#35     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:207)
#36     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:685)
#37     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#38     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:681)
#39     _rootRun (dart:async/zone.dart:907)
#40     _CustomZone.run (dart:async/zone.dart:802)
#41     _CustomZone.runGuarded (dart:async/zone.dart:708)
#42     runZoned (dart:async/zone.dart:1243)
#43     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:680)
#44     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#45     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#46     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#47     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#48     _rootRunUnary (dart:async/zone.dart:914)
#49     _CustomZone.runUnary (dart:async/zone.dart:810)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#53     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#54     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#55     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#56     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127)
#57     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102)
#58     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#59     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#60     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#61     _rootRunUnary (dart:async/zone.dart:914)
#62     _CustomZone.runUnary (dart:async/zone.dart:810)
#63     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#66     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#67     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#68     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#69     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#70     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#71     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#72     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#73     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#74     _rootRunUnary (dart:async/zone.dart:914)
#75     _CustomZone.runUnary (dart:async/zone.dart:810)
#76     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#77     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#78     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#79     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#80     _StreamController._add (dart:async/stream_controller.dart:616)
#81     _StreamController.add (dart:async/stream_controller.dart:562)
#82     _Socket._onData (dart:io-patch/socket_patch.dart:1646)
#83     _rootRunUnary (dart:async/zone.dart:918)
#84     _CustomZone.runUnary (dart:async/zone.dart:810)
#85     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#86     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#87     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#88     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#89     _StreamController._add (dart:async/stream_controller.dart:616)
#90     _StreamController.add (dart:async/stream_controller.dart:562)
#91     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1215)
#92     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#93     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#94     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#95     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#96     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/1495783005

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/072aaaefb6a6013bfaea5690885b40122b0e1517
