### ISSUE TITLE
Analyzer doesn't notice that mixin with extends isn't satisfied

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25118]
``` dart
class A { void test() { print('pass'); } }
class B extends A { }

class Q { }
class R extends Q with B { }

void main() {
  new R().test();
}
```

The analyzer gives this the :+1:, but it should complain that B's requirements, namely that it implements A, are not met by R.

At runtime, this fails, as can be statically predicted:

```
Class 'R' has no instance method 'test'.

NoSuchMethodError: method not found: 'test'
Receiver: Instance of 'R'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      main (test.dart:9:11)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

**Comment by srawlins** [comment]
There is now a static error for the given example, as of Dart 2.0.0-dev.64.1.

```
$ dartanalyzer 25118.dart 
Analyzing 25118.dart...
  error • The class 'B' can't be used as a mixin because it extends a class other than Object at 25118.dart:5:24 • mixin_inherits_from_not_object
1 error found.
```

**Comment by Hixie** [comment]
In 2.0.0-dev.63.0.flutter-4c9689c1d2, it says the following:

```
test.dart:5:7: Error: The non-abstract class 'R' is missing implementations for these members:
  'test'.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class R extends Q with B { }
      ^
```

...which seems correct. Did this regress in dev.64.1, or is this just a question of whether supermixins are enabled?

**Comment by srawlins** [comment]
That, I think, is what `dart` says, not `dartanalyzer`. I checked though, here's when I call `dartanalyzer --supermixin`:

```
Analyzing 25118.dart...
  error • Missing concrete implementation of 'A.test' at 25118.dart:5:7 • non_abstract_class_inherits_abstract_member_one
1 error found.
```

which is basically the same as your error (same position and gist of the message, though `dart`'s message is definitely more helpful.

But at least `dartanalyzer --supermixin` _has an error_ (fixing the original bug here)
