### ISSUE TITLE
Timer related test failures

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#25216]
Could this be related to the recent changes to Timer/Stopwatch?

```
FAILED: none-vm debug_ia32 co19/LibTest/async/Future/Future.delayed_A01_t02
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
Unhandled exception:
Expect.isTrue(false, 'delay=0:00:00.300000, elapsed=0:00:00.299508') fails.
#0      _fail (file:///E:/b/build/slave/vm-win32-debug-be/build/sdk/tests/co19/src/Utils/expect.dart:17:5)
#1      Expect.isTrue (file:///E:/b/build/slave/vm-win32-debug-be/build/sdk/tests/co19/src/Utils/expect_common.dart:36:5)
#2      check.<anonymous closure> (file:///E:/b/build/slave/vm-win32-debug-be/build/sdk/tests/co19/src/LibTest/async/Future/Future.delayed_A01_t02.dart:27:12)
#3      Future.Future.delayed.<anonymous closure> (dart:async/future.dart:228)
#4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by rmacnak-google** [comment]
9387fead15f6158abc502702d0091c355d69dec3
fc551b6f330c3d8e0d240dd80a8afeed1bb6d9cb
1a333dcdd2d9a57588926eda89bfa0f1092c9165
2bfdde5c36c9393f38a453a49684e4ba0f5e8b8f
