### ISSUE TITLE
VM assertion failure win64: isolate_data.h:33: error: expected: packages_file == NULL

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#25211]
http://build.chromium.org/p/client.dart/builders/vm-win64-debug-be/builds/2439/steps/checked_tests/logs/stdio

```
FAILED: none-vm-checked debug_x64 co19/LibTest/isolate/Isolate/spawnUri_A02_t01
Expected: RuntimeError 
Actual: Timeout
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.throws() fails
#0      _fail (file:///E:/b/build/slave/vm-win64-debug-be/build/sdk/tests/co19/src/Utils/expect.dart:17:5)
#1      Expect.throws (file:///E:/b/build/slave/vm-win64-debug-be/build/sdk/tests/co19/src/Utils/expect_common.dart:290:5)
#2      main (file:///E:/b/build/slave/vm-win64-debug-be/build/sdk/tests/co19/src/LibTest/isolate/Isolate/spawnUri_A02_t01.dart:18:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
E:\b\build\slave\vm-win64-debug-be\build\sdk\runtime\bin/isolate_data.h:33: error: expected: packages_file == NULL


Command[vm]: set DART_CONFIGURATION=DebugX64 & build\DebugX64\dart.exe --enable_asserts --enable_type_checks --ignore-unrecognized-flags --package-root=build/DebugX64/packages/ E:\b\build\slave\vm-win64-debug-be\build\sdk\tests\co19\src\LibTest\isolate\Isolate\spawnUri_A02_t01.dart
Took 0:02:00.011000

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --checked -t120 co19/LibTest/isolate/Isolate/spawnUri_A02_t01
```

**Comment by fsc8000** [comment]
Not occurring anymore. Assuming fixed for now.
