### ISSUE TITLE
Invalid conversion in test harness

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25227]
Test configuration: none_vm_release_mips
[18:56 |   8% | + 1050 | -    0]Unhandled exception:
Uncaught Error: Unsupported operation: Infinity or NaN toInt
Stack Trace:
#0      double.toInt (dart:core-patch/double.dart:136)
#1      CompactProgressIndicator._printProgress (file:///home/rmacnak/dart1/sdk/tools/testing/dart/test_progress.dart:593:66)
#2      CompactIndicator._printDoneProgress (file:///home/rmacnak/dart1/sdk/tools/testing/dart/test_progress.dart:580:59)
#3      ProgressIndicator.done (file:///home/rmacnak/dart1/sdk/tools/testing/dart/test_progress.dart:550:23)
#4      ProcessQueue.eventFinishedTestCase (file:///home/rmacnak/dart1/sdk/tools/testing/dart/test_runner.dart:2946:20)
#5      ProcessQueue.ProcessQueue.setupForRunning.<anonymous closure> (file:///home/rmacnak/dart1/sdk/tools/testing/dart/test_runner.dart:2909:36)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#8      _DelayedData.perform (dart:async/stream_impl.dart:595)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:711)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:671)
#11     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#12     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#14     _Timer._handleTimeout (dart:isolate-patch/timer_impl.dart:399)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:145)
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _Timer._handleTimeout (dart:isolate-patch/timer_impl.dart:399)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:145)

**Comment by rmacnak-google** [comment]
Assumed stale.
