### ISSUE TITLE
Infinite loop while performing task InferInstanceMembersInUnitTask

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25239]
Seemed to happen after editing a top-level declaration (`DartType instantiateToBounds(FunctionType function)`) in type_system.dart:

```
Dart analysis server, SDK version 1.14.0-edge.1c3df7f4ecb7b4a503fa9aa4e88d584c436006f0, server version 1.14.0, error: Task failed: InferInstanceMembersInUnitTask for source /Users/jmesserly/src/dart/sdk/pkg/analyzer/lib/src/generated/scanner.dart
Infinite loop while performing task InferInstanceMembersInUnitTask for /Users/jmesserly/src/dart/sdk/pkg/analyzer/lib/src/generated/scanner.dart in /Users/jmesserly/src/dart/sdk/pkg/analyzer/lib/src/generated/scanner.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:307)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:635)
#5      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1153)
#6      DartAssistContributor.computeAssists.<computeAssists_async_body> (package:analysis_server/plugin/edit/assist/assist_dart.dart:64)
#7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#8      _rootRun (dart:async/zone.dart:903)
#9      _CustomZone.run (dart:async/zone.dart:802)
#10     _CustomZone.runGuarded (dart:async/zone.dart:708)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#12     _rootRun (dart:async/zone.dart:907)
#13     _CustomZone.run (dart:async/zone.dart:802)
#14     _CustomZone.runGuarded (dart:async/zone.dart:708)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:202)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)

[... bunch more of those java.lang.Throwable stacks ...]
```
Possibly the same issue as https://github.com/dart-lang/sdk/issues/25035

**Comment by jmesserly** [comment]
I haven't seen this occur again so optimistically assuming it's fixed.
