### ISSUE TITLE
The null object does not have a getter 'boundTypeParameters'.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#25245]
```
Dart analysis server, SDK version 1.14.0-edge.ad0e9622e9211c9593f5e51789fa6ff3c9c43e3a, server version 1.14.0, error: Task failed: PartiallyResolveUnitReferencesTask for source /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/ast.dart
Unexpected exception while performing PartiallyResolveUnitReferencesTask for source /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/ast.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271:10)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246:9)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1052:27)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188:15)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1050:49)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:370:37)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:806:17)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'boundTypeParameters'.

NoSuchMethodError: method not found: 'boundTypeParameters'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:644:52)
#3      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12244:41)
#4      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:9080:10)
#5      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12244:41)
#6      AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3059:13)
#7      PrefixExpression.visitChildren (package:analyzer/src/generated/ast.dart:14806:5)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9107:10)
#9      PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7580:27)
#10     UnifyingAstVisitor.visitPrefixExpression (package:analyzer/src/generated/ast.dart:19663:53)
#11     PrefixExpression.accept (package:analyzer/src/generated/ast.dart:14802:41)
#12     ScopedVisitor.safelyVisit (package:analyzer/src/generated/resolver.dart:10042:12)
#13     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:8910:5)
#14     IfStatement.accept (package:analyzer/src/generated/ast.dart:9393:41)
#15     NodeList.accept (package:analyzer/src/generated/ast.dart:12642:20)
#16     Block.visitChildren (package:analyzer/src/generated/ast.dart:3544:17)
#17     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9107:10)
#18     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7580:27)
#19     UnifyingAstVisitor.visitBlock (package:analyzer/src/generated/ast.dart:19443:31)
#20     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:10053:23)
#21     Block.accept (package:analyzer/src/generated/ast.dart:3540:41)
#22     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3059:13)
#23     BlockFunctionBody.visitChildren (package:analyzer/src/generated/ast.dart:3623:5)
#24     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9107:10)
#25     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7580:27)
#26     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/src/generated/ast.dart:19446:55)
#27     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:10065:35)
#28     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:8397:35)
#29     PartialResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7558:40)
#30     BlockFunctionBody.accept (package:analyzer/src/generated/ast.dart:3619:41)
#31     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3059:13)
#32     FunctionExpression.visitChildren (package:analyzer/src/generated/ast.dart:8370:5)
#33     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9107:10)
#34     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7580:27)
#35     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/src/generated/ast.dart:19557:57)
#36     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:10365:38)
#37     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:8867:38)
#38     FunctionExpression.accept (package:analyzer/src/generated/ast.dart:8364:41)
#39     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3059:13)
#40     VariableDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:20011:5)
#41     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9107:10)
#42     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7580:27)
#43     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/src/generated/ast.dart:19742:59)
#44     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:10517:35)
#45     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:9223:35)
#46     VariableDeclaration.accept (package:analyzer/src/generated/ast.dart:20005:41)
#47     NodeList.accept (package:analyzer/src/generated/ast.dart:12642:20)
#48     VariableDeclarationList.visitChildren (package:analyzer/src/generated/ast.dart:20120:16)
#49     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9107:10)
#50     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7580:27)
#51     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/src/generated/ast.dart:19746:7)
#52     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:9248:39)
#53     VariableDeclarationList.accept (package:analyzer/src/generated/ast.dart:20114:41)
#54     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3059:13)
#55     FieldDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:7350:5)
#56     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9107:10)
#57     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7580:27)
#58     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/src/generated/ast.dart:19535:53)
#59     ResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:8736:34)
#60     PartialResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:7575:39)
#61     FieldDeclaration.accept (package:analyzer/src/generated/ast.dart:7345:41)
#62     NodeList.accept (package:analyzer/src/generated/ast.dart:12642:20)
#63     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:10134:18)
#64     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:10111:11)
#65     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:8439:34)
#66     ClassDeclaration.accept (package:analyzer/src/generated/ast.dart:4281:41)
#67     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:8527:23)
#68     CompilationUnit.accept (package:analyzer/src/generated/ast.dart:4900:41)
#69     PartiallyResolveUnitReferencesTask.internalPerform (package:analyzer/src/task/dart.dart:3592:10)
#70     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310:9)
#71     AnalysisTask.perform (package:analyzer/task/model.dart:210:7)
#72     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271:10)
#73     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246:9)
#74     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1052:27)
#75     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188:15)
#76     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1050:49)
#77     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:370:37)
#78     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:806:17)
#79     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#80     _rootRun (dart:async/zone.dart:903)
#81     _CustomZone.run (dart:async/zone.dart:802)
#82     _CustomZone.runGuarded (dart:async/zone.dart:708)
#83     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#84     _rootRun (dart:async/zone.dart:907)
#85     _CustomZone.run (dart:async/zone.dart:802)
#86     _CustomZone.runGuarded (dart:async/zone.dart:708)
#87     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#88     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#89     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#90     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:203)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
```

**Comment by bwilkerson** [comment]
Do you know how to reproduce this? The getter `boundTypeParameters` has been renamed and it's replacement isn't invoked in the `ElementResolver.visitMethodInvocation` method anymore, so I'm at a loss to get any information from which to start tracking down this bug.

**Comment by scheglov** [comment]
No, unfortunately I don't how to reproduce this.

**Comment by bwilkerson** [comment]
Then I'll close it for lack of information.
