### ISSUE TITLE
Timer related test failing on Windows

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#25278]
http://build.chromium.org/p/client.dart/builders/vm-win64-debug-be/builds/2511/steps/checked_tests/logs/stdio

```
FAILED: none-vm-checked debug_x64 co19/LibTest/async/Stream/Stream.periodic_A01_t01
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
Unhandled exception:
Expect.isTrue(false, 'expected=0:00:00.200000, actual=0:00:00.199615') fails.
#0      _fail (file:///E:/b/build/slave/vm-win64-debug-be/build/sdk/tests/co19/src/Utils/expect.dart:17:5)
#1      Expect.isTrue (file:///E:/b/build/slave/vm-win64-debug-be/build/sdk/tests/co19/src/Utils/expect_common.dart:36:5)
#2      check.<anonymous closure> (file:///E:/b/build/slave/vm-win64-debug-be/build/sdk/tests/co19/src/LibTest/async/Stream/Stream.periodic_A01_t01.dart:37:12)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1087)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#6      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#7      _StreamController._add (dart:async/stream_controller.dart:616)
#8      _StreamController.add (dart:async/stream_controller.dart:562)
#9      Stream.Stream.periodic.sendEvent (dart:async/stream.dart:159)
#10     Stream.Stream.periodic.startPeriodicTimer.<anonymous closure> (dart:async/stream.dart:165)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by rmacnak-google** [comment]
22683803edd6873c6b5c321897d485ecd97f56c2
