### ISSUE TITLE
Analyzer: crash in mirrors/metadata_allowed_values_test/29

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25287]
```
NoSuchMethodError: method not found: 'librarySource'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ComputeConstantDependenciesTask.buildInputs (package:analyzer/src/task/dart.dart:1741:28)
#3      WorkItem.WorkItem (package:analyzer/src/task/driver.dart:608:20)
#4      WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:708:22)
#5      _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:816:17)
#6      CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:395:35)
#7      WorkOrder.moveNext.<anonymous closure> (package:analyzer/src/task/driver.dart:782:31)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188:15)
#9      WorkOrder.moveNext (package:analyzer/src/task/driver.dart:774:44)
#10     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:106:26)
#11     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:636:14)
#12     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:609:12)
#13     AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:259:22)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188:15)
#15     AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:258:31)
#16     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165:26)
#17     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126:12)
#18     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:533:34)
#19     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:184:30)
#20     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:127:14)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188:15)
#22     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:126:27)
#23     Driver.start.<anonymous closure> (package:analyzer_cli/src/driver.dart:109:16)
#24     _BatchRunner.runAsBatch.<anonymous closure> (package:analyzer_cli/src/driver.dart:608:39)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1087)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#30     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#31     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127)
#32     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102)
#33     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#34     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#36     _RootZone.runUnaryGuarded (dart:async/zone.dart:1087)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#47     _RootZone.runUnaryGuarded (dart:async/zone.dart:1087)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#50     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#51     _StreamController._add (dart:async/stream_controller.dart:616)
#52     _StreamController.add (dart:async/stream_controller.dart:562)
#53     _Socket._onData (dart:io-patch/socket_patch.dart:1646)
#54     _RootZone.runUnaryGuarded (dart:async/zone.dart:1087)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#57     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#58     _StreamController._add (dart:async/stream_controller.dart:616)
#59     _StreamController.add (dart:async/stream_controller.dart:562)
#60     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1215)
#61     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#64     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by bwilkerson** [comment]
I believe that this has been fixed in the latest (bleeding edge) code base. Please re-open this issue if you see this problem again.
