### ISSUE TITLE
exception from dartanalyzer

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25302]
From the latest dev release (`dartanalyzer version 1.14.0-dev.5.0`):

```
Caused by The null object does not have a getter 'bound'.

NoSuchMethodError: method not found: 'bound'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ErrorVerifier._checkForTypeParameterSupertypeOfItsBound (package:analyzer/src/generated/error_verifier.dart:5351)
#3      ErrorVerifier.visitTypeParameter (package:analyzer/src/generated/error_verifier.dart:1072)
#4      TypeParameter.accept (package:analyzer/src/generated/ast.dart:19344)
#5      NodeList.accept (package:analyzer/src/generated/ast.dart:12645)
#6      TypeParameterList.visitChildren (package:analyzer/src/generated/ast.dart:19406)
#7      RecursiveAstVisitor.visitTypeParameterList (package:analyzer/src/generated/ast.dart:15556)
#8      TypeParameterList.accept (package:analyzer/src/generated/ast.dart:19402)
#9      AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3062)
#10     MethodDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:12077)
...
```

**Comment by devoncarew** [comment]
This is when run with most analysis flags on, including strong mode.

**Comment by bwilkerson** [comment]
The exception is occurring on the last line:

  bool _checkForTypeParameterSupertypeOfItsBound(TypeParameter parameter) {
    TypeParameterElement element = parameter.element;
    // prepare bound
    DartType bound = element.bound;

This means that we have a type parameter for which there is no element. There's only one place I can think of where this might happen, so I've added debugging code (https://codereview.chromium.org/1713793002/) to help catch the problem earlier.

Please re-open this issue if you see this behavior again.
