### ISSUE TITLE
Stacktraces in dart2js output are truncated at Closure_fromTearOff

### ISSUE THREAD

**Issue by jbdeboer** [dart-lang/sdk#25306]
Our Dart application is throwing an error (printed as "null") and the stack trace is printed as:

```
  at dart.wrapException (http://iyan84:19320/fe3/web/main_debug.dart.js:4277:17)
    at ExceptionHandler.call$3 (http://iyan84:19320/fe3/web/main_debug.dart.js:52160:19)
    at ExceptionHandler.dart.ExceptionHandler.call$3 [as call$2] (http://iyan84:19320/fe3/web/main_debug.dart.js:52192:21)
    at PlatformRef___initApp__closure0.dart.PlatformRef___initApp__closure0.call$2 (http://iyan84:19320/fe3/web/main_debug.dart.js:45319:45)
    at NgZone.dart.NgZone._onErrorHandler$2 (http://iyan84:19320/fe3/web/main_debug.dart.js:41446:37)
    at NgZone.dart.NgZone._onErrorWithLongStackTrace$2 (http://iyan84:19320/fe3/web/main_debug.dart.js:41419:18)
    at eval (eval at <anonymous> (http://iyan84:19320/fe3/web/main_debug.dart.js:4599:14), <anonymous>:2:40)
    at dart._rootRunBinary (http://iyan84:19320/fe3/web/main_debug.dart.js:88710:18)
    at StackZoneSpecification.dart.StackZoneSpecification.handleUncaughtError$5 (http://iyan84:19320/fe3/web/main_debug.dart.js:128299:41)
    at eval (eval at <anonymous> (http://iyan84:19320/fe3/web/main_debug.dart.js:4599:14), <anonymous>:2:46)"
```

Line 4599 at the end of the stacktrace is "  return new Function(t1 + H.S(t2) + "}")()".  It is the last line of Closure_forwardCallTo which is called from Closure_fromTearOff.

We have no idea who called "eval" or Closure_fromTearOff and therefore have no idea what application code is responsible for this error.

**Comment by sigmundch** [comment]
@jbdeboer - I might be missing something. 

It sounds like closure-fromtearoff is a callback to some async API in the app and basically what we show is the top of the stack at that moment. Are you looking to know where that callback was registered? (e.g. like using the `stack_trace` package to track asynchronous call stacks using zones) or do you believe some stack frames are actually missing because of how we generate code using `new Function`?

If it is the latter, you could try running the app with the `--csp` support flag. That will generate bigger code, but it might reveal whether there is an issue that follows from how we generate some code dynamically.
