### ISSUE TITLE
AnalysisServer gets "FileSystemException" via Webstorm WS-143.1559.5

### ISSUE THREAD

**Issue by corgrath** [dart-lang/sdk#25315]
Using WebStorm WS-143.1559.5 and Dart SDK 1.13.1, the AnalysisServer gets:

	2015-12-26 10:41:03,053 [  52410]  DEBUG - yzer.DartAnalysisServerService - analysis_setPriorityFiles, files:
	C:\christoffer\Dropbox\computer_mainstation\webstorm\labs-chat-service\src\backend\webentry\LeaveChannelWebEntry.dart 
	2015-12-26 10:41:03,053 [  52410]  DEBUG - yzer.DartAnalysisServerService - analysis_setSubscriptions, subscriptions:
	{HIGHLIGHTS=[C:\christoffer\Dropbox\computer_mainstation\webstorm\labs-chat-service\src\backend\webentry\LeaveChannelWebEntry.dart], OVERRIDES=[C:\christoffer\Dropbox\computer_mainstation\webstorm\labs-chat-service\src\backend\webentry\LeaveChannelWebEntry.dart], NAVIGATION=[C:\christoffer\Dropbox\computer_mainstation\webstorm\labs-chat-service\src\backend\webentry\LeaveChannelWebEntry.dart], IMPLEMENTED=[C:\christoffer\Dropbox\computer_mainstation\webstorm\labs-chat-service\src\backend\webentry\LeaveChannelWebEntry.dart]} 
	2015-12-26 10:41:03,360 [  52717]  DEBUG - yzer.DartAnalysisServerService - analysis_getErrors(C:\christoffer\Dropbox\computer_mainstation\webstorm\labs-chat-service\src\backend\webentry\LeaveChannelWebEntry.dart) 
	2015-12-26 10:41:06,072 [  55429]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.13.1, server version 1.12.0, FATAL error: Failed to handle request: {clientRequestTime: 1451122863052, params: {included: [C:\christoffer\Dropbox\computer_mainstation\webstorm\labs-chat-service], excluded: [C:\christoffer\Dropbox\computer_mainstation\webstorm\labs-chat-service\.idea, C:\christoffer\Dropbox\computer_mainstation\webstorm\labs-chat-service\.pub], packageRoots: {}}, method: analysis.setAnalysisRoots, id: 3}
	FileSystemException: Directory listing failed, path = 'C:\christoffer\Dropbox\computer_mainstation\webstorm\labs-chat-service\tools\node_modules\grunt-contrib-less\node_modules\less\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\is-property\*' (OS Error: The system cannot find the path specified.
	, errno = 3)
	#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:913)
	#1      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:715)
	#2      _rootRunBinary (dart:async/zone.dart:930)
	#3      _CustomZone.runBinary (dart:async/zone.dart:818)
	#4      runZoned.<anonymous closure> (dart:async/zone.dart:1220)
	#5      _CustomZone.handleUncaughtError (dart:async/zone.dart:784)
	#6      _nullErrorHandler (dart:async/stream_impl.dart:575)
	#7      _rootRunBinary (dart:async/zone.dart:926)
	#8      _CustomZone.runBinary (dart:async/zone.dart:818)
	#9      _CustomZone.runBinaryGuarded (dart:async/zone.dart:724)
	#10     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
	#11     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
	#12     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:279)
	#13     _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:396)
	#14     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:331)
	#15     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:395)
	#16     _BroadcastStreamController.addError (dart:async/broadcast_stream_controller.dart:267)
	#17     _rootRunBinary (dart:async/zone.dart:926)
	#18     _CustomZone.runBinary (dart:async/zone.dart:818)
	#19     _CustomZone.runBinaryGuarded (dart:async/zone.dart:724)
	#20     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
	#21     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
	#22     _DelayedError.perform (dart:async/stream_impl.dart:606)
	#23     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:711)
	#24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:671)
	#25     _rootRun (dart:async/zone.dart:903)
	#26     _CustomZone.run (dart:async/zone.dart:802)
	#27     _CustomZone.runGuarded (dart:async/zone.dart:708)
	#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
	#29     _rootRun (dart:async/zone.dart:907)
	#30     _CustomZone.run (dart:async/zone.dart:802)
	#31     _CustomZone.runGuarded (dart:async/zone.dart:708)
	#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
	#33     _microtaskLoop (dart:async/schedule_microtask.dart:43)
	#34     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
	#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
	#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
	 
	java.lang.Throwable
		at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
		at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:204)
		at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
		at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
		at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
		at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
		at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
		at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
	2015-12-26 10:41:06,072 [  55429]  ERROR - yzer.DartAnalysisServerService - WebStorm 11.0.3  Build #WS-143.1559.5 
	2015-12-26 10:41:06,072 [  55429]  ERROR - yzer.DartAnalysisServerService - JDK: 1.8.0_51 
	2015-12-26 10:41:06,072 [  55429]  ERROR - yzer.DartAnalysisServerService - VM: Java HotSpot(TM) Server VM 
	2015-12-26 10:41:06,072 [  55429]  ERROR - yzer.DartAnalysisServerService - Vendor: Oracle Corporation 
	2015-12-26 10:41:06,072 [  55429]  ERROR - yzer.DartAnalysisServerService - OS: Windows 8 
	2015-12-26 10:41:06,072 [  55429]  ERROR - yzer.DartAnalysisServerService - Last Action: SaveAll 
	2015-12-26 10:41:06,072 [  55429]  DEBUG - yzer.DartAnalysisServerService - stopping server 

The directory
```
C:\christoffer\Dropbox\computer_mainstation\webstorm\labs-chat-service\tools\node_modules\grunt-contrib-less\node_modules\less\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\is-property\
```

does exist, but maybe the server crashes due to the insane long directory path.

Node.js NPM can create these crazy long paths for their modules.

I have also reported this bug to JetBrains WebStorm support (issue ID: #85180).

Any advice or suggestions on how to bypass this problem?

**Comment by alexander-doroshko** [comment]
I guess the problem is that Dart can't work with long paths on Windows.

**Comment by alexander-doroshko** [comment]
Probably related to #24229. Seems to be a major issue that was undeservingly forgotten.
