### ISSUE TITLE
process.stdin.add incorrectly throw an error

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25348]
If you write to a closed stdin stream for a process, it can produce the following error (with no useful stack information; see #25342):

```
Unhandled exception:
SocketException: Write failed, port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

According to [the IOSink documentation](https://api.dartlang.org/1.13.0/dart-io/IOSink-class.html), writing to a closed sink should not cause an error:

> If data is added to the IOSink after the sink is closed, the data will be ignored.

To reproduce:

```dart
// inner.dart
import 'dart:async';
import 'dart:io';

main() async {
  stdin.listen(null).cancel();
  await new Future.delayed(new Duration(seconds: 5));
}

// outer.dart
import 'dart:async';
import 'dart:io';

main() async {
  var process = await Process.start(Platform.executable, ['inner.dart']);
  await new Future.delayed(new Duration(seconds: 1));
  process.stdin.writeln('hello');
}
```

**Comment by floitschG** [comment]
Is this fixed?

**Comment by nex3** [comment]
No, my example still produces an error.

**Comment by floitschG** [comment]
On which platform? I tried it yesterday, and I didn't see any error.

**Comment by nex3** [comment]
Ubuntu 14.04, on a39234eede23e97aba5b15ea3430b30a9a455a18 and 1.21.0.

**Comment by floitschG** [comment]
That's weird. I'm just one commit ahead (2547caab258bec7b8d9742df2cce3fdfc2680786), and that one should definitely not have any impact.

Do you need to run this in a loop?

(I'm on Goobuntu, too)

**Comment by nex3** [comment]
No, I just created the two files and ran `dart outer.dart`.

**Comment by floitschG** [comment]
aah. I didn't realize that the path to `inner.dart` wasn't relative to `outer.dart`.
I can reproduce now.

**Comment by a-siva** [comment]
@floitschG the code in _NativeSocket gets an exception when doing the write for the code here:
    if (result is OSError) {
      scheduleMicrotask(() => reportError(result, "Write failed"));
      result = 0;
    }
We could tag on the additional error string and error code to the error string which in this case was
OSError {
  final String message = 'Broken pipe'
  final int errorCode = 32
 }

Not sure who higher up in the call chain is supposed to catch the exception and drop it to satisy
the API documentation "If data is added to the IOSink after the sink is closed, the data will be ignored".

I wouldn't want to do it here as this is fairly low level and errors from here should be reported.

**Comment by zanderso** [comment]
I've been looking into this a bit more. I think the problem is that the IOSink, not knowing that the other side has gone down, doesn't know that it should be closed. It doesn't know that it should be closed until it attempts the write and it fails at the OS level. At that point, the OS error gets put on the 'done' Future on the IOSink, and only after that happens does the IOSink consider itself to be closed.

One way to address this in the program would be by saying:

```dart
process.stdin.done.then((_) {...}, onError: (e) {...});
process.stdin.writeln(...);
```

Maybe it would be best to consider this a workaround, and @floitschG can propose a cleaner API for this.

/cc @munificent
