### ISSUE TITLE
Directory.delete(recursive: true) flakily fails on Windows

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25353]
We're seeing this error on [the pub package bots](https://build.chromium.org/p/client.dart.packages/builders/packages-windows-pub/builds/117/steps/annotated_steps/logs/stdio):

```
FileSystemException: Deletion failed, path = 'C:\Users\CHROME~1\AppData\Local\Temp\pub_d56c58ae-b3f4-11e5-bef0-005056030165' (OS Error: The directory is not empty.
, errno = 145)
```

The stack trace indicates that this is coming from [line 389 of `lib/src/io.dart`](https://github.com/dart-lang/pub/blob/57a17f2567d1ff3325960d0960f939fa243b5fd7/lib/src/io.dart#L389), which runs `new Directory(path).deleteSync(recursive: true)`. A recursive deletion shouldn't fail because the directory isn't empty; the whole point is to delete the directory's contents as well.

**Comment by ricowind** [comment]
This may very well be an IO bug, but I seem to recall having seen this in cases where there was open files in the directory - windows does not allow deleting a file in use. Nonetheless, the deleteSync call should throw earlier, stating "I can't delete file XXX/foobar.dart" instead which is really the issue in that case. Not really a solution, just something to consider.

**Comment by DanTup** [comment]
I just hit this too, while trying to reproduce anothre bug. What's weird is that it only seems to happen on me when I have a watcher set up:

```dart
import 'dart:io';
import 'package:watcher/watcher.dart' as watcher;

const srcFolder = 'M:\\Dev\\TestStuff\\repo_46616\\build';

Future<void> main() async {
  final destFolder = await Directory.systemTemp.createTemp();
  print('Copying $srcFolder to $destFolder...');

  final res = await Process.run(
      "cmd", ["/c", "xcopy", "/E", "/I", srcFolder, destFolder.path]);
  print(res.stderr);

  print('Setting up watcher...');
  final watch = watcher.DirectoryWatcher(destFolder.path);
  watch.events.listen(
    (e) => print('${e.type}: ${e.path}'),
    onError: (e, s) => print('Watch error: $e\n$s'),
  );

  print('Deleting $destFolder');
  await destFolder.delete(recursive: true);

  print('Done!');
}
```

If I run this as-is, it fails:

```
Copying M:\Dev\TestStuff\repo_46616\build to Directory: 'X:\Danny Temp\cc0fa4e4-3c74-11ea-8435-d05099106836'...

Setting up watcher...
Deleting Directory: 'X:\Danny Temp\cc0fa4e4-3c74-11ea-8435-d05099106836'
Unhandled exception:
FileSystemException: Deletion failed, path = 'X:\Danny Temp\cc0fa4e4-3c74-11ea-8435-d05099106836' (OS Error: The directory is not empty.

, errno = 145)
#0      _Directory._delete.<anonymous closure>  (dart:io/directory_impl.dart:199:9)
#1      _RootZone.runUnary  (dart:async/zone.dart:1381:54)
#2      _FutureListener.handleValue  (dart:async/future_impl.dart:139:18)
```

However if I comment out the watcher code, it works:

```
Copying M:\Dev\TestStuff\repo_46616\build to Directory: 'X:\Danny Temp\ffc85a27-3c74-11ea-8435-d05099106836'...

Deleting Directory: 'X:\Danny Temp\ffc85a27-3c74-11ea-8435-d05099106836'
Done!
Exited
```

I ran it many times, and got the same results.
