### ISSUE TITLE
JsFunction.withThis + async =  dart2js crash

### ISSUE THREAD

**Issue by amaurel** [dart-lang/sdk#25396]
dart2js crash on the following code.

```
import 'dart:js' as libjs;
main() async {
  var fnClickCallback = new libjs.JsFunction.withThis((_){});
}
```

Ubuntu : 14.04
Dart : Dart VM version: 1.13.2 (Tue Jan  5 16:03:09 2016) on "linux_x64"

**Comment by zoechi** [comment]
Do you get an error message?

**Comment by sigmundch** [comment]
Thanks for reporting. Seems like an error with the async rewriter.

Here is the crash stack trace when using 1.14.0-dev.5.0:

```
The compiler crashed: RangeError (index): Invalid value: Valid value range is empty: -1
#0      List.[] (dart:core-patch/growable_array.dart:135)
#1      List.removeLast (dart:core-patch/growable_array.dart:198)
#2      AsyncRewriterBase.translateJump (package:compiler/src/js/rewrite_async.dart:950)
#3      AsyncRewriterBase.visitReturn (package:compiler/src/js/rewrite_async.dart:1299)
#4      Return.accept (package:js_ast/src/nodes.dart:402)
#5      AsyncRewriterBase.visitStatement (package:compiler/src/js/rewrite_async.dart:356)
#6      AsyncRewriterBase.visitBlock (package:compiler/src/js/rewrite_async.dart:836)
#7      Block.accept (package:js_ast/src/nodes.dart:255)
#8      AsyncRewriterBase.visitStatement (package:compiler/src/js/rewrite_async.dart:356)
#9      AsyncRewriterBase.visitFun (package:compiler/src/js/rewrite_async.dart:680)
#10     Fun.accept (package:js_ast/src/nodes.dart:913)
#11     AsyncRewriterBase.visitExpression (package:compiler/src/js/rewrite_async.dart:372)
#12     AsyncRewriterBase.withExpression (package:compiler/src/js/rewrite_async.dart:409)
#13     AsyncRewriterBase.visitReturn (package:compiler/src/js/rewrite_async.dart:1294)
#14     Return.accept (package:js_ast/src/nodes.dart:402)
#15     AsyncRewriterBase.visitStatement (package:compiler/src/js/rewrite_async.dart:356)
#16     AsyncRewriterBase.visitBlock (package:compiler/src/js/rewrite_async.dart:836)
#17     Block.accept (package:js_ast/src/nodes.dart:255)
#18     AsyncRewriterBase.visitStatement (package:compiler/src/js/rewrite_async.dart:356)
#19     AsyncRewriterBase.visitFun (package:compiler/src/js/rewrite_async.dart:680)
#20     Fun.accept (package:js_ast/src/nodes.dart:913)
#21     AsyncRewriterBase.visitExpression (package:compiler/src/js/rewrite_async.dart:372)
#22     AsyncRewriterBase.withCallTargetExpression (package:compiler/src/js/rewrite_async.dart:434)
#23     AsyncRewriterBase.visitCall (package:compiler/src/js/rewrite_async.dart:853)
#24     Call.accept (package:js_ast/src/nodes.dart:724)
#25     AsyncRewriterBase.visitExpressionIgnoreResult (package:compiler/src/js/rewrite_async.dart:365)
#26     AsyncRewriterBase.visitExpressionStatement (package:compiler/src/js/rewrite_async.dart:1003)
#27     ExpressionStatement.accept (package:js_ast/src/nodes.dart:268)
#28     AsyncRewriterBase.visitStatement (package:compiler/src/js/rewrite_async.dart:356)
#29     AsyncRewriterBase.visitBlock (package:compiler/src/js/rewrite_async.dart:836)
#30     Block.accept (package:js_ast/src/nodes.dart:255)
#31     AsyncRewriterBase.visitStatement (package:compiler/src/js/rewrite_async.dart:356)
#32     AsyncRewriterBase.visitFun (package:compiler/src/js/rewrite_async.dart:680)
#33     Fun.accept (package:js_ast/src/nodes.dart:913)
#34     AsyncRewriterBase.rewrite (package:compiler/src/js/rewrite_async.dart:210)
#35     JavaScriptBackend.rewriteAsync (package:compiler/src/js_backend/backend.dart:2628)
#36     SsaFunctionCompiler.compile (package:compiler/src/ssa/builder.dart:28)
#37     JavaScriptBackend.codegen (package:compiler/src/js_backend/backend.dart:1633)
#38     Compiler.codegen (package:compiler/src/compiler.dart:1242)
#39     CodegenWorkItem.run (package:compiler/src/common/codegen.dart:272)
#40     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:1118)
#41     _CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:1752)
#42     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:1117)
#43     QueueFilter.processWorkItem (package:compiler/src/enqueue.dart:1014)
#44     Enqueuer.forEach (package:compiler/src/enqueue.dart:704)
#45     Compiler.emptyQueue (package:compiler/src/compiler.dart:1116)
#46     Compiler.processQueue (package:compiler/src/compiler.dart:1144)
#47     Compiler.compileLoadedLibraries (package:compiler/src/compiler.dart:1067)
#48     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:884)
#49     _RootZone.runUnary (dart:async/zone.dart:1149)
#50     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#51     _Future._propagateToListeners (dart:async/future_impl.dart:637)
#52     _Future._completeWithValue (dart:async/future_impl.dart:424)
#53     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#54     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by amaurel** [comment]
yes, I get similar message.

**Comment by greglittlefield-wf** [comment]
Getting a similar error.

OS X: 10.11.2 (15C50)
Dart: Dart VM version: 1.13.2 (Tue Jan  5 06:36:44 2016) on "macos_x64"

```
[Error from Dart2JS on web_skin_dart|test/ui_components_test.dart.sauce_browser_test.dart]:
test/ui_components/panel/abstract_collapse_test.dart:32:63:
The compiler crashed when compiling this element.
    test('cleans up the onTransitionEnd listener on unmount', () async {
                                                              ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Build error:
Transform Dart2JS on web_skin_dart|test/ui_components_test.dart.sauce_browser_test.dart threw error: RangeError (index): Invalid value: Valid value range is empty: -1
dart:core                                                      List.removeLast
package:compiler_unsupported/src/js/rewrite_async.dart 950     AsyncRewriterBase.translateJump
package:compiler_unsupported/src/js/rewrite_async.dart 1299    AsyncRewriterBase.visitReturn
package:js_ast/src/nodes.dart 402                              Return.accept
package:compiler_unsupported/src/js/rewrite_async.dart 356     AsyncRewriterBase.visitStatement
package:compiler_unsupported/src/js/rewrite_async.dart 836     AsyncRewriterBase.visitBlock
package:js_ast/src/nodes.dart 255                              Block.accept
package:compiler_unsupported/src/js/rewrite_async.dart 356     AsyncRewriterBase.visitStatement
package:compiler_unsupported/src/js/rewrite_async.dart 680     AsyncRewriterBase.visitFun
package:js_ast/src/nodes.dart 913                              Fun.accept
package:compiler_unsupported/src/js/rewrite_async.dart 372     AsyncRewriterBase.visitExpression
package:compiler_unsupported/src/js/rewrite_async.dart 409     AsyncRewriterBase.withExpression
package:compiler_unsupported/src/js/rewrite_async.dart 1294    AsyncRewriterBase.visitReturn
package:js_ast/src/nodes.dart 402                              Return.accept
package:compiler_unsupported/src/js/rewrite_async.dart 356     AsyncRewriterBase.visitStatement
package:compiler_unsupported/src/js/rewrite_async.dart 836     AsyncRewriterBase.visitBlock
package:js_ast/src/nodes.dart 255                              Block.accept
package:compiler_unsupported/src/js/rewrite_async.dart 356     AsyncRewriterBase.visitStatement
package:compiler_unsupported/src/js/rewrite_async.dart 680     AsyncRewriterBase.visitFun
package:js_ast/src/nodes.dart 913                              Fun.accept
package:compiler_unsupported/src/js/rewrite_async.dart 372     AsyncRewriterBase.visitExpression
package:compiler_unsupported/src/js/rewrite_async.dart 434     AsyncRewriterBase.withCallTargetExpression
package:compiler_unsupported/src/js/rewrite_async.dart 853     AsyncRewriterBase.visitCall
package:js_ast/src/nodes.dart 724                              Call.accept
package:compiler_unsupported/src/js/rewrite_async.dart 372     AsyncRewriterBase.visitExpression
package:compiler_unsupported/src/js/rewrite_async.dart 505     AsyncRewriterBase.withExpressions.<fn>
dart:core                                                      List.addAll
package:compiler_unsupported/src/js/rewrite_async.dart 504     AsyncRewriterBase.withExpressions
package:compiler_unsupported/src/js/rewrite_async.dart 1204    AsyncRewriterBase.visitNew.<fn>
package:compiler_unsupported/src/js/rewrite_async.dart 451     AsyncRewriterBase.withCallTargetExpression
package:compiler_unsupported/src/js/rewrite_async.dart 1203    AsyncRewriterBase.visitNew
package:js_ast/src/nodes.dart 741                              New.accept
package:compiler_unsupported/src/js/rewrite_async.dart 372     AsyncRewriterBase.visitExpression
package:compiler_unsupported/src/js/rewrite_async.dart 505     AsyncRewriterBase.withExpressions.<fn>
dart:core                                                      List.addAll
package:compiler_unsupported/src/js/rewrite_async.dart 504     AsyncRewriterBase.withExpressions
package:compiler_unsupported/src/js/rewrite_async.dart 854     AsyncRewriterBase.visitCall.<fn>
package:compiler_unsupported/src/js/rewrite_async.dart 451     AsyncRewriterBase.withCallTargetExpression
package:compiler_unsupported/src/js/rewrite_async.dart 853     AsyncRewriterBase.visitCall
package:js_ast/src/nodes.dart 724                              Call.accept
package:compiler_unsupported/src/js/rewrite_async.dart 365     AsyncRewriterBase.visitExpressionIgnoreResult
package:compiler_unsupported/src/js/rewrite_async.dart 1003    AsyncRewriterBase.visitExpressionStatement
package:js_ast/src/nodes.dart 268                              ExpressionStatement.accept
package:compiler_unsupported/src/js/rewrite_async.dart 356     AsyncRewriterBase.visitStatement
package:compiler_unsupported/src/js/rewrite_async.dart 836     AsyncRewriterBase.visitBlock
package:js_ast/src/nodes.dart 255                              Block.accept
package:compiler_unsupported/src/js/rewrite_async.dart 356     AsyncRewriterBase.visitStatement
package:compiler_unsupported/src/js/rewrite_async.dart 680     AsyncRewriterBase.visitFun
package:js_ast/src/nodes.dart 913                              Fun.accept
package:compiler_unsupported/src/js/rewrite_async.dart 210     AsyncRewriterBase.rewrite
package:compiler_unsupported/src/js_backend/backend.dart 2755  JavaScriptBackend.rewriteAsync
package:compiler_unsupported/src/ssa/builder.dart 28           SsaFunctionCompiler.compile
package:compiler_unsupported/src/js_backend/backend.dart 1594  JavaScriptBackend.codegen
package:compiler_unsupported/src/compiler.dart 1223            Compiler.codegen
package:compiler_unsupported/src/common/codegen.dart 197       CodegenWorkItem.run
package:compiler_unsupported/src/compiler.dart 1102            Compiler.emptyQueue.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 1691            _CompilerDiagnosticReporter.withCurrentElement
package:compiler_unsupported/src/compiler.dart 1101            Compiler.emptyQueue.<fn>
package:compiler_unsupported/src/enqueue.dart 1072             QueueFilter.processWorkItem
package:compiler_unsupported/src/enqueue.dart 769              Enqueuer.forEach
package:compiler_unsupported/src/compiler.dart 1100            Compiler.emptyQueue
package:compiler_unsupported/src/compiler.dart 1128            Compiler.processQueue
package:compiler_unsupported/src/compiler.dart 1051            Compiler.compileLoadedLibraries
package:compiler_unsupported/src/compiler.dart 871             Compiler.runCompiler.<fn>
```

**Comment by kmillikin** [comment]
Thanks a lot for the report, I'll take a look.  I won't get to it for at least a week, though.

**Comment by kmillikin** [comment]
The async transformer is transforming the bodies of nested JS function but it is not analyzing them.

These functions seem to only occur as foreign code embedded by dart2js to implement dart:js, and they are not async so they don't really need to be transformed.  I'll put in a fix (next week).
