### ISSUE TITLE
exception from analysis server related to generic methods

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#25409]
Seems to be coming from this line:
```dart
paramTypes[i] = genericParameters[i].type;
```
genericParameters comes from ResolverVisitor.resolveArgumentsToParameters, where it's totally legal to return `null` in one of the positions. We should handle that gracefully.

```
Caused by The null object does not have a getter 'type'.

NoSuchMethodError: method not found: 'type'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      StaticTypeAnalyzer._inferMethodInvocationGeneric (package:analyzer/src/generated/static_type_analyzer.dart:1825)
#3      StaticTypeAnalyzer._inferMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:1796)
#4      StaticTypeAnalyzer.visitMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:735)
#5      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:8244)
#6      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:9164)
#7      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:8244)
#8      AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:1110)
<snip>
```

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1579503005/

**Comment by jmesserly** [comment]
Caught this trying to run strong mode on Analyzer itself, slowly going through and fixing errors. Editing code is a great way to catch crash bugs from invalid intermediate edit states. :)
