### ISSUE TITLE
cps crashes with simple sync* program

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#25460]
```dart
foo() sync* {
  var y = 0;
  for (var x in [1, 2, 3]) {
    yield x;
    y = x;
  }
  yield y;
}


main() {
  print(foo());
}
```

Trying to compile the above program with `--use-cps-ir` causes this failure:

```
foo.dart:1:1:
Internal Error: The compiler crashed when compiling this element.
foo() sync* {
^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Tree IR integrity violation in function(foo):
variable(foo#x) used out of scope
#0      CheckTreeIntegrity.error (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_integrity.dart:139:5)
#1      CheckTreeIntegrity.read (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_integrity.dart:46:7)
#2      CheckTreeIntegrity.visitVariableUse (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_integrity.dart:65:5)
#3      VariableUse.accept (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:129:48)
#4      RecursiveVisitor.visitExpression (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:1100:38)
#5      RecursiveVisitor.visitYield (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:1308:5)
#6      Yield.accept (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:959:20)
#7      RecursiveVisitor.visitStatement (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:1101:36)
#8      RecursiveVisitor.visitIf (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:1190:5)
#9      If.accept (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:623:47)
#10     RecursiveVisitor.visitStatement (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:1101:36)
#11     CheckTreeIntegrity.visitJumpTargetBody (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_integrity.dart:87:5)
#12     CheckTreeIntegrity.visitWhileTrue (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_integrity.dart:102:5)
#13     WhileTrue.accept (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:492:47)
#14     RecursiveVisitor.visitStatement (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:1101:36)
#15     RecursiveVisitor.visitExpressionStatement (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:1213:5)
#16     ExpressionStatement.accept (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:633:47)
#17     RecursiveVisitor.visitStatement (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_nodes.dart:1101:36)
#18     CheckTreeIntegrity.checkBody (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_integrity.dart:134:5)
#19     CheckTreeIntegrity.check (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/tree_ir/tree_ir_integrity.dart:144:5)
#20     CpsFunctionCompiler.checkTreeIntegrity.<anonymous closure> (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/js_backend/codegen/task.dart:256:32)
#21     CompilerTask.measureSubtask (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:79:37)
#22     CpsFunctionCompiler.checkTreeIntegrity (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/js_backend/codegen/task.dart:255:26)
#23     CpsFunctionCompiler.optimizeTreeIr.applyTreePass (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/js_backend/codegen/task.dart:267:14)
#24     CpsFunctionCompiler.optimizeTreeIr.<anonymous closure> (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/js_backend/codegen/task.dart:271:20)
#25     CompilerTask.measure (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:55:37)
#26     CpsFunctionCompiler.optimizeTreeIr (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/js_backend/codegen/task.dart:270:26)
#27     CpsFunctionCompiler.compile.<anonymous closure> (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/js_backend/codegen/task.dart:114:24)
#28     _CompilerDiagnosticReporter.withCurrentElement (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:1751:15)
#29     CpsFunctionCompiler.compile (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/js_backend/codegen/task.dart:96:21)
#30     JavaScriptBackend.codegen (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/js_backend/backend.dart:1633:47)
#31     Compiler.codegen (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:1241:20)
#32     CodegenWorkItem.run (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/common/codegen.dart:272:21)
#33     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:1117:46)
#34     _CompilerDiagnosticReporter.withCurrentElement (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:1751:15)
#35     Compiler.emptyQueue.<anonymous closure> (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:1116:14)
#36     QueueFilter.processWorkItem (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/enqueue.dart:1014:6)
#37     Enqueuer.forEach (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/enqueue.dart:704:16)
#38     Compiler.emptyQueue (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:1115:11)
#39     Compiler.processQueue (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:1143:5)
#40     Compiler.compileLoadedLibraries (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:1066:5)
#41     Compiler.runInternal.<anonymous closure> (file:///home/het/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:884:7)
#42     _RootZone.runUnary (dart:async/zone.dart:1149)
#43     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#44     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#45     _Future._completeWithValue (dart:async/future_impl.dart:376)
#46     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#48     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by hterkelsen** [comment]
If you don't compile in checked mode, the program seems to run correctly:

```
> $DART/third_party/d8/linux/d8 out.js
(1, 2, 3, 3)
```

**Comment by asgerf** [comment]
https://codereview.chromium.org/1584253003/
