### ISSUE TITLE
Inconsistent error message about yield statement location

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25495]
Dart Programming Language Speciﬁcation (4th edition draft) version 1.11 chapter 17.16.1 Yield reads:
>It is a compile-time error if a yield statement appears in a function that is not a generator function.

The following examples demonstrate the problem
```dart
main() {
  yield 1;
}
```
>error: line 18 pos 9: semicolon expected  yield 1;

```dart
main() async {
  yield 1;
}
```

>error: line 18 pos 3: yield statement only allowed in generator functions  yield 1;

Dart VM version: 1.13.2 (Tue Jan 05 06:46:24 2016) on "windows_x64"

Please, make compile error messages consistent.

**Comment by alsemenov** [comment]
the same problem is observed for yield-each statement:
```dart
main() {
  yield* [1];
}
```

>Unhandled exception:
>No top-level getter 'yield' declared.
>
>NoSuchMethodError: method not found: 'yield'
>Receiver: top-level
>Arguments: [...]
>#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:188)
>#1      main (file:///D:/dev/dart/col9/Language/Statements/Yield_and_Yield_Each/Yield_Each/location_t01.dart:18:3)
>#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
>#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)


```dart
import 'dart:async';

main() async {
  yield* new Stream<int>.fromIterable([1]);
}
```

>'file:///D:/dev/dart/col9/Language/Statements/Yield_and_Yield_Each/Yield_Each/location_t02.dart': >error: line 19 pos 3: yield* statement only allowed in generator functions

**Comment by lrhn** [comment]
The `yield*` example is particulary interesting - it's *not* a "yield statement", nor is it a `yield*` statement - it's a multiplication of an undeclared variable. It has to be:

    foo(yield) {
      yield* 42;
      yield (42);
    }
I can pass a value to that function that makes it work, so it is definitely not a yield* or yield statement in there.

The "yield" name isn't a contextually reserved word in a non-async[*]/sync* function, so you can't write a yield/yield* statement at all in these functions. 
So, effectively, the syntax error can only occur in an "async" function - it's the only type of function that allows yield statements *syntactically*, but isn't a generator function.

I find that VM, dart2js and analyzer all agree on this - they have a compile-time error if you have a yield statement in an "async" function.

**Comment by alsemenov** [comment]
I am not sure what is the best solution for this issue. But I can suggest at least three options:
1. Modify the specification, declare the yield as reserved word
2. Modify the specification, add clarifications about yield in synchronous functions, explaining that yield is not a statement inside synchronous function.
3. Modify compiler, if yield is not defined in the current scope, then consider it as a statement and report correct error. If yield is defined properly as variable, function parameter, etc, than report no error.
