### ISSUE TITLE
incremental analysis shows no errors or warnings after fixing syntax for a generic type

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25522]
To reproduce, paste into Atom:
```
class MockSdk implements DartSdk {
  static const List<SdkLibrary LIBRARIES = const [
    LIB_CORE,
    LIB_ASYNC,
    LIB_COLLECTION,
    LIB_CONVERT,
    LIB_MATH,
    LIB_HTML,
  ];
}
```

Then type '>' after "SdkLibrary" on line 2 to fix the syntax error.

It does not display any errors or warnings. However, if you reanalyze sources, many errors and warnings will appear.

(Found with a stress test.)

**Comment by skybrian** [comment]
This one is a regression. I wasn't able to reproduce it using Dart 1.13.0.

**Comment by scheglov** [comment]
Attempt to paste this code causes the following exception.
So far it seems that we incorrectly recover from the `List< SdkLibrary` type parsing be including the following `LIBRARIES` as the end token.

```
Failed to find the declaration of the variable LIBRARIES in /Users/scheglov/dart/test/bin/test2.dart

#0 InferStaticVariableTask.getDeclaration (package:analyzer/src/task/dart.dart:3056:7) 
#1 ComputePropagableVariableDependenciesTask.internalPerform (package:analyzer/src/task/dart.dart:2150:39) 
#2 AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310:9) 
#3 AnalysisTask.perform (package:analyzer/task/model.dart:210:7) 
#4 AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271:10) 
#5 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246:9) 
#6 AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1122:27) 
#7 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194:15) 
#8 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1120:50) 
#9 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371:37) 
#10 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:807:17) 
#11 Future.Future.delayed. (dart:async/future.dart:228) 
#12 _rootRun (dart:async/zone.dart:903) 
#13 _CustomZone.run (dart:async/zone.dart:802) 
#14 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#15 _CustomZone.bindCallback. (dart:async/zone.dart:733) 
#16 _rootRun (dart:async/zone.dart:907) 
#17 _CustomZone.run (dart:async/zone.dart:802) 
#18 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#19 _CustomZone.bindCallback. (dart:async/zone.dart:733) 
#20 Timer._createTimer. (dart:async-patch/timer_patch.dart:16) 
#21 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385) 
#22 _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414) 
#23 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by scheglov** [comment]
CL for fixing the exception https://codereview.chromium.org/1615963003

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/b78decfa8fbe36e73a1e4afec880d393acaec947
