### ISSUE TITLE
Exception if dart:async not specified in _embedder.yaml

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#25520]
Given the following ```_embedder.yaml``` file
```
embedder_libs:
  'dart:core':    '/absolute/path/to/fletch-sdk/internal/dart_lib/lib/core/core.dart'
  # 'dart:async': '/absolute/path/to/any/dart-sdk/async/async.dart'
  'dart:fletch':  '/absolute/path/to/fletch-sdk/internal/fletch_lib/lib/fletch/fletch.dart'
analyzer:
  language:
    enableAsync: false
```
the analyzer throws the exception shown below. If the ```dart:async``` line in the ```_embedder.yaml``` file  above is uncommented, then the exception does not occur.
```
Invalid input descriptor (null, LIBRARY_ELEMENT3) for Run BuildTypeProviderTask on Instance of 'AnalysisContextTarget' Path: Run LibraryErrorsReadyTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run DartErrorsTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run LibraryUnitErrorsTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart in /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run GenerateHintsTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart in /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run StrongModeVerifyUnitTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart in /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run EvaluateUnitConstantsTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart in /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run ResolveLibraryReferencesTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run PropagateVariableTypesInLibraryClosureTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run ReadyLibraryElement6Task on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run PropagateVariableTypesInLibraryTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run PropagateVariableTypesInUnitTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart in /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run PartiallyResolveUnitReferencesTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart in /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run ReadyLibraryElement5Task on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run ResolveLibraryTypeNamesTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run ResolveUnitTypeNamesTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart in /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run BuildEnumMemberElementsTask on /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart in /Users/danrubel/work/git/dartino/projects/fletch-test/bin/hello.dart| Run BuildTypeProviderTask on Instance of 'AnalysisContextTarget'

#0 WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:671:11) 
#1 _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:821:17) 
#2 CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:395:35) 
#3 WorkOrder.moveNext. (package:analyzer/src/task/driver.dart:787:31) 
#4 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194:15) 
#5 WorkOrder.moveNext (package:analyzer/src/task/driver.dart:779:44) 
#6 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:245:35) 
#7 AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1122:27) 
#8 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194:15) 
#9 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1120:50) 
#10 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371:37) 
#11 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:807:17) 
#12 Future.Future. (dart:async/future.dart:118) 
#13 _rootRun (dart:async/zone.dart:903) 
#14 _CustomZone.run (dart:async/zone.dart:802) 
#15 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#16 _CustomZone.bindCallback. (dart:async/zone.dart:733) 
#17 _rootRun (dart:async/zone.dart:907) 
#18 _CustomZone.run (dart:async/zone.dart:802) 
#19 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#20 _CustomZone.bindCallback. (dart:async/zone.dart:733) 
#21 Timer._createTimer. (dart:async-patch/timer_patch.dart:16) 
#22 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385) 
#23 _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414) 
#24 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

**Comment by sethladd** [comment]
Thanks for tracking this down!

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1715563002/
