### ISSUE TITLE
Exception while analyzing the flutter stock example

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25528]
The following exception was seen while attempting to analyze the flutter stock example.

Unhandled exception:
Task failed: Run BuildDirectiveElementsTask on .../flutter/examples/stocks/lib/main.dart
Invalid input descriptor (null, LIBRARY_ELEMENT1) for Run BuildDirectiveElementsTask on .../flutter/examples/stocks/lib/main.dart
Path:
Run LibraryErrorsReadyTask on .../flutter/examples/stocks/test/locale_test.dart|
Run DartErrorsTask on .../flutter/examples/stocks/test/locale_test.dart|
Run LibraryUnitErrorsTask on .../flutter/examples/stocks/test/locale_test.dart in .../flutter/examples/stocks/test/locale_test.dart|
Run GenerateHintsTask on .../flutter/examples/stocks/test/locale_test.dart in .../flutter/examples/stocks/test/locale_test.dart|
Run StrongModeVerifyUnitTask on .../flutter/examples/stocks/test/locale_test.dart in .../flutter/examples/stocks/test/locale_test.dart|
Run EvaluateUnitConstantsTask on .../flutter/examples/stocks/test/locale_test.dart in .../flutter/examples/stocks/test/locale_test.dart|
Run ResolveLibraryReferencesTask on .../flutter/examples/stocks/test/locale_test.dart|
Run PropagateVariableTypesInLibraryClosureTask on .../flutter/examples/stocks/test/locale_test.dart|
Run ReadyLibraryElement6Task on .../flutter/examples/stocks/test/locale_test.dart|
Run PropagateVariableTypesInLibraryTask on .../flutter/examples/stocks/test/locale_test.dart|
Run PropagateVariableTypesInUnitTask on .../flutter/examples/stocks/test/locale_test.dart in .../flutter/examples/stocks/test/locale_test.dart|
Run PartiallyResolveUnitReferencesTask on .../flutter/examples/stocks/test/locale_test.dart in .../flutter/examples/stocks/test/locale_test.dart|
Run ReadyLibraryElement5Task on .../flutter/examples/stocks/test/locale_test.dart|
Run ResolveLibraryTypeNamesTask on .../flutter/examples/stocks/test/locale_test.dart|
Run ResolveUnitTypeNamesTask on .../flutter/examples/stocks/test/locale_test.dart in .../flutter/examples/stocks/test/locale_test.dart|
Run BuildExportNamespaceTask on .../flutter/examples/stocks/lib/main.dart|
Run BuildPublicNamespaceTask on .../flutter/examples/stocks/lib/main.dart|
Run BuildDirectiveElementsTask on .../flutter/examples/stocks/lib/main.dart
#0      WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:671:11)
#1      _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:821:17)
#2      CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:395:35)
#3      WorkOrder.moveNext.<anonymous closure> (package:analyzer/src/task/driver.dart:787:31)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194:15)
#5      WorkOrder.moveNext (package:analyzer/src/task/driver.dart:779:44)
#6      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:245:35)
#7      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1066:27)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194:15)
#9      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1064:49)
#10     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371:37)
#11     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:807:17)
#12     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#13     _rootRun (dart:async/zone.dart:903)
#14     _CustomZone.run (dart:async/zone.dart:802)
#15     _CustomZone.runGuarded (dart:async/zone.dart:708)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#17     _rootRun (dart:async/zone.dart:907)
#18     _CustomZone.run (dart:async/zone.dart:802)
#19     _CustomZone.runGuarded (dart:async/zone.dart:708)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#21     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#23     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

**Comment by bwilkerson** [comment]
I believe that this is caused by not being able to resolve dart:core.

https://codereview.chromium.org/1605923005/ changes the failure mode so that we no longer throw an uncaught exception, but instead record the underlying cause of the problem and continue.

That said, failure to configure the SDK correctly (especially dart:core) will not result in any useful feedback, so clients need to be prepared to handle `null` analysis results.
