### ISSUE TITLE
Base64Codec doesn't like being used as a transformer

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25577]
If you pass `Base64Encoder` or `Base64Decoder` to `Stream.transform()` and then listen to the result, it produces an error.

```dart
import 'dart:async';
import 'dart:convert';

main() async {
  var controller = new StreamController();
  controller.stream.transform(BASE64.encoder).listen(print);
}
```

This throws

```
Unhandled exception:
type '_EventSinkWrapper' is not a subtype of type 'ChunkedConversionSink<List<int>>' of '_sink@229117450'.
#0      _Base64DecoderSink._Base64DecoderSink (dart:convert/base64.dart:690)
#1      Base64Decoder.startChunkedConversion (dart:convert/base64.dart:320)
#2      _ConverterStreamEventSink._ConverterStreamEventSink (dart:convert/chunked_conversion.dart:78)
#3      Converter.bind.<anonymous closure> (dart:convert/converter.dart:43)
#4      _SinkTransformerStreamSubscription._SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:45)
#5      _BoundSinkStream.listen (dart:async/stream_transformers.dart:186)
#6      main.<main_async_body> (file:///usr/local/google/home/nweiz/goog/pkg/stream_channel/test.dart:7:47)
#7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by lrhn** [comment]
Type error in code. It assumes the output sink is a `ChunkedConversionSink`, but we replaced that with just `Sink` when introducing `Sink`.
(`ChunkedConversionSink` is identical to `Sink`, it's only retained for backwards compatibility).
