### ISSUE TITLE
Dart freezes randomly on windows

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/sdk#25582]
Hello,
Since we upgraded to 1.13 we have a terrible experience with Dart.
The dart VM stop working at random time: 
- the Dart analyzer stops working in Webstorm (have to restart it) 
- Dartium freezes and shows "Page unresponsive: wait or kill"
- `pub serve` stops serving assets.
- Custom dart scripts hang forever

It happens several time per hour.

I don't really know what happens but several of my co-worker see the same behavior.
It happens on windows 8.1 and Windows 10. Not on MacOS.

Please give me pointer of how I can help diagnose this.

Thank you.

**Comment by lukechurch** [comment]
cc @danrubel

**Comment by zoechi** [comment]
Can you try if this is still an issue in 1.14? I think to remember that there were similar issues reported not to long ago. 1.14 stable was already released.

**Comment by xavierhainaux** [comment]
I upgraded to 1.14. While it seems to happen a bit less (only 2 or 3 times a day), I can still experience the Analyzer and pub serve that stops working.

There is a few dart-related entries in the Webstorm idea.log (pasted bellow) but it doesn't look like the source of the problem.
Is there somewhere else I could check?

```
2016-02-09 13:44:14,773 [16015004]   INFO - yzer.DartAnalysisServerService - analysis_getNavigation() took too long for file C:\xxx.dart: 1001ms 
```

and

```
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:204)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
2016-02-08 17:46:18,259 [30100754]  ERROR - yzer.DartAnalysisServerService - WebStorm 11.0.3  Build #WS-143.1559.5 
2016-02-08 17:46:18,259 [30100754]  ERROR - yzer.DartAnalysisServerService - JDK: 1.8.0_51 
2016-02-08 17:46:18,259 [30100754]  ERROR - yzer.DartAnalysisServerService - VM: Java HotSpot(TM) Server VM 
2016-02-08 17:46:18,259 [30100754]  ERROR - yzer.DartAnalysisServerService - Vendor: Oracle Corporation 
2016-02-08 17:46:18,259 [30100754]  ERROR - yzer.DartAnalysisServerService - OS: Windows 8 
2016-02-08 17:46:18,259 [30100754]  ERROR - yzer.DartAnalysisServerService - Last Action: EditorRight 
2016-02-08 17:46:18,259 [30100754]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.14.1, server version 1.14.0, error: Failed to handle completion domain request: {clientRequestTime: 1454949962704, params: {file: C:\Users\xavier.hainaux\dart\pdwg\dart\core\lib\game\game_chrome.dart, offset: 1755}, method: completion.getSuggestions, id: 9071}
Instance of 'AnalysisNotScheduledError'
#0      PendingFuture.forciblyComplete (package:analyzer/src/context/context.dart:2014)
#1      AnalysisContextImpl._evaluatePendingFutures (package:analyzer/src/context/context.dart:1417)
#2      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1067)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#4      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1066)
#5      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#6      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:807)
#7      Future.Future.delayed.<anonymous closure> (dart:async/future.dart:228)
#8      _rootRun (dart:async/zone.dart:903)
#9      _CustomZone.run (dart:async/zone.dart:802)
#10     _CustomZone.runGuarded (dart:async/zone.dart:708)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#12     _rootRun (dart:async/zone.dart:907)
#13     _CustomZone.run (dart:async/zone.dart:802)
#14     _CustomZone.runGuarded (dart:async/zone.dart:708)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#16     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by danrubel** [comment]
May be related to https://github.com/dart-lang/sdk/issues/24271#issuecomment-180403148
