### ISSUE TITLE
VM: break out of try-finally may execute finally clause twice

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#25654]
Repro:

```
main() {
  L:
  while (true) {
    try {
      break L;
    } finally {
      print("f");
    }
  }
  throw "ex";
}
```

Output:
```
$ xcodebuild/ReleaseX64/dart repro.dart 
f
f
Unhandled exception:
ex
#0      main (file:///Users/fschneider/dartgit/sdk/repro.dart:10:3)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by fsc8000** [comment]
Proposed fix: https://codereview.chromium.org/1660203002/

**Comment by fsc8000** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/b354660f026c607710d2889d5b427dcbc9d84cf7.

I fixed the same bug with continue-targets already a long time ago (https://codereview.chromium.org//308053012), but missed the break-target case there.
