### ISSUE TITLE
FATAL error while analyzing 

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#25663]
Just (to be exact - 19 mins ago, according to IJs status bar...) got this error:
IntelliJ IDEA (Minerva) IU-144.3357.4
Build #IU-144.3357, built on January 26, 2016
JRE: 1.8.0_40-release-b127 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

With latest Dart-Version and latest Dart-Plugin in IJ on Mac OSX 10.9.5
```
Dart analysis server, SDK version 1.14.0, server version 1.14.0, FATAL error: Failed to perform operation: 
Instance of 'PerformAnalysisOperation' The null object does not have a getter 'source'. 
NoSuchMethodError: method not found: 'source' Receiver: null Arguments: [] 

#0 Object._noSuchMethod (dart:core-patch/object_patch.dart:42) 
#1 Object.noSuchMethod (dart:core-patch/object_patch.dart:45) 
#2 PropagateVariableTypeTask.buildInputs (package:analyzer/src/task/dart.dart:4049) 
#3 WorkItem.WorkItem (package:analyzer/src/task/driver.dart:608) 
#4 WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:712) 
#5 _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:821) 
#6 CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:395) 
#7 WorkOrder.moveNext.  (package:analyzer/src/task/driver.dart:787) 
#8 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194) 
#9 WorkOrder.moveNext (package:analyzer/src/task/driver.dart:779) 
#10 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:245) 
#11 AnalysisContextImpl.performAnalysisTask.  (package:analyzer/src/context/context.dart:1068) 
#12 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194) 
#13 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1066) 
#14 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371) 
#15 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:807) 
#16 Future.Future.  (dart:async/future.dart:118) 
#17 _rootRun (dart:async/zone.dart:903) 
#18 _CustomZone.run (dart:async/zone.dart:802) 
#19 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#20 _CustomZone.bindCallback.  (dart:async/zone.dart:733) 
#21 _rootRun (dart:async/zone.dart:907) 
#22 _CustomZone.run (dart:async/zone.dart:802) 
#23 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#24 _CustomZone.bindCallback.  (dart:async/zone.dart:733) 
#25 Timer._createTimer.  (dart:async-patch/timer_patch.dart:16) 
#26 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385) 
#27 _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414) 
#28 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
The error is happening on the last line:

    VariableElement variable = target;
    LibrarySpecificUnit unit =
        new LibrarySpecificUnit(variable.library.source, variable.source);

We appear to have a variable that doesn't know which library it's part of.
