### ISSUE TITLE
Hitting analysis stack trace

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#25681]
This is created analyzing the dart intl package in Atom with strong mode enabled.

Note, the second stack trace shows a null deference I tried working around in:

https://codereview.chromium.org/1664213002/

```
[RequestError method: analysis.setSubscriptions, code: SERVER_ERROR, message: AnalysisException: Cannot compute RESOLVED_UNIT for /Users/vsm/git/i18n/intl/test/date_time_format_test_core.dart in /Users/vsm/git/i18n/intl/test/date_time_format_test_core.dart
Caused by Unexpected exception while performing ResolveUnitTask for source /Users/vsm/git/i18n/intl/test/date_time_format_test_core.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:328)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:218)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:657)
#5      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1224)
#6      AnalysisServer._getResolvedCompilationUnitToResendNotification.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1339)
#7      runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:35)
#8      AnalysisServer._getResolvedCompilationUnitToResendNotification (package:analysis_server/src/analysis_server.dart:1338)
#9      AnalysisServer.setAnalysisSubscriptions.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1013)
#10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#11     AnalysisServer.setAnalysisSubscriptions (package:analysis_server/src/analysis_server.dart:978)
#12     AnalysisDomainHandler.setSubscriptions (package:analysis_server/src/domain_analysis.dart:296)
#13     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:209)
#14     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:686)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#16     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:682)
#17     _rootRun (dart:async/zone.dart:895)
#18     _CustomZone.run (dart:async/zone.dart:790)
#19     _CustomZone.runGuarded (dart:async/zone.dart:696)
#20     runZoned (dart:async/zone.dart:1231)
#21     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:681)
#22     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#26     _rootRunUnary (dart:async/zone.dart:902)
#27     _CustomZone.runUnary (dart:async/zone.dart:798)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#37     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#39     _rootRunUnary (dart:async/zone.dart:902)
#40     _CustomZone.runUnary (dart:async/zone.dart:798)
#41     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#44     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#45     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#46     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#47     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#48     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#49     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#50     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#51     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#52     _rootRunUnary (dart:async/zone.dart:902)
#53     _CustomZone.runUnary (dart:async/zone.dart:798)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#57     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#58     _StreamController._add (dart:async/stream_controller.dart:632)
#59     _StreamController.add (dart:async/stream_controller.dart:578)
#60     _Socket._onData (dart:io-patch/socket_patch.dart:1646)
#61     _rootRunUnary (dart:async/zone.dart:906)
#62     _CustomZone.runUnary (dart:async/zone.dart:798)
#63     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#66     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#67     _StreamController._add (dart:async/stream_controller.dart:632)
#68     _StreamController.add (dart:async/stream_controller.dart:578)
#69     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1215)
#70     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#71     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#72     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#73     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
Caused by The null object does not have a getter 'source'.
NoSuchMethodError: method not found: 'source'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      StaticTypeAnalyzer._inferMethodInvocationInlineJS (package:analyzer/src/generated/static_type_analyzer.dart:1922)
#3      StaticTypeAnalyzer.visitMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:740)
#4      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7047)
#5      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:8144)
#6      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7047)
#7      AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:935)
#8      VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10449)
#9      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#10     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1844)
#11     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:9701)
#12     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:8272)
#13     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10443)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7410)
#15     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10544)
#16     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#17     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1848)
#18     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:8298)
#19     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10538)
#20     AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:935)
#21     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10598)
#22     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#23     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:1852)
#24     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10594)
#25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7410)
#26     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1252)
#27     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#28     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:1545)
#29     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:9221)
#30     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1248)
#31     AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:935)
#32     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1199)
#33     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#34     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:1548)
#35     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:9233)
#36     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7432)
#37     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1195)
#38     AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:935)
#39     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5012)
#40     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#41     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:1659)
#42     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:9541)
#43     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7908)
#44     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5006)
#45     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7410)
#46     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:410)
#47     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#48     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:1527)
#49     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:7324)
#50     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:406)
#51     ScopedVisitor.safelyVisit (package:analyzer/src/generated/resolver.dart:9210)
#52     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:8143)
#53     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7047)
#54     AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:935)
#55     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3987)
#56     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#57     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:1631)
#58     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3983)
#59     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7410)
#60     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1252)
#61     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#62     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:1545)
#63     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:9221)
#64     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1248)
#65     AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:935)
#66     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1199)
#67     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#68     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:1548)
#69     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:9233)
#70     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7432)
#71     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1195)
#72     AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:935)
#73     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5012)
#74     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#75     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:1659)
#76     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:9516)
#77     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7908)
#78     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5006)
#79     AstNodeImpl._safelyVisitChild (package:analyzer/src/dart/ast/ast.dart:935)
#80     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4861)
#81     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8156)
#82     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:1652)
#83     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:9509)
#84     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:7888)
#85     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:9501)
#86     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7879)
#87     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4854)
#88     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:7554)
#89     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2360)
#90     ResolveUnitTask.internalPerform (package:analyzer/src/task/dart.dart:4674)
#91     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:318)
#92     AnalysisTask.perform (package:analyzer/task/model.dart:218)
#93     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274)
#94     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#95     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:657)
#96     AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1224)
#97     AnalysisServer._getResolvedCompilationUnitToResendNotification.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1339)
#98     runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:35)
#99     AnalysisServer._getResolvedCompilationUnitToResendNotification (package:analysis_server/src/analysis_server.dart:1338)
#100    AnalysisServer.setAnalysisSubscriptions.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1013)
#101    _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#102    AnalysisServer.setAnalysisSubscriptions (package:analysis_server/src/analysis_server.dart:978)
#103    AnalysisDomainHandler.setSubscriptions (package:analysis_server/src/domain_analysis.dart:296)
#104    AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:209)
#105    AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:686)
#106    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#107    AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:682)
#108    _rootRun (dart:async/zone.dart:895)
#109    _CustomZone.run (dart:async/zone.dart:790)
#110    _CustomZone.runGuarded (dart:async/zone.dart:696)
#111    runZoned (dart:async/zone.dart:1231)
#112    AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:681)
#113    ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#114    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#115    ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#116    ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#117    _rootRunUnary (dart:async/zone.dart:902)
#118    _CustomZone.runUnary (dart:async/zone.dart:798)
#119    _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#120    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#121    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#122    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#123    _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#124    _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#125    _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127)
#126    _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102)
#127    StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#128    _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#129    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#130    _rootRunUnary (dart:async/zone.dart:902)
#131    _CustomZone.runUnary (dart:async/zone.dart:798)
#132    _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#133    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#134    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#135    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#136    _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#137    _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#138    _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#139    _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#140    _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#141    _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#142    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#143    _rootRunUnary (dart:async/zone.dart:902)
#144    _CustomZone.runUnary (dart:async/zone.dart:798)
#145    _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#146    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#147    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#148    _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#149    _StreamController._add (dart:async/stream_controller.dart:632)
#150    _StreamController.add (dart:async/stream_controller.dart:578)
#151    _Socket._onData (dart:io-patch/socket_patch.dart:1646)
#152    _rootRunUnary (dart:async/zone.dart:906)
#153    _CustomZone.runUnary (dart:async/zone.dart:798)
#154    _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#155    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#156    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#157    _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#158    _StreamController._add (dart:async/stream_controller.dart:632)
#159    _StreamController.add (dart:async/stream_controller.dart:578)
#160    _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1215)
#161    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#162    _microtaskLoop (dart:async/schedule_microtask.dart:41)
#163    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#164    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#165    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
]
    at [object Object].dart.wrapException (/Users/vsm/.atom/packages/dartlang/web/entry.dart.js:23940:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/Users/vsm/.atom/packages/dartlang/web/entry.dart.js:45534:19)
    at [object Object].dart._microtaskLoop (/Users/vsm/.atom/packages/dartlang/web/entry.dart.js:42917:27)
    at [object Object].dart._startMicrotaskLoop (/Users/vsm/.atom/packages/dartlang/web/entry.dart.js:42923:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/vsm/.atom/packages/dartlang/web/entry.dart.js:23255:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/vsm/.atom/packages/dartlang/web/entry.dart.js:25120:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/Users/vsm/.atom/packages/dartlang/web/entry.dart.js:22867:25)
    at [object Object].dart._callInIsolate (/Users/vsm/.atom/packages/dartlang/web/entry.dart.js:22509:28)
    at dart.invokeClosure (/Users/vsm/.atom/packages/dartlang/web/entry.dart.js:24088:20)
    at /Users/vsm/.atom/packages/dartlang/web/entry.dart.js:24109:18
```

**Comment by vsmenon** [comment]
I suspect this was related to #25667 which @bwilkerson fixed.

**Comment by jmesserly** [comment]
Nice! Let's close it and reopen if it appears?
