### ISSUE TITLE
Analyzer exception "method not found: 'isDynamic'

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#25711]
I get this exception repeatedly all day.

> Dart analysis server, SDK version 1.15.0-edge.c174f4c778125faabb152f7e6234dcf3596c7164, server version 1.14.0, error: Failed to handle completion domain request: {clientRequestTime: 1454868531167, params: {file: /home/zoechi/dart/bwu_ng_icon/bwu_ng_icon/lib/icon/iconset_registry.dart, offset: 565}, method: completion.getSuggestions, id: 842}
The null object does not have a getter 'isDynamic'.
>
NoSuchMethodError: method not found: 'isDynamic'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      TypeMemberContributor.computeSuggestions.<computeSuggestions_async_body> (package:analysis_server/src/services/completion/dart/type_member_contributor.dart:75)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#4      _rootRunUnary (dart:async/zone.dart:902)
#5      _CustomZone.runUnary (dart:async/zone.dart:798)
#6      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#7      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#8      _Future._complete (dart:async/future_impl.dart:414)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:52)
#10     DartCompletionRequestImpl.resolveExpression.<resolveExpression_async_body> (package:analysis_server/src/services/completion/dart/completion_manager.dart:255)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#12     _rootRunUnary (dart:async/zone.dart:902)
#13     _CustomZone.runUnary (dart:async/zone.dart:798)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:637)
#16     _Future._completeWithValue (dart:async/future_impl.dart:424)
#17     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#18     _rootRun (dart:async/zone.dart:895)
#19     _CustomZone.run (dart:async/zone.dart:790)
#20     _CustomZone.runGuarded (dart:async/zone.dart:696)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:203)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
>
>
>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:203)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
>
>
>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:203)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1688493002/

**Comment by zoechi** [comment]
:+1:
