### ISSUE TITLE
Dart analysis server, annotation and closure

### ISSUE THREAD

**Issue by tristancaron** [dart-lang/sdk#25730]
I made a class property annotated.

```
class MyClass {
  @BadAnnotation(const [(_) => null])
  String property;
}
```

Then (on Webstorm) Dart Analysis throws
```
Dart analysis server, SDK version 1.14.1, server version 1.14.0, error: Exception from assist contributor: DefaultAssistContributor
The null object does not have a getter 'librarySource'.

NoSuchMethodError: method not found: 'librarySource'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ComputeConstantDependenciesTask.buildInputs (package:analyzer/src/task/dart.dart:1856)
#3      WorkItem.WorkItem (package:analyzer/src/task/driver.dart:608)
#4      WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:712)
#5      _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:821)
#6      CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:395)
#7      WorkOrder.moveNext. (package:analyzer/src/task/driver.dart:787)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analy... (show balloon)
```

I think the correct error is that the closure isn't allowed here, isn't ?

**Comment by bwilkerson** [comment]
Yes, the problem is that closures are not constant expressions.

**Comment by bwilkerson** [comment]
I believe that this was fixed by https://codereview.chromium.org/1705773002/.
Test added with https://codereview.chromium.org/1711053002/.
