### ISSUE TITLE
Dartium deferred-import LayoutTest fails

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#25756]
```
Running: testScopeChain
Exception while running: function bound didGetScriptSource() { [native code] }
TypeError: Cannot read property '_agent' of undefined
    at setBreakpointAndWaitUntilPaused (evaluateInWebInspector1.js:89:35)
    at didShowScriptSource (evaluateInWebInspector1.js:73:17)
    at Object.result (evaluateInWebInspector0.js:468:25)
    at Object.receiver.(anonymous function) (evaluateInWebInspector0.js:498:22)
    at Object.WebInspector.SourceFrame.setContent (file:///usr/local/google/home/alanknight/dartium-new/src/out/Release/resources/inspector/source_frame_module.js:1833:6)
    at Object.WebInspector.UISourceCode._fireContentAvailable (file:///usr/local/google/home/alanknight/dartium-new/src/out/Release/resources/inspector/inspector.js:7064:13)
    at Object.requestContentLoaded (file:///usr/local/google/home/alanknight/dartium-new/src/out/Release/resources/inspector/inspector.js:8112:1)
    at Object.replyWithContent (file:///usr/local/google/home/alanknight/dartium-new/src/out/Release/resources/inspector/inspector.js:6257:13)
    at Object.contentLoaded (file:///usr/local/google/home/alanknight/dartium-new/src/out/Release/resources/inspector/inspector.js:6254:18)
    at Object.resourceContentLoaded (file:///usr/local/google/home/alanknight/dartium-new/src/out/Release/resources/inspector/inspector.js:6259:16)
```

**Comment by jacob314** [comment]
Fixed by https://codereview.chromium.org/1689033003
