### ISSUE TITLE
AssertAssignableInstr::Canonicalize sometimes creates checks against TypeRef which runtime can't handle

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#25782]
In the optimized version of the function `f` from the reproduction below compiler ends up generating `AssertAssignable:6(v3, TypeRef: B<...> (@0xf5d8f331 Hefbb15c), 'field' instantiator_type_arguments(v0))` because `AssertAssignableInstr::Canonicalize` replaces destination type of the original `AssertAssignable` against type parameter with whatever `InstantiateFrom` returned (and it returns `TypeRef`). However `Instance::IsInstanceOf` (which is called in the runtime function `TypeCheck`) apparently can't cope with `dst_type` being  `TypeRef` - it returns `false` even though it would return true if we unwrap the ref.

Either optimizing compiler needs to take care and unwrap `TypeRef` when canonicalizing or runtime system must be able to cope with `TypeRef`s passed to `IsInstanceOf`.

Note: this issue causes flakiness on the dart2js buildbot. 

/cc @whesse @asgerf @rakudrama @fsc8000 @crelier 

```dart
// VMOptions=--enable_asserts --enable_type_checks --enable-inlining-annotations --optimization-counter-threshold=10

const AlwaysInline = "AlwaysInline";
const NeverInline = "NeverInline";

abstract class A<T extends A<T>> {
  @AlwaysInline
  m(x) => new R<T>(x);
}

class B extends A<B> {}

class R<T> {
  @AlwaysInline
  R(T field);
}

class C extends B {}

class D extends C {}

// Method A<T>.m will be inlined and T=B will be forwarded to AssertAssignable in the
// R. However B will be wrapped in the TypeRef which breaks runtime TypeCheck
// function (Instance::IsInstanceOf does not work for TypeRefs).
@NeverInline
f(o) => new B().m(o);

main() {
  final o = new D();
  for (var i = 0; i < 10; i++) {
    f(o);
  }
}
```

```
$ out/DebugIA32/dart --enable_asserts --enable_type_checks --enable-inlining-annotations --optimization-counter-threshold=10 test.dart
Unhandled exception:
type 'D' is not a subtype of type 'B' of 'field'.
#0      R.R (file:///usr/local/google/home/vegorov/src/dart/sdk/test.dart:16:7)
#1      A.m (file:///usr/local/google/home/vegorov/src/dart/sdk/test.dart:9:15)
#2      f (file:///usr/local/google/home/vegorov/src/dart/sdk/test.dart:27:17)
#3      main (file:///usr/local/google/home/vegorov/src/dart/sdk/test.dart:32:5)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by mraleph** [comment]
Fixed in b2994a4f556a13d6420b122a97ceef739f427653 by unwrapping `TypeRef` in the optimizer.
