### ISSUE TITLE
Non-deterministic JS output in core_runtime_types_test

### ISSUE THREAD

**Issue by asgerf** [dart-lang/sdk#25795]
The JS output for `core_runtime_types_test` fails about 10% of the time, and not always with the same stack trace.

To reproduce, compile `tests/corelib/core_runtime_types_test.dart` with CPS and run it 100 times:

``` bash
for i in $(seq 100); do d8 out.js; done
```

Example output:

```
out.js:2754: Expect.throws: Unexpected 'Error: undefined is not a function'
TypeError: undefined is not a function
    at J.$ge$n (out.js:2847:41)
    at CoreRuntimeTypesTest_testComparisonOperatorErrors_closure2.dart.CoreRuntimeTypesTest_testComparisonOperatorErrors_closure2.call$0 (out.js:1792:13)
    at dart.Expect_throws (out.js:2743:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1532:9)
    at dart.main (out.js:1575:15)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3
      throw H.wrapException(new K.ExpectException(message));
      ^
Expect.throws: Unexpected 'Error: undefined is not a function'
TypeError: undefined is not a function
    at J.$ge$n (out.js:2847:41)
    at CoreRuntimeTypesTest_testComparisonOperatorErrors_closure2.dart.CoreRuntimeTypesTest_testComparisonOperatorErrors_closure2.call$0 (out.js:1792:13)
    at dart.Expect_throws (out.js:2743:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1532:9)
    at dart.main (out.js:1575:15)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3
    at dart.wrapException (out.js:773:18)
    at dart.Expect__fail (out.js:2754:15)
    at dart.Expect_throws (out.js:2749:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1532:9)
    at dart.main (out.js:1575:15)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3

out.js:2754: Expect.throws: Unexpected 'Error: undefined is not a function'
TypeError: undefined is not a function
    at J.$gt$n (out.js:2852:41)
    at CoreRuntimeTypesTest_testComparisonOperatorErrors_closure1.dart.CoreRuntimeTypesTest_testComparisonOperatorErrors_closure1.call$0 (out.js:1784:13)
    at dart.Expect_throws (out.js:2743:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1531:9)
    at dart.main (out.js:1573:13)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3
      throw H.wrapException(new K.ExpectException(message));
      ^
Expect.throws: Unexpected 'Error: undefined is not a function'
TypeError: undefined is not a function
    at J.$gt$n (out.js:2852:41)
    at CoreRuntimeTypesTest_testComparisonOperatorErrors_closure1.dart.CoreRuntimeTypesTest_testComparisonOperatorErrors_closure1.call$0 (out.js:1784:13)
    at dart.Expect_throws (out.js:2743:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1531:9)
    at dart.main (out.js:1573:13)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3
    at dart.wrapException (out.js:773:18)
    at dart.Expect__fail (out.js:2754:15)
    at dart.Expect_throws (out.js:2749:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1531:9)
    at dart.main (out.js:1573:13)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3

out.js:2754: Expect.throws: Unexpected 'Error: undefined is not a function'
TypeError: undefined is not a function
    at J.$le$n (out.js:2857:41)
    at CoreRuntimeTypesTest_testComparisonOperatorErrors_closure0.dart.CoreRuntimeTypesTest_testComparisonOperatorErrors_closure0.call$0 (out.js:1776:13)
    at dart.Expect_throws (out.js:2743:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1530:9)
    at dart.main (out.js:1575:15)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3
      throw H.wrapException(new K.ExpectException(message));
      ^
Expect.throws: Unexpected 'Error: undefined is not a function'
TypeError: undefined is not a function
    at J.$le$n (out.js:2857:41)
    at CoreRuntimeTypesTest_testComparisonOperatorErrors_closure0.dart.CoreRuntimeTypesTest_testComparisonOperatorErrors_closure0.call$0 (out.js:1776:13)
    at dart.Expect_throws (out.js:2743:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1530:9)
    at dart.main (out.js:1575:15)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3
    at dart.wrapException (out.js:773:18)
    at dart.Expect__fail (out.js:2754:15)
    at dart.Expect_throws (out.js:2749:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1530:9)
    at dart.main (out.js:1575:15)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3

out.js:2754: Expect.throws: Unexpected 'Error: undefined is not a function'
TypeError: undefined is not a function
    at J.$div$n (out.js:2842:41)
    at CoreRuntimeTypesTest_testBinaryOperatorErrors_closure1.dart.CoreRuntimeTypesTest_testBinaryOperatorErrors_closure1.call$0 (out.js:1712:13)
    at dart.Expect_throws (out.js:2743:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1519:9)
    at dart.main (out.js:1573:13)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3
      throw H.wrapException(new K.ExpectException(message));
      ^
Expect.throws: Unexpected 'Error: undefined is not a function'
TypeError: undefined is not a function
    at J.$div$n (out.js:2842:41)
    at CoreRuntimeTypesTest_testBinaryOperatorErrors_closure1.dart.CoreRuntimeTypesTest_testBinaryOperatorErrors_closure1.call$0 (out.js:1712:13)
    at dart.Expect_throws (out.js:2743:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1519:9)
    at dart.main (out.js:1573:13)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3
    at dart.wrapException (out.js:773:18)
    at dart.Expect__fail (out.js:2754:15)
    at dart.Expect_throws (out.js:2749:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1519:9)
    at dart.main (out.js:1573:13)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3

out.js:2754: Expect.throws: Unexpected 'Error: undefined is not a function'
TypeError: undefined is not a function
    at J.$lt$n (out.js:2862:41)
    at CoreRuntimeTypesTest_testComparisonOperatorErrors_closure.dart.CoreRuntimeTypesTest_testComparisonOperatorErrors_closure.call$0 (out.js:1768:13)
    at dart.Expect_throws (out.js:2743:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1529:9)
    at dart.main (out.js:1573:13)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3
      throw H.wrapException(new K.ExpectException(message));
      ^
Expect.throws: Unexpected 'Error: undefined is not a function'
TypeError: undefined is not a function
    at J.$lt$n (out.js:2862:41)
    at CoreRuntimeTypesTest_testComparisonOperatorErrors_closure.dart.CoreRuntimeTypesTest_testComparisonOperatorErrors_closure.call$0 (out.js:1768:13)
    at dart.Expect_throws (out.js:2743:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1529:9)
    at dart.main (out.js:1573:13)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3
    at dart.wrapException (out.js:773:18)
    at dart.Expect__fail (out.js:2754:15)
    at dart.Expect_throws (out.js:2749:11)
    at dart.CoreRuntimeTypesTest_testBinaryOperatorErrors (out.js:1529:9)
    at dart.main (out.js:1573:13)
    at out.js:3152:9
    at init.currentScript (out.js:3132:7)
    at out.js:3147:5
    at out.js:3155:3
```

**Comment by rakudrama** [comment]
Does this also happen with jsshell or a significantly different version of v8?

**Comment by asgerf** [comment]
It works fine in jsshell and in d8 with --no-crankshaft.

**Comment by asgerf** [comment]
It seems the message associated with the exception is normally something like:
`J.getInterceptor$n(...).$div is not a function`
But occasionally, it is thrown as
`undefined is not a function`

We could file an issue with V8, but maybe our error message matching should just be a bit broader.

**Comment by nex3** [comment]
@rakudrama It looks like this is still an issue; see [this log](https://uberchromegw.corp.google.com/i/client.dart/builders/dart2js-linux-d8-minified-1-5-be/builds/5958/steps/dart2js-d8%20tests/logs/stdio). I'm re-opening.
