### ISSUE TITLE
NodeReplacer fails when replacing a comment in a variable declaration list

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#25818]
[5932101]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.15.0-dev.2.0, server version 1.14.0, error: Failure in incremental resolver
IllegalArgumentException: The old node is not a child of it's parent null
#0      NodeReplacer.visitNode (package:analyzer/src/dart/ast/utilities.dart:4649)
#1      NodeReplacer.visitVariableDeclarationList (package:analyzer/src/dart/ast/utilities.dart:4952)
#2      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10546)
#3      NodeReplacer.replace (package:analyzer/src/dart/ast/utilities.dart:5025)
#4      PoorMansIncrementalResolver._resolveCommentDoc (package:analyzer/src/generated/incremental_resolver.dart:1657)
#5      PoorMansIncrementalResolver.resolve (package:analyzer/src/generated/incremental_resolver.dart:1444)
#6      AnalysisContextImpl._tryPoorMansIncrementalResolution.<anonymous closure> (package:analyzer/src/context/context.dart:1883)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#8      AnalysisContextImpl._tryPoorMansIncrementalResolution (package:analyzer/src/context/context.dart:1842)
#9      AnalysisContextImpl.handleContentsChanged (package:analyzer/src/context/context.dart:1018)
#10     AnalysisServer.updateContent.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1241)
#11     List.forEach (dart:core-patch/growable_array.dart:233)
#12     AnalysisServer.updateContent.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1239)
#13     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#14     AnalysisServer.updateContent (package:analysis_server/src/analysis_server.dart:1192)
#15     AnalysisDomainHandler.updateContent (package:analysis_server/src/domain_analysis.dart:305)
#16     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:211)
#17     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:692)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#19     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:688)
#20     _rootRun (dart:async/zone.dart:895)
#21     _CustomZone.run (dart:async/zone.dart:790)
#22     _CustomZone.runGuarded (dart:async/zone.dart:696)
#23     runZoned (dart:async/zone.dart:1231)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:687)
#25     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#28     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#29     _rootRunUnary (dart:async/zone.dart:902)
#30     _CustomZone.runUnary (dart:async/zone.dart:798)

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1715723002/
