### ISSUE TITLE
Analyzer crash in strong mode: failed to find declaration

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#25846]
Found via stress testing for dart-services
(Dart VM version: 1.14.1 (Wed Feb  3 11:49:51 2016) on "macos_x64")
Also reproduces against the analyzer 0.27.3-alpha.0

lukechurch-macbookpro:temp lukechurch$ **cat tinytest.dart**
```dart
void main;) {
  String n x = ""(
  
 oprint($(afsd));
}
```

lukechurch-macbookpro:temp lukechurch$ **dartanalyzer tinytest.dart**
```
Analyzing [tinytest.dart]...
[error] Variables cannot have a type of 'void' (/Users/lukechurch/temp/tinytest.dart, line 1, col 1)
...
8 errors and 4 warnings found.
```
lukechurch-macbookpro:temp lukechurch$ **dartanalyzer --strong tinytest.dart**
```
Analyzing [tinytest.dart]...
Unhandled exception:
AnalysisException: Cannot compute LIBRARY_ELEMENT for /Users/lukechurch/temp/tinytest.dart
Caused by Failed to find the declaration of the variable x in /Users/lukechurch/temp/tinytest.dart
#0      InferStaticVariableTask.getDeclaration (package:analyzer/src/task/dart.dart:3096)
#1      ComputeInferableStaticVariableDependenciesTask.internalPerform (package:analyzer/src/task/dart.dart:2006)
#2      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#3      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#4      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#5      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#6      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:651)
#7      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:624)
#8      AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:259)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#10     AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:258)
#11     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
#12     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126)
#13     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:533)
#14     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:184)
#15     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:127)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#17     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:126)
#18     Driver.start (package:analyzer_cli/src/driver.dart:112)
#19     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:14)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:655)
#1      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:624)
#2      AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:259)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#4      AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:258)
#5      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
#6      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126)
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:533)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:184)
#9      Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:127)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#11     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:126)
#12     Driver.start (package:analyzer_cli/src/driver.dart:112)
#13     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:14)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
lukechurch-macbookpro:temp lukechurch$ 
```

**Comment by jmesserly** [comment]
simplified repro:
```dart
String n x = "";
```

Analyzer creates an element for "x", and task to infer int, but when it looks up the node, it finds "String n".

I can certainly patch this in ComputeInferableStaticVariableDependenciesTask, but I wonder if it's a deeper problem in Analyzer, as it means any Node lookup for that Element will fail. This could break other IDE operations, such as refactoring.

**Comment by jmesserly** [comment]
BTW, nice catch Luke!

(Makes me think, we should probably try more fuzz testing for strong mode.)

**Comment by bwilkerson** [comment]
> ... but I wonder if it's a deeper problem in Analyzer ...

Yes, it almost certainly is. What does the AST for that line look like?

> ...  we should probably try more fuzz testing for strong mode.

@skybrian Are you running our stress tests in both strong and spec mode?

**Comment by skybrian** [comment]
I'm not doing strong mode yet.

**Comment by jmesserly** [comment]
Looks like `String n x` will parse into something with "x" treated as the semicolon:
```dart
// parser.dart:
  VariableDeclarationStatement _parseVariableDeclarationStatementAfterType(
      CommentAndMetadata commentAndMetadata, Token keyword, TypeName type) {
    VariableDeclarationList variableList =
        _parseVariableDeclarationListAfterType(
            commentAndMetadata, keyword, type);
    Token semicolon = _expect(TokenType.SEMICOLON); // BUG?
    return new VariableDeclarationStatement(variableList, semicolon);
  }
```
So when we look for "x" in the AST, we think it's part of the "String n;" node.

IMO, it would be better for error recovery to synthesize the expected token, then continue, rather than consuming the token, which is more likely to result in cascading errors. Looking through the parser however it seems like a fairly pervasive problem. A bit outside my comfort zone to tackle.

What I may do instead is just try and harden the field inference code. If it can't find the initializer, seems like bailing out is a better strategy than crashing. :)

**Comment by jmesserly** [comment]
The other recovery trick here would be to pretend there was a comma between "x n". That would work for this example, but I don't have confidence that will prevent the problem in all cases.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1736563003/

**Comment by bwilkerson** [comment]
> ... will parse into something with "x" treated as the semicolon ...
> So when we look for "x" in the AST ...

Why are we looking for "x" if it was treated like a semicolon (which is clearly the wrong thing to do)?

**Comment by jmesserly** [comment]
there seems to be a pattern in parser to use: `_expect(TokenType.SEMICOLON)` and save the value in the statement. But the code for _expect is:
```dart

  /**
   * If the current token has the expected type, return it after advancing to
   * the next token. Otherwise report an error and return the current token
   * without advancing.
   *
   * Note that the method [_expectGt] should be used if the argument to this
   * method would be [TokenType.GT].
   *
   * The [type] is the type of token that is expected.
   */
  Token _expect(TokenType type) {
    if (_matches(type)) {
      return getAndAdvance();
    }
    // Remove uses of this method in favor of matches?
    // Pass in the error code to use to report the error?
    if (type == TokenType.SEMICOLON) {
      if (_tokenMatches(_currentToken.next, TokenType.SEMICOLON)) {
        _reportErrorForCurrentToken(
            ParserErrorCode.UNEXPECTED_TOKEN, [_currentToken.lexeme]);
        _advance();
        return getAndAdvance();
      }
      _reportErrorForToken(ParserErrorCode.EXPECTED_TOKEN,
          _currentToken.previous, [type.lexeme]);
    } else {
      _reportErrorForCurrentToken(
          ParserErrorCode.EXPECTED_TOKEN, [type.lexeme]);
    }
    return _currentToken;
  }
```

I misstated above, in fact it does not advance, but the token ends up used in two different AST nodes:
```
String n x = '';
^^^^^^^^^^         <-- span for: String n;
         ^^^^^^^   <-- span for: dynamic x = '';
```

**Comment by jmesserly** [comment]
yeah I didn't explain what was going on very well ... we're trying to infer `dynamic x = ''` which is marked as a VariableDeclaration node with an implicit type and an initializer. But we find `String n` node instead. (the quoted code is how those nodes print themselves via toString).

**Comment by bwilkerson** [comment]
I'm in the middle of trying a different approach. Update soon.

**Comment by jmesserly** [comment]
Go for it :)

**Comment by bwilkerson** [comment]
@jmesserly See https://codereview.chromium.org/1736873002/
