### ISSUE TITLE
NoSuchMethodError: method not found: 'library'

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#25884]
Dart analysis server, SDK version 1.15.0-edge.e4b800845b42381da08a1eac9f906d7ebb12a2a7, server version 1.14.0, error: Failed to send notification
The null object does not have a getter 'library'.
 
```
NoSuchMethodError: method not found: 'library'
Receiver: null
Arguments: []
# 0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
# 1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
# 2      _OverriddenElementsFinder._OverriddenElementsFinder (package:analysis_server/src/computer/computer_overrides.dart:141)
# 3      DartUnitOverridesComputer._addOverride (package:analysis_server/src/computer/computer_overrides.dart:66)
# 4      DartUnitOverridesComputer.compute (package:analysis_server/src/computer/computer_overrides.dart:43)
# 5      sendAnalysisNotificationOverrides.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:244)
# 6      _sendNotification.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:280)
# 7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
# 8      _sendNotification (package:analysis_server/src/operation/operation_analysis.dart:278)
# 9      sendAnalysisNotificationOverrides (package:analysis_server/src/operation/operation_analysis.dart:243)
# 10     _DartOverridesOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:503)
# 11     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:837)
# 12     Future.Future.<anonymous closure> (dart:async/future.dart:118)
# 13     _rootRun (dart:async/zone.dart:891)
# 14     _CustomZone.run (dart:async/zone.dart:790)
# 15     _CustomZone.runGuarded (dart:async/zone.dart:696)
# 16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
# 17     _rootRun (dart:async/zone.dart:895)
# 18     _CustomZone.run (dart:async/zone.dart:790)
# 19     _CustomZone.runGuarded (dart:async/zone.dart:696)
# 20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
# 21     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
# 22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
# 23     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
# 24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
 
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
    at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:208)
    at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
    at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
    at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
    at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
    at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
    at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
```

Looks similar to #24630

**Comment by bwilkerson** [comment]
It appears that we have a member of a class that doesn't know what class it's a part of. I don't know how to reproduce this, but have added debugging code in the hope that we can get more information (https://codereview.chromium.org/1775913005/).

**Comment by zoechi** [comment]
It's quite old. Should this be closed?

**Comment by bwilkerson** [comment]
Having not been able to reproduce it I can't say for sure that it's fixed, but it does seem likely to be stale.
