### ISSUE TITLE
"AnalysisException: Cannot compute DART_ERRORS"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25901]
I ran the analyzer while I was editing `stock_news.dart`, maybe just before I created it or while I was creating it, not sure. Anyway, the analyzer crashed with this output instead of gracefully handling whatever crazy state I had thrown at it:

```
AnalysisException: Cannot compute DART_ERRORS for .../flutter/examples/stocks/lib/main.dart
Caused by Could not find import element for '.../flutter/examples/stocks/lib/stock_news.dart'
Path to root: ImportDirectiveImpl, CompilationUnitImpl
#0      DeclarationResolver._mismatch (package:analyzer/src/generated/resolver.dart:2750)
#1      DeclarationResolver._findImport (package:analyzer/src/generated/resolver.dart:2635)
#2      DeclarationResolver.visitImportDirective (package:analyzer/src/generated/resolver.dart:2359)
#3      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:5637)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7429)
#5      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2375)
#6      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:646)
#7      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2369)
#8      DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2087)
```

If you can figure out how to repro this based on the stack, then good. If not, then feel free to just close this bug, I'll reopen it if I can repro reliably.

**Comment by bwilkerson** [comment]
I believe that this has been fixed in bleeding edge. The code that was failing has been moved to a later stage where it can be executed reliably.
