### ISSUE TITLE
Analysis Server exceptions with SDK 1.16.0-edge.37ad6d2d

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#26034]
Today's Dart SDK 1.16.0-edge.37ad6d2d1425003437e8ed78707587771b93a456
I've opened this project at this revision: https://github.com/dart-lang/sdk/tree/e1f6fc7c95c9506d137f950078fb108a3014a206 in WebStorm and got 6 errors:
### 1

```
Dart analysis server, SDK version 1.16.0-edge.37ad6d2d1425003437e8ed78707587771b93a456, server version 1.15.0, error: Task failed: BuildCompilationUnitElementTask for source C:\dart\dart-sdk-nightly\lib\io\http.dart
Mismatch in DeclarationResolver while resolving C:\dart\dart-sdk-nightly\lib\io\http.dart
Found element with name "HttpStatus" at 289, but expected offset of 280
Path to root: SimpleIdentifierImpl, ClassDeclarationImpl, CompilationUnitImpl
#0      RecursiveAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3490)
#1      DeclarationResolver._findWithNameAndOffset (package:analyzer/src/generated/resolver.dart:2694)
#2      DeclarationResolver._findIdentifier (package:analyzer/src/generated/resolver.dart:2667)
#3      DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2230)
#4      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1824)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7573)
#6      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2412)
#7      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2336)
#8      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2405)
#9      DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2206)
#10     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:895)
#11     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#12     AnalysisTask.perform (package:analyzer/task/model.dart:229)
#13     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#14     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#15     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1164)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#17     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1162)
#18     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:370)
#19     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:869)
#20     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#21     _rootRun (dart:async/zone.dart:891)
#22     _CustomZone.run (dart:async/zone.dart:790)
#23     _CustomZone.runGuarded (dart:async/zone.dart:696)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#25     _rootRun (dart:async/zone.dart:895)
#26     _CustomZone.run (dart:async/zone.dart:790)
#27     _CustomZone.runGuarded (dart:async/zone.dart:696)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#29     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#30     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#31     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```
### 2

```
Dart analysis server, SDK version 1.16.0-edge.37ad6d2d1425003437e8ed78707587771b93a456, server version 1.15.0, error: Task failed: VerifyUnitTask for source C:\dart_projects\dart-lang\sdk\tests\corelib\map_test.dart
Unexpected exception while performing VerifyUnitTask for source C:\dart_projects\dart-lang\sdk\tests\corelib\map_test.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1164)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1162)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:370)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:869)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:891)
#11     _CustomZone.run (dart:async/zone.dart:790)
#12     _CustomZone.runGuarded (dart:async/zone.dart:696)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#14     _rootRun (dart:async/zone.dart:895)
#15     _CustomZone.run (dart:async/zone.dart:790)
#16     _CustomZone.runGuarded (dart:async/zone.dart:696)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Class 'ClassElementHandle' has no instance method '_computeMixinAppConstructors'.

NoSuchMethodError: method not found: '_computeMixinAppConstructors'
Receiver: Instance of 'ClassElementHandle'
Arguments: [Instance(length:0) of '_GrowableList']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ClassElementImpl._computeMixinAppConstructors (package:analyzer/src/dart/element/element.dart:684)
#3      ClassElementImpl.constructors (package:analyzer/src/dart/element/element.dart:174)
#4      ClassElementImpl.unnamedConstructor (package:analyzer/src/dart/element/element.dart:395)
#5      ErrorVerifier._checkForUndefinedConstructorInInitializerImplicit (package:analyzer/src/generated/error_verifier.dart:5434)
#6      ErrorVerifier.visitConstructorDeclaration (package:analyzer/src/generated/error_verifier.dart:557)
#7      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2847)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7573)
#9      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1884)
#10     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:2312)
#11     ErrorVerifier.visitClassDeclaration (package:analyzer/src/generated/error_verifier.dart:461)
#12     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1824)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7573)
#14     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2412)
#15     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2336)
#16     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:528)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2405)
#18     VerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:5187)
#19     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#20     AnalysisTask.perform (package:analyzer/task/model.dart:229)
#21     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#22     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#23     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1164)
#24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#25     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1162)
#26     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:370)
#27     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:869)
#28     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#29     _rootRun (dart:async/zone.dart:891)
#30     _CustomZone.run (dart:async/zone.dart:790)
#31     _CustomZone.runGuarded (dart:async/zone.dart:696)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#33     _rootRun (dart:async/zone.dart:895)
#34     _CustomZone.run (dart:async/zone.dart:790)
#35     _CustomZone.runGuarded (dart:async/zone.dart:696)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#37     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#38     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#39     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```
### 3

```
Dart analysis server, SDK version 1.16.0-edge.37ad6d2d1425003437e8ed78707587771b93a456, server version 1.15.0, error: Failed to index: C:\dart_projects\dart-lang\sdk\tests\language\constructor_setter_negative_test.dart
Invalid argument(s): Unsupported synthetic element FieldElementImpl
#0      PackageIndexAssembler.newElementInfo (package:analyzer/src/summary/index_unit.dart:232)
#1      PackageIndexAssembler._getElementInfo.<anonymous closure> (package:analyzer/src/summary/index_unit.dart:143)
#2      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:254)
#3      PackageIndexAssembler._getElementInfo (package:analyzer/src/summary/index_unit.dart:140)
#4      _UnitIndexAssembler.addElementRelation (package:analyzer/src/summary/index_unit.dart:761)
#5      _IndexContributor.recordRelationOffset (package:analyzer/src/summary/index_unit.dart:371)
#6      _IndexContributor.recordRelation (package:analyzer/src/summary/index_unit.dart:340)
#7      _IndexContributor.visitConstructorFieldInitializer (package:analyzer/src/summary/index_unit.dart:447)
#8      ConstructorFieldInitializerImpl.accept (package:analyzer/src/dart/ast/ast.dart:2945)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7573)
#10     ConstructorDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2855)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:2068)
#12     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:1807)
#13     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:1895)
#14     GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:1853)
#15     GeneralizingAstVisitor.visitConstructorDeclaration (package:analyzer/dart/ast/visitor.dart:1881)
#16     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2847)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7573)
#18     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1884)
#19     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:2068)
#20     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:1807)
#21     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:1895)
#22     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:1870)
#23     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:2053)
#24     GeneralizingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:1851)
#25     _IndexContributor.visitClassDeclaration (package:analyzer/src/summary/index_unit.dart:433)
#26     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1824)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7573)
#28     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2412)
#29     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:2068)
#30     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1867)
#31     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2405)
#32     PackageIndexAssembler.index (package:analyzer/src/summary/index_unit.dart:129)
#33     _ContextIndex.indexUnit (package:analysis_server/src/services/index/index.dart:264)
#34     Index.indexUnit (package:analysis_server/src/services/index/index.dart:87)
#35     _DartIndexOperation.perform.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:458)
#36     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#37     _DartIndexOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:456)
#38     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:869)
#39     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#40     _rootRun (dart:async/zone.dart:891)
#41     _CustomZone.run (dart:async/zone.dart:790)
#42     _CustomZone.runGuarded (dart:async/zone.dart:696)
#43     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#44     _rootRun (dart:async/zone.dart:895)
#45     _CustomZone.run (dart:async/zone.dart:790)
#46     _CustomZone.runGuarded (dart:async/zone.dart:696)
#47     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#48     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#49     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#50     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```
### 4

```
Dart analysis server, SDK version 1.16.0-edge.37ad6d2d1425003437e8ed78707587771b93a456, server version 1.15.0, error: Task failed: BuildCompilationUnitElementTask for source C:\dart\dart-sdk-nightly\lib\_internal\js_runtime\lib\foreign_helper.dart
Mismatch in DeclarationResolver while resolving C:\dart\dart-sdk-nightly\lib\_internal\js_runtime\lib\foreign_helper.dart
Found element with name "JS" at 6587, but expected offset of 6443
Path to root: SimpleIdentifierImpl, FunctionDeclarationImpl, CompilationUnitImpl
#0      RecursiveAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3490)
#1      DeclarationResolver._findWithNameAndOffset (package:analyzer/src/generated/resolver.dart:2694)
#2      DeclarationResolver._findIdentifier (package:analyzer/src/generated/resolver.dart:2667)
#3      DeclarationResolver.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:2377)
#4      FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4988)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7573)
#6      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2412)
#7      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2336)
#8      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2405)
#9      DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2206)
#10     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:895)
#11     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#12     AnalysisTask.perform (package:analyzer/task/model.dart:229)
#13     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#14     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#15     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1164)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#17     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1162)
#18     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:370)
#19     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:869)
#20     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#21     _rootRun (dart:async/zone.dart:891)
#22     _CustomZone.run (dart:async/zone.dart:790)
#23     _CustomZone.runGuarded (dart:async/zone.dart:696)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#25     _rootRun (dart:async/zone.dart:895)
#26     _CustomZone.run (dart:async/zone.dart:790)
#27     _CustomZone.runGuarded (dart:async/zone.dart:696)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#29     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#30     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#31     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```
### 5

```
Dart analysis server, SDK version 1.16.0-edge.37ad6d2d1425003437e8ed78707587771b93a456, server version 1.15.0, error: Task failed: BuildCompilationUnitElementTask for source C:\dart\dart-sdk-nightly\lib\io\file.dart
Mismatch in DeclarationResolver while resolving C:\dart\dart-sdk-nightly\lib\io\file.dart
Found element with name "FileMode" at 302, but expected offset of 293
Path to root: SimpleIdentifierImpl, ClassDeclarationImpl, CompilationUnitImpl
#0      RecursiveAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3490)
#1      DeclarationResolver._findWithNameAndOffset (package:analyzer/src/generated/resolver.dart:2694)
#2      DeclarationResolver._findIdentifier (package:analyzer/src/generated/resolver.dart:2667)
#3      DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2230)
#4      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1824)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7573)
#6      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2412)
#7      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2336)
#8      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2405)
#9      DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2206)
#10     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:895)
#11     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#12     AnalysisTask.perform (package:analyzer/task/model.dart:229)
#13     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#14     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#15     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1164)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#17     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1162)
#18     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:370)
#19     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:869)
#20     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#21     _rootRun (dart:async/zone.dart:891)
#22     _CustomZone.run (dart:async/zone.dart:790)
#23     _CustomZone.runGuarded (dart:async/zone.dart:696)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#25     _rootRun (dart:async/zone.dart:895)
#26     _CustomZone.run (dart:async/zone.dart:790)
#27     _CustomZone.runGuarded (dart:async/zone.dart:696)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#29     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#30     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#31     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```
### 6

```
Dart analysis server, SDK version 1.16.0-edge.37ad6d2d1425003437e8ed78707587771b93a456, server version 1.15.0, error: Task failed: BuildCompilationUnitElementTask for source C:\dart\dart-sdk-nightly\lib\_internal\js_runtime\lib\shared\embedded_names.dart
Mismatch in DeclarationResolver while resolving C:\dart\dart-sdk-nightly\lib\_internal\js_runtime\lib\shared\embedded_names.dart
Found element with name "TYPEDEF_PREDICATE_PROPERTY_NAME" at 942, but expected offset of 921
Path to root: SimpleIdentifierImpl, VariableDeclarationImpl, VariableDeclarationListImpl, TopLevelVariableDeclarationImpl, CompilationUnitImpl
#0      RecursiveAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3490)
#1      DeclarationResolver._findWithNameAndOffset (package:analyzer/src/generated/resolver.dart:2694)
#2      DeclarationResolver._findIdentifier (package:analyzer/src/generated/resolver.dart:2667)
#3      DeclarationResolver.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:2622)
#4      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10614)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7573)
#6      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10715)
#7      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:2847)
#8      DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:2639)
#9      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10709)
#10     TopLevelVariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9933)
#11     RecursiveAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:2805)
#12     DeclarationResolver.visitTopLevelVariableDeclaration (package:analyzer/src/generated/resolver.dart:2574)
#13     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:9928)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7573)
#15     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2412)
#16     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2336)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2405)
#18     DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2206)
#19     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:895)
#20     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#21     AnalysisTask.perform (package:analyzer/task/model.dart:229)
#22     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#23     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#24     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1164)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#26     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1162)
#27     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:370)
#28     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:869)
#29     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#30     _rootRun (dart:async/zone.dart:891)
#31     _CustomZone.run (dart:async/zone.dart:790)
#32     _CustomZone.runGuarded (dart:async/zone.dart:696)
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#34     _rootRun (dart:async/zone.dart:895)
#35     _CustomZone.run (dart:async/zone.dart:790)
#36     _CustomZone.runGuarded (dart:async/zone.dart:696)
#37     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#38     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#39     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#40     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
@scheglov See items 2 and 3.

**Comment by scheglov** [comment]
CL for fixing 3.
https://codereview.chromium.org/1816583002

**Comment by bwilkerson** [comment]
2: https://codereview.chromium.org/1815253002/

**Comment by natebosch** [comment]
Looks like some fixes went in - hopefully this was resolved.
If not we won't be able to repro a stack trace against a very old analyzer. Please file a new issue if this is still a problem on the latest SDK.
