### ISSUE TITLE
Class 'LibraryElementHandle' has no instance getter '_libraryCycle'.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26035]
Seems this exception is thrown on each key press

> Dart analysis server, SDK version 1.16.0-edge.4b8ee463de0430bb9bcba3bf1845642f3795a0cb, server version 1.15.0, error: Failed to handle completion domain request: {clientRequestTime: 1458291698712, params: {file: /home/zoechi/dart/bwu_ng_quick_nav/lib/src/bwu_quick_nav_routing.dart, offset: 1395}, method: completion.getSuggestions, id: 106}
AnalysisException: failed to resolve declarations
Caused by Unexpected exception while performing BuildDirectiveElementsTask for source /home/zoechi/dart/bwu_ng_quick_nav/lib/bwu_ng_quick_nav.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1164)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1162)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:370)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:869)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:891)
#11     _CustomZone.run (dart:async/zone.dart:790)
#12     _CustomZone.runGuarded (dart:async/zone.dart:696)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#14     _rootRun (dart:async/zone.dart:895)
#15     _CustomZone.run (dart:async/zone.dart:790)
#16     _CustomZone.runGuarded (dart:async/zone.dart:696)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
>
Caused by Class 'LibraryElementHandle' has no instance getter '_libraryCycle'.
>
NoSuchMethodError: method not found: '_libraryCycle'
Receiver: Instance of 'LibraryElementHandle'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3596)
#3      List.forEach (dart:core-patch/growable_array.dart:254)
#4      LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3601)
#5      List.forEach (dart:core-patch/growable_array.dart:254)
#6      LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3597)
#7      List.forEach (dart:core-patch/growable_array.dart:254)
#8      LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3597)
#9      List.forEach (dart:core-patch/growable_array.dart:254)
#10     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3597)
#11     List.forEach (dart:core-patch/growable_array.dart:254)
#12     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3597)
#13     List.forEach (dart:core-patch/growable_array.dart:254)
#14     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3597)
#15     List.forEach (dart:core-patch/growable_array.dart:254)
#16     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3597)
#17     List.forEach (dart:core-patch/growable_array.dart:254)
#18     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3597)
#19     List.forEach (dart:core-patch/growable_array.dart:254)
#20     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3597)
#21     List.forEach (dart:core-patch/growable_array.dart:254)
#22     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3600)
#23     List.forEach (dart:core-patch/growable_array.dart:254)
#24     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3601)
#25     List.forEach (dart:core-patch/growable_array.dart:254)
#26     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3601)
#27     List.forEach (dart:core-patch/growable_array.dart:254)
#28     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3600)
#29     List.forEach (dart:core-patch/growable_array.dart:254)
#30     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3601)
#31     List.forEach (dart:core-patch/growable_array.dart:254)
#32     LibraryElementImpl.invalidateLibraryCycles.invalidate (package:analyzer/src/dart/element/element.dart:3597)
#33     LibraryElementImpl.invalidateLibraryCycles (package:analyzer/src/dart/element/element.dart:3603)
#34     BuildDirectiveElementsTask.internalPerform (package:analyzer/src/task/dart.dart:1036)
#35     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#36     AnalysisTask.perform (package:analyzer/task/model.dart:229)
#37     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#38     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#39     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1164)
#40     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#41     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1162)
#42     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:370)
#43     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:869)
#44     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#45     _rootRun (dart:async/zone.dart:891)
#46     _CustomZone.run (dart:async/zone.dart:790)
#47     _CustomZone.runGuarded (dart:async/zone.dart:696)
#48     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#49     _rootRun (dart:async/zone.dart:895)
#50     _CustomZone.run (dart:async/zone.dart:790)
#51     _CustomZone.runGuarded (dart:async/zone.dart:696)
#52     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#53     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#54     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#55     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
>
>
#0      AnalysisFutureHelper.computeAsync.<anonymous closure> (package:analyzer/src/context/context.dart:2016)
#1      PendingFuture.evaluate (package:analyzer/src/context/context.dart:2121)
#2      AnalysisFutureHelper.computeAsync (package:analyzer/src/context/context.dart:2022)
#3      DartCompletionRequestImpl._computeAsync.<_computeAsync_async_body> (package:analysis_server/src/services/completion/dart/completion_manager.dart:425)
#4      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#5      _rootRun (dart:async/zone.dart:891)
#6      _CustomZone.run (dart:async/zone.dart:790)
#7      _CustomZone.runGuarded (dart:async/zone.dart:696)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#9      _rootRun (dart:async/zone.dart:895)
#10     _CustomZone.run (dart:async/zone.dart:790)
#11     _CustomZone.runGuarded (dart:async/zone.dart:696)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
>
>
#0      DartCompletionRequestImpl._computeAsync.<_computeAsync_async_body> (package:analysis_server/src/services/completion/dart/completion_manager.dart:430)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _rootRunBinary (dart:async/zone.dart:914)
#3      _CustomZone.runBinary (dart:async/zone.dart:806)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:581)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:643)
#6      _Future._completeError (dart:async/future_impl.dart:434)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:490)
#8      _rootRun (dart:async/zone.dart:895)
#9      _CustomZone.run (dart:async/zone.dart:790)
#10     _CustomZone.runGuarded (dart:async/zone.dart:696)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:208)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
>
>
>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:208)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
>
>
>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:208)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
>
>
>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:208)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
>
>
>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:208)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
>
>
>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:208)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)

**Comment by bwilkerson** [comment]
@scheglov I'm guessing this is a result of enabling summaries for the SDK (because I don't know how else we would have gotten a LibraryElementHandle). Let's talk this morning.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/1810393002/
