### ISSUE TITLE
Exceptions thrown across JS interop show up as 'V8 Exception' in Dartium

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#26093]
As of Dart 1.15.0, when using the new `package:js` JS interop, exceptions thrown across JS interop show up as `'V8 Exception'` in Dartium, when they used to be a toString'd version of the exception.

This is especially problematic when trying to debug exceptions in Dart code that's called from the JS. 

Note the output for the following code in different Dart versions:

``` js
// JS

function jsThrowError() {
  throw new Error("I'm a JavaScript error!");
}

function jsCallFunction(functionToCall) {
  functionToCall();
}
```

``` dart
// Dart

import 'package:js/js.dart';

@JS()
external void jsThrowError();

@JS()
external void jsCallFunction(functionToCall);

main() {
  print('Throwing exception in JS function...');
  try {
    jsThrowError();
  } catch(e) {
    print('Type: ${e.runtimeType}');
    print(e);
  }

  print('');

  print('Throwing exception in Dart function called from JS...');
  try {
    jsCallFunction(allowInterop(() {
      throw new Exception("I'm an exception from Dart!");
    }));
  } catch(e) {
    print('Type: ${e.runtimeType}');
    print(e);
  }
}
```
### dart2js - Dart 1.13.2, Dart 1.14.0, Dart 1.15.0, Dart 1.16.0-dev.2.0

```
Throwing exception in JS function...
Type: JSObject
Error: I'm a JavaScript error!

Throwing exception in Dart function called from JS...
Type: _Exception
Exception: I'm an exception from Dart!
```
### Dartium - Dart 1.13.2, Dart 1.14.0

This output is slightly different than dart2js: errors are toString'd.

This kind difference is to be expected between dart2js and Dartium, but at least we get String versions of the exceptions we can use to debug. 

```
Throwing exception in JS function...
Type: String
Error: I'm a JavaScript error!

Throwing exception in Dart function called from JS...
Type: String
Unhandled exception:
Exception: I'm an exception from Dart!
#0      main.<anonymous closure> (http://localhost:8080/v8_exception_demo.dart:23:7)
#1      JsFunction._apply (dart:js:1178)
#2      JsFunction.apply (dart:js:1176)
#3      jsCallFunction (http://localhost:8080/v8_exception_demo.dart_js_interop_patch.dart:10:66)
#4      main (http://localhost:8080/v8_exception_demo.dart:22:5)
```
### Dartium - Dart 1.15.0, Dart 1.16.0-dev.2.0

All exceptions show up as the string `V8 Exception`, which makes it hard to debug what kind of error we're dealing with.

```
Throwing exception in JS function...
Type: String
V8 Exception

Throwing exception in Dart function called from JS...
Type: String
V8 Exception
```

**Comment by jacehensley-wf** [comment]
Are there any updates to this issue? Thanks!

**Comment by greglittlefield-wf** [comment]
Worth noting that Dart 1.17 seems to show fewer V8 Exceptions, but it does still show them.

**Comment by terrylucas** [comment]
The package js.dart doesn't work in Dartium.

**Comment by matanlurey** [comment]
@terrylucas Is that true? I use it in AngularDart and it works for both Dartium+DDC+dart2js.

**Comment by terrylucas** [comment]
It's not true (was for a short time during dev which I remembered).

**Comment by terrylucas** [comment]
With Dart 1.24.1 Stable (Dartium 50) the output is:
```
Observatory listening at http://127.0.0.1:44938/
Throwing exception in JS function...
Type: String
Error: I'm a JavaScript error!

Throwing exception in Dart function called from JS...
Type: String
Unhandled exception:
Exception: I'm an exception from Dart!
#0      main.<anonymous closure> (http://localhost:63342/chartjs_sample/web/main.dart:18:7)
#1      _JSObjectBase._callMethod (dart:js:1111)
#2      JsNative.callMethod (dart:js:1455)
#3      jsCallFunction (http://localhost:63342/chartjs_sample/web/js_library.dart_js_interop_patch.dart:11:30)
#4      main (http://localhost:63342/chartjs_sample/web/main.dart:17:5)
```
Here's your code slightly modified:

**test.html**
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Dart JS Interop</title>
    <script>
        function jsThrowError() {
            throw new Error("I'm a JavaScript error!");
        }

        function jsCallFunction(functionToCall) {
            functionToCall();
        }
    </script>
    <script defer src="main.dart" type="application/dart"></script>
    <script defer src="packages/browser/dart.js"></script>
</head>
<body>
</body>
</html>
```
**library_js.dart**
```
@JS()
library js_library;

import 'package:js/js.dart';

@JS()
external jsThrowError();

@JS()
external jsCallFunction(functionToCall);
```
**main.dart**
```
import 'package:js/js.dart';
import "js_library.dart";

main() {
  print('Throwing exception in JS function...');
  try {
    jsThrowError();
  } catch(e) {
    print('Type: ${e.runtimeType}');
    print(e);
  }

  print('');

  print('Throwing exception in Dart function called from JS...');
  try {
    jsCallFunction(allowInterop(() {
      throw new Exception("I'm an exception from Dart!");
    }));
  } catch(e) {
    print('Type: ${e.runtimeType}');
    print(e);
  }
}
```
