### ISSUE TITLE
type '_BroadcastStream<EventData>' is not a subtype of type 'Stream<ContextMenu>'

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26091]
```dart
import 'dart:async' show Stream, StreamController;

class Events {
  static const EventType<ContextMenu> contextMenu =
      const EventType<ContextMenu>('bwu-context-menu');
}

class EventData {}

class EventType<T extends EventData> {
  final String name;
  const EventType(this.name);
}

class ContextMenu extends EventData {}

class EventBus<T extends EventData> {
  final Map<EventType<T>, StreamController<T>> streamControllers =
      <EventType<T>, StreamController<T>>{};

  Stream<T> onEvent(EventType<T> eventType) {
    return streamControllers.putIfAbsent(eventType, () {
      return new StreamController<T>.broadcast(sync: true);
    }).stream;
  }

  T fire(EventType<T> eventType, T data) {
    final StreamController<T> controller =
        streamControllers.putIfAbsent(eventType, () {
      return new StreamController<T>.broadcast(sync: true);
    });

    controller.add(data);
    return data;
  }
}

class Grid {
  EventBus<EventData> _eventBus = new EventBus<EventData>();

  Stream<ContextMenu> get onBwuContextMenu =>
      _eventBus.onEvent(Events.contextMenu);

  void someMethod() {
    onBwuContextMenu.listen((ContextMenu e) {
      print(e);
    });
  }
}

void main() {
  final Grid g = new Grid();
  g.someMethod();
}
```

results in 

```
Uncaught Unhandled exception:
type '_BroadcastStream<EventData>' is not a subtype of type 'Stream<ContextMenu>' in type cast where
  _BroadcastStream is from dart:async
  EventData is from package:bwu_datagrid/core/core.dart
  Stream is from dart:async
  ContextMenu is from package:bwu_datagrid/core/core.dart
>
#0      Object._as (dart:core-patch/object_patch.dart:67)
#1      BwuDatagrid.onBwuContextMenu (package:bwu_datagrid/bwu_datagrid.dart:4105:7)
#2      AppElement.attached.<anonymous closure> (package:bwu_datagrid_examples/e07_events/app_element.dart:65:14)
#3      _RootZone.runUnary (dart:async/zone.dart:1137)
#4      _Future._propagateToListeners
```

Is this a bug, am I doing something wrong, or is it just not possible to be built this way?

> Dart VM version: 1.16.0-edge.8606e22993df8de3466fc2d1d8de360f09b51692 (Thu Mar 24 14:39:02 2016) on "linux_x64"

**Comment by joseluis** [comment]
Same thing here I believe, also using extended generics. There were no warnings or errors in dartanalyzer 1.15.0-stable (strong mode), and there are many errors in 1.16.0-dev. This is a minimal code example:

```dart
abstract class StackBase<T extends num> { /* ... */ }

abstract class LifoStack<T extends num> extends StackBase<T> {
  // ...
  T get pop => _data[--_size];
}

class LifoStackInt<int> extends LifoStack { /* ... */ }

// e.g.:
LifoStackInt s = new LifoStackInt();
print(s.pop & s.pop);
print(s.pop.toUnsigned(32));
```

```
[error] The operator '&' is not defined for the class 'num'. (.../primitives.dart, line 417, col 42)
[error] The operator '~' is not defined for the class 'num'. (.../primitives.dart, line 632, col 25)
[error] The operator '<<' is not defined for the class 'num'. (.../primitives.dart, line 647, col 42)
[error] The operator '|' is not defined for the class 'num'. (.../primitives.dart, line 700, col 42)
[error] The operator '>>' is not defined for the class 'num'. (.../primitives.dart, line 952, col 42)
[error] The operator '^' is not defined for the class 'num'. (.../primitives.dart, line 1031, col 42)
[error] The method 'toUnsigned' is not defined for the class 'num'. (.../primitives.dart, line 1039, col 30)
// ...
```

**Comment by floitschG** [comment]
@joseluis: you probably just need to change the declaration of `class LifoStackInt`:
`class LifoStackInt extends LifoStack<int>`.
I didn't see any warning with dart2js or the analyzer with my current version, so I'm not 100% sure if that's what caused the error.

@zoechi: isn't that expected?
`eventBus` is declared to be a `new EventBus<EventData>`.
`onEvent` returns a `Stream<T>`, thus `Stream<EventData>` (to be more precise a `new StreamController<T>.broadcast`).
The getter `onBwuContextMenu` declares to return a `Stream<ContextMenu>`. However, a `Stream<EventData>` is not a `Stream<ContextMenu>` and that leads to the dynamic error.

**Comment by joseluis** [comment]
@floitschG thanks that was it.

**Comment by zoechi** [comment]
@floitschG thanks a lot :+1: and sorry for bothering you, should have checked better :-/

**Comment by floitschG** [comment]
No problem :)
