### ISSUE TITLE
Cannot compute RESOLVED_UNIT... 

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#26097]
Caught this one while refactoring two related projects in Atom, where one references the other. Not sure how to reproduce this, but glad that the server figured out that it was in an infinite loop and stopped...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.4
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.8

### Stack Trace
```
Uncaught [Analyzer RequestError method: analysis.setSubscriptions, code: SERVER_ERROR, message: AnalysisException: Cannot compute RESOLVED_UNIT for /<redacted>/atom.dart/lib/atom_utils.dart in /<redacted>/atom.dart/lib/atom_utils.dart
Caused by Infinite loop while performing task InferInstanceMembersInUnitTask for /<redacted>/atom.dart/lib/atom_utils.dart in /<redacted>/atom.dart/lib/atom_utils.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:326)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:273)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:248)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1164)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1162)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:872)
#9      Future.Future.delayed.<anonymous closure> (dart:async/future.dart:228)
#10     _rootRun (dart:async/zone.dart:891)
#11     _CustomZone.run (dart:async/zone.dart:790)
#12     _CustomZone.runGuarded (dart:async/zone.dart:696)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#14     _rootRun (dart:async/zone.dart:895)
#15     _CustomZone.run (dart:async/zone.dart:790)
#16     _CustomZone.runGuarded (dart:async/zone.dart:696)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by scheglov** [comment]
I think this is fixed now with https://github.com/dart-lang/sdk/commit/bc8b32145baba551e08508b7f9062ca92f18d93e.
