### ISSUE TITLE
History.pushState - throws UnimplementedError: structured clone of other type

### ISSUE THREAD

**Issue by jonboj** [dart-lang/sdk#26108]
Applying History.pushState method to a Dart object
https://api.dartlang.org/stable/1.15.0/dart-html/History/pushState.html

Results in stackdump below, indicating problems with the conversion to native. 

Dart object tried to pushed

```
class AppState {
  final int index;

  AppState(this.index){
  }
}

```
Environment
`Ubuntu 15.10, Dart sdk - 1.15.0`

Stackdump
```
Uncaught Unhandled exception:
UnimplementedError: structured clone of other type
#0      _StructuredClone.walk (file:///mnt/data/b/build/slave/dartium-lucid64-full-stable/build/src/dart/sdk/lib/html/html_common/conversions.dart:136)
#1      _StructuredClone.convertDartToNative_PrepareForStructuredClone (file:///mnt/data/b/build/slave/dartium-lucid64-full-stable/build/src/dart/sdk/lib/html/html_common/conversions.dart:151)
#2      convertDartToNative_PrepareForStructuredClone (file:///mnt/data/b/build/slave/dartium-lucid64-full-stable/build/src/dart/sdk/lib/html/html_common/conversions_dartium.dart:4)
#3      convertDartToNative_SerializedScriptValue (file:///mnt/data/b/build/slave/dartium-lucid64-full-stable/build/src/dart/sdk/lib/html/html_common/conversions.dart:33)
#4      History.pushState (dart:html:19793)
#5      AppHistoryCtrl.pushState (package:mintest/app_history_ctrl.dart:35:20)

```

**Comment by alan-knight** [comment]
Yes, you can only push things that can be serialized. Dart objects are opaque to JavaScript, so it would have to be converted to a Map or some other representation that the JS  Structured Clone algorithm knows how to deal with. http://w3c.github.io/html/infrastructure.html#safe-passing-of-structured-data
