### ISSUE TITLE
Crash in strong mode analyzer Cannot compute LIBRARY_ELEMENT

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#26115]
```
enum T {A9 B = ,99, C, D}

void x() {
  print(T.B.index);
  
}
```

```
dartanalyzer --strong REDUCTION.dart


Unhandled exception:
AnalysisException: Cannot compute LIBRARY_ELEMENT for /Users/lukechurch/Analysis/strongMode/STRONG_MODE/REDUCTION.dart
Caused by Failed to find the declaration of the variable B in /Users/lukechurch/Analysis/strongMode/STRONG_MODE/REDUCTION.dart
#0      InferStaticVariableTask.getDeclaration (package:analyzer/src/task/dart.dart:3096)
#1      ComputeInferableStaticVariableDependenciesTask.internalPerform (package:analyzer/src/task/dart.dart:2006)
#2      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#3      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#4      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#5      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#6      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:651)
#7      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:624)
#8      AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:259)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#10     AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:258)
#11     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
#12     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126)
#13     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:533)
#14     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:184)
#15     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:127)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#17     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:126)
#18     Driver.start (package:analyzer_cli/src/driver.dart:112)
#19     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:14)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:655)
#1      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:624)
#2      AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:259)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#4      AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:258)
#5      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
#6      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126)
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:533)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:184)
#9      Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:127)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#11     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:126)
#12     Driver.start (package:analyzer_cli/src/driver.dart:112)
#13     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:14)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/054be34e6cda5aca9bcc7c63aa679e9bc0ab3d89
