### ISSUE TITLE
analyzer allows instantiating a type parameter

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#26124]
here's the VM throwing:

```
$ dart --package-root=xcodebuild/ReleaseX64/packages/ ./tests/language/prefix10_negative_test.dart 
Unhandled exception:
'./tests/language/prefix10_negative_test.dart': malformed type: line 16 pos 17: type parameter 'T' cannot be instantiated
    var i = new T.Library10(10);  // This should be an error.
                ^


#0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:56)
#1      P.main (./tests/language/prefix10_negative_test.dart:16:17)
#2      main (./tests/language/prefix10_negative_test.dart:23:5)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

vs analyzer:

```
$ dartanalyzer --package-root=xcodebuild/ReleaseX64/packages/ ./tests/language/prefix10_negative_test.dart 
Analyzing [./tests/language/prefix10_negative_test.dart]...
[hint] Unused import (./tests/language/prefix10_negative_test.dart, line 10, col 8)
1 hint found.
```

This seems like an easy problem to detect statically.

**Comment by bwilkerson** [comment]
It should be easy, obviously just overlooked. (Though I'd kind of prefer allowing it.)

**Comment by jmesserly** [comment]
this is still an issue. Might go away after switch to CFE, if it does this checking?

**Comment by srawlins** [comment]
Still an issue

**Comment by srawlins** [comment]
This test lives at `tests/language/prefix/shadow_test.dart` and the analyzer now reports an error.
