### ISSUE TITLE
Unabel to find variable crash on InferStaticVariableTask in Strong mode

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#26148]
Version: 0.27.3-alpha.6
```
vo r@(i $=) namt
 pd1
nv
  p3;
  (m( mia}numn":; n u {{) tin"riu2 r
}
```

```
AnalysisException: Cannot compute DART_ERRORS for StringSource (main.dart)
Caused by Failed to find the declaration of the variable $ in StringSource (main.dart)
#0      InferStaticVariableTask.getDeclaration (package:analyzer/src/task/dart.dart:2996:7)
#1      ComputeInferableStaticVariableDependenciesTask.internalPerform (package:analyzer/src/task/dart.dart:1882:39)
#2      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329:9)
#3      AnalysisTask.perform (package:analyzer/task/model.dart:229:7)
#4      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276:10)
#5      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251:9)
#6      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1167:27)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#8      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1165:50)
#9      Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:161:24)
#10     Analyzer.analyzeMulti (package:services/src/analyzer.dart:100:7)
#11     CommonServer._analyzeMulti.<_analyzeMulti_async_body> (package:services/src/common_server.dart:316:12)
#12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:676:7)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:620:12)
#2      Analyzer.analyzeMulti.<anonymous closure> (package:services/src/analyzer.dart:104:18)
#3      List.forEach (dart:core-patch/growable_array.dart:254)
#4      Analyzer.analyzeMulti (package:services/src/analyzer.dart:103:19)
#5      CommonServer._analyzeMulti.<_analyzeMulti_async_body> (package:services/src/common_server.dart:316:12)
#6      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/1851623002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/054be34e6cda5aca9bcc7c63aa679e9bc0ab3d89
