### ISSUE TITLE
Frequent timeouts of precompilation_test on the buildbot only

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#26144]
For example:
https://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-be/builds/12996/steps/vm%20tests/logs/stdio
https://build.chromium.org/p/client.dart/builders/vm-mac-release-x64-be/builds/12543/steps/checked%20vm%20tests/logs/stdio

**Comment by fsc8000** [comment]
It looks like the test hangs when running the program:
```
stdout:
Creating precompiled snapshot...
Creating shared library...
Running test program...
```

**Comment by rmacnak-google** [comment]
```
(gdb) thread apply all bt

Thread 2 (Thread 0xf7464b40 (LWP 10023)):
#0  0xf77b3440 in __kernel_vsyscall ()
#1  0xf7554696 in epoll_wait () from /lib/i386-linux-gnu/libc.so.6
#2  0x0805f995 in dart::bin::EventHandlerImplementation::Poll (args=162890080)
    at runtime/bin/eventhandler_linux.cc:391
#3  0x0805cb21 in dart::bin::ThreadStart (data_ptr=<optimized out>)
    at runtime/bin/thread_linux.cc:91
#4  0xf7771f70 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#5  0xf7553bee in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 1 (Thread 0xf7466700 (LWP 10022)):
#0  0xf77b3440 in __kernel_vsyscall ()
#1  0xf7775d4b in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib/i386-linux-gnu/libpthread.so.0
#2  0x081d3e1f in dart::Monitor::WaitMicros (this=<optimized out>, micros=0)
    at runtime/vm/os_thread_linux.cc:401
#3  0x081d3d3a in dart::Monitor::Wait (this=0x9bf9f50, millis=0)
    at runtime/vm/os_thread_linux.cc:385
#4  0x081ecda8 in Wait (millis=<optimized out>, this=<optimized out>, 
    millis=<optimized out>) at runtime/vm/lockers.h:169
#5  dart::ServiceIsolate::KillServiceIsolate ()
    at runtime/vm/service_isolate.cc:457
---Type <return> to continue, or q <return> to quit---
#6  0x0811efd0 in dart::Dart::Cleanup () at runtime/vm/dart.cc:307
#7  0x08071497 in Dart_Cleanup () at runtime/vm/dart_api_impl.cc:1176
#8  0x08052226 in dart::bin::main (argc=<optimized out>, argv=<optimized out>)
    at runtime/bin/main.cc:1677
#9  0x08052a58 in main (argc=5, argv=0xffb208b4) at runtime/bin/main.cc:1711
```

**Comment by rmacnak-google** [comment]
@johnmccutchan

**Comment by rmacnak-google** [comment]
321872ed73a2a350d02e485540f3309a687ce88d
