### ISSUE TITLE
Error from the analysis server: Found constructor element named _internal with no enclosing element

### ISSUE THREAD

**Issue by mezoni** [dart-lang/sdk#26179]
```
null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:975)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:46)
#2      ConstructorElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:1373)
#3      ElementImpl.toString (package:analyzer/src/dart/element/element.dart:2079)
#4      DartUnitHoverComputer.compute (package:analysis_server/src/computer/computer_hover.dart:56)
#5      AnalysisDomainHandler.getHover (package:analysis_server/src/domain_analysis.dart:100)
#6      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:193)
#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:743)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#9      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:739)
#10     _rootRun (dart:async/zone.dart:895)
#11     _CustomZone.run (dart:async/zone.dart:790)
#12     _CustomZone.runGuarded (dart:async/zone.dart:696)
#13     runZoned (dart:async/zone.dart:1231)
#14     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:738)
#15     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#17     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#18     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#19     _rootRunUnary (dart:async/zone.dart:902)
#20     _CustomZone.runUnary (dart:async/zone.dart:798)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:130)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:105)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#30     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#31     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#32     _rootRunUnary (dart:async/zone.dart:902)
#33     _CustomZone.runUnary (dart:async/zone.dart:798)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#40     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#41     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#42     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#43     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#45     _rootRunUnary (dart:async/zone.dart:902)
#46     _CustomZone.runUnary (dart:async/zone.dart:798)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#50     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#51     _StreamController._add (dart:async/stream_controller.dart:632)
#52     _StreamController.add (dart:async/stream_controller.dart:578)
#53     _Socket._onData (dart:io-patch/socket_patch.dart:1648)
#54     _rootRunUnary (dart:async/zone.dart:906)
#55     _CustomZone.runUnary (dart:async/zone.dart:798)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#59     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#60     _StreamController._add (dart:async/stream_controller.dart:632)
#61     _StreamController.add (dart:async/stream_controller.dart:578)
#62     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1215)
#63     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#64     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#65     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#66     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#67     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by mezoni** [comment]
Shutdown -> Start -> Reanalyze -> Shutdown -> Start -> Reanalyze -> ...
This does not helps locate the problem.
Exception throws periodically, what causes it to throws are unknown.
Source code is not so much and it works (but periodically throws this `null exception`).
P.S.
The `null exception` this is very informative message!

**Comment by mezoni** [comment]
How to access this log?

```
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:46)
```

Already very tired of this pop-up message (about the error from the analysis server) in 'dart-plugin' for Atom.

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
