### ISSUE TITLE
VM Service: an Isolate that closed due to an error doesn't have its error field set

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26203]
When a Dart process is started with `--pause-isolates-on-exit` and the main isolate exits due to an unhandled error, `getIsolate()` no longer returns an object with an `Isolate.error` field. [Here's an inspector view](http://www.jsonmate.com/permalink/57055cc1180f6b4d110f5065) of the isolate JSON; note that `pauseEvent` is `PauseExit`, but there's no `error` field.

This seems to have started some time between 1.15 and 9f43293f274c20667d0e020a0afc311c7add695a.

See also dart-lang/vm_service_client#5

**Comment by nex3** [comment]
The easiest way to reproduce this is probably to run `pub run test test/error_test.dart -n 'for an async error includes error metadata'` in [`vm_service_client`](/dart-lang/vm_service_client).

**Comment by johnmccutchan** [comment]
Confirmed in bleeding_edge.

```dart
main() {
  throw "an error";
}
```

Looks related to the move of sticky error from isolate to thread.

Fix is here: https://codereview.chromium.org/1862903003

**Comment by kevmoo** [comment]
Thanks much, @johnmccutchan !

**Comment by nex3** [comment]
I'm still seeing this as of e048774776f20cf45edddf607a0c90abcb3ccd07. [Here's a response to `getIsolate()`](http://www.jsonmate.com/permalink/570c031d180f6b4d110f5089) for a `main()` that synchronously throws an exception, run with `--pause-isolates-on-exit`. Note that `Isolate.pauseEvent` is `PauseException`, but there's no `Isolate.error` field. The same `pub run test` invocation from before should still reproduce this.

**Comment by kevmoo** [comment]
@johnmccutchan Can you look into this ASAP?

**Comment by mit-mit** [comment]
Just elaborating: This is blocking google3 rolls, and thus potentially blocking the final validation of releasing 1.16 to stable.

**Comment by johnmccutchan** [comment]
@kevmoo @mit-mit How is this bug blocking google3 rolls?

**Comment by johnmccutchan** [comment]
@nex3 

Here is my script:

```dart
main() async {
  throw "oh no";
}
```

I run it as follows:

```
$ ./out/DebugX64/dart --enable-vm-service --pause-isolates-on-exit script.dart
```

I grab the isolate like so:

```
$ curl localhost:8181/getIsolate?isolateId=isolates/root|python -mjson.tool
```

I get the following:

```json
{
    "id": "",
    "jsonrpc": "2.0",
    "result": {
        "_debuggerSettings": {
            "_exceptions": "none"
        },
        "_heaps": {
            "new": {
                "avgCollectionPeriodMillis": 0.0,
                "capacity": 2097152,
                "collections": 0,
                "external": 0,
                "name": "new",
                "time": 0.0,
                "type": "HeapSpace",
                "used": 21600,
                "vmName": "Scavenger"
            },
            "old": {
                "avgCollectionPeriodMillis": 0.0,
                "capacity": 2445312,
                "collections": 0,
                "external": 0,
                "name": "old",
                "time": 0.0,
                "type": "HeapSpace",
                "used": 2035584,
                "vmName": "PageSpace"
            }
        },
        "_originNumber": "135770883",
        "_tagCounters": {
            "counters": [
                0,
                0,
                33,
                0,
                25,
                10,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                5,
                0
            ],
            "names": [
                "Idle",
                "LoadWait",
                "VM",
                "CompileOptimized",
                "CompileUnoptimized",
                "CompileClass",
                "CompileTopLevel",
                "CompileScanner",
                "CompileParseFunction",
                "CompileParseRegExp",
                "CompileFlowGraphBuilder",
                "Dart",
                "GCNewSpace",
                "GCOldSpace",
                "Embedder",
                "Runtime",
                "Native"
            ]
        },
        "breakpoints": [],
        "error": {
            "_vmType": "UnhandledException",
            "class": {
                "fixedId": true,
                "id": "classes/31",
                "name": "UnhandledException",
                "type": "@Class"
            },
            "exception": {
                "_vmType": "String",
                "class": {
                    "_vmName": "_OneByteString@915557746",
                    "fixedId": true,
                    "id": "classes/67",
                    "name": "_OneByteString",
                    "type": "@Class"
                },
                "id": "objects/1",
                "kind": "String",
                "length": 5,
                "type": "@Instance",
                "valueAsString": "oh no"
            },
            "id": "objects/0",
            "kind": "UnhandledException",
            "message": "Unhandled exception:\noh no\n#0      main.<main_async_body> (file:///Users/johnmccutchan/b.dart:2:3)\n#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)\n#2      _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#3      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#4      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)\n#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)\n",
            "size": 32,
            "stacktrace": {
                "_vmType": "Stacktrace",
                "class": {
                    "_vmName": "_StackTrace@915557746",
                    "fixedId": true,
                    "id": "classes/58",
                    "name": "_StackTrace",
                    "type": "@Class"
                },
                "id": "objects/2",
                "kind": "StackTrace",
                "type": "@Instance",
                "valueAsString": "#0      main.<main_async_body> (file:///Users/johnmccutchan/b.dart:2:3)\n#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)\n#2      _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#3      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#4      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)\n#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)\n"
            },
            "type": "Error"
        },
        "exceptionPauseMode": "None",
        "fixedId": true,
        "id": "isolates/135770883",
        "libraries": [
            {
                "fixedId": true,
                "id": "libraries/0",
                "name": "dart.core",
                "type": "@Library",
                "uri": "dart:core"
            },
            {
                "fixedId": true,
                "id": "libraries/1",
                "name": "dart.isolate",
                "type": "@Library",
                "uri": "dart:isolate"
            },
            {
                "fixedId": true,
                "id": "libraries/2",
                "name": "dart.mirrors",
                "type": "@Library",
                "uri": "dart:mirrors"
            },
            {
                "fixedId": true,
                "id": "libraries/3",
                "name": "dart.collection",
                "type": "@Library",
                "uri": "dart:collection"
            },
            {
                "fixedId": true,
                "id": "libraries/4",
                "name": "dart.developer",
                "type": "@Library",
                "uri": "dart:developer"
            },
            {
                "fixedId": true,
                "id": "libraries/5",
                "name": "dart.nativewrappers",
                "type": "@Library",
                "uri": "dart:nativewrappers"
            },
            {
                "fixedId": true,
                "id": "libraries/6",
                "name": "dart.typed_data",
                "type": "@Library",
                "uri": "dart:typed_data"
            },
            {
                "fixedId": true,
                "id": "libraries/7",
                "name": "dart.async",
                "type": "@Library",
                "uri": "dart:async"
            },
            {
                "fixedId": true,
                "id": "libraries/8",
                "name": "dart.convert",
                "type": "@Library",
                "uri": "dart:convert"
            },
            {
                "_vmName": "dart._internal@521182500",
                "fixedId": true,
                "id": "libraries/9",
                "name": "dart._internal",
                "type": "@Library",
                "uri": "dart:_internal"
            },
            {
                "fixedId": true,
                "id": "libraries/10",
                "name": "dart.math",
                "type": "@Library",
                "uri": "dart:math"
            },
            {
                "fixedId": true,
                "id": "libraries/11",
                "name": "dart.profiler",
                "type": "@Library",
                "uri": "dart:profiler"
            },
            {
                "_vmName": "dart._vmservice@72520438",
                "fixedId": true,
                "id": "libraries/12",
                "name": "dart._vmservice",
                "type": "@Library",
                "uri": "dart:_vmservice"
            },
            {
                "fixedId": true,
                "id": "libraries/13",
                "name": "builtin",
                "type": "@Library",
                "uri": "dart:_builtin"
            },
            {
                "fixedId": true,
                "id": "libraries/14",
                "name": "dart.io",
                "type": "@Library",
                "uri": "dart:io"
            },
            {
                "fixedId": true,
                "id": "libraries/15",
                "name": "",
                "type": "@Library",
                "uri": "file:///Users/johnmccutchan/b.dart"
            }
        ],
        "livePorts": 0,
        "name": "b.dart$main",
        "number": "135770883",
        "pauseEvent": {
            "isolate": {
                "fixedId": true,
                "id": "isolates/135770883",
                "name": "b.dart$main",
                "number": "135770883",
                "type": "@Isolate"
            },
            "kind": "PauseExit",
            "timestamp": 1461193435081,
            "type": "Event"
        },
        "pauseOnExit": true,
        "rootLib": {
            "fixedId": true,
            "id": "libraries/15",
            "name": "",
            "type": "@Library",
            "uri": "file:///Users/johnmccutchan/b.dart"
        },
        "runnable": true,
        "startTime": 1461193434892,
        "type": "Isolate"
    }
}
```

**Comment by johnmccutchan** [comment]
@mit-mit How is this bug blocking google3 rolls?

**Comment by floitschG** [comment]
From what I understood, the code coverage tool is affected by this, and we can't roll without coverage working.

**Comment by kevmoo** [comment]
@floitschG @mit-mit It's a bit more complicated than than.

pkg/coverage uses pkg/vm_service_client

This bug affects some aspects of vm_service_client – unclear if it affects coverage.

pkg/coverage has to be upgraded to support the API changes, either way

**Comment by johnmccutchan** [comment]
@kevmoo What makes you think that this bug might be affecting coverage? What data has lead you to that conclusion?

**Comment by kevmoo** [comment]
@johnmccutchan as I said, the only indication is that vm_service_client is crashing on tests.

Sorry - I could have been more clear. Initially I thought it was likely the case – now it's just plausible (along with a fix to pkg/coverage that MUST happen)

**Comment by nex3** [comment]
@johnmccutchan Please run the `vm_service_client` test to verify the fix, rather than a custom script.

**Comment by johnmccutchan** [comment]
@nex3 Please create a reproducible that doesn't depend on `vm_service_client` or `test`.

**Comment by kevmoo** [comment]
Until we *know* this is blocking 1.16, I'm removing the milestone.

We still believe this is a valid bug, so it should be open – @johnmccutchan just wants more info

**Comment by johnmccutchan** [comment]
FYI, we have [three](https://github.com/dart-lang/sdk/blob/master/runtime/observatory/tests/service/get_isolate_after_async_error_test.dart) [unit](https://github.com/dart-lang/sdk/blob/master/runtime/observatory/tests/service/get_isolate_after_language_error_test.dart) [tests](https://github.com/dart-lang/sdk/blob/master/runtime/observatory/tests/service/get_isolate_after_sync_error_test.dart) that verify the error is present after three different kinds of errors. These tests all pass.

**Comment by iposva-google** [comment]
Assigned to @nex3 to create a reduced test case even if this is not blocking 1.16.

**Comment by nex3** [comment]
@johnmccutchan The difference is that my script doesn't mark `main()` as async; all your unit tests have the throw in an asynchronous context. The following program consistently fails to have an error field on 9c5e6fa304d1b6ec9fecab5b60f86a6ef1713684:

```dart
main() {
  throw "oh no";
}
```

**Comment by johnmccutchan** [comment]
@nex3 We have a unit test that covers the synchronous case. It passes. Here is a raw test.

Script:

```dart
main() {
  throw "oh no";
}
```

I run it as follows:

```
$ ./out/DebugX64/dart --enable-vm-service --pause-isolates-on-exit script.dart
```

I grab the isolate like so:

```
$ curl localhost:8181/getIsolate?isolateId=isolates/root|python -mjson.tool
```

I get the following:

```
{
    "id": "",
    "jsonrpc": "2.0",
    "result": {
        "_debuggerSettings": {
            "_exceptions": "none"
        },
        "_heaps": {
            "new": {
                "avgCollectionPeriodMillis": 0.0,
                "capacity": 2097152,
                "collections": 0,
                "external": 0,
                "name": "new",
                "time": 0.0,
                "type": "HeapSpace",
                "used": 20512,
                "vmName": "Scavenger"
            },
            "old": {
                "avgCollectionPeriodMillis": 0.0,
                "capacity": 2183168,
                "collections": 0,
                "external": 0,
                "name": "old",
                "time": 0.0,
                "type": "HeapSpace",
                "used": 1832608,
                "vmName": "PageSpace"
            }
        },
        "_originNumber": "684083943",
        "_tagCounters": {
            "counters": [
                0,
                0,
                62,
                0,
                47,
                18,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                7,
                0
            ],
            "names": [
                "Idle",
                "LoadWait",
                "VM",
                "CompileOptimized",
                "CompileUnoptimized",
                "CompileClass",
                "CompileTopLevel",
                "CompileScanner",
                "CompileParseFunction",
                "CompileParseRegExp",
                "CompileFlowGraphBuilder",
                "Dart",
                "GCNewSpace",
                "GCOldSpace",
                "Embedder",
                "Runtime",
                "Native"
            ]
        },
        "breakpoints": [],
        "error": {
            "_vmType": "UnhandledException",
            "class": {
                "fixedId": true,
                "id": "classes/31",
                "name": "UnhandledException",
                "type": "@Class"
            },
            "exception": {
                "_vmType": "String",
                "class": {
                    "_vmName": "_OneByteString@915557746",
                    "fixedId": true,
                    "id": "classes/67",
                    "name": "_OneByteString",
                    "type": "@Class"
                },
                "id": "objects/1",
                "kind": "String",
                "length": 5,
                "type": "@Instance",
                "valueAsString": "oh no"
            },
            "id": "objects/0",
            "kind": "UnhandledException",
            "message": "Unhandled exception:\noh no\n#0      main (file:///usr/local/google/home/johnmccutchan/b.dart:2:3)\n#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)\n#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n",
            "size": 32,
            "stacktrace": {
                "_vmType": "Stacktrace",
                "class": {
                    "_vmName": "_StackTrace@915557746",
                    "fixedId": true,
                    "id": "classes/58",
                    "name": "_StackTrace",
                    "type": "@Class"
                },
                "id": "objects/2",
                "kind": "StackTrace",
                "type": "@Instance",
                "valueAsString": "#0      main (file:///usr/local/google/home/johnmccutchan/b.dart:2:3)\n#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)\n#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n"
            },
            "type": "Error"
        },
        "exceptionPauseMode": "None",
        "fixedId": true,
        "id": "isolates/684083943",
        "isReloading": false,
        "libraries": [
            {
                "fixedId": true,
                "id": "libraries/0",
                "name": "dart.core",
                "type": "@Library",
                "uri": "dart:core"
            },
            {
                "fixedId": true,
                "id": "libraries/1",
                "name": "dart.isolate",
                "type": "@Library",
                "uri": "dart:isolate"
            },
            {
                "fixedId": true,
                "id": "libraries/2",
                "name": "dart.mirrors",
                "type": "@Library",
                "uri": "dart:mirrors"
            },
            {
                "fixedId": true,
                "id": "libraries/3",
                "name": "dart.collection",
                "type": "@Library",
                "uri": "dart:collection"
            },
            {
                "fixedId": true,
                "id": "libraries/4",
                "name": "dart.developer",
                "type": "@Library",
                "uri": "dart:developer"
            },
            {
                "fixedId": true,
                "id": "libraries/5",
                "name": "dart.nativewrappers",
                "type": "@Library",
                "uri": "dart:nativewrappers"
            },
            {
                "fixedId": true,
                "id": "libraries/6",
                "name": "dart.typed_data",
                "type": "@Library",
                "uri": "dart:typed_data"
            },
            {
                "fixedId": true,
                "id": "libraries/7",
                "name": "dart.async",
                "type": "@Library",
                "uri": "dart:async"
            },
            {
                "fixedId": true,
                "id": "libraries/8",
                "name": "dart.convert",
                "type": "@Library",
                "uri": "dart:convert"
            },
            {
                "_vmName": "dart._internal@521182500",
                "fixedId": true,
                "id": "libraries/9",
                "name": "dart._internal",
                "type": "@Library",
                "uri": "dart:_internal"
            },
            {
                "fixedId": true,
                "id": "libraries/10",
                "name": "dart.math",
                "type": "@Library",
                "uri": "dart:math"
            },
            {
                "fixedId": true,
                "id": "libraries/11",
                "name": "dart.profiler",
                "type": "@Library",
                "uri": "dart:profiler"
            },
            {
                "_vmName": "dart._vmservice@72520438",
                "fixedId": true,
                "id": "libraries/12",
                "name": "dart._vmservice",
                "type": "@Library",
                "uri": "dart:_vmservice"
            },
            {
                "fixedId": true,
                "id": "libraries/13",
                "name": "builtin",
                "type": "@Library",
                "uri": "dart:_builtin"
            },
            {
                "fixedId": true,
                "id": "libraries/14",
                "name": "dart.io",
                "type": "@Library",
                "uri": "dart:io"
            },
            {
                "fixedId": true,
                "id": "libraries/15",
                "name": "",
                "type": "@Library",
                "uri": "file:///usr/local/google/home/johnmccutchan/b.dart"
            }
        ],
        "livePorts": 0,
        "name": "b.dart$main",
        "number": "684083943",
        "pauseEvent": {
            "isolate": {
                "fixedId": true,
                "id": "isolates/684083943",
                "name": "b.dart$main",
                "number": "684083943",
                "type": "@Isolate"
            },
            "kind": "PauseExit",
            "timestamp": 1461356693575,
            "type": "Event"
        },
        "pauseOnExit": true,
        "rootLib": {
            "fixedId": true,
            "id": "libraries/15",
            "name": "",
            "type": "@Library",
            "uri": "file:///usr/local/google/home/johnmccutchan/b.dart"
        },
        "runnable": true,
        "startTime": 1461356693265,
        "type": "Isolate"
    }
}
```

**Comment by nex3** [comment]
It looks like the difference is that I'm invoking `dart --observe` and you're invoking `dart --enable-vm-service --pause-isolates-on-exit`. If you use `--observe`, the error is not included, whereas if you use `--enable-vm-service --pause-isolates-on-exit`, it is.

**Comment by johnmccutchan** [comment]
@nex3 `--observe` is not a flag that should be used by tools or tests. It is a flag purely for **user** convenience. 

`--observe` implies `--pause-isolates-on-exit --pause-isolates-on-unhandled-exceptions --warn-on-pause-with-no-debugger --enable-vm-service`.

The important flag here is: `--pause-isolates-on-unhandled-exceptions`. Which stops the isolate before the sticky error is set.

**Comment by nex3** [comment]
> `--observe` is not a flag that should be used by tools or tests. It is a flag purely for **user** convenience. 

Where is this documented?

> The important flag here is: `--pause-isolates-on-unhandled-exceptions`. Which stops the isolate before the sticky error is set.

Okay, then this is the bug. The error should be set (and it was as recently as Dart 1.14.0).

**Comment by johnmccutchan** [comment]
The flag `--pause-isolates-on-unhandled-exception` did not exist in Dart 1.14. The behaviour of programs run with `--observe` has changed. Stop re-opening this bug.
