### ISSUE TITLE
crash with constants + named-args + deferred imports

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#26406]
Here is an example:

``` sh
> dart2js a.dart
```

where:

``` dart
// a.dart
import 'b.dart' deferred as b; // unused, but triggers the issue with constants

class A {
  final int x;

  const A(bool foo)
    : x = foo ? 1 : 0;
}

main() => const A(true);
```

``` dart
// b.dart is empty
```

produces:

```
The compiler crashed: Unsupported operation: PositionalArgumentReference.evaluate
#0      PositionalArgumentReference.evaluate (package:compiler/src/constants/expressions.dart:1186:5)
#1      ConditionalConstantExpression.evaluate (package:compiler/src/constants/expressions.dart:1131:19)
#2      ConstantCompilerBase.evaluate.<anonymous closure> (package:compiler/src/compile_time_constants.dart:169:23)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#4      ConstantCompilerBase.evaluate (package:compiler/src/compile_time_constants.dart:168:22)
#5      JavaScriptConstantCompiler.getConstantValue (package:compiler/src/js_backend/constant_handler_javascript.dart:252:5)
#6      DeferredLoadTask._collectAllElementsAndConstantsResolvedFrom.collectDependencies.<anonymous closure> (package:compiler/src/deferred_load.dart:344:39)
#7      Maplet.forEach (package:compiler/src/util/maplet.dart:205:15)
#8      TreeElementMapping.forEachConstantNode (package:compiler/src/resolution/tree_elements.dart:363:18)
#9      DeferredLoadTask._collectAllElementsAndConstantsResolvedFrom.collectDependencies (package:compiler/src/deferred_load.dart:340:14)
#10     DeferredLoadTask._collectAllElementsAndConstantsResolvedFrom (package:compiler/src/deferred_load.dart:395:26)
#11     DeferredLoadTask._mapDependencies (package:compiler/src/deferred_load.dart:483:7)
#12     DeferredLoadTask._mapDependencies (package:compiler/src/deferred_load.dart:497:9)
#13     DeferredLoadTask.onResolutionComplete.<anonymous closure> (package:compiler/src/deferred_load.dart:628:7)
#14     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:1560:15)
#15     CompilerTask.measureElement (package:compiler/src/common/tasks.dart:186:20)
#16     DeferredLoadTask.onResolutionComplete (package:compiler/src/deferred_load.dart:626:5)
#17     Compiler.compileLoadedLibraries.<anonymous closure> (package:compiler/src/compiler.dart:881:26)
#18     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:200:34)
#19     Compiler.compileLoadedLibraries (package:compiler/src/compiler.dart:811:16)
#20     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:721:7)
#21     _RootZone.runUnary (dart:async/zone.dart:1137)
#22     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:553)
#23     _Future._propagateToListeners (dart:async/future_impl.dart:639)
#24     _Future._completeWithValue (dart:async/future_impl.dart:426)
#25     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:481)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

You get a similar error when using named arguments instead of positional arguments.

**Comment by sigmundch** [comment]
The issue was introduced at this commit b361d8c, when we start evaluating constants eagerly as soon as we retrieve the value.

For now, I'll try to fix this by removing the extra `evaluate` in `constant_handler_javascript`, and allowing null results in the deferred task. 

@johnniwinther - some questions for you:
* In the future, would it make sense to change the deferred task to compute its dependencies using constant expressions instead of constant values?
* In `backend.dart` we also check that the constant value is not null, not sure if we also need to revert the change there or not, so far the tests I've done don't seem to trigger that case.

**Comment by sigmundch** [comment]
CL with a temporary fix is here: https://codereview.chromium.org/1950243002/

I was worried something else might hit the changes in backend and the type inferrer, so I have included those in the fix for now.

**Comment by sigmundch** [comment]
It appears that the original change also has an effect in increasing the total number of deferred libraries we generate, so we should pay close attention to that when revisiting this code.

**Comment by sigmundch** [comment]
(obsolete, since this only applied to the old FE)
