### ISSUE TITLE
Implement profiling, coverage, and other Observatory support for DBC

### ISSUE THREAD

**Issue by chinmaygarde** [dart-lang/sdk#26405]
Steps to Reproduce:
Evaluating any expression marks the expression as pending in the Observatory UI and crashes the VM. The stack trace is attached:

Stack Trace:

```
#0  0x0000000101808618 in dart::Object::IsNull() const [inlined] at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../dart/runtime/vm/object.h:286
#1  0x0000000101808618 in dart::SourceReport::PrintCallSitesData(dart::JSONObject*, dart::Function const&, dart::Code const&) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../dart/runtime/vm/source_report.cc:149
#2  0x00000001018091f8 in dart::SourceReport::VisitFunction(dart::JSONArray*, dart::Function const&) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../dart/runtime/vm/source_report.cc:374
#3  0x00000001018094d4 in dart::SourceReport::VisitLibrary(dart::JSONArray*, dart::Library const&) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../dart/runtime/vm/source_report.cc:402
#4  0x000000010180996c in dart::SourceReport::PrintJSON(dart::JSONStream*, dart::Script const&, dart::TokenPosition, dart::TokenPosition) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../dart/runtime/vm/source_report.cc:441
#5  0x00000001017f0e28 in dart::GetSourceReport(dart::Thread*, dart::JSONStream*) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../dart/runtime/vm/service.cc:2369
#6  0x00000001017ea878 in dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../dart/runtime/vm/service.cc:843
#7  0x000000010167d4b8 in dart::IsolateMessageHandler::HandleMessage(dart::Message*) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../dart/runtime/vm/isolate.cc:498
#8  0x000000010169c390 in dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../dart/runtime/vm/message_handler.cc:206
#9  0x000000010169c47c in dart::MessageHandler::HandleNextMessage() at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../dart/runtime/vm/message_handler.cc:257
#10 0x00000001014e53c4 in ::Dart_HandleMessage() at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../dart/runtime/vm/dart_api_impl.cc:1663
#11 0x00000001013af61c in blink::DartMessageHandler::OnHandleMessage(blink::DartState*) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../sky/engine/tonic/dart_message_handler.cc:85
#12 0x00000001013af4c8 in blink::DartMessageHandler::HandleMessage(base::WeakPtr<blink::DartState>) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../sky/engine/tonic/dart_message_handler.cc:118
#13 0x00000001013b0080 in base::internal::RunnableAdapter<void (*)(base::WeakPtr<blink::DartState>)>::Run(base::WeakPtr<blink::DartState> const&) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/bind_internal.h:157
#14 0x00000001013affe8 in base::internal::InvokeHelper<false, void, base::internal::RunnableAdapter<void (*)(base::WeakPtr<blink::DartState>)>, base::internal::TypeList<base::WeakPtr<blink::DartState> const&> >::MakeItSo(base::internal::RunnableAdapter<void (*)(base::WeakPtr<blink::DartState>)>, base::WeakPtr<blink::DartState> const&) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/bind_internal.h:293
#15 0x00000001013affac in base::internal::Invoker<base::IndexSequence<0ul>, base::internal::BindState<base::internal::RunnableAdapter<void (*)(base::WeakPtr<blink::DartState>)>, void (base::WeakPtr<blink::DartState>), base::internal::TypeList<base::WeakPtr<blink::DartState> > >, base::internal::TypeList<base::internal::UnwrapTraits<base::WeakPtr<blink::DartState> > >, base::internal::InvokeHelper<false, void, base::internal::RunnableAdapter<void (*)(base::WeakPtr<blink::DartState>)>, base::internal::TypeList<base::WeakPtr<blink::DartState> const&> >, void ()>::Run(base::internal::BindStateBase*) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/bind_internal.h:343
#16 0x0000000100147f6c in base::Callback<void ()>::Run() const at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/callback.h:396
#17 0x00000001002d089c in base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask const&) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/debug/task_annotator.cc:49
#18 0x00000001001b6480 in base::MessageLoop::RunTask(base::PendingTask const&) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/message_loop/message_loop.cc:481
#19 0x00000001001b6658 in base::MessageLoop::DeferOrRunPendingTask(base::PendingTask const&) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/message_loop/message_loop.cc:490
#20 0x00000001001b6b00 in base::MessageLoop::DoWork() at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/message_loop/message_loop.cc:602
#21 0x0000000100c36bc0 in mojo::common::MessagePumpMojo::DoRunLoop(mojo::common::MessagePumpMojo::RunState*, base::MessagePump::Delegate*) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../mojo/message_pump/message_pump_mojo.cc:162
#22 0x0000000100c36af0 in mojo::common::MessagePumpMojo::Run(base::MessagePump::Delegate*) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../mojo/message_pump/message_pump_mojo.cc:126
#23 0x00000001001b5ecc in base::MessageLoop::RunHandler() at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/message_loop/message_loop.cc:445
#24 0x00000001001ec798 in base::RunLoop::Run() at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/run_loop.cc:55
#25 0x00000001001b534c in base::MessageLoop::Run() at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/message_loop/message_loop.cc:288
#26 0x00000001002739ec in base::Thread::Run(base::MessageLoop*) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/threading/thread.cc:198
#27 0x0000000100273e24 in base::Thread::ThreadMain() at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/threading/thread.cc:248
#28 0x000000010025d344 in base::(anonymous namespace)::ThreadFunc(void*) at /Volumes/Mojo/sky_engine/src/out/ios_Debug/../../base/threading/platform_thread_posix.cc:74
#29 0x000000018129bb28 in _pthread_body ()
#30 0x000000018129ba8c in _pthread_start ()
#31 0x0000000181299028 in thread_start ()
```

**Comment by zanderso** [comment]
Yah, sorry, we're still working on bringing this up. /cc @mraleph

**Comment by zanderso** [comment]
https://codereview.chromium.org/1971543002/

This should fix the crash, but be aware that the info displayed by the Observatory won't be correct until the implementation is complete.

**Comment by rmacnak-google** [comment]
634a62c9df04314edd8b4e526fa3cde73aaf8d93

**Comment by rmacnak-google** [comment]
3dba3a77c1360ce447a5fb8ecf1f48348067f5de

**Comment by rmacnak-google** [comment]
f6a320b973be0e5f622e6f4886a7afc0b08eedda Implement coverage by adding missing count increments to unoptimized static and instance calls.
