### ISSUE TITLE
Unhandled exception: AnalysisException

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26426]
I'm getting an unhandled exception while trying to make the core libraries strong-mode clean.

The way I work:

```
mv out/ReleaseX64/dart-sdk/lib/math out/ReleaseX64/dart-sdk/lib/math_copy
ln -s $PWD/sdk/lib/math out/ReleaseX64/dart-sdk/lib/math
```

And then run the analyzer on the sdk sources.
Until today this made it possible to work on the core libraries without needing to rebuild. It seems this workflow has been broken recently.

```
$ out/ReleaseX64/dart-sdk/bin/dart --package-root=$PWD/out/ReleaseX64/packages /mnt/ssd/floitsch/code/dart/sdk/pkg/analyzer_cli/bin/analyzer.dart --no-hints --strong --warnings out/ReleaseX64/dart-sdk/lib/math/math.dart
Analyzing [out/ReleaseX64/dart-sdk/lib/math/math.dart]...
Unhandled exception:
AnalysisException: Cannot compute DART_ERRORS for /mnt/ssd/floitsch/code/dart/sdk/out/ReleaseX64/dart-sdk/lib/math/math.dart
Caused by Mismatch in DeclarationResolver while resolving /mnt/ssd/floitsch/code/dart/sdk/out/ReleaseX64/dart-sdk/lib/math/point.dart
Found element with name "factor" at 1765, but expected offset of 1774
Path to root: DeclaredSimpleIdentifier, SimpleFormalParameterImpl, FormalParameterListImpl, MethodDeclarationImpl, ClassDeclarationImpl, CompilationUnitImpl
#0      RecursiveAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3433:5)
#1      DeclarationResolver._findWithNameAndOffset (package:analyzer/src/generated/resolver.dart:2697:9)
#2      DeclarationResolver._findIdentifier (package:analyzer/src/generated/resolver.dart:2670:23)
#3      DeclarationResolver._getElementForParameter (package:analyzer/src/generated/resolver.dart:2741:12)
#4      DeclarationResolver.visitSimpleFormalParameter (package:analyzer/src/generated/resolver.dart:2543:34)
#5      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:8862:15)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7663:20)
#7      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4706:17)
#8      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:1587:10)
#9      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4702:15)
#10     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7170:18)
#11     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1737:10)
#12     DeclarationResolver.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:2517:35)
#13     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7162:15)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7663:20)
#15     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1896:13)
#16     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:1425:10)
#17     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2234:34)
#18     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1836:15)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7663:20)
#20     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2427:21)
#21     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449:10)
#22     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2420:15)
#23     DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2209:10)
#24     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:998:33)
#25     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329:9)
#26     AnalysisTask.perform (package:analyzer/task/model.dart:229:7)
#27     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276:10)
#28     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:18)
#29     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:667:14)
#30     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:615:12)
#31     AnalyzerImpl.prepareErrors.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:130:17)
#32     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#33     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:128:30)
#34     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:164:5)
#35     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:123:12)
#36     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:575:34)
#37     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:216:30)
#38     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:159:14)
#39     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#40     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:158:27)
#41     Driver.start (package:analyzer_cli/src/driver.dart:139:32)
#42     main (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/analyzer_cli/bin/analyzer.dart:11:11)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:671:7)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:615:12)
#2      AnalyzerImpl.prepareErrors.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:130:17)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:128:30)
#5      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:164:5)
#6      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:123:12)
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:575:34)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:216:30)
#9      Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:159:14)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#11     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:158:27)
#12     Driver.start (package:analyzer_cli/src/driver.dart:139:32)
#13     main (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/analyzer_cli/bin/analyzer.dart:11:11)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
I believe that what's happening here is that analyzer has failed to flush an element model that was invalidated by some change, and that it subsequently attempted to use that element model when re-creating a resolved AST. We've seen similar exceptions before, but have not yet been able to track down (a) whether that conjecture is accurate or (b) where it's happening.

You should be able to continue working if you force server to re-analyze everything.

**Comment by floitschG** [comment]
How does one force the command-line tool to reanalyze everything?

**Comment by bwilkerson** [comment]
You can't because it always reanalyzes everything; I just didn't notice you were using the command-line tool. I'm guessing that summaries have broken this.

**Comment by scheglov** [comment]
Yes, I think this happens because we started to use SDK summaries in command-line analyzer.

But it seems that we should not do this when we are analyzing SDK itself. Actually it works, but only if SDK source correspond to summaries, which is not the case when you change SDK source and want to see it they can be analyzed. So, we should disable it for SDK sources.

**Comment by lukechurch** [comment]
I'm not sure if it's related, but containing ```Caused by Mismatch in DirectiveResolver``` and the like are now happening a lot. They also on user code as well as the SDK.

We've saw a few thousand instances of this problem via instrumentation for 1.16.0-dev.5.0.

**Comment by scheglov** [comment]
Well, in case of modifying SDK and using summaries this exception is expected.

In other cases - it is not.
So, I guess it happens at the same position, but by a different reason.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1963023002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/e7b51f7bd127757c031b79435cbf15a5009cf923
