### ISSUE TITLE
Observatory crashes with exception when viewing a function

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#26434]
Tested with revision b1f2c2cd3ac27f20fde5dcc3051154154d305c30

I tried running the test program from issue #26428 with --observe

```
out/ReleaseX64/dart --observe str.dart
```

I clicked on CPU profile and selected the top function there.

```
Unexpected exception:

NullError: method not found: 'cq' on null

Stacktrace:

TypeError: Cannot read property 'cq' of null
    at dart.AB (http://127.0.0.1:8181/index.html.polymer.bootstrap.dart.js:29404:19)
    at http://127.0.0.1:8181/index.html.polymer.bootstrap.dart.js:28535:9
    at a1x.a (http://127.0.0.1:8181/index.html.polymer.bootstrap.dart.js:11028:72)
    at a1x.dart.a1x.$2 (http://127.0.0.1:8181/index.html.polymer.bootstrap.dart.js:11275:24)
    at a0x.dart.a0x.$1 (http://127.0.0.1:8181/index.html.polymer.bootstrap.dart.js:11271:31)
    at dart.Ac (http://127.0.0.1:8181/index.html.polymer.bootstrap.dart.js:11192:24)
    at Yu.dart.Yu.fi (http://127.0.0.1:8181/index.html.polymer.bootstrap.dart.js:12442:12)
    at Zi.dart.Zi.$0 (http://127.0.0.1:8181/index.html.polymer.bootstrap.dart.js:11622:12)
    at dart.K.t.fm (http://127.0.0.1:8181/index.html.polymer.bootstrap.dart.js:11585:43)
    at K.dart.K.oz (http://127.0.0.1:8181/index.html.polymer.bootstrap.dart.js:11538:3)
    at Zb.dart.Zb.$0 (http://127.0.0.1:8181/index.html.polymer.bootstrap.dart.js:11616:23)

[Connect to a different VM]
```

**Comment by johnmccutchan** [comment]
Updated the title because this has nothing to do with the CPU profile.

Also, this was fixed yesterday afternoon.
