### ISSUE TITLE
Flaky crashes in safepoint check on ARM64

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#26476]
```
Program terminated with signal SIGBUS, Bus error.
#0  CompareAndSwapWord (new_value=0, old_value=1, ptr=0x7f940011a4) at runtime/vm/atomic_linux.h:53
53    return __sync_val_compare_and_swap(ptr, old_value, new_value);
(gdb) bt
#0  CompareAndSwapWord (new_value=0, old_value=1, ptr=0x7f940011a4) at runtime/vm/atomic_linux.h:53
#1  dart::MonitorLocker::WaitWithSafepointCheck (this=0x7fa90409b8, thread=0x7f940009d0, millis=<optimized out>)
    at runtime/vm/lockers.cc:41
#2  0x0000000000889a44 in dart::SafepointHandler::SafepointThreads (this=this@entry=0x17df5930, 
    T=T@entry=0x7f940009d0) at runtime/vm/safepoint.cc:67
#3  0x000000000088a3b4 in dart::SafepointOperationScope::SafepointOperationScope (this=<optimized out>, 
    T=0x7f940009d0) at runtime/vm/safepoint.cc:23
#4  0x00000000005ec168 in dart::CompileParsedFunctionHelper::Compile (this=this@entry=0x7fa9041498, 
    pipeline=pipeline@entry=0x7fa9042040) at runtime/vm/compiler.cc:1148
#5  0x00000000005ee1c0 in dart::CompileFunctionHelper (pipeline=0x7fa9042040, function=..., 
    optimized=optimized@entry=true, osr_id=osr_id@entry=-1) at runtime/vm/compiler.cc:1287
#6  0x00000000005efa70 in dart::Compiler::CompileOptimizedFunction (thread=thread@entry=0x7f940009d0, function=..., 
    osr_id=osr_id@entry=-1) at runtime/vm/compiler.cc:1464
#7  0x00000000005efde4 in dart::BackgroundCompiler::Run (this=0x7fa4022670) at runtime/vm/compiler.cc:1861
#8  0x00000000008f3fc8 in dart::ThreadPool::Worker::Loop (this=this@entry=0x7fa0021640)
    at runtime/vm/thread_pool.cc:388
#9  0x00000000008f455c in dart::ThreadPool::Worker::Main (args=548145337920) at runtime/vm/thread_pool.cc:446
#10 0x00000000007dbca0 in dart::ThreadStart (data_ptr=<optimized out>) at runtime/vm/os_thread_linux.cc:123
#11 0x0000007fa9fc0e34 in start_thread () from /lib/aarch64-linux-gnu/libpthread.so.0
#12 0x0000007fa9d497c0 in clone () from /lib/aarch64-linux-gnu/libc.so.6
```

**Comment by rmacnak-google** [comment]
@a-siva

**Comment by mraleph** [comment]
I assume that we are not seeing this anymore. If we still see them please reopen and we should investigate.
