### ISSUE TITLE
Flaky failure with service/gc_test

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#26490]
@johnmccutchan @turnidge 

https://build.chromium.org/p/client.dart/builders/vm-win-debug-x64-be/builds/977/steps/vm%20tests/logs/stdio

```
FAILED: none-vm debug_x64 service/gc_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching build\DebugX64\dart.exe --trace-service --trace-service-verbose --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=build/DebugX64/packages/ --enable-vm-service:0 E:\b\build\slave\vm-win-debug-x64-be\build\sdk\runtime\observatory\tests\service\gc_test.dart
[+109ms] Isolate gc_test.dart$main-479031267 deferring OOB interrupts
[+109ms] Isolate gc_test.dart$main-479031267 restoring OOB interrupts
[+156ms] Isolate gc_test.dart$main-479031267 deferring OOB interrupts
[+156ms] Isolate vm-service deferring OOB interrupts
[+171ms] Isolate vm-service restoring OOB interrupts
[+171ms] Isolate gc_test.dart$main-479031267 restoring OOB interrupts
[+171ms] Isolate gc_test.dart$main-479031267 deferring OOB interrupts
[+187ms] Isolate gc_test.dart$main-479031267 restoring OOB interrupts
[+187ms] Isolate vm-service deferring OOB interrupts
[+202ms] Isolate vm-service restoring OOB interrupts
vm-service: Booting dart:vmservice library.
vm-service: Registering running isolates.
vm-service: Isolate gc_test.dart$main-479031267 479031267 registered.
[+265ms] Isolate vm-service deferring OOB interrupts
[+280ms] Isolate vm-service restoring OOB interrupts
[+296ms] Isolate vm-service deferring OOB interrupts
[+312ms] Isolate vm-service restoring OOB interrupts
[+312ms] Isolate vm-service deferring OOB interrupts
[+312ms] Isolate vm-service restoring OOB interrupts
[+358ms] Isolate gc_test.dart$main-479031267 deferring OOB interrupts
[+358ms] Isolate gc_test.dart$main-479031267 restoring OOB interrupts
[+358ms] Isolate gc_test.dart$main-479031267 deferring OOB interrupts
[+358ms] Isolate gc_test.dart$main-479031267 restoring OOB interrupts
[+358ms] Isolate vm-service deferring OOB interrupts
[+358ms] Isolate vm-service restoring OOB interrupts
[+405ms] Isolate vm-service deferring OOB interrupts
[+405ms] Isolate vm-service restoring OOB interrupts
[+468ms] Isolate vm-service deferring OOB interrupts
[+468ms] Isolate vm-service restoring OOB interrupts
Observatory listening on http://127.0.0.1:57327
[+655ms] Isolate vm-service deferring OOB interrupts
[+655ms] Isolate vm-service restoring OOB interrupts
[+858ms] Isolate vm-service deferring OOB interrupts
[+858ms] Isolate vm-service restoring OOB interrupts
[+858ms] Isolate vm-service deferring OOB interrupts
[+858ms] Isolate vm-service restoring OOB interrupts
[+1092ms] Isolate vm-service deferring OOB interrupts
[+1638ms] Isolate vm-service restoring OOB interrupts
[+1638ms] Isolate vm-service deferring OOB interrupts
[+1638ms] Isolate vm-service restoring OOB interrupts
[+2293ms] Isolate vm-service deferring OOB interrupts
[+2293ms] Isolate vm-service restoring OOB interrupts
[+2589ms] Isolate vm-service deferring OOB interrupts
[+2589ms] Isolate vm-service restoring OOB interrupts
[+2589ms] Isolate vm-service deferring OOB interrupts
[+2605ms] Isolate vm-service restoring OOB interrupts
[+3463ms] Isolate gc_test.dart$main-479031267 deferring OOB interrupts
[+3463ms] Isolate gc_test.dart$main-479031267 restoring OOB interrupts
[+3525ms] Isolate gc_test.dart$main-479031267 deferring OOB interrupts
[+3525ms] Isolate gc_test.dart$main-479031267 restoring OOB interrupts
[+3541ms] Isolate gc_test.dart$main-479031267 deferring OOB interrupts
[+3572ms] Isolate gc_test.dart$main-479031267 restoring OOB interrupts
[+3650ms] Isolate gc_test.dart$main-479031267 deferring OOB interrupts
[+3650ms] Isolate gc_test.dart$main-479031267 restoring OOB interrupts
** Signaled to run test queries on 57327

Loading VM...
[+4227ms] Isolate vm-service deferring OOB interrupts
[+4227ms] Isolate vm-service restoring OOB interrupts
[+4383ms] Isolate gc_test.dart$main-479031267 deferring OOB interrupts
[+4383ms] Isolate gc_test.dart$main-479031267 restoring OOB interrupts
[+4711ms] Isolate vm-service deferring OOB interrupts
[+4711ms] Isolate vm-service restoring OOB interrupts
[+4758ms] Isolate vm-service deferring OOB interrupts
[+4758ms] Isolate vm-service restoring OOB interrupts
[+4773ms] Isolate vm-service deferring OOB interrupts
[+4773ms] Isolate vm-service restoring OOB interrupts
[+4960ms] Isolate gc_test.dart$main-479031267 deferring OOB interrupts
[+4960ms] Isolate gc_test.dart$main-479031267 restoring OOB interrupts
vm-service: starting stream 'VM'
vm-service: starting stream 'Isolate'
vm-service: starting stream 'Debug'
vm-service: starting stream '_Graph'
[+5522ms] Isolate vm-service processing service request getVM
[+5522ms] Isolate vm-service processed service request getVM (0us)
Done loading VM
[+5959ms] Isolate gc_test.dart$main-479031267 processing service request getIsolate
[+5974ms] Isolate gc_test.dart$main-479031267 processed service request getIsolate (15600us)
Running gc_test.dart [1/1]
vm-service: starting stream 'GC'
vm\service_event.cc:35: error: expected: isolate == NULL || !ServiceIsolate::IsServiceIsolateDescendant(isolate_)
** Killing script


stderr:
Unhandled exception:
Testee exited with 3
#0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:242:11)
#1      _RootZone.runUnary (dart:async/zone.dart:1204)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: set DART_CONFIGURATION=DebugX64 & build\DebugX64\dart.exe --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=build/DebugX64/packages/ E:\b\build\slave\vm-win-debug-x64-be\build\sdk\runtime\observatory\tests\service\gc_test.dart
Took 0:00:08.205758

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t120 service/gc_test



===
=== 1 test failed
===

```

**Comment by fsc8000** [comment]
Not seen in a while. Closing as stale.
