### ISSUE TITLE
Need to support JS methods with names that are not valid Dart keywords

### ISSUE THREAD

**Issue by ioancristea** [dart-lang/sdk#26531]
Hi
**Describe the issue you're seeing**
I try to make a Dart version of the firebase 3 js. I need to create an external 'catch' method.

**Does it happen in Dartium or when compiled to JavaScript?**
When compiled to JavaScript

* Dart SDK version: *use `dart --version`*
Dart VM version: 1.16.0 (Tue Apr 26 14:18:21 2016) on "linux_x64"
* pkg/js version: *look at `pubspec.lock`*
js: ^0.6.0

Failing code:
```dart
@JS('Promise')
class Promise {
  external Promise(resolver);

  external all(List<Promise> values);
  external reject(error);
  external resolve(value);
  external catch([onReject]);
  external then([onResolve, onReject]);
}
```

Also i recive that error
```
FIREBASE WARNING: Exception was thrown by user callback. NoSuchMethodError: method not found: 'call'
Receiver: Closure 'AppComponent_closure'
Arguments: [null, null]
    at dart.wrapException (http://localhost:8080/main.dart.js:2818:17)
    at AppComponent_closure.dart.Object.noSuchMethod$1 (http://localhost:8080/main.dart.js:21524:17)
    at J.noSuchMethod$1$ (http://localhost:8080/main.dart.js:26288:39)
    at dart.Primitives_functionNoSuchMethod (http://localhost:8080/main.dart.js:2723:16)
    at dart.Primitives__genericApplyFunctionWithPositionalArguments (http://localhost:8080/main.dart.js:2758:20)
    at dart.Primitives_applyFunctionWithPositionalArguments (http://localhost:8080/main.dart.js:2744:16)
    at dart._callDartFunctionFast (http://localhost:8080/main.dart.js:23496:16)
    at http://localhost:8080/main.dart.js:23488:18
    at https://www.gstatic.com/firebasejs/3.0.2/firebase.js:346:688
    at https://www.gstatic.com/firebasejs/3.0.2/firebase.js:541:48
```
when i call this (the error is in allowInterop, without this is working fine)

```
firebase.database().ref('manufacturers').set(new firebase.TestSet(name: 'wefwef'), allowInterop(([error]) {
      window.console.debug('ss');
    }));
```

**Comment by DisDis** [comment]
possible duplicate https://github.com/dart-lang/sdk/issues/25785

**Comment by jacob314** [comment]
for method names that are not valid dart names you have to prefix them with 
JS$
so 
JS$catch
That will work in dart2js but support still needs to be added for dartium but will be straightforward to add.

**Comment by jacob314** [comment]
This is the same issue as #26718
