### ISSUE TITLE
full parser can't handle annotations?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#26579]
This code produces the following check-mode error in our full parser:

``` dart
abstract class A {
  @deprecated foo();
}
```

Here is an example test to reproduce the issue:

``` dart
import 'package:compiler/src/diagnostics/diagnostic_listener.dart';
import 'package:compiler/src/elements/modelx.dart';
import 'package:compiler/src/io/source_file.dart';
import 'package:compiler/src/options.dart';
import 'package:compiler/src/parser/element_listener.dart';
import 'package:compiler/src/parser/node_listener.dart';
import 'package:compiler/src/parser/parser.dart';
import 'package:compiler/src/scanner/string_scanner.dart';
import 'package:compiler/src/script.dart';

void main() {
  String sourceCode = '''abstract class A {
     @deprecated foo();
  }''';
  Uri uri = Uri.parse('source:foo');
  var library = new LibraryElementX(new Script(
      uri, uri, new StringSourceFile.fromName('<string>', sourceCode)));
  var listener = new NodeListener(new ScannerOptions(),
      new MockDiagnosticListener(), library.entryCompilationUnit);
  var tokens = new StringScanner.fromString(sourceCode).tokenize();
  new Parser(listener, new _ParserOptions()).parseUnit(tokens);
}

class MockDiagnosticListener implements DiagnosticReporter {
  dynamic noSuchMethod(Invocation invocation) => null;
}

class _ParserOptions extends ParserOptions {
  bool get enableGenericMethodSyntax => false;
}
```

When run in checked mode, you can see the following broken invariant:

```
Unhandled exception:
type 'Identifier' is not a subtype of type 'Modifiers' of 'modifiers' where
  Identifier is from package:compiler/src/tree/nodes.dart
  Modifiers is from package:compiler/src/tree/nodes.dart

#0      NodeListener.endClassDeclaration (package:compiler/src/parser/node_listener.dart:38:27)
#1      Parser.parseClass (package:compiler/src/parser/parser.dart:740:14)
#2      Parser.parseClassOrNamedMixinApplication (package:compiler/src/parser/parser.dart:700:14)
#3      Parser.parseTopLevelDeclaration (package:compiler/src/parser/parser.dart:128:14)
#4      Parser.parseUnit (package:compiler/src/parser/parser.dart:115:15)
#5      main (file:///usr/local/google/home/sigmund/dart/git_all/sdk/test.dart:21:46)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

Likely we do pop correctly the token for the annotation

/cc @bwilkerson

**Comment by sigmundch** [comment]
I fixed this a few weeks ago, closing.
