### ISSUE TITLE
Isolate.spawn() crashes on invalid arguments

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#26588]
The description of constructor `Isolate.spawn()` reads:

> Creates and spawns an isolate that shares the same code as the current isolate.
> 
> The argument entryPoint specifies the entry point of the spawned isolate. It must be a top-level function or a static method that takes one argument - that is, one-parameter functions that can be compile-time constant function values. It is not allowed to pass the value of function expressions or an instance method extracted from an object.
>...
>Returns a future that will complete with an Isolate instance if the spawning succeeded. It will complete with an error otherwise.

However, the constructor crashes if entryPoint is a top level function that takes 2 arguments.
Here is code sample:
```dart
import "dart:isolate";

entryPointWith2Args(message1, message2) {
  print("message1: $message1 message2: $message2");
}

main() {
    Isolate.spawn(entryPointWith2Args, 'hello');
}
```
Output:
>dart-sdk\bin\dart.exe  test1.dart
>E:\b\build\slave\dart-sdk-windows-stable\build\sdk\runtime\vm/object.h:5259: error: Handle check >failed: saw UnwindError expected Instance

Sometimes it does not crash. Just execute it again.
In checked mode the test throws expected type error:

> dart-sdk\bin\dart.exe  --checked  test1.dart
> Unhandled exception:
> type '(dynamic, dynamic) => dynamic' is not a subtype of type '(dynamic) => void' of 'entryPoint'
> #0      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:307)
> #1      main (file:///D:/dev/dart/col9/LibTest/isolate/Isolate/test1.dart:8:13)
> #2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
> #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
> 

Dart VM version: 1.16.0 (Tue Apr 26 07:06:15 2016) on "windows_x64"

**Comment by lrhn** [comment]
Seems the VM implementation isn't validating the input function type in production mode. 
We can either add the test at the dart patch-file level or do it in C code (the latter likely being more efficient since we can't check for being "static or top-level" in Dart code anyway).

**Comment by zanderso** [comment]
The UnwindError making it into a handle check is probably due to wrong or missing error propagation code.

@turnidge

**Comment by alsemenov** [comment]
If the call to `Isolate.spawn()` is surrounded by try-catch it does not crash, however behaves incorrectly:
```dart
import "dart:isolate";

entryPointWith2Args(message1, message2) {
  print("message1: $message1 message2: $message2");
}

main() {
  try {
    Isolate.spawn(entryPointWith2Args, 'hello').then(
        (v) {
          print("Isolate.spawn(entryPointWith2Args,'hello') is expected to fail");
        },
        onError: (e) {
          print("returned Future has completed with error: $e");
        }
    );
  } catch (e) {
    print("call to Isolate.spawn(...) throws error: $e");
  }
}
```
Output:
>dart-sdk\bin\dart.exe  test.dart
>Isolate.spawn(entryPointWith2Args,'hello') is expected to fail 

Expected output:
>dart-sdk\bin\dart.exe  test.dart
>returned Future has completed with error: Invalid argument(s): Isolate.spawn expects to be passed a static or top-level function

**Comment by fsc8000** [comment]
Failed twice recently:

https://build.chromium.org/p/client.dart/builders/vm-linux-debug-simmips-be/builds/1677/steps/vm%20tests/logs/stdio

https://build.chromium.org/p/client.dart/builders/vm-linux-debug-ia32-be/builds/8500/steps/vm%20tests/logs/stdio

**Comment by fsc8000** [comment]
This seems to happen during shutdown. I managed to create this stack trace:
```
(gdb) thread apply all bt

Thread 8 (Thread 0xf73b3b40 (LWP 11537)):
#0  0xf7702440 in __kernel_vsyscall ()
#1  0xf74a3a36 in epoll_wait () from /lib/i386-linux-gnu/libc.so.6
#2  0x081cd6ab in dart::bin::EventHandlerImplementation::Poll (args=args@entry=179929232) at runtime/bin/eventhandler_linux.cc:399
#3  0x081c89ed in dart::bin::ThreadStart (data_ptr=0xab8e018) at runtime/bin/thread_linux.cc:91
#4  0xf76c6f72 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#5  0xf74a2f8e in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 7 (Thread 0xf71b1b40 (LWP 11542)):
#0  0xf7702440 in __kernel_vsyscall ()
#1  0xf76cb0ed in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
#2  0x083b37e2 in dart::Monitor::WaitMicros (this=0xab9a000, micros=5000000) at runtime/vm/os_thread_linux.cc:423
#3  0x083b3870 in dart::Monitor::Wait (this=this@entry=0xab9a000, millis=<optimized out>) at runtime/vm/os_thread_linux.cc:402
#4  0x0847ed9f in Wait (this=<synthetic pointer>, millis=<optimized out>) at runtime/vm/lockers.h:169
#5  dart::ThreadPool::Worker::Loop (this=this@entry=0xab9a000) at runtime/vm/thread_pool.cc:420
#6  0x0847ee85 in dart::ThreadPool::Worker::Main (args=args@entry=179937280) at runtime/vm/thread_pool.cc:464
#7  0x083b2b52 in dart::ThreadStart (data_ptr=0xab90740) at runtime/vm/os_thread_linux.cc:123
#8  0xf76c6f72 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#9  0xf74a2f8e in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 6 (Thread 0xf6cb6b40 (LWP 11573)):
#0  0xf7702440 in __kernel_vsyscall ()
#1  0xf76cad0b in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
#2  0x083b3707 in dart::Monitor::WaitMicros (this=0xab8aa50, micros=0) at runtime/vm/os_thread_linux.cc:418
#3  0x083b3870 in dart::Monitor::Wait (this=this@entry=0xab8aa50, millis=<optimized out>) at runtime/vm/os_thread_linux.cc:402
#4  0x0822e960 in Wait (this=<synthetic pointer>, millis=0) at runtime/vm/lockers.h:169
#5  dart::BackgroundCompiler::Run (this=0xab972e0) at runtime/vm/compiler.cc:2029
#6  0x0847ed4e in dart::ThreadPool::Worker::Loop (this=this@entry=0xab9a150) at runtime/vm/thread_pool.cc:407
#7  0x0847ee85 in dart::ThreadPool::Worker::Main (args=args@entry=179937616) at runtime/vm/thread_pool.cc:464
#8  0x083b2b52 in dart::ThreadStart (data_ptr=0xab907c0) at runtime/vm/os_thread_linux.cc:123
#9  0xf76c6f72 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#10 0xf74a2f8e in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 5 (Thread 0xf6ab5b40 (LWP 11598)):
#0  0xf7702440 in __kernel_vsyscall ()
#1  0xf76cb0ed in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
#2  0x083b37e2 in dart::Monitor::WaitMicros (this=0xab9a0e0, micros=5000000) at runtime/vm/os_thread_linux.cc:423
#3  0x083b3870 in dart::Monitor::Wait (this=this@entry=0xab9a0e0, millis=<optimized out>) at runtime/vm/os_thread_linux.cc:402
#4  0x0847ed9f in Wait (this=<synthetic pointer>, millis=<optimized out>) at runtime/vm/lockers.h:169
#5  dart::ThreadPool::Worker::Loop (this=this@entry=0xab9a0e0) at runtime/vm/thread_pool.cc:420
#6  0x0847ee85 in dart::ThreadPool::Worker::Main (args=args@entry=179937504) at runtime/vm/thread_pool.cc:464
#7  0x083b2b52 in dart::ThreadStart (data_ptr=0xab908b0) at runtime/vm/os_thread_linux.cc:123
#8  0xf76c6f72 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#9  0xf74a2f8e in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 4 (Thread 0xf6a34b40 (LWP 11615)):
#0  0xf7702440 in __kernel_vsyscall ()
#1  0xf73e5687 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf73e8ab3 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x083b22eb in dart::OS::Abort () at runtime/vm/os_linux.cc:416
#4  0x081c9d9a in dart::DynamicAssertionHelper::Fail (this=this@entry=0xf6a32960, format=format@entry=0x8868c88 "Handle check failed: saw %s expected %s") at runtime/platform/assert.cc:43
#5  0x084b3c55 in dart::Instance::CheckedHandle (zone=0xf6a32a08, raw_ptr=raw_ptr@entry=0xf67feebd) at runtime/vm/object.h:5627
#6  0x084b9cd9 in CheckedHandle (raw_ptr=0xf67feebd) at runtime/vm/object.h:5627
#7  DRT_HelperInlineCacheMissHandlerOneArg (isolate=<optimized out>, thread=<optimized out>, zone=<optimized out>, arguments=...) at runtime/vm/code_generator.cc:911
#8  dart::DRT_InlineCacheMissHandlerOneArg (arguments=...) at runtime/vm/code_generator.cc:910
#9  0xf7232267 in ?? ()
#10 0xf7232e78 in ?? ()
#11 0xf66ed21c in ?? ()
#12 0xf7232564 in ?? ()
#13 0x08247b24 in dart::DartEntry::InvokeFunction (function=..., arguments=..., arguments_descriptor=...) at runtime/vm/dart_entry.cc:132
#14 0x082488b1 in dart::DartEntry::InvokeFunction (function=..., arguments=...) at runtime/vm/dart_entry.cc:29
#15 0x08248f4d in dart::DartEntry::InvokeNoSuchMethod (receiver=..., target_name=..., arguments=..., arguments_descriptor=...) at runtime/vm/dart_entry.cc:269
#16 0x084beb44 in DRT_HelperInvokeClosureNoSuchMethod (isolate=<optimized out>, thread=<optimized out>, zone=<optimized out>, arguments=...) at runtime/vm/code_generator.cc:1605
#17 dart::DRT_InvokeClosureNoSuchMethod (arguments=...) at runtime/vm/code_generator.cc:1590
#18 0xf7232267 in ?? ()
#19 0xf7233a84 in ?? ()
#20 0xf66dc3ff in ?? ()
#21 0xf66ec8c8 in ?? ()
#22 0xf66dc3ff in ?? ()
#23 0xf66ec69c in ?? ()
#24 0xf7232564 in ?? ()
#25 0x08247b24 in dart::DartEntry::InvokeFunction (function=..., arguments=..., arguments_descriptor=...) at runtime/vm/dart_entry.cc:132
#26 0x082488b1 in dart::DartEntry::InvokeFunction (function=..., arguments=...) at runtime/vm/dart_entry.cc:29
#27 0x0824b35f in dart::DartLibraryCalls::HandleMessage (handler=..., message=...) at runtime/vm/dart_entry.cc:577
#28 0x0832a30a in dart::IsolateMessageHandler::HandleMessage (this=0xb60ab40, message=0xab97ac0) at runtime/vm/isolate.cc:575
#29 0x08347d6f in dart::MessageHandler::HandleMessages (this=this@entry=0xb60ab40, ml=ml@entry=0xf6a34220, allow_normal_messages=true, allow_multiple_normal_messages=allow_multiple_normal_messages@entry=true) at runtime/vm/message_handler.cc:213
#30 0x08348242 in dart::MessageHandler::TaskCallback (this=0xb60ab40) at runtime/vm/message_handler.cc:368
#31 0x0847ed4e in dart::ThreadPool::Worker::Loop (this=this@entry=0xab9a1c0) at runtime/vm/thread_pool.cc:407
#32 0x0847ee85 in dart::ThreadPool::Worker::Main (args=args@entry=179937728) at runtime/vm/thread_pool.cc:464
#33 0x083b2b52 in dart::ThreadStart (data_ptr=0xab90980) at runtime/vm/os_thread_linux.cc:123
#34 0xf76c6f72 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#35 0xf74a2f8e in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 3 (Thread 0xf69b3b40 (LWP 11617)):
#0  0xf7702440 in __kernel_vsyscall ()
#1  0xf76cb0ed in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
#2  0x083b37e2 in dart::Monitor::WaitMicros (this=0xab9a380, micros=5000000) at runtime/vm/os_thread_linux.cc:423
#3  0x083b3870 in dart::Monitor::Wait (this=this@entry=0xab9a380, millis=<optimized out>) at runtime/vm/os_thread_linux.cc:402
#4  0x0847ed9f in Wait (this=<synthetic pointer>, millis=<optimized out>) at runtime/vm/lockers.h:169
#5  dart::ThreadPool::Worker::Loop (this=this@entry=0xab9a380) at runtime/vm/thread_pool.cc:420
#6  0x0847ee85 in dart::ThreadPool::Worker::Main (args=args@entry=179938176) at runtime/vm/thread_pool.cc:464
#7  0x083b2b52 in dart::ThreadStart (data_ptr=0xab90950) at runtime/vm/os_thread_linux.cc:123
#8  0xf76c6f72 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#9  0xf74a2f8e in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 2 (Thread 0xf6655b40 (LWP 11647)):
#0  0xf7702440 in __kernel_vsyscall ()
#1  0xf76cb0ed in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
#2  0x083b37e2 in dart::Monitor::WaitMicros (this=0xab9a310, micros=5000000) at runtime/vm/os_thread_linux.cc:423
#3  0x083b3870 in dart::Monitor::Wait (this=this@entry=0xab9a310, millis=<optimized out>) at runtime/vm/os_thread_linux.cc:402
#4  0x0847ed9f in Wait (this=<synthetic pointer>, millis=<optimized out>) at runtime/vm/lockers.h:169
#5  dart::ThreadPool::Worker::Loop (this=this@entry=0xab9a310) at runtime/vm/thread_pool.cc:420
#6  0x0847ee85 in dart::ThreadPool::Worker::Main (args=args@entry=179938064) at runtime/vm/thread_pool.cc:464
#7  0x083b2b52 in dart::ThreadStart (data_ptr=0xab909c0) at runtime/vm/os_thread_linux.cc:123
#8  0xf76c6f72 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#9  0xf74a2f8e in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 1 (Thread 0xf73b5700 (LWP 11500)):
#0  0xf7702440 in __kernel_vsyscall ()
#1  0xf76cad0b in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
#2  0x083b3707 in dart::Monitor::WaitMicros (this=0xab8a0a0, micros=0) at runtime/vm/os_thread_linux.cc:418
#3  0x083b3870 in dart::Monitor::Wait (this=this@entry=0xab8a0a0, millis=<optimized out>) at runtime/vm/os_thread_linux.cc:402
#4  0x0823b15a in Wait (this=<synthetic pointer>, millis=0) at runtime/vm/lockers.h:169
#5  WaitForApplicationIsolateShutdown () at runtime/vm/dart.cc:327
#6  dart::Dart::Cleanup () at runtime/vm/dart.cc:404
#7  0x081a2275 in dart::Dart_Cleanup () at runtime/vm/dart_api_impl.cc:1198
#8  0x0818c13a in dart::bin::ErrorExit (exit_code=exit_code@entry=255, format=format@entry=0x88a16ed "%s\n") at runtime/bin/main.cc:149
#9  0x08195c1a in dart::bin::RunMainIsolate (script_name=script_name@entry=0xffa520c1 "/usr/local/google/home/fschneider/dartgit/sdk/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t04.dart", dart_options=dart_options@entry=0xffa51370) at runtime/bin/main.cc:1624
#10 0x0818d44a in dart::bin::main (argc=argc@entry=4, argv=argv@entry=0xffa51494) at runtime/bin/main.cc:1858
#11 0x0818d61b in main (argc=4, argv=0xffa51494) at runtime/bin/main.cc:1897
```
