### ISSUE TITLE
Dart2js --analyze-only --allow-native-extensions crashes on native static function.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#26586]
Reproduction:

```
import 'dart-ext:foo';
class A {
  static void foo() native "foo";
}
main() =>  A.foo();
```

```
$ dart2js --analyze-only --allow-native-extensions main.dart
```

```
Internal Error: The compiler crashed when compiling this element.
  static void foo() native "foo";
  ^^^^^^^^^^^^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: The null object does not have a getter 'length'.

NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      NativeData.getNativeTagsOfClassRaw (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/js_backend/native_data.dart:152:47)
#3      NativeEnqueuerBase._setNativeNameForStaticMethod (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/native/enqueue.dart:443:30)
#4      NativeEnqueuerBase.handleMethodAnnotations (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/native/enqueue.dart:415:9)
#5      NativeEnqueuerBase.registerElement.<anonymous closure> (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/native/enqueue.dart:380:9)
#6      CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:1560:15)
#7      NativeEnqueuerBase.registerElement (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/native/enqueue.dart:375:14)
#8      ResolutionEnqueuer.internalAddToWorkList (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/enqueue.dart:813:20)
#9      Enqueuer.addToWorkList (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/enqueue.dart:137:9)
#10     Enqueuer.registerStaticUseInternal (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/enqueue.dart:620:7)
#11     TreeShakingEnqueuerStrategy.processStaticUse (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/enqueue.dart:1018:14)
#12     Enqueuer.registerStaticUse (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/enqueue.dart:591:14)
#13     _EnqueuerImpactVisitor.visitStaticUse (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/enqueue.dart:1039:14)
#14     Setlet.forEach (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/util/setlet.dart:222:39)
#15     TransformedWorldImpact.apply (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/universe/world_impact.dart:148:16)
#16     JavaScriptImpactStrategy.visitImpact (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/js_backend/backend.dart:3042:16)
#17     Enqueuer.applyImpact (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/enqueue.dart:155:10)
#18     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:957:27)
#19     CompilerTask.measureSubtask (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/common/tasks.dart:200:34)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:956:30)
#21     CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:1560:15)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:954:20)
#23     QueueFilter.processWorkItem (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/enqueue.dart:983:6)
#24     Enqueuer.forEach (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/enqueue.dart:674:16)
#25     Compiler.emptyQueue.<anonymous closure> (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:953:15)
#26     CompilerTask.measureSubtask (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/common/tasks.dart:200:34)
#27     Compiler.emptyQueue (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:952:16)
#28     Compiler.processQueue.<anonymous closure> (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:989:9)
#29     CompilerTask.measureSubtask (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/common/tasks.dart:200:34)
#30     Compiler.processQueue (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:966:16)
#31     Compiler.compileLoadedLibraries.<anonymous closure> (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:848:9)
#32     CompilerTask.measureSubtask (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/common/tasks.dart:200:34)
#33     Compiler.compileLoadedLibraries (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:811:16)
#34     Compiler.runInternal.<anonymous closure> (file:///usr/local/google/home/sigurdm/projects/git-repo/sdk/pkg/compiler/lib/src/compiler.dart:721:7)
#35     _RootZone.runUnary (dart:async/zone.dart:1204)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#37     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#38     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#39     _Future._completeWithValue (dart:async/future_impl.dart:477)
#40     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by MrBirb** [comment]
@mit-mit Oh mit mit

**Comment by mit-mit** [comment]
Closing as wont-fix based on https://github.com/dart-lang/sdk/issues/45451
