### ISSUE TITLE
Uppercase Headers in dart:io

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/sdk#26594]
It seems that dart:io can't parse uppercase headers. A very popular UPnP SDK uses uppercase headers for embedded devices, which causes problems.

```
[services@mars UPNP]$ curl 'http://10.0.1.143:49153/rootdesc1.xml' -v
*   Trying 10.0.1.143...
* Connected to 10.0.1.143 (10.0.1.143) port 49153 (#0)
> GET /rootdesc1.xml HTTP/1.1
> Host: 10.0.1.143:49153
> User-Agent: curl/7.48.0
> Accept: */*
>
< HTTP/1.1 200 OK
< CONTENT-LENGTH: 1101
< CONTENT-TYPE: text/xml
< DATE: Mon, 26 Jun 2006 08:59:57 GMT
< LAST-MODIFIED: Wed, 24 May 2006 01:35:32 GMT
< SERVER: Linux/3.18.0, UPnP/1.0, Portable SDK for UPnP devices/1.6.19
< X-User-Agent: redsonic
< CONNECTION: close
<
<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>AXIS A8004-VE - ACCC8E30E2BF</friendlyName>
<manufacturer>AXIS</manufacturer>
<manufacturerURL>http://www.axis.com/</manufacturerURL>
<modelDescription>AXIS A8004-VE Network Video Door Station</modelDescription>
<modelName>AXIS A8004-VE</modelName>
<modelNumber>A8004-VE</modelNumber>
<modelURL>http://www.axis.com/</modelURL>
<serialNumber>ACCC8E30E2BF</serialNumber>
<UDN>uuid:Upnp-BasicDevice-1_0-ACCC8E30E2BF</UDN>
<serviceList>
<service>
<serviceType>urn:axis-com:service:BasicService:1</serviceType>
<serviceId>urn:axis-com:serviceId:BasicServiceId</serviceId>
<controlURL>/upnp/control/BasicServiceId</controlURL>
<eventSubURL>/upnp/event/BasicServiceId</eventSubURL>
<SCPDURL>/scpd_basic.xml</SCPDURL>
</service>
</serviceList>
<presentationURL>http://10.0.1.143:80/</presentationURL>
</device>
<URLBase>http://10.0.1.143:49153/</URLBase>
</root>
* Closing connection 0
```

```
[FINE][DSA] Failed to fetch device: http://10.0.1.143:49153/rootdesc1.xml
[FINE][DSA] Failed to parse HTTP
[FINE][DSA] #0      IOClient.send.<send_async_body> (package:http/src/io_client.dart:78:7)
[FINE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[FINE][DSA] #2      _RootZone.runBinary (dart:async/zone.dart:1142)
[FINE][DSA] #3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:581)
[FINE][DSA] #4      _Future._propagateToListeners (dart:async/future_impl.dart:643)
[FINE][DSA] #5      _Future._completeError (dart:async/future_impl.dart:434)
[FINE][DSA] #6      Future.wait.handleError (dart:async/future.dart:280)
[FINE][DSA] #7      _RootZone.runBinary (dart:async/zone.dart:1142)
[FINE][DSA] #8      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:581)
[FINE][DSA] #9      _Future._propagateToListeners (dart:async/future_impl.dart:643)
[FINE][DSA] #10     _Future._completeError (dart:async/future_impl.dart:434)
[FINE][DSA] #11     _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:490)
[FINE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[FINE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[FINE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[FINE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by lrhn** [comment]
@sgjesse FYI

**Comment by sgjesse** [comment]
It is not the upper-case headers - they are handled, as the code below illustrates.

The `HttpException` with the message `Failed to parse HTTP` is thrown when the `dart:io`HTTP parser thinks that the HTTP does not adhere to the spec (e.g. if the byte directly after `HTTP`in the header is not  0x20). So there must be something else in the response from the UPnP server that `dart:io` does not like.

Could you try to get the exact binary response from the server (e.g. using `curl -O`)? If that is fed into the `socket.write` in the program below the same error should happen.
```
import 'dart:io';

main () async {
  var server = await ServerSocket.bind("127.0.0.1", 0);
  server.listen((socket) async {
    int port = server.port;
    socket.write("HTTP/1.1 200 OK\r\n"
                 "CONTENT-LENGTH: 21\r\n"
                 "CONTENT-TYPE: text/xml\r\n"
                 "DATE: Mon, 26 Jun 2006 08:59:57 GMT\r\n"
                 "LAST-MODIFIED: Wed, 24 May 2006 01:35:32 GMT\r\n"
                 "SERVER: Linux/3.18.0, UPnP/1.0, Portable SDK for UPnP devices/1.6.19\r\n"
                 "X-User-Agent: redsonic\r\n"
                 "CONNECTION: close\r\n"
                 "\r\n"
                 "<?xml version=\"1.0\"?>");
    var body = new StringBuffer();
    await for (var data in socket) {
      body.write(new String.fromCharCodes(data));
    }
    print("=== REQUEST RECEIVED ===");
    print(body.toString());
    print("=== END REQUEST RECEIVED ===");
    socket.close();
    server.close();
  });

  var client = new HttpClient();
  client.userAgent = null;
  var request = await client.get("127.0.0.1", server.port, "/");
  var response = await request.close();
  var body = new StringBuffer();
  await for (var data in response) {
    body.write(new String.fromCharCodes(data));
  }
  print("=== RESPONSE RECEIVED ===");
  print(response.headers);
  print(body.toString());
  print("=== END RESPONSE RECEIVED ===");
}
```

**Comment by kaendfinger** [comment]
This is no longer an issue, looks like it was weird behavior on the server-side.
