### ISSUE TITLE
Default exception handler truncates messages at U+0000 characters

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26624]
``` dart
void main() { String m = 'hello\x00world'; print('$m'); throw '$m'; }
```

->

```
hello^@world
Unhandled exception:
hello
#0      main (test.dart:1:57)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by rmacnak-google** [comment]
We'd have to change `const char* Dart_GetError(Dart_Handle handle)` to answer a length + buffer instead of a C string. Or add a new API function.
