### ISSUE TITLE
observatory doesn't stop on exception or breaks in main.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26661]
I'm unable to debug a small script (attached below).

```
$ dart --version
Dart VM version: 1.17.0-edge.4c64a8da973e5d6912e2ca30cb37e5c5799add97 (Fri Jun  3 18:19:18 2016) on "linux_x64"
```

I start the execution with 
```
$ dart --observe /tmp/t.dart
something else
vm-service: isolate 't.dart$main' has no debugger attached and is paused at exit.  Connect to Observatory at http://127.0.0.1:8181 to debug.
```

Then I open the observatory on the given address and open the debugger.
I set 'break-on-exception' to 'All', and restart the vm:

```
$ set break-on-exception All
Now pausing for exceptions: all
$ vm restart
Restarting VM...
The current isolate 354093311 't.dart$main' has exited
No current isolate
Isolate 77311778 't.dart$main' has been created
Switching to isolate 77311778 't.dart$main'
Isolate is running (type 'pause' to interrupt)
t.dart$main:stdout> something else
Paused at isolate exit (type 'continue' or [F7] to exit the isolate')

Isolate has exited due to an unhandled exception:
Unhandled exception:
No top-level getter 'developer' declared.

NoSuchMethodError: method not found: 'developer'
Receiver: top-level
Arguments: [...]
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:169)
#1      main.<anonymous closure> (file:///tmp/t.dart:21:7)
#2      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

Clearly, the vm didn't pause at the exception.
The 'break-on-exception' variable is still set to 'All':

```
$ set break-on-exception
break-on-exception = All
```

Just breaking in 'main' doesn't work either.
```
$ break main
Breakpoint 1 added at t.dart:18:5
$ vm restart
Restarting VM...
The current isolate 77311778 't.dart$main' has exited
No current isolate
Isolate 1023153903 't.dart$main' has been created
Switching to isolate 1023153903 't.dart$main'
Isolate is running (type 'pause' to interrupt)
t.dart$main:stdout> something else
Paused at isolate exit (type 'continue' or [F7] to exit the isolate')

Isolate has exited due to an unhandled exception:
Unhandled exception:
No top-level getter 'developer' declared.

NoSuchMethodError: method not found: 'developer'
Receiver: top-level
Arguments: [...]
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:169)
#1      main.<anonymous closure> (file:///tmp/t.dart:21:7)
#2      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Type 'set break-on-exception Unhandled' to pause the isolate when an unhandled exception occurs.
You can make this the default by running with --pause-isolates-on-unhandled-exceptions
```

Here is the example file I'm using.

``` dart
import 'dart:async';
import 'dart:developer';

class A {
  Timer timer;
  
  foo() {
    timer = new Timer(const Duration(milliseconds: 200), () {
      this.doSomethingElse();
    });
  }

  doSomethingElse() {
    print("something else");
  }
}

main() {
  var a = new A()..foo();
  new Timer(const Duration(milliseconds: 300), () {
      developer.inspect(a.timer);
      });
}
```

**Comment by johnmccutchan** [comment]
@turnidge

**Comment by floitschG** [comment]
Actually, the provided test case is way too big. I'm even stuck with a tiny hello-world example (see below).

```
$ cat /tmp/obs.dart
main() {
  print("hello world");
}
$ dart --observe /tmp/obs.dart
hello world
vm-service: isolate 'obs.dart$main' has no debugger attached and is paused at exit.  Connect to Observatory at http://127.0.0.1:8181 to debug.
```

In the debugger (at the given address):
```
$ b main
Breakpoint 1 added at obs.dart:1:5
$ vm restart
Restarting VM...
The current isolate 283984197 'obs.dart$main' has exited
No current isolate
Isolate 439955387 'obs.dart$main' has been created
Switching to isolate 439955387 'obs.dart$main'
obs.dart$main:stdout> hello world
Paused at isolate exit (type 'continue' or [F7] to exit the isolate')
Paused at isolate exit (type 'continue' or [F7] to exit the isolate')
```

As can be seen: the program did not break at `main`.

**Comment by turnidge** [comment]
Florian, the "vm restart" command restarts the whole main isolate.  I am wondering if you mean to be using "c" or "continue" to restart instead?

**Comment by floitschG** [comment]
"c" doesn't work for me. It just exits the program.

I want to restart the program from the beginning with my breakpoints in place. In 'gdb' I type 'start' (to which `vm restart` looked most similar) to start the program again from the beginning.

**Comment by johnmccutchan** [comment]
I'm pretty sure the issue is that by restarting the VM new isolates are recreated and breakpoints are attached to the old (killed) isolates. What we need is the following:

1) Before the VM restarts, remember all breakpoints in each isolate.
2) Restart the VM
3) Map the new isolates to the old isolates
4) Restore the breakpoints
5) Resume the isolate execution.

**Comment by turnidge** [comment]
All breakpoints are per-isolate in the service protocol right now and live and die with the isolate.  We could add in global breakpoints to Observatory but we don't have it on our roadmap currently.

**Comment by zoechi** [comment]
Looks similar #29433
