### ISSUE TITLE
Rare segfault during service isolate shutdown

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#26669]
Occured here: https://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-optcounter-threshold-be/builds/1117/steps/checked%20vm%20tests/logs/stdio

Repro:
```
    python tools/test.py -mrelease --write-debug-log --write-test-outcome-log --copy-coredumps --vm-options --optimization-counter-threshold=5 --exclude-suite pkg --checked -t60 co19/Language/Expressions/Property_Extraction/Anonymous_Constructor_Closurization/named_parameters_t01
```

```
(gdb) bt
#0  dart::SnapshotWriter::WriteMarkedObjectImpl (this=this@entry=0x7fffffffcc90, raw=raw@entry=0x7ffff53c3db9, tags=140737307753801, object_id=8, as_reference=true) at runtime/vm/snapshot.cc:2392
#1  0x00000000007e6641 in dart::SnapshotWriter::WriteObjectImpl (this=this@entry=0x7fffffffcc90, raw=raw@entry=0x7ffff53c3db9, as_reference=as_reference@entry=true) at runtime/vm/snapshot.cc:2382
#2  0x00000000007e6ab5 in WriteObjectImpl (as_reference=<optimized out>, raw=0x7ffff53c3db9, this=0x7fffffffcc90) at runtime/vm/snapshot.cc:2359
#3  dart::SnapshotWriter::ArrayWriteTo (this=this@entry=0x7fffffffcc90, object_id=object_id@entry=187, array_kind=array_kind@entry=64, tags=274878169088, length=length@entry=0x8, type_arguments=type_arguments@entry=0x7ffff7e8e021, data=data@entry=0x7ffff53c3da0, as_reference=as_reference@entry=false) at runtime/vm/snapshot.cc:2574
#4  0x00000000008742df in dart::RawArray::WriteTo (this=this@entry=0x7ffff53c3d89, writer=writer@entry=0x7fffffffcc90, object_id=187, kind=<optimized out>, as_reference=<optimized out>) at runtime/vm/raw_object_snapshot.cc:2933
#5  0x00000000007e6374 in dart::SnapshotWriter::WriteMarkedObjectImpl (this=this@entry=0x7fffffffcc90, raw=0x7ffff53c3d89, tags=<optimized out>, object_id=<optimized out>, as_reference=<optimized out>) at runtime/vm/snapshot.cc:2407
#6  0x00000000007e6641 in dart::SnapshotWriter::WriteObjectImpl (this=this@entry=0x7fffffffcc90, raw=<optimized out>, as_reference=as_reference@entry=false) at runtime/vm/snapshot.cc:2382
#7  0x00000000007e66f7 in dart::SnapshotWriter::WriteObjectImpl (this=this@entry=0x7fffffffcc90, raw=<optimized out>, as_reference=false) at runtime/vm/snapshot.cc:2383
#8  0x00000000007e744a in WriteObject (rawobj=<optimized out>, this=0x7fffffffcc90) at runtime/vm/snapshot.cc:1869
#9  dart::MessageWriter::WriteMessage (this=this@entry=0x7fffffffcc90, obj=...) at runtime/vm/snapshot.cc:2827
#10 0x00000000007da837 in dart::ServiceIsolate::SendIsolateShutdownMessage () at runtime/vm/service_isolate.cc:203
#11 0x000000000056b29c in dart::Dart_ShutdownIsolate () at runtime/vm/dart_api_impl.cc:1306
#12 0x000000000055636a in dart::bin::RunMainIsolate (script_name=script_name@entry=0x7fffffffe0d8 "/usr/local/google/home/fschneider/dartgit2/sdk/tests/co19/src/Language/Expressions/Property_Extraction/Anonymous_Constructor_Closurization/named_parameters_t01.dart", dart_options=dart_options@entry=0x7fffffffdae0) at runtime/bin/main.cc:1484
#13 0x000000000054fcfb in dart::bin::main (argc=7, argv=0x7fffffffdc38) at runtime/bin/main.cc:1705
#14 0x000000000054fea9 in main (argc=<optimized out>, argv=<optimized out>) at runtime/bin/main.cc:1746
```

**Comment by fsc8000** [comment]
Fixed via https://github.com/dart-lang/sdk/commit/82fac9b30bacf5ac7a8dcd523d6349d6a710ac51.
