### ISSUE TITLE
Error from the analysis server: Failed to handle completion domain request: {params: {file: F:\Users\user\dart\for_web\extended_peg\lib\src\extended_peg\parser_generator.dart, offset: 288}, method: completion.getSuggestions, id: 2611}

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#26685]
_From @mezoni on June 10, 2016 15:0_

The null object does not have a getter 'type'.
```
NoSuchMethodError: method not found: 'type'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _OpTypeAstVisitor.visitInstanceCreationExpression.<anonymous closure> (package:analysis_server/src/services/completion/dart/optype.dart:558)
#3      _Visitor._addSuggestion (package:analysis_server/src/services/completion/dart/local_constructor_contributor.dart:249)
#4      _Visitor.declaredClass (package:analysis_server/src/services/completion/dart/local_constructor_contributor.dart:202)
#5      LocalDeclarationVisitor.visitCompilationUnit.<anonymous closure> (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:125)
#6      Object&ListMixin.forEach (dart:collection/list.dart:63)
#7      LocalDeclarationVisitor.visitCompilationUnit (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:123)
#8      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2433)
#9      LocalDeclarationVisitor.visitNode (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:214)
#10     LocalDeclarationVisitor.visitClassDeclaration (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:118)
#11     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1841)
#12     LocalDeclarationVisitor.visitNode (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:214)
#13     LocalDeclarationVisitor.visitMethodDeclaration (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:209)
#14     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7181)
#15     LocalDeclarationVisitor.visitNode (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:214)
#16     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:1075)
#17     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:948)
#18     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1218)
#19     LocalDeclarationVisitor.visitNode (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:214)
#20     LocalDeclarationVisitor.visitBlock (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:99)
#21     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1274)
#22     LocalDeclarationVisitor.visitNode (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:214)
#23     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:1244)
#24     GeneralizingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:1314)
#25     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10828)
#26     LocalDeclarationVisitor.visitNode (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:214)
#27     GeneralizingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1310)
#28     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10771)
#29     LocalDeclarationVisitor.visitNode (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:214)
#30     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:920)
#31     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:1008)
#32     GeneralizingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1306)
#33     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10679)
#34     LocalDeclarationVisitor.visitNode (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:214)
#35     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:1045)
#36     GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:1118)
#37     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6144)
#38     LocalDeclarationVisitor.visit (package:analysis_server/src/services/completion/dart/local_declaration_visitor.dart:65)
#39     LocalConstructorContributor.computeSuggestions.<computeSuggestions_async_body> (package:analysis_server/src/services/completion/dart/local_constructor_contributor.dart:177)
#40     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#41     _rootRunUnary (dart:async/zone.dart:958)
#42     _CustomZone.runUnary (dart:async/zone.dart:837)
#43     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#44     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#45     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#46     _Future._complete (dart:async/future_impl.dart:467)
#47     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#48     DartCompletionRequestImpl.resolveContainingStatement.<resolveContainingStatement_async_body> (package:analysis_server/src/services/completion/dart/completion_manager.dart:251)
#49     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#50     _rootRun (dart:async/zone.dart:946)
#51     _CustomZone.run (dart:async/zone.dart:826)
#52     _CustomZone.runGuarded (dart:async/zone.dart:724)
#53     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#54     _rootRun (dart:async/zone.dart:950)
#55     _CustomZone.run (dart:async/zone.dart:826)
#56     _CustomZone.runGuarded (dart:async/zone.dart:724)
#57     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#58     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#59     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#60     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

_Copied from original issue: dart-atom/dartlang#1032_

**Comment by devoncarew** [comment]
_From @mezoni on June 10, 2016 15:7_

Good software but very buggy.
I already encounter a lot of problems and found some bugs (you know which).
At least one bug (or more) were found per a week (from a single person, me) in this software. 
Not very comfortable to use it.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2085563002/
