### ISSUE TITLE
Flaky test standalone/io/file_blocking_lock_test

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#26698]
This failed once one of the buildbots. Could the test result be timing-dependent? @zanderso 

https://build.chromium.org/p/client.dart/builders/vm-linux-release-ia32-asan-be/builds/4258/steps/vm%20tests/logs/stdio

```
FAILED: none-vm release_ia32 standalone/io/file_blocking_lock_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
Unhandled exception:
Expect.equals(expected: <true>, actual: <false>) fails.
#0      Expect._fail (package:expect/expect.dart:385:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      testLockWholeFile.<testLockWholeFile_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-ia32-asan-be/build/sdk/tests/standalone/io/file_blocking_lock_test.dart:97:10)
#3      _RootZone.runUnary (dart:async/zone.dart:1204)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#7      _Future._completeWithValue (dart:async/future_impl.dart:477)
#8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --ignore-unrecognized-flags --package-root=out/ReleaseIA32/packages/ /mnt/data/b/build/slave/vm-linux-release-ia32-asan-be/build/sdk/tests/standalone/io/file_blocking_lock_test.dart
Took 0:00:03.920823

Short reproduction command (experimental):
    python tools/test.py -mrelease -aia32 --write-debug-log --write-test-outcome-log --copy-coredumps --builder-tag asan -t240 --exclude-suite pkg standalone/io/file_blocking_lock_test
```

**Comment by fsc8000** [comment]
This is still timing out sometimes
