### ISSUE TITLE
analyzer crash

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26695]
```
Error from the analysis server: Task failed: StrongModeVerifyUnitTask for source /usr/local/google/home/ianh/dev/flutter/packages/flutter/lib/src/services/image_provider.dart
Unexpected exception while performing StrongModeVerifyUnitTask for source /usr/local/google/home/ianh/dev/flutter/packages/flutter/lib/src/services/image_provider.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1176)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1174)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:946)
#11     _CustomZone.run (dart:async/zone.dart:826)
#12     _CustomZone.runGuarded (dart:async/zone.dart:724)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#14     _rootRun (dart:async/zone.dart:950)
#15     _CustomZone.run (dart:async/zone.dart:826)
#16     _CustomZone.runGuarded (dart:async/zone.dart:724)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'isVoid'.

NoSuchMethodError: method not found: 'isVoid'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      CodeChecker._checkDowncast (package:analyzer/src/task/strong/checker.dart:664)
#3      CodeChecker.checkAssignment (package:analyzer/src/task/strong/checker.dart:146)
#4      CodeChecker.visitDefaultFormalParameter (package:analyzer/src/task/strong/checker.dart:290)
#5      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3384)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682)
#7      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4723)
#8      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:1587)
#9      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4719)
#10     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7189)
#11     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1737)
#12     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7181)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682)
#14     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1909)
#15     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:1425)
#16     CodeChecker.visitClassDeclaration (package:analyzer/src/task/strong/checker.dart:243)
#17     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1841)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682)
#19     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2440)
#20     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449)
#21     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2433)
#22     StrongModeVerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:5596)
#23     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#24     AnalysisTask.perform (package:analyzer/task/model.dart:229)
#25     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#26     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#27     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1176)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#29     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1174)
#30     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#31     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#32     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#33     _rootRun (dart:async/zone.dart:946)
#34     _CustomZone.run (dart:async/zone.dart:826)
#35     _CustomZone.runGuarded (dart:async/zone.dart:724)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#37     _rootRun (dart:async/zone.dart:950)
#38     _CustomZone.run (dart:async/zone.dart:826)
#39     _CustomZone.runGuarded (dart:async/zone.dart:724)
#40     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#41     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#42     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#43     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by Hixie** [comment]
I left it running and 220s later it gave me actual messages.

**Comment by Hixie** [comment]
This doing `flutter analyze --flutter-repo` on: https://github.com/Hixie/flutter/tree/images

**Comment by Hixie** [comment]
cc @devoncarew

**Comment by pq** [comment]
cc @leafpetersen, @jmesserly for what looks strong-mode related.

**Comment by jmesserly** [comment]
Seems like an assert tripped. Somehow we got a parameter with a null type:
```dart
// From CodeChecker
  @override
  void visitDefaultFormalParameter(DefaultFormalParameter node) {
    // Check that defaults have the proper subtype.
    var parameter = node.parameter;
    var parameterType = _elementType(parameter.element);
    assert(parameterType != null);
    var defaultValue = node.defaultValue;
    if (defaultValue != null) {
      checkAssignment(defaultValue, parameterType);
    }

    node.visitChildren(this);
  }
// The _elementType function for reference:
DartType _elementType(Element e) {
  if (e == null) {
    // Malformed code - just return dynamic.
    return DynamicTypeImpl.instance;
  }
  return (e as dynamic).type;
}
```
It's easy to add a ?? DynamicTypeImpl.instance, but that may just hide a problem somewhere else.

@bwilkerson should `element.type` for a ParameterElement be non-null always after resolution? It feels like it should be but I'm not 100% sure.

**Comment by Hixie** [comment]
There's almost certainly some horrendous code somewhere on that branch that's causing the analyzer to see code that you never imagined someone would write. I've been fixing things bit by bit by running the VM's compiler over the code and I've found numerous horrible cases of mismatched parens and so forth.

It might be valuable to fuzz-test the analyzer by having a script that randomly generates valid code paired with a script that randomly bit-twiddles the output before analyzing it.

**Comment by bwilkerson** [comment]
> ... should element.type for a ParameterElement be non-null always after resolution?

I think the answer is 'yes'. I was also looking at fixing this, and have not been able to reproduce it. Happy to let you look at it.

> It might be valuable to fuzz-test the analyzer ...

We actually do have a fuzz tester (thanks to Luke), but it doesn't get run regularly as it ought to.

**Comment by Hixie** [comment]
I narrowed it down. Run dartanalyzer on the following to crash:

```dart
class A { B({ this.test: 1.0 }); final double test; }
```

**Comment by jmesserly** [comment]
Nice repro @Hixie !

So it seems things get in a pretty bad state when the field is after the constructor & we don't hook up the type correctly. Investigating more to see why that's the case... my current guess is that FieldElement.type is null at the point we try and copy it into FieldFormalParameterElement.

**Comment by jmesserly** [comment]
Have a fix, about to send out. Since this is FIELD_INITIALIZER_OUTSIDE_CONSTRUCTOR error anyway, I don't think we need to worry about finding the correct field type, so `dynamic` there should work.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2061073002/

**Comment by bwilkerson** [comment]
Out of curiosity, what kind of parameter does analyzer produce? Does it recover by throwing out the `this.`, or does it create a parameter named `this`, or something else completely? Either way, I'm surprised that the type doesn't get set to `dynamic`.
