### ISSUE TITLE
Analyzer Class 'DynamicTypeImpl' has no instance getter 'interfaces'

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26691]
```
Dart analysis server, SDK version 1.18.0-edge.7653369e50da13ac66111bab0311c6cf9ddcf5a5, server version 1.15.0, error: Task failed: GenerateLintsTask for source /home/myuser/dart/dart-lang/webdriver.dart/lib/support/firefox_profile.dart
Unexpected exception while performing GenerateLintsTask for source /home/myuser/dart/dart-lang/webdriver.dart/lib/support/firefox_profile.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:341)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1191)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1189)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:946)
#11     _CustomZone.run (dart:async/zone.dart:826)
#12     _CustomZone.runGuarded (dart:async/zone.dart:724)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#14     _rootRun (dart:async/zone.dart:950)
#15     _CustomZone.run (dart:async/zone.dart:826)
#16     _CustomZone.runGuarded (dart:async/zone.dart:724)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Class 'DynamicTypeImpl' has no instance getter 'interfaces'.

NoSuchMethodError: method not found: 'interfaces'
Receiver: Instance of 'DynamicTypeImpl'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _findImplementedInterfaces (package:linter/src/rules/iterable_contains_unrelated_type.dart:130)
#3      _findIterableTypeArgument (package:linter/src/rules/iterable_contains_unrelated_type.dart:145)
#4      _Visitor.visitMethodInvocation (package:linter/src/rules/iterable_contains_unrelated_type.dart:197)
#5      DelegatingAstVisitor.visitMethodInvocation.<anonymous closure> (package:analyzer/dart/ast/visitor.dart:604)
#6      List.forEach (dart:core-patch/growable_array.dart:254)
#7      DelegatingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:604)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7309)
#9      PrefixExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8457)
#10     DelegatingAstVisitor.visitPrefixExpression (package:analyzer/dart/ast/visitor.dart:676)
#11     PrefixExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:8453)
#12     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3989)
#13     DelegatingAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:376)
#14     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3985)
#15     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5234)
#16     DelegatingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:447)
#17     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5228)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#19     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:429)
#20     DelegatingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140)
#21     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:425)
#22     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7316)
#23     DelegatingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:605)
#24     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7309)
#25     AssignmentExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:844)
#26     DelegatingAstVisitor.visitAssignmentExpression (package:analyzer/dart/ast/visitor.dart:161)
#27     AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:839)
#28     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4156)
#29     DelegatingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:383)
#30     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4152)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#32     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1284)
#33     DelegatingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:182)
#34     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1280)
#35     IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5704)
#36     DelegatingAstVisitor.visitIfStatement (package:analyzer/dart/ast/visitor.dart:484)
#37     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5699)
#38     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#39     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1284)
#40     DelegatingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:182)
#41     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1280)
#42     IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5704)
#43     DelegatingAstVisitor.visitIfStatement (package:analyzer/dart/ast/visitor.dart:484)
#44     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5699)
#45     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#46     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1284)
#47     DelegatingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:182)
#48     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1280)
#49     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1228)
#50     DelegatingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:189)
#51     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1224)
#52     ConstructorDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2902)
#53     DelegatingAstVisitor.visitConstructorDeclaration (package:analyzer/dart/ast/visitor.dart:274)
#54     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2892)
#55     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#56     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1915)
#57     DelegatingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:224)
#58     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1847)
#59     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#60     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2446)
#61     DelegatingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:252)
#62     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439)
#63     GenerateLintsTask.internalPerform (package:analyzer/src/task/dart.dart:3071)
#64     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#65     AnalysisTask.perform (package:analyzer/task/model.dart:229)
#66     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#67     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#68     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1191)
#69     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#70     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1189)
#71     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#72     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#73     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#74     _rootRun (dart:async/zone.dart:946)
#75     _CustomZone.run (dart:async/zone.dart:826)
#76     _CustomZone.runGuarded (dart:async/zone.dart:724)
#77     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#78     _rootRun (dart:async/zone.dart:950)
#79     _CustomZone.run (dart:async/zone.dart:826)
#80     _CustomZone.runGuarded (dart:async/zone.dart:724)
#81     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#82     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#83     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#84     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#85     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:207)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
```

**Comment by bwilkerson** [comment]
I believe that this was fixed by https://github.com/dart-lang/linter/commit/16afe69d29d5fcc51369a551f4a2a9c48934845b. Please re-open this issue if that's not the case.
