### ISSUE TITLE
 Task failed: PropagateVariableTypesInUnitTask

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#26712]
Fresh build.  Seeing this on atom.

```
[~/src/git/clones/flutter] (master) $ dart --version
Dart VM version: 1.18.0-edge.2eef9f5e27e9ede5bbca09e4c99eccdc1e07f182 (Wed Jun 15 21:05:19 2016) on "macos_ia32"
```

Pretty likely a blocker for rolling ahead with the latest dev build. :(

```
Infinite loop while performing task PropagateVariableTypesInUnitTask for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
  Dependency Cycle:
    Run PropagateVariableTypesInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart
    Run PartiallyResolveUnitReferencesTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart
    Run InferInstanceMembersInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/viewport.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/viewport.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/viewport.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/viewport.dart
    Run InferStaticVariableTypesInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart
    Run InferStaticVariableTypesInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
    Run PartiallyResolveUnitReferencesTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
    Run InferInstanceMembersInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart
    Run InferInstanceMembersInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/box.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/box.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/box.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/box.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/stack.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/stack.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/flow.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/flow.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/custom_layout.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/custom_layout.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/rotated_box.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/rotated_box.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/paragraph.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/paragraph.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/auto_layout.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/auto_layout.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/editable_line.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/editable_line.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/table.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/table.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/error.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/error.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/overflow.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/overflow.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/image.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/image.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/list.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/list.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/shifted_box.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/shifted_box.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/performance_overlay.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/performance_overlay.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/child_view.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/child_view.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/flex.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/flex.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/layer.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/layer.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/view.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/view.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/binding.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/binding.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/debug.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/debug.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/proxy_box.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/proxy_box.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
    Run InferInstanceMembersInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart
    Run PropagateVariableTypesInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
  Cyclic Path:
    CREATED_RESOLVED_UNIT11 for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/viewport.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/viewport.dart
    CREATED_RESOLVED_UNIT11 for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart
    INFERABLE_STATIC_VARIABLES_IN_UNIT for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
    CREATED_RESOLVED_UNIT9 for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
    CREATED_RESOLVED_UNIT10 for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/binding.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/binding.dart
    CREATED_RESOLVED_UNIT11 for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/viewport.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/viewport.dart
    PROPAGABLE_VARIABLES_IN_UNIT for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:326)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1191)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1189)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:946)
#11     _CustomZone.run (dart:async/zone.dart:826)
#12     _CustomZone.runGuarded (dart:async/zone.dart:724)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#14     _rootRun (dart:async/zone.dart:950)
#15     _CustomZone.run (dart:async/zone.dart:826)
#16     _CustomZone.runGuarded (dart:async/zone.dart:724)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

cc @bwilkerson @scheglov 

Any help appreciated!

**Comment by pq** [comment]
This is happening reliably too:

```
AnalysisException: failed to resolve expression
Caused by Infinite loop while performing task PropagateVariableTypesInUnitTask for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart
  Dependency Cycle:
    Run PropagateVariableTypesInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart
    Run PartiallyResolveUnitReferencesTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart
    Run InferInstanceMembersInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart
    Run InferStaticVariableTypesInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart
    Run InferStaticVariableTypesInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
    Run PartiallyResolveUnitReferencesTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
    Run InferInstanceMembersInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart
    Run InferInstanceMembersInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/box.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/box.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/box.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/box.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/stack.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/stack.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/flow.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/flow.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/custom_layout.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/custom_layout.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/rotated_box.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/rotated_box.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/paragraph.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/paragraph.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/auto_layout.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/auto_layout.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/editable_line.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/editable_line.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/table.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/table.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/error.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/error.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/overflow.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/overflow.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/image.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/image.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/list.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/list.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/viewport.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/viewport.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/shifted_box.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/shifted_box.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/performance_overlay.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/performance_overlay.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/child_view.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/child_view.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/flex.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/flex.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/layer.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/layer.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/view.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/view.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/binding.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/binding.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/debug.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/debug.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/proxy_box.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/proxy_box.dart
    Run ResolveInstanceFieldsInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
    Run PropagateVariableTypesInUnitTask on /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
  Cyclic Path:
    CREATED_RESOLVED_UNIT11 for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart
    CREATED_RESOLVED_UNIT11 for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart
    INFERABLE_STATIC_VARIABLES_IN_UNIT for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
    CREATED_RESOLVED_UNIT9 for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/rendering.dart
    CREATED_RESOLVED_UNIT10 for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/grid.dart
    CREATED_RESOLVED_UNIT11 for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/object.dart
    PROPAGABLE_VARIABLES_IN_UNIT for /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart in /Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/rendering/block.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:326)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1191)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1189)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#9      Future.Future.delayed.<anonymous closure> (dart:async/future.dart:228)
#10     _rootRun (dart:async/zone.dart:946)
#11     _CustomZone.run (dart:async/zone.dart:826)
#12     _CustomZone.runGuarded (dart:async/zone.dart:724)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#14     _rootRun (dart:async/zone.dart:950)
#15     _CustomZone.run (dart:async/zone.dart:826)
#16     _CustomZone.runGuarded (dart:async/zone.dart:724)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
#0      AnalysisFutureHelper.computeAsync.<anonymous closure> (package:analyzer/src/context/context.dart:2050)
#1      PendingFuture.evaluate (package:analyzer/src/context/context.dart:2155)
#2      AnalysisFutureHelper.computeAsync (package:analyzer/src/context/context.dart:2056)
#3      DartCompletionRequestImpl._computeAsync.<_computeAsync_async_body> (package:analysis_server/src/services/completion/dart/completion_manager.dart:437)
#4      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#5      _rootRun (dart:async/zone.dart:946)
#6      _CustomZone.run (dart:async/zone.dart:826)
#7      _CustomZone.runGuarded (dart:async/zone.dart:724)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#9      _rootRun (dart:async/zone.dart:950)
#10     _CustomZone.run (dart:async/zone.dart:826)
#11     _CustomZone.runGuarded (dart:async/zone.dart:724)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
#0      DartCompletionRequestImpl._computeAsync.<_computeAsync_async_body> (package:analysis_server/src/services/completion/dart/completion_manager.dart:442)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _rootRunBinary (dart:async/zone.dart:970)
#3      _CustomZone.runBinary (dart:async/zone.dart:849)
#4      _FutureListener.handleError (dart:async/future_impl.dart:146)
#5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#7      _Future._completeError (dart:async/future_impl.dart:485)
#8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#9      _rootRun (dart:async/zone.dart:950)
#10     _CustomZone.run (dart:async/zone.dart:826)
#11     _CustomZone.runGuarded (dart:async/zone.dart:724)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by bwilkerson** [comment]
It would be easier to explain in a face-to-face. Let's discuss this while we're in the office today.

**Comment by scheglov** [comment]
I think this is fixed now with https://github.com/dart-lang/sdk/commit/bc8b32145baba551e08508b7f9062ca92f18d93e.

**Comment by pq** [comment]
Cool.  Thanks!
