### ISSUE TITLE
Analysis Server throws 'Mismatch in DirectiveResolver'

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#26748]
This simple project with 2 dart files causes Analysis Server exception. Reproduced with latest at this moment SDKs 1.17.1 and 1.18-dev.2.0:

`foo.dart` (notice space after bar.dart):
```
import 'bar.dart ';
```

`bar.dart`: empty file in the same folder.

```
Dart analysis server, SDK version 1.17.1, server version 1.15.0, error: Task failed: ResolveDirectiveElementsTask for source C:\dart_projects\failure\foo.dart
Mismatch in DirectiveResolver while resolving C:\dart_projects\failure\foo.dart
Could not find any import element for 'C:\dart_projects\failure\bar.dart '
Path to root: ImportDirectiveImpl, CompilationUnitImpl
#0      SimpleAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3457)
#1      DirectiveResolver._findImport (package:analyzer/src/generated/resolver.dart:2936)
#2      DirectiveResolver.visitImportDirective (package:analyzer/src/generated/resolver.dart:2850)
#3      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:5836)
#4      DirectiveResolver.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:2825)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2433)
#6      ResolveDirectiveElementsTask.internalPerform (package:analyzer/src/task/dart.dart:4615)
#7      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#8      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#9      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#10     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#11     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1176)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#13     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1174)
#14     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#15     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#16     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#17     _rootRun (dart:async/zone.dart:946)
#18     _CustomZone.run (dart:async/zone.dart:826)
#19     _CustomZone.runGuarded (dart:async/zone.dart:724)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#21     _rootRun (dart:async/zone.dart:950)
#22     _CustomZone.run (dart:async/zone.dart:826)
#23     _CustomZone.runGuarded (dart:async/zone.dart:724)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#25     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by alexander-doroshko** [comment]
Got similar exception for another totally valid file.
I opened [test](https://github.com/dart-lang/test) project and got dependencies.
SDK 1.17.1, file: **pub.dartlang.org/scheduled_test-0.12.5+6/lib/scheduled_test.dart**, offset: 387, length: 20
```
Dart analysis server, SDK version 1.17.1, server version 1.15.0, FATAL error: Failed to handle request: {clientRequestTime: 1466771647768, params: {file: C:\Users\alexander.doroshko\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\scheduled_test-0.12.5+6\lib\scheduled_test.dart, offset: 387, length: 20}, method: analysis.getNavigation, id: 33}
AnalysisException: Cannot compute RESOLVED_UNIT for C:\Users\alexander.doroshko\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\scheduled_test-0.12.5+6\lib\scheduled_test.dart in C:\Users\alexander.doroshko\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\scheduled_test-0.12.5+6\lib\scheduled_test.dart
Caused by Mismatch in DirectiveResolver while resolving C:\Users\alexander.doroshko\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\scheduled_test-0.12.5+6\lib\scheduled_test.dart
Could not find any import element for 'C:\Users\alexander.doroshko\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stack_trace-1.6.1\lib\stack_trace.dart'
Path to root: ImportDirectiveImpl, CompilationUnitImpl
#0      SimpleAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3457)
#1      DirectiveResolver._findImport (package:analyzer/src/generated/resolver.dart:2936)
#2      DirectiveResolver.visitImportDirective (package:analyzer/src/generated/resolver.dart:2850)
#3      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:5836)
#4      DirectiveResolver.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:2825)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2433)
#6      ResolveDirectiveElementsTask.internalPerform (package:analyzer/src/task/dart.dart:4615)
#7      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#8      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#9      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#10     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#11     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1176)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#13     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1174)
#14     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#15     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#16     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#17     _rootRun (dart:async/zone.dart:946)
#18     _CustomZone.run (dart:async/zone.dart:826)
#19     _CustomZone.runGuarded (dart:async/zone.dart:724)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#21     _rootRun (dart:async/zone.dart:950)
#22     _CustomZone.run (dart:async/zone.dart:826)
#23     _CustomZone.runGuarded (dart:async/zone.dart:724)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#25     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:678)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1282)
#2      AnalysisServer.getResolvedCompilationUnits.<anonymous closure> (package:analysis_server/src/analysis_server.dart:735)
#3      runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:34)
#4      AnalysisServer.getResolvedCompilationUnits (package:analysis_server/src/analysis_server.dart:730)
#5      AnalysisDomainHandler.getNavigation.<anonymous closure> (package:analysis_server/src/domain_analysis.dart:137)
#6      _rootRunUnary (dart:async/zone.dart:958)
#7      _CustomZone.runUnary (dart:async/zone.dart:837)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#9      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#11     _Future._completeWithValue (dart:async/future_impl.dart:477)
#12     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#13     _rootRun (dart:async/zone.dart:950)
#14     _CustomZone.run (dart:async/zone.dart:826)
#15     _CustomZone.runGuarded (dart:async/zone.dart:724)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by alexander-doroshko** [comment]
Still getting this fatal error with 1.18.0-dev.4.4
// cc @scheglov

**Comment by scheglov** [comment]
I was not able to reproduce it on Mac.
But I can reproduce it on Windows.

Ah... I see the difference.
On Mac this code prints `true` and `false`.
On Windows an analogous code prints `true` and `true`.

```Dart
import 'dart:io';

main() {
  print(new File('/Users/scheglov/dart/test/bin/test.dart').existsSync());
  print(new File('/Users/scheglov/dart/test/bin/test.dart ').existsSync());
}
```

So, we think that the `bar.dart ` source exists, but we (unexpectedly) were not able to resolve the import.

Interestingly, Dart VM on Mac also says that `bar.dart ` (with a space) cannot be resolved. But the same code works fine on Windows, where spaces are ignored.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/41ac4308879a6a900b19cc216af2e44045eadf9b
