### ISSUE TITLE
Very bad error reporting

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26746]
The following program has unusable error reporting in Chrome:

``` dart
foo() { print("foo"); }

int run1(f) {
  f();
  return 1;
  return 2;
}

runBench() async {
  var f = foo();
  for (int i = 0; i < 100; i++) {
    await run1(f);
  }
}

main(List<String> args) {
  runBench();
}
```

On the command line it reports a nice error:
```
$ d8 preambles/d8.js /tmp/foo.js
foo
/home/floitsch/code/dart/sdk/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: NullError: method not found: 'call$0' on null
          throw e;
          ^
TypeError: Cannot read property 'call$0' of null
    at dart.run1 (/tmp/foo.js:3130:8)
    at /tmp/foo.js:3154:39
    at _wrapJsFunctionForAsync_closure.$protected (/tmp/foo.js:3366:15)
    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (/tmp/foo.js:3579:14)
    at _awaitOnObject_closure.dart._awaitOnObject_closure.call$1 (/tmp/foo.js:3567:34)
    at _RootZone.dart._RootZone.runUnary$2 (/tmp/foo.js:4138:20)
    at _FutureListener.dart._FutureListener.handleValue$1 (/tmp/foo.js:3622:34)
    at _Future__propagateToListeners_handleValueCallback.dart._Future__propagateToListeners_handleValueCallback.call$0 (/tmp/foo.js:3974:60)
    at dart._Future.static._Future__propagateToListeners (/tmp/foo.js:3842:104)
    at _Future__addListener_closure.dart._Future__addListener_closure.call$0 (/tmp/foo.js:3889:11)
```

In the browser you get:
```
foo.js:1104 Uncaught 
```

/cc @rakudrama

**Comment by floitschG** [comment]
This seems to be fixed.
