### ISSUE TITLE
Assertion in store_buffer.cc

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#26783]
Seen on the buildbot:
https://build.chromium.org/p/client.dart/builders/pkg-mac-debug-be/builds/2958/steps/pkg%20tests%20failures/logs/stdio

```
FAILED: none-vm-checked debug_ia32 pkg/analyzer/tool/task_dependency_graph/check_test
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stderr:
/b/build/slave/pmd-be/build/sdk/runtime/vm/store_buffer.cc: 107: error: expected: thread->isolate()->mutator_thread() == thread


Command[vm]: DART_CONFIGURATION=DebugIA32 xcodebuild/DebugIA32/dart-sdk/bin/dart --enable_asserts --enable_type_checks --ignore-unrecognized-flags --package-root=xcodebuild/DebugIA32/packages/ /b/build/slave/pmd-be/build/sdk/pkg/analyzer/tool/task_dependency_graph/check_test.dart
Took 0:01:33.656896

Short reproduction command (experimental):
    python tools/test.py -aia32 --use-sdk --checked --write-test-outcome-log -t300 --copy-coredumps pkg/analyzer/tool/task_dependency_graph/check_test
```

**Comment by fsc8000** [comment]
@a-siva

**Comment by fsc8000** [comment]
This assert seems wrong. The background compiler thread can call this function as well.

```
0  0xf7724440 in __kernel_vsyscall ()
#1  0xf7407687 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf740aab3 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x0844e02b in dart::OS::Abort() ()
#4  0x081d5945 in dart::DynamicAssertionHelper::Fail(char const*, ...) ()
#5  0x0854dd3f in dart::StoreBuffer::PushBlock(dart::PointerBlock<1024>*, dart::StoreBuffer::ThresholdPolicy) ()
#6  0x0856b8be in dart::Thread::ExitIsolateAsHelper(bool) ()
#7  0x0822af46 in dart::BackgroundCompiler::Run() ()
#8  0x08572bd0 in dart::ThreadPool::Worker::Loop() ()
#9  0x085731ab in dart::ThreadPool::Worker::Main(unsigned int) ()
#10 0x0844ffe5 in ?? ()
#11 0xf76e8f72 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#12 0xf74c4f8e in clone () from /lib/i386-linux-gnu/libc.so.6
```
