### ISSUE TITLE
HOT RELOAD: OSR related reload crash

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26806]
How to reproduce (may take minutes of reloading):

In your top level `sdk/` run the following once:

`$ ln -s sdk/lib/ lib`

In `pkg/compiler` run the following:
`$ gdb --args ../../out/ReleaseX64/dart --trace-reload --background_compilation=false --reload-every=500000 bin/dart2js.dart --categories=all bin/dart2js.dart`

The crash I observed was:

```
#0  Write<dart::RawObject*> (value=<synthetic pointer>, ptr=0x7ffff7e86348) at runtime/vm/verified_memory.h:55
#1  dart::RawObject::StorePointer<dart::RawObject*> (this=0x7ffff7e86321, addr=0x7ffff7e86348, value=0x7fffaafeb731)
    at runtime/vm/raw_object.h:578
#2  0x000000000072604e in StorePointer<dart::RawObject*> (value=<optimized out>, addr=<optimized out>, this=0x7ffff4dbb550)
    at runtime/vm/object.h:647
#3  set_owner (function=..., this=this@entry=0x7ffff4dbb550) at runtime/vm/object.h:4703
#4  dart::Function::AttachCode (this=this@entry=0x7ffff4dbb4f0, value=...) at runtime/vm/object.cc:5263
#5  0x0000000000887460 in DRT_HelperStackOverflow (zone=<optimized out>, thread=<optimized out>, isolate=<optimized out>, arguments=...)
    at runtime/vm/code_generator.cc:1385
#6  dart::DRT_StackOverflow (arguments=...) at runtime/vm/code_generator.cc:1217
#7  0x00007ffff7e4341b in ?? ()
#8  0x0000000001104c20 in ?? ()
#9  0x0000000000000000 in ?? ()
```

Digging in, we are looking at the function `"Function '_emptyDeferredQueue@74414697':."` and the code is `"[stub: LazyCompile]"`.

The crash happens when trying to associate the code with the function (set_owner). The code object is read only in the vm-isolate heap and we can't touch that memory.

**Comment by johnmccutchan** [comment]
Note that during a reload we replace many functions's code with the lazy compile stub.
