### ISSUE TITLE
Error: Expected response for class com.jetbrains.lang.dart.ide.runner.server.vmService.VmServiceWrapper$8

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26824]
First reported in https://youtrack.jetbrains.com/issue/WEB-22267

When I debug a Dart command line app I get

```
/usr/local/bin/dart/dart-sdk/bin/dart --ignore-unrecognized-flags --checked --pause_isolates_on_start --enable-vm-service:36525 --trace_service_pause_events /home/zoechi/dart/bwu_server/server/bwu_server_shared/test/datastore/entity_key_test.dart
Observatory listening on http://127.0.0.1:36525
00:00 +0: bwu_server_shared.datastore_entity_key basic
00:00 +1: bwu_server_shared.datastore_entity_key EntityKeyStatus
00:00 +2: bwu_server_shared.datastore_entity_key fromDatastoreKey with id
00:00 +3: bwu_server_shared.datastore_entity_key fromDatastoreKey with name
00:00 +4: bwu_server_shared.datastore_entity_key _makePersistent
Instance of 'CommitRequest'
Error: Expected response for class com.jetbrains.lang.dart.ide.runner.server.vmService.VmServiceWrapper$8
  implementing interface org.dartlang.vm.service.consumer.EvaluateInFrameConsumer
  but received {"type":"Sentinel","kind":"OptimizedOut","valueAsString":"<optimized out>"}
Error: Expected response for class com.jetbrains.lang.dart.ide.runner.server.vmService.VmServiceWrapper$8
  implementing interface org.dartlang.vm.service.consumer.EvaluateInFrameConsumer
  but received {"type":"Sentinel","kind":"OptimizedOut","valueAsString":"<optimized out>"}
Error: Expected response for class com.jetbrains.lang.dart.ide.runner.server.vmService.VmServiceWrapper$8
  implementing interface org.dartlang.vm.service.consumer.EvaluateInFrameConsumer
  but received {"type":"Sentinel","kind":"OptimizedOut","valueAsString":"<optimized out>"}
Error: Expected response for class com.jetbrains.lang.dart.ide.runner.server.vmService.VmServiceWrapper$8
  implementing interface org.dartlang.vm.service.consumer.EvaluateInFrameConsumer
  but received {"type":"Sentinel","kind":"OptimizedOut","valueAsString":"<optimized out>"}
Error: Expected response for class com.jetbrains.lang.dart.ide.runner.server.vmService.VmServiceWrapper$8
  implementing interface org.dartlang.vm.service.consumer.EvaluateInFrameConsumer
  but received {"type":"Sentinel","kind":"OptimizedOut","valueAsString":"<optimized out>"}
Error: Expected response for class com.jetbrains.lang.dart.ide.runner.server.vmService.VmServiceWrapper$8
  implementing interface org.dartlang.vm.service.consumer.EvaluateInFrameConsumer
  but received {"type":"Sentinel","kind":"OptimizedOut","valueAsString":"<optimized out>"}
160703 19:34:52.656 SEVERE 0 bwu_server_shared.shared.datastore Bad state: No element
00:18 +4 -1: bwu_server_shared.datastore_entity_key _makePersistent
  Bad state: No element
  dart:collection                                                   Object&ListMixin.firstWhere
  package:bwu_server_shared/src/datastore/unit_of_work.dart 474:10  UnitOfWork.sysEntityKind
  package:bwu_server_shared/src/datastore/entity_sys.dart 242:39    Sys._uniqueConstraints.<fn>
  dart:core                                                         List.forEach
  package:bwu_server_shared/src/datastore/entity_sys.dart 188:8     Sys._uniqueConstraints
  package:bwu_server_shared/src/datastore/unit_of_work.dart 253:46  UnitOfWork.commit.<async>.<fn>.<fn>
  dart:core                                                         List.forEach
  package:bwu_server_shared/src/datastore/unit_of_work.dart 251:16  UnitOfWork.commit.<async>.<fn>
  dart:async                                                        Future.doWhile
  package:bwu_server_shared/src/datastore/unit_of_work.dart 243:19  UnitOfWork.commit.<async>
  ===== asynchronous gap ===========================
  dart:async                                                        Future.doWhile
  package:bwu_server_shared/src/datastore/unit_of_work.dart 243:19  UnitOfWork.commit.<async>
  ===== asynchronous gap ===========================
  dart:async                                                        Future.doWhile
  package:bwu_server_shared/src/datastore/unit_of_work.dart 243:19  UnitOfWork.commit.<async>
  ===== asynchronous gap ===========================
  dart:async                                                        Future.Future.microtask
  package:bwu_server_shared/src/datastore/unit_of_work.dart         UnitOfWork.commit
  package:bwu_server_shared/src/datastore/unit_of_work.dart 442:43  UnitOfWork._initSysRecords.<async>
  dart:async                                                        _SyncCompleter.complete
  package:bwu_server_shared/src/datastore/unit_of_work.dart 747:5   UnitOfWork.query.<async>
  dart:async                                                        _SyncCompleter.complete
  test/datastore/mock_datastore.dart 206:5                          MockConnection.runQuery.<async>
  ===== asynchronous gap ===========================
  dart:async                                                        _asyncThenWrapperHelper
  package:bwu_server_shared/src/datastore/unit_of_work.dart         UnitOfWork._initSysRecords
  package:bwu_server_shared/src/datastore/unit_of_work.dart 387:18  UnitOfWork._initServer.<async>
  dart:async                                                        _SyncCompleter.complete
  test/datastore/mock_datastore.dart 191:5                          MockConnection.commit.<async>
  ===== asynchronous gap ===========================
  dart:async                                                        _asyncThenWrapperHelper
  package:bwu_server_shared/src/datastore/unit_of_work.dart         UnitOfWork._initServer
  package:bwu_server_shared/src/datastore/unit_of_work.dart 376:12  UnitOfWork.init
  test/datastore/mock_datastore.dart 45:39                          createMockSession
  test/datastore/entity_key_test.dart 76:34                         main.<fn>.<fn>
  
  This test failed after it had already completed. Make sure to use [expectAsync]
  or the [completes] matcher when testing async code.
  dart:collection                                                   Object&ListMixin.firstWhere
  package:bwu_server_shared/src/datastore/unit_of_work.dart 474:10  UnitOfWork.sysEntityKind
  package:bwu_server_shared/src/datastore/entity_sys.dart 242:39    Sys._uniqueConstraints.<fn>
  dart:core                                                         List.forEach
  package:bwu_server_shared/src/datastore/entity_sys.dart 188:8     Sys._uniqueConstraints
  package:bwu_server_shared/src/datastore/unit_of_work.dart 253:46  UnitOfWork.commit.<async>.<fn>.<fn>
  dart:core                                                         List.forEach
  package:bwu_server_shared/src/datastore/unit_of_work.dart 251:16  UnitOfWork.commit.<async>.<fn>
  dart:async                                                        Future.doWhile
  package:bwu_server_shared/src/datastore/unit_of_work.dart 243:19  UnitOfWork.commit.<async>
  ===== asynchronous gap ===========================
  dart:async                                                        Future.doWhile
  package:bwu_server_shared/src/datastore/unit_of_work.dart 243:19  UnitOfWork.commit.<async>
  ===== asynchronous gap ===========================
  dart:async                                                        Future.doWhile
  package:bwu_server_shared/src/datastore/unit_of_work.dart 243:19  UnitOfWork.commit.<async>
  ===== asynchronous gap ===========================
  dart:async                                                        Future.Future.microtask
  package:bwu_server_shared/src/datastore/unit_of_work.dart         UnitOfWork.commit
  package:bwu_server_shared/src/datastore/unit_of_work.dart 442:43  UnitOfWork._initSysRecords.<async>
  dart:async                                                        _SyncCompleter.complete
  package:bwu_server_shared/src/datastore/unit_of_work.dart 747:5   UnitOfWork.query.<async>
  dart:async                                                        _SyncCompleter.complete
  test/datastore/mock_datastore.dart 206:5                          MockConnection.runQuery.<async>
  ===== asynchronous gap ===========================
  dart:async                                                        _asyncThenWrapperHelper
  package:bwu_server_shared/src/datastore/unit_of_work.dart         UnitOfWork._initSysRecords
  package:bwu_server_shared/src/datastore/unit_of_work.dart 387:18  UnitOfWork._initServer.<async>
  dart:async                                                        _SyncCompleter.complete
  test/datastore/mock_datastore.dart 191:5                          MockConnection.commit.<async>
  ===== asynchronous gap ===========================
  dart:async                                                        _asyncThenWrapperHelper
  package:bwu_server_shared/src/datastore/unit_of_work.dart         UnitOfWork._initServer
  package:bwu_server_shared/src/datastore/unit_of_work.dart 376:12  UnitOfWork.init
  test/datastore/mock_datastore.dart 45:39                          createMockSession
  test/datastore/entity_key_test.dart 76:34                         main.<fn>.<fn>
  
00:18 +4 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:938)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Process finished with exit code 255

```

Seems to be when an exception is thrown

I get the error output since I updated to 

```
Dart VM version: 1.18.0-edge.34d3c37233f3beb6d1dfb5b23d23c0a674419661 (Fri Jul  1 22:40:11 2016) on "linux_x64"
```

Reverting to 
```
Dart VM version: 1.18.0-edge.524fbc1e0f9d61ff5da69bbed2b35745528de945 (Wed Jun 29 20:02:58 2016) on "linux_x64"
``` 
fixed it.

**Comment by alexander-doroshko** [comment]
[evaluateInFrame](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#evaluateinframe) in spec doesn't allow Sentinel as response, but looks like it was sent by the VM.

**Comment by alexander-doroshko** [comment]
@floitschG This looks more like VM Service issue, not the analyzer's one.

**Comment by zoechi** [comment]
I can't reproduce. I think this can be closed.
