### ISSUE TITLE
Deadlock during old space allocation

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#26891]
```
out/ProductX64/dart --package-root=out/ProductX64/packages tests/corelib/regexp/pcre_test.dart
```

```
Thread 4 (Thread 0x7f52da431700 (LWP 14735)):
#0  0x00007f52d9128a13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000056bcc6 in dart::bin::EventHandlerImplementation::Poll (
    args=args@entry=29667968) at runtime/bin/eventhandler_linux.cc:391
#2  0x00000000005679f7 in dart::bin::ThreadStart (data_ptr=<optimized out>)
    at runtime/bin/thread_linux.cc:91
#3  0x00007f52da027184 in start_thread (arg=0x7f52da431700) at pthread_create.c:312
#4  0x00007f52d912837d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7f52d8f6d700 (LWP 14738)):
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000006e2a85 in dart::Monitor::WaitMicros (this=this@entry=0x7f52d0033420, 
    micros=micros@entry=0) at runtime/vm/os_thread_linux.cc:418
#2  0x00000000006e2bbc in dart::Monitor::Wait (this=this@entry=0x7f52d0033420, 
    millis=millis@entry=0) at runtime/vm/os_thread_linux.cc:402
#3  0x00000000005aadab in Wait (this=<synthetic pointer>, millis=0)
    at runtime/vm/lockers.h:169
#4  dart::BackgroundCompiler::Run (this=0x7f52d0033ab0) at runtime/vm/compiler.cc:1894
#5  0x0000000000796eb8 in dart::ThreadPool::Worker::Loop (this=this@entry=0x1c73bd0)
    at runtime/vm/thread_pool.cc:407
#6  0x0000000000797074 in dart::ThreadPool::Worker::Main (args=args@entry=29834192)
    at runtime/vm/thread_pool.cc:464
#7  0x00000000006e2057 in dart::ThreadStart (data_ptr=<optimized out>)
    at runtime/vm/os_thread_linux.cc:123
#8  0x00007f52da027184 in start_thread (arg=0x7f52d8f6d700) at pthread_create.c:312
#9  0x00007f52d912837d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7f52d863c700 (LWP 14753)):
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000006e2a85 in dart::Monitor::WaitMicros (this=0x1c95320, micros=micros@entry=0)
    at runtime/vm/os_thread_linux.cc:418
#2  0x00000000006e2bbc in dart::Monitor::Wait (this=<optimized out>, millis=millis@entry=0)
    at runtime/vm/os_thread_linux.cc:402
#3  0x000000000068a929 in dart::MonitorLocker::WaitWithSafepointCheck (
    this=this@entry=0x7f52d863a320, thread=thread@entry=0x1c65b80, millis=millis@entry=0)
---Type <return> to continue, or q <return> to quit---
    at runtime/vm/lockers.cc:34
#4  0x000000000062f0bd in dart::Heap::AllocateOld (this=0x1c64b40, size=size@entry=80, 
    type=type@entry=dart::HeapPage::kData) at runtime/vm/heap.cc:99
#5  0x00000000006986a3 in Allocate (space=dart::Heap::kOld, size=80, this=<optimized out>)
    at runtime/vm/heap.h:79
#6  dart::Object::Allocate (cls_id=64, size=80, space=dart::Heap::kOld)
    at runtime/vm/object.cc:1839
#7  0x000000000069886f in dart::Array::New (len=len@entry=6, 
    space=space@entry=dart::Heap::kOld, class_id=64) at runtime/vm/object.cc:21263
#8  0x00000000006b7b8e in New (space=dart::Heap::kOld, len=6) at runtime/vm/object.cc:21250
#9  dart::Array::Grow (source=..., new_length=6, space=space@entry=dart::Heap::kOld)
    at runtime/vm/object.cc:21317
#10 0x00000000006b7d41 in dart::ICData::FindFreeIndex (this=this@entry=0x7f52d863ab70, 
    index=index@entry=0x7f52d863a4b0) at runtime/vm/object.cc:12925
#11 0x00000000006c1782 in dart::ICData::AddReceiverCheck (this=this@entry=0x7f52d863ab70, 
    receiver_class_id=49, target=..., count=count@entry=1) at runtime/vm/object.cc:12968
#12 0x00000000007d4723 in dart::InlineCacheMissHandler (args=..., ic_data=...)
    at runtime/vm/code_generator.cc:813
#13 0x00000000007d90ef in DRT_HelperInlineCacheMissHandlerOneArg (isolate=<optimized out>, 
    thread=<optimized out>, zone=<optimized out>, arguments=...)
    at runtime/vm/code_generator.cc:859
#14 dart::DRT_InlineCacheMissHandlerOneArg (arguments=...)
    at runtime/vm/code_generator.cc:853
#15 0x00007f52da2b141b in ?? ()
#16 0x0000000001c65b80 in ?? ()
#17 0x0000000000000002 in ?? ()
#18 0x00007f52d863b018 in ?? ()
#19 0x00007f52d863b020 in ?? ()
#20 0x00007f52da2f3101 in ?? ()
#21 0x00007f52da2f3fa1 in ?? ()
#22 0x00007f52d863b048 in ?? ()
#23 0x00007f52da2b231e in ?? ()
#24 0x00007f52cb6d8431 in ?? ()
#25 0x00007f52d88f7351 in ?? ()
#26 0x00007f52da2f1021 in ?? ()
#27 0x00007f52cb6d8431 in ?? ()
#28 0x00007f52da2f36e1 in ?? ()
#29 0x00007f52cb42b021 in ?? ()
---Type <return> to continue, or q <return> to quit---
#30 0x00007f52da2f4b71 in ?? ()
#31 0x00007f52d863b090 in ?? ()
#32 0x00007f52cb4251ea in ?? ()
#33 0x0000000000000bc8 in ?? ()
#34 0x00007f52d88f7351 in ?? ()
#35 0x00007f52d88f7351 in ?? ()
#36 0x00007f52d8b7a541 in ?? ()
#37 0x00007f52da2f1021 in ?? ()
#38 0x00007f52d8097961 in ?? ()
#39 0x00007f52cb6edf61 in ?? ()
#40 0x00007f52d863b0c0 in ?? ()
#41 0x00007f52d88d6ad5 in ?? ()
#42 0x00007f52d8b7a541 in ?? ()
#43 0x00007f52da2f1021 in ?? ()
#44 0x00007f52d814cb91 in ?? ()
#45 0x00007f52d80979c1 in ?? ()
#46 0x00007f52d863b100 in ?? ()
#47 0x00007f52d88d2120 in ?? ()
#48 0x00007f52d814dc61 in ?? ()
#49 0x00007f52d814dc61 in ?? ()
#50 0x00007f52d8b7a541 in ?? ()
#51 0x00007f52da2f1021 in ?? ()
#52 0x00007f52d8095431 in ?? ()
#53 0x00007f52d814cbf1 in ?? ()
#54 0x00007f52d863b138 in ?? ()
#55 0x00007f52d88d60f5 in ?? ()
#56 0x00007f52d814dc61 in ?? ()
#57 0x00007f52cbdfa191 in ?? ()
#58 0x00007f52da2f1021 in ?? ()
#59 0x00007f52d8934351 in ?? ()
#60 0x00007f52d8095521 in ?? ()
#61 0x00007f52d863b180 in ?? ()
#62 0x00007f52d88bcbc3 in ?? ()
#63 0x00007f52da2f1021 in ?? ()
#64 0x00007f52d88f6d61 in ?? ()
#65 0x00007f52d88f6d61 in ?? ()
#66 0x00007f52d8b7a541 in ?? ()
#67 0x00007f52da2f1021 in ?? ()
---Type <return> to continue, or q <return> to quit---
#68 0x00007f52d8094dc1 in ?? ()
#69 0x00007f52d89343b1 in ?? ()
#70 0x00007f52d863b1c0 in ?? ()
#71 0x00007f52d88d5e98 in ?? ()
#72 0x00007f52da2f1021 in ?? ()
#73 0x00007f52d88f6d61 in ?? ()
#74 0x00007f52d8b7a541 in ?? ()
#75 0x00007f52da2f1021 in ?? ()
#76 0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f52da433780 (LWP 14733)):
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000006e2a85 in dart::Monitor::WaitMicros (this=this@entry=0x7ffc9bf11cf0, 
    micros=micros@entry=0) at runtime/vm/os_thread_linux.cc:418
#2  0x00000000006e2bbc in dart::Monitor::Wait (this=this@entry=0x7ffc9bf11cf0, 
    millis=millis@entry=0) at runtime/vm/os_thread_linux.cc:402
#3  0x000000000054d54a in Wait (this=<synthetic pointer>, millis=0)
    at runtime/vm/lockers.h:169
#4  dart::Dart_RunLoop () at runtime/vm/dart_api_impl.cc:1656
#5  0x00000000005384e8 in dart::bin::RunMainIsolate (
    script_name=script_name@entry=0x7ffc9bf12ea3 "tests/corelib/regexp/pcre_test.dart", 
    dart_options=dart_options@entry=0x7ffc9bf12190) at runtime/bin/main.cc:1471
#6  0x00000000005339b4 in dart::bin::main (argc=3, argv=0x7ffc9bf122e8)
    at runtime/bin/main.cc:1713
#7  0x0000000000533b59 in main (argc=<optimized out>, argv=<optimized out>)
    at runtime/bin/main.cc:1752
```

```
(gdb) thread 2
[Switching to thread 2 (Thread 0x7f52d863c700 (LWP 14753))]
#4  0x000000000062f0bd in dart::Heap::AllocateOld (this=0x1c64b40, size=size@entry=80, 
    type=type@entry=dart::HeapPage::kData) at runtime/vm/heap.cc:99
99	      ml.WaitWithSafepointCheck(thread);
(gdb) frame 4
#4  0x000000000062f0bd in dart::Heap::AllocateOld (this=0x1c64b40, size=size@entry=80, 
    type=type@entry=dart::HeapPage::kData) at runtime/vm/heap.cc:99
99	      ml.WaitWithSafepointCheck(thread);
(gdb) print addr
$4 = 0
(gdb) print old_space_.tasks_
$5 = 0
```

**Comment by rmacnak-google** [comment]
d28744b8d23d12f730587ad639f64011e42e9267
