### ISSUE TITLE
exception when writing files to the devfs

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#26904]
When run against the ios simulator, I get an exception when writing files to the devfs. This is reproducible by running `flutter run --devfs`. I can write a file (`foo.txt`) w/o a directory; anything with a directory in the path fails (`foo/bar.txt`). I suspect that the parent directories need to be created.

```
vm-service: Error: Unhandled exception:
	FileSystemException: Cannot open file, path = '/Users/.../BC0CC205-716F-4FCD-914C-589FDF557E73/tmp/flutter_gallery0Gmu7N/lib/demo/all.dart' (OS Error: No such file or directory, errno = 2)
	#0      _File.open.<anonymous closure> (file_impl.dart:356)
	#1      _RootZone.runUnary (dart:async/zone.dart:1683)
	#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
	#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
	#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
	#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
	#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
	#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
	#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
	#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
	#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Note that after this exception the service protocol no longer responds to requests (though the websocket is still live.

For android devices, the exception is:

```
E/DartVM  : vm-service: Error: Unhandled exception:
E/DartVM  : FileSystemException: Creation of temporary directory failed, path = '/data/local/tmp' (OS Error: Permission denied, errno = 13)
E/DartVM  : #0      _Directory.createTemp.<anonymous closure> (directory_impl.dart:128)
E/DartVM  : #1      _RootZone.runUnary (dart:async/zone.dart:1683)
...
```

@turnidge @johnmccutchan

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2157013002
https://codereview.chromium.org/2156243002/
