### ISSUE TITLE
Exception in Observatory web interface

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#26936]
![screen shot 2016-07-21 at 9 43 14 am](https://cloud.githubusercontent.com/assets/5479/17031153/995ca3da-4f27-11e6-9268-76bd88308dbc.png)

When I click `localhost$main` I'm taken to a blank page.

Dev console shows:

```
WARNING: 2016-07-21 09:43:19.055: Caught exception: NullError: method not found: 'N' on null
TypeError: Cannot read property 'N' of null
    at bR.GI (http://127.0.0.1:58133/index.html.polymer.bootstrap.dart.js:29183:2)
    at bR.aW (http://127.0.0.1:58133/index.html.polymer.bootstrap.dart.js:29165:6)
    at bR.c6 (http://127.0.0.1:58133/index.html.polymer.bootstrap.dart.js:28480:6)
    at U0.dart.U0.$1 (http://127.0.0.1:58133/index.html.polymer.bootstrap.dart.js:28489:8)
    at v.dart.zN (http://127.0.0.1:58133/index.html.polymer.bootstrap.dart.js:11195:24)
    at Xs.dart.Xs.fg (http://127.0.0.1:58133/index.html.polymer.bootstrap.dart.js:12459:12)
    at Yg.$0 (http://127.0.0.1:58133/index.html.polymer.bootstrap.dart.js:11639:12)
    at fa (http://127.0.0.1:58133/index.html.polymer.bootstrap.dart.js:11602:43)
    at J.ov (http://127.0.0.1:58133/index.html.polymer.bootstrap.dart.js:11555:3)
    at Y9.dart.Y9.$0 (http://127.0.0.1:58133/index.html.polymer.bootstrap.dart.js:11633:23)
```

**Comment by sethladd** [comment]
cc @johnmccutchan

**Comment by johnmccutchan** [comment]
@B3rn475

**Comment by sethladd** [comment]
This was on Flutter, so it's probably a very recent version of Dart.

**Comment by johnmccutchan** [comment]
@sethladd @B3rn475 Is this still an issue?

**Comment by sethladd** [comment]
I think we're good now. Thanks for checking in.
