### ISSUE TITLE
MessageNotUnderstood in HTTP header parsing

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#26958]
https://build.chromium.org/p/client.dart/builders/vm-linux-release-ia32-optcounter-threshold-be/builds/1612/steps/vm%20tests/logs/stdio

```
FAILED: none-vm release_ia32 service/observatory_assets_test
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:

stdout:
** Launching out/ReleaseIA32/dart --optimization-counter-threshold=5 --ignore-unrecognized-flags --package-root=out/ReleaseIA32/packages/ --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/observatory_assets_test.dart
Observatory listening on http://127.0.0.1:41018
** Signaled to run test queries on 41018

Loading VM...
Done loading VM
Running observatory_assets_test.dart [1/1]
Trying to fetch http://localhost:41018/third_party/trace_viewer_full.html
vm-service: Error: Unhandled exception:
The null object does not have a method 'toLowerCase'.

NoSuchMethodError: method not found: 'toLowerCase'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _HeaderValue._parse.parseParameters (dart:io/http_headers.dart:770)
#3      _HeaderValue._parse (dart:io/http_headers.dart:786)
#4      _ContentType.parse (dart:io/http_headers.dart:823)
#5      ContentType.parse (dart:io/http.dart:799)
#6      Server._requestHandler (server.dart:188:23)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#11     _StreamController._add (dart:async/stream_controller.dart:635)
#12     _StreamController.add (dart:async/stream_controller.dart:581)
#13     _HttpServer._handleRequest (dart:io/http_impl.dart:2385)
#14     _HttpConnection._HttpConnection.<anonymous closure> (dart:io/http_impl.dart:2139)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#18     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#19     _StreamController._add (dart:async/stream_controller.dart:635)
#20     _StreamController.add (dart:async/stream_controller.dart:581)
#21     _HttpParser._headersEnd (dart:io/http_parser.dart:389)
#22     _HttpParser._doParse (dart:io/http_parser.dart:711)
#23     _HttpParser._parse (dart:io/http_parser.dart:332)
#24     _HttpParser._onData (dart:io/http_parser.dart:821)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#28     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#29     _StreamController._add (dart:async/stream_controller.dart:635)
#30     _StreamController.add (dart:async/stream_controller.dart:581)
#31     _Socket._onData (dart:io-patch/socket_patch.dart:1659)
#32     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#35     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#36     _StreamController._add (dart:async/stream_controller.dart:635)
#37     _StreamController.add (dart:async/stream_controller.dart:581)
#38     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1226)
#39     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)



Command[vm]: DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --optimization-counter-threshold=5 --ignore-unrecognized-flags --package-root=out/ReleaseIA32/packages/ /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/observatory_assets_test.dart
Took 0:01:00.032176
```

**Comment by whesse** [comment]
@lrhn @whesse @floitschG 
Ryan - since we are all on vacation, can you look into this some more yourself?

**Comment by sgjesse** [comment]
Do we have any way to get the actual HTTP headers causing the issue? I can see an error on the Content-Type parser when the content type has no actual value, something like this:
```
Content-Type: text/html; charset=;
```
Then `toLowerCase` will be called on `null`.

**Comment by sgjesse** [comment]
I have looked a bit more into this. It turns out, that the content type it chokes on is one that is returned from the VM service asset handler, [here](https://github.com/dart-lang/sdk/blob/e6241bc12d1449a57fe569a188ecc1f7d9d5186b/sdk/lib/vmservice/asset.dart#L13), called from [here](https://github.com/dart-lang/sdk/blob/e6241bc12d1449a57fe569a188ecc1f7d9d5186b/sdk/lib/vmservice/asset.dart#L13). However, all the possible returned content types is handled correctly by `ContentType.parse`.

I have made the change https://codereview.chromium.org/2225003002, which addresses the `null` case and thest all the content types returned by the VM service asset handler.

**Comment by sgjesse** [comment]
Closed by https://github.com/dart-lang/sdk/commit/f9404b969ba0b244fbff6dc8aa0388c57f3ad577.
