### ISSUE TITLE
dartanalyzer crash using @JS() on external dynamic property

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#26987]
I guess this isn't valid code, but I was trying to expose a JS property to Dart and I did this:

```
@JS()
external dynamic exports;
```

When I ran the analyzer with `dartanalyzer . --strong` I got this output:

```
PS M:\Coding\TestStuff\dartvs-code\dartvs> dartanalyzer . --strong
Analyzing [.]...
Unhandled exception:
AnalysisException: Cannot compute DART_ERRORS for M:\Coding\TestStuff\dartvs-code\dartvs\lib\extension.dart
Caused by Unexpected exception while performing VerifyUnitTask for source M:\Coding\TestStuff\dartvs-code\dartvs\lib\extension.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:350)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:703)
#5      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:651)
#6      AnalyzerImpl.prepareErrors.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:130)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#8      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:128)
#9      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
#10     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:123)
#11     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:608)
#12     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:214)
#13     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:157)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#15     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:156)
#16     Driver.start (package:analyzer_cli/src/driver.dart:137)
#17     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'name'.

NoSuchMethodError: method not found: 'name'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ErrorVerifier._checkForMissingJSLibAnnotation (package:analyzer/src/generated/error_verifier.dart:4404)
#3      ErrorVerifier.visitAnnotation (package:analyzer/src/generated/error_verifier.dart:326)
#4      AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:314)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#6      AnnotatedNodeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:162)
#7      TopLevelVariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10000)
#8      RecursiveAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1918)
#9      ErrorVerifier.visitTopLevelVariableDeclaration (package:analyzer/src/generated/error_verifier.dart:1132)
#10     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:9996)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2446)
#13     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449)
#14     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:547)
#15     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439)
#16     VerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:6257)
#17     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:338)
#18     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#19     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#20     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#21     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:703)
#22     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:651)
#23     AnalyzerImpl.prepareErrors.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:130)
#24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#25     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:128)
#26     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
#27     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:123)
#28     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:608)
#29     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:214)
#30     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:157)
#31     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#32     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:156)
#33     Driver.start (package:analyzer_cli/src/driver.dart:137)
#34     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:708)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:651)
#2      AnalyzerImpl.prepareErrors.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:130)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:128)
#5      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
#6      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:123)
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:608)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:214)
#9      Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:157)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#11     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:156)
#12     Driver.start (package:analyzer_cli/src/driver.dart:137)
#13     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
PS M:\Coding\TestStuff\dartvs-code\dartvs>
```

Even if what I'm doing is bad, I guess the analyzer shouldn't crash this way?

**Comment by bwilkerson** [comment]
Yes, the analyzer should never crash.

**Comment by bwilkerson** [comment]
Aside from the exception, the problem with the original code is that it isn't valid to declare an external variable. Top-level functions, getters, and setters, as well as constructors, methods, getters and setters in a class can all be external, but not top-level variables and fields in classes.

**Comment by DanTup** [comment]
Thanks for clarifying. I was trying to get at `exports` for a node module, but I think the dev compiler (with it's node mode) will work better if I can get it working.

Slightly off-topic, but I'm curious though; does this mean you can't access a global variable declared in JS from Dart in the same way as a function? (I'm looking at the examples [here](https://pub.dartlang.org/packages/js) though I don't know whether these are up-to-date, it sounded like the JS interop stuff might be changing ... ?)

**Comment by bwilkerson** [comment]
@jacob314 I don't know for sure, but Jacob should be able to answer that. My guess is "yes", but you can always make the variable private and provide a public getter/setter pair.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2196483004/
