### ISSUE TITLE
NativeMessageHandlers are leaked

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#27002]
Reproduced by doing an ASAN build:

https://github.com/dart-lang/sdk/wiki/Debugging-Dart-VM-with-AddressSanitizer

and running any program.

```
==13614==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 216 byte(s) in 1 object(s) allocated from:
    #0 0x5cf3d9 in operator new(unsigned long) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5cf3d9)
    #1 0x6dfbf0 in Dart_NewNativePort (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x6dfbf0)
    #2 0x6fcb4c in dart::bin::Loader::Loader(dart::bin::IsolateData*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x6fcb4c)
    #3 0x702e55 in dart::bin::Loader::LibraryTagHandler(Dart_LibraryTag, _Dart_Handle*, _Dart_Handle*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x702e55)
    #4 0x5e571f in dart::bin::CreateIsolateAndSetupHelper(char const*, char const*, char const*, char const*, Dart_IsolateFlags*, char**, int*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e571f)
    #5 0x5e348a in dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e348a)
    #6 0x5e7b1b in dart::bin::main(int, char**) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e7b1b)
    #7 0x5e934a in main (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e934a)
    #8 0x7f9cf2e74f44 (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x5cf3d9 in operator new(unsigned long) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5cf3d9)
    #1 0xe2db9c in dart::MessageHandler::MessageHandler() (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0xe2db9c)
    #2 0xe3ef28 in dart::NativeMessageHandler::NativeMessageHandler(char const*, void (*)(long, _Dart_CObject*)) /usr/local/google/home/zra/dart/sdk/runtime/vm/native_message_handler.cc:17
    #3 0x6dfc03 in Dart_NewNativePort (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x6dfc03)
    #4 0x6fcb4c in dart::bin::Loader::Loader(dart::bin::IsolateData*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x6fcb4c)
    #5 0x702e55 in dart::bin::Loader::LibraryTagHandler(Dart_LibraryTag, _Dart_Handle*, _Dart_Handle*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x702e55)
    #6 0x5e571f in dart::bin::CreateIsolateAndSetupHelper(char const*, char const*, char const*, char const*, Dart_IsolateFlags*, char**, int*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e571f)
    #7 0x5e348a in dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e348a)
    #8 0x5e7b1b in dart::bin::main(int, char**) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e7b1b)
    #9 0x5e934a in main (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e934a)
    #10 0x7f9cf2e74f44 (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x5cf3d9 in operator new(unsigned long) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5cf3d9)
    #1 0xe2dbd0 in dart::MessageHandler::MessageHandler() (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0xe2dbd0)
    #2 0xe3ef28 in dart::NativeMessageHandler::NativeMessageHandler(char const*, void (*)(long, _Dart_CObject*)) /usr/local/google/home/zra/dart/sdk/runtime/vm/native_message_handler.cc:17
    #3 0x6dfc03 in Dart_NewNativePort (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x6dfc03)
    #4 0x6fcb4c in dart::bin::Loader::Loader(dart::bin::IsolateData*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x6fcb4c)
    #5 0x702e55 in dart::bin::Loader::LibraryTagHandler(Dart_LibraryTag, _Dart_Handle*, _Dart_Handle*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x702e55)
    #6 0x5e571f in dart::bin::CreateIsolateAndSetupHelper(char const*, char const*, char const*, char const*, Dart_IsolateFlags*, char**, int*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e571f)
    #7 0x5e348a in dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e348a)
    #8 0x5e7b1b in dart::bin::main(int, char**) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e7b1b)
    #9 0x5e934a in main (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e934a)
    #10 0x7f9cf2e74f44 (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)

Indirect leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x5c1f08 in strdup (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5c1f08)
    #1 0xe3ef59 in dart::NativeMessageHandler::NativeMessageHandler(char const*, void (*)(long, _Dart_CObject*)) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0xe3ef59)
    #2 0x6dfc03 in Dart_NewNativePort (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x6dfc03)
    #3 0x6fcb4c in dart::bin::Loader::Loader(dart::bin::IsolateData*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x6fcb4c)
    #4 0x702e55 in dart::bin::Loader::LibraryTagHandler(Dart_LibraryTag, _Dart_Handle*, _Dart_Handle*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x702e55)
    #5 0x5e571f in dart::bin::CreateIsolateAndSetupHelper(char const*, char const*, char const*, char const*, Dart_IsolateFlags*, char**, int*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e571f)
    #6 0x5e348a in dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e348a)
    #7 0x5e7b1b in dart::bin::main(int, char**) (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e7b1b)
    #8 0x5e934a in main (/usr/local/google/home/zra/dart/sdk/out/DebugX64/dart+0x5e934a)
    #9 0x7f9cf2e74f44 (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)

SUMMARY: LeakSanitizer: 255 byte(s) leaked in 4 allocation(s).
```

**Comment by johnmccutchan** [comment]
The port isn't leaked (it's cleaned up in Loader::~Loader). The native message handler is leaked which is odd because we don't keep any explicit references to the native message handler. Digging in a bit deeper and it seems that the NativeMessageHandler gives itself a live port count of one but never marks the port as a live port so when we close the live port count is never decrement resulting in the native message handler never being deleted.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2200903002/

**Comment by johnmccutchan** [comment]
Note that this leak affects all native ports

**Comment by johnmccutchan** [comment]
I had to revert my change because it started to hit a race condition (trying to enter a message handler that was deleted).
