### ISSUE TITLE
Errors from cleanupCallback and shutdownLoaders when running test files

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/sdk#27022]
I have attached a simple example containing two test files. When I run "all tests", either in WebStorm or by typing "pub run test tests" at the command line, I get the following error:

```
/Users/shaza/Downloads/dart-sdk/bin/dart --ignore-unrecognized-flags --checked --trace_service_pause_events file:///Users/shaza/Downloads/dart-sdk/bin/snapshots/pub.dart.snapshot run test:test -r json /Users/shaza/GoogleDrive/TMP-mockito-test/mockito-test-example/cat-test
Testing started at 3:45 PM ...
vm-service: Error: Unhandled exception:
No top-level method '_sendResourceResponse' with matching arguments declared.

NoSuchMethodError: incorrect number of arguments passed to method named '_sendResourceResponse'
Receiver: top-level
Tried calling: _sendResourceResponse(SendPort, 1, null, null, "Service shutdown")
Found: _sendResourceResponse(SendPort, int, Uri, Uri, String, dynamic)
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:178)
#1      shutdownLoaders.<anonymous closure> (loader.dart:894:5)
#2      List.forEach (dart:core-patch/growable_array.dart:248)
#3      shutdownLoaders (loader.dart:891:39)
#4      cleanupCallback.<cleanupCallback_async_body> (dart:vmservice_io:44:3)
#5      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Process finished with exit code 0
```

[cat-test.zip](https://github.com/dart-lang/sdk/files/400468/cat-test.zip)

**Comment by mit-mit** [comment]
Not entirely sure where this is happening, initially triaging to VM...

**Comment by johnmccutchan** [comment]
This is an old bug that was fixed in https://github.com/dart-lang/sdk/commit/1033075c36c3908f114bf7e9ad00bbf10157b06c
