### ISSUE TITLE
HOT RELOAD: crash "Cannot forward VM heap objects"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27059]
I got this while using hot reload in Flutter somewhat aggressively:

```
E/DartVM  : ../../dart/runtime/vm/become.cc: 219: error: become: Cannot forward VM heap objects
E/DartVM  : Dumping native stack trace for thread 48b7
E/DartVM  : Stack dump aborted because GetAndValidateIsolateStackBounds.
--------- beginning of crash
W/ActivityManager:   Force finishing activity io.flutter.gallery/org.domokit.sky.shell.SkyActivity
Application finished.
W/ActivityManager: Exception thrown during pause
W/ActivityManager: android.os.DeadObjectException
W/ActivityManager: at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager: at android.os.BinderProxy.transact(Binder.java:503)
W/ActivityManager: at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
W/ActivityManager: at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
W/ActivityManager: at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
W/ActivityManager: at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
W/ActivityManager: at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
W/ActivityManager: at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12042)
W/ActivityManager: at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11938)
W/ActivityManager: at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12627)
W/ActivityManager: at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12134)
W/ActivityManager: at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

Don't have a repro, but will keep an eye out if I see it again.

cc @rmacnak-google @johnmccutchan

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2240663004/ <-- a CL which will dump more information the next time this happens.

**Comment by johnmccutchan** [comment]
I believe we haven't seen this again. I'm closing this.
