### ISSUE TITLE
Precompiler fails with std::bad_alloc when compiling huge functions

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#27087]
When compiling huge functions, we run out of zone memory.

```
(gdb) bt
#0  0xf7fdb440 in __kernel_vsyscall ()
#1  0xf7cbe687 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7cc1ab3 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xf7eee405 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#4  0xf7eec063 in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#5  0xf7eec09f in std::terminate() () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#6  0xf7eec306 in __cxa_throw () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#7  0xf7eec916 in operator new(unsigned int) () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#8  0xf7eec9cb in operator new[](unsigned int) () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#9  0x0845ff09 in New (next=0xffede078, size=65536) at runtime/vm/zone.cc:60
#10 dart::Zone::AllocateExpand (this=this@entry=0xffffb988, size=size@entry=24584) at runtime/vm/zone.cc:135
#11 0x081fd9fc in AllocUnsafe (size=<optimized out>, this=0xffffb988) at runtime/vm/zone.h:240
#12 Alloc<unsigned int> (len=6145, this=0xffffb988) at runtime/vm/zone.h:262
#13 dart::BitVector::BitVector (this=0xffeea0c0, zone=0xffffb988, length=196620) at runtime/vm/bit_vector.h:50
#14 0x083c728d in dart::AliasedSet::EnsureSet (this=0x10466358, sets=0x10466398, alias=123666) at runtime/vm/redundancy_elimination.cc:877
#15 0x083cd143 in dart::AliasedSet::AddRepresentative (this=this@entry=0x10466358, place=0x103491a8) at runtime/vm/redundancy_elimination.cc:792
#16 0x083ce0dd in AliasedSet (phi_moves=<optimized out>, places=0xffd6428, places_map=0xffffb258, zone=0xffffb988, this=0x10466358) at runtime/vm/redundancy_elimination.cc:704
#17 dart::NumberPlaces (graph=graph@entry=0xe944248, map=map@entry=0xffffb258, mode=mode@entry=dart::kOptimizeStores) at runtime/vm/redundancy_elimination.cc:1319
#18 0x083cecd8 in OptimizeGraph (graph=0xe944248, graph@entry=0x0) at runtime/vm/redundancy_elimination.cc:2518
#19 dart::DeadStoreElimination::Optimize (graph=<optimized out>, graph@entry=0xe944248) at runtime/vm/redundancy_elimination.cc:2702
#20 0x083bbcd1 in dart::PrecompileParsedFunctionHelper::Compile (this=this@entry=0xffffb88c, pipeline=pipeline@entry=0x9477a90) at runtime/vm/precompiler.cc:2598
#21 0x083bf09b in dart::PrecompileFunctionHelper (pipeline=pipeline@entry=0x9477a90, function=..., optimized=<optimized out>) at runtime/vm/precompiler.cc:2877
#22 0x083bf836 in dart::Precompiler::CompileFunction (thread=0x8e16268, function=...) at runtime/vm/precompiler.cc:2934
```

**Comment by fsc8000** [comment]
The function in question contains around 200K stores to an array. Our representation of alias sets in the load/store optimizer is quadratic in space, storing a bit vector of length 200K for each place. Possible solutions:

1. Sparse representation of alias sets for places
2. Avoid storing sets for large number of places

@mraleph For now I think I'll just have a cut-off size, to avoid the space explosion.
