### ISSUE TITLE
"substitute2" crash in analyzer server

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27102]
Not sure exactly what I did, but this happened as I was editing code in Flutter's framework and tests:

```
Analyzing Flutter repository...                          
Error from the analysis server: Task failed: InferInstanceMembersInUnitTask for source /usr/local/google/home/ianh/.pub-cache/hosted/pub.dartlang.org/stream_channel-1.5.0/lib/stream_channel.dart
Unexpected exception while performing InferInstanceMembersInUnitTask for source /usr/local/google/home/ianh/.pub-cache/hosted/pub.dartlang.org/stream_channel-1.5.0/lib/stream_channel.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:350)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1231)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1229)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:888)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a method 'substitute2'.

NoSuchMethodError: method not found: 'substitute2'
Receiver: null
Arguments: [_List len:1, _List len:1]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      MethodMember.from (package:analyzer/src/dart/element/member.dart:646)
#3      InterfaceTypeImpl.methods (package:analyzer/src/dart/element/type.dart:1346)
#4      InheritanceManager._recordMapWithClassMembers (package:analyzer/src/dart/resolver/inheritance_manager.dart:627)
#5      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:559)
#6      InheritanceManager.lookupOverrides (package:analyzer/src/dart/resolver/inheritance_manager.dart:193)
#7      InstanceMemberInferrer._inferExecutable (package:analyzer/src/task/strong_mode.dart:261)
#8      List.forEach (dart:core-patch/growable_array.dart:248)
#9      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:230)
#10     InstanceMemberInferrer.inferCompilationUnit.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:93)
#11     List.forEach (dart:core-patch/growable_array.dart:248)
#12     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:91)
#13     InferInstanceMembersInUnitTask.internalPerform (package:analyzer/src/task/dart.dart:3506)
#14     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:338)
#15     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#16     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#17     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#18     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1231)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#20     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1229)
#21     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#22     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:888)
#23     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#24     _rootRun (dart:async/zone.dart:1146)
#25     _CustomZone.run (dart:async/zone.dart:1026)
#26     _CustomZone.runGuarded (dart:async/zone.dart:924)
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#28     _rootRun (dart:async/zone.dart:1150)
#29     _CustomZone.run (dart:async/zone.dart:1026)
#30     _CustomZone.runGuarded (dart:async/zone.dart:924)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#32     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#33     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#34     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
We have a `ClassElement` containing a `MethodElement` and the method's type is `null`. I can't tell from the stack trace why this would be.

**Comment by devoncarew** [comment]
assumed stale
