### ISSUE TITLE
gclient sync error

### ISSUE THREAD

**Issue by vynes** [dart-lang/sdk#27122]
I'm using Gentoo, Python 2.7.

When doing `gclient sync` I get this error:

Syncing projects:  98% (88/89), done.                                     

_________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --recursive --directory sdk/third_party/d8' in '/home/me/SDK/dart'
Traceback (most recent call last):
  File "/usr/bin/gclient", line 10, in <module>
    sys.exit(gclient.Main(sys.argv[1:]))
  File "/usr/lib64/python2.7/site-packages/depot_tools/gclient.py", line 2000, in Main
    return dispatcher.execute(OptionParser(), argv)
  File "/usr/lib64/python2.7/site-packages/depot_tools/subcommand.py", line 245, in execute
    return command(parser, args[1:])
  File "/usr/lib64/python2.7/site-packages/depot_tools/gclient.py", line 1778, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/usr/lib64/python2.7/site-packages/depot_tools/gclient.py", line 1305, in RunOnDeps
    self.RunHooksRecursively(self._options)
  File "/usr/lib64/python2.7/site-packages/depot_tools/gclient.py", line 850, in RunHooksRecursively
    hook, cwd=self.root.root_dir, always=True)
  File "/usr/lib64/python2.7/site-packages/depot_tools/gclient_utils.py", line 281, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/depot_tools/gclient_utils.py", line 476, in CheckCallAndFilter
    **kwargs)
  File "/usr/lib64/python2.7/site-packages/depot_tools/subprocess2.py", line 253, in __init__
    % (str(e), kwargs.get('cwd'), args[0]))
OSError: Execution failed with error: [Errno 2] No such file or directory.
Check that /home/me/SDK/dart or download_from_google_storage exist and have execution permission.

**Comment by whesse** [comment]
Could it be that your depot_tools is not up to date?  I have never seen it located in site-packages before, just in a standalone directory on my path.  If depot_tools is up to date, is the download_from_google_storage.py in the depot_tools directory, and on the path?

Also, does your checkout of the gclient repository in /home/me/SDK/dart check out the github.com/dart-lang/sdk repo into a subdirectory called sdk, or into the directory called dart?  It should be in a directory called sdk.  Check that /home/me/SDK/dart/sdk/third_party/d8 exists and contains "linux", "windows", "macos" directories and README.google.

**Comment by vynes** [comment]
I was using gclient standalone, not from depot_tools. All is well now, thank you.

**Comment by zhongh3** [comment]
This is likely the duplicate of #32702.
