### ISSUE TITLE
Analysis Server - Task failed: InferInstanceMembersInUnitTask when editing analysis_options.yaml

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27186]
When making changes to `analysis_options.yaml` I sometimes get an error like this...

I had pasted all the lints in from the website and was going through commenting some out. This happens when I hit save after changing:

```yaml
    - always_specify_types
```

to 

```yaml
    # - always_specify_types
```

```text
{"event":"server.error","params":{"isFatal":false,"message":"Task failed: InferInstanceMembersInUnitTask for source M:\\Apps\\DartPubCache\\hosted\\pub.dartlang.org\\html-0.13.0\\lib\\dom.dart","stackTrace":"

Unexpected exception while performing InferInstanceMembersInUnitTask for source M:\\Apps\\DartPubCache\\hosted\\pub.dartlang.org\\html-0.13.0\\lib\\dom.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:350)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1231)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1229)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:889)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     ...
```

**Comment by scheglov** [comment]
Cannot reproduce.

**Comment by DanTup** [comment]
Sorry, been super busy lately and haven't been able to try this. It's still sat in my list; if I can repro in the latest SDK when I get some time (which might not be for a while) I'll get better details/repro case.
