### ISSUE TITLE
dart2js crash on: tools/test.py -mrelease -cdart2js -rd8 --fast-startup --checked -t120 co19/Language/Types/Parameterized_Types/Actual_Type_of_Declaration/actual_type_t05

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#27198]
We appear to be generating a TypeInfoExpression containing a type variable but no corresponding input.

```
tests/co19/src/Language/Types/Parameterized_Types/Actual_Type_of_Declaration/actual_type_t05.dart:22:1:
Internal Error: The compiler crashed when compiling this element.
main() {
^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:153)
#1      SsaCodeGenerator.visitTypeInfoExpression.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:2905:68)
#2      TypeRepresentationGenerator.visitTypeVariableType (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:797:22)
#3      TypeVariableType.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/dart_types.dart:233:20)
#4      TypeRepresentationGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:794:37)
#5      TypeRepresentationGenerator.getTypeRepresentation (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:783:39)
#6      _RuntimeTypesEncoder.getTypeRepresentation (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:608:36)
#7      SsaCodeGenerator.visitTypeInfoExpression (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:2904:51)
#8      HTypeInfoExpression.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/nodes.dart:3306:39)
#9      SsaCodeGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:608:10)
#10     SsaCodeGenerator.visitExpression (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:614:5)
#11     SsaCodeGenerator.use (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:595:7)
#12     SsaCodeGenerator.visitTypeInfoExpression (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:2897:7)
#13     HTypeInfoExpression.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/nodes.dart:3306:39)
#14     SsaCodeGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:608:10)
#15     SsaCodeGenerator.visitExpression (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:614:5)
#16     SsaCodeGenerator.use (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:595:7)
#17     SubtypeCheckedModeHelper.generateAdditionalArguments (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/checked_mode_helpers.dart:134:13)
#18     CheckedModeHelper.generateCall (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/checked_mode_helpers.dart:36:5)
#19     SsaCodeGenerator.visitTypeConversion (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:2804:19)
#20     HTypeConversion.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2827:39)
#21     SsaCodeGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:608:10)
#22     SsaCodeGenerator.visitStatement (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:620:5)
#23     SsaCodeGenerator.define (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:589:7)
#24     SsaCodeGenerator.iterateBasicBlock (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1234:9)
#25     SsaCodeGenerator.visitBasicBlock (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1124:5)
#26     SsaCodeGenerator.visitGoto (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1381:5)
#27     HGoto.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2136:39)
#28     SsaCodeGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:608:10)
#29     SsaCodeGenerator.iterateBasicBlock (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1239:5)
#30     SsaCodeGenerator.visitBasicBlock (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1124:5)
#31     SsaCodeGenerator.visitGraph (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:322:5)
#32     SsaCodeGeneratorTask.generateMethod.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:88:15)
#33     CompilerTask.measure (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#34     SsaCodeGeneratorTask.generateMethod (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:82:12)
#35     SsaCodeGeneratorTask.generateCode (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:64:14)
#36     SsaFunctionCompiler.compile (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/ssa.dart:43:38)
#37     JavaScriptBackend.codegen (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/backend.dart:1624:43)
#38     Compiler.codegen (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:957:20)
#39     CodegenWorkItem.run (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/codegen.dart:251:21)
#40     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:829:52)
#41     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#42     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:828:34)
#43     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#44     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:825:30)
#45     CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:1625:15)
#46     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:823:20)
#47     QueueFilter.processWorkItem (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/enqueue.dart:954:6)
#48     Enqueuer.forEach (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/enqueue.dart:645:16)
#49     Compiler.emptyQueue.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:822:15)
#50     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#51     Compiler.emptyQueue (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:821:16)
#52     Compiler.processQueue.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:858:9)
#53     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#54     Compiler.processQueue (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:835:16)
#55     Compiler.compileLoadedLibraries.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:743:9)
#56     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#57     Compiler.compileLoadedLibraries (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:637:16)
#58     Compiler.runInternal.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:547:7)
#59     _RootZone.runUnary (dart:async/zone.dart:1404)
#60     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#61     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#62     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#63     _Future._completeWithValue (dart:async/future_impl.dart:477)
#64     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)



Command[dart2js]: DART_CONFIGURATION=ReleaseX64 sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --enable-checked-mode --allow-mock-compilation --categories=all --fast-startup --package-root=out/ReleaseX64/packages/ /usr/local/google/home/sra/Dart/sdk/tests/co19/src/Language/Types/Parameterized_Types/Actual_Type_of_Declaration/actual_type_t05.dart --out=/usr/local/google/home/sra/Dart/sdk/out/ReleaseX64/generated_compilations/dart2js-checked/tests_co19_src_Language_Types_Parameterized_Types_Actual_Type_of_Declaration_actual_type_t05/out.js
Took 0:00:02.256432

Command[d8]: DART_CONFIGURATION=ReleaseX64 /usr/local/google/home/sra/Dart/sdk/third_party/d8/linux/d8 /usr/local/google/home/sra/Dart/sdk/sdk/lib/_internal/js_runtime/lib/preambles/d8.js /usr/local/google/home/sra/Dart/sdk/out/ReleaseX64/generated_compilations/dart2js-checked/tests_co19_src_Language_Types_Parameterized_Types_Actual_Type_of_Declaration_actual_type_t05/out.js
Did not run

Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2js -rd8 --fast-startup --checked -t120 co19/Language/Types/Parameterized_Types/Actual_Type_of_Declaration/actual_type_t05
```

**Comment by rakudrama** [comment]
This test is no longer failing.
