### ISSUE TITLE
dart2js crash with typedef types as type parameters

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#27199]
This is a recent regression. Compile with `--checked`.

```dart
typedef Iterable<T> ItemListFilter<T>(Iterable<T> items);

class C<T> {
  Map<String, ItemListFilter<T>> ff = {};
}

main() {
  print(new C());
}
```

```
Internal Error: The compiler crashed when compiling this element.
  Map<String, ItemListFilter<T>> ff = {};
                                 ^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:153)
#1      SsaCodeGenerator.visitTypeInfoExpression.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:2906:31)
#2      TypeRepresentationGenerator.visitTypeVariableType (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:797:22)
#3      TypeVariableType.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/dart_types.dart:233:20)
#4      TypeRepresentationGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:794:37)
#5      TypeRepresentationGenerator.visitList (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:815:34)
#6      TypeRepresentationGenerator.visitInterfaceType (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:806:37)
#7      InterfaceType.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/dart_types.dart:552:20)
#8      TypeRepresentationGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:794:37)
#9      TypeRepresentationGenerator.visitList (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:815:34)
#10     TypeRepresentationGenerator.visitFunctionType (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:857:11)
#11     FunctionType.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/dart_types.dart:730:20)
#12     TypeRepresentationGenerator.visitTypedefType (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:903:28)
#13     TypedefType.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/dart_types.dart:873:20)
#14     TypeRepresentationGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:794:37)
#15     TypeRepresentationGenerator.getTypeRepresentation (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:783:39)
#16     _RuntimeTypesEncoder.getTypeRepresentation (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:608:36)
#17     SsaCodeGenerator.visitTypeInfoExpression (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:2902:51)
#18     HTypeInfoExpression.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/nodes.dart:3306:39)
#19     SsaCodeGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:608:10)
#20     SsaCodeGenerator.visitExpression (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:614:5)
#21     SsaCodeGenerator.use (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:595:7)
#22     SsaCodeGenerator.visitTypeInfoExpression (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:2895:7)
#23     HTypeInfoExpression.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/nodes.dart:3306:39)
#24     SsaCodeGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:608:10)
#25     SsaCodeGenerator.visitExpression (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:614:5)
#26     SsaCodeGenerator.use (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:595:7)
#27     SubtypeCheckedModeHelper.generateAdditionalArguments (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/checked_mode_helpers.dart:134:13)
#28     CheckedModeHelper.generateCall (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/checked_mode_helpers.dart:36:5)
#29     SsaCodeGenerator.visitTypeConversion (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:2804:19)
#30     HTypeConversion.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2827:39)
#31     SsaCodeGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:608:10)
#32     SsaCodeGenerator.visitExpression (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:614:5)
#33     SsaCodeGenerator.use (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:595:7)
#34     SsaCodeGenerator.visitFieldSet (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1867:5)
#35     HFieldSet.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/nodes.dart:1736:39)
#36     SsaCodeGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:608:10)
#37     SsaCodeGenerator.visitStatement (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:620:5)
#38     SsaCodeGenerator.define (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:589:7)
#39     SsaCodeGenerator.iterateBasicBlock (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1234:9)
#40     SsaCodeGenerator.visitBasicBlock (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1124:5)
#41     SsaCodeGenerator.visitGoto (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1381:5)
#42     HGoto.accept (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2136:39)
#43     SsaCodeGenerator.visit (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:608:10)
#44     SsaCodeGenerator.iterateBasicBlock (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1239:5)
#45     SsaCodeGenerator.visitBasicBlock (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1124:5)
#46     SsaCodeGenerator.visitGraph (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:322:5)
#47     SsaCodeGeneratorTask.generateLazyInitializer.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:75:15)
#48     CompilerTask.measure (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#49     SsaCodeGeneratorTask.generateLazyInitializer (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:69:12)
#50     SsaCodeGeneratorTask.generateCode (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:62:14)
#51     SsaFunctionCompiler.compile (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/ssa.dart:43:38)
#52     JavaScriptBackend.codegen (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/backend.dart:1624:43)
#53     Compiler.codegen (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:957:20)
#54     CodegenWorkItem.run (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/codegen.dart:251:21)
#55     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:829:52)
#56     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#57     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:828:34)
#58     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#59     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:825:30)
#60     CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:1625:15)
#61     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:823:20)
#62     QueueFilter.processWorkItem (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/enqueue.dart:954:6)
#63     Enqueuer.forEach (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/enqueue.dart:645:16)
#64     Compiler.emptyQueue.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:822:15)
#65     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#66     Compiler.emptyQueue (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:821:16)
#67     Compiler.processQueue.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:858:9)
#68     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#69     Compiler.processQueue (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:835:16)
#70     Compiler.compileLoadedLibraries.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:743:9)
#71     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#72     Compiler.compileLoadedLibraries (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:637:16)
#73     Compiler.runInternal.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:547:7)
#74     _RootZone.runUnary (dart:async/zone.dart:1404)
#75     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#76     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#77     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#78     _Future._completeWithValue (dart:async/future_impl.dart:477)
#79     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#80     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#81     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#82     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#83     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by rakudrama** [comment]
Fix available: https://codereview.chromium.org/2285373003
