### ISSUE TITLE
Isolate spawn_A04_t03 test is flaky and failing

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27202]
The test co19/LibTest/isolate/Isolate/spawn_A04_t03 is flaking on the VM on all platforms, and consistently failing on Windows, simmips, and simarm.

Error on windows and on simmips are identical:
```
stderr:
Unhandled exception:
Expect.equals(expected: <ping>, actual: <timeout>) fails.
#0      _fail (file:///E:/b/build/slave/vm-win-debug-x64-be/build/sdk/tests/co19/src/Utils/expect.dart:17:5)
#1      Expect.equals (file:///E:/b/build/slave/vm-win-debug-x64-be/build/sdk/tests/co19/src/Utils/expect_common.dart:27:5)
#2      test.<test_async_body> (file:///E:/b/build/slave/vm-win-debug-x64-be/build/sdk/tests/co19/src/LibTest/isolate/Isolate/spawn_A04_t03.dart:44:12)
#3      _RootZone.runUnary (dart:async/zone.dart:1404)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#
```

**Comment by floitschG** [comment]
Test should be updated: https://github.com/dart-lang/co19/issues/76
