### ISSUE TITLE
Many co19 isolate tests failing on Dartium

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27219]
The following new tests are failing on Dartium:
co19/LibTest/isolate/Isolate/spawnUri_A01_t06
co19/LibTest/isolate/Isolate/spawnUri_A01_t07
co19/LibTest/isolate/Isolate/spawnUri_A02_t01
co19/LibTest/isolate/Isolate/spawn_A01_t06
co19/LibTest/isolate/Isolate/spawn_A02_t02
co19/LibTest/isolate/Isolate/spawn_A03_t01
co19/LibTest/isolate/Isolate/spawn_A03_t02
co19/LibTest/isolate/Isolate/spawn_A03_t03
co19/LibTest/isolate/Isolate/spawn_A03_t04
co19/LibTest/isolate/Isolate/spawn_A04_t01
co19/LibTest/isolate/Isolate/spawn_A04_t02
co19/LibTest/isolate/Isolate/spawn_A04_t03
co19/LibTest/isolate/Isolate/spawn_A04_t04
co19/LibTest/isolate/Isolate/spawn_A04_t05
co19/LibTest/isolate/Isolate/spawn_A05_t01
co19/LibTest/isolate/Isolate/spawn_A05_t02
co19/LibTest/isolate/Isolate/spawn_A05_t03
co19/LibTest/isolate/Isolate/spawn_A06_t01
co19/LibTest/isolate/Isolate/spawn_A06_t02
co19/LibTest/isolate/Isolate/spawn_A06_t03
co19/LibTest/isolate/Isolate/spawn_A06_t04
co19/LibTest/isolate/Isolate/spawn_A06_t05
co19/LibTest/isolate/Isolate/spawn_A06_t06
co19/LibTest/isolate/Isolate/spawn_A06_t07

They are suppressed by lines in status file tests/co19/co19-dartium.status.

**Comment by whesse** [comment]
Error is: 
 http://127.0.0.1:49600/root_build/generated_tests/none-dartium/tests_co19_src_LibTest_isolate_Isolate_spawn_A06_t07/test.html?crossOriginPort=49601:1:
                    Uncaught Unhandled exception:
                    Unsupported operation: Isolate.spawn
                    #0      Isolate.spawn.<spawn_async_body> (dart:isolate-patch/isolate_patch.dart:325)
                    #1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)

So perhaps this is working as intended - isolate.spawn is unsupported.
