### ISSUE TITLE
Analysis server crashes on import of file named `con` on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27243]
On Windows there are a bunch of names you're not allowed to have as files:

https://support.microsoft.com/en-us/kb/74496

The analysis server crashes if you have any of these in `import`/`part` statements. This means if you try to type `import 'container.dart'` but your auto-complete inserts the quotes such that you end up with `import 'con'` during typing, you still hit the crash.

This can be reproduced by setting the analysis root to a folder that has a single dart file with the following content:

```dart
import 'con';
```

Here's what the log looks like:

```text
[21:02:03]: ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
[21:02:03]: ==> {"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["c:\\Users\\danny\\Desktop\\DartCrash"],"excluded":[]}}
[21:02:03]: ==> {"id":"3","method":"analysis.updateContent","params":{"files":{"c:\\Users\\danny\\Desktop\\DartCrash\\test.dart":{"type":"add","content":"import 'con';"}}}}
[21:02:03]: ==> {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["c:\\Users\\danny\\Desktop\\DartCrash\\test.dart"]}}
[21:02:04]: <== {"event":"server.connected","params":{"version":"1.15.0","pid":5004}}
[21:02:04]: <== {"id":"1"}
[21:02:04]: <== {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
[21:02:04]: <== {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
[21:02:04]: <== {"id":"2"}
[21:02:04]: <== {"id":"3","result":{}}
[21:02:04]: <== {"id":"4"}
[21:02:04]: <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[21:02:04]: <== {"event":"analysis.errors","params":{"file":"c:\\Users\\danny\\Desktop\\DartCrash\\test.dart","errors":[]}}
```

Nothing is ever received after this point.

**Comment by DanTup** [comment]
FWIW, I tried starting with Observatory as discussed but I couldn't get any more info. The isolate is listed but when I click on it I get a completely blank page. The bit that says "Loading..." on the left window also never seems to finish and the Debug link goes to a page that says "No stack" and "No pending messages".

![Observatory](https://cloud.githubusercontent.com/assets/1078012/18230336/50c14d84-728f-11e6-83c7-2ee2f1f71cc8.png)

**Comment by scheglov** [comment]
Works for me in `1.20.0-dev.1.0 (Tue Aug 30 01:38:36 2016) on "windows_ia32"`.

For the following code
```dart
import 'con';
import 'package:path/path.dart';

main() {
  join('');
}
```
I get an error `ERROR: Target of URI does not exist: 'con' ([test] bin\test.dart:2)`, but otherwise analysis of this file works fine - I get completion and other errors.

I think that with changes https://github.com/dart-lang/sdk/commit/ed887c09d1d1b3c99bf56f6b9fc719808442c0be and  https://github.com/dart-lang/sdk/commit/6cceb72ea753cdd190c9e87449a1a1ad8fe32262 the problem should not happen.

What version of Dart SDK do you use?

**Comment by DanTup** [comment]
I'm using 1.19. I'll try and grab a 1.20 dev later and re-test with that.

It literally only needed the first line of your sample to fail for me!

**Comment by scheglov** [comment]
And I use `Windows 7 x64`.
I wonder if behavior is different for `Windows 8`.
It works for me even using `1.19.0 (Fri Aug 26 02:33:42 2016) on "windows_ia32"`.

I used a bigger sample mostly to check that other things work.

**Comment by DanTup** [comment]
I'm still seeing this behaviour on `1.20.0-dev.1.0`:

```text
[21:50:58]: ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
[21:50:58]: ==> {"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["c:\\Users\\danny\\Desktop\\DartCrash"],"excluded":[]}}
[21:50:58]: ==> {"id":"3","method":"analysis.updateContent","params":{"files":{"c:\\Users\\danny\\Desktop\\DartCrash\\test.dart":{"type":"add","content":"import 'con';"}}}}
[21:50:58]: ==> {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["c:\\Users\\danny\\Desktop\\DartCrash\\test.dart"]}}
[21:50:59]: <== {"event":"server.connected","params":{"version":"1.15.0","pid":1700}}
[21:50:59]: <== {"id":"1"}
[21:50:59]: <== {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
[21:50:59]: <== {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
[21:50:59]: <== {"id":"2"}
[21:50:59]: <== {"id":"3","result":{}}
[21:50:59]: <== {"id":"4"}
[21:50:59]: <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[21:50:59]: <== {"event":"analysis.errors","params":{"file":"c:\\Users\\danny\\Desktop\\DartCrash\\test.dart","errors":[]}}
[21:51:00]: ==> {"id":"5","method":"completion.getSuggestions","params":{"file":"c:\\Users\\danny\\Desktop\\DartCrash\\test.dart","offset":13}}
[21:51:02]: ==> {"id":"6","method":"completion.getSuggestions","params":{"file":"c:\\Users\\danny\\Desktop\\DartCrash\\test.dart","offset":13}}
```

Behaviour of Observatory is the same as above - clicking the isolate renders a white page.

I'm on Windows 10 x64 though the report came to me from someone using Windows 8.1 x64. Issues with using filenames like `con` are older than Windows 8 though, I'm surprised you're not seeing it :(

**Comment by scheglov** [comment]
Yeah, I know that special names cannot be used as names of files in DOS or Windows.
I run Windows in VMWare on Mac, don't know if it matters.

The Observatory problem is suspicious.
Maybe VM get into a state when it cannot handle other IO or something.

For example the Dart code below works fine for me - it shows an exception, an then it still able to print.
```dart
import 'dart:io';

main() {
  try {
    new File('con').readAsStringSync();
  } on Exception catch (e, st) {
    print(e);
    print(st);
    // TODO
  }
  print(42);
}
```

  Does it work for you?

```
C:\dart32\dart-sdk-1.19\bin\dart.exe --ignore-unrecognized-flags --checked --enable-vm-service:49993 --trace_service_pause_events C:\Users\scheglov\dart\test\bin\test_io.dart
Observatory listening on http://127.0.0.1:49993
FileSystemException: readSync failed, path = 'con' (OS Error: Недостаточно памяти для обработки команды.
, errno = 8)
#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:684)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:481)
#2      _File.readAsStringSync (dart:io/file_impl.dart:507)
#3      main (file:///C:/Users/scheglov/dart/test/bin/test_io.dart:5:21)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

42

Process finished with exit code 0
```

**Comment by DanTup** [comment]
I've shut the PC down now but I'll try and do some more digging tomorrow evening and give you code above a test.

**Comment by DanTup** [comment]
@scheglov For me (Win 10, x64) your sample program hangs:

![Hang](https://cloud.githubusercontent.com/assets/1078012/18320835/66ddc494-7523-11e6-9d9e-98f830659455.png)

Trying to Pause the debugger doesn't do anything.

**Comment by DanTup** [comment]
Same with the flags you had:

![Hang 2](https://cloud.githubusercontent.com/assets/1078012/18320916/befceca4-7523-11e6-870e-a2dad33b782a.png)

**Comment by scheglov** [comment]
Well, that explains why Analysis Server stops responding.
It looks as a VM issue.

**Comment by DanTup** [comment]
@scheglov If Windows treats "con" as a console, the behaviour is somewhat expected - it never gets EOF from the console and therefore just sits there. Could be valid for someone to write code to do this? I guess it depends on whether reading something like "con" using `readAsStringSync` on Windows is considered valid or should generate an error.

Though obviously in the context of the analysis server this obviously doesn't make sense :-/

**Comment by scheglov** [comment]
That's fair.
I guess we need to ban reading from Windows device drivers.

Although the problem is more serious - what if someone attempts to read from `/dev/something` which is also does not have `EOF`? And in general case any file can potentially block on reading for unlimited time. :-(

**Comment by scheglov** [comment]
https://codereview.chromium.org/2324513002

We decided that we cannot and should protect against all possible problems.
But still want to guard the ones which cause actual problems for users.

**Comment by DanTup** [comment]
With this fix, will the analysis server throw an exception when you're typing `container.dart` into an import? Or is the exception handled?

**Comment by bwilkerson** [comment]
It will act as if the file doesn't exist. So, it will throw an exception, but the exception will be handled just like entering any other invalid name would be.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/c1cd58ce29c64874ee395876aab15a392d2ccf6d

**Comment by DanTup** [comment]
Great; thanks! :+1:

**Comment by DanTup** [comment]
Tested on `1.20.0-dev.4.0` and everything works as expected; thanks!
