### ISSUE TITLE
Assertion failure in VerifyCanonicalVisitor

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#27364]
Repro is running with --optimization-counter-threshold=5 in DEBUG mode. @a-siva 

```
gdb --args out/DebugX64/dart --short_socket_read --short_socket_write --optimization-counter-threshold=5 --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ tests/standalone/io/socket_close_test.dart
```

```
runtime/vm/verifier.cc: 97: error: expected: instanceHandle_.CheckIsCanonical(thread_)
```

```
(gdb) bt
#0  0x00007ffff6c01c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6c05028 in __GI_abort () at abort.c:89
#2  0x0000000000858a59 in dart::OS::Abort () at runtime/vm/os_linux.cc:416
#3  0x00000000005c350f in dart::DynamicAssertionHelper::Fail (this=this@entry=0x7fffd7a08200, format=format@entry=0xba21a4 "expected: %s") at runtime/platform/assert.cc:43
#4  0x0000000000983cd6 in dart::VerifyCanonicalVisitor::VisitObject (this=0x7fffd7a08410, obj=<optimized out>) at runtime/vm/verifier.cc:97
#5  0x00000000008604b1 in dart::HeapPage::VisitObjects (this=<optimized out>, visitor=visitor@entry=0x7fffd7a08410) at runtime/vm/pages.cc:84
#6  0x0000000000861018 in dart::PageSpace::VisitObjects (this=this@entry=0x7fffc4022828, visitor=visitor@entry=0x7fffd7a08410) at runtime/vm/pages.cc:606
#7  0x000000000070e189 in dart::Heap::IterateOldObjects (this=this@entry=0x7fffc4022710, visitor=visitor@entry=0x7fffd7a08410) at runtime/vm/heap.cc:250
#8  0x000000000070e2a1 in dart::Heap::IterateObjects (this=0x7fffc4022710, visitor=visitor@entry=0x7fffd7a08410) at runtime/vm/heap.cc:244
#9  0x0000000000778932 in dart::ShutdownIsolate (parameter=140736481725216) at runtime/vm/isolate.cc:1506
#10 0x00000000007adb2d in dart::MessageHandler::TaskCallback (this=0x7fffc4026a90) at runtime/vm/message_handler.cc:422
#11 0x00000000007ae47a in dart::MessageHandlerTask::Run (this=0x7fffe8037b70) at runtime/vm/message_handler.cc:29
#12 0x0000000000973c41 in dart::ThreadPool::Worker::Loop (this=this@entry=0x7fffd8003080) at runtime/vm/thread_pool.cc:407
#13 0x00000000009741f4 in dart::ThreadPool::Worker::Main (args=140736817279104) at runtime/vm/thread_pool.cc:464
#14 0x000000000085a963 in dart::ThreadStart (data_ptr=<optimized out>) at runtime/vm/os_thread_linux.cc:123
#15 0x00007ffff7bc4184 in start_thread (arg=0x7fffd7a09700) at pthread_create.c:312
#16 0x00007ffff6cc537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by fsc8000** [comment]
Another related assertion failure is with closures:
```
stderr:
runtime/vm/object.cc: 4360: error: expected: obj.IsCanonical()
Dumping native stack trace for thread 7f8b
  [0x00000000008b61bd] dart::Profiler::DumpStackTrace(bool)
  [0x00000000008b61bd] dart::Profiler::DumpStackTrace(bool)
  [0x00000000005cb30d] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x0000000000841c9b] dart::CanonicalInstanceKey::Matches(dart::Instance const&) const
  [0x0000000000842a24] long dart::HashTable<dart::CanonicalInstanceTraits, 0l, 0l>::FindKey<dart::CanonicalInstanceKey>(dart::CanonicalInstanceKey const&) const
  [0x00000000007c774f] dart::Class::LookupCanonicalInstance(dart::Zone*, dart::Instance const&) const
  [0x0000000000803fa9] dart::Instance::CheckAndCanonicalize(dart::Thread*, char const**) const
  [0x0000000000872042] dart::Parser::EvaluateConstExpr(dart::TokenPosition, dart::AstNode*)
  [0x000000000087c3eb] dart::Parser::FoldConstExpr(dart::TokenPosition, dart::AstNode*)
  [0x0000000000872a26] dart::Parser::ParseExpr(bool, bool)
  [0x0000000000879643] dart::Parser::ParseActualParameters(dart::ArgumentListNode*, bool)
  [0x000000000086f555] dart::Parser::ParseNewOperator(dart::Token::Kind)
  [0x0000000000871285] dart::Parser::ParsePrimary()
  [0x00000000008a3d34] dart::Parser::ParsePostfixExpr()
  [0x00000000008a1778] dart::Parser::ParseUnaryExpr()
  [0x0000000000879f00] dart::Parser::ParseBinaryExpr(int)
  [0x000000000087bbd6] dart::Parser::ParseConditionalExpr()
  [0x0000000000872883] dart::Parser::ParseExpr(bool, bool)
  [0x0000000000881c89] dart::Parser::ParseAwaitableExpr(bool, bool, dart::SequenceNode**)
  [0x0000000000894951] dart::Parser::ParseVariableDeclaration(dart::AbstractType const&, bool, bool, dart::SequenceNode**)
  [0x0000000000894eb1] dart::Parser::ParseVariableDeclarationList()
  [0x0000000000896f15] dart::Parser::ParseStatement()
  [0x0000000000880222] dart::Parser::ParseStatementSequence()
  [0x000000000086ad95] dart::Parser::ParseFunc(dart::Function const&, bool)
  [0x000000000086859e] dart::Parser::ParseFunction(dart::ParsedFunction*)
  [0x0000000000654cd1] dart::DartCompilationPipeline::ParseFunction(dart::ParsedFunction*)
  [0x0000000000659e84] Unknown symbol
  [0x000000000065aba1] dart::Compiler::EnsureUnoptimizedCode(dart::Thread*, dart::Function const&)
  [0x00000000007ce7b9] dart::Function::EnsureHasCompiledUnoptimizedCode() const
  [0x000000000078653b] dart::IsolateReloadContext::EnsuredUnoptimizedCodeForStack()
  [0x0000000000784ebe] dart::IsolateReloadContext::Reload(bool)
  [0x000000000077bf28] dart::Isolate::ReloadSources(dart::JSONStream*, bool, bool)
  [0x000000000064b157] dart::DRT_StackOverflow(dart::NativeArguments)
  [0x00007fb42692d4dc] Unknown symbol
  [0x00007fb42446a4cd] Unknown symbol
  [0x00007fb424487df3] Unknown symbol
  [0x00007fb424cb2674] Unknown symbol
  [0x00007fb424485a62] Unknown symbol
  [0x00007fb4244876ac] Unknown symbol
  [0x00007fb424487416] Unknown symbol
  [0x00007fb424cb2674] Unknown symbol
  [0x00007fb424486fe7] Unknown symbol
  [0x00007fb42448ac3d] Unknown symbol
  [0x00007fb424460fd1] Unknown symbol
  [0x00007fb4244609a6] Unknown symbol
  [0x00007fb424ce01f8] Unknown symbol
  [0x00007fb424cd7591] Unknown symbol
  [0x00007fb424cdef75] Unknown symbol
  [0x00007fb424cb2674] Unknown symbol
  [0x00007fb424cdec06] Unknown symbol
  [0x00007fb42692d9d7] Unknown symbol
  [0x0000000000673040] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&)
  [0x0000000000672daa] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
  [0x0000000000675cb7] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  [0x0000000000778681] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x00000000007a91e3] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x00000000007a9856] dart::MessageHandler::TaskCallback()
  [0x00000000007aa2f9] dart::MessageHandlerTask::Run()
-- End of DumpStackTrace
```

**Comment by johnmccutchan** [comment]
@fsc8000 Can you update the status of this bug?

**Comment by fsc8000** [comment]
This specific issue is fixed. There is stricter verification code that is currently disabled. But that seems like a different issue.
