### ISSUE TITLE
NPE from the analysis server, in analyzer/src/summary/package_bundle_reader.dart

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#27362]
This is for SDK version `1.20.0-dev.1.0`, so could be a bit out of date.

```
Dart analysis server, SDK version 1.20.0-dev.1.0, server version 1.15.0, FATAL error: Failed to perform operation: Instance of 'PerformAnalysisOperation'
The null object does not have a getter 'lineStarts'.

NoSuchMethodError: method not found: 'lineStarts'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ResynthesizerResultProvider.compute (package:analyzer/src/summary/package_bundle_reader.dart:237)
#3      SdkSummaryResultProvider.compute (package:analyzer/src/summary/summary_sdk.dart:45)
#4      AnalysisContextImpl.aboutToComputeResult.<anonymous closure> (package:analyzer/src/context/context.dart:569)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.aboutToComputeResult (package:analyzer/src/context/context.dart:567)
#7      WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:746)
#8      _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:879)
#9      CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:414)
#10     WorkOrder.moveNext.<anonymous closure> (package:analyzer/src/task/driver.dart:845)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#12     WorkOrder.moveNext (package:analyzer/src/task/driver.dart:837)
#13     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:253)
```

**Comment by devoncarew** [comment]
I'm not seeing this with `Dart 1.20.0-dev.5.0`, however it may be intermittent. I'll report back if I see it again.

@pq, Flutter is on `1.20.0-dev.1.0` (the version I saw this issue on).

**Comment by pq** [comment]
@devoncarew: Looking at a fresh roll now; stay tuned!

**Comment by devoncarew** [comment]
Cool, will close this out.
