### ISSUE TITLE
Class 'ParameterElementForLink_VariableSetter' has no instance getter 'isCovariant'.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27367]
Linking of summaries is broken.

FYI @stereotype441 @jmesserly 

```
Unhandled exception:
Class 'ParameterElementForLink_VariableSetter' has no instance getter 'isCovariant'.

NoSuchMethodError: method not found: 'isCovariant'
Receiver: Instance of 'ParameterElementForLink_VariableSetter'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ParameterElementForLink_VariableSetter.noSuchMethod (package:analyzer/src/summary/link.dart:4012:60)
#3      InstanceMemberInferrer._inferExecutable.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:312:41)
#4      Object&ListMixin.any (dart:collection/list.dart:115)
#5      InstanceMemberInferrer._inferExecutable (package:analyzer/src/task/strong_mode.dart:310:55)
#6      List.forEach (dart:core-patch/growable_array.dart:258)
#7      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:223:32)
#8      InstanceMemberInferrer.inferCompilationUnit.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:93:9)
#9      List.forEach (dart:core-patch/growable_array.dart:258)
#10     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:91:16)
#11     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1244:12)
#12     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3485:12)
#13     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3260:15)
#14     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3182:7)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:1819:13)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:1785:24)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:1785:24)
#18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:1838:18)
#19     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3225:42)
#20     Linker.link (package:analyzer/src/summary/link.dart:3709:35)
#21     relink (package:analyzer/src/summary/link.dart:126:57)
#22     link (package:analyzer/src/summary/link.dart:107:3)
#23     _Builder.build (package:analyzer/src/summary/summary_file_builder.dart:95:45)
#24     SummaryBuilder.build (package:analyzer/src/summary/summary_file_builder.dart:72:70)
#25     _buildSummary (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/tool/summary/build_sdk_summaries.dart:58:64)
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/2342883004

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/3f264975f8c613860f323723a83500792c224d4d
