### ISSUE TITLE
VM stuck in deadlock with background finalization and background compiler thread

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#27380]
Repro:
```
out/DebugX64/dart --old-gen-heap-size=8 --optimization-counter-threshold=51 --ignore-unrecognized-flags /usr/local/google/home/fschneider/dartgit2/sdk/runtime/observatory/tests/service/implicit_getter_setter_test.dart
```

```
(gdb) thread apply all bt

Thread 7 (Thread 0x7f090f107700 (LWP 21182)):
#0  0x00007f090ddfda13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x00000000005d2581 in dart::bin::EventHandlerImplementation::Poll (args=args@entry=60784704) at runtime/bin/eventhandler_linux.cc:399
#2  0x00000000005cdd99 in dart::bin::ThreadStart (data_ptr=<optimized out>) at runtime/bin/thread_linux.cc:91
#3  0x00007f090ecfc184 in start_thread (arg=0x7f090f107700) at pthread_create.c:312
#4  0x00007f090ddfd37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 6 (Thread 0x7f090dd02700 (LWP 21183)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x000000000087de4c in dart::Monitor::WaitMicros (this=this@entry=0x39da180, micros=<optimized out>) at runtime/vm/os_thread_linux.cc:423
#2  0x0000000000992c5c in WaitMicros (this=<synthetic pointer>, micros=<optimized out>) at runtime/vm/lockers.h:176
#3  dart::ThreadInterrupter::ThreadMain (parameters=<optimized out>) at runtime/vm/thread_interrupter.cc:169
#4  0x000000000087c803 in dart::ThreadStart (data_ptr=<optimized out>) at runtime/vm/os_thread_linux.cc:123
#5  0x00007f090ecfc184 in start_thread (arg=0x7f090dd02700) at pthread_create.c:312
#6  0x00007f090ddfd37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 5 (Thread 0x7f090db01700 (LWP 21184)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000087dd28 in dart::Monitor::WaitMicros (this=0x39da7e0, micros=micros@entry=0) at runtime/vm/os_thread_linux.cc:418
#2  0x000000000087dfb1 in dart::Monitor::Wait (this=<optimized out>, millis=millis@entry=0) at runtime/vm/os_thread_linux.cc:402
#3  0x0000000000792f11 in Wait (this=0x7f090db00c10, millis=0) at runtime/vm/lockers.h:169
#4  dart::Isolate::ScheduleThread (this=this@entry=0x4d23200, is_mutator=is_mutator@entry=true, bypass_safepoint=bypass_safepoint@entry=false) at runtime/vm/isolate.cc:2595
#5  0x000000000098c965 in dart::Thread::EnterIsolate (isolate=isolate@entry=0x4d23200) at runtime/vm/thread.cc:245
#6  0x00000000007ccadd in StartIsolateScope (new_isolate=0x4d23200, this=<synthetic pointer>) at runtime/vm/isolate.h:885
#7  dart::MessageHandler::HandleMessages (this=this@entry=0x4d4c270, ml=ml@entry=0x7f090db00d40, allow_normal_messages=true, allow_multiple_normal_messages=allow_multiple_normal_messages@entry=true) at runtime/vm/message_handler.cc:191
#8  0x00000000007cf4b9 in dart::MessageHandler::TaskCallback (this=0x4d4c270) at runtime/vm/message_handler.cc:368
#9  0x00000000007cfefa in dart::MessageHandlerTask::Run (this=0x39e0c20) at runtime/vm/message_handler.cc:29
#10 0x0000000000995ae1 in dart::ThreadPool::Worker::Loop (this=this@entry=0x39d4000) at runtime/vm/thread_pool.cc:407
#11 0x0000000000996094 in dart::ThreadPool::Worker::Main (args=60637184) at runtime/vm/thread_pool.cc:464
#12 0x000000000087c803 in dart::ThreadStart (data_ptr=<optimized out>) at runtime/vm/os_thread_linux.cc:123
#13 0x00007f090ecfc184 in start_thread (arg=0x7f090db01700) at pthread_create.c:312
#14 0x00007f090ddfd37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 4 (Thread 0x7f090d20a700 (LWP 21185)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000087dd28 in dart::Monitor::WaitMicros (this=0x39dab40, micros=micros@entry=0) at runtime/vm/os_thread_linux.cc:418
#2  0x000000000087dfb1 in dart::Monitor::Wait (this=<optimized out>, millis=millis@entry=0) at runtime/vm/os_thread_linux.cc:402
#3  0x00000000006641ad in Wait (this=0x7f090d209500, millis=0) at runtime/vm/lockers.h:169
#4  dart::BackgroundCompiler::Run (this=0x39f80c0) at runtime/vm/compiler.cc:1905
#5  0x0000000000995ae1 in dart::ThreadPool::Worker::Loop (this=this@entry=0x39d40a0) at runtime/vm/thread_pool.cc:407
#6  0x0000000000996094 in dart::ThreadPool::Worker::Main (args=60637344) at runtime/vm/thread_pool.cc:464
#7  0x000000000087c803 in dart::ThreadStart (data_ptr=<optimized out>) at runtime/vm/os_thread_linux.cc:123
#8  0x00007f090ecfc184 in start_thread (arg=0x7f090d20a700) at pthread_create.c:312
#9  0x00007f090ddfd37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7f090d0c9700 (LWP 21186)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000087dd28 in dart::Monitor::WaitMicros (this=0x39da900, micros=micros@entry=0) at runtime/vm/os_thread_linux.cc:418
#2  0x000000000087dfb1 in dart::Monitor::Wait (this=<optimized out>, millis=millis@entry=0) at runtime/vm/os_thread_linux.cc:402
#3  0x00000000007c32d5 in dart::MonitorLocker::WaitWithSafepointCheck (this=this@entry=0x7f090d0c6a20, thread=thread@entry=0x39f6400, millis=millis@entry=0) at runtime/vm/lockers.cc:34
#4  0x000000000088577d in dart::PageSpace::MarkSweep (this=this@entry=0x4d37718, invoke_api_callbacks=<optimized out>) at runtime/vm/pages.cc:810
#5  0x000000000072fe41 in dart::Heap::CollectOldSpaceGarbage (this=0x4d37600, thread=0x39f6400, api_callbacks=dart::Heap::kInvokeApiCallbacks, reason=dart::Heap::kFull) at runtime/vm/heap.cc:396
#6  0x00000000007302d8 in dart::Heap::CollectAllGarbage (this=this@entry=0x4d37600) at runtime/vm/heap.cc:439
#7  0x0000000000730518 in dart::Heap::AllocateOld (this=this@entry=0x4d37600, size=size@entry=96, type=type@entry=dart::HeapPage::kData) at runtime/vm/heap.cc:105
#8  0x0000000000846616 in dart::Heap::Allocate (this=0x4d37600, size=96, space=dart::Heap::kOld) at runtime/vm/heap.h:79
#9  0x0000000000802d86 in dart::Object::Allocate (cls_id=cls_id@entry=75, size=96, space=space@entry=dart::Heap::kOld) at runtime/vm/object.cc:1843
#10 0x00000000008211c5 in dart::TypedData::New (class_id=class_id@entry=75, len=65, space=space@entry=dart::Heap::kOld) at runtime/vm/object.cc:22196
#11 0x000000000069921a in dart::DeoptInfoBuilder::CreateDeoptInfo (this=this@entry=0x7f090d0c6f20, deopt_table=...) at runtime/vm/deopt_instructions.cc:1310
#12 0x00000000006f7077 in dart::CompilerDeoptInfo::CreateDeoptInfo (this=<optimized out>, compiler=compiler@entry=0x7f090d0c7510, builder=builder@entry=0x7f090d0c6f20, deopt_table=...) at runtime/vm/flow_graph_compiler_x64.cc:185
#13 0x00000000006ef666 in dart::FlowGraphCompiler::CreateDeoptInfo (this=this@entry=0x7f090d0c7510, assembler=assembler@entry=0x7f090d0c7350) at runtime/vm/flow_graph_compiler.cc:1058
#14 0x000000000065cd28 in dart::CompileParsedFunctionHelper::FinalizeCompilation (this=this@entry=0x7f090d0c7a10, assembler=assembler@entry=0x7f090d0c7350, graph_compiler=graph_compiler@entry=0x7f090d0c7510, flow_graph=flow_graph@entry=0x5d12c00) at runtime/vm/compiler.cc:497
#15 0x000000000065f83c in dart::CompileParsedFunctionHelper::Compile (this=this@entry=0x7f090d0c7a10, pipeline=pipeline@entry=0x57082d8) at runtime/vm/compiler.cc:1136
#16 0x0000000000662256 in dart::CompileFunctionHelper (pipeline=0x57082d8, function=..., optimized=optimized@entry=true, osr_id=osr_id@entry=-1) at runtime/vm/compiler.cc:1271
#17 0x0000000000663f30 in dart::Compiler::CompileOptimizedFunction (thread=thread@entry=0x39f6400, function=..., osr_id=osr_id@entry=-1) at runtime/vm/compiler.cc:1467
#18 0x0000000000664300 in dart::BackgroundCompiler::Run (this=0x39f8100) at runtime/vm/compiler.cc:1869
#19 0x0000000000995ae1 in dart::ThreadPool::Worker::Loop (this=this@entry=0x39d4140) at runtime/vm/thread_pool.cc:407
#20 0x0000000000996094 in dart::ThreadPool::Worker::Main (args=60637504) at runtime/vm/thread_pool.cc:464
#21 0x000000000087c803 in dart::ThreadStart (data_ptr=<optimized out>) at runtime/vm/os_thread_linux.cc:123
#22 0x00007f090ecfc184 in start_thread (arg=0x7f090d0c9700) at pthread_create.c:312
#23 0x00007f090ddfd37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7f090cb36700 (LWP 21188)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000087dd28 in dart::Monitor::WaitMicros (this=0x39da7e0, micros=micros@entry=0) at runtime/vm/os_thread_linux.cc:418
#2  0x000000000087dfb1 in dart::Monitor::Wait (this=<optimized out>, millis=millis@entry=0) at runtime/vm/os_thread_linux.cc:402
#3  0x0000000000792f11 in Wait (this=0x7f090cb35ca0, millis=0) at runtime/vm/lockers.h:169
#4  dart::Isolate::ScheduleThread (this=this@entry=0x4d23200, is_mutator=is_mutator@entry=false, bypass_safepoint=bypass_safepoint@entry=false) at runtime/vm/isolate.cc:2595
#5  0x000000000098ca0d in dart::Thread::EnterIsolateAsHelper (isolate=0x4d23200, kind=kind@entry=dart::Thread::kFinalizerTask, bypass_safepoint=bypass_safepoint@entry=false) at runtime/vm/thread.cc:283
#6  0x00000000009ed0e2 in dart::BackgroundFinalizer::Run (this=0x4dcf5e0) at runtime/vm/dart_api_state.cc:30
#7  0x0000000000995ae1 in dart::ThreadPool::Worker::Loop (this=this@entry=0x39d4280) at runtime/vm/thread_pool.cc:407
#8  0x0000000000996094 in dart::ThreadPool::Worker::Main (args=60637824) at runtime/vm/thread_pool.cc:464
#9  0x000000000087c803 in dart::ThreadStart (data_ptr=<optimized out>) at runtime/vm/os_thread_linux.cc:123
#10 0x00007f090ecfc184 in start_thread (arg=0x7f090cb36700) at pthread_create.c:312
#11 0x00007f090ddfd37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7f090f109780 (LWP 21180)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000087dd28 in dart::Monitor::WaitMicros (this=this@entry=0x7ffdaa765c20, micros=micros@entry=0) at runtime/vm/os_thread_linux.cc:418
#2  0x000000000087dfb1 in dart::Monitor::Wait (this=this@entry=0x7ffdaa765c20, millis=millis@entry=0) at runtime/vm/os_thread_linux.cc:402
#3  0x00000000005b7f3a in Wait (this=<synthetic pointer>, millis=0) at runtime/vm/lockers.h:169
#4  dart::Dart_RunLoop () at runtime/vm/dart_api_impl.cc:1693
#5  0x0000000000588e19 in dart::bin::RunMainIsolate (script_name=script_name@entry=0x7ffdaa76710a "/usr/local/google/home/fschneider/dartgit2/sdk/runtime/observatory/tests/service/implicit_getter_setter_test.dart", dart_options=dart_options@entry=0x7ffdaa766060) at runtime/bin/main.cc:1586
#6  0x0000000000581c76 in dart::bin::main (argc=6, argv=0x7ffdaa766218) at runtime/bin/main.cc:1835
#7  0x0000000000581e69 in main (argc=<optimized out>, argv=<optimized out>) at runtime/bin/main.cc:1874
```

**Comment by a-siva** [comment]
Landed https://github.com/dart-lang/sdk/commit/da487a567c2a08646e8061c4239d3d0c754d2a91
