### ISSUE TITLE
Could not find element with name "E" in DeclarationResolver

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27390]
```
Could not find element with name "E" at 183842
all elements: []
_enclosingExecutable.typeParameters: (E extends Element name: E, offset: 183506)
Path to root: DeclaredSimpleIdentifier(E)(staticElement: null), TypeParameterImpl(E extends Element)(element: null), TypeParameterListImpl(<E extends Element>), MethodDeclarationImpl(element: getAncestor)(typeParameters: [E extends Element]), ClassDeclarationImpl(element: MultiplyDefinedElementImpl), CompilationUnitImpl
#0      RecursiveAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3448:5)
#1      DeclarationResolver._findWithNameAndOffset (package:analyzer/src/generated/resolver.dart:2799:5)
#2      DeclarationResolver._findIdentifier (package:analyzer/src/generated/resolver.dart:2755:23)
#3      DeclarationResolver.visitTypeParameter (package:analyzer/src/generated/resolver.dart:2679:13)
#4      TypeParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:10470:15)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7728:20)
#6      TypeParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10531:21)
#7      RecursiveAstVisitor.visitTypeParameterList (package:analyzer/dart/ast/visitor.dart:1948:10)
#8      TypeParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10527:15)
#9      MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7218:22)
#10     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1737:10)
#11     DeclarationResolver.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:2602:35)
#12     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7211:15)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7728:20)
#14     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1916:13)
#15     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:1425:10)
#16     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2317:34)
#17     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1848:15)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7728:20)
#19     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2447:21)
#20     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449:10)
#21     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2440:15)
#22     DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2292:10)
#23     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1081:33)
#24     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339:9)
#25     AnalysisTask.perform (package:analyzer/task/model.dart:238:7)
#26     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#27     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#28     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1243:27)
#29     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#30     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1241:50)
#31     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:355:37)
#32     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:893:17)
#33     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#34     _rootRun (dart:async/zone.dart:1146)
#35     _CustomZone.run (dart:async/zone.dart:1026)
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/2355543002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/dd5a6c2265f87ceecda50a886664f111c93c7d05
