### ISSUE TITLE
Cannot run Analysis Server benchmark on Flutter code

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27405]
Not sure why, but it fails in linter.

@pq 

```
/Users/scheglov/Applications/dart-sdk/bin/dart --ignore-unrecognized-flags --checked --enable-vm-service:63435 --trace_service_pause_events /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/benchmark/perf/benchmark_flutter.dart /Users/scheglov/Source/flutter flutter-memory-initialAnalysis-1
Observatory listening on http://127.0.0.1:63435
Unhandled exception:
Task failed: GenerateLintsTask for source /Users/scheglov/Source/flutter/packages/flutter/lib/src/animation/tween.dart
Unexpected exception while performing GenerateLintsTask for source /Users/scheglov/Source/flutter/packages/flutter/lib/src/animation/tween.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:351:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1243:27)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1241:50)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:355:37)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:893:17)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by type 'TypeParameterElementImpl' is not a subtype of type 'ClassElement' of 'element' where
  TypeParameterElementImpl is from package:analyzer/src/dart/element/element.dart
  ClassElement is from package:analyzer/dart/element/element.dart

#0      DartTypeUtilities.implementsInterface (package:linter/src/util/dart_type_utilities.dart:42:33)
#1      _isSubscription (package:linter/src/rules/cancel_subscriptions.dart:60:58)
#2      _buildVariableReporter.<anonymous closure>.<anonymous closure> (package:linter/src/util/leak_detector_visitor.dart:36:42)
#3      Iterable.any (dart:core/iterable.dart:337)
#4      _buildVariableReporter.<anonymous closure> (package:linter/src/util/leak_detector_visitor.dart:36:12)
#5      Object&ListMixin.forEach (dart:collection/list.dart:63)
#6      LeakDetectorVisitor.visitFieldDeclaration (package:linter/src/util/leak_detector_visitor.dart:151:27)
#7      DelegatingAstVisitor.visitFieldDeclaration.<anonymous closure> (package:analyzer/dart/ast/visitor.dart:396:47)
#8      List.forEach (dart:core-patch/growable_array.dart:258)
#9      DelegatingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:396:16)
#10     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4301:15)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7728:20)
#12     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1916:13)
#13     DelegatingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:224:10)
#14     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1848:15)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7728:20)
#16     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2447:21)
#17     DelegatingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:252:10)
#18     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2440:15)
#19     GenerateLintsTask.internalPerform (package:analyzer/src/task/dart.dart:3274:10)
#20     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339:9)
#21     AnalysisTask.perform (package:analyzer/task/model.dart:238:7)
#22     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#23     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#24     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1243:27)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#26     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1241:50)
#27     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:355:37)
#28     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:893:17)
#29     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#30     _rootRun (dart:async/zone.dart:1146)
#31     _CustomZone.run (dart:async/zone.dart:1026)
#32     _CustomZone.runGuarded (dart:async/zone.dart:924)
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#34     _rootRun (dart:async/zone.dart:1150)
#35     _CustomZone.run (dart:async/zone.dart:1026)
#36     _CustomZone.runGuarded (dart:async/zone.dart:924)
#37     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#38     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#39     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#40     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      DefaultFailureHandler.fail (package:unittest/src/matcher/expect.dart:117:5)
#1      fail (package:unittest/src/matcher/expect.dart:103:18)
#2      AnalysisServerMemoryUsageTest.setUp.<anonymous closure> (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/benchmark/perf/memory_tests.dart:64:7)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:268)
#6      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:386)
#7      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:261)
#8      _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:488)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:268)
#12     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#13     _StreamController._add (dart:async/stream_controller.dart:635)
#14     _StreamController.add (dart:async/stream_controller.dart:581)
#15     IntegrationTestMixin.dispatchNotification (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/test/integration/integration_test_methods.dart:1682:24)
#16     Server.listenToOutput.<anonymous closure> (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/test/integration/integration_tests.dart:555:30)
#17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:268)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#22     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#23     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:158)
#24     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:133)
#25     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:268)
#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#32     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#33     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#34     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#35     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#36     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#37     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#38     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:268)
#41     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#42     _StreamController._add (dart:async/stream_controller.dart:635)
#43     _StreamController.add (dart:async/stream_controller.dart:581)
#44     _Socket._onData (dart:io-patch/socket_patch.dart:1666)
#45     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:268)
#48     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#49     _StreamController._add (dart:async/stream_controller.dart:635)
#50     _StreamController.add (dart:async/stream_controller.dart:581)
#51     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1233)
#52     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:766)
#53     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#54     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#55     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Process finished with exit code 255
```

**Comment by pq** [comment]
Thanks Brian!

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2355343002/

**Comment by alexeieleusis** [comment]
Thank you Brian!
