### ISSUE TITLE
dart2js fails with getter/setter for-in loop variable

### ISSUE THREAD

**Issue by harryterkelsen** [dart-lang/sdk#27439]
dart2js fails to correctly compile this program:

``` dart
int _a = 0;
int get a => _a;
void set a(int newA) {
  _a = newA;
}
main() {
  int sum = 0;
  for (a in [1 ,2, 3]) {
    sum += a;
  }
  print(sum);
}
```

Running `dart2js` in checked mode on this program gives:

```
$ dart2js --checked foo.dart 
foo.dart:5:1:
Internal Error: Static set element getter(a) must be a field or a setter.
int get a => _a;
^^^^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Assertion failure: Static set element getter(a) must be a field or a setter.
#0      invariant (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:60:5)
#1      StaticUse.StaticUse.staticSet (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/universe/use.dart:127:12)
#2      ResolverVisitor.visitForInDeclaredIdentifierIn (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/members.dart:4330:17)
#3      ResolverVisitor.visitSyncForIn (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/members.dart:4275:5)
#4      SyncForIn.accept (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/tree/nodes.dart:2451:38)
#5      CommonResolverVisitor.visit (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#6      ResolverVisitor.visitNodeList (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/members.dart:3551:7)
#7      NodeList.accept (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/tree/nodes.dart:826:38)
#8      CommonResolverVisitor.visit (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#9      ResolverVisitor.visitIn (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/members.dart:499:31)
#10     ResolverVisitor.visitBlock (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/members.dart:519:5)
#11     Block.accept (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/tree/nodes.dart:882:38)
#12     CommonResolverVisitor.visit (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#13     ResolverTask.resolveMethodElementImplementation.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/resolution.dart:264:17)
#14     CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:1640:15)
#15     ResolverTask.resolveMethodElementImplementation (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/resolution.dart:219:21)
#16     ResolverTask.resolveMethodElement.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/resolution.dart:336:16)
#17     CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:1640:15)
#18     ResolverTask.resolveMethodElement (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/resolution.dart:300:21)
#19     ResolverTask.resolve.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/resolution.dart:105:32)
#20     CompilerTask.measure (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#21     ResolverTask.resolve (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/resolution/resolution.dart:85:12)
#22     _CompilerResolution.computeWorldImpact.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:2117:61)
#23     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:265)
#24     _CompilerResolution.computeWorldImpact (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:2113:30)
#25     Compiler.analyzeElement.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:936:27)
#26     CompilerTask.measureSubtask (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#27     Compiler.analyzeElement (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:923:16)
#28     Compiler.analyze.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:958:35)
#29     CompilerTask.measureSubtask (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#30     Compiler.analyze (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:940:16)
#31     ResolutionWorkItem.run (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/common/resolution.dart:50:35)
#32     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:840:52)
#33     CompilerTask.measureSubtask (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#34     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:839:34)
#35     CompilerTask.measureSubtask (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#36     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:836:30)
#37     CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:1640:15)
#38     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:834:20)
#39     QueueFilter.processWorkItem (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/enqueue.dart:842:6)
#40     ResolutionEnqueuer.forEach (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/enqueue.dart:653:16)
#41     Compiler.emptyQueue.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:833:15)
#42     CompilerTask.measureSubtask (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#43     Compiler.emptyQueue (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:832:16)
#44     Compiler.processQueue.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:873:9)
#45     CompilerTask.measureSubtask (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#46     Compiler.processQueue (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:846:16)
#47     Compiler.compileLoadedLibraries.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:692:9)
#48     CompilerTask.measureSubtask (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#49     Compiler.compileLoadedLibraries (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:648:16)
#50     Compiler.runInternal.<anonymous closure> (file:///usr/local/google/home/het/Code/dart/sdk/pkg/compiler/lib/src/compiler.dart:558:7)
#51     _RootZone.runUnary (dart:async/zone.dart:1404)
#52     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#53     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#54     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#55     _Future._completeWithValue (dart:async/future_impl.dart:477)
#56     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#59     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

For for-in loops, `dart2js` should find the setter element for the loop variable, not the getter.

**Comment by rakudrama** [comment]
This seems to be fixed, now generating expected code when compiler runs under `--enable-asserts`.
