### ISSUE TITLE
64-bit dartium build failing in runhooks on buildbot

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27442]
The error happened after reverting the build slave to ubuntu precise, and there seems to be a python script missing in the mojo download hook:

_______ running '/usr/bin/python src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py --tools-directory=../../../../../../tools' in '/b/build/slave/dartium-linux-x64-be/build'
Traceback (most recent call last):
  File "src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py", line 101, in <module>
    sys.exit(main())
  File "src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py", line 98, in main
    return download(args.tools_directory, args.version_file)
  File "src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py", line 49, in download
    download_version_for_platform(version, platform, tools_directory)
  File "src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py", line 67, in download_version_for_platform
    depot_tools_path)
  File "/b/build/slave/dartium-linux-x64-be/build/src/third_party/mojo/src/mojo/public/tools/pylib/gs.py", line 31, in download_from_public_bucket
    env=env)

@alan-knight @terrylucas

**Comment by whesse** [comment]
The issue is fixed with cl https://codereview.chromium.org/2378683002/

An equivalent fix was landed against mojo last year in https://chromium.googlesource.com/external/mojo/+/97b3360decaf5d0fa129f67e6648e7b81516d6fb
and we just didn't have it in our copy.

**Comment by whesse** [comment]
We need to copy gsutil to depot_tools/third_party with
cp -r /b/depot_tools/external_bin/gsutil/gsutil_4.7/gsutil /b/depot_tools/third_party
and then
chmod 775 /b/depot_tools/third_party/gsutil/gsutil
chmod 775 /b/depot_tools/third_party/gsutil/gsutil.py

Then the fix will work.
