### ISSUE TITLE
global_compile.dart broken file paths on Windows 

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#27451]
There is a problem parsing the URI when running in the windows command line. The file path gets truncated down to just `c:`

```
Unhandled exception:
FileSystemException: Cannot open file, path = 'c:' (OS Error: Access is denied.
, errno = 5)
#0      _File.throwIfError (dart:io/file_impl.dart:562)
#1      _File.openSync (dart:io/file_impl.dart:413)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:473)
#3      _File.readAsStringSync (dart:io/file_impl.dart:507)
#4      _loadFile (file:///c:/Users/nshahan/code/dart-sdk/sdk/pkg/dev_compiler/tool/global_compile.dart:267:24)
#5      transitiveFiles (file:///c:/Users/nshahan/code/dart-sdk/sdk/pkg/dev_compiler/tool/global_compile.dart:275:18)
#6      main (file:///c:/Users/nshahan/code/dart-sdk/sdk/pkg/dev_compiler/tool/global_compile.dart:79:3)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by mit-mit** [comment]
@nshahan was this fixed in https://github.com/dart-lang/sdk/commit/8f5f1a0fb0b4f169eb264ee6c10fb076b4c05643 ?

**Comment by nshahan** [comment]
I was seeing this issue when running on a windows machine. The branch you mentioned worked for me on the project I was working on but was not thoroughly tested on other platforms and I don't want to merge those changes in. I will cleanup.
