### ISSUE TITLE
Exception thrown trying to compute value of @null

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27464]
Count: 2
Session Id: 1473978471793.2766

Message: Task failed: ComputeConstantValueTask for element @null in source xxx.dart,
StackTrace: Unexpected exception while performing ComputeConstantValueTask for element @null in source xxx.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:350)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:718)
#5      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1338)
#6      AnalysisServer._getResolvedCompilationUnitToResendNotification.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1467)
#7      runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:37)
#8      AnalysisServer._getResolvedCompilationUnitToResendNotification (package:analysis_server/src/analysis_server.dart:1466)
#9      AnalysisServer.setAnalysisSubscriptions.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1121)
#10     _HashMap.forEach (dart:collection-patch/collection_patch.dart:148)
#11     AnalysisServer.setAnalysisSubscriptions (package:analysis_server/src/analysis_server.dart:1086)
#12     AnalysisDomainHandler.setSubscriptions (package:analysis_server/src/domain_analysis.dart:293)
#13     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:206)
#14     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:768)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#16     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:764)
#17     _rootRun (dart:async/zone.dart:1158)
#18     _CustomZone.run (dart:async/zone.dart:1034)
#19     _CustomZone.runGuarded (dart:async/zone.dart:932)
#20     runZoned (dart:async/zone.dart:1509)
#21     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:763)
#22     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
#26     _rootRunUnary (dart:async/zone.dart:1166)
#27     _CustomZone.runUnary (dart:async/zone.dart:1045)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:940)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:158)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:133)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#37     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#38     _rootRunUnary (dart:async/zone.dart:1166)
#39     _CustomZone.runUnary (dart:async/zone.dart:1045)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:940)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#46     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#47     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#48     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#49     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#50     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#51     _rootRunUnary (dart:async/zone.dart:1166)
#52     _CustomZone.runUnary (dart:async/zone.dart:1045)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:940)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#56     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#57     _StreamController._add (dart:async/stream_controller.dart:635)
#58     _StreamController.add (dart:async/stream_controller.dart:581)
#59     _Socket._onData (dart:io-patch/socket_patch.dart:1666)
#60     _rootRunUnary (dart:async/zone.dart:1170)
#61     _CustomZone.runUnary (dart:async/zone.dart:1045)
#62     _CustomZone.runUnaryGuarded (dart:async/zone.dart:940)
#63     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#64     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#65     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#66     _StreamController._add (dart:async/stream_controller.dart:635)
#67     _StreamController.add (dart:async/stream_controller.dart:581)
#68     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1233)
#69     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:766)
#70     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#71     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#72     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#73     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Caused by The null object does not have a getter 'context'.

NoSuchMethodError: method not found: 'context'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ElementAnnotationImpl.context (package:analyzer/src/dart/element/element.dart:2537)
#3      ComputeConstantValueTask.internalPerform (package:analyzer/src/task/dart.dart:2063)
#4      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:338)
#5      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#6      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#7      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#8      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:718)
#9      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1338)
#10     AnalysisServer._getResolvedCompilationUnitToResendNotification.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1467)
#11     runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:37)
#12     AnalysisServer._getResolvedCompilationUnitToResendNotification (package:analysis_server/src/analysis_server.dart:1466)
#13     AnalysisServer.setAnalysisSubscriptions.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1121)
#14     _HashMap.forEach (dart:collection-patch/collection_patch.dart:148)
#15     AnalysisServer.setAnalysisSubscriptions (package:analysis_server/src/analysis_server.dart:1086)
#16     AnalysisDomainHandler.setSubscriptions (package:analysis_server/src/domain_analysis.dart:293)
#17     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:206)
#18     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:768)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#20     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:764)
#21     _rootRun (dart:async/zone.dart:1158)
#22     _CustomZone.run (dart:async/zone.dart:1034)
#23     _CustomZone.runGuarded (dart:async/zone.dart:932)
#24     runZoned (dart:async/zone.dart:1509)
#25     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:763)
#26     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)
#27     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#28     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161)
#29     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
#30     _rootRunUnary (dart:async/zone.dart:1166)
#31     _CustomZone.runUnary (dart:async/zone.dart:1045)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:940)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#35     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#36     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#37     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#38     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:158)
#39     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:133)
#40     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#42     _rootRunUnary (dart:async/zone.dart:1166)
#43     _CustomZone.runUnary (dart:async/zone.dart:1045)
#44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:940)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#47     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#48     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#49     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#50     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#51     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#52     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#53     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#54     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#55     _rootRunUnary (dart:async/zone.dart:1166)
#56     _CustomZone.runUnary (dart:async/zone.dart:1045)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:940)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#60     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#61     _StreamController._add (dart:async/stream_controller.dart:635)
#62     _StreamController.add (dart:async/stream_controller.dart:581)
#63     _Socket._onData (dart:io-patch/socket_patch.dart:1666)
#64     _rootRunUnary (dart:async/zone.dart:1170)
#65     _CustomZone.runUnary (dart:async/zone.dart:1045)
#66     _CustomZone.runUnaryGuarded (dart:async/zone.dart:940)
#67     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#68     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#69     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#70     _StreamController._add (dart:async/stream_controller.dart:635)
#71     _StreamController.add (dart:async/stream_controller.dart:581)
#72     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1233)
#73     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:766)
#74     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#75     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#76     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#77     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by bwilkerson** [comment]
I'm assuming that this is stale.
