### ISSUE TITLE
Null element causes exception in completion

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27461]
Count: 56
Session Id: 1474326051346.0796

    message: Failed to handle completion domain request: {clientRequestTime: 1474397129772, params: {file: xxx.dart, offset: 411}, method: completion.getSuggestions, id: 1516},
    stackTrace: The null object does not have a getter 'displayName'.

NoSuchMethodError: method not found: 'displayName'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      createSuggestion (package:analysis_server/src/services/completion/dart/suggestion_builder.dart:37)
#3      FieldFormalContributor.computeSuggestions.<computeSuggestions_async_body> (package:analysis_server/src/services/completion/dart/field_formal_contributor.dart:66)
#4      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#5      _rootRun (dart:async/zone.dart:1154)
#6      _CustomZone.run (dart:async/zone.dart:1034)
#7      _CustomZone.runGuarded (dart:async/zone.dart:932)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:959)
#9      _rootRun (dart:async/zone.dart:1158)
#10     _CustomZone.run (dart:async/zone.dart:1034)
#11     _CustomZone.runGuarded (dart:async/zone.dart:932)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:959)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2383533005/
