### ISSUE TITLE
VM: big_integer_arith_vm_test/gcd failing under DBC

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#27474]
```
FAILED: none-vm release_simdbc corelib/big_integer_arith_vm_test/gcd
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.equals(expected: <23089744183296>, actual: <5376>) fails.
#0      Expect._fail (package:expect/expect.dart:385:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      testBigintGcd (file:///usr/local/google/home/fschneider/dartgit2/sdk/out/ReleaseSIMDBC/generated_tests/corelib/big_integer_arith_vm_test_gcd.dart:310:10)
#3      main (file:///usr/local/google/home/fschneider/dartgit2/sdk/out/ReleaseSIMDBC/generated_tests/corelib/big_integer_arith_vm_test_gcd.dart:433:5)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=ReleaseSIMDBC out/ReleaseSIMDBC/dart --optimization_counter_threshold=10 --no-background_compilation --ignore-unrecognized-flags --packages=/usr/local/google/home/fschneider/dartgit/sdk/.packages /usr/local/google/home/fschneider/dartgit2/sdk/out/ReleaseSIMDBC/generated_tests/corelib/big_integer_arith_vm_test_gcd.dart
Took 0:00:00.291962

Short reproduction command (experimental):
    python tools/test.py -mrelease -asimdbc -t480 --packages /usr/local/google/home/fschneider/dartgit/sdk/.packages --exclude-suite pkg corelib/big_integer_arith_vm_test/gcd
```

**Comment by mit-mit** [comment]
Is this a new 1.20 regression? If so, what is the potential impact?

**Comment by fsc8000** [comment]
@zanderso @mraleph Another bigint related failure. Not sure if these two are related
```
out/ReleaseSIMDBC64/dart --no-background-compilation --packages=.packages out/ReleaseSIMDBC64/generated_tests/corelib/big_integer_arith_vm_test_modPow.dart
```

Result:
```
Unhandled exception:
Expect.equals(expected: <35088523091000351053091545070>, actual: <82576665612830700457539783555>) fails.
```
