### ISSUE TITLE
VM: lib/math/double_pow_test failing wiht SIMDBC64

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#27481]
```
FAILED: none-vm release_simdbc64 lib/math/double_pow_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.identical(expected: <0.0>, actual: <NaN>, 'NaN') fails.
#0      Expect._fail (package:expect/expect.dart:385:5)
#1      Expect.identical (package:expect/expect.dart:148:5)
#2      test (file:///usr/local/google/home/fschneider/dartgit2/sdk/tests/lib/math/double_pow_test.dart:88:14)
#3      main (file:///usr/local/google/home/fschneider/dartgit2/sdk/tests/lib/math/double_pow_test.dart:173:32)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=ReleaseSIMDBC64 out/ReleaseSIMDBC64/dart --optimization-counter-threshold=5 --no-background-compilation --ignore-unrecognized-flags --packages=/usr/local/google/home/fschneider/dartgit/sdk/.packages /usr/local/google/home/fschneider/dartgit2/sdk/tests/lib/math/double_pow_test.dart
Took 0:00:00.522024

Short reproduction command (experimental):
    python tools/test.py -mrelease -asimdbc64 -t480 --packages /usr/local/google/home/fschneider/dartgit/sdk/.packages --exclude-suite pkg lib/math/double_pow_test
```

**Comment by fsc8000** [comment]
NaN is handled differently on DBC than on other architectures: https://codereview.chromium.org/2400103002/
