### ISSUE TITLE
Analysis server crash

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27513]
Not sure how to trigger it, but I got this:

```
The null object does not have a method '-'.

NoSuchMethodError: method not found: '-'
Receiver: null
Arguments: [null]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _UpdateElementOffsetsVisitor.visitElement (package:analyzer/src/task/incremental_element_builder.dart:746)
#3      GeneralizingElementVisitor.visitVariableElement (package:analyzer/dart/element/visitor.dart:178)
#4      GeneralizingElementVisitor.visitPropertyInducingElement (package:analyzer/dart/element/visitor.dart:168)
#5      GeneralizingElementVisitor.visitFieldElement (package:analyzer/dart/element/visitor.dart:111)
#6      FieldElementImpl.accept (package:analyzer/src/dart/element/element.dart:4181)
#7      IncrementalCompilationUnitElementBuilder._replaceNode (package:analyzer/src/task/incremental_element_builder.dart:509)
#8      IncrementalCompilationUnitElementBuilder._processClassMembers (package:analyzer/src/task/incremental_element_builder.dart:321)
#9      IncrementalCompilationUnitElementBuilder._processUnitMembers (package:analyzer/src/task/incremental_element_builder.dart:456)
#10     IncrementalCompilationUnitElementBuilder.build (package:analyzer/src/task/incremental_element_builder.dart:140)
#11     AnalysisContextImpl._sourceChanged (package:analyzer/src/context/context.dart:1904)
#12     AnalysisContextImpl.applyChanges (package:analyzer/src/context/context.dart:650)
#13     ServerContextManagerCallbacks.applyChangesToContext (package:analysis_server/src/analysis_server.dart:1633)
#14     ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1433)
#15     _rootRunUnary (dart:async/zone.dart:1158)
#16     _CustomZone.runUnary (dart:async/zone.dart:1037)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:268)
#20     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:386)
#21     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:261)
#22     _rootRunUnary (dart:async/zone.dart:1158)
#23     _CustomZone.runUnary (dart:async/zone.dart:1037)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#26     _DelayedData.perform (dart:async/stream_impl.dart:600)
#27     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:716)
#28     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:676)
#29     _rootRun (dart:async/zone.dart:1146)
#30     _CustomZone.run (dart:async/zone.dart:1026)
#31     _CustomZone.runGuarded (dart:async/zone.dart:924)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#33     _rootRun (dart:async/zone.dart:1150)
#34     _CustomZone.run (dart:async/zone.dart:1026)
#35     _CustomZone.runGuarded (dart:async/zone.dart:924)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#39     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#40     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by DanTup** [comment]
Might this be the same as #27770?

**Comment by bwilkerson** [comment]
Yes, I believe it is. Thanks!
