### ISSUE TITLE
Navigation to symbols declared in dart:html library broken

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#27538]
Reproducible since SDK 1.18 and up to the latest 1.20-dev.10.1 if summaries are enabled.
Simple single-file project:
```
import "dart:html";
main() {
  querySelector("");
}
```

Analysis Server gives navigation info for `querySelector` reference. Target file is `SDK/lib/html/dartium/html_dartium.dart`, but target offset/line/column (1406076/43434/9) is incorrect, there's some unrelated stuff at this offset in `html_dartium.dart`.
**BUT** `querySelector` function declaration in `SDK/lib/html/dart2js/html_dart2js.dart` file is exactly at this offset!

Also Analysis Server gives no highlighting and navigation info for the  `html_dartium.dart` file itself. Let me know if it should be tracked separately.

Also if you open `html_dartium.dart` file in the editor Analysis Server throws an error:

```
Dart analysis server, SDK version 1.20.0-dev.10.1, server version 1.17.0, error: Failed to handle completion domain request: {clientRequestTime: 1475847963778, params: {file: C:\dart_projects\untitled\bin\main.dart, offset: 44}, method: completion.getSuggestions, id: 51}
AnalysisException: failed to resolve expression
Caused by Mismatch in DeclarationResolver while resolving C:\dart\dart-dev-channel\lib\html\dartium\html_dartium.dart
Could not find element with name "_window" at 2194
Path to root: DeclaredSimpleIdentifier, VariableDeclarationImpl, VariableDeclarationListImpl, TopLevelVariableDeclarationImpl, CompilationUnitImpl
#0      RecursiveAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3464)
#1      DeclarationResolver._findWithNameAndOffset (package:analyzer/src/generated/resolver.dart:2833)
#2      DeclarationResolver._findIdentifier (package:analyzer/src/generated/resolver.dart:2791)
#3      DeclarationResolver.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:2746)
#4      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10773)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#6      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10871)
#7      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1960)
#8      DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:2763)
#9      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10865)
#10     TopLevelVariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10064)
#11     RecursiveAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1918)
#12     DeclarationResolver.visitTopLevelVariableDeclaration (package:analyzer/src/generated/resolver.dart:2698)
#13     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10059)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#15     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2452)
#16     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2445)
#18     DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2328)
#19     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1080)
#20     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#21     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#22     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#23     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#24     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1184)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#26     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1182)
#27     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#28     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:894)
#29     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#30     _rootRun (dart:async/zone.dart:1146)
#31     _CustomZone.run (dart:async/zone.dart:1026)
#32     _CustomZone.runGuarded (dart:async/zone.dart:924)
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#34     _rootRun (dart:async/zone.dart:1150)
#35     _CustomZone.run (dart:async/zone.dart:1026)
#36     _CustomZone.runGuarded (dart:async/zone.dart:924)
#37     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#38     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#39     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#40     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by alexander-doroshko** [comment]
@bwilkerson Is it just a P2? Navigation and highlighting are the most important features of the Analysis Server.

**Comment by bwilkerson** [comment]
Some would argue that code completion is the most important feature. That aside, we tend to reserve P1 for issues that cause server to be unusable (such as crashes).

**Comment by alexander-doroshko** [comment]
@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/2404903002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/1fc611fe2ce575476bb205f80a8b78b692f68d6d
