### ISSUE TITLE
@JS annotated classes that start with an underscore have no accessible methods

### ISSUE THREAD

**Issue by moomoohk** [dart-lang/sdk#27537]
### Expected
Given two identical classes (barring the names):
```Dart
@JS
class _Test {
  external _Test();
  external void testMethod();
}

@JS
class Test {
  external Test();
  external void testMethod();  // Same as _Test.testMethod
}
```

then `new _Test().testMethod()` should do the same thing as `new Test().testMethod()`

### Actual
Running:
```Dart
var testObj = new _Test();
testObj.testMethod();
```
produces:
```
dart:core-patch/object_patch.dart:43 Uncaught Unhandled exception:
Class 'JSObjectImpl' has no instance method 'testMethod'.

NoSuchMethodError: method not found: 'testMethod'
Receiver: Instance of 'JSObjectImpl'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      JSObject.noSuchMethod.throwError (dart:js:1304)
#3      JSObject.noSuchMethod (dart:js:1343)
#4      Eval.<anonymous closure> (evaluate:source:2:6)No PropertiesObject._noSuchMethod@0150898 @ dart:core-patch/object_patch.dart:43Object.noSuchMethod @ dart:core-patch/object_patch.dart:46JSObject.throwError @ dart:js:1303JSObject.noSuchMethod @ dart:js:1342<anonymous closure> @ evaluate:source:1
```

On the other hand, running:
```Dart
var testObj = new Test();
testObj.testMethod();
```
works fine

**Comment by jacob314** [comment]
The @JS annotation needs to be written as
@JS()

Also, make sure you annotate your library with 
@JS() so that JS Interop is active.

**Comment by moomoohk** [comment]
@jacob314 thanks. I've updated the example code.
