### ISSUE TITLE
NPE in ParameterAssignments lint

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27545]
There are two issues here. One is that the lint contains a bug. The other is that a bug in a lint rule caused the GenerateLintsTask to fail.

Dart analysis server, SDK version 1.20.0-dev.10.1, server version 1.17.0, error: Task failed: GenerateLintsTask for source x.dart
Unexpected exception while performing GenerateLintsTask for source x.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:351)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1184)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1182)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:894)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'parameters'.

NoSuchMethodError: method not found: 'parameters'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _Visitor.visitMethodDeclaration (package:linter/src/rules/parameter_assignments.dart:81)
#3      DelegatingAstVisitor.visitMethodDeclaration.<anonymous closure> (package:analyzer/dart/ast/visitor.dart:597)
#4      List.forEach (dart:core-patch/growable_array.dart:258)
#5      DelegatingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:597)
#6      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7226)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#8      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1920)
#9      DelegatingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:224)
#10     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1852)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2452)
#13     DelegatingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:252)
#14     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2445)
#15     GenerateLintsTask.internalPerform (package:analyzer/src/task/dart.dart:3262)
#16     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#17     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#18     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#19     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#20     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1184)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#22     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1182)
#23     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#24     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:894)
#25     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#26     _rootRun (dart:async/zone.dart:1146)
#27     _CustomZone.run (dart:async/zone.dart:1026)
#28     _CustomZone.runGuarded (dart:async/zone.dart:924)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#30     _rootRun (dart:async/zone.dart:1150)
#31     _CustomZone.run (dart:async/zone.dart:1026)
#32     _CustomZone.runGuarded (dart:async/zone.dart:924)
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#34     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#35     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#36     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2403443003/
https://codereview.chromium.org/2407553002/
