### ISSUE TITLE
Need to handle mismatches in DeclarationResolver

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27541]
The line numbers are wrong, but I suspect the bug still exists.

Dart analysis server, SDK version 1.20.0-dev.4.0, server version 1.17.0, error: Task failed: BuildCompilationUnitElementTask for source x.dart
Mismatch in DeclarationResolver while resolving x.dart
Could not find element with name "S2" at 2129
Path to root: DeclaredSimpleIdentifier, TypeParameterImpl, TypeParameterListImpl, MethodDeclarationImpl, ClassDeclarationImpl, CompilationUnitImpl
#0      RecursiveAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3426)
#1      DeclarationResolver._findWithNameAndOffset (package:analyzer/src/generated/resolver.dart:2795)
#2      DeclarationResolver._findIdentifier (package:analyzer/src/generated/resolver.dart:2753)
#3      DeclarationResolver.visitTypeParameter (package:analyzer/src/generated/resolver.dart:2677)
#4      TypeParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:10412)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#6      TypeParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10473)
#7      RecursiveAstVisitor.visitTypeParameterList (package:analyzer/dart/ast/visitor.dart:1948)
#8      TypeParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10469)
#9      MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7194)
#10     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1737)
#11     DeclarationResolver.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:2600)
#12     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7187)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#14     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1915)
#15     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:1425)
#16     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2315)
#17     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1847)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#19     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2446)
#20     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449)
#21     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439)
#22     DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2290)
#23     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1077)
#24     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:338)
#25     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#26     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#27     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#28     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1243)
#29     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#30     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1241)
#31     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:355)
#32     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:894)
#33     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#34     _rootRun (dart:async/zone.dart:1146)
#35     _CustomZone.run (dart:async/zone.dart:1026)
#36     _CustomZone.runGuarded (dart:async/zone.dart:924)
#37     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#38     _rootRun (dart:async/zone.dart:1150)
#39     _CustomZone.run (dart:async/zone.dart:1026)
#40     _CustomZone.runGuarded (dart:async/zone.dart:924)
#41     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#42     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#43     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#44     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by bwilkerson** [comment]
I'm assuming that this is stale.
