### ISSUE TITLE
NPE in ErrorVerifier

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27544]
Dart analysis server, SDK version 1.20.0-dev.5.0, server version 1.17.0, error: Task failed: VerifyUnitTask for source x.dart
Unexpected exception while performing VerifyUnitTask for source x.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:351)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1243)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1241)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:355)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:893)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'displayName'.

NoSuchMethodError: method not found: 'displayName'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ErrorVerifier._checkForAmbiguousImport (package:analyzer/src/generated/error_verifier.dart:2362)
#3      ErrorVerifier.visitSimpleIdentifier (package:analyzer/src/generated/error_verifier.dart:1130)
#4      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9010)
#5      TypeNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10333)
#6      RecursiveAstVisitor.visitTypeName (package:analyzer/dart/ast/visitor.dart:1936)
#7      ErrorVerifier.visitTypeName (package:analyzer/src/generated/error_verifier.dart:1200)
#8      TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10329)
#9      ConstructorNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3091)
#10     RecursiveAstVisitor.visitConstructorName (package:analyzer/dart/ast/visitor.dart:1479)
#11     ConstructorNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:3087)
#12     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6154)
#13     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:1665)
#14     ErrorVerifier.visitInstanceCreationExpression (package:analyzer/src/generated/error_verifier.dart:916)
#15     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6150)
#16     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7313)
#17     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1743)
#18     ErrorVerifier.visitMethodInvocation (package:analyzer/src/generated/error_verifier.dart:1021)
#19     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7309)
#20     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4156)
#21     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:1557)
#22     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4152)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#24     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1284)
#25     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:1389)
#26     ErrorVerifier.visitBlock (package:analyzer/src/generated/error_verifier.dart:400)
#27     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1280)
#28     IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5704)
#29     RecursiveAstVisitor.visitIfStatement (package:analyzer/dart/ast/visitor.dart:1641)
#30     ErrorVerifier.visitIfStatement (package:analyzer/src/generated/error_verifier.dart:867)
#31     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5699)
#32     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#33     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1284)
#34     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:1389)
#35     ErrorVerifier.visitBlock (package:analyzer/src/generated/error_verifier.dart:400)
#36     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1280)
#37     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1228)
#38     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:1395)
#39     ErrorVerifier.visitBlockFunctionBody (package:analyzer/src/generated/error_verifier.dart:419)
#40     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1224)
#41     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7196)
#42     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1737)
#43     ErrorVerifier.visitMethodDeclaration (package:analyzer/src/generated/error_verifier.dart:1000)
#44     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7187)
#45     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#46     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1915)
#47     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:1425)
#48     ErrorVerifier.visitClassDeclaration (package:analyzer/src/generated/error_verifier.dart:498)
#49     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1847)
#50     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#51     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2446)
#52     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449)
#53     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:568)
#54     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439)
#55     VerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:6142)
#56     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#57     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#58     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#59     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#60     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1243)
#61     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#62     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1241)
#63     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:355)
#64     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:893)
#65     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#66     _rootRun (dart:async/zone.dart:1146)
#67     _CustomZone.run (dart:async/zone.dart:1026)
#68     _CustomZone.runGuarded (dart:async/zone.dart:924)
#69     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#70     _rootRun (dart:async/zone.dart:1150)
#71     _CustomZone.run (dart:async/zone.dart:1026)
#72     _CustomZone.runGuarded (dart:async/zone.dart:924)
#73     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#74     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#75     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#76     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#77     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2403503002/
