### ISSUE TITLE
analyzer crash on dart2js

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#27615]
This test fails

```
tools/test.py -mrelease -cdart2analyzer -rnone dart2js/analyze_all_test
```

```
=== Failure summary:


FAILED: dart2analyzer-none release_x64 dart2js/analyze_all_test
Expected: Pass 
Actual: Crash
CommandOutput[dart2analyzer]:

stderr:
AnalysisException: Cannot compute LIBRARY_ELEMENT for /usr/local/google/home/sra/Dart/sdk/tests/compiler/dart2js/analyze_all_test.dart
Caused by Element mismatch in /usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/dart2js.dart at compileWithSerializedData(null compilerOptions, null compilerInput, null compilerDiagnostics, null compilerOutput, null serializedData, {null compileOnly})
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:48:7)
#1      BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1081:33)
#2      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339:9)
#3      AnalysisTask.perform (package:analyzer/task/model.dart:238:7)
#4      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#5      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
#6      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723:14)
#7      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:696:12)
#8      AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:247:22)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#10     AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:246:31)
#11     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:160:26)
#12     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:121:12)
#13     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:633:34)
#14     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:219:30)
#15     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:162:14)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#17     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:161:27)
#18     Driver.start.<anonymous closure> (package:analyzer_cli/src/driver.dart:139:16)
#19     _BatchRunner.runAsBatch.<anonymous closure> (package:analyzer_cli/src/driver.dart:830:39)
#20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#26     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:158)
#27     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:133)
#28     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#36     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#37     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#38     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#39     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#41     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#44     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#45     _StreamController._add (dart:async/stream_controller.dart:635)
#46     _StreamController.add (dart:async/stream_controller.dart:581)
#47     _Socket._onData (dart:io-patch/socket_patch.dart:1675)
#48     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#51     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#52     _StreamController._add (dart:async/stream_controller.dart:635)
#53     _StreamController.add (dart:async/stream_controller.dart:581)
#54     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1242)
#55     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:776)
#56     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#57     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#58     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Caused by NoSuchMethodError: The getter 'functions' was called on null.
Receiver: null
Tried calling: functions
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ElementWalker.ElementWalker.forExecutable (package:analyzer/src/generated/declaration_resolver.dart:506:30)
#3      DeclarationResolver.visitDefaultFormalParameter (package:analyzer/src/generated/declaration_resolver.dart:111:17)
#4      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3415:15)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743:20)
#6      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4759:17)
#7      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:823:10)
#8      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4755:15)
#9      FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5264:18)
#10     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:847:10)
#11     DeclarationResolver.visitFunctionExpression (package:analyzer/src/generated/declaration_resolver.dart:201:43)
#12     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5259:15)
#13     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5110:26)
#14     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:835:10)
#15     DeclarationResolver.visitFunctionDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:185:37)
#16     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:435:13)
#17     DeclarationResolver.visitFunctionDeclaration (package:analyzer/src/generated/declaration_resolver.dart:184:5)
#18     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5103:15)
#19     FunctionDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5155:27)
#20     RecursiveAstVisitor.visitFunctionDeclarationStatement (package:analyzer/dart/ast/visitor.dart:841:10)
#21     FunctionDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5151:15)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743:20)
#23     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1287:17)
#24     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:625:10)
#25     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1283:15)
#26     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1231:13)
#27     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:631:10)
#28     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1227:15)
#29     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5265:12)
#30     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:847:10)
#31     DeclarationResolver.visitFunctionExpression (package:analyzer/src/generated/declaration_resolver.dart:201:43)
#32     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5259:15)
#33     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5110:26)
#34     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:835:10)
#35     DeclarationResolver.visitFunctionDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:185:37)
#36     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:435:13)
#37     DeclarationResolver.visitFunctionDeclaration (package:analyzer/src/generated/declaration_resolver.dart:184:5)
#38     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5103:15)
#39     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743:20)
#40     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2452:21)
#41     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:685:10)
#42     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2445:15)
#43     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:45:12)
#44     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1081:33)
#45     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339:9)
#46     AnalysisTask.perform (package:analyzer/task/model.dart:238:7)
#47     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#48     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
#49     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723:14)
#50     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:696:12)
#51     AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:247:22)
#52     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#53     AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:246:31)
#54     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:160:26)
#55     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:121:12)
#56     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:633:34)
#57     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:219:30)
#58     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:162:14)
#59     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#60     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:161:27)
#61     Driver.start.<anonymous closure> (package:analyzer_cli/src/driver.dart:139:16)
#62     _BatchRunner.runAsBatch.<anonymous closure> (package:analyzer_cli/src/driver.dart:830:39)
#63     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#66     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#67     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#68     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#69     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:158)
#70     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:133)
#71     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#72     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#73     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#74     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#75     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#76     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#77     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#78     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#79     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#80     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#81     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#82     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#83     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#84     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#85     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#86     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#87     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#88     _StreamController._add (dart:async/stream_controller.dart:635)
#89     _StreamController.add (dart:async/stream_controller.dart:581)
#90     _Socket._onData (dart:io-patch/socket_patch.dart:1675)
#91     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#92     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#93     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#94     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#95     _StreamController._add (dart:async/stream_controller.dart:635)
#96     _StreamController.add (dart:async/stream_controller.dart:581)
#97     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1242)
#98     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:776)
#99     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#100    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#101    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#102    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:728:7)
#1      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:696:12)
#2      AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:247:22)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#4      AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:246:31)
#5      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:160:26)
#6      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:121:12)
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:633:34)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:219:30)
#9      Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:162:14)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#11     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:161:27)
#12     Driver.start.<anonymous closure> (package:analyzer_cli/src/driver.dart:139:16)
#13     _BatchRunner.runAsBatch.<anonymous closure> (package:analyzer_cli/src/driver.dart:830:39)
#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#17     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#18     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#19     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#20     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:158)
#21     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:133)
#22     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#23     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#24     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#30     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#31     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#32     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#33     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#34     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#38     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#39     _StreamController._add (dart:async/stream_controller.dart:635)
#40     _StreamController.add (dart:async/stream_controller.dart:581)
#41     _Socket._onData (dart:io-patch/socket_patch.dart:1675)
#42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#45     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#46     _StreamController._add (dart:async/stream_controller.dart:635)
#47     _StreamController.add (dart:async/stream_controller.dart:581)
#48     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1242)
#49     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:776)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)



Command[dart2analyzer]: DART_CONFIGURATION=ReleaseX64 sdk/bin/dartanalyzer --ignore-unrecognized-flags --show-package-warnings --enable-async --packages=/usr/local/google/home/sra/Dart/sdk/.packages --machine --no-hints /usr/local/google/home/sra/Dart/sdk/tests/compiler/dart2js/analyze_all_test.dart
Took 0:00:05.343443

Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2analyzer -rnone -t240 --packages /usr/local/google/home/sra/Dart/sdk/.packages dart2js/analyze_all_test

```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by stereotype441** [comment]
Fix out for review: https://codereview.chromium.org/2437793002/
