### ISSUE TITLE
Fields aren't properly virtualized in presence of mixin

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27643]
The following code should print `17`.

```dart
abstract class B {
  int get x;
}

class C {
  int get x => 42;
}

class D extends C with B {
  final int x;

  D(this.x);
}

void main() {
  var d = new D(17);
  print(d.x);
}
```

Instead, it throws:
```
TypeError: Cannot set property x of [object Object] which has only a getter
    at D.new (/Users/vsm/ddctest/getter.js:20:14)
    at D.Object (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2045:23)
    at C (/Users/vsm/ddctest/getter.js:10:14)
    at Mixin (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:760:5)
    at D (/Users/vsm/ddctest/getter.js:18:14)
    at getter.main (/Users/vsm/ddctest/getter.js:28:13)
    at dart._checkAndCall (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:1554:16)
    at dart.dcall (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:1559:17)
    at _IsolateContext.eval (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:8912:23)
    at _isolate_helper.startRootIsolate (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:8679:19)
```

**Comment by jmesserly** [comment]
looked at the code, and mixins are handled, my guess is it's because B.x is abstract. (There's a strange thing in there that stops the search when it hits an abstract member. Never made sense to me.)

**Comment by vsmenon** [comment]
Ahh I think you're right.  This fails too:

```dart
class C {
  int get x => 42;
}

abstract class B extends C {
  int get x;
}


class D extends B {
  final int x;

  D(this.x);
}

void main() {
  var d = new D(17);
  print(d.x);
}
```

**Comment by jmesserly** [comment]
yeah ... deleting that strange bailout fixes them. Not sure if it will break something else yet (testing)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2441693003/
