### ISSUE TITLE
Could not find element with name "_onChangeCallback"

### ISSUE THREAD

**Issue by Adamovskiy** [dart-lang/sdk#27669]
When strong mode was turned on, dart analysis progress spinner became infinite.

```
2016-10-26 16:30:50,067 [ 325943]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.20.1, server version 1.17.0, error: Task failed: BuildCompilationUnitElementTask for source ~/myProject/lib/component/control/custom/custom_control.dart
Mismatch in DeclarationResolver while resolving /Users/aleksey.adamovsky/dev/projects/ok-sales/client/lib/component/control/custom/custom_control.dart
Could not find element with name "_onChangeCallback" at 263
Path to root: DeclaredSimpleIdentifier, VariableDeclarationImpl, VariableDeclarationListImpl, FieldDeclarationImpl, ClassDeclarationImpl, CompilationUnitImpl
#0      RecursiveAstVisitor&ExistingElementResolver._mismatch (package:analyzer/src/generated/resolver.dart:3464)
#1      DeclarationResolver._findWithNameAndOffset (package:analyzer/src/generated/resolver.dart:2833)
#2      DeclarationResolver._findIdentifier (package:analyzer/src/generated/resolver.dart:2791)
#3      DeclarationResolver.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:2746)
#4      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10773)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#6      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10871)
#7      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1960)
#8      DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:2763)
#9      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10865)
#10     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4316)
#11     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:1569)
#12     DeclarationResolver.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:2463)
#13     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4311)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#15     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1920)
#16     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:1425)
#17     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2353)
#18     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1852)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#20     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2452)
#21     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449)
#22     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2445)
#23     DeclarationResolver.resolve (package:analyzer/src/generated/resolver.dart:2328)
#24     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1080)
#25     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#26     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#27     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#28     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#29     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1184)
#30     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#31     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1182)
#32     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#33     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:894)
#34     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#35     _rootRun (dart:async/zone.dart:1146)
#36     _CustomZone.run (dart:async/zone.dart:1026)
#37     _CustomZone.runGuarded (dart:async/zone.dart:924)
#38     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#39     _rootRun (dart:async/zone.dart:1150)
#40     _CustomZone.run (dart:async/zone.dart:1026)
#41     _CustomZone.runGuarded (dart:async/zone.dart:924)
#42     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#43     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#44     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#45     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by alexander-doroshko** [comment]
@bwilkerson Alexey Adamovskiy is at the Dart Summit in case you have additional questions :)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
