### ISSUE TITLE
Dart Dev Compiler fails to run

### ISSUE THREAD

**Issue by Hackzzila** [dart-lang/sdk#27709]
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=C:\tools\dart-sdk --modules node -o discord.js lib/discord.dart
    dart --version: 1.20.1 (Wed Oct 12 15:07:45 2016) on "windows_x64"
```
Invalid argument(s): Uri c: must have scheme 'file:'.
#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:73)
#1      Context.fromUri (package:path/src/context.dart:834)
#2      fromUri (package:path/path.dart:354)
#3      placeSourceMap.transformUri (package:dev_compiler/src/compiler/compiler.dart:506)
#4      placeSourceMap (package:dev_compiler/src/compiler/compiler.dart:510)
#5      JSModuleFile.getCode (package:dev_compiler/src/compiler/compiler.dart:426)
#6      JSModuleFile.writeCodeSync (package:dev_compiler/src/compiler/compiler.dart:455)
#7      _compile (package:dev_compiler/src/compiler/command.dart:149)
#8      compile (package:dev_compiler/src/compiler/command.dart:51)
#9      main.<main_async_body> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:51)
#10     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

**Comment by vsmenon** [comment]
Merging with #27797
