### ISSUE TITLE
Interpolation of fixed-sized list fails in dart2js

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#27700]
```dart
main(){
  var x = new List(0);
  //  var y = x.toString();  // Add this and it works.
  var z = "$x";  // fails.
}
```

Stack trace is something like:
```
...\lib\_internal\js_runtime\lib\preambles\d8.js:263: TypeError: Cannot read property 'prototype' of undefined
          throw e;
          ^
TypeError: Cannot read property 'prototype' of undefined
    at J.getInterceptor (pl.js:721:23)
    at J.toString$0$ (pl.js:725:14)
    at dart.S (pl.js:452:15)
    at dart.main (pl.js:702:20)
    at action (c:\src\dart\sdk\out\ReleaseX64\dart-sdk\lib\_internal\js_runtime\lib\preambles\d8.js:275:31)
    at eventLoop (c:\src\dart\sdk\out\ReleaseX64\dart-sdk\lib\_internal\js_runtime\lib\preambles\d8.js:258:9)
    at self.dartMainRunner (c:\src\dart\sdk\out\ReleaseX64\dart-sdk\lib\_internal\js_runtime\lib\preambles\d8.js:276:5)
    at pl.js:867:23
    at init.currentScript (pl.js:853:7)
    at pl.js:864:5
```

Seems the interceptor for `toString` doesn't get included unless you directly call `toString`?

**Comment by sigmundch** [comment]
@johnniwinther - seems like we need to track in our world impacts that interpolations implicitly use .toString. Do you agree?

**Comment by johnniwinther** [comment]
It already is!

**Comment by rakudrama** [comment]
The actual line of the error is

```js
      return J.JSArray.prototype;
```

J.JSArray is not defined, so the missing impact is the allocation of a JSArray (or JSFixedArray).
There are several places where this constructor is handled. One is in the ssa graph builder where it is replaced with "new Array(#)".

**Comment by johnniwinther** [comment]
I'll look into it.

**Comment by johnniwinther** [comment]
A fix is ready at https://codereview.chromium.org/2624173002/
