### ISSUE TITLE
dart2js --minify fails with 'nsm_dispatcher_test.dart'

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#27715]
Starting from sdk commit 40611dd6111d5cecbd01bec2cf3bb9e2e5fb1e17 and until now (at commit a850b4c977a5b177abe17864006657111d835840), the test `nsm_dispatcher_test.dart` fails as follows (`dart2js` from commits a850b4.. and 406111d.. work the same as 1.21.0-dev.1.0 in this respect).
```
..$ dart2js --version
Dart-to-JavaScript compiler (dart2js) version: 1.21.0-dev.1.0
..$ dart2js --minify tests/kernel/unsorted/nsm_dispatcher_test.dart
tests/kernel/unsorted/nsm_dispatcher_test.dart:8:3:
Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing some optimizations.
Consider removing this 'noSuchMethod' implementation.
  noSuchMethod(Invocation invocation) {
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
..$ d8 out.js
Warning: 'a5' is used reflectively but not in MirrorsUsed. This will break minified code.
|Symbol("a5")|
/usr/local/google/home/eernst/bin/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: Expect.isTrue(false) fails.
          throw e;
          ^
Expect.isTrue(false) fails.
    at dart.c (out.js:395:3)
    at dart.ay (out.js:847:24)
    at dart.k (out.js:846:3)
    at dart.a9 (out.js:851:3)
    at action (/usr/local/google/home/eernst/bin/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (/usr/local/google/home/eernst/bin/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (/usr/local/google/home/eernst/bin/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at out.js:1017:55
    at init.currentScript (out.js:1013:55)
    at out.js:1016:84
..$ dart2js tests/kernel/unsorted/nsm_dispatcher_test.dart
tests/kernel/unsorted/nsm_dispatcher_test.dart:8:3:
Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing some optimizations.
Consider removing this 'noSuchMethod' implementation.
  noSuchMethod(Invocation invocation) {
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
..$ d8 out.js
Warning: 'fun' is used reflectively but not in MirrorsUsed. This will break minified code.
|Symbol("fun")|
Warning: 'fun' is used reflectively but not in MirrorsUsed. This will break minified code.
|Symbol("fun")|1|
Warning: 'fun' is used reflectively but not in MirrorsUsed. This will break minified code.
|Symbol("fun")|1|2|
Warning: 'fun' is used reflectively but not in MirrorsUsed. This will break minified code.
|Symbol("fun")|1|Symbol("b")/2|
Warning: 'fun' is used reflectively but not in MirrorsUsed. This will break minified code.
|Symbol("fun")|1|Symbol("a")/1|Symbol("b")/2|
Warning: 'fun' is used reflectively but not in MirrorsUsed. This will break minified code.
|Symbol("fun")|1|Symbol("a")/1|Symbol("b")/2|
```
Presumably, this test should be marked in the status file to never run with `dart2js`, to run with `dart2js` but fail with `--minify`, or the test should be modified to work correctly with `--minify`.

**Comment by mraleph** [comment]
This test is skipped on dart2js configuration for now.
