### ISSUE TITLE
SIMDBC64: Compiling dart2js with itself crashes with --trace-bailout

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#27726]
@zanderso @mraleph 
Output:
```
$ xcodebuild/ReleaseSIMDBC64/dart --trace-bailout pkg/compiler/lib/src/dart2js.dart --categories=all --library-root=`pwd`/sdk pkg/compiler/lib/src/dart2js.dart 
'file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/enum_creator.dart': bailout: line 207 pos 3: FlowGraphAllocator Bailout in createMembers: SPILL
  void createMembers() {
  ^

'dart:core-patch/string_buffer_patch.dart': bailout: line 64: FlowGraphCompiler Bailout in writeCharCode: StoreIndexed:74(v16 T{Uint16List}, v18 T{_Smi}, v27)
  @ patch void writeCharCode(int charCode) {
          ^

'dart:typed_data': bailout: line 1373: FlowGraphCompiler Bailout in _setIndexedUint16@6027147: StoreIndexed:8(v3, v17, v5 T{_Smi})
  void _setIndexedUint16(int index, int value) {
  ^

pkg/compiler/lib/src/js_emitter/startup_emitter/fragment_emitter.dart:1046:3:
Internal Error: The compiler crashed when compiling this element.
  js.Block emitLazilyInitializedStatics(Fragment fragment) {
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Invalid argument(s): _data
#0      List._GrowableList.withData (dart:core-patch/growable_array.dart:108)
#1      List._GrowableList (dart:core-patch/growable_array.dart:95)
#2      List.List._fromLiteral (dart:core-patch/array_patch.dart:66)
#3      List.List.generate (dart:core/list.dart:137)
#4      Types.substTypes (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/dart_types.dart:1420:33)
#5      FunctionType.subst (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/dart_types.dart:681:15)
#6      Types.substTypes.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/dart_types.dart:1422:32)
#7      List.List.generate (dart:core/list.dart:142)
#8      Types.substTypes (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/dart_types.dart:1420:33)
#9      FunctionType.subst (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/dart_types.dart:679:15)
#10     DartType.substByContext (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/dart_types.dart:62:12)
#11     InterfaceMember.type (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/dart_types.dart:929:36)
#12     MemberAccess.computeType (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:127:57)
#13     ElementAccess.isCallable (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:115:9)
#14     TypeCheckerVisitor.analyzeInvocation (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:997:23)
#15     TypeCheckerVisitor.visitSend (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:1364:14)
#16     Send.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:619:38)
#17     TypeCheckerVisitor.analyze (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:445:28)
#18     TypeCheckerVisitor.analyzeNonVoid (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:419:21)
#19     TypeCheckerVisitor.analyzeVariableInitializer (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:1780:31)
#20     TypeCheckerVisitor.visitVariableDefinitions (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:1794:9)
#21     VariableDefinitions.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:1800:38)
#22     TypeCheckerVisitor.analyze (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:445:28)
#23     TypeCheckerVisitor.visitNodeList (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:1671:7)
#24     NodeList.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:826:38)
#25     TypeCheckerVisitor.analyze (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:445:28)
#26     TypeCheckerVisitor.visitBlock (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:592:12)
#27     Block.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:882:38)
#28     TypeCheckerVisitor.analyze (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:445:28)
#29     TypeCheckerVisitor.visitFunctionExpression (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:670:5)
#30     FunctionExpression.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:1111:38)
#31     TypeCheckerTask.check.<anonymous closure>.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:71:28)
#32     CompilerTask.measure (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#33     TypeCheckerTask.check.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:62:7)
#34     CompilerDiagnosticReporter.withCurrentElement (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:1651:15)
#35     TypeCheckerTask.check (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/typechecker.dart:61:14)
#36     _CompilerResolution.computeWorldImpact.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:2143:26)
#37     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:262)
#38     _CompilerResolution.computeWorldImpact (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:2124:30)
#39     Compiler.analyzeElement.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:947:27)
#40     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#41     Compiler.analyzeElement (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:934:16)
#42     Compiler.analyze.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:969:35)
#43     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#44     Compiler.analyze (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:951:16)
#45     ResolutionWorkItem.run (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/resolution.dart:50:35)
#46     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:850:52)
#47     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#48     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:849:34)
#49     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#50     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:847:30)
#51     CompilerDiagnosticReporter.withCurrentElement (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:1651:15)
#52     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:845:20)
#53     QueueFilter.processWorkItem (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/enqueue.dart:852:6)
#54     ResolutionEnqueuer.forEach (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/enqueue.dart:663:16)
#55     Compiler.emptyQueue.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:844:15)
#56     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#57     Compiler.emptyQueue (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:843:16)
#58     Compiler.processQueue.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:884:9)
#59     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#60     Compiler.processQueue (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:857:16)
#61     Compiler.compileLoadedLibraries.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:693:9)
#62     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#63     Compiler.compileLoadedLibraries (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:649:16)
#64     Compiler.runInternal.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:559:7)
#65     _RootZone.runUnary (dart:async/zone.dart:1404)
#66     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#67     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#68     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#69     _Future._completeWithValue (dart:async/future_impl.dart:477)
#70     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#71     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#72     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#73     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by fsc8000** [comment]
Also crashes with 32-bit SIMDBC:
```
$ xcodebuild/ReleaseSIMDBC/dart --trace-bailout pkg/compiler/lib/src/dart2js.dart --categories=all --library-root=`pwd`/sdk pkg/compiler/lib/src/dart2js.dart 
'file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/enum_creator.dart': bailout: line 207 pos 3: FlowGraphAllocator Bailout in createMembers: SPILL
  void createMembers() {
  ^

'dart:core-patch/string_buffer_patch.dart': bailout: line 64: FlowGraphCompiler Bailout in writeCharCode: StoreIndexed:74(v16 T{Uint16List}, v18 T{_Smi}, v27)
  @ patch void writeCharCode(int charCode) {
          ^

'dart:typed_data': bailout: line 1373: FlowGraphCompiler Bailout in _setIndexedUint16@6027147: StoreIndexed:8(v3, v17, v5 T{_Smi})
  void _setIndexedUint16(int index, int value) {
  ^

pkg/compiler/lib/src/js_emitter/startup_emitter/fragment_emitter.dart:783:3:
Internal Error: The compiler crashed when compiling this element.
  Map<js.Expression, js.Expression> emitInstanceMethod(Method method) {
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: Class 'String' has no instance getter 'kind'.
Receiver: "_TypedList"
Tried calling: kind
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ResolverVisitor.handleLocalAccess (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:2509:25)
#3      ResolverVisitor.handleResolvedSend (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:2897:14)
#4      ResolverVisitor.handleUnqualifiedSend (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:2977:14)
#5      ResolverVisitor.visitSend (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:3015:14)
#6      Send.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:619:38)
#7      CommonResolverVisitor.visit (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#8      ResolverVisitor.visitExpressionPrefix (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:1095:31)
#9      ResolverVisitor.handleQualifiedSend (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:2349:31)
#10     ResolverVisitor.visitSend (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:3012:14)
#11     Send.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:619:38)
#12     CommonResolverVisitor.visit (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#13     ResolverVisitor.visitExpression (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:1083:31)
#14     ResolverVisitor.handleLogicalAnd.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:1262:40)
#15     ResolverVisitor.doInPromotionScope (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:218:24)
#16     ResolverVisitor.handleLogicalAnd (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:1262:9)
#17     ResolverVisitor.handleOperatorSend (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:1666:20)
#18     ResolverVisitor.visitSend (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:3009:14)
#19     Send.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:619:38)
#20     CommonResolverVisitor.visit (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#21     ResolverVisitor.visitParenthesizedExpression (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:3799:31)
#22     ParenthesizedExpression.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:1905:38)
#23     CommonResolverVisitor.visit (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#24     ResolverVisitor.visitIf.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:608:57)
#25     ResolverVisitor.doInPromotionScope (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:218:24)
#26     ResolverVisitor.visitIf (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:608:5)
#27     If.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:914:38)
#28     CommonResolverVisitor.visit (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#29     ResolverVisitor.visitNodeList (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:3552:7)
#30     NodeList.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:826:38)
#31     CommonResolverVisitor.visit (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#32     ResolverVisitor.visitIn (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:494:31)
#33     ResolverVisitor.visitBlock (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:514:5)
#34     Block.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:882:38)
#35     CommonResolverVisitor.visit (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#36     ResolverVisitor.visitIn (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:494:31)
#37     ResolverVisitor.visitIf.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:610:30)
#38     ResolverVisitor.doInPromotionScope (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:218:24)
#39     ResolverVisitor.visitIf (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:609:5)
#40     If.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:914:38)
#41     CommonResolverVisitor.visit (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#42     ResolverVisitor.visitNodeList (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:3552:7)
#43     NodeList.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:826:38)
#44     CommonResolverVisitor.visit (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#45     ResolverVisitor.visitIn (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:494:31)
#46     ResolverVisitor.visitBlock (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/members.dart:514:5)
#47     Block.accept (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/tree/nodes.dart:882:38)
#48     CommonResolverVisitor.visit (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:30:54)
#49     ResolverTask.resolveMethodElementImplementation.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution.dart:264:17)
#50     CompilerDiagnosticReporter.withCurrentElement (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:1651:15)
#51     ResolverTask.resolveMethodElementImplementation (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution.dart:219:21)
#52     ResolverTask.resolveMethodElement.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution.dart:347:16)
#53     CompilerDiagnosticReporter.withCurrentElement (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:1651:15)
#54     ResolverTask.resolveMethodElement (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution.dart:300:21)
#55     ResolverTask.resolve.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution.dart:105:32)
#56     CompilerTask.measure (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#57     ResolverTask.resolve (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/resolution/resolution.dart:85:12)
#58     _CompilerResolution.computeWorldImpact.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:2128:61)
#59     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:262)
#60     _CompilerResolution.computeWorldImpact (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:2124:30)
#61     Compiler.analyzeElement.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:947:27)
#62     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#63     Compiler.analyzeElement (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:934:16)
#64     Compiler.analyze.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:969:35)
#65     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#66     Compiler.analyze (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:951:16)
#67     ResolutionWorkItem.run (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/resolution.dart:50:35)
#68     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:850:52)
#69     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#70     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:849:34)
#71     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#72     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:847:30)
#73     CompilerDiagnosticReporter.withCurrentElement (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:1651:15)
#74     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:845:20)
#75     QueueFilter.processWorkItem (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/enqueue.dart:852:6)
#76     ResolutionEnqueuer.forEach (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/enqueue.dart:663:16)
#77     Compiler.emptyQueue.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:844:15)
#78     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#79     Compiler.emptyQueue (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:843:16)
#80     Compiler.processQueue.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:884:9)
#81     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#82     Compiler.processQueue (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:857:16)
#83     Compiler.compileLoadedLibraries.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:693:9)
#84     CompilerTask.measureSubtask (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#85     Compiler.compileLoadedLibraries (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:649:16)
#86     Compiler.runInternal.<anonymous closure> (file:///Users/fschneider/dartgit/sdk/pkg/compiler/lib/src/compiler.dart:559:7)
#87     _RootZone.runUnary (dart:async/zone.dart:1404)
#88     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#89     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#90     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#91     _Future._completeWithValue (dart:async/future_impl.dart:477)
#92     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#93     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#94     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#95     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#96     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by zanderso** [comment]
I remember having problems with `--trace-bailout` without `--no-background-compilation`. Does that make any difference?

**Comment by fsc8000** [comment]
Indeed. This seems to be an issue with --trace-bailout and background compilation.

**Comment by alexmarkov** [comment]
Closing this issue as SIMDBC64 mode was removed a while ago.
