### ISSUE TITLE
Attempt to use import prefix as a type argument causes exception

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27763]
The code like this:
```dart
import 'dart:io' as pp;

class C {
  List<pp> v;
}
```

Causes the following exception.

```
Dart analysis server, SDK version 1.21.0-edge.9ebef9af7c7086a4e0f935b3ebd29aa4e990da91, server version 1.17.0, error: Task failed: PartiallyResolveUnitReferencesTask for source /Users/scheglov/dart/test2/bin/test.dart
Unexpected exception while performing PartiallyResolveUnitReferencesTask for source /Users/scheglov/dart/test2/bin/test.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:351:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723:14)
#5      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:671:12)
#6      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:482:54)
#7      PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:899:15)
#8      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:471:20)
#9      AnalysisDriver.results.results_async_gen_body> (package:analyzer/src/dart/analysis/driver.dart:288:35)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#11     _rootRunUnary (dart:async/zone.dart:1158)
#12     _CustomZone.runUnary (dart:async/zone.dart:1037)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#16     _Future._complete (dart:async/future_impl.dart:467)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#18     _Monitor.signal.signal_async_body> (package:analyzer/src/dart/analysis/driver.dart:1020:3)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#20     _rootRunUnary (dart:async/zone.dart:1158)
#21     _CustomZone.runUnary (dart:async/zone.dart:1037)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#23     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#24     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#25     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342)
#26     _rootRun (dart:async/zone.dart:1150)
#27     _CustomZone.run (dart:async/zone.dart:1026)
#28     _CustomZone.runGuarded (dart:async/zone.dart:924)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by UnimplementedError
#0      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:1254:7)
#1      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1612:28)
#2      _UnitResynthesizer.buildType.getTypeArgument (package:analyzer/src/summary/resynthesize.dart:1605:18)
#3      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1283:45)
#4      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:1249:15)
#5      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1612:28)
#6      _ResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:1418:31)
#7      NonParameterVariableElementImpl.type (package:analyzer/src/dart/element/element.dart:6777:16)
#8      ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:6448:52)
#9      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10864:15)
#10     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4315:17)
#11     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6297:10)
#12     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4642:27)
#13     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:2582:53)
#14     ResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:5863:34)
#15     PartialResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:4637:39)
#16     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4310:15)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7742:20)
#18     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:7295:18)
#19     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7272:11)
#20     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5580:34)
#21     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1851:15)
#22     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5646:25)
#23     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2444:15)
#24     PartiallyResolveUnitReferencesTask.internalPerform (package:analyzer/src/task/dart.dart:4280:10)
#25     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339:9)
#26     AnalysisTask.perform (package:analyzer/task/model.dart:238:7)
#27     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#28     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
#29     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723:14)
#30     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:671:12)
#31     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:482:54)
#32     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:899:15)
#33     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:471:20)
#34     AnalysisDriver.results.results_async_gen_body> (package:analyzer/src/dart/analysis/driver.dart:288:35)
#35     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#36     _rootRunUnary (dart:async/zone.dart:1158)
#37     _CustomZone.runUnary (dart:async/zone.dart:1037)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#39     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#40     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#41     _Future._complete (dart:async/future_impl.dart:467)
#42     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#43     _Monitor.signal.signal_async_body> (package:analyzer/src/dart/analysis/driver.dart:1020:3)
#44     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#45     _rootRunUnary (dart:async/zone.dart:1158)
#46     _CustomZone.runUnary (dart:async/zone.dart:1037)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#48     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#49     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#50     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342)
#51     _rootRun (dart:async/zone.dart:1150)
#52     _CustomZone.run (dart:async/zone.dart:1026)
#53     _CustomZone.runGuarded (dart:async/zone.dart:924)
#54     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#55     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#56     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#57     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#58     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/2658123004

**Comment by scheglov** [comment]
This was fixed.
