### ISSUE TITLE
If the target directory doesn't exist, give a better error

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#27771]
dartdevc arguments: --dart-sdk=/Users/kevmoo/homebrew/Cellar/dart/1.21.0-dev.4.0/libexec --modules common -o out/foo.js bin/main.dart
    dart --version: 1.21.0-dev.4.0 (Thu Nov  3 17:24:26 2016) on "macos_x64"
```
FileSystemException: Cannot open file, path = 'out/foo.js' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:562)
#1      _File.openSync (dart:io/file_impl.dart:413)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:531)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:555)
#4      JSModuleFile.writeCodeSync (package:dev_compiler/src/compiler/compiler.dart:505)
#5      _compile (package:dev_compiler/src/compiler/command.dart:157)
#6      compile (package:dev_compiler/src/compiler/command.dart:51)
#7      main.<main_async_body> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:51)
#8      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by jmesserly** [comment]
Should probably just create the directory?

**Comment by kevmoo** [comment]
Either one is better than the current story. 😄 

I'm fine if we make the user create it – ensures they know where it's going, etc.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2483753004
