### ISSUE TITLE
Analysis server consumes large amounts of RAM and causes machine to become unresponsive

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27770]
Original report in [analyzer-discuss](https://groups.google.com/a/dartlang.org/d/msg/analyzer-discuss/bEwWgjkveGo/hpV_50jVCgAJ).

I was converting [a Python repo from GitHub](https://github.com/PyAndy/FootballGame) to Dart as an exercise in testing [Dart Code](https://marketplace.visualstudio.com/items?itemName=DanTup.dart-code) and my machine became really unresponsive. I opened Task Manager (it took several minutes!) and noticed the "memory (working set)" value for the Dart VM running the analysis server was over 6GB in size (I have 8 GB physical RAM). I terminated it and continued and after 10-15 mins, the same happened again.

There's an error in the analysis server output when this happens:

```text
{
  "error": {
    "code": "SERVER_ERROR",
    "message": "The null object does not have a method '-'.


NoSuchMethodError: method not found: '-'
Receiver: null
Arguments: [2748]",
    "stackTrace": "#0      Object._noSuchMethod (dart:core-patch\/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch\/object_patch.dart:47)
#2      _UpdateElementOffsetsVisitor.visitElement (package:analyzer\/src\/task\/incremental_element_builder.dart:754)
#3      GeneralizingElementVisitor.visitVariableElement (package:analyzer\/dart\/element\/visitor.dart:178)
#4      GeneralizingElementVisitor.visitPropertyInducingElement (package:analyzer\/dart\/element\/visitor.dart:168)
#5      GeneralizingElementVisitor.visitFieldElement (package:analyzer\/dart\/element\/visitor.dart:111)
#6      FieldElementImpl.accept (package:analyzer\/src\/dart\/element\/element.dart:4241)
#7      IncrementalCompilationUnitElementBuilder._replaceNode (package:analyzer\/src\/task\/incremental_element_builder.dart:516)
#8      IncrementalCompilationUnitElementBuilder._processClassMembers (package:analyzer\/src\/task\/incremental_element_builder.dart:324)
#9      IncrementalCompilationUnitElementBuilder._processUnitMembers (package:analyzer\/src\/task\/incremental_element_builder.dart:463)
#10     IncrementalCompilationUnitElementBuilder.build (package:analyzer\/src\/task\/incremental_element_builder.dart:140)
#11     AnalysisContextImpl._sourceChanged (package:analyzer\/src\/context\/context.dart:1845)
#12     AnalysisContextImpl.handleContentsChanged (package:analyzer\/src\/context\/context.dart:1064)
#13     AnalysisServer.updateContent.<anonymous closure>.<anonymous closure> (package:analysis_server\/src\/analysis_server.dart:1360)
#14     List.forEach (dart:core-patch\/growable_array.dart:258)
#15     AnalysisServer.updateContent.<anonymous closure> (package:analysis_server\/src\/analysis_server.dart:1353)
#16     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch\/compact_hash.dart:351)
#17     AnalysisServer..."
  }
}
```

I can reliably reproduce this by opening the attached `start_state` project and performing the following:

1. Open file `team.dart`
2. Find the code `def play_round(self):`
3. Delete the colon
4. Type opening `{` in its place
5. Add closing `}` after the `self.ladder()` call
6. Find the code `def ladder(self)` and put cursor before the `d` in `def`
7. Press `del` 4 times to remove the `def `

Note: In step 4 where I type `{`, the editor inserts `{}`, I don't know if that matters.

Attached is the starting state of the project, the end state (to make it clearer the changes I made) and the analysis server log.

- [analyzer log.zip](https://github.com/dart-lang/sdk/files/573992/analyzer.log.zip)
- [start_state.zip](https://github.com/dart-lang/sdk/files/573990/start_state.zip)
- [end_state.zip](https://github.com/dart-lang/sdk/files/573991/end_state.zip)

Here are some earlier screenshots I took while trying to figure out what was happening; they might not be useful.

![dart_prof](https://cloud.githubusercontent.com/assets/1078012/20040088/0455fff8-a449-11e6-8b8e-f89dbe136330.png)
![dart_ram](https://cloud.githubusercontent.com/assets/1078012/20040089/04578094-a449-11e6-999a-3f23102ca480.png)

**Comment by bwilkerson** [comment]
@scheglov It would be interesting to see how this case works under the analysis driver.

**Comment by scheglov** [comment]
At the moment it fails with the following exception.
```
Caused by Bad state: Invalid attempt to set a compile-time constant result |dynamic keylambda|
#0      VariableElementImpl.evaluationResult= (package:analyzer/src/dart/element/element.dart:8387:5)
#1      ConstantVerifier._validateDefaultValues (package:analyzer/src/generated/resolver.dart:1693:17)
#2      ConstantVerifier.visitConstructorDeclaration (package:analyzer/src/generated/resolver.dart:1303:5)
```
The reason is that we create `ParameterElementImpl` insetad of `DefaultParameterElementImpl`.
I'm looking why this happens.

**Comment by scheglov** [comment]
Hm... The AST is inconsistent.
This `sorted` is parsed as `ConstructorDeclarationImpl`.
We create `DefaultFormalParameterImpl` with a default value, but with `kind == REQUIRED`.

```Dart
sorted(self.teams , [key = lambda, t : -t.wins]) : print = ('{}: {} wins'.format(team, team.wins));
```

```Python
    def ladder(self):
        for team in sorted(self.teams, key=lambda t: -t.wins):
            print('{}: {} wins'.format(team, team.wins))
```

Then, later, when we resynthesize in `factory ParameterElementImpl.forSerializedFactory`, we create `ParameterElementImpl` instead of `DefaultParameterElementImpl`.
```Dart
      if (unlinkedParameter.kind == UnlinkedParamKind.required) {
        element = new ParameterElementImpl.forSerialized(
            unlinkedParameter, enclosingElement);
      } else {
        element = new DefaultParameterElementImpl.forSerialized(
            unlinkedParameter, enclosingElement);
      }
```

I guess we should use `kind == ParameterKind.POSITIONAL` instead.

**Comment by scheglov** [comment]
OK, I patched parameters parsing. And worked around another bug with `from helpers import select_from_menu` which in Dart we parse as an import directive without a URI, and later have problem to resolve it, so in `SummaryResynthesized.getLibraryElement()` the `librarySource` is `null`.

After this with the new driver everything works smoothly, using `97 MB` of heap.

**Comment by scheglov** [comment]
[CL](https://codereview.chromium.org/2477183002) for parameters parsing.

**Comment by DanTup** [comment]
@scheglov It's not clear what the status of this is - is there still work to do? If not, should this show up in the dev builds yet? I tested with `Dart-1.21.0-dev.7.0` but there's still an error as soon as I replace the `:` with `{}` (details below). Apologies if this is expected/unfinished, I was just testing something related so it was convenient to re-test.

NoSuchMethodError: The method '_subFromInteger' was called on null.
Receiver: null
Tried calling: _subFromInteger(2057)

```text
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      int.- (dart:core-patch/integers.dart:15)
#3      _UpdateElementOffsetsVisitor.visitElement (package:analyzer/src/task/incremental_element_builder.dart:754)
#4      GeneralizingElementVisitor.visitVariableElement (package:analyzer/dart/element/visitor.dart:178)
#5      GeneralizingElementVisitor.visitPropertyInducingElement (package:analyzer/dart/element/visitor.dart:168)
#6      GeneralizingElementVisitor.visitFieldElement (package:analyzer/dart/element/visitor.dart:111)
#7      FieldElementImpl.accept (package:analyzer/src/dart/element/element.dart:4245)
#8      IncrementalCompilationUnitElementBuilder._replaceNode (package:analyzer/src/task/incremental_element_builder.dart:516)
#9      IncrementalCompilationUnitElementBuilder._processClassMembers (package:analyzer/src/task/incremental_element_builder.dart:324)
#10     IncrementalCompilationUnitElementBuilder._processUnitMembers (package:analyzer/src/task/incremental_element_builder.dart:463)
#11     IncrementalCompilationUnitElementBuilder.build (package:analyzer/src/task/incremental_element_builder.dart:140)
#12     AnalysisContextImpl._sourceChanged (package:analyzer/src/context/context.dart:1854)
#13     AnalysisContextImpl.handleContentsChanged (package:analyzer/src/context/context.dart:1073)
#14     AnalysisServer.updateContent.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1522)
#15     List.forEach (dart:core-patch/growable_array.dart:258)
#16     AnalysisServer.updateContent.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1515)
#17     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:348)
#18     AnalysisServer.updateContent (package:analysis_server/src/analysis_server.dart:1460)
#19     AnalysisDomainHandler.updateContent (package:analysis_server/src/domain_analysis.dart:313)
#20     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:219)
#21     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:845)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#23     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:841)
#24     _rootRun (dart:async/zone.dart:1150)
#25     _CustomZone.run (dart:async/zone.dart:1026)
#26     _CustomZone.runGuarded (dart:async/zone.dart:924)
#27     runZoned (dart:async/zone.dart:1501)
#28     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:840)
#29     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)
#30     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#31     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161)
#32     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
#33     _rootRunUnary (dart:async/zone.dart:1158)
#34     _CustomZone.runUnary (dart:async/zone.dart:1037)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#41     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:158)
#42     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:133)
#43     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#45     _rootRunUnary (dart:async/zone.dart:1158)
#46     _CustomZone.runUnary (dart:async/zone.dart:1037)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#50     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#51     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#52     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#53     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#54     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#55     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#56     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#57     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#58     _rootRunUnary (dart:async/zone.dart:1158)
#59     _CustomZone.runUnary (dart:async/zone.dart:1037)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#63     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#64     _StreamController._add (dart:async/stream_controller.dart:635)
#65     _StreamController.add (dart:async/stream_controller.dart:581)
#66     _Socket._onData (dart:io-patch/socket_patch.dart:1680)
#67     _rootRunUnary (dart:async/zone.dart:1162)
#68     _CustomZone.runUnary (dart:async/zone.dart:1037)
#69     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#70     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#71     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#72     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#73     _StreamController._add (dart:async/stream_controller.dart:635)
#74     _StreamController.add (dart:async/stream_controller.dart:581)
#75     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#76     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:781)
#77     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#78     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#79     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#80     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by DanTup** [comment]
@bwilkerson @scheglov FWIW, the error in the original issue here seems to be happening quite a bit to people using Dart Code. I recently added some analytics for crashes and in 262 sessions in the last 2 days there were 575 instances of `The null object does not have a method '-'.`. Analytics doesn't seem to let me group by any session info, so unfortunately I can't tell whether that's 1 user with 575 occurrences or 262 users with a few occurrences (nor can I tell if it's consuming their machine in the way it did mine; I don't know for sure whether the unstable system was specifically caused by that error).

![Errors](https://cloud.githubusercontent.com/assets/1078012/20573094/1f932b64-b1a6-11e6-87e7-d011fb8d0627.png)

Let me know if you'd like me to do any testing against a dev SDK if/when you think this should be fixed.

**Comment by scheglov** [comment]
We decided to [turn off](https://github.com/dart-lang/sdk/commit/2301e67340ec89d41b241960fa7e87c3735cdd15) the functionality that causes the first and the second exceptions.

**Comment by DanTup** [comment]
Ok, I'll try and give a test in `1.21.0-dev.9.0` this week and confirm it's all working with my samples. Thanks!

**Comment by DanTup** [comment]
Indeed, I am unable to repro any of these issues with `1.21.0-dev.9.0` 👍

**Comment by bwilkerson** [comment]
Excellent! I'll assume this was fixed, but let us know if you see it again.
