### ISSUE TITLE
DDC - SDK path resolution failure on Windows

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/sdk#27797]
## Try No 1:

I could not execute dartdevc against a single file. This is what I tried (on Win 10):

    dartdevc arguments: --dart-sdk=C:\tools\dart-sdk -o out\ddc_apt.js lib\ddc_apt.dart
    dart --version: 1.20.1 (Wed Oct 12 15:07:45 2016) on "windows_x64"
```
Invalid argument(s): Uri c: must have scheme 'file:'.
#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:73)
#1      Context.fromUri (package:path/src/context.dart:834)
#2      fromUri (package:path/path.dart:354)
#3      placeSourceMap.transformUri (package:dev_compiler/src/compiler/compiler.dart:506)
#4      placeSourceMap (package:dev_compiler/src/compiler/compiler.dart:510)
#5      JSModuleFile.getCode (package:dev_compiler/src/compiler/compiler.dart:426)
#6      JSModuleFile.writeCodeSync (package:dev_compiler/src/compiler/compiler.dart:455)
#7      _compile (package:dev_compiler/src/compiler/command.dart:149)
#8      compile (package:dev_compiler/src/compiler/command.dart:51)
#9      main.<main_async_body> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:51)
#10     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

The Dart SDK is found properly, it is located at `C:\tools\dart-sdk`.

## Try No 2:

My command was:
`dartdevc -o out\ddc_apt.js --dart-sdk="file:///c:/tools/dart-sdk" lib\ddc_apt.dart`

**Error report:**

    dartdevc arguments: --dart-sdk=C:\tools\dart-sdk -o out\ddc_apt.js --dart-sdk=file:///c:/tools/dart-sdk lib\ddc_apt.dart
    dart --version: 1.20.1 (Wed Oct 12 15:07:45 2016) on "windows_x64"
```
AnalysisException: Could not create a source for dart:core

#0      AnalysisContextImpl.typeProvider (package:analyzer/src/context/context.dart:539)
#1      ModuleCompiler.ModuleCompiler (package:dev_compiler/src/compiler/compiler.dart:93)
#2      _compile (package:dev_compiler/src/compiler/command.dart:86)
#3      compile (package:dev_compiler/src/compiler/command.dart:51)
#4      main.<main_async_body> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:51)
#5      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

## Try No 3:

Tried to provide it with summary file based on this conversation:  https://gitter.im/dart-lang/dev_compiler/archives/2016/09/16

dartdevc -o out\ddc_apt.js --dart-sdk="file:///c:/tools/dart-sdk" --dart-sdk-summary="file:///c:/tools/dart-sdk/lib/_internal/strong.sum" lib\ddc_apt.dart

**Error:**

    dartdevc arguments: --dart-sdk=C:\tools\dart-sdk -o out\ddc_apt.js --dart-sdk=file:///c:/tools/dart-sdk --dart-sdk-summary=file:///c:/tools/dart-sdk/lib/_internal/strong.sum lib\ddc_apt.dart
    dart --version: 1.20.1 (Wed Oct 12 15:07:45 2016) on "windows_x64"
```
FileSystemException: Cannot open file, path = 'file:///c:/tools/dart-sdk/lib/_internal/strong.sum' (OS Error: blah-blah in Hungarian.
, errno = 123)
#0      _File.throwIfError (dart:io/file_impl.dart:562)
#1      _File.openSync (dart:io/file_impl.dart:413)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:473)
#3      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:434)
#4      List.forEach (dart:core-patch/growable_array.dart:258)
#5      SummaryDataStore.SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:365)
#6      SummaryBasedDartSdk.SummaryBasedDartSdk (package:analyzer/src/summary/summary_sdk.dart:119)
#7      createSdkPathResolver (package:dev_compiler/src/analyzer/context.dart:170)
#8      ModuleCompiler.ModuleCompiler (package:dev_compiler/src/compiler/compiler.dart:79)
#9      _compile (package:dev_compiler/src/compiler/command.dart:86)
#10     compile (package:dev_compiler/src/compiler/command.dart:51)
#11     main.<main_async_body> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:51)
#12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

I also tried to replace the file URI with "windowsy" path (c:\tools\dart-sdk...) but I received the same `Invalid argument(s): Uri c: must have scheme 'file:'.` error as in try 1.

**Comment by daniel-v** [comment]
My report could be a duplicate of #27709 .

**Comment by daniel-v** [comment]
Update: The same error still occurs with Dart version 1.21.0

**Comment by daniel-v** [comment]
With dart-lang/source_span#13 I was able to execute the `dartdevc`.

**Comment by daniel-v** [comment]
Good news, thanks!
