### ISSUE TITLE
Dart analyzer crashes while performing GenerateLintsTask

### ISSUE THREAD

**Issue by ajrcarey** [dart-lang/sdk#27795]
Output from dartanalyzer:

```
Analyzing [lib/src/foundation/optional/later.dart]...
Unhandled exception:
AnalysisException: Cannot compute DART_ERRORS for /home/alastair/.decrypt/Documents/Programming/Duet/src/web/lib/src/foundation/optional/later.dart
Caused by Unexpected exception while performing GenerateLintsTask for source /home/alastair/.decrypt/Documents/Programming/Duet/src/web/lib/src/foundation/optional/later.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:351)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:722)
#5      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:670)
#6      AnalyzerImpl.prepareErrors.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:128)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#8      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:126)
#9      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:162)
#10     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:121)
#11     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:630)
#12     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:219)
#13     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:162)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#15     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:161)
#16     Driver.start (package:analyzer_cli/src/driver.dart:142)
#17     main (file:///tmp/tmp0W_1tF/dart-1.20.1/dart/pkg/analyzer_cli/bin/analyzer.dart:11)
#18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'parameters'.

NoSuchMethodError: method not found: 'parameters'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _Visitor.visitMethodDeclaration (package:linter/src/rules/parameter_assignments.dart:81)
#3      DelegatingAstVisitor.visitMethodDeclaration.<anonymous closure> (package:analyzer/dart/ast/visitor.dart:597)
#4      List.forEach (dart:core-patch/growable_array.dart:258)
#5      DelegatingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:597)
#6      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7226)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#8      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1920)
#9      DelegatingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:224)
#10     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1852)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2452)
#13     DelegatingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:252)
#14     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2445)
#15     GenerateLintsTask.internalPerform (package:analyzer/src/task/dart.dart:3262)
#16     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#17     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#18     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#19     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#20     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:722)
#21     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:670)
#22     AnalyzerImpl.prepareErrors.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:128)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#24     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:126)
#25     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:162)
#26     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:121)
#27     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:630)
#28     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:219)
#29     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:162)
#30     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#31     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:161)
#32     Driver.start (package:analyzer_cli/src/driver.dart:142)
#33     main (file:///tmp/tmp0W_1tF/dart-1.20.1/dart/pkg/analyzer_cli/bin/analyzer.dart:11)
#34     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:727)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:670)
#2      AnalyzerImpl.prepareErrors.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:128)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:126)
#5      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:162)
#6      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:121)
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:630)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:219)
#9      Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:162)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#11     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:161)
#12     Driver.start (package:analyzer_cli/src/driver.dart:142)
#13     main (file:///tmp/tmp0W_1tF/dart-1.20.1/dart/pkg/analyzer_cli/bin/analyzer.dart:11)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

The source file in question:

```
import 'package:duet/foundation/annotation.dart';
import 'optional.dart';

@sealed
class Later<T> {

  // Wraps a value that can be declared final now, but not set until later.
  // Once set, the value is final and cannot be changed.

  // Example usage:

  // final Later<int> x = new Later<int>();

  // ... (later) ...

  // this.x.set(5); // ok

  // ... (later) ...

  // this.x.set(10); // throws LaterAlreadyInitializedError exception

  Optional<T> _value = new Optional<T>.Null();

  bool get isSet => this._value.isNotEmpty;

  bool get isNotSet => !this.isSet;

  void set(T value) {
    if (this._value.isNotEmpty) {
      throw new LaterAlreadyInitializedError();
    } else {
      this._value = new Optional<T>(value);
    }
  }

  Optional<T> get value => this._value;

  T get unwrap => this._value.orElseThrow(new LaterNotInitializedException());

  Later<T> ifSet(f(T t)) {
    this._value.ifPresent(f);
    return this;
  }

  T orElseSet(Supplier<T> supplier) {
    if (this.isNotSet) {
      this.set(supplier());
    }

    return this.unwrap;
  }

}

@locked
class LaterAlreadyInitializedError
extends Error {}

@locked
class LaterNotInitializedException
implements Exception {}
```

If the problem is in the imported annotations package or optional.dart, I am happy to submit those as well.

This is on Ubuntu 16.10 with dartanalyzer 1.20.1. The problem did not occur in 1.19.

**Comment by bwilkerson** [comment]
Thanks for the report! This issue has been fixed in bleeding edge, but apparently that fix hasn't made it into the latest dev release.

You should probably disable the lint for now, then re-enable it when you update to the next release.
