### ISSUE TITLE
Search match has no element

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27799]
```
Failed to handle request,"The null object does not have a getter 'context'.

NoSuchMethodError: method not found: 'context'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      newLocation_fromMatch (package:analysis_server/src/protocol_server.dart:157)
#3      newSearchResult_fromMatch (package:analysis_server/src/protocol_server.dart:198)
#4      SearchDomainHandler.toResult (package:analysis_server/src/search/search_domain.dart:232)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:416)
#6      ListIterable.toList (dart:_internal/iterable.dart:222)
#7      SearchDomainHandler._sendSearchNotification (package:analysis_server/src/search/search_domain.dart:213)
#8      SearchDomainHandler.findTopLevelDeclarations.<findTopLevelDeclarations_async_body> (package:analysis_server/src/search/search_domain.dart:138)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#10     _rootRunUnary (dart:async/zone.dart:1166)
#11     _CustomZone.runUnary (dart:async/zone.dart:1045)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#15     _Future._complete (dart:async/future_impl.dart:467)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#17     SearchEngineImpl._searchDefinedNames.<_searchDefinedNames_async_body> (package:analysis_server/src/services/search/search_engine_internal.dart:144)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#19     _rootRunUnary (dart:async/zone.dart:1166)
#20     _CustomZone.runUnary (dart:async/zone.dart:1045)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#22     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#23     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#24     _Future._complete (dart:async/future_impl.dart:467)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#26     Index._mergeLocations.<_mergeLocations_async_body> (package:analysis_server/src/services/index/index.dart:141)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#28     _rootRunUnary (dart:async/zone.dart:1166)
#29     _CustomZone.runUnary (dart:async/zone.dart:1045)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#31     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#32     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#33     _Future._complete (dart:async/future_impl.dart:467)
#34     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#35     _ContextIndex._mergeLocations.<_mergeLocations_async_body> (package:analysis_server/src/services/index/index.dart:319)
#36     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#37     _rootRun (dart:async/zone.dart:1154)
#38     _CustomZone.run (dart:async/zone.dart:1034)
#39     _CustomZone.runGuarded (dart:async/zone.dart:932)
#40     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:959)
#41     _rootRun (dart:async/zone.dart:1158)
#42     _CustomZone.run (dart:async/zone.dart:1034)
#43     _CustomZone.runGuarded (dart:async/zone.dart:932)
#44     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:959)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by scheglov** [comment]
This is one of the race conditions which used to exists in Analysis Server.
This errors does not happen with Analysis Driver.
