### ISSUE TITLE
Segfault in runtime/bin/socket.cc

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#27847]
Running the following test sometimes triggers a segfault:
```
out/ReleaseX64/dart --print-stacktrace-at-throw --enable_asserts --enable_type_checks --packages=.packages tests/standalone/io/socket_source_address_test.dart
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000005dc7fb in dart::bin::ListeningSocketRegistry::CloseOneSafe (this=this@entry=0x2648040, os_socket=0x3c121e0) at runtime/bin/socket.cc:193
193	    current = current->next;
(gdb) bt
#0  0x00000000005dc7fb in dart::bin::ListeningSocketRegistry::CloseOneSafe (this=this@entry=0x2648040, os_socket=0x3c121e0) at runtime/bin/socket.cc:193
#1  0x00000000005dc952 in CloseOneSafe (os_socket=<optimized out>, this=<optimized out>) at runtime/bin/socket.cc:182
#2  CloseAllSafe (this=0x2648040) at runtime/bin/socket.cc:217
#3  ~ListeningSocketRegistry (this=0x2648040, __in_chrg=<optimized out>) at runtime/bin/socket.h:381
#4  dart::bin::ListeningSocketRegistry::Cleanup () at runtime/bin/socket.cc:44
#5  0x00000000005cfdad in dart::bin::EventHandler::Stop () at runtime/bin/eventhandler.cc:103
#6  0x000000000058fe14 in dart::bin::ErrorExit (exit_code=exit_code@entry=255, format=format@entry=0xd5318e "%s\n") at runtime/bin/main.cc:150
#7  0x0000000000598a88 in dart::bin::RunMainIsolate (script_name=script_name@entry=0x7ffd4f7a20e5 "/usr/local/google/home/fschneider/dartgit2/sdk/tests/standalone/io/socket_source_address_test.dart", dart_options=dart_options@entry=0x7ffd4f79ff60) at runtime/bin/main.cc:1695
#8  0x000000000059103c in dart::bin::main (argc=7, argv=0x7ffd4f7a0108) at runtime/bin/main.cc:1917
#9  0x00000000005912f9 in main (argc=<optimized out>, argv=<optimized out>) at runtime/bin/main.cc:1955
```

@mkustermann

**Comment by mkustermann** [comment]
If I've some time next week I can take a look.

**Comment by mkustermann** [comment]
CL which should fix it: https://codereview.chromium.org/2540013002/
