### ISSUE TITLE
Exception in resynthesizer when an incomplete setter is typed.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27846]
The following code causes an exception.
I was trying to type `void setUp() {}`, but after typing `void set` the server crashed.

```dart
class C {
  void set

  foo() {}
}
```

```
Dart analysis server, SDK version 1.21.0-edge.08854375b316f285588a8a51dd379bad4da26c6f, server version 1.17.0, error: Task failed: BuildCompilationUnitElementTask for source /Users/scheglov/dart/test2/bin/test.dart
Element mismatch in /Users/scheglov/dart/test2/bin/test.dart at /Users/scheglov/dart/test2/bin/test.dart
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:50:7)
#1      BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1082:33)
#2      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321:9)
#3      AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#4      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#5      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
#6      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:731:14)
#7      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:673:12)
#8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:500:54)
#9      PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1086:15)
#10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:482:20)
#11     AnalysisDriver._performWork.<_performWork_async_body> (package:analyzer/src/dart/analysis/driver.dart:751:31)
#12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#13     _rootRun (dart:async/zone.dart:1146)
#14     _CustomZone.run (dart:async/zone.dart:1026)
#15     _CustomZone.runGuarded (dart:async/zone.dart:924)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#17     _rootRun (dart:async/zone.dart:1150)
#18     _CustomZone.run (dart:async/zone.dart:1026)
#19     _CustomZone.runGuarded (dart:async/zone.dart:924)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/array.dart:134)
#1      ClassElementImpl._resynthesizeFieldsAndPropertyAccessors (package:analyzer/src/dart/element/element.dart:1215:42)
#2      ClassElementImpl.accessors (package:analyzer/src/dart/element/element.dart:502:7)
#3      ElementWalker.ElementWalker.forClass (package:analyzer/src/generated/declaration_resolver.dart:546:30)
#4      DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:86:15)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923:15)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814:20)
#7      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523:21)
#8      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:698:10)
#9      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516:15)
#10     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:47:12)
#11     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1082:33)
#12     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321:9)
#13     AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#14     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#15     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
#16     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:731:14)
#17     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:673:12)
#18     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:500:54)
#19     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1086:15)
#20     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:482:20)
#21     AnalysisDriver._performWork.<_performWork_async_body> (package:analyzer/src/dart/analysis/driver.dart:751:31)
#22     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#23     _rootRun (dart:async/zone.dart:1146)
#24     _CustomZone.run (dart:async/zone.dart:1026)
#25     _CustomZone.runGuarded (dart:async/zone.dart:924)
#26     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#27     _rootRun (dart:async/zone.dart:1150)
#28     _CustomZone.run (dart:async/zone.dart:1026)
#29     _CustomZone.runGuarded (dart:async/zone.dart:924)
#30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#33     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#34     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by srawlins** [comment]
This exception is not seen any longer.
