### ISSUE TITLE
Exception from analysis server (running from Atom)

### ISSUE THREAD

**Issue by pulyaevskiy** [dart-lang/sdk#27864]
### what happened

Tried to use comment-based generic method syntax. I had a function like this:

```dart
Future retryAsync(Function func) {
  // implementation
}
```

The exception appeared when (or after) I changed it to:

```dart
Future retryAsync/*<T>*/(Function func) {
  // implementation
}
```

Not sure the exact timing though. The way I typed it is I started from `/**/`
and then added `<T>` inside.

### version information

- Dart SDK 1.20.1
- Atom 1.12.4
- dartlang 0.6.45

### the exception

Task failed: VerifyUnitTask for source /Users/anatoly/Projects/kafka/lib/kafka.ng.dart 

```
Unexpected exception while performing VerifyUnitTask for source /Users/anatoly/Projects/kafka/lib/kafka.ng.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:351)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1184)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1182)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:894)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'displayName'.

NoSuchMethodError: method not found: 'displayName'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ErrorVerifier._checkForAmbiguousImport (package:analyzer/src/generated/error_verifier.dart:2364)
#3      ErrorVerifier.visitSimpleIdentifier (package:analyzer/src/generated/error_verifier.dart:1132)
#4      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9069)
#5      TypeNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10400)
#6      RecursiveAstVisitor.visitTypeName (package:analyzer/dart/ast/visitor.dart:1936)
#7      ErrorVerifier.visitTypeName (package:analyzer/src/generated/error_verifier.dart:1202)
#8      TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10396)
#9      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10870)
#10     RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1960)
#11     ErrorVerifier.visitVariableDeclarationList (package:analyzer/src/generated/error_verifier.dart:1259)
#12     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10865)
#13     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4316)
#14     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:1569)
#15     ErrorVerifier.visitFieldDeclaration (package:analyzer/src/generated/error_verifier.dart:721)
#16     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4311)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#18     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1920)
#19     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:1425)
#20     ErrorVerifier.visitClassDeclaration (package:analyzer/src/generated/error_verifier.dart:500)
#21     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1852)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#23     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2452)
#24     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449)
#25     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:570)
#26     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2445)
#27     VerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:6193)
#28     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#29     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#30     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#31     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#32     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1184)
#33     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#34     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1182)
#35     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#36     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:894)
#37     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#38     _rootRun (dart:async/zone.dart:1146)
#39     _CustomZone.run (dart:async/zone.dart:1026)
#40     _CustomZone.runGuarded (dart:async/zone.dart:924)
#41     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#42     _rootRun (dart:async/zone.dart:1150)
#43     _CustomZone.run (dart:async/zone.dart:1026)
#44     _CustomZone.runGuarded (dart:async/zone.dart:924)
#45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#46     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#47     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#48     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


```

**Comment by bwilkerson** [comment]
Thanks for reporting the problem!

I believe that this has been fixed in bleeding edge, so the fix should be available in the next dev release.
