### ISSUE TITLE
Exception from analysis server (running from VSCode/dart-code)

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#27863]
### What I was doing

Typing in the editor, either during a completion or immediately after.

### Versions

- Dart SDK 1.21.0-dev.3.0
- Visual Studio Code 1.7.1
- Dart Code 0.14.3

### Exception 

Exception from fix contributor: DefaultFixContributor

```text
Could not get contents of /Users/devoncarew/projects/flutter/bin/cache/dart-sdk/lib/core/string.dart
#0      AnalysisContextImpl.parseCompilationUnit (package:analyzer/src/context/context.dart:1167)
#1      getParsedUnit (package:analysis_server/src/services/correction/util.dart:536)
#2      getParsedClassElementNode (package:analysis_server/src/services/correction/util.dart:516)
#3      FixProcessor._addFix_createField (package:analysis_server/src/services/correction/fix_internal.dart:1034)
#4      FixProcessor.compute.<compute_async_body> (package:analysis_server/src/services/correction/fix_internal.dart:354)
#5      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#6      _rootRun (dart:async/zone.dart:1146)
#7      _CustomZone.run (dart:async/zone.dart:1026)
#8      _CustomZone.runGuarded (dart:async/zone.dart:924)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#10     _rootRun (dart:async/zone.dart:1150)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Caused by FileSystemException(path=/Users/devoncarew/projects/flutter/bin/cache/dart-sdk/lib/core/string.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:169)
#1      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:94)
#2      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:78)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#4      FileSource.contents (package:analyzer/src/source/source_resource.dart:77)
#5      AnalysisContextImpl.getContents (package:analyzer/src/context/context.dart:855)
#6      AnalysisContextImpl.parseCompilationUnit (package:analyzer/src/context/context.dart:1165)
#7      getParsedUnit (package:analysis_server/src/services/correction/util.dart:536)
#8      getParsedClassElementNode (package:analysis_server/src/services/correction/util.dart:516)
#9      FixProcessor._addFix_createField (package:analysis_server/src/services/correction/fix_internal.dart:1034)
#10     FixProcessor.compute.<compute_async_body> (package:analysis_server/src/services/correction/fix_internal.dart:354)
#11     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#12     _rootRun (dart:async/zone.dart:1146)
#13     _CustomZone.run (dart:async/zone.dart:1026)
#14     _CustomZone.runGuarded (dart:async/zone.dart:924)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#16     _rootRun (dart:async/zone.dart:1150)
#17     _CustomZone.run (dart:async/zone.dart:1026)
#18     _CustomZone.runGuarded (dart:async/zone.dart:924)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by devoncarew** [comment]
there may have been other issues with the sdk on disk; closing

**Comment by omtodkar** [comment]
Found exception again from analysis server (running from VSCode / Dart Code)

### What I was doing

While typing and waiting for dart auto-suggestion as in below code:

```dart
final _paragraphPattern = RegExp(source);
```

### Versions

- Flutter SDK 1.2.1
- Visual Studio Code 1.33.0
- Dart Code 2.25.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/usr/local/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.25.0
```

### Exception (fatal)

Failed to handle request: {id: 155, method: edit.getAvailableRefactorings, params: {file: /Users/omkar/Workspace/bluemine/textile/lib/src/block_parser.dart, length: 6, offset: 714}, clientRequestTime: 1554715909126}

```text
RangeError: Value not in range: 720
#0      _StringBase.substring (dart:core/runtime/libstring_patch.dart:387:7)
#1      StatementAnalyzer._hasTokens (package:analysis_server/src/services/correction/statement_analyzer.dart:216:33)
#2      StatementAnalyzer._checkSelectedNodes (package:analysis_server/src/services/correction/statement_analyzer.dart:202:11)
#3      StatementAnalyzer.visitCompilationUnit (package:analysis_server/src/services/correction/statement_analyzer.dart:91:7)
#4      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2558:49)
#5      StatementAnalyzer.analyze (package:analysis_server/src/services/correction/statement_analyzer.dart:56:24)
#6      ExtractMethodRefactoringImpl._checkSelection (package:analysis_server/src/services/refactoring/extract_method.dart:478:14)
#7      ExtractMethodRefactoringImpl.isAvailable (package:analysis_server/src/services/refactoring/extract_method.dart:401:13)
#8      EditDomainHandler._getAvailableRefactoringsImpl (package:analysis_server/src/edit/edit_domain.dart:635:14)
<asynchronous suspension>
#9      EditDomainHandler._getAvailableRefactorings (package:analysis_server/src/edit/edit_domain.dart:607:5)
#10     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:363:16)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:349:45)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:345:50)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1500:12)
#18     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:344:5)
#19     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#22     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#30     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#31     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#32     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#33     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#34     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#35     _rootRunUnary (dart:async/zone.dart:1132:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#40     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#41     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#42     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#43     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#44     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#45     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#46     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#48     _rootRunUnary (dart:async/zone.dart:1132:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#53     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#54     _StreamController._add (dart:async/stream_controller.dart:640:7)
#55     _StreamController.add (dart:async/stream_controller.dart:586:5)
#56     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#57     _rootRunUnary (dart:async/zone.dart:1136:13)
#58     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#62     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#63     _StreamController._add (dart:async/stream_controller.dart:640:7)
#64     _StreamController.add (dart:async/stream_controller.dart:586:5)
#65     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1323:33)
#66     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:844:14)
#67     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#68     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#69     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#70     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/omkar/Workspace/bluemine/textile",
        "explicitFileCount": 7,
        "implicitFileCount": 653,
        "workItemQueueLength": 6,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment]
@omtodkar it's better to open new issues than post on closed ones, as they're more easily missed.

It looks like your issue is a dupe of #36682 though.
