### ISSUE TITLE
Exception from analysis server (running from VSCode)

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#27865]
### What I was doing

Opened a file to edit

### Versions

- Dart SDK 1.21.0-dev.6.0
- Visual Studio Code 1.7.1
- Dart Code 0.14.3

### Exception (Fatal)

Failed to handle request: {params: {file: /Users/devoncarew/projects/dart-lang/dart-sdk/sdk/pkg/analysis_server/test/context_manager_test.dart, offset: 344}, method: analysis.getHover, id: 234}

```text
AnalysisException: Cannot compute RESOLVED_UNIT for /Users/devoncarew/projects/dart-lang/dart-sdk/sdk/pkg/analysis_server/test/context_manager_test.dart in /Users/devoncarew/projects/dart-lang/dart-sdk/sdk/pkg/analysis_server/test/context_manager_test.dart
Caused by Unexpected exception while performing ResolveDirectiveElementsTask for source /Users/devoncarew/projects/dart-lang/dart-sdk/sdk/pkg/analysis_server/lib/src/services/refactoring/rename.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:351)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1193)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1191)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:960)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by NoSuchMethodError: The getter 'imports' was called on null.
Receiver: null
Tried calling: imports
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      DirectiveResolver.visitImportDirective (package:analyzer/src/generated/resolver.dart:2311)
#3      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:5948)
#4      DirectiveResolver.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:2291)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#6      ResolveDirectiveElementsTask.internalPerform (package:analyzer/src/task/dart.dart:5003)
#7      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#8      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#9      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#10     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#11     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1193)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#13     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1191)
#14     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#15     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:960)
#16     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#17     _rootRun (dart:async/zone.dart:1146)
#18     _CustomZone.run (dart:async/zone.dart:1026)
#19     _CustomZone.runGuarded (dart:async/zone.dart:924)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#21     _rootRun (dart:async/zone.dart:1150)
#22     _CustomZone.run (dart:async/zone.dart:1026)
#23     _CustomZone.runGuarded (dart:async/zone.dart:924)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#25     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:736)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1299)
#2      AnalysisServer.getResolvedCompilationUnits.<anonymous closure> (package:analysis_server/src/analysis_server.dart:802)
#3      runWithActiveContext (package:analysis_server/src/operation/operation_analysis.dart:33)
#4      AnalysisServer.getResolvedCompilationUnits (package:analysis_server/src/analysis_server.dart:797)
#5      AnalysisDomainHandler.getHover.<getHover_async_body> (package:analysis_server/src/domain_analysis.dart:98)
#6      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#7      _rootRun (dart:async/zone.dart:1146)
#8      _CustomZone.run (dart:async/zone.dart:1026)
#9      _CustomZone.runGuarded (dart:async/zone.dart:924)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#11     _rootRun (dart:async/zone.dart:1150)
#12     _CustomZone.run (dart:async/zone.dart:1026)
#13     _CustomZone.runGuarded (dart:async/zone.dart:924)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by devoncarew** [comment]
assumed stale
