### ISSUE TITLE
standalone/io/socket_info_ipv6_test failing on Windows

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#27876]
```
Unhandled exception:
Expect.equals(at index 2: Expected <::2a:7c0...>, Found: <::1>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:99:9)
#2      testHostAndPort.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/vm-win-release-ia32-be/build/sdk/tests/standalone/io/socket_info_ipv6_test.dart:16:16)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:144)
#7      _MapStream._handleData (dart:async/stream_pipe.dart:244)
#8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:176)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#12     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#13     _StreamController._add (dart:async/stream_controller.dart:635)
#14     _StreamController.add (dart:async/stream_controller.dart:581)
#15     _RawServerSocket.listen.<anonymous closure> (dart:io-patch/socket_patch.dart:1160)
#16     _RootZone.runGuarded (dart:async/zone.dart:1327)
#17     _RootZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1361)
#18     _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:862)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by lrhn** [comment]
Looking at the error, it seems something becomes `localhost` instead of an external IPv6 address. 
That  could be an actual error or just a false assumption by the test.
