### ISSUE TITLE
Regression in handling overlays for files that don't exist in Analysis Server

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#27887]
There seems to have been a regression in Analysis Server causing crashes when it attempts to analyze overlay only files. Consider the trace at the end of this report, it comes from the Analysis Server bundled with 1.20.1.

dart-services uses in memory overlays only, never materialising the files to disk. It seems that there is a race condition where in some cases this causes a failed to handle completion domain request. This occurred after 20 successful completion responses. 

Unfortunately this blocks upgrading DartPad to support the latest strong mode implementation.

```
RECV: {"id":"90","result":{}}
SEND: {"id":"91","method":"analysis.updateContent","params":{"files":{"/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analysisServerSXMJbx/main.dart":{"type":"add","content":"________"}}}}
RECV: {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
RECV: {"event":"analysis.errors","params":{"file":"/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analysisServerSXMJbx/main.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analysisServerSXMJbx/main.dart","offset":7,"length":14,"startLine":1,"startColumn":8},"message":"Unused import","code":"unused_import","hasFix":true}]}}
RECV: {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
RECV: {"id":"91","result":{}}
SEND: {"id":"92","method":"analysis.setPriorityFiles","params":{"files":["/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analysisServerSXMJbx/main.dart"]}}
RECV: {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
RECV: {"id":"92"}
RECV: {"event":"analysis.errors","params":{"file":"/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analysisServerSXMJbx/main.dart","errors":[]}}
RECV: {"event":"analysis.errors","params":{"file":"/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analysisServerSXMJbx/main.dart","errors":[]}}
RECV: {"event":"analysis.errors","params":{"file":"/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analysisServerSXMJbx/main.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analysisServerSXMJbx/main.dart","offset":7,"length":14,"startLine":1,"startColumn":8},"message":"Unused import","code":"unused_import","hasFix":true}]}}
RECV: {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
SEND: {"id":"93","method":"completion.getSuggestions","params":{"file":"/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analysisServerSXMJbx/main.dart","offset":21}}
RECV: {"id":"93","result":{"id":"22"}}
RECV: {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {params: {file: /var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analysisServerSXMJbx/main.dart, offset: 21}, method: completion.getSuggestions, id: 93}","stackTrace":"FileSystemException(path=/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analysisServerSXMJbx/main.dart; message=Cannot open file)\n#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:169)\n#1      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:94)\n#2      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:78)\n#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)\n#4      FileSource.contents (package:analyzer/src/source/source_resource.dart:77)\n#5      _UriSuggestionBuilder.visitNamespaceDirective (package:analysis_server/src/services/completion/dart/uri_contributor.dart:69)\n#6      _UriSuggestionBuilder.visitImportDirective (package:analysis_server/src/services/completion/dart/uri_contributor.dart:51)\n#7      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:5877)\n#8      UriContributor.computeSuggestions.<computeSuggestions_async_body> (package:analysis_server/src/services/completion/dart/uri_contributor.dart:33)\n#9      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)\n#10     _rootRun (dart:async/zone.dart:1146)\n#11     _CustomZone.run (dart:async/zone.dart:1026)\n#12     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#14     _rootRun (dart:async/zone.dart:1150)\n#15     _CustomZone.run (dart:async/zone.dart:1026)\n#16     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#18     _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)\n#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)\n"}}
```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2537513004/
