### ISSUE TITLE
Unexpected exception while performing VerifyUnitTask

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#27904]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

(please describe what you were doing when this exception occurred)

### Versions

- Dart SDK 1.20.1
- Visual Studio Code 1.7.2
- Dart Code 0.14.4

### Exception

Task failed: VerifyUnitTask for source /Stuff/Projects/lol_duel/bin/dps.dart

```text
Unexpected exception while performing VerifyUnitTask for source /Stuff/Projects/lol_duel/bin/dps.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:351)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1184)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1182)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:894)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'displayName'.

NoSuchMethodError: method not found: 'displayName'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ErrorVerifier._checkForAmbiguousImport (package:analyzer/src/generated/error_verifier.dart:2364)
#3      ErrorVerifier.visitSimpleIdentifier (package:analyzer/src/generated/error_verifier.dart:1132)
#4      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9069)
#5      TypeNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10400)
#6      RecursiveAstVisitor.visitTypeName (package:analyzer/dart/ast/visitor.dart:1936)
#7      ErrorVerifier.visitTypeName (package:analyzer/src/generated/error_verifier.dart:1202)
#8      TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10396)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#10     TypeArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10265)
#11     RecursiveAstVisitor.visitTypeArgumentList (package:analyzer/dart/ast/visitor.dart:1930)
#12     ErrorVerifier.visitTypeArgumentList (package:analyzer/src/generated/error_verifier.dart:1195)
#13     TypeArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10261)
#14     TypeNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10401)
#15     RecursiveAstVisitor.visitTypeName (package:analyzer/dart/ast/visitor.dart:1936)
#16     ErrorVerifier.visitTypeName (package:analyzer/src/generated/error_verifier.dart:1202)
#17     TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10396)
#18     SimpleFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8961)
#19     RecursiveAstVisitor.visitSimpleFormalParameter (package:analyzer/dart/ast/visitor.dart:1846)
#20     ErrorVerifier.visitSimpleFormalParameter (package:analyzer/src/generated/error_verifier.dart:1127)
#21     SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:8956)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#23     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4759)
#24     RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:1587)
#25     ErrorVerifier.visitFormalParameterList (package:analyzer/src/generated/error_verifier.dart:747)
#26     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4755)
#27     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5264)
#28     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:1611)
#29     ErrorVerifier.visitFunctionExpression (package:analyzer/src/generated/error_verifier.dart:814)
#30     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5259)
#31     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5110)
#32     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:1599)
#33     ErrorVerifier.visitFunctionDeclaration (package:analyzer/src/generated/error_verifier.dart:795)
#34     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5103)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7743)
#36     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2452)
#37     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:1449)
#38     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:570)
#39     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2445)
#40     VerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:6193)
#41     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#42     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#43     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#44     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#45     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1184)
#46     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#47     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1182)
#48     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#49     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:894)
#50     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#51     _rootRun (dart:async/zone.dart:1146)
#52     _CustomZone.run (dart:async/zone.dart:1026)
#53     _CustomZone.runGuarded (dart:async/zone.dart:924)
#54     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#55     _rootRun (dart:async/zone.dart:1150)
#56     _CustomZone.run (dart:async/zone.dart:1026)
#57     _CustomZone.runGuarded (dart:async/zone.dart:924)
#58     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#59     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#60     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#61     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
@scheglov Is this the same occurrence as the one you recently fixed, or is this a new manifestation of a similar problem?

**Comment by scheglov** [comment]
It looks different to me.
The one I fixed recently was that an element did not implement `displayName`.
Here we attempt to ask `displayName` of `null`.

**Comment by devoncarew** [comment]
assumed stale
