### ISSUE TITLE
In latest dev-build dartanalyzer continually fails in IntelliJ

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#27906]
What steps will reproduce the problem?
1.
When I try to edit my code I don't get auto completion or quick fixes.
The analyzer view shows all kinds of errors, warnings, hints
Also the code editor shows the squiggled lines.
2.
I add a space somewhere in the code and all the errors, warnings, hints in the analyzer view vanish.
When I add another space the analyzer starts reanalyzing my project.
3.

What is the expected result?

What happens instead?

Please provide any additional information below.
Attach a code sample as text, a screenshot or screencast if possible

Dart VM version: 1.21.0-edge.d92107e01d4a12ae19edf2afd3eb9c60ca0eb7ab (Fri Nov 25 15:43:41 2016) on "linux_x64"
Dart Plugin version `Version: 163.8651`

reverting to
Dart VM version: 1.21.0-edge.640b5ca80a2739d2db6466834778c60147ad15c0 (Mon Nov 21 12:35:27 2016) on "linux_x64"
seems to fix it

https://youtrack.jetbrains.com/issue/WEB-24397

**Comment by zoechi** [comment]
[idea.log.txt](https://github.com/dart-lang/sdk/files/616487/idea.log.txt)

**Comment by zoechi** [comment]
It's the same with 

> Dart VM version: 1.21.0-edge.7957a1c2562ae4398ac05e5b36b3df06fff423a9 (Sun Nov 27 23:05:52 2016) on "linux_x64"

**Comment by zoechi** [comment]
Seems to work in 

> Dart VM version: 1.21.0-edge.0cf02040f870a256cc0fc4eb90a3c46a82008fec (Mon Nov 28 16:11:59 2016) on "linux_x64"

**Comment by zoechi** [comment]
Still got it

```
2016-11-29 11:35:43,026 [148079247]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.21.0-edge.280d6ede9d2d3370030c47915599969aaeb6c8bf, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1480415743002, params: {file: /home/myuser/dart/myproject/lib/designer/webui/list/list_component.dart, offset: 2299}, method: edit.getFixes, id: 27}
NoSuchMethodError: The method 'getLocation' was called on null.
Receiver: null
Tried calling: getLocation(2299)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      EditDomainHandler.getFixes.<getFixes_async_body> (package:analysis_server/src/edit/edit_domain.dart:208)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#4      _rootRunUnary (dart:async/zone.dart:1158)
#5      _CustomZone.runUnary (dart:async/zone.dart:1037)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#9      _Future._complete (dart:async/future_impl.dart:467)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#11     AnalysisServer.getResolvedCompilationUnit.<getResolvedCompilationUnit_async_body> (package:analysis_server/src/analysis_server.dart:809)
#12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#13     _rootRun (dart:async/zone.dart:1146)
#14     _CustomZone.run (dart:async/zone.dart:1026)
#15     _CustomZone.runGuarded (dart:async/zone.dart:924)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#17     _rootRun (dart:async/zone.dart:1150)
#18     _CustomZone.run (dart:async/zone.dart:1026)
#19     _CustomZone.runGuarded (dart:async/zone.dart:924)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:221)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
2016-11-29 11:35:43,027 [148079248]  ERROR - yzer.DartAnalysisServerService - IntelliJ IDEA 2016.3  Build #IU-163.7743.44 
```

**Comment by mit-mit** [comment]
@bwilkerson isn't this a 1.21 blocker?

**Comment by mit-mit** [comment]
Marking as 1.21 candidate until further analysis.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2537753003/

**Comment by zoechi** [comment]
Oh, missed that this was already marked as fixed.
I can confirm that this doesn't happen anymore in 
```
Dart VM version: 1.21.0-edge.6bb28d748ae7e337de0da62bffd546c2cd393d13 (Fri Dec  2 17:12:48 2016) on "linux_x64"
```
Thanks a lot :)
