### ISSUE TITLE
Flaky failures of socket_source_address_test

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#27951]
Example:
https://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-be/builds/16555/steps/vm%20tests/logs/stdio

Output:
```
FAILED: none-vm release_x64 standalone/io/socket_source_address_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
Unhandled exception:
Expect.fail('Unexpected: Expect.fail('Did not throw')')
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.fail (package:expect/expect.dart:154:5)
#2      throws.<throws_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/socket_source_address_test.dart:19:16)
#3      _RootZone.runUnary (dart:async/zone.dart:1404)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#7      _Future._completeWithValue (dart:async/future_impl.dart:477)
#8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/socket_source_address_test.dart
Took 0:00:00.259263

Short reproduction command (experimental):
    python tools/test.py -mrelease -t60 standalone/io/socket_source_address_test
```

@mkustermann This is the same test that also segfaulted sometimes (see #27847), but this failure occurred after the other fix, so it seems unrelated.

**Comment by mkustermann** [comment]
I agree, looks unrelated. The exception seems to occur for tcp **client** sockets (whereas the two fixes are only concerning **server** sockets).

**Comment by mkustermann** [comment]
I can now confirm the test is written in a flaky way. 

The test is listening on IPv6-only socket on a random port (i.e. port is assigned by the OS). Then the test tries to connect to the very same port using IPv4. So it expects to not be able to connect, because the server is IPv6-only.

=> But there might be other processes running on the system which happen to listen on this very same port on IPv4.

Here is a stripped down reproduction:
```
import "dart:async";
import "dart:io";

Future testConnect() async {
  var server = await ServerSocket.bind(InternetAddress.ANY_IP_V6, 0, v6Only: true);
  server.listen((s) => s.destroy());

  try {
    Socket s = await Socket.connect(InternetAddress.LOOPBACK_IP_V4,
                                    server.port,
                                    sourceAddress: '127.0.0.1');
    throw 'Could connect to remote even though we did not expect to.: \n'
          '  address/port:             ${s.address}/${s.port}\n'
          '  remoteAddress/remotePort: ${s.remoteAddress}/${s.remotePort})';
  } on SocketException catch (e) { }

  await server.close();
}

main() async {
  while (true) await testConnect();
}
```

On my machine:
```
$ out/ReleaseX64/dart flaky.dart
Unhandled exception:
Could connect to remote even though we did not expect to.: 
  address/port:             InternetAddress('127.0.0.1', IP_V4)/44256
  remoteAddress/remotePort: InternetAddress('127.0.0.1', IP_V4)/39743)
#0      testConnect.<testConnect_async_body> (file:///usr/local/google/home/kustermann/repositories/sdk-gclient/sdk/flaky.dart:12:5)
#1      _RootZone.runUnary (dart:async/zone.dart:1404)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
$ netstat -atnlp | grep 39743 | grep LISTEN
tcp        0      0 127.0.0.1:39743         0.0.0.0:*               LISTEN      8056/python2  
$ ps aux | grep 8056 | grep -v grep
kusterm+  8056  5.6  0.0 2386336 50748 ?       Ssl  13:23   2:49 /usr/bin/python ycmd ...
```

As can be seen after a number of iterations the test can connect to the port, which happens to be some python server running on my system.

**Comment by mkustermann** [comment]
Here's a [CL](https://codereview.chromium.org/2546733002/) which does it a bit differently, but it could also make the buildbot more flaky as it is now.

What the test is testing is simply dependent on not just the dart process but all other processes on the system. So I don't think we can make it completely stable.

**Comment by fsc8000** [comment]
I have not seen this test fail for a while now. Seems fixed by @mkustermann 's CL.
