### ISSUE TITLE
Task failed: GatherUsedLocalElementsTask

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#27964]
# Analyzer Feedback from IntelliJ
IDEA: 171.SNAPSHOT Dart: 1.21.0-dev.11.1

## Stack

```dart
Dart analysis server, SDK version 1.21.0-dev.11.1, server version 1.17.0, error: Task failed: GatherUsedLocalElementsTask for source C:\dart_projects\DartSample2\bin\empty.dart
Unexpected exception while performing GatherUsedLocalElementsTask for source C:\dart_projects\DartSample2\bin\empty.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:971)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find <K extends Object, V>() → dynamic in [<K, V>() → dynamic]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3153)
#1      FunctionElementImpl.identifier (package:analyzer/src/dart/element/element.dart:4391)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3193)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2911)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2800)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10460)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3471)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)
#10     FunctionExpressionInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5417)
#11     RecursiveAstVisitor.visitFunctionExpressionInvocation (package:analyzer/dart/ast/visitor.dart:866)
#12     FunctionExpressionInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5413)
#13     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4257)
#14     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:806)
#15     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4253)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#17     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#18     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:638)
#19     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#20     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#21     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:644)
#22     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#23     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7306)
#24     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:986)
#25     GatherUsedLocalElementsVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:3481)
#26     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7297)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#28     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#29     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:674)
#30     GatherUsedLocalElementsVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3451)
#31     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#32     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#33     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#34     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:698)
#35     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#36     GatherUsedLocalElementsTask.internalPerform (package:analyzer/src/task/dart.dart:3085)
#37     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#38     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#39     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#40     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#41     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#42     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#43     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#44     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#45     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:971)
#46     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#47     _rootRun (dart:async/zone.dart:1146)
#48     _CustomZone.run (dart:async/zone.dart:1026)
#49     _CustomZone.runGuarded (dart:async/zone.dart:924)
#50     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#51     _rootRun (dart:async/zone.dart:1150)
#52     _CustomZone.run (dart:async/zone.dart:1026)
#53     _CustomZone.runGuarded (dart:async/zone.dart:924)
#54     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#55     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#56     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#57     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by alexander-doroshko** [comment]
duplicate of #28538
