### ISSUE TITLE
Exception from fix contributor: DefaultFixContributor. NoSuchMethodError: The getter 'end' was called on null.

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#27963]
# Analyzer Feedback from IntelliJ
IDEA: 171.SNAPSHOT Dart: 1.21.0-dev.11.1

## Stack

```dart
Dart analysis server, SDK version 1.21.0-dev.11.1, server version 1.17.0, error: Exception from fix contributor: DefaultFixContributor
NoSuchMethodError: The getter 'end' was called on null.
Receiver: null
Tried calling: end
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      FixProcessor._addFix_addMissingParameter (package:analysis_server/src/services/correction/fix_internal.dart:493)
#3      FixProcessor.compute.<compute_async_body> (package:analysis_server/src/services/correction/fix_internal.dart:265)
#4      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#5      _rootRun (dart:async/zone.dart:1146)
#6      _CustomZone.run (dart:async/zone.dart:1026)
#7      _CustomZone.runGuarded (dart:async/zone.dart:924)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2547053002/
