### ISSUE TITLE
DDC cannot resolve 'call' in certain cases

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27960]
The following code gives on errors or warnings, but fails at runtime.

```dart
typedef void Func(Object x);

Map<String, Func> map = {
  'print': print
};

void foo(String str) {
  map[str].call("hello");
}

void main() {
  foo('print');
}
```

The error is:

```
ReferenceError: call is not defined
    at unknown.foo (/Users/vsm/ddctest/unknown.js:19:48)
    at unknown.main (/Users/vsm/ddctest/unknown.js:23:13)
    at dart._checkAndCall (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:1649:16)
    at dart.dcall (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:1654:17)
    at _IsolateContext.eval (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:9057:23)
    at _isolate_helper.startRootIsolate (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:8824:19)
    at [eval]:1:37
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:541:32)
```

**Comment by vsmenon** [comment]
Here's the JS:

```
  unknown.foo = function(str) {
    dart.dcall(/* Unimplemented unknown name */call, "hello");
  };
```

Perhaps a few things going wrong - shouldn't be a `dcall`, right?

**Comment by jmesserly** [comment]
we never implemented the "call" method on functions. I thought it was going away?

**Comment by jmesserly** [comment]
(note that ".call" on a function type is different from a "call" method on an interface type. We implement the latter not the former)

**Comment by vsmenon** [comment]
I think we're eliminating the sub-typing between Object types with a call method and FunctionTypes.  I.e., an object emulating a function cannot pass as a function.  Not sure beyond that.

**Comment by jmesserly** [comment]
can you just change above code to say:
```dart
void foo(String str) {
  map[str]("hello");
}
```

(I'm  not sure this should be P1, it seems like something we may not even have in Dart 2)

**Comment by vsmenon** [comment]
Will try that.

**Comment by jmesserly** [comment]
I guess you implemented it partially in this CL: https://codereview.chromium.org/2255993002/diff/20001/lib/src/compiler/code_generator.dart

not sure if it regressed, or the original patch doesn't handle all cases.

**Comment by vsmenon** [comment]
https://codereview.chromium.org/2539033004/
