### ISSUE TITLE
Uri.base is broken on Node.js

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#27979]
Currently `Uri.base` doesn't work in many situations when compiled Dart code is run on Node.js. [It uses `global.location`](https://github.com/dart-lang/sdk/blob/24ffedcef0a6661b3de31867780b33b8c179d69c/sdk/lib/_internal/js_runtime/lib/js_helper.dart#L946-L954), which is undefined in Node.js. The preamble tries to work around this [by shoving a path into a `file:` URL](https://github.com/dart-lang/sdk/blob/24ffedcef0a6661b3de31867780b33b8c179d69c/sdk/lib/_internal/js_runtime/lib/preambles/d8.js#L19-L33), but this is invalid in general. It breaks in all cases on Windows, and will break on POSIX systems if the path contains characters that need to be percent-escaped.

This is an issue for both DDC and dart2js.

**Comment by nex3** [comment]
One possible way to do this would be to have `Uri.base()`'s JS implementation try to call `process.cwd()` on Node and use `new Uri.file()` to properly convert that to a URL.

**Comment by nex3** [comment]
This is causing real-world breakages for Angular users in the wild (see https://github.com/sass/dart-sass/issues/734). Can it be prioritized?

**Comment by kevintruby** [comment]
This is also appears to be the cause of an odd SSR issue when working with Vue CLI 3 single-file components. In my use case, also trying to compile SCSS directly from components via webpack and the `sass` npm module, which is a distribution of Dart Sass.

Returns the following:

```
> vue-cli-service build


⠧  Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                                                               1:47:15 PM

 error  in ./src/components/Breadcrumb.vue?vue&type=style&index=0&id=352a2dd2&lang=scss&scoped=true&

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Unsupported operation: 'Uri.base' is not supported
```

It's been really difficult finding help on this issue, and would love to get more info 🙂

**Comment by molszanski** [comment]
I've also faced issues with SSR. 

Managed to duct-tape it with with this code in our `setup-for-ssr.js`
```js
 global.location=  {
   href: "file://"+process.cwd()+"/"
 };
```

**Comment by nex3** [comment]
@molszanski Be aware that file paths are not substitutable for `file:` URLs in general. There are many edge cases that work differently between them, particularly on Windows, so that code will break in some situations.

**Comment by molszanski** [comment]
@nex3 Thank you Natalie for the heads up! I've read your comments and warnings. Appreciate them a lot! Luckily I can get away with this hack for now. But this will come back and bite me one day.

**Comment by nex3** [comment]
This breaks even more badly when the Node.js environment is using [jsdom](https://github.com/jsdom/jsdom#readme), which is common in test environments. jsdom configures `window.location.href` to simulate a browser environment, which overrides the preamble's (already-hacky) replacement and makes `Uri.base` look like it's operating in a browser when in fact it's not.

**Comment by Justinidlerz** [comment]
This will affect to the `createServer().ssrLoadModule()` of [Vite](https://github.com/vitejs/vite) when using sass 

```shell
Error: Unsupported operation: 'Uri.base' is not supported
    at Object._newRenderError (/Users/project/node_modules/sass/sass.dart.js:13537:19)
    at _render_closure1.call$2 (/Users/project/node_modules/sass/sass.dart.js:80375:21)
    at _RootZone.runBinary$3$3 (/Users/project/node_modules/sass/sass.dart.js:27269:18)
    at _FutureListener.handleError$1 (/Users/project/node_modules/sass/sass.dart.js:25797:19)
    at _Future__propagateToListeners_handleError.call$0 (/Users/project/node_modules/sass/sass.dart.js:26094:49)
    at Object._Future__propagateToListeners (/Users/project/node_modules/sass/sass.dart.js:4543:77)
    at _Future._completeError$2 (/Users/project/node_modules/sass/sass.dart.js:25927:9)
    at _Future__asyncCompleteError_closure.call$0 (/Users/project/node_modules/sass/sass.dart.js:26016:18)
    at Object._microtaskLoop (/Users/project/node_modules/sass/sass.dart.js:4594:24)
    at StaticClosure._startMicrotaskLoop (/Users/project/node_modules/sass/sass.dart.js:4600:11) {
  formatted: "Error: Unsupported operation: 'Uri.base' is not supported",
  status: 3,
  id: '/Users/project/src/pages/FindProductDetail/FindProductDetail.module.scss',
  frame: "Error: Unsupported operation: 'Uri.base' is not supported",
  plugin: 'vite:css'
```
