### ISSUE TITLE
Fatal error: The getter 'element' was called on null.

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#27974]
May be caused by the angular_analyzer_plugin. I'm filing it here as I see no angular-specific classes in stack trace. Here are details about my project structure: https://github.com/dart-lang/angular_analyzer_plugin/issues/120#issuecomment-264534297

IDEA: 171.SNAPSHOT Dart: 1.21.0-dev.11.1
## Stack

```dart
Dart analysis server, SDK version 1.21.0-dev.11.1, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1480704795786, params: {file: C:\dart_projects\angular-examples\toh-6\lib\heroes_component.html, offset: 263}, method: edit.getFixes, id: 8}
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      EditDomainHandler.getFixes.<getFixes_async_body> (package:analysis_server/src/edit/edit_domain.dart:214)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#4      _rootRunUnary (dart:async/zone.dart:1158)
#5      _CustomZone.runUnary (dart:async/zone.dart:1037)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#9      _Future._complete (dart:async/future_impl.dart:467)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#11     AnalysisServer.getResolvedCompilationUnit.<getResolvedCompilationUnit_async_body> (package:analysis_server/src/analysis_server.dart:827)
#12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#13     _rootRun (dart:async/zone.dart:1146)
#14     _CustomZone.run (dart:async/zone.dart:1026)
#15     _CustomZone.runGuarded (dart:async/zone.dart:924)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#17     _rootRun (dart:async/zone.dart:1150)
#18     _CustomZone.run (dart:async/zone.dart:1026)
#19     _CustomZone.runGuarded (dart:async/zone.dart:924)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by scheglov** [comment]
This ishttps://codereview.chromium.org/2549883002

**Comment by scheglov** [comment]
The fix landed.
https://github.com/dart-lang/sdk/commit/24ffedcef0a6661b3de31867780b33b8c179d69c

But we need to cherry pick it into the release.

**Comment by scheglov** [comment]
Merge request.
https://github.com/dart-lang/sdk/issues/27980
