### ISSUE TITLE
Exception on .packages change

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27983]
1. Open a `.packages` file.
2. Change something in it, as simple as the generated `# Generated by pub on 2016-10-19 14:20:10.833540.` comment.
3. Analysis Server crashes.

@bwilkerson could you look at this?

@stereotype441 this was in one of your server crash logs :-)

```
{"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {clientRequestTime: 1480819938615, params: {included: [/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/front_end, /Users/scheglov/dart/test2], excluded: [/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/.idea, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/.pub, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/build, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/tool, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/tool/instrumentation, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/.pub, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/build, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/front_end/.pub, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/front_end/build, /Users/scheglov/dart/test2/.pub, /Users/scheglov/dart/test2/build]}, method: analysis.setAnalysisRoots, id: 3}","stackTrace":"NoSuchMethodError: The getter 'analysisOptions' was called on null.
Receiver: null
Tried calling: analysisOptions
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      setLints (package:analyzer/src/services/lint.dart:25:44)
#3      LinterPlugin.registerLints (package:linter/src/plugin/linter_plugin.dart:99:5)
#4      AnalysisOptionsProcessor.optionsProcessed (package:linter/src/config.dart:48:24)
#5      ContextBuilder.getAnalysisOptions.<anonymous closure> (package:analyzer/src/context/builder.dart:352:39)
#6      Object&ListMixin.forEach (dart:collection/list.dart:63)
#7      ContextBuilder.getAnalysisOptions (package:analyzer/src/context/builder.dart:351:27)
#8      ContextManagerImpl._checkForPackagespecUpdate (package:analysis_server/src/context_manager.dart:1003:19)
#9      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1512:5)
#10     _rootRunUnary (dart:async/zone.dart:1158)
#11     _CustomZone.runUnary (dart:async/zone.dart:1037)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#15     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:386)
#16     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:261)
#17     _rootRunUnary (dart:async/zone.dart:1158)
#18     _CustomZone.runUnary (dart:async/zone.dart:1037)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#21     _DelayedData.perform (dart:async/stream_impl.dart:590)
#22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:666)
#24     _rootRun (dart:async/zone.dart:1146)
#25     _CustomZone.run (dart:async/zone.dart:1026)
#26     _CustomZone.runGuarded (dart:async/zone.dart:924)
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#28     _rootRun (dart:async/zone.dart:1150)
#29     _CustomZone.run (dart:async/zone.dart:1026)
#30     _CustomZone.runGuarded (dart:async/zone.dart:924)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#34     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#35     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
"}}
```

**Comment by bwilkerson** [comment]
I believe this is fixed by a sequence of changes, the last of which was https://codereview.chromium.org/2559523005/.
