### ISSUE TITLE
diagnostic.getDiagnostics not implemented for the new analysis driver?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28068]
### What I was doing

General development.

### Request

While responding to request: `diagnostic.getDiagnostics`

### Versions

- Dart SDK 1.21.0
- Visual Studio Code 1.7.2
- Dart Code 0.14.5

### Analyzer Info

The analyzer was launched with the arguments:

```text
--port=20200
--client-id=DanTup.dart-code
--client-version=0.14.5
--instrumentation-log-file=/Users/devoncarew/as_vscode.log
--enable-new-analysis-driver
```

### Exception

Bad state: Should not be used with the new analysis driver

```text
#0      ContextManagerImpl.folderMap (package:analysis_server/src/context_manager.dart:540)
#1      ContextManagerImpl.analysisContexts (package:analysis_server/src/context_manager.dart:536)
#2      AnalysisServer.analysisContexts (package:analysis_server/src/analysis_server.dart:437)
#3      DiagnosticDomainHandler.computeDiagnostics (package:analysis_server/src/domain_diagnostic.dart:42)
#4      DiagnosticDomainHandler.handleRequest (package:analysis_server/src/domain_diagnostic.dart:92)
#5      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:851)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#7      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:847)
#8      _rootRun (dart:async/zone.dart:1150)
#9      _CustomZone.run (dart:async/zone.dart:1026)
#10     _CustomZone.runGuarded (dart:async/zone.dart:924)
#11     runZoned (dart:async/zone.dart:1501)
#12     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:846)
#13     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#15     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161)
#16     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
#17     _rootRunUnary (dart:async/zone.dart:1158)
#18     _CustomZone.runUnary (dart:async/zone.dart:1037)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#22     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#23     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#24     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#25     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:158)
#26     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:133)
#27     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#28     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#29     _rootRunUnary (dart:async/zone.dart:1158)
#30     _CustomZone.runUnary (dart:async/zone.dart:1037)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#37     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#38     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#39     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#40     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#42     _rootRunUnary (dart:async/zone.dart:1158)
#43     _CustomZone.runUnary (dart:async/zone.dart:1037)
#44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#47     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#48     _StreamController._add (dart:async/stream_controller.dart:635)
#49     _StreamController.add (dart:async/stream_controller.dart:581)
#50     _Socket._onData (dart:io-patch/socket_patch.dart:1680)
#51     _rootRunUnary (dart:async/zone.dart:1162)
#52     _CustomZone.runUnary (dart:async/zone.dart:1037)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#56     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#57     _StreamController._add (dart:async/stream_controller.dart:635)
#58     _StreamController.add (dart:async/stream_controller.dart:581)
#59     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#60     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:781)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#63     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#64     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by bwilkerson** [comment]
@scheglov Some of the data in this request doesn't make sense with the new driver, so we should figure out what we can support.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2625493002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/5a9c5ac1eceb7386b5f96ddef4377eb98fbe3c8c
