### ISSUE TITLE
Exception in ContextManagerImpl._updateContextPackageUriResolver

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#28086]
```
Dart analysis server, SDK version 1.22.0-edge.cc2eba8c2a23e1659ed26fcd37f9e114d43259fb, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1481577610947, params: {included: [/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/front_end, /Users/scheglov/dart/test2], excluded: [/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/.idea, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/.pub, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/build, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/tool, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/tool/instrumentation, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/.pub, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/build, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/front_end/.pub, /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/front_end/build, /Users/scheglov/dart/test2/.pub, /Users/scheglov/dart/test2/build]}, method: analysis.setAnalysisRoots, id: 3}
Bad state: Should not be used with the new analysis driver
#0      ContextManagerImpl.folderMap (package:analysis_server/src/context_manager.dart:561:7)
#1      ContextManagerImpl._updateContextPackageUriResolver (package:analysis_server/src/context_manager.dart:1704:31)
#2      ContextManagerImpl._recomputeFolderDisposition (package:analysis_server/src/context_manager.dart:1663:5)
#3      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1415:7)
#4      _rootRunUnary (dart:async/zone.dart:1158)
#5      _CustomZone.runUnary (dart:async/zone.dart:1037)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#9      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:386)
#10     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:261)
#11     _rootRunUnary (dart:async/zone.dart:1158)
#12     _CustomZone.runUnary (dart:async/zone.dart:1037)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#15     _DelayedData.perform (dart:async/stream_impl.dart:590)
#16     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#17     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:666)
#18     _rootRun (dart:async/zone.dart:1146)
#19     _CustomZone.run (dart:async/zone.dart:1026)
#20     _CustomZone.runGuarded (dart:async/zone.dart:924)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#22     _rootRun (dart:async/zone.dart:1150)
#23     _CustomZone.run (dart:async/zone.dart:1026)
#24     _CustomZone.runGuarded (dart:async/zone.dart:924)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#28     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#29     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
Do you remember what you were doing at the time that caused the exception?

**Comment by scheglov** [comment]
`get rebase` I think.
`_recomputeFolderDisposition` is invoked just once in `_handleWatchEvent `, so probably we could simulate this easily.

**Comment by bwilkerson** [comment]
I believe that I can reproduce the problem.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2571353002/
