### ISSUE TITLE
Invalid annotation causes an exception in _ConstExprBuilder

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#28099]
Analyzer Feedback from IntelliJ

The following code causes the exception.

```dart
fff() {}

@fff()
class C {}
```

## Version information

- `IDEA 171.SNAPSHOT`
- `1.22.0-edge.9b210471f9666ed02e473cb4d26c0403d86924f9`
- `IC-171.SNAPSHOT, JRE 1.8.0_72-b15x64 Oracle Corporation, OS Mac OS X(x86_64) v10.11.6 unknown, screens 1680x1050  Retina`

## Exception

Please append the contents of:
file:///private/var/folders/00/0wqkh000h01000cxqpysvccm003ky_/T/report.txt

```
Dart analysis server, SDK version 1.22.0-edge.665a12d1b59bb3e335a2d8adf64bff5d5d37435e, server version 1.17.0, error: Task failed: BuildCompilationUnitElementTask for source /Users/scheglov/dart/test2/bin/test.dart
Element mismatch in /Users/scheglov/dart/test2/bin/test.dart at /Users/scheglov/dart/test2/bin/test.dart
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:50:7)
#1      BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1084:33)
#2      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321:9)
#3      AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#4      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#5      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
#6      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723:14)
#7      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1292:12)
#8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:656:56)
#9      PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1427:15)
#10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:643:20)
#11     AnalysisDriver._performWork.<_performWork_async_body> (package:analyzer/src/dart/analysis/driver.dart:910:33)
#12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#13     _rootRun (dart:async/zone.dart:1146)
#14     _CustomZone.run (dart:async/zone.dart:1026)
#15     _CustomZone.runGuarded (dart:async/zone.dart:924)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#17     _rootRun (dart:async/zone.dart:1150)
#18     _CustomZone.run (dart:async/zone.dart:1026)
#19     _CustomZone.runGuarded (dart:async/zone.dart:924)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unsupported element for invokeConstructor FunctionElementHandle
#0      _ConstExprBuilder._pushInstanceCreation (package:analyzer/src/summary/resynthesize.dart:654:9)
#1      _ConstExprBuilder.build (package:analyzer/src/summary/resynthesize.dart:493:11)
#2      _UnitResynthesizer._buildConstExpression (package:analyzer/src/summary/resynthesize.dart:1825:53)
#3      _UnitResynthesizer.buildAnnotation (package:analyzer/src/summary/resynthesize.dart:1531:28)
#4      _ResynthesizerContext.buildAnnotation (package:analyzer/src/summary/resynthesize.dart:1391:31)
#5      ElementImpl._buildAnnotations (package:analyzer/src/dart/element/element.dart:3144:34)
#6      ClassElementImpl.metadata (package:analyzer/src/dart/element/element.dart:799:11)
#7      DeclarationResolver._resolveMetadata (package:analyzer/src/generated/declaration_resolver.dart:486:50)
#8      DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:89:5)
#9      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923:15)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814:20)

**Comment by scheglov** [comment]
https://codereview.chromium.org/2565173008

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/871f478c63fa0332cc9630e2351eb060042357e1
