### ISSUE TITLE
Dynamic calls with universal-function-typed params fail with a confusing error

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#28105]
This:

```dart
T foo<T>(x) => x as T;

void main() {
  dynamic list = <Object>[1, 2, 3];
  var result = list.map(foo);
  print(list);
}
```

results in:

```
TypeError: obj[dartx.noSuchMethod] is not a function
    at dart.noSuchMethod (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2023:37)
    at callNSM (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:1638:19)
    at dart._checkAndCall (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:1675:12)
    at dart._callMethod (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:1757:17)
    at dart.dsend (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:1760:17)
    at genlist.main (/Users/vsm/ddctest/genlist.js:20:23)
```

**Comment by vsmenon** [comment]
@leafpetersen @jmesserly 
Note, on the above, if I change `dynamic` to `var`, I get a static error:
```
[error] The argument type '<T>(dynamic) → T' can't be assigned to the parameter type '(Object) → dynamic'. (genlist.dart, line 5, col 25)
```

@davidmorgan hit this in json deserialization code, but we've worked around with more typing.

**Comment by jmesserly** [comment]
probably a similar issue as https://github.com/dart-lang/sdk/issues/28079

**Comment by jmesserly** [comment]
It does show up correctly as a type error now.

The type doesn't display correctly, that's covered in #28079 so I'm going to close this one.
