### ISSUE TITLE
Closure conversion: context can be `null`

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#28129]
_From @karlklose on October 12, 2016 7:36_

This stacktrace is from running the reified generics tests:

```
FAILED: none-vm debug_x64 language/lazy_static2_test
Expected: Pass 
Actual: CompileTimeError
CommandOutput[vm]:

stderr:
+ '[' -z '' -o '!' -r /usr/local/google/home/karlklose/ssd/workspace/kernel-sdk/sdk/tests/language/lazy_static2_test.dart.dill.status -o /usr/local/google/home/karlklose/ssd/workspace/kernel-sdk/sdk/tests/language/lazy_static2_test.dart -nt /usr/local/google/home/karlklose/ssd/workspace/kernel-sdk/sdk/tests/language/lazy_static2_test.dart.dill.status -o /usr/local/google/home/karlklose/ssd/workspace/reify/bin/../lib/runtime/declarations.dart -nt /usr/local/google/home/karlklose/ssd/workspace/kernel-sdk/sdk/tests/language/lazy_static2_test.dart.dill.status -o /usr/local/google/home/karlklose/ssd/workspace/reify/bin/../lib/runtime/interceptors.dart -nt /usr/local/google/home/karlklose/ssd/workspace/kernel-sdk/sdk/tests/language/lazy_static2_test.dart.dill.status -o /usr/local/google/home/karlklose/ssd/workspace/reify/bin/../lib/runtime/types.dart -nt /usr/local/google/home/karlklose/ssd/workspace/kernel-sdk/sdk/tests/language/lazy_static2_test.dart.dill.status ']'
+ dart -DreifyCheckout=/usr/local/google/home/karlklose/ssd/workspace/reify/bin/../ --package-root=/usr/local/google/home/karlklose/ssd/workspace/reify/bin/../third_party/kernel/bin/packages /usr/local/google/home/karlklose/ssd/workspace/reify/bin/dartk.dart -t reified_vm --sdk /usr/local/google/home/karlklose/ssd/workspace/kernel-sdk/sdk/out/ReleaseX64/obj/gen/patched_sdk/ -pout/DebugX64/packages/ -l -o /usr/local/google/home/karlklose/ssd/workspace/kernel-sdk/sdk/tests/language/lazy_static2_test.dart.dill /usr/local/google/home/karlklose/ssd/workspace/kernel-sdk/sdk/tests/language/lazy_static2_test.dart
Unhandled exception:
The null object does not have a method 'toClosureContext'.

NoSuchMethodError: method not found: 'toClosureContext'
Receiver: null
Arguments: [Instance of 'VariableDeclaration']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ClosureConverter.handleLocalFunction (package:kernel/transformations/closure_conversion.dart:470:23)
#3      ClosureConverter.visitFunctionExpression.<anonymous closure> (package:kernel/transformations/closure_conversion.dart:536:12)
#4      ClosureConverter.saveContext (package:kernel/transformations/closure_conversion.dart:421:15)
#5      ClosureConverter.visitFunctionExpression (package:kernel/transformations/closure_conversion.dart:535:64)
#6      FunctionExpression.accept (package:kernel/ast.dart:2318:36)
#7      Field.transformChildren (package:kernel/ast.dart:673:33)
#8      Transformer.defaultTreeNode (package:kernel/visitor.dart:310:10)
#9      TreeVisitor.defaultMember (package:kernel/visitor.dart:189:35)
#10     TreeVisitor.visitField (package:kernel/visitor.dart:192:31)
#11     Field.accept (package:kernel/ast.dart:657:32)
#12     transformList (package:kernel/ast.dart:3476:27)
#13     Library.transformChildren (package:kernel/ast.dart:216:5)
#14     Transformer.defaultTreeNode (package:kernel/visitor.dart:310:10)
#15     TreeVisitor.visitLibrary (package:kernel/visitor.dart:208:35)
#16     ClosureConverter.visitLibrary (package:kernel/transformations/closure_conversion.dart:431:30)
#17     Library.accept (package:kernel/ast.dart:205:30)
#18     transformList (package:kernel/ast.dart:3476:27)
#19     Program.transformChildren (package:kernel/ast.dart:3433:5)
#20     Transformer.defaultTreeNode (package:kernel/visitor.dart:310:10)
#21     TreeVisitor.visitProgram (package:kernel/visitor.dart:216:35)
#22     transformProgram (package:kernel/transformations/closure_conversion.dart:105:18)
#23     ReifiedVmTarget.transformProgram (file:///usr/local/google/home/karlklose/ssd/workspace/reify/lib/reify_target.dart:42:5)
#24     batchMain.<batchMain_async_body> (file:///usr/local/google/home/karlklose/ssd/workspace/reify/third_party/kernel/bin/dartk.dart:345:12)
#25     _RootZone.runUnary (dart:async/zone.dart:1204)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#27     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#28     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#29     _Future._complete (dart:async/future_impl.dart:467)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#31     DartLoaderBatch.getLoader.<getLoader_async_body> (package:kernel/analyzer/loader.dart:706:5)
#32     _RootZone.runUnary (dart:async/zone.dart:1204)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#34     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#35     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#36     _Future._complete (dart:async/future_impl.dart:467)
#37     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#38     createPackages.<createPackages_async_body> (package:kernel/analyzer/loader.dart:715:7)
#39     _RootZone.runUnary (dart:async/zone.dart:1204)
#40     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#41     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#42     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#43     _Future._completeWithValue (dart:async/future_impl.dart:477)
#44     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

_Copied from original issue: dart-lang/kernel#40_

**Comment by sjindel-google** [comment]
This issue is obsolete. The referenced test passes with closure conversion enabled.
