### ISSUE TITLE
VM: remove flag for new assert with message feature

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#28136]
The new assert with message feature -- sdk #24213 -- is now complete everywhere, and should not be behind a flag. Please remove that flag.

Also, confirmed it's working great:

test.dart:
```
main() {
  assert(2 > 1, 'Math is broken');
  var v;
  assert(v != null, 'v is null');
}
```

result:
```
$ ./bin/dart -c --assert-message test.dart

Unhandled exception:
'file:///Users/mit/tmp/dart-sdk/test.dart': Failed assertion: line 4 pos 10: 'v != null': v is null
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:33)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:29)
#2      main (file:///Users/mit/tmp/dart-sdk/test.dart:4:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
mit-macbookpro2:dart-sdk mit$```

**Comment by mit-mit** [comment]
This was tested with http://gsdview.appspot.com/dart-archive/channels/dev/raw/1.22.0-dev.2.0/sdk/

**Comment by mit-mit** [comment]
CC @a-siva
