### ISSUE TITLE
DDC breaks if you pass it a path in -o

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#28135]
Misread the documentation and passed it a path, not a file name:

```
$ ./bin/dartdevc test.dart -o .
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=/Users/mit/tmp/dart-sdk test.dart -o .
    dart --version: 1.22.0-dev.2.0 (Fri Dec 16 01:42:35 2016) on "macos_x64"

FileSystemException: Cannot open file, path = '.' (OS Error: Is a directory, errno = 21)
#0      _File.throwIfError (dart:io/file_impl.dart:562)
#1      _File.openSync (dart:io/file_impl.dart:413)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:531)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:555)
#4      JSModuleFile.writeCodeSync (package:dev_compiler/src/compiler/compiler.dart:514)
#5      _compile (package:dev_compiler/src/compiler/command.dart:180)
#6      compile (package:dev_compiler/src/compiler/command.dart:47)
#7      main.<main_async_body> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:53)
#8      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by vsmenon** [comment]
Marking dup of #27326
