### ISSUE TITLE
New driver task failed: Element mismatch

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#28158]
When adding arguments to a call site that don't exist in the declaration, I see this exception.
May have been triggered by analysis, or while I was editing, or when I asked for quick fixes at the call site... not sure.

```
[  37628]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.22.0-edge.1d7fb1c6bae09913ca2499eba2a515c097e53ef0, server version 1.17.0, error: Task failed: BuildCompilationUnitElementTask for source /********/dartlang/sdk/pkg/dev_compiler/lib/src/analyzer/context.dart
Element mismatch in /*********/dartlang/sdk/pkg/dev_compiler/lib/src/analyzer/context.dart at createAnalysisContext() → AnalysisContextImpl
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:50)
#1      BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1084)
#2      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#3      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#4      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#5      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#6      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723)
#7      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1292)
#8      AnalysisContextImpl.resolveCompilationUnit (package:analyzer/src/context/context.dart:1286)
#9      ElementImpl.unit (package:analyzer/src/dart/element/element.dart:2977)
#10     ElementImpl.getNodeMatching (package:analyzer/src/dart/element/element.dart:3068)
#11     FunctionElementImpl.computeNode (package:analyzer/src/dart/element/element.dart:4446)
#12     FixProcessor._addFix_addMissingParameter (package:analysis_server/src/services/correction/fix_internal.dart:494)
#13     FixProcessor.compute.<compute_async_body> (package:analysis_server/src/services/correction/fix_internal.dart:271)
#14     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#15     _rootRun (dart:async/zone.dart:1146)
#16     _CustomZone.run (dart:async/zone.dart:1026)
#17     _CustomZone.runGuarded (dart:async/zone.dart:924)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#19     _rootRun (dart:async/zone.dart:1150)
#20     _CustomZone.run (dart:async/zone.dart:1026)
#21     _CustomZone.runGuarded (dart:async/zone.dart:924)
#22     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Caused by RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/array.dart:134)
#1      ElementWalker.getParameter (package:analyzer/src/generated/declaration_resolver.dart:661)
#2      DeclarationResolver.visitSimpleFormalParameter (package:analyzer/src/generated/declaration_resolver.dart:357)
#3      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9044)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#5      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4830)
#6      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:836)
#7      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4826)
#8      FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5335)
#9      RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:860)
#10     DeclarationResolver.visitFunctionExpression (package:analyzer/src/generated/declaration_resolver.dart:243)
#11     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)
#12     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5181)
#13     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:848)
#14     DeclarationResolver.visitFunctionDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:225)
#15     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:502)
#16     DeclarationResolver.visitFunctionDeclaration (package:analyzer/src/generated/declaration_resolver.dart:224)
#17     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5174)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#19     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#20     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:698)
#21     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#22     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:47)
#23     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1084)
#24     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#25     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#26     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#27     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#28     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723)
#29     AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1292)
#30     AnalysisContextImpl.resolveCompilationUnit (package:analyzer/src/context/context.dart:1286)
#31     ElementImpl.unit (package:analyzer/src/dart/element/element.dart:2977)
#32     ElementImpl.getNodeMatching (package:analyzer/src/dart/element/element.dart:3068)
#33     FunctionElementImpl.computeNode (package:analyzer/src/dart/element/element.dart:4446)
#34     FixProcessor._addFix_addMissingParameter (package:analysis_server/src/services/correction/fix_internal.dart:494)
#35     FixProcessor.compute.<compute_async_body> (package:analysis_server/src/services/correction/fix_internal.dart:271)
#36     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#37     _rootRun (dart:async/zone.dart:1146)
#38     _CustomZone.run (dart:async/zone.dart:1026)
#39     _CustomZone.runGuarded (dart:async/zone.dart:924)
#40     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#41     _rootRun (dart:async/zone.dart:1150)
#42     _CustomZone.run (dart:async/zone.dart:1026)
#43     _CustomZone.runGuarded (dart:async/zone.dart:924)
#44     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:208)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
[  37630]  ERROR - yzer.DartAnalysisServerService - IntelliJ IDEA 2016.2.4  Build #IC-162.2032.8 
[  37630]  ERROR - yzer.DartAnalysisServerService - JDK: 1.8.0_102-google-v7 
[  37631]  ERROR - yzer.DartAnalysisServerService - VM: OpenJDK 64-Bit Server VM 
[  37631]  ERROR - yzer.DartAnalysisServerService - Vendor: Google Inc. 
[  37631]  ERROR - yzer.DartAnalysisServerService - OS: Linux 
[  37631]  ERROR - yzer.DartAnalysisServerService - Last Action: Back 
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I think https://github.com/dart-lang/sdk/commit/305d0dff8934efbbc120250b9db4397fba0b38c1 fixes this.
