### ISSUE TITLE
SDK version 1.22.0-dev.2.0: NoSuchMethodError: The getter 'name' was called on null

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#28163]
I was editing syntactically invalid code.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.SNAPSHOT`
- `1.22.0-dev.2.0`
- `171.SNAPSHOT, JRE 1.8.0_92-b14x64 Oracle Corporation, OS Windows 10(amd64) v10.0 , screens 1920x1200`

## Exception

```
Dart analysis server, SDK version 1.22.0-dev.2.0, server version 1.17.0, error: Exception from fix contributor: DefaultFixContributor
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      FixProcessor._addFix_makeEnclosingClassAbstract (package:analysis_server/src/services/correction/fix_internal.dart:1662)
#3      FixProcessor.compute.<compute_async_body> (package:analysis_server/src/services/correction/fix_internal.dart:293)
#4      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#5      _rootRun (dart:async/zone.dart:1146)
#6      _CustomZone.run (dart:async/zone.dart:1026)
#7      _CustomZone.runGuarded (dart:async/zone.dart:924)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2609833002/
