### ISSUE TITLE
Dart Analysis failed after enabling strong mode + code update + pub get

### ISSUE THREAD

**Issue by denisoby** [dart-lang/sdk#28208]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.1834.8`
- `1.21.0`
- `WS-171.1834.8, JRE 1.8.0_112-release-b620x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-57-generic unknown, screens 3840x1080`

## Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.21.0, server version 1.17.0, error: Task failed: ResolveDirectiveElementsTask for source /home/denis/.pub-cache/hosted/http%58%47%47pub-dev.wrke.in/csslib-0.13.2 2/lib/visitor.dart
Unexpected exception while performing ResolveDirectiveElementsTask for source /home/denis/.pub-cache/hosted/http%58%47%47pub-dev.wrke.in/csslib-0.13.2 2/lib/visitor.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by NoSuchMethodError: The getter 'imports' was called on null.
Receiver: null
Tried calling: imports
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      DirectiveResolver.visitImportDirective (package:analyzer/src/generated/resolver.dart:2312)
#3      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:5948)
#4      DirectiveResolver.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:2292)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#6      ResolveDirectiveElementsTask.internalPerform (package:analyzer/src/task/dart.dart:5029)
#7      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#8      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#9      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#10     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#11     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#13     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#14     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#15     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
