### ISSUE TITLE
js-interop: NoSuchMethodError: The method '_operator_getter' was called on null

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/sdk#28203]
**Describe the issue you're seeing**
When importing a port of highlight.js generated with `dart_js_facade_gen` into an NG2 app, I get a strange error:

```
EXCEPTION: NoSuchMethodError: The method '_operator_getter' was called on null.
Receiver: null
Tried calling: _operator_getter("js")
VM61:1 EXCEPTION: NoSuchMethodError: The method '_operator_getter' was called on null.
Receiver: null
Tried calling: _operator_getter("js")(anonymous function) @ VM61:1
VM61:1 STACKTRACE:(anonymous function) @ VM61:1
VM61:1 #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      JsNative.getProperty (dart:js:1451)
#3      highlightBlock (package:angel_site/highlight.dart_js_interop_patch.dart:247:93)
#4      HomeComponent.ngOnInit (http://localhost:3000/components/home/home.dart:17:5)
#5      ViewHomeComponentHost0.detectChangesInternal (http://localhost:3000/components/home/home.template.dart:107:132)
#6      AppView.detectChanges (package:angular2/src/core/linker/app_view.dart:350:5)
#7      DebugAppView.detectChanges (package:angular2/src/debug/debug_app_view.dart:138:28)
#8      AppView.detectContentChildrenChanges (package:angular2/src/core/linker/app_view.dart:366:26)
#9      ViewAngelSiteComponent0.detectChangesInternal (http://localhost:3000/components/angel_site/angel_site.template.dart:479:10)
#10     AppView.detectChanges (package:angular2/src/core/linker/app_view.dart:350:5)
#11     DebugAppView.detectChanges (package:angular2/src/debug/debug_app_view.dart:138:28)
#12     AppView.detectViewChildrenChanges (package:angular2/src/core/linker/app_view.dart:372:23)
#13     AppView.detectChangesInternal (package:angular2/src/core/linker/app_view.dart:361:5)
#14     AppView.detectChanges (package:angular2/src/core/linker/app_view.dart:350:5)
#15     DebugAppView.detectChanges (package:angular2/src/debug/debug_app_view.dart:138:28)
#16     ViewRefImpl.detectChanges (package:angular2/src/core/linker/view_ref.dart:104:13)
#17     ApplicationRefImpl.tick (package:angular2/src/core/application_ref.dart:383:32)
#18     ApplicationRefImpl.ApplicationRefImpl.<anonymous closure>.<anonymous closure> (package:angular2/src/core/application_ref.dart:268:9)
#19     _rootRun (dart:async/zone.dart:1150)
#20     _ZoneDelegate.run (dart:async/zone.dart:693)
#21     NgZoneImpl._run (package:angular2/src/core/zone/ng_zone_impl.dart:146:21)
#22     _CustomZone.run (dart:async/zone.dart:1026)
#23     _CustomZone.runGuarded (dart:async/zone.dart:924)
#24     NgZoneImpl.runInnerGuarded (package:angular2/src/core/zone/ng_zone_impl.dart:115:23)
#25     NgZone.runGuarded (package:angular2/src/core/zone/ng_zone.dart:200:27)
#26     ApplicationRefImpl.ApplicationRefImpl.<anonymous closure> (package:angular2/src/core/application_ref.dart:267:13)
#27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#30     _SyncBroadcastStreamController._sendData.<anonymous closure> (dart:async/broadcast_stream_controller.dart:394)
#31     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:335)
#32     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:393)
#33     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:261)
#34     EventEmitter.emit (package:angular2/src/facade/async.dart:25:17)
#35     NgZone._checkStable (package:angular2/src/core/zone/ng_zone.dart:141:34)
#36     NgZone.NgZone.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:124:16)
#37     NgZoneImpl._run (package:angular2/src/core/zone/ng_zone_impl.dart:148:14)
#38     _CustomZone.run (dart:async/zone.dart:1026)
#39     _CustomZone.runGuarded (dart:async/zone.dart:924)
#40     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#43     _ScheduleImmediateHelper._handleMutation (dart:html:49308)
```

**Does it happen in Dartium or when compiled to JavaScript?**
Both.

* Dart SDK version: *Dart VM version: 1.21.0 (Wed Dec  7 06:44:15 2016) on "macos_x64"*
* pkg/js version: *0.6.1*

Failing code:
[Generated Interop Library](https://github.com/angel-dart/site/blob/master/lib/highlight.dart)
[HomeComponent](https://github.com/angel-dart/site/blob/master/web/components/home/home.dart#L17)

**Comment by kulshekhar** [comment]
The problem might be with `"highlight.js.hljs.blockText"` being used when it should probably be `"hljs.blockText"` (and similar changes on other methods).

Posting the issue on the [js_facade_gen](https://github.com/dart-lang/js_facade_gen) might get you some sort of a resolution quicker

**Comment by thosakwe** [comment]
@kulshekhar Thanks, I'll try that. Also, great work on Jaguar. ;)

**Comment by thosakwe** [comment]
Woohoo! It worked.

**Comment by kulshekhar** [comment]
@thosakwe no problem

(I'm not associated with Jaguar, btw)
