### ISSUE TITLE
Unexpected exception while performing GatherUsedLocalElementsTask for source

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#28225]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Writing Dart code.  Happy to share the project if needed.

### Versions

- Dart SDK 1.21.0
- Visual Studio Code 1.8.1
- Dart Code 0.14.7

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.14.7
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Stuff/Projects/lol_duel",
        "explicitFileCount": 10,
        "implicitFileCount": 113,
        "workItemQueueLength": 4,
        "cacheEntryExceptions": [
            "Unexpected exception while performing GatherUsedLocalElementsTask for source /Stuff/Projects/lol_duel/lib/lolsim.dart\n#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)\n#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)\n#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)\n#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)\n#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)\n#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)\n#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)\n#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)\n#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)\n#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)\n#10     _rootRun (dart:async/zone.dart:1146)\n#11     _CustomZone.run (dart:async/zone.dart:1026)\n#12     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#14     _rootRun (dart:async/zone.dart:1150)\n#15     _CustomZone.run (dart:async/zone.dart:1026)\n#16     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)\n#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)\n#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)\n#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n\nCaused by Bad state: Unable to find Iterable<String> mapsString in [null mapsString]\n#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3153)\n#1      LocalVariableElementImpl.identifier (package:analyzer/src/dart/element/element.dart:6049)\n#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3193)\n#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2911)\n#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2800)\n#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)\n#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)\n#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10460)\n#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3471)\n#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)\n#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)\n#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)\n#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:596)\n#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)\n#14     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7426)\n#15     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:992)\n#16     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7419)\n#17     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10866)\n#18     RecursiveAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1203)\n#19     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10860)\n#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)\n#21     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10958)\n#22     RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1209)\n#23     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10952)\n#24     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11013)\n#25     RecursiveAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:1215)\n#26     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11009)\n#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)\n#28     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)\n#29     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:638)\n#30     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)\n#31     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)\n#32     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:644)\n#33     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)\n#34     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7306)\n#35     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:986)\n#36     GatherUsedLocalElementsVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:3481)\n#37     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7297)\n#38     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)\n#39     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)\n#40     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:674)\n#41     GatherUsedLocalElementsVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3451)\n#42     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)\n#43     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)\n#44     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)\n#45     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:698)\n#46     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)\n#47     GatherUsedLocalElementsTask.internalPerform (package:analyzer/src/task/dart.dart:3085)\n#48     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)\n#49     AnalysisTask.perform (package:analyzer/task/model.dart:220)\n#50     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)\n#51     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)\n#52     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)\n#53     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)\n#54     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)\n#55     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)\n#56     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)\n#57     Future.Future.<anonymous closure> (dart:async/future.dart:118)\n#58     _rootRun (dart:async/zone.dart:1146)\n#59     _CustomZone.run (dart:async/zone.dart:1026)\n#60     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#61     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#62     _rootRun (dart:async/zone.dart:1150)\n#63     _CustomZone.run (dart:async/zone.dart:1026)\n#64     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#65     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#66     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)\n#67     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)\n#68     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)\n#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n\n"
        ]
    }
]
```

### Exception

Task failed: GatherUsedLocalElementsTask for source /Stuff/Projects/lol_duel/lib/lolsim.dart

```text
Unexpected exception while performing GatherUsedLocalElementsTask for source /Stuff/Projects/lol_duel/lib/lolsim.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find Iterable<String> mapsString in [null mapsString]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3153)
#1      LocalVariableElementImpl.identifier (package:analyzer/src/dart/element/element.dart:6049)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3193)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2911)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2800)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10460)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3471)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:596)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#14     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7426)
#15     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:992)
#16     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7419)
#17     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10866)
#18     RecursiveAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1203)
#19     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10860)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#21     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10958)
#22     RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1209)
#23     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10952)
#24     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11013)
#25     RecursiveAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:1215)
#26     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11009)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#28     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#29     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:638)
#30     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#31     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#32     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:644)
#33     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#34     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7306)
#35     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:986)
#36     GatherUsedLocalElementsVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:3481)
#37     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7297)
#38     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#39     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#40     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:674)
#41     GatherUsedLocalElementsVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3451)
#42     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#43     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#44     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#45     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:698)
#46     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#47     GatherUsedLocalElementsTask.internalPerform (package:analyzer/src/task/dart.dart:3085)
#48     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#49     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#50     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#51     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#52     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#53     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#54     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#55     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#56     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#57     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#58     _rootRun (dart:async/zone.dart:1146)
#59     _CustomZone.run (dart:async/zone.dart:1026)
#60     _CustomZone.runGuarded (dart:async/zone.dart:924)
#61     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#62     _rootRun (dart:async/zone.dart:1150)
#63     _CustomZone.run (dart:async/zone.dart:1026)
#64     _CustomZone.runGuarded (dart:async/zone.dart:924)
#65     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#66     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#67     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#68     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by srawlins** [comment]
Thanks for opening this issue. Unfortunately we didn't look at this before it grew stale. More recent versions of Dart appear to not be crashing on this code path.
