### ISSUE TITLE
Unexpected exception while performing GatherUsedLocalElementsTask

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#28224]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Editing files in a local dart project (I'm happy to share if needed).

### Versions

- Dart SDK 1.21.0
- Visual Studio Code 1.8.1
- Dart Code 0.14.7

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.14.7
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Stuff/Projects/lol_duel",
        "explicitFileCount": 10,
        "implicitFileCount": 112,
        "workItemQueueLength": 4,
        "cacheEntryExceptions": [
            "Unexpected exception while performing GatherUsedLocalElementsTask for source /Stuff/Projects/lol_duel/lib/lolsim.dart\n#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)\n#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)\n#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)\n#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)\n#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)\n#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)\n#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)\n#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)\n#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)\n#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)\n#10     _rootRun (dart:async/zone.dart:1146)\n#11     _CustomZone.run (dart:async/zone.dart:1026)\n#12     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#14     _rootRun (dart:async/zone.dart:1150)\n#15     _CustomZone.run (dart:async/zone.dart:1026)\n#16     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)\n#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)\n#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)\n#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n\nCaused by Bad state: Unable to find (Mob mob) → void in [(null mob) → dynamic]\n#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3153)\n#1      FunctionElementImpl.identifier (package:analyzer/src/dart/element/element.dart:4391)\n#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3193)\n#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2911)\n#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2800)\n#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)\n#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)\n#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10460)\n#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3471)\n#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)\n#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)\n#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)\n#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:596)\n#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)\n#14     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7426)\n#15     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:992)\n#16     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7419)\n#17     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4257)\n#18     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:806)\n#19     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4253)\n#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)\n#21     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)\n#22     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:638)\n#23     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)\n#24     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)\n#25     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:644)\n#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)\n#27     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7306)\n#28     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:986)\n#29     GatherUsedLocalElementsVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:3481)\n#30     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7297)\n#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)\n#32     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)\n#33     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:674)\n#34     GatherUsedLocalElementsVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3451)\n#35     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)\n#36     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)\n#37     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)\n#38     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:698)\n#39     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)\n#40     GatherUsedLocalElementsTask.internalPerform (package:analyzer/src/task/dart.dart:3085)\n#41     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)\n#42     AnalysisTask.perform (package:analyzer/task/model.dart:220)\n#43     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)\n#44     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)\n#45     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)\n#46     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)\n#47     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)\n#48     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)\n#49     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)\n#50     Future.Future.<anonymous closure> (dart:async/future.dart:118)\n#51     _rootRun (dart:async/zone.dart:1146)\n#52     _CustomZone.run (dart:async/zone.dart:1026)\n#53     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#54     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#55     _rootRun (dart:async/zone.dart:1150)\n#56     _CustomZone.run (dart:async/zone.dart:1026)\n#57     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#58     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#59     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)\n#60     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)\n#61     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)\n#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n\n"
        ]
    }
]
```

### Exception

Task failed: GatherUsedLocalElementsTask for source /Stuff/Projects/lol_duel/lib/lolsim.dart

```text
Unexpected exception while performing GatherUsedLocalElementsTask for source /Stuff/Projects/lol_duel/lib/lolsim.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find (Mob mob) → void in [(null mob) → dynamic]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3153)
#1      FunctionElementImpl.identifier (package:analyzer/src/dart/element/element.dart:4391)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3193)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2911)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2800)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10460)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3471)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:596)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#14     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7426)
#15     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:992)
#16     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7419)
#17     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4257)
#18     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:806)
#19     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4253)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#21     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#22     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:638)
#23     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#24     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#25     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:644)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#27     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7306)
#28     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:986)
#29     GatherUsedLocalElementsVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:3481)
#30     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7297)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#32     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#33     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:674)
#34     GatherUsedLocalElementsVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3451)
#35     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#36     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#37     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#38     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:698)
#39     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#40     GatherUsedLocalElementsTask.internalPerform (package:analyzer/src/task/dart.dart:3085)
#41     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#42     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#43     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#44     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#45     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#46     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#47     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#48     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#49     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#50     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#51     _rootRun (dart:async/zone.dart:1146)
#52     _CustomZone.run (dart:async/zone.dart:1026)
#53     _CustomZone.runGuarded (dart:async/zone.dart:924)
#54     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#55     _rootRun (dart:async/zone.dart:1150)
#56     _CustomZone.run (dart:async/zone.dart:1026)
#57     _CustomZone.runGuarded (dart:async/zone.dart:924)
#58     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#59     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#60     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#61     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by srawlins** [comment]
Apologies we did not get a chance to look at this error before it became stale. Please re-open if you see this again.
