### ISSUE TITLE
Exception while handling watch event

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#28229]
The exception below was thrown (by the 'replay' stress tester) while attempting to create a context builder in response to a watch event.

The error was reported as being associated with request '2', but (a) a response to request '2' had already been received and (b) the error wasn't received until after a response to request '395' had been received.

There were numerous git checkouts during the test run, and it seems likely that there is a timing issue in that the server is examining the state of the disk at the same time git is changing that state. That seems likely, given the additional information that the error only occurs on about half of the runs of the test.

@scheglov The new driver was not enabled, but I'm wondering whether any of the changes required to accommodate the new driver might have (a) introduced this bug or (b) caused it to be erroneously reported as an error associated with request '2'.
```
Unhandled exception:
Bad state: Server error: {event: server.error, params: {isFatal: true, message: Failed to handle request: {params: {included: [/Users/brianwilkerson/src/test/polymer1], excluded: []}, method: analysis.setAnalysisRoots, id: 2}, stackTrace: Invalid argument (path): Directory does not exist.: "/Users/brianwilkerson/src/test/polymer1/core_dropdown_item_label"
#0      ContextBuilder._findPackagesLocation (package:analyzer/src/context/builder.dart:452:7)
#1      ContextBuilder.findPackagesFromFile (package:analyzer/src/context/builder.dart:246:25)
#2      ContextBuilder.createPackageMap (package:analyzer/src/context/builder.dart:196:12)
#3      ContextBuilder.createSourceFactory (package:analyzer/src/context/builder.dart:211:25)
#4      ContextManagerImpl._createSourceFactory (package:analysis_server/src/context_manager.dart:1280:20)
#5      ContextManagerImpl._updateContextPackageUriResolver (package:analysis_server/src/context_manager.dart:1718:11)
#6      ContextManagerImpl._recomputeFolderDisposition (package:analysis_server/src/context_manager.dart:1668:5)
#7      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1420:7)
#8      _rootRunUnary (dart:async/zone.dart:1158)
#9      _CustomZone.runUnary (dart:async/zone.dart:1037)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:386)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:261)
#15     _rootRunUnary (dart:async/zone.dart:1158)
#16     _CustomZone.runUnary (dart:async/zone.dart:1037)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#19     _DelayedData.perform (dart:async/stream_impl.dart:590)
#20     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#21     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:666)
#22     _rootRun (dart:async/zone.dart:1146)
#23     _CustomZone.run (dart:async/zone.dart:1026)
#24     _CustomZone.runGuarded (dart:async/zone.dart:924)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#26     _rootRun (dart:async/zone.dart:1150)
#27     _CustomZone.run (dart:async/zone.dart:1026)
#28     _CustomZone.runGuarded (dart:async/zone.dart:924)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
}}
```

**Comment by bwilkerson** [comment]
I'm assuming that this is stale.
