### ISSUE TITLE
Task failed: BuildCompilationUnitElementTask for source

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#28232]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Editing lolsim.dart in https://github.com/eseidel/lolsim

### Versions

- Dart SDK 1.21.0
- Visual Studio Code 1.8.1
- Dart Code 0.14.7

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.14.7
```

### Exception

Task failed: BuildCompilationUnitElementTask for source /Stuff/Projects/lol_duel/lib/lolsim.dart

```text
Element mismatch in /Stuff/Projects/lol_duel/lib/lolsim.dart at class Mob
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:50)
#1      BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1082)
#2      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#3      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#4      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#5      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#6      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#8      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#9      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#10     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#11     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#12     _rootRun (dart:async/zone.dart:1146)
#13     _CustomZone.run (dart:async/zone.dart:1026)
#14     _CustomZone.runGuarded (dart:async/zone.dart:924)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#16     _rootRun (dart:async/zone.dart:1150)
#17     _CustomZone.run (dart:async/zone.dart:1026)
#18     _CustomZone.runGuarded (dart:async/zone.dart:924)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#20     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#21     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#22     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Element offset mismatch
#0      DeclarationResolver._matchOffset (package:analyzer/src/generated/declaration_resolver.dart:451)
#1      DeclarationResolver._match (package:analyzer/src/generated/declaration_resolver.dart:445)
#2      DeclarationResolver.visitMethodDeclaration (package:analyzer/src/generated/declaration_resolver.dart:322)
#3      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7297)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#5      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#6      RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:674)
#7      DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:87)
#8      DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:502)
#9      DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:86)
#10     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#13     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:698)
#14     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#15     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:47)
#16     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1082)
#17     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#18     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#19     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#20     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#21     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#23     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#24     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#25     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#26     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#27     _rootRun (dart:async/zone.dart:1146)
#28     _CustomZone.run (dart:async/zone.dart:1026)
#29     _CustomZone.runGuarded (dart:async/zone.dart:924)
#30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#31     _rootRun (dart:async/zone.dart:1150)
#32     _CustomZone.run (dart:async/zone.dart:1026)
#33     _CustomZone.runGuarded (dart:async/zone.dart:924)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#35     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#36     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#37     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
