### ISSUE TITLE
Analyzer error after deleting a project from another IntelliJ instance and switching back.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#28230]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.1834.9`
- `1.22.0-edge.55b62121b0f6d64207927f09fe920c62bee8fd43`
- `IU-171.1834.9, JRE 1.8.0_112-release-b620x64 JetBrains s.r.o, OS Linux(amd64) v4.8.0-2-amd64 unknown, screens 3840x2160`

## Exception

```
Dart analysis server, SDK version 1.22.0-edge.55b62121b0f6d64207927f09fe920c62bee8fd43, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1483343598804, params: {file: /designer.dart, offset: 305, length: 86}, method: analysis.getNavigation, id: 469}
NoSuchMethodError: The method 'then' was called on null.
Receiver: null
Tried calling: then(Closure: (AnalysisDoneReason) => dynamic)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AnalysisDomainHandler.getNavigation.<getNavigation_async_body> (package:analysis_server/src/domain_analysis.dart:177)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#4      _rootRun (dart:async/zone.dart:1146)
#5      _CustomZone.run (dart:async/zone.dart:1026)
#6      _CustomZone.runGuarded (dart:async/zone.dart:924)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#8      _rootRun (dart:async/zone.dart:1150)
#9      _CustomZone.run (dart:async/zone.dart:1026)
#10     _CustomZone.runGuarded (dart:async/zone.dart:924)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
