### ISSUE TITLE
Dartium build instructions not working

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#28248]
Following the instructions from the wiki https://github.com/dart-lang/sdk/wiki/Building-Dartium results in an error during ```gclient runhooks```.

```
________ running '/usr/bin/python src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py --tools-directory=../../../../../../tools' in '/usr/local/google/home/fschneider/dartium'
/usr/local/google/home/fschneider/depot_tools/third_party/gsutil/gsutil
Traceback (most recent call last):
  File "src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py", line 101, in <module>
    sys.exit(main())
  File "src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py", line 98, in main
    return download(args.tools_directory, args.version_file)
  File "src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py", line 49, in download
    download_version_for_platform(version, platform, tools_directory)
  File "src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py", line 67, in download_version_for_platform
    depot_tools_path)
  File "/usr/local/google/home/fschneider/dartium/src/third_party/mojo/src/mojo/public/tools/pylib/gs.py", line 31, in download_from_public_bucket
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Error: Command '/usr/bin/python src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py --tools-directory=../../../../../../tools' returned non-zero exit status 1 in /usr/local/google/home/fschneider/dartium
```

There seems to be a mismatch of where the gsutil tool should be found.

**Comment by rh-galaxy** [comment]
[Windows] Several issues exists. Have been trying different solutions in build.py, gclient_utils.py, and options to ninja for ignoring warnings... nothing works fully. latest error: 

d:\dartium\src>ninja -v -C out\Debug chrome
[13/21002] D:\Program\depot_tools\python276_bin\python.exe gyp-win-tool action-wrapper environment.x86 nacl_lib_newlib_target_build_IRT_x86_32_nlib_12a5f5d7ade6835387ec213c3eb64334..rsp ..\..\native_client\src\untrusted\nacl
ninja: build stopped: subcommand failed.

**Comment by whesse** [comment]
This is because depot_tools have moved the gsutils to a new location.  I have fixed it in the past on buildbot by running (in the depot_tools directory):
cp -r external_bin/gsutil/gsutil_4.15/gsutil third_party
chmod 775 third_party/gsutil/gsutil

But now the buildbot is deleting those moved files on every run.
If we don't need the mojo shell download to build Dartium, then we should remove this step from the instructions.  I will try that first.

Otherwise, we could try moving the gsutil files, but this is something that should only happen on the buildbots.

This is now turning the Dartium linux builders red.

**Comment by whesse** [comment]
An alternative is to make the gsutil files undeletable by using chmod 555 instead of chmod 755.  I am trying that as well.

**Comment by whesse** [comment]
I think this has been fixed by the roll to Dartium 50.  It is certainly not P0.  P3 to verify the fix.
