### ISSUE TITLE
url size limitation

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28251]
_From @lejard-h on January 2, 2017 15:19_

Reproduce

```dart
import 'package:http/http.dart';

main() {
  Client client = new IOClient();
  String str = "a" * 10000;
  client.post("http://localhost:1338/$str").then((Response res) {
    print(res.statusCode);
    print(res.body);
    client.close();
  }, onError: (error) {
    print(error);
    client.close();
  });
}
```

`nc -l 1338`

I am getting this error but I cannot catch it.

```dart
Unhandled exception:
HttpException: Headers size exceeded the of '8192' bytes
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1138)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Is it the correct behaviour, I am dealing with an api that need a lot of data in the url, any workaround ?

_Copied from original issue: dart-lang/http#50_

**Comment by nex3** [comment]
There's no check for this in `http`, so I think this is a `dart:io` issue.

**Comment by lrhn** [comment]
It is. The `http_impl.dart` file writes the header into a buffer of size `const int _OUTGOING_BUFFER_SIZE = 8 * 1024;`.
The likely reason for choosing this limit is that some web servers have limits on the length of their headers, and the Apache web server is known to have an 8K limit (it also have a 1K line limit, so your URI will fail at that too).

Do we want to change this, and make the header size unlimited (by using a growing buffer instead of a fixed-size one)?

**Comment by floitschG** [comment]
@sgjesse: do you remember if there were good reasons for this limit?

**Comment by sgjesse** [comment]
The limitation is mainly an implementation detail, as we collect the whole header before sending the first byte of the response, and probably the size was chosen based on some known limitation that @lrhn mentions. I don't see any reason for not allowing larger header sizes (neither limiting the request line nor the headers part), by either extending the buffer dynamically, or sending it in several chunks. Probably sending several chunks would be the best solution.

There is a [stackoverflow article](http://stackoverflow.com/questions/1097651/is-there-a-practical-http-header-length-limit) describing limitations on various web servers - not sure how accurate it is, but typically an application deals with one specific web server for a particulair type of request, so having a common lower denominator does not realy make sense.

Not sure if we have the same limitation on our inbound HTTP (client response and server request), but there should be no limit there either.

Finally the [catch-all](https://github.com/dart-lang/sdk/blob/dff9e61d4dcf3df8fced73801fbb9f32669b8c39/sdk/lib/io/http_impl.dart#L937) that reports the "Headers size exceeded" exception seems wrong.

**Comment by lexaknyazev** [comment]
Maybe related: https://github.com/dart-lang/sdk/issues/25390
Such attack costs nothing for client, but could be harmful for server.

**Comment by thosakwe** [comment]
Are there any plans to ever fix this? I often use [`angel_proxy`](https://github.com/angel-dart/proxy) to proxy `pub serve` within my applications, and Angel responses are stored in a `BytesBuilder`. Trying to flush this to the `io` response sometimes produces the `Headers size exceeded` error, which makes it entirely impossible to run both my backend and `pub serve` together.

**Comment by lrhn** [comment]
It was changed, but reverted because it caused some test failures. I'm planning to try it again soon.

**Comment by thosakwe** [comment]
@lrhn Take your time. I refactored `angel_proxy` to just pipe one response into another, instead of sending an entire buffer. This seemed to work (I guess because the response ends up sent as chunks?)

**Comment by bugrevealingbme** [comment]
We want this limit to be increased or changed. I'm also stuck with this problem in my SpeedTest app.
