### ISSUE TITLE
applied latest angular_analyzer_pluging

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#28265]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.2014.21`
- `1.22.0-edge.5edca8c4d3733f319ab2d328aa28ceb286a30904`
- `IU-171.2014.21, JRE 1.8.0_112-release-b621x64 JetBrains s.r.o, OS Linux(amd64) v4.8.0-2-amd64 unknown, screens 3840x2160`

## Exception

Please append the contents of:
file:///tmp/report2.txt

```
Dart analysis server, SDK version 1.22.0-edge.5edca8c4d3733f319ab2d328aa28ceb286a30904, server version 1.17.0, error: Exception from analysis domain receiver: (AnalysisDomain) => void
Bad state: Should not be used with the new analysis driver
#0      ContextManagerImpl.folderMap (package:analysis_server/src/context_manager.dart:561)
#1      ContextManagerImpl.analysisContexts (package:analysis_server/src/context_manager.dart:557)
#2      AnalysisServer.analysisContexts (package:analysis_server/src/analysis_server.dart:447)
#3      AnalysisDomainImpl.onResultChanged (package:analysis_server/src/domain_analysis.dart:420)
#4      AnalysisDomainContributor.setAnalysisDomain (package:angular_analyzer_server_plugin/src/analysis.dart:33)
#5      AnalysisDomainHandler._callAnalysisDomainReceivers (package:analysis_server/src/domain_analysis.dart:387)
#6      AnalysisDomainHandler.AnalysisDomainHandler (package:analysis_server/src/domain_analysis.dart:47)
#7      ServerPlugin.registerExtensions.<anonymous closure> (package:analysis_server/src/plugin/server_plugin.dart:300)
#8      ServerPlugin.createDomains.<anonymous closure> (package:analysis_server/src/plugin/server_plugin.dart:228)
#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#10     ListIterable.toList (dart:_internal/iterable.dart:219)
#11     ServerPlugin.createDomains (package:analysis_server/src/plugin/server_plugin.dart:229)
#12     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:439)
#13     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:92)
#14     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#15     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:480)
#16     _rootRun (dart:async/zone.dart:1150)
#17     _CustomZone.run (dart:async/zone.dart:1026)
#18     runZoned (dart:async/zone.dart:1503)
#19     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:517)
#20     Driver.start (package:analysis_server/src/server/driver.dart:479)
#21     main (file:///home/zoechi/dart/dart-lang/angular_analyzer_plugin/server_plugin/bin/server.dart:19)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)

**Comment by zoechi** [comment]
This exception is thrown directly after applying the plugin and restarting the analyzer

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
The Angular plugin is not compatible with the latest Analysis Server.
We plan to separate plugins from Analysis Server itself in near future.
