### ISSUE TITLE
Flaky standalone/io/socket_source_address_test timeout

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#28266]
Happened on `vm-linux-debug-x64-be`

```
FAILED: none-vm-checked debug_x64 standalone/io/socket_source_address_test
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: PID 14780 - process
    TID 14780:
    #0  0x00007f291e0b8404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000862130 dart::Monitor::WaitMicros(long)
    #2  0x000000000065532a Dart_RunLoop
    #3  0x000000000054463d dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
    #4  0x000000000054581f dart::bin::main(int, char**)
    #5  0x0000000000546289 main
    #6  0x00007f291d2e0f45 __libc_start_main
    #7  0x000000000054417b _start
    TID 14781:
    #0  0x00007f291d3b9a13 epoll_wait
    #1  0x000000000054a0a5 dart::bin::EventHandlerImplementation::Poll(unsigned long)
    #2  0x00000000005677a3 dart::bin::ThreadStart(void*)
    #3  0x00007f291e0b4184 start_thread
    #4  0x00007f291d3b937d __clone
    TID 14782:
    #0  0x00007f291e0b8404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000862130 dart::Monitor::WaitMicros(long)
    #2  0x0000000000946f32 dart::ThreadInterrupter::ThreadMain(unsigned long)
    #3  0x0000000000861124 dart::ThreadStart(void*)
    #4  0x00007f291e0b4184 start_thread
    #5  0x00007f291d3b937d __clone
    TID 14783:
    #0  0x00007f291e0b8404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000862130 dart::Monitor::WaitMicros(long)
    #2  0x00000000006c4d6a dart::BackgroundCompiler::Run()
    #3  0x00000000009483b1 dart::ThreadPool::Worker::Loop()
    #4  0x00000000009481ed dart::ThreadPool::Worker::Main(unsigned long)
    #5  0x0000000000861124 dart::ThreadStart(void*)
    #6  0x00007f291e0b4184 start_thread
    #7  0x00007f291d3b937d __clone
    TID 14816:
    #0  0x00007f291e0b8404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000862130 dart::Monitor::WaitMicros(long)
    #2  0x00000000006c4d6a dart::BackgroundCompiler::Run()
    #3  0x00000000009483b1 dart::ThreadPool::Worker::Loop()
    #4  0x00000000009481ed dart::ThreadPool::Worker::Main(unsigned long)
    #5  0x0000000000861124 dart::ThreadStart(void*)
    #6  0x00007f291e0b4184 start_thread
    #7  0x00007f291d3b937d __clone
    
    

stdout:
unittest-suite-wait-for-done
Failed to execute test closure in attempt 0 (10 retries left).


Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/tests/standalone/io/socket_source_address_test.dart
Took 0:02:00.067789

Short reproduction command (experimental):
    python tools/test.py --checked -t120 standalone/io/socket_source_address_test
```

**Comment by nex3** [comment]
I think this has been fixed, intentionally or not. Recent logs for `vm-linux-debug-x64-be` don't include `standalone/io/socket_source_address_test` in their 20 slowest tests, which means that it's consistently running in less than 15s (out of a 2m timeout). I'm closing this for now.

**Comment by fsc8000** [comment]
This just failed again. In contrast to the first report there is an exception thrown before timing out.

https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-linux-release-x64-be%2F17699%2F%2B%2Frecipes%2Fsteps%2Fvm_tests%2F0%2Fstdout


```

FAILED: none-vm release_x64 standalone/io/socket_source_address_test
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: Process list including children: [26879]
    Trying to capture stack trace for pid 26879
    PID 26879 - process
    TID 26879:
    #0  0x00007fa2ef30e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000851f95 dart::Monitor::WaitMicros(long)
    #2  0x000000000064f61a Dart_RunLoop
    #3  0x0000000000523f4f dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
    #4  0x00000000005252e5 dart::bin::main(int, char**)
    #5  0x0000000000525c29 main
    #6  0x00007fa2ee536f45 __libc_start_main
    #7  0x000000000052389b _start
    TID 26880:
    #0  0x00007fa2ee60fa13 epoll_wait
    #1  0x0000000000528535 dart::bin::EventHandlerImplementation::Poll(unsigned long)
    #2  0x00000000005434ae dart::bin::ThreadStart(void*)
    #3  0x00007fa2ef30a184 start_thread
    #4  0x00007fa2ee60f37d __clone
    TID 26881:
    #0  0x00007fa2ef30e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000851f95 dart::Monitor::WaitMicros(long)
    #2  0x000000000095581f dart::ThreadInterrupter::ThreadMain(unsigned long)
    #3  0x00000000008516d9 dart::ThreadStart(void*)
    #4  0x00007fa2ef30a184 start_thread
    #5  0x00007fa2ee60f37d __clone
    TID 26883:
    #0  0x00007fa2ef30e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000851f95 dart::Monitor::WaitMicros(long)
    #2  0x00000000006b0bda dart::BackgroundCompiler::Run()
    #3  0x00000000009564dd dart::ThreadPool::Worker::Loop()
    #4  0x00000000009563a5 dart::ThreadPool::Worker::Main(unsigned long)
    #5  0x00000000008516d9 dart::ThreadStart(void*)
    #6  0x00007fa2ef30a184 start_thread
    #7  0x00007fa2ee60f37d __clone
    TID 26886:
    #0  0x00007fa2ef30e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000851f95 dart::Monitor::WaitMicros(long)
    #2  0x00000000006b0bda dart::BackgroundCompiler::Run()
    #3  0x00000000009564dd dart::ThreadPool::Worker::Loop()
    #4  0x00000000009563a5 dart::ThreadPool::Worker::Main(unsigned long)
    #5  0x00000000008516d9 dart::ThreadStart(void*)
    #6  0x00007fa2ef30a184 start_thread
    #7  0x00007fa2ee60f37d __clone
    
    

stdout:
unittest-suite-wait-for-done
Failed to execute test closure (retry id: 7) in attempt 0 (10 retries left).
Exception: Expect.fail('Unexpected: Expect.fail('Did not throw')')
Stacktrace: #0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.fail (package:expect/expect.dart:154:5)
#2      throws.<throws_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/socket_source_address_test.dart:21:16)
<asynchronous suspension>
#3      throws (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/socket_source_address_test.dart)
#4      testConnect.<testConnect_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/socket_source_address_test.dart:112:13)
<asynchronous suspension>
#5      testConnect (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/socket_source_address_test.dart)
#6      main.<main_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/socket_source_address_test.dart:171:11)
<asynchronous suspension>
#7      main.<main_async_body>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/socket_source_address_test.dart)
#8      retry.<retry_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/test_utils.dart:24:23)
<asynchronous suspension>
#9      retry (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/test_utils.dart)
#10     main.<main_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/socket_source_address_test.dart:170:9)
<asynchronous suspension>
#11     main (file:///mnt/data/b/build/slave/vm-linux-release-x64-be/build/sdk/tests/standalone/io/socket_source_address_test.dart)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```
