### ISSUE TITLE
standalone/io/raw_socket_test fails to pause the reader

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#28288]
Observed on release_simarm64 but it is likely a general race condition in the test.

```
FAILED: none-vm-checked release_simarm64 standalone/io/raw_socket_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <3386320>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      testPauseSocket.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simarm64-be/build/sdk/tests/standalone/io/raw_socket_test.dart:320:20)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#6      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#7      _StreamController._add (dart:async/stream_controller.dart:635)
#8      _StreamController.add (dart:async/stream_controller.dart:581)
#9      _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1252)
#10     _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:798)
#11     _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:804)
#12     _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:825)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=ReleaseSIMARM64 out/ReleaseSIMARM64/dart --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-simarm64-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-simarm64-be/build/sdk/tests/standalone/io/raw_socket_test.dart
Took 0:00:05.731242

Short reproduction command (experimental):
    python tools/test.py -mrelease -asimarm64 --checked -t240 standalone/io/raw_socket_test
```

The offending line is:

```dart
320: Expect.equals(0, bytesRead);  // Checks that reader is paused.
```

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2610893006

**Comment by nex3** [comment]
Both of the major authors of that test file have left the team, so I'm assigning to @whesse as the third biggest contributor. Feel free to reassign if you know someone more appropriate.

**Comment by mraleph** [comment]
This issue has been last updated 279 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.
