### ISSUE TITLE
Automatic error report from intellij

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/sdk#28294]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.2014.21`
- `1.22.0-dev.5.0`
- `IC-171.2014.21, JRE 1.8.0_112-release-b621x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-57-generic unknown, screens 4096x2160`

## Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.22.0-dev.5.0, server version 1.17.0, error: Analysis failed: /home/alexeieleusis/development/clue/bazel-clue/external/dart_linux_x86_64/dart-sdk/lib/html/dartium/html_dartium.dart
Bad state: No ErrorCode for _LintCode.invariant_boolean in /home/alexeieleusis/development/clue/bazel-clue/external/dart_linux_x86_64/dart-sdk/lib/html/dartium/html_dartium.dart
#0      AnalysisDriver._getErrorsFromSerialized.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:888)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#2      ListIterable.toList (dart:_internal/iterable.dart:219)
#3      AnalysisDriver._getErrorsFromSerialized (package:analyzer/src/dart/analysis/driver.dart:892)
#4      AnalysisDriver._getAnalysisResultFromBytes (package:analyzer/src/dart/analysis/driver.dart:859)
#5      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:711)
#6      PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1479)
#7      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:674)
#8      AnalysisDriver._performWork.<_performWork_async_body> (package:analyzer/src/dart/analysis/driver.dart:1033)
#9      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)

**Comment by bwilkerson** [comment]
This has been fixed in bleeding edge and the fix will be in the next roll of the SDK.
