### ISSUE TITLE
standalone/io/socket_bind_test.dart is flaky on SIMMIPS

### ISSUE THREAD

**Issue by DmitryOlshansky-google** [dart-lang/sdk#28315]
It used to pass but recently started to fail with:
```
Unhandled exception:
SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 34080
#0      testListenCloseListenClose.<testListenCloseListenClose_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/tests/standalone/io/socket_bind_test.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _RootZone.runBinary (dart:async/zone.dart:1410)
#3      _FutureListener.handleError (dart:async/future_impl.dart:146)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#6      _Future._completeError (dart:async/future_impl.dart:485)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

The test code in question is:
```dart
testListenCloseListenClose(String host) async {
  asyncStart();

  ServerSocket socket =
      await ServerSocket.bind(host, 0, shared: true);
  ServerSocket socket2 =
      await ServerSocket.bind(host, socket.port, shared: true);

  var subscription = socket.listen((_) { throw 'error'; });
  subscription.cancel();
  await socket.close();

  // The second socket should have kept the OS socket alive. We can therefore
  // test if it is working correctly.
  asyncStart();
  socket2.first.then((socket) async {
    await socket.drain();
    await socket.close();
    asyncEnd();
  });

  Socket client = await Socket.connect(host, socket2.port);
  await client.close();
  await client.drain();

  asyncEnd();
}
```

**Comment by fsc8000** [comment]
I noticed that the line number in frame 0 is missing. I'll file a separate issue for that.

**Comment by mkustermann** [comment]
The MIPS support has been removed some time ago, there are no flaky markers for this test in the status files and it doesn't seem like it has occurred in a while. Closing this issue therefore.
