### ISSUE TITLE
Memory leaks in isolate spawning

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#28351]
isolate/function_send1_test
isolate/issue_21398_parent_isolate_test

```
=================================================================
==2074==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3520 byte(s) in 22 object(s) allocated from:
    #0 0x60a72b in operator new(unsigned long) (/usr/local/google/home/rmacnak/dart3/sdk/out/ReleaseX64/dart+0x60a72b)
    #1 0x15d7610 in dart::BootstrapNatives::DN_Isolate_spawnUri(_Dart_NativeArguments*) (/usr/local/google/home/rmacnak/dart3/sdk/out/\
ReleaseX64/dart+0x15d7610)
```

**Comment by rmacnak-google** [comment]
@a-siva
