### ISSUE TITLE
Memory leaks in dart:io directory listing

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#28350]
standalone/io/directory_error_test
standalone/io/directory_fuzz_test
standalone/io/directory_list_nonexistent_test

```
=================================================================
==26549==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4097 byte(s) in 1 object(s) allocated from:
    #0 0x5e1eb3 in calloc (/mnt/data/b/build/slave/vm-linux-release-x64-asan-be/build/sdk/out/ReleaseX64/dart+0x5e1eb3)
    #1 0x64e383 in dart::bin::PathBuffer::PathBuffer() (/mnt/data/b/build/slave/vm-linux-release-x64-asan-be/build/sdk/out/ReleaseX64/dart+0x64e383)
    #2 0x649f63 in dart::bin::SyncDirectoryListing::SyncDirectoryListing(_Dart_Handle*, char const*, bool, bool) (/mnt/data/b/build/slave/vm-linux-release-x64-asan-be/build/sdk/out/ReleaseX64/dart+0x649f63)
    #3 0x649dbe in dart::bin::Builtin_Directory_FillWithDirectoryListing(_Dart_NativeArguments*) (/mnt/data/b/build/slave/vm-linux-release-x64-asan-be/build/sdk/out/ReleaseX64/dart+0x649dbe)
    #4 0xde7897 in dart::NativeEntry::NativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) (/mnt/data/b/build/slave/vm-linux-release-x64-asan-be/build/sdk/out/ReleaseX64/dart+0xde7897)
    #5 0x7fde1c4be7a2  (<unknown module>)
```

**Comment by rmacnak-google** [comment]
@zanderso
