### ISSUE TITLE
Unexpected exception while performing GatherUsedLocalElementsTask for source 

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#28356]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I was replacing all instances of log with _log in my source, having realized I was inadvertantly exporting the symbol `log` from my library.

### Versions

- Dart SDK 1.21.0
- Visual Studio Code 1.8.1
- Dart Code 0.14.9

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.14.9
```

### Exception

Task failed: GatherUsedLocalElementsTask for source /Stuff/Projects/lol_duel/lib/dragon.dart

```text
Unexpected exception while performing GatherUsedLocalElementsTask for source /Stuff/Projects/lol_duel/lib/dragon.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find (String itemId) → Item in [(null itemId) → dynamic]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3153)
#1      FunctionElementImpl.identifier (package:analyzer/src/dart/element/element.dart:4391)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3193)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2911)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2800)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10460)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3471)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:596)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#14     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7426)
#15     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:992)
#16     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7419)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#18     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#19     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:596)
#20     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#21     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6261)
#22     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:914)
#23     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6256)
#24     AssignmentExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:918)
#25     RecursiveAstVisitor.visitAssignmentExpression (package:analyzer/dart/ast/visitor.dart:620)
#26     AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:913)
#27     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4257)
#28     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:806)
#29     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4253)
#30     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#31     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#32     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:638)
#33     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#34     IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5810)
#35     RecursiveAstVisitor.visitIfStatement (package:analyzer/dart/ast/visitor.dart:890)
#36     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5805)
#37     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#38     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#39     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:638)
#40     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#41     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#42     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:644)
#43     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#44     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7306)
#45     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:986)
#46     GatherUsedLocalElementsVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:3481)
#47     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7297)
#48     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#49     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#50     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:674)
#51     GatherUsedLocalElementsVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3451)
#52     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#53     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#54     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#55     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:698)
#56     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#57     GatherUsedLocalElementsTask.internalPerform (package:analyzer/src/task/dart.dart:3085)
#58     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#59     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#60     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#61     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#62     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#63     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#64     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#65     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#66     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#67     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#68     _rootRun (dart:async/zone.dart:1146)
#69     _CustomZone.run (dart:async/zone.dart:1026)
#70     _CustomZone.runGuarded (dart:async/zone.dart:924)
#71     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#72     _rootRun (dart:async/zone.dart:1150)
#73     _CustomZone.run (dart:async/zone.dart:1026)
#74     _CustomZone.runGuarded (dart:async/zone.dart:924)
#75     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#76     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#77     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#78     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#79     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
