### ISSUE TITLE
Memory leak of timeline arguments

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#28354]
standalone/array_bounds_check_generalization_test

```
Too many leaks! Only the first 5000 leaks encountered will be reported.
Indirect leak of 693 byte(s) in 17 object(s) allocated from:
    #0 0x5ce603 in strdup (/usr/local/google/home/rmacnak/ssd/dart2/sdk/out/ReleaseX64/dart+0x5ce603)
    #1 0x13c21ab in dart::TimelineEventScope::CopyArgument(long, char const*, char const*) (/usr/local/google/h\
ome/rmacnak/ssd/dart2/sdk/out/ReleaseX64/dart+0x13c21ab)
    #2 0xffdcd8 in dart::Parser::ParseClass(dart::Class const&) (/usr/local/google/home/rmacnak/ssd/dart2/sdk/o\
ut/ReleaseX64/dart+0xffdcd8)
    #3 0x9eb3db in dart::Compiler::CompileClass(dart::Class const&) (/usr/local/google/home/rmacnak/ssd/dart2/s\
dk/out/ReleaseX64/dart+0x9eb3db)
...
```

**Comment by rmacnak-google** [comment]
@johnmccutchan

**Comment by mkustermann** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/dd91dd2319939900c871ff16e6203c637495870b
