### ISSUE TITLE
Bad state: Unknown expression type: this (SDK 1.22.0-dev.7.0)

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#28366]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.SNAPSHOT`
- `1.22.0-dev.7.0`
- `171.SNAPSHOT, JRE 1.8.0_92-b14x64 Oracle Corporation, OS Windows 10(amd64) v10.0 , screens 1920x1200`

## Exception
```
Dart analysis server, SDK version 1.22.0-dev.7.0, server version 1.17.0, error: Captured exception
Bad state: Unknown expression type: this
#0      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:392)
#1      AbstractConstExprSerializer._serializeArguments.<anonymous closure> (package:analyzer/src/summary/summarize_const_expr.dart:403)
#2      Object&ListMixin.forEach (dart:collection/list.dart:63)
#3      AbstractConstExprSerializer._serializeArguments (package:analyzer/src/summary/summarize_const_expr.dart:400)
#4      AbstractConstExprSerializer.serializeInstanceCreation (package:analyzer/src/summary/summarize_const_expr.dart:164)
#5      _ConstExprSerializer.serializeAnnotation (package:analyzer/src/summary/summarize_ast.dart:69)
#6      _SummarizeAstVisitor.serializeAnnotations.<anonymous closure> (package:analyzer/src/summary/summarize_ast.dart:421)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:412)
#8      ListIterable.toList (dart:_internal/iterable.dart:219)
#9      _SummarizeAstVisitor.serializeAnnotations (package:analyzer/src/summary/summarize_ast.dart:423)
#10     _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:479)
#11     _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1032)
#12     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8023)
#14     _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:524)
#15     serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22)
#16     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:389)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1484)
#18     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:388)
#19     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:619)
#20     _FilesReferencingNameTask.perform.<perform_async_body> (package:analyzer/src/dart/analysis/driver.dart:1609)
#21     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#22     _rootRun (dart:async/zone.dart:1146)
#23     _CustomZone.run (dart:async/zone.dart:1026)
#24     _CustomZone.runGuarded (dart:async/zone.dart:924)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#26     _rootRun (dart:async/zone.dart:1150)
#27     _CustomZone.run (dart:async/zone.dart:1026)
#28     _CustomZone.runGuarded (dart:async/zone.dart:924)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

```
1484245658998 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Bad state: Unknown expression type: this\n#0      AbstractConstExprSerializer._serialize
1484245654615 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\convert\\json.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C:\\dart_p
1484245654494 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\convert\\html_escape.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C:\
1484245654388 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\convert\\encoding.dart","errors":[]}}
1484245654292 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\convert\\converter.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C:\\d
1484245654194 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\convert\\convert.dart","errors":[]}}
1484245652110 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\splay_tree.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C
1484245652000 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\set.dart","errors":[]}}
1484245651912 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\queue.dart","errors":[]}}
1484245651805 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\maps.dart","errors":[]}}
1484245651109 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\list.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"C:\\dar
1484245649715 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\linked_list.dart","errors":[]}}
1484245649611 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\linked_hash_set.dart","errors":[]}}
1484245649499 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\linked_hash_map.dart","errors":[]}}
1484245649413 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\iterator.dart","errors":[]}}
1484245649099 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\iterable.dart","errors":[]}}
1484245648996 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\hash_set.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C:\
1484245648897 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\hash_map.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C:\
1484245646307 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\collections.dart","errors":[]}}
1484245643271 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\collection\\collection.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","locat
1484245643095 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\async\\zone.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C:\\dart_pro
1484245642901 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\async\\timer.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"C:\\dart_pr
1484245642719 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\async\\stream_transformers.dart","errors":[]}}
1484245642576 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\async\\stream_pipe.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C:\\d
1484245642401 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\async\\stream_impl.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C:\\d
1484245641582 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\async\\stream_controller.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":
1484245641362 <= {"id":"11","result":{"id":"0","element":{"kind":"FIELD","name":"CREATE_MISSING_METHOD_CALL","location":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analysis_server\\lib\\src\\serv
1484245641357 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\sdk\\lib\\async\\stream.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"C:\\dart_p
1484245641202 => {"id":"11","method":"search.findElementReferences","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analysis_server\\lib\\src\\services\\correction\\fix.dart","offset":7936,"
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/2628213003

**Comment by scheglov** [comment]
ada43dbf37987103e6240a612b0d0f6f13fc2409
