### ISSUE TITLE
Exception in prelinker

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#28391]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.SNAPSHOT`
- `1.22.0-edge.1f5562e29c917fa5f21944d80bde86dc687da3b1`
- `IC-171.SNAPSHOT, JRE 1.8.0_112-b16x64 Oracle Corporation, OS Mac OS X(x86_64) v10.12.2 unknown, screens 1680x1050  Retina`

## Exception

```
{"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/scheglov/Source/flutter/packages/flutter_tools/bin/fuchsia_builder.dart","stackTrace":"NoSuchMethodError: The method 'containsKey' was called on null.\nReceiver: null\nTried calling: containsKey(\"fs\")\n#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)\n#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)\n#2      _Prelinker.filterExportNamespace.<anonymous closure> (package:analyzer/src/summary/prelink.dart:356:43)\n#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:348)\n#4      _Prelinker.filterExportNamespace (package:analyzer/src/summary/prelink.dart:355:21)\n#5      _Prelinker.handleImport (package:analyzer/src/summary/prelink.dart:417:5)\n#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:412)\n#7      ListIterable.toList (dart:_internal/iterable.dart:219)\n#8      _Prelinker.prelink (package:analyzer/src/summary/prelink.dart:499:48)\n#9      prelink (package:analyzer/src/summary/prelink.dart:22:8)\n#10     setupForLink (package:analyzer/src/summary/link.dart:151:36)\n#11     link (package:analyzer/src/summary/link.dart:111:7)\n#12     AnalysisDriver._createLibraryContext.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:821:27)\n#13     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1484:15)\n#14     AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:820:15)\n#15     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1484:15)\n#16     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:769:20)\n#17     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:688:40)\n#18     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1484:15)\n#19     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:679:20)\n#20     AnalysisDriver._performWork.<_performWork_async_body> (package:analyzer/src/dart/analysis/driver.dart:1038:33)\n#21     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)\n#22     _rootRun (dart:async/zone.dart:1146)\n#23     _CustomZone.run (dart:async/zone.dart:1026)\n#24     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#26     _rootRun (dart:async/zone.dart:1150)\n#27     _CustomZone.run (dart:async/zone.dart:1026)\n#28     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#30     _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)\n#33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)\n#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n\n"}}
```

```
Dart analysis server, SDK version 1.22.0-edge.1f5562e29c917fa5f21944d80bde86dc687da3b1, server version 1.17.0, error: Analysis failed: /Users/scheglov/Source/flutter/packages/flutter_tools/bin/flutter_tools.dart
NoSuchMethodError: The method 'containsKey' was called on null.
Receiver: null
Tried calling: containsKey("fs")
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _Prelinker.filterExportNamespace.<anonymous closure> (package:analyzer/src/summary/prelink.dart:356:43)
#3      _HashVMBase
```

**Comment by stereotype441** [comment]
Change out for review: https://codereview.chromium.org/2655713002/
