### ISSUE TITLE
crash redirecting to unresolved

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#28392]
crash when using unresolved target on redirecting constructor:

```dart
import 'dart:mirrors';
abstract class _A {
  factory _A() = unresolved;
}

main() {
  reflectClass(_A);
}
```

produces this crash:
```
The compiler crashed: unsupported operation on erroneous element
#0      ErroneousElementX.unsupported (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/elements/modelx.dart:236)
#1      ErroneousElementX.functionSignature (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/elements/modelx.dart:247)
#2      SsaBuilder.visitRedirectingFactoryBody (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/ssa/builder.dart:5080)
#3      RedirectingFactoryBody.accept (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/tree/nodes.dart:1575)
#4      SsaBuilder.buildMethod (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/ssa/builder.dart:740)
#5      SsaBuilder.build (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/ssa/builder.dart:285)
#6      SsaBuilderTask.build.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/ssa/builder.dart:81)
#7      CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:1610)
#8      SsaBuilderTask.build.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/ssa/builder.dart:72)
#9      CompilerTask.measure (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63)
#10     SsaBuilderTask.build (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/ssa/builder.dart:70)
#11     SsaFunctionCompiler.compile (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/ssa/ssa.dart:43)
#12     JavaScriptBackend.codegen (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/js_backend/backend.dart:1502)
#13     CodegenWorkItem.run (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/codegen.dart:248)
#14     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:832)
#15     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#16     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:832)
#17     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#18     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:830)
#19     CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:1610)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:828)
#21     EnqueuerStrategy.processWorkItem (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/enqueue.dart:448)
#22     CodegenEnqueuer.forEach (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:236)
#23     Compiler.emptyQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:824)
#24     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#25     Compiler.emptyQueue (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:823)
#26     Compiler.processQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:852)
#27     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#28     Compiler.processQueue (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:841)
#29     Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:719)
#30     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#31     Compiler.compileLoadedLibraries (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:609)
#32     Compiler.runInternal.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:517)
#33     _RootZone.runUnary (dart:async/zone.dart:1404)
#34     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#35     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#36     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#37     _Future._completeWithValue (dart:async/future_impl.dart:477)
#38     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#41     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

We do report an error about the unresolved symbol and we don't crash unless mirrors are used (otherwise this factory is never generated even if it's invoked)

**Comment by bkonyi** [comment]
Closing as `dart:mirrors` is no longer supported on web.
