### ISSUE TITLE
I get these often lately when the analyzer starts working (for example after I killed it)

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#28397]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.2272.14`
- `1.22.0-edge.12a3699301b9efd176846c6d9d2daabb550c64eb`
- `IU-171.2272.14, JRE 1.8.0_112-release-b676x64 JetBrains s.r.o, OS Linux(amd64) v4.8.0-2-amd64 unknown, screens 3840x2160`

## Exception

Please append the contents of:
file:///tmp/report1433.txt

```
Dart analysis server, SDK version 1.22.0-edge.b13bb540e36593117cb45ffb7dcd0a7287b0f307, server version 1.17.0, error: Exception from assist contributor: DefaultAssistContributor
Instance of 'CancelCorrectionException'
#0      AssistProcessor.compute.<compute_async_body> (package:analysis_server/src/services/correction/assist_internal.dart:102)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#2      _rootRun (dart:async/zone.dart:1146)
#3      _CustomZone.run (dart:async/zone.dart:1026)
#4      _CustomZone.runGuarded (dart:async/zone.dart:924)
#5      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#6      _rootRun (dart:async/zone.dart:1150)
#7      _CustomZone.run (dart:async/zone.dart:1026)
#8      _CustomZone.runGuarded (dart:async/zone.dart:924)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#12     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)

**Comment by zoechi** [comment]
Haven't seen this for a while
