### ISSUE TITLE
analyzer: The getter 'apiSignature' was called on null.

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#28399]
Context: Using Visual Studio Code.

using - Dart SDK 1.22.0-dev.5.0

NoSuchMethodError: The getter 'apiSignature' was called on null.
Receiver: null
Tried calling: apiSignature

```text
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AnalysisDriver.AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:256)
#3      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1827)
#4      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1186)
#5      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1247)
#6      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:886)
#7      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:1211)
#8      AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:302)
#9      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:241)
#10     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:876)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#12     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:872)
#13     _rootRun (dart:async/zone.dart:1150)
#14     _CustomZone.run (dart:async/zone.dart:1026)
#15     _CustomZone.runGuarded (dart:async/zone.dart:924)
#16     runZoned (dart:async/zone.dart:1501)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:871)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
#22     _rootRunUnary (dart:async/zone.dart:1158)
#23     _CustomZone.runUnary (dart:async/zone.dart:1037)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:159)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:134)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#34     _rootRunUnary (dart:async/zone.dart:1158)
#35     _CustomZone.runUnary (dart:async/zone.dart:1037)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#47     _rootRunUnary (dart:async/zone.dart:1158)
#48     _CustomZone.runUnary (dart:async/zone.dart:1037)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#53     _StreamController._add (dart:async/stream_controller.dart:635)
#54     _StreamController.add (dart:async/stream_controller.dart:581)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1680)
#56     _rootRunUnary (dart:async/zone.dart:1162)
#57     _CustomZone.runUnary (dart:async/zone.dart:1037)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#62     _StreamController._add (dart:async/stream_controller.dart:635)
#63     _StreamController.add (dart:async/stream_controller.dart:581)
#64     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:781)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#68     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
The new analysis driver requires that the Dart SDK has summaries.

Do you use `EmbedderSdk`? Before [this change](https://github.com/dart-lang/sdk/commit/c5b994750e98982c3d1ff733bc799bfff01f5d87) it had summaries only in [strong mode](https://github.com/dart-lang/sdk/issues/28384). @pq I believe is working on landing the PR that will build Flutter specific Dart SDK summaries to be used by `EmbedderSdk`.

**Comment by pq** [comment]
Yep.  https://github.com/flutter/flutter/pull/7461.  Have nits to address and then will land.

**Comment by sethladd** [comment]
Sorry, I didn't add enough context. I was using Visual Studio Code.

**Comment by bwilkerson** [comment]
I saw the same exception in my log file. There isn't any context; this happened immediately after start-up (after `analysis.setAnalysisRoots`). I do not have any flutter code loaded and am using a locally built SDK.
```
1484675917532:Res:{"error"::{"code"::"SERVER_ERROR","message"::"NoSuchMethodError:: The getter 'apiSignature' was called on null.
Receiver:: null
Tried calling:: apiSignature","stackTrace"::"
#0      Object._noSuchMethod (dart::core-patch/object_patch.dart::44)
#1      Object.noSuchMethod (dart::core-patch/object_patch.dart::47)
#2      AnalysisDriver.AnalysisDriver (package::analyzer/src/dart/analysis/driver.dart::256)
#3      ServerContextManagerCallbacks.addAnalysisDriver (package::analysis_server/src/analysis_server.dart::1830)
#4      ContextManagerImpl._createContext (package::analysis_server/src/context_manager.dart::1169)
#5      ContextManagerImpl._createContexts (package::analysis_server/src/context_manager.dart::1211)
#6      ContextManagerImpl.setRoots (package::analysis_server/src/context_manager.dart::868)
#7      AnalysisServer.setAnalysisRoots (package::analysis_server/src/analysis_server.dart::1214)
#8      AnalysisDomainHandler.setAnalysisRoots (package::analysis_server/src/domain_analysis.dart::302)
#9      AnalysisDomainHandler.handleRequest (package::analysis_server/src/domain_analysis.dart::241)
#10     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package::analysis_server/src/analysis_server.dart::876)
#11     _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::189)
#12     AnalysisServer.handleRequest.<anonymous closure> (package::analysis_server/src/analysis_server.dart::872)
#13     _rootRun (dart::async/zone.dart::1150)
#14     _CustomZone.run (dart::async/zone.dart::1026)
#15     _CustomZone.runGuarded (dart::async/zone.dart::924)
#16     runZoned (dart::async/zone.dart::1501)
#17     AnalysisServer.handleRequest (package::analysis_server/src/analysis_server.dart::871)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package::analysis_server/src/channel/byte_stream_channel.dart::170)
#19     _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::189)
#20     ByteStreamServerChannel._readRequest (package::analysis_server/src/channel/byte_stream_channel.dart::161)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package::analysis_server/src/channel/byte_stream_channel.dart::110)
#22     _rootRunUnary (dart::async/zone.dart::1158)
#23     _CustomZone.runUnary (dart::async/zone.dart::1037)
#24     _CustomZone.runUnaryGuarded (dart::async/zone.dart::932)
#25     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::331)
#26     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::258)
#27     _SinkTransformerStreamSubscription._add (dart::async/stream_transformers.dart::67)
#28     _EventSinkWrapper.add (dart::async/stream_transformers.dart::14)
#29     _StringAdapterSink.add (dart::convert/string_conversion.dart::256)
#30     _LineSplitterSink._addLines (dart::convert/line_splitter.dart::159)
#31     _LineSplitterSink.addSlice (dart::convert/line_splitter.dart::134)
#32     StringConversionSinkMixin.add (dart::convert/string_conversion.dart::180)
#33     _SinkTransformerStreamSubscription._handleData (dart::async/stream_transformers.dart::119)
#34     _rootRunUnary (dart::async/zone.dart::1158)
#35     _CustomZone.runUnary (dart::async/zone.dart::1037)
#36     _CustomZone.runUnaryGuarded (dart::async/zone.dart::932)
#37     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::331)
#38     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::258)
#39     _SinkTransformerStreamSubscription._add (dart::async/stream_transformers.dart::67)
#40     _EventSinkWrapper.add (dart::async/stream_transformers.dart::14)
#41     _StringAdapterSink.add (dart::convert/string_conversion.dart::256)
#42     _StringAdapterSink.addSlice (dart::convert/string_conversion.dart::260)
#43     _Utf8ConversionSink.addSlice (dart::convert/string_conversion.dart::336)
#44     _Utf8ConversionSink.add (dart::convert/string_conversion.dart::329)
#45     _ConverterStreamEventSink.add (dart::convert/chunked_conversion.dart::92)
#46     _SinkTransformerStreamSubscription._handleData (dart::async/stream_transformers.dart::119)
#47     _rootRunUnary (dart::async/zone.dart::1158)
#48     _CustomZone.runUnary (dart::async/zone.dart::1037)
#49     _CustomZone.runUnaryGuarded (dart::async/zone.dart::932)
#50     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::331)
#51     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::258)
#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart::async/stream_controller.dart::768)
#53     _StreamController._add (dart::async/stream_controller.dart::635)
#54     _StreamController.add (dart::async/stream_controller.dart::581)
#55     _Socket._onData (dart::io-patch/socket_patch.dart::1682)
#56     _rootRunUnary (dart::async/zone.dart::1162)
#57     _CustomZone.runUnary (dart::async/zone.dart::1037)
#58     _CustomZone.runUnaryGuarded (dart::async/zone.dart::932)
#59     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::331)
#60     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::258)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart::async/stream_controller.dart::768)
#62     _StreamController._add (dart::async/stream_controller.dart::635)
#63     _StreamController.add (dart::async/stream_controller.dart::581)
#64     _RawSocket._RawSocket.<anonymous closure> (dart::io-patch/socket_patch.dart::1249)
#65     _NativeSocket.issueReadEvent.issue (dart::io-patch/socket_patch.dart::783)
#66     _microtaskLoop (dart::async/schedule_microtask.dart::41)
#67     _startMicrotaskLoop (dart::async/schedule_microtask.dart::50)
#68     _runPendingImmediateCallback (dart::isolate-patch/isolate_patch.dart::96)
#69     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::149)
"},"id"::"3"}
```

**Comment by pq** [comment]
I think you're hitting the issue tracked down here: https://github.com/flutter/flutter-intellij/issues/622.

Net-net, `1.22.0-dev.8.0` should resolve it.

**Comment by scheglov** [comment]
@bwilkerson One way or another you attempted to use a SDK without summaries.

**Comment by bwilkerson** [comment]
@pq I'm using bleeding edge as of 2 minutes ago, so I don't think there are any fixes in that dev release that will fix the problem.

@scheglov In the root of the directory containing the SDK that IntelliJ is configured to use:
```
$ ls lib/_internal/
ddc_sdk.sum		libraries.dart		sdk_library_metadata	strong.sum
js_runtime		pub			spec.sum
```
It appears that I have summaries. What am I missing?

**Comment by scheglov** [comment]
There must be some rouge context with embedder or something that causes using `EmbedderSdk` without summaries.

**Comment by bwilkerson** [comment]
This happens immediately after a restart of IntelliJ (and hence server) before I've done anything (other than having a couple of files opened automatically).

I was going to verify that none of the contexts were using an `EmbedderSdk`, but the status pages don't contain a complete list of contexts / drivers, so I can't use them for that. Then I opened Observatory and looked at the allocation profile. It doesn't list the class, which I take to mean that no instances of it have been created.

**Comment by devoncarew** [comment]
Fixed here: https://github.com/flutter/flutter/commit/41251d2450c69b7ed54c4895433593b8b8cbff05 (by building a strong mode summary file for the flutter version of the sdk).

**Comment by sethladd** [comment]
Thanks for the help!
