### ISSUE TITLE
service/dev_fs_spawn_test flaked on the optcounter threshold bot

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#28411]
https://build.chromium.org/p/client.dart/builders/vm-linux-release-ia32-optcounter-threshold-be/builds/3738/steps/vm%20tests/logs/stdio

```
FAILED: none-vm release_ia32 service/dev_fs_spawn_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseIA32/dart -DDART_SERVICE_USE_AUTH=false --error_on_bad_type --error_on_bad_override --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/.packages --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/dev_fs_spawn_test.dart
>testee>out> Observatory listening on http://127.0.0.1:36817/
** Signaled to run test queries on http://127.0.0.1:36817/
>testee>out> 
Loading VM...
Done loading VM
Running dev_fs_spawn_test.dart [1/2]
Running dev_fs_spawn_test.dart [2/2]
>testee>out> HELLO WORLD 1
Paused with PauseBreakpoint
>testee>out> HELLO WORLD 2
Paused with PauseBreakpoint
>testee>err> Dumping native stack trace for thread 1f96
>testee>err>   [0x085b8248] dart::Zone::CapacityInBytes() const
>testee>err>   [0x085b8248] dart::Zone::CapacityInBytes() const
>testee>err>   [0x085b87e2] dart::Zone::PrintJSON(dart::JSONStream*) const
>testee>err>   [0x084212ad] dart::JSONStream::PrintValue(dart::Zone*)
>testee>err>   [0x085a813c] dart::Thread::PrintJSON(dart::JSONStream*) const
>testee>err>   [0x0842126d] dart::JSONStream::PrintValue(dart::Thread*)
>testee>err>   [0x085ac85c] dart::ThreadRegistry::PrintJSON(dart::JSONStream*) const
>testee>err>   [0x0842122d] dart::JSONStream::PrintValue(dart::ThreadRegistry*)
>testee>err>   [0x084224b4] dart::JSONStream::PrintProperty(char const*, dart::ThreadRegistry*)
>testee>err>   [0x08400491] dart::Isolate::PrintJSON(dart::JSONStream*, bool)
>testee>err>   [0x0857417f] Unknown symbol
>testee>err>   [0x0857d66c] dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
>testee>err>   [0x0857db9d] dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
>testee>err>   [0x0840704d] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
>testee>err>   [0x084272c6] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
>testee>err>   [0x0842749c] dart::MessageHandler::HandleOOBMessages()
>testee>err>   [0x085a8661] dart::Thread::HandleInterrupts()
>testee>err>   [0x085e8f7c] dart::DRT_StackOverflow(dart::NativeArguments)
>testee>err>   [0xf7284387] Unknown symbol
>testee>err>   [0xf506d858] Unknown symbol
>testee>err>   [0xf506d342] Unknown symbol
>testee>err>   [0xf506ba74] Unknown symbol
>testee>err>   [0xf506b5d7] Unknown symbol
>testee>err>   [0xf506b273] Unknown symbol
>testee>err>   [0xf7284684] Unknown symbol
>testee>err>   [0x0830d8b8] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&)
>testee>err>   [0x0830e035] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
>testee>err>   [0x082b8488] Dart_Invoke
>testee>err>   [0x0816bf9c] dart::bin::DartUtils::SetWorkingDirectory()
>testee>err>   [0x0816c480] dart::bin::DartUtils::PrepareBuiltinLibrary(_Dart_Handle*, _Dart_Handle*, bool, bool)
>testee>err>   [0x0816c97b] dart::bin::DartUtils::PrepareForScriptLoading(bool, bool)
>testee>err>   [0x08152bdf] Unknown symbol
>testee>err>   [0x08152f5a] Unknown symbol
>testee>err>   [0x0865964f] Unknown symbol
>testee>err> -- End of DumpStackTrace


stderr:
Unhandled exception:
Testee exited with -6
#0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:249:11)
#1      _RootZone.runUnary (dart:async/zone.dart:1404)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --error_on_bad_type --error_on_bad_override --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/dev_fs_spawn_test.dart
Took 0:00:04.529435

Short reproduction command (experimental):
    python tools/test.py -mrelease -aia32 -t60 --vm-options --optimization-counter-threshold=5 service/dev_fs_spawn_test
```

**Comment by fsc8000** [comment]
Another occurrence today:

```
FAILED: none-vm release_ia32 service/dev_fs_spawn_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseIA32/dart -DDART_SERVICE_USE_AUTH=false --error_on_bad_type --error_on_bad_override --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/.packages --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/dev_fs_spawn_test.dart
>testee>out> Observatory listening on http://127.0.0.1:38552/
** Signaled to run test queries on http://127.0.0.1:38552/
>testee>out> 
Loading VM...
Done loading VM
Running dev_fs_spawn_test.dart [1/2]
>testee>err> Dumping native stack trace for thread 675f
>testee>err>   [0x085bb26f] dart::Zone::PrintJSON(dart::JSONStream*) const
>testee>err>   [0x085bb26f] dart::Zone::PrintJSON(dart::JSONStream*) const
>testee>err>   [0x085a8d0c] dart::Thread::PrintJSON(dart::JSONStream*) const
>testee>err>   [0x085ad54c] dart::ThreadRegistry::PrintJSON(dart::JSONStream*) const
>testee>err>   [0x08408877] dart::Isolate::PrintJSON(dart::JSONStream*, bool)
>testee>err>   [0x08574bb3] Unknown symbol
>testee>err>   [0x0857d70e] dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
>testee>err>   [0x0857db41] dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
>testee>err>   [0x0840e73f] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
>testee>err>   [0x0842eaff] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
>testee>err>   [0x0842ecca] dart::MessageHandler::HandleOOBMessages()
>testee>err>   [0x085a9731] dart::Thread::HandleInterrupts()
>testee>err>   [0x085edaa1] dart::DRT_StackOverflow(dart::NativeArguments)
>testee>err>   [0xf72ac387] Unknown symbol
>testee>err>   [0xf5ac1374] Unknown symbol
>testee>err>   [0xf5abf35a] Unknown symbol
>testee>err>   [0xf5abea3f] Unknown symbol
>testee>err>   [0xf72ac684] Unknown symbol
>testee>err>   [0x0831d8d0] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned int)
>testee>err>   [0x0831e67d] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
>testee>err>   [0x082c94c0] Dart_Invoke
>testee>err>   [0x0816af26] dart::bin::DartUtils::ResolveScript(_Dart_Handle*)
>testee>err>   [0x08152825] Unknown symbol
>testee>err>   [0x08152af0] Unknown symbol
>testee>err>   [0x08657562] Unknown symbol
>testee>err> -- End of DumpStackTrace


stderr:
Unhandled exception:
Testee exited with -6
#0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:249:11)
#1      _RootZone.runUnary (dart:async/zone.dart:1404)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --error_on_bad_type --error_on_bad_override --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/dev_fs_spawn_test.dart
Took 0:00:03.428775

Short reproduction command (experimental):
    python tools/test.py -mrelease -aia32 -t60 --vm-options --optimization-counter-threshold=5 service/dev_fs_spawn_test
```

**Comment by jensjoha** [comment]
And again
```
FAILED: none-vm release_ia32 service/dev_fs_spawn_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseIA32/dart -DDART_SERVICE_USE_AUTH=false --error_on_bad_type --error_on_bad_override --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/.packages --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/dev_fs_spawn_test.dart
>testee>out> Observatory listening on http://127.0.0.1:49303/
** Signaled to run test queries on http://127.0.0.1:49303/
>testee>out> 
Loading VM...
Done loading VM
Running dev_fs_spawn_test.dart [1/2]
Running dev_fs_spawn_test.dart [2/2]
>testee>out> HELLO WORLD 1
Paused with PauseBreakpoint
>testee>out> HELLO WORLD 2
Paused with PauseBreakpoint
>testee>err> Dumping native stack trace for thread 40ca
>testee>err>   [0x085c5b08] dart::Zone::PrintJSON(dart::JSONStream*) const
>testee>err>   [0x085c5b08] dart::Zone::PrintJSON(dart::JSONStream*) const
>testee>err>   [0x085b2f0c] dart::Thread::PrintJSON(dart::JSONStream*) const
>testee>err>   [0x085b781c] dart::ThreadRegistry::PrintJSON(dart::JSONStream*) const
>testee>err>   [0x0840ccd7] dart::Isolate::PrintJSON(dart::JSONStream*, bool)
>testee>err>   [0x0857e553] Unknown symbol
>testee>err>   [0x0858702e] dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
>testee>err>   [0x08587451] dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
>testee>err>   [0x0841263f] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
>testee>err>   [0x0843413f] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
>testee>err>   [0x0843430a] dart::MessageHandler::HandleOOBMessages()
>testee>err>   [0x085b3991] dart::Thread::HandleInterrupts()
>testee>err>   [0x085fc77e] dart::DRT_StackOverflow(dart::NativeArguments)
>testee>err>   [0xf72bf387] [Stub] CallToRuntime
>testee>err>   [0xf40c3082] _HashMap.[]=
>testee>err>   [0xf40c2178] _RawReceivePortImpl.handler=
>testee>err>   [0xf40c1f1a] _startIsolate
>testee>err>   [0xf72bf684] [Stub] InvokeDartCode
>testee>err>   [0x083214d0] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned int)
>testee>err>   [0x0832227d] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
>testee>err>   [0x08413399] Unknown symbol
>testee>err>   [0x084345db] dart::MessageHandler::TaskCallback()
>testee>err> -- End of DumpStackTrace
** Killing script
Unexpected exception in service tests: NetworkRpcException(Canceling request: WebSocket closed(id: 39 method: getIsolate params: {isolateId: isolates/586996534}))
null


stderr:
Unhandled exception:
NetworkRpcException(Canceling request: WebSocket closed(id: 39 method: getIsolate params: {isolateId: isolates/586996534}))
#0      _ServiceTesterRunner.run.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:339:9)
<asynchronous suspension>
#1      _rootRunBinary (dart:async/zone.dart:1174)
#2      _RootZone.runBinary (dart:async/zone.dart:1411)
#3      runZoned.<anonymous closure> (dart:async/zone.dart:1478)
#4      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:552)
#6      _Future._completeError (dart:async/future_impl.dart:485)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#8      _rootRun (dart:async/zone.dart:1150)
#9      _CustomZone.run (dart:async/zone.dart:1026)
#10     _CustomZone.runGuarded (dart:async/zone.dart:924)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --error_on_bad_type --error_on_bad_override --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/runtime/observatory/tests/service/dev_fs_spawn_test.dart
Took 0:00:05.103235

Short reproduction command (experimental):
    python tools/test.py -mrelease -aia32 -t60 --vm-options --optimization-counter-threshold=5 service/dev_fs_spawn_test
```
