### ISSUE TITLE
`gclient runhooks` fails on armhf, arm64, mipsel

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#28429]
It's been a few months since I've tried this, so I don't have a particular change to point at.

mipsel:
```
________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook --arch i386' in '/home/rmacnak/dart1'
Installing Debian Wheezy i386 root image: /home/rmacnak/dart1/sdk/build/linux/debian_wheezy_i386-sysroot
Downloading http://storage.googleapis.com/chrome-linux-sysroot/toolchain/a2d45701cb21244b9514e420950ba6ba687fb655/debian_wheezy_i386_sysroot.tgz
Traceback (most recent call last):
  File "sdk/build/linux/sysroot_scripts/install-sysroot.py", line 181, in <module>
    sys.exit(main())
  File "sdk/build/linux/sysroot_scripts/install-sysroot.py", line 157, in main
    subprocess.check_call(['curl', '--fail', '-L', url, '-o', tarball])
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Error: Command '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook --arch i386' returned non-zero exit status 1 in /home/rmacnak/dart1
```

armhf:
```
________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook --arch i386' in '/home/rmacnak/dart1'
Installing Debian Wheezy i386 root image: /home/rmacnak/dart1/sdk/build/linux/debian_wheezy_i386-sysroot
Downloading http://storage.googleapis.com/chrome-linux-sysroot/toolchain/a2d45701cb21244b9514e420950ba6ba687fb655/debian_wheezy_i386_sysroot.tgz
Traceback (most recent call last):
  File "sdk/build/linux/sysroot_scripts/install-sysroot.py", line 181, in <module>
    sys.exit(main())
  File "sdk/build/linux/sysroot_scripts/install-sysroot.py", line 157, in main
    subprocess.check_call(['curl', '--fail', '-L', url, '-o', tarball])
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Error: Command '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook --arch i386' returned non-zero exit status 1 in /home/rmacnak/dart1
```

arm64:
```
Traceback (most recent call last):
  File "/home/rmacnak/dart1/sdk/tools/gn.py", line 425, in <module>
    sys.exit(main(sys.argv))
  File "/home/rmacnak/dart1/sdk/tools/gn.py", line 412, in main
    results = pool.map(run_command, commands, chunksize=1)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
OSError: [Errno 8] Exec format error
Error: Command '/usr/bin/python sdk/tools/generate_buildfiles.py' returned non-zero exit status 1 in /home/rmacnak/dart1
```

@zanderso @whesse

**Comment by zanderso** [comment]
With GN, we won't be able to support building on non-intel hosts without some difficulty. We should make sure that cross-builds are well supported, though.

I'm not sure why mips and arm are failing on the wheezy sysroot script, but even if they got past that point, they would fail the same way that arm64 is failing. In particular, we pull GN binaries from google storage that are vended by chrome infrastructure, and they only provide builds for intel architectures. If we wanted to support GN builds on non-intel hosts, we'd have to cross-build and vend our own binaries.

gyp will eventually be deprecated, but in the meantime, setting DART_USE_GYP should still work for builds on non-intel hosts.

**Comment by Hixie** [comment]
FWIW, this is a blocker for self-hosted development with Dart on a raspberry pi. Having to cross-compile a tool chain is a much higher barrier to entry than just downloading the code and running it. In every other respect, developing straight on a pi is fine.

**Comment by zanderso** [comment]
@Hixie Yah, it's a blocker. I'm hoping that since we've switched to Fuchsia's buildtools, it'll be more likely that we'll eventually get good self-hosting support on ARM, though ARMv6 Raspberry Pi might still be difficult.
