### ISSUE TITLE
Analysis Server crashes when directory was removed very quickly

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/sdk#28427]
Analyzer Feedback from IntelliJ

This happened when I was running CMake and it made a directory very quickly then removed it. This is probably something that should be caught and simply warned.

## Version information

- `IDEA 171.2272.14`
- `1.21.1`
- `IU-171.2272.14, JRE 1.8.0_112-release-b676x64 JetBrains s.r.o, OS Linux(amd64) v4.9.3-200.fc25.x86_64 unknown, screens 3840x2160`

## Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.21.1, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1484691401596, params: {included: [/home/alex/Code/Legion], excluded: [/home/alex/Code/Legion/.idea, /home/alex/Code/Legion/.pub, /home/alex/Code/Legion/build]}, method: analysis.setAnalysisRoots, id: 3}
FileSystemException: Failed to watch path, path = '/home/alex/Code/Legion/examples/cmake/legion/linux-x86/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_b829e.dir' (OS Error: No such file or directory, errno = 2)
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:1109)
#1      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:876)
#2      _rootRunBinary (dart:async/zone.dart:1174)
#3      _CustomZone.runBinary (dart:async/zone.dart:1049)
#4      runZoned.<anonymous closure> (dart:async/zone.dart:1478)
#5      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005)
#6      _nullErrorHandler (dart:async/stream_impl.dart:570)
#7      _rootRunBinary (dart:async/zone.dart:1170)
#8      _CustomZone.runBinary (dart:async/zone.dart:1049)
#9      _CustomZone.runBinaryGuarded (dart:async/zone.dart:941)
#10     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:350)
#11     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:368)
#12     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:267)
#13     _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:401)
#14     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:335)
#15     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:400)
#16     _BroadcastStreamController.addError (dart:async/broadcast_stream_controller.dart:272)
#17     _rootRunBinary (dart:async/zone.dart:1170)
#18     _CustomZone.runBinary (dart:async/zone.dart:1049)
#19     _CustomZone.runBinaryGuarded (dart:async/zone.dart:941)
#20     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:350)
#21     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:368)
#22     _DelayedError.perform (dart:async/stream_impl.dart:601)
#23     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:666)
#25     _rootRun (dart:async/zone.dart:1146)
#26     _CustomZone.run (dart:async/zone.dart:1026)
#27     _CustomZone.runGuarded (dart:async/zone.dart:924)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#29     _rootRun (dart:async/zone.dart:1150)
#30     _CustomZone.run (dart:async/zone.dart:1026)
#31     _CustomZone.runGuarded (dart:async/zone.dart:924)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#35     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#36     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
