### ISSUE TITLE
[Kernel] async stacktrace not correct

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#28446]
E.g. the following code
```dart
void main() {
  var x = () async {
    print("Hello #1!");
    await runAsync();
    print("Hello # 2!");
  };
  x();
}

runAsync() async {
  throw 'oh no!';
}
```

produces 
```
Hello #1!
Unhandled exception:
oh no!
#0      runAsync.<runAsync_async_body> (file:///usr/local/google/home/jensj/code/testdata/src/stacktrace_tests.dart:11:3)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#2      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#3      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#4      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```
when run from source, but
```
Hello #1!
Unhandled exception:
oh no!
#0      main.<anonymous closure>.async_op (file:///usr/local/google/home/jensj/code/testdata/src/stacktrace_tests.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async:134:33)
#2      _RootZone.runBinary (dart:async/zone.dart:1410:54)
#3      _FutureListener.handleError (dart:async/future_impl.dart:146:20)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649:47)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:671:13)
#6      _Future._completeError (dart:async/future_impl.dart:485:5)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:56:12)
#8      _Completer.completeError (dart:async/future_impl.dart:27:5)
#9      runAsync.async_op (file:///usr/local/google/home/jensj/code/testdata/src/stacktrace_tests.dart)
#10     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184:26)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:5)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate:1057:5)
#14     _RawReceivePortImpl._handleMessage (dart:isolate:1107:5)
```
when run from kernel.
I will add a test that demonstrates this as well. Update: https://codereview.chromium.org/2638403004/

I think @kmillikin  volunteered @mkustermann

**Comment by mkustermann** [comment]
Fixed by c5c7f45be0811a5fe0bca730fdd0b05ed68af619
