### ISSUE TITLE
Was optimising imports.

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#28449]
[report.txt](https://github.com/dart-lang/sdk/files/718018/report.txt)
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.2272.15`
- `1.22.0-dev.9.0`
- `WS-171.2272.15, JRE 1.8.0_112-release-b676x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.2 unknown, screens 2560x1440, 1200x1920`

## Exception

Please append the contents of:
file:///private/var/folders/2j/ls4q_sd155q7lkksb0jbg6500000gn/T/report.txt

```
Dart analysis server, SDK version 1.22.0-dev.9.0, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1484867547371, params: {file: /Users/rayk/WebstormProjects/da2lab/lib/hero_detail_component.dart}, method: edit.organizeDirectives, id: 4327}
AnalysisException: Cannot compute DART_ERRORS for /Users/rayk/WebstormProjects/da2lab/lib/hero_detail_component.dart
Caused by Unexpected exception while performing GatherUsedLocalElementsTask for source /Users/rayk/WebstormProjects/da2lab/lib/hero_detail_component.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1187)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1185)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find dynamic id in [null _id, null id]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3162)
#1      LocalVariableElementImpl.identifier (package:analyzer/src/dart/element/element.dart:6076)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3202)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2920)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2809)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10528)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3522)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5346)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7760)
#11     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1019)
#12     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7755)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
