### ISSUE TITLE
add source-map entry for all generated methods

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#28442]
We still have holes in the source map data.

We know that this is true for one-shot interceptors, and likely for other pieces of code.

This is triggering issues with tools that search backwards for the first function entry above the error that contain a mapping. The tools are not clever about scoping rules and often associate the wrong location if these entries are missing, so before we generate the best data for each missing code, we should consider generating a placeholder empty entry (an indication that the mapping is not recorded), so that tools stop searching backwards.

@johnniwinther suggested that we include an entry for practically every js_template.

Below a simple repro example.

Input:
```dart
class MyType {
  get length => 3; // ensures we build an interceptor for `.length`
}

main() {
  confuse('').trim(); // includes some code above the interceptors
  confuse([]).length;
  confuse(new MyType()).length;
  confuse(null).length; // called through the interceptor
}

confuse(x) {
  return x;
  return x;
}
```

Running the output of this code in d8 produces:
```
sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: TypeError: Cannot read property 'get$length' of null
          throw e;
          ^
TypeError: Cannot read property 'get$length' of null
    at Object.J.get$length$as (out.js:430:43)
    at O.main (out.js:583:9)
    at action (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at out.js:856:23
    at init.currentScript (out.js:842:7)
    at out.js:853:5
    at out.js:860:3
```

Using a naive source-map lookup that searches for the first enclosing function with an entry yields these top 2 frames:
```
JSString._skipTrailingWhitespacejs_string.dart 264:3
main                b.dart 13:3 
```

The problem is that `_skipTrailingWhitespacejs` is defined above the interceptor and gets selected for the mapping. In particular, this is what the `J` container (where these definitions live) looks like:
```js
  }, J = {
    getInterceptor: function(receiver) {
     ...
    },
    JSString__isWhitespace: function(codeUnit) {
     ...
    },
    JSString__skipLeadingWhitespace: function(string, index) {
     ...
    },
    JSString__skipTrailingWhitespace: function(string, index) {
     ...
    },
    getInterceptor$as: function(receiver) {
      ...
    },
    getInterceptor$s: function(receiver) {
      ...
    },
    get$length$as: function(receiver) {
      return J.getInterceptor$as(receiver).get$length(receiver);
    },
   ...
```

**Comment by vsmenon** [comment]
Is this obsolete?  Downgrading from p1 regardless.

**Comment by johnniwinther** [comment]
The immediate problem is fixed, namely that the generated method get attributed to the last method with source mapping. We now have a 'stop marker' that shows that these generated method have no source mapping.

I do think that we should provide some kind of mapping for these, so the problem is not obsolete but of a lesser priority.
