### ISSUE TITLE
just switched between tabs in IDEA

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#28475]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.2455.10`
- `1.22.0-edge.8cf71084dc4f6710afc4bf2af47f659759942245`
- `IU-171.2455.10, JRE 1.8.0_112-release-b692x64 JetBrains s.r.o, OS Linux(amd64) v4.8.0-2-amd64 unknown, screens 3840x2160`

## Exception

Please append the contents of:
file:///tmp/report1.txt

```
Dart analysis server, SDK version 1.22.0-edge.8cf71084dc4f6710afc4bf2af47f659759942245, server version 1.17.0, error: Exception from navigation contributor: AngularNavigationContributor
NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AngularNavigationContributor._addTemplateRegions (package:angular_analyzer_server_plugin/src/analysis.dart:118)
#3      AngularNavigationContributor.computeNavigation (package:angular_analyzer_server_plugin/src/analysis.dart:78)
#4      computeNavigation (package:analysis_server/src/domains/analysis/navigation.dart:28)
#5      sendAnalysisNotificationNavigation.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:210)
#6      _sendNotification.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:281)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#8      _sendNotification (package:analysis_server/src/operation/operation_analysis.dart:279)
#9      sendAnalysisNotificationNavigation (package:analysis_server/src/operation/operation_analysis.dart:208)
#10     AnalysisServer.setAnalysisSubscriptions.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1268)
#11     _HashMap.forEach (dart:collection-patch/collection_patch.dart:151)
#12     AnalysisServer.setAnalysisSubscriptions (package:analysis_server/src/analysis_server.dart:1245)
#13     AnalysisDomainHandler.setSubscriptions (package:analysis_server/src/domain_analysis.dart:334)
#14     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:247)
#15     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:876)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#17     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:872)
#18     _rootRun (dart:async/zone.dart:1150)
#19     _CustomZone.run (dart:async/zone.dart:1026)
#20     _CustomZone.runGuarded (dart:async/zone.dart:924)
#21     runZoned (dart:async/zone.dart:1501)
#22     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:871)
#23     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)
#24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#25     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161)
#26     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
#27     _rootRunUnary (dart:async/zone.dart:1158)
#28     _CustomZone.runUnary (dart:async/zone.dart:1037)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#35     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:159)

**Comment by bwilkerson** [comment]
@MichaelRFairhurst Feel free to move this to a different repo if there's a better place for Angular issues.

**Comment by MichaelRFairhurst** [comment]
Moved to analyzer. Thanks Gunter for filing and Brian for forwarding
