### ISSUE TITLE
Analyzer exception: Bad state: Unknown expression type: super

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#28491]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.SNAPSHOT`
- `1.22.0-dev.9.0`
- `171.SNAPSHOT, JRE 1.8.0_112-b15x64 Oracle Corporation, OS Windows 10(amd64) v10.0 , screens 1920x1200`

## Exception

```
Dart analysis server, SDK version 1.22.0-dev.9.0, server version 1.17.0, error: Captured exception
Bad state: Unknown expression type: super
#0      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:402)
#1      AbstractConstExprSerializer._serializeArguments.<anonymous closure> (package:analyzer/src/summary/summarize_const_expr.dart:413)
#2      Object&ListMixin.forEach (dart:collection/list.dart:63)
#3      AbstractConstExprSerializer._serializeArguments (package:analyzer/src/summary/summarize_const_expr.dart:410)
#4      AbstractConstExprSerializer.serializeInstanceCreation (package:analyzer/src/summary/summarize_const_expr.dart:172)
#5      _ConstExprSerializer.serializeAnnotation (package:analyzer/src/summary/summarize_ast.dart:69)
#6      _SummarizeAstVisitor.serializeAnnotations.<anonymous closure> (package:analyzer/src/summary/summarize_ast.dart:421)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:412)
#8      ListIterable.toList (dart:_internal/iterable.dart:219)
#9      _SummarizeAstVisitor.serializeAnnotations (package:analyzer/src/summary/summarize_ast.dart:423)
#10     _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:479)
#11     _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1032)
#12     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)
#14     _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:524)
#15     serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22)
#16     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:390)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1491)
#18     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:389)
#19     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:620)
#20     _TopLevelNameDeclarationsTask.perform.<perform_async_body> (package:analyzer/src/dart/analysis/driver.dart:1675)
#21     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#22     _rootRun (dart:async/zone.dart:1146)
#23     _CustomZone.run (dart:async/zone.dart:1026)
#24     _CustomZone.runGuarded (dart:async/zone.dart:924)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#26     _rootRun (dart:async/zone.dart:1150)
#27     _CustomZone.run (dart:async/zone.dart:1026)
#28     _CustomZone.runGuarded (dart:async/zone.dart:924)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by scheglov** [comment]
https://codereview.chromium.org/2661803002

**Comment by scheglov** [comment]
70dd81dd372b15a29a2fa9f54691c45e83530288
