### ISSUE TITLE
Analyzer fails when analyzing flutter repo in checked mode

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#28519]
```
+flutter analyze --flutter-repo
Analyzing 911 files...
Task failed: VerifyUnitTask for source /home/travis/build/flutter/flutter/dev/automated_tests/flutter_test/test_async_utils_guarded_test.dart
AnalysisException: Cannot compute DART_ERRORS for /home/travis/build/flutter/flutter/dev/automated_tests/flutter_test/test_async_utils_guarded_test.dart
Caused by Unexpected exception while performing VerifyUnitTask for source /home/travis/build/flutter/flutter/dev/automated_tests/flutter_test/test_async_utils_guarded_test.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723)
#5      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:665)
#6      AnalysisDriver._analyze (package:flutter_tools/src/dart/analysis.dart:88)
#7      AnalysisDriver.analyze (package:flutter_tools/src/dart/analysis.dart:52)
#8      AnalyzeOnce.analyze.<analyze_async_body> (package:flutter_tools/src/commands/analyze_once.dart:155)
#9      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#10     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#11     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
#12     _rootRun (dart:async/zone.dart:1146)
#13     _CustomZone.run (dart:async/zone.dart:1026)
#14     _CustomZone.runGuarded (dart:async/zone.dart:924)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#16     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#17     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
#18     _rootRun (dart:async/zone.dart:1150)
#19     _CustomZone.run (dart:async/zone.dart:1026)
#20     _CustomZone.runGuarded (dart:async/zone.dart:924)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
Caused by 'package:analyzer/src/dart/element/type.dart': Failed assertion: line 977: 'g.typeFormals.isNotEmpty && f.typeFormals.isEmpty': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:33)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:29)
#2      FunctionTypeImpl.recoverTypeArguments (package:analyzer/src/dart/element/type.dart:977)
#3      ErrorVerifier._checkForImplicitDynamicInvoke (package:analyzer/src/generated/error_verifier.dart:3968)
#4      ErrorVerifier.visitMethodInvocation (package:analyzer/src/generated/error_verifier.dart:1035)
#5      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7648)
#6      ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9130)
#7      RecursiveAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:1098)
#8      ErrorVerifier.visitReturnStatement (package:analyzer/src/generated/error_verifier.dart:1123)
#9      ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:9126)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)
#11     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#12     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:647)
#13     ErrorVerifier.visitBlock (package:analyzer/src/generated/error_verifier.dart:397)
#14     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#15     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#16     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:653)
#17     ErrorVerifier.visitBlockFunctionBody (package:analyzer/src/generated/error_verifier.dart:416)
#18     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#19     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5352)
#20     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:869)
#21     ErrorVerifier.visitFunctionExpression (package:analyzer/src/generated/error_verifier.dart:809)
#22     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5346)
#23     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5196)
#24     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:857)
#25     ErrorVerifier.visitFunctionDeclaration (package:analyzer/src/generated/error_verifier.dart:790)
#26     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5189)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)
#28     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#29     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#30     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:565)
#31     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#32     VerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:6300)
#33     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#34     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#35     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#36     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#37     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723)
#38     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:665)
#39     AnalysisDriver._analyze (package:flutter_tools/src/dart/analysis.dart:88)
#40     AnalysisDriver.analyze (package:flutter_tools/src/dart/analysis.dart:52)
#41     AnalyzeOnce.analyze.<analyze_async_body> (package:flutter_tools/src/commands/analyze_once.dart:155)
#42     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#43     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#44     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
#45     _rootRun (dart:async/zone.dart:1146)
#46     _CustomZone.run (dart:async/zone.dart:1026)
#47     _CustomZone.runGuarded (dart:async/zone.dart:924)
#48     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#49     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#50     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
#51     _rootRun (dart:async/zone.dart:1150)
#52     _CustomZone.run (dart:async/zone.dart:1026)
#53     _CustomZone.runGuarded (dart:async/zone.dart:924)
#54     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#55     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#56     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#57     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
package:analyzer/src/context/context.dart 728                     AnalysisContextImpl.computeResult
package:analyzer/src/context/context.dart 665                     AnalysisContextImpl.computeErrors
package:flutter_tools/src/dart/analysis.dart 88                   AnalysisDriver._analyze
package:flutter_tools/src/dart/analysis.dart 52                   AnalysisDriver.analyze
package:flutter_tools/src/commands/analyze_once.dart 155          AnalyzeOnce.analyze.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/commands/analyze_once.dart 201          AnalyzeOnce.analyze.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/analyze_once.dart              AnalyzeOnce.analyze
package:flutter_tools/src/commands/analyze.dart 60                AnalyzeCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 188                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119         FlutterCommand.run
package:args/command_runner.dart 194                              CommandRunner.runCommand.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:args/command_runner.dart                                  CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 212  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 73                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 109                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 150  FlutterCommandRunner.run
package:flutter_tools/executable.dart 124                         main.<async>.<fn>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 123                         main.<async>.<fn>
package:flutter_tools/src/base/context.dart 76                    AppContext._run.<async>
+detect_error_on_exit
+exit_code=1
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Error: script exited early due to error (1)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by scheglov** [comment]
Cannot reproduce, by opening `flutter/dev/automated_tests/` using Dart Analysis Server in checked mode.

**Comment by Hixie** [comment]
Can you reproduce it by running `flutter analyze --flutter-repo` in checked mode?

**Comment by scheglov** [comment]
No, I cannot.
`/Users/scheglov/Source/flutter/bin/cache/dart-sdk/bin/dart --checked /Users/scheglov/Source/flutter/bin/cache/flutter_tools.snapshot analyze --flutter-repo` runs fine without exceptions or analyzer warnings.

**Comment by Hixie** [comment]
Oh, you have to recompile the snapshot with --checked to enable checked mode, I think.

Try just uncommenting out the FLUTTER_TOOL_ARGS line in bin/flutter and then running `flutter analyze --flutter-repo`. I just tried it tip of tree and had the crash.

**Comment by scheglov** [comment]
OK, I can reproduce it. Thanks.

**Comment by scheglov** [comment]
@jmesserly Could take a look?
I reduced the problem to a reproducible test case in `CheckedTest`.

```Dart
  solo_test_issue28519() async {
    addFile(r'''
class C {
  static void test(int body()) {}
}

main() {
  C.test(()  {
    return 42;
  });
}
''');
    check(implicitDynamic: false);
  }
```

**Comment by jmesserly** [comment]
FYI, this is simply an assertion failure--you can workaround it in the meantime by running Analyzer in unchecked mode. I've sent out a CL to fix: https://codereview.chromium.org/2664643002

**Comment by Hixie** [comment]
yup, we've been using unchecked mode this whole time. 🙂 we're looking to switching to checked mode for unrelated reasons.
