### ISSUE TITLE
Flaky crash of vm/cc/ExternalStringStaticFieldDeoptimize test

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#28524]
This is an example of different flaky crashes that started appearing recently. Not sure exactly when:

```
FAILED: none-vm release_x64 vm/cc/ExternalStringStaticFieldDeoptimize
Expected: Pass 
Actual: Crash
CommandOutput[run_vm_unittest]:

Command[run_vm_unittest]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/run_vm_tests --ignore-unrecognized-flags ExternalStringStaticFieldDeoptimize
Took 0:00:00.023867

Short reproduction command (experimental):
    python tools/test.py -mrelease -t60 --vm-options --optimization-counter-threshold=5 vm/cc/ExternalStringStaticFieldDeoptimize
```

**Comment by fsc8000** [comment]
Another instance:
```
FAILED: none-vm product_x64 vm/cc/ExternalStringGuardFieldDeoptimize
Expected: Pass 
Actual: Crash
CommandOutput[run_vm_unittest]:

Command[run_vm_unittest]: DART_CONFIGURATION=ProductX64 xcodebuild/ProductX64/run_vm_tests --ignore-unrecognized-flags ExternalStringGuardFieldDeoptimize
Took 0:00:00.020384

Short reproduction command (experimental):
    python tools/test.py -mproduct -t60 --builder-tag no_ipv6 vm/cc/ExternalStringGuardFieldDeoptimize
```

**Comment by jensjoha** [comment]
And again:

```
FAILED: none-vm product_x64 vm/cc/ExternalStringGuardFieldDeoptimize
Expected: Pass 
Actual: Crash
CommandOutput[run_vm_unittest]:

Command[run_vm_unittest]: DART_CONFIGURATION=ProductX64 xcodebuild/ProductX64/run_vm_tests --ignore-unrecognized-flags ExternalStringGuardFieldDeoptimize
Took 0:00:00.019579

Short reproduction command (experimental):
    python tools/test.py -mproduct -t60 --builder-tag no_ipv6 vm/cc/ExternalStringGuardFieldDeoptimize
```

(twice in a row)

**Comment by mraleph** [comment]
Currently we don't archive dumps from these bots. I will update recipes to include vm-linux-product-x64-be and vm-linux-release-x64-be into crash dump archiving trial.

**Comment by mraleph** [comment]
I have recipe change, but we need to change `core_pattern` for this to work. Waiting for chrome infra action (see #28439 and cinfra ticket linked from there)

**Comment by mraleph** [comment]
Crash dump collection is enabled on all Linux bots. Links to crash dump will be at the end of test log.

**Comment by mraleph** [comment]
We've got a dump - looking into it.

**Comment by mraleph** [comment]
This is caused by 259c7ac2be54ee3e20f5a6c6f3df7d910f01f594 which I think needs to be reverted.

Stack trace from the core dump:
```
#0  next_block (this=<optimized out>) at ../../runtime/vm/handles.h:193
#1  IsValidScopedHandle (this=<optimized out>, handle=<optimized out>) at ../../runtime/vm/handles_impl.h:189
#2  IsValidScopedHandle (this=<optimized out>, object=<optimized out>) at ../../runtime/vm/thread.cc:816
#3  dart::Thread::IsValidHandle (this=<optimized out>, object=0x60a2428) at ../../runtime/vm/thread.cc:762
#4  0x0000000000b84abb in dart::ThreadRegistry::IsValidHandle (this=<optimized out>, handle=<optimized out>) at ../../runtime/vm/thread_registry.cc:112
#5  0x000000000082d6df in dart::Api::IsValid (handle=0x60a2428) at ../../runtime/vm/dart_api_impl.cc:543
#6  0x00000000005fd350 in dart::A_change_str_native (args=<optimized out>) at ../../runtime/vm/dart_api_impl_test.cc:8784
#7  0x00000000009e3137 in dart::NativeEntry::NativeCallWrapperNoStackCheck (args=0x7ffcf9b97780, func=0x5fd240 <dart::A_change_str_native(_Dart_NativeArguments*)>) at ../../runtime/vm/native_entry.cc:163
```

When I look at the code added in 259c7ac2be54ee3e20f5a6c6f3df7d910f01f594, I can see that `ThreadRegistry::IsValidHandle` calls into `Thread::IsValidHandle` which can attempt to iterate all zones / api scopes within a thread and ask them about handles. However there is no locking in place to prevent races, so zones can go away as we are trying to look at them if thread we are looking at is not a current thread (which can easily happen because we usually have a background compiler thread up and running).

**Comment by bkonyi** [comment]
[2a20b04](https://github.com/dart-lang/sdk/commit/2a20b0433d64ee3dec7ed69b1fb57d2b148910c8) should fix this issue.
