### ISSUE TITLE
Task failed: GatherUsedLocalElementsTask

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#28538]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.SNAPSHOT`
- `1.22.0-dev.9.1`
- `171.SNAPSHOT, JRE 1.8.0_112-b15x64 Oracle Corporation, OS Windows 10(amd64) v10.0 , screens 1920x1200`

## Exception

```
Dart analysis server, SDK version 1.22.0-dev.9.1, server version 1.17.0, error: Task failed: GatherUsedLocalElementsTask for source C:\dart_projects\dart-lang\sdk\pkg\analyzer\lib\src\dart\analysis\driver.dart
Unexpected exception while performing GatherUsedLocalElementsTask for source C:\dart_projects\dart-lang\sdk\pkg\analyzer\lib\src\dart\analysis\driver.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1187)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1185)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find () → List<Completer<AnalysisDriverUnitIndex>> in [() → dynamic]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3162)
#1      FunctionElementImpl.identifier (package:analyzer/src/dart/element/element.dart:4402)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3202)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2920)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2809)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10528)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3522)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5346)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:605)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#14     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7655)
#15     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1013)
#16     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7648)
#17     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7652)
#18     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1013)
#19     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7648)
#20     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4260)
#21     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:815)
#22     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4256)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)
#24     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#25     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:647)
#26     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#27     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#28     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:653)
#29     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#30     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7535)
#31     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1007)
#32     GatherUsedLocalElementsVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:3532)
#33     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7526)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)
#35     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#36     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:683)
#37     GatherUsedLocalElementsVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3502)
#38     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#39     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)
#40     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#41     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#42     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#43     GatherUsedLocalElementsTask.internalPerform (package:analyzer/src/task/dart.dart:3105)
#44     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#45     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#46     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#47     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#48     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1187)
#49     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#50     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1185)
#51     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#52     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#53     Future.Future.<anonymous closure> (dart:async/future.dart:158)
#54     _rootRun (dart:async/zone.dart:1146)
#55     _CustomZone.run (dart:async/zone.dart:1026)
#56     _CustomZone.runGuarded (dart:async/zone.dart:924)
#57     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#58     _rootRun (dart:async/zone.dart:1150)
#59     _CustomZone.run (dart:async/zone.dart:1026)
#60     _CustomZone.runGuarded (dart:async/zone.dart:924)
#61     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#62     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#63     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#64     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```

```
1485537734670 <= {"event":"server.error","params":{"isFatal":false,"message":"Task failed: GatherUsedLocalElementsTask for source C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\anal
1485537734649 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\search.dart","errors":[]}}
1485537734635 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\search.dart","errors":[]}}
1485537734616 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","errors":[{"severity":"ERROR","type":"STATIC_WARN
1485537734616 <= {"event":"analysis.overrides","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","overrides":[]}}
1485537734613 <= {"event":"analysis.navigation","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","regions":[{"offset":224,"length":12,"targets
1485537734602 <= {"event":"analysis.highlights","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","regions":[{"type":"DIRECTIVE","offset":217,"
1485537734591 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","errors":[]}}
1485537734591 <= {"id":"75","result":{"fixes":[{"error":{"severity":"WARNING","type":"STATIC_WARNING","location":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\dr
1485537734524 => {"id":"75","method":"edit.getFixes","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","offset":51933},"clientRequestTime":1485
1485537734519 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1485537734519 <= {"id":"74","result":{"assists":[]}}
1485537734518 => {"id":"74","method":"edit.getAssists","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","offset":51933,"length":0},"clientRequ
1485537734517 <= {"id":"73","result":{"fixes":[]}}
1485537734516 <= {"id":"72","result":{}}
1485537734461 => {"id":"73","method":"edit.getFixes","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","offset":51932},"clientRequestTime":1485
1485537734440 => {"id":"72","method":"analysis.updateContent","params":{"files":{"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart":{"type":"add","content":"// C
1485537733964 <= {"id":"71","result":{"assists":[{"message":"Remove type annotation","edits":[{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","fileSta
1485537733958 => {"id":"71","method":"edit.getAssists","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","offset":53556,"length":0},"clientRequ
1485537731705 <= {"id":"70","result":{"assists":[{"message":"Remove type annotation","edits":[{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","fileSta
1485537731699 => {"id":"70","method":"edit.getAssists","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","offset":53562,"length":0},"clientRequ
1485537729965 <= {"id":"69","result":{"assists":[{"message":"Remove type annotation","edits":[{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","fileSta
1485537729961 => {"id":"69","method":"edit.getAssists","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","offset":53561,"length":0},"clientRequ
1485537727712 <= {"id":"68","result":{"assists":[{"message":"Remove type annotation","edits":[{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","fileSta
1485537727705 => {"id":"68","method":"edit.getAssists","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","offset":53560,"length":0},"clientRequ
1485537723552 <= {"event":"analysis.implemented","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\lib\\src\\dart\\analysis\\driver.dart","classes":[],"members":[]}}
1485537723548 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1485537723547 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\test\\src\\dart\\analysis\\file_state_test.dart","errors":[]}}
1485537723540 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\pkg\\analyzer\\test\\src\\dart\\analysis\\file_state_test.dart","errors":[]}}
```

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
