### ISSUE TITLE
DFE doesn't work on Windows

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#28532]
```
E:/b/depot_tools/python276_bin/python.exe ../../build/gn_run_binary.py compiled_action dart.exe --packages=E:/b/build/slave/vm-win-release-x64-be/build/sdk/.packages --snapshot=E:/b/build/slave/vm-win-release-x64-be/build/sdk/out/ReleaseX64/gen/kernel-service.dart.snapshot --snapshot-kind=app-jit E:/b/build/slave/vm-win-release-x64-be/build/sdk/utils/kernel-service/kernel-service.dart file://E:/b/build/slave/vm-win-release-x64-be/build/sdk/pkg/compiler/lib/src/dart2js.dart
Command failed: ./dart.exe --packages=E:/b/build/slave/vm-win-release-x64-be/build/sdk/.packages --snapshot=E:/b/build/slave/vm-win-release-x64-be/build/sdk/out/ReleaseX64/gen/kernel-service.dart.snapshot --snapshot-kind=app-jit E:/b/build/slave/vm-win-release-x64-be/build/sdk/utils/kernel-service/kernel-service.dart file://E:/b/build/slave/vm-win-release-x64-be/build/sdk/pkg/compiler/lib/src/dart2js.dart
output: Unhandled exception:

FileSystemException: Exists failed, path = '/E:/b/build/slave/vm-win-release-x64-be/build/sdk/.packages' (OS Error: The filename, directory name, or volume label syntax is incorrect.


, errno = 123)

#0      main.<anonymous closure> (file:///E:/b/build/slave/vm-win-release-x64-be/build/sdk/utils/kernel-service/kernel-service.dart:110:7)

#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by alexmarkov** [comment]
This issue is outdated: DFE works on Windows. As of today, we have bots which build and test Dart SDK in Dart 2 mode on Windows.
