### ISSUE TITLE
BuildCompilationUnitElementTask from Dart analysis server

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28557]
[report.txt](https://github.com/dart-lang/sdk/files/738757/report.txt)
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.2613.7`
- `1.21.1`
- `IU-171.2613.7, JRE 1.8.0_112-release-b696x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.11.6 unknown, screens 1920x1080, 1920x1080, 2560x1440`

## Exception

Please append the contents of:
file:///private/var/folders/m4/9rg16xhd2rlbln753n9zk1540000gn/T/report.txt

```
Dart analysis server, SDK version 1.21.1, server version 1.17.0, error: Task failed: BuildCompilationUnitElementTask for source /Volumes/Daten/DevLocal/DevDart/MobiAd.REST.UI.MDL/lib/proxies/DeviceProxy.dart
Element mismatch in /Volumes/Daten/DevLocal/DevDart/MobiAd.REST.UI.MDL/lib/proxies/DeviceProxy.dart at class DeviceProxy extends SyncClient with Emitter
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:50)
#1      BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1082)
#2      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#3      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#4      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#5      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#6      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#8      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#9      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#10     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#11     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#12     _rootRun (dart:async/zone.dart:1146)
#13     _CustomZone.run (dart:async/zone.dart:1026)
#14     _CustomZone.runGuarded (dart:async/zone.dart:924)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#16     _rootRun (dart:async/zone.dart:1150)
#17     _CustomZone.run (dart:async/zone.dart:1026)
#18     _CustomZone.runGuarded (dart:async/zone.dart:924)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#20     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#21     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#22     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Element offset mismatch
#0      DeclarationResolver._matchOffset (package:analyzer/src/generated/declaration_resolver.dart:451)
#1      DeclarationResolver._match (package:analyzer/src/generated/declaration_resolver.dart:445)
#2      DeclarationResolver.visitMethodDeclaration (package:analyzer/src/generated/declaration_resolver.dart:325)
#3      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7297)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#5      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#6      RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:674)
#7      DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:87)
#8      DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:502)
#9      DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:86)
#10     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
