### ISSUE TITLE
Flakiness on dartkp-dart_precompiled caused by MallocHooks 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#28638]
```
FAILED: dartkp-dart_precompiled release_x64 co19/Language/Reference/Operator_Precedence/precedence_16_unary_postfix_t07
Expected: Pass 
Actual: Crash
```

Crash dumps archived:

https://storage.cloud.google.com/dart-temp-crash-archive/b74dce4b-44eb-490c-9734-215420f300fd/core.15324.tar.gz
https://storage.cloud.google.com/dart-temp-crash-archive/b74dce4b-44eb-490c-9734-215420f300fd/release_x64_dart_precompiled_runtime.tar.gz

Stack trace from the dump points towards the `MallocHooks`:

```
(gdb) thread apply all bt

Thread 2 (Thread 0x7f11120ed780 (LWP 15324)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000051eee5 in dart::bin::Monitor::WaitMicros (this=0x22e8120, micros=<optimized out>) at ../../runtime/bin/thread_linux.cc:293
#2  0x00000000005029b9 in Wait (millis=0, this=<optimized out>) at ../../runtime/bin/lockers.h:40
#3  dart::bin::EventHandler::Stop () at ../../runtime/bin/eventhandler.cc:93
#4  0x0000000000500bb9 in dart::bin::main (argc=<optimized out>, argv=<optimized out>) at ../../runtime/bin/main.cc:2075
#5  0x00000000005012d9 in main (argc=36602188, argv=0x80) at ../../runtime/bin/main.cc:2103

Thread 1 (Thread 0x7f11120eb700 (LWP 15330)):
#0  0x00007f1110d0fc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f1110d13028 in __GI_abort () at abort.c:89
#2  0x0000000000506371 in dart::bin::segv_handler (signal=<optimized out>, siginfo=<optimized out>, context=<optimized out>) at ../../runtime/bin/platform_linux.cc:27
#3  <signal handler called>
#4  0x00000000006a6ff6 in Lookup (this=<optimized out>, key=<optimized out>) at ../../runtime/vm/hash_map.h:141
#5  Lookup (this=0x23080c0, key=<optimized out>, value=<optimized out>) at ../../runtime/vm/malloc_hooks.cc:94
#6  dart::MallocHooksState::RecordFreeHook (ptr=0x22f6f60) at ../../runtime/vm/malloc_hooks.cc:274
#7  0x000000000052d705 in MallocHook::InvokeDeleteHookSlow (p=<optimized out>) at ../../third_party/tcmalloc/gperftools/src/malloc_hook.cc:505
#8  0x00000000008f7c51 in InvokeDeleteHook (p=<optimized out>) at ../../third_party/tcmalloc/gperftools/src/malloc_hook-inl.h:138
#9  tc_free (ptr=0x22f6f60) at ../../third_party/tcmalloc/gperftools/src/tcmalloc.cc:1609
#10 0x00000000005028a0 in dart::bin::TimeoutQueue::UpdateTimeout (this=<optimized out>, port=<optimized out>, timeout=<optimized out>) at ../../runtime/bin/eventhandler.cc:34
#11 0x000000000050353e in dart::bin::EventHandlerImplementation::HandleInterruptFd (this=<optimized out>) at ../../runtime/bin/eventhandler_linux.cc:211
#12 0x0000000000503c07 in dart::bin::EventHandlerImplementation::Poll (args=<optimized out>) at ../../runtime/bin/eventhandler_linux.cc:402
#13 0x000000000051e74e in dart::bin::ThreadStart (data_ptr=<optimized out>) at ../../runtime/bin/thread_linux.cc:89
#14 0x00007f1111ace184 in start_thread (arg=0x7f11120eb700) at pthread_create.c:312
#15 0x00007f1110dd337d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

Seems to happen in the shutdown sequence.

**Comment by mraleph** [comment]
Here is another instance. Seems like there is a race in shutdown introduced by MallocHooks:

```
(gdb) thread apply all bt
Thread 2 (Thread 0x7fc516609780 (LWP 30835)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000051eee5 in dart::bin::Monitor::WaitMicros (this=0x2dee0c0, micros=<optimized out>) at ../../runtime/bin/thread_linux.cc:293
#2  0x00000000005029b9 in Wait (millis=0, this=<optimized out>) at ../../runtime/bin/lockers.h:40
#3  dart::bin::EventHandler::Stop () at ../../runtime/bin/eventhandler.cc:93
#4  0x0000000000500bb9 in dart::bin::main (argc=<optimized out>, argv=<optimized out>) at ../../runtime/bin/main.cc:2075
#5  0x00000000005012d9 in main (argc=48161004, argv=0x80) at ../../runtime/bin/main.cc:2103

Thread 1 (Thread 0x7fc516607700 (LWP 30836)):
#0  0x00007fc51522bc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fc51522f028 in __GI_abort () at abort.c:89
#2  0x0000000000738919 in dart::OS::Abort () at ../../runtime/vm/os_linux.cc:415
#3  0x000000000064de96 in dart::DynamicAssertionHelper::Fail (this=0x7fc516606d78, format=<optimized out>) at ../../runtime/platform/assert.cc:42
#4  0x00000000007392d4 in dart::OSThread::SetThreadLocal (key=<optimized out>, value=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:179
#5  0x00000000006a6fc6 in MallocHookScope (this=<optimized out>) at ../../runtime/vm/malloc_hooks.cc:37
#6  dart::MallocHooksState::RecordFreeHook (ptr=0x2df6010) at ../../runtime/vm/malloc_hooks.cc:268
#7  0x000000000052d705 in MallocHook::InvokeDeleteHookSlow (p=<optimized out>) at ../../third_party/tcmalloc/gperftools/src/malloc_hook.cc:505
#8  0x00000000008f7c51 in InvokeDeleteHook (p=<optimized out>) at ../../third_party/tcmalloc/gperftools/src/malloc_hook-inl.h:138
#9  tc_free (ptr=0x2df6010) at ../../third_party/tcmalloc/gperftools/src/tcmalloc.cc:1609
#10 0x000000000051e748 in dart::bin::ThreadStart (data_ptr=0x7873) at ../../runtime/bin/thread_linux.cc:86
#11 0x00007fc515fea184 in start_thread (arg=0x7fc516607700) at pthread_create.c:312
#12 0x00007fc5152ef37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

This dump is at:

gs://dart-temp-crash-archive/94ae66d1-f883-41ba-86ce-a51f50dbf607/release_x64_dart_precompiled_runtime.tar.gz
gs://dart-temp-crash-archive/94ae66d1-f883-41ba-86ce-a51f50dbf607/core.30835.tar.gz

**Comment by a-siva** [comment]
uploaded https://codereview.chromium.org/2678313003/ for review
