### ISSUE TITLE
analyzer_cli/embedder_test failing

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#28653]
@leafpetersen @bwilkerson @jmesserly 

The test analyzer_cli/test/embedder_test has started failing on all platforms (lrunning on the VM) after commit a3b4366f11bee47b818b263b75adf0617f319563
of CL https://codereview.chromium.org/2667343005

Suppressing in status file pkg/pkg.status

Error message is:
```
FAILED: none-vm-checked release_x64 pkg/analyzer_cli/test/embedder_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

00:01 +0 -1: _embedder.yaml resolution
  AnalysisException: Cannot compute LIBRARY_ELEMENT for /b/build/slave/azr-be/build/sdk/pkg/analyzer_cli/test/data/embedder_client/embedder_yaml_user.dart
  Caused by Unexpected exception while performing BuildTypeProviderTask for source <unknown source>
  #0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333:7)
  #1      AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
  #2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
  #3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
  #4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:732:14)
  #5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:699:12)
  #6      AnalyzerImpl._resolveLibrary.<_resolveLibrary_async_body> (package:analyzer_cli/src/analyzer_impl.dart:272:24)
  #7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)


 Caused by NoSuchMethodError: The method 'instantiate' was called on null.
  Receiver: null
  Tried calling: instantiate(Instance(length:1) of '_GrowableList')
  #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
  #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
  #2      TypeProviderImpl._initializeFrom (package:analyzer/src/generated/resolver.dart:9512:39)
  #3      TypeProviderImpl.TypeProviderImpl.forNamespaces (package:analyzer/src/generated/resolver.dart:9377:5)
  #4      BuildTypeProviderTask.internalPerform (package:analyzer/src/task/dart.dart:1939:13)
  #5      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321:9)
  #6      AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
  #7      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
  #8      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
  #9      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:732:14)
  #10     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:699:12)
  #11     AnalyzerImpl._resolveLibrary.<_resolveLibrary_async_body> (package:analyzer_cli/src/analyzer_impl.dart:272:24)
  #12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
  #13     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  #14     
```

**Comment by jmesserly** [comment]
it looks like FutureOr definition is missing (failing line https://codereview.chromium.org/2667343005/diff/40001/pkg/analyzer/lib/src/generated/resolver.dart) ... could it somehow be using an out of date SDK/summary?

**Comment by leafpetersen** [comment]
Fix on the way.
