### ISSUE TITLE
Exception reading unlinked summary data

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#28705]
While the stack trace below is not consistent with the current code, I believe that the error still exists.

```
RangeError (byteOffset): Invalid value: Valid value range is empty: 0
#0      _ByteDataView.getUint32 (dart:typed_data-patch/typed_data_patch.dart:2845)
#1      BufferContext._getUint32 (package:analyzer/src/summary/flat_buffers.dart:74)
#2      BufferContext.derefObject (package:analyzer/src/summary/flat_buffers.dart:56)
#3      TableReader.read (package:analyzer/src/summary/flat_buffers.dart:700)
#4      readAnalysisDriverUnlinkedUnit (package:analyzer/src/summary/format.dart:1267)
#5      AnalysisDriverUnlinkedUnit.AnalysisDriverUnlinkedUnit.fromBuffer (package:analyzer/src/summary/idl.dart:264)
#6      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:401)
#7      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:645)
#8      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:505)
#9      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:442)
#10     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:645)
#11     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:505)
#12     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:452)
#13     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:645)
#14     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:505)
#15     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:442)
#16     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:645)
#17     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:505)
#18     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:442)
#19     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:645)
#20     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:505)
#21     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:452)
#22     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:645)
#23     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:505)
#24     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:442)
#25     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:620)
#26     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:669)
#27     AnalysisDriver._performWork.\u003c_performWork_async_body\u003e (package:analyzer/src/dart/analysis/driver.dart:1045)
#28     Future.Future.microtask.\u003canonymous closure\u003e (dart:async/future.dart:184)
#29     _rootRun (dart:async/zone.dart:1154)
#30     _CustomZone.run (dart:async/zone.dart:1034)
#31     _CustomZone.runGuarded (dart:async/zone.dart:932)
#32     _CustomZone.bindCallback.\u003canonymous closure\u003e (dart:async/zone.dart:959)
#33     _rootRun (dart:async/zone.dart:1158)
#34     _CustomZone.run (dart:async/zone.dart:1034)
#35     _CustomZone.runGuarded (dart:async/zone.dart:932)
#36     _CustomZone.bindCallback.\u003canonymous closure\u003e (dart:async/zone.dart:959)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#39     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#40     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by scheglov** [comment]
@bwilkerson Could you archive your `~/.dartServer/.analysis-driver` folder and send the archive to me?

**Comment by scheglov** [comment]
I believe this was fixed by flushing files on write.
https://github.com/dart-lang/sdk/commit/2d0d00061190d1df824628e7ec045ece27af7fd1
