### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by danielmundt** [dart-lang/sdk#28703]
### What I was doing

Running pub update.

### Versions

- Dart SDK 1.21.0
- Visual Studio Code 1.9.1
- Dart Code 0.14.9

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.14.9
```

### Exception

Task failed: ComputeConstantDependenciesTask for element JsonLiteralGenerator() â†’ JsonLiteralGenerator in source C:\Users\Devel\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\source_gen-0.5.4\lib\generators\json_literal_generator.dart

```text
Unexpected exception while performing ComputeConstantDependenciesTask for element JsonLiteralGenerator() â†’ JsonLiteralGenerator in source C:\Users\Devel\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\source_gen-0.5.4\lib\generators\json_literal_generator.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ConstantEvaluationEngine.computeDependencies (package:analyzer/src/dart/constant/evaluation.dart:307)
#3      ComputeConstantDependenciesTask.internalPerform (package:analyzer/src/task/dart.dart:1982)
#4      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#5      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#6      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#7      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#8      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#10     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#11     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#12     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#13     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#14     _rootRun (dart:async/zone.dart:1146)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     _rootRun (dart:async/zone.dart:1150)
#19     _CustomZone.run (dart:async/zone.dart:1026)
#20     _CustomZone.runGuarded (dart:async/zone.dart:924)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#22     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2696073003/
