### ISSUE TITLE
Possible VM Crash in service test (service/get_cpu_profile_timeline_rpc_test)

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28736]
From this [buildbot failure](https://build.chromium.org/p/client.dart/builders/vm-linux-release-simmips-be/builds/4254/steps/checked%20vm%20tests/logs/stdio):

```
FAILED: none-vm-checked release_simmips service/get_cpu_profile_timeline_rpc_test
Expected: Pass Slow 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseSIMMIPS/dart -DDART_SERVICE_USE_AUTH=false --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/.packages --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart
>testee>out> Observatory listening on http://127.0.0.1:44050/
>testee>out> Testee doing something.
>testee>out> Testee did something.
** Signaled to run test queries on http://127.0.0.1:44050/
>testee>out> 
Loading VM...
Done loading VM
Running get_cpu_profile_timeline_rpc_test.dart [1/1]
>testee>err> Dumping native stack trace for thread 4c38
>testee>err>   [0x08616a2c] Unknown symbol
>testee>err>   [0x08616a2c] Unknown symbol
>testee>err>   [0x08619640] Unknown symbol
>testee>err>   [0x08619c2e] dart::Profile::Build(dart::Thread*, dart::SampleFilter*, dart::Profile::TagOrder, int)
>testee>err>   [0x08619f42] dart::ProfilerService::PrintJSONImpl(dart::Thread*, dart::JSONStream*, dart::Profile::TagOrder, int, dart::SampleFilter*, bool)
>testee>err>   [0x0861a206] dart::ProfilerService::PrintTimelineJSON(dart::JSONStream*, dart::Profile::TagOrder, long long, long long)
>testee>err>   [0x08577741] Unknown symbol
>testee>err>   [0x0857f74e] dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
>testee>err>   [0x0857fb71] dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
>testee>err>   [0x0840bb9f] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
>testee>err>   [0x0842d3bf] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
>testee>err>   [0x0842d89a] dart::MessageHandler::TaskCallback()
>testee>err> -- End of DumpStackTrace
** Killing script
Unexpected exception in service tests: NetworkRpcException(Canceling request: WebSocket closed(id: 6 method: _getCpuProfileTimeline params: {tags: VMUser, isolateId: isolates/117415057}))
dart:async/future.dart 237                                    Future.Future.error
package:observatory/src/service/object.dart 823:18            VM.invokeRpcNoUpgrade.<fn>
package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
dart:async/zone.dart 1158                                     _rootRunUnary
dart:async/zone.dart 1037                                     _CustomZone.runUnary
dart:async/future_impl.dart 150                               _FutureListener.handleError
dart:async/future_impl.dart 649                               _Future._propagateToListeners.handleError
dart:async/future_impl.dart 671                               _Future._propagateToListeners
dart:async/future_impl.dart 485                               _Future._completeError
dart:async/future_impl.dart 537                               _Future._asyncCompleteError.<fn>
package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 1150                                     _rootRun
dart:async/zone.dart 1026                                     _CustomZone.run
dart:async/zone.dart 924                                      _CustomZone.runGuarded
dart:async/zone.dart 951                                      _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                         _microtaskLoop
dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                      _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                     _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
unparsed                                                      #3      _CustomZone.registerUnaryCallback (dart:async/zone.dart:1073)
unparsed                                                      #4      _registerErrorHandler (dart:async/async_error.dart:22)
unparsed                                                      #5      _Future.catchError (dart:async/future_impl.dart:256)
unparsed                                                      #6      VM.invokeRpcNoUpgrade (package:observatory/src/service/object.dart:821:8)
unparsed                                                      #7      Isolate.invokeRpcNoUpgrade (package:observatory/src/service/object.dart:1466:15)
unparsed                                                      #8      tests.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart:28:32)
<asynchronous                                                 suspension>
unparsed                                                      #9      tests.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart)
unparsed                                                      #10     _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:325:23)
<asynchronous                                                 suspension>
unparsed                                                      #11     _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #12     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:87:24)
unparsed                                                      #13     _rootRun (dart:async/zone.dart:1150)
unparsed                                                      #14     _CustomZone.run (dart:async/zone.dart:1026)
unparsed                                                      #15     runZoned (dart:async/zone.dart:1503)
unparsed                                                      #16     Chain.capture (package:stack_trace/src/chain.dart:85:12)
unparsed                                                      #17     _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:297:13)
<asynchronous                                                 suspension>
unparsed                                                      #18     _ServiceTesterRunner.run.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #19     _RootZone.runUnary (dart:async/zone.dart:1404)
unparsed                                                      #20     _FutureListener.handleValue (dart:async/future_impl.dart:131)
unparsed                                                      #21     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
unparsed                                                      #22     _Future._propagateToListeners (dart:async/future_impl.dart:667)
unparsed                                                      #23     _Future._completeWithValue (dart:async/future_impl.dart:477)
unparsed                                                      #24     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
unparsed                                                      #25     _microtaskLoop (dart:async/schedule_microtask.dart:41)
unparsed                                                      #26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
unparsed                                                      #27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
unparsed                                                      #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
===== asynchronous gap ===========================
unparsed                                                      #3      _CustomZone.registerCallback (dart:async/zone.dart:1061)
unparsed                                                      #4      _CustomZone.bindCallback (dart:async/zone.dart:949)
unparsed                                                      #5      scheduleMicrotask (dart:async/schedule_microtask.dart:148)
unparsed                                                      #6      Future.Future.microtask (dart:async/future.dart:182)
unparsed                                                      #7      tests.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart)
unparsed                                                      #8      _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:325:23)
<asynchronous                                                 suspension>
unparsed                                                      #9      _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #10     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:87:24)
unparsed                                                      #11     _rootRun (dart:async/zone.dart:1150)
unparsed                                                      #12     _CustomZone.run (dart:async/zone.dart:1026)
unparsed                                                      #13     runZoned (dart:async/zone.dart:1503)
unparsed                                                      #14     Chain.capture (package:stack_trace/src/chain.dart:85:12)
unparsed                                                      #15     _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:297:13)
<asynchronous                                                 suspension>
unparsed                                                      #16     _ServiceTesterRunner.run.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #17     _RootZone.runUnary (dart:async/zone.dart:1404)
unparsed                                                      #18     _FutureListener.handleValue (dart:async/future_impl.dart:131)
unparsed                                                      #19     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
unparsed                                                      #20     _Future._propagateToListeners (dart:async/future_impl.dart:667)
unparsed                                                      #21     _Future._completeWithValue (dart:async/future_impl.dart:477)
unparsed                                                      #22     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
unparsed                                                      #23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
unparsed                                                      #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
unparsed                                                      #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
unparsed                                                      #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
===== asynchronous gap ===========================
unparsed                                                      #3      _CustomZone.registerUnaryCallback (dart:async/zone.dart:1073)
unparsed                                                      #4      _asyncThenWrapperHelper (dart:async-patch/async_patch.dart:27)
unparsed                                                      #5      _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #6      Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:87:24)
unparsed                                                      #7      _rootRun (dart:async/zone.dart:1150)
unparsed                                                      #8      _CustomZone.run (dart:async/zone.dart:1026)
unparsed                                                      #9      runZoned (dart:async/zone.dart:1503)
unparsed                                                      #10     Chain.capture (package:stack_trace/src/chain.dart:85:12)
unparsed                                                      #11     _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:297:13)
<asynchronous                                                 suspension>
unparsed                                                      #12     _ServiceTesterRunner.run.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #13     _RootZone.runUnary (dart:async/zone.dart:1404)
unparsed                                                      #14     _FutureListener.handleValue (dart:async/future_impl.dart:131)
unparsed                                                      #15     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
unparsed                                                      #16     _Future._propagateToListeners (dart:async/future_impl.dart:667)
unparsed                                                      #17     _Future._completeWithValue (dart:async/future_impl.dart:477)
unparsed                                                      #18     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
unparsed                                                      #19     _microtaskLoop (dart:async/schedule_microtask.dart:41)
unparsed                                                      #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
unparsed                                                      #21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
unparsed                                                      #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)



stderr:
Unhandled exception:
NetworkRpcException(Canceling request: WebSocket closed(id: 6 method: _getCpuProfileTimeline params: {tags: VMUser, isolateId: isolates/117415057}))
dart:async/future.dart 237                                    Future.Future.error
package:observatory/src/service/object.dart 823:18            VM.invokeRpcNoUpgrade.<fn>
package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
dart:async/zone.dart 1158                                     _rootRunUnary
dart:async/zone.dart 1037                                     _CustomZone.runUnary
dart:async/future_impl.dart 150                               _FutureListener.handleError
dart:async/future_impl.dart 649                               _Future._propagateToListeners.handleError
dart:async/future_impl.dart 671                               _Future._propagateToListeners
dart:async/future_impl.dart 485                               _Future._completeError
dart:async/future_impl.dart 537                               _Future._asyncCompleteError.<fn>
package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
dart:async/zone.dart 1150                                     _rootRun
dart:async/zone.dart 1026                                     _CustomZone.run
dart:async/zone.dart 924                                      _CustomZone.runGuarded
dart:async/zone.dart 951                                      _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                         _microtaskLoop
dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                      _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                     _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
unparsed                                                      #3      _CustomZone.registerUnaryCallback (dart:async/zone.dart:1073)
unparsed                                                      #4      _registerErrorHandler (dart:async/async_error.dart:22)
unparsed                                                      #5      _Future.catchError (dart:async/future_impl.dart:256)
unparsed                                                      #6      VM.invokeRpcNoUpgrade (package:observatory/src/service/object.dart:821:8)
unparsed                                                      #7      Isolate.invokeRpcNoUpgrade (package:observatory/src/service/object.dart:1466:15)
unparsed                                                      #8      tests.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart:28:32)
<asynchronous                                                 suspension>
unparsed                                                      #9      tests.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart)
unparsed                                                      #10     _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:325:23)
<asynchronous                                                 suspension>
unparsed                                                      #11     _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #12     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:87:24)
unparsed                                                      #13     _rootRun (dart:async/zone.dart:1150)
unparsed                                                      #14     _CustomZone.run (dart:async/zone.dart:1026)
unparsed                                                      #15     runZoned (dart:async/zone.dart:1503)
unparsed                                                      #16     Chain.capture (package:stack_trace/src/chain.dart:85:12)
unparsed                                                      #17     _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:297:13)
<asynchronous                                                 suspension>
unparsed                                                      #18     _ServiceTesterRunner.run.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #19     _RootZone.runUnary (dart:async/zone.dart:1404)
unparsed                                                      #20     _FutureListener.handleValue (dart:async/future_impl.dart:131)
unparsed                                                      #21     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
unparsed                                                      #22     _Future._propagateToListeners (dart:async/future_impl.dart:667)
unparsed                                                      #23     _Future._completeWithValue (dart:async/future_impl.dart:477)
unparsed                                                      #24     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
unparsed                                                      #25     _microtaskLoop (dart:async/schedule_microtask.dart:41)
unparsed                                                      #26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
unparsed                                                      #27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
unparsed                                                      #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
===== asynchronous gap ===========================
unparsed                                                      #3      _CustomZone.registerCallback (dart:async/zone.dart:1061)
unparsed                                                      #4      _CustomZone.bindCallback (dart:async/zone.dart:949)
unparsed                                                      #5      scheduleMicrotask (dart:async/schedule_microtask.dart:148)
unparsed                                                      #6      Future.Future.microtask (dart:async/future.dart:182)
unparsed                                                      #7      tests.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart)
unparsed                                                      #8      _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:325:23)
<asynchronous                                                 suspension>
unparsed                                                      #9      _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #10     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:87:24)
unparsed                                                      #11     _rootRun (dart:async/zone.dart:1150)
unparsed                                                      #12     _CustomZone.run (dart:async/zone.dart:1026)
unparsed                                                      #13     runZoned (dart:async/zone.dart:1503)
unparsed                                                      #14     Chain.capture (package:stack_trace/src/chain.dart:85:12)
unparsed                                                      #15     _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:297:13)
<asynchronous                                                 suspension>
unparsed                                                      #16     _ServiceTesterRunner.run.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #17     _RootZone.runUnary (dart:async/zone.dart:1404)
unparsed                                                      #18     _FutureListener.handleValue (dart:async/future_impl.dart:131)
unparsed                                                      #19     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
unparsed                                                      #20     _Future._propagateToListeners (dart:async/future_impl.dart:667)
unparsed                                                      #21     _Future._completeWithValue (dart:async/future_impl.dart:477)
unparsed                                                      #22     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
unparsed                                                      #23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
unparsed                                                      #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
unparsed                                                      #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
unparsed                                                      #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
===== asynchronous gap ===========================
unparsed                                                      #3      _CustomZone.registerUnaryCallback (dart:async/zone.dart:1073)
unparsed                                                      #4      _asyncThenWrapperHelper (dart:async-patch/async_patch.dart:27)
unparsed                                                      #5      _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #6      Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:87:24)
unparsed                                                      #7      _rootRun (dart:async/zone.dart:1150)
unparsed                                                      #8      _CustomZone.run (dart:async/zone.dart:1026)
unparsed                                                      #9      runZoned (dart:async/zone.dart:1503)
unparsed                                                      #10     Chain.capture (package:stack_trace/src/chain.dart:85:12)
unparsed                                                      #11     _ServiceTesterRunner.run.<anonymous closure>.<<anonymous closure>_async_body> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:297:13)
<asynchronous                                                 suspension>
unparsed                                                      #12     _ServiceTesterRunner.run.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
unparsed                                                      #13     _RootZone.runUnary (dart:async/zone.dart:1404)
unparsed                                                      #14     _FutureListener.handleValue (dart:async/future_impl.dart:131)
unparsed                                                      #15     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
unparsed                                                      #16     _Future._propagateToListeners (dart:async/future_impl.dart:667)
unparsed                                                      #17     _Future._completeWithValue (dart:async/future_impl.dart:477)
unparsed                                                      #18     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
unparsed                                                      #19     _microtaskLoop (dart:async/schedule_microtask.dart:41)
unparsed                                                      #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
unparsed                                                      #21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
unparsed                                                      #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: DART_CONFIGURATION=ReleaseSIMMIPS out/ReleaseSIMMIPS/dart --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart
Took 0:00:08.222269

Short reproduction command (experimental):
    python tools/test.py -mrelease -asimmips --checked -t240 service/get_cpu_profile_timeline_rpc_test
```

/cc @johnmccutchan Do you have any ideas what might go wrong here?

**Comment by mkustermann** [comment]
I'll look into why we don't have coredumps on this bot yet.

**Comment by floitschG** [comment]
Unfortunately the coredumps aren't recorded, because the crash happens in a nested process.

Today we had a similar crash. https://build.chromium.org/p/client.dart/builders/vm-linux-release-simmips-be/builds/4724/steps/checked%20vm%20tests/logs/stdio

```
FAILED: none-vm-checked release_simmips service/get_cpu_profile_timeline_rpc_test
Expected: Pass Slow 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseSIMMIPS/dart -DDART_SERVICE_USE_AUTH=false --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/.packages --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart
>testee>out> Observatory listening on http://127.0.0.1:58073/
>testee>out> Testee doing something.
>testee>out> Testee did something.
** Signaled to run test queries on http://127.0.0.1:58073/
>testee>out> 
Loading VM...
Done loading VM
Running get_cpu_profile_timeline_rpc_test.dart [1/1]
>testee>err> Dumping native stack trace for thread 6731
>testee>err>   [0x086279ab] Unknown symbol
>testee>err>   [0x086279ab] Unknown symbol
>testee>err>   [0x0862a2f0] Unknown symbol
>testee>err>   [0x0862a8de] dart::Profile::Build(dart::Thread*, dart::SampleFilter*, dart::Profile::TagOrder, int)
>testee>err>   [0x0862ac02] dart::ProfilerService::PrintJSONImpl(dart::Thread*, dart::JSONStream*, dart::Profile::TagOrder, int, dart::SampleFilter*, bool)
>testee>err>   [0x0862ad20] dart::ProfilerService::PrintTimelineJSON(dart::JSONStream*, dart::Profile::TagOrder, long long, long long)
>testee>err>   [0x08587271] Unknown symbol
>testee>err>   [0x0858f28e] dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
>testee>err>   [0x0858f681] dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
>testee>err>   [0x08415a94] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
>testee>err>   [0x08437d3f] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
>testee>err>   [0x0843821a] dart::MessageHandler::TaskCallback()
>testee>err> -- End of DumpStackTrace
** Killing script
Unexpected exception in service tests: NetworkRpcException(Canceling request: WebSocket closed(id: 6 method: _getCpuProfileTimeline params: {tags: VMUser, isolateId: isolates/395768576}))
#0      tests.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart:28:18)
<asynchronous suspension>
#1      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:324:23)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1158)
#3      _CustomZone.runUnary (dart:async/zone.dart:1037)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#7      _Future._completeWithValue (dart:async/future_impl.dart:477)
#8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)



stderr:
Unhandled exception:
NetworkRpcException(Canceling request: WebSocket closed(id: 6 method: _getCpuProfileTimeline params: {tags: VMUser, isolateId: isolates/395768576}))
#0      _ServiceTesterRunner.run.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:339:9)
<asynchronous suspension>
#1      _rootRunBinary (dart:async/zone.dart:1174)
#2      _RootZone.runBinary (dart:async/zone.dart:1411)
#3      runZoned.<anonymous closure> (dart:async/zone.dart:1478)
#4      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:552)
#6      _Future._completeError (dart:async/future_impl.dart:485)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:56)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:331:7)
<asynchronous suspension>
#10     _rootRunUnary (dart:async/zone.dart:1158)
#11     _CustomZone.runUnary (dart:async/zone.dart:1037)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#15     _Future._completeWithValue (dart:async/future_impl.dart:477)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#17     _rootRun (dart:async/zone.dart:1150)
#18     _CustomZone.run (dart:async/zone.dart:1026)
#19     _CustomZone.runGuarded (dart:async/zone.dart:924)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: DART_CONFIGURATION=ReleaseSIMMIPS out/ReleaseSIMMIPS/dart --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-simmips-be/build/sdk/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart
Took 0:00:07.102908

Short reproduction command (experimental):
    python tools/test.py -mrelease -asimmips --checked -t240 service/get_cpu_profile_timeline_rpc_test


```

**Comment by alexmarkov** [comment]
Tentatively closing this issue, as test doesn't appear on flakiness dashboard. It is either hiding or https://github.com/dart-lang/sdk/commit/3b22a7ae4689620c5ce1778c5afe4071c72ad79e fixed the problem.
