### ISSUE TITLE
"Unexpected exception while performing ResolveUnitTask" from Analyzer (1.21.1)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#28755]
I suspect you may have fixed this but I just got it while typing in 1.21.1.

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Typing code. Here's a trimmed version of the AS log. There were some getFixes requests sent around the time I was typing (I ended up receiving three errors; the second two messages suggested they were a result of this original error).

```text
[15:27:48]: ==> {"id":"24","method":"analysis.updateContent","params":{"files":{"m:\\Coding\\Applications\\chart-data-migrator\\bin\\migrate.dart":{"type":"change","edits":[{"offset":317,"length":0,"replacement":"e","id":""}]}}}}
[15:27:48]: ==> {"id":"25","method":"edit.getFixes","params":{"file":"m:\\Coding\\Applications\\chart-data-migrator\\bin\\migrate.dart","offset":316}}
[15:27:49]: ==> {"id":"26","method":"analysis.updateContent","params":{"files":{"m:\\Coding\\Applications\\chart-data-migrator\\bin\\migrate.dart":{"type":"change","edits":[{"offset":318,"length":0,"replacement":"w","id":""}]}}}}
[15:27:49]: ==> {"id":"27","method":"edit.getFixes","params":{"file":"m:\\Coding\\Applications\\chart-data-migrator\\bin\\migrate.dart","offset":316}}
[15:27:49]: <== {"event":"completion.results", ...
[15:27:49]: <== {"id":"24","result":{}}
[15:27:49]: <== {"id":"26","result":{}}
[15:27:49]: <== {"id":"25","result":{"fixes":[]}}
[15:27:49]: <== {"id":"27","result":{"fixes":[]}}
[15:27:49]: <== {"event":"analysis.errors", ...
[15:27:49]: <== {"event":"server.error","params": ...
```

### Versions

- Dart SDK 1.21.1
- Visual Studio Code 1.9.1
- Dart Code 0.15.1

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.15.1
```

### Exception

Task failed: ResolveUnitTask for source m:\Coding\Applications\chart-data-migrator\bin\migrate.dart

```text
Unexpected exception while performing ResolveUnitTask for source m:\Coding\Applications\chart-data-migrator\bin\migrate.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find dynamic req in [CreateTableRequest req, Response resp]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3153)
#1      LocalVariableElementImpl.identifier (package:analyzer/src/dart/element/element.dart:6049)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3193)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2911)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2800)
#5      _HashMap.[] (dart:collection-patch/collection_patch.dart:87)
#6      TypeOverrideManager_TypeOverrideScope.getType (package:analyzer/src/generated/resolver.dart:8726)
#7      TypeOverrideManager.getType (package:analyzer/src/generated/resolver.dart:8614)
#8      StaticTypeAnalyzer.visitSimpleIdentifier (package:analyzer/src/generated/static_type_analyzer.dart:1327)
#9      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9157)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6311)
#11     UnifyingAstVisitor.visitSimpleIdentifier (package:analyzer/dart/ast/visitor.dart:2763)
#12     SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9157)
#13     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10865)
#14     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#15     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:2816)
#16     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:7736)
#17     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:6436)
#18     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10860)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#20     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10958)
#21     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#22     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:2820)
#23     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:6462)
#24     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10952)
#25     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11013)
#26     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#27     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:2824)
#28     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11009)
#29     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#30     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#31     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#32     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2517)
#33     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7237)
#34     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#35     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#36     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#37     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2520)
#38     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7249)
#39     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5554)
#40     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#41     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5336)
#42     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#43     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:2631)
#44     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7549)
#45     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:6041)
#46     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)
#47     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5181)
#48     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#49     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:2624)
#50     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:7542)
#51     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5999)
#52     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7534)
#53     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5989)
#54     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5174)
#55     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5659)
#56     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#57     ResolveUnitTask.internalPerform (package:analyzer/src/task/dart.dart:5679)
#58     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#59     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#60     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#61     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#62     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#63     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#64     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#65     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#66     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#67     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#68     _rootRun (dart:async/zone.dart:1146)
#69     _CustomZone.run (dart:async/zone.dart:1026)
#70     _CustomZone.runGuarded (dart:async/zone.dart:924)
#71     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#72     _rootRun (dart:async/zone.dart:1150)
#73     _CustomZone.run (dart:async/zone.dart:1026)
#74     _CustomZone.runGuarded (dart:async/zone.dart:924)
#75     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#76     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#77     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#78     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#79     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by DanTup** [comment]
FWIW, here's some stats from Dart Code's analytics - looks like this error has been sent a couple of times from `1.22.0-dev.9` too.

![Error numbers](https://cloud.githubusercontent.com/assets/1078012/22863496/09001290-f139-11e6-8a59-4a1e158f1fde.png)

**Comment by bwilkerson** [comment]
Yes, we are, sadly, aware of the issue. It, and several related exceptions, occur in a piece of code we are currently working on replacing, so hopefully it will be fixed soon.
