### ISSUE TITLE
NoSuchMethodError: Class 'String' has no instance getter 'iterator' with bad analysis_options file

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#28756]
While trying to repro another issue, I saved my `analysis_options.yaml` file with incorrect contents (there's no minus in front of the filename) and restarted the analyzer.

```yaml
analyzer:
  strong-mode:
    implicit-dynamic: false
  exclude:
    lib/ignore_me.dart
```

It resulted in an exception from the analysis server. I don't think it's bad that an error is returned, but this doesn't seem like a useful one - if the file is invalid it would be better to report it in a way that we can pass on to the user.

### Versions

- Dart SDK 1.21.1
- Visual Studio Code 1.9.1
- Dart Code 0.15.1

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.15.1
```

### Exception (fatal)

Failed to handle request: {params: {included: [c:\Users\danny\Desktop\DartSample], excluded: []}, method: analysis.setAnalysisRoots, id: 2}

```text
NoSuchMethodError: Class 'String' has no instance getter 'iterator'.
Receiver: "lib/ignore_me.dart"
Tried calling: iterator
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      toStringList (package:analyzer/src/util/yaml.dart:18)
#3      ContextManagerImpl.processOptionsForContext (package:analysis_server/src/context_manager.dart:671)
#4      ContextManagerImpl._checkForAnalysisOptionsUpdate (package:analysis_server/src/context_manager.dart:985)
#5      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1513)
#6      _rootRunUnary (dart:async/zone.dart:1158)
#7      _CustomZone.runUnary (dart:async/zone.dart:1037)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#11     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:386)
#12     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:261)
#13     _rootRunUnary (dart:async/zone.dart:1158)
#14     _CustomZone.runUnary (dart:async/zone.dart:1037)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#17     _DelayedData.perform (dart:async/stream_impl.dart:590)
#18     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:666)
#20     _rootRun (dart:async/zone.dart:1146)
#21     _CustomZone.run (dart:async/zone.dart:1026)
#22     _CustomZone.runGuarded (dart:async/zone.dart:924)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#24     _rootRun (dart:async/zone.dart:1150)
#25     _CustomZone.run (dart:async/zone.dart:1026)
#26     _CustomZone.runGuarded (dart:async/zone.dart:924)
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#30     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#31     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2697603005/
