### ISSUE TITLE
Unexpected (incorrect?) port number reported in error when HttpClient connections fail

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#28753]
This is a bit confusing - I'm failing to connect to port `8000` on `192.168.0.100` but the error message has a different port number listed (`8286`). I don't know if this is the local port being used but that doesn't seem like a useful thing (and it would be confusing to display immediately after the remote host/IP).

I'm using x64 Dart SDK v1.21.0 on Windows 10 Pro.

```dart
Uri dynamoEndpoint = Uri.parse("http://192.168.0.100:8000/");

Future<String> _sendRequest(String action, Request request) async {
  final http = new HttpClient();
  final request = await http.postUrl(dynamoEndpoint);
  request.headers
    ..contentType = new ContentType("application", "x-amz-json-1.0");
  request.write(request);
  final response = await request.close().whenComplete(http.close);
  return response.transform(UTF8.decoder).join("");
}
```

Error:

```text
dart bin\migrate.dart
Unhandled exception:
SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = 192.168.0.100, port = 8286
#0      _sendRequest.<_sendRequest_async_body> (package:chart_data_migrator/dynamodb.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _RootZone.runBinary (dart:async/zone.dart:1410)
#3      _FutureListener.handleError (dart:async/future_impl.dart:146)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#6      _Future._completeError (dart:async/future_impl.dart:485)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
finished (255)
```

**Comment by zoechi** [comment]
Looks like #12693

**Comment by DanTup** [comment]
Yep, I think you're correct. The original comment there says it's showing local host too, though I'm seeing the remote IP and only local (probably) port (and the most recent comment on that suggests the same).

That case has been open since 2013 😢

**Comment by natebosch** [comment]
Lets track at #12693
