### ISSUE TITLE
DDC won't run on Win

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/sdk#28752]
Running Dart dev compiler on Windows fails.

Tried the following:
`dartdevc some\input.dart -o out`
and
`dartdevc some\input.dart -o out\input.dart.js`

In either case, I get this error:
```
Invalid argument(s): Uri c: must have scheme 'file:'.
#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:73)
#1      Context.fromUri (package:path/src/context.dart:834)
#2      fromUri (package:path/path.dart:354)
#3      placeSourceMap.transformUri (package:dev_compiler/src/compiler/compiler.dart:555)
#4      placeSourceMap (package:dev_compiler/src/compiler/compiler.dart:559)
#5      JSModuleFile.getCode (package:dev_compiler/src/compiler/compiler.dart:464)
#6      JSModuleFile.writeCodeSync (package:dev_compiler/src/compiler/compiler.dart:494)
#7      _compile (package:dev_compiler/src/compiler/command.dart:159)
#8      compile (package:dev_compiler/src/compiler/command.dart:52)
#9      main.<main_async_body> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:51)
#10     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Am I using DDC wrong?
Related report: [dart-lang/source_span#12]

**Comment by Mohammed90** [comment]
Here's more debug information related to this issue.

Tried the following:
`dartdevc --dart-sdk="file:///C:/tools/dart-sdk" -v .\main.dart -o main.dart.js`

and (note: the syntax to the path here is wrong, but I thought I should give it a shot as it might reveal if it's path parsing issue):

`dartdevc --dart-sdk="file://C:/tools/dart-sdk" -v .\main.dart -o main.dart.js`

The result is:
 ```
    dartdevc arguments: --dart-sdk=C:\tools\dart-sdk --dart-sdk=file:///C:/tools/dart-sdk -v .\main.dart -o main.dart.js
    dart --version: 1.22.0 (Mon Feb 13 17:39:28 2017) on "windows_x64"

FileSystemException: Cannot open file, path = 'file:///C:/tools/dart-sdk\lib\_internal\ddc_sdk.sum' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
#0      _File.throwIfError (dart:io/file_impl.dart:562)
#1      _File.openSync (dart:io/file_impl.dart:413)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:473)
#3      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:411)
#4      List.forEach (dart:core-patch/growable_array.dart:258)
#5      SummaryDataStore.SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:328)
#6      SummaryBasedDartSdk.SummaryBasedDartSdk (package:analyzer/src/summary/summary_sdk.dart:40)
#7      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:340)
#8      ModuleCompiler.ModuleCompiler (package:dev_compiler/src/compiler/compiler.dart:83)
#9      _compile (package:dev_compiler/src/compiler/command.dart:124)
#10     compile (package:dev_compiler/src/compiler/command.dart:53)
#11     main.<main_async_body> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:53)
#12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)```
