### ISSUE TITLE
Debugging via kernel and kernel isolate hangs at exit

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#28789]
Say I have this dart file (helloworld.dart):
```dart
main() {
  print("Hello, World!");
}
```

and, standing in dart-sdk/sdk$, run
```
out/ReleaseX64/dart --dfe=utils/kernel-service/kernel-service.dart --packages=.packages --pause_isolates_on_start --enable-vm-service:54975 helloworld.dart
```

I'm told
```
Observatory listening on http://127.0.0.1:54975/
```
going to that address, wait for the isolate "helloworld.dart$main" to be paused at start (it might already be, it will come when the kernel isolate has done its thing). Debug it and say continue. Observatory disconnects (as expected). The terminal says "Hello, World!" (as expected), but the program doesn't exit. 

eu-stack says
```
PID 163365 - process
TID 163365:
#0  0x00007f224833f404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000000000853755 dart::Monitor::WaitMicros(long)
#2  0x00000000009398fa dart::ServiceIsolate::Shutdown()
#3  0x00000000006baa36 dart::Dart::Cleanup()
#4  0x000000000064e39e Dart_Cleanup
#5  0x0000000000525865 dart::bin::main(int, char**)
#6  0x0000000000525f59 main
#7  0x00007f2247567f45 __libc_start_main
#8  0x0000000000523ebb _start
TID 163366:
#0  0x00007f2247640a13 epoll_wait
#1  0x0000000000528e25 dart::bin::EventHandlerImplementation::Poll(unsigned long)
#2  0x0000000000543dae dart::bin::ThreadStart(void*)
#3  0x00007f224833b184 start_thread
#4  0x00007f224764037d __clone
TID 163371:
#0  0x00007f224833f404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000000000853755 dart::Monitor::WaitMicros(long)
#2  0x00000000006b1aaa dart::BackgroundCompiler::Run()
#3  0x000000000095822d dart::ThreadPool::Worker::Loop()
#4  0x00000000009580f5 dart::ThreadPool::Worker::Main(unsigned long)
#5  0x0000000000852e99 dart::ThreadStart(void*)
#6  0x00007f224833b184 start_thread
#7  0x00007f224764037d __clone
```

**Comment by jensjoha** [comment]
This happens basically every time in release mode, until suddenly it doesn't.
This seems to happen more often on a debug build than on a release build (though it also appears to 'get warm' and do it less often).

I've added some printf's:
```
diff --git a/runtime/vm/message_handler.cc b/runtime/vm/message_handler.cc
index 649ae662a4..841d62cf4e 100644
--- a/runtime/vm/message_handler.cc
+++ b/runtime/vm/message_handler.cc
@@ -495,6 +497,7 @@ void MessageHandler::increment_live_ports() {
   CheckAccess();
 #endif
   live_ports_++;
+  printf("Incremented live ports to %ld\n", live_ports_);
 }
 
 
@@ -504,6 +507,7 @@ void MessageHandler::decrement_live_ports() {
   CheckAccess();
 #endif
   live_ports_--;
+  printf("Decremented live ports to %ld\n", live_ports_);
 }
 
 
diff --git a/runtime/vm/port.cc b/runtime/vm/port.cc
index 20a142dd82..4be835f671 100644
--- a/runtime/vm/port.cc
+++ b/runtime/vm/port.cc
@@ -110,6 +110,7 @@ void PortMap::SetPortState(Dart_Port port, PortState state) {
   map_[index].state = state;
   if (state == kLivePort) {
     map_[index].handler->increment_live_ports();
+    printf("Incremented live ports with port %ld [%s]\n", port, map_[index].handler->name());
   }
   if (FLAG_trace_isolates) {
     OS::Print(
@@ -210,6 +213,7 @@ bool PortMap::ClosePort(Dart_Port port) {
     map_[index].handler = deleted_entry_;
     if (map_[index].state == kLivePort) {
       handler->decrement_live_ports();
+      printf("Decremeneted live ports with port %ld [%s]\n", port, handler->name());
     }
 
     used_--;
diff --git a/runtime/vm/service.cc b/runtime/vm/service.cc
index c456fee51e..8e8143a2d7 100644
--- a/runtime/vm/service.cc
+++ b/runtime/vm/service.cc
@@ -164,14 +164,17 @@ void Service::CancelStream(const char* stream_id) {
   for (intptr_t i = 0; i < num_streams; i++) {
     if (strcmp(stream_id, streams_[i]->id()) == 0) {
       streams_[i]->set_enabled(false);
+      OS::Print("vm-service: stopping stream '%s' (1)\n", stream_id);
       return;
     }
   }
   if (stream_cancel_callback_) {
     Thread* T = Thread::Current();
     TransitionVMToNative transition(T);
+    OS::Print("vm-service: stopping stream '%s' (2)\n", stream_id);
     return (*stream_cancel_callback_)(stream_id);
   }
+  OS::Print("vm-service: stopping stream '%s' (3)\n", stream_id);
 }
 
 RawObject* Service::RequestAssets() {
diff --git a/runtime/vm/service_isolate.cc b/runtime/vm/service_isolate.cc
index 0cb3cd25c1..71e9727645 100644
--- a/runtime/vm/service_isolate.cc
+++ b/runtime/vm/service_isolate.cc
@@ -269,6 +269,7 @@ void ServiceIsolate::SendServiceExitMessage() {
 
 void ServiceIsolate::SetServicePort(Dart_Port port) {
   MonitorLocker ml(monitor_);
+  printf("Setting service port to %ld\n", port);
   port_ = port;
 }
```

and on a hanging run I get this:

```
[...]
Decremented live ports to 0
Decremeneted live ports with port 885123160 [helloworld.dart$main-778084227]
Hello, World!
Decremented live ports to 0
Decremented live ports to 9
Decremeneted live ports with port 921675198 [vm-service]
Decremented live ports to 8
Decremeneted live ports with port 449834014 [vm-service]
vm-service: stopping stream 'VM' (1)
vm-service: stopping stream 'Isolate' (1)
vm-service: stopping stream 'Debug' (1)
vm-service: stopping stream '_Graph' (1)
vm-service: stopping stream 'Stdout' (2)
vm-service: stopping stream 'Stderr' (2)
vm-service: stopping stream '_Logging' (1)
Incremented live ports to 9
Incremented live ports with port 886162531 [vm-service]
Decremented live ports to 8
Decremeneted live ports with port 27336983 [vm-service]
vm-service: stopping stream 'Stdout' (2)
vm-service: stopping stream 'Stderr' (2)
vm-service: stopping stream '_Logging' (1)
Decremented live ports to 7
Decremeneted live ports with port 466087942 [vm-service]
Decremented live ports to 6
Decremeneted live ports with port 336844365 [vm-service]
Decremented live ports to 5
Decremeneted live ports with port 63303822 [vm-service]
Decremented live ports to 4
Decremeneted live ports with port 573498265 [vm-service]
Decremented live ports to 3
Decremeneted live ports with port 130605531 [vm-service]
Decremented live ports to 2
Decremeneted live ports with port 617011615 [vm-service]
Decremented live ports to 1
Decremeneted live ports with port 679488405 [vm-service]
```

where it seems to me that the interesting part is the creation of port 886162531 whilst shutting down. This port is never closed again.
Port 679488405 should probably have been the last one, meaning no more live ports, meaning the message_handler.cc, MessageHandler::TaskCallback(), would have run the  end callback (ShutdownIsolate), which would run ServiceIsolate::SetServicePort(ILLEGAL_PORT); which would stop the wait from the stacktrace above (#2  0x00000000009398fa dart::ServiceIsolate::Shutdown()).

If I could then just figure out why that new port is created...

**Comment by jensjoha** [comment]
I got the following stacktrace (dart-side) for the new port:
```
#0      RawReceivePort.RawReceivePort (dart:isolate-patch/isolate_patch.dart:48)
#1      Message.send (dart:_vmservice/message.dart:97)
#2      RunningIsolate.route (dart:_vmservice/running_isolate.dart:18)
#3      RunningIsolates.route (dart:_vmservice/running_isolates.dart:60)
#4      VMService.route (dart:_vmservice:477)
#5      Client.onMessage (dart:_vmservice/client.dart:30)
#6      WebSocketClient.onWebSocketMessage (server.dart:42:7)
#7      WebSocketClient.WebSocketClient.<anonymous closure> (server.dart:15:32)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#11     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#12     _StreamController._add (dart:async/stream_controller.dart:635)
#13     _StreamController.add (dart:async/stream_controller.dart:581)
#14     _WebSocketImpl._WebSocketImpl._fromSocket.<anonymous closure> (dart:io/websocket_impl.dart:1111)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#20     _WebSocketProtocolTransformer._messageFrameEnd (dart:io/websocket_impl.dart:333)
#21     _WebSocketProtocolTransformer.add (dart:io/websocket_impl.dart:228)
#22     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#26     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#27     _StreamController._add (dart:async/stream_controller.dart:635)
#28     _StreamController.add (dart:async/stream_controller.dart:581)
#29     _Socket._onData (dart:io-patch/socket_patch.dart:1680)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#33     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#34     _StreamController._add (dart:async/stream_controller.dart:635)
#35     _StreamController.add (dart:async/stream_controller.dart:581)
#36     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#37     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:781)
#38     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#40     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:103)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:156)
```

So it seems that the vmservice gets some message that it responds to. In doing so, it creates a port which stops the vm from shutting down...

**Comment by jensjoha** [comment]
So this seems to be what happens:

* While stuff is closing down, the dart-side wants to send a "getIsolate" message.
* This opens a receive port.
* The handler on this receive port closes the port.
* The message send errors out because the receiving port no longer exist.
* The receive port is never closed.
* On the C++-side, message_handler.cc in MessageHandler::TaskCallback(), doesn't run the end callback (ShutdownIsolate) because of the open port.
* This means that ServiceIsolate::SetServicePort(ILLEGAL_PORT) is not run either.
* This in turn means that we're stuck in dart::ServiceIsolate::Shutdown().

Solution: Close receive port on error => https://codereview.chromium.org/2703133004
