### ISSUE TITLE
Analyzer error

### ISSUE THREAD

**Issue by dabhaid** [dart-lang/sdk#28782]
Exception from analysis server (running from Atom)

### what happened

This seems to happen every time the analyzer runs from cold (e.g. launch Atom)

In addition I suspect the root cause of this is resulting in my seeing a lot
of warnings that things like 'wait', 'then', 'map', 'transform' are not methods
and List is not a type.

### version information

- Dart SDK 1.17.0-dev.4.1
- Atom 1.14.2
- dartlang 0.6.45

### the exception

Found element with null library: StackTrace

```
null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:987)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:46)
#2      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:282)
#3      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2247)
#4      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:6152)
#5      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2247)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682)
#7      CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2169)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6772)
#9      PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5201)
#10     UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:3278)
#11     ResolverVisitor.safelyVisitComment (package:analyzer/src/generated/resolver.dart:5884)
#12     ResolverVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:6745)
#13     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:8043)
#14     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:6734)
#15     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7181)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682)
#17     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:7724)
#18     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7701)
#19     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:6103)
#20     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1841)
#21     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:6169)
#22     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2433)
#23     PartiallyResolveUnitReferencesTask.internalPerform (package:analyzer/src/task/dart.dart:3910)
#24     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#25     AnalysisTask.perform (package:analyzer/task/model.dart:229)
#26     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#27     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#28     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1161)
#29     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#30     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1159)
#31     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#32     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#33     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#34     _rootRun (dart:async/zone.dart:946)
#35     _CustomZone.run (dart:async/zone.dart:826)
#36     _CustomZone.runGuarded (dart:async/zone.dart:724)
#37     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#38     _rootRun (dart:async/zone.dart:950)
#39     _CustomZone.run (dart:async/zone.dart:826)
#40     _CustomZone.runGuarded (dart:async/zone.dart:724)
#41     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#42     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#43     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#44     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```

**Comment by eseidelGoogle** [comment]
1.17 is pretty old. :)  Might be worth an upgrade:
https://www.dartlang.org/tools/sdk

**Comment by dabhaid** [comment]
Yes - I twigged about two seconds after submitting the bug. A hangover of having set up to use flutter in a fuchsia repo I haven't updated in a while on this machine :) Thanks Eric!
