### ISSUE TITLE
NPE from DartUnitHoverComputer._computeDocumentation

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28829]
This is from an SDK built from head:

- Dart SDK 1.23.0-edge.e35365588b18fd4cb9b551a95770f1dec1117842

Failed to handle request: {params: {file: /Users/devoncarew/projects/workspace/sdk/pkg/analyzer_cli/lib/src/analyzer_impl.dart, offset: 2485}, method: analysis.getHover, id: 413}

```text
NoSuchMethodError: The getter 'documentationComment' was called on null.
Receiver: null
Tried calling: documentationComment
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      DartUnitHoverComputer._computeDocumentation (package:analysis_server/src/computer/computer_hover.dart:118)
#3      DartUnitHoverComputer.compute (package:analysis_server/src/computer/computer_hover.dart:76)
#4      AnalysisDomainHandler.getHover (package:analysis_server/src/domain_analysis.dart:117)
<asynchronous suspension>
#5      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:230)
#6      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:876)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#8      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:872)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     runZoned (dart:async/zone.dart:1501)
#13     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:871)
#14     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#16     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161)
#17     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
...
```

**Comment by bwilkerson** [comment]
That offset appears to be in the middle of a dartdoc comment for an instance field. Do you have local changes to that file?

**Comment by devoncarew** [comment]
Ah, yeah, plenty. And I was in the middle of editing it. Let me try and map to where it would have been.

**Comment by devoncarew** [comment]
Possibly on the `this.librarySource` param of the `AnalyzerImpl` constructor. I may have been in the middle of changing the name (and type) of the param.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2704933002/
