### ISSUE TITLE
samples/sample_extension/test/sample_extension_app_snapshot_test sometimes fails on win-debug

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#28842]
The failures have the following form:
```FAILED: none-vm debug_ia32 samples/sample_extension/test/sample_extension_app_snapshot_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
+ out\DebugIA32\dart.exe --snapshot=C:\Users\CHROME~2\AppData\Local\Temp\sample_extension_8db77f2c-f7af-11e6-bd97-005056030146\test_sample_synchronous_extension.dart.snapshot --snapshot-kind=app-jit C:\Users\CHROME~2\AppData\Local\Temp\sample_extension_8db77f2c-f7af-11e6-bd97-005056030146\test_sample_synchronous_extension.dart
Failing process stdout: 
Failing process stderr: e:\b\build\slave\vm-win-debug-ia32-be\build\sdk\runtime\vm\verifier.cc: 55: error: Invalid object pointer encountered 0x4348248



Dumping native stack trace for thread 1924

e:\b\build\slave\vm-win-debug-ia32-be\build\sdk\runtime\vm\heap.cc: 214: error: expected: old_space_->iterating_thread_ != thread()

Aborting re-entrant request for stack trace.


End failing process stderr


stderr:
Unhandled exception:
Expect.fail('Test failed with exit code 3')
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.fail (package:expect/expect.dart:154:5)
#2      run (file:///E:/b/build/slave/vm-win-debug-ia32-be/build/sdk/samples/sample_extension/test/sample_extension_test_helper.dart:48:12)
<asynchronous suspension>
#3      testNativeExtensions (file:///E:/b/build/slave/vm-win-debug-ia32-be/build/sdk/samples/sample_extension/test/sample_extension_test_helper.dart:79:15)
<asynchronous suspension>
#4      main (file:///E:/b/build/slave/vm-win-debug-ia32-be/build/sdk/samples/sample_extension/test/sample_extension_app_snapshot_test.dart:10:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: set DART_CONFIGURATION=DebugIA32 & out\DebugIA32\dart.exe --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-debug-ia32-be\build\sdk\.packages E:\b\build\slave\vm-win-debug-ia32-be\build\sdk\samples\sample_extension\test\sample_extension_app_snapshot_test.dart
Took 0:00:02.626262

Short reproduction command (experimental):
    python tools/test.py -aia32 -t120 samples/sample_extension/test/sample_extension_app_snapshot_test
```

**Comment by jensjoha** [comment]
(apparently I didn't search well enough back in March: https://github.com/dart-lang/sdk/issues/29176)

**Comment by athomas** [comment]
Test no longer exists.
