### ISSUE TITLE
tests/standalone/io/console_unicode_test.dart prints non UTF-8 output and breaks output logging

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#28872]
When I pipe the output of tests/standalone/io/console_unicode_test.dart through iconv, I get an error (and the output appears to be garbled):

```
$ ./xcodebuild/ReleaseX64/dart tests/standalone/io/console_unicode_test.dart | iconv -t utf8 -f utf8
These are three black spades: ♠♠♠
German characters: aäbcdefghijklmnoöpqrsßtuüvwxyz
These are three black spades: ♠♠♠
German characters: aäbcdefghijklmnoöpqrsßtuüvwxyz
These are three black spades: ```
German characters: a
iconv: (stdin):6:20: cannot convert
```

On Android, this causes a stack trace in test.dart when the output is decoded from UTF-8:

```
Unhandled exception:
FormatException: Bad UTF-8 encoding 0x62 (at offset 21)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:486)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:333)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#8      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#9      _StreamController._add (dart:async/stream_controller.dart:635)
#10     _StreamController.add (dart:async/stream_controller.dart:581)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:1682)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#15     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#16     _StreamController._add (dart:async/stream_controller.dart:635)
#17     _StreamController.add (dart:async/stream_controller.dart:581)
#18     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1249)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:783)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by zanderso** [comment]
There is no guarantee that Dart programs only output utf8 on stdout or stderr. I will see if I can update test.dart to remove that assumption.

**Comment by peter-ahe-google** [comment]
May I also suggest that you add a note in the test that it's not supposed to emit only UTF-8.

**Comment by peter-ahe-google** [comment]
Actually, I'm not sure that it would be a good idea to change test.dart in this respect. This limitation has been in place for many years, and it has mostly caught bugs.

**Comment by zanderso** [comment]
Could you elaborate on that? It seems like we don't currently have any tests for putting arbitrary data on Dart's stdout stream.

**Comment by zanderso** [comment]
What bugs were caught by having this restriction?

**Comment by peter-ahe-google** [comment]
It's been a while since I last encountered this, I think I've seen it with byte codes in Dartino. Instead of printing the raw bytes, they should have been pretty printed.

Also, I vaguely remember something about misconfigured programs that emit latin-1 instead of UTF-8.

Finally, having this restriction ensures that our logs are in UTF-8.

**Comment by zanderso** [comment]
Okay. I will update the test, and also see if I can get test.dart to do something more helpful in this case.

**Comment by zanderso** [comment]
After taking a look, I see now that the Android test runner has to convert the output to a string to parse out the exit code. Doing the right thing there for non-utf8 output probably requires some surgery. Instead, I'll catch and report non-utf8 output for other configurations, which should hopefully be sufficient to avoid having tests that trigger the problem for Android.

https://codereview.chromium.org/2710003005
