### ISSUE TITLE
Huge unreadable stack traces

### ISSUE THREAD

**Issue by hermanbergwerf** [dart-lang/sdk#28879]
While working in dart `1.23.0-dev.0.0`, I encountered very large stack traces when running the test package.

E.g.
```
00:01 +21 -1: test/parse_test.dart: Fundamental checks for the parser                              
  'package:eqlib/src/parser.dart': Failed assertion: line 269 pos 10: 'output.length == 1': is not true.
  unparsed       unparsed                                                      #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:33)
  unparsed       unparsed                                                      #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:29)
  unparsed       unparsed                                                      #2      parseExpression (package:eqlib/src/parser.dart:269:10)
  unparsed       unparsed                                                      #3      Expr.Expr.parse (package:eqlib/src/expr.dart:26:12)
  unparsed       unparsed                                                      #4      main.<anonymous closure> (file:///home/herman/repos/eqdb/eqlib/test/parse_test.dart:42:16)
  unparsed       unparsed                                                      #5      Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:114:19)
  <asynchronous  suspension>
  unparsed       unparsed                                                      #6      Invoker.waitForOutstandingCallbacks.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:188:17)
  <asynchronous  suspension>
  unparsed       unparsed                                                      #7      _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #8      _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #9      _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #10     runZoned (dart:async/zone.dart:1501)
  unparsed       unparsed                                                      #11     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:185:7)
  unparsed       unparsed                                                      #12     _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #13     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #14     runZoned (dart:async/zone.dart:1503)
  unparsed       unparsed                                                      #15     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:184:5)
  unparsed       unparsed                                                      #16     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:112:29)
  <asynchronous  suspension>
  unparsed       unparsed                                                      #17     Future.Future.<anonymous closure> (dart:async/future.dart:158)
  unparsed       unparsed                                                      #18     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  unparsed       unparsed                                                      #19     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
  unparsed       unparsed                                                      #20     _rootRun (dart:async/zone.dart:1146)
  unparsed       unparsed                                                      #21     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #22     _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
  unparsed       unparsed                                                      #24     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  unparsed       unparsed                                                      #25     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
  unparsed       unparsed                                                      #26     _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #27     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #28     _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
  unparsed       unparsed                                                      #30     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
  unparsed       unparsed                                                      #31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
  unparsed       unparsed                                                      #32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
  unparsed       unparsed                                                      #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
  ===== asynchronous gap ===========================
  unparsed       unparsed                                                      #4      _Completer.completeError (dart:async/future_impl.dart:22)
  unparsed       unparsed                                                      #5      Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:115:8)
  <asynchronous  suspension>
  unparsed       unparsed                                                      #6      Invoker.waitForOutstandingCallbacks.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:188:17)
  <asynchronous  suspension>
  unparsed       unparsed                                                      #7      _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #8      _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #9      _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #10     runZoned (dart:async/zone.dart:1501)
  unparsed       unparsed                                                      #11     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:185:7)
  unparsed       unparsed                                                      #12     _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #13     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #14     runZoned (dart:async/zone.dart:1503)
  unparsed       unparsed                                                      #15     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:184:5)
  unparsed       unparsed                                                      #16     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:112:29)
  <asynchronous  suspension>
  unparsed       unparsed                                                      #17     Future.Future.<anonymous closure> (dart:async/future.dart:158)
  unparsed       unparsed                                                      #18     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  unparsed       unparsed                                                      #19     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
  unparsed       unparsed                                                      #20     _rootRun (dart:async/zone.dart:1146)
  unparsed       unparsed                                                      #21     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #22     _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
  unparsed       unparsed                                                      #24     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  unparsed       unparsed                                                      #25     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
  unparsed       unparsed                                                      #26     _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #27     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #28     _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
  unparsed       unparsed                                                      #30     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
  unparsed       unparsed                                                      #31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
  unparsed       unparsed                                                      #32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
  unparsed       unparsed                                                      #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
  ===== asynchronous gap ===========================
  unparsed       unparsed                                                      #3      _CustomZone.registerUnaryCallback (dart:async/zone.dart:1073)
  unparsed       unparsed                                                      #4      _asyncThenWrapperHelper (dart:async-patch/async_patch.dart:27)
  unparsed       unparsed                                                      #5      Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart)
  unparsed       unparsed                                                      #6      Invoker.waitForOutstandingCallbacks.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:188:17)
  <asynchronous  suspension>
  unparsed       unparsed                                                      #7      _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #8      _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #9      _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #10     runZoned (dart:async/zone.dart:1501)
  unparsed       unparsed                                                      #11     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:185:7)
  unparsed       unparsed                                                      #12     _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #13     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #14     runZoned (dart:async/zone.dart:1503)
  unparsed       unparsed                                                      #15     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:184:5)
  unparsed       unparsed                                                      #16     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:112:29)
  <asynchronous  suspension>
  unparsed       unparsed                                                      #17     Future.Future.<anonymous closure> (dart:async/future.dart:158)
  unparsed       unparsed                                                      #18     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  unparsed       unparsed                                                      #19     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
  unparsed       unparsed                                                      #20     _rootRun (dart:async/zone.dart:1146)
  unparsed       unparsed                                                      #21     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #22     _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
  unparsed       unparsed                                                      #24     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  unparsed       unparsed                                                      #25     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
  unparsed       unparsed                                                      #26     _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #27     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #28     _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
  unparsed       unparsed                                                      #30     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
  unparsed       unparsed                                                      #31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
  unparsed       unparsed                                                      #32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
  unparsed       unparsed                                                      #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
  ===== asynchronous gap ===========================
  unparsed       unparsed                                                      #3      _CustomZone.registerCallback (dart:async/zone.dart:1061)
  unparsed       unparsed                                                      #4      _CustomZone.bindCallback (dart:async/zone.dart:949)
  unparsed       unparsed                                                      #5      scheduleMicrotask (dart:async/schedule_microtask.dart:148)
  unparsed       unparsed                                                      #6      Future.Future.microtask (dart:async/future.dart:182)
  unparsed       unparsed                                                      #7      Invoker.waitForOutstandingCallbacks.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart)
  unparsed       unparsed                                                      #8      _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #9      _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #10     _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #11     runZoned (dart:async/zone.dart:1501)
  unparsed       unparsed                                                      #12     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:185:7)
  unparsed       unparsed                                                      #13     _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #14     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #15     runZoned (dart:async/zone.dart:1503)
  unparsed       unparsed                                                      #16     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:184:5)
  unparsed       unparsed                                                      #17     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:112:29)
  <asynchronous  suspension>
  unparsed       unparsed                                                      #18     Future.Future.<anonymous closure> (dart:async/future.dart:158)
  unparsed       unparsed                                                      #19     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  unparsed       unparsed                                                      #20     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
  unparsed       unparsed                                                      #21     _rootRun (dart:async/zone.dart:1146)
  unparsed       unparsed                                                      #22     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #23     _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
  unparsed       unparsed                                                      #25     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  unparsed       unparsed                                                      #26     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
  unparsed       unparsed                                                      #27     _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #28     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #29     _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
  unparsed       unparsed                                                      #31     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
  unparsed       unparsed                                                      #32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
  unparsed       unparsed                                                      #33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
  unparsed       unparsed                                                      #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
  ===== asynchronous gap ===========================
  unparsed       unparsed                                                      #3      _CustomZone.registerCallback (dart:async/zone.dart:1061)
  unparsed       unparsed                                                      #4      _CustomZone.bindCallback (dart:async/zone.dart:949)
  unparsed       unparsed                                                      #5      Timer.Timer (dart:async/timer.dart:53)
  unparsed       unparsed                                                      #6      Timer.run (dart:async/timer.dart:92)
  unparsed       unparsed                                                      #7      Future.Future (dart:async/future.dart:156)
  unparsed       unparsed                                                      #8      Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:309:13)
  <asynchronous  suspension>
  unparsed       unparsed                                                      #9      _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #10     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #11     _CustomZone.runGuarded (dart:async/zone.dart:924)
  unparsed       unparsed                                                      #12     runZoned (dart:async/zone.dart:1501)
  unparsed       unparsed                                                      #13     runZonedWithValues.<anonymous closure> (package:test/src/utils.dart:202:12)
  unparsed       unparsed                                                      #14     _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #15     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #16     runZoned (dart:async/zone.dart:1503)
  unparsed       unparsed                                                      #17     runZonedWithValues (package:test/src/utils.dart:201:10)
  unparsed       unparsed                                                      #18     Invoker._onRun.<anonymous closure> (package:test/src/backend/invoker.dart:296:7)
  unparsed       unparsed                                                      #19     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:86:24)
  unparsed       unparsed                                                      #20     _rootRun (dart:async/zone.dart:1150)
  unparsed       unparsed                                                      #21     _CustomZone.run (dart:async/zone.dart:1026)
  unparsed       unparsed                                                      #22     runZoned (dart:async/zone.dart:1503)
  unparsed       unparsed                                                      #23     Chain.capture (package:stack_trace/src/chain.dart:84:12)
  unparsed       unparsed                                                      #24     Invoker._onRun (package:test/src/backend/invoker.dart:295:11)
  unparsed       unparsed                                                      #25     LiveTestController._run (package:test/src/backend/live_test_controller.dart:189:11)
  unparsed       unparsed                                                      #26     _LiveTest.run (package:test/src/backend/live_test_controller.dart:40:31)
  unparsed       unparsed                                                      #27     RemoteListener._runLiveTest (package:test/src/runner/remote_listener.dart:197:14)
  unparsed       unparsed                                                      #28     RemoteListener._serializeTest.<anonymous closure> (package:test/src/runner/remote_listener.dart:151:7)
  unparsed       unparsed                                                      #29     _rootRunUnary (dart:async/zone.dart:1158)
  unparsed       unparsed                                                      #30     _CustomZone.runUnary (dart:async/zone.dart:1037)
  unparsed       unparsed                                                      #31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
  unparsed       unparsed                                                      #32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
  unparsed       unparsed                                                      #33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
  unparsed       unparsed                                                      #34     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
  unparsed       unparsed                                                      #35     _StreamController._add (dart:async/stream_controller.dart:635)
  unparsed       unparsed                                                      #36     _StreamController.add (dart:async/stream_controller.dart:581)
  unparsed       unparsed                                                      #37     _rootRunUnary (dart:async/zone.dart:1162)
  unparsed       unparsed                                                      #38     _CustomZone.runUnary (dart:async/zone.dart:1037)
  unparsed       unparsed                                                      #39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
  unparsed       unparsed                                                      #40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
  unparsed       unparsed                                                      #41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
  unparsed       unparsed                                                      #42     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
  unparsed       unparsed                                                      #43     _StreamController._add (dart:async/stream_controller.dart:635)
  unparsed       unparsed                                                      #44     _StreamController.add (dart:async/stream_controller.dart:581)
  unparsed       unparsed                                                      #45     _StreamSinkWrapper.add (dart:async/stream_controller.dart:868)
  unparsed       unparsed                                                      #46     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:120:12)
  unparsed       unparsed                                                      #47     _MultiChannel._MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:137:31)
  unparsed       unparsed                                                      #48     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
  unparsed       unparsed                                                      #49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
  unparsed       unparsed                                                      #50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
  unparsed       unparsed                                                      #51     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
  unparsed       unparsed                                                      #52     _StreamController._add (dart:async/stream_controller.dart:635)
  unparsed       unparsed                                                      #53     _StreamController.add (dart:async/stream_controller.dart:581)
  unparsed       unparsed                                                      #54     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
  unparsed       unparsed                                                      #55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
  unparsed       unparsed                                                      #56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
  unparsed       unparsed                                                      #57     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
  unparsed       unparsed                                                      #58     _StreamController._add (dart:async/stream_controller.dart:635)
  unparsed       unparsed                                                      #59     _StreamController.add (dart:async/stream_controller.dart:581)
  unparsed       unparsed                                                      #60     _StreamSinkWrapper.add (dart:async/stream_controller.dart:868)
  unparsed       unparsed                                                      #61     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
  unparsed       unparsed                                                      #62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
  unparsed       unparsed                                                      #63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
  unparsed       unparsed                                                      #64     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
  unparsed       unparsed                                                      #65     _StreamController._add (dart:async/stream_controller.dart:635)
  unparsed       unparsed                                                      #66     _StreamController.add (dart:async/stream_controller.dart:581)
  unparsed       unparsed                                                      #67     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
  unparsed       unparsed                                                      #68     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
  unparsed       unparsed                                                      #69     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
  unparsed       unparsed                                                      #70     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
  unparsed       unparsed                                                      #71     _StreamController._add (dart:async/stream_controller.dart:635)
  unparsed       unparsed                                                      #72     _StreamController.add (dart:async/stream_controller.dart:581)
  unparsed       unparsed                                                      #73     _StreamSinkWrapper.add (dart:async/stream_controller.dart:868)
  unparsed       unparsed                                                      #74     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
  unparsed       unparsed                                                      #75     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
  unparsed       unparsed                                                      #76     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
  unparsed       unparsed                                                      #77     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
  unparsed       unparsed                                                      #78     _StreamController._add (dart:async/stream_controller.dart:635)
  unparsed       unparsed                                                      #79     _StreamController.add (dart:async/stream_controller.dart:581)
  unparsed       unparsed                                                      #80     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
  
00:01 +24 -1: Some tests failed. 
```

I downgraded to the latest stable version, where stack traces are back to normal, like this:
```
00:01 +12 -1: test/parse_test.dart: Fundamental checks for the parser                              
  'package:eqlib/src/parser.dart': Failed assertion: line 269 pos 10: 'output.length == 1': is not true.
  dart:core                             _AssertionError._throwNew
  package:eqlib/src/parser.dart 269:10  parseExpression
  package:eqlib/src/expr.dart 26:12     Expr.Expr.parse
  test/parse_test.dart 42:16            main.<fn>
  
00:02 +24 -1: Some tests failed.
```

**Comment by anders-sandholm** [comment]
@nex3, please forgive my ignorance, not sure if this is at all related to https://github.com/dart-lang/stack_trace/pull/19 or something entirely different. 

If not related, I'd be grateful for any help figuring out what to best do next.

**Comment by nex3** [comment]
@anders-sandholm That's exactly right, that PR adds support for the VM's new stack trace format.

@hermanbergwerf If you run `pub upgrade stack_trace`, this issue should go away.

**Comment by hermanbergwerf** [comment]
For me this issue is now resolved
