### ISSUE TITLE
[Fasta] NoSuchMethodError: The getter 'fileUri' was called on null

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#28884]
Trying to compile this file:
```dart
var x = () {
  var y = 42;
  return y;
};

main() {
  print(x());
}
```

like this:
```
out/ReleaseX64/dart -DDFE_USE_FASTA=true --packages=.packages --dfe=utils/kernel-service/kernel-service.dart x.dart
```

I get this error:

```
NoSuchMethodError: The getter 'fileUri' was called on null.
Receiver: null
Tried calling: fileUri
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      KernelVariableBuilder.KernelVariableBuilder (package:front_end/src/fasta/kernel/kernel_variable_builder.dart:18:51)
#3      BodyBuilder.endInitializedIdentifier (package:front_end/src/fasta/kernel/body_builder.dart:920:32)
#4      Parser.parseOptionallyInitializedIdentifier (package:front_end/src/fasta/parser/parser.dart:3126:14)
#5      Parser.parseVariablesDeclarationMaybeSemicolon (package:front_end/src/fasta/parser/parser.dart:3106:13)
#6      Parser.parseVariablesDeclaration (package:front_end/src/fasta/parser/parser.dart:3092:12)
#7      Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:2116:14)
#8      Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:2102:20)
#9      Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:2039:15)
#10     Parser.parseUnnamedFunction (package:front_end/src/fasta/parser/parser.dart:1913:13)
#11     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:2668:14)
#12     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:2637:14)
#13     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:2574:15)
#14     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:2450:13)
#15     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:2423:11)
#16     Parser.parseFieldInitializerOpt (package:front_end/src/fasta/parser/parser.dart:1395:15)
#17     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:1215:13)
#18     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:1083:11)
#19     DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:518:22)
#20     DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:421:5)
#21     DietListener.endTopLevelFields (package:front_end/src/fasta/source/diet_listener.dart:231:5)
#22     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:1224:16)
#23     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:1083:11)
#24     Parser._parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:163:14)
#25     Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:139:13)
#26     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:131:15)
#27     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:134:14)
```

**Comment by peter-ahe-google** [comment]
Proposed fix: [CL 2722503003](https://codereview.chromium.org/2722503003).
