### ISSUE TITLE
analyzer_cl/test/driver_test has runtime errors on windows

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28889]
Marking the test as failing.

**Comment by floitschG** [comment]
Here is the stdout:

```
FAILED: none-vm-checked release_x64 pkg/analyzer_cli/test/driver_test
Expected: Pass Slow 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
00:00 +0: Driver options todos
00:04 +1: Driver exit codes fatal hints
00:04 +2: Driver exit codes not fatal hints
00:04 +3: Driver exit codes fatal errors
00:05 +4: Driver exit codes not fatal warnings
00:05 +5: Driver exit codes fatal warnings
00:05 +6: Driver exit codes missing options file
00:05 +7: Driver exit codes missing dart file
00:05 +8: Driver exit codes part file
00:05 +9: Driver exit codes non-dangling part file
00:08 +10: Driver exit codes extra part file
00:08 +11: Driver linter lints in options - old gets analysis options
00:09 +12: Driver linter lints in options - old generates lints
00:09 +13: Driver linter default lints - old gets default lints
00:09 +14: Driver linter default lints - old generates lints
00:09 +15: Driver linter no `--lints` flag (none in options) - old lints disabled
00:09 +16: Driver linter no `--lints` flag (none in options) - old no registered lints
00:09 +17: Driver linter no `--lints` flag (none in options) - old no generated warnings
00:10 +18: Driver linter lints in options - new gets analysis options
00:12 +19: Driver linter lints in options - new generates lints
00:12 +20: Driver linter default lints - new gets default lints
00:12 +21: Driver linter default lints - new generates lints
00:12 +22: Driver linter no `--lints` flag (none in options) - new lints disabled
00:12 +23: Driver linter no `--lints` flag (none in options) - new no registered lints
00:12 +24: Driver linter no `--lints` flag (none in options) - new no generated warnings
00:12 +25: Driver containsLintRuleEntry
00:12 +26: Driver options processing basic config - old filters
00:14 +27: Driver options processing basic config - old language
00:14 +28: Driver options processing basic config - old strongMode
00:14 +29: Driver options processing with flags - old override fatal warning
00:14 +30: Driver options processing basic config - new filters
00:14 +31: Driver options processing basic config - new language
00:14 +32: Driver options processing basic config - new strongMode
00:15 +33: Driver options processing with flags - new override fatal warning
00:15 +34: Driver options processing include directive
00:16 +35: Driver options processing test strong SDK
00:20 +36: Driver build-mode - old no stats
00:20 +36 -1: Driver build-mode - old no stats
  FileSystemException: Exists failed, path = 'file:\test_file.dart|E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\analyzer_cli\test\data\test_file.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
  
  , errno = 123)
  dart:io                                                        _Directory.existsSync
  package:analyzer/file_system/physical_file_system.dart 323:29  _PhysicalResource.exists
  package:analyzer/src/context/builder.dart 512:17               ContextBuilder._findPackagesLocation
  package:analyzer/src/context/builder.dart 283:25               ContextBuilder.findPackagesFromFile
  package:analyzer/src/context/builder.dart 224:12               ContextBuilder.createPackageMap
  package:analyzer/src/context/builder.dart 749:28               _BasicWorkspace.packages
  package:analyzer/src/context/builder.dart 744:51               _BasicWorkspace.packageMap
  package:analyzer/src/context/builder.dart 755:43               _BasicWorkspace.packageUriResolver
  package:analyzer/src/context/builder.dart 763:19               _BasicWorkspace.createSourceFactory
  package:analyzer/src/context/builder.dart 375:45               ContextBuilder.getAnalysisOptions
  package:analyzer_cli/src/driver.dart 745:10                    Driver.createAnalysisOptionsForCommandLineOptions
  package:analyzer_cli/src/build_mode.dart 250:18                BuildMode._createContext
  package:analyzer_cli/src/build_mode.dart 163:5                 BuildMode.analyze
  package:analyzer_cli/src/driver.dart 290:64                    Driver._buildModeAnalyze.<fn>
  package:analyzer/src/generated/utilities_general.dart 189:15   _PerformanceTagImpl.makeCurrentWhile
  package:analyzer_cli/src/driver.dart 284:27                    Driver._buildModeAnalyze
  package:analyzer_cli/src/driver.dart 135:32                    Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 351:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     _Completer.completeError
  package:analyzer_cli/src/driver.dart 164:3                     Driver.start
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  package:analyzer_cli/src/driver.dart                           Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 351:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.<fn>
  package:test                                                   Declarer.test.<fn>.<fn>
  
00:20 +36 -1: Driver build-mode - old Fails if file not found, even when --build-suppress-exit-code is given
00:20 +36 -2: Driver build-mode - old Fails if file not found, even when --build-suppress-exit-code is given
  FileSystemException: Exists failed, path = 'file:\test_file.dart|E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\analyzer_cli\test\data\non_existent_file.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
  
  , errno = 123)
  dart:io                                                        _Directory.existsSync
  package:analyzer/file_system/physical_file_system.dart 323:29  _PhysicalResource.exists
  package:analyzer/src/context/builder.dart 512:17               ContextBuilder._findPackagesLocation
  package:analyzer/src/context/builder.dart 283:25               ContextBuilder.findPackagesFromFile
  package:analyzer/src/context/builder.dart 224:12               ContextBuilder.createPackageMap
  package:analyzer/src/context/builder.dart 749:28               _BasicWorkspace.packages
  package:analyzer/src/context/builder.dart 744:51               _BasicWorkspace.packageMap
  package:analyzer/src/context/builder.dart 755:43               _BasicWorkspace.packageUriResolver
  package:analyzer/src/context/builder.dart 763:19               _BasicWorkspace.createSourceFactory
  package:analyzer/src/context/builder.dart 375:45               ContextBuilder.getAnalysisOptions
  package:analyzer_cli/src/driver.dart 745:10                    Driver.createAnalysisOptionsForCommandLineOptions
  package:analyzer_cli/src/build_mode.dart 250:18                BuildMode._createContext
  package:analyzer_cli/src/build_mode.dart 163:5                 BuildMode.analyze
  package:analyzer_cli/src/driver.dart 290:64                    Driver._buildModeAnalyze.<fn>
  package:analyzer/src/generated/utilities_general.dart 189:15   _PerformanceTagImpl.makeCurrentWhile
  package:analyzer_cli/src/driver.dart 284:27                    Driver._buildModeAnalyze
  package:analyzer_cli/src/driver.dart 135:32                    Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 361:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     _Completer.completeError
  package:analyzer_cli/src/driver.dart 164:3                     Driver.start
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  package:analyzer_cli/src/driver.dart                           Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 361:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.<fn>
  package:test                                                   Declarer.test.<fn>.<fn>
  
00:20 +36 -2: Driver build-mode - old Fails if there are errors
00:20 +36 -3: Driver build-mode - old Fails if there are errors
  FileSystemException: Exists failed, path = 'file:\test_file.dart|E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\analyzer_cli\test\data\file_with_error.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
  
  , errno = 123)
  dart:io                                                        _Directory.existsSync
  package:analyzer/file_system/physical_file_system.dart 323:29  _PhysicalResource.exists
  package:analyzer/src/context/builder.dart 512:17               ContextBuilder._findPackagesLocation
  package:analyzer/src/context/builder.dart 283:25               ContextBuilder.findPackagesFromFile
  package:analyzer/src/context/builder.dart 224:12               ContextBuilder.createPackageMap
  package:analyzer/src/context/builder.dart 749:28               _BasicWorkspace.packages
  package:analyzer/src/context/builder.dart 744:51               _BasicWorkspace.packageMap
  package:analyzer/src/context/builder.dart 755:43               _BasicWorkspace.packageUriResolver
  package:analyzer/src/context/builder.dart 763:19               _BasicWorkspace.createSourceFactory
  package:analyzer/src/context/builder.dart 375:45               ContextBuilder.getAnalysisOptions
  package:analyzer_cli/src/driver.dart 745:10                    Driver.createAnalysisOptionsForCommandLineOptions
  package:analyzer_cli/src/build_mode.dart 250:18                BuildMode._createContext
  package:analyzer_cli/src/build_mode.dart 163:5                 BuildMode.analyze
  package:analyzer_cli/src/driver.dart 290:64                    Driver._buildModeAnalyze.<fn>
  package:analyzer/src/generated/utilities_general.dart 189:15   _PerformanceTagImpl.makeCurrentWhile
  package:analyzer_cli/src/driver.dart 284:27                    Driver._buildModeAnalyze
  package:analyzer_cli/src/driver.dart 135:32                    Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 367:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     _Completer.completeError
  package:analyzer_cli/src/driver.dart 164:3                     Driver.start
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  package:analyzer_cli/src/driver.dart                           Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 367:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.<fn>
  package:test                                                   Declarer.test.<fn>.<fn>
  
00:20 +36 -3: Driver build-mode - old Succeeds if there are errors, when --build-suppress-exit-code is given
00:20 +36 -4: Driver build-mode - old Succeeds if there are errors, when --build-suppress-exit-code is given
  FileSystemException: Exists failed, path = 'file:\test_file.dart|E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\analyzer_cli\test\data\file_with_error.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
  
  , errno = 123)
  dart:io                                                        _Directory.existsSync
  package:analyzer/file_system/physical_file_system.dart 323:29  _PhysicalResource.exists
  package:analyzer/src/context/builder.dart 512:17               ContextBuilder._findPackagesLocation
  package:analyzer/src/context/builder.dart 283:25               ContextBuilder.findPackagesFromFile
  package:analyzer/src/context/builder.dart 224:12               ContextBuilder.createPackageMap
  package:analyzer/src/context/builder.dart 749:28               _BasicWorkspace.packages
  package:analyzer/src/context/builder.dart 744:51               _BasicWorkspace.packageMap
  package:analyzer/src/context/builder.dart 755:43               _BasicWorkspace.packageUriResolver
  package:analyzer/src/context/builder.dart 763:19               _BasicWorkspace.createSourceFactory
  package:analyzer/src/context/builder.dart 375:45               ContextBuilder.getAnalysisOptions
  package:analyzer_cli/src/driver.dart 745:10                    Driver.createAnalysisOptionsForCommandLineOptions
  package:analyzer_cli/src/build_mode.dart 250:18                BuildMode._createContext
  package:analyzer_cli/src/build_mode.dart 163:5                 BuildMode.analyze
  package:analyzer_cli/src/driver.dart 290:64                    Driver._buildModeAnalyze.<fn>
  package:analyzer/src/generated/utilities_general.dart 189:15   _PerformanceTagImpl.makeCurrentWhile
  package:analyzer_cli/src/driver.dart 284:27                    Driver._buildModeAnalyze
  package:analyzer_cli/src/driver.dart 135:32                    Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 374:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     _Completer.completeError
  package:analyzer_cli/src/driver.dart 164:3                     Driver.start
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  package:analyzer_cli/src/driver.dart                           Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 374:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.<fn>
  package:test                                                   Declarer.test.<fn>.<fn>
  
00:20 +36 -4: Driver build-mode - new no stats
00:20 +36 -5: Driver build-mode - new no stats
  FileSystemException: Exists failed, path = 'file:\test_file.dart|E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\analyzer_cli\test\data\test_file.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
  
  , errno = 123)
  dart:io                                                        _Directory.existsSync
  package:analyzer/file_system/physical_file_system.dart 323:29  _PhysicalResource.exists
  package:analyzer/src/context/builder.dart 512:17               ContextBuilder._findPackagesLocation
  package:analyzer/src/context/builder.dart 283:25               ContextBuilder.findPackagesFromFile
  package:analyzer/src/context/builder.dart 224:12               ContextBuilder.createPackageMap
  package:analyzer/src/context/builder.dart 749:28               _BasicWorkspace.packages
  package:analyzer/src/context/builder.dart 744:51               _BasicWorkspace.packageMap
  package:analyzer/src/context/builder.dart 755:43               _BasicWorkspace.packageUriResolver
  package:analyzer/src/context/builder.dart 763:19               _BasicWorkspace.createSourceFactory
  package:analyzer/src/context/builder.dart 375:45               ContextBuilder.getAnalysisOptions
  package:analyzer_cli/src/driver.dart 745:10                    Driver.createAnalysisOptionsForCommandLineOptions
  package:analyzer_cli/src/build_mode.dart 250:18                BuildMode._createContext
  package:analyzer_cli/src/build_mode.dart 163:5                 BuildMode.analyze
  package:analyzer_cli/src/driver.dart 290:64                    Driver._buildModeAnalyze.<fn>
  package:analyzer/src/generated/utilities_general.dart 189:15   _PerformanceTagImpl.makeCurrentWhile
  package:analyzer_cli/src/driver.dart 284:27                    Driver._buildModeAnalyze
  package:analyzer_cli/src/driver.dart 135:32                    Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 351:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     _Completer.completeError
  package:analyzer_cli/src/driver.dart 164:3                     Driver.start
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  package:analyzer_cli/src/driver.dart                           Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 351:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.<fn>
  package:test                                                   Declarer.test.<fn>.<fn>
  
00:21 +36 -5: Driver build-mode - new Fails if file not found, even when --build-suppress-exit-code is given
00:21 +36 -6: Driver build-mode - new Fails if file not found, even when --build-suppress-exit-code is given
  FileSystemException: Exists failed, path = 'file:\test_file.dart|E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\analyzer_cli\test\data\non_existent_file.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
  
  , errno = 123)
  dart:io                                                        _Directory.existsSync
  package:analyzer/file_system/physical_file_system.dart 323:29  _PhysicalResource.exists
  package:analyzer/src/context/builder.dart 512:17               ContextBuilder._findPackagesLocation
  package:analyzer/src/context/builder.dart 283:25               ContextBuilder.findPackagesFromFile
  package:analyzer/src/context/builder.dart 224:12               ContextBuilder.createPackageMap
  package:analyzer/src/context/builder.dart 749:28               _BasicWorkspace.packages
  package:analyzer/src/context/builder.dart 744:51               _BasicWorkspace.packageMap
  package:analyzer/src/context/builder.dart 755:43               _BasicWorkspace.packageUriResolver
  package:analyzer/src/context/builder.dart 763:19               _BasicWorkspace.createSourceFactory
  package:analyzer/src/context/builder.dart 375:45               ContextBuilder.getAnalysisOptions
  package:analyzer_cli/src/driver.dart 745:10                    Driver.createAnalysisOptionsForCommandLineOptions
  package:analyzer_cli/src/build_mode.dart 250:18                BuildMode._createContext
  package:analyzer_cli/src/build_mode.dart 163:5                 BuildMode.analyze
  package:analyzer_cli/src/driver.dart 290:64                    Driver._buildModeAnalyze.<fn>
  package:analyzer/src/generated/utilities_general.dart 189:15   _PerformanceTagImpl.makeCurrentWhile
  package:analyzer_cli/src/driver.dart 284:27                    Driver._buildModeAnalyze
  package:analyzer_cli/src/driver.dart 135:32                    Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 361:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     _Completer.completeError
  package:analyzer_cli/src/driver.dart 164:3                     Driver.start
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  package:analyzer_cli/src/driver.dart                           Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 361:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.<fn>
  package:test                                                   Declarer.test.<fn>.<fn>
  
00:21 +36 -6: Driver build-mode - new Fails if there are errors
00:21 +36 -7: Driver build-mode - new Fails if there are errors
  FileSystemException: Exists failed, path = 'file:\test_file.dart|E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\analyzer_cli\test\data\file_with_error.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
  
  , errno = 123)
  dart:io                                                        _Directory.existsSync
  package:analyzer/file_system/physical_file_system.dart 323:29  _PhysicalResource.exists
  package:analyzer/src/context/builder.dart 512:17               ContextBuilder._findPackagesLocation
  package:analyzer/src/context/builder.dart 283:25               ContextBuilder.findPackagesFromFile
  package:analyzer/src/context/builder.dart 224:12               ContextBuilder.createPackageMap
  package:analyzer/src/context/builder.dart 749:28               _BasicWorkspace.packages
  package:analyzer/src/context/builder.dart 744:51               _BasicWorkspace.packageMap
  package:analyzer/src/context/builder.dart 755:43               _BasicWorkspace.packageUriResolver
  package:analyzer/src/context/builder.dart 763:19               _BasicWorkspace.createSourceFactory
  package:analyzer/src/context/builder.dart 375:45               ContextBuilder.getAnalysisOptions
  package:analyzer_cli/src/driver.dart 745:10                    Driver.createAnalysisOptionsForCommandLineOptions
  package:analyzer_cli/src/build_mode.dart 250:18                BuildMode._createContext
  package:analyzer_cli/src/build_mode.dart 163:5                 BuildMode.analyze
  package:analyzer_cli/src/driver.dart 290:64                    Driver._buildModeAnalyze.<fn>
  package:analyzer/src/generated/utilities_general.dart 189:15   _PerformanceTagImpl.makeCurrentWhile
  package:analyzer_cli/src/driver.dart 284:27                    Driver._buildModeAnalyze
  package:analyzer_cli/src/driver.dart 135:32                    Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 367:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     _Completer.completeError
  package:analyzer_cli/src/driver.dart 164:3                     Driver.start
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  package:analyzer_cli/src/driver.dart                           Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 367:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.<fn>
  package:test                                                   Declarer.test.<fn>.<fn>
  
00:21 +36 -7: Driver build-mode - new Succeeds if there are errors, when --build-suppress-exit-code is given
00:21 +36 -8: Driver build-mode - new Succeeds if there are errors, when --build-suppress-exit-code is given
  FileSystemException: Exists failed, path = 'file:\test_file.dart|E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\analyzer_cli\test\data\file_with_error.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
  
  , errno = 123)
  dart:io                                                        _Directory.existsSync
  package:analyzer/file_system/physical_file_system.dart 323:29  _PhysicalResource.exists
  package:analyzer/src/context/builder.dart 512:17               ContextBuilder._findPackagesLocation
  package:analyzer/src/context/builder.dart 283:25               ContextBuilder.findPackagesFromFile
  package:analyzer/src/context/builder.dart 224:12               ContextBuilder.createPackageMap
  package:analyzer/src/context/builder.dart 749:28               _BasicWorkspace.packages
  package:analyzer/src/context/builder.dart 744:51               _BasicWorkspace.packageMap
  package:analyzer/src/context/builder.dart 755:43               _BasicWorkspace.packageUriResolver
  package:analyzer/src/context/builder.dart 763:19               _BasicWorkspace.createSourceFactory
  package:analyzer/src/context/builder.dart 375:45               ContextBuilder.getAnalysisOptions
  package:analyzer_cli/src/driver.dart 745:10                    Driver.createAnalysisOptionsForCommandLineOptions
  package:analyzer_cli/src/build_mode.dart 250:18                BuildMode._createContext
  package:analyzer_cli/src/build_mode.dart 163:5                 BuildMode.analyze
  package:analyzer_cli/src/driver.dart 290:64                    Driver._buildModeAnalyze.<fn>
  package:analyzer/src/generated/utilities_general.dart 189:15   _PerformanceTagImpl.makeCurrentWhile
  package:analyzer_cli/src/driver.dart 284:27                    Driver._buildModeAnalyze
  package:analyzer_cli/src/driver.dart 135:32                    Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 374:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     _Completer.completeError
  package:analyzer_cli/src/driver.dart 164:3                     Driver.start
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  package:analyzer_cli/src/driver.dart                           Driver.start
  pkg\analyzer_cli\test\driver_test.dart 478:16                  drive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         drive
  pkg\analyzer_cli\test\driver_test.dart 340:17                  main.<fn>.createTests.<fn>.doDrive
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.doDrive
  pkg\analyzer_cli\test\driver_test.dart 374:24                  main.<fn>.createTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.microtask
  pkg\analyzer_cli\test\driver_test.dart                         main.<fn>.createTests.<fn>.<fn>
  package:test                                                   Declarer.test.<fn>.<fn>
  
00:21 +36 -8: Some tests failed.



stderr:
Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1138)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:396)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: set DART_CONFIGURATION=ReleaseX64 & out\ReleaseX64\dart-sdk\bin\dart.exe --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=E:\b\build\slave\analyzer-win7-release-be\build\sdk\.packages E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\analyzer_cli\test\driver_test.dart
Took 0:00:22.347235

Short reproduction command (experimental):
    python tools/test.py -mrelease --checked -t60 --use-sdk --builder-tag win7 pkg/analyzer_cli/test/driver_test
```

**Comment by bwilkerson** [comment]
I have a fix that I'll commit in a couple of minutes.

**Comment by floitschG** [comment]
Great.
The status file change is in a single commit. You should be able to just revert it.

**Comment by bwilkerson** [comment]
@stereotype441 I'm fairly certain the bug is in `driver_test.dart` in the function `adjustFileSpec` (https://github.com/dart-lang/sdk/blob/master/pkg/analyzer_cli/test/driver_test.dart#L458), but I'm not sure what this function is suppose to be doing, so I'm not sure how to fix it.

**Comment by stereotype441** [comment]
The purpose of the function `adjustFileSpec` is to convert a file path that is relative to analyzer_cli's `test` directory to an absolute path, e.g. it converts `data/file_with_warning.dart` to `/home/username/dart/sdk/pkg/analyzer_cli/test/data/file_with_warning.dart`.

But there's some extra logic to handle the fact that analyzer_cli's build mode accepts arguments of the form `$uri|$path`, so in that case it converts just the "path" part and leaves the URI alone.

**Comment by danrubel** [comment]
Suggested fix: https://codereview.chromium.org/2720493002/
