### ISSUE TITLE
Racy stack corruption in deopt?

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#28890]
From the IA32 opt counter bot. Looks like a frame doesn't have a Code object where one is expected.

```
FAILED: none-vm release_ia32 co19/LibTest/isolate/ReceivePort/toList_A01_t01
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
Dumping native stack trace for thread 1a98
  [0x085a24ed] dart::StackFrame::IsStubFrame() const
  [0x085a24ed] dart::StackFrame::IsStubFrame() const
  [0x08603afe] DLRT_DeoptimizeFillFrame
  [0xf72879b6] [Stub] Deoptimize
  [0xf68e8668] _handlePackagesRequest
  [0xf6cab026] _Closure.call
  [0xf6cccc99] Future.Future.microtask.<anonymous closure>
  [0xf68e0439] _startMicrotaskLoop
  [0xf68e031e] _startMicrotaskLoop
  [0xf68dc3f1] _RawReceivePortImpl._handleMessage
  [0xf7287684] [Stub] InvokeDartCode
  [0x08324170] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned int)
  [0x08324f1d] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
  [0x08327a3f] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  [0x0841537a] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x0843722f] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x0843770a] dart::MessageHandler::TaskCallback()
-- End of DumpStackTrace


Command[vm]: DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/tests/co19/src/LibTest/isolate/ReceivePort/toList_A01_t01.dart
Took 0:00:01.337355

Short reproduction command (experimental):
    python tools/test.py -mrelease -aia32 -t60 --vm-options --optimization-counter-threshold=5 co19/LibTest/isolate/ReceivePort/toList_A01_t01
```

```
#0  0xf774a440 in __kernel_vsyscall ()
#1  0xf743a687 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf743dab3 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x0815c826 in dart::bin::segv_handler (signal=11, siginfo=0xf55f3c4c, 
    context=0xf55f3ccc) at ../../runtime/bin/platform_linux.cc:27
#4  <signal handler called>
#5  GetClassId (
    this=<error reading variable: Cannot access memory at address 0x46505858>)
    at ../../runtime/vm/raw_object.h:528
#6  dart::StackFrame::IsStubFrame (this=0xf55f419c)
    at ../../runtime/vm/stack_frame.cc:32
#7  0x085a2794 in dart::StackFrame::IsDartFrame (this=0xf55f419c, 
    validate=false) at ../../runtime/vm/stack_frame.h:93
#8  0x08603afe in NextFrame (this=0xf55f4160)
    at ../../runtime/vm/stack_frame.h:320
#9  dart::DLRT_DeoptimizeFillFrame (last_fp=4116662332)
    at ../../runtime/vm/code_generator.cc:2138
#10 0xf72879b6 in ?? ()
#11 0xf68e8668 in ?? ()
#12 0xf6cab026 in ?? ()
#13 0xf6cccc99 in ?? ()
#14 0xf68e0439 in ?? ()
#15 0xf68e031e in ?? ()
#16 0xf68dc3f1 in ?? ()
#17 0xf7287684 in ?? ()
#18 0x08324170 in dart::DartEntry::InvokeFunction (function=..., arguments=..., 
    arguments_descriptor=..., current_sp=4116662688)
    at ../../runtime/vm/dart_entry.cc:125
#19 0x08324f1d in dart::DartEntry::InvokeFunction (function=..., arguments=...)
    at ../../runtime/vm/dart_entry.cc:29
#20 0x08327a3f in dart::DartLibraryCalls::HandleMessage (handler=..., 
    message=...) at ../../runtime/vm/dart_entry.cc:557
#21 0x0841537a in dart::IsolateMessageHandler::HandleMessage (this=0xbba01b0, 
    message=0xb12dd20) at ../../runtime/vm/isolate.cc:577
#22 0x0843722f in dart::MessageHandler::HandleMessages (
    this=this@entry=0xbba01b0, ml=ml@entry=0xf55f5210, 
    allow_normal_messages=true, 
    allow_multiple_normal_messages=allow_multiple_normal_messages@entry=true)
    at ../../runtime/vm/message_handler.cc:217
#23 0x0843770a in dart::MessageHandler::TaskCallback (this=0xbba01b0)
    at ../../runtime/vm/message_handler.cc:375
#24 0x085bcb4e in dart::ThreadPool::Worker::Loop (this=this@entry=0xb134d90)
    at ../../runtime/vm/thread_pool.cc:402
#25 0x085bcc95 in dart::ThreadPool::Worker::Main (args=args@entry=185814416)
    at ../../runtime/vm/thread_pool.cc:459
#26 0x084b55b2 in dart::ThreadStart (data_ptr=0xb12b120)
    at ../../runtime/vm/os_thread_linux.cc:125
#27 0xf7716f72 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#28 0xf74f7f8e in clone () from /lib/i386-linux-gnu/libc.so.6
``` 

```
bool StackFrame::IsStubFrame() const {
  ASSERT(!(IsEntryFrame() || IsExitFrame()));
#if !defined(TARGET_OS_WINDOWS)
  // On Windows, the profiler calls this from a separate thread where
  // Thread::Current() is NULL, so we cannot create a NoSafepointScope.
  NoSafepointScope no_safepoint;
#endif
  RawCode* code = GetCodeObject();
  ASSERT(code != Object::null());
  const intptr_t cid = code->ptr()->owner_->GetClassId();  <<<<<<<<<<<<<<<<<<
  ASSERT(cid == kNullCid || cid == kClassCid || cid == kFunctionCid);
  return cid == kNullCid || cid == kClassCid;
}
```

**Comment by mraleph** [comment]
Assuming this is stale.
