### ISSUE TITLE
Hit an analyzer crash during code completion

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#28891]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.3224.1`
- `1.22.0`
- `IC-171.3224.1, JRE 1.8.0_112-release-b702x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-62-lowlatency unknown, screens 1366x768`

## Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.22.0, server version 1.17.0, error: Failed to handle completion domain request: {clientRequestTime: 1487962859048, params: {file: /home/dwayne/roboto-bot/lib/src/daemon.dart, offset: 2111}, method: completion.getSuggestions, id: 12081}
AnalysisException: failed to resolve expression
Caused by Unexpected exception while performing PartiallyResolveUnitReferencesTask for source /home/dwayne/.pub-cache/hosted/pub.dartlang.org/async-1.13.2/lib/src/stream_queue.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by NoSuchMethodError: The method 'substitute2' was called on null.
Receiver: null
Tried calling: substitute2(_List len:1, _List len:1)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      MethodMember.from (package:analyzer/src/dart/element/member.dart:649)
#3      InterfaceTypeImpl.getMethod (package:analyzer/src/dart/element/type.dart:1542)
#4      InterfaceTypeImpl.lookUpMethod (package:analyzer/src/dart/element/type.dart:1832)
#5      InterfaceTypeImpl.lookUpInheritedGetterOrMethod (package:analyzer/src/dart/element/type.dart:1785)
#6      ElementResolver._lookupGetterOrMethod (package:analyzer/src/generated/element_resolver.dart:1746)
#7      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:293)
#8      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2330)
#9      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:5698)
#10     CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2330)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#12     CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2252)
#13     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6374)
#14     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4704)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
