### ISSUE TITLE
dart2js: Assert generating is-test information for resolution-unreached call method

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#28894]
This test case hits an assertion.

```sh
DART_VM_OPTIONS='--checked' sdk/bin/dart2js ~/play1/bug6j3n.dart
```

```dart
class I {
  call(a1,a2,a3,a4,a5) {}
}

typedef f5(p1,p2,p3,p4,p5);

main() {
  var x = new I();
  print(x is f5);
}
```

In production mode, it 'works' because dart2js tests the result against null (i.e. the same result that when null causes `getClosureToClassMapping` to assert).

The call needs to be guarded against methods omitted during resolution.

```dart
    void generateFunctionTypeSignature(
        FunctionElement method, ResolutionFunctionType type) {
      assert(method.isImplementation);
      jsAst.Expression thisAccess = new jsAst.This();
      if (!method.isAbstract) {
        ClosureClassMap closureData = compiler.closureToClassMapper
            .getClosureToClassMapping(method.resolvedAst);
        if (closureData != null) {
```

----
```
bug.dart:2:3:
Internal Error: No ClosureClassMap computed for function(I#call).
  call(a1,a2,a3,a4,a5) {}
  ^^^^^^^^^^^^^^^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Assertion failure: No ClosureClassMap computed for function(I#call).
#0      invariant (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:60:5)
#1      ClosureTask.getClosureToClassMapping.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/closure.dart:47:14)
#2      CompilerTask.measure (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#3      ClosureTask.getClosureToClassMapping (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/closure.dart:40:12)
#4      RuntimeTypeGenerator.generateIsTests.generateFunctionTypeSignature (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_emitter/runtime_type_generator.dart:114:14)
#5      RuntimeTypeGenerator._generateIsTestsOn (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_emitter/runtime_type_generator.dart:289:38)
#6      RuntimeTypeGenerator.generateIsTests (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_emitter/runtime_type_generator.dart:167:5)
#7      ProgramBuilder._buildClass (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_emitter/program_builder/program_builder.dart:575:57)
#8      List.forEach (dart:core-patch/growable_array.dart:258)
#9      ProgramBuilder.buildProgram.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_emitter/program_builder/program_builder.dart:135:15)
#10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:351)
#11     ProgramBuilder.buildProgram (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_emitter/program_builder/program_builder.dart:134:10)
#12     Emitter.emitProgram (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_emitter/full_emitter/emitter.dart:1604:24)
#13     CodeEmitterTask.assembleProgram.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_emitter/code_emitter_task.dart:180:26)
#14     CompilerTask.measure (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#15     CodeEmitterTask.assembleProgram (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_emitter/code_emitter_task.dart:176:12)
#16     JavaScriptBackend.assembleProgram (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/backend.dart:1085:31)
#17     Compiler.compileLoadedLibraries.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:694:35)
#18     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#19     Compiler.compileLoadedLibraries (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:579:16)
#20     Compiler.runInternal.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:487:7)
#21     _RootZone.runUnary (dart:async/zone.dart:1404)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#23     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#24     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#25     _Future._completeWithValue (dart:async/future_impl.dart:477)
#26     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

**Comment by rakudrama** [comment]
Johnni - what is the correct way to strengthen the guard 'is abstract' to include 'proven uncalled in resolution'?
