### ISSUE TITLE
app_jit-vm debug_x64 flakyness in several tests

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#28901]
Since Feb 26 09:20, the build bot app-linux-debug-x64-be has had several failures similar to the following:

```
FAILED: app_jit-vm debug_x64 service/command_test
Expected: Pass 
Actual: Crash
Unexpected compile-time error.
CommandOutput[app_jit]:
..
All 6 tests passed.
unittest-suite-success


Command[app_jit]: .. /b/build/slave/app-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/command_test.dart
Took 0:00:03.398768

Command[vm]: .. /b/build/slave/app-linux-debug-x64-be/build/sdk/out/DebugX64/generated_compilations/app_jit/runtime_observatory_tests_service_command_test/out.jitsnapshot
Did not run

Short reproduction command (experimental):
    python tools/test.py -capp_jit -t240 --builder-tag no_ipv6 service/command_test
```

It is a new test each time, but the failure has the same shape (always unexpected compile-time error), which makes it look like a vm issue rather than a problem with the concrete tests where this failure occurs.

**Comment by a-siva** [comment]
@rmacnak-google

**Comment by rmacnak-google** [comment]
Core dumps for the two most recent failures of app-jit look like a double-free in the malloc hooks shutdown. @bkonyi 

```
FAILED: app_jit-vm debug_x64 co19/LibTest/core/DateTime/parse_A01_t04
Expected: Pass 
Actual: Crash
CommandOutput[app_jit]:
CommandOutput[vm]:

Command[app_jit]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --snapshot=/b/build/slave/app-linux-debug-x64-be/build/sdk/out/DebugX64/generated_compilations/app_jit/tests_co19_src_LibTest_core_DateTime_parse_A01_t04/out.jitsnapshot --snapshot-kind=app-jit --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-debug-x64-be/build/sdk/.packages /b/build/slave/app-linux-debug-x64-be/build/sdk/tests/co19/src/LibTest/core/DateTime/parse_A01_t04.dart
Took 0:00:02.001909

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-debug-x64-be/build/sdk/.packages /b/build/slave/app-linux-debug-x64-be/build/sdk/out/DebugX64/generated_compilations/app_jit/tests_co19_src_LibTest_core_DateTime_parse_A01_t04/out.jitsnapshot
Took 0:00:01.153452

Short reproduction command (experimental):
    python tools/test.py -capp_jit -t240 --builder-tag no_ipv6 co19/LibTest/core/DateTime/parse_A01_t04

--- Uploading into gs://dart-temp-crash-archive/d12d1df9-e61c-48bf-8b57-806f0c0e2a41/ (https://storage.cloud.google.com/dart-temp-crash-archive/d12d1df9-e61c-48bf-8b57-806f0c0e2a41/) ---
Running command:  ['/b/build/scripts/slave/gsutil', 'cp', 'debug_x64_dart.tar.gz', 'gs://dart-temp-crash-archive/d12d1df9-e61c-48bf-8b57-806f0c0e2a41/debug_x64_dart.tar.gz']
+++ Uploaded gs://dart-temp-crash-archive/d12d1df9-e61c-48bf-8b57-806f0c0e2a41/debug_x64_dart.tar.gz (https://storage.cloud.google.com/dart-temp-crash-archive/d12d1df9-e61c-48bf-8b57-806f0c0e2a41/debug_x64_dart.tar.gz)
Running command:  ['/b/build/scripts/slave/gsutil', 'cp', 'core.12824.tar.gz', 'gs://dart-temp-crash-archive/d12d1df9-e61c-48bf-8b57-806f0c0e2a41/core.12824.tar.gz']
+++ Uploaded gs://dart-temp-crash-archive/d12d1df9-e61c-48bf-8b57-806f0c0e2a41/core.12824.tar.gz (https://storage.cloud.google.com/dart-temp-crash-archive/d12d1df9-e61c-48bf-8b57-806f0c0e2a41/core.12824.tar.gz)

Program terminated with signal SIGABRT, Aborted.
#0  0x00007f5c3057ec37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f5c3057ec37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f5c30582028 in __GI_abort () at abort.c:89
#2  0x0000000000536ba1 in dart::bin::segv_handler (signal=<optimized out>, 
    siginfo=<optimized out>, context=<optimized out>)
    at ../../runtime/bin/platform_linux.cc:27
#3  <signal handler called>
#4  Next (this=<optimized out>) at ../../runtime/vm/hash_map.h:178
#5  dart::AddressMap::Clear (this=<optimized out>)
    at ../../runtime/vm/malloc_hooks.cc:214
#6  0x0000000000855902 in ResetStats () at ../../runtime/vm/malloc_hooks.cc:251
#7  dart::MallocHooksState::TearDown () at ../../runtime/vm/malloc_hooks.cc:259
#8  0x000000000085620a in dart::MallocHooks::TearDown ()
    at ../../runtime/vm/malloc_hooks.cc:299
#9  0x000000000070c56e in dart::Dart::Cleanup () at ../../runtime/vm/dart.cc:495
#10 0x000000000065ec4b in Dart_Cleanup ()
    at ../../runtime/vm/dart_api_impl.cc:1203
#11 0x000000000052f6d5 in dart::bin::main (argc=<optimized out>, 
    argv=<optimized out>) at ../../runtime/bin/main.cc:1718
#12 0x000000000052fe29 in main (argc=29, argv=0x98d20)
    at ../../runtime/bin/main.cc:1752
```


```
FAILED: app_jit-vm debug_x64 service/command_test
Expected: Pass 
Actual: Crash
Unexpected compile-time error.
CommandOutput[app_jit]:

stdout:
unittest-suite-wait-for-done
PASS: command completion test suite
PASS: run a simple command
PASS: run a subcommand
PASS: run a command which is not found
PASS: run a command which is ambiguous
PASS: run a command using an alias

All 6 tests passed.
unittest-suite-success


Command[app_jit]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --snapshot=/b/build/slave/app-linux-debug-x64-be/build/sdk/out/DebugX64/generated_compilations/app_jit/runtime_observatory_tests_service_command_test/out.jitsnapshot --snapshot-kind=app-jit --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-debug-x64-be/build/sdk/.packages /b/build/slave/app-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/command_test.dart
Took 0:00:03.398768

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-debug-x64-be/build/sdk/.packages /b/build/slave/app-linux-debug-x64-be/build/sdk/out/DebugX64/generated_compilations/app_jit/runtime_observatory_tests_service_command_test/out.jitsnapshot
Did not run

Short reproduction command (experimental):
    python tools/test.py -capp_jit -t240 --builder-tag no_ipv6 service/command_test

--- Uploading into gs://dart-temp-crash-archive/1c071e79-2ad9-4785-8a73-a9d3703fff67/ (https://storage.cloud.google.com/dart-temp-crash-archive/1c071e79-2ad9-4785-8a73-a9d3703fff67/) ---
Running command:  ['/b/build/scripts/slave/gsutil', 'cp', 'debug_x64_dart.tar.gz', 'gs://dart-temp-crash-archive/1c071e79-2ad9-4785-8a73-a9d3703fff67/debug_x64_dart.tar.gz']
+++ Uploaded gs://dart-temp-crash-archive/1c071e79-2ad9-4785-8a73-a9d3703fff67/debug_x64_dart.tar.gz (https://storage.cloud.google.com/dart-temp-crash-archive/1c071e79-2ad9-4785-8a73-a9d3703fff67/debug_x64_dart.tar.gz)
Running command:  ['/b/build/scripts/slave/gsutil', 'cp', 'core.12118.tar.gz', 'gs://dart-temp-crash-archive/1c071e79-2ad9-4785-8a73-a9d3703fff67/core.12118.tar.gz']
+++ Uploaded gs://dart-temp-crash-archive/1c071e79-2ad9-4785-8a73-a9d3703fff67/core.12118.tar.gz (https://storage.cloud.google.com/dart-temp-crash-archive/1c071e79-2ad9-4785-8a73-a9d3703fff67/core.12118.tar.gz)

Program terminated with signal SIGABRT, Aborted.
#0  0x00007f364458ac37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f364458ac37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f364458e028 in __GI_abort () at abort.c:89
#2  0x0000000000536ba1 in dart::bin::segv_handler (signal=<optimized out>, 
    siginfo=<optimized out>, context=<optimized out>)
    at ../../runtime/bin/platform_linux.cc:27
#3  <signal handler called>
#4  Next (this=<optimized out>) at ../../runtime/vm/hash_map.h:178
#5  dart::AddressMap::Clear (this=<optimized out>)
    at ../../runtime/vm/malloc_hooks.cc:214
#6  0x0000000000855902 in ResetStats () at ../../runtime/vm/malloc_hooks.cc:251
#7  dart::MallocHooksState::TearDown () at ../../runtime/vm/malloc_hooks.cc:259
#8  0x000000000085620a in dart::MallocHooks::TearDown ()
    at ../../runtime/vm/malloc_hooks.cc:299
#9  0x000000000070c56e in dart::Dart::Cleanup () at ../../runtime/vm/dart.cc:495
#10 0x000000000065ec4b in Dart_Cleanup ()
    at ../../runtime/vm/dart_api_impl.cc:1203
#11 0x000000000052f6d5 in dart::bin::main (argc=<optimized out>, 
    argv=<optimized out>) at ../../runtime/bin/main.cc:1718
#12 0x000000000052fe29 in main (argc=11, argv=0x162910)
    at ../../runtime/bin/main.cc:1752
(gdb) 
```

**Comment by a-siva** [comment]
This appears to be a duplicate of https://github.com/dart-lang/sdk/issues/28904
