### ISSUE TITLE
[Fasta] NoSuchMethodError: The getter 'fileUri' was called on null

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#28921]
Trying to compile this file:

```dart
var tests = () {
  for (var num in [42]) {
    print(num);
  }
};

main(args) => tests(); 
```

like this:
```
out/ReleaseX64/dart --packages=.packages --dfe=utils/kernel-service/kernel-service.dart x.dart
```

I get this error:

```
NoSuchMethodError: The getter 'fileUri' was called on null.
Receiver: null
Tried calling: fileUri
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      JumpTarget.JumpTarget (package:front_end/src/fasta/kernel/body_builder.dart:2474:42)
#3      BodyBuilder.createJumpTarget (package:front_end/src/fasta/kernel/body_builder.dart:269:16)
#4      ScopeListener.createBreakTarget (package:front_end/src/fasta/source/scope_listener.dart:35:12)
#5      ScopeListener.enterBreakTarget (package:front_end/src/fasta/source/scope_listener.dart:59:29)
#6      BodyBuilder.enterLoop (package:front_end/src/fasta/kernel/body_builder.dart:964:7)
#7      ScopeListener.beginForStatement (package:front_end/src/fasta/source/scope_listener.dart:93:5)
#8      Parser.parseForStatement (package:front_end/src/fasta/parser/parser.dart:3149:14)
#9      Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:2124:14)
#10     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:2100:20)
#11     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:2037:15)
#12     Parser.parseUnnamedFunction (package:front_end/src/fasta/parser/parser.dart:1911:13)
#13     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:2666:14)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:2635:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:2572:15)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:2448:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:2421:11)
#18     Parser.parseFieldInitializerOpt (package:front_end/src/fasta/parser/parser.dart:1393:15)
#19     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:1211:13)
#20     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:1079:11)
#21     DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:509:22)
#22     DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:409:5)
#23     DietListener.endTopLevelFields (package:front_end/src/fasta/source/diet_listener.dart:211:5)
#24     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:1220:16)
#25     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:1079:11)
#26     Parser._parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:159:14)
#27     Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:135:13)
#28     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:127:15)
#29     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:113:14)
<asynchronous suspension>
#30     Loader.buildBodies (package:front_end/src/fasta/loader.dart:88:13)
<asynchronous suspension>
#31     KernelTarget.writeProgram (package:front_end/src/fasta/kernel/kernel_target.dart:219:20)
<asynchronous suspension>
#32     parseScriptImpl (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/utils/kernel-service/kernel-service.dart:127:34)
<asynchronous suspension>
#33     parseScript (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/utils/kernel-service/kernel-service.dart:150:18)
<asynchronous suspension>
#34     _processLoadRequestImpl (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/utils/kernel-service/kernel-service.dart:191:16)
<asynchronous suspension>
#35     _processLoadRequest (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/utils/kernel-service/kernel-service.dart:209:20)
<asynchronous suspension>
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by peter-ahe-google** [comment]
Thank you, I think I already have a [CL](https://codereview.chromium.org/2723513002) pending that should fix this.
