### ISSUE TITLE
Deferred dart:js library works in Chrome, doesn't work in Dartium

### ISSUE THREAD

**Issue by jimmyshiau** [dart-lang/sdk#28952]
### index.html
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Dart_web_hello</title>
    <script defer src="main.dart" type="application/dart"></script>
    <script defer src="packages/browser/dart.js"></script>
</head>

<body>

  <div id="output"></div>

  <script>
    var Chart = function (options) {
        this.options = options;
    }

    Chart.prototype.redraw = function () {
        document.querySelector('#output').innerText = 'Render ' + this.options.type + ' chart';
    }
  </script>
</body>
</html>

```

### main.dart
```dart
import 'dart:async';
//import 'chartjs.dart';//Dartium workaround, import chartjs.dart
import 'deferred_lib.dart' deferred as mylib;

void main() {
  initChart();
}

Future initChart() async {
  await mylib.loadLibrary();
  mylib.initChart();
}
```

### deferred_lib.dart
```dart
library deferred_lib;

import 'chartjs.dart';

void initChart() {
  final Chart chart = new Chart(new ChartConfiguration(type: 'Pie'));
  chart.redraw();
}
```

### chartjs.dart
```dart
@JS()
library js.chart;

import "package:js/js.dart";

@JS('Chart')
class Chart {
  external void redraw();
  external factory Chart(ChartConfiguration options);
}

@anonymous
@JS()
abstract class ChartConfiguration {
  external String get type;
  external set type(String v);

  external factory ChartConfiguration({String type});
}
```

**Comment by jimmyshiau** [comment]
If you didn't import `chartjs.dart` in `main.dart`, Dartium will show error

```
Uncaught Unhandled exception:
NoSuchMethodError: No static method 'ChartConfiguration.' declared in class 'ChartConfiguration'.
Receiver: Type: class 'ChartConfiguration'
Tried calling: ChartConfiguration.()
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:188)
#1      ChartConfiguration.ChartConfiguration (http://localhost:63342/boeneo/Dart_web_hello/web/chartjs.dart:24:53)
#2      initChart (http://localhost:63342/boeneo/Dart_web_hello/web/deferred_lib.dart:10:37)
#3      initChart.<initChart_async_body> (http://localhost:63342/boeneo/Dart_web_hello/web/main.dart:15:3)
#4      _RootZone.runUnary (dart:async/zone.dart:1404)
```

**Comment by terrylucas** [comment]
We will not fix this issue in Dartium. It would require significant changes to the DartVM that would not be useful elsewhere. The Dart Dev Compiler will support this case more cleanly and is the path for productive Dart debugging on the client going forward.

Your work around solution or try setting using load_deferred_eagerly option via:

export DART_FLAGS=--load_deferred_eagerly

this may also solve your problem.
