### ISSUE TITLE
VM test sometimes times out (standalone/io/socket_source_address_test)

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#28959]
The bot (https://build.chromium.org/p/client.dart/builders/vm-linux-release-ia32-be/builds/17277/steps/vm%20tests/logs/stdio) reported that the test timed out. I don't know whether this should be marked as slow or whether this indicates a bug.

In case the link above doesn't work, the relevant failure is:

FAILED: none-vm release_ia32 standalone/io/socket_source_address_test
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: Process list including children: [30377]
    Trying to capture stack trace for pid 30377
    PID 30377 - process
    TID 30377:
    #0  0xf77a2440 __kernel_vsyscall
    #1  0xf7773d4b pthread_cond_wait@@GLIBC_2.3.2
    #2  0x084bab37 dart::Monitor::WaitMicros(long long)
    #3  0x082d2470 Dart_RunLoop
    #4  0x081572f8 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
    #5  0x0814ebd2 dart::bin::main(int, char**)
    #6  0x0814edbb main
    #7  0xf747fa83 __libc_start_main
    #8  0x08155972 _start
    TID 30378:
    #0  0xf77a2440 __kernel_vsyscall
    #1  0xf7552696 epoll_wait
    #2  0x0815bddb dart::bin::EventHandlerImplementation::Poll(unsigned int)
    #3  0x0817e6cd dart::bin::ThreadStart(void*)
    #4  0xf776ff70 start_thread
    #5  0xf7551bee __clone
    TID 30379:
    #0  0xf77a2440 __kernel_vsyscall
    #1  0xf7773d4b pthread_cond_wait@@GLIBC_2.3.2
    #2  0x084bab37 dart::Monitor::WaitMicros(long long)
    #3  0x085c15dd dart::ThreadInterrupter::ThreadMain(unsigned int)
    #4  0x084b9e92 dart::ThreadStart(void*)
    #5  0xf776ff70 start_thread
    #6  0xf7551bee __clone
    TID 30380:
    #0  0xf77a2440 __kernel_vsyscall
    #1  0xf7773d4b pthread_cond_wait@@GLIBC_2.3.2
    #2  0x084bab37 dart::Monitor::WaitMicros(long long)
    #3  0x0830bac0 dart::BackgroundCompiler::Run()
    #4  0x085c243e dart::ThreadPool::Worker::Loop()
    #5  0x085c257d dart::ThreadPool::Worker::Main(unsigned int)
    #6  0x084b9e92 dart::ThreadStart(void*)
    #7  0xf776ff70 start_thread
    #8  0xf7551bee __clone
    TID 30384:
    #0  0xf77a2440 __kernel_vsyscall
    #1  0xf7773d4b pthread_cond_wait@@GLIBC_2.3.2
    #2  0x084bab37 dart::Monitor::WaitMicros(long long)
    #3  0x0830bac0 dart::BackgroundCompiler::Run()
    #4  0x085c243e dart::ThreadPool::Worker::Loop()
    #5  0x085c257d dart::ThreadPool::Worker::Main(unsigned int)
    #6  0x084b9e92 dart::ThreadStart(void*)
    #7  0xf776ff70 start_thread
    #8  0xf7551bee __clone
    
    eu-stack: dwfl_thread_getframes tid 30377 at 0x8155971 in /mnt/data/b/build/slave/vm-linux-release-ia32-be/build/sdk/out/ReleaseIA32/dart: no matching address range
    

stdout:
unittest-suite-wait-for-done
Failed to execute test closure (retry id: 1) in attempt 0 (10 retries left).
Exception: SocketException: Failed to create server socket (OS Error: Address already in use, errno = 98), address = 127.0.0.1, port = 35128
Stacktrace: #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:520)
#1      _RootZone.runUnary (dart:async/zone.dart:1404)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Command[vm]: DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-ia32-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-ia32-be/build/sdk/tests/standalone/io/socket_source_address_test.dart
Took 0:01:00.052287

Short reproduction command (experimental):
    python tools/test.py -mrelease -aia32 -t60 standalone/io/socket_source_address_test

**Comment by mraleph** [comment]
@bwilkerson please use Markdown when you paste logs, this makes it more readable and also avoid GitHub recognizing `#1` as issue number.

**Comment by whesse** [comment]
The previous comment didn't explain how to use markdown to quote a log or code. Use three backticks (3 X `) on a line before and after the code.  Like this:

```
     #34 is not an issue number
          and I'm indented
```
#28959 is me!
