### ISSUE TITLE
AnalysisException: Cannot compute RESOLVED_UNIT for ...

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28956]
[report2.txt](https://github.com/dart-lang/sdk/files/814109/report2.txt)
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.3566.24`
- `1.22.1`
- `IU-171.3566.24, JRE 1.8.0_112-release-724-b5x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.11.6 unknown, screens 1920x1080, 1920x1080, 2560x1440`

## Exception

Please append the contents of:
file:///private/var/folders/m4/9rg16xhd2rlbln753n9zk1540000gn/T/report2.txt

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1488465828043, params: {file: /Volumes/Daten/DevLocal/DevDart/MobiAd.REST.UI.MDL/test/integration/services/stats/StatsService_test.dart, offset: 1241}, method: edit.getFixes, id: 2243}
AnalysisException: Cannot compute RESOLVED_UNIT for 

/Volumes/Daten/DevLocal/DevDart/MobiAd.REST.UI.MDL/test/integration/services/stats/StatsService_test.dart in /Volumes/Daten/DevLocal/DevDart/MobiAd.REST.UI.MDL/test/integration/services/stats/StatsService_test.dart
Caused by Unexpected exception while performing StrongModeVerifyUnitTask for source /Volumes/Daten/DevLocal/DevDart/MobiAd.REST.UI.MDL/test/integration/services/stats/StatsService_test.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by NoSuchMethodError: The getter 'isDynamic' was called on null.
Receiver: null
Tried calling: isDynamic
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      CodeChecker._checkForUnsafeBlockClosureInference (package:analyzer/src/task/strong/checker.dart:740)
#3      CodeChecker.visitFunctionExpression (package:analyzer/src/task/strong/checker.dart:432)
#4      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5347)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#6      ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#7      RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:605)
#8      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#9      MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7656)
#10     CodeChecker.visitMethodInvocation (package:analyzer/src/task/strong/checker.dart:567)
#11     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7649)

**Comment by bwilkerson** [comment]
Do you have a test case that can reproduce this exception?

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
