### ISSUE TITLE
Bad state: Support for generic type aliases is not yet implemented

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#28957]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 172.SNAPSHOT`
- `1.23.0-dev.2.0`
- `172.SNAPSHOT, JRE 1.8.0_112-b15x64 Oracle Corporation, OS Windows 10(amd64) v10.0 , screens 1920x1200`

## Exception

```
Dart analysis server, SDK version 1.23.0-dev.2.0, server version 1.18.0, error: Analysis failed: C:\dart_projects\dart-lang\sdk\tests\language\mixin_illegal_syntax_test.dart context: exception_20170302_203216_465
Bad state: Support for generic type aliases is not yet implemented
#0      ErrorVerifier.visitGenericTypeAlias (package:analyzer/src/generated/error_verifier.dart:883)
#1      GenericTypeAliasImpl.accept (package:analyzer/src/dart/ast/ast.dart:5849)
#2      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8046)
#3      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#4      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#5      ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:566)
#6      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#7      LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:279)
#8      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:96)
#9      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:351)
#10     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:95)
#11     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:759)
#12     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1639)
#13     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:745)
#14     AnalysisDriver._performWork (package:analyzer/src/dart/analysis/driver.dart:1077)
<asynchronous suspension>
#15     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1371)
<asynchronous suspension>
#16     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1297)
#17     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:404)
#18     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)
#19     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#20     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:477)
#21     _rootRun (dart:async/zone.dart:1150)
#22     _CustomZone.run (dart:async/zone.dart:1026)
#23     runZoned (dart:async/zone.dart:1503)
#24     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:514)
#25     Driver.start (package:analysis_server/src/server/driver.dart:476)
#26     main (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```

```
1488475935950 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\method_override7_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR",
1488475935965 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\method_override8_test.dart","errors":[{"severity":"WARNING","type":"STATIC_WARNING","l
1488475935981 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\method_override_test.dart","errors":[{"severity":"WARNING","type":"STATIC_WARNING","lo
1488475935996 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\minify_closure_variable_collision_test.dart","errors":[]}}
1488475936012 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mint_arithmetic_test.dart","errors":[]}}
1488475936028 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mint_compares_test.dart","errors":[]}}
1488475936044 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\missing_const_constructor_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIM
1488475936055 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\missing_part_of_tag_part.dart","errors":[]}}
1488475936069 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\missing_part_of_tag_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERRO
1488475936086 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_black_listed_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR
1488475936106 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_bound_test.dart","errors":[]}}
1488475936120 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_cyclic_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","loc
1488475936142 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_extends_field_test.dart","errors":[{"severity":"INFO","type":"HINT","location":{
1488475936157 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_extends_is_test.dart","errors":[]}}
1488475936173 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_extends_method_test.dart","errors":[{"severity":"INFO","type":"HINT","location":
1488475936187 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_field_initializer_test.dart","errors":[]}}
1488475936218 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_field_test.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"
1488475936234 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_forwarding_constructor1_test.dart","errors":[]}}
1488475936248 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_forwarding_constructor2_test.dart","errors":[]}}
1488475936264 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_forwarding_constructor3_test.dart","errors":[]}}
1488475936283 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_forwarding_constructor4_test.dart","errors":[{"severity":"ERROR","type":"COMPILE
1488475936305 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_generic_test.dart","errors":[]}}
1488475936321 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_getter_regression_test.dart","errors":[]}}
1488475936339 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_illegal_constructor_test.dart","errors":[{"severity":"WARNING","type":"STATIC_WA
1488475936356 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_illegal_cycles_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERR
1488475936369 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_illegal_object_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERR
1488475936384 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_illegal_static_access_test.dart","errors":[{"severity":"WARNING","type":"STATIC_
1488475936403 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_illegal_superclass_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME
1488475936420 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_illegal_super_use_test.dart","errors":[{"severity":"WARNING","type":"STATIC_TYPE
1488475936533 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: C:\\dart_projects\\dart-lang\\sdk\\tests\\language\\mixin_illegal_syntax_test.dart context: exception_201
```

**Comment by bwilkerson** [comment]
This is as expected at this point. As the error message suggests, support for generic function types and generic type aliases is not yet implemented. See https://github.com/dart-lang/sdk/issues/27969.
