### ISSUE TITLE
analyzer crash "unsupported assignable" revealed by fuzz testing

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#28992]
Having trouble fuzz testing my own code because it keeps tripping this failure case in DAS:

```
@a(-b=""c
```

That seems to be a highly distilled version of the error. Though it seems to occur for any operator in place of `-` (I've tried `+` and `*`), whitespace doesn't matter, and either `""` or `{}` or `()` will trigger it, but both require some identifier `c` to follow for it to be triggered.

```

analysis_server.dart.snapshot$main:stdout> {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Bad state: Unsupported assignable: -b\n#0      AbstractConstExprSerializer._pushAssignable (package:analyzer/src/summary/summarize_const_expr.dart:272)\n#1      AbstractConstExprSerializer._serializeAssignment (package:analyzer/src/summary/summarize_const_expr.dart:470)\n#2      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:370)\n#3      AbstractConstExprSerializer._serializeArguments.<anonymous closure> (package:analyzer/src/summary/summarize_const_expr.dart:423)\n#4      Object&ListMixin.forEach (dart:collection/list.dart:63)\n#5      AbstractConstExprSerializer._serializeArguments (package:analyzer/src/summary/summarize_const_expr.dart:418)\n#6      AbstractConstExprSerializer.serializeInstanceCreation (package:analyzer/src/summary/summarize_const_expr.dart:178)\n#7      _ConstExprSerializer.serializeAnnotation (package:analyzer/src/summary/summarize_ast.dart:69)\n#8      _SummarizeAstVisitor.serializeAnnotations.<anonymous closure> (package:analyzer/src/summary/summarize_ast.dart:417)\n#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:412)\n#10     ListIterable.toList (dart:_internal/iterable.dart:219)\n#11     _SummarizeAstVisitor.serializeAnnotations (package:analyzer/src/summary/summarize_ast.dart:419)\n#12     _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:986)\n#13     _SummarizeAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/src/summary/summarize_ast.dart:1384)\n#14     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10403)\n#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)\n#16     _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:520)\n#17     serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22)\n#18     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:403)\n#19     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1662)\n#20     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:402)\n#21     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:167)\n#22     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1662)\n#23     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:163)\n#24     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:195)\n#25     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:975)\n<asynchronous suspension>\n#26     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1394)\n<asynchronous suspension>\n#27     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1320)\n#28     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:410)\n#29     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)\n#30     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)\n#31     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:477)\n#32     _rootRun (dart:async/zone.dart:1150)\n#33     _CustomZone.run (dart:async/zone.dart:1026)\n#34     runZoned (dart:async/zone.dart:1503)\n#35     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:514)\n#36     Driver.start (package:analysis_server/src/server/driver.dart:476)\n#37     main (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/server_plugin/bin/server.dart:36)\n#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)\n#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n"}}
analysis_server.dart.snapshot$main:stdout> {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Bad state: Unsupported assignable: -b\n#0      AbstractConstExprSerializer._pushAssignable (package:analyzer/src/summary/summarize_const_expr.dart:272)\n#1      AbstractConstExprSerializer._serializeAssignment (package:analyzer/src/summary/summarize_const_expr.dart:470)\n#2      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:370)\n#3      AbstractConstExprSerializer._serializeArguments.<anonymous closure> (package:analyzer/src/summary/summarize_const_expr.dart:423)\n#4      Object&ListMixin.forEach (dart:collection/list.dart:63)\n#5      AbstractConstExprSerializer._serializeArguments (package:analyzer/src/summary/summarize_const_expr.dart:418)\n#6      AbstractConstExprSerializer.serializeInstanceCreation (package:analyzer/src/summary/summarize_const_expr.dart:178)\n#7      _ConstExprSerializer.serializeAnnotation (package:analyzer/src/summary/summarize_ast.dart:69)\n#8      _SummarizeAstVisitor.serializeAnnotations.<anonymous closure> (package:analyzer/src/summary/summarize_ast.dart:417)\n#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:412)\n#10     ListIterable.toList (dart:_internal/iterable.dart:219)\n#11     _SummarizeAstVisitor.serializeAnnotations (package:analyzer/src/summary/summarize_ast.dart:419)\n#12     _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:986)\n#13     _SummarizeAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/src/summary/summarize_ast.dart:1384)\n#14     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10403)\n#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)\n#16     _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:520)\n#17     serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22)\n#18     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:403)\n#19     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1662)\n#20     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:402)\n#21     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:167)\n#22     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1662)\n#23     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:163)\n#24     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:195)\n#25     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:975)\n<asynchronous suspension>\n#26     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1394)\n<asynchronous suspension>\n#27     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1320)\n#28     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:410)\n#29     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)\n#30     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)\n#31     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:477)\n#32     _rootRun (dart:async/zone.dart:1150)\n#33     _CustomZone.run (dart:async/zone.dart:1026)\n#34     runZoned (dart:async/zone.dart:1503)\n#35     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:514)\n#36     Driver.start (package:analysis_server/src/server/driver.dart:476)\n#37     main (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/server_plugin/bin/server.dart:36)\n#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)\n#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n"}}
analysis_server.dart.snapshot$main:stdout> {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Bad state: Unsupported assignable: -b\n#0      Driver._captureExceptions.<anonymous closure> (package:analysis_server/src/server/driver.dart:503)\n#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005)\n#2      _Future._propagateToListeners (dart:async/future_impl.dart:552)\n#3      _Future._completeError (dart:async/future_impl.dart:485)\n#4      _SyncCompleter._completeError (dart:async/future_impl.dart:56)\n#5      _Completer.completeError (dart:async/future_impl.dart:27)\n#6      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1151)\n#7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)\n#8      _rootRun (dart:async/zone.dart:1146)\n#9      _CustomZone.run (dart:async/zone.dart:1026)\n#10     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#12     _rootRun (dart:async/zone.dart:1150)\n#13     _CustomZone.run (dart:async/zone.dart:1026)\n#14     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)\n#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)\n#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n<asynchronous suspension>\n#21     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1320)\n#22     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:410)\n#23     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)\n#24     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)\n#25     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:477)\n#26     _rootRun (dart:async/zone.dart:1150)\n#27     _CustomZone.run (dart:async/zone.dart:1026)\n#28     runZoned (dart:async/zone.dart:1503)\n#29     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:514)\n#30     Driver.start (package:analysis_server/src/server/driver.dart:476)\n#31     main (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/server_plugin/bin/server.dart:36)\n#32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)\n#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n"}}
analysis_server.dart.snapshot$main:stdout> {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Bad state: Unsupported assignable: -b\n#0      Driver._captureExceptions.<anonymous closure> (package:analysis_server/src/server/driver.dart:503)\n#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005)\n#2      _Future._propagateToListeners (dart:async/future_impl.dart:552)\n#3      _Future._completeError (dart:async/future_impl.dart:485)\n#4      _completeWithErrorCallback (dart:async/future.dart:824)\n#5      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:186)\n#6      _rootRun (dart:async/zone.dart:1146)\n#7      _CustomZone.run (dart:async/zone.dart:1026)\n#8      _CustomZone.runGuarded (dart:async/zone.dart:924)\n#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#10     _rootRun (dart:async/zone.dart:1150)\n#11     _CustomZone.run (dart:async/zone.dart:1026)\n#12     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)\n#17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)\n#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n<asynchronous suspension>\n#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1320)\n#20     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:410)\n#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)\n#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)\n#23     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:477)\n#24     _rootRun (dart:async/zone.dart:1150)\n#25     _CustomZone.run (dart:async/zone.dart:1026)\n#26     runZoned (dart:async/zone.dart:1503)\n#27     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:514)\n#28     Driver.start (package:analysis_server/src/server/driver.dart:476)\n#29     main (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/server_plugin/bin/server.dart:36)\n#30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)\n#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n"}}
analysis_server.dart.snapshot$main:stdout> {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Bad state: Unsupported assignable: -b\n#0      Driver._captureExceptions.<anonymous closure> (package:analysis_server/src/server/driver.dart:503)\n#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005)\n#2      _CustomZone.runGuarded (dart:async/zone.dart:926)\n#3      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#4      _rootRun (dart:async/zone.dart:1150)\n#5      _CustomZone.run (dart:async/zone.dart:1026)\n#6      _CustomZone.runGuarded (dart:async/zone.dart:924)\n#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)\n#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)\n#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n<asynchronous suspension>\n#13     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1320)\n#14     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:410)\n#15     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)\n#16     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)\n#17     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:477)\n#18     _rootRun (dart:async/zone.dart:1150)\n#19     _CustomZone.run (dart:async/zone.dart:1026)\n#20     runZoned (dart:async/zone.dart:1503)\n#21     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:514)\n#22     Driver.start (package:analysis_server/src/server/driver.dart:476)\n#23     main (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/server_plugin/bin/server.dart:36)\n#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)\n#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n"}}
```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2736373004/
