### ISSUE TITLE
Analyzer crash "Element mismatch" revealed by fuzz tester

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#28993]
Another failure case my angular fuzzer is revealing which is occurring inside DAS

distilled repro:
```
@a(b import
```

`b` seems to be possibly any expression (have tried `[]`, `foo: []`, etc).

Doesn't seem to care whether the annotation is closed or in front of a class or neither.

```
Unhandled exception:
AnalysisException: Element mismatch in /home/mfairhurst/dart/angular-dart-analyzer/playground/lib/overview_component.dart at /home/mfairhurst/dart/angular-dart-analyzer/playground/lib/overview_component.dart
Caused by Bad state: Found 1 annotation nodes and 0 element annotations
#0      DeclarationResolver._resolveAnnotations (package:analyzer/src/generated/declaration_resolver.dart:491)
#1      DeclarationResolver.visitImportDirective (package:analyzer/src/generated/declaration_resolver.dart:291)
#2      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:6186)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#4      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2522)
#5      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#6      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#7      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49)
#8      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:509)
#9      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:350)
#11     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88)
#12     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:759)
#13     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1662)
#14     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:745)
#15     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:983)
<asynchronous suspension>
#16     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1394)
<asynchronous suspension>
#17     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1320)
#18     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:410)
#19     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)
#20     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#21     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:477)
#22     _rootRun (dart:async/zone.dart:1150)
#23     _CustomZone.run (dart:async/zone.dart:1026)
#24     runZoned (dart:async/zone.dart:1503)
#25     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:514)
#26     Driver.start (package:analysis_server/src/server/driver.dart:476)
#27     main (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/server_plugin/bin/server.dart:36)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:52)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:509)
#2      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:350)
#4      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88)
#5      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:759)
#6      PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1662)
#7      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:745)
#8      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:983)
<asynchronous suspension>
#9      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1394)
<asynchronous suspension>
#10     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1320)
#11     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:410)
#12     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)
#13     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#14     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:477)
#15     _rootRun (dart:async/zone.dart:1150)
#16     _CustomZone.run (dart:async/zone.dart:1026)
#17     runZoned (dart:async/zone.dart:1503)
#18     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:514)
#19     Driver.start (package:analysis_server/src/server/driver.dart:476)
#20     main (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/server_plugin/bin/server.dart:36)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

#0      Driver._captureExceptions.<anonymous closure> (package:analysis_server/src/server/driver.dart:503)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005)
#2      _CustomZone.runGuarded (dart:async/zone.dart:926)
#3      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
<asynchronous suspension>
#9      AngularDriver.performWork (package:angular_analyzer_plugin/src/angular_driver.dart:124)
<asynchronous suspension>
#10     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1394)
<asynchronous suspension>
#11     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1320)
#12     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:410)
#13     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)
#14     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#15     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:477)
#16     _rootRun (dart:async/zone.dart:1150)
#17     _CustomZone.run (dart:async/zone.dart:1026)
#18     runZoned (dart:async/zone.dart:1503)
#19     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:514)
#20     Driver.start (package:analysis_server/src/server/driver.dart:476)
#21     main (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/server_plugin/bin/server.dart:36)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by devoncarew** [comment]
@MichaelRFairhurst, I'm curious, how automated is your fuzz tester? Is this something you're running manually currently? It seems like you've found a few issues in the analyzer codebase with it, and I'm wondering if it's something we can adapt and create one or more analyzer integration tests from.

**Comment by bwilkerson** [comment]
I'll note, for the record, that Luke has had a fuzz tester for a very long time that has also uncovered lots of issues in analyzer. We have not, unfortunately, always had the resources to address those issues.

**Comment by MichaelRFairhurst** [comment]
Also ran into this one:

```
@Component(
  selector: 'my-counter',
  inputs: const ['count']part,
```

notice the pesky `part` keyword there.

```
AnalysisException: Element mismatch in /test.dart at /test.dart
Caused by RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:153)
#1      DeclarationResolver.visitPartDirective (package:analyzer/src/generated/declaration_resolver.dart:356:50)
#2      PartDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:8400:15)
#3      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2529:15)
#4      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707:10)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516:15)
#6      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49:12)
#7      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:511:31)
#8      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89:9)
#9      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:348)
#10     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88:13)
#11     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:954:67)
#12     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1666:15)
#13     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:940:20)
#14     AnalysisDriver.performWork.<performWork_async_body> (package:analyzer/src/dart/analysis/driver.dart:697:33)
#15     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#16     _rootRun (dart:async/zone.dart:1146)
#17     _CustomZone.run (dart:async/zone.dart:1026)
#18     _CustomZone.runGuarded (dart:async/zone.dart:924)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#20     _rootRun (dart:async/zone.dart:1150)
#21     _CustomZone.run (dart:async/zone.dart:1026)
#22     _CustomZone.runGuarded (dart:async/zone.dart:924)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
