### ISSUE TITLE
DDC crash involving type parameters in promotion

### ISSUE THREAD

**Issue by asgerf** [dart-lang/sdk#29028]
This input causes DDC to crash at compile-time:
```dart
class A {}

class B extends A {}

class Foo<T extends A> {
  List<T> foo(T x) {
    List<T> tlist = <T>[];
    if (x is B) {
      var list = [x];
      tlist = list;
    }
    return tlist;
  }
}
```

Error from DDC:
```
    dartdevc arguments: ddc-crash.dart -o ddc-crash.js --modules node
    dart --version: 1.22.0-dev.10.6 (Tue Feb  7 19:57:17 2017) on "linux_x64"

Interpolated value #3 is not an Expression or List of Expressions: null
#0      InstantiatorGeneratorVisitor.error (package:dev_compiler/src/js_ast/template.dart:155:5)
#1      InstantiatorGeneratorVisitor.visitSplayableExpression.<anonymous closure>.toExpression (package:dev_compiler/src/js_ast/template.dart:200:18)
#2      InstantiatorGeneratorVisitor.visitSplayableExpression.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:204:28)
#3      InstantiatorGeneratorVisitor.handleCallOrNew.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:589:34)
#4      InstantiatorGeneratorVisitor.visitAssignment.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:549:53)
#5      InstantiatorGeneratorVisitor.handleCallOrNew.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:586:31)
#6      InstantiatorGeneratorVisitor.visitFunctionExpression.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:664:26)
#7      InstantiatorGeneratorVisitor.visitVariableInitialization.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:558:48)
#8      InstantiatorGeneratorVisitor.visitVariableDeclarationList.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:536:34)
#9      InstantiatorGeneratorVisitor.visitExpressionStatement.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:344:29)
#10     Template.instantiate (package:dev_compiler/src/js_ast/template.dart:107:26)
#11     JsBuilder.statement (package:dev_compiler/src/js_ast/builder.dart:224:21)
#12     _GeneratorTable._dischargeType (package:dev_compiler/src/compiler/type_utilities.dart:134:17)
#13     _CacheTable.discharge (package:dev_compiler/src/compiler/type_utilities.dart:58:18)
#14     TypeTable.discharge.<anonymous closure> (package:dev_compiler/src/compiler/type_utilities.dart:187:23)
#15     ExpandIterator.moveNext (dart:_internal/iterable.dart:480)
#16     List.List.from (dart:core-patch/array_patch.dart:39)
#17     Iterable.toList (dart:core/iterable.dart:347)
#18     TypeTable.discharge (package:dev_compiler/src/compiler/type_utilities.dart:187:42)
#19     CodeGenerator._defineClassTypeArguments (package:dev_compiler/src/compiler/code_generator.dart:1226:18)
#20     CodeGenerator.visitClassDeclaration (package:dev_compiler/src/compiler/code_generator.dart:863:18)
#21     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923:15)
#22     CodeGenerator._visit (package:dev_compiler/src/compiler/code_generator.dart:5515:23)
#23     CodeGenerator._emitDeclaration.<anonymous closure> (package:dev_compiler/src/compiler/code_generator.dart:514:14)
#24     ElementLoader.emitDeclaration (package:dev_compiler/src/compiler/element_loader.dart:85:23)
#25     CodeGenerator._emitDeclaration (package:dev_compiler/src/compiler/code_generator.dart:507:24)
#26     CodeGenerator._finishDeclarationsInUnit (package:dev_compiler/src/compiler/code_generator.dart:533:9)
#27     List.forEach (dart:core-patch/array.dart:77)
#28     CodeGenerator._emitModule (package:dev_compiler/src/compiler/code_generator.dart:315:22)
#29     CodeGenerator.compile (package:dev_compiler/src/compiler/code_generator.dart:195:18)
#30     ModuleCompiler.compile (package:dev_compiler/src/compiler/compiler.dart:217:26)
#31     _compile (package:dev_compiler/src/compiler/command.dart:174:25)
#32     compile (package:dev_compiler/src/compiler/command.dart:53:5)
#33     main.<main_async_body> (file:///usr/local/google/home/asgerf/dart/dart-repo/sdk/pkg/dev_compiler/bin/dartdevc.dart:53:16)
#34     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

I tested this against dartdevc that shipped in 1.22-dev.10.6 as well as newest commit as of now (b955d390a10da74f27e26dfb3b4b54e4dccde2bd).

My understanding is that the analyzer emulates the intersection type `T&B` by generating a fresh type parameter `T' extends T&B`, though I don't understand exactly how it does this.  My guess is that the problem is related to how code generation deals with this type parameter.

**Comment by asgerf** [comment]
Another view on the same problem. This input compiles but fails at runtime:
```dart
class A {}

class B extends A {}

class Foo<T extends A> {
  void foo(T x) {
    if (x is B) {
      var list = [x];
    }
  }
}

main() {
  new Foo<B>().foo(new B());
}
```

The following "top-level" declaration shows up in the JS output:
```js
let JSArrayOfT = () => (JSArrayOfT = dart.constFn(_interceptors.JSArray$(T)))();
```
This fails since T is not in scope at the top-level.

**Comment by jmesserly** [comment]
The compiler crash does not seem to reproduce anymore, but the runtime crash does. Working on it. I think your guess is correct, this is something to do with how Analyzer represents the `T' extends T&B` fresh type parameter

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2969373002/
