### ISSUE TITLE
Kernel and --pause-isolates-on-unhandled-exceptions in async

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#29056]
It seems that since https://codereview.chromium.org/2692803006/ and https://codereview.chromium.org/2725623003 we - when doing the async transformation - need to
a) name the completer :async_completer
b) mark the catching as generated somehow

The first part is probably just
```
diff --git a/runtime/vm/kernel_to_il.cc b/runtime/vm/kernel_to_il.cc
index 194fc9e5f5..5c8a347e85 100644
--- a/runtime/vm/kernel_to_il.cc
+++ b/runtime/vm/kernel_to_il.cc
@@ -708,8 +708,8 @@ void ScopeBuilder::VisitFunctionNode(FunctionNode* node) {
     node->body()->AcceptStatementVisitor(this);
   }

-  // Ensure that :await_jump_var, :await_ctx_var, :async_op and
-  // :async_stack_trace are captured.
+  // Ensure that :await_jump_var, :await_ctx_var, :async_op,
+  // :async_completer and :async_stack_trace are captured.
   if (node->async_marker() == FunctionNode::kSyncYielding) {
     {
       LocalVariable* temp = NULL;
@@ -730,6 +730,13 @@ void ScopeBuilder::VisitFunctionNode(FunctionNode* node) {
         scope_->CaptureVariable(temp);
       }
     }
+    {
+      LocalVariable* temp =
+          scope_->LookupVariable(Symbols::AsyncCompleter(), true);
+      if (temp != NULL) {
+        scope_->CaptureVariable(temp);
+      }
+    }
     if (FLAG_causal_async_stacks) {
       LocalVariable* temp =
           scope_->LookupVariable(Symbols::AsyncStackTraceVar(), true);
diff --git a/pkg/kernel/lib/transformations/continuation.dart b/pkg/kernel/lib/transformations/continuation.dart
index a8b28205e7..38a7fd86c1 100644
--- a/pkg/kernel/lib/transformations/continuation.dart
+++ b/pkg/kernel/lib/transformations/continuation.dart
@@ -790,7 +790,7 @@ class AsyncFunctionRewriter extends AsyncRewriterBase {
         new InterfaceType(helper.completerClass, completerTypeArguments);

     // final Completer<T> :completer = new Completer<T>.sync();
-    completerVariable = new VariableDeclaration(":completer",
+    completerVariable = new VariableDeclaration(":async_completer",
         initializer: new StaticInvocation(helper.completerConstructor,
             new Arguments([], types: completerTypeArguments))
           ..fileOffset = enclosingFunction.body.fileOffset,
```

The second part might require us to change the kernel format slightly...

Test-code (extracted from the service tests):
```dart
class Foo {

}

doThrow() {
  throw "TheException"; // Line 13.
  return "end of doThrow";
}

asyncThrower() async {
  doThrow();
}

main() async {
  try {
    // caught.
    try {
      await asyncThrower();
    } catch (e) {
    }

    // uncaught.
    try {
      await asyncThrower();  // LINE_A.
    } on double catch (e) {
    }
  } on Foo catch (e) {
  }
}
```

**Comment by sjindel-google** [comment]
What exact is the bug? The test code's behaviour appears correct in Kernel.

**Comment by jensjoha** [comment]
The bug is that "--pause-isolates-on-unhandled-exceptions" doesn't work in an async function via kernel.

Example:

With the above code in x.dart and running through kernel:

```
$ out/ReleaseX64/dart --dfe=utils/kernel-service/kernel-service.dart --kernel-binaries=out/ReleaseX64 --packages=.packages --enable-vm-service:54975 --pause-isolates-on-unhandled-exceptions x.dart
Observatory listening on http://127.0.0.1:54975/
Unhandled exception:
TheException
#0      doThrow (x.dart:6:3)
#1      asyncThrower (x.dart:11:3)
<asynchronous suspension>
#2      main (x.dart:24:13)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate:1252:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate:1142:12)
```

i.e. the debugger doesn't pause, the script just crashes.

If instead running without kernel:
```
$ out/ReleaseX64/dart --enable-vm-service:54975 --pause-isolates-on-unhandled-exceptions x.dart
Observatory listening on http://127.0.0.1:54975/
```
(and now the debugger has stopped at line 6: Going to observatory will show "paused by exception at doThrow (x.dart:6:3) [debug]"

**Comment by dgrove** [comment]
@a-siva @jensjoha - can you please move this to Dart2-beta3/beta4/stable, or remove the milestone?

**Comment by DanTup** [comment]
I think this may fixed now (see https://github.com/flutter/flutter/issues/16741#issuecomment-386689529) in b2c98f9. Certainly the Flutter issue is working fine for me.

**Comment by aam** [comment]
There is still remaining issue outstanding, which can be seen on currently failing test https://github.com/dart-lang/sdk/blob/master/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions_test.dart

**Comment by DanTup** [comment]
Ah ok, sounds like you're on top of it! :-)

(#29156 next? ;-))

**Comment by kmillikin** [comment]
@aam was this fixed and can it be closed?  The service test is no longer marked as failing.
