### ISSUE TITLE
modified lib/mirrors/invocation_fuzz_test fails with Unimplemented error on dart2js

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#29086]
out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: UnimplementedError
          throw e;
          ^
UnimplementedError
    at dart.d (/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js:2683:3)
    at dart.D (/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js:2689:23)
    at fp.dart.Cy.gbc (/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js:5442:26)
    at dart.BB (/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js:16829:24)
    at KD.dart.KD.$1 (/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js:16917:26)
    at ad.dart.ad.P.H.b.func [as P] (/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js:455:20)
    at dart.Z2 (/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js:16849:5)
    at jz.dart.jz.hg (/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js:1997:9)
    at dart.C5 (/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js:1777:8)
    at /b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js:18541:68

Command[dart2js]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --minify --packages=/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/.packages /b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_tests/lib/mirrors/invocation_fuzz_test_emptyarray.dart --out=/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js
Took 0:00:09.459777

Command[d8]: DART_CONFIGURATION=ReleaseX64 /b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/third_party/d8/linux/d8 out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js /b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/multitest_lib_mirrors_invocation_fuzz_test_emptyarray/out.js
Took 0:00:01.280704

Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2js -rd8 --minified -t60 --use-sdk --dart2js-batch --reset-browser-configuration lib/mirrors/invocation_fuzz_test/emptyarray

**Comment by lrhn** [comment]
In a non-minified run, the error is:
```
...
Symbol("dart.mirrors")
Symbol("dart.typed_data")
Symbol("test.invoke_natives")
Skipping test.invoke_natives
../sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: UnimplementedError
          throw e;
          ^
UnimplementedError
    at dart.wrapException (../tests/lib/mirrors/invocation_fuzz_test.dart.out:6285:17)
    at dart.throwExpression (../tests/lib/mirrors/invocation_fuzz_test.dart.out:6298:15)
    at JsFunctionTypeMirror.dart.BrokenClassMirror.get$declarations (../tests/lib/mirrors/invocation_fuzz_test.dart.out:12193:18)
    at dart.checkInstance (../tests/lib/mirrors/invocation_fuzz_test.dart.out:39081:35)
    at main_closure0.dart.main_closure0.call$1 (../tests/lib/mirrors/invocation_fuzz_test.dart.out:39268:18)
    at JSArray.dart.JSArray.forEach$1.H.computeSignature.func [as forEach$1] (../tests/lib/mirrors/invocation_fuzz_test.dart.out:956:13)
    at dart.main (../tests/lib/mirrors/invocation_fuzz_test.dart.out:39122:25)
    at _IsolateContext.dart._IsolateContext.eval$1 (../tests/lib/mirrors/invocation_fuzz_test.dart.out:4853:25)
    at dart.startRootIsolate (../tests/lib/mirrors/invocation_fuzz_test.dart.out:4451:21)
    at ../tests/lib/mirrors/invocation_fuzz_test.dart.out:41376:11
```
so it's the `BrokenClassMirror` that throws.

Since it throws an `UnimplementedError`, this is probably deliberate. Dart2js doesn't implement the full mirror library.

**Comment by bkonyi** [comment]
Closing since `dart:mirrors` is no longer supported for dart2js.
