### ISSUE TITLE
dartanalyzer crashing against pkg/angular2 @ 2.2.0 w/ --strong

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#29105]
Dart VM version: 1.23.0-dev.9.0 (Thu Mar 16 09:51:27 2017) on "macos_x64"

1. Sync down https://github.com/dart-lang/angular2
1. cd angular2
1. `git checkout -b old_ver 655d2b49000fee008d834cdb0ff2dfed8bbca2b4` – the 2.2.0 release
1. `dartanalyzer --strong .`

Expected: it works!

Actual:

Many things...
```
[hint] 'NgPluralCase' is deprecated and shouldn't be used at lib/src/common/directives/core_directives.dart:4:40 (deprecated_member_use).
[hint] 'NgPlural' is deprecated and shouldn't be used at lib/src/common/directives/core_directives.dart:70:3 (deprecated_member_use).
[hint] 'NgPluralCase' is deprecated and shouldn't be used at lib/src/common/directives/core_directives.dart:71:3 (deprecated_member_use).
[hint] 'NgControlStatus' is deprecated and shouldn't be used at lib/src/common/forms.dart:26:55 (deprecated_member_use).
[hint] 'NgControlStatus' is deprecated and shouldn't be used at lib/src/common/forms/directives.dart:29:49 (deprecated_member_use).
Unhandled exception:
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1092)
#1      CompilationUnitElementInDependency.getLinkedType (package:analyzer/src/summary/link.dart:1394)
#2      ParameterElementForLink.type (package:analyzer/src/summary/link.dart:4117)
#3      FunctionTypeImpl.parameters (package:analyzer/src/dart/element/type.dart:578)
#4      InstanceMemberInferrer._inferParameterCovariance.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:391)
#5      Object&ListMixin.any (dart:collection/list.dart:115)
#6      InstanceMemberInferrer._inferParameterCovariance (package:analyzer/src/task/strong_mode.dart:390)
#7      InstanceMemberInferrer._inferExecutable (package:analyzer/src/task/strong_mode.dart:312)
#8      List.forEach (dart:core-patch/growable_array.dart:258)
#9      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:227)
#10     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:96)
#11     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1293)
#12     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3631)
#13     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3369)
#14     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3291)
#15     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#16     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#17     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3334)
#18     Linker.link (package:analyzer/src/summary/link.dart:3856)
#19     relink (package:analyzer/src/summary/link.dart:132)
#20     link (package:analyzer/src/summary/link.dart:113)
#21     LibraryContext.LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:106)
#22     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1666)
#23     LibraryContext.LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:105)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1666)
#25     LibraryContext.LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:51)
#26     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:851)
#27     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:816)
#28     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1028)
<asynchronous suspension>
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1398)
<asynchronous suspension>
#30     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1324)
#31     Driver._createAnalysisContext (package:analyzer_cli/src/driver.dart:594)
#32     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:191)
<asynchronous suspension>
#33     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167)
<asynchronous suspension>
#34     Driver.start (package:analyzer_cli/src/driver.dart:146)
<asynchronous suspension>
#35     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by srawlins** [comment]
The dartanalyzer no longer crashes while analyzing the Angular codebase.
