### ISSUE TITLE
Analyzer Exception - failed to resolve declarations

### ISSUE THREAD

**Issue by sambbaron** [dart-lang/sdk#29124]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-171.3780.79`
- `1.22.1`
- `WS-171.3780.79, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.11.6 unknown, screens 2560x1440`

## Exception

Please append the contents of:
file:///private/var/folders/9t/6gh49wjd6q78w4m09z07cz9c0000gn/T/report.txt

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Failed to handle completion domain request: {clientRequestTime: 1490113000361, params: {file: /Users/sambaron/ActiveProjects/AppTree/Web/portal/lib/base/views/table/table_settings/table_setting_modal_editor.dart, offset: 793}, method: completion.getSuggestions, id: 437}
AnalysisException: failed to resolve declarations
Caused by Instance of 'AnalysisNotScheduledError'
#0      PendingFuture.forciblyComplete (package:analyzer/src/context/context.dart:2223)
#1      AnalysisContextImpl._evaluatePendingFutures (package:analyzer/src/context/context.dart:1504)
#2      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1198)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#4      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#5      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#6      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#7      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#8      _rootRun (dart:async/zone.dart:1146)
#9      _CustomZone.run (dart:async/zone.dart:1026)
#10     _CustomZone.runGuarded (dart:async/zone.dart:924)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#12     _rootRun (dart:async/zone.dart:1150)
#13     _CustomZone.run (dart:async/zone.dart:1026)
#14     _CustomZone.runGuarded (dart:async/zone.dart:924)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#16     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      DartCompletionRequestImpl._computeAsync.<_computeAsync_async_body> (package:analysis_server/src/services/completion/dart/completion_manager.dart:486)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _rootRunBinary (dart:async/zone.dart:1170)
#3      _CustomZone.runBinary (dart:async/zone.dart:1049)
#4      _FutureListener.handleError (dart:async/future_impl.dart:146)
#5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#7      _Future._completeError (dart:async/future_impl.dart:485)
#8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
