### ISSUE TITLE
standalone/io/http_auth_digest_test failed on buildbot

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#29137]
The `standalone/io/http_auth_digest_test` failed on the buildbot.

https://build.chromium.org/p/client.dart/builders/vm-linux-release-ia32-optcounter-threshold-be/builds/4805/steps/vm%20tests/logs/stdio

Relevant output:
```
FAILED: none-vm release_ia32 standalone/io/http_auth_digest_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.equals(at index 0: Expected <6a5248d5736cd16...>, Found: <d9ef102c662c093...>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:99:9)
#2      Server._start.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/tests/standalone/io/http_auth_digest_test.dart:109:20)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#6      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#7      _StreamController._add (dart:async/stream_controller.dart:628)
#8      _StreamController.add (dart:async/stream_controller.dart:574)
#9      _HttpServer._handleRequest (dart:io/http_impl.dart:2343)
#10     _HttpConnection._HttpConnection.<anonymous closure> (dart:io/http_impl.dart:2096)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#14     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#15     _StreamController._add (dart:async/stream_controller.dart:628)
#16     _StreamController.add (dart:async/stream_controller.dart:574)
#17     _HttpParser._headersEnd (dart:io/http_parser.dart:389)
#18     _HttpParser._doParse (dart:io/http_parser.dart:711)
#19     _HttpParser._parse (dart:io/http_parser.dart:332)
#20     _HttpParser._onData (dart:io/http_parser.dart:821)
#21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#24     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#25     _StreamController._add (dart:async/stream_controller.dart:628)
#26     _StreamController.add (dart:async/stream_controller.dart:574)
#27     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#31     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#32     _StreamController._add (dart:async/stream_controller.dart:628)
#33     _StreamController.add (dart:async/stream_controller.dart:574)
#34     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#35     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)


Command[vm]: DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/tests/standalone/io/http_auth_digest_test.dart
Took 0:00:01.521243

Short reproduction command (experimental):
    python tools/test.py -mrelease -aia32 -t60 --vm-options --optimization-counter-threshold=5 standalone/io/http_auth_digest_test
```

**Comment by mraleph** [comment]
I am looking into this.
