### ISSUE TITLE
crash in type inferrer: call + mixin application

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#29130]
The following program makes the type-inferrer crash:

```dart
main() => new B();

class A {
  call() {}
}

abstract class B implements A {
  factory B() => new _B();
}

class _B = A with B;
```

with the following exception:
```
he compiler crashed: NoSuchMethodError: The getter 'functionSignature' was called on null.
Receiver: null
Tried calling: functionSignature
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ClosureTracerVisitor.run (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/inferrer/closure_tracer.dart:33)
#3      InferrerEngine.runOverAllElements.<anonymous closure>.trace (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:334)
#4      InferrerEngine.runOverAllElements.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:381)
#5      _HashFieldBase&_HashBase&_OperatorEqualsAndHashCode&SetMixin.forEach (dart:collection/set.dart:145)
#6      InferrerEngine.runOverAllElements (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:331)
#7      TypeGraphInferrer.analyzeMain (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/inferrer/type_graph_inferrer.dart:68)
#8      GlobalTypeInferenceTask.runGlobalTypeInference.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/types/types.dart:260)
#9      CompilerTask.measure (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63)
#10     GlobalTypeInferenceTask.runGlobalTypeInference (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/types/types.dart:257)
#11     Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:685)
#12     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#13     Compiler.compileLoadedLibraries (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:592)
#14     Compiler.runInternal.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:500)
#15     _RootZone.runUnary (dart:async/zone.dart:1404)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#17     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#18     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#19     _Future._completeWithValue (dart:async/future_impl.dart:477)
#20     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by sigmundch** [comment]
Turns out that the mixin is not at play here, but the factory method is.

Here is an even simpler example:
```dart
main() => new B();

class A {
  call() {}
}

abstract class B implements A {
  factory B() => null;
}
```
