### ISSUE TITLE
Analyzer Error in Webstorm

### ISSUE THREAD

**Issue by jfphilbin** [dart-lang/sdk#29149]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-171.3780.79`
- `<NO SDK>`
- `WS-171.3780.79, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 3840x2160, 3840x2160, 3840x2160`

## Exception

Please append the contents of:
file://C:\Users\admin\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.22.0, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1490296323847, params: {file: \date_time.dart, offset: 269, length: 52}, method: analysis.getNavigation, id: 82}
NoSuchMethodError: The method 'then' was called on null.
Receiver: null
Tried calling: then(Closure: (AnalysisDoneReason) => dynamic)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AnalysisDomainHandler.getNavigation.<getNavigation_async_body> (package:analysis_server/src/domain_analysis.dart:177)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#4      _rootRun (dart:async/zone.dart:1146)
#5      _CustomZone.run (dart:async/zone.dart:1026)
#6      _CustomZone.runGuarded (dart:async/zone.dart:924)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#8      _rootRun (dart:async/zone.dart:1150)
#9      _CustomZone.run (dart:async/zone.dart:1026)
#10     _CustomZone.runGuarded (dart:async/zone.dart:924)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#12     _microtaskLoop (dart:async/schedu

**Comment by bwilkerson** [comment]
Thanks for the report!

This has been fixed in bleeding edge and should be included in the next dev and stable builds.
