### ISSUE TITLE
Generated automatically by WebStorm.

### ISSUE THREAD

**Issue by lfyuomr-gylo** [dart-lang/sdk#29144]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-171.3780.79`
- `1.22.1`
- `WS-171.3780.79, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-64-generic unknown, screens 1366x768`

## Exception

[Content of /tmp/report.txt file](https://gist.github.com/lfyuomr-gylo/1908f2e8b220a2c56bede5ce847acc9b)

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Task failed: GatherUsedLocalElementsTask for source /home/gylo/HSE/3_course/ProgLangs/02/web/table.dart
Unexpected exception while performing GatherUsedLocalElementsTask for source /home/gylo/HSE/3_course/ProgLangs/02/web/table.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find dynamic number in [null number, null parser, null e, null exp]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3162)
#1      LocalVariableElementImpl.identifier (package:analyzer/src/dart/element/element.dart:6110)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3202)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2920)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2809)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10562)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3522)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5347)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:605)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#14     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7656)
#15     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1013)
#16     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7649)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
