### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by zengyun261** [dart-lang/sdk#29157]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-171.3780.79`
- `1.22.1`
- `WS-171.3780.79, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2560x1440`

## Exception

Please append the contents of:
file://C:\Users\zy\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1490362965038, params: {file: C:\Users\zy\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\postgresql-0.3.4 1\lib\postgresql.dart, offset: 42, length: 77}, method: analysis.getNavigation, id: 6}
NoSuchMethodError: The method 'then' was called on null.
Receiver: null
Tried calling: then(Closure: (AnalysisDoneReason) => dynamic)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AnalysisDomainHandler.getNavigation.<getNavigation_async_body> (package:analysis_server/src/domain_analysis.dart:177)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#4      _rootRun (dart:async/zone.dart:1146)
#5      _CustomZone.run (dart:async/zone.dart:1026)
#6      _CustomZone.runGuarded (dart:async/zone.dart:924)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#8      _rootRun (dart:async/zone.dart:1150)
#9      _CustomZone.run (dart:async/zone.dart:1026)
#10     _CustomZone.runGuarded (dart:async/zone.dart:924)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.d

**Comment by bwilkerson** [comment]
Thanks for the report!

This has been fixed in bleeding edge and the fix will be available in the next release.
