### ISSUE TITLE
Exception while working with WebStorm

### ISSUE THREAD

**Issue by tomas-rokos** [dart-lang/sdk#29152]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-171.3780.79`
- `1.22.1`
- `WS-171.3780.79, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.3 unknown, screens 1280x800  Retina`

## Exception

Please append the contents of:
file:///private/var/folders/z1/_9fc26d13wdgfzy25f_13j1h0000gn/T/report.txt

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1490299927235, params: {file: /Users/tomasrokos/Desktop/ismecka/lib/ismecka.dart, offset: 772, length: 45}, method: analysis.getNavigation, id: 12}
AnalysisException: Cannot compute RESOLVED_UNIT for /Users/tomasrokos/Desktop/ismecka/lib/ismecka.dart in /Users/tomasrokos/Desktop/ismecka/lib/ismecka.dart
Caused by Unexpected exception while performing ResolveDirectiveElementsTask for source /Users
[report.txt](https://github.com/dart-lang/sdk/files/866074/report.txt)
/tomasrokos/Desktop/ismecka/lib/utils/ismecka/ismecka.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by NoSuchMethodError: The getter 'imports' was called on null.
Receiver: null
Tried calling: imports
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      DirectiveResolver.visitImportDirective (package:analyzer/src/generated/resolver.dart:2344)
#3      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:6178)
#4      DirectiveResolver.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:2311)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#6      ResolveDirectiveElementsTask.internalPerform (package:analyzer/src/task/dart.dart:5085)
#7      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#8      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#9      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#10     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#11     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)

**Comment by tomas-rokos** [comment]
[report.txt](https://github.com/dart-lang/sdk/files/866079/report.txt)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
