### ISSUE TITLE
pause_on_unhandled_async_exceptions2_test on app-linux-release-x64-be

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#29178]
https://uberchromegw.corp.google.com/i/client.dart/builders/app-linux-release-x64-be/builds/4379/steps/vm%20tests/logs/stdio

```
=== Failure summary:


FAILED: app_jit-vm release_x64 service/pause_on_unhandled_async_exceptions2_test
Expected: Pass 
Actual: RuntimeError
Unexpected compile-time error.
CommandOutput[app_jit]:

stderr:
Unhandled exception:
<Received error while converting exception to string>
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      StringBuffer.StringBuffer (dart:core-patch/string_buffer_patch.dart:56)
#3      _Uri._toFilePath (dart:core/uri.dart:2632)
#4      _Uri.toFilePath (dart:core/uri.dart:2620)
#5      _ServiceTesteeLauncher._ServiceTesteeLauncher (file:///b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:86:54)
#6      _ServiceTesterRunner.run (file:///b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:284:23)
#7      runIsolateTests (file:///b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:411:32)
<asynchronous suspension>
#8      main (file:///b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart:57:15)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


Command[app_jit]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --snapshot=/b/build/slave/app-linux-release-x64-be/build/sdk/out/ReleaseX64/generated_compilations/app_jit/runtime_observatory_tests_service_pause_on_unhandled_async_exceptions2_test.dart_1/out.jitsnapshot --snapshot-kind=app-jit --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-release-x64-be/build/sdk/.packages /b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart
Took 0:00:01.526858

Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-release-x64-be/build/sdk/.packages /b/build/slave/app-linux-release-x64-be/build/sdk/out/ReleaseX64/generated_compilations/app_jit/runtime_observatory_tests_service_pause_on_unhandled_async_exceptions2_test.dart_1/out.jitsnapshot
Did not run

Short reproduction command (experimental):
    python tools/test.py -mrelease -capp_jit -t60 --builder-tag no_ipv6 service/pause_on_unhandled_async_exceptions2_test



===
=== 1 test failed
===
```

https://uberchromegw.corp.google.com/i/client.dart/builders/app-linux-release-x64-be/builds/4365/steps/vm%20tests/logs/stdio
```
=== Failure summary:


FAILED: app_jit-vm release_x64 service/pause_on_unhandled_async_exceptions2_test
Expected: Pass 
Actual: Timeout
CommandOutput[app_jit]:
diagnostics: Process list including children: [2621, 2714]
    Trying to capture stack trace for pid 2621
    PID 2621 - process
    TID 2621:
    #0  0x00007f3ac397b404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000863db5 dart::Monitor::WaitMicros(long)
    #2  0x0000000000653a3a Dart_RunLoop
    #3  0x0000000000527dc3 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
    #4  0x0000000000528f05 dart::bin::main(int, char**)
    #5  0x0000000000529369 main
    #6  0x00007f3ac2ba0f45 __libc_start_main
    #7  0x00000000005274eb _start
    TID 2623:
    #0  0x00007f3ac2c7d283 epoll_wait
    #1  0x000000000052c455 dart::bin::EventHandlerImplementation::Poll(unsigned long)
    #2  0x0000000000547a7e dart::bin::ThreadStart(void*)
    #3  0x00007f3ac3977184 start_thread
    #4  0x00007f3ac2c7cbed __clone
    TID 2624:
    #0  0x00007f3ac397b404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000863db5 dart::Monitor::WaitMicros(long)
    #2  0x000000000096a21f dart::ThreadInterrupter::ThreadMain(unsigned long)
    #3  0x00000000008634f9 dart::ThreadStart(void*)
    #4  0x00007f3ac3977184 start_thread
    #5  0x00007f3ac2c7cbed __clone
    TID 2626:
    #0  0x00007f3ac397b404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000863db5 dart::Monitor::WaitMicros(long)
    #2  0x00000000006b8f6a dart::BackgroundCompiler::Run()
    #3  0x000000000096aedd dart::ThreadPool::Worker::Loop()
    #4  0x000000000096adab dart::ThreadPool::Worker::Main(unsigned long)
    #5  0x00000000008634f9 dart::ThreadStart(void*)
    #6  0x00007f3ac3977184 start_thread
    #7  0x00007f3ac2c7cbed __clone
    TID 2627:
    #0  0x00007f3ac397b404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000863db5 dart::Monitor::WaitMicros(long)
    #2  0x00000000006b8f6a dart::BackgroundCompiler::Run()
    #3  0x000000000096aedd dart::ThreadPool::Worker::Loop()
    #4  0x000000000096adab dart::ThreadPool::Worker::Main(unsigned long)
    #5  0x00000000008634f9 dart::ThreadStart(void*)
    #6  0x00007f3ac3977184 start_thread
    #7  0x00007f3ac2c7cbed __clone
    TID 2715:
    #0  0x00007f3ac397ee44 wait
    #1  0x0000000000532238 dart::bin::ExitCodeHandler::ExitCodeHandlerEntry(unsigned long)
    #2  0x0000000000547a7e dart::bin::ThreadStart(void*)
    #3  0x00007f3ac3977184 start_thread
    #4  0x00007f3ac2c7cbed __clone
    
    
    Trying to capture stack trace for pid 2714
    PID 2714 - process
    TID 2714:
    #0  0x00007f5eea708404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000863db5 dart::Monitor::WaitMicros(long)
    #2  0x0000000000653a3a Dart_RunLoop
    #3  0x0000000000527dc3 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
    #4  0x0000000000528f05 dart::bin::main(int, char**)
    #5  0x0000000000529369 main
    #6  0x00007f5ee992df45 __libc_start_main
    #7  0x00000000005274eb _start
    TID 2723:
    #0  0x00007f5ee9a0a283 epoll_wait
    #1  0x000000000052c455 dart::bin::EventHandlerImplementation::Poll(unsigned long)
    #2  0x0000000000547a7e dart::bin::ThreadStart(void*)
    #3  0x00007f5eea704184 start_thread
    #4  0x00007f5ee9a09bed __clone
    TID 2725:
    #0  0x00007f5eea708404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000863db5 dart::Monitor::WaitMicros(long)
    #2  0x000000000096a21f dart::ThreadInterrupter::ThreadMain(unsigned long)
    #3  0x00000000008634f9 dart::ThreadStart(void*)
    #4  0x00007f5eea704184 start_thread
    #5  0x00007f5ee9a09bed __clone
    TID 2727:
    #0  0x00007f5eea708404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000863db5 dart::Monitor::WaitMicros(long)
    #2  0x00000000006b8f6a dart::BackgroundCompiler::Run()
    #3  0x000000000096aedd dart::ThreadPool::Worker::Loop()
    #4  0x000000000096adab dart::ThreadPool::Worker::Main(unsigned long)
    #5  0x00000000008634f9 dart::ThreadStart(void*)
    #6  0x00007f5eea704184 start_thread
    #7  0x00007f5ee9a09bed __clone
    TID 2729:
    #0  0x00007f5eea708404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000863db5 dart::Monitor::WaitMicros(long)
    #2  0x00000000006b8f6a dart::BackgroundCompiler::Run()
    #3  0x000000000096aedd dart::ThreadPool::Worker::Loop()
    #4  0x000000000096adab dart::ThreadPool::Worker::Main(unsigned long)
    #5  0x00000000008634f9 dart::ThreadStart(void*)
    #6  0x00007f5eea704184 start_thread
    #7  0x00007f5ee9a09bed __clone
    TID 2794:
    #0  0x00007f5eea708404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000863db5 dart::Monitor::WaitMicros(long)
    #2  0x00000000007a04d0 dart::Isolate::PauseEventHandler()
    #3  0x00000000006cef11 dart::Debugger::Pause(dart::ServiceEvent*)
    #4  0x00000000006d670e dart::Debugger::PauseException(dart::Instance const&)
    #5  0x00000000006e7596 dart::Exceptions::Throw(dart::Thread*, dart::Instance const&)
    #6  0x00000000009aa58c dart::DRT_Throw(dart::NativeArguments)
    #7  0x00007f5eeaba061b
    
    eu-stack: dwfl_thread_getframes tid 2794 at 0x7f5eeaba061a in /lib/x86_64-linux-gnu/ld-2.19.so: no matching address range
    

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseX64/dart -DDART_SERVICE_USE_AUTH=false --pause-isolates-on-unhandled-exceptions --snapshot=/b/build/slave/app-linux-release-x64-be/build/sdk/out/ReleaseX64/generated_compilations/app_jit/runtime_observatory_tests_service_pause_on_unhandled_async_exceptions2_test.dart_1/out.jitsnapshot --snapshot-kind=app-jit --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-release-x64-be/build/sdk/.packages --enable-vm-service:0 /b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart
>testee>out> Observatory listening on http://127.0.0.1:38680/
** Signaled to run test queries on http://127.0.0.1:38680/
>testee>out> 
Loading VM...
>testee>out> 4950


Command[app_jit]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --snapshot=/b/build/slave/app-linux-release-x64-be/build/sdk/out/ReleaseX64/generated_compilations/app_jit/runtime_observatory_tests_service_pause_on_unhandled_async_exceptions2_test.dart_1/out.jitsnapshot --snapshot-kind=app-jit --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-release-x64-be/build/sdk/.packages /b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart
Took 0:01:00.203820

Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-release-x64-be/build/sdk/.packages /b/build/slave/app-linux-release-x64-be/build/sdk/out/ReleaseX64/generated_compilations/app_jit/runtime_observatory_tests_service_pause_on_unhandled_async_exceptions2_test.dart_1/out.jitsnapshot
Did not run

Short reproduction command (experimental):
    python tools/test.py -mrelease -capp_jit -t60 --builder-tag no_ipv6 service/pause_on_unhandled_async_exceptions2_test



===
=== 1 test failed
===
```

https://uberchromegw.corp.google.com/i/client.dart/builders/app-linux-release-x64-be/builds/4359/steps/vm%20tests/logs/stdio

```
=== Failure summary:


FAILED: app_jit-vm release_x64 service/pause_on_unhandled_async_exceptions2_test
Expected: Pass 
Actual: RuntimeError
Unexpected compile-time error.
CommandOutput[app_jit]:

stderr:
Unhandled exception:
<Received error while converting exception to string>
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      StringBuffer.StringBuffer (dart:core-patch/string_buffer_patch.dart:56)
#3      _Uri._toFilePath (dart:core/uri.dart:2632)
#4      _Uri.toFilePath (dart:core/uri.dart:2620)
#5      _ServiceTesteeLauncher._ServiceTesteeLauncher (file:///b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:86:54)
#6      _ServiceTesterRunner.run (file:///b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:284:23)
#7      runIsolateTests (file:///b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:411:32)
<asynchronous suspension>
#8      main (file:///b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart:57:15)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


Command[app_jit]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --snapshot=/b/build/slave/app-linux-release-x64-be/build/sdk/out/ReleaseX64/generated_compilations/app_jit/runtime_observatory_tests_service_pause_on_unhandled_async_exceptions2_test.dart_1/out.jitsnapshot --snapshot-kind=app-jit --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-release-x64-be/build/sdk/.packages /b/build/slave/app-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart
Took 0:00:00.890253

Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-release-x64-be/build/sdk/.packages /b/build/slave/app-linux-release-x64-be/build/sdk/out/ReleaseX64/generated_compilations/app_jit/runtime_observatory_tests_service_pause_on_unhandled_async_exceptions2_test.dart_1/out.jitsnapshot
Did not run

Short reproduction command (experimental):
    python tools/test.py -mrelease -capp_jit -t60 --builder-tag no_ipv6 service/pause_on_unhandled_async_exceptions2_test



===
=== 1 test failed
===
```

so 1 timeout and 2 "Received error while converting exception to string" --- and that's just on 1 waterfall screen. Marking as flaky.

**Comment by floitschG** [comment]
Also crashing. Updated the status file.

https://build.chromium.org/p/client.dart/builders/app-linux-debug-x64-be/builds/2678/steps/vm%20tests/logs/stdio

```
FAILED: app_jit-vm debug_x64 service/pause_on_unhandled_async_exceptions2_test
Expected: Pass RuntimeError Timeout 
Actual: Crash
Unexpected compile-time error.
CommandOutput[app_jit]:

stderr:
../../runtime/vm/object.cc: 17345: error: expected: this->Equals(type)
Dumping native stack trace for thread 3954
  [0x00000000009bf763] dart::Profiler::DumpStackTrace()
  [0x00000000009bf763] dart::Profiler::DumpStackTrace()
  [0x0000000000696191] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x00000000008efff0] dart::Type::Canonicalize(dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*) const
  [0x00000000006a16a0] dart::ClassFinalizer::FinalizeType(dart::Class const&, dart::AbstractType const&, dart::ClassFinalizer::FinalizationKind, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)
  [0x0000000000947cb9] dart::Parser::FinalizeFormalParameterTypes(dart::ParamList const*)
  [0x000000000093ebd7] dart::Parser::ParseFunc(dart::Function const&, bool)
  [0x000000000093ca0c] dart::Parser::ParseFunction(dart::ParsedFunction*)
  [0x00000000006fa8a0] dart::DartCompilationPipeline::ParseFunction(dart::ParsedFunction*)
  [0x0000000000700501] Unknown symbol
  [0x0000000000701639] dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)
  [0x00000000007035ab] dart::BackgroundCompiler::Run()
-- End of DumpStackTrace


Command[app_jit]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --snapshot=/b/build/slave/app-linux-debug-x64-be/build/sdk/out/DebugX64/generated_compilations/app_jit/runtime_observatory_tests_service_pause_on_unhandled_async_exceptions2_test.dart_1/out.jitsnapshot --snapshot-kind=app-jit --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-debug-x64-be/build/sdk/.packages /b/build/slave/app-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart
Took 0:00:02.598012

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/app-linux-debug-x64-be/build/sdk/.packages /b/build/slave/app-linux-debug-x64-be/build/sdk/out/DebugX64/generated_compilations/app_jit/runtime_observatory_tests_service_pause_on_unhandled_async_exceptions2_test.dart_1/out.jitsnapshot
Did not run

Short reproduction command (experimental):
    python tools/test.py -capp_jit -t240 --builder-tag no_ipv6 service/pause_on_unhandled_async_exceptions2_test
```

**Comment by stefantsov** [comment]
Another instance of this issue. This time on vm-mac-debug:

Link (will go stale): https://uberchromegw.corp.google.com/i/client.dart/builders/vm-mac-debug-simdbc64-be/builds/3025/steps/vm%20tests/logs/stdio

Relevant output:
```
FAILED: none-vm debug_simdbc64 service/pause_on_unhandled_async_exceptions2_test
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true xcodebuild/DebugSIMDBC64/dart -DDART_SERVICE_USE_AUTH=false --pause-isolates-on-unhandled-exceptions --error_on_bad_type --error_on_bad_override --async_debugger --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/.packages --enable-vm-service:0 /b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart
>testee>out> Observatory listening on http://127.0.0.1:59728/
** Signaled to run test queries on http://127.0.0.1:59728/
>testee>out> 
Loading VM...
>testee>out> 4950
Done loading VM
Running pause_on_unhandled_async_exceptions2_test.dart [1/2]
Paused with PauseException
Running pause_on_unhandled_async_exceptions2_test.dart [2/2]
We stopped!


stderr:
../../runtime/vm/scavenger.h: 166: error: expected: (thread->end() == 0) || (thread->end() == top_)
Dumping native stack trace for thread 1403
  [0x00000001025b1d77] dart::Profiler::DumpStackTrace(bool)
  [0x00000001025b1d77] dart::Profiler::DumpStackTrace(bool)
  [0x0000000102739520] cbb_add_hex.hextable
-- End of DumpStackTrace


Command[vm]: DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --error_on_bad_type --error_on_bad_override --async_debugger --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/.packages /b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart
Took 0:00:03.850745

Short reproduction command (experimental):
    python tools/test.py -a simdbc64 service/pause_on_unhandled_async_exceptions2_test
```

Also, the test left a live Dart process that was killed by the following taskkill command:

```
Hanging process info:
  PID: 69175
  Command line: xcodebuild/DebugSIMDBC64/dart -DDART_SERVICE_USE_AUTH=false --pause-isolates-on-unhandled-exceptions --error_on_bad_type --error_on_bad_override --async_debugger --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/.packages --enable-vm-service:0 /b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart
```

**Comment by rmacnak-google** [comment]
This test suite was deleted.
