### ISSUE TITLE
Analyzer plugin crashes in IntelliJ

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#29175]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-171.3780.79`
- `1.22.1`
- `WS-171.3780.79, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.3 unknown, screens 1440x900  Retina`

## Exception

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Task failed: StrongModeVerifyUnitTask for source /Users/filiph/dev/edgehead/tool/parse_writers_input.dart
Unexpected exception while performing StrongModeVerifyUnitTask for source /Users/filiph/dev/edgehead/tool/parse_writers_input.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.delayed.<anonymous closure> (dart:async/future.dart:268)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by NoSuchMethodError: The getter 'isDynamic' was called on null.
Receiver: null
Tried calling: isDynamic
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      CodeChecker._checkForUnsafeBlockClosureInference (package:analyzer/src/task/strong/checker.dart:740)
#3      CodeChecker.visitFunctionExpression (package:analyzer/src/task/strong/checker.dart:432)
#4      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5347)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#6      ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#7      RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:605)
#8      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#9      MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7656)
#10     CodeChecker.visitMethodInvocation (package:analyzer/src/task/strong/checker.dart:567)
#11     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7649)
#12     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#13     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:815)
#14     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#16     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
```

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Task failed: StrongModeVerifyUnitTask for source /Users/filiph/dev/edgehead/tool/parse_writers_input.dart
Unexpected exception while performing StrongModeVerifyUnitTask for source /Users/filiph/dev/edgehead/tool/parse_writers_input.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.delayed.<anonymous closure> (dart:async/future.dart:268)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by NoSuchMethodError: The getter 'isDynamic' was called on null.
Receiver: null
Tried calling: isDynamic
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      CodeChecker._checkForUnsafeBlockClosureInference (package:analyzer/src/task/strong/checker.dart:740)
#3      CodeChecker.visitFunctionExpression (package:analyzer/src/task/strong/checker.dart:432)
#4      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5347)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#6      ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#7      RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:605)
#8      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#9      MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7656)
#10     CodeChecker.visitMethodInvocation (package:analyzer/src/task/strong/checker.dart:567)
#11     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7649)
#12     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#13     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:815)
#14     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#16     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#17     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:647)
#18     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#19     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#20     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:653)
#21     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#22     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5353)
#23     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:869)
#24     CodeChecker.visitFunctionExpression (package:analyzer/src/task/strong/checker.dart:433)
#25     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5347)
#26     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5197)
#27     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:857)
#28     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5190)
#29     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#30     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#31     CodeChecker.visitCompilationUnit (package:analyzer/src/task/strong/checker.dart:305)
#32     StrongModeVerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:6179)
#33     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#34     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#35     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#36     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#37     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#38     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#39     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#40     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#41     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#42     Future.Future.delayed.<anonymous closure> (dart:async/future.dart:268)
#43     _rootRun (dart:async/zone.dart:1146)
#44     _CustomZone.run (dart:async/zone.dart:1026)
#45     _CustomZone.runGuarded (dart:async/zone.dart:924)
#46     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#47     _rootRun (dart:async/zone.dart:1150)
#48     _CustomZone.run (dart:async/zone.dart:1026)
#49     _CustomZone.runGuarded (dart:async/zone.dart:924)
#50     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#51     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#52     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#53     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

Please append the contents of:
file:///private/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/report2.txt

```
1490673536575 <= {"id":"256"}
1490673536575 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1490673536575 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1490673536582 <= {"event":"analysis.implemented","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","classes":[{"offset":14526,"length":19}],"members":[{"offset":15020,"length
1490673536822 => {"id":"257","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":13282,"length":0},"clientRequestTime":1490673536822}
1490673536825 => {"id":"258","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":13282,"length":0},"clientRequestTime":1490673536825}
1490673536825 <= {"id":"257","result":{"assists":[{"message":"Split variable declaration","edits":[{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","fileStamp":0,"edits":[{"offset":1
1490673536827 => {"id":"259","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":13282,"length":0},"clientRequestTime":1490673536827}
1490673536828 <= {"id":"258","result":{"assists":[{"message":"Split variable declaration","edits":[{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","fileStamp":0,"edits":[{"offset":1
1490673536831 <= {"id":"259","result":{"assists":[{"message":"Split variable declaration","edits":[{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","fileStamp":0,"edits":[{"offset":1
1490673538585 => {"id":"260","method":"edit.getFixes","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":13283},"clientRequestTime":1490673538585}
1490673538586 <= {"id":"260","result":{"fixes":[{"error":{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":13284,"leng
1490673538587 => {"id":"261","method":"edit.getFixes","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":13284},"clientRequestTime":1490673538587}
1490673538588 <= {"id":"261","result":{"fixes":[{"error":{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":13284,"leng
1490673538588 => {"id":"262","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":13284,"length":0},"clientRequestTime":1490673538588}
1490673538589 <= {"id":"262","result":{"assists":[{"message":"Split variable declaration","edits":[{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","fileStamp":0,"edits":[{"offset":1
1490673538590 => {"id":"263","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":13284,"length":0},"clientRequestTime":1490673538590}
1490673538591 <= {"id":"263","result":{"assists":[{"message":"Split variable declaration","edits":[{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","fileStamp":0,"edits":[{"offset":1
1490673538591 => {"id":"264","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":13284,"length":0},"clientRequestTime":1490673538591}
1490673538591 <= {"id":"264","result":{"assists":[{"message":"Split variable declaration","edits":[{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","fileStamp":0,"edits":[{"offset":1
1490673542869 => {"id":"265","method":"analysis.updateContent","params":{"files":{"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart":{"type":"add","content":"library parse_writers_input;\n\nim
1490673542869 => {"id":"266","method":"completion.getSuggestions","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":13285},"clientRequestTime":1490673542869}
1490673542875 <= {"id":"265","result":{}}
1490673542875 <= {"id":"266","result":{"id":"23"}}
1490673542876 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1490673542879 <= {"event":"analysis.highlights","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":28},{"type":"BUILT_IN","o
1490673542883 <= {"event":"analysis.navigation","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","regions":[{"offset":8,"length":19,"targets":[0]},{"offset":37,"length":12,"
1490673542883 <= {"event":"analysis.overrides","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","overrides":[{"offset":7187,"length":4,"superclassMember":{"element":{"kind":
1490673542883 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/User
1490673542947 <= {"event":"server.error","params":{"isFatal":false,"message":"Task failed: StrongModeVerifyUnitTask for source /Users/filiph/dev/edgehead/tool/parse_writers_input.dart","stackTrace":"U
```

**Comment by scheglov** [comment]
I have just landed a [change](https://github.com/dart-lang/sdk/commit/27ab6478b9072dfc7cabbc63a36dc3adef463998) that removes this code :-)
