### ISSUE TITLE
Crash on windows debug bot

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#29176]
https://uberchromegw.corp.google.com/i/client.dart/builders/vm-win-debug-x64-be/builds/3570/steps/checked%20vm%20tests/logs/stdio

```
=== Failure summary:


FAILED: none-vm-checked debug_x64 samples/sample_extension/test/sample_extension_script_snapshot_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
+ out\DebugX64\dart.exe --snapshot=C:\Users\CHROME~2\AppData\Local\Temp\sample_extension_db4977ee-1358-11e7-9ad3-005056030139\test_sample_synchronous_extension.dart.snapshot --snapshot-kind=script C:\Users\CHROME~2\AppData\Local\Temp\sample_extension_db4977ee-1358-11e7-9ad3-005056030139\test_sample_synchronous_extension.dart
Failing process stdout: 
Failing process stderr: e:\b\build\slave\vm-win-debug-x64-be\build\sdk\runtime\vm\object.h: 6482: error: expected: (value & kSmiTagMask) == kSmiTag

Dumping native stack trace for thread 1204

e:\b\build\slave\vm-win-debug-x64-be\build\sdk\runtime\vm\heap.cc: 214: error: expected: old_space_->iterating_thread_ != thread()

Aborting re-entrant request for stack trace.


End failing process stderr


stderr:
Unhandled exception:
Expect.fail('Test failed with exit code 3')
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.fail (package:expect/expect.dart:154:5)
#2      run (file:///E:/b/build/slave/vm-win-debug-x64-be/build/sdk/samples/sample_extension/test/sample_extension_test_helper.dart:43:12)
<asynchronous suspension>
#3      testNativeExtensions (file:///E:/b/build/slave/vm-win-debug-x64-be/build/sdk/samples/sample_extension/test/sample_extension_test_helper.dart:72:15)
<asynchronous suspension>
#4      main (file:///E:/b/build/slave/vm-win-debug-x64-be/build/sdk/samples/sample_extension/test/sample_extension_script_snapshot_test.dart:10:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


Command[vm]: set DART_CONFIGURATION=DebugX64 & out\DebugX64\dart.exe --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-debug-x64-be\build\sdk\.packages E:\b\build\slave\vm-win-debug-x64-be\build\sdk\samples\sample_extension\test\sample_extension_script_snapshot_test.dart
Took 0:00:02.223222

Short reproduction command (experimental):
    python tools/test.py --checked -t120 samples/sample_extension/test/sample_extension_script_snapshot_test



===
=== 1 test failed
===

```

**Comment by johnmccutchan** [comment]
@a-siva FYI

**Comment by jensjoha** [comment]
Happened again on vm-win-debug-ia32-russian-be 
 (https://uberchromegw.corp.google.com/i/client.dart/builders/vm-win-debug-ia32-russian-be/builds/2783/)

```
=== Failure summary:


FAILED: none-vm-checked debug_ia32samples/sample_extension/test/sample_extension_script_snapshot_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
+ out\DebugIA32\dart.exe --snapshot=C:\Users\CHROME~2\AppData\Local\Temp\sample_extension_a8dd5476-311d-11e7-babd-005056030209\test_sample_synchronous_extension.dart.snapshot --snapshot-kind=script C:\Users\CHROME~2\AppData\Local\Temp\sample_extension_a8dd5476-311d-11e7-babd-005056030209\test_sample_synchronous_extension.dart
Failing process stdout: 
Failing process stderr: e:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\runtime\vm\object.h: 6540: error: expected: (value & kSmiTagMask) == kSmiTag

Dumping native stack trace for thread 1374

e:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\runtime\vm\heap.cc: 214: error: expected: old_space_->iterating_thread_ != thread()

Aborting re-entrant request for stack trace.


End failing process stderr


stderr:
Unhandled exception:
Expect.fail('Test failed with exit code 3')
#0      Expect._fail (package:expect/expect.dart:464:5)
#1      Expect.fail (package:expect/expect.dart:183:5)
#2      run (file:///E:/b/build/slave/vm-win-debug-ia32-russian-be/build/sdk/samples/sample_extension/test/sample_extension_test_helper.dart:43:12)
<asynchronous suspension>
#3      testNativeExtensions (file:///E:/b/build/slave/vm-win-debug-ia32-russian-be/build/sdk/samples/sample_extension/test/sample_extension_test_helper.dart:76:15)
<asynchronous suspension>
#4      main (file:///E:/b/build/slave/vm-win-debug-ia32-russian-be/build/sdk/samples/sample_extension/test/sample_extension_script_snapshot_test.dart:10:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


Command[vm]: set DART_CONFIGURATION=DebugIA32 & out\DebugIA32\dart.exe --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\.packages E:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\samples\sample_extension\test\sample_extension_script_snapshot_test.dart
Took 0:00:05.690569

Short reproduction command (experimental):
    python tools/test.py -aia32 --checked -t120 samples/sample_extension/test/sample_extension_script_snapshot_test



===
=== 1 test failed
===
```

**Comment by mraleph** [comment]
I assume this is stale.
