### ISSUE TITLE
Improve quality of NSM errors for top-level invocations on new front-end

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#29170]
Compare errors below. Old FE has a much more understandable error message.

```
╭─ ~/src/dart/sdk ‹ 65b06efb58›
╰─$ out/ReleaseX64/dart --ignore-unrecognized-flags --packages=/usr/local/google/home/vegorov/src/dart/sdk/.packages /usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseX64/generated_tests/language/setter_no_getter_call_test_01.dart 
initializing
Unhandled exception:
NoSuchMethodError: No top-level getter 'topLevel' declared.
Receiver: top-level
Tried calling: topLevel
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:196)
#1      main (file:///usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseX64/generated_tests/language/setter_no_getter_call_test_01.dart:24:7)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151) 


╭─ ~/src/dart/sdk ‹ 65b06efb58›
╰─$ out/ReleaseX64/dart --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --ignore-unrecognized-flags --packages=/usr/local/google/home/vegorov/src/dart/sdk/.packages /usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseX64/generated_tests/language/setter_no_getter_call_test_01.dart
out/ReleaseX64/generated_tests/language/setter_no_getter_call_test_01.dart:24:7: Warning: Getter not found: 'topLevel'.
^Ainitializing
Unhandled exception:
NoSuchMethodError: Receiver: null
Tried calling: topLevel
#0      main (file:///usr/local/google/home/vegorov/src/dart/sdk/out/ReleaseX64/generated_tests/language/setter_no_getter_call_test_01.dart:24:7)
#1      _startIsolate.<anonymous closure> (patched_sdk/lib/isolate/isolate.dart:1239:19)
#2      _RawReceivePortImpl._handleMessage (patched_sdk/lib/isolate/isolate.dart:1129:12)             
```

**Comment by peter-ahe-google** [comment]
This is a library bug:

```
   * The [receiver] is the receiver of the method call.
   * That is, the object on which the method was attempted called.
   * If the receiver is `null`, it is interpreted as a call to a top-level
   * function of a library.
```

It's not clear how to deal with static methods, nor is it clear how to deal with NSM on null.

**Comment by peter-ahe-google** [comment]
My suggestion is that we add the following (external) constructors to `NoSuchMethodError`:

```
NoSuchMethodError.topLevelMember(...)
NoSuchMethodError.staticMember(...)
NoSuchMethodError.instanceMember(...) 
```

`NoSuchMethodError.instanceMember` could simply be the existing constructor.

In addition, I'd like to an additional parameter for giving alternative suggestions.

**Comment by lrhn** [comment]
There is no requirement that the errors thrown by the runtime system must use the exact classes of `dart:core`. If more context information is needed to ensure a good error message, we can introduce more error classes or more (private) constructors for the existing classes. This should be driven by the need of the runtime system, so removing area-library.
