### ISSUE TITLE
Analyser Error

### ISSUE THREAD

**Issue by jfphilbin** [dart-lang/sdk#29179]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-171.3780.79`
- `1.22.0`
- `WS-171.3780.79, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 3840x2160, 3840x2160, 3840x2160`

## Exception

Please append the contents of:
file://C:\Users\admin\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 1.22.0, server version 1.17.0, error: Failed to handle completion domain request: {clientRequestTime: 1490702875276, params: {file: C:\odw\sdk\dictionary\lib\src\vr\vr.dart, offset: 1228}, method: completion.getSuggestions, id: 2445}
AnalysisException: failed to resolve declarations
Caused by Instance of 'AnalysisNotScheduledError'
#0      PendingFuture.forciblyComplete (package:analyzer/src/context/context.dart:2223)
#1      AnalysisContextImpl._evaluatePendingFutures (package:analyzer/src/context/context.dart:1504)
#2      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1198)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#4      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#5      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#6      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#7      Future.Future.delayed.<anonymous closure> (dart:async/future.dart:268)
#8      _rootRun (dart:async/zone.dart:1146)
#9      _CustomZone.run (dart:async/zone.dart:1026)
#10     _CustomZone.run

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
