### ISSUE TITLE
Unexpected exception while performing ResolveDirectiveElementsTask

### ISSUE THREAD

**Issue by patkujawa-wf** [dart-lang/sdk#29187]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA PY-171.3780.115`
- `1.22.1`
- `PY-171.3780.115, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.11.6 unknown, screens 1440x900  Retina`

## Exception

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Task failed: ResolveDirectiveElementsTask for source /Users/patkujawa/.pub-cache/hosted/pub.workiva.org/frugal-2.2.0/lib/src/frugal.dart
Unexpected exception while performing ResolveDirectiveElementsTask for source /Users/patkujawa/.pub-cache/hosted/pub.workiva.org/frugal-2.2.0/lib/src/frugal.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by NoSuchMethodError: The getter 'imports' was called on null.
Receiver: null
Tried calling: imports
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      DirectiveResolver.visitImportDirective (package:analyzer/src/generated/resolver.dart:2344)
#3      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:6178)
#4      DirectiveResolver.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:2311)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#6      ResolveDirectiveElementsTask.internalPerform (package:analyzer/src/task/dart.dart:5085)
#7      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#8      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#9      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#10     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#11     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#13     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#14     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#15     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#16     Future.Future.<anonymous closure> (dart:async/future.dart:158)
#17     _rootRun (dart:async/zone.dart:1146)
#18     _CustomZone.run (dart:async/zone.dart:1026)
#19     _CustomZone.runGuarded (dart:async/zone.dart:924)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#21     _rootRun (dart:async/zone.dart:1150)
#22     _CustomZone.run (dart:async/zone.dart:1026)
#23     _CustomZone.runGuarded (dart:async/zone.dart:924)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#25     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```

```
1490731143476 <= {"id":"252"}
1490731143477 <= {"id":"253"}
1490731149166 => {"id":"254","method":"analysis.updateContent","params":{"files":{"/Users/patkujawa/.pub-cache/git/w_viewer-88aea700b002592c3dcbde4e8b70e9cac49ce1bd/lib/src/modules/content_renderer/co
1490731149168 <= {"id":"254","result":{}}
1490731150198 => {"id":"255","method":"analysis.setPriorityFiles","params":{"files":["/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart"]},"clientRequestTime
1490731150199 => {"id":"256","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart
1490731150200 <= {"id":"255"}
1490731150204 <= {"event":"analysis.overrides","params":{"file":"/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart","overrides":[{"offset":4664,"length":10,"
1490731150222 <= {"event":"analysis.navigation","params":{"file":"/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart","regions":[{"offset":7,"length":12,"targ
1490731150233 <= {"event":"analysis.highlights","params":{"file":"/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart","regions":[{"type":"DIRECTIVE","offset":
1490731150234 <= {"id":"256"}
1490731150234 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1490731150238 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1490731150250 <= {"event":"analysis.implemented","params":{"file":"/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart","classes":[],"members":[]}}
1490731150451 => {"id":"257","method":"edit.getAssists","params":{"file":"/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart","offset":11448,"length":0},"clie
1490731150452 => {"id":"258","method":"edit.getAssists","params":{"file":"/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart","offset":11448,"length":0},"clie
1490731152290 <= {"id":"257","result":{"assists":[{"message":"Split variable declaration","edits":[{"file":"/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart
1490731152291 <= {"id":"258","result":{"assists":[{"message":"Split variable declaration","edits":[{"file":"/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart
1490731155283 => {"id":"259","method":"analysis.setPriorityFiles","params":{"files":["/Users/patkujawa/.pub-cache/git/w_viewer-88aea700b002592c3dcbde4e8b70e9cac49ce1bd/lib/src/modules/content_renderer
1490731155283 => {"id":"260","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["/Users/patkujawa/.pub-cache/git/w_viewer-88aea700b002592c3dcbde4e8b70e9cac49ce1bd/lib/src/mo
1490731158083 => {"id":"261","method":"analysis.setPriorityFiles","params":{"files":["/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart"]},"clientRequestTime
1490731158083 => {"id":"262","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart
1490731160323 <= {"id":"259"}
1490731160324 <= {"event":"analysis.navigation","params":{"file":"/Users/patkujawa/.pub-cache/git/w_viewer-88aea700b002592c3dcbde4e8b70e9cac49ce1bd/lib/src/modules/content_renderer/content_renderer_ap
1490731160324 <= {"id":"260"}
1490731160325 <= {"id":"261"}
1490731160325 <= {"event":"analysis.navigation","params":{"file":"/Volumes/workspace/graph_app/lib/src/sox_ui/src/experiences/evidence_testing_experience.dart","regions":[],"targets":[],"files":[]}}
1490731160326 <= {"id":"262"}
1490731160326 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1490731170376 <= {"event":"server.error","params":{"isFatal":false,"message":"Task failed: ResolveDirectiveElementsTask for source /Users/patkujawa/.pub-cache/hosted/pub.workiva.org/frugal-2.2.0/lib/s
```

**Comment by devoncarew** [comment]
assumed stale
