### ISSUE TITLE
Laziness / out-of-order codegen

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29182]
This example is extracted from https://github.com/dart-lang/angular2_components

Consider 2 files, `lazy.dart` and `lazy2.dart`:

lazy.dart:
```dart
import 'lazy2.dart';

const _defaultPositions = const [
  RelativePosition.OffsetBottomRight
];

void main() {
  _defaultPositions.first.contentX.dump();
}
```

lazy2.dart:
```dart
import 'lazy.dart';
export 'lazy.dart' show main;

class Alignment {
  const Alignment();

  static const After = const _AfterCustomAlignment();
  static const Start = const _StartCustomAlignment();

  void dump() {}
}

class _AfterCustomAlignment extends Alignment {
  final int x = 42;

  const _AfterCustomAlignment();

  void dump() { print(x); }
}

class _StartCustomAlignment extends Alignment {
  final int x = 38;

  const _StartCustomAlignment();
}

class RelativePosition {

  static const OffsetBottomRight = const RelativePosition(contentX: Alignment.After);

  final Alignment contentX;
  const RelativePosition({this.contentX: Alignment.Start});
}
```
If I compile and run as below, I see an error:
```
> dartdevc --modules node -o lazy.js lazy.dart lazy2.dart 
> node -e "require('lazy').lazy.main()"
/Users/vsm/ddctest/lazy.js:28
    return const$1 || (const$1 = dart.const(new lazy2._AfterCustomAlignment()));
                                            ^
TypeError: lazy2._AfterCustomAlignment is not a constructor
    at After (/Users/vsm/ddctest/lazy.js:28:45)
    at Function.lazyGetter [as After] (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2681:16)
    at OffsetBottomRight (/Users/vsm/ddctest/lazy.js:47:76)
    at Function.lazyGetter [as OffsetBottomRight] (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2681:16)
    at Object.<anonymous> (/Users/vsm/ddctest/lazy.js:50:64)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Note, if I reverse the order of the dart files I pass to `dartdevc`, it works correctly (and prints 42).

**Comment by vsmenon** [comment]
This is the generated JS.  The exception occurs when `lazy._defaultPositions` is set.  This triggers an access to `lazy2._AfterCustomAlignment` before it's defined.

```
'use strict';
const dart_sdk = require('dart_sdk');
const core = dart_sdk.core;
const dart = dart_sdk.dart;
const dartx = dart_sdk.dartx;
const lazy = Object.create(null);
const lazy2 = Object.create(null);
let VoidTovoid = () => (VoidTovoid = dart.constFn(dart.definiteFunctionType(dart.void, [])))();
let const$;
let const$0;
let const$1;
let const$2;
lazy2.Alignment = class Alignment extends core.Object {
  new() {
  }
  dump() {}
};
dart.setSignature(lazy2.Alignment, {
  constructors: () => ({new: dart.definiteFunctionType(lazy2.Alignment, [])}),
  methods: () => ({dump: dart.definiteFunctionType(dart.void, [])}),
  sfields: () => ({
    After: lazy2._AfterCustomAlignment,
    Start: lazy2._StartCustomAlignment
  })
});
dart.defineLazy(lazy2.Alignment, {
  get After() {
    return const$1 || (const$1 = dart.const(new lazy2._AfterCustomAlignment()));
  },
  get Start() {
    return const$2 || (const$2 = dart.const(new lazy2._StartCustomAlignment()));
  }
});
lazy2.RelativePosition = class RelativePosition extends core.Object {
  new(opts) {
    let contentX = opts && 'contentX' in opts ? opts.contentX : lazy2.Alignment.Start;
    this.contentX = contentX;
  }
};
dart.setSignature(lazy2.RelativePosition, {
  constructors: () => ({new: dart.definiteFunctionType(lazy2.RelativePosition, [], {contentX: lazy2.Alignment})}),
  fields: () => ({contentX: lazy2.Alignment}),
  sfields: () => ({OffsetBottomRight: lazy2.RelativePosition})
});
dart.defineLazy(lazy2.RelativePosition, {
  get OffsetBottomRight() {
    return dart.const(new lazy2.RelativePosition({contentX: lazy2.Alignment.After}));
  }
});
lazy._defaultPositions = dart.constList([lazy2.RelativePosition.OffsetBottomRight], lazy2.RelativePosition);
lazy.main = function() {
  lazy._defaultPositions[dartx.first].contentX.dump();
};
dart.fn(lazy.main, VoidTovoid());
lazy2._AfterCustomAlignment = class _AfterCustomAlignment extends lazy2.Alignment {
  new() {
    this.x = 42;
    super.new();
  }
  dump() {
    core.print(this.x);
  }
};
dart.setSignature(lazy2._AfterCustomAlignment, {
  constructors: () => ({new: dart.definiteFunctionType(lazy2._AfterCustomAlignment, [])}),
  fields: () => ({x: core.int})
});
lazy2._StartCustomAlignment = class _StartCustomAlignment extends lazy2.Alignment {
  new() {
    this.x = 38;
    super.new();
  }
};
dart.setSignature(lazy2._StartCustomAlignment, {
  constructors: () => ({new: dart.definiteFunctionType(lazy2._StartCustomAlignment, [])}),
  fields: () => ({x: core.int})
});
lazy2.main = lazy.main;
// Exports:
exports.lazy = lazy;
exports.lazy2 = lazy2;
```

**Comment by vsmenon** [comment]
@jakemac53

**Comment by jmesserly** [comment]
I think this example would trigger an assert if DDC is run in checked mode. Basically, a top-level variable referencing a static field is not handled at all. This can be seen in startCheckingReferences, the comment by the asserts is not correct.

Offhand I think we should change startCheckingReferences to detect when we're already emitting top level code, but going to keep looking at this.

**Comment by jmesserly** [comment]
Yeah this is bad ... top-level const fields assume they can force other things to be in front of them if need be. Meanwhile static const fields just check if they are lazy based on what's already emitted or not. Unfortunately if the static field decides to be lazy, there's no mechanism for communicating this back to the top-level field. It looks like the top-level field does have a code path to handle this, if we could communicate back that the static field must not be accessed eagerly..

**Comment by jmesserly** [comment]
Chatted with everyone, we're gonna see what all lazy top-level fields look like.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2797443007/
