### ISSUE TITLE
Importing library intl by alt+enter hints on DateFormat field declaration

### ISSUE THREAD

**Issue by Thiltal** [dart-lang/sdk#29180]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA RM-171.3780.96`
- `1.22.1`
- `RM-171.3780.96, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-53-generic unknown, screens 1920x1080, 1920x1080`

## Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Task failed: GatherUsedLocalElementsTask for source /home/zdenek/WebstormProjects/front-end/lib/_common/model/user_group.dart
Unexpected exception while performing GatherUsedLocalElementsTask for source /home/zdenek/WebstormProjects/front-end/lib/_common/model/user_group.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find (UserGroup userGroup) → SelectOption in [(null userGroup) → dynamic]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3162)
#1      FunctionElementImpl.identifier (package:analyzer/src/dart/element/element.dart:4425)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3202)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2920)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2809)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10562)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3522)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5347)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:605)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#14     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7656)
#15     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1013)
#16     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7649)
#17     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9131)
#18     RecursiveAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:1098)
#19     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:9127)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#21     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#22     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:647)
#23     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#24     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#25     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:653)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#27     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7536)
#28     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1007)
#29     GatherUsedLocalElementsVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:3532)
#30     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7527)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#32     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#33     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:683)
#34     GatherUsedLocalElementsVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3502)
#35     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#36     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#37     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#38     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#39     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#40     GatherUsedLocalElementsTask.internalPerform (package:analyzer/src/task/dart.dart:3105)
#41     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#42     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#43     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#44     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#45     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#46     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#47     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#48     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#49     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#50     Future.Future.<anonymous closure> (dart:async/future.dart:158)
#51     _rootRun (dart:async/zone.dart:1146)
#52     _CustomZone.run (dart:async/zone.dart:1026)
#53     _CustomZone.runGuarded (dart:async/zone.dart:924)
#54     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#55     _rootRun (dart:async/zone.dart:1150)
#56     _CustomZone.run (dart:async/zone.dart:1026)
#57     _CustomZone.runGuarded (dart:async/zone.dart:924)
#58     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#59     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#60     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#61     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```

```
1490702977516 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/mindmup/model/attributes/attribute_group.dart","errors":[]}}
1490702977519 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/mindmup/model/attributes/attribute.dart","errors":[]}}
1490702977522 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/mindmup/model/attributes/custom_attribute.dart","errors":[{"severity":"INFO","type":"TODO","lo
1490702977523 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/mindmup/model/attributes/attribute_group.dart","errors":[]}}
1490702977525 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/wbs/services/wbs_journal_provider.dart","errors":[]}}
1490702977526 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/wbs/services/wbs_journal_detail_formatter.dart","errors":[]}}
1490702977527 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/wbs/services/wbs_journal_provider.dart","errors":[]}}
1490702977528 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/wbs/services/wbs_journal_detail_formatter.dart","errors":[]}}
1490702977528 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/rbs/services/rbs_service.dart","errors":[]}}
1490702977529 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/rbs/services/rbs_service.dart","errors":[]}}
1490702977530 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/wbs/services/wbs_service.dart","errors":[]}}
1490702977531 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/wbs/services/wbs_service.dart","errors":[]}}
1490702977534 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/mindmup/services/user_provider.dart","errors":[]}}
1490702977536 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/mindmup/services/user_provider.dart","errors":[]}}
1490702977549 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/_common/components/easy_lookup/easy_lookup.dart","errors":[]}}
1490702977554 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/_common/components/easy_lookup/easy_lookup.dart","errors":[{"severity":"INFO","type":"TODO","l
1490702977556 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/_common/lang.dart","errors":[]}}
1490702977561 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/_common/lang.dart","errors":[]}}
1490702977565 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/_common/model/availables/available_values.dart","errors":[]}}
1490702977567 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/_common/model/availables/available_project_values.dart","errors":[]}}
1490702977568 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/_common/model/availables/available_issue_values.dart","errors":[]}}
1490702977569 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/_common/model/availables/available_values.dart","errors":[]}}
1490702977569 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/_common/model/availables/available_project_values.dart","errors":[]}}
1490702977579 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/_common/model/availables/available_issue_values.dart","errors":[]}}
1490702977585 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/test/common_model/issue_available_values_test.dart","errors":[]}}
1490702977588 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/test/common_model/issue_available_values_test.dart","errors":[]}}
1490702977592 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/test/common_model/cf_test.dart","errors":[]}}
1490702977593 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/test/common_model/cf_test.dart","errors":[]}}
1490702977593 <= {"event":"analysis.errors","params":{"file":"/home/zdenek/WebstormProjects/front-end/lib/_common/model/model.dart","errors":[]}}
1490702977607 <= {"event":"server.error","params":{"isFatal":false,"message":"Task failed: GatherUsedLocalElementsTask for source /home/zdenek/WebstormProjects/front-end/lib/_common/model/user_group.d
```

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
