### ISSUE TITLE
Analyzer error in Webstorm 2017.1 / Dart SDK 1.22.1

### ISSUE THREAD

**Issue by emmanuele** [dart-lang/sdk#29203]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-171.3780.79`
- `1.22.1`
- `WS-171.3780.79, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception

Please append the contents of:
file://C:\Users\lemmanuele\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Task failed: ResolveUnitTask for source C:\devel\mlog-mric-js\mLogistics\lib\modules\accountRequestsManagement\accountRequestDetail\accountRequestInfo\AccountRequestInfoController.dart
Unexpected exception while performing ResolveUnitTask for source C:\devel\mlog-mric-js\mLogistics\lib\modules\accountRequestsManagement\accountRequestDetail\accountRequestInfo\AccountRequestInfoController.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Fut

**Comment by bwilkerson** [comment]
Thanks for the report! Unfortunately, there isn't enough information here for us to be able to reproduce the issue. That said, it looks similar to several issues that will be fixed in the 1.23 release (due in about a week), so please let us know if you continue to see this after updating.
