### ISSUE TITLE
service/async_single_step_exception_test fails on simdbc architectures

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#29218]
```
=== Failure summary:


FAILED: none-vm release_simdbc64 service/async_single_step_exception_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true xcodebuild/ReleaseSIMDBC64/dart -DDART_SERVICE_USE_AUTH=false --error_on_bad_type --error_on_bad_override --verbose_debug --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-release-simdbc64-be/build/sdk/.packages --enable-vm-service:0 /b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart
>testee>out> Observatory listening on http://127.0.0.1:63925/
** Signaled to run test queries on http://127.0.0.1:63925/
>testee>out> 
Loading VM...
>testee>out> HandleSteppingRequest- kStepOut 101c86270
>testee>out> >>> single step break at file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart:30 (func <testMain_async_body> token 136)
Done loading VM
Running async_single_step_exception_test.dart [1/27]
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [2/27]
Checking we are at line 30
Program is stopped at line: 30
Running async_single_step_exception_test.dart [3/27]
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [4/27]
>testee>out> HandleSteppingRequest- kStepOver 101c86270
>testee>out> mmmmm
>testee>out> >>> single step break at file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart:32 (func <testMain_async_body> token 149)
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [5/27]
Checking we are at line 32
Program is stopped at line: 32
Running async_single_step_exception_test.dart [6/27]
>testee>out> HandleSteppingRequest- kStepInto
>testee>out> Registering pending breakpoint for uncompiled function 'file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart_::_helper_<helper_async_body>' at line 22 col 1
>testee>out> Resolved BP 1 to pos 96, line 22 col 7, function 'file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart_::_helper_<helper_async_body>' (requested range 94-119, requested col -1)
>testee>out> Setting breakpoint 1 at line 22 col 7 for closure '<helper_async_body>'
>testee>out> >>> hit synthetic breakpoint at file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart:22 (token 96) (address 0x101b169b0)
>testee>out> HandleSteppingRequest- kStepOver 101c86270
>testee>out> >>> single step break at file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart:23 (func <helper_async_body> token 102)
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [7/27]
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [8/27]
Checking we are at line 23
Program is stopped at line: 23
Running async_single_step_exception_test.dart [9/27]
>testee>out> HandleSteppingRequest- kStepOver 101c86270
>testee>out> helper
>testee>out> >>> single step break at file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart:24 (func <helper_async_body> token 110)
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [10/27]
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [11/27]
Checking we are at line 24
Program is stopped at line: 24
Running async_single_step_exception_test.dart [12/27]
>testee>out> HandleSteppingRequest- kStepInto
>testee>out> >>> single step break at file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart:26 (func <helper_async_body> token 119)
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [13/27]
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [14/27]
>testee>out> HandleSteppingRequest- kStepInto
Paused with PauseBreakpoint
>testee>out> >>> single step break at file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart:28 (func <testMain_async_body> token 124)
Running async_single_step_exception_test.dart [15/27]
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [16/27]
>testee>out> HandleSteppingRequest- kStepInto
>testee>out> >>> single step break at file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart:35 (func <testMain_async_body> token 164)
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [17/27]
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [18/27]
Checking we are at line 35
Program is stopped at line: 35
Running async_single_step_exception_test.dart [19/27]
>testee>out> HandleSteppingRequest- kStepOver 101c866c8
>testee>out> error: a
>testee>out> >>> single step break at file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart:38 (func <testMain_async_body> token 181)
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [20/27]
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [21/27]
Paused with PauseBreakpoint
>testee>out> HandleSteppingRequest- kStepOver 101c866c8
>testee>out> foo
>testee>out> >>> single step break at file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart:40 (func <testMain_async_body> token 191)
Running async_single_step_exception_test.dart [22/27]
Paused with PauseBreakpoint
Running async_single_step_exception_test.dart [23/27]
Checking we are at line 38
** Killing script
Unexpected exception in service tests: Expected to be at line 38 but actually at line 40
Full stack trace:
 Frame([FrameKind.regular] testMain.<testMain_async_body> async_single_step_exception_test.dart:token(191)) [40]
 Frame([FrameKind.regular] _asyncErrorWrapperHelper.<anonymous closure> async_patch.dart:token(130)) [37]
 Frame([FrameKind.regular] _RootZone.runBinary zone.dart:token(9837)) [1376]
 Frame([FrameKind.regular] _FutureListener.handleError future_impl.dart:token(1150)) [142]
 Frame([FrameKind.regular] _Future._propagateToListeners.handleError future_impl.dart:token(4382)) [648]
 Frame([FrameKind.regular] _Future._propagateToListeners future_impl.dart:token(4531)) [669]
 Frame([FrameKind.regular] _Future._completeError future_impl.dart:token(3412)) [486]
 Frame([FrameKind.regular] _SyncCompleter._completeError future_impl.dart:token(462)) [55]
 Frame([FrameKind.regular] _Completer.completeError future_impl.dart:token(226)) [27]
 Frame([FrameKind.regular] helper.<helper_async_body> async_single_step_exception_test.dart:token(119)) [26]
 Frame([FrameKind.regular] Future.Future.microtask.<anonymous closure> future.dart:token(389)) [184]
 Frame([FrameKind.regular] _microtaskLoop schedule_microtask.dart:token(157)) [41]
 Frame([FrameKind.regular] _startMicrotaskLoop schedule_microtask.dart:token(184)) [50]
 Frame([FrameKind.regular] _runPendingImmediateCallback isolate_patch.dart:token(552)) [99]
 Frame([FrameKind.regular] _RawReceivePortImpl._handleMessage isolate_patch.dart:token(813)) [152]

#0      stoppedAtLine.<anonymous closure> (file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/service_test_common.dart:273:7)
<asynchronous suspension>
#1      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:326:23)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1128)
#3      _CustomZone.runUnary (dart:async/zone.dart:1012)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#7      _Future._completeWithValue (dart:async/future_impl.dart:478)
#8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#9      _rootRun (dart:async/zone.dart:1120)
#10     _CustomZone.run (dart:async/zone.dart:1001)
#11     _CustomZone.runGuarded (dart:async/zone.dart:901)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)



stderr:
Unhandled exception:
Expected to be at line 38 but actually at line 40
Full stack trace:
 Frame([FrameKind.regular] testMain.<testMain_async_body> async_single_step_exception_test.dart:token(191)) [40]
 Frame([FrameKind.regular] _asyncErrorWrapperHelper.<anonymous closure> async_patch.dart:token(130)) [37]
 Frame([FrameKind.regular] _RootZone.runBinary zone.dart:token(9837)) [1376]
 Frame([FrameKind.regular] _FutureListener.handleError future_impl.dart:token(1150)) [142]
 Frame([FrameKind.regular] _Future._propagateToListeners.handleError future_impl.dart:token(4382)) [648]
 Frame([FrameKind.regular] _Future._propagateToListeners future_impl.dart:token(4531)) [669]
 Frame([FrameKind.regular] _Future._completeError future_impl.dart:token(3412)) [486]
 Frame([FrameKind.regular] _SyncCompleter._completeError future_impl.dart:token(462)) [55]
 Frame([FrameKind.regular] _Completer.completeError future_impl.dart:token(226)) [27]
 Frame([FrameKind.regular] helper.<helper_async_body> async_single_step_exception_test.dart:token(119)) [26]
 Frame([FrameKind.regular] Future.Future.microtask.<anonymous closure> future.dart:token(389)) [184]
 Frame([FrameKind.regular] _microtaskLoop schedule_microtask.dart:token(157)) [41]
 Frame([FrameKind.regular] _startMicrotaskLoop schedule_microtask.dart:token(184)) [50]
 Frame([FrameKind.regular] _runPendingImmediateCallback isolate_patch.dart:token(552)) [99]
 Frame([FrameKind.regular] _RawReceivePortImpl._handleMessage isolate_patch.dart:token(813)) [152]

#0      _ServiceTesterRunner.run.<anonymous closure> (file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:341:9)
<asynchronous suspension>
#1      _rootRunBinary (dart:async/zone.dart:1144)
#2      _RootZone.runBinary (dart:async/zone.dart:1377)
#3      runZoned.<anonymous closure> (dart:async/zone.dart:1441)
#4      _CustomZone.handleUncaughtError (dart:async/zone.dart:981)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:552)
#6      _Future._completeError (dart:async/future_impl.dart:486)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:333:7)
<asynchronous suspension>
#10     _rootRunUnary (dart:async/zone.dart:1128)
#11     _CustomZone.runUnary (dart:async/zone.dart:1012)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#15     _Future._completeWithValue (dart:async/future_impl.dart:478)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     _CustomZone.runGuarded (dart:async/zone.dart:901)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)


Command[vm]: DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --error_on_bad_type --error_on_bad_override --verbose_debug --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-release-simdbc64-be/build/sdk/.packages /b/build/slave/vm-mac-release-simdbc64-be/build/sdk/runtime/observatory/tests/service/async_single_step_exception_test.dart
Took 0:00:04.994097

Short reproduction command (experimental):
    python tools/test.py -mrelease -asimdbc64 -t240 service/async_single_step_exception_test



===
=== 1 test failed
===

```

**Comment by a-siva** [comment]
Kernel bots also show a similar failure.

**Comment by alexmarkov** [comment]
Closing this issue as SIMDBC64 mode was removed a while ago.
