### ISSUE TITLE
Add cast on return in async functions instead of deferring

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29251]
This code:

```dart
import 'dart:async';

Future<List<String>> foo() async {
  List<Object> x = ["hello", "world"];
  return x.toList();
}

main() {
  foo().then(print);
}
```
generates a trace that's hard to work with:

```
/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:22343
  throw error;
  ^
Error
    at dart.throw (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2488:17)
    at dart.throwTypeError (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2007:13)
    at dart._throwTypeError (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2416:29)
    at dart.check (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2395:8)
    at Function.check_G [as _check] (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2448:17)
    at _Future.value (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:18934:21)
    at _AsyncCallbackEntry.async.scheduleMicrotask.dart.fn.e [as callback] (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:18192:28)
    at async._microtaskLoop (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:19253:11)
    at async._startMicrotaskLoop (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:19260:11)
    at Immediate.internalCallback [as _onImmediate] (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:19364:7)
```

**Comment by vsmenon** [comment]
Note, if I explicitly add a cast on return in the function above:
```dart
import 'dart:async';

Future<List<String>> foo() async {
  List<Object> x = ["hello", "world"];
  return x.toList() as FutureOr<List<String>>;
}

main() {
  foo().then(print);
}
```
we get a much easier trace:
```
Error
    at dart.throw (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2488:17)
    at dart.throwCastError (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2001:13)
    at dart._throwCastError (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2411:29)
    at dart.as (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2389:8)
    at Function.as_G [as as] (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2442:17)
    at /Users/vsm/ddctest/futureor.js:18:37
    at next (native)
    at onValue (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2045:22)
    at /Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2063:18
    at _AsyncCallbackEntry.async.scheduleMicrotask.dart.fn.e [as callback] (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:18192:29)
```

I.e., the failure shows right away instead of later in Future SDK code.

**Comment by vsmenon** [comment]
@jmesserly
