### ISSUE TITLE
Pub failure on local directories

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#29264]
The bot just flaked on the dart2js/source_map_pub_build_validity_test.

Afaict the test should not need http. However, the test failed with a `HTTP error 502: Bad Gateway` message.

/cc @munificent 

https://build.chromium.org/p/client.dart/builders/dart2js-linux-jsshell-1-4-be/builds/5355/steps/dart2js%20unit%20tests/logs/stdio

Relevant output:
```
FAILED: none-vm-checked release_x64 dart2js/source_map_pub_build_validity_test
Expected: Pass Slow 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done
Copying '/b/build/slave/dart2js-linux-jsshell-1-4-be/build/sdk/third_party/sunflower' to '/tmp/sourceMap_test-xVq34r'.
Running '/b/build/slave/dart2js-linux-jsshell-1-4-be/build/sdk/sdk/bin/pub get' from 'Directory: '/tmp/sourceMap_test-xVq34r''.
Resolving dependencies...

HTTP error 502: Bad Gateway
package:pub/src/source/hosted.dart 329:5                                                     BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 139:7                                                     BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 165:12                                                           BoundSource.getVersions
package:pub/src/solver/version_solver.dart 230:24                                            SolverCache.getVersions.<fn>
dart:async                                                                                   runZoned
package:pub/src/http.dart 228:10                                                             withDependencyType
package:pub/src/solver/version_solver.dart 229:19                                            SolverCache.getVersions
===== asynchronous gap ===========================
package:pub/src/solver/unselected_package_queue.dart 121:38                                  UnselectedPackageQueue._getNumVersions
===== asynchronous gap ===========================
package:pub/src/solver/unselected_package_queue.dart 50:33                                   UnselectedPackageQueue.add
===== asynchronous gap ===========================
package:pub/src/solver/version_selection.dart 68:27                                          VersionSelection.select.<fn>
===== asynchronous gap ===========================
dart:async                                                                                   Future.forEach
package:pub/src/solver/version_selection.dart 61:18                                          VersionSelection.select
===== asynchronous gap ===========================
package:pub/src/solver/backtracking_solver.dart 171:24                                       BacktrackingSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 41:10                                             resolveVersions.<fn>
package:pub/src/log.dart 408:18                                                              progress
package:pub/src/solver/version_solver.dart 39:10                                             resolveVersions
package:pub/src/entrypoint.dart 190:24                                                       Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 38:23                                                       GetCommand.run
package:args/command_runner.dart 194:27                                                      CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168:49                                                   PubCommandRunner.runCommand.<fn>
dart:async                                                                                   Future.Future.sync
package:pub/src/utils.dart 99:9                                                              captureErrors.<fn>
dart:async                                                                                   runZoned
package:pub/src/utils.dart 118:5                                                             captureErrors
package:pub/src/command_runner.dart 168:13                                                   PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117:11                                                   PubCommandRunner.run
===== asynchronous gap ===========================
/b/build/slave/dart2js-linux-jsshell-1-4-be/build/sdk/third_party/pkg/pub/bin/pub.dart 8:26  main
This is an unexpected error. Please run

    pub --trace get

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new



stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <69>, 'Unexpected exitCode from pub get') fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main.<anonymous closure> (file:///b/build/slave/dart2js-linux-jsshell-1-4-be/build/sdk/tests/compiler/dart2js/source_map_pub_build_validity_test.dart:31:14)
<asynchronous suspension>
#3      asyncTest (package:async_helper/async_helper.dart:93:4)
#4      main (file:///b/build/slave/dart2js-linux-jsshell-1-4-be/build/sdk/tests/compiler/dart2js/source_map_pub_build_validity_test.dart:13:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/b/build/slave/dart2js-linux-jsshell-1-4-be/build/sdk/.packages /b/build/slave/dart2js-linux-jsshell-1-4-be/build/sdk/tests/compiler/dart2js/source_map_pub_build_validity_test.dart
Took 0:00:05.390734

Short reproduction command (experimental):
    python tools/test.py -mrelease --checked -t60 --use-sdk --reset-browser-configuration dart2js/source_map_pub_build_validity_test

```

**Comment by sigmundch** [comment]
Seems like for eons this test has been reaching out the network to call pub-get: https://github.com/dart-lang/sdk/blob/master/tests/compiler/dart2js/source_map_pub_build_validity_test.dart#L26

I sent a fix to bypass this here https://codereview.chromium.org/2824083002/

Technically we could an offline pub-cache and what not, but in this case the entire example is self contained and the only dependency is for development (package:browser). I made the test override the pubspec.yaml to skip all that unnecessary boilerplate.

**Comment by sigmundch** [comment]
oops - didn't include you @floitschG in the review initially, I just sent the CL your way.

**Comment by mkustermann** [comment]
Seems like @sigmundch has change the test to use `pub get --offline`, so I'll close this issue.
