### ISSUE TITLE
get_native_allocation_samples_test failed on bot.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#29262]
get_native_allocation_samples_test failed on debug_x64

Log (will go stale): https://build.chromium.org/p/client.dart/builders/vm-linux-debug-x64-be/builds/12725/steps/checked%20vm%20tests/logs/stdio

Relevant output:

```
FAILED: none-vm-checked debug_x64 service/get_native_allocation_samples_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true out/DebugX64/dart -DDART_SERVICE_USE_AUTH=false --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/.packages --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/get_native_allocation_samples_test.dart
>testee>out> Observatory listening on http://127.0.0.1:37368/
** Signaled to run test queries on http://127.0.0.1:37368/
>testee>out> 
Loading VM...
Done loading VM
Running get_native_allocation_samples_test.dart [1/2]
>testee>err> ../../runtime/vm/object.h: 6501: error: expected: (value & kSmiTagMask) == kSmiTag
>testee>err> Dumping native stack trace for thread 3ce1
>testee>err> ../../runtime/vm/heap.cc: 214: error: expected: old_space_->iterating_thread_ != thread()
>testee>err> Aborting re-entrant request for stack trace.
** Killing script
Unexpected exception in service tests: NetworkRpcException(Canceling request: WebSocket closed(id: 6 method: _getNativeAllocationSamples params: {tags: None}))
#0      tests.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/get_native_allocation_samples_test.dart:61:9)
<asynchronous suspension>
#1      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:313:23)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1128)
#3      _CustomZone.runUnary (dart:async/zone.dart:1012)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#7      _Future._completeWithValue (dart:async/future_impl.dart:478)
#8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#9      _rootRun (dart:async/zone.dart:1120)
#10     _CustomZone.run (dart:async/zone.dart:1001)
#11     _CustomZone.runGuarded (dart:async/zone.dart:901)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)



stderr:
Unhandled exception:
NetworkRpcException(Canceling request: WebSocket closed(id: 6 method: _getNativeAllocationSamples params: {tags: None}))
#0      _ServiceTesterRunner.run.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:341:9)
<asynchronous suspension>
#1      _rootRunBinary (dart:async/zone.dart:1144)
#2      _RootZone.runBinary (dart:async/zone.dart:1377)
#3      runZoned.<anonymous closure> (dart:async/zone.dart:1441)
#4      _CustomZone.handleUncaughtError (dart:async/zone.dart:981)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:552)
#6      _Future._completeError (dart:async/future_impl.dart:486)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:333:7)
<asynchronous suspension>
#10     _rootRunUnary (dart:async/zone.dart:1128)
#11     _CustomZone.runUnary (dart:async/zone.dart:1012)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#15     _Future._completeWithValue (dart:async/future_impl.dart:478)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     _CustomZone.runGuarded (dart:async/zone.dart:901)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)


Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/get_native_allocation_samples_test.dart
Took 0:00:06.781683

Short reproduction command (experimental):
    python tools/test.py --checked -t120 service/get_native_allocation_samples_test

```

**Comment by alexmarkov** [comment]
This test doesn't run as it is filtered in status file:

```
[ $arch != ia32 || $arch != x64 || $system != linux ]
get_native_allocation_samples_test: Skip # Unsupported.
```

The condition `$arch != ia32 || $arch != x64` is always true - maybe it was meant to be `($arch != ia32 && $arch != x64)`.

Relevant commits:
[disabled the test entirely](https://codereview.chromium.org/2796283003/patch/40001/50001)
[disabled the test on all non-linux systems](https://codereview.chromium.org/2771293003/patch/100001/110017)

I tried to re-enable the test but it fails on linux/x64 with "ServerRpcException(Feature is disabled)":

```
tools/test.py --print-passing-stdout -m debug -a x64 -c dartk service/get_native_allocation_samples_test

Test configuration:
    custom configuration(architecture: x64, compiler: dartk, mode: debug, runtime: vm, system: linux, preview-dart-2)
Suites tested: service

FAILED: dartk-vm debug_x64 service/get_native_allocation_samples_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 04.000237s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --no-background-compilation --ignore-unrecognized-flags --packages=.packages runtime/observatory/tests/service/get_native_allocation_samples_test.dart

exit code:
255

stdout:
** Launching SERVICE_TEST_TESTEE=true out/DebugX64/dart --disable-service-auth-codes --profiler --no-background-compilation --ignore-unrecognized-flags --packages=.packages --enable-vm-service:0 runtime/observatory/tests/service/get_native_allocation_samples_test.dart
>testee>out> Observatory listening on http://127.0.0.1:41147/
** Signaled to run test queries on http://127.0.0.1:41147/
>testee>out> 
Loading VM...
Done loading VM
Running get_native_allocation_samples_test.dart [1/2]
** Killing script
Unexpected exception in service tests: ServerRpcException(Feature is disabled)
#0      tests.<anonymous closure> (file://.../sdk/runtime/observatory/tests/service/get_native_allocation_samples_test.dart:58:9)
<asynchronous suspension>
#1      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file://.../sdk/runtime/observatory/tests/service/test_helper.dart:321:23)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

stderr:
Unhandled exception:
ServerRpcException(Feature is disabled)
#0      tests.<anonymous closure> (file://.../sdk/runtime/observatory/tests/service/get_native_allocation_samples_test.dart:58:9)
<asynchronous suspension>
#1      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file://.../sdk/runtime/observatory/tests/service/test_helper.dart:321:23)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

--- Re-run this test:
python tools/test.py -m debug -c dartk --print-passing-stdout service/get_native_allocation_samples_test

[00:04 | 100% | +    0 | -    1]
```

@bkonyi could you take a look?

**Comment by bkonyi** [comment]
This test should likely pass if you provide the `--profiler_native_memory` flag. This feature is disabled by default as it's really heavy weight. Enabling by default on the bots would likely cause us to timeout consistently.

**Comment by alexmarkov** [comment]
@bkonyi thank you!

This test works with `--profiler_native_memory`.

I'm going to re-enable the test with
```// VMOptions=--profiler_native_memory```

**Comment by bkonyi** [comment]
Thanks for handling that Alex!

**Comment by alexmarkov** [comment]
The test is flaky. Now it fails in the following way:

```
FAILED: dartk-vm release_x64 service/get_native_allocation_samples_test
  Expected: Pass
  Actual: RuntimeError
  --- Command "vm" (took 02.000865s):
  DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --profiler_native_memory --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/runtime/observatory/tests/service/get_native_allocation_samples_test.dart
  exit code:
  255
  stdout:
  ** Launching SERVICE_TEST_TESTEE=true out/ReleaseX64/dart --disable-service-auth-codes --profiler --profiler_native_memory --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages --enable-vm-service:0 /b/s/w/ir/runtime/observatory/tests/service/get_native_allocation_samples_test.dart
  >testee>out> Observatory listening on http://127.0.0.1:35767/
  ** Signaled to run test queries on http://127.0.0.1:35767/
  >testee>out> 
  Loading VM...
  Done loading VM
  Running get_native_allocation_samples_test.dart [1/2]
  Running get_native_allocation_samples_test.dart [2/2]
  ** Killing script
  Unexpected exception in service tests: Bad state: No element
  #0      Stream.last.<anonymous closure> (dart:async/stream.dart:1289:13)
  #1      _rootRun (dart:async/zone.dart:1120:38)
  #2      _CustomZone.run (dart:async/zone.dart:1021:19)
  #3      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
  #5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
  #6      _DelayedDone.perform (dart:async/stream_impl.dart:610:14)
  #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
  #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
  #9      _rootRun (dart:async/zone.dart:1120:38)
  #10     _CustomZone.run (dart:async/zone.dart:1021:19)
  #11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #13     _rootRun (dart:async/zone.dart:1124:13)
  #14     _CustomZone.run (dart:async/zone.dart:1021:19)
  #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
  #20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
  #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
  stderr:
  Unhandled exception:
  Bad state: No element
  #0      Stream.last.<anonymous closure> (dart:async/stream.dart:1289:13)
  #1      _rootRun (dart:async/zone.dart:1120:38)
  #2      _CustomZone.run (dart:async/zone.dart:1021:19)
  #3      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
  #5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
  #6      _DelayedDone.perform (dart:async/stream_impl.dart:610:14)
  #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
  #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
  #9      _rootRun (dart:async/zone.dart:1120:38)
  #10     _CustomZone.run (dart:async/zone.dart:1021:19)
  #11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #13     _rootRun (dart:async/zone.dart:1124:13)
  #14     _CustomZone.run (dart:async/zone.dart:1021:19)
  #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
  #20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
  #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
  --- Re-run this test:
  python tools/test.py -n dartk-linux-release-x64 service/get_native_allocation_samples_test
```

**Comment by alexmarkov** [comment]
CL to re-enable the test: https://dart-review.googlesource.com/c/sdk/+/110751
