### ISSUE TITLE
Analyser crashed in IDEA

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29314]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-171.4073.28`
- `1.24.0-edge.021d99e05deae069352f5b8d2c00f1ef0b1f00f3`
- `IU-171.4073.28, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Linux(amd64) v4.9.0-2-amd64 unknown, screens 3840x2160`

## Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.24.0-edge.021d99e05deae069352f5b8d2c00f1ef0b1f00f3, server version 1.18.0, error: Analysis failed: /home/zoechi/dart/myproj/bwu_ng_mdl/lib/src/dialog/dialog_component.dart
Bad state: No ErrorCode for LintCode.directives_ordering in /home/zoechi/dart/myproj/bwu_ng_mdl/lib/src/dialog/dialog_component.dart
#0      AnalysisDriver._getErrorsFromSerialized.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1117)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#2      ListIterable.toList (dart:_internal/iterable.dart:218)
#3      AnalysisDriver._getErrorsFromSerialized (package:analyzer/src/dart/analysis/driver.dart:1126)
#4      AnalysisDriver._getAnalysisResultFromBytes (package:analyzer/src/dart/analysis/driver.dart:1088)
#5      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:947)
#6      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:820)
<asynchronous suspension>
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1439)
<asynchronous suspension>
#8      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1372)
#9      AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:436)
#10     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)
#11     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#12     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:489)
#13     _rootRun (dart:async/zone.dart:1120)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     runZoned (dart:async/zone.dart:1465)
#16     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:528)
#17     Driver.start (package:analysis_server/src/server/driver.dart:488)
#18     main (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/analysis_server/bin/server.dart:12)
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)

**Comment by zoechi** [comment]
Issue moved to [dart-lang/linter #587](https://github.com/dart-lang/linter/issues/587) via [**ZenHub**](https://www.zenhub.com/)
