### ISSUE TITLE
Crash of analyzer in IntelliJ

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#29312]
Unsure if this is the same problem as previously, so filing just to be sure.

## Version information

- `IDEA 171.4073.15`
- `1.22.1`
- `WS-171.4073.15, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.3 unknown, screens 1440x900  Retina`

## Exception

Please append the contents of:
file:///private/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/report.txt

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Failed to handle completion domain request: {clientRequestTime: 1491769060939, params: {file: /Users/filiph/dev/edgehead/tool/parse_writers_input.dart, offset: 8304}, method: completion.getSuggestions, id: 10997}
AnalysisException: failed to resolve expression
Caused by Unexpected exception while performing ResolveVariableReferencesTask for source /Users/filiph/dev/edgehead/tool/parse_writers_input.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find String helpMessage in [String className, String forLocation, ClassBuilder classBuilder, bool hasRescue, String rescueSituationClassName, TypeBuilder classType, MethodBuilder isApplicableBuilder, num successChance, MethodBuilder applySuccessBuilder, String successDescription, MethodBuilder applyFailureBuilder, MethodBuilder successChanceBuilder, MethodBuilder rerollableBuilder, MethodBuilder rollReasonBuilder, MethodBuilder rerollResourceBuilder, String helpMessage, MethodBuilder helpMessageBuilder, MethodBuilder isAggressiveBuilder, FieldBuilder singletonBuilder]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3162)
#1      LocalVariableElementImpl.identifier (package:analyzer/src/dart/element/element.dart:6110)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3202)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2920)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2809)
#5      _HashFieldBase

```

Contents of file:

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Failed to handle completion domain request: {clientRequestTime: 1491769060939, params: {file: /Users/filiph/dev/edgehead/tool/parse_writers_input.dart, offset: 8304}, method: completion.getSuggestions, id: 10997}
AnalysisException: failed to resolve expression
Caused by Unexpected exception while performing ResolveVariableReferencesTask for source /Users/filiph/dev/edgehead/tool/parse_writers_input.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find String helpMessage in [String className, String forLocation, ClassBuilder classBuilder, bool hasRescue, String rescueSituationClassName, TypeBuilder classType, MethodBuilder isApplicableBuilder, num successChance, MethodBuilder applySuccessBuilder, String successDescription, MethodBuilder applyFailureBuilder, MethodBuilder successChanceBuilder, MethodBuilder rerollableBuilder, MethodBuilder rollReasonBuilder, MethodBuilder rerollResourceBuilder, String helpMessage, MethodBuilder helpMessageBuilder, MethodBuilder isAggressiveBuilder, FieldBuilder singletonBuilder]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3162)
#1      LocalVariableElementImpl.identifier (package:analyzer/src/dart/element/element.dart:6110)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3202)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2920)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2809)
#5      _HashFieldBase&_HashBase&_OperatorEqualsAndHashCode._hashCode (dart:collection-patch/compact_hash.dart:109)
#6      _CompactLinkedHashSet.add (dart:collection-patch/compact_hash.dart:480)
#7      VariableResolverVisitor.visitSimpleIdentifier (package:analyzer/src/generated/resolver.dart:10739)
#8      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9397)
#9      AssignmentExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:917)
#10     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#11     UnifyingAstVisitor.visitAssignmentExpression (package:analyzer/dart/ast/visitor.dart:2910)
#12     AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:913)
#13     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#14     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#15     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3005)
#16     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#18     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#19     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#20     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#21     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7317)
#22     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:7755)
#23     ScopedVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:7706)
#24     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:6035)
#25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#26     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#27     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#28     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#29     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7317)
#30     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#31     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#32     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#33     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#34     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7329)
#35     VariableResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:10615)
#36     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#37     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7536)
#38     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#39     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3106)
#40     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:7742)
#41     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:7734)
#42     VariableResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:10688)
#43     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7527)
#44     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#45     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:7398)
#46     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7375)
#47     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#48     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#49     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#50     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#51     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#52     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#53     ResolveVariableReferencesTask.internalPerform (package:analyzer/src/task/dart.dart:5941)
#54     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#55     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#56     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#57     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#58     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#59     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#60     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#61     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#62     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#63     Future.Future.<anonymous closure> (dart:async/future.dart:158)
#64     _rootRun (dart:async/zone.dart:1146)
#65     _CustomZone.run (dart:async/zone.dart:1026)
#66     _CustomZone.runGuarded (dart:async/zone.dart:924)
#67     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#68     _rootRun (dart:async/zone.dart:1150)
#69     _CustomZone.run (dart:async/zone.dart:1026)
#70     _CustomZone.runGuarded (dart:async/zone.dart:924)
#71     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#72     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#73     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#74     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#75     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisFutureHelper.computeAsync.<anonymous closure> (package:analyzer/src/context/context.dart:2031)
#1      PendingFuture.evaluate (package:analyzer/src/context/context.dart:2203)
#2      AnalysisFutureHelper.computeAsync (package:analyzer/src/context/context.dart:2037)
#3      DartCompletionRequestImpl._computeAsync.<_computeAsync_async_body> (package:analysis_server/src/services/completion/dart/completion_manager.dart:481)
#4      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#5      _rootRun (dart:async/zone.dart:1146)
#6      _CustomZone.run (dart:async/zone.dart:1026)
#7      _CustomZone.runGuarded (dart:async/zone.dart:924)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      DartCompletionRequestImpl._computeAsync.<_computeAsync_async_body> (package:analysis_server/src/services/completion/dart/completion_manager.dart:486)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _rootRunBinary (dart:async/zone.dart:1170)
#3      _CustomZone.runBinary (dart:async/zone.dart:1049)
#4      _FutureListener.handleError (dart:async/future_impl.dart:146)
#5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#7      _Future._completeError (dart:async/future_impl.dart:485)
#8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

```
1491769059977 <= {"event":"completion.results","params":{"id":"987","replacementOffset":8284,"replacementLength":16,"results":[],"isLast":true}}
1491769059978 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1491769059983 <= {"event":"analysis.implemented","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","classes":[],"members":[]}}
1491769060115 => {"id":"10992","method":"analysis.updateContent","params":{"files":{"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart":{"type":"add","content":"library parse_writers_input;\n\n
1491769060115 => {"id":"10993","method":"completion.getSuggestions","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":8302},"clientRequestTime":1491769060115}
1491769060117 <= {"id":"10992","result":{}}
1491769060118 <= {"id":"10993","result":{"id":"989"}}
1491769060120 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1491769060120 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/User
1491769060123 <= {"event":"completion.results","params":{"id":"988","replacementOffset":8284,"replacementLength":17,"results":[],"isLast":true}}
1491769060124 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1491769060130 <= {"event":"analysis.implemented","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","classes":[],"members":[]}}
1491769060196 => {"id":"10994","method":"analysis.updateContent","params":{"files":{"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart":{"type":"add","content":"library parse_writers_input;\n\n
1491769060196 => {"id":"10995","method":"completion.getSuggestions","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":8303},"clientRequestTime":1491769060196}
1491769060198 <= {"id":"10994","result":{}}
1491769060198 <= {"id":"10995","result":{"id":"990"}}
1491769060200 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1491769060201 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/User
1491769060203 <= {"event":"completion.results","params":{"id":"989","replacementOffset":8284,"replacementLength":18,"results":[],"isLast":true}}
1491769060204 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1491769060209 <= {"event":"analysis.implemented","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","classes":[],"members":[]}}
1491769060939 => {"id":"10996","method":"analysis.updateContent","params":{"files":{"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart":{"type":"add","content":"library parse_writers_input;\n\n
1491769060939 => {"id":"10997","method":"completion.getSuggestions","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","offset":8304},"clientRequestTime":1491769060939}
1491769060941 <= {"id":"10996","result":{}}
1491769060942 <= {"id":"10997","result":{"id":"991"}}
1491769060944 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1491769060944 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/edgehead/tool/parse_writers_input.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/User
1491769060947 <= {"event":"completion.results","params":{"id":"990","replacementOffset":8284,"replacementLength":19,"results":[],"isLast":true}}
1491769060947 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1491769060958 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {clientRequestTime: 1491769060939, params: {file: /Users/filiph/dev/edgehead/t
```

**Comment by natebosch** [comment]
We aren't able to repro stack traces from very old analyzer versions. Please file a new issue if you can repro with the current SDK.
