### ISSUE TITLE
No live ports in service/get_isolate_rpc_test

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#29324]
During my gardening shift today the `service/get_isolate_rpc_test` flaked (from [this failure](https://build.chromium.org/p/client.dart/builders/vm-win-debug-x64-be/builds/3701/steps/checked%20vm%20tests/logs/stdio)):

```

FAILED: none-vm-checked debug_x64 service/get_isolate_rpc_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true out\DebugX64\dart.exe -DDART_SERVICE_USE_AUTH=false --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-debug-x64-be\build\sdk\.packages --enable-vm-service:0 E:\b\build\slave\vm-win-debug-x64-be\build\sdk\runtime\observatory\tests\service\get_isolate_rpc_test.dart
>testee>out> Observatory listening on http://127.0.0.1:64998/
** Signaled to run test queries on http://127.0.0.1:64998/
>testee>out> 
Loading VM...
Done loading VM
Running get_isolate_rpc_test.dart [1/3]
** Killing script
Unexpected exception in service tests: Expected: a positive value
  Actual: <0>
   Which: is not a positive value

#0      DefaultFailureHandler.fail (package:unittest/src/matcher/expect.dart:117:5)
#1      DefaultFailureHandler.failMatch (package:unittest/src/matcher/expect.dart:121:5)
#2      expect (package:unittest/src/matcher/expect.dart:95:20)
#3      tests.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-x64-be/build/sdk/runtime/observatory/tests/service/get_isolate_rpc_test.dart:22:5)
<asynchronous suspension>
#4      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:313:23)
<asynchronous suspension>
#5      _rootRunUnary (dart:async/zone.dart:1128)
#6      _CustomZone.runUnary (dart:async/zone.dart:1012)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#10     _Future._completeWithValue (dart:async/future_impl.dart:478)
#11     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     _CustomZone.runGuarded (dart:async/zone.dart:901)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)



stderr:
Unhandled exception:
Expected: a positive value
  Actual: <0>
   Which: is not a positive value

#0      _ServiceTesterRunner.run.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:341:9)
<asynchronous suspension>
#1      _rootRunBinary (dart:async/zone.dart:1144)
#2      _RootZone.runBinary (dart:async/zone.dart:1377)
#3      runZoned.<anonymous closure> (dart:async/zone.dart:1441)
#4      _CustomZone.handleUncaughtError (dart:async/zone.dart:981)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:552)
#6      _Future._completeError (dart:async/future_impl.dart:486)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:333:7)
<asynchronous suspension>
#10     _rootRunUnary (dart:async/zone.dart:1128)
#11     _CustomZone.runUnary (dart:async/zone.dart:1012)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#15     _Future._completeWithValue (dart:async/future_impl.dart:478)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     _CustomZone.runGuarded (dart:async/zone.dart:901)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)


Command[vm]: set DART_CONFIGURATION=DebugX64 & out\DebugX64\dart.exe --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-debug-x64-be\build\sdk\.packages E:\b\build\slave\vm-win-debug-x64-be\build\sdk\runtime\observatory\tests\service\get_isolate_rpc_test.dart
Took 0:00:07.125712

Short reproduction command (experimental):
    python tools/test.py --checked -t120 service/get_isolate_rpc_test
```

It seems like this expectation is hit:
```
 22     expect(result['livePorts'], isPositive);
```

Is it ensured on the VM side that this will be positive?

@johnmccutchan

**Comment by floitschG** [comment]
The same test flaked again. (See below).
I have marked the test as flaky.

https://build.chromium.org/p/client.dart/builders/vm-win-debug-ia32-russian-be/builds/2701/steps/checked%20vm%20tests/logs/stdio

```
FAILED: none-vm-checked debug_ia32 service/get_isolate_rpc_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true out\DebugIA32\dart.exe -DDART_SERVICE_USE_AUTH=false --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\.packages --enable-vm-service:0 E:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\runtime\observatory\tests\service\get_isolate_rpc_test.dart
>testee>out> Observatory listening on http://127.0.0.1:64374/
** Signaled to run test queries on http://127.0.0.1:64374/
>testee>out> 
Loading VM...
Done loading VM
Running get_isolate_rpc_test.dart [1/3]
** Killing script
Unexpected exception in service tests: Expected: a positive value
  Actual: <0>
   Which: is not a positive value

#0      DefaultFailureHandler.fail (package:unittest/src/matcher/expect.dart:117:5)
#1      DefaultFailureHandler.failMatch (package:unittest/src/matcher/expect.dart:121:5)
#2      expect (package:unittest/src/matcher/expect.dart:95:20)
#3      tests.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-ia32-russian-be/build/sdk/runtime/observatory/tests/service/get_isolate_rpc_test.dart:22:5)
<asynchronous suspension>
#4      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-ia32-russian-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:313:23)
<asynchronous suspension>
#5      _rootRunUnary (dart:async/zone.dart:1128)
#6      _CustomZone.runUnary (dart:async/zone.dart:1012)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#10     _Future._completeWithValue (dart:async/future_impl.dart:478)
#11     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     _CustomZone.runGuarded (dart:async/zone.dart:901)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)



stderr:
Unhandled exception:
Expected: a positive value
  Actual: <0>
   Which: is not a positive value

#0      _ServiceTesterRunner.run.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-ia32-russian-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:341:9)
<asynchronous suspension>
#1      _rootRunBinary (dart:async/zone.dart:1144)
#2      _RootZone.runBinary (dart:async/zone.dart:1377)
#3      runZoned.<anonymous closure> (dart:async/zone.dart:1442)
#4      _CustomZone.handleUncaughtError (dart:async/zone.dart:981)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:552)
#6      _Future._completeError (dart:async/future_impl.dart:486)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-ia32-russian-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:333:7)
<asynchronous suspension>
#10     _rootRunUnary (dart:async/zone.dart:1128)
#11     _CustomZone.runUnary (dart:async/zone.dart:1012)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#15     _Future._completeWithValue (dart:async/future_impl.dart:478)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     _CustomZone.runGuarded (dart:async/zone.dart:901)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)


Command[vm]: set DART_CONFIGURATION=DebugIA32 & out\DebugIA32\dart.exe --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\.packages E:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\runtime\observatory\tests\service\get_isolate_rpc_test.dart
Took 0:00:07.454745

Short reproduction command (experimental):
    python tools/test.py -aia32 --checked -t120 service/get_isolate_rpc_test
```
