### ISSUE TITLE
analyser crashing after installing angular_analyzer_plugin

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29322]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-171.4073.28`
- `1.24.0-edge.078847f2cc580d4a9e1d31d7ea2d70bf94be22a9`
- `IU-171.4073.28, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Linux(amd64) v4.9.0-2-amd64 unknown, screens 3840x2160`

## Exception

Please append the contents of:
file:///tmp/report919.txt

```
Dart analysis server, SDK version 1.24.0-edge.078847f2cc580d4a9e1d31d7ea2d70bf94be22a9, server version 1.18.0, FATAL error: Failed to handle request: {clientRequestTime: 1491897209967, params: {included: [/home/myuser/dart/myproj/bwu_ng_mdl, /home/myuser/dart/myproj/fhir_client_api, /home/myuser/dart/myproj/fhir_designer, /home/myuser/dart/myproj/fhir_webui], excluded: [/home/myuser/dart/myproj/fhir_designer/.idea, /home/myuser/dart/myproj/bwu_ng_mdl/.pub, /home/myuser/dart/myproj/bwu_ng_mdl/build, /home/myuser/dart/myproj/fhir_client_api/.pub, /home/myuser/dart/myproj/fhir_client_api/build, /home/myuser/dart/myproj/fhir_designer/.pub, /home/myuser/dart/myproj/fhir_designer/build, /home/myuser/dart/myproj/fhir_webui/.pub, /home/myuser/dart/myproj/fhir_webui/build]}, method: analysis.setAnalysisRoots, id: 3}
RangeError: Value not in range: -5
#0      _StringBase.substring (dart:core-patch/string_patch.dart:363)
#1      PluginWatcher._checkPluginsFor.getPackageRoot (package:analysis_server/src/plugin/plugin_watcher.dart:98)
#2      PluginWatcher._checkPluginsFor (package:analysis_server/src/plugin/plugin_watcher.dart:108)
#3      PluginWatcher.addedDriver.<anonymous closure> (package:analysis_server/src/plugin/plugin_watcher.dart:56)
#4      _rootRunUnary (dart:async/zone.dart:1128)
#5      _CustomZone.runUnary (dart:async/zone.dart:1012)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#9      _SyncBroadcastStreamController._sendData.<anonymous closure> (dart:async/broadcast_stream_controller.dart:387)
#10     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:328)
#11     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:386)
#12     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254)
#13     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:480)
#14     _rootRunUnary (dart:async/zone.dart:1132)
#15     _CustomZone.runUnary (dart:async/zone.dart:1012)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#18     _DelayedData.perform (dart:async/stream_impl.dart:578)
#19     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
#20     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#21     _rootRun (dart:async/zone.dart:1116)
#22     _CustomZone.run (dart:async/zone.dart:1001)
#23     _CustomZone.runGuarded (dart:async/zone.dart:901)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#25     _rootRun (dart:async/zone.dart:1120)
#26     _CustomZone.run (dart:async/zone.dart:1001)
#27     _CustomZone.runGuarded (dart:async/zone.dart:901)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
```
[report919.txt](https://github.com/dart-lang/sdk/files/912532/report919.txt)

**Comment by bwilkerson** [comment]
I also saw this yesterday. It is unrelated to the angular plugin, and I will be investigating today.

**Comment by scheglov** [comment]
@bwilkerson I landed [the change](https://github.com/dart-lang/sdk/commit/6fe8e2278b2cb678ad016b6151c12d016bc7a7db) with which we should stop resolving `package` URIs to `NonExistingSource`, and will return `null` instead. This might fix the issue.

**Comment by bwilkerson** [comment]
It is fixed for the case I was seeing, so I'm going to assume that it's fixed.
