### ISSUE TITLE
I just updated to the latest build and restarted the analysis server in IntelliJ

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29384]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.4249.4`
- `1.24.0-edge.6a56c86c8181f4d9115a76b6fde81da44413d07f`
- `IU-171.4249.4, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Linux(amd64) v4.9.0-2-amd64 unknown, screens 3840x2160`

## Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.24.0-edge.6a56c86c8181f4d9115a76b6fde81da44413d07f, server version 1.18.0, error: Exception while using a _Visitor to visit a ForEachStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      List.single (dart:core-patch/array.dart:93)
#1      _Visitor.visitForEachStatement (package:linter/src/rules/omit_local_variable_types.dart:74)
#2      ForEachStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4706)
#3      ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2757)
#4      List.forEach (dart:core-patch/growable_array.dart:256)
#5      ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2755)
#6      UnifyingAstVisitor.visitForEachStatement (package:analyzer/dart/ast/visitor.dart:3017)
#7      ForEachStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4706)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#9      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#10     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#11     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#12     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#13     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#14     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#15     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#16     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#17     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#18     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#19     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#20     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#21     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5204)
#22     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#23     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026)
#24     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5197)
#25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#26     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#27     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#28     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#29     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#30     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:237)
#31     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120)
#32     _HashVMBase
```

[report.txt](https://github.com/dart-lang/sdk/files/932288/report.txt)

**Comment by alexeieleusis** [comment]
On it, this is our highest priority piece of work now.
