### ISSUE TITLE
Handling of main in Fasta, Kernel, and Dart VM

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29386]
Currently, the VM expects to find a method named `_getMainClosure` in the platform-private library `dart:_builtin`. This behavior is consistent with how the Dart VM interprets the specification, but not how dart2js does.

The difference between dart2js and the VM can be observed with this program:

```
get main => () {
      throw "I shouldn't be called.";
    };
```

In the Dart VM, this happens:

```
Unhandled exception:
I shouldn't be called.
#0      main.<anonymous closure> (file:///Users/ahe/w/dart-sdk/sdk/test.dart:2:7)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

In dart2js, this happens:

```
$ ./sdk/bin/dart2js test.dart
test.dart:1:5:
Warning: 'main' is not a function.
get main => () {
    ^^^^
$ ./third_party/d8/macos/d8 out.js
out.js:572: NoSuchMethodError: 'main' is not a function.
      throw H.wrapException(new H.MainError("'main' is not a function."));
      ^
NoSuchMethodError: 'main' is not a function.
    at dart.wrapException (out.js:553:17)
    at dart.badMain (out.js:572:15)
    at out.js:1054:9
    at init.currentScript (out.js:1034:7)
    at out.js:1049:5
    at out.js:1057:3
```

In either case, the specification isn't followed:

>A _script_ is a library whose exported namespace  (see Exports above) includes a top-level member named  `main`. It is a static warning if the static type of `main` is not assignable to a function type or is a function type with more than two required parameters.
>
>A script _S_ may be executed as follows:
>
>First, _S_ is compiled as a library as specified above. Then, the top-level function `main` that is in the exported namespace of _S_ is invoked. If `main` has no positional parameters, it is invoked with no arguments. Otherwise if `main` has exactly one positional parameter, it is invoked with a single actual argument whose runtime type implements `List<String>`.  Otherwise `main` is invoked with the following two actual arguments:
>
>1. An object whose runtime type implements `List<String>`.
>2. The initial message of the current isolate _i_ as determined by the invocation of `Isolate.spawnUri` that spawned _i_.
>
>It is a run time error if _S_ does not declare or export either:
>
>*  A top-level function named  `main`, or
>* A top-level getter named `main` that returns a function.

In dart2js' case, the specification isn't followed because a top-level getter named `main` that returns a function is present.

In the VM's case, the specification says nothing about invoking said getter, or how it's results should be invoked.

The specification needs to be clarified regarding this issue, and `pkg/kernel/lib/transformations/setup_builtin_library.dart` and Fasta may need adjustments. In addition, it is possible that the `main` property of a Kernel `Program` AST node needs to have its semantics adjusted.

**Comment by peter-ahe-google** [comment]
Blocked on #29387

**Comment by jensjoha** [comment]
Is this issue still valid?

`_getMainClosure` was removed in 8b7af73daafedacf0f239d17096703420937af69 and `setup_builtin_library.dart` was almost removed in 04f7ba272a65a3ea0e170b53c68e200deda959db (and `git grep setup_builtin_library` only finds the file itself).
