### ISSUE TITLE
The getter 'typeParameters' was called on null.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29416]
While doing nothing special, just editing Dart code.

[report2.txt](https://github.com/dart-lang/sdk/files/946669/report2.txt)
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-171.4249.21`
- `1.24.0-edge.7db51c7624a26e2c4cfded9f6ea962030a6797ba`
- `IU-171.4249.21, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Linux(amd64) v4.9.0-2-amd64 unknown, screens 3840x2160`

## Exception

Please append the contents of:
file:///tmp/report2.txt

```
Dart analysis server, SDK version 1.24.0-edge.7db51c7624a26e2c4cfded9f6ea962030a6797ba, server version 1.18.0, error: Captured exception
NoSuchMethodError: The getter 'typeParameters' was called on null.
Receiver: null
Tried calling: typeParameters
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      BindingTypeSynthesizer._instantiateClass (package:angular_analyzer_plugin/src/directive_extraction.dart:551)
#3      BindingTypeSynthesizer.BindingTypeSynthesizer (package:angular_analyzer_plugin/src/directive_extraction.dart:492)
#4      DirectiveLinker.resynthesizeDirectives (package:angular_analyzer_plugin/src/directive_linking.dart:50)
<asynchronous suspension>
#5      AngularDriver.resynthesizeDirectives (package:angular_analyzer_plugin/src/angular_driver.dart:595)
<asynchronous suspension>
#6      AngularDriver.getDirectives (package:angular_analyzer_plugin/src/angular_driver.dart:607)
<asynchronous suspension>
#7      AngularDriver.resolveDart (package:angular_analyzer_plugin/src/angular_driver.dart:493)
<asynchronous suspension>
#8      AngularDriver.pushDartErrors (package:angular_analyzer_plugin/src/angular_driver.dart:445)
<asynchronous suspension>
#9      AngularDriver.performWork (package:angular_analyzer_plugin/src/angular_driver.dart:202)
<asynchronous suspension>
#10     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1506)
<asynchronous suspension>
#11     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1436)
#12     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:448)
#13     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)
#14     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#15     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:489)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     runZoned (dart:async/zone.dart:1466)
#19     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:528)
#20     Driver.start (package:analysis_server/src/server/driver.dart:488)
#21     main (file:///home/zoechi/dart/dart-lang/angular_analyzer_plugin/server_plugin/bin/server.dart:20)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)

**Comment by MichaelRFairhurst** [comment]
Hmm. This is very strange to me. From what I can tell, this can only happen if:

1. someone has a ClassDeclaration ast node annotated with @Component or @Directive
and
2. the resulting unit element does not include that class

I'm trying to think of other possibilities...for instance, maybe a hash collision? So that step 2 got a completely different unit element?

Alternatively, trying to think if step 1 occurred with a newer or older version of the file than step 2, if that's possible. Unfortunately I think it is.


I think this means that we have a race condition we have to deal with. We may need a way to ensure that fileContentOverlay is not updated during some analysis execution which includes async gaps.

**Comment by bwilkerson** [comment]
@zoechi Were you editing Flutter code?

**Comment by zoechi** [comment]
@bwilkerson no, I didn't do anything with Flutter recently. 

@MichaelRFairhurst 
I didn't encounter this anymore since. 
Feel free to close and I just add a comment or create a new issue if I run into it again.

**Comment by hoaquo** [comment]
I have same problem while compiling code using ffi

Unhandled exception:
```
Crash when compiling file:///Users/hoaquo/Workspace/repository/testlib/lib/geometry/path_helper.dart,
at character offset 6235:
NoSuchMethodError: The getter 'typeParameters' was called on null.
Receiver: null
Tried calling: typeParameters
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      TypeInferrerImpl.getSetterType  (package:front_end/src/fasta/type_inference/type_inferrer.dart:1320:25)
#2      InferenceVisitor.visitPropertySet  (package:front_end/src/fasta/kernel/inference_visitor.dart:4441:38)
#3      PropertySet.accept1  (package:kernel/ast.dart:2792:9)

#4      TypeInferrerImpl.inferExpression  (package:front_end/src/fasta/type_inference/type_inferrer.dart:1477:27)
#5      InferenceVisitor.visitExpressionStatement  (package:front_end/src/fasta/kernel/inference_visitor.dart:726:49)
#6      ExpressionStatement.accept  (package:kernel/ast.dart:4491:43)
#7      TypeInferrerImpl.inferStatement  (package:front_end/src/fasta/type_inference/type_inferrer.dart:2646:22)
#18     TypeInferrerImpl.inferStatement  (package:front_end/src/fasta/type_inference/type_inferrer.dart:2646:22)
#19     TypeInferrerImpl.inferFunctionBody  (package:front_end/src/fasta/type_inference/type_inferrer.dart:1525:39)
#20     BodyBuilder.finishFunction  (package:front_end/src/fasta/kernel/body_builder.dart:910:28)
#21     DietListener.listenerFinishFunction  (package:front_end/src/fasta/source/diet_listener.dart:904:14)
#22     DietListener.buildFunctionBody  (package:front_end/src/fasta/source/diet_listener.dart:937:7)
#23     DietListener.endClassMethod  (package:front_end/src/fasta/source/diet_listener.dart:664:5)
#24     Parser.parseMethod  (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3480:20)
#25     Parser.parseClassOrMixinOrExtensionMemberImpl  (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3241:15)
#26     Parser.parseClassOrMixinOrExtensionBody  (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2974:15)
#27     Parser.parseClass  (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#28     Parser.parseClassOrNamedMixinApplication  (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1779:14)
#29     Parser.parseTopLevelKeywordDeclaration  (package:_fe_analyzer_shared/src/parser/parser_impl.dart:574:14)
#30     Parser.parseTopLevelDeclarationImpl  (package:_fe_analyzer_shared/src/parser/parser_impl.dart:470:14)
#31     Parser.parseUnit  (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#32     SourceLoader.buildBody  (package:front_end/src/fasta/source/source_loader.dart:312:14)
<asynchronous suspension>
#33     Loader.buildBodies  (package:front_end/src/fasta/loader.dart:243:15)
```

**Comment by scheglov** [comment]
@hoaquo The error message is close to the original one, but this is actually a different issue in a different sub-system (front-end it your case). @stefantsov
