### ISSUE TITLE
Analyzer crash on incomplete code

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29447]
Analyzer version: 0.30.0-alpha.3

Log:
```
===== FAILING OP: OperationType.Analysis, offset: null  =====
class A {}
class B extends A {}

typedef T 

main() {
  Function<
}
=====                                                 =====
AnalysisException: Cannot compute DART_ERRORS for StringSource (/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analyzerNNstLN/main.dart)
Caused by Unexpected exception while performing ParseDartTask for source /var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analyzerNNstLN/main.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199:27)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197:50)
#7      Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:204:24)
#8      Analyzer.analyzeMulti (package:services/src/analyzer.dart:138:7)
#9      Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#10     testAnalysis.<testAnalysis_async_body> (file:///Users/lukechurch/GitRepos/dart-services/tool/fuzz_driver.dart:241:35)
#11     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Caused by NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      Parser._tokenMatches (package:analyzer/src/generated/parser.dart:8071:60)
#3      Parser.skipFormalParameterList (package:analyzer/src/generated/parser.dart:5518:10)
#4      Parser.skipGenericFunctionTypeAfterReturnType (package:analyzer/src/generated/parser.dart:5539:12)
#5      Parser.skipTypeAnnotation (package:analyzer/src/generated/parser.dart:5655:14)
#6      Parser.skipReturnType (package:analyzer/src/generated/parser.dart:5593:14)
#7      Parser._couldBeStartOfCompilationUnitMember (package:analyzer/src/generated/parser.dart:5889:21)
#8      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:1990:14)
#9      Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:1865:12)
#10     ParseDartTask.internalPerform (package:analyzer/src/task/dart.dart:4114:35)
#11     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321:9)
#12     AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#13     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#14     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#15     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199:27)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#17     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197:50)
#18     Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:204:24)
#19     Analyzer.analyzeMulti (package:services/src/analyzer.dart:138:7)
#20     Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#21     testAnalysis.<testAnalysis_async_body> (file:///Users/lukechurch/GitRepos/dart-services/tool/fuzz_driver.dart:241:35)
#22     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:737:7)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:674:12)
#2      Analyzer.analyzeMulti.<anonymous closure> (package:services/src/analyzer.dart:142:18)
#3      List.forEach (dart:core-patch/growable_array.dart:258)
#4      Analyzer.analyzeMulti (package:services/src/analyzer.dart:141:19)
#5      Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#6      testAnalysis.<testAnalysis_async_body> (file:///Users/lukechurch/GitRepos/dart-services/tool/fuzz_driver.dart:241:35)
#7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2837033003/
