### ISSUE TITLE
Dart 1.23 analyzer crash "Element mismatch"

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/sdk#29444]
This code makes the dartanalyzer and analysis server 1.23 crash

`main.dart`
```dart
library lib;

part 'main_part.dart';

main() {
  new A(null);
}

```

`main_part.dart`
```dart
part of lib;

class A  {
  final dataAccess;

  A(this.dataAccess(String url));
}
```

```
C:\Users\xavier.hainaux\dart\bug_dart_1.23>dartanalyzer web/function/main.dart
Analyzing web\function\main.dart...
Unhandled exception:
AnalysisException: Element mismatch in C:\Users\xavier.hainaux\dart\bug_dart_1.23\web\function\main_part.dart at dynamic dataAccess
Caused by RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/array.dart:128)
#1      ElementWalker.getParameter (package:analyzer/src/generated/declaration_resolver.dart:761)
#2      DeclarationResolver.visitSimpleFormalParameter (package:analyzer/src/generated/declaration_resolver.dart:406)
#3      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9300)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#5      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4853)
#6      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:845)
#7      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4849)
#8      FieldFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4552)
#9      RecursiveAstVisitor.visitFieldFormalParameter (package:analyzer/dart/ast/visitor.dart:833)
#10     DeclarationResolver.visitFieldFormalParameter.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:202)
#11     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:585)
#12     DeclarationResolver.visitFieldFormalParameter (package:analyzer/src/generated/declaration_resolver.dart:201)
#13     FieldFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:4544)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#15     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4853)
#16     RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:845)
#17     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4849)
#18     ConstructorDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2996)
#19     RecursiveAstVisitor.visitConstructorDeclaration (package:analyzer/dart/ast/visitor.dart:725)
#20     DeclarationResolver.visitConstructorDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:112)
#21     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:585)
#22     DeclarationResolver.visitConstructorDeclaration (package:analyzer/src/generated/declaration_resolver.dart:110)
#23     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2989)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#25     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#26     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:683)
#27     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:90)
#28     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:585)
#29     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:89)
#30     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#32     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#33     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#34     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#35     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:50)
#36     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:511)
#37     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#38     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#39     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88)
#40     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:954)
#41     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1671)
#42     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:940)
#43     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:491)
<asynchronous suspension>
#44     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:131)
<asynchronous suspension>
#45     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:175)
<asynchronous suspension>
#46     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:121)
<asynchronous suspension>
#47     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:699)
<asynchronous suspension>
#48     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:245)
<asynchronous suspension>
#49     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167)
<asynchronous suspension>
#50     Driver.start (package:analyzer_cli/src/driver.dart:146)
<asynchronous suspension>
#51     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#52     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:53)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:511)
#2      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#4      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88)
#5      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:954)
#6      PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1671)
#7      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:940)
#8      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:491)
<asynchronous suspension>
#9      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:131)
<asynchronous suspension>
#10     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:175)
<asynchronous suspension>
#11     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:121)
<asynchronous suspension>
#12     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:699)
<asynchronous suspension>
#13     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:245)
<asynchronous suspension>
#14     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167)
<asynchronous suspension>
#15     Driver.start (package:analyzer_cli/src/driver.dart:146)
<asynchronous suspension>
#16     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:995)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1671)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:940)
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:491)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:131)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:175)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:121)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:699)
<asynchronous suspension>
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:245)
<asynchronous suspension>
#9      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167)
<asynchronous suspension>
#10     Driver.start (package:analyzer_cli/src/driver.dart:146)
<asynchronous suspension>
#11     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by natebosch** [comment]
Unfortunately we aren't going back to repro stack traces on very old versions of analyzer. If this still occurs with the latest SDK please add a comment to let us know.
