### ISSUE TITLE
Analyzer crash on typedef

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29446]
Src: 
```
typedef void Function();
```

Analyzer version: ```0.30.0-alpha.3```

Fuzz test result:

```
===== FAILING OP: OperationType.Analysis, offset: null  =====
typedef void Function();
=====                                                 =====
AnalysisException: Cannot compute DART_ERRORS for StringSource (/var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analyzernKP8PY/main.dart)
Caused by Unexpected exception while performing ParseDartTask for source /var/folders/kx/yl86m99n6zj1xl_zlyqv5mvm003cc5/T/analyzernKP8PY/main.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199:27)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197:50)
#7      Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:204:24)
#8      Analyzer.analyzeMulti (package:services/src/analyzer.dart:138:7)
#9      Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#10     testAnalysis.<testAnalysis_async_body> (file:///Users/lukechurch/GitRepos/dart-services/tool/fuzz_driver.dart:241:35)
#11     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Caused by NoSuchMethodError: The getter 'next' was called on null.
Receiver: null
Tried calling: next
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      Parser.skipTypeAnnotation (package:analyzer/src/generated/parser.dart:5658:19)
#3      Parser.skipReturnType (package:analyzer/src/generated/parser.dart:5589:16)
#4      Parser.hasReturnTypeInTypeAlias (package:analyzer/src/generated/parser.dart:333:18)
#5      Parser._parseFunctionTypeAlias (package:analyzer/src/generated/parser.dart:6966:9)
#6      Parser.parseTypeAlias (package:analyzer/src/generated/parser.dart:5164:12)
#7      Parser.parseCompilationUnitMember (package:analyzer/src/generated/parser.dart:2064:14)
#8      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:1973:20)
#9      Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:1865:12)
#10     ParseDartTask.internalPerform (package:analyzer/src/task/dart.dart:4114:35)
#11     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321:9)
#12     AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#13     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#14     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#15     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199:27)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#17     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197:50)
#18     Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:204:24)
#19     Analyzer.analyzeMulti (package:services/src/analyzer.dart:138:7)
#20     Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#21     testAnalysis.<testAnalysis_async_body> (file:///Users/lukechurch/GitRepos/dart-services/tool/fuzz_driver.dart:241:35)
#22     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by bwilkerson** [comment]
@floitschG Is the following valid?
```
typedef void Function();
```
My understanding is that `void Function()` should be parsed as a return type and that the parser should then report that it is missing the name of the typedef.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2836983002/
