### ISSUE TITLE
SIGBUG accessing Observatory on ARM Linux

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#29452]
```
gdb --args ./dart --observe --profile-vm hello.dart
...
Program received signal SIGBUS, Bus error.
[Switching to Thread 0x7654e440 (LWP 13119)]
0x0031f44a in readFrom (v=0x75c02ad4, this=0x7654c910) at ../../runtime/platform/globals.h:169
169	../../runtime/platform/globals.h: No such file or directory.
(gdb) bt
#0  0x0031f44a in readFrom (v=0x75c02ad4, this=0x7654c910) at ../../runtime/platform/globals.h:169
#1  dart::Int32x4::value (this=0x7654cdbc) at ../../runtime/vm/object.cc:22381
#2  0x004959b2 in DN_HelperTypedData_SetInt32x4 (isolate=<optimized out>, thread=<optimized out>, 
    arguments=0x7654cff0, zone=0x7654c990) at ../../runtime/lib/typed_data.cc:250
#3  dart::BootstrapNatives::DN_TypedData_SetInt32x4 (args=0x7654cff0) at ../../runtime/lib/typed_data.cc:250
#4  0x76bc73e0 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Maybe unaligned write?

**Comment by rmacnak-google** [comment]
dddd96cfd2984f4c157b8c3632ad2b5dcb25b9fc
