### ISSUE TITLE
Flaky debugger_location_test

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#29466]
The `debugger_location_test` just flaked on the Russian windows bot.

https://build.chromium.org/p/client.dart/builders/vm-win-debug-ia32-russian-be/builds/2703/steps/vm%20tests/logs/stdio

Relevant output:

```
FAILED: none-vm debug_ia32 service/debugger_location_test
Expected: Pass Slow 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true out\DebugIA32\dart.exe -DDART_SERVICE_USE_AUTH=false --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\.packages --enable-vm-service:0 E:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\runtime\observatory\tests\service\debugger_location_test.dart
>testee>out> Observatory listening on http://127.0.0.1:61641/
** Signaled to run test queries on http://127.0.0.1:61641/
>testee>out> 
Loading VM...
Done loading VM
Running debugger_location_test.dart [1/11]
Paused with PauseBreakpoint
Running debugger_location_test.dart [2/11]
Running debugger_location_test.dart [3/11]
Running debugger_location_test.dart [4/11]
Running debugger_location_test.dart [5/11]
** Killing script
Unexpected exception in service tests: NetworkRpcException(Canceling request: Connection saw corrupt JSON message: FormatException: Unexpected character (at character 1)
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...
^
(id: 107 method: getObject params: {objectId: libraries/@19468852, count: 100, isolateId: isolates/502995638}))
#0      DebuggerLocation._parseScriptLine (package:observatory/src/debugger/debugger_location.dart:91:21)
<asynchronous suspension>
#1      DebuggerLocation.parse (package:observatory/src/debugger/debugger_location.dart:35:14)
#2      tests.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-ia32-russian-be/build/sdk/runtime/observatory/tests/service/debugger_location_test.dart:86:38)
<asynchronous suspension>
#3      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-ia32-russian-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:326:23)
<asynchronous suspension>
#4      _rootRunUnary (dart:async/zone.dart:1128)
#5      _CustomZone.runUnary (dart:async/zone.dart:1012)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#9      _Future._completeWithValue (dart:async/future_impl.dart:478)
#10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#11     _rootRun (dart:async/zone.dart:1120)
#12     _CustomZone.run (dart:async/zone.dart:1001)
#13     _CustomZone.runGuarded (dart:async/zone.dart:901)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)



stderr:
Unhandled exception:
NetworkRpcException(Canceling request: Connection saw corrupt JSON message: FormatException: Unexpected character (at character 1)
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...
^
(id: 107 method: getObject params: {objectId: libraries/@19468852, count: 100, isolateId: isolates/502995638}))
#0      _ServiceTesterRunner.run.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-ia32-russian-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:341:9)
<asynchronous suspension>
#1      _rootRunBinary (dart:async/zone.dart:1144)
#2      _RootZone.runBinary (dart:async/zone.dart:1377)
#3      runZoned.<anonymous closure> (dart:async/zone.dart:1442)
#4      _CustomZone.handleUncaughtError (dart:async/zone.dart:981)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:552)
#6      _Future._completeError (dart:async/future_impl.dart:486)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/vm-win-debug-ia32-russian-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:333:7)
<asynchronous suspension>
#10     _rootRunUnary (dart:async/zone.dart:1128)
#11     _CustomZone.runUnary (dart:async/zone.dart:1012)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#15     _Future._completeWithValue (dart:async/future_impl.dart:478)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     _CustomZone.runGuarded (dart:async/zone.dart:901)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)


Command[vm]: set DART_CONFIGURATION=DebugIA32 & out\DebugIA32\dart.exe --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\.packages E:\b\build\slave\vm-win-debug-ia32-russian-be\build\sdk\runtime\observatory\tests\service\debugger_location_test.dart
Took 0:00:09.954000

Short reproduction command (experimental):
    python tools/test.py -aia32 -t120 service/debugger_location_test
```

**Comment by rmacnak-google** [comment]
This test suite was deleted.
