### ISSUE TITLE
Unhandled exception in Cookie constructor

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#29463]
Try to call Cookie constructor without optional arguments and you'll get NoSuchMethodError

```dart
import "dart:io";
main() {
  Cookie cookie = new Cookie();
}
```
Result:
```
Unhandled exception:
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _Cookie._validate (dart:io/http_headers.dart:979)
#3      _Cookie._Cookie (dart:io/http_headers.dart:844)
#4      Cookie.Cookie (dart:io/http.dart:868)
#5      main (file:///D:/Google/dart/co19/LibTest/io/Cookie/Cookie_A01_t01.dart:18:23)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

Process finished with exit code 255
```

Tested on Dart VM version: 1.24.0-dev.0.0 (Fri Apr 21 05:40:04 2017) on "windows_x64"

**Comment by sortie** [comment]
The co19 test needs to be updated per https://github.com/dart-lang/co19/issues/393.
