### ISSUE TITLE
Exception in Cookie.fromSetCookieValue() for empty cookie name

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#29492]
According RFC 6265 (https://tools.ietf.org/html/rfc6265), 5.2.  The Set-Cookie Header

>    5.  If the name string is empty, ignore the set-cookie-string entirely. 

But in Cookie.fromSetCookieValue() produces HttpException if set-cookie-string has empty name
```dart
import "dart:io";

main() {
  Cookie cookie = new Cookie.fromSetCookieValue("myname=myvalue;"); // works
  cookie = new Cookie.fromSetCookieValue("=myvalue;"); // Unhandled exception, see below
}
```
Result is
```
Unhandled exception:
HttpException: Failed to parse header value [=myvalue; expires=Mon, 17-Jul-2017 16:06:00 GMT; Max-Age=31449600; Path=/; secure]
#0      _Cookie._parseSetCookieValue (dart:io/http_headers.dart:929)
#1      _Cookie._Cookie.fromSetCookieValue (dart:io/http_headers.dart:849)
#2      Cookie.Cookie.fromSetCookieValue (dart:io/http.dart:875)
```
I think, in this case cookie object should be created but with empty properties

**Comment by lrhn** [comment]
This is a case of the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle). You are trying to create a cookie here, which will be passed to the server.
If that cookie has no name, the server will accept and ignore it, so you are just adding needless overhead. We could accept the call and send it, or accept the call and not send the cookie (which should have the same effect), but there is no need to ever do that, so it's most likely an error. 
So, we throw, to ensure that you don't do something useless.

I can't guarantee that this was done deliberately, and wasn't just an oversight, but the behavior is actually the one we want. The error message could be better though.

**Comment by sortie** [comment]
This is inconsistent with the Cookie constructor that lets one create an empty named cookie `new Cookie("", "x")` with toString() `=x; HttpOnly`.
