### ISSUE TITLE
Something goes wrong

### ISSUE THREAD

**Issue by mitrofanzzz** [dart-lang/sdk#29493]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-171.4073.35`
- `1.24.0-dev.0.0`
- `IC-171.4073.35, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Linux(amd64) v4.10.0-20-generic unknown, screens 1920x1080`

# Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.24.0-dev.0.0, server version 1.18.0, FATAL error: Failed to handle request: {clientRequestTime: 1493280482804, params: {file: /home/sisop/IdeaProjects/dart/toh-5-master/web/main.dart, offset: 0, length: 0}, method: edit.getAssists, id: 6}
NoSuchMethodError: The getter 'contextRoot' was called on null.
Receiver: null
Tried calling: contextRoot
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      EditDomainHandler.getAssists (package:analysis_server/src/edit/edit_domain.dart:159)
<asynchronous suspension>
#3      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:353)
#4      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:965)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:961)
#7      _rootRun (dart:async/zone.dart:1120)
#8      _CustomZone.run (dart:async/zone.dart:1001)
#9      _CustomZone.runGuarded (dart:async/zone.dart:901)
#10     runZoned (dart:async/zone.dart:1464)
#11     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:960)
#12     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2844413002/
