### ISSUE TITLE
Bad interaction between metadata and helper call

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29530]
If I run the following with `--emit-metadata`:

```dart
class Bar {
  final String x;

  const Bar(this.x);
}

class Foo {
  @Bar('bar')
  int x = 42;
}

void main() {
  dynamic f = new Foo();
  f.x = "hello";
}
```

I get the following compiler crash:

```
Wrong number of template arguments, given 3, expected 2:
#.fieldType(#)
#0      Template.instantiate (package:dev_compiler/src/js_ast/template.dart:104:9)
#1      JsBuilder.call (package:dev_compiler/src/js_ast/builder.dart:210:21)
#2      CodeGenerator._callHelper (package:dev_compiler/src/compiler/code_generator.dart:5837:15)
#3      CodeGenerator._emitFieldSignature (package:dev_compiler/src/compiler/code_generator.dart:2961:12)
#4      CodeGenerator._emitClassSignature (package:dev_compiler/src/compiler/code_generator.dart:1967:26)
#5      CodeGenerator.visitClassDeclaration (package:dev_compiler/src/compiler/code_generator.dart:968:5)
#6      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923:15)
#7      CodeGenerator._visit (package:dev_compiler/src/compiler/code_generator.dart:5508:23)
#8      CodeGenerator._emitTypeDeclaration (package:dev_compiler/src/compiler/code_generator.dart:541:22)
#9      CodeGenerator.visitCompilationUnit (package:dev_compiler/src/compiler/code_generator.dart:612:9)
#10     List.forEach (dart:core-patch/array.dart:73)
#11     CodeGenerator._emitModule (package:dev_compiler/src/compiler/code_generator.dart:348:22)
#12     CodeGenerator.compile (package:dev_compiler/src/compiler/code_generator.dart:232:18)
#13     ModuleCompiler.compile (package:dev_compiler/src/compiler/compiler.dart:220:26)
#14     _compile (package:dev_compiler/src/compiler/command.dart:186:25)
#15     compile (package:dev_compiler/src/compiler/command.dart:60:5)
#16     main (file:///Users/vsm/dart/sdk/pkg/dev_compiler/bin/dartdevc.dart:53:16)
```

**Comment by vsmenon** [comment]
@keertip

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2861503002
