### ISSUE TITLE
dartanalyzer crash on parsing AngularDart 2.0 codebase

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#29533]
Steps to reproduce:

1. `git clone https://github.com/dart-lang/angular2.git`
2. `cd angular2`
3. `git checkout 2.0.0`
4. `dartanalyzer --strong lib/`

I get this error:

```
Unhandled exception:
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1097)
#1      CompilationUnitElementInDependency.getLinkedType (package:analyzer/src/summary/link.dart:1409)
#2      ParameterElementForLink.type (package:analyzer/src/summary/link.dart:4189)
#3      FunctionTypeImpl.parameters (package:analyzer/src/dart/element/type.dart:594)
#4      InstanceMemberInferrer._inferParameterCovariance.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:438)
#5      Object&ListMixin.any (dart:collection/list.dart:115)
#6      InstanceMemberInferrer._inferParameterCovariance (package:analyzer/src/task/strong_mode.dart:437)
#7      InstanceMemberInferrer._inferExecutable (package:analyzer/src/task/strong_mode.dart:380)
#8      List.forEach (dart:core-patch/growable_array.dart:256)
#9      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:315)
#10     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:100)
#11     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1297)
#12     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3665)
#13     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3403)
#14     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3325)
#15     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#16     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#17     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3368)
#18     Linker.link (package:analyzer/src/summary/link.dart:3890)
#19     relink (package:analyzer/src/summary/link.dart:132)
#20     link (package:analyzer/src/summary/link.dart:113)
#21     LibraryContext.LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:106)
#22     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1671)
#23     LibraryContext.LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:105)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1671)
#25     LibraryContext.LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:51)
#26     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1046)
#27     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1011)
#28     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:744)
<asynchronous suspension>
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1403)
<asynchronous suspension>
#30     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1337)
#31     Driver._createAnalysisContext (package:analyzer_cli/src/driver.dart:594)
#32     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:191)
<asynchronous suspension>
#33     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167)
<asynchronous suspension>
#34     Driver.start (package:analyzer_cli/src/driver.dart:146)
<asynchronous suspension>
#35     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

Dart VM version: 1.23.0 (Fri Apr 21 03:07:31 2017) on "macos_x64".

**Comment by scheglov** [comment]
OK, I can reproduce the problem.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/c61167ab1d1eaf687c63df213e76b9d320123bef
