### ISSUE TITLE
Failed to handle completion domain reques

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#29551]
I'm not sure if it's still useful to report these by hand or not, but in case it is:

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Editing some Dart code.

### Versions

- Dart SDK 1.24.0-dev.0.0
- Visual Studio Code 1.11.2
- Dart Code 0.14.9

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.14.9
```

### Exception

Failed to handle completion domain request: {params: {file: /Stuff/Projects/lol_duel/lib/champions/fiora.dart, offset: 128}, method: completion.getSuggestions, id: 75485}

```text
FileSystemException(path=/Users/eseidel/.pub-cache/hosted/pub.dartlang.org/async-1.13.2/lib/; message=Directory listing failed)
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:308)
#1      _UriSuggestionBuilder._addPackageFolderSuggestions (package:analysis_server/src/services/completion/dart/uri_contributor.dart:180)
#2      _UriSuggestionBuilder._addPackageSuggestions.<anonymous closure> (package:analysis_server/src/services/completion/dart/uri_contributor.dart:203)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#4      _UriSuggestionBuilder._addPackageSuggestions (package:analysis_server/src/services/completion/dart/uri_contributor.dart:198)
#5      _UriSuggestionBuilder.visitSimpleStringLiteral (package:analysis_server/src/services/completion/dart/uri_contributor.dart:101)
#6      SimpleStringLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:9585)
#7      UriContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/uri_contributor.dart:33)
<asynchronous suspension>
#8      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:83)
<asynchronous suspension>
#9      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:87)
<asynchronous suspension>
#10     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:200)
<asynchronous suspension>
#11     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:113)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     _CustomZone.runGuarded (dart:async/zone.dart:901)
#15     runZoned (dart:async/zone.dart:1464)
#16     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:110)
#17     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:965)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#19     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:961)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     _CustomZone.runGuarded (dart:async/zone.dart:901)
#23     runZoned (dart:async/zone.dart:1464)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:960)
#25     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161)
#28     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
#29     _rootRunUnary (dart:async/zone.dart:1128)
#30     _CustomZone.runUnary (dart:async/zone.dart:1012)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:157)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:132)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#41     _rootRunUnary (dart:async/zone.dart:1128)
#42     _CustomZone.runUnary (dart:async/zone.dart:1012)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#46     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#47     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#48     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#49     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#50     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#51     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#52     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:96)
#53     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#54     _rootRunUnary (dart:async/zone.dart:1128)
#55     _CustomZone.runUnary (dart:async/zone.dart:1012)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#59     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#60     _StreamController._add (dart:async/stream_controller.dart:628)
#61     _StreamController.add (dart:async/stream_controller.dart:574)
#62     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#63     _rootRunUnary (dart:async/zone.dart:1132)
#64     _CustomZone.runUnary (dart:async/zone.dart:1012)
#65     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#66     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#67     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#68     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#69     _StreamController._add (dart:async/stream_controller.dart:628)
#70     _StreamController.add (dart:async/stream_controller.dart:574)
#71     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#72     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#73     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#74     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#75     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#76     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by devoncarew** [comment]
> I'm not sure if it's still useful to report these by hand or not

It is for recent SDKs! The stack traces are definitely useful when we can match them up to the current source.

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-lang/sdk/commit/f6f845c879d7f65113e4f1ce5b4e862a76c7b4c8
