### ISSUE TITLE
After restarting IDEA, the Dart Analysis view briefly shows some errors/warnings and then this error is reported

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29552]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA 171.4424.14`
- `1.24.0-edge.6a575117630f40859b4fc034696e9a14486501d6`
- `IU-171.4424.14, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Linux(amd64) v4.9.0-2-amd64 unknown, screens 3840x2160`

# Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.24.0-edge.6a575117630f40859b4fc034696e9a14486501d6, server version 1.18.0, error: Captured exception
NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AngularDriver.getStandardAngular (package:angular_analyzer_plugin/src/angular_driver.dart:269)
<asynchronous suspension>
#3      AngularDriver.resolveDart (package:angular_analyzer_plugin/src/angular_driver.dart:592)
<asynchronous suspension>
#4      AngularDriver.pushDartErrors (package:angular_analyzer_plugin/src/angular_driver.dart:530)
<asynchronous suspension>
#5      AngularDriver.performWork (package:angular_analyzer_plugin/src/angular_driver.dart:231)
<asynchronous suspension>
#6      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#7      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#8      new AnalysisServer (package:analysis_server/src/analysis_server.dart:454)
#9      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:96)
#10     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#11     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:482)
#12     _rootRun (dart:async/zone.dart:1120)

**Comment by zoechi** [comment]
seems to work fine without the angular plugin

**Comment by zoechi** [comment]
[report.txt](https://github.com/dart-lang/sdk/files/975475/report.txt)

**Comment by mk13** [comment]
Taking a look at it.

**Comment by zoechi** [comment]
This seems to work now after updating to the latest Dart and plugin build.

**Comment by bwilkerson** [comment]
Excellent! Please let us know if you see this again.
