### ISSUE TITLE
Analyzer checked mode crash on pruned typedefs assertion

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29595]
Running the analyzer in checked mode (in strong mode) on the following code causes a crash:

```dart
typedef R RunHandler<R>(R f());

class _ZoneDelegate {
  R run<R>(R f()) {
    var implementation = null;
    RunHandler<R> handler = (f) =>
        implementation.function(f);
    return null;
  }
}
```
```
rundart.sh dart -c ~/src/dart-repo/sdk/pkg/analyzer_cli/bin/analyzer.dart --strong ./tmp/test.dart
```

Stack trace head:
```
'package:analyzer/src/dart/element/type.dart': Failed assertion: line 941 pos 12: 'this.prunedTypedefs == null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:35)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:31)
#2      FunctionTypeImpl.substitute2 (package:analyzer/src/dart/element/type.dart:941:12)
#3      FunctionTypeImpl._forEachParameterType (package:analyzer/src/dart/element/type.dart:988:23)
#4      FunctionTypeImpl.normalParameterTypes (package:analyzer/src/dart/element/type.dart:555:5)
#5      FunctionTypeImpl.== (package:analyzer/src/dart/element/type.dart:731:15)
#6      ResolverVisitor.overrideVariable (package:analyzer/src/generated/resolver.dart:5271:23)
#7      StaticTypeAnalyzer.visitVariableDeclaration (package:analyzer/src/generated/static_type_analyzer.dart:1436:19)
#8      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11137:15)
#9      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241:10)
#10     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3224:59)
#11     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:7802:35)
#12     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:6368:35)
#13     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11137:15)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052:20)
#15     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11239:16)
#16     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239:10)
#17     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228:7)
#18     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:6396:39)
#19     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11233:15)
#20     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11294:20)
#21     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239:10)
```

**Comment by jmesserly** [comment]
seems to have been fixed.
