### ISSUE TITLE
Add null-check on typeParameters

### ISSUE THREAD

**Issue by mk13** [dart-lang/sdk#29617]
Use case : just filling out Component. Potentially from mistyping 'selector' and 'seelector'.

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4249.39`
- `1.24.0-dev.4.0`
- `IU-171.4249.39, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.4 unknown, screens 1440x900, 1200x1920  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/83/h011zfcd1x3d5nshw8mb8wj000d2hp/T/report.txt

```
Dart analysis server, SDK version 1.24.0-dev.4.0, server version 1.18.0, error: Captured exception
NoSuchMethodError: The getter 'typeParameters' was called on null.
Receiver: null
Tried calling: typeParameters
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      BindingTypeSynthesizer._instantiateClass (package:angular_analyzer_plugin/src/directive_extraction.dart:612)
#3      new BindingTypeSynthesizer (package:angular_analyzer_plugin/src/directive_extraction.dart:553)
#4      DirectiveLinker.resynthesizeDirectives (package:angular_analyzer_plugin/src/directive_linking.dart:53)
<asynchronous suspension>
#5      AngularDriver.resynthesizeDirectives (package:angular_analyzer_plugin/src/angular_driver.dart:698)
<asynchronous suspension>
#6      AngularDriver.getDirectives (package:angular_analyzer_plugin/src/angular_driver.dart:709)
<asynchronous suspension>
#7      AngularDriver.getUnlinkedDirectives (package:angular_analyzer_plugin/src/angular_driver.dart:702)
<asynchronous suspension>
#8      ChildDirectiveLinker.matchDirective (package:angular_analyzer_plugin/src/directive_linking.dart:279)
<asynchronous suspension>
#9      ChildDirectiveLinker.lookupFromLibrary (package:angular_analyzer_plugin/src/directive_linking.dart:239)
<asynchronous suspension>

**Comment by mk13** [comment]
Been able to consistently reproduce it. 

Hard update and rebuild; cannot reproduce the issue afterwards. Will close the ticket for now until it happens again.
