### ISSUE TITLE
Crash in Dart IntelliJ plug-in

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#29649]
Analyzer Feedback from IntelliJ

I got this while trying to find all uses of a variable. My workspace is `/tools/testing/dart/` in the Dart repo. (You may not be able to repro this locally since I had a bunch of uncommitted changes when this occurred.)

Overall, the analysis experience has been *really* weird in this directory. When errors appear in a file (red squigglies), they never seem to go away, even after the error is fixed and no longer shows up in the Dart analysis window.

# Version information

- `IDEA IU-171.4424.56`
- `1.24.0-edge.008c254909e13ed57ab674f67aff384468dd3439`
- `IU-171.4424.56, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.4 unknown, screens 2560x1600`

# Exception

Please append the contents of:
file:///private/var/folders/vw/b46gfymx10ddqfg1m_tr72sw003cg5/T/report.txt

```
Dart analysis server, SDK version 1.24.0-edge.008c254909e13ed57ab674f67aff384468dd3439, server version 1.18.0, error: Captured exception
NoSuchMethodError: The getter 'functions' was called on null.
Receiver: null
Tried calling: functions
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ExecutableElementHandle.functions (package:analyzer/src/dart/element/handle.dart:488)
#3      _DeferredLocalFunctionElement.actualElement (package:analyzer/src/summary/resynthesize.dart:817)
#4      ExecutableElementHandle.typeParameters (package:analyzer/src/dart/element/handle.dart:530)
#5      FunctionTypeImpl.typeFormals (package:analyzer/src/dart/element/type.dart:666)
#6      ResolverVisitor.matchFunctionTypeParameters (package:analyzer/src/generated/resolver.dart:5185)
#7      ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:6007)
#8      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#9      VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11143)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239)
#11     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4660)
#12     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3224)
```

```
Dart analysis server, SDK version 1.24.0-edge.008c254909e13ed57ab674f67aff384468dd3439, server version 1.18.0, error: Captured exception
NoSuchMethodError: The getter 'functions' was called on null.
Receiver: null
Tried calling: functions
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ExecutableElementHandle.functions (package:analyzer/src/dart/element/handle.dart:488)
#3      _DeferredLocalFunctionElement.actualElement (package:analyzer/src/summary/resynthesize.dart:817)
#4      ExecutableElementHandle.typeParameters (package:analyzer/src/dart/element/handle.dart:530)
#5      FunctionTypeImpl.typeFormals (package:analyzer/src/dart/element/type.dart:666)
#6      ResolverVisitor.matchFunctionTypeParameters (package:analyzer/src/generated/resolver.dart:5185)
#7      ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:6007)
#8      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#9      VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11143)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239)
#11     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4660)
#12     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3224)
#13     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:7802)
#14     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:6368)
#15     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11137)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#17     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11239)
#18     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239)
#19     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4660)
#20     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228)
#21     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:6396)
#22     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11233)
#23     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4404)
#24     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239)
#25     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4660)
#26     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:3011)
#27     ResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:5864)
#28     PartialResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:4655)
#29     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399)
#30     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#31     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:7340)
#32     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7317)
#33     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5581)
#34     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#35     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5647)
#36     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#37     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:544)
#38     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#39     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#40     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88)
#41     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:999)
#42     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#43     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#44     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1044)
#45     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:770)
<asynchronous suspension>
#46     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#47     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#48     new AnalysisServer (package:analysis_server/src/analysis_server.dart:460)
#49     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:91)
#50     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#51     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:476)
#52     _rootRun (dart:async/zone.dart:1120)
#53     _CustomZone.run (dart:async/zone.dart:1001)
#54     runZoned (dart:async/zone.dart:1467)
#55     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:515)
#56     Driver.start (package:analysis_server/src/server/driver.dart:475)
#57     main (file:///Users/rnystrom/dev/dart/sdk/pkg/analysis_server/bin/server.dart:12)
#58     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1038)
#1      PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#3      AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1044)
#4      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:770)
<asynchronous suspension>
#5      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#6      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#7      new AnalysisServer (package:analysis_server/src/analysis_server.dart:460)
#8      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:91)
#9      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#10     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:476)
#11     _rootRun (dart:async/zone.dart:1120)
#12     _CustomZone.run (dart:async/zone.dart:1001)
#13     runZoned (dart:async/zone.dart:1467)
#14     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:515)
#15     Driver.start (package:analysis_server/src/server/driver.dart:475)
#16     main (file:///Users/rnystrom/dev/dart/sdk/pkg/analysis_server/bin/server.dart:12)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

```
1495141132427 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/utils.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/rnystrom
1495141132430 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/vm_test_config.dart","errors":[]}}
1495141132451 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/android.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/rnystr
1495141132458 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/dependency_graph.dart","errors":[]}}
1495141132463 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/html_test.dart","errors":[]}}
1495141132474 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/multitest.dart","errors":[]}}
1495141132481 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/record_and_replay.dart","errors":[]}}
1495141132488 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/status_expression.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Us
1495141132495 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/status_file.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/rn
1495141132501 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/summary_report.dart","errors":[]}}
1495141132501 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1495141133310 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1495141133338 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/
1495141133345 <= {"event":"analysis.highlights","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","regions":[{"type":"DIRECTIVE","offset":217,"length":20},{"t
1495141133354 <= {"event":"analysis.navigation","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","regions":[{"offset":224,"length":12,"targets":[0]},{"offset
1495141133355 <= {"event":"analysis.overrides","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","overrides":[{"offset":9654,"length":8,"superclassMember":{"e
1495141133355 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1495141133663 => {"id":"51","method":"analysis.updateContent","params":{"files":{"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart":{"type":"remove"}}},"clientRequestTime":1495
1495141133667 <= {"id":"51","result":{}}
1495141133667 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1495141133715 <= {"event":"analysis.errors","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/
1495141133719 <= {"event":"analysis.highlights","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","regions":[{"type":"DIRECTIVE","offset":217,"length":20},{"t
1495141133731 <= {"event":"analysis.navigation","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","regions":[{"offset":224,"length":12,"targets":[0]},{"offset
1495141133732 <= {"event":"analysis.overrides","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","overrides":[{"offset":9654,"length":8,"superclassMember":{"e
1495141133733 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1495141137087 => {"id":"52","method":"edit.getAssists","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","offset":9357,"length":0},"clientRequestTime":1495141
1495141137088 <= {"id":"52","result":{"assists":[{"message":"Convert into getter","edits":[{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","fileStamp":0,"edits":[{"o
1495141138029 => {"id":"53","method":"search.findElementReferences","params":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","offset":9353,"includePotential":true},"
1495141138037 <= {"id":"53","result":{"id":"0","element":{"kind":"FIELD","name":"allNames","location":{"file":"/Users/rnystrom/dev/dart/sdk/tools/testing/dart/test_configurations.dart","offset":9353,"
1495141138061 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The getter 'functions' was called on null.\nReceiver: null\nTried cal
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
