### ISSUE TITLE
Analysis Server Crash: The getter 'uri' was called on null

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29666]
From DartPad v1.23.0
```
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      InputPackagesResultProvider.hasResultsForSource (package:analyzer/src/summary/package_bundle_reader.dart:36:31)
#3      ResynthesizerResultProvider.compute (package:analyzer/src/summary/package_bundle_reader.dart:163:10)
#4      AnalysisContextImpl.aboutToComputeResult.<anonymous closure> (package:analyzer/src/context/context.dart:582:52)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#6      AnalysisContextImpl.aboutToComputeResult (package:analyzer/src/context/context.dart:580:42)
#7      AnalysisContextImpl.aboutToComputeResult.<anonymous closure> (package:analyzer/src/context/context.dart:591:29)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#9      AnalysisContextImpl.aboutToComputeResult (package:analyzer/src/context/context.dart:580:42)
#10     WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:746:21)
#11     _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:879:17)
#12     CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:414:35)
#13     WorkOrder.moveNext.<anonymous closure> (package:analyzer/src/task/driver.dart:845:31)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#15     WorkOrder.moveNext (package:analyzer/src/task/driver.dart:837:44)
#16     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:253:35)
#17     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199:27)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#19     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197:50)
#20     Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:204:24)
#21     Analyzer.analyzeMulti (package:services/src/analyzer.dart:138:7)
#22     Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#23     testAnalysis (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:248:35)
<asynchronous suspension>
#24     testPath (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:190:39)
<asynchronous suspension>
#25     main (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:109:13)
<asynchronous suspension>
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
@scheglov The stack trace is out of date, but the bug might still be relevant.

**Comment by scheglov** [comment]
I have not seen this for a while, I think never since analysis driver.

**Comment by bwilkerson** [comment]
Then we'll assume it's obsolete until we see it on a current build.

**Comment by pylaligand** [comment]
[One of our Fuchsia build bots](https://luci-logdog.appspot.com/v/?s=fuchsia%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8967422497481534624%2F%2B%2Fsteps%2Fbuild_fuchsia%2F0%2Fsteps%2Fninja%2F0%2Fstdout) just hit a similar issue using dartanalyzer:
```
[13528/19631] ACTION //lib/flutter/packages/flutter_tools:flutter_tools(//build/toolchain:host_x64)
FAILED: host_x64/gen/lib/flutter/packages/flutter_tools/flutter_tools.analyzed 
/usr/bin/env ../../build/dart/run_analysis.py --source-dir /b/s/w/ir/kitchen-workdir/lib/flutter/packages/flutter_tools/lib --dot-packages /b/s/w/ir/kitchen-workdir/out/debug-x86-64/host_x64/gen/lib/flutter/packages/flutter_tools/flutter_tools.packages --dartanalyzer /b/s/w/ir/kitchen-workdir/dart/tools/sdks/linux/dart-sdk/bin/dartanalyzer --dart-sdk /b/s/w/ir/kitchen-workdir/dart/tools/sdks/linux/dart-sdk --options /b/s/w/ir/kitchen-workdir/lib/flutter/analysis_options.yaml --stamp /b/s/w/ir/kitchen-workdir/out/debug-x86-64/host_x64/gen/lib/flutter/packages/flutter_tools/flutter_tools.analyzed --depname host_x64/gen/lib/flutter/packages/flutter_tools/flutter_tools.analyzed --depfile /b/s/w/ir/kitchen-workdir/out/debug-x86-64/host_x64/gen/lib/flutter/packages/flutter_tools/flutter_tools.analysis.d
Analyzing /b/s/w/ir/kitchen-workdir/lib/flutter/packages/flutter_tools/lib...
Unhandled exception:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      new _LibraryResynthesizer (package:analyzer/src/summary/resynthesize.dart:902)
#3      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:254)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:270)
#5      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:222)
#6      LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:91)
#7      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:64)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#9      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:63)
#10     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1075)
#11     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#12     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1063)
#13     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:571)
<asynchronous suspension>
#14     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:133)
<asynchronous suspension>
#15     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:178)
<asynchronous suspension>
#16     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:109)
<asynchronous suspension>
#17     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:778)
#18     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:328)
<asynchronous suspension>
#19     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:226)
<asynchronous suspension>
#20     Driver.start (package:analyzer_cli/src/driver.dart:195)
<asynchronous suspension>
#21     main (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:13)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1114)
#1      PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1063)
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:571)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:133)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:178)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:109)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:778)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:328)
<asynchronous suspension>
#9      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:226)
<asynchronous suspension>
#10     Driver.start (package:analyzer_cli/src/driver.dart:195)
<asynchronous suspension>
#11     main (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:13)
<asynchronous suspension>
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

This is using the 1.25.0-dev.11.0 SDK (the one that Flutter currently uses for analysis). I was unable to reproduce locally.

**Comment by bwilkerson** [comment]
@scheglov This is showing up with the new AnalysisDriver.

**Comment by scheglov** [comment]
I was able to reproduce it when I pass a not absolute path to `AnalysisDriver`. We can work it around there, but I think this means that there is a problem with `analyzer_cli` or `SourceFactory`. At this point it is impossible to track down, we would need either to be able to reproduce the actual problem locally, or add logging and try to gather more information.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/#/c/sdk/+/8405

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/#/c/sdk/+/8704 instead.

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
