### ISSUE TITLE
Analysis server crash: initializer= was called on null

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29668]
Dartpad v1.23.0

```
AnalysisException: Cannot compute DART_ERRORS for StringSource (/tmp/analyzerhc1OzK/main.dart)
Caused by Unexpected exception while performing BuildCompilationUnitElementTask for source /tmp/analyzerhc1OzK/main.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199:27)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197:50)
#7      Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:204:24)
#8      Analyzer.analyzeMulti (package:services/src/analyzer.dart:138:7)
#9      Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#10     testAnalysis (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:248:35)
<asynchronous suspension>
#11     testPath (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:190:39)
<asynchronous suspension>
#12     main (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:109:13)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

Caused by NoSuchMethodError: The setter 'initializer=' was called on null.
Receiver: null
Tried calling: initializer=Instance of 'FunctionElementImpl'
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _BaseElementBuilder.buildParameterInitializer (package:analyzer/src/dart/element/builder.dart:1348:17)
#3      ElementBuilder.visitDefaultFormalParameter (package:analyzer/src/dart/element/builder.dart:1043:5)
#4      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3490:15)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052:20)
#6      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4853:17)
#7      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:845:10)
#8      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4849:15)
#9      GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5781:18)
#10     _BaseElementBuilder._visitChildren (package:analyzer/src/dart/element/builder.dart:1612:14)
#11     _BaseElementBuilder.visitGenericFunctionType (package:analyzer/src/dart/element/builder.dart:1470:5)
#12     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5774:20)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052:20)
#14     TypeArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10620:16)
#15     RecursiveAstVisitor.visitTypeArgumentList (package:analyzer/dart/ast/visitor.dart:1200:10)
#16     TypeArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10616:15)
#17     TypeNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10756:21)
#18     RecursiveAstVisitor.visitTypeName (package:analyzer/dart/ast/visitor.dart:1206:10)
#19     TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10751:15)
#20     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11228:12)
#21     RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1230:10)
#22     ApiElementBuilder.visitVariableDeclarationList (package:analyzer/src/dart/element/builder.dart:660:39)
#23     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11223:15)
#24     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4404:17)
#25     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:827:10)
#26     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399:15)
#27     _ElementBuilder_visitClassDeclaration.visitNode (package:analyzer/src/dart/element/builder.dart:1640:42)
#28     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:3011:53)
#29     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399:15)
#30     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052:20)
#31     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991:13)
#32     ApiElementBuilder.visitClassDeclaration (package:analyzer/src/dart/element/builder.dart:80:12)
#33     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923:15)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052:20)
#35     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523:21)
#36     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707:10)
#37     ApiElementBuilder.visitCompilationUnit (package:analyzer/src/dart/element/builder.dart:135:38)
#38     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516:15)
#39     CompilationUnitBuilder.buildCompilationUnit.<anonymous closure> (package:analyzer/src/dart/element/builder.dart:758:12)
#40     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#41     CompilationUnitBuilder.buildCompilationUnit (package:analyzer/src/dart/element/builder.dart:750:42)
#42     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1098:25)
#43     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321:9)
#44     AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#45     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#46     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#47     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199:27)
#48     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#49     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197:50)
#50     Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:204:24)
#51     Analyzer.analyzeMulti (package:services/src/analyzer.dart:138:7)
#52     Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#53     testAnalysis (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:248:35)
<asynchronous suspension>
#54     testPath (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:190:39)
<asynchronous suspension>
#55     main (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:109:13)
<asynchronous suspension>
#56     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:737:7)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:674:12)
#2      Analyzer.analyzeMulti.<anonymous closure> (package:services/src/analyzer.dart:142:18)
#3      List.forEach (dart:core-patch/growable_array.dart:256)
#4      Analyzer.analyzeMulti (package:services/src/analyzer.dart:141:19)
#5      Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#6      testAnalysis (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:248:35)
<asynchronous suspension>
#7      testPath (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:190:39)
<asynchronous suspension>
#8      main (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:109:13)
<asynchronous suspension>
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
