### ISSUE TITLE
Missing const constructor for bool.fromEnvironment

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29660]
```
python ../../tools/patch_sdk.py --quiet dart2js /Users/ahe/w/dart-sdk/sdk/sdk /Users/ahe/w/dart-sdk/sdk/sdk/lib/_internal/js_runtime/lib patched_dart2js_sdk /Users/ahe/w/dart-sdk/sdk/.packages
patched_dart2js_sdk/lib/_internal/js_runtime/lib/linked_hash_map.dart:10:29: Error: Not a const factory.
const _USE_ES6_MAPS = const bool.fromEnvironment("dart2js.use.es6.maps");
                            ^
Unhandled exception:
Internal error: No constructor named '_CompileTimeError::' in 'dart:core'.
#0      internalError (package:front_end/src/fasta/errors.dart:38:5)
#1      LibraryBuilder.getConstructor (package:front_end/src/fasta/builder/library_builder.dart:146:11)
#2      TargetImplementation.getCompileTimeError (package:front_end/src/fasta/target_implementation.dart:73:28)
#3      Loader.getCompileTimeError (package:front_end/src/fasta/loader.dart:154:43)
#4      BodyBuilder.buildCompileTimeError (package:front_end/src/fasta/kernel/body_builder.dart:2753:42)
#5      BodyBuilder.buildStaticInvocation (package:front_end/src/fasta/kernel/body_builder.dart:1998:16)
#6      BodyBuilder.endNewExpression.<anonymous closure> (package:front_end/src/fasta/kernel/body_builder.dart:2127:16)
#7      BodyBuilder.endNewExpression (package:front_end/src/fasta/kernel/body_builder.dart:2143:6)
#8      BodyBuilder.endConstExpression (package:front_end/src/fasta/kernel/body_builder.dart:2150:5)
#9      Parser.parseConstExpression (package:front_end/src/fasta/parser/parser.dart:3250:14)
#10     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:2955:16)
#11     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:2903:14)
#12     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:2772:13)
#13     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:2745:11)
#14     Parser.parseFieldInitializerOpt (package:front_end/src/fasta/parser/parser.dart:1552:15)
#15     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:1334:13)
#16     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:1312:11)
#17     DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:543:22)
#18     DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:445:5)
#19     DietListener.endTopLevelFields (package:front_end/src/fasta/source/diet_listener.dart:232:5)
#20     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:1345:16)
#21     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:1312:11)
#22     Parser._parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:355:14)
#23     Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:327:13)
#24     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:319:15)
#25     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:155:18)
<asynchronous suspension>
#26     Loader.buildBodies (package:front_end/src/fasta/loader.dart:97:13)
<asynchronous suspension>
#27     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:268:20)
<asynchronous suspension>
#28     compilePlatform (package:compiler/src/kernel/fasta_support.dart:55:36)
<asynchronous suspension>
#29     _main (file:///Users/ahe/w/dart-sdk/sdk/tools/patch_sdk.dart:114:11)
<asynchronous suspension>
#30     main (file:///Users/ahe/w/dart-sdk/sdk/tools/patch_sdk.dart:52:11)
<asynchronous suspension>
#31     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by peter-ahe-google** [comment]
I suggest this is resolved by making the factory constructor external so Fasta doesn't have to support special rules in dart2js.

**Comment by sigmundch** [comment]
It seems we have two issues here. I agree that anything that fasta assumes of the sdk is available in the unpatched sdk (in this case _CompileTimeError). I'll take a look at addressing this piece.

However, we shouldn't have any compile-time errors when building the sdk (and thus no need to generate code that mentions _CompileTimeError when building the patched sdk.) Is `const bool.fromEnvironment` is not recognized as const for some reason?

**Comment by sigmundch** [comment]
Agr - sorry, ignore my last comment, I can see now that you filed 2 separate bugs for the two issues. Not sure why I only read the title of the other bug and the description of this one.

I agree with your two suggestions.

**Comment by sigmundch** [comment]
CL out for review https://codereview.chromium.org/2896393003/

**Comment by sigmundch** [comment]
fix in https://github.com/dart-lang/sdk/commit/dd70d8b655bc1187f942779dd5455fab1f2f8045

**Comment by peter-ahe-google** [comment]
Thank you!
