### ISSUE TITLE
Analysis server crash: The getter 'beginToken' was called on null.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29664]
From DartPad, version 1.23.0

```
AnalysisException: Cannot compute DART_ERRORS for StringSource (/tmp/analyzerDSLH2C/main.dart)
Caused by Unexpected exception while performing BuildCompilationUnitElementTask for source /tmp/analyzerDSLH2C/main.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199:27)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197:50)
#7      Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:204:24)
#8      Analyzer.analyzeMulti (package:services/src/analyzer.dart:138:7)
#9      Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#10     testAnalysis (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:248:35)
<asynchronous suspension>
#11     testPath (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:190:39)
<asynchronous suspension>
#12     main (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:109:13)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

Caused by NoSuchMethodError: The getter 'beginToken' was called on null.
Receiver: null
Tried calling: beginToken
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      SimpleFormalParameterImpl.beginToken (package:analyzer/src/dart/ast/ast.dart:9275:23)
#3      AstNodeImpl.offset (package:analyzer/src/dart/ast/ast.dart:956:29)
#4      _BaseElementBuilder._setCodeRange (package:analyzer/src/dart/element/builder.dart:1557:31)
#5      _BaseElementBuilder.visitSimpleFormalParameter (package:analyzer/src/dart/element/builder.dart:1489:7)
#6      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9301:15)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052:20)
#8      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4853:17)
#9      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:845:10)
#10     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4849:15)
#11     GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5781:18)
#12     _BaseElementBuilder._visitChildren (package:analyzer/src/dart/element/builder.dart:1612:14)
#13     _BaseElementBuilder.visitGenericFunctionType (package:analyzer/src/dart/element/builder.dart:1470:5)
#14     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5774:20)
#15     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11228:12)
#16     RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1230:10)
#17     ApiElementBuilder.visitVariableDeclarationList (package:analyzer/src/dart/element/builder.dart:660:39)
#18     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11223:15)
#19     TopLevelVariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10409:20)
#20     RecursiveAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1188:10)
#21     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10404:15)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052:20)
#23     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523:21)
#24     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707:10)
#25     ApiElementBuilder.visitCompilationUnit (package:analyzer/src/dart/element/builder.dart:135:38)
#26     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516:15)
#27     CompilationUnitBuilder.buildCompilationUnit.<anonymous closure> (package:analyzer/src/dart/element/builder.dart:758:12)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#29     CompilationUnitBuilder.buildCompilationUnit (package:analyzer/src/dart/element/builder.dart:750:42)
#30     BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1098:25)
#31     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321:9)
#32     AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#33     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#34     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#35     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199:27)
#36     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#37     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197:50)
#38     Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:204:24)
#39     Analyzer.analyzeMulti (package:services/src/analyzer.dart:138:7)
#40     Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#41     testAnalysis (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:248:35)
<asynchronous suspension>
#42     testPath (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:190:39)
<asynchronous suspension>
#43     main (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:109:13)
<asynchronous suspension>
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:737:7)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:674:12)
#2      Analyzer.analyzeMulti.<anonymous closure> (package:services/src/analyzer.dart:142:18)
#3      List.forEach (dart:core-patch/growable_array.dart:256)
#4      Analyzer.analyzeMulti (package:services/src/analyzer.dart:141:19)
#5      Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#6      testAnalysis (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:248:35)
<asynchronous suspension>
#7      testPath (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:190:39)
<asynchronous suspension>
#8      main (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:109:13)
<asynchronous suspension>
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
Do we have any way to reproduce this? Looking at the code I don't see how to produce a `SimpleFormalParameter` without an `identifier` (it should minimally be a synthetic identifier).

**Comment by bwilkerson** [comment]
@lukechurch

**Comment by bwilkerson** [comment]
The package `services` needs to be updated to use the new analysis driver.

**Comment by bwilkerson** [comment]
I suspect that this has been fixed, but if not I can't fix it without a way to reproduce it. Hence I'm closing this.
