### ISSUE TITLE
Analysis Server Crash, The getter 'type' was called on null.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29667]
Dartpad v1.23.0

```
AnalysisException: Cannot compute DART_ERRORS for StringSource (/tmp/analyzer5vFP7p/main.dart)
Caused by Unexpected exception while performing ParseDartTask for source /tmp/analyzer5vFP7p/main.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199:27)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197:50)
#7      Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:204:24)
#8      Analyzer.analyzeMulti (package:services/src/analyzer.dart:138:7)
#9      Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#10     testAnalysis (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:248:35)
<asynchronous suspension>
#11     testPath (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:190:39)
<asynchronous suspension>
#12     main (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:109:13)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

Caused by NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      Parser._tokenMatches (package:analyzer/src/generated/parser.dart:8071:60)
#3      Parser.skipFormalParameterList (package:analyzer/src/generated/parser.dart:5518:10)
#4      Parser.skipGenericFunctionTypeAfterReturnType (package:analyzer/src/generated/parser.dart:5539:12)
#5      Parser.skipTypeAnnotation (package:analyzer/src/generated/parser.dart:5655:14)
#6      Parser.skipReturnType (package:analyzer/src/generated/parser.dart:5593:14)
#7      Parser._isTypedIdentifier (package:analyzer/src/generated/parser.dart:6277:19)
#8      Parser.parseFinalConstVarOrType (package:analyzer/src/generated/parser.dart:2865:16)
#9      Parser.parseNormalFormalParameter (package:analyzer/src/generated/parser.dart:4263:34)
#10     Parser.parseFormalParameter (package:analyzer/src/generated/parser.dart:2896:9)
#11     Parser._parseFormalParameterListAfterParen (package:analyzer/src/generated/parser.dart:6831:11)
#12     Parser._parseFormalParameterListUnchecked (package:analyzer/src/generated/parser.dart:6922:12)
#13     Parser.parseFunctionDeclaration (package:analyzer/src/generated/parser.dart:3291:22)
#14     Parser.parseCompilationUnitMember (package:analyzer/src/generated/parser.dart:2239:14)
#15     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:1973:20)
#16     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:1865:12)
#17     ParseDartTask.internalPerform (package:analyzer/src/task/dart.dart:4114:35)
#18     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321:9)
#19     AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#20     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#21     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#22     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199:27)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189:15)
#24     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197:50)
#25     Analyzer._ensureAnalysisDone (package:services/src/analyzer.dart:204:24)
#26     Analyzer.analyzeMulti (package:services/src/analyzer.dart:138:7)
#27     Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#28     testAnalysis (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:248:35)
<asynchronous suspension>
#29     testPath (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:190:39)
<asynchronous suspension>
#30     main (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:109:13)
<asynchronous suspension>
#31     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:737:7)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:674:12)
#2      Analyzer.analyzeMulti.<anonymous closure> (package:services/src/analyzer.dart:142:18)
#3      List.forEach (dart:core-patch/growable_array.dart:256)
#4      Analyzer.analyzeMulti (package:services/src/analyzer.dart:141:19)
#5      Analyzer.analyze (package:services/src/analyzer.dart:118:12)
#6      testAnalysis (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:248:35)
<asynchronous suspension>
#7      testPath (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:190:39)
<asynchronous suspension>
#8      main (file:///home/lukechurch/dart-services/tool/fuzz_driver.dart:109:13)
<asynchronous suspension>
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
I wasn't able to reproduce this issue, but did find another similar bug (fixed here https://codereview.chromium.org/2895743002/).

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
