### ISSUE TITLE
Dart analysis error

### ISSUE THREAD

**Issue by zhongguo168a** [dart-lang/sdk#29673]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-171.4424.63`
- `1.22.1`
- `WS-171.4424.63, JRE 1.8.0_121-b13x32 Oracle Corporation, OS Windows 10(x86) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Win10\User\Local\Temp\report1.txt

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Failed to send analysis.implemented notification.
type 'FunctionElementImpl' is not a subtype of type 'ClassElement' in type cast where
  FunctionElementImpl is from package:analyzer/src/dart/element/element.dart
  ClassElement is from package:analyzer/dart/element/element.dart

#0      Object._as (dart:core-patch/object_patch.dart:76)
#1      SearchEngineImpl.searchAllSubtypes.<searchAllSubtypes_async_body>.<anonymous closure> (package:analysis_server/src/services/search/search_engine_internal.dart:37)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:412)
#3      ListIterable.toSet (dart:_internal/iterable.dart:227)
#4      SearchEngineImpl.searchAllSubtypes.<searchAllSubtypes_async_body> (package:analysis_server/src/services/search/search_engine_internal.dart:37)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#6      _rootRunUnary (dart:async/zone.dart:1158)
#7      _CustomZone.runUnary (dart:async/zone.dart:1037)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#9      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#11     _Future._complete

**Comment by bwilkerson** [comment]
Can you provide us with any information about how to reproduce this bug?

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
