### ISSUE TITLE
Dart analysis server crashed when creating static const int as binary literals.

### ISSUE THREAD

**Issue by BiffJutsu** [dart-lang/sdk#29687]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Filling out const members of this class:
class TYPE {
  static const int ALTMETADATA = 0x88;
  static const int ALTROW = 0xD3;
  static const int COLMETADATA = 0x81;
  static const int COLINFO = 0xA5;
}
Happened right after typing 0x on each line.

### Versions

- Dart SDK 1.23.0
- Visual Studio Code 1.12.2
- Dart Code 1.4.0

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=1.4.0
```

### Exception

Captured exception

```text
NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4294967296)
#0      Driver._captureExceptions.<anonymous closure> (package:analysis_server/src/server/driver.dart:517)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:981)
#2      _Future._propagateToListeners (dart:async/future_impl.dart:547)
#3      _Future._completeError (dart:async/future_impl.dart:482)
#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#5      _Completer.completeError (dart:async/future_impl.dart:27)
#6      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:863)
#7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#8      _rootRun (dart:async/zone.dart:1116)
#9      _CustomZone.run (dart:async/zone.dart:1001)
#10     _CustomZone.runGuarded (dart:async/zone.dart:901)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     _CustomZone.runGuarded (dart:async/zone.dart:901)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
<asynchronous suspension>
#20     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1337)
#21     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:421)
#22     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)
#23     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#24     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:489)
#25     _rootRun (dart:async/zone.dart:1120)
#26     _CustomZone.run (dart:async/zone.dart:1001)
#27     runZoned (dart:async/zone.dart:1465)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:528)
#29     Driver.start (package:analysis_server/src/server/driver.dart:488)
#30     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/analysis_server/bin/server.dart:12)
#31     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2912843004/
