### ISSUE TITLE
Analyzer crash with generic methods

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#29725]
The following program causes the analyzer to throw an exception:

```dart
import 'dart:async';

abstract class Closeable {
  dynamic close();
}

Future<S> withAs<T extends Closeable, S>(FutureOr<T> closeable,
                                         FutureOr<S> fn(T c)) async {
  T c = await closeable;
  S result;
  try {
    result = await fn(c);
  } catch (_) {
    try {
      await c.close();
    } catch (_) {
      // ignore exceptions while closing.
    }
    rethrow;
  }

  await c.close();
  return result;
}


class CloseableThing implements Closeable {
  static int _closeableThings = 0;
  int _whichThing;
  CloseableThing() {
    _whichThing = _closeableThings++;
  }

  void close() {
    print("closed a CloseableThing: $_whichThing");
  }

  String toString() => "CloseableThing($_whichThing)";
}

main() async {
  withAs<CloseableThing>(new CloseableThing(), (CloseableThing thing) {
    print("Found a closeable thing: $thing");
  });

  await withAs<CloseableThing>(new Future.delayed(const Duration(seconds: 1),
                                                  () => new CloseableThing()),
      (CloseableThing thing) {
    print("Found a future closeable thing: $thing");
  });
}
```

```
zra@zach:~/dart/sdk$ out/ReleaseX64/dart-sdk/bin/dartanalyzer ../try_closeable.dart 
Analyzing ../try_closeable.dart...
Unhandled exception:
Invalid argument(s): argumentTypes.length (1) != parameterTypes.length (2)
#0      InterfaceTypeImpl.substitute2 (package:analyzer/src/dart/element/type.dart:2022)
#1      ErrorVerifier._checkTypeArguments (package:analyzer/src/generated/error_verifier.dart:6261)
#2      ErrorVerifier.visitMethodInvocation (package:analyzer/src/generated/error_verifier.dart:1002)
#3      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#4      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#5      RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:815)
#6      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#8      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#9      RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:647)
#10     ErrorVerifier.visitBlock (package:analyzer/src/generated/error_verifier.dart:397)
#11     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#12     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#13     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:653)
#14     ErrorVerifier.visitBlockFunctionBody (package:analyzer/src/generated/error_verifier.dart:416)
#15     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#16     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#17     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:869)
#18     ErrorVerifier.visitFunctionExpression (package:analyzer/src/generated/error_verifier.dart:780)
#19     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#20     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5204)
#21     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:857)
#22     ErrorVerifier.visitFunctionDeclaration (package:analyzer/src/generated/error_verifier.dart:761)
#23     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5197)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#25     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#26     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#27     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:540)
#28     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#29     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:291)
#30     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:96)
#31     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#32     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:95)
#33     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:999)
#34     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#35     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#36     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:525)
<asynchronous suspension>
#37     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:133)
<asynchronous suspension>
#38     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:178)
<asynchronous suspension>
#39     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:123)
<asynchronous suspension>
#40     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:722)
#41     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:262)
<asynchronous suspension>
#42     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:166)
<asynchronous suspension>
#43     Driver.start (package:analyzer_cli/src/driver.dart:145)
<asynchronous suspension>
#44     main (file:///usr/local/google/home/zra/dart/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1038)
#1      PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:525)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:133)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:178)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:123)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:722)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:262)
<asynchronous suspension>
#9      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:166)
<asynchronous suspension>
#10     Driver.start (package:analyzer_cli/src/driver.dart:145)
<asynchronous suspension>
#11     main (file:///usr/local/google/home/zra/dart/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by natebosch** [comment]
This no longer crashes, it surfaces correct errors about missing type arguments.
