### ISSUE TITLE
Analysis Crash : NoSuchMethodError: The getter 'length' was called on null.

### ISSUE THREAD

**Issue by daftspaniel** [dart-lang/sdk#29732]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-171.4424.63`
- `1.23.0`
- `WS-171.4424.63, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Linux(amd64) v4.10.0-21-generic unknown, screens 1280x800`

# Exception

Please append the contents of:
file:///tmp/report.txt

```
[report.txt](https://github.com/dart-lang/sdk/files/1032705/report.txt)

Dart analysis server, SDK version 1.23.0, server version 1.18.0, error: Analysis failed: /home/daftspaniel/WebstormProjects/nb8080/web/main.dart
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ApiSignature.addBytes (package:analyzer/src/summary/api_signature.dart:75)
#3      Iterable.forEach (dart:core/iterable.dart:226)
#4      FileState.transitiveSignature (package:analyzer/src/dart/analysis/file_state.dart:330)
#5      AnalysisDriver._getResolvedUnitSignature (package:analyzer/src/dart/analysis/driver.dart:1131)
#6      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:920)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:808)
<asynchronous suspension>
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1403)
<asynchronous suspension>
#9      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1337)
#10     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:421)
#11     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)
[report.txt](https://github.com/dart-lang/sdk/files/1032706/report.txt)

#12     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#13     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:489)

**Comment by daftspaniel** [comment]
```
Dart analysis server, SDK version 1.23.0, server version 1.18.0, error: Analysis failed: /home/daftspaniel/WebstormProjects/nb8080/web/main.dart
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ApiSignature.addBytes (package:analyzer/src/summary/api_signature.dart:75)
#3      Iterable.forEach (dart:core/iterable.dart:226)
#4      FileState.transitiveSignature (package:analyzer/src/dart/analysis/file_state.dart:330)
#5      AnalysisDriver._getResolvedUnitSignature (package:analyzer/src/dart/analysis/driver.dart:1131)
#6      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:920)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:808)
<asynchronous suspension>
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1403)
<asynchronous suspension>
#9      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1337)
#10     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:421)
#11     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)
#12     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#13     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:489)
#14     _rootRun (dart:async/zone.dart:1120)
#15     _CustomZone.run (dart:async/zone.dart:1001)
#16     runZoned (dart:async/zone.dart:1465)
#17     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:528)
#18     Driver.start (package:analysis_server/src/server/driver.dart:488)
#19     main (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/analysis_server/bin/server.dart:12)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1495822357185 started analysis server:
  /home/daftspaniel/Software/Dart/dart-sdk/bin/dart /home/daftspaniel/Software/Dart/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=WebStorm --client-version=WS-171.4424.63 --useAnaly
1495822358542 <= {"event":"server.connected","params":{"version":"1.18.0","pid":4734,"sessionId":""}}
1495822358638 <= {"id":"0","result":{"version":"1.18.0"}}
1495822358648 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1495822357259}
1495822358648 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1495822358648 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["/home/daftspaniel/WebstormProjects/nb8080"],"excluded":["/home/daftspaniel/WebstormProjects/nb8080/.idea","/home/
1495822358648 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["/home/daftspaniel/WebstormProjects/nb8080/web/lib/board.dart"]},"clientRequestTime":1495822357828}
1495822358648 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["/home/daftspaniel/WebstormProjects/nb8080/web/lib/board.dart"],"OVERRIDES":["/home/daftspaniel
1495822358688 <= {"id":"1"}
1495822358711 <= {"id":"2"}
1495822358905 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1495822358917 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1495822359461 <= {"id":"3"}
1495822359469 <= {"id":"4"}
1495822359485 <= {"id":"5"}
1495822359499 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1495822362777 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /home/daftspaniel/WebstormProjects/nb8080/web/main.dart","stackTrace":"NoSuchMethodError: The getter 'len
```

**Comment by daftspaniel** [comment]
Offending code:
```
//  void putNoteColorsInPicker() {
//    var rgb = activeNote.note.style.backgroundColor;
//    rgb = rgb.replaceAll(' ', '').replaceAll('rgb(', '').replaceAll(')', '');
//    print(int.parse(1).toRadixString(16));
//
//    var p = rgb.split(',');
//    print(p.length);
//    print(p[0]);
//    print(p[1]);
//    print(p[2]);
//
//    var r = int.parse(p[0]).toRadixString(16);
//    var g = int.parse(p[1]).toRadixString(16);
//    var b = int.parse(p[2]).toRadixString(16);
//    print('#$r$g$b');
//    backColor.value = '#$r$g$b';
//    foreColor.value = '#$r$g$b';
//  }
```

This was half done code - now updated and no crash :+1:

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
