### ISSUE TITLE
_HttpClientBasicCredentials appears out of nowhere with SIMD, hot reload

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#29734]
Running against 4de9d7162939, [the vm-mac-release-simdbc64-reload-be builder](https://build.chromium.org/p/client.dart/builders/vm-mac-release-simdbc64-reload-be/builds/857/steps/checked%20vm%20tests/logs/stdio) produced this error:

```
FAILED: none-vm-checked release_simdbc64 vm/dart/byte_array_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.throws: Unexpected 'Instance of '_HttpClientBasicCredentials''
Instance of '_HttpClientBasicCredentials'
#0      Expect._fail (package:expect/expect.dart:464:5)
#1      Expect.throws (package:expect/expect.dart:452:11)
#2      ByteArrayTest.testUint32ListViewImpl (file:///b/build/slave/vm-mac-release-simdbc64-reload-be/build/sdk/runtime/tests/vm/dart/byte_array_test.dart:2922:12)
#3      ByteArrayTest.testUint32ListView (file:///b/build/slave/vm-mac-release-simdbc64-reload-be/build/sdk/runtime/tests/vm/dart/byte_array_test.dart:3213:5)
#4      ByteArrayTest.testMain (file:///b/build/slave/vm-mac-release-simdbc64-reload-be/build/sdk/runtime/tests/vm/dart/byte_array_test.dart:4859:5)
#5      main (file:///b/build/slave/vm-mac-release-simdbc64-reload-be/build/sdk/runtime/tests/vm/dart/byte_array_test.dart:4871:19)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


Command[vm]: DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --enable_asserts --enable_type_checks --hot-reload-test-mode --optimization_counter_threshold=10 --disable_alloc_stubs_after_gc --no-background-compilation --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-release-simdbc64-reload-be/build/sdk/.packages /b/build/slave/vm-mac-release-simdbc64-reload-be/build/sdk/runtime/tests/vm/dart/byte_array_test.dart
Took 0:00:04.145569

Short reproduction command (experimental):
    python tools/test.py -mrelease -asimdbc64 --checked --hot-reload -t240 vm/dart/byte_array_test
```

This seems to be a flake, but it looks like something's going wrong deep in the VM. `byte_array_test` doesn't make any reference to HTTP, nor does it so much as transitively import `dart:io`. The line that produced the error is `view[-1] = 0;`, where `view` is a `Uint8List`.

I'm guessing the flake has to do with hot-reload infrastructure and not with `byte_array_test` in particular, so I'm not changing its status.

**Comment by mraleph** [comment]
Did not happen in a while - assuming obsolete.
