### ISSUE TITLE
dartk-vm service/step_through_property_get_test regression 

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#29740]
Started with 3b9cf7351bb0:

```
FAILED: dartk-vm release_x64 service/step_through_property_get_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseX64/dart -DDART_SERVICE_USE_AUTH=false --pause-isolates-on-start --pause-isolates-on-exit --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --platform=out/ReleaseX64/patched_sdk/platform.dill --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-linux-release-x64-be/build/sdk/.packages --enable-vm-service:0 /b/build/slave/vm-kernel-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/step_through_property_get_test.dart
** Signaled to run test queries on http://127.0.0.1:41063/
>testee>out> Observatory listening on http://127.0.0.1:41063/
Loading VM...
Done loading VM
Running step_through_property_get_test.dart [1/4]
Paused with PauseStart
Running step_through_property_get_test.dart [2/4]
Setting breakpoint for line 33
>testee>err> Dumping native stack trace for thread 6c52
>testee>err>   [0x0000000000a45bfe] dart::TokenStream::Iterator::Iterator(dart::Zone*, dart::TokenStream const&, dart::TokenPosition, dart::TokenStream::Iterator::StreamType)
>testee>err>   [0x0000000000a45bfe] dart::TokenStream::Iterator::Iterator(dart::Zone*, dart::TokenStream const&, dart::TokenPosition, dart::TokenStream::Iterator::StreamType)
>testee>err>   [0x0000000000aa1028] dart::Parser::Parser(dart::Script const&, dart::Library const&, dart::TokenPosition)
>testee>err>   [0x0000000000aa5077] dart::Parser::FieldHasFunctionLiteralInitializer(dart::Field const&, dart::TokenPosition*, dart::TokenPosition*)
>testee>err>   [0x0000000000905bc4] dart::Debugger::FindBestFit(dart::Script const&, dart::TokenPosition, dart::TokenPosition, dart::Function*)
>testee>err>   [0x0000000000905ce2] dart::Debugger::SetBreakpoint(dart::Script const&, dart::TokenPosition, dart::TokenPosition, long, long)
>testee>err>   [0x00000000009066b1] dart::Debugger::BreakpointLocationAtLineCol(dart::String const&, long, long)
>testee>err>   [0x000000000090674e] dart::Debugger::SetBreakpointAtLineCol(dart::String const&, long, long)
>testee>err>   [0x0000000000baf4fb] Unknown symbol
>testee>err>   [0x0000000000ba81a0] Unknown symbol
>testee>err>   [0x0000000000ba5fa1] dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
>testee>err>   [0x0000000000ba66d7] dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
>testee>err>   [0x00000000009d8450] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
>testee>err>   [0x00000000009ff1aa] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
>testee>err>   [0x00000000009ff518] dart::MessageHandler::TaskCallback()
>testee>err>   [0x0000000000bea10d] dart::ThreadPool::Worker::Loop()
>testee>err>   [0x0000000000be9fba] dart::ThreadPool::Worker::Main(unsigned long)
>testee>err>   [0x0000000000a99e29] Unknown symbol
>testee>err> -- End of DumpStackTrace
** Killing script
Unexpected exception in service tests: NetworkRpcException(Canceling request: WebSocket closed(id: 10 method: addBreakpoint params: {scriptId: libraries/@16183050/scripts/file%3A%2F%2F%2Fb%2Fbuild%2Fslave%2Fvm-kernel-linux-release-x64-be%2Fbuild%2Fsdk%2Fruntime%2Fobservatory%2Ftests%2Fservice%2Fstep_through_property_get_test.dart/15c471944e0, line: 33, isolateId: isolates/167114476}))
#0      setBreakpointAtLine.<anonymous closure> (file:///b/build/slave/vm-kernel-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/service_test_common.dart:242:22)
<asynchronous suspension>
#1      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/vm-kernel-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:326:23)
<asynchronous suspension>
#2      _rootRunUnary (patched_sdk/lib/async/zone.dart:1128:38)
#3      _CustomZone.runUnary (patched_sdk/lib/async/zone.dart:1012:19)
#4      _FutureListener.handleValue (patched_sdk/lib/async/future_impl.dart:129:18)
#5      _Future._propagateToListeners.handleValueCallback (patched_sdk/lib/async/future_impl.dart:636:45)
#6      _Future._propagateToListeners (patched_sdk/lib/async/future_impl.dart:665:32)
#7      _Future._completeWithValue (patched_sdk/lib/async/future_impl.dart:478:5)
#8      _Future._asyncComplete.<anonymous closure> (patched_sdk/lib/async/future_impl.dart:510:7)
#9      _rootRun (patched_sdk/lib/async/zone.dart:1120:13)
#10     _CustomZone.run (patched_sdk/lib/async/zone.dart:1001:19)
#11     _CustomZone.runGuarded (patched_sdk/lib/async/zone.dart:901:14)
#12     _CustomZone.bindCallback.<anonymous closure> (patched_sdk/lib/async/zone.dart:926:20)
#13     _microtaskLoop (patched_sdk/lib/async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (patched_sdk/lib/async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate:1083:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate:1133:5)



stderr:
Unhandled exception:
NetworkRpcException(Canceling request: WebSocket closed(id: 10 method: addBreakpoint params: {scriptId: libraries/@16183050/scripts/file%3A%2F%2F%2Fb%2Fbuild%2Fslave%2Fvm-kernel-linux-release-x64-be%2Fbuild%2Fsdk%2Fruntime%2Fobservatory%2Ftests%2Fservice%2Fstep_through_property_get_test.dart/15c471944e0, line: 33, isolateId: isolates/167114476}))
#0      _ServiceTesterRunner.run.<anonymous closure> (file:///b/build/slave/vm-kernel-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:341:9)
<asynchronous suspension>
#1      _rootRunBinary (patched_sdk/lib/async/zone.dart:1144:13)
#2      _RootZone.runBinary (patched_sdk/lib/async/zone.dart:1377:12)
#3      runZoned.<anonymous closure> (patched_sdk/lib/async/zone.dart:1443:30)
#4      _CustomZone.handleUncaughtError (patched_sdk/lib/async/zone.dart:981:19)
#5      _Future._propagateToListeners (patched_sdk/lib/async/future_impl.dart:552:16)
#6      _Future._completeError (patched_sdk/lib/async/future_impl.dart:486:5)
#7      _SyncCompleter._completeError (patched_sdk/lib/async/future_impl.dart:55:12)
#8      _Completer.completeError (patched_sdk/lib/async/future_impl.dart:27:5)
#9      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/vm-kernel-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart)
<asynchronous suspension>
#10     _rootRunUnary (patched_sdk/lib/async/zone.dart:1128:38)
#11     _CustomZone.runUnary (patched_sdk/lib/async/zone.dart:1012:19)
#12     _FutureListener.handleValue (patched_sdk/lib/async/future_impl.dart:129:18)
#13     _Future._propagateToListeners.handleValueCallback (patched_sdk/lib/async/future_impl.dart:636:45)
#14     _Future._propagateToListeners (patched_sdk/lib/async/future_impl.dart:665:32)
#15     _Future._completeWithValue (patched_sdk/lib/async/future_impl.dart:478:5)
#16     _Future._asyncComplete.<anonymous closure> (patched_sdk/lib/async/future_impl.dart:510:7)
#17     _rootRun (patched_sdk/lib/async/zone.dart:1120:13)
#18     _CustomZone.run (patched_sdk/lib/async/zone.dart:1001:19)
#19     _CustomZone.runGuarded (patched_sdk/lib/async/zone.dart:901:14)
#20     _CustomZone.bindCallback.<anonymous closure> (patched_sdk/lib/async/zone.dart:926:20)
#21     _microtaskLoop (patched_sdk/lib/async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (patched_sdk/lib/async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate:1083:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate:1133:5)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --platform=out/ReleaseX64/patched_sdk/platform.dill --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-linux-release-x64-be/build/sdk/.packages /b/build/slave/vm-kernel-linux-release-x64-be/build/sdk/runtime/observatory/tests/service/step_through_property_get_test.dart
Took 0:00:06.435134

Short reproduction command (experimental):
    python tools/test.py -m release -c dartk -t 60 --builder-tag no_ipv6 service/step_through_property_get_test
```

**Comment by aam** [comment]
Fixed by https://codereview.chromium.org/2907003002/
