### ISSUE TITLE
Dart analyzer crash

### ISSUE THREAD

**Issue by TimIrwin26** [dart-lang/sdk#29757]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA 172.2465.6`
- `1.22.0`
- `IU-172.2465.6, JRE 1.8.0_152-release-855-b1x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.5 unknown, screens 1920x1080, 1280x800`

# Exception

Please append the contents of:
file:///private/var/folders/7q/y_bcf83s5v7_pb5lfd83yw_m0000gp/T/report.txt
[report.txt](https://github.com/dart-lang/sdk/files/1039914/report.txt)

```
Dart analysis server, SDK version 1.22.0, server version 1.17.0, error: Task failed: ResolveUnitTask for source /Users/tirwin/maui/frontend/maui_frontend/lib/hcm_application.dart
Unexpected exception while performing ResolveUnitTask for source /Users/tirwin/maui/frontend/maui_frontend/lib/hcm_application.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)

**Comment by TimIrwin26** [comment]
Analyzer issue reported by IntelliJ

**Comment by bwilkerson** [comment]
Any information on how to reproduce the issue? I expect that this is obsolete, but wouldn't mind confirming that if possible.

**Comment by TimIrwin26** [comment]
No idea, running IJ EAP, happened twice today, apparently randomly while 
I was working.

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
