### ISSUE TITLE
hot_reload_e2e_test is flaky

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29819]
```
FAILED: none-vm-checked release_x64 pkg/front_end/test/src/incremental/hot_reload_e2e_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
00:00 +0: initial program is valid
00:15 +1: reload after leaf library modification
00:25 +2: reload after non-leaf library modification
00:25 +2 ~1: reload after whole program modification
00:34 +3 ~1: reload twice
00:44 +3 ~1 -1: reload twice
  Expected: empty
    Actual: [
    '../../runtime/vm/kernel_binary_flowgraph.cc: 1289: error: unreachable code',
    'Dumping native stack trace for thread 1703',
    '  [0x000000010e6a7e57] dart::Profiler::DumpStackTrace(bool)',
    '  [0x000000010e6a7e57] dart::Profiler::DumpStackTrace(bool)',
    '  [0x000000010e3240b3] dart::DynamicAssertionHelper::Fail(char const*, ...)',
    '  [0x000000010e659f5f] dart::kernel::StreamingFlowGraphBuilder::BuildStatement()',
    '  [0x000000010e6799c2] dart::kernel::FlowGraphBuilder::BuildGraphOfFunction(dart::kernel::FunctionNode*, dart::kernel::Constructor*)',
    '  [0x000000010e678262] dart::kernel::FlowGraphBuilder::BuildGraph()',
    '  [0x000000010e4039bb] dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*> const&, long)',
    '  [0x000000010e406496] dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)',
    '  [0x000000010e407ec0] dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long)',
    '  [0x000000010e407839] dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)',
    '  [0x000000010e403ce2] dart::DRT_CompileFunction(dart::NativeArguments)',
    '  [0x00000001103ee61b] [Stub] CallToRuntime',
    '  [0x00000001103ee690] [Stub] LazyCompile',
    '  [0x0000000111fb6ad7] f',
    '  [0x0000000111fb6863] main.<anonymous closure>',
    '  [0x0000000111f937b8] _Closure.call',
    '  [0x0000000111fb49b0] _Timer._runTimers',
    '  [0x0000000111fb39c8] _Timer._handleMessage',
    '  [0x0000000111fb380f] _Timer._handleMessage',
    '  [0x0000000111f937b8] _Closure.call',
    '  [0x0000000111faafbf] _RawReceivePortImpl._handleMessage',
    '  [0x00000001103eea59] [Stub] InvokeDartCode',
    ...
  ]
  ../../runtime/vm/kernel_binary_flowgraph.cc: 1289: error: unreachable code
  Dumping native stack trace for thread 1703
    [0x000000010e6a7e57] dart::Profiler::DumpStackTrace(bool)
    [0x000000010e6a7e57] dart::Profiler::DumpStackTrace(bool)
    [0x000000010e3240b3] dart::DynamicAssertionHelper::Fail(char const*, ...)
    [0x000000010e659f5f] dart::kernel::StreamingFlowGraphBuilder::BuildStatement()
    [0x000000010e6799c2] dart::kernel::FlowGraphBuilder::BuildGraphOfFunction(dart::kernel::FunctionNode*, dart::kernel::Constructor*)
    [0x000000010e678262] dart::kernel::FlowGraphBuilder::BuildGraph()
    [0x000000010e4039bb] dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*> const&, long)
    [0x000000010e406496] dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
    [0x000000010e407ec0] dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long)
    [0x000000010e407839] dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)
    [0x000000010e403ce2] dart::DRT_CompileFunction(dart::NativeArguments)
    [0x00000001103ee61b] [Stub] CallToRuntime
    [0x00000001103ee690] [Stub] LazyCompile
    [0x0000000111fb6ad7] f
    [0x0000000111fb6863] main.<anonymous closure>
    [0x0000000111f937b8] _Closure.call
    [0x0000000111fb49b0] _Timer._runTimers
    [0x0000000111fb39c8] _Timer._handleMessage
    [0x0000000111fb380f] _Timer._handleMessage
    [0x0000000111f937b8] _Closure.call
    [0x0000000111faafbf] _RawReceivePortImpl._handleMessage
    [0x00000001103eea59] [Stub] InvokeDartCode
    [0x000000010e41bd00] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
    [0x000000010e41f2be] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
    [0x000000010e503a31] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
    [0x000000010e52d7c6] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
    [0x000000010e52dccd] dart::MessageHandler::TaskCallback()
    [0x000000010e745b8d] dart::ThreadPool::Worker::Loop()
    [0x000000010e745a31] dart::ThreadPool::Worker::Main(unsigned long)
    [0x000000010e5d9a87] dart::ThreadStart(void*)
    [0x00007fffdf3a593b] _pthread_body
    [0x00007fffdf3a5887] _pthread_body
    [0x00007fffdf3a508d] thread_start
  -- End of DumpStackTrace
  
  package:test                                                        expect
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 79:7    main.startProgram.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                          _Future.then
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 78:68   main.startProgram
  ===== asynchronous gap ===========================
  dart:async                                                          _asyncThenWrapperHelper
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 52:39   main.startProgram
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 138:23  main.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                          new Future.microtask
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 137:33  main.<fn>
  
  Expected: <4>
    Actual: <3>
  
  package:test                                                        expect
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 75:7    main.startProgram.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                          _BoundSinkStream.listen
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 71:59   main.startProgram
  ===== asynchronous gap ===========================
  dart:async                                                          _asyncThenWrapperHelper
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 52:39   main.startProgram
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 138:23  main.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                          new Future.microtask
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 137:33  main.<fn>
  
  NoSuchMethodError: The method '[]' was called on null.
  Receiver: null
  Tried calling: [](3)
  dart:core                                                           Object.noSuchMethod
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 152:23  main.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                          _Completer.completeError
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 153:3   main.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                          _asyncThenWrapperHelper
  pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart 137:33  main.<fn>
  
00:44 +3 ~1 -1: Some tests failed.



stderr:
Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1108)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


Command[vm]: DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/Users/ahe/w/dart-sdk/sdk/.packages /Users/ahe/w/dart-sdk/sdk/pkg/front_end/test/src/incremental/hot_reload_e2e_test.dart
Took 0:00:45.537932

Short reproduction command (experimental):
    python tools/test.py -m release --checked -t 240 pkg/front_end/test/src/incremental/hot_reload_e2e_test
```

**Comment by a-siva** [comment]
Looks like some kind of memory corruption issue, will take a look.

**Comment by sigmundch** [comment]
@a-siva just curious if this has been fixed and we can reenable the test. I noticed the test is starting to get out of date (here is a CL updating it https://codereview.chromium.org/2976553002 to use the new --kernel-binaries flag).

**Comment by a-siva** [comment]
Submitted https://github.com/dart-lang/sdk/commit/53cf85abc80fc804caddc2c680e696d6e6049113, closing issue.
