### ISSUE TITLE
pkg/analysis_server/test/integration/diagnostic/get_server_port_test is failing on pkg-linux-release-be

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#29820]
Failure introduced by 79c2668d2b3256f291a6ef826efb08b16e777522

```
FAILED: none-vm-checked release_x64 pkg/analysis_server/test/integration/diagnostic/get_server_port_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
00:00 +0: GetServerPortTest | test_connect
00:03 +0 -1: GetServerPortTest | test_connect
  {id: 2, error: {code: DEBUG_PORT_COULD_NOT_BE_OPENED, message: 'package:analysis_server/protocol/protocol_generated.dart': Failed assertion: line 5349 pos 12: 'value != null': is not true.}}
  dart:async                                                                  _Completer.completeError
  pkg/analysis_server/test/integration/support/integration_tests.dart 590:21  Server.listenToOutput.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                                  _BoundSinkStream.listen
  pkg/analysis_server/test/integration/support/integration_tests.dart 564:10  Server.listenToOutput
  pkg/analysis_server/test/integration/support/integration_tests.dart 207:12  AbstractAnalysisServerIntegrationTest.setUp
  ===== asynchronous gap ===========================
  dart:async                                                                  _asyncThenWrapperHelper
  pkg/analysis_server/test/integration/support/integration_tests.dart 186:24  AbstractAnalysisServerIntegrationTest.setUp
  dart:mirrors                                                                _LocalClosureMirror.apply
  package:test_reflective_loader/test_reflective_loader.dart 215:32           _invokeSymbolIfExists
  package:test_reflective_loader/test_reflective_loader.dart 238:10           _runTest
  package:test_reflective_loader/test_reflective_loader.dart 126:18           defineReflectiveTests.<fn>.<fn>
  
00:03 +0 -1: Some tests failed.



stderr:
Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1108)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/b/build/slave/pkg-linux-release-be/build/sdk/.packages /b/build/slave/pkg-linux-release-be/build/sdk/pkg/analysis_server/test/integration/diagnostic/get_server_port_test.dart
Took 0:00:04.536153

Short reproduction command (experimental):
    python tools/test.py -m release --checked --use-sdk pkg/analysis_server/test/integration/diagnostic/get_server_port_test
```

**Comment by mraleph** [comment]
The test is now marked as failing to keep the bot green

**Comment by devoncarew** [comment]
@mraleph, thanks for the triage! (and sorry for the failure) - will investigate

**Comment by mraleph** [comment]
It seems that this test somehow relies on IPv6 present - because it passes on IPv6 enabled buildbots. However this particular bot has only IPv4.

**Comment by devoncarew** [comment]
fixed by https://codereview.chromium.org/2930003002/
