### ISSUE TITLE
enqueuer.remainingTestCases.isEmpty': is not true

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29842]
```
$ ./tools/test.py --time -pcolor --report -ax64 -mrelease,debug -cdartkp,dartk -rdart_precompiled,none language//constants_test 
Warning: combination of compiler 'dartk' and runtime 'dart_precompiled' is invalid. Skipping this combination.
Warning: combination of compiler 'dartk' and runtime 'dart_precompiled' is invalid. Skipping this combination.
Warning: combination of compiler 'dartkp' and runtime 'none' is invalid. Skipping this combination.
Warning: combination of compiler 'dartkp' and runtime 'none' is invalid. Skipping this combination.
Test configurations: dartkp_dart_precompiled_release_x64 dartkp_dart_precompiled_debug_x64 dartk_none_release_x64 dartk_none_debug_x64
Total: 24 tests
 * 0 tests will be skipped (0 skipped by design)
 * 0 tests are expected to be flaky but not crash
 * 0 tests are expected to flaky crash
 * 20 tests are expected to pass
 * 0 tests are expected to fail that we won't fix
 * 0 tests are expected to fail that we should fix
 * 4 tests are expected to crash that we should fix
 * 0 tests are allowed to timeout
 * 0 tests are skipped on browsers due to compile-time error
 * 0 could not be categorized or are in multiple categories

[00:28 |  50% | +   12 | -    0]Unhandled exception:
'file:///.../tools/testing/dart/test_runner.dart': Failed assertion: line 2988 pos 14: 'enqueuer.remainingTestCases.isEmpty': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:35)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:31)
#2      new TestCaseCompleter.<anonymous closure> (file:///.../tools/testing/dart/test_runner.dart:2988:14)
#3      _RootZone.runGuarded (dart:async/zone.dart:1296)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:384)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:394)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277)
#7      _StreamController&&_SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:775)
#8      _StreamController._closeUnchecked (dart:async/stream_controller.dart:627)
#9      _StreamController.close (dart:async/stream_controller.dart:620)
#10     CommandQueue._checkDone.<anonymous closure> (file:///.../tools/testing/dart/test_runner.dart:2628:30)
#11     _RootZone.runUnary (dart:async/zone.dart:1371)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#15     _Future._completeWithValue (dart:async/future_impl.dart:478)
#16     Future.wait.<anonymous closure> (dart:async/future.dart:362)
#17     _RootZone.runUnary (dart:async/zone.dart:1371)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#19     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#20     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#21     _Future._completeWithValue (dart:async/future_impl.dart:478)
#22     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by peter-ahe-google** [comment]
This appears to be due to these two options:

    -cdartkp,dartk -rdart_precompiled,none

**Comment by peter-ahe-google** [comment]
@munificent

**Comment by peter-ahe-google** [comment]
It's the configuration -rnone that's causing the problem. This is probably an old bug.

**Comment by peter-ahe-google** [comment]
This works:

```
./tools/test.py --time -pcolor --report -ax64 -mrelease,debug -cdartkp,dartk -rdart_precompiled,vm language//constants_test
```

I'm not really sure what -rnone is.

**Comment by munificent** [comment]
Thanks, I'll take a look.
