### ISSUE TITLE
dart2js/dill_loader_test

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29856]
```
FAILED: none-vm-checked release_x64 dart2js/dill_loader_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <255>, 'Unhandled exception:
Could not find _ConstantExpressionError in dart:core
#0      DartLoader.loadSdkInterface (package:analyzer/src/kernel/loader.dart:743:11)
#1      batchMain (file:///Users/ahe/w/dart-sdk/sdk/pkg/kernel/tool/dartk.dart:359:12)
<asynchronous suspension>
#2      main (file:///Users/ahe/w/dart-sdk/sdk/pkg/kernel/tool/dartk.dart:227:37)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
') fails.
#0      Expect._fail (package:expect/expect.dart:464:5)
#1      Expect.equals (package:expect/expect.dart:124:5)
#2      runDartk (file:///Users/ahe/w/dart-sdk/sdk/tests/compiler/dart2js/dill_loader_test.dart:32:10)
#3      main.<anonymous closure> (file:///Users/ahe/w/dart-sdk/sdk/tests/compiler/dart2js/dill_loader_test.dart:56:30)
<asynchronous suspension>
#4      asyncTest (package:async_helper/async_helper.dart:93:4)
#5      main (file:///Users/ahe/w/dart-sdk/sdk/tests/compiler/dart2js/dill_loader_test.dart:50:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


Command[vm]: DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/Users/ahe/w/dart-sdk/sdk/.packages /Users/ahe/w/dart-sdk/sdk/tests/compiler/dart2js/dill_loader_test.dart
Took 0:00:08.674354

Short reproduction command (experimental):
    python tools/test.py -m release --checked -t 240 --dart2js-batch dart2js/dill_loader_test
```

**Comment by peter-ahe-google** [comment]
But it's right there: https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/errors.dart#L563

**Comment by sigmundch** [comment]
It appears that this test is building the kernel file using `tools/dartk_wrappers/dartk`, which (a) uses the old dartk frontend, (b) calls it using the checked-in vm in used by test.dart (under tools/sdk/...), (c) we don't specify an sdk location, so it doesn't consume the files from the sdk sources in master.

We should take this opportunity to create the .dill file using fasta instead and invoke it using the public APIs in `package:front_end`.
