### ISSUE TITLE
Fix reading of named mixin applications from dill files

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#29855]
The way named mixin applications are read from dill files should be fixed. Currently their `supertype` fields seem to be broken. Here is an example of a stacktrace one may get when trying to access `supertype` field of such type after reading the type from a dill file.

```
Unhandled exception:
Reference to root::dart:core::Object is not bound to an AST node. A class was expected
#0      Reference.asClass (package:kernel/ast.dart:199:7)
#1      Supertype.classNode (package:kernel/ast.dart:4303:36)
#2      Printer.visitSupertype (package:kernel/text/ast_to_text.dart:431:32)
#3      Supertype.accept (package:kernel/ast.dart:4305:26)
#4      Printer.writeNode (package:kernel/text/ast_to_text.dart:394:12)
#5      debugNodeToString (package:kernel/text/ast_to_text.dart:94:61)
#6      Node.toString (package:kernel/ast.dart:84:24)
#7      _StringBase._interpolate (dart:core-patch/string_patch.dart:812)
#8      BinaryBuilder.readClass (package:kernel/binary/ast_from_binary.dart:462:66)
#9      BinaryBuilder._fillTreeNodeList (package:kernel/binary/ast_from_binary.dart:164:28)
#10     BinaryBuilder._mergeNamedNodeList (package:kernel/binary/ast_from_binary.dart:187:7)
#11     BinaryBuilder.readLibrary (package:kernel/binary/ast_from_binary.dart:362:5)
#12     BinaryBuilder._readOneProgram (package:kernel/binary/ast_from_binary.dart:263:22)
#13     BinaryBuilder.readProgram (package:kernel/binary/ast_from_binary.dart:224:7)
#14     loadProgramFromBytes (package:kernel/kernel.dart:32:28)
#15     _appendDillForUri (package:front_end/src/fasta/fasta.dart:298:25)
#16     writeDepsFile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:282:5)
<asynchronous suspension>
#17     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1001)
#20     runZoned (dart:async/zone.dart:1466)
...
```

Later the field eventually end up having `null` value. I discovered the issue trying to run a dart script with a `platform.dill` that wasn't processed by the mixin transformation. During outline building in fasta `installDefaultConstructors` tries to follow `supertype` links of mixin applications and eventually reaches `null` where `Object` was expected.

**Comment by kmillikin** [comment]
Related issue #31690.  I agree that this code should be more robust, at least by checking its preconditions.
