### ISSUE TITLE
New watches result in OptimizedOut sentinel which throws an exception

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#29874]
I am experiencing this intermittently when trying to add watches when stopped at a breakpoint in IntelliJ.  Once it starts my debug session seems to get into a permanently wedged state.

Dart SDK is 1.24.0 Linux.

```
2017-06-14 13:41:41,165 [186149932]  ERROR - vice.DartVmServiceDebugProcess - IntelliJ IDEA 2017.1.1  Build #IC-171.4073.35 
2017-06-14 13:41:41,165 [186149932]  ERROR - vice.DartVmServiceDebugProcess - JDK: 1.8.0_112-release 
2017-06-14 13:41:41,166 [186149933]  ERROR - vice.DartVmServiceDebugProcess - VM: OpenJDK 64-Bit Server VM 
2017-06-14 13:41:41,166 [186149933]  ERROR - vice.DartVmServiceDebugProcess - Vendor: JetBrains s.r.o 
2017-06-14 13:41:41,166 [186149933]  ERROR - vice.DartVmServiceDebugProcess - OS: Linux 
2017-06-14 13:41:41,166 [186149933]  ERROR - vice.DartVmServiceDebugProcess - Last Action: $Copy 
2017-06-14 13:41:41,167 [186149934]  ERROR - vice.DartVmServiceDebugProcess - Expected response for class com.jetbrains.lang.dart.ide.runner.server.vmService.VmServiceWrapper$10
  implementing interface org.dartlang.vm.service.consumer.EvaluateInFrameConsumer
  but received {"type":"Sentinel","kind":"OptimizedOut","valueAsString":"<optimized out>"} 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcess$3.logError(DartVmServiceDebugProcess.java:177)
	at org.dartlang.vm.service.VmServiceBase.logUnknownResponse(VmServiceBase.java:341)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:546)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:99)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by jcollins-g** [comment]
It looks a little bit like #26824, but so far I haven't seen this be fatal for the application being debugged.

**Comment by jcollins-g** [comment]
I can now be more specific on when this comes up.  And while the bug does permanently prevent watches for the given variables, the rest of the debug session seems to work fine contrary to my initial impression.

Problem occurred while doing some exploratory debugging of this section of code:
```
    for (String fieldName in accessorMap.keys) {
      List<PropertyAccessorElement> elements = accessorMap[fieldName];
      // TODO(jcollins-g): why doesn't the analyzer put these fields in _cls.fields?
      FieldElement f = Package.getBasestElement(elements.first.variable);
      // Two accessors here from different variables shouldn't be possible, right?
      assert(!elements.any((e) => Package.getBasestElement(e.variable) != f));
      PropertyAccessorElement getterElement = f.getter;
      PropertyAccessorElement setterElement = f.setter;
      Accessor getter = new InheritableAccessor.from(getterElement, inheritedAccessors, this);
      Accessor setter = new InheritableAccessor.from(setterElement, inheritedAccessors, this);
      inheritedAccessors.removeAll([getterElement, setterElement]);
      if ((getter != null && getter.isInherited) || (setter != null && setter.isInherited)) {
        // Field is >=50% inherited.
        // TODO(jcollins-g): make half-inherited fields half-italicized...?
        _fields.add(new ModelElement.from(f, library, enclosingClass: this,
                                          getter: getter, setter: setter));
      } else {
        _fields.add(new ModelElement.from(f, library,
                                          getter: getter, setter: setter));
      }
    }
```

The first "new ModelElement.from" case raised an exception and I was stopped in the debugger looking at this method for why.  I noticed that "getterElement" was not present in the list of variables and so therefore tried to add a watch for it.  That watch never appeared and resulted in the backtrace, above.  Same with setterElement.

On a whim, I refactored this to remove the extraneous getterElement variable, and use f.getter directly.  That is a functional workaround that avoids the exception.

**Comment by jcollins-g** [comment]
Some more details that may be helpful: this only seems to happen when an exception is raised, stopping the code in the debugger.  I can reproduce this by generating an exception with an assertion vs using a breakpoint on the same condition.  A breakpoint works fine -- all variables appear correctly.

**Comment by alexander-doroshko** [comment]
@devoncarew Can this exception be solved at https://github.com/dart-lang/vm_service_drivers level?

**Comment by devoncarew** [comment]
I'd have to look a bit more at the problem. I'd guess the issue is that the interface only supports returning an `InstanceRef`? In the wrapper library, we could catch sentinel types and map that to the error response (in that interface, a `ErrorRef`).

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/vm_service_drivers#169
