### ISSUE TITLE
Fasta compiler in checked mode triggers an assertion in transformations/erasure.dart

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#29898]
Running fasta compiler in **checked** mode throws an exception quoted below.
Running same script against same input in unchecked mode completes fine.

```
╭─aam@host ~/projects/dart/sdk  ‹master› 
╰─➤  ~/projects/dart/sdk/xcodebuild/ReleaseX64/dart --checked ~/projects/dart/sdk/xcodebuild/ReleaseX64/dart-sdk/lib/front_end/tool/_fasta/compile.dart --packages=/Users/aam/projects/flutter/test_root/flutter/flutter/examples/flutter_gallery/.packages --platform=/Users/aam/projects/flutter/test_root/flutter/engine/src/out/android_debug_unopt/flutter_patched_sdk/platform.dill /Users/aam/projects/flutter/test_root/flutter/flutter/examples/flutter_gallery/lib/main.dart --target=flutter_fasta

...

file:///Users/aam/.pub-cache/hosted/pub.dartlang.org/async-1.13.3/lib/src/typed/stream_subscription.dart:36:13: Warning: Declared type variables of 'TypeSafeStreamSubscription::asFuture' doesn't match those on overridden method 'StreamSubscription::asFuture'.
  Future<E> asFuture<E>([E futureValue]) => _subscription.asFuture(futureValue);
            ^
Unhandled exception:
'package:kernel/transformations/erasure.dart': Failed assertion: line 75 pos 14: 'node.enclosingClass.typeParameters.length ==
          node.function.typeParameters.length': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:35)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:31)
#2      Erasure.visitProcedure (package:kernel/transformations/erasure.dart:75:14)
#3      Procedure.accept (package:kernel/ast.dart:1182:32)
#4      transformList (package:kernel/ast.dart:4471:27)
#5      Class.transformChildren (package:kernel/ast.dart:790:5)
#6      Erasure.visitClass (package:kernel/transformations/erasure.dart:66:10)
#7      Class.accept (package:kernel/ast.dart:730:30)
#8      transformList (package:kernel/ast.dart:4471:27)
#9      Library.transformChildren (package:kernel/ast.dart:366:5)
#10     Transformer.defaultTreeNode (package:kernel/visitor.dart:331:10)
#11     TreeVisitor.visitLibrary (package:kernel/visitor.dart:222:35)
#12     Library.accept (package:kernel/ast.dart:353:30)
#13     transformLibraries (package:kernel/transformations/erasure.dart:18:13)
#14     FlutterFastaTarget.performModularTransformationsOnLibraries (package:kernel/target/flutter_fasta.dart:33:7)
#15     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:678:19)
#16     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:286:7)
<asynchronous suspension>
#17     CompileTask.compile (package:front_end/src/fasta/fasta.dart:164:38)
<asynchronous suspension>
#18     compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#19     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     runZoned (dart:async/zone.dart:1467)
#23     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#24     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#25     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#26     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#27     main (file:///Users/aam/projects/dart/sdk/xcodebuild/ReleaseX64/dart-sdk/lib/front_end/tool/_fasta/compile.dart:7:33)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by aam** [comment]
The source of the parameter mismatch error above seems to be 
```
  factory TickerProviderStateMixin._() => null;
```
at 
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/ticker_provider.dart#L159

**Comment by peter-ahe-google** [comment]
Thank you. I recommend that you avoid running Fasta in checked as it isn't being tested in checked mode yet.

**Comment by aam** [comment]
Ah, good to know, thanks!

**Comment by peter-ahe-google** [comment]
But if you do and find any problems like this, please report them :-)

**Comment by aam** [comment]
I stumbled on this because by default IntelliJ Dart plugin runs the app in checked mode. So in order to run Fasta from IntelliJ I have to make sure to uncheck 'Checked mode' checkbox.

**Comment by peter-ahe-google** [comment]
I see. I normally run all my experiments in checked mode as well.

**Comment by jensjoha** [comment]
This issue relates to a file that was deleted in dd0d299dcbba58587d105f7daf03970c353a0f5e. Closing the issue.
