### ISSUE TITLE
Analyzer Error

### ISSUE THREAD

**Issue by jfphilbin** [dart-lang/sdk#29918]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-171.4249.40`
- `1.24.1`
- `WS-171.4249.40, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2560x1440`

## Exception

Please append the contents of:
file://C:\Users\jim\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.24.1, server version 1.18.0, error: Could not initialize the library map from [C:\tools\dart\stable\sdk\dart-sdk-1.24.1\lib\_internal\sdk_library_metadata\lib\libraries.dart, C:\tools\dart\stable\sdk\dart-sdk-1.24.1\lib\_internal\libraries.dart]

FileSystemException(path=C:\tools\dart\stable\sdk\dart-sdk-1.24.1\lib\_internal\libraries.dart

**Comment by bwilkerson** [comment]
Do you have more information? The FileSystemException is missing the message, so I can't even tell what went wrong. Please check `C:\Users\jim\AppData\Local\Temp\report.txt` to see whether there is more information there that you could send us.

That said, there might be a problem with the installation of the SDK, so it might be worth re-downloading and installing it.

**Comment by bwilkerson** [comment]
@jfphilbin ping

**Comment by jfphilbin** [comment]
```
Dart analysis server, SDK version 1.24.1, server version 1.18.0, error: Could not initialize the library map from [C:\tools\dart\stable\sdk\dart-sdk-1.24.1\lib\_internal\sdk_library_metadata\lib\libraries.dart, C:\tools\dart\stable\sdk\dart-sdk-1.24.1\lib\_internal\libraries.dart]

FileSystemException(path=C:\tools\dart\stable\sdk\dart-sdk-1.24.1\lib\_internal\libraries.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:186)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:616)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:496)
#3      ContextBuilder.findSdk.<anonymous closure> (package:analyzer/src/context/builder.dart:379)
#4      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:131)
#5      DartSdkManager.getSdk (package:analyzer/src/generated/sdk.dart:148)
#6      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:378)
#7      ContextBuilder.createSourceFactory (package:analyzer/src/context/builder.dart:249)
#8      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:166)
#9      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1958)
#10     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1198)
#11     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1241)
#12     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:892)
#13     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:1316)
#14     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:323)
#15     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:253)
#16     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:975)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#18     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:971)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     _CustomZone.runGuarded (dart:async/zone.dart:901)
#22     runZoned (dart:async/zone.dart:1465)
#23     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:970)
#24     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:168)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#26     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:159)
#27     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#28     _rootRunUnary (dart:async/zone.dart:1128)
#29     _CustomZone.runUnary (dart:async/zone.dart:1012)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#36     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#37     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#38     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#40     _rootRunUnary (dart:async/zone.dart:1128)
#41     _CustomZone.runUnary (dart:async/zone.dart:1012)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#47     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#48     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#49     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#50     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#51     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#52     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#53     _rootRunUnary (dart:async/zone.dart:1128)
#54     _CustomZone.runUnary (dart:async/zone.dart:1012)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#58     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#59     _StreamController._add (dart:async/stream_controller.dart:667)
#60     _StreamController.add (dart:async/stream_controller.dart:613)
#61     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#62     _rootRunUnary (dart:async/zone.dart:1132)
#63     _CustomZone.runUnary (dart:async/zone.dart:1012)
#64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#67     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#68     _StreamController._add (dart:async/stream_controller.dart:667)
#69     _StreamController.add (dart:async/stream_controller.dart:613)
#70     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#71     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#72     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#73     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#74     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#75     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)

```

```
1497646208090 started analysis server:
  C:\tools\dart\stable\sdk\dart-sdk-1.24.1\bin\dart C:\tools\dart\stable\sdk\dart-sdk-1.24.1\bin\snapshots\analysis_server.dart.snapshot --client-id=WebStorm --client-version=WS-171.4249.40 --useAnaly
1497646208601 <= {"event":"server.connected","params":{"version":"1.18.0","pid":10520,"sessionId":""}}
1497646208633 <= {"id":"0","result":{"version":"1.18.0"}}
1497646208633 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1497646208092}
1497646208633 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1497646208633 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["C:\\odw\\sdk\\dictionary"],"excluded":["C:\\odw\\sdk\\dictionary\\.idea","C:\\odw\\sdk\\dictionary\\.pub","C:\\od
1497646208633 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["C:\\odw\\sdk\\dictionary\\lib\\src\\string\\char_predicates.dart"]},"clientRequestTime":1497646208093}
1497646208633 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["C:\\odw\\sdk\\dictionary\\lib\\src\\string\\char_predicates.dart"],"OVERRIDES":["C:\\odw\\sdk\
1497646208633 => {"id":"6","method":"edit.getAssists","params":{"file":"C:\\odw\\sdk\\dictionary\\lib\\src\\string\\char_predicates.dart","offset":4439,"length":0},"clientRequestTime":1497646208208}
1497646208639 <= {"id":"1"}
1497646208645 <= {"id":"2"}
1497646208665 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1497646208674 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1497646208849 <= {"event":"server.error","params":{"isFatal":false,"message":"Could not initialize the library map from [C:\\tools\\dart\\stable\\sdk\\dart-sdk-1.24.1\\lib\\_internal\\sdk_library_meta
```

**Comment by bwilkerson** [comment]
> FileSystemException(path=C:\tools\dart\stable\sdk\dart-sdk-1.24.1\lib\_internal\libraries.dart; message=Cannot open file)

There are two possible locations for the libraries.dart file:
`C:\tools\dart\stable\sdk\dart-sdk-1.24.1\lib\_internal\libraries.dart` and
`C:\tools\dart\stable\sdk\dart-sdk-1.24.1\lib\_internal\sdk_library_metadata\lib\libraries.dart`.

Does either of these file exist? Do you have read permission for either of them? If the answer to both is "yes", then perhaps server is running out of file handles.

**Comment by jfphilbin** [comment]
Brian,

 

Sorry for the late reply, I've been on vacation and travelling in remote areas, 

 

I do have both of these files and I do have read permission.  I haven't seen any analyzer errors in a while.

I'm now running 1.24.2.

 

Jim Philbin

Co-Chair, DICOM Standards Committee

Principal

Poplar Hill Informatics

jfphilbin@gmail.com

**Comment by bwilkerson** [comment]
I'm going to assume that the issue has been fixed, but please let us know if you see this or any new issues.
