### ISSUE TITLE
Missing dynamic checks in DDC allows heap unsoundness

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#29912]
The following example illustrates that DDC does not generate all the needed checks in order to ensure heap soundness when we mix covariance (with a generic class) and contravariance (with a function type). The program is accepted by `dartanalyzer --strong n014.dart` with no issues.

```dart
typedef void F<T>(T t);

class C<T> {
  F<T> f;
  C(this.f);
}

class A {
  void a() => print("A");
}

class B extends A {
  void b() => print("B");
}

void foo(B b) {
  print("Reached foo"); // Invocation with argument of type `A` was permitted.
  b.b(); // Low-level failure: "TypeError: b.b is not a function".
}

main() {
  C<A> c = new C<B>(foo); // A plain upcast.
  F<A> f = c.f; // No statically known casts, but should fail in strong mode.
  // However, we're still running!
  print(f.runtimeType); // Prints '(B) -> void', not a subtype of F<A>: Heap not sound.
  f(new A()); // Statically safe, but dynamically unsafe.
}
```
When compiling and executing the program using dartdevc.dart from 5982ace801dc4f222f3a327066d8494be3a969b3, 2017-06-15 14:18:09,  `ddc n014.dart`, the resulting output is as follows:
```
(B) -> void
Reached foo
/usr/local/google/home/eernst/devel/dart/work/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:9877
          throw e;
          ^

TypeError: b.b is not a function
    at n014.foo (/usr/local/google/home/eernst/lang/dart/scratch/201706/n014.js:60:5)
    at n014.main (/usr/local/google/home/eernst/lang/dart/scratch/201706/n014.js:67:3)
    at dart._checkAndCall (/usr/local/google/home/eernst/devel/dart/work/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2287:14)
    at dart.dcall (/usr/local/google/home/eernst/devel/dart/work/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:2292:15)
    at _IsolateContext.eval (/usr/local/google/home/eernst/devel/dart/work/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:9870:21)
    at _isolate_helper.startRootIsolate (/usr/local/google/home/eernst/devel/dart/work/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:9668:17)
    at Object.<anonymous> (/usr/local/google/home/eernst/lang/dart/scratch/201706/n014.run.js:4:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```
The behavior shows that the heap unsoundness occurs already at the initialization of `f` in `main`, and the subsequent invocation of `f` illustrates that this invocation has no argument type check (presumably because the invocation is expected to be safe). Finally, the invocation of a `B` instance method on an `A` in `foo` fails, because that method does not exist.

**Comment by vsmenon** [comment]
@jmesserly - is this a dup?

**Comment by jmesserly** [comment]
yup, this is part of #27259, I mentioned it in this comment https://github.com/dart-lang/sdk/issues/27259#issuecomment-305005599
