### ISSUE TITLE
NoSuchMethodError: The getter 'parameters' was called on null.

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#29925]
Not sure if these are still useful to file or not.

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Adding parameters to a constructor (named, using variables which didn't exist yet).

### Versions

- Dart SDK 1.24.0-dev.6.0
- Visual Studio Code 1.13.1
- Dart Code 1.4.2

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=1.4.2
```

### Exception

Failed to handle completion domain request: {id: 10648, method: completion.getSuggestions, params: {file: /Stuff/Projects/lol_duel/lib/champions/amumu.dart, offset: 1430}}

```text
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _OpTypeAstVisitor.visitNamedExpression (package:analysis_server/src/services/completion/dart/optype.dart:738)
#3      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7764)
#4      new OpType.forCompletion (package:analysis_server/src/services/completion/dart/optype.dart:117)
#5      DartCompletionRequestImpl.opType (package:analysis_server/src/services/completion/dart/completion_manager.dart:185)
#6      DartCompletionRequestImpl.includeIdentifiers (package:analysis_server/src/services/completion/dart/completion_manager.dart:159)
#7      ImportedReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/imported_reference_contributor.dart:44)
<asynchronous suspension>
#8      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:76)
<asynchronous suspension>
#9      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:101)
<asynchronous suspension>
#10     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:210)
<asynchronous suspension>
#11     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:137)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     _CustomZone.runGuarded (dart:async/zone.dart:901)
#15     runZoned (dart:async/zone.dart:1465)
#16     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:134)
#17     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:975)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#19     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:971)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     _CustomZone.runGuarded (dart:async/zone.dart:901)
#23     runZoned (dart:async/zone.dart:1465)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:970)
#25     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:168)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:159)
#28     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#29     _rootRunUnary (dart:async/zone.dart:1128)
#30     _CustomZone.runUnary (dart:async/zone.dart:1012)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#41     _rootRunUnary (dart:async/zone.dart:1128)
#42     _CustomZone.runUnary (dart:async/zone.dart:1012)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#46     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#47     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#48     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#49     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#50     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#51     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#52     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#53     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#54     _rootRunUnary (dart:async/zone.dart:1128)
#55     _CustomZone.runUnary (dart:async/zone.dart:1012)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#59     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#60     _StreamController._add (dart:async/stream_controller.dart:667)
#61     _StreamController.add (dart:async/stream_controller.dart:613)
#62     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#63     _rootRunUnary (dart:async/zone.dart:1132)
#64     _CustomZone.runUnary (dart:async/zone.dart:1012)
#65     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#66     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#67     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#68     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#69     _StreamController._add (dart:async/stream_controller.dart:667)
#70     _StreamController.add (dart:async/stream_controller.dart:613)
#71     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#72     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#73     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#74     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#75     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#76     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by bwilkerson** [comment]
Yes, it is useful, thanks!

Fixed here: https://codereview.chromium.org/2944083002/
