### ISSUE TITLE
VM: Bad API error when Process.start fails with ENOMEM

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#29936]
Normally this results in an uncatchable API error about malformed UTF8. Below is a backtrace with the API error replaced with an abort.

```
(gdb) bt
#0  __libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
#1  0x76d67ee6 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0x76d68bee in __GI_abort () at abort.c:89
#3  0x00357b20 in dart::OS::Abort () at ../../runtime/vm/os_linux.cc:416
#4  0x002046ee in dart::DynamicAssertionHelper::Fail (this=0x76b41440, this@entry=0x76b40140, 
    format=0x6f2aac "%s") at ../../runtime/platform/assert.cc:42
#5  0x001fca7e in dart::Dart_NewStringFromUTF8 (
    utf8_array=0x2926f08 "\030m\222\002\070m\222\002\230m\222\002\330m\222\002\bn\222\002\070n\222\002hn\222\002", length=28) at ../../runtime/vm/dart_api_impl.cc:2430
#6  0x00131b64 in NewString (
    str=0x2926f08 "\030m\222\002\070m\222\002\230m\222\002\330m\222\002\bn\222\002\070n\222\002hn\222\002") at ../../runtime/bin/dartutils.h:168
#7  dart::bin::DartUtils::SetStringField (handle=0x12c4010, name=<optimized out>, 
    val=0x2926f08 "\030m\222\002\070m\222\002\230m\222\002\330m\222\002\bn\222\002\070n\222\002hn\222\002") at ../../runtime/bin/dartutils.cc:159
#8  0x00127ef6 in dart::bin::Builtin_Process_Start (args=0x76b402c8)
    at ../../runtime/bin/process.cc:185
#9  0x00307c5c in dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck (args=0x76b402c8, 
    func=0x127ca1 <dart::bin::Builtin_Process_Start(_Dart_NativeArguments*)>)
    at ../../runtime/vm/native_entry.cc:198
#10 0x76bc24b8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) frame 8
#8  0x00127ef6 in dart::bin::Builtin_Process_Start (args=0x76b402c8)
    at ../../runtime/bin/process.cc:185
185	in ../../runtime/bin/process.cc
(gdb) print error_code
$7 = 12
(gdb) print os_error_message
$8 = 0x2926f08 "\030m\222\002\070m\222\002\230m\222\002\330m\222\002\bn\222\002\070n\222\002hn\222\002"
(gdb) print ENOMEM
$9 = 12

```

**Comment by rmacnak-google** [comment]
One of the Android bots failed with
```
Done dartkp-dart_precompiled release_arm language_2/redirecting_factory_long_test: pass
Done dartkp-dart_precompiled release_arm language_2/covariant_subtyping_tearoff1_test: pass
Unhandled exception:
ProcessException: OS error message was a not a utf8 string.
  Command: adb -s 075670b10ae53094 push /b/build/slave/vm-kernel-precomp-android-release-1-3-be/build/sdk/out/ReleaseAndroidARM/generated_compilations/dartkp/tests_language_2_rewrite_for_update_order_test/out.aotsnapshot /data/local/tmp/precompilation-testing/test/out.aotsnapshot
#0      CommandExecutorImpl._runAdbPrecompilationCommand (file:///b/build/slave/vm-kernel-precomp-android-release-1-3-be/build/sdk/tools/testing/dart/test_runner.dart:1304:16)
<asynchronous suspension>
#1      CommandExecutorImpl._runCommand.<anonymous closure> (file:///b/build/slave/vm-kernel-precomp-android-release-1-3-be/build/sdk/tools/testing/dart/test_runner.dart:1232:16)
#2      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._complete (dart:async/future_impl.dart:476:7)
#7      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#8      _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#11     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#12     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
step returned non-zero exit code: 255
```
and then went offline.
