### ISSUE TITLE
Fasta crash on compilation: ParenthesizedExpression is not a subtype of IncompleteSend

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29943]
@peter-ahe-google 
ID: 1765c0b6778ba2fa1f4e4e933b2d2e817bd556c5
```
Unhandled exception:
type 'ParenthesizedExpression' is not a subtype of type 'IncompleteSend' of 'send' where
  ParenthesizedExpression is from package:front_end/src/fasta/kernel/fasta_accessors.dart
  IncompleteSend is from package:front_end/src/fasta/kernel/fasta_accessors.dart

#0      BodyBuilder.doDotOrCascadeExpression (package:front_end/src/fasta/kernel/body_builder.dart:883:27)
#1      BodyBuilder.handleBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:816:14)
#2      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:2838:22)
#3      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:2784:11)
#4      Parser.parseVariableInitializerOpt (package:front_end/src/fasta/parser/parser.dart:1603:15)
#5      Parser.parseOptionallyInitializedIdentifier (package:front_end/src/fasta/parser/parser.dart:3525:13)
#6      Parser.parseVariablesDeclarationMaybeSemicolon (package:front_end/src/fasta/parser/parser.dart:3505:13)
#7      Parser.parseVariablesDeclaration (package:front_end/src/fasta/parser/parser.dart:3483:12)
#8      Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:2447:14)
#9      Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:2433:20)
#10     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:2363:15)
#11     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:545:14)
#12     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:433:5)
#13     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:214:5)
#14     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:1427:14)
#15     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:1333:11)
#16     Parser._parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:372:14)
#17     Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:344:13)
#18     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#19     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:146:14)
<asynchronous suspension>
#20     Loader.buildBodies (package:front_end/src/fasta/loader.dart:117:13)
<asynchronous suspension>
#21     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:282:20)
<asynchronous suspension>
#22     CompileTask.compile (package:front_end/src/fasta/fasta.dart:164:38)
<asynchronous suspension>
#23     compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#24     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#25     _rootRun (dart:async/zone.dart:1120)
#26     _CustomZone.run (dart:async/zone.dart:1001)
#27     runZoned (dart:async/zone.dart:1467)
#28     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#29     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#30     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#31     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#32     main (file:///home/lukechurch/GitRepos/sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by peter-ahe-google** [comment]
@lukechurch ID missing.

**Comment by lukechurch** [comment]
@peter-ahe-google PTAL

**Comment by peter-ahe-google** [comment]
Repro:

```
main() {
  x.(null);
}
```
