### ISSUE TITLE
Fasta stack trace from compilation Scope.lookup

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29940]
@peter-ahe-google 
ID: a0b033517868b2035cc5449a576cc0717609e005

```
Unhandled exception:
type 'VariableAccessor' is not a subtype of type 'String' of 'name' where
  VariableAccessor is from package:front_end/src/fasta/kernel/fasta_accessors.dart
  String is from dart:core

#0      Scope.lookup (package:front_end/src/fasta/scope.dart:114:25)
#1      BodyBuilder.handleType (package:front_end/src/fasta/kernel/body_builder.dart:1683:25)
#2      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1189:16)
#3      Parser.parseModifiers (package:front_end/src/fasta/parser/parser.dart:1806:30)
#4      Parser.parseVariablesDeclarationMaybeSemicolon (package:front_end/src/fasta/parser/parser.dart:3503:13)
#5      Parser.parseVariablesDeclaration (package:front_end/src/fasta/parser/parser.dart:3483:12)
#6      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:2581:16)
#7      Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:2441:14)
#8      Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:2433:20)
#9      Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:2363:15)
#10     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:545:14)
#11     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:433:5)
#12     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:214:5)
#13     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:1427:14)
#14     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:1333:11)
#15     Parser._parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:372:14)
#16     Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:344:13)
#17     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#18     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:146:14)
<asynchronous suspension>
#19     Loader.buildBodies (package:front_end/src/fasta/loader.dart:117:13)
<asynchronous suspension>
#20     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:282:20)
<asynchronous suspension>
#21     CompileTask.compile (package:front_end/src/fasta/fasta.dart:164:38)
<asynchronous suspension>
#22     compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#23     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#24     _rootRun (dart:async/zone.dart:1120)
#25     _CustomZone.run (dart:async/zone.dart:1001)
#26     runZoned (dart:async/zone.dart:1467)
#27     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#28     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#29     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#30     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#31     main (file:///home/lukechurch/GitRepos/sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by peter-ahe-google** [comment]
@lukechurch ID missing.

**Comment by lukechurch** [comment]
@peter-ahe-google PTAL

**Comment by peter-ahe-google** [comment]
Repro:

```
main() {
  var a = "";
  a.b c = null;
}
```
