### ISSUE TITLE
Fasta crash on compilation: Can't extend an unmodifiable scope

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29942]
@peter-ahe-google 
ID: 618491fb87beb403c3683219044c5160f0019939-main

```
Unhandled exception:
Can't extend an unmodifiable scope.
#0      internalError (package:front_end/src/fasta/errors.dart:38:5)
#1      Scope.declare (package:front_end/src/fasta/scope.dart:196:7)
#2      BodyBuilder.declareVariable (package:front_end/src/fasta/kernel/body_builder.dart:322:30)
#3      BodyBuilder.endFunctionName (package:front_end/src/fasta/kernel/body_builder.dart:2378:5)
#4      Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:2249:14)
#5      Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:3215:14)
#6      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:2972:14)
#7      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:2942:14)
#8      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:2811:13)
#9      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:2784:11)
#10     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:2341:15)
#11     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:545:14)
#12     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:433:5)
#13     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:214:5)
#14     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:1427:14)
#15     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:1333:11)
#16     Parser._parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:372:14)
#17     Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:344:13)
#18     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#19     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:146:14)
<asynchronous suspension>
#20     Loader.buildBodies (package:front_end/src/fasta/loader.dart:117:13)
<asynchronous suspension>
#21     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:282:20)
<asynchronous suspension>
#22     CompileTask.compile (package:front_end/src/fasta/fasta.dart:164:38)
<asynchronous suspension>
#23     compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#24     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#25     _rootRun (dart:async/zone.dart:1120)
#26     _CustomZone.run (dart:async/zone.dart:1001)
#27     runZoned (dart:async/zone.dart:1467)
#28     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#29     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#30     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#31     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#32     main (file:///home/lukechurch/GitRepos/sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by peter-ahe-google** [comment]
@lukechurch ID missing.

**Comment by lukechurch** [comment]
@peter-ahe-google PTAL

**Comment by peter-ahe-google** [comment]
Repro:

```
main() {
}

f() =

h() => null;
```

**Comment by jensjoha** [comment]
I cannot reproduce a crash, but I do get errors etc. Can this issue be closed?
