### ISSUE TITLE
Fasta crash in Source.getLocation

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29976]
@peter-ahe-google
ID: 24ad5571a11e9cf3e55919e76ebdf5480bf3ed82
```
Unhandled exception:
RangeError (offset): Invalid value: Not in range 0..291, inclusive: 293
#0      RangeError.checkValueInInterval (dart:core/errors.dart:267)
#1      Source.getLocation (package:kernel/ast.dart:4546:16)
#2      getLocation (package:front_end/src/fasta/messages.dart:81:9)
#3      format (package:front_end/src/fasta/messages.dart:64:51)
#4      formatUnexpected (package:front_end/src/fasta/errors.dart:72:10)
#5      InputError.format (package:front_end/src/fasta/errors.dart:93:22)
#6      KernelTarget.handleInputError (package:front_end/src/fasta/kernel/kernel_target.dart:218:30)
#7      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:251:7)
<asynchronous suspension>
#8      CompileTask.buildOutline (package:front_end/src/fasta/fasta.dart:149:38)
<asynchronous suspension>
#9      CompileTask.compile (package:front_end/src/fasta/fasta.dart:161:39)
<asynchronous suspension>
#10     compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#11     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     runZoned (dart:async/zone.dart:1467)
#15     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#16     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#17     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#18     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#19     main (file:///home/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

**Comment by peter-ahe-google** [comment]
Repro:

```
void main() {
  f(
    "x${x*"'"é'}x
  )
}
```

**Comment by peter-ahe-google** [comment]
Probably related to #29982.

**Comment by jensjoha** [comment]
I cannot reproduce a crash, but I do get errors etc. Can this issue be closed?
