### ISSUE TITLE
Fasta crash function already bound

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29975]
@peter-ahe-google
ID: 2f89720d770b230c45c7d2837ba45d70abae9833
```
Unhandled exception:
root::REDACTED_FILE_PATH.dart::@typedefs::formatFunction is already bound
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:118:7)
#1      Library.computeCanonicalNames (package:kernel/ast.dart:335:51)
#2      Program.computeCanonicalNames (package:kernel/ast.dart:4376:15)
#3      BinaryPrinter.computeCanonicalNames (package:kernel/binary/ast_to_binary.dart:151:13)
#4      BinaryPrinter.writeProgramFile (package:kernel/binary/ast_to_binary.dart:176:5)
#5      writeProgramToFile (package:front_end/src/fasta/kernel/utils.dart:36:29)
<asynchronous suspension>
#6      CompileTask.compile (package:front_end/src/fasta/fasta.dart:168:11)
<asynchronous suspension>
#7      compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#8      CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#9      _rootRun (dart:async/zone.dart:1120)
#10     _CustomZone.run (dart:async/zone.dart:1001)
#11     runZoned (dart:async/zone.dart:1467)
#12     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#13     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#14     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#15     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#16     main (file:///home/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

**Comment by peter-ahe-google** [comment]
Repro:

```
typedef void F();
typedef void F();

void main() {}
```

**Comment by jensjoha** [comment]
I cannot reproduce the crash, but do get errors about duplicate names. Can this issue be closed?
