### ISSUE TITLE
Fasta crash invalid MIME type

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29977]
@peter-ahe-google
ID: 298ef4cb901b52d10fa398d173185dc75e432b86
```
Unhandled exception:
FormatException: Invalid MIME type (at character 11)
data:async
          ^

#0      UriData._parse (dart:core/uri.dart:3602)
#1      Uri.parse (dart:core/uri.dart:796)
#2      _Uri.resolve (dart:core/uri.dart:2473)
#3      SourceLibraryBuilder.resolve (package:front_end/src/fasta/source/source_library_builder.dart:124:35)
#4      SourceLibraryBuilder.addImport (package:front_end/src/fasta/source/source_library_builder.dart:144:21)
#5      OutlineBuilder.endImport (package:front_end/src/fasta/source/outline_builder.dart:152:15)
#6      Parser.parseImport (package:front_end/src/fasta/parser/parser.dart:410:14)
#7      Parser._parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:366:14)
#8      Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:344:13)
#9      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#10     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:134:37)
<asynchronous suspension>
#11     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:137:13)
<asynchronous suspension>
#12     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:230:20)
<asynchronous suspension>
#13     CompileTask.buildOutline (package:front_end/src/fasta/fasta.dart:149:38)
<asynchronous suspension>
#14     CompileTask.compile (package:front_end/src/fasta/fasta.dart:161:39)
<asynchronous suspension>
#15     compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#16     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     runZoned (dart:async/zone.dart:1467)
#20     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#21     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#22     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#23     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#24     main (file:///home/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

**Comment by peter-ahe-google** [comment]
Repro:

```
import 'data:async';

main() {}
```
