### ISSUE TITLE
Fasta crash: Illegal scheme character

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29987]
@peter-ahe-google
ID: 792b929486920d66096a2d138e1b52eb8c61e58e
```
Unhandled exception:
FormatException: Illegal scheme character (at character 5)
dart_:
    ^

#0      _Uri._fail (dart:core/uri.dart:1597)
#1      _Uri._makeScheme (dart:core/uri.dart:2059)
#2      new _Uri.notSimple (dart:core/uri.dart:1437)
#3      Uri.parse (dart:core/uri.dart:1012)
#4      _Uri.resolve (dart:core/uri.dart:2473)
#5      SourceLibraryBuilder.resolve (package:front_end/src/fasta/source/source_library_builder.dart:124:35)
#6      SourceLibraryBuilder.addImport (package:front_end/src/fasta/source/source_library_builder.dart:144:21)
#7      OutlineBuilder.endImport (package:front_end/src/fasta/source/outline_builder.dart:152:15)
#8      Parser.parseImport (package:front_end/src/fasta/parser/parser.dart:410:14)
#9      Parser._parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:366:14)
#10     Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:344:13)
#11     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#12     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:134:37)
<asynchronous suspension>
#13     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:137:13)
<asynchronous suspension>
#14     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:230:20)
<asynchronous suspension>
#15     CompileTask.buildOutline (package:front_end/src/fasta/fasta.dart:149:38)
<asynchronous suspension>
#16     CompileTask.compile (package:front_end/src/fasta/fasta.dart:161:39)
<asynchronous suspension>
#17     compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#18     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#23     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#24     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#25     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#26     main (file:///home/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

**Comment by peter-ahe-google** [comment]
Repro:

```
import "dart_:core";

main() {}
```

**Comment by peter-ahe-google** [comment]
This is probably a dup of #29977.
