### ISSUE TITLE
Fasta crash: Failed assertion in continuation

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29983]
@peter-ahe-google
ID: 6598a8cf89f347fb21fc97d9267db1dae77dd057
```
Unhandled exception:
'package:kernel/transformations/continuation.dart': Failed assertion: line 209 pos 12: 'node.expression == null || node.expression is NullLiteral': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:35)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:31)
#2      SyncStarFunctionRewriter.visitReturnStatement (package:kernel/transformations/continuation.dart:209:12)
#3      ReturnStatement.accept (package:kernel/ast.dart:3516:35)
#4      transformList (package:kernel/ast.dart:4474:27)
#5      Block.transformChildren (package:kernel/ast.dart:3144:5)
#6      Transformer.defaultTreeNode (package:kernel/visitor.dart:331:10)
#7      TreeVisitor.defaultStatement (package:kernel/visitor.dart:176:41)
#8      TreeVisitor.visitBlock (package:kernel/visitor.dart:180:31)
#9      Block.accept (package:kernel/ast.dart:3136:35)
#10     SyncStarFunctionRewriter.buildClosureBody (package:kernel/transformations/continuation.dart:180:30)
#11     SyncStarFunctionRewriter.rewrite (package:kernel/transformations/continuation.dart:148:39)
#12     RecursiveContinuationRewriter.visitFunctionNode (package:kernel/transformations/continuation.dart:58:59)
#13     FunctionNode.accept (package:kernel/ast.dart:1470:30)
#14     Procedure.transformChildren (package:kernel/ast.dart:1195:27)
#15     Transformer.defaultTreeNode (package:kernel/visitor.dart:331:10)
#16     TreeVisitor.defaultMember (package:kernel/visitor.dart:203:35)
#17     TreeVisitor.visitProcedure (package:kernel/visitor.dart:205:39)
#18     RecursiveContinuationRewriter.visitProcedure (package:kernel/transformations/continuation.dart:48:57)
#19     Procedure.accept (package:kernel/ast.dart:1182:32)
#20     transformList (package:kernel/ast.dart:4474:27)
#21     Library.transformChildren (package:kernel/ast.dart:367:5)
#22     Transformer.defaultTreeNode (package:kernel/visitor.dart:331:10)
#23     TreeVisitor.visitLibrary (package:kernel/visitor.dart:222:35)
#24     Library.accept (package:kernel/ast.dart:353:30)
#25     RecursiveContinuationRewriter.rewriteLibrary (package:kernel/transformations/continuation.dart:44:17)
#26     transformLibraries (package:kernel/transformations/continuation.dart:19:14)
#27     VmFastaTarget.performModularTransformationsOnLibraries (package:kernel/target/vm_fasta.dart:38:5)
#28     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:678:19)
#29     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:286:7)
<asynchronous suspension>
#30     CompileTask.compile (package:front_end/src/fasta/fasta.dart:164:38)
<asynchronous suspension>
#31     compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#32     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#33     _rootRun (dart:async/zone.dart:1120)
#34     _CustomZone.run (dart:async/zone.dart:1001)
#35     runZoned (dart:async/zone.dart:1467)
#36     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#37     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#38     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#39     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#40     main (file:///home/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

**Comment by peter-ahe-google** [comment]
Repro:

```
f() sync* {
  return missing;
}

main() {}
```

**Comment by kmillikin** [comment]
The continuation transformer asserts that `return` in a `sync*` function either does not have a subexpression or else it is `null`.  If we simply transform with the assert, the transformed code does not signal a compile-time errror.

**Comment by kmillikin** [comment]
The input does have a compile-time error:

```dart
  static method f() → dynamic sync* {
    return throw new core::NoSuchMethodError::_withType(null,
                                                        #missing,
                                                        33,
                                                        <dynamic>[].toList(growable: false),
                                                        <dynamic, dynamic>{},
                                                        null);
  }
```
