### ISSUE TITLE
Fasta crash in Source.getTextLine

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29982]
@peter-ahe-google
ID: 5138f6a104342f9a03eceadfbe99a5e36398da4b
```
Unhandled exception:
RangeError: Value not in range: 673
#0      _StringBase.substring (dart:core-patch/string_patch.dart:360)
#1      Source.getTextLine (package:kernel/ast.dart:4529:25)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:93:9)
#3      format (package:front_end/src/fasta/messages.dart:65:25)
#4      formatUnexpected (package:front_end/src/fasta/errors.dart:72:10)
#5      InputError.format (package:front_end/src/fasta/errors.dart:93:22)
#6      KernelTarget.handleInputError (package:front_end/src/fasta/kernel/kernel_target.dart:218:30)
#7      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:251:7)
<asynchronous suspension>
#8      CompileTask.buildOutline (package:front_end/src/fasta/fasta.dart:149:38)
<asynchronous suspension>
#9      CompileTask.compile (package:front_end/src/fasta/fasta.dart:161:39)
<asynchronous suspension>
#10     compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#11     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     runZoned (dart:async/zone.dart:1467)
#15     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#16     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#17     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#18     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#19     main (file:///home/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

**Comment by peter-ahe-google** [comment]
Repro

```
main() {
  var eh = {"éh": "éh"};
  print('${eh[éh']}');
}
```

**Comment by bwilkerson** [comment]
This issue was impacted by https://dart-review.googlesource.com/c/sdk/+/15680.

**Comment by jensjoha** [comment]
I cannot reproduce a crash, but I do get errors etc. Can this issue be closed?
