### ISSUE TITLE
Analysing firebase_database plugin for flutter

### ISSUE THREAD

**Issue by arashbi** [dart-lang/sdk#29991]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-171.4694.23`
- `1.18.1`
- `IC-171.4694.23, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.11.6 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/36/kyqvb6b906129sfnj7px34fm0000gn/T/report.txt

```
Dart analysis server, SDK version 1.18.1, server version 1.15.0, error: Found element with null library: StackTrace
null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:990)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:46)
#2      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:282)
#3      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2253)
#4      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:6233)
#5      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2253)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#7      CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2175)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6856)
#9      PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5283)
#10     UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:3278)
#11     ResolverVisitor.safelyVisitComment (package:analyzer/src/generated/resolver.dart:5966)
#12     ResolverVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:6829)
#13     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:8130)

**Comment by devoncarew** [comment]
@arashbi, the sdk version above - `1.18.1` - is really pretty old. I'd recommend upgrading the sdk used.

If you don't have the Flutter plugin for IntelliJ, I would install that, and point it towards your flutter sdk location on disk. That will configure IntelliJ to use the version of the dart sdk contained in the flutter sdk.
