### ISSUE TITLE
VM mishandles an identifier followed by the keyword "assert".

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29990]
```dart
void main() {
  null assert(0); // "The method 'assert' was called on null." (!)
}
```
```
Unhandled exception:
NoSuchMethodError: The method 'assert' was called on null.
Receiver: null
Tried calling: assert(0)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      main (file:///usr/local/google/home/ianh/dev/scratch/test.dart:3:8)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

Contrast with:
```dart
void main() {
  null.assert(0); // "identifier expected"
}

void main() {
  null azzert(0); // "semicolon expected"
}

void main() {
  null.azzert(0); // "The method 'azzert' was called on null."
}```

**Comment by rmacnak-google** [comment]
@crelier

**Comment by crelier** [comment]
The declared precedence of the assert keyword in runtime/vm/token.h looks like a typo to me.
CL on its way.
