### ISSUE TITLE
Analyzer crash: NoSuchMethodError: The getter 'beginToken' was called on null.

### ISSUE THREAD

**Issue by jakobr-google** [dart-lang/sdk#30020]
Analyzer kept crashing on me, and it took a while to spot why. Spoiler alert: I did have an error in my code.

Possibly the same as #29664. Stack trace looks the same.

```
dartanalyzer version 1.24.2
```

Here's the very stripped-down version of the code with the error:

```dart
class Wrong<T> {
  T Function(<List<int> foo) bar;
}
```

Did you spot it? Of course you did! It's the tiny extra `<`, and it only seems to happen when the generic `T` is involved. Analyzer really didn't like it:

```
Analyzing analyzer_crash.dart...
Unhandled exception:
NoSuchMethodError: The getter 'beginToken' was called on null.
Receiver: null
Tried calling: beginToken
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      SimpleFormalParameterImpl.beginToken (package:analyzer/src/dart/ast/ast.dart:9275)
#3      AstNodeImpl.offset (package:analyzer/src/dart/ast/ast.dart:956)
#4      _SummarizeAstVisitor.serializeCodeRange (package:analyzer/src/summary/summarize_ast.dart:493)
#5      _SummarizeAstVisitor.serializeParameter (package:analyzer/src/summary/summarize_ast.dart:843)
#6      _SummarizeAstVisitor.visitSimpleFormalParameter (package:analyzer/src/summary/summarize_ast.dart:1446)
#7      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9301)
#8      _SummarizeAstVisitor.serializeGenericFunctionType.<anonymous closure> (package:analyzer/src/summary/summarize_ast.dart:808)
#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#10     ListIterable.toList (dart:_internal/iterable.dart:218)
#11     _SummarizeAstVisitor.serializeGenericFunctionType (package:analyzer/src/summary/summarize_ast.dart:809)
#12     _SummarizeAstVisitor.serializeTypeName (package:analyzer/src/summary/summarize_ast.dart:975)
#13     _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:1022)
#14     _SummarizeAstVisitor.visitFieldDeclaration (package:analyzer/src/summary/summarize_ast.dart:1210)
#15     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399)
#16     _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:472)
#17     _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1076)
#18     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#20     _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:525)
#21     serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22)
#22     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:473)
#23     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#24     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:472)
#25     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:766)
#26     AnalysisDriver.getSourceKind (package:analyzer/src/dart/analysis/driver.dart:650)
<asynchronous suspension>
#27     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:256)
<asynchronous suspension>
#28     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:166)
<asynchronous suspension>
#29     Driver.start (package:analyzer_cli/src/driver.dart:145)
<asynchronous suspension>
#30     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#31     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2955063004/
