### ISSUE TITLE
_asyncStackTraceHelper expects Function gets int in Flutter Gallery app in Kernel mode

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30058]
Running flutter gallery app in kernel mode with causal_async_stacks enabled results in the following app exception thrown:

```
06-30 12:08:23.688 15079 15097 I flutter : ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
06-30 12:08:23.710 15079 15097 I flutter : The following assertion was thrown building Title("Flutter Gallery"; color: MaterialColor(primary
06-30 12:08:23.710 15079 15097 I flutter : value: Color(0xff9e9e9e)); dirty):
06-30 12:08:23.710 15079 15097 I flutter : type 'int' is not a subtype of type 'Function' of 'async_op' where
06-30 12:08:23.710 15079 15097 I flutter :   int is from dart:core
06-30 12:08:23.710 15079 15097 I flutter :   Function is from dart:core
06-30 12:08:23.717 15079 15097 I flutter : 
06-30 12:08:23.717 15079 15097 I flutter : Either the assertion indicates an error in the framework itself, or we should provide substantially
06-30 12:08:23.717 15079 15097 I flutter : more information in this error message to help you determine and fix the underlying cause.
06-30 12:08:23.717 15079 15097 I flutter : In either case, please report this assertion by filing a bug on GitHub:
06-30 12:08:23.718 15079 15097 I flutter :   https://github.com/flutter/flutter/issues/new
06-30 12:08:23.718 15079 15097 I flutter : 
06-30 12:08:23.718 15079 15097 I flutter : When the exception was thrown, this was the stack:
06-30 12:08:23.800 15079 15097 I flutter : #0      _asyncStackTraceHelper (dart:async)
06-30 12:08:23.800 15079 15097 I flutter : #1      SystemChrome.setApplicationSwitcherDescription (package:flutter/src/services/system_chrome.dart)
06-30 12:08:23.800 15079 15097 I flutter : #2      Title.build (package:flutter/src/widgets/title.dart:31:18)
06-30 12:08:23.800 15079 15097 I flutter : #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3446:28)
06-30 12:08:23.800 15079 15097 I flutter : #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3391:15)
06-30 12:08:23.800 15079 15097 I flutter : #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.801 15079 15097 I flutter : #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.801 15079 15097 I flutter : #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.801 15079 15097 I flutter : #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.801 15079 15097 I flutter : #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.801 15079 15097 I flutter : #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.801 15079 15097 I flutter : #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.801 15079 15097 I flutter : #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.801 15079 15097 I flutter : #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.801 15079 15097 I flutter : #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.801 15079 15097 I flutter : #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.802 15079 15097 I flutter : #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.802 15079 15097 I flutter : #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.802 15079 15097 I flutter : #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.802 15079 15097 I flutter : #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.802 15079 15097 I flutter : #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.802 15079 15097 I flutter : #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.802 15079 15097 I flutter : #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.802 15079 15097 I flutter : #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.802 15079 15097 I flutter : #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.802 15079 15097 I flutter : #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.802 15079 15097 I flutter : #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.803 15079 15097 I flutter : #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.803 15079 15097 I flutter : #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333:14)
06-30 12:08:23.803 15079 15097 I flutter : #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.803 15079 15097 I flutter : #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.803 15079 15097 I flutter : #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.803 15079 15097 I flutter : #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.803 15079 15097 I flutter : #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.803 15079 15097 I flutter : #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.803 15079 15097 I flutter : #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.803 15079 15097 I flutter : #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.803 15079 15097 I flutter : #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.803 15079 15097 I flutter : #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.804 15079 15097 I flutter : #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.804 15079 15097 I flutter : #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.804 15079 15097 I flutter : #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.804 15079 15097 I flutter : #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.804 15079 15097 I flutter : #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.804 15079 15097 I flutter : #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.804 15079 15097 I flutter : #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.804 15079 15097 I flutter : #46     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart)
06-30 12:08:23.804 15079 15097 I flutter : #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.805 15079 15097 I flutter : #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.805 15079 15097 I flutter : #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.805 15079 15097 I flutter : #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.805 15079 15097 I flutter : #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.805 15079 15097 I flutter : #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.805 15079 15097 I flutter : #53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.805 15079 15097 I flutter : #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.805 15079 15097 I flutter : #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.805 15079 15097 I flutter : #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.805 15079 15097 I flutter : #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.805 15079 15097 I flutter : #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.806 15079 15097 I flutter : #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.806 15079 15097 I flutter : #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.806 15079 15097 I flutter : #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.806 15079 15097 I flutter : #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.806 15079 15097 I flutter : #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.806 15079 15097 I flutter : #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.806 15079 15097 I flutter : #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.806 15079 15097 I flutter : #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.806 15079 15097 I flutter : #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.806 15079 15097 I flutter : #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.806 15079 15097 I flutter : #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.807 15079 15097 I flutter : #70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.807 15079 15097 I flutter : #71     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart)
06-30 12:08:23.807 15079 15097 I flutter : #72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.807 15079 15097 I flutter : #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.807 15079 15097 I flutter : #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.807 15079 15097 I flutter : #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.807 15079 15097 I flutter : #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.807 15079 15097 I flutter : #77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.807 15079 15097 I flutter : #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.807 15079 15097 I flutter : #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.808 15079 15097 I flutter : #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.808 15079 15097 I flutter : #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.808 15079 15097 I flutter : #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.808 15079 15097 I flutter : #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.808 15079 15097 I flutter : #84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart)
06-30 12:08:23.808 15079 15097 I flutter : #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.808 15079 15097 I flutter : #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.808 15079 15097 I flutter : #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.808 15079 15097 I flutter : #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
06-30 12:08:23.808 15079 15097 I flutter : #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
06-30 12:08:23.809 15079 15097 I flutter : #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
06-30 12:08:23.809 15079 15097 I flutter : #91     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart)
06-30 12:08:23.809 15079 15097 I flutter : #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
06-30 12:08:23.809 15079 15097 I flutter : #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
06-30 12:08:23.809 15079 15097 I flutter : #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
06-30 12:08:23.809 15079 15097 I flutter : #95     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:732:16)
06-30 12:08:23.809 15079 15097 I flutter : #96     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:703:5)
06-30 12:08:23.809 15079 15097 I flutter : #97     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:649:17)
06-30 12:08:23.809 15079 15097 I flutter : #98     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2122:19)
06-30 12:08:23.809 15079 15097 I flutter : #99     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:648:13)
06-30 12:08:23.809 15079 15097 I flutter : #100    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:543:7)
06-30 12:08:23.810 15079 15097 I flutter : #101    runApp (package:flutter/src/widgets/binding.dart:581:7)
06-30 12:08:23.810 15079 15097 I flutter : #102    main (file:///usr/local/google/home/aam/p/f/t8/flutter/flutter/examples/flutter_gallery/lib/main.dart:13:3)
06-30 12:08:23.810 15079 15097 I flutter : #103    _startIsolate.<anonymous closure> (dart:isolate:1242:19)
06-30 12:08:23.810 15079 15097 I flutter : #104    _RawReceivePortImpl._handleMessage (dart:isolate:1132:12)
06-30 12:08:23.810 15079 15097 I flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
```

@kmillikin , any ideas?

**Comment by aam** [comment]
@rmacnak-google

**Comment by aam** [comment]
This was fixed https://codereview.chromium.org/2936793003/. That cl was later reverted however, so I created #30178 to track it.
