### ISSUE TITLE
Error when expanding postfix template

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#30050]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA 173.SNAPSHOT`
- `1.25.0-edge.fc32e0e72b572ff42de9651fdd3c5e400b49dd1f`
- `173.SNAPSHOT, JRE 1.8.0_112-b15x64 Oracle Corporation, OS Windows 10(amd64) v10.0 , screens 1920x1200`

# Exception

```
Dart analysis server, SDK version 1.25.0-edge.fc32e0e72b572ff42de9651fdd3c5e400b49dd1f, server version 1.18.1, FATAL error: Failed to handle request: {id: 127, method: edit.getPostfixCompletion, params: {file: C:\dart_projects\DartSample2\bin\empty.dart, offset: 23, key: .nn}, clientRequestTime: 1498749795228}
NoSuchMethodError: The getter 'change' was called on null.
Receiver: null
Tried calling: change
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      EditDomainHandler.getPostfixCompletion (package:analysis_server/src/edit/edit_domain.dart:293)
<asynchronous suspension>
#3      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:366)
#4      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:679)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#6      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:675)
#7      _rootRun (dart:async/zone.dart:1120)
#8      _CustomZone.run (dart:async/zone.dart:1001)
#9      _CustomZone.runGuarded (dart:async/zone.dart:901)
#10     runZoned (dart:async/zone.dart:1465)
#11     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:674)
#12     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#14     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#15     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#16     _rootRunUnary (dart:async/zone.dart:1128)
#17     _CustomZone.runUnary (dart:async/zone.dart:1012)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#24     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#25     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#26     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#28     _rootRunUnary (dart:async/zone.dart:1128)
#29     _CustomZone.runUnary (dart:async/zone.dart:1012)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#36     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#37     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#38     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#39     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#41     _rootRunUnary (dart:async/zone.dart:1128)
#42     _CustomZone.runUnary (dart:async/zone.dart:1012)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#46     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#47     _StreamController._add (dart:async/stream_controller.dart:667)
#48     _StreamController.add (dart:async/stream_controller.dart:613)
#49     _Socket._onData (dart:io-patch/socket_patch.dart:1643)
#50     _rootRunUnary (dart:async/zone.dart:1132)
#51     _CustomZone.runUnary (dart:async/zone.dart:1012)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#55     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#56     _StreamController._add (dart:async/stream_controller.dart:667)
#57     _StreamController.add (dart:async/stream_controller.dart:613)
#58     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
#59     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#60     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#61     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#62     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#63     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

```
1498749794378 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"C:\\dart_proje
1498749794382 <= {"id":"116","result":{"assists":[{"message":"Assign value to new local variable","edits":[{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","fileStamp":0,"edits":[{"offset":23
1498749794382 <= {"id":"117","result":{"assists":[{"message":"Assign value to new local variable","edits":[{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","fileStamp":0,"edits":[{"offset":23
1498749794382 <= {"event":"analysis.highlights","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","regions":[{"type":"TOP_LEVEL_FUNCTION_DECLARATION","offset":0,"length":4},{"type":"K
1498749794382 <= {"event":"analysis.navigation","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","regions":[{"offset":0,"length":4,"targets":[0]}],"targets":[{"kind":"FUNCTION","file
1498749794382 <= {"event":"analysis.overrides","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","overrides":[]}}
1498749794384 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1498749794384 <= {"event":"analysis.implemented","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","classes":[],"members":[]}}
1498749794684 => {"id":"118","method":"edit.getFixes","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","offset":23},"clientRequestTime":1498749794684}
1498749794686 <= {"id":"118","result":{"fixes":[{"error":{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","offset":24,"length":2,"start
1498749795055 => {"id":"119","method":"edit.getFixes","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","offset":24},"clientRequestTime":1498749795055}
1498749795056 <= {"id":"119","result":{"fixes":[{"error":{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","offset":24,"length":2,"start
1498749795056 => {"id":"120","method":"edit.getAssists","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","offset":26,"length":0},"clientRequestTime":1498749795056}
1498749795057 <= {"id":"120","result":{"assists":[{"message":"Assign value to new local variable","edits":[{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","fileStamp":0,"edits":[{"offset":23
1498749795059 => {"id":"121","method":"edit.getAssists","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","offset":26,"length":0},"clientRequestTime":1498749795059}
1498749795060 <= {"id":"121","result":{"assists":[{"message":"Assign value to new local variable","edits":[{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","fileStamp":0,"edits":[{"offset":23
1498749795213 => {"id":"122","method":"edit.isPostfixCompletionApplicable","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","offset":23,"key":".nn"},"clientRequestTime":1498749795213
1498749795214 <= {"id":"122","result":{"value":true}}
1498749795216 => {"id":"123","method":"edit.isPostfixCompletionApplicable","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","offset":23,"key":".nn"},"clientRequestTime":1498749795216
1498749795217 <= {"id":"123","result":{"value":true}}
1498749795218 => {"id":"124","method":"edit.isPostfixCompletionApplicable","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","offset":23,"key":".nn"},"clientRequestTime":1498749795218
1498749795219 <= {"id":"124","result":{"value":true}}
1498749795220 => {"id":"125","method":"edit.isPostfixCompletionApplicable","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","offset":23,"key":".nn"},"clientRequestTime":1498749795220
1498749795220 <= {"id":"125","result":{"value":true}}
1498749795228 => {"id":"126","method":"analysis.updateContent","params":{"files":{"C:\\dart_projects\\DartSample2\\bin\\empty.dart":{"type":"add","content":"main() {\n  if (true)\n  \n}"}}},"clientReq
1498749795228 => {"id":"127","method":"edit.getPostfixCompletion","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","offset":23,"key":".nn"},"clientRequestTime":1498749795228}
1498749795229 <= {"id":"126","result":{}}
1498749795229 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1498749795292 <= {"event":"analysis.errors","params":{"file":"C:\\dart_projects\\DartSample2\\bin\\empty.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"C:\\dart_proje
1498749795307 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 127, method: edit.getPostfixCompletion, params: {file: C:\\dart_projects\\DartSample2\\bin\\
```

**Comment by alexander-doroshko** [comment]
@stevemessick

**Comment by stevemessick** [comment]
Fixed in
https://codereview.chromium.org/2966813002/
