### ISSUE TITLE
Regression on stack traces in DDC

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#30075]
These tests started failing recently:

```
Chrome 59.0.3071 (Mac OS X 10.12.5)  language/stacktrace_rethrow_error_test_withtraceparameter_multi FAILED
	Expected: bb3 actual:     at Object.stacktrace_rethrow_error_test_withtraceparameter_multi.gg3 (gen/codegen_output/language/stacktrace_rethrow_error_test_withtraceparameter_multi.js:168:22)
	Error: Expected: bb3 actual:     at Object.stacktrace_rethrow_error_test_withtraceparameter_multi.gg3 (gen/codegen_output/language/stacktrace_rethrow_error_test_withtraceparameter_multi.js:168:22)
	    at finish (test/browser/language_tests.js:809:59)
	    at Context.<anonymous> (test/browser/language_tests.js:833:11)
Chrome 59.0.3071 (Mac OS X 10.12.5)  language/stacktrace_rethrow_nonerror_test FAILED
	Expected: bb3 actual:     at Object.stacktrace_rethrow_nonerror_test.gg3 (gen/codegen_output/language/stacktrace_rethrow_nonerror_test.js:164:22)
	Error: Expected: bb3 actual:     at Object.stacktrace_rethrow_nonerror_test.gg3 (gen/codegen_output/language/stacktrace_rethrow_nonerror_test.js:164:22)
	    at finish (test/browser/language_tests.js:809:59)
```

**Comment by jmesserly** [comment]
These tests are passing for me on my machine ... I'm going to try `gclient sync -f` and rebuilding the SDK & see if that causes a failure.

**Comment by jmesserly** [comment]
Might be flaky? I'm seeing this every test run now:
```
Chrome 59.0.3071 (Mac OS X 10.12.5)  language/stacktrace_rethrow_error_test_withtraceparameter_multi FAILED
	Error: test marked as 'fail' but passed
	    at finish (test/browser/language_tests.js:801:23)
	    at Context.<anonymous> (test/browser/language_tests.js:848:13)
Chrome 59.0.3071 (Mac OS X 10.12.5)  language/stacktrace_rethrow_nonerror_test FAILED
	Error: test marked as 'fail' but passed
	    at finish (test/browser/language_tests.js:801:23)
	    at Context.<anonymous> (test/browser/language_tests.js:848:13)
```

**Comment by vsmenon** [comment]
I'm seeing that too - locally and travis.  Reverted the status failures:

https://codereview.chromium.org/2971193002/

**Comment by jmesserly** [comment]
I think we can close this out
