### ISSUE TITLE
Error while typing a function-typed field in a class.

### ISSUE THREAD

**Issue by camsteffen** [dart-lang/sdk#30089]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.70`
- `1.24.2`
- `IU-171.4694.70, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.5 unknown, screens 1920x1080, 1440x900, 1920x1080  Retina`

# Exception

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Failed to handle completion domain request: {id: 11870, method: completion.getSuggestions, params: {file: /Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart, offset: 1964}, clientRequestTime: 1499348616871}
NoSuchMethodError: The getter 'end' was called on null.
Receiver: null
Tried calling: end
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      CompletionTarget._isCandidateToken (package:analysis_server/src/provisional/completion/dart/completion_target.dart:410)
#3      new CompletionTarget.forOffset (package:analysis_server/src/provisional/completion/dart/completion_target.dart:201)
#4      DartCompletionRequestImpl._updateTargets (package:analysis_server/src/services/completion/dart/completion_manager.dart:209)
#5      new DartCompletionRequestImpl._ (package:analysis_server/src/services/completion/dart/completion_manager.dart:154)
#6      DartCompletionRequestImpl.from (package:analysis_server/src/services/completion/dart/completion_manager.dart:254)
<asynchronous suspension>
#7      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:54)
<asynchronous suspension>
#8      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:101)
<asynchronous suspension>
#9      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:210)
<asynchronous suspension>
#10     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:137)
#11     _rootRun (dart:async/zone.dart:1120)
#12     _CustomZone.run (dart:async/zone.dart:1001)
#13     _CustomZone.runGuarded (dart:async/zone.dart:901)
#14     runZoned (dart:async/zone.dart:1465)
#15     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:134)
#16     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:975)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#18     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:971)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     _CustomZone.runGuarded (dart:async/zone.dart:901)
#22     runZoned (dart:async/zone.dart:1465)
#23     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:970)
#24     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:168)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#26     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:159)
#27     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#28     _rootRunUnary (dart:async/zone.dart:1128)
#29     _CustomZone.runUnary (dart:async/zone.dart:1012)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#36     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#37     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#38     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#40     _rootRunUnary (dart:async/zone.dart:1128)
#41     _CustomZone.runUnary (dart:async/zone.dart:1012)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#47     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#48     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#49     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#50     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#51     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#52     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#53     _rootRunUnary (dart:async/zone.dart:1128)
#54     _CustomZone.runUnary (dart:async/zone.dart:1012)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#58     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#59     _StreamController._add (dart:async/stream_controller.dart:667)
#60     _StreamController.add (dart:async/stream_controller.dart:613)
#61     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#62     _rootRunUnary (dart:async/zone.dart:1132)
#63     _CustomZone.runUnary (dart:async/zone.dart:1012)
#64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#67     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#68     _StreamController._add (dart:async/stream_controller.dart:667)
#69     _StreamController.add (dart:async/stream_controller.dart:613)
#70     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#71     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#72     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#73     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#74     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#75     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

```
1499348616638 <= {"id":"11865","result":{}}
1499348616639 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1499348616671 <= {"id":"11866","result":{"id":"1620"}}
1499348616671 <= {"event":"analysis.errors","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","errors":[{"sever
1499348616672 <= {"event":"analysis.highlights","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","regions":[{"
1499348616673 <= {"event":"analysis.navigation","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","regions":[{"
1499348616674 <= {"event":"analysis.overrides","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","overrides":[]
1499348616728 <= {"event":"analysis.errors","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/mss_threat_ui.dart","errors":[]}}
1499348616745 <= {"event":"completion.results","params":{"id":"1620","replacementOffset":1961,"replacementLength":1,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"DivElement","selectio
1499348616754 <= {"event":"analysis.errors","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc-view-components.dart","errors":[]}}
1499348616754 => {"id":"11867","method":"analysis.updateContent","params":{"files":{"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.
1499348616754 => {"id":"11868","method":"completion.getSuggestions","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search
1499348616787 <= {"event":"analysis.errors","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/footer/tc-false-positive.dart","errors":[{"severity":"INFO","type":
1499348616787 <= {"id":"11867","result":{}}
1499348616821 <= {"id":"11868","result":{"id":"1621"}}
1499348616821 <= {"event":"analysis.errors","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","errors":[{"sever
1499348616822 <= {"event":"analysis.highlights","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","regions":[{"
1499348616823 <= {"event":"analysis.navigation","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","regions":[{"
1499348616825 <= {"event":"analysis.overrides","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","overrides":[]
1499348616871 => {"id":"11869","method":"analysis.updateContent","params":{"files":{"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.
1499348616871 => {"id":"11870","method":"completion.getSuggestions","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search
1499348616891 <= {"event":"analysis.errors","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/footer/tc-footer-components.dart","errors":[]}}
1499348616898 <= {"event":"completion.results","params":{"id":"1621","replacementOffset":1961,"replacementLength":2,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"DivElement","selectio
1499348616898 <= {"id":"11869","result":{}}
1499348616956 <= {"id":"11870","result":{"id":"1622"}}
1499348616956 <= {"event":"analysis.errors","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","errors":[]}}
1499348616957 <= {"event":"analysis.highlights","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","regions":[{"
1499348616958 <= {"event":"analysis.navigation","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","regions":[{"
1499348616959 <= {"event":"analysis.overrides","params":{"file":"/Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart","overrides":[]
1499348616971 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {id: 11870, method: completion.getSuggestions, params: {file: /Users/csteffen/
```

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Failed to handle completion domain request: {id: 11870, method: completion.getSuggestions, params: {file: /Users/csteffen/src/threat-console/threat-console-ui/lib/src/tc_detail/research_tools/alert_search/tc_alert_search.dart, offset: 1964}, clientRequestTime: 1499348616871}
NoSuchMethodError: The getter 'end' was called on null.
Receiver: null
Tried calling: end
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      CompletionTarget._isCandidateToken (package:analysis_server/src/provisional/completion/dart/completion_target.dart:410)
#3      new CompletionTarget.forOffset (package:analysis_server/src/provisional/completion/dart/completion_target.dart:201)
#4      DartCompletionRequestImpl._updateTargets (package:analysis_server/src/services/completion/dart/completion_manager.dart:209)
#5      new DartCompletionRequestImpl._ (package:analysis_server/src/services/completion/dart/completion_manager.dart:154)
#6      DartCompletionRequestImpl.from (package:analysis_server/src/services/completion/dart/completion_manager.dart:254)
<asynchronous suspension>
#7      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:54)
<asynchronous suspension>

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2974533002/
