### ISSUE TITLE
Analyzer Crash in IntelliJ

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#30097]
While rolling Flutter's engine I encountered an analyzer crash in IntelliJ (see report below).

See also: https://github.com/flutter/flutter/issues/11100

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-171.4694.70`
- `1.25.0-dev.4.0`
- `IC-171.4694.70, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.5 unknown, screens 1920x1200`

# Exception

Please append the contents of:
file:///private/var/folders/t2/r2h8ytq53_x45hn80bhpb0ww0044f6/T/report2.txt

```
Dart analysis server, SDK version 1.25.0-dev.4.0, server version 1.18.1, error: Analysis failed: /Users/goderbauer/dev/flutter/packages/flutter/lib/src/animation/animations.dart context: exception_20170706_165647_825
NoSuchMethodError: The getter 'superclass' was called on null.
Receiver: null
Tried calling: superclass
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _OverrideChecker._extendsErrorLocation (package:analyzer/src/task/strong/checker.dart:1599)
#3      _OverrideChecker._checkInterfacesOverrides (package:analyzer/src/task/strong/checker.dart:1439)
#4      _OverrideChecker._checkInterfacesOverrides (package:analyzer/src/task/strong/checker.dart:1442)
#5      _OverrideChecker._checkAllInterfaceOverrides (package:analyzer/src/task/strong/checker.dart:1286)
#6      _OverrideChecker.check (package:analyzer/src/task/strong/checker.dart:1251)
#7      CodeChecker.visitClassDeclaration (package:analyzer/src/task/strong/checker.dart:295)
#8      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1906)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#10     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2502)
#11     CodeChecker.visitCompilationUnit (package:analyzer/src/task/strong/checker.dart:314)
#12     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:277)
```

$ cat /private/var/folders/t2/r2h8ytq53_x45hn80bhpb0ww0044f6/T/report2.txt
```
Dart analysis server, SDK version 1.25.0-dev.4.0, server version 1.18.1, error: Analysis failed: /Users/goderbauer/dev/flutter/packages/flutter/lib/src/animation/animations.dart context: exception_20170706_165647_825
NoSuchMethodError: The getter 'superclass' was called on null.
Receiver: null
Tried calling: superclass
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _OverrideChecker._extendsErrorLocation (package:analyzer/src/task/strong/checker.dart:1599)
#3      _OverrideChecker._checkInterfacesOverrides (package:analyzer/src/task/strong/checker.dart:1439)
#4      _OverrideChecker._checkInterfacesOverrides (package:analyzer/src/task/strong/checker.dart:1442)
#5      _OverrideChecker._checkAllInterfaceOverrides (package:analyzer/src/task/strong/checker.dart:1286)
#6      _OverrideChecker.check (package:analyzer/src/task/strong/checker.dart:1251)
#7      CodeChecker.visitClassDeclaration (package:analyzer/src/task/strong/checker.dart:295)
#8      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1906)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#10     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2502)
#11     CodeChecker.visitCompilationUnit (package:analyzer/src/task/strong/checker.dart:314)
#12     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:277)
#13     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:103)
#14     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#15     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#17     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
#18     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:64)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#20     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:63)
#21     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1055)
#22     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#23     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1043)
#24     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:900)
<asynchronous suspension>
#25     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1595)
<asynchronous suspension>
#26     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1538)
#27     new AnalysisServer (package:analysis_server/src/analysis_server.dart:386)
#28     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#29     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#30     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:446)
#31     _rootRun (dart:async/zone.dart:1120)
#32     _CustomZone.run (dart:async/zone.dart:1001)
#33     runZoned (dart:async/zone.dart:1467)
#34     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:485)
#35     Driver.start (package:analysis_server/src/server/driver.dart:445)
#36     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#37     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1499385405804 <= {"id":"0","result":{"version":"1.18.1"}}
1499385405807 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1499385405412}
1499385405807 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1499385405807 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["/Users/goderbauer/dev/flutter/packages/flutter"],"excluded":["/Users/goderbauer/dev/flutter/packages/flutter/.ide
1499385405808 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["/Users/goderbauer/dev/flutter/packages/flutter/lib/painting.dart"]},"clientRequestTime":1499385405459}
1499385405808 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["/Users/goderbauer/dev/flutter/packages/flutter/lib/painting.dart"],"OVERRIDES":["/Users/goderb
1499385405813 <= {"id":"1"}
1499385405818 <= {"id":"2"}
1499385405851 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1499385405859 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1499385406515 <= {"id":"3"}
1499385406518 <= {"id":"4"}
1499385406527 <= {"id":"5"}
1499385406536 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1499385407134 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/painting.dart","errors":[]}}
1499385407180 <= {"event":"analysis.highlights","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/painting.dart","regions":[{"type":"DIRECTIVE","offset":166,"length":510},{"type":"B
1499385407197 <= {"event":"analysis.navigation","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/painting.dart","regions":[{"offset":667,"length":8,"targets":[0]},{"offset":685,"le
1499385407199 <= {"event":"analysis.overrides","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/painting.dart","overrides":[]}}
1499385407229 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/animation.dart","errors":[]}}
1499385407325 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/cupertino.dart","errors":[]}}
1499385407328 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/foundation.dart","errors":[]}}
1499385407328 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/gestures.dart","errors":[]}}
1499385407392 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/material.dart","errors":[]}}
1499385407396 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/physics.dart","errors":[]}}
1499385407397 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/rendering.dart","errors":[]}}
1499385407398 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/scheduler.dart","errors":[]}}
1499385407398 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/services.dart","errors":[]}}
1499385407408 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/src/animation/animation.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR"
1499385407412 <= {"event":"analysis.errors","params":{"file":"/Users/goderbauer/dev/flutter/packages/flutter/lib/src/animation/animation_controller.dart","errors":[]}}
1499385407856 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/goderbauer/dev/flutter/packages/flutter/lib/src/animation/animations.dart context: exception_20170
```

**Comment by devoncarew** [comment]
Note, that from here: https://github.com/flutter/flutter/issues/11100, the number of errors (and the types) may indicate that he sdk is somehow badly formed.

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
