### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30091]
One of the dart2js tests appears to be flaky. The most recent occurrence is recorded in this log file: `https://build.chromium.org/p/client.dart/builders/dart2js-linux-chromeff-1-4-be/builds/5522/steps/dart2js-chrome-co19-fast-startup%20tests/logs/stdio`. In case the log file is inaccessible, I've copied the relevant portion below.

```
!@@@STEP_FAILURE@@@

FAILED: dart2js-chrome release_x64 co19/LayoutTests/fast/canvas/webgl/WebGLContextEvent_t01
Expected: Pass 
Actual: RuntimeError
CommandOutput[dart2js]:

stdout:
Compiled 3,755,754 characters Dart to 396,002 characters JavaScript in 4.68 seconds
Dart file (/b/build/slave/dart2js-linux-chromeff-1-4-be/build/sdk/tests/co19/src/LayoutTests/fast/canvas/webgl/WebGLContextEvent_t01.dart) compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js

CommandOutput[chrome]:

stdout:
events:
  [
        {
              type: debug
              value: test_controller.js started
              timestamp: 0
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = true, isStatusUpdate = true, isDone = false)
              timestamp: 0.001
        },
        {
              type: print
              value: dart-calling-main
              timestamp: 0.06
        },
        {
              type: print
              value: unittest-suite-wait-for-done
              timestamp: 0.065
        },
        {
              type: sync_exception
              value: Exception: Expect.fail('Unable to fetch WebGL rendering context for Canvas')
                    Stack: Expect.fail('Unable to fetch WebGL rendering context for Canvas')
                        at Object.wrapException (http://127.0.0.1:59127/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js:710:17)
                        at Object._fail (http://127.0.0.1:59127/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js:3467:15)
                        at Object.create3DContext (http://127.0.0.1:59127/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js:3529:11)
                        at main_createNewCanvas.call$0 (http://127.0.0.1:59127/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js:8995:19)
                        at main_runTest1.call$0 (http://127.0.0.1:59127/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js:9053:28)
                        at StaticClosure.main (http://127.0.0.1:59127/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js:3424:64)
                        at _IsolateContext.eval$1 (http://127.0.0.1:59127/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js:4110:23)
                        at Object.startRootIsolate (http://127.0.0.1:59127/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js:324:21)
                        at http://127.0.0.1:59127/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js:9944:11
                        at dartMainRunner (http://127.0.0.1:59127/root_dart/tools/testing/dart/test_controller.js:311:5)
              timestamp: 0.103
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = false, isStatusUpdate = false, isDone = true)
              timestamp: 0.104
        },
        {
              type: dom
              value: <head>
                      <meta http-equiv="X-UA-Compatible" content="IE=edge">
                      <meta name="dart.unittest" content="full-stack-traces">
                      <title> Test /b/build/slave/dart2js-linux-chromeff-1-4-be/build/sdk/tests/co19/src/LayoutTests/fast/canvas/webgl/WebGLContextEvent_t01.dart </title>
                      <style>
                         .unittest-table { font-family:monospace; border:1px; }
                         .unittest-pass { background: #6b3;}
                         .unittest-fail { background: #d55;}
                         .unittest-error { background: #a11;}
                      </style>
                    </head>
                    <body>
                      <h1> Running /b/build/slave/dart2js-linux-chromeff-1-4-be/build/sdk/tests/co19/src/LayoutTests/fast/canvas/webgl/WebGLContextEvent_t01.dart </h1>
                      <script type="text/javascript" src="/root_dart/tools/testing/dart/test_controller.js">
                      </script>
                      <script type="text/javascript" src="/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js" onerror="scriptTagOnErrorCallback(null)" defer="">
                      </script>
                      <script type="text/javascript" src="/root_dart/pkg/browser/lib/dart.js"></script>
                    
                    </body>
              timestamp: 0.104
        },
  ]
  



stderr:


BrowserOutput while running the test (* EXPERIMENTAL *):
BrowserOutput.stdout:
  
BrowserOutput.stderr:
  



To retest, run:  /b/build/slave/dart2js-linux-chromeff-1-4-be/build/sdk/tools/sdks/linux/dart-sdk/bin/dart /b/build/slave/dart2js-linux-chromeff-1-4-be/build/sdk/tools/testing/dart/http_server.dart -p 59127 -c 35820 --build-directory=/b/build/slave/dart2js-linux-chromeff-1-4-be/build/sdk/out/ReleaseX64/ --runtime=chrome --packages=/b/build/slave/dart2js-linux-chromeff-1-4-be/build/sdk/.packages

Command[dart2js]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --fast-startup --packages=/b/build/slave/dart2js-linux-chromeff-1-4-be/build/sdk/.packages --out=/b/build/slave/dart2js-linux-chromeff-1-4-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.js /b/build/slave/dart2js-linux-chromeff-1-4-be/build/sdk/tests/co19/src/LayoutTests/fast/canvas/webgl/WebGLContextEvent_t01.dart
Took 0:00:04.685122

Command[chrome]: /b/build/slave/dart2js-linux-chromeff-1-4-be/build/sdk/tools/sdks/linux/dart-sdk/bin/dart tools/testing/dart/launch_browser.dart chrome http://127.0.0.1:59127/root_build/generated_tests/dart2js-chrome-sdk/tests_co19_src_LayoutTests_fast_canvas_webgl_WebGLContextEvent_t01/test.html?crossOriginPort=35820
Took 0:00:00.166104

Short reproduction command (experimental):
    python tools/test.py -m release -c dart2js -r chrome --fast-startup --use-sdk --dart2js-batch --reset-browser-configuration co19/LayoutTests/fast/canvas/webgl/WebGLContextEvent_t01
```

**Comment by athomas** [comment]
Duplicates #29961.
