### ISSUE TITLE
dart2js crashes with noSuchMethod

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30121]
The following code crashes dart2js on trunk.

``` dart
class Mock {
  noSuchMethod(i) {
  }
}
class Foo {
  int call() => 1;
}
class MockFoo extends Mock implements Foo {}

main() {
  var foo = new MockFoo();
  foo();
}
```

```
Internal Error: Assertion failure
class MockFoo extends Mock implements Foo {}
^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Assertion failure
#0      failedAt (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:50:3)
#1      InferrerEngine.runOverAllElements.<anonymous closure> (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:394:38)
#2      _HashFieldBase&_HashBase&_OperatorEqualsAndHashCode&SetMixin.forEach (dart:collection/set.dart:145)
#3      InferrerEngine.runOverAllElements (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:339:29)
#4      TypeGraphInferrer.analyzeMain (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/inferrer/type_graph_inferrer.dart:69:14)
#5      GlobalTypeInferenceTask.runGlobalTypeInference.<anonymous closure> (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/types/types.dart:303:29)
#6      CompilerTask.measure (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#7      GlobalTypeInferenceTask.runGlobalTypeInference (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/types/types.dart:300:5)
#8      Compiler.compileLoadedLibraries.<anonymous closure> (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:603:25)
#9      CompilerTask.measureSubtask (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#10     Compiler.compileLoadedLibraries (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:512:16)
#11     Compiler.runInternal (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:467:5)
<asynchronous suspension>
#12     Compiler.run.<anonymous closure>.<anonymous closure> (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:300:38)
#13     new Future.sync (dart:async/future.dart:222)
#14     Compiler.run.<anonymous closure> (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:300:20)
#15     CompilerTask.measureSubtask (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:176:35)
#16     Compiler.run (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/compiler.dart:297:41)
#17     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///mnt/ssd/floitsch/code/dart/sdk/pkg/compiler/lib/src/apiimpl.dart:265:25)
#18     _RootZone.runUnary (dart:async/zone.dart:1371)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#20     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#21     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#22     _Future._completeWithValue (dart:async/future_impl.dart:478)
#23     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by sigmundch** [comment]
This appears related to one of your changes from last week. Could you take a look?

**Comment by sigmundch** [comment]
(`you` = @johnniwinther :-))

**Comment by johnniwinther** [comment]
The bug is ancient! It also failed three months ago and that part of the inference hasn't been touched for long.

**Comment by sigmundch** [comment]
ha! sorry for the distraction :( -- I thought it was recent.
