### ISSUE TITLE
Simple Angular2 project created with stagehand and added some minimalistic stuff.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#30135]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.70`
- `1.25.0-dev.4.0`
- `IU-171.4694.70, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.5 unknown, screens 1920x1200, 3360x1890  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/report.txt

```
Dart analysis server, SDK version 1.25.0-dev.4.0, server version 1.18.2, error: Captured exception
NoSuchMethodError: Class 'MethodElementImpl' has no instance getter 'localVariables'.
Receiver: Instance of 'MethodElementImpl'
Tried calling: localVariables
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      DartVariableManager.newLocalVariableElement (package:angular_analyzer_plugin/src/resolver.dart:646)
#3      PrepareEventScopeVisitor.visitStatementsBoundAttr (package:angular_analyzer_plugin/src/resolver.dart:726)
#4      StatementsBoundAttribute.accept (package:angular_analyzer_plugin/ast.dart:176)
#5      AngularScopeVisitor.visitElementInScope (package:angular_analyzer_plugin/src/resolver.dart:304)
#6      AngularScopeVisitor.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:270)
#7      PrepareEventScopeVisitor.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:675)
#8      ElementInfo.accept (package:angular_analyzer_plugin/ast.dart:455)
#9      AngularScopeVisitor.visitElementInScope (package:angular_analyzer_plugin/src/resolver.dart:304)
#10     AngularScopeVisitor.visitDocumentInfo (package:angular_analyzer_plugin/src/resolver.dart:249)
#11     DocumentInfo.accept (package:angular_analyzer_plugin/ast.dart:377)
#12     TemplateResolver._resolveScope (package:angular_analyzer_plugin/src/resolver.dart:170)
```

https://github.com/bwu-dart-playground/angular_provider_directive.git

**Comment by MichaelRFairhurst** [comment]
Fixed in the above PR in the angular_analyzer_plugin project.
