### ISSUE TITLE
DDC crash on null-aware access of private field inside initializer

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#30138]
The following crashes during compilation:

```
class Bar {
  String s;
}

class Foo {
  Bar _bar;
  String str;

  Foo(this._bar) : str = _bar?.s;
}

void main() {
  var b = new Bar();
  var f = new Foo(b);
  print(f.str);
}
```

with

```
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ResolutionMapImpl.elementDeclaredByCompilationUnit (package:analyzer/src/dart/ast/resolution_map.dart:45:12)
#3      SourceMapPrintingContext.enterNode (package:dev_compiler/src/compiler/source_map_printer.dart:55:34)
#4      Printer.visit (package:dev_compiler/src/js_ast/printer.dart:212:13)
#5      Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:611:7)
#6      Printer.visitCommaSeparated (package:dev_compiler/src/js_ast/printer.dart:225:7)
#7      Printer.functionOut (package:dev_compiler/src/js_ast/printer.dart:557:7)
#8      Printer.visitFun (package:dev_compiler/src/js_ast/printer.dart:943:5)
#9      Fun.accept (package:dev_compiler/src/js_ast/nodes.dart:1205:42)
#10     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:213:10)
#11     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:611:7)
#12     Printer.visitAssignment (package:dev_compiler/src/js_ast/printer.dart:682:7)
#13     Assignment.accept (package:dev_compiler/src/js_ast/nodes.dart:785:42)
#14     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:213:10)
#15     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:606:7)
#16     Printer.visitAccess (package:dev_compiler/src/js_ast/printer.dart:933:5)
#17     PropertyAccess.accept (package:dev_compiler/src/js_ast/nodes.dart:1280:42)
#18     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:213:10)
#19     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:611:7)
#20     Printer.visitAssignment (package:dev_compiler/src/js_ast/printer.dart:674:5)
#21     Assignment.accept (package:dev_compiler/src/js_ast/nodes.dart:785:42)
#22     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:213:10)
#23     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:611:7)
#24     Printer.visitExpressionStatement (package:dev_compiler/src/js_ast/printer.dart:292:5)
#25     ExpressionStatement.accept (package:dev_compiler/src/js_ast/nodes.dart:352:42)
#26     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:213:10)
#27     List.forEach (dart:core-patch/growable_array.dart:256)
#28     Printer.visitAll (package:dev_compiler/src/js_ast/printer.dart:231:11)
#29     Printer.visitProgram (package:dev_compiler/src/js_ast/printer.dart:238:5)
#30     Program.accept (package:dev_compiler/src/js_ast/nodes.dart:314:42)
#31     JSModuleFile.getCode (package:dev_compiler/src/compiler/compiler.dart:500:10)
#32     JSModuleFile.writeCodeSync (package:dev_compiler/src/compiler/compiler.dart:534:16)
#33     _compile (package:dev_compiler/src/compiler/command.dart:197:12)
#34     compile (package:dev_compiler/src/compiler/command.dart:60:5)
#35     main (file:///Users/vsm/dart/sdk/pkg/dev_compiler/bin/dartdevc.dart:53:16)
<asynchronous suspension>
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by vsmenon** [comment]
@jmesserly - can you take a look?

**Comment by jmesserly** [comment]
sure thing!

psychic debugging:

The right hand side `_bar` should bind to the parameter, *not* to the field (`this` access is not allowed in initializers). It looks like the Dart AST node for `_bar` is not hooked up to the compilation unit (via `enclosingElement`). My guess is that's caused by the temporary variable Dart AST node. I'm surprised we haven't hit this before; I guess because the constructor doesn't have a source mapping node.

I'll have to check if temporary variables are capturing their source location, if not, that's one problem. The other problem is we really shouldn't have to rely on `enclosingElement` to know what source file we're in. I think DDC's current module item ordering scheme can find that easier. Maybe we can clean it up and remove the whole `if (unit == null) {` code block in SourceMapPrintingContext.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2977943002/

**Comment by jmesserly** [comment]
going to reopen this, CL needs fixing for Windows. It looks like there's yet another layer to source map transformation wackiness. Stack trace is:
```
Invalid argument(s): Illegal character in path
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1695)
#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1760)
#2      new _Uri.file (dart:core/uri.dart:1663)
#3      _sourceToUri (package:dev_compiler/src/compiler/compiler.dart:602:18)
#4      placeSourceMap.makeRelative (package:dev_compiler/src/compiler/compiler.dart:565:15)
#5      placeSourceMap (package:dev_compiler/src/compiler/compiler.dart:583:27)
#6      JSModuleFile.getCode (package:dev_compiler/src/compiler/compiler.dart:474:11)
#7      JSModuleFile.writeCodeSync (package:dev_compiler/src/compiler/compiler.dart:502:16)
#8      _compile (package:dev_compiler/src/compiler/command.dart:201:12)
#9      compile (package:dev_compiler/src/compiler/command.dart:60:5)
#10     main (file:///E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:53:16)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
maybe the "Source.fullPath" -> file URI round trip actually does something on Windows

**Comment by jmesserly** [comment]
log is at https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fdart-sdk-windows-be%2F13962%2F%2B%2Frecipes%2Fsteps%2Fgenerate_sdks%2F0%2Fstdout
