### ISSUE TITLE
language/stacktrace_demangle_ctors_test fails with -c precompiler -r dart_precompiled 

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#30153]
Bisecting says it was introduced in f20b32b7936ed0ce071f8991a7030705c8aacf19.

python tools/test.py -mrelease -c precompiler -r dart_precompiled language/stacktrace_demangle_ctors_test

```
Test configuration: precompiler_dart_precompiled_release_x64

FAILED: precompiler-dart_precompiled release_x64 language/stacktrace_demangle_ctors_test
Expected: Pass
Actual: RuntimeError
CommandOutput[precompiler]:
CommandOutput[assemble]:
CommandOutput[remove_assembly]:
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.isFalse(true) fails.
#0      Expect._fail (package:expect/expect.dart:464)
#1      Expect.isFalse (package:expect/expect.dart:142)
#2      main ([...]/tests/language/stacktrace_demangle_ctors_test.dart:35)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
[...]
```

For now I will update the status file.

**Comment by alexmarkov** [comment]
`language/stack_trace/demangle_ctors_test` currently passes on all VM bots, including `vm-aot-linux-release-x64`.
