### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by kristofemond** [dart-lang/sdk#30162]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-171.4424.63`
- `1.23.0`
- `WS-171.4424.63, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2400x1350, 2400x1350`

# Exception

Please append the contents of:
file://C:\Users\kristof.edmond\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.23.0, server version 1.18.0, error: Captured exception
NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4294967296)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AbstractConstExprSerializer._pushInt (package:analyzer/src/summary/summarize_const_expr.dart:290)
#3      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:315)
#4      AbstractConstExprSerializer.serialize (package:analyzer/src/summary/summarize_const_expr.dart:139)
#5      _SummarizeAstVisitor.serializeConstExpr (package:analyzer/src/summary/summarize_ast.dart:557)
#6      _SummarizeAstVisitor.serializeFunctionBody (package:analyzer/src/summary/summarize_ast.dart:755)
#7      _SummarizeAstVisitor.serializeInitializerFunction (package:analyzer/src/summary/summarize_ast.dart:828)
#8      _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:1029)
#9      _SummarizeAstVisitor.visitFieldDeclaration (package:analyzer/src/summary/summarize_ast.dart:1210)
#10     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399)
#11     _SummarizeAstVisitor.serializeClass (package:analyzer/src/sum

**Comment by scheglov** [comment]
Brian, you fixed this in https://github.com/dart-lang/sdk/commit/852edf38d9f77dbea13d990f333e8b85b003b755, as #29687.
