### ISSUE TITLE
co19/LayoutTests/fast/text/font-ligature-letter-spacing_t01 seems flaky dartium-linux-x64-be

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30167]
The test failed with the same error in 5 out of 20 recent builds. Passes fine on my dev workstation.
```

Jul 14 07:24 | 14b76d6b22dff51090228de771888630058684a5 | failure | #2042 | Failed steps failed annotated steps failed dartium_core_unchecked_tests failed failure reason
Jul 14 06:24 | c94f8ef9ecfdb5d7f89263db9fe6d7744ed9317d | success | #2041 | Build successful
Jul 14 05:29 | 18a41eba089cbbad7339ff76713a1acb3a8eb974 | success | #2040 | Build successful
Jul 14 04:35 | 5904409d50fa9b800d015faadbe49cb13e358644 | success | #2039 | Build successful
Jul 14 03:40 | 5b38490530796f7cc19bcb01dc7cdab480ebb579 | success | #2038 | Build successful
Jul 14 02:46 | a459f73facd32a26514e92e691eb8ab8776e3e75 | success | #2037 | Build successful
Jul 14 01:41 | 08f53354733d376b791d9809d18895adf69b9255 | success | #2036 | Build successful
Jul 13 23:19 | 418d11fbd6800f8e3d8e3e3e4239f03ce9372a0e | success | #2035 | Build successful
Jul 13 22:21 | 0d9357431d84ff853e10dcc10ce1be3b4f3a1ead | success | #2034 | Build successful
Jul 13 19:04 | df8bf384eb815cf38450cb50a0f4b62230fba217 | success | #2033 | Build successful
Jul 13 18:07 | 58e5a2393761bfdfe567a9673e4ed598261c9dde | success | #2032 | Build successful
Jul 13 17:10 | 4f7fa8a930cf7572ff42b85e5b00325e35326499 | success | #2031 | Build successful
Jul 13 16:17 | 23faeddbef793a42989b74387b3acbd934b595e3 | failure | #2030 | Failed steps failed annotated steps failed dartium_core_checked_tests failed failure reason
Jul 13 15:22 | be95b916ddf0af2b204286a438e7169e3bb2c67a | success | #2029 | Build successful
Jul 13 14:24 | b5ded27c32bb5fc820b0cbea6a52ee5fc2143dbd | success | #2028 | Build successful
Jul 13 13:30 | d952055a7ea7be9e695070531c81050ca5c352b0 | failure | #2027 | Failed steps failed annotated steps failed dartium_core_checked_tests failed failure reason
Jul 13 12:34 | 1c343d35ac0188e0f7e96f1135e82eb6da7bbe7c | success | #2026 | Build successful
Jul 13 11:21 | c9b42f6a41b10903f85ad7fc4bd1efd87a994357 | failure | #2025 | Failed steps failed annotated steps failed dartium_core_unchecked_tests failed failure reason
Jul 13 09:29 | 125bd4cfed38f8fbbeaf703faf1512cc7964e97c | failure | #2024 | Failed steps failed annotated steps failed dartium_core_checked_tests failed failure reason
Jul 13 06:38 | 579a23d8ef2edafba63a917f0c7fad4787d2ee5f | success | #2023 | Build successf
```

```
FAILED: none-dartium-checked release_x64 co19/LayoutTests/fast/text/font-ligature-letter-spacing_t01
Expected: Pass 
Actual: RuntimeError
CommandOutput[dartium]:

stdout:
events:
  [
        {
              type: debug
              value: test_controller.js started
              timestamp: 0
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = true, isStatusUpdate = true, isDone = false)
              timestamp: 0
        },
        {
              type: print
              value: dart-calling-main
              timestamp: 0.122
        },
        {
              type: print
              value: dart-main-done
              timestamp: 0.324
        },
        {
              type: window_onerror
              value: window.onerror called: 
                    
                    http://127.0.0.1:43287/root_build/generated_tests/none-dartium-checked/tests_co19_src_LayoutTests_fast_text_font-ligature-letter-spacing_t01/test.html?crossOriginPort=34886:1:
                    Uncaught Unhandled exception:
                    Expect.equals(expected: <282.96875>, actual: <138.359375>, 'Ligature not applied due to letter spacing.') fails.
                    #0      _fail (http://127.0.0.1:43287/root_dart/tests/co19/src/Utils/expect.dart:17:5)
                    #1      Expect.equals (http://127.0.0.1:43287/root_dart/tests/co19/src/Utils/expect_common.dart:27:5)
                    #2      testLetterSpaceAndLigature (http://127.0.0.1:43287/root_dart/tests/co19/src/LayoutTests/fast/text/font-ligature-letter-spacing_t01.dart:54:12)
                    #3      new _EventStreamSubscription.<anonymous closure> (dart:html:49065)
                    
                    
              timestamp: 0.34
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = false, isStatusUpdate = false, isDone = true)
              timestamp: 0.34
        },
        {
              type: dom
              value: <head>
                      <meta http-equiv="X-UA-Compatible" content="IE=edge">
                      <meta name="dart.unittest" content="full-stack-traces">
                      <title> Test /b/build/slave/dtmlinuxbe/build/src/dart/tests/co19/src/LayoutTests/fast/text/font-ligature-letter-spacing_t01.dart </title>
                      <style>
                         .unittest-table { font-family:monospace; border:1px; }
                         .unittest-pass { background: #6b3;}
                         .unittest-fail { background: #d55;}
                         .unittest-error { background: #a11;}
                      </style>
                    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
                    <style type="text/css">
                    @font-face {
                      font-family: megalopolis;
                      src: url(/root_dart/tests/co19/src/LayoutTests/third_party/MEgalopolis/MEgalopolisExtra.woff) format("woff");
                    }
                    
                    .dligDiv {
                    -moz-font-feature-settings:"frac" 1, "dlig" 1;
                    -moz-font-feature-settings:"frac=1, dlig=1";
                    -ms-font-feature-settings:"frac" 1, "dlig" 1;
                    -o-font-feature-settings:"frac" 1, "dlig" 1;
                    -webkit-font-feature-settings:"frac" 1, "dlig" 1;
                    font-feature-settings:"frac" 1, "dlig" 1;
                    }
                    
                    .common {
                    font-size: 24px;
                    line-height: 100%;
                    padding: 0px;
                    letter-spacing:20px;
                    font-family: megalopolis;
                    }
                    
                    p { font-family: serif; font-style: italic; }
                    </style>
                    </head>
                    <body>
                      <h1> Running /b/build/slave/dtmlinuxbe/build/src/dart/tests/co19/src/LayoutTests/fast/text/font-ligature-letter-spacing_t01.dart </h1>
                      <script type="text/javascript" src="/root_dart/tools/testing/dart/test_controller.js">
                      </script>
                      <script type="application/dart" src="/root_build/generated_tests/none-dartium-checked/tests_co19_src_LayoutTests_fast_text_font-ligature-letter-spacing_t01/test.dart" onerror="scriptTagOnErrorCallback(null)" defer="">
                      </script>
                      <script type="text/javascript" src="/root_dart/pkg/browser/lib/dart.js"></script>
                    
                    <div class="dligDiv common">
                        <span class="dligSpan">CACACACA</span>
                    </div>
                    
                    <div class="common">
                        <span class="letterSpace">CACACACA</span>
                    </div>
                    </body>
              timestamp: 0.34
        },
  ]
  



stderr:


BrowserOutput while running the test (* EXPERIMENTAL *):
BrowserOutput.stdout:
  
BrowserOutput.stderr:
  



To retest, run:  /b/build/slave/dtmlinuxbe/build/src/dart/tools/sdks/linux/dart-sdk/bin/dart /b/build/slave/dtmlinuxbe/build/src/dart/tools/testing/dart/http_server.dart -p 43287 -c 34886 --build-directory=/b/build/slave/dtmlinuxbe/build/src/out/ReleaseX64/ --runtime=dartium --packages=/b/build/slave/dtmlinuxbe/build/src/dart/.packages

Command[dartium]: /b/build/slave/dtmlinuxbe/build/src/dart/tools/sdks/linux/dart-sdk/bin/dart tools/testing/dart/launch_browser.dart dartium http://127.0.0.1:43287/root_build/generated_tests/none-dartium-checked/tests_co19_src_LayoutTests_fast_text_font-ligature-letter-spacing_t01/test.html?crossOriginPort=34886
Took 0:00:00.415301

Short reproduction command (experimental):
    python tools/test.py -m release -r dartium --checked co19/LayoutTests/fast/text/font-ligature-letter-spacing_t01
```

**Comment by aam** [comment]
dartium is decommissioned.
