### ISSUE TITLE
Error in IntelliJ Console when using Dart Analyzer

### ISSUE THREAD

**Issue by irfantusneem** [dart-lang/sdk#30161]
I have removed the prefix to the location of the file.  Ping me @google.com for the location.

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4073.35`
- `1.22.0-dev.4.0`
- `IU-171.4073.35, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-83-generic unknown, screens 1920x1200`

# Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.22.0-dev.4.0, server version 1.17.0, error: Analysis failed: tools/css_cleaner/check_encapsulation_host.dart
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _SummarizeAstVisitor.serializeParameter (package:analyzer/src/summary/summarize_ast.dart:806)
#3      _SummarizeAstVisitor.visitSimpleFormalParameter (package:analyzer/src/summary/summarize_ast.dart:1374)
#4      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9253)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8023)
#6      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4830)
#7      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:845)
#8      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4826)
#9      GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5752)
#10     RecursiveAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:893)
#11     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5745)
#12     GenericTypeAliasImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5835)
#13     RecursiveAstVisitor.visitGenericTypeAlias (package:analyzer/dart/ast/visitor.dart:899)

**Comment by scheglov** [comment]
The version `1.22.0-dev.4.0` is way too old.
Please update to `1.24.*`.
