### ISSUE TITLE
dart-sdk-windows-be test failure: dartdevc fails with 'Illegal character in path'

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30172]
dart-sdk-windows-be buildbot started failing with https://build.chromium.org/p/client.dart/builders/dart-sdk-windows-be/builds/13962. 

The culprit seems to be https://github.com/dart-lang/sdk/commit/52880e9c4c028fbd992dceac7de4499a2fb8e3be.

```
E:/b/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../build/gn_run_binary.py compiled_action dart.exe --packages=E:/b/build/slave/dart-sdk-windows-be/build/sdk/.packages --snapshot=E:/b/build/slave/dart-sdk-windows-be/build/sdk/out/ReleaseX64/gen/dartdevc.dart.snapshot --snapshot-kind=app-jit E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/bin/dartdevc.dart --dart-sdk E:/b/build/slave/dart-sdk-windows-be/build/sdk/sdk --dart-sdk-summary E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler -o dartdevc.js --unsafe-force-compile E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/bin/dartdevc.dart
Command failed: ./dart.exe --packages=E:/b/build/slave/dart-sdk-windows-be/build/sdk/.packages --snapshot=E:/b/build/slave/dart-sdk-windows-be/build/sdk/out/ReleaseX64/gen/dartdevc.dart.snapshot --snapshot-kind=app-jit E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/bin/dartdevc.dart --dart-sdk E:/b/build/slave/dart-sdk-windows-be/build/sdk/sdk --dart-sdk-summary E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler -o dartdevc.js --unsafe-force-compile E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/bin/dartdevc.dart
output: We're sorry, you've found a bug in our compiler.

You can report this bug at:

    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler

Please include the information below in your report, along with

any other information that may help us track it down. Thanks!

    dartdevc arguments: --dart-sdk E:/b/build/slave/dart-sdk-windows-be/build/sdk/sdk --dart-sdk-summary E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler -o dartdevc.js --unsafe-force-compile E:/b/build/slave/dart-sdk-windows-be/build/sdk/pkg/dev_compiler/bin/dartdevc.dart

    dart --version: 1.25.0-edge.ebd9440b18396124708cdb67bd82c1985e8a427a (Fri Jul 14 13:08:39 2017) on "windows_x64"

Invalid argument(s): Illegal character in path

#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1695)

#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1760)
...
```

**Comment by jmesserly** [comment]
reverted that commit
