### ISSUE TITLE
DDC fails compiling a default parameter = a const Symbol

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30184]
Example:
https://gist.github.com/matanlurey/78b10f9dd0056766e84c0d06aa61cf9c

```
NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      CodeGenerator.visitSymbolLiteral.emitSymbol (package:dev_compiler/src/compiler/code_generator.dart:5130)
#3      CodeGenerator._emitConst.<anonymous closure> (package:dev_compiler/src/compiler/code_generator.dart:4431)
#4      CodeGenerator._cacheConst (package:dev_compiler/src/compiler/code_generator.dart:4415)
#5      CodeGenerator._emitConst (package:dev_compiler/src/compiler/code_generator.dart:4431)
#6      CodeGenerator.visitSymbolLiteral (package:dev_compiler/src/compiler/code_generator.dart:5140)
#7      SymbolLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:10250)
#8      CodeGenerator._visit (package:dev_compiler/src/compiler/code_generator.dart:5253)
#9      CodeGenerator._visitInitializer (package:dev_compiler/src/compiler/code_generator.dart:3909)
#10     CodeGenerator._emitLazyFields (package:dev_compiler/src/compiler/code_generator.dart:3927)
#11     CodeGenerator._emitTopLevelFields (package:dev_compiler/src/compiler/code_generator.dart:3893)
#12     CodeGenerator.visitCompilationUnit (package:dev_compiler/src/compiler/code_generator.dart:589)
#13     List.forEach (dart:core-patch/array.dart:73)
#14     CodeGenerator._emitModule (package:dev_compiler/src/compiler/code_generator.dart:347)
#15     CodeGenerator.compile (package:dev_compiler/src/compiler/code_generator.dart:231)
#16     ModuleCompiler.compile (package:dev_compiler/src/compiler/compiler.dart:222)
#17     _compile (package:dev_compiler/src/compiler/command.dart:186)
#18     compile (package:dev_compiler/src/compiler/command.dart:60)
```

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/52281
