### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#30226]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.23`
- `1.25.0-dev.7.0`
- `IU-171.4694.23, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.5 unknown, screens 2560x1600`

# Exception

```
Dart analysis server, SDK version 1.25.0-dev.7.0, server version 1.18.2, error: Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in SimpleFormalParameterImpl in FormalParameterListImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      Visitor.checkIdentifier (package:linter/src/rules/non_constant_identifier_names.dart:50)
#3      Visitor.visitFormalParameterList.<anonymous closure> (package:linter/src/rules/non_constant_identifier_names.dart:63)
#4      Object&ListMixin.forEach (dart:collection/list.dart:63)
#5      Visitor.visitFormalParameterList (package:linter/src/rules/non_constant_identifier_names.dart:61)
#6      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4811)
#7      ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2756)
#8      List.forEach (dart:core-patch/growable_array.dart:267)
#9      ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2754)
#10     UnifyingAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:3020)
#11     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4811)
#12     GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5739)
#13     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#14     UnifyingAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:3047)
#15     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5732)
#16     SimpleFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9233)
#17     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#18     UnifyingAstVisitor.visitSimpleFormalParameter (package:analyzer/dart/ast/visitor.dart:3168)
#19     SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9228)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#21     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4815)
#22     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#23     UnifyingAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:3020)
#24     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4811)
#25     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7485)
#26     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#27     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3106)
#28     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7477)
#29     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#30     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1974)
#31     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#32     UnifyingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:2937)
#33     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1906)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#35     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2502)
#36     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#37     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#38     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#39     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:249)
#40     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:131)
#41     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#42     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:130)
#43     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#44     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:129)
#45     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:64)
#46     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#47     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:63)
#48     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1069)
#49     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#50     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1057)
#51     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:894)
<asynchronous suspension>
#52     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1609)
<asynchronous suspension>
#53     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1552)
#54     new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#55     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#56     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#57     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:434)
#58     _rootRun (dart:async/zone.dart:1120)
#59     _CustomZone.run (dart:async/zone.dart:1001)
#60     runZoned (dart:async/zone.dart:1467)
#61     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:473)
#62     Driver.start (package:analysis_server/src/server/driver.dart:433)
#63     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#64     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1500663692019 <= {"id":"8492","result":{"assists":[]}}
1500663693483 => {"id":"8493","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1032,"length":0},"clientRequestTime":1500663
1500663693484 <= {"id":"8493","result":{"assists":[]}}
1500663693490 => {"id":"8494","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1032,"length":0},"clientRequestTime":1500663
1500663693491 => {"id":"8495","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1032,"length":0},"clientRequestTime":1500663
1500663693491 <= {"id":"8494","result":{"assists":[]}}
1500663693492 => {"id":"8496","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1032,"length":0},"clientRequestTime":1500663
1500663693492 <= {"id":"8495","result":{"assists":[]}}
1500663693492 <= {"id":"8496","result":{"assists":[]}}
1500663693493 => {"id":"8497","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1032,"length":0},"clientRequestTime":1500663
1500663693494 <= {"id":"8497","result":{"assists":[]}}
1500663694672 => {"id":"8498","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1042,"length":10},"clientRequestTime":150066
1500663694673 <= {"id":"8498","result":{"assists":[]}}
1500663694679 => {"id":"8499","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1042,"length":10},"clientRequestTime":150066
1500663694680 => {"id":"8500","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1042,"length":10},"clientRequestTime":150066
1500663694680 <= {"id":"8499","result":{"assists":[]}}
1500663694681 => {"id":"8501","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1042,"length":10},"clientRequestTime":150066
1500663694681 <= {"id":"8500","result":{"assists":[]}}
1500663694681 => {"id":"8502","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1042,"length":10},"clientRequestTime":150066
1500663694681 <= {"id":"8501","result":{"assists":[]}}
1500663694682 <= {"id":"8502","result":{"assists":[]}}
1500663698396 => {"id":"8503","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart":{"type":"add","content":"// Copyright (c) 20
1500663698403 <= {"id":"8503","result":{}}
1500663698403 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1500663698423 => {"id":"8504","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1042,"length":0},"clientRequestTime":1500663
1500663698436 => {"id":"8505","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1042,"length":0},"clientRequestTime":1500663
1500663698437 => {"id":"8506","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1042,"length":0},"clientRequestTime":1500663
1500663698438 => {"id":"8507","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1042,"length":0},"clientRequestTime":1500663
1500663698445 => {"id":"8508","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/type_helper.dart","offset":1042,"length":0},"clientRequestTime":1500663
1500663698455 <= {"event":"server.error","params":{"isFatal":false,"message":"Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in SimpleFormalParameterImpl
```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2986703002/
