### ISSUE TITLE
Analyzer error at bleeding edge, running against SDK tests

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#30252]
Perhaps foolishly, I attempted to have IntelliJ run the analyzer for everything under the tests directory.  It resulted in this crash, which seems to occur reliably.

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-172.3317.76`
- `1.24.2`
- `IC-172.3317.76, JRE 1.8.0_152-release-915-b5x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/w1/ynzyqn915kng3c3psc6b9js0000b33/T/report.txt

Appended below:

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Analysis failed: /Users/jcollins/dart/sdk/sdk/tests/language/regress_29481_test.dart context: exception_20170724_153153_111
Invalid argument(s): Cannot resolve a GenericFunctionTypeImpl
#0      TypeParameterBoundsResolver._resolveTypeParameters (package:analyzer/src/generated/resolver.dart:8886)
#1      TypeParameterBoundsResolver.resolveTypeBounds (package:analyzer/src/generated/resolver.dart:8848)
#2      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:534)
#3      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#5      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88)
#6      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:999)
#7      PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#8      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#9      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:854)
<asynchronous suspension>
#10     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#11     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#12     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#13     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#14     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#15     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     runZoned (dart:async/zone.dart:1467)
#19     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#20     Driver.start (package:analysis_server/src/server/driver.dart:473)
#21     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analysis_server/bin/server.dart:12)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1500935512851 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_26175_test.dart","errors":[]}}
1500935512861 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_26230_test.dart","errors":[]}}
1500935512868 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_26453_test.dart","errors":[]}}
1500935512874 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_26530_test.dart","errors":[]}}
1500935512879 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_26543_1_test.dart","errors":[]}}
1500935512884 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_26543_2_test.dart","errors":[]}}
1500935512895 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_26543_3_test.dart","errors":[]}}
1500935512907 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_26668_test.dart","errors":[{"severity":"WARNING","type":"STATIC_TYPE_WARNING","locatio
1500935512916 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_26855_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":
1500935512925 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_26948_test.dart","errors":[]}}
1500935512932 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_27164_test.dart","errors":[]}}
1500935512940 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_27572_test.dart","errors":[{"severity":"WARNING","type":"STATIC_TYPE_WARNING","locatio
1500935512946 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_27617_test.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/Users
1500935512954 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_27659_test.dart","errors":[]}}
1500935512961 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_27700_test.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/Users
1500935512968 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_27957_lib1.dart","errors":[]}}
1500935512977 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_27957_lib2.dart","errors":[]}}
1500935512982 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_27957_test.dart","errors":[]}}
1500935512992 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_28217_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":
1500935512998 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_28255_test.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/Users
1500935513006 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_28278_lib.dart","errors":[]}}
1500935513013 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_28278_test.dart","errors":[]}}
1500935513026 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_28341_test.dart","errors":[]}}
1500935513033 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_28610_test.dart","errors":[]}}
1500935513043 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_29025_test.dart","errors":[{"severity":"WARNING","type":"STATIC_TYPE_WARNING","locatio
1500935513052 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_29243_test.dart","errors":[]}}
1500935513065 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_29349_test.dart","errors":[{"severity":"WARNING","type":"STATIC_TYPE_WARNING","locatio
1500935513076 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_29357_test.dart","errors":[]}}
1500935513081 <= {"event":"analysis.errors","params":{"file":"/Users/jcollins/dart/sdk/sdk/tests/language/regress_29405_test.dart","errors":[{"severity":"WARNING","type":"STATIC_WARNING","location":{"
1500935513141 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/jcollins/dart/sdk/sdk/tests/language/regress_29481_test.dart context: exception_20170724_153153_11
```

**Comment by jcollins-g** [comment]
Sorry, yes, this is a duplicate.
