### ISSUE TITLE
Strong mode does not support super mixins

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30283]
Strong mode does not do any stronger checking for super mixins.  For example, the example below, which is statically valid in Dart 1.0, passes strong mode (and should not, since it crashes at runtime).

I believe the current proposal that the language team is considering would move support for super mixins over to a new syntax, so we may wish to wait on that to add strong mode support for super mixins.

```dart
class A {
  int get foo => 3;
}

// If used as a mixin, superclass should satisfy A's contract
class B extends A {
  void test() {
    print(foo.isEven);
  }
}

class C {
  num get foo => 3.0;
}

// C does not satisfy A's contract
class D extends C with B {}

void main() {
  new D().test();
}
```

```
leafp-macbookpro:sdk leafp$ ./xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --supermixin  ~/tmp/test.dart
Analyzing /Users/leafp/tmp/test.dart...
No issues found!
leafp-macbookpro:sdk leafp$ ./xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --supermixin  --strong ~/tmp/test.dart
Analyzing /Users/leafp/tmp/test.dart...
No issues found!
leafp-macbookpro:sdk leafp$ ./xcodebuild/ReleaseX64/dart-sdk/bin/dart -c  ~/tmp/test.dart
Unhandled exception:
NoSuchMethodError: Class 'double' has no instance getter 'isEven'.
Receiver: 3.0
Tried calling: isEven
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      C&B.test (file:///Users/leafp/tmp/test.dart:7:15)
#3      main (file:///Users/leafp/tmp/test.dart:18:11)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

cc @jmesserly @lrhn @eernstg @munificent @floitschG @Hixie

**Comment by jmesserly** [comment]
FWIW, super mixins are also not implemented in DDC: https://github.com/dart-lang/sdk/issues/27344

explicit mixin syntax would be excellent 👍

**Comment by bwilkerson** [comment]
@leafpetersen Should we close this issue, or is this still something under investigation?

**Comment by leafpetersen** [comment]
Sure we can close this since I think mixing planning is tracked elsewhere.
