### ISSUE TITLE
Crash in analysis server 1.25.0-dev.9.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#30307]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.23`
- `1.25.0-dev.9.0`
- `IU-171.4694.23, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 2560x1600`

# Exception
```
Dart analysis server, SDK version 1.25.0-dev.9.0, server version 1.18.3, error: Analysis failed: /Users/kevmoo/source/github/json_serializable/test/json_serializable_test.dart context: exception_20170801_081557_918
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept(Instance of 'ConstantVisitor')
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:594)
#3      ConstantVisitor.visitInstanceCreationExpression (package:analyzer/src/dart/constant/evaluation.dart:1364)
#4      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6447)
#5      ConstantEvaluationEngine.computeConstantValue (package:analyzer/src/dart/constant/evaluation.dart:189)
#6      _ConstantWalker.evaluate (package:analyzer/src/dart/analysis/library_analyzer.dart:744)
#7      DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:149)
#8      DependencyWalker.walk (package:front_end/src/dependency_walker.dart:168)
#9      LibraryAnalyzer._computeConstants (package:analyzer/src/dart/analysis/library_analyzer.dart:168)
#10     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:100)
#11     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:64)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#13     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:63)
#14     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1075)
#15     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#16     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1063)
#17     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:920)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1615)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1558)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#23     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:434)
#24     _rootRun (dart:async/zone.dart:1120)
#25     _CustomZone.run (dart:async/zone.dart:1001)
#26     runZoned (dart:async/zone.dart:1467)
#27     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:473)
#28     Driver.start (package:analysis_server/src/server/driver.dart:433)
#29     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1501600555782 => {"id":"262","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart":{"type":"add","content":"// C
1501600555797 <= {"id":"262","result":{}}
1501600555797 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1501600555815 => {"id":"263","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","offset":6156,"length":0},"clientReque
1501600555849 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","errors":[{"severity":"INFO","type":"TODO","locati
1501600555850 <= {"id":"263","result":{"assists":[]}}
1501600555854 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","regions":[{"type":"DIRECTIVE","offset":217,"l
1501600555860 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","regions":[{"offset":224,"length":12,"targets"
1501600555876 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","overrides":[{"offset":1946,"length":27,"superc
1501600555876 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1501600555876 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","classes":[],"members":[]}}
1501600556600 => {"id":"264","method":"edit.getFixes","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","offset":6171},"clientRequestTime":15016
1501600556601 <= {"id":"264","result":{"fixes":[]}}
1501600556617 => {"id":"265","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","offset":6171,"length":0},"clientReque
1501600556618 <= {"id":"265","result":{"assists":[]}}
1501600557040 => {"id":"266","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","offset":6172,"length":0},"clientReque
1501600557040 => {"id":"267","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","offset":6172,"length":0},"clientReque
1501600557041 <= {"id":"266","result":{"assists":[]}}
1501600557041 <= {"id":"267","result":{"assists":[]}}
1501600557643 => {"id":"268","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart":{"type":"add","content":"// C
1501600557646 <= {"id":"268","result":{}}
1501600557646 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1501600557669 => {"id":"269","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","offset":6172,"length":0},"clientReque
1501600557732 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ER
1501600557733 <= {"id":"269","result":{"assists":[]}}
1501600557735 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","regions":[{"type":"DIRECTIVE","offset":217,"l
1501600557741 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","regions":[{"offset":224,"length":12,"targets"
1501600557742 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/src/json_serializable_generator.dart","overrides":[{"offset":1946,"length":27,"superc
1501600557749 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/lib/generators.dart","errors":[]}}
1501600557944 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/kevmoo/source/github/json_serializable/test/json_serializable_test.dart context: exception_2017080
```

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2989193002/
