### ISSUE TITLE
DDC exception "AnalysisContext must be strong mode"

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#30319]
I think a less "dramatic" behavior than 

```
We're sorry, you've found a bug in our compiler.
```

would be helpful.

```
Error compiling dartdevc module:angular|lib/lib__shared_1.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=/usr/local/Cellar/dart/1.25.0-dev.9.0/libexec --dart-sdk-summary=/usr/local/Cellar/dart/1.25.0-dev.9.0/libexec/lib/_internal/ddc_sdk.sum --modules=amd --dart-sdk=/usr/local/Cellar/dart/1.25.0-dev.9.0/libexec --module-root=/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1 --library-root=/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular --summary-extension=linked.sum --no-summarize -o /private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/lib__shared_1.js --source-map --source-map-comment --inline-source-map -s /private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/meta/lib__meta.linked.sum -s /private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/logging/lib__logging.linked.sum -s /private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/stack_trace/lib__stack_trace.linked.sum -s /private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/path/lib__path.linked.sum --url-mapping=package:angular/src/core/di/decorators.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/di/decorators.dart --url-mapping=package:angular/src/core/di/injector.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/di/injector.dart --url-mapping=package:angular/src/core/di/opaque_token.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/di/opaque_token.dart --url-mapping=package:angular/src/di/provider.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/di/provider.dart --url-mapping=package:angular/src/core/di/provider.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/di/provider.dart --url-mapping=package:angular/src/facade/exception_handler.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/facade/exception_handler.dart --url-mapping=package:angular/src/facade/exceptions.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/facade/exceptions.dart --url-mapping=package:angular/src/core/di/reflective_key.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/di/reflective_key.dart --url-mapping=package:angular/src/core/reflection/types.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/reflection/types.dart --url-mapping=package:angular/src/core/reflection/platform_reflection_capabilities.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/reflection/platform_reflection_capabilities.dart --url-mapping=package:angular/src/core/reflection/reflector.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/reflection/reflector.dart --url-mapping=package:angular/src/core/reflection/reflection.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/reflection/reflection.dart --url-mapping=package:angular/src/facade/lang.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/facade/lang.dart --url-mapping=package:angular/src/core/di/reflective_provider.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/di/reflective_provider.dart --url-mapping=package:angular/src/core/di/reflective_injector.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/di/reflective_injector.dart --url-mapping=package:angular/src/core/di/reflective_exceptions.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/di/reflective_exceptions.dart --url-mapping=package:angular/src/core/di.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/di.dart --url-mapping=package:angular/src/core/metadata/view.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/metadata/view.dart --url-mapping=package:angular/src/core/zone/ng_zone.dart,/private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/pub_Q1grM1/packages/angular/src/core/zone/ng_zone.dart package:angular/src/core/di/decorators.dart package:angular/src/core/di/injector.dart package:angular/src/core/di/opaque_token.dart package:angular/src/di/provider.dart package:angular/src/core/di/provider.dart package:angular/src/facade/exception_handler.dart package:angular/src/facade/exceptions.dart package:angular/src/core/di/reflective_key.dart package:angular/src/core/reflection/types.dart package:angular/src/core/reflection/platform_reflection_capabilities.dart package:angular/src/core/reflection/reflector.dart package:angular/src/core/reflection/reflection.dart package:angular/src/facade/lang.dart package:angular/src/core/di/reflective_provider.dart package:angular/src/core/di/reflective_injector.dart package:angular/src/core/di/reflective_exceptions.dart package:angular/src/core/di.dart package:angular/src/core/metadata/view.dart package:angular/src/core/zone/ng_zone.dart
    dart --version: 1.25.0-dev.9.0 (Tue Aug  1 01:48:27 2017) on "macos_x64"

Invalid argument(s): AnalysisContext must be strong mode
#0      new ModuleCompiler (package:dev_compiler/src/compiler/compiler.dart:123)
#1      _compile (package:dev_compiler/src/compiler/command.dart:136)
#2      compile (package:dev_compiler/src/compiler/command.dart:60)
#3      _CompilerWorker.performRequest (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:69)
<asynchronous suspension>
#4      AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33)
#5      _rootRun (dart:async/zone.dart:1120)
#6      _CustomZone.run (dart:async/zone.dart:1001)
#7      runZoned (dart:async/zone.dart:1467)
#8      AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33)
<asynchronous suspension>
#9      main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:51)
<asynchronous suspension>
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

The root cause 
```
Invalid argument(s): AnalysisContext must be strong mode
```
is hidden within a lot of exception output (the same exception output repeatedly)

**Comment by vsmenon** [comment]
@jakemac53 

Hmm, that's bad.  :-)  What were you building?  Was this during a `pub serve`?

**Comment by zoechi** [comment]
Yes, it was with `pub serve` and all was missing was that strong mode was not enabled in analyis_options.yaml. And I found "bug in our compiler" a bit dramatic. I'd rather see a message like

Please enable strong mode. For more details see https://www.dartlang.org/guides/language/analysis-options#specifying-strong-mode

**Comment by jakemac53** [comment]
Hmm, I thought ddc automatically overrides the context be be strong mode regardless of your analysis_options.yaml setting?

**Comment by zoechi** [comment]
It didn't when I tried back then. Enabling strong mode in analysis_options.yaml fixed the error.
I haven't tried since, because I run into several other issues.

**Comment by vsmenon** [comment]
Yes, what @jakemac53 said - DDC should be setting strong mode regardless:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/analyzer/context.dart#L76

@zoechi did you have `strong-mode` explicitly set to false in your yaml file?  Did you see the error on initial compile or a later recompile?

**Comment by zoechi** [comment]
@vsmenon no, the setting was just missing.

**Comment by jakemac53** [comment]
It looks like if you have an `analyzer:` section which doesn't explicitly specify strong mode then this error happens. An empty file or one that has no `analyzer:` section works fine.

**Comment by zoechi** [comment]
@jakemac53 that's possible. I added the strong-mode setting. I don't remember how exactly the file looked like before that. But I guess you're right.
Glad to hear that this should now be reproducible.

The issue is mainly about the error output though.
If you check the output closely it actually tells strong mode is not enabled, but the rest of the output is unnecessary and confusing.

**Comment by vsmenon** [comment]
Yes, we're just surprised it could happen.  The intent wasn't to tell folks to enable strong mode.  The intent was to force strong mode on regardless.  :-)

It looks like the yaml file is overriding this in a surprising way.

**Comment by jakemac53** [comment]
I think the error output is just because it was an unhandled exception and that is the default handling.

Since this does indicate user-error generally it should probably look different.

**Comment by vsmenon** [comment]
Hmm, seems related to https://github.com/dart-lang/sdk/issues/29713 - that's closed but a few forked issues from there.

**Comment by jmesserly** [comment]
pub serve has been deprecated/removed. we can reopen if this happens with the new build system
