### ISSUE TITLE
Analyzer crash (RangeError) when typing in analyzer code

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#30327]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Working on the analyzer. Note: I'm not running the same version that I'm editing - I'm using 1.24.2 SDK and just happen to have a copy of the analysis_server package open. Log is attached - I deleted a single character from `computer_closingLabels.dart` (the `e` off the end of `name` in line 42).

[analyzer.txt](https://github.com/dart-lang/sdk/files/1201478/analyzer.copy.txt)
[computer_closingLabels.dart.txt](https://github.com/dart-lang/sdk/files/1201481/computer_closingLabels.dart.txt)

@bwilkerson I can repro this by opening the file with the `e` missing and then just putting the cursor there. I've taken a copy of the analysis_server folder though it's 1.2MB zipped. If you can't repro or understand from the rest of this report, let me know and I can send it over.

### Versions

- Dart SDK 1.24.2
- Visual Studio Code 1.14.2
- Dart Code 2.3.5

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=2.3.5
```

### Exception (fatal)

Failed to handle request: {id: 16, method: edit.getFixes, params: {file: /Users/danny/Dev/Google/sdk/pkg/analysis_server/lib/src/computer/computer_closingLabels.dart, offset: 1354}}

```text
RangeError (index): Invalid value: Not in range 0..2628, inclusive: 172427
#0      String.codeUnitAt (dart:core-patch/string_patch.dart:927)
#1      CorrectionUtils.getLineThis (package:analysis_server/src/services/correction/util.dart:1004)
#2      CorrectionUtils.isClassWithEmptyBody (package:analysis_server/src/services/correction/util.dart:1233)
#3      CorrectionUtils.prepareNewClassMemberLocation (package:analysis_server/src/services/correction/util.dart:1270)
#4      CorrectionUtils.prepareNewFieldLocation (package:analysis_server/src/services/correction/util.dart:1287)
#5      FixProcessor._addFix_createField (package:analysis_server/src/services/correction/fix_internal.dart:1195)
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:390)
<asynchronous suspension>
#7      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:85)
<asynchronous suspension>
#8      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:242)
<asynchronous suspension>
#9      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:319)
#10     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:975)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#12     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:971)
#13     _rootRun (dart:async/zone.dart:1120)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     _CustomZone.runGuarded (dart:async/zone.dart:901)
#16     runZoned (dart:async/zone.dart:1465)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:970)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:168)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:159)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#22     _rootRunUnary (dart:async/zone.dart:1128)
#23     _CustomZone.runUnary (dart:async/zone.dart:1012)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#34     _rootRunUnary (dart:async/zone.dart:1128)
#35     _CustomZone.runUnary (dart:async/zone.dart:1012)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#47     _rootRunUnary (dart:async/zone.dart:1128)
#48     _CustomZone.runUnary (dart:async/zone.dart:1012)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#53     _StreamController._add (dart:async/stream_controller.dart:667)
#54     _StreamController.add (dart:async/stream_controller.dart:613)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#56     _rootRunUnary (dart:async/zone.dart:1132)
#57     _CustomZone.runUnary (dart:async/zone.dart:1012)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#62     _StreamController._add (dart:async/stream_controller.dart:667)
#63     _StreamController.add (dart:async/stream_controller.dart:613)
#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#68     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by bwilkerson** [comment]
I am not able to get it to fail using bleeding edge. Haven't yet tried using 1.24.2.

**Comment by DanTup** [comment]
I've shut down for the night but I can try on master over the weekend and if still happens I'll try and trim the repro down a little and attach it.

**Comment by DanTup** [comment]
@bwilkerson I can still repro on master here. I've pushed the exact code to this branch here:

https://github.com/DanTup/sdk/tree/as-crash

So, try this:

- Clone that repro/fetch dependencies/whatever
- Open pkg/analysis_server from that repo as an analysis root (but using master to actually run the analyzer)
- Open the file `computer_closingLabels.dart`
- Send a getFixes command with the cursor immediately after the compile error on `.nam` (if using Code, just putting the cursor there will do this)

It's perfectly reproducible here, happens every time. Let me know if you can't get it.

**Comment by bwilkerson** [comment]
I'm guessing I don't have permission:
```
$ git clone https://github.com/DanTup/sdk/tree/as-crash
Cloning into 'as-crash'...
remote: Not Found
fatal: repository 'https://github.com/DanTup/sdk/tree/as-crash/' not found
```

**Comment by DanTup** [comment]
@bwilkerson Sorry, that link was to see the branch on GH! The repo url is:

https://github.com/DanTup/sdk

And the branch is called `as-crash`.

**Comment by bwilkerson** [comment]
Found it! I'm kind of surprised that no one has run into this before now. It happens when we attempt to construct a fix to add a member to a class, the class is defined in a file other than the one containing the error being fixed, and the location of the class' opening and/or closing braces are past the end of the file containing the error.

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2998703002/

**Comment by DanTup** [comment]
Yeah, I thought it might be something like that 😂

👍
