### ISSUE TITLE
UnimplementedError: UnmatchedToken

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#30320]
@danrubel I'm running a fuzz tester for dart-lang/angular-analyzer-plugin, and every 100 or so fuzzes I get

```
UnimplementedError: UnmatchedToken
#0      translateErrorToken (package:front_end/src/scanner/errors.dart:147:7)
#1      _Scanner2.tokenize (package:analyzer/src/dart/scanner/scanner.dart:185:7)
#2      FileState._parse.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:613:24)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200:15)
#4      FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:612:48)
#5      FileState.parse.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:395:14)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200:15)
#7      FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:394:40)
#8      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:444:32)
#9      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:805:12)
#10     AnalysisDriver._computeUnitElementSignature (package:analyzer/src/dart/analysis/driver.dart:1145:31)
#11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:846:26)
<asynchronous suspension>
#12     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1616:26)
<asynchronous suspension>
#13     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1558:5)
#14     AbstractAngularTest.setUp (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/angular_analyzer_plugin/test/abstract_angular.dart:115:54)
#15     FuzzTest.checkNoCrash.<anonymous closure> (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/angular_analyzer_plugin/test/fuzz_test.dart:603:18)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     _CustomZone.runGuarded (dart:async/zone.dart:901)
#19     runZoned (dart:async/zone.dart:1465)
#20     FuzzTest.checkNoCrash (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/angular_analyzer_plugin/test/fuzz_test.dart:602:5)
#21     FuzzTest.test_fuzz_continually (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/angular_analyzer_plugin/test/fuzz_test.dart:454:13)
<asynchronous suspension>
#22     main (file:///home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/angular_analyzer_plugin/test/fuzz_test.dart:19:18)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

which is cluttering output for my own possible exceptions :)

Here's one reproduction. I tried to simplify it, but my analysis server seemed to have got into a real funk

```
-->                                                                              
  selector: 'my-aaa',                                                            
                                                                                 
class Compone                                                                    
       ria-hidden="true"                                                         
       attr.aria-hidden="{{!invalid}}"                                           
import 'pakage:angular2/angular2.dart';                                          
                                                                                 
  directives: const [Coun terComponent, NgIf, NgFor, NgForm, NgModel])<!--       
@Component(                                                                      
  templateUrl: 'test.htisml',
```

@bwilkerson after a while of modifying this to figure out what exactly caused the issue, I started getting

```
Object._noSuchMethod (dart::core-patch/object_patch.dart::42)
#1      Object.noSuchMethod (dart::core-patch/object_patch.dart::46)
#2      ApiSignature.addBytes (package::front_end/src/base/api_signature.dart::73)
#3      Iterable.forEach (dart::core/iterable.dart::226)
#4      FileState.transitiveSignature (package::analyzer/src/dart/analysis/file_state.dart::364)
#5      AnalysisDriver._getResolvedUnitSignature (package::analyzer/src/dart/analysis/driver.dart::1250)
#6      AnalysisDriver._computeAnalysisResult (package::analyzer/src/dart/analysis/driver.dart::1035)
#7      AnalysisDriver.performWork (package::analyzer/src/dart/analysis/driver.dart::914)
<asynchronous suspension>
#8      AnalysisDriverScheduler._run (package::analyzer/src/dart/analysis/driver.dart::1609)
<asynchronous suspension>
#9      AnalysisDriverScheduler.start (package::analyzer/src/dart/analysis/driver.dart::1552)
#10     new AnalysisServer (package::analysis_server/src/analysis_server.dart::383)
#11     SocketServer.createAnalysisServer (package::analysis_server/src/socket_server.dart::86)
#12     StdioAnalysisServer.serveStdio (package::analysis_server/src/server/stdio_server.dart::37)
#13     Driver.start.<anonymous closure> (package::analysis_server/src/server/driver.dart::434)
#14     _rootRun (dart::async/zone.dart::1120)
#15     _CustomZone.run (dart::async/zone.dart::1001)
#16     runZoned (dart::async/zone.dart::1467)
#17     Driver._captureExceptions (package::analysis_server/src/server/driver.dart::473)
#18     Driver.start (package::analysis_server/src/server/driver.dart::433)
#19     main (file::///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/analysis_server/bin/server.dart::12)
#20     _startIsolate.<anonymous closure> (dart::isolate-patch/isolate_patch.dart::263)
#21     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::151)
```

even after clearing out ~/.dartServer/.analysis_driver and restarting DAS. No idea why it suddenly switched from one exception to the other.

**Comment by bwilkerson** [comment]
@scheglov The second looks like the file state doesn't have a salt for a file. Is that normal (and we forgot to guard against it) or is the absence of the salt the real issue here?

**Comment by scheglov** [comment]
No, it is not normal, and we should not guard against them.

This is a subsequence of a previous exception in a scanner, or a parser, or loading the unlinked unit from the byte store. Once these errors are fixed, we won't have the API signature problems (and a couple of other exception kinds we see in the internal monitoring).

**Comment by danrubel** [comment]
@MichaelRFairhurst Do you have the source code that was scanned, causing this error? Or some snippet of what was "fuzzed" to create the problem? This may be related to a fasta scanner recovery bug I'm trying to track down.

**Comment by MichaelRFairhurst** [comment]
Yep its in the original post.

**Comment by danrubel** [comment]
Wow. I looked right at it and my brain did not register it as Dart code so I didn't see it. :$
I'll see if I can recreate and debug with this.
Thanks!

**Comment by MichaelRFairhurst** [comment]
Absolutely! Sorry with the curt reply. Was paintballing with the team for
an offsite :)
