### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#30357]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-172.3544.35`
- `1.24.2`
- `IC-172.3544.35, JRE 1.8.0_152-release-915-b6x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\semenov\AppData\Local\Temp\report.txt
[report.txt](https://github.com/dart-lang/sdk/files/1207480/report.txt)

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Could not initialize the library map from [D:\dev\dart\sdk\lib\_internal\sdk_library_metadata\lib\libraries.dart, D:\dev\dart\sdk\lib\_internal\libraries.dart]

FileSystemException(path=D:\dev\dart\sdk\lib\_internal\libraries.dart
```
It looks like dart sdk installation directory is changed 
**D:\dev\dart\sdk**\lib\_internal\libraries.dart should be **D:\dev\dart-sdk**\lib\_internal\libraries.dart

**Comment by bwilkerson** [comment]
Server uses the sdk path passed by IntelliJ, so I'm guessing this is on the IntelliJ side.

**Comment by alexander-doroshko** [comment]
@bwilkerson, this looks like a corrupted Dart SDK installation to me.
@alsemenov, could you attach these 2 files here: `D:\dev\dart\sdk\lib\_internal\sdk_library_metadata\lib\libraries.dart` and `D:\dev\dart\sdk\lib\_internal\libraries.dart`.

**Comment by alsemenov** [comment]
I'd like to clarify:
Dart SDK is installed into D:\dev\dart\dart-sdk\
This directory is specified in IDEA settings 
![idea_dart_settings](https://user-images.githubusercontent.com/4629015/29104851-3412acf4-7cf3-11e7-86ca-65380b1db3b5.png)
In provided report.txt there is a command line for starting the server
```
D:\dev\dart\dart-sdk\bin\dart.exe D:\dev\dart\dart-sdk\bin\snapshots\analysis_server.dart.snapshot --client-id=IntelliJ-IDEA --client-version=IC-172.3544.35 --useAnalysisHighlight2
```
It uses correct installation directory and dart.exe path
But for some unknown to me reason the server tries to open file `D:\\dev\\dart\\sdk\\lib\\_internal\\sdk_library_metadata\\lib\\libraries.dart`, which is neither inside of Dart SDK installation directory nor inside current project directory. 

In fact, directory `d:\dev\dart\sdk` also exists, it contains cloned [Dart SDK](https://github.com/dart-lang/sdk/) repository. There is no directory `d:\dev\dart\sdk\lib\`, thus requested files `D:\dev\dart\sdk\lib\_internal\sdk_library_metadata\lib\libraries.dart` and `D:\dev\dart\sdk\lib\_internal\libraries.dart` do not exist. However they exist inside Dart SDK installation directory.

**Comment by alexander-doroshko** [comment]
@bwilkerson I have reproduced the issue and I do not see anything wrong done by the IDE. Assigning area-analyzer. 
If you have:
- `https://github.com/dart-lang/sdk` cloned to `C:\dev\dart\sdk`
- standard Dart SDK 1.24.2 installed in `C:\dev\dart\dart-sdk`

then as soon as you open any Dart project and configure `C:\dev\dart\dart-sdk` as a Dart SDK you get Analysis Server crash because of looking for `libraries.dart` files in incorrect locations.
```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Could not initialize the library map from [C:\dev\dart\sdk\lib\_internal\sdk_library_metadata\lib\libraries.dart, C:\dev\dart\sdk\lib\_internal\libraries.dart]

FileSystemException(path=C:\dev\dart\sdk\lib\_internal\libraries.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:186)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:616)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:496)
#3      ContextBuilder.findSdk.<anonymous closure> (package:analyzer/src/context/builder.dart:379)
#4      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:131)
#5      DartSdkManager.getSdk (package:analyzer/src/generated/sdk.dart:148)
#6      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:378)
#7      ContextBuilder.createSourceFactory (package:analyzer/src/context/builder.dart:249)
#8      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:166)
#9      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1958)
...
```

**Comment by bwilkerson** [comment]
Found it. The problem is some special case code that exists to support our testing infrastructure. The code in question is here (https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/dart/sdk/sdk.dart#L704). It takes the location of the running VM (`exec`), which in this case is `D:\dev\dart\dart-sdk\bin\dart.exe`, strips off the last two components so that `outDir` is `D:\dev\dart\dart-sdk`, replaces the last component so that `sdkPath` is `D:\dev\dart\sdk` and checks to see whether the directory exists. If so, it assumes that we're running a test. In this case that assumption is wrong.

I'll think about whether we can safeguard the code more, but in the meantime you can work around the problem by checking out the repo to a different location.
