### ISSUE TITLE
Future being completed multiple times

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30365]
This appears to be in the angular plugin.
```
Bad state: Future already completed
#0      _Completer.completeError (dart:async/future_impl.dart:21)
#1      AngularDriver.getUnit (package:angular_analyzer_plugin/src/angular_driver.dart:696)
#2      _asyncThenWrapperHelper.anonymous closure (dart:async-patch/async_patch.dart:30)
#3      _rootRunUnary (dart:async/zone.dart:1128)
#4      _CustomZone.runUnary (dart:async/zone.dart:1012)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#6      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#7      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#8      _Future._completeWithValue (dart:async/future_impl.dart:478)
#9      _Future._asyncComplete.\u003canonymous closure\u003e (dart:async/future_impl.dart:510)
#10     _rootRun (dart:async/zone.dart:1120)
#11     _CustomZone.run (dart:async/zone.dart:1001)
#12     _CustomZone.runGuarded (dart:async/zone.dart:901)
#13     _CustomZone.bindCallback.\u003canonymous closure\u003e (dart:async/zone.dart:926)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

asynchronous suspension

#19     AngularDriver.performWork (package:angular_analyzer_plugin/src/angular_driver.dart:237)

asynchronous suspension

#20     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1609)

asynchronous suspension

#21     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1552)
#22     new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#23     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#24     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#25     Driver.start.anonymous closure (package:analysis_server/src/server/driver.dart:434)
#26     _rootRun (dart:async/zone.dart:1120)
#27     _CustomZone.run (dart:async/zone.dart:1001)
#28     runZoned (dart:async/zone.dart:1467)
#29     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:473)
#30     Driver.start (package:analysis_server/src/server/driver.dart:433)

asynchronous suspension

#32     _startIsolate.\u003canonymous closure\u003e (dart:isolate-patch/isolate_patch.dart:263)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by MichaelRFairhurst** [comment]
I think this is an error in the AnalysisDriver. This is the line of code

```
  Future<CompilationUnitElement> getUnit(String path) async =>                   
      (await dartDriver.getUnitElement(path)).element;
```

But I'm not sure I understand dart's asyncy stuff enough to say for sure...

**Comment by bwilkerson** [comment]
I can't say that I understand the output either, but I noticed that `AnalysisDriver.getUnitElement` is documented as being able to return `null`:
```
/**
 * Return a [Future] that completes with the [UnitElementResult] for the
 * file with the given [path], or with `null` if the file cannot be analyzed.
 */
```
But the code in `AngularDriver` doesn't handle that possibility. Given that the first line of the stack trace is `_Completer.completeError`, it's possible that a `null` value was returned and an error was thrown when attempting to invoke `element`.

**Comment by lrhn** [comment]
This looks problematic. It seems to be a completer defined internally in the VM's implementation of `async` functions. There should be no way for that to be completed twice.

It's obviously possible if somebody else mis-implements `Future` in a way that calls a `then`-listener more than once, but I think such an egeregious breach of contract would be caught quickly.

**Comment by MichaelRFairhurst** [comment]
I never understood why this happened, but it has stopped under the new plugin architecture.

Much more likely than not there was something boneheaded in what I was doing, I don't think this is indicative of a deeper problem, so I'm closing.
