### ISSUE TITLE
Crash in angular plugin

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30364]
This is non-fatal for server, but I believe that it's crashing the angular plugin's isolate.
```
NoSuchMethodError: The getter 'typeParameters' was called on null.\nReceiver: null\nTried calling: typeParameters
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      BindingTypeSynthesizer._instantiateClass (package:angular_analyzer_plugin/src/directive_extraction.dart:626)
#3      new BindingTypeSynthesizer (package:angular_analyzer_plugin/src/directive_extraction.dart:567)
#4      DirectiveLinker.resynthesizeDirectives (package:angular_analyzer_plugin/src/directive_linking.dart:55)

asynchronous suspension

#5      AngularDriver.resynthesizeDirectives (package:angular_analyzer_plugin/src/angular_driver.dart:700)

asynchronous suspension

#6      AngularDriver.getAngularAnnotatedClasses (package:angular_analyzer_plugin/src/angular_driver.dart:712)

asynchronous suspension

#7      AngularDriver.resolveDart (package:angular_analyzer_plugin/src/angular_driver.dart:593)

asynchronous suspension


#8      AngularDriver.pushDartErrors (package:angular_analyzer_plugin/src/angular_driver.dart:546)

asynchronous suspension

#9      AngularDriver.performWork (package:angular_analyzer_plugin/src/angular_driver.dart:237)

asynchronous suspension

#10     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1609)

asynchronous suspension

#11     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1552)
#12     new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#13     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#14     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#15     Driver.start.anonymous closure (package:analysis_server/src/server/driver.dart:434)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     runZoned (dart:async/zone.dart:1467)
#19     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:473)
#20     Driver.start (package:analysis_server/src/server/driver.dart:433)

asynchronous suspension

#22     _startIsolate.\u003canonymous closure\u003e (dart:isolate-patch/isolate_patch.dart:263)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by MichaelRFairhurst** [comment]
Hmm, I haven't reproduced this one yet. I think its a race condition that won't be solved until we have an AnalysisSession. That said, I'll keep an eye out for it in my fuzzer, which gives me something reproducible.

**Comment by bwilkerson** [comment]
Would it make sense to add code to guard against the exception? Or code to produce some debugging output that you could use to find and fix the underlying problem? Based on internal logs, this appears to be happening not infrequently.
