### ISSUE TITLE
incremental compilation fails on two-file app

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30409]
Changing imported library(lib.dart) (change literal 142 to 42) and trying to recompile and hot-reload results in crash in frontend kernel serialization:
```
╰─➤  xcodebuild/DebugX64/dart pkg/front_end/example/incremental_reload/run.dart main.dart out.dill 

Press a key to trigger a command:
   r:  incremental compile + reload
   c:  incremental compile w/o reload
   l:  reload w/o recompile
   q:  quit
#    Files     Files %      ------- Time -------------------------  Binary
     Modified  Sent  Total      Check Compile   Reload    Total      Avg   Size  
  1:        0      2  100%      0 ms  1003 ms     0 ms  1003 ms  1003 ms   418b
  2:        1      2  100%      1 ms    24 ms     0 ms    25 ms   514 ms     0b
  error: compilation error: Reference to root::dart:async::Timer::@factories::periodic is not bound to an AST node. A procedure was expected, #0      Reference.asProcedure (package:kernel/ast.dart:227:7)
#1      StaticInvocation.target (package:kernel/ast.dart:2369:44)
#2      StaticInvocation.visitChildren (package:kernel/ast.dart:2385:5)
#3      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:294:10)
#4      Visitor.defaultTreeNode (package:kernel/visitor.dart:263:39)
#5      TreeVisitor.defaultExpression (package:kernel/visitor.dart:122:43)
#6      TreeVisitor.visitStaticInvocation (package:kernel/visitor.dart:140:53)
#7      StaticInvocation.accept (package:kernel/ast.dart:2381:36)
#8      ExpressionStatement.visitChildren (package:kernel/ast.dart:3202:17)
#9      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:294:10)
#10     Visitor.defaultTreeNode (package:kernel/visitor.dart:263:39)
#11     TreeVisitor.defaultStatement (package:kernel/visitor.dart:176:41)
#12     TreeVisitor.visitExpressionStatement (package:kernel/visitor.dart:179:7)
#13     ExpressionStatement.accept (package:kernel/ast.dart:3198:35)
#14     visitList (package:kernel/ast.dart:4552:14)
#15     Block.visitChildren (package:kernel/ast.dart:3224:5)
#16     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:294:10)
#17     Visitor.defaultTreeNode (package:kernel/visitor.dart:263:39)
#18     TreeVisitor.defaultStatement (package:kernel/visitor.dart:176:41)
#19     TreeVisitor.visitBlock (package:kernel/visitor.dart:180:31)
#20     Block.accept (package:kernel/ast.dart:3220:35)
#21     FunctionNode.visitChildren (package:kernel/ast.dart:1556:11)
#22     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:294:10)
#23     Visitor.defaultTreeNode (package:kernel/visitor.dart:263:39)
#24     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:228:45)
#25     FunctionNode.accept (package:kernel/ast.dart:1549:30)
#26     Procedure.visitChildren (package:kernel/ast.dart:1264:15)
#27     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:294:10)
#28     Visitor.defaultTreeNode (package:kernel/visitor.dart:263:39)
#29     TreeVisitor.defaultMember (package:kernel/visitor.dart:203:35)
#30     TreeVisitor.visitProcedure (package:kernel/visitor.dart:205:39)
#31     StringIndexer.visitProcedure (package:kernel/binary/ast_to_binary.dart:1410:25)
#32     Procedure.accept (package:kernel/ast.dart:1257:32)
#33     visitList (package:kernel/ast.dart:4552:14)
#34     Library.visitChildren (package:kernel/ast.dart:372:5)
#35     StringIndexer.visitLibrary (package:kernel/binary/ast_to_binary.dart:1355:10)
#36     Library.accept (package:kernel/ast.dart:365:30)
#37     StringIndexer.scanLibrary (package:kernel/binary/ast_to_binary.dart:1311:13)
#38     LimitedBinaryPrinter.buildStringIndex.<anonymous closure> (package:kernel/binary/limited_ast_to_binary.dart:42:21)
#39     Iterable.forEach (dart:core/iterable.dart:226)
#40     LimitedBinaryPrinter.buildStringIndex (package:kernel/binary/limited_ast_to_binary.dart:41:40)
#41     BinaryPrinter.writeProgramFile (package:kernel/binary/ast_to_binary.dart:182:5)
#42     rebuild (file:///Users/aam/projects/dart1/sdk/pkg/front_end/example/incremental_reload/compiler_with_invalidation.dart:158:12)
<asynchronous suspension>
#43     listenOnKeyPress.<anonymous closure> (file:///Users/aam/projects/dart1/sdk/pkg/front_end/example/incremental_reload/run.dart:81:37)
<asynchronous suspension>
#44     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#47     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#48     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#49     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#50     _SimpleAsciiDecoderSink.add (dart:convert/ascii.dart:296)
#51     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#52     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#53     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#56     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#57     _StreamController._add (dart:async/stream_controller.dart:667)
#58     _StreamController.add (dart:async/stream_controller.dart:613)
#59     _Socket._onData (dart:io-patch/socket_patch.dart:1643)
#60     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#63     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#64     _StreamController._add (dart:async/stream_controller.dart:667)
#65     _StreamController.add (dart:async/stream_controller.dart:613)
#66     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
#67     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#68     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#69     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#70     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

main.dart:
```
import 'dart:async';
import 'lib.dart';

void main() {
   new Timer.periodic(new Duration(seconds:1), (_) { print(info()); });
}
```

lib.dart:
```
info() { return 142; } 
```

**Comment by aam** [comment]
@scheglov

**Comment by scheglov** [comment]
https://codereview.chromium.org/2995773002/

**Comment by sigmundch** [comment]
Thanks @scheglov - I'm a bit surprised - github said I assigned the issue to you here, but I believe Alex was who did so. It doesn't matter, but pretty odd.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/ada4db3fb6c7cb067e0f0bb98f9ec23d9362e5a5
