### ISSUE TITLE
Crash: SDK 1.25.0-dev.10

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#30439]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.23`
- `1.25.0-dev.10.0`
- `IU-171.4694.23, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 2560x1600`

# Exception

Please append the contents of:
file:///private/var/folders/bj/09dxmvxx5hl4t07lbvqgj66w0071_k/T/report.txt

```
Dart analysis server, SDK version 1.25.0-dev.10.0, server version 1.18.3, error: Captured exception
UnimplementedError: UnmatchedToken
#0      translateErrorToken (package:front_end/src/scanner/errors.dart:147)
#1      _Scanner2.tokenize (package:analyzer/src/dart/scanner/scanner.dart:185)
#2      FileState._parse.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:613)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#4      FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:612)
#5      FileState.parse.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:395)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#7      FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:394)
#8      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:444)
#9      FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:220)
#10     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#11     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:216)
#12     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:289)
#13     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:801)
<asynchronous suspension>
#14     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1615)
<asynchronous suspension>
#15     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1558)
#16     new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#17     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#18     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#19     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:434)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     runZoned (dart:async/zone.dart:1467)
#23     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:473)
#24     Driver.start (package:analysis_server/src/server/driver.dart:433)
#25     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

```
1502816287143 => {"id":"228","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","offset":6816,"length":0},"clientRequestTime":1502816287143}
1502816287147 <= {"id":"227","result":{}}
1502816287147 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1502816287163 => {"id":"229","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","offset":6816,"length":0},"clientRequestTime":1502816287163}
1502816287198 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","errors":[{"severity":"ERROR","type":"STATIC_TYPE_WARNING","location":{"file
1502816287198 <= {"id":"228","result":{"assists":[]}}
1502816287199 <= {"id":"229","result":{"assists":[]}}
1502816287201 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN
1502816287204 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"length":
1502816287205 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","overrides":[]}}
1502816287207 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1502816287207 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","classes":[],"members":[]}}
1502816287509 => {"id":"230","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart":{"type":"add","content":"import 'dart:async';\nimport '
1502816287509 => {"id":"231","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","offset":6817,"length":0},"clientRequestTime":1502816287509}
1502816287514 <= {"id":"230","result":{}}
1502816287514 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1502816287523 => {"id":"232","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","offset":6817,"length":0},"clientRequestTime":1502816287523}
1502816287557 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","errors":[{"severity":"ERROR","type":"STATIC_TYPE_WARNING","location":{"file
1502816287558 <= {"id":"231","result":{"assists":[]}}
1502816287559 <= {"id":"232","result":{"assists":[]}}
1502816287568 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN
1502816287569 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"length":
1502816287569 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","overrides":[]}}
1502816287571 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1502816287571 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","classes":[],"members":[]}}
1502816287593 => {"id":"233","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart":{"type":"add","content":"import 'dart:async';\nimport '
1502816287593 => {"id":"234","method":"completion.getSuggestions","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","offset":6818},"clientRequestTime":1502816287593}
1502816287595 <= {"id":"233","result":{}}
1502816287595 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1502816287599 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"UnimplementedError: UnmatchedToken\n#0      translateErrorToken (package:front_end/src/s
```

**Comment by bwilkerson** [comment]
@danrubel

**Comment by danrubel** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/02ce5106012a447d431c7f2cb03d9307155bf8a2 ... See https://github.com/dart-lang/sdk/issues/30320

**Comment by kevmoo** [comment]
Duplicate of #30320
