### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by Bikeman868** [dart-lang/sdk#30443]
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Opened VS Code

### Request

While responding to request: `analysis.setAnalysisRoots`

### Versions

- Dart SDK 1.24.2
- Visual Studio Code 1.14.2
- Dart Code 2.3.5

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=2.3.5
```

### Exception

NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName

```text
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      PluginWatcher._getSdkPath (package:analysis_server/src/plugin/plugin_watcher.dart:134)
#3      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:54)
#4      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:1447)
#5      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:300)
#6      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:167)
#7      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1958)
#8      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1198)
#9      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1241)
#10     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:892)
#11     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:1316)
#12     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:323)
#13     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:253)
#14     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:975)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#16     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:971)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     _CustomZone.runGuarded (dart:async/zone.dart:901)
#20     runZoned (dart:async/zone.dart:1465)
#21     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:970)
#22     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:168)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:159)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#26     _rootRunUnary (dart:async/zone.dart:1128)
#27     _CustomZone.runUnary (dart:async/zone.dart:1012)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#37     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#38     _rootRunUnary (dart:async/zone.dart:1128)
#39     _CustomZone.runUnary (dart:async/zone.dart:1012)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#46     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#47     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#48     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#49     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#50     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#51     _rootRunUnary (dart:async/zone.dart:1128)
#52     _CustomZone.runUnary (dart:async/zone.dart:1012)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#56     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#57     _StreamController._add (dart:async/stream_controller.dart:667)
#58     _StreamController.add (dart:async/stream_controller.dart:613)
#59     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#60     _rootRunUnary (dart:async/zone.dart:1132)
#61     _CustomZone.runUnary (dart:async/zone.dart:1012)
#62     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#63     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#64     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#65     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#66     _StreamController._add (dart:async/stream_controller.dart:667)
#67     _StreamController.add (dart:async/stream_controller.dart:613)
#68     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#69     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#70     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#71     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#72     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#73     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by bwilkerson** [comment]
My first guess would be that the SDK that DartCode is configured to use might be corrupted. Does the directory being pointed at contain either the file `_internal/libraries.dart` or `_internal/sdk_library_metadata/lib/libraries.dart`?

**Comment by Bikeman868** [comment]
You were right, my SDK does not contain an `_internal` folder at all.
I re-installed the SDK and now everything works.
