### ISSUE TITLE
Cast exception as a result of deserialization

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30471]
This exception was reported through silo.

Based on the stack trace, it appears that we have a function type whole `element` is a `MethodElementHandle`, but that when we re-synthesize the method element it is a constructor element instead. The library being analyzed (which might be different than the library defining the constructor being deserialized) consisted of a single compilation unit in which there was a single class (with two annotations), and the class defined a single, unnamed, constructor (and no other members).

```
type 'ConstructorElementImpl' is not a subtype of type 'MethodElement' in type cast where
  ConstructorElementImpl is from package:analyzer/src/dart/element/element.dart
  MethodElement is from package:analyzer/dart/element/element.dart

#0      Object._as (dart:core-patch/object_patch.dart:72)
#1      MethodElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:894)
#2      ExecutableElementHandle.returnType (package:analyzer/src/dart/element/handle.dart:511)
#3      FunctionTypeImpl.baseReturnType (package:analyzer/src/dart/element/type.dart:434)
#4      FunctionTypeImpl.returnType (package:analyzer/src/dart/element/type.dart:625)
#5      UnknownInferredType.isUnknown (package:analyzer/src/generated/type_system.dart:1644)
#6      UnknownInferredType.isKnown (package:analyzer/src/generated/type_system.dart:1633)
#7      _GenericInferrer._chooseTypeFromConstraints (package:analyzer/src/generated/type_system.dart:1905)
#8      _GenericInferrer._inferTypeParameterFromContext (package:analyzer/src/generated/type_system.dart:2011)
#9      _GenericInferrer.infer (package:analyzer/src/generated/type_system.dart:1784)
#10     StrongTypeSystemImpl.inferGenericFunctionOrType (package:analyzer/src/generated/type_system.dart:312)
#11     StaticTypeAnalyzer.inferListType (package:analyzer/src/generated/static_type_analyzer.dart:192)
#12     ResolverVisitor.visitListLiteral (package:analyzer/src/generated/resolver.dart:5907)
#13     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7090)
#14     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11054)
#15     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5995)
#16     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4594)
#17     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3224)
#18     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:7558)
#19     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:6124)
#20     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11048)
#21     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#22     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11150)
#23     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5995)
#24     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4594)
#25     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228)
#26     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:6152)
#27     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11144)
#28     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4369)
#29     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5995)
#30     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4594)
#31     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:3011)
#32     ResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:5620)
#33     PartialResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:4589)
#34     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4364)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#36     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:7096)
#37     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7073)
#38     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5337)
#39     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1906)
#40     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5403)
#41     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#42     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:561)
#43     LibraryAnalyzer._analyze.anonymous closure (package:analyzer/src/dart/analysis/library_analyzer.dart:96)
#44     _HashVMBase\u0026MapMixin\u0026\u0026_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#45     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:95)
#46     LibraryAnalyzer.analyze.\u003canonymous closure\u003e (package:analyzer/src/dart/analysis/library_analyzer.dart:64)
#47     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#48     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:63)
#49     AnalysisDriver._computeAnalysisResult.anonymous closure (package:analyzer/src/dart/analysis/driver.dart:1075)
#50     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#51     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1063)
#52     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:900)

asynchronous suspension
#53     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1615)

asynchronous suspension
#54     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1558)
#55     new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#56     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#57     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#58     Driver.start.anonymous closure (package:analysis_server/src/server/driver.dart:434)
#59     _rootRun (dart:async/zone.dart:1120)
#60     _CustomZone.run (dart:async/zone.dart:1001)
#61     runZoned (dart:async/zone.dart:1467)
#62     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:473)
#63     Driver.start (package:analysis_server/src/server/driver.dart:433)

asynchronous suspension
#65     _startIsolate.anonymous closure (dart:isolate-patch/isolate_patch.dart:263)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by scheglov** [comment]
I was unable to reproduce this :-(

**Comment by bwilkerson** [comment]
I'm assuming that this is stale.
