### ISSUE TITLE
dartk test failure standalone/io/file_system_watcher_test - Too many open files

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30528]
```
FAILED: dartk-vm-checked release_x64 standalone/io/file_system_watcher_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
Unhandled exception:
FileSystemException: Failed to initialize file system entity watcher (OS Error: Too many open files, errno = 24)
#0      testWatchCreateFile.<anonymous closure> (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/standalone/io/file_system_watcher_test.dart:29:5)
#1      _RootZone.runUnaryGuarded (patched_sdk/lib/async/zone.dart:1307:17)
#2      _BufferingStreamSubscription._sendError.sendError (patched_sdk/lib/async/stream_impl.dart:352:15)
#3      _BufferingStreamSubscription._sendError (patched_sdk/lib/async/stream_impl.dart:368:16)
#4      _DelayedError.perform (patched_sdk/lib/async/stream_impl.dart:597:14)
#5      _StreamImplEvents.handleNext (patched_sdk/lib/async/stream_impl.dart:702:11)
#6      _PendingEvents.schedule.<anonymous closure> (patched_sdk/lib/async/stream_impl.dart:662:7)
#7      _microtaskLoop (patched_sdk/lib/async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (patched_sdk/lib/async/schedule_microtask.dart:50:5)
#9      _runPendingImmediateCallback (dart:isolate:1083:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate:1133:5)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/ReleaseX64/patched_sdk --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/aam/p/d/dart-sdk/sdk/.packages /usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/standalone/io/file_system_watcher_test.dart
Took 0:00:02.057475

Short reproduction command (experimental):
    python tools/test.py -m release -c dartk --checked standalone/io/file_system_watcher_test

```

**Comment by aam** [comment]
Fixed by raising max number of open handles on my machine to 64000.
