### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by ram6ler** [dart-lang/sdk#30545]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Defining a function with an argument of type `Map<String, bool Function(dynamic)>`. (The exceptions appears to be due to the `bool Function(dynamic)`.)

### Versions

- Dart SDK 1.24.2
- Visual Studio Code 1.15.1
- Dart Code 2.4.0

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=2.4.0
```

### Exception

Captured exception

```text
NoSuchMethodError: The getter 'beginToken' was called on null.
Receiver: null
Tried calling: beginToken
#0      Driver._captureExceptions.<anonymous closure> (package:analysis_server/src/server/driver.dart:502)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:981)
#2      _Future._propagateToListeners (dart:async/future_impl.dart:552)
#3      _Future._completeError (dart:async/future_impl.dart:486)
#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#5      _Completer.completeError (dart:async/future_impl.dart:27)
#6      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:909)
#7      new Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#8      _rootRun (dart:async/zone.dart:1116)
#9      _CustomZone.run (dart:async/zone.dart:1001)
#10     _CustomZone.runGuarded (dart:async/zone.dart:901)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     _CustomZone.runGuarded (dart:async/zone.dart:901)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
<asynchronous suspension>
#21     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#22     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#23     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#24     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#25     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#26     _rootRun (dart:async/zone.dart:1120)
#27     _CustomZone.run (dart:async/zone.dart:1001)
#28     runZoned (dart:async/zone.dart:1467)
#29     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#30     Driver.start (package:analysis_server/src/server/driver.dart:473)
#31     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analysis_server/bin/server.dart:12)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
I believe that this has been fixed, but that the fix has not yet made it into a stable build. If you want to use the new function type syntax, I would recommend that you move to the latest 0.25.0 dev build.
