### ISSUE TITLE
list_concurrent_modify_test crash with dart2js-with-kernel 

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#30559]
```
FAILED: dart2js-d8 release_x64 corelib_2/list_concurrent_modify_test
Expected: RuntimeError 
Actual: Crash
Unexpected compile-time error.
CommandOutput[dart2js]:

stdout:
patched_dart2js_sdk/lib/core/iterator.dart@1733+1:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (1.25.0-edge.86918d713b9bef9a3cfd1190ebbd293e3473ade4), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'thisLocal' was called on null.
Receiver: null
Tried calling: thisLocal
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      LocalsHandler.startFunction (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/locals_handler.dart:245)
#3      KernelSsaGraphBuilder.openFunction (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:824)
#4      KernelSsaGraphBuilder.buildFunctionNode (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:687)
#5      KernelSsaGraphBuilder.build.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:149)
#6      CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:1111)
#7      KernelSsaGraphBuilder.build (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:134)
#8      KernelSsaBuilder.build (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:110)
#9      SsaBuilderTask.build (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/ssa.dart:84)
#10     SsaFunctionCompiler.compile (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/ssa.dart:43)
#11     JavaScriptBackend.codegen (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/js_backend/backend.dart:890)
#12     KernelCodegenWorkItem.run (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:78)
#13     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:752)
#14     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#15     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:752)
#16     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#17     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:750)
#18     CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:1111)
#19     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:748)
#20     EnqueuerStrategy.processWorkItem (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/enqueue.dart:510)
#21     CodegenEnqueuer.forEach (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:224)
#22     Compiler.emptyQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:744)
#23     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#24     Compiler.emptyQueue (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:743)
#25     Compiler.processQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:767)
#26     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#27     Compiler.processQueue (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:762)
#28     Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:626)
#29     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#30     Compiler.compileLoadedLibraries (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:518)
#31     Compiler.runInternal (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:473)
<asynchronous suspension>
#32     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:303)
#33     new Future.sync (dart:async/future.dart:222)
#34     Compiler.run.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:303)
#35     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:176)
#36     Compiler.run (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:300)
#37     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/apiimpl.dart:265)
#38     _RootZone.runUnary (dart:async/zone.dart:1371)
#39     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#40     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#41     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#42     _Future._completeWithValue (dart:async/future_impl.dart:478)
#43     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)



Command[dart2js]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --minify --use-kernel --packages=/b/build/slave/dart2js-linux-d8-minified-5-5-be/build/sdk/.packages /b/build/slave/dart2js-linux-d8-minified-5-5-be/build/sdk/tests/corelib_2/list_concurrent_modify_test.dart --out=/b/build/slave/dart2js-linux-d8-minified-5-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_corelib_2_list_concurrent_modify_test/out.js
Took 0:00:01.361492

Command[d8]: DART_CONFIGURATION=ReleaseX64 /b/build/slave/dart2js-linux-d8-minified-5-5-be/build/sdk/third_party/d8/linux/d8 out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js /b/build/slave/dart2js-linux-d8-minified-5-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_corelib_2_list_concurrent_modify_test/out.js
Did not run

Short reproduction command (experimental):
    python tools/test.py -m release -c dart2js -r d8 --minified --dart2js-with-kernel --use-sdk --dart2js-batch --reset-browser-configuration corelib_2/list_concurrent_modify_test
```

Updating the status file for now.

**Comment by sigmundch** [comment]
Thanks @jensjoha!

Since the `--dart2js-with-kernel` is still in a partial state, feel free to directly update the .status files without filling a bug if you like - We are currently periodically going through the .status file and triaging issues as we make progress.

**Comment by rakudrama** [comment]
I'm going to do a bit of status file maintenance and move the status file update into the block of issues we are working on.
We will track this issue as part of the regular --use-kernel effort
