### ISSUE TITLE
Dart Analyzer crashes

### ISSUE THREAD

**Issue by michschn** [dart-lang/sdk#30578]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.70`
- `trunk google3`
- `IU-171.4694.70, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-87-generic unknown, screens 3840x2160, 1200x1920`

# Exception

Please append the contents of:
file:///tmp/report.txt
contact michschn@google.com instead.

```
Dart analysis server, SDK version trunk google3, server version 1.18.4, error: Captured exception
NoSuchMethodError: The getter 'className' was called on null.
Receiver: null
Tried calling: className
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      DirectiveLinker.resynthesizeDirectives (package:angular_analyzer_plugin/src/directive_linking.dart:59)
<asynchronous suspension>
#3      AngularDriver.resynthesizeDirectives (package:angular_analyzer_plugin/src/angular_driver.dart:707)
<asynchronous suspension>
#4      AngularDriver.getAngularAnnotatedClasses (package:angular_analyzer_plugin/src/angular_driver.dart:740)
<asynchronous suspension>
#5      AngularDriver.resolveDart (package:angular_analyzer_plugin/src/angular_driver.dart:599)
<asynchronous suspension>
#6      AngularDriver.pushDartErrors (package:angular_analyzer_plugin/src/angular_driver.dart:551)
<asynchronous suspension>
#7      AngularDriver.performWork (package:angular_analyzer_plugin/src/angular_driver.dart:240)
<asynchronous suspension>
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1615)
<asynchronous suspension>
#9      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1558)
#10     new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#11     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)

**Comment by zoechi** [comment]
@MichaelRFairhurst there is a similar error in #34224
You closed this issue without a reference to a PR. 
Any memory about what solved it?
