### ISSUE TITLE
async/await rewritter introduces name conflicts

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30585]
We seem to have an issue in how we create local variables in the async/await rewrite.

Even though we use `freshName` to create the name for `errorCode` [here](https://github.com/dart-lang/sdk/blob/9efd55d531348622fd957b017efc50f087a2a340/pkg/compiler/lib/src/js/rewrite_async.dart#L201), we seem to get conflicts if the name matches the enclosing function name.

Here is a repro:
```dart
import 'dart:async';
  
Future main() async {
  try {
    await errorCode();
  } catch (e, s) {
    print('YES - we caught the error here: $e $s');
  }
}

Future errorCode() async {
  // If we throw here, it will be caught
  // throw 'test error';
  await errorCodeDeep();
}

Future errorCodeDeep() async {
  throw 'test error';
}
```

This produces this error in d8:
```
sdk/lib/_internal/js_runtime/lib/preambles/d8.js:255: NoSuchMethodError: method not found: 'call$2' (this.bodyFunction.call$2 is not a function)
          throw e;
          ^
TypeError: this.bodyFunction.call$2 is not a function
    at _awaitOnObject_closure0.call$2 (out.js:3462:27)
    at _RootZone.runBinary$3 (out.js:3972:20)
    at _FutureListener.handleError$1 (out.js:3524:21)
    at _Future__propagateToListeners_handleError.call$0 (out.js:3879:42)
    at Object._Future__propagateToListeners (out.js:3735:92)
    at _Future._completeError$2 (out.js:3641:11)
    at _SyncCompleter._completeError$2 (out.js:3494:21)
    at _SyncCompleter.completeError$2 (out.js:3482:14)
    at Object._asyncRethrow (out.js:3238:17)
    at out.js:4990:20
```

If you rename "errorCode" to "errorCode2", then you get the expected behavior instead:
```
YES - we caught the error here: test error test error
    at Object.wrapException (out.js:1977:17)
    at out.js:4995:23
    at _wrapJsFunctionForAsync_closure.$protected (out.js:3261:15)
    at _wrapJsFunctionForAsync_closure.call$2 (out.js:3468:14)
    at _awaitOnObject_closure.call$1 (out.js:3456:34)
    at _RootZone.runUnary$2 (out.js:3967:20)
    at _FutureListener.handleValue$1 (out.js:3512:34)
    at _Future__propagateToListeners_handleValueCallback.call$0 (out.js:3860:60)
    at Object._Future__propagateToListeners (out.js:3733:108)
    at _Future__addListener_closure.call$0 (out.js:3776:11)
```

**Comment by sigmundch** [comment]
The issue is that we have conflicts between the name of the function and the arguments passed when creating the state machine:

```js
var $async$errorCode = P._wrapJsFunctionForAsync(function($async$errorCode, $async$result) {                                                                        
```

Similar to `errorCode` here is a simpler examples that causes issue with the `result` argument:
```dart
import 'dart:async';
  
Future main() => result();
Future result() async {
  await new Future((){});
}
```
