### ISSUE TITLE
Exception in analyzer search engine

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30599]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-172.3757.52`
- `1.25.0-edge.2f4919852095ee3287d35e138184c11e29b3ce8d`
- `IC-172.3757.52, JRE 1.8.0_152-release-915-b10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/00/0w95r000h01000cxqpysvccm003j4q/T/report1.txt

```
Dart analysis server, SDK version 1.25.0-edge.2f4919852095ee3287d35e138184c11e29b3ce8d, server version 1.18.4, error: Failed to send analysis.implemented notification.
NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains("ClassMemberParserTest_Fasta")
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      Search.subtypes (package:analyzer/src/dart/analysis/search.dart:144)
<asynchronous suspension>
#3      SearchEngineImpl.membersOfSubtypes.addMembers (package:analysis_server/src/services/search/search_engine_internal.dart:37)
<asynchronous suspension>
#4      SearchEngineImpl.membersOfSubtypes.addMembers (package:analysis_server/src/services/search/search_engine_internal.dart:43)
<asynchronous suspension>
#5      SearchEngineImpl.membersOfSubtypes.addMembers (package:analysis_server/src/services/search/search_engine_internal.dart:43)
<asynchronous suspension>
#6      SearchEngineImpl.membersOfSubtypes (package:analysis_server/src/services/search/search_engine_internal.dart:48)
<asynchronous suspension>
#7      ImplementedComputer.compute (package:analysis_server/src/domains/analysis/implemented_dart.dart:32)
<asynchronous suspension>
#8      scheduleImplementedNotification (package:analysis_server/src/operation/operation_analysis.dart:33)
<asynchronous suspension>

**Comment by bwilkerson** [comment]
@scheglov Has this changed recently? I can guard against a null return from `subtypedNames`, or I can always return an empty list, but it seems like this might indicate a deeper issue.

**Comment by scheglov** [comment]
This has the same reason as other `FileState` related NPEs - we were unable to decode invalid, truncated, zero size summary file. Once this is fixed, the NPEs will get fixed too.

**Comment by bwilkerson** [comment]
This appears to have been user error.
