### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by kharland** [dart-lang/sdk#30605]
### What I was doing

Editing a file in VsCode.  I am using the Dart Code plugin for VsCode v 2.4.0.  The only other significant content in the editor console are a few hints that I am calling a member annotated with "@protected" outside of a subclass or instance method.

### Versions

- Dart SDK 1.24.2
- Visual Studio Code 1.15.1
- Dart Code 2.4.0

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=2.4.0
```

### Exception

Analysis failed: /Users/kjharland/Code/projects/distributed/pkg/distributed_ipc/lib/src/vm/vm_node_connection.dart

```text
NoSuchMethodError: Class 'GenericTypeAliasElementForLink' has no instance getter 'returnType'.
Receiver: Instance of 'GenericTypeAliasElementForLink'
Tried calling: returnType
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      GenericTypeAliasElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3318)
#3      FunctionTypeImpl.baseReturnType (package:analyzer/src/dart/element/type.dart:435)
#4      FunctionTypeImpl.returnType (package:analyzer/src/dart/element/type.dart:626)
#5      FunctionTypeImpl.== (package:analyzer/src/dart/element/type.dart:729)
#6      TypeImpl.equalArrays (package:analyzer/src/dart/element/type.dart:2631)
#7      FunctionTypeImpl.== (package:analyzer/src/dart/element/type.dart:730)
#8      InheritanceManager._unionInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:893)
#9      InheritanceManager._computeInterfaceLookupMap (package:analyzer/src/dart/resolver/inheritance_manager.dart:455)
#10     InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:496)
#11     InheritanceManager.lookupOverrides (package:analyzer/src/dart/resolver/inheritance_manager.dart:205)
#12     InstanceMemberInferrer._inferExecutable (package:analyzer/src/task/strong_mode.dart:370)
#13     InstanceMemberInferrer._inferClass.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:333)
#14     List.forEach (dart:core-patch/growable_array.dart:256)
#15     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:332)
#16     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:107)
#17     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1302)
#18     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3672)
#19     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3408)
#20     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3330)
#21     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#22     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#23     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3373)
#24     Linker.link (package:analyzer/src/summary/link.dart:3897)
#25     relink (package:analyzer/src/summary/link.dart:132)
#26     link (package:analyzer/src/summary/link.dart:113)
#27     new LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:116)
#28     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#29     new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:115)
#30     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#31     new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:53)
#32     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1092)
#33     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:989)
#34     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#35     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#36     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:834)
<asynchronous suspension>
#37     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#38     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#39     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#40     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#41     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#42     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#43     _rootRun (dart:async/zone.dart:1120)
#44     _CustomZone.run (dart:async/zone.dart:1001)
#45     runZoned (dart:async/zone.dart:1467)
#46     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#47     Driver.start (package:analysis_server/src/server/driver.dart:473)
#48     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analysis_server/bin/server.dart:12)
#49     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by kevmoo** [comment]
@jcollins-g – this feels like an issue we're seeing w/ dartdoc + Flutter, right?

**Comment by DanTup** [comment]
Just noticed this in my dev console today too while working on Dart Code. This is just it parsing the tiny sample projects inside Dart Code used for my integration tests.

> Analysis failed: /Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world/test/broken_test.dart context: exception_20180607_074533_361

 Here's an exception file from the server if it helps:

[exception_20180607_074533_361.zip](https://github.com/dart-lang/sdk/files/2079496/exception_20180607_074533_361.zip)

(it looks like the same error was reported for a lot of files, so I don't think it's specific to `broken_test.dart`).

**Comment by DanTup** [comment]
Oh hangon, that might be useless; this workspace is using Dart v1 server from my PATH! ...

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
