### ISSUE TITLE
Analyzer creates formal parameter with all null fields

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30600]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-172.3757.52`
- `1.25.0-edge.2f4919852095ee3287d35e138184c11e29b3ce8d`
- `IC-172.3757.52, JRE 1.8.0_152-release-915-b10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/00/0w95r000h01000cxqpysvccm003j4q/T/report.txt

```
Dart analysis server, SDK version 1.25.0-edge.2f4919852095ee3287d35e138184c11e29b3ce8d, server version 1.18.4, error: Analysis failed: /Users/brianwilkerson/src/dart/sdk/sdk/tests/language_2/void_type_function_types_test.dart
NoSuchMethodError: The getter 'beginToken' was called on null.
Receiver: null
Tried calling: beginToken
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      SimpleFormalParameterImpl.beginToken (package:analyzer/src/dart/ast/ast.dart:9202)
#3      AstNodeImpl.offset (package:analyzer/src/dart/ast/ast.dart:949)
#4      _SummarizeAstVisitor.serializeCodeRange (package:analyzer/src/summary/summarize_ast.dart:487)
#5      _SummarizeAstVisitor.serializeParameter (package:analyzer/src/summary/summarize_ast.dart:799)
#6      _SummarizeAstVisitor.visitSimpleFormalParameter (package:analyzer/src/summary/summarize_ast.dart:1346)
#7      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9228)
#8      _SummarizeAstVisitor.serializeGenericFunctionType.<anonymous closure> (package:analyzer/src/summary/summarize_ast.dart:764)
#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#10     ListIterable.toList (dart:_internal/iterable.dart:218)
#11     _SummarizeAstVisitor.serializeGenericFunctionType (package:analyzer/src/summary/summarize_ast.dart:765)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
