### ISSUE TITLE
git cl presumbit crashes.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30630]
@sortie 
When trying to upload the CL https://dart-review.googlesource.com/c/sdk/+/3460 the presubmit crashes with the error below.
This is on Windows using the depot tools git (and probably python).

It's possibly caused by the files containing raw non-ASCII characters.

I used --bypass-hooks to overcome the problem (since it's a clean revert, it "should be safe").

```
λ git cl presubmit
Running presubmit commit checks ...
Traceback (most recent call last):
  File "c:\src\depot_tools\\git_cl.py", line 6112, in <module>
    sys.exit(main(sys.argv[1:]))
  File "c:\src\depot_tools\\git_cl.py", line 6094, in main
    return dispatcher.execute(OptionParser(), argv)
  File "c:\src\depot_tools\subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "c:\src\depot_tools\\git_cl.py", line 4746, in CMDpresubmit
    change=cl.GetChange(base_branch, None))
  File "c:\src\depot_tools\\git_cl.py", line 1573, in RunHook
    gerrit_obj=self._codereview_impl.GetGerritObjForPresubmit())
  File "c:\src\depot_tools\presubmit_support.py", line 1368, in DoPresubmitChecks
    results += executer.ExecPresubmitScript(presubmit_script, filename)
  File "c:\src\depot_tools\presubmit_support.py", line 1262, in ExecPresubmitScript
    gerrit_obj=self.gerrit, dry_run=self.dry_run)
  File "c:\src\depot_tools\presubmit_support.py", line 451, in __init__
    self.cpu_count, _capture_interrupt)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\multiprocessing\__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\multiprocessing\pool.py", line 159, in __init__
    self._repopulate_pool()
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\multiprocessing\pool.py", line 222, in _repopulate_pool
    w.start()
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 562, in save_tuple
    save(element)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 748, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <function _capture_interrupt at 0x031078B0>: it's not found as presubmit_support._capture_interrupt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

**Comment by lrhn** [comment]
TBR

**Comment by lrhn** [comment]
Update: It's not just that CL, I have the same problem with https://dart-review.googlesource.com/c/sdk/+/3620 - which has no fancy non-ASCII characters. So far two out of two CL's fail to run presubmit on Windows.

**Comment by athomas** [comment]
I believe those issues have been fixed.
