### ISSUE TITLE
DDC async functions are not named in generated JS

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#30640]
Related to #30634 and #30636.

```dart
import 'dart:async';

Future foo() async {
  throw new Exception('foo error');
}

Future main() async {
  await foo();
}
```

results in:

```
Error
    at dart.throw (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:5062:27)
    at /Users/vsm/ddctest/stacktest4.js:11:15
```

I.e., async function names are lost.

**Comment by jmesserly** [comment]
This one should be a really easy fix, we can just keep the name on the `function*`

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/4121
