### ISSUE TITLE
Analyzer crash – messing with angular plugin

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#30641]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.23`
- `1.25.0-dev.16.0`
- `IU-171.4694.23, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 2560x1600`

# Exception

Please append the contents of:
file:///private/var/folders/bj/09dxmvxx5hl4t07lbvqgj66w0071_k/T/report.txt

```
Dart analysis server, SDK version 1.25.0-dev.16.0, server version 1.18.4, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [/Users/kevmoo/source/github/gwt_mail_sample], excluded: [/Users/kevmoo/source/github/gwt_mail_sample/.idea, /Users/kevmoo/source/github/gwt_mail_sample/.pub, /Users/kevmoo/source/github/gwt_mail_sample/build]}, clientRequestTime: 1504739051848}
NoSuchMethodError: The getter 'contextRoot' was called on null.
Receiver: null
Tried calling: contextRoot
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      ContextManagerImpl._checkForAnalysisOptionsUpdate (package:analysis_server/src/context_manager.dart:906)
#3      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1411)
#4      _rootRunUnary (dart:async/zone.dart:1128)
#5      _CustomZone.runUnary (dart:async/zone.dart:1012)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#10     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98)
#11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#12     _rootRunUnary (dart:async/zone.dart:1128)
#13     _CustomZone.runUnary (dart:async/zone.dart:1012)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#17     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:379)
#18     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254)
#19     _rootRunUnary (dart:async/zone.dart:1128)
#20     _CustomZone.runUnary (dart:async/zone.dart:1012)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#23     _DelayedData.perform (dart:async/stream_impl.dart:579)
#24     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:695)
#25     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:655)
#26     _rootRun (dart:async/zone.dart:1116)
#27     _CustomZone.run (dart:async/zone.dart:1001)
#28     _CustomZone.runGuarded (dart:async/zone.dart:901)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#30     _rootRun (dart:async/zone.dart:1120)
#31     _CustomZone.run (dart:async/zone.dart:1001)
#32     _CustomZone.runGuarded (dart:async/zone.dart:901)
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#36     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:376)
#37     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:401)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

```
1504739041993 => {"id":"6","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/gwt_mail_sample/web/main.dart","offset":239,"length":0},"clientRequestTime":1504739041631}
1504739041995 <= {"id":"1"}
1504739041998 <= {"id":"2"}
1504739042022 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1504739042028 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1504739042126 => {"id":"7","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/gwt_mail_sample/web/main.dart","offset":326,"length":0},"clientRequestTime":1504739042126}
1504739042148 <= {"id":"3","error":{"code":"SERVER_ERROR","message":"NoSuchMethodError: The getter 'fullName' was called on null.\nReceiver: null\nTried calling: fullName","stackTrace":"#0      Object
1504739042151 <= {"id":"4"}
1504739042159 <= {"id":"5"}
1504739042171 <= {"id":"6","result":{"assists":[]}}
1504739042171 <= {"id":"7","result":{"assists":[]}}
1504739046249 => {"id":"8","method":"analysis.setPriorityFiles","params":{"files":[]},"clientRequestTime":1504739046249}
1504739046249 => {"id":"9","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":[],"OVERRIDES":[],"NAVIGATION":[],"IMPLEMENTED":[]}},"clientRequestTime":1504739046249}
1504739046251 <= {"id":"8"}
1504739046252 <= {"id":"9"}
1504739051794 => {"id":"10","method":"server.shutdown","clientRequestTime":1504739051794}
1504739051797 <= {"id":"10"}
1504739051842 started analysis server:
  /Users/kevmoo/homebrew/opt/dart/libexec/bin/dart /Users/kevmoo/homebrew/opt/dart/libexec/bin/snapshots/analysis_server.dart.snapshot --client-id=IntelliJ-IDEA --client-version=IU-171.4694.23 --useAn
1504739052153 <= {"event":"server.connected","params":{"version":"1.18.4","pid":37461,"sessionId":""}}
1504739052181 <= {"id":"0","result":{"version":"1.18.4"}}
1504739052181 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1504739051847}
1504739052181 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1504739052182 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["/Users/kevmoo/source/github/gwt_mail_sample"],"excluded":["/Users/kevmoo/source/github/gwt_mail_sample/.idea","/U
1504739052186 <= {"id":"1"}
1504739052189 <= {"id":"2"}
1504739052225 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1504739052237 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1504739052388 <= {"id":"3","error":{"code":"SERVER_ERROR","message":"NoSuchMethodError: The getter 'fullName' was called on null.\nReceiver: null\nTried calling: fullName","stackTrace":"#0      Object
1504739131839 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [/Users/kevmoo/source/github/gwt_ma
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/6262
