### ISSUE TITLE
Flaky dart-sdk build

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#30642]
The dart-sdk build has been failing a couple of times today and then succeeds on a following run without intervention. See for example https://uberchromegw.corp.google.com/i/client.dart/builders/dart-sdk-mac-be/builds/16237/steps/generate%20sdks/logs/stdio

Here are 3 examples of the same failure on 3 different runs:

Run 1:
[...]
[1726/1957] CC obj/third_party/boringssl/boringssl/v3_genn.o
[1727/1957] CC obj/third_party/boringssl/boringssl/v3_ia5.o
[1728/1957] CC obj/third_party/boringssl/boringssl/v3_cpols.o
FAILED: obj/third_party/boringssl/boringssl/v3_cpols.o 
../../buildtools/mac-x64/clang/bin/clang -MMD -MF obj/third_party/boringssl/boringssl/v3_cpols.o.d -DTOOLCHAIN_VERSION=81fd7fe3a7666a212d95a42541228bb1c8fb7ec3 -DNDEBUG -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -DOPENSSL_SMALL -D_XOPEN_SOURCE=700 -I../.. -Igen -I../../third_party/boringssl/src/include -isysroot /Applications/Xcode7.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.8  -fno-exceptions -arch i386 -fcolor-diagnostics -stdlib=libc++ -Wheader-hygiene -Wstring-conversion -O3 -fno-ident -fdata-sections -ffunction-sections -g3 -ggdb3 -Wendif-labels -Wno-missing-field-initializers -Wno-unused-parameter -Wpartial-availability -std=c99 -std=c99 -c ../../third_party/boringssl/src/crypto/x509v3/v3_cpols.c -o obj/third_party/boringssl/boringssl/v3_cpols.o
clang-6.0: error: unable to execute command: Segmentation fault: 11
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
Fuchsia clang version 6.0.0 (/b/s/w/ir/cache/git/fuchsia.googlesource.com-third_party-clang ccfbe4353febc886ae0b5864afb3d9c5d4838077) (/b/s/w/ir/cache/git/fuchsia.googlesource.com-third_party-llvm 7d9adf93462bf014ded85852beb1c4de402c808b) (based on LLVM 6.0.0git-7d9adf93462git-7d9adf93462)
Target: i386-apple-darwin15.4.0
Thread model: posix
InstalledDir: /b/build/slave/dart-sdk-mac-be/build/sdk/xcodebuild/ReleaseIA32/../../buildtools/mac-x64/clang/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6.0: note: diagnostic msg: /var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/v3_cpols-8217aa.c
clang-6.0: note: diagnostic msg: /var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/v3_cpols-8217aa.sh
clang-6.0: note: diagnostic msg: Crash backtrace is located in
clang-6.0: note: diagnostic msg: /Users/chrome-bot/Library/Logs/DiagnosticReports/clang-6.0_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang-6.0: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang-6.0: note: diagnostic msg: 

********************
[1729/1957] CC obj/third_party/boringssl/boringssl/v3_int.o
[1730/1957] CC obj/third_party/boringssl/boringssl/v3_crld.o
[1731/1957] CC obj/third_party/boringssl/boringssl/v3_info.o
[1732/1957] CC obj/third_party/boringssl/boringssl/x509_vfy.o
[1733/1957] CC obj/third_party/boringssl/boringssl/v3_lib.o
[1734/1957] CC obj/third_party/boringssl/boringssl/v3_pci.o
[1735/1957] CC obj/third_party/boringssl/boringssl/v3_ncons.o
[1736/1957] CXX obj/runtime/vm/libdart_vm_nosnapshot_with_precompiler/kernel_binary_flowgraph.o
[1737/1957] ACTION //runtime/vm:patched_sdk(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
BUILD FAILED
!@@@STEP_FAILURE@@@
Traceback (most recent call last):
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 235, in <module>
    CreateUploadSDK()
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 112, in CreateUploadSDK
    BuildSDK()
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 30, in BuildSDK
    '--arch=ia32', 'create_sdk'])
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 224, in Run
    return bot.RunProcess(command, env=env)
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/bot.py", line 286, in RunProcess
    raise OSError(exit_code)
OSError: 1
step returned non-zero exit code: 1
@@@STEP_FAILURE@@@

--------------------------------------------------------------------------------
started: Wed Sep  6 06:16:13 2017
ended: Wed Sep  6 06:18:09 2017
duration: 1 mins, 55 secs
status: FAILURE
status reason: 

Run2:
[...]
[1726/1957] CC obj/third_party/boringssl/boringssl/v3_ia5.o
[1727/1957] CC obj/third_party/boringssl/boringssl/v3_genn.o
[1728/1957] CC obj/third_party/boringssl/boringssl/v3_cpols.o
FAILED: obj/third_party/boringssl/boringssl/v3_cpols.o 
../../buildtools/mac-x64/clang/bin/clang -MMD -MF obj/third_party/boringssl/boringssl/v3_cpols.o.d -DTOOLCHAIN_VERSION=81fd7fe3a7666a212d95a42541228bb1c8fb7ec3 -DNDEBUG -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -DOPENSSL_SMALL -D_XOPEN_SOURCE=700 -I../.. -Igen -I../../third_party/boringssl/src/include -isysroot /Applications/Xcode7.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.8  -fno-exceptions -arch i386 -fcolor-diagnostics -stdlib=libc++ -Wheader-hygiene -Wstring-conversion -O3 -fno-ident -fdata-sections -ffunction-sections -g3 -ggdb3 -Wendif-labels -Wno-missing-field-initializers -Wno-unused-parameter -Wpartial-availability -std=c99 -std=c99 -c ../../third_party/boringssl/src/crypto/x509v3/v3_cpols.c -o obj/third_party/boringssl/boringssl/v3_cpols.o
clang-6.0: error: unable to execute command: Segmentation fault: 11
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
Fuchsia clang version 6.0.0 (/b/s/w/ir/cache/git/fuchsia.googlesource.com-third_party-clang ccfbe4353febc886ae0b5864afb3d9c5d4838077) (/b/s/w/ir/cache/git/fuchsia.googlesource.com-third_party-llvm 7d9adf93462bf014ded85852beb1c4de402c808b) (based on LLVM 6.0.0git-7d9adf93462git-7d9adf93462)
Target: i386-apple-darwin15.4.0
Thread model: posix
InstalledDir: /b/build/slave/dart-sdk-mac-be/build/sdk/xcodebuild/ReleaseIA32/../../buildtools/mac-x64/clang/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6.0: note: diagnostic msg: /var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/v3_cpols-e892e0.c
clang-6.0: note: diagnostic msg: /var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/v3_cpols-e892e0.sh
clang-6.0: note: diagnostic msg: Crash backtrace is located in
clang-6.0: note: diagnostic msg: /Users/chrome-bot/Library/Logs/DiagnosticReports/clang-6.0_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang-6.0: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang-6.0: note: diagnostic msg: 

********************
[1729/1957] CC obj/third_party/boringssl/boringssl/v3_int.o
[1730/1957] CC obj/third_party/boringssl/boringssl/v3_crld.o
[1731/1957] CC obj/third_party/boringssl/boringssl/v3_info.o
[1732/1957] CC obj/third_party/boringssl/boringssl/x509_vfy.o
[1733/1957] CC obj/third_party/boringssl/boringssl/v3_lib.o
[1734/1957] CC obj/third_party/boringssl/boringssl/v3_pci.o
[1735/1957] CC obj/third_party/boringssl/boringssl/v3_ncons.o
[1736/1957] CXX obj/runtime/vm/libdart_vm_nosnapshot_with_precompiler/kernel_binary_flowgraph.o
[1737/1957] ACTION //runtime/vm:patched_sdk(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
BUILD FAILED
!@@@STEP_FAILURE@@@
Traceback (most recent call last):
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 235, in <module>
    CreateUploadSDK()
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 112, in CreateUploadSDK
    BuildSDK()
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 30, in BuildSDK
    '--arch=ia32', 'create_sdk'])
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 224, in Run
    return bot.RunProcess(command, env=env)
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/bot.py", line 286, in RunProcess
    raise OSError(exit_code)
OSError: 1
step returned non-zero exit code: 1
@@@STEP_FAILURE@@@

--------------------------------------------------------------------------------
started: Wed Sep  6 16:30:08 2017
ended: Wed Sep  6 16:32:05 2017
duration: 1 mins, 56 secs
status: FAILURE
status reason: 

Run 3:
[...]
[1724/1957] CC obj/third_party/boringssl/boringssl/v3_alt.o
[1725/1957] CC obj/third_party/boringssl/boringssl/pcy_tree.o
[1726/1957] CC obj/third_party/boringssl/boringssl/v3_genn.o
[1727/1957] CC obj/third_party/boringssl/boringssl/v3_ia5.o
[1728/1957] CC obj/third_party/boringssl/boringssl/v3_cpols.o
FAILED: obj/third_party/boringssl/boringssl/v3_cpols.o 
../../buildtools/mac-x64/clang/bin/clang -MMD -MF obj/third_party/boringssl/boringssl/v3_cpols.o.d -DTOOLCHAIN_VERSION=81fd7fe3a7666a212d95a42541228bb1c8fb7ec3 -DNDEBUG -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -DOPENSSL_SMALL -D_XOPEN_SOURCE=700 -I../.. -Igen -I../../third_party/boringssl/src/include -isysroot /Applications/Xcode7.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.8  -fno-exceptions -arch i386 -fcolor-diagnostics -stdlib=libc++ -Wheader-hygiene -Wstring-conversion -O3 -fno-ident -fdata-sections -ffunction-sections -g3 -ggdb3 -Wendif-labels -Wno-missing-field-initializers -Wno-unused-parameter -Wpartial-availability -std=c99 -std=c99 -c ../../third_party/boringssl/src/crypto/x509v3/v3_cpols.c -o obj/third_party/boringssl/boringssl/v3_cpols.o
clang-6.0: error: unable to execute command: Segmentation fault: 11
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
Fuchsia clang version 6.0.0 (/b/s/w/ir/cache/git/fuchsia.googlesource.com-third_party-clang ccfbe4353febc886ae0b5864afb3d9c5d4838077) (/b/s/w/ir/cache/git/fuchsia.googlesource.com-third_party-llvm 7d9adf93462bf014ded85852beb1c4de402c808b) (based on LLVM 6.0.0git-7d9adf93462git-7d9adf93462)
Target: i386-apple-darwin15.4.0
Thread model: posix
InstalledDir: /b/build/slave/dart-sdk-mac-be/build/sdk/xcodebuild/ReleaseIA32/../../buildtools/mac-x64/clang/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6.0: note: diagnostic msg: /var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/v3_cpols-8217aa.c
clang-6.0: note: diagnostic msg: /var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/v3_cpols-8217aa.sh
clang-6.0: note: diagnostic msg: Crash backtrace is located in
clang-6.0: note: diagnostic msg: /Users/chrome-bot/Library/Logs/DiagnosticReports/clang-6.0_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang-6.0: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang-6.0: note: diagnostic msg: 

********************
[1729/1957] CC obj/third_party/boringssl/boringssl/v3_int.o
[1730/1957] CC obj/third_party/boringssl/boringssl/v3_crld.o
[1731/1957] CC obj/third_party/boringssl/boringssl/v3_info.o
[1732/1957] CC obj/third_party/boringssl/boringssl/x509_vfy.o
[1733/1957] CC obj/third_party/boringssl/boringssl/v3_lib.o
[1734/1957] CC obj/third_party/boringssl/boringssl/v3_pci.o
[1735/1957] CC obj/third_party/boringssl/boringssl/v3_ncons.o
[1736/1957] CXX obj/runtime/vm/libdart_vm_nosnapshot_with_precompiler/kernel_binary_flowgraph.o
[1737/1957] ACTION //runtime/vm:patched_sdk(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
BUILD FAILED
!@@@STEP_FAILURE@@@
Traceback (most recent call last):
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 235, in <module>
    CreateUploadSDK()
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 112, in CreateUploadSDK
    BuildSDK()
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 30, in BuildSDK
    '--arch=ia32', 'create_sdk'])
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/dart_sdk.py", line 224, in Run
    return bot.RunProcess(command, env=env)
  File "/b/build/slave/dart-sdk-mac-be/build/sdk/tools/bots/bot.py", line 286, in RunProcess
    raise OSError(exit_code)
OSError: 1
step returned non-zero exit code: 1
@@@STEP_FAILURE@@@

--------------------------------------------------------------------------------
started: Wed Sep  6 06:16:13 2017
ended: Wed Sep  6 06:18:09 2017
duration: 1 mins, 55 secs
status: FAILURE
status reason:

**Comment by efortuna** [comment]
We've seen this happen 3 times over the course of the last 24 hours.

Bob mentioned that Bill updated clang not too long ago. Is it perhaps related to that?

**Comment by zanderso** [comment]
@whesse Is there any way to harvest the backtrace file from the buildbot? /Users/chrome-bot/Library/Logs/DiagnosticReports/clang-6.0__.crash

**Comment by zanderso** [comment]
phosek@, who builds our toolchain, has not seen this failure before. I'm going to roll back to the clang 5.0 toolchain first thing tomorrow morning. In the meantime, it would be super helpful if we can get the crash dump for him.

**Comment by zanderso** [comment]
@chinmaygarde FYI in case this also affects Flutter. It looks like our buildbots have uncovered a crasher in the toolchain on Mac.

**Comment by whesse** [comment]
I can't upload the files here, but all three files are uploaded to http://gsdview.appspot.com/dart-archive/channels/be/raw/clang-crash/ and should be downloadable from that address.  This is also a gs:// URL: gs://dart-archive/channels/be/raw/clang-crash/ and the three files are 
gs://dart-archive/channels/be/raw/clang-crash/clang-6.0_2017-09-07-040716_vm683-m3.crash
gs://dart-archive/channels/be/raw/clang-crash/v3_cpols-2786c5.c
gs://dart-archive/channels/be/raw/clang-crash/v3_cpols-2786c5.sh

**Comment by petrhosek** [comment]
Has it only been happening on macOS or did you see that crash on Linux as well?

**Comment by petrhosek** [comment]
I've noticed you're using an older toolchain build `81fd7fe3a7666a212d95a42541228bb1c8fb7ec3`. I don't see the crash with `da06e6b0456f5e3d2bf990c9e0199f0846197949` which is the current build. Would it be possible to roll your toolchain to the latest version?

**Comment by zanderso** [comment]
My suggestion would be to try a roll again after the ia32 ASAN runtime libraries are included. Our buildbots have seen enough red this week already =(

It looks like we were on buildtools 5b8eb38aaf523f0124756454276cd0a5b720c17e, which the Flutter engine is still on. I've rolled back to buildtools 057ef89874e3c622248cf99259434fdc683c4e30, which is probalby quite old, but which is the last version I knew to work.

**Comment by zanderso** [comment]
The toolchain has been rolled back, and @petrhosek and I have discussed when to try rolling forward again, so I'm going to close this issue.
