### ISSUE TITLE
Having a directory called "sdk" next to the actual sdk causes errors

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#30651]
Raised by @jakemac53 at https://github.com/Dart-Code/Dart-Code/issues/421, but I can repro from the command line so I don't think it's Dart Code specific and probably should have an issue here.

(cc @bwilkerson)

--

You can repro this by adding a directory called `sdk` next to your main sdk (for me they were both in my home dir).

You can work around this by renaming the `sdk` dir.

### Request

While responding to request: `analysis.setAnalysisRoots`

### Versions

- Dart SDK 1.25.0-dev.15.0
- Visual Studio Code 1.15.1
- Dart Code 2.4.0

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=2.4.0
```

### Exception

NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName

```text
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      PluginWatcher._getSdkPath (package:analysis_server/src/plugin/plugin_watcher.dart:95)
#3      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:54)
#4      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:1568)
#5      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:325)
#6      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:169)
#7      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1128)
#8      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1095)
#9      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1133)
#10     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:761)
#11     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:865)
#12     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:329)
#13     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:254)
#14     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:694)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#16     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:690)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     _CustomZone.runGuarded (dart:async/zone.dart:901)
#20     runZoned (dart:async/zone.dart:1465)
#21     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:689)
#22     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#26     _rootRunUnary (dart:async/zone.dart:1128)
#27     _CustomZone.runUnary (dart:async/zone.dart:1012)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#37     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#38     _rootRunUnary (dart:async/zone.dart:1128)
#39     _CustomZone.runUnary (dart:async/zone.dart:1012)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#46     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#47     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#48     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#49     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#50     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#51     _rootRunUnary (dart:async/zone.dart:1128)
#52     _CustomZone.runUnary (dart:async/zone.dart:1012)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#56     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#57     _StreamController._add (dart:async/stream_controller.dart:667)
#58     _StreamController.add (dart:async/stream_controller.dart:613)
#59     _Socket._onData (dart:io-patch/socket_patch.dart:1643)
#60     _rootRunUnary (dart:async/zone.dart:1132)
#61     _CustomZone.runUnary (dart:async/zone.dart:1012)
#62     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#63     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#64     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#65     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#66     _StreamController._add (dart:async/stream_controller.dart:667)
#67     _StreamController.add (dart:async/stream_controller.dart:613)
#68     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
#69     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#70     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#71     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#72     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#73     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

Diagnostics requested after the error occurred are:

```js
[]
```

**Comment by DanTup** [comment]
I can repro this quite easily:

- SDK 1.24.2 is at `M:\Apps\Dart\Latest`
- Create empty folder at `M:\Apps\Dart\sdk`
- Run `M:\Apps\Dart\Latest\bin\dart.exe M:\Apps\Dart\Latest\bin\snapshots\analysis_server.dart.snapshot`
- Send `{"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["c:\\Users\\danny\\Desktop\\DartSample"],"excluded":[]}}`

**Comment by alexander-doroshko** [comment]
@bwilkerson That's the same as https://github.com/dart-lang/sdk/issues/30357#issuecomment-321305277, looks like the use case is not so rare.

**Comment by natebosch** [comment]
Closing in favor of #30357 which I renamed to have the same title as this issue for discoverability. That other issue has a bit more context from @bwilkerson already
