### ISSUE TITLE
Minor crash in intelij with basic AngularDart with router

### ISSUE THREAD

**Issue by recursiverighthook** [dart-lang/sdk#30663]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-172.3968.27`
- `1.24.2`
- `WS-172.3968.27, JRE 1.8.0_152-release-915-b11x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\alexa\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Failed to handle completion domain request: {id: 883, method: completion.getSuggestions, params: {file: C:\Users\alexa\Code\parents\bmdfamilyfarms.com\lib\app_component.dart, offset: 841}, clientRequestTime: 1505009564813}
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _OpTypeAstVisitor.visitNamedExpression (package:analysis_server/src/services/completion/dart/optype.dart:738)
#3      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7764)
#4      new OpType.forCompletion (package:analysis_server/src/services/completion/dart/optype.dart:117)
#5      DartCompletionRequestImpl.opType (package:analysis_server/src/services/completion/dart/completion_manager.dart:185)
#6      DartCompletionRequestImpl.includeIdentifiers (package:analysis_server/src/services/completion/dart/completion_manager.dart:159)
#7      ImportedReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/imported_reference_contributor.dart:44)
<asynchronous suspension>
#8      DartCompletionManager.computeSuggestions (package:analysis_

**Comment by bwilkerson** [comment]
Thank you for the report!

This problem has been fixed, and the fix is available in the latest dev build.
