### ISSUE TITLE
Error while trying to run the project

### ISSUE THREAD

**Issue by Shajeel-Afzal** [dart-lang/sdk#30664]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-172.3968.16`
- `1.21.0-dev.10.0`
- `IC-172.3968.16, JRE 1.8.0_152-release-915-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/z0/c42m1s012k5_yr_9v22q1trw0000gn/T/report.txt

```
Dart analysis server, SDK version 1.21.0-dev.10.0, server version 1.17.0, FATAL error: Failed to handle request: {clientRequestTime: 1504977700574, params: {file: /Users/shajeelafzal/Documents/flutter_workspace/cricket_app_flutter/lib/main.dart, offset: 47}, method: edit.getFixes, id: 46}
NoSuchMethodError: The method 'getLocation' was called on null.
Receiver: null
Tried calling: getLocation(47)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      EditDomainHandler.getFixes.<getFixes_async_body> (package:analysis_server/src/edit/edit_domain.dart:208)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#4      _rootRunUnary (dart:async/zone.dart:1158)
#5      _CustomZone.runUnary (dart:async/zone.dart:1037)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#9      _Future._complete (dart:async/future_impl.dart:467)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#11     AnalysisServer.getResolvedCompilationUnit.<getResolvedCompilationUnit_async_body> (package:analysis_server/src/analysis_server.dart:809)
#12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#13     _rootRun (dart:async/zone.dart:1146)

**Comment by bwilkerson** [comment]
This has likely been fixed in the latest dev releases. Please upgrade to a newer version of the SDK and let us know if you're still seeing this issue. Thanks!
