### ISSUE TITLE
Unknown analyzer error

### ISSUE THREAD

**Issue by adambender** [dart-lang/sdk#30693]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.70`
- `1.25.0-dev.9.0`
- `IU-171.4694.70, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-92-generic unknown, screens 2560x1600, 2560x1440, 2560x1440`

# Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.25.0-dev.9.0, server version 1.18.3, FATAL error: Failed to handle request: {id: 10969, method: edit.getFixes, params: {file: .../lib/service_run_mode.dart, offset: 442}, clientRequestTime: 1505339532107}
RangeError (index): Invalid value: Not in range 0..711, inclusive: 2186
#0      String.codeUnitAt (dart:core-patch/string_patch.dart:927)
#1      CorrectionUtils.getLineThis (package:analysis_server/src/services/correction/util.dart:939)
#2      CorrectionUtils.isClassWithEmptyBody (package:analysis_server/src/services/correction/util.dart:1126)
#3      CorrectionUtils.prepareNewClassMemberLocation (package:analysis_server/src/services/correction/util.dart:1163)
#4      CorrectionUtils.prepareNewFieldLocation (package:analysis_server/src/services/correction/util.dart:1180)
#5      FixProcessor._addFix_createField (package:analysis_server/src/services/correction/fix_internal.dart:1170)
<asynchronous suspension>
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:381)
<asynchronous suspension>
#7      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:84)
<asynchronous suspension>
#8      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:241)
<asynchronous suspension>

**Comment by bwilkerson** [comment]
There is a good chance that this has been fixed on bleeding edge, but I don't have a reproduction case to prove that.

**Comment by scheglov** [comment]
Assume fixed.
