### ISSUE TITLE
standalone/io/http_loopback_test flake on vm-linux-release-x64-reload-rollback-be

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#30700]
```
FAILED: none-vm-checked release_x64 standalone/io/http_loopback_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.equals(expected: <true>, actual: <false>) fails.
#0      Expect._fail (package:expect/expect.dart:496:5)
#1      Expect.equals (package:expect/expect.dart:124:5)
#2      IPv6ToIPv4FailureTest (file:///b/build/slave/vm-linux-release-x64-reload-rollback-be/build/sdk/tests/standalone/io/http_loopback_test.dart:54:12)
<asynchronous suspension>
#3      main (file:///b/build/slave/vm-linux-release-x64-reload-rollback-be/build/sdk/tests/standalone/io/http_loopback_test.dart:76:9)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --enable_asserts --enable_type_checks --hot-reload-rollback-test-mode --ignore-unrecognized-flags --packages=/b/build/slave/vm-linux-release-x64-reload-rollback-be/build/sdk/.packages /b/build/slave/vm-linux-release-x64-reload-rollback-be/build/sdk/tests/standalone/io/http_loopback_test.dart
Took 0:00:00.528586

Short reproduction command (experimental):
    python tools/test.py -m release --checked --hot-reload-rollback standalone/io/http_loopback_test
```

https://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-reload-rollback-be/builds/6547/steps/checked%20vm%20tests/logs/stdio

**Comment by dcharkes** [comment]
```dart
FAILED: dartk-vm release_arm64 standalone_2/io/http_loopback_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 12.000194s):
DART_CONFIGURATION=ReleaseXARM64 out/ReleaseXARM64/dart --sync-async --ignore-unrecognized-flags --packages=/b/build/slave/target-arm64-vm-linux-release-be/build/sdk/.packages /b/build/slave/target-arm64-vm-linux-release-be/build/sdk/tests/standalone_2/io/http_loopback_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <true>, actual: <false>) fails.
#0      Expect._fail (package:expect/expect.dart:651:5)
#1      Expect.equals (package:expect/expect.dart:124:5)
#2      IPv4ToIPv6FailureTest (file:///b/build/slave/target-arm64-vm-linux-release-be/build/sdk/tests/standalone_2/io/http_loopback_test.dart:33:12)
<asynchronous suspension>
#3      main (file:///b/build/slave/target-arm64-vm-linux-release-be/build/sdk/tests/standalone_2/io/http_loopback_test.dart:73:9)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -m release -c dartk -a arm64 standalone_2/io/http_loopback_test
```

Same error, but `IPv4ToIPv6FailureTest` instead of `IPv6ToIPv4FailureTest`

**Comment by sjindel-google** [comment]
This has also showed up on `dartk-linux-debug-simdbc64`.
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8929852162568218016/+/steps/vm_tests_shard_7/0/stdout
However, the error is different:

```
FAILED: dartk-vm debug_simdbc64 standalone_2/io/http_loopback_test
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 665ms):
DART_CONFIGURATION=DebugSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=out/DebugSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/out/DebugSIMDBC64/generated_compilations/dartk/tests_standalone_2_io_http_loopback_test/out.dill /b/s/w/ir/tests/standalone_2/io/http_loopback_test.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 02.000467s):
DART_CONFIGURATION=DebugSIMDBC64 out/DebugSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/DebugSIMDBC64/generated_compilations/dartk/tests_standalone_2_io_http_loopback_test/out.dill

exit code:
255

stderr:
Unhandled exception:
Expect.fail('Unexpected exception: Expect.fail('Unexpected connection to IPv6 server!')')
#0      Expect._fail (package:expect/expect.dart:651:5)
#1      Expect.fail (package:expect/expect.dart:269:5)
#2      IPv4ToIPv6FailureTest (file:///b/s/w/ir/tests/standalone_2/io/http_loopback_test.dart:30:12)
<asynchronous suspension>
#3      main (file:///b/s/w/ir/tests/standalone_2/io/http_loopback_test.dart:69:9)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
