### ISSUE TITLE
Analyzer crashes with new typedef + named arguments

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30729]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.70`
- `1.25.0-dev.4.0`
- `IU-171.4694.70, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1440x900`

# Exception

Please append the contents of:
file:///private/var/folders/7z/ngj4xpds2tb_y6sy6v6mwl8h0000gn/T/report.txt

```
Dart analysis server, SDK version 1.25.0-dev.4.0, server version 1.18.1, error: Analysis failed: /Users/matan/git/din/lib/src/clients/ws_client.dart
NoSuchMethodError: The getter 'typeArguments' was called on null.
Receiver: null
Tried calling: typeArguments
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ErrorVerifier._checkForMapTypeNotAssignable (package:analyzer/src/generated/error_verifier.dart:4568)
#3      ErrorVerifier.visitMapLiteral (package:analyzer/src/generated/error_verifier.dart:944)
#4      MapLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7266)
#5      DefaultFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3470)
#6      RecursiveAstVisitor.visitDefaultFormalParameter (package:analyzer/dart/ast/visitor.dart:755)
#7      ErrorVerifier.visitDefaultFormalParameter (package:analyzer/src/generated/error_verifier.dart:614)
#8      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3465)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#10     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4815)
#11     RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:845)
#12     ErrorVerifier.visitFormalParameterList (package:analyzer/src/generated/error_verifier.dart:713)
```

## Report

```
Dart analysis server, SDK version 1.25.0-dev.4.0, server version 1.18.1, error: Analysis failed: /Users/matan/git/din/lib/src/clients/ws_client.dart
NoSuchMethodError: The getter 'typeArguments' was called on null.
Receiver: null
Tried calling: typeArguments
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ErrorVerifier._checkForMapTypeNotAssignable (package:analyzer/src/generated/error_verifier.dart:4568)
#3      ErrorVerifier.visitMapLiteral (package:analyzer/src/generated/error_verifier.dart:944)
#4      MapLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7266)
#5      DefaultFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3470)
#6      RecursiveAstVisitor.visitDefaultFormalParameter (package:analyzer/dart/ast/visitor.dart:755)
#7      ErrorVerifier.visitDefaultFormalParameter (package:analyzer/src/generated/error_verifier.dart:614)
#8      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3465)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#10     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4815)
#11     RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:845)
#12     ErrorVerifier.visitFormalParameterList (package:analyzer/src/generated/error_verifier.dart:713)
#13     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4811)
#14     GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5739)
#15     RecursiveAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:893)
#16     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5732)
#17     GenericTypeAliasImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5822)
#18     RecursiveAstVisitor.visitGenericTypeAlias (package:analyzer/dart/ast/visitor.dart:899)
#19     GenericTypeAliasImpl.accept (package:analyzer/src/dart/ast/ast.dart:5814)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#21     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2502)
#22     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#23     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:540)
#24     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#25     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:303)
#26     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:103)
#27     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#28     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102)
#29     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#30     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
```

Here is the file, as I was typing it:

```dart
typedef WebSocketFactory = Future Function(String url, {Map<String, String> headers: const {}});
```

**Comment by matanlurey** [comment]
When I wrote it the _old_ way, I figured out that typedef's can't have default parameters :)

**Comment by jmesserly** [comment]
this is a similar problem as https://github.com/dart-lang/sdk/issues/30596, we need to do error verification on the AST structure of the new function types, and reject old-style FunctionTypedFormalParameter, as well as DefaultFormalParameter. Probably can do this at the parser level.

**Comment by devoncarew** [comment]
Just to update, I can still repro this from head.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/12201
