### ISSUE TITLE
checked mode crash with mixin transformation + IKG on dart2js

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30728]
Repro:
```
python tools/test.py -m release --checked --use-sdk pkg/front_end/tool/incremental_perf_test
```

(Note incremental_perf_test is not yet in the repo, but will be landed soon in a CL that refers to this bug)

**Comment by sigmundch** [comment]
the test is introduced here: https://dart-review.googlesource.com/c/sdk/+/6026

**Comment by peter-ahe-google** [comment]
Do you have a stack trace?

**Comment by sigmundch** [comment]
Turns out the issue here was that the compiler was trying to apply the mixin transformation on the outline of the sdk rather than the full platform.dill file. This is not going to work until the transformer is made fully modular. I'm closing this as a duplicate of #29881

For reference, here is the stack trace
```
package:kernel/transformations/mixin_full_resolution.dart': Failed assertion: line 108 pos 12: 'librariesToBeTransformed.contains(class_.enclosingLibrary)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:35)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:31)
#2      MixinFullResolution.transformClass (package:kernel/transformations/mixin_full_resolution.dart:108:12)
#3      MixinFullResolution.transformClass (package:kernel/transformations/mixin_full_resolution.dart:101:7)
#4      MixinFullResolution.transform (package:kernel/transformations/mixin_full_resolution.dart:52:9)
#5      transformLibraries (package:kernel/transformations/mixin_full_resolution.dart:16:8)
#6      VmFastaTarget.performModularTransformationsOnLibraries (package:kernel/target/vm_fasta.dart:28:5)
#7      KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:646:19)
#8      KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:285:7)
<asynchronous suspension>
#9      KernelDriver._compileCycle.<anonymous closure>.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:259:35)
<asynchronous suspension>
...
```
