### ISSUE TITLE
--snapshot now executes the entrypoint script by default w/Dart 2.0.0-dev.0.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#30790]
```
pu
Resolving dependencies... (4.1s)
Overriding the upper bound Dart SDK constraint to <=2.0.0-dev.0.0 for the following packages:

analyzer, angular, angular_compiler, angular_forms, archive, args, async, barback, browser, build, build_barback, charcode, code_builder, code_transformers, collection, convert, csslib, dart_style, dart_to_js_script_rewriter, front_end, func, glob, html, intl, isolate, js, kernel, logging, observable, path, perf_api, pool, quiver, quiver_hashcode, source_gen, source_maps, source_span, stack_trace, string_scanner, tuple, unittest, utf, uuid, watcher, webdriver, yaml

To disable this you can set the PUB_ALLOW_PRERELEASE_SDK system environment variable to `false`, or you can silence this message by setting it to `quiet`.
  analyzer 0.30.0+2 (0.31.0-alpha.1 available)
  angular 4.0.0
  angular_compiler 0.3.0
  angular_components 0.6.0
  angular_forms 1.0.0
  archive 1.0.31
  args 0.13.7 (1.0.0 available)
  async 1.13.3 (2.0.0 available)
  barback 0.15.2+11
  browser 0.10.0+2
> build 0.10.1 (was 0.10.0+1)
  build_barback 0.4.0
  charcode 1.1.1
  cli_util 0.1.2
  code_builder 1.0.4 (2.0.0-alpha+1 available)
  code_transformers 0.5.1+3
  collection 1.14.3
  convert 2.0.1
  crypto 2.0.2
  csslib 0.14.0
  dart_style 1.0.7
  dart_to_js_script_rewriter 1.0.3
  fixnum 0.10.6
  front_end 0.1.0-alpha.4 (0.1.0-alpha.6 available)
  func 1.0.0
  glob 1.1.3
  html 0.13.2
  intl 0.15.1
  isolate 1.0.0
  js 0.6.1
  kernel 0.3.0-alpha.1 (0.3.0-alpha.3 available)
  logging 0.11.3+1
> matcher 0.12.1+3 (was 0.12.1+2)
  meta 1.1.1
  observable 0.20.4+1
  package_config 1.0.2
  path 1.4.2
  perf_api 0.1.0
  plugin 0.2.0+1
  pool 1.3.1
  quiver 0.25.0
  quiver_hashcode 1.0.0
  source_gen 0.7.1
  source_maps 0.10.4
  source_span 1.4.0
> stack_trace 1.8.1 (was 1.8.0)
  string_scanner 1.0.2
  tuple 1.0.1
  typed_data 1.1.4
  unittest 0.11.7 (0.12.4+1 available)
  utf 0.9.0+3
  uuid 0.5.3
  watcher 0.9.7+3
  webdriver 1.2.3 (2.0.0-beta available)
  yaml 2.1.12
Changed 3 dependencies!
Precompiling dependencies...
Loading source assets...
Loading angular and dart_to_js_script_rewriter transformers... (2.8s)
Failed to compile a snapshot to .pub/transformers/transformers.snapshot:
Unhandled exception:
NoSuchMethodError: The method 'send' was called on null.
Receiver: null
Tried calling: send(SendPort)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      loadTransformers (package:$pub/transformer_isolate.dart:21:11)
#3      main (file:///private/var/folders/bj/09dxmvxx5hl4t07lbvqgj66w0071_k/T/pub_KkZuDl/runInIsolate.dart:5:35)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by kevmoo** [comment]
FYI: running it again doesn't crash...

**Comment by kevmoo** [comment]
Repro: see gwt_mail_app or angular_component_example

**Comment by jakemac53** [comment]
I added some more logging into pub, its creating a file like this:

```dart
import 'dart:isolate';
import 'package:angular/transformer.dart';
import 'package:dart_to_js_script_rewriter/dart_to_js_script_rewriter.dart';
import r'package:$pub/transformer_isolate.dart';
void main(_, SendPort replyTo) => loadTransformers(replyTo);
```

It spawns the isolate like this, and I confirmed `message` is not `null` (its a `SendPort`):

```dart
await Isolate.spawnUri(p.toUri(p.absolute(dartPath)), [], message,
        packageRoot: packageRoot);
```

So this looks like an `Isolate.spawnUri` issue where its not passing through the message?

**Comment by jakemac53** [comment]
fwiw, I was unable to repro this with a basic example :/

**Comment by jakemac53** [comment]
So the issue actually here is not when its spawing the isolate, but when it tries to create the snapshot for the script. The script expects a `SendPort` and it doesn't get one when generating the snapshot.

Either that code changed to require a `SendPort` when it didn't used to, or the snapshot generation command changed to actually execute the entrypoint when it didn't used to (is app-jit the default now?).

**Comment by jakemac53** [comment]
Ok I confirmed that creating a snapshot now executes the main dart script by default and it didn't previously.

**Comment by kevmoo** [comment]
Seeing another manifestation, I think.

1) Have a package globally activated in 1.25.0-dev
2) Try to run it in 2.0.0-dev.0.0

expected: see warning about wrong snapshot version, but it still runs
actual: 

```
Wrong script snapshot version, expected 'd120342d48b35fc67901acb723bb6e9f' found '47f19879b9cac7de1b33e7b7ea414c7a'
Unable to spawn isolate: Unhandled exception:
Could not load "file:///Users/kevmoo/.pub-cache/global_packages/pubviz/bin/pubviz.dart.snapshot": FileSystemException: Cannot open file, path = '/Users/kevmoo/.pub-cache/global_packages/pubviz/bin/pubviz.dart.snapshot' (OS Error: No such file or directory, errno = 2)
null
```

**Comment by a-siva** [comment]
Can you post actual commands run, it seems like a snapshots generated from a different version of the VM are being loaded.

**Comment by kevmoo** [comment]
@rmacnak-google seems to have a fix https://dart-review.googlesource.com/c/sdk/+/6765

**Comment by kevmoo** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/913d828db0fd5ac7113f4a28ff696566ab3bb3d3
