### ISSUE TITLE
VM executable fails to load Dart paths containing #

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#30808]
If you run the following in a shell:

```
$ echo 'void main() => print("hi");' > '#foo.dart'
$ dart \#foo.dart
```

the VM crashes with:

```
vm-service: Error: Unhandled exception:
Unsupported operation: Cannot extract a file path from a URI with a fragment component
#0      _SimpleUri.toFilePath (dart:core/uri.dart:4566)
#1      _loadFile (loader.dart:428:26)
#2      _handleResourceRequest (loader.dart:513:7)
#3      _processLoadRequest (loader.dart:1017:9)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

`#foo.dart` is a valid path on Unix and Windows, and the VM should handle it appropriately.

See also https://github.com/dart-lang/pub/issues/1675, which was caused by this issue.

**Comment by zanderso** [comment]
The input paths are treated as URI's. You can access #foo.dart using percent encoding:
```
$ dart %23foo.dart
hi
```
I'm not sure that anyone is going to work on refactoring to add special cases for strings that are valid paths but not valid URIs, so I'm going to recommend closing this issue as "not planned". @a-siva

**Comment by nex3** [comment]
> The input paths are treated as URI's.

This is not generally true. On Windows, it accepts paths. Running e.g. `dart C:\foo\bar.dart` works as expected, despite that not being a valid URI of any kind.

Right now, it seems that the VM accepts some undefined combination of paths and URLs. This is a very bad user experience, because it leads users to believe it's safe to pass paths when in fact a subset of totally valid paths will unexpectedly break the VM.

I propose the following scheme to make this behave closer to user expectation: an argument is paris sed as a URL **if and only if** it begins with a URL scheme indicator (`http://`, `file://`, `data://`, etc). Everything else is parsed as a path. This preserves the ability to load from non-filesystem sources without validating the user expectation that `dart $path` will work for any valid local path. It's still possible to write cross-platform invocations on relative paths, since forward slashes are valid in both Windows and Unix.

**Comment by dgrove** [comment]
@zanderso what are your thoughts on addressing this?

**Comment by zanderso** [comment]
We do a small amount of preprocessing on Windows paths so that Uri.parse() will work. See for example: https://github.com/dart-lang/sdk/blob/master/runtime/bin/builtin.dart#L218, and https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/. Otherwise, all paths on the command line and in imports are passed to Uri.parse() directly.

We could take the absence of a scheme as a hint that we should automagically Uri escape a string as a Uri component (using Uri.encodeComponent() https://api.dartlang.org/stable/1.24.2/dart-core/Uri/encodeComponent.html) before passing to Uri.parse(). @bkonyi has some recent familiarity in this area. Piping something other than Uris through the VM and loader would be a big change that I think we should avoid. /cc @a-siva.

**Comment by nex3** [comment]
Rather than escaping the path, why not convert it to a `file:` URL?

**Comment by zanderso** [comment]
Could you clarify what you mean by "convert it to a file: URL"?

**Comment by nex3** [comment]
Any operating system path can fairly straightforwardly be converted to an equivalent (possibly relative) `file:` URL—this is what the [`new Uri.file()`](https://api.dartlang.org/stable/1.24.2/dart-core/Uri/Uri.file.html) constructor does. My proposed procedure is:

1. Check if the argument begins with a URL scheme (`http://`, `file://`, `data:`, or `package:`). If so, pass it as-is to the VM's loader.

2. Otherwise, convert it to a file URL as with `new Uri.file(path, windows: Platform.isWindows)`, and pass the result to the VM's loader.

**Comment by zanderso** [comment]
As mentioned above, the VM loader currently only accepts Uris, and changing that is not straightforward, but otherwise I think the approaches are equivalent.

**Comment by nex3** [comment]
Right—I'm proposing my procedure as a layer in front of the VM loader. The VM loader only sees the post-processed output, which is either a URI the user passed on (from step 1) or a path that's been converted to a URI (from step 2).

**Comment by zanderso** [comment]
/cc @floitschG @lrhn Florian mentioned that he had some thoughts on this, and that Lasse might as well. Two things:
- The VM treats paths in imports and paths on the command line similarly. We should think about retaining that property, which might depend on the language spec having an opinion about what to do with the strings in these places.
- I don't think it's a blocker, but I also want to note here that this change would be breaking for anyone who is already escaping their file system paths.

**Comment by zanderso** [comment]
@alexmarkov @aam
