### ISSUE TITLE
Fasta should not care about colors if we are not going to print to console

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30805]
I think running external processes during compilation is strange.

And it is not a compiler business to care about output at all.
Its clients know better how to report errors.

**Comment by sigmundch** [comment]
Konstantin added to the CL a piece of context that I think it is relevant here. There are a  couple scenarios where fasta uses colors: 
- producing error messages in the console

- producing error recovery nodes containing formatted error messages (for example:
```
#0      computeEnableColors (package:front_end/src/fasta/colors.dart:116:20)
#1      CompilerContext.enableColors (package:front_end/src/fasta/compiler_context.dart:105:43)
#2      formatInternal (package:front_end/src/fasta/command_line_reporting.dart:47:25)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:194:10)
#4      CompilerContext.format (package:front_end/src/fasta/compiler_context.dart:66:12)
#5      KernelTarget.handleRecoverableErrors (package:front_end/src/fasta/kernel/kernel_target.dart:317:49)
#6      KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:291:7)
```
)

To me the former makes sense - attaching an error handler or disabling the default reporting of error messages should be enough to prevent fasta from using colors in this scenario.

The latter involves some additional design and I'll defer to Peter on what should be done here. It's possible that once the proper error recovery nodes are added in kernel and fasta produces those error nodes, then there will be no need for fasta to generate formatted messages in the code.

For now, I'm personally OK letting Peter fix this later (since it seems like a low priority issue) and temporarily disable colors in IKG as a workaround like Konstantin did. Peter is that a good strategy to move forward?

**Comment by scheglov** [comment]
SGTM, thank you for opening the issue.

**Comment by peter-ahe-google** [comment]
I don't think we should disable colors in IKG. This is the primary interface to flutter, and I'm pretty sure it's going to be the primary interface for the Dart VM command line as well.

I don't subscribe to any of the objections @scheglov makes in this bug report, but there was a concern mentioned in the CL about performance. I'd like to fix that performance problem short-term, and that is why I asked for a bug report instead of simply disabling it.

Could you please add details about how to reproduce this problem?

**Comment by scheglov** [comment]
Output should be done be the final client.

`KernelDriver` is not a final client.

Even IKG is not a final client - `frontend_server` might have its own ideas where to show messages - maybe show them in IDE UI.

Run `pkg/analyzer/test/generated/non_error_resolver_kernel_test.dart` to reproduce.
