### ISSUE TITLE
unsigned/signed mismatch in co19/Language/Classes/Instance_Methods/Operators/allowed_names_t01

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#30800]
The test fails (sometimes) in an assertion that compares -8 to 4294967288 (=2^32-8)

This was observed in the commit queue, a subsequent run passed successfully.

https://dart-review.googlesource.com/c/sdk/+/6380/1
https://chromium-swarm.appspot.com/task?id=38aa9bb35abdde10

FAILED: dart2js-chrome release_ia32 co19/Language/Classes/Instance_Methods/Operators/allowed_names_t01
Expected: Pass 
Actual: RuntimeError
CommandOutput[dart2js]:

stdout:
tests/co19/src/Language/Classes/Instance_Methods/Operators/allowed_names_t01.dart:44:3:
Hint: The class 'C' overrides 'operator==', but not 'get hashCode'.
  operator ==(C other) {
  ^^^^^^^^^^^^^^^^^^^^
Compiled 1,760,713 characters Dart to 39,561 characters JavaScript in 0.43 seconds
Dart file (/b/swarming/w/ir/tests/co19/src/Language/Classes/Instance_Methods/Operators/allowed_names_t01.dart) compiled to JavaScript: out/ReleaseIA32/generated_compilations/dart2js-sdk/tests_co19_src_Language_Classes_Instance_Methods_Operators_allowed_names_t01/test.js

CommandOutput[chrome]:

stdout:
events:
  [
        {
              type: debug
              value: test_controller.js started
              timestamp: 0
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = true, isStatusUpdate = true, isDone = false)
              timestamp: 0
        },
        {
              type: print
              value: dart-calling-main
              timestamp: 0.014
        },
        {
              type: sync_exception
              value: Exception: Expect.equals(expected: <-8>, actual: <4294967288>) fails.
                    Stack: Expect.equals(expected: <-8>, actual: <4294967288>) fails.
                        at Object.wrapException (http://127.0.0.1:53193/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Classes_Instance_Methods_Operators_allowed_names_t01/test.js:558:17)
                        at Object._fail (http://127.0.0.1:53193/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Classes_Instance_Methods_Operators_allowed_names_t01/test.js:877:15)
                        at Object.Expect_equals (http://127.0.0.1:53193/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Classes_Instance_Methods_Operators_allowed_names_t01/test.js:884:9)
                        at main (http://127.0.0.1:53193/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Classes_Instance_Methods_Operators_allowed_names_t01/test.js:867:9)
                        at dartMainRunner (http://127.0.0.1:53193/root_dart/tools/testing/dart/test_controller.js:311:5)
                        at http://127.0.0.1:53193/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Classes_Instance_Methods_Operators_allowed_names_t01/test.js:1114:7
                        at init.currentScript (http://127.0.0.1:53193/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Classes_Instance_Methods_Operators_allowed_names_t01/test.js:1100:7)
                        at http://127.0.0.1:53193/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Classes_Instance_Methods_Operators_allowed_names_t01/test.js:1111:5
                        at http://127.0.0.1:53193/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Classes_Instance_Methods_Operators_allowed_names_t01/test.js:1119:3
              timestamp: 0.015
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = false, isStatusUpdate = false, isDone = true)
              timestamp: 0.015
        },
        {
              type: dom
              value: <head>
                      <meta http-equiv="X-UA-Compatible" content="IE=edge">
                      <meta name="dart.unittest" content="full-stack-traces">
                      <title> Test /b/swarming/w/ir/tests/co19/src/Language/Classes/Instance_Methods/Operators/allowed_names_t01.dart </title>
                      <style>
                         .unittest-table { font-family:monospace; border:1px; }
                         .unittest-pass { background: #6b3;}
                         .unittest-fail { background: #d55;}
                         .unittest-error { background: #a11;}
                      </style>
                    </head>
                    <body>
                      <h1> Running /b/swarming/w/ir/tests/co19/src/Language/Classes/Instance_Methods/Operators/allowed_names_t01.dart </h1>
                      <script type="text/javascript" src="/root_dart/tools/testing/dart/test_controller.js">
                      </script>
                      <script type="text/javascript" src="/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Classes_Instance_Methods_Operators_allowed_names_t01/test.js" onerror="scriptTagOnErrorCallback(null)" defer="">
                      </script>
                      <script type="text/javascript" src="/root_dart/pkg/browser/lib/dart.js"></script>
                    
                    </body>
              timestamp: 0.015
        },
  ]

**Comment by athomas** [comment]
Duplicates #30853
