### ISSUE TITLE
Analysis server error

### ISSUE THREAD

**Issue by giorgiofran** [dart-lang/sdk#30815]
[report1.txt](https://github.com/dart-lang/sdk/files/1317335/report1.txt)
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-172.4155.35`
- `1.24.2`
- `WS-172.4155.35, JRE 1.8.0_152-release-915-b11x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Giorgio\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Analysis failed: C:\Users\Giorgio\Projects\Dart\vidya\vidya_web\lib\src\base\web\web_service.dart
Invalid argument(s): argumentTypes.length (1) != parameterTypes.length (2)
#0      InterfaceTypeImpl.substitute2 (package:analyzer/src/dart/element/type.dart:2022)
#1      ErrorVerifier._checkTypeArguments (package:analyzer/src/generated/error_verifier.dart:6261)
#2      ErrorVerifier.visitMethodInvocation (package:analyzer/src/generated/error_verifier.dart:1002)
#3      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#4      ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4094)
#5      RecursiveAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:809)
#6      ErrorVerifier.visitExpressionFunctionBody (package:analyzer/src/generated/error_verifier.dart:666)
#7      ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:4090)
#8      FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#9      RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:869)
#10     ErrorVerifier.visitFunctionExpression (package:analyzer/src/generated/error_verifier.dart:780)
#11     FunctionExpression

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
