### ISSUE TITLE
dart2js/kernel/closed_world2_test fails with new function type syntax

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30826]
The `dart2js/kernel/closed_world2_test` fails with new function type syntax.

```
FAILED: none-vm-checked release_ia32 dart2js/kernel/closed_world2_test
Expected: Slow Pass 
Actual: RuntimeError
CommandOutput[vm]:
stdout:
unittest-suite-wait-for-done
---- analyze-only ------------------------------------------------
memory:main.dart:75:1:
Warning: The class 'ClassWithCall14' can't inherit both getters and methods by the named 'call'.
class ClassWithCall14 extends ClassWithCallBase
^^^^^
memory:main.dart:22:3:
Info: The inherited method 'call' is declared here in class 'ClassWithCallBase'.
  void call() {}
  ^^^^^^^^^^^
memory:main.dart:42:3:
Info: The inherited getter 'call' is declared here in class 'ClassWithCallGetter'.
  int get call => 0;
  ^^^^^^^^^^^^
memory:main.dart:77:1:
Warning: 'ClassWithCall15' doesn't implement the setter 'call' declared in 'ClassWithCallSetter'.
Try adding an implementation of 'call' or declaring 'ClassWithCall15' to be 'abstract'.
class ClassWithCall15 extends ClassWithCallBase
^^^^^
memory:main.dart:46:3:
Info: The setter 'call' is declared here in class 'ClassWithCallSetter'.
  void set call(int i) {}
  ^^^^^^^^^^^^^^^^^^^^
memory:main.dart:80:1:
Warning: 'ClassImplementsFunction' doesn't implement 'call' declared in 'Function'.
Try adding an implementation of 'call' or declaring 'ClassImplementsFunction' to be 'abstract'.
class ClassImplementsFunction implements Function {}
^^^^^
---- analyze-all -------------------------------------------------
memory:main.dart:75:1:
Warning: The class 'ClassWithCall14' can't inherit both getters and methods by the named 'call'.
class ClassWithCall14 extends ClassWithCallBase
^^^^^
memory:main.dart:22:3:
Info: The inherited method 'call' is declared here in class 'ClassWithCallBase'.
  void call() {}
  ^^^^^^^^^^^
memory:main.dart:42:3:
Info: The inherited getter 'call' is declared here in class 'ClassWithCallGetter'.
  int get call => 0;
  ^^^^^^^^^^^^
memory:main.dart:80:1:
Warning: 'ClassImplementsFunction' doesn't implement 'call' declared in 'Function'.
Try adding an implementation of 'call' or declaring 'ClassImplementsFunction' to be 'abstract'.
class ClassImplementsFunction implements Function {}
^^^^^
memory:main.dart:77:1:
Warning: 'ClassWithCall15' doesn't implement the setter 'call' declared in 'ClassWithCallSetter'.
Try adding an implementation of 'call' or declaring 'ClassWithCall15' to be 'abstract'.
class ClassWithCall15 extends ClassWithCallBase
^^^^^
memory:main.dart:46:3:
Info: The setter 'call' is declared here in class 'ClassWithCallSetter'.
  void set call(int i) {}
  ^^^^^^^^^^^^^^^^^^^^
---- closed world from kernel ------------------------------------
stderr:
Unhandled exception:
Unsupported operation: Unsupported type parameter type node R.
#0      KernelToElementMapBase&KernelToElementMapForImpactMixin&ElementCreatorMixin._getTypeVariable.<anonymous closure> (package:compiler/src/kernel/element_map_impl.dart:851:7)
#1      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:270)
#2      KernelToElementMapBase&KernelToElementMapForImpactMixin&ElementCreatorMixin._getTypeVariable (package:compiler/src/kernel/element_map_impl.dart:825:29)
#3      KernelToElementMapBase.getTypeVariable (package:compiler/src/kernel/element_map_impl.dart:262:7)
#4      DartTypeConverter.visitTypeParameterType (package:compiler/src/kernel/element_map_impl.dart:1486:44)
#5      TypeParameterType.accept (package:kernel/ast.dart:4675:34)
#6      DartTypeConverter.visitType (package:compiler/src/kernel/element_map_impl.dart:1470:17)
#7      DartTypeConverter.visitFunctionType (package:compiler/src/kernel/element_map_impl.dart:1492:9)
#8      FunctionType.accept (package:kernel/ast.dart:4473:34)
#9      DartTypeConverter.visitType (package:compiler/src/kernel/element_map_impl.dart:1470:17)
#10     DartTypeConverter.visitFunctionType (package:compiler/src/kernel/element_map_impl.dart:1492:9)
#11     FunctionType.accept (package:kernel/ast.dart:4473:34)
#12     DartTypeConverter.convert (package:compiler/src/kernel/element_map_impl.dart:1464:17)
#13     KernelToElementMapBase.getDartType (package:compiler/src/kernel/element_map_impl.dart:393:60)
#14     KernelToElementMapBase.getFunctionType (package:compiler/src/kernel/element_map_impl.dart:436:31)
#15     FunctionDataImpl.getFunctionType (package:compiler/src/kernel/env.dart:531:33)
#16     KernelToElementMapBase._getFunctionType (package:compiler/src/kernel/element_map_impl.dart:610:17)
#17     KernelElementEnvironment.getFunctionType (package:compiler/src/kernel/element_map_impl.dart:1278:23)
#18     checkElementEnvironment.checkMembers (file:///b/swarming/w/ir/cache/builder/sdk/tests/compiler/dart2js/equivalence/check_functions.dart:550:16)
#19     checkElementEnvironment.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/swarming/w/ir/cache/builder/sdk/tests/compiler/dart2js/equivalence/check_functions.dart:688:21)
#20     _CompilerElementEnvironment.forEachConstructor (package:compiler/src/resolution/resolution_strategy.dart:529:8)
#21     checkElementEnvironment.<anonymous closure>.<anonymous closure> (file:///b/swarming/w/ir/cache/builder/sdk/tests/compiler/dart2js/equivalence/check_functions.dart:671:12)
#22     _CompilerElementEnvironment.forEachClass.<anonymous closure> (package:compiler/src/resolution/resolution_strategy.dart:633:10)
#23     LinkEntry.forEach (package:front_end/src/fasta/util/link_implementation.dart:124:8)
#24     LibraryElementX.forEachLocalMember (package:compiler/src/elements/modelx.dart:1247:27)
#25     _CompilerElementEnvironment.forEachClass (package:compiler/src/resolution/resolution_strategy.dart:630:28)
#26     checkElementEnvironment.<anonymous closure> (file:///b/swarming/w/ir/cache/builder/sdk/tests/compiler/dart2js/equivalence/check_functions.dart:563:10)
#27     computeSetDifference (file:///b/swarming/w/ir/cache/builder/sdk/tests/compiler/dart2js/equivalence/check_helpers.dart:196:24)
#28     checkSetEquivalence (file:///b/swarming/w/ir/cache/builder/sdk/tests/compiler/dart2js/equivalence/check_helpers.dart:222:19)
#29     checkElementEnvironment (file:///b/swarming/w/ir/cache/builder/sdk/tests/compiler/dart2js/equivalence/check_functions.dart:554:3)
#30     mainInternal (file:///b/swarming/w/ir/cache/builder/sdk/tests/compiler/dart2js/kernel/closed_world2_test.dart:242:3)
<asynchronous suspension>
#31     main.<anonymous closure> (file:///b/swarming/w/ir/cache/builder/sdk/tests/compiler/dart2js/kernel/closed_world2_test.dart:175:11)
<asynchronous suspension>
#32     asyncTest (package:async_helper/async_helper.dart:93:4)
#33     main (file:///b/swarming/w/ir/cache/builder/sdk/tests/compiler/dart2js/kernel/closed_world2_test.dart:174:3)
#34     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
Command[vm]: DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart-sdk/bin/dart --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/b/swarming/w/ir/cache/builder/sdk/.packages /b/swarming/w/ir/cache/builder/sdk/tests/compiler/dart2js/kernel/closed_world2_test.dart
Took 0:00:38.809048
Short reproduction command (experimental):
    python tools/test.py -m release -a ia32 --checked --use-sdk --reset-browser-configuration dart2js/kernel/closed_world2_test
```

**Comment by sigmundch** [comment]
@johnniwinther can you take a look? My hunch is that the issue is on the dart2js side of things

**Comment by floitschG** [comment]
Same crash for `dart2js_extra/mirrors_used_warning_test/none` and for `language/await_for_test`.

See https://build.chromium.org/p/client.dart/builders/dart2js-linux-d8-minified-4-5-be/builds/7851/steps/dart2js-with-kernel-d8%20tests/logs/stdio
