### ISSUE TITLE
Issue building SDK

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#30830]
`./tools/build.py -mrelease create_sdk` gets me:

```
Invalid argument(s): AnalysisContext must be strong mode
#0      new ModuleCompiler (package:dev_compiler/src/compiler/compiler.dart:123:7)
#1      _compile (package:dev_compiler/src/compiler/command.dart:136:22)
#2      compile (package:dev_compiler/src/compiler/command.dart:60:5)
#3      main (file:///home/mfairhurst/dart/sdk/sdk/pkg/dev_compiler/bin/dartdevc.dart:53:16)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

I got this for HEAD, and after checking out the tag for 1.25.0-dev.9.0

I even tried hardcoding "strongMode = true" in `pkg/analyzer/lib/src/generated/engine.dart`, but can't seem to get the hardcoded value in all the places its needing I guess?

**Comment by vsmenon** [comment]
Is this still an open?

**Comment by MichaelRFairhurst** [comment]
I was not able to solve it, eventually @a14n ran the tests that I was trying to run for me instead. Didn't put much time in after that.
 
Seemed to be related to depot_tools failing to run hooks. @whesse recommended I reclone from scratch.

I may not get to it for a while, but it may be worth leaving open until then for in case others run into it?

**Comment by MichaelRFairhurst** [comment]
Cloned from scratch and I'm still getting this:

```
~/dart/sdk2/sdk φ tools/build.py -ax64 -mdebug create_sdk
ninja -C out/DebugX64 create_sdk
ninja: Entering directory `out/DebugX64'
[1932/1997] ACTION //utils/dartdevc:dartdevc(//build/toolchain/linux:clang_x64)
FAILED: gen/dartdevc.dart.snapshot 
python ../../build/gn_run_binary.py compiled_action dart --packages=/home/mfairhurst/dart/sdk2/sdk/.packages --snapshot=/home/mfairhurst/dart/sdk2/sdk/out/DebugX64/gen/dartdevc.dart.snapshot --snapshot-kind=app-jit /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart --dart-sdk /home/mfairhurst/dart/sdk2/sdk/sdk --dart-sdk-summary /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler -o dartdevc.js --unsafe-force-compile /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart
Command failed: ./dart --packages=/home/mfairhurst/dart/sdk2/sdk/.packages --snapshot=/home/mfairhurst/dart/sdk2/sdk/out/DebugX64/gen/dartdevc.dart.snapshot --snapshot-kind=app-jit /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart --dart-sdk /home/mfairhurst/dart/sdk2/sdk/sdk --dart-sdk-summary /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler -o dartdevc.js --unsafe-force-compile /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart
output: We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk /home/mfairhurst/dart/sdk2/sdk/sdk --dart-sdk-summary /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler -o dartdevc.js --unsafe-force-compile /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart
    dart --version: 2.0.0-edge.e9ff04ae7e3ff9b7c1ba731ba9537b21d0e18402 (Fri Nov 10 15:12:05 2017) on "linux_x64"
\```
Invalid argument(s): AnalysisContext must be strong mode
#0      new ModuleCompiler (package:dev_compiler/src/analyzer/module_compiler.dart:123:7)
#1      _compile (package:dev_compiler/src/analyzer/command.dart:133:22)
#2      compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#3      main (file:///home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart:27:16)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

I think it has something to do with the SDK I'm using to bootstrap the build, which is currently

```
Dart VM version: 1.25.0-dev.16.3 (Mon Sep 11 04:09:38 2017) on "linux_x64"
```

I'll upgrade and then try again.

**Comment by MichaelRFairhurst** [comment]
Still happened

```
~/dart/sdk2/sdk φ tools/build.py -ax64 -mdebug create_sdk
gn gen --check in out/DebugX64
GN Time: 0.396 seconds
ninja -C out/DebugX64 create_sdk
ninja: Entering directory `out/DebugX64'
[1932/1997] ACTION //utils/dartdevc:dartdevc(//build/toolchain/linux:clang_x64)
FAILED: gen/dartdevc.dart.snapshot 
python ../../build/gn_run_binary.py compiled_action dart --packages=/home/mfairhurst/dart/sdk2/sdk/.packages --snapshot=/home/mfairhurst/dart/sdk2/sdk/out/DebugX64/gen/dartdevc.dart.snapshot --snapshot-kind=app-jit /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart --dart-sdk /home/mfairhurst/dart/sdk2/sdk/sdk --dart-sdk-summary /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler -o dartdevc.js --unsafe-force-compile /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart
Command failed: ./dart --packages=/home/mfairhurst/dart/sdk2/sdk/.packages --snapshot=/home/mfairhurst/dart/sdk2/sdk/out/DebugX64/gen/dartdevc.dart.snapshot --snapshot-kind=app-jit /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart --dart-sdk /home/mfairhurst/dart/sdk2/sdk/sdk --dart-sdk-summary /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler -o dartdevc.js --unsafe-force-compile /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart
output: We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk /home/mfairhurst/dart/sdk2/sdk/sdk --dart-sdk-summary /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.sum --library-root /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler -o dartdevc.js --unsafe-force-compile /home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart
    dart --version: 2.0.0-edge.e9ff04ae7e3ff9b7c1ba731ba9537b21d0e18402 (Fri Nov 10 15:36:41 2017) on "linux_x64"
\```
Invalid argument(s): AnalysisContext must be strong mode
#0      new ModuleCompiler (package:dev_compiler/src/analyzer/module_compiler.dart:123:7)
#1      _compile (package:dev_compiler/src/analyzer/command.dart:133:22)
#2      compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#3      main (file:///home/mfairhurst/dart/sdk2/sdk/pkg/dev_compiler/bin/dartdevc.dart:27:16)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by MichaelRFairhurst** [comment]
Solved by @whesse, I had an `analysis_options.yaml` file in my home directory. Explains why nobody else was seeing it!

**Comment by MichaelRFairhurst** [comment]
Reopening: Bill suggested that this should be caught at build time. Will update the title accordingly as well
