### ISSUE TITLE
Crash in Fasta while parsing a native class

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30836]
```dart
class A native 'something' {
  final int x;
  A() {}
}
```

```
  'package:front_end/src/fasta/source/outline_builder.dart': Failed assertion: line 927 pos 12: 'nativeMethodName == null': is not true.
  #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:35)
  #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:31)
  #2      OutlineBuilder.endMember (package:front_end/src/fasta/source/outline_builder.dart:927:12)
  #3      Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2373:14)
  #4      Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2265:15)
  #5      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:931:13)
  #6      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:884:14)
  #7      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:316:14)
  #8      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:274:14)
  #9      Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:263:13)
  #10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:252:15)
  #11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:161:37)
  <asynchronous suspension>
  #12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:145:13)
  <asynchronous suspension>
  #13     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:236:20)
  <asynchronous suspension>
  #14     KernelDriver._compileCycle.<anonymous closure>.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:258:28)
```

**Comment by peter-ahe-google** [comment]
Since @askeksa-google is looking at removing crashes, please update this bug if you start working on it.
