### ISSUE TITLE
Failure: Unimplemented Error in Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#30844]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-172.4155.36`
- `1.24.0-dev.6.6`
- `IU-172.4155.36, JRE 1.8.0_152-release-915-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1680x1050  Retina`

# Exception

```
Dart analysis server, SDK version 1.24.0-dev.6.6, server version 1.18.0, error: Analysis failed: /Users/gspencer/code/engine/src/flutter/frontend_server/bin/starter.dart context: exception_20170920_211441_729
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1096)
#1      CompilationUnitElementForLink.resolveTypeRef.getTypeArgument (package:analyzer/src/summary/link.dart:1103)
#2      new List.generate (dart:core/list.dart:142)
#3      ClassElementForLink_Class.buildType (package:analyzer/src/summary/link.dart:647)
#4      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1113)
#5      VariableElementForLink.declaredType (package:analyzer/src/summary/link.dart:5196)
#6      VariableElementForLink.type (package:analyzer/src/summary/link.dart:5287)
#7      PropertyAccessorElementForLink_Variable.returnType (package:analyzer/src/summary/link.dart:4548)
#8      PropertyAccessorElementForLink_Variable.asStaticType (package:analyzer/src/summary/link.dart:4501)
#9      ExprTypeComputer._doPushReference (package:analyzer/src/summary/link.dart:2485)
#10     ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2073)
#11     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:4957)
#12     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:4808)
#13     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#14     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#15     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5226)
#16     FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2700)
#17     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:673)
#18     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1308)
#19     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3672)
#20     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3408)
#21     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3330)
#22     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#23     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#24     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#25     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#26     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#27     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#28     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#29     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#30     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#31     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3373)
#32     Linker.link (package:analyzer/src/summary/link.dart:3897)
#33     relink (package:analyzer/src/summary/link.dart:132)
#34     link (package:analyzer/src/summary/link.dart:113)
#35     new LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:116)
#36     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#37     new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:115)
#38     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#39     new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:53)
#40     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1092)
#41     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:989)
#42     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#43     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#44     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:854)
<asynchronous suspension>
#45     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#46     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#47     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#48     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#49     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#50     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#51     _rootRun (dart:async/zone.dart:1120)
#52     _CustomZone.run (dart:async/zone.dart:1001)
#53     runZoned (dart:async/zone.dart:1467)
#54     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#55     Driver.start (package:analysis_server/src/server/driver.dart:473)
#56     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#57     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1505967275263 <= {"id":"4"}
1505967275273 <= {"id":"5"}
1505967275284 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1505967276823 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/examples/hello_flutter/lib/main.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file
1505967276910 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/examples/spinning_square/lib/main.dart","errors":[{"severity":"INFO","type":"LINT","location":{"fi
1505967277161 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/snapshot/snapshot.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/Users/
1505967277193 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/snapshot/snapshot_fuchsia.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":
1505967278790 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/ui.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"/Use
1505967278801 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/window.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/Us
1505967278850 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/shell/common/diagnostic/diagnostic_server.dart","errors":[{"severity":"INFO","type":"LINT","locati
1505967278861 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/shell/testing/observatory/empty_main.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERRO
1505967278896 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/shell/testing/observatory/launcher.dart","errors":[{"severity":"INFO","type":"LINT","location":{"f
1505967278936 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/shell/testing/observatory/service_client.dart","errors":[{"severity":"INFO","type":"LINT","locatio
1505967279007 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/shell/testing/observatory/test.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file"
1505967279019 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/testing/fail_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"fil
1505967279760 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/testing_hooks.dart","errors":[]}}
1505967279780 <= {"event":"analysis.highlights","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/testing_hooks.dart","regions":[{"type":"DIRECTIVE","offset":166,"length":16},{"type":"B
1505967279805 <= {"event":"analysis.navigation","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/testing_hooks.dart","regions":[{"offset":174,"length":7,"targets":[0]},{"offset":491,"l
1505967279808 <= {"event":"analysis.overrides","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/testing_hooks.dart","overrides":[]}}
1505967279815 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/compositing.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file":"/Users/gsp
1505967279817 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/geometry.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file":"/Users/gspenc
1505967279821 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/hash_codes.dart","errors":[]}}
1505967279822 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/hooks.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/Users/gspencer/
1505967279823 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/lerp.dart","errors":[]}}
1505967279825 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/natives.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/U
1505967279839 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/painting.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file":"/Users/gspenc
1505967279844 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/pointer.dart","errors":[]}}
1505967279845 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/semantics.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"
1505967279849 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/engine/src/flutter/lib/ui/text.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/User
1505967281743 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/gspencer/code/engine/src/flutter/frontend_server/bin/starter.dart context: exception_20170920_2114
```

**Comment by bwilkerson** [comment]
There's a fairly good chance (though I haven't verified) that this is fixed in the latest 0.25.0-dev branch.
