### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by deepak-gehlot** [dart-lang/sdk#30865]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-171.4073.35`
- `1.23.0-dev.11.7`
- `IC-171.4073.35, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\RWS6~1\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.23.0-dev.11.7, server version 1.18.0, error: Analysis failed: E:\flutter\apps\lib\main.dart context: exception_20170922_182347_970
NoSuchMethodError: Class 'DynamicElementImpl' has no instance getter 'supertype'.
Receiver: Instance of 'DynamicElementImpl'
Tried calling: supertype
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:478)
#3      InheritanceManager._computeInterfaceLookupMap (package:analyzer/src/dart/resolver/inheritance_manager.dart:450)
#4      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:496)
#5      InheritanceManager.lookupOverrides (package:analyzer/src/dart/resolver/inheritance_manager.dart:205)
#6      InstanceMemberInferrer._computeFieldOverrideType (package:analyzer/src/task/strong_mode.dart:126)
#7      InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:402)
#8      List.forEach (dart:core-patch/growable_array.dart:256)
#9      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:313)
#10     InstanceMemberInferrer.inferCompilationUnit (package:analyz

**Comment by bwilkerson** [comment]
Do you happen to know what kind of code was being analyzed when this error occurred? Looking at the code in question it isn't clear how to reproduce the bug.

**Comment by bwilkerson** [comment]
Reported with more information in #32037.
