### ISSUE TITLE
Failure in intelliJ analyzer plugin 1.24.2

### ISSUE THREAD

**Issue by KOGI** [dart-lang/sdk#30881]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-172.4155.36`
- `1.24.2`
- `IU-172.4155.36, JRE 1.8.0_152-release-915-b11x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1680x1050, 1680x1050`

# Exception

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, FATAL error: Failed to handle request: {id: 9928, method: edit.getFixes, params: {file: D:\code\foo\bar\lib\src\routes\webhooks.dart, offset: 27796}, clientRequestTime: 1506398284655}
RangeError (index): Invalid value: Not in range 0..27791, inclusive: 27795
#0      String.codeUnitAt (dart:core-patch/string_patch.dart:927)
#1      CorrectionUtils.getLineContentStart (package:analysis_server/src/services/correction/util.dart:918)
#2      CorrectionUtils.getLinesRange (package:analysis_server/src/services/correction/util.dart:981)
#3      CorrectionUtils.getLinesRangeStatements (package:analysis_server/src/services/correction/util.dart:996)
#4      FixProcessor._addFix_removeDeadCode (package:analysis_server/src/services/correction/fix_internal.dart:1863)
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:251)
<asynchronous suspension>
#6      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:85)
<asynchronous suspension>
#7      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:242)
<asynchronous suspension>
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:319)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:975)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:971)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     _CustomZone.runGuarded (dart:async/zone.dart:901)
#15     runZoned (dart:async/zone.dart:1465)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:970)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:168)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:159)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#21     _rootRunUnary (dart:async/zone.dart:1128)
#22     _CustomZone.runUnary (dart:async/zone.dart:1012)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#33     _rootRunUnary (dart:async/zone.dart:1128)
#34     _CustomZone.runUnary (dart:async/zone.dart:1012)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#46     _rootRunUnary (dart:async/zone.dart:1128)
#47     _CustomZone.runUnary (dart:async/zone.dart:1012)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#51     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#52     _StreamController._add (dart:async/stream_controller.dart:667)
#53     _StreamController.add (dart:async/stream_controller.dart:613)
#54     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#55     _rootRunUnary (dart:async/zone.dart:1132)
#56     _CustomZone.runUnary (dart:async/zone.dart:1012)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#60     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#61     _StreamController._add (dart:async/stream_controller.dart:667)
#62     _StreamController.add (dart:async/stream_controller.dart:613)
#63     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#64     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

```
1506398285234 <= {"event":"analysis.overrides","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","overrides":[{"offset":72,"length":12,"superclassMember":{"element"
1506398285237 <= {"id":"9923","result":{}}
1506398285326 => {"id":"9931","method":"analysis.updateContent","params":{"files":{"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart":{"type":"add","content":"\npart of katana_engine
1506398285328 => {"id":"9932","method":"edit.getAssists","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","offset":27791,"length":0},"clientRequestTime":1506398285
1506398285331 => {"id":"9933","method":"edit.getAssists","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","offset":27791,"length":0},"clientRequestTime":1506398285
1506398287331 <= {"event":"analysis.errors","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","errors":[{"severity":"WARNING","type":"STATIC_WARNING","location":{"f
1506398287334 <= {"id":"9924","result":{"assists":[{"message":"Convert into block body","edits":[{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","fileStamp":0,"edits":[{"o
1506398287334 <= {"id":"9925","result":{"assists":[{"message":"Convert into block body","edits":[{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","fileStamp":0,"edits":[{"o
1506398287335 <= {"id":"9926","result":{"assists":[]}}
1506398287335 <= {"id":"9927","result":{"assists":[]}}
1506398287335 <= {"id":"9929","result":{"assists":[{"message":"Surround with block","edits":[{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","fileStamp":0,"edits":[{"offse
1506398287336 <= {"id":"9930","result":{"assists":[{"message":"Surround with block","edits":[{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","fileStamp":0,"edits":[{"offse
1506398287342 <= {"event":"analysis.highlights","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","regions":[{"type":"DIRECTIVE","offset":1,"length":22},{"type":"BU
1506398287351 <= {"event":"analysis.navigation","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","regions":[{"offset":9,"length":13,"targets":[0]},{"offset":31,"le
1506398287352 <= {"event":"analysis.overrides","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","overrides":[{"offset":72,"length":12,"superclassMember":{"element"
1506398287354 <= {"id":"9931","result":{}}
1506398287356 => {"id":"9934","method":"analysis.updateContent","params":{"files":{"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart":{"type":"add","content":"\npart of katana_engine
1506398287360 => {"id":"9935","method":"edit.getAssists","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","offset":27790,"length":0},"clientRequestTime":1506398287
1506398287368 => {"id":"9936","method":"edit.getAssists","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","offset":27790,"length":0},"clientRequestTime":1506398287
1506398287377 <= {"id":"9934","result":{}}
1506398289287 <= {"event":"analysis.errors","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"D:\\cod
1506398289287 <= {"id":"9932","result":{"assists":[]}}
1506398289287 <= {"id":"9933","result":{"assists":[]}}
1506398289287 <= {"id":"9935","result":{"assists":[]}}
1506398289287 <= {"id":"9936","result":{"assists":[]}}
1506398289291 <= {"event":"analysis.highlights","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","regions":[{"type":"DIRECTIVE","offset":1,"length":22},{"type":"BU
1506398289297 <= {"event":"analysis.navigation","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","regions":[{"offset":9,"length":13,"targets":[0]},{"offset":31,"le
1506398289297 <= {"event":"analysis.overrides","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\routes\\webhooks.dart","overrides":[{"offset":72,"length":12,"superclassMember":{"element"
1506398289321 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 9928, method: edit.getFixes, params: {file: D:\\code\\foo\\bar\\lib\\src\\routes\\w
1506398289321 <= {"event":"analysis.errors","params":{"file":"D:\\code\\foo\\bar\\lib\\src\\models\\line.dart","errors":[]}}
```

**Comment by devoncarew** [comment]
@scheglov, this is from a `1.24.2` sdk. If the exception is no longer relevant (the source lines don't map to something), feel free to close.

**Comment by scheglov** [comment]
This is a known bug - sometimes there is race condition when we use element model from one files state, but the files have been changed since then, so offsets are not valid anymore. The proper solution is to switch Quick Assists/Fixes to `AnalysisSession`, once we find time to do this.

**Comment by bwilkerson** [comment]
> This is a known bug ...

Is there another open issue for that bug, or is this it?

**Comment by scheglov** [comment]
I'm not aware of any issue that describes this problem and originates from us, vs. a user that stumbles upon it.

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
