### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#30885]
Test tests/lib_2/html/custom/document_register_type_extensions_test.dart crashes the dartdevc compiler.

Here's the stack trace:
```
Invalid library root. /b/swarming/w/ir/cache/builder/sdk/tests/lib_2/html/custom/ does not contain /b/swarming/w/ir/cache/builder/sdk/tests/lib_2/html/utils.dart
#0      jsLibraryName (package:dev_compiler/src/compiler/code_generator.dart:6073:5)
#1      CodeGenerator._emitModule (package:dev_compiler/src/compiler/code_generator.dart:331:32)
#2      CodeGenerator.compile (package:dev_compiler/src/compiler/code_generator.dart:250:18)
#3      ModuleCompiler.compile (package:dev_compiler/src/compiler/compiler.dart:221:28)
#4      _compile (package:dev_compiler/src/compiler/command.dart:187:25)
#5      compile (package:dev_compiler/src/compiler/command.dart:57:5)
#6      runBatch (file:///b/swarming/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:62:27)
<asynchronous suspension>
#7      main (file:///b/swarming/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:25:11)
<asynchronous suspension>
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
```

**Comment by jmesserly** [comment]
this will be fixed with https://github.com/dart-lang/sdk/issues/32211
