### ISSUE TITLE
Analysis server crash: NoSuchMethodError: The method 'contains' was called on null.

### ISSUE THREAD

**Issue by jakobr-google** [dart-lang/sdk#30901]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.70`
- `1.25.0-dev.9.0`
- `IU-171.4694.70, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-93-generic unknown, screens 1920x1200, 1920x1200`

# Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 1.25.0-dev.9.0, server version 1.18.4, error: Captured exception
NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains(Instance of 'FileState')
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:242)
#3      PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#4      FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:216)
#5      FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:289)
#6      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:814)
<asynchronous suspension>
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1659)
<asynchronous suspension>
#8      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1602)
#9      new AnalysisServer (package:analysis_server/src/analysis_server.dart:379)
#10     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#11     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#12     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:430)
#13     _rootRun (dart:async/zone.dart:1120)
```

```
1506505047483 <= {"id":"187","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_th
1506505047486 => {"id":"188","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":314,"length":0}
1506505047488 <= {"id":"188","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_th
1506505047488 => {"id":"189","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":314,"length":0}
1506505047489 => {"id":"190","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":314,"length":0}
1506505047491 <= {"id":"189","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_th
1506505047491 => {"id":"191","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":314,"length":0}
1506505047493 <= {"id":"190","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_th
1506505047493 => {"id":"192","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":314,"length":0}
1506505047495 <= {"id":"191","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_th
1506505047495 => {"id":"193","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":314,"length":0}
1506505047496 <= {"id":"192","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_th
1506505047497 => {"id":"194","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":314,"length":0}
1506505047498 <= {"id":"193","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_th
1506505047499 => {"id":"195","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":314,"length":0}
1506505047500 <= {"id":"194","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_th
1506505047501 => {"id":"196","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":314,"length":0}
1506505047502 <= {"id":"195","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_th
1506505047504 <= {"id":"196","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_th
1506505048670 => {"id":"197","method":"analysis.updateContent","params":{"files":{"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart":{"type":"add","
1506505048670 => {"id":"198","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":354,"length":0}
1506505048678 => {"id":"199","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":354,"length":0}
1506505048679 => {"id":"200","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":354,"length":0}
1506505048682 => {"id":"201","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":354,"length":0}
1506505048682 => {"id":"202","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":354,"length":0}
1506505048684 <= {"id":"197","result":{}}
1506505048686 => {"id":"203","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":354,"length":0}
1506505048686 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1506505048693 => {"id":"204","method":"edit.getAssists","params":{"file":"/usr/local/google/home/jakobr/src/dart-sdk/sdk/tests/lib_2/html/js_typed_interop_bind_this_test.dart","offset":354,"length":0}
1506505048775 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The method 'contains' was called on null.\nReceiver: null\nTried call
```

**Comment by nex3** [comment]
I'm also seeing this with 2.0.0-dev.3.

**Comment by bwilkerson** [comment]
@scheglov This can happen if the file being added has not been refreshed. Is that a valid state (in which case I can add a null check) or a symptom of a deeper problem?

**Comment by scheglov** [comment]
This is not an expected state. `FileState.refresh()` should successfully handle any file, existing or missing. There are two know cases when this happened before:
1. Exception during scanning or parsing. This should not happen, but it did happen. We [added](https://dart-review.googlesource.com/c/sdk/+/17561) a work around.
2. Damaged `ByteStore` because of race condition between the main Analysis Server isolate and the Angular plugin. This was fixed some time ago.

**Comment by bwilkerson** [comment]
@jakobr-google Do you happen to remember what you were doing at the time this occurred?

**Comment by nex3** [comment]
This has happened for me in the normal course of editing, using dart-mode for Emacs.

**Comment by bwilkerson** [comment]
Thanks. Can you remember any other details? Were you, for example, running a git command at the same time? Were you using a newer syntax that analyzer might not have yet understood?

**Comment by nex3** [comment]
I'm sure some git stuff was happening during the lifetime of the analysis server, and presumably the code occasionally got into invalid states I was editing the file. I don't remember anything more specific than that, though.

**Comment by jakobr-google** [comment]
In my case, I was working on the Dart 2 test migration, so I had the entire SDK open in Intellij. IIRC, this mostly occurred when I was switching branches, so files were being added and removed.

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
