### ISSUE TITLE
Invalid import URI causes exception

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30984]
```dart
import 'stuff_\$platform.dart';
```

```exception
  @29: Expected a String, but got ';'.
  null
  #0      Listener.handleUnrecoverableError (package:front_end/src/fasta/parser/listener.dart:1145:5)
  #1      Parser.reportUnrecoverableErrorWithToken (package:front_end/src/fasta/parser/parser.dart:4590:23)
  #2      Parser.parseStringPart (package:front_end/src/fasta/parser/parser.dart:1123:11)
  #3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:3975:15)
  #4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:3915:13)
  #5      Parser.parseLiteralStringOrRecoverExpression (package:front_end/src/fasta/parser/parser.dart:2430:14)
  #6      Parser.parseImport (package:front_end/src/fasta/parser/parser.dart:436:13)
  #7      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:384:14)
  #8      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:300:14)
  #9      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:274:15)
  #10     computeUnlinkedUnit (package:front_end/src/incremental/unlinked_unit.dart:25:32)
  #11     FileState.refresh (package:front_end/src/incremental/file_state.dart:170:23)
```

and
```dart
library lib;
part '${'a'}.dart';
```

```exception
  RangeError: Value not in range: 1
  #0      _StringBase.substring (dart:core-patch/string_patch.dart:368)
  #1      unescapeString (package:front_end/src/fasta/quote.dart:136:14)
  #2      DirectiveListener.beginLiteralString (package:front_end/src/fasta/source/directive_listener.dart:57:14)
  #3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:3955:14)
  #4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:3915:13)
  #5      Parser.parseLiteralStringOrRecoverExpression (package:front_end/src/fasta/parser/parser.dart:2430:14)
  #6      Parser.parsePart (package:front_end/src/fasta/parser/parser.dart:683:13)
  #7      Parser.parsePartOrPartOf (package:front_end/src/fasta/parser/parser.dart:675:14)
  #8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:389:14)
  #9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:300:14)
  #10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:274:15)
  #11     computeUnlinkedUnit (package:front_end/src/incremental/unlinked_unit.dart:25:32)
  #12     FileState.refresh (package:front_end/src/incremental/file_state.dart:170:23)
```

**Comment by peter-ahe-google** [comment]
I'd like to only parse and scan files twice, inside fasta. I don't think the directive listener belongs in the pipeline.

**Comment by peter-ahe-google** [comment]
The second error also exists in Fasta and I've filed #30994.

**Comment by scheglov** [comment]
We use Fasta parser for two purposes:
1. Build dependency graph. So that we can build ordered library cycles, and decide whether we can read results for some cycles from the cache, or recompile.
2. Build API signatures, which are based on tokens outside of method bodies, excluding comments. API signatures are used to compile full signatures of library cycles. We might stop using them when we switch to depending on outlines of direct dependencies. But we still need to build dependency graphs.

**Comment by sigmundch** [comment]
filed #31000 to track the general problem about how we get the dependency graph in one step

**Comment by bwilkerson** [comment]
@scheglov The parser appears to handle both of these cases. Could you clarify what the remaining problems are (or close the issue if there are none)?

**Comment by peter-ahe-google** [comment]
The directive listener is deprecated. If this bug can be reproduced by running fasta, please reopen.

**Comment by MichaelRFairhurst** [comment]
I think this is still a problem.

On the latest:

```
00:00 +0 -1: CompileTimeErrorCodeTest_Kernel | test_uriWithInterpolation_nonConstant [E]
  RangeError: Value not in range: 1
  #0      _StringBase.substring (dart:core-patch/dart:core/string_patch.dart:372)
  #1      unescapeString (package:front_end/src/fasta/quote.dart:136:14)
  #2      DirectiveListener.beginLiteralString (package:front_end/src/fasta/source/directive_listener.dart:57:14)
  #3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4966:14)
  #4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4919:13)
  #5      Parser.parseLiteralStringOrRecoverExpression (package:front_end/src/fasta/parser/parser.dart:3198:14)
  #6      Parser.parsePart (package:front_end/src/fasta/parser/parser.dart:835:13)
  #7      Parser.parsePartOrPartOf (package:front_end/src/fasta/parser/parser.dart:822:14)
  #8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:482:16)
  #9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:365:14)
  #10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:308:15)
  #11     computeUnlinkedUnit (package:front_end/src/incremental/unlinked_unit.dart:25:32)
  #12     FileState.refresh (package:front_end/src/incremental/file_state.dart:208:23)
  <asynchronous suspension>
  #13     FileSystemState.getFile (package:front_end/src/incremental/file_state.dart:461:18)
  <asynchronous suspension>
  #14     KernelDriver.getKernelSequence.<anonymous closure>.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:278:31)
  <asynchronous suspension>
  #15     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
  <asynchronous suspension>
  #16     KernelDriver.getKernelSequence.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:277:25)
  <asynchronous suspension>
  #17     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
  <asynchronous suspension>
  #18     KernelDriver.runWithFrontEndContext.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:340:22)
  #19     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
  #20     _rootRun (dart:async/zone.dart:1124)
  #21     _CustomZone.run (dart:async/zone.dart:1021)
  #22     runZoned (dart:async/zone.dart:1499)
  #23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
  #24     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
  #25     KernelDriver.runWithFrontEndContext (package:front_end/src/incremental/kernel_driver.dart:338:34)
  <asynchronous suspension>
  #26     KernelDriver.getKernelSequence (package:front_end/src/incremental/kernel_driver.dart:261:18)
  <asynchronous suspension>
  #27     KernelDriver.getKernel (package:front_end/src/incremental/kernel_driver.dart:227:43)
  <asynchronous suspension>
  #28     KernelContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/kernel_context.dart:160:48)
  <asynchronous suspension>
  #29     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
  <asynchronous suspension>
  #30     KernelContext.forSingleLibrary (package:analyzer/src/dart/analysis/kernel_context.dart:158:19)
  <asynchronous suspension>
  #31     AnalysisDriver._createKernelContext (package:analyzer/src/dart/analysis/driver.dart:1339:32)
  <asynchronous suspension>
  #32     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1192:35)
  <asynchronous suspension>
  #33     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
  <asynchronous suspension>
  #34     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183:20)
  <asynchronous suspension>
  #35     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:879:19)
  <asynchronous suspension>
  #36     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1887:24)
  <asynchronous suspension>
  #37     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1830:5)
  #38     ResolverTestCase.resetWith (file:///home/mfairhurst/dart/sdk2/sdk/pkg/analyzer/test/generated/resolver_test_case.dart:700:17)
  #39     ResolverTestCase.reset (file:///home/mfairhurst/dart/sdk2/sdk/pkg/analyzer/test/generated/resolver_test_case.dart:654:5)
  #40     ResolverTestCase.setUp (file:///home/mfairhurst/dart/sdk2/sdk/pkg/analyzer/test/generated/resolver_test_case.dart:802:5)
  #41     _LocalInstanceMirror._invoke (dart:mirrors-patch/dart:mirrors/mirrors_impl.dart:531)
  #42     _LocalInstanceMirror.invoke (dart:mirrors-patch/dart:mirrors/mirrors_impl.dart:527)
  #43     _LocalClosureMirror.apply (dart:mirrors-patch/dart:mirrors/mirrors_impl.dart:555)
  #44     _invokeSymbolIfExists (package:test_reflective_loader/test_reflective_loader.dart:215:32)
  #45     _runTest (package:test_reflective_loader/test_reflective_loader.dart:238:10)
  #46     defineReflectiveTests.<anonymous closure>.<anonymous closure> (package:test_reflective_loader/test_reflective_loader.dart:126:18)
  #47     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:139:19)
  <asynchronous suspension>
  #48     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:206:15)
  <asynchronous suspension>
  #49     _rootRun (dart:async/zone.dart:1124)
  #50     _CustomZone.run (dart:async/zone.dart:1021)
  #51     runZoned (dart:async/zone.dart:1499)
  #52     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:203:5)
  #53     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:137:29)
  <asynchronous suspension>
  #54     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:351:23)
  <asynchronous suspension>
  #55     new Future.<anonymous closure> (dart:async/future.dart:174)
  #56     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:189:15)
  #57     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:99:48)
  #58     _rootRun (dart:async/zone.dart:1120)
  #59     _CustomZone.run (dart:async/zone.dart:1021)
  #60     _CustomZone.runGuarded (dart:async/zone.dart:923)
  #61     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
  #62     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:189:15)
  #63     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:99:48)
  #64     _rootRun (dart:async/zone.dart:1124)
  #65     _CustomZone.run (dart:async/zone.dart:1021)
  #66     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947)
  #67     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
  #68     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:367)
  #69     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:401)
  #70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
  
  package:analyzer/src/dart/analysis/driver.dart 1256:9              AnalysisDriver._computeAnalysisResult.<fn>
  package:front_end/src/base/performance_logger.dart 52:21           PerformanceLog.runAsync
  package:analyzer/src/dart/analysis/driver.dart 1183:20             AnalysisDriver._computeAnalysisResult
  package:analyzer/src/dart/analysis/driver.dart 879:19              AnalysisDriver.performWork
  package:analyzer/src/dart/analysis/driver.dart 1887:24             AnalysisDriverScheduler._run
  package:analyzer/src/dart/analysis/driver.dart 1830:5              AnalysisDriverScheduler.start
  test/generated/resolver_test_case.dart 700:17                      ResolverTestCase.resetWith
  test/generated/resolver_test_case.dart 654:5                       ResolverTestCase.reset
  test/generated/resolver_test_case.dart 802:5                       ResolverTestCase.setUp
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 531              _LocalInstanceMirror._invoke
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 527              _LocalInstanceMirror.invoke
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 555              _LocalClosureMirror.apply
  package:test_reflective_loader/test_reflective_loader.dart 215:32  _invokeSymbolIfExists
  package:test_reflective_loader/test_reflective_loader.dart 238:10  _runTest
  package:test_reflective_loader/test_reflective_loader.dart 126:18  defineReflectiveTests.<fn>.<fn>
  package:test/src/backend/declarer.dart 139:19                      Declarer.test.<fn>.<fn>
  package:test/src/backend/invoker.dart 206:15                       Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1124                                          _rootRun
  dart:async/zone.dart 1021                                          _CustomZone.run
  dart:async/zone.dart 1499                                          runZoned
  package:test/src/backend/invoker.dart 203:5                        Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 137:29                      Declarer.test.<fn>
  package:test/src/backend/invoker.dart 351:23                       Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/future.dart 174                                         new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 189:15       StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 99:48        StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1120                                          _rootRun
  dart:async/zone.dart 1021                                          _CustomZone.run
  dart:async/zone.dart 923                                           _CustomZone.runGuarded
  dart:async/zone.dart 963                                           _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 189:15       StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 99:48        StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124                                          _rootRun
  dart:async/zone.dart 1021                                          _CustomZone.run
  dart:async/zone.dart 947                                           _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21                    Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 367                _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 401                _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 163             _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22                                     _Completer.completeError
  package:analyzer/src/dart/analysis/driver.dart                     AnalysisDriver._computeAnalysisResult.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062                                          _CustomZone.registerBinaryCallback
  dart:async-patch/dart:async/async_patch.dart 49                    _asyncErrorWrapperHelper
  package:analyzer/src/dart/analysis/driver.dart 1183:75             AnalysisDriver._computeAnalysisResult.<fn>
  package:front_end/src/base/performance_logger.dart 52:21           PerformanceLog.runAsync
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045                                          _CustomZone.registerCallback
  dart:async/zone.dart 962                                           _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                             scheduleMicrotask
  dart:async/future.dart 198                                         new Future.microtask
  package:front_end/src/base/performance_logger.dart 47:58           PerformanceLog.runAsync
  package:analyzer/src/dart/analysis/driver.dart 1183:20             AnalysisDriver._computeAnalysisResult
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045                                          _CustomZone.registerCallback
  dart:async/zone.dart 962                                           _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                             scheduleMicrotask
  dart:async/future.dart 198                                         new Future.microtask
  package:analyzer/src/dart/analysis/driver.dart 1147:47             AnalysisDriver._computeAnalysisResult
  package:analyzer/src/dart/analysis/driver.dart 879:19              AnalysisDriver.performWork
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045                                          _CustomZone.registerCallback
  dart:async/zone.dart 962                                           _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                             scheduleMicrotask
  dart:async/future.dart 198                                         new Future.microtask
  package:analyzer/src/dart/analysis/driver.dart 869:36              AnalysisDriver.performWork
  package:analyzer/src/dart/analysis/driver.dart 1887:24             AnalysisDriverScheduler._run
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053                                          _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 40                    _asyncThenWrapperHelper
  package:analyzer/src/dart/analysis/driver.dart 1845:29             AnalysisDriverScheduler._run
  package:analyzer/src/dart/analysis/driver.dart 1830:5              AnalysisDriverScheduler.start
  test/generated/resolver_test_case.dart 700:17                      ResolverTestCase.resetWith
  test/generated/resolver_test_case.dart 654:5                       ResolverTestCase.reset
  test/generated/resolver_test_case.dart 802:5                       ResolverTestCase.setUp
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 531              _LocalInstanceMirror._invoke
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 527              _LocalInstanceMirror.invoke
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 555              _LocalClosureMirror.apply
  package:test_reflective_loader/test_reflective_loader.dart 215:32  _invokeSymbolIfExists
  package:test_reflective_loader/test_reflective_loader.dart 238:10  _runTest
  package:test_reflective_loader/test_reflective_loader.dart 126:18  defineReflectiveTests.<fn>.<fn>
  package:test/src/backend/declarer.dart 139:19                      Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053                                          _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 40                    _asyncThenWrapperHelper
  package:test/src/backend/declarer.dart 137:66                      Declarer.test.<fn>.<fn>
  package:test/src/backend/invoker.dart 206:15                       Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045                                          _CustomZone.registerCallback
  dart:async/zone.dart 962                                           _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                             scheduleMicrotask
  dart:async/future.dart 198                                         new Future.microtask
  package:test/src/backend/invoker.dart 203:23                       Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1124                                          _rootRun
  dart:async/zone.dart 1021                                          _CustomZone.run
  dart:async/zone.dart 1499                                          runZoned
  package:test/src/backend/invoker.dart 203:5                        Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 137:29                      Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045                                          _CustomZone.registerCallback
  dart:async/zone.dart 962                                           _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                             scheduleMicrotask
  dart:async/future.dart 198                                         new Future.microtask
  package:test/src/backend/declarer.dart 122:66                      Declarer.test.<fn>
  package:test/src/backend/invoker.dart 351:23                       Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045                                          _CustomZone.registerCallback
  dart:async/zone.dart 962                                           _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                             scheduleMicrotask
  dart:async/future.dart 198                                         new Future.microtask
  package:test/src/backend/invoker.dart 350:29                       Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/future.dart 174                                         new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 189:15       StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 99:48        StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1120                                          _rootRun
  dart:async/zone.dart 1021                                          _CustomZone.run
  dart:async/zone.dart 923                                           _CustomZone.runGuarded
  dart:async/zone.dart 963                                           _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 189:15       StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 99:48        StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124                                          _rootRun
  dart:async/zone.dart 1021                                          _CustomZone.run
  dart:async/zone.dart 947                                           _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21                    Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 367                _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 401                _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 163             _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045                                          _CustomZone.registerCallback
  dart:async/zone.dart 962                                           _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                           new Timer
  dart:async/timer.dart 87                                           Timer.run
  dart:async/future.dart 172                                         new Future
  package:test/src/backend/invoker.dart 350:13                       Invoker._onRun.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045                                          _CustomZone.registerCallback
  dart:async/zone.dart 962                                           _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                             scheduleMicrotask
  dart:async/future.dart 198                                         new Future.microtask
  package:test/src/backend/invoker.dart 337:25                       Invoker._onRun.<fn>.<fn>
  dart:async/zone.dart 1124                                          _rootRun
  dart:async/zone.dart 1021                                          _CustomZone.run
  dart:async/zone.dart 1499                                          runZoned
  package:test/src/backend/invoker.dart 337:7                        Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 93:24                           Chain.capture.<fn>
  dart:async/zone.dart 1124                                          _rootRun
  dart:async/zone.dart 1021                                          _CustomZone.run
  dart:async/zone.dart 1499                                          runZoned
  package:stack_trace/src/chain.dart 91:12                           Chain.capture
  package:test/src/backend/invoker.dart 336:11                       Invoker._onRun
  package:test/src/backend/live_test_controller.dart 188:11          LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40:31           _LiveTest.run
  dart:async/future.dart 200                                         new Future.microtask.<fn>
  dart:async/schedule_microtask.dart 41                              _microtaskLoop
  dart:async/schedule_microtask.dart 50                              _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/isolate_patch.dart 111             _runPendingImmediateCallback
  dart:isolate-patch/dart:isolate/isolate_patch.dart 164             _RawReceivePortImpl._handleMessage
```

**Comment by sigmundch** [comment]
@MichaelRFairhurst - it is my understanding that kernel driver is still using the "directive listener" and that Peter wants to switch all clients to directly gather the data they need from fasta instead. (In essence there would otherwise be a lot of duplication of error recovery if we don't). 

@peter-ahe-google can comment in more detail, but I believe some small changes need to be made inside the front-end to be able to support that kind of change. I filed a new issue to better track that more clearly: https://github.com/dart-lang/sdk/issues/31553

**Comment by MichaelRFairhurst** [comment]
Thanks for the clarification Siggi, I see where I misread there! Thanks for everyone's patience as I try to help more than hinder, here!

With #31553 opened, I'm assuming this should be closed again? Will do so now, though of course, if I'm wrong please someone do re-open.
