### ISSUE TITLE
Invalid dynamic use causes exception

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30985]
```dart
class A {
  const A([x]);
}
class B {
  dynamic @A(const A()) x;
}
```

```
  @40: Unexpected token 'dynamic'.
  null
  #0      Listener.handleUnrecoverableError (package:front_end/src/fasta/parser/listener.dart:1145:5)
  #1      Parser.reportUnrecoverableErrorWithToken (package:front_end/src/fasta/parser/parser.dart:4590:23)
  #2      Parser.reportUnexpectedToken (package:front_end/src/fasta/parser/parser.dart:4638:12)
  #3      Parser.parseMethod.parseModifierList (package:front_end/src/fasta/parser/parser.dart:2819:11)
  #4      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:2828:22)
  #5      Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2766:11)
  #6      Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2658:15)
  #7      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1086:13)
  #8      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1056:14)
  #9      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:366:14)
  #10     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:300:14)
  #11     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:274:15)
  #12     computeUnlinkedUnit (package:front_end/src/incremental/unlinked_unit.dart:29:10)
  #13     FileState.refresh (package:front_end/src/incremental/file_state.dart:170:23)
```

**Comment by peter-ahe-google** [comment]
FWIW, Fasta correctly reports this error but doesn't recover well.

**Comment by scheglov** [comment]
We use Fasta parser for two purposes:
1. Build dependency graph. So that we can build ordered library cycles, and decide whether we can read results for some cycles from the cache, or recompile.
2. Build API signatures, which are based on tokens outside of method bodies, excluding comments. API signatures are used to compile full signatures of library cycles. We might stop using them when we switch to depending on outlines of direct dependencies. But we still need to build dependency graphs.

**Comment by peter-ahe-google** [comment]
Siggi and I just had a productive discussion about how to compute dependency graphs via the first few steps of Fasta's outline phase.

**Comment by sigmundch** [comment]
I filed #31000 to track the general problem here.

**Comment by bwilkerson** [comment]
FYI, I added an AstBuilder test for this (https://dart-review.googlesource.com/c/sdk/+/25582) and it passed without any changes.

**Comment by peter-ahe-google** [comment]
This appears to have been fixed. I see these error messages from Fasta:

```
t.dart:5:3: Error: Unexpected token 'dynamic'.
  dynamic @A(const A()) x;
  ^
t.dart:5:14: Error: Can't have modifier 'const' here.
Try removing 'const'.
  dynamic @A(const A()) x;
             ^
t.dart:5:25: Error: Expected a block.
Try adding {}.
  dynamic @A(const A()) x;
                        ^
t.dart:5:25: Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
Try adding the name of the type of the variable or the keyword 'var'.
  dynamic @A(const A()) x;
                        ^
```
