### ISSUE TITLE
Invalid URI causes LibraryDependency to disappear

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30997]
```dart
import '[invalid uri]' deferred as p;
main() {
  p.loadLibrary();
}
```

```kernel
library;
import self as self;

static const field dynamic #errors = const <dynamic>["file:///test.dart:1:9: Error: Couldn't parse URI '[invalid uri]':\n  Invalid character.\nimport '[invalid uri]' deferred as p;\n        ^"]/* from null */;
static method main() → dynamic {
  throw invalid-expression;
}
```

The problem is that when Analyzer resolves `p.loadLibrary();` it does not know that `p` is actually  defined, because there is no corresponding `LibraryDependency` is the kernel.

**Comment by peter-ahe-google** [comment]
I initially assigned @sigmundch as I thought this was an issue about deferred loading which he is working on.

However, this is  about error recovery.

**Comment by peter-ahe-google** [comment]
Aske, I think this is an issue caused by 394f854fec5e6b6710f19e5fe60e95b8c8761b74. I didn't notice it during code review, but the FormatException is caught and handled at the wrong level.

So we also have this crash:

```
$ cat -n t.dart
     1  part "[bad]";
$ ./pkg/front_end/tool/fasta compile t.dart --platform=xcodebuild/ReleaseX64/patched_sdk/platform.dill
Unhandled exception:
FormatException: Invalid character (at character 1)
[bad]
^

#0      _Uri._fail (dart:core/uri.dart:1597)
#1      _Uri._normalize (dart:core/uri.dart:2292)
#2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2248)
#3      _Uri._makePath (dart:core/uri.dart:2096)
#4      new _Uri.notSimple (dart:core/uri.dart:1460)
#5      Uri.parse (dart:core/uri.dart:1012)
#6      _Uri.resolve (dart:core/uri.dart:2473)
#7      SourceLibraryBuilder.addPart (package:front_end/src/fasta/source/source_library_builder.dart:197:25)
#8      OutlineBuilder.endPart (package:front_end/src/fasta/source/outline_builder.dart:226:15)
#9      Parser.parsePart (package:front_end/src/fasta/parser/parser.dart:686:14)
#10     Parser.parsePartOrPartOf (package:front_end/src/fasta/parser/parser.dart:675:14)
#11     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:389:14)
#12     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:300:14)
#13     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:274:15)
#14     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:166:37)
<asynchronous suspension>
#15     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:145:13)
<asynchronous suspension>
#16     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:236:20)
<asynchronous suspension>
#17     CompileTask.buildOutline (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:145:38)
<asynchronous suspension>
#18     CompileTask.compile (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:157:39)
<asynchronous suspension>
#19     compile.<anonymous closure> (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:98:25)
<asynchronous suspension>
#20     withGlobalOptions.<anonymous closure> (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:342:13)
#21     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#22     _rootRun (dart:async/zone.dart:1124)
#23     _CustomZone.run (dart:async/zone.dart:1021)
#24     runZoned (dart:async/zone.dart:1499)
#25     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#26     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#27     withGlobalOptions (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:335:26)
#28     compile (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:91:18)
<asynchronous suspension>
#29     compileEntryPoint (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:49:11)
<asynchronous suspension>
#30     main (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#31     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
