### ISSUE TITLE
Analyzer crash

### ISSUE THREAD

**Issue by brianegan** [dart-lang/sdk#31023]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-172.4155.35`
- `1.25.0-dev.11.0`
- `WS-172.4155.35, JRE 1.8.0_152-release-915-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1440x900  Retina`

# Exception

```
Dart analysis server, SDK version 1.25.0-dev.11.0, server version 1.18.4, error: Failed to handle completion domain request: {id: 26182, method: completion.getSuggestions, params: {file: /Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart, offset: 2102}, clientRequestTime: 1507243306323}
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      _OpTypeAstVisitor.visitNamedExpression.<anonymous closure> (package:analyzer_plugin/src/utilities/completion/optype.dart:745)
#3      Object&ListMixin.firstWhere (dart:collection/list.dart:127)
#4      _OpTypeAstVisitor.visitNamedExpression (package:analyzer_plugin/src/utilities/completion/optype.dart:743)
#5      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7704)
#6      new OpType.forCompletion (package:analyzer_plugin/src/utilities/completion/optype.dart:117)
#7      DartCompletionRequestImpl.opType (package:analysis_server/src/services/completion/dart/completion_manager.dart:166)
#8      DartCompletionRequestImpl.includeIdentifiers (package:analysis_server/src/services/completion/dart/completion_manager.dart:148)
#9      ImportedReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/imported_reference_contributor.dart:44)
<asynchronous suspension>
#10     DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:74)
<asynchronous suspension>
#11     CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:104)
<asynchronous suspension>
#12     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:219)
<asynchronous suspension>
#13     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:152)
#14     _rootRun (dart:async/zone.dart:1120)
#15     _CustomZone.run (dart:async/zone.dart:1001)
#16     _CustomZone.runGuarded (dart:async/zone.dart:901)
#17     runZoned (dart:async/zone.dart:1465)
#18     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:149)
#19     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:682)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#21     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:678)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     _CustomZone.runGuarded (dart:async/zone.dart:901)
#25     runZoned (dart:async/zone.dart:1465)
#26     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:677)
#27     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#29     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#30     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#31     _rootRunUnary (dart:async/zone.dart:1128)
#32     _CustomZone.runUnary (dart:async/zone.dart:1012)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#39     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#40     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#41     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#43     _rootRunUnary (dart:async/zone.dart:1128)
#44     _CustomZone.runUnary (dart:async/zone.dart:1012)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#50     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#51     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#52     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#53     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#54     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#55     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#56     _rootRunUnary (dart:async/zone.dart:1128)
#57     _CustomZone.runUnary (dart:async/zone.dart:1012)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#62     _StreamController._add (dart:async/stream_controller.dart:667)
#63     _StreamController.add (dart:async/stream_controller.dart:613)
#64     _Socket._onData (dart:io-patch/socket_patch.dart:1643)
#65     _rootRunUnary (dart:async/zone.dart:1132)
#66     _CustomZone.runUnary (dart:async/zone.dart:1012)
#67     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#68     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#69     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#70     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#71     _StreamController._add (dart:async/stream_controller.dart:667)
#72     _StreamController.add (dart:async/stream_controller.dart:613)
#73     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
#74     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#75     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#76     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#77     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#78     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

```
1507243305551 <= {"event":"analysis.errors","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"fil
1507243305552 <= {"event":"analysis.highlights","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":39},{"type":"BU
1507243305554 <= {"event":"analysis.navigation","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","regions":[{"offset":7,"length":31,"targets":[0]},{"offset":47,"le
1507243305554 <= {"event":"analysis.overrides","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","overrides":[{"offset":288,"length":11,"superclassMember":{"element
1507243305554 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1507243305554 <= {"event":"analysis.implemented","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","classes":[],"members":[]}}
1507243305853 => {"id":"26176","method":"edit.getFixes","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","offset":2071},"clientRequestTime":1507243305853}
1507243305854 => {"id":"26177","method":"analysis.updateContent","params":{"files":{"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart":{"type":"add","content":"import 'package:flutte
1507243305855 <= {"id":"26177","result":{}}
1507243305855 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1507243305865 => {"id":"26178","method":"edit.getAssists","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","offset":2101,"length":0},"clientRequestTime":1507243305
1507243305880 <= {"event":"analysis.errors","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"fi
1507243305880 <= {"id":"26176","result":{"fixes":[]}}
1507243305881 <= {"id":"26178","result":{"assists":[{"message":"Convert into expression body","edits":[{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","fileStamp":0,"edits
1507243305882 <= {"event":"analysis.highlights","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":39},{"type":"BU
1507243305884 <= {"event":"analysis.navigation","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","regions":[{"offset":7,"length":31,"targets":[0]},{"offset":47,"le
1507243305884 <= {"event":"analysis.overrides","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","overrides":[{"offset":288,"length":11,"superclassMember":{"element
1507243305884 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1507243305884 <= {"event":"analysis.implemented","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","classes":[],"members":[]}}
1507243306185 => {"id":"26179","method":"edit.getFixes","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","offset":2101},"clientRequestTime":1507243306185}
1507243306186 <= {"id":"26179","result":{"fixes":[]}}
1507243306189 => {"id":"26180","method":"edit.getAssists","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","offset":2101,"length":0},"clientRequestTime":1507243306
1507243306196 <= {"id":"26180","result":{"assists":[{"message":"Convert into expression body","edits":[{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","fileStamp":0,"edits
1507243306323 => {"id":"26181","method":"analysis.updateContent","params":{"files":{"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart":{"type":"add","content":"import 'package:flutte
1507243306323 => {"id":"26182","method":"completion.getSuggestions","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","offset":2102},"clientRequestTime":15072433063
1507243306323 <= {"id":"26181","result":{}}
1507243306323 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1507243306345 <= {"id":"26182","result":{"id":"2385"}}
1507243306345 <= {"event":"analysis.errors","params":{"file":"/Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"fil
1507243306353 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {id: 26182, method: completion.getSuggestions, params: {file: /Users/phillywig
```

```
Dart analysis server, SDK version 1.25.0-dev.11.0, server version 1.18.4, error: Failed to handle completion domain request: {id: 26182, method: completion.getSuggestions, params: {file: /Users/phillywiggins/lab/flutter_mvc/example/vanilla/lib/main.dart, offset: 2102}, clientRequestTime: 1507243306323}
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      _OpTypeAstVisitor.visitNamedExpression.<anonymous closure> (package:analyzer_plugin/src/utilities/completion/optype.dart:745)
#3      Object

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/11940
