### ISSUE TITLE
Type `_check` and `as` collide with static methods of the same name

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#31049]
Traditionally DDC compiler assumed that instance/static method names beginning with underscore were safe for the compiler to use, because Dart private members would be symbolized. This assumption is still valid for instance members, but it is no longer valid for static members/constructors. For example:

```dart
class C {
  static void _check(obj) {
    print('Called `C._check($obj)`');
  }
}
class D<T> {
  m(T obj) {
    print('Called `D<$T>.m($obj)`');
  }
}
main() {
  new D<C>().m(null);
  C._check('hello');
}
```
The VM prints:
```
Called `D<C>.m(null)`
Called `C._check(hello)`
```
However DDC overwrites the static method with the check function, resulting in an exception:
```
Called `D<C>.m(null)`
Type 'String' is not a subtype of type 'C' in strong mode Error
    at Object.dart.throw (dart_sdk.js:5118:27)
    at Object.dart.castError (dart_sdk.js:5046:15)
    at Object.dart.as (dart_sdk.js:5017:15)
    at Function.check_C (dart_sdk.js:4224:17)
    at test.main (test.js:42:10)
```
We also use `is` and `new` which are keywords and therefore safe, however we use `as` which results in a similar problem:
```dart
class C {
  static void as(obj) {
    print('Called `C.as($obj)`');
  }
}
main() {
  // works on the VM, on DDC this is compiled to `'hello' as C` which throws
  C.as('hello');
}
```

**Comment by jmesserly** [comment]
There are a few ways to fix this.

- symbolize statics, like we did before. This has a perf/code size/debug console UX cost.
- introduce a name mangling scheme to ensure some names are available for compiler use.
- use a reserved word if a sensible one exists (only `assert` and `extends` seem plausible and neither is a great fit). We can merge `as` and `_check` so we only need to find one name.

Probably name mangling is the answer here. We already do that for certain names that are invalid to use in JS.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/12481
