### ISSUE TITLE
Dartanalyzer exception

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#31067]
Wanted to try something today and hit this issue:

```
$ mkdir -p pkg/front_end/benchmarks/ikg

$ cat > pkg/front_end/benchmarks/ikg/dart2js.dart << EOF 
import 'package:compiler/src/dart2js.dart' as dart2js;
main(args) => dart2js.main(args);
EOF

$ dartanalyzer pkg/front_end/benchmarks/ikg/dart2js.dart
Analyzing pkg/front_end/benchmarks/ikg/dart2js.dart...
Unhandled exception:
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1096)
#1      CompilationUnitElementForLink.resolveTypeRef.getTypeArgument (package:analyzer/src/summary/link.dart:1103)
#2      new List.generate (dart:core/list.dart:142)
#3      ClassElementForLink_Class.buildType (package:analyzer/src/summary/link.dart:647)
#4      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1113)
#5      VariableElementForLink.declaredType (package:analyzer/src/summary/link.dart:5196)
#6      VariableElementForLink.type (package:analyzer/src/summary/link.dart:5287)
#7      PropertyAccessorElementForLink_Variable.returnType (package:analyzer/src/summary/link.dart:4548)
#8      PropertyAccessorElementForLink_Variable.asStaticType (package:analyzer/src/summary/link.dart:4501)
#9      ExprTypeComputer._doPushReference (package:analyzer/src/summary/link.dart:2485)
#10     ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2073)
#11     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:4957)
#12     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:4808)
#13     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#14     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#15     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5226)
#16     FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2700)
#17     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:673)
#18     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1308)
#19     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3672)
#20     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3408)
#21     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3330)
#22     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#23     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#24     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#25     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#26     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#27     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#28     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#29     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3373)
#30     Linker.link (package:analyzer/src/summary/link.dart:3897)
#31     relink (package:analyzer/src/summary/link.dart:132)
#32     link (package:analyzer/src/summary/link.dart:113)
...

$ dartanalyzer --version
dartanalyzer version 1.24.2
```

Guess in no case we would ever want to throw such an exception (this is not done inside sdk checkout but a download of a golem build)

@scheglov Do you know who's the best person to take a look at this?

**Comment by scheglov** [comment]
This is a very old version.
The code has been fixed some time ago.
