### ISSUE TITLE
Analysis server crashes with: NoSuchMethodError: The getter 'type' was called on null.

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#31064]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I am using VSCode for flutter/engine.

### Versions

- Dart SDK 1.24.2
- Visual Studio Code 1.17.1
- Dart Code 2.4.2

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=2.4.2
```

### Exception

Analysis failed: /Users/yjbanov/code/flutter/engine/src/dart/tests/standalone_2/deferred_transitive_import_error_test.dart context: exception_20171010_173225_906

```text
NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:632)
#3      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#4      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6224)
#5      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#6      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6222)
#7      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#8      AwaitExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1091)
#9      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239)
#10     UnifyingAstVisitor.visitAwaitExpression (package:analyzer/dart/ast/visitor.dart:2913)
#11     ResolverVisitor.visitAwaitExpression (package:analyzer/src/generated/resolver.dart:5471)
#12     AwaitExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1087)
#13     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#14     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239)
#15     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3005)
#16     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#18     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#19     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239)
#20     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#21     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7258)
#22     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#23     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#24     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239)
#25     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#26     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7270)
#27     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5542)
#28     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#29     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#30     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239)
#31     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#32     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7573)
#33     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:6014)
#34     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#35     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5204)
#36     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6239)
#37     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026)
#38     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:7566)
#39     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5990)
#40     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7558)
#41     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5980)
#42     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5197)
#43     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5647)
#44     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#45     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:551)
#46     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#47     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#48     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88)
#49     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:999)
#50     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#51     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#52     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:854)
<asynchronous suspension>
#53     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#54     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#55     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#56     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#57     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#58     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#59     _rootRun (dart:async/zone.dart:1120)
#60     _CustomZone.run (dart:async/zone.dart:1001)
#61     runZoned (dart:async/zone.dart:1467)
#62     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#63     Driver.start (package:analysis_server/src/server/driver.dart:473)
#64     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analysis_server/bin/server.dart:12)
#65     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
I believe that this has been fixed in bleeding edge. Please let me know if you're still seeing this after moving to a 2.0-dev build.
