### ISSUE TITLE
dart2js crashes when it finds "||=" operators (invalid)

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#31061]
```dart
var x = false;
main() {
  x ||= true;
}
```

crashes dart2js with the following error:
```
The compiler crashed: NoSuchMethodError: The getter 'kind' was called on null.
Receiver: null
Tried calling: kind
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ResolverVisitor.handleUpdate (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/resolution/members.dart:3461:20)
#2      ResolverVisitor.handleStaticOrTopLevelUpdate (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/resolution/members.dart:2892:12)
#3      ResolverVisitor.handleResolvedSendSet (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/resolution/members.dart:2972:14)
#4      ResolverVisitor.handleUnqualifiedSendSet (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/resolution/members.dart:3032:14)
#5      ResolverVisitor.visitSendSet (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/resolution/members.dart:3519:14)
#6      SendSet.accept (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/tree/nodes.dart:824:38)
#7      CommonResolverVisitor.visit (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:32:54)
#8      ResolverVisitor.visitExpressionStatement (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/resolution/members.dart:538:5)
#9      ExpressionStatement.accept (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/tree/nodes.dart:1695:38)
#10     CommonResolverVisitor.visit (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:32:54)
```

**Comment by rakudrama** [comment]
This feature appears to be untested on any platform.
The string `||=` does not appear in the tests/ directory.

**Comment by eernstg** [comment]
Issue #26998 already requests an implementation of the compound assignment operators `||=` and `&&=` (but we need to make sure that it actually happens!).

I'll close this because it is subsumed by #26998.

**Comment by lrhn** [comment]
While the feature isn't implemented yet, the parser shouldn't be *crashing* on any syntax.

**Comment by sigmundch** [comment]
Correct - I filed the issue because a user run into this and found a crash. Fix added in https://dart-review.googlesource.com/c/sdk/+/12760
