### ISSUE TITLE
Crash when missing semicolon after a top-level variable

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31077]
```dart
library helper;
dynamic toString = (int x) => x + 42');
```

```
  @56: Expected ';' before this.
  DONT_KNOW_HOW_TO_FIX,
  #0      Listener.handleUnrecoverableError (package:front_end/src/fasta/parser/listener.dart:1156:5)
  #1      Parser.reportUnrecoverableError (package:front_end/src/fasta/parser/parser.dart:4742:23)
  #2      Parser.expect (package:front_end/src/fasta/parser/parser.dart:1466:14)
  #3      Parser.expectSemicolon (package:front_end/src/fasta/parser/parser.dart:2566:12)
  #4      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2221:13)
  #5      Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2182:11)
  #6      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:333:14)
  #7      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:280:15)
  #8      computeUnlinkedUnit (package:front_end/src/incremental/unlinked_unit.dart:25:32)
  #9      FileState.refresh (package:front_end/src/incremental/file_state.dart:170:23)
```

@bwilkerson

**Comment by peter-ahe-google** [comment]
This is a problem with DirectiveListener. We plan to replace it with deeper integration with Fasta's outline builder.

**Comment by bwilkerson** [comment]
@scheglov The method `parseFields` has been changed to invoke `ensureSemicolon` rather than `expectSemicolon`. I suspect that this issue has been fixed. Can you verify?
