### ISSUE TITLE
Crash on extra semicolon after a block method body

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31078]
```dart
class C {
  foo() {};
}
```

```
  @20: Expected a declaration, but got ';'.
  null
  #0      Listener.handleUnrecoverableError (package:front_end/src/fasta/parser/listener.dart:1165:5)
  #1      Parser.reportUnrecoverableErrorWithToken (package:front_end/src/fasta/parser/parser.dart:4763:23)
  #2      Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2824:14)
  #3      Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2783:15)
  #4      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1090:13)
  #5      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1062:14)
  #6      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:372:14)
  #7      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:306:14)
  #8      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:280:15)
  #9      computeUnlinkedUnit (package:front_end/src/incremental/unlinked_unit.dart:29:10)
  #10     FileState.refresh (package:front_end/src/incremental/file_state.dart:170:23)
```

@bwilkerson

**Comment by peter-ahe-google** [comment]
This is a problem with DirectiveListener. We plan to replace it with deeper integration with Fasta's outline builder.

**Comment by bwilkerson** [comment]
It looks to me like a parser recovery issue.

**Comment by bwilkerson** [comment]
@scheglov This CL fixes the error recovery in the parser and probably fixes this issue: https://dart-review.googlesource.com/c/sdk/+/25460. Could you confirm?

**Comment by scheglov** [comment]
This is fixed.
Thanks.
