### ISSUE TITLE
Crash on class class.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31075]
```dart
class class A {}
```

```
  @6: Expected a class body, but got 'class'.
  null
  #0      Listener.handleUnrecoverableError (package:front_end/src/fasta/parser/listener.dart:1156:5)
  #1      Parser.reportUnrecoverableErrorWithToken (package:front_end/src/fasta/parser/parser.dart:4761:23)
  #2      Parser.skipClassBody (package:front_end/src/fasta/parser/parser.dart:2760:14)
  #3      TopLevelParser.parseClassBody (package:front_end/src/fasta/parser/top_level_parser.dart:18:40)
  #4      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1090:13)
  #5      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1062:14)
  #6      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:372:14)
  #7      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:306:14)
  #8      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:280:15)
  #9      computeUnlinkedUnit (package:front_end/src/incremental/unlinked_unit.dart:25:32)
  #10     FileState.refresh (package:front_end/src/incremental/file_state.dart:170:23)
  <asynchronous suspension>
  #11     FileSystemState.getFile (package:front_end/src/incremental/file_state.dart:383:18)
  <asynchronous suspension>
  #12     KernelDriver.getKernel.<anonymous closure>.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:142:31)
```

@bwilkerson

**Comment by peter-ahe-google** [comment]
This is a problem with DirectiveListener. We plan to replace it with deeper integration with Fasta's outline builder.

**Comment by bwilkerson** [comment]
@scheglov The parser has been changed. It now interprets the input above as two class declarations, with the first declaration being incomplete. I suspect that this issue has been fixed. Can you confirm?

**Comment by scheglov** [comment]
Thanks!
