### ISSUE TITLE
VM: "Invalid const object field"?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31106]
```
$ dart --version

Dart VM version: 2.0.0-dev.3.0 (Wed Oct  4 03:03:29 2017) on "macos_x64"
```

The following bit of code is detected as OK in the `analyzer`, and works in `dart2js`:

```dart
class UserSchema extends Schema<User> {
  static Map<String, Object> _decode$(User user) {
    return {
      'first': user.first,
      'last': user.last,
      'born': user.born,
    };
  }

  static User _encode$(Map<String, Object> json) {
    return new User(
      first: json['first'] as String,
      last: json['last'] as String,
      born: json['born'] as int,
    );
  }

  const UserSchema() : super(
      name: 'users', 
      encode: _encode$, 
      decode: _decode$);
}
```

... see the full code here:

https://dartpad.dartlang.org/2c0f961c67a8c032c1060f651079ba06

However, it crashes at runtime in the VM as of `2.0.0-dev.3.0`.

(I haven't tried it on bleeding edge or any other version of the VM)

```
$ dart test/schema_test.dart

Unhandled exception:
'file:///.../test/schema_test.dart': error: line 11 pos 36: Invalid const object field: Closure: (User) => Map<String, Object> from Function '_decode$@16215532': static.

  final schema = const UserSchema();
                                   ^

#0      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by a-siva** [comment]
Canonicalization seems to be failing?

**Comment by crelier** [comment]
This is a bug similar to issue #27164 fixed earlier by mhausner.
Arguments to the super const initializer need the const treatment and canonicalization.
CL is under review.
