### ISSUE TITLE
Incorrect optimization of integer arithmetic

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#31114]
Reproduction
```
$ out/ReleaseIA32/dart --background-compilation=false --optimization-counter-threshold=20 tests/standalone_2/pow_test.dart 
Unhandled exception:
Expect.equals(expected: <1073741824>, actual: <-1073741824>) fails.
#0      Expect._fail (package:expect/expect.dart:496:5)
#1      Expect.equals (package:expect/expect.dart:124:5)
#2      main (file:///usr/local/google/home/kustermann/repositories/sdk-gclient/sdk/tests/standalone_2/pow_test.dart:86:12)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

**Comment by mkustermann** [comment]
The root cause of this issue is that 3cc0cea37e56bc5c590905f2da4bc5d9db9d73e6 introduces re-using of type propagation information on use sites, which turns out to be unsafe in certain situations (e.g. due to widen-to-int32 optimizations).

[workaround](https://dart-review.googlesource.com/c/sdk/+/14060) is on it's way.
