### ISSUE TITLE
dart2js kernel fails on language_2/checked_setter{,2,3}_test

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#31128]
https://uberchromegw.corp.google.com/i/client.dart/builders/dart2js-linux-d8-minified-1-5-be/builds/8051/steps/dart2js-with-kernel-d8%20tests/logs/stdio
https://uberchromegw.corp.google.com/i/client.dart/builders/dart2js-linux-d8-minified-2-5-be/builds/8125/steps/dart2js-with-kernel-d8%20tests/logs/stdio
https://uberchromegw.corp.google.com/i/client.dart/builders/dart2js-linux-d8-minified-4-5-be/builds/8408/steps/dart2js-with-kernel-d8%20tests/logs/stdio

E.g.
```
FAILED: dart2js-d8 release_x64 language_2/checked_setter3_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[dart2js]:

stdout:
Compiled 7,764,756 characters Dart to 34,361 characters JavaScript in 0.66 seconds
Dart file (/b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/tests/language_2/checked_setter3_test.dart) compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_language_2_checked_setter3_test/out.js

CommandOutput[d8]:

stdout:
out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:255: Expect.throws(TypeError) fails: Did not throw
          throw e;
          ^
Expect.throws(TypeError) fails: Did not throw
    at Object.c (/b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_language_2_checked_setter3_test/out.js:333:3)
    at Object.M (/b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_language_2_checked_setter3_test/out.js:872:23)
    at Object.aY (/b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_language_2_checked_setter3_test/out.js:869:10)
    at Object.N (/b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_language_2_checked_setter3_test/out.js:871:3)
    at aA (/b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_language_2_checked_setter3_test/out.js:881:3)
    at action (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:267:31)
    at eventLoop (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:250:9)
    at self.dartMainRunner (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:268:5)
    at /b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_language_2_checked_setter3_test/out.js:1028:39
    at init.currentScript (/b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_language_2_checked_setter3_test/out.js:1024:55)



Command[dart2js]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --minify --use-kernel --packages=/b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/.packages /b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/tests/language_2/checked_setter3_test.dart --out=/b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_language_2_checked_setter3_test/out.js
Took 0:00:00.657721

Command[d8]: DART_CONFIGURATION=ReleaseX64 /b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/third_party/d8/linux/d8 out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js /b/build/slave/dart2js-linux-d8-minified-1-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_language_2_checked_setter3_test/out.js
Took 0:00:00.048402

Short reproduction command (experimental):
    python tools/test.py -m release -c dart2js -r d8 --minified --dart2js-with-kernel --use-sdk --dart2js-batch --reset-browser-configuration language_2/checked_setter3_test
```

As result of https://github.com/dart-lang/sdk/commit/cac79d8db9f55134e39775d636afa80c7faa9c54

Will update status files for now.

**Comment by sigmundch** [comment]
thanks! Closing this bug because this is covered by our migration effort. We are using the .status files to track our progress.
