### ISSUE TITLE
findSystemLocale crashes Chrome and Dartium on Mac

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#31122]
On Dartium:
```
VM381:1 Uncaught Unhandled exception:
'dart:io-patch/platform_patch.dart': error: line 12: native function 'Platform_OperatingSystem' (0 arguments) cannot be found
  static String _operatingSystem() native "Platform_OperatingSystem";
  ^

#0      _Platform.operatingSystem (platform_impl.dart:60)
#1      Platform._operatingSystem (platform.dart:71)
#2      Platform._operatingSystem (platform.dart:71)
#3      Platform.operatingSystem (platform.dart:95)
#4      findSystemLocale (package:intl/intl_standalone.dart:38:16)
#5      main (http://localhost:8080/main.dart:49:33)
<asynchronous suspension>
```

Chrome:
```
js_helper.dart:1772 Uncaught Error: Unsupported operation: Platform._operatingSystem
    at Object.wrapException (http://localhost:8080/main.dart.js:4810:17)
    at Object._Platform__operatingSystem (http://localhost:8080/main.dart.js:23498:15)
    at Object._Platform_operatingSystem (http://localhost:8080/main.dart.js:23504:16)
    at http://localhost:8080/main.dart.js:39403:14
    at Isolate.prototype.(anonymous function) (http://localhost:8080/main.dart.js:39658:42)
    at Object.findSystemLocale (http://localhost:8080/main.dart.js:26570:9)
    at http://localhost:8080/main.dart.js:38049:38
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:9871:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:10208:14)
    at _awaitOnObject_closure.dart._awaitOnObject_closure.call$1 (http://localhost:8080/main.dart.js:10196:34)
wrapException @ js_helper.dart:1772
call$0 @ async_patch.dart:577
_microtaskLoop @ schedule_microtask.dart:41
dart._startMicrotaskLoop @ schedule_microtask.dart:50
dart._AsyncRun__initializeScheduleImmediate_internalCallback.call$1 @ async_patch.dart:51
call$0 @ js_helper.dart:2456
eval$1 @ isolate_helper.dart:474
_callInIsolate @ isolate_helper.dart:59
dart.invokeClosure @ js_helper.dart:2456
(anonymous) @ js_helper.dart:2476
childList (async)
call$1 @ async_patch.dart:67
_scheduleAsyncCallback @ async_patch.dart:28
dart._rootScheduleMicrotask @ zone.dart:1176
_addListener$1 @ zone.dart:1391
_thenNoZoneRegistration$2 @ future_impl.dart:251
_awaitOnObject @ async_patch.dart:206
_asyncStart @ async_patch.dart:142
dart.main @ main.dart:55
eval$1 @ isolate_helper.dart:474
startRootIsolate @ isolate_helper.dart:129
(anonymous) @ main.dart.js:39749
(anonymous) @ main.dart.js:39750
init.currentScript @ main.dart.js:39730
(anonymous) @ main.dart.js:39741
(anonymous) @ main.dart.js:39753
``` 

OS ---------------------------------------------------------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1611
Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

Software installed -----------------------------------------------------------
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

Dart VM version: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"
Pub 1.24.2

Chromium: 50.0.2661.108
Chrome: 61.0.3163.100

**Comment by MikeMitterer** [comment]
F... I included `package:intl/intl_standalone.dart` instead of `package:intl/intl_browser.dart`
