### ISSUE TITLE
NoSuchMethodError: The getter 'length' was called on null.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31125]
Crash in fasta
sha: 00035dd344e17c16a968b545c3c5513a0adf184e
```
import 'package';
```

```
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:122:64)
<asynchronous suspension>
#2      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:161:26)
<asynchronous suspension>
#3      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:145:13)
<asynchronous suspension>
#4      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:242:20)
<asynchronous suspension>
#5      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:96:28)
<asynchronous suspension>
#6      BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:50:13)
<asynchronous suspension>
#7      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#8      _rootRun (dart:async/zone.dart:1124)
#9      _CustomZone.run (dart:async/zone.dart:1021)
#10     runZoned (dart:async/zone.dart:1499)
#11     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#12     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#13     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:48:28)
#14     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:57:27)
<asynchronous suspension>
#15     testPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:35:9)
<asynchronous suspension>
#16     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:108:3)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by peter-ahe-google** [comment]
@askeksa-google I may have something that fixes this in a local branch. It seems familiar.

**Comment by lukechurch** [comment]
@peter-ahe-google @askeksa-google That would be great - This makes up 71% of the failures that we currently see.

**Comment by peter-ahe-google** [comment]
This is simply a bug in the file system in the prototype I gave Luke.
