### ISSUE TITLE
NoSuchMethodError: The method 'inferFieldTopLevel' was called on null.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31124]
Crash in fasta
sha: 0001676c4ad16f4ce9c6491bb99cbb80ee2a9665
```
var a = () => 'b';a();
```

```
NoSuchMethodError: The method 'inferFieldTopLevel' was called on null.
Receiver: null
Tried calling: inferFieldTopLevel(Instance of 'ShadowField', null, true)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FieldInitializerInferenceNode.resolveInternal (package:front_end/src/fasta/type_inference/type_inference_engine.dart:44:24)
#2      InferenceNode.resolve (package:front_end/src/fasta/type_inference/type_inference_engine.dart:157:7)
#3      TypeInferenceEngineImpl.finishTopLevelFields (package:front_end/src/fasta/type_inference/type_inference_engine.dart:347:12)
#4      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:520:25)
#5      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:264:14)
<asynchronous suspension>
#6      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:96:28)
<asynchronous suspension>
#7      BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:50:13)
<asynchronous suspension>
#8      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#9      _rootRun (dart:async/zone.dart:1124)
#10     _CustomZone.run (dart:async/zone.dart:1021)
#11     runZoned (dart:async/zone.dart:1499)
#12     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#13     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#14     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:48:28)
#15     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:57:27)
<asynchronous suspension>
#16     testPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:35:9)
<asynchronous suspension>
#17     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:108:3)
#18     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by stereotype441** [comment]
Should be addressed by https://dart-review.googlesource.com/c/sdk/+/14504
