### ISSUE TITLE
Unhandled AmbiguousBuilder in handleType

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31156]
Crash in fasta
@peter-ahe-google
id: 00b59266fa9e0a0fcb94b4fba3b4a06c528c502f

```
org-dartlang-bulkcompile:///main.dart:2:61: Internal problem: Unhandled AmbiguousBuilder in handleType.
REDACTED
                                                            ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:41:10)
#2      BodyBuilder.handleType (package:front_end/src/fasta/kernel/body_builder.dart:1737:7)
#3      Parser.parseType.commitType (package:front_end/src/fasta/parser/parser.dart:1735:18)
#4      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1802:26)
#5      Parser.parseIsOperatorRest (package:front_end/src/fasta/parser/parser.dart:4225:13)
#6      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3641:19)
#7      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3567:11)
#8      Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4208:15)
#9      Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4182:14)
#10     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4163:13)
#11     Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1959:18)
#12     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4008:14)
#13     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3763:14)
#14     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3733:14)
#15     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3596:13)
#16     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3567:11)
#17     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3485:13)
#18     Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1924:16)
#19     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:3447:12)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3346:14)
#21     Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3338:20)
#22     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:4439:15)
#23     Parser.parseTryStatement (package:front_end/src/fasta/parser/parser.dart:4564:15)
#24     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3374:14)
#25     Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3338:20)
#26     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3262:15)
#27     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:621:14)
#28     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:493:5)
#29     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:231:5)
#30     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2348:14)
#31     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2256:11)
#32     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:335:14)
#33     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:282:15)
#34     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:176:14)
<asynchronous suspension>
#35     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#36     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:290:20)
<asynchronous suspension>
#37     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#38     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:51:37)
<asynchronous suspension>
#39     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#40     _rootRun (dart:async/zone.dart:1124)
#41     _CustomZone.run (dart:async/zone.dart:1021)
#42     runZoned (dart:async/zone.dart:1499)
#43     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#44     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#45     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:48:28)
#46     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:60:27)
<asynchronous suspension>
#47     testPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:39:9)
<asynchronous suspension>
#48     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:112:3)
#49     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by peter-ahe-google** [comment]
I'm adding 'needs info' so as I later plan to do a pass through these issues and produce reproductions.

**Comment by peter-ahe-google** [comment]
```
==> lib_a.dart <==
class A {}

a() {}

==> lib_b.dart <==
class A {}

a() {}

==> t.dart <==
part "lib_a.dart";
part "lib_b.dart";

main() {
  A varA;
}
```

**Comment by peter-ahe-google** [comment]
The following code produces a related (yet different) crash:

```
==> lib_a.dart <==
class A {}

a() {}

==> lib_b.dart <==
class A {}

a() {}

==> t.dart <==
import "lib_a.dart";
import "lib_b.dart";

main() {
  A<dynamic> varA;
}
```

**Comment by askeksa-google** [comment]
We are postponing this until the ongoing refactoring of builders and generators have stabilized.

**Comment by askeksa-google** [comment]
The second example works now, but the first one still crashes.

**Comment by askeksa-google** [comment]
None of the examples crash now.
