### ISSUE TITLE
Disagreement between parseExpression and skipExpression

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31155]
Crash in fasta
@peter-ahe-google
id: 002b82c6e906bdd246d4af2588a7413c9dc7e679

```
Internal problem: Couldn't find 'X' in 'Y'.
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      ClassBuilder.[] (package:front_end/src/fasta/builder/class_builder.dart:205:9)
#2      BodyBuilder.finishFields (package:front_end/src/fasta/kernel/body_builder.dart:436:29)
#3      DietListener.listenerFinishFields (package:front_end/src/fasta/source/diet_listener.dart:600:14)
#4      DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:645:5)
#5      DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:507:5)
#6      DietListener.endFields (package:front_end/src/fasta/source/diet_listener.dart:216:5)
#7      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2297:16)
#8      Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2895:11)
#9      Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2783:15)
#10     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1162:13)
#11     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1133:14)
#12     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:374:14)
#13     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:308:14)
#14     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:282:15)
#15     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:176:14)
<asynchronous suspension>
#16     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#17     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:290:20)
<asynchronous suspension>
#18     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#19     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:51:37)
<asynchronous suspension>
#20     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#21     _rootRun (dart:async/zone.dart:1124)
#22     _CustomZone.run (dart:async/zone.dart:1021)
#23     runZoned (dart:async/zone.dart:1499)
#24     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#25     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#26     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:48:28)
#27     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:60:27)
<asynchronous suspension>
#28     testPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:39:9)
<asynchronous suspension>
#29     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:112:3)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by peter-ahe-google** [comment]
I'm adding 'needs info' so as I later plan to do a pass through these issues and produce reproductions.

**Comment by peter-ahe-google** [comment]
Repro:

```
class A {}

class B {}

class C {
  var f = Map<A, B> {
  }
}

void main() {

}
```

**Comment by peter-ahe-google** [comment]
This looks like a problem with error recovery not matching the behavior of diet_parser.

**Comment by danrubel** [comment]
The problem appears to be that `parseExpression` and `skipExpression` disagree on how `var f = Map<A, B> {};` should be handled. `parseExpression` treats `Map<A` as an expression while `skipExpression` skips over `Map` and `<A, B>`. I spent a while trying to get the two to agree on how to handle that expression, but no luck.

https://dart-review.googlesource.com/c/sdk/+/16335

**Comment by danrubel** [comment]
@peter-ahe-google Would you take a look and see if you have a solution that I can implement?

**Comment by peter-ahe-google** [comment]
Will do.

**Comment by danrubel** [comment]
It appears that the DietListener uses `skipExpression` to skip field initializers but is calling `parseFields` and indirectly `parseExpression` which is causing the problem. I recommend refactoring  the DietListener to call `parseFieldInitializerOpt` for each field initializer rather than calling `parseFields` to parse the fields. Doing so should alleviate the problem.

**Comment by askeksa-google** [comment]
@danrubel I am not sure I understand what you are suggesting. Isn't calling `parseFieldInitializerOpt` for each field initializer exactly what `parseFields` does in the first place? What would you do differently?

Would you do this with the current `skipExpression` implementation? As I see it, the problem is that when `skipExpression` sees a `<` token, it always skips ahead to the matching `>` token, while `parseExpression` only does this in some cases, depending on the tokens that follow the `>`. It would seem that calling `skipExpression` in a different context would not change that.

**Comment by askeksa-google** [comment]
Never mind. I will pursue a different solution.
