### ISSUE TITLE
Class 'ParenthesizedExpression' has no instance method 'withReceiver'.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31157]
Crash in fasta
@peter-ahe-google
id: 385ea5f330c491ea75062823bccb011ef9b117a8

```
NoSuchMethodError: Class 'ParenthesizedExpression' has no instance method 'withReceiver'.
Receiver: Instance of 'ParenthesizedExpression'
Tried calling: withReceiver(Instance of 'StaticAccessor', 117, isNullAware: true)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      BodyBuilder.doIfNotNull (package:front_end/src/fasta/kernel/body_builder.dart:914:15)
#2      BodyBuilder.endBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:853:39)
#3      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3622:22)
#4      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3567:11)
#5      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3485:13)
#6      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1924:16)
#7      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:3447:12)
#8      Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3346:14)
#9      Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3338:20)
#10     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3262:15)
#11     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:621:14)
#12     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:493:5)
#13     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:231:5)
#14     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2348:14)
#15     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2256:11)
#16     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:335:14)
#17     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:282:15)
#18     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:176:14)
<asynchronous suspension>
#19     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#20     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:290:20)
<asynchronous suspension>
#21     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#22     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:51:37)
<asynchronous suspension>
#23     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#24     _rootRun (dart:async/zone.dart:1124)
#25     _CustomZone.run (dart:async/zone.dart:1021)
#26     runZoned (dart:async/zone.dart:1499)
#27     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#28     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#29     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:48:28)
#30     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:60:27)
<asynchronous suspension>
#31     testPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:39:9)
<asynchronous suspension>
#32     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:112:3)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by peter-ahe-google** [comment]
I'm adding 'needs info' so as I later plan to do a pass through these issues and produce reproductions.

**Comment by askeksa-google** [comment]
Probably closely related to https://github.com/dart-lang/sdk/issues/31187

**Comment by askeksa-google** [comment]
Parenthesized expression after dot:
```dart
main() {
  return null?.(0);
}
```
