### ISSUE TITLE
samples/sample_extension/test/sample_extension_script_snapshot_test test regression

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31164]
6451ce078f5ce903bed00c978762a54030eef721 caused regression in 
```
╰─➤  python tools/test.py -m release -a simdbc64 --hot-reload samples/sample_extension/test/sample_extension_script_snapshot_test
Test configuration: none_vm_release_simdbc64

FAILED: none-vm release_simdbc64 samples/sample_extension/test/sample_extension_script_snapshot_test
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stdout:
+ out/ReleaseSIMDBC64/dart --snapshot=/tmp/sample_extension_ZSPEDY/test_sample_synchronous_extension.dart.snapshot --snapshot-kind=script /tmp/sample_extension_ZSPEDY/test_sample_synchronous_extension.dart
+ out/ReleaseSIMDBC64/dart /tmp/sample_extension_ZSPEDY/test_sample_synchronous_extension.dart.snapshot


stderr:
Dumping native stack trace for thread 1f0fd
  [0x0000000000800bd7] Unknown symbol
  [0x0000000000800bd7] Unknown symbol
-- End of DumpStackTrace


Command[vm]: DART_CONFIGURATION=ReleaseSIMDBC64 out/ReleaseSIMDBC64/dart --hot-reload-test-mode --ignore-unrecognized-flags --packages=$HOME/p/d/dart-sdk/sdk/.packages $HOME/p/d/dart-sdk/sdk/samples/sample_extension/test/sample_extension_script_snapshot_test.dart
Took 0:00:02.980627

Short reproduction command (experimental):
    python tools/test.py -m release -a simdbc64 --hot-reload samples/sample_extension/test/sample_extension_script_snapshot_test

[00:03 | 100% | +    0 | -    1]
=== Failure summary:


FAILED: none-vm release_simdbc64 samples/sample_extension/test/sample_extension_script_snapshot_test
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stdout:
+ out/ReleaseSIMDBC64/dart --snapshot=/tmp/sample_extension_ZSPEDY/test_sample_synchronous_extension.dart.snapshot --snapshot-kind=script /tmp/sample_extension_ZSPEDY/test_sample_synchronous_extension.dart
+ out/ReleaseSIMDBC64/dart /tmp/sample_extension_ZSPEDY/test_sample_synchronous_extension.dart.snapshot


stderr:
Dumping native stack trace for thread 1f0fd
  [0x0000000000800bd7] Unknown symbol
  [0x0000000000800bd7] Unknown symbol
-- End of DumpStackTrace


Command[vm]: DART_CONFIGURATION=ReleaseSIMDBC64 out/ReleaseSIMDBC64/dart --hot-reload-test-mode --ignore-unrecognized-flags --packages=$HOME/p/d/dart-sdk/sdk/.packages $HOME/p/d/dart-sdk/sdk/samples/sample_extension/test/sample_extension_script_snapshot_test.dart
Took 0:00:02.980627

Short reproduction command (experimental):
    python tools/test.py -m release -a simdbc64 --hot-reload samples/sample_extension/test/sample_extension_script_snapshot_test



===
=== 1 test failed
===

[00:03 | 100% | +    0 | -    1]
```

**Comment by sjindel-google** [comment]
Is this issue still relevant? The status files for this test don't allow this error, and it hasn't shown up for over 1 year.

**Comment by aam** [comment]
Not sure about original cause reported, but the test is still failing. So I would imagine it is still relevant, https://github.com/dart-lang/sdk/blob/master/samples/samples.status#L31 has the test marked as failed.

```
-- Command "vm" (took 02.000200s):
DART_CONFIGURATION=ReleaseSIMDBC64 out/ReleaseSIMDBC64/dart --hot-reload-test-mode --ignore-unrecognized-flags --packages=/usr/local/google/home/aam/p/d/dart-sdk/sdk/.packages /usr/local/google/home/aam/p/d/dart-sdk/sdk/out/ReleaseSIMDBC64/generated_compilations/dartk/samples_sample_extension_test_sample_extension_test/out.dill

exit code:
255

stdout:
+ out/ReleaseSIMDBC64/dart --hot-reload-test-mode --ignore-unrecognized-flags --packages=$DH/sdk/.packages /tmp/sample_extension_XPVDTL/test_sample_synchronous_extension.dart
Failing process stdout: 
Failing process stderr: ../../runtime/vm/runtime_entry.cc: 1899: error: *** Isolate reload failed:
{"type":"ReloadReport","success":false,"notices":[{"type":"ReasonForCancelling","message":"NoSuchMethodError: The getter 'uri' was called on null.\nReceiver: null\nTried calling: uri\n#0      Object.noSuchMethod (dart:core\/runtime\/libobject_patch.dart:50:5)\n#1      BuilderGraph.neighborsOf (package:front_end\/src\/fasta\/builder_graph.dart:35:35)\n#2      _SyncIterator.moveNext (dart:core\/runtime\/libcore_patch.dart:152:12)\n#3      IncrementalCompiler.computeReusedLibraries (package:front_end\/src\/fasta\/incremental_compiler.dart:760:34)\n#4      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end\/src\/fasta\/incremental_compiler.dart:209:46)\n<asynchronous suspension>\n#5      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end\/src\/fasta\/compiler_context.dart:122:46)\n#6      new Future.sync (dart:async\/future.dart:224:31)\n#7      CompilerContext.runInContext.<anonymous closure> (package:front_end\/src\/fasta\/compiler_context.dart:122:19)\n#8      _rootRun (dart:async\/zone.dart:1124:13)\n#9      _CustomZone.run (dart:async\/zone.dart:1021:19)\n#10     _runZoned (dart:async\/zone.dart:1516:10)\n#11     runZoned (dart:async\/zone.dart:1463:12)\n#12     CompilerContext.runInContext (package:front_end\/src\/fasta\/compiler_context.dart:121:12)\n#13     IncrementalCompiler.computeDelta (package:front_end\/src\/fasta\/incremental_compiler.dart:116:20)\n<asynchronous suspension>\n#14     IncrementalCompiler.compile (package:vm\/incremental_compiler.dart:50:44)\n<asynchronous suspension>\n#15     IncrementalCompilerWrapper.compileInternal (file:\/\/\/usr\/local\/google\/home\/aam\/p\/d\/dart-sdk\/sdk\/pkg\/vm\/bin\/kernel_service.dart:215:28)\n<asynchronous suspension>\n#16     Compiler.compile.<anonymous closure> (file:\/\/\/usr\/local\/google\/home\/aam\/p\/d\/dart-sdk\/sdk\/pkg\/vm\/bin\/kernel_service.dart:143:31)\n<asynchronous suspension>\n#17     new Future.<anonymous closure> (dart:async\/future.dart:176:37)\n#18     _rootRun (dart:async\/zone.dart:1120:38)\n#19     _CustomZone.run (dart:async\/zone.dart:1021:19)\n#20     _CustomZone.runGuarded (dart:async\/zone.dart:923:7)\n#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async\/zone.dart:963:23)\n#22     _rootRun (dart:async\/zone.dart:1124:13)\n#23     _CustomZone.run (dart:async\/zone.dart:1021:19)\n#24     _CustomZone.bindCallback.<anonymous closure> (dart:async\/zone.dart:947:23)\n#25     Timer._createTimer.<anonymous closure> (dart:async\/runtime\/libtimer_patch.dart:21:15)\n#26     _Timer._runTimers (dart:isolate\/runtime\/libtimer_impl.dart:382:19)\n#27     _Timer._handleMessage (dart:isolate\/runtime\/libtimer_impl.dart:416:5)\n#28     _RawReceivePortImpl._handleMessage (dart:isolate\/runtime\/libisolate_patch.dart:171:12)\n"}]}

thread=162023, isolate=test_sample_synchronous_extension.dart:main()(0x558e4a3e3200)
  [0x0000558e493bf1cc] dart::Profiler::DumpStackTrace(void*)
  [0x0000558e493bf1cc] dart::Profiler::DumpStackTrace(void*)
-- End of DumpStackTrace

End failing process stderr
```

**Comment by sjindel-google** [comment]
I see. This is the same error I'm working on right now in a related revision.

**Comment by sjindel-google** [comment]
This test doesn't exist anymore.
