### ISSUE TITLE
NoSuchMethodError: Class 'KernelFieldBuilder' has no instance method 'computeFormalParameterInitializerScope'.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31179]
Crash in fasta
@peter-ahe-google
id: 0511bc2345e4ef47e2574f058dade05140cdb37a

```
NoSuchMethodError: Class 'KernelFieldBuilder' has no instance method 'computeFormalParameterInitializerScope'.
Receiver: Instance of 'KernelFieldBuilder'
Tried calling: computeFormalParameterInitializerScope(Instance of 'Scope')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      BodyBuilder.prepareInitializers (package:front_end/src/fasta/kernel/body_builder.dart:496:20)
#2      BodyBuilder.handleNoInitializers (package:front_end/src/fasta/kernel/body_builder.dart:528:7)
#3      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2653:16)
#4      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3073:13)
#5      Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2981:11)
#6      DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:658:22)
#7      DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:522:5)
#8      DietListener.endFields (package:front_end/src/fasta/source/diet_listener.dart:218:5)
#9      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2358:16)
#10     Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2980:11)
#11     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2866:15)
#12     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1223:13)
#13     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1183:14)
#14     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:361:14)
#15     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:295:14)
#16     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#17     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#18     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#19     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#20     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#21     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#22     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#23     _rootRun (dart:async/zone.dart:1124)
#24     _CustomZone.run (dart:async/zone.dart:1021)
#25     runZoned (dart:async/zone.dart:1499)
#26     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#27     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#28     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#29     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#30     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#31     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Seems to have been fixed by https://github.com/dart-lang/sdk/commit/a2c5217e8d0471d32482e02177c080387ce258be @danrubel
