### ISSUE TITLE
unsupported operation 'name'

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31170]
Crash in fasta
@peter-ahe-google
id: 016f4068b55dfb7648f350fcd53e2294c9fc9287

```
org-dartlang-bulkcompile:///main.dart:60:33: Internal problem: Unsupported operation: 'name'.
  REDACTED
                                ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unsupported (package:front_end/src/fasta/problems.dart:55:10)
#2      IncompleteSend&ErrorAccessor.name (package:front_end/src/fasta/kernel/fasta_accessors.dart:231:20)
#3      IncompleteSend&ErrorAccessor.plainNameForRead (package:front_end/src/fasta/kernel/fasta_accessors.dart:234:34)
#4      getNodeName (package:front_end/src/fasta/kernel/body_builder.dart:3939:17)
#5      BodyBuilder.endNewExpression.<anonymous closure> (package:front_end/src/fasta/kernel/body_builder.dart:2424:31)
#6      BodyBuilder.endNewExpression (package:front_end/src/fasta/kernel/body_builder.dart:2432:6)
#7      BodyBuilder.endConstExpression (package:front_end/src/fasta/kernel/body_builder.dart:2439:5)
#8      Parser.parseConstExpression (package:front_end/src/fasta/parser/parser.dart:4180:14)
#9      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3860:16)
#10     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3808:14)
#11     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3670:13)
#12     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3642:11)
#13     KernelFieldBuilder.prepareTopLevelInference (package:front_end/src/fasta/kernel/kernel_field_builder.dart:114:30)
#14     SourceClassBuilder.prepareTopLevelInference.<anonymous closure> (package:front_end/src/fasta/source/source_class_builder.dart:177:15)
#15     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:360)
#16     Scope.forEach (package:front_end/src/fasta/scope.dart:243:11)
#17     SourceClassBuilder.prepareTopLevelInference (package:front_end/src/fasta/source/source_class_builder.dart:176:11)
#18     SourceLoader.prepareTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:513:15)
#19     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:263:14)
<asynchronous suspension>
#20     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:96:28)
<asynchronous suspension>
#21     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#22     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#23     _rootRun (dart:async/zone.dart:1124)
#24     _CustomZone.run (dart:async/zone.dart:1021)
#25     runZoned (dart:async/zone.dart:1499)
#26     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#27     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#28     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#29     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#30     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#31     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by peter-ahe-google** [comment]
I'm adding 'needs info' so as I later plan to do a pass through these issues and produce reproductions.

**Comment by peter-ahe-google** [comment]
Repro:

```
class A {
  B();

  static const field = const B();
}

main() {}
```
