### ISSUE TITLE
NoSuchMethodError: The getter 'uri' was called on null.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31172]
Crash in fasta
@peter-ahe-google
id: 04ba4eacf2f8f07d0eecfc4339565cd76145edbd

```
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      UriTranslatorImpl._translateDartUri (package:front_end/src/fasta/uri_translator_impl.dart:57:68)
#2      UriTranslatorImpl.translate (package:front_end/src/fasta/uri_translator_impl.dart:41:38)
#3      TargetImplementation.translateUri (package:front_end/src/fasta/target_implementation.dart:53:46)
#4      Loader.read.<anonymous closure> (package:front_end/src/fasta/loader.dart:78:30)
#5      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:274)
#6      Loader.read (package:front_end/src/fasta/loader.dart:73:39)
#7      SourceLibraryBuilder.addImport (package:front_end/src/fasta/source/source_library_builder.dart:183:16)
#8      OutlineBuilder.endImport (package:front_end/src/fasta/source/outline_builder.dart:188:17)
#9      Parser.parseImport (package:front_end/src/fasta/parser/parser.dart:453:16)
#10     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:387:16)
#11     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:295:14)
#12     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#13     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:166:37)
<asynchronous suspension>
#14     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:145:13)
<asynchronous suspension>
#15     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:242:20)
<asynchronous suspension>
#16     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:96:28)
<asynchronous suspension>
#17     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#19     _rootRun (dart:async/zone.dart:1124)
#20     _CustomZone.run (dart:async/zone.dart:1021)
#21     runZoned (dart:async/zone.dart:1499)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#24     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#25     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#26     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#27     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by peter-ahe-google** [comment]
I'm adding 'needs info' so as I later plan to do a pass through these issues and produce reproductions.

**Comment by askeksa-google** [comment]
```dart
import 'dart:foo/foo.dart' as foo;
```

**Comment by renatoathaydes** [comment]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-183.5153.38`
- `2.1.0`
- `IC-183.5153.38, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-139-generic, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.1.0, server version 1.21.1, error: Analysis failed: /home/renato/programming/projects/dart-web/web/main.dart context: exception_20190126_164743_831
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new _LibraryResynthesizer (package:analyzer/src/summary/resynthesize.dart:633:32)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:354:56)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#4      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:322:36)
#5      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:217:14)
#6      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:106:12)
#7      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:84:14)
<asynchronous suspension>
#8      _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:270:21)
<asynchronous suspension>
#9      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:83:43)
<asynchronous suspension>
#10     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:71)
<asynchronous suspension>
#11     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
#12     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
#13     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1050:39)
<asynchronous suspension>
#14     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
#15     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#16     new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
#17     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#18     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#19     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:551:12)
#25     Driver.start (package:analysis_server/src/server/driver.dart:503:7)
#26     main (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/analysis_server/bin/server.dart:12:11)
#27     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#28     main (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/analysis_server/bin/server.dart:10:10)
#29     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#30     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///tmp/report.txt.

Dart analysis server, SDK version 2.1.0, server version 1.21.1, error: Analysis failed: /home/renato/programming/projects/dart-web/web/main.dart context: exception_20190126_164743_831
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new _LibraryResynthesizer (package:analyzer/src/summary/resynthesize.dart:633:32)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:354:56)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#4      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:322:36)
#5      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:217:14)
#6      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:106:12)
#7      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:84:14)
<asynchronous suspension>
#8      _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:270:21)
<asynchronous suspension>
#9      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:83:43)
<asynchronous suspension>
#10     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:71)
<asynchronous suspension>
#11     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
#12     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
#13     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1050:39)
<asynchronous suspension>
#14     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
#15     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#16     new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
#17     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#18     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#19     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:551:12)
#25     Driver.start (package:analysis_server/src/server/driver.dart:503:7)
#26     main (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/analysis_server/bin/server.dart:12:11)
#27     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#28     main (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/analysis_server/bin/server.dart:10:10)
#29     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#30     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
1548517399410 <= {"id":"12469","result":{}}
1548517399410 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548517399410 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548517399734 => {"id":"12470","method":"analysis.updateContent","params":{"files":{"/home/renato/programming/projects/dart-web/pubspec.yaml":{"type":"add","content":"name: pharma_soft\ndescription: P
1548517399738 <= {"id":"12470","result":{}}
1548517399738 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548517399738 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548517400630 => {"id":"12471","method":"analysis.updateContent","params":{"files":{"/home/renato/programming/projects/dart-web/pubspec.yaml":{"type":"add","content":"name: pharma_soft\ndescription: P
1548517400634 <= {"id":"12471","result":{}}
1548517400634 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548517400636 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548517401042 => {"id":"12472","method":"analysis.updateContent","params":{"files":{"/home/renato/programming/projects/dart-web/pubspec.yaml":{"type":"add","content":"name: pharma_soft\ndescription: P
1548517401048 <= {"id":"12472","result":{}}
1548517401048 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548517401055 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548517401573 => {"id":"12473","method":"analysis.updateContent","params":{"files":{"/home/renato/programming/projects/dart-web/pubspec.yaml":{"type":"add","content":"name: pharma_soft\ndescription: P
1548517401576 <= {"id":"12473","result":{}}
1548517401577 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548517401581 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548517417089 <= {"event":"analysis.flushResults","params":{"files":["/home/renato/programming/projects/dart-web/pubspec.yaml___jb_tmp___"]}}
1548517417090 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548517417097 <= {"event":"analysis.errors","params":{"file":"/home/renato/programming/projects/dart-web/pubspec.yaml","errors":[]}}
1548517417107 <= {"event":"analysis.flushResults","params":{"files":["/home/renato/programming/projects/dart-web/pubspec.yaml___jb_old___"]}}
1548517417117 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548517417814 => {"id":"12474","method":"analysis.updateContent","params":{"files":{"/home/renato/programming/projects/dart-web/pubspec.yaml":{"type":"remove"}}},"clientRequestTime":1548517417814}
1548517417817 <= {"id":"12474","result":{}}
1548517417817 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548517417817 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548517663802 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548517663843 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /home/renato/programming/projects/dart-web/web/main.dart context: exception_20190126_164743_831","stackTr
```

**Comment by peter-ahe-google** [comment]
@renatoathaydes this is a separate problem, would you mind filing a new issue?

**Comment by renatoathaydes** [comment]
@peter-ahe-google sure

**Comment by peter-ahe-google** [comment]
@renatoathaydes thank you!
