### ISSUE TITLE
Crash on unterminated typedef

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31171]
Crash in fasta
@peter-ahe-google
id: 009031c9bfd0635c1181888e97ed070f4c7938cb

```
Internal problem: Couldn't find 'dynamic' in 'org-dartlang-bulkcompile:///main.dart'.
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      LibraryBuilder.[] (package:front_end/src/fasta/builder/library_builder.dart:212:9)
#2      BodyBuilder.finishFields (package:front_end/src/fasta/kernel/body_builder.dart:442:24)
#3      DietListener.listenerFinishFields (package:front_end/src/fasta/source/diet_listener.dart:615:14)
#4      DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:660:5)
#5      DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:522:5)
#6      DietListener.endTopLevelFields (package:front_end/src/fasta/source/diet_listener.dart:245:5)
#7      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2356:16)
#8      Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2316:11)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:322:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#11     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#12     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#13     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#14     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#15     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#17     _rootRun (dart:async/zone.dart:1124)
#18     _CustomZone.run (dart:async/zone.dart:1021)
#19     runZoned (dart:async/zone.dart:1499)
#20     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#21     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#22     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#23     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#24     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#25     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by peter-ahe-google** [comment]
I'm adding 'needs info' so as I later plan to do a pass through these issues and produce reproductions.

**Comment by askeksa-google** [comment]
Unterminated typedef:
```dart
typedef T = 
typedef F = Map<String, dynamic> Function();
```
