### ISSUE TITLE
NoSuchMethodError: Class 'ShadowIntLiteral' has no instance method 'withReceiver'.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31187]
Crash in fasta
@peter-ahe-google
id: 15a0000cdd6e1348c69d45b12f9dd590ecbacbc6

```
NoSuchMethodError: Class 'ShadowIntLiteral' has no instance method 'withReceiver'.
Receiver: Instance of 'ShadowIntLiteral'
Tried calling: withReceiver(Instance of 'VariableAccessor', 39, isNullAware: true)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      BodyBuilder.doIfNotNull (package:front_end/src/fasta/kernel/body_builder.dart:940:15)
#2      BodyBuilder.endBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:879:39)
#3      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3696:22)
#4      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3642:11)
#5      Parser.parseReturnStatement (package:front_end/src/fasta/parser/parser.dart:3512:13)
#6      Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3429:14)
#7      Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3417:20)
#8      Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3342:15)
#9      DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:636:14)
#10     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:508:5)
#11     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:233:5)
#12     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2429:14)
#13     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2317:11)
#14     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:322:14)
#15     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#16     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#17     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#18     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#19     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#20     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#21     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#22     _rootRun (dart:async/zone.dart:1124)
#23     _CustomZone.run (dart:async/zone.dart:1021)
#24     runZoned (dart:async/zone.dart:1499)
#25     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#26     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#27     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#28     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#29     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#30     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#31     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Integer literal as send:
```dart
main() {
  var x = null;
  return x?.1;
}
```
