### ISSUE TITLE
Internal problem: Couldn't find ''.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31189]
Crash in fasta
@peter-ahe-google
id: 1b580e392bc011704bd7fc6ab1261d037cb33e50

```
org-dartlang-bulkcompile:///main.dart:4:4: Internal problem: Couldn't find ''.
  REDACTED
   ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      DietListener.lookupBuilder (package:front_end/src/fasta/source/diet_listener.dart:698:14)
#2      DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:518:23)
#3      DietListener.endTopLevelFields (package:front_end/src/fasta/source/diet_listener.dart:245:5)
#4      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2356:16)
#5      Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2316:11)
#6      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:322:14)
#7      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#8      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#9      Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#10     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#12     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#13     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#14     _rootRun (dart:async/zone.dart:1124)
#15     _CustomZone.run (dart:async/zone.dart:1021)
#16     runZoned (dart:async/zone.dart:1499)
#17     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#18     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#19     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#20     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#21     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#22     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Small reproduction case:
```dart
main() {
  var dict = {key: }
  var 
  });
}
```

**Comment by jensjoha** [comment]
The repro code no longer crashes, can we close this issue?

**Comment by peter-ahe-google** [comment]
We shouldn't close these bugs until we have verified that the crash has been intentionally fixed and is covered by a regression test.
