### ISSUE TITLE
Crash on using ++ as binary operator

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31185]
Crash in fasta
@peter-ahe-google
id: 0edfdf9688cfe8ffb91f05d4ea386d5eeb0fef44

```
org-dartlang-bulkcompile:///main.dart:7:23: Internal problem: Unhandled DelayedPostfixIncrement in doInvocation.
    REDACTED
                      ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:41:10)
#2      ContextAccessor.doInvocation (package:front_end/src/fasta/kernel/body_builder.dart:3554:12)
#3      BodyBuilder.finishSend (package:front_end/src/fasta/kernel/body_builder.dart:812:23)
#4      BodyBuilder.handleSend (package:front_end/src/fasta/kernel/body_builder.dart:805:12)
#5      Parser.parseArgumentOrIndexStar (package:front_end/src/fasta/parser/parser.dart:3826:18)
#6      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3699:21)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3684:19)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3642:11)
#9      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3561:13)
#10     Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1985:16)
#11     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:3523:12)
#12     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3425:14)
#13     Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3417:20)
#14     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:4678:15)
#15     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3427:14)
#16     Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3417:20)
#17     Parser.parseForRest (package:front_end/src/fasta/parser/parser.dart:4593:13)
#18     Parser.parseForStatement (package:front_end/src/fasta/parser/parser.dart:4541:14)
#19     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3437:14)
#20     Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3417:20)
#21     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3342:15)
#22     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:636:14)
#23     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:508:5)
#24     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:233:5)
#25     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2429:14)
#26     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2317:11)
#27     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:322:14)
#28     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#29     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#30     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#31     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#32     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#33     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#34     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#35     _rootRun (dart:async/zone.dart:1124)
#36     _CustomZone.run (dart:async/zone.dart:1021)
#37     runZoned (dart:async/zone.dart:1499)
#38     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#39     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#40     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#41     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#42     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#43     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Increment with parenthesized expressions on both sides:
```dart
main() {
  int i = 5;
  return (i) ++ (i);
}
```
