### ISSUE TITLE
Internal problem: Couldn't find 'unary-'.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31183]
Crash in fasta
@peter-ahe-google
id: 0ccd4e4b999df9d9905a7cbd496be716f4dd5989

```
org-dartlang-bulkcompile:///main.dart:14:3: Internal problem: Couldn't find 'unary-'.
  operator unary- => ;
  ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      DietListener.lookupBuilder (package:front_end/src/fasta/source/diet_listener.dart:698:14)
#2      DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:474:32)
#3      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3094:14)
#4      Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2981:11)
#5      Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2866:15)
#6      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1223:13)
#7      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1183:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:361:14)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:295:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#11     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#12     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#13     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#14     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#15     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#17     _rootRun (dart:async/zone.dart:1124)
#18     _CustomZone.run (dart:async/zone.dart:1021)
#19     runZoned (dart:async/zone.dart:1499)
#20     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#21     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#22     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#23     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#24     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#25     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Simple repro case:
```dart
class C {
  operator unary- => 0;
}
```
