### ISSUE TITLE
NoSuchMethodError: Class 'ShadowBoolLiteral' has no instance method 'withReceiver'.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31186]
Crash in fasta
@peter-ahe-google
id: 0fc8df73003098c7c7709dab81cf1c9da7a0b726

```
NoSuchMethodError: Class 'ShadowBoolLiteral' has no instance method 'withReceiver'.
Receiver: Instance of 'ShadowBoolLiteral'
Tried calling: withReceiver(Instance of 'VariableAccessor', 63, isNullAware: true)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      BodyBuilder.doIfNotNull (package:front_end/src/fasta/kernel/body_builder.dart:940:15)
#2      BodyBuilder.endBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:879:39)
#3      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3696:22)
#4      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3642:11)
#5      Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4382:15)
#6      Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4339:14)
#7      Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4320:13)
#8      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:2020:18)
#9      Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4112:14)
#10     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3838:14)
#11     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3808:14)
#12     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3670:13)
#13     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3642:11)
#14     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3561:13)
#15     Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1985:16)
#16     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:3523:12)
#17     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3425:14)
#18     Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3417:20)
#19     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3342:15)
#20     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:636:14)
#21     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:508:5)
#22     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:233:5)
#23     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2429:14)
#24     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2317:11)
#25     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:322:14)
#26     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#27     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#28     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#29     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#30     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#31     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#32     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#33     _rootRun (dart:async/zone.dart:1124)
#34     _CustomZone.run (dart:async/zone.dart:1021)
#35     runZoned (dart:async/zone.dart:1499)
#36     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#37     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#38     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#39     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#40     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#41     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Bool literal as send. Probably closely related to https://github.com/dart-lang/sdk/issues/31187
```dart
main() {
  var x = null;
  return x?.false;
}
```
