### ISSUE TITLE
Superfluous errors when writing = instead of =>

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31182]
Crash in fasta
@peter-ahe-google
id: 0af3fefbacbd2aa57008b937c17dc2ec53293dd8

```
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/dart:core/string_patch.dart:372)
#1      unescapeString (package:front_end/src/fasta/quote.dart:136:14)
#2      BodyBuilder.endLiteralString (package:front_end/src/fasta/kernel/body_builder.dart:1284:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4284:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4216:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3844:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3808:14)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3670:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3642:11)
#9      Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3319:15)
#10     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:636:14)
#11     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:508:5)
#12     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:475:5)
#13     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3094:14)
#14     Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2981:11)
#15     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2866:15)
#16     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1223:13)
#17     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1183:14)
#18     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:361:14)
#19     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:295:14)
#20     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#21     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#22     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#23     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#24     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#25     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#26     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#27     _rootRun (dart:async/zone.dart:1124)
#28     _CustomZone.run (dart:async/zone.dart:1021)
#29     runZoned (dart:async/zone.dart:1499)
#30     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#31     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#32     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#33     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#34     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#35     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Arrow method using `=` instead of `=>` with string interpolation:
```dart
class Box {
  int x;
  String toString() = "$x";
}
```

**Comment by jensjoha** [comment]
The reproduction code doesn't crash now, only produces lots of errors. Can we close?
