### ISSUE TITLE
NoSuchMethodError: The method 'accept' was called on null.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31181]
Crash in fasta
@peter-ahe-google
id: 0a680bc21ca560b7c013e26063eb203a3d9dafa6

```
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept(Instance of '_InnerTypeSubstitutor')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _TypeSubstitutor.visit (package:kernel/type_algebra.dart:389:41)
#2      _InnerTypeSubstitutor.freshTypeParameter (package:kernel/type_algebra.dart:343:19)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#4      ListIterable.toList (dart:_internal/iterable.dart:218)
#5      _TypeSubstitutor.freshTypeParameters (package:kernel/type_algebra.dart:415:47)
#6      _TypeSubstitutor.visitFunctionType (package:kernel/type_algebra.dart:436:32)
#7      FunctionType.accept (package:kernel/ast.dart:4570:34)
#8      _TypeSubstitutor.visit (package:kernel/type_algebra.dart:389:41)
#9      Substitution.substituteType (package:kernel/type_algebra.dart:239:53)
#10     substitute (package:kernel/type_algebra.dart:19:45)
#11     KernelFunctionTypeAliasBuilder.buildTypesWithBuiltArguments (package:front_end/src/fasta/kernel/kernel_function_type_alias_builder.dart:92:12)
#12     KernelFunctionTypeAliasBuilder.buildType (package:front_end/src/fasta/kernel/kernel_function_type_alias_builder.dart:109:12)
#13     KernelNamedTypeBuilder.build (package:front_end/src/fasta/kernel/kernel_named_type_builder.dart:51:20)
#14     KernelFieldBuilder.build (package:front_end/src/fasta/kernel/kernel_field_builder.dart:70:25)
#15     KernelLibraryBuilder.buildBuilder (package:front_end/src/fasta/kernel/kernel_library_builder.dart:768:33)
#16     SourceLibraryBuilder.build.<anonymous closure> (package:front_end/src/fasta/source/source_library_builder.dart:403:9)
#17     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:360)
#18     Scope.forEach (package:front_end/src/fasta/scope.dart:243:11)
#19     LibraryBuilder.forEach (package:front_end/src/fasta/builder/library_builder.dart:205:11)
#20     SourceLibraryBuilder.build (package:front_end/src/fasta/source/source_library_builder.dart:401:5)
#21     KernelLibraryBuilder.build (package:front_end/src/fasta/kernel/kernel_library_builder.dart:787:16)
#22     SourceLoader.buildProgram.<anonymous closure> (package:front_end/src/fasta/source/source_loader.dart:461:31)
#23     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:360)
#24     SourceLoader.buildProgram (package:front_end/src/fasta/source/source_loader.dart:459:14)
#25     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:250:14)
<asynchronous suspension>
#26     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:96:28)
<asynchronous suspension>
#27     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#28     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#29     _rootRun (dart:async/zone.dart:1124)
#30     _CustomZone.run (dart:async/zone.dart:1021)
#31     runZoned (dart:async/zone.dart:1499)
#32     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#33     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#34     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#35     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#36     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#37     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Type parameter from typedef put on a function type:
```dart
typedef Foo<T> = T Function<T>(T a);

Foo x;
```
