### ISSUE TITLE
NoSuchMethodError: Class 'ShadowExpressionStatement' has no instance getter 'initializer'.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31184]
Crash in fasta
@peter-ahe-google
id: 0d30b9e522506b190ddd1a7ac20569363d892c3d

```
NoSuchMethodError: Class 'ShadowExpressionStatement' has no instance getter 'initializer'.
Receiver: Instance of 'ShadowExpressionStatement'
Tried calling: initializer
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      AsyncRewriterBase.visitForStatement (package:kernel/transformations/continuation.dart:471:16)
#2      ForStatement.accept (package:kernel/ast.dart:3647:35)
#3      AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation.dart:376:17)
#4      Block.accept (package:kernel/ast.dart:3460:35)
#5      AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:396:10)
#6      AsyncRewriterBase.buildWrappedBody (package:kernel/transformations/continuation.dart:336:24)
#7      AsyncStarFunctionRewriter.buildWrappedBody (package:kernel/transformations/continuation.dart:795:44)
#8      AsyncRewriterBase.setupAsyncContinuations (package:kernel/transformations/continuation.dart:288:39)
#9      AsyncStarFunctionRewriter.rewrite (package:kernel/transformations/continuation.dart:767:5)
#10     RecursiveContinuationRewriter.visitFunctionNode (package:kernel/transformations/continuation.dart:62:60)
#11     FunctionNode.accept (package:kernel/ast.dart:1698:30)
#12     Procedure.transformChildren (package:kernel/ast.dart:1412:27)
#13     Transformer.defaultTreeNode (package:kernel/visitor.dart:350:10)
#14     TreeVisitor.defaultMember (package:kernel/visitor.dart:213:35)
#15     TreeVisitor.visitProcedure (package:kernel/visitor.dart:215:39)
#16     RecursiveContinuationRewriter.visitProcedure (package:kernel/transformations/continuation.dart:48:57)
#17     Procedure.accept (package:kernel/ast.dart:1399:32)
#18     transformList (package:kernel/ast.dart:5124:27)
#19     Library.transformChildren (package:kernel/ast.dart:406:5)
#20     Transformer.defaultTreeNode (package:kernel/visitor.dart:350:10)
#21     TreeVisitor.visitLibrary (package:kernel/visitor.dart:232:35)
#22     Library.accept (package:kernel/ast.dart:390:30)
#23     RecursiveContinuationRewriter.rewriteLibrary (package:kernel/transformations/continuation.dart:44:17)
#24     transformLibraries (package:kernel/transformations/continuation.dart:19:14)
#25     VmTarget.performModularTransformationsOnLibraries (package:kernel/target/vm.dart:66:5)
#26     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:643:19)
#27     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:293:7)
<asynchronous suspension>
#28     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#29     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#30     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#31     _rootRun (dart:async/zone.dart:1124)
#32     _CustomZone.run (dart:async/zone.dart:1021)
#33     runZoned (dart:async/zone.dart:1499)
#34     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#35     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#36     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#37     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#38     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#39     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Comma instead of semicolon in a for loop:
```dart
main() {
  for (int i = 0, i > 10; i++) {}
}
```
Interestingly, it does not crash with `<` in the condition instead of `>`. Probably some interaction with generics delimiter matching.
