### ISSUE TITLE
Assert on type argument to factory constructor

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31196]
Crash in fasta
@peter-ahe-google
id: 354fbee513b2be38bfeb3829ca56bd6fae3552c7

```
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ProcedureBuilder.getFormal (package:front_end/src/fasta/builder/procedure_builder.dart:120:43)
#2      BodyBuilder.endFormalParameter (package:front_end/src/fasta/kernel/body_builder.dart:1917:52)
#3      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:2197:18)
#4      Parser.parseModifiers (package:front_end/src/fasta/parser/parser.dart:2809:13)
#5      Parser.parseFormalParameter (package:front_end/src/fasta/parser/parser.dart:956:13)
#6      Parser.parseFormalParameters (package:front_end/src/fasta/parser/parser.dart:933:15)
#7      Parser.parseFormalParametersOpt (package:front_end/src/fasta/parser/parser.dart:864:14)
#8      DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:628:22)
#9      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:508:5)
#10     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:475:5)
#11     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3094:14)
#12     Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2981:11)
#13     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2866:15)
#14     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1223:13)
#15     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1183:14)
#16     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:361:14)
#17     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:295:14)
#18     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#19     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#20     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#21     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#22     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#23     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#24     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#25     _rootRun (dart:async/zone.dart:1124)
#26     _CustomZone.run (dart:async/zone.dart:1021)
#27     runZoned (dart:async/zone.dart:1499)
#28     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#29     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#30     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#31     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#32     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#33     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#34     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
The test program currently hits an assert:

```
'package:front_end/src/fasta/kernel/kernel_library_builder.dart': Failed assertion: line 670 pos 12: 'constructorNameReference.suffix == null': is not true.
```

Reproduction for that can be reduced to:

```dart
class Foo<T> {
  factory Foo<String>.init() => null;
}
```

If the assert is removed, the original exception occurs. However, that is not reproduced by the above, reduced program. A small program to reproduce the original exception (with or without the assert) is:

```dart
class Foo {
  Bar(int something);

  factory Bar() => null;
}
```

**Comment by askeksa-google** [comment]
Original exception fixed by the fix for https://github.com/dart-lang/sdk/issues/31299 - though the assert failure remains. If the assert is removed, the compilation completes, but with the rather nonsensical warning:
```
Warning: Couldn't find constructor 'Foo.init'.
```
