### ISSUE TITLE
Internal problem: Unhandled ShadowSuperInitializer in toValue.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31198]
Crash in fasta
@peter-ahe-google
id: 3cb20dea3e46daaf3b0ebffaff607061bd4f3fb7

```
org-dartlang-bulkcompile:///main.dart: Internal problem: Unhandled ShadowSuperInitializer in toValue.
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:41:10)
#2      BodyBuilder.toValue (package:front_end/src/fasta/kernel/body_builder.dart:238:14)
#3      SendAccessor.withReceiver (package:front_end/src/fasta/kernel/fasta_accessors.dart:533:16)
#4      BodyBuilder.doDotOrCascadeExpression (package:front_end/src/fasta/kernel/body_builder.dart:948:17)
#5      BodyBuilder.endBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:873:14)
#6      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3696:22)
#7      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3642:11)
#8      Parser.parseInitializer (package:front_end/src/fasta/parser/parser.dart:2679:15)
#9      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2666:15)
#10     Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2651:14)
#11     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:631:22)
#12     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:508:5)
#13     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:475:5)
#14     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3094:14)
#15     Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2981:11)
#16     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2866:15)
#17     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1223:13)
#18     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1183:14)
#19     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:361:14)
#20     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:295:14)
#21     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#22     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#23     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#24     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#25     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#26     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#27     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#28     _rootRun (dart:async/zone.dart:1124)
#29     _CustomZone.run (dart:async/zone.dart:1021)
#30     runZoned (dart:async/zone.dart:1499)
#31     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#32     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#33     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#34     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#35     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#36     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#37     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Small reproduction case:

```dart
abstract class A {}

class B extends A {
  B(): super().foo() {}
}

void main() {
  new B();
}
```

Initializers are parsed as expressions, but the `super()` call is special-cased when it appears in an initializer to parse into a `SuperInitializer` instead (in `ThisAccessor.doInvocation()`). The `SuperInitializer` is not a valid receiver, which causes the exception when it appears as one.
