### ISSUE TITLE
Internal problem: Unhandled KernelTypeVariableBuilder in TypeDeclarationAccessor.buildType.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31190]
Crash in fasta
@peter-ahe-google
id: 1c410af223b210236d8a247662b92836a8a2ba32

```
org-dartlang-bulkcompile:///main.dart:4:3: Internal problem: Unhandled KernelTypeVariableBuilder in TypeDeclarationAccessor.buildType.
REDACTED
  ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:41:10)
#2      TypeDeclarationAccessor.buildType (package:front_end/src/fasta/kernel/fasta_accessors.dart:1053:16)
#3      BodyBuilder.handleType (package:front_end/src/fasta/kernel/body_builder.dart:1751:17)
#4      Parser.parseType.commitType (package:front_end/src/fasta/parser/parser.dart:1796:18)
#5      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1863:26)
#6      Parser.parseModifiers (package:front_end/src/fasta/parser/parser.dart:2809:13)
#7      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2331:19)
#8      Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2980:11)
#9      DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:658:22)
#10     DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:522:5)
#11     DietListener.endFields (package:front_end/src/fasta/source/diet_listener.dart:218:5)
#12     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2358:16)
#13     Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2980:11)
#14     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2866:15)
#15     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1223:13)
#16     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1183:14)
#17     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:361:14)
#18     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:295:14)
#19     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#20     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#21     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#22     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#23     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#24     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#25     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#26     _rootRun (dart:async/zone.dart:1124)
#27     _CustomZone.run (dart:async/zone.dart:1021)
#28     runZoned (dart:async/zone.dart:1499)
#29     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#30     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#31     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#32     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#33     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#34     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Type parameter on a type parameter:
```dart
class Typed<T> {
  T<U> v;
}
```
