### ISSUE TITLE
Unsupported operation: 'plainNameForRead'.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31192]
Crash in fasta
@peter-ahe-google
id: 1ec568cb8a5aa739bbd5fb02dc344e54de7c7abf

```
org-dartlang-bulkcompile:///main.dart:1:32: Internal problem: Unsupported operation: 'plainNameForRead'.
REDACTED
                               ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unsupported (package:front_end/src/fasta/problems.dart:55:10)
#2      ContextAccessor.plainNameForRead (package:front_end/src/fasta/kernel/body_builder.dart:3550:12)
#3      FastaAccessor.buildFieldInitializer (package:front_end/src/fasta/kernel/fasta_accessors.dart:163:24)
#4      BodyBuilder.endInitializer (package:front_end/src/fasta/kernel/body_builder.dart:565:26)
#5      Parser.parseInitializer (package:front_end/src/fasta/parser/parser.dart:2681:14)
#6      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2666:15)
#7      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2651:14)
#8      DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:631:22)
#9      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:508:5)
#10     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:475:5)
#11     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3094:14)
#12     Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2981:11)
#13     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2866:15)
#14     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1223:13)
#15     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1183:14)
#16     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:361:14)
#17     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:295:14)
#18     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#19     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#20     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#21     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#22     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#23     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#24     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#25     _rootRun (dart:async/zone.dart:1124)
#26     _CustomZone.run (dart:async/zone.dart:1021)
#27     runZoned (dart:async/zone.dart:1499)
#28     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#29     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#30     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#31     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#32     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#33     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#34     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment]
Increment in initializer:
```dart
class Increment {
  var x;
  Increment() : x++ {}
}
```

**Comment by lrhn** [comment]
Clever! Please also check:
```dart
class Increment {
  var x;
  Increment.v1(int x) : x+=1;
  Increment.v2(int x) : x++;
}
```
The `x+=1` and `x++` are invalid syntax where they occur, and should not be desugared into `x = x + 1;` before checking (because the latter would be correct syntax).

**Comment by askeksa-google** [comment]
Those work fine as well. There is no desugaring going on at this stage.
