### ISSUE TITLE
Frontend on Flutter Gallery regression - SyncIterable<LocalizationsDelegate> is not a subtype of LocalizationsDelegate

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31200]
There is new error produced on running Flutter Gallery example, which seems to be a regression introduced in Dart after 87538ffd7e (and before 80e3fed6df31aafa33a6a641479cb0e0031ae643).

Here is the error:
```
I/flutter ( 3990): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3990): The following assertion was thrown building WidgetsApp-[GlobalObjectKey
I/flutter ( 3990): _MaterialAppState#b9fce](dirty, state: _WidgetsAppState#3b2b5):
I/flutter ( 3990): type '_SyncIterable<LocalizationsDelegate>' is not a subtype of type 'LocalizationsDelegate' of
I/flutter ( 3990): '_current@0150898' where
I/flutter ( 3990):   _SyncIterable is from dart:core
I/flutter ( 3990):   LocalizationsDelegate is from package:flutter/src/widgets/localizations.dart
I/flutter ( 3990):   LocalizationsDelegate is from package:flutter/src/widgets/localizations.dart
I/flutter ( 3990): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3990): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3990): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3990):   https://github.com/flutter/flutter/issues/new
I/flutter ( 3990): When the exception was thrown, this was the stack:
I/flutter ( 3990): #0      _SyncIterator._current= (dart:core)
I/flutter ( 3990): #1      _WidgetsAppState._localizationsDelegates (package:flutter/src/widgets/app.dart)
I/flutter ( 3990): #2      _SyncIterator.moveNext (dart:core:277:12)
I/flutter ( 3990): #3      new List.from (flutter_patched_sdk/lib/core/list.dart:144:17)
I/flutter ( 3990): #4      Iterable.toList (flutter_patched_sdk/lib/core/iterable.dart:347:16)
I/flutter ( 3990): #5      _WidgetsAppState.build (package:flutter/src/widgets/app.dart:493:44)
I/flutter ( 3990): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3640:27)
I/flutter ( 3990): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3550:15)
I/flutter ( 3990): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter ( 3990): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter ( 3990): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart)
I/flutter ( 3990): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525:5)
I/flutter ( 3990): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 3990): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 3990): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562:16)
I/flutter ( 3990): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter ( 3990): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter ( 3990): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525:5)
I/flutter ( 3990): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 3990): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 3990): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562:16)
I/flutter ( 3990): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter ( 3990): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter ( 3990): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525:5)
I/flutter ( 3990): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 3990): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 3990): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562:16)
I/flutter ( 3990): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter ( 3990): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter ( 3990): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525:5)
I/flutter ( 3990): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 3990): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 3990): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562:16)
I/flutter ( 3990): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter ( 3990): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter ( 3990): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart)
I/flutter ( 3990): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525:5)
I/flutter ( 3990): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 3990): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 3990): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562:16)
I/flutter ( 3990): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter ( 3990): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter ( 3990): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525:5)
I/flutter ( 3990): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 3990): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 3990): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562:16)
I/flutter ( 3990): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter ( 3990): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter ( 3990): #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart)
I/flutter ( 3990): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525:5)
I/flutter ( 3990): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 3990): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 3990): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562:16)
I/flutter ( 3990): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter ( 3990): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter ( 3990): #55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart)
I/flutter ( 3990): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525:5)
I/flutter ( 3990): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 3990): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 3990): #59     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:809:16)
I/flutter ( 3990): #60     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:780:5)
I/flutter ( 3990): #61     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:726:17)
I/flutter ( 3990): #62     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2231:19)
I/flutter ( 3990): #63     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:725:13)
I/flutter ( 3990): #64     _____BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:616:7)
I/flutter ( 3990): #65     runApp (package:flutter/src/widgets/binding.dart:658:7)
I/flutter ( 3990): #66     main (file:///$HOME/projects/flutter/test_root6/flutter/flutter/examples/flutter_gallery/lib/main.dart:13:3)
I/flutter ( 3990): #67     _startIsolate.<anonymous closure> (dart:isolate:1252:19)
I/flutter ( 3990): #68     _RawReceivePortImpl._handleMessage (dart:isolate:1142:12)
I/flutter ( 3990): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Here is snippet of kernel files(full kernel files are attached to the bug).

new failing:
```
    get _localizationsDelegates() → core::Iterable<loc::LocalizationsDelegate<dynamic>> /* originally sync* */ {
      dynamic :await_jump_var = 0;
      dynamic :await_ctx_var;
      function :sync_op(core::_SyncIterator<loc::LocalizationsDelegate<dynamic>> :iterator) → core::bool yielding {
        {
          if(!this.{fra::State::widget}.localizationsDelegates.==(null)) {
            :iterator.{core::_SyncIterator::isYieldEach} = true;
            :iterator.{core::_SyncIterator::_current} = this.{fra::State::widget}.localizationsDelegates;
            [yield] true;
          }
          {
            :iterator.{core::_SyncIterator::_current} = loc::DefaultWidgetsLocalizations::delegate;
            [yield] true;
          }
        }
        return false;
      }
      return new core::_SyncIterable::•<loc::LocalizationsDelegate<dynamic>>(:sync_op);
    }
```
old working:
```
    get _localizationsDelegates() → core::Iterable<loc::LocalizationsDelegate<dynamic>> /* originally sync* */ {
      dynamic :await_jump_var = 0;
      dynamic :await_ctx_var;
      function :sync_op(core::Iterator<dynamic> :iterator) → core::bool yielding {
        {
          if(!this.{fra::State::widget}.localizationsDelegates.==(null)) {
            :iterator.isYieldEach = true;
            :iterator._current = this.{fra::State::widget}.localizationsDelegates;
            [yield] true;
          }
          {
            :iterator._current = loc::DefaultWidgetsLocalizations::delegate;
            [yield] true;
          }
        }
        return false;
      }
      return new core::_SyncIterable::•(:sync_op);
    }
```

[dills.zip](https://github.com/dart-lang/sdk/files/1404512/dills.zip)

@peter-ahe-google @sigmundch any thoughts ?

@jason-simmons FYI - this I believe will result in failing `--preview-dart-2` tests in next flutter roll.

**Comment by mraleph** [comment]
This was my bug and should have been fixed by: https://dart-review.googlesource.com/c/sdk/+/15542

Please reopen if it is not.

**Comment by aam** [comment]
Thanks, @mraleph , rolling up to 9cd7bc724dfb6ed13c51dc86272963d99abd3fd1 did indeed fix the issue.
