### ISSUE TITLE
Fasta crash on missing "part of" declaration

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#31210]
In `whatever.dart`:
```dart
part 'whatever_part.dart';

main() {}
```
In `whatever_part.dart`:
```dart
//part of 'whatever.dart';
```

Compiling `whatever.dart` gives:
```
Unhandled exception:
Cannot bind root::file:///usr/local/google/home/askesc/whatever_part.dart::@methods::main to #lib1::main, target is already bound to root::file:///usr/local/google/home/askesc/whatever.dart::@methods::main
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:157:7)
#1      Library.computeCanonicalNames (package:kernel/ast.dart:378:48)
#2      Program.computeCanonicalNames (package:kernel/ast.dart:4959:15)
#3      BinaryPrinter.computeCanonicalNames (package:kernel/binary/ast_to_binary.dart:182:13)
#4      BinaryPrinter.writeProgramFile (package:kernel/binary/ast_to_binary.dart:202:5)
#5      writeProgramToFile (package:front_end/src/fasta/kernel/utils.dart:37:29)
<asynchronous suspension>
#6      CompileTask.compile (file:///usr/local/google/home/askesc/Drive/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:164:11)
<asynchronous suspension>
#7      compile.<anonymous closure> (file:///usr/local/google/home/askesc/Drive/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:98:25)
<asynchronous suspension>
#8      withGlobalOptions.<anonymous closure> (file:///usr/local/google/home/askesc/Drive/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:375:13)
#9      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#10     _rootRun (dart:async/zone.dart:1124)
#11     _CustomZone.run (dart:async/zone.dart:1021)
#12     runZoned (dart:async/zone.dart:1499)
#13     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#14     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#15     withGlobalOptions (file:///usr/local/google/home/askesc/Drive/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:368:26)
#16     compile (file:///usr/local/google/home/askesc/Drive/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:91:18)
<asynchronous suspension>
#17     compileEntryPoint (file:///usr/local/google/home/askesc/Drive/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:49:11)
<asynchronous suspension>
#18     main (file:///usr/local/google/home/askesc/Drive/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

**Comment by askeksa-google** [comment]
This was fixed by https://github.com/dart-lang/sdk/commit/e3c11c2703ddd25153bd11147bc97793e55c7ee3
