### ISSUE TITLE
Analysis server error: Cannot extract a file path from a package URI

### ISSUE THREAD

**Issue by pylaligand** [dart-lang/sdk#31216]
With an analysis server built at `68a4c5783d5fef10a512efff4c6d4f9842066ba5`, I'm getting the following error:
```
#0      _SimpleUri.toFilePath (dart:core/uri.dart:4558)
#1      _Visitor._isDefinedInLib (package:linter/src/rules/public_member_api_docs.dart:122)
#2      _Visitor.visitCompilationUnit (package:linter/src/rules/public_member_api_docs.dart:210)
#3      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#4      ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2756)
#5      List.forEach (dart:core-patch/growable_array.dart:267)
#6      ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2754)
#7      UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#8      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#9      LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:254)
#10     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:136)
#11     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#12     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:135)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#14     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:134)
#15     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:75)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#17     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:74)
#18     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1210)
<asynchronous suspension>
#19     PerformanceLog.runAsync (package:front_end/src/base/performace_logger.dart:52)
<asynchronous suspension>
#20     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1172)
<asynchronous suspension>
#21     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1001)
<asynchronous suspension>
#22     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1814)
<asynchronous suspension>
#23     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1757)
#24     new AnalysisServer (package:analysis_server/src/analysis_server.dart:378)
#25     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#26     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#27     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:430)
#28     _rootRun (dart:async/zone.dart:1120)
#29     _CustomZone.run (dart:async/zone.dart:1001)
#30     runZoned (dart:async/zone.dart:1467)
#31     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:470)
#32     Driver.start (package:analysis_server/src/server/driver.dart:429)
#33     some local program using analysis_server_lib to start the service
```

The URI in question is of the form `package:foo/src/bar.dart` and I confirmed that there's an entry for it in the .packages file.

Am I holding it wrong? :)

/cc @zanderso @scheglov @bwilkerson

**Comment by scheglov** [comment]
There are several problems with the way this lint rule is implemented.

1. You should not use `uri.toFilePath()` because it works only for `file://` URIs. Use `source.fullName` to get the absolute path and then ask `ResourceProvider`.

2. You should not use `PhysicalResourceProvider` because you get code get cannot be unit tested without I/O. Pass in the `ResourceProvider` with which the `AnalysisDriver` instance is created.

/cc @pq

**Comment by pylaligand** [comment]
Did any of this change recently? It was working fine last week.

**Comment by bwilkerson** [comment]
The lines in question changed on 10/4.

@devoncarew

**Comment by pylaligand** [comment]
I confirm that reverting these few lines to pre-10/4 version fixes the issue.

**Comment by devoncarew** [comment]
It sounds like you're unblocked for now. I'll look at a fix to the lint this afternoon / tomorrow timeframe.

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/linter#822
