### ISSUE TITLE
Analysis exception during edit.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#31212]
Occurred while editing.

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-172.4343.14`
- `2.0.0-edge.0eb9528be827d957ec52e54a60c8379680e21d17`
- `IC-172.4343.14, JRE 1.8.0_152-release-915-b12x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 2560x1600`

# Exception
```
Dart analysis server, SDK version 2.0.0-edge.0eb9528be827d957ec52e54a60c8379680e21d17, server version 1.18.4, error: Exception while using a Visitor to visit a CommentImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
RangeError (start): Invalid value: Not in range 0..166, inclusive: -1
#0      _StringBase.indexOf (dart:core-patch/dart:core/string_patch.dart:316)
#1      String.indexOf (dart:core-patch/dart:core/string_patch.dart:1001)
#2      Visitor.visitComment (package:linter/src/rules/comment_references.dart:71)
#3      CommentImpl.accept (package:analyzer/src/dart/ast/ast.dart:2229)
#4      ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2756)
#5      List.forEach (dart:core-patch/dart:core/growable_array.dart:270)
#6      ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2754)
#7      UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:2943)
#8      CommentImpl.accept (package:analyzer/src/dart/ast/ast.dart:2229)
#9      AnnotatedNodeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:162)
#10     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7478)
#11     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#12     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3106)
#13     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7474)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7987)
#15     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1974)
#16     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#17     UnifyingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:2937)
#18     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1906)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7987)
#20     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2502)
#21     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#22     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#23     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#24     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:254)
#25     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:136)
#26     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:360)
#27     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:135)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#29     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:134)
#30     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:75)
#31     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#32     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:74)
#33     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1210)
<asynchronous suspension>
#34     PerformanceLog.runAsync (package:front_end/src/base/performace_logger.dart:52)
<asynchronous suspension>
#35     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1172)
<asynchronous suspension>
#36     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:870)
<asynchronous suspension>
#37     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1814)
<asynchronous suspension>
#38     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1757)
#39     new AnalysisServer (package:analysis_server/src/analysis_server.dart:378)
#40     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#41     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#42     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:430)
#43     _rootRun (dart:async/zone.dart:1124)
#44     _CustomZone.run (dart:async/zone.dart:1021)
#45     runZoned (dart:async/zone.dart:1499)
#46     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:470)
#47     Driver.start (package:analysis_server/src/server/driver.dart:429)
#48     main (file:///Users/pquitslund/src/git/clones/dart/sdk/pkg/analysis_server/bin/server.dart:12)
#49     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

```
1508868341309 <= 			+++ Link bundles.
1508868341309 <= 				Linked 0 bundles.
1508868341309 <= 			--- Link bundles in 0 ms.
1508868341309 <= 		--- Create library context in 2 ms.
1508868341338 <= 		Computed new analysis result.
1508868341338 <= 	--- Compute analysis result for /Users/pquitslund/src/git/clones/linter/lib/src/rules/avoid_positional_boolean_parameters.dart in 30 ms.
1508868341338 <= {"event":"analysis.errors","params":{"file":"/Users/pquitslund/src/git/clones/linter/lib/src/rules/avoid_positional_boolean_parameters.dart","errors":[{"severity":"ERROR","type":"STAT
1508868341339 <= {"id":"1074","result":{"assists":[]}}
1508868341339 <= {"id":"1075","result":{"assists":[]}}
1508868341340 <= {"event":"analysis.highlights","params":{"file":"/Users/pquitslund/src/git/clones/linter/lib/src/rules/avoid_positional_boolean_parameters.dart","regions":[{"type":"DIRECTIVE","offset
1508868341342 <= {"event":"analysis.navigation","params":{"file":"/Users/pquitslund/src/git/clones/linter/lib/src/rules/avoid_positional_boolean_parameters.dart","regions":[{"offset":224,"length":32,"
1508868341343 <= {"event":"analysis.overrides","params":{"file":"/Users/pquitslund/src/git/clones/linter/lib/src/rules/avoid_positional_boolean_parameters.dart","overrides":[{"offset":1421,"length":10
1508868341345 <= --- Analyzing in 46 ms.
1508868341345 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1508868341347 <= {"event":"analysis.implemented","params":{"file":"/Users/pquitslund/src/git/clones/linter/lib/src/rules/avoid_positional_boolean_parameters.dart","classes":[],"members":[]}}
1508868341645 => {"id":"1076","method":"edit.getFixes","params":{"file":"/Users/pquitslund/src/git/clones/linter/lib/src/rules/avoid_positional_boolean_parameters.dart","offset":2441},"clientRequestTi
1508868341683 <= +++ Analyzing.
1508868341683 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1508868341684 <= 	+++ Compute analysis result for /Users/pquitslund/.pub-cache/hosted/pub.dartlang.org/analyzer-0.31.0-alpha.0/lib/dart/ast/ast.dart.
1508868341684 <= 		+++ Create library context.
1508868341684 <= 			+++ Append library files.
1508868341684 <= 			--- Append library files in 0 ms.
1508868341684 <= 			+++ Load linked bundles.
1508868341685 <= 				Loaded 567 linked bundles.
1508868341685 <= 			--- Load linked bundles in 1 ms.
1508868341686 <= 			+++ Link bundles.
1508868341686 <= 				Linked 0 bundles.
1508868341686 <= 			--- Link bundles in 0 ms.
1508868341686 <= 		--- Create library context in 2 ms.
1508868341942 <= {"event":"server.error","params":{"isFatal":false,"message":"Exception while using a Visitor to visit a CommentImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnit
```

**Comment by pq** [comment]
cc @bwilkerson @scheglov

**Comment by pq** [comment]
Great catch.  Thank you!

**Comment by pq** [comment]
This issue was moved to dart-lang/linter#819
