### ISSUE TITLE
Fasta crash on nested generic function types

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#31213]
```
$ cat <<EOF >test.dart

typedef C<A, K> = int Function<B>(A x, K y, B v);
typedef D<K> = C<A, K> Function<A>(int z);

dynamic producer<K>() {
  return <A>(int v1) {
    return <B>(A v2, K v3, B v4) => 0;
  };
}

main() {
  assert(producer<String>() is D<String>);
}
EOF

$ DART_CONFIGURATION=DebugX64 ./pkg/front_end/tool/fasta compile test.dart

Unhandled exception:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept(Instance of '_InnerTypeSubstitutor')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _TypeSubstitutor.visit (package:kernel/type_algebra.dart:389:41)
#2      _InnerTypeSubstitutor.freshTypeParameter (package:kernel/type_algebra.dart:343:19)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#4      ListIterable.toList (dart:_internal/iterable.dart:218)
#5      _TypeSubstitutor.freshTypeParameters (package:kernel/type_algebra.dart:415:47)
#6      _TypeSubstitutor.visitFunctionType (package:kernel/type_algebra.dart:436:32)
#7      FunctionType.accept (package:kernel/ast.dart:4570:34)
#8      _TypeSubstitutor.visit (package:kernel/type_algebra.dart:389:41)
#9      Substitution.substituteType (package:kernel/type_algebra.dart:239:53)
#10     substitute (package:kernel/type_algebra.dart:19:45)
#11     KernelFunctionTypeAliasBuilder.buildTypesWithBuiltArguments (package:front_end/src/fasta/kernel/kernel_function_type_alias_builder.dart:92:12)
#12     KernelFunctionTypeAliasBuilder.buildType (package:front_end/src/fasta/kernel/kernel_function_type_alias_builder.dart:109:12)
#13     KernelNamedTypeBuilder.build (package:front_end/src/fasta/kernel/kernel_named_type_builder.dart:46:20)
#14     KernelFunctionTypeBuilder.build (package:front_end/src/fasta/kernel/kernel_function_type_builder.dart:40:21)
...
```

**Comment by a-siva** [comment]
cc @sigmundch

**Comment by sjindel-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/16360

**Comment by sjindel-google** [comment]
VM support for nested generic function types in the Kernel FE should be ready.

**Comment by sjindel-google** [comment]
When this issue is resolved, support for nested generic function types in the VM's Kernel FE should be tested further.

**Comment by peter-ahe-google** [comment]
Is running the above program in strong mode sufficient testing?

**Comment by sjindel-google** [comment]
We can't run the program at all through the Kernel FE since Fasta doesn't produce any output.

**Comment by peter-ahe-google** [comment]
Once this bug in Fasta has been fixed, what would you consider sufficient testing? The above program?

**Comment by sjindel-google** [comment]
It would definitely be a good start, although I would like to write some more involved tests as well.
We are severely lacking test coverage for generic methods and functions.

**Comment by peter-ahe-google** [comment]
Thank you.

In that case, I suggest you create a separate bug for tracking the test coverage.
