### ISSUE TITLE
Analysis server crash

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/sdk#31283]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-172.4155.36`
- `1.24.2`
- `IU-172.4155.36, JRE 1.8.0_152-release-915-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1440x900`

# Exception

Please append the contents of:
file:///private/var/folders/md/xrrg3dn921l5_qw7v2l3cb9w0000gn/T/report1.txt

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Analysis failed: /Users/thosakwe/Source/Dart/lex/example/calculator.dart context: exception_20171103_232321_639
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1096)
#1      ParameterElementForLink.type (package:analyzer/src/summary/link.dart:4204)
#2      FunctionTypeImpl.parameters (package:analyzer/src/dart/element/type.dart:594)
#3      InstanceMemberInferrer._inferParameterCovariance.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:458)
#4      Object

**Comment by thosakwe** [comment]
```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Analysis failed: /Users/thosakwe/Source/Dart/lex/example/calculator.dart context: exception_20171103_232321_639
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1096)
#1      ParameterElementForLink.type (package:analyzer/src/summary/link.dart:4204)
#2      FunctionTypeImpl.parameters (package:analyzer/src/dart/element/type.dart:594)
#3      InstanceMemberInferrer._inferParameterCovariance.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:458)
#4      Object&ListMixin.any (dart:collection/list.dart:115)
#5      InstanceMemberInferrer._inferParameterCovariance (package:analyzer/src/task/strong_mode.dart:457)
#6      InstanceMemberInferrer._inferExecutable (package:analyzer/src/task/strong_mode.dart:400)
#7      InstanceMemberInferrer._inferClass.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:333)
#8      List.forEach (dart:core-patch/growable_array.dart:256)
#9      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:332)
#10     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:107)
#11     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1302)
#12     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3672)
#13     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3408)
#14     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3330)
#15     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#16     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#17     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#18     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#19     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3373)
#20     Linker.link (package:analyzer/src/summary/link.dart:3897)
#21     relink (package:analyzer/src/summary/link.dart:132)
#22     link (package:analyzer/src/summary/link.dart:113)
#23     new LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:116)
#24     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#25     new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:115)
#26     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#27     new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:53)
#28     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1092)
#29     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:989)
#30     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#31     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#32     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:854)
<asynchronous suspension>
#33     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#34     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#35     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#36     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#37     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#38     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#39     _rootRun (dart:async/zone.dart:1120)
#40     _CustomZone.run (dart:async/zone.dart:1001)
#41     runZoned (dart:async/zone.dart:1467)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#43     Driver.start (package:analysis_server/src/server/driver.dart:473)
#44     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analysis_server/bin/server.dart:12)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1509765796629 started analysis server:
  /usr/local/opt/dart/libexec/bin/dart /usr/local/opt/dart/libexec/bin/snapshots/analysis_server.dart.snapshot --client-id=IntelliJ-IDEA --client-version=IU-172.4155.36 --useAnalysisHighlight2
1509765798188 <= {"event":"server.connected","params":{"version":"1.18.0","pid":70611,"sessionId":""}}
1509765798268 <= {"id":"0","result":{"version":"1.18.0"}}
1509765798271 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1509765796642}
1509765798271 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1509765798272 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["/Users/thosakwe/Source/Dart/lex"],"excluded":["/Users/thosakwe/Source/Dart/lex/.idea","/Users/thosakwe/Source/Dar
1509765798272 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["/Users/thosakwe/Source/Dart/lex/example/query_string.dart"]},"clientRequestTime":1509765796644}
1509765798272 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["/Users/thosakwe/Source/Dart/lex/example/query_string.dart"],"OVERRIDES":["/Users/thosakwe/Sour
1509765798280 <= {"id":"1"}
1509765798290 <= {"id":"2"}
1509765798469 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1509765798474 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1509765799333 <= {"id":"3"}
1509765799333 <= {"id":"4"}
1509765799492 <= {"id":"5"}
1509765799503 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1509765801664 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/thosakwe/Source/Dart/lex/example/calculator.dart context: exception_20171103_232321_639","stackTra
```

**Comment by thosakwe** [comment]
`calculator.dart`: https://github.com/thosakwe/combinator/blob/master/example/calculator.dart

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
