### ISSUE TITLE
Dart compilation failed 

### ISSUE THREAD

**Issue by timk10** [dart-lang/sdk#31337]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-172.4155.35`
- `1.21.1`
- `WS-172.4155.35, JRE 1.8.0_152-release-915-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.3 unknown, screens 1440x900, 2560x1440  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/6r/t7ll03vd4ys_5l55ff_qczm40000gp/T/report.txt

```
Dart analysis server, SDK version 1.21.1, server version 1.17.0, error: Task failed: BuildCompilationUnitElementTask for source /Users/tim/work/core/appserver/lib/src/controllers/psessionclientcontroller.dart
Element mismatch in /Users/tim/work/core/appserver/lib/src/controllers/psessionclientcontroller.dart at class PSessionClientController extends BaseController
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:50)
#1      BuildCompilationUnitElementTask.internalPerform (package:analyzer/src/task/dart.dart:1082)
#2      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#3      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#4      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#5      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#6      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#8      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#9      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#10     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:972)
#11     Future.Future.<anonymous closure> (dart:async/future.dart:118)
[report.txt](https://github.com/dart-lang/sdk/files/1458659/report.txt)

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
