### ISSUE TITLE
dartdevk.dart fails to compile programs

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#31400]
Steps to reproduce:

```bash
$ ./tools/build.py -m release -a x64 dartdevc_test
...
$ dart -c pkg/dev_compiler/bin/dartdevk.dart -o asdf.js asdf.dart 
Unhandled exception:
FormatException: Bad UTF-8 encoding 0x88 (at offset 6812578)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:568)
#1      Utf8Decoder.convert (dart:convert/utf.dart:344)
#2      BinaryBuilder.readStringEntry (package:kernel/binary/ast_from_binary.dart:116:10)
#3      BinaryBuilder.readStringTable (package:kernel/binary/ast_from_binary.dart:150:18)
#4      BinaryBuilder._readOneProgram (package:kernel/binary/ast_from_binary.dart:457:5)
#5      BinaryBuilder.readProgram (package:kernel/binary/ast_from_binary.dart:369:7)
#6      ProcessedOptions.loadProgram (package:front_end/src/base/processed_options.dart:298:43)
#7      ProcessedOptions.loadSdkSummary (package:front_end/src/base/processed_options.dart:257:28)
<asynchronous suspension>
#8      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:60:36)
<asynchronous suspension>
#9      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:31:18)
<asynchronous suspension>
#10     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#11     _rootRun (dart:async/zone.dart:1124)
#12     _CustomZone.run (dart:async/zone.dart:1021)
#13     runZoned (dart:async/zone.dart:1499)
#14     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#15     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#16     generateKernel (package:front_end/src/kernel_generator_impl.dart:30:32)
<asynchronous suspension>
#17     compile (package:dev_compiler/src/kernel/command.dart:83:30)
<asynchronous suspension>
#18     main (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/dev_compiler/bin/dartdevk.dart:18:27)
<asynchronous suspension>
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by kmillikin** [comment]
I suspect that this was triggered by @mkustermann's change, but not really caused by it.  It looks like we're using two different versions of the Kernel package.

**Comment by mkustermann** [comment]
I'll take a look and re-assign if I cannot fix it.

**Comment by mkustermann** [comment]
So for me it looks like this:
```
% echo 'main() => print("hello");' > asdf.dart

%  ./tools/build.py -m release -a x64 dartdevc_test
...

% dart -c pkg/dev_compiler/bin/dartdevk.dart -o asdf.js asdf.dart
Error: SDK summary not found: pkg/dev_compiler/lib/sdk/ddc_sdk.dill.
Unhandled exception:
FileSystemException(uri=file:///usr/local/...sdk/pkg/dev_compiler/lib/sdk/ddc_sdk.dill; message=No such file or directory)
#0      _PhysicalFileSystemEntity.readAsBytes (package:front_end/physical_file_system.dart:60:7)
<asynchronous suspension>
...

% dart -c pkg/dev_compiler/bin/dartdevk.dart --dart-sdk-summary=out/ReleaseX64/gen/utils/dartdevc/ddc_sdk.dill  -o asdf.js asdf.dart

% ls -lh asdf.js
-rw-r----- 1 kustermann eng 385 Nov 17 13:28 asdf.js
```
@stefantsov 
Could it be that you have a stale `pkg/dev_compiler/lib/sdk/ddc_sdk.dill` in your filesystem? You need to pass `--dart-sdk-summary=out/ReleaseX64/gen/utils/dartdevc/ddc_sdk.dill` to the `dartdevk.dart` tool I think.

**Comment by stefantsov** [comment]
@mkustermann Ah! Thank you!
