### ISSUE TITLE
Fasta crashes when "dynamic" is given type arguments.

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#31416]
```
$ cat <<EOF >test.dart
dynamic<int> x = null;
main() {
  x.toString();
}
$ DART_CONFIGURATION=ReleaseX64 ./pkg/front_end/tool/fasta compile --platform=vm_platform_strong.dill --strong test.dart
Note: strong mode support is preliminary and may not work.
Unhandled exception:
test.dart:1:1: Internal problem: Unhandled DynamicTypeBuilder<KernelTypeBuilder, dynamic> in TypeDeclarationAccessor.buildType.
dynamic<int> x = null;
^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:41:10)
#2      TypeDeclarationAccessor.buildType (package:front_end/src/fasta/kernel/fasta_accessors.dart:1076:16)
#3      BodyBuilder.handleType (package:front_end/src/fasta/kernel/body_builder.dart:1838:17)
#4      Parser.parseType.commitType (package:front_end/src/fasta/parser/parser.dart:2014:18)
#5      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:2097:26)
#6      Parser.parseModifiers (package:front_end/src/fasta/parser/parser.dart:3116:13)
#7      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2595:19)
#8      Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2577:11)
#9      DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:721:22)
#10     DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:564:5)
#11     DietListener.endTopLevelFields (package:front_end/src/fasta/source/diet_listener.dart:251:5)
#12     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2619:16)
#13     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2577:11)
#14     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:393:14)
#15     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:308:15)
#16     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:181:14)
<asynchronous suspension>
#17     Loader.buildBodies (package:front_end/src/fasta/loader.dart:136:13)
<asynchronous suspension>
#18     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:291:20)
<asynchronous suspension>
#19     CompileTask.compile (file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:160:38)
<asynchronous suspension>
#20     compile.<anonymous closure> (file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:98:25)
<asynchronous suspension>
#21     withGlobalOptions.<anonymous closure> (file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:376:13)
#22     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#23     _rootRun (dart:async/zone.dart:1126)
#24     _CustomZone.run (dart:async/zone.dart:1023)
#25     runZoned (dart:async/zone.dart:1501)
#26     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#27     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#28     withGlobalOptions (file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:369:26)
#29     compile (file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:91:18)
<asynchronous suspension>
#30     compileEntryPoint (file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:49:11)
<asynchronous suspension>
#31     main (file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

**Comment by eernstg** [comment]
Note the connection to #28811: [This CL](https://dart-review.googlesource.com/c/sdk/+/21080) introduced 'tests/language_2/built_in_identifier_type_annotation.dart' where the declaration `dynamic<int> x = null;` caused the insertion of several status file entries, which might delineate the nature of this problem:
```dart
language_2_analyzer.status:built_in_identifier_type_annotation_test/22: MissingCompileTimeError # Issue 28813
language_2_dart2js.status:built_in_identifier_type_annotation_test/22: MissingCompileTimeError # Error only in strong mode
language_2_dart2js.status:built_in_identifier_type_annotation_test/22: Crash # Issue 28815
language_2_dartdevc.status:built_in_identifier_type_annotation_test/22: MissingCompileTimeError # Issue 28816
language_2_kernel.status:built_in_identifier_type_annotation_test/22: DartkCrash # Issue 28814
language_2_kernel.status:built_in_identifier_type_annotation_test/22: MissingCompileTimeError # Error only in strong mode
language_2_kernel.status:built_in_identifier_not_prefix_test/22: MissingCompileTimeError # Issue 28814
language_2_kernel.status:built_in_identifier_type_annotation_test/22: Crash # Issue 28814
language_2_kernel.status:built_in_identifier_type_annotation_test/22: DartkCrash # Issue 28814
language_2_vm.status:built_in_identifier_type_annotation_test/22: MissingCompileTimeError # Error only in strong mode
```

**Comment by vsmenon** [comment]
@kmillikin - I bumped this to Beta 3.  Can you move to [Beta 4 ](https://github.com/dart-lang/sdk/milestone/54)or [Dart 2](https://github.com/dart-lang/sdk/milestone/12) if one of those is more appropriate?

**Comment by askeksa-google** [comment]
Works now.

**Comment by sjindel-google** [comment]
Why isn't it closed?

**Comment by askeksa-google** [comment]
I was thinking it lacked a regression test. But we have one in the fix: https://dart-review.googlesource.com/c/sdk/+/42744
