### ISSUE TITLE
Analyzer library crashes on test 0.12.28

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#31418]
_From @dustyholmes-wf on November 20, 2017 15:28_

After the release of 0.12.27 I started experiencing a dartdoc failure in a private project containing test utilities. 

The issue is resolved if I require <=0.12.26

Relevant dependencies:
- analyzer 0.30.0+4
- dartdoc 0.14.1
- test 0.12.28

```
Generation failed: AnalysisException: Cannot compute LIBRARY_ELEMENT for lib/automation.dart
Caused by Unexpected exception while performing ResolveUnitTypeNamesTask for source /Users/dusty/.pub-cache/hosted/pub.dartlang.org/test-0.12.28/lib/src/backend/invoker.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:730)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:697)
#6      DartDoc._parseLibraries.processLibrary (package:dartdoc/dartdoc.dart:507)
#7      List.forEach (dart:core-patch/growable_array.dart:256)
#8      DartDoc._parseLibraries (package:dartdoc/dartdoc.dart:512)
#9      DartDoc.generateDocs (package:dartdoc/dartdoc.dart:136)
<asynchronous suspension>
#10     main.<anonymous closure> (http://localhost:57749/dartdoc.dart:200)
<asynchronous suspension>
#11     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:101)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     runZoned (dart:async/zone.dart:1467)
#15     Chain.capture (package:stack_trace/src/chain.dart:99)
#16     main (http://localhost:57749/dartdoc.dart:199)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

Caused by NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9944)
#3      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5774)
#4      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11238)
#5      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#6      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10105)
#7      UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228)
#8      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11233)
#9      FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4404)
#10     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#11     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10105)
#12     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:3011)
#13     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399)
#14     TypeResolverVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:9806)
#15     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7359)
#16     TypeResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:9752)
#17     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#19     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#20     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#21     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10105)
#22     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#23     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#24     ResolveUnitTypeNamesTask.internalPerform (package:analyzer/src/task/dart.dart:5134)
#25     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#26     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#27     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#28     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#29     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:730)
#30     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:697)
#31     DartDoc._parseLibraries.processLibrary (package:dartdoc/dartdoc.dart:507)
#32     List.forEach (dart:core-patch/growable_array.dart:256)
#33     DartDoc._parseLibraries (package:dartdoc/dartdoc.dart:512)
#34     DartDoc.generateDocs (package:dartdoc/dartdoc.dart:136)
<asynchronous suspension>
#35     main.<anonymous closure> (http://localhost:57749/dartdoc.dart:200)
<asynchronous suspension>
#36     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:101)
#37     _rootRun (dart:async/zone.dart:1120)
#38     _CustomZone.run (dart:async/zone.dart:1001)
#39     runZoned (dart:async/zone.dart:1467)
#40     Chain.capture (package:stack_trace/src/chain.dart:99)
#41     main (http://localhost:57749/dartdoc.dart:199)
<asynchronous suspension>
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


package:analyzer/src/context/context.dart 735  AnalysisContextImpl.computeResult
package:analyzer/src/context/context.dart 697  AnalysisContextImpl.computeLibraryElement
package:dartdoc/dartdoc.dart 507               DartDoc._parseLibraries.processLibrary
dart:core                                      List.forEach
package:dartdoc/dartdoc.dart 512               DartDoc._parseLibraries
package:dartdoc/dartdoc.dart 136               DartDoc.generateDocs
===== asynchronous gap ===========================
dart:async                                     _Completer.completeError
package:dartdoc/dartdoc.dart 216               DartDoc.generateDocs
===== asynchronous gap ===========================
dart:async                                     new Future.microtask
package:dartdoc/dartdoc.dart 128               DartDoc.generateDocs
http://localhost:57749/dartdoc.dart 200        main.<fn>
===== asynchronous gap ===========================
dart:async                                     new Future.microtask
http://localhost:57749/dartdoc.dart 199        main.<fn>
package:stack_trace                            Chain.capture
http://localhost:57749/dartdoc.dart 199        main
```

_Copied from original issue: dart-lang/test#722_

**Comment by nex3** [comment]
I've moved this issue here because it seems like a bug in the analyzer library that it would crash when trying to resolve a library in test. It's also worth noting that the analyzer executable completes successfully on the same version of test, without reporting any errors.

**Comment by dustyholmes-wf** [comment]
I also created https://github.com/dart-lang/sdk/issues/31413 here for that reason.

**Comment by nex3** [comment]
I'll close this as a duplicate then.
