### ISSUE TITLE
Crash in scavenger on dartk-vm release_x64 service/set_library_debuggable_test

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#31439]
/cc @rmacnak-google 

```
=== Failure summary:
FAILED: dartk-vm release_x64 service/set_library_debuggable_test
Expected: Pass
Actual: Crash
--- Command "vm" (took 04.000495s):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --dfe=xcodebuild/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=xcodebuild/ReleaseX64 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/.packages /b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/runtime/observatory/tests/service/set_library_debuggable_test.dart
stdout:
** Launching SERVICE_TEST_TESTEE=true xcodebuild/ReleaseX64/dart -DDART_SERVICE_USE_AUTH=false --profiler --dfe=xcodebuild/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=xcodebuild/ReleaseX64 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/.packages --enable-vm-service:0 /b/build/slave/vm-kernel-mac-release-x64-be/build/sdk/runtime/observatory/tests/service/set_library_debuggable_test.dart
>testee>out> Observatory listening on http://127.0.0.1:52217/
** Signaled to run test queries on http://127.0.0.1:52217/
>testee>out> 
Loading VM...
Done loading VM
Running set_library_debuggable_test.dart [1/16]
Paused with PauseBreakpoint
Running set_library_debuggable_test.dart [2/16]
stderr:
Dumping native stack trace for thread 1603
  [0x000000010196a225] dart::RawObject::SizeFromClass() const
  [0x000000010196a225] dart::RawObject::SizeFromClass() const
  [0x00000001019c4f05] dart::Scavenger::ProcessToSpace(dart::ScavengerVisitor*)
  [0x00000001019c57a9] dart::Scavenger::Scavenge()
  [0x00000001018266c1] dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::Heap::GCReason)
  [0x00000001018255ad] dart::Heap::AllocateNew(long)
  [0x000000010185bf94] dart::Object::Allocate(long, long, dart::Heap::Space)
  [0x00000001018605bb] dart::Array::New(long, dart::Heap::Space)
  [0x0000000101aff41f] dart::kernel::StreamingFlowGraphBuilder::BuildSuperMethodInvocation(dart::TokenPosition*)
  [0x0000000101af7155] dart::kernel::StreamingFlowGraphBuilder::BuildExpression(dart::TokenPosition*)
  [0x0000000101b06b2e] dart::kernel::StreamingFlowGraphBuilder::BuildReturnStatement()
  [0x0000000101afb9b2] dart::kernel::StreamingFlowGraphBuilder::BuildStatement()
  [0x0000000101b04458] dart::kernel::StreamingFlowGraphBuilder::BuildBlock()
  [0x0000000101afb945] dart::kernel::StreamingFlowGraphBuilder::BuildStatement()
  [0x0000000101afac8f] dart::kernel::StreamingFlowGraphBuilder::BuildGraphOfFunction(bool)
  [0x0000000101afbd01] dart::kernel::StreamingFlowGraphBuilder::BuildGraph(long)
  [0x0000000101b1e3e3] dart::kernel::FlowGraphBuilder::BuildGraph()
  [0x0000000101a78262] dart::CallSiteInliner::TryInlining(dart::Function const&, dart::Array const&, dart::InlinedCallData*)
  [0x0000000101a82d08] dart::CallSiteInliner::InlineStaticCalls()
  [0x0000000101a7e82b] dart::CallSiteInliner::InlineCalls()
  [0x0000000101a7e3f5] dart::FlowGraphInliner::Inline()
  [0x0000000101b46509] dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  [0x0000000101b478fd] dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long)
  [0x0000000101b4883a] dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)
  [0x0000000101b4a4c8] dart::BackgroundCompiler::Run()
  [0x00000001019fa87d] dart::ThreadPool::Worker::Loop()
  [0x00000001019fa728] dart::ThreadPool::Worker::Main(unsigned long)
  [0x00000001018f9a17] dart::ThreadStart(void*)
  [0x00007fff8b5ff99d] _pthread_body
  [0x00007fff8b5ff91a] _pthread_body
  [0x00007fff8b5fd351] thread_start
-- End of DumpStackTrace
--- Re-run this test:
python tools/test.py -m release -c dartk -r vm service/set_library_debuggable_test
===
=== 1 test failed
===
```

**Comment by mkustermann** [comment]
Today there was a very similar crash on ia32: it crashes when doing scavenge on background compiler:

From [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8923466353338695824/+/steps/vm_tests_shard_1/0/stdout):
```
FAILED: dartk-vm release_ia32 standalone_2/io/raw_synchronous_socket_test
Expected: Pass
Actual: Crash

--- Command "vm" (took 08.000052s):
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/io/raw_synchronous_socket_test.dart

exit code:
-6

stdout:
unittest-suite-wait-for-done

stderr:
===== CRASH =====
version=2.2.0-edge.e97ddcbf642fe9844ea15d71167ab0665d9b35d6 (Thu Jan 24 07:50:40 2019 +0000) on "linux_ia32"
si_signo=Segmentation fault(11), si_code=1, si_addr=0x4
thread=1705, isolate=raw_synchronous_socket_test.dart:main()(0x37b6b00)
  [0x016a2680] Unknown symbol
  [0x016a2680] Unknown symbol
  [0x016a188d] dart::Scavenger::ProcessToSpace(dart::ScavengerVisitor*)
  [0x016a2180] dart::Scavenger::Scavenge()
  [0x0169626f] dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::Heap::GCReason)
  [0x01694def] dart::Heap::AllocateOld(int, dart::HeapPage::PageType)
  [0x0145a65e] dart::Object::Allocate(int, int, dart::Heap::Space)
  [0x01471e89] dart::Function::New(dart::String const&, dart::RawFunction::Kind, bool, bool, bool, bool, bool, dart::Object const&, dart::TokenPosition, dart::Heap::Space)
  [0x01487f8b] dart::Function::NewSignatureFunction(dart::Object const&, dart::Function const&, dart::TokenPosition, dart::Heap::Space)
  [0x016632f6] dart::kernel::TypeTranslator::BuildFunctionType(bool)
  [0x01662de5] dart::kernel::TypeTranslator::BuildTypeInternal()
  [0x016609b6] dart::kernel::TypeTranslator::BuildType()
  [0x0166c024] dart::kernel::ScopeBuilder::AddVariableDeclarationParameter(int, dart::kernel::ScopeBuilder::ParameterTypeCheckMode, dart::kernel::ProcedureAttributesMetadata const&)
  [0x016680ec] dart::kernel::ScopeBuilder::BuildScopes()
  [0x014dc3a0] dart::ParsedFunction::EnsureKernelScopes()
  [0x0163efc7] dart::kernel::StreamingFlowGraphBuilder::BuildGraph()
  [0x01652ca6] dart::kernel::FlowGraphBuilder::BuildGraph()
  [0x015d1586] Unknown symbol
  [0x015dc0cc] Unknown symbol
  [0x015d786f] Unknown symbol
  [0x015d74e3] dart::FlowGraphInliner::Inline()
  [0x01619679] Unknown symbol
  [0x016190ac] dart::CompilerPass::Run(dart::CompilerPassState*) const
  [0x01619366] dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)
  [0x016807dd] dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  [0x0168127b] Unknown symbol
  [0x01681e42] dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, int)
  [0x016834c7] dart::BackgroundCompiler::Run()
  [0x01683c47] Unknown symbol
  [0x01565dc1] dart::ThreadPool::Worker::Loop()
  [0x01565c8e] dart::ThreadPool::Worker::Main(unsigned int)
  [0x014db603] Unknown symbol
  [0xf7775f72] Unknown symbol
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -n dartk-optcounter-linux-release-ia32 standalone_2/io/raw_synchronous_socket_test
```

The dump is [available](https://isolateserver.appspot.com/browse?namespace=default-gzip&hash=e2b3eb0f249cf6d917bb2c6b2b49f2dc6c92e485):
```
https://isolateserver.appspot.com/browse?namespace=default-gzip&digest=b214a22c559b0a8106b203af035b6bb1042ab77e&as=core.1702.tar.gz
https://isolateserver.appspot.com/browse?namespace=default-gzip&digest=d1120351417335c0b01e4dc4da4a49303886e275&as=dart.tar.gz
```

I could open the dump and see those stacks
```
(gdb) info threads
  Id   Target Id         Frame 
  14   Thread 0xf63feb40 (LWP 1857) dart::PushArgumentInstr::Accept (this=0xf63fd030, visitor=0x392e300) at ../../runtime/vm/compiler/backend/il.cc:1002  // raw_synchronous_socket_test.dart:echoServer() BG compiler
  13   Thread 0xf0b7eb40 (LWP 1859) 0xf77a8cd9 in ?? ()
  12   Thread 0xf0bffb40 (LWP 1858) 0xf77a8cd9 in ?? ()
  11   Thread 0xf61fab40 (LWP 1711) 0xf77a8cd9 in ?? ()
* 10   Thread 0xf627bb40 (LWP 1710) 0xf77a8cd9 in ?? ()
  9    Thread 0xf62fcb40 (LWP 1709) 0xf77a8cd9 in ?? ()
  8    Thread 0xf657fb40 (LWP 1706) 0xf77a8cd9 in ?? ()
  7    Thread 0xf756cb40 (LWP 1703) 0xf77a8cd9 in ?? ()
  6    Thread 0xf0a7cb40 (LWP 1861) 0xf77a8cd9 in ?? ()
  5    Thread 0xf637db40 (LWP 1708) 0xf77a8cd9 in ?? ()
  4    Thread 0xf756d780 (LWP 1702) 0xf77a8cd9 in ?? ()
  3    Thread 0xf713fb40 (LWP 1704) AllocUnsafe (this=<optimized out>, size=24) at ../../runtime/vm/zone.h:205   // kernel-service BG compiler
  2    Thread 0xf0afdb40 (LWP 1860) 0xf77a8cd9 in ?? ()  
  1    Thread 0xf70beb40 (LWP 1705) 0xf77a8cd9 in ?? ()  // raw_synchronous_socket_test.dart:main() BG compiler (Crasher)

(gdb) thread 1
(gdb) bt
#0  0xf77a8cd9 in ?? ()
#1  <signal handler called>
#2  ScavengePointer (this=0xf70bbb50, p=0xf06001f8) at ../../runtime/vm/heap/scavenger.cc:131
#3  dart::ScavengerVisitor::VisitPointers (this=0xf70bbb50, first=0xf0600160, last=0xf0600358) at ../../runtime/vm/heap/scavenger.cc:86
#4  0x016a188d in VisitPointersNonvirtual<dart::ScavengerVisitor> (this=<optimized out>, visitor=<optimized out>) at ../../runtime/vm/raw_object.h:616
#5  dart::Scavenger::ProcessToSpace (this=0x378f004, visitor=0xf70bbb50) at ../../runtime/vm/heap/scavenger.cc:672
#6  0x016a2180 in dart::Scavenger::Scavenge (this=0x378f004) at ../../runtime/vm/heap/scavenger.cc:952
#7  0x0169626f in dart::Heap::CollectNewSpaceGarbage (this=0x378f000, thread=0x37bbe00, reason=dart::Heap::kFull) at ../../runtime/vm/heap/heap.cc:417
#8  0x01694def in CollectMostGarbage (this=<optimized out>, reason=dart::Heap::kFull) at ../../runtime/vm/heap/heap.cc:484
#9  dart::Heap::AllocateOld (this=0x378f000, size=16, type=dart::HeapPage::kData) at ../../runtime/vm/heap/heap.cc:101
#10 0x0145a65e in Allocate (this=<optimized out>, size=<optimized out>, space=<optimized out>) at ../../runtime/vm/heap/heap.h:83
#11 dart::Object::Allocate (cls_id=9, size=16, space=dart::Heap::kOld) at ../../runtime/vm/object.cc:2034
#12 0x01471e89 in New (space=<optimized out>) at ../../runtime/vm/object.cc:7936
#13 dart::Function::New (name=..., kind=dart::RawFunction::kSignatureFunction, is_static=<optimized out>, is_const=<optimized out>, is_abstract=<optimized out>, is_external=<optimized out>, is_native=<optimized out>, owner=..., token_pos=..., space=dart::Heap::kOld) at ../../runtime/vm/object.cc:7054
#14 0x01487f8b in dart::Function::NewSignatureFunction (owner=..., parent=..., token_pos=..., space=dart::Heap::kOld) at ../../runtime/vm/object.cc:7103
#15 0x016632f6 in dart::kernel::TypeTranslator::BuildFunctionType (this=0xf70bc720, simple=<optimized out>) at ../../runtime/vm/compiler/frontend/kernel_translation_helper.cc:2791
#16 0x01662de5 in dart::kernel::TypeTranslator::BuildTypeInternal (this=0xf70bc720) at ../../runtime/vm/compiler/frontend/kernel_translation_helper.cc:2740
#17 0x016609b6 in dart::kernel::TypeTranslator::BuildType (this=0xf70bc720) at ../../runtime/vm/compiler/frontend/kernel_translation_helper.cc:2701
#18 0x0166c024 in BuildAndVisitVariableType (this=0xf70bc628) at ../../runtime/vm/compiler/frontend/scope_builder.cc:1220
#19 dart::kernel::ScopeBuilder::AddVariableDeclarationParameter (this=0xf70bc628, pos=4, type_check_mode=dart::kernel::ScopeBuilder::kTypeCheckForNonDynamicallyInvokedMethod, attrs=...) at ../../runtime/vm/compiler/frontend/scope_builder.cc:1429
#20 0x016680ec in AddPositionalAndNamedParameters (this=<optimized out>, pos=<optimized out>, type_check_mode=dart::kernel::ScopeBuilder::kTypeCheckForNonDynamicallyInvokedMethod, attrs=...) at ../../runtime/vm/compiler/frontend/scope_builder.cc:1409
#21 dart::kernel::ScopeBuilder::BuildScopes (this=0xf70bc628) at ../../runtime/vm/compiler/frontend/scope_builder.cc:242
#22 0x014dc3a0 in dart::ParsedFunction::EnsureKernelScopes (this=0x3c75a68) at ../../runtime/vm/parser.cc:135
#23 0x0163efc7 in dart::kernel::StreamingFlowGraphBuilder::BuildGraph (this=0xf70bc880) at ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:1990
#24 0x01652ca6 in dart::kernel::FlowGraphBuilder::BuildGraph (this=0xf70bcab0) at ../../runtime/vm/compiler/frontend/kernel_to_il.cc:722
#25 0x015d1586 in dart::CallSiteInliner::TryInlining (this=0xf70bcdc0, function=..., argument_names=..., call_data=0xf70bcc98, stricter_heuristic=5) at ../../runtime/vm/compiler/backend/inliner.cc:1060
#26 0x015dc0cc in dart::CallSiteInliner::InlineStaticCalls (this=0xf70bcdc0) at ../../runtime/vm/compiler/backend/inliner.cc:1489
#27 0x015d786f in dart::CallSiteInliner::InlineCalls (this=0xf70bcdc0) at ../../runtime/vm/compiler/backend/inliner.cc:857
#28 0x015d74e3 in dart::FlowGraphInliner::Inline (this=0xf70bce50) at ../../runtime/vm/compiler/backend/inliner.cc:2351
#29 0x01619679 in dart::CompilerPass_Inlining::DoBody (this=0x17ad1c0 <dart::compiler_pass_Inlining>, state=0xf70bcf80) at ../../runtime/vm/compiler/compiler_pass.cc:282
#30 0x016190ac in dart::CompilerPass::Run (this=0x17ad1c0 <dart::compiler_pass_Inlining>, state=0xf70bcf80) at ../../runtime/vm/compiler/compiler_pass.cc:177
#31 0x01619366 in dart::CompilerPass::RunPipeline (mode=dart::CompilerPass::kJIT, pass_state=0xf70bcf80) at ../../runtime/vm/compiler/compiler_pass.cc:221
#32 0x016807dd in dart::CompileParsedFunctionHelper::Compile (this=0xf70bd2e8, pipeline=0x3d6a088) at ../../runtime/vm/compiler/jit/compiler.cc:665
#33 0x0168127b in dart::CompileFunctionHelper (pipeline=0x3d6a088, function=..., optimized=<optimized out>, osr_id=-1) at ../../runtime/vm/compiler/jit/compiler.cc:796
#34 0x01681e42 in dart::Compiler::CompileOptimizedFunction (thread=0x37bbe00, function=..., osr_id=-1) at ../../runtime/vm/compiler/jit/compiler.cc:1067
#35 0x016834c7 in dart::BackgroundCompiler::Run (this=0x378c6a0) at ../../runtime/vm/compiler/jit/compiler.cc:1482
#36 0x01683c47 in dart::BackgroundCompilerTask::Run (this=0x37820a0) at ../../runtime/vm/compiler/jit/compiler.cc:1564
```
