### ISSUE TITLE
Analyzer crashing when run against package:test 0.12.28

### ISSUE THREAD

**Issue by cbracken** [dart-lang/sdk#31442]
When running `flutter analyze` over the Flutter repo, I'm seeing a crash when analyzing `lib/src/backend/invoker.dart` from package:test v0.12.28.

Flutter is using SDK 1.25.0-dev.11.0.

```
RUNNING: cd .; bin/flutter analyze --flutter-repo
Analyzing 1311 files...
Task failed: ResolveUnitTypeNamesTask for source /home/travis/.pub-cache/hosted/pub.dartlang.org/test-0.12.28/lib/src/backend/invoker.dart
AnalysisException: Cannot compute DART_ERRORS for /home/travis/build/flutter/flutter/dev/automated_tests/flutter_test/exception_handling_test.dart
Caused by Unexpected exception while performing ResolveUnitTypeNamesTask for source /home/travis/.pub-cache/hosted/pub.dartlang.org/test-0.12.28/lib/src/backend/invoker.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:287)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:112)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:720)
#5      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:663)
#6      AnalysisDriver._analyze (package:flutter_tools/src/dart/analysis.dart:87)
#7      AnalysisDriver.analyze (package:flutter_tools/src/dart/analysis.dart:51)
#8      AnalyzeOnce.analyze (package:flutter_tools/src/commands/analyze_once.dart:154)
<asynchronous suspension>
#9      AnalyzeCommand.runCommand (package:flutter_tools/src/commands/analyze.dart:62)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     new Future.sync (dart:async/future.dart:222)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#18     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1120)
#22     _CustomZone.run (dart:async/zone.dart:1001)
#23     runZoned (dart:async/zone.dart:1467)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:43)
<asynchronous suspension>
#27     main (file:///home/travis/build/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
Caused by NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9666)
#3      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5732)
#4      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11149)
#5      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#6      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9827)
#7      UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228)
#8      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11144)
#9      FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4369)
#10     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#11     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9827)
#12     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:3011)
#13     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4364)
#14     TypeResolverVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:9528)
#15     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7081)
#16     TypeResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:9474)
#17     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1906)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#19     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2502)
#20     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#21     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9827)
#22     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#23     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#24     ResolveUnitTypeNamesTask.internalPerform (package:analyzer/src/task/dart.dart:5141)
#25     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#26     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#27     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:287)
#28     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:112)
#29     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:720)
#30     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:663)
#31     AnalysisDriver._analyze (package:flutter_tools/src/dart/analysis.dart:87)
#32     AnalysisDriver.analyze (package:flutter_tools/src/dart/analysis.dart:51)
#33     AnalyzeOnce.analyze (package:flutter_tools/src/commands/analyze_once.dart:154)
<asynchronous suspension>
#34     AnalyzeCommand.runCommand (package:flutter_tools/src/commands/analyze.dart:62)
#35     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
<asynchronous suspension>
#36     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
<asynchronous suspension>
#37     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#38     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#39     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#40     new Future.sync (dart:async/future.dart:222)
#41     CommandRunner.run (package:args/command_runner.dart:109)
#42     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#43     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#44     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#45     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#46     _rootRun (dart:async/zone.dart:1120)
#47     _CustomZone.run (dart:async/zone.dart:1001)
#48     runZoned (dart:async/zone.dart:1467)
#49     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#50     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#51     main (package:flutter_tools/executable.dart:43)
<asynchronous suspension>
#52     main (file:///home/travis/build/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#53     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:725)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:663)
#2      AnalysisDriver._analyze (package:flutter_tools/src/dart/analysis.dart:87)
#3      AnalysisDriver.analyze (package:flutter_tools/src/dart/analysis.dart:51)
#4      AnalyzeOnce.analyze (package:flutter_tools/src/commands/analyze_once.dart:154)
<asynchronous suspension>
#5      AnalyzeCommand.runCommand (package:flutter_tools/src/commands/analyze.dart:62)
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
<asynchronous suspension>
#7      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#10     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#11     new Future.sync (dart:async/future.dart:222)
#12     CommandRunner.run (package:args/command_runner.dart:109)
#13     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#14     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#15     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#16     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     runZoned (dart:async/zone.dart:1467)
#20     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#21     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:43)
<asynchronous suspension>
#23     main (file:///home/travis/build/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by matanlurey** [comment]
pkg/test is using the new generic function syntax now, which crashes in <2.0.0-dev

**Comment by pq** [comment]
I think this is the same as reported here: https://github.com/dart-lang/sdk/issues/31357.

**Comment by matanlurey** [comment]
I filed an issue for pkg/test here, which is the culprit:
https://github.com/dart-lang/test/issues/725

**Comment by bwilkerson** [comment]
@MichaelRFairhurst Is this something you would feel comfortable looking into?

**Comment by devoncarew** [comment]
@cbracken, can you bump the sdk to a later version and re-test? If the crash has been fixed post `1.25.0-dev.11.0` - which is fairly old at this point - that rolling to a new sdk (https://github.com/flutter/flutter/pull/13180) should address this issue.

**Comment by MichaelRFairhurst** [comment]
I can definitely look into it; first thing is to try on the newer version as Devon said. @cbracken do you have time or do you want me to do this for you? (Side note: not sure if bumping the flutter SDK requires special steps)

**Comment by MichaelRFairhurst** [comment]
Devon just set me up with the steps to bump. Will hopefully repro and confirm (or not) in a second whether this is solved in a newer version...

**Comment by cbracken** [comment]
@MichaelRFairhurst FYI sent out a tentative SDK roll since it's been quite a while in any case: flutter/flutter#13226

I haven't yet tried re-bumping packages with this.

**Comment by devoncarew** [comment]
@cbracken, so we know, is `flutter update-packages --force-upgrade` how we would go about bumping to the latest package versions?

**Comment by cbracken** [comment]
@devoncarew yep, that's exactly the command you want.

**Comment by MichaelRFairhurst** [comment]
Looks like this was fixed as of 2.0.0-dev.7.0. (was finally able to repro the crash to bisect the fix point)

**Comment by cbracken** [comment]
@MichaelRFairhurst thanks for bisecting this. There's WIP (#13223) from @leafpetersen to resolve the framework issues blocking the roll to 2.0.0-dev. Once that's in we should be set it sounds like.

**Comment by matanlurey** [comment]
I think you linked to the wrong bug @cbracken

**Comment by leafpetersen** [comment]
I'm working on a PR here:  https://github.com/flutter/flutter/pull/13223 .

**Comment by bwilkerson** [comment]
I'm guessing that this issue has been resolved. If not, please re-open it.
