### ISSUE TITLE
gen_snapshot fails to produce dependencies file when running from kernel

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#31502]
Flutter running on the Flutter engine built with the tip of the dart-sdk issues an error:

```
flutter build aot -v --release --preview-dart-2 --local-engine-src-path [...skipped...]/engine/src --local-engine android_release
```

```
[ +412 ms] [...skipped...]engine/src/out/android_release/clang_x86/gen_snapshot --await_is_keyword --vm_snapshot_data=build/aot/vm_snapshot_data --isolate_snapshot_data=build/aot/isolate_snapshot_data --packages=.packages --url_mapping=dart:ui,../../bin/cache/pkg/sky_engine/lib/ui/ui.dart --url_mapping=dart:vmservice_io,../../bin/cache/pkg/sky_engine/sdk_ext/vmservice_io.dart --print_snapshot_sizes --dependencies=build/aot/snapshot.d --causal_async_stacks --embedder_entry_points_manifest=[...skipped...]/engine/src/flutter/runtime/dart_vm_entry_points.txt --embedder_entry_points_manifest=[...skipped...]/engine/src/third_party/dart/runtime/bin/dart_io_entries.txt --snapshot_kind=app-aot-blobs --vm_snapshot_instructions=build/aot/vm_snapshot_instr --isolate_snapshot_instructions=build/aot/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division [...skipped...]/flutter/examples/flutter_gallery/lib/main.dart.dill
[+9373 ms] VMIsolate(CodeSize): 4607
                   Isolate(CodeSize): 2796113
                   ReadOnlyData(CodeSize): 2239560
                   Instructions(CodeSize): 6396464
                   Total(CodeSize): 11436744
[   +7 ms] Error during AOT snapshot fingerprinting: FileSystemException: Cannot open file, path = 'build/aot/snapshot.d' (OS Error: No such file or directory, errno = 2)
           #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:337)
           #1      _rootRunUnary (dart:async/zone.dart:1128)
           #2      _CustomZone.runUnary (dart:async/zone.dart:1012)
           #3      _FutureListener.handleValue (dart:async/future_impl.dart:129)
           #4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
           #5      _Future._propagateToListeners (dart:async/future_impl.dart:665)
           #6      _Future._completeWithValue (dart:async/future_impl.dart:478)
           #7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
           #8      _rootRun (dart:async/zone.dart:1120)
           #9      _CustomZone.run (dart:async/zone.dart:1001)
           #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:928)
           #11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
           #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
           #13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
           #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

Indeed, gen_snapshot command does not produce 'build/aot/snapshot.d' file specified in the --dependencies argument.

**Comment by alexmarkov** [comment]
/cc @sivachandra @rmacnak-google 

It looks like the commit https://github.com/dart-lang/sdk/commit/124d592f595038da8c424e7bfd790bfa9d7a7583 have broken this as dependencies are no longer initialized at https://github.com/dart-lang/sdk/commit/124d592f595038da8c424e7bfd790bfa9d7a7583#diff-61eae2a81ed2de47c7a63189ecdd8811R1622 due to early return at https://github.com/dart-lang/sdk/commit/124d592f595038da8c424e7bfd790bfa9d7a7583#diff-61eae2a81ed2de47c7a63189ecdd8811R1562.

**Comment by mraleph** [comment]
I would like to suggest that before any further refactoring on `gen_snapshot`,  we should make sure that we have behavioral tests for all `gen_snapshot` functionality that is being used by Flutter.

**Comment by sivachandra** [comment]
I agree that we should have tests for gen_snapshot. But, considering you marked this bug as P0, I think we can land the fix I propose here: https://dart-review.googlesource.com/c/sdk/+/25510

**Comment by sivachandra** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/4a19ab4e22373f5e4987546d7b95bd34da390eca
