### ISSUE TITLE
Analyser crash when renaming a symbol (field of a class)

### ISSUE THREAD

**Issue by NicolasJacob** [dart-lang/sdk#31522]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing
Rename a symbol (field of a class)

### Request

While responding to request: `edit.getRefactoring`

### Versions

- Dart SDK 1.25.0-dev.11.0
- Visual Studio Code 1.18.1
- Dart Code 2.5.1

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=2.5.1
```

### Exception

NoSuchMethodError: The method 'intersects' was called on null.
Receiver: null
Tried calling: intersects(Instance of 'SourceRange')

```text
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      _ClassMemberValidator._getShadowingLocalElement (package:analysis_server/src/services/refactoring/rename_class_member.dart:273)
<asynchronous suspension>
#3      _ClassMemberValidator.validate (package:analysis_server/src/services/refactoring/rename_class_member.dart:201)
<asynchronous suspension>
#4      RenameClassMemberRefactoringImpl.checkFinalConditions (package:analysis_server/src/services/refactoring/rename_class_member.dart:61)
#5      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:762)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1120)
#7      _CustomZone.run (dart:async/zone.dart:1001)
#8      _CustomZone.runGuarded (dart:async/zone.dart:901)
#9      runZoned (dart:async/zone.dart:1465)
#10     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:731)
#11     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:574)
#12     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:357)
#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:682)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#15     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:678)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     _CustomZone.runGuarded (dart:async/zone.dart:901)
#19     runZoned (dart:async/zone.dart:1465)
#20     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:677)
#21     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#23     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#24     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#25     _rootRunUnary (dart:async/zone.dart:1128)
#26     _CustomZone.runUnary (dart:async/zone.dart:1012)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#32     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#33     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#34     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#35     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#37     _rootRunUnary (dart:async/zone.dart:1128)
#38     _CustomZone.runUnary (dart:async/zone.dart:1012)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#42     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#43     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#44     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#45     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#46     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#47     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#48     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#50     _rootRunUnary (dart:async/zone.dart:1128)
#51     _CustomZone.runUnary (dart:async/zone.dart:1012)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#55     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#56     _StreamController._add (dart:async/stream_controller.dart:667)
#57     _StreamController.add (dart:async/stream_controller.dart:613)
#58     _Socket._onData (dart:io-patch/socket_patch.dart:1643)
#59     _rootRunUnary (dart:async/zone.dart:1132)
#60     _CustomZone.runUnary (dart:async/zone.dart:1012)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#64     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#65     _StreamController._add (dart:async/stream_controller.dart:667)
#66     _StreamController.add (dart:async/stream_controller.dart:613)
#67     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
#68     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#69     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#70     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#71     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#72     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/home/nicolas/project/pr",
        "explicitFileCount": 9,
        "implicitFileCount": 611,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
