### ISSUE TITLE
Webstorm analysis error

### ISSUE THREAD

**Issue by nolram88** [dart-lang/sdk#31525]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-172.4343.25`
- `1.24.2`
- `WS-172.4343.25, JRE 1.8.0_152-release-915-b12x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.1 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/sk/zpvzvqxs15b899txd218469w0000gn/T/report.txt

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Analysis failed: /Users/marlonmckinnie/dev/angular_components_example/web/main.dart context: exception_20171203_123200_333
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1096)
#1      ParameterElementForLink.type (package:analyzer/src/summary/link.dart:4204)
#2      FunctionTypeImpl.parameters (package:analyzer/src/dart/element/type.dart:594)
#3      InstanceMemberInferrer._inferParameterCovariance.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:458)
#4      Object

**Comment by devoncarew** [comment]
assumed stale
