### ISSUE TITLE
DDC crashes on generic function typed loop variable.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#31540]
Example: https://dartpad.dartlang.org/e5f8ceaa049ba2b24cecaf7c5d5b4c27
```dart
import "dart:async";
FutureOr<T> future<T>(T value) async => value;
FutureOr<T> id<T>(T value) => value;
main() async {
  for (final FutureOr<T> Function<T>(T) func in <Function>[future, id]) {
    print(await func(42));
  }
}
```
The type is needed because the list cannot have a generic type as type argument (which is separately annoying).
If I remove the `FutureOr<T> Function<T>(T)` type, the program runs.

The error report says:

> We're sorry, you've found a bug in our compiler.
> You can report this bug at:
>     https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
> Please include the information below in your report, along with
> any other information that may help us track it down. Thanks!
>     dartdevc arguments: --dart-sdk=../out/ReleaseX64/dart-sdk --strong cddc.dart -o.
>     dart --version: 2.0.0-edge.b0160af36a97f6b378531677f948c55c8f8b8a67 (Thu Nov 30 11:07:41 2017 +0000) on "linux_x64"
```
AnalysisException: Cannot compute LIBRARY_ELEMENT for ./cddc.dart
Caused by Unexpected exception while performing ResolveUnitTypeNamesTask for source ./cddc.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:287)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:112)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:719)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:687)
#6      ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:183)
#7      _compile (package:dev_compiler/src/analyzer/command.dart:187)
#8      compile (package:dev_compiler/src/analyzer/command.dart:57)
#9      main (../sdk/pkg/dev_compiler/bin/dartdevc.dart:27)
<asynchronous suspension>
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

Caused by NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9630)
#2      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5729)
#3      DeclaredIdentifierImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3347)
#4      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#5      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9791)
#6      UnifyingAstVisitor.visitDeclaredIdentifier (package:analyzer/dart/ast/visitor.dart:2971)
#7      ScopedVisitor.visitDeclaredIdentifier (package:analyzer/src/generated/resolver.dart:7112)
#8      TypeResolverVisitor.visitDeclaredIdentifier (package:analyzer/src/generated/resolver.dart:9545)
#9      DeclaredIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:3342)
#10     ScopedVisitor.visitForEachStatementInScope (package:analyzer/src/generated/resolver.dart:7191)
#11     ScopedVisitor.visitForEachStatement (package:analyzer/src/generated/resolver.dart:7169)
#12     ForEachStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4672)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7987)
#14     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1346)
#15     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#16     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9791)
#17     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#18     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:6959)
#19     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1342)
#20     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1291)
#21     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#22     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9791)
#23     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#24     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:6971)
#25     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1287)
#26     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5322)
#27     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#28     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9791)
#29     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#30     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7274)
#31     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5316)
#32     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5167)
#33     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#34     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9791)
#35     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026)
#36     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:7267)
#37     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7259)
#38     TypeResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:9589)
#39     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5160)
#40     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7987)
#41     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2502)
#42     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#43     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9791)
#44     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#45     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#46     ResolveUnitTypeNamesTask.internalPerform (package:analyzer/src/task/dart.dart:5125)
#47     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#48     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#49     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:287)
#50     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:112)
#51     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:719)
#52     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:687)
#53     ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:183)
#54     _compile (package:dev_compiler/src/analyzer/command.dart:187)
#55     compile (package:dev_compiler/src/analyzer/command.dart:57)
#56     main (../sdk/pkg/dev_compiler/bin/dartdevc.dart:27)
<asynchronous suspension>
#57     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:724)
#1      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:687)
#2      ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:183)
#3      _compile (package:dev_compiler/src/analyzer/command.dart:187)
#4      compile (package:dev_compiler/src/analyzer/command.dart:57)
#5      main (../sdk/pkg/dev_compiler/bin/dartdevc.dart:27)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by lrhn** [comment]
The analyzer crashes with the same error, so adding area-analyzer as well.

**Comment by MichaelRFairhurst** [comment]
This has been fixed with https://dart-review.googlesource.com/c/sdk/+/32447
