### ISSUE TITLE
io https server crashes with SocketException after a while

### ISSUE THREAD

**Issue by welopino** [dart-lang/sdk#31558]
This little https server script runs for a while. 

```
import 'dart:io';
import 'package:http_server/http_server.dart';

main() async {
   
   
  //files
  var staticFiles = new VirtualDirectory(".....");
  staticFiles.allowDirectoryListing = true;
  staticFiles.directoryHandler = (dir, request) {
    var indexUri = new Uri.file(dir.path).resolve('index.html');
    staticFiles.serveFile(new File(indexUri.toFilePath()), request);
  };

  //https
  SecurityContext context = new SecurityContext();
  var chain =   Platform.script.resolve('certificate+intermediateCertificate.pem').toFilePath();
  var key =    Platform.script.resolve(''certificate+intermediateCertificate.pem').toFilePath();
  context.useCertificateChain(chain);
  context.usePrivateKey(key, password: '...');
  HttpServer
    .bindSecure(InternetAddress.ANY_IP_V6, 443, context)
    .then((server) {
      server.forEach(staticFiles.serveRequest);
    }
  );
}
```
After a while it crashes, and I get this:

```
Unhandled exception:
SocketException: OS Error: Connection reset by peer, errno = 104, address = ::, port = 443
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1108)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

On the same Ubuntu server a java based Vert.x sever runs a https service without problems.

**Comment by SandPod** [comment]
Any updates on this?

Our users are experiencing similar issues through the Serverpod framework.

There are multiple dart issues tracking what seems to be the same issue, I would suggest consolidating them into a single issue:
- https://github.com/dart-lang/sdk/issues/27440
- https://github.com/dart-lang/sdk/issues/47247
- https://github.com/dart-lang/sdk/issues/55776


This seems to have reached a possible solution to the issue in Dart code, could this be missing in the library code as well? https://github.com/dart-lang/sdk/issues/25518
