### ISSUE TITLE
exception when running the analysis server benchmarks with --preview-dart-2

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31554]
Currently https://dart-review.googlesource.com/c/sdk/+/26461 fails, but we should eventually restore the test.

@devoncarew

**Comment by devoncarew** [comment]
This is the exception:

```
  Analysis failed: /Users/devoncarew/projects/dart-lang/dart-sdk/sdk/pkg/meta/lib/meta.dart context: exception_20171205_161923_021
  Bad state: Some types were not consumed, starting at offset -1
  #0      ResolutionApplier.checkDone (package:analyzer/src/fasta/resolution_applier.dart:72:7)
  #1      LibraryAnalyzer._resolveFile2 (package:analyzer/src/dart/analysis/library_analyzer.dart:734:21)
  #2      LibraryAnalyzer._analyze2.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:208:9)
  #3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
  #4      LibraryAnalyzer._analyze2 (package:analyzer/src/dart/analysis/library_analyzer.dart:207:13)
  <asynchronous suspension>
  #5      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:95:22)
  <asynchronous suspension>
  #6      _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217:21)
  <asynchronous suspension>
  #7      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:93:43)
  <asynchronous suspension>
  #8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1216:71)
  <asynchronous suspension>
  #9      PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
  <asynchronous suspension>
  #10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183:20)
  <asynchronous suspension>
  #11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1010:39)
  <asynchronous suspension>
  #12     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1887:24)
  <asynchronous suspension>
  #13     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1830:5)
```

**Comment by devoncarew** [comment]
The benchmark test now passes. The full benchmark (`dart pkg/analysis_server/benchmark/benchmarks.dart run --repeat=1 --preview-dart-2 analysis-server`) fails with a separate exception:

```
Class '_CompileTimeError' not found in library 'dart:core'
#0      _ClassTable._getClassIndex (package:kernel/library_index.dart:161:7)
#1      _ClassTable.getMember (package:kernel/library_index.dart:175:12)
#2      LibraryIndex.getMember (package:kernel/library_index.dart:101:38)
#3      CoreTypes.compileTimeErrorDefaultConstructor (package:kernel/core_types.dart:391:16)
#4      Target.buildCompileTimeError (package:kernel/target/targets.dart:195:19)
#5      SourceLoader.buildCompileTimeError (package:front_end/src/fasta/source/source_loader.dart:659:33)
#6      BodyBuilder.buildCompileTimeError (package:front_end/src/fasta/kernel/body_builder.dart:3292:28)
#7      BodyBuilder.wrapInCompileTimeError (package:front_end/src/fasta/kernel/body_builder.dart:3301:9)
#8      TypeInferrerImpl.checkAssignability (package:front_end/src/fasta/type_inference/type_inferrer.dart:403:34)
#9      TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:979:9)
#10     TypeInferrerImpl.inferMethodInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1190:24)
#11     ShadowMethodInvocation._inferExpression (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1429:21)
#12     ShadowTypeInferrer.inferExpression (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:2187:25)
#13     ShadowExpressionStatement._inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:674:14)
#14     ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:2230:24)
#15     ShadowBlock._inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:188:16)
```

**Comment by scheglov** [comment]
With https://dart-review.googlesource.com/c/sdk/+/29000 we will be able to go a bit further.

**Comment by devoncarew** [comment]
We're further now - updated with the current exception:

```
Unhandled exception:
Analysis failed: /Users/.../pkg/analysis_server/benchmark/benchmarks.dart context: exception_20171212_214227_895
Bad state: (Null) null
#0      _ResolutionApplierContext.enterLocalFunction (package:analyzer/src/dart/analysis/library_analyzer.dart:1153:7)
#1      ResolutionApplier.visitFunctionExpression (package:analyzer/src/fasta/resolution_applier.dart:254:18)
#2      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5316:49)
#3      ResolutionApplier._applyResolutionToArguments (package:analyzer/src/fasta/resolution_applier.dart:538:29)
#4      ResolutionApplier.visitMethodInvocation (package:analyzer/src/fasta/resolution_applier.dart:365:5)
#5      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7595:49)
#6      ResolutionApplier.visitVariableDeclaration (package:analyzer/src/fasta/resolution_applier.dart:507:23)
#7      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11058:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7987:20)
#9      ResolutionApplier.visitVariableDeclarationList (package:analyzer/src/fasta/resolution_applier.dart:523:22)
#10     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11154:15)
#11     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11215:20)
#12     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431:10)
#13     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494:39)
#14     GeneralizingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:566:7)
#15     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11211:15)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7987:20)
#17     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1346:17)
#18     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431:10)
#19     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494:39)
#20     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:184:31)
#21     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1342:49)
#22     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1291:13)
#23     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431:10)
#24     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314:45)
#25     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:187:55)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1287:49)
#27     LibraryAnalyzer._resolveFile2 (package:analyzer/src/dart/analysis/library_analyzer.dart:763:25)
#28     LibraryAnalyzer._analyze2.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:208:9)
#29     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
#30     LibraryAnalyzer._analyze2 (package:analyzer/src/dart/analysis/library_analyzer.dart:207:13)
<asynchronous suspension>
```

**Comment by scheglov** [comment]
This should be fixed in https://dart-review.googlesource.com/c/sdk/+/29002

And the next (yes, we have a next crash waiting for us :-)) is import prefixes resolution https://dart-review.googlesource.com/c/sdk/+/28541, but it might take a while to get it approved :-(

**Comment by devoncarew** [comment]
:) thanks for all the fixes

```
Unhandled exception:
Analysis failed: /Users/.../dart-sdk/sdk/pkg/analysis_server/benchmark/benchmarks.dart context: exception_20171213_080055_754
Bad state: Expected element reference for analyzer offset 3308; got one for kernel offset 3313
#0      ValidatingResolutionApplier._getReferenceFor (package:analyzer/src/fasta/resolution_applier.dart:868:7)
#1      ResolutionApplier.visitSimpleIdentifier (package:analyzer/src/fasta/resolution_applier.dart:440:26)
#2      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9350:49)
#3      ResolutionApplier.visitMethodInvocation (package:analyzer/src/fasta/resolution_applier.dart:345:18)
#4      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7595:49)
#5      ResolutionApplier.visitAssignmentExpression (package:analyzer/src/fasta/resolution_applier.dart:81:24)
#6      AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:906:49)
#7      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4231:18)
#8      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431:10)
#9      GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494:39)
#10     GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:291:59)
```

**Comment by devoncarew** [comment]
```
Unhandled exception:
Analysis failed: /Users/devoncarew/projects/dart-lang/dart-sdk/sdk/pkg/analysis_server/benchmark/perf/benchmark_angular.dart context: exception_20171231_131148_121
UnimplementedError: type: (FunctionTypeImpl) (String) → dynamic
#0      _ExprBuilder._buildType (package:analyzer/src/kernel/resynthesize.dart:758:5)
#1      _ExprBuilder._buildTypeArgumentList (package:analyzer/src/kernel/resynthesize.dart:766:39)
#2      _ExprBuilder._build (package:analyzer/src/kernel/resynthesize.dart:547:11)
#3      _ExprBuilder.build (package:analyzer/src/kernel/resynthesize.dart:447:14)
#4      _KernelUnitResynthesizerContextImpl.getExpression (package:analyzer/src/kernel/resynthesize.dart:1119:44)
#5      TopLevelVariableElementImpl&ConstVariableElement.constantInitializer (package:analyzer/src/dart/element/element.dart:2642:14)
#6      ConstantEvaluationEngine.computeDependencies (package:analyzer/src/dart/constant/evaluation.dart:278:41)
#7      _ConstantNode.computeDependencies (package:analyzer/src/dart/analysis/library_analyzer.dart:963:22)
#8      Node.getDependencies (package:front_end/src/dependency_walker.dart:42:40)
#9      DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:102:40)
#10     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:168:18)
#11     LibraryAnalyzer._computeConstants (package:analyzer/src/dart/analysis/library_analyzer.dart:295:47)
#12     LibraryAnalyzer._analyze2 (package:analyzer/src/dart/analysis/library_analyzer.dart:226:7)
<asynchronous suspension>
#13     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:97:22)
<asynchronous suspension>
#14     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217:21)
<asynchronous suspension>
#15     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:95:43)
<asynchronous suspension>
#16     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1216:71)
```

**Comment by bwilkerson** [comment]
What is the current state of this issue? I know that a lot of the preview-dart-2 issues in analyzer and server have been fixed.

**Comment by devoncarew** [comment]
Closing and will re-open as a new issue.
