### ISSUE TITLE
DDK cannot compile the SDK yet

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31575]
DDK is currently failing here:

```
[vsm-macbookpro2.roam.corp.google.com:/Users/vsm/dart/sdk/pkg/dev_compiler] [vsm-macbookpro2.roam.corp.google.com:/Users/vsm/dart/sdk/pkg/dev_compiler] ./tool/kernel_sdk.dart -g
Unhandled exception:
Interpolated value #0 is not a selector: childNodes
#0      InstantiatorGeneratorVisitor.error (package:dev_compiler/src/js_ast/template.dart:155:5)
#1      InstantiatorGeneratorVisitor.visitInterpolatedSelector.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:246:7)
#2      InstantiatorGeneratorVisitor.visitAccess.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:646:65)
#3      InstantiatorGeneratorVisitor.visitReturn.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:465:36)
#4      InstantiatorGeneratorVisitor.visitBlock.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:341:25)
#5      Template.instantiate (package:dev_compiler/src/js_ast/template.dart:107:26)
#6      JsBuilder.statement (package:dev_compiler/src/js_ast/builder.dart:221:21)
#7      ProgramCompiler._emitNativeFieldAccessors (package:dev_compiler/src/kernel/compiler.dart:1882:32)
#8      ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:1529:26)
#9      ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:494:21)
#10     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:450:22)
#11     ProgramCompiler._declareBeforeUse (package:dev_compiler/src/kernel/compiler.dart:469:59)
#12     ProgramCompiler.visitInterfaceType (package:dev_compiler/src/kernel/compiler.dart:2425:5)
#13     InterfaceType.accept (package:kernel/ast.dart:4701:34)
#14     ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:2396:50)
#15     ProgramCompiler.visitIsExpression (package:dev_compiler/src/kernel/compiler.dart:4519:22)
#16     IsExpression.accept (package:kernel/ast.dart:3026:36)
#17     ProgramCompiler._visitAndMarkExpression (package:dev_compiler/src/kernel/compiler.dart:2994:31)
#18     ProgramCompiler.visitReturnStatement (package:dev_compiler/src/kernel/compiler.dart:3335:12)
#19     ReturnStatement.accept (package:kernel/ast.dart:4072:35)
#20     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:2935:21)
#21     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#22     ListIterable.toList (dart:_internal/iterable.dart:218)
#23     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3011:57)
#24     Block.accept (package:kernel/ast.dart:3685:35)
#25     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:2935:21)
#26     ProgramCompiler._emitFunctionBody (package:dev_compiler/src/kernel/compiler.dart:2785:18)
#27     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:2616:11)
#28     ProgramCompiler._emitLibraryFunction (package:dev_compiler/src/kernel/compiler.dart:2354:14)
#29     MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#30     new List.from (dart:core-patch/array_patch.dart:46)
#31     Iterable.toList (dart:core/iterable.dart:347)
#32     ProgramCompiler._emitLibraryProcedures (package:dev_compiler/src/kernel/compiler.dart:2332:10)
#33     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:398:7)
#34     Iterable.forEach (dart:core/iterable.dart:226)
#35     ProgramCompiler.emitProgram (package:dev_compiler/src/kernel/compiler.dart:282:15)
#36     compileToJSModule (package:dev_compiler/src/kernel/command.dart:155:19)
#37     main (file:///Users/vsm/dart/sdk/pkg/dev_compiler/tool/kernel_sdk.dart:51:20)
<asynchronous suspension>
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by vsmenon** [comment]
@kmillikin - tracking issue for sdk.  Is someone in AAR looking at this?

**Comment by jmesserly** [comment]
Taking a look. InstantiatorGeneratorVisitor errors usually means DDC built the JS AST incorrectly (the number of holes does not match the number of supplied values, e.g. `js.call('#.#', [jsExpr])` ... it would need two expressions for that to be valid)

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/32504 fixes this issue and a couple of others
