### ISSUE TITLE
IOSink works incorrectly after its closing.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#31570]
Dart API Specification reads about the io/IOSink class:
> It is an error to add data to the IOSink after the sink is closed.

So, I expect that if I try to add something to the sink after the its is closed, some Error should be thrown.

Here is a simple code example:
```
import "dart:async";
import "dart:io";

class MyStreamConsumer<List> extends StreamConsumer<List> {
  MyStreamConsumer() {}
  Future<dynamic> addStream(Stream<List> stream) {return new Future(() => "OK");}
  Future close() {return new Future(() => "CLOSED");}
}

main() async {
  StreamConsumer consumer = new MyStreamConsumer();
  IOSink sink = new IOSink(consumer);
  await sink.close();
  try {
    sink.writeln();
    print("FAILED");
  } catch(e) {
    print("OK");
  };
}
```

Here is a sample output:

```
$> dart -c test.dart
Observatory listening on http://127.0.0.1:60569/
StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:io/io_sink.dart:160)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:165)
#2      _IOSinkImpl.write (dart:io/io_sink.dart:302)
#3      _IOSinkImpl.writeln (dart:io/io_sink.dart:323)

FAILED

#4      main (file:///D:/DART/sdk/tests/co19/LibTest/io/IOSink/test.dart:15:10)
<asynchronous suspension>
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
Actually, Error is not actually thrown here, only error message is printed.
I've tried to debug it and here is a dart source code (lib/io/IOSink.dart):
 ```
void _reportClosedSink() {
    // TODO(29554): this is very brittle and depends on the layout of the
    // stderr class.
    if (this == stderr._sink) {
      // We can't report on stderr anymore (as we would otherwise
      // have an infinite recursion.
      throw new StateError("Stderr is closed.");
    }
    // TODO(29554): throw a StateError, and don't just report the problem.
    stderr.writeln("StreamSink is closed and adding to it is an error.");
    stderr.writeln("  See http://dartbug.com/29554.");
    stderr.writeln(StackTrace.current);
  }
```

**Comment by iarkh** [comment]
Please sorry - this is a duplicate of #29554.
