### ISSUE TITLE
Analysis server exception for generic types

### ISSUE THREAD

**Issue by GRouslan** [dart-lang/sdk#31598]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

In Flutter app. After adding some code:

```
abstract class RDispatchable<T extends RResult<T, P>, P>{

  static Map<Type, PublishSubject> _subjects = {};

  void dispatch() {
    _getSubject<T>(this).add(this);
  }

  PublishSubject<T> get subject => _getSubject<T>(this);

  static PublishSubject<S> _getSubject<S extends RResult<S, G>, G>(S object) {
    PublishSubject<S> subject =
    _subjects[object.runtimeType];
    if (subject == null) {
      subject = new PublishSubject<S>();
      _subjects[object.runtimeType] = subject;
    }
    return subject;
  }

  Observable<T> get observable => subject.observable;
}

abstract class RResult<T extends RResult<T, P>, P> extends RDispatchable<T, P>{
  REnvelope newEnvelope(RState oldState);

  RResult(this.payload);

  final P payload;

  @override
  String toString() {
    return '${this.runtimeType} ${this.payload}';
  }

}
```
rxdart library is used.

### Versions

- Dart SDK 1.25.0-dev.11.0
- Visual Studio Code 1.18.1
- Dart Code 2.4.2

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=2.4.2
```

### Exception

Analysis failed: /.../model.dart context: exception_20171210_131845_129

```text
Invalid argument(s): argumentTypes.length (1) != parameterTypes.length (2)
#0      InterfaceTypeImpl.substitute2 (package:analyzer/src/dart/element/type.dart:2042)
#1      ErrorVerifier._checkTypeArguments (package:analyzer/src/generated/error_verifier.dart:6267)
#2      ErrorVerifier.visitMethodInvocation (package:analyzer/src/generated/error_verifier.dart:1001)
#3      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7598)
#4      MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7602)
#5      RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1013)
#6      ErrorVerifier.visitMethodInvocation (package:analyzer/src/generated/error_verifier.dart:1003)
#7      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7598)
#8      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4228)
#9      RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:815)
#10     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4224)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#12     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1346)
#13     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:647)
#14     ErrorVerifier.visitBlock (package:analyzer/src/generated/error_verifier.dart:397)
#15     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1342)
#16     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1291)
#17     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:653)
#18     ErrorVerifier.visitBlockFunctionBody (package:analyzer/src/generated/error_verifier.dart:416)
#19     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1287)
#20     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7486)
#21     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1007)
#22     ErrorVerifier.visitMethodDeclaration (package:analyzer/src/generated/error_verifier.dart:983)
#23     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7477)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#25     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1974)
#26     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:683)
#27     ErrorVerifier.visitClassDeclaration (package:analyzer/src/generated/error_verifier.dart:481)
#28     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1906)
#29     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#30     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2502)
#31     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#32     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:540)
#33     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#34     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:305)
#35     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:104)
#36     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#37     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:103)
#38     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#39     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:102)
#40     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:64)
#41     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#42     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:63)
#43     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1075)
#44     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#45     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1063)
#46     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:920)
<asynchronous suspension>
#47     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1615)
<asynchronous suspension>
#48     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1558)
#49     new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#50     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#51     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#52     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:434)
#53     _rootRun (dart:async/zone.dart:1120)
#54     _CustomZone.run (dart:async/zone.dart:1001)
#55     runZoned (dart:async/zone.dart:1467)
#56     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:473)
#57     Driver.start (package:analysis_server/src/server/driver.dart:433)
#58     main (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#59     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "...",
        "explicitFileCount": 67,
        "implicitFileCount": 1535,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by natebosch** [comment]
We won't be able to repro analyzer stack traces from very old versions of the analyzer. If you see this problem with the latest SDK please file a new issue.
