### ISSUE TITLE
Process.run() issue on Windows for wrong path on dart 1.2x

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#31611]
If, on Windows, file path started with '/' char, then this process can be successfuly run on Dart 2.0 but produces an error on Dart 1.2x. Example is below

```dart
import "dart:io";

main() async {
  String executable = Platform.resolvedExecutable;
  String eScript = '/D:/DART/sdk/tests/co19/LibTest/io/Process/start_A01_t01_lib.dart';
  await Process.run(executable, [eScript]).then((ProcessResult results) {
    print(results.stderr);
  });
  print("DONE");
}
```
The program above works on Dart 2.0 but fails on Dart 1.24 with the following error

```
Unhandled exception:
Invalid argument(s): Illegal character in path
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1695)
#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1784)
#2      new _Uri.file (dart:core/uri.dart:1663)
#3      _Platform._nativeScript= (dart:io-patch/platform_patch.dart:45)
```

For Windows, path '/D:/...' is wrong, but, for example, `Platform.script.path` on Windows returns path in this format. See #31610

**Comment by whesse** [comment]
I think this should fail on Dart 2.0 as well, so the error is in the opposite direction.

In the issue about getting a script path on Windows, #31610, the problem is that we don't want the URI.path, but we want a native file path from a file:// URI, so we should use URI.toFilePath().

I will keep this issue open, because I think it may be an error that Process.run accepts a windows path starting with / in dart 2.0.
