### ISSUE TITLE
Bad stack trace with readAsString when the content is not utf-8

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#31619]
Where `silly.png` is a png – or other, non-UTF8 file.

```dart
import 'dart:io';

main(List<String> arguments) async {
  final file = new File('silly.png');
  try {
    print("sync");
    print(file.readAsStringSync());
  } catch (e, stack) {
    print(e);
    print(stack);
  }

  try {
    print("async");
    print(await file.readAsString());
  } catch (e, stack) {
    print(e);
    print(stack);
  }
}
```

Output – notice in the 2nd case there is no reference to the call site in `main.dart` (where there is in the sync case.

```
sync
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'silly.png'
#0      _File._tryDecode (dart:io/file_impl.dart:558)
#1      _File.readAsStringSync (dart:io/file_impl.dart:567)
#2      main (file:///Users/kevmoo/source/github/_testHarness/bin/main.dart:10:16)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

async
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'silly.png'
#0      _File._tryDecode (dart:io/file_impl.dart:558)
#1      _File.readAsString.<anonymous closure> (dart:io/file_impl.dart:564)
#2      _RootZone.runUnary (dart:async/zone.dart:1381)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:662)
#6      _Future._completeWithValue (dart:async/future_impl.dart:477)
#7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:111)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
```

**Comment by kevmoo** [comment]
On Dart VM version: 2.0.0-dev.10.0

**Comment by kevmoo** [comment]
CC @rmacnak-google @zanderso

**Comment by lrhn** [comment]
This is expected behavior for an asynchronous program, so I'm not sure fixing this particular case is worth it.

The asynchronous `await` means that the stack frames from main to the call of `file.readAsString` is no more. They have ceased to exist. We cannot capture what is not there, so what you get is the stack trace from the event loop to the currently executing code - the *entire* available stack trace at the point where there error happens.

The solution, as committed above, is to capture the stack trace preemptively. That's a memory allocation that might never be needed, and it only handles this one particular function. It is not a solution that generalizes. On the other hand, the operation being performed here (reading from disk) is probably so much more expensive in every way that the stack copy disappears in comparison, so I expect the harm to be minimal.
