### ISSUE TITLE
Uri.queryParameters crashes with a weird URI

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#31621]
```dart
main(List<String> arguments) {
  var string = r'''https://pub.dartlang.org/packages?%FF%FE%3Cscript%3Ealert%28313%29%3C%2Fscript%3E=1&q=&page=2''';
  var url = Uri.parse(string);
  print(url.queryParameters);
}
```

I'd expect the original parse to fail. Or to not hit this issue.

```
Unhandled exception:
FormatException: Bad UTF-8 encoding 0xff (at offset 0)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:574)
#1      Utf8Decoder.convert (dart:convert/utf.dart:350)
#2      Utf8Codec.decode (dart:convert/utf.dart:72)
#3      _Uri._uriDecode (dart:core/uri.dart:2833)
#4      Uri.decodeQueryComponent (dart:core/uri.dart:1106)
#5      Uri.splitQueryString.<anonymous closure> (dart:core/uri.dart:1159)
#6      Object&ListMixin.fold (dart:collection/list.dart:200)
#7      Uri.splitQueryString (dart:core/uri.dart:1150)
#8      _Uri.queryParameters (dart:core/uri.dart:1896)
#9      main (file:///Users/kevmoo/source/github/_testHarness/bin/main.dart:9:13)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

**Comment by kevmoo** [comment]
Dart VM version: 2.0.0-dev.10.0

**Comment by kevmoo** [comment]
CC @lrhn

**Comment by a871031791** [comment]
Question is solved?How to sloved this question,Please let me know,Thanks!

**Comment by lrhn** [comment]
The URI is perfeclty valid URI syntax, so the parsing succeeds.
Accessing the queryParameters as a `String` makes the class attempt to decode the query as UTF-8. That fails because it isn't UTF-8.

Annoyingly, there is no way to access the query-part of the URI without attempting to decode as UTF-8.
We should add some functionality to that effect, or give access to the query as *bytes*.

We had hoped to change the `Uri` class as part of Dart 2, but ran out of resources before getting there, but we still hope to do so in the future.

**Comment by franklinyow** [comment]
@kevmoo @lrhn 
Please re-evaluate this and do one of the following:

1. Add it to a milestone if it is still P1
2. Change priority label and add milestone if no longer P1
3. Close, if this issue is no longer needed

**Comment by kevmoo** [comment]
Still crashes w/ the same error with Dart 2.8

**Comment by natebosch** [comment]
This exception is something that was specifically used to detect malformed requests in https://github.com/dart-lang/shelf/pull/144

Do we have a proposal for how to add access to the bytes?
