### ISSUE TITLE
dart2js with kernel seems to loop in subtype check involving function typed bound

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31679]
Consider the following program:

```dart
class C<X, Y extends List<X Function(X)>> {
  X x;
  Y funs;
  C(this.x, this.funs);
  void run() {
    for (var f in funs) x = f(x);
  }
}

main() {
  print((new C<int, List<int Function(int)>>(
      42, <int Function(int)>[(int x) => x + 1])..run()).x);
}
```

Compilation of this program with `dart2js --use-kernel --checked` (version 2.0.0-dev.7.0 as well as `dart2js_developer` from a fresh commit f781e271ca698fdb4adf7a6d371d053e27c6726d) succeeds, but the generated code fails during a subtype check:

```
/usr/local/google/home/eernst/bin/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:255: RangeError: Maximum call stack size exceeded
          throw e;
          ^
RangeError: Maximum call stack size exceeded
    at Object.functionTypeCheck (out.js:1032:36)
    at Object.functionTypeCheck (out.js:1032:18)
    at Object.functionTypeCheck (out.js:1032:18)
    at Object.functionTypeCheck (out.js:1032:18)
    at Object.functionTypeCheck (out.js:1032:18)
    at Object.functionTypeCheck (out.js:1032:18)
    at Object.functionTypeCheck (out.js:1032:18)
    at Object.functionTypeCheck (out.js:1032:18)
    at Object.functionTypeCheck (out.js:1032:18)
    at Object.functionTypeCheck (out.js:1032:18)
```

Note that a similar symptom arose in a different situation recently (issue #31676), where the type also involved a subterm of the form `T Function(T)`, but it was created using a class with a `call` method.

**Comment by eernstg** [comment]
Here is yet another small program that seems to encounter the same problem, where each type variable occurs only in a contravariant position in a bound (so it's not about having both polarities for the same type variable). Compile it with `dart2js --use-kernel --checked` and run it:
```dart
class C<X extends Function(Y), Y extends Function(Z), Z> {}

main() {
  print(new C());
}
```
Tool versions are the same as [above](https://github.com/dart-lang/sdk/issues/31679#issue-282868273). Here's the run-time output:
```
/usr/local/google/home/eernst/bin/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:255: RangeError: Maximum call stack size exceeded
          throw e;
          ^
RangeError: Maximum call stack size exceeded
    at Object.functionTypeCheck (out.js:797:36)
    at Object.functionTypeCheck (out.js:797:18)
    at Object.functionTypeCheck (out.js:797:18)
    at Object.functionTypeCheck (out.js:797:18)
    at Object.functionTypeCheck (out.js:797:18)
    at Object.functionTypeCheck (out.js:797:18)
    at Object.functionTypeCheck (out.js:797:18)
    at Object.functionTypeCheck (out.js:797:18)
    at Object.functionTypeCheck (out.js:797:18)
    at Object.functionTypeCheck (out.js:797:18)
```
