### ISSUE TITLE
dartanalyzer crashes on function type in bound (with and without `--strong`)

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31680]
Consider the following program:
```dart
class C<X, Y extends List<X Function(X)>> {
  X x;
  Y funs;
  C(this.x, this.funs);
  void run() {
    for (var f in funs) x = f(x);
  }
}

main() {
  print((new C<int, List<int Function(int)>>(
      42, <int Function(int)>[(int x) => x + 1])..run()).x);
}
```

Running `dartanalyzer` or `dartanalyzer --strong` (2.0.0-dev.7.0) on this program causes the following crash (with identical output with and without `--strong`):

```
Unhandled exception:
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9629)
#2      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5729)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7987)
#4      TypeArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10555)
```

**Comment by eernstg** [comment]
Here is a simpler program that causes a similar crash, with and without `--strong`:
```dart
class D<X, Y extends List<X Function(X)>> {}
main() => new D();
```

**Comment by bwilkerson** [comment]
@MichaelRFairhurst Is this something you could take a look at?

**Comment by MichaelRFairhurst** [comment]
Fix landed in https://dart-review.googlesource.com/c/sdk/+/32661
