### ISSUE TITLE
dart2js crashes on function type bounds

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31688]
Consider the following program:
```dart
class C<X extends Function(Y), Y extends Function(Z), Z> {}

main() {
  print(new C());
}
```
When compiling this program with `dart2js` and `dart2js --checked` (version 2.0.0-dev.7.0) we get the following crash:
```
Internal Error: The compiler crashed when compiling this element.
class C<X extends Function(Y), Y extends Function(Z), Z> {}
^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.0.0-dev.7.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: Class 'FunctionTypeAnnotation' has no instance getter 'typeName'.
Receiver: Instance of 'FunctionTypeAnnotation'
Tried calling: typeName
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      TypeResolver.resolveNominalTypeAnnotation (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/resolution/type_resolver.dart:233)
#2      TypeDefinitionVisitor.resolveTypeVariableBounds (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/resolution/class_hierarchy.dart:78)
#3      ClassResolverVisitor.visitClassNode (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/resolution/class_hierarchy.dart:148)
#4      ClassNode.accept (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/tree/nodes.dart:539)
#5      CommonResolverVisitor.visit (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:32)
#6      ResolverTask.resolveClassInternal.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/resolution/resolution.dart:668)
#7      CompilerTask.measure (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63)
#8      ResolverTask.resolveClassInternal.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/resolution/resolution.dart:660)
#9      CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:1129)
#10     ResolverTask.resolveClassInternal (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/resolution/resolution.dart:658)
```
With a fresh `dart2js` from commit dfc356eb0ac8ae17a34648809ca7c339d43092e6 we get a different crash:
```
Internal Error: The compiler crashed when compiling this element.
class C<X extends Function(Y), Y extends Function(Z), Z> {}
^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: type 'FunctionTypeAnnotation' is not a subtype of type 'NominalTypeAnnotation' of 'bound' where
  FunctionTypeAnnotation is from file:///usr/local/google/home/eernst/devel/dart/work/sdk/pkg/compiler/lib/src/tree/nodes.dart
  NominalTypeAnnotation is from file:///usr/local/google/home/eernst/devel/dart/work/sdk/pkg/compiler/lib/src/tree/nodes.dart

#0      NodeListener.endTypeVariable (file:///usr/local/google/home/eernst/devel/dart/work/sdk/pkg/compiler/lib/src/parser/node_listener.dart:1127:35)
#1      Parser.parseTypeVariable (package:front_end/src/fasta/parser/parser.dart:1953:14)
#2      Parser.parseTypeVariablesOpt.<anonymous closure> (package:front_end/src/fasta/parser/parser.dart:2647:16)
#3      Parser.parseStuff (package:front_end/src/fasta/parser/parser.dart:2667:28)
#4      Parser.parseTypeVariablesOpt (package:front_end/src/fasta/parser/parser.dart:2644:12)
#5      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1416:13)
#6      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:511:14)
#7      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:425:14)
#8      Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:397:9)
#9      PartialClassElement.parseNode.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/eernst/devel/dart/work/sdk/pkg/compiler/lib/src/parser/partial_elements.dart:391:32)
#10     CompilerTask.measure (file:///usr/local/google/home/eernst/devel/dart/work/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
```
This seems to imply that the relevant part of the implementation is under active development, which might mean that it needs to be fixed (even though this is not `dart2js --use-kernel`, that is, "it's a legacy `dart2js` crash").

**Comment by sigmundch** [comment]
handled by the CFE
