### ISSUE TITLE
corelib_2/map_test failure when mixin transformation is disabled

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31690]
With mixin transformation disabled in the kernel(https://dart-review.googlesource.com/c/sdk/+/23760) frontend fails on corelib_2/map_test

```
stderr:
tests/corelib_2/map_test.dart:903:7: Internal problem: Unhandled Null in installDefaultConstructor.
class MapBaseMap<K, V> = MapBase<K, V> with MapBaseOperations<K, V>;
      ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29)
#1      unhandled (package:front_end/src/fasta/problems.dart:41)
#2      KernelTarget.installDefaultConstructor (package:front_end/src/fasta/kernel/kernel_target.dart:430)
#3      KernelTarget.installDefaultConstructors (package:front_end/src/fasta/kernel/kernel_target.dart:394)
#4      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:236)
<asynchronous suspension>
#5      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:100)
<asynchronous suspension>
#6      kernelForProgram.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:43)
<asynchronous suspension>
#7      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:96)
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     runZoned (dart:async/zone.dart:1501)
#11     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:96)
#12     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:107)
#13     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:42)
<asynchronous suspension>
#14     SingleShotCompiler.compileInternal (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:120)
<asynchronous suspension>
#15     Compiler.compile.<anonymous closure> (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:81)
#16     new Future.<anonymous closure> (dart:async/future.dart:174)
#17     _rootRun (dart:async/zone.dart:1122)
#18     _CustomZone.run (dart:async/zone.dart:1023)
#19     _CustomZone.runGuarded (dart:async/zone.dart:925)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#24     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#25     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:367)
#26     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:401)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

--- Re-run this test:
python tools/test.py -m release -c dartk --strong corelib_2/map_test
```

**Comment by kmillikin** [comment]
Running Fasta in checked mode shows what's going on:

```
$ pkg/front_end/tool/fasta compile --target=none --strong tests/corelib_2/map_test.dart

Note: strong mode support is preliminary and may not work.
Unhandled exception:
type 'DillClassBuilder' is not a subtype of type 'SourceClassBuilder' of 'named' where
  DillClassBuilder is from package:front_end/src/fasta/dill/dill_class_builder.dart
  KernelTypeBuilder is from package:front_end/src/fasta/kernel/kernel_type_builder.dart
  InterfaceType is from package:kernel/ast.dart
  SourceClassBuilder is from package:front_end/src/fasta/source/source_class_builder.dart
  KernelTypeBuilder is from package:front_end/src/fasta/kernel/kernel_type_builder.dart
  InterfaceType is from package:kernel/ast.dart

#0      KernelTarget.installDefaultConstructor (package:front_end/src/fasta/kernel/kernel_target.dart:426:36)
#1      KernelTarget.installDefaultConstructors (package:front_end/src/fasta/kernel/kernel_target.dart:395:9)
#2      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:237:7)
```
So the code for building outlines has a precondition that if a superclass is a mixin application then it is coming from Dart source and not from a .dill file.  Specifically, if we want to disable mixin elimination for the VM's platform files, this precondition is no longer true.

We should make this code more robust by checking its preconditions.

Marking this a low priority based on the understanding that implementing mixin elimination in the VM is also not a high priority.  If you still want to do mixin elimination in the JIT VM, I think that having the front end eliminate the mixin applications from the precompiled platform is the way you would want to go anyway.
