### ISSUE TITLE
Crash in platform building

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#31700]
With CL https://dart-review.googlesource.com/c/sdk/+/26620 I get a front-end crash when building the SDK:
```
ninja -C out/ReleaseX64 all
ninja: Entering directory `out/ReleaseX64'
[43/181] ACTION //runtime/vm:vm_legacy_...form(//build/toolchain/linux:clang_x64)
FAILED: vm_platform.dill vm_outline.dill 
python ../../tools/compile_platform.py dart:core ../../sdk/lib/libraries.json vm_
platform.dill vm_outline.dill
Unhandled exception:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept(Instance of '_OccurrenceVisitor')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      _OccurrenceVisitor.handleTypeParameter (package:kernel/type_algebra.dart:
711:23)
#2      Object&ListMixin.any (dart:collection/list.dart:115)
#3      _OccurrenceVisitor.visitFunctionType (package:kernel/type_algebra.dart:69
9:32)
#4      FunctionType.accept (package:kernel/ast.dart:4878:34)
#5      _OccurrenceVisitor.visit (package:kernel/type_algebra.dart:679:37)
#6      containsTypeVariable (package:kernel/type_algebra.dart:75:44)
#7      KernelFunctionBuilder.buildFunction (package:front_end/src/fasta/kernel/k
ernel_procedure_builder.dart:199:15)
#8      KernelProcedureBuilder.build (package:front_end/src/fasta/kernel/kernel_procedure_builder.dart:320:28)
#9      SourceClassBuilder.build.buildBuilders (package:front_end/src/fasta/source/source_class_builder.dart:117:37)
#10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/
compact_hash.dart:361)
#11     Scope.forEach (package:front_end/src/fasta/scope.dart:243:11)
#12     SourceClassBuilder.build (package:front_end/src/fasta/source/source_class
_builder.dart:129:11)
#13     KernelLibraryBuilder.buildBuilder (package:front_end/src/fasta/kernel/ker
nel_library_builder.dart:771:21)
#14     SourceLibraryBuilder.build.<anonymous closure> (package:front_end/src/fasta/source/source_library_builder.dart:437:9)
#15     LibraryBuilder.forEach.<anonymous closure> (package:front_end/src/fasta/builder/library_builder.dart:187:10)
#16     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:361)
#17     Scope.forEach (package:front_end/src/fasta/scope.dart:243:11)
#18     LibraryBuilder.forEach (package:front_end/src/fasta/builder/library_build
er.dart:185:11)
#19     SourceLibraryBuilder.build (package:front_end/src/fasta/source/source_lib
rary_builder.dart:435:5)
#20     KernelLibraryBuilder.build (package:front_end/src/fasta/kernel/kernel_lib
rary_builder.dart:851:16)
#21     SourceLoader.buildProgram.<anonymous closure> (package:front_end/src/fast
a/source/source_loader.dart:527:34)
#22     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:361)
#23     SourceLoader.buildProgram (package:front_end/src/fasta/source/source_load
er.dart:524:14)
#24     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_tar
get.dart:234:14)
<asynchronous suspension>
#25     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:
100:28)
<asynchronous suspension>
#26     compilePlatformInternal (file:///usr/local/google/home/lrn/dart/co/sdk/pk
g/front_end/tool/_fasta/compile_platform.dart:68:13)
<asynchronous suspension>
#27     compilePlatform.<anonymous closure> (file:///usr/local/google/home/lrn/da
rt/co/sdk/pkg/front_end/tool/_fasta/compile_platform.dart:56:12)
#28     withGlobalOptions.<anonymous closure> (file:///usr/local/google/home/lrn/
dart/co/sdk/pkg/front_end/tool/_fasta/command_line.dart:364:13)
#29     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:96:35)
#30     _rootRun (dart:async/zone.dart:1124)
#31     _CustomZone.run (dart:async/zone.dart:1021)
#32     runZoned (dart:async/zone.dart:1499)
#33     CompilerContext.runInContext (package:front_end/src/fasta/compiler_contex
t.dart:96:14)
#34     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_cont
ext.dart:107:41)
#35     withGlobalOptions (file:///usr/local/google/home/lrn/dart/co/sdk/pkg/fron
t_end/tool/_fasta/command_line.dart:357:26)
#36     compilePlatform (file:///usr/local/google/home/lrn/dart/co/sdk/pkg/front_
end/tool/_fasta/compile_platform.dart:53:9)
<asynchronous suspension>
#37     main (file:///usr/local/google/home/lrn/dart/co/sdk/pkg/front_end/tool/_f
asta/compile_platform.dart:42:13)
<asynchronous suspension>
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart
:151)
```

Same error occurs for other targets:
```
FAILED: dart2js_platform.dill dart2js_outline.dill 
python ../../tools/compile_platform.py --target=dart2js dart:core ../../sdk/lib/l
ibraries.json dart2js_platform.dill dart2js_outline.dill
Unhandled exception:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept(Instance of '_OccurrenceVisitor')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      _OccurrenceVisitor.handleTypeParameter (package:kernel/type_algebra.dart:
711:23)
```
and
```
FAILED: patched_sdk/lib/libraries.json 
python ../../tools/patch_sdk.py --quiet vm /usr/local/google/home/lrn/dart/co/sdk
/sdk /usr/local/google/home/lrn/dart/co/sdk/out/ReleaseX64/gen/runtime/vm/patches
 patched_sdk /usr/local/google/home/lrn/dart/co/sdk/.packages
Unhandled exception:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept(Instance of '_OccurrenceVisitor')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      _OccurrenceVisitor.handleTypeParameter (package:kernel/type_algebra.dart:
711:23)
```

**Comment by peter-ahe-google** [comment]
Aske will look at this, and it may be a known issue that he has already implemented a fix for.

**Comment by peter-ahe-google** [comment]
Proposed fix: [change 22500](https://dart-review.googlesource.com/c/sdk/+/22500).
