### ISSUE TITLE
autofill on a ValueChanged<double> object

### ISSUE THREAD

**Issue by gaara87** [dart-lang/sdk#31702]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA 173.4506631`
- `1.25.0-dev.11.0`
- `AI-173.4506631, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/n8/nkbn1t4d42j8_fwgqpmj5s44n2p9fm/T/report.txt

```
Dart analysis server, SDK version 1.25.0-dev.11.0, server version 1.18.4, FATAL error: Failed to handle request: {id: 812, method: edit.isPostfixCompletionApplicable, params: {file: /Users/ramaniar/workspace/FlutterProjects/wrap_it_up/lib/customizations.dart, offset: 645, key: .if}, clientRequestTime: 1513795698446}
Invalid argument(s): argumentTypes.length (0) != typeFormals.length (1)
#0      FunctionTypeImpl.instantiate (package:analyzer/src/dart/element/type.dart:860)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:541)
#2      Object

**Comment by devoncarew** [comment]
dup of https://github.com/dart-lang/sdk/issues/34114
