### ISSUE TITLE
All dartk tests fail on Windows

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31706]
Here is an example failure:

```
FAILED: dartk-vm release_x64 service/get_ports_rpc_test
Expected: Pass
Actual: DartkCrash

--- Command "vm" (took 640ms):
set DART_CONFIGURATION=ReleaseX64 & out\ReleaseX64\dart.exe --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/ReleaseX64 --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=C:\src\dart-sdk\sdk\.packages C:\src\dart-sdk\sdk\runtime\observatory\tests\service\get_ports_rpc_test.dart

exit code:
252

stderr:
FileSystemException(uri=c:; message=PhysicalFileSystem only supports file:* URIs)
#0      PhysicalFileSystem.entityForUri (package:front_end/src/api_prototype/physical_file_system.dart:24)
#1      ProcessedOptions.validateOptions (package:front_end/src/base/processed_options.dart:244)
<asynchronous suspension>
#2      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:45)
<asynchronous suspension>
#3      kernelForProgram.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:43)
<asynchronous suspension>
#4      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:96)
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:96)
#9      CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:107)
#10     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:42)
<asynchronous suspension>
#11     SingleShotCompiler.compileInternal (file:///C:/src/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:129)
<asynchronous suspension>
#12     Compiler.compile.<anonymous closure> (file:///C:/src/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:90)
#13     new Future.<anonymous closure> (dart:async/future.dart:174)
#14     _rootRun (dart:async/zone.dart:1122)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#21     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#22     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:367)
#23     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:401)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

--- Re-run this test:
python tools/test.py -m release -c dartk service/get_ports_rpc_test
```

**Comment by aam** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/d9173c09496990020c05ae8326655579f3746007.
