### ISSUE TITLE
Issue on running Flutter clean on running the example in Firebase_Auth

### ISSUE THREAD

**Issue by Prayuta** [dart-lang/sdk#31727]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4127.27`
- `1.25.0-dev.11.0`
- `IC-173.4127.27, JRE 1.8.0_152-release-1024-b8x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 2880x1620`

# Exception

Please append the contents of:
file://C:\Users\Srinivas\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.25.0-dev.11.0, server version 1.18.4, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\Projects\FlutterPlugins\packages\firebase_auth], excluded: [D:\Projects\FlutterPlugins\packages\firebase_auth\.idea, D:\Projects\FlutterPlugins\packages\firebase_auth\.pub, D:\Projects\FlutterPlugins\packages\firebase_auth\build, D:\Projects\FlutterPlugins\packages\firebase_auth\example\.pub, D:\Projects\FlutterPlugins\packages\firebase_auth\example\build]}, clientRequestTime: 1514443044971}
FileSystemException: Exists failed, path = 'D:\Projects\FlutterPlugins\packages\firebase_auth\example\build\app\intermediates\transforms\dexBuilder\debug\166\io' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:63)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:323)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:168)
#3      _HashVMBase

**Comment by natebosch** [comment]
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.
