### ISSUE TITLE
Analyzer Error

### ISSUE THREAD

**Issue by brianegan** [dart-lang/sdk#31735]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4127.27`
- `1.25.0-dev.11.0`
- `IC-173.4127.27, JRE 1.8.0_152-release-1024-b8x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.2 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/5n/7cgb8l2x7m56g1c11schk1zr0000gn/T/report.txt

```
Dart analysis server, SDK version 1.25.0-dev.11.0, server version 1.18.4, error: Captured exception
NoSuchMethodError: The getter 'beginToken' was called on null.
Receiver: null
Tried calling: beginToken
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      SimpleFormalParameterImpl.beginToken (package:analyzer/src/dart/ast/ast.dart:9202)
#3      AstNodeImpl.offset (package:analyzer/src/dart/ast/ast.dart:949)
#4      _SummarizeAstVisitor.serializeCodeRange (package:analyzer/src/summary/summarize_ast.dart:487)
#5      _SummarizeAstVisitor.serializeParameter (package:analyzer/src/summary/summarize_ast.dart:799)
#6      _SummarizeAstVisitor.visitSimpleFormalParameter (package:analyzer/src/summary/summarize_ast.dart:1346)
#7      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9228)
#8      _SummarizeAstVisitor.serializeGenericFunctionType.<anonymous closure> (package:analyzer/src/summary/summarize_ast.dart:764)
#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#10     ListIterable.toList (dart:_internal/iterable.dart:218)
#11     _SummarizeAstVisitor.serializeGenericFunctionType (package:analyzer/src/summary/summarize_ast.dart:765)
#12     _SummarizeAstVisitor.serializeTypeName (package:analyzer/src/summary/summarize_ast.dart:931)
#13     _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:977)
#14     _SummarizeAstVisitor.visitFieldDeclaration (package:analyzer/src/summary/summarize_ast.dart:1148)
#15     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4364)
#16     _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:466)
#17     _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1014)
#18     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1906)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#20     _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:519)
#21     serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22)
#22     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:446)
#23     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#24     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:445)
#25     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:220)
#26     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#27     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:216)
#28     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:289)
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:801)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1615)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1558)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#35     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:434)
#36     _rootRun (dart:async/zone.dart:1120)
#37     _CustomZone.run (dart:async/zone.dart:1001)
#38     runZoned (dart:async/zone.dart:1467)
#39     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:473)
#40     Driver.start (package:analysis_server/src/server/driver.dart:433)
#41     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

```
1514764289137 <= {"event":"analysis.overrides","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","overrides":[{"offset":2893,"length":11,"s
1514764289137 <= {"id":"1062","result":{}}
1514764289186 <= {"event":"analysis.errors","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","errors":[{"severity":"WARNING","type":"STATI
1514764289187 <= {"id":"1063","result":{"assists":[{"message":"Remove type annotation","edits":[{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","f
1514764289187 <= {"id":"1064","result":{"assists":[{"message":"Remove type annotation","edits":[{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","f
1514764289189 <= {"event":"analysis.highlights","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","regions":[{"type":"DIRECTIVE","offset":0
1514764289191 <= {"event":"analysis.navigation","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","regions":[{"offset":7,"length":12,"targe
1514764289191 <= {"event":"analysis.closingLabels","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","labels":[{"offset":1233,"length":724,
1514764289192 <= {"event":"analysis.outline","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","kind":"LIBRARY","outline":{"element":{"kind
1514764289192 <= {"event":"analysis.overrides","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","overrides":[{"offset":2894,"length":11,"s
1514764289227 <= {"event":"analysis.errors","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/main.dart","errors":[]}}
1514764289228 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1514764289228 <= {"event":"analysis.implemented","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","classes":[],"members":[]}}
1514764289484 => {"id":"1065","method":"analysis.updateContent","params":{"files":{"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart":{"type":"add","content"
1514764289484 => {"id":"1066","method":"completion.getSuggestions","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","offset":2694},"client
1514764289485 <= {"id":"1065","result":{}}
1514764289485 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1514764289531 <= {"id":"1066","result":{"id":"164"}}
1514764289531 <= {"event":"analysis.errors","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","errors":[{"severity":"WARNING","type":"STATI
1514764289532 <= {"event":"completion.results","params":{"id":"164","replacementOffset":2693,"replacementLength":1,"results":[],"isLast":true}}
1514764289533 <= {"event":"analysis.highlights","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","regions":[{"type":"DIRECTIVE","offset":0
1514764289536 <= {"event":"analysis.navigation","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","regions":[{"offset":7,"length":12,"targe
1514764289536 <= {"event":"analysis.closingLabels","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","labels":[{"offset":1233,"length":724,
1514764289537 <= {"event":"analysis.outline","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","kind":"LIBRARY","outline":{"element":{"kind
1514764289538 <= {"event":"analysis.overrides","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","overrides":[{"offset":2895,"length":11,"s
1514764289542 => {"id":"1067","method":"analysis.updateContent","params":{"files":{"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart":{"type":"add","content"
1514764289542 => {"id":"1068","method":"completion.getSuggestions","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/github_search_widget.dart","offset":2695},"client
1514764289568 <= {"event":"analysis.errors","params":{"file":"/Users/phillywiggins/lab/rxdart/example/flutter/github_search/lib/main.dart","errors":[]}}
1514764289569 <= {"id":"1067","result":{}}
1514764289582 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The getter 'beginToken' was called on null.\nReceiver: null\nTried ca
```

**Comment by bwilkerson** [comment]
This should have been fixed by https://dart-review.googlesource.com/4600.
