### ISSUE TITLE
StringBuffer patch fails with VM strong mode

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#31737]
Apparently, this happens on loading script source.
```
Dart VM version: 2.0.0-dev.14.0 (Wed Dec 20 10:43:00 2017 +0100) on "windows_x64"

Unhandled exception:
type 'List' is not a subtype of type 'List<String>' of '_parts@0150898' where
  List is from dart:core
  List is from dart:core
  String is from dart:core

#0      StringBuffer._parts= (dart:core-patch/dart:core/string_buffer_patch.dart:17)
#1      StringBuffer._addPart (dart:core-patch/dart:core/string_buffer_patch.dart:163)
#2      StringBuffer.write (dart:core-patch/dart:core/string_buffer_patch.dart:67)
#3      new StringBuffer (dart:core-patch/dart:core/string_buffer_patch.dart:56)
#4      ListIterable.join (dart:_internal/iterable.dart:152)
#5      _Uri._makePath (dart:core/uri.dart:2100)
#6      new _Uri (dart:core/uri.dart:1497)
#7      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1761)
#8      new _Uri.directory (dart:core/uri.dart:1670)
#9      _setWorkingDirectory (dart:_builtin:145)
```

CL: https://dart-review.googlesource.com/c/sdk/+/31900

**Comment by mraleph** [comment]
Note: when using strong mode with VM you need to use `pkg/vm/tool/dart2` wrapper (which is not available on Windows yet). Strong mode is not supposed to work with old front-end. 

When I run your code through it I don't get any error, because Fasta correctly infers type argument. Here is the Kernel representation of the `_addPart` dumped from `vm_platform_strong.dill`

```
   method _addPart(core::String str) → void {
      core::int length = str.{core::String::length};
      this.{core::StringBuffer::_partsCodeUnits} = this.{core::StringBuffer::_partsCodeUnits}.{core::num::+}(length);
      this.{core::StringBuffer::_partsCodeUnitsSinceCompaction} = this.{core::StringBuffer::_partsCodeUnitsSinceCompaction}.{core::num::+}(length);
      if(this.{core::StringBuffer::_parts}.{core::Object::==}(null)) {
        this.{core::StringBuffer::_parts} = let final core::_GrowableList<core::String> #t596 = core::_GrowableList::withCapacity<core::String>(10) in let final dynamic #t597 = #t596.{core::_GrowableList::add}(str) in #t596;
      }
      else {
        this.{core::StringBuffer::_parts}.{core::List::add}(str);
        core::int partsSinceCompaction = this.{core::StringBuffer::_parts}.{core::List::length}.{core::num::-}(this.{core::StringBuffer::_partsCompactionIndex});
        if(partsSinceCompaction.{core::num::==}(core::StringBuffer::_PARTS_TO_COMPACT)) {
          this.{core::StringBuffer::_compact}();
        }
      }
    }
 ```

We are going to add Windows wrapper for Dart 2 soon (porting `pkg/vm/tool/dart2` should be rather straightforward).

**Comment by mraleph** [comment]
@lexaknyazev please let me know if you have any questions

**Comment by lexaknyazev** [comment]
@mraleph Thanks for the prompt feedback, seems like I was too eager to try new features.

Running `pkg/vm/tool/dart2` fails with:
```
kernel-service: Isolate creation error: Unhandled exception:
Could not load "file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/gen/kernel-service.dart.snapshot": FileSystemException: Cannot open file, path = '/home/alexey/dart-sdk/sdk/out/ReleaseX64/gen/kernel-service.dart.snapshot' (OS Error: No such file or directory, errno = 2)
null
Error while initializing Kernel isolate
```

I've built SDK with `./tools/build.py --mode release --arch x64 create_sdk`.

**Comment by mraleph** [comment]
@lexaknyazev You need to buiild `runtime_kernel` target if you want to use `dart2` wrapper.

**Comment by mraleph** [comment]
Why was this reopened @bkonyi ?
