### ISSUE TITLE
Not able to read file :(

### ISSUE THREAD

**Issue by zarub2k** [dart-lang/sdk#31731]
I have both of my dart and sample file in the same location. When I try to run my dart application which is simply reading the content of the file and I am getting an error. I have no clue what I am doing wrong. Can anyone give me a hint on this?

My code has been checked-in the location https://github.com/hustlebar/darthustle/tree/master/lib
Check dart_io.dart file and the hello.json

FileSystemException: Cannot open file, path = 'hello.json' (OS Error: No such file or directory, errno = 2), #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:337)
#1      _RootZone.runUnary (dart:async/zone.dart:1371)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#5      _Future._completeWithValue (dart:async/future_impl.dart:478)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)

**Comment by zarub2k** [comment]
After I modified the path relative to my base project directory, this is working fine. So I am closing the issue.
