### ISSUE TITLE
Invalid argument (handler): Must be a ServiceExtensionHandler: Closure: (String, Map<String, String>) => Future

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#31751]
Running hello world flutter app with --strong option produces the following error 

E/flutter (13373): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (13373): Invalid argument (handler): Must be a ServiceExtensionHandler: Closure: (String, Map<String, String>) => Future
E/flutter (13373): #0      registerExtension (file:///usr/local/google/home/asiva/workspace/flutter-ws/engine/src/out/android_release/flutter_patched_sdk/lib/developer/extension.dart:146)
E/flutter (13373): #1      BindingBase.registerServiceExtension (package:flutter/src/foundation/binding.dart:360)
E/flutter (13373): #2      BindingBase.registerSignalServiceExtension (package:flutter/src/foundation/binding.dart:243)
E/flutter (13373): #3      BindingBase.initServiceExtensions (package:flutter/src/foundation/binding.dart:105)
E/flutter (13373): #4      __BindingBase&GestureBinding&ServicesBinding.initServiceExtensions (package:flutter/src/services/binding.dart:62)
E/flutter (13373): #5      ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.initServiceExtensions (package:flutter/src/scheduler/binding.dart:188)
E/flutter (13373): #6      _____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.initServiceExtensions (package:flutter/src/rendering/binding.dart:55)
E/flutter (13373): #7      ______BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.initServiceExtensions (package:flutter/src/widgets/binding.dart:259)
E/flutter (13373): #8      new BindingBase. (package:flutter/src/foundation/binding.dart:55)
E/flutter (13373): #9      new _BindingBase&GestureBinding. (package:flutter/src/widgets/binding.dart:0)
E/flutter (13373): #10     new __BindingBase&GestureBinding&ServicesBinding. (package:flutter/src/widgets/binding.dart:0)
E/flutter (13373): #11     new ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding. (package:flutter/src/widgets/binding.dart:0)
E/flutter (13373): #12     new ____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding. (package:flutter/src/widgets/binding.dart:0)
E/flutter (13373): #13     new _____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding. (package:flutter/src/widgets/binding.dart:0)
E/flutter (13373): #14     new ______BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding. (package:flutter/src/widgets/binding.dart:0)
E/flutter (13373): #15     new WidgetsFlutterBinding. (package:flutter/src/widgets/binding.dart:0)
E/flutter (13373): #16     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:897)
E/flutter (13373): #17     runApp (package:flutter/src/widgets/binding.dart:689)
E/flutter (13373): #18     main (file:///usr/local/google/home/asiva/workspace/flutter-ws/flutter/examples/hello_world/lib/main.dart:6)
E/flutter (13373): #19     _startIsolate.<anonymous closure> (dart:isolate:1257)
E/flutter (13373): #20     _RawReceivePortImpl._handleMessage (dart:isolate:1147)
Application finished.

**Comment by a-siva** [comment]
rmacnak@ has fixed a number of strong mode errors in the service code and I don't see these errors when running flutter gallery in strong mode anymore.
