### ISSUE TITLE
strong mode runtime errors when running debug version of hello world flutter app

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#31752]
1. vmservice on hello world flutter app is not initializing when run with --strong option

E/DartVM  (13523): vm-service: Error: Unhandled exception:
E/DartVM  (13523): type '_Future' is not a subtype of type 'Future<Socket>' where
E/DartVM  (13523):   _Future is from dart:async
E/DartVM  (13523):   Future is from dart:async
E/DartVM  (13523):   Socket is from dart:io
E/DartVM  (13523): 
E/DartVM  (13523): #0      _Socket.flush (dart:io:2691:35)
E/DartVM  (13523): #1      _HttpOutgoing.close.finalize (file:///usr/local/google/home/asiva/workspace/flutter-ws/engine/src/out/android_debug_unopt/flutter_patched_sdk/lib/_http/http_impl.dart:1428:21)
E/DartVM  (13523): #2      _HttpOutgoing.close (file:///usr/local/google/home/asiva/workspace/flutter-ws/engine/src/out/android_debug_unopt/flutter_patched_sdk/lib/_http/http_impl.dart:1445:35)
E/DartVM  (13523): #3      _StreamSinkImpl._closeTarget (file:///usr/local/google/home/asiva/workspace/flutter-ws/engine/src/out/android_debug_unopt/flutter_patched_sdk/lib/_http/http_impl.dart:606:13)
E/DartVM  (13523): #4      _StreamSinkImpl.close (file:///usr/local/google/home/asiva/workspace/flutter-ws/engine/src/out/android_debug_unopt/flutter_patched_sdk/lib/_http/http_impl.dart:599:9)
E/DartVM  (13523): #5      _HttpResponse.detachSocket (file:///usr/local/google/home/asiva/workspac
E/flutter (13523): [ERROR:flutter/runtime/dart_init.cc(167)] Isolate (848730656) 'vm-service' exited with an error

2. Type error "type '(ByteData) => Future' is not a subtype of type '(ByteData) => Future<ByteData>' of 'handler'"

E/flutter (13523): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (13523): type '(ByteData) => Future' is not a subtype of type '(ByteData) => Future<ByteData>' of 'handler'
E/flutter (13523): #0      BinaryMessages.setMessageHandler (package:flutter/src/services/platform_messages.dart)
E/flutter (13523): #1      BasicMessageChannel.setMessageHandler (package:flutter/src/services/platform_channel.dart:64:22)
E/flutter (13523): #2      ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.initInstances (package:flutter/src/scheduler/binding.dart:179:30)
E/flutter (13523): #3      ____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:22:11)
E/flutter (13523): #4      _____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:31:11)
E/flutter (13523): #5      ______BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:241:11)
E/flutter (13523): #6      new BindingBase (package:flutter/src/foundation/binding.dart:51:5)
E/flutter (13523): #7      new _BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
E/flutter (13523): #8      new __BindingBase&GestureBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
E/flutter (13523): #9      new ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
E/flutter (13523): #10     new ____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
E/flutter (13523): #11     new _____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
E/flutter (13523): #12     new ______BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
E/flutter (13523): #13     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
E/flutter (13523): #14     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:897:11)
E/flutter (13523): #15     runApp (package:flutter/src/widgets/binding.dart:689:25)
E/flutter (13523): #16     main (file:///usr/local/google/home/asiva/workspace/flutter-ws/flutter/examples/hello_world/lib/main.dart:7:16)
E/flutter (13523): #17     _startIsolate.<anonymous closure> (dart:isolate:1257:19)
E/flutter (13523): #18     _RawReceivePortImpl._handleMessage (dart:isolate:1147:12)

**Comment by a-siva** [comment]
rmacnak@ has fixed a number of errors in the service code and I don't  see these errors when running flutter gallery in strong mode.
