### ISSUE TITLE
Analyzer fails when running on Dart VM with fixed-size integers

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#31768]
Reproduction:
```
DART_VM_OPTIONS=--limit-ints-to-64-bits tools/test.py -m release -c dart2analyzer -r none --strong --host-checked corelib_2/num_sign_test
```

```
'package:analyzer/src/summary/summarize_const_expr.dart': Failed assertion: line 290 pos 12: 'value >= 0': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
#1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
#2      AbstractConstExprSerializer._pushInt (package:analyzer/src/summary/summarize_const_expr.dart:290:12)
#3      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:316:7)
#4      Object&ListMixin.forEach (dart:collection/list.dart:63)
#5      AbstractConstExprSerializer._serializeListLiteral (package:analyzer/src/summary/summarize_const_expr.dart:544:16)
#6      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:357:7)
#7      AbstractConstExprSerializer.serialize (package:analyzer/src/summary/summarize_const_expr.dart:139:7)
#8      _SummarizeAstVisitor.serializeConstExpr (package:analyzer/src/summary/summarize_ast.dart:551:16)
#9      _SummarizeAstVisitor.serializeFunctionBody (package:analyzer/src/summary/summarize_ast.dart:715:22)
#10     _SummarizeAstVisitor.serializeInitializerFunction (package:analyzer/src/summary/summarize_ast.dart:784:5)
#11     _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:984:23)
#12     _SummarizeAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/src/summary/summarize_ast.dart:1354:5)
#13     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10341:15)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7987:20)
#15     _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:519:34)
#16     serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22:37)
#17     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:447:46)
#18     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#19     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:446:26)
#20     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:764:12)
#21     AnalysisDriver.getSourceKind (package:analyzer/src/dart/analysis/driver.dart:781:33)
<asynchronous suspension>
#22     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:322:34)
<asynchronous suspension>
#23     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:226:20)
<asynchronous suspension>
#24     Driver.start.<anonymous closure> (package:analyzer_cli/src/driver.dart:192:22)
<asynchronous suspension>
#25     BatchRunner.runAsBatch.<anonymous closure> (package:analyzer_cli/src/batch_mode.dart:52:45)
<asynchronous suspension>
#26     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
```

Also, certain pkg/analyzer tests fail:
```
tools/test.py --vm-options=--limit-ints-to-64-bits -m release -c none -r vm --checked pkg/analyzer/test/src/summary/summarize_ast_test
```

```
[... skipped ...]
00:00 ^[[32m+130^[[0m^[[31m -1^[[0m: LinkedSummarizeAstSpecTest | test_constExpr_pushLongInt ^[[1m^[[31m[E]^[[0m^[[0m
  Expected: [UnlinkedExprOperation:UnlinkedExprOperation.pushLongInt]
    Actual: [UnlinkedExprOperation:UnlinkedExprOperation.pushInt]
     Which: was UnlinkedExprOperation:<UnlinkedExprOperation.pushInt> instead of UnlinkedExprOperation:<UnlinkedExprOperation.pushLongInt> at location [0]
  
  package:test/src/frontend/expect.dart 164:30                       fail
  package:test/src/frontend/expect.dart 158:3                        _expect
  package:test/src/frontend/expect.dart 68:3                         expect
  pkg/analyzer/test/src/summary/summary_common.dart 199:5            SummaryLinkerTest&SummaryTest.assertUnlinkedConst
  pkg/analyzer/test/src/summary/summary_common.dart 2814:5           SummaryLinkerTest&SummaryTest.test_constExpr_pushLongInt
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 531              _LocalInstanceMirror._invoke
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 527              _LocalInstanceMirror.invoke
  package:test_reflective_loader/test_reflective_loader.dart 253:35  _runTest.<fn>
[... skipped ...]
```

/cc @bwilkerson

**Comment by bwilkerson** [comment]
I have fixed the analyzer's handling of integers, and this test now passes.
