### ISSUE TITLE
Dart2js fails when running on Dart VM with fixed-size integers

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#31762]
Reproduction:
```
DART_VM_OPTIONS=--limit-ints-to-64-bits tools/test.py -m release -c dart2js -r chrome -a ia32 --dart2js-batch --reset-browser-configuration dart2js_extra/21579_test
```

Typical failure:
```
tests/compiler/dart2js_extra/21579_test.dart:15:20:
Internal Error: '1000000000000000000000': FormatException: Invalid radix-10 number
1000000000000000000000
  a.sort((a, b) => 1000000000000000000000 * a.compareTo(b));
                   ^^^^^^^^^^^^^^^^^^^^^^
The compiler is broken.
When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.
The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.
Please include the following information:
* the name and version of your operating system,
* the Dart SDK build number (build number could not be determined), and
* the entire message you see here (including the full stack trace
  below as well as the source location above).
The compiler crashed: Internal Error: '1000000000000000000000': FormatException: Invalid radix-10 number
1000000000000000000000
#0      CompilerDiagnosticReporter.internalError (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:1242:5)
#1      NodeListener.handleOnError (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/parser/node_listener.dart:371:14)
#2      NodeListener.handleLiteralInt.<anonymous closure> (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/parser/node_listener.dart:377:46)
#3      LiteralInt.value (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/tree/nodes.dart:1298:13)
#4      ResolverVisitor.visitLiteralInt (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/members.dart:3507:66)
#5      LiteralInt.accept (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/tree/nodes.dart:1302:38)
#6      CommonResolverVisitor.visit (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:32:54)
#7      ResolverVisitor.visitExpression (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/members.dart:1093:31)
#8      ResolverVisitor.handleUserDefinableBinary (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/members.dart:1370:37)
#9      ResolverVisitor.handleOperatorSend (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/members.dart:1698:20)
#10     ResolverVisitor.visitSend (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/members.dart:3025:14)
#11     Send.accept (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/tree/nodes.dart:716:38)
#12     CommonResolverVisitor.visit (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:32:54)
#13     ResolverVisitor.visitReturn (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/members.dart:3601:5)
#14     Return.accept (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/tree/nodes.dart:1609:38)
#15     CommonResolverVisitor.visit (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:32:54)
#16     ResolverVisitor.visitFunctionExpression (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/members.dart:605:5)
#17     FunctionExpression.accept (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/tree/nodes.dart:1209:38)
#18     CommonResolverVisitor.visit (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/resolution_common.dart:32:54)
#19     ResolverVisitor.resolveArguments (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/members.dart:711:33)
#20     ResolverVisitor.handleDynamicAccessSemantics (file:///b/swarming/w/ir/cache/builder/sdk/pkg/compiler/lib/src/resolution/members.dart:2287:11)
```

/cc @sigmundch @rakudrama

**Comment by alexmarkov** [comment]
Some tests fail due to runtime error:
```
DART_VM_OPTIONS=--limit-ints-to-64-bits tools/test.py -m release -c dart2js -r chrome -a ia32 language_2/deopt_smi_op_test
```

```
Compiled 1,912,308 characters Dart to 39,186 characters JavaScript in 1.90 seconds
Dart file (/usr/local/google/home/alexmarkov/work/dart/sdk/tests/language_2/deopt_smi_op_test.dart) compiled to JavaScript: out/ReleaseIA32/generated_compilations/dart2js/tests_language_2_deopt_smi_op_test/test.js

--- Command "chrome" (took 88ms):
/usr/local/google/home/alexmarkov/work/dart/sdk/tools/sdks/linux/dart-sdk/bin/dart tools/testing/dart/launch_browser.dart chrome http://127.0.0.1:40734/root_build/generated_tests/dart2js-chrome/tests_language_2_deopt_smi_op_test/test.html?crossOriginPort=46690

Runtime error:
Expect.equals(expected: <0>, actual: <4.611686018427388e+23>) fails.
Expect.equals(expected: <0>, actual: <4.611686018427388e+23>) fails.
    at Object.wrapException (http://127.0.0.1:40734/root_build/generated_compilations/dart2js/tests_language_2_deopt_smi_op_test/test.js:553:17)
    at Object.Expect__fail (http://127.0.0.1:40734/root_build/generated_compilations/dart2js/tests_language_2_deopt_smi_op_test/test.js:868:15)
    at Object.Expect_equals (http://127.0.0.1:40734/root_build/generated_compilations/dart2js/tests_language_2_deopt_smi_op_test/test.js:865:9)
    at main (http://127.0.0.1:40734/root_build/generated_compilations/dart2js/tests_language_2_deopt_smi_op_test/test.js:895:9)
    at dartMainRunner (http://127.0.0.1:40734/root_dart/tools/testing/dart/test_controller.js:324:5)
    at http://127.0.0.1:40734/root_build/generated_compilations/dart2js/tests_language_2_deopt_smi_op_test/test.js:1102:7
    at http://127.0.0.1:40734/root_build/generated_compilations/dart2js/tests_language_2_deopt_smi_op_test/test.js:1088:7
    at http://127.0.0.1:40734/root_build/generated_compilations/dart2js/tests_language_2_deopt_smi_op_test/test.js:1099:5
    at http://127.0.0.1:40734/root_build/generated_compilations/dart2js/tests_language_2_deopt_smi_op_test/test.js:1107:3
```

**Comment by efortuna** [comment]
Fixing with https://github.com/dart-lang/sdk/issues/33286
