### ISSUE TITLE
DDC error: Bad state: Too many elements

### ISSUE THREAD

**Issue by tejainece** [dart-lang/sdk#31773]
Error compiling dartdevc module:biginteger_js|web/web__main.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=/usr/lib/dart --dart-sdk-summary=/usr/lib/dart/lib/_internal/ddc_sdk.sum --modules=amd --dart-sdk=/usr/lib/dart --module-root=/tmp/pub_v5fH7j --library-root=/tmp/pub_v5fH7j/web --summary-extension=linked.sum --no-summarize -o /tmp/pub_v5fH7j/web/web__main.js --source-map --source-map-comment --inline-source-map -s /tmp/pub_v5fH7j/packages/biginteger_js/lib__biginteger_js.linked.sum -s /tmp/pub_v5fH7j/packages/js/lib__js.linked.sum /tmp/pub_v5fH7j/web/main.dart
    dart --version: 1.24.2 (Thu Jun 22 15:42:21 2017) on "linux_x64"
```
Bad state: Too many elements
#0      List.single (dart:core-patch/growable_array.dart:231)
#1      CodeGenerator._emitObjectLiteral (package:dev_compiler/src/compiler/code_generator.dart:4184)
#2      CodeGenerator._emitInstanceCreationExpression (package:dev_compiler/src/compiler/code_generator.dart:4164)
#3      CodeGenerator.visitInstanceCreationExpression (package:dev_compiler/src/compiler/code_generator.dart:4228)
#4      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6494)
#5      CodeGenerator._visit (package:dev_compiler/src/compiler/code_generator.dart:5499)
#6      CodeGenerator._emitArgumentList (package:dev_compiler/src/compiler/code_generator.dart:3841)
#7      CodeGenerator._emitFunctionCall (package:dev_compiler/src/compiler/code_generator.dart:3683)
#8      CodeGenerator.visitMethodInvocation (package:dev_compiler/src/compiler/code_generator.dart:3523)
#9      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#10     CodeGenerator._visit (package:dev_compiler/src/compiler/code_generator.dart:5499)
#11     CodeGenerator.visitExpressionStatement (package:dev_compiler/src/compiler/code_generator.dart:3937)
#12     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#13     CodeGenerator._visit (package:dev_compiler/src/compiler/code_generator.dart:5499)
#14     CodeGenerator._visitList (package:dev_compiler/src/compiler/code_generator.dart:5507)
#15     CodeGenerator.visitBlockFunctionBody (package:dev_compiler/src/compiler/code_generator.dart:3496)
#16     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#17     CodeGenerator._visit (package:dev_compiler/src/compiler/code_generator.dart:5499)
#18     CodeGenerator._emitFunctionBody (package:dev_compiler/src/compiler/code_generator.dart:2692)
#19     CodeGenerator._emitFunction (package:dev_compiler/src/compiler/code_generator.dart:2680)
#20     CodeGenerator.visitFunctionDeclaration (package:dev_compiler/src/compiler/code_generator.dart:2518)
#21     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5197)
#22     CodeGenerator._visit (package:dev_compiler/src/compiler/code_generator.dart:5499)
#23     CodeGenerator.visitCompilationUnit (package:dev_compiler/src/compiler/code_generator.dart:617)
#24     List.forEach (dart:core-patch/array.dart:73)
#25     CodeGenerator._emitModule (package:dev_compiler/src/compiler/code_generator.dart:348)
#26     CodeGenerator.compile (package:dev_compiler/src/compiler/code_generator.dart:232)
#27     ModuleCompiler.compile (package:dev_compiler/src/compiler/compiler.dart:222)
#28     _compile (package:dev_compiler/src/compiler/command.dart:186)
#29     compile (package:dev_compiler/src/compiler/command.dart:60)
#30     _CompilerWorker.performRequest (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/dev_compiler/bin/dartdevc.dart:69)
<asynchronous suspension>
#31     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33)
#32     _rootRun (dart:async/zone.dart:1120)
#33     _CustomZone.run (dart:async/zone.dart:1001)
#34     runZoned (dart:async/zone.dart:1467)
#35     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33)
<asynchronous suspension>
#36     main (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/dev_compiler/bin/dartdevc.dart:51)
<asynchronous suspension>
#37     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

**Comment by jmesserly** [comment]
From the stack trace, this looks like an incorrect definition or use of a JS object literal class. But DDC should issue an error message.

My guess is it happens in code like:
```dart
@JS()
@anonymous
class A {
  external factory A({int x, String y});
  external int get x;
  external String get y;
}

@JS()
@anonymous
class B {
  // this is incorrect: `x` and `y` should be named parameters
  external factory B(int x, String y);
  external int get x;
  external String get y;
}

main() {
  var a = new A(x: 3, y: 'foo'); // correct
  var b = new B(4, 'bar'); // incorrect, will crash DDC
}
```

**Comment by vsmenon** [comment]
@tejainece - looks like this is a public package?  Do you have repro steps?

**Comment by tejainece** [comment]
@vsmenon Yes. Will post the reproducible fixture here in an hour.

**Comment by tejainece** [comment]
Sorry. I can't reproduce it anymore.
