### ISSUE TITLE
service/bad_reload_test strong-mode error in simdbc64

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#31895]
```
python tools/test.py -c dartk -a simdbc64 -mrelease --strong service/bad_reload_test
```

gets me this:
```
>testee>err> Unhandled exception:
>testee>err> IsolateSpawnException: Unable to spawn isolate: Unhandled exception:
>testee>err> type 'List' is not a subtype of type 'List<String>' of '_parts@0150898' where
>testee>err>   List is from dart:core
>testee>err>   List is from dart:core
>testee>err>   String is from dart:core
>testee>err>
>testee>err> #0      StringBuffer._parts= (dart:core-patch/dart:core/string_buffer_patch.dart:17)
>testee>err> #1      StringBuffer._addPart (dart:core-patch/dart:core/string_buffer_patch.dart:163)
>testee>err> #2      StringBuffer.write (dart:core-patch/dart:core/string_buffer_patch.dart:67)
>testee>err> #3      ListIterable.join (dart:_internal/iterable.dart:154)
>testee>err> #4      _Uri._makePath (dart:core/uri.dart:2100)
>testee>err> #5      new _Uri (dart:core/uri.dart:1497)
>testee>err> #6      _Uri._makeFileUri (dart:core/uri.dart:1725)
>testee>err> #7      new _Uri.directory (dart:core/uri.dart:1670)
>testee>err> #8      _setWorkingDirectory (dart:_builtin:145)
>testee>err> #0      Isolate.spawnUri (dart:isolate:457:14)
>testee>err> <asynchronous suspension>
>testee>err> #1      testMain (file://[...]/runtime/observatory/tests/service/bad_reload_test.dart:27:39)
>testee>err> <asynchronous suspension>
>testee>err> #2      _ServiceTesteeRunner.run (file://[...]/runtime/observatory/tests/service/test_helper.dart:50:36)
>testee>err> <asynchronous suspension>
>testee>err> #3      runIsolateTests (file://[...]/runtime/observatory/tests/service/test_helper.dart:410:32)
>testee>err> <asynchronous suspension>
>testee>err> #4      main (file://[...]/runtime/observatory/tests/service/bad_reload_test.dart:81:15)
>testee>err> #5      _startIsolate.<anonymous closure> (dart:isolate:1254:32)
>testee>err> #6      _RawReceivePortImpl._handleMessage (dart:isolate:1146:12)
>testee>err> StreamSink is closed and adding to it is an error.
>testee>err>   See http://dartbug.com/29554.
>testee>err> #0      _StreamSinkImpl._reportClosedSink (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/_http/http_impl.dart:537:31)
>testee>err> #1      _StreamSinkImpl.add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/_http/http_impl.dart:542:7)
>testee>err> #2      _WebSocketImpl.add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/_http/websocket_impl.dart:1203:11)
>testee>err> #3      WebSocketClient.post (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/vmservice_io/server.dart:78:18)
>testee>err> #4      _RootZone.runUnary (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/zone.dart:1381:54)
>testee>err> #5      _FutureListener.handleValue (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/future_impl.dart:129:18)
>testee>err> #6      _Future._propagateToListeners.handleValueCallback (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/future_impl.dart:633:45)
>testee>err> #7      _Future._propagateToListeners (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/future_impl.dart:662:32)
>testee>err> #8      _Future._complete (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/future_impl.dart:467:7)
>testee>err> #9      _SyncCompleter.complete (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/future_impl.dart:51:12)
>testee>err> #10     VMService.routeRequest (dart:_vmservice)
>testee>err> <asynchronous suspension>
>testee>err> #11     Client.onRequest (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/vmservice/client.dart:44:13)
>testee>err> #12     WebSocketClient.onWebSocketMessage (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/vmservice_io/server.dart:52:13)
>testee>err> #13     new WebSocketClient.<anonymous closure> (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/vmservice_io/server.dart:25:32)
>testee>err> #14     _RootZone.runUnaryGuarded (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/zone.dart:1316:10)
>testee>err> #15     _BufferingStreamSubscription._sendData (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_impl.dart:330:11)
>testee>err> #16     _BufferingStreamSubscription._add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_impl.dart:257:7)
>testee>err> #17     _SyncStreamController._sendData (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_controller.dart:762:19)
>testee>err> #18     _StreamController._add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_controller.dart:638:7)
>testee>err> #19     _StreamController.add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_controller.dart:584:5)
>testee>err> #20     new _WebSocketImpl._fromSocket.<anonymous closure> (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/_http/websocket_impl.dart:1128:21)
>testee>err> #21     _RootZone.runUnaryGuarded (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/zone.dart:1316:10)
>testee>err> #22     _BufferingStreamSubscription._sendData (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_impl.dart:330:11)
>testee>err> #23     _BufferingStreamSubscription._add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_impl.dart:257:7)
>testee>err> #24     _SinkTransformerStreamSubscription._add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_transformers.dart:68:11)
>testee>err> #25     _EventSinkWrapper.add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_transformers.dart:15:11)
>testee>err> #26     _WebSocketProtocolTransformer._messageFrameEnd (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/_http/websocket_impl.dart:336:22)
>testee>err> #27     _WebSocketProtocolTransformer.add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/_http/websocket_impl.dart:231:46)
>testee>err> #28     _SinkTransformerStreamSubscription._handleData (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_transformers.dart:120:24)
>testee>err> #29     _RootZone.runUnaryGuarded (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/zone.dart:1316:10)
>testee>err> #30     _BufferingStreamSubscription._sendData (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_impl.dart:330:11)
>testee>err> #31     _BufferingStreamSubscription._add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_impl.dart:257:7)
>testee>err> #32     _SyncStreamController._sendData (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_controller.dart:762:19)
>testee>err> #33     _StreamController._add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_controller.dart:638:7)
>testee>err> #34     _StreamController.add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_controller.dart:584:5)
>testee>err> #35     _Socket._onData (dart:io:2783:41)
>testee>err> #36     _RootZone.runUnaryGuarded (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/zone.dart:1316:10)
>testee>err> #37     _BufferingStreamSubscription._sendData (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_impl.dart:330:11)
>testee>err> #38     _BufferingStreamSubscription._add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_impl.dart:257:7)
>testee>err> #39     _SyncStreamController._sendData (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_controller.dart:762:19)
>testee>err> #40     _StreamController._add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_controller.dart:638:7)
>testee>err> #41     _StreamController.add (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/stream_controller.dart:584:5)
>testee>err> #42     new _RawSocket.<anonymous closure> (dart:io:2383:33)
>testee>err> #43     _NativeSocket.issueReadEvent.issue (dart:io:1938:14)
>testee>err> #44     _microtaskLoop (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/schedule_microtask.dart:41:21)
>testee>err> #45     _startMicrotaskLoop (file://[...]/out/DebugSIMDBC64/patched_sdk/lib/async/schedule_microtask.dart:50:5)
>testee>err> #46     _runPendingImmediateCallback (dart:isolate:1097:13)
>testee>err> #47     _RawReceivePortImpl._handleMessage (dart:isolate:1147:5)
```

whereas with `-a x64` it works just fine.

(note: in simdbc the test fails even without --strong, although it then crashes the VM instead --- I suspect it has something to do with the kernel file being generated in the non-simdbc version, which I guess means that the simdbc version cannot actually compile to kernel itself?)

**Comment by alexmarkov** [comment]
Closing this issue as SIMDBC64 mode was removed a while ago.
