### ISSUE TITLE
Call of non-generic tearoff with generic type arguments should throw NoSuchMethodError

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#31897]
I'm adding a new test `language_2/no_such_method_tearoff_fta_test` which currently fails on `--compiler=dartdevc` and `--compiler=dartdevk` with:

```
sdk % tools/test.py -mrelease -cdartdevc --strong  language_2/no_such_method_tearoff_fta_test
Test configuration: dartdevc_chrome_release_x64_strong

FAILED: dartdevc-chrome release_x64 language_2/no_such_method_tearoff_fta_test
Expected: Pass
Actual: RuntimeError

--- Command "dartdevc" (took 01.000293s):
DART_CONFIGURATION=ReleaseX64 sdk/bin/dartdevc --dart-sdk-summary  ...

exit code:
0

--- Command "chrome" (took 761ms):
...

Runtime error:
Expect.throws(Providing type arguments to a non-generic tearoff should throw go NSM.): Unexpected 'got type arguments to non-generic function () => void, got <class String extends core.Object {
    static fromCharCodes(charCodes, start, end) {
      if (start === void 0) start = 0;
      if (end === void 0) end = null;
      if (_interceptors.JSArray.is(charCodes)) {
        return core.String._stringFromJSArray(JSArrayOfint()._check(charCodes), start, end);
      }
      if (_native_typed_data.NativeUint8List.is(charCodes)) {
        return core.String._stringFromUint8List(charCodes, start, end);
      }
      return core.String._stringFromIterable(charCodes, start, end);
    }
    static fromCharCode(charCode) {
      return _js_helper.Primitives.stringFromCharCode(charCode);
    }
    static fromEnvironment(name, opts) {
      let defaultValue = opts && 'defaultValue' in opts ? opts.defaultValue : null;
      dart.throw(new core.UnsupportedError.new('String.fromEnvironment can only be used as a const constructor'));
    }
    static _stringFromJSArray(list, start, endOrNull) {
      let len = list[$length];
      let end = core.RangeError.checkValidRange(start, endOrNull, len);
      if (dart.notNull(start) > 0 || dart.notNull(end) < len) {
        list = JSArrayOfint()._check(list[$sublist](start, end));
      }
      return _js_helper.Primitives.stringFromCharCodes(list);
    }
    static _stringFromUint8List(charCodes, start, endOrNull) {
      let len = charCodes[$length];
      let end = core.RangeError.checkValidRange(start, endOrNull, len);
      return _js_helper.Primitives.stringFromNativeUint8List(charCodes, start, end);
    }
    static _stringFromIterable(charCodes, start, end) {
      if (dart.notNull(start) < 0) dart.throw(new core.RangeError.range(start, 0, charCodes[$length]));
      if (end != null && dart.notNull(end) < dart.notNull(start)) {
        dart.throw(new core.RangeError.range(end, start, charCodes[$length]));
      }
      let it = charCodes[$iterator];
      for (let i = 0; i < dart.notNull(start); i++) {
        if (!dart.test(it.moveNext())) {
          dart.throw(new core.RangeError.range(start, 0, i));
        }
      }
      let list = JSArrayOfint().of([]);
      if (end == null) {
        while (dart.test(it.moveNext()))
          list[$add](it.current);
      } else {
        for (let i = start; dart.notNull(i) < dart.notNull(end); i = dart.notNull(i) + 1) {
          if (!dart.test(it.moveNext())) {
            dart.throw(new core.RangeError.range(end, start, i));
          }
          list[$add](it.current);
        }
      }
      return _js_helper.Primitives.stringFromCharCodes(JSArrayOfint()._check(list));
    }
  }> expected none.'
Error
    at Object.dart.throw (http://127.0.0.1:46632/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4909:29)
    at Object.dart.throwTypeError (http://127.0.0.1:46632/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:3632:15)
    at Object.dart._checkAndCall (http://127.0.0.1:46632/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4704:12)
    at Object.dart.dgcall (http://127.0.0.1:46632/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4718:17)
    at expect$.Expect.throwsNoSuchMethodError.dart.fn (http://127.0.0.1:46632/root_dart/out/ReleaseX64/generated_compilations/dartdevc-strong/tests_language_2_no_such_method_tearoff_fta_test/no_such_method_tearoff_fta_test.js:18:12)
    at Function.throws (http://127.0.0.1:46632/root_dart/out/ReleaseX64/gen/utils/dartdevc/pkg/expect.js:366:9)
    at Function.throwsNoSuchMethodError (http://127.0.0.1:46632/root_dart/out/ReleaseX64/gen/utils/dartdevc/pkg/expect.js:396:21)
    at no_such_method_tearoff_fta_test.main (http://127.0.0.1:46632/root_dart/out/ReleaseX64/generated_compilations/dartdevc-strong/tests_language_2_no_such_method_tearoff_fta_test/no_such_method_tearoff_fta_test.js:17:20)
    at dartMainRunner (http://127.0.0.1:46632/root_dart/tools/testing/dart/test_controller.js:324:5)
    at http://127.0.0.1:46632/root_build/generated_tests/dartdevc-chrome-strong/tests_language_2_no_such_method_tearoff_fta_test/test.html?crossOriginPort=38539:76:3
    at Object.execCb (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1696:33)
    at Module.check (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:883:51)
    at Module.<anonymous> (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1139:34)
    at http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:134:23
    at http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1189:21
    at each (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:59:31)
    at Module.emit (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1188:17)
    at Module.check (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:938:30)
    at Module.<anonymous> (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1139:34)
    at http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:134:23
    at http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1189:21
    at each (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:59:31)
    at Module.emit (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1188:17)
    at Module.check (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:938:30)
    at Module.<anonymous> (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1139:34)
    at http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:134:23
    at http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1189:21
    at each (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:59:31)
    at Module.emit (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1188:17)
    at Module.check (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:938:30)
    at Module.enable (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1176:22)
    at Module.init (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:788:26)
    at callGetModule (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1203:63)
    at Object.completeLoad (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1590:21)
    at HTMLScriptElement.onScriptLoad (http://127.0.0.1:46632/root_dart/third_party/requirejs/require.js:1717:29)
at Object.dart.throw (http://127.0.0.1:46632/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4909:29)
    at Function._fail (http://127.0.0.1:46632/root_dart/out/ReleaseX64/gen/utils/dartdevc/pkg/expect.js:421:17)
    at Function.throws (http://127.0.0.1:46632/root_dart/out/ReleaseX64/gen/utils/dartdevc/pkg/expect.js:371:27)
    at Function.throwsNoSuchMethodError (http://127.0.0.1:46632/root_dart/out/ReleaseX64/gen/utils/dartdevc/pkg/expect.js:396:21)
    at no_such_method_tearoff_fta_test.main (http://127.0.0.1:46632/root_dart/out/ReleaseX64/generated_compilations/dartdevc-strong/tests_language_2_no_such_method_tearoff_fta_test/no_such_method_tearoff_fta_test.js:17:20)

exit code:
0

--- To debug locally, run:
...

--- Re-run this test:
python tools/test.py -m release -c dartdevc --strong language_2/no_such_method_tearoff_fta_test


[00:07 | 100% | +    0 | -    1]
[00:07 | 100% | +    0 | -    1]

```

I'll mark it in the status file with this issue number.

**Comment by jmesserly** [comment]
Great catch! We chose TypeError tentatively, but it was supposed to be changed to a noSuchMethod call once Invocation had typeArguments: https://github.com/dart-lang/sdk/issues/30095#issuecomment-313611320

(Violating the `extends` clause of the type parameter should still be a TypeError, presumably)

**Comment by jmesserly** [comment]
CC @leafpetersen @lrhn 

At one point we thought arity mismatches (either argument or type arguments) should be TypeErrors:
```
  // TODO(leafp): throw a type error (rather than NSM)
  // if the arity matches but the types are wrong.
```
... not sure how we're currently feeling for Dart 2. Calling nSM will degrade the error reporting somewhat, although it does increase possibility for custom handling/mocking. Thoughts? I'm happy to fix either way.

If nothing else, it would be nice if arguments & type arguments were consistent in how they handle arity mismatches. Also if we keep the error above, we need to print the type name correctly, rather than the raw JS typerep object :). The error should say something like: `type arguments <String> passed to non-generic function of type: () => void`

**Comment by jmesserly** [comment]
EDIT: disregard above, I'm confusing myself, sorry for the ping everyone! :)

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/36488
