### ISSUE TITLE
whole_program_test and bootstrap_test fail on Windows bots

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31924]
The buildbots analyzer-win7-release-be and analyzer-win7-release-strong-be are currently showing failures with the tests `pkg/front_end/test/whole_program_test` and `pkg/front_end/test/fasta/bootstrap_test`.  Sample log output:

```
FAILED: none-vm-checked release_x64 pkg/front_end/test/fasta/bootstrap_test
Expected: Pass Slow
Actual: RuntimeError
--- Command "vm" (took 03.000207s):
set DART_CONFIGURATION=ReleaseX64 & out\ReleaseX64\dart-sdk\bin\dart.exe --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=E:\b\build\slave\analyzer-win7-release-be\build\sdk\.packages E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\front_end\test\fasta\bootstrap_test.dart
exit code:
255
stdout:
unittest-suite-wait-for-done
Unhandled exception:
FileSystemException(uri=e:.packages; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:31:7)
#1      ProcessedOptions._findPackages.checkInDir (package:front_end/src/base/processed_options.dart:474:28)
<asynchronous suspension>
#2      ProcessedOptions._findPackages (package:front_end/src/base/processed_options.dart:479:37)
<asynchronous suspension>
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:422:30)
<asynchronous suspension>
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:355:28)
<asynchronous suspension>
#5      CompileTask.buildOutline (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/tool/_fasta/entry_points.dart:131:51)
<asynchronous suspension>
#6      CompileTask.compile (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/tool/_fasta/entry_points.dart:163:39)
<asynchronous suspension>
#7      compile.<anonymous closure> (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/tool/_fasta/entry_points.dart:104:25)
<asynchronous suspension>
#8      withGlobalOptions.<anonymous closure> (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/tool/_fasta/command_line.dart:364:13)
#9      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:96:35)
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     runZoned (dart:async/zone.dart:1501)
#13     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:96:14)
#14     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:107:41)
#15     withGlobalOptions (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/tool/_fasta/command_line.dart:357:26)
#16     compile (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/tool/_fasta/entry_points.dart:97:18)
<asynchronous suspension>
#17     compileEntryPoint (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/tool/_fasta/entry_points.dart:55:11)
<asynchronous suspension>
#18     main (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
stderr:
Unhandled exception:
Compilation failed.
#0      runCompiler (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/test/fasta/bootstrap_test.dart:61:5)
<asynchronous suspension>
#1      main (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/test/fasta/bootstrap_test.dart:29:11)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
--- Re-run this test:
python tools/test.py -m release -c none -r vm --checked -t 120 --use-sdk --builder-tag win7 pkg/front_end/test/fasta/bootstrap_test
FAILED: none-vm-checked release_x64 pkg/front_end/test/whole_program_test
Expected: Slow Pass
Actual: RuntimeError
--- Command "vm" (took 03.000454s):
set DART_CONFIGURATION=ReleaseX64 & out\ReleaseX64\dart-sdk\bin\dart.exe --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=E:\b\build\slave\analyzer-win7-release-be\build\sdk\.packages E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\front_end\test\whole_program_test.dart
exit code:
255
stdout:
unittest-suite-wait-for-done
Running:
    E:\b\build\slave\analyzer-win7-release-be\build\sdk\out\ReleaseX64\dart-sdk\bin\dart.exe --packages=E:\b\build\slave\analyzer-win7-release-be\build\sdk\.packages -c E:\b\build\slave\analyzer-win7-release-be\build\sdk\pkg\front_end\tool\_fasta\compile.dart --platform=E:\b\build\slave\analyzer-win7-release-be\build\sdk\out\ReleaseX64\dart-sdk\lib\_internal\vm_platform.dill --output=C:\Users\CHROME~2\AppData\Local\Temp\whole_programd9e4b91e-fba9-11e7-9a1f-005056030018\hello.dart.dill --packages=E:\b\build\slave\analyzer-win7-release-be\build\sdk\.packages --verify C:\Users\CHROME~2\AppData\Local\Temp\whole_programd9e4b91e-fba9-11e7-9a1f-005056030018\hello.dart
Output:
    c:: Error: Unexpected input: c:    
ExitCode: 1
Took:     0:00:03.131637
stderr:
Unhandled exception:
Compilation of hello.dart failed.
#0      run (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/test/whole_program_test.dart:110:5)
<asynchronous suspension>
#1      runCompiler (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/test/whole_program_test.dart:67:9)
<asynchronous suspension>
#2      main (file:///E:/b/build/slave/analyzer-win7-release-be/build/sdk/pkg/front_end/test/whole_program_test.dart:43:11)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
--- Re-run this test:
python tools/test.py -m release -c none -r vm --checked -t 120 --use-sdk --builder-tag win7 pkg/front_end/test/whole_program_test
```

As near as I can tell, these tests started failing with beda5c3e620ab6717242823ba4a5c8343b5c733c.

I will follow up with a CL that marks these tests as failing in the status file.

**Comment by whesse** [comment]
This is already done, and the information is added to issue #31902
