### ISSUE TITLE
Crash in analyzer run from IDEA.

### ISSUE THREAD

**Issue by GoHash-Include** [dart-lang/sdk#31922]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4127.27`
- `1.25.0-dev.11.0`
- `IC-173.4127.27, JRE 1.8.0_152-release-1024-b8x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1280x800`

# Exception

Please append the contents of:
file:///private/var/folders/bp/kchprjjs7nlfcjjpsf61fy_00000gn/T/report.txt

```
Dart analysis server, SDK version 1.25.0-dev.11.0, server version 1.18.4, FATAL error: Failed to handle request: {id: 283, method: edit.importElements, params: {file: /Users/mbp13i5/newTestFlutter/mathaqi_a_app/lib/RestHelper.dart, elements: [{path: /Users/mbp13i5/newTestFlutter/flutter/bin/cache/pkg/sky_engine/lib/convert/convert.dart, prefix: , elements: [JSON]}]}, clientRequestTime: 1516164178863}
NoSuchMethodError: The getter 'source' was called on null.
Receiver: null
Tried calling: source
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      ImportElementsComputer._matches (package:analysis_server/src/computer/import_elements_computer.dart:378)
#3      ImportElementsComputer._findMatchingImports (package:analysis_server/src/computer/import_elements_computer.dart:310)
#4      ImportElementsComputer.createEdits.<anonymous closure> (package:analysis_server/src/computer/import_elements_computer.dart:69)
#5      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:50)
<asynchronous suspension>
#6      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:47)
#7      ImportElementsComputer.createEdits (package:analysis_server/src/computer/import_elements_computer.dart:65)
<asynchronous suspension>

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/37083
