### ISSUE TITLE
Cannot read stdin.echoMode property in some cases.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#31932]
Here is a simple dart test example:
```dart
import "dart:io";
main(List<String> args) {
  print(stdin.echoMode);
}
```
I run it in my Far Manager terminal on Windows and get `true` in stdout. This is expected behavior.
However, if I start it from Idea IDE I always get the following error:
```
D:\DART\sdk\out\Release-x64\dart-sdk\bin\dart.exe --ignore-unrecognized-flags --checked --pause_isolates_on_start --enable-vm-service:51962 --trace_service_pause_events D:\DART\sdk\tests\co19\LibTest\io\Stdin\t.dart
Observatory listening on http://127.0.0.1:51962/
Unhandled exception:
StdinException: Error getting terminal echo mode, OS Error: The handle is invalid.
, errno = 6
#0      Stdin.echoMode (dart:io-patch/stdio_patch.dart:70)
#1      main (file:///D:/DART/sdk/tests/co19/LibTest/io/Stdin/t.dart:4:21)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

Process finished with exit code 255
```
I believe such a behaviour should be either fixed or specified in API Spec somehow.

Please note:

1. The following test example started both from terminal and Idea works OK for me, i.e. I am able to pipe some text into child process stdin and print it into stdout:
```dart
import "../../../Utils/expect.dart";
import "dart:io";

run_process() { stdout.write(stdin.readLineSync()); }

run_main() async {
  String executable = Platform.resolvedExecutable;
  String eScript = Platform.script.toString();
  int called = 0;
  await Process.run("echo Hello!", ["|", executable, eScript, "test"],
      runInShell: true).then((ProcessResult results) {
    print(results.stdout);
    called++;
  });
  Expect.equals(1, called);
}

main(List<String> args) {
  if(args.length > 0)
    run_process();
  else {
    run_main();
  }
}

```
Sample output in console is:
```
D:\DART\sdk\out\Release-x64\dart-sdk\bin\dart.exe --ignore-unrecognized-flags --checked --enable-vm-service:52782 --trace_service_pause_events D:\DART\sdk\tests\co19\LibTest\io\Stdin\echoMode_A01_t01.dart
Observatory listening on http://127.0.0.1:52782/
Hello! 

Process finished with exit code 0
```
2. However, similar example fails, i.e. I am not able to print echoMode property of the child stdin under the same conditions:
```
D:\DART\sdk\out\Release-x64\dart-sdk\bin\dart.exe --ignore-unrecognized-flags --checked --enable-vm-service:52882 --trace_service_pause_events D:\DART\sdk\tests\co19\LibTest\io\Stdin\echoMode_A01_t01.dart
Observatory listening on http://127.0.0.1:52882/
Unhandled exception:

, errno = 6
#0      Stdin.echoMode (dart:io-patch/stdio_patch.dart:70)
#1      run_process (file:///D:/DART/sdk/tests/co19/LibTest/io/Stdin/echoMode_A01_t01.dart:17:22)
#2      main (file:///D:/DART/sdk/tests/co19/LibTest/io/Stdin/echoMode_A01_t01.dart:34:5)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

Process finished with exit code 0
```

**Comment by rmacnak-google** [comment]
@zanderso I'm guessing this failure is because stdin is not a terminal.

**Comment by natebosch** [comment]
Yeah, this will only work if stdin is a terminal. I think we can probably close this issue if we document that on the property.

Note that our `hasTerminal` property is also [currently broken](https://github.com/dart-lang/sdk/issues/34213) if `stdin` is a character device but not a TTY.
