### ISSUE TITLE
Analyzer crashes if you "git clean"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#31961]
Steps to reproduce, from a flutter repo:

```
# in one terminal, at the root of the flutter repo
flutter update-packages
flutter analyze --watch --flutter-repo
# in a second, once the analysis is ready, at the root of the flutter repo
git clean -xffd
```

The analyzer promptly starts repeating long stack traces over and over. When I hit ^C, the last few stack traces were all the same:

```
Error from the analysis server: Analysis failed: /home/ianh/dev/flutter/packages/flutter/lib/src/material/input_border.dart
NoSuchMethodError: The getter 'units' was called on null.
Receiver: null
Tried calling: units
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      LibraryElementInDependency._makeUnitElement (package:analyzer/src/summary/link.dart:3952)
#2      LibraryElementForLink.units (package:analyzer/src/summary/link.dart:3757)
#3      LibraryElementForLink.getContainedName.<anonymous closure> (package:analyzer/src/summary/link.dart:3796)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:275)
#5      LibraryElementForLink.getContainedName (package:analyzer/src/summary/link.dart:3795)
#6      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5352)
#7      TypeProviderForLink.objectType (package:analyzer/src/summary/link.dart:5321)
#8      ClassElementForLink_Class._computeInterfaceType (package:analyzer/src/summary/link.dart:740)
#9      ClassElementForLink_Class.supertype (package:analyzer/src/summary/link.dart:659)
#10     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:301)
#11     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:88)
#12     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1330)
#13     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3909)
#14     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3645)
#15     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3567)
#16     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:149)
#17     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:168)
#18     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3610)
#19     Linker.link (package:analyzer/src/summary/link.dart:4134)
#20     relink (package:analyzer/src/summary/link.dart:132)
#21     link (package:analyzer/src/summary/link.dart:113)
#22     new LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:119)
#23     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#24     new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:118)
#25     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#26     new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:56)
#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1373)
<asynchronous suspension>
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1205)
<asynchronous suspension>
#29     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1010)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1887)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1830)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:386)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#37     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:436)
#38     _rootRun (dart:async/zone.dart:1126)
#39     _CustomZone.run (dart:async/zone.dart:1023)
#40     runZoned (dart:async/zone.dart:1501)
#41     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:476)
#42     Driver.start (package:analysis_server/src/server/driver.dart:435)
#43     main (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

cc @devoncarew @pq

**Comment by Hixie** [comment]
Heh. I really didn't realise I'd filed that twice, my bad!

I run into this all the time.

**Comment by stereotype441** [comment]
There hasn’t been activity on this issue for two years, so I’m assuming it was addressed.  Please feel to re-open if you're still seeing this.
