### ISSUE TITLE
CFE crashes with CompilerOptions.embedSourceText=false + compile time error

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#32007]
Seems like the source is removed too early.

E.g., with CompilerOptions.embedSourceText=true

```
topaz/runtime/dart_runner/examples/hello_dart/bin/hello_dart.dart:7:1: Error: Unexpected token 'void'.
void void main(List<String> args) {
^
```

with CompilerOptions.embedSourceText=false

```
Crash when formatting: [UnexpectedToken] Unexpected token 'void'.
RangeError (index): Invalid value: Valid value range is empty: 276
#0      _StringBase.[] (dart:core-patch/dart:core/string_patch.dart:233)
#1      Source.getTextLine (package:kernel/ast.dart:5773)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27)
#3      formatInternal (package:front_end/src/fasta/command_line_reporting.dart:71)
#4      format (package:front_end/src/fasta/command_line_reporting.dart:205)
#5      report (package:front_end/src/fasta/command_line_reporting.dart:187)
#6      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:195)
#7      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:62)
#8      Loader.addMessage (package:front_end/src/fasta/loader.dart:238)
#9      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:197)
#10     LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:84)
#11     OutlineBuilder.addCompileTimeError (package:front_end/src/fasta/source/outline_builder.dart:1059)
#12     StackListener.handleRecoverableError (package:front_end/src/fasta/source/stack_listener.dart:337)
#13     Parser.reportRecoverableErrorWithToken (package:front_end/src/fasta/parser/parser.dart:6354)
#14     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2913)
#15     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:453)
#16     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:307)
#17     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:187)
<asynchronous suspension>
#18     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:162)
<asynchronous suspension>
#19     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:226)
<asynchronous suspension>
#20     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:90)
<asynchronous suspension>
#21     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:96)
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:96)
#26     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:48)
<asynchronous suspension>
#27     main (file:///usr/local/google/home/rmacnak/topaz2/topaz/runtime/dart_runner/kernel/compiler.dart:90)
<asynchronous suspension>
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:276)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)

Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 276
#0      _StringBase.[] (dart:core-patch/dart:core/string_patch.dart:233)
#1      Source.getTextLine (package:kernel/ast.dart:5773)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27)
#3      formatInternal (package:front_end/src/fasta/command_line_reporting.dart:71)
#4      format (package:front_end/src/fasta/command_line_reporting.dart:205)
#5      report (package:front_end/src/fasta/command_line_reporting.dart:187)
#6      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:195)
#7      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:62)
#8      Loader.addMessage (package:front_end/src/fasta/loader.dart:238)
#9      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:197)
#10     LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:84)
#11     OutlineBuilder.addCompileTimeError (package:front_end/src/fasta/source/outline_builder.dart:1059)
#12     StackListener.handleRecoverableError (package:front_end/src/fasta/source/stack_listener.dart:337)
#13     Parser.reportRecoverableErrorWithToken (package:front_end/src/fasta/parser/parser.dart:6354)
#14     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2913)
#15     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:453)
#16     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:307)
#17     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:187)
<asynchronous suspension>
#18     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:162)
<asynchronous suspension>
#19     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:226)
<asynchronous suspension>
#20     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:90)
<asynchronous suspension>
#21     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:96)
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:96)
#26     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:48)
<asynchronous suspension>
#27     main (file:///usr/local/google/home/rmacnak/topaz2/topaz/runtime/dart_runner/kernel/compiler.dart:90)
<asynchronous suspension>
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:276)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
ninja: build stopped: cannot make progress due to previous errors.
```

**Comment by mraleph** [comment]
Fixed by 32277cc95982349c476cff9a37957eb6f6ceff2b
