### ISSUE TITLE
Dart 2 runtime error while registering File.openRead onError callback with runZoned

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#32015]
```
Dart VM version: 2.0.0-edge.ec7435945d8998e712b1a086a2a4917895e3a86c
```
**foo.dart**
```dart
import 'dart:async';
import 'dart:io';

void main() {
  runZoned(run);
}

void run() {
  new File('tmp')
    ..createSync()
    ..openRead().listen((data) {
      print('Data: $data');
    }, onError: (e, st) {
      print('Error: $e');
      print('StackTrace:\n$st');
    });
}
```

```
$  ~/dart-sdk/sdk/pkg/vm/tool/dart2 foo.dart
Data: []
Error: type '(Object, [StackTrace]) => void' is not a subtype of type '(Object, StackTrace) => FutureOr<RandomAccessFile>'
StackTrace:
#0      _registerErrorHandler (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/async_error.dart:20:66)
#1      _Future.catchError (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/future_impl.dart:257:17)
#2      _FileStream._closeFile (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/io/file_impl.dart:65:25)
#3      _FileStream._readBlock.<anonymous closure> (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/io/file_impl.dart:105:9)
#4      _rootRunUnary (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/zone.dart:1134:38)
#5      _CustomZone.runUnary (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/zone.dart:1031:19)
#6      _FutureListener.handleValue (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/future_impl.dart:129:18)
#7      _Future._propagateToListeners.handleValueCallback (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/future_impl.dart:633:45)
#8      _Future._propagateToListeners (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/future_impl.dart:662:32)
#9      _Future._completeWithValue (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/future_impl.dart:477:5)
#10     _Future._asyncComplete.<anonymous closure> (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/future_impl.dart:507:7)
#11     _rootRun (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/zone.dart:1126:13)
#12     _CustomZone.run (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/zone.dart:1023:19)
#13     _CustomZone.bindCallback.<anonymous closure> (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/zone.dart:949:23)
#14     _microtaskLoop (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/schedule_microtask.dart:41:21)
#15     _startMicrotaskLoop (file:///home/alexey/dart-sdk/sdk/out/ReleaseX64/patched_sdk/lib/async/schedule_microtask.dart:50:5)
#16     _runPendingImmediateCallback (dart:isolate:1098:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate:1148:5)

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
There are several issues compounding this issue.

One is that `RandomAccessFile.close` returns a `Future<RandomAccessFile>`. It should just return a `Future<void>` (when possible, `Future` until then). We don't do method chaining in Dart by returning `this`.

The code that triggers the actual error is:
```dart
    _openedFile.close().catchError(_controller.addError).whenComplete(done);
```
Here the `_controller.addError` has type `void Function(Object, [StackTrace])`.
The  `catchError` method is only declared as accepting a `Function` because it has to accept both an argument of type `FutureOr<T> Function(Object)` or of type `FutureOr<T> Function(Object, StacktTrace)`. So, static checking fails to catch that the argument is not assignable to the expected type because of the incompatible return type.

If the close method returned `Future<void>`, any return type would be valid.

That is: The bug is in the platform library code, it is not Dart 2 compatible, and it wasn't caught by analysis because we use `Function` as argument type.

**Comment by lexaknyazev** [comment]
Just curious, why does the same code run fine with Dart 2 without `runZoned`?

**Comment by lexaknyazev** [comment]
CL: https://dart-review.googlesource.com/c/sdk/+/44060
