### ISSUE TITLE
Exception from analysis server when opening analysis server code

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32033]
Hit this when opening the analysis server folder (pkg/analysis_server) to bump the version number (cc @bwilkerson). This is using latest stable SDK (1.24.3) which is getting on a bit now; I'm not sure whether the latest code is expected to still work with it.

### Versions

- Dart SDK 1.24.3
- Visual Studio Code 1.19.3
- Dart Code 2.7.3

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=Dart-Code.dart-code
--client-version=2.7.3
```

### Exception

Analysis failed: /Users/danny/Dev/Google/sdk/pkg/analysis_server/benchmark/integration/local_runner.dart context: exception_20180202_155513_773

```text
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1096)
#1      CompilationUnitElementForLink.resolveTypeRef.getTypeArgument (package:analyzer/src/summary/link.dart:1103)
#2      new List.generate (dart:core/list.dart:142)
#3      ClassElementForLink_Class.buildType (package:analyzer/src/summary/link.dart:647)
#4      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1113)
#5      VariableElementForLink.declaredType (package:analyzer/src/summary/link.dart:5196)
#6      VariableElementForLink.type (package:analyzer/src/summary/link.dart:5287)
#7      PropertyAccessorElementForLink_Variable.returnType (package:analyzer/src/summary/link.dart:4548)
#8      PropertyAccessorElementForLink_Variable.asStaticType (package:analyzer/src/summary/link.dart:4501)
#9      ExprTypeComputer._doPushReference (package:analyzer/src/summary/link.dart:2485)
#10     ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2073)
#11     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:4957)
#12     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:4808)
#13     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#14     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#15     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5226)
#16     FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2700)
#17     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:673)
#18     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1308)
#19     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3672)
#20     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3408)
#21     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3330)
#22     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#23     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#24     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#25     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#26     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#27     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#28     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#29     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#30     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#31     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#32     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3373)
#33     Linker.link (package:analyzer/src/summary/link.dart:3897)
#34     relink (package:analyzer/src/summary/link.dart:132)
#35     link (package:analyzer/src/summary/link.dart:113)
#36     new LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:116)
#37     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#38     new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:115)
#39     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#40     new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:53)
#41     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1092)
#42     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:989)
#43     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#44     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#45     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:854)
<asynchronous suspension>
#46     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#47     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#48     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#49     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#50     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#51     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#52     _rootRun (dart:async/zone.dart:1120)
#53     _CustomZone.run (dart:async/zone.dart:1001)
#54     runZoned (dart:async/zone.dart:1467)
#55     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#56     Driver.start (package:analysis_server/src/server/driver.dart:473)
#57     main (file:///Users/whesse/dart/sdk/pkg/analysis_server/bin/server.dart:12)
#58     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
I'm not aware of any changes to the analysis server code base that would prevent it from being analyzed by the latest stable build, but the latest stable build is very old and many of the bugs in it have been fixed. I would encourage you to move to the latest 2.0-dev build (I think we're at 20 as of today) or even build from bleeding edge. You'll likely need to build bleeding edge anyway if you start making more invasive changes to the analyzer/server code bases in order to test those changes.

**Comment by DanTup** [comment]
I can't repro this with `2.0.0-dev.20.0` so I guess this can be closed (unless you think the bugs are serious and plan to do more pre-2.0 stable releases).

>  You'll likely need to build bleeding edge anyway if you start making more invasive changes to the analyzer/server code bases in order to test those changes.

Yeah, I figured this might be the case so expect to have to get this set up soon! :-)

**Comment by bwilkerson** [comment]
I don't believe that we're planning to have any more pre-2.0 stable releases, so I'm closing this.
