### ISSUE TITLE
bug related to needs rti in closures

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32053]
This program prints `C<int>` in the old compiler, but crashes with use-kernel:

```dart
class A<T> {
  final f;
  A() : f = (() => new C<T>());
}

class C<T> {}

main() => print(new A<int>().f().runtimeType);
```

The error is of the form:
```
nternal Error: Runtime type information not available for type_variable_local(A.T) in (local(A.#)) for j:closure_call(A_closure.call).
  A() : f = (() => new C<T>());
  ^
#0      failedAt (pkg/compiler/lib/src/diagnostics/invariant.dart:55:3)
#1      LocalsHandler.readLocal (pkg/compiler/lib/src/ssa/locals_handler.dart:328:11)
#2      TypeBuilder.addTypeVariableReference.readAsParameter (pkg/compiler/lib/src/ssa/type_builder.dart:122:12)
#3      TypeBuilder.addTypeVariableReference (pkg/compiler/lib/src/ssa/type_builder.dart:133:31)
#4      TypeBuilder.analyzeTypeArgument (pkg/compiler/lib/src/ssa/type_builder.dart:215:14)
#5      KernelSsaGraphBuilder._addTypeArguments (pkg/compiler/lib/src/ssa/builder_kernel.dart:3025:30)
#6      KernelSsaGraphBuilder.visitConstructorInvocation (pkg/compiler/lib/src/ssa/builder_kernel.dart:4294:5)
```

**Comment by sigmundch** [comment]
Some additional notes:
* the original program where I found this doesn't actually use .runtimeType on the result of the closure, but we conservatively assume that we need it (it is used somewhere else in the program).
* with '--disable-rti-optimization' the problem goes away.

**Comment by sigmundch** [comment]
I believe I found the issue: when we translate FE rti needs to the backend, we simply translate the set of classes that need RTI, but we dropped the extra logic we need to decide whether to preserve RTI (like when runtimeType is used).

**Comment by sigmundch** [comment]
fixed in https://github.com/dart-lang/sdk/commit/2847a8b3afea24b6607c3e0287b344f8123ca2ad
