### ISSUE TITLE
Crash in dart2js

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#32059]
With CL https://dart-review.googlesource.com/c/sdk/+/32541 landed, some tests crash in the following way (see, e.g., https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fdart2js-linux-d8-minified-3-5-be%2F9821%2F%2B%2Frecipes%2Fsteps%2Fdart2js-with-kernel-d8_tests%2F0%2Fstdout):
```
FAILED: dart2js-d8 release_x64 corelib_2/json_map_test
Expected: Pass
Actual: Crash
Unexpected compile error.
--- Command "dart2js" (took 01.000841s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart2js --sync-async --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --minify --use-kernel --strong --packages=/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/.packages /b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/tests/corelib_2/json_map_test.dart --out=/b/build/slave/dart2js-linux-d8-minified-2-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-strong-minified-sdk/tests_corelib_2_json_map_test/out.js
exit code:
-10
stdout:
../../../dart-sdk-linux-be/build/sdk/sdk/lib/internal/iterable.dart@8271+1:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.
When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.
The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.
Please include the following information:
* the name and version of your operating system,
* the Dart SDK build number (2.0.0-edge.b7a60e7ad97a5751af41d19822d13aba9368c855), and
* the entire message you see here (including the full stack trace
  below as well as the source location above).
The compiler crashed: Wrong number of template arguments, given 2, expected 1
#0      Template.instantiate (package:js_ast/src/template.dart:105)
#1      SsaCodeGenerator.visitForeignCode (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:2112)
#2      HForeignCode.accept (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2129)
#3      SsaCodeGenerator.visit (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:711)
#4      SsaCodeGenerator.visitExpression (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:717)
#5      SsaCodeGenerator.define (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:683)
#6      SsaCodeGenerator.iterateBasicBlock (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1373)
#7      SsaCodeGenerator.enterSubGraph (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1241)
#8      SsaCodeGenerator.visitSubGraph (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:429)
#9      SsaCodeGenerator.visitSubGraphInfo (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:833)
#10     HSubGraphBlockInformation.accept (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/nodes.dart:3344)
#11     SsaCodeGenerator.generateStatements (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:515)
#12     SsaCodeGenerator.generateStatementsInNewBlock (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:526)
#13     SsaCodeGenerator.generateIf (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1640)
#14     SsaCodeGenerator.visitIf (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1677)
#15     HIf.accept (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2473)
#16     SsaCodeGenerator.visit (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:711)
#17     SsaCodeGenerator.iterateBasicBlock (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1378)
#18     SsaCodeGenerator.enterSubGraph (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1241)
#19     SsaCodeGenerator.visitSubGraph (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:429)
#20     SsaCodeGenerator.visitGraph (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:420)
#21     SsaCodeGeneratorTask.generateMethod.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:118)
#22     CompilerTask.measure (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63)
#23     SsaCodeGeneratorTask.generateMethod (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:101)
#24     SsaCodeGeneratorTask.generateCode (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:70)
#25     SsaFunctionCompiler.compile (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/ssa.dart:47)
#26     JavaScriptBackend.codegen (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/js_backend/backend.dart:848)
#27     KernelCodegenWorkItem.run (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:79)
#28     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:784)
#29     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#30     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:784)
#31     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#32     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:782)
#33     CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:1156)
#34     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:780)
#35     EnqueuerStrategy.processWorkItem (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/enqueue.dart:511)
#36     CodegenEnqueuer.forEach (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:224)
#37     Compiler.emptyQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:776)
#38     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#39     Compiler.emptyQueue (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:775)
#40     Compiler.processQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:797)
#41     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#42     Compiler.processQueue (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:794)
#43     Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:640)
#44     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#45     Compiler.compileLoadedLibraries (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:534)
#46     Compiler.runInternal (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:488)
<asynchronous suspension>
#47     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:313)
#48     new Future.sync (dart:async/future.dart:222)
#49     Compiler.run.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:313)
#50     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#51     Compiler.run (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:310)
#52     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/apiimpl.dart:265)
#53     _RootZone.runUnary (dart:async/zone.dart:1381)
#54     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#55     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#56     _Future._propagateToListeners (dart:async/future_impl.dart:662)
#57     _Future._completeWithValue (dart:async/future_impl.dart:477)
#58     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#61     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:112)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
--- Re-run this test:
python tools/test.py -m release -c dart2js -r d8 --strong --minified --dart2js-with-kernel --use-sdk --dart2js-batch --reset-browser-configuration corelib_2/json_map_test
Done dart2js-d8 release_x64 corelib_2/json_map_test: fail
```
I'm not sure what the error source is yet, but in any case, it should not make the compiler crash.

**Comment by sigmundch** [comment]
(.status shows this test is now working)
