### ISSUE TITLE
Implement instantiate-to-bounds in the VM

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#32076]
When the VM reads the bound of a type parameter on a local function from kernel, it does it using this code, which ignores the actual type and always puts dynamic:

https://github.com/dart-lang/sdk/blob/cca7b4419da61592925bf9dbd31fab733b8b4d93/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc#L2573-L2578

This bug is caught by the test `language_2/generic_function_bounds_test` after the crash is fixed in https://dart-review.googlesource.com/c/sdk/+/39160

**Comment by sjindel-google** [comment]
It seems like this only a problem with bounds that reference type parameters from the same type parameter list, e.g.:
```
f<A extends C<A>>
```

In this case, until the bounds finalized, the type parameters will be substituted with `dynamic`, so
the bound will be finalized as `C<dynamic>`.

**Comment by sjindel-google** [comment]
I can't reproduce this problem.

Consider:
```
$ cat >test.dart <<EOF
class A<T> {}
class B implements A<B> {}
class C implements A<dynamic> {}

void main() {
  void test<T extends A<T>>() {}
  dynamic x = test;
  x<B>();
  x<C>();
}
EOF
$ pkg/vm/tool/dart2 test.dart
Unhandled exception:                                                                                                                                                                                                                                                                                                          
type 'C' is not a subtype of type 'A<C>' of 'T' where                                                                                                                                                                                                                                                                         
  C is from file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/test.dart                                                                                                                                                                                                                                                  
  A is from file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/test.dart                                                                                                                                                                                                                                                  
  C is from file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/test.dart                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                              
#0      main.test (file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/test.dart)                                                                                                                                                                                                                                          
#1      main (file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/test.dart:9:4)                                                                                                                                                                                                                                           
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)                                                                                                                                                                                                                                 
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12) 
```

The error with `generic_function_bounds_test.dart` seems to be the result of `dynamic` being used as the default for a dynamic generic function call without type arguments, where the corresponding type parameter has a bound stricter than dynamic. Here's a simple reproduction:

```
$ cat >test.dart <<EOF
void test<T extends num>() {}                                                                                                                                                                                                                                                                                                                              
void main() {
  (test as dynamic)();
}
$ pkg/vm/tool/dart2 test.dart
Unhandled exception:                                                                                                                                                                                                                                                                                                          
type 'dynamic' is not a subtype of type 'num' of 'T' where                                                                                                                                                                                                                                                                    
  num is from dart:core                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                              
#0      main (file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/test.dart:4:20)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by sjindel-google** [comment]
Related: #31581
