### ISSUE TITLE
New crash in SsaCodeGenerator.visitTypeInfoExpression

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/sdk#32092]
Repro with:

python tools/test.py -m release -c dart2js -r d8 --checked --strong corelib_2/splay_tree_from_iterable_test

Doesn't happen with the kernel front end.

The compiler crashed: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/dart:core/growable_array.dart:141)
#1      SsaCodeGenerator.visitTypeInfoExpression.<anonymous closure> (file:///usr/local/google/home/erikcorry/dart/sdk/pkg/compiler/lib/src/ssa/codegen.dart:3057)
#2      TypeRepresentationGenerator.visitTypeVariableType (file:///usr/local/google/home/erikcorry/dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:1629)
#3      ResolutionTypeVariableType.accept (file:///usr/local/google/home/erikcorry/dart/sdk/pkg/compiler/lib/src/elements/resolution_types.dart:248)
#4      TypeRepresentationGenerator.visit (file:///usr/local/google/home/erikcorry/dart/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:1618)

**Comment by ErikCorryGoogle** [comment]
We don't run --strong  without the kernel front end so this bug report is invalid - sorry!
