### ISSUE TITLE
Changes in dart2js-specific patch files for sdk break inference

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#32104]
[CL 39960](https://dart-review.googlesource.com/c/sdk/+/39960) makes changes to dart2js-specific patches for the sdk, namely it changes the patch factories from being redirecting factories to being non-redirecting factories.  The change breaks some inference expectations.

```bash
$ python tools/test.py -m release -c none -r vm -a ia32 --checked -t 120
--reset-browser-configuration dart2js/inference/inference1_test
Test configuration: none_vm_release_ia32_checked

FAILED: none-vm-checked release_ia32 dart2js/inference/inference1_test
Expected: Slow Pass
Actual: RuntimeError

--- Command "vm" (took 18.000011s):
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --enable_asserts
--enable_type_checks --ignore-unrecognized-flags
--packages=/usr/local/google/home/dmitryas/dart/sdk/.packages
/usr/local/google/home/dmitryas/dart/sdk/tests/compiler/dart2js/inference/inference1_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done
Data dir: tests/compiler/dart2js/inference/data/
----------------------------------------------------------------
Test: closure2.dart
Supporting libraries:
--from ast------------------------------------------------------
--from kernel---------------------------------------------------
----------------------------------------------------------------
Test: locals.dart
Supporting libraries:
--from ast------------------------------------------------------
--from kernel---------------------------------------------------
----------------------------------------------------------------
Test: while.dart
Supporting libraries:
--from ast------------------------------------------------------
--from kernel---------------------------------------------------
----------------------------------------------------------------
Test: expose_this_mask.dart
Supporting libraries:
--from ast------------------------------------------------------
--from kernel---------------------------------------------------
----------------------------------------------------------------
Test: as.dart
Supporting libraries:
--from ast------------------------------------------------------
--from kernel---------------------------------------------------
----------------------------------------------------------------
Test: assert.dart
Supporting libraries:
--from ast------------------------------------------------------
--from kernel---------------------------------------------------
----------------------------------------------------------------
Test: no_such_method3.dart
Supporting libraries:
--from ast------------------------------------------------------
memory:sdk/tests/compiler/dart2js_native/main.dart:31:12:
Warning: The method 'foo' is not defined for the class 'A'.
test5() => (a ? new A() : new B())
    // ignore: undefined_method
    . foo();

memory:sdk/tests/compiler/dart2js_native/main.dart:21:12:
Warning: The method 'foo' is not defined for the class 'A'.
test1() => new A()
    // ignore: undefined_method
    . foo();

--from kernel---------------------------------------------------
----------------------------------------------------------------
Test: closurization_static.dart
Supporting libraries:
--from ast------------------------------------------------------
--from kernel---------------------------------------------------
----------------------------------------------------------------
Test: global_field_closure2.dart
Supporting libraries:
--from ast------------------------------------------------------
--from kernel---------------------------------------------------
----------------------------------------------------------------
Test: switch2.dart
Supporting libraries:
--from ast------------------------------------------------------
--from kernel---------------------------------------------------
----------------------------------------------------------------
Test: const_closure5.dart
Supporting libraries:
--from ast------------------------------------------------------
--from kernel---------------------------------------------------
----------------------------------------------------------------
Test: list.dart
Supporting libraries:
--from ast------------------------------------------------------
memory:sdk/tests/compiler/dart2js_native/main.dart:103:1:
Info: HERE: Object: function(newUint8List) (PartialMethodElement)
 expected: element: newUint8List:Container([exact=NativeUint8List], element:
[exact=JSUInt31], length: 15)
 actual: element: newUint8List:Container([exact=NativeUint8List], element:
[exact=JSUInt31], length: null)
newUint8List() => new Uint8List(Class1.field);
^^^^^^^^^^^^^^
memory:sdk/tests/compiler/dart2js_native/main.dart:80:1:
Info: HERE: Object: function(newUint16List) (PartialMethodElement)
 expected: element: newUint16List:Container([exact=NativeUint16List], element:
[exact=JSUInt31], length: 12)
 actual: element: newUint16List:Container([exact=NativeUint16List], element:
[exact=JSUInt31], length: null)
newUint16List() => new Uint16List(_field3);
^^^^^^^^^^^^^^^
memory:sdk/tests/compiler/dart2js_native/main.dart:72:1:
Info: HERE: Object: function(newInt8List) (PartialMethodElement)
 expected: element: newInt8List:Container([exact=NativeInt8List], element:
[subclass=JSInt], length: 11)
 actual: element: newInt8List:Container([exact=NativeInt8List], element:
[subclass=JSInt], length: null)
newInt8List() => new Int8List(_field2);
^^^^^^^^^^^^^
memory:sdk/tests/compiler/dart2js_native/main.dart:56:1:
Info: HERE: Object: function(newInt16List) (PartialMethodElement)
 expected: element: newInt16List:Container([exact=NativeInt16List], element:
[subclass=JSInt], length: 9)
 actual: element: newInt16List:Container([exact=NativeInt16List], element:
[subclass=JSInt], length: null)
newInt16List() => new Int16List(9);
^^^^^^^^^^^^^^
memory:sdk/tests/compiler/dart2js_native/main.dart:54:1:
Info: HERE: Object: function(newFloat64List) (PartialMethodElement)
 expected: element: newFloat64List:Container([exact=NativeFloat64List],
element: [subclass=JSNumber], length: 8)
 actual: element: newFloat64List:Container([exact=NativeFloat64List], element:
[subclass=JSNumber], length: null)
newFloat64List() => new Float64List(8);
^^^^^^^^^^^^^^^^
memory:sdk/tests/compiler/dart2js_native/main.dart:52:1:
Info: HERE: Object: function(newFloat32List) (PartialMethodElement)
 expected: element: newFloat32List:Container([exact=NativeFloat32List],
element: [subclass=JSNumber], length: 7)
 actual: element: newFloat32List:Container([exact=NativeFloat32List], element:
[subclass=JSNumber], length: null)
newFloat32List() => new Float32List(7);
^^^^^^^^^^^^^^^^
--annotations diff [main.dart]-------------
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:typed_data';

main() {
  emptyList();
  nullList();
  constList();
  constNullList();
  intList();
  newList();
  newFixedList();
  newFilledList();
  newFloat32x4List();
  newInt32x4List();
  newFloat64x2List();
  newFloat32List();
  newFloat64List();
  newInt16List();
  newInt32List();
  newInt8List();
  newUint16List();
  newUint32List();
  newUint8ClampedList();
  newUint8List();
}

emptyList() => [];

constList() => const [];

nullList() => [null];

constNullList() => const [null];

intList() => [1, 2, 3];

newList() => new List();

newFixedList() => new List(2);

newFilledList() => new List.filled(3, '');

newFloat32x4List() => new Float32x4List(4);

newInt32x4List() => new Int32x4List(5);

newFloat64x2List() => new Float64x2List(6);

/*element: newFloat32List:Container([exact=NativeFloat32List], element:
[subclass=JSNumber], length: 7) | element:
newFloat32List:Container([exact=NativeFloat32List], element:
[subclass=JSNumber], length: null)*/newFloat32List() => new Float32List(7);

/*element: newFloat64List:Container([exact=NativeFloat64List], element:
[subclass=JSNumber], length: 8) | element:
newFloat64List:Container([exact=NativeFloat64List], element:
[subclass=JSNumber], length: null)*/newFloat64List() => new Float64List(8);

/*element: newInt16List:Container([exact=NativeInt16List], element:
[subclass=JSInt], length: 9) | element:
newInt16List:Container([exact=NativeInt16List], element: [subclass=JSInt],
length: null)*/newInt16List() => new Int16List(9);

////////////////////////////////////////////////////////////////////////////////
// Create a Int32List using an unchanged non-final top-level field as length.
////////////////////////////////////////////////////////////////////////////////

var _field1 = 10;

newInt32List() => new Int32List(_field1);

////////////////////////////////////////////////////////////////////////////////
// Create a Int8List using a final top-level field as length.
////////////////////////////////////////////////////////////////////////////////

final _field2 = 11;

/*element: newInt8List:Container([exact=NativeInt8List], element:
[subclass=JSInt], length: 11) | element:
newInt8List:Container([exact=NativeInt8List], element: [subclass=JSInt],
length: null)*/newInt8List() => new Int8List(_field2);

////////////////////////////////////////////////////////////////////////////////
// Create a Uint16List using a const top-level field as length.
////////////////////////////////////////////////////////////////////////////////

const _field3 = 12;

/*element: newUint16List:Container([exact=NativeUint16List], element:
[exact=JSUInt31], length: 12) | element:
newUint16List:Container([exact=NativeUint16List], element: [exact=JSUInt31],
length: null)*/newUint16List() => new Uint16List(_field3);

////////////////////////////////////////////////////////////////////////////////
// Create a Uint32List using a parenthesized literal int as length.
////////////////////////////////////////////////////////////////////////////////

newUint32List() => new Uint32List((13));

////////////////////////////////////////////////////////////////////////////////
// Create a Uint8ClampedList using a constant multiplication as length.
////////////////////////////////////////////////////////////////////////////////

newUint8ClampedList() =>
    new Uint8ClampedList(2 * 7);

////////////////////////////////////////////////////////////////////////////////
// Create a Uint8List using a const static field as length.
////////////////////////////////////////////////////////////////////////////////

abstract class Class1 {
  static const field = 15;
}

/*element: newUint8List:Container([exact=NativeUint8List], element:
[exact=JSUInt31], length: 15) | element:
newUint8List:Container([exact=NativeUint8List], element: [exact=JSUInt31],
length: null)*/newUint8List() => new Uint8List(Class1.field);

----------------------------------------------------------

stderr:
Unhandled exception:
Expect.fail('Errors found.')
#0      Expect._fail (package:expect/expect.dart:566:5)
#1      Expect.fail (package:expect/expect.dart:232:5)
#2      checkCode
(file:///usr/local/google/home/dmitryas/dart/sdk/tests/compiler/dart2js/equivalence/id_equivalence_helper.dart:645:12)
<asynchronous suspension>
#3      checkTests
(file:///usr/local/google/home/dmitryas/dart/sdk/tests/compiler/dart2js/equivalence/id_equivalence_helper.dart:524:13)
<asynchronous suspension>
#4      runTests.<anonymous closure>
(file:///usr/local/google/home/dmitryas/dart/sdk/tests/compiler/dart2js/inference/inference_test_helper.dart:35:11)
<asynchronous suspension>
#5      asyncTest (package:async_helper/async_helper.dart:96:4)
#6      runTests
(file:///usr/local/google/home/dmitryas/dart/sdk/tests/compiler/dart2js/inference/inference_test_helper.dart:33:3)
#7      main
(file:///usr/local/google/home/dmitryas/dart/sdk/tests/compiler/dart2js/inference/inference1_test.dart:8:3)
#8      _startIsolate.<anonymous closure>
(dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#9      _RawReceivePortImpl._handleMessage
(dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

--- Re-run this test:
python tools/test.py -m release -c none -r vm -a ia32 --checked -t 120
--reset-browser-configuration dart2js/inference/inference1_test

[00:18 | 100% | +    0 | -    1]

```

**Comment by stefantsov** [comment]
Update: [CL 39960](https://dart-review.googlesource.com/c/sdk/+/39960) may not land any time soon, so that may not be an issue to spend too much time on.

**Comment by sigmundch** [comment]
I believe this is now stale, @stefantsov please reopen if I'm mistaken.

**Comment by stefantsov** [comment]
Yep, that's right.  Thank hou @sigmundch for taking care of it!
