### ISSUE TITLE
exception from analysis server: NoSuchMethodError: The getter 'displayName' was called on null.

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#32110]
Analyzer Feedback from IntelliJ

This is from the `2.0.0-dev.22.0` version of the sdk, so may be out of date from head.

@scheglov 

# Version information

- `IDEA IC-173.4548.28`
- `2.0.0-dev.22.0`
- `IC-173.4548.28, JRE 1.8.0_144-b01x64 Oracle Corporation, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/jx/f3k8s0j14h3gcjz2td9jmf2c003j4x/T/report.txt

```
Dart analysis server, SDK version 2.0.0-dev.22.0, server version 1.18.5, error: Failed to send notification
NoSuchMethodError: The getter 'displayName' was called on null.
Receiver: null
Tried calling: displayName
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FlutterOutlineComputer._addAttribute (package:analysis_server/src/flutter/flutter_outline_computer.dart:59)
#2      FlutterOutlineComputer._createOutline (package:analysis_server/src/flutter/flutter_outline_computer.dart:122)
#3      _FlutterOutlineBuilder.visitExpression (package:analysis_server/src/flutter/flutter_outline_computer.dart:183)
#4      GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:364)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6514)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8120)
#7      ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7225)
#8      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#9      GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#10     _FlutterOutlineBuilder.visitExpression (package:analysis_server/src/flutter/flutter_outline_computer.dart:194)
#11     GeneralizingAstVisitor.visitLiteral (package:analyzer/dart/ast/visitor.dart:400)
#12     GeneralizingAstVisitor.visitTypedLiteral (package:analyzer/dart/ast/visitor.dart:543)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/40104
