### ISSUE TITLE
Analyzer error: NoSuchMethodError: The getter 'element' was called on null

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32142]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Don't seem to be able to repro this, but I was editing code that looks something like this in a flutter project (I was typing around the `HashSet` part trying to see if there was such a class:

```dart
import 'dart:math';
import 'dart:typed_data';
import 'package:flip8/src/font.dart';

class Chip8 {
  static const int screenWidth = 64;
  static const int screenHeight = 32;

  bool _needsRedraw = false;
  Uint8List _v = new Uint8List(16);
  int _delay = 0;
  int _i = 0;
  int _pc = 0x200;
  int _sp = 0;
  Uint16List _stack = new Uint16List(16);
  Uint8List _ram = new Uint8List(0x1000);
  HashSet
  Map<int, > _opCodes;

  final _rng = new Random();
  final List<List<bool>> _screenBuffer = new List<List<bool>>.generate(
      screenWidth, (_) => new List<bool>.filled(screenHeight, false),
      growable: false);
  Map<int, void Function(OpCodeData)> _opCodes;
  Map<int, void Function(OpCodeData)> _opCodesMisc;

  Chip8() {
// ...
```

### Versions

- Dart SDK 2.0.0-dev.22.0
- Visual Studio Code 1.20.0
- Dart Code 2.8.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.8.1
```

### Exception

Analysis failed: /Users/danny/Dev/Flip-8/lib/src/chip8.dart context: exception_20180213_203506_408

```text
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9814)
#2      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5784)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8120)
#4      TypeArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10688)
#5      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#6      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9975)
#7      UnifyingAstVisitor.visitTypeArgumentList (package:analyzer/dart/ast/visitor.dart:3212)
#8      TypeArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10684)
#9      TypeNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10828)
#10     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#11     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9975)
#12     UnifyingAstVisitor.visitTypeName (package:analyzer/dart/ast/visitor.dart:3215)
#13     TypeResolverVisitor.visitTypeName (package:analyzer/src/generated/resolver.dart:10005)
#14     TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10823)
#15     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11297)
#16     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#17     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9975)
#18     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228)
#19     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11292)
#20     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4427)
#21     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#22     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9975)
#23     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:3011)
#24     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4422)
#25     TypeResolverVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:9677)
#26     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7198)
#27     TypeResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:9623)
#28     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1906)
#29     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8120)
#30     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2502)
#31     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#32     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9975)
#33     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#34     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#35     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:682)
#36     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:127)
#37     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
#38     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:126)
#39     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#40     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217)
<asynchronous suspension>
#41     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97)
<asynchronous suspension>
#42     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1218)
<asynchronous suspension>
#43     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#44     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#45     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:989)
<asynchronous suspension>
#46     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1889)
<asynchronous suspension>
#47     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832)
#48     new AnalysisServer (package:analysis_server/src/analysis_server.dart:394)
#49     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#50     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#51     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:442)
#52     _rootRun (dart:async/zone.dart:1126)
#53     _CustomZone.run (dart:async/zone.dart:1023)
#54     runZoned (dart:async/zone.dart:1501)
#55     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:482)
#56     Driver.start (package:analysis_server/src/server/driver.dart:441)
#57     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#58     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/danny/Dev/Flip-8",
        "explicitFileCount": 4,
        "implicitFileCount": 808,
        "workItemQueueLength": 4,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
This was fixed in 2.0.0-dev.28.0.
