### ISSUE TITLE
Flutter benchmark hot_mode_dev_cycle__preview_dart_2_benchmark times out during hot reload

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#32145]
After rolling Dart to Flutter, hot_mode_dev_cycle__preview_dart_2_benchmark times out with the following error:

```
stdout: [        ] Benchmarking hot reload
stdout: [        ] Performing hot reload...
stdout: [   +4 ms] Refreshing active FlutterViews before reloading.
stdout: [        ] _flutter.listViews: {}
stdout: [ +420 ms] Syncing files to device Moto G 4...
stdout: [        ] DevFS: Starting sync from LocalDirectory: '/private/var/folders/_5/bqxnl8nn353dps4d6fzg77x00000gn/T/edited_flutter_gallery'
stdout: [        ] Scanning project files
stdout: [   +6 ms] Scanning package files
stdout: [  +60 ms] Scanning asset files
stdout: [   +6 ms] Scanning for deleted files
stdout: [   +3 ms] Compiling dart to kernel with 0 updated files
stdout: [   +9 ms] Updating files
stdout: [  +27 ms] DevFS: Sync finished
stdout: [        ] Synced 0.0MB.
stdout: [   +2 ms] _reloadSources: {pause: false, rootLibUri: /data/user/0/io.flutter.demo.gallery/cache/edited_flutter_galleryMTCIBY/edited_flutter_gallery/lib/main.dart.dill, packagesUri: /data/user/0/io.flutter.demo.gallery/cache/edited_flutter_galleryMTCIBY/edited_flutter_gallery/.packages, isolateId: isolates/993507320}
stdout: [+30014 ms] Request to Dart VM Service timed out: _reloadSources({pause: false, rootLibUri: /data/user/0/io.flutter.demo.gallery/cache/edited_flutter_galleryMTCIBY/edited_flutter_gallery/lib/main.dart.dill, packagesUri: /data/user/0/io.flutter.demo.gallery/cache/edited_flutter_galleryMTCIBY/edited_flutter_gallery/.packages, isolateId: isolates/993507320})
stderr: [   +2 ms] Hot reload failed: TimeoutException: Request to Dart VM Service timed out: _reloadSources({pause: false, rootLibUri: /data/user/0/io.flutter.demo.gallery/cache/edited_flutter_galleryMTCIBY/edited_flutter_gallery/lib/main.dart.dill, packagesUri: /data/user/0/io.flutter.demo.gallery/cache/edited_flutter_galleryMTCIBY/edited_flutter_gallery/.packages, isolateId: isolates/993507320})
stderr:            #0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:740)
stderr:            
stderr:            #1      Isolate.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:997)
stderr:            #2      Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1046)
stderr:            
stderr:            #3      FlutterDevice.reloadSources (package:flutter_tools/src/resident_runner.dart:139)
stderr:            #4      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:529)
stderr:            
stderr:            #5      HotRunner.restart (package:flutter_tools/src/run_hot.dart:459)
```

The problem can be reproduced by building debug and host-debug Flutter engine at rev. 834d6eb02988e7f2c44eda05cec908378a1a9138 and running

```
cd  flutter/dev/benchmarks/complex_layout
flutter run --hot --benchmark --verbose --resident --preview-dart-2 --local-engine android_debug
```

Bisected this regression to Dart SDK rev. 2ba978a186117c1a4a340d7586874429d3d20536.
This problem is blocking roll of Dart to Flutter.

/cc @bkonyi

**Comment by mraleph** [comment]
I suggest considering reverting the culprit commit to unblock the roll if we can't fix it within say half a day.

**Comment by aam** [comment]
it also blocks roll of the engine into the flutter, unless we rollback dart roll 834d6eb02988e7f2c44eda05cec908378a1a9138 from the engine

**Comment by aam** [comment]
...and 5529f893e24d09f2f775882cf38879d3ead95c26, which depends on rolled dart.

**Comment by bkonyi** [comment]
I've uploaded a fix [here](https://dart-review.googlesource.com/c/sdk/+/41025). Just waiting for approval, but then this should be unblocked.
