### ISSUE TITLE
DDC error when throwing a string in async code

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32144]
The code below emits an error when trying to rethrow the exception from async code in DDC.

```dart
import 'dart:async';

void main() async {
  await new Future(() => throw "Bar");
}
```

```
leafp-macbookpro:sdk leafp$ rundart.sh ~/src/dart-repo/sdk/pkg/dev_compiler/tool/ddc  ~/tmp/async_assert.dart
/Users/leafp/src/dart-repo/sdk/xcodebuild/ReleaseX64/gen/utils/dartdevc/js/common/dart_sdk.js:30991
  error.stack = dart.toString(stackTrace);
              ^

TypeError: Cannot create property 'stack' on string 'Bar'
    at Object.async._rethrow (/Users/leafp/src/dart-repo/sdk/xcodebuild/ReleaseX64/gen/utils/dartdevc/js/common/dart_sdk.js:30991:15)
    at async._AsyncCallbackEntry.new.async._schedulePriorityAsyncCallback.dart.fn [as callback] (/Users/leafp/src/dart-repo/sdk/xcodebuild/ReleaseX64/gen/utils/dartdevc/js/common/dart_sdk.js:30986:11)
    at Object.async._microtaskLoop (/Users/leafp/src/dart-repo/sdk/xcodebuild/ReleaseX64/gen/utils/dartdevc/js/common/dart_sdk.js:27533:11)
    at async._startMicrotaskLoop (/Users/leafp/src/dart-repo/sdk/xcodebuild/ReleaseX64/gen/utils/dartdevc/js/common/dart_sdk.js:27540:11)
    at Immediate.internalCallback (/Users/leafp/src/dart-repo/sdk/xcodebuild/ReleaseX64/gen/utils/dartdevc/js/common/dart_sdk.js:27644:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by jmesserly** [comment]
this example works now
