### ISSUE TITLE
Error from analysis server: NoSuchMethodError: The method 'getType' was called on null.

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32150]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I opened up the Flutter "Stocks" example app and deleted the `.packages` file (possibly while initial analysis was in progress). Not sure if it matters, but running with `preview-dart-2`. Log of the analysis server communication [here](https://github.com/dart-lang/sdk/files/1723654/analyzer.txt).

### Versions

- Dart SDK 2.0.0-dev.24.0
- Visual Studio Code 1.20.0
- Dart Code 2.9.0-dev

### Analyzer Info

The analyzer was launched using the arguments:

```text
M:\Apps\Dart\Dart-2.0.0-dev.24.0\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.9.0-dev
--preview-dart-2
```

### Exception

Analysis failed: m:\Coding\Applications\flutter\examples\stocks\test\search_test.dart context: exception_20180214_110601_481

```text
NoSuchMethodError: The method 'getType' was called on null.
Receiver: null
Tried calling: getType("main")
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ElementResolver._handlePrefixedImplicitConstructorCase (package:analyzer/src/generated/element_resolver.dart:1745)
#2      ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:685)
#3      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7728)
#4      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6067)
#5      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7728)
#6      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4286)
#7      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6082)
#8      UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3005)
#9      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4282)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8120)
#11     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1346)
#12     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6082)
#13     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#14     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7118)
#15     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1342)
#16     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1291)
#17     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6082)
#18     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#19     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7130)
#20     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5350)
#21     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1287)
#22     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5377)
#23     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6082)
#24     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#25     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7458)
#26     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5849)
#27     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5371)
#28     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8120)
#29     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:428)
#30     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6082)
#31     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898)
#32     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:5225)
#33     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:424)
#34     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6069)
#35     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7728)
#36     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4286)
#37     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6082)
#38     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3005)
#39     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4282)
#40     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8120)
#41     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1346)
#42     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6082)
#43     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#44     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7118)
#45     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1342)
#46     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1291)
#47     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6082)
#48     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#49     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7130)
#50     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5350)
#51     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1287)
#52     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5377)
#53     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6082)
#54     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#55     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7433)
#56     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5849)
#57     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5371)
#58     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5222)
#59     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6082)
#60     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026)
#61     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:7426)
#62     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5825)
#63     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7418)
#64     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5815)
#65     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5215)
#66     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5455)
#67     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#68     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:697)
#69     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:127)
#70     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
#71     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:126)
#72     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#73     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217)
<asynchronous suspension>
#74     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97)
<asynchronous suspension>
#75     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1218)
<asynchronous suspension>
#76     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#77     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#78     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1010)
<asynchronous suspension>
#79     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1889)
<asynchronous suspension>
#80     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832)
#81     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#82     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#83     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#84     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:442)
#85     _rootRun (dart:async/zone.dart:1126)
#86     _CustomZone.run (dart:async/zone.dart:1023)
#87     runZoned (dart:async/zone.dart:1501)
#88     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:482)
#89     Driver.start (package:analysis_server/src/server/driver.dart:441)
#90     main (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#91     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#92     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "m:\\Coding\\Applications\\flutter\\examples\\stocks",
        "explicitFileCount": 15,
        "implicitFileCount": 95,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/41380
