### ISSUE TITLE
Reliable analysis server failure

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#32162]
Analyzer Feedback from IntelliJ

This seems 100% reliable. 

1. Check out the Dart SDK at commit 23fe39e89fcaeda926fb0fef1378ef48cad6a558
1. Apply patchset 6 from https://dart-review.googlesource.com/c/sdk/+/40661
1. Open IntelliJ CE 2017.3.3, Build #IC-173.4301.25 with the Dart plugin
1. File > Open... pkg/front_end from the SDK
1. Open the file lib/src/fasta/type_inference/type_inferrer.dart
1. Find import '../fasta_codes.dart'; on line 63
1. Insert the cursor between the closing single quote and the semicolon.
1. Type "<space>show".  The Dart Analysis window reports "Dart Analyzer Error" 100% of the time for me.

**Comment by devoncarew** [comment]
@kmillikin, do you have a stack trace from the error? The dialog should offer to report one.

**Comment by kmillikin** [comment]
I was able to get this stack trace:

```
https://github.com/dart-lang/sdk/issues/new?body=Analyzer%20Feedback%20from%20IntelliJ# Version information- `IDEA IC-173.4301.25`- `2.0.0-edge.aadf7235dc777b995547296795135f5bc3a11611`- `IC-173.4301.25, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Linux(amd64) v4.9.0-5-amd64 unknown, screens 2560x1440`# ExceptionPlease append the contents of:file:///tmp/report2.txt```Dart analysis server, SDK version 2.0.0-edge.aadf7235dc777b995547296795135f5bc3a11611, server version 1.18.6, error: Analysis failed: /home/kmillikin/dart.git/sdk/pkg/front_end/lib/src/fasta/type_inference/type_inferrer.dart context: exception_20180215_111236_670NoSuchMethodError: The getter 'element' was called on null.Receiver: nullTried calling: element
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9799)
#2      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5823)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8195)
#4      TypeArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10763)
#5      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#6      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9960)
#7      UnifyingAstVisitor.visitTypeArgumentList (package:analyzer/dart/ast/visitor.dart:3212)
#8      TypeArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10759)
#9      TypeNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10903)
#10     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#11     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:9960)
#12     UnifyingAstVisitor.visitTypeName (package:analyzer/dart/ast/visitor.dart:3215)
#13     TypeResolverVisito
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Thank you for reporting this.
https://dart-review.googlesource.com/c/sdk/+/41922
