### ISSUE TITLE
Analyzer Exception

### ISSUE THREAD

**Issue by kortnevdmitriy** [dart-lang/sdk#32160]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-173.4548.30`
- `2.0.0-dev.24.0`
- `WS-173.4548.30, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\kortn\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-dev.24.0, server version 1.18.6, FATAL error: Failed to handle request: {id: 28, method: edit.getFixes, params: {file: C:\Users\kortn\WebstormProjects\ByldWeb\web\main.dart, offset: 88}, clientRequestTime: 1518618426534}
NoSuchMethodError: The getter 'state' was called on null.
Receiver: null
Tried calling: state
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:53)
<asynchronous suspension>
#2      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:50)
<asynchronous suspension>
#3      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:48)
#4      FixProcessor._addFix_createImportUri (package:analysis_server/src/services/correction/fix_internal.dart:1406)
<asynchronous suspension>
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:235)
<asynchronous suspension>
#6      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:84)
<asynchronous suspension>
#7      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:242)
<asynchronous suspension>
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:355)

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/41400
