### ISSUE TITLE
Fasta's incremental compiler can't cope with disappearing library. 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32197]
I upgraded Dart inside my Flutter Engine checkout and I could not build it anymore with this error:

```
Unhandled exception:
RangeError (index): Invalid value: Not in range 0..260, inclusive: 261
#0      List._setIndexed (dart:core-patch/dart:core/growable_array.dart:147)
#1      List.[]= (dart:core-patch/dart:core/growable_array.dart:144)
#2      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:188:35)
<asynchronous suspension>
#3      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103:35)
#4      _rootRun (dart:async/zone.dart:1126)
#5      _CustomZone.run (dart:async/zone.dart:1023)
#6      runZoned (dart:async/zone.dart:1501)
#7      CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103:14)
#8      IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:57:20)
<asynchronous suspension>
#9      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33:40)
<asynchronous suspension>
#10     _FrontendCompiler.compile.<anonymous closure> (package:frontend_server/server.dart:185:65)
#11     new Future.<anonymous closure> (dart:async/future.dart:174)
#12     _rootRun (dart:async/zone.dart:1122)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#16     _rootRun (dart:async/zone.dart:1126)
#17     _CustomZone.run (dart:async/zone.dart:1023)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#19     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#20     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#21     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

This happens because because Fasta attempts to preserve the order of libraries in the resulting program, but does not account for possibility that some libraries might have disappeared. Which means that `libraries.length` might be smaller than some of indices preserved in `importUriToOrder`.

Library that disappeared in this particular case was `incremental_class_hierarchy.dart` (because `frontend_server` is being trained upon itself in non-hermetic manner, so library structure from old builds gets leaked into new builds. Related issue flutter/flutter#14750).

**Comment by peter-ahe-google** [comment]
Jens, could you take a look?

**Comment by jensjoha** [comment]
If possible please verify that it's fixed.
I *did* reproduce it in a test before fixing it though.
