### ISSUE TITLE
Webstorm Debugging

### ISSUE THREAD

**Issue by jbhsoftware** [dart-lang/sdk#32219]
Hello, forgive me for being a novice. I am a self taught coder which I know is tough because I didn't learn the fundamentals first etc...

With that said, I am 6 months into a web app and had to move to a new machine. On the new machine I am having a weird issue that I do not know how to figure out. 

My code on the old machine worked in Dartium for debugging and when built and deployed with firebase hosting.

My code on the new machine works in Dartium, but has console errors in Chrome debugger, and when built and deployed.

In Webstorm, when I look at my breakpoints with Dartium, they are all checked as valid, but when I look with Chrome, about 5% are not checked as valid and typically error out there.

I believe the issues are centered around DSON objects/conversions.

I know that this is not enough information to diagnose the problem, but I am looking for guidance on where to start? I am not looking for anyone to do it for me, just point me in the direction that I need to study and I will figure it out!

Thank you in advance!

**Comment by jbhsoftware** [comment]
Again, I am a novice, but any advice on the error message here is greatly appreciated!

`ReferenceError: activeBorrowerObject is not defined
    at eval (eval at sendNewBorrowerToStream$1 (http://localhost:53854/main.dart.js:87688:9), <anonymous>:1:1)
    at CoreService.sendNewBorrowerToStream$1 (http://localhost:53854/main.dart.js:87688:9)
    at http://localhost:53854/main.dart.js:88492:23
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53854/main.dart.js:7344:15)
    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:53854/main.dart.js:7839:14)
    at _awaitOnObject_closure.dart._awaitOnObject_closure.call$1 (http://localhost:53854/main.dart.js:7827:34)
    at StaticClosure.dart._rootRunUnary (http://localhost:53854/main.dart.js:7683:18)
    at _ZoneDelegate.runUnary$3 (http://localhost:53854/main.dart.js:10950:41)
    at NgZone.dart.NgZone._runUnary$5 (http://localhost:53854/main.dart.js:30281:24)
    at Object.eval (eval at Closure_forwardCallTo (http://localhost:53854/main.dart.js:4917:14), <anonymous>:2:47)`

**Comment by eernstg** [comment]
Hello, I don't know the details of DSON etc., but it sounds like it would be helpful for you to look for 'Dartium is going away in Dart 2.0' [here](https://webdev.dartlang.org/articles/low-level-html/embedding-in-html#dart-mime-type-and-the-script-tag), and then update your tool chain. I know for certain that other people can give you much better specific information on DSON and stuff, so I won't make any attempts to do that. ;-)

**Comment by jbhsoftware** [comment]
Dartium is actually working, it's the Chrome debug, and when I actually build the application with pub build it gets the same errors, but runs well in Dartium.

**Comment by jbhsoftware** [comment]
Also, the error shown above is actually the "value" of the object shown in the debugger right before it errors out.  The error message shown in the console after is:

`EXCEPTION: Error: Reference.update failed: First argument  contains an invalid key ($identityHash) in property 'borrowers.-L5ikphsjccOqQKkdU_A.listOfBorrowerDocuments.0'.  Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"
STACKTRACE: 
Error: Reference.update failed: First argument  contains an invalid key ($identityHash) in property 'borrowers.-L5ikphsjccOqQKkdU_A.listOfBorrowerDocuments.0'.  Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"
    at https://www.gstatic.com/firebasejs/4.9.1/firebase-database.js:6:18187
    at Object.t.forEach (https://www.gstatic.com/firebasejs/4.9.1/firebase-app.js:6:12375)
    at Object.t.validateFirebaseData (https://www.gstatic.com/firebasejs/4.9.1/firebase-database.js:6:18076)
    at https://www.gstatic.com/firebasejs/4.9.1/firebase-database.js:6:18349
    at Object.t.forEach (https://www.gstatic.com/firebasejs/4.9.1/firebase-app.js:6:12375)
    at Object.t.validateFirebaseData (https://www.gstatic.com/firebasejs/4.9.1/firebase-database.js:6:18076)
    at https://www.gstatic.com/firebasejs/4.9.1/firebase-database.js:6:19278
    at Object.t.forEach (https://www.gstatic.com/firebasejs/4.9.1/firebase-app.js:6:12375)
    at Object.t.validateFirebaseMergeDataArg (https://www.gstatic.com/firebasejs/4.9.1/firebase-database.js:6:19229)
    at t.update (https://www.gstatic.com/firebasejs/4.9.1/firebase-database.js:6:45971)
ORIGINAL EXCEPTION: Error: Reference.update failed: First argument  contains an invalid key ($identityHash) in property 'borrowers.-L5ikphsjccOqQKkdU_A.listOfBorrowerDocuments.0'.  Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"

dart.Dl.$3 @ main.dart.js:13887`

**Comment by montyr75** [comment]
Yeah, I've been getting having this issue as well, since the 4.3 version of the firebase package. I actually have to hardcode the prior version of the firebase package to keep my JS builds functioning.

`Reference.update failed: First argument contains an invalid key ($identityHash)`  <-- that's on an attempt to update a Firebase record from a Dart Map.

**Comment by kevmoo** [comment]
I'd love to see a minimal repro here. Happy to investigate.

**Comment by jbhsoftware** [comment]
I figured out it has something to do with the lists now containing an
'$identityHash' property that I had never previously seen. I really didn't
figure this out until I switched to Firestore.

Switching to Firestore seemed to correct it for me.

**Comment by kevmoo** [comment]
Thanks for the update @jbhsoftware .

Closing this out as it is almost certainly not a Dart SDK issue
