### ISSUE TITLE
(Fatal?) exception from analysis server typing import parts on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32276]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Trying to investigate an analysis server test I pasted a path into an import that looks a bit like this:

```dart
import "package:test/test.dart";
import "file:///C:\Users\danny\Desktop\DartSample\bin\main.dart";
```

I'd written `file:///` and pasted a path which I was about to start tweaking. The editor sent a request for fixes and the server threw an error. It's marked as fatal, though the server still seems to be working (I can trigger this error multiple times in one session by moving my cursor around).

### Versions

- Dart SDK 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
- Visual Studio Code 1.20.1
- Dart Code 2.9.0-dev

### Analyzer Info

The analyzer was launched using the arguments:

```text
M:\Coding\Applications\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.9.0-dev
```

### Exception (fatal)

Failed to handle request: {id: 70, method: edit.getFixes, params: {file: c:\Users\danny\Desktop\DartSample\bin\main.dart, offset: 40}}

```text
AnalysisException: Cannot analyze "C:\Program Files (x86)\Microsoft VS Code\\C:UsersdannyDesktopDartSampleinmain.dart"

#0      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:55)
<asynchronous suspension>
#1      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:66)
<asynchronous suspension>
#2      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:48)
#3      FixProcessor._addFix_createImportUri (package:analysis_server/src/services/correction/fix_internal.dart:1445)
<asynchronous suspension>
#4      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:236)
<asynchronous suspension>
#5      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:85)
<asynchronous suspension>
#6      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:242)
<asynchronous suspension>
#7      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:355)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:722)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:718)
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1490)
#14     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:717)
#15     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207)
#17     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#18     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#19     _rootRunUnary (dart:async/zone.dart:1134)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#31     _rootRunUnary (dart:async/zone.dart:1134)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#44     _rootRunUnary (dart:async/zone.dart:1134)
#45     _CustomZone.runUnary (dart:async/zone.dart:1031)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#49     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#50     _StreamController._add (dart:async/stream_controller.dart:639)
#51     _StreamController.add (dart:async/stream_controller.dart:585)
#52     _Socket._onData (dart:io-patch/socket_patch.dart:1654)
#53     _rootRunUnary (dart:async/zone.dart:1138)
#54     _CustomZone.runUnary (dart:async/zone.dart:1031)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#58     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#59     _StreamController._add (dart:async/stream_controller.dart:639)
#60     _StreamController.add (dart:async/stream_controller.dart:585)
#61     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1231)
#62     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#63     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#64     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#65     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "c:\\Users\\danny\\Desktop\\DartSample",
        "explicitFileCount": 5,
        "implicitFileCount": 385,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
In the import, all of the backslashes were being taken as escape characters, which made it appear that the URI was `file:///C:UsersdannyDesktopDartSample_inmain.dart` (underscore in place of backspace character). It appears that the `Uri` class doesn't recognize this as being an absolute path, so when it resolves it relative to something else it just tacks in on as a file name. What's confusing, to me, is why it resolved it relative to `C:\Program Files (x86)\Microsoft VS Code\` and why it doubled the separator. Any ideas?

In any case, I added guard code in https://dart-review.googlesource.com/c/sdk/+/43202 to prevent this from causing an error (fatal or otherwise), which I think closes out this issue.

**Comment by DanTup** [comment]
> What's confusing, to me, is why it resolved it relative to `C:\Program Files (x86)\Microsoft VS Code\`

I'd have to do some testing, but I'll take a guess - maybe I'm not setting a working directory when I spawn the analyzer so it's defaulting to this, and then the VM is resolving it relative to it's cwd?

> and why it doubled the separator

That is a bit weird. I'll have a play around and see if I can understand what it's doing.

**Comment by DanTup** [comment]
Hmm, I put this in a test to see if I could understand what happened:

```dart
 @soloTest
  test_danny() async {
    await resolveTestUnit('''
    import 'file:///C:\Users\danny\Desktop\DartSample\bin\main.dart';
''');

    await assertHasAssistAt(
        'file', DartAssistKind.CONVERT_PART_OF_TO_URI, '''a''');
  }
```

However it failed because it returned the wrong assist types:

> Expected to find assist dart.assist.convert.partOfToPartUri in
  Assist(kind=dart.assist.convert.toDoubleQuotedString, change={"message":"Convert to double quoted string","edits":[{"file":"C:\\test.dart","fileStamp":0,"edits":[{"offset":61,"length":1,"replacement":"\""},{"offset":11,"length":1,"replacement":"\""}]}],"linkedEditGroups":[],"id":"dart.assist.convert.toDoubleQuotedString"})

(I've commented out your `try/catch`).

So, I'm not really sure. If you want me to do a little more digging and know why the above test isn't triggering the code from the original error, let me know.

**Comment by bwilkerson** [comment]
As long as it's not negatively impacting users we should probably consider it good enough and not spend more time on it.

**Comment by DanTup** [comment]
I don't believe so - I didn't see any other issues after the change you made here. Ofc, if any do come up I'll raise new issues.
