### ISSUE TITLE
setField doesn't work how described in documentation

### ISSUE THREAD

**Issue by maksimr** [dart-lang/sdk#32288]
The documentation for **delegate** method says 

```dart
if (invocation.isGetter) {
 ...
} else if (invocation.isSetter) {
  return this.setField(invocation.memberName,
                       invocation.positionalArguments[0]).reflectee;
} else {
 ...
}
```
https://api.dartlang.org/stable/1.24.3/dart-mirrors/ObjectMirror/delegate.html

But this code doesn't work.
Example which reproduces the problem

```dart
/* Dart VM version: 1.24.3 (Wed Dec 13 23:26:59 2017) on "macos_x64" */
import "dart:mirrors" show InstanceMirror, reflect;

class ProxyHandler {
  ProxyHandler({this.get, this.set});
  final Function(InstanceMirror, Symbol) get;
  final Function(InstanceMirror, Symbol, dynamic) set;
}

@proxy
class Proxy {
  Proxy(f, this.handler) {
    _im = reflect(f);
  }

  InstanceMirror _im;
  ProxyHandler handler;

  noSuchMethod(inv) {
    if (inv.isGetter) return handler.get(_im, inv.memberName);
    if (inv.isSetter) return handler.set(_im, inv.memberName, inv.positionalArguments[0]);
    return _im.delegate(inv);
  }
}

class Person {
  Person(this.name, this.age);
  String name;
  int age;
}

main() {
  var a = new Person('A', 20);
  var proxyA = new Proxy(a, new ProxyHandler(
    get: (InstanceMirror im, prop) => im.getField(prop).reflectee,
    set: (InstanceMirror im, prop, value) => im.setField(prop, value)
  ));

  assert(proxyA == a.name);
  proxyA.name = 'B';
  assert(a.name == 'B');
}
```
https://gist.github.com/maksimr/46d9ddf68afef5af9b2e26772fd26d44

```
➜  maksimrv:/tmp/proxy  dart ./proxy.dart
Unhandled exception:
NoSuchMethodError: Class 'Person' has no instance setter 'name=='.
Receiver: Instance of 'Person'
Tried calling: name=="B"
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _LocalInstanceMirror._invokeSetter (dart:mirrors-patch/mirrors_impl.dart:531)
#3      _LocalInstanceMirror._setFieldSlow (dart:mirrors-patch/mirrors_impl.dart:480)
#4      _LocalInstanceMirror.setField (dart:mirrors-patch/mirrors_impl.dart:496)
#5      main.<anonymous closure> (file:///tmp/proxy/proxy.dart:36:49)
#6      Proxy.noSuchMethod (file:///tmp/proxy/proxy.dart:21:38)
#7      main (file:///tmp/proxy/proxy.dart:40:10)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

**Comment by zoechi** [comment]
As far as I remember the setters name has a `_` suffix => `name_`
