### ISSUE TITLE
Fasta crash in strong mode when trying to use a nonexisting class in a mixin

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#32313]
When I try to compile this in fasta strong mode:

```
abstract class A<T extends Object> extends Object with NonExisting<T> {}

class B extends Object with NonExisting<Object>, A {}

main() {}
```

I get this:

```
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _TypeSubstitutor.visitSupertype (package:kernel/type_algebra.dart:441:14)
#2      Substitution.substituteSupertype (package:kernel/type_algebra.dart:309:45)
#3      StrongModeMixinInferrer.generateConstraints (package:front_end/src/fasta/type_inference/type_inferrer.dart:1685:12)
#4      StrongModeMixinInferrer.infer (package:front_end/src/fasta/type_inference/type_inferrer.dart:1730:7)
#5      ClosedWorldClassHierarchy._topologicalSortVisit (package:kernel/class_hierarchy.dart:781:48)
#6      ClosedWorldClassHierarchy._initialize (package:kernel/class_hierarchy.dart:705:9)
#7      new ClassHierarchy (package:kernel/class_hierarchy.dart:38:9)
#8      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:581:21)
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:252:14)
<asynchronous suspension>
#10     CompileTask.buildOutline ([sdk]/pkg/front_end/tool/_fasta/entry_points.dart:224:38)
<asynchronous suspension>
#11     CompileTask.compile ([sdk]/pkg/front_end/tool/_fasta/entry_points.dart:236:39)
<asynchronous suspension>
#12     compile.<anonymous closure> ([sdk]/pkg/front_end/tool/_fasta/entry_points.dart:180:25)
<asynchronous suspension>
#13     withGlobalOptions.<anonymous closure> ([sdk]/pkg/front_end/tool/_fasta/command_line.dart:387:13)
#14     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103:35)
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103:14)
#19     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:114:41)
#20     withGlobalOptions ([sdk]/pkg/front_end/tool/_fasta/command_line.dart:380:26)
#21     compile ([sdk]/pkg/front_end/tool/_fasta/entry_points.dart:173:18)
<asynchronous suspension>
#22     compileEntryPoint ([sdk]/pkg/front_end/tool/_fasta/entry_points.dart:59:11)
<asynchronous suspension>
#23     main ([sdk]/pkg/front_end/tool/_fasta/compile.dart:7:33)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by peter-ahe-google** [comment]
This is actually what you get:

```
t.dart:1:36: Error: The type 'NonExisting<#T0>' can't be mixed in.
abstract class A<T extends Object> extends Object with NonExisting<T> {}
                                   ^
t.dart:3:9: Error: The type 'NonExisting<#U0>' can't be mixed in.
class B extends Object with NonExisting<Object>, A {}
        ^
t.dart:1:36: Error: The type 'NonExisting' can't be used as supertype.
abstract class A<T extends Object> extends Object with NonExisting<T> {}
                                   ^
t.dart:3:9: Error: The type 'NonExisting' can't be used as supertype.
class B extends Object with NonExisting<Object>, A {}
        ^
Unhandled exception:
Crash when compiling dart:async,
at character offset null:
NoSuchMethodError: The getter 'typeArguments' was called on null.
Receiver: null
Tried calling: typeArguments
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _TypeSubstitutor.visitSupertype (package:kernel/type_algebra.dart:441:14)
#2      Substitution.substituteSupertype (package:kernel/type_algebra.dart:309:45)
#3      StrongModeMixinInferrer.generateConstraints (package:front_end/src/fasta/type_inference/type_inferrer.dart:1685:12)
#4      StrongModeMixinInferrer.infer (package:front_end/src/fasta/type_inference/type_inferrer.dart:1730:7)
#5      ClosedWorldClassHierarchy._topologicalSortVisit (package:kernel/class_hierarchy.dart:781:48)
#6      ClosedWorldClassHierarchy._initialize (package:kernel/class_hierarchy.dart:705:9)
#7      new ClassHierarchy (package:kernel/class_hierarchy.dart:38:9)
#8      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:581:21)
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:252:14)
<asynchronous suspension>
#10     CompileTask.buildOutline (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:224:38)
<asynchronous suspension>
#11     CompileTask.compile (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:236:39)
<asynchronous suspension>
#12     compile.<anonymous closure> (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:180:25)
<asynchronous suspension>
#13     withGlobalOptions.<anonymous closure> (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:387:13)
#14     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103:35)
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103:14)
#19     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:114:41)
#20     withGlobalOptions (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:380:26)
#21     compile (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:173:18)
<asynchronous suspension>
#22     compileEntryPoint (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:59:11)
<asynchronous suspension>
#23     main (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _TypeSubstitutor.visitSupertype (package:kernel/type_algebra.dart:441:14)
#2      Substitution.substituteSupertype (package:kernel/type_algebra.dart:309:45)
#3      StrongModeMixinInferrer.generateConstraints (package:front_end/src/fasta/type_inference/type_inferrer.dart:1685:12)
#4      StrongModeMixinInferrer.infer (package:front_end/src/fasta/type_inference/type_inferrer.dart:1730:7)
#5      ClosedWorldClassHierarchy._topologicalSortVisit (package:kernel/class_hierarchy.dart:781:48)
#6      ClosedWorldClassHierarchy._initialize (package:kernel/class_hierarchy.dart:705:9)
#7      new ClassHierarchy (package:kernel/class_hierarchy.dart:38:9)
#8      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:581:21)
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:252:14)
<asynchronous suspension>
#10     CompileTask.buildOutline (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:224:38)
<asynchronous suspension>
#11     CompileTask.compile (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:236:39)
<asynchronous suspension>
#12     compile.<anonymous closure> (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:180:25)
<asynchronous suspension>
#13     withGlobalOptions.<anonymous closure> (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:387:13)
#14     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103:35)
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103:14)
#19     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:114:41)
#20     withGlobalOptions (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:380:26)
#21     compile (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:173:18)
<asynchronous suspension>
#22     compileEntryPoint (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:59:11)
<asynchronous suspension>
#23     main (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by peter-ahe-google** [comment]
Those error messages are horrible, and clearly not conveying that `NonExisting` doesn't exist.

**Comment by jensjoha** [comment]
Yes, sorry, I didn't try to be misleading, just trying to point out that I got a crash.

**Comment by peter-ahe-google** [comment]
No reason to apologize, I just wanted to mention that even the errors before the crash are bad :-(
