### ISSUE TITLE
I <3 Dart :)

### ISSUE THREAD

**Issue by oz10h** [dart-lang/sdk#32328]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-173.4548.30`
- `2.0.0-dev.30.0`
- `WS-173.4548.30, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\root\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Analysis failed: C:\Users\root\sswap\SectionSwapClient\test\app_test.dart context: exception_20180226_174059_111
NoSuchMethodError: The getter 'units' was called on null.
Receiver: null
Tried calling: units
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      LibraryElementInDependency._makeUnitElement (package:analyzer/src/summary/link.dart:3715)
#3      LibraryElementForLink.units (package:analyzer/src/summary/link.dart:3520)
#4      LibraryElementForLink.getContainedName.<anonymous closure> (package:analyzer/src/summary/link.dart:3559)
#5      _HashVMBase

**Comment by matanlurey** [comment]
Unfortunately we are no longer updating Dart SDK 1.24.3.

Quite a bit of work has been put in the 2.0.0-dev channel, so this might already be fixed.
