### ISSUE TITLE
Mixin type inference tries to do a subtype check with an incomplete class hierarchy

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#32353]
Consider the following code (adapted from https://github.com/google/file.dart):

```dart
import 'dart:io' as io;

abstract class _LocalDirectory
    extends _LocalFileSystemEntity<_LocalDirectory, io.Directory>
    with ForwardingDirectory, DirectoryAddOnsMixin {}

abstract class _LocalFileSystemEntity<T extends FileSystemEntity,
    D extends io.FileSystemEntity> extends ForwardingFileSystemEntity<T, D> {}

abstract class FileSystemEntity implements io.FileSystemEntity {}

abstract class ForwardingFileSystemEntity<T extends FileSystemEntity,
    D extends io.FileSystemEntity> implements FileSystemEntity {}

abstract class ForwardingDirectory<T extends Directory>
    extends ForwardingFileSystemEntity<T, io.Directory> implements Directory {}

abstract class Directory implements FileSystemEntity, io.Directory {}

abstract class DirectoryAddOnsMixin implements Directory {}
```

When trying to infer the type parameters for `_LocalDirectory`'s use of the mixin `ForwardingDirectory`, here's what happens:
- We find that the superclass constraint is `ForwardingFileSystemEntity<T, io.Directory>`.  Call this `A`.
- We look at the superclass (`_LocalFileSystemEntity<_LocalDirectory, io.Directory>`), and find that it is a subclass of `ForwardingFileSystemEntity<_LocalDirectory, io.Directory>`.  Call this `B`.
- We now attempt to use the general type inference algorithm to constrain `T` such that `A = B`.  We do this by gathering the constraints implied by `A <: B` and `B <: A`.
- Three constraints are gathered:
  - `T <: _LocalDirectory` (from `A <: B`)
  - `_LocalDirectory <: T` (from `B <: A`)
  - `T <: Directory` (from the definition of `T`, which is `T extends Directory`)
- The general type inference algorithm then tries to reduce the first and third constraints to `T <: GLB(_LocalDirectory, Directory)`.
- `GLB(_LocalDirectory, Directory)` should be `_LocalDirectory`, however the GLB logic can’t tell that it is, because the class hierarchy hasn’t been fully built.  In particular, `_LocalDirectory`’s subclassing of `Directory` is through its other mixin (`DirectoryAddOnsMixin`), which hasn’t been processed yet.

The analyzer mixin type inference algorithm fails at this point, saying that it can't infer a type.  The front end mixin type inference algorithm crashes.

**Comment by stereotype441** [comment]
Analyzer fix is out for review: https://dart-review.googlesource.com/c/sdk/+/44220

**Comment by peter-ahe-google** [comment]
Appears to be fixed by [change 45021](https://dart-review.googlesource.com/c/sdk/+/45021).

**Comment by peter-ahe-google** [comment]
This problem doesn't reproduce in 9f56e283721ce7809f028680133484a6b24f9202.

**Comment by peter-ahe-google** [comment]
@stereotype441's analysis of the problem above doesn't match my understanding of how the code worked before 9f56e28, so I'd like to keep this open and see if I can reproduce this problem.

**Comment by kmillikin** [comment]
I don't know if @stereotype441's analysis is right or not.

The mixin inference in Kernel's class hierarchy analysis has a more fundamental problem which we have to fix in any case.

CHA has two traversals of the class hierarchy and only safely answer subtype queries after the second pass, when it has built the intervals necessary for those queries.  Before that, it will just crash.

The mixin inference uses the constraint generator from type inference as an off-the-shelf algorithm during the first pass of CHA, and that solver can ask subtype queries which will crash.  In any case, we will have to use a different implementation of constraint generation or else a different implementation of subtype queries.  @stefantsov will fix the crash.

**Comment by peter-ahe-google** [comment]
I have a repro that crashes again, should we restore P1 status?

```
abstract class io_FileSystemEntity {}

abstract class io_Directory implements io_FileSystemEntity {}

abstract class _LocalDirectory<U, V> extends _LocalFileSystemEntity<U, V>
    with ForwardingDirectory {}

class Foo extends _LocalDirectory<_LocalDirectory, io_Directory> {}

abstract class _LocalFileSystemEntity<T extends FileSystemEntity,
    D extends io_FileSystemEntity> extends ForwardingFileSystemEntity<T, D> {}

abstract class FileSystemEntity implements io_FileSystemEntity {}

abstract class ForwardingFileSystemEntity<T extends FileSystemEntity,
    D extends io_FileSystemEntity> implements FileSystemEntity {}

abstract class ForwardingDirectory<T extends Directory>
    extends ForwardingFileSystemEntity<T, io_Directory> implements Directory {}

abstract class Directory implements FileSystemEntity, io_Directory {}
```

**Comment by peter-ahe-google** [comment]
I'm not sure if my repro is a legal program. I think this is:

```
abstract class io_FileSystemEntity {}

abstract class io_Directory implements io_FileSystemEntity {}

abstract class _LocalDirectory<T extends FileSystemEntity,
        D extends io_FileSystemEntity> extends _LocalFileSystemEntity<T, D>
    with ForwardingDirectory {}

class Foo extends _LocalDirectory<_LocalDirectory, io_Directory> {}

abstract class _LocalFileSystemEntity<T extends FileSystemEntity,
    D extends io_FileSystemEntity> extends ForwardingFileSystemEntity<T, D> {}

abstract class FileSystemEntity implements io_FileSystemEntity {}

abstract class ForwardingFileSystemEntity<T extends FileSystemEntity,
    D extends io_FileSystemEntity> implements FileSystemEntity {}

abstract class ForwardingDirectory<T extends Directory>
    extends ForwardingFileSystemEntity<T, io_Directory> implements Directory {}

abstract class Directory implements FileSystemEntity, io_Directory {}
```

**Comment by peter-ahe-google** [comment]
I'm not sure if my program is legal. I don't think it is because of the use of _LocalDirectory as a raw type in:

```
class Foo extends _LocalDirectory<_LocalDirectory, io_Directory> {}
```

**Comment by stefantsov** [comment]
I've simplified the repro code, so that the only raw type is the mixed in interface type:

```dart
class A {}

class B<X, Y> {}

class C<X> extends B<X, A> {}

class D<X, Y> extends B<X, Y> with C {}
```

Attempting to compile this code results in a compiler crash with the following stack trace:

```
Unhandled exception:                                                                                                                                                                                                                                                            
Crash when compiling dart:async,                                                                                                                                                                                                                                                
at character offset null:                                                                                                                                                                                                                                                       
NoSuchMethodError: The getter 'length' was called on null.                                                                                                                                                                                                                      
Receiver: null                                                                                                                                                                                                                                                                  
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _intervalListContains (package:kernel/class_hierarchy.dart:1139:36)
#2      _ClassInfo.isSubtypeOf (package:kernel/class_hierarchy.dart:1203:12)                                                          
#3      ClosedWorldClassHierarchy.getClassAsInstanceOf (package:kernel/class_hierarchy.dart:535:15)
#4      ClosedWorldClassHierarchy.getTypeAsInstanceOf (package:kernel/class_hierarchy.dart:542:28)
#5      TypeConstraintGatherer._isInterfaceSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:162:31)
#6      TypeConstraintGatherer._isSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:287:14)
#7      TypeConstraintGatherer._isSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:284:14)
#8      TypeConstraintGatherer._isInterfaceSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:165:12)
#9      TypeConstraintGatherer._isSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:287:14)
#10     TypeConstraintGatherer.trySubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:50:20)
#11     StrongModeMixinInferrer.generateConstraints (package:front_end/src/fasta/type_inference/type_inferrer.dart:1748:16)
#12     StrongModeMixinInferrer.infer (package:front_end/src/fasta/type_inference/type_inferrer.dart:1768:7)
#13     ClosedWorldClassHierarchy._topologicalSortVisit (package:kernel/class_hierarchy.dart:781:48)
#14     ClosedWorldClassHierarchy._initialize (package:kernel/class_hierarchy.dart:705:9)
#15     new ClassHierarchy (package:kernel/class_hierarchy.dart:38:9)
#16     SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:580:21)
#17     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:255:14)
<asynchronous suspension>
#18     CompileTask.buildOutline (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/tool/_fasta/entry_points.dart:236:38)
<asynchronous suspension>         
#19     CompileTask.compile (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/tool/_fasta/entry_points.dart:248:39)
<asynchronous suspension>
#20     compile.<anonymous closure> (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/tool/_fasta/entry_points.dart:192:25)
<asynchronous suspension>                                                                                                                                    
#21     withGlobalOptions.<anonymous closure> (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/tool/_fasta/command_line.dart:398:13)
#22     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103:35)
#23     _rootRun (dart:async/zone.dart:1126)
#24     _CustomZone.run (dart:async/zone.dart:1023)
#25     runZoned (dart:async/zone.dart:1501)                                                          
#26     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103:14)
#27     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:114:41)
#28     withGlobalOptions (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/tool/_fasta/command_line.dart:391:26)
#29     compile (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/tool/_fasta/entry_points.dart:185:18)
<asynchronous suspension>                                                                                                                                                                                                                                          
#30     compileEntryPoint (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/tool/_fasta/entry_points.dart:64:11)
<asynchronous suspension>
#31     main (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)  
```

If the type argument to the mixed in `C` is specified explicitly as `X`, then a compile-time error is generated as follows:

```bash
Error: 'D' can't implement both '#lib1::B<#lib1::D::X, #lib1::D::Y>' and '#lib1::B<#lib1::D::X, #lib1::A>'
class D<X, Y> extends B<X, Y> with C<X> {}
      ^
```

**Comment by peter-ahe-google** [comment]
Nice repro. I suggest that you update tests/language_2/bug32353_test.dart with your smaller repro. The original repro relies on dart:io which can cause problems:

1. The test wont cover configuration where dart:io isn't available.
2. dart:io may change and break the (intent of the) test.
