### ISSUE TITLE
Attempting to run 'flutter drive' in --preview-dart-2 mode causes errors

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#32367]
When trying to run 'flutter drive' in --preview-dart-2 mode we get the following error

```
E/flutter (26449): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (26449): type '(Map<String, String>) => Future<Map<String, dynamic>>' is not a subtype of type '(Map<String, String>) => Future<Map<String, String>>'
E/flutter (26449): #0      _DriverBinding.initServiceExtensions (package:flutter_driver/src/extension/extension.dart:49:27)
E/flutter (26449): #1      new BindingBase (package:flutter/src/foundation/binding.dart:55:5)
E/flutter (26449): #2      new _BindingBase&ServicesBinding (package:flutter_driver/src/extension/extension.dart)
E/flutter (26449): #3      new __BindingBase&ServicesBinding&SchedulerBinding (package:flutter_driver/src/extension/extension.dart)
E/flutter (26449): #4      new ___BindingBase&ServicesBinding&SchedulerBinding&GestureBinding (package:flutter_driver/src/extension/extension.dart)
E/flutter (26449): #5      new ____BindingBase&ServicesBinding&SchedulerBinding&GestureBinding&PaintingBinding (package:flutter_driver/src/extension/extension.dart)
E/flutter (26449): #6      new _____BindingBase&ServicesBinding&SchedulerBinding&GestureBinding&PaintingBinding&RendererBinding (package:flutter_driver/src/extension/extension.dart)
E/flutter (26449): #7      new ______BindingBase&ServicesBinding&SchedulerBinding&GestureBinding&PaintingBinding&RendererBinding&WidgetsBinding (package:flutter_driver/src/extension/extension.dart)
E/flutter (26449): #8      new _DriverBinding (package:flutter_driver/src/extension/extension.dart)
E/flutter (26449): #9      enableFlutterDriverExtension (package:flutter_driver/src/extension/extension.dart:66:7)
E/flutter (26449): #10     main (file:$FH/flutter/dev/benchmarks/complex_layout/test_driver/scroll_perf.dart:9:3)
E/flutter (26449): #11     _startIsolate.<anonymous closure> (dart:isolate/isolate_patch.dart:279:19)
E/flutter (26449): #12     _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
```

**Comment by a-siva** [comment]
See pull request in flutter/flutter https://github.com/flutter/flutter/pull/14897

**Comment by vsmenon** [comment]
@a-siva - looks like a legit type error?  Is the plan to land that pull request?

**Comment by a-siva** [comment]
Yes, but I think there are more issues after that,

**Comment by dgrove** [comment]
Any updates now that flutter/flutter#14897 is merged?

**Comment by a-siva** [comment]
Waiting for Keerti to see if she runs into any errors on the Google3 side of things, we are not aware of any more new issues at this point.

**Comment by keertip** [comment]
Don't see this issue in google3.

**Comment by a-siva** [comment]
@keertip can you confirm that you were able to run tests that use flutter drive in google3, we can close this issue if you confirm.

**Comment by keertip** [comment]
Yes, can run the driver tests in google3. There are some failures, but they are due to strong mode errors in the test code itself, nothing to do with the platform.
