### ISSUE TITLE
Just running a sample of Flutter

### ISSUE THREAD

**Issue by jonnydangerous** [dart-lang/sdk#32361]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4443003`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `AI-171.4443003, JRE 1.8.0_152-release-915-b08x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1920x1080, 1680x1050, 1920x1080  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/33/l8dcpvn94qs1m9r9j8zss0cccfd1nk/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.6, FATAL error: Failed to handle request: {id: 509, method: edit.getFixes, params: {file: /Users/jbrown/Dev/My Flutter/hello_world/lib/main.dart, offset: 685}, clientRequestTime: 1519853546088}
RangeError (index): Invalid value: Not in range 0..690, inclusive: 692
#0      String.codeUnitAt (dart:core-patch/dart:core/string_patch.dart:931)
#1      CorrectionUtils.getLineThis (package:analysis_server/src/services/correction/util.dart:895)
#2      CorrectionUtils.isClassWithEmptyBody (package:analysis_server/src/services/correction/util.dart:1091)
#3      CorrectionUtils.prepareNewClassMemberLocation (package:analysis_server/src/services/correction/util.dart:1128)
#4      FixProcessor._addFix_createMissingOverrides (package:analysis_server/src/services/correction/fix_internal.dart:1535)
<asynchronous suspension>
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:323)
<asynchronous suspension>
#6      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:85)
<asynchronous suspension>
#7      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:242)
<asynchronous suspension>
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:355)

**Comment by devoncarew** [comment]
@scheglov @bwilkerson

**Comment by scheglov** [comment]
I believe that this is the same race condition we see from time to time - the file content has changed, but we use stale resolved AST. We still did not have time to fix it yet.

**Comment by bwilkerson** [comment]
I suspect that's correct. I'm also hoping that the new 'analyzer' package API will help us find and fix such issues via the `AnalysisSession` class.
