### ISSUE TITLE
'..' with '??' crashes Dart2JS

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#32378]
This code in Fasta crashes the Dart2JS compiler:

```dart
  KernelTypeVariableBuilder(
      String name, KernelLibraryBuilder compilationUnit, int charOffset,
      [KernelTypeBuilder bound, TypeParameter actual])
      : actualParameter = actual ?? new TypeParameter(name, null)
          ..fileOffset = charOffset,
        super(name, bound, compilationUnit, charOffset);
```

The current workaround from Johnni is:

```dart
  KernelTypeVariableBuilder(
      String name, KernelLibraryBuilder compilationUnit, int charOffset,
      [KernelTypeBuilder bound, TypeParameter actual])
      : actualParameter = actual != null
            ? (actual..fileOffset = charOffset)
            : (new TypeParameter(name, null)..fileOffset = charOffset),
        super(name, bound, compilationUnit, charOffset);
```

When this bug is solved, we should replace the code in `kernel_type_variable_builder.dart` with its more natural expression.

The crash is:

```
--- Re-run this test:
python tools/test.py -m release -c dart2js -r d8 -a ia32 --host-checked --dart2js-batch --reset-browser-configuration pkg/front_end/test/summary_generator_test
FAILED: dart2js-d8 release_ia32 pkg/front_end/test/kernel_generator_test
Expected: Pass
Actual: Crash
Unexpected compile error.
--- Command "dart2js" (took 02:23.000254s):
DART_CONFIGURATION=ReleaseIA32 sdk/bin/dart2js_developer --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/pkg/front_end/test/kernel_generator_test.dart --out=/b/s/w/ir/cache/builder/sdk/out/ReleaseIA32/generated_compilations/dart2js/pkg_front_end_test_kernel_generator_test/out.js
exit code:
-10
stdout:
Hint: 2 warning(s) suppressed in package:kernel.
Hint: 2 warning(s) and 1 hint(s) suppressed in package:front_end.
Hint: 2 hint(s) suppressed in package:collection.
pkg/front_end/lib/src/fasta/kernel/kernel_library_builder.dart:416:40:
Internal Error: The compiler crashed when compiling this element.
      Map<String, TypeVariableBuilder> computeTypeVariables() {
                                       ^^^^^^^^^^^^^^^^^^^^
The compiler is broken.
When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.
The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.
Please include the following information:
* the name and version of your operating system,
* the Dart SDK build number (build number could not be determined), and
* the entire message you see here (including the full stack trace
  below as well as the source location above).
The compiler crashed: 'file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart': Failed assertion: line 557 pos 12: 'instruction.usedBy.isEmpty': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
#1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
#2      HInstructionList.remove (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:557:12)
#3      HBasicBlock.remove (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:698:17)
#4      SsaLoadElimination.visitFieldSet (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/optimize.dart:2661:25)
#5      HFieldSet.accept (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:1960:39)
#6      SsaLoadElimination.visitBasicBlock (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/optimize.dart:2619:19)
#7      SsaLoadElimination.visitGraph (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/optimize.dart:2578:7)
#8      SsaOptimizerTask.optimize.runPhase.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/optimize.dart:56:46)
#9      CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#10     SsaOptimizerTask.optimize.runPhase (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/optimize.dart:56:7)
#11     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#12     SsaOptimizerTask.optimize.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/optimize.dart:112:14)
#13     CompilerTask.measure (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#14     SsaOptimizerTask.optimize (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/optimize.dart:66:5)
#15     SsaFunctionCompiler.compile (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/ssa.dart:45:15)
#16     JavaScriptBackend.codegen (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/backend.dart:848:43)
#17     ElementCodegenWorkItem.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/element_strategy.dart:176:21)
#18     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:784:70)
#19     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:784:32)
#21     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:782:28)
#23     CompilerDiagnosticReporter.withCurrentElement (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:1156:15)
#24     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:780:18)
#25     EnqueuerStrategy.processWorkItem (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/enqueue.dart:511:6)
#26     CodegenEnqueuer.forEach (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:224:20)
#27     Compiler.emptyQueue.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:776:16)
#28     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#29     Compiler.emptyQueue (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:775:14)
#30     Compiler.processQueue.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:797:7)
#31     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#32     Compiler.processQueue (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:794:14)
#33     Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:640:9)
#34     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#35     Compiler.compileLoadedLibraries (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:534:16)
#36     Compiler.runInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:488:5)
<asynchronous suspension>
#37     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:313:38)
#38     new Future.sync (dart:async/future.dart:222)
#39     Compiler.run.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:313:20)
#40     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#41     Compiler.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:310:41)
#42     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/apiimpl.dart:265:25)
#43     _RootZone.runUnary (dart:async/zone.dart:1381)
#44     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#45     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#46     _Future._propagateToListeners (dart:async/future_impl.dart:662)
#47     _Future._completeWithValue (dart:async/future_impl.dart:477)
#48     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#49     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#50     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#51     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

**Comment by parlough** [comment]
I couldn't determine the commit that fixed this, but I can't reproduce it with a variety of code structures. Likely some changes in the null safety migration.

The code with the workaround specified here no longer exists as well, so it doesn't need to be updated back to the original style.
