### ISSUE TITLE
Analyzer crash on Windows 10

### ISSUE THREAD

**Issue by rasdev** [dart-lang/sdk#32388]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA PS-173.4548.32`
- `2.0.0-dev.31.0`
- `PS-173.4548.32, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1200, 1920x1200`

# Exception

Please append the contents of:
file://C:\Users\Gateway\AppData\Local\Temp\report.txt
[report.txt](https://github.com/dart-lang/sdk/files/1775746/report.txt)

```
Dart analysis server, SDK version 2.0.0-dev.31.0, server version 1.18.7, error: Analysis failed: C:\dev\dart\angular_components_example\lib\src\material_popup_demo\material_popup_demo.dart
RangeError (byteOffset): Invalid value: Not in range 0..8656, inclusive: 36661
#0      _ByteDataView.getUint32 (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:4231)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:72)
#2      BufferContext.derefObject (package:front_end/src/base/flat_buffers.dart:54)
#3      StringReader.read (package:front_end/src/base/flat_buffers.dart:662)
#4      Reader.vTableGet (package:front_end/src/base/flat_buffers.dart:644)
#5      _AnalysisDriverUnitErrorImpl.uniqueName (package:analyzer/src/summary/format.dart:1009)
#6      AnalysisDriver._getErrorsFromSerialized (package:analyzer/src/dart/analysis/driver.dart:1440)
#7      AnalysisDriver._getAnalysisResultFromBytes (package:analyzer/src/dart/analysis/driver.dart:1417)
#8      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1178)
<asynchronous suspension>
#9      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1010)
<asynchronous suspension>
#10     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1889)
<asynchronous suspension>
#11     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832)

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
