### ISSUE TITLE
"The getter 'name' was called on null" in analysis server.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#32398]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4548.28`
- `1.24.0-dev.6.6`
- `IC-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
```
Dart analysis server, SDK version 1.24.0-dev.6.6, server version 1.18.0, error: Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in FunctionDeclarationImpl in FunctionDeclarationStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      Visitor.checkIdentifier (package:linter/src/rules/non_constant_identifier_names.dart:50)
#3      Visitor.visitFormalParameterList.<anonymous closure> (package:linter/src/rules/non_constant_identifier_names.dart:63)
#4      Object&ListMixin.forEach (dart:collection/list.dart:63)
#5      Visitor.visitFormalParameterList (package:linter/src/rules/non_constant_identifier_names.dart:61)
#6      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4849)
#7      ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2757)
#8      List.forEach (dart:core-patch/growable_array.dart:256)
#9      ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2755)
#10     UnifyingAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:3020)
#11     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4849)
#12     GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5781)
#13     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#14     UnifyingAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:3047)
#15     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5774)
#16     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5202)
#17     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#18     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026)
#19     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5197)
#20     FunctionDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5250)
#21     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#22     UnifyingAstVisitor.visitFunctionDeclarationStatement (package:analyzer/dart/ast/visitor.dart:3030)
#23     FunctionDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5246)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#25     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#26     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#27     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#28     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#29     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#30     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#31     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#32     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#33     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#34     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#35     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#36     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#37     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5204)
#38     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#39     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026)
#40     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5197)
#41     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#42     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#43     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#44     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#45     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#46     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:237)
#47     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120)
#48     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#49     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:119)
#50     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:999)
#51     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#52     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#53     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:854)
<asynchronous suspension>
#54     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#55     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#56     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#57     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#58     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#59     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#60     _rootRun (dart:async/zone.dart:1120)
#61     _CustomZone.run (dart:async/zone.dart:1001)
#62     runZoned (dart:async/zone.dart:1467)
#63     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#64     Driver.start (package:analysis_server/src/server/driver.dart:473)
#65     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#66     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#67     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1520035707930 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/bug_report_test.dart","errors":[]}}
1520035707987 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/crash_reporting_test.dart","errors":[]}}
1520035708007 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/cache_test.dart","errors":[]}}
1520035708034 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/stop_test.dart","errors":[]}}
1520035708045 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/application_package_test.dart","errors":[]}}
1520035708087 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/dart/pub_get_test.dart","errors":[]}}
1520035708106 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/utils_test.dart","errors":[]}}
1520035708117 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/vmservice_test.dart","errors":[]}}
1520035708139 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/runner/flutter_command_test.dart","errors":[]}}
1520035708157 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/runner/flutter_command_runner_test.dart","errors":[]}}
1520035708177 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/asset_bundle_package_fonts_test.dart","errors":[]}}
1520035708193 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/asset_bundle_variant_test.dart","errors":[]}}
1520035708206 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/asset_test.dart","errors":[]}}
1520035708216 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/hot_test.dart","errors":[]}}
1520035708252 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/ios/code_signing_test.dart","errors":[]}}
1520035708287 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/ios/ios_workflow_test.dart","errors":[]}}
1520035708320 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/ios/mac_test.dart","errors":[]}}
1520035708344 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/ios/devices_test.dart","errors":[]}}
1520035708359 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/ios/xcodeproj_test.dart","errors":[]}}
1520035708393 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/ios/simulators_test.dart","errors":[]}}
1520035708423 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/ios/cocoapods_test.dart","errors":[]}}
1520035708438 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/artifacts_test.dart","errors":[]}}
1520035708468 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/compile_test.dart","errors":[{"severity":"ERROR","type":"STATIC_TYPE_WARNING","lo
1520035708503 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/version_test.dart","errors":[]}}
1520035708551 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/devfs_test.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file":"/
1520035708572 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/flutter_manifest_test.dart","errors":[]}}
1520035708592 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/protocol_discovery_test.dart","errors":[{"severity":"ERROR","type":"STATIC_TYPE_W
1520035708608 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/android/gradle_test.dart","errors":[]}}
1520035708632 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_tools/test/android/android_sdk_test.dart","errors":[]}}
1520035708666 <= {"event":"server.error","params":{"isFatal":false,"message":"Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in FunctionDeclarationImpl i
```
```
Dart analysis server, SDK version 1.24.0-dev.6.6, server version 1.18.0, error: Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in FunctionDeclarationImpl in FunctionDeclarationStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      Visitor.checkIdentifier (package:linter/src/rules/non_constant_identifier_names.dart:50)
#3      Visitor.visitFormalParameterList.<anonymous closure> (package:linter/src/rules/non_constant_identifier_names.dart:63)
#4      Object
```

**Comment by bwilkerson** [comment]
@pq

**Comment by pq** [comment]
Thanks!  It looks like we're asking for the name of a `null` SimpleIdentifier here:

https://github.com/dart-lang/linter/blob/master/lib/src/rules/non_constant_identifier_names.dart#L50

**_EDIT:_** It looks from the trace above like this is happening when a formal parameter is asked for it's identifier which is returning `null`.  I think that's been fixed already in https://github.com/dart-lang/linter/commit/ced90f3bb2e182cba56811e553b5673869b71128.

@gspencergoog : it  looks like you've got a pretty old SDK; if you update, you shouldn't hit this anymore.

**Comment by gspencergoog** [comment]
This was a path issue: I had my homebrew path before my flutter/bin in my path.  Works fine if I set the PATH correctly.
