### ISSUE TITLE
Analysis failed: ... UnimplementedError in summary/link.dart

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#32400]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4548.28`
- `1.24.0-dev.6.6`
- `IC-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1680x1050  Retina`

# Exception
```
Dart analysis server, SDK version 1.24.0-dev.6.6, server version 1.18.0, error: Analysis failed: /Users/gspencer/code/flutter/packages/flutter_tools/test/dart_dependencies_test.dart context: exception_20180302_161237_462
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1096)
#1      CompilationUnitElementForLink.resolveTypeRef.getTypeArgument (package:analyzer/src/summary/link.dart:1103)
#2      new List.generate (dart:core/list.dart:142)
#3      ClassElementForLink_Class.buildType (package:analyzer/src/summary/link.dart:647)
#4      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1113)
#5      VariableElementForLink.declaredType (package:analyzer/src/summary/link.dart:5196)
#6      VariableElementForLink.type (package:analyzer/src/summary/link.dart:5287)
#7      PropertyAccessorElementForLink_Variable.returnType (package:analyzer/src/summary/link.dart:4548)
#8      PropertyAccessorElementForLink_Variable.asStaticType (package:analyzer/src/summary/link.dart:4501)
#9      ExprTypeComputer._doPushReference (package:analyzer/src/summary/link.dart:2485)
#10     ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2073)
#11     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:4957)
#12     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:4808)
#13     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#14     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#15     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5226)
#16     FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2700)
#17     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:673)
#18     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1308)
#19     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3672)
#20     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3408)
#21     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3330)
#22     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#23     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#24     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#25     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#26     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#27     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#28     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#29     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#30     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3373)
#31     Linker.link (package:analyzer/src/summary/link.dart:3897)
#32     relink (package:analyzer/src/summary/link.dart:132)
#33     link (package:analyzer/src/summary/link.dart:113)
#34     new LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:116)
#35     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#36     new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:115)
#37     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#38     new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:53)
#39     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1092)
#40     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:989)
#41     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#42     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#43     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:854)
<asynchronous suspension>
#44     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#45     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#46     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#47     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#48     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#49     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#50     _rootRun (dart:async/zone.dart:1120)
#51     _CustomZone.run (dart:async/zone.dart:1001)
#52     runZoned (dart:async/zone.dart:1467)
#53     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#54     Driver.start (package:analysis_server/src/server/driver.dart:473)
#55     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#56     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1520035718349 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/platform_channel/lib/main.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location"
1520035718939 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/dev/benchmarks/complex_layout/test_driver/scroll_perf.dart","errors":[]}}
1520035719281 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/dev/benchmarks/complex_layout/test_driver/scroll_perf_test.dart","errors":[]}}
1520035719301 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/dev/benchmarks/complex_layout/test_driver/semantics_perf_test.dart","errors":[]}}
1520035719308 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/dev/benchmarks/complex_layout/test_driver/semantics_perf.dart","errors":[]}}
1520035719404 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/dev/benchmarks/complex_layout/lib/main.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","locat
1520035719638 => {"id":"9","method":"edit.getAssists","params":{"file":"/Users/gspencer/code/flutter/packages/flutter/lib/src/material/slider_theme.dart","offset":1734,"length":0},"clientRequestTime":
1520035720075 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/test/widgets_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERR
1520035720076 <= {"id":"9","result":{"assists":[{"message":"Convert into block documentation comment","edits":[{"file":"/Users/gspencer/code/flutter/packages/flutter/lib/src/material/slider_theme.dart
1520035720118 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/test/translations_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIM
1520035720170 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/test/override_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ER
1520035720210 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/test/date_time_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_E
1520035720265 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/test/time_picker_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME
1520035720311 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/test/basics_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERRO
1520035720359 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/test/date_picker_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME
1520035720362 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/lib/flutter_localizations.dart","errors":[]}}
1520035720427 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/lib/src/l10n/date_localizations.dart","errors":[]}}
1520035720541 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/lib/src/l10n/localizations.dart","errors":[{"severity":"INFO","type":"LINT","l
1520035720622 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/lib/src/widgets_localizations.dart","errors":[]}}
1520035720676 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_localizations/lib/src/material_localizations.dart","errors":[{"severity":"ERROR","type":"SYN
1520035720871 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/platform_channel_swift/test_driver/button_tap_test.dart","errors":[]}}
1520035721266 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/platform_channel_swift/test_driver/button_tap.dart","errors":[]}}
1520035721291 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/examples/platform_channel_swift/lib/main.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","loc
1520035721292 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1520035727893 => {"id":"10","method":"edit.getFixes","params":{"file":"/Users/gspencer/code/flutter/packages/flutter/lib/src/material/slider_theme.dart","offset":1062},"clientRequestTime":152003572789
1520035727908 <= {"id":"10","result":{"fixes":[]}}
1520035727917 => {"id":"11","method":"edit.getAssists","params":{"file":"/Users/gspencer/code/flutter/packages/flutter/lib/src/material/slider_theme.dart","offset":1259,"length":0},"clientRequestTime"
1520035727918 <= {"id":"11","result":{"assists":[]}}
1520035954236 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1520035957483 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/gspencer/code/flutter/packages/flutter_tools/test/dart_dependencies_test.dart context: exception_2
```
```
Dart analysis server, SDK version 1.24.0-dev.6.6, server version 1.18.0, error: Analysis failed: /Users/gspencer/code/flutter/packages/flutter_tools/test/dart_dependencies_test.dart context: exception_20180302_161237_462
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1096)
#1      CompilationUnitElementForLink.resolveTypeRef.getTypeArgument (package:analyzer/src/summary/link.dart:1103)
#2      new List.generate (dart:core/list.dart:142)
#3      ClassElementForLink_Class.buildType (package:analyzer/src/summary/link.dart:647)
#4      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1113)
#5      VariableElementForLink.declaredType (package:analyzer/src/summary/link.dart:5196)
#6      VariableElementForLink.type (package:analyzer/src/summary/link.dart:5287)
#7      PropertyAccessorElementForLink_Variable.returnType (package:analyzer/src/summary/link.dart:4548)
#8      PropertyAccessorElementForLink_Variable.asStaticType (package:analyzer/src/summary/link.dart:4501)
#9      ExprTypeComputer._doPushReference (package:analyzer/src/summary/link.dart:2485)
#10     ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2073)
#11     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:4957)
#12     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:4808)

**Comment by matanlurey** [comment]
@gspencergoog:

You seem to have a _quite_ old version of the analyzer/server:
`Dart analysis server, SDK version 1.24.0-dev.6.6,`

... this is from several quarters ago. Time to update/upgrade something?

**Comment by bwilkerson** [comment]
Closing as obsolete. Please let us know if you see a similar issue after updating to the latest 2.0-dev version.

**Comment by gspencergoog** [comment]
Yeah, it turned out to be a path problem (I had the homebrew bin in my path before the flutter bin).  I'm amazed it worked for as long as it did...
