### ISSUE TITLE
Dart2JS strong mode / kernel crash

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#32406]
Dart VM version: 2.0.0-dev.32.0

**foo.dart**
```dart
import 'dart:async';

void main() {
  new Future.value(null).then((_) {});
}
```

```
$ dart2js --use-kernel --strong foo.dart
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.0.0-dev.32.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Interpolated value #1 is not an Expression or List of Expressions: [VariableUse(f), Instance of 'LiteralNull', null]
#0      InstantiatorGeneratorVisitor.error (package:js_ast/src/template.dart:156)
#1      InstantiatorGeneratorVisitor.visitSplayableExpression.<anonymous closure>.toExpression (package:js_ast/src/template.dart:223)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:343)
#4      List.addAll (dart:core-patch/dart:core/growable_array.dart:194)
#5      InstantiatorGeneratorVisitor.handleCallOrNew.<anonymous closure> (package:js_ast/src/template.dart:582)
#6      InstantiatorGeneratorVisitor.visitReturn.<anonymous closure> (package:js_ast/src/template.dart:450)
#7      Template.instantiate (package:js_ast/src/template.dart:108)
#8      JsBuilder.statement (package:js_ast/src/builder.dart:216)
#9      ParameterStubGenerator.generateParameterStub (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_emitter/parameter_stub_generator.dart:190)
#10     ParameterStubGenerator.generateParameterStubs (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_emitter/parameter_stub_generator.dart:316)
#11     ProgramBuilder._generateParameterStubs (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_emitter/program_builder/program_builder.dart:979)
#12     ProgramBuilder._buildMethod (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_emitter/program_builder/program_builder.dart:945)
#13     ProgramBuilder._buildClass.visitMember (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_emitter/program_builder/program_builder.dart:695)
#14     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#15     ProgramBuilder._buildClass (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_emitter/program_builder/program_builder.dart:742)
#16     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#17     ProgramBuilder.buildProgram.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_emitter/program_builder/program_builder.dart:212)
#18     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#19     ProgramBuilder.buildProgram (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_emitter/program_builder/program_builder.dart:211)
#20     Emitter.emitProgram (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_emitter/full_emitter/emitter.dart:1615)
#21     CodeEmitterTask.assembleProgram.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_emitter/code_emitter_task.dart:214)
#22     CompilerTask.measure (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63)
#23     CodeEmitterTask.assembleProgram (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_emitter/code_emitter_task.dart:180)
#24     JavaScriptBackend.assembleProgram (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_backend/backend.dart:885)
#25     Compiler.compileLoadedLibraries.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:645)
#26     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#27     Compiler.compileLoadedLibraries (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:534)
#28     Compiler.runInternal (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:488)
<asynchronous suspension>
#29     Compiler.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:313)
#30     new Future.sync (dart:async/future.dart:222)
#31     Compiler.run.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:313)
#32     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#33     Compiler.run (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:310)
#34     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/apiimpl.dart:265)
#35     _RootZone.runUnary (dart:async/zone.dart:1381)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#37     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#38     _Future._propagateToListeners (dart:async/future_impl.dart:662)
#39     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#42     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)

**Comment by lexaknyazev** [comment]
Can't reproduce with `2.0.0-dev.59.0`.

**Comment by sigmundch** [comment]
Sorry we didn't update the bug on our end when it was fixed. Thanks so much for following up and checking again!
