### ISSUE TITLE
Autocomplete error in VS Code working on flutter

### ISSUE THREAD

**Issue by RexRonin** [dart-lang/sdk#32404]
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

writing flutter code in a form field, in particular editing the properties of a text field

### Versions

- Dart SDK 1.24.3
- Visual Studio Code 1.20.1
- Dart Code 2.9.2

### Analyzer Info

The analyzer was launched using the arguments:

```text
/opt/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.9.2
```

### Exception

Failed to handle completion domain request: {id: 9227, method: completion.getSuggestions, params: {file: /home/simon/Development/demobook/concierge/lib/views/create_user.dart, offset: 3447}}

```text
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _OpTypeAstVisitor.visitNamedExpression.<anonymous closure> (package:analysis_server/src/services/completion/dart/optype.dart:741)
#3      Object&ListMixin.firstWhere (dart:collection/list.dart:127)
#4      _OpTypeAstVisitor.visitNamedExpression (package:analysis_server/src/services/completion/dart/optype.dart:739)
#5      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7764)
#6      new OpType.forCompletion (package:analysis_server/src/services/completion/dart/optype.dart:117)
#7      DartCompletionRequestImpl.opType (package:analysis_server/src/services/completion/dart/completion_manager.dart:185)
#8      DartCompletionRequestImpl.includeIdentifiers (package:analysis_server/src/services/completion/dart/completion_manager.dart:159)
#9      ImportedReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/imported_reference_contributor.dart:44)
<asynchronous suspension>
#10     DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:76)
<asynchronous suspension>
#11     CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:101)
<asynchronous suspension>
#12     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:210)
<asynchronous suspension>
#13     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:137)
#14     _rootRun (dart:async/zone.dart:1120)
#15     _CustomZone.run (dart:async/zone.dart:1001)
#16     _CustomZone.runGuarded (dart:async/zone.dart:901)
#17     runZoned (dart:async/zone.dart:1465)
#18     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:134)
#19     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:975)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#21     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:971)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     _CustomZone.runGuarded (dart:async/zone.dart:901)
#25     runZoned (dart:async/zone.dart:1465)
#26     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:970)
#27     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:168)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#29     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:159)
#30     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#31     _rootRunUnary (dart:async/zone.dart:1128)
#32     _CustomZone.runUnary (dart:async/zone.dart:1012)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#39     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#40     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#41     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#43     _rootRunUnary (dart:async/zone.dart:1128)
#44     _CustomZone.runUnary (dart:async/zone.dart:1012)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#50     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#51     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#52     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#53     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#54     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#55     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#56     _rootRunUnary (dart:async/zone.dart:1128)
#57     _CustomZone.runUnary (dart:async/zone.dart:1012)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#62     _StreamController._add (dart:async/stream_controller.dart:667)
#63     _StreamController.add (dart:async/stream_controller.dart:613)
#64     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#65     _rootRunUnary (dart:async/zone.dart:1132)
#66     _CustomZone.runUnary (dart:async/zone.dart:1012)
#67     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#68     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#69     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#70     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#71     _StreamController._add (dart:async/stream_controller.dart:667)
#72     _StreamController.add (dart:async/stream_controller.dart:613)
#73     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#74     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#75     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#76     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#77     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#78     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/78712
