### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by tomialagbe** [dart-lang/sdk#32413]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4443003`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `AI-171.4443003, JRE 1.8.0_152-release-915-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768, 1600x900`

# Exception

Please append the contents of:
file://C:\Users\Tomi\AppData\Local\Temp\report536.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.6, error: Captured exception
NoSuchMethodError: The getter 'lineStarts' was called on null.
Receiver: null
Tried calling: lineStarts
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:478)
#2      FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:220)
#3      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#4      FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:216)
#5      FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:289)
#6      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:870)
<asynchronous suspension>
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1889)
<asynchronous suspension>
#8      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832)
#9      new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#10     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#11     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Do you use or used Angular plugin?
Update Dar SDK, the plugin, remove `C:\Users\YourUserName\AppData\Local\.dartServer\.analysis-driver` and restart Dart Analysis Server.

**Comment by tomialagbe** [comment]
I'll try that.
Thanks 

Sent from Yahoo Mail on Android 
 
  On Mon, 5 Mar 2018 at 18:07, Konstantin Scheglov<notifications@github.com> wrote:   
Do you use or used Angular plugin?
Update Dar SDK, the plugin, remove C:\Users\YourUserName\AppData\Local\.dartServer\.analysis-driver and restart Dart Analysis Server.

**Comment by tomialagbe** [comment]
It worked. Thanks.
