### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by MagicianKing** [dart-lang/sdk#32424]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-173.4548.28`
- `1.12.0`
- `IU-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/bl/pzv7w8017kd91x9x0rdg5krw0000gn/T/report.txt

```
Dart analysis server, SDK version 1.12.0, server version 1.9.0, FATAL error: The null object does not have a getter 'isInSystemLibrary'.

NoSuchMethodError: method not found: 'isInSystemLibrary'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      SdkCachePartition.contains (package:analyzer/src/generated/engine.dart:11128)
#3      AnalysisCache.get (package:analyzer/src/generated/engine.dart:134)
#4      AnalysisContextImpl_CycleBuilder._createLibraryOrNull (package:analyzer/src/generated/engine.dart:5232)
#5      AnalysisContextImpl_CycleBuilder._addDependency (package:analyzer/src/generated/engine.dart:5050)
#6      AnalysisContextImpl_CycleBuilder._computeLibraryDependenciesFromDirectives (package:analyzer/src/generated/engine.dart:5121)
#7      AnalysisContextImpl_CycleBuilder._computeLibraryDependencies (package:analyzer/src/generated/engine.dart:5089)
#8      AnalysisContextImpl_CycleBuilder._addDependency (package:analyzer/src/generated/engine.dart:5052)
#9      AnalysisContextImpl_CycleBuilder._computeLibraryDependenciesFromDirectives (package:analyzer/src/generated/engine.dart:5115)
#10     AnalysisContextImpl_CycleBuilder._computeLibraryDependencies (package:analyzer/src/generated/engine.dart:5089)
#11     AnalysisContextImpl_CycleBuilder.computeCycleContaining (package:analyzer/src/generated/engine.dart:5012)

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
