### ISSUE TITLE
dart2js fails no_such_method_t01 test on d8 and on chrome-csp-minified

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#32434]
The test
co19/Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/no_such_method_t01
is failing with a RuntimeError on the d8 runtime, and on the chrome-csp-minified runtime.

It may be a problem with the test not using the Symbol or MirrorsUsed annotation.
A failing run is at https://ci.chromium.org/buildbot/client.dart/dart2js-linux-d8-minified-3-5-be/10263
The error is 
DART_CONFIGURATION=ReleaseX64 /b/build/slave/dart2js-linux-d8-minified-3-5-be/build/sdk/third_party/d8/linux/d8 out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js /b/build/slave/dart2js-linux-d8-minified-3-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Getter_Access_and_Method_Extraction_no_such_method_t01/out.js
exit code:
1
stdout:
Warning: 'gaf' is used reflectively but not in MirrorsUsed. This will break minified code.
out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: Expect.equals(expected: <Symbol("someGetter")>, actual: <Symbol("gaf")>) fails.
          throw e;
          ^
Expect.equals(expected: <Symbol("someGetter")>, actual: <Symbol("gaf")>) fails.
    at Object.c (/b/build/slave/dart2js-linux-d8-minified-3-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Getter_Access_and_Method_Extraction_no_such_method_t01/out.js:503:3)
    at Object.n (/b/build/slave/dart2js-linux-d8-minified-3-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Getter_Access_and_Method_Extraction_no_such_method_t01/out.js:1271:23)
    at Object.F (/b/build/slave/dart2js-linux-d8-minified-3-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Getter_Access_and_Method_Extraction_no_such_method_t01/out.js:1276:3)
    at aX.D (/b/build/slave/dart2js-linux-d8-minified-3-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Getter_Access_and_Method_Extraction_no_such_method_t01/out.js:1329:3)
    at aX.gaf (/b/build/slave/dart2js-linux-d8-minified-3-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Getter_Access_and_Method_Extraction_no_such_method_t01/out.js:133:62)
    at aK (/b/build/slave/dart2js-linux-d8-minified-3-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Getter_Access_and_Method_Extraction_no_such_method_t01/out.js:1323:3)
    at action (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at /b/build/slave/dart2js-linux-d8-minified-3-5-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Getter_Access_and_Method_Extraction_no_such_method_t01/out.js:1496:39
--- Re-run this test:
python tools/test.py -m release -c dart2js -r d8 --minified --use-sdk --dart2js-batch --reset-browser-configuration co19/Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/no_such_method_t01

**Comment by sigmundch** [comment]
I'll mark this test as fail-by-design => it uses dart:mirrors, which we no longer support.
