### ISSUE TITLE
Map.update blows up when key not found

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#32437]
```dart
void main() {
  var m = {1: 2, 2: 3, 3: 5};
  m.update(3, (e) => 7);
  print(m);
  m.update(4, (e) => 7);
  print(m);
}
```

```shell
$ dart --version
Dart VM version: 2.0.0-dev.32.0 (Thu Mar 1 18:39:53 2018 +0100) on "macos_x64"

$ dart b.dart
{1: 2, 2: 3, 3: 7}
Unhandled exception:
NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _HashVMBase&MapMixin.update (dart:collection/maps.dart:117)
#2      main (file:///Users/srawlins/code/dart-repo4/sdk/b.dart:5:5)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

I believe the error is [here](https://github.com/dart-lang/sdk/blob/master/sdk/lib/collection/maps.dart#L116..L118): 😄 

```dart
    if (ifAbsent == null) {
      return this[key] = ifAbsent();
    }
```

A one-character fix, although I imagine this speaks to the need for some more tests 😄

**Comment by srawlins** [comment]
While we're at it, it would be good to document which type of error is thrown if key is not in the map, and no ifAbsent closure is passed (ArgumentError).

**Comment by lrhn** [comment]
We try not to overspecify which errors are thrown. It allows dart2js to get away with repurposing JS errors without worrying about getting the exact same Dart error type as the VM implementation.
It's an `Error`, and the error will describe the problem to some extend, but beyond that we make no promises.

**Comment by srawlins** [comment]
Ah I see. Fair enough.

**Comment by srawlins** [comment]
This was fixed at some point:

```
$ dart ~/32437.dart 
{1: 2, 2: 3, 3: 7}
Unhandled exception:
Invalid argument (key): Key not in map.: 4
#0      __InternalLinkedHashMap&_HashVMBase&MapMixin.update (dart:collection/maps.dart:155:5)
#1      main (file:///Users/srawlins/32437.dart:5:5)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
