### ISSUE TITLE
Handle missing references better

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#32449]
We've seen this stack trace reported in flutter/flutter#15206:

```
compiler message: Unhandled exception:
Crash when compiling file:///Users/tlarsen/Documents/Projects/checklist/lib/main.dart,
at character offset null:
Reference to root::package:checklist/src/note.dart is not bound to an AST node. A library was expected
#0      Reference.asLibrary (package:kernel/ast.dart:217)
#1      LibraryDependency.targetLibrary (package:kernel/ast.dart:495)
#2      SourceLoader.computeFullProgram (package:front_end/src/fasta/source/source_loader.dart:570)
#3      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:580)
#4      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:252)
<asynchronous suspension>
#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:166)
<asynchronous suspension>
#6      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103)
#7      _rootRun (dart:async/zone.dart:1126)
#8      _CustomZone.run (dart:async/zone.dart:1023)
#9      runZoned (dart:async/zone.dart:1501)
#10     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103)
#11     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:58)
<asynchronous suspension>
#12     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#13     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:207)
#14     new Future.<anonymous closure> (dart:async/future.dart:174)
#15     _rootRun (dart:async/zone.dart:1122)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#22     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#23     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#24     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

I think we could improve the user experience if we detect this situation and convert it to a deprected_InputError.

We can directly detect this particular situation, but I practice it would be impossible finding all possible null references. So it might make sense to throw a named exception when this situation occurs in kernel.

**Comment by peter-ahe-google** [comment]
Another stack trace:

```
compiler message: Unhandled exception:
Reference to root::package:flutter/src/widgets/framework.dart is not bound to an AST node. A library was expected
#0      Reference.asLibrary (package:kernel/ast.dart:217)
#1      _PrivateName.library (package:kernel/ast.dart:4714)
#2      CanonicalName.getChildFromQualifiedName (package:kernel/canonical_name.dart:110)
#3      CanonicalName.getChildFromMember (package:kernel/canonical_name.dart:116)
#4      Class.computeCanonicalNames (package:kernel/ast.dart:787)
#5      Library.computeCanonicalNames (package:kernel/ast.dart:397)
#6      LimitedBinaryPrinter.computeCanonicalNames (package:kernel/binary/limited_ast_to_binary.dart:36)
#7      BinaryPrinter.writeProgramFile (package:kernel/binary/ast_to_binary.dart:283)
#8      FrontendCompiler.compile (package:vm/frontend_server.dart:229)
<asynchronous suspension>
#9      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:29)
<asynchronous suspension>
#10     starter (package:frontend_server/server.dart:107)
<asynchronous suspension>
#11     main (file:///b/build/slave/Mac_Engine/build/src/flutter/frontend_server/bin/starter.dart:6)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by peter-ahe-google** [comment]
@jensjoha any ideas for how we can detect when this happens?

**Comment by jensjoha** [comment]
I've responded in https://github.com/flutter/flutter/issues/15206 -- basically I think it's an already fixed error. I will try to see if I can reproduce though (with the old version, then if it goes away with the fix).

**Comment by jensjoha** [comment]
So I reproduced the 2nd stack trace with the old version of flutter (and it doesn't happen on the current version).
As such I think we can lower the priority on this issue, what do you think @peter-ahe-google ?

One note though, in the flutter issue I claimed that 57a01968ed85eb25cf5fe02fe3b64f2776d8f085 was a workaround which is probably not the case as this crash happens when serializing, not when building outlines (the first stack trace does btw) - so maybe we should either (as Peter suggests) add some checks, or we should add some fallback to the flutter frontend_server to retry without initializing from dill when there is a failure when we have initialized from dill.
