### ISSUE TITLE
Boot up error while starting my IDEA

### ISSUE THREAD

**Issue by zarub2k** [dart-lang/sdk#32444]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4548.28`
- `2.0.0-dev.16.0`
- `IC-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1200`

# Exception

Please append the contents of:
file://C:\Users\tham\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-dev.16.0, server version 1.18.4, error: Analysis failed: C:\work\personal\repos\public\flutterhustle\lib\main.dart context: exception_20180307_104339_680
Can't find dart:async
#0      KernelTarget.computeCoreTypes (package:front_end/src/fasta/kernel/kernel_target.dart:543)
#1      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:248)
<asynchronous suspension>
#2      KernelDriver._compileCycle.<anonymous closure>.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:447)
<asynchronous suspension>
#3      PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#4      KernelDriver._compileCycle.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:446)
<asynchronous suspension>
#5      PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#6      KernelDriver._compileCycle (package:front_end/src/incremental/kernel_driver.dart:384)
<asynchronous suspension>
#7      KernelDriver.getKernelSequence.<anonymous closure>.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:330)
<asynchronous suspension>
#8      PerformanceLog.runAsync (package:fron

**Comment by bwilkerson** [comment]
The work to port analyzer to kernel is incomplete, so the exception is not too surprising. What's more surprising is that the code in question is running at all. Could you please send us the content of your analysis options file and any additional command-line arguments you have configured (in IntelliJ) to send to the analysis server?

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
