### ISSUE TITLE
DDC: Error message with little information

### ISSUE THREAD

**Issue by akaufmann** [dart-lang/sdk#32470]
```dart
main() {
  var a = null;
  
  // this works
  // print(a == 5);
 
  print(a < 5);
}
```

Exception
```dart
Unhandled exception:
NoSuchMethodError: The method '<' was called on null.
Receiver: null
Tried calling: <(5)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      main (file:///Users/akaufmann/devel/dart/error.dart:7:11)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Exception with dart2js
```js
Uncaught TypeError: C.JSNull_methods.$lt is not a function
```

Exception with DDC
```js
Uncaught
```

```dart
core.NoSuchMethodError.withInvocation {
  requireMap:{prefix: undefined, name: "_@r6", parentMap: undefined, unnormalized: false, url: "/_@r6.js", …}
  requireModules:null
  requireType:"require"
  Symbol(_arguments):[5]
  Symbol(_error):Error at Object.dart.throw (http://localhost:8080/packages/$sdk/dev_compiler/amd/dart_sdk.js:4909:29) at Object.dart.defaultNoSuchMethod (http://localhost:8080/packages/$sdk/dev_compiler/amd/dart_sdk.js:5007:15) at Object.dart.noSuchMethod (http://localhost:8080/packages/$sdk/dev_compiler/amd/dart_sdk.js:5002:27) at callNSM (http://localhost:8080/packages/$sdk/dev_compiler/amd/dart_sdk.js:4673:19) at Object.dart._checkAndCall (http://localhost:8080/packages/$sdk/dev_compiler/amd/dart_sdk.js:4681:16) at Object.dart.callMethod (http://localhost:8080/packages/$sdk/dev_compiler/amd/dart_sdk.js:4765:17) at Object.dart.dsend (http://localhost:8080/packages/$sdk/dev_compiler/amd/dart_sdk.js:4768:17) at Object.main.main (http://localhost:8080/main.ddc.js:33:21) at http://localhost:8080/main.dart.bootstrap.js:129:12 at Object.execCb (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1696:33) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:878:55) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.enable (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1176:22) at Module.init (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:788:26) at callGetModule (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1203:63) at Object.completeLoad (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1590:21) at HTMLScriptElement.onScriptLoad (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1717:29)
  Symbol(_existingArgumentNames):null
  Symbol(_memberName):_internal.Symbol.new {Symbol(_name): "<"}
  Symbol(_namedArguments):LinkedMap.new {Symbol(_map): Map(0), Symbol(_keyMap): Map(0), 
  Symbol(_modifications): 0}
  Symbol(_receiver):null
  ...
}
```

`
Dart VM version: 2.0.0-dev.33.0 (Tue Mar 6 16:02:31 2018 +0100) on "macos_x64"
`

**Comment by vsmenon** [comment]
With DDC tip, I'm now seeing:

```
NoSuchMethodError: method not found: '<'
Receiver: null
Arguments: [5] Error
```

If you're still seeing a problem, please re-open and let us how you're running (e.g., build_runner)?
