### ISSUE TITLE
Frontend seems to fail on flutter_driver tests

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#32477]
Following https://github.com/flutter/flutter/pull/15344 flutter dependency update class_hierarchy of compiler seems to fail on flutter_driver tests:

``` $FH/flutter/packages/flutter_driver  $  ../../bin/flutter test --preview-dart-2
Running "flutter packages get" in flutter_driver...          0.6s
00:00 +0: ...flutter/packages/flutter_driver/test/flutter_driver_test.dart     compiler message: Unhandled exception:
compiler message: Crash when compiling file:///tmp/dart_test_listenerGCXYFX/listener.dart,
compiler message: at character offset null:
compiler message: NoSuchMethodError: The getter 'length' was called on null.
compiler message: Receiver: null
compiler message: Tried calling: length
compiler message: #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
compiler message: #1      _intervalListContains (package:kernel/class_hierarchy.dart:1139)
compiler message: #2      _ClassInfo.isSubtypeOf (package:kernel/class_hierarchy.dart:1203)
compiler message: #3      ClosedWorldClassHierarchy.getClassAsInstanceOf (package:kernel/class_hierarchy.dart:535)
compiler message: #4      ClosedWorldClassHierarchy.getTypeAsInstanceOf (package:kernel/class_hierarchy.dart:542)
compiler message: #5      TypeConstraintGatherer._isInterfaceSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:162)
compiler message: #6      TypeConstraintGatherer._isSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:287)
compiler message: #7      TypeConstraintGatherer._isSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:284)
compiler message: #8      TypeConstraintGatherer._isInterfaceSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:165)
compiler message: #9      TypeConstraintGatherer._isSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:287)
compiler message: #10     TypeConstraintGatherer.trySubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:50)
compiler message: #11     StrongModeMixinInferrer.generateConstraints (package:front_end/src/fasta/type_inference/type_inferrer.dart:1741)
compiler message: #12     StrongModeMixinInferrer.infer (package:front_end/src/fasta/type_inference/type_inferrer.dart:1761)
compiler message: #13     ClosedWorldClassHierarchy._topologicalSortVisit (package:kernel/class_hierarchy.dart:781)
compiler message: #14     ClosedWorldClassHierarchy._initialize (package:kernel/class_hierarchy.dart:705)
compiler message: #15     new ClassHierarchy (package:kernel/class_hierarchy.dart:38)
compiler message: #16     SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:580)
compiler message: #17     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:255)
compiler message: <asynchronous suspension>
compiler message: #18     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:132)
compiler message: <asynchronous suspension>
compiler message: #19     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103)
compiler message: #20     _rootRun (dart:async/zone.dart:1126)
compiler message: #21     _CustomZone.run (dart:async/zone.dart:1023)
compiler message: #22     runZoned (dart:async/zone.dart:1501)
compiler message: #23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103)
compiler message: #24     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:58)
compiler message: <asynchronous suspension>
compiler message: #25     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
compiler message: <asynchronous suspension>
compiler message: #26     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:207)
compiler message: #27     new Future.<anonymous closure> (dart:async/future.dart:174)
compiler message: #28     _rootRun (dart:async/zone.dart:1122)
compiler message: #29     _CustomZone.run (dart:async/zone.dart:1023)
compiler message: #30     _CustomZone.runGuarded (dart:async/zone.dart:925)
compiler message: #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
compiler message: #32     _rootRun (dart:async/zone.dart:1126)
compiler message: #33     _CustomZone.run (dart:async/zone.dart:1023)
compiler message: #34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
compiler message: #35     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
compiler message: #36     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
compiler message: #37     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
compiler message: #38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
compiler message: 
compiler message: 
compiler message: #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
compiler message: #1      _intervalListContains (package:kernel/class_hierarchy.dart:1139)
compiler message: #2      _ClassInfo.isSubtypeOf (package:kernel/class_hierarchy.dart:1203)
compiler message: #3      ClosedWorldClassHierarchy.getClassAsInstanceOf (package:kernel/class_hierarchy.dart:535)
compiler message: #4      ClosedWorldClassHierarchy.getTypeAsInstanceOf (package:kernel/class_hierarchy.dart:542)
compiler message: #5      TypeConstraintGatherer._isInterfaceSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:162)
compiler message: #6      TypeConstraintGatherer._isSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:287)
compiler message: #7      TypeConstraintGatherer._isSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:284)
compiler message: #8      TypeConstraintGatherer._isInterfaceSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:165)
compiler message: #9      TypeConstraintGatherer._isSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:287)
compiler message: #10     TypeConstraintGatherer.trySubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:50)
compiler message: #11     StrongModeMixinInferrer.generateConstraints (package:front_end/src/fasta/type_inference/type_inferrer.dart:1741)
compiler message: #12     StrongModeMixinInferrer.infer (package:front_end/src/fasta/type_inference/type_inferrer.dart:1761)
compiler message: #13     ClosedWorldClassHierarchy._topologicalSortVisit (package:kernel/class_hierarchy.dart:781)
compiler message: #14     ClosedWorldClassHierarchy._initialize (package:kernel/class_hierarchy.dart:705)
compiler message: #15     new ClassHierarchy (package:kernel/class_hierarchy.dart:38)
compiler message: #16     SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:580)
compiler message: #17     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:255)
compiler message: <asynchronous suspension>
compiler message: #18     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:132)
compiler message: <asynchronous suspension>
compiler message: #19     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103)
compiler message: #20     _rootRun (dart:async/zone.dart:1126)
compiler message: #21     _CustomZone.run (dart:async/zone.dart:1023)
compiler message: #22     runZoned (dart:async/zone.dart:1501)
compiler message: #23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103)
compiler message: #24     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:58)
compiler message: <asynchronous suspension>
compiler message: #25     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
compiler message: <asynchronous suspension>
compiler message: #26     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:207)
compiler message: #27     new Future.<anonymous closure> (dart:async/future.dart:174)
compiler message: #28     _rootRun (dart:async/zone.dart:1122)
compiler message: #29     _CustomZone.run (dart:async/zone.dart:1023)
compiler message: #30     _CustomZone.runGuarded (dart:async/zone.dart:925)
compiler message: #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
compiler message: #32     _rootRun (dart:async/zone.dart:1126)
compiler message: #33     _CustomZone.run (dart:async/zone.dart:1023)
compiler message: #34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
compiler message: #35     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
compiler message: #36     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
compiler message: #37     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
compiler message: #38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by aam** [comment]
cc @a-siva @mraleph

**Comment by a-siva** [comment]
Changing to P0 as this is blocking us from flipping --preview-dart-2 flag by default

**Comment by kmillikin** [comment]
I think this is https://github.com/dart-lang/sdk/issues/32353 with a proposed fix at https://dart-review.googlesource.com/c/sdk/+/45681.  We will verify.

**Comment by aam** [comment]
As I was going to to verify whether https://dart-review.googlesource.com/c/sdk/+/45681 fixes the problem, I first checked ToT of dart sdk 70d715f115 and it is already fixed there. It was broken at previous dart sdk roll b5b8080b2c. Too bad that dart roll introduces https://github.com/flutter/flutter/issues/15368.

**Comment by kmillikin** [comment]
Issue #32353 was fixed, so we need to verify that this issue is also fixed.

**Comment by dgrove** [comment]
@aam can you verify that this is fixed?

**Comment by aam** [comment]
Yes, I verified it yesterday: https://github.com/dart-lang/sdk/issues/32477#issuecomment-372139957
