### ISSUE TITLE
analysis service  error

### ISSUE THREAD

**Issue by xiayifeng** [dart-lang/sdk#32492]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4443003`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `AI-171.4443003, JRE 1.8.0_152-release-915-b08x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1280x800, 1920x1080  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/qf/tnzyqkk50ml0t729xh60n5lm0000gp/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.6, error: Failed to handle completion domain request: {id: 13, method: completion.getSuggestions, params: {file: /Users/sh-xiayf/flutter.workspace/flutter_app/lib/canvasTest.dart, offset: 90}, clientRequestTime: 1520825295932}
NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      OverrideContributor._buildSuggestion (package:analysis_server/src/services/completion/dart/override_contributor.dart:106)
<asynchronous suspension>
#2      OverrideContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/override_contributor.dart:54)
<asynchronous suspension>
#3      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:107)
<asynchronous suspension>
#4      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:102)
<asynchronous suspension>
#5      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:215)
<asynchronous suspension>
#6      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:148)
#7      _rootRun (dart:async/zone.dart:1126)

**Comment by bwilkerson** [comment]
I believe that this has been fixed on bleeding edge (as of 3/19). Please update and let us know if you still see this error.
