### ISSUE TITLE
When I click a Dart Analyzer Error link in IntelliJ this is all I get

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#32496]
> Analyzer Feedback from IntelliJ

The created URL is
```
https://github.com/dart-lang/sdk/issues/new?body=Analyzer%20Feedback%20from%20IntelliJ# Version information- `IDEA IU-173.4548.28`- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`- `IU-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1920x1200, 3840x2160  Retina`# ExceptionPlease append the contents of:file:///private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/report2.txt```Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.7, error: Analysis failed: /Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_shared/test/client/state/collection_change_test.dart context: exception_20180312_095423_864Element mismatch in /Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_shared/test/client/state/collection_change_test.dart at /Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_shared/test/client/state/collection_change_test.dart#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:74)#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:674)#2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:127)#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)#4      LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:126)#5      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101)<asynchronous suspension>#6      _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217)<asynchronous suspension>#7      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.d
```

**Comment by bwilkerson** [comment]
@devoncarew @stevemessick

**Comment by devoncarew** [comment]
`from%20IntelliJ# Version information`

It looks like we're inconsistently performing url encoding.

**Comment by zoechi** [comment]
#32496 seems to be such a case

**Comment by srawlins** [comment]
This was fixed right? We're getting properly formatted stack traces...
