### ISSUE TITLE
Analyzer throws "Class 'DynamicTypeImpl' has no instance getter 'superclass'" opening Flutter repo

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32494]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Opened Flutter repo at https://github.com/flutter/flutter/commit/e5ba3041cd6e490489904e397abad38c40244b27 using dev-32 as the SDK.

### Versions

- Dart SDK 2.0.0-dev.32.0
- Visual Studio Code 1.21.0
- Dart Code 2.10.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
M:\Apps\Dart\Dart-2.0.0-dev.32.0\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.10.0
```

### Exception

Exception while using a Visitor to visit a MapLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in VariableDeclarationImpl in VariableDeclarationListImpl in VariableDeclarationStatementImpl in BlockImpl in ForEachStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl

```text
NoSuchMethodError: Class 'DynamicTypeImpl' has no instance getter 'superclass'.
Receiver: Instance of 'DynamicTypeImpl'
Tried calling: superclass
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      Visitor._getSelfAndInheritedTypes (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:132)
#2      _SyncIterator.moveNext (dart:core-patch/dart:core/core_patch.dart:153)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#4      ExpandIterator.moveNext (dart:_internal/iterable.dart:477)
#5      MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#6      Iterable.any (dart:core/iterable.dart:400)
#7      Visitor._hasImmutableAnnotation (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:125)
#8      Visitor._visitTypedLiteral (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:93)
#9      Visitor.visitMapLiteral (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:76)
#10     MapLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7497)
#11     ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2756)
#12     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#13     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2754)
#14     UnifyingAstVisitor.visitMapLiteral (package:analyzer/dart/ast/visitor.dart:3100)
#15     MapLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7497)
#16     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7940)
#17     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#18     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3112)
#19     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7935)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8221)
#21     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:433)
#22     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#23     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898)
#24     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:429)
#25     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6620)
#26     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#27     UnifyingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:3069)
#28     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6546)
#29     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11303)
#30     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#31     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3224)
#32     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11297)
#33     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8221)
#34     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11399)
#35     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#36     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228)
#37     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11393)
#38     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11454)
#39     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#40     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:3232)
#41     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11450)
#42     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8221)
#43     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1351)
#44     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#45     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#46     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1347)
#47     ForEachStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4766)
#48     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#49     UnifyingAstVisitor.visitForEachStatement (package:analyzer/dart/ast/visitor.dart:3017)
#50     ForEachStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4759)
#51     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8221)
#52     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1351)
#53     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#54     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#55     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1347)
#56     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1296)
#57     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#58     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#59     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1292)
#60     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5409)
#61     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#62     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#63     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5403)
#64     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5254)
#65     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#66     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026)
#67     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5247)
#68     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8221)
#69     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2507)
#70     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#71     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#72     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2500)
#73     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:371)
#74     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:163)
#75     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#76     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162)
#77     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207)
#78     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:161)
#79     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#80     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217)
<asynchronous suspension>
#81     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97)
<asynchronous suspension>
#82     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1218)
<asynchronous suspension>
#83     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#84     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#85     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1010)
<asynchronous suspension>
#86     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1889)
<asynchronous suspension>
#87     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832)
#88     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#89     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#90     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#91     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:442)
#92     _rootRun (dart:async/zone.dart:1126)
#93     _CustomZone.run (dart:async/zone.dart:1023)
#94     runZoned (dart:async/zone.dart:1501)
#95     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:482)
#96     Driver.start (package:analysis_server/src/server/driver.dart:441)
#97     main (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#98     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#99     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\devicelab",
        "explicitFileCount": 86,
        "implicitFileCount": -86,
        "workItemQueueLength": 86,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\examples\\platform_channel_swift",
        "explicitFileCount": 3,
        "implicitFileCount": -3,
        "workItemQueueLength": 3,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\examples\\flutter_view",
        "explicitFileCount": 1,
        "implicitFileCount": -1,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\asci_casing",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\changed_sdk_location",
        "explicitFileCount": 1,
        "implicitFileCount": -1,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\syntax_error",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\integration_tests\\flavors",
        "explicitFileCount": 2,
        "implicitFileCount": -2,
        "workItemQueueLength": 2,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools",
        "explicitFileCount": 197,
        "implicitFileCount": -197,
        "workItemQueueLength": 197,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\tools\\vitool",
        "explicitFileCount": 3,
        "implicitFileCount": -3,
        "workItemQueueLength": 3,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_localizations",
        "explicitFileCount": 12,
        "implicitFileCount": -12,
        "workItemQueueLength": 12,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\integration_tests\\ui",
        "explicitFileCount": 14,
        "implicitFileCount": -14,
        "workItemQueueLength": 14,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\examples\\hello_world",
        "explicitFileCount": 3,
        "implicitFileCount": -3,
        "workItemQueueLength": 3,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\missing_dependency_tests",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\examples\\platform_view",
        "explicitFileCount": 1,
        "implicitFileCount": -1,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter",
        "explicitFileCount": 813,
        "implicitFileCount": -813,
        "workItemQueueLength": 813,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_test",
        "explicitFileCount": 19,
        "implicitFileCount": -19,
        "workItemQueueLength": 19,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\bots",
        "explicitFileCount": 6,
        "implicitFileCount": 137,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\automated_tests",
        "explicitFileCount": 11,
        "implicitFileCount": -11,
        "workItemQueueLength": 11,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\examples\\catalog",
        "explicitFileCount": 15,
        "implicitFileCount": -15,
        "workItemQueueLength": 15,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\tools",
        "explicitFileCount": 9,
        "implicitFileCount": -9,
        "workItemQueueLength": 9,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\asset_test\\font",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\docs\\platform_integration",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_driver",
        "explicitFileCount": 24,
        "implicitFileCount": -24,
        "workItemQueueLength": 24,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\examples\\layers",
        "explicitFileCount": 46,
        "implicitFileCount": -46,
        "workItemQueueLength": 46,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\integration_tests\\platform_interaction",
        "explicitFileCount": 4,
        "implicitFileCount": -4,
        "workItemQueueLength": 4,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\integration_tests\\external_ui",
        "explicitFileCount": 2,
        "implicitFileCount": -2,
        "workItemQueueLength": 2,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\examples\\stocks",
        "explicitFileCount": 15,
        "implicitFileCount": -15,
        "workItemQueueLength": 15,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_path",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_import",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\integration_tests\\channels",
        "explicitFileCount": 5,
        "implicitFileCount": -5,
        "workItemQueueLength": 5,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\manual_tests",
        "explicitFileCount": 14,
        "implicitFileCount": -14,
        "workItemQueueLength": 14,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\benchmarks\\microbenchmarks",
        "explicitFileCount": 6,
        "implicitFileCount": -6,
        "workItemQueueLength": 6,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\asset_test\\main",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_package",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\examples\\flutter_gallery",
        "explicitFileCount": 91,
        "implicitFileCount": -91,
        "workItemQueueLength": 91,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\dev\\benchmarks\\complex_layout",
        "explicitFileCount": 5,
        "implicitFileCount": -5,
        "workItemQueueLength": 5,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\good",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "m:\\Coding\\Applications\\flutter\\examples\\platform_channel",
        "explicitFileCount": 3,
        "implicitFileCount": -3,
        "workItemQueueLength": 3,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
https://github.com/dart-lang/linter/pull/918 fixes the bug, but we still need to pull the latest version of the linter into the sdk.

**Comment by pq** [comment]
I published a new linter and it's integrated as of https://github.com/dart-lang/sdk/commit/3918265129f515b11d6de8f4a4ee851077c9e6a7.

Thanks for the report (and for the fix!)
