### ISSUE TITLE
analyzer 0.31.2-alpha.0 throws exception analyzing dartdoc with previewDart2

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#32509]
This bug appears to be fixed in head; we should publish a new version of analyzer.

```
~/dart/dartdoc
$ git status
On branch preview-dart-2
Your branch is ahead of 'master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
~/dart/dartdoc
$ grind test-dartdoc
grinder running test-dartdoc

test-dartdoc
test-dartdoc: +  /usr/local/google/home/jcollins/dart/all_sdks/2.0.0-dev.35.0/bin/dart --checked bin/dartdoc.dart --output /tmp/dartdocHDBJJG
test-dartdoc: Generating documentation for 'dartdoc' into /tmp/dartdocHDBJJG/
test-dartdoc: parsing lib/dartdoc.dart...
test-dartdoc: parsing /usr/local/google/home/jcollins/dart/all_sdks/2.0.0-dev.35.0/lib/_internal/js_runtime/lib/interceptors.dart...
test-dartdoc:
test-dartdoc: Generation failed: type 'LibraryElementHandle' is not a subtype of type 'LibraryElementImpl' of 'libraryElement' where
test-dartdoc:   LibraryElementHandle is from package:analyzer/src/dart/element/handle.dart
test-dartdoc:   LibraryElementImpl is from package:analyzer/src/dart/element/element.dart
test-dartdoc:
test-dartdoc: #0      ElementResolver._handlePrefixedImplicitConstructorCase (package:analyzer/src/generated/element_resolver.dart:1749:43)
test-dartdoc: #1      ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:678:15)
test-dartdoc: #2      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7803:49)
test-dartdoc: #3      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6073:10)
test-dartdoc: #4      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7803:49)
test-dartdoc: #5      VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11277:19)
test-dartdoc: #6      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6088:10)
test-dartdoc: #7      PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4635:27)
test-dartdoc: #8      UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3224:59)
test-dartdoc: #9      ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:7683:35)
test-dartdoc: #10     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:6232:35)
test-dartdoc: #11     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11271:49)
test-dartdoc: #12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8195:20)
test-dartdoc: #13     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11373:16)
test-dartdoc: #14     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6088:10)
test-dartdoc: #15     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4635:27)
test-dartdoc: #16     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228:7)
test-dartdoc: #17     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:6256:39)
test-dartdoc: #18     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11367:15)
test-dartdoc: #19     TopLevelVariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10554:20)
test-dartdoc: #20     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6088:10)
test-dartdoc: #21     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4635:27)
test-dartdoc: #22     UnifyingAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3206:7)
test-dartdoc: #23     ResolverVisitor.visitTopLevelVariableDeclaration (package:analyzer/src/generated/resolver.dart:6216:45)
test-dartdoc: #24     PartialResolverVisitor.visitTopLevelVariableDeclaration (package:analyzer/src/generated/resolver.dart:4641:50)
test-dartdoc: #25     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10549:15)
test-dartdoc: #26     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5461:25)
test-dartdoc: #27     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2500:49)
test-dartdoc: #28     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:690:10)
test-dartdoc: #29     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:127:9)
test-dartdoc: #30     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
test-dartdoc: #31     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:126:13)
test-dartdoc: #32     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101:16)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #33     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217:21)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #34     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97:43)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #35     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1218:71)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #36     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #37     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183:20)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #38     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:626:43)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #39     DartDoc.logAnalysisErrors (package:dartdoc/dartdoc.dart:109:48)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #40     PackageBuilder._parseLibraries (package:dartdoc/src/model.dart:5138:11)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #41     PackageBuilder.getLibraries (package:dartdoc/src/model.dart:5218:28)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #42     PackageBuilder.buildPackageGraph (package:dartdoc/src/model.dart:4948:43)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #43     DartDoc.generateDocs (package:dartdoc/dartdoc.dart:160:26)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #44     main.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/jcollins/dart/dartdoc/bin/dartdoc.dart:274:46)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #45     _rootRun (dart:async/zone.dart:1126)
test-dartdoc: #46     _CustomZone.run (dart:async/zone.dart:1023)
test-dartdoc: #47     runZoned (dart:async/zone.dart:1501)
test-dartdoc: #48     main.<anonymous closure> (file:///usr/local/google/home/jcollins/dart/dartdoc/bin/dartdoc.dart:273:11)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #49     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:101:24)
test-dartdoc: #50     _rootRun (dart:async/zone.dart:1126)
test-dartdoc: #51     _CustomZone.run (dart:async/zone.dart:1023)
test-dartdoc: #52     runZoned (dart:async/zone.dart:1501)
test-dartdoc: #53     Chain.capture (package:stack_trace/src/chain.dart:99:12)
test-dartdoc: #54     main (file:///usr/local/google/home/jcollins/dart/dartdoc/bin/dartdoc.dart:272:15)
test-dartdoc: <asynchronous suspension>
test-dartdoc: #55     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
test-dartdoc: #56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
test-dartdoc:
test-dartdoc: package:analyzer/src/dart/analysis/driver.dart 1258:9     AnalysisDriver._computeAnalysisResult.<fn>
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                _Completer.completeError
test-dartdoc: package:analyzer/src/dart/analysis/driver.dart            AnalysisDriver._computeAnalysisResult.<fn>
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                _asyncErrorWrapperHelper
test-dartdoc: package:analyzer/src/dart/analysis/driver.dart 1183:75    AnalysisDriver._computeAnalysisResult.<fn>
test-dartdoc: package:front_end/src/base/performance_logger.dart 52:21  PerformanceLog.runAsync
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                new Future.microtask
test-dartdoc: package:front_end/src/base/performance_logger.dart 47:58  PerformanceLog.runAsync
test-dartdoc: package:analyzer/src/dart/analysis/driver.dart 1183:20    AnalysisDriver._computeAnalysisResult
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                new Future.microtask
test-dartdoc: package:analyzer/src/dart/analysis/driver.dart 1147:47    AnalysisDriver._computeAnalysisResult
test-dartdoc: package:analyzer/src/dart/analysis/driver.dart 626:43     AnalysisDriver.getErrors
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                new Future.microtask
test-dartdoc: package:analyzer/src/dart/analysis/driver.dart 621:53     AnalysisDriver.getErrors
test-dartdoc: package:dartdoc/dartdoc.dart 109:48                       DartDoc.logAnalysisErrors
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                new Future.microtask
test-dartdoc: package:dartdoc/dartdoc.dart 103:48                       DartDoc.logAnalysisErrors
test-dartdoc: package:dartdoc/src/model.dart 5138:11                    PackageBuilder._parseLibraries
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                _asyncThenWrapperHelper
test-dartdoc: package:dartdoc/src/model.dart 5132:73                    PackageBuilder._parseLibraries
test-dartdoc: package:dartdoc/src/model.dart 5218:28                    PackageBuilder.getLibraries
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                new Future.microtask
test-dartdoc: package:dartdoc/src/model.dart 5216:69                    PackageBuilder.getLibraries
test-dartdoc: package:dartdoc/src/model.dart 4948:43                    PackageBuilder.buildPackageGraph
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                new Future.microtask
test-dartdoc: package:dartdoc/src/model.dart 4947:50                    PackageBuilder.buildPackageGraph
test-dartdoc: package:dartdoc/dartdoc.dart 160:26                       DartDoc.generateDocs
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                new Future.microtask
test-dartdoc: package:dartdoc/dartdoc.dart 157:47                       DartDoc.generateDocs
test-dartdoc: bin/dartdoc.dart 274:46                                   main.<fn>.<fn>
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                new Future.microtask
test-dartdoc: bin/dartdoc.dart 273:29                                   main.<fn>.<fn>
test-dartdoc: dart:async                                                runZoned
test-dartdoc: bin/dartdoc.dart 273:11                                   main.<fn>
test-dartdoc: ===== asynchronous gap ===========================
test-dartdoc: dart:async                                                new Future.microtask
test-dartdoc: bin/dartdoc.dart 272:32                                   main.<fn>
test-dartdoc: package:stack_trace                                       Chain.capture
test-dartdoc: bin/dartdoc.dart 272:15                                   main
test-dartdoc:

ProcessException: SubprocessLauncher got non-zero exitCode
  Command: /usr/local/google/home/jcollins/dart/all_sdks/2.0.0-dev.35.0/bin/dart --checked bin/dartdoc.dart --output /tmp/dartdocHDBJJG
#0      SubprocessLauncher.runStreamed (package:dartdoc/src/io_utils.dart:162:7)
<asynchronous suspension>
#1      testDartdoc (file:///usr/local/google/home/jcollins/dart/dartdoc/tool/grind.dart:589:18)
<asynchronous suspension>
#2      _LocalLibraryMirror._invoke (dart:mirrors-patch/dart:mirrors/mirrors_impl.dart:1273)
#3      _LocalObjectMirror.invoke (dart:mirrors-patch/dart:mirrors/mirrors_impl.dart:360)
#4      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:79:38)
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      ZonedValue.withValue (package:grinder/src/utils.dart:104:12)
#9      GrinderTask.execute (package:grinder/src/grinder_task.dart:64:27)
#10     Grinder._invokeTask (package:grinder/src/grinder.dart:193:27)
#11     Grinder.start.<anon> (package:grinder/src/grinder.dart:168:16)
#12     Future.forEach.<anon> (dart:async/future.dart:484)
#13     Future.doWhile.<anon> (dart:async/future.dart:526)
#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
#15     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1355)
#16     Future.doWhile (dart:async/future.dart:541)
#17     Future.forEach (dart:async/future.dart:482)
#18     Grinder.start (package:grinder/src/grinder.dart:167:21)
#19     runTasks (package:grinder/src/cli.dart:67:39)
<asynchronous suspension>
#20     grind (package:grinder/grinder.dart:46:12)
#21     main (file:///usr/local/google/home/jcollins/dart/dartdoc/tool/grind.dart:14:30)
~/dart/dartdoc
$ 

```

**Comment by jcollins-g** [comment]
currently blocking dart-lang/dartdoc#1630.
