### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by qiuncheng** [dart-lang/sdk#32516]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-173.4548.28`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `IU-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.2 unknown, screens 1440x900, 1920x1080  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/y0/d30719b57mz9rk1qptq3t8kc0000gn/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.6, FATAL error: Failed to handle request: {id: 464, method: edit.getFixes, params: {file: /Users/yolo/Desktop/flutter_demo/flutter_demo_2/lib/main.dart, offset: 226}, clientRequestTime: 1520921458294}
RangeError (index): Invalid value: Not in range 0..232, inclusive: 234
#0      String.codeUnitAt (dart:core-patch/dart:core/string_patch.dart:931)
#1      CorrectionUtils.getLineThis (package:analysis_server/src/services/correction/util.dart:895)
#2      CorrectionUtils.isClassWithEmptyBody (package:analysis_server/src/services/correction/util.dart:1091)
#3      CorrectionUtils.prepareNewClassMemberLocation (package:analysis_server/src/services/correction/util.dart:1128)
#4      FixProcessor._addFix_createMissingOverrides (package:analysis_server/src/services/correction/fix_internal.dart:1536)
<asynchronous suspension>
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:323)
<asynchronous suspension>
#6      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:85)
<asynchronous suspension>
#7      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:242)
<asynchronous suspension>
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:355)

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
