### ISSUE TITLE
Error in Android Studio

### ISSUE THREAD

**Issue by FunMiles** [dart-lang/sdk#32520]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4443003`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `AI-171.4443003, JRE 1.8.0_152-release-915-b08x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/0n/r170838n5qqfrb0f0fwqy4300000gn/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.6, error: Failed to handle completion domain request: {id: 15084, method: completion.getSuggestions, params: {file: /Users/michel/Development/Androdev/Flutter/flutter_flightlog/lib/editflight.dart, offset: 2278}, clientRequestTime: 1520966628877}
NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      OverrideContributor._buildSuggestion (package:analysis_server/src/services/completion/dart/override_contributor.dart:106)
<asynchronous suspension>
#2      OverrideContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/override_contributor.dart:54)
<asynchronous suspension>
#3      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:107)
<asynchronous suspension>
#4      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:102)
<asynchronous suspension>
#5      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:215)
<asynchronous suspension>
#6      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:148)
#7      _rootRun (dart:async/zone.dart:1126)

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
