### ISSUE TITLE
Analysis server crashes when SDK path contains certain characters

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32532]
I apologise for this case in advance, but I figured since I found it I should raise it 😿

I was investigating a bug in Dart Code related to symbols in paths, so I figured I'd put all the characters that Windows allowed in there (that I could type on my keyboard, anyway...) and then make sure I escaped everything correctly. I put the SDK in a folder named `Dart-Test-!£$%^&()_+-=,.@~;'#[]{}`,

Turns out, Dart Code isn't the only thing that didn't like them.

```text
[15:33:47]: Spawning M:\Apps\Dart\Dart-Test-!£$%^&()_+-=,.@~;'#[]{}\bin\dart.exe with args ["M:\\Apps\\Dart\\Dart-Test-!£$%^&()_+-=,.@~;'#[]{}\\bin\\snapshots\\analysis_server.dart.snapshot","--client-id=Dart-Code.dart-code","--client-version=2.11.0-dev"]
[15:33:47]: ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
[15:33:47]: ==> {"id":"2","method":"analysis.setAnalysisRoots","params":{"excluded":[],"included":["m:\\Coding\\Applications\\flutter\\examples\\hello_world"]}}
[15:33:47]: ==> {"id":"3","method":"analysis.updateContent","params":{"files":{"m:\\Coding\\Applications\\flutter\\examples\\hello_world\\lib\\main.dart":{"content":"// Copyright 2015 The Chromium Authors. All rights reserved.\r\n// Use of this source code is governed by a BSD-style license that can be\r\n// found in the LICENSE file.\r\n\r\nimport 'package:flutter/widgets.dart';\r\n\r\nvoid main() => runApp(const Center(child: const Text('Hello, world!', textDirection: TextDirection.ltr)));\r\n","type":"add"}}}}
[15:33:47]: ERR Unhandled exception:
FormatException: Invalid character (at character 44)
/M:/Apps/Dart/Dart-Test-!£$%^&()_+-=,.@~;'#[]{}/bin/snapshots/analysis_serv...
                                           ^

#0      _Uri._fail (dart:core/uri.dart:1597)
#1      _Uri._normalize (dart:core/uri.dart:2292)
#2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2248)
#3      _Uri._makeFragment (dart:core/uri.dart:2161)
#4      new _Uri.notSimple (dart:core/uri.dart:1467)
#5      Uri.parse (dart:core/uri.dart:1012)
#6      _resolveScriptUri (dart:_builtin:239)
[15:33:47]: ERR vm-service: Error: Unhandled exception:
FormatException: Invalid character (at character 43)
M:\Apps\Dart\Dart-Test-!£$%^&()_+-=,.@~;'#[]{}\bin\snapshots\analysis_serve...
                                          ^

#0      _Uri._fail (dart:core/uri.dart:1597)
#1      _Uri._normalize (dart:core/uri.dart:2292)
#2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2248)
#3      _Uri._makeFragment (dart:core/uri.dart:2161)
#4      new _Uri.notSimple (dart:core/uri.dart:1467)
#5      Uri.parse (dart:core/uri.dart:1012)
#6      IsolateLoaderState.init (loader.dart:83:25)
#7      _processLoadRequest (loader.dart:1042:23)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
[15:33:50]: ==> {"id":"4","method":"analysis.getHover","params":{"file":"m:\\Coding\\Applications\\flutter\\examples\\hello_world\\lib\\main.dart","offset":232}}
```

**Comment by DanTup** [comment]
It was an old version I was using, but I just re-tested with `2.0.0-dev.35.0` and it's the same.

**Comment by DanTup** [comment]
If I remove the last four characters `[]{}` then it gets further, but the server crashes with this:

```text
### Analyzer Info

The analyzer was launched using the arguments:

```text
M:\Apps\Dart\Dart-Test-!£$%^&()_+-=,.@~;'#\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.11.0-dev
```

### Exception

Captured exception

```text
IsolateSpawnException: Unable to spawn isolate: Dart_LoadScript expects argument 'source' to be non-null.
#0      Isolate.spawn (dart:isolate-patch/dart:isolate/isolate_patch.dart:363)
<asynchronous suspension>
#1      EvictingFileByteStore._requestCacheCleanUp (package:front_end/src/byte_store/file_byte_store.dart:68)
<asynchronous suspension>
#2      new EvictingFileByteStore (package:front_end/src/byte_store/file_byte_store.dart:43)
#3      AnalysisServer._createByteStore (package:analysis_server/src/analysis_server.dart:1089)
#4      new AnalysisServer (package:analysis_server/src/analysis_server.dart:390)
#5      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#6      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#7      Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:442)
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     runZoned (dart:async/zone.dart:1501)
#11     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:482)
#12     Driver.start (package:analysis_server/src/server/driver.dart:441)
#13     main (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by bwilkerson** [comment]
The first exception looks like a bug in the implementation of `Uri`, which is causing the VM to crash. I'm going to mark this as a VM issue until that's resolved.

The second might well be the same bug, but I haven't looked into it enough to know for sure.

**Comment by tonyclickspace** [comment]
Just hit this in SDK version 2.0.0-dev.69.2, with a `#` symbol in the project path on Mac. Analyzer just crashes out and WebStorm encourages me to file a bug report. Stack trace is a bit deeper than the first reported version of this bug, so thought I should add it:

Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-181.5281.31`
- `2.0.0-dev.69.2`
- `WS-181.5281.31, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1280x800, 1920x1080, 1920x1080`

# Exception

```
Dart analysis server, SDK version 2.0.0-dev.69.2, server version 1.20.3, error: Analysis failed: /Users/tonydowney/Development/slides_in_dev/#ClientName/slide/display.dart
FormatException: Invalid character (at character 45)
/Users/tonydowney/Development/slides_in_dev/#ClientName/slide...
                                            ^

#0      _Uri._fail (dart:core/uri.dart:1614:5)
#1      _Uri._normalize (dart:core/uri.dart:2309:11)
#2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2265:12)
#3      _Uri._makePath (dart:core/uri.dart:2113:16)
#4      new _Uri (dart:core/uri.dart:1514:12)
#5      FileSystemState._absolutePathToFileUri (package:analyzer/src/dart/analysis/file_state.dart:946:18)
#6      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:821:28)
#7      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1205:31)
<asynchronous suspension>
#8      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1064:39)
<asynchronous suspension>
#9      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005:24)
<asynchronous suspension>
#10     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946:5)
#11     new AnalysisServer (package:analysis_server/src/analysis_server.dart:402:29)
#12     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#13     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#14     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:441:19)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:483:12)
#20     Driver.start (package:analysis_server/src/server/driver.dart:440:5)
#21     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12:11)
#22     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by DanTup** [comment]
Unfortunately this isn't fixed by the fix for #34621 (probably to be expected, had a different stack trace):

```
[11:59:57 AM]: Spawning M:\Apps\Dart\Dart-Test-!£$%^&()_+-=,.@~;'#[]{}\bin\dart.exe with args ["M:\\Coding\\Applications\\Google\\dart-sdk\\sdk\\pkg\\analysis_server\\bin\\server.dart","--client-id=Dart-Code.dart-code","--client-version=2.19.0-beta.2"]
[11:59:57 AM]: ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
[11:59:57 AM]: ==> {"id":"2","method":"analysis.updateContent","params":{"files":{"M:\\Coding\\TestStuff\\#Dart-Test-!£$%^&()_+-=,.@~;'#[]{}\\bin\\main.dart":{"content":"main() {\r\n  print(\"test\");\r\n  m\r\n}\r\n ","type":"add"}}}}
[11:59:58 AM]: vm-service: Error: Unhandled exception:
FormatException: Invalid character (at character 43)
M:\Apps\Dart\Dart-Test-!£$%^&()_+-=,.@~;'#[]{}\bin\snapshots\kernel-service...
                                          ^

#0      _Uri._fail (dart:core/uri.dart:1614:5)
#1      _Uri._normalize (dart:core/uri.dart:2309:11)
#2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2265:12)
#3      _Uri._makeFragment (dart:core/uri.dart:2178:12)
#4      new _Uri.notSimple (dart:core/uri.dart:1484:18)
#5      Uri.parse (dart:core/uri.dart:1012:16)
#6      IsolateLoaderState.init (dart:vmservice_io/loader.dart:86:25)
#7      _processLoadRequest (dart:vmservice_io/loader.dart:1025:23)
#8      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
