### ISSUE TITLE
Dart analysis server crash

### ISSUE THREAD

**Issue by afpatmin** [dart-lang/sdk#32554]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-173.4674.32`
- `2.0.0-dev.38.0`
- `WS-173.4674.32, JRE 1.8.0_152-release-1024-b15x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

# Exception

report.txt:
```
Dart analysis server, SDK version 2.0.0-dev.38.0, server version 1.19.0, error: Analysis failed: D:\AppFoundry\Workspaces\DAHL\bokain_admin\lib\components\calendar_component\booking_add_component\booking_add_component.dart context: exception_20180316_152650_204
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/dart:core/array.dart:133)
#1      _LibraryResynthesizer.createUnitResynthesizer (package:analyzer/src/summary/resynthesize.dart:1025)
#2      _LibraryResynthesizer.buildLibrary (package:analyzer/src/summary/resynthesize.dart:963)
#3      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:256)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
#5      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:222)
#6      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:159)
#7      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:336)
#8      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:35)
#9      ElementHandle.getAncestor (package:analyzer/src/dart/element/handle.dart:456)
#10     ElementHandle.library (package:analyzer/src/dart/element/handle.dart:415)
#11     LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:549)
#12     LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:430)
#13     EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:163)
#14     EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:163)
#15     EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:163)
#16     Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1101)
#17     VariableResolverVisitor.visitSimpleIdentifier (package:analyzer/src/generated/resolver.dart:10793)
#18     SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9606)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8242)
#20     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7347)
#21     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#22     UnifyingAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:3097)
#23     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7342)
#24     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7961)
#25     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#26     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3112)
#27     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7956)
#28     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8242)
#29     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:433)
#30     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#31     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898)
#32     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:429)
#33     AnnotationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:325)
#34     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#35     UnifyingAstVisitor.visitAnnotation (package:analyzer/dart/ast/visitor.dart:2895)
#36     AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:319)
#37     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8242)
#38     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:7324)
#39     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7302)
#40     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1911)
#41     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8242)
#42     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2507)
#43     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#44     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#45     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2500)
#46     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:691)
#47     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:127)
#48     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#49     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:126)
#50     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#51     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217)
<asynchronous suspension>
#52     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97)
<asynchronous suspension>
#53     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1218)
<asynchronous suspension>
#54     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#55     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#56     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1010)
<asynchronous suspension>
#57     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1889)
<asynchronous suspension>
#58     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832)
#59     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#60     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#61     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#62     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#63     _rootRun (dart:async/zone.dart:1126)
#64     _CustomZone.run (dart:async/zone.dart:1023)
#65     runZoned (dart:async/zone.dart:1501)
#66     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#67     Driver.start (package:analysis_server/src/server/driver.dart:443)
#68     main (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#69     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

```
1521210408747 <= {"event":"analysis.navigation","params":{"file":"D:\\AppFoundry\\Workspaces\\DAHL\\bokain_admin\\lib\\components\\model_components\\customer\\customer_add_component.dart","regions":[{
1521210408753 <= {"event":"analysis.closingLabels","params":{"file":"D:\\AppFoundry\\Workspaces\\DAHL\\bokain_admin\\lib\\components\\model_components\\customer\\customer_add_component.dart","labels":
1521210408769 <= {"event":"analysis.outline","params":{"file":"D:\\AppFoundry\\Workspaces\\DAHL\\bokain_admin\\lib\\components\\model_components\\customer\\customer_add_component.dart","kind":"LIBRARY
1521210408781 <= {"event":"analysis.overrides","params":{"file":"D:\\AppFoundry\\Workspaces\\DAHL\\bokain_admin\\lib\\components\\model_components\\customer\\customer_add_component.dart","overrides":[
1521210409331 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\d_components\\lib\\d_components.dart","errors":[]}}
1521210409336 <= {"id":"7","result":{"assists":[]}}
1521210409499 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\d_components\\lib\\src\\d_colorpicker_component\\d_colorpicker.dart","errors":[]}}
1521210409501 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\d_components\\lib\\src\\d_navbar_component\\d_navbar.dart","errors":[]}}
1521210409514 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\d_components\\lib\\src\\d_slider_component\\d_slider.dart","errors":[]}}
1521210409516 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\d_components\\lib\\src\\d_timepicker_component\\d_timepicker.dart","errors":[]}}
1521210409517 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\d_components\\lib\\src\\d_tooltip_component\\d_tooltip.dart","errors":[]}}
1521210409714 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\angular_modern_charts.dart","errors":[]}}
1521210409720 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\components\\barchart_component\\barchart_component.dart","errors":[]}}
1521210409721 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\components\\gaugechart_component\\gaugechart_component.dart","errors":[]}}
1521210409721 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\components\\linechart_component\\linechart_component.dart","errors":[]}}
1521210409722 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\components\\piechart_component\\piechart_component.dart","errors":[]}}
1521210409731 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\components\\radarchart_component\\radarchart_component.dart","errors":[]}}
1521210409732 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\models\\barchart_data.dart","errors":[]}}
1521210409732 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\models\\barchart_properties.dart","errors":[]}}
1521210409733 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\models\\gaugechart_data.dart","errors":[]}}
1521210409734 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\models\\gaugechart_properties.dart","errors":[]}}
1521210409738 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\models\\linechart_data.dart","errors":[]}}
1521210409739 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\models\\linechart_properties.dart","errors":[]}}
1521210409740 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\models\\piechart_data.dart","errors":[]}}
1521210409740 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\models\\piechart_properties.dart","errors":[]}}
1521210409741 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\models\\radarchart_data.dart","errors":[]}}
1521210409745 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Forks\\angular_modern_charts\\lib\\src\\models\\radarchart_properties.dart","errors":[]}}
1521210409774 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Workspaces\\DAHL\\bokain_admin\\lib\\components\\app_component.dart","errors":[]}}
1521210409782 <= {"event":"analysis.errors","params":{"file":"D:\\AppFoundry\\Workspaces\\DAHL\\bokain_admin\\lib\\components\\associative_table_component\\associative_table_component.dart","errors":[
1521210410229 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: D:\\AppFoundry\\Workspaces\\DAHL\\bokain_admin\\lib\\components\\calendar_component\\booking_add_componen
```

```
Dart analysis server, SDK version 2.0.0-dev.38.0, server version 1.19.0, error: Analysis failed: D:\AppFoundry\Workspaces\DAHL\bokain_admin\lib\components\calendar_component\booking_add_component\booking_add_component.dart context: exception_20180316_152650_204
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/dart:core/array.dart:133)
#1      _LibraryResynthesizer.createUnitResynthesizer (package:analyzer/src/summary/resynthesize.dart:1025)
#2      _LibraryResynthesizer.buildLibrary (package:analyzer/src/summary/resynthesize.dart:963)
#3      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:256)
#4      _HashVMBase

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I saw this once before, but I don't know how to reproduce this.
Unless there is a reproducible test case, there is nothing I can do :-(

**Comment by bwilkerson** [comment]
I'm assuming that this issue is stale. Please let us know if you're continuing to see the problem.
