### ISSUE TITLE
Analysis server crash (IntelliJ) in latest SDK

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#32550]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-173.4548.28`
- `2.0.0-dev.38.0`
- `IU-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/bn/dtrksvvs32j6004mk6r0dcdw007b7h/T/report.txt

```
Dart analysis server, SDK version 2.0.0-dev.36.0, server version 1.19.0, error: Analysis failed: /Users/matanl/git/angular/angular_ast/test/ast_cli_tester.dart
RangeError (byteOffset): Invalid value: Not in range 0..1304, inclusive: 6029346
#0      _ByteDataView.getUint32 (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:4278)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:72)
#2      StringReader.read (package:front_end/src/base/flat_buffers.dart:663)
#3      _FbGenericList.[] (package:front_end/src/base/flat_buffers.dart:826)
#4      Object
```

Here is the code in `ast_cli_tester.dart`:

```dart
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:io';

import 'package:angular_ast/angular_ast.dart';
import 'package:path/path.dart' as p;

RecoveringExceptionHandler exceptionHandler = new RecoveringExceptionHandler();

List<StandaloneTemplateAst> parse(String template) => const NgParser().parse(
      template,
      sourceUrl: '/test/parser_test.dart#inline',
      exceptionHandler: exceptionHandler,
      desugar: false,
      parseExpressions: false,
    );

void main() {
  String input;
  if (exceptionHandler is RecoveringExceptionHandler) {
    exceptionHandler.exceptions.clear();
  }
  var fileDir = p.join('test', 'ast_cli_tester_source.html');
  var file = new File(fileDir.toString());
  input = file.readAsStringSync();
  //input = stdin.readLineSync(encoding: UTF8);
  var ast = parse(input);
  print('----------------------------------------------');
  if (exceptionHandler is ThrowingExceptionHandler) {
    print('CORRECT!');
    print(ast);
  }
  if (exceptionHandler is RecoveringExceptionHandler) {
    var exceptionsList = exceptionHandler.exceptions;
    if (exceptionsList.isEmpty) {
      print('CORRECT!');
      print(ast);
    } else {
      var visitor = const HumanizingTemplateAstVisitor();
      var fixed = ast.map((t) => t.accept(visitor)).join('');
      print('ORGNL: $input');
      print('FIXED: $fixed');

      print('\n\nERRORS:');
      exceptionHandler.exceptions.forEach((e) {
        var context = input.substring(e.offset, e.offset + e.length);
        print('${e.errorCode.message} :: $context at ${e.offset}');
      });
    }
  }
}
```

... with the full file, here:
https://github.com/dart-lang/angular/blob/master/angular_ast/test/ast_cli_tester.dart

**Comment by bwilkerson** [comment]
I'm assuming that this issue is stale. Please let us know if you're continuing to see the problem.
