### ISSUE TITLE
Analysis Server crash on -dev.39

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32560]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-173.4674.33`
- `2.0.0-dev.39.0`
- `IU-173.4674.33, JRE 1.8.0_152-release-1024-b15x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 3840x2160`

# Exception

Please append the contents of:
file:///private/var/folders/9_/hw8ty6ns5c31y68b55m6v3bw0071_k/T/report.txt

```
Dart analysis server, SDK version 2.0.0-dev.39.0, server version 1.20.0, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [/Users/kevmoo/source/github/webdev/example], excluded: [/Users/kevmoo/source/github/webdev/example/.idea, /Users/kevmoo/source/github/webdev/example/.pub, /Users/kevmoo/source/github/webdev/example/build]}, clientRequestTime: 1521229661034}
FormatException: No ':' on line (at offset 5541)
#0      parse (package:package_config/packages_file.dart:53)
#1      ContextBuilder.findPackagesFromFile (package:analyzer/src/context/builder.dart:336)
#2      ContextBuilder.createPackageMap (package:analyzer/src/context/builder.dart:273)
#3      _BasicWorkspace.packages (package:analyzer/src/context/builder.dart:848)
#4      _BasicWorkspace.packageMap (package:analyzer/src/context/builder.dart:843)
#5      _BasicWorkspace.packageUriResolver (package:analyzer/src/context/builder.dart:854)
#6      _BasicWorkspace.createSourceFactory (package:analyzer/src/context/builder.dart:862)
#7      ContextBuilder.getAnalysisOptions (package:analyzer/src/context/builder.dart:432)
#8      ContextManagerImpl._checkForPackagespecUpdate (package:analysis_server/src/context_manager.dart:974)
#9      ContextManagerImpl._handleWatchEventImpl (package:analysis_server/src/context_manager.dart:1487)
#10     ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1356)
#11     _rootRunUnary (dart:async/zone.dart:1134)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#16     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#17     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98)
#18     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#19     _rootRunUnary (dart:async/zone.dart:1134)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#24     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:379)
#25     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254)
#26     _rootRunUnary (dart:async/zone.dart:1134)
#27     _CustomZone.runUnary (dart:async/zone.dart:1031)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#30     _DelayedData.perform (dart:async/stream_impl.dart:578)
#31     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
#32     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#33     _rootRun (dart:async/zone.dart:1122)
#34     _CustomZone.run (dart:async/zone.dart:1023)
#35     _CustomZone.runGuarded (dart:async/zone.dart:925)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#37     _rootRun (dart:async/zone.dart:1126)
#38     _CustomZone.run (dart:async/zone.dart:1023)
#39     _CustomZone.runGuarded (dart:async/zone.dart:925)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#43     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#44     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

```
1521229691415 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229691774 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229691946 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229692084 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229692201 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229692479 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229692622 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229692898 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229693068 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229693281 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229693423 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229693666 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229693780 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229693982 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229694129 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229694417 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229694589 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229694799 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229694946 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229695184 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229695325 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229695560 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229695709 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229695944 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229696117 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229696336 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229696456 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229696716 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521229696857 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521229697082 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [/Users/kevmoo/source/github/webdev
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/48340
