### ISSUE TITLE
Exception thrown from the analysis server

### ISSUE THREAD

**Issue by Porl91** [dart-lang/sdk#32563]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I was attempting to implement a method on a class from the base abstract class, which was previously an empty definition. 
After typing 'void' and then typing space I received this exception. After doing this a few times it seemed to resolve itself and now isn't reproducible. :(
Here's an example of my class structure:

```dart
abstract class TestAbstract {
  void test();
}

class TestConcrete implements TestAbstract {
    // Typing 'void ' here caused the exception to throw
}
```

### Versions

- Dart SDK 2.0.0-dev.35.0
- Visual Studio Code 1.21.0
- Dart Code 2.10.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\Dart\Builds\dart-sdk-2.0.0-dev.35.0\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.10.0
```

### Exception

Failed to handle completion domain request: {id: 3341, method: completion.getSuggestions, params: {file: c:\Users\Porl\Desktop\DartWebGL\demo\web\models\chunk_renderer.dart, offset: 84}}

```text
NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      OverrideContributor._buildSuggestion (package:analysis_server/src/services/completion/dart/override_contributor.dart:111)
<asynchronous suspension>
#2      OverrideContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/override_contributor.dart:54)
<asynchronous suspension>
#3      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:108)
<asynchronous suspension>
#4      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:102)
<asynchronous suspension>
#5      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:215)
<asynchronous suspension>
#6      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:148)
#7      _rootRun (dart:async/zone.dart:1126)
#8      _CustomZone.run (dart:async/zone.dart:1023)
#9      runZoned (dart:async/zone.dart:1490)
#10     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:145)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:722)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:718)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1490)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:717)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#22     _rootRunUnary (dart:async/zone.dart:1134)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#34     _rootRunUnary (dart:async/zone.dart:1134)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#47     _rootRunUnary (dart:async/zone.dart:1134)
#48     _CustomZone.runUnary (dart:async/zone.dart:1031)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#53     _StreamController._add (dart:async/stream_controller.dart:639)
#54     _StreamController.add (dart:async/stream_controller.dart:585)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1662)
#56     _rootRunUnary (dart:async/zone.dart:1138)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#62     _StreamController._add (dart:async/stream_controller.dart:639)
#63     _StreamController.add (dart:async/stream_controller.dart:585)
#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1235)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:788)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#68     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "c:\\Users\\Porl\\Desktop\\DartWebGL\\dart_ammo_js",
        "explicitFileCount": 11,
        "implicitFileCount": 129,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "c:\\Users\\Porl\\Desktop\\DartWebGL\\demo",
        "explicitFileCount": 13,
        "implicitFileCount": 166,
        "workItemQueueLength": 15,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/47185
