### ISSUE TITLE
Chrome 63 Roll IE11 Failure test line-break-after-inline-latin1_t01

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#32578]
IE11 Failure co19 test LayoutTests/fast/text/line-break-after-inline-latin1_t01

Another test fails same way see LibTest/html/IFrameElement/getClientRects_A01_t02

```
      value: TypeError: Object doesn't support property or method 'get$width'
      timestamp: 0.039
      stack_trace: TypeError: Object doesn't support property or method 'get$width'
               at main (http://127.0.0.1:61095/root_build/generated_compilations/dart2js-sdk/short10529_Element_getClientRects_A01_t02/test.js:3711:11)
               at dartMainRunner (http://127.0.0.1:61095/root_dart/tools/testing/dart/test_controller.js:324:5)
               at Anonymous function (http://127.0.0.1:61095/root_build/generated_compilations/dart2js-sdk/short10529_Element_getClientRects_A01_t02/test.js:4264:7)
               at onLoad (http://127.0.0.1:61095/root_build/generated_compilations/dart2js-sdk/short10529_Element_getClientRects_A01_t02/test.js:4257:7)

```

**Comment by terrylucas** [comment]
Also tests:
LayoutTests/fast/text/decomposed-after-stacked-diacritics_t01
LayoutTests/fast/text/line-breaks-after-ideographic-comma-or-full-stop_t02
LayoutTests/fast/text/multiglyph-characters_t01
LibTest/html/Element/getBoundingClientRect_A01_t02

**Comment by terrylucas** [comment]
LayoutTests/fast/text/international/complex-text-rectangle_t01
LayoutTests/fast/text/justification-padding-mid-word_t01

**Comment by terrylucas** [comment]
html/element_test/position

**Comment by terrylucas** [comment]
Fixed with CL [https://dart-review.googlesource.com/c/sdk/+/50504](https://dart-review.googlesource.com/c/sdk/+/50504).
