### ISSUE TITLE
Chrome 63 Roll IE11 Failure test getClientRects_A01_t02

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#32579]
IE11 Failure in co19 test LibTest/html/Element/getClientRects_A01_t02

```
      value: TypeError: Object doesn't support property or method 'containsRectangle$1'
      timestamp: 0.071
      stack_trace: TypeError: Object doesn't support property or method 'containsRectangle$1'
               at J.containsRectangle$1$x (http://127.0.0.1:64494/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LibTest_html_Element_getClientRects_A01_t02/test.js:3851:5)
               at main (http://127.0.0.1:64494/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LibTest_html_Element_getClientRects_A01_t02/test.js:3719:9)
               at dartMainRunner (http://127.0.0.1:64494/root_dart/tools/testing/dart/test_controller.js:324:5)
               at Anonymous function (http://127.0.0.1:64494/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LibTest_html_Element_getClientRects_A01_t02/test.js:4271:7)
               at onLoad (http://127.0.0.1:64494/root_build/generated_compilations/dart2js-sdk/tests_co19_src_LibTest_html_Element_getClientRects_A01_t02/test.js:4264:7)

```

**Comment by terrylucas** [comment]
Fixed with CL [https://dart-review.googlesource.com/c/sdk/+/50504](https://dart-review.googlesource.com/c/sdk/+/50504).
