### ISSUE TITLE
Analysis Server crash

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32588]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-173.4674.33`
- `2.0.0-dev.39.0`
- `IU-173.4674.33, JRE 1.8.0_152-release-1024-b15x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 3840x2160`

# Exception

Please append the contents of:
file:///private/var/folders/9_/hw8ty6ns5c31y68b55m6v3bw0071_k/T/report1.txt

```
Dart analysis server, SDK version 2.0.0-dev.39.0, server version 1.20.0, error: Exception while using a _Visitor to visit a CompilationUnitImpl
NoSuchMethodError: The getter 'childEntities' was called on null.
Receiver: null
Tried calling: childEntities
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      DartTypeUtilities.traverseNodesInDFS (package:linter/src/util/dart_type_utilities.dart:201)
#2      ConditionScopeVisitor._isRelevantOutsideOfForStatement (package:linter/src/util/condition_scope_visitor.dart:334)
#3      ConditionScopeVisitor.visitForStatement (package:linter/src/util/condition_scope_visitor.dart:203)
#4      ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5083)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8246)
#6      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1351)
#7      RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:647)
#8      BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1347)
#9      BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1296)
#10     ConditionScopeVisitor.visitBlockFunctionBody (package:linter/src/util/condition_scope_visitor.dart:148)
#11     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1292)
#12     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7742)
#13     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1007)
#14     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7733)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8246)
#16     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1979)
#17     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:683)
#18     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1911)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8246)
#20     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2507)
#21     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#22     _Visitor.visitCompilationUnit (package:linter/src/rules/invariant_booleans.dart:186)
#23     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2500)
#24     ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2757)
#25     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#26     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2755)
#27     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#28     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2500)
#29     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:371)
#30     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:163)
#31     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#32     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162)
#33     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207)
#34     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:161)
#35     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#36     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217)
<asynchronous suspension>
#37     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97)
<asynchronous suspension>
#38     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1218)
<asynchronous suspension>
#39     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#40     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#41     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1010)
<asynchronous suspension>
#42     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1889)
<asynchronous suspension>
#43     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832)
#44     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#45     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#46     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#47     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#48     _rootRun (dart:async/zone.dart:1126)
#49     _CustomZone.run (dart:async/zone.dart:1023)
#50     runZoned (dart:async/zone.dart:1501)
#51     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#52     Driver.start (package:analysis_server/src/server/driver.dart:443)
#53     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#54     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

```
1521469951092 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/bin/service/dartdoc.dart","errors":[]}}
1521469951115 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/bin/server.dart","errors":[]}}
1521469951131 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/search_memcache.dart","errors":[]}}
1521469951160 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/search_service.dart","errors":[]}}
1521469951372 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/backend.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file"
1521469951400 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/atom_feed.dart","errors":[{"severity":"INFO","type":"TODO","location":{"fil
1521469951538 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/handlers.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file
1521469951546 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/handlers_redirects.dart","errors":[]}}
1521469951600 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/model_properties.dart","errors":[]}}
1521469951641 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/upload_signer_service.dart","errors":[]}}
1521469951649 => {"id":"8","method":"analysis.setPriorityFiles","params":{"files":["/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/dartdoc/handlers.dart"]},"clientRequestTime":1521469951649}
1521469951649 => {"id":"9","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/dartdoc/handlers.dart"],"CLOSING_LABELS":
1521469951658 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/oauth2_service.dart","errors":[]}}
1521469951658 <= {"id":"8"}
1521469951660 <= {"id":"9"}
1521469951708 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/dartdoc/handlers.dart","errors":[]}}
1521469951717 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/dartdoc/handlers.dart","regions":[{"type":"DIRECTIVE","offset":217,"length":20},
1521469951742 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/dartdoc/handlers.dart","regions":[{"offset":224,"length":12,"targets":[0]},{"off
1521469951742 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/dartdoc/handlers.dart","labels":[]}}
1521469951747 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/dartdoc/handlers.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_U
1521469951753 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/dartdoc/handlers.dart","overrides":[]}}
1521469951813 => {"id":"10","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/dartdoc/handlers.dart","offset":0,"length":0},"clientRequestTime":1521469
1521469952146 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/templates.dart","errors":[{"severity":"INFO","type":"TODO","location":{"fil
1521469952150 <= {"id":"10","result":{"assists":[]}}
1521469952179 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/template_consts.dart","errors":[]}}
1521469952232 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/static_files.dart","errors":[]}}
1521469952312 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/models.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":
1521469952439 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/frontend/service_utils.dart","errors":[]}}
1521469952465 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pub-dartlang-dart/app/lib/shared/search_client.dart","errors":[]}}
1521469952511 <= {"event":"server.error","params":{"isFatal":false,"message":"Exception while using a _Visitor to visit a CompilationUnitImpl","stackTrace":"NoSuchMethodError: The getter 'childEntitie
```

**Comment by bwilkerson** [comment]
https://github.com/dart-lang/linter/pull/931
