### ISSUE TITLE
Uncaught exception when adding Future.timeout twice

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#32586]
In the following code, `catchError` shall catch the exception, and it did. However, another uncaught exception will take place too (see output) -- it is actually the same exception but shall be caught and handled (in this test case, it is ignored).

```dart
import "dart:async";

void main() {
  test();
}

test() async {
  await connect(0);
  await connect(1);
  await connect(2);
}

Future connect(int id) {
  void completeError() {
    if (_completer != null) {
      _completer.complete(null);
      _completer = null;
    }
  }

  if (_connecting != null) {
    print("Re-entry: $id...");
    _connecting.timeout(const Duration(seconds: 2), onTimeout: () {
      print("Timeout 2");
      completeError();
    });
    return (_completer = new Completer()).future;
  }

  _completer = new Completer();
  (_connecting = connectIt()).catchError((ex) {
    //it will catch the exception, but another exception is not caught
    print("Got 1: $ex");
    _connecting = null;
    completeError();
  }).timeout(const Duration(seconds: 2), onTimeout: () {
    print("Timeout 1");
    completeError();
  });
  return _completer.future;
}

Future _connecting;
Completer _completer;

Future connectIt() => new Future.delayed(const Duration(seconds: 5), () {
      throw "error here";
    });
```

The output:

```
Timeout 1
Re-entry: 1...
Timeout 2
Re-entry: 2...
Got 1: error here
Unhandled exception:
error here
#0      connectIt.<anonymous closure> (file:///Users/tomyeh/test/dart/async7.dart:53:3)
#1      new Future.delayed.<anonymous closure> (dart:async/future.dart:281)
#2      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

Note:

1. It works correctly if assigning `_connecting` with the return value of `catchError`.
2. If I added another `catchError` before 2nd timeout, both `catchError` will be called and no uncaught exception will occur.

**Comment by lrhn** [comment]
This is working as intended. The future returned by the first `_connecting.timeout` can complete with an error, and that is not handled.
