### ISSUE TITLE
VM: incorrect type is assigned to phi in strong mode

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#32597]
The following example is derived from fasta code [recover.dart#L158](https://github.com/dart-lang/sdk/blob/ac322d0fb4ade348e64c87f6d9522a41357860ef/pkg/front_end/lib/src/fasta/scanner/recover.dart#L158):

```dart
class Token {
  Token next;
}

class StringToken extends Token {
}

class ErrorToken extends Token {
}

void foo(Token tokens) {
  Token current = tokens;
  for (int i = 0; i < 1; i++) {
    while (current is ErrorToken) {
      ErrorToken first = current;
      print(first);
    }
    current = current.next;
  }
}

void main() {
  Token token = new StringToken();
  token.next = token;

  for (int i = 0; i < 100; i++) {
    foo(token);
  }
  print('ok');
}
```

It works if strong mode types are not used:
```
dart --preview-dart-2 --no-use-strong-mode-types --no-background-compilation --optimization-counter-threshold=10 foo.dart
ok
```

It doesn't work if optimizations using strong mode types are enabled:
```
dart --preview-dart-2 --no-background-compilation --optimization-counter-threshold=10 foo.dart

Unhandled exception:
type 'StringToken' is not a subtype of type 'ErrorToken' where
  StringToken is from file:///usr/local/google/home/alexmarkov/work/dart/sdk/foo.dart
  ErrorToken is from file:///usr/local/google/home/alexmarkov/work/dart/sdk/foo.dart

#0      foo (file:///usr/local/google/home/alexmarkov/work/dart/sdk/foo.dart:16:26)
#1      main (file:///usr/local/google/home/alexmarkov/work/dart/sdk/foo.dart:28:5)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by mraleph** [comment]
Note that solution does not solve the whole problem because variables can have clashing indices.

```dart
// VMOptions=--optimization_counter_threshold=10 --no-background-compilation

class Token {
  Token next;
}

class StringToken extends Token {}

class ErrorToken extends Token {}

bool failed = false;

void foo(Token tokens, {bool x: false}) {
  dynamic v;
  {
    Token current = tokens;
    while (current is ErrorToken) {
      failed = true;
      current = null;
    }
    v = current;
  }
  if (x) {
    ErrorToken second = v;
    print(second);
  }
}

void main() {
  Token token = new StringToken();
  token.next = token;

  for (int i = 0; i < 100; i++) {
    foo(token);
  }
  print(failed ? 'failure' : 'success');
}
```
