### ISSUE TITLE
dart2js failing w/ pkg:build_runner on -dev.39.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32600]
```
[INFO] build_web_compilers|entrypoint on web/game_web.dart:Running dart2js with --dump-info --fast-startup --minify --no-frequency-based-minification --no-source-maps --show-package-warnings --trust-primitives --trust-type-annotations --packages=.package-0f968e02296f0686fc07877eae6b645a -oweb/game_web.dart.js web/game_web.dart
[SEVERE] build_web_compilers|entrypoint on web/game_web.dart:
Dart2Js finished with:

/b/build/slave/dart-sdk-mac-dev/build/sdk/sdk/lib/_internal/js_runtime/lib/isolate_helper.dart@43652+1:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.0.0-dev.39.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: Class 'JClass' has no instance getter 'superclass'.
Receiver: Instance of 'JClass'
Tried calling: superclass
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      new _ConstructorBodyNamingScope.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/js_backend/minify_namer.dart:342)
#2      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
#3      new _ConstructorBodyNamingScope (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/js_backend/minify_namer.dart:341)
#4      Namer&_MinifiedFieldNamer&_MinifyConstructorBodyNamer.constructorBodyName (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/js_backend/minify_namer.dart:367)
#5      Namer.instanceMethodName (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/js_backend/namer.dart:790)
#6      SsaCodeGenerator.visitInvokeConstructorBody (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1771)
#7      HInvokeConstructorBody.accept (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/nodes.dart:1894)
#8      SsaCodeGenerator.visit (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:711)
#9      SsaCodeGenerator.visitStatement (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:723)
#10     SsaCodeGenerator.define (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:692)
#11     SsaCodeGenerator.iterateBasicBlock (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1373)
#12     SsaCodeGenerator.enterSubGraph (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1241)
#13     SsaCodeGenerator.visitSubGraph (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:429)
#14     SsaCodeGenerator.visitGraph (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:420)
#15     SsaCodeGeneratorTask.generateMethod.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:118)
#16     CompilerTask.measure (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63)
#17     SsaCodeGeneratorTask.generateMethod (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:101)
#18     SsaCodeGeneratorTask.generateCode (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/codegen.dart:70)
#19     SsaFunctionCompiler.compile (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/ssa.dart:47)
#20     JavaScriptBackend.codegen (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/js_backend/backend.dart:848)
#21     KernelCodegenWorkItem.run (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:79)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:784)
#23     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#24     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:784)
#25     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#26     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:782)
#27     CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:1156)
#28     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:780)
#29     EnqueuerStrategy.processWorkItem (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/enqueue.dart:513)
#30     CodegenEnqueuer.forEach (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:227)
#31     Compiler.emptyQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:776)
#32     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#33     Compiler.emptyQueue (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:775)
#34     Compiler.processQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:797)
#35     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#36     Compiler.processQueue (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:794)
#37     Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:640)
#38     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#39     Compiler.compileLoadedLibraries (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:534)
#40     Compiler.runInternal (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:488)
<asynchronous suspension>
#41     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:313)
#42     new Future.sync (dart:async/future.dart:222)
#43     Compiler.run.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:313)
#44     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#45     Compiler.run (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:310)
#46     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/apiimpl.dart:265)
#47     _RootZone.runUnary (dart:async/zone.dart:1381)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#49     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#50     _Future._propagateToListeners (dart:async/future_impl.dart:662)
#51     _Future._completeWithValue (dart:async/future_impl.dart:477)
#52     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#53     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#54     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#55     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)


```

**Comment by kevmoo** [comment]
CC @sigmundch @efortuna 

@natebosch – this is via `build_runner` – so wondering if it's usage...

**Comment by natebosch** [comment]
> When compiling the above element

It's not clear to me what element it's talking about - that could be an issue with `build_runner`.

Does this work if you pass `--use-old-frontend` in the dart2js_args?

**Comment by kevmoo** [comment]
> Does this work if you pass --use-old-frontend in the dart2js_args?

Yup!

**Comment by sigmundch** [comment]
@kevmoo - is this compiling pop pop win?

**Comment by kevmoo** [comment]
Yup...

**Comment by sigmundch** [comment]
so this is actually from using `--no-frequency-based-minification`, which turns out a different code path in dart2js that hasn't been ported yet.
