### ISSUE TITLE
assertion failure when inferring doubly compound assignment.

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32611]
I came across this case:
```dart
void main() {
  int y = 1;
  int z = 1;
  z += y += 1;
}
```

Which produces a crash when running the FE in checked mode during inference:
```
'package:front_end/src/fasta/kernel/kernel_shadow_ast.dart': Failed assertion: line 422 pos 16: 'identical(combiner.arguments.positional[0], rhs)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
#1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
#2      ShadowComplexAssignment._inferRhs (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:422:16)
#3      ShadowVariableAssignment._inferExpression (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:2222:26)
#4      ShadowTypeInferrer.inferExpression (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:2066:25)
#5      ShadowExpressionStatement._inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:697:14)
#6      ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:2108:24)
#7      ShadowBlock._inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:179:16)
#8      ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:2108:24)
#9      TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:998:5)
#10     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:640:19)
#11     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684:14)
#12     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718:7)
#13     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565:5)
#14     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:240:5)
#15     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:3053:14)
#16     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2953:14)
#17     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:483:14)
#18     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:337:15)
#19     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198:14)
```

**Comment by stereotype441** [comment]
I'm happy to take a look if time allows, but most of my time is now committed to analyzer work (and I'm going on vacation Apr 2-20), so someone on the FE team (@stefantsov perhaps) will probably have time to look at this before I can.

**Comment by sigmundch** [comment]
my apologies, I wasn't aware... just kept this unassigned to make it clearer

**Comment by sigmundch** [comment]
I'd say low - unless you believe the assertion is indicative of a bigger problem (like some broken invariant in the compiler).

Practically, this only triggered when running the compiler under the VM with assertions enabled. I found code that triggered this in a user package. If we need to debug with assertions enabled, we can undo the nested compound assignment by hand in that code in an instant.
