### ISSUE TITLE
Analyzer crash while editing file in Visual Studio Code

### ISSUE THREAD

**Issue by NicolasJacob** [dart-lang/sdk#32635]
### What I was doing

editing a file.

### Versions

- Dart SDK 2.0.0-dev.40.0
- Visual Studio Code 1.21.1
- Dart Code 2.10.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.10.0
--preview-dart-2
```

### Exception (fatal)

Failed to handle request: {id: 1519, method: edit.getFixes, params: {file: /home/nicolas/project/dart/grpc-dart/lib/src/server/handler.dart, offset: 7635}}

```text
AnalysisException: null

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:143)
#1      AnalysisSessionImpl.getResolvedAst (package:analyzer/src/dart/analysis/session.dart:96)
#2      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:51)
<asynchronous suspension>
#3      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:66)
<asynchronous suspension>
#4      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:47)
#5      DartFileEditBuilderImpl.finalize (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1187)
<asynchronous suspension>
#6      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:69)
<asynchronous suspension>
#7      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:47)
#8      FixProcessor._addFix_addMissingParameter (package:analysis_server/src/services/correction/fix_internal.dart:675)
<asynchronous suspension>
#9      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:294)
<asynchronous suspension>
#10     DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:85)
<asynchronous suspension>
#11     EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:242)
<asynchronous suspension>
#12     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:355)
#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:722)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207)
#15     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:718)
#16     _rootRun (dart:async/zone.dart:1126)
#17     _CustomZone.run (dart:async/zone.dart:1023)
#18     runZoned (dart:async/zone.dart:1490)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:717)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#24     _rootRunUnary (dart:async/zone.dart:1134)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#36     _rootRunUnary (dart:async/zone.dart:1134)
#37     _CustomZone.runUnary (dart:async/zone.dart:1031)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#49     _rootRunUnary (dart:async/zone.dart:1134)
#50     _CustomZone.runUnary (dart:async/zone.dart:1031)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#54     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#55     _StreamController._add (dart:async/stream_controller.dart:639)
#56     _StreamController.add (dart:async/stream_controller.dart:585)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:1674)
#58     _rootRunUnary (dart:async/zone.dart:1138)
#59     _CustomZone.runUnary (dart:async/zone.dart:1031)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#63     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#64     _StreamController._add (dart:async/stream_controller.dart:639)
#65     _StreamController.add (dart:async/stream_controller.dart:585)
#66     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#67     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
#68     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#69     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#70     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/home/nicolas/project/dart/grpc-dart/example/helloworld",
        "explicitFileCount": 6,
        "implicitFileCount": 364,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/home/nicolas/project/dart/grpc-dart/example/route_guide",
        "explicitFileCount": 9,
        "implicitFileCount": 335,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/home/nicolas/project/dart/grpc-dart/example/metadata",
        "explicitFileCount": 6,
        "implicitFileCount": 335,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/home/nicolas/project/dart/grpc-dart",
        "explicitFileCount": 25,
        "implicitFileCount": 448,
        "workItemQueueLength": 2,
        "cacheEntryExceptions": []
    },
    {
        "name": "/home/nicolas/project/dart/grpc-dart/example/googleapis",
        "explicitFileCount": 38,
        "implicitFileCount": 335,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/home/nicolas/project/dart/grpc-dart/interop",
        "explicitFileCount": 8,
        "implicitFileCount": 343,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/47900
