### ISSUE TITLE
No token position for type errors in asserts in --preview-dart-2

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#32640]
`test.dart`:
```dart
typedef T DoSpecialThing<T>(T thing);

String specialStringThing(String thing) => thing;
double specialDoubleThing(double thing) => thing;

class Property<T> {
  Property(this._operation);
  T doThing(T thing) => thing;
  DoSpecialThing<T> get doSpecialThing => _operation;
  DoSpecialThing<T> _operation;
}

Property<String> stringProperty = new Property<String>(specialStringThing);
Property<double> doubleProperty = new Property<double>(specialDoubleThing);

void main() {
  List<Property> properties = [ stringProperty, doubleProperty ];
  List values = [ "String value", 0.0 ];

  for (int i = 0; i < properties.length; ++i) {
    assert(properties[i].doSpecialThing(values[i]) == values[i]);
  }
}
```

Gives:

```
Unhandled exception:
type '(String) => String' is not a subtype of type '(dynamic) => dynamic'
#0      main (file:///usr/local/google/home/zra/dart/dart2tests/test.dart)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Note the lack of line and column numbers in the first line of the stack trace.

/cc @bkonyi

**Comment by mraleph** [comment]
I think CFE might not be assigning the position because the cast is synthetic? /cc @stereotype441

**Comment by stereotype441** [comment]
@mraleph I think you are likely correct.  I'm happy to take a look if time allows, but most of my time is now committed to analyzer work (and I'm going on vacation Apr 2-20), so someone on the FE team (@stefantsov perhaps) will probably have time to look at this before I can.

**Comment by stefantsov** [comment]
I can take a look.  What's the priority?

**Comment by stereotype441** [comment]
I've verified that the CFE *is* assigning a position to the AsExpression.  Perhaps the VM is ignoring it?  @mraleph

**Comment by ezrasandzerbell** [comment]
Got this same error for an unrelated use case. I am trying to use methods from the camera.dart library that were previously working. I ran flutter update yesterday and the camera methods are no longer running. 

**Relevant code:** 

`import 'package:camera/camera.dart';


Future main() async{
  cameras = await availableCameras();
  runApp(new MyApp());
}

//camera code starts here

List<CameraDescription> cameras;`

**The error message that returns:** 

`Launching lib/main.dart on iPhone 7 in debug mode...
Skipping compilation. Fingerprint match.
Running Xcode clean...
Starting Xcode build...
Xcode build done.
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'List<Map<String, String>>' where
  List is from dart:core
  List is from dart:core
  Map is from dart:core
  String is from dart:core
  String is from dart:core

#0      availableCameras (package:camera/camera.dart)
<asynchronous suspension>
#1      main (package:sightworks_flutter/main.dart:15:19)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
Syncing files to device iPhone 7...
Error -32601 received from application: Method not found`
