### ISSUE TITLE
Error occurred while editing widget_inspector.dart in the flutter repo

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#32667]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-173.4674.33`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `IU-173.4674.33, JRE 1.8.0_152-release-1024-b15x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/n5/d160x2xj2095jng193ptjjl00025bq/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.20.0, error: Exception while using a _Visitor to visit a VariableDeclarationStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'parent' was called on null.
Receiver: null
Tried calling: parent
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _getCompilationUnit (package:linter/src/ast.dart:287)
#2      hasErrorWithConstantVisitor (package:linter/src/ast.dart:276)
#3      _Visitor._visitVariableDeclarationList.<anonymous closure> (package:linter/src/rules/prefer_const_declarations.dart:79)
#4      Object

**Comment by bwilkerson** [comment]
I'm assuming that this issue is stale. Please let us know if you're continuing to see the problem.
