### ISSUE TITLE
dart plugin stopped working

### ISSUE THREAD

**Issue by jagdishjadeja** [dart-lang/sdk#32664]
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

i was just using  vs code as normally but something happened with null.dart file and than dart plugin started showing this error

### Versions

- Dart SDK 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
- Visual Studio Code 1.21.1
- Dart Code 2.10.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.10.0
--preview-dart-2
```

### Exception

Analysis failed: c:\Users\DRAGON\Desktop\medico\homecooks\lib\homecook_provider.dart context: exception_20180324_125850_943

```text
Bad state: No definition of type Null
#0      SummaryTypeProvider._getType (package:analyzer/src/summary/summary_sdk.dart:358)
#1      SummaryTypeProvider.nullType (package:analyzer/src/summary/summary_sdk.dart:270)
#2      InferenceContext.pushReturnContext (package:analyzer/src/generated/resolver.dart:4274)
#3      ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5355)
#4      BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1292)
#5      MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7717)
#6      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6088)
#7      UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3106)
#8      ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:7605)
#9      ResolverVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:6061)
#10     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:7597)
#11     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:6051)
#12     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7708)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8221)
#14     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:7206)
#15     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7183)
#16     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5395)
#17     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1911)
#18     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5461)
#19     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2500)
#20     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:697)
#21     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:127)
#22     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
#23     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:126)
#24     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#25     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217)
<asynchronous suspension>
#26     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97)
<asynchronous suspension>
#27     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1218)
<asynchronous suspension>
#28     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#29     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#30     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1010)
<asynchronous suspension>
#31     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1889)
<asynchronous suspension>
#32     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832)
#33     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#34     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#35     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#36     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:442)
#37     _rootRun (dart:async/zone.dart:1126)
#38     _CustomZone.run (dart:async/zone.dart:1023)
#39     runZoned (dart:async/zone.dart:1501)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:482)
#41     Driver.start (package:analysis_server/src/server/driver.dart:441)
#42     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "myproject",
        "explicitFileCount": 14,
        "implicitFileCount": 837,
        "workItemQueueLength": 2,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
I'm assuming that this issue is stale. Please let us know if you're continuing to see the problem.
