### ISSUE TITLE
Analysis server: NoSuchMethodError: The getter 'units' was called on null.

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32686]
I pulled `master` from Flutter a few moments ago and opened the `Stocks` example app and got this crash.

### Versions

- Dart SDK 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
- Flutter SDK 0.2.5-pre.46
- Visual Studio Code 1.21.1
- Dart Code 2.11.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.11.0
--preview-dart-2
```

### Exception

Analysis failed: /Users/danny/Dev/Google/flutter/examples/stocks/test/locale_test.dart context: exception_20180327_192741_169

```text
NoSuchMethodError: The getter 'units' was called on null.
Receiver: null
Tried calling: units
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      LibraryElementInDependency._makeUnitElement (package:analyzer/src/summary/link.dart:4106)
#2      LibraryElementForLink.units (package:analyzer/src/summary/link.dart:3911)
#3      LibraryElementForLink.getContainedName.<anonymous closure> (package:analyzer/src/summary/link.dart:3950)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
#5      LibraryElementForLink.getContainedName (package:analyzer/src/summary/link.dart:3949)
#6      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5528)
#7      TypeProviderForLink.objectType (package:analyzer/src/summary/link.dart:5497)
#8      ClassElementForLink_Class._computeInterfaceType (package:analyzer/src/summary/link.dart:820)
#9      ClassElementForLink_Class.supertype (package:analyzer/src/summary/link.dart:734)
#10     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:310)
#11     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:87)
#12     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1433)
#13     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:4063)
#14     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3799)
#15     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3721)
#16     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:149)
#17     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:115)
#18     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:115)
#19     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:115)
#20     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:115)
#21     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:168)
#22     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3764)
#23     Linker.link (package:analyzer/src/summary/link.dart:4288)
#24     relink (package:analyzer/src/summary/link.dart:132)
#25     link (package:analyzer/src/summary/link.dart:113)
#26     new LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:119)
#27     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#28     new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:118)
#29     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#30     new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:56)
#31     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1375)
<asynchronous suspension>
#32     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1204)
<asynchronous suspension>
#33     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#34     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1181)
<asynchronous suspension>
#35     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1007)
<asynchronous suspension>
#36     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1896)
<asynchronous suspension>
#37     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1839)
#38     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#39     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#40     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#42     _rootRun (dart:async/zone.dart:1126)
#43     _CustomZone.run (dart:async/zone.dart:1023)
#44     runZoned (dart:async/zone.dart:1501)
#45     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#46     Driver.start (package:analysis_server/src/server/driver.dart:443)
#47     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#48     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/danny/Dev/Google/flutter/examples/stocks",
        "explicitFileCount": 15,
        "implicitFileCount": 829,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
@scheglov I seem to remember seeing a fix for this go by. Do you remember?

**Comment by scheglov** [comment]
Hm... No, I don' remember fixing this.
@DanTup Could you please send me this `exception_20180327_192741_169` from the analysis cache directory?

**Comment by DanTup** [comment]
Sent via email!

**Comment by scheglov** [comment]
Oh, we were not able to find `TypeProviderForLink.objectType`.
No SDK found, or something like this maybe?
I will try to test what happens when SDK libraries are not available.

**Comment by DanTup** [comment]
Hmmm, I'm not sure what this means. I ran the analyzer from the SDK using the VM that was in it, so it should all be there :/

**Comment by scheglov** [comment]
I can reproduce this issue in Analysis Driver tests:
```dart
    provider.getFile("$sdkRoot/lib/core/core.dart").delete();
    addTestFile('class C {}');
```

Don't know yet how this happens.

**Comment by scheglov** [comment]
This most probably a race condition of some kind, or a temporary state.

I will add validation into Analysis Driver, we cannot analyze anything if `dart:core` and `dart:async` are not available. We should fail fast with a compilation error, instead of throwing an exception internally.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/48703
