### ISSUE TITLE
Huge memory leak: IntelliJ Dart Analysis Server error

### ISSUE THREAD

**Issue by chances** [dart-lang/sdk#32693]
Analyzer Feedback from IntelliJ

In a IntelliJ project with multiple modules: shared Dart libraries, a Flutter app, a PolymerDart 1.0.0 app, and an AngularDart 5.0.0 app.

The `dart` process running the Analysis Server encounters some massive memory leak. The memory usage of the process balloons to 15GB in 20 seconds.

# Version information

- `IDEA IU-172.3544.18`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `IU-172.3544.18, JRE 1.8.0_152-release-915-b6x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.1 unknown, screens 1440x900, 2560x1440  Retina`

# Exception

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.20.0, error: Analysis failed: /Users/chancesnow/Projects/apptreerevolution-web/revolution/test/date_util_test.dart
RangeError (byteOffset): Invalid value: Not in range 0..5352, inclusive: 1073741885
#0      _ByteDataView.getUint32 (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:4278)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:72)
#2      StringReader.read (package:front_end/src/base/flat_buffers.dart:663)
#3      _FbGenericList.[] (package:front_end/src/base/flat_buffers.dart:826)
#4      Object&ListMixin.toSet (dart:collection/list.dart:258)
#5      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:472)
#6      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#7      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#8      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#9      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#10     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#12     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#13     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#14     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#15     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#16     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#17     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#18     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#19     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#20     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#21     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#22     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#23     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:519)
#24     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#25     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#26     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#27     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#28     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#29     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#30     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#31     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#32     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:519)
#33     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#34     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#35     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#36     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#37     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#38     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#39     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#40     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#41     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:519)
#42     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#43     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#44     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#45     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#46     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#47     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#48     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#49     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#50     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#51     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#52     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#53     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#54     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#55     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#56     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#57     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#58     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#59     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#60     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#61     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#62     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:519)
#63     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:812)
#64     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:582)
#65     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:514)
#66     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:772)
#67     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1146)
<asynchronous suspension>
#68     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1007)
<asynchronous suspension>
#69     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1894)
<asynchronous suspension>
#70     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1837)
#71     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#72     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#73     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#74     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#75     _rootRun (dart:async/zone.dart:1126)
#76     _CustomZone.run (dart:async/zone.dart:1023)
#77     runZoned (dart:async/zone.dart:1501)
#78     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#79     Driver.start (package:analysis_server/src/server/driver.dart:443)
#80     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#81     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#82     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

```
1522182963137 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/forced_logout_dialog_view.dart","errors":[]}}
1522182963138 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/page_switcher_view.dart","errors":[]}}
1522182963139 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/activity_button_view.dart","errors":[]}}
1522182963141 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/image_dialog_view.dart","errors":[]}}
1522182963142 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/browser_toast_view.dart","errors":[]}}
1522182963143 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/di_behaviors.dart","errors":[]}}
1522182963144 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/shared_styles.dart","errors":[]}}
1522182963145 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/visibility_behavior.dart","errors":[]}}
1522182963146 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/card_form_view.dart","errors":[]}}
1522182963146 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/abandon_changes_dialog_view.dart","errors":[]}}
1522182963147 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/confirm_logout_dialog_view.dart","errors":[]}}
1522182963148 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/tap_handler.dart","errors":[]}}
1522182963149 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/views/dialog_view.dart","errors":[]}}
1522182963150 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/notifications/model/notifications.dart","errors":[]}}
1522182963152 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/notifications/views/notifications_view.dart","errors":[]}}
1522182963154 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/onboarding_controller.dart","errors":[{"severity":"INFO","type"
1522182963154 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/model/error_handler_mixin.dart","errors":[]}}
1522182963155 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/model/onboarding_step.dart","errors":[]}}
1522182963155 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/views/onboard_shared_styles.dart","errors":[]}}
1522182963156 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/views/onboarding_controller_proxy.dart","errors":[]}}
1522182963158 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/views/onboard_username.dart","errors":[]}}
1522182963159 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/views/onboard_verify.dart","errors":[{"severity":"INFO","type":
1522182963160 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/views/onboard_complete.dart","errors":[]}}
1522182963161 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/views/onboard_phone_or_email.dart","errors":[]}}
1522182963163 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/views/onboard_start.dart","errors":[]}}
1522182963164 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/views/onboard_account_info.dart","errors":[]}}
1522182963165 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/views/onboarding_app.dart","errors":[{"severity":"ERROR","type"
1522182963165 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/lib/onboarding/views/onboard_page.dart","errors":[]}}
1522182963168 <= {"event":"analysis.errors","params":{"file":"/Users/chancesnow/Projects/apptreerevolution-web/web_client/tool/ci.dart","errors":[]}}
1522182964141 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/chancesnow/Projects/apptreerevolution-web/revolution/test/date_util_test.dart","stackTrace":"Range
```

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.20.0, error: Analysis failed: /Users/chancesnow/Projects/apptreerevolution-web/revolution/test/date_util_test.dart
RangeError (byteOffset): Invalid value: Not in range 0..5352, inclusive: 1073741885
#0      _ByteDataView.getUint32 (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:4278)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:72)
#2      StringReader.read (package:front_end/src/base/flat_buffers.dart:663)
#3      _FbGenericList.[] (package:front_end/src/base/flat_buffers.dart:826)
#4      Object

**Comment by MichaelRFairhurst** [comment]
This should be fixed in 0.0.14. you may need to remove ~/.dartServer/.plugin-manager and restart your analysis/ide.

I will close because it seems like an issue fixed there, but please reopen if update doesn't work!

**Comment by MichaelRFairhurst** [comment]
Actually I'm going to reopen this one. I only just noticed its <1hr old...

**Comment by MichaelRFairhurst** [comment]
To fix the string byte offset/range error itself, you can clear out `~/.dartServer/.analysis-driver/*` to empty your cache. You can try that, though I would suspect in this case, it looks like it will come back.

**Comment by chances** [comment]
Deleting `~/.dartServer/.analysis-driver` resolved both problems. Especially nice not to see the gigantic memory leak.

I'm guessing I was manually purging some analysis cache?

**Comment by MichaelRFairhurst** [comment]
Yep, that cache is critical to the entire process since we do incremental reanalysis. Glad it fixed it for you!

For some info on what might have corrupted the cache, we have a few questions if you have time to answer!
- Did you have the angular plugin installed before this happened?
- Did you recently upgrade your SDK when this happened, and do you know what from/to?
- Did you see it crash with any other sort of error before the rangeerror+leak happened?

**Comment by MichaelRFairhurst** [comment]
I'm going to close since it was fixed for you but please do feel free to check back in with this info, or reopen if you hit it again! Thanks for filing!!

**Comment by chances** [comment]
> Did you have the angular plugin installed before this happened?

Yes.

> Did you recently upgrade your SDK when this happened, and do you know what from/to?

Yes. I had recently upgraded to `2.0.0-dev.42.0`. I don't recall from which version exactly, but I think it was `>2.0.0-dev.30.0`

> Did you see it crash with any other sort of error before the rangeerror+leak happened?

Yes, though I neglected to gather error logs for the first couple errors.
