### ISSUE TITLE
CFE crashes on generic return type in function literal

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#32694]
```
$ echo >test.dart <<EOF
void main() {
  var x = T <T>() {};
}
$ pkg/vm/tool/dart2 test.dart
test.dart:4:11: Error: A function expression can't have a name.                                                                               
  var x = T <T>() {};                       
          ^                                                                                                                             
test.dart:4:11: Error: 'T' already declared in this scope.         
  var x = T <T>() {};                                                                 
          ^                                        
Crash when compiling file:///usr/local/google/home/sjindel/src/dart-sdk/sdk/test.dart,
at character offset 39:                                                               
NoSuchMethodError: Class 'Scope' has no instance getter 'name'.                                 
Receiver: Instance of 'Scope'                                                  
Tried calling: name                                                                
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)                       
#1      BodyBuilder.pushNewLocalVariable (package:front_end/src/fasta/kernel/body_builder.dart:1582)
#2      BodyBuilder.endVariableInitializer (package:front_end/src/fasta/kernel/body_builder.dart:1552)
#3      Parser.parseVariableInitializerOpt (package:front_end/src/fasta/parser/parser.dart:3099)   
#4      Parser.parseOptionallyInitializedIdentifier (package:front_end/src/fasta/parser/parser.dart:5622)
#5      Parser.parseVariablesDeclarationRest (package:front_end/src/fasta/parser/parser.dart:5603)    
#6      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5596)
...
```

**Comment by a-siva** [comment]
Why is this a P2 and not a P1 (I would think any crasher should be a P1 ?

**Comment by peter-ahe-google** [comment]
I have a fix for this: https://dart-review.googlesource.com/c/sdk/+/50040, but I need to extend the tests to cover local variable declarations. Also, I'd like to use the error markers we use in some strong mode tests.

**Comment by kmillikin** [comment]
Hmm, that CL doesn't seem to point anywhere.  I'm going to push this to the next milestone.  We have several other crashers on invalid syntax and so I don't think we have to treat this one specially.  Do you agree @sjindel-google?

**Comment by sjindel-google** [comment]
I think it's fine to punt this one, however, I think it may be more important than the other crashes since this was caused by an honest attempt at writing a function literal with a return type.

**Comment by peter-ahe-google** [comment]
Sorry, I deleted the CL as I tend to do when I modify it before sending it out for review but forgot that I had linked it here.

I discovered an issue when working on this fix that I've addressed in [change 50422](https://dart-review.googlesource.com/c/sdk/+/50422).

**Comment by peter-ahe-google** [comment]
Proposed fix: https://dart-review.googlesource.com/51120
