### ISSUE TITLE
Linker type inference doesn't handle closures with old-style function-typed parameters

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#32708]
Consider the following code:
```dart
var x = (int f(String x)) => 0;
```

With https://dart-review.googlesource.com/c/sdk/+/48741, attempting to produce a summary for the above code produces the following exception:

```
  UnimplementedError: GenericFunctionTypeElementImpl
  #0      _createLinkedType (package:analyzer/src/summary/link.dart:254:5)
  #1      _serializeSyntheticParam (package:analyzer/src/summary/link.dart:304:16)
  #2      _storeFunctionElementByValue.<anonymous closure> (package:analyzer/src/summary/link.dart:350:13)
  ...
```

To reproduce, remove the `@failingTest` annotation from `test_type_inference_closure_with_function_typed_parameter` and run `resynthesize_ast_test.dart`.

Users can work around this issue by using a new-style function-typed parameter, e.g.:

```dart
var x = (int Function(String) f) => 0;
```

**Comment by stereotype441** [comment]
I believe this bug is occurring because https://dart-review.googlesource.com/c/sdk/+/48741 makes the linker use the resolver visitor for type inference, and the resolver visitor creates ordinary `GenericFunctionTypeElementImpl`s to represent function-typed parameters, rather than `GenericFunctionTypeElementForLink`, which is what is expected by the linker.

I think the best way to fix this is to modify the resolver so that when invoked by the linker, it creates `GenericFunctionTypeElementForLink` instead of `GenericFunctionTypeElementImpl`.  This may require adding some form of abstract mechanism or callback so that the client of the resolver can indicate how the resolver should create function type elements.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/48761
