### ISSUE TITLE
Analyzer Error Feedback from IntelliJ

### ISSUE THREAD

**Issue by kostaa** [dart-lang/sdk#32720]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-181.4203.550`
- `2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c`
- `IC-181.4203.550, JRE 1.8.0_152-release-1136-b20x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1680x1050`

# Exception
[report1.txt](https://github.com/dart-lang/sdk/files/1864340/report1.txt)

```
Dart analysis server, SDK version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c, server version 1.20.0, error: Analysis failed: D:\repo__dart_flutter\_built_value.dart\example\lib\collections.g.dart context: exception_20180330_185147_258
RangeError (index): Invalid value: Valid value range is empty: 6
#0      List.[] (dart:core-patch/dart:core/array.dart:10)
#1      CompilationUnitElementForLink.resolveRef (package:analyzer/src/summary/link.dart:1187)
#2      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1253)
#3      ClassElementForLink_Class._computeInterfaceType (package:analyzer/src/summary/link.dart:816)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#5      ListIterable.toList (dart:_internal/iterable.dart:219)
#6      ClassElementForLink_Class.interfaces (package:analyzer/src/summary/link.dart:625)
#7      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:594)
#8      InheritanceManager._computeInterfaceLookupMap (package:analyzer/src/dart/resolver/inheritance_manager.dart:450)
#9      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:675)
#10     InheritanceManager.lookupOverrides (package:analyzer/src/dart/resolver/inheritance_manager.dart:205)
#11     InstanceMemberInferrer._computeFieldOverrideType (package:analyzer/src/task/strong_mode.dart:113)

**Comment by bwilkerson** [comment]
I'm assuming that this issue is stale. Please let us know if you're continuing to see the problem.
