### ISSUE TITLE
Analysis server crash - intelliJ report

### ISSUE THREAD

**Issue by xiahuawuyu** [dart-lang/sdk#32732]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4670197`
- `1.24.2`
- `AI-173.4670197, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\Administrator\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [E:\develop\goWork\flutter_app2\android, E:\develop\goWork\flutter_app2], excluded: [E:\develop\goWork\flutter_app2\.idea, E:\develop\goWork\flutter_app2\.idea, E:\develop\goWork\flutter_app2\.pub, E:\develop\goWork\flutter_app2\build]}, clientRequestTime: 1522637009948}
NoSuchMethodError: The method 'removeFile' was called on null.
Receiver: null
Tried calling: removeFile("E:\\develop\\goWork\\flutter_app2\\.packages.mine")
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ServerContextManagerCallbacks.applyFileRemoved (package:analysis_server/src/analysis_server.dart:2115)
#3      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1520)
#4      _rootRunUnary (dart:async/zone.dart:1128)
#5      _CustomZone.runUnary (dart:async/zone.dart:1012)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257

**Comment by bwilkerson** [comment]
I'm assuming that this issue is stale. Please let us know if you're continuing to see the problem.
