### ISSUE TITLE
BigInt#% error

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#32739]
With `Dart VM version: 2.0.0-dev.42.0` the following program:

```dart
main() {
  print(BigInt.parse("2432363650") % BigInt.parse("2201792050"));
}
```

gives the errors

```
Unhandled exception:
RangeError (index): Index out of range: index should be less than 2: 2
#0      Uint32List.[]= (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:2465)
#1      _BigIntImpl._divRem (dart:core-patch/dart:core/bigint_patch.dart:1368)
#2      _BigIntImpl._rem (dart:core-patch/dart:core/bigint_patch.dart:1292)
#3      _BigIntImpl.% (dart:core-patch/dart:core/bigint_patch.dart:1683)
```

It looks like the breakage landed somewhere between `2.0.0-dev.28.0` (result is `230571600`) and `2.0.0-dev.35.0` (error).

**Comment by vadimtsushko** [comment]
It is still breaking on Dart VM version: 2.0.0-dev.44.0 (Unknown timestamp) on "linux_x64"

**Comment by crelier** [comment]
Thanks for the report. I'll have a look later today.

**Comment by a14n** [comment]
Thanks!
