### ISSUE TITLE
Analyzer 2-dev.44 error when run over site-www examples

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#32740]
Repro:

- Download and setup site-www (following the instructions in the README): https://github.com/dart-lang/site-www
- From the repo root folder run: `scripts/analyze-and-test-examples.sh`.

The issue details given below were generated by WebStorm.

---

Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-173.4674.32`
- `2.0.0-dev.44.0`
- `WS-173.4674.32, JRE 1.8.0_152-release-1024-b15x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1920x1080, 2880x1620  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/cl/hfrjvtvx6bl6t3m8tc1v9xf40000gq/T/report.txt

```nocode
Dart analysis server, SDK version 2.0.0-dev.44.0, server version 1.20.0, error: Analysis failed: /Users/chalin/git/dart/site-www/examples/misc/test/language_tour/callable_classes_test.dart context: exception_20180402_162409_676
NoSuchMethodError: Class 'ClassElementForLink_Class' has no instance method 'lookUpMethod'.
Receiver: Instance of 'ClassElementForLink_Class'
Tried calling: lookUpMethod("call", Instance of 'LibraryElementInBuildUnit')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ClassElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:530)
#2      ElementResolver._isExecutableType (package:analyzer/src/generated/element_resolver.dart:1678)
#3      ElementResolver._getErrorCodeForExecuting (package:analyzer/src/generated/element_resolver.dart:1484)
#4      ElementResolver._checkForInvocationError (package:analyzer/src/generated/element_resolver.dart:1272)
#5      ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:728)
#6      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7861)
#7      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6199)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7861)
#9      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2270)
#10     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:4825)
```

cc @kwalrath @munificent

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I can reproduce the problem on this test case.
```dart
class A {}
class B {
  A a;
}
var c = new B().a();
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/49100

**Comment by chalin** [comment]
I confirm that this now works under Dart 2-dev.46.
