### ISSUE TITLE
Dart analyzer crashes with "getter 'parent' was called on null"

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#32745]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4674.33`
- `2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c`
- `IC-173.4674.33, JRE 1.8.0_152-release-1024-b15x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1440x900, 2560x1600  Retina`

# Exception

Please append the contents of:
```
Dart analysis server, SDK version 2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c, server version 1.20.0, error: Exception while using a _Visitor to visit a TopLevelVariableDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'parent' was called on null.
Receiver: null
Tried calling: parent
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      getCompilationUnit (package:linter/src/ast.dart:151)
#2      hasErrorWithConstantVisitor (package:linter/src/ast.dart:314)
#3      _Visitor._visitVariableDeclarationList.<anonymous closure> (package:linter/src/rules/prefer_const_declarations.dart:79)
#4      Object&ListMixin.every (dart:collection/list.dart:119)
#5      _Visitor._visitVariableDeclarationList (package:linter/src/rules/prefer_const_declarations.dart:78)
#6      _Visitor.visitTopLevelVariableDeclaration (package:linter/src/rules/prefer_const_declarations.dart:69)
#7      TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10608)
#8      ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2757)
#9      List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#10     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2755)
#11     UnifyingAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3206)
#12     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10608)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8253)
#14     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2511)
#15     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#16     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2504)
#18     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:371)
#19     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:163)
#20     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#21     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#23     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:161)
#24     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#25     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:220)
<asynchronous suspension>
#26     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97)
<asynchronous suspension>
#27     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1216)
<asynchronous suspension>
#28     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#29     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1181)
<asynchronous suspension>
#30     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:876)
<asynchronous suspension>
#31     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1896)
<asynchronous suspension>
#32     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1839)
#33     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#34     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#35     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#36     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#37     _rootRun (dart:async/zone.dart:1126)
#38     _CustomZone.run (dart:async/zone.dart:1023)
#39     runZoned (dart:async/zone.dart:1501)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#41     Driver.start (package:analysis_server/src/server/driver.dart:443)
#42     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

```
1522715769320 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/material/feedback_test.dart","errors":[]}}
1522715769369 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/material/modal_bottom_sheet_test.dart","errors":[]}}
1522715769415 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/material/slider_theme_test.dart","errors":[]}}
1522715769426 => {"id":"950","method":"edit.getAssists","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/lib/src/semantics/semantics.dart","offset":59368,"length":0},"clientReque
1522715769437 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/material/scrollbar_paint_test.dart","errors":[]}}
1522715769438 <= {"id":"950","result":{"assists":[]}}
1522715769450 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/services/haptic_feedback_test.dart","errors":[]}}
1522715769458 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/services/system_sound_test.dart","errors":[]}}
1522715769468 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/services/system_chrome_test.dart","errors":[]}}
1522715769496 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/services/asset_bundle_test.dart","errors":[]}}
1522715769505 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/services/system_navigator_test.dart","errors":[]}}
1522715769556 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/modal_barrier_test.dart","errors":[]}}
1522715769576 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/placeholder_test.dart","errors":[]}}
1522715769825 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/semantics_4_test.dart","errors":[]}}
1522715769896 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/navigator_test.dart","errors":[]}}
1522715769941 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/slivers_evil_test.dart","errors":[]}}
1522715770036 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/heroes_test.dart","errors":[]}}
1522715770050 => {"id":"951","method":"edit.getFixes","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/lib/src/semantics/semantics.dart","offset":59358},"clientRequestTime":15227
1522715770069 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/basic_test.dart","errors":[]}}
1522715770070 <= {"id":"951","result":{"fixes":[]}}
1522715770109 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/list_view_builder_test.dart","errors":[]}}
1522715770151 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/semantics_debugger_test.dart","errors":[]}}
1522715770179 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/fade_transition_test.dart","errors":[]}}
1522715770209 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/build_scope_test.dart","errors":[]}}
1522715770244 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/layout_builder_test.dart","errors":[]}}
1522715770248 => {"id":"952","method":"analysis.updateContent","params":{"files":{"/Users/yjbanov/code/flutter/flutter/packages/flutter/lib/src/semantics/semantics.dart":{"type":"add","content":"// Co
1522715770248 => {"id":"953","method":"completion.getSuggestions","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/lib/src/semantics/semantics.dart","offset":59369},"clientReques
1522715770263 <= {"event":"analysis.errors","params":{"file":"/Users/yjbanov/code/flutter/flutter/packages/flutter/test/widgets/listview_end_append_test.dart","errors":[]}}
1522715770265 <= {"id":"952","result":{}}
1522715770360 <= {"event":"server.error","params":{"isFatal":false,"message":"Exception while using a _Visitor to visit a TopLevelVariableDeclarationImpl in CompilationUnitImpl","stackTrace":"NoSuchMe
```

```
Dart analysis server, SDK version 2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c, server version 1.20.0, error: Exception while using a _Visitor to visit a TopLevelVariableDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'parent' was called on null.
Receiver: null
Tried calling: parent
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      getCompilationUnit (package:linter/src/ast.dart:151)
#2      hasErrorWithConstantVisitor (package:linter/src/ast.dart:314)
#3      _Visitor._visitVariableDeclarationList.<anonymous closure> (package:linter/src/rules/prefer_const_declarations.dart:79)
#4      Object

**Comment by bwilkerson** [comment]
We need to pull a new version of the `linter` package into the SDK before the fix can make it to users, and then roll a new version of the SDK into flutter before Flutter users see the fix.
