### ISSUE TITLE
Exception in prefer_const_declarations

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#32751]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA 182.SNAPSHOT`
- `2.0.0-edge.0c892a8bc89c3ed33a92c02cf1a67711115ff25c`
- `IC-182.SNAPSHOT, JRE 1.8.0_112-b16x64 Oracle Corporation, OS Mac OS X(x86_64) v10.13.2 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/cp/_32g44l548q8d0bfj4_l9s3m003ky_/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.0c892a8bc89c3ed33a92c02cf1a67711115ff25c, server version 1.20.0, error: Exception while using a _Visitor to visit a VariableDeclarationStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'parent' was called on null.
Receiver: null
Tried calling: parent
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      getCompilationUnit (package:linter/src/ast.dart:151:54)
#2      hasErrorWithConstantVisitor (package:linter/src/ast.dart:314:14)
#3      _Visitor._visitVariableDeclarationList.<anonymous closure> (package:linter/src/rules/prefer_const_declarations.dart:79:27)
#4      Object

**Comment by a14n** [comment]
Dup of #32745
