### ISSUE TITLE
DDC dsend crashes for generic methods with metadata

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32756]
Test runs as expected with dartdevc.

I was anticipating a dynamic/Object mismatch but not a crash.
If I comment out the o.memberFn calls, the o.map calls fail in a different way.

```
Runtime error:
TypeError: Cannot read property 'length' of undefined
at Object.dart._checkApply (http://127.0.0.1:34193/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4812:36)
    at Object.dart._checkAndCall (http://127.0.0.1:34193/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4916:14)
    at Object.dart.callMethod (http://127.0.0.1:34193/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4981:17)
    at Object.dart.dsend (http://127.0.0.1:34193/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4984:17)
    at function_call_generic_test.main (http://127.0.0.1:34193/root_dart/out/ReleaseX64/generated_compilations/dartdevk-checked-strong-sdk/tests_language_2_function_call_generic_test/function_call_generic_test.js:81:120)

exit code:
0

--- Re-run this test:
python tools/test.py -m release -c dartdevk -r chrome --checked --strong --use-sdk language_2/function_call_generic_test
```

**Comment by jmesserly** [comment]
The cause is the emit-metadata flag (which for some reason, is incorrectly defaulting to `true` in DDK) ... it's failing because of the `@NoInline()` annotation which is kept around in the signature data for dart:mirrors support. Dynamic call helper for generic methods in DDC doesn't expect to find metadata there. Should be an easy fix.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/51040
