### ISSUE TITLE
Dart Analysis Server Error

### ISSUE THREAD

**Issue by hagenpatrick** [dart-lang/sdk#32760]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4670197`
- `2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c`
- `AI-173.4670197, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1280`

# Exception

Please append the contents of:
file://C:\Users\Patrick\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c, server version 1.19.0, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\Patrick\AndroidStudioProjects\flutter_test_app], excluded: [C:\Users\Patrick\AndroidStudioProjects\flutter_test_app\.idea, C:\Users\Patrick\AndroidStudioProjects\flutter_test_app\.dart_tool, C:\Users\Patrick\AndroidStudioProjects\flutter_test_app\.idea, C:\Users\Patrick\AndroidStudioProjects\flutter_test_app\.pub, C:\Users\Patrick\AndroidStudioProjects\flutter_test_app\build]}, clientRequestTime: 1522775729183}
FileSystemException: Exists failed, path = 'C:\Users\Patrick\AndroidStudioProjects\flutter_test_app\.idea\workspace.xml___jb_old___' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:73)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:323)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166)
#3      _HashVMBase

**Comment by bwilkerson** [comment]
I'm assuming that this issue is stale. Please let us know if you're continuing to see the problem.
