### ISSUE TITLE
dart2js Crash with --preview-dart-2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32770]
*will update w/ repo shortly*

```
packages/angular/src/core/linker/app_view.dart:648:20:
Internal Error: Runtime type information not available for type_variable_local(eventHandler1.F) in (local(AppView.eventHandler1#event), local(AppView.eventHandler1#)) for j:closure_call(AppView_eventHandler1_closure.call).
  void Function(E) eventHandler1<E, F extends E>(void Function(F) handler) {
                   ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.0.0-dev.45.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Assertion failure: Runtime type information not available for type_variable_local(eventHandler1.F) in (local(AppView.eventHandler1#event), local(AppView.eventHandler1#)) for j:closure_call(AppView_eventHandler1_closure.call).
#0      failedAt (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:55)
#1      LocalsHandler.readLocal (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/locals_handler.dart:328)
#2      KernelSsaGraphBuilder.visitFunctionNode.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3971)
#3      KernelCodegenWorldBuilder.forEachInstanceField.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/universe/codegen_world_builder.dart:741)
#4      KernelToElementMapBase._forEachClassMember.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:742)
#5      Iterable.forEach (dart:core/iterable.dart:292)
#6      RecordEnv.forEachMember (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/kernel/env.dart:476)
#7      KernelToElementMapBase._forEachClassMember (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:741)
#8      KernelElementEnvironment.forEachClassMember (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:1486)
#9      KernelCodegenWorldBuilder.forEachInstanceField (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/universe/codegen_world_builder.dart:739)
#10     KernelSsaGraphBuilder.visitFunctionNode (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3968)
#11     FunctionNode.accept (package:kernel/ast.dart:1994)
#12     KernelSsaGraphBuilder.visitFunctionExpression (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3991)
#13     FunctionExpression.accept (package:kernel/ast.dart:3513)
#14     KernelSsaGraphBuilder._visitPositionalArguments (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:2862)
#15     KernelSsaGraphBuilder._visitArgumentsForDynamicTarget (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:2875)
#16     KernelSsaGraphBuilder.visitMethodInvocation (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:4045)
#17     MethodInvocation.accept (package:kernel/ast.dart:2820)
#18     KernelSsaGraphBuilder.visitExpressionStatement (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1226)
#19     ExpressionStatement.accept (package:kernel/ast.dart:3808)
#20     KernelSsaGraphBuilder.visitBlock (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1193)
#21     Block.accept (package:kernel/ast.dart:3836)
#22     KernelSsaGraphBuilder.buildFunctionNode (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:963)
#23     KernelSsaGraphBuilder.build.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:209)
#24     CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:1151)
#25     KernelSsaGraphBuilder.build (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:181)
#26     KernelSsaBuilder.build.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:109)
#27     CompilerTask.measure (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63)
#28     KernelSsaBuilder.build (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:95)
#29     SsaBuilderTask.build (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/ssa.dart:91)
#30     SsaFunctionCompiler.compile (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/ssa/ssa.dart:43)
#31     JavaScriptBackend.codegen (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/js_backend/backend.dart:848)
#32     KernelCodegenWorkItem.run (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:79)
#33     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:779)
#34     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#35     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:779)
#36     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#37     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:777)
#38     CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:1151)
#39     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:775)
#40     EnqueuerStrategy.processWorkItem (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/enqueue.dart:523)
#41     CodegenEnqueuer.forEach (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:237)
#42     Compiler.emptyQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:771)
#43     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#44     Compiler.emptyQueue (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:770)
#45     Compiler.processQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:792)
#46     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#47     Compiler.processQueue (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:789)
#48     Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:635)
#49     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#50     Compiler.compileLoadedLibraries (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:529)
#51     Compiler.runInternal (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:483)
<asynchronous suspension>
#52     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:308)
#53     new Future.sync (dart:async/future.dart:222)
#54     Compiler.run.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:308)
#55     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178)
#56     Compiler.run (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:305)
#57     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/apiimpl.dart:263)
#58     _RootZone.runUnary (dart:async/zone.dart:1381)
#59     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#60     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#61     Future._propagateToListeners (dart:async/future_impl.dart:662)
#62     Future._completeWithValue (dart:async/future_impl.dart:477)
#63     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#64     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#65     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#66     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#67     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

**Comment by kevmoo** [comment]
Repro

* clone https://github.com/kevmoo/angular
* checkout branch `i32770_dart2js_repro`
* `cd examples/hacker_news_pwa/`
* `pub get`
* `pub run build_runner serve --config release`

**Comment by rakudrama** [comment]
Compiling this with `--strong` repros:

```dart
var g;

class AppView<T> {
  void Function(E) eventHandler1<E, F extends E>(void Function(F) handler) {
    return (E event) {
      // F;
      g =  () => handler(event as F);
    };
  }
}

main() {
  g = new AppView<String>().eventHandler1(null);
}
```

_updateScopeBasedOnRtiNeed seems to not add F to the outer anonymous closure.
Uncommenting `// F;` 'fixes' the problem.

**Comment by rakudrama** [comment]
After https://dart-review.googlesource.com/c/sdk/+/49640, the error moved to:

```
packages/service_worker/src/js_adapter.dart:39:12:
Internal Error: Runtime type information not available for type_variable_local(futureToPromise.T) in (local(futureToPromise#resolveFn), local(futureToPromise#rejectFn), local(futureToPromise#)) for j:closure_call(futureToPromise_closure.call).
Promise<J> futureToPromise<T, J>(Future<T> future, [J wrapValue(T value)]) {
           ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.0.0-edge.f5da30ef13b9272c0c4a8996e387978765b949eb), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Assertion failure: Runtime type information not available for type_variable_local(futureToPromise.T) in (local(futureToPromise#resolveFn), local(futureToPromise#rejectFn), local(futureToPromise#)) for j:closure_call(futureToPromise_closure.call).
#0      failedAt (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:55)
#1      LocalsHandler.readLocal (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/locals_handler.dart:328)
#2      KernelSsaGraphBuilder.visitFunctionNode.<anonymous closure> (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3971)
#3      KernelCodegenWorldBuilder.forEachInstanceField.<anonymous closure> (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/universe/codegen_world_builder.dart:741)
#4      KernelToElementMapBase._forEachClassMember.<anonymous closure> (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:742)
#5      Iterable.forEach (dart:core/iterable.dart:292)
#6      RecordEnv.forEachMember (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/kernel/env.dart:476)
#7      KernelToElementMapBase._forEachClassMember (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:741)
#8      KernelElementEnvironment.forEachClassMember (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:1486)
#9      KernelCodegenWorldBuilder.forEachInstanceField (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/universe/codegen_world_builder.dart:739)
#10     KernelSsaGraphBuilder.visitFunctionNode (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3968)
#11     FunctionNode.accept (package:kernel/ast.dart:1991)
#12     KernelSsaGraphBuilder.visitFunctionExpression (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3991)
#13     FunctionExpression.accept (package:kernel/ast.dart:3510)
#14     KernelSsaGraphBuilder._visitPositionalArguments (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:2862)
#15     KernelSsaGraphBuilder._visitArgumentsForDynamicTarget (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:2875)
#16     KernelSsaGraphBuilder.visitMethodInvocation (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:4045)
#17     MethodInvocation.accept (package:kernel/ast.dart:2817)
#18     KernelSsaGraphBuilder.visitMethodInvocation (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:4035)
#19     MethodInvocation.accept (package:kernel/ast.dart:2817)
#20     KernelSsaGraphBuilder.visitExpressionStatement (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1226)
#21     ExpressionStatement.accept (package:kernel/ast.dart:3805)
#22     KernelSsaGraphBuilder.visitBlock (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1193)
#23     Block.accept (package:kernel/ast.dart:3833)
#24     KernelSsaGraphBuilder.buildFunctionNode (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:963)
#25     KernelSsaGraphBuilder.build.<anonymous closure> (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:209)
#26     CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/compiler.dart:1151)
#27     KernelSsaGraphBuilder.build (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:181)
#28     KernelSsaBuilder.build.<anonymous closure> (file:///usr/local/google/home/sra/Dart2/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:109)
...
```

**Comment by rakudrama** [comment]
A stand-alone repro of the above error, crashes with both `--strong` and `--strong --omit-implicit-checks`.

```
import 'dart:async' show Future;

Promise<J> futureToPromise<T, J>(Future<T> future, [J wrapValue(T value)]) {
  return new Promise<J>(
    allowInterop(
      (void resolveFn(J value), void rejectFn(error)) {
        future.then((value) {
          dynamic wrapped;
          if (wrapValue != null) {
            wrapped = wrapValue(value);
          } else if (value != null) {
            wrapped = value;
          }
          resolveFn(wrapped);
        }).catchError((error) {
          rejectFn(error);
        });
      },
    ),
  );
}

class Promise<X> {
  var x;
  Promise(this.x);
}

dynamic allowInterop(dynamic x) => x;

main() {
  print(futureToPromise);
}
```
