### ISSUE TITLE
Poor quality error message from Dart VM constant evaluation

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#32805]
In this code

```dart
class Bar {
  const Bar();
}

class Foo {
  void foo({Bar bar: Bar()}) {}
}

main() {
  new Foo().foo();
}
```
and after the landing of this CL: https://dart-review.googlesource.com/c/sdk/+/49900

The VM reports:

```
Unhandled exception:
'file:....dart': error: Not a constant expression: unexpected kernel tag ConstructorInvocation (31)
#0      main (file:///....dart:10:13)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by srawlins** [comment]
In Dart 2.5.0-dev.2.1, with const-update-2018, this code no longer errors.
