### ISSUE TITLE
stderr.addError exits programs

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#32808]
Tested with `DartVM-1.24.2` and `DartVM-2.0.0-dev.44.0`.

The following program exits with unhandled exception.

```dart
import 'dart:async';
import 'dart:io';

main() async {
  for (var i = 0; i < 5; i++) {
    print(i);
    try {
      await m();
    } catch (e) {
      print('error $i');
      print(e);
      stderr.addError(e);
    }
  }
}

Future m() async {
  print('m');
  throw 'throw';
}
```

It produces the following output. Note that it should iterate 5 times.

```
$ dart --version
Dart VM version: 2.0.0-dev.44.0 (Mon Apr 2 16:14:58 2018 +0200) on "linux_x64"
$ dart test.dart
0
m
error 0
throw
1
m
error 1
throw
2
Unhandled exception:
throw
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

If I comment out `stderr.addError(e);` I get the following output:

```
$ dart test.dart
0
m
error 0
throw
1
m
error 1
throw
2
m
error 2
throw
3
m
error 3
throw
4
m
error 4
throw
```

**Comment by bkonyi** [comment]
I've been able to reproduce this. I'll investigate.

**Comment by bkonyi** [comment]
It appears that this is consistent behavior with all streams which do not have error handlers registered, so I think this is working as intended.

```dart
import 'dart:async';

main() async {
  final c = new StreamController<String>();
  c.stream.listen((e) {
    print("Stream: $e");
  });
  c.add('Foobar');
  c.addError('Error!');
}
```

Which results in the following exception:

```
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```
Is there any reason why you want to call `addError` on `stderr`? If you're just trying to print to `stderr` you can use `stderr.write` to accomplish that.

**Comment by a14n** [comment]
I used `addError` because it was its signature was close to the `catch (e,s)`. This behaviour is really unintuitive.
