### ISSUE TITLE
DartkCrash in BinaryPrinter for tests expecting compile-time errors

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#32800]
The same CL which is referenced in #32590 is experiencing DartkCrash failures in BinaryPrinter on the trybots. Failures can be seen [here](https://dart-review.googlesource.com/c/sdk/+/46820). This is blocking fixes which make hot reload behaviour consistent with Dart 1.0.

**Comment by peter-ahe-google** [comment]
From [dart/buildbucket/cr-buildbucket.appspot.com/8950063878231555008/+/steps/vm_strong_tests_shard_3/0/stdout](https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8950063878231555008%2F%2B%2Fsteps%2Fvm_strong_tests_shard_3%2F0%2Fstdout):

```
FAILED: dartk-vm release_x64 language_2/switch4_negative_test
Expected: Pass
Actual: DartkCrash
--- Command "vm" (took 01.000285s):
DART_CONFIGURATION=ReleaseX64 DART_USE_SDK=1 pkg/vm/tool/dart2 --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/language_2/switch4_negative_test.dart
exit code:
252
stderr:
tests/language_2/switch4_negative_test.dart: Error: Label not found: 'L'.
NoSuchMethodError: The method '<' was called on null.
Receiver: null
Tried calling: <(128)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      BinaryPrinter.writeUInt30 (package:kernel/binary/ast_to_binary.dart:78)
#2      BinaryPrinter.visitContinueSwitchStatement (package:kernel/binary/ast_to_binary.dart:1512)
#3      ContinueSwitchStatement.accept (package:kernel/ast.dart:4202)
#4      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#5      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#6      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#7      BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1392)
#8      Block.accept (package:kernel/ast.dart:3833)
#9      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#10     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#11     BinaryPrinter.visitSwitchCase (package:kernel/binary/ast_to_binary.dart:1505)
#12     SwitchCase.accept (package:kernel/ast.dart:4180)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#14     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#15     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#16     BinaryPrinter.visitSwitchStatement (package:kernel/binary/ast_to_binary.dart:1491)
#17     SwitchStatement.accept (package:kernel/ast.dart:4135)
#18     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#19     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#20     BinaryPrinter.visitLabeledStatement (package:kernel/binary/ast_to_binary.dart:1425)
#21     LabeledStatement.accept (package:kernel/ast.dart:3936)
#22     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#23     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#24     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#25     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1392)
#26     Block.accept (package:kernel/ast.dart:3833)
#27     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#28     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#29     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:237)
#30     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:950)
#31     FunctionNode.accept (package:kernel/ast.dart:1991)
#32     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#33     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#34     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:237)
#35     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:814)
#36     Procedure.accept (package:kernel/ast.dart:1653)
#37     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#38     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#39     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#40     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:745)
#41     Class.accept (package:kernel/ast.dart:859)
#42     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#43     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#44     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#45     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:597)
#46     Library.accept (package:kernel/ast.dart:409)
#47     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#48     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#49     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#50     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:213)
#51     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49)
#52     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:309)
#53     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:57)
#54     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:322)
<asynchronous suspension>
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
--- Re-run this test:
python tools/test.py -m release -c dartk -r vm --strong --use-sdk --output-directory /b/s/w/ioqPi3IY --builder-tag swarming language_2/switch4_negative_test
```

**Comment by peter-ahe-google** [comment]
From [dart/buildbucket/cr-buildbucket.appspot.com/8950063878231555008/+/steps/vm_strong_tests_shard_5/0/stdout](https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8950063878231555008%2F%2B%2Fsteps%2Fvm_strong_tests_shard_5%2F0%2Fstdout):

```
FAILED: dartk-vm release_x64 language_2/conditional_property_access_test/05
Expected: Pass
Actual: DartkCrash
Missing expected compile error.
--- Command "vm" (took 01.000881s):
DART_CONFIGURATION=ReleaseX64 DART_USE_SDK=1 pkg/vm/tool/dart2 --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseX64/generated_tests/language_2/conditional_property_access_test_05.dart
exit code:
252
stderr:
xcodebuild/ReleaseX64/generated_tests/language_2/conditional_property_access_test_05.dart:45:32: Error: The getter 'bad' isn't defined for the class '#lib1::C'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bad'.
  Expect.equals(null, nullC()?.bad); //# 05: compile-time error
                               ^
NoSuchMethodError: The method '&' was called on null.
Receiver: null
Tried calling: &(7)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      BinaryPrinter.visitVariableGet (package:kernel/binary/ast_to_binary.dart:969)
#2      VariableGet.accept (package:kernel/ast.dart:2138)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#5      BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:237)
#6      BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1589)
#7      BinaryPrinter.visitLet (package:kernel/binary/ast_to_binary.dart:1314)
#8      Let.accept (package:kernel/ast.dart:3559)
#9      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#10     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#11     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#12     BinaryPrinter.visitArguments (package:kernel/binary/ast_to_binary.dart:1125)
#13     Arguments.accept (package:kernel/ast.dart:2686)
#14     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#15     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#16     BinaryPrinter.visitStaticInvocation (package:kernel/binary/ast_to_binary.dart:1108)
#17     StaticInvocation.accept (package:kernel/ast.dart:2926)
#18     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#19     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#20     BinaryPrinter.visitExpressionStatement (package:kernel/binary/ast_to_binary.dart:1385)
#21     ExpressionStatement.accept (package:kernel/ast.dart:3805)
#22     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#23     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#24     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#25     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1392)
#26     Block.accept (package:kernel/ast.dart:3833)
#27     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#28     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#29     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:237)
#30     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:950)
#31     FunctionNode.accept (package:kernel/ast.dart:1991)
#32     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#33     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#34     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:237)
#35     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:814)
#36     Procedure.accept (package:kernel/ast.dart:1653)
#37     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#38     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#39     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#40     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:601)
#41     Library.accept (package:kernel/ast.dart:409)
#42     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#43     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#44     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#45     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:213)
#46     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49)
#47     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:309)
#48     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:57)
#49     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:322)
<asynchronous suspension>
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
--- Re-run this test:
python tools/test.py -m release -c dartk -r vm --strong --use-sdk --output-directory /b/s/w/ioXhlJRD --builder-tag swarming language_2/conditional_property_access_test/05
FAILED: dartk-vm release_x64 language_2/conditional_property_access_test/06
Expected: Pass
Actual: DartkCrash
Missing expected compile error.
--- Command "vm" (took 01.000816s):
DART_CONFIGURATION=ReleaseX64 DART_USE_SDK=1 pkg/vm/tool/dart2 --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseX64/generated_tests/language_2/conditional_property_access_test_06.dart
exit code:
252
stderr:
xcodebuild/ReleaseX64/generated_tests/language_2/conditional_property_access_test_06.dart:46:41: Error: The getter 'v' isn't defined for the class '#lib1::B'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'v'.
  { B b = new C(1); Expect.equals(1, b?.v); } //# 06: compile-time error
                                        ^
NoSuchMethodError: The method '&' was called on null.
Receiver: null
Tried calling: &(7)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      BinaryPrinter.visitVariableGet (package:kernel/binary/ast_to_binary.dart:969)
#2      VariableGet.accept (package:kernel/ast.dart:2138)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#5      BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:237)
#6      BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1589)
#7      BinaryPrinter.visitLet (package:kernel/binary/ast_to_binary.dart:1314)
#8      Let.accept (package:kernel/ast.dart:3559)
#9      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#10     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#11     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#12     BinaryPrinter.visitArguments (package:kernel/binary/ast_to_binary.dart:1125)
#13     Arguments.accept (package:kernel/ast.dart:2686)
#14     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#15     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#16     BinaryPrinter.visitStaticInvocation (package:kernel/binary/ast_to_binary.dart:1108)
#17     StaticInvocation.accept (package:kernel/ast.dart:2926)
#18     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#19     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#20     BinaryPrinter.visitExpressionStatement (package:kernel/binary/ast_to_binary.dart:1385)
#21     ExpressionStatement.accept (package:kernel/ast.dart:3805)
#22     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#23     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#24     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#25     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1392)
#26     Block.accept (package:kernel/ast.dart:3833)
#27     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#28     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#29     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#30     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1392)
#31     Block.accept (package:kernel/ast.dart:3833)
#32     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#33     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#34     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:237)
#35     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:950)
#36     FunctionNode.accept (package:kernel/ast.dart:1991)
#37     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#38     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#39     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:237)
#40     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:814)
#41     Procedure.accept (package:kernel/ast.dart:1653)
#42     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#43     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#44     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#45     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:601)
#46     Library.accept (package:kernel/ast.dart:409)
#47     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#48     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#49     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#50     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:213)
#51     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49)
#52     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:309)
#53     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:57)
#54     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:322)
<asynchronous suspension>
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
--- Re-run this test:
python tools/test.py -m release -c dartk -r vm --strong --use-sdk --output-directory /b/s/w/ioXhlJRD --builder-tag swarming language_2/conditional_property_access_test/06
FAILED: dartk-vm release_x64 lib_2/mirrors/library_imports_bad_metadata_test/01
Expected: Pass
Actual: DartkCrash
Missing expected compile error.
--- Command "vm" (took 01.000361s):
DART_CONFIGURATION=ReleaseX64 DART_USE_SDK=1 pkg/vm/tool/dart2 --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseX64/generated_tests/lib_2/mirrors/library_imports_bad_metadata_test_01.dart
exit code:
252
stderr:
xcodebuild/ReleaseX64/generated_tests/lib_2/mirrors/library_imports_bad_metadata_test_01.dart:7:2: Error: Getter not found: 'undefined'.
@undefined // //# 01: compile-time error
 ^
xcodebuild/ReleaseX64/generated_tests/lib_2/mirrors/library_imports_bad_metadata_test_01.dart: Error: This can't be used as metadata; metadata should be a reference to a compile-time constant variable, or a call to a constant constructor.
NoSuchMethodError: The method 'declare' was called on null.
Receiver: null
Tried calling: declare(Instance of 'VariableDeclaration')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1592)
#2      BinaryPrinter.visitLet (package:kernel/binary/ast_to_binary.dart:1314)
#3      Let.accept (package:kernel/ast.dart:3559)
#4      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#5      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#6      BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:237)
#7      BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1589)
#8      BinaryPrinter.visitLet (package:kernel/binary/ast_to_binary.dart:1314)
#9      Let.accept (package:kernel/ast.dart:3559)
#10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#11     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#12     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#13     BinaryPrinter.writeLibraryDependency (package:kernel/binary/ast_to_binary.dart:645)
#14     BinaryPrinter.writeLibraryDependencies (package:kernel/binary/ast_to_binary.dart:628)
#15     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:592)
#16     Library.accept (package:kernel/ast.dart:409)
#17     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#18     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#19     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#20     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:213)
#21     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49)
#22     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:309)
#23     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:57)
#24     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:322)
<asynchronous suspension>
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
--- Re-run this test:
python tools/test.py -m release -c dartk -r vm --strong --use-sdk --output-directory /b/s/w/ioXhlJRD --builder-tag swarming lib_2/mirrors/library_imports_bad_metadata_test/01
```

**Comment by peter-ahe-google** [comment]
I can reproduce the first crash using:

```
./pkg/front_end/tool/fasta compile --strong tests/language_2/switch4_negative_test.dart
```

**Comment by peter-ahe-google** [comment]
I think the test.py Fasta compiler configuration has a bug regarding crashes.

**Comment by peter-ahe-google** [comment]
No, this not a bug in test.py's implementation of Fasta compiler configuration. The status file does say it crashes.

**Comment by bkonyi** [comment]
Looks like there's at least one more issue [here](https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8949618579803678224%2F%2B%2Fsteps%2Fvm_strong_tests_shard_5%2F0%2Fstdout):

```=== Failure summary:
FAILED: dartk-vm release_x64 lib_2/mirrors/library_imports_bad_metadata_test/01
Expected: Pass
Actual: DartkCrash
Missing expected compile error.
--- Command "vm" (took 01.000319s):
DART_CONFIGURATION=ReleaseX64 DART_USE_SDK=1 pkg/vm/tool/dart2 --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseX64/generated_tests/lib_2/mirrors/library_imports_bad_metadata_test_01.dart
exit code:
252
stderr:
xcodebuild/ReleaseX64/generated_tests/lib_2/mirrors/library_imports_bad_metadata_test_01.dart:7:2: Error: Getter not found: 'undefined'.
@undefined // //# 01: compile-time error
 ^
xcodebuild/ReleaseX64/generated_tests/lib_2/mirrors/library_imports_bad_metadata_test_01.dart: Error: This can't be used as metadata; metadata should be a reference to a compile-time constant variable, or a call to a constant constructor.
NoSuchMethodError: The method 'declare' was called on null.
Receiver: null
Tried calling: declare(Instance of 'VariableDeclaration')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1592)
#2      BinaryPrinter.visitLet (package:kernel/binary/ast_to_binary.dart:1314)
#3      Let.accept (package:kernel/ast.dart:3559)
#4      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#5      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#6      BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:237)
#7      BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1589)
#8      BinaryPrinter.visitLet (package:kernel/binary/ast_to_binary.dart:1314)
#9      Let.accept (package:kernel/ast.dart:3559)
#10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#11     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#12     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:221)
#13     BinaryPrinter.writeLibraryDependency (package:kernel/binary/ast_to_binary.dart:645)
#14     BinaryPrinter.writeLibraryDependencies (package:kernel/binary/ast_to_binary.dart:628)
#15     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:592)
#16     Library.accept (package:kernel/ast.dart:409)
#17     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:229)
#18     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#19     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#20     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:213)
#21     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49)
#22     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:309)
#23     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:57)
#24     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:322)
<asynchronous suspension>
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
--- Re-run this test:
python tools/test.py -m release -c dartk -r vm --strong --use-sdk --output-directory /b/s/w/ioiUEBTK --builder-tag swarming lib_2/mirrors/library_imports_bad_metadata_test/01
===
=== 1 test failed
===```

**Comment by dgrove** [comment]
any updates on this, @askeksa-google ?

**Comment by askeksa-google** [comment]
Looking into that undefined metadata crash...
