### ISSUE TITLE
Bug report from analysis server in VSCode

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/sdk#32812]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Typing Dart code in VS code.

### Versions

- Dart SDK 2.0.0-dev.39.0
- Visual Studio Code 1.21.1
- Dart Code 2.12.0-dev

### Analyzer Info

The analyzer was launched using the arguments:

```text
/usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.12.0-dev
--no-preview-dart-2
```

### Exception

Exception while using a _Visitor to visit a VariableDeclarationStatementImpl in BlockImpl in ForEachStatementImpl in LabeledStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl

```text
NoSuchMethodError: The getter 'parent' was called on null.
Receiver: null
Tried calling: parent
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _getCompilationUnit (package:linter/src/ast.dart:287)
#2      hasErrorWithConstantVisitor (package:linter/src/ast.dart:276)
#3      _Visitor._visitVariableDeclarationList.<anonymous closure> (package:linter/src/rules/prefer_const_declarations.dart:79)
#4      Object&ListMixin.every (dart:collection/list.dart:119)
#5      _Visitor._visitVariableDeclarationList (package:linter/src/rules/prefer_const_declarations.dart:78)
#6      _Visitor.visitVariableDeclarationStatement (package:linter/src/rules/prefer_const_declarations.dart:73)
#7      VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11476)
#8      ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2757)
#9      List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#10     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2755)
#11     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:3232)
#12     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11476)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8246)
#14     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1351)
#15     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#16     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#17     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1347)
#18     ForEachStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4766)
#19     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#20     UnifyingAstVisitor.visitForEachStatement (package:analyzer/dart/ast/visitor.dart:3017)
#21     ForEachStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4759)
#22     LabeledStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7090)
#23     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#24     UnifyingAstVisitor.visitLabeledStatement (package:analyzer/dart/ast/visitor.dart:3088)
#25     LabeledStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:7085)
#26     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8246)
#27     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1351)
#28     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#29     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#30     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1347)
#31     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1296)
#32     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#33     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#34     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1292)
#35     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5430)
#36     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#37     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#38     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5424)
#39     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5275)
#40     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#41     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026)
#42     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5268)
#43     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8246)
#44     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2507)
#45     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#46     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#47     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2500)
#48     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:371)
#49     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:163)
#50     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#51     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162)
#52     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:207)
#53     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:161)
#54     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#55     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217)
<asynchronous suspension>
#56     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97)
<asynchronous suspension>
#57     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1218)
<asynchronous suspension>
#58     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#59     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#60     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:989)
<asynchronous suspension>
#61     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1889)
<asynchronous suspension>
#62     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832)
#63     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#64     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#65     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#66     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#67     _rootRun (dart:async/zone.dart:1126)
#68     _CustomZone.run (dart:async/zone.dart:1023)
#69     runZoned (dart:async/zone.dart:1501)
#70     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#71     Driver.start (package:analysis_server/src/server/driver.dart:443)
#72     main (file:///tmp/tmpvgnPvD/dart-2.0.0-dev.39.0/dart/pkg/analysis_server/bin/server.dart:12)
#73     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/home/herman/repos/qedb/expr",
        "explicitFileCount": 35,
        "implicitFileCount": 411,
        "workItemQueueLength": 2,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
@pq This has been fixed in the linter package, but might require a pull into the SDK.

**Comment by pq** [comment]
Landed w/ https://github.com/dart-lang/sdk/commit/516b59bd653d18126c05b76a88cc74f85088b899

**Comment by devoncarew** [comment]
assumed closed w/ the linter update
