### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by VijayMaurya2079** [dart-lang/sdk#32817]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4670197`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `AI-173.4670197, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\HP\AppData\Local\Temp\report2.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.6, error: Analysis failed: C:\Users\HP\Desktop\hello_flutter\lib\main.dart context: exception_20180407_120502_721
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/dart:core/array.dart:133)
#1      _LibraryResynthesizer.createUnitResynthesizer (package:analyzer/src/summary/resynthesize.dart:1025)
#2      _LibraryResynthesizer.buildLibrary (package:analyzer/src/summary/resynthesize.dart:963)
#3      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:256)
#4      _HashVMBase

**Comment by bwilkerson** [comment]
@scheglov

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this issue.
