### ISSUE TITLE
dart2js: strong mode crash during inlining

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32828]
Here is the stack trace:

stack trace:
```
Internal Error: The compiler crashed when compiling this element.                
  ComponentRef<T> loadNextToLocation<T>(          
                  ^                                                              
....

RangeError (index): Invalid value: Not in range 0..4, inclusive: 5
0      List.[] (dart:core-patch/dart:core/growable_array.dart:141)                                                                                         
#1      KernelSsaGraphBuilder._completeDynamicCallArgumentsList (package:compiler/src/ssa/builder_kernel.dart:4888:55)
#2      KernelSsaGraphBuilder._completeCallArgumentsList (package:compiler/src/ssa/builder_kernel.dart:4813:14)
#3      KernelSsaGraphBuilder._tryInlineMethod.doInlining (package:compiler/src/ssa/builder_kernel.dart:4768:46)
#4      KernelSsaGraphBuilder._tryInlineMethod (package:compiler/src/ssa/builder_kernel.dart:4782:17)
#5      KernelSsaGraphBuilder._pushDynamicInvocation (package:compiler/src/ssa/builder_kernel.dart:3825:11)
#6      KernelSsaGraphBuilder.visitMethodInvocation (package:compiler/src/ssa/builder_kernel.dart:4041:5)
#7      MethodInvocation.accept (package:kernel/ast.dart:2817:36)                
#8      KernelSsaGraphBuilder.visitReturnStatement (package:compiler/src/ssa/builder_kernel.dart:1259:23)
#9      ReturnStatement.accept (package:kernel/ast.dart:4254:35)                 
#10     KernelSsaGraphBuilder.visitBlock (package:compiler/src/ssa/builder_kernel.dart:1193:17)
#11     Block.accept (package:kernel/ast.dart:3833:35)                           
#12     KernelSsaGraphBuilder.buildFunctionNode (package:compiler/src/ssa/builder_kernel.dart:963:23)
#13     KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:196:15)
#14     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:1151:15)
#15     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:181:21)
#16     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/kernel/kernel_backend_strategy.dart:109:22)
#17     CompilerTask.measure (package:compiler/src/common/tasks.dart:63:44)          
#18     KernelSsaBuilder.build (package:compiler/src/kernel/kernel_backend_strategy.dart:95:17)
#19     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:91:21)               
#20     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:43:29)    
#21     JavaScriptBackend.codegen (package:compiler/src/js_backend/backend.dart:848:43)
#22     KernelCodegenWorkItem.run (package:compiler/src/kernel/kernel_backend_strategy.dart:79:21)
#23     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compil
#24     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:178:35)
#25     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:779:32)
#26     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:178:35)
```

The code in question is defined here: https://github.com/dart-lang/angular/blob/a7f10cb665a763e32ae0f42a2823168af4eccbe4/angular/lib/src/core/linker/component_loader.dart#L102

I don't have a small repro yet, but will try to work on one.

**Comment by sigmundch** [comment]
Here is a reduced repro:
```dart
class A {
  void m2<T>(void Function(T) f, [a]) {}
}

void m1(String x) {}

main() => new A().m2<String>(m1);
```
