### ISSUE TITLE
Dart Analysis Issue

### ISSUE THREAD

**Issue by ChemSwift** [dart-lang/sdk#32824]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4670197`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `AI-173.4670197, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.4 unknown, screens 1920x1080, 1920x1080, 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/0n/l3xb74416l9cvzsn5l_yy5tm0000gn/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.19.0, error: Exception while using a Visitor to visit a ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: Class 'DynamicTypeImpl' has no instance getter 'superclass'.
Receiver: Instance of 'DynamicTypeImpl'
Tried calling: superclass
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      Visitor._getSelfAndInheritedTypes (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:132)
#2      _SyncIterator.moveNext (dart:core-patch/dart:core/core_patch.dart:153)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#4      ExpandIterator.moveNext (dart:_internal/iterable.dart:477)
#5      MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#6      Iterable.any (dart:core/iterable.dart:400)
#7      Visitor._hasImmutableAnnotation (package:linter/src/rules/prefer_const_literals_to_create_immutables.dart:125)

**Comment by bwilkerson** [comment]
Thank you for the report.

This issue was fixed in the linter package on 3/12, and should be in the next dev release of the SDK. Please let us know if you're still encountering this issue after updating.
