### ISSUE TITLE
Failure in regress_29137_vm_test, precompiled, simarm64

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32855]
Cf. [this log](https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8949465721553171280%2F%2B%2Fsteps%2Fstrong_vm_tests_shard_2%2F0%2Fstdout), we get the following failure:

```
FAILED: dartkp-dart_precompiled release_simarm64 language_2/vm/regress_29137_vm_test
Expected: Pass
Actual: RuntimeError
--- Command "vm_compile_to_kernel" (took 02.000453s):
DART_CONFIGURATION=ReleaseSIMARM64 DART_VM_FLAGS=--limit-ints-to-64-bits /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --strong-mode --sync-async --platform=out/ReleaseSIMARM64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp-strong/tests_language_2_vm_regress_29137_vm_test/out.dill --entry-points out/ReleaseSIMARM64/gen/runtime/bin/precompiler_entry_points.json --entry-points /b/s/w/ir/pkg/vm/lib/transformations/type_flow/entry_points_extra.json --entry-points /b/s/w/ir/pkg/vm/lib/transformations/type_flow/entry_points_extra_standalone.json /b/s/w/ir/tests/language_2/vm/regress_29137_vm_test.dart
exit code:
0
--- Command "precompiler" (took 04.000879s):
DART_CONFIGURATION=ReleaseSIMARM64 out/ReleaseSIMARM64/dart_bootstrap --snapshot-kind=app-aot --snapshot=/b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp-strong/tests_language_2_vm_regress_29137_vm_test/out.aotsnapshot --use-blobs --strong --preview-dart-2 --no-background-compilation --reify-generic-functions --limit-ints-to-64-bits --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp-strong/tests_language_2_vm_regress_29137_vm_test/out.dill
exit code:
0
--- Command "remove_kernel_file" (took 26ms):
DART_CONFIGURATION=ReleaseSIMARM64 rm /b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp-strong/tests_language_2_vm_regress_29137_vm_test/out.dill
exit code:
0
--- Command "vm" (took 153ms):
DART_CONFIGURATION=ReleaseSIMARM64 out/ReleaseSIMARM64/dart_precompiled_runtime --preview-dart-2 --optimization-counter-threshold=5 --no-background-compilation --reify-generic-functions --limit-ints-to-64-bits --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp-strong/tests_language_2_vm_regress_29137_vm_test/out.aotsnapshot
exit code:
255
stderr:
Unhandled exception:
Expect.equals(expected: <4026532080>, actual: <1034818683120>) fails.
#0      Expect._fail (package:expect/expect.dart:603)
#1      Expect.equals (package:expect/expect.dart:124)
#2      main (file:///b/s/w/ir/tests/language_2/vm/regress_29137_vm_test.dart:32)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165)
--- Re-run this test:
python tools/test.py -m release -c dartkp -r dart_precompiled -a simarm64 --strong --use-blobs --output-directory /b/s/w/ioA22aKm language_2/vm/regress_29137_vm_test
Done dartkp-dart_precompiled release_simarm64 language_2/vm/regress_29137_vm_test: fail
```

**Comment by eernstg** [comment]
Failures like the above occur also in [build 560](https://ci.chromium.org/p/dart/builders/luci.dart.ci/vm-kernel-precomp-linux-release-simarm64/560) and in [build 561](https://ci.chromium.org/p/dart/builders/luci.dart.ci/vm-kernel-precomp-linux-release-simarm64/561), so the issue does not look like a flake.

**Comment by mraleph** [comment]
I think we reverted the offending change, the bot should cycle green.
