### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by PachyrhizusRen** [dart-lang/sdk#32854]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4670197`
- `2.0.0-dev.16.0`
- `AI-173.4670197, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Administrator\AppData\Local\Temp\report2.txt
```
Dart analysis server, SDK version 2.0.0-dev.16.0, server version 1.18.4, error: Analysis failed: D:\git\fluttertest\lib\main\home.dart
Bad state: Expected element reference for analyzer offset 295; got one for kernel offset 232
#0      ValidatingResolutionApplier._getReferenceFor (package:analyzer/src/fasta/resolution_applier.dart:1008)
#1      ResolutionApplier.visitInstanceCreationExpression (package:analyzer/src/fasta/resolution_applier.dart:334)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6444)
#3      ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9142)
#4      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#5      GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#6      GeneralizingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:472)
#7      ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:9138)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8050)
#9      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1346)
#10     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#11     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#12     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:184)
#13     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1342)
#14     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1291)
#15     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#16     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314)
#17     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:187)
#18     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1287)
#19     LibraryAnalyzer._resolveFile2 (package:analyzer/src/dart/analysis/library_analyzer.dart:778)
#20     LibraryAnalyzer._analyze2.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:210)
#21     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
#22     LibraryAnalyzer._analyze2 (package:analyzer/src/dart/analysis/library_analyzer.dart:209)
<asynchronous suspension>
#23     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:97)
<asynchronous suspension>
#24     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217)
<asynchronous suspension>
#25     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:95)
<asynchronous suspension>
#26     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1216)
<asynchronous suspension>
#27     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#28     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:989)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1887)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1830)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:386)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#35     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:436)
#36     _rootRun (dart:async/zone.dart:1126)
#37     _CustomZone.run (dart:async/zone.dart:1023)
#38     runZoned (dart:async/zone.dart:1501)
#39     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:476)
#40     Driver.start (package:analysis_server/src/server/driver.dart:435)
#41     main (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

```
1523512739997 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1523512740593 => {"id":"916","method":"analysis.updateContent","params":{"files":{"D:\\git\\fluttertest\\lib\\main\\home.dart":{"type":"add","content":"import 'package:flutter/material.dart';\n\nclass
1523512740594 => {"id":"917","method":"completion.getSuggestions","params":{"file":"D:\\git\\fluttertest\\lib\\main\\home.dart","offset":373},"clientRequestTime":1523512740594}
1523512740711 => {"id":"918","method":"analysis.updateContent","params":{"files":{"D:\\git\\fluttertest\\lib\\main\\home.dart":{"type":"add","content":"import 'package:flutter/material.dart';\n\nclass
1523512740711 => {"id":"919","method":"completion.getSuggestions","params":{"file":"D:\\git\\fluttertest\\lib\\main\\home.dart","offset":374},"clientRequestTime":1523512740711}
1523512740872 => {"id":"920","method":"analysis.updateContent","params":{"files":{"D:\\git\\fluttertest\\lib\\main\\home.dart":{"type":"add","content":"import 'package:flutter/material.dart';\n\nclass
1523512740872 => {"id":"921","method":"completion.getSuggestions","params":{"file":"D:\\git\\fluttertest\\lib\\main\\home.dart","offset":375},"clientRequestTime":1523512740872}
1523512740960 <= {"event":"analysis.errors","params":{"file":"D:\\git\\fluttertest\\lib\\main\\home.dart","errors":[]}}
1523512740960 <= {"id":"915","result":{"assists":[]}}
1523512740961 <= {"id":"916","result":{}}
1523512740961 <= {"event":"analysis.highlights","params":{"file":"D:\\git\\fluttertest\\lib\\main\\home.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":39},{"type":"BUILT_IN","offset":0,"leng
1523512740961 <= {"event":"analysis.navigation","params":{"file":"D:\\git\\fluttertest\\lib\\main\\home.dart","regions":[{"offset":7,"length":31,"targets":[0]},{"offset":47,"length":8,"targets":[1]},{
1523512740962 <= {"event":"analysis.closingLabels","params":{"file":"D:\\git\\fluttertest\\lib\\main\\home.dart","labels":[{"offset":291,"length":87,"label":"Scaffold"}]}}
1523512740962 <= {"event":"analysis.outline","params":{"file":"D:\\git\\fluttertest\\lib\\main\\home.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{
1523512740963 <= {"event":"analysis.overrides","params":{"file":"D:\\git\\fluttertest\\lib\\main\\home.dart","overrides":[{"offset":140,"length":11,"superclassMember":{"element":{"kind":"METHOD","name
1523512740963 <= {"id":"918","result":{}}
1523512740963 <= {"id":"920","result":{}}
1523512741843 <= {"id":"917","result":{"id":"119"}}
1523512741843 <= {"id":"919","result":{"id":"120"}}
1523512741843 <= {"id":"921","result":{"id":"121"}}
1523512741844 <= {"event":"completion.results","params":{"id":"119","replacementOffset":373,"replacementLength":0,"results":[],"isLast":true}}
1523512741844 <= {"event":"completion.results","params":{"id":"120","replacementOffset":374,"replacementLength":0,"results":[],"isLast":true}}
1523512741844 <= {"event":"completion.results","params":{"id":"121","replacementOffset":375,"replacementLength":0,"results":[],"isLast":true}}
1523512741844 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1523512742148 => {"id":"922","method":"analysis.updateContent","params":{"files":{"D:\\git\\fluttertest\\lib\\main\\home.dart":{"type":"add","content":"import 'package:flutter/material.dart';\n\nclass
1523512742153 <= {"id":"922","result":{}}
1523512742153 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1523512742480 => {"id":"923","method":"analysis.updateContent","params":{"files":{"D:\\git\\fluttertest\\lib\\main\\home.dart":{"type":"add","content":"import 'package:flutter/material.dart';\n\nclass
1523512742486 => {"id":"924","method":"edit.getAssists","params":{"file":"D:\\git\\fluttertest\\lib\\main\\home.dart","offset":372,"length":0},"clientRequestTime":1523512742486}
1523512743153 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: D:\\git\\fluttertest\\lib\\main\\home.dart","stackTrace":"Bad state: Expected element reference for analy
```

```
Dart analysis server, SDK version 2.0.0-dev.16.0, server version 1.18.4, error: Analysis failed: D:\git\fluttertest\lib\main\home.dart
Bad state: Expected element reference for analyzer offset 295

**Comment by scheglov** [comment]
We are going to integrate CFE and Analyzer differently.
