### ISSUE TITLE
dart2js: crash inserting check for non-null jsarray

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32872]
We are hitting a crash with this exception in some programs:
```
The compiler crashed: Assertion failure: Unexpected check: [subclass=JSArray].
#0      failedAt (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:55:3)
#1      SsaCodeGenerator.generateReceiverOrArgumentTypeTest (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/codegen.dart:2944:11)
#2      SsaCodeGenerator.visitTypeConversion (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/codegen.dart:2949:28)
#3      HTypeConversion.accept (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/nodes.dart:3181:39)
#4      SsaCodeGenerator.visit (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/codegen.dart:711:10)
#5      SsaCodeGenerator.visitStatement (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/codegen.dart:723:5)
#6      SsaCodeGenerator.define (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/codegen.dart:692:7)
#7      SsaCodeGenerator.iterateBasicBlock (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1373:9)
#8      SsaCodeGenerator.enterSubGraph (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/codegen.dart:1241:7)
#9      SsaCodeGenerator.visitSubGraph (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/codegen.dart:429:5)
#10     SsaCodeGenerator.visitGraph (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/codegen.dart:420:5)
#11     SsaCodeGeneratorTask.generateMethod.<anonymous closure> (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/codegen.dart:118:15)
#12     CompilerTask.measure (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
```

This was found when generating code for `operator +` in `DelegatingList` from https://github.com/dart-lang/collection/blob/master/lib/src/wrappers.dart#L145

Turns out that we generate an HTypeConvertion for either int/num values or just to check that an array receiver is not null. See https://github.com/dart-lang/sdk/blob/92f1d0fab43fbe9e55b42b6a41082b9b899dd19a/pkg/compiler/lib/src/ssa/codegen.dart#L2918

We seem to crash because the checked type is not exactly identical to the input type, but a supertype of it. In particular, when we crash checkedType is `[subclass=JSArray]` while inputType is `[null|exact=JSUnmodifiableArray]`.

Here is a sample program that reproduces this issue:

```dart
import 'dart:collection';

dontInline(a, b) {
  return a + b;
  return a + b;
}

main() {
  new DelegatingList(null);
  dontInline(new DelegatingList(new List.unmodifiable([2])), [1]);
}

class DelegatingList<E> extends Object with ListMixin<E> implements List<E> {
  List<E> _base;
  List<E> get _listBase => _base;
  DelegatingList(this._base);

  List<E> operator +(List<E> other) => _listBase + other;

  E operator [](int index) => _base[index];
  void operator []=(int index, E value) { _base[index] = value; }
  int get length => _base.length;
  set length(int newLength) { _base.length = newLength; }
}
```

I believe we should check for whether `checkedType.nullable().containsMaks(inputType, closedWorld)` instead.

/cc @rakudrama - do you agree?

**Comment by sigmundch** [comment]
slightly simplified repro:
```dart
import 'dart:collection';

main() {
  confuse(new A(null));
  confuse(new List2());
  new A<int>(new List<int>.unmodifiable(<int>[2])).m(confuse([23]));
}

class List2<E> extends Object with ListMixin<E> implements List<E> {
  List2();
  E operator [](int index) => throw "A";
  void operator []=(int index, E value) => throw "A";
  int get length => throw "A";
  set length(int newLength) => throw "A";
}

class A<E>  {
  List<E> _list;
  A(this._list);
  List<E> m(List<E> other) {
    List<E> base = _list;
    return base + other;
    return 0;
  }
}

confuse(a) => a;
```

**Comment by sigmundch** [comment]
and this one repros without the --checked mode flag
```dart
import 'dart:collection';

main() {
  confuse(new A(null));
  confuse(new UnmodifiableListView([]));
  confuse([]);
  new A<int>(new List<int>.unmodifiable([2])).m([23]);
}

class A<E>  {
  final _list;
  A(this._list);

  List<E> m(List<E> other) {
    return (_list as List<E>) + other;
    return 0;
  }
}

confuse(a) => a;
```

**Comment by rakudrama** [comment]
Fixed via https://github.com/dart-lang/sdk/commit/7383cd46e0f951bded3ccc721c54be2d9cdce25b
