### ISSUE TITLE
Analyzer Exception - NoSuchMethodError: Class 'ParameterElementForLink_VariableSetter' has no instance getter 'isNotOptional'.

### ISSUE THREAD

**Issue by jerrywell** [dart-lang/sdk#32896]
Hi, We are Quire. This exception shown after we upgraded to newest Flutter (master branch). All syntax highlights , warning/error tips and "jump to definition" are broken. Hope you can help us for this error, otherwise we can only stay on very old Flutter version (before beta 1) and the Dart version 2.0.0-dev-31.0 or earlier... Thank you very much.

Analyzer Feedback from IntelliJ.

# Version information

- `IDEA IC-181.4445.78`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `IC-181.4445.78, JRE 1.8.0_152-release-1136-b27x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.4 unknown, screens 1440x900, 1920x1080, 1920x1080`

# Exception

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.20.0, error: Analysis failed: /Users/jerry/Documents/potix/quire/boeneo/client/lib/workspace/detail/model/task_detail.dart context: exception_20180416_104025_766
NoSuchMethodError: Class 'ParameterElementForLink_VariableSetter' has no instance getter 'isNotOptional'.
Receiver: Instance of 'ParameterElementForLink_VariableSetter'
Tried calling: isNotOptional
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ParameterElementForLink_VariableSetter.noSuchMethod (package:analyzer/src/summary/link.dart:4146)
#2      FunctionTypeImpl.relateParameters (package:analyzer/src/dart/element/type.dart:1255)
#3      FunctionTypeImpl.relate (package:analyzer/src/dart/element/type.dart:1227)
#4      StrongTypeSystemImpl._isFunctionSubtypeOf (package:analyzer/src/generated/type_system.dart:811)
#5      StrongTypeSystemImpl.isSubtypeOf (package:analyzer/src/generated/type_system.dart:959)
#6      InheritanceManager._resolveInheritanceLookup.<anonymous closure> (package:analyzer/src/dart/resolver/inheritance_manager.dart:866)
#7      _HashMap.forEach (dart:collection-patch/dart:collection/collection_patch.dart:165)
#8      InheritanceManager._resolveInheritanceLookup (package:analyzer/src/dart/resolver/inheritance_manager.dart:808)
#9      InheritanceManager._computeInterfaceLookupMap (package:analyzer/src/dart/resolver/inheritance_manager.dart:456)
#10     InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:609)
#11     InheritanceManager.lookupOverrides (package:analyzer/src/dart/resolver/inheritance_manager.dart:205)
#12     InstanceMemberInferrer._computeFieldOverrideType (package:analyzer/src/task/strong_mode.dart:113)
#13     InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:412)
#14     InstanceMemberInferrer._inferClass.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:317)
#15     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#16     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:316)
#17     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:87)
#18     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1497)
#19     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3517)
#20     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3189)
#21     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3111)
#22     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:149)
#23     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:115)
#24     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:168)
#25     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3154)
#26     Linker.link (package:analyzer/src/summary/link.dart:3748)
#27     relink (package:analyzer/src/summary/link.dart:138)
#28     link (package:analyzer/src/summary/link.dart:119)
#29     new LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:119)
#30     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#31     new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:118)
#32     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#33     new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:56)
#34     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1380)
<asynchronous suspension>
#35     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1211)
<asynchronous suspension>
#36     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#37     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1182)
<asynchronous suspension>
#38     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1008)
<asynchronous suspension>
#39     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1925)
<asynchronous suspension>
#40     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1868)
#41     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#42     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#43     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#45     _rootRun (dart:async/zone.dart:1126)
#46     _CustomZone.run (dart:async/zone.dart:1023)
#47     runZoned (dart:async/zone.dart:1501)
#48     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#49     Driver.start (package:analysis_server/src/server/driver.dart:443)
#50     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#51     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

```
1523846417956 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1523846418044 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/boeneo/analysis_options.yaml","errors":[]}}
1523846418079 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/boeneo/pubspec.yaml","errors":[]}}
1523846419381 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1523846419385 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1523846419658 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/browser/analysis_options.yaml","errors":[]}}
1523846419666 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/browser/pubspec.yaml","errors":[]}}
1523846419833 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1523846419838 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1523846419959 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/flutter/pubspec.yaml","errors":[]}}
1523846421032 <= {"id":"3"}
1523846421037 <= {"id":"4"}
1523846421051 <= {"id":"5"}
1523846421111 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1523846422128 => {"id":"6","method":"edit.listPostfixCompletionTemplates","clientRequestTime":1523846422128}
1523846423927 <= {"id":"6","result":{"templates":[{"name":"assert","key":".assert","example":"expr.assert -> assert(expr);"},{"name":"fori","key":".fori","example":"limit.fori -> for(var i = 0; i < li
1523846424451 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/util.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/Users/jerr
1523846424686 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/base.dart","errors":[]}}
1523846424704 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/preference.dart","errors":[]}}
1523846424718 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/gplus.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":
1523846424732 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/test/task_cache_test.dart","errors":[]}}
1523846424735 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/util/task_stats_util.dart","errors":[]}}
1523846424753 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/scope_cache.dart","errors":[]}}
1523846424756 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/mill.dart","errors":[]}}
1523846424779 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/user.dart","errors":[]}}
1523846424782 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/workspace/sidebar/model/my_task_tree.dart","errors":[]}}
1523846424995 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/workspace/sidebar/model/sidebar.dart","errors":[]}}
1523846425026 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/workspace/search/model/search.dart","errors":[]}}
1523846425040 <= {"event":"analysis.errors","params":{"file":"/Users/jerry/Documents/potix/quire/boeneo/client/lib/workspace/detail/model/project_stats_detail.dart","errors":[]}}
1523846425816 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/jerry/Documents/potix/quire/boeneo/client/lib/workspace/detail/model/task_detail.dart context: exc
```

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.20.0, error: Analysis failed: /Users/jerry/Documents/potix/quire/boeneo/client/lib/workspace/detail/model/task_detail.dart context: exception_20180416_104025_766
NoSuchMethodError: Class 'ParameterElementForLink_VariableSetter' has no instance getter 'isNotOptional'.
Receiver: Instance of 'ParameterElementForLink_VariableSetter'
Tried calling: isNotOptional
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ParameterElementForLink_VariableSetter.noSuchMethod (package:analyzer/src/summary/link.dart:4146)
#2      FunctionTypeImpl.relateParameters (package:analyzer/src/dart/element/type.dart:1255)
#3      FunctionTypeImpl.relate (package:analyzer/src/dart/element/type.dart:1227)
#4      StrongTypeSystemImpl._isFunctionSubtypeOf (package:analyzer/src/generated/type_system.dart:811)
#5      StrongTypeSystemImpl.isSubtypeOf (package:analyzer/src/generated/type_system.dart:959)
#6      InheritanceManager._resolveInheritanceLookup.<anonymous closure> (package:analyzer/src/dart/resolver/inheritance_manager.dart:866)
#7      _HashMap.forEach (dart:collection-patch/dart:collection/collection_patch.dart:165)
#8      InheritanceManager._resolveInheritanceLookup (package:analyzer/src/dart/resolver/inheritance_manager.dart:808)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/51243
