### ISSUE TITLE
Syntax error showing & not suggest methods

### ISSUE THREAD

**Issue by nirav4273** [dart-lang/sdk#32899]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-181.4445.78`
- `2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c`
- `IC-181.4445.78, JRE 1.8.0_152-release-1136-b27x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\NIRAVP~1\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c, server version 1.20.0, error: Analysis failed: E:\git\flutter_app_list\starter_ket_fresh\lib\main.dart
NoSuchMethodError: The getter 'lineStarts' was called on null.
Receiver: null
Tried calling: lineStarts
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:479)
#2      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:813)
#3      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:583)
#4      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:526)
#5      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:813)
#6      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:583)
#7      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:520)
#8      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:813)
#9      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:583)
#10     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:515)
#11     FileSystemSta

**Comment by GauravJain98** [comment]
Someone please solve this, its useless to use android studios without autocomplete imo

**Comment by zoechi** [comment]
@GauravJain98 you could provide concrete information that allows to reproduce the issue. 
That would make it much more likely for the issue to get solved than your comment above does ;p

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this issue.
