### ISSUE TITLE
BigInt: RangeError thrown from % operator

### ISSUE THREAD

**Issue by kibantony** [dart-lang/sdk#32898]
Dart VM version: 2.0.0-dev.43.0.flutter-52afcba357 (Fri Mar 30 20:33:12 2018 +0000) on "macos_x64"
(Running in a Flutter app on iOS)

The following code:
```
      BigInt a = BigInt.from(3051792470);
      BigInt t = BigInt.from(3051710550);
      BigInt b = a % t;
```
Generates the following exception:
```
RangeError (index): Index out of range: index should be less than 2: 2
#0      Uint32List.[]= (dart:typed_data/runtime/libtyped_data_patch.dart:2465:7)
#1      _BigIntImpl._divRem (dart:core/runtime/libbigint_patch.dart:1382:19)
#2      _BigIntImpl._rem (dart:core/runtime/libbigint_patch.dart:1306:5)
#3      _BigIntImpl.% (dart:core/runtime/libbigint_patch.dart:1697:18)
...
```

**Comment by kibantony** [comment]
Possible duplicate of issue #32739

**Comment by crelier** [comment]
Yes, this is indeed a duplicate. I verified that this does not fail with the current build.
Closing issue.
