### ISSUE TITLE
Dart 2.0 throws unhandled exception when trying make super-bounded type assigning

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#32906]
Dart SDK Version: `2.0.0-dev.48.0 `
OS: `Windows 10`

This bug is similar with #32903, but it's regarding dart (not dartanalyzer) incorrect behavior in preview-dart-2 mode.

Dart 2.0 Super Bounded Types Spec  reads:

> The feature described here, super-bounded types, consists in allowing an actual type argument to be a supertype of the declared bound, as long as a consistent replacement of `Object`, `dynamic`, and `void `by `Null `produces a traditional, well-bounded type. For example, if a class `C` takes a type argument `X` which must extend` C<X>`, `C<Object>`, `C<dynamic>`, and `C<void>` are correct super-bounded types.
> We extend covariance for generic class types such that it can be used also in cases where a type argument violates the corresponding bound.
> For instance, assuming the classes `C` and `D` as declared in the Motivation section, `C<D>` is a subtype of `C<Object>`. This is new because` C<Object>` used to be a compile-time error, which means that no questions could be asked about its properties. Note that this is a straightforward application of the usual covariance rule: `C<D> <: C<Object>` because `D <: Object`. We need this relaxation of the rules in order to be able to define which violations of the declared bounds are admissible.

This means that constructions like `C<dynamic> c0 = ...` now should be allowed in strong mode for bounded types like `class C<X extends C<X>>`.

If I run `dart -c` with the example from bug #32903: 
```
class C<X extends C<X>> {}
class D extends C<D> {}
main() { C<dynamic> c = new D(); }
```
the test does not produce any errors and passes. However, if I try `Object`  super-bounded class:
```
class C<X extends C<X>> {}
class D extends C<D> {}
main() { C<Object> c = new D(); }
```
it starts to fail with unhandled exception:
```
$> dart -c test.dart
Unhandled exception:
'file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Super-bounded-types/test.dart': malbounded type: line 1 pos 9: type parameter 'X' of class 'C' must extend bound 'C<X>', but type argument 'Object' is not a subtype of 'C<Object>' where
  Object is from dart:core
  C is from file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Super-bounded-types/test.dart
  Object is from dart:core

class C<X extends C<X>> {}
        ^
'file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Super-bounded-types/test.dart': malbounded type: line 3 pos 10: type 'C<Object>' has an out of bound type argument
main() { C<Object> c = new D(); }
         ^


#0      main (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Super-bounded-types/test.dart:3:28)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Process finished with exit code 255
```
It seems like this contradicts to the super-bounded types spec.

**Comment by kmillikin** [comment]
This needs triage.  Is it a bug in Fasta or the VM?

**Comment by stefantsov** [comment]
I can't reproduce the error.  Here's what I do:

```bash
$ git fetch origin master
$ git checkout origin/master
$ ./tools/build.py -m release -a x64 runtime_kernel
$ pkg/vm/tool/dart2 program.dart
```

I also tried to print some types out of the program and have rewritten it to the following:

```dart
class C<X extends C<X>> {
  X foo;
  C(this.foo);
}

class D extends C<D> {
  D(D d) : super(d);
}

main() {
  C<Object> c = new D(new D(null));
  print(c.runtimeType);
  print(c.foo.runtimeType);
  // print(c.foo.foo); // compile-time error
}
```

Here's the output:

```
D
D
```

And the compile-time error is produced when the commented line is uncommented.

Maybe, the issue is that the program in the message above is run with `dart -c`, not with `dart2`?
