### ISSUE TITLE
error from prefer_const_declarations in analysis server

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32915]
(not sure if this should go here or a repo for the linter? This is using v2 dev.43 SDK, not sure if it may already be fixed)

### What I was doing

Editing code in `flutter_tools` (specifically, editing a copy of the device listing code which currently has about 45 compile errors since I'm changing it to work for emulators images).

### Versions

- Dart SDK 2.0.0-dev.43.0
- Flutter SDK 0.3.1-pre.19
- Visual Studio Code 1.22.2
- Dart Code 2.12.0-dev

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/dantup/Dev/dart-sdk/dart-2.0.0-dev.43.0/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.12.0-dev
```

### Exception

Exception while using a _Visitor to visit a TopLevelVariableDeclarationImpl in CompilationUnitImpl

```text
NoSuchMethodError: The getter 'parent' was called on null.
Receiver: null
Tried calling: parent
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      getCompilationUnit (package:linter/src/ast.dart:151)
#2      hasErrorWithConstantVisitor (package:linter/src/ast.dart:314)
#3      _Visitor._visitVariableDeclarationList.<anonymous closure> (package:linter/src/rules/prefer_const_declarations.dart:79)
#4      Object&ListMixin.every (dart:collection/list.dart:119)
#5      _Visitor._visitVariableDeclarationList (package:linter/src/rules/prefer_const_declarations.dart:78)
#6      _Visitor.visitTopLevelVariableDeclaration (package:linter/src/rules/prefer_const_declarations.dart:69)
#7      TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10604)
#8      ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2757)
#9      List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#10     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2755)
#11     UnifyingAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3206)
#12     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10604)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8249)
#14     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2507)
#15     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#16     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2500)
#18     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:371)
#19     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:163)
#20     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#21     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#23     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:161)
#24     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#25     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:220)
<asynchronous suspension>
#26     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97)
<asynchronous suspension>
#27     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1216)
<asynchronous suspension>
#28     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#29     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1181)
<asynchronous suspension>
#30     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:986)
<asynchronous suspension>
#31     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1896)
<asynchronous suspension>
#32     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1839)
#33     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#34     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#35     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#36     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#37     _rootRun (dart:async/zone.dart:1126)
#38     _CustomZone.run (dart:async/zone.dart:1023)
#39     runZoned (dart:async/zone.dart:1501)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#41     Driver.start (package:analysis_server/src/server/driver.dart:443)
#42     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_path",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools",
        "explicitFileCount": 204,
        "implicitFileCount": 1432,
        "workItemQueueLength": 208,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/asset_test/font",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/changed_sdk_location",
        "explicitFileCount": 1,
        "implicitFileCount": 93,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_package",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_import",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/asset_test/main",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/syntax_error",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/good",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/asci_casing",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by pq** [comment]
This one was fixed w/  #32745. 🏁
