### ISSUE TITLE
"The getter 'parent' was called on null" in analysis server edit.getFixes 

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32926]
### What I was doing

Working in `flutter_tools` I got this after writing some code (`const emulatorPortRegex = new RegExp(r'emulator-(\d+)');`) and then using a fix to add a type annotation.

### Versions

- Dart SDK 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
- Flutter SDK 0.3.1-pre.46
- Visual Studio Code 1.22.2
- Dart Code 2.12.0-dev

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.12.0-dev
```

### Exception (fatal)

Failed to handle request: {id: 5387, method: edit.getFixes, params: {file: /Users/dantup/Dev/Google/flutter/packages/flutter_tools/lib/src/android/android_device.dart, offset: 4230}}

```text
NoSuchMethodError: The getter 'parent' was called on null.
Receiver: null
Tried calling: parent
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FixProcessor._addFix_removeThisExpression (package:analysis_server/src/services/correction/fix_internal.dart:2396)
<asynchronous suspension>
#2      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:492)
<asynchronous suspension>
#3      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:86)
<asynchronous suspension>
#4      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:534)
<asynchronous suspension>
#5      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:233)
<asynchronous suspension>
#6      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:337)
#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:722)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#9      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:718)
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     runZoned (dart:async/zone.dart:1490)
#13     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:717)
#14     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#16     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#17     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#18     _rootRunUnary (dart:async/zone.dart:1134)
#19     _CustomZone.runUnary (dart:async/zone.dart:1031)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#26     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#27     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#28     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#30     _rootRunUnary (dart:async/zone.dart:1134)
#31     _CustomZone.runUnary (dart:async/zone.dart:1031)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#35     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#36     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#37     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#38     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#39     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#40     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#41     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#43     _rootRunUnary (dart:async/zone.dart:1134)
#44     _CustomZone.runUnary (dart:async/zone.dart:1031)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#48     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#49     _StreamController._add (dart:async/stream_controller.dart:639)
#50     _StreamController.add (dart:async/stream_controller.dart:585)
#51     _Socket._onData (dart:io-patch/socket_patch.dart:1674)
#52     _rootRunUnary (dart:async/zone.dart:1138)
#53     _CustomZone.runUnary (dart:async/zone.dart:1031)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#57     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#58     _StreamController._add (dart:async/stream_controller.dart:639)
#59     _StreamController.add (dart:async/stream_controller.dart:585)
#60     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#61     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#64     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_path",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools",
        "explicitFileCount": 202,
        "implicitFileCount": 1433,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/asset_test/font",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/changed_sdk_location",
        "explicitFileCount": 1,
        "implicitFileCount": 93,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_package",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_import",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/asset_test/main",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/syntax_error",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/good",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/asci_casing",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment]
Looking at the "remove this" note in the stack trace, maybe it was actually related to this code (I typed `this.` to see a list of the fields:

```dart
    try {
      final this.id // <--may have been this that caused it
      final AndroidConsole console = await AndroidConsole.connect('localhost', );
      final String avdName = await console.getAvdName();
      console.destroy();
      return avdName;
    }
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/51940
