### ISSUE TITLE
Analysis Server crash - -dev.49

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32934]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.4203.550`
- `2.0.0-dev.49.0`
- `IU-181.4203.550, JRE 1.8.0_152-release-1136-b20x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1920x1200  Retina`

# Exception

```
Dart analysis server, SDK version 2.0.0-dev.49.0, server version 1.20.1, error: Analysis failed: /Users/kevmoo/source/github/json_serializable/json/test/writer_test.dart
type 'ClassElementImpl' is not a subtype of type 'ExecutableElement' in type cast where
  ClassElementImpl is from package:analyzer/src/dart/element/element.dart
  ExecutableElement is from package:analyzer/dart/element/element.dart

#0      Object._as (dart:core-patch/dart:core/object_patch.dart:67)
#1      ExecutableElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:514)
#2      FunctionElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:636)
#3      ExecutableElementHandle.parameters (package:analyzer/src/dart/element/handle.dart:541)
#4      FunctionTypeImpl.baseParameters (package:analyzer/src/dart/element/type.dart:494)
#5      FunctionTypeImpl.parameters (package:analyzer/src/dart/element/type.dart:647)
#6      StrongTypeSystemImpl._substituteForUnknownType (package:analyzer/src/generated/type_system.dart:957)
#7      StrongTypeSystemImpl.upperBoundForType (package:analyzer/src/generated/type_system.dart:617)
#8      StaticTypeAnalyzer.inferFormalParameterList.inferType (package:analyzer/src/generated/static_type_analyzer.dart:134)
#9      StaticTypeAnalyzer.inferFormalParameterList (package:analyzer/src/generated/static_type_analyzer.dart:152)
#10     ResolverVisitor._inferFormalParameterList (package:analyzer/src/generated/resolver.dart:6725)
#11     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5989)
#12     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5434)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#14     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:432)
#15     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#16     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898)
#17     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:5369)
#18     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:428)
#19     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6214)
#20     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871)
#21     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4325)
#22     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#23     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3005)
#24     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4321)
#25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#26     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1353)
#27     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#28     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#29     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7259)
#30     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1349)
#31     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1298)
#32     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#33     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#34     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7271)
#35     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5494)
#36     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1294)
#37     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5440)
#38     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#39     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#40     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7599)
#41     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5994)
#42     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5434)
#43     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#44     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:432)
#45     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#46     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898)
#47     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:5369)
#48     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:428)
#49     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6214)
#50     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871)
#51     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4325)
#52     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#53     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3005)
#54     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4321)
#55     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#56     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1353)
#57     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#58     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#59     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7259)
#60     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:7759)
#61     ResolverVisitor.visitForEachStatementInScope (package:analyzer/src/generated/resolver.dart:5912)
#62     ScopedVisitor.visitForEachStatement (package:analyzer/src/generated/resolver.dart:7469)
#63     ResolverVisitor.visitForEachStatement (package:analyzer/src/generated/resolver.dart:5842)
#64     ForEachStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4766)
#65     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#66     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1353)
#67     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#68     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#69     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7259)
#70     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1349)
#71     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1298)
#72     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#73     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#74     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7271)
#75     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5494)
#76     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1294)
#77     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5440)
#78     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#79     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#80     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7599)
#81     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5994)
#82     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5434)
#83     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#84     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:432)
#85     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#86     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898)
#87     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:5369)
#88     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:428)
#89     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6214)
#90     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871)
#91     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4325)
#92     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#93     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3005)
#94     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4321)
#95     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#96     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1353)
#97     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#98     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#99     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7259)
#100    ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:7759)
#101    ResolverVisitor.visitForEachStatementInScope (package:analyzer/src/generated/resolver.dart:5912)
#102    ScopedVisitor.visitForEachStatement (package:analyzer/src/generated/resolver.dart:7469)
#103    ResolverVisitor.visitForEachStatement (package:analyzer/src/generated/resolver.dart:5842)
#104    ForEachStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4766)
#105    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#106    BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1353)
#107    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#108    UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#109    ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7259)
#110    BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1349)
#111    BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1298)
#112    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#113    UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#114    ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7271)
#115    ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5494)
#116    BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1294)
#117    FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5440)
#118    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#119    UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#120    ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7574)
#121    ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5994)
#122    FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5434)
#123    FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5284)
#124    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6227)
#125    UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026)
#126    ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:7567)
#127    ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5970)
#128    ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7559)
#129    ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5960)
#130    FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5277)
#131    ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5599)
#132    CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2504)
#133    LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:696)
#134    LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:127)
#135    _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#136    LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:126)
#137    LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#138    _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:220)
<asynchronous suspension>
#139    LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:97)
<asynchronous suspension>
#140    AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1223)
<asynchronous suspension>
#141    PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#142    AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1182)
<asynchronous suspension>
#143    AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1008)
<asynchronous suspension>
#144    AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1925)
<asynchronous suspension>
#145    AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1868)
#146    new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#147    SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#148    StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#149    Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#150    _rootRun (dart:async/zone.dart:1126)
#151    _CustomZone.run (dart:async/zone.dart:1023)
#152    runZoned (dart:async/zone.dart:1501)
#153    Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#154    Driver.start (package:analysis_server/src/server/driver.dart:443)
#155    main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#156    _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#157    _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

```
1524203708136 <= {"id":"2726","result":{}}
1524203708136 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1524203708138 => {"id":"2727","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/new_values.dart","offset":1308,"length":0},"clientRequestTime":152420
1524203708222 <= {"id":"2727","result":{"assists":[]}}
1524203708224 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1524203708329 => {"id":"2728","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/json_serializable/json/test/new_values.dart":{"type":"add","content":"class Fun {\n  fin
1524203708329 => {"id":"2729","method":"completion.getSuggestions","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/new_values.dart","offset":1309},"clientRequestTime":1524203
1524203708329 <= {"id":"2728","result":{}}
1524203708329 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1524203708372 <= {"id":"2729","result":{"id":"162"}}
1524203708372 <= {"event":"completion.results","params":{"id":"162","replacementOffset":1309,"replacementLength":0,"results":[],"isLast":true}}
1524203708391 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/writer_test.dart","errors":[]}}
1524203708418 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","loc
1524203708421 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1524203708608 => {"id":"2730","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/json_serializable/json/test/new_values.dart":{"type":"add","content":"class Fun {\n  fin
1524203708608 => {"id":"2731","method":"completion.getSuggestions","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/new_values.dart","offset":1310},"clientRequestTime":1524203
1524203708609 <= {"id":"2730","result":{}}
1524203708609 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1524203708627 <= {"id":"2731","result":{"id":"163"}}
1524203708627 <= {"event":"completion.results","params":{"id":"163","replacementOffset":1310,"replacementLength":0,"results":[],"isLast":true}}
1524203708646 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/writer_test.dart","errors":[]}}
1524203708668 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","loc
1524203708671 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1524203708721 => {"id":"2732","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/json_serializable/json/test/new_values.dart":{"type":"add","content":"class Fun {\n  fin
1524203708721 => {"id":"2733","method":"completion.getSuggestions","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/new_values.dart","offset":1311},"clientRequestTime":1524203
1524203708722 <= {"id":"2732","result":{}}
1524203708722 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1524203708737 <= {"id":"2733","result":{"id":"164"}}
1524203708737 <= {"event":"completion.results","params":{"id":"164","replacementOffset":1311,"replacementLength":0,"results":[],"isLast":true}}
1524203708771 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/kevmoo/source/github/json_serializable/json/test/writer_test.dart","stackTrace":"type 'ClassElemen
```

**Comment by scheglov** [comment]
I suspect that this happens when there are two conflicting declarations with the same name.
Given that we will replace analysis with CFE, this is not something we probably will fix.
