### ISSUE TITLE
AnalysisServer crash - dev.49

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32935]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.4203.550`
- `2.0.0-dev.49.0`
- `IU-181.4203.550, JRE 1.8.0_152-release-1136-b20x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1920x1200  Retina`

# Exception

```
Dart analysis server, SDK version 2.0.0-dev.49.0, server version 1.20.1, FATAL error: Failed to handle request: {id: 8350, method: edit.getFixes, params: {file: /Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart, offset: 625}, clientRequestTime: 1524206362365}
NoSuchMethodError: The getter 'keyword' was called on null.
Receiver: null
Tried calling: keyword
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FixProcessor._addFix_makeVariableFinal.<anonymous closure> (package:analysis_server/src/services/correction/fix_internal.dart:2200)
#2      DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:47)
#3      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:67)
<asynchronous suspension>
#4      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:47)
#5      FixProcessor._addFix_makeVariableFinal (package:analysis_server/src/services/correction/fix_internal.dart:2199)
<asynchronous suspension>
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:471)
<asynchronous suspension>
#7      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:86)
<asynchronous suspension>
#8      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:534)
<asynchronous suspension>
#9      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:233)
<asynchronous suspension>
#10     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:337)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:722)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:718)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1490)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:717)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#22     _rootRunUnary (dart:async/zone.dart:1134)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#34     _rootRunUnary (dart:async/zone.dart:1134)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#47     _rootRunUnary (dart:async/zone.dart:1134)
#48     _CustomZone.runUnary (dart:async/zone.dart:1031)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#53     _StreamController._add (dart:async/stream_controller.dart:639)
#54     _StreamController.add (dart:async/stream_controller.dart:585)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1674)
#56     _rootRunUnary (dart:async/zone.dart:1138)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#62     _StreamController._add (dart:async/stream_controller.dart:639)
#63     _StreamController.add (dart:async/stream_controller.dart:585)
#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#68     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

```
1524206360676 <= {"id":"8345","result":{}}
1524206360676 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1524206360687 => {"id":"8346","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","offset":586,"length":0},"clientRequestTime":1524
1524206360712 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","loc
1524206360713 <= {"id":"8346","result":{"assists":[{"message":"Convert to async function body","edits":[{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","fileStamp"
1524206360715 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":29},{"t
1524206360715 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","regions":[{"offset":7,"length":14,"targets":[0]},{"offset
1524206360716 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","labels":[]}}
1524206360716 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UN
1524206360717 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","overrides":[{"offset":570,"length":11,"superclassMember":{
1524206360719 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1524206360720 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","classes":[],"members":[]}}
1524206361407 => {"id":"8347","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart":{"type":"add","content":"import 'dart:co
1524206361410 <= {"id":"8347","result":{}}
1524206361410 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1524206361413 => {"id":"8348","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","offset":587,"length":0},"clientRequestTime":1524
1524206361441 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","locati
1524206361441 <= {"id":"8348","result":{"assists":[{"message":"Convert to block body","edits":[{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","fileStamp":0,"edits
1524206361442 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":29},{"t
1524206361444 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","regions":[{"offset":7,"length":14,"targets":[0]},{"offset
1524206361444 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","labels":[]}}
1524206361445 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UN
1524206361445 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","overrides":[{"offset":570,"length":11,"superclassMember":{
1524206361447 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1524206361447 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","classes":[],"members":[]}}
1524206361754 => {"id":"8349","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","offset":587,"length":65},"clientRequestTime":152
1524206361756 <= {"id":"8349","result":{"assists":[]}}
1524206362365 => {"id":"8350","method":"edit.getFixes","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","offset":625},"clientRequestTime":1524206362365}
1524206362376 => {"id":"8351","method":"edit.getFixes","params":{"file":"/Users/kevmoo/source/github/json_serializable/json/test/listener_test.dart","offset":646},"clientRequestTime":1524206362376}
1524206362377 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 8350, method: edit.getFixes, params: {file: /Users/kevmoo/source/github/json_serializable/js
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/53840
