### ISSUE TITLE
Analyzer crashing externally on angular repo

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/sdk#32965]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4301.25`
- `2.0.0-dev.49.0`
- `IC-173.4301.25, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/ls/1jj80hm96sb7j_wjh2tb2bnm005b3f/T/report1.txt

```
Dart analysis server, SDK version 2.0.0-dev.49.0, server version 1.20.1, error: Analysis failed: /Users/alorenzen/angular/angular_ast/test/ast_cli_tester.dart
Invalid argument(s): lineStarts must be non-empty
#0      new LineInfo (package:analyzer/source/line_info.dart:47)
#1      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:451)
#2      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#3      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#4      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#5      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#6      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#7      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#8      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#9      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#10     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#11     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#12     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#13     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#14     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#15     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#16     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#17     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#18     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#19     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#20     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#21     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#22     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#23     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#24     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#25     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#26     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#27     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#28     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#29     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#30     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#31     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#32     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#33     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#34     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#35     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#36     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#37     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#38     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#39     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#40     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#41     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#42     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#43     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#44     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#45     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#46     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#47     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#48     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#49     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#50     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#51     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#52     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#53     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#54     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#55     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#56     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#57     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#58     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#59     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#60     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#61     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#62     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#63     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#64     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#65     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#66     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#67     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#68     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#69     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#70     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#71     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#72     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#73     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#74     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#75     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#76     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:498)
#77     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#78     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#79     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#80     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#81     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#82     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:498)
#83     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#84     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#85     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#86     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#87     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#88     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#89     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:823)
#90     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1147)
<asynchronous suspension>
#91     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1008)
<asynchronous suspension>
#92     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1925)
<asynchronous suspension>
#93     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1868)
#94     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#95     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#96     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#97     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#98     _rootRun (dart:async/zone.dart:1126)
#99     _CustomZone.run (dart:async/zone.dart:1023)
#100    runZoned (dart:async/zone.dart:1501)
#101    Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#102    Driver.start (package:analysis_server/src/server/driver.dart:443)
#103    main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#104    _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#105    _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

```
1524610746388 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/analysis_options.yaml","errors":[]}}
1524610746389 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1524610746390 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1524610746422 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/analysis_options.yaml","errors":[]}}
1524610746423 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/examples/hacker_news_pwa/pubspec.yaml","errors":[]}}
1524610746426 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1524610746428 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1524610746456 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/examples/registration_form/analysis_options.yaml","errors":[]}}
1524610746457 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/examples/registration_form/pubspec.yaml","errors":[]}}
1524610746459 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1524610746459 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1524610746473 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/analysis_options.yaml","errors":[]}}
1524610746475 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/dev/pubspec.yaml","errors":[]}}
1524610746476 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1524610746476 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1524610746482 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/analysis_options.yaml","errors":[]}}
1524610746485 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1524610746486 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1524610746506 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/analysis_options.yaml","errors":[]}}
1524610746508 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/pubspec.yaml","errors":[]}}
1524610746514 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1524610746515 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1524610746537 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/analysis_options.yaml","errors":[]}}
1524610746538 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_router/pubspec.yaml","errors":[]}}
1524610746538 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1524610746539 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1524610746569 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/analysis_options.yaml","errors":[]}}
1524610747373 <= {"id":"3"}
1524610747383 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1524610747843 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/alorenzen/angular/angular_ast/test/ast_cli_tester.dart","stackTrace":"Invalid argument(s): lineSta
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by alorenzen** [comment]
Getting the same error, but on a different file.

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4301.25`
- `2.0.0-dev.50.0`
- `IC-173.4301.25, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 2560x1600`

# Exception

Please append the contents of:
file:///private/var/folders/ls/1jj80hm96sb7j_wjh2tb2bnm005b3f/T/report2.txt

```
Dart analysis server, SDK version 2.0.0-dev.50.0, server version 1.20.1, error: Analysis failed: /Users/alorenzen/angular/angular_forms/test/directives_test.dart
Invalid argument(s): lineStarts must be non-empty
#0      new LineInfo (package:analyzer/source/line_info.dart:47)
#1      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:451)
#2      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#3      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#4      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#5      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#6      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#7      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#8      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#9      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#10     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#11     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#12     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#13     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#14     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#15     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#16     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:498)
#17     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#18     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#19     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#20     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#21     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#22     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#23     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#24     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#25     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#26     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#27     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#28     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#29     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#30     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#31     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:498)
#32     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#33     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#34     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#35     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#36     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#37     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:498)
#38     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#39     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:625)
#40     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:493)
#41     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:823)
#42     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1147)
<asynchronous suspension>
#43     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1008)
<asynchronous suspension>
#44     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1925)
<asynchronous suspension>
#45     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1868)
#46     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#47     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#48     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#49     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#50     _rootRun (dart:async/zone.dart:1126)
#51     _CustomZone.run (dart:async/zone.dart:1023)
#52     runZoned (dart:async/zone.dart:1501)
#53     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#54     Driver.start (package:analysis_server/src/server/driver.dart:443)
#55     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#56     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

```
1524781272173 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/examples/registration_form/lib/address/address_component.dart","errors":[]}}
1524781272174 <= {"id":"1716","result":{}}
1524781272229 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/alorenzen
1524781272232 <= {"event":"analysis.highlights","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN","
1524781272239 <= {"event":"analysis.navigation","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":29,"length":24,
1524781272239 <= {"event":"analysis.closingLabels","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","labels":[]}}
1524781272241 <= {"event":"analysis.outline","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit
1524781272241 <= {"event":"analysis.overrides","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","overrides":[{"offset":11564,"length":8,"superclassMember":{"element":{"kind
1524781272263 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/examples/registration_form/lib/root/root_component.dart","errors":[{"severity":"INFO","type":"TODO","location":{"
1524781272283 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/test/directives_test.dart","errors":[]}}
1524781272302 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/test/validators_test.dart","errors":[]}}
1524781272315 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/test/form_builder_test.dart","errors":[]}}
1524781272325 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/angular_forms.dart","errors":[]}}
1524781272334 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/directives/normalize_validator.dart","errors":[]}}
1524781272345 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/directives/ng_control_status.dart","errors":[]}}
1524781272361 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/directives/radio_control_value_accessor.dart","errors":[]}}
1524781272374 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/directives/default_value_accessor.dart","errors":[]}}
1524781272381 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/directives.dart","errors":[]}}
1524781272383 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1524781272387 <= {"event":"analysis.implemented","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","classes":[{"offset":487,"length":15}],"members":[{"offset":9185,"length":
1524781404881 => {"id":"1717","method":"edit.getAssists","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","offset":9245,"length":0},"clientRequestTime":1524781404881}
1524781404883 <= {"id":"1717","result":{"assists":[{"message":"Convert to async function body","edits":[{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","fileStamp":0,"edits":[{"off
1524781416932 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1524781417083 <= {"event":"analysis.errors","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/alorenzen
1524781417085 <= {"event":"analysis.highlights","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN","
1524781417090 <= {"event":"analysis.navigation","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":29,"length":24,
1524781417091 <= {"event":"analysis.closingLabels","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","labels":[]}}
1524781417092 <= {"event":"analysis.outline","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit
1524781417093 <= {"event":"analysis.overrides","params":{"file":"/Users/alorenzen/angular/angular_forms/lib/src/model.dart","overrides":[{"offset":11564,"length":8,"superclassMember":{"element":{"kind
1524781417192 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/alorenzen/angular/angular_forms/test/directives_test.dart","stackTrace":"Invalid argument(s): line
```

**Comment by alorenzen** [comment]
In debugging a bit, this seems to be related to having some `.dart_tool` subdirectories that weren't marked as excluded. 
To reproduce, I created a new IntelliJ project with the existing sources. Everything seemed to be fine for a while.
Then, I kicked off a `pub run build_runner build` for one of the angular packages. Suddenly, I was getting an error in the `Event Log` every time I restarted the analysis server.
When I found and marked *all* `.dart_tool` subdirectories as excluded, I no longer get the error.

**Comment by bwilkerson** [comment]
Good to know, thanks!

I would have expected server to have ignored hidden files and directories unless the content of those directories is being referenced from elsewhere.

Nevertheless, server should only be analyzing `.dart` files in the `.dart_tool` directories, and shouldn't crash no matter what the content of the `.dart` files might be, so there's still a problem here.

@scheglov

**Comment by scheglov** [comment]
I'm not able to reproduce this :-(

I checked out angular, opened it in IntelliJ, ran `pub get` in every packages.
Then I ran `pub run build_runner build` in every package.
No exceptions.

I don't have Angular plugin installed, unless it is installed automatically as a part of opening Angular repo in IntelliJ.

I looked at the code, but was not able to find a code part that would cause us to use empty lines starts array. We get lines starts from `UnlinkedUnit`, which is serialized from a freshly parsed `CompilationUnit` in `file_state.dart:431`. And `parse()` does set `CompilationUnit.lineInfo`.

**Comment by alorenzen** [comment]
Is there any information I can do that will help you investigate this?

I got another crash today when opening the project:

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4301.25`
- `2.0.0-dev.50.0`
- `IC-173.4301.25, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 2560x1600`

# Exception

Please append the contents of:
file:///private/var/folders/ls/1jj80hm96sb7j_wjh2tb2bnm005b3f/T/report.txt

```
Dart analysis server, SDK version 2.0.0-dev.50.0, server version 1.20.1, error: Analysis failed: /Users/alorenzen/angular/angular_ast/test/lexer_test.dart
RangeError (byteOffset): Invalid value: Not in range 0..7424, inclusive: 31688
#0      _ByteDataView.getUint32 (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:4278)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:68)
#2      BufferContext.derefObject (package:front_end/src/base/flat_buffers.dart:54)
#3      StringReader.read (package:front_end/src/base/flat_buffers.dart:658)
#4      Reader.vTableGet (package:front_end/src/base/flat_buffers.dart:640)
#5      _AnalysisDriverUnitErrorImpl.uniqueName (package:analyzer/src/summary/format.dart:1009)
#6      AnalysisDriver._getErrorsFromSerialized (package:analyzer/src/dart/analysis/driver.dart:1452)
#7      AnalysisDriver._getAnalysisResultFromBytes (package:analyzer/src/dart/analysis/driver.dart:1429)
#8      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1177)
<asynchronous suspension>
#9      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1008)
<asynchronous suspension>
#10     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1925)
<asynchronous suspension>
#11     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1868)
#12     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)

**Comment by scheglov** [comment]
Please archive your `/Users/scheglov/.dartServer/.analysis-driver` folder and share it with my corp account.

**Comment by bwilkerson** [comment]
@scheglov Did we get the data we need, or should we close this as stale?
