### ISSUE TITLE
Dart Analysis Server Issue

### ISSUE THREAD

**Issue by Harsh18894** [dart-lang/sdk#32973]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4720617`
- `2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c`
- `AI-173.4720617, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\HARSHD~1\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c, server version 1.20.0, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\Harsh Deep Singh\Downloads\trainings_trail_one], excluded: [C:\Users\Harsh Deep Singh\Downloads\trainings_trail_one\.idea, C:\Users\Harsh Deep Singh\Downloads\trainings_trail_one\.idea, C:\Users\Harsh Deep Singh\Downloads\trainings_trail_one\.pub, C:\Users\Harsh Deep Singh\Downloads\trainings_trail_one\build]}, clientRequestTime: 1524630816899}
FileSystemException: Exists failed, path = 'C:\Users\Harsh Deep Singh\Downloads\trainings_trail_one\lib\ui\Dashboard.dart___jb_old___' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:73)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:323)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166)
#3      _HashVMBase

**Comment by bwilkerson** [comment]
I'm guessing that this issue is stale. Please let us know if you're still seeing problems.
