### ISSUE TITLE
Dartanalyzer totally lost in context.

### ISSUE THREAD

**Issue by ohir** [dart-lang/sdk#32995]
Given PoB source:
```dart
typedef void FunA();
class AnalyzerBug {
  final Set<FunA> s = new Set<FunA>(); // line 3
  final Map<Object, Set<FunA>> o = Map<Object, Set<FunA>>{}; // here is bad '= Map ...{}'
}
```
dartanalyzer totally lost context:
```log
% dartanalyzer pob.dart 
Analyzing pob.dart...
  error • Set isn't a type at pob.dart:3:9 • not_a_type
  error • The name 'Set' isn't a class at pob.dart:3:27 • new_with_non_type
  error • The name 'Set' isn't a type so it can't be used as a type argument at pob.dart:4:21 • non_type_as_type_argument
  error • The operator '<' isn't defined for the class 'Type' at pob.dart:4:39 • undefined_operator
  error • Expected to find ';' at pob.dart:4:48 • expected_token
  error • Expected a class member at pob.dart:4:51 • expected_class_member
  error • Unexpected text '<' at pob.dart:4:51 • unexpected_token
  error • Expected a class member at pob.dart:4:56 • expected_class_member
  error • Unexpected text '>>' at pob.dart:4:56 • unexpected_token
  error • Expected a class member at pob.dart:4:58 • expected_class_member
  error • Unexpected text '{' at pob.dart:4:58 • unexpected_token
  error • Unexpected text ';' at pob.dart:4:60 • unexpected_token
  error • Expected a method, getter, setter or operator declaration at pob.dart:5:1 • expected_executable
  error • Unexpected text '}' at pob.dart:5:1 • unexpected_token
  warning • The final variable 'Set' must be initialized at pob.dart:4:48 • final_not_initialized
```

```
dartanalyzer version 2.0.0-edge.af1436931b93e755d38223c487d33a0a1f5eadf5
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b
Dart VM version: 2.0.0-dev.48.0.flutter-fe606f890b (Mon Apr 16 21:21:13 2018 +0000)
on "linux_x64"
```

**Comment by bwilkerson** [comment]
@danrubel Does the Fasta parser do better?

**Comment by srawlins** [comment]
The example at the top now leads to a crash:

```none
Crash when compiling file:///Users/srawlins/code/dart-csslib/32995.dart,
at character offset null:
type 'ParserRecovery' is not a subtype of type 'TypeBuilder'
#0      OutlineBuilder.endClassMethod (package:front_end/src/fasta/source/outline_builder.dart:1061:17)
#1      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3490:20)
#2      Parser.parseInvalidOperatorDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6569:19)
#3      Parser.recoverFromInvalidMember (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6612:14)
#4      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3206:16)
#5      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2984:15)
#6      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#7      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1779:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:574:14)
#9      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:470:14)
#10     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:335:37)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:260:13)
#13     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#15     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:288:12)
#16     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:108:28)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#18     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#19     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#20     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#21     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#24     _rootRun (dart:async/zone.dart:1126:13)
#25     _CustomZone.run (dart:async/zone.dart:1023:19)
#26     _runZoned (dart:async/zone.dart:1518:10)
#27     runZoned (dart:async/zone.dart:1465:12)
#28     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#29     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#30     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#31     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#32     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:359:17)
#33     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:163:45)
#34     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#35     _rootRun (dart:async/zone.dart:1122:38)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#39     _rootRun (dart:async/zone.dart:1126:13)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#42     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#43     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#44     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


#0      OutlineBuilder.endClassMethod (package:front_end/src/fasta/source/outline_builder.dart:1061:17)
#1      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3490:20)
#2      Parser.parseInvalidOperatorDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6569:19)
#3      Parser.recoverFromInvalidMember (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6612:14)
#4      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3206:16)
#5      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2984:15)
#6      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#7      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1779:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:574:14)
#9      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:470:14)
#10     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:335:37)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:260:13)
#13     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#15     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:288:12)
#16     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:108:28)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#18     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#19     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#20     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#21     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#24     _rootRun (dart:async/zone.dart:1126:13)
#25     _CustomZone.run (dart:async/zone.dart:1023:19)
#26     _runZoned (dart:async/zone.dart:1518:10)
#27     runZoned (dart:async/zone.dart:1465:12)
#28     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#29     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#30     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#31     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#32     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:359:17)
#33     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:163:45)
#34     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#35     _rootRun (dart:async/zone.dart:1122:38)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#39     _rootRun (dart:async/zone.dart:1126:13)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#42     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#43     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#44     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by jensjoha** [comment]
Now you'll get a single error message, something like
```
error • t.dart:4:36 • The name of the class 'Map' can't be included in a map literal. Try removing 'Map' • literal_with_class
```

This was done in 31acdc9d92c93742999c8fb92f2c4c051bd1fafe and ac9b4aab8d5ebb598907c8d07a742756dce5a2ff.
