### ISSUE TITLE
dart2js crashes with unexpected ~

### ISSUE THREAD

**Issue by butlermatt** [dart-lang/sdk#33001]
Hey folks,

I was playing around with dartpad looking at some of the language nuances and out of curiosity I wanted to see how dart handled an incomplete, 2 character token (eg ~/). So I ran the following in dartpad and it came up with the crash error listed below.

First and foremost my system info:
Windows 10 64bit
Chrome 66.0

```dart
void main() {
    print(5 ~ 2);
}
```
Here I intentionally left off the `/` from the truncating division and this was the result.

```
Error compiling to JavaScript:
main.dart:2:13:
Warning: Additional argument.
  print(5 ~ 2);
            ^
/usr/lib/dart/lib/core/int.dart:85:3:
Info: This is the method declaration.
  int operator ~();
  ^^^^^^^^^^^^^^^^
main.dart:2:9:
Internal Error: Unhandled node: 5~2
  print(5 ~ 2);
        ^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (1.24.2), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Internal Error: Unhandled node: 5~2
#0      CompilerDiagnosticReporter.internalError (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:1186)
#1      SsaBuilder.internalError (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:3852)
#2      SsaBuilder.visitNode (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:299)
#3      SsaBuilder.errorUndefinedBinaryExpression (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:6506)
#4      InvalidBinaryStructure.dispatch (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/resolution/send_structure.dart:765)
#5      Visitor&BaseImplementationOfCompoundsMixin&BaseImplementationOfSetIfNullsMixin&BaseImplementationOfSuperIndexSetIfNullMixin&SemanticSendResolvedMixin.visitSend (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/resolution/semantic_visitor.dart:52)
#6      Send.accept (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/tree/nodes.dart:639)
#7      SsaBuilder.visit (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:1587)
#8      SsaBuilder.makeStaticArgumentList.compileArgument (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:2557)
#9      Elements.makeArgumentsList.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/elements/elements.dart:834)
#10     List.forEach (dart:core-patch/array.dart:73)
#11     FunctionSignatureCommon.forEachRequiredParameter (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/elements/common.dart:511)
#12     Elements.makeArgumentsList (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/elements/elements.dart:833)
#13     SsaBuilder.makeStaticArgumentList (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:2561)
#14     SsaBuilder.generateStaticFunctionInvoke (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:3617)
#15     SsaBuilder.visitTopLevelFunctionInvoke (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:3677)
#16     InvokeStructure.dispatch (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/resolution/send_structure.dart:236)
#17     Visitor&BaseImplementationOfCompoundsMixin&BaseImplementationOfSetIfNullsMixin&BaseImplementationOfSuperIndexSetIfNullMixin&SemanticSendResolvedMixin.visitSend (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/resolution/semantic_visitor.dart:52)
#18     Send.accept (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/tree/nodes.dart:639)
#19     SsaBuilder.visit (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:1587)
#20     SsaBuilder.visitExpressionStatement (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:1672)
#21     ExpressionStatement.accept (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/tree/nodes.dart:1618)
#22     SsaBuilder.visit (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:1587)
#23     SsaBuilder.visitBlock (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:1633)
#24     Block.accept (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/tree/nodes.dart:903)
#25     SsaBuilder.buildMethod (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:787)
#26     SsaBuilder.build (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:340)
#27     SsaAstBuilderTask.build.<anonymous closure>.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:139)
#28     CompilerDiagnosticReporter.withCurrentElement (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:1098)
#29     SsaAstBuilderTask.build.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:130)
#30     CompilerTask.measure (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/common/tasks.dart:63)
#31     SsaAstBuilderTask.build (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/builder.dart:124)
#32     SsaFunctionCompiler.compile (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/ssa/ssa.dart:37)
#33     JavaScriptBackend.codegen (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/js_backend/backend.dart:932)
#34     ElementCodegenWorkItem.run (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/js_backend/element_strategy.dart:125)
#35     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:737)
#36     CompilerTask.measureSubtask (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/common/tasks.dart:176)
#37     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:737)
#38     CompilerTask.measureSubtask (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/common/tasks.dart:176)
#39     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:735)
#40     CompilerDiagnosticReporter.withCurrentElement (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:1098)
#41     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:733)
#42     EnqueuerStrategy.processWorkItem (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/enqueue.dart:507)
#43     CodegenEnqueuer.forEach (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/js_backend/enqueuer.dart:227)
#44     Compiler.emptyQueue.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:729)
#45     CompilerTask.measureSubtask (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/common/tasks.dart:176)
#46     Compiler.emptyQueue (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:728)
#47     Compiler.processQueue.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:752)
#48     CompilerTask.measureSubtask (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/common/tasks.dart:176)
#49     Compiler.processQueue (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:747)
#50     Compiler.compileLoadedLibraries.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:621)
#51     CompilerTask.measureSubtask (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/common/tasks.dart:176)
#52     Compiler.compileLoadedLibraries (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:518)
#53     Compiler.runInternal (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:473)
<asynchronous suspension>
#54     Compiler.run.<anonymous closure>.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:308)
#55     new Future.sync (dart:async/future.dart:206)
#56     Compiler.run.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:308)
#57     CompilerTask.measureSubtask (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/common/tasks.dart:176)
#58     Compiler.run (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/compiler.dart:305)
#59     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///tmp/tmp5a0ua3/dart-1.24.2/dart/pkg/compiler/lib/src/apiimpl.dart:263)
#60     _RootZone.runUnary (dart:async/zone.dart:1371)
#61     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#62     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#63     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#64     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:343)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by sigmundch** [comment]
Thanks for filing!

Good news is that this is now fixed in the dev channel. This is correctly detected by the new common front-end, which dart2js uses by default now.

I'm not sure when will dartpad get updated to the latest version of dart2js, but  @devoncarew can probably comment on it.

**Comment by devoncarew** [comment]
We're tracking the work to upgrade to Dart 2 here: https://github.com/dart-lang/dart-services/issues/337.
