### ISSUE TITLE
Directory.watch() doesn't work with runtime Dart 2 semantics

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#33027]
When running the following script with `--preview-dart-2`:

```dart
import 'dart:io';

void main() {
  new Directory('.').watch().listen(print);
}
```

it produces this error:

```
Unhandled exception:
type '_BroadcastStream<dynamic>' is not a subtype of type 'Stream<FileSystemEvent>' where
  _BroadcastStream is from dart:async
  Stream is from dart:async
  FileSystemEvent is from dart:io

#0      _FileSystemWatcher._watch (dart:io/runtime/binfile_patch.dart:112:69)
#1      FileSystemEntity.watch (dart:io/file_system_entity.dart:489:33)
#2      main (file:///home/nweiz/test.dart:4:22)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Tested with Dart 2.0.0-dev.52.0.

**Comment by dgrove** [comment]
This blocks getting some third-party packages to be Dart 2 compliant.

**Comment by a-siva** [comment]
The CL https://dart-review.googlesource.com/c/sdk/+/53696 which is under review should address this issue. Will close the issue once the CL lands and cycles through the bots.

**Comment by a-siva** [comment]
CL has landed.
