### ISSUE TITLE
Fatal analysis server exception: "The getter 'keyword' was called on null" (make variable final quickfix?)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33058]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I had the below file and I backspaced over the colon for the initialiser list of `CancellationSource`. Note: This is recent flutter master; I'm not sure why the hash in the Dart SDK version below is from Feb (though interestingly it was a changeset about changing version numbers) - I'll raise a Dart Code issue to look at that. I believe this is effectively current code.

```dart
import 'dart:async';

class CancellationToken {
  Completer<void> _completer;
  CancellationToken(this._completer);

  bool get isCancellationRequested => _completer.isCompleted;
  Future<void> get cancelled => _completer.future;
}

class CancellationSource {
  Completer<void> completer = new Completer<void>();
  final CancellationToken _token;
  CancellationSource() _token = new CancellationToken(this);
  CancellationToken get token => _token;
  void cancel() => completer.complete();
}
```

### Versions

- Dart SDK 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
- Flutter SDK 0.3.6-pre.72
- Visual Studio Code 1.23.0
- Dart Code 2.12.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.12.1
--no-preview-dart-2
```

### Exception (fatal)

Failed to handle request: {id: 25, method: edit.getFixes, params: {file: /Users/dantup/Dev/Google/flutter/packages/flutter_tools/lib/src/cancellation.dart, offset: 535}}

```text
NoSuchMethodError: The getter 'keyword' was called on null.
Receiver: null
Tried calling: keyword
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FixProcessor._addFix_makeVariableFinal.<anonymous closure> (package:analysis_server/src/services/correction/fix_internal.dart:2201)
#2      DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:47)
#3      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:67)
<asynchronous suspension>
#4      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:47)
#5      FixProcessor._addFix_makeVariableFinal (package:analysis_server/src/services/correction/fix_internal.dart:2200)
<asynchronous suspension>
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:472)
<asynchronous suspension>
#7      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:86)
<asynchronous suspension>
#8      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:529)
<asynchronous suspension>
#9      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:228)
<asynchronous suspension>
#10     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:332)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:722)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:718)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1490)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:717)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#22     _rootRunUnary (dart:async/zone.dart:1134)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#34     _rootRunUnary (dart:async/zone.dart:1134)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#47     _rootRunUnary (dart:async/zone.dart:1134)
#48     _CustomZone.runUnary (dart:async/zone.dart:1031)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#53     _StreamController._add (dart:async/stream_controller.dart:639)
#54     _StreamController.add (dart:async/stream_controller.dart:585)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1674)
#56     _rootRunUnary (dart:async/zone.dart:1138)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#62     _StreamController._add (dart:async/stream_controller.dart:639)
#63     _StreamController.add (dart:async/stream_controller.dart:585)
#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#68     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_path",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools",
        "explicitFileCount": 202,
        "implicitFileCount": 1432,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/asset_test/font",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/changed_sdk_location",
        "explicitFileCount": 1,
        "implicitFileCount": 93,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_package",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_import",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/asset_test/main",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/syntax_error",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/good",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/asci_casing",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment]
(cc @bwilkerson )

**Comment by bwilkerson** [comment]
This should have been fixed by https://dart-review.googlesource.com/53840. Let me know if that's not the case.

**Comment by DanTup** [comment]
Can't repro on latest code, so seems like it 👍
