### ISSUE TITLE
Sporadic VM crashes in pub get

### ISSUE THREAD

**Issue by cbracken** [dart-lang/sdk#33074]
Saw this segfault on the Mac Flutter chromebot.
[Log with trace](https://build.chromium.org/p/client.flutter/builders/Mac/builds/5898/steps/run%20test.dart%20for%20tests%20shard/logs/stdio)

Relevant Dart/Native backtrace:
```
02:42 +261 ~1: test/commands/packages_test.dart: packages get/upgrade get fetches packages and injects plugin in plugin project
Exception: pub get failed (-6)
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:168:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104:13)
<asynchronous suspension>
#3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:60:11)
<asynchronous suspension>
#4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:90:13)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344:18)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279:33)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     runZoned (dart:async/zone.dart:1501)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309:31)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1126)
#17     _CustomZone.run (dart:async/zone.dart:1023)
#18     runZoned (dart:async/zone.dart:1501)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#22     new Future.sync (dart:async/future.dart:222)
#23     CommandRunner.run (package:args/command_runner.dart:109:11)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174:21)
#25     main.<anonymous closure>.runCommandIn (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/commands/packages_test.dart:70:20)
<asynchronous suspension>
#26     main.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/commands/packages_test.dart:221:25)
<asynchronous suspension>
#27     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:100:42)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1126)
#30     _CustomZone.run (dart:async/zone.dart:1023)
#31     runZoned (dart:async/zone.dart:1501)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#33     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:88:30)
#34     _rootRun (dart:async/zone.dart:1126)
#35     _CustomZone.run (dart:async/zone.dart:1023)
#36     runZoned (dart:async/zone.dart:1490)
#37     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:86:18)
#38     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#39     _rootRun (dart:async/zone.dart:1126)
#40     _CustomZone.run (dart:async/zone.dart:1023)
#41     runZoned (dart:async/zone.dart:1501)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#43     testUsingContext.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:63:22)
#44     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#45     _rootRun (dart:async/zone.dart:1126)
#46     _CustomZone.run (dart:async/zone.dart:1023)
#47     runZoned (dart:async/zone.dart:1501)
#48     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#49     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#50     testUsingContext.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:62:11)
<asynchronous suspension>
#51     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
<asynchronous suspension>
#52     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#53     _rootRun (dart:async/zone.dart:1126)
#54     _CustomZone.run (dart:async/zone.dart:1023)
#55     runZoned (dart:async/zone.dart:1501)
#56     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
#57     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
#58     _rootRun (dart:async/zone.dart:1126)
#59     _CustomZone.run (dart:async/zone.dart:1023)
#60     runZoned (dart:async/zone.dart:1501)
#61     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
<asynchronous suspension>
#62     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#63     new Future.<anonymous closure> (dart:async/future.dart:174)
#64     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#65     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#66     _rootRun (dart:async/zone.dart:1122)
#67     _CustomZone.run (dart:async/zone.dart:1023)
#68     _CustomZone.runGuarded (dart:async/zone.dart:925)
#69     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#70     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#71     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#72     _rootRun (dart:async/zone.dart:1126)
#73     _CustomZone.run (dart:async/zone.dart:1023)
#74     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#75     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#76     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#77     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#78     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


===== CRASH =====
version=2.0.0-dev.53.0.flutter-e6d7d67f4b (Thu May 3 21:11:44 2018 +0000) on "macos_x64"
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
Dumping native stack trace for thread f03
  [0x0000000103f01a34] [Stub] TwoArgsCheckInlineCache
  [0x0000000103f01a34] [Stub] TwoArgsCheckInlineCache
  [0x000000010593e0cd] SolveReport._reportPackage
  [0x00000001083a98bd] *_Closure.call
  [0x00000001076cf438] _GrowableList.forEach
  [0x000000010593d43f] SolveReport._reportChanges
  [0x000000010593d19d] SolveReport.show
  [0x000000010593c460] SolveResult.showReport
  [0x00000001071e02f3] Entrypoint.acquireDependencies
  [0x0000000106e87d1b] _Closure.call
  [0x00000001073e5336] _asyncThenWrapperHelper.<anonymous closure>
  [0x00000001083a98bd] *_Closure.call
  [0x00000001073e515a] StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure>
  [0x00000001059103ac] *StackZoneSpecification._run
  [0x00000001073e4f7a] StackZoneSpecification._registerUnaryCallback.<anonymous closure>
  [0x000000010591f9ae] *_rootRunUnary
  [0x0000000103dd0562] _rootRunUnary
  [0x00000001059176b3] *_FutureListener.handleValue
  [0x0000000103dd4b9c] _Future._propagateToListeners.handleValueCallback
  [0x000000010591567c] *_Future._propagateToListeners
  [0x0000000105923a88] *_Future._complete
  [0x000000010592c8c3] *_completeOnAsyncReturn
  [0x00000001073cd94f] VersionSolver.solve
  [0x0000000106e87d1b] _Closure.call
  [0x00000001073e5336] _asyncThenWrapperHelper.<anonymous closure>
  [0x00000001083a98bd] *_Closure.call
  [0x00000001073e515a] StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure>
  [0x00000001059103ac] *StackZoneSpecification._run
  [0x00000001073e4f7a] StackZoneSpecification._registerUnaryCallback.<anonymous closure>
  [0x000000010591f9ae] *_rootRunUnary
  [0x0000000103dd0562] _rootRunUnary
  [0x00000001059176b3] *_FutureListener.handleValue
  [0x0000000103dd4b9c] _Future._propagateToListeners.handleValueCallback
  [0x000000010591567c] *_Future._propagateToListeners
  [0x0000000105923a88] *_Future._complete
  [0x000000010592c8c3] *_completeOnAsyncReturn
  [0x00000001059359af] VersionSolver._result
  [0x0000000106e87d1b] _Closure.call
  [0x00000001073e5336] _asyncThenWrapperHelper.<anonymous closure>
  [0x00000001083a98bd] *_Closure.call
  [0x00000001073e515a] StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure>
  [0x00000001059103ac] *StackZoneSpecification._run
  [0x00000001073e4f7a] StackZoneSpecification._registerUnaryCallback.<anonymous closure>
  [0x000000010591f9ae] *_rootRunUnary
  [0x0000000103dd0562] _rootRunUnary
  [0x00000001059176b3] *_FutureListener.handleValue
  [0x0000000103dd4b9c] _Future._propagateToListeners.handleValueCallback
  [0x000000010591567c] *_Future._propagateToListeners
  [0x0000000105923a88] *_Future._complete
  [0x000000010592c8c3] *_completeOnAsyncReturn
  [0x00000001083a1d1e] BoundSource.describe
  [0x000000010590e63a] *_Closure.call
  [0x0000000103e49e5c] new Future.microtask.<anonymous closure>
  [0x00000001059103ac] *StackZoneSpecification._run
  [0x000000010592980c] *StackZoneSpecification._registerCallback.<anonymous closure>
  [0x0000000105916b51] *_rootRun
  [0x0000000105929710] *_rootRun
  [0x0000000105923761] *_CustomZone.runGuarded
  [0x000000010592e327] *_CustomZone.bindCallbackGuarded.<anonymous closure>
  [0x00000001059103ac] *StackZoneSpecification._run
  [0x000000010592980c] *StackZoneSpecification._registerCallback.<anonymous closure>
  [0x0000000105916adf] *_rootRun
  [0x0000000105929710] *_rootRun
  [0x0000000105923761] *_CustomZone.runGuarded
  [0x000000010592e327] *_CustomZone.bindCallbackGuarded.<anonymous closure>
  [0x00000001059342a7] *_microtaskLoop
  [0x0000000103dc99b9] _startMicrotaskLoop
  [0x0000000103dc9cf3] _startMicrotaskLoop
  [0x000000010590e63a] *_Closure.call
  [0x00000001076d6bb1] _Timer._runTimers
  [0x00000001076d53dc] _Timer._handleMessage
  [0x00000001076d51f6] _Timer._handleMessage
  [0x00000001083a98bd] *_Closure.call
  [0x0000000103e80620] _RawReceivePortImpl._handleMessage
  [0x0000000103f00a83] [Stub] InvokeDartCode
  [0x00000001024765c7] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  [0x000000010247a15e] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  [0x00000001024ab0d6] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x00000001024d959a] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x00000001024d9d6c] dart::MessageHandler::TaskCallback()
  [0x000000010268d7cd] dart::ThreadPool::Worker::Loop()
  [0x000000010268d5ff] dart::ThreadPool::Worker::Main(unsigned long)
  [0x000000010258af49] dart::ThreadStart(void*)
  [0x00007fffe3d0a93b] _pthread_body
  [0x00007fffe3d0a887] _pthread_body
  [0x00007fffe3d0a08d] thread_start
-- End of DumpStackTrace
```
Flutter engine revision: flutter/engine@20b286dd428a0d8dd0f87b7a03ab67fbf0da2836
Includes Dart VM revision: dart-lang/sdk@e6d7d67f4b35556805dd083fed15bf3ed41f7e33

**Comment by a-siva** [comment]
This is not easily reproducible.

**Comment by dgrove** [comment]
Does this still rate as a P1?

**Comment by a-siva** [comment]
Do we still see these crashes?
@cbracken cbracke Is there a way of getting a coredump from the flutter builders when this happens.
(removing milestone for now, if it reproduces we can add the milestone back).

**Comment by cbracken** [comment]
Yep we still see crashes on the Mac bots.

Talked with @mraleph while he was here and we confirmed we have coredumps enabled in the local .bashrc -- when we log in and type `ulimit -c` it's showing as unlimited and we were able to get a corefile from a small C program I wrote to include a null pointer dereference.

That said, I've never been able to collect a corefile from the machine. It reboots after each build; I'm wondering if it's clearing out the /cores dir on boot. One thought we had was to add a wrapper that looks for corefiles at the end of the build and uploads them to Google Storage. @mraleph mentioned they had previously set something up like this for the Dart build bots.

**Comment by a-siva** [comment]
I noticed the recent engine roll into the framework shows a crash in 'pub get', see https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8857620590359448672/+/steps/download_dependencies/0/stdout
```
===== CRASH =====
 si_signo=Segmentation fault(11), si_code=1, si_addr=0x7f4565f64e68
 version=2.12.0-244.0.dev (dev) (Tue Jan 19 10:47:18 2021 -0800) on "linux_x64"
 pid=16619, thread=16626, isolate_group=main(0x22f0260), isolate=main(0x22ef9e0)
 isolate_instructions=7f4580d07000, vm_instructions=17efb80
 Stack dump aborted because InitialRegisterCheck failed.
 pub get failed (-6; Stack dump aborted because InitialRegisterCheck failed.)

```

**Comment by a-siva** [comment]
A number of fixes been made after these crashes were reported, unclear if we are still seeing crashes.
Closing this ieeue, if we encounter any crashes with 'pub get' please open a fresh issue and it will be investigated.
