### ISSUE TITLE
Need to bootstrap incremental compiler if it doesn't already exist for expression compilation

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#33087]

**Comment by aam** [comment]
@sjindel-google can you confirm if there is a way to bootstrap expression-evaluation-friendly incremental compiler from the dill file in absence of dart sources used to build that dill file? 

`IncrementalCompiler` has an option to bootstrap from dill file: https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/incremental_compiler.dart#L81, but such compiler seems to be unusable with `compileExpression`.
Looking at the https://github.com/dart-lang/sdk/blob/master/pkg/front_end/test/fasta/expression_test.dart#L303 it seems that it tests scenario of bootstrapping from dill file, but it relies on sources present as well.

We need to bootstrap incremental compiler from single kernel dill file because that is the only thing that VM will have if user's dart application was launched from such dill file.

**Comment by sjindel-google** [comment]
> Looking at the https://github.com/dart-lang/sdk/blob/master/pkg/front_end/test/fasta/expression_test.dart#L303 it seems that it tests scenario of bootstrapping from dill file, but it relies on sources present as well.

The test script creates two separate `IncrementalCompiler`s for each test. The second one is only given the `.dill` file and is able to compile the expression from that. So I don't see how it relies on the presence of the sources? Perhaps they are available through the memory filesystem shared by both compilers, but that is often the case for `kernel-service` as well.

> such compiler seems to be unusable with compileExpression.

Can you provide a way to reproduce of this issue?

**Comment by aam** [comment]
Following patch adds a test on top of the https://dart-review.googlesource.com/c/sdk/+/54407 that you can run with `python tools/test.py -mrelease -cnone -rvm --checked pkg/vm/test/incremental_compiler_test `: 

```
diff --git a/pkg/vm/test/incremental_compiler_test.dart b/pkg/vm/test/incremental_compiler_test.dart
index 3736600803..4d978e8f12 100644
--- a/pkg/vm/test/incremental_compiler_test.dart
+++ b/pkg/vm/test/incremental_compiler_test.dart
@@ -56,6 +56,38 @@ main() {
     });
   });
 
+  group('initialize-from-dill', () {
+    test('compile', () async {
+      var systemTempDir = Directory.systemTemp;
+      var sourceFile = new File('${systemTempDir.path}/foo.dart')..createSync();
+      sourceFile.writeAsStringSync("main() {}\n");
+
+      IncrementalCompiler compiler = new IncrementalCompiler(options, sourceFile.uri);
+      Component component = await compiler.compile();
+      File dillFile = new File('${systemTempDir.path}/foo.dart.dill');
+      await _writeProgramToFile(component, dillFile);
+//      sourceFile.deleteSync();
+
+      IncrementalCompiler compilerFromDill = new IncrementalCompiler(options, dillFile.uri);
+      component = await compilerFromDill.compile(entryPoint: sourceFile.uri);
+
+      final StringBuffer buffer = new StringBuffer();
+      new Printer(buffer, showExternal: false, showMetadata: true)
+          .writeLibraryFile(component.mainMethod.enclosingLibrary);
+      expect(
+          buffer.toString(),
+          equals('library;\n'
+              'import self as self;\n'
+              '\n'
+              'static method main() → dynamic {}\n'));
+
+      var result = await compilerFromDill.compileExpression(
+          '2+2', [], [], sourceFile.uri.toString(), null, false);
+      expect(result, isNotNull);
+    });
+  });
+
+
   group('reload', () {
     test('picks up after rejected delta', () async {
       var systemTempDir = Directory.systemTemp;
```

It passes with `sourceFile.deleteSync();` commented out. Once I uncomment it, I was not able to 
make it pass. The closest I got was with following second compilation:
```
      IncrementalCompiler compilerFromDill = new IncrementalCompiler(options, dillFile.uri,
          bootstrapDill: dillFile.uri);
      component = await compilerFromDill.compile(entryPoint: sourceFile.uri);
```
but this still fails with
```
00:01 +1 -1: initialize-from-dill compile [E]
  'package:front_end/src/fasta/incremental_compiler.dart': Failed assertion: line 367 pos 12: 'dillLoadedData != null && userCode != null': is not true.
  dart:core-patch/dart:core/errors_patch.dart 37                _AssertionError._doThrowNew
  dart:core-patch/dart:core/errors_patch.dart 33                _AssertionError._throwNew
  package:front_end/src/fasta/incremental_compiler.dart 367:12  IncrementalCompiler.compileExpression
 ```

**Comment by jensjoha** [comment]
a) The test is wrong. It doesn't actually initialize from the dill. Correct to
```
IncrementalCompiler compilerFromDill = new IncrementalCompiler(options, dillFile.uri, bootstrapDill: dillFile.uri);
```

b) It now crashes because `userCode` is null. In this case it's set to null here:
```
      if (componentWithDill == null) {
        userCode.loader.builders.clear();
        userCode = userCodeOld;
      }
```

correcting to
```
      if (componentWithDill == null && userCodeOld != null) {
        userCode.loader.builders.clear();
        userCode = userCodeOld;
      }
```
fixes that.

c) It then crashes with
```
Tried calling: createLocalTypeInferrer(Instance of '_Uri', null, Instance of 'KernelLibraryBuilder')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      DietListener.createListener (package:front_end/src/fasta/source/diet_listener.dart:535:31)
```
because `typeInferenceEngine` wasn't created  because `buildOutlines` bailed out because it wasn't asked to compile anything. As a hack I tried removing the bailout (i.e. the first line in `buildOutlines` in  `kernel_target.dart`) (though that might not be the way to go) and stuff now seems to work.

All of this must be problems with expression compilation so I'm assigning it back.

**Comment by aam** [comment]
@kmillikin This problem seems to happen when frontend compiler finds existing dill file with previous results of compilation and bootstraps itself from it. This effectively results in expression compilation not working once application was compiled once.

**Comment by jensjoha** [comment]
@aam  please confirm this solves your problem.

**Comment by aam** [comment]
@jensjoha original issue "The getter 'loader' was called on null." seems to be fixed, but simple flow of evaluating class-scoped expression regressed(still only when compiler is initialized from dill file). Compiler now fails to evaluate static class property expression(static field name in context of a class)  with following exception:
```
ompiler message: Unhandled exception:
compiler message: Unsupported operation: Cannot set value in unmodifiable Map
compiler message: #0      _ImmutableMap.[]= (dart:core/runtime/libimmutable_map.dart:72:5)
compiler message: #1      SourceLibraryBuilder.addToScope (package:front_end/src/fasta/source/source_library_builder.dart:711:10)
compiler message: #2      Import.finalizeImports.<anonymous closure> (package:front_end/src/fasta/import.dart:65:18)
compiler message: #3      Import.finalizeImports.<anonymous closure> (package:front_end/src/fasta/import.dart:79:10)
compiler message: #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
compiler message: #5      Scope.forEach (package:front_end/src/fasta/scope.dart:251:13)
compiler message: #6      Import.finalizeImports (package:front_end/src/fasta/import.dart:72:26)
compiler message: #7      SourceLibraryBuilder.addImportsToScope (package:front_end/src/fasta/source/source_library_builder.dart:689:14)
compiler message: #8      KernelLibraryBuilder.addImportsToScope (package:front_end/src/fasta/kernel/kernel_library_builder.dart:1134:11)
compiler message: #9      IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:486:22)
compiler message: <asynchronous suspension>
compiler message: #10     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
compiler message: #11     new Future.sync (dart:async/future.dart:222:31)
compiler message: #12     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
compiler message: #13     _rootRun (dart:async/zone.dart:1126:13)
compiler message: #14     _CustomZone.run (dart:async/zone.dart:1023:19)
compiler message: #15     _runZoned (dart:async/zone.dart:1518:10)
compiler message: #16     runZoned (dart:async/zone.dart:1465:12)
compiler message: #17     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
compiler message: #18     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:428:26)
compiler message: <asynchronous suspension>
compiler message: #19     IncrementalCompiler.compileExpression (package:vm/incremental_compiler.dart:103:23)
compiler message: #20     FrontendCompiler.compileExpression (package:vm/frontend_server.dart:448:44)
compiler message: <asynchronous suspension>
compiler message: #21     _FlutterFrontendCompiler.compileExpression (package:frontend_server/server.dart:55:22)
compiler message: #22     listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:650:20)
compiler message: <asynchronous suspension>
compiler message: #23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
compiler message: #24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
compiler message: #25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
compiler message: #26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
compiler message: #27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
compiler message: #28     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
compiler message: #29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
compiler message: #30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
compiler message: #31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
compiler message: #32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
compiler message: #33     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
compiler message: #34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
compiler message: #35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
compiler message: #36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
compiler message: #37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
compiler message: #38     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
compiler message: #39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
compiler message: #40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
compiler message: #41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
compiler message: #42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
compiler message: #43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
compiler message: #44     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
compiler message: #45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
compiler message: #46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
compiler message: #47     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
compiler message: #48     _StreamController._add (dart:async/stream_controller.dart:639:7)
compiler message: #49     _StreamController.add (dart:async/stream_controller.dart:585:5)
compiler message: #50     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1672:41)
compiler message: #51     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
compiler message: #52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
compiler message: #53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
compiler message: #54     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
compiler message: #55     _StreamController._add (dart:async/stream_controller.dart:639:7)
compiler message: #56     _StreamController.add (dart:async/stream_controller.dart:585:5)
compiler message: #57     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1245:33)
compiler message: #58     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:797:14)
compiler message: #59     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
compiler message: #60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
compiler message: #61     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
compiler message: #62     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

**Comment by zoechi** [comment]
I still get "loader was called on null", but also have seen Cannot set value in unmodifiable Map.
Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2
Perhaps this Dart version doesn't contain the fix yet. It usually takes a while until new Dart versions land in Flutter.

See also flutter/flutter#18857

**Comment by jensjoha** [comment]
It's my understanding that https://dart-review.googlesource.com/c/sdk/+/62729 fixes the problem, so I'll ignore my assignment for now.

**Comment by jensjoha** [comment]
Was this fixed with https://dart-review.googlesource.com/c/sdk/+/62729 / 860689052ac9c07d8c7da26aead845cf09c8e396 ?

**Comment by aam** [comment]
This hasn't landed into flutter yet, but from initial testing, yes it seems to be fixed.

**Comment by aam** [comment]
Sorry for the confusion, but what was fixed in https://github.com/dart-lang/sdk/commit/860689052ac9c07d8c7da26aead845cf09c8e396 was https://github.com/dart-lang/sdk/issues/33087#issuecomment-388504565.

There is still work remaining to actually create incremental compiler if dart app was launched from kernel file and incremental compiler was not created. At present this only happening in simarm/simdbc tests.

**Comment by aam** [comment]
Remaining work to support observatory/expression evaluation in standalone dart vm(per https://github.com/dart-lang/sdk/issues/33087#issuecomment-427966692) is deemed to be lower priority, is not on 2.1 path. So will close this again and track remaining work on https://github.com/dart-lang/sdk/issues/34736.
