### ISSUE TITLE
CFE crash while trying to compile

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#33095]
```
result 375e0993-f391-49d3-a646-9d6d63054452
Unhandled exception:
Concurrent modification during iteration: Instance(length:2903) of '_GrowableList'.
#0      ListIterator.moveNext (dart:_internal/iterable.dart:337)
#1      BinaryPrinter.writeConstantTable (package:kernel/binary/ast_to_binary.dart:134)
#2      BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:322)
#3      FrontendCompiler.compile (package:vm/frontend_server.dart:289)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:29)
<asynchronous suspension>
#5      starter (package:frontend_server/server.dart:107)
<asynchronous suspension>
#6      main (file:///b/build/slave/Linux_Engine/build/src/flutter/frontend_server/bin/starter.dart:6)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by tvolkert** [comment]
This was against 779dc6eb85c1f2249803d017ffa785c85681ad1b

**Comment by aam** [comment]
Are there steps to reproduce this?
I have run flutter gallery against that roll and it was compiling and working fine.

**Comment by tvolkert** [comment]
@aam try to build `//mobile/flutter/samples/production/app` inside Google.

**Comment by alexmarkov** [comment]
This looks related to constant evaluation.

/cc @mkustermann

**Comment by aam** [comment]
039e8a1755080c2cbf9ae96fca0063561e3ed72a seems to be the culprit.

**Comment by aam** [comment]
The culprit cl reverts cleanly and with it the test builds fine.

**Comment by dgrove** [comment]
@aam can you go ahead and revert this now?

**Comment by aam** [comment]
The revert is being landed here: https://dart-review.googlesource.com/c/sdk/+/54720

**Comment by dgrove** [comment]
Dropping the P0 and milestone now that this has reverted cleanly.
