### ISSUE TITLE
Confusing inference of `func<T>(Obj<T> a, T b)`

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33094]
Internal customer was confused, because the following:

```dart
class Obj<T> {}

void func<T>(Obj<T> a, T b) {
  print('T: $T');
  print('a.runtimeType: ${a.runtimeType}');
}

main() {
  // Shouldn't this be a compile-time error?
  func(new Obj<int>(), "Hello World");
}
```

... did not trigger an analysis/compiler error/warning.

When running this with `dart --preview-dart-2` (Dart VM version: 2.0.0-dev.52.0), I get:

```
T: Object
a.runtimeType: Obj<int>
```

The program fails (expectedly) if you write:

```dart
func<int>(new Obj<int>(), "Hello World")
```

... but if you omit `<int>` at the function call, `T` seems to be filled in as `Object` instead :-/

**Comment by matanlurey** [comment]
(I did not try `--no-implicit-casts` or `--no-implicit-dynamic` in the analyzer)

**Comment by matanlurey** [comment]
BTW, if I change `new Obj<int>` to `new Obj<void>`, we do get _2_ errors:

```
* Couldn't infer type parameter 'T'. Tried to infer 'void' for 'T' which doesn't work: Parameter 'b' declared as 'T' but argument is 'List<dynamic>'. The type 'void' was inferred from: Parameter 'a' declared as 'Obj<T>' but argument is 'Obj<void>'. Consider passing explicit type argument(s) to the generic.

* The argument type 'List' can't be assigned to the parameter type 'void'.
```

**Comment by matanlurey** [comment]
@hterkelsen brought up a particularly scary one:

```dart
void addTo<T>(List<T> list, T element) {
  list.add(element);
}

void main() {
  // Works, with no errors.
  final list = [1, 2, 3];
  addTo(list, "hello");
  print(list);
}
```

In Dart 1, this prints: `[1, 2, 3, hello]`.

In Dart 2 (`dart --preview-dart-2`), this fails at runtime, but not compile-time:

```
Unhandled exception:
type 'String' is not a subtype of type 'int' of 'value' where
  String is from dart:core
  int is from dart:core

#0      List.add (dart:core/runtime/libgrowable_array.dart)
#1      addTo (file:///tmp/stash2.dart:2:8)
#2      main (file:///tmp/stash2.dart:8:3)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

(Though the error makes it _very_ tough for me to understand what happened)

**Comment by matanlurey** [comment]
As we discovered, we can (correctly) get a static error if we write, instead:

```dart
void addTo<U extends T, T>(List<T> list, U element) {
  list.add(element);
}
```

I imagine if we got invariant generics as an option, one could also write:

```dart
void addTo<in T>(...)
```

... right?

**Comment by leafpetersen** [comment]
Yeah, this is WAI.  I don't think the Dart 2 migration would have been possible if we had been much stricter, but I certainly agree that inference is currently more forgiving than I like.  I would like to provide a way to opt into stricter inference, but I think it requires some careful design.  The property of inference that allows the examples above to infer `Object` is the same property that allows inference to deduce `List<num>` for `[1.0, 1]`.  It's hard to prevent the former without also preventing the latter, and many people expect the latter to work.  I think this will require some empirical work and iteration with customers. 

Unfortunately, variance annotations on generics wouldn't solve this, it doesn't really work that way.

Options I have considered include:
  - Use min/max instead of LUB/GLB.  This means that `[1.0, 1]` doesn't work though.
  - Use LUB/GLB, but make it an error to infer a top type (unless at least one or possibly all of the types involved were top types)
  - Forbid inference from introducing implicit downcasts that weren't already there

The second restriction would solve this issue.

The third restriction would catch things like this:

```dart
main() {
  List<Object> a = [3];
  Object Function(Object) f = (a) => a;
  Iterable<int> l = a.map(f);
}
```
