### ISSUE TITLE
Automatically created issue by Android Studio

### ISSUE THREAD

**Issue by malkia** [dart-lang/sdk#33107]
[report.txt](https://github.com/dart-lang/sdk/files/1998108/report.txt)
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4720617`
- `2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c`
- `AI-173.4720617, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2160x1440`

# Exception

Please append the contents of:
file://C:\Users\malki\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c, server version 1.20.2, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\p\flu\flutter\examples\flutter_gallery], excluded: [C:\p\flu\flutter\examples\flutter_gallery\.idea]}, clientRequestTime: 1526186250990}
FileSystemException: Exists failed, path = 'C:\p\flu\flutter\examples\flutter_gallery\build\app\intermediates\assets\release\flutter_assets\packages\flutter_gallery_assets\shrine\fonts\abrilfatface' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:73)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:323)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166)
#3      _HashVMBase

**Comment by vsmenon** [comment]
Dup of #33106 (@devoncarew - looks like a couple folks hit this very recently).
