### ISSUE TITLE
Fasta accepts type parameters on constructors

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#33110]
```dart
class Foo {
  Foo<A>() {}
}
```
Tested by `language_2/constructor_type_parameter_test`.

**Comment by askeksa-google** [comment]
In debug mode, the example hits an assert in the serializer:
```
Unhandled exception:
'package:kernel/binary/ast_to_binary.dart': Failed assertion: line 803 pos 12: 'node.function.typeParameters.isEmpty': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
#1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
#2      BinaryPrinter.visitConstructor (package:kernel/binary/ast_to_binary.dart:803:12)
#3      Constructor.accept (package:kernel/ast.dart:1242:32)
#4      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:237:10)
#5      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:229:7)
#6      BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:767:5)
#7      Class.accept (package:kernel/ast.dart:861:30)
#8      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:237:10)
#9      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:229:7)
#10     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:621:5)
#11     Library.accept (package:kernel/ast.dart:409:30)
#12     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:237:10)
#13     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#14     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:452:25)
#15     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:317:5)
#16     writeComponentToFile (package:front_end/src/fasta/kernel/utils.dart:42:13)
<asynchronous suspension>
#17     CompileTask.compile (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:271:13)
<asynchronous suspension>
#18     compile.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:193:25)
<asynchronous suspension>
#19     withGlobalOptions.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:390:13)
#20     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:106:35)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     runZoned (dart:async/zone.dart:1501)
#24     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:106:14)
#25     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:117:41)
#26     withGlobalOptions (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:383:26)
#27     compile (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:186:18)
<asynchronous suspension>
#28     compileEntryPoint (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:65:11)
<asynchronous suspension>
#29     main (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```
