### ISSUE TITLE
Dart2+VM+Const+Generics = Confusing crash

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33120]
While helping teams internally migrate VM tests to Dart2, I hit the following:

`"Error evaluating constant constructor"`

These really hurt, because they are actually missing parts of the stack trace, making it extra hard to figure out offending lines. It took me over an hour to debug this, and I've been doing Dart2 migrations for over a year. Unfortunately I'm _not_ able to reproduce externally.

Internal issue is [b/79701769](b/79701769).

Here is a sort of representative sample, and an example crash:

```dart
import 'package:test/test.dart';

class CacheBucket {
  final CacheConfig cacheConfig;
  const CacheBucket._({this.cacheConfig: const CacheConfig()});
  const CacheBucket() : this._();
}

class CacheEntry<K, V> {
  final K key;
  final V value;
  const CacheEntry(this.key, this.value);
}

typedef Iterable<CacheEntry<K, V>> CacheEvictionFn<K, V>(
  List<CacheEntry<K, V>> entries,
);

Iterable<CacheEntry<K, V>> identityCacheEviction<K, V>(
  List<CacheEntry<K, V>> entries,
) =>
    entries;

class CacheConfig {
  final CacheEvictionFn cacheEvictionFn;
  const CacheConfig({this.cacheEvictionFn = identityCacheEviction});
}

void main() {
  test('should not blow up spectacularly', () {
    new CacheBucket();
  });
}
```

... causes ...

```
type '<K, V>(List<CacheEntry<K, V>>, int) => Iterable<CacheEntry<K, V>>' is not a subtype of type '(List<CacheEntry<dynamic, dynamic>>, int) => Iterable<CacheEntry<dynamic, dynamic>>' of 'cacheEvictionFn'
#0      new CacheConfig._ (../cache_config.dart)
#1      new CacheConfig (../cache_config.dart)
#2      main.<anonymous closure>.<anonymous closure> (test.dart:11:37)
[ 28 other lines that have nothing to do with the failure ]
error: error evaluating constant constructor
test.dart 11:37  main.<fn>.<fn>
```

**NOTE**: This doesn't seem to crash externally with `--preview-dart-2`. I don't know if this is related to how `package:test` uses isolates, or something else entirely (internal only infra), or if I just can't extract a test case properly.

**Comment by mraleph** [comment]
@jensjoha can you look at producing better error messages from constant evaluator?

@mkustermann

**Comment by mkustermann** [comment]
@mraleph These are bugs either in the constant evaluator or in transformations (e.g. TFA) which violate Kernel IR assumptions.

These are not compile-time error messages.

**Comment by mkustermann** [comment]
It seems these error messages are coming from the c++ constant evaluator we have in the flow graph builder.

To be more consistent across our tools as well as to provide better error messages, I think it makes sense to move these errors out of the VM into the CFE.

We will very soon switch to using a kernel2kernel constant evaluator in AOT mode (after that re-lands), which I believe produces in most cases better error messages than existing VM.

@peter-ahe-google @jensjoha Maybe it would make sense to also use this in the CFE now?

**Comment by peter-ahe-google** [comment]
@mkustermann yes, we should incorporate the kernel2kernel constant evaluator in the CFE. We just need to make sure that we only do the evaluation without rewriting constants to preserve most flexibility for modular compilation.

It's not just about consistency across tools, the CFE would need to evaluate constants before the Analyzer can completely switch to the CFE as well.

**Comment by jensjoha** [comment]
Reproduction:

pubspec.yaml:
```
name: issue_33120
dependencies:
  test: 0.12.38
```

runner.dart:
```
import 'package:test/src/executable.dart' as executable;

main(List<String> args) async {
  await executable.main(args);
}
```
test.dart:
```
Iterable<Map<K, V>> qux<K, V>(List<Map<K, V>> quux) {
  return quux;
}

typedef Iterable<Map<K, V>> Baz<K, V>(List<Map<K, V>> quux);

class Bar {
  final Baz baz;
  const Bar({this.baz: qux});
}

class Foo {
  final Bar bar;
  Foo({this.bar: const Bar()});
}

void main() {
  new Foo();
}
```

Run like this:
```
[whereever]/dart-sdk/sdk/out/ReleaseX64/dart --preview-dart-2 runner.dart test.dart
```

Result:
```
00:01 +0 -1: loading test.dart [E]                                                                                                                                                           
  Failed to load "test.dart":
  Unhandled exception:
  type '<K, V>(List<Map<K, V>>) => Iterable<Map<K, V>>' is not a subtype of type '(List<Map<dynamic, dynamic>>) => Iterable<Map<dynamic, dynamic>>' of 'baz'
  #0      new Bar ([...]/issue_33120/test.dart)
  #1      main ([...]/issue_33120/test.dart:18:7)
  #2      _rootRun (dart:async/zone.dart:1126:13)
  #3      _CustomZone.run (dart:async/zone.dart:1023:19)
  #4      runZoned (dart:async/zone.dart:1501:17)
  #5      Declarer.declare (package:test/src/backend/declarer.dart:121:22)
  #6      RemoteListener.start.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/runner/remote_listener.dart:118:26)
  <asynchronous suspension>
  #7      _rootRun (dart:async/zone.dart:1126:13)
  #8      _CustomZone.run (dart:async/zone.dart:1023:19)
  #9      runZoned (dart:async/zone.dart:1490:19)
  #10     RemoteListener.start.<anonymous closure>.<anonymous closure> (package:test/src/runner/remote_listener.dart:70:9)
  #11     _rootRun (dart:async/zone.dart:1126:13)
  #12     _CustomZone.run (dart:async/zone.dart:1023:19)
  #13     runZoned (dart:async/zone.dart:1501:17)
  #14     StackTraceFormatter.asCurrent (package:test/src/backend/stack_trace_formatter.dart:41:31)
  #15     RemoteListener.start.<anonymous closure> (package:test/src/runner/remote_listener.dart:69:33)
  #16     _rootRun (dart:async/zone.dart:1126:13)
  #17     _CustomZone.run (dart:async/zone.dart:1023:19)
  #18     runZoned (dart:async/zone.dart:1501:17)
  #19     SuiteChannelManager.asCurrent (package:test/src/runner/suite_channel_manager.dart:34:31)
  #20     RemoteListener.start (package:test/src/runner/remote_listener.dart:68:31)
  #21     serializeSuite (package:test/src/runner/plugin/remote_platform_helpers.dart:34:20)
  #22     main (data:application/dart;charset=utf-8,%20%20%20%20import%20%22dart:isolate%22;%0A%0A%20%20%20%20import%20%22package:stream_channel/stream_channel.dart%22;%0A%0A%20%20%20%20import%20%22package:test/src/runner/plugin/remote_platform_helpers.dart%22;%0A%20%20%20%20import%20%22package:test/src/runner/vm/catch_isolate_errors.dart%22;%0A%0A%20%20%20%20import%20%22[...]/issue_33120/test.dart%22%20as%20test;%0A%0A%20%20%20%20void%20main(_,%20SendPort%20message)%20%7B%0A%20%20%20%20%20%20var%20channel%20=%20serializeSuite(()%20%7B%0A%20%20%20%20%20%20%20%20catchIsolateErrors();%0A%20%20%20%20%20%20%20%20return%20test.main;%0A%20%20%20%20%20%20%7D);%0A%20%20%20%20%20%20new%20IsolateChannel.connectSend(message).pipe(channel);%0A%20%20%20%20%7D%0A%20%20:11:21)
  #23     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:275:32)
  #24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
  error: error evaluating constant constructor
  test.dart 18:7  main
  ===== asynchronous gap ===========================
  package:test    serializeSuite
  data:... 11:21  main
  
00:01 +0 -1: Some tests failed.
```

**Comment by matanlurey** [comment]
Thanks @jensjoha!

**Comment by jensjoha** [comment]
So what happens is this:

If you from the command line try to run with both `--preview-dart-2` and `--checked` you are told that `Flags --checked and --preview-dart-2 are not compatible.`.

If you do it from code though it's perfectly happy to comply. As such, an example without package:test that basically does the same thing:

```
import 'dart:io';
import 'dart:isolate';

main(List<String> args) async {
  if (args.isEmpty) {
    await spawnAndListen();
  } else {
    new Foo();
  }
}

void spawnAndListen() async {
  Isolate isolate =
      await Isolate.spawnUri(Platform.script, ["spawned!"], "", checked: true);
  RawReceivePort port;
  void handler(message) {
    if (message != null) {
      print(message[0]);
    }
    port.close();
  }

  port = new RawReceivePort(handler);
  isolate.addErrorListener(port.sendPort);
  isolate.addOnExitListener(port.sendPort);
}

Iterable<Map<K, V>> qux<K, V>(List<Map<K, V>> quux) {
  return quux;
}

typedef Iterable<Map<K, V>> Baz<K, V>(List<Map<K, V>> quux);

class Bar {
  final Baz baz;
  const Bar({this.baz: qux});
}

class Foo {
  final Bar bar;
  Foo({this.bar: const Bar()});
}
```

notice the `checked: true`.

In total it basically boils down to this getting added to the flowgraph:
```
    t2 <- LoadLocal(:temp1 @-9)
    t2 <- Constant(#null)
    t2 <- Constant(#null)
    AssertAssignable:76(t2, Function Type: (dynamic, List<Map<dynamic, dynamic>>) => Iterable<Map<dynamic, dynamic>>, 'baz', instantiator_type_args(t2), function_type_args(t2))
```

and the AssertAssignable then saying no...

**Comment by mraleph** [comment]
Regis, would you have a moment to look at this? It seems that we need to change `Isolate.spawnUri(..., checked: true)` to only enable asserts if we are spawning an isolate in Dart 2 mode.

**Comment by a-siva** [comment]
I can do that Regis, let me take this issue over.
