### ISSUE TITLE
Missing source position in Kernel

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#33155]
I think I stumbled upon a missing source position.  You can't reproduce this directly without patching in some of my changes, but this should be enough:

```
Crash when compiling package:front_end/src/fasta/builder/metadata_builder.dart,
at character offset null:
type 'UnresolvedType<TypeBuilder>' is not a subtype of type 'UnresolvedType<KernelTypeBuilder>' of 'type'
#0      DeclarationBuilder.addType (package:front_end/src/fasta/source/source_library_builder.dart)
#1      KernelLibraryBuilder.copyTypeVariables (package:front_end/src/fasta/kernel/kernel_library_builder.dart:980:19)
#2      KernelLibraryBuilder.addFactoryMethod (package:front_end/src/fasta/kernel/kernel_library_builder.dart:617:11)
#3      OutlineBuilder.endFactoryMethod (package:front_end/src/fasta/source/outline_builder.dart:1135:13)
#4      Parser.parseFactoryMethod (package:front_end/src/fasta/parser/parser.dart:3462:14)
#5      Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3203:19)
#6      Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3101:15)
#7      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1700:13)
```

`DeclarationBuilder.addType` looks like:

```dart
  void addType(UnresolvedType<T> type) {
    types.add(type);
  }
```

and compiled to:

```dart
  method addType(generic-covariant-impl unr::UnresolvedType<self::DeclarationBuilder::T> type) → void {
    this.{self::DeclarationBuilder::types}.{core::List::add}(type);
  }
```

**Comment by jensjoha** [comment]
For the first one at least it originates in the catch in https://github.com/dart-lang/sdk/blob/87131780cb16a10edc925aaf8c1b1c8a4580c96c/pkg/front_end/lib/src/fasta/kernel/kernel_target.dart#L264-L266 and doesn't pass a source position. I don't think it's fair to say it has anything to do with kernel though. It's internal to fasta.
