### ISSUE TITLE
Crash in dart2js on illegal initializer

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#33157]
After https://dart-review.googlesource.com/c/sdk/+/55660 dart2js crashes on `co19/Language/Classes/Constructors/Generative_Constructors/initializers_t12`:

```
The compiler crashed: 'file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/kernel/env.dart': Failed assertion: line 395 pos 16: '!name.contains('#')': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
#1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
#2      ClassEnvImpl._ensureMaps.addProcedures (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/kernel/env.dart:395:16)
#3      ClassEnvImpl._ensureMaps (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/kernel/env.dart:433:18)
#4      ClassEnvImpl.forEachMember (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/kernel/env.dart:477:5)
#5      KernelToElementMapBase._forEachClassMember (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:761:9)
#6      KernelElementEnvironment.forEachClassMember (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:1599:16)
#7      ResolutionWorldBuilderBase.processClassMembers (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/universe/resolution_world_builder.dart:786:25)
#8      ResolutionEnqueuer._applyClassUse (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/enqueue.dart:296:21)
#9      ResolutionWorldBuilderBase._processInstantiatedClass.processClass (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/universe/resolution_world_builder.dart:772:18)
#10     ResolutionWorldBuilderBase._processInstantiatedClass (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/universe/resolution_world_builder.dart:778:39)
#11     ResolutionWorldBuilderBase.registerTypeInstantiation (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/universe/resolution_world_builder.dart:544:7)
#12     ResolutionEnqueuer._registerInstantiatedType.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/enqueue.dart:254:21)
#13     CompilerTask.measure (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#14     ResolutionEnqueuer._registerInstantiatedType (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/enqueue.dart:253:10)
#15     ResolutionEnqueuer.processStaticUse (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/enqueue.dart:332:9)
#16     TreeShakingEnqueuerStrategy.processStaticUse (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/enqueue.dart:557:14)
#17     EnqueuerImplImpactVisitor.visitStaticUse (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/enqueue.dart:605:23)
#18     Setlet.forEach (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/util/setlet.dart:229:39)
#19     TransformedWorldImpact.apply (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/universe/world_impact.dart:280:16)
#20     JavaScriptImpactStrategy.visitImpact (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/js_backend/backend.dart:1115:16)
#21     ResolutionEnqueuer.applyImpact (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/enqueue.dart:243:20)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:475:28)
#23     CompilerTask.measureSubtask (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#24     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:474:28)
#25     CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:802:15)
#26     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:472:18)
#27     EnqueuerStrategy.processWorkItem (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/enqueue.dart:537:6)
#28     ResolutionEnqueuer._forEach (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/enqueue.dart:411:20)
#29     ResolutionEnqueuer.forEach (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/enqueue.dart:428:5)
#30     Compiler.emptyQueue.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:468:16)
#31     CompilerTask.measureSubtask (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#32     Compiler.emptyQueue (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:467:14)
#33     Compiler.processQueue.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:489:7)
#34     CompilerTask.measureSubtask (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#35     Compiler.processQueue (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:486:14)
#36     Compiler.compileLoadedLibraries.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:355:9)
#37     CompilerTask.measureSubtask (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#38     Compiler.compileLoadedLibraries (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:319:16)
#39     Compiler.runInternal (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:297:5)
<asynchronous suspension>
#40     Compiler.run.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:217:38)
#41     new Future.sync (dart:async/future.dart:222)
#42     Compiler.run.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:217:20)
#43     CompilerTask.measureSubtask (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#44     Compiler.run (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/compiler.dart:214:41)
#45     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/compiler/lib/src/apiimpl.dart:150:25)
#46     _RootZone.runUnary (dart:async/zone.dart:1381)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#49     Future._propagateToListeners (dart:async/future_impl.dart:662)
#50     Future._completeWithValue (dart:async/future_impl.dart:477)
#51     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#54     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```
This could be some invalid kernel generated by Fasta or a bug in dart2js.

**Comment by danrubel** [comment]
This occurs during parser recovery and should be fixed by https://dart-review.googlesource.com/c/sdk/+/63180
Please re-open if this is still a problem.
