### ISSUE TITLE
dart2js_developer crashes on Hacker News app

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#33162]
I think the issue is related to generic types on JS-interop classes.
```
$ sdk/bin/dart2js_developer ~/hn0/third_party/dart/angular_hn/web/main.dart
../../hn0/third_party/dart/angular_hn/packages/service_worker/src/js_facade/promise.dart:21:21:
Internal Error: The compiler crashed when compiling this element.
  external Thenable then([ResolveFn<T> resolveFn, RejectFn rejectFn]);
                    ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: 'file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/native/enqueue.dart': Failed assertion: line 132 pos 16: 'type is VoidType': Thenable.T was TypeVariableType
#0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
#1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
#2      NativeEnqueuerBase._processNativeBehavior (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/native/enqueue.dart:132:16)
#3      NativeEnqueuerBase.registerNativeBehavior (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/native/enqueue.dart:83:5)
#4      JavaScriptImpactTransformer.transformResolutionImpact (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/impact_transformer.dart:287:33)
#5      KernelWorkItem.run.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/kernel/kernel_strategy.dart:229:32)
#6      CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#7      KernelWorkItem.run.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/kernel/kernel_strategy.dart:226:28)
#8      CompilerTask.measure (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#9      KernelWorkItem.run (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/kernel/kernel_strategy.dart:218:26)
#10     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:469:70)
#11     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#12     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:469:32)
#13     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#14     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:467:28)
#15     CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:795:15)
#16     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:465:18)
#17     EnqueuerStrategy.processWorkItem (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/enqueue.dart:537:6)
#18     ResolutionEnqueuer._forEach (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/enqueue.dart:411:20)
#19     ResolutionEnqueuer.forEach (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/enqueue.dart:428:5)
#20     Compiler.emptyQueue.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:461:16)
#21     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#22     Compiler.emptyQueue (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:460:14)
#23     Compiler.processQueue.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:482:7)
#24     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#25     Compiler.processQueue (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:479:14)
#26     Compiler.compileLoadedLibraries.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:348:9)
#27     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#28     Compiler.compileLoadedLibraries (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:312:16)
#29     Compiler.runInternal (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:290:5)
<asynchronous suspension>
#30     Compiler.run.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:216:38)
#31     new Future.sync (dart:async/future.dart:222)
#32     Compiler.run.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:216:20)
#33     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#34     Compiler.run (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:213:41)
#35     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/apiimpl.dart:149:25)
#36     _RootZone.runUnary (dart:async/zone.dart:1381)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#39     Future._propagateToListeners (dart:async/future_impl.dart:662)
#40     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#43     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)

```

**Comment by vsmenon** [comment]
@sigmundch @rakudrama - is someone looking at this?

**Comment by rakudrama** [comment]
@johnniwinther Was https://dart-review.googlesource.com/c/sdk/+/56665 supposed to help here?

**Comment by johnniwinther** [comment]
No. This is a different problem.

**Comment by dgrove** [comment]
Should this be moved out of PreRelease1, @rakudrama and @vsmenon ?

**Comment by rakudrama** [comment]
@johnniwinther I believe this is fixed

**Comment by johnniwinther** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/58460
