### ISSUE TITLE
service/eval_test fails in Debug mode after move to frontend expression evaluation

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#33171]
The test fails with enable_kernel_expression_compilation=true(which is default),  passes with enable_kernel_expression_compilation=false

```
╰─➤  DART_CONFIGURATION=DebugX64 pkg/vm/tool/dart2 --no-background-compilation --enable_kernel_expression_compilation=true  --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=$DH/sdk/.packages $DH/sdk/runtime/observatory/tests/service/eval_test.dart                                                                130 ↵

** Launching SERVICE_TEST_TESTEE=true $DH/sdk/pkg/vm/tool/../../../out/DebugX64/dart -DDART_SERVICE_USE_AUTH=false --profiler --preview_dart_2 --strong --reify-generic-functions --limit-ints-to-64-bits --no-background-compilation --enable_kernel_expression_compilation=true --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=$DH/sdk/.packages --enable-vm-service:0 $DH/sdk/runtime/observatory/tests/service/eval_test.dart
>testee>out> Observatory listening on http://127.0.0.1:38051/
** Signaled to run test queries on http://127.0.0.1:38051/
>testee>out> 
Loading VM...
Done loading VM
Running eval_test.dart [1/2]
Paused with PauseBreakpoint
Running eval_test.dart [2/2]
Instance(105)
Instance(1105)
>testee>err> ../../runtime/vm/class_finalizer.cc: 2636: error: expected: cls.is_type_finalized()
>testee>err> Dumping native stack trace for thread 167f5
>testee>err>   [0x0000000000b2691f] dart::Profiler::DumpStackTrace(void*)
>testee>err>   [0x0000000000b2691f] dart::Profiler::DumpStackTrace(void*)
>testee>err>   [0x0000000000da8ae2] dart::Assert::Fail(char const*, ...)
>testee>err>   [0x000000000093c4a2] dart::ClassFinalizer::FinalizeClass(dart::Class const&)
>testee>err>   [0x0000000000d51d4c] dart::Compiler::CompileClass(dart::Class const&)
>testee>err>   [0x0000000000a16e41] dart::Class::EnsureIsFinalized(dart::Thread*) const
>testee>err>   [0x0000000000a26cc8] dart::Class::LookupFunctionAllowPrivate(dart::String const&, dart::Class::MemberKind) const
>testee>err>   [0x0000000000a1f5a4] Unknown symbol
>testee>err>   [0x0000000000a72f22] dart::Instance::Evaluate(dart::Class const&, dart::String const&, dart::Array const&, dart::Array const&, dart::Array const&, dart::TypeArguments const&) const
>testee>err>   [0x0000000000a72b99] dart::Instance::Evaluate(dart::Class const&, dart::String const&, dart::Array const&, dart::Array const&) const
>testee>err>   [0x0000000000ba84ef] Unknown symbol
>testee>err>   [0x0000000000ba4fe6] dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
>testee>err>   [0x0000000000ba5aff] dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
>testee>err>   [0x00000000009c1d17] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
>testee>err>   [0x00000000009f6f35] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
>testee>err>   [0x00000000009f7464] dart::MessageHandler::HandleOOBMessages()
>testee>err>   [0x0000000000d83b8b] Dart_HandleServiceMessages
>testee>err>   [0x00000000009c9bd6] dart::Isolate::PauseEventHandler()
>testee>err>   [0x000000000098d5bf] dart::Debugger::Pause(dart::ServiceEvent*)
>testee>err>   [0x000000000099c41a] dart::Debugger::SignalPausedEvent(dart::ActivationFrame*, dart::Breakpoint*)
>testee>err>   [0x000000000099c89f] dart::Debugger::PauseStepping()
>testee>err>   [0x0000000000b8ce58] dart::DRT_SingleStepHandler(dart::NativeArguments)
>testee>err>   [0x00007fcb6d3408ec] [Stub] CallToRuntime
>testee>err>   [0x00007fcb6d340ebb] [Stub] DebugStepCheck
>testee>err>   [0x00007fcb59c83d29] MyClass.method
>testee>err>   [0x00007fcb6d341400] [Stub] DeoptimizeLazyFromReturn
>testee>err>   [0x00007fcb59c82ef3] testFunction
>testee>err>   [0x00007fcb675b6bd2] _Closure.call
>testee>err>   [0x00007fcb59c81f92] _ServiceTesteeRunner.run
>testee>err>   [0x00007fcb675b6bd2] _Closure.call
>testee>err>   [0x00007fcb675b6abe] _AsyncAwaitCompleter.start
>testee>err>   [0x00007fcb59c8166f] _ServiceTesteeRunner.run
>testee>err>   [0x00007fcb675b71b8] runIsolateTests
>testee>err>   [0x00007fcb675b6bd2] _Closure.call
>testee>err>   [0x00007fcb675b6abe] _AsyncAwaitCompleter.start
>testee>err>   [0x00007fcb675b4c2a] runIsolateTests
>testee>err>   [0x00007fcb675b3988] main
>testee>err>   [0x00007fcb675b379b] main
>testee>err>   [0x00007fcb6758ce95] _Closure.call
>testee>err>   [0x00007fcb675b2843] _startIsolate.<anonymous closure>
>testee>err>   [0x00007fcb6758ce95] _Closure.call
>testee>err>   [0x00007fcb675b24dc] _RawReceivePortImpl._handleMessage
>testee>err>   [0x00007fcb6d340df6] [Stub] InvokeDartCode
>testee>err>   [0x0000000000987119] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
>testee>err>   [0x0000000000989d49] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
>testee>err>   [0x00000000009c1d7c] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
>testee>err>   [0x00000000009f6f35] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
>testee>err>   [0x00000000009f7a9c] dart::MessageHandler::TaskCallback()
>testee>err>   [0x0000000000be4717] dart::ThreadPool::Worker::Loop()
>testee>err>   [0x0000000000be4452] dart::ThreadPool::Worker::Main(unsigned long)
>testee>err>   [0x0000000000ac7455] Unknown symbol
>testee>err> -- End of DumpStackTrace
** Killing script
Unexpected exception in service tests: NetworkRpcException(Canceling request: WebSocket closed(id: 24 method: evaluate params: {targetId: objects/int-10000, expression: this + 5, isolateId: isolates/664125762}))
#0      tests.<anonymous closure> (file://$DH/sdk/runtime/observatory/tests/service/eval_test.dart:63:14)
<asynchronous suspension>
#1      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file://$DH/sdk/runtime/observatory/tests/service/test_helper.dart:331:23)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:477:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507:7)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

Unhandled exception:
NetworkRpcException(Canceling request: WebSocket closed(id: 24 method: evaluate params: {targetId: objects/int-10000, expression: this + 5, isolateId: isolates/664125762}))
#0      tests.<anonymous closure> (file://$DH/sdk/runtime/observatory/tests/service/eval_test.dart:63:14)
<asynchronous suspension>
#1      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file://$DH/sdk/runtime/observatory/tests/service/test_helper.dart:331:23)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:477:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507:7)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

```

**Comment by dgrove** [comment]
@aam I am assuming that you need this fairly soon, hence the milestone.
