### ISSUE TITLE
Issue with Dart analysis server

### ISSUE THREAD

**Issue by karanvb** [dart-lang/sdk#33193]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4720617`
- `2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c`
- `AI-173.4720617, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\KARANV~1\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c, server version 1.20.0, error: Analysis failed: D:\FlutterProjects\udacity-course-master\course\02_category_widget\task_02_category_widget\lib\main.dart
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ApiSignature.addBytes (package:front_end/src/base/api_signature.dart:73)
#2      Iterable.forEach (dart:core/iterable.dart:292)
#3      FileState.transitiveSignature (package:analyzer/src/dart/analysis/file_state.dart:385)
#4      AnalysisDriver._getResolvedUnitSignature (package:analyzer/src/dart/analysis/driver.dart:1488)
#5      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1160)
<asynchronous suspension>
#6      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:987)
<asynchronous suspension>
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1925)
<asynchronous suspension>
#8      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1868)
#9      new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#10

**Comment by bwilkerson** [comment]
@scheglov

**Comment by bwilkerson** [comment]
Is there a way for us to detect damaged bundles and gracefully recover (by automatically removing the bundle and re-generating it, for example)?

**Comment by scheglov** [comment]
I have a [CL that adds CRC32](https://dart-review.googlesource.com/c/sdk/+/3700) to every object we put into the `ByteStore`. We postponed it in hope that resolving race between Analysis Server and Angular plugin will solve the cache damaging issue, but it seems that the issue persists. Less radical solution could be reading unlinked bundles from loaded bytes in try/catch and ignoring if it fail to read some initial data. But this will not protect against other kinds of data - linked bundles and resolved results. So, I will revive this CRC32 CL, even though it has some performance cost.
