### ISSUE TITLE
Keeps crashing - gives this error in amost all .dart files -> error: Required library 'dart:async' is missing. (missing_dart_library at [myapp] lib\Components\app_component.dart:1)

### ISSUE THREAD

**Issue by manuelgomes2** [dart-lang/sdk#33219]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4720617`
- `2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c`
- `AI-173.4720617, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://D:\temp1\report1.txt

```
Dart analysis server, SDK version 2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c, server version 1.20.2, FATAL error: Failed to handle request: {id: 9, method: edit.getFixes, params: {file: E:\theService\theservice_mobileapp\the_service\lib\Components\app_component.dart, offset: 0}, clientRequestTime: 1527116263127}
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      new FixProcessor (package:analysis_server/src/services/correction/fix_internal.dart:152)
#2      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:85)
<asynchronous suspension>
#3      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:529)
<asynchronous suspension>
#4      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:228)
<asynchronous suspension>
#5      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:332)
#6      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:722)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#8      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:718)
#9      _rootRun (dart:async/zone.dart:1126)

**Comment by manuelgomes2** [comment]
Changed channel to "dev" channel, updated, and the problem disappeared - so, is the beta channel broken?
