### ISSUE TITLE
errors thrown by constant evaluator are unreadable

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#33216]
```dart
 class B {
   const B(int v);
 }

 const dynamic c = "";

 void foo([x = const B(c)]) { }

 void main() {
   foo();
 }
```

results in 

```shell
$ out/ReleaseX64/dart --preview-dart-2 /tmp/error.dart
Unhandled exception:
'file:///tmp/error.dart': error: Not a constant expression:  is not an instance of Type: class 'int'
#0      main (file:///tmp/error.dart:11:3)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Not that the top-most frame does not actually point to the location of the type error - it points to the invocation of `foo` within the `main`.

The type error itself is very different from how VM reports other similar type errors.

Other cases: 

```dart
 class A {
   const A(int v);
 }

 class C {
   const C(int v);
 }

 class B extends C {
   const B._(v) : super(v);

   const B(v) : this._(v);
 }

 const dynamic c = "";

 void foo([x = const B(c)]) { }

 void main() {
   foo();
 }
```

produces unreadable (notice double "Unhandled exception" and no location information on frame `#1`)

```shell
$ out/ReleaseX64/dart --preview-dart-2 /tmp/error.dart
Unhandled exception:
Unhandled exception:
type 'String' is not a subtype of type 'int'
#0      new B._ (file:///tmp/error.dart:11:24)
#1      new B (file:///tmp/error.dart)
#2      main (file:///tmp/error.dart:21:3)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
error: error evaluating constant constructor
#0      main (file:///tmp/error.dart:21:3)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

while 

```dart
class A {
   const A(int v);
 }

 class C {
   const C(int v);
 }

 class B extends C {
   const B._(v, {x: const C(c)}) : super(v);

   const B(v) : this._(v);
 }

 const dynamic c = "";

 void foo([x = const B(c)]) { }

 void main() {
   foo();
 }
```

produces 

```shell
$ out/ReleaseX64/dart --preview-dart-2 /tmp/error.dart
Unhandled exception:
Unhandled exception:
'file:///tmp/error.dart': error: Not a constant expression:  is not an instance of Type: class 'int'
#0      new B (file:///tmp/error.dart)
#1      main (file:///tmp/error.dart:21:3)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
error: error evaluating constant constructor
#0      main (file:///tmp/error.dart:21:3)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by mraleph** [comment]
@kmillikin please select priority

**Comment by kmillikin** [comment]
I don't think there's anything we need to put in Kernel for the VM to generate a better error.  @a-siva can you reassign to someone on the VM team?  (Also, consider whether this is in scope for Dart2Stable.)

If it turns out we need to change something in Kernel, let us know.

**Comment by jensjoha** [comment]
With https://dart-review.googlesource.com/c/sdk/+/63883 I get

```
Unhandled exception:
'[...]/issue_33216.dart': error: line 7 pos 24: Not a constant expression: Type 'String' is not a subtype of type 'int'
 void foo([x = const B(c)]) { }
                       ^

#0      main ([...]/issue_33216.dart:10:4)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

then
```
Unhandled exception:
Unhandled exception:
type 'String' is not a subtype of type 'int'
#0      new B._ ([...]/issue_33216.dart:10:25)
#1      new B ([...]/issue_33216.dart:12:22)
#2      main ([...]/issue_33216.dart:20:4)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
'[...]/issue_33216.dart': error: line 17 pos 22: error evaluating constant constructor
 void foo([x = const B(c)]) { }
                     ^

#0      main ([...]/issue_33216.dart:20:4)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

and finally
```
Unhandled exception:
Unhandled exception:
'[...]/issue_33216.dart': error: line 10 pos 29: Not a constant expression: Type 'String' is not a subtype of type 'int'
   const B._(v, {x: const C(c)}) : super(v);
                            ^

#0      new B ([...]/issue_33216.dart:12:22)
#1      main ([...]/issue_33216.dart:20:4)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
'[...]/issue_33216.dart': error: line 17 pos 22: error evaluating constant constructor
 void foo([x = const B(c)]) { }
                     ^

#0      main ([...]/issue_33216.dart:20:4)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Stuff like
```
Unhandled exception:
Unhandled exception:
```
might not be great, but `--no-preview-dart-2 --checked` does that too.

**Comment by dgrove** [comment]
After talking with @kevmoo:
  - Dart Analyzer messages are fine for these cases
  - Dart VM messages are not too bad (given @jensjoha 's report)

Moving to Dart 2.1

**Comment by a-siva** [comment]
The error messages reported by Dart VM after the changes made by @jensjoha are consistent with what was being generated by Dart 1.
I would close this and open a new enhancement issue with more details on generating consistent error messages across the different tools.

**Comment by a-siva** [comment]
See comment above, I believe this issue can be closed unless somebody disagrees with that.
