### ISSUE TITLE
Missing position information on redirecting constructors

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#33217]
```dart
class C {
   C(int v) {
     throw 'Error';
   }
 }

 class B extends C {
   B._(v) : super(v);
   B(v) : this._(v);
 }

 void main() {
   new B("");
 }
```

results in 

```
$ out/ReleaseX64/dart --preview-dart-2 /tmp/error.dart
Unhandled exception:
type 'String' is not a subtype of type 'int'
#0      new B._ (file:///tmp/error.dart:10:18)
#1      new B (file:///tmp/error.dart)
#2      main (file:///tmp/error.dart:15:7)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Note that frame `#1` misses position information.

**Comment by mraleph** [comment]
@kmillikin please select priority

**Comment by srawlins** [comment]
This has been fixed:

```
$ dart 33217.dart 
Unhandled exception:
type 'String' is not a subtype of type 'int'
#0      new B._ (file:///Users/srawlins/code/dart-sdk/sdk/33217.dart:8:18)
#1      new B (file:///Users/srawlins/code/dart-sdk/sdk/33217.dart:9:15)
#2      main (file:///Users/srawlins/code/dart-sdk/sdk/33217.dart:13:7)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
