### ISSUE TITLE
strong mode issue when computing outlines

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33228]
When the analysis server runs on a strong mode VM, I see:

```
Dart analysis server, SDK version 2.0.0-edge.ba0da68563fb466967d72acb9c7e426b9806a150, server version 1.20.3, error: Failed to send notification
type 'ParameterElementImpl' is not a subtype of type 'ExecutableElement'
#0      _FunctionBodyOutlinesVisitor.visitMethodInvocation (package:analysis_server/src/computer/computer_outline.dart:416:59)
#1      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871:49)
#2      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4325:18)
#3      RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:815:10)
#4      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4321:49)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263:20)
#6      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1353:17)
#7      RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:647:10)
#8      BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1349:49)
#9      IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6120:21)
#10     RecursiveAstVisitor.visitIfStatement (package:analyzer/dart/ast/visitor.dart:911:10)
#11     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:6114:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263:20)
```

**Comment by devoncarew** [comment]
@scheglov, do you mind taking a look?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/56625

**Comment by devoncarew** [comment]
(part of the fix for https://github.com/dart-lang/sdk/issues/33189#issuecomment-391807547)
