### ISSUE TITLE
Error on win 7 x64 

### ISSUE THREAD

**Issue by Munster999** [dart-lang/sdk#33233]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4720617`
- `2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c`
- `AI-173.4720617, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080, 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Shak\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c, server version 1.20.0, FATAL error: Failed to handle request: {id: 4419, method: edit.getFixes, params: {file: K:\FlutterProjects\make_it_rain\lib\main.dart, offset: 47}, clientRequestTime: 1527245752745}
NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FileSystemState.hasUri (package:analyzer/src/dart/analysis/file_state.dart:863)
#2      AnalysisDriver.getResult (package:analyzer/src/dart/analysis/driver.dart:745)
#3      AnalysisSessionImpl.getResolvedAst (package:analyzer/src/dart/analysis/session.dart:97)
#4      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:51)
<asynchronous suspension>
#5      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:66)
<asynchronous suspension>
#6      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:47)
#7      FixProcessor._addFix_createImportUri (package:analysis_server/src/services/correction/fix_int

**Comment by scheglov** [comment]
I think https://dart-review.googlesource.com/c/sdk/+/73242 fixes this, at least the symptom.
