### ISSUE TITLE
Analyzer throwing an error in angular project after upgrading to Dart 2.0.0-dev.58.0

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#33231]
Upgrading to Dart 2.0.0-dev.58.0 causes the analyzer to produce a weird message when running `dartanalyzer .` on our project.

We haven't determined what we are doing in our angular app to cause this yet.  This error does not get thrown on a boilerplate AngularDart 5.0.0-alpha+8 project.
```
Unhandled exception:
NoSuchMethodError: The getter 'isEmpty' was called on null.
Receiver: null
Tried calling: isEmpty
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      PropertyAccessorMember.from (package:analyzer/src/dart/element/member.dart:851:56)
#2      InterfaceTypeImpl.getGetter (package:analyzer/src/dart/element/type.dart:1781:30)
#3      InterfaceTypeImpl.lookUpGetter (package:analyzer/src/dart/element/type.dart:1983:39)
#4      InterfaceTypeImpl.lookUpInheritedGetter (package:analyzer/src/dart/element/type.dart:2025:16)
#5      ElementResolver._lookUpGetter (package:analyzer/src/generated/element_resolver.dart:1783:19)
#6      ElementResolver._resolveProperty (package:analyzer/src/generated/element_resolver.dart:2362:23)
#7      ElementResolver._resolvePropertyAccess (package:analyzer/src/generated/element_resolver.dart:2392:23)
#8      ElementResolver.visitPrefixedIdentifier (package:analyzer/src/generated/element_resolver.dart:996:5)
#9      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8951:49)
#10     ResolverVisitor.visitPrefixedIdentifier (package:analyzer/src/generated/resolver.dart:6245:10)
#11     PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8951:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263:20)
#13     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:432:16)
#14     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#15     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898:45)
#16     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:5368:18)
#17     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:428:49)
#18     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6213:24)
#19     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871:49)
#20     ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:6256:18)
#21     PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:9163:49)
#22     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11346:19)
#23     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#24     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3224:59)
#25     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:7823:11)
#26     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:6370:11)
#27     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11340:49)
#28     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263:20)
#29     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11442:16)
#30     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#31     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228:7)
#32     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:6394:11)
#33     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11436:15)
#34     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11497:20)
#35     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#36     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:3232:7)
#37     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11493:15)
#38     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263:20)
#39     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1353:17)
#40     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#41     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919:31)
#42     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7258:13)
#43     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1349:49)
#44     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1298:13)
#45     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#46     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922:55)
#47     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7270:13)
#48     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5493:13)
#49     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1294:49)
#50     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5440:12)
#51     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#52     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033:57)
#53     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7598:15)
#54     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5993:15)
#55     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5434:49)
#56     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263:20)
#57     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:432:16)
#58     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#59     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898:45)
#60     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:5368:18)
#61     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:428:49)
#62     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6213:24)
#63     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871:49)
#64     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4325:18)
#65     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#66     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3005:59)
#67     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4321:49)
#68     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263:20)
#69     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1353:17)
#70     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#71     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919:31)
#72     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7258:13)
#73     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1349:49)
#74     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1298:13)
#75     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#76     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922:55)
#77     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7270:13)
#78     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5493:13)
#79     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1294:49)
#80     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5440:12)
#81     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#82     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033:57)
#83     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7573:13)
#84     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5993:15)
#85     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5434:49)
#86     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5284:26)
#87     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6226:10)
#88     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026:59)
#89     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:7566:11)
#90     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5969:11)
#91     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7558:7)
#92     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5959:13)
#93     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5277:49)
#94     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5598:25)
#95     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2504:49)
#96     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:710:10)
#97     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:129:9)
#98     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
#99     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:128:13)
#100    LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:103:16)
<asynchronous suspension>
#101    _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:220:21)
<asynchronous suspension>
#102    LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:99:43)
<asynchronous suspension>
#103    AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1243:71)
<asynchronous suspension>
#104    PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#105    AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1202:20)
<asynchronous suspension>
#106    AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:629:43)
<asynchronous suspension>
#107    AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:133:60)
<asynchronous suspension>
#108    AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:178:11)
<asynchronous suspension>
#109    AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:109:18)
<asynchronous suspension>
#110    Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:854:21)
#111    Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:385:40)
<asynchronous suspension>
#112    Driver._analyzeAll (package:analyzer_cli/src/driver.dart:234:20)
<asynchronous suspension>
#113    Driver.start (package:analyzer_cli/src/driver.dart:203:38)
<asynchronous suspension>
#114    main (file:///tmp/tmp6cwDYx/dart-2.0.0-dev.58.0/dart/pkg/analyzer_cli/bin/analyzer.dart:13:17)
<asynchronous suspension>
#115    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#116    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1283:9)
<asynchronous suspension>
#1      PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1202:20)
<asynchronous suspension>
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:629:43)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:133:60)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:178:11)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:109:18)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:854:21)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:385:40)
<asynchronous suspension>
#9      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:234:20)
<asynchronous suspension>
#10     Driver.start (package:analyzer_cli/src/driver.dart:203:38)
<asynchronous suspension>
#11     main (file:///tmp/tmp6cwDYx/dart-2.0.0-dev.58.0/dart/pkg/analyzer_cli/bin/analyzer.dart:13:17)
<asynchronous suspension>
#12     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by johnpryan** [comment]
Here's the file that is causing the error:

```
import 'dart:io';
import 'dart:async' show Future, runZoned;
import 'package:path/path.dart' show join, dirname;
import 'package:shelf/shelf.dart' as shelf;
import 'package:shelf_route/shelf_route.dart';
import 'package:shelf/shelf_io.dart' as shelf_io;
import 'package:shelf_static/shelf_static.dart';
import 'package:shelf_gzip/shelf_gzip.dart';

Future main() async {
  await writeConfig();
  // Assumes the server lives in bin/ and that `pub build` ran
  var pathToBuild =
      join(dirname(Platform.script.toFilePath()), '..', 'build/web');

  var staticHandler = createStaticHandler(pathToBuild,
      defaultDocument: 'index.html', serveFilesOutsidePath: true);

  var portEnv = Platform.environment[Environment.port];
  var port = portEnv == null ? 9999 : int.parse(portEnv);

  var appRouter = router();

  runZoned(() async {
    var pipeline = new shelf.Pipeline();

    if (isProduction()) {
      print("in production mode: redirecting all http requests to https");
      pipeline = pipeline.addMiddleware(createHttpsOnlyMiddleware());
    } else {
      print("not in production mode: allowing http requests");
    }

    pipeline = pipeline.addMiddleware(gzipMiddleware);
    var cascade =
        new shelf.Cascade().add(staticHandler).add(appRouter.handler).handler;
    var newPipeline = pipeline.addHandler(cascade);

    await shelf_io.serve(newPipeline, '0.0.0.0', port);

    print("Serving $pathToBuild on port $port");
  }, onError: (e, stackTrace) => print('Server error: $e $stackTrace'));
}

shelf.Middleware createHttpsOnlyMiddleware() {
  return shelf.createMiddleware(requestHandler: (shelf.Request request) {
    if (request.requestedUri.scheme != "https") {
      return new shelf.Response.movedPermanently(
          request.requestedUri.replace(scheme: "https"));
    }
    return null;
  });
}

bool isProduction() {
  const envKey = "DART_ENV";
  return Platform.environment.containsKey(envKey) &&
      Platform.environment[envKey] == "production";
}

class Environment {
  static const String port = 'PORT';
  static const String environment = 'ENVIRONMENT';
  static const String environmentsHost = 'ENVIRONMENTS_HOST';
}

```

**Comment by johnpryan** [comment]
Changing runZoned() from an anonymous function into a separate top-level function fixed the issue.

**Comment by johnpryan** [comment]
[report.txt](https://github.com/dart-lang/sdk/files/2055311/report.txt)
attached is the full analyzer report

**Comment by johnpryan** [comment]
I think this is stale.
