### ISSUE TITLE
Analyzer Error

### ISSUE THREAD

**Issue by kostaa** [dart-lang/sdk#33245]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-181.5087.20`
- `2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c`
- `IC-181.5087.20, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1680x1050`

```
Dart analysis server, SDK version 2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c, server version 1.20.2, error: Analysis failed: D:\repo__at\_moneyvore_rdx\lib\lib_widgets\loading.dart context: exception_20180526_170645_075
RangeError (byteOffset): Invalid value: Not in range 0..30968, inclusive: 31074
#0      _ByteDataView.getUint32 (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:4268)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:68)
#2      BufferContext.derefObject (package:front_end/src/base/flat_buffers.dart:54)
#3      ListReader.read (package:front_end/src/base/flat_buffers.dart:600)
#4      Reader.vTableGet (package:front_end/src/base/flat_buffers.dart:640)
#5      _LinkedUnitImpl.types (package:analyzer/src/summary/format.dart:3879)
#6      new _UnitResynthesizer (package:analyzer/src/summary/resynthesize.dart:1207)
#7      _LibraryResynthesizer.createUnitResynthesizer (package:analyzer/src/summary/resynthesize.dart:752)
#8      _LibraryResynthesizer.buildLibrary (package:analyzer/src/summary/resynthesize.dart:688)
#9      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:352)
#10     _HashVMBase

**Comment by scheglov** [comment]
We started adding CRC32 (later replaced with something lighter) do data in analysis cache.
https://dart-review.googlesource.com/c/sdk/+/3700

I think this helped, I don't see a lot of similar reports anymore.
