### ISSUE TITLE
75a75263d35d998834ebccb319f18ab7e4877e5d Blocking Dart SDK Roll

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#33242]
Dart SDK roll into Flutter is blocked by failures caused by the following commit:

```
75a75263d35d998834ebccb319f18ab7e4877e5d is the first bad commit
commit 75a75263d35d998834ebccb319f18ab7e4877e5d
Author: Kevin Millikin <kmillikin@google.com>
Date:   Thu May 24 15:59:54 2018 +0000

    Clone annotations when cloning nodes that have them

    Annotations were not cloned.

    Fixes https://github.com/dart-lang/sdk/issues/33099

    Change-Id: I2d2b2153be9efcf1be4b39815eb8ac15b7cacd38
    Reviewed-on: https://dart-review.googlesource.com/56494
    Reviewed-by: Dmitry Stefantsov <dmitryas@google.com>
    Commit-Queue: Kevin Millikin <kmillikin@google.com>

:040000 040000 84f727925c06e779c8cc1e71aa9d5709a6db41b9 c0b7ccf31492c8a660924376cf5dd4ea78a70796 M      pkg
```

Partial stacktrace:

```
00:16 +117: /home/travis/build/flutter/flutter sdk/packages/flutter/test/cupertino/scrollbar_paint_test.dart: - Paints iOS spec
The following TestFailure object was thrown running a test:
  Expected: Object or closure painting: 'a rounded rectangle with Color(0x99777777),
  RRect.fromLTRBR(795.0, 4.0, 797.5, 86.0, 1.3)'
  Actual: ?:<exactly one widget with type "CupertinoScrollbar" (ignoring offstage widgets):
  CupertinoScrollbar(state: _CupertinoScrollbarState#d8c59(tickers: tracking 1 ticker))>
   Which: threw the following exception:
          '': error: native function 'Canvas_translate' (3 arguments) cannot be found
          #0      _GlowingOverscrollIndicatorPainter._paintSide (package:flutter/src/widgets/overscroll_indicator.dart:493:16)
          #1      _GlowingOverscrollIndicatorPainter.paint (package:flutter/src/widgets/overscroll_indicator.dart:518:5)
          #2      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:520:13)
          #3      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:563:7)
          #4      TestRecordingPaintingContext.paintChild (file:///home/travis/build/flutter/flutter%20sdk/packages/flutter/test/rendering/recording_canvas.dart:102:11)
          #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:127:15)
          #6      TestRecordingPaintingContext.paintChild (file:///home/travis/build/flutter/flutter%20sdk/packages/flutter/test/rendering/recording_canvas.dart:102:11)
          #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:127:15)
          #8      TestRecordingPaintingContext.paintChild (file:///home/travis/build/flutter/flutter%20sdk/packages/flutter/test/rendering/recording_canvas.dart:102:11)
          #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:127:15)
          #10     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:561:11)
          #11     TestRecordingPaintingContext.paintChild (file:///home/travis/build/flutter/flutter%20sdk/packages/flutter/test/rendering/recording_canvas.dart:102:11)
          #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:127:15)
          #13     _evaluatePainter (file:///home/travis/build/flutter/flutter%20sdk/packages/flutter/test/rendering/mock_canvas.dart:501:20)
          #14     _TestRecordingCanvasMatcher.matches (file:///home/travis/build/flutter/flutter%20sdk/packages/flutter/test/rendering/mock_canvas.dart:518:12)
          #15     _expect (package:test/src/frontend/expect.dart:155:17)
          #16     expect (package:test/src/frontend/expect.dart:69:3)
```

PR: https://github.com/flutter/flutter/pull/17913 
Travis: https://travis-ci.org/flutter/flutter/jobs/383847021

**Comment by tvolkert** [comment]
Does `75a75263d35d998834ebccb319f18ab7e4877e5d` revert cleanly?

**Comment by aam** [comment]
It does https://dart-review.googlesource.com/#/c/sdk/+/56722
