### ISSUE TITLE
Another Analyzer Error

### ISSUE THREAD

**Issue by kostaa** [dart-lang/sdk#33253]
This is the third analyzer error that I have raised over the last couple of days.  I have tried several Flutter/Dart versions but they all seem to have some kind of analyzer related problems. Or is this an InteliJ plugin issue? Any workarounds for this or proved working version that I could use?  

Analyzer Feedback from IntelliJ

### Version information

- `IDEA IC-181.5087.20`
- `2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822`
- `IC-181.5087.20, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1680x1050`

```
Dart analysis server, SDK version 2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822, server version 1.20.3, error: Analysis failed: D:\repo__at\_moneyvore_rdx\lib\wgt_payee\payee_editor.dart context: exception_20180528_084107_642
Element mismatch in D:\repo__at\_moneyvore_rdx\lib\wgt_payee\payee_editor.dart at D:\repo__at\_moneyvore_rdx\lib\wgt_payee\payee_editor.dart
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:74)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:682)
#2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:129)
#3      _HashVMBase

**Comment by kostaa** [comment]
And here is one more - different one from the above.
```
Dart analysis server, SDK version 2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822, server version 1.20.3, error: NoSuchMethodError: The getter 'units' was called on null.
Receiver: null
Tried calling: units
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      LibraryElementInDependency._makeUnitElement (package:analyzer/src/summary/link.dart:4054:46)
#2      LibraryElementForLink.units (package:analyzer/src/summary/link.dart:3859:9)
#3      LibraryElementForLink.getContainedName.<anonymous closure> (package:analyzer/src/summary/link.dart:3898:34)
#4      _HashVMBase
