### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#33279]
### What I was doing

I was opening flutter in vscode

### Request

While responding to request: `analysis.setAnalysisRoots`

### Versions

- Dart SDK 2.0.0-edge.fe606f890b0a311da802c78b0af414a3c2087a79
- Flutter SDK 0.5.1-pre.19
- Visual Studio Code 1.23.1
- Dart Code 2.12.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
~/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.12.1
```

### Exception

NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName

```text
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      PluginWatcher._getSdkPath (package:analysis_server/src/plugin/plugin_watcher.dart:101)
#2      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:53)
#3      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:1883)
#4      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:369)
#5      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:194)
#6      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1194)
#7      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1139)
#8      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1179)
#9      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:757)
#10     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:894)
#11     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:340)
#12     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:265)
#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:722)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#15     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:718)
#16     _rootRun (dart:async/zone.dart:1126)
#17     _CustomZone.run (dart:async/zone.dart:1023)
#18     runZoned (dart:async/zone.dart:1490)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:717)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#24     _rootRunUnary (dart:async/zone.dart:1134)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#36     _rootRunUnary (dart:async/zone.dart:1134)
#37     _CustomZone.runUnary (dart:async/zone.dart:1031)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#49     _rootRunUnary (dart:async/zone.dart:1134)
#50     _CustomZone.runUnary (dart:async/zone.dart:1031)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#54     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#55     _StreamController._add (dart:async/stream_controller.dart:639)
#56     _StreamController.add (dart:async/stream_controller.dart:585)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
#58     _rootRunUnary (dart:async/zone.dart:1138)
#59     _CustomZone.runUnary (dart:async/zone.dart:1031)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#63     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#64     _StreamController._add (dart:async/stream_controller.dart:639)
#65     _StreamController.add (dart:async/stream_controller.dart:585)
#66     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#67     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
#68     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#69     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#70     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

Diagnostics requested after the error occurred are:

```js
[]
```

**Comment by bwilkerson** [comment]
@scheglov The code where the exception is being thrown is:
```
String _getSdkPath(AnalysisDriver driver) {
  String sdkRoot = driver.sourceFactory.forUri('dart:core').fullName;
  ...
}
```
which means that the problem is a driver whose source factory cannot resolve the location of `dart:core`. Is there a reasonable situation in which that would be expected?

**Comment by scheglov** [comment]
I have not seen it myself, but I think it might be a transient state during Dart SDK update during `flutter upgrade`. If Dart SDK was deleted while we were trying to read `libraries.dart` from it.

**Comment by a14n** [comment]
After some cleanup by removing `flutter/bin/cache` the issue does not appear anymore.

Feel free to close.
