### ISSUE TITLE
dartk reload tests are timing out on simulators

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#33291]
This blocks #33126.

Tests time out after 4 (16 in  debug mode) mins:
```
Running "vm" command: DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --preview-dart-2 --hot-reload-test-mode --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/xcodebuild/DebugSIMDBC64/generated_compilations/dartk-strong/tests_corelib_2_apply_generic_function_test/out.dill
Running "vm_compile_to_kernel" command: DART_CONFIGURATION=DebugSIMDBC64 DART_VM_FLAGS=--limit-ints-to-64-bits /b/s/w/ir/cache/builder/sdk/pkg/vm/tool/gen_kernel --no-aot --strong-mode --sync-async --platform=xcodebuild/DebugSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/cache/builder/sdk/xcodebuild/DebugSIMDBC64/generated_compilations/dartk-strong/tests_corelib_2_bigint_parse_radix_test/out.dill /b/s/w/ir/cache/builder/sdk/tests/corelib_2/bigint_parse_radix_test.dart
Running "vm" command: DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --preview-dart-2 --hot-reload-test-mode --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/xcodebuild/DebugSIMDBC64/generated_compilations/dartk-strong/tests_corelib_2_bigint_from_test/out.dill
FAILED: dartk-vm debug_simdbc64 corelib_2/apply4_test
Expected: Pass
Actual: Timeout
--- Command "vm_compile_to_kernel" (took 276ms):
DART_CONFIGURATION=DebugSIMDBC64 DART_VM_FLAGS=--limit-ints-to-64-bits /b/s/w/ir/cache/builder/sdk/pkg/vm/tool/gen_kernel --no-aot --strong-mode --sync-async --platform=xcodebuild/DebugSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/cache/builder/sdk/xcodebuild/DebugSIMDBC64/generated_compilations/dartk-strong/tests_corelib_2_apply4_test/out.dill /b/s/w/ir/cache/builder/sdk/tests/corelib_2/apply4_test.dart
exit code:
0
--- Command "vm" (took 16:05.000047s):
DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --preview-dart-2 --hot-reload-test-mode --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/xcodebuild/DebugSIMDBC64/generated_compilations/dartk-strong/tests_corelib_2_apply4_test/out.dill
exit code:
-15
```

There is this recurring error in the logs:
```
stderr:
kernel-service: Error: Unhandled exception:
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      new Uint8List.fromList (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:2196)
#2      MemoryFileSystemEntity.writeAsBytesSync (package:front_end/src/api_prototype/memory_file_system.dart:111)
#3      _buildFileSystem (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:439)
#4      lookupOrBuildNewIncrementalCompiler (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:205)
<asynchronous suspension>
#5      _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:365)
<asynchronous suspension>
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

Full logs:
https://logs.chromium.org/v/?s=dart%2Fled%2Fathom_google.com%2Fb5abdd97a2554229ecd583fb570c5c4615c3b1508ea60c794593946861fb4bb3%2F%2B%2Fsteps%2Fvm_tests%2F0%2Fstdout
https://logs.chromium.org/v/?s=dart%2Fled%2Fathom_google.com%2Fcb93f06bb1deca86f955f2d5491dc4ea60e41074f321bdb948829adc8d7ed3d8%2F%2B%2Fsteps%2Fvm_tests%2F0%2Fstdout

**Comment by a-siva** [comment]
@athomas is it possible to add a TryJob option in the CQ for the hot-reload bot on macos, so I can try it out

**Comment by athomas** [comment]
@a-siva Done, it will ~15mins before they show up. You might have to refresh your browser to see them in Gerrit.

**Comment by mit-mit** [comment]
@a-siva who's looking at this one?
