### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by seasbary** [dart-lang/sdk#33305]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-172.4343.25`
- `1.24.2`
- `WS-172.4343.25, JRE 1.8.0_152-release-915-b12x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\temp\report.txt

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\WebSpace\DartDemo], excluded: [D:\WebSpace\DartDemo\.idea, D:\WebSpace\DartDemo\.pub, D:\WebSpace\DartDemo\.tmp, D:\WebSpace\DartDemo\build, D:\WebSpace\DartDemo\temp, D:\WebSpace\DartDemo\tmp]}, clientRequestTime: 1527817021420}
NoSuchMethodError: The getter 'analysisOptions' was called on null.
Receiver: null
Tried calling: analysisOptions
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ContextManagerImpl._updateContextPackageUriResolver (package:analysis_server/src/context_manager.dart:1710)
#3      ContextManagerImpl._recomputeFolderDisposition (package:analysis_server/src/context_manager.dart:1665)
#4      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1417)
#5      _rootRunUnary (dart:async/zone.dart:1128)
#6      _CustomZone.runUnary (dart:async/zone.dart:1012)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#10     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#11     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98)
#12     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)

**Comment by srawlins** [comment]
I suspect this was fixed as part of https://github.com/dart-lang/sdk/issues/27983.
