### ISSUE TITLE
VM: Very confusing error on invalid const assignment

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#33303]
The following code:

```dart
import 'package:test/test.dart';

class Provider {
  const Provider();
}

class Module {
  final List<Provider> providers;
  const Module(this.providers);
}

const aGoodModule = const Module(const [
  const Provider(),
]);

const listOfThings = const [
  const [],
  const Provider(),
];

const aBadModule = const Module(listOfThings);

void main() {
  test('$aBadModule should be invalid', () {
    expect(aBadModule.providers, const isInstanceOf<List<Provider>>());
  });
}
```

... throws the following very scary error message:

```
Unhandled exception:
'file:///Users/matanl/github/dart.scratch/dart2_const_downcast/test/dart2_const_downcast_test.dart': error: Not a constant expression: _ImmutableList len:2 is not an instance of Type: class 'List', args:[TypeArguments: (@0x11e2dc031 H39565ba6) [Type: class 'Provider']]'file:///Users/matanl/github/dart.scratch/dart2_const_downcast/test/dart2_const_downcast_test.dart': error: line 26 pos 10: Not a constant expression.
  test('$aBadModule should be invalid', () {
```

... this _is_ an error (`listOfThings` is not a `List<Provider>`), but it's very hard to figure out here:
* `_ImmutableList` isn't something I wrote
* This seems to not have the better error messages I've seen elsewhere
* This seems to leak internals of the VM (`TypeArguments: (@0x11e2dc031 H39565ba6)`).

I'll file a separate bug on the analyzer/DDC - I wouldn't have gotten that far if the IDE warned me.

**Comment by matanlurey** [comment]
Interestingly, this does fails nicely at compile-time in Dart2JS with `--preview-dart-2`:

```
test/dart2_const_downcast_test.dart:21:26:
Error: `listOfThings` of type 'List<Object>' is not a subtype of List<Provider>.
const aBadModule = const Module(listOfThings);
                         ^
Error: Compilation failed.
```

**Comment by matanlurey** [comment]
Code: https://github.com/matanlurey/dart.scratch/tree/master/dart2_const_downcast

You can reproduce:

```bash
$ dart --preview-dart-2 test/dart2_const_downcast_test.dart
```

**Comment by a-siva** [comment]
A small change in the VM makes the error better
```
{
   Error& error = Error::Handle();
   if (!result_.IsInstanceOf(type, instantiator_type_arguments,
                             function_type_arguments, &error)) {
+    const AbstractType& rtype = AbstractType::Handle(result_.GetType(Heap::kNew));
+    const String& result_str = String::Handle(rtype.UserVisibleName());
+    const String& type_str = String::Handle(type.UserVisibleName());
     H.ReportError(script_, TokenPosition::kNoSource,
                   "Not a constant expression: %s is not an instance of %s",
-                  result_.ToCString(), type.ToCString());
+                  result_str.ToCString(), type_str.ToCString());
   }
 }
```

```
Unhandled exception:
'file:///tmp/test/test/dart2_const_downcast_test.dart': error: Not a constant expression: List<Object> is not an instance of List<Provider>'file:///tmp/test/test/dart2_const_downcast_test.dart': error: line 24 pos 10: Not a constant expression.
  test('$aBadModule should be invalid', () {
```

Let me check all the places in the VM were we report user visible error messages and change the code to use UserVisibleName() instead of a call to ToCString() which prints an internal name,

**Comment by matanlurey** [comment]
Thanks!

**Comment by a-siva** [comment]
Landed https://dart-review.googlesource.com/c/sdk/+/57880, will keep this open to scrub for more cases.

**Comment by matanlurey** [comment]
@a-siva Worth keeping open still? This looks much better now:

```
'file:///tmp/vm.dart': error: line 21 pos 33: Not a constant expression: Type 'List<Object>' is not a subtype of type 'List<Provider>'
const aBadModule = const Module(listOfThings);
                                ^
'file:///tmp/vm.dart': error: line 27 pos 3: Not a constant expression.
  aBadModule.providers;
  ^

#0      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#1      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by a-siva** [comment]
Closing it.
