### ISSUE TITLE
Analysis server error - -dev.59

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33312]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5087.20`
- `2.0.0-dev.59.0`
- `IU-181.5087.20, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.4 unknown, screens 3840x2160`

# Exception
```
Dart analysis server, SDK version 2.0.0-dev.59.0, server version 1.20.3, FATAL error: Failed to handle request: {id: 12960, method: edit.getFixes, params: {file: /Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart, offset: 4202}, clientRequestTime: 1527876990721}
NoSuchMethodError: The getter 'thenStatement' was called on null.
Receiver: null
Tried calling: thenStatement
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FixProcessor._addFix_replaceWithConditionalAssignment (package:analysis_server/src/services/correction/fix_internal.dart:2681)
<asynchronous suspension>
#2      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:556)
<asynchronous suspension>
#3      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:86)
<asynchronous suspension>
#4      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:542)
<asynchronous suspension>
#5      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:235)
<asynchronous suspension>
#6      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:339)
#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:722)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#9      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:718)
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     runZoned (dart:async/zone.dart:1490)
#13     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:717)
#14     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#16     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#17     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#18     _rootRunUnary (dart:async/zone.dart:1134)
#19     _CustomZone.runUnary (dart:async/zone.dart:1031)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#26     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#27     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#28     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#30     _rootRunUnary (dart:async/zone.dart:1134)
#31     _CustomZone.runUnary (dart:async/zone.dart:1031)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#35     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#36     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#37     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#38     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#39     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#40     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#41     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#43     _rootRunUnary (dart:async/zone.dart:1134)
#44     _CustomZone.runUnary (dart:async/zone.dart:1031)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#48     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#49     _StreamController._add (dart:async/stream_controller.dart:639)
#50     _StreamController.add (dart:async/stream_controller.dart:585)
#51     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
#52     _rootRunUnary (dart:async/zone.dart:1138)
#53     _CustomZone.runUnary (dart:async/zone.dart:1031)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#57     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#58     _StreamController._add (dart:async/stream_controller.dart:639)
#59     _StreamController.add (dart:async/stream_controller.dart:585)
#60     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#61     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#64     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

```
1527876989648 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1527876989648 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","classes":[{"offset":1966,"length":10}],"members":[{"offset":2011,
1527876989938 => {"id":"12956","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart":{"type":"add","content":"// Copyright (c) 2018, 
1527876989943 <= {"id":"12956","result":{}}
1527876989943 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1527876989950 => {"id":"12957","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","offset":4196,"length":0},"clientRequestTime":15278769899
1527876989992 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"fil
1527876989992 <= {"id":"12957","result":{"assists":[]}}
1527876989994 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","regions":[{"type":"DIRECTIVE","offset":217,"length":54},{"type":"B
1527876989999 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","regions":[{"offset":224,"length":46,"targets":[0]},{"offset":279,"
1527876989999 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","labels":[]}}
1527876990000 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name
1527876990002 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","overrides":[{"offset":2040,"length":8,"superclassMember":{"element"
1527876990004 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1527876990004 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","classes":[{"offset":1966,"length":10}],"members":[{"offset":2011,
1527876990342 => {"id":"12958","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart":{"type":"add","content":"// Copyright (c) 2018, 
1527876990343 <= {"id":"12958","result":{}}
1527876990347 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1527876990347 => {"id":"12959","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","offset":4197,"length":0},"clientRequestTime":15278769903
1527876990393 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"fil
1527876990393 <= {"id":"12959","result":{"assists":[]}}
1527876990395 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","regions":[{"type":"DIRECTIVE","offset":217,"length":54},{"type":"B
1527876990396 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","regions":[{"offset":224,"length":46,"targets":[0]},{"offset":279,"
1527876990396 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","labels":[]}}
1527876990397 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name
1527876990397 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","overrides":[{"offset":2040,"length":8,"superclassMember":{"element"
1527876990401 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1527876990402 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","classes":[{"offset":1966,"length":10}],"members":[{"offset":2011,
1527876990721 => {"id":"12960","method":"edit.getFixes","params":{"file":"/Users/kevmoo/source/github/pubspec_parse/lib/src/dependency.dart","offset":4202},"clientRequestTime":1527876990721}
1527876990746 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 12960, method: edit.getFixes, params: {file: /Users/kevmoo/source/github/pubspec_parse/lib/s
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/58042

**Comment by kevmoo** [comment]
Points for including the commit sha when closing - 7246d2e75920651d024b3ef7cb3aa969d20461f0
