### ISSUE TITLE
open IDE

### ISSUE THREAD

**Issue by 2bon** [dart-lang/sdk#33320]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5087.20`
- `1.24.3`
- `IU-181.5087.20, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 2560x1080`

# Exception

Please append the contents of:
file://C:\Users\RickX\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Analysis failed: D:\Users\Rick\IdeaProjects\material-components-flutter-codelabs\mdc_100_series\lib\home.dart context: exception_20180603_232541_536
NoSuchMethodError: Class 'GenericTypeAliasElementForLink' has no instance getter 'returnType'.
Receiver: Instance of 'GenericTypeAliasElementForLink'
Tried calling: returnType
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      GenericTypeAliasElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3318)
#3      FunctionTypeImpl.baseReturnType (package:analyzer/src/dart/element/type.dart:435)
#4      FunctionTypeImpl.returnType (package:analyzer/src/dart/element/type.dart:626)
#5      FunctionTypeImpl.== (package:analyzer/src/dart/element/type.dart:729)
#6      TypeImpl.equalArrays (package:analyzer/src/dart/element/type.dart:2631)
#7      FunctionTypeImpl.== (package:analyzer/src/dart/element/type.dart:730)
#8      InheritanceManager._unionInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:893)
#9      InheritanceManager._computeInterfaceLookupMap (package:analyzer/src/dart/resolver/inheritance_manager.dart:455)
#10     InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:496)
#11     InheritanceManager.lookupOverrides (package:analyzer/src/dart/resolver/inheritance_manager.dart:205)

**Comment by devoncarew** [comment]
Thanks for the report! Closing due to an older sdk version (`SDK version 1.24.3`).
