### ISSUE TITLE
HttpClient - Connection closed while receiving data

### ISSUE THREAD

**Issue by JasonWeise** [dart-lang/sdk#33321]
HI Team

I am having issues with a request to a SOAP endpoint using HttpClient. I have confirmed the endpoing works fine by POSTING with the same request from Postman, but the issue I am receiving with Dart is the following error:
**[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
HttpException: Connection closed while receiving data, uri = ...**

I am using HttpClient as the staging server we are using does not have a valid SSL certificate so am using badCertificateCallback to try get around that.

Is it likely that the connection is being closed by the badCertificateCallback unexpectedly?

Any pointers or advice would be greatly appreciated.

Dart VM version: 2.0.0-dev.59.0 
Flutter App connecting to backend SOAP API from third party (works with Postman using same method)

My data method:

```dart
_getData() async {
  var envelope = "[BODY CONTAINING SOAP ENVELOPE AS PER WORKING IN POSTMAN]";
  bool _certificateCheck(X509Certificate cert, String host, int port) => true;
  var httpClient = new HttpClient()..badCertificateCallback = _certificateCheck;
  var uri = new Uri.https('admin.mysite.com', '/api/v2_soap/');
  var request = await httpClient.postUrl(uri);
  request.headers.contentLength = envelope.length;
  request.headers.add(HttpHeaders.CONTENT_TYPE, "text/xml");
  await request.write(envelope);
  HttpClientResponse response = await request.close();
  var responseBody = await response.transform(UTF8.decoder).join();
  return responseBody;
}
```

Being called by:

```dart
_getUserApi().then((results) => data = results);
````

Thanks in advance.

**Comment by HannoOttens** [comment]
I have the same issue, is there a solution?

**Comment by jaswant0605** [comment]
Same issue with me too

**Comment by HannoOttens** [comment]
For me it was an emulator issue. Ran it on my phone and everything was fine.

**Comment by dujianchi** [comment]
Same issue with me too

**Comment by hamiao123** [comment]
Same issue with me too，Is there a solution

**Comment by kangwang1988** [comment]
@eseidelGoogle 
@hamiao123  is from our team.
Can you help us figure out how to solve this problem?

**Comment by efortuna** [comment]
@a-siva might you know who could take a look at this?

**Comment by mraleph** [comment]
Assigning to @a-siva for triage. This seems to have fallen through the cracks.

**Comment by emeyex** [comment]
I believe I am having the same issue, with a completely vanilla test case (dart command-line server only, no flutter, no web). The client and server are essentially ripped from https://www.dartlang.org/tutorials/dart-vm/httpserver#making-post.

Currently this is blocking me from using dart's HttpClient for writing tests...  Hopefully I'm just making a stupid mistake, or, if there's a work-around, please advise, thanks!

Version info:
`dart --version: Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "macos_x64"`

server.dart:
```
import 'dart:io';
import 'dart:convert';

Future main() async {
  var server = await HttpServer.bind('localhost', 8080);
  await for(var req in server) {
    print('request: ${req.uri.pathSegments}');
    HttpResponse response = req.response;
    if(req.method == 'POST') {
      final body = jsonDecode(utf8.decode(await req.first));
      response.write(jsonEncode(body));
    }
    await response.close();
  }
}
```

client.dart:
```
import 'dart:io';
import 'dart:convert';

Future main() async {
  final jsonData = {'a': 1, 'b': 'hello', 'c': true};
  HttpClientRequest request = await HttpClient().postUrl(Uri.parse('http://localhost:8080/account/view/device1')) /*1*/
    ..headers.contentType = ContentType.json /*2*/
    ..write(jsonEncode(jsonData)); /*3*/
  HttpClientResponse response = await request.close(); /*4*/
  print('got response');
  await response.transform(utf8.decoder /*5*/).forEach(print);
}
```

Client yields this error:
```
Unhandled exception:
HttpException: Connection closed while receiving data, uri = http://localhost:8080/account/view/device1
#0      _HttpIncoming.listen.<anonymous closure> (dart:_http/http_impl.dart:161:7)
#1      _invokeErrorHandler (dart:async/async_error.dart:13:29)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:286:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:168:13)
... etc ...
```
whereas same POST from Postman works fine.

Originally was having this issue in a more complex scenario trying to write tests using HttpClient, but it seems like this is about as stripped down a scenario as possible (no libraries, only importing `dart:io` and `dart:convert`) and it's still happening.

**Comment by emeyex** [comment]
Interestingly, if I run the same server code _within the same process / from the same file_ as `client.dart`, the program works as expected. It occurred to me that tests might be written that way. To repro, it requires running the client and server programs from separate shells/procs.

**Comment by mkustermann** [comment]
The server side is not getting all of the data with
```dart
      final body = jsonDecode(utf8.decode(await req.first));
```

If you change this to drain all of the data, via:
```dart
      final bytesBuilder = await req.fold(new BytesBuilder(), (bb, bytes) => bb..add(bytes));
      final bytes = bytesBuilder.takeBytes();
      final body = jsonDecode(utf8.decode(bytes));
```

The example you gave should work.

**Comment by mkustermann** [comment]
@emeyex Just because the client writes all bytes at once does not mean the server will get all of them at once, the underlying protocols and kernels will chunk the data in arbitrary sized chunks and deliver it to the other end. There is no guarantee whatsoever in how many chunks the bytes get delivered (even one byte at a time can happen). So it is necessary to read all of the bytes unto the EndOfStream comes.

**Comment by emeyex** [comment]
Sure, I guess I presumed that the API was operating above the basic TCP level. And FWIW, in my case, what I'm saying is `await req.first` actually _was_ receiving all of the data I had sent... so I guess the difference for me was awaiting EndOfStream. The other part of the mystery is that posts from the Postman app work just fine against the same server (i.e., it receives the entire body echoed back).

**Comment by TimSchue** [comment]
I have the same probleme wrote Api with laravel and it works when I upload it to a server but its closing connection when I use localhost...
Has anyone solved it, I would be grateful for some insights :D?

**Comment by jairoqr3000** [comment]
resolvi el problema agregando el proxy cntlm a mi pc, luego en el emulador android en setting -> proxy-> manual proxy configuration->hostname: 127.0.0.1 portnumber:3128
en el hostname no funciona si pones localhost

**Comment by shekhar18** [comment]
For me, it was an emulator issue also Ran it on my phone but sometimes it issue occurs.  how to fix this issue any idea.

**Comment by not-Ian** [comment]
Any updates to this issue? My team is getting this error when calling non-localhost APIs from a iOS simulator.

Calling the same APIs from Postman works just fine, and also calling these APIs from a physical iOS device works just fine.

Dart SDK version: 2.15.1 (stable)

my `flutter doctor` output:

> [✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G221 darwin-x64, locale
>     en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 13.0)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.5)
> [✓] IntelliJ IDEA Ultimate Edition (version 2017.1.5)
> [✓] VS Code (version 1.63.2)
> [✓] Connected device (3 available)
>     ! Error: iPhone is not connected. Xcode will continue when iPhone is
>       connected. (code -13)
>     ! Error: iPhone is not connected. Xcode will continue when iPhone is
>       connected. (code -13)

thanks

**Comment by FakharAlyas119** [comment]
i am also facing same issue but it is working in postman

**Comment by a-siva** [comment]
Closing issue as Stale.

**Comment by danielb1194** [comment]
This is still happening to me as of today.

`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.38.7, on Microsoft Windows [Version 10.0.26100.7623], locale en-US)
[√] Windows Version (11 Home 64-bit, 24H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 36.1.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2026 18.1.1)
[√] Connected device (4 available)
[√] Network resources`
