### ISSUE TITLE
mirrors/dynamic_load_test fails on Windows

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#33338]
```
Running "vm" command: set DART_CONFIGURATION=ReleaseX64 & pkg\vm\tool\dart2.bat --sync-async --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\out\ReleaseX64\generated_tests\lib_2\mirrors\initializing_formals_test_none.dart
FAILED: dartk-vm release_x64 lib_2/mirrors/dynamic_load_test
Expected: Pass
Actual: RuntimeError
--- Command "vm" (took 03.000953s):
set DART_CONFIGURATION=ReleaseX64 & pkg\vm\tool\dart2.bat --sync-async --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\tests\lib_2\mirrors\dynamic_load_test.dart
exit code:
255
stdout:
IsolateMirror on 'dynamic_load_test.dart:main()'
LibraryMirror on 'dynamic_load_success'
InstanceMirror on 1
InstanceMirror on 2
LibraryMirror on 'dynamic_load_success'
InstanceMirror on 3
InstanceMirror on 4
tests/lib_2/mirrors/DOES_NOT_EXIST: Error: The system cannot find the file specified.
stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:605:5)
#1      Expect.isTrue (package:expect/expect.dart:133:5)
#2      main (file:///C:/b/s/w/ir/tests/lib_2/mirrors/dynamic_load_test.dart:45:10)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
--- Re-run this test:
python tools/test.py -m release -c dartk --strong --output-directory C:\b\s\w\iodxgot1 lib_2/mirrors/dynamic_load_test
Done dartk-vm release_x64 lib_2/mirrors/dynamic_load_test: fail
```

**Comment by aam** [comment]
Fixed via f2883d1b4f8efd152614c1802442e71fc4dec695
