### ISSUE TITLE
Crash with sync-async as default

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#33363]
The following tests fail under hot-reload now that `--sync-async` is the default for the VM:

```
python tools/test.py -m release --hot-reload co19/LibTest/isolate/ReceivePort/firstWhere_A01_t01
python tools/test.py -m release --hot-reload co19/LibTest/isolate/ReceivePort/firstWhere_A02_t01
python tools/test.py -m release --hot-reload co19/LibTest/isolate/ReceivePort/lastWhere_A02_t01
```

Here is the error message:
```
--- Command "vm" (took 435ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --no-preview-dart-2 --enable_asserts --enable_type_checks --hot-reload-rollback-test-mode --ignore-unrecognized-flags --packages=/b/build/slave/vm-linux-release-x64-reload-rollback-be/build/sdk/.packages /b/build/slave/vm-linux-release-x64-reload-rollback-be/build/sdk/tests/co19/src/LibTest/isolate/ReceivePort/firstWhere_A01_t01.dart
exit code:
-6
stdout:
unittest-suite-wait-for-done
stderr:
Unhandled exception:
NoSuchMethodError: Class '_GeneratedStreamImpl' has no instance method 'firstWhere' with matching arguments.
Receiver: Instance of '_GeneratedStreamImpl'
Tried calling: firstWhere(Closure: (int) => dynamic, defaultValue: Closure: () => dynamic)
Found: firstWhere((T) => bool, {() => T orElse}) => Future<T>
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      check2 (file:///b/build/slave/vm-linux-release-x64-reload-rollback-be/build/sdk/tests/co19/src/LibTest/isolate/ReceivePort/firstWhere_A01_t01.dart:32:14)
#2      check (file:///b/build/slave/vm-linux-release-x64-reload-rollback-be/build/sdk/tests/co19/src/LibTest/isolate/ReceivePort/firstWhere_A01_t01.dart:46:3)
#3      main (file:///b/build/slave/vm-linux-release-x64-reload-rollback-be/build/sdk/tests/co19/src/LibTest/isolate/ReceivePort/firstWhere_A01_t01.dart:50:3)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
../../runtime/vm/isolate.cc: 1854: error: Isolate did not reload before exiting and --check-reloaded is enabled.
Dumping native stack trace for thread 641d
===== CRASH =====
version=2.0.0-edge.398ba13e4ac6460bf731d9a7aa8aaccbf8b19439 (Wed Jun 6 14:32:13 2018 +0000) on "linux_x64"
si_signo=Segmentation fault(11), si_code=1, si_addr=0x848
Aborting re-entrant request for stack trace.
```

**Comment by a-siva** [comment]
These tests are running in Dart 1 mode.
I don't think we want to turn on sync-async by default in Dart 1 mode. It is only turned on for Dart 2.
