### ISSUE TITLE
NPE in StaticTypeAnalyze when for-in is unresolved

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33370]
I was typing something like, an maybe `_addedRoots` was incomplete and unresolved.

```dart
    for (var previousRoot in _addedRoots)
```

Analyzer Feedback from IntelliJ

# Version information

- `IDEA 182.SNAPSHOT`
- `2.0.0-edge.9672d69a0691ef66a4b554537e26c8c0f95fcbe6`
- `IC-182.SNAPSHOT, JRE 1.8.0_112-b16x64 Oracle Corporation, OS Mac OS X(x86_64) v10.13.4 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/cp/_32g44l548q8d0bfj4_l9s3m003ky_/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.9672d69a0691ef66a4b554537e26c8c0f95fcbe6, server version 1.20.3, error: Analysis failed: /Users/scheglov/dart/pub/lib/src/dart.dart context: exception_20180606_115820_116
NoSuchMethodError: The method 'resolveToBound' was called on null.
Receiver: null
Tried calling: resolveToBound(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      StaticTypeAnalyzer._findIteratedType (package:analyzer/src/generated/static_type_analyzer.dart:1668:17)
#2      StaticTypeAnalyzer._inferForEachLoopVariableType (package:analyzer/src/generated/static_type_analyzer.dart:1924:33)
#3      StaticTypeAnalyzer.visitDeclaredIdentifier (package:analyzer/src/generated/static_type_analyzer.dart:496:7)
#4      DeclaredIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:3385:49)
#5      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6341:10)
#6      UnifyingAstVisitor.visitDeclaredIdentifier (package:analyzer/dart/ast/visitor.dart:2971:57)
#7      ScopedVisitor.visitDeclaredIdentifier (package:analyzer/src/generated/resolver.dart:7527:34)
#8      DeclaredIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:3385:49)
#9      ResolverVisitor.visitForEachStatementInScope (package:analyzer/src/generated/resolver.dart:5996:19)
#10     ScopedVisitor.visitForEachStatement (package:analyzer/src/generated/resolver.dart:7584:7)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/72960
