### ISSUE TITLE
Auto complete not working and Cant import other .dart files

### ISSUE THREAD

**Issue by forwinder15** [dart-lang/sdk#33387]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4819257`
- `2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c`
- `AI-173.4819257, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\FIRSTB~1\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c, server version 1.20.2, error: Captured exception
NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains(Instance of 'FileState')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:244)
#2      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#3      FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:218)
#4      FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:291)
#5      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:883)
<asynchronous suspension>
#6      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1940)
<asynchronous suspension>
#7      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1883)
#8      new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#9      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#10     StdioAnalysisServer.serveStdio (package:a

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I think this has been fixed in https://github.com/dart-lang/sdk/commit/371c8e4b870df44f3d44a393bdc6a73e4ab275d4

So, download the latest SDK build.
Or, if you cannot do this, remove `C:\Users\<user>\AppData\Local\.dartServer\.analysis-driver`.
