### ISSUE TITLE
AnalysisServer crash -dev.61

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33412]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5087.20`
- `2.0.0-dev.61.0`
- `IU-181.5087.20, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.4 unknown, screens 2560x1600`

# Exception

```
Dart analysis server, SDK version 2.0.0-dev.61.0, server version 1.20.3, error: Failed to send analysis.implemented notification.
Concurrent modification during iteration: Instance of '_CompactLinkedHashSet<String>'.
#0      _CompactIterator.moveNext (dart:collection-patch/dart:collection/compact_hash.dart:438)
#1      Search.subtypes (package:analyzer/src/dart/analysis/search.dart:383)
<asynchronous suspension>
#2      SearchEngineImpl.membersOfSubtypes.addMembers (package:analysis_server/src/services/search/search_engine_internal.dart:40)
<asynchronous suspension>
#3      SearchEngineImpl.membersOfSubtypes (package:analysis_server/src/services/search/search_engine_internal.dart:51)
<asynchronous suspension>
#4      ImplementedComputer.compute (package:analysis_server/src/domains/analysis/implemented_dart.dart:34)
<asynchronous suspension>
#5      scheduleImplementedNotification (package:analysis_server/src/operation/operation_analysis.dart:36)
<asynchronous suspension>
#6      AnalysisServer._scheduleAnalysisImplementedNotification (package:analysis_server/src/analysis_server.dart:1149)
<asynchronous suspension>
#7      AnalysisServer.sendStatusNotificationNew (package:analysis_server/src/analysis_server.dart:883)
#8      _rootRunUnary (dart:async/zone.dart:1134)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#12     _DelayedData.perform (dart:async/stream_impl.dart:584)
#13     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700)
#14     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660)
#15     _rootRun (dart:async/zone.dart:1122)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     _CustomZone.runGuarded (dart:async/zone.dart:925)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#25     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#26     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

```
1528731503761 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/travis.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN
1528731503766 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/travis.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"length":
1528731503767 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/travis.dart","labels":[]}}
1528731503769 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/travis.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<u
1528731503770 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/travis.dart","overrides":[{"offset":3307,"length":8,"superclassMember":{"element":{"ki
1528731503772 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1528731503861 => {"id":"17","method":"analysis.setPriorityFiles","params":{"files":["/Users/kevmoo/source/github/repo_manager/lib/src/data_model.g.dart"]},"clientRequestTime":1528731503861}
1528731503861 => {"id":"18","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/Users/kevmoo/source/github/repo_manager/lib/src/data_model.g.dart"],"CLOSING_LABELS":["/Users
1528731504033 => {"id":"19","method":"analysis.setPriorityFiles","params":{"files":[]},"clientRequestTime":1528731504033}
1528731504033 => {"id":"20","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":[],"CLOSING_LABELS":[],"OUTLINE":[],"NAVIGATION":[],"HIGHLIGHTS":[],"IMPLEMENTED":[]}},"clientRe
1528731505623 => {"id":"21","method":"analysis.setPriorityFiles","params":{"files":["/Users/kevmoo/source/github/repo_manager/lib/src/github.dart"]},"clientRequestTime":1528731505623}
1528731505624 => {"id":"22","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/Users/kevmoo/source/github/repo_manager/lib/src/github.dart"],"CLOSING_LABELS":["/Users/kevmo
1528731506003 => {"id":"23","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","offset":13211,"length":0},"clientRequestTime":1528731506003}
1528731506844 <= {"id":"17"}
1528731506845 <= {"id":"18"}
1528731506845 <= {"id":"19"}
1528731506845 <= {"id":"20"}
1528731506846 <= {"id":"21"}
1528731506846 <= {"id":"22"}
1528731506854 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1528731506912 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/data_model.g.dart","errors":[]}}
1528731506979 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/kevmoo
1528731507033 <= {"id":"23","result":{"assists":[]}}
1528731507039 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN
1528731507051 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"length":
1528731507052 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","labels":[]}}
1528731507055 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<u
1528731507055 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/src/github.dart","overrides":[]}}
1528731507058 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1528731509903 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to send analysis.implemented notification.","stackTrace":"Concurrent modification during iteration: Instance of '_C
```

**Comment by bwilkerson** [comment]
@scheglov In case this is related to the recent changes you made in this area.

**Comment by jbaxe2** [comment]
I am getting the same issue, since yesterday after updating to 2.0.0-dev.61.0.  Same version of IntelliJ.  Running Ubuntu 17.10, with kernel release 4.13.0-45-generic.

After the initial crash when IntelliJ loads, running the analyzer again appears to work.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/60142
