### ISSUE TITLE
Feedback from IntelliJ

### ISSUE THREAD

**Issue by mchakroun** [dart-lang/sdk#33434]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA 182.2949.6`
- `2.0.0-dev.61.0`
- `WS-182.2949.6, JRE 1.8.0_152-release-1226-b7x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.4 unknown, screens 1920x1080`

# Exception

Please append the contents of:
file:///private/var/folders/kz/bpbrh2qn6mv8zt7v32cc1lcr0000gn/T/report.txt

```
Dart analysis server, SDK version 2.0.0-dev.61.0, server version 1.20.3, error: Failed to send analysis.implemented notification.
Concurrent modification during iteration: Instance of '_CompactLinkedHashSet<String>'.
#0      _CompactIterator.moveNext (dart:collection-patch/dart:collection/compact_hash.dart:438)
#1      Search.subtypes (package:analyzer/src/dart/analysis/search.dart:383)
<asynchronous suspension>
#2      SearchEngineImpl.membersOfSubtypes.addMembers (package:analysis_server/src/services/search/search_engine_internal.dart:40)
<asynchronous suspension>
#3      SearchEngineImpl.membersOfSubtypes (package:analysis_server/src/services/search/search_engine_internal.dart:51)
<asynchronous suspension>
#4      ImplementedComputer.compute (package:analysis_server/src/domains/analysis/implemented_dart.dart:34)
<asynchronous suspension>
#5      scheduleImplementedNotification (package:analysis_server/src/operation/operation_analysis.dart:36)
<asynchronous suspension>
#6      AnalysisServer._scheduleAnalysisImplementedNotification (package:analysis_server/src/analysis_server.dart:1149)
<asynchronous suspension>
#7      AnalysisServer.sendStatusNotificationNew (package:analysis_server/src/analysis_server.dart:883)
#8      _rootRunUnary (dart:async/zone.dart:1134)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)

**Comment by devoncarew** [comment]
closing as a dup of https://github.com/dart-lang/sdk/issues/33735
