### ISSUE TITLE
Dart Analyzer ErrorEncountered a Dart Analysis Server error

### ISSUE THREAD

**Issue by fyzs-n9001** [dart-lang/sdk#33442]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4819257`
- `2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c`
- `AI-173.4819257, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\admin\AppData\Local\Temp\report14609.txt

```
Dart analysis server, SDK version 2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c, server version 1.20.2, error: Analysis failed: C:\Users\admin\Desktop\pt2\lib\drawer\home.dart
NoSuchMethodError: The getter 'libraryNameOffset' was called on null.
Receiver: null
Tried calling: libraryNameOffset
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FileState.isPart (package:analyzer/src/dart/analysis/file_state.dart:232)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1165)
<asynchronous suspension>
#3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1023)
<asynchronous suspension>
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1940)
<asynchronous suspension>
#5      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1883)
#6      new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#7      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#8      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#9      Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dar

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/33387
