### ISSUE TITLE
Dart Analyzer broken after upgrade

### ISSUE THREAD

**Issue by ericwindmill** [dart-lang/sdk#33451]
Other Info:
I upgraded my Flutter package and Intellij / plugins yesterday. This is the first time I've really worked since then, so it could be a result of either of those things.

All the Dart tools in Intellij are failing intermitently (analyzer, cmd+clicking, alt+enter)

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-173.4674.33`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `IU-173.4674.33, JRE 1.8.0_152-release-1024-b15x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.2 unknown, screens 1920x1200, 2560x1440  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/y5/449tvrsj2fxcmgl46jj5ds5h0000gn/T/report1845.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.20.2, error: Captured exception
NoSuchMethodError: The getter 'lineStarts' was called on null.
Receiver: null
Tried calling: lineStarts
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:448)
#2      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:860)
#3      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:622)
#4      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:490)
#5      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:860)
#6      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:622)
#7      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:490)
#8      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:860)
#9      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:622)
#10     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:490)
#11     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:860)
#12     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:622)
```

Another issue at the same time:

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-173.4674.33`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `IU-173.4674.33, JRE 1.8.0_152-release-1024-b15x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.2 unknown, screens 1920x1200, 2560x1440  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/y5/449tvrsj2fxcmgl46jj5ds5h0000gn/T/report2696.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.20.2, error: Analysis failed: /Users/eric/Desktop/apptree/apptreerevolution-web/portal/web/main.dart context: exception_20180614_085023_833
Bad state: No definition of type Future
#0      SummaryTypeProvider._getType (package:analyzer/src/summary/summary_sdk.dart:358)
#1      SummaryTypeProvider.futureType (package:analyzer/src/summary/summary_sdk.dart:220)
#2      SummaryTypeProvider.futureDynamicType (package:analyzer/src/summary/summary_sdk.dart:185)
#3      LibraryElementImpl.createLoadLibraryFunctionForLibrary (package:analyzer/src/dart/element/element.dart:7032)
#4      LibraryElementImpl.createLoadLibraryFunction (package:analyzer/src/dart/element/element.dart:6880)
#5      SummaryResynthesizer.finishCoreAsyncLibraries (package:analyzer/src/summary/resynthesize.dart:204)
#6      new InputPackagesResultProvider (package:analyzer/src/summary/package_bundle_reader.dart:81)
#7      LibraryContext._createResynthesizingContext (package:analyzer/src/dart/analysis/library_context.dart:208)
#8      new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:138)
#9      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#10     new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:56)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/33387

Try to remove `/Users/<user>/.dartServer/.analysis-driver`.

**Comment by ericwindmill** [comment]
I've done that once this morning based on another ticket, and it 'worked' for a minute. Trying again.
