### ISSUE TITLE
Dart Analyzer massive memory leak

### ISSUE THREAD

**Issue by ericwindmill** [dart-lang/sdk#33455]
I posted earlier via issue in #33451.
I was referred to #33387.

Taking the advice given in those files solved the issue for about 45 minutes, but there is still an issue.

----

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-173.4674.33`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `IU-173.4674.33, JRE 1.8.0_152-release-1024-b15x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.2 unknown, screens 1920x1200, 2560x1440  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/y5/449tvrsj2fxcmgl46jj5ds5h0000gn/T/report2414.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.20.2, error: Analysis failed: /Users/eric/Desktop/apptree/apptreerevolution-web/portal/web/main.dart
RangeError (byteOffset): Invalid value: Not in range 0..9444, inclusive: 1342177407
#0      _ByteDataView.getUint32 (dart:typed_data-patch/dart:typed_data/typed_data_patch.dart:4268)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:68)
#2      _FbList.length (package:front_end/src/base/flat_buffers.dart:841)
#3      new LineInfo (package:analyzer/source/line_info.dart:46)
#4      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:448)
#5      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:860)
#6      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:622)
#7      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:490)
#8      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:860)
#9      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:622)
#10     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:490)
#11     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:860)
#12     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:622)

**Comment by scheglov** [comment]
We started adding CRC32 (later replaced with something lighter) do data in analysis cache.
https://dart-review.googlesource.com/c/sdk/+/3700

I think this helped, I don't see a lot of similar reports anymore.
