### ISSUE TITLE
nSM Forwarding from Mixin between VM and dart2js disagree - VM loses default values

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#33459]
Not sure what tool is in the wrong here. Here's a [DartPad](https://dartpad.dartlang.org/9c8d2f39e29eed151108afa2c149ca5c) - dart2js is now running with `--preview-dart-2`.

Here's the text:

```dart
void main() {
  var a = new AImpl();
  var b = new B(a);
  print("CALLING W/O NAMED ARG");
  b.a();
  print("CALLING W/ NAMED ARG");
  b.a(followLinks: false);
}

abstract class A {
  a({followLinks: true});
}

class AImpl implements A {
  a({followLinks: true}) {
    print('AImpl: followLinks is $followLinks');
    if (followLinks) print('yay');
    if (!followLinks) print('nay');
  }
}

class BestMixinEvar {
  final methods = <Symbol, Function>{};

  noSuchMethod(Invocation i) {
    var na = i.namedArguments;
    print('BestMixinEvar.noSuchMethod: namedargs: $na');
    if (i.memberName == #a) return Function.apply(methods[#a], [], na);
  }
}

class B extends A with BestMixinEvar {
  A delegate;

  B(this.delegate) {
    methods.addAll(<Symbol, Function>{
      #a: delegate.a,
    });
  }
}
```

In the DartVM this blows up with `--preview-dart-2` in Dart dev.61:

```none
$ dart --preview-dart-2 a.dart 
CALLING W/O NAMED ARG
BestMixinEvar.noSuchMethod: namedargs: {Symbol("followLinks"): null}
AImpl: followLinks is null
Unhandled exception:
Failed assertion: boolean expression must not be null
#0      AImpl.a (file:///Users/srawlins/code/dart-file/packages/file/a.dart)
#1      Function._apply (dart:core/runtime/libfunction_patch.dart:10:68)
#2      Function.apply (dart:core/runtime/libfunction_patch.dart:31:12)
#3      _B&A&BestMixinEvar.noSuchMethod (file:///Users/srawlins/code/dart-file/packages/file/a.dart:28:45)
#4      _B&A&BestMixinEvar.a (file:///Users/srawlins/code/dart-file/packages/file/a.dart:11:3)
#5      main (file:///Users/srawlins/code/dart-file/packages/file/a.dart:5:5)
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

But in dart2js its OK:

```none
CALLING W/O NAMED ARG
BestMixinEvar.noSuchMethod: namedargs: {}
Warning: 'a' is used reflectively but not in MirrorsUsed. This will break minified code.
AImpl: followLinks is true
yay
CALLING W/ NAMED ARG
BestMixinEvar.noSuchMethod: namedargs: {Symbol("followLinks"): false}
Warning: 'a' is used reflectively but not in MirrorsUsed. This will break minified code.
AImpl: followLinks is false
nay
```

This is causing https://github.com/google/file.dart/issues/88.

This might be related to https://github.com/dart-lang/sdk/issues/32660 or https://github.com/dart-lang/sdk/issues/33380.

**Comment by srawlins** [comment]
CC @jmesserly @keertip @lrhn @tvolkert

**Comment by jmesserly** [comment]
Yeah this looks like a CFE/Kernel issue. The default arg is getting dropped from the no such method forwarder:
```dart
  abstract class _B&A&BestMixinEvar = test::A with test::BestMixinEvar {
    no-such-method-forwarder method a({dynamic followLinks}) → dynamic
      return this.{test::BestMixinEvar::noSuchMethod}(new core::_Invocation::method(#a, null, <dynamic>[], <core::Symbol, dynamic>{#followLinks: followLinks})) as{TypeError} dynamic;
  }
```
Changing the example to use `class B extends BestMixinEvar implements A` instead of a mixin does not work either:
```dart
  class B extends test::BestMixinEvar implements test::A {
    // ...
    no-such-method-forwarder method a({dynamic followLinks}) → dynamic
      return this.{test::BestMixinEvar::noSuchMethod}(new core::_Invocation::method(#a, null, <dynamic>[], <core::Symbol, dynamic>{#followLinks: followLinks})) as{TypeError} dynamic;
  }
```
Adding an abstract method `a({followLinks: true});` to `B` fixes it in CFE:
```dart
    no-such-method-forwarder method a({dynamic followLinks = true}) → dynamic
      return this.{test::BestMixinEvar::noSuchMethod}(new core::_Invocation::method(#a, null, <dynamic>[], <core::Symbol, dynamic>{#followLinks: followLinks})) as{TypeError} dynamic;
```

**Comment by stefantsov** [comment]
I'm cautiously optimistic about having a fix for the issue in [CL 62808](https://dart-review.googlesource.com/c/sdk/+/62808).

**Comment by stefantsov** [comment]
Sorry, pressed the wrong button.  I didn't mean to close the issue yet.
