### ISSUE TITLE
dart2js bizarre behavior of constant evaluation for shifts with negative counts

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#33468]
```dart
 class X { final x; const X(this.x); }

 void main() {
   print(const X(1 << -1).x);
 }
```

Does this:

```
╭─vegorov@volhv ~/src/dart/sdk ‹ 371d8e934f*›
╰─$ sdk/bin/dart2js /tmp/shift.dart
Compiled 8,380,026 characters Dart to 39,032 characters JavaScript in 3.35 seconds
╭─vegorov@volhv ~/src/dart/sdk ‹ 371d8e934f*›
╰─$ ~/src/v8/v8/out.gn/x64.release/d8 sdk/lib/_internal/js_runtime/lib/preambles/d8.js out.js
sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: TypeError: Cannot read property 'get$x' of null
          throw e;
          ^
TypeError: Cannot read property 'get$x' of null
    at main (out.js:894:30)
    at action (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at out.js:1097:7
    at out.js:1083:7
    at out.js:1094:5
    at out.js:1102:3
```

I would expect a compile time error or an runtime exception about negative shift count.

**Comment by rakudrama** [comment]
This should be a compile time error (constant evaluation would throw if evaluated at runtime).

**Comment by johnniwinther** [comment]
Yes. It's a bug the evaluation; we fail to report an error with the evaluation of constant values results in `null`.
