### ISSUE TITLE
Analyzer crash: Concurrent modification during iteration

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#33463]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.4203.550`
- `2.0.0-dev.62.0`
- `IU-181.4203.550, JRE 1.8.0_152-release-1136-b20x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.5 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/zr/lnfchxms55s5d2_1xc5f47_w00d63q/T/report.txt

```
Dart analysis server, SDK version 2.0.0-dev.62.0, server version 1.20.3, error: Failed to send analysis.implemented notification.
Concurrent modification during iteration: Instance of '_CompactLinkedHashSet<String>'.
#0      _CompactIterator.moveNext (dart:collection-patch/dart:collection/compact_hash.dart:438)
#1      Search.subtypes (package:analyzer/src/dart/analysis/search.dart:383)
<asynchronous suspension>
#2      SearchEngineImpl.membersOfSubtypes.addMembers (package:analysis_server/src/services/search/search_engine_internal.dart:40)
<asynchronous suspension>
#3      SearchEngineImpl.membersOfSubtypes (package:analysis_server/src/services/search/search_engine_internal.dart:51)
<asynchronous suspension>
#4      ImplementedComputer.compute (package:analysis_server/src/domains/analysis/implemented_dart.dart:34)
<asynchronous suspension>
#5      scheduleImplementedNotification (package:analysis_server/src/operation/operation_analysis.dart:36)
<asynchronous suspension>
#6      AnalysisServer._scheduleAnalysisImplementedNotification (package:analysis_server/src/analysis_server.dart:1149)
<asynchronous suspension>
#7      AnalysisServer.sendStatusNotificationNew (package:analysis_server/src/analysis_server.dart:883)
#8      _rootRunUnary (dart:async/zone.dart:1134)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/33412
