### ISSUE TITLE
Dartanalyzer crashes in preview-dart-2 mode with unhandled NoSuchMethodError: The method 'call' was called on null.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33477]
* Dart SDK Version: 2.0.0-dev.63.0
* OS: Windows 10
* Dart mode: preview-dart-2

The following sample code example throws unexpected NoSuchMethodError, I believe compile error should be thrown here instead:
``` dart
class A<X extends B> {}
class B<X extends C> {}
class C<X extends A<B>> {}

main() {
  A<B> a1 = new A();
}
```
Please note that if I run "dart --preview-dart-2" with this example, I get StackOverflow exactly like with the example from the bug #33152. However, #33152 source does not crash with analyzer.

Sample output is:
```
$> dartanalyzer --dart-preview-2 ttt.dart
Analyzing ttt.dart...
Unhandled exception:
NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      InterfaceTypeImpl.typeArguments (package:analyzer/src/dart/element/type.dart:1395:26)
#2      InterfaceTypeImpl.appendTo (package:analyzer/src/dart/element/type.dart:1431:27)
#3      TypeImpl.toString (package:analyzer/src/dart/element/type.dart:2499:5)
#4      _StringBase._interpolateSingle (dart:core/runtime/libstring_patch.dart:799:17)
#5      StringBuffer.write (dart:core/runtime/libstring_buffer_patch.dart:64:24)
#6      TypeParameterElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:9633:14)
#7      ClassElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:1098:57)
#8      ElementImpl.toString (package:analyzer/src/dart/element/element.dart:3607:5)
#9      _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:817:19)
#10     new _ElementMismatchException (package:analyzer/src/generated/declaration_resolver.dart:1019:65)
#11     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:74:17)
#12     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:691:10)
#13     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:133:9)
#14     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
#15     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:132:13)
#16     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:107:16)
<asynchronous suspension>
#17     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#18     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:43)
<asynchronous suspension>
#19     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1283:71)
<asynchronous suspension>
#20     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#21     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1240:20)
<asynchronous suspension>
#22     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:652:43)
<asynchronous suspension>
#23     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:130:58)
<asynchronous suspension>
#24     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:170:11)
<asynchronous suspension>
#25     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:106:18)
<asynchronous suspension>
#26     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:763:21)
#27     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:384:40)
#28     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#32     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:347:9)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1323:9)
<asynchronous suspension>
#1      PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1240:20)
<asynchronous suspension>
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:652:43)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:130:58)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:170:11)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:106:18)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:763:21)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:384:40)
#9      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#13     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:347:9)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#16     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

**Comment by scheglov** [comment]
Brian, I think you are fixing this in https://dart-review.googlesource.com/c/sdk/+/75403
