### ISSUE TITLE
standalone_2/io/directory_test crashes on vm-kernel-precomp-linux-debug

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#33475]
build: https://ci.chromium.org/p/dart/builders/luci.dart.try/vm-kernel-precomp-linux-debug-x64-try/1
log: https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8943452090537384608%2F%2B%2Fsteps%2Fstrong_vm_tests_shard_6%2F0%2Fstdout
```
Expected: RuntimeError
Actual: Crash
--- Command "vm_compile_to_kernel" (took 01.000915s):
DART_CONFIGURATION=DebugX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --strong-mode --sync-async --platform=out/DebugX64/vm_platform_strong.dill -o /b/s/w/ir/out/DebugX64/generated_compilations/dartkp-strong/tests_standalone_2_io_directory_test/out.dill --entry-points out/DebugX64/gen/runtime/bin/precompiler_entry_points.json --entry-points /b/s/w/ir/pkg/vm/lib/transformations/type_flow/entry_points_extra.json --entry-points /b/s/w/ir/pkg/vm/lib/transformations/type_flow/entry_points_extra_standalone.json /b/s/w/ir/tests/standalone_2/io/directory_test.dart
exit code:
0
--- Command "precompiler" (took 25.000730s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart_bootstrap --snapshot-kind=app-aot --snapshot=/b/s/w/ir/out/DebugX64/generated_compilations/dartkp-strong/tests_standalone_2_io_directory_test/out.S --strong --preview-dart-2 --no-enable-malloc-hooks --reify-generic-functions --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/DebugX64/generated_compilations/dartkp-strong/tests_standalone_2_io_directory_test/out.dill
exit code:
0
--- Command "remove_kernel_file" (took 17ms):
DART_CONFIGURATION=DebugX64 rm /b/s/w/ir/out/DebugX64/generated_compilations/dartkp-strong/tests_standalone_2_io_directory_test/out.dill
exit code:
0
--- Command "assemble" (took 01.000993s):
DART_CONFIGURATION=DebugX64 gcc -m64 -shared -nostdlib -o /b/s/w/ir/out/DebugX64/generated_compilations/dartkp-strong/tests_standalone_2_io_directory_test/out.aotsnapshot /b/s/w/ir/out/DebugX64/generated_compilations/dartkp-strong/tests_standalone_2_io_directory_test/out.S
exit code:
0
--- Command "remove_assembly" (took 21ms):
DART_CONFIGURATION=DebugX64 rm /b/s/w/ir/out/DebugX64/generated_compilations/dartkp-strong/tests_standalone_2_io_directory_test/out.S
exit code:
0
--- Command "vm" (took 120ms):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart_precompiled_runtime --preview-dart-2 --no-enable-malloc-hooks --reify-generic-functions --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/DebugX64/generated_compilations/dartkp-strong/tests_standalone_2_io_directory_test/out.aotsnapshot
exit code:
-6
stdout:
unittest-suite-wait-for-done
stderr:
Unhandled exception:
type 'bool' is not a subtype of type 'FutureOr<Directory>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:147)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:650)
#2      Future._propagateToListeners (dart:async/future_impl.dart:671)
#3      Future._completeWithValue (dart:async/future_impl.dart:482)
#4      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:512)
#5      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#6      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#7      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113)
#8      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166)
===== CRASH =====
version=2.0.0-edge.e2d72aad91abeebb4998c3da0749aaa888046e3d (Sun Jun 17 04:44:45 2018 +0000) on "linux_x64"
si_signo=Segmentation fault(11), si_code=128, si_addr=(nil)
Dumping native stack trace for thread 1279
  [0x000055be08e9961f] dart::bin::Namespace::ResolvePath(dart::bin::Namespace*, char const*, long*, char const**)
  [0x000055be08e9961f] dart::bin::Namespace::ResolvePath(dart::bin::Namespace*, char const*, long*, char const**)
  [0x000055be08eb1838] dart::bin::DirectoryListingEntry::Next(dart::bin::DirectoryListing*)
  [0x000055be08eaed2c] dart::bin::Directory::List(dart::bin::DirectoryListing*)
  [0x000055be08eb0385] dart::bin::Directory::ListNextRequest(dart::bin::CObjectArray const&)
  [0x000055be08e986fa] dart::bin::IOServiceCallback(long, _Dart_CObject*)
  [0x000055be09108865] dart::NativeMessageHandler::HandleMessage(dart::Message*)
  [0x000055be0910362a] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x000055be0910420c] dart::MessageHandler::TaskCallback()
  [0x000055be0926c9e7] dart::ThreadPool::Worker::Loop()
  [0x000055be0926c708] dart::ThreadPool::Worker::Main(unsigned long)
  [0x000055be091c8655] Unknown symbol
-- End of DumpStackTrace
--- Re-run this test:
python tools/test.py -m debug -c dartkp -r dart_precompiled --strong --output-directory /b/s/w/io1nZ5Io --vm-options --no-enable-malloc-hooks standalone_2/io/directory_test
===
=== 1 test failed
===
--- Total time: 24:15 ---
```

**Comment by mraleph** [comment]
I have briefly looked at this (because it occurred on the bot again) and my hypothesis would be that there is a race (or improper sequencing of shutdown actions)  between isolate shutdown and the worker loop that handles IO.

I was not able to reproduce it so far unfortunately.

/cc @zanderso
