### ISSUE TITLE
my dart issue

### ISSUE THREAD

**Issue by juggernetZ** [dart-lang/sdk#33487]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4819257`
- `1.24.3`
- `AI-173.4819257, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900`

# Exception

Please append the contents of:
file://C:\Users\SUSANN~1\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in VariableDeclarationListImpl in VariableDeclarationStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in ArgumentListImpl in MethodInvocationImpl in ExpressionStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in NamedExpressionImpl in ArgumentListImpl in MethodInvocationImpl in ExpressionStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in ArgumentListImpl in MethodInvocationImpl in ExpressionStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      Visitor.checkIdentifier (package:linter/src/rules/non_constant_identifier_names.dart:50)
#3      Visitor.visitFormalParameterList.<anonymous closure> (package:linter/src/rules/non_constant_identifier_names.dart:63)
#4      Object

**Comment by matanlurey** [comment]
Unfortunately this is a version of Dart from almost a year ago now.

Please try the latest development branch and see if the problem persists.
