### ISSUE TITLE
Left shift by negative amount causes analyzer crash

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#33481]
```
% cat test.dart
 class X { final x; const X(this.x); }

 void main() {
   print(const X(1 << -1).x);
 }

% dartanalyzer  test.dart     
Analyzing test.dart...                                                                       
Unhandled exception:                                                                               
Invalid argument(s): -1                                                                                
#0      int._shlFromInt (dart:core/runtime/libintegers.dart:465:53)                   
#1      int.<< (dart:core/runtime/libintegers.dart:60:39)                                     
#2      IntState.shiftLeft (package:analyzer/src/dart/constant/value.dart:2288:33)                  
#3      DartObjectImpl.shiftLeft (package:analyzer/src/dart/constant/value.dart:638:40)
#4      DartObjectComputer.shiftLeft (package:analyzer/src/dart/constant/evaluation.dart:1991:28)
#5      ConstantVisitor.visitBinaryExpression (package:analyzer/src/dart/constant/evaluation.dart:1291:34)
#6      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1215:49)            
#7      ConstantVisitor._valueOf (package:analyzer/src/dart/constant/evaluation.dart:1672:49)
#8      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:446:45)
#9      ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1667:26)                           
#10     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6577:15)                                       
#11     PropertyAccessImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9167:14)                             
#12     RecursiveAstVisitor.visitPropertyAccess (package:analyzer/dart/ast/visitor.dart:1079:10)                         
...
% dartanalyzer --version
dartanalyzer version 2.0.0-dev.63.0
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/73040
