### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by xxnjdlys** [dart-lang/sdk#33518]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5281.24`
- `2.0.0-edge.4b2d60cb18e418c5cb92cf22d2d959d8b70142a3`
- `IU-181.5281.24, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1440x900, 1920x1080, 1200x1920  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/53/6t_r0r3d0x31lq7w7941cqym0000gn/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.4b2d60cb18e418c5cb92cf22d2d959d8b70142a3, server version 1.20.3, error: Failed to send analysis.implemented notification.
NoSuchMethodError: The getter 'uriStr' was called on null.
Receiver: null
Tried calling: uriStr
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      Search.subtypes (package:analyzer/src/dart/analysis/search.dart:392)
<asynchronous suspension>
#2      SearchEngineImpl.membersOfSubtypes.addMembers (package:analysis_server/src/services/search/search_engine_internal.dart:40)
<asynchronous suspension>
#3      SearchEngineImpl.membersOfSubtypes (package:analysis_server/src/services/search/search_engine_internal.dart:51)
<asynchronous suspension>
#4      ImplementedComputer.compute (package:analysis_server/src/domains/analysis/implemented_dart.dart:34)
<asynchronous suspension>
#5      scheduleImplementedNotification (package:analysis_server/src/operation/operation_analysis.dart:36)
<asynchronous suspension>
#6      AnalysisServer._scheduleAnalysisImplementedNotification (package:analysis_server/src/analysis_server.dart:1149)
<asynchronous suspension>
#7      AnalysisServer.sendStatusNotificationNew (package:analysis_server/src/analysis_server.dart:883)
#8      _rootRunUnary (dart:async/zone.dart:1134)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I can reproduce this with a part file without a library.
Working on the regression test.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/62240
