### ISSUE TITLE
DartVM issue with List in const context

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#33533]
```sh
$ bin/cache/dart-sdk/bin/dart --version
Dart VM version: 2.0.0-dev.63.0.flutter-4c9689c1d2 (Mon Jun 18 15:50:02 2018 +0000) on "linux_x64"
$ cat packages/flutter_tools/lib/test.dart
enum IOSArch {
  armv7,
  arm64,
}
const List<IOSArch> defaultIOSArchs = <IOSArch>[
  IOSArch.arm64,
];
void main() {
  print(defaultIOSArchs);
}
$ bin/cache/dart-sdk/bin/dart packages/flutter_tools/lib/test.dart
Unhandled exception:
'file:///home/..../flutter/flutter/packages/flutter_tools/lib/test.dart': error: line 5 pos 39: initializer is not a valid compile-time constant
const List<IOSArch> defaultIOSArchs = <IOSArch>[
                                      ^

#0      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by a14n** [comment]
My bad I thought `--preview-dart-2` was already the default. Thanks.
