### ISSUE TITLE
goal: run dartanalyzer --use-cfe analyzing itself

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33541]
This is running:

```
./xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --use-cfe pkg/analyzer_cli/lib/
```

and

```
./xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --use-cfe pkg/analyzer/
```

**Comment by devoncarew** [comment]
Currently:

```
Analyzing pkg/analyzer_cli/lib...
Unhandled exception:
Crash when compiling file:///Users/devoncarew/projects/workspace/sdk/xcodebuild/ReleaseX64/dart-sdk/lib/internal/iterable.dart,
at character offset 2550:
Bad state: Data already stored for offset -1
#0      ResolutionStorer._store (package:analyzer/src/fasta/resolution_storer.dart:66:7)
#1      ResolutionStorer.genericExpressionExit (package:analyzer/src/fasta/resolution_storer.dart:185:5)
#2      TypeInferenceListener.notExit (package:front_end/src/fasta/type_inference/type_inference_listener.dart:295:7)
#3      ShadowNot.infer (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1900:23)
#4      ShadowTypeInferrer.inferExpression (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:2731:22)
#5      IfJudgment.infer (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1350:14)
#6      ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:2782:24)
```

**Comment by devoncarew** [comment]
This is working now! We'll need to test this on a bot.
