### ISSUE TITLE
goal: run the analysis server benchmark with --use-cfe

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33540]
We should be able to run the analysis server benchmark with --use-cfe:

```
./xcodebuild/ReleaseX64/dart-sdk/bin/dart pkg/analysis_server/benchmark/benchmarks.dart run --repeat=1 --quick --use-cfe analysis-server
```

and

```
./xcodebuild/ReleaseX64/dart-sdk/bin/dart pkg/analysis_server/benchmark/benchmarks.dart run --repeat=1 --use-cfe analysis-server
```

**Comment by devoncarew** [comment]
The current behavior:

```
Running analysis-server 1 times...
Unhandled exception:
Analysis failed: /Users/devoncarew/projects/workspace/sdk/pkg/meta/lib/meta.dart context: exception_20180620_155430_746
Crash when compiling file:///Users/devoncarew/projects/workspace/sdk/xcodebuild/ReleaseX64/dart-sdk/lib/internal/iterable.dart,
at character offset 2550:
Bad state: Data already stored for offset -1
#0      ResolutionStorer._store (package:analyzer/src/fasta/resolution_storer.dart:66:7)
#1      ResolutionStorer.genericExpressionExit (package:analyzer/src/fasta/resolution_storer.dart:185:5)
#2      TypeInferenceListener.notExit (package:front_end/src/fasta/type_inference/type_inference_listener.dart:295:7)
#3      ShadowNot.infer (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1900:23)
#4      ShadowTypeInferrer.inferExpression (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:2731:22)
#5      IfJudgment.infer (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1350:14)
#6      ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:2782:24)
#7      BlockJudgment.infer (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:268:16)
#8      ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:2782:24)
```

**Comment by devoncarew** [comment]
Now:

```
Unhandled exception:
Analysis failed: /Users/devoncarew/projects/workspace/sdk/pkg/meta/lib/meta.dart context: exception_20180624_150158_910
Element mismatch in /Users/devoncarew/projects/workspace/sdk/pkg/meta/lib/meta.dart at /Users/devoncarew/projects/workspace/sdk/pkg/meta/lib/meta.dart
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:74:7)
#1      LibraryAnalyzer._resolveFile2 (package:analyzer/src/dart/analysis/library_analyzer.dart:738:10)
#2      LibraryAnalyzer._analyze2.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:216:13)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
#4      LibraryAnalyzer._analyze2.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:212:17)
#5      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#6      LibraryAnalyzer._analyze2.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:211:17)
<asynchronous suspension>
#7      PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#8      LibraryAnalyzer._analyze2 (package:analyzer/src/dart/analysis/library_analyzer.dart:185:26)
<asynchronous suspension>
#9      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:22)
<asynchronous suspension>
#10     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#11     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:98:43)
```

**Comment by devoncarew** [comment]
Strangely enough, this looks like this completes now:

```
./xcodebuild/ReleaseX64/dart-sdk/bin/dart pkg/analysis_server/benchmark/benchmarks.dart run --repeat=1 analysis-server
Running analysis-server 1 times...
  {analysis-server-warm-analysis: {micros: 17755324}, analysis-server-warm-memory: {bytes: 189043952}, analysis-server-edit: {micros: 70307}, analysis-server-completion: {micros: 195056}}
Finished in 28 seconds.

{"benchmark":"analysis-server","result":{"analysis-server-warm-analysis":{"micros":17755324},"analysis-server-warm-memory":{"bytes":189043952},"analysis-server-edit":{"micros":70307},"analysis-server-completion":{"micros":195056}}}
```

**Comment by devoncarew** [comment]
It looks like we can run the analysis server benchmarks now! Definitely some tuning to do, but this is a great milestone:

./xcodebuild/ReleaseX64/dart-sdk/bin/dart pkg/analysis_server/benchmark/benchmarks.dart run analysis-server-cold

```
Running analysis-server-cold 3 times...
  {analysis-server-cold-analysis: {micros: 17156964}, analysis-server-cold-memory: {bytes: 189045456}}
  {analysis-server-cold-analysis: {micros: 17142456}, analysis-server-cold-memory: {bytes: 189030176}}
  {analysis-server-cold-analysis: {micros: 17707110}, analysis-server-cold-memory: {bytes: 189026016}}
Finished in 65 seconds.

{"benchmark":"analysis-server-cold","result":{"analysis-server-cold-analysis":{"micros":17142456},"analysis-server-cold-memory":{"bytes":189026016}}}
```

./xcodebuild/ReleaseX64/dart-sdk/bin/dart pkg/analysis_server/benchmark/benchmarks.dart run **--use-cfe** analysis-server-cold

```
Running analysis-server-cold 3 times...
  {analysis-server-cold-analysis: {micros: 40093469}, analysis-server-cold-memory: {bytes: 977913280}}
  {analysis-server-cold-analysis: {micros: 39977296}, analysis-server-cold-memory: {bytes: 978165200}}
  {analysis-server-cold-analysis: {micros: 39795372}, analysis-server-cold-memory: {bytes: 978643216}}
Finished in 122 seconds.

{"benchmark":"analysis-server-cold","result":{"analysis-server-cold-analysis":{"micros":39795372},"analysis-server-cold-memory":{"bytes":977913280}}}
```

**Comment by devoncarew** [comment]
Closing as complete; we have a bot change in-bound which will test that this works on every CL.

**Comment by devoncarew** [comment]
Re-opening as the benchmark fails to run on windows:

```
Running analysis-server-cold 1 times...
analysis-server-cold threw exception: FormatException: Unexpected end of input (at character 1)
^
#0      _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1358:5)
#1      _ChunkedJsonParser.close (dart:convert/runtime/libconvert_patch.dart:511:7)
#2      _parseJson (dart:convert/runtime/libconvert_patch.dart:30:10)
#3      JsonDecoder.convert (dart:convert/json.dart:540:36)
#4      JsonCodec.decode (dart:convert/json.dart:167:41)
#5      AnalysisServerMemoryUsageTest.getMemoryUsage (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/benchmark/perf/memory_tests.dart:46:25)
#6      ColdAnalysisBenchmark.run (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/benchmark/perf/benchmarks_impl.dart:47:26)
<asynchronous suspension>
#7      RunCommand.run (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/benchmark/benchmarks.dart:128:53)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#10     new Future.sync (dart:async/future.dart:224:31)
#11     CommandRunner.run (package:args/command_runner.dart:109:11)
#12     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/benchmark/benchmarks.dart:30:10)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
step returned non-zero exit code: 1
```

**Comment by devoncarew** [comment]
This should be fixed by https://dart-review.googlesource.com/c/sdk/+/70100.

**Comment by whesse** [comment]
If the two steps dropped from the win builder are now working again (the benchmarks and the pkg), then we can merge the windows builder back again in test_matrix.json.

**Comment by devoncarew** [comment]
Yup! Out for review here: https://dart-review.googlesource.com/c/sdk/+/70142
