### ISSUE TITLE
NoSuchMethodError: The getter 'potentialEditIds' was called on null.

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#33578]
* Dart SDK Version: 2.0.0-dev.62.0 
* Operating System: macOS

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Tried to rename an optional named parameter in a top-level function.

### Request

While responding to request: `edit.getRefactoring`

### Versions

- Dart SDK 2.0.0-dev.62.0
- Visual Studio Code 1.24.1
- Dart Code 2.14.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/usr/local/Cellar/dart/2.0.0-dev.62.0/libexec/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.14.0
```

### Exception

NoSuchMethodError: The getter 'potentialEditIds' was called on null.
Receiver: null
Tried calling: potentialEditIds

```text
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:855)
<asynchronous suspension>
#2      _rootRun (dart:async/zone.dart:1126)
#3      _CustomZone.run (dart:async/zone.dart:1023)
#4      _runZoned (dart:async/zone.dart:1518)
#5      runZoned (dart:async/zone.dart:1502)
#6      _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:810)
#7      EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:650)
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:350)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:745)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:741)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     _runZoned (dart:async/zone.dart:1518)
#15     runZoned (dart:async/zone.dart:1502)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:740)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
#21     _rootRunUnary (dart:async/zone.dart:1134)
#22     _CustomZone.runUnary (dart:async/zone.dart:1031)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#33     _rootRunUnary (dart:async/zone.dart:1134)
#34     _CustomZone.runUnary (dart:async/zone.dart:1031)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#46     _rootRunUnary (dart:async/zone.dart:1134)
#47     _CustomZone.runUnary (dart:async/zone.dart:1031)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#51     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#52     _StreamController._add (dart:async/stream_controller.dart:639)
#53     _StreamController.add (dart:async/stream_controller.dart:585)
#54     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
#55     _rootRunUnary (dart:async/zone.dart:1138)
#56     _CustomZone.runUnary (dart:async/zone.dart:1031)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#60     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#61     _StreamController._add (dart:async/stream_controller.dart:639)
#62     _StreamController.add (dart:async/stream_controller.dart:585)
#63     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#64     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#67     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "<path-to-package>",
        "explicitFileCount": 8,
        "implicitFileCount": 1252,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment]
I'm seeing this intermittently in Dart Code's integration tests too (for `CONVERT_METHOD_TO_GETTER`):

```text
[14:48:09 GMT+0000 (UTC)] [Analyzer] [Error] NoSuchMethodError: The getter 'potentialEditIds' was called on null.
Receiver: null
Tried calling: potentialEditIds
[14:48:09 GMT+0000 (UTC)] [General] [Error] [Analyzer] NoSuchMethodError: The getter 'potentialEditIds' was called on null.
Receiver: null
Tried calling: potentialEditIds
[14:48:09 GMT+0000 (UTC)] [Analyzer] [Error] #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:874:55)
<asynchronous suspension>
#2      _rootRun (dart:async/zone.dart:1124:13)
#3      _CustomZone.run (dart:async/zone.dart:1021:19)
#4      _runZoned (dart:async/zone.dart:1516:10)
#5      runZoned (dart:async/zone.dart:1500:12)
#6      _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:829:5)
#7      EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:668:24)
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:366:16)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:645:45)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:641:50)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:640:5)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#52     _StreamController._add (dart:async/stream_controller.dart:639:7)
#53     _StreamController.add (dart:async/stream_controller.dart:585:5)
#54     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#55     _rootRunUnary (dart:async/zone.dart:1136:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#61     _StreamController._add (dart:async/stream_controller.dart:639:7)
#62     _StreamController.add (dart:async/stream_controller.dart:585:5)
#63     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#67     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/87842/
