### ISSUE TITLE
Decide how to handle errors with parts.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33587]
There are two kinds of errors:

1. A file with `part of` is imported, see https://github.com/dart-lang/sdk/issues/30959.

2. A file without `part of` is used in `part 'xyz.dart'`. This causes the file to be both a part and a library, and later causes exception. We can filter out such extra libraries, which are also used as parts on the analyzer side. Just not sure if this is expected behavior.

```
  #0      SourceLibraryBuilder.addPart (package:front_end/src/fasta/source/source_library_builder.dart:321:22)
  #1      KernelLibraryBuilder.addPart (package:front_end/src/fasta/kernel/kernel_library_builder.dart:873:11)
  #2      OutlineBuilder.endPart (package:front_end/src/fasta/source/outline_builder.dart:278:13)
  #3      Parser.parsePart (package:front_end/src/fasta/parser/parser.dart:946:14)
  #4      Parser.parsePartOrPartOf (package:front_end/src/fasta/parser/parser.dart:931:14)
  #5      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:576:16)
  #6      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:444:14)
  #7      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:324:15)
  #8      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:195:37)
  <asynchronous suspension>
  #9      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
  <asynchronous suspension>
  #10     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:237:20)
  <asynchronous suspension>
  #11     FrontEndCompiler.getResolution.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/frontend_resolution.dart:302:30)
```

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
