### ISSUE TITLE
language_2/const_constructor_nonconst_param_test/01 fails in dartkp mode

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#33604]
```
FAILED: dartkp-dart_precompiled debug_x64 language_2/const_constructor_nonconst_param_test/01
Expected: Pass
Actual: DartkCrash
Missing expected compile error.
--- Command "vm_compile_to_kernel" (took 381ms):
DART_CONFIGURATION=DebugX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --strong-mode --sync-async --platform=out/DebugX64/vm_platform_strong.dill -o /b/s/w/ir/out/DebugX64/generated_compilations/dartkp-strong/multitest_language_2_const_constructor_nonconst_param_test_01/out.dill --entry-points out/DebugX64/gen/runtime/bin/precompiler_entry_points.json --entry-points /b/s/w/ir/pkg/vm/lib/transformations/type_flow/entry_points_extra.json --entry-points /b/s/w/ir/pkg/vm/lib/transformations/type_flow/entry_points_extra_standalone.json /b/s/w/ir/out/DebugX64/generated_tests/language_2/const_constructor_nonconst_param_test_01.dart
exit code:
-10
stderr:
Exception: No support for Null.runtimeType
#0      ConstantEvaluator.ensureIsSubtype (package:kernel/transformations/constants.dart:1050:7)
#1      ConstantEvaluator.visitAsExpression (package:kernel/transformations/constants.dart:988:5)
#2      AsExpression.accept (package:kernel/ast.dart:3165:36)
#3      ConstantEvaluator.evaluatePositionalArguments.<anonymous closure> (package:kernel/transformations/constants.dart:1078:19)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#5      ListIterable.toList (dart:_internal/iterable.dart:219)
#6      ConstantEvaluator.evaluatePositionalArguments (package:kernel/transformations/constants.dart:1079:8)
#7      ConstantEvaluator.visitConstructorInvocation (package:kernel/transformations/constants.dart:526:25)
#8      ConstructorInvocation.accept (package:kernel/ast.dart:2921:36)
#9      ConstantEvaluator.evaluate (package:kernel/transformations/constants.dart:402:37)
#10     ConstantsTransformer.tryEvaluateWithContext (package:kernel/transformations/constants.dart:347:34)
#11     ConstantsTransformer.tryEvaluateAndTransformWithContext (package:kernel/transformations/constants.dart:340:31)
#12     ConstantsTransformer.visitConstructorInvocation (package:kernel/transformations/constants.dart:334:14)
#13     ConstructorInvocation.accept (package:kernel/ast.dart:2921:36)
#14     FieldInitializer.transformChildren (package:kernel/ast.dart:1771:21)
#15     Transformer.defaultTreeNode (package:kernel/visitor.dart:435:10)
#16     TreeVisitor.defaultInitializer (package:kernel/visitor.dart:235:45)
#17     TreeVisitor.visitFieldInitializer (package:kernel/visitor.dart:238:53)
#18     FieldInitializer.accept (package:kernel/ast.dart:1762:37)
#19     transformList (package:kernel/ast.dart:5740:27)
#20     ConstantsTransformer.visitConstructor.<anonymous closure> (package:kernel/transformations/constants.dart:158:7)
#21     ConstantEvaluator.withNewEnvironment (package:kernel/transformations/constants.dart:1110:16)
#22     ConstantsTransformer.visitConstructor (package:kernel/transformations/constants.dart:156:23)
#23     Constructor.accept (package:kernel/ast.dart:1297:32)
#24     transformList (package:kernel/ast.dart:5740:27)
#25     ConstantsTransformer.visitClass.<anonymous closure> (package:kernel/transformations/constants.dart:140:7)
#26     ConstantEvaluator.withNewEnvironment (package:kernel/transformations/constants.dart:1110:16)
#27     ConstantsTransformer.visitClass (package:kernel/transformations/constants.dart:136:23)
#28     Class.accept (package:kernel/ast.dart:905:30)
#29     transformList (package:kernel/ast.dart:5740:27)
#30     ConstantsTransformer.convertLibrary (package:kernel/transformations/constants.dart:108:5)
#31     transformLibraries (package:kernel/transformations/constants.dart:73:26)
#32     transformComponent (package:kernel/transformations/constants.dart:45:3)
#33     _performConstantEvaluation.<anonymous closure> (package:vm/kernel_front_end.dart:164:5)
<asynchronous suspension>
#34     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#35     new Future.sync (dart:async/future.dart:222)
#36     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#37     _rootRun (dart:async/zone.dart:1126)
#38     _CustomZone.run (dart:async/zone.dart:1023)
#39     _runZoned (dart:async/zone.dart:1518)
#40     runZoned (dart:async/zone.dart:1465)
#41     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#42     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:126:41)
#43     _performConstantEvaluation (package:vm/kernel_front_end.dart:152:25)
<asynchronous suspension>
#44     _runGlobalTransformations (package:vm/kernel_front_end.dart:122:13)
<asynchronous suspension>
#45     compileToKernel (package:vm/kernel_front_end.dart:72:11)
<asynchronous suspension>
#46     compile (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:126:27)
<asynchronous suspension>
#47     runBatchModeCompiler.<anonymous closure> (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:166:28)
<asynchronous suspension>
#48     runBatch (package:kernel/src/tool/batch_util.dart:38:35)
<asynchronous suspension>
#49     runBatchModeCompiler (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:152:9)
<asynchronous suspension>
#50     main (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:68:11)
<asynchronous suspension>
#51     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
--- Re-run this test:
python tools/test.py -m debug -c dartkp -r dart_precompiled --strong --output-directory /b/s/w/iobnpBYA --vm-options --no-enable-malloc-hooks language_2/const_constructor_nonconst_param_test/01
```

**Comment by mraleph** [comment]
Please take a look @mkustermann. I am going to mark this test as failing for now.
