### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/sdk#33600]
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Opening Flutter clone on newly created branch

### Versions

- Dart SDK 2.0.0-edge.4c9689c1d2da97d0aa25cf16cc90c2e463ad157f
- Visual Studio Code 1.24.1
- Dart Code 2.15.0-beta.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\Entwicklung\Flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.15.0-beta.1
--instrumentation-log-file=c:\\temp\DartAnalysisInstrument.log
```

### Exception (fatal)

Failed to handle request: {id: 12, method: analysis.setAnalysisRoots, params: {excluded: [], included: [C:\Entwicklung\Flutter]}}

```text
NoSuchMethodError: The method 'removeFile' was called on null.
Receiver: null
Tried calling: removeFile("C:\\Entwicklung\\Flutter\\version")
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ServerContextManagerCallbacks.applyFileRemoved (package:analysis_server/src/analysis_server.dart:1367)
#2      ContextManagerImpl._handleWatchEventImpl (package:analysis_server/src/context_manager.dart:1447)
#3      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1334)
#4      _rootRunUnary (dart:async/zone.dart:1134)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#10     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98)
#11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#12     _rootRunUnary (dart:async/zone.dart:1134)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#17     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:379)
#18     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254)
#19     _rootRunUnary (dart:async/zone.dart:1134)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#23     _DelayedData.perform (dart:async/stream_impl.dart:584)
#24     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700)
#25     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660)
#26     _rootRun (dart:async/zone.dart:1122)
#27     _CustomZone.run (dart:async/zone.dart:1023)
#28     _CustomZone.runGuarded (dart:async/zone.dart:925)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     _CustomZone.runGuarded (dart:async/zone.dart:925)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#36     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#37     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[]
```

**Comment by scheglov** [comment]
Thank you for the report.
Unfortunately I was not able to find out why it happened.

There is a short period of time when `ContextInfo` is already created and put into data structures, but `analysisDriver` is not yet set. But it happens not is async code, so it should not be interrupted by async file system watcher.

There is also similar issue https://github.com/dart-lang/sdk/issues/34342

**Comment by srawlins** [comment]
This occurred again in February, with 2.1.0-dev. https://github.com/dart-lang/sdk/issues/35877

**Comment by srawlins** [comment]
This has not been reported again since 2.1.0.
