### ISSUE TITLE
Analyzer crash when analyzing co19 strong_mode branch

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#33614]
The command-line dartanalyzer on bleeding-edge crashes when analyzing the entire source directory of the co19 tests strong_mode branch.  After checking out the most recent commit to dart.googlesource.com/co19 strong_mode branch into tests/co19_2/src, the command gives a stack trace:  I will try and pin this down with a more precise reproduction.

```
whesse@mcvoodie:~/ssd/sdk$ out/ReleaseX64/dart-sdk/bin/dartanalyzer tests/co19_2/src/
Analyzing tests/co19_2/src...
Unhandled exception:
NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      InterfaceTypeImpl.typeArguments (package:analyzer/src/dart/element/type.dart:1395:26)
#2      InterfaceTypeImpl.appendTo (package:analyzer/src/dart/element/type.dart:1431:27)
#3      TypeImpl.toString (package:analyzer/src/dart/element/type.dart:2503:5)
#4      _StringBase._interpolateSingle (dart:core/runtime/libstring_patch.dart:799:17)
#5      StringBuffer.write (dart:core/runtime/libstring_buffer_patch.dart:64:24)
#6      TypeParameterElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:9633:14)
#7      ClassElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:1098:57)
#8      ElementImpl.toString (package:analyzer/src/dart/element/element.dart:3607:5)
#9      _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:817:19)
#10     new _ElementMismatchException (package:analyzer/src/generated/declaration_resolver.dart:1016:65)
#11     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:74:17)
#12     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:684:10)
#13     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:130:9)
#14     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
#15     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:129:13)
#16     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:104:16)
<asynchronous suspension>
#17     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#18     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:98:43)
<asynchronous suspension>
#19     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1283:71)
<asynchronous suspension>
#20     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#21     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1240:20)
<asynchronous suspension>
#22     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:652:43)
<asynchronous suspension>
#23     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:130:58)
<asynchronous suspension>
#24     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:170:11)
<asynchronous suspension>
#25     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:106:18)
<asynchronous suspension>
#26     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:763:21)
#27     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:384:40)
<asynchronous suspension>
#28     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:241:20)
<asynchronous suspension>
#29     Driver.start (package:analyzer_cli/src/driver.dart:208:38)
<asynchronous suspension>
#30     main (file:///usr/local/google/home/whesse/ssd/sdk/pkg/analyzer_cli/bin/analyzer.dart:13:17)
<asynchronous suspension>
#31     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#32     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1323:9)
<asynchronous suspension>
#1      PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1240:20)
<asynchronous suspension>
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:652:43)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:130:58)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:170:11)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:106:18)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:763:21)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:384:40)
<asynchronous suspension>
#9      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:241:20)
<asynchronous suspension>
#10     Driver.start (package:analyzer_cli/src/driver.dart:208:38)
<asynchronous suspension>
#11     main (file:///usr/local/google/home/whesse/ssd/sdk/pkg/analyzer_cli/bin/analyzer.dart:13:17)
<asynchronous suspension>
#12     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by scheglov** [comment]
Same as https://github.com/dart-lang/sdk/issues/33477, which has an example, and can be reproduced.
