### ISSUE TITLE
Subclass named constructor collides with superclass static field

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#33621]
In DDC, if I compile and run this program:

```dart
class Foo {
  static final baz = new Bar.baz();
}

class Bar extends Foo {
  Bar.baz();
}

main() {
  print(new Bar.baz());
}
```

It compiles without error and then throws an exception at runtime (here node, but similar occurs in a browser):

```
(temp.Bar.baz = function() {
              ^

TypeError: Cannot set property baz of class Foo extends core.Object {} which has only a getter
    at Object.<anonymous> (/Users/rnystrom/temp/temp.js:18:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rnystrom/temp/temp.run.js:9:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

I'm guessing this is because ECMAScript inherits static members on classes so the final field `baz` field in Foo prevents adding the `foo` named constructor when executing the declaration of Bar.

**Comment by jmesserly** [comment]
This should be an easy fix, we need to use the `defineValue` helper to define a property (via Object.defineProperty) rather than relying on `=`.

(We could always define properties, but it's smaller/cleaner looking to use `=` where possible, so we typically implement this sort of thing as "use = if possible, otherwise use defineValue")

**Comment by jmesserly** [comment]
fixed in https://dart-review.googlesource.com/c/sdk/+/83563 (may need to add a test to that CL, if no existing test covers it)
