### ISSUE TITLE
Fatal server error if content is modified to make an in-flight getAvailableRefactorings request invalid

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33623]
If you send an `updateContent` while a `getAvaialbleRefactorings` is in-progress, you can cause a fatal server error. I hit this in tests but probably this is a race the user could cause (VS Code sends the request for refactors when the use pauses typing, so if they cleared the document right after Code sent that, they'd probably get this).

I got this on v2.0.0-dev.64.1 (it may be related to #33471 which is the issue I was testing a fix for).

```
[07:28:49]: ==> {"id":"7","method":"analysis.updateContent","params":{"files":{"/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart":{"edits":[{"id":"","length":0,"offset":0,"replacement":"\nmain() {\n  print(\"test\n}\n\t\t"}],"type":"change"}}}}
[07:28:49]: <== {"id":"7","result":{}}
[07:28:49]: ==> {"id":"9","method":"edit.getAvailableRefactorings","params":{"file":"/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart","length":0,"offset":23}}
[07:28:49]: ==> {"id":"12","method":"analysis.updateContent","params":{"files":{"/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart":{"edits":[{"id":"","length":0,"offset":24,"replacement":"  \n"}],"type":"change"}}}}
[07:28:49]: ==> {"id":"13","method":"analysis.updateContent","params":{"files":{"/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart":{"edits":[{"id":"","length":0,"offset":23,"replacement":";"}],"type":"change"}}}}
[07:28:49]: ==> {"id":"14","method":"analysis.updateContent","params":{"files":{"/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart":{"edits":[{"id":"","length":0,"offset":23,"replacement":")"}],"type":"change"}}}}
[07:28:49]: ==> {"id":"15","method":"analysis.updateContent","params":{"files":{"/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart":{"edits":[{"id":"","length":0,"offset":23,"replacement":"\""}],"type":"change"}}}}
[07:28:49]: ==> {"id":"16","method":"edit.getAvailableRefactorings","params":{"file":"/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart","length":0,"offset":26}}
[07:28:49]: ==> {"id":"19","method":"analysis.updateContent","params":{"files":{"/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart":{"edits":[{"id":"","length":34,"offset":0,"replacement":""}],"type":"change"}}}}
[07:28:49]: ==> {"id":"20","method":"analysis.updateContent","params":{"files":{"/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}}}
[07:28:49]: <== {"id":"12","result":{}}
[07:28:49]: <== {"id":"13","result":{}}
[07:28:49]: <== {"id":"14","result":{}}
[07:28:49]: <== {"id":"15","result":{}}
[07:28:49]: <== {"id":"19","result":{}}
[07:28:49]: <== {"id":"20","result":{}}
[07:28:49]: <== {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 16, method: edit.getAvailableRefactorings, params: {file: /Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/empty.dart, length: 0, offset: 26}}","stackTrace":"
RangeError: Value not in range: 26
#0      _StringBase.substring (dart:core/runtime/libstring_patch.dart:366:7)
#1      CorrectionUtils.getText (package:analysis_server/src/services/correction/util.dart:949:20)
#2      CorrectionUtils.getRangeText (package:analysis_server/src/services/correction/util.dart:942:12)
#3      ExtractLocalRefactoringImpl._checkSelection (package:analysis_server/src/services/refactoring/extract_local.dart:233:28)
#4      ExtractLocalRefactoringImpl.isAvailable (package:analysis_server/src/services/refactoring/extract_local.dart:219:13)
#5      EditDomainHandler._getAvailableRefactoringsImpl (package:analysis_server/src/edit/edit_domain.dart:602:14)
<asynchronous suspension>
#6      EditDomainHandler._getAvailableRefactorings (package:analysis_server/src/edit/edit_domain.dart:580:5)
#7      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:345:16)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:746:45)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:742:50)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1502:12)
#15     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:741:5)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#17     …
```

**Comment by leonsenft** [comment]
Just encountered this. I indeed saw the crash when deleting an identifier I auto-completed incorrectly.

**Comment by leonsenft** [comment]
Is this not a duplicate of https://github.com/dart-lang/sdk/issues/33471?

**Comment by DanTup** [comment]
Ugh, I don't know what I was thinking when I raised this - it looked different to me, but it's actually the same!
