### ISSUE TITLE
Include import prefixes on type error messages - CFE

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#33667]
Take the following code:

```dart
import 'dart:math' as math;

class Random {}

void main() {
  List<Random> list = <Random>[];
  addRandom(list);
}

addRandom(List<math.Random> list) => list..add(new math.Random());
```

Running this on the VM (2.0.0-dev.63.0, --preview-dart-2), I get this error:

```none
a.dart:7:13: Error: A value of type 'dart.core::List<#lib1::Random>' can't be assigned to a variable of type 'dart.core::List<dart.math::Random>'.
Try changing the type of the left hand side, or casting the right hand side to 'dart.core::List<dart.math::Random>'.
  addRandom(list);
            ^
```

In this example, the library names are short (`#lib1` and `dart.math`, but in real code, they can be much longer, `foo.bar.baz.service.impl.fake::Random` can't be assigned to `foo.bar.other.proto.service.pb::Random`. I think the user's prefixes should be respected here, if there are any. The user wrote the prefixes to understand their own code better, and to separate possibly conflicting members. We should respect that:

```none
a.dart:7:13: Error: A value of type 'dart.core::List<#lib1::Random>' can't be assigned to a variable of type 'dart.core::List<dart.math::math.Random>'.
Try changing the type of the left hand side, or casting the right hand side to 'dart.core::List<dart.math::math.Random>'.
```

(Or better yet:

```none
a.dart:7:13: Error: A value of type 'List<Random>' can't be assigned to a variable of type 'List<math.Random>'.
Try changing the type of the left hand side, or casting the right hand side to 'List<math.Random>'.
```

but I won't get into library-name issues in this issue.)

I'll file separate issues for analyzer, DDC, and dart2js.

**Comment by mraleph** [comment]
This is not a runtime type error message - it is a compile time error message, coming from CFE.

**Comment by srawlins** [comment]
Eek, my bad. I'm getting a similar DDC runtime one, and made a wrong assumption.

**Comment by srawlins** [comment]
FWIW here's a runtime VM issue:

```dart
import 'dart:math' as math;

// Poorly named wrapper for math.Random
class Random {
  math.Random inner;

  Random(this.inner);
}

void main() {
  List<Random> list = new List<Random>()..add(new Random(new math.Random(7)));
  addRandom(list.map((e) => e.inner));
}

addRandom(List<math.Random> list) => list..add(new math.Random());
```

```none
$ dart --preview-dart-2 b.dart 
Unhandled exception:
type 'MappedListIterable<Random, Random>' is not a subtype of type 'List<Random>' where
  Random is from dart:math
  Random is from file:///Users/srawlins/code/b.dart

#0      main (file:///Users/srawlins/code/b.dart:12:18)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

I see three `Random`s that need specifying, 2 in `MappedListIterable<Random, Random>` and 1 in `List<Random>`. What do these refer to:

```
  Random is from dart:math
  Random is from file:///Users/srawlins/code/b.dart
```

??? The user prefixes from the source would really help here:

```none 
type 'MappedListIterable<Random, math.Random>' is not a subtype of type 'List<math.Random>' where
  math.Random is from dart:math
  Random is from file:///Users/srawlins/code/b.dart
```

I can open a separate issue if desired.

**Comment by askeksa-google** [comment]
This issue is obsolete since https://dart-review.googlesource.com/c/sdk/+/84604 landed.

**Comment by srawlins** [comment]
Very nice, thank you!
