### ISSUE TITLE
analysis server crash -dev.65 - adding an annotation to the top of a test file

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33681]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5281.24`
- `2.0.0-dev.65.0`
- `IU-181.5281.24, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.5 unknown, screens 3840x2160`

# Exception

```
Dart analysis server, SDK version 2.0.0-dev.65.0, server version 1.20.3, error: Failed to handle completion domain request: {id: 4528, method: completion.getSuggestions, params: {file: /Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart, offset: 234}, clientRequestTime: 1530211406860}
type 'PrefixedIdentifierImpl' is not a subtype of type 'SimpleIdentifier'
#0      _getTargetId (package:analysis_server/src/services/completion/dart/arglist_contributor.dart)
#1      ArgListContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/arglist_contributor.dart:189:33)
<asynchronous suspension>
#2      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:110:29)
<asynchronous suspension>
#3      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:98:46)
<asynchronous suspension>
#4      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:209:5)
<asynchronous suspension>
#5      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:144:9)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1502:12)
#10     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:141:12)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:746:45)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:742:50)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1502:12)
#18     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:741:5)
#19     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#21     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#22     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#23     _rootRunUnary (dart:async/zone.dart:1134:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#30     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#31     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#32     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#33     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#34     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#35     _rootRunUnary (dart:async/zone.dart:1134:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#40     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#41     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#42     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#43     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#44     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#45     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#46     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#48     _rootRunUnary (dart:async/zone.dart:1134:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#53     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#54     _StreamController._add (dart:async/stream_controller.dart:639:7)
#55     _StreamController.add (dart:async/stream_controller.dart:585:5)
#56     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1672:41)
#57     _rootRunUnary (dart:async/zone.dart:1138:13)
#58     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#62     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#63     _StreamController._add (dart:async/stream_controller.dart:639:7)
#64     _StreamController.add (dart:async/stream_controller.dart:585:5)
#65     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1245:33)
#66     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:797:14)
#67     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#68     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#69     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#70     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

```
1530211404481 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","classes":[],"members":[]}}
1530211404942 => {"id":"4525","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart":{"type":"add","content":"
1530211404943 <= {"id":"4525","result":{}}
1530211404943 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1530211404966 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_T
1530211404966 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","regions":[{"type":"DIRECTIVE","offset":217
1530211404967 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","regions":[{"offset":230,"length":12,"targe
1530211404967 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","labels":[]}}
1530211404968 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","kind":"LIBRARY","outline":{"element":{"kind":
1530211404968 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","overrides":[]}}
1530211404970 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1530211404970 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","classes":[],"members":[]}}
1530211406634 => {"id":"4526","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart":{"type":"add","content":"
1530211406635 <= {"id":"4526","result":{}}
1530211406635 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1530211406670 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_T
1530211406671 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","regions":[{"type":"DIRECTIVE","offset":217
1530211406672 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","regions":[{"offset":218,"length":7,"target
1530211406672 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","labels":[]}}
1530211406672 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","kind":"LIBRARY","outline":{"element":{"kind":
1530211406672 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","overrides":[]}}
1530211406674 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1530211406674 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","classes":[],"members":[]}}
1530211406860 => {"id":"4527","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart":{"type":"add","content":"
1530211406860 => {"id":"4528","method":"completion.getSuggestions","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","offset":234},"clientReq
1530211406861 <= {"id":"4527","result":{}}
1530211406861 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1530211406885 <= {"id":"4528","result":{"id":"548"}}
1530211406885 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/webdev/e2e_getting_started/test/e2e_getting_started_test.dart","errors":[]}}
1530211406892 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {id: 4528, method: completion.getSuggestions, params: {file: /Users/kevmoo/sou
```

```

**Comment by scheglov** [comment]
@bwilkerson fixed this as https://github.com/dart-lang/sdk/issues/34227
