### ISSUE TITLE
dartanalyzer doesn't recognize config file

### ISSUE THREAD

**Issue by l7ssha** [dart-lang/sdk#33706]
Hi,
Today I've observed some weird behavior on `dartanalyzer`. It seems to dont recognize any element of config file.

My config file: https://github.com/l7ssha/nyxx/blob/development/analysis_options.yaml
Output of command: [log.txt](https://github.com/dart-lang/sdk/files/2149740/log.txt)
Command I'm using: `dartanalyzer analysis_options.yaml . >> log.txt`

* Dart SDK Version: `1.24.3 (Wed Dec 13 16:10:39 2017) on "linux_x64"`
* OS: `Linux lushke 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux`

**Comment by bwilkerson** [comment]
I don't understand. What were you expecting to see that you didn't see? (And if it's important, what directory were you in (so I know what '.' refers to).

**Comment by l7ssha** [comment]
`.` refers to same directory as `analysis_options.yaml`, so it can analyze all project files. I don't understand you too - `dartanalyzer` has problem with recognizing all fields in config files, so basically something is wrong.

**Comment by zoechi** [comment]
Looks like the analyzer treats `analysis_options.yaml` like it were a `*.dart` file

**Comment by bwilkerson** [comment]
Might be related to #27375.

> ... has problem with recognizing all fields in config files ...

If you mean "all" literally, that would imply that it's not finding the analysis options file. If it used some of the information but not all, then that would point to a different likely cause.

**Comment by zoechi** [comment]
Log file content from the initial comment
```
Analyzing analysis_options.yaml, nyx...
  error • Undefined class 'analyzer' at analysis_options.yaml:1:1 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:1:9 • expected_executable
  error • Unexpected text ':' at analysis_options.yaml:1:9 • unexpected_token
  error • Undefined class 'strong' at analysis_options.yaml:2:3 • undefined_class
  error • The name '' is already defined at analysis_options.yaml:2:9 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:2:9 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:2:9 • unexpected_token
  error • Undefined class 'mode' at analysis_options.yaml:2:10 • undefined_class
  error • The name '' is already defined at analysis_options.yaml:2:14 • duplicate_definition
  error • Unexpected text ':' at analysis_options.yaml:2:14 • unexpected_token
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:2:14 • expected_executable
  error • Undefined class 'linter' at analysis_options.yaml:3:1 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:3:7 • expected_executable
  error • Unexpected text ':' at analysis_options.yaml:3:7 • unexpected_token
  error • The name '' is already defined at analysis_options.yaml:3:7 • duplicate_definition
  error • Undefined class 'rules' at analysis_options.yaml:4:3 • undefined_class
  error • Unexpected text ':' at analysis_options.yaml:4:8 • unexpected_token
  error • The name '' is already defined at analysis_options.yaml:4:8 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:4:8 • expected_executable
  error • Undefined class 'avoid_empty_else' at analysis_options.yaml:5:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:6:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:6:5 • unexpected_token
  error • The name '' is already defined at analysis_options.yaml:6:5 • duplicate_definition
  error • Undefined class 'comment_references' at analysis_options.yaml:6:7 • undefined_class
  error • Unexpected text '-' at analysis_options.yaml:7:5 • unexpected_token
  error • The name '' is already defined at analysis_options.yaml:7:5 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:7:5 • expected_executable
  error • Undefined class 'control_flow_in_finally' at analysis_options.yaml:7:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:8:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:8:5 • unexpected_token
  error • The name '' is already defined at analysis_options.yaml:8:5 • duplicate_definition
  error • Undefined class 'empty_statements' at analysis_options.yaml:8:7 • undefined_class
  error • Unexpected text '-' at analysis_options.yaml:9:5 • unexpected_token
  error • The name '' is already defined at analysis_options.yaml:9:5 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:9:5 • expected_executable
  error • Undefined class 'hash_and_equals' at analysis_options.yaml:9:7 • undefined_class
  error • Unexpected text '-' at analysis_options.yaml:10:5 • unexpected_token
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:10:5 • expected_executable
  error • The name '' is already defined at analysis_options.yaml:10:5 • duplicate_definition
  error • Undefined class 'iterable_contains_unrelated_type' at analysis_options.yaml:10:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:11:5 • expected_executable
  error • The name '' is already defined at analysis_options.yaml:11:5 • duplicate_definition
  error • Unexpected text '-' at analysis_options.yaml:11:5 • unexpected_token
  error • Undefined class 'list_remove_unrelated_type' at analysis_options.yaml:11:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:12:5 • expected_executable
  error • The name '' is already defined at analysis_options.yaml:12:5 • duplicate_definition
  error • Unexpected text '-' at analysis_options.yaml:12:5 • unexpected_token
  error • Undefined class 'test_types_in_equals' at analysis_options.yaml:12:7 • undefined_class
  error • The name '=' is already defined at analysis_options.yaml:13:5 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:13:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:13:5 • unexpected_token
  error • Undefined class 'throw_in_finally' at analysis_options.yaml:13:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:14:5 • expected_executable
  error • The name '=' is already defined at analysis_options.yaml:14:5 • duplicate_definition
  error • Unexpected text '-' at analysis_options.yaml:14:5 • unexpected_token
  error • Undefined class 'unrelated_type_equality_checks' at analysis_options.yaml:14:7 • undefined_class
  error • Unexpected text '-' at analysis_options.yaml:15:5 • unexpected_token
  error • The name '=' is already defined at analysis_options.yaml:15:5 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:15:5 • expected_executable
  error • Undefined class 'valid_regexps' at analysis_options.yaml:15:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:16:5 • expected_executable
  error • The name '=' is already defined at analysis_options.yaml:16:5 • duplicate_definition
  error • Unexpected text '-' at analysis_options.yaml:16:5 • unexpected_token
  error • Undefined class 'always_declare_return_types' at analysis_options.yaml:16:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:17:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:17:5 • unexpected_token
  error • The name '=' is already defined at analysis_options.yaml:17:5 • duplicate_definition
  error • Undefined class 'annotate_overrides' at analysis_options.yaml:17:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:18:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:18:5 • unexpected_token
  error • The name '=' is already defined at analysis_options.yaml:18:5 • duplicate_definition
  error • Undefined class 'avoid_init_to_null' at analysis_options.yaml:18:7 • undefined_class
  error • Unexpected text '-' at analysis_options.yaml:19:5 • unexpected_token
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:19:5 • expected_executable
  error • The name '=' is already defined at analysis_options.yaml:19:5 • duplicate_definition
  error • Undefined class 'avoid_return_types_on_setters' at analysis_options.yaml:19:7 • undefined_class
  error • Unexpected text '-' at analysis_options.yaml:20:5 • unexpected_token
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:20:5 • expected_executable
  error • The name '=' is already defined at analysis_options.yaml:20:5 • duplicate_definition
  error • Undefined class 'await_only_futures' at analysis_options.yaml:20:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:21:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:21:5 • unexpected_token
  error • The name '=' is already defined at analysis_options.yaml:21:5 • duplicate_definition
  error • Undefined class 'camel_case_types' at analysis_options.yaml:21:7 • undefined_class
  error • Unexpected text '-' at analysis_options.yaml:22:5 • unexpected_token
  error • The name '' is already defined at analysis_options.yaml:22:5 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:22:5 • expected_executable
  error • Undefined class 'constant_identifier_names' at analysis_options.yaml:22:7 • undefined_class
  error • The name '' is already defined at analysis_options.yaml:23:5 • duplicate_definition
  error • Unexpected text '-' at analysis_options.yaml:23:5 • unexpected_token
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:23:5 • expected_executable
  error • Undefined class 'empty_catches' at analysis_options.yaml:23:7 • undefined_class
  error • The name '' is already defined at analysis_options.yaml:24:5 • duplicate_definition
  error • Unexpected text '-' at analysis_options.yaml:24:5 • unexpected_token
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:24:5 • expected_executable
  error • Undefined class 'empty_constructor_bodies' at analysis_options.yaml:24:7 • undefined_class
  error • Unexpected text '-' at analysis_options.yaml:25:5 • unexpected_token
  error • The name '' is already defined at analysis_options.yaml:25:5 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:25:5 • expected_executable
  error • Undefined class 'library_names' at analysis_options.yaml:25:7 • undefined_class
  error • The name '' is already defined at analysis_options.yaml:26:5 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:26:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:26:5 • unexpected_token
  error • Undefined class 'library_prefixes' at analysis_options.yaml:26:7 • undefined_class
  error • The name '' is already defined at analysis_options.yaml:27:5 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:27:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:27:5 • unexpected_token
  error • Undefined class 'non_constant_identifier_names' at analysis_options.yaml:27:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:28:5 • expected_executable
  error • The name '' is already defined at analysis_options.yaml:28:5 • duplicate_definition
  error • Unexpected text '-' at analysis_options.yaml:28:5 • unexpected_token
  error • Undefined class 'only_throw_errors' at analysis_options.yaml:28:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:29:5 • expected_executable
  error • The name '' is already defined at analysis_options.yaml:29:5 • duplicate_definition
  error • Unexpected text '-' at analysis_options.yaml:29:5 • unexpected_token
  error • Undefined class 'overridden_fields' at analysis_options.yaml:29:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:30:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:30:5 • unexpected_token
  error • The name '' is already defined at analysis_options.yaml:30:5 • duplicate_definition
  error • Undefined class 'package_api_docs' at analysis_options.yaml:30:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:31:5 • expected_executable
  error • The name '' is already defined at analysis_options.yaml:31:5 • duplicate_definition
  error • Unexpected text '-' at analysis_options.yaml:31:5 • unexpected_token
  error • Undefined class 'package_prefixed_library_names' at analysis_options.yaml:31:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:32:5 • expected_executable
  error • The name '=' is already defined at analysis_options.yaml:32:5 • duplicate_definition
  error • Unexpected text '-' at analysis_options.yaml:32:5 • unexpected_token
  error • Undefined class 'prefer_is_not_empty' at analysis_options.yaml:32:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:33:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:33:5 • unexpected_token
  error • The name '=' is already defined at analysis_options.yaml:33:5 • duplicate_definition
  error • Undefined class 'public_member_api_docs' at analysis_options.yaml:33:7 • undefined_class
  error • The name '=' is already defined at analysis_options.yaml:34:5 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:34:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:34:5 • unexpected_token
  error • Undefined class 'slash_for_doc_comments' at analysis_options.yaml:34:7 • undefined_class
  error • Unexpected text '-' at analysis_options.yaml:35:5 • unexpected_token
  error • The name '=' is already defined at analysis_options.yaml:35:5 • duplicate_definition
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:35:5 • expected_executable
  error • Undefined class 'sort_constructors_first' at analysis_options.yaml:35:7 • undefined_class
  error • Unexpected text '-' at analysis_options.yaml:36:5 • unexpected_token
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:36:5 • expected_executable
  error • The name '=' is already defined at analysis_options.yaml:36:5 • duplicate_definition
  error • Undefined class 'sort_unnamed_constructors_first' at analysis_options.yaml:36:7 • undefined_class
  error • Unexpected text '-' at analysis_options.yaml:37:5 • unexpected_token
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:37:5 • expected_executable
  error • The name '=' is already defined at analysis_options.yaml:37:5 • duplicate_definition
  error • Undefined class 'type_init_formals' at analysis_options.yaml:37:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:38:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:38:5 • unexpected_token
  error • The name '=' is already defined at analysis_options.yaml:38:5 • duplicate_definition
  error • Undefined class 'unnecessary_getters_setters' at analysis_options.yaml:38:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:39:5 • expected_executable
  error • Unexpected text '-' at analysis_options.yaml:39:5 • unexpected_token
  error • The name '=' is already defined at analysis_options.yaml:39:5 • duplicate_definition
  error • Undefined class 'package_names' at analysis_options.yaml:39:7 • undefined_class
  error • Expected a method, getter, setter or operator declaration at analysis_options.yaml:39:7 • expected_executable
  error • The name '=' is already defined at analysis_options.yaml:40:2 • duplicate_definition
  lint • Document all public members at example/commands-example.dart:15:7 • public_member_api_docs
  lint • Document all public members at example/commands-example.dart:16:3 • public_member_api_docs
  lint • Declare method return types at example/commands-example.dart:19:3 • always_declare_return_types
  lint • Document all public members at example/commands-example.dart:24:7 • public_member_api_docs
  lint • Document all public members at example/commands-example.dart:25:3 • public_member_api_docs
  lint • Declare method return types at example/commands-example.dart:29:3 • always_declare_return_types
  lint • Document all public members at test/discord.dart:8:7 • public_member_api_docs
  lint • Document all public members at test/discord.dart:9:3 • public_member_api_docs
  lint • Declare method return types at test/discord.dart:12:3 • always_declare_return_types
  lint • Document all public members at test/discord.dart:17:7 • public_member_api_docs
  lint • Document all public members at test/discord.dart:18:3 • public_member_api_docs
  lint • Declare method return types at test/discord.dart:24:3 • always_declare_return_types
  hint • The value of the local variable 'commands' isn't used at example/commands-example.dart:11:7 • unused_local_variable
  hint • 'sendMessage' is deprecated and shouldn't be used at example/commands-example.dart:20:27 • deprecated_member_use
  hint • 'sendMessage' is deprecated and shouldn't be used at example/commands-example.dart:30:27 • deprecated_member_use
  hint • 'sendMessage' is deprecated and shouldn't be used at example/ping-pong.dart:16:25 • deprecated_member_use
  hint • 'sendMessage' is deprecated and shouldn't be used at lib/src/commands/Commands.dart:77:12 • deprecated_member_use
  hint • 'sendMessage' is deprecated and shouldn't be used at test/discord.dart:13:27 • deprecated_member_use
  hint • The value of the local variable 'commandsListener' isn't used at test/discord.dart:33:7 • unused_local_variable
158 errors, 12 lints and 7 hints found.
```

**Comment by l7ssha** [comment]
@zoechi I've captured this error:
```
Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: Broken pipe, errno = 32)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:843)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:285)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#5      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#6      _StreamController._add (dart:async/stream_controller.dart:667)
#7      _StreamController.add (dart:async/stream_controller.dart:613)
#8      _StreamSinkImpl.add (dart:io/io_sink.dart:168)
#9      _IOSinkImpl.write (dart:io/io_sink.dart:302)
#10     _StdSink.write (dart:io/stdio.dart:314)
#11     HumanErrorFormatter.flush (package:analyzer_cli/src/error_formatter.dart:289)
#12     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:267)
<asynchronous suspension>
#13     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:166)
<asynchronous suspension>
#14     Driver.start (package:analyzer_cli/src/driver.dart:145)
<asynchronous suspension>
#15     main (file:///usr/local/google/home/whesse/ssd/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by natebosch** [comment]
@bwilkerson - the analysis server will give hints in analysis_options.yaml right?

I think this issue is asking to be able to see those hints when passing the file as an argument to `dartanalyzer` CLI instead of having it treat the file as Dart source and spew a bunch of errors since the syntax is not valid Dart.

**Comment by MichaelRFairhurst** [comment]
Can you check if you're importing your analysis options as if it were a dart file:

```
import 'analysis_options.yaml'; // should not do this!
```

This repro'd it or me, so it _might_ be the cause here?

**Comment by natebosch** [comment]
Ah yeah, I can't actually repro this issue as is....

**Comment by bwilkerson** [comment]
I'm assuming that this issue is stale. Please let me know if you're still seeing the issue.
