### ISSUE TITLE
Dart analysis server, SDK version 1.24.3, server version 1.18.0, 

### ISSUE THREAD

**Issue by PiaDeveloperBr** [dart-lang/sdk#33702]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4819257`
- `1.24.3`
- `AI-173.4819257, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.5 unknown, screens 1440x900`

# Exception

Please append the contents of:
file:///private/var/folders/yc/gbl9kr4n37nd4w0_ppx3l1dc0000gn/T/report.txt

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Analysis failed: Invalid argument(s): Cannot serialize an instance of GenericFunctionTypeImpl
#0      AbstractConstExprSerializer.serializeTypeName (package:analyzer/src/summary/summarize_const_expr.dart:211)
#1      AbstractConstExprSerializer._serializeListLiteral (package:analyzer/src/summary/summarize_const_expr.dart:550)
#2      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:356)
#3      AbstractConstExprSerializer.serialize (package:analyzer/src/summary/summarize_const_expr.dart:139)
#4      _SummarizeAstVisitor.serializeConstExpr (package:analyzer/src/summary/summarize_ast.dart:557)
#5      _SummarizeAstVisitor.serializeFunctionBody (package:analyzer/src/summary/summarize_ast.dart:755)
#6      _SummarizeAstVisitor.serializeInitializerFunction (package:analyzer/src/summary/summarize_ast.dart:828)
#7      _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:1029)
#8      _SummarizeAstVisitor.visitFieldDeclaration (package:analyzer/src/summary/summarize_ast.dart:1210)
#9      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399)
#10     _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:472)
#11     _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1076)

**Comment by devoncarew** [comment]
Thanks for the feedback! Closing due to the older sdk version (`1.24.3`).
