### ISSUE TITLE
Building SDK on ARM64 appears to be broken.

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#33728]
It fails in the `gclient sync` command:
```
XXXXX:~/dart-sdk$ gclient sync
Syncing projects: 100% (83/83), done.                                     
Running hooks:  21% ( 3/14) drt_resources  
________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --platform=win32 --directory sdk/third_party/drt_resources' in '/home/YYYYY/dart-sdk'
The current platform doesn't match "win32", skipping.
Running hooks:  35% ( 5/14) 7zip         
________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --platform=win32 --extract -s sdk/third_party/7zip.tar.gz.sha1' in '/home/YYYYY/dart-sdk'
The current platform doesn't match "win32", skipping.
nunning hooks:  50% ( 7/14) sysroot_i386
________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --arch i386' in '/home/YYYYY/dart-sdk'
Wheezy i386 sysroot image already up to date: /home/YYYYY/dart-sdk/sdk/build/linux/debian_wheezy_i386-sysroot
Running hooks:  57% ( 8/14) sysroot_amd64
________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --arch amd64' in '/home/YYYYY/dart-sdk'
Wheezy amd64 sysroot image already up to date: /home/YYYYY/dart-sdk/sdk/build/linux/debian_wheezy_amd64-sysroot
Jessie amd64 sysroot image already up to date: /home/YYYYY/dart-sdk/sdk/build/linux/debian_jessie_amd64-sysroot
Running hooks:  64% ( 9/14) sysroot_amd64
________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --arch arm' in '/home/YYYYY/dart-sdk'
Wheezy arm sysroot image already up to date: /home/YYYYY/dart-sdk/sdk/build/linux/debian_wheezy_arm-sysroot
Running hooks:  71% (10/14) sysroot_amd64
________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --arch arm64' in '/home/YYYYY/dart-sdk'
Jessie arm64 sysroot image already up to date: /home/YYYYY/dart-sdk/sdk/build/linux/debian_jessie_arm64-sysroot
Running hooks:  85% (12/14) buildtools            
________ running '/usr/bin/python sdk/tools/buildtools/update.py' in '/home/YYYYY/dart-sdk'
Not downloading buildtools binaries for aarch64
^Nnning hooks: 100% (14/14)              
________ running '/usr/bin/python sdk/tools/generate_buildfiles.py' in '/home/YYYYY/dart-sdk'
Traceback (most recent call last):
  File "/home/YYYYY/dart-sdk/sdk/tools/gn.py", line 512, in <module>
    sys.exit(Main(sys.argv))
  File "/home/YYYYY/dart-sdk/sdk/tools/gn.py", line 499, in Main
    results = pool.map(RunCommand, commands, chunksize=1)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 2] No such file or directory
Running hooks: 100% (14/14), done.
```

`gn` will not run, and it appears that the buildtools are messed up:
```
XXXXX:~/dart-sdk$ gn
gn.py: Could not find gn executable at: /home/YYYYY/dart-sdk/sdk/buildtools/linux64/gn
XXXXX:~/dart-sdk$ ls /home/YYYYY/dart-sdk/sdk/buildtools/
AUTHORS  cipd  clang_format  download.sh  exec_tool.sh  fuchsia.ensure  gn  go  godepfile  LICENSE  ninja  PATENTS  README.md  update.sh  vars.sh
XXXXX:~/dart-sdk$ /home/YYYYY/dart-sdk/sdk/buildtools/gn
Cannot find /home/YYYYY/dart-sdk/sdk/buildtools/linux-x64/gn
Did you run update.sh?
XXXXX:~/dart-sdk$ /home/YYYYY/dart-sdk/sdk/buildtools/update.sh
Unknown machine architecture.
```

**Comment by zanderso** [comment]
`gn` is built and vended by the provider of our buildtools, and they do not provide native arm64 binaries. I am going to close this as 'not planned' but 'infeasible' would be a better label if we had it in the tracker.

**Comment by sjindel-google** [comment]
So just to be clear, it's impossible to build the SDK natively on ARM64?

**Comment by zanderso** [comment]
Building natively on ARM64 is not possible.

Those instructions probably do need updating, but they are about cross-building, not about building natively on ARM.

**Comment by lmcdougald** [comment]
Worth noting the documentation update didn't happen / isn't quite complete.

I'm not confident enough to write something technically accurate + accessible but the following line threw me off:

"If you are building natively on the device you will be running on, you can skip this step."
