### ISSUE TITLE
Exception while using a AlwaysSpecifyTypes to visit a SimpleFormalParameterImpl in FormalParameterListImpl in GenericFunctionTypeImpl..

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33731]
I can't repro this in a small sample so I've attached the file in a state that repros it for me

[test_driver.dart.txt](https://github.com/dart-lang/sdk/files/2155557/test_driver.dart.txt)

Specifically I had written `Function(void)` here (I always get confused trying to args that are functions in Dart; they're much different (less-natural IMO) to TypeScript!):

```dart
Future<void> run({
    bool withDebugger = false,
    Function(void) // I think this caused the crash
  }) async {
```

### Versions

- Flutter SDK 0.5.6-pre.131
- Visual Studio Code 1.24.1
- Dart Code 2.15.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
M:\Coding\Applications\Google\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.15.0
--preview-dart-2
```

### Exception

Exception while using a AlwaysSpecifyTypes to visit a SimpleFormalParameterImpl in FormalParameterListImpl in GenericFunctionTypeImpl in SimpleFormalParameterImpl in DefaultFormalParameterImpl in FormalParameterListImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl

```text
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _Visitor.visitSimpleFormalParameter (package:linter/src/rules/always_specify_types.dart:145)
#2      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9515)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:659)
#4      LinterVisitor.visitSimpleFormalParameter (package:analyzer/src/lint/linter_visitor.dart:510)
#5      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9515)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#7      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4933)
#8      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:845)
#9      LinterVisitor.visitFormalParameterList (package:analyzer/src/lint/linter_visitor.dart:258)
#10     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4929)
#11     GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5854)
#12     RecursiveAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:893)
#13     LinterVisitor.visitGenericFunctionType (package:analyzer/src/lint/linter_visitor.dart:306)
#14     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5847)
#15     SimpleFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9520)
#16     RecursiveAstVisitor.visitSimpleFormalParameter (package:analyzer/dart/ast/visitor.dart:1116)
#17     LinterVisitor.visitSimpleFormalParameter (package:analyzer/src/lint/linter_visitor.dart:511)
#18     SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9515)
#19     DefaultFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3512)
#20     RecursiveAstVisitor.visitDefaultFormalParameter (package:analyzer/dart/ast/visitor.dart:755)
#21     LinterVisitor.visitDefaultFormalParameter (package:analyzer/src/lint/linter_visitor.dart:168)
#22     DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3508)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#24     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4933)
#25     RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:845)
#26     LinterVisitor.visitFormalParameterList (package:analyzer/src/lint/linter_visitor.dart:258)
#27     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4929)
#28     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7758)
#29     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1007)
#30     LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:420)
#31     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7750)
#32     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#33     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1982)
#34     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:683)
#35     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:96)
#36     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1914)
#37     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#38     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2511)
#39     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#40     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:120)
#41     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2504)
#42     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:386)
#43     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:169)
#44     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#45     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:168)
#46     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#47     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:167)
#48     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:107)
<asynchronous suspension>
#49     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222)
<asynchronous suspension>
#50     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#51     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1283)
<asynchronous suspension>
#52     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#53     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1240)
<asynchronous suspension>
#54     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1043)
<asynchronous suspension>
#55     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005)
<asynchronous suspension>
#56     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946)
#57     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397)
#58     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#59     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#60     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:441)
#61     _rootRun (dart:async/zone.dart:1126)
#62     _CustomZone.run (dart:async/zone.dart:1023)
#63     _runZoned (dart:async/zone.dart:1518)
#64     runZoned (dart:async/zone.dart:1465)
#65     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:483)
#66     Driver.start (package:analysis_server/src/server/driver.dart:440)
#67     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#68     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\syntax_error",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_path",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_test\\test\\test_config\\project_root",
        "explicitFileCount": 1,
        "implicitFileCount": 94,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\asset_test\\main",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\asset_test\\font",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\changed_sdk_location",
        "explicitFileCount": 1,
        "implicitFileCount": 93,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\good",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_package",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_test",
        "explicitFileCount": 32,
        "implicitFileCount": 840,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\asci_casing",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_import",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools",
        "explicitFileCount": 214,
        "implicitFileCount": 1309,
        "workItemQueueLength": 215,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
I suspect the issue is the `Function(void)` in
```
Future<void> run({
    bool withDebugger = false,
    Function(void)
  }) async {
```
The parser is probably getting confused by the absence of an identifier and not recovering well.

**Comment by DanTup** [comment]
I trigged this again with this (there's a bad `>` in there):

```
Future<T> _timeoutWithMessages<T>(Function(Future><T>) action, {Duration timeout, String message}) {
}
```

### Versions

- Flutter SDK 0.5.7-pre.98
- Visual Studio Code 1.25.0
- Dart Code 2.16.0-beta.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.16.0-beta.1
```

### Exception

Exception while using a AlwaysSpecifyTypes to visit a SimpleFormalParameterImpl in FormalParameterListImpl in GenericFunctionTypeImpl in SimpleFormalParameterImpl in FormalParameterListImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl

```text
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _Visitor.visitSimpleFormalParameter (package:linter/src/rules/always_specify_types.dart:145)
#2      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9515)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:659)
#4      LinterVisitor.visitSimpleFormalParameter (package:analyzer/src/lint/linter_visitor.dart:510)
#5      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9515)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#7      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4933)
#8      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:845)
#9      LinterVisitor.visitFormalParameterList (package:analyzer/src/lint/linter_visitor.dart:258)
#10     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4929)
#11     GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5854)
#12     RecursiveAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:893)
#13     LinterVisitor.visitGenericFunctionType (package:analyzer/src/lint/linter_visitor.dart:306)
#14     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5847)
#15     SimpleFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9520)
#16     RecursiveAstVisitor.visitSimpleFormalParameter (package:analyzer/dart/ast/visitor.dart:1116)
#17     LinterVisitor.visitSimpleFormalParameter (package:analyzer/src/lint/linter_visitor.dart:511)
#18     SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9515)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#20     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4933)
#21     RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:845)
#22     LinterVisitor.visitFormalParameterList (package:analyzer/src/lint/linter_visitor.dart:258)
#23     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4929)
#24     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5439)
#25     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:869)
#26     LinterVisitor.visitFunctionExpression (package:analyzer/src/lint/linter_visitor.dart:282)
#27     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5434)
#28     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5284)
#29     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:857)
#30     LinterVisitor.visitFunctionDeclaration (package:analyzer/src/lint/linter_visitor.dart:270)
#31     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5277)
#32     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#33     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2511)
#34     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#35     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:120)
#36     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2504)
#37     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:386)
#38     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:169)
#39     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#40     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:168)
#41     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#42     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:167)
#43     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:107)
<asynchronous suspension>
#44     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222)
<asynchronous suspension>
#45     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101)
<asynchronous suspension>
#46     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1283)
<asynchronous suspension>
#47     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#48     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1240)
<asynchronous suspension>
#49     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:926)
<asynchronous suspension>
#50     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005)
<asynchronous suspension>
#51     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946)
#52     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397)
#53     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#54     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#55     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:441)
#56     _rootRun (dart:async/zone.dart:1126)
#57     _CustomZone.run (dart:async/zone.dart:1023)
#58     _runZoned (dart:async/zone.dart:1518)
#59     runZoned (dart:async/zone.dart:1465)
#60     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:483)
#61     Driver.start (package:analysis_server/src/server/driver.dart:440)
#62     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#63     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#64     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter",
        "explicitFileCount": 857,
        "implicitFileCount": 498,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_path",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/dev/benchmarks/complex_layout",
        "explicitFileCount": 5,
        "implicitFileCount": 951,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools",
        "explicitFileCount": 214,
        "implicitFileCount": 1309,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/dev/benchmarks",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_import",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/asset_test/main",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_test/test/test_config/project_root",
        "explicitFileCount": 1,
        "implicitFileCount": 94,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/good",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/asci_casing",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/dev/devicelab",
        "explicitFileCount": 95,
        "implicitFileCount": 795,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_test",
        "explicitFileCount": 32,
        "implicitFileCount": 841,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/asset_test/font",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/changed_sdk_location",
        "explicitFileCount": 1,
        "implicitFileCount": 93,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_package",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/dev/benchmarks/microbenchmarks",
        "explicitFileCount": 6,
        "implicitFileCount": 862,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/data/dart_dependencies_test/syntax_error",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
https://github.com/dart-lang/linter/pull/1072
