### ISSUE TITLE
Analyzer Feedback from IntelliJ: NoSuchMethodError: The getter 'length' was called on null.

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#33740]
Analyzer Feedback from IntelliJ

/cc @bwilkerson 

# Version information

- `IDEA IC-181.4203.550`
- `2.0.0-dev.66.0`
- `IC-181.4203.550, JRE 1.8.0_152-release-1136-b20x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.5 unknown, screens 1440x900  Retina`

# Exception

```
Dart analysis server, SDK version 2.0.0-dev.66.0, server version 1.20.3, error: Analysis failed: /Users/vegorov/src/mtg_collection/bin/collection-server.dart
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      InterfaceTypeImpl.superclass (package:analyzer/src/dart/element/type.dart:1384:23)
#2      InterfaceTypeImpl.lookUpMethodInSuperclass (package:analyzer/src/dart/element/type.dart:1806:31)
#3      InterfaceTypeImpl.lookUpMethod (package:analyzer/src/dart/element/type.dart:1793:12)
#4      InterfaceTypeImpl.lookUpInheritedMethod (package:analyzer/src/dart/element/type.dart:1760:16)
#5      ElementResolver._lookUpMethod (package:analyzer/src/generated/element_resolver.dart:1813:19)
#6      ElementResolver._resolveInvokedElementWithTarget (package:analyzer/src/generated/element_resolver.dart:2294:25)
#7      ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:677:25)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7872:49)
#9      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6348:10)
#10     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7872:49)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8264:20)
#12     CascadeExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1544:22)
#13     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6363:10)
#14     UnifyingAstVisitor.visitCascadeExpression (package:analyzer/dart/ast/visitor.dart:2931:55)
#15     ResolverVisitor.visitCascadeExpression (package:analyzer/src/generated/resolver.dart:5651:18)
#16     CascadeExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1539:49)
#17     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11347:19)
#18     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6363:10)
#19     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3224:59)
#20     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:7963:11)
#21     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:6507:11)
#22     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11341:49)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8264:20)
#24     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11443:16)
#25     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6363:10)
#26     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228:7)
#27     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:6531:11)
#28     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11437:15)
#29     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11498:20)
#30     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6363:10)
#31     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:3232:7)
#32     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11494:15)
#33     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8264:20)
#34     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1353:17)
#35     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6363:10)
#36     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919:31)
#37     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7398:13)
#38     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1349:49)
#39     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1298:13)
#40     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6363:10)
#41     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922:55)
#42     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7410:13)
#43     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5629:13)
#44     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1294:49)
#45     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5442:12)
#46     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6363:10)
#47     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033:57)
#48     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7713:13)
#49     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:6130:15)
#50     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5436:49)
#51     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5286:26)
#52     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6363:10)
#53     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026:59)
#54     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:7706:11)
#55     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:6106:11)
#56     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7698:7)
#57     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:6096:13)
#58     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5279:49)
#59     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5734:25)
#60     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2506:49)
#61     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:712:10)
#62     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:130:9)
#63     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
#64     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:129:13)
#65     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:104:16)
<asynchronous suspension>
#66     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#67     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:98:43)
<asynchronous suspension>
#68     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1283:71)
<asynchronous suspension>
#69     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#70     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1240:20)
<asynchronous suspension>
#71     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1043:23)
<asynchronous suspension>
#72     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005:24)
<asynchronous suspension>
#73     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946:5)
#74     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#75     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#76     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#77     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:441:19)
#78     _rootRun (dart:async/zone.dart:1126:13)
#79     _CustomZone.run (dart:async/zone.dart:1023:19)
#80     _runZoned (dart:async/zone.dart:1518:10)
#81     runZoned (dart:async/zone.dart:1465:12)
#82     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:483:12)
#83     Driver.start (package:analysis_server/src/server/driver.dart:440:5)
#84     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12:11)
#85     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#86     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

```

```
1530606011326 <= {"id":"1717","result":{"files":[],"targets":[],"regions":[]}}
1530606011327 => {"id":"1718","method":"analysis.getNavigation","params":{"file":"/Users/vegorov/src/mtg_collection/bin/collection-server.dart","offset":328,"length":45},"clientRequestTime":1530606011
1530606011336 <= {"id":"1718","result":{"files":[],"targets":[],"regions":[]}}
1530606011337 => {"id":"1719","method":"analysis.getNavigation","params":{"file":"/Users/vegorov/src/mtg_collection/bin/collection-server.dart","offset":328,"length":45},"clientRequestTime":1530606011
1530606011345 <= {"id":"1719","result":{"files":[],"targets":[],"regions":[]}}
1530606011347 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1530606011406 => {"id":"1720","method":"analysis.getNavigation","params":{"file":"/Users/vegorov/src/mtg_collection/bin/collection-server.dart","offset":328,"length":45},"clientRequestTime":1530606011
1530606011407 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1530606011415 <= {"id":"1720","result":{"files":[],"targets":[],"regions":[]}}
1530606011416 => {"id":"1721","method":"analysis.getNavigation","params":{"file":"/Users/vegorov/src/mtg_collection/bin/collection-server.dart","offset":328,"length":45},"clientRequestTime":1530606011
1530606011425 <= {"id":"1721","result":{"files":[],"targets":[],"regions":[]}}
1530606011426 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1530606011454 => {"id":"1722","method":"analysis.getNavigation","params":{"file":"/Users/vegorov/src/mtg_collection/bin/collection-server.dart","offset":328,"length":45},"clientRequestTime":1530606011
1530606011455 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1530606011463 <= {"id":"1722","result":{"files":[],"targets":[],"regions":[]}}
1530606011465 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1530606011488 => {"id":"1723","method":"analysis.getNavigation","params":{"file":"/Users/vegorov/src/mtg_collection/bin/collection-server.dart","offset":328,"length":45},"clientRequestTime":1530606011
1530606011488 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1530606011496 <= {"id":"1723","result":{"files":[],"targets":[],"regions":[]}}
1530606011498 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1530606012538 => {"id":"1724","method":"analysis.getNavigation","params":{"file":"/Users/vegorov/src/mtg_collection/bin/collection-server.dart","offset":328,"length":45},"clientRequestTime":1530606012
1530606012582 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1530606012600 <= {"id":"1724","result":{"files":[],"targets":[],"regions":[]}}
1530606012600 => {"id":"1725","method":"analysis.getNavigation","params":{"file":"/Users/vegorov/src/mtg_collection/bin/collection-server.dart","offset":328,"length":45},"clientRequestTime":1530606012
1530606012609 <= {"id":"1725","result":{"files":[],"targets":[],"regions":[]}}
1530606012610 => {"id":"1726","method":"analysis.getNavigation","params":{"file":"/Users/vegorov/src/mtg_collection/bin/collection-server.dart","offset":328,"length":45},"clientRequestTime":1530606012
1530606012619 <= {"id":"1726","result":{"files":[],"targets":[],"regions":[]}}
1530606012621 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1530606012942 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1530606012970 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/vegorov/src/mtg_collection/bin/collection-server.dart","stackTrace":"NoSuchMethodError: The getter
```

**Comment by devoncarew** [comment]
We've received two reports of this one; /cc @scheglov

**Comment by scheglov** [comment]
Seems rare, don't see it internally.
Possibly related to https://github.com/dart-lang/sdk/issues/33477

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/75403
