### ISSUE TITLE
Dart Analyzer Error Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by wublack** [dart-lang/sdk#33759]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4720617`
- `2.0.0-edge.4c9689c1d2da97d0aa25cf16cc90c2e463ad157f`
- `AI-173.4720617, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\admin\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.4c9689c1d2da97d0aa25cf16cc90c2e463ad157f, server version 1.20.3, FATAL error: Failed to handle request: {id: 8, method: edit.getFixes, params: {file: D:\workspace\Flutter-UI-Kit\test\widget_test.dart, offset: 0}, clientRequestTime: 1530669682767}
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      new FixProcessor (package:analysis_server/src/services/correction/fix_internal.dart:242)
#2      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:87)
<asynchronous suspension>
#3      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:562)
<asynchronous suspension>
#4      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:239)
<asynchronous suspension>
#5      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:347)
#6      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:746)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities

**Comment by scheglov** [comment]
I suspect that this is duplicate for https://github.com/dart-lang/sdk/issues/34298, there is no unit in `AnalysisResult`.
