### ISSUE TITLE
CFE needs to recover when the class hierarchy is invalid.

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#33756]
The front end throws an exception if the class hierarchy is not valid. It needs to recover. For the specific case given below (a class that implements `I<int>` and `I<String>`), I would suggest either picking one of the two conflicting types or treating the class as if it did not implement either one.

Reproduce by running:
```
dart --enable-asserts sdk/pkg/analyzer_cli/bin/analyzer.dart --use-cfe sdk/tests/language_2/conflicting_generic_interfaces_simple_test.dart
```
Stack trace:
```
Analyzing sdk/tests/language_2/conflicting_generic_interfaces_simple_test.dart...
Unhandled exception:
#lib1::C can't implement both #lib1::I<dart.core::int> and #lib1::I<dart.core::String>
#0      new ClassHierarchy.<anonymous closure> (package:kernel/class_hierarchy.dart:28:9)
#1      ClosedWorldClassHierarchy.onAmbiguousSupertypes=.<anonymous closure> (package:kernel/class_hierarchy.dart:422:28)
#2      _ClassInfo.recordGenericSuperType (package:kernel/class_hierarchy.dart:1399:28)
#3      ClosedWorldClassHierarchy._recordSuperTypes.<anonymous closure> (package:kernel/class_hierarchy.dart:1143:19)
#4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
#5      ClosedWorldClassHierarchy._recordSuperTypes (package:kernel/class_hierarchy.dart:1141:36)
#6      ClosedWorldClassHierarchy._initializeTopologicallySortedClasses (package:kernel/class_hierarchy.dart:884:9)
#7      ClosedWorldClassHierarchy._initialize (package:kernel/class_hierarchy.dart:850:5)
#8      new ClassHierarchy (package:kernel/class_hierarchy.dart:33:9)
#9      FrontEndCompiler.compile.<anonymous closure> (package:analyzer/src/dart/analysis/frontend_resolution.dart:238:44)
<asynchronous suspension>
#10     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#11     FrontEndCompiler._runWithFrontEndContext.<anonymous closure> (package:analyzer/src/dart/analysis/frontend_resolution.dart:337:22)
#12     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#13     new Future.sync (dart:async/future.dart:222:31)
#14     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _runZoned (dart:async/zone.dart:1518:10)
#18     runZoned (dart:async/zone.dart:1465:12)
#19     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#20     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:128:41)
#21     FrontEndCompiler._runWithFrontEndContext (package:analyzer/src/dart/analysis/frontend_resolution.dart:335:34)
<asynchronous suspension>
#22     FrontEndCompiler.compile (package:analyzer/src/dart/analysis/frontend_resolution.dart:203:12)
#23     KernelContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/kernel_context.dart:88:26)
<asynchronous suspension>
#24     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#25     KernelContext.forSingleLibrary (package:analyzer/src/dart/analysis/kernel_context.dart:83:19)
<asynchronous suspension>
#26     AnalysisDriver._createKernelContext (package:analyzer/src/dart/analysis/driver.dart:1412:32)
<asynchronous suspension>
#27     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1353:33)
<asynchronous suspension>
#28     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:985:40)
<asynchronous suspension>
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005:24)
<asynchronous suspension>
#30     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946:5)
#31     Driver._createContextAndAnalyze (package:analyzer_cli/src/driver.dart:648:15)
#32     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:310:9)
<asynchronous suspension>
#33     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:241:20)
<asynchronous suspension>
#34     Driver.start (package:analyzer_cli/src/driver.dart:208:38)
<asynchronous suspension>
#35     main (file:///Users/brianwilkerson/src/dart/sdk/sdk/pkg/analyzer_cli/bin/analyzer.dart:13:17)
<asynchronous suspension>
#36     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#37     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by bwilkerson** [comment]
Even though the CFE integration work is suspended, it would be better if the CFE didn't throw an exception. Hence I'm moving this to a front_end issue.
