### ISSUE TITLE
I get a piece of binary data, can't utf8.decode to string

### ISSUE THREAD

**Issue by 6643** [dart-lang/sdk#33775]
```
import 'dart:convert';

main(List<String> args) {
  var bytes = [120, 128, 129];

  print(new String.fromCharCodes(bytes));
  print(utf8.decode(bytes));
}
```

```
x
Unhandled exception:
FormatException: Bad UTF-8 encoding 0x80 (at offset 1)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:574:13)
#1      Utf8Decoder.convert (dart:convert/utf.dart:350:13)
#2      Utf8Codec.decode (dart:convert/utf.dart:72:60)
#3      main (file:///home/if/Documents/project/zhubao/bin/utf8.dart:7:14)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)


```

**Comment by sureshg** [comment]
This is expected because the byte array is not UTF-8 encoded. 
```
1111000
10000000
10000001
```
Try `utf8.decode(bytes,allowMalformed: false)` to avoid the malformed code points.

**Comment by matanlurey** [comment]
Thanks @sureshg! Yes, @6643 - your code is not valid UTF-8.
