### ISSUE TITLE
No Idea what this is about, just got web storm and configured the SDK there

### ISSUE THREAD

**Issue by Sammyalhashe** [dart-lang/sdk#33779]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-181.5281.31`
- `2.0.0-dev.67.0`
- `WS-181.5281.31, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.5 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/s4/8xg0tgf92dq8vtnzb8c11h6r0000gn/T/report2.txt

```
Dart analysis server, SDK version 2.0.0-dev.67.0, server version 1.20.3, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [/Users/sammyalhashemi/Desktop/DartgularTest], excluded: [/Users/sammyalhashemi/Desktop/DartgularTest/.idea, /Users/sammyalhashemi/Desktop/DartgularTest/.dart_tool, /Users/sammyalhashemi/Desktop/DartgularTest/.pub, /Users/sammyalhashemi/Desktop/DartgularTest/.tmp, /Users/sammyalhashemi/Desktop/DartgularTest/build, /Users/sammyalhashemi/Desktop/DartgularTest/temp, /Users/sammyalhashemi/Desktop/DartgularTest/tmp]}, clientRequestTime: 1531022399675}
type 'List<dynamic>' is not a subtype of type 'List<String>' of 'errorPair'
#0      ServerIsolateChannel.listen.<anonymous closure> (package:analyzer_plugin/src/channel/isolate_channel.dart:241:16)
#1      _rootRunUnary (dart:async/zone.dart:1138:13)
#2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#6      _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#7      _StreamController._add (dart:async/stream_controller.dart:639:7)
#8      _StreamController.add (dart:async/stream_controller.dart:585:5)

**Comment by bwilkerson** [comment]
I assume that this is stale. If you're still seeing a problem, please let me know.
