### ISSUE TITLE
Data Analyzer error

### ISSUE THREAD

**Issue by drkhannah** [dart-lang/sdk#33790]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5281.24`
- `1.24.3`
- `IU-181.5281.24, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.5 unknown, screens 1920x1080, 1680x1050`

# Exception

Please append the contents of:
file:///private/var/folders/6x/_w944gxn13lgvkvkg99m1pn00000gn/T/report.txt

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Analysis failed: /Users/derek/Toybox/opensource/flutter/flutter/examples/stocks/test/locale_test.dart context: exception_20180709_114251_450
NoSuchMethodError: Class 'GenericTypeAliasElementForLink' has no instance getter 'returnType'.
Receiver: Instance of 'GenericTypeAliasElementForLink'
Tried calling: returnType
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      GenericTypeAliasElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3318)
#3      FunctionTypeImpl.baseReturnType (package:analyzer/src/dart/element/type.dart:435)
#4      FunctionTypeImpl.returnType (package:analyzer/src/dart/element/type.dart:626)
#5      FunctionTypeImpl.== (package:analyzer/src/dart/element/type.dart:729)
#6      TypeImpl.equalArrays (package:analyzer/src/dart/element/type.dart:2631)
#7      FunctionTypeImpl.== (package:analyzer/src/dart/element/type.dart:730)
#8      InheritanceManager._unionInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:893)
#9      InheritanceManager._computeInterfaceLookupMap (package:analyzer/src/dart/resolver/inheritance_manager.dart:455)
#10     InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:496)

**Comment by matanlurey** [comment]
This is a version of the analyzer from over a year ago. All effort is only being put into the 2.0.0-dev SDK, which will become the new stable branch soon. Please feel free to open a new ticket if problems persist.
