### ISSUE TITLE
analysis server crash -dev.68 - in `analyzer_plugin` - type 'List<dynamic>' is not a subtype of type 'List<String>' 

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33808]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5281.24`
- `2.0.0-dev.68.0`
- `IU-181.5281.24, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.5 unknown, screens 3840x2160`

# Exception

```
Dart analysis server, SDK version 2.0.0-dev.68.0, server version 1.20.3, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [/Users/kevmoo/source/github/repo_manager], excluded: [/Users/kevmoo/source/github/repo_manager/.idea, /Users/kevmoo/source/github/repo_manager/.dart_tool, /Users/kevmoo/source/github/repo_manager/.pub, /Users/kevmoo/source/github/repo_manager/build, /Users/kevmoo/source/github/repo_manager/funky]}, clientRequestTime: 1531242624270}
type 'List<dynamic>' is not a subtype of type 'List<String>' of 'errorPair'
#0      ServerIsolateChannel.listen.<anonymous closure> (package:analyzer_plugin/src/channel/isolate_channel.dart:241:16)
#1      _rootRunUnary (dart:async/zone.dart:1138:13)
#2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#6      _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#7      _StreamController._add (dart:async/stream_controller.dart:639:7)
#8      _StreamController.add (dart:async/stream_controller.dart:585:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

```
1531243385909 <= {"id":"502","result":{}}
1531243385911 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1531243385982 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","errors":[{"severity":"ERROR","type":"HINT","location":{"file"
1531243385986 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"t
1531243385991 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset
1531243385992 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","labels":[]}}
1531243385995 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UN
1531243385995 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","overrides":[{"offset":3008,"length":8,"interfaceMembers":[
1531243385998 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1531243386000 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","classes":[],"members":[]}}
1531243793074 => {"id":"503","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","offset":5254,"length":0},"clientRequestTime":1531
1531243793076 <= {"id":"503","result":{"assists":[]}}
1531243845067 => {"id":"504","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","offset":5254,"length":0},"clientRequestTime":1531
1531243845068 <= {"id":"504","result":{"assists":[]}}
1531243865482 => {"id":"505","method":"edit.getFixes","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","offset":8623},"clientRequestTime":1531243865482}
1531243865485 <= {"id":"505","result":{"fixes":[]}}
1531243865489 => {"id":"506","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","offset":8623,"length":0},"clientRequestTime":1531
1531243865498 <= {"id":"506","result":{"assists":[{"message":"Convert to async function body","edits":[{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.dart","fileStamp":
1531243870266 => {"id":"507","method":"analysis.setPriorityFiles","params":{"files":["/Users/kevmoo/source/github/repo_manager/lib/components/app_component.html"]},"clientRequestTime":1531243870266}
1531243870266 => {"id":"508","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/Users/kevmoo/source/github/repo_manager/lib/components/app_component.html"],"CLOSING_LABELS"
1531243870270 <= {"id":"507"}
1531243870274 <= {"id":"508"}
1531243885249 => {"id":"509","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.html":{"type":"add","content":"<div class=\"sta
1531243885249 => {"id":"510","method":"completion.getSuggestions","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.html","offset":1375},"clientRequestTime":15312
1531243885252 <= {"id":"509","result":{}}
1531243885252 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1531243885253 <= {"id":"510","result":{"id":"67"}}
1531243885254 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1531243885400 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/repo_manager/lib/components/app_component.html","errors":[]}}
1531243885419 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [/Users/kevmoo/source/github/repo_m
```

**Comment by kevmoo** [comment]
@MichaelRFairhurst – need to update plugin logic somewhere? This in w/ an angular project w/ the angular plugin enabled

**Comment by devoncarew** [comment]
Note, that this only happens when the analysis server plugin throws an uncaught exception to the isolate it's running in.

**Comment by kevmoo** [comment]
Cool. It'd be good to get that error all the way through, right?

**Comment by devoncarew** [comment]
Yup; this is fixed in head now.

**Comment by kevmoo** [comment]
HEAD for analysis_server of pkg:analyzer_plugin?

**Comment by devoncarew** [comment]
Head for the sdk repo.

**Comment by devoncarew** [comment]
The fix was in //pkg/analysis_server/ and //pkg/analyzer_plugin/.

**Comment by kevmoo** [comment]
Does analyzer_plugin need to be published to get the fix?

**Comment by devoncarew** [comment]
I don't believe so - I believe the next dev sdk will contain the fix.

But related, looking at https://pub.dartlang.org/packages/analyzer_plugin, I see that Mike doesn't have rights to publish. @bwilkerson, can you add @MichaelRFairhurst to the list of publishers for that plugin?

**Comment by bwilkerson** [comment]
Done
