### ISSUE TITLE
front_end/test/fasta/bootstrap_test has issues when switching the front end to run in Dart2 pipeline

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#33811]
bootstrap_test uses the --no-preview-dart-2 option and passes a 'dill' file as input. the VM does not support this combination anymore and reports this as an error.
--no-preview-dart-2 implies the Dart 1 pipeline and it cannot run '.dill' files.

If I modify the test to remove the --no_preview_dart_2 option in the method runCompiler, the test fails in the bootstrap step with the following runtime type error

```
unittest-suite-wait-for-done
Unhandled exception:
type '(TargetFlags) => dynamic' is not a subtype of type '(TargetFlags) => Target'
#0      new Map._fromLiteral (dart:core/runtime/libmap_patch.dart:18:38)
#1      targets (package:kernel/target/targets.dart:34:69)
#2      targets (package:kernel/target/targets.dart:34:35)
#3      installAdditionalTargets (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/pkg/front_end/tool/_fasta/additional_targets.dart:18:3)
#4      compileEntryPoint (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/pkg/front_end/tool/_fasta/entry_points.dart:65:3)
<asynchronous suspension>
#5      main (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

Unhandled exception:
Compilation failed.
#0      runCompiler (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/pkg/front_end/test/fasta/bootstrap_test.dart:63:5)
<asynchronous suspension>
#1      main (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/pkg/front_end/test/fasta/bootstrap_test.dart:30:11)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by peter-ahe-google** [comment]
I'm working on fixing it in this CL: https://dart-review.googlesource.com/c/sdk/+/65084
