### ISSUE TITLE
Support arbitrary type argument count in functions in dart2js

### ISSUE THREAD

**Issue by nickclmb** [dart-lang/sdk#33819]
Hi all,

Dart2js crashes with error because of this TODO:
https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/ssa/builder_kernel.dart#L4387

Seems critical can you please check
```
The compiler crashed: Internal Error: Generic function instantiation not implemented for 8 type arguments
#0      CompilerDiagnosticReporter.internalError (file:///tmp/tmpAi0tzS/dart-2.0.0-dev.67.0/dart/pkg/compiler/lib/src/compiler.dart:868:5)
#1      KernelSsaGraphBuilder.visitInstantiation (file:///tmp/tmpAi0tzS/dart-2.0.0-dev.67.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:4375:16)
#2      Instantiation.accept (package:kernel/ast.dart:2959:36)
```

**Comment by nickclmb** [comment]
Same here:
https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/js_backend/constant_emitter.dart#L341

**Comment by nickclmb** [comment]
@kevmoo @johnniwinther

**Comment by sigmundch** [comment]
Because the full solution will take us longer to implement, we are landing first a change to raise the limit manually. We should be able to support up to 20 type arguments after the change lands. Our hope is that this will unblock you until we have the full solution ready.

CL from @johnniwinther is here https://dart-review.googlesource.com/c/sdk/+/65541

**Comment by nickclmb** [comment]
Thanks for update and your work. 20 should be enough, so far we have 9 generics max. Looking forward for hotfix. Thanks in advance
