### ISSUE TITLE
2-dev.68 dartanalyzer exception: NoSuchMethodError: The getter 'ordinal' was called on null

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#33821]
## Environment

Dart VM version: 2.0.0-dev.68.0 (Tue Jul 10 14:47:26 2018 +0200) on "macos_x64"

## Steps to reproduce

```console
> pub global activate stagehand
> pub global run stagehand console-full
> pub upgrade
> dartanalyzer --no-hints --fatal-warnings . analysis_options.yaml 
Analyzing xxx7, analysis_options.yaml...
Unhandled exception:
NoSuchMethodError: The getter 'ordinal' was called on null.
Receiver: null
Tried calling: ordinal
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      ErrorSeverity.max (package:front_end/src/base/errors.dart:136:32)
#2      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:350:35)
<asynchronous suspension>
#3      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:241:20)
<asynchronous suspension>
#4      Driver.start (package:analyzer_cli/src/driver.dart:208:38)
<asynchronous suspension>
#5      main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:13:17)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

cc @kwalrath @kevmoo

**Comment by chalin** [comment]
I forgot to mention, the problem goes away if you omit the `analysis_options.yaml` argument. This exception is new to 2-dev.68 AFAICT.

**Comment by devoncarew** [comment]
> the problem goes away if you omit the analysis_options.yaml argument

Given that, I don't think this is a dart2 blocker. I'll investigate and triage in any case. @chalin, thanks for the report!

**Comment by devoncarew** [comment]
This requires both `--no-hints`, and a warning in an analysis options file.

**Comment by devoncarew** [comment]
fixed in https://dart.googlesource.com/sdk/+/96b840dcd2a6cb47bdfd05c854db56180abebc3c
