### ISSUE TITLE
Both Dart and analyzer don't reject attempts to use class type as a Callable function when call method is not defined.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33831]
Dart SDK Version: 2.0.0-dev.68.0
OS: Windows 10

The following code sample demonstrates the problem:
``` dart
class A {}
main() {
  A();
}
```
It tries to call `A` class as `Callable` function or, from another point of view, call a default `A` constructor without the `new` clause.
It passes without any errors and warnings both with analyzer and dart with the recent developer 2.0 version.
It seems like it should fail like in does with dart 1.24.
Dart 1.24 sample output is:
```
Unhandled exception:
NoSuchMethodError: Attempted to use type 'A' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the A constructor and forget the 'new' operator?
Receiver: Type: class 'A'
Tried calling: A()
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      main (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Instantiate-to-bound/function/test.dart:3:4)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
Dartanalyzer 1.24 sample output is  (please note that it's not a strong mode here!):
```
Analyzing test.dart...
  warning - The function 'A' isn't defined at test.dart:3:3 - undefined_function
1 warning found.

```

**Comment by iarkh** [comment]
Thank you for the clarification!

If so - is there any changes for the Callable functions? What is the common rule if I have both constructor and call method for the given class?

**Comment by lrhn** [comment]
A callable object is an object with an instance method named `call`.
There is no conflict between that and constructors since `Type` objects do not have any instance methods named `call`. A static method named `call` has no effect wrt. being callable.

```dart
class A {
  int call() => 42;
}
p(o) { print(o.runtimeType); }
main() {
  p(A);  // Type
  p(A()); // A
  p(A()()); // int
}
```
