### ISSUE TITLE
analysis_sever crash - -dev.68 - type 'ImportDirectiveImpl' is not a subtype of type 'CompilationUnitMember' in type cast

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33856]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5540.7`
- `2.0.0-dev.68.0`
- `IU-181.5540.7, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.5 unknown, screens 3840x2160`

# Exception

```
Dart analysis server, SDK version 2.0.0-dev.68.0, server version 1.20.3, FATAL error: Failed to handle request: {id: 271, method: edit.getFixes, params: {file: /Users/kevmoo/source/github/intl/test/utc_timezone_test.dart, offset: 525}, clientRequestTime: 1531524936056}
type 'ImportDirectiveImpl' is not a subtype of type 'CompilationUnitMember' in type cast
#0      Object._as (dart:core/runtime/libobject_patch.dart:67:25)
#1      AstNodeImpl.getAncestor (package:analyzer/src/dart/ast/ast.dart:981:17)
#2      FixProcessor._addFix_createClass (package:analysis_server/src/services/correction/fix_internal.dart:1210:16)
<asynchronous suspension>
#3      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:320:19)
<asynchronous suspension>
#4      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:88:41)
<asynchronous suspension>
#5      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:562:49)
<asynchronous suspension>
#6      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:239:32)
<asynchronous suspension>
#7      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:347:9)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:751:45)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:747:50)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1502:12)
#15     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:746:5)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#18     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#20     _rootRunUnary (dart:async/zone.dart:1134:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#27     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#28     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#29     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#30     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#31     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#32     _rootRunUnary (dart:async/zone.dart:1134:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#40     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#41     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#42     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#43     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#45     _rootRunUnary (dart:async/zone.dart:1134:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#50     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#51     _StreamController._add (dart:async/stream_controller.dart:639:7)
#52     _StreamController.add (dart:async/stream_controller.dart:585:5)
#53     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#54     _rootRunUnary (dart:async/zone.dart:1138:13)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#59     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#60     _StreamController._add (dart:async/stream_controller.dart:639:7)
#61     _StreamController.add (dart:async/stream_controller.dart:585:5)
#62     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#63     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#64     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#65     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#66     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#67     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

```
1531524932663 <= {"id":"266","result":{"assists":[]}}
1531524933432 => {"id":"267","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart":{"type":"add","content":"// Copyright (c) 2017, the Dar
1531524933433 <= {"id":"267","result":{}}
1531524933434 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1531524933439 => {"id":"268","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","offset":217,"length":0},"clientRequestTime":1531524933439}
1531524933452 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","errors":[]}}
1531524933453 <= {"id":"268","result":{"assists":[]}}
1531524933454 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","regions":[{"type":"DIRECTIVE","offset":218,"length":116},{"type":"BUILT
1531524933454 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","regions":[{"offset":308,"length":25,"targets":[0]},{"offset":336,"lengt
1531524933454 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","labels":[]}}
1531524933455 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<u
1531524933455 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","overrides":[]}}
1531524933458 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1531524933458 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","classes":[],"members":[]}}
1531524933757 => {"id":"269","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart":{"type":"add","content":"// Copyright (c) 2017, the Dar
1531524933760 <= {"id":"269","result":{}}
1531524933760 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1531524933761 => {"id":"270","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","offset":556,"length":0},"clientRequestTime":1531524933761}
1531524933785 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file"
1531524933788 <= {"id":"270","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","fileStamp":0,"edits":[{"o
1531524933789 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","regions":[{"type":"DIRECTIVE","offset":525,"length":148},{"type":"BUILT
1531524933789 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","regions":[{"offset":647,"length":25,"targets":[0]},{"offset":675,"lengt
1531524933789 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","labels":[]}}
1531524933790 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<u
1531524933790 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","overrides":[]}}
1531524933794 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/intl/test/timezone_test_core.dart","errors":[]}}
1531524933795 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1531524933795 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","classes":[],"members":[]}}
1531524936056 => {"id":"271","method":"edit.getFixes","params":{"file":"/Users/kevmoo/source/github/intl/test/utc_timezone_test.dart","offset":525},"clientRequestTime":1531524936056}
1531524936216 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 271, method: edit.getFixes, params: {file: /Users/kevmoo/source/github/intl/test/utc_timezon
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/65023
