### ISSUE TITLE
Dart Analyzer throws an error

### ISSUE THREAD

**Issue by the-dagger** [dart-lang/sdk#33862]
Analyzer Feedback from IntelliJ

Even though there are no issues in the dart file, I get an error warning on all my dart files and the project fails to run.

On running the project from command line, it works just fine.

# Version information

- `IDEA IC-181.5540.7`
- `1.24.3`
- `IC-181.5540.7, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.5 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      Visitor.checkIdentifier (package:linter/src/rules/non_constant_identifier_names.dart:50)
#3      Visitor.visitFormalParameterList.<anonymous closure> (package:linter/src/rules/non_constant_identifier_names.dart:63)
#4      Object&ListMixin.forEach (dart:collection/list.dart:63)
#5      Visitor.visitFormalParameterList (package:linter/src/rules/non_constant_identifier_names.dart:61)
#6      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4849)
#7      ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2757)
#8      List.forEach (dart:core-patch/growable_array.dart:256)
#9      ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2755)
#10     UnifyingAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:3020)
#11     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4849)
#12     GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5781)
#13     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#14     UnifyingAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:3047)
#15     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5774)
#16     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7540)
#17     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#18     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3106)
#19     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7535)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#21     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#22     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#23     UnifyingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:2937)
#24     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#26     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#27     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2762)
#28     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#29     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#30     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:237)
#31     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120)
#32     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#33     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:119)
#34     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:999)
#35     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#36     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#37     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:743)
<asynchronous suspension>
#38     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#39     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#40     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#41     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#42     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#43     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#44     _rootRun (dart:async/zone.dart:1120)
#45     _CustomZone.run (dart:async/zone.dart:1001)
#46     runZoned (dart:async/zone.dart:1467)
#47     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#48     Driver.start (package:analysis_server/src/server/driver.dart:473)
#49     main (file:///Users/whesse/dart/sdk/pkg/analysis_server/bin/server.dart:12)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


1531587662254 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1531587662424 => {"id":"18","method":"edit.getAssists","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/main.dart","offset":113,"length":0},"clientRequestTime":1531587662424}
1531587662848 <= {"event":"analysis.errors","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/main.dart","errors":[{"severity":"WARNING","type":"STATIC_TYPE_WARNING","location":{"
1531587662849 <= {"id":"18","result":{"assists":[]}}
1531587662851 <= {"event":"analysis.highlights","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":39},{"type":"BUILT_
1531587662852 <= {"event":"analysis.navigation","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/main.dart","regions":[{"offset":7,"length":31,"targets":[0]},{"offset":47,"length
1531587662855 <= {"event":"analysis.outline","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"
1531587662855 <= {"event":"analysis.overrides","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/main.dart","overrides":[]}}
1531587662859 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1531587668772 => {"id":"19","method":"edit.getAssists","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/main.dart","offset":1,"length":0},"clientRequestTime":1531587668771}
1531587668778 <= {"id":"19","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/main.dart","fileStamp":0,"edits":[{"
1531587669084 => {"id":"20","method":"analysis.setPriorityFiles","params":{"files":["/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/src/blocs/provider.dart"]},"clientRequestTime":1531587669084}
1531587669084 => {"id":"21","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/src/blocs/provider.dart"],"OVERRIDES":["
1531587669087 <= {"id":"20"}
1531587669090 <= {"id":"21"}
1531587669107 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1531587669239 <= {"event":"analysis.errors","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/src/blocs/provider.dart","errors":[{"severity":"WARNING","type":"STATIC_TYPE_WARNING"
1531587669244 <= {"event":"analysis.highlights","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/src/blocs/provider.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":39},{
1531587669255 <= {"event":"analysis.navigation","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/src/blocs/provider.dart","regions":[{"offset":7,"length":31,"targets":[0]},{"offs
1531587669257 <= {"event":"analysis.outline","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/src/blocs/provider.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_
1531587669275 <= {"event":"analysis.overrides","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/src/blocs/provider.dart","overrides":[{"offset":244,"length":18,"superclassMember"
1531587669277 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1531587669607 => {"id":"22","method":"edit.getAssists","params":{"file":"/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/src/blocs/provider.dart","offset":439,"length":0},"clientRequestTime":1531
1531587669611 <= {"id":"22","result":{"assists":[]}}
1531587670982 => {"id":"23","method":"analysis.setPriorityFiles","params":{"files":["/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/src/blocs/bloc.dart"]},"clientRequestTime":1531587670982}
1531587670985 => {"id":"24","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["/Users/harshitdwivedi/Desktop/Flutter/login_bloc/lib/src/blocs/bloc.dart"],"OVERRIDES":["/Use
1531587670986 <= {"id":"23"}
1531587670988 <= {"id":"24"}
1531587670992 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1531587671138 <= {"event":"server.error","params":{"isFatal":false,"message":"Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in MethodDeclarationImpl in 
```

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      Visitor.checkIdentifier (package:linter/src/rules/non_constant_identifier_names.dart:50)
#3      Visitor.visitFormalParameterList.<anonymous closure> (package:linter/src/rules/non_constant_identifier_names.dart:63)
#4      Object
```

**Comment by bwilkerson** [comment]
https://github.com/dart-lang/linter/pull/1078
