### ISSUE TITLE
Crash when switching channel from dev to beta

### ISSUE THREAD

**Issue by aaronfg** [dart-lang/sdk#33875]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4819257`
- `2.0.0-edge.4c9689c1d2da97d0aa25cf16cc90c2e463ad157f`
- `AI-173.4819257, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1280x800, 3360x1050`

# Exception

Please append the contents of:
file:///private/var/folders/4m/ckx5fvpx5176ds3gkcjy7mz40000gn/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.4c9689c1d2da97d0aa25cf16cc90c2e463ad157f, server version 1.20.3, FATAL error: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FolderBasedDartSdk.getSdkProperty (package:analyzer/src/dart/sdk/sdk.dart:690)
#2      FolderBasedDartSdk.defaultSdkDirectory (package:analyzer/src/dart/sdk/sdk.dart:677)
#3      Driver.start (package:analysis_server/src/server/driver.dart:386)
#4      main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)


---

report.txt:

```
Dart analysis server, SDK version 2.0.0-edge.4c9689c1d2da97d0aa25cf16cc90c2e463ad157f, server version 1.20.3, FATAL error: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FolderBasedDartSdk.getSdkProperty (package:analyzer/src/dart/sdk/sdk.dart:690)
#2      FolderBasedDartSdk.defaultSdkDirectory (package:analyzer/src/dart/sdk/sdk.dart:677)
#3      Driver.start (package:analysis_server/src/server/driver.dart:386)
#4      main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)```

```
1531774923222 <= {"event":"analysis.flushResults","params":{"files":["/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/ios/Flutter/flutter_assets/AssetManifest.json"]}}
1531774923222 <= {"event":"analysis.flushResults","params":{"files":["/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/ios/Flutter/flutter_assets/FontManifest.json"]}}
1531774923223 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1531774923223 <= {"event":"analysis.flushResults","params":{"files":["/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/ios/Flutter/flutter_assets/fonts/MaterialIcons-Regular.ttf"]
1531774923250 <= {"event":"analysis.flushResults","params":{"files":["/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/ios/Flutter/flutter_assets/isolate_snapshot_data"]}}
1531774923250 <= {"event":"analysis.flushResults","params":{"files":["/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/ios/Flutter/flutter_assets/kernel_blob.bin"]}}
1531774923253 <= {"event":"analysis.flushResults","params":{"files":["/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/ios/Flutter/flutter_assets/LICENSE"]}}
1531774923341 <= {"event":"analysis.flushResults","params":{"files":["/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/ios/Flutter/flutter_assets/packages/cupertino_icons/assets/C
1531774923341 <= {"event":"analysis.flushResults","params":{"files":["/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/ios/Flutter/flutter_assets/platform.dill"]}}
1531774923341 <= {"event":"analysis.flushResults","params":{"files":["/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/ios/Flutter/flutter_assets/vm_snapshot_data"]}}
1531774923442 <= {"event":"analysis.errors","params":{"file":"/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/lib/main.dart","errors":[]}}
1531774923446 <= {"event":"analysis.highlights","params":{"file":"/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/lib/main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length
1531774923447 <= {"event":"analysis.navigation","params":{"file":"/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/lib/main.dart","regions":[{"offset":7,"length":31,"targets":[0]}
1531774923448 <= {"event":"analysis.closingLabels","params":{"file":"/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/lib/main.dart","labels":[{"offset":289,"length":710,"label":"
1531774923455 <= {"event":"analysis.outline","params":{"file":"/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/lib/main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPI
1531774923455 <= {"event":"analysis.overrides","params":{"file":"/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/lib/main.dart","overrides":[{"offset":248,"length":5,"superclassM
1531774923485 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1531774923485 <= {"event":"analysis.implemented","params":{"file":"/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/lib/main.dart","classes":[],"members":[]}}
1531774965165 => {"id":"824","method":"execution.deleteContext","params":{"id":"5"},"clientRequestTime":1531774965165}
1531774965170 <= {"id":"824"}
1531775154409 => {"id":"825","method":"execution.createContext","params":{"contextRoot":"/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/lib/main.dart"},"clientRequestTime":15317
1531775154410 <= {"id":"825","result":{"id":"6"}}
1531775159911 => {"id":"826","method":"execution.deleteContext","params":{"id":"6"},"clientRequestTime":1531775159911}
1531775159912 <= {"id":"826"}
1531775165188 => {"id":"827","method":"edit.getAssists","params":{"file":"/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/lib/main.dart","offset":1738,"length":0},"clientRequestT
1531775165191 <= {"id":"827","result":{"assists":[{"message":"Convert to async function body","edits":[{"file":"/Users/aaronfg/crap/flutter/platformchanneltest/platform_channel_test/lib/main.dart","fi
1531775368197 => {"id":"828","method":"server.shutdown","clientRequestTime":1531775368197}
1531775368204 <= {"id":"828"}
1531775368292 started analysis server:
  /Users/aaronfg/crap/flutter/flutter/bin/cache/dart-sdk/bin/dart /Users/aaronfg/crap/flutter/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=Android-Studio --client
```

**Comment by scheglov** [comment]
@bwilkerson This is another situation when Analysis Server breaks when SDK becomes unavailable.

Maybe we should read all we need from SDK or environment on Analysis Server start, and keep it all in memory. If this fails - the server goes down. If it is successful, we always use it, and never have to check for special cases like `dart:core` does not exist, or `Uri.base` now suddenly throws an exception, etc. Complete isolation modulo analysis root.
