### ISSUE TITLE
FATAL error: Failed to handle request

### ISSUE THREAD

**Issue by parasthekoder** [dart-lang/sdk#33908]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4819257`
- `2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822`
- `AI-173.4819257, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900`

# Exception

```
Dart analysis server, SDK version 2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822, server version 1.20.3, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\Paras\AndroidStudioProjects\svn\hms, C:\Users\Paras\AndroidStudioProjects\svn\hms\android], excluded: [C:\Users\Paras\AndroidStudioProjects\svn\hms\.idea, C:\Users\Paras\AndroidStudioProjects\svn\hms\.dart_tool, C:\Users\Paras\AndroidStudioProjects\svn\hms\.idea, C:\Users\Paras\AndroidStudioProjects\svn\hms\.pub, C:\Users\Paras\AndroidStudioProjects\svn\hms\build]}, clientRequestTime: 1531996152533}
FileSystemException: Exists failed, path = 'C:\Users\Paras\AndroidStudioProjects\svn\hms\build\app\generated\source\r\debug\com\google\android\gms\ads_identifier' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#4      _WindowsDirectoryWatcher._onBatch (package:watcher/src/directory_watcher/windows.dart:163)
#5      _WindowsDirectoryWatcher._onEvent.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:157)
#6      _rootRun (dart:async/zone.dart:1122)
#7      _CustomZone.run (dart:async/zone.dart:1023)
#8      _CustomZone.runGuarded (dart:async/zone.dart:925)
#9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#13     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#14     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#15     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

```
1531996316391 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\panels\\admissions_panel.dart","errors":[{"severity":"INFO","type":"HINT","locatio
1531996316423 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\panels\\messages_panel.dart","errors":[]}}
1531996316438 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\panels\\opds_panel.dart","errors":[]}}
1531996316532 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\panels\\profile_panel.dart","errors":[]}}
1531996316548 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\panels\\support_panel.dart","errors":[]}}
1531996316641 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\panels\\timeline_panel.dart","errors":[]}}
1531996316735 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\SideBar.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C:\\U
1531996316751 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\templates\\bill_tile.dart","errors":[]}}
1531996316798 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\templates\\expanded_tile.dart","errors":[]}}
1531996316891 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\templates\\image_tile.dart","errors":[]}}
1531996316891 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\templates\\model\\card.dart","errors":[]}}
1531996316907 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\templates\\model\\expanded_card.dart","errors":[]}}
1531996316907 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\templates\\model\\image_card.dart","errors":[]}}
1531996316923 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\templates\\model\\normal_card.dart","errors":[]}}
1531996317001 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\templates\\normal_tile.dart","errors":[{"severity":"INFO","type":"HINT","location"
1531996317032 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\templates\\simple_tile.dart","errors":[]}}
1531996317032 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\values\\colors.dart","errors":[]}}
1531996317048 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\values\\dimens.dart","errors":[]}}
1531996317063 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\values\\style.dart","errors":[]}}
1531996317079 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\views\\admission_details.dart","errors":[]}}
1531996317110 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\views\\bill_details.dart","errors":[]}}
1531996317220 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\views\\media_explorer.dart","errors":[]}}
1531996317235 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\views\\opd_details.dart","errors":[]}}
1531996317298 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\views\\photo_viewer.dart","errors":[]}}
1531996317329 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\lib\\web_view.dart","errors":[]}}
1531996319564 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Paras\\AndroidStudioProjects\\svn\\hms\\test\\widget_test.dart","errors":[]}}
1531996319564 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1531996333334 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1531996333553 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1531996394465 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\\Users\\Paras\\AndroidStudioPro
```

```
Dart analysis server, SDK version 2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822, server version 1.20.3, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\Paras\AndroidStudioProjects\svn\hms, C:\Users\Paras\AndroidStudioProjects\svn\hms\android], excluded: [C:\Users\Paras\AndroidStudioProjects\svn\hms\.idea, C:\Users\Paras\AndroidStudioProjects\svn\hms\.dart_tool, C:\Users\Paras\AndroidStudioProjects\svn\hms\.idea, C:\Users\Paras\AndroidStudioProjects\svn\hms\.pub, C:\Users\Paras\AndroidStudioProjects\svn\hms\build]}, clientRequestTime: 1531996152533}
FileSystemException: Exists failed, path = 'C:\Users\Paras\AndroidStudioProjects\svn\hms\build\app\generated\source\r\debug\com\google\android\gms\ads_identifier' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166)
#3      _HashVMBase

**Comment by devoncarew** [comment]
closing as a dup of https://github.com/dart-lang/sdk/issues/34108
