### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [dart-lang/sdk#33929]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5281.24`
- `2.0.0-edge.4c9689c1d2da97d0aa25cf16cc90c2e463ad157f`
- `IU-181.5281.24, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1440x900  Retina`

# Exception

[report.txt](https://github.com/dart-lang/sdk/files/2214514/report.txt)

```
Dart analysis server, SDK version 2.0.0-edge.4c9689c1d2da97d0aa25cf16cc90c2e463ad157f, server version 1.20.3, error: Failed to send analysis.implemented notification.
NoSuchMethodError: The getter 'uriStr' was called on null.
Receiver: null
Tried calling: uriStr
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      Search.subtypes (package:analyzer/src/dart/analysis/search.dart:392)
<asynchronous suspension>
#2      SearchEngineImpl.membersOfSubtypes.addMembers (package:analysis_server/src/services/search/search_engine_internal.dart:40)
<asynchronous suspension>
#3      SearchEngineImpl.membersOfSubtypes (package:analysis_server/src/services/search/search_engine_internal.dart:51)
<asynchronous suspension>
#4      ImplementedComputer.compute (package:analysis_server/src/domains/analysis/implemented_dart.dart:34)
<asynchronous suspension>
#5      scheduleImplementedNotification (package:analysis_server/src/operation/operation_analysis.dart:36)
<asynchronous suspension>
#6      AnalysisServer._scheduleAnalysisImplementedNotification (package:analysis_server/src/analysis_server.dart:1150)
<asynchronous suspension>
#7      AnalysisServer.sendStatusNotificationNew (package:analysis_server/src/analysis_server.dart:884)
#8      _rootRunUnary (dart:async/zone.dart:1134)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)

**Comment by scheglov** [comment]
I suspect this has been fixed, but I will look again.
