### ISSUE TITLE
NoSuchMethodError from  PostfixCompletionProcessor._findOuterExpression

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33974]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-181.5540.7`
- `2.0.0-edge.2fed345d6a6eda30fd4b20a92ab5851f537531e1`
- `IC-181.5540.7, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/00/0w978000h01000cxqpysvccm003j4x/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.2fed345d6a6eda30fd4b20a92ab5851f537531e1, server version 1.20.3, FATAL error: Failed to handle request: {id: 72, method: edit.isPostfixCompletionApplicable, params: {file: /Users/devoncarew/projects/workspace/sdk/pkg/analysis_server/lib/src/server/driver.dart, offset: 15947, key: .return}, clientRequestTime: 1532526350057}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase&Object&ListMixin.firstWhere (dart:collection/list.dart:142:15)
#3      PostfixCompletionProcessor._findOuterExpression (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:564:28)
#4      PostfixCompletionProcessor.findObjectExpression (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:482:7)
#5      DartPostfixCompletion.isObjectContext (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:221:22)
#6      PostfixCompletionProcessor.isApplicable (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:513:23)
<asynchronous suspension>
#7      EditDomainHandler.isPostfixCompletionApplicable (package:analysis_server/src/edit/edit_domain.dart:441:33)
<asynchronous suspension>
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:364:9)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:751:45)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:747:50)
```

**Comment by devoncarew** [comment]
dup of https://github.com/dart-lang/sdk/issues/34114
