### ISSUE TITLE
Analyzer Error Windows

### ISSUE THREAD

**Issue by littlemarc2011** [dart-lang/sdk#34009]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.3684.101`
- `1.24.3`
- `IU-182.3684.101, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1920x1080, 1600x900`

# Exception

Please append the contents of:
file://C:\Users\marc\AppData\Local\Temp\report2.txt

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Analysis failed: C:\Users\marc\IdeaProjects\hairsaloon\test\widget_test.dart
Invalid argument(s): Cannot serialize an instance of GenericFunctionTypeImpl
#0      AbstractConstExprSerializer.serializeTypeName (package:analyzer/src/summary/summarize_const_expr.dart:211)
#1      AbstractConstExprSerializer._serializeListLiteral (package:analyzer/src/summary/summarize_const_expr.dart:550)
#2      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:356)
#3      AbstractConstExprSerializer.serialize (package:analyzer/src/summary/summarize_const_expr.dart:139)
#4      _SummarizeAstVisitor.serializeConstExpr (package:analyzer/src/summary/summarize_ast.dart:557)
#5      _SummarizeAstVisitor.serializeFunctionBody (package:analyzer/src/summary/summarize_ast.dart:755)
#6      _SummarizeAstVisitor.serializeInitializerFunction (package:analyzer/src/summary/summarize_ast.dart:828)
#7      _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:1029)
#8      _SummarizeAstVisitor.visitFieldDeclaration (package:analyzer/src/summary/summarize_ast.dart:1210)
#9      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399)
#10     _SummarizeAstVisitor.serializeClass (package:analyzer/src
```

**Comment by littlemarc2011** [comment]
Here is a screenshot of the error that it seems to come from:
![error](https://user-images.githubusercontent.com/13179783/43349329-96c7ec9c-91c4-11e8-85ee-0f195cc6c1f3.png)

**Comment by devoncarew** [comment]
Thanks for the report! Closing due to an older (`SDK version 1.24.3`) sdk version.
