### ISSUE TITLE
Compiler bug with invalid library root when using build_runner

### ISSUE THREAD

**Issue by renggli** [dart-lang/sdk#34023]
Dart VM version: 2.0.0-dev.69.4 (Fri Jul 27 11:42:55 2018 +0200) on "macos_x64"

```
[INFO] Generating build script completed, took 503ms
[INFO] Reading cached asset graph completed, took 461ms
[INFO] Checking for updates since last build completed, took 636ms
[INFO] Running build completed, took 384ms
[INFO] Caching finalized dependency graph completed, took 178ms
[SEVERE] build_web_compilers|ddc on test/smalltalk_test.module (cached):
Error compiling dartdevc module:petitparser|test/smalltalk_test.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=/usr/local/lib/dart --dart-sdk-summary=/usr/local/lib/dart/lib/_internal/ddc_sdk.sum --modules=amd -o test/smalltalk_test.ddc.js --module-root=. --library-root=/test --summary-extension=linked.sum --no-summarize --options=packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s packages/petitparser/src/core/actions/action.linked.sum -s packages/petitparser/src/core/characters/any_of.linked.sum -s packages/petitparser/petitparser.linked.sum -s example/smalltalk/src/grammar.linked.sum -s example/smalltalk/smalltalk.linked.sum -s packages/collection/src/utils.linked.sum -s packages/collection/src/algorithms.linked.sum -s packages/collection/src/canonicalized_map.linked.sum -s packages/collection/src/comparators.linked.sum -s packages/collection/src/iterable_zip.linked.sum -s packages/collection/src/priority_queue.linked.sum -s packages/collection/collection.linked.sum -s packages/async/async.linked.sum -s packages/path/path.linked.sum -s packages/pub_semver/pub_semver.linked.sum -s packages/charcode/ascii.linked.sum -s packages/charcode/html_entity.linked.sum -s packages/charcode/charcode.linked.sum -s packages/source_span/source_span.linked.sum -s packages/string_scanner/string_scanner.linked.sum -s packages/typed_data/typed_buffers.linked.sum -s packages/typed_data/typed_data.linked.sum -s packages/http_parser/http_parser.linked.sum -s packages/http/src/base_client.linked.sum -s packages/http/http.linked.sum -s packages/package_config/src/util.linked.sum -s packages/package_config/packages_file.linked.sum -s packages/package_resolver/package_resolver.linked.sum -s packages/source_maps/src/source_map_span.linked.sum -s packages/source_maps/builder.linked.sum -s packages/source_maps/printer.linked.sum -s packages/source_maps/refactor.linked.sum -s packages/source_maps/source_maps.linked.sum -s packages/stack_trace/stack_trace.linked.sum -s packages/source_map_stack_trace/source_map_stack_trace.linked.sum -s packages/boolean_selector/boolean_selector.linked.sum -s packages/test/src/backend/closed_exception.linked.sum -s packages/matcher/src/core_matchers.linked.sum -s packages/matcher/matcher.linked.sum -s packages/stream_channel/stream_channel.linked.sum -s packages/pool/pool.linked.sum -s packages/meta/meta.linked.sum -s packages/term_glyph/term_glyph.linked.sum -s packages/test/test.linked.sum --url-mapping=file:///test/smalltalk_test.dart,test/smalltalk_test.dart file:///test/smalltalk_test.dart
    dart --version: 2.0.0-dev.69.4 (Fri Jul 27 11:42:55 2018 +0200) on "macos_x64"

Invalid library root. /test/ does not contain /example/smalltalk/src/grammar.dart
#0      jsLibraryName (package:dev_compiler/src/analyzer/code_generator.dart:6384:5)
#1      CodeGenerator.emitLibraryName.<anonymous closure> (package:dev_compiler/src/analyzer/code_generator.dart:6151:34)
#2      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
#3      CodeGenerator.emitLibraryName (package:dev_compiler/src/analyzer/code_generator.dart:6150:18)
#4      CodeGenerator._emitTopLevelNameNoInterop (package:dev_compiler/src/analyzer/code_generator.dart:3345:9)
#5      CodeGenerator._emitType (package:dev_compiler/src/analyzer/code_generator.dart:3329:12)
#6      CodeGenerator._emitConstructorAccess (package:dev_compiler/src/analyzer/code_generator.dart:3255:44)
#7      CodeGenerator._emitConstructorName (package:dev_compiler/src/analyzer/code_generator.dart:4304:27)
#8      CodeGenerator._emitInstanceCreationExpression.emitNew (package:dev_compiler/src/analyzer/code_generator.dart:4360:18)
#9      CodeGenerator._emitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4367:51)
#10     CodeGenerator.visitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4507:12)
#11     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6579:15)
#12     CodeGenerator._visitExpression (package:dev_compiler/src/analyzer/code_generator.dart:5803:18)
#13     CodeGenerator._visitInitializer (package:dev_compiler/src/analyzer/code_generator.dart:4272:11)
#14     CodeGenerator._emitLazyFields (package:dev_compiler/src/analyzer/code_generator.dart:4287:15)
#15     CodeGenerator._emitTopLevelFields (package:dev_compiler/src/analyzer/code_generator.dart:4235:21)
#16     CodeGenerator.visitCompilationUnit (package:dev_compiler/src/analyzer/code_generator.dart:672:9)
#17     List.forEach (dart:core/runtime/libarray.dart:79:8)
#18     CodeGenerator._emitModule (package:dev_compiler/src/analyzer/code_generator.dart:418:22)
#19     CodeGenerator.compile (package:dev_compiler/src/analyzer/code_generator.dart:269:20)
#20     ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:201:26)
#21     _compile (package:dev_compiler/src/analyzer/command.dart:185:25)
#22     compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#23     _CompilerWorker.performRequest (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#24     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#30     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#31     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#32     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Similar errors repeat with other library roots. I suspect the problem is because some of the examples in `example/` are tested from `test/`? Possibly related to https://github.com/dart-lang/sdk/issues/34022, even if the error is very different?

Steps to reproduce:

```
git clone git@github.com:petitparser/dart-petitparser.git
cd dart-petitparser/
git checkout 06e13aef
pub upgrade
pub run build_runner test
```

**Comment by vsmenon** [comment]
@jakemac53 @natebosch 

I think we assume that `test` can import from `lib`, but not `example`, right?

**Comment by jakemac53** [comment]
Yes, we do not support importing across top level directories with relative imports. Each top level directory is served at the root of the server, and thus you can't access other top level directories because that would require reaching outside the server root.

**Comment by natebosch** [comment]
@jakemac53 - can we do a better job at identifying and messaging this scenario?

**Comment by renggli** [comment]
If I can't refer to an example by relative path, how can I import the examples into my unit tests?

**Comment by jakemac53** [comment]
> If I can't refer to an example using a relative path, how can I import the examples into my unit tests?

One option is to make the `example` directory actually a package in itself - with a pubspec.yaml and a `lib` directory.

Then, you can add a `dev_dependency` on it using the path dependency type:

```yaml
dev_dependencies:
  my_example:
    path: my_example
```

Then, in your tests you can import the files under `lib` from that package using a package: import.

You could also consider adding tests of the examples in a `example/test` directory within that package.

**Comment by renggli** [comment]
Thank you Jacob, that solved my problem. Should I close the issue, or do you want to investigate further on the error reporting?

**Comment by jakemac53** [comment]
Closing this issue in favor of https://github.com/dart-lang/build/issues/1697
