### ISSUE TITLE
crash when running dartanalyzer --use-cfe

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34038]
When running the command-line analyzer in --use-cfe mode, and analyzing pkg/kernel, I see the following exception:

> ./xcodebuild/ReleaseX64/dart-sdk/bin/dart pkg/analyzer_cli/bin/analyzer.dart --use-cfe pkg/kernel/

```
Analyzing pkg/kernel...
Unhandled exception:
RangeError (index): Invalid value: Not in range 0..8, inclusive: 9
#0      List._setIndexed (dart:core/runtime/libarray.dart:16:64)
#1      List.[]= (dart:core/runtime/libarray.dart:13:5)
#2      LibraryElementImpl.imports (package:analyzer/src/dart/element/element.dart:6666:20)
#3      LibraryElementImpl.importedLibraries (package:analyzer/src/dart/element/element.dart:6634:35)
#4      AnalyzerImpl.addLibrarySources (package:analyzer_cli/src/analyzer_impl.dart:88:42)
#5      AnalyzerImpl.addLibrarySources (package:analyzer_cli/src/analyzer_impl.dart:89:7)
#6      AnalyzerImpl.prepareSources (package:analyzer_cli/src/analyzer_impl.dart:143:5)
#7      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:169:5)
<asynchronous suspension>
#8      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:106:18)
<asynchronous suspension>
#9      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:754:21)
#10     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:388:40)
<asynchronous suspension>
#11     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:239:20)
<asynchronous suspension>
#12     Driver.start (package:analyzer_cli/src/driver.dart:206:38)
<asynchronous suspension>
#13     main (file:///Users/devoncarew/projects/workspace/sdk/pkg/analyzer_cli/bin/analyzer.dart:13:17)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by devoncarew** [comment]
This will be important to fix for further dogfooding.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/67682

**Comment by devoncarew** [comment]
Thanks!
