### ISSUE TITLE
front_end/tool/perf_test fails when the analyzer is switched to --use-fasta-parser

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34039]
./tools/test.py -m release -c none -r vm --checked --no-preview-dart-2 -t 120 --use-sdk --builder-tag pkg_tests_no_preview_dart_2 pkg/front_end/tool/perf_test

```
exit code:
255

stdout:
input size: 2027991 chars
load:                 65806 us, 65 ms, 32.45 ns/char
scan:                 121091 us, 121 ms, 59.71 ns/char
== iteration 0
scan:                 52205 us, 52 ms, 25.74 ns/char
total:                53032 us, 53 ms, 26.15 ns/char
== iteration 1
scan:                 54688 us, 54 ms, 26.97 ns/char
total:                55184 us, 55 ms, 27.21 ns/char
== iteration 2
scan:                 48025 us, 48 ms, 23.68 ns/char
total:                48523 us, 48 ms, 23.93 ns/char
== iteration 3
scan:                 43893 us, 43 ms, 21.64 ns/char
total:                44395 us, 44 ms, 21.89 ns/char
== iteration 4
scan:                 43423 us, 43 ms, 21.41 ns/char
total:                43883 us, 43 ms, 21.64 ns/char
== iteration 5
scan:                 43552 us, 43 ms, 21.48 ns/char
total:                44076 us, 44 ms, 21.73 ns/char
== iteration 6
scan:                 42644 us, 42 ms, 21.03 ns/char
total:                43069 us, 43 ms, 21.24 ns/char
== iteration 7
scan:                 43837 us, 43 ms, 21.62 ns/char
total:                44056 us, 44 ms, 21.72 ns/char
== iteration 8
scan:                 40140 us, 40 ms, 19.79 ns/char
total:                40386 us, 40 ms, 19.91 ns/char
== iteration 9
scan:                 40050 us, 40 ms, 19.75 ns/char
total:                40280 us, 40 ms, 19.86 ns/char
input size: 2027991 chars
load:                 23989 us, 23 ms, 11.83 ns/char
scan:                 46146 us, 46 ms, 22.75 ns/char
== iteration 0

stderr:
Unhandled exception:
type 'SimpleToken' is not a subtype of type 'BeginToken' of 'start'
#0      new ComplexTypeParamOrArgInfo (package:front_end/src/fasta/parser/type_info_impl.dart:554:23)
#1      computeTypeParamOrArg (package:front_end/src/fasta/parser/type_info.dart:285:18)
#2      computeType (package:front_end/src/fasta/parser/type_info.dart:192:7)
#3      Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:2663:25)
#4      Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:2576:15)
#5      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1688:13)
#6      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1648:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:545:14)
#8      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:482:14)
#9      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:328:15)
#10     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:132:32)
#11     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:127:12)
#12     parseFull (file:///Users/devoncarew/projects/workspace/sdk/pkg/front_end/tool/perf.dart:188:21)
#13     parseFiles (file:///Users/devoncarew/projects/workspace/sdk/pkg/front_end/tool/perf.dart:176:5)
#14     main.<anonymous closure> (file:///Users/devoncarew/projects/workspace/sdk/pkg/front_end/tool/perf.dart:57:26)
<asynchronous suspension>
#15     main (file:///Users/devoncarew/projects/workspace/sdk/pkg/front_end/tool/perf.dart:76:18)
<asynchronous suspension>
#16     main (file:///Users/devoncarew/projects/workspace/sdk/pkg/front_end/tool/perf_test.dart:15:11)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by devoncarew** [comment]
/cc @danrubel 

This reproduces on the bots consistently - I can't yet get it to repro locally.

**Comment by devoncarew** [comment]
To repro:

- patch in https://dart-review.googlesource.com/c/sdk/+/67090
- create hello.dart at the repo root
- `./xcodebuild/ReleaseX64/dart-sdk/bin/dart pkg/front_end/tool/perf.dart parse hello.dart`

hello.dart:

```
main() {
  print("Hello, World");
}
```

**Comment by danrubel** [comment]
Fixed as of https://dart-review.googlesource.com/c/sdk/+/70400
