### ISSUE TITLE
Bad state: Unable to convert (MissingExplicitTypeArguments) when running dartanalyzer --use-cfe on pkg/front_end

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34042]
To repro:

./xcodebuild/ReleaseX64/dart-sdk/bin/dart pkg/analyzer_cli/bin/analyzer.dart --use-cfe pkg/front_end/

```
Analyzing pkg/front_end...
Unhandled exception:
Bad state: Unable to convert (MissingExplicitTypeArguments, null, @1158, No type arguments provided, 2 possible.)
#0      FastaErrorReporter.reportCompilationMessage (package:analyzer/src/fasta/error_converter.dart:683:7)
#1      LibraryAnalyzer._analyze2.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:224:28)
#2      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
#3      LibraryAnalyzer._analyze2.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:212:17)
#4      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#5      LibraryAnalyzer._analyze2.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:211:17)
<asynchronous suspension>
#6      PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#7      LibraryAnalyzer._analyze2 (package:analyzer/src/dart/analysis/library_analyzer.dart:185:26)
<asynchronous suspension>
#8      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:22)
<asynchronous suspension>
#9      _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#10     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:98:43)
<asynchronous suspension>
#11     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1283:71)
<asynchronous suspension>
#12     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#13     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1240:20)
<asynchronous suspension>
#14     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:652:43)
<asynchronous suspension>
#15     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:130:58)
<asynchronous suspension>
#16     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:170:11)
<asynchronous suspension>
#17     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:106:18)
<asynchronous suspension>
#18     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:754:21)
#19     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:388:40)
<asynchronous suspension>
#20     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:239:20)
<asynchronous suspension>
#21     Driver.start (package:analyzer_cli/src/driver.dart:206:38)
<asynchronous suspension>
#22     main (file:///Users/devoncarew/projects/workspace/sdk/pkg/analyzer_cli/bin/analyzer.dart:13:17)
<asynchronous suspension>
#23     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1323:9)
<asynchronous suspension>
#1      PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1240:20)
<asynchronous suspension>
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:652:43)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:130:58)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:170:11)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:106:18)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:754:21)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:388:40)
<asynchronous suspension>
#9      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:239:20)
<asynchronous suspension>
#10     Driver.start (package:analyzer_cli/src/driver.dart:206:38)
<asynchronous suspension>
#11     main (file:///Users/devoncarew/projects/workspace/sdk/pkg/analyzer_cli/bin/analyzer.dart:13:17)
<asynchronous suspension>
#12     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by devoncarew** [comment]
@scheglov, can you take a look at this?

**Comment by scheglov** [comment]
`pkg/front_end` can be analyzed now.

**Comment by devoncarew** [comment]
Thanks!
