### ISSUE TITLE
two DDC test failures related to moving the analyzer to --use-fasta-parser

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34041]
```
tests/corelib_2/corelib_2.status
  format_exception_test: RuntimeError
tests/language_2/language_2_dartdevc.status
  super_conditional_operator_test/01: Crash
```

**Comment by devoncarew** [comment]
Related to https://dart-review.googlesource.com/c/sdk/+/67090/4.

**Comment by bwilkerson** [comment]
@danrubel

**Comment by devoncarew** [comment]
And, cc'ing @vsmenon as well (note, the above CL has not yet landed).

**Comment by vsmenon** [comment]
Here's a link to the log:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8939457313331647536/+/steps/ddc_tests/0/stdout

The first appears to be an issue with new lines.

The second is crashing in the analyzer:

```
AnalysisException: Cannot compute SOURCE_KIND for /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_tests/language_2/super_conditional_operator_test_01.dart
Caused by Unexpected exception while performing ParseDartTask for source /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_tests/language_2/super_conditional_operator_test_01.dart
#0      AnalysisTask._safelyPerform (package:analyzer/src/task/api/model.dart:335:7)
#1      AnalysisTask.perform (package:analyzer/src/task/api/model.dart:222:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:285:10)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110:22)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:717:14)
#5      AnalysisContextImpl.computeKindOf (package:analyzer/src/context/context.dart:675:14)
#6      ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:162:19)
```

**Comment by natebosch** [comment]
Analyzer isn't moving in this direction anymore, and DDC is moving to CFE. We haven't deleted the old code path yet but this particular issue isn't something we need to have solved before we do.
