### ISSUE TITLE
--pause-isolates-on-exit sometimes fails to pause

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#34056]
Reproduced on Linux VM with 2.0.0-dev.69.5.  Seems distinct from #31747 as it doesn't seem to matter how we are exiting, but rather some combination of how much work is being done beforehand.  This bug currently keeps the coverage package from working on dart-services, because it relies on this flag working.

Reproduction:
```
~/dart/clean
$ dart --version
Dart VM version: 2.0.0-dev.69.5 (Tue Jul 31 15:05:14 2018 +0200) on "linux_x64"
~/dart/clean
$
~/dart/clean
$ git clone git@github.com:dart-lang/dart-services.git
Cloning into 'dart-services'...
remote: Counting objects: 4098, done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 4098 (delta 88), reused 117 (delta 62), pack-reused 3935
Receiving objects: 100% (4098/4098), 960.92 KiB | 3.87 MiB/s, done.
Resolving deltas: 100% (2766/2766), done.
~/dart/clean
$ cd dart-services
~/dart/clean/dart-services
$ pub get
Resolving dependencies... (6.6s)
Overriding the upper bound Dart SDK constraint to <=2.0.0-dev.69.5 for the following packages:
 
uuid
 
To disable this you can set the PUB_ALLOW_PRERELEASE_SDK system environment variable to `false`, or you can silence this message by setting it to `quiet`.
+ _discoveryapis_commons 0.1.6+1
+ analysis_server_lib 0.1.4+2
+ analyzer 0.32.4
+ appengine 0.4.4+2
+ archive 2.0.0
+ args 1.4.4
+ async 2.0.8
+ boolean_selector 1.0.4
+ charcode 1.1.2
+ cli_util 0.1.3+2
+ codemirror 0.4.3+5.13.4
+ collection 1.14.11
+ convert 2.0.2
+ crypto 2.0.6
+ csslib 0.14.4+1
+ dart2_constant 1.0.1+dart2
+ dart_style 1.1.3
+ discoveryapis_generator 0.9.8
+ fixnum 0.10.8
+ front_end 0.1.4
+ gcloud 0.5.0 (0.6.0+1 available)
+ glob 1.1.7
+ googleapis 0.51.0
+ googleapis_auth 0.2.5+1
+ googleapis_beta 0.46.0
+ grinder 0.8.3
+ html 0.13.3+2
+ http 0.11.3+17
+ http2 0.1.8+2
+ http_multi_server 2.0.5
+ http_parser 3.1.3
+ http_server 0.9.8
+ io 0.3.3
+ js 0.6.1+1
+ json_rpc_2 2.0.9
+ kernel 0.3.4
+ logging 0.11.3+2
+ matcher 0.12.3+1 (0.12.4 available)
+ memcache 0.3.0+1
+ meta 1.1.6
+ mime 0.9.6+2
+ multi_server_socket 1.0.2
+ node_preamble 1.4.4
+ package_config 1.0.5
+ package_resolver 1.0.4
+ path 1.6.2
+ plugin 0.2.0+3
+ pool 1.3.6
+ protobuf 0.8.0 (0.9.0+1 available)
+ pub_semver 1.4.2
+ quiver 0.29.0+2 (2.0.0+1 available)
+ rpc 0.6.0-dev.1
+ shelf 0.7.3+3
+ shelf_packages_handler 1.0.4
+ shelf_static 0.2.8
+ shelf_web_socket 0.2.2+3
+ source_map_stack_trace 1.1.5
+ source_maps 0.10.7
+ source_span 1.4.1
+ stack_trace 1.9.3
+ stream_channel 1.6.8
+ string_scanner 1.0.3
+ term_glyph 1.0.1
+ test 1.3.0
+ typed_data 1.1.6
+ uri 0.11.3
+ utf 0.9.0+5
+ uuid 1.0.1
+ vm_service_client 0.2.6
+ watcher 0.9.7+10
+ web_socket_channel 1.0.9
+ yaml 2.1.15
Changed 72 dependencies!
Precompiling executables... 
Precompiled grinder:grinder.
Precompiled grinder:init.
Precompiled archive:tar.
Precompiled grinder:_boot.
Precompiled discoveryapis_generator:generate.
Precompiled rpc:generate.
Precompiled test:test.
~/dart/clean/dart-services
$ dart --pause-isolates-on-exit --enable-vm-service test/all.dart # expect hang, instead exits with code 241
Observatory listening on http://127.0.0.1:8181/
00:00 +0: analysis_server simple_completion
00:02 +1: analysis_server repro #126 - completions polluted on second request
00:03 +2: analysis_server import_test
00:05 +3: analysis_server import_and_other_test
00:06 +4: analysis_server simple_quickFix
00:08 +5: analysis_server simple_format
00:09 +6: analysis_server format good code
00:11 +7: analysis_server format with issues
00:12 +8: analysis_server analyze
00:14 +9: analysis_server analyze with errors
00:15 +10: analysis_server analyze strong
00:17 +11: analysis_server analyze preview-dart-2
00:20 +12: analysis_server analyze no-preview-dart-2
00:23 +13: AnalysisIssue toMap
00:23 +14: AnalysisIssue toString
00:23 +15: BenchmarkHarness single
00:26 +16: BenchmarkHarness many
00:32 +17: CommonServer (setUpAll)
00:35 +17: CommonServer analyze
INFO: 2018-08-01 11:51:21.753607: PERF: Analyzed 4 lines of Dart in 60ms.
00:35 +18: CommonServer analyze errors
INFO: 2018-08-01 11:51:21.781372: PERF: Analyzed 4 lines of Dart in 13ms.
00:35 +19: CommonServer analyze negative-test noSource
00:35 +20: CommonServer compile
INFO: 2018-08-01 11:51:21.805624: CACHE: MISS, forced: false
INFO: 2018-08-01 11:51:22.379320: PERF: Compiled 4 lines of Dart into 10kb of JavaScript in 573ms.
00:35 +21: CommonServer compile error
INFO: 2018-08-01 11:51:22.395081: CACHE: MISS, forced: false
SEVERE: 2018-08-01 11:51:22.847858: Error during compile: RPC Error with status: 400 and message: main.dart:2:16:
Error: Expected ';' after this.
 
Error: Compilation failed.
 
#0      CommonServer._compile.<anonymous closure>.<anonymous closure> (package:dart_services/src/common_server.dart:378:13)
<asynchronous suspension>
#1      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#2      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#3      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:292:13)
#13     Compiler.compile (package:dart_services/src/compiler.dart)
<asynchronous suspension>
#14     CommonServer._compile.<anonymous closure> (package:dart_services/src/common_server.dart:356:14)
#15     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#16     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#17     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#24     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#25     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#26     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#34     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
 
00:36 +22: CommonServer compile negative-test noSource
00:36 +23: CommonServer complete
INFO: 2018-08-01 11:51:22.887101: PERF: Computed completions in 31ms.
00:36 +24: CommonServer complete no data
00:36 +25: CommonServer complete param missing
00:36 +26: CommonServer complete param missing 2
00:36 +27: CommonServer document
INFO: 2018-08-01 11:51:22.944509: PERF: Computed dartdoc in 32ms.
00:36 +28: CommonServer document little data
INFO: 2018-08-01 11:51:22.967014: PERF: Computed dartdoc in 15ms.
00:36 +29: CommonServer document no data
INFO: 2018-08-01 11:51:22.978302: PERF: Computed dartdoc in 8ms.
00:36 +30: CommonServer document negative-test noSource
00:36 +31: CommonServer document negative-test noOffset
00:36 +32: CommonServer counter test
INFO: 2018-08-01 11:51:23.003401: PERF: Analyzed 4 lines of Dart in 11ms.
00:36 +33: CommonServer format
INFO: 2018-08-01 11:51:23.075272: PERF: Computed format in 68ms.
00:36 +34: CommonServer format bad code
INFO: 2018-08-01 11:51:23.082119: PERF: Computed format in 3ms.
00:36 +35: CommonServer format position
INFO: 2018-08-01 11:51:23.092868: PERF: Computed format in 7ms.
00:36 +36: CommonServer fix
INFO: 2018-08-01 11:51:23.184027: PERF: Computed fixes in 86ms.
00:36 +37: CommonServer version
00:36 +38: CommonServer summarize
INFO: 2018-08-01 11:51:23.196850: About to summarize: 4c6f43598f745bbb8712097be9f008ca63308285
INFO: 2018-08-01 11:51:23.206618: PERF: Analyzed 4 lines of Dart in 9ms.
00:36 +39: CommonServer summarizeDifferent
INFO: 2018-08-01 11:51:23.220677: About to summarize: 4c6f43598f745bbb8712097be9f008ca63308285
INFO: 2018-08-01 11:51:23.230913: PERF: Analyzed 4 lines of Dart in 10ms.
INFO: 2018-08-01 11:51:23.232588: About to summarize: 54910cc942577c871f5d79018c775389d80dbdb5
INFO: 2018-08-01 11:51:23.248835: PERF: Analyzed 5 lines of Dart in 16ms.
00:36 +40: CommonServer (tearDownAll)
00:36 +40: Lines empty string
00:36 +41: Lines getLineForOffset
00:36 +42: stripMatchingQuotes
00:36 +43: vmVersion
00:36 +44: compiler simple
00:37 +45: compiler sourcemap
00:37 +46: compiler version
~/dart/clean/dart-services
$ echo $?
241
~/dart/clean/dart-services
$ vim test/all.dart #comment out line 28, -or- all lines in main() _except_ line 28, or comment out all but some other small subset of main()
~/dart/clean/dart-services
$ git diff
diff --git a/test/all.dart b/test/all.dart
index 4246ce8..434e333 100644
--- a/test/all.dart
+++ b/test/all.dart
@@ -25,7 +25,7 @@ Future main() async {
   analysis_server_test.defineTests();
   api_classes_test.defineTests();
   bench_test.defineTests();
-  common_server_test.defineTests();
+  //common_server_test.defineTests();
   common_test.defineTests();
   compiler_test.defineTests();
   dartpad_server_test.defineTests();
~/dart/clean/dart-services
$ dart --pause-isolates-on-exit --enable-vm-service test/all.dart # now hangs on exit as expected
Observatory listening on http://127.0.0.1:8181/
00:00 +0: analysis_server simple_completion
00:01 +1: analysis_server repro #126 - completions polluted on second request
00:03 +2: analysis_server import_test
00:05 +3: analysis_server import_and_other_test
00:06 +4: analysis_server simple_quickFix
00:08 +5: analysis_server simple_format
00:09 +6: analysis_server format good code
00:11 +7: analysis_server format with issues
00:12 +8: analysis_server analyze
00:14 +9: analysis_server analyze with errors
00:16 +10: analysis_server analyze strong
00:17 +11: analysis_server analyze preview-dart-2
00:20 +12: analysis_server analyze no-preview-dart-2
00:23 +13: AnalysisIssue toMap
00:23 +14: AnalysisIssue toString
00:23 +15: BenchmarkHarness single
00:26 +16: BenchmarkHarness many
00:32 +17: Lines empty string
00:32 +18: Lines getLineForOffset
00:32 +19: stripMatchingQuotes
00:32 +20: vmVersion
00:32 +21: compiler simple
00:33 +22: compiler sourcemap
00:34 +23: compiler version
00:34 +24: compiler verify asserts always enabled
00:35 +25: compiler simple web
00:36 +26: compiler web async
00:38 +27: compiler errors
00:38 +28: compiler good import
00:39 +29: compiler bad import - local
00:39 +30: compiler bad import - http
00:39 +31: compiler disallow compiler warnings
00:40 +32: compiler transitive errors
00:40 +33: compiler errors on previewDart2
00:40 +34: ExportServer Export
00:40 +35: ExportServer Export uuid different
00:40 +36: ExportServer Pull export
00:40 +37: GistMapping ID request
00:40 +38: GistMapping Store gist
00:41 +39: GistMapping Store gist failure
00:41 +40: GistMapping Retrieve gist success
00:41 +41: GistMapping Retrieve gist failure
00:41 +42: pub version
00:41 +43: pub resolvePackages simple
00:42 +44: pub resolvePackages complex
00:45 +45: pub getPackageLibDir
00:46 +46: pub flushCache
00:46 +47: pub PackageInfo name
00:46 +48: pub PackageInfo name bad
00:46 +49: pub PackageInfo version
00:46 +50: pub PackageInfo version bad
00:46 +51: PubHelper resolves content
00:47 +52: PubHelper does not resolve
00:47 +53: MockPub no-op impls
00:47 +54: getAllUnsafeImportsFor null
00:47 +55: getAllUnsafeImportsFor empty
00:47 +56: getAllUnsafeImportsFor bad source
00:47 +57: getAllUnsafeImportsFor one
00:47 +58: getAllUnsafeImportsFor two
00:47 +59: getAllUnsafeImportsFor three
00:47 +60: filterSafePackagesFromImports empty
00:47 +61: filterSafePackagesFromImports simple
00:47 +62: filterSafePackagesFromImports defensive
00:47 +63: filterSafePackagesFromImports negative dart import
00:47 +64: filterSafePackagesFromImports negative path import
00:47 +65: The corsHeaders middleware adds default CORS headers to the response
00:47 +66: The corsHeaders middleware adds custom CORS headers to the response
00:47 +67: Summarizer helpers Unique case detection in list
00:47 +68: Summarizer helpers Unique case detection no false triggers in list
00:47 +69: Summarizer Non-null input does not fail
00:47 +70: Summarizer returnAsMarkDown
00:47 +71: Summarizer Null throws ArgumentError
00:47 +72: Summarizer Same input causes same output
00:47 +73: Summarizer Unique case detection
00:47 +74: Summarizer Unique case detection
00:47 +75: Summarizer Unique case detection no false triggers
00:47 +76: Summarizer Modification causes change
00:47 +77: Summarizer Same input same output
00:47 +78: Summarizer Html and css detection
00:47 +79: All tests passed!
[[[ hangs with isolate paused on exit ]]]
```

**Comment by a-siva** [comment]
@ZichangG can you check if this problem still reproduces, if it does not we can close the issue.
