### ISSUE TITLE
analysis server crash in -dev.69.5 - FixProcessor._addFix_changeTypeAnnotation

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#34074]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.3684.101`
- `2.0.0-dev.69.5`
- `IU-182.3684.101, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 3840x2160`

# Exception
```
Dart analysis server, SDK version 2.0.0-dev.69.5, server version 1.20.3, FATAL error: Failed to handle request: {id: 565, method: edit.getFixes, params: {file: /Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart, offset: 2150}, clientRequestTime: 1533327962706}
NoSuchMethodError: The getter 'parent' was called on null.
Receiver: null
Tried calling: parent
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      FixProcessor._addFix_changeTypeAnnotation (package:analysis_server/src/services/correction/fix_internal.dart:1002:39)
<asynchronous suspension>
#2      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:471:13)
<asynchronous suspension>
#3      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:88:41)
<asynchronous suspension>
#4      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:562:49)
<asynchronous suspension>
#5      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:239:32)
<asynchronous suspension>
#6      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:347:9)
#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:751:45)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#9      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:747:50)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1500:12)
#14     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:746:5)
#15     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#17     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#18     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#49     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#50     _StreamController._add (dart:async/stream_controller.dart:639:7)
#51     _StreamController.add (dart:async/stream_controller.dart:585:5)
#52     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#53     _rootRunUnary (dart:async/zone.dart:1136:13)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#58     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#59     _StreamController._add (dart:async/stream_controller.dart:639:7)
#60     _StreamController.add (dart:async/stream_controller.dart:585:5)
#61     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#62     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#63     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#64     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#65     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#66     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

```
1533327961752 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","classes":[],"members":[]}}
1533327962047 => {"id":"561","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart":{"type":"add","content":"import 'dart:async';\nimpor
1533327962048 <= {"id":"561","result":{}}
1533327962048 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1533327962052 => {"id":"562","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","offset":2149,"length":0},"clientRequestTime":1533327962052}
1533327962071 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","errors":[{"severity":"ERROR","type":"STATIC_TYPE_WARNING","location":{"f
1533327962072 <= {"id":"562","result":{"assists":[]}}
1533327962073 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT
1533327962078 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"lengt
1533327962078 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","labels":[]}}
1533327962079 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":
1533327962079 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","overrides":[]}}
1533327962082 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1533327962084 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","classes":[],"members":[]}}
1533327962377 => {"id":"563","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart":{"type":"add","content":"import 'dart:async';\nimpor
1533327962380 => {"id":"564","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","offset":2150,"length":0},"clientRequestTime":1533327962380}
1533327962381 <= {"id":"563","result":{}}
1533327962382 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1533327962399 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file"
1533327962400 <= {"id":"564","result":{"assists":[]}}
1533327962401 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT
1533327962402 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"lengt
1533327962402 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","labels":[]}}
1533327962403 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":
1533327962403 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","overrides":[]}}
1533327962405 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1533327962407 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","classes":[],"members":[]}}
1533327962706 => {"id":"565","method":"edit.getFixes","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","offset":2150},"clientRequestTime":1533327962706}
1533327962716 => {"id":"566","method":"edit.getFixes","params":{"file":"/Users/kevmoo/source/github/gnarly/shared/lib/rest_service.dart","offset":2150},"clientRequestTime":1533327962716}
1533327962721 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 565, method: edit.getFixes, params: {file: /Users/kevmoo/source/github/gnarly/shared/lib/res
```

**Comment by bwilkerson** [comment]
There is a CL out to fix this (https://dart-review.googlesource.com/c/sdk/+/68435) but it's causing some test failures that I haven't had time to look into. Not sure when I'll be able to get back to this.

**Comment by bwilkerson** [comment]
This finally landed.

**Comment by kevmoo** [comment]
Points for using `Fixes #xyz` in the commit message so we can track which commit/release the fix is in.

In this case d72334e6a26e147e92da57a8601346cdbaf95ddf
