### ISSUE TITLE
Gracefully handle absence of sources in VM

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#34070]
Certain VM code calls `Script::Source()` and does not expect it to return `null`. When running from app-jit snapshot, source is not retained but observatory and debugger are still present. In such case, in Dart 1, VM generated the artificial sources from token streams. However, in Dart 2 `Script::Source()` returns `null` if source is not available.

We should fix all callers of `Script::Source()` to check result for `null` and handle this case gracefully. This includes debugger and observatory which should not crash if source is not available.

Another option is to generate artificial sources from kernel.

For example, test service/next_through_call_on_field_test crashes in the following way in app-jitk mode:
```
tools/test.py --print-passing-stdout -m debug -c app_jitk --strong service/next_through_call_on_field_test
```
```
>testee>err> ../../runtime/vm/object.h: 7379: error: expected: raw() != null()
>testee>err> Dumping native stack trace for thread 373ca
>testee>err>   [0x000056340e5a7d6f] dart::Profiler::DumpStackTrace(void*)
>testee>err>   [0x000056340e5a7d6f] dart::Profiler::DumpStackTrace(void*)
>testee>err>   [0x000056340e85c282] dart::Assert::Fail(char const*, ...)
>testee>err>   [0x000056340e307d46] Unknown symbol
>testee>err>   [0x000056340e4d0448] dart::Script::TokenRangeAtLine(long, dart::TokenPosition*, dart::TokenPosition*) const
>testee>err>   [0x000056340e41f0cf] dart::Debugger::BreakpointLocationAtLineCol(dart::String const&, long, long)
>testee>err>   [0x000056340e41f2bb] dart::Debugger::SetBreakpointAtLineCol(dart::String const&, long, long)
>testee>err>   [0x000056340e6335d2] Unknown symbol
>testee>err>   [0x000056340e628b3d] Unknown symbol
>testee>err>   [0x000056340e626059] dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
>testee>err>   [0x000056340e626ae3] dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
>testee>err>   [0x000056340e43cf1b] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
>testee>err>   [0x000056340e4783fd] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
>testee>err>   [0x000056340e478e36] dart::MessageHandler::TaskCallback()
>testee>err>   [0x000056340e66aee1] dart::ThreadPool::Worker::Loop()
>testee>err>   [0x000056340e66a9bc] dart::ThreadPool::Worker::Main(unsigned long)
>testee>err>   [0x000056340e548ee5] Unknown symbol
>testee>err> -- End of DumpStackTrace
```

If this particular crash is fixed (`Script::TokenRangeAtLine` and `KernelLineStartsReader::TokenRangeAtLine` are changed to handle `null` source), observatory still crashes with exception:
```
NoSuchMethodError: The method '-' was called on null.
Receiver: null
Tried calling: -(0)
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      Script.getLine (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:3537:23)
#2      Script._addBreakpoint (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:3720:5)
#3      Breakpoint._update (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:2394:17)
#4      ServiceObject.updateFromServiceMap (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:401:5)
#5      Isolate.getFromMap (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:1499:11)
#6      _upgradeList (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:4789:23)
#7      _upgradeMap.<anonymous closure> (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:4778:7)
#8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
#9      _upgradeMap (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:4774:7)
#10     _upgradeCollection (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:4767:5)
#11     Isolate._update (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:1642:5)
#12     ServiceObject.updateFromServiceMap (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:401:5)
#13     ServiceObject.reload.<anonymous closure> (file:...dart/sdk/runtime/observatory/lib/src/service/object.dart:359:11)
```

These crashes cause many service/* tests to fail in app-jit mode and may also cause sporadic timeouts on app-kernel-linux-debug-x64 bots.

/cc @a-siva @rmacnak-google

**Comment by bkonyi** [comment]
Do we have any preference whether we update the callers of `Script::Source()` to handle `null` properly or generate artificial sources from kernel? Without the actual source, I'm wondering if it would even be useful for the debugger to display any artificial source information.

**Comment by a-siva** [comment]
I don't think we have a way to generate sources from kernel, I would think gracefully handling null would be the way to go.

**Comment by bkonyi** [comment]
@a-siva, I didn't think we did but just wanted to check. I'll look into where we aren't handling `null` properly with `Script::Source()`.
