### ISSUE TITLE
dart2js crash on language_2/covariant_subtyping_test

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#34099]
The following slice of `language_2/covariant_subtyping_test` crashes with

```
Internal Error: Runtime type information not available for type_variable_local(genericFunctionWithBounds.T) in (local(genericFunctionWithBounds#inner), type_variable_local(call.E)) for j:closure_call(genericFunctionWithBounds_inner.call).
GenericMethodBounds<E> Function<E extends T>() genericFunctionWithBounds<T>() {
```

The error goes away with enough optimizations (tracing to drop signature, `--omit-implicit-checks`), so repro with `-O0`.

```dart
import 'package:expect/expect.dart';

class GenericMethodBounds<T> {
  Type get t => T;
  GenericMethodBounds<E> foo<E extends T>() => new GenericMethodBounds<E>();
  GenericMethodBounds<E> bar<E extends void Function(T)>() =>
      new GenericMethodBounds<E>();
}

GenericMethodBounds<E> Function<E extends T>() genericFunctionWithBounds<T>() {
  inner<E extends T>() => new GenericMethodBounds<E>();
  return inner;
}

testGenericMethodBounds() {
  test(GenericMethodBounds<Object> g) {
    Expect.throwsTypeError(() => g.foo<String>());
    Expect.throwsTypeError(() => g.foo());
    Expect.equals(g.foo<Null>().t, Null);
    Expect.equals(g.foo<int>().t, int);
    Expect.isFalse(g.foo<int>() is GenericMethodBounds<double>);
    g.bar<Function(Object)>();
    dynamic d = g;
    d.bar<Function(num)>();
    Expect.throwsTypeError(() => d.bar<Function(String)>());
    Expect.throwsTypeError(() => d.bar<Function(Null)>());
  }

  test(genericFunctionWithBounds<num>()<int>());
}

main() {
  testGenericMethodBounds();
}
```

```
test.dart:10:48:
Internal Error: Runtime type information not available for type_variable_local(genericFunctionWithBounds.T) in (local(genericFunctionWithBounds#inner), type_variable_local(call.E)) for j:closure_call(genericFunctionWithBounds_inner.call).
GenericMethodBounds<E> Function<E extends T>() genericFunctionWithBounds<T>() {
                                               ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Assertion failure: Runtime type information not available for type_variable_local(genericFunctionWithBounds.T) in (local(genericFunctionWithBounds#inner), type_variable_local(call.E)) for j:closure_call(genericFunctionWithBounds_inner.call).
#0      failedAt (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:49:3)
#1      LocalsHandler.readLocal (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/locals_handler.dart:322:11)
#2      TypeBuilder.addTypeVariableReference.readAsParameter (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:148:12)
#3      TypeBuilder.addTypeVariableReference (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:159:31)
#4      TypeBuilder.analyzeTypeArgument (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:229:14)
#5      KernelSsaGraphBuilder._assertIsType (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:4705:53)
#6      KernelSsaGraphBuilder.checkTypeVariableBounds (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1197:11)
#7      KernelSsaGraphBuilder._potentiallyAddFunctionParameterTypeChecks (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1145:7)
#8      KernelSsaGraphBuilder.openFunction (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1333:7)
#9      KernelSsaGraphBuilder.buildFunctionNode (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:995:5)
#10     KernelSsaGraphBuilder.build.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:221:13)
#11     CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:750:15)
#12     KernelSsaGraphBuilder.build (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:190:21)
#13     KernelSsaBuilder.build.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:116:22)
#14     CompilerTask.measure (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:63:51)
#15     KernelSsaBuilder.build (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:102:17)
#16     SsaBuilderTask.build (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/ssa.dart:96:21)
#17     SsaFunctionCompiler.compile (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/ssa/ssa.dart:44:29)
#18     JavaScriptBackend.codegen (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/backend.dart:697:26)
#19     KernelCodegenWorkItem.run (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:85:21)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:428:70)
#21     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:428:32)
#23     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#24     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:426:28)
#25     CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:750:15)
#26     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:424:18)
#27     CodegenEnqueuer._forEach (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:241:12)
#28     CodegenEnqueuer.forEach (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:256:5)
#29     Compiler.emptyQueue.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:420:16)
#30     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#31     Compiler.emptyQueue (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:419:14)
#32     Compiler.processQueue.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:441:7)
#33     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#34     Compiler.processQueue (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:438:14)
#35     Compiler.generateJavaScriptCode (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:359:5)
#36     Compiler.compileLoadedLibraries.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:385:38)
#37     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#38     Compiler.compileLoadedLibraries (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:379:16)
#39     Compiler.runInternal (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:277:5)
<asynchronous suspension>
#40     Compiler.run.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:216:38)
#41     new Future.sync (dart:async/future.dart:224:31)
#42     Compiler.run.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:216:20)
#43     CompilerTask.measureSubtask (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#44     Compiler.run (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/compiler.dart:213:41)
#45     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/apiimpl.dart:148:22)
#46     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#49     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#50     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#51     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#54     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#55     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
```

**Comment by sigmundch** [comment]
this was fixed a while ago, the test is now passing.
