### ISSUE TITLE
OS Error: Access is denied from analysis.setAnalysisRoots

### ISSUE THREAD

**Issue by Purus** [dart-lang/sdk#34108]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.3911.13`
- `2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822`
- `IC-182.3911.13, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

# Exception

Please append the contents of:
file://C:\Users\Purus\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822, server version 1.20.3, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [F:\05. Project\01-Flutter\SilkThread], excluded: [F:\05. Project\01-Flutter\SilkThread\.idea, F:\05. Project\01-Flutter\SilkThread\.dart_tool, F:\05. Project\01-Flutter\SilkThread\.pub, F:\05. Project\01-Flutter\SilkThread\build, F:\05. Project\01-Flutter\SilkThread\out]}, clientRequestTime: 1533831378907}
FileSystemException: Exists failed, path = 'F:\05. Project\01-Flutter\SilkThread\build\firebase_remote_config\generated\source\r\debug\com\google\android\gms\base' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166)
#3      _HashVMBase

**Comment by Purus** [comment]
Content of `C:\Users\Purus\AppData\Local\Temp\report.txt` is below.

```
Dart analysis server, SDK version 2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822, server version 1.20.3, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [F:\05. Project\01-Flutter\SilkThread], excluded: [F:\05. Project\01-Flutter\SilkThread\.idea, F:\05. Project\01-Flutter\SilkThread\.dart_tool, F:\05. Project\01-Flutter\SilkThread\.pub, F:\05. Project\01-Flutter\SilkThread\build, F:\05. Project\01-Flutter\SilkThread\out]}, clientRequestTime: 1533831378907}
FileSystemException: Exists failed, path = 'F:\05. Project\01-Flutter\SilkThread\build\firebase_remote_config\generated\source\r\debug\com\google\android\gms\base' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#4      _WindowsDirectoryWatcher._onBatch (package:watcher/src/directory_watcher/windows.dart:163)
#5      _WindowsDirectoryWatcher._onEvent.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:157)
#6      _rootRun (dart:async/zone.dart:1122)
#7      _CustomZone.run (dart:async/zone.dart:1023)
#8      _CustomZone.runGuarded (dart:async/zone.dart:925)
#9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#13     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#14     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#15     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

```
1533832904909 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1533832904909 <= {"event":"analysis.flushResults","params":{"files":["F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart___jb_tmp___"]}}
1533832905081 <= {"event":"analysis.errors","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","errors":[]}}
1533832905081 <= {"event":"analysis.highlights","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":39},{"type":"BU
1533832905081 <= {"event":"analysis.navigation","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","regions":[{"offset":7,"length":31,"targets":[0]},{"offset":47,"le
1533832905081 <= {"event":"analysis.closingLabels","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","labels":[{"offset":1405,"length":371,"label":"Scaffold"},{"off
1533832905097 <= {"event":"analysis.outline","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","nam
1533832905097 <= {"event":"analysis.overrides","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","overrides":[{"offset":167,"length":11,"superclassMember":{"element
1533832905144 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1533832905144 <= {"event":"analysis.implemented","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","classes":[],"members":[]}}
1533832905331 => {"id":"383","method":"analysis.updateContent","params":{"files":{"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart":{"type":"remove"}}},"clientRequestTime":153383290
1533832905362 <= {"id":"383","result":{}}
1533832905362 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1533832905394 => {"id":"384","method":"edit.getAssists","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","offset":449,"length":0},"clientRequestTime":1533832905394
1533832905566 <= {"event":"analysis.errors","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","errors":[]}}
1533832905581 <= {"id":"384","result":{"assists":[]}}
1533832905581 <= {"event":"analysis.highlights","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":39},{"type":"BU
1533832905581 <= {"event":"analysis.navigation","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","regions":[{"offset":7,"length":31,"targets":[0]},{"offset":48,"le
1533832905581 <= {"event":"analysis.closingLabels","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","labels":[{"offset":1457,"length":381,"label":"Scaffold"},{"off
1533832905581 <= {"event":"analysis.outline","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","nam
1533832905581 <= {"event":"analysis.overrides","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","overrides":[{"offset":172,"length":11,"superclassMember":{"element
1533832905581 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1533832905581 <= {"event":"analysis.implemented","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","classes":[],"members":[]}}
1533832905909 => {"id":"385","method":"edit.getAssists","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","offset":350,"length":0},"clientRequestTime":1533832905909
1533832905909 <= {"id":"385","result":{"assists":[]}}
1533833004726 => {"id":"386","method":"edit.getAssists","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","offset":350,"length":0},"clientRequestTime":1533833004726
1533833004726 <= {"id":"386","result":{"assists":[]}}
1533833025746 => {"id":"387","method":"edit.getAssists","params":{"file":"F:\\05. Project\\01-Flutter\\SilkThread\\lib\\categories_list.dart","offset":497,"length":0},"clientRequestTime":1533833025746
1533833025746 <= {"id":"387","result":{"assists":[]}}
1533833049162 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [F:\\05. Project\\01-Flutter\\SilkT
```

**Comment by scheglov** [comment]
This might be a `package:watcher` problem, or it might be that we are using is incorrectly.

I will close this issue for now, and reopen depending on the response from the `package:watcher` developers.

**Comment by topex-psy** [comment]
Any update for this issue?
