### ISSUE TITLE
Kernel crash with noSuchMethod, generic method, generic argument with a generic default value

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#34122]
In Dart 2.0.0, take the following script:

```dart
typedef MyHandler<T>(T arg1);

defaultHandler<T>(T arg1) {}

abstract class Mock {
  noSuchMethod(Invocation invocation) => print(invocation);
}

class Foo {
  bar<T>({MyHandler<T> arg: defaultHandler}) {}
}

// Error when this class is defined.
class MockFoo extends Mock implements Foo {}
```

Execute it with the Dart VM:

```none$ dart b.dart
Type parameter T is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:2073:28)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:1703:38)
#2      TypeParameterType.accept (package:kernel/ast.dart:5035:34)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:246:10)
#4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#5      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:238:7)
#6      BinaryPrinter.visitInstantiation (package:kernel/binary/ast_to_binary.dart:1332:5)
#7      Instantiation.accept (package:kernel/ast.dart:2959:36)
#8      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:246:10)
#9      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#10     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:254:7)
#11     BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1597:5)
#12     List.forEach (dart:core/runtime/libgrowable_array.dart:274:8)
#13     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:230:11)
#14     BinaryPrinter.writeVariableDeclarationList (package:kernel/binary/ast_to_binary.dart:1604:5)
#15     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:965:5)
#16     FunctionNode.accept (package:kernel/ast.dart:2007:30)
#17     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:246:10)
#18     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#19     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:254:7)
#20     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:830:5)
#21     Procedure.accept (package:kernel/ast.dart:1669:32)
#22     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:246:10)
#23     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#24     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:238:7)
#25     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:759:5)
#26     Class.accept (package:kernel/ast.dart:905:30)
#27     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:246:10)
#28     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#29     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:238:7)
#30     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:616:5)
#31     Library.accept (package:kernel/ast.dart:409:30)
#32     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:246:10)
#33     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#34     List.forEach (dart:core/runtime/libgrowable_array.dart:274:8)
#35     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:230:11)
#36     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49:5)
#37     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:324:5)
#38     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:60:11)
#39     _processLoadRequest (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:483:11)
<asynchronous suspension>
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

This appears to be a combination of (1) noSuchMethod, (2) the generic method `foo<T>`, (3) the generic default value `defaultHandler`.

This similar code has no errors:

```dart
typedef MyHandler<T>(T arg1);

defaultHandler<T>(T arg1) {}

abstract class Mock {
  noSuchMethod(Invocation invocation) => print(invocation);
}

class Foo {
  bar<T>({MyHandler<T> arg: defaultHandler}) {}
}

// No noSuchMethod; no error.
class SubFoo implements Foo {
  bar<T>({MyHandler<T> arg: defaultHandler}) {}
}

class Okay {
  bar<T>({MyHandler<T> arg}) {}
}

// No generic default value; no error.
class MockOkay extends Mock implements Okay {}

main() {}
```

**Comment by srawlins** [comment]
CC @sjindel-google @stefantsov who have worked with the joys of nSM before.

**Comment by srawlins** [comment]
Quick update, as I know kernel saw a lot of improvements in Dart 2.1.0, the example still crashes, with the same crash, in 2.1.0-dev.8.0.

**Comment by kevmoo** [comment]
I'm hitting something VERY similar with Dart VM version: 2.3.0-dev.0.5 (Tue Apr 30 12:57:36 2019 -0700) on "macos_x64"

**Comment by kevmoo** [comment]
CC @kmillikin

**Comment by mraleph** [comment]
The original code in the bug report no longer crashes.
