### ISSUE TITLE
2 service tests fail in app_jitk mode after 2915e98de9e5d2f4f9017697f4048dc7fabc9a1d

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#34143]
After 2915e98de9e5d2f4f9017697f4048dc7fabc9a1d, the following tests start failing:
```
tools/test.py -m release -c app_jitk -n app_jitk-linux-release-x64 service/step_test
tools/test.py -m release -c app_jitk -n app_jitk-linux-release-x64 service/code_test
```

These tests were not failing at be7022f6d93820334922bc1098b3d85593290adf.

Log:

```
Running out.jitsnapshot [3/4]
Setting breakpoint for line 14
** Killing script
Unexpected exception in service tests: ServerRpcException(addBreakpoint: Cannot add breakpoint at line '14')
#0      setBreakpointAtLine.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/service_test_common.dart:245:22)
<asynchronous suspension>
#1      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/test_helper.dart:331:23)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
stderr:
Unhandled exception:
ServerRpcException(addBreakpoint: Cannot add breakpoint at line '14')
#0      setBreakpointAtLine.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/service_test_common.dart:245:22)
<asynchronous suspension>
#1      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/test_helper.dart:331:23)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
--- Re-run this test:
python tools/test.py -m release -c app_jitk -n app_jitk-linux-release-x64 service/step_test
```

/cc @mkustermann

**Comment by bkonyi** [comment]
This should be fixed when #34070 is resolved.
