### ISSUE TITLE
SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = 8.8.8.7, port = 80

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#34142]
standalone_2/io/socket_cancel_connect_test test fails on vm-kernel-precomp-android-release-3-3-be bot with the following error:

```
Executing adb -s 069a6592003ba933 shell /data/local/tmp/precompilation-testing/dart_precompiled_runtime --sync-async --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-precomp-android-release-3-3-be/build/sdk/.packages /data/local/tmp/precompilation-testing/test/out.aotsnapshot ; echo AdbShellExitCode:  $?
Stdout:
unittest-suite-wait-for-done
SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = 8.8.8.7, port = 80
unittest-suite-success
Unhandled exception:
SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = 8.8.8.7, port = 80
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170)
AdbShellExitCode: 255
ExitCode: 255
Time: 0:00:00.146257
--- Re-run this test:
python tools/test.py -m release -c dartkp -r dart_precompiled -a arm -s android --use-blobs standalone_2/io/socket_cancel_connect_test
```

Could be a network / bot setup problem.

/cc @athomas

**Comment by Sherlock-White** [comment]
My android device occured with the same problem, but I can run my project on web broswer.
What's more, one week ago I could get correct response from the server on the same android device.
Here is my error log：
`E/flutter (10769): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = 139.198.32.71, port = 9900
E/flutter (10769): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
E/flutter (10769): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)
E/flutter (10769): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
E/flutter (10769): #3      Socket._startConnect (dart:io-patch/socket_patch.dart:2038:22)
E/flutter (10769): #4      Socket.startConnect (dart:io/socket.dart:792:21)
E/flutter (10769): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2440:18)
E/flutter (10769): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2834:12)
E/flutter (10769): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2839:12)
E/flutter (10769): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2698:12)
E/flutter (10769): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2570:7)
E/flutter (10769): #10     IOClient.send (package:http/src/io_client.dart:35:38)
E/flutter (10769): #11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
E/flutter (10769): #12     BaseClient.get (package:http/src/base_client.dart:27:7)
E/flutter (10769): #13     Task.getData (package:lessons/common_util/task.dart:16:43)
E/flutter (10769): #14     _ProblemTitleState._getData (package:lessons/common_ui/problem_title.dart:46:36)
E/flutter (10769): #15     _ProblemTitleState.initState (package:lessons/common_ui/problem_title.dart:28:5)
E/flutter (10769): #16     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4893:57)
E/flutter (10769): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
E/flutter (10769): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
E/flutter (10769): #19     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
E/flutter (10769): #20     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
E/flutter (10769): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
E/flutter (10769): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
E/flutter (10769): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284:14)
E/flutter (10769): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
E/flutter (10769): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
E/flutter (10769): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284:14)
E/flutter (10769): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
E/flutter (10769): #28     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
E/flutter (10769): #29     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
E/flutter (10769): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
E/flutter (10769): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
E/flutter (10769): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284:14)
E/flutter (10769): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
E/flutter (10769): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
E/flutter (10769): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
E/flutter (10769): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
E/flutter (10769): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:5)
E/flutter (10769): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
E/flutter (10769): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
E/flutter (10769): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
E/flutter (10769): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
E/flutter (10769): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
E/flutter (10769): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:5)
E/flutter (10769): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
E/flutter (10769): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
E/flutter (10769): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
E/flutter (10769): #47     ComponentElement
`
