### ISSUE TITLE
Non-named arguments following named arguments are not resolved

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#34153]
I'm not certain what the underlying issue is, but it appears that non-named arguments that appear after named arguments are not resolved.

For example, given the following code
```
class A {
  A({int one, String two: 'defaultValue'}) { }
}
main() {
  int o = 0;
  new A(two: 'foo', o);
}
```
the reference to `o` in the constructor's argument list does not have any element information associated with it.

This example is a slight modification of the test `ArgListContributorTest_UseCFE.test_ArgumentList_local_constructor_named_param_4`, and the stack trace from running the test (with these mods) is:
```
  Bad state: No data for o at (offset=95, isSynthetic=false) in /completionTest.dart
  #0      ResolutionApplier._get (package:analyzer/src/fasta/resolution_applier.dart:732:7)
  #1      ResolutionApplier.visitSimpleIdentifier (package:analyzer/src/fasta/resolution_applier.dart:621:16)
  #2      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9447:49)
  #3      ResolutionApplier.visitArgumentList (package:analyzer/src/fasta/resolution_applier.dart:113:18)
  #4      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:418:49)
  #5      ResolutionApplier.visitInstanceCreationExpression (package:analyzer/src/fasta/resolution_applier.dart:439:18)
  #6      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6487:15)
  #7      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4235:18)
  #8      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431:10)
  #9      GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494:39)
  #10     GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:291:59)
  #11     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4231:49)
  #12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8139:20)
  #13     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1253:17)
  #14     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431:10)
  #15     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494:39)
  #16     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:184:31)
  #17     ResolutionApplier.visitBlock (package:analyzer/src/fasta/resolution_applier.dart:158:11)
  #18     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1249:49)
  #19     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1198:13)
  #20     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431:10)
  #21     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314:45)
  #22     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:187:55)
  #23     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1194:49)
  #24     LibraryAnalyzer._resolveFile2 (package:analyzer/src/dart/analysis/library_analyzer.dart:829:45)
  #25     LibraryAnalyzer._analyze2.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:214:13)
  #26     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:364:8)
  #27     LibraryAnalyzer._analyze2.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:211:17)
  #28     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
  #29     LibraryAnalyzer._analyze2.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:210:17)
  <asynchronous suspension>
  #30     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
  <asynchronous suspension>
  #31     LibraryAnalyzer._analyze2 (package:analyzer/src/dart/analysis/library_analyzer.dart:184:26)
  <asynchronous suspension>
  #32     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:100:22)
  <asynchronous suspension>
  #33     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
  <asynchronous suspension>
  #34     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:96:43)
  <asynchronous suspension>
  #35     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1283:71)
  <asynchronous suspension>
  #36     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
  <asynchronous suspension>
  #37     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1241:20)
  <asynchronous suspension>
  #38     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:927:19)
  <asynchronous suspension>
  #39     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005:24)
  <asynchronous suspension>
  #40     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946:5)
  #41     AbstractContextTest.setUp (file:///Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/test/abstract_context.dart:158:15)
  #42     DartCompletionContributorTest.setUp (file:///Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/test/services/completion/dart/completion_contributor_util.dart:555:11)
  #43     _LocalInstanceMirror._invoke (dart:mirrors/runtime/libmirrors_impl.dart:327:37)
  #44     _LocalInstanceMirror.invoke (dart:mirrors/runtime/libmirrors_impl.dart:323:25)
  #45     _LocalClosureMirror.apply (dart:mirrors/runtime/libmirrors_impl.dart:351:17)
  #46     _invokeSymbolIfExists (package:test_reflective_loader/test_reflective_loader.dart:222:32)
  #47     _runTest (package:test_reflective_loader/test_reflective_loader.dart:259:10)
  #48     defineReflectiveTests.<anonymous closure>.<anonymous closure> (package:test_reflective_loader/test_reflective_loader.dart:123:18)
  #49     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:168:27)
  <asynchronous suspension>
  #50     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
  <asynchronous suspension>
  #51     _rootRun (dart:async/zone.dart:1124:13)
  #52     _CustomZone.run (dart:async/zone.dart:1021:19)
  #53     _runZoned (dart:async/zone.dart:1516:10)
  #54     runZoned (dart:async/zone.dart:1463:12)
  #55     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
  #56     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:166:33)
  #57     _rootRun (dart:async/zone.dart:1124:13)
  #58     _CustomZone.run (dart:async/zone.dart:1021:19)
  #59     _runZoned (dart:async/zone.dart:1516:10)
  #60     runZoned (dart:async/zone.dart:1463:12)
  #61     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:165:13)
  <asynchronous suspension>
  #62     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
  <asynchronous suspension>
  #63     new Future.<anonymous closure> (dart:async/future.dart:176:37)
  #64     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #65     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #66     _rootRun (dart:async/zone.dart:1120:38)
  #67     _CustomZone.run (dart:async/zone.dart:1021:19)
  #68     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #69     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #70     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #71     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #72     _rootRun (dart:async/zone.dart:1124:13)
  #73     _CustomZone.run (dart:async/zone.dart:1021:19)
  #74     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
  #75     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
  #76     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
  #77     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
  #78     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:169:12)
```

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
