### ISSUE TITLE
Got this error editing matchers.dart

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#34154]
Iterations of the code
```dart
  @override
  Future<String> matchAsync(dynamic item) async {
    Future<ui.Image> imageFuture;
    if (item is Future<ui.Image>) {
      imageFuture = item;
    } else if (item is ui.Image) {
      imageFuture = new Future.value(item);
    } else {
      final Finder finder = item;
      final Iterable<Element> elements = finder.evaluate();
      if (elements.isEmpty) {
        return 'could not be rendered because no widget was found';
      } else if (elements.length > 1) {
        return 'matched too many widgets';
      }
      imageFuture = _captureImage(elements.single);
    }
```

```dart
  @override
  Future<String> matchAsync(dynamic item) async {
    Future<ui.Image> imageFuture;
    if (item is Future<ui.Image>) {
      imageFuture = item;
    } else if (item is ui.Image) {
      imageFuture = new Future<ui.Image>.value(item);
    } else {
      final Finder finder = item;
      final Iterable<Element> elements = finder.evaluate();
      if (elements.isEmpty) {
        return 'could not be rendered because no widget was found';
      } else if (elements.length > 1) {
        return 'matched too many widgets';
      }
      imageFuture = _captureImage(elements.single);
    }
```

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5087.20`
- `2.0.0-edge.eab492385c3f345cb2f44f3b702b0e30e4a9c107`
- `IU-181.5087.20, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/pl/5yqcvds916b39jxc_pb66y700025bq/T/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.eab492385c3f345cb2f44f3b702b0e30e4a9c107, server version 1.20.5, FATAL error: Failed to handle request: {id: 2664, method: edit.isPostfixCompletionApplicable, params: {file: /Users/jacobr/git/flutter/1/flutter/packages/flutter_test/lib/src/matchers.dart, offset: 51550, key: .return}, clientRequestTime: 1534364101305}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:47:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase

**Comment by devoncarew** [comment]
dup of https://github.com/dart-lang/sdk/issues/34114
