### ISSUE TITLE
passing function that does not return FutureOr<T> to Future<T>.catchError leads to super confusing errors

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#34163]
```dart
import 'dart:async';
import 'dart:io';

void main() {
  onError(e) => true;

  new Future<int>(() => throw "haha").catchError(onError);
}
```

causes 

```
╭─ ~/src/dart/sdk ‹master›
╰─$ out/ReleaseX64/dart /tmp/x.dart                                                     255 ↵
Unhandled exception:
type 'bool' is not a subtype of type 'FutureOr<int>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:147:7)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#3      Future._completeError (dart:async/future_impl.dart:494:5)
#4      _completeWithErrorCallback (dart:async/future.dart:910:10)
#5      new Future.<anonymous closure> (dart:async/future.dart:178:9)
#6      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#7      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#8      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Not a single frame here belongs to the user code - so it is extremely hard to figure out where things went wrong.

**Comment by matanlurey** [comment]
Huge 👍 - see also https://github.com/dart-lang/sdk/issues/34144.

**Comment by lrhn** [comment]
The initial cause of the problem is obviously that we can't type the `Function` argument to `catchError` because it has to allow both unary and binary functions. That means we cannot specify that the function must return `FutureOr<T>`. That ... is annoying. (Possible solutions involves splitting the function in two, only allowing a a binary function, or introducing union types, all of those are breaking changes).

The error here is a late error. We deliberately do not check the actual type of the function, because without a context type, the inferred type of a function literal might not be what it needs to be.
Example:
```dart
Future<SomeValue> future = ...;
future = future.catchError((error) => error.originalValue, (error) => error is SomethingWrongException);
```
Here, we know that the return type of the first function should be `SomeValue`, and indeed it is, because `SomethingWrongException.originalValue` has type `SomeValue`. Due to lack of type inference, we can't *infer* that return type, so the actual return type will be `Object`. 

So, to not punish users for our lack of inference, we delay the type checks and only check the actual return value. That's obviously way later than when you pass the "wrong function"  - but your wrong function has the same type as other *correct* functions, so there is no way to detect that without breaking good code.


The "perfect" type for `catchError` would be:
```dart
Future<T> catchError<E>(FutureOr<T> handleError(E error, StackTrace stack), [bool test(E error)]);
```
This would infer and type-check the above example (with a `, _` for the now mandatory stack trace) just as the user wants (and they can even omit the test function).

Without a way to refer to `E` in the `handleError` parameter, we can't use this kind of type-parameterization because we loose inference.

So, it's annoying, but hard to fix.

**Comment by matanlurey** [comment]
I guess another option is either:

(a) Writing a lint to "ban" `Future.catchError` (i.e. always use `async`/`await`, which is slower)
(b) Creating convenience functions in `package:async`, and ban direct use of `Future.catchError`:

```dart
Future<T> safeCatchError<T, E>(Future<T> future, FutureOr<T> Function(E) handle) {
  return future.catchError((e) {
    if (e is E) {
      return handle(e);
    }
    return new Future.error(e);
  });
}

Future<T> safeCatchStack<T, E>(Future<T> future, FutureOr<T> Function(E, StackTrace) handle) {
  return future.catchError((e, s) {
    if (e is E) {
      return handle(e, s);
    }
    return new Future.error(e, s);
  });
}
```

_By **ban**, I mean write a lint, and enforce it in google3. I imagine other large projects care too_

**Comment by srawlins** [comment]
Note: I'm adding static analysis in the analyzer for this case in #35825 .
