### ISSUE TITLE
Fasta does not detect circular constant expressions

### ISSUE THREAD

**Issue by dhil** [dart-lang/sdk#34204]
According to the specification (c.f. end of §16.1) it is a compile-time error if the value of a constant expression depends on itself. The analyzer and fasta both reject the following program `circular_consts0.dart`, but for different reasons:
```dart
class CircularConsts0 {
  // Illegal program - mutually recursive compile-time constants
  static const i = j; // a compile-time constant
  static const j = i; // a compile-time constant
}

void main() {}
```
The analyzer correctly detects the circularity:
```
$ dartanalyzer circular_consts0.dart
Analyzing circular_consts0.dart...
  error • Compile-time constant expression depends on itself at circular_consts0.dart:3:16 • recursive_compile_time_constant
  error • The type of 'i' can't be inferred because it depends on itself through the cycle: [j, i] at bug.dart:3:20 • strong_mode_top_level_cycle
  error • Compile-time constant expression depends on itself at circular_consts0.dart:4:16 • recursive_compile_time_constant
  error • The type of 'j' can't be inferred because it depends on itself through the cycle: [j, i] at bug.dart:4:20 • strong_mode_top_level_cycle
4 errors found.
```
Moreover, the analyzer also alerts that type inference failed. Type inference also fails in fasta:
```
$ fasta compile --strong circular_consts0.dart
circular_consts0.dart:4:16: Error: Can't infer the type of 'j': circularity found during type inference.
Specify the type explicitly.
  static const j = i; // a compile-time constant
               ^
circular_consts0.dart:3:16: Error: Can't infer the type of 'i': circularity found during type inference.
Specify the type explicitly.
  static const i = j; // a compile-time constant
```
Following the advice of fasta, to explicity specify the type, leads to disaster. Consider the following program `circular_consts1.dart`:
```dart
class CircularConsts1 {
  static const int i = j; // a compile-time constant with declared type int
  static const j = i;
}

void main() {
  print("${CircularConsts1.i}");
}
```
Declaring the type of either compile-time constant is sufficient to resolve the type inference problem. As a result fasta no longer complains...
```
$ fasta compile --strong circular_consts1.dart
$ echo $?
0
```
... meaning that we can run the program
```
$ dart circular_consts1.dart
Unhandled exception:
'circular_consts1.dart': error: line 3 pos 20: Not a constant expression.
  static const j = i;
                   ^
'circular_consts1.dart': error: line 2 pos 24: Not a constant expression.
  static const int i = j; // a compile-time constant
                       ^
'circular_consts1.dart: error: line 7 pos 28: Not a constant expression.
  print("${CircularConsts1.i}");
                           ^

#0      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#1      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Fasta should detect the circularity irrespective of type inference and produce a compile-time error.

**Comment by dhil** [comment]
Related to #34189.

**Comment by johnniwinther** [comment]
FYI: this error is reported by dart2js.

**Comment by askeksa-google** [comment]
Closing because there is no more work to do on this except flipping the flag. This will give us a better overview of remaining issues.
