### ISSUE TITLE
NoSuchMethodError: The getter 'isBottom' was called on null

### ISSUE THREAD

**Issue by Mantas0726** [dart-lang/sdk#34209]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.0.0-edge.eab492385c3f345cb2f44f3b702b0e30e4a9c107`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Mantoska\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.eab492385c3f345cb2f44f3b702b0e30e4a9c107, server version 1.20.5, error: Analysis failed: C:\taskermate_flutter\lib\networking\TM_api.dart context: exception_20180821_110102_005
NoSuchMethodError: The getter 'isBottom' was called on null.
Receiver: null
Tried calling: isBottom
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:47:5)
#1      _isBottom (package:analyzer/src/generated/type_system.dart:50:12)
#2      GenericInferrer._matchSubtypeOf (package:analyzer/src/generated/type_system.dart:654:9)
#3      GenericInferrer.tryMatchSubtypeOf (package:analyzer/src/generated/type_system.dart:271:20)
#4      GenericInferrer.constrainArgument (package:analyzer/src/generated/type_system.dart:116:5)
#5      StrongTypeSystemImpl.inferGenericFunctionOrType (package:analyzer/src/generated/type_system.dart:950:16)
#6      StaticTypeAnalyzer._inferGenericInvoke (package:analyzer/src/generated/static_type_analyzer.dart:1472:17)
#7      StaticTypeAnalyzer._inferInstanceCreationExpression (package:analyzer/src/generated/static_type_analyzer.dart:1511:29)
#8      StaticTypeAnalyzer.visitInstanceCreationExpression (package:analyzer/src/generated/static_type_analyzer.dart:544:5)
#9      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6487:15)
#10     ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:6066:10)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/73240
