### ISSUE TITLE
in analysis server code completion, type 'PrefixedIdentifierImpl' is not a subtype of type 'SimpleIdentifier'

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34227]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.3911.36`
- `2.1.0-edge.00d9330987079553842defdfca0a8919a467033e`
- `IC-182.3911.36, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/00/0w978000h01000cxqpysvccm003j4x/T/report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.00d9330987079553842defdfca0a8919a467033e, server version 1.20.5, error: Failed to handle completion domain request: {id: 50, method: completion.getSuggestions, params: {file: /Users/devoncarew/projects/workspace/sdk/pkg/analysis_server/test/integration/edit/get_postfix_completion_test.dart, offset: 770}, clientRequestTime: 1534959354087}
type 'PrefixedIdentifierImpl' is not a subtype of type 'SimpleIdentifier'
#0      _getTargetId (package:analysis_server/src/services/completion/dart/arglist_contributor.dart:65:7)
#1      ArgListContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/arglist_contributor.dart:189:33)
<asynchronous suspension>
#2      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:110:29)
<asynchronous suspension>
#3      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:97:46)
<asynchronous suspension>
#4      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:208:5)
<asynchronous suspension>
#5      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:143:9)
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/71188
