### ISSUE TITLE
analysis server crash - 2.1.0-dev.1.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#34226]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.4129.33`
- `2.1.0-dev.1.0`
- `IU-182.4129.33, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 3840x2160`

# Exception

```
Dart analysis server, SDK version 2.1.0-dev.1.0, server version 1.20.5, error: Exception while using a InvariantBooleans to visit a CompilationUnitImpl
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      _InvariantBooleansVisitor.visitCondition (package:linter/src/rules/invariant_booleans.dart:143:51)
#2      ConditionScopeVisitor._visitIfStatement (package:linter/src/util/condition_scope_visitor.dart:364:5)
#3      ConditionScopeVisitor.visitIfStatement (package:linter/src/util/condition_scope_visitor.dart:212:5)
#4      IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:6048:49)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8139:20)
#6      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1253:17)
#7      RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:647:10)
#8      BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1249:49)
#9      BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1198:13)
#10     ConditionScopeVisitor.visitBlockFunctionBody (package:linter/src/util/condition_scope_visitor.dart:148:10)
#11     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1194:49)
#12     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5369:12)
#13     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:869:10)
#14     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5363:49)
#15     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5207:26)
#16     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:857:10)
#17     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5200:49)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8139:20)
#19     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2430:21)
#20     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707:10)
#21     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2423:49)
#22     LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:659:14)
#23     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:119:5)
#24     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2423:49)
#25     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:394:10)
#26     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:165:13)
#27     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
#28     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:164:17)
#29     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#30     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:163:37)
#31     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:16)
<asynchronous suspension>
#32     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#33     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:96:43)
<asynchronous suspension>
#34     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1283:71)
<asynchronous suspension>
#35     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#36     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1241:20)
<asynchronous suspension>
#37     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:927:19)
<asynchronous suspension>
#38     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005:24)
<asynchronous suspension>
#39     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946:5)
#40     new AnalysisServer (package:analysis_server/src/analysis_server.dart:391:29)
#41     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:78:26)
#42     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#43     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:484:21)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _runZoned (dart:async/zone.dart:1516:10)
#47     runZoned (dart:async/zone.dart:1463:12)
#48     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:528:12)
#49     Driver.start (package:analysis_server/src/server/driver.dart:482:7)
#50     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12:11)
#51     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1534958786128 => {"id":"884","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","offset":4627,"length":0},"clientRequestTime":153495878612
1534958786131 <= {"id":"883","result":{}}
1534958786131 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1534958786156 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"fi
1534958786157 <= {"id":"884","result":{"assists":[]}}
1534958786158 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","regions":[{"type":"DIRECTIVE","offset":217,"length":17},{"type":"
1534958786160 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","regions":[{"offset":224,"length":9,"targets":[0]},{"offset":243,"
1534958786160 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","labels":[]}}
1534958786160 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","nam
1534958786160 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","overrides":[]}}
1534958786163 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1534958786163 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","classes":[],"members":[]}}
1534958786459 => {"id":"885","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart":{"type":"add","content":"// Copyright (c) 2017, t
1534958786469 <= {"id":"885","result":{}}
1534958786469 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1534958786470 => {"id":"886","method":"edit.getAssists","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","offset":4628,"length":0},"clientRequestTime":153495878647
1534958786496 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/Users/
1534958786498 <= {"id":"886","result":{"assists":[]}}
1534958786501 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","regions":[{"type":"DIRECTIVE","offset":217,"length":17},{"type":"
1534958786503 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","regions":[{"offset":224,"length":9,"targets":[0]},{"offset":243,"
1534958786503 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","labels":[]}}
1534958786503 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","nam
1534958786503 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","overrides":[]}}
1534958786506 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1534958786506 <= {"event":"analysis.implemented","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","classes":[],"members":[]}}
1534958786567 => {"id":"887","method":"analysis.updateContent","params":{"files":{"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart":{"type":"add","content":"// Copyright (c) 2017, t
1534958786567 => {"id":"888","method":"completion.getSuggestions","params":{"file":"/Users/kevmoo/source/github/mono_repo/mono_repo/lib/src/utils.dart","offset":4629},"clientRequestTime":1534958786567
1534958786568 <= {"id":"887","result":{}}
1534958786568 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1534958786593 <= {"event":"server.error","params":{"isFatal":false,"message":"Exception while using a InvariantBooleans to visit a CompilationUnitImpl","stackTrace":"NoSuchMethodError: The getter 'nam
```

**Comment by bwilkerson** [comment]
Correct. The real analyzer bug is that it isn't protected against failures like this in lints.
