### ISSUE TITLE
"The getter 'className' was called on null" when calling VM service evaluate method

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#34224]
Below are request/responses to the VM service to evaluate `toString()` on an instance. This throws a NoSuchMethodError because it seems to try to access `className` of null.

The code looks like this:

```dart
main() {
  Object a = new Object();
  Object b = new Object();
  Object c = new Object();
  print(a); // Breakpoint here
}
```

The code sends an evaluateInFrame for `a` which returns an object with ID `objects/19`. This ID is sent in an `evaluateRequest` to evaluate its `toString()` method, however that fails with the error.

(Note: This is the release v2.0.0 SDK running on the VM, it is not Flutter)

```js
==> {
	"id": "27",
	"method": "evaluateInFrame",
	"params": {
		"expression": "a",
		"frameIndex": 0,
		"isolateId": "isolates/518820155"
	}
}

<== {
	"jsonrpc": "2.0",
	"result": {
		"type": "@Instance",
		"class": {
			"type": "@Class",
			"fixedId": true,
			"id": "classes\/39",
			"name": "Object"
		},
		"kind": "PlainInstance",
		"id": "objects\/19"
	},
	"id": "27"
}

==> {
	"id": "28",
	"method": "evaluate",
	"params": {
		"expression": "toString()",
		"isolateId": "isolates/518820155",
		"targetId": "objects/19"
	}
}

==> {
	"code": 113,
	"message": "Expression compilation error",
	"data": {
		"details": "NoSuchMethodError: The getter 'className' was called on null.
		Receiver: null
		Tried calling: className
		#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
		#1      serializeProcedure (package:front_end/src/fasta/kernel/utils.dart:82)
		#2      _processExpressionCompilationRequest (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/vm/bin/kernel_service.dart:296)
		<asynchronous suspension>
		#3      _processLoadRequest (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/vm/bin/kernel_service.dart:367)
		<asynchronous suspension>
		#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
		"
	}
}
```

**Comment by goderbauer** [comment]
I am seeing the same error when debugging a Flutter app running on a device with IntelliJ. After the exception the debugger becomes unusable because it can't resolve the values of variables any more and after stepping some more IntelliJ just exits out of the debugging mode.

**Comment by mraleph** [comment]
Assigning to @kmillikin for triage. 

This bug is a serious developer experience issue - because our tools should not be just crashing on developers for unclear reasons. Setting priority to P1.

/cc @a-siva @aam

**Comment by kmillikin** [comment]
@jensjoha can you take a look at this?

**Comment by belichenk0andreyka** [comment]
Help me please! I can not get rid of this error! (Could not load source 'dart:core/runtime/libobject_patch.dart': <source not available>)
I have two drop lists (one drop list with sports and the other with countries) and a list with leagues. The list with leagues should be sorted when selecting items in the drop lists, This error pops up when I select the country in the drop lists.
[https://github.com/belichenk0andreyka/GitHubFirstApp/blob/Json_branch/lib/home_screen/leagues_list.dart](Link of project on GitHub)

**Comment by belichenk0andreyka** [comment]
Помоги мне, пожалуйста! Я не могу избавиться от этой ошибки! (Не удалось загрузить источник 'dart: core / runtime / libobject_patch.dart':) У 
меня есть два раскрывающихся списка (один со списком со спортом, а другой со странами) и со списком лиг. Список с лигами должен быть отсортирован при выборе элементов в выпадающих списках. Эта ошибка появляется, когда я выбираю страну в выпадающих списках. 
My project on GitHub:
[https://github.com/belichenk0andreyka/GitHubFirstApp/blob/Json_branch/lib/home_screen/leagues_list.dart](url)

**Comment by belichenk0andreyka** [comment]
Help me please! I can not get rid of this error! Could not load source 'dart:core/runtime/libobject_patch.dart': <source not available>
 I have two drop lists (one drop list with sports and the other with countries) and a list with leagues. The list with leagues should be sorted when selecting items in the drop lists, This error pops up when I select the city in the drop lists.
Link to my project on GitHub:
[https://github.com/belichenk0andreyka/GitHubFirstApp/blob/Json_branch/lib/home_screen/leagues_list.dart](url)

**Comment by mraleph** [comment]
@belichenk0andreyka please don't leave comments on random issues that have nothing to do with the error you are seeing. 

As you can see on the left hand side - you are hitting `noSuchMethod` error, most likely because `jsonData[_str]` is `null`. I see that you set `_str` to `countrys`, I guess that should instead be `countries`.
