### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by viratshukla** [dart-lang/sdk#34221]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.0.0-edge.be6309690fd60284a87f3258a740c7c30efb1092`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\admin\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.be6309690fd60284a87f3258a740c7c30efb1092, server version 1.20.5, FATAL error: Failed to handle request: {id: 792, method: edit.isPostfixCompletionApplicable, params: {file: D:\FlutterProjects\sipaper\lib\location_list.dart, offset: 62, key: .for}, clientRequestTime: 1534919485838}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:47:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase

**Comment by devoncarew** [comment]
Thanks for the report! Marking as a dup of https://github.com/dart-lang/sdk/issues/34114
