### ISSUE TITLE
pkg/plugin_manager_test is flaky

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#34231]
Most frequently fails with
```
Running "vm" command: set DART_CONFIGURATION=ReleaseX64 & out\ReleaseX64\dart-sdk\bin\dart.exe --enable_asserts --ignore-unrecognized-flags --packages=C:\b\s\w\ir\cache\builder\sdk\.packages C:\b\s\w\ir\cache\builder\sdk\pkg\analyzer\test\generated\package_test.dart
FAILED: dartk-vm release_x64 pkg/analysis_server/test/src/plugin/plugin_manager_test
Expected: Pass Slow
Actual: RuntimeError
--- Command "vm" (took 04:26.000037s):
set DART_CONFIGURATION=ReleaseX64 & out\ReleaseX64\dart-sdk\bin\dart.exe --enable_asserts --ignore-unrecognized-flags --packages=C:\b\s\w\ir\cache\builder\sdk\.packages C:\b\s\w\ir\cache\builder\sdk\pkg\analysis_server\test\src\plugin\plugin_manager_test.dart
exit code:
255
stdout:
00:00 [32m+0[0m: BuiltInPluginInfoTest | test_addContextRoot[0m
00:00 [32m+1[0m: BuiltInPluginInfoTest | test_creation[0m
00:00 [32m+2[0m: BuiltInPluginInfoTest | test_removeContextRoot[0m
00:00 [32m+3[0m: BuiltInPluginInfoTest | test_start_notRunning[0m
00:00 [32m+4[0m: BuiltInPluginInfoTest | test_start_running[0m
00:00 [32m+5[0m: BuiltInPluginInfoTest | test_stop_notRunning[0m
00:00 [32m+6[0m: BuiltInPluginInfoTest | test_stop_running[0m
00:00 [32m+7[0m: DiscoveredPluginInfoTest | test_addContextRoot[0m
00:00 [32m+8[0m: DiscoveredPluginInfoTest | test_creation[0m
00:00 [32m+9[0m: DiscoveredPluginInfoTest | test_removeContextRoot[0m
00:00 [32m+10[0m: DiscoveredPluginInfoTest | test_start_notRunning[0m
00:00 [32m+11[0m: DiscoveredPluginInfoTest | test_start_running[0m
00:00 [32m+12[0m: DiscoveredPluginInfoTest | test_stop_notRunning[0m
00:00 [32m+13[0m: DiscoveredPluginInfoTest | test_stop_running[0m
00:00 [32m+14[0m: PluginManagerTest | test_broadcastRequest_none[0m
00:00 [32m+15[0m: PluginManagerTest | test_creation[0m
00:00 [32m+16[0m: PluginManagerTest | test_pathsFor_withPackagesFile[0m
00:00 [32m+17[0m: PluginManagerTest | test_pathsFor_withPubspec_inBazelWorkspace[0m
00:00 [32m+18[0m: PluginManagerTest | test_pluginsForContextRoot_none[0m
00:00 [32m+19[0m: PluginManagerTest | test_stopAll_none[0m
00:00 [32m+20[0m: PluginManagerFromDiskTest | test_addPluginToContextRoot[0m
00:22 [32m+21[0m: PluginManagerFromDiskTest | test_addPluginToContextRoot_pubspec[0m
00:22 [32m+22[0m: PluginManagerFromDiskTest | test_broadcastRequest_many[0m
00:52 [32m+23[0m: PluginManagerFromDiskTest | test_broadcastRequest_many_noContextRoot[0m
01:20 [32m+24[0m: PluginManagerFromDiskTest | test_broadcastWatchEvent[0m
01:34 [32m+25[0m: PluginManagerFromDiskTest | test_pluginsForContextRoot_multiple[0m
02:04 [32m+25[0m[31m -1[0m: PluginManagerFromDiskTest | test_pluginsForContextRoot_multiple [1m[31m[E][0m[0m
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
  package:test/src/backend/invoker.dart 332:26                  Invoker._handleError.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test/src/backend/invoker.dart 330:10                  Invoker._handleError
  package:test/src/backend/invoker.dart 283:9                   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test/src/backend/invoker.dart 281:38                  Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 947:23                                   _CustomZone.bindCallback.<fn>
  dart:async/runtime/libtimer_patch.dart 21:15                  Timer._createTimer.<fn>
  dart:isolate/runtime/libtimer_impl.dart 382:19                _Timer._runTimers
  dart:isolate/runtime/libtimer_impl.dart 416:5                 _Timer._handleMessage
  dart:isolate/runtime/libisolate_patch.dart 171:12             _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 946:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1191:21                                  _rootCreateTimer
  dart:async/zone.dart 1088:19                                  _CustomZone.createTimer
  package:test/src/backend/invoker.dart 280:34                  Invoker.heartbeat
  package:test/src/backend/invoker.dart 242:5                   Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 166:33                 Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 1516:10                                  _runZoned
  dart:async/zone.dart 1463:12                                  runZoned
  package:test/src/backend/declarer.dart 165:13                 Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test/src/backend/invoker.dart 402:15                  Invoker._onRun.<fn>.<fn>.<fn>
  
02:04 [32m+25[0m[31m -1[0m: PluginManagerFromDiskTest | test_pluginsForContextRoot_one[0m
02:25 [32m+26[0m[31m -1[0m: PluginManagerFromDiskTest | test_removedContextRoot[0m
02:40 [32m+27[0m[31m -1[0m: PluginManagerFromDiskTest | test_restartPlugins[0m
03:39 [32m+28[0m[31m -1[0m: PluginSessionTest | test_handleNotification[0m
03:39 [32m+29[0m[31m -1[0m: PluginSessionTest | test_handleOnDone[0m
03:39 [32m+30[0m[31m -1[0m: PluginSessionTest | test_handleOnError[0m
03:39 [32m+31[0m[31m -1[0m: PluginSessionTest | test_handleResponse[0m
03:39 [32m+32[0m[31m -1[0m: PluginSessionTest | test_nextRequestId[0m
03:39 [32m+33[0m[31m -1[0m: PluginSessionTest | test_sendRequest[0m
03:39 [32m+34[0m[31m -1[0m: PluginSessionTest | test_start_notCompatible[0m
03:39 [32m+35[0m[31m -1[0m: PluginSessionTest | test_start_running[0m
03:39 [32m+36[0m[31m -1[0m: PluginSessionTest | test_stop_notRunning[0m
03:39 [32m+37[0m[31m -1[0m: PluginSessionTest | test_stop_running[0m
03:39 [32m+38[0m[31m -1[0m: PluginSessionFromDiskTest | test_start_notRunning[0m
03:53 [32m+39[0m[31m -1[0m: [31mSome tests failed.[0m
stderr:
Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
--- Re-run this test:
python tools/test.py -m release -n unittest-asserts-win pkg/analysis_server/test/src/plugin/plugin_manager_test
Done dartk-vm release_x64 pkg/analysis_server/test/src/plugin/plugin_manager_test: fail
!@@@STEP_CLEAR@@@
```

Seems to have started with https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/pkg-win-release/1774

**Comment by vsmenon** [comment]
@bwilkerson @athomas - not sure this is analyzer server test infra or underlying infra.

**Comment by keertip** [comment]
Closing as obsolete.
