### ISSUE TITLE
Received "The compiler is broken" message from Dart2JS

### ISSUE THREAD

**Issue by ajrcarey** [dart-lang/sdk#34261]
During a compilation from Dart 2.0 code to Javascript, the following message was received:

```
Dart2Js finished with:

packages/duet_foundation/src/query/upsert/query.dart:17:40:
Internal Error: The compiler crashed when compiling this element.
  @override Promise<UpsertQueryResult> execute(
                                       ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.0.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'thisLocal' was called on null.
Receiver: null
Tried calling: thisLocal
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      LocalsHandler.startFunction (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/ssa/locals_handler.dart:240:51)
#2      KernelSsaGraphBuilder.openFunction (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1309:19)
#3      KernelSsaGraphBuilder.buildFunctionNode (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:987:5)
#4      KernelSsaGraphBuilder.build.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:203:15)
#5      CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:750:15)
#6      KernelSsaGraphBuilder.build (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:188:21)
#7      KernelSsaBuilder.build.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:116:22)
#8      CompilerTask.measure (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63:51)
#9      KernelSsaBuilder.build (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:102:17)
#10     SsaBuilderTask.build (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/ssa/ssa.dart:96:21)
#11     SsaFunctionCompiler.compile (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/ssa/ssa.dart:44:29)
#12     JavaScriptBackend.codegen (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/js_backend/backend.dart:700:26)
#13     KernelCodegenWorkItem.run (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:85:21)
#14     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:428:70)
#15     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#16     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:428:32)
#17     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#18     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:426:28)
#19     CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:750:15)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:424:18)
#21     EnqueuerStrategy.processWorkItem (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/enqueue.dart:501:6)
#22     CodegenEnqueuer._forEach (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:247:20)
#23     CodegenEnqueuer.forEach (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:262:5)
#24     Compiler.emptyQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:420:16)
#25     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#26     Compiler.emptyQueue (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:419:14)
#27     Compiler.processQueue.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:441:7)
#28     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#29     Compiler.processQueue (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:438:14)
#30     Compiler.generateJavaScriptCode (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:359:5)
#31     Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:385:38)
#32     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#33     Compiler.compileLoadedLibraries (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:379:16)
#34     Compiler.runInternal (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:277:5)
<asynchronous suspension>
#35     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:216:38)
#36     new Future.sync (dart:async/future.dart:224:31)
#37     Compiler.run.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:216:20)
#38     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#39     Compiler.run (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:213:41)
#40     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/compiler/lib/src/apiimpl.dart:148:22)
#41     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#44     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#45     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#46     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#49     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

Submitting as instructed by the compiler :)

This is on Dart 2.0.0 running on linux 64. There are no analysis issues with the code. It should theroetically run on flutter as well, I will try and find time to test that out later on and report back.

Let me know what I can do to help.

**Comment by zoechi** [comment]
Can you provide a minimal reproduction?

**Comment by ajrcarey** [comment]
No, because I do not know what is causing the problem. As I already stated, there are no errors in the code. I would need guidance on how to track the error in the compiler from your end.

**Comment by sigmundch** [comment]
@ajrcarey - in this case, the most helpful thing would be to have some code snippets to see what the compiler was trying to do.

If by any chance your code is open-source, you could give us a pointer at how/where you compile your app. If your app is not available openly, another option is to share the body of `execute` (from packages/duet_foundation/src/query/upsert/query.dart:17:40)
