### ISSUE TITLE
dar2js crash: Assertion failure: Runtime type information not available for type_variable_local...

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#34272]
The test (will be submitted as tests/language_2/closure_type_arguments_test.dart):

```dart
import "package:expect/expect.dart";

typedef MapFunc<S1, S2> = void Function(Map<S1, S2> arg);

class A<P> {
  final List barTypeArguments = [];

  void foo<Q, Q1 extends P, Q2 extends Q, Q3 extends P, Q4 extends Q>() {
    void bar<T1 extends P, T2 extends Q>(Map<T1, T2> arg) {
      barTypeArguments..add(T1)..add(T2);
    }

    // Call with explicit type arguments.
    bar<Q1, Q2>(null);

    // No explicit type arguments - should be instantiated to bounds.
    bar(null);

    // Partial tear-off instantiation.
    MapFunc<Q3, Q4> instantiated = bar;
    instantiated(null);
  }
}

abstract class MyIterable implements Iterable {}

main() {
  final a = new A<num>();
  a.foo<Iterable, int, List, double, MyIterable>();
  Expect.listEquals(
      [int, List, num, Iterable, double, MyIterable], a.barTypeArguments);

  // Test instantiation to bounds in the enclosing method.
  dynamic b = new A<int>();
  b.foo();
  Expect.listEquals(
      [int, dynamic, int, dynamic, int, dynamic], b.barTypeArguments);
}
```

dart2js crashes with the following error:
```
tests/language_2/closure_type_arguments_test.dart:12:8:
Internal Error: Runtime type information not available for type_variable_local(foo.Q) in (local(A.foo#arg), local(A.foo#bar), type_variable_local(call.T1), type_variable_local(call.T2)) for j:closure_call(A_foo_bar.call).
  void foo<Q, Q1 extends P, Q2 extends Q, Q3 extends P, Q4 extends Q>() {
       ^
The compiler is broken.
When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.
The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.
Please include the following information:
* the name and version of your operating system,
* the Dart SDK build number (2.1.0-edge.5e4e6037a91538cb369353525d89d391421b2a51), and
* the entire message you see here (including the full stack trace
  below as well as the source location above).
The compiler crashed: Assertion failure: Runtime type information not available for type_variable_local(foo.Q) in (local(A.foo#arg), local(A.foo#bar), type_variable_local(call.T1), type_variable_local(call.T2)) for j:closure_call(A_foo_bar.call).
#0      failedAt (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:49:3)
#1      LocalsHandler.readLocal (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/locals_handler.dart:322:11)
#2      TypeBuilder.addTypeVariableReference.readAsParameter (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:143:12)
#3      TypeBuilder.addTypeVariableReference (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:154:31)
#4      TypeBuilder.analyzeTypeArgument (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:224:14)
#5      KernelSsaGraphBuilder._assertIsType (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:4594:53)
#6      KernelSsaGraphBuilder.checkTypeVariableBounds (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1188:11)
#7      KernelSsaGraphBuilder._potentiallyAddFunctionParameterTypeChecks (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1141:7)
#8      KernelSsaGraphBuilder.openFunction (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1324:7)
#9      KernelSsaGraphBuilder.buildFunctionNode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:991:5)
#10     KernelSsaGraphBuilder.build.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:220:13)
#11     CompilerDiagnosticReporter.withCurrentElement (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:750:15)
#12     KernelSsaGraphBuilder.build (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:189:21)
#13     KernelSsaBuilder.build.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:117:22)
#14     CompilerTask.measure (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:63:51)
#15     KernelSsaBuilder.build (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:103:17)
#16     SsaBuilderTask.build (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/ssa.dart:96:21)
#17     SsaFunctionCompiler.compile (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/ssa.dart:44:29)
#18     JavaScriptBackend.codegen (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/backend.dart:697:26)
#19     KernelCodegenWorkItem.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:86:21)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:428:70)
#21     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:428:32)
#23     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#24     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:426:28)
#25     CompilerDiagnosticReporter.withCurrentElement (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:750:15)
#26     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:424:18)
#27     CodegenEnqueuer._forEach (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:236:12)
#28     CodegenEnqueuer.forEach (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:251:5)
#29     Compiler.emptyQueue.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:420:16)
#30     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#31     Compiler.emptyQueue (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:419:14)
#32     Compiler.processQueue.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:441:7)
#33     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#34     Compiler.processQueue (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:438:14)
#35     Compiler.generateJavaScriptCode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:359:5)
#36     Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:385:38)
#37     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#38     Compiler.compileLoadedLibraries (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:379:16)
#39     Compiler.runInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:277:5)
<asynchronous suspension>
#40     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:216:38)
#41     new Future.sync (dart:async/future.dart:224:31)
#42     Compiler.run.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:216:20)
#43     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#44     Compiler.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:213:41)
#45     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/apiimpl.dart:148:22)
#46     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#49     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#50     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#51     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#54     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#55     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by sigmundch** [comment]
Marking as fixed - this is working at the latest version of the compiler, woohoo! We didn't track when this got fixed though
