### ISSUE TITLE
Incorrect type argument in a generic closure in DDC

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#34273]
The test (will be submitted as tests/language_2/closure_type_arguments_test.dart):

```dart
import "package:expect/expect.dart";

typedef MapFunc<S1, S2> = void Function(Map<S1, S2> arg);

class A<P> {
  final List barTypeArguments = [];

  void foo<Q, Q1 extends P, Q2 extends Q, Q3 extends P, Q4 extends Q>() {
    void bar<T1 extends P, T2 extends Q>(Map<T1, T2> arg) {
      barTypeArguments..add(T1)..add(T2);
    }

    // Call with explicit type arguments.
    bar<Q1, Q2>(null);

    // No explicit type arguments - should be instantiated to bounds.
    bar(null);

    // Partial tear-off instantiation.
    MapFunc<Q3, Q4> instantiated = bar;
    instantiated(null);
  }
}

abstract class MyIterable implements Iterable {}

main() {
  final a = new A<num>();
  a.foo<Iterable, int, List, double, MyIterable>();
  Expect.listEquals(
      [int, List, num, Iterable, double, MyIterable], a.barTypeArguments);

  // Test instantiation to bounds in the enclosing method.
  dynamic b = new A<int>();
  b.foo();
  Expect.listEquals(
      [int, dynamic, int, dynamic, int, dynamic], b.barTypeArguments);
}
```

Output:
```
Runtime error:
Expect.listEquals(at index 1, expected: <dynamic>, actual: <Object>) fails
at Object.dart.throw (http://127.0.0.1:44619/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:4212:29)
    at Function._fail (http://127.0.0.1:44619/root_build/gen/utils/dartdevc/pkg_kernel/expect.js:461:17)
    at Function.listEquals (http://127.0.0.1:44619/root_build/gen/utils/dartdevc/pkg_kernel/expect.js:260:25)
    at closure_type_arguments_test.main (http://127.0.0.1:44619/root_dart/out/ReleaseX64/generated_compilations/dartdevk-checked-sdk/tests_language_2_closure_type_arguments_test/closure_type_arguments_test.js:82:20)
```
[Full log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8937259771994837168/+/steps/ddc_kernel_tests/0/stdout)

**Comment by jmesserly** [comment]
It looks like this is DDC+Kernel.

This is probably the `Object` vs `dynamic` issue with respect to something that doesn't have an explicit bound (in this case, `Q`). If I recall correctly, Kernel added an API to distinguish between `<Q extends Object>`, `<Q extends dynamic>`, and `<Q>`, but I have not updated DDC+Kernel to use it yet. Prior to that, we did not have enough information to distinguish these 3 cases, so we could not implement the desired instantiate to bounds behavior.

**Comment by jmesserly** [comment]
Simplified repro:
```dart
main() {
  f<T>() => T;
  print(f());
  print((f as dynamic)());
}
```
it should print `dynamic` for both, but DDC+Kernel prints `Object` for the second one. This is because the runtime type information stores `Object` for the bound of T (which is the correct bound, but not correct for default instantiation).

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/72081
