### ISSUE TITLE
Analyzer crash while editing a file.

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/sdk#34292]
I was working in one of the files for https://github.com/redbrogdon/veggieseasons and had this pop up. I believe it was triggered by an autocomplete lookup, but don't quote me on that.

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.4129.33`
- `2.0.0-edge.be6309690fd60284a87f3258a740c7c30efb1092`
- `IC-182.4129.33, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 3008x1692  Retina`

# Exception

```
Dart analysis server, SDK version 2.0.0-edge.be6309690fd60284a87f3258a740c7c30efb1092, server version 1.20.5, FATAL error: Failed to handle request: {id: 4354, method: edit.isPostfixCompletionApplicable, params: {file: /Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart, offset: 20178, key: .return}, clientRequestTime: 1535497337541}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:47:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase&Object&ListMixin.firstWhere (dart:collection/list.dart:142:15)
#3      PostfixCompletionProcessor._findOuterExpression (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:564:28)
#4      PostfixCompletionProcessor.findObjectExpression (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:482:7)
#5      DartPostfixCompletion.isObjectContext (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:221:22)
#6      PostfixCompletionProcessor.isApplicable (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:513:23)
<asynchronous suspension>
#7      EditDomainHandler.isPostfixCompletionApplicable (package:analysis_server/src/edit/edit_domain.dart:443:33)
<asynchronous suspension>
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:364:9)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:744:45)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:740:50)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:739:5)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#52     _StreamController._add (dart:async/stream_controller.dart:639:7)
#53     _StreamController.add (dart:async/stream_controller.dart:585:5)
#54     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#55     _rootRunUnary (dart:async/zone.dart:1136:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#61     _StreamController._add (dart:async/stream_controller.dart:639:7)
#62     _StreamController.add (dart:async/stream_controller.dart:585:5)
#63     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#67     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
```

```
1535497337051 => {"id":"4347","method":"completion.getSuggestions","params":{"file":"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart","offset":20176},"clientRequestTime":153549733
1535497337078 <= {"event":"completion.results","params":{"id":"651","replacementOffset":20174,"replacementLength":1,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"BuildContext","select
1535497337079 <= {"id":"4346","result":{}}
1535497337128 <= {"id":"4347","result":{"id":"652"}}
1535497337128 <= {"event":"analysis.errors","params":{"file":"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"
1535497337183 => {"id":"4348","method":"analysis.updateContent","params":{"files":{"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart":{"type":"add","content":"// Copyright 2018 The
1535497337183 => {"id":"4349","method":"completion.getSuggestions","params":{"file":"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart","offset":20177},"clientRequestTime":153549733
1535497337247 => {"id":"4350","method":"analysis.updateContent","params":{"files":{"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart":{"type":"add","content":"// Copyright 2018 The
1535497337248 => {"id":"4351","method":"completion.getSuggestions","params":{"file":"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart","offset":20178},"clientRequestTime":153549733
1535497337322 <= {"event":"completion.results","params":{"id":"652","replacementOffset":20174,"replacementLength":2,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"BuildContext","select
1535497337324 <= {"id":"4348","result":{}}
1535497337324 <= {"id":"4350","result":{}}
1535497337358 <= {"id":"4349","result":{"id":"653"}}
1535497337358 <= {"id":"4351","result":{"id":"654"}}
1535497337358 <= {"event":"analysis.errors","params":{"file":"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"f
1535497337359 <= {"event":"completion.results","params":{"id":"653","replacementOffset":20177,"replacementLength":0,"results":[],"isLast":true}}
1535497337387 => {"id":"4352","method":"analysis.updateContent","params":{"files":{"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart":{"type":"add","content":"// Copyright 2018 The
1535497337387 => {"id":"4353","method":"completion.getSuggestions","params":{"file":"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart","offset":20179},"clientRequestTime":153549733
1535497337488 <= {"event":"completion.results","params":{"id":"654","replacementOffset":20174,"replacementLength":4,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"BuildContext","select
1535497337489 <= {"id":"4352","result":{}}
1535497337524 <= {"id":"4353","result":{"id":"655"}}
1535497337524 <= {"event":"analysis.errors","params":{"file":"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"
1535497337530 <= {"event":"completion.results","params":{"id":"655","replacementOffset":20179,"replacementLength":0,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"isBefore","selectionO
1535497337532 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1535497337541 => {"id":"4354","method":"edit.isPostfixCompletionApplicable","params":{"file":"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart","offset":20178,"key":".return"},"cli
1535497337544 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1535497337559 => {"id":"4355","method":"analysis.updateContent","params":{"files":{"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart":{"type":"add","content":"// Copyright 2018 The
1535497337559 => {"id":"4356","method":"completion.getSuggestions","params":{"file":"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart","offset":20180},"clientRequestTime":153549733
1535497337567 <= {"event":"analysis.errors","params":{"file":"/Users/redbrogdon/source/veggieseasons/lib/data/veggie_provider.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"
1535497337578 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 4354, method: edit.isPostfixCompletionApplicable, params: {file: /Users/redbrogdon/source/ve
```

**Comment by scheglov** [comment]
This was fixed in https://dart-review.googlesource.com/c/sdk/+/71620
