### ISSUE TITLE
FileSystemException in _WindowsDirectoryWatcher when running analysis server

### ISSUE THREAD

**Issue by tom0gao** [dart-lang/sdk#34294]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.0.0-edge.be6309690fd60284a87f3258a740c7c30efb1092`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Gao\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Tools\Projects\DJHY\lian_miao, C:\Tools\Projects\DJHY\lian_miao\android], excluded: [C:\Tools\Projects\DJHY\lian_miao\.idea, C:\Tools\Projects\DJHY\lian_miao\.dart_tool, C:\Tools\Projects\DJHY\lian_miao\.idea, C:\Tools\Projects\DJHY\lian_miao\.pub, C:\Tools\Projects\DJHY\lian_miao\build]}, clientRequestTime: 1535536529554}
FileSystemException: Exists failed, path = 'C:\Tools\Projects\DJHY\lian_miao\build\app\intermediates\transforms\instantRunSlicer\debug\7\com\djhy' (OS Error: 拒绝访问。
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by scheglov** [comment]
Change for `watcher`: https://github.com/dart-lang/watcher/pull/67

**Comment by scheglov** [comment]
Change for using the version of `watcher` with the fix: https://dart-review.googlesource.com/c/sdk/+/83544
