### ISSUE TITLE
automatic message from event log

### ISSUE THREAD

**Issue by marcosrma** [dart-lang/sdk#34325]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.0.0-edge.be6309690fd60284a87f3258a740c7c30efb1092`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1280x800`

# Exception

Please append the contents of:
file:///private/var/folders/kw/tp26__0n01n688zz_0t0m0cw0000gq/T/report2.txt

```
Dart analysis server, SDK version 2.0.0-edge.be6309690fd60284a87f3258a740c7c30efb1092, server version 1.20.5, FATAL error: Failed to handle request: {id: 9691, method: edit.isPostfixCompletionApplicable, params: {file: /Users/marcosalves/_Development/menu_test/lib/ui/test_page.dart, offset: 10563, key: .switch}, clientRequestTime: 1535646523515}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:47:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase

**Comment by scheglov** [comment]
This was fixed in https://dart-review.googlesource.com/c/sdk/+/71620
