### ISSUE TITLE
Android Studio prompted me to submit this issue when I ran Flutter Clean

### ISSUE THREAD

**Issue by GroovinChip** [dart-lang/sdk#34326]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\groov\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822, server version 1.20.3, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\groov\Flutter_Projects\call_manager\call_manager], excluded: [C:\Users\groov\Flutter_Projects\call_manager\call_manager\.idea, C:\Users\groov\Flutter_Projects\call_manager\call_manager\.dart_tool, C:\Users\groov\Flutter_Projects\call_manager\call_manager\.idea, C:\Users\groov\Flutter_Projects\call_manager\call_manager\.pub, C:\Users\groov\Flutter_Projects\call_manager\call_manager\build]}, clientRequestTime: 1535669907307}
FileSystemException: Exists failed, path = 'C:\Users\groov\Flutter_Projects\call_manager\call_manager\build\google_sign_in\generated\source\buildConfig\debug\io\flutter\plugins\googlesignin' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166)
#3      _HashVMBase

**Comment by vsmenon** [comment]
Looks like a dup of #34294
