### ISSUE TITLE
Test.py should not crash if an invalid URL is requested of a test server

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#34347]
Unsupported operation: Illegal character in path: <!DOCTYPE 
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1714:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2643:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2618:22)
#3      new File.fromUri (dart:io/file.dart:264:49)
#4      TestingServers._handleFileOrDirectoryRequest (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:251:22)
<asynchronous suspension>
#5      TestingServers._startHttpServer.<anonymous closure>.fileHandler (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:232:9)
#6      DispatchingServer._dispatchRequest (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:35:26)

**Comment by whesse** [comment]
Unhandled exception:
Unsupported operation: Illegal character in path: <!DOCTYPE 
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1714:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2643:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2618:22)
#3      new File.fromUri (dart:io/file.dart:264:49)
#4      TestingServers._handleFileOrDirectoryRequest (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:251:22)
<asynchronous suspension>
#5      TestingServers._startHttpServer.<anonymous closure>.fileHandler (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:232:9)
#6      DispatchingServer._dispatchRequest (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:35:26)

**Comment by whesse** [comment]
Unhandled exception:
''''
Unsupported operation: Illegal character in path: <!DOCTYPE 
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1714:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2643:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2618:22)
#3      new File.fromUri (dart:io/file.dart:264:49)
#4      TestingServers._handleFileOrDirectoryRequest (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:251:22)
<asynchronous suspension>
#5      TestingServers._startHttpServer.<anonymous closure>.fileHandler (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:232:9)
#6      DispatchingServer._dispatchRequest (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:35:26)
''''

**Comment by whesse** [comment]
Unhandled exception:
```
Unsupported operation: Illegal character in path: <!DOCTYPE 
""""
    #0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1714:11)
    #1      _Uri._toWindowsFilePath (dart:core/uri.dart:2643:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2618:22)
#3      new File.fromUri (dart:io/file.dart:264:49)
#4      TestingServers._handleFileOrDirectoryRequest (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:251:22)
<asynchronous suspension>
#5      TestingServers._startHttpServer.<anonymous closure>.fileHandler (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:232:9)
#6      DispatchingServer._dispatchRequest (file:///C:/b/s/w/ir/tools/testing/dart/http_server.dart:35:26)
```
