### ISSUE TITLE
Mixin transformer crashes when type variables on a method differ

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#34354]
```dart
class A {
  foo<T>() {}
}

class B {
  foo() {}
}

class C = A with B;
class D = B with A;
class E extends A with B {}
class F extends B with A {}
```
Any of the last four lines will cause a crash with this assert:
```
'package:kernel/transformations/mixin_full_resolution.dart': Failed assertion: line 203 pos 18: 'src.typeParameters.length == dst.typeParameters.length': is not true.
```
When run without asserts, the subsequent code indexing into the array crashes:
```
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libgrowable_array.dart:142:60)
#1      MixinFullResolution.transformClass (package:kernel/transformations/mixin_full_resolution.dart:205:31)
```

**Comment by askeksa-google** [comment]
Might be related to https://github.com/dart-lang/sdk/issues/32313 which is also a crash during mixin transformation caused by a missing type parameter.

**Comment by stefantsov** [comment]
I believe this is fixed after [CL 100580](https://dart-review.googlesource.com/c/sdk/+/100580) landed.
