### ISSUE TITLE
IsolateSpawnException in EvictingFileByteStore._requestCacheCleanUp

### ISSUE THREAD

**Issue by williammw** [dart-lang/sdk#34352]
### What I was doing

just create a hello_world from vs code and exception shown

### Versions

- Dart SDK 2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822
- Visual Studio Code 1.26.1
- Dart Code 2.18.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
D:\#lib\flutter-sdk\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.18.0
```

### Exception

Captured exception

```text
IsolateSpawnException: Unable to spawn isolate: Dart_LoadScript expects argument 'source' to be non-null.
#0      Isolate.spawn (dart:isolate-patch/dart:isolate/isolate_patch.dart:363)
<asynchronous suspension>
#1      EvictingFileByteStore._requestCacheCleanUp (package:front_end/src/byte_store/file_byte_store.dart:70)
<asynchronous suspension>
#2      new EvictingFileByteStore (package:front_end/src/byte_store/file_byte_store.dart:45)
#3      AnalysisServer._createByteStore (package:analysis_server/src/analysis_server.dart:1090)
#4      new AnalysisServer (package:analysis_server/src/analysis_server.dart:390)
#5      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#6      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#7      Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:435)
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     runZoned (dart:async/zone.dart:1501)
#11     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:475)
#12     Driver.start (package:analysis_server/src/server/driver.dart:434)
#13     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by devoncarew** [comment]
@scheglov, do you have an idea of why this is failing (`Unable to spawn isolate: Dart_LoadScript expects...`)?

**Comment by scheglov** [comment]
This does not look as an Analyzer issue.
We are just spawning an isolate.
It looks like a VM / library issue.

**Comment by scheglov** [comment]
I don't know how proxy could affect this.
Maybe?

@a-siva Is this something related to Dart VM?

**Comment by a-siva** [comment]
Dart_LoadScript should only be called in Dart 1 mode, it appears there is some issue here with an isolate being spawned in Dart 1 mode. Can this be tried on the latest version of Dart SDK.

**Comment by stereotype441** [comment]
I'm closing this issue because we believe this error was due to old Dart 1 code.  @williammw, please feel to reopen if you still see this problem with Dart 2.1.0.
