### ISSUE TITLE
Issue As Feedback

### ISSUE THREAD

**Issue by rakeshlanjewarwork** [dart-lang/sdk#34407]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\Rakesh\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 3863, method: edit.isPostfixCompletionApplicable, params: {file: E:\flutterProjects\adil2\al_adil_app\lib\Leftpage.dart, offset: 268, key: .if}, clientRequestTime: 1536385929042}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase

**Comment by bwilkerson** [comment]
Fixed in 83324a8
