### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by avishkar2k** [dart-lang/sdk#34428]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4443003`
- `2.0.0-edge.be6309690fd60284a87f3258a740c7c30efb1092`
- `AI-171.4443003, JRE 1.8.0_152-release-915-b01x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-134-generic unknown, screens 1920x1080`

# Exception

Please append the contents of:
file:///tmp/report.txt

```
Dart analysis server, SDK version 2.0.0-edge.be6309690fd60284a87f3258a740c7c30efb1092, server version 1.20.5, FATAL error: Failed to handle request: {id: 2885, method: edit.getFixes, params: {file: /home/appinventiv/simple_login_signup/lib/common/network/rest_ds.dart, offset: 829}, clientRequestTime: 1536614274116}
NoSuchMethodError: The getter 'kind' was called on null.
Receiver: null
Tried calling: kind
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:47:5)
#1      FixProcessor._addFix_createGetter (package:analysis_server/src/services/correction/fix_internal.dart:1776:40)
<asynchronous suspension>
#2      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:489:13)
<asynchronous suspension>
#3      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:88:41)
<asynchronous suspension>
#4      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:564:49)
<asynchronous suspension>
#5      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:239:32)
<asynchronous suspension>
#6      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:347:9)
#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:744:45)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/74301
