### ISSUE TITLE
Compiler error caused by infinite loop.

### ISSUE THREAD

**Issue by giorgiofran** [dart-lang/sdk#34448]
* Dart SDK Version: 2.0.0
* Windows 10.
* Chrome 
[INFO] 34.8s elapsed, 183/184 actions completed.
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read vidya_web|lib/vidya_web.ddc.js, check your console or the `.dart_tool/build/generated/vidya_web/lib/vidya_web.ddc.js.errors` log file.
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read vidya_web|lib/src/base/web/web_service.ddc.js, check your console or the `.dart_tool/build/generated/vidya_web/lib/src/base/web/web_service.ddc.js.errors` log file.
[INFO] Running build completed, took 36.2s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 963ms

[SEVERE] build_web_compilers|ddc on lib/src/base/web/web_service.dartdevc.module (cached):
Error compiling dartdevc module:vidya_web|lib/src/base/web/web_service.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=C:\Users\Giorgio\Programmi\Dart\dart-sdk.2.0.0 --dart-sdk-summary=C:\Users\Giorgio\Programmi\Dart\dart-sdk.2.0.0/lib/_internal/ddc_sdk.sum --modules=amd -o C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vidya_web/src/base/web/web_service.ddc.js --module-root=. --library-root=/lib --summary-extension=dartdevc.linked.sum --no-summarize --options=C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/meta/meta.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/collection/src/utils.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/collection/src/algorithms.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/collection/src/canonicalized_map.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/collection/src/comparators.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/collection/src/iterable_zip.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/collection/src/priority_queue.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/collection/collection.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/src/core/change_detection/change_detection.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/path/path.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/stack_trace/stack_trace.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/logging/logging.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/src/core/zone/ng_zone.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/src/core/application_tokens.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/core.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/di.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/src/core/linker/view_type.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/meta/dart2js.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/js/js.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/js/js_util.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/src/core/change_detection/change_detection.template.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/di.template.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/src/core/application_tokens.template.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/core.template.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/intl/date_symbols.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/intl/number_symbols.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/intl/number_symbols_data.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/intl/src/plural_rules.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/intl/intl.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/src/bootstrap/modules.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/angular/angular.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/typed_data/typed_buffers.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/typed_data/typed_data.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/charcode/ascii.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/convert/convert.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/crypto/crypto.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/quiver/core.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/more/char_matcher.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/fixnum/fixnum.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/bson/bson.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vidya_base/translations/translations_en.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vidya_base/translations/translations_en_US.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vidya_base/translations/translations_it.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vidya_base/translations/translations_it_IT.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vidya_base/translations/translations_pt.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vidya_base/translations/translations_pt_BR.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vy_date/vy_date.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vy_range_collection/vy_range_collection.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vy_app_util/vy_app_util.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/rational/rational.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/decimal/decimal.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vy_fixed_decimal/vy_fixed_decimal.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/mongo_dart_query/mongo_dart_query.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vy_db_mongo/vy_db_mongo.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vy_field_type/vy_field_type.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vy_mutable_values/common/internalSanitizeValueType.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vy_mutable_values/common/container_utils.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/uuid/aes.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/uuid/uuid_util.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/uuid/uuid.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vidya_base/vidya_base.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vidya_web/src/base/model/app_data.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vidya_web/vidya_web.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/charcode/html_entity.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/charcode/charcode.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/source_span/source_span.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/string_scanner/string_scanner.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/http_parser/http_parser.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/async/async.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/http/src/base_client.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/http/browser_client.dartdevc.linked.sum -s C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/http/http.dartdevc.linked.sum --url-mapping=package:vidya_web/src/base/web/web_service.dart,C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages/vidya_web/src/base/web/web_service.dart package:vidya_web/src/base/web/web_service.dart
    dart --version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64"
```
AnalysisException: Cannot compute LIBRARY_ELEMENT for C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart
Caused by Infinite loop while performing task PartiallyResolveUnitReferencesTask for C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart
  Dependency Cycle:
    Run PartiallyResolveUnitReferencesTask on C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart
    Run InferInstanceMembersInUnitTask on C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart
    Run ResolveInstanceFieldsInUnitTask on C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart
    Run InferStaticVariableTypesInUnitTask on C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart
    Run PartiallyResolveUnitReferencesTask on C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart
    Run InferInstanceMembersInUnitTask on C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart
    Run ResolveInstanceFieldsInUnitTask on C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart
    Run InferStaticVariableTypesInUnitTask on C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart
  Cyclic Path:
    CREATED_RESOLVED_UNIT10 for C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart
    CREATED_RESOLVED_UNIT10 for C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\web\web_service.dart
    CREATED_RESOLVED_UNIT10 for C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart in C:\Users\Giorgio\AppData\Local\Temp\scratch_space773c581f-b66e-11e8-881b-080027a53827\packages\vidya_web\src\base\init\init_meta_db.dart

#0      AnalysisTask._safelyPerform (package:analyzer/src/task/api/model.dart:320:11)
#1      AnalysisTask.perform (package:analyzer/src/task/api/model.dart:222:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:285:10)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110:22)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:721:14)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:689:12)
#6      ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:166:38)
#7      _compile (package:dev_compiler/src/analyzer/command.dart:185:25)
#8      compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#9      _CompilerWorker.performRequest (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#16     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:726:7)
#1      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:689:12)
#2      ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:166:38)
#3      _compile (package:dev_compiler/src/analyzer/command.dart:185:25)
#4      compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#5      _CompilerWorker.performRequest (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#6      AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#12     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

```
}

[SEVERE] build_web_compilers|ddc on lib/vidya_web.dartdevc.module (cached):
Error compiling dartdevc module:vidya_web|lib/vidya_web.ddc.js

**Comment by giorgiofran** [comment]
After Testing for a while, I think that I got what caused the infinite loop.
I have a structure of the sources made like this:
lib
+---src
|        + source1.dart
|        +source2.dart
+ global.dart

in global.dart I export the two sources
```
 export 'src/source1.dart';
 export 'src/source2.dart';
```

Then, in sourc2.dart I import the first source,
  but instead of doing a simple import like: `import 'source1.dart';`
I refer to the global.dart file: `import 'package:my_package/global.dart show Source1;`

This is because I find more readable one only import with a list of shown classes. 
At least it seems to me easier to manage in a large project.
Consider that this was working with dart 1.24.3 an dart2js.

**Comment by Markzipan** [comment]
This issue applies to the analyzer-backed DDC, which should be gone. Please re-open if it's still a problem.
