### ISSUE TITLE
Crash in BG compiler due to non-finalized type

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#34459]
From [this log](https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-linux-debug-x64-be%2F18025%2F%2B%2Frecipes%2Fsteps%2Fchecked_vm_tests%2F0%2Fstdout):
```
FAILED: none-vm-checked debug_x64 service/pause_on_unhandled_async_exceptions2_test
Expected: Pass
Actual: RuntimeError
--- Command "vm" (took 06.000816s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --no-preview-dart-2 --enable_asserts --enable_type_checks --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --async_debugger --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/.packages /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart
exit code:
255
stdout:
** Launching SERVICE_TEST_TESTEE=true out/DebugX64/dart -DDART_SERVICE_USE_AUTH=false --pause-isolates-on-unhandled-exceptions --profiler --no-preview-dart-2 --enable_asserts --enable_type_checks --optimization-counter-threshold=5 --error_on_bad_type --error_on_bad_override --async_debugger --ignore-unrecognized-flags --packages=/mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/.packages --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/pause_on_unhandled_async_exceptions2_test.dart
>testee>out> Observatory listening on http://127.0.0.1:52324/
** Signaled to run test queries on http://127.0.0.1:52324/
>testee>out> 
Loading VM...
>testee>err> ../../runtime/vm/object.cc: 18064: error: expected: other.IsFinalized()
>testee>err> Dumping native stack trace for thread ea5
>testee>err>   [0x00007ff78e59f2ef] dart::Profiler::DumpStackTrace(void*)
>testee>err>   [0x00007ff78e59f2ef] dart::Profiler::DumpStackTrace(void*)
>testee>err>   [0x00007ff78e86d982] dart::Assert::Fail(char const*, ...)
>testee>err>   [0x00007ff78e49c560] dart::AbstractType::TypeTest(dart::Object::TypeTestKind, dart::AbstractType const&, dart::Error*, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*, dart::Heap::Space) const
>testee>err>   [0x00007ff78e758670] dart::AssertAssignableInstr::ComputeType() const
>testee>err>   [0x00007ff78e758751] dart::AssertAssignableInstr::RecomputeType()
>testee>err>   [0x00007ff78e7543d6] dart::FlowGraphTypePropagator::PropagateRecursive(dart::BlockEntryInstr*)
>testee>err>   [0x00007ff78e75449c] dart::FlowGraphTypePropagator::PropagateRecursive(dart::BlockEntryInstr*)
>testee>err>   [0x00007ff78e75449c] dart::FlowGraphTypePropagator::PropagateRecursive(dart::BlockEntryInstr*)
>testee>err>   [0x00007ff78e75449c] dart::FlowGraphTypePropagator::PropagateRecursive(dart::BlockEntryInstr*)
>testee>err>   [0x00007ff78e75449c] dart::FlowGraphTypePropagator::PropagateRecursive(dart::BlockEntryInstr*)
>testee>err>   [0x00007ff78e753781] dart::FlowGraphTypePropagator::Propagate()
>testee>err>   [0x00007ff78e7536d8] dart::FlowGraphTypePropagator::Propagate(dart::FlowGraph*)
>testee>err>   [0x00007ff78e768bad] Unknown symbol
>testee>err>   [0x00007ff78e76848d] dart::CompilerPass::Run(dart::CompilerPassState*) const
>testee>err>   [0x00007ff78e7686de] dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)
>testee>err>   [0x00007ff78e7f2a82] dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
>testee>err>   [0x00007ff78e7f4115] Unknown symbol
>testee>err>   [0x00007ff78e7f55a5] dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)
>testee>err>   [0x00007ff78e7f7972] dart::BackgroundCompiler::Run()
>testee>err>   [0x00007ff78e666641] dart::ThreadPool::Worker::Loop()
>testee>err>   [0x00007ff78e66611c] dart::ThreadPool::Worker::Main(unsigned long)
>testee>err>   [0x00007ff78e540355] Unknown symbol
>testee>err> -- End of DumpStackTrace
>testee>out> 4950
** Killing script
Unexpected exception in service tests: Testee exited with -6
#0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:253:11)
#1      _rootRunUnary (dart:async/zone.dart:1132)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671)
#6      Future._completeWithValue (dart:async/future_impl.dart:486)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516)
#8      _rootRun (dart:async/zone.dart:1124)
#9      _CustomZone.run (dart:async/zone.dart:1021)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:115)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:172)
stderr:
Unhandled exception:
Testee exited with -6
#0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:253:11)
#1      _rootRunUnary (dart:async/zone.dart:1132)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671)
#6      Future._completeWithValue (dart:async/future_impl.dart:486)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516)
#8      _rootRun (dart:async/zone.dart:1124)
#9      _CustomZone.run (dart:async/zone.dart:1021)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:115)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:172)
--- Re-run this test:
python tools/test.py -m debug --checked --no-preview-dart-2 service/pause_on_unhandled_async_exceptions2_test
```

**Comment by a-siva** [comment]
Tried the test above on the latest build and it seems to work without any crashes, closing issue.
