### ISSUE TITLE
Dart2JS crash with const constructor calling another const constructor

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#34479]
DartPad: https://dartpad.dartlang.org/152966b4b39142fe233061d81e8c93ca
(switch between lines 8 and 9, 8 crashes 9 doesn't)

Seems the type parameter given to `empty` isn't forwarded to `nullable` properly.

Compiler error from 2.1.0-dev.4.0:

```
The compiler crashed: RangeError (index): Invalid value: Valid value range is empty: 0
  #0      List.[] (dart:core/runtime/libgrowable_array.dart:142:60)
  #1      TypeVariableType.subst (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/elements/types.dart:399:23)
  #2      _substTypes.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/elements/types.dart:872:30)
  #3      new List.generate (dart:core/list.dart:162:28)
  #4      _substTypes (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/elements/types.dart:870:11)
  #5      InterfaceType.subst (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/elements/types.dart:200:9)
  #6      KernelToElementMapBase._substByContext (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:506:17)
  #7      KernelEvaluationEnvironment.substByContext (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:1956:24)
  #8      GenerativeConstantConstructor.computeInstanceType (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/constants/constructors.dart:81:24)
  #9      ConstructedConstantExpression.computeInstanceType (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/constants/expressions.dart:575:10)
  #10     RedirectingGenerativeConstantConstructor.computeInstanceType (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/constants/constructors.dart:191:35)
  #11     ConstructedConstantExpression.computeInstanceType (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/constants/expressions.dart:575:10)
  #12     ConstructedConstantExpression.evaluate (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/constants/expressions.dart:586:34)
  #13     ConstructedConstantExpression.evaluate.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/constants/expressions.dart:597:40)
  #14     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
  #15     ConstructedConstantExpression.evaluate.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/constants/expressions.dart:596:12)
  #16     EvaluationEnvironmentBase.evaluateConstructor (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/constants/evaluation.dart:112:36)
  #17     ConstructedConstantExpression.evaluate (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/constants/expressions.dart:587:24)
  #18     KernelConstantEnvironment._getConstantValue.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:1929:25)
  #19     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
  #20     KernelConstantEnvironment._getConstantValue (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:1928:22)
  #21     KernelToElementMapBase.computeConstantValue (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:501:33)
  #22     KernelToElementMapBaseMixin.getConstantValue (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/kernel/element_map_mixins.dart:320:27)
  #23     KernelSsaGraphBuilder.visitConstructorInvocation (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:4620:44)
  #24     ConstructorInvocation.accept (package:kernel/ast.dart:2934:36)
  #25     KernelSsaGraphBuilder._visitPositionalArguments (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3099:16)
  #26     KernelSsaGraphBuilder._visitArgumentsForDynamicTarget (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3112:33)
  #27     KernelSsaGraphBuilder.visitMethodInvocation (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:4426:42)
  #28     MethodInvocation.accept (package:kernel/ast.dart:2773:36)
  #29     KernelSsaGraphBuilder.visitLet (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3088:26)
  #30     Let.accept (package:kernel/ast.dart:3515:36)
  #31     KernelSsaGraphBuilder.visitLet (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3092:15)
  #32     Let.accept (package:kernel/ast.dart:3515:36)
  #33     KernelSsaGraphBuilder.visitReturnStatement (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1472:23)
  #34     ReturnStatement.accept (package:kernel/ast.dart:4049:35)
  #35     KernelSsaGraphBuilder.visitBlock (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1405:17)
  #36     Block.accept (package:kernel/ast.dart:3628:35)
  #37     KernelSsaGraphBuilder.buildFunctionNode (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1028:23)
  #38     KernelSsaGraphBuilder.build.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:204:15)
  #39     CompilerDiagnosticReporter.withCurrentElement (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:750:15)
  #40     KernelSsaGraphBuilder.build (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:189:21)
  #41     KernelSsaBuilder.build.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:117:22)
  #42     CompilerTask.measure (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63:51)
  #43     KernelSsaBuilder.build (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:103:17)
  #44     SsaBuilderTask.build (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/ssa.dart:96:21)
  #45     SsaFunctionCompiler.compile (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/ssa/ssa.dart:44:29)
  #46     JavaScriptBackend.codegen (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_backend/backend.dart:697:26)
  #47     KernelCodegenWorkItem.run (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:86:21)
  #48     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:428:70)
  #49     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
  #50     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:428:32)
  #51     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
  #52     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:426:28)
  #53     CompilerDiagnosticReporter.withCurrentElement (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:750:15)
  #54     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:424:18)
  #55     CodegenEnqueuer._forEach (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:236:12)
  #56     CodegenEnqueuer.forEach (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:251:5)
  #57     Compiler.emptyQueue.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:420:16)
  #58     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
  #59     Compiler.emptyQueue (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:419:14)
  #60     Compiler.processQueue.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:441:7)
  #61     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
  #62     Compiler.processQueue (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:438:14)
  #63     Compiler.generateJavaScriptCode (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:359:5)
  #64     Compiler.compileLoadedLibraries.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:385:38)
  #65     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
  #66     Compiler.compileLoadedLibraries (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:379:16)
  #67     Compiler.runInternal (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:277:5)
  <asynchronous suspension>
  #68     Compiler.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:216:38)
  #69     new Future.sync (dart:async/future.dart:224:31)
  #70     Compiler.run.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:216:20)
  #71     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
  #72     Compiler.run (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:213:41)
  #73     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/compiler/lib/src/apiimpl.dart:148:22)
  #74     _RootZone.runUnary (dart:async/zone.dart:1379:54)
  #75     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
  #76     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
  #77     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
  #78     Future._completeWithValue (dart:async/future_impl.dart:486:5)
  #79     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
  #80     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #81     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #82     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
  #83     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by sigmundch** [comment]
/cc @johnniwinther 
This appears to be an issue of variable substitution during constant evaluation.
