### ISSUE TITLE
Strange Error: type 'Future' is not a subtype of type 'FutureOr'

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#34481]
* Dart: 2.0.0
* Linux
* Dart VM (server)

I got a strange exception as follows. It happened only once in our production system since we upgraded to Dart 2 several weeks ago. Sorry, I can not reproduce it.

```
814:8183:2018-09-17 01:00:37.857230Z:quire.notification:19
SEVERE: Failed to add notification
Cause: type 'Future' is not a subtype of type 'FutureOr'
#0      _FutureListener.handleError (dart:async/future_impl.dart:147:20)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#3      Future._completeError (dart:async/future_impl.dart:494:5)
#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#5      _Completer.completeError (dart:async/future_impl.dart:27:5)
#6      _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)
#7      access (package:access/access.dart)
#8      _addNotifsFromQue 
#9      addNotification. 
#10     _Deferrer._startTimer. (file:///Users/quire/
.pub-cache/hosted/pub.dartlang.org/rikulo_commons-3.0.2+1/lib/src/async/async_util.dart:135:46)
#11     _rootRun (dart:async/zone.dart:1120:38)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#14     _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963:23)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback. (dart:async/zone.dart:947:23)
#18     Timer._createTimer. (dart:async/runtime/libtimer_patch.dart:21:15)
#19     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#20     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by a-siva** [comment]
Issue #34482 has been fixed, closing this.
