### ISSUE TITLE
Dart Analyzer Error  | Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by eddydn** [dart-lang/sdk#34501]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\reale\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 809, method: edit.isPostfixCompletionApplicable, params: {file: E:\AndroidExamples\test_coin\lib\main.dart, offset: 808, key: !}, clientRequestTime: 1537233335730}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase

**Comment by bwilkerson** [comment]
I believe that this has been fixed on bleeding edge. Please let us know if you still see this error after updating to the next dev or stable build.

**Comment by charlenopires** [comment]
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

(please describe what you were doing when this exception occurred)

### Request

While responding to request: `analysis.setAnalysisRoots`

### Versions

- Flutter SDK 0.11.7-pre.48
- Visual Studio Code 1.28.2
- Dart Code 2.20.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
D:\Dart\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.20.0
```

### Exception

NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName

```text
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      PluginWatcher._getSdkPath (package:analysis_server/src/plugin/plugin_watcher.dart:101:63)
#2      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:53:49)
#3      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:1798:22)
#4      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:352:16)
#5      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:177:33)
#6      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1127:48)
#7      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1107:19)
#8      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1147:16)
#9      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:737:9)
#10     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:819:22)
#11     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:385:14)
#12     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:299:16)
#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:645:45)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#15     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:641:50)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1500:12)
#20     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:640:5)
#21     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#23     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#24     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#32     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#33     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#34     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#35     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#37     _rootRunUnary (dart:async/zone.dart:1132:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#42     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#43     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#44     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#45     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#46     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#47     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#48     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#55     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#56     _StreamController._add (dart:async/stream_controller.dart:639:7)
#57     _StreamController.add (dart:async/stream_controller.dart:585:5)
#58     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#59     _rootRunUnary (dart:async/zone.dart:1136:13)
#60     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#64     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#65     _StreamController._add (dart:async/stream_controller.dart:639:7)
#66     _StreamController.add (dart:async/stream_controller.dart:585:5)
#67     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#68     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#69     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#70     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#71     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#72     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[]
```
