### ISSUE TITLE
RangeError in _UnitResynthesizer.getReferenceInfo

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#34534]
Suspect it's related to: #34519 

# Version information

- `IDEA 183.2635.17`
- `2.1.0-dev.5.0`
- `WS-183.2635.17, JRE 1.8.0_152-release-1293-b10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 2560x1440, 1200x1920`

# Exception

Please append the contents of:
file:///private/var/folders/k3/rpf30xp576gd3b7wdpvvyg2r0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-dev.5.0, server version 1.20.5, error: Analysis failed: /Users/rayk/Projects/app/lib/src/services/app_service.dart context: exception_20180921_133628_649
RangeError (index): Invalid value: Not in range 0..18, inclusive: 19
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1456:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1362:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7771:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7663:5)
#6      _ParameterElementImpl

**Comment by scheglov** [comment]
I believe this is fixed with https://github.com/dart-lang/sdk/commit/e648d63bedc2a4decb3b8cbcf0f2e1c44db960b0.
