### ISSUE TITLE
Analysis server crash: Element not found in summary: dart:core;dart:core/map.dart;BuildResult

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#34544]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Editing the following code:

```dart
enum BuildResult { Unknown, Running, Pass, Fail, Flake }

class Commit {
  String hash;
  String get id => hash;
  String authorName;
  Uri authorAvatar;
}

class Project {
  final String id;
  final String name;
  final List<TaskGroup> taskGroups = new List<; // ########## I had just typed the < here
  final List<CommitResult> commitResults;
}
```

### Versions

- Flutter SDK 0.9.3-pre.14
- Visual Studio Code 1.27.2
- Dart Code 2.18.1-dev

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.18.1-dev
```

### Exception

Analysis failed: /Users/danny/Dev/flutter_dashboard/lib/src/build_results.dart context: exception_20180921_175416_684

```text
Exception: Element not found in summary: dart:core;dart:core/map.dart;BuildResult
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:308:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:345:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:35:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:111:29)
#4      _ReferenceInfo._buildType.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:996:48)
#5      InterfaceTypeImpl.typeArguments (package:analyzer/src/dart/element/type.dart:1389:26)
#6      DeclarationResolver._setGenericFunctionType (package:analyzer/src/generated/declaration_resolver.dart:551:37)
#7      DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/declaration_resolver.dart:503:7)
#8      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11481:15)
#9      FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4387:17)
#10     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:834:10)
#11     DeclarationResolver.visitFieldDeclaration (package:analyzer/src/generated/declaration_resolver.dart:207:11)
#12     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4382:49)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#14     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#15     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:690:10)
#16     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:91:13)
#17     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:571:13)
#18     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:90:5)
#19     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#21     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#22     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#23     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#24     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:51:12)
#25     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#26     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#27     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#28     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:13)
#29     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#30     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#31     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#32     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#33     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#34     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#35     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1025:23)
<asynchronous suspension>
#36     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#37     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#38     new AnalysisServer (package:analysis_server/src/analysis_server.dart:389:29)
#39     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:78:26)
#40     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:487:21)
#42     _rootRun (dart:async/zone.dart:1124:13)
#43     _CustomZone.run (dart:async/zone.dart:1021:19)
#44     _runZoned (dart:async/zone.dart:1516:10)
#45     runZoned (dart:async/zone.dart:1463:12)
#46     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:531:12)
#47     Driver.start (package:analysis_server/src/server/driver.dart:485:7)
#48     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#49     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#50     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#51     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/danny/Dev/flutter_dashboard",
        "explicitFileCount": 5,
        "implicitFileCount": 847,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment]
(@bwilkerson not sure if there are any other particular tags I should add to issues like this - for ex analyzer-untriaged?)

**Comment by DanTup** [comment]
(also, I can send you/@scheglov the `exception_20180921_175416_684` file if it's useful).

**Comment by bwilkerson** [comment]
> not sure if there are any other particular tags I should add to issues like this - for ex analyzer-untriaged?

Nope, the "area-analyzer" tag is sufficient, though you're welcome to add "type-bug" if you want. (The "analyzer-untriaged" is a short term tag we used to help triage items that needed to be in the 2.1 milestone.)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Yes, this looks very much like the bug I fixed a couple of days ago - typed field with initializer.
https://github.com/dart-lang/sdk/commit/765a78d44e7a9e5fd09b10a3b0c60c6e2e4bba96
