### ISSUE TITLE
analyzer crash on `mixin` syntax: NoSuchMethodError: The getter 'accessors' was called on null.

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#34571]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Added `prefer_mixin` lint to `analysis_options.yaml` and restarted VSCode.

### Versions

- Flutter SDK 0.4.3-pre.1162
- Visual Studio Code 1.27.1
- Dart Code 2.18.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/home/yjbanov/code/flutter/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.18.0
```

### Exception

Exception while using a OverriddenFields to visit a FieldDeclarationImpl in MixinDeclarationImpl in CompilationUnitImpl

```text
NoSuchMethodError: The getter 'accessors' was called on null.
Receiver: null
Tried calling: accessors
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _Visitor._getOverriddenMember.containsOverriddenMember (package:linter/src/rules/overridden_fields.dart:134:11)
#2      Iterable.firstWhere (dart:core/iterable.dart:569:15)
#3      _Visitor._getOverriddenMember (package:linter/src/rules/overridden_fields.dart:140:20)
#4      _Visitor.visitFieldDeclaration.<anonymous closure> (package:linter/src/rules/overridden_fields.dart:112:11)
#5      _NodeListImpl&Object&ListMixin.forEach (org-dartlang-sdk:///sdk/lib/collection/list.dart:68:13)
#6      _Visitor.visitFieldDeclaration (package:linter/src/rules/overridden_fields.dart:110:27)
#7      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4382:49)
#8      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:671:14)
#9      LinterVisitor.visitFieldDeclaration (package:analyzer/src/lint/linter_visitor.dart:239:5)
#10     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4382:49)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#12     MixinDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7919:13)
#13     RecursiveAstVisitor.visitMixinDeclaration (package:analyzer/dart/ast/visitor.dart:1026:10)
#14     LinterVisitor.visitMixinDeclaration (package:analyzer/src/lint/linter_visitor.dart:432:11)
#15     MixinDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7910:49)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#17     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#18     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#19     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:120:11)
#20     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#21     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:269:10)
#22     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:139:13)
#23     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#24     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:138:17)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#26     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:137:37)
#27     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#28     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#29     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#30     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#31     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#32     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#33     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:908:19)
<asynchronous suspension>
#34     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#35     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#36     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#37     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#38     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#39     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _runZoned (dart:async/zone.dart:1516:10)
#43     runZoned (dart:async/zone.dart:1463:12)
#44     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#45     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#46     main (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#47     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#48     main (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#49     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#50     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/home/yjbanov/code/flutter/flutter/packages/flutter",
        "explicitFileCount": 895,
        "implicitFileCount": -37,
        "workItemQueueLength": 503,
        "cacheEntryExceptions": []
    }
]
```

@stereotype441 @JekCharlsonYu @leafpetersen

**Comment by bwilkerson** [comment]
https://github.com/dart-lang/linter/pull/1182

Still need to get linter published and pulled into the SDK.

**Comment by bwilkerson** [comment]
The linter changes have landed.
