### ISSUE TITLE
analyzer crash: type 'MixinDeclarationImpl' is not a subtype of type 'ClassDeclaration'

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#34570]
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Added `prefer_mixin` lint to `analysis_options.yaml` and restarted VSCode.

### Versions

- Flutter SDK 0.4.3-pre.1162
- Visual Studio Code 1.27.1
- Dart Code 2.18.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/home/yjbanov/code/flutter/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.18.0
```

### Exception

Exception while using a AvoidRenamingMethodParameters to visit a MethodDeclarationImpl in MixinDeclarationImpl in CompilationUnitImpl

```text
type 'MixinDeclarationImpl' is not a subtype of type 'ClassDeclaration'
#0      _Visitor.visitMethodDeclaration (package:linter/src/rules/avoid_renaming_method_parameters.dart:69:22)
#1      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7686:49)
#2      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:671:14)
#3      LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:419:5)
#4      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7686:49)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#6      MixinDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7919:13)
#7      RecursiveAstVisitor.visitMixinDeclaration (package:analyzer/dart/ast/visitor.dart:1026:10)
#8      LinterVisitor.visitMixinDeclaration (package:analyzer/src/lint/linter_visitor.dart:432:11)
#9      MixinDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7910:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#11     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#12     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#13     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:120:11)
#14     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#15     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:269:10)
#16     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:139:13)
#17     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#18     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:138:17)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#20     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:137:37)
#21     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
#22     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#23     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:77:65)
#24     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
#25     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#31     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#38     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#39     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/home/yjbanov/code/flutter/flutter/packages/flutter",
        "explicitFileCount": 895,
        "implicitFileCount": -37,
        "workItemQueueLength": 503,
        "cacheEntryExceptions": []
    }
]
```

@stereotype441 @JekCharlsonYu @leafpetersen

**Comment by scheglov** [comment]
The linter has been updated in SDK.
So, the fix should be in.
https://dart-review.googlesource.com/c/sdk/+/76565
