### ISSUE TITLE
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType' in TypeProviderForLink._buildInterfaceType

### ISSUE THREAD

**Issue by aman-malhotra-1999** [dart-lang/sdk#34576]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\AMANMA~1\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a, server version 1.20.5, error: Analysis failed: D:\FlutterApps\music_player\lib\drawer.dart
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5013:5)
#1      TypeProviderForLink.objectType (package:analyzer/src/summary/link.dart:4982:23)
#2      ClassElementForLink_Class._computeInterfaceType (package:analyzer/src/summary/link.dart:853:67)
#3      ClassElementForLink_Class.supertype (package:analyzer/src/summary/link.dart:762:27)
#4      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:306:33)
#5      InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:83:9)
#6      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1500:10)
#7      LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3517:12)
#8      LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3189:15)
#9      LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3111:7)
#10     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:149:13)
#11     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:115:24)
#12     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:168:18)

**Comment by scheglov** [comment]
It looks to me like an instance of missing / incomplete Dart SDK to me, probably during `flutter upgrade`. There is nothing we could do on the linking level, we need some more radical solution, e.g. pre-loading the whole Dart SDK once on Analysis Server start.

**Comment by stereotype441** [comment]
Closing because we believe this probably happened during an upgrade of the SDK, and there's no reasonable way for the analyzer to be able to analyze effectively if that's happening.  @aman-malhotra-1999, if you're still seeing a problem, please reopen the bug and let us know what seems to trigger it.
