### ISSUE TITLE
asserts don't print failed condition if sources are not present in kernel file

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#34586]
When dart vm runs against kernel file without source code embedded in it, failed asserts report `null` instead of original dart condition:

```
'\'file:///$FH/flutter/packages/flutter/test/foundation/error_reporting_test.dart\': Failed assertion: line 12 pos 12: \'null\'',
```

The penalty of having source code present just to have asserts reporting correct condition seems to be too high: for flutter tests (`package/flutter`) average kernel file with the source is 16M vs 6M without source. Test execution time when running against kernel files without source code drops by ~25% (from 2m50s to 2m07s).

It seems reasonable for `assert` in Kernel AST to capture source text condition in the kernel file itself instead of capturing just token positions.

@rmacnak-google

**Comment by aam** [comment]
Thanks Jens.
Can you clarify please what other kind of error reporting source is used for? "debugging" - do you mean observatory? Other aspects of observatory will still be usable.
Also how flutter uses sources to properly invalidate changed files?

**Comment by jensjoha** [comment]
- Basically every call to `H.ReportError` (e.g. for constant evaluation errors) (with a token position) uses the source to add a code-snippet to the error report.

- Observatory, sure - but more generally, whatever uses the service protocol to get source. But also internally, if calling Script::GetTokenLocation with a token_len --- and Script::TokenRangeAtLine seems to use the source (which again is used for setting breakpoints in the debugger).

- Flutter uses source to properly invalidate changed files when initializing from a dill. The frontend_server (in package:vm) loads the source code in the dill it's asked to initialize from, reads every file and checks that the content is still the same. If it's not the file is invalidated.

I'm not saying that we cannot change these things - we probably can, and maybe even should (e.g. for invalidating I'd like to try to include a timestamp as well and invalidate based on that so we avoid reading all files when initializing from dill in the frontend_server in a hope that that's faster).

We're somewhat getting of topic here though - I still don't think we should include the assert condition text in asserts. I am all for getting less reliant on the source and maybe eventually find a way to let the VM (et al) know about the source without directly including it in the dill file.

As for the speedup of the flutter tests a good first step might be figuring out what exactly is 43 seconds faster when you don't include the source. Is it writing the dill? Reading the dill? Loading in source in the VM? Something else? If we can pin that down, can we optimize it?

**Comment by jensjoha** [comment]
I just tried to reproduce your findings, but couldn't:

```
With source:
$ flutter test --local-engine=host_debug
02:18 +3115 ~25: All tests passed!
$ flutter test --local-engine=host_debug
02:18 +3115 ~25: All tests passed!
$ flutter test --local-engine=host_debug
02:19 +3115 ~25: All tests passed!

Without source:
$ flutter test --local-engine=host_debug
02:15 +3106 ~25 -9: Some tests failed.
$ flutter test --local-engine=host_debug
02:13 +3106 ~25 -9: Some tests failed.
$ flutter test --local-engine=host_debug
02:12 +3106 ~25 -9: Some tests failed.
```

So slightly faster without the source, but only in the 3-7 second (2-5%) range.

If you throw https://github.com/flutter/flutter/pull/22407 into the mix you get this instead:
```
With source:
$ flutter test --local-engine=host_debug
01:18 +3115 ~25: All tests passed!
$ flutter test --local-engine=host_debug
01:17 +3115 ~25: All tests passed!
$ flutter test --local-engine=host_debug
01:18 +3115 ~25: All tests passed!

Without source:
$ flutter test --local-engine=host_debug
01:14 +3106 ~25 -9: Some tests failed.
$ flutter test --local-engine=host_debug
01:17 +3106 ~25 -9: Some tests failed.
$ flutter test --local-engine=host_debug
01:17 +3106 ~25 -9: Some tests failed.
```
Here, removing the source _might_ be faster, but I don't think it's statistically significant.

What I think might have happened is that you're comparing `flutter test` with `flutter test --local-engine=host_debug` which, at least on my machine, is quite different:
```
With source:
$ flutter test
02:39 +3101 ~25: All tests passed! 
$ flutter test
02:28 +3101 ~25: All tests passed!
$ flutter test
02:28 +3101 ~25: All tests passed!
```
which compared to the numbers from `flutter test --local-engine=host_debug` without source (2:15, 2:13, 2:12) is at least closer to what you saw (though there's still some way up to a 25%/43s difference).

**Comment by DanTup** [comment]
> Can you clarify please what other kind of error reporting source is used for? "debugging" - do you mean observatory? Other aspects of observatory will still be usable.

FWIW, this has come up a few times in Dart Code. Now that sources aren't included, when the user ends up breaking inside SDK source they see this:

![screen shot 2018-12-03 at 8 40 49 am](https://user-images.githubusercontent.com/1078012/49362630-28571f80-f6d7-11e8-8c04-c7c6b729adeb.png)

This mostly happens when an exception occurs inside `dart:` sources because VS Code jumps to the top stack frame (this will change in a future update, though the user can still always navigate up the stack and see this message).

It's also confusing because users can invoke Go-to-definition on framework source and see the source code in the editor, then when they debug and try to step into it it we say there's no source.

**Comment by jensjoha** [comment]
In regards to the source now missing I created https://github.com/dart-lang/sdk/issues/34832 (basically requesting to put it back in or creating some mechanism for the VM to provide it by other means).

**Comment by rajeshzmoke** [comment]
App crashing in release

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: Offset argument contained a NaN value.
flutter: 'dart:ui/painting.dart': Failed assertion: line 38: '<optimized out>'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _offsetIsValid (dart:ui/painting.dart:38:10)
flutter: #3      Path.contains (dart:ui/painting.dart:2090:12)
flutter: #4      ClipPathLayer.find (package:flutter/src/rendering/layer.dart:1137:19)
flutter: #5      ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #6      OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #7      TransformLayer.find (package:flutter/src/rendering/layer.dart:1218:18)
flutter: #8      ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #9      ClipPathLayer.find (package:flutter/src/rendering/layer.dart:1139:18)
flutter: #10     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #11     PhysicalModelLayer.find (package:flutter/src/rendering/layer.dart:1515:18)
flutter: #12     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #13     OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #14     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #15     OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #16     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #17     PhysicalModelLayer.find (package:flutter/src/rendering/layer.dart:1515:18)
flutter: #18     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #19     OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #20     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #21     OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #22     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #23     OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #24     TransformLayer.find (package:flutter/src/rendering/layer.dart:1218:18)
flutter: #25     RenderView._updateSystemChrome (package:flutter/src/rendering/view.dart:218:58)
flutter: #26     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:201:9)
flutter: #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:350:16)
flutter: #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
flutter: #36     _invoke (dart:ui/hooks.dart:219:10)
flutter: #37     _drawFrame (dart:ui/hooks.dart:178:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by nafis042** [comment]
@rajeshzmoke, I am getting the same error. Do you able to solve the issue?

**Comment by Pebsie** [comment]
No update since June 2019? That's really weak. This seems to randomly occur and is a fatal platform flaw.

**Comment by nebis-software** [comment]
Happening also here today , using Flutter (Channel stable, 3.24.5).
Any fix and/or workaround? This "optmized out" makes debugging very very hard...
Thanks
