### ISSUE TITLE
Inconsistency between unlinked API signature and actual unlinked summary

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#34619]
eb9687189de61c7a50bb1ad76dd10389ed428663 added switched to a new implementation of computing unlinked API signatures, separated from computing actual unlinked summaries. Unfortunately it turned out that they happen to follow different rules about when to store field and top-level variable initializers. The new API signature computer ignores initializers of typed variables. The AST summarizer stores initializers for them.

  This leads to exceptions like the one below.
  I see also a lot like this from internal users.

  I see two possible ways to fix this:

1. Revert the change that computes unlinked API signatures, and get them from unlinked summaries.

2. Fix AST summarizer. I'd prefer this.

  WDYT? @bwilkerson @stereotype441 

```
Exception: Element not found in summary: dart:core;dart:core/int.dart;List

#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:311:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:345:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:35:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:111:29)
#4      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:992:24)
#5      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:938:15)
#6      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:963:15)
#7      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1376:28)
#8      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:462:30)
#9      ExecutableElementImpl.returnType (package:analyzer/src/dart/element/element.dart:4003:64)
#10     DeclarationResolver.visitMethodDeclaration (package:analyzer/src/generated/declaration_resolver.dart:364:54)
#11     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7686:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#13     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#14     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:690:10)
#15     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:89:13)
#16     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:543:13)
#17     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:88:5)
```

**Comment by scheglov** [comment]
Fix for AST analyzer.
https://dart-review.googlesource.com/c/sdk/+/77260

**Comment by stereotype441** [comment]
sgtm.  I made a minor comment on the CL.
