### ISSUE TITLE
isSubtypeOf called with null 

### ISSUE THREAD

**Issue by jaaaxsonmh** [dart-lang/sdk#34625]
[report.txt](https://github.com/dart-lang/sdk/files/2432648/report.txt)

Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 8294, method: edit.isPostfixCompletionApplicable, params: {file: D:\Projects\trees_company\lib\main.dart, offset: 1099, key: !}, clientRequestTime: 1538370522119}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase&Object&ListMixin.firstWhere (dart:collection/list.dart:142:15)
#3      PostfixCompletionProcessor._findOuterExpression (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:564:28)
#4      PostfixCompletionProcessor.findBoolExpression (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:473:7)
#5      DartPostfixCompletion.isBoolContext (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:209:22)
#6      PostfixCompletionProcessor.isApplicable (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:513:23)
<asynchronous suspension>
#7      EditDomainHandler.isPostfixCompletionApplicable (package:analysis_server/src/edit/edit_domain.dart:443:33)
<asynchronous suspension>
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:364:9)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:744:45)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:740:50)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:739:5)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#52     _StreamController._add (dart:async/stream_controller.dart:639:7)
#53     _StreamController.add (dart:async/stream_controller.dart:585:5)
#54     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#55     _rootRunUnary (dart:async/zone.dart:1136:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#61     _StreamController._add (dart:async/stream_controller.dart:639:7)
#62     _StreamController.add (dart:async/stream_controller.dart:585:5)
#63     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#67     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

```
1538370521840 <= {"event":"analysis.implemented","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","classes":[],"members":[]}}
1538370521918 => {"id":"8290","method":"analysis.updateContent","params":{"files":{"D:\\Projects\\trees_company\\lib\\main.dart":{"type":"add","content":"import 'package:flutter/material.dart';\nimpor
1538370521918 => {"id":"8291","method":"completion.getSuggestions","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","offset":1099},"clientRequestTime":1538370521918}
1538370521919 <= {"id":"8290","result":{}}
1538370521919 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1538370521939 <= {"id":"8291","result":{"id":"1440"}}
1538370521939 <= {"event":"analysis.errors","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"D:\\Projects\\tree
1538370522049 <= {"event":"completion.results","params":{"id":"1440","replacementOffset":1092,"replacementLength":7,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"DecorationPosition","
1538370522049 <= {"event":"analysis.highlights","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":39},{"type":"BUILT_IN","offset":0,"len
1538370522050 <= {"event":"analysis.navigation","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","regions":[{"offset":7,"length":31,"targets":[0]},{"offset":47,"length":42,"targets":[1]}
1538370522050 <= {"event":"analysis.closingLabels","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","labels":[{"offset":1126,"length":108,"label":"MaterialApp"}]}}
1538370522050 <= {"event":"analysis.outline","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","location":
1538370522050 <= {"event":"analysis.overrides","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","overrides":[]}}
1538370522066 <= {"event":"analysis.errors","params":{"file":"D:\\Projects\\trees_company\\test\\widget_test.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"D:\\Projects\\trees_co
1538370522067 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1538370522067 <= {"event":"analysis.implemented","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","classes":[],"members":[]}}
1538370522099 => {"id":"8292","method":"analysis.updateContent","params":{"files":{"D:\\Projects\\trees_company\\lib\\main.dart":{"type":"add","content":"import 'package:flutter/material.dart';\nimpor
1538370522099 => {"id":"8293","method":"completion.getSuggestions","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","offset":1100},"clientRequestTime":1538370522099}
1538370522099 <= {"id":"8292","result":{}}
1538370522100 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1538370522116 <= {"id":"8293","result":{"id":"1441"}}
1538370522116 <= {"event":"analysis.errors","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"D:\\Projects\\tree
1538370522117 <= {"event":"completion.results","params":{"id":"1441","replacementOffset":1100,"replacementLength":0,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"AR_KEY","selectionOff
1538370522118 <= {"event":"analysis.highlights","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":39},{"type":"BUILT_IN","offset":0,"len
1538370522118 <= {"event":"analysis.navigation","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","regions":[{"offset":7,"length":31,"targets":[0]},{"offset":47,"length":42,"targets":[1]}
1538370522118 <= {"event":"analysis.closingLabels","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","labels":[{"offset":1127,"length":108,"label":"MaterialApp"}]}}
1538370522119 => {"id":"8294","method":"edit.isPostfixCompletionApplicable","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","offset":1099,"key":"!"},"clientRequestTime":1538370522119}
1538370522119 <= {"event":"analysis.outline","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","location":
1538370522119 <= {"event":"analysis.overrides","params":{"file":"D:\\Projects\\trees_company\\lib\\main.dart","overrides":[]}}
1538370522128 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 8294, method: edit.isPostfixCompletionApplicable, params: {file: D:\\Projects\\trees_company
```

```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 8294, method: edit.isPostfixCompletionApplicable, params: {file: D:\Projects\trees_company\lib\main.dart, offset: 1099, key: !}, clientRequestTime: 1538370522119}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase

**Comment by bwilkerson** [comment]
I believe that this has been fixed in bleeding edge. Please let us know if you continue to see this after updating to the next dev or stable release.
