### ISSUE TITLE
After move a package for another package

### ISSUE THREAD

**Issue by lamkrodrigues** [dart-lang/sdk#34629]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\lamkr\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a, server version 1.20.5, error: Analysis failed: C:\projects\clipe\gerfacmob\lib\core\modulos\ModulosState.dart
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1088:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2945:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:469:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1045:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1764:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8251:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:522:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:21:37)
#9      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:428:46)
#10     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:427:26)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/34610
