### ISSUE TITLE
An error that occurred when i am developing flutter app

### ISSUE THREAD

**Issue by dansuse** [dart-lang/sdk#34620]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\daniel\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a, server version 1.20.5, error: Exception while using a PreferIterableWhereType to visit a MethodInvocationImpl in MethodInvocationImpl in ExpressionFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'bestType' was called on null.
Receiver: null
Tried calling: bestType
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      _Visitor.visitMethodInvocation (package:linter/src/rules/prefer_iterable_whereType.dart:52:25)
#2      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7753:49)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:659:14)
#4      LinterVisitor.visitMethodInvocation (package:analyzer/src/lint/linter_visitor.dart:425:5)
#5      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7753:49)
#6      MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7757:14)
#7      RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1020:10)
#8      LinterVisitor.visitMethodInvocation (package:analyzer/src/lint/linter_visitor.dart:426:11)
#9      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7753:49)
#10     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4054:18)

**Comment by bwilkerson** [comment]
Thanks for the report! This has been fixed in bleeding edge and the fix will be included in the next dev or stable build.
