### ISSUE TITLE
After move a package to another package

### ISSUE THREAD

**Issue by lamkrodrigues** [dart-lang/sdk#34630]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Contents of file://C:\Users\lamkr\AppData\Local\Temp\report1.txt:
```
Dart analysis server, SDK version 2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a, server version 1.20.5, error: Failed to send analysis.implemented notification.
NoSuchMethodError: The getter 'subtypedNames' was called on null.
Receiver: null
Tried calling: subtypedNames
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      FileState.subtypedNames (package:analyzer/src/dart/analysis/file_state.dart:270:51)
#2      Search.subtypes (package:analyzer/src/dart/analysis/search.dart:387:16)
<asynchronous suspension>
#3      SearchEngineImpl.membersOfSubtypes.addMembers (package:analysis_server/src/services/search/search_engine_internal.dart:40:33)
<asynchronous suspension>
#4      SearchEngineImpl.membersOfSubtypes (package:analysis_server/src/services/search/search_engine_internal.dart:51:21)
<asynchronous suspension>
#5      ImplementedComputer.compute (package:analysis_server/src/domains/analysis/implemented_dart.dart:34:43)
<asynchronous suspension>
#6      scheduleImplementedNotification (package:analysis_server/src/operation/operation_analysis.dart:36:24)
<asynchronous suspension>
#7      AnalysisServer._scheduleAnalysisImplementedNotification (package:analysis_server/src/analysis_server.dart:1157:7)
<asynchronous suspension>
#8      AnalysisServer.sendStatusNotificationNew (package:analysis_server/src/analysis_server.dart:893:7)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#16     _rootRun (dart:async/zone.dart:1120:38)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#27     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
1538392463898 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\auditor\\questao\\test_QuestaoView_abrirTecladoFocoObs.dart","errors":[]}}
1538392463908 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\auditor\\questao\\test_QuestaoView_enterObsNullDaErro.dart","errors":[]}}
1538392463908 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\auditor\\questionario\\test_ListaQuestoesView.dart","errors":[]}}
1538392463918 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\autorizacao\\test_AutorizacaoApi.dart","errors":[]}}
1538392463928 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\autorizacao\\test_LoginView.dart","errors":[]}}
1538392463928 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\log\\test_Log.dart","errors":[]}}
1538392463939 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\permissoes\\test_Permissoes.dart","errors":[]}}
1538392463959 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\qrcode\\test_QrCode.dart","errors":[]}}
1538392463959 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\questionarios\\test_QuestionarioApi.dart","errors":[]}}
1538392463979 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\questionarios\\test_QuestionarioRepository.dart","errors":[]}}
1538392463989 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\questionarios\\test_QuestionarioView.dart","errors":[]}}
1538392463997 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\test_ServicoEnvio.dart","errors":[]}}
1538392463999 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\test\\widget_test.dart","errors":[]}}
1538392464007 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1538392471369 => {"id":"6","method":"analysis.setPriorityFiles","params":{"files":["C:\\projects\\clipe\\gerfacmob\\lib\\login\\LoginState.dart"]},"clientRequestTime":1538392471368}
1538392471369 => {"id":"7","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["C:\\projects\\clipe\\gerfacmob\\lib\\login\\LoginState.dart"],"CLOSING_LABELS":["C:\\projects\\
1538392471453 <= {"id":"6"}
1538392471898 <= {"id":"7"}
1538392471898 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1538392472966 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\clipe\\gerfacmob\\lib\\login\\LoginState.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":"C:\
1538392472970 <= {"event":"analysis.highlights","params":{"file":"C:\\projects\\clipe\\gerfacmob\\lib\\login\\LoginState.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN"
1538392473116 <= {"event":"analysis.navigation","params":{"file":"C:\\projects\\clipe\\gerfacmob\\lib\\login\\LoginState.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":31,"length":3
1538392473152 <= {"event":"analysis.closingLabels","params":{"file":"C:\\projects\\clipe\\gerfacmob\\lib\\login\\LoginState.dart","labels":[{"offset":7638,"length":184,"label":"MaterialPageRoute"},{"o
1538392473263 <= {"event":"analysis.outline","params":{"file":"C:\\projects\\clipe\\gerfacmob\\lib\\login\\LoginState.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<un
1538392473384 => {"id":"8","method":"edit.getAssists","params":{"file":"C:\\projects\\clipe\\gerfacmob\\lib\\login\\LoginState.dart","offset":7995,"length":0},"clientRequestTime":1538392473384}
1538392473587 <= {"event":"analysis.overrides","params":{"file":"C:\\projects\\clipe\\gerfacmob\\lib\\login\\LoginState.dart","overrides":[{"offset":2271,"length":5,"superclassMember":{"element":{"kin
1538392473592 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1538392474891 <= {"id":"8","result":{"assists":[{"message":"Remove type annotation","edits":[{"file":"C:\\projects\\clipe\\gerfacmob\\lib\\login\\LoginState.dart","fileStamp":0,"edits":[{"offset":7995
1538392482283 => {"id":"9","method":"edit.getFixes","params":{"file":"C:\\projects\\clipe\\gerfacmob\\lib\\login\\LoginState.dart","offset":7995},"clientRequestTime":1538392482283}
1538392485771 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to send analysis.implemented notification.","stackTrace":"NoSuchMethodError: The getter 'subtypedNames' was called 
```

```
Dart analysis server, SDK version 2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a, server version 1.20.5, error: Failed to send analysis.implemented notification.
NoSuchMethodError: The getter 'subtypedNames' was called on null.
Receiver: null
Tried calling: subtypedNames
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      FileState.subtypedNames (package:analyzer/src/dart/analysis/file_state.dart:270:51)
#2      Search.subtypes (package:analyzer/src/dart/analysis/search.dart:387:16)
<asynchronous suspension>
#3      SearchEngineImpl.membersOfSubtypes.addMembers (package:analysis_server/src/services/search/search_engine_internal.dart:40:33)
<asynchronous suspension>
#4      SearchEngineImpl.membersOfSubtypes (package:analysis_server/src/services/search/search_engine_internal.dart:51:21)
<asynchronous suspension>
#5      ImplementedComputer.compute (package:analysis_server/src/domains/analysis/implemented_dart.dart:34:43)
<asynchronous suspension>
#6      scheduleImplementedNotification (package:analysis_server/src/operation/operation_analysis.dart:36:24)
<asynchronous suspension>
#7      AnalysisServer._scheduleAnalysisImplementedNotification (package:analysis_server/src/analysis_server.dart:1157:7)
<asynchronous suspension>
#8      AnalysisServer.sendStatusNotificationNew (package:analysis_server/src/analysis_server.dart:893:7)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)

**Comment by bwilkerson** [comment]
@scheglov
