### ISSUE TITLE
"Internal problem: Unhandled DartType in push"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#34645]
I started the analyzer while I was in the middle of dealing with a large number of conflicts, and it crashed:

```
Crash when compiling package:flutter_tools/src/base/io.dart,
at character offset null:
packages/flutter_tools/lib/src/base/io.dart:1: Internal problem: Unhandled DartType in push.
#0      internalProblem (package:front_end/src/fasta/problems.dart:32:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:45:10)
#2      BodyBuilder.push (package:front_end/src/fasta/kernel/body_builder.dart:273:7)
#3      BodyBuilder.handleType (package:front_end/src/fasta/kernel/body_builder.dart:2297:9)
#4      PrefixedType.parseType (package:front_end/src/fasta/parser/type_info_impl.dart:148:14)
#5      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2220:28)
#6      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2899:15)
#7      Parser.parseClassOrMixinMember (package:front_end/src/fasta/parser/parser.dart:2710:12)
#8      DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:846:22)
#9      DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:653:5)
#10     DietListener.endFields (package:front_end/src/fasta/source/diet_listener.dart:281:5)
#11     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2240:16)
#12     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2899:15)
#13     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2689:15)
#14     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1708:13)
#15     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1668:14)
#16     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:563:14)
#17     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:455:14)
#18     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:334:15)
#19     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:253:14)
<asynchronous suspension>
#20     Loader.buildBodies (package:front_end/src/fasta/loader.dart:181:15)
<asynchronous suspension>
#21     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:298:24)
<asynchronous suspension>
#22     withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
<asynchronous suspension>
#23     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:295:12)
<asynchronous suspension>
#24     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:150:42)
<asynchronous suspension>
#25     withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
<asynchronous suspension>
#26     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:57:10)
<asynchronous suspension>
#27     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:42:18)
<asynchronous suspension>
#28     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:130:20)
<asynchronous suspension>
#29     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#37     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:128:10)
#38     generateKernel (package:front_end/src/kernel_generator_impl.dart:41:32)
<asynchronous suspension>
#39     kernelForComponent (package:front_end/src/api_prototype/kernel_generator.dart:83:17)
<asynchronous suspension>
#40     SingleShotCompilerWrapper.compileInternal (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/vm/bin/kernel_service.dart:186:11)
<asynchronous suspension>
#41     Compiler.compile.<anonymous closure> (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/vm/bin/kernel_service.dart:134:39)
#42     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#43     _rootRun (dart:async/zone.dart:1120:38)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#47     _rootRun (dart:async/zone.dart:1124:13)
#48     _CustomZone.run (dart:async/zone.dart:1021:19)
#49     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#50     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#51     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#52     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#53     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

I don't have a good way to give you the actual state of my branch since I'm literally mid-merge, but I guess try adding a bunch of merge markers everywhere...

**Comment by kmillikin** [comment]
Hmm, this will be hard to reproduce exactly.  But looking at the code there does seem to be a problem.  https://github.com/dart-lang/sdk/commit/00ceb8e3592f125b5627df4341e95dedbb4c05f6 made it so the body builder's stack didn't contain Dart types, but https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/kernel/body_builder.dart#L2335 seems like it needs to be updated.  @peter-ahe-google can you take a look?

**Comment by peter-ahe-google** [comment]
Sorry about that. I'll get right on it.

**Comment by peter-ahe-google** [comment]
Repro:

```
class Dupe {}

class Dupe {}

class C {
  Dupe.a b;
}
```

**Comment by peter-ahe-google** [comment]
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/77802
