### ISSUE TITLE
Re-enable evaluating an expression @ a breakpoint

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#34646]
_From @pq on October 1, 2018 23:16_

When visiting apptree, this one came up.  Easy to repro.

1. Set a breakpoint.
2. When paused, evaluate an expression.
3. Exception is thrown.

To get back to a happy state we need to restart the analysis server.

Analyzer Feedback from IntelliJ

# Version information

- `IDEA 183.2940.10`
- `2.1.0-edge.4cf2d3990bac1f1df2f524899e1560a3683f3133`
- `IU-183.2940.10, JRE 1.8.0_151-b12x64 Oracle Corporation, OS Mac OS X(x86_64) v10.13.6, screens 1680x1050  Retina`

# Exception

```
Dart analysis server, SDK version 2.1.0-edge.4cf2d3990bac1f1df2f524899e1560a3683f3133, server version 1.20.5, FATAL error: Failed to handle request: {id: 2622, method: execution.getSuggestions, params: {code: con, offset: 3, contextFile: /Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart, contextOffset: 2154, variables: [], expressions: []}, clientRequestTime: 1538435427635}
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:156:7)
#1      AnalysisSessionImpl.getResolvedAst (package:analyzer/src/dart/analysis/session.dart:121:5)
#2      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:58:42)
<asynchronous suspension>
#3      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:68:41)
<asynchronous suspension>
#4      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:47:18)
#5      RuntimeCompletionComputer.compute (package:analysis_server/src/domains/execution/completion.dart:59:25)
<asynchronous suspension>
#6      ExecutionDomainHandler.getSuggestions (package:analysis_server/src/domain_execution.dart:79:63)
<asynchronous suspension>
#7      ExecutionDomainHandler.handleRequest (package:analysis_server/src/domain_execution.dart:97:9)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:750:45)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:746:50)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1500:12)
#15     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:745:5)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#18     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#27     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#28     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#29     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#30     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#31     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#40     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#41     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#42     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#43     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#45     _rootRunUnary (dart:async/zone.dart:1132:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#50     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#51     _StreamController._add (dart:async/stream_controller.dart:639:7)
#52     _StreamController.add (dart:async/stream_controller.dart:585:5)
#53     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#54     _rootRunUnary (dart:async/zone.dart:1136:13)
#55     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#59     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#60     _StreamController._add (dart:async/stream_controller.dart:639:7)
#61     _StreamController.add (dart:async/stream_controller.dart:585:5)
#62     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#63     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#64     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#65     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#66     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#67     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

```
1538435427461 => {"id":"2621","method":"execution.getSuggestions","params":{"code":"co","offset":2,"contextFile":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","contextOffset":2154,"varia
1538435427629 <= {"id":"2620","result":{"suggestions":[{"kind":"INVOCATION","relevance":1000,"completion":"Codec","selectionOffset":5,"selectionLength":0,"isDeprecated":false,"isPotential":false,"docS
1538435427632 <= {"event":"analysis.highlights","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":22},{"type":"BUILT_IN","
1538435427632 <= {"event":"analysis.navigation","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","regions":[{"offset":7,"length":14,"targets":[0]},{"offset":31,"length":31,
1538435427632 <= {"event":"analysis.closingLabels","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","labels":[{"offset":1292,"length":52,"label":"MaterialApp"},{"offset":22
1538435427632 <= {"event":"analysis.outline","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit
1538435427632 <= {"event":"analysis.overrides","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","overrides":[{"offset":1220,"length":5,"superclassMember":{"element":{"kind"
1538435427635 => {"id":"2622","method":"execution.getSuggestions","params":{"code":"con","offset":3,"contextFile":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","contextOffset":2154,"vari
1538435427660 <= {"event":"analysis.errors","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file":"/Users/pquitslun
1538435427661 <= {"event":"analysis.highlights","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":22},{"type":"BUILT_IN","
1538435427662 <= {"event":"analysis.navigation","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","regions":[{"offset":7,"length":14,"targets":[0]},{"offset":31,"length":31,
1538435427662 <= {"event":"analysis.closingLabels","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","labels":[{"offset":1292,"length":52,"label":"MaterialApp"},{"offset":22
1538435427663 <= {"event":"analysis.outline","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit
1538435427663 <= {"event":"analysis.overrides","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","overrides":[{"offset":1220,"length":5,"superclassMember":{"element":{"kind"
1538435427702 <= {"event":"analysis.errors","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file":"/Users/pquitslun
1538435427709 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 2622, method: execution.getSuggestions, params: {code: con, offset: 3, contextFile: /Users/p
1538435427895 <= {"id":"2621","result":{"suggestions":[{"kind":"INVOCATION","relevance":1000,"completion":"Codec","selectionOffset":5,"selectionLength":0,"isDeprecated":false,"isPotential":false,"docS
1538435427897 <= {"event":"analysis.highlights","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":22},{"type":"BUILT_IN","
1538435427897 <= {"event":"analysis.navigation","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","regions":[{"offset":7,"length":14,"targets":[0]},{"offset":31,"length":31,
1538435427898 <= {"event":"analysis.closingLabels","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","labels":[{"offset":1292,"length":52,"label":"MaterialApp"},{"offset":22
1538435427898 <= {"event":"analysis.outline","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit
1538435427899 <= {"event":"analysis.overrides","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","overrides":[{"offset":1220,"length":5,"superclassMember":{"element":{"kind"
1538435427942 <= {"event":"analysis.errors","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file":"/Users/pquitslun
1538435427943 <= {"event":"analysis.highlights","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":22},{"type":"BUILT_IN","
1538435427944 <= {"event":"analysis.navigation","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","regions":[{"offset":7,"length":14,"targets":[0]},{"offset":31,"length":31,
1538435427944 <= {"event":"analysis.closingLabels","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","labels":[{"offset":1292,"length":52,"label":"MaterialApp"},{"offset":22
1538435427944 <= {"event":"analysis.outline","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit
1538435427945 <= {"event":"analysis.overrides","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","overrides":[{"offset":1220,"length":5,"superclassMember":{"element":{"kind"
1538435427946 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1538435427947 <= {"event":"analysis.implemented","params":{"file":"/Users/pquitslund/IdeaProjects/fplugin_proj/lib/main.dart","classes":[],"members":[]}}
```

/cc @jacob314 @bwilkerson @devoncarew 

_Copied from original issue: flutter/flutter-intellij#2647_

**Comment by pq** [comment]
_From @jacob314 on October 2, 2018 1:55_

@scheglov any ideas?

**Comment by pq** [comment]
_From @scheglov on October 2, 2018 1:58_

I've seen this myself a couple times.
Unfortunately I didn't have time to implement a proper fix yet.

**Comment by pq** [comment]
As another point of reference: you can get back to a happy place by editing and re-saving the file.

> Unfortunately I didn't have time to implement a proper fix yet.

Is this a fix here or in the dart plugin?

**Comment by pq** [comment]
_From @scheglov on October 2, 2018 18:5_

It should be fixed in Analysis Server.
API and the Dart plugin are fine.

**Comment by pq** [comment]
OK, great.  Should I move this to the SDK?

**Comment by pq** [comment]
_From @scheglov on October 2, 2018 18:7_

Sounds right to me.

**Comment by bwilkerson** [comment]
Unfortunately, the implementation approach used to support completions within runtime expressions is not compatible with the semantics of `AnalysisSession`, and re-implementing the feature before 2.1 is not feasible. As a result, we have chosen to disable the feature temporarily (https://dart-review.googlesource.com/c/sdk/+/78145).

This issue is being updated to reflect the need to re-enable the feature in the near term.

**Comment by srawlins** [comment]
I'm very curious to know if this is still disabled; if so, sounds like P2 to re-enable

**Comment by srawlins** [comment]
Closing as stale for now.
