### ISSUE TITLE
Error: Failed to handle completion domain request

### ISSUE THREAD

**Issue by marcosnasp** [dart-lang/sdk#34658]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.4505.22`
- `2.0.0`
- `IU-182.4505.22, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\MARCOS~1\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0, server version 1.20.3, error: Failed to handle completion domain request: {id: 9861, method: completion.getSuggestions, params: {file: D:\Desenv\git_repos\github\rest-api-dart-aqueduct\fave_reads\lib\controller\books_controller.dart, offset: 1598}, clientRequestTime: 1538577111043}
type 'PrefixedIdentifierImpl' is not a subtype of type 'SimpleIdentifier'
#0      _getTargetId (package:analysis_server/src/services/completion/dart/arglist_contributor.dart)
#1      ArgListContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/arglist_contributor.dart:189:33)
<asynchronous suspension>
#2      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:110:29)
<asynchronous suspension>
#3      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:98:46)
<asynchronous suspension>
#4      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:209:5)
<asynchronous suspension>
#5      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:144:9)
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1500:12)
#10     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:141:12)

**Comment by devoncarew** [comment]
Thanks for the report! This is a dup of https://github.com/dart-lang/sdk/issues/34227, which is fixed, and available in the latest dev version of the SDK.
