### ISSUE TITLE
linter vs mixins: NoSuchMethodError: The getter 'declaredElement' was called on null.

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#34664]
As of https://chromium.googlesource.com/external/github.com/flutter/engine/+/71ba20a6426e4a9c3f3810f33f54e18f3be91985 Dart SDK roll into Flutter, I'm seeing the following linter crash when running `flutter analyze`:

```
Error from the analysis server: Exception while using a AvoidFieldInitializersInConstClasses to visit a FieldDeclarationImpl in MixinDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'declaredElement' was called on null.
Receiver: null
Tried calling: declaredElement
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _Visitor.visitFieldDeclaration (package:linter/src/rules/avoid_field_initializers_in_const_classes.dart:104:10)
#2      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4382:49)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:671:14)
#4      LinterVisitor.visitFieldDeclaration (package:analyzer/src/lint/linter_visitor.dart:239:5)
#5      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4382:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#7      MixinDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7919:13)
#8      RecursiveAstVisitor.visitMixinDeclaration (package:analyzer/dart/ast/visitor.dart:1026:10)
#9      LinterVisitor.visitMixinDeclaration (package:analyzer/src/lint/linter_visitor.dart:432:11)
#10     MixinDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7910:49)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#13     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#14     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:120:11)
#15     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#16     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:271:10)
#17     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:141:13)
#18     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#19     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:140:17)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#21     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:139:37)
#22     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:80:14)
<asynchronous suspension>
#23     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#24     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:79:43)
<asynchronous suspension>
#25     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#26     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#27     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#28     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1046:39)
<asynchronous suspension>
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#30     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#31     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#32     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#33     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#34     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#40     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#41     main (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#42     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#43     main (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#44     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

@pq @JekCharlsonYu @stereotype441

**Comment by yjbanov** [comment]
I'm seeing it again in `linter` version `0.1.68` and `analyzer` version `0.33.0`.

Example:

```
Error from the analysis server: Exception while using a AvoidFieldInitializersInConstClasses to visit a FieldDeclarationImpl in MixinDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'declaredElement' was called on null.
Receiver: null
Tried calling: declaredElement
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _Visitor.visitFieldDeclaration (package:linter/src/rules/avoid_field_initializers_in_const_classes.dart:104:10)
#2      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4382:49)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:671:14)
#4      LinterVisitor.visitFieldDeclaration (package:analyzer/src/lint/linter_visitor.dart:239:5)
#5      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4382:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#7      MixinDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7919:13)
#8      RecursiveAstVisitor.visitMixinDeclaration (package:analyzer/dart/ast/visitor.dart:1026:10)
#9      LinterVisitor.visitMixinDeclaration (package:analyzer/src/lint/linter_visitor.dart:432:11)
#10     MixinDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7910:49)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#13     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#14     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:120:11)
#15     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#16     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:271:10)
#17     LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:144:13)
#18     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#19     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:143:17)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#21     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:142:37)
#22     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:83:14)
#23     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#24     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:82:65)
#25     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#27     _rootRunUnary (dart:async/zone.dart:1132:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#32     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#39     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#40     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#41     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Contents of `packages/flutter_tool/.packages`:

```
# Generated by pub on 2018-10-04 15:45:25.530534.
analyzer:file:///usr/local/google/home/yjbanov/.pub-cache/hosted/pub.dartlang.org/analyzer-0.33.0/lib/
...
linter:file:///usr/local/google/home/yjbanov/.pub-cache/hosted/pub.dartlang.org/linter-0.1.68/lib/
...
```

**Comment by yjbanov** [comment]
Having said that, I have multiple copies of `analyzer` and `linter`. One version is coming from `pub`, linked to from the `.packages` file. One version is downloaded by the `flutter` command from the pre-built Dart SDK in our build artifact cloud bucket. Finally, there's one in my custom build of the Flutter Engine. I'm not 100% sure which version I end up using when I run the analyzer. I'll see if I can find that out.

**Comment by yjbanov** [comment]
nvm, was hitting a wrong version of the Dart SDK.
