### ISSUE TITLE
Fasta/kernel 'finishForwarders' crashes when named parameter initializer is null.

### ISSUE THREAD

**Issue by jban332** [dart-lang/sdk#34694]
I get the error with dart2js, SDK version 2.1.0-dev.6.0.

The problem is at [pkg/front_end/lib/src/fasta/kernel/kernel_library_builder.dart](https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/kernel/kernel_library_builder.dart) method 'finishForwarders' line:
```dart
forwarderNamed.initializer = cloner.clone(originNamed.initializer);
```

A few lines earlier the same method does a null check for initializers of positional parameters. This makes me believe that the fix is:
```dart
if (originNamed.initializer!=null) {
  forwarderNamed.initializer = cloner.clone(originNamed.initializer);
}
```

Stack trace:

The compiler crashed: Crash when compiling null,
at character offset null:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept(Instance of 'CloneVisitor')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      CloneVisitor.clone (package:kernel/clone.dart:69:34)
#2      KernelLibraryBuilder.finishForwarders (package:front_end/src/fasta/kernel/kernel_library_builder.dart:1069:45)
#3      SourceLoader.finishNoSuchMethodForwarders.<anonymous closure> (package:front_end/src/fasta/source/source_loader.dart:448:26)
#4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#5      SourceLoader.finishNoSuchMethodForwarders (package:front_end/src/fasta/source/source_loader.dart:446:14)
#6      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:299:18)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
<asynchronous suspension>
#8      KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:294:12)
<asynchronous suspension>
#9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:150:42)
<asynchronous suspension>
#10     withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
<asynchronous suspension>
#11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:57:10)
<asynchronous suspension>
#12     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:70:32)
<asynchronous suspension>
#13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:130:20)
<asynchronous suspension>
#14     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#15     new Future.sync (dart:async/future.dart:224:31)
#16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#22     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:128:10)
#23     compile (package:front_end/src/api_unstable/dart2js.dart:68:46)
<asynchronous suspension>
#24     LibraryLoaderTask.loadLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/library_loader.dart:66:27)
<asynchronous suspension>
#25     CompilerTask.measure (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63:51)
#26     LibraryLoaderTask.loadLibraries (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/library_loader.dart:48:12)
#27     Compiler.runInternal (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:266:59)
<asynchronous suspension>
#28     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:215:38)
#29     new Future.sync (dart:async/future.dart:224:31)
#30     Compiler.run.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:215:20)
#31     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#32     Compiler.run (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:212:41)
#33     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/compiler/lib/src/apiimpl.dart:148:22)
#34     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#38     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#39     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#42     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by kmillikin** [comment]
I tried various things to try to get a nsm forwarder with an origin with a null initializer (e.g., involving forwarding stubs) and I couldn't make it happen.
