### ISSUE TITLE
DDC: Crash using private members with new-style Dart 2 mixins

### ISSUE THREAD

**Issue by ethanblake4** [dart-lang/sdk#34708]
dart --version output: `2.1.0-dev.6.0 (Thu Sep 27 09:51:34 2018 +0200) on "macos_x64"`

When using a mixin created with the new-style `mixin` keyword, dartdevc crashes if the implementing class contains a private member. The following code causes a compiler crash:
```dart
mixin AwesomeAnimal {}

class Dog with AwesomeAnimal {

  Dog({ this.barkNoise });

  String barkNoise;

  bool get _canBark {
    return barkNoise != null;
  }

  @override
  String toString() {
    return "Dog can bark: $_canBark";
  }
}
```

The issue will not occur if:
- `_canBark` is changed to `canBark`, making it public
- `mixin` is changed to `abstract class`

The issue will still occur if:
- `_canBark` is changed to be a instance variable instead of a getter

Stack trace:
```
Receiver: null
Tried calling: []("_canBark")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new _LibraryVirtualFieldModel.build.<anonymous closure> (package:dev_compiler/src/analyzer/property_model.dart:127:47)
#2      MappedIterator.moveNext (dart:_internal/iterable.dart:392:18)
#3      WhereIterator.moveNext (dart:_internal/iterable.dart:438:22)
#4      _HashSet.addAll (dart:collection/runtime/libcollection_patch.dart:641:22)
#5      new _LibraryVirtualFieldModel.build (package:dev_compiler/src/analyzer/property_model.dart:126:34)
#6      VirtualFieldModel._getModel.<anonymous closure> (package:dev_compiler/src/analyzer/property_model.dart:29:52)
#7      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29) [49 more]
```

**Comment by ethanblake4** [comment]
Another update: The issue will also occur if the class is private. So, the following code will fail to compile:

```dart
mixin AwesomeAnimal {}

class _Dog with AwesomeAnimal {

  _Dog({ this.barkNoise });

  String barkNoise;

  @override
  String toString() {
    return "Dog can bark: $_canBark";
  }
}```

**Comment by Markzipan** [comment]
This issue should be resolved in DDC now (and fails to repro locally for me).
