### ISSUE TITLE
Missing necessary RTI with omit-implicit-checks

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#34701]
The bug might be related to subclassing with mixins. This started breaking with b4341f02d

**repro.dart**:
```dart
import 'dart:async';
import 'package:meta/dart2js.dart';

class A {
  @noInline
  Future<T> _foo<T>(FutureOr<T> Function() f) async {
    return await f();
  }

  @noInline
  Future<String> get m async => _foo(() => "a");
}

class M {}

class B extends A with M {

  @noInline
  Future<T> _foo<T>(FutureOr<T> Function() f) => super._foo(f);
}

main() async {
  var b = new B();
  print(b.m.runtimeType);
  print((await b.m).runtimeType);
}
```

Running this program prints if you use dart2js with no options:
```
_Future<String>
String
```

when passing `--omit-implicit-checks` you get:
```
_Future<String>
_Future<dynamic>
```

One key difference in the output is that we drop the type parameter for `_foo$1$1` on B's definition:
```
      _foo$1$1: function(f) {
```

vs
```
      _foo$1$1: function(f, $T) {
```

Because we drop the type-parameter, future chaining takes a different code path (in Dart1 this would have worked through flattening)

**Comment by sigmundch** [comment]
Also note that if we remove the `@noInline` annotations, we get a wonderful crash:

```
The compiler crashed: Assertion failure: Runtime type information not available for type_variable_local(_foo.T) in (SyntheticLocal(result), Instance of 'ThisLocal', local(B._foo#f)) for j:method(B._foo).
#0      failedAt (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:49:3)
#1      LocalsHandler.readLocal (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/locals_handler.dart:322:11)
#2      TypeBuilder.addTypeVariableReference.readAsParameter (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:143:12)
#3      TypeBuilder.addTypeVariableReference (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:154:31)
#4      TypeBuilder.analyzeTypeArgument (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:224:14)
#5      KernelSsaGraphBuilder._addTypeArguments (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3279:30)
#6      KernelSsaGraphBuilder._visitArgumentsForStaticTarget (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3271:5)
#7      KernelSsaGraphBuilder.visitSuperMethodInvocation (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:4587:36)
#8      SuperMethodInvocation.accept (package:kernel/ast.dart:2863:36)
#9      KernelSsaGraphBuilder.visitReturnStatement (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1477:23)
#10     ReturnStatement.accept (package:kernel/ast.dart:4082:35)
#11     KernelSsaGraphBuilder._visitInlinedFunction (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:5451:30)
#12     KernelSsaGraphBuilder._doInline (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:5429:5)
#13     KernelSsaGraphBuilder._tryInlineMethod.doInlining.<anonymous closure> (file:///usr/local/google/home/sigmund/dart/git_all/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:5124:11)
```

Is that for a related reason?

**Comment by johnniwinther** [comment]
A fix is ready: https://dart-review.googlesource.com/c/sdk/+/78360

I couldn't repro the crash, though.

**Comment by sigmundch** [comment]
mmm - I can repro the crash if I comment out all 3 `noInline` and I run with `--omit-implicit-checks`:

```dart
import 'dart:async';
import 'package:meta/dart2js.dart';

class A {
  Future<T> _foo<T>(FutureOr<T> Function() f) async => await f();
  Future<String> get m async => _foo(() => "a");
}
class M {}
class B extends A with M {
  Future<T> _foo<T>(FutureOr<T> Function() f) => super._foo(f);
}

main() async {
  var b = new B();
  print(b.m.runtimeType);
  print((await b.m).runtimeType);
}
```

**Comment by johnniwinther** [comment]
Ahh, a third annotation...

I'll update the added test. The fix also fixes the crash.

**Comment by sigmundch** [comment]
:+1: awesome
