### ISSUE TITLE
NoSuchMethodError: The getter 'declaredElement' was called on null in ResolutionMapImpl.elementDeclaredByCompilationUnit 

### ISSUE THREAD

**Issue by thargyi74** [dart-lang/sdk#34740]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1440x900`

# Exception

Please append the contents of:
file:///private/var/folders/97/j96btsj95357rvm4xhg5b1nw0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, FATAL error: Failed to handle request: {id: 7, method: edit.getAssists, params: {file: /Volumes/Ye Min Naing HD/Flutter Tensor Programming/gridview_tabs_steppers/lib/main.dart, offset: 391, length: 0}, clientRequestTime: 1539143675608}
NoSuchMethodError: The getter 'declaredElement' was called on null.
Receiver: null
Tried calling: declaredElement
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ResolutionMapImpl.elementDeclaredByCompilationUnit (package:analyzer/src/dart/ast/resolution_map.dart:50:12)
#2      EditDomainHandler.getAssists (package:analysis_server/src/edit/edit_domain.dart:179:25)
<asynchronous suspension>
#3      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:342:9)
#4      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:750:45)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#6      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:746:50)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1500:12)

**Comment by scheglov** [comment]
It seems that `AnalysisResult` returned from `AnalysisDriver.getResult()` did not have `unit` filled. It might be because of some race condition in `performWork()` that was doing some async work. Now, this asynchronous is gone, and the error is probably fixed.
