### ISSUE TITLE
Dart2js generates code for async* which crashes at run-time.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34776]
Example code:
```dart
Stream<int> foo() async* {                                        
  yield 1;                                                        
}
                                                                                                                                 
main() {                                                          
 foo();
}
```
crashes with:
```
.../sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: TypeError: Closure '_wrapJsFunctionForAsync_closure': type '(int, dynamic) => dynamic' is not a subtype of type '(dynamic, dynamic) => dynamic'
          throw e;
          ^
TypeError: Closure '_wrapJsFunctionForAsync_closure': type '(int, dynamic) => dynamic' is not a subtype of type '(dynamic, dynamic) => dynamic'
    at Object.wrapException (yield2.dart.out:737:17)
    at Object.functionTypeCheck (yield2.dart.out:1225:17)
    at _RootZone.registerBinaryCallback$3$1 (yield2.dart.out:3477:18)
    at _RootZone.registerBinaryCallback$1 (yield2.dart.out:3480:21)
    at Object._wrapJsFunctionForAsync (yield2.dart.out:1872:30)
    at Object.foo (yield2.dart.out:3755:26)
    at main (yield2.dart.out:3788:9)
    at action (.../sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (.../sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (.../sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
```
This is very suspicious since the stream is never even listened to, so there are no user-provided callbacks involved, this is entirely in the code added by the compiler for the `async*` function.

**Comment by lrhn** [comment]
Was apparently an out-of-date/sync SDK issue. A complete rebuild removed the problem.
