### ISSUE TITLE
Analyzer crash: 'MixinDeclarationImpl' is not a subtype of type 'ClassDeclaration'

### ISSUE THREAD

**Issue by dhil** [dart-lang/sdk#34809]
Analyzer version: `dartanalyzer version 2.1.0-edge.49c7014fe0c65e042623f5bb2986ab57661fabc4`.

The following (incorrect) program causes the analyzer to crash.
```dart
class A {}
mixin M on A {
  const factory M() = A;
}
void main() {}
```

Trace:
```
Unhandled exception:
type 'MixinDeclarationImpl' is not a subtype of type 'ClassDeclaration'
#0      TypeNameResolver._inferTypeArgumentsForRedirectedConstructor (package:analyzer/src/generated/resolver.dart:7341:24)
#1      TypeNameResolver.resolveTypeName (package:analyzer/src/generated/resolver.dart:7200:13)
#2      TypeResolverVisitor.visitTypeName (package:analyzer/src/generated/resolver.dart:8760:23)
#3      TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:11019:49)
#4      ConstructorNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3130:12)
#5      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3169:10)
#6      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8728:18)
#7      UnifyingAstVisitor.visitConstructorName (package:analyzer/dart/ast/visitor.dart:3010:51)
#8      ConstructorNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:3126:49)
#9      ScopedVisitor.visitConstructorDeclaration (package:analyzer/src/generated/resolver.dart:6308:35)
#10     TypeResolverVisitor.visitConstructorDeclaration (package:analyzer/src/generated/resolver.dart:8446:11)
#11     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2932:15)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#13     ScopedVisitor.visitMixinMembersInScope (package:analyzer/src/generated/resolver.dart:6686:18)
#14     ScopedVisitor.visitMixinDeclaration (package:analyzer/src/generated/resolver.dart:6668:7)
#15     MixinDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7930:49)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#17     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2423:21)
#18     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3169:10)
#19     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8728:18)
#20     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2994:51)
#21     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2416:49)
#22     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:590:10)
#23     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:109:9)
#24     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#25     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:108:13)
#26     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:84:14)
<asynchronous suspension>
#27     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:270:21)
<asynchronous suspension>
#28     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:83:43)
<asynchronous suspension>
#29     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:71)
<asynchronous suspension>
#30     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
#31     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
#32     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:638:43)
<asynchronous suspension>
#33     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:130:58)
<asynchronous suspension>
#34     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:170:11)
<asynchronous suspension>
#35     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:106:18)
<asynchronous suspension>
#36     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:751:21)
#37     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:406:40)
#38     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#39     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#40     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#41     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#42     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1287:9)
<asynchronous suspension>
#1      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:638:43)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:130:58)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:170:11)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:106:18)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:751:21)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:406:40)
#9      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#13     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#16     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/80264
