### ISSUE TITLE
Dart Analysis failing

### ISSUE THREAD

**Issue by SelloN** [dart-lang/sdk#34805]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\SelloN\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Captured exception
Out of Memory
#0      new Uint8List (dart:typed_data/runtime/libtyped_data_patch.dart:2169:66)
#1      new ByteData (dart:typed_data/runtime/libtyped_data_patch.dart:41:22)
#2      _UnitApiSignatureComputer.addTokens (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:121:386)
#3      _UnitApiSignatureComputer.compute (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:108:9)
#4      computeUnlinkedApiSignature (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:15:12)
#5      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:437:31)
#6      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#7      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:435:24)
#8      FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:222:32)
#9      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#10     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:218:20)
#11     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:291:9)
#12     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:899:22)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Do you use Angular plugin?

Could you try to use the latest Dev channel build from https://webdev.dartlang.org/tools/sdk/archive (currently `2.1.0-dev.7.1`)? We made several changes that we hope will fix the memory leak.

**Comment by SelloN** [comment]
No I don't use Angular plugin. It just stopped after an update.
