### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by Fraunhofer** [dart-lang/sdk#34828]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 3840x1080`

# Exception

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Captured exception
Out of Memory
#0      new Uint8List (dart:typed_data/runtime/libtyped_data_patch.dart:2169:66)
#1      new ByteData (dart:typed_data/runtime/libtyped_data_patch.dart:41:22)
#2      ApiSignature.addInt (package:front_end/src/base/api_signature.dart:145:30)
#3      _UnitApiSignatureComputer.addToken (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:98:40)
#4      _UnitApiSignatureComputer.addTokens (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:70:7)
#5      _UnitApiSignatureComputer.addClassOrMixin (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:43:9)
#6      _UnitApiSignatureComputer.compute (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:105:9)
#7      computeUnlinkedApiSignature (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:15:12)
#8      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:437:31)
#9      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#10     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:435:24)
#11     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:222:32)
#12     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)

**Comment by DanTup** [comment]
Maybe same as #34851/#34850/#34929?
