### ISSUE TITLE
Encountered a Dart Analysis Server error

### ISSUE THREAD

**Issue by Klievan** [dart-lang/sdk#34823]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1440x900  Retina`

# Exception
https://gist.github.com/Klievan/e5c48bf13ad97db355b37bb24995d6e8

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/ivanherrera/development/ChiroBrechtApp/lib/views/admin/BeheerLeiderWidget.dart context: exception_20181016_221452_326
RangeError (index): Invalid value: Not in range 0..11, inclusive: 12
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1456:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1362:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7707:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7599:5)
#6      _ParameterElementImpl

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I think this was fixed in 765a78d44e7a9e5fd09b10a3b0c60c6e2e4bba96
Please try with the latest dev channel build.

**Comment by Klievan** [comment]
Can confirm, it is fixed on the latest dev channel. Cheers!

**Comment by bwilkerson** [comment]
Thanks for checking and for letting us know!
