### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by adminparry** [dart-lang/sdk#34831]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.5281.24`
- `2.1.0-edge.a50dfd66980ed5c9aef9851fcc57557fb607769c`
- `IU-181.5281.24, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\parry\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a50dfd66980ed5c9aef9851fcc57557fb607769c, server version 1.20.5, error: Analysis failed: D:\flutter_tourist\lib\lesson3\gallery\app.dart
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5052:5)
#1      TypeProviderForLink.objectType (package:analyzer/src/summary/link.dart:5021:23)
#2      ClassElementForLink_Class._computeInterfaceType (package:analyzer/src/summary/link.dart:868:67)
#3      ClassElementForLink_Class.supertype (package:analyzer/src/summary/link.dart:779:27)
#4      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:300:33)
#5      InstanceMemberInferrer._inferClasses (package:analyzer/src/task/strong_mode.dart:331:9)
#6      InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:82:5)
#7      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1557:10)
#8      LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3635:12)
#9      LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3335:15)
#10     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3275:7)
#11     Depen

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/34823
