### ISSUE TITLE
Cannot build 32 bit dart

### ISSUE THREAD

**Issue by Rockvole** [dart-lang/sdk#34840]
I have spent weeks writing some dart code to run on my server. I never thought that my ubuntu server being 32-bit would be an issue.
I tried installing dart from the googleapis repo, but that fails on my 32-bit server (works on my 64 bit machine). 
I downloaded the dart 2.0.0 32 bit zip and that installs fine, except my dart code has a bunch of errors only on dart 2.0.0. I cannot find a newer zip file to download.
https://www.dartlang.org/tools/sdk/archive

So I follow the instructions to build :
https://github.com/dart-lang/sdk/wiki/Building

All works fine on my 64 bit machine, but on the 32-bit Ubuntu server I get :

	fetch dart
	Running: gclient root
	WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
	Running: gclient config --spec 'solutions = [
	  {
		"url": "https://dart.googlesource.com/sdk.git",
		"managed": False,
		"name": "sdk",
		"deps_file": "DEPS",
		"custom_deps": {},
	  },
	]
	'
	Running: gclient sync

	________ running 'git -c core.deltaBaseCacheLimit=512m clone --no-checkout --progress https://dart.googlesource.com/sdk.git /work/git/dart-sdk/_gclient_sdk_CNSlXN' in '/work/git/dart-sdk'
	Cloning into '/work/git/dart-sdk/_gclient_sdk_CNSlXN'...
	remote: Sending approximately 697.66 MiB ...        
	remote: Counting objects: 911, done        
	remote: Finding sources: 100% (56/56)           
	remote: Total 778022 (delta 622451), reused 778004 (delta 622451)        
	Receiving objects: 100% (778022/778022), 697.44 MiB | 12.69 MiB/s, done.
	Resolving deltas:  69% (429633/622451)   
	[0:01:00] Still working on:
	[0:01:00]   sdk
	Resolving deltas:  75% (468054/622451)   
	[0:01:10] Still working on:
	[0:01:10]   sdk
	Resolving deltas:  78% (487593/622451)   
	[0:01:20] Still working on:
	[0:01:20]   sdk
	Resolving deltas:  79% (496594/622451)   
	[0:01:30] Still working on:
	[0:01:30]   sdk
	Resolving deltas:  82% (515933/622451)   
	[0:01:40] Still working on:
	[0:01:40]   sdk
	Resolving deltas:  84% (525557/622451)   
	[0:01:50] Still working on:
	[0:01:50]   sdk
	Resolving deltas:  86% (538812/622451)   
	[0:02:00] Still working on:
	[0:02:00]   sdk
	Resolving deltas:  95% (593503/622451)   
	[0:02:10] Still working on:
	[0:02:10]   sdk
	Resolving deltas: 100% (622451/622451), done.
	Checking connectivity... done.
	Syncing projects:   0% ( 0/ 2) 
	[0:02:18] Still working on:
	[0:02:18]   sdk
	Syncing projects: 100% (86/86), done.                                     

	________ running 'cipd ensure -log-level error -root /work/git/dart-sdk -ensure-file /tmp/tmpnlOrlc.ensure' in '.'
	Errors:
	  failed to resolve dart/dart-sdk/linux-386@version:2.1.0-dev.6.0 (line 7): no such package
	Error: Command 'cipd ensure -log-level error -root /work/git/dart-sdk -ensure-file /tmp/tmpnlOrlc.ensure' returned non-zero exit status 1
	Traceback (most recent call last):
	  File "/work/git/depot_tools/fetch.py", line 306, in <module>
		sys.exit(main())
	  File "/work/git/depot_tools/fetch.py", line 301, in main
		return run(options, spec, root)
	  File "/work/git/depot_tools/fetch.py", line 295, in run
		return checkout.init()
	  File "/work/git/depot_tools/fetch.py", line 137, in init
		self.run_gclient(*sync_cmd)
	  File "/work/git/depot_tools/fetch.py", line 82, in run_gclient
		return self.run(cmd_prefix + cmd, **kwargs)
	  File "/work/git/depot_tools/fetch.py", line 71, in run
		subprocess.check_call(cmd, **kwargs)
	  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
		raise CalledProcessError(retcode, cmd)
	subprocess.CalledProcessError: Command '('gclient', 'sync')' returned non-zero exit status 1

**Comment by Rockvole** [comment]
@whesse

**Comment by whesse** [comment]
On the archive page at https://www.dartlang.org/tools/sdk/archive there is a second section with dev releases, below the section giving stable releases.  You should be able to download a more recent 32-bit SDK from that lower section.

The problem where the i386 cipd package seems to be missing, when gclient sync is run on the checkout, could be a real problem and needs to be checked out, @athomas

**Comment by athomas** [comment]
@Rockvole Can you build the 32bit SDK on the 64bit machine and then copy it to your server?

@whesse There's more than this in the build infrastructure that wouldn't work on 32bit. I don't want to increase the maintenance burden unless we really have to. If cross compiling to 32bit on a 64bit machine is viable alternative, we should just document that.

Direct link to the latest dev release (from the archive page):
https://storage.googleapis.com/dart-archive/channels/dev/release/2.1.0-dev.7.1/sdk/dartsdk-linux-ia32-release.zip

**Comment by Rockvole** [comment]
@whesse - thanks I got it working using the dev version. I didn't see that section before, I think the dev section expands via javascript and my darkreader extension is interfering with that on firefox.

I never thought of cross compiling on my 64-bit machine, I'm sure that would be fine for most people. My server has only 1gb ram and the 32-bit version of Ubuntu runs very well on it.
