### ISSUE TITLE
Dart Analysis Peaked memory usage high at 99%, i have attached error report here. The same thing happens in VSCode too

### ISSUE THREAD

**Issue by suriyansuresh** [dart-lang/sdk#34851]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-181.5540.7`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IC-181.5540.7, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

# Exception

Please append the contents of:
file://C:\Users\SURESH~1\AppData\Local\Temp\report1061.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: D:\code\housie\housie_app\lib\main.dart
Out of Memory
#0      new Uint8List (dart:typed_data/runtime/libtyped_data_patch.dart:2169:66)
#1      new ByteData (dart:typed_data/runtime/libtyped_data_patch.dart:41:22)
#2      ApiSignature.addInt (package:front_end/src/base/api_signature.dart:145:30)
#3      _UnitApiSignatureComputer.addToken (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:98:40)
#4      _UnitApiSignatureComputer.addTokens (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:70:7)
#5      _UnitApiSignatureComputer.addClassOrMixin (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:43:9)
#6      _UnitApiSignatureComputer.compute (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:105:9)
#7      computeUnlinkedApiSignature (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:15:12)
#8      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:437:31)
#9      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#10     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:435:24)
#11     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:904:12)
#12     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:639:21)

**Comment by natebosch** [comment]
cc @scheglov

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/34850
