### ISSUE TITLE
Debug evaluation probably doesn't provide types

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#34863]
I have the following file:
```
import 'dart:developer';

main() {
  List<String> msgs = ["hello", "a", "b"];
  debugger();
  print(msgs.where((s) => s.contains("a")).toList());
  print(msgs);
}
```

Executing it with `out/ReleaseX64/dart --enable-vm-service:54975 <file.dart>` and going to http://127.0.0.1:54975/ it's stopped at `:6:14` as it should. Going to the debugger and evaluating `p msgs.where((s) => s.contains("a")).toList()` gives me
```
Unhandled exception:
type '(dynamic) => dynamic' is not a subtype of type '(String) => bool' of 'test'
#0      Eval (org-dartlang-debug:synthetic_debug_expression:0:6)
#1      main (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/mx.dart:6:14)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:286:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:169:12)
```

If I instead say `p msgs.where((String s) => s.contains("a")).toList()` or `p msgs.where((s) => s.contains("a") as bool).toList()` I get the expected
```
= _GrowableList (1) {  ⊟  
[ 0 ] : 'a'
}
```

It seems like probably fasta isn't getting passed the correct types.
Update: Actually, running `out/ReleaseX64/dart -DDFE_VERBOSE=true --enable-vm-service:54975` basically confirms that: `DFE: request: [4, SendPort, 207040027, msgs.where((s) => s.contains("a")).toList(), [msgs], [], file:///usr/local/google/home/jensj/code/dart-sdk/sdk/mx.dart, null, false, false, true]`.

**Comment by jensjoha** [comment]
Here we go:
https://github.com/dart-lang/sdk/blob/a502061c112a73879123301ec017fb06e02476e1/pkg/vm/lib/incremental_compiler.dart#L133-L142
