### ISSUE TITLE
"await for" not working in abstract class

### ISSUE THREAD

**Issue by kaetemi** [dart-lang/sdk#34877]
The same function, using "await for" on the Stream works fine if placed in the class that inherits the abstract class, but fails when implemented in the abstract class.

It seems to be compiling as a regular iteration instead?

---

Here's the code of the function, very simple:

```
  @override
  Future<void> refreshDemoAllOffers() async {
    print("refreshDemoAllOffers");
    NetLoadOffersReq loadOffersReq = new NetLoadOffersReq();
    Stream<TalkMessage> results = ts.sendStreamRequest("loadOffers", loadOffersReq.writeToBuffer());
    await for (TalkMessage res in results) {
      print(res);
    }
    print("refreshDemoAllOffers done");
  }
```

The Stream is just a regular Stream coming from a regular StreamController.

---

It crashes in the "await for", with the following stack logged:

```
I/flutter ( 8677): refreshDemoAllOffers
I/flutter ( 8677): Failed to search for offers: NoSuchMethodError: Class '_ControllerStream<TalkMessage>' has no instance getter 'iterator'.
I/flutter ( 8677): Receiver: Instance of '_ControllerStream<TalkMessage>'
I/flutter ( 8677): Tried calling: iterator
I/flutter ( 8677): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 8677): #1      __NetworkManagerState&State&WidgetsBindingObserver&NetworkProfiles&NetworkOffers&NetworkOffersBusiness&NetworkOffersDemo.refreshDemoAllOffers (package:inf/network_generic/network_offers_demo.dart:51:35)
I/flutter ( 8677): #2      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
I/flutter ( 8677): #3      __NetworkManagerState&State&WidgetsBindingObserver&NetworkProfiles&NetworkOffers&NetworkOffersBusiness&NetworkOffersDemo.refreshDemoAllOffers (package:inf/network_generic/network_offers_demo.dart:45:36)
I/flutter ( 8677): #4      _AppInfluencerState.navigateToSearchOffers.<anonymous closure>.<anonymous closure> (package:inf/navigation_bindings/app_influencer.dart:247:29)
I/flutter ( 8677): #5      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
I/flutter ( 8677): #6      _App
```

---

It does not crash when the exact same function is implemented in the main class.

The classes are structured as follows.

```
abstract class NetworkOffersDemo
    implements NetworkInterface, NetworkInternals {
// ...
}

class _NetworkManagerState extends State<_NetworkManagerStateful>
    with
        WidgetsBindingObserver,
        NetworkProfiles,
        NetworkOffers,
        NetworkOffersBusiness,
        NetworkOffersDemo
    implements NetworkInterface, NetworkInternals {
// ...
}

abstract class NetworkInterface {
// ...
Future<void> refreshDemoAllOffers();
// ...
}

```

So, implementing the function in _NetworkManagerState makes it work, but implementing it in NetworkOffersDemo causes the failure.

---

Dart VM version: 2.1.0-dev.5.0.flutter-a2eb050044 (Mon Sep 24 15:27:07 2018 +0000) on "windows_x64"

**Comment by natebosch** [comment]
I can repro this on the VM at version `2.1.0-dev.7.1`

```dart
import 'dart:async';

abstract class Interface {
  Future<int> stuff(Stream<int> values);
}

abstract class _Mixin implements Interface {
  @override
  Future<int> stuff(Stream<int> values) async {
    var total = 0;
    await for (var value in values) {
      total += value;
    }
    return total;
  }
}

class Implementation extends Object with _Mixin implements Interface {}

void main() async {
  print(await Implementation().stuff(Stream.fromIterable([1, 2, 3])));
}
```

**Comment by kmillikin** [comment]
Yuck.  All for in loops turn into synchronous ones when mixed in and I don't think it ever worked.  I have a fix on the way.
