### ISSUE TITLE
Flaky co19_2/LibTest/io/HttpClientResponse/cookies_A01_t02

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#34884]
From [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8931966217513389808/+/steps/vm_co19_tests_shard_1/0/stdout):
```

FAILED: dartk-vm debug_simdbc64 co19_2/LibTest/io/HttpClientResponse/cookies_A01_t02
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 802ms):
DART_CONFIGURATION=DebugSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/DebugSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_HttpClientResponse_cookies_A01_t02/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/HttpClientResponse/cookies_A01_t02.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 03.000869s):
DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_HttpClientResponse_cookies_A01_t02/out.dill

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
type 'OSError' is not a subtype of type 'bool' of 'function result'
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m debug -a simdbc64 -n dartk-mac-debug-simdbc64 co19_2/LibTest/io/HttpClientResponse/cookies_A01_t02
```

This looks like an incorrect return type of a native function.

**Comment by sortie** [comment]
This seems related to the kind of problem seen in #35207 (although I don't believe that would cause the flakiness?)
