### ISSUE TITLE
what fuck?

### ISSUE THREAD

**Issue by AgelessSwart** [dart-lang/sdk#34900]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4819257`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-173.4819257, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Force\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: F:\Android_project\getbatteryleve\lib\pages\tabs_page.dart context: exception_20181023_165809_580
Element mismatch in F:\Android_project\getbatteryleve\lib\pages\tabs_page.dart at class tabsPageState extends State<tabsPage>
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:54:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#3      __InternalLinkedHashMap

**Comment by AgelessSwart** [comment]
> Analyzer Feedback from IntelliJ
> 
> # Version information
> * `IDEA AI-173.4819257`
> * `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
> * `AI-173.4819257, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`
> 
> # Exception
> Please append the contents of:
> file://C:\Users\Force\AppData\Local\Temp\report1.txt
> 
> ```
> Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: F:\Android_project\getbatteryleve\lib\pages\tabs_page.dart context: exception_20181023_165809_580
> Element mismatch in F:\Android_project\getbatteryleve\lib\pages\tabs_page.dart at class tabsPageState extends State<tabsPage>
> #0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:54:7)
> #1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
> #2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
> #3      __InternalLinkedHashMap
> ```
