### ISSUE TITLE
co19_2/LibTest/io/HttpClientResponse/isRedirect_A01_t01 flaked on Mac

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#34916]
Might be related to Mac issue that we were trying to debug or to the recent changes in HttpClient. 

/cc @mkustermann @aam 

```
FAILED: dartk-vm release_simdbc64 co19_2/LibTest/io/HttpClientResponse/isRedirect_A01_t01
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 392ms):
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_HttpClientResponse_isRedirect_A01_t01/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/HttpClientResponse/isRedirect_A01_t01.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 929ms):
DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_HttpClientResponse_isRedirect_A01_t01/out.dill

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
HttpException: , uri = http://127.0.0.1:52513
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m release -a simdbc64 -n dartk-mac-release-simdbc64 co19_2/LibTest/io/HttpClientResponse/isRedirect_A01_t01
```

**Comment by mraleph** [comment]
Another test flaked:

```
FAILED: dartk-vm release_simdbc64 co19_2/LibTest/io/HttpClientResponse/cookies_A01_t02
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 743ms):
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_HttpClientResponse_cookies_A01_t02/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/HttpClientResponse/cookies_A01_t02.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 861ms):
DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_HttpClientResponse_cookies_A01_t02/out.dill

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
HttpException: , uri = http://127.0.0.1:64521
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m release -a simdbc64 -n dartk-mac-release-simdbc64 co19_2/LibTest/io/HttpClientResponse/cookies_A01_t02
```

**Comment by alexmarkov** [comment]
`simdbc64` architecture was discontinued. `co19_2/LibTest/io/HttpClientResponse/isRedirect_A01_t01` and `co19_2/LibTest/io/HttpClientResponse/cookies_A01_t02` are passing (and not flaky) on all configurations.
