### ISSUE TITLE
Crash during Kernel serialisation: "Missing canonical name for Reference to null::a"

### ISSUE THREAD

**Issue by dhil** [dart-lang/sdk#34912]
Dart version: `Dart VM version: 2.1.0-edge.0b15595913ff89d8486e6677af0254dd6feab350 (Wed Oct 24 10:37:07 2018 +0000) on "linux_x64"`

Having two fields with the same name causes a crash to happen during serialisation of Kernel
```dart
class A {
  int a;
  int a;
  A(this.a, this.a);
}

void main() {
  A(1, 2);
}
```
Stack trace:
```
Missing canonical name for Reference to null::a
#0      BinaryPrinter.writeReference (package:kernel/binary/ast_to_binary.dart:532:9)
#1      BinaryPrinter.visitFieldInitializer (package:kernel/binary/ast_to_binary.dart:925:5)
#2      FieldInitializer.accept (package:kernel/ast.dart:1832:37)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#5      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:242:7)
#6      BinaryPrinter.visitConstructor (package:kernel/binary/ast_to_binary.dart:813:5)
#7      Constructor.accept (package:kernel/ast.dart:1367:32)
#8      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#9      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#10     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:242:7)
#11     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:770:5)
#12     Class.accept (package:kernel/ast.dart:972:30)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#14     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#15     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:242:7)
#16     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:620:5)
#17     Library.accept (package:kernel/ast.dart:409:30)
#18     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#19     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#20     List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
#21     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:234:11)
#22     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49:5)
#23     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:328:5)
#24     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:68:11)
#25     _processLoadRequest (file:///usr/local/google/home/hillerstrom/projects/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:459:13)
<asynchronous suspension>
#26     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
The crash happens regardless of whether none, one, or both of the fields are marked `final`. I believe this program should not even make it to the serialisation phase, it should have been rejected early on by Fasta. By omitting the constructor (and changing the constructor invocation to `A()`) Fasta does indeed produce an early `'a' is already declared in this scope` error.

**Comment by peter-ahe-google** [comment]
Should be fixed by https://dart-review.googlesource.com/c/sdk/+/81413
