### ISSUE TITLE
Out of Memory in package:analyzer

### ISSUE THREAD

**Issue by JanRegent** [dart-lang/sdk#34938]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.4892.20`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IC-182.4892.20, JRE 1.8.0_152-release-1248-b19x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1366x768`

# Exception

Please append the contents of:
file://C:\Users\jregent\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Captured exception
Out of Memory
#0      new Uint8List (dart:typed_data/runtime/libtyped_data_patch.dart:2169:66)
#1      new ByteData (dart:typed_data/runtime/libtyped_data_patch.dart:41:22)
#2      _UnitApiSignatureComputer.addToken (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:121:386)
#3      _UnitApiSignatureComputer.addTokens (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:70:7)
#4      _UnitApiSignatureComputer.addClassOrMixin (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:43:9)
#5      _UnitApiSignatureComputer.compute (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:105:9)
#6      computeUnlinkedApiSignature (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:15:12)
#7      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:437:31)
#8      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#9      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:435:24)
#10     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:222:32)
#11     Performance

**Comment by DanTup** [comment]
Maybe same as #34851/#34850/#34929/#34828/#35015?
