### ISSUE TITLE
VM debug logging can interfere with tests examining stderr

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#34933]
```
FAILED: dartk-vm release_x64 standalone_2/io/dart_std_io_pipe_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 25.000780s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --short_socket_write --optimization-counter-threshold=5 --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/io/dart_std_io_pipe_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(at index 0: Expected <Hello\x0A>, Found: <Attempt:11 waiting for 1 threads to check in\x0AAttempt:12 waiting for 1 threads to check in\x0AAttempt:13 waiting for 1 threads to check in\x0AAttempt:14 waiting for 1 threads to check in\x0AAttempt:15 waiting for 1 threads to check in\x0AAttempt:16 waiting for 1 threads to check in\x0AAttempt:17 waiting for 1 threads to check in\x0AHello\x0A...>) fails.
#0      Expect._fail (package:expect/expect.dart:651:5)
#1      Expect.equals (package:expect/expect.dart:119:9)
#2      checkFileContent (file:///b/s/w/ir/tests/standalone_2/io/dart_std_io_pipe_test.dart:28:10)
#3      test.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/dart_std_io_pipe_test.dart:68:11)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#9      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#12     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m release -n dartk-optcounter-linux-release-x64 standalone_2/io/dart_std_io_pipe_test
```

@a-siva

**Comment by mraleph** [comment]
I think the actual bug here should not be about the interference: we have a test where we could not enter a safepoint after 17 seconds. This indicates a bug in runtime or in the safepointing mechanism. 

If we did not have logging here - we would not know what caused the Timeout. 

/cc @a-siva
