### ISSUE TITLE
Analyzer fails, flutter analyze --flutter-repo

### ISSUE THREAD

**Issue by HansMuller** [dart-lang/sdk#34936]
https://github.com/flutter/flutter/pull/23539 crashes the analyzer.  You see more of the failure in the Cirrus logs for this PR, for example: https://cirrus-ci.com/task/6017324228280320

```dart
Error from the analysis server: Analysis failed: /usr/local/google/home/hansmuller/github/flutter/packages/flutter/test/widgets/page_forward_transitions_test.dart context:
exception_20181025_150526_090
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      GenericInferrer._matchInterfaceSubtypeOf.guardedInterfaceSubtype (package:analyzer/src/generated/type_system.dart:493:29)
#2      GenericInferrer._matchInterfaceSubtypeOf (package:analyzer/src/generated/type_system.dart:511:32)
#3      GenericInferrer._matchInterfaceSubtypeOf.guardedInterfaceSubtype (package:analyzer/src/generated/type_system.dart:494:24)
#4      GenericInferrer._matchInterfaceSubtypeOf (package:analyzer/src/generated/type_system.dart:516:34)
#5      GenericInferrer._matchSubtypeOf (package:analyzer/src/generated/type_system.dart:656:14)
#6      GenericInferrer.tryMatchSubtypeOf (package:analyzer/src/generated/type_system.dart:271:20)
```

**Comment by HansMuller** [comment]
This failure doesn't appear to be specific to this PR. I'm seeing the same swan song with a clean branch from the Flutter repo.
