### ISSUE TITLE
CFE crashes on deserialization

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#34943]
CFE crashes on deserialization of `co19_2/Language/Statements/Labels/scope_t01` and `co19_2/Language/Statements/Labels/scope_t07`

Stack-trace seen from dart2js:
```
tests/co19_2/src/Language/Statements/Labels/scope_t07.dart:15:1:
Internal Error: The compiler crashed when compiling this element.
main() {
^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libgrowable_array.dart:145:60)
#1      BinaryBuilder.readExpression (package:kernel/binary/ast_from_binary.dart:1374:45)
#2      BinaryBuilder.readStatement (package:kernel/binary/ast_from_binary.dart:1600:40)
#3      BinaryBuilder.readStatementList (package:kernel/binary/ast_from_binary.dart:1578:19)
#4      BinaryBuilder.readBlock (package:kernel/binary/ast_from_binary.dart:1745:16)
#5      BinaryBuilder.readStatement (package:kernel/binary/ast_from_binary.dart:1602:16)
#6      BinaryBuilder.readStatementOption (package:kernel/binary/ast_from_binary.dart:1593:38)
#7      BinaryBuilder._setLazyLoadFunction.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:1288:21)
#8      FunctionNode._buildLazy (package:kernel/ast.dart:2017:23)
#9      FunctionNode.body (package:kernel/ast.dart:2022:5)
#10     CapturedScopeBuilder.visitFunctionNode (package:compiler/src/js_model/closure_visitors.dart:551:10)
#11     FunctionNode.accept (package:kernel/ast.dart:2077:30)
#12     Procedure.visitChildren (package:kernel/ast.dart:1746:15)
#13     CapturedScopeBuilder.visitInvokable.<anonymous closure> (package:compiler/src/js_model/closure_visitors.dart:413:12)
#14     CapturedScopeBuilder.enterNewScope (package:compiler/src/js_model/closure_visitors.dart:148:18)
#15     CapturedScopeBuilder.visitInvokable (package:compiler/src/js_model/closure_visitors.dart:412:5)
#16     CapturedScopeBuilder.visitProcedure (package:compiler/src/js_model/closure_visitors.dart:477:5)
#17     Procedure.accept (package:kernel/ast.dart:1739:32)
#18     KernelClosureAnalysis.computeScopeModel (package:compiler/src/js_model/closure.dart:59:12)
#19     KernelToElementMapImpl.computeScopeModel (package:compiler/src/kernel/element_map_impl.dart:1458:34)
#20     KernelWorkItem.run.<anonymous closure>.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:207:47)
#21     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:178:35)
#22     KernelWorkItem.run.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:206:21)
#23     CompilerTask.measure (package:compiler/src/common/tasks.dart:63:51)
#24     KernelWorkItem.run (package:compiler/src/kernel/kernel_strategy.dart:204:26)
#25     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:449:70)
#26     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:178:35)
#27     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:449:32)
#28     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:178:35)
#29     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:447:28)
#30     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:770:15)
#31     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:445:18)
#32     ResolutionEnqueuer._forEach (package:compiler/src/enqueue.dart:417:12)
#33     ResolutionEnqueuer.forEach (package:compiler/src/enqueue.dart:432:5)
#34     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:441:16)
#35     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:178:35)
#36     Compiler.emptyQueue (package:compiler/src/compiler.dart:440:14)
#37     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:466:7)
#38     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:178:35)
#39     Compiler.processQueue (package:compiler/src/compiler.dart:459:14)
#40     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:323:5)
#41     Compiler.compileLoadedLibraries.<anonymous closure> (package:compiler/src/compiler.dart:391:34)
#42     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:178:35)
#43     Compiler.compileLoadedLibraries (package:compiler/src/compiler.dart:390:14)
#44     Compiler.runInternal (package:compiler/src/compiler.dart:277:5)
<asynchronous suspension>
#45     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:217:38)
#46     new Future.sync (dart:async/future.dart:224:31)
#47     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:217:20)
#48     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:178:35)
#49     Compiler.run (package:compiler/src/compiler.dart:214:41)
#50     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:148:22)
#51     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#52     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#53     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#54     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#55     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#56     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#59     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#60     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by jensjoha** [comment]
The code is compiled to this:
```
static method main() → dynamic {
  {
    dynamic x;
  }
  x = self::foo();
[...]
```

meaning that when we deserialize the "var x;" line is deserialized in a block, and then the block ends we throw it away...
