### ISSUE TITLE
Dart Analyzer Error: Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by Navil** [dart-lang/sdk#34951]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.4892.20`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IC-182.4892.20, JRE 1.8.0_152-release-1248-b19x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

# Exception

Please append the contents of:
file://C:\Users\navil\AppData\Local\Temp\report2.txt

````
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: D:\GitHub\nudges_flutter\lib\tabs_page.dart context: exception_20181027_120940_739
Exception: Element not found in summary: package:nudges_flutter/tabs_page.dart;package:nudges_flutter/tabs_page.dart;BuildContext
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:308:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:345:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:35:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:111:29)
#4      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:983:24)
#5      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:929:15)
#6      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:954:15)
#7      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1367:28)
#8      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#9      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7707:14)
#10     ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7599:5)
#11     DeclarationResolver.visitSimpleFormalParameter (package:analyzer/src/generated/declaration_resolver.dart:408:50)
#12     SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9559:15)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#14     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4858:17)
#15     RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:852:10)
#16     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4854:49)
#17     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7694:18)
#18     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1014:10)
#19     DeclarationResolver.visitMethodDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:366:13)
#20     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:543:13)
#21     DeclarationResolver.visitMethodDeclaration (package:analyzer/src/generated/declaration_resolver.dart:365:5)
#22     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7686:49)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#24     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#25     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:690:10)
#26     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:89:13)
#27     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:543:13)
#28     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:88:5)
#29     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#30     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#31     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#32     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#33     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#34     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:51:12)
#35     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#36     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#37     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#38     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:13)
#39     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#40     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#41     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#42     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#43     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#44     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#45     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1025:23)
<asynchronous suspension>
#46     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#47     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#48     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#49     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#50     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#51     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#52     _rootRun (dart:async/zone.dart:1124:13)
#53     _CustomZone.run (dart:async/zone.dart:1021:19)
#54     _runZoned (dart:async/zone.dart:1516:10)
#55     runZoned (dart:async/zone.dart:1463:12)
#56     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#57     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#58     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#59     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#60     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#61     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#62     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1540634912731 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1540634911690}
1540634912734 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1540634912734 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["D:\\GitHub\\nudges_flutter"],"excluded":["D:\\GitHub\\nudges_flutter\\.idea","D:\\GitHub\\nudges_flutter\\.dart_t
1540634912734 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["D:\\GitHub\\nudges_flutter\\lib\\tabs_page.dart"]},"clientRequestTime":1540634911875}
1540634912735 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["D:\\GitHub\\nudges_flutter\\lib\\tabs_page.dart"],"CLOSING_LABELS":["D:\\GitHub\\nudges_flutter
1540634912739 <= {"id":"1"}
1540634912762 <= {"id":"2"}
1540634913004 <= {"event":"analysis.errors","params":{"file":"D:\\GitHub\\nudges_flutter\\pubspec.yaml","errors":[]}}
1540634913655 => {"id":"6","method":"edit.listPostfixCompletionTemplates","clientRequestTime":1540634913654}
1540634913851 <= {"id":"3"}
1540634913856 <= {"id":"4"}
1540634913876 <= {"id":"5"}
1540634913876 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540634918015 <= {"id":"6","result":{"templates":[{"name":"assert","key":".assert","example":"expr.assert -> assert(expr);"},{"name":"fori","key":".fori","example":"limit.fori -> for(var i = 0; i < li
1540634918216 <= {"event":"analysis.errors","params":{"file":"D:\\GitHub\\nudges_flutter\\lib\\findgroups_page.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"D:\\GitHub\\nudges_f
1540634918233 <= {"event":"analysis.errors","params":{"file":"D:\\GitHub\\nudges_flutter\\lib\\login_page.dart","errors":[]}}
1540634918243 <= {"event":"analysis.errors","params":{"file":"D:\\GitHub\\nudges_flutter\\lib\\main.dart","errors":[]}}
1540634918251 <= {"event":"analysis.errors","params":{"file":"D:\\GitHub\\nudges_flutter\\lib\\mygroups_page.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"D:\\GitHub\\nudges_flu
1540634919677 <= {"event":"analysis.errors","params":{"file":"D:\\GitHub\\nudges_flutter\\test\\widget_test.dart","errors":[]}}
1540634919761 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1540634979030 => {"id":"7","method":"edit.getAssists","params":{"file":"D:\\GitHub\\nudges_flutter\\lib\\tabs_page.dart","offset":634,"length":0},"clientRequestTime":1540634979030}
1540634979039 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540634979276 <= {"id":"7","result":{"assists":[]}}
1540634979288 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1540634980501 => {"id":"8","method":"analysis.updateContent","params":{"files":{"D:\\GitHub\\nudges_flutter\\lib\\tabs_page.dart":{"type":"add","content":"import 'package:flutter/material.dart';\nimpo
1540634980517 <= {"id":"8","result":{}}
1540634980518 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540634980771 => {"id":"9","method":"analysis.updateContent","params":{"files":{"D:\\GitHub\\nudges_flutter\\lib\\tabs_page.dart":{"type":"add","content":"import 'package:flutter/material.dart';\nimpo
1540634980772 => {"id":"10","method":"completion.getSuggestions","params":{"file":"D:\\GitHub\\nudges_flutter\\lib\\tabs_page.dart","offset":622},"clientRequestTime":1540634980772}
1540634980805 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: D:\\GitHub\\nudges_flutter\\lib\\tabs_page.dart context: exception_20181027_120940_739","stackTrace":"Exc
```
`
```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: D:\GitHub\nudges_flutter\lib\tabs_page.dart context: exception_20181027_120940_739
Exception: Element not found in summary: package:nudges_flutter/tabs_page.dart

**Comment by Navil** [comment]
I actually managed to fix it myself. I didn't close all my brackets. It still compiled tho.
