### ISSUE TITLE
Dart Analyzer eats ram and crashes when analyzing code containing Future

### ISSUE THREAD

**Issue by linusaarnio** [dart-lang/sdk#35001]
Dart SDK Version : Dart 2.1.0-dev.5.0.flutter-a2eb050044
Flutter : 0.9.4
Os : Linux Mint 19 Tara
Editors: -VScode 1.28.2
             -Android Studio 3.1.4

A few seconds after I write the following code: 
```
 <Future<List<Unit>> getUnits(String category) async{

  }
```

The Analyzer first gets really resource intense, slowing my system to a crawl for about 1-2 minutes and then crashes showing first the following error message a few times: 

[13:23:02 GMT+0100 (CET)] [General] [Error] [Analyzer] Exhausted heap space, trying to allocate 8598323216 bytes.
```
[13:23:02 GMT+0100 (CET)] [General] [Error] [Analyzer] Captured exception
[13:23:02 GMT+0100 (CET)] [General] [Error] [Analyzer] Out of Memory
#0      new Uint8List (dart:typed_data/runtime/libtyped_data_patch.dart:2169:66)
#1      new ByteData (dart:typed_data/runtime/libtyped_data_patch.dart:41:22)
#2      _UnitApiSignatureComputer.addTokens (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:121:361)
#3      _UnitApiSignatureComputer.addClassOrMixin (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:43:9)
#4      _UnitApiSignatureComputer.compute (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:105:9)
#5      computeUnlinkedApiSignature (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:15:12)
#6      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:437:31)
#7      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#8      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:435:24)
#9      FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:222:32)
#10     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#11     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:218:20)
#12     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:291:9)
#13     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:899:22)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:778:12269)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#19     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.runGuarded (dart:async/zon…
```

And then:

```
[13:23:05 GMT+0100 (CET)] [General] [Error] This socket is closed
Error: This socket is closed
	at Socket._writeGeneric (net.js:726:18)
	at Socket._write (net.js:786:8)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at Socket.Writable.write (_stream_writable.js:290:11)
	at Socket.write (net.js:704:40)
	at Analyzer.sendMessage (/home/linus/.vscode/extensions/dart-code.dart-code-2.19.0/out/src/services/stdio_service.js:64:28)
	at Analyzer.sendMessage (/home/linus/.vscode/extensions/dart-code.dart-code-2.19.0/out/src/analysis/analyzer.js:113:19)
	at Promise (/home/linus/.vscode/extensions/dart-code.dart-code-2.19.0/out/src/services/stdio_service.js:59:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/home/linus/.vscode/extensions/dart-code.dart-code-2.19.0/out/src/services/stdio_service.js:48:16)
	at Analyzer.analysisGetHover (/home/linus/.vscode/extensions/dart-code.dart-code-2.19.0/out/src/analysis/analyzer_gen.js:297:21)
	at Promise (/home/linus/.vscode/extensions/dart-code.dart-code-2.19.0/out/src/providers/dart_hover_provider.js:14:27)
	at new Promise (<anonymous>)
	at DartHoverProvider.provideHover (/home/linus/.vscode/extensions/dart-code.dart-code-2.19.0/out/src/providers/dart_hover_provider.js:13:16)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:500:127
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:108:368
	at new n.Class.derive._oncancel (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:85:776)
	at Object.t.asThenable (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:108:333)
	at e.provideHover (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:500:86)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:514:826
	at e._withAdapter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:512:91)
	at e.$provideHover (/usr/share/code/resources/app/out/vs/workbenc…
```

This happens in both Android Studio and VSCode.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.1.0; please re-open if you see this in a recent version of Dart/Flutter.
