### ISSUE TITLE
file_lock_test flaky on vm-kernel-win-release-ia32

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#35012]
```
FAILED: dartk-vm release_ia32 standalone_2/io/file_lock_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 25.000487s):
set DART_CONFIGURATION=ReleaseIA32 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseIA32\crashpad_handler.exe & out\ReleaseIA32\dart.exe --sync-async --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\tests\standalone_2\io\file_lock_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done
Client failed, exit code -1073741816
  stdout:
LOCK FAILED


  stderr:

  arguments:
[--sync-async, --ignore-unrecognized-flags, --packages=C:\b\s\w\ir\.packages, C:\b\s\w\ir\tests\standalone_2\io\file_lock_script.dart, C:\b\s\w\ittd1az_\dart_file_lock3a79de73-dd4f-11e8-87d2-cb9eda44d122\file, EXCLUSIVE, 9, -1]

stderr:
Unhandled exception:
Expect.fail('Client subprocess exit code: -1073741816')
#0      Expect._fail (package:expect/expect.dart:651:5)
#1      Expect.fail (package:expect/expect.dart:269:5)
#2      check.<anonymous closure> (file:///C:/b/s/w/ir/tests/standalone_2/io/file_lock_test.dart:36:14)
#3      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#8      Future.wait.<anonymous closure> (dart:async/future.dart:399:22)
#9      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m release -a ia32 -n dartk-win-release-ia32 standalone_2/io/file_lock_test
```

**Comment by alexmarkov** [comment]
@mraleph pointed out that termination with exit code -1073741816 without any diagnostic could be related to https://github.com/dart-lang/sdk/issues/34888.
