### ISSUE TITLE
Parser crash on bad function type syntax

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#35035]
This (reasonable) attempt at writing a function type taking a named parameter:
```dart
void Function({obj: Object}) x;
```
crashes the parser with this output:
```
junk/function_type_crash.dart:2:19: Error: Expected an identifier, but got ':'.
void Function({obj: Object}) x;
                  ^
junk/function_type_crash.dart:2:19: Error: Can't have a default value in a function type.
void Function({obj: Object}) x;
                  ^
Unhandled exception:
Crash when compiling file:///usr/local/google/home/askesc/dart-sdk/sdk/junk/function_type_crash.dart,
at character offset null:
type 'ParserRecovery' is not a subtype of type 'Identifier'
#0      BodyBuilder.handleValuedFormalParameter (package:front_end/src/fasta/kernel/body_builder.dart:2684:16)
#1      Parser.parseFormalParameter (package:front_end/src/fasta/parser/parser.dart:1424:16)
#2      Parser.parseOptionalNamedParameters (package:front_end/src/fasta/parser/parser.dart:1512:11)
#3      Parser.parseFormalParameters (package:front_end/src/fasta/parser/parser.dart:1182:17)
#4      Parser.parseFormalParametersRequiredOpt (package:front_end/src/fasta/parser/parser.dart:1156:12)
#5      ComplexTypeInfo.parseType (package:front_end/src/fasta/parser/type_info_impl.dart:389:22)
#6      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2231:28)
#7      Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2198:12)
#8      Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2055:12)
#9      DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:843:22)
#10     DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:654:5)
#11     DietListener.endTopLevelFields (package:front_end/src/fasta/source/diet_listener.dart:315:5)
#12     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2248:16)
#13     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2198:12)
#14     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:481:14)
#15     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#16     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:253:14)
<asynchronous suspension>
#17     Loader.buildBodies (package:front_end/src/fasta/loader.dart:182:15)
<asynchronous suspension>
#18     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:307:20)
<asynchronous suspension>
#19     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#20     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:305:12)
<asynchronous suspension>
#21     CompileTask.compile (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:260:28)
<asynchronous suspension>
#22     compile.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:213:25)
<asynchronous suspension>
#23     withGlobalOptions.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:458:13)
#24     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:132:20)
<asynchronous suspension>
#25     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#33     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:130:10)
#34     withGlobalOptions (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:451:26)
#35     compile.<anonymous closure> (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:206:18)
<asynchronous suspension>
#36     runProtectedFromAbort (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:506:24)
<asynchronous suspension>
#37     compile (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:205:16)
<asynchronous suspension>
#38     compileEntryPoint (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:69:11)
<asynchronous suspension>
#39     main (file:///usr/local/google/home/askesc/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#40     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by peter-ahe-google** [comment]
Proposed fix https://dart-review.googlesource.com/c/sdk/+/82984

**Comment by reinaldomoreira** [comment]
Version 1.17 occurring this problem while debugging

**Comment by askeksa-google** [comment]
This is a different situation from the original issue. The stack trace seems to indicate something around a constructor call. Can you provide some code that reproduces the crash?
