### ISSUE TITLE
Dart analysis server crash during flutter tutorial part 2

### ISSUE THREAD

**Issue by chandler37** [dart-lang/sdk#35045]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1440x900  Retina`

# Exception

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: //AndroidStudioProjects/immaculater/lib/main.dart
Exception: Element not found in summary: package:flutter/src/painting/text_style.dart;package:flutter/src/painting/text_style.dart;StatefulWidget
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:308:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:345:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:35:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:111:29)
#4      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:983:24)
#5      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:929:15)
#6      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:954:15)
#7      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1367:28)
#8      _UnitResynthesizer.buildLinkedType (package:analyzer/src/summary/resynthesize.dart:1320:12)
#9      SummaryResynthesizerContext.resolveLinkedType (package:analyzer/src/summary/resynthesize.dart:451:30)
#10     NonParameterVariableElementImpl.type (package:analyzer/src/dart/element/element.dart:7242:12)
#11     PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:8231:18)
#12     DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/declaration_resolver.dart:476:56)
#13     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11481:15)
#14     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4387:17)
#15     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:834:10)
#16     DeclarationResolver.visitFieldDeclaration (package:analyzer/src/generated/declaration_resolver.dart:197:11)
#17     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4382:49)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#19     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#20     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:690:10)
#21     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:89:13)
#22     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:543:13)
#23     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:88:5)
#24     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#26     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#27     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#28     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#29     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:51:12)
#30     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#31     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#32     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#33     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:13)
#34     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#35     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#36     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#37     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#38     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#39     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#40     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1025:23)
<asynchronous suspension>
#41     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#42     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#43     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#44     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#45     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#46     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#47     _rootRun (dart:async/zone.dart:1124:13)
#48     _CustomZone.run (dart:async/zone.dart:1021:19)
#49     _runZoned (dart:async/zone.dart:1516:10)
#50     runZoned (dart:async/zone.dart:1463:12)
#51     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#52     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#53     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#54     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#55     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#56     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#57     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1541271369382 => {"id":"520","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".assert"},"client
1541271369468 <= {"id":"519","result":{"value":false}}
1541271369483 => {"id":"521","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".for"},"clientReq
1541271369587 => {"id":"522","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".switch"},"client
1541271369596 <= {"id":"520","result":{"value":false}}
1541271369698 => {"id":"523","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".null"},"clientRe
1541271369731 <= {"id":"521","result":{"value":false}}
1541271369732 <= {"id":"522","result":{"value":false}}
1541271369803 => {"id":"524","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".nn"},"clientRequ
1541271369867 <= {"id":"523","result":{"value":false}}
1541271369907 => {"id":"525","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":"!"},"clientReques
1541271369994 <= {"id":"524","result":{"value":false}}
1541271370009 => {"id":"526","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".not"},"clientReq
1541271370115 => {"id":"527","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".tryon"},"clientR
1541271370153 <= {"id":"525","result":{"value":false}}
1541271370227 => {"id":"528","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".par"},"clientReq
1541271370281 <= {"id":"526","result":{"value":false}}
1541271370281 <= {"id":"527","result":{"value":false}}
1541271370290 <= {"id":"528","result":{"value":false}}
1541271370291 => {"id":"529","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".else"},"clientRe
1541271370297 <= {"id":"529","result":{"value":false}}
1541271370297 => {"id":"530","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".iter"},"clientRe
1541271370302 <= {"id":"530","result":{"value":false}}
1541271370302 => {"id":"531","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".notnull"},"clien
1541271370307 <= {"id":"531","result":{"value":false}}
1541271370307 => {"id":"532","method":"edit.isPostfixCompletionApplicable","params":{"file":"//AndroidStudioProjects/immaculater/lib/main.dart","offset":460,"key":".fori"},"clientRe
1541271370312 <= {"id":"532","result":{"value":false}}
1541271370314 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1541271370433 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1541271370449 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: //AndroidStudioProjects/immaculater/lib/main.dart","stackTrace":"Exception: Element no
```

Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: //AndroidStudioProjects/immaculater/lib/main.dart
Exception: Element not found in summary: package:flutter/src/painting/text_style.dart

**Comment by chandler37** [comment]
Fixed with 'flutter channel dev; flutter upgrade' to the following:

Analysis server version: 1.20.5

Dart SDK: 2.1.0-dev.8.0.flutter-bf26f760b1 (Thu Oct 25 07:36:06 2018 +0000) on "macos_x64"
