### ISSUE TITLE
type '_PhysicalFolder' is not a subtype of type 'File' in ContextManagerImpl

### ISSUE THREAD

**Issue by Aragorn450** [dart-lang/sdk#35050]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I am using Windows 10 and I opened VSCode up for the second time after installing Dart Code and the Flutter extension. VSCode also looks to have updated Dart Code to v2.20.0.

### Request

While responding to request: `analysis.setAnalysisRoots`

### Versions

- Flutter SDK 0.9.4
- Visual Studio Code 1.28.2
- Dart Code 2.20.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\Development\tools\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.20.0
```

### Exception

type '_PhysicalFolder' is not a subtype of type 'File'

```text
#0      ContextManagerImpl._findPackageSpecFile (package:analysis_server/src/context_manager.dart:1245:5)
#1      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1142:24)
#2      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1160:13)
#3      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:742:9)
#4      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:933:22)
#5      AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:395:14)
#6      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:309:16)
#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:750:45)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#9      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:746:50)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1500:12)
#14     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:745:5)
#15     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#17     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#18     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#49     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#50     _StreamController._add (dart:async/stream_controller.dart:639:7)
#51     _StreamController.add (dart:async/stream_controller.dart:585:5)
#52     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#53     _rootRunUnary (dart:async/zone.dart:1136:13)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#58     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#59     _StreamController._add (dart:async/stream_controller.dart:639:7)
#60     _StreamController.add (dart:async/stream_controller.dart:585:5)
#61     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#62     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#63     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#64     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#65     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#66     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "C:\\Development\\GitHub\\Simpleview",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment]
We haven't seen this crash in a while, so closing as stale. Please file a new issue if you hit this on a recent version of Dart.
