### ISSUE TITLE
language_2/vm/mult_int_test fails on dartkp-simarm64-windows

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#35091]
The language_2/vm/mult_int_test started to fail from [this build](https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/vm-kernel-precomp-win-release-simarm64/1204), see [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8930555936459488368/+/steps/vm_tests_shard_1_on_Windows/0/stdout):

```

FAILED: dartkp-dart_precompiled release_simarm64 language_2/vm/mult_int_test
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 02.000484s):
set DART_CONFIGURATION=ReleaseSIMARM64 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseSIMARM64\crashpad_handler.exe & C:\b\s\w\ir\pkg\vm\tool\gen_kernel.bat --aot --platform=out/ReleaseSIMARM64/vm_platform_strong.dill -o C:\b\s\w\ir\out\ReleaseSIMARM64\generated_compilations\dartkp\tests_language_2_vm_mult_int_test\out.dill C:\b\s\w\ir\tests\language_2\vm\mult_int_test.dart --packages=C:\b\s\w\ir\.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "precompiler" (took 03.000593s):
set DART_CONFIGURATION=ReleaseSIMARM64 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseSIMARM64\crashpad_handler.exe & out\ReleaseSIMARM64\gen_snapshot --snapshot-kind=app-aot-blobs --blobs_container_filename=C:/b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp/tests_language_2_vm_mult_int_test/out.aotsnapshot --no_background_compilation --sync-async --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\out\ReleaseSIMARM64\generated_compilations\dartkp\tests_language_2_vm_mult_int_test\out.dill

exit code:
0

--- Command "remove_kernel_file" (took 15ms):
set DART_CONFIGURATION=ReleaseSIMARM64 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseSIMARM64\crashpad_handler.exe & cmd.exe /c del C:\b\s\w\ir\out\ReleaseSIMARM64\generated_compilations\dartkp\tests_language_2_vm_mult_int_test\out.dill

exit code:
0

--- Command "vm" (took 234ms):
set DART_CONFIGURATION=ReleaseSIMARM64 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseSIMARM64\crashpad_handler.exe & out\ReleaseSIMARM64\dart_precompiled_runtime.exe --no_background_compilation --optimization_counter_threshold=10 --sync-async --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:/b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp/tests_language_2_vm_mult_int_test/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <-30064771072>, actual: <0>) fails.
#0      Expect._fail (package:expect/expect.dart:651)
#1      Expect.equals (package:expect/expect.dart:124)
#2      doVars (file:///C:/b/s/w/ir/tests/language_2/vm/mult_int_test.dart:83)
#3      main (file:///C:/b/s/w/ir/tests/language_2/vm/mult_int_test.dart:97)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171)

--- Re-run this test:
python tools/test.py -m release -a simarm64 -n dartkp-win-release-simarm64 language_2/vm/mult_int_test
```

I don't have a windows machine atm, so I cannot look more into this.

There were only 3 commits in the first build failure, namely 1dabf0d1, cde47930, 331472ec where only cde47930 seems relevant.

@aartbik Could this be related to optimizations you were doing recently?

**Comment by aartbik** [comment]
The revert for https://github.com/flutter/flutter/issues/23879 was a temporary measure, since I suspect it was masking a pre-existing bug in the code someplace. This failure may actually indicate that it indeed shows up elsewhere.
