### ISSUE TITLE
Crash in libintegers_patch `Invalid radix-16 number` on ios

### ISSUE THREAD

**Issue by MarcelEdward2** [dart-lang/sdk#35136]
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following FormatException was thrown during a platform message callback:
flutter: Invalid radix-16 number
flutter: ffffffffcec5f4fa
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      int._throwFormatException (dart:core/runtime/libintegers_patch.dart:130:5)
flutter: #1      int._parse (dart:core/runtime/libintegers_patch.dart:104:14)
flutter: #2      int.parse (dart:core/runtime/libintegers_patch.dart:61:12)
flutter: #3      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:396:22)
flutter: #4      FirestoreMessageCodec.readValueOfType (file:///Users/macbook/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+1/lib/src/firestore_message_codec.dart:98:22)
flutter: #5      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:365:12)
flutter: #6      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:432:39)
flutter: #7      FirestoreMessageCodec.readValueOfType (file:///Users/macbook/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+1/lib/src/firestore_message_codec.dart:98:22)
flutter: #8      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:365:12)
flutter: #9      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:432:39)
flutter: #10     FirestoreMessageCodec.readValueOfType (file:///Users/macbook/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+1/lib/src/firestore_message_codec.dart:98:22)
flutter: #11     StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:365:12)
flutter: #12     StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:425:23)
flutter: #13     FirestoreMessageCodec.readValueOfType (file:///Users/macbook/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+1/lib/src/firestore_message_codec.dart:98:22)
flutter: #14     StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:365:12)
flutter: #15     StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:432:39)
flutter: #16     FirestoreMessageCodec.readValueOfType (file:///Users/macbook/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+1/lib/src/firestore_message_codec.dart:98:22)
flutter: #17     StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:365:12)
flutter: #18     StandardMethodCodec.decodeMethodCall (package:flutter/src/services/message_codecs.dart:514:44)
flutter: #19     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:329:35)
flutter: <asynchronous suspension>
flutter: #20     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:299:54)
flutter: #21     BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)
flutter: <asynchronous suspension>
flutter: #22     _invoke3 (dart:ui/hooks.dart:187:13)
flutter: #23     _dispatchPlatformMessage (dart:ui/hooks.dart:96:5)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/21313#issuecomment-437154233

**Comment by lrhn** [comment]
This is actually working as intended. The value of hexadecimal ffffffffcec5f4fa is too large to fit in an integer.
The current error message is;
```
FormatException: Positive input exceeds the limit of integer
ffffffffcec5f4fa
```

We could consider allowing values that are valid unsigned 64-bit integers, like we do for literals.
