### ISSUE TITLE
dartfmt crash: type 'MethodInvocationImpl' is not a subtype of type 'SimpleIdentifier' in type cast

### ISSUE THREAD

**Issue by dhil** [dart-lang/sdk#35151]
The `dartfmt` tool crashes on the following program using the bleeding edge SDK
```dart
class A {
  A() : super.a = 42;
}
```
Trace:
```
Hit a bug in the formatter when formatting bug.dart.
Please report at github.com/dart-lang/dart_style/issues.
type 'MethodInvocationImpl' is not a subtype of type 'SimpleIdentifier' in type cast
#0      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:633:28)
#1      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2393:14)
#2      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2369:14)
#3      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3010:13)
#4      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2895:15)
#5      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2700:15)
#6      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1710:13)
#7      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1670:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:565:14)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:457:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#11     ParserAdapter.parseCompilationUnit2 (file:///usr/local/google/home/hillerstrom/projects/dart-sdk/sdk/pkg/analyzer/lib/src/generated/parser_fasta.dart:150:32)
#12     ParserAdapter.parseCompilationUnit (file:///usr/local/google/home/hillerstrom/projects/dart-sdk/sdk/pkg/analyzer/lib/src/generated/parser_fasta.dart:145:12)
#13     DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:119:21)
#14     processFile (package:dart_style/src/io.dart:77:28)
#15     formatPaths (file:///usr/local/google/home/hillerstrom/projects/dart-sdk/sdk/third_party/pkg_tested/dart_style/bin/format.dart:261:12)
#16     main (file:///usr/local/google/home/hillerstrom/projects/dart-sdk/sdk/third_party/pkg_tested/dart_style/bin/format.dart:189:5)
#17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by bwilkerson** [comment]
While the analyzer should not crash when given invalid code, I'll point out that this code is invalid. It is not possible to initialize an inherited field in the initializer list of a constructor.

@danrubel This appears to be an issue with the way the parser recovers. Ideally I'd like to see us issue a single error to the effect that instance fields cannot be initialized outside their declaring class, but I'm not sure how to prevent follow-on errors. Perhaps we should just fix the crash and worry about cleaning up the extra errors in a latter phase. (In which case, I think the right answer is for "super.a" to be parsed so as to produce a `PropertyAccess`.)
