### ISSUE TITLE
InconsistentAnalysisException not caught in OverrideContributor

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#35169]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.5107.16`
- `2.1.0-edge.f6128b48b6272687434874961efb142dfad4ce92`
- `IC-182.5107.16, JRE 1.8.0_152-release-1248-b22x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/_z/xg4j4cl517zc6rm212d2pjsc003j4q/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.f6128b48b6272687434874961efb142dfad4ce92, server version 1.21.1, error: Failed to handle completion domain request: {id: 3483, method: completion.getSuggestions, params: {file: /Users/brianwilkerson/src/dart/sdk/sdk/pkg/analyzer/lib/src/hint/sdk_constraint_verifier.dart, offset: 2073}, clientRequestTime: 1542223546407}
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:201:7)
#1      AnalysisSessionImpl.getResolvedUnit (package:analyzer/src/dart/analysis/session.dart:166:5)
#2      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:57:47)
<asynchronous suspension>
#3      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:68:41)
<asynchronous suspension>
#4      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:46:18)
#5      OverrideContributor._buildReplacementText (package:analysis_server/src/services/completion/dart/override_contributor.dart:80:19)
<asynchronous suspension>
#6      OverrideContributor._buildSuggestion (package:analysis_server/src/services/completion/dart/override_contributor.dart:102:39)
<asynchronous suspension>

**Comment by DanTup** [comment]
I've seen this a lot today (in Flutter master) when I'm typing and completion is open (which is almost all the time, it's opened quite aggressively in VS Code). We currently surface server errors to users (encouraging them to send an error report) so it's quite visible.

**Comment by bwilkerson** [comment]
I believe that this CL should fix the problem: https://dart-review.googlesource.com/c/sdk/+/88222.
