### ISSUE TITLE
dartdevc.bat --k fails on Windows 10

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#35171]
```
[C:\Users\timsneath] \users\timsneath\Downloads\dartsdk-windows-x64-release\dart-sdk\bin\dartdevc.bat --kernel
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk=C:\Users\timsneath\Downloads\dartsdk-windows-x64-release\dart-sdk
    dart --version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"

FormatException: Could not find an option named "dart-sdk".
#0      Parser.validate (package:args/src/parser.dart:261:21)
#1      Parser.parseLongOption (package:args/src/parser.dart:250:7)
#2      Parser.parse (package:args/src/parser.dart:90:11)
#3      ArgParser.parse (package:args/src/arg_parser.dart:307:45)
#4      _compile (package:dev_compiler/src/kernel/command.dart:87:30)
<asynchronous suspension>
#5      compile (package:dev_compiler/src/kernel/command.dart:37:18)
<asynchronous suspension>
#6      compile (package:dev_compiler/src/compiler/shared_command.dart:357:12)
#7      main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:32:24)
<asynchronous suspension>
#8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:285:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by matanlurey** [comment]
Are you using this via a build system, or directly? It's not supported directly AFAIK.

/cc @natebosch

**Comment by natebosch** [comment]
It's probably possible to invoke it directly as long as you aren't looking for a modular output. I'm that case it isn't super useful but should be doable. In general though the build_runner approach is the supported way, and it's the way to get modular output.

**Comment by timsneath** [comment]
Thanks Matan!

Jenny is looking into this. I was smoke testing on Windows 10. Didn't have a specific use case in mind.
