### ISSUE TITLE
Crash in Fasta

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#35177]
This code crashes when run with the VM:
```dart
main() {
 dynamic Function() f;
 (f)()<int>();
}
```
The parentheses around `f` is needed to trigger the crash, so is the type argument.
The `dynamic` is not important, replacing it with a correct type like `void Function<T>()` does not remove the crash.

The stack trace starts with:
```
Crash when compiling funtest.dart,
at character offset 7:
type 'List<UnresolvedType<KernelTypeBuilder>>' is not a subtype of type 'Arguments' #0      BodyBuilder.handleSend (package:front_end/src/fasta/kernel/body_builder.dart:1162:15)
#1      Parser.parseArgumentOrIndexStar (package:front_end/src/fasta/parser/parser.dart:3947:18)
#2      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3755:21)
#3      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3681:13)
#4      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3646:13)
#5      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:4894:16)
#6      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:4854:12)
#7      Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3550:14)
#8      Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3469:20)
#9      Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3374:15)
#10     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:826:14)
#11     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:303:5)
#12     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2289:14)
#13     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2190:14)
#14     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:481:14)
```

**Comment by peter-ahe-google** [comment]
I believe this is a bug in the parser. In `parseArgumentOrIndexStar` we call `typeArg.parseArguments` after calling `parseArguments`.

The code in question is supposedly handling this case:

`a(b)<T>(c)`

However, this example doesn't trigger the above code.
