### ISSUE TITLE
crash on standalone_2/http_launch_test on dartk-win-debug-x64

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#35193]
```
AILED: dartk-vm debug_x64 standalone_2/http_launch_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 14.000647s):
set DART_CONFIGURATION=DebugX64 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64\crashpad_handler.exe & out\DebugX64\dart.exe --no-background-compilation --sync-async --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\tests\standalone_2\http_launch_test.dart

exit code:
255

stdout:
Exit code for process 2 = -2147483645
---stdout:---

---stderr:---

---

stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <-2147483645>) fails.
#0      Expect._fail (package:expect/expect.dart:651:5)
#1      Expect.equals (package:expect/expect.dart:124:5)
#2      checkResults (file:///C:/b/s/w/ir/tests/standalone_2/http_launch_test.dart:83:12)
#3      serverRunning.<anonymous closure> (file:///C:/b/s/w/ir/tests/standalone_2/http_launch_test.dart:69:5)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#9      Future.wait.<anonymous closure> (dart:async/future.dart:403:22)
#10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#15     Future.wait.<anonymous closure> (dart:async/future.dart:403:22)
#16     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m debug -n dartk-win-debug-x64 --write-logs standalone_2/http_launch_test
```

**Comment by mraleph** [comment]
We had a crashdump but did not archive it. I am going to improve crash dump archiving to handle nested processes as well.
