### ISSUE TITLE
RangeError (offset): Invalid value: Not in range 0..1027, inclusive: 1350

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#35215]
I tried to build an app and this happened:

```
Unhandled exception:
Crash when compiling file:///home/ianh/dev/cruisemonkey/lib/src/views/seamail.dart,
at character offset 294:
RangeError (offset): Invalid value: Not in range 0..1027, inclusive: 1350
#0      RangeError.checkValueInInterval (dart:core/errors.dart:280:7)
#1      Source.getLocation (package:kernel/ast.dart:5704:16)
#2      Component.getLocation (package:kernel/ast.dart:5473:31)
#3      _getLocationInComponent (package:kernel/ast.dart:5819:22)
#4      Constructor._getLocationInEnclosingFile (package:kernel/ast.dart:1392:12)
#5      TreeNode.location (package:kernel/ast.dart:165:12)
#6      BodyBuilder.throwNoSuchMethodError (package:front_end/src/fasta/kernel/body_builder.dart:1362:27)
#7      BodyBuilder.buildStaticInvocation (package:front_end/src/fasta/kernel/body_builder.dart:3012:16)
#8      BodyBuilder.buildConstructorInvocation (package:front_end/src/fasta/kernel/body_builder.dart:3325:24)
#9      _KernelTypeUseGenerator&KernelReadOnlyAccessGenerator&TypeUseGenerator.invokeConstructor (package:front_end/src/fasta/kernel/expression_generator.dart:636:19)
#10     BodyBuilder.buildConstructorReferenceInvocation (package:front_end/src/fasta/kernel/body_builder.dart:3227:17)
#11     BodyBuilder.endNewExpression (package:front_end/src/fasta/kernel/body_builder.dart:3210:5)
#12     Parser.parseNewExpression (package:front_end/src/fasta/parser/parser.dart:4387:14)
#13     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3976:16)
#14     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3895:12)
#15     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3707:13)
#16     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3679:13)
#17     Parser.parseExpressionFunctionBody (package:front_end/src/fasta/parser/parser.dart:3392:13)
#18     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3322:14)
#19     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3205:13)
#20     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3137:13)
#21     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4038:16)
#22     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3997:14)
#23     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3895:12)
#24     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3707:13)
#25     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3679:13)
#26     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4669:15)
#27     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4626:14)
#28     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4605:13)
#29     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4339:12)
#30     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3956:14)
#31     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3895:12)
#32     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3707:13)
#33     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3679:13)
#34     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4669:15)
#35     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4626:14)
#36     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4605:13)
#37     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4339:12)
#38     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3956:14)
#39     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3748:21)
#40     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3679:13)
#41     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3644:13)
#42     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:4892:16)
#43     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3477:14)
#44     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3467:20)
#45     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3372:15)
#46     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3205:13)
#47     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3137:13)
#48     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4038:16)
#49     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3997:14)
#50     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3895:12)
#51     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3707:13)
#52     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3679:13)
#53     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4669:15)
#54     Parser.parseConstructorInvocationArguments (package:front_end/src/fasta/parser/parser.dart:4372:13)
#55     Parser.parseNewExpression (package:front_end/src/fasta/parser/parser.dart:4386:13)
#56     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3976:16)
#57     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3895:12)
#58     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3707:13)
#59     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3679:13)
#60     Parser.parseReturnStatement (package:front_end/src/fasta/parser/parser.dart:3585:13)
#61     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3483:14)
#62     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3467:20)
#63     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3372:15)
#64     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3205:13)
#65     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3137:13)
#66     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4038:16)
#67     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3997:14)
#68     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3895:12)
#69     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3707:13)
#70     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3679:13)
#71     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4669:15)
#72     Parser.parseConstructorInvocationArguments (package:front_end/src/fasta/parser/parser.dart:4372:13)
#73     Parser.parseNewExpression (package:front_end/src/fasta/parser/parser.dart:4386:13)
#74     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3976:16)
#75     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3895:12)
#76     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3707:13)
#77     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3679:13)
#78     Parser.parseReturnStatement (package:front_end/src/fasta/parser/parser.dart:3585:13)
#79     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3483:14)
#80     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3467:20)
#81     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3372:15)
#82     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3205:13)
#83     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3137:13)
#84     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4038:16)
#85     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3997:14)
#86     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3895:12)
#87     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3707:13)
#88     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3679:13)
#89     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4669:15)
#90     Parser.parseConstructorInvocationArguments (package:front_end/src/fasta/parser/parser.dart:4372:13)
#91     Parser.parseNewExpression (package:front_end/src/fasta/parser/parser.dart:4386:13)
#92     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3976:16)
#93     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3895:12)
#94     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3707:13)
#95     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3679:13)
#96     Parser.parseReturnStatement (package:front_end/src/fasta/parser/parser.dart:3585:13)
#97     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3483:14)
#98     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3467:20)
#99     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3372:15)
#100    DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:826:14)
#101    DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:578:5)
#102    Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3030:14)
#103    Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2895:15)
#104    Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2700:15)
#105    Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1710:13)
#106    Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1670:14)
#107    Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:565:14)
#108    Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:457:14)
#109    Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#110    SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:253:14)
<asynchronous suspension>
#111    Loader.buildBodies (package:front_end/src/fasta/loader.dart:181:15)
<asynchronous suspension>
#112    KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:307:20)
<asynchronous suspension>
#113    withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#114    KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:305:12)
<asynchronous suspension>
#115    IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:257:26)
<asynchronous suspension>
#116    CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#117    new Future.sync (dart:async/future.dart:224:31)
#118    CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#119    _rootRun (dart:async/zone.dart:1124:13)
#120    _CustomZone.run (dart:async/zone.dart:1021:19)
#121    _runZoned (dart:async/zone.dart:1516:10)
#122    runZoned (dart:async/zone.dart:1463:12)
#123    CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#124    IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:108:20)
<asynchronous suspension>
#125    IncrementalCompiler.compile (package:vm/incremental_compiler.dart:47:44)
<asynchronous suspension>
#126    FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:336:67)
#127    new Future.<anonymous closure> (dart:async/future.dart:176:37)
#128    _rootRun (dart:async/zone.dart:1120:38)
#129    _CustomZone.run (dart:async/zone.dart:1021:19)
#130    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#131    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#132    _rootRun (dart:async/zone.dart:1124:13)
#133    _CustomZone.run (dart:async/zone.dart:1021:19)
#134    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#135    Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#136    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#137    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#138    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:834:7)
#1      DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:578:5)
#2      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3030:14)
#3      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2895:15)
#4      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2700:15)
#5      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1710:13)
#6      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1670:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:565:14)
#8      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:457:14)
#9      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#10     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:253:14)
<asynchronous suspension>
#11     Loader.buildBodies (package:front_end/src/fasta/loader.dart:181:15)
<asynchronous suspension>
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:307:20)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#14     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:305:12)
<asynchronous suspension>
#15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:257:26)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#17     new Future.sync (dart:async/future.dart:224:31)
#18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#24     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:108:20)
<asynchronous suspension>
#25     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:47:44)
<asynchronous suspension>
#26     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:336:67)
#27     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#28     _rootRun (dart:async/zone.dart:1120:38)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#36     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#37     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Compiler failed on /home/ianh/dev/cruisemonkey/lib/main.dart
 4.0s
```

I tried just running the compiler on that file alone and it didn't crash. I'll add more information if I can figure out what's causing the crash.

**Comment by Hixie** [comment]
It stopped crashing when I changed a constructor call from having one positional argument to having one named argument. (The constructor declaration wanted named arguments only.)

**Comment by peter-ahe-google** [comment]
I think I understand what the problem is. The constructor you were calling, was it defined in a `dart:` library?

If so, I can can reproduce the problem as I can see the location is messed up when I compile this program:

```
main() {
  new int.fromEnvironment("a", 1);
}
```

The candidate message refers to `runtime/lib/integers_patch.dart`, but it should refer to `.../core/int.dart` for the offset to be correct.

**Comment by peter-ahe-google** [comment]
I say I can reproduce the problem, although I can't reproduce the crash. However, as soon as we're referring to the wrong file, we may crash depending on the length of the file we incorrectly refer to.

**Comment by peter-ahe-google** [comment]
Scratch my above remarks. I can't yet reproduce the problem and I'm not sure what it is yet.

**Comment by jensjoha** [comment]
I have written a test of the incremental compiler that reproduces this.
Next up: the fix.
