### ISSUE TITLE
Formatting crashes the analysis server

### ISSUE THREAD

**Issue by miyoyo** [dart-lang/sdk#35227]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Format on save

### Request

While responding to request: `edit.format`

### Versions

- Flutter SDK 0.11.7-pre.53
- Visual Studio Code 1.29.1
- Dart Code 2.20.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\tools\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.20.0
```

### Exception

The formatter produced unexpected output. Input was:
```dart
import 'package:flutter/material.dart';

class HookableWidget extends StatefulWidget {
  @override
  _HookableWidgetState createState() => _HookableWidgetState();
}

class _HookableWidgetState extends State<HookableWidget> with Hooks {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

mixin Hooks<T extends StatefulWidget> on State<T> {
  var _hooks = <Hook<T>>[];
  set hooks(List<Hook<T>> h) => _hooks = h;

  @override
  void initState() {
    for (var hook in _hooks) {
      hook.initState();
    }
    super.initState();
  }

  @override
  void didChangeDependencies() {
    for (var hook in _hooks) {
      hook.didChangeDependencies();
    }
    super.didChangeDependencies();
  }

  @override
  void didUpdateWidget(T oldWidget) {
    for (var hook in _hooks) {
      hook.didUpdateWidget(oldWidget);
    }
    super.didUpdateWidget(oldWidget);
  }

  @override
  void reassemble() {
    for (var hook in _hooks) {
      hook.reassemble();
    }
    super.reassemble();
  }

  @override
  void deactivate() {
    for (var hook in _hooks) {
      hook.deactivate();
    }
    super.deactivate();
  }

  @override
  void dispose() {
    for (var hook in _hooks) {
      hook.dispose();
    }
    super.dispose();
  }
}

abstract class Hook<T extends StatefulWidget> {
  void initState();
  void didChangeDependencies();
  void didUpdateWidget(T oldWidget);
  void reassemble();
  void deactivate();
  void dispose();
}

class _Text {
  const Text();
  static const Gray5C = Color(0x5c5c5c); 
}

class MyColors { 
  static const Text = _Text();
}
```
Which formatted to:
```dart
import 'package:flutter/material.dart';

class HookableWidget extends StatefulWidget {
  @override
  _HookableWidgetState createState() => _HookableWidgetState();
}

class _HookableWidgetState extends State<HookableWidget> with Hooks {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

mixin Hooks<T extends StatefulWidget> on State<T> {
  var _hooks = <Hook<T>>[];
  set hooks(List<Hook<T>> h) => _hooks = h;

  @override
  void initState() {
    for (var hook in _hooks) {
      hook.initState();
    }
    super.initState();
  }

  @override
  void didChangeDependencies() {
    for (var hook in _hooks) {
      hook.didChangeDependencies();
    }
    super.didChangeDependencies();
  }

  @override
  void didUpdateWidget(T oldWidget) {
    for (var hook in _hooks) {
      hook.didUpdateWidget(oldWidget);
    }
    super.didUpdateWidget(oldWidget);
  }

  @override
  void reassemble() {
    for (var hook in _hooks) {
      hook.reassemble();
    }
    super.reassemble();
  }

  @override
  void deactivate() {
    for (var hook in _hooks) {
      hook.deactivate();
    }
    super.deactivate();
  }

  @override
  void dispose() {
    for (var hook in _hooks) {
      hook.dispose();
    }
    super.dispose();
  }
}

abstract class Hook<T extends StatefulWidget> {
  void initState();
  void didChangeDependencies();
  void didUpdateWidget(T oldWidget);
  void reassemble();
  void deactivate();
  void dispose();
}

class _Text {
  Text();
  static const Gray5C = Color(0x5c5c5c);
}

class MyColors {
  static const Text = _Text();
}
```

```text
#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:146:7)
#1      EditDomainHandler.format (package:analysis_server/src/edit/edit_domain.dart:132:35)
#2      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:353:16)
#3      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:645:45)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#5      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:641:50)
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1500:12)
#10     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:640:5)
#11     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#13     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#14     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#22     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#23     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#24     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#25     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#27     _rootRunUnary (dart:async/zone.dart:1132:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#35     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#36     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#37     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#38     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#45     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#46     _StreamController._add (dart:async/stream_controller.dart:639:7)
#47     _StreamController.add (dart:async/stream_controller.dart:585:5)
#48     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#49     _rootRunUnary (dart:async/zone.dart:1136:13)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#55     _StreamController._add (dart:async/stream_controller.dart:639:7)
#56     _StreamController.add (dart:async/stream_controller.dart:585:5)
#57     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#58     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#61     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "C:\\Users\\miyoyo\\projects\\redacted\\miyoyo\\test_project",
        "explicitFileCount": 4,
        "implicitFileCount": 972,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/dart_style#759

**Comment by munificent** [comment]
This is a bug in the front end that dartfmt uses:

```dart
class _Text {
  const Text();
  static const Gray5C = Color(0x5c5c5c); 
}
```

That constructor should be `_Text()`, but the code says `Text()`. So Dart sees that as just defining a method whose name is `Text`. But methods can't have `const` before them, so this code is erroneous. The front end isn't reporting an error and instead parses it as a method declaration (without the const) and hands it to the formatter.

The formatter outputs it as an abstract method declaration. Then it does a sanity check on its output to make sure it didn't discard any code, sees that `const` is missing, and blows up. So, two things should happen here:

1. The front end should *definitely* be reporting an error on this code.

2. It would be good if analysis_server caught UnexpectedOutputException from dartfmt and reporting it more gracefully instead of crashing.

**Comment by srawlins** [comment]
Apologies that we didn't get to this bug before it got stale. :/ Dart 2.2 is fairly old now and the bug should be fixed by now. Feel free to re-open if you encounter this on a recent version of Dart.
