### ISSUE TITLE
raw_datagram_read_all_test flaked on vm-kernel-mac-debug-simdbc64

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#35235]
raw_datagram_read_all_test flaked on vm-kernel-mac-debug-simdbc64: https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/vm-kernel-mac-debug-simdbc64/599:

```
stderr:
Unhandled exception:
Expect.isNull(actual: <Instance of 'Datagram'>) fails.
#0      Expect._fail (package:expect/expect.dart:651:5)
#1      Expect.isNull (package:expect/expect.dart:151:5)
#2      main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/raw_datagram_read_all_test.dart:33:18)
#3      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#4      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#5      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -m debug -a simdbc64 -n dartk-mac-debug-simdbc64 standalone_2/io/raw_datagram_read_all_test
```

**Comment by aam** [comment]
Now stable failure on reload bot https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-reload-linux-debug-x64/8606:
```
--- Command "vm" (took 05.000058s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --hot-reload-test-mode --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/io/raw_datagram_read_all_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.isNull(actual: <Instance of 'Datagram'>) fails.
#0      Expect._fail (package:expect/expect.dart:698:5)
#1      Expect.isNull (package:expect/expect.dart:159:5)
#2      main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/raw_datagram_read_all_test.dart:33:18)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartk-reload-linux-debug-x64 standalone_2/io/raw_datagram_read_all_test
```

**Comment by aam** [comment]
Similarly this failed on isolate-stress bot https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8840540285446276848/+/u/Run_Isolate_Stress_Tests_shard_4/task_stdout_stderr:_Run_Isolate_Stress_Tests_shard_4
```

Error(/b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/../../../tests/standalone_2/io/raw_datagram_read_all_test.dart): Expect.isNull(actual: <Instance of 'Datagram'>) fails. 
stack:#0      Expect._fail (package:expect/expect.dart:731)
#1      Expect.isNull (package:expect/expect.dart:159)
#2      main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/raw_datagram_read_all_test.dart:35)
#3      _rootRun (dart:async/zone.dart:1420)
#4      _CustomZone.run (dart:async/zone.dart:1328)
#5      _CustomZone.runGuarded (dart:async/zone.dart:1236)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
#7      _rootRun (dart:async/zone.dart:1428)
#8      _CustomZone.run (dart:async/zone.dart:1328)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```
