### ISSUE TITLE
Runtime exceptions for compile time errors are showing the source line twice

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#35239]
Runtime exceptions for compile time errors are showing the source line twice:

```
I/flutter (16788): The following _CompileTimeError was thrown building SeamailThreadView(dirty):
I/flutter (16788): 'package:cruisemonkey/src/views/seamail.dart': error: line 94 pos 21:
I/flutter (16788): lib/src/views/seamail.dart:94:21: Error: No named parameter with the name 'isFilled'.
I/flutter (16788):                     isFilled: true,
I/flutter (16788):                     ^^^^^^^^
I/flutter (16788):                     isFilled: true,
I/flutter (16788):                     ^
```

**Comment by vsmenon** [comment]
Not sure if this is a CFE error (@kmillikin ) or reporting problem downstream.

**Comment by aam** [comment]
Oh, I see. If I introduce invalid named parameter, I'm getting double-reporting in exception thrown by the framework:
```
[   +4 ms] Compiling dart to kernel with 1 updated files
[  +33 ms] 
           Compiler message:
[        ] lib/gallery/home.dart:27:9: Error: No named parameter with the name 'kuka'.
[        ]         kuka: 123,
[        ]         ^^^^
[        ] file://$FH/flutter/packages/flutter/lib/src/widgets/container.dart:1: Context: Found this candidate, but the arguments don't match.
[  +15 ms] Updating files
[  +68 ms] DevFS: Sync finished
[        ] Syncing files to device Nexus 5... (completed)
[        ] Synced 0.0MB.
[        ] Sending to VM service: _reloadSources({pause: false, rootLibUri: file:///data/user/0/io.flutter.demo.gallery/cache/flutter_galleryMEROUI/flutter_gallery/lib/main.dart.incremental.dill, packagesUri: file:///data/user/0/io.flutter.demo.gallery/cache/flutter_galleryMEROUI/flutter_gallery/.packages, isolateId: isolates/35287456})
[ +174 ms] Result: {type: ReloadReport, success: true, details: {savedLibraryCount: 541, loadedLibraryCount: 3, finalLibraryCount: 544, shapeChangeMappings: []}}
[   +1 ms] reloaded 3 of 544 libraries
[        ] Sending reload events to Nexus 5
[        ] Sending reload event to "main.dart$main-35287456"
[        ] Sending to VM service: getIsolate({isolateId: isolates/35287456})
[  +69 ms] Result: {type: Isolate, fixedId: true, id: isolates/35287456, name: main.dart:main(), number: 35287456, _originNumber: 35287456, startTime: 1543954968612, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 6, avgCollectionPeriodMil...
[   +8 ms] Sending to VM service: _flutter.listViews({})
[  +44 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xb4ce548c, isolate: {type: @Isolate, fixedId: true, id: isolates/35287456, name: main.dart$main-35287456, number: 35287456}}]}
[        ] Evicting dirty assets
[        ] Reassembling application
[        ] Sending to VM service: ext.flutter.reassemble({isolateId: isolates/35287456})
[ +280 ms] I/flutter ( 8154): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +10 ms] I/flutter ( 8154): The following _CompileTimeError was thrown building _FlutterLogo(dirty):
[        ] I/flutter ( 8154): 'package:flutter_gallery/gallery/home.dart': error: line 27 pos 9: lib/gallery/home.dart:27:9:
[        ] I/flutter ( 8154): Error: No named parameter with the name 'kuka'.
[        ] I/flutter ( 8154):         kuka: 123,
[        ] I/flutter ( 8154):         ^^^^
[        ] I/flutter ( 8154):         kuka: 123,
[        ] I/flutter ( 8154):         ^
[        ] I/flutter ( 8154): When the exception was thrown, this was the stack:
[  +21 ms] I/flutter ( 8154): #0      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
[        ] I/flutter ( 8154): #1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
[        ] I/flutter ( 8154): #2      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
[        ] I/flutter ( 8154): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
[        ] I/flutter ( 8154): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
[        ] I/flutter ( 8154): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
[        ] I/flutter ( 8154): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
[        ] I/flutter ( 8154): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
[        ] I/flutter ( 8154): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
[        ] I/flutter ( 8154): #10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
[        ] I/flutter ( 8154): #11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
[        ] I/flutter ( 8154): #12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[        ] I/flutter ( 8154): (elided one frame from package dart:async)
[        ] I/flutter ( 8154): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by aam** [comment]
Generated incremental kernel file seems correct:
```
$ $FH/engine/src/out/host_debug_unopt/dart pkg/front_end/tool/_fasta/dump_partial.dart $FH/flutter/examples/flutter_gallery/build/app.dill.incremental.dill $FH/flutter/examples/flutter_gallery/build/app.dill $FH/engine/src/out/host_debug_unopt/flutter_patched_sdk/platform_strong.dill 
...
  class _FlutterLogo extends fra::StatelessWidget {
    const constructor •({key::Key key = null}) → home::_FlutterLogo
      : super fra::StatelessWidget::•(key: key)
      ;
    @core::override
    method build(fra::BuildContext context) → fra::Widget {
      return new bas::Center::•(child: invalid-expression "lib/gallery/home.dart:27:9: Error: No named parameter with the name 'kuka'.\n        kuka: 123,\n        ^^^^");
    }
  }
```

**Comment by aam** [comment]
@kmillikin you might have some thoughts on this since double-reporting is happening because we further decorate the error provided by frontend with token position in kernel_binary_flowgraph.cc kernel reader(https://dart-review.googlesource.com/c/sdk/+/31320/5/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc#5873).

**Comment by aam** [comment]
@peter-ahe-google do you know if it is possible to change `invalid-expression` message that goes into the compiled kernel file?  That might be helpful in case we decide to drop source line quote with underlining carets from the  message compiled into kernel file.

**Comment by peter-ahe-google** [comment]
For consistency across all our tools, I think it's preferable if the source snippets are controlled by the front-end. So I suggest that the VM doesn't print source snippets when handling invalid-expressions.
