### ISSUE TITLE
"Unexpected tag 192 (Unknown) in ?, expected expression"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#35240]
During a hot reload in which I'd done nothing but change the initializers of some constant expressions:

```
I/flutter (16788): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (16788): The following _CompileTimeError was thrown building
I/flutter (16788): _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#fd6a3](dirty, state: _OverlayEntryState#b542d):
I/flutter (16788): 'package:flutter/src/widgets/modal_barrier.dart': error: Unexpected tag 192 (Unknown) in ?, expected
I/flutter (16788): expression
I/flutter (16788): 
I/flutter (16788): When the exception was thrown, this was the stack:
I/flutter (16788): #0      ModalRoute._buildModalBarrier (package:flutter/src/widgets/routes.dart:1198:17)
I/flutter (16788): #1      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:170:25)
I/flutter (16788): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3787:27)
I/flutter (16788): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:15)
I/flutter (16788): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #5      StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
I/flutter (16788): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #7      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4563:32)
I/flutter (16788): #8      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4953:17)
I/flutter (16788): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #10     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (16788): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #14     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
I/flutter (16788): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
I/flutter (16788): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
I/flutter (16788): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #24     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
I/flutter (16788): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
I/flutter (16788): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
I/flutter (16788): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
I/flutter (16788): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #36     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
I/flutter (16788): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
I/flutter (16788): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:3759:5)
I/flutter (16788): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #46     StatelessElement.update (package:flutter/src/widgets/framework.dart:3759:5)
I/flutter (16788): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #50     StatelessElement.update (package:flutter/src/widgets/framework.dart:3759:5)
I/flutter (16788): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
I/flutter (16788): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #58     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
I/flutter (16788): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
I/flutter (16788): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #64     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
I/flutter (16788): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #68     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
I/flutter (16788): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #72     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
I/flutter (16788): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #76     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
I/flutter (16788): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #80     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
I/flutter (16788): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #84     StatelessElement.update (package:flutter/src/widgets/framework.dart:3759:5)
I/flutter (16788): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #88     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
I/flutter (16788): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #92     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
I/flutter (16788): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #96     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
I/flutter (16788): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16788): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (16788): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16788): #100    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (16788): #101    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter (16788): #102    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (16788): #103    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (file:///home/ianh/dev/flutter/packages/flutter/lib/src/scheduler/binding.dart:990:15)
I/flutter (16788): #104    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (file:///home/ianh/dev/flutter/packages/flutter/lib/src/scheduler/binding.dart:930:9)
I/flutter (16788): #105    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (file:///home/ianh/dev/flutter/packages/flutter/lib/src/scheduler/binding.dart:751:7)
I/flutter (16788): #107    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (16788): #108    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (16788): #109    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (16788): (elided one frame from package dart:async)
I/flutter (16788): ════════════════════════════════════════════════════════════════════════════════════════════════════

Reloaded 281 of 442 libraries in 4,152ms.
```

**Comment by aam** [comment]
Not sure what is the problem here.
Next time it happens can you please capture revision of the flutter(and engine), build/app.dill, build/app.dill.incremental.dill from your project folder.
Having kernel files should help pinpoint the problem - whether incremental kernel file is incorrect(in which case we should look at frontend), or it is correct, in which case we should be able to troubleshot the failure in the VM by forcing it to reload that incremental kernel file.

**Comment by Hixie** [comment]
I'm actually seeing this quite a lot when doing development on master. It tends to happen after I made a syntax error somewhere and did a hot reload, from what I can tell (but then it persists even after I fixed the bug?).

I'll try to get more details.

**Comment by aam** [comment]
It's been a while since this was opened, will close at this point. Please reopen if more information becomes available.
