### ISSUE TITLE
NPE in ConstantVisitor._getConstantValue

### ISSUE THREAD

**Issue by jelly-cai** [dart-lang/sdk#35241]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.bf26f760b1bb3d5fea6bda110f6a17b590364120`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Administrator.USER-20180228II\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.bf26f760b1bb3d5fea6bda110f6a17b590364120, server version 1.20.5, error: Analysis failed: C:\Users\Administrator.USER-20180228II\AndroidStudioProjects\flutter_v2ex\lib\html\html_widget.dart context: exception_20181122_153926_096
NoSuchMethodError: The getter 'value' was called on null.
Receiver: null
Tried calling: value
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ConstantVisitor._getConstantValue (package:analyzer/src/dart/constant/evaluation.dart:1519:51)
#2      ConstantVisitor.visitPrefixedIdentifier (package:analyzer/src/dart/constant/evaluation.dart:1395:12)
#3      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9033:49)
#4      ConstantVerifier._validateFieldInitializers (package:analyzer/src/dart/constant/constant_verifier.dart:547:49)
#5      ConstantVerifier.visitConstructorDeclaration (package:analyzer/src/dart/constant/constant_verifier.dart:109:7)
#6      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2932:15)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#8      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1781:13)
#9      R

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/86080

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/86100
