### ISSUE TITLE
Flaky failures of `first_A02_t02.dart` and `first_A04_t01.dart`

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#35247]
These tests fail with errors like:

```
FAILED: dartk-vm release_simdbc64 co19_2/LibTest/io/Stdin/first_A02_t02
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 362ms):
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Stdin_first_A02_t02/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/Stdin/first_A02_t02.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 721ms):
DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Stdin_first_A02_t02/out.dill

exit code:
255

stderr:
Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by alexmarkov** [comment]
`simdbc64` architecture was discontinued. `co19_2/LibTest/io/Stdin/first_A02_t02` and `co19_2/LibTest/io/Stdin/first_A04_t01` are passing on all configurations.
