### ISSUE TITLE
"adb push" errors in CQ

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#35243]
This kind of error is showing up on many ARM bots:

```
--- Command "adb_precompilation" (took 19:11.000430s):
Steps to push precompiled runner and precompiled code to an attached device. Uses (and requires) adb.

exit code:
255

stdout:
Executing adb -s 0cbdbc6c0c371b48 shell rm -Rf /data/local/tmp/precompilation-testing/test ; echo AdbShellExitCode:  $?
ExitCode: 0
Time: 0:19:11.363898

Executing adb -s 0cbdbc6c0c371b48 shell mkdir -p /data/local/tmp/precompilation-testing/test ; echo AdbShellExitCode:  $?
Stderr:
error: device not found
ExitCode: 255
Time: 0:00:00.007772
```

See:
https://logs.chromium.org/logs/chromium/bb/client.dart/vm-kernel-precomp-android-release-3-3-be/1612/+/recipes/steps/test_vm/0/stdout
https://logs.chromium.org/logs/chromium/bb/client.dart/vm-kernel-precomp-android-release-1-3-be/1549/+/recipes/steps/test_vm/0/stdout
https://logs.chromium.org/logs/chromium/bb/client.dart/vm-kernel-precomp-android-release-2-3-be/1497/+/recipes/steps/test_vm/0/stdout

**Comment by alexmarkov** [comment]
Another adb-related error happened today on vm-kernel-precomp-android-release-3-3-be bot ([log](https://logs.chromium.org/logs/chromium/bb/client.dart/vm-kernel-precomp-android-release-3-3-be/1789/+/recipes/steps/test_vm/0/stdout)):

```
Unhandled exception:
Exception: Running: adb -s 0cbdbc6c0c371b48 push out/ReleaseAndroidARM/dart_precompiled_runtime /data/local/tmp/precompilation-testing/dart_precompiled_runtime failed:stdout:
  
stderr:
  protocol failure
exitCode: 1
timedOut: false
#0      AdbCommandResult.throwIfFailed (package:test_dart/android.dart:33:7)
#1      AdbDevice._adbCommand (package:test_dart/android.dart:378:12)
<asynchronous suspension>
#2      AdbDevice.pushCachedData (package:test_dart/android.dart:260:12)
#3      CommandExecutorImpl._runAdbPrecompilationCommand.<anonymous closure> (package:test_dart/test_runner.dart:1274:16)
#4      CommandExecutorImpl._runAdbPrecompilationCommand (package:test_dart/test_runner.dart:1304:25)
<asynchronous suspension>
#5      CommandExecutorImpl._runCommand.<anonymous closure> (package:test_dart/test_runner.dart:1232:16)
#6      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#10     Future._complete (dart:async/future_impl.dart:473:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#16     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
step returned non-zero exit code: 255
```

**Comment by alexmarkov** [comment]
Now these errors appear as exceptions in AdbDevicePool.create ([log1](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8920272349147067392/+/steps/vm_tests_shard_10_on_Android/0/stdout), [log2](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8920283866649403360/+/steps/vm_tests_shard_2_on_Android/0/stdout)):

```
  Unhandled exception:
  Exception: No android devices found. Please make sure "adb devices" shows your device!
  #0      AdbDevicePool.create (package:test_dart/android.dart:440:7)
  <asynchronous suspension>
  #1      testConfigurations (package:test_dart/test_configurations.dart:242:41)
  <asynchronous suspension>
  #2      main (package:test_dart/main.dart:37:3)
  #3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
  #4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by whesse** [comment]
We had a failure today where multiple tests failed in the chmod stage, so the test could not be made executable.  This disappeared in the next commit.  Build with failures is

https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-android-release-arm/878

FAILED: dartkp-dart_precompiled release_arm language_2/mixin_mixin_bound_test
Expected: Pass
Actual: Fail

Executing adb -s 0528efb90a2869a3 shell chmod 777 /data/local/tmp/precompilation-testing/dart_precompiled_runtime /data/local/tmp/precompilation-testing/process_test ; echo AdbShellExitCode:  $?
Stdout:
Unable to chmod /data/local/tmp/precompilation-testing/dart_precompiled_runtime: Operation not permitted
AdbShellExitCode: 10
ExitCode: 10
Time: 0:00:00.096179

--- Re-run this test:
python tools/test.py -n dartkp-android-release-arm language_2/mixin_mixin_bound_test

**Comment by alexmarkov** [comment]
Still seeing "Exception: No android devices found. Please make sure "adb devices" shows your device!" on vm-kernel-precomp-android-release-arm bot: [log1](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8916991832721517312/+/steps/vm_tests_shard_11_on_Android/0/stdout), [log2](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8916991832721517312/+/steps/vm_tests_shard_12_on_Android/0/stdout).

```
  Test configurations:
      dartkp-android-release-arm(architecture: arm, compiler: dartkp, mode: release, runtime: dart_precompiled, system: android, vm-options: [], dart2js-options: [], timeout: null, preview-dart-2, use-blobs)
  Suites tested: samples, standalone, standalone_2, corelib_2, language_2, vm, benchmark_smoke, utils, lib_2, analyze_library, service, kernel, ffi
      dartkp-android-release-arm(architecture: arm, compiler: dartkp, mode: release, runtime: dart_precompiled, system: android, vm-options: [], dart2js-options: [], timeout: null, preview-dart-2, use-blobs)
  Suites tested: observatory_ui
  Unhandled exception:
  Exception: No android devices found. Please make sure "adb devices" shows your device!
  #0      AdbDevicePool.create (package:test_dart/android.dart:440:7)
  <asynchronous suspension>
  #1      testConfigurations (package:test_dart/test_configurations.dart:242:41)
  <asynchronous suspension>
  #2      main (package:test_dart/main.dart:37:3)
  #3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
  #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by aam** [comment]
Another "Exception: No android devices found. Please make sure "adb devices" shows your device!"  on  vm-kernel-precomp-android-release-arm.

**Comment by whesse** [comment]
To fix this problem, we need to detect failing android devices (maybe disk full, who knows why) and quarantine them. We could try an auto-reboot, or just send a log message about them.  The main thing is not to report it as a failure of an individual test.  This should be a higher priority, I think.

**Comment by sstrickl** [comment]
This isn't adb devices related, but is still adb related. We got a batch of adb chmod errors on vm-kernel-precomp-android-release-arm this weekend during a single build ([logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8913801393233248496/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0)).

Example test log:
```
  /===============================================================\
  | lib_2/convert/codec1_test broke (Pass -> Fail, expected Pass) |
  \===============================================================/

  --- Command "vm_compile_to_kernel []" (took 01.000263s):
  DART_CONFIGURATION=ReleaseAndroidARM /b/swarming/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseAndroidARM/vm_platform_strong.dill -o /b/swarming/w/ir/out/ReleaseAndroidARM/generated_compilations/dartkp/tests_lib_2_convert_codec1_test/out.dill /b/swarming/w/ir/tests/lib_2/convert/codec1_test.dart --packages=/b/swarming/w/ir/.packages -Ddart.developer.causal_async_stacks=true

  exit code:
  0

  --- Command "precompiler" (took 02.000935s):
  DART_CONFIGURATION=ReleaseAndroidARM out/ReleaseAndroidARM/clang_x86/gen_snapshot --snapshot-kind=app-aot-blobs --blobs_container_filename=/b/swarming/w/ir/out/ReleaseAndroidARM/generated_compilations/dartkp/tests_lib_2_convert_codec1_test/out.aotsnapshot --no-sim-use-hardfp --ignore-unrecognized-flags --packages=/b/swarming/w/ir/.packages /b/swarming/w/ir/out/ReleaseAndroidARM/generated_compilations/dartkp/tests_lib_2_convert_codec1_test/out.dill

  exit code:
  0

  --- Command "remove_kernel_file" (took 8ms):
  DART_CONFIGURATION=ReleaseAndroidARM rm /b/swarming/w/ir/out/ReleaseAndroidARM/generated_compilations/dartkp/tests_lib_2_convert_codec1_test/out.dill

  exit code:
  0

  --- Command "adb_precompilation" (took 317ms):
  Steps to push precompiled runner and precompiled code to an attached device. Uses (and requires) adb.

  exit code:
  10

  stdout:
  Executing adb -s 0bcd0b1e0330103a shell rm -Rf /data/local/tmp/precompilation-testing/test ; echo AdbShellExitCode:  $?
  Stdout:
  AdbShellExitCode: 0
  ExitCode: 0
  Time: 0:00:00.057111

  Executing adb -s 0bcd0b1e0330103a shell mkdir -p /data/local/tmp/precompilation-testing/test ; echo AdbShellExitCode:  $?
  Stdout:
  AdbShellExitCode: 0
  ExitCode: 0
  Time: 0:00:00.091531

  Executing Skipped cached push
  ExitCode: 0
  Time: 0:00:00.000034

  Executing Skipped cached push
  ExitCode: 0
  Time: 0:00:00.000008

  Executing adb -s 0bcd0b1e0330103a shell chmod 777 /data/local/tmp/precompilation-testing/dart_precompiled_runtime /data/local/tmp/precompilation-testing/process_test ; echo AdbShellExitCode:  $?
  Stdout:
  Unable to chmod /data/local/tmp/precompilation-testing/dart_precompiled_runtime: Operation not permitted
  AdbShellExitCode: 10
  ExitCode: 10
  Time: 0:00:00.090188

  --- Re-run this test:
  python tools/test.py -n dartkp-android-release-arm lib_2/convert/codec1_test
```

**Comment by aartbik** [comment]
> --- Command "adb_precompilation" (took 09.000386s):
> Steps to push precompiled runner and precompiled code to an attached device. Uses (and requires) adb.
> 
> exit code:
> -9

**Comment by alexmarkov** [comment]
This is no longer flaky: vm-kernel-precomp-android-release-arm64 bot failed many times in a row with the same error:

```
 Unhandled exception:
 Exception: No android devices found. Please make sure "adb devices" shows your device!
 #0      AdbDevicePool.create (package:test_runner/src/android.dart:386:7)
 <asynchronous suspension>
 #1      testConfigurations (package:test_runner/src/test_configurations.dart:238:41)
 <asynchronous suspension>
 #2      main (file:///b/swarming/w/ir/pkg/test_runner/bin/test_runner.dart:39:5)
 #3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
 #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by alexmarkov** [comment]
Similar failures also appeared on vm-ffi-android-debug-arm64 and vm-ffi-android-release-arm64 bots.

**Comment by athomas** [comment]
whesse@ landed a change today that makes the test runner exit if an ADB command fails (instead of "Fail"ing the test and most likely all following tests). This prevents those failures from turning into real test results that create noise on the results feed. When that happens, the builder will also go purple instead of red, which makes it easier to see whether there was an infra or test failure.
