### ISSUE TITLE
Crash when computing redirectee type for erroneous program with multiple equal redirecting factory constructors

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#35260]
The program

```
class Supertype {
  factory Supertype() = X;
  factory Supertype() = X; //# 01: compile-time error
}

class X implements Supertype {
  X();
}
```

crashes with

```
Crash when compiling null,
at character offset null:
NoSuchMethodError: The getter 'typeArguments' was called on null.
Receiver: null
Tried calling: typeArguments
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      KernelClassBuilder.computeRedirecteeType (package:front_end/src/fasta/kernel/kernel_class_builder.dart:1496:51)
#2      KernelClassBuilder.checkRedirectingFactory (package:front_end/src/fasta/kernel/kernel_class_builder.dart:1572:9)
#3      KernelClassBuilder.checkRedirectingFactories (package:front_end/src/fasta/kernel/kernel_class_builder.dart:1724:9)
#4      SourceLoader.checkRedirectingFactories (package:front_end/src/fasta/source/source_loader.dart:875:17)
#5      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:287:14)
<asynchronous suspension>
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24
[...]
```

**Comment by jensjoha** [comment]
Fixed by ad62f21e5b2966a121c45d05f93a304d282c1cfd.
