### ISSUE TITLE
dartk-vm release_x64 standalone_2/io/socket_bind_test flaked

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#35299]
There are two shared server sockets opened in the test, first one gets closed, the second should remain open, but it ends up [flaky] closed which causes this test failure.

Test logs: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8928413538526644704/+/steps/vm_tests_shard_4/0/stdout

```
--- Command "vm" (took 02.000527s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --hot-reload-rollback-test-mode --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/io/socket_bind_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 46890
#0      testListenCloseListenClose (file:///b/s/w/ir/tests/standalone_2/io/socket_bind_test.dart:111:18)
<asynchronous suspension>
#1      main (file:///b/s/w/ir/tests/standalone_2/io/socket_bind_test.dart:145:5)
#2      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._complete (dart:async/future_impl.dart:473:7)
#7      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#8      _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#9      _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#10     retry (file:///b/s/w/ir/tests/standalone_2/io/test_utils.dart)
#11     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#19     main.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/socket_bind_test.dart)
#20     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#27     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#28     testBindDifferentAddresses (file:///b/s/w/ir/tests/standalone_2/io/socket_bind_test.dart)
#29     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#33     Future._complete (dart:async/future_impl.dart:473:7)
#34     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#35     _NativeSocket.multiplex (dart:io/runtime/binsocket_patch.dart:897:26)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -m release -n dartk-reload-rollback-linux-release-x64 standalone_2/io/socket_bind_test
```

**Comment by aam** [comment]
History on this flaky test:
- (unsuccessful) attempt to fix this landed https://dart-review.googlesource.com/c/sdk/+/85562.
- reported previously on https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8928593665843343984/+/steps/vm_tests_shard_1/0/stdout and https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8928478512982357216/+/steps/vm_tests_shard_4/0/stdout

cc @mkustermann

**Comment by aam** [comment]
Trying to reproduce the failure locally(on linux) as I ran `for a in {1..50}; do out/DebugIA32/dart --hot-reload-rollback-test-mode --sync-async --ignore-unrecognized-flags tests/standalone_2/io/socket_bind_test.dart&; done
` I got different error in the same test
```
Failed to execute test closure (retry id: 1) in attempt 0 (10 retries left).
Exception: SocketException: Failed to create server socket (OS Error: Address already in use, errno = 98), address = 0.0.0.0, port = 41707
Stacktrace: #0      _NativeSocket.bind (dart:io/runtime/binsocket_patch.dart:573:7)
<asynchronous suspension>
#1      _RawServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1167:26)
#2      _ServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1423:29)
#3      ServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1414:26)
#4      testBindDifferentAddresses (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/standalone_2/io/socket_bind_test.dart:70:35)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/standalone_2/io/socket_bind_test.dart:131:11)
<asynchronous suspension>
#6      retry (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/standalone_2/io/test_utils.dart:24:23)
<asynchronous suspension>
#7      main (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/standalone_2/io/socket_bind_test.dart:130:9)
<asynchronous suspension>
#8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

**Comment by aam** [comment]
and on next run I got original `SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 33664` error too.

**Comment by sjindel-google** [comment]
I'm seeing a similar issue with `standalone_2/io/socket_source_address_test`: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8927363564357968464/+/steps/vm_tests_shard_7/0/stdout

```
FAILED: dartk-vm release_simdbc64 standalone_2/io/socket_source_address_test
Expected: Pass
Actual: Fail

--- Command "vm_compile_to_kernel" (took 573ms):
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_standalone_2_io_socket_source_address_test/out.dill /b/s/w/ir/tests/standalone_2/io/socket_source_address_test.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 931ms):
DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_standalone_2_io_socket_source_address_test/out.dill

exit code:
0

stdout:
unittest-suite-wait-for-done
Failed to execute test closure (retry id: 2) in attempt 0 (10 retries left).
Exception: SocketException: Failed to create server socket (OS Error: Address already in use, errno = 48), address = 0.0.0.0, port = 49155
Stacktrace: #0      _NativeSocket.bind (dart:io/runtime/binsocket_patch.dart:573:7)
<asynchronous suspension>
#1      _RawServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1167:26)
#2      _ServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1423:29)
#3      ServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1414:26)
#4      testConnect (file:///b/s/w/ir/tests/standalone_2/io/socket_source_address_test.dart:100:35)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/socket_source_address_test.dart:156:11)
<asynchronous suspension>
#6      retry (file:///b/s/w/ir/tests/standalone_2/io/test_utils.dart:24:23)
<asynchronous suspension>
#7      main (file:///b/s/w/ir/tests/standalone_2/io/socket_source_address_test.dart:155:9)
<asynchronous suspension>
#8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by alexmarkov** [comment]
Both `standalone_2/io/socket_bind_test` and `standalone/io/socket_bind_test` are currently passing on all configurations and not flaky.
