### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by JungleeRaju** [dart-lang/sdk#35336]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-172.4343.25`
- `2.0.0-dev.8.0`
- `WS-172.4343.25, JRE 1.8.0_152-release-915-b12x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\admin\AppData\Local\Temp\report2.txt

```
Dart analysis server, SDK version 2.0.0-dev.8.0, server version 1.18.4, error: Analysis failed: D:\Rameshraju\Projects\JWR\junglee-web-rummy\jwr-html5-web-client\game\shared\component\CardHand.dart
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ApiSignature.addBytes (package:front_end/src/base/api_signature.dart:73)
#2      Iterable.forEach (dart:core/iterable.dart:226)
#3      FileState.transitiveSignature (package:analyzer/src/dart/analysis/file_state.dart:367)
#4      AnalysisDriver._getResolvedUnitSignature (package:analyzer/src/dart/analysis/driver.dart:1446)
#5      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1159)
<asynchronous suspension>
#6      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1010)
<asynchronous suspension>
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1859)
<asynchronous suspension>
#8      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1802)
#9      new AnalysisServer (package:analysis_server/src/analysis_server.dart:385)
#10     SocketServer.createAnalysisServer (package:analysis_server/src/socket_

**Comment by stereotype441** [comment]
I'm closing this issue since we haven't heard a response.  @JungleeRaju, please feel to re-open if you still see this problem with Dart 2.1.0.
