### ISSUE TITLE
dart2js compiler fails on "FutureOr<int> i = 0"

### ISSUE THREAD

**Issue by gothamgasworks** [dart-lang/sdk#35341]
* Dart SDK Version: 2.1.0

bug.dart:

```dart
import "dart:async";

void main() {
  FutureOr<int> i = 0;
  print(i.runtimeType);
}
```

Runs correctly on the Dart VM, however running the command `dart2js -o bug.dart.js bug.dart` gives:

```
bug.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.1.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Unsupported operation: Unexpected type FutureOr<int>
#0      RuntimeTypesNeedBuilderImpl.computeRuntimeTypesNeed.impliedClass (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:1702:7)
#1      RuntimeTypesNeedBuilderImpl.computeRuntimeTypesNeed (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:1757:32)
#2      ClosedWorldRtiNeedMixin.computeRtiNeed (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/world.dart:586:31)
#3      new KClosedWorldImpl (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:2150:5)
#4      ResolutionWorldBuilderImpl.closeWorld (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/universe/resolution_world_builder.dart:985:36)
#5      Compiler.closeResolution (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:414:56)
#6      Compiler.computeClosedWorld (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:343:32)
#7      Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:390:34)
#8      CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#9      Compiler.compileLoadedLibraries (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:389:14)
#10     Compiler.runInternal (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:276:5)
<asynchronous suspension>
#11     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:216:38)
#12     new Future.sync (dart:async/future.dart:224:31)
#13     Compiler.run.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:216:20)
#14     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#15     Compiler.run (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:213:41)
#16     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/compiler/lib/src/apiimpl.dart:148:22)
#17     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#21     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by sigmundch** [comment]
Thanks for reporting!

Johnni - can you take a look?

It appears that the small repro above is now working in master (I believe it is working since e62951fd3d, but I believe that's likely because we are hiding the issue, not because we fixed the internal crash)

**Comment by gothamgasworks** [comment]
I've ran it on a dev channel build, no luck:

```
bug.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.2.0-dev.0.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Unsupported operation: Unexpected type FutureOr<int>
#0      RuntimeTypesNeedBuilderImpl.computeRuntimeTypesNeed.impliedClass (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:1704:7)
#1      RuntimeTypesNeedBuilderImpl.computeRuntimeTypesNeed (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/js_backend/runtime_types.dart:1759:32)
#2      new KClosedWorldImpl (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/kernel/kernel_world.dart:83:31)
#3      ResolutionWorldBuilderImpl.closeWorld (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/universe/resolution_world_builder.dart:1013:36)
#4      Compiler.closeResolution (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:443:56)
#5      Compiler.computeClosedWorld (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:354:32)
#6      Compiler.compileLoadedLibraries.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:401:34)
#7      CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#8      Compiler.compileLoadedLibraries (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:400:14)
#9      Compiler.runInternal (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:286:13)
<asynchronous suspension>
#10     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:220:38)
#11     new Future.sync (dart:async/future.dart:224:31)
#12     Compiler.run.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:220:20)
#13     CompilerTask.measureSubtask (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#14     Compiler.run (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/compiler.dart:217:41)
#15     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/compiler/lib/src/apiimpl.dart:89:22)
#16     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by johnniwinther** [comment]
I'm working on a fix now.

**Comment by sigmundch** [comment]
@gothamgasworks sorry for not being clear, the change I mentioned about our master branch has not been released to the dev channel yet, which explains why you still see the error in 2.2.0-dev.0.0.

Johhni has a CL ready to fix the problem, once it lands we'll update this issue and you should expect it to be available in the following dev release (I'm honestly not sure when the next one is scheduled for, but normally it is a matter of days).

In case it helps and you need to work around it, you can change your code to:

```dart
import "dart:async";
void main() {
  FutureOr<int> i = 0;
  print((i as dynamic).runtimeType);
}
```

In particular, the issue comes up because of the use of `.runtimeType`. This property has a big cost in the generated code of dart2js, so we normally encourage not to use it much. We also work hard to recognize certain patterns where `.runtimeType` can be done cheaply. The patterns are things like `a.runtimeType == b.runtimeType`.

Our pattern recognition relies on looking at the static type of the receiver of the call to `.runtimeType`. It appears we had not included a case for `FutureOr<T>` (it is not a nominal type like others in Dart, so it requires special handling). If you change the static type before calling .runtimeType, dart2js wont crash anymore.
