### ISSUE TITLE
dart2js: Non-short-circuit boolean operators crash

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#35356]
Consider the following program:

```dart
main() {
  bool b = true & true;
  b |= true;
  b = b^b;
  print(b);
}
```

The non-short-circuit boolean operators `&`, `|`, and `^` were added to `bool` recently (specified in 0808d29b4e33c303bf40524407a6e331c7a439f8, implemented in cc08d0e1da55d7f76d5542bfbd628c29f9ff0beb), but something goes wrong when `dart2js` compiles the above, because execution produces the following output:

```
..../preambles/d8.js:263: Invalid argument: true
          throw e;
          ^
Invalid argument: true
    at Object.wrapException (out.js:581:17)
    at Object.iae (out.js:558:15)
    at main (out.js:1257:18)
    at action (/usr/local/google/home/eernst/bin/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (/usr/local/google/home/eernst/bin/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (/usr/local/google/home/eernst/bin/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at out.js:1471:7
    at out.js:1457:7
    at out.js:1468:5
    at out.js:1476:3
```

**Comment by sigmundch** [comment]
it seems we have logic in our optimizer that assumes that all bit operators were available only on ints or non-primitive types. This assumption is no longer true now that bool also implement some of these operators.

I sent a CL (https://dart-review.googlesource.com/c/sdk/+/86801) to remove the assumption, but we probably want to make the specialization more detailed to improve what we do on boolean operators.

/cc @rakudrama

**Comment by joshualitt** [comment]
Closing because I believe this may be working on TOT.
