### ISSUE TITLE
JIT-DebugSIMARM compile-time crash

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#35406]
KBC-INT-ReleaseX64 - JIT-DebugSIMARM: !DIVERGENCE! 1.2:4023176434 (output=false)

fail2:
../../runtime/vm/object.cc: 20680: error: Fatal error in OneByteString::New: invalid len 536870912

**Comment by aartbik** [comment]
Reproducible, stack trace:

../../runtime/vm/object.cc: 19564: error: Fatal error in OneByteString::New: invalid len 536870912

thread=61329, isolate=fuzz4023176434.dart:main()(0x23b4b00)
  [0x0169fbac] dart::Profiler::DumpStackTrace(void*)
  [0x0169fbac] dart::Profiler::DumpStackTrace(void*)
  [0x01936144] Dart_DumpNativeStackTrace
  [0x019380cb] dart::Assert::Fail(char const*, ...)
  [0x0165f131] dart::OneByteString::New(int, dart::Heap::Space)
  [0x01661d7d] dart::OneByteString::Concat(dart::String const&, dart::String const&, dart::Heap::Space)
  [0x015dfd7e] dart::String::Concat(dart::String const&, dart::String const&, dart::Heap::Space)
  [0x014b4580] dart::BootstrapNatives::DN_String_concat(_Dart_NativeArguments*)
  [0x017254de] dart::Simulator::SupervisorCall(dart::Instr*)
  [0x017265f1] dart::Simulator::DecodeType7(dart::Instr*)
  [0x01729fc6] dart::Simulator::Execute()
  [0x0172a673] dart::Simulator::Call(int, int, int, int, int, bool, bool)
  [0x015613d0] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned int)
  [0x01560f88] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
  [0x015644aa] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  [0x0159de5a] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x015d8f81] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x015d9bf4] dart::MessageHandler::TaskCallback()
  [0x015db0ec] Unknown symbol
  [0x017597ef] dart::ThreadPool::Worker::Loop()
  [0x01759387] dart::ThreadPool::Worker::Main(unsigned int)

**Comment by aartbik** [comment]
Happens occasionally in nightly run, most likely just due to excessive string lengths, something that is scheduled for improvement in Q1.

JIT-MARKSWEEPEVERY-ReleaseSIMDBC - JIT-ReleaseX64: !DIVERGENCE! 1.2:4242528457 (output=false)

fail1:
../../runtime/vm/object.cc: 19590: error: Fatal error in OneByteString::New: invalid len 536870912

thread=22279, isolate=fuzz.dart:main()(0x3aa2b00)
  [0x014adc1c] dart::Profiler::DumpStackTrace(void*)
  [0x014adc1c] dart::Profiler::DumpStackTrace(void*)
-- End of DumpStackTrace

**Comment by aartbik** [comment]
Another one, different method:

KBC-INT-ReleaseX64 - JIT-DEPOPTEVERY-DebugIA32: !DIVERGENCE! 1.2:2743217172 (output=false)

fail2:
../../runtime/vm/object.cc: 19837: error: Fatal error in TwoByteString::New: invalid len 671088640

thread=22163, isolate=fuzz.dart:main()(0x2b24b00)
  [0x0167781c] dart::Profiler::DumpStackTrace(void*)
  [0x0167781c] dart::Profiler::DumpStackTrace(void*)
  [0x018f9144] Dart_DumpNativeStackTrace
  [0x018fb09b] dart::Assert::Fail(char const*, ...)
  [0x01636e01] dart::TwoByteString::New(int, dart::Heap::Space)
  [0x0163973d] dart::TwoByteString::Concat(dart::String const&, dart::String const&, dart::Heap::Space)
  [0x015b75a2] dart::String::Concat(dart::String const&, dart::String const&, dart::Heap::Space)

**Comment by aartbik** [comment]
Things to watch out for at this moment:
- String/List concatenation x = x + x inside a loop
-  Large padLeft/padRight argument

**Comment by aartbik** [comment]
Two more from today's nightly:

Isolate (/b/s/w/itoHbATO/dart_fuzzZBORFC) KBC-CMP-ReleaseX64 - JIT-NOFIELDGUARDS-ReleaseIA32: !DIVERGENCE! 1.2:171582009 (output=false)

fail2:
Unhandled exception:
Out of Memory
#0      _StringBase._concatRangeNative (dart:core/runtime/libstring_patch.dart:939:34)
#1      _StringBase._concatRange (dart:core/runtime/libstring_patch.dart:933:12)
#2      StringBuffer.toString (dart:core/runtime/libstring_buffer_patch.dart:127:23)
#3      IterableBase.iterableToFullString (dart:collection/iterable.dart:281:19)
#4      ListBase.listToString (dart:collection/list.dart:32:20)
#5      List.toString (dart:core/runtime/libgrowable_array.dart:363:33)
#6      _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:847:23)
#7      main (file:///b/s/w/itoHbATO/dart_fuzzZBORFC/fuzz.dart:263:62)
#8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)


Isolate (/b/s/w/itqlxbNl/dart_fuzzLXCTDV) JIT-ReleaseSIMDBC64 - JIT-STACKTRACEEVERY-ReleaseSIMDBC: !DIVERGENCE! 1.2:943768244 (output=false)

fail2:
../../runtime/vm/object.cc: 19593: error: Fatal error in TwoByteString::New: invalid len 536870912

thread=21944, isolate=fuzz.dart:main()(0x2cd0b00)
  [0x014caeac] dart::Profiler::DumpStackTrace(void*)
  [0x014caeac] dart::Profiler::DumpStackTrace(void*)
-- End of DumpStackTrace
