### ISSUE TITLE
Flaky timeouts of lib_2/isolate/ tests on mac simdbc64 reload

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35410]
Note this test shows up as a failure, but it reports an inner timeout.

```dart
FAILED: dartk-vm debug_simdbc64 lib_2/isolate/nested_spawn2_test
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 02.000323s):
DART_CONFIGURATION=DebugSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/DebugSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_lib_2_isolate_nested_spawn2_test/out.dill /b/s/w/ir/tests/lib_2/isolate/nested_spawn2_test.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 03:39.000127s):
DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --hot-reload-test-mode --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_lib_2_isolate_nested_spawn2_test/out.dill

exit code:
255

stdout:
unittest-suite-wait-for-done
ERROR: spawned isolate can spawn other isolates
  Test failed: Caught Test timed out after 120 seconds.
  tests/lib_2/isolate/remote_unittest_helper.dart 138:9  _simulateTests.<fn>.<fn>
  package:unittest/src/internal_test_case.dart 120:24    InternalTestCase.run.<fn>
  dart:async/zone.dart 1132:38                           _rootRunUnary
  dart:async/zone.dart 1029:19                           _CustomZone.runUnary
  dart:async/future_impl.dart 126:18                     _FutureListener.handleValue
  dart:async/future_impl.dart 639:45                     Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 668:32                     Future._propagateToListeners
  dart:async/future_impl.dart 483:5                      Future._completeWithValue
  dart:async/future_impl.dart 513:7                      Future._asyncComplete.<fn>
  dart:async/zone.dart 1124:13                           _rootRun
  dart:async/zone.dart 1021:19                           _CustomZone.run
  dart:async/zone.dart 923:7                             _CustomZone.runGuarded
  dart:async/zone.dart 963:23                            _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21               _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                _startMicrotaskLoop
  dart:isolate/runtime/libisolate_patch.dart 115:13      _runPendingImmediateCallback
  dart:isolate/runtime/libisolate_patch.dart 172:5       _RawReceivePortImpl._handleMessage

0 PASSED, 0 FAILED, 1 ERRORS

stderr:
Unhandled exception:
Exception: Some tests failed.
#0      SimpleConfiguration.onDone (package:unittest/src/simple_configuration.dart:197:9)
#1      _completeTests (package:unittest/unittest.dart:610:10)
#2      _runTest (package:unittest/unittest.dart:550:5)
#3      _nextTestCase (package:unittest/unittest.dart:496:3)
#4      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#5      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#6      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -n dartk-reload-mac-debug-simdbc64 lib_2/isolate/nested_spawn2_test
```

[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8927205942385044608/+/steps/vm_tests_shard_2/0/stdout)

Running a 50 repeats (40 seconds each) on a macbook did not reproduce this.

~~Why does this test take 40 seconds with simdbc64 on mac, while on linux it takes 3 seconds? I'll investigate the performance on mac, maybe this caused the flaky timeout.~~
The slowness is not OS specific. (I was put off by the -n flag for test.py, on a Linux desktop the test also takes 30 seconds.)

**Comment by dcharkes** [comment]
For reference: both mac & linux spend the majority of the time in the simulator for this test.

```
  - start_thread
      - 99.02% dart::ThreadStart
         - 99.02% dart::ThreadPool::Worker::Main
            - dart::ThreadPool::Worker::Loop
               - 77.71% dart::MessageHandler::TaskCallback
                  - 77.45% dart::MessageHandler::HandleMessages
                     - 77.43% dart::IsolateMessageHandler::HandleMessage
                        - 76.93% dart::DartLibraryCalls::HandleMessage
                           - dart::DartEntry::InvokeFunction
                              - 76.49% dart::Simulator::Call
```

**Comment by dcharkes** [comment]
same stacktrace on completely different testcase:

```dart
FAILED: dartk-vm debug_simdbc64 lib_2/isolate/unresolved_ports_test
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 03.000095s):
DART_CONFIGURATION=DebugSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/DebugSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_lib_2_isolate_unresolved_ports_test/out.dill /b/s/w/ir/tests/lib_2/isolate/unresolved_ports_test.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 03:32.000243s):
DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --hot-reload-test-mode --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_lib_2_isolate_unresolved_ports_test/out.dill

exit code:
255

stdout:
unittest-suite-wait-for-done
ERROR: Message chain with unresolved ports
  Test failed: Caught Test timed out after 120 seconds.
  tests/lib_2/isolate/remote_unittest_helper.dart 138:9  _simulateTests.<fn>.<fn>
  package:unittest/src/internal_test_case.dart 120:24    InternalTestCase.run.<fn>
  dart:async/zone.dart 1132:38                           _rootRunUnary
  dart:async/zone.dart 1029:19                           _CustomZone.runUnary
  dart:async/future_impl.dart 126:18                     _FutureListener.handleValue
  dart:async/future_impl.dart 639:45                     Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 668:32                     Future._propagateToListeners
  dart:async/future_impl.dart 483:5                      Future._completeWithValue
  dart:async/future_impl.dart 513:7                      Future._asyncComplete.<fn>
  dart:async/zone.dart 1124:13                           _rootRun
  dart:async/zone.dart 1021:19                           _CustomZone.run
  dart:async/zone.dart 923:7                             _CustomZone.runGuarded
  dart:async/zone.dart 963:23                            _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21               _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                _startMicrotaskLoop
  dart:isolate/runtime/libisolate_patch.dart 115:13      _runPendingImmediateCallback
  dart:isolate/runtime/libisolate_patch.dart 172:5       _RawReceivePortImpl._handleMessage

0 PASSED, 0 FAILED, 1 ERRORS

stderr:
Unhandled exception:
Exception: Some tests failed.
#0      SimpleConfiguration.onDone (package:unittest/src/simple_configuration.dart:197:9)
#1      _completeTests (package:unittest/unittest.dart:610:10)
#2      _runTest (package:unittest/unittest.dart:550:5)
#3      _nextTestCase (package:unittest/unittest.dart:496:3)
#4      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#5      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#6      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -n dartk-reload-mac-debug-simdbc64 lib_2/isolate/unresolved_ports_test
```

**Comment by dcharkes** [comment]
The issue persists for `unresolved_ports_test`, same stack trace: [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8925271774788236048/+/steps/vm_tests_shard_8/0/stdout)

**Comment by alexmarkov** [comment]
`simdbc64` architecture was discontinued.
