### ISSUE TITLE
NoSuchMethodError: Class 'DietListener' has no instance method 'popCharOffset'.

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#35445]
Saw this flaky failure, logs are available at [here](https://isolateserver.appspot.com/browse?namespace=default-gzip&hash=34457163fd572686a0a868e90aff318adb835370)

```
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --optimization-counter-threshold=5 --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseIA32/generated_tests/language_2/duplicate_interface_implements_test_none.dart

exit code:
252

stderr:
Crash when compiling file:///b/s/w/ir/out/ReleaseIA32/generated_tests/language_2/duplicate_interface_lib.dart,
at character offset null:
NoSuchMethodError: Class 'DietListener' has no instance method 'popCharOffset'.
Receiver: Instance of 'DietListener'
Tried calling: popCharOffset()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      OutlineBuilder.endLibraryName (package:front_end/src/fasta/source/outline_builder.dart:437:5)
#2      Parser.parseLibraryName (package:front_end/src/fasta/parser/parser.dart:650:14)
#3      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:623:18)
#4      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:489:14)
#5      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:354:15)
#6      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:251:14)
<asynchronous suspension>
#7      Loader.buildBodies (package:front_end/src/fasta/loader.dart:178:15)
<asynchronous suspension>
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:279:20)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#10     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:277:12)
<asynchronous suspension>
#11     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:145:38)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#13     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:55:10)
<asynchronous suspension>
#14     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:40:18)
<asynchronous suspension>
#15     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:132:20)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#17     new Future.sync (dart:async/future.dart:224:31)
#18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#24     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:130:10)
#25     generateKernel (package:front_end/src/kernel_generator_impl.dart:39:32)
<asynchronous suspension>
#26     kernelForComponent (package:front_end/src/api_prototype/kernel_generator.dart:83:17)
<asynchronous suspension>
#27     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:227:11)
<asynchronous suspension>
#28     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:128:31)
<asynchronous suspension>
#29     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#30     _rootRun (dart:async/zone.dart:1120:38)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#37     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#38     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#39     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)


#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      OutlineBuilder.endLibraryName (package:front_end/src/fasta/source/outline_builder.dart:437:5)
#2      Parser.parseLibraryName (package:front_end/src/fasta/parser/parser.dart:650:14)
#3      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:623:18)
#4      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:489:14)
#5      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:354:15)
#6      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:251:14)
<asynchronous suspension>
#7      Loader.buildBodies (package:front_end/src/fasta/loader.dart:178:15)
<asynchronous suspension>
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:279:20)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#10     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:277:12)
<asynchronous suspension>
#11     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:145:38)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#13     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:55:10)
<asynchronous suspension>
#14     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:40:18)
<asynchronous suspension>
#15     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:132:20)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#17     new Future.sync (dart:async/future.dart:224:31)
#18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#24     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:130:10)
#25     generateKernel (package:front_end/src/kernel_generator_impl.dart:39:32)
<asynchronous suspension>
#26     kernelForComponent (package:front_end/src/api_prototype/kernel_generator.dart:83:17)
<asynchronous suspension>
#27     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:227:11)
<asynchronous suspension>
#28     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:128:31)
<asynchronous suspension>
#29     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#30     _rootRun (dart:async/zone.dart:1120:38)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#37     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#38     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#39     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -n dartk-optcounter-linux-release-ia32 language_2/duplicate_interface_implements_test/none


```

**Comment by alexmarkov** [comment]
The test is currently passing and not flaky.
