### ISSUE TITLE
ubuntu system  GN build has error

### ISSUE THREAD

**Issue by zhshw** [dart-lang/sdk#35450]
*  Linux  ubuntu 1604
last commit 278299c73b93f14fa77afec9b6be649ddc76f1cd
wiki: https://github.com/dart-lang/sdk/wiki/Building

- my build steps:
```
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
export PATH="$PATH:$PWD/depot_tools"
cd depot_tools
git checkout 5aa5cd76f00e7774f71367f34d9998cfa0034d04
cd ../
mkdir dart-sdk
cd dart-sdk
fetch dart
```
```
Error: 1> Var is not defined: host_os
Traceback (most recent call last):
  File "/home/work/tmp/depot_tools/fetch.py", line 299, in <module>
    sys.exit(main())
  File "/home/work/tmp/depot_tools/fetch.py", line 294, in main
    return run(options, spec, root)
  File "/home/work/tmp/depot_tools/fetch.py", line 288, in run
    return checkout.init()
  File "/home/work/tmp/depot_tools/fetch.py", line 131, in init
    self.run_gclient(*sync_cmd)
  File "/home/work/tmp/depot_tools/fetch.py", line 78, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/home/work/tmp/depot_tools/fetch.py", line 68, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync')' returned non-zero exit status 1
```

- then exec

```
DEPOT_TOOLS_UPDATE=0 gclient sync
```

```
sdk (ERROR)
[0:00:00] Started.
[0:00:00] ________ unmanaged solution; skipping sdk
Error: 1> Var is not defined: host_os
```
**buildtools path cannot generate**

- then  exec 
```
cd sdk
./tools/build.py runtime
```
Couldn't find the gn binary at path: /home/work/tmp/dart-sdk/sdk/buildtools/gn

**Comment by rhboop** [comment]
In case someone is confused again. `fetch dart` is a command, not `git clone https://github.com/dart-lang/sdk.git`.
