### ISSUE TITLE
InconsistentAnalysisException from DartChangeBuilderImpl.createFileEditBuilder while typing

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#35456]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-183.4886.37`
- `2.2.0-edge.0df70ab15b9aec042046399e9c768cece51e04d6`
- `IC-183.4886.37, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/t6/ghq95c9n0xx7qb0kmk21bm6w003j4x/T/report.txt

```
Dart analysis server, SDK version 2.2.0-edge.0df70ab15b9aec042046399e9c768cece51e04d6, server version 1.21.1, error: Failed to handle completion domain request: {id: 1620, method: completion.getSuggestions, params: {file: /Users/devoncarew/projects/google/codemirror.dart/lib/codemirror.dart, offset: 48880}, clientRequestTime: 1545248957617}
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:199:7)
#1      AnalysisSessionImpl.getResolvedUnit (package:analyzer/src/dart/analysis/session.dart:164:5)
#2      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:67:47)
<asynchronous suspension>
#3      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:68:41)
<asynchronous suspension>
#4      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:50:18)
#5      OverrideContributor._buildReplacementText (package:analysis_server/src/services/completion/dart/override_contributor.dart:80:19)
<asynchronous suspension>
#6      OverrideContributor._buildSuggestion (package:analysis_server/src/services/completion/dart/override_contributor.dart:102:39)
<asynchronous suspension>

**Comment by srawlins** [comment]
I imagine this was fixed for https://github.com/dart-lang/sdk/issues/35169.

**Comment by srawlins** [comment]
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).
