### ISSUE TITLE
Analysis Server error in ServerContextManagerCallbacks.removeContext after changing analysis roots

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#35452]
Windows 10, Dart SDK 2.1.1-dev.0.0

Full instrumentation log [attached](https://github.com/dart-lang/sdk/files/2695056/das_error_log.txt), search for 'SERVER_ERROR' there.

```
Dart analysis server, SDK version 2.1.1-dev.0.0, server version 1.21.1, error: NoSuchMethodError: The method 'dispose' was called on null.
Receiver: null
Tried calling: dispose()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ServerContextManagerCallbacks.removeContext (package:analysis_server/src/analysis_server.dart:1322:12)
#2      ContextManagerImpl._destroyContext (package:analysis_server/src/context_manager.dart:1187:15)
#3      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:718:9)
#4      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:816:22)
#5      AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:385:14)
#6      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:299:16)
#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:642:45)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#9      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:638:50)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1500:12)
#14     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:637:5)
#15     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#17     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#18     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#49     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#50     _StreamController._add (dart:async/stream_controller.dart:640:7)
#51     _StreamController.add (dart:async/stream_controller.dart:586:5)
#52     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1722:41)
#53     _rootRunUnary (dart:async/zone.dart:1136:13)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#58     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#59     _StreamController._add (dart:async/stream_controller.dart:640:7)
#60     _StreamController.add (dart:async/stream_controller.dart:586:5)
#61     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1284:33)
#62     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#63     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#64     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#65     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#66     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by devoncarew** [comment]
Note that this exception occurred while testing the new scoped analysis support in IntelliJ.

**Comment by srawlins** [comment]
I suspect this crash is fixed; please re-open if you see this again.
