### ISSUE TITLE
analyzer feedback from intelliJ

### ISSUE THREAD

**Issue by rishirD** [dart-lang/sdk#35463]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.2 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/tz/_g_vdh8971dc2d442zrsg2w00000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Captured exception
IsolateSpawnException: Unable to spawn isolate: Crash when compiling file:///Users/RishiDeep/%23rD/Web/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot,
at character offset null:
Bad state: No element
#0      List.first (dart:core/runtime/libgrowable_array.dart:215:5)
#1      BodyBuilder.finishFields (package:front_end/src/fasta/kernel/body_builder.dart:547:28)
#2      DietListener.listenerFinishFields (package:front_end/src/fasta/source/diet_listener.dart:804:14)
#3      DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:847:5)
#4      DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:654:5)
#5      DietListener.endTopLevelFields (package:front_end/src/fasta/source/diet_listener.dart:315:5)
#6      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2248:16)
#7      Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2198:12)
#8      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:481:14)
#9      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#10     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:253:14)
<asynchronous suspension>
#11     Loader.buildBodies (package:front_end/src/fasta/loader.dart:181:15)
<asynchronous suspension>

**Comment by stereotype441** [comment]
Although the problem is reported by the analysis server, it looks from the stack trace like a front end or VM problem.
