### ISSUE TITLE
pkg/dartfix/test/src/driver_test fails

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#35478]
```
╰─➤  tools/test.py -mrelease -ax64 pkg/dartfix/test/src/driver_test
tools/testing/dart/main.dart:1: Warning: Interpreting this as package URI, 'package:test_dart/main.dart'.
Test configuration:
    custom configuration(architecture: x64, compiler: dartk, mode: release, runtime: vm, system: linux, vm-options: [], timeout: null, preview-dart-2)
Suites tested: pkg

FAILED: dartk-vm release_x64 pkg/dartfix/test/src/driver_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 14.000504s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --ignore-unrecognized-flags --packages=$DH/sdk/.packages $DH/sdk/pkg/dartfix/test/src/driver_test.dart

exit code:
255

stdout:
00:00 +0: protocol version
00:00 +1: client version
00:00 +2: fix example
00:08 +2 -1: fix example [E]
  {"code":"SERVER_ERROR","message":"NoSuchMethodError: The getter 'fullName' was called on null.\nReceiver: null\nTried calling: fullName","stackTrace":"#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)\n#1      PluginWatcher._getSdkPath (package:analysis_server/src/plugin/plugin_watcher.dart:101:63)\n#2      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:53:49)\n#3      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:2021:22)\n#4      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:371:16)\n#5      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:187:33)\n#6      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:772:48)\n#7      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1090:19)\n#8      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1130:16)\n#9      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:730:9)\n#10     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:507:22)\n#11     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:369:14)\n#12     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:298:16)\n#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:349:45)\n#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)\n#15     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:345:50)\n#16     _rootRun (dart:async/zone.dart:1124:13)\n#17     _CustomZone.run (dart:async/zone.dart:1021:19)\n#18     _runZoned (dart:async/zone.dart:1516:10)\n#19     runZoned (dart:async/zone.dart:1500:12)\n#20     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:344:5)\n#21     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)\n#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)\n#23     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)\n#24     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)\n#25     _rootRunUnary (dart:async/zone.dart:1132:38)\n#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)\n#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)\n#32     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)\n#33     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)\n#34     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)\n#35     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)\n#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)\n#37     _rootRunUnary (dart:async/zone.dart:1132:38)\n#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#42     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)\n#43     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)\n#44     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)\n#45     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)\n#46     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)\n#47     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)\n#48     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)\n#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)\n#50     _rootRunUnary (dart:async/zone.dart:1132:38)\n#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#55     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)\n#56     _StreamController._add (dart:async/stream_controller.dart:640:7)\n#57     _StreamController.add (dart:async/stream_controller.dart:586:5)\n#58     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1722:41)\n#59     _rootRunUnary (dart:async/zone.dart:1136:13)\n#60     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#64     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)\n#65     _StreamController._add (dart:async/stream_controller.dart:640:7)\n#66     _StreamController.add (dart:async/stream_controller.dart:586:5)\n#67     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1284:33)\n#68     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)\n#69     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)\n#70     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)\n#71     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)\n#72     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)\n"}
  dart:async/future_impl.dart 22:43                             _Completer.completeError
  package:analysis_server_client/server.dart 97:21              Server.listenToOutput.<fn>
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1132:38                                  _rootRunUnary
  dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
  dart:async/zone.dart 931:7                                    _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 336:11                            _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 263:7                             _BufferingStreamSubscription._add
  dart:async/stream_transformers.dart 68:11                     _SinkTransformerStreamSubscription._add
  dart:async/stream_transformers.dart 15:11                     _EventSinkWrapper.add
  dart:convert/string_conversion.dart 238:11                    _StringAdapterSink.add
  dart:convert/line_splitter.dart 150:13                        _LineSplitterSink._addLines
  dart:convert/line_splitter.dart 125:5                         _LineSplitterSink.addSlice
  dart:convert/string_conversion.dart 165:5                     StringConversionSinkMixin.add
  dart:async/stream_transformers.dart 120:24                    _SinkTransformerStreamSubscription._handleData
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1132:38                                  _rootRunUnary
  dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
  dart:async/zone.dart 931:7                                    _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 336:11                            _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 263:7                             _BufferingStreamSubscription._add
  dart:async/stream_transformers.dart 68:11                     _SinkTransformerStreamSubscription._add
  dart:async/stream_transformers.dart 15:11                     _EventSinkWrapper.add
  dart:convert/string_conversion.dart 238:11                    _StringAdapterSink.add
  dart:convert/string_conversion.dart 243:7                     _StringAdapterSink.addSlice
  dart:convert/string_conversion.dart 314:20                    _Utf8ConversionSink.addSlice
  dart:convert/string_conversion.dart 307:5                     _Utf8ConversionSink.add
  dart:convert/chunked_conversion.dart 74:18                    _ConverterStreamEventSink.add
  dart:async/stream_transformers.dart 120:24                    _SinkTransformerStreamSubscription._handleData
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1132:38                                  _rootRunUnary
  dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
  dart:async/zone.dart 931:7                                    _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 336:11                            _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 263:7                             _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 764:19                      _SyncStreamController._sendData
  dart:async/stream_controller.dart 640:7                       _StreamController._add
  dart:async/stream_controller.dart 586:5                       _StreamController.add
  dart:io/runtime/binsocket_patch.dart 1722:41                  _Socket._onData
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1136:13                                  _rootRunUnary
  dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
  dart:async/zone.dart 931:7                                    _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 336:11                            _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 263:7                             _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 764:19                      _SyncStreamController._sendData
  dart:async/stream_controller.dart 640:7                       _StreamController._add
  dart:async/stream_controller.dart 586:5                       _StreamController.add
  dart:io/runtime/binsocket_patch.dart 1284:33                  new _RawSocket.<fn>
  dart:io/runtime/binsocket_patch.dart 826:14                   _NativeSocket.issueReadEvent.issue
  dart:async/schedule_microtask.dart 41:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                       _startMicrotaskLoop
  dart:isolate/runtime/libisolate_patch.dart 115:13             _runPendingImmediateCallback
  dart:isolate/runtime/libisolate_patch.dart 172:5              _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/stream_impl.dart 139:21                            _BufferingStreamSubscription.onData
  dart:async/stream_impl.dart 112:10                            new _BufferingStreamSubscription
  dart:async/stream_transformers.dart 45:9                      new _SinkTransformerStreamSubscription
  dart:async/stream_transformers.dart 185:13                    _BoundSinkStream.listen
  package:analysis_server_client/server.dart 65:10              Server.listenToOutput
  package:dartfix/src/driver.dart 79:12                         Driver.startServer
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:dartfix/src/driver.dart                               Driver.startServer
  package:dartfix/src/driver.dart 48:16                         Driver.start
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  pkg/dartfix/test/src/driver_test.dart                         main.<fn>
  package:test/src/backend/declarer.dart 168:27                 Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:test/src/backend/declarer.dart                        Declarer.test.<fn>.<fn>.<fn>
  package:test/src/backend/invoker.dart 250:15                  Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test/src/backend/invoker.dart 402:11                  Invoker._onRun.<fn>.<fn>.<fn>
  
00:08 +2 -1: run example
--- launching original example
--- launching fixed example
--- waiting for original example
--- waiting for fixed example
--- original example output
myDouble = 4.0

--- fixed example output
myDouble = 4.0

00:08 +3 -1: Some tests failed.

stderr:
Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -m release pkg/dartfix/test/src/driver_test

[00:14 | 100% | +    0 | -    1]
```

cc @danrubel

**Comment by aam** [comment]
Updating status file is not relevant it seems any more, so I ran approve_results scripts to get the bot to green:
```
$ tools/sdks/dart-sdk/bin/dart tools/approve_results.dart -b pkg-linux-release 
Selected bot: pkg-linux-release

The following tests are now succeeding:

The following tests are now failing:

BOT                TEST                              RESULT        EXPECTED
pkg-linux-release  pkg/dartfix/test/src/driver_test  RuntimeError  Pass

1 of 738 tests are failing (0.14%)
0 of 738 tests are flaky (0.00%)
737 of 738 tests were fixed since last approval (99.86%)
1 of 738 tests were broken since last approval (0.14%)

Note: It is assumed bugs have been filed about the above failures before they are approved here.
Note: Approving the failures will turn the bot green on the next commit.
Do you want to approve? (yes/no) [yes] yes

Uploading approved results...
Uploaded approved results for pkg-linux-release
Successfully approved results, the next commit will turn bots green
```

**Comment by stereotype441** [comment]
@danrubel FYI

**Comment by sortie** [comment]
I also approved it on pkg-mac-release and pkg-win-release where it had been flaky but had become non-flaky with this problem.
