### ISSUE TITLE
service/simple_reload_test fails in app_jitk mode due to bad paths

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#35506]
`service/simple_reload_test` is failing in app_jitk mode when the test attempts to spawn an isolate from a `Uri` while running from a snapshot. The `Uri` for the script to be spawned is built from the `Platform.script.path`, which points to the directory containing the snapshot when the test is running from the snapshot. Hardcoding a fully resolved path resolves the issue locally, but the test needs to be modified in such a way that the root of the SDK directory is known.

**Comment by dcharkes** [comment]
This showed up as a timeout besides a failures as well:
`>testee>err> IsolateSpawnException: Unable to spawn isolate: Error: Error when reading 'out/ReleaseX64/generated_compilations/app_jitk/runtime_observatory_tests_service_simple_reload_test/simple_reload/v1/main.dart': No such file or directory`

[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8925316284212781952/+/steps/vm_tests/0/stdout)

```dart
FAILED: app_jitk-vm release_x64 service/simple_reload_test
Expected: RuntimeError
Actual: Timeout

--- Command "app_jit" (took 06.000629s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --snapshot=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/app_jitk/runtime_observatory_tests_service_simple_reload_test/out.jitsnapshot --snapshot-kind=app-jit --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/simple_reload_test.dart

exit code:
0

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseX64/dart -DDART_SERVICE_USE_AUTH=false --profiler --snapshot=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/app_jitk/runtime_observatory_tests_service_simple_reload_test/out.jitsnapshot --snapshot-kind=app-jit --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --enable-vm-service:0 /b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/simple_reload_test.dart
>testee>out> Observatory listening on http://127.0.0.1:44504/
** Signaled to run test queries on http://127.0.0.1:44504/
>testee>out> 
Loading VM...
>testee>out> file:///b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/
Done loading VM
Running simple_reload_test.dart [1/4]
Paused with PauseBreakpoint
Running simple_reload_test.dart [2/4]
Running simple_reload_test.dart [3/4]
>testee>out> Instance of 'Isolate'
>testee>out> spawned isolate running
Paused with PauseBreakpoint
Running simple_reload_test.dart [4/4]
All service tests completed successfully.
** Killing script
** Process exited

--- Command "vm" (took 01:00.000563s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/app_jitk/runtime_observatory_tests_service_simple_reload_test/out.jitsnapshot

exit code:
-15

diagnostics:
Process list including children: [17643, 17655]
Trying to capture stack trace for pid 17643
PID 17643 - process
TID 17643:
#0  0x00007ffa527f5404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000557eea6e5288 dart::Monitor::WaitMicros(long)
#2  0x0000557eea8ec03a Dart_RunLoop
#3  0x0000557eea3ccafd dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
#4  0x0000557eea3cd807 dart::bin::main(int, char**)
#5  0x0000557eea3ce119 main
#6  0x00007ffa51f33f45 __libc_start_main
#7  0x0000557eea3cc029 _start
TID 17646:
#0  0x00007ffa520106d3 epoll_wait
#1  0x0000557eea3d5095 dart::bin::EventHandlerImplementation::Poll(unsigned long)
#2  0x0000557eea3f46de dart::bin::ThreadStart(void*)
#3  0x00007ffa527f1184 start_thread
#4  0x00007ffa5201003d __clone
TID 17650:
#0  0x00007ffa527f5404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000557eea6e5288 dart::Monitor::WaitMicros(long)
#2  0x0000557eea8b7cea dart::BackgroundCompiler::Run()
#3  0x0000557eea77e8a7 dart::ThreadPool::Worker::Loop()
#4  0x0000557eea77e733 dart::ThreadPool::Worker::Main(unsigned long)
#5  0x0000557eea6e4b79 dart::ThreadStart(void*)
#6  0x00007ffa527f1184 start_thread
#7  0x00007ffa5201003d __clone
TID 17656:
#0  0x00007ffa527f8e44 wait
#1  0x0000557eea3dc159 dart::bin::ExitCodeHandler::ExitCodeHandlerEntry(unsigned long)
#2  0x0000557eea3f46de dart::bin::ThreadStart(void*)
#3  0x00007ffa527f1184 start_thread
#4  0x00007ffa5201003d __clone
TID 17658:
#0  0x00007ffa527f5404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000557eea6e5288 dart::Monitor::WaitMicros(long)
#2  0x0000557eea8b7cea dart::BackgroundCompiler::Run()
#3  0x0000557eea77e8a7 dart::ThreadPool::Worker::Loop()
#4  0x0000557eea77e733 dart::ThreadPool::Worker::Main(unsigned long)
#5  0x0000557eea6e4b79 dart::ThreadStart(void*)
#6  0x00007ffa527f1184 start_thread
#7  0x00007ffa5201003d __clone


Trying to capture stack trace for pid 17655
PID 17655 - process
TID 17655:
#0  0x00007f856f0f7404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000556e35627288 dart::Monitor::WaitMicros(long)
#2  0x0000556e3569b66a dart::ServiceIsolate::Shutdown()
#3  0x0000556e3552034f dart::Dart::Cleanup()
#4  0x0000556e3530e4c9 dart::bin::ErrorExit(int, char const*, ...)
#5  0x0000556e3530eb5f dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
#6  0x0000556e3530f807 dart::bin::main(int, char**)
#7  0x0000556e35310119 main
#8  0x00007f856e835f45 __libc_start_main
#9  0x0000556e3530e029 _start
TID 17657:
#0  0x00007f856e9126d3 epoll_wait
#1  0x0000556e35317095 dart::bin::EventHandlerImplementation::Poll(unsigned long)
#2  0x0000556e353366de dart::bin::ThreadStart(void*)
#3  0x00007f856f0f3184 start_thread
#4  0x00007f856e91203d __clone
TID 17662:
#0  0x00007f856f0f7404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000556e35627288 dart::Monitor::WaitMicros(long)
#2  0x0000556e357f9cea dart::BackgroundCompiler::Run()
#3  0x0000556e356c08a7 dart::ThreadPool::Worker::Loop()
#4  0x0000556e356c0733 dart::ThreadPool::Worker::Main(unsigned long)
#5  0x0000556e35626b79 dart::ThreadStart(void*)
#6  0x00007f856f0f3184 start_thread
#7  0x00007f856e91203d __clone



stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseX64/dart -DDART_SERVICE_USE_AUTH=false --profiler --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --enable-vm-service:0 /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/app_jitk/runtime_observatory_tests_service_simple_reload_test/out.jitsnapshot
>testee>out> 
>testee>out> file:///b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/app_jitk/runtime_observatory_tests_service_simple_reload_test/
** Signaled to run test queries on http://127.0.0.1:36131/
>testee>out> Observatory listening on http://127.0.0.1:36131/
Loading VM...
Done loading VM
Running out.jitsnapshot [1/4]
Paused with PauseBreakpoint
Running out.jitsnapshot [2/4]
Running out.jitsnapshot [3/4]
>testee>err> Unhandled exception:
>testee>err> IsolateSpawnException: Unable to spawn isolate: Error: Error when reading 'out/ReleaseX64/generated_compilations/app_jitk/runtime_observatory_tests_service_simple_reload_test/simple_reload/v1/main.dart': No such file or directory
>testee>err> #0      Isolate.spawnUri (dart:isolate/runtime/libisolate_patch.dart:460:14)
>testee>err> <asynchronous suspension>
>testee>err> #1      testMain (file:///b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/simple_reload_test.dart:26:39)
>testee>err> <asynchronous suspension>
>testee>err> #2      _ServiceTesteeRunner.run (file:///b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/test_helper.dart:50:36)
>testee>err> <asynchronous suspension>
>testee>err> #3      runIsolateTests (file:///b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/test_helper.dart:410:32)
>testee>err> <asynchronous suspension>
>testee>err> #4      main (file:///b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/simple_reload_test.dart:74:15)
>testee>err> #5      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
>testee>err> #6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -n app_jitk-linux-release-x64 service/simple_reload_test
```
