### ISSUE TITLE
Observatory attempts to add to a closed StreamSink on VM shutdown

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#35502]
To reproduce:

run

``
out/DebugX64/dart --observe --enable-inlining-annotations --optimization_counter_threshold=10 --no-use-osr --no-background-compilation --ignore-unrecognized-flags --packages=.packages runtime/tests/vm/dart/truncating_ints_test.dart

Connect with observatory, open the 'debug' window, set a breakpoint at 'test_add' and then issue the 'continue' command. This results in the following exception.

```
sivalinuxmach[sdk]>out/DebugX64/dart --observe --enable-inlining-annotations --optimization_counter_threshold=10 --no-use-osr --no-background-compilation --ignore-unrecognized-flags --packages=.packages runtime/tests/vm/dart/truncating_ints_test.dart
Observatory listening on http://127.0.0.1:8181/
vm-service: isolate(86489733)  'truncating_ints_test.dart:main()' has no debugger attached and is paused at exit.  Connect to Observatory at http://127.0.0.1:8181/ to debug.
StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:_http/http_impl.dart:537:31)
#1      _StreamSinkImpl.add (dart:_http/http_impl.dart:542:7)
#2      _WebSocketImpl.add (dart:_http/websocket_impl.dart:1204:11)
#3      WebSocketClient.post (dart:vmservice_io/server.dart:78:18)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#8      Future._complete (dart:async/future_impl.dart:473:7)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#10     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#11     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#12     VMService.routeRequest (dart:_vmservice)
<asynchronous suspension>
#13     Client.onRequest (dart:_vmservice/client.dart:44:13)
#14     WebSocketClient.onWebSocketMessage (dart:vmservice_io/server.dart:52:13)
#15     new WebSocketClient.<anonymous closure> (dart:vmservice_io/server.dart:25:32)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#20     _StreamController._add (dart:async/stream_controller.dart:640:7)
#21     _StreamController.add (dart:async/stream_controller.dart:586:5)
#22     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1129:21)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#29     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#35     _StreamController._add (dart:async/stream_controller.dart:640:7)
#36     _StreamController.add (dart:async/stream_controller.dart:586:5)
#37     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1722:41)
#38     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#42     _StreamController._add (dart:async/stream_controller.dart:640:7)
#43     _StreamController.add (dart:async/stream_controller.dart:586:5)
#44     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1284:33)
#45     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```

**Comment by bkonyi** [comment]
This isn't as severe as we thought. `--observe` doesn't enable `--pause-isolates-on-start` by default, so following the reproduction steps above is equivalent to setting a breakpoint once the script has already finished executing. Continuing after this point causes the VM to exit, and the Observatory can be in the middle of trying to add data to an IOSink, causing the message above to be printed.

This isn't a crash, but isn't a good user experience either. Once #29554 is resolved this may become an actual crash if the exception isn't caught. Either way, this isn't a critical issue.

**Comment by bkonyi** [comment]
Now that #29554 is closed, we might see some crashes in observatory due to this issue.

**Comment by bkonyi** [comment]
It looks like this exception is already being handled, but we dump the stack to the console for some reason. [This change](https://dart-review.googlesource.com/c/sdk/+/94840) removes the needless print as this is an acceptable failure to swallow.
