### ISSUE TITLE
Assign a generic function to property in class

### ISSUE THREAD

**Issue by Means88** [dart-lang/sdk#35514]
```
Dart VM version: 2.0.0-dev.69.2 (Mon Jul 23 17:10:56 2018 +0200) on "macos_x64"
```
```dart
Type id<Type>(Type a) => a;

typedef FunctionType<T> = T Function(T);

class FunctionWrapper<T> {
  FunctionWrapper({
    this.func = id,  
  });

  FunctionType<T> func;
}

main() {
  final f = FunctionWrapper<int>();
  print(f.func(0));
}

```
Causes a runtime error:
```
Unhandled exception:
type '(T) => T' is not a subtype of type '(int) => int'
#0      main (file:///Users/means88/code/test/function.dart)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

```
Maybe an error should be thrown during the static checking if it was not supported.

**Comment by eernstg** [comment]
Clearly there's a bug in the reported behavior, and I think I've seen a relevant github issue. But I'm not working directly on these things and I can't find such an issue right now, so I'll leave it to others to pin that down.

However, one issue which is evident is that you don't get a compile-time error on `= id`, but you should.

The problem is that `id` has type `X Function<X>(X)`, but an attempt is made to use it to initialize an instance variable `func` of type `T Function(T)` (where `T` denotes the type variable of the enclosing class). There is no subtype relationship between those two function types, so this would just be a compile-time error in general.

However, Dart has a special mechanism addressing exactly this kind of type mismatch: Generic function instantiation. This is a mechanism where type inference is used to compute some actual type arguments to the generic function type (such that the resulting non-generic function type is assignable to the context type, here: the type of `func`).

So we could have had a regular assignment in the body of the constructor like `func = id`, and that would "just work", assigning an instantiation of the generic function `id` to `func` which has already received its type argument and become a function of type `T Function(T)`.

However, again, that is a dynamic operation (because the value of `T` differs according to the execution history), and this means that it cannot be a compile-time constant. More precisely, an occurrence of `id` which is subject to generic function instantiation involving a type variable from the enclosing class is not a constant expression. Consequently, it is a compile-time error to use it as a default value (in the given example, it is the default value for a named parameter).

This error is not reported, so I'm marking this as a bug in the common front end.

However, the fact that it runs and reports an error mentioning a type which contains a free type variable rather than its value would be another bug, and it might be better to create a separate issue for that (but that's the part that I'm leaving to someone else to handle ;-).

**Comment by jodinathan** [comment]
unfortunately this still happens

https://dartpad.dartlang.org/bf386455c236384861927f40101bbfda
