### ISSUE TITLE
webdev serve, DataTransferItem.getAsEntry returns 'NativeJavaScriptObject' instead of 'Entry'

### ISSUE THREAD

**Issue by Loonacy** [dart-lang/sdk#35510]
* Dart SDK Version 2.1.0
* Windows
* Chrome

When compiled with web serve, it throws an exception that says "Type 'NativeJavaScriptObject' is not a subtype of expected type 'Entry'."
When compiled with dart2js it works as expected.

Here's a sample of the code i'm using:

```
void main() {
	fileDivElement.onDrop.listen(_onFilesDrop);
}

void _onFilesDrop(MouseEvent event) async {
	event.stopPropagation();
	event.preventDefault();
	List<Entry> items = List<Entry>();
	for(int i=0; i<event.dataTransfer.items.length; i++) {
// ------------------- This is where it dies --------------------- //
		items.add(event.dataTransfer.items[i].getAsEntry()); 
	}
	_processFiles(items);
}
```

**Comment by natebosch** [comment]
cc @jmesserly - related to JS interop difference between dart2js and ddc?

**Comment by vsmenon** [comment]
I think when we hit this, @terrylucas typically adds a call to `registerExtension` on the unrecognized type (in `dart:html`) to map it to the Dart type.

**Comment by terrylucas** [comment]
Yep Looks like known problem that I've fixed in the past with registerExtension.  In this case type DataTransferItem needs registerExtension.

**Comment by Loonacy** [comment]
I just tried again with a bare project and got the same error.  I also tried with terrylucas' code with the same error.
More info on my environment:
Windows 10 Pro 1809 (OS Build 17763.253)
IntelliJ IDEA 2018.3.2 (Community edition)
Dart SDK 2.1.0
Chrome 71.0.3578.98 64-bit

I've attached the files I tested with.
My console log:

```
dart_sdk.js:18260 Got file drop
dart_sdk.js:18260 Pre-entry
dart_sdk.js:4858 Uncaught _js_helper.TypeErrorImpl.new {message: "Type 'NativeJavaScriptObject' is not a subtype of expected type 'Entry'.", Symbol(_error): Error
    at Object.dart.throw (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:48…}
dart.throw @ dart_sdk.js:4858
async._rethrow @ dart_sdk.js:27742
async._schedulePriorityAsyncCallback.dart.fn @ dart_sdk.js:27737
async._microtaskLoop @ dart_sdk.js:24434
async._startMicrotaskLoop @ dart_sdk.js:24440
internalCallback @ dart_sdk.js:24510
childList (async)
dart.fn.callback @ dart_sdk.js:24520
_scheduleImmediate @ dart_sdk.js:24496
async._scheduleAsyncCallback @ dart_sdk.js:24454
async._rootScheduleMicrotask @ dart_sdk.js:27793
scheduleMicrotask @ dart_sdk.js:27983
[_asyncCompleteError] @ dart_sdk.js:24124
async._asyncCompleteWithErrorCallback @ dart_sdk.js:23581
runBody @ dart_sdk.js:21875
async.async @ dart_sdk.js:21880
main._onFilesDrop @ main.dart:3
dart._checkAndCall @ dart_sdk.js:4668
dart.dcall @ dart_sdk.js:4673
(anonymous function).html$._wrapZone.dart.fn.e @ dart_sdk.js:96928
```

Log from terrylucas' code:
```
dart_sdk.js:18260 ENTER _onDragOver
dart_sdk.js:18260 EXIT _onDragOver
dart_sdk.js:18260 ENTER _onFilesDrop
dart_sdk.js:4858 Uncaught _js_helper.TypeErrorImpl.new {message: "Type 'NativeJavaScriptObject' is not a subtype of expected type 'FileEntry'.", Symbol(_error): Error
    at Object.dart.throw (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:48…}message: "Type 'NativeJavaScriptObject' is not a subtype of expected type 'FileEntry'."Symbol(_error): Error
    at Object.dart.throw (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:4857:29)
    at Object.dart.castError (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:4474:15)
    at Object.dart.as (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:4773:17)
    at Function.check_C [as _check] (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:4000:19)
    at _onFilesDrop (http://localhost:53322/main.ddc.js:50:40)
    at _onFilesDrop.next (<anonymous>)
    at runBody (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:21853:34)
    at Object.async.async (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:21880:7)
    at main._onFilesDrop (http://localhost:53322/main.ddc.js:37:18)
    at async._RootZone.new.runUnaryGuarded (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:27908:11)
    at _BroadcastSubscription.new.[_sendData] (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:22422:22)
    at _BroadcastSubscription.new.[_add] (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:22369:26)
    at _SyncBroadcastStreamController.new.[_sendData] (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:23054:29)
    at _SyncBroadcastStreamController.new.add (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:22864:24)
    at Object.dart._checkAndCall (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:4668:16)
    at Object.dart.dcall (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:4673:17)
    at HTMLDivElement.(anonymous function).html$._wrapZone.dart.fn.e (http://localhost:53322/packages/$sdk/dev_compiler/amd/dart_sdk.js:96928:96)hashCode: (...)runtimeType: (...)stackTrace: (...)Symbol(dartx.hashCode): (...)Symbol(dartx.runtimeType): (...)Symbol(dartx.stackTrace): (...)__proto__: Error
dart.throw @ dart_sdk.js:4858
async._rethrow @ dart_sdk.js:27742
async._schedulePriorityAsyncCallback.dart.fn @ dart_sdk.js:27737
async._microtaskLoop @ dart_sdk.js:24434
async._startMicrotaskLoop @ dart_sdk.js:24440
internalCallback @ dart_sdk.js:24510
childList (async)
dart.fn.callback @ dart_sdk.js:24520
_scheduleImmediate @ dart_sdk.js:24496
async._scheduleAsyncCallback @ dart_sdk.js:24454
async._rootScheduleMicrotask @ dart_sdk.js:27793
scheduleMicrotask @ dart_sdk.js:27983
[_asyncCompleteError] @ dart_sdk.js:24124
async._asyncCompleteWithErrorCallback @ dart_sdk.js:23581
runBody @ dart_sdk.js:21875
async.async @ dart_sdk.js:21880
main._onFilesDrop @ main.dart:13
runUnaryGuarded @ dart_sdk.js:27908
[_sendData] @ dart_sdk.js:22422
[_add] @ dart_sdk.js:22369
[_sendData] @ dart_sdk.js:23054
add @ dart_sdk.js:22864
dart._checkAndCall @ dart_sdk.js:4668
dart.dcall @ dart_sdk.js:4673
(anonymous function).html$._wrapZone.dart.fn.e @ dart_sdk.js:96928
```

[EntryTest.zip](https://github.com/dart-lang/sdk/files/2738619/EntryTest.zip)

**Comment by Loonacy** [comment]
Forgot to add, I tried dropping a file and a folder, neither works.
