### ISSUE TITLE
Null returnType in CodeChecker._checkImplicitCovarianceCast

### ISSUE THREAD

**Issue by AppleEducate** [dart-lang/sdk#35538]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.2.0-edge.88e6fe0f673e3d88f06fb6797103f9a9305961d9`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1920x1200  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/w3/2drj4mxn1wz7xjx378b4h2pr0000gq/T/report.txt

```
Dart analysis server, SDK version 2.2.0-edge.88e6fe0f673e3d88f06fb6797103f9a9305961d9, server version 1.21.1, error: Analysis failed: /Users/developer/Github/plugins/packages/native_widgets/lib/native_widgets.dart context: exception_20190102_094921_333
NoSuchMethodError: The getter 'returnType' was called on null.
Receiver: null
Tried calling: returnType
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      CodeChecker._checkImplicitCovarianceCast (package:analyzer/src/task/strong/checker.dart:812:37)
#2      CodeChecker.visitMethodInvocation (package:analyzer/src/task/strong/checker.dart:526:7)
#3      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7856:49)
#4      ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9444:18)
#5      CodeChecker.visitReturnStatement (package:analyzer/src/task/strong/checker.dart:578:10)
#6      ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:9440:49)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8351:20)
#8      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1254:17)
#9      RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:655:10)
#10     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1250:49)
#11     IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6065:21)

**Comment by srawlins** [comment]
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).
