### ISSUE TITLE
RangeError in ExtractMethodRefactoringImpl.isAvailable

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#35535]
Looks very similar to #33471 but has a different stack trace (is a different refactor):

```
Failed to handle request: {id: 1003, method: edit.getAvailableRefactorings, params: {file: C:\projects\dart-code\test\test_projects\hello_world\lib\empty.dart, length: 168, offset: 0}}
RangeError: Value not in range: 168
#0      _StringBase.substring (dart:core/runtime/libstring_patch.dart:377:7)
#1      StatementAnalyzer._hasTokens (package:analysis_server/src/services/correction/statement_analyzer.dart:209:33)
#2      StatementAnalyzer._checkSelectedNodes (package:analysis_server/src/services/correction/statement_analyzer.dart:194:11)
#3      StatementAnalyzer.visitCompilationUnit (package:analysis_server/src/services/correction/statement_analyzer.dart:83:7)
#4      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2416:49)
#5      ExtractMethodRefactoringImpl._checkSelection (package:analysis_server/src/services/refactoring/extract_method.dart:482:24)
#6      ExtractMethodRefactoringImpl.isAvailable (package:analysis_server/src/services/refactoring/extract_method.dart:404:13)
#7      EditDomainHandler._getAvailableRefactoringsImpl (package:analysis_server/src/edit/edit_domain.dart:624:14)
<asynchronous suspension>
#8      EditDomainHandler._getAvailableRefactorings (package:analysis_server/src/edit/edit_domain.dart:598:5)
#9      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:358:16)
#10     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:645:45)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#12     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:641:50)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1500:12)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:640:5)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#47     _rootRunUnary (dart:async/zone.dart:1132:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#52     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#53     _StreamController._add (dart:async/stream_controller.dart:639:7)
#54     _StreamController.add (dart:async/stream_controller.dart:585:5)
#55     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#56     _rootRunUnary (dart:async/zone.dart:1136:13)
#57     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#61     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#62     _StreamController._add (dart:async/stream_controller.dart:639:7)
#63     _StreamController.add (dart:async/stream_controller.dart:585:5)
#64     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#65     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#68     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#69     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

I think I may have sent a modification for the file while `getAvailableRefactorings` was in-flight.

**Comment by scheglov** [comment]
I believe these race conditions were fixed with switching to `ResolvedUnitResult`. 
https://github.com/dart-lang/sdk/commit/142641e596865bd3702431cb25687e14c5cfc3f2
