### ISSUE TITLE
Dart2JS' --dump-info crashes when compiling with -O0

### ISSUE THREAD

**Issue by miyoyo** [dart-lang/sdk#35560]
```
Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
Browser: Not Applicable (But Opera 56.0.3051.88)
```

```
>webdev build
Creating build script, took 15246ms
[INFO] Reading cached asset graph completed, took 348ms
[INFO] Checking for updates since last build completed, took 588ms
[INFO] build_web_compilers|entrypoint on web/main.dart:Running dart2js with -O0 --dump-info --packages=.package-acd735766d376bf964b4882c68067e9e -oweb/main.dart.js web/main.dart
[INFO] build_web_compilers|entrypoint on web/main.dart:Dart2Js finished with:

web/main.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.1.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'inferrer' was called on null.
Receiver: null
Tried calling: inferrer
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ElementInfoCollector._hasBeenResolved (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:164:59)
#2      ElementInfoCollector.visitField (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:121:36)
#3      ElementInfoCollector.visitLibrary.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:88:31)
#4      JsToElementMapBase._forEachLibraryMember.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/js_model/element_map_impl.dart:182:8)
#5      Iterable.forEach (dart:core/iterable.dart:277:30)
#6      JLibraryEnv.forEachMember (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/js_model/env.dart:114:23)
#7      JsToElementMapBase._forEachLibraryMember (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/js_model/element_map_impl.dart:181:16)
#8      JsElementEnvironment.forEachLibraryMember (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/js_model/element_map_impl.dart:1304:16)
#9      ElementInfoCollector.visitLibrary (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:80:17)
#10     Iterable.forEach (dart:core/iterable.dart:277:30)
#11     ElementInfoCollector.run (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:58:27)
#12     DumpInfoTask.dumpInfo.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:552:11)
#13     CompilerTask.measure (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63:51)
#14     DumpInfoTask.dumpInfo (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/dump_info.dart:549:5)
#15     Compiler.generateJavaScriptCode (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:379:20)
#16     Compiler.compileLoadedLibraries.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:395:9)
#17     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#18     Compiler.compileLoadedLibraries (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:389:14)
#19     Compiler.runInternal (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:276:5)
<asynchronous suspension>
#20     Compiler.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:216:38)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     Compiler.run.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:216:20)
#23     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#24     Compiler.run (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:213:41)
#25     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/apiimpl.dart:148:22)
#26     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)


[INFO] Running build completed, took 2.5s
[INFO] Caching finalized dependency graph completed, took 151ms
[INFO] Reading manifest at build\.build.manifest completed, took 1ms
[INFO] Deleting previous outputs in `build` completed, took 62ms
[INFO] Creating merged output dir `build` completed, took 301ms
[INFO] Writing asset manifest completed, took 6ms
[INFO] Succeeded after 3.1s with 2 outputs (2 actions)
[WARNING] BuildModules:
Failed to clean up temp dir C:\Users\miyoyo\AppData\Local\Temp\scratch_spacef4b650f0-1030-11e9-87cf-005056c00008.
```

**Comment by sigmundch** [comment]
Thanks for reporting @miyoyo!

It appears like we fixed it this recently while trying to fix something else. The fix landed in 0fded45406. It is not in the stable channel yet, but it made it on the dev channel starting version `2.1.1-dev.0.0`.

Thanks again!
