### ISSUE TITLE
RangeError in _LibraryResynthesizer.buildLibrary when using package:analyzer (0.34.1)

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#35621]
Steps to reproduce: running `pana` on `fenris`.

Exception:
````
stderr: Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libarray.dart:137:52)
#1      _LibraryResynthesizer.buildLibrary (package:analyzer/src/summary/resynthesize.dart:728:53)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:362:53)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#4      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:327:36)
#5      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:219:14)
#6      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:353:42)
#7      LibraryElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:882:45)
#8      LibraryElementHandle.exportNamespace (package:analyzer/src/dart/element/handle.dart:895:36)
#9      NamespaceBuilder._getExportMapping (package:analyzer/src/dart/resolver/scope.dart:840:17)
#10     NamespaceBuilder.createImportNamespaceForDirective (package:analyzer/src/dart/resolver/scope.dart:702:42)
#11     ImportElementImpl.namespace (package:analyzer/src/dart/element/element.dart:5028:32)
#12     LibraryImportScope._createImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:462:43)
#13     new LibraryImportScope (package:analyzer/src/dart/resolver/scope.dart:371:5)
#14     new LibraryScope (package:analyzer/src/dart/resolver/scope.dart:566:19)
#15     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:110:25)
#16     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:88:14)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:87:43)
#19     AnalysisDriver._computeResolvedLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1497:65)
#20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#21     AnalysisDriver._computeResolvedLibrary (package:analyzer/src/dart/analysis/driver.dart:1484:20)
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1103:22)
<asynchronous suspension>
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2114:24)
<asynchronous suspension>
#24     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2055:5)
#25     PackageBuilder.driver (package:dartdoc/src/model.dart:6475:17)
#26     PackageBuilder.buildPackageGraph (package:dartdoc/src/model.dart:6363:38)
````

**Comment by stereotype441** [comment]
Escalating to P1 due to duplicate report
