### ISSUE TITLE
Flaky asan failure in lib_2/isolate/regress_flutter_22796_test

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35633]
```dart
FAILED: dartk-vm release_x64 lib_2/isolate/regress_flutter_22796_test
Expected: Pass
Actual: Fail

--- Command "vm" (took 01.000833s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/lib_2/isolate/regress_flutter_22796_test.dart

exit code:
1

stdout:
ok

stderr:
=================================================================
==10329==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x56140b0f8b32 in operator new(unsigned long) /b/s/w/ir/kitchen-workdir/llvm-project/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x56140bbfd12d in dart::VirtualMemory::AllocateAligned(long, long, bool, char const*) ../../out/ReleaseX64/../../runtime/vm/virtual_memory_linux.cc:89:10
    #2 0x56140c098832 in dart::HeapPage::Allocate(long, dart::HeapPage::PageType, char const*) ../../out/ReleaseX64/../../runtime/vm/heap/pages.cc:63:27
    #3 0x56140c098832 in dart::PageSpace::AllocatePage(dart::HeapPage::PageType, bool) ../../out/ReleaseX64/../../runtime/vm/heap/pages.cc:305
    #4 0x56140c099f47 in dart::PageSpace::TryAllocateInFreshPage(long, dart::HeapPage::PageType, dart::PageSpace::GrowthPolicy, bool) ../../out/ReleaseX64/../../runtime/vm/heap/pages.cc:461:22
    #5 0x56140c083596 in dart::PageSpace::TryAllocate(long, dart::HeapPage::PageType, dart::PageSpace::GrowthPolicy) ../../out/ReleaseX64/../../runtime/vm/heap/pages.h:259:12
    #6 0x56140c083596 in dart::Heap::AllocateOld(long, dart::HeapPage::PageType) ../../out/ReleaseX64/../../runtime/vm/heap/heap.cc:85
    #7 0x56140b7ce5dd in dart::Object::Allocate(long, long, dart::Heap::Space) ../../out/ReleaseX64/../../runtime/vm/object.cc
    #8 0x56140b8c00f7 in dart::Instructions::New(long, bool, unsigned long) ../../out/ReleaseX64/../../runtime/vm/object.cc:12088:9
    #9 0x56140b8db26c in dart::Code::FinalizeCode(char const*, dart::FlowGraphCompiler*, dart::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*) ../../out/ReleaseX64/../../runtime/vm/object.cc:14269:51
    #10 0x56140b8dc9bb in dart::Code::FinalizeCode(dart::Function const&, dart::FlowGraphCompiler*, dart::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*) ../../out/ReleaseX64/../../runtime/vm/object.cc
    #11 0x56140c03b1e3 in dart::CompileParsedFunctionHelper::FinalizeCompilation(dart::Assembler*, dart::FlowGraphCompiler*, dart::FlowGraph*) ../../out/ReleaseX64/../../runtime/vm/compiler/jit/compiler.cc:386:29
    #12 0x56140c03eeb1 in dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*) ../../out/ReleaseX64/../../runtime/vm/compiler/jit/compiler.cc:707:17
    #13 0x56140c04106b in dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long) ../../out/ReleaseX64/../../runtime/vm/compiler/jit/compiler.cc:800:46
    #14 0x56140c043c46 in dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long) ../../out/ReleaseX64/../../runtime/vm/compiler/jit/compiler.cc:1071:10
    #15 0x56140c04812a in dart::BackgroundCompiler::Run() ../../out/ReleaseX64/../../runtime/vm/compiler/jit/compiler.cc:1486:11
    #16 0x56140bbc79ff in dart::ThreadPool::Worker::Loop() ../../out/ReleaseX64/../../runtime/vm/thread_pool.cc:381:11
    #17 0x56140bbc76bd in dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseX64/../../runtime/vm/thread_pool.cc:436:27
    #18 0x56140b9a1ebd in dart::ThreadStart(void*) ../../out/ReleaseX64/../../runtime/vm/os_thread_linux.cc:131:5
    #19 0x7f77cb838183 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8183)

SUMMARY: AddressSanitizer: 32 byte(s) leaked in 1 allocation(s).

--- Re-run this test:
python tools/test.py -n dartk-asan-linux-release-x64 lib_2/isolate/regress_flutter_22796_test
```

Looking back 1500 builds, it started happening 9 days ago, it didn't happen before that: [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924685557526335072/+/steps/vm_tests/0/stdout), [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924813846634812048/+/steps/vm_tests/0/stdout), [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8925389227343651040/+/steps/vm_tests/0/stdout)

**Comment by dcharkes** [comment]
The [test itself](https://github.com/dart-lang/sdk/blob/master/tests/lib_2/isolate/regress_flutter_22796_test.dart) hasn't changed in the last months, so it must be a regression in the VM.

@mraleph: any ideas?

**Comment by dcharkes** [comment]
It doesn't reproduce on my machine:

```
$ python tools/test.py -n dartk-asan-linux-release-x64 --repeat 1000 lib_2/isolate/regress_flutter_22796_test
tools/testing/dart/main.dart:1: Warning: Interpreting this as package URI, 'package:test_dart/main.dart'.
Test configuration:
    dartk-asan-linux-release-x64(architecture: x64, compiler: dartk, mode: release, runtime: vm, system: linux, builder-tag: asan, vm-options: [], timeout: 240, preview-dart-2)
Suites tested: lib_2
[03:16 | 100% | + 1000 | -    0]
```

**Comment by a-siva** [comment]
This appears to be a duplicate of https://github.com/dart-lang/sdk/issues/35795
