### ISSUE TITLE
null deref in _TypeToConvert.allElements

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#35648]
I ran `flutter analyze --watch` in a directory that happened to contain an old checkout of flutter, including the Dart SDK, and this freaked out the analyzer:

```
Error from the analysis server: Analysis failed: /home/ianh/dev/temp/flutter/bin/cache/dart-sdk/lib/core/annotations.dart
NoSuchMethodError: The getter 'isNotEmpty' was called on null.
Receiver: null
Tried calling: isNotEmpty
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _TypeToConvert.allElements.<anonymous closure> (package:analyzer/error/listener.dart:344:52)
#2      WhereIterator.moveNext (dart:_internal/iterable.dart:439:11)
#3      new List.from (dart:core/runtime/libarray_patch.dart:40:17)
#4      Iterable.toList (dart:core/iterable.dart:398:16)
#5      _TypeToConvert.allElements (package:analyzer/error/listener.dart:344:64)
#6      ErrorReporter._convertTypeNames (package:analyzer/error/listener.dart:231:49)
#7      ErrorReporter.reportTypeErrorForNode (package:analyzer/error/listener.dart:187:5)
#8      ErrorVerifier._checkForAssignableExpressionAtType (package:analyzer/src/generated/error_verifier.dart:2245:22)
#9      ErrorVerifier._checkForArgumentTypeNotAssignable (package:analyzer/src/generated/error_verifier.dart:2143:7)
#10     ErrorVerifier._checkForArgumentTypeNotAssignableWithExpectedTypes (package:analyzer/src/generated/error_verifier.dart:2185:5)
#11     ErrorVerifier._checkForArgumentTypeNotAssignableForArgument (package:analyzer/src/generated/error_verifier.dart:2164:5)
#12     ErrorVerifier._checkForArgumentTypesNotAssignableInList (package:analyzer/src/generated/error_verifier.dart:2204:7)
#13     ErrorVerifier.visitArgumentList (package:analyzer/src/generated/error_verifier.dart:339:5)
#14     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:419:49)
#15     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6617:20)
#16     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:943:10)
#17     ErrorVerifier.visitInstanceCreationExpression (package:analyzer/src/generated/error_verifier.dart:897:13)
#18     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6528:15)
#19     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4059:18)
#20     RecursiveAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:817:10)
#21     ErrorVerifier.visitExpressionFunctionBody (package:analyzer/src/generated/error_verifier.dart:657:13)
#22     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:4055:15)
#23     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7733:12)
#24     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1015:10)
#25     ErrorVerifier.visitMethodDeclaration (package:analyzer/src/generated/error_verifier.dart:981:13)
#26     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7724:49)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8351:20)
#28     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#29     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:691:10)
#30     ErrorVerifier.visitClassDeclaration (package:analyzer/src/generated/error_verifier.dart:492:13)
#31     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#32     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8351:20)
#33     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#34     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:715:10)
#35     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:529:11)
#36     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#37     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:347:10)
#38     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure>
(package:analyzer/src/dart/analysis/library_analyzer.dart:124:9)
#39     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#40     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:123:13)
#41     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#42     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:122:34)
#43     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:88:14)
#44     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#45     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:87:43)
#46     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1430:63)
#47     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#48     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#49     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1223:33)
<asynchronous suspension>
#50     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2114:24)
<asynchronous suspension>
#51     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2055:5)
#52     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#53     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#54     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#55     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#56     _rootRun (dart:async/zone.dart:1124:13)
#57     _CustomZone.run (dart:async/zone.dart:1021:19)
#58     _runZoned (dart:async/zone.dart:1516:10)
#59     runZoned (dart:async/zone.dart:1463:12)
#60     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#61     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#62     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#63     main (file:///b/rr/tmpJV1_1s/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#64     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#65     main (file:///b/rr/tmpJV1_1s/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#66     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#67     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by srawlins** [comment]
Closing as stale; please re-open if you see this crash again.
