### ISSUE TITLE
Crash in Fasta type inference on malformed for-in statement

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#35651]
This test program:

```dart
main() {
  const int x;
  for (x in [1, 2, 3]) {
    print(x);
  }
}
```

crashes Fasta in type inference:

```
Unhandled exception:
Crash when compiling file:///**snip**/programs/dart/constants.dart,
at character offset 5:
file:///**snip**/programs/dart/constants.dart:3:8: Internal problem: Unhandled SyntheticExpressionJudgment in handleForInStatementWithoutVariable.
  for (x in [1, 2, 3]) {
       ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:43:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:56:10)
#2      InferenceVistor.handleForInStatementWithoutVariable (file:///**snip**/dart.git/sdk/pkg/front_end/lib/src/fasta/kernel/inference_visitor.dart:340:7)
#3      InferenceVistor.visitForInStatement (file:///**snip**/dart.git/sdk/pkg/front_end/lib/src/fasta/kernel/inference_visitor.dart:369:7)
#4      ForInStatement.accept1 (package:kernel/ast.dart:3983:42)
#5      ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1544:24)
#6      InferenceVistor.visitBlockJudgment (file:///**snip**/dart.git/sdk/pkg/front_end/lib/src/fasta/kernel/inference_visitor.dart:76:16)
```

FYI @peter-ahe-google

**Comment by peter-ahe-google** [comment]
Proposed fix https://dart-review.googlesource.com/c/sdk/+/89515
