### ISSUE TITLE
Flaky failures of co19_2/LibTest/io/Stdin/readLineSync_A03_t02

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#35676]
The error is:

```
FAILED: dartk-vm release_simdbc64 co19_2/LibTest/io/Stdin/readLineSync_A03_t02
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 01.000062s):
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Stdin_readLineSync_A03_t02/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/Stdin/readLineSync_A03_t02.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 538ms):
DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Stdin_readLineSync_A03_t02/out.dill

exit code:
255

stderr:
Unhandled exception:
FileSystemException: Cannot delete file, path = '/b/s/w/it2gGwQ2/out_HeRWpF/out_6445-9674-7002-5331.tmp' (OS Error: No such file or directory, errno = 2)
#0      _File._delete.<anonymous closure> (dart:io/file_impl.dart:291:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#9      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -n dartk-mac-release-simdbc64 co19_2/LibTest/io/Stdin/readLineSync_A03_t02
```

The test has been seen to fail on `dartk-linux-release-x64` (3 times), `dartk-linux-product-x64` (2 times) and `dartk-mac-release-simdbc64` (once).

For example:

```
https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/vm-kernel-linux-release-x64/3391
```

**Comment by dcharkes** [comment]
Same for `co19_2/LibTest/io/Stdin/readLineSync_A03_t03` on product_x64: [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924002089590451104/+/steps/vm_co19_tests_shard_2/0/stdout)

```dart
FAILED: dartk-vm product_x64 co19_2/LibTest/io/Stdin/readLineSync_A03_t03
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 01.000166s):
DART_CONFIGURATION=ProductX64 out/ProductX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/io/Stdin/readLineSync_A03_t03.dart

exit code:
255

stderr:
Unhandled exception:
FileSystemException: Cannot delete file, path = '/b/s/w/itFJHsEZ/readLineSync_A03_t03_VPBMOV/readLineSync_A03_t03_8538-1998-8340-1393.tmp' (OS Error: No such file or directory, errno = 2)
#0      _File._delete.<anonymous closure> (dart:io/file_impl.dart:291:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#9      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -n dartk-linux-product-x64 co19_2/LibTest/io/Stdin/readLineSync_A03_t03
```

Multiple readLineSync tests fail:

```sql
select test_name, count(*) as count, min(commit_time) as earliest, max(commit_time) as latest
from `dart-ci.results.results`
where name like "co19_2/LibTest/io/Stdin/readLineSync%"
and result <> "Pass"
group by test_name order by test_name
```

| test_name                             | count | earliest                | latest                  |
| ------------------------------------- | ----- | ----------------------- | ----------------------- |
| LibTest/io/Stdin/readLineSync_A03_t01 | 2     | 2019-01-02 14:30:44 UTC | 2019-01-15 11:34:42 UTC |
| LibTest/io/Stdin/readLineSync_A03_t02 | 7     | 2018-12-13 12:53:09 UTC | 2019-01-17 14:59:18 UTC |
| LibTest/io/Stdin/readLineSync_A03_t03 | 7     | 2018-12-11 19:18:10 UTC | 2019-01-18 09:44:18 UTC |
| LibTest/io/Stdin/readLineSync_A04_t01 | 6     | 2019-01-04 14:44:00 UTC | 2019-01-17 08:48:48 UTC |

Under multiple configurations:

| configuration                | count | earliest                | latest                  |
| ---------------------------- | ----- | ----------------------- | ----------------------- |
| dartk-linux-product-x64      | 3     | 2018-12-20 11:12:49 UTC | 2019-01-18 09:44:18 UTC |
| dartk-linux-release-simdbc64 | 5     | 2018-12-11 19:18:10 UTC | 2019-01-17 14:59:18 UTC |
| dartk-linux-release-x64      | 5     | 2018-12-13 12:53:09 UTC | 2019-01-09 20:10:31 UTC |
| dartk-mac-debug-simdbc64     | 1     | 2019-01-14 18:50:29 UTC | 2019-01-14 18:50:29 UTC |
| dartk-mac-product-x64        | 4     | 2019-01-04 18:35:53 UTC | 2019-01-15 15:52:54 UTC |
| dartk-mac-release-simdbc64   | 2     | 2019-01-02 14:30:44 UTC | 2019-01-16 08:22:09 UTC |
| dartk-mac-release-x64        | 2     | 2019-01-14 15:51:46 UTC | 2019-01-17 08:48:48 UTC |
