### ISSUE TITLE
"error: Not a constant expression: unexpected kernel tag ConstructorInvocation (31)"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#35683]
If you run this:

```
class Test {
  Test({ this.test = Duration(minutes: 1) }); // the default value is not explicitly "const"
  final Duration test;
}

void main() {
  Test();
}
```

...you get:

```
Unhandled exception:
'file:///home/ianh/dev/scratch/test.dart': error: Not a constant expression: unexpected kernel tag ConstructorInvocation (31)
#0      main (file:///home/ianh/dev/scratch/test.dart:8:3)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

...which is a horrible error message.

**Comment by clearloop** [comment]
You can run:

```dart
class Test {
  Test({Duration test}) : test = test ?? Duration(minutes: 1);
  final Duration test;
}

void main() {
  Test();
}
```

Frankly speaking, I'm not sure about the difference between these two constructor invocations...

It seems like, we should use `Test({...}): ...;` when our classes contain other classes.

**Comment by gnprice** [comment]
This appears to have been fixed:

```
$ dart tmp.dart
tmp.dart:2:22: Error: Constant expression expected.
Try inserting 'const'.
  Test({ this.test = Duration(minutes: 1) }); // the default value is not explicitly "const"
                     ^^^^^^^^

$ dart --version
Dart SDK version: 2.19.1 (stable) (Unknown timestamp) on "linux_x64"
```
