### ISSUE TITLE
NPE in BestPracticesVerifier._checkForDeprecatedMemberUse

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35814]
We're seeing several instances of a stack trace like this one, coming from SDK version 2.1.1-dev.2.0 (fe73eaab0ab, which is based on bleeding edge d9944433af2).  Example stack trace:

```
Exception
Dart analysis server, SDK version 2.1.1-dev.2.0, server version 1.22.1, error: Captured exception
NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains("...redacted...")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      BestPracticesVerifier._checkForDeprecatedMemberUse (package:analyzer/src/generated/resolver.dart:725:45)
#2      BestPracticesVerifier._checkForDeprecatedMemberUseAtIdentifier (package:analyzer/src/generated/resolver.dart:757:5)
#3      BestPracticesVerifier.visitSimpleIdentifier (package:analyzer/src/generated/resolver.dart:575:5)
#4      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9799:49)
#5      PrefixedIdentifierImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9086:18)
#6      RecursiveAstVisitor.visitPrefixedIdentifier (package:analyzer/dart/ast/visitor.dart:1087:10)
#7      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9081:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8372:20)
#9      ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:423:16)
#10     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:613:10)
#11     BestPracticesVerifier.visitArgumentList (package:analyzer/src/generated/resolver.dart:356:11)
#12     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:419:49)
#13     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7884:20)
#14     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1021:10)
#15     BestPracticesVerifier.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:524:11)
#16     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7877:49)
#17     ConditionalExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2575:22)
#18     RecursiveAstVisitor.visitConditionalExpression (package:analyzer/dart/ast/visitor.dart:721:10)
#19     ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:2570:15)
#20     ParenthesizedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8730:18)
#21     RecursiveAstVisitor.visitParenthesizedExpression (package:analyzer/dart/ast/visitor.dart:1063:10)
#22     ParenthesizedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:8726:15)
#23     AssignmentExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:839:21)
#24     RecursiveAstVisitor.visitAssignmentExpression (package:analyzer/dart/ast/visitor.dart:637:10)
#25     BestPracticesVerifier.visitAssignmentExpression (package:analyzer/src/generated/resolver.dart:371:11)
#26     AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:834:49)
#27     ParenthesizedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8730:18)
#28     RecursiveAstVisitor.visitParenthesizedExpression (package:analyzer/dart/ast/visitor.dart:1063:10)
#29     ParenthesizedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:8726:15)
#30     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4256:18)
#31     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:823:10)
#32     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4252:49)
#33     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8372:20)
#34     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1254:17)
#35     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:655:10)
#36     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1250:49)
#37     IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6071:21)
#38     RecursiveAstVisitor.visitIfStatement (package:analyzer/dart/ast/visitor.dart:919:10)
#39     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:6066:49)
#40     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8372:20)
#41     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1254:17)
#42     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:655:10)
#43     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1250:49)
#44     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1199:13)
#45     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:661:10)
#46     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1195:49)
#47     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7739:12)
#48     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1015:10)
#49     BestPracticesVerifier.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:509:13)
#50     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7730:49)
#51     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8372:20)
#52     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#53     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:691:10)
#54     BestPracticesVerifier.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:397:13)
#55     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#56     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8372:20)
#57     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2443:21)
#58     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:715:10)
#59     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2436:49)
#60     LibraryAnalyzer._computeHints (package:analyzer/src/dart/analysis/library_analyzer.dart:214:10)
#61     LibraryAnalyzer.analyzeSync.. (package:analyzer/src/dart/analysis/library_analyzer.dart:149:11)
#62     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#63     LibraryAnalyzer.analyzeSync. (package:analyzer/src/dart/analysis/library_analyzer.dart:148:15)
#64     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#65     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:134:35)
#66     LibraryAnalyzer.analyze. (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#67     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#68     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#69     AnalysisDriver._computeAnalysisResult. (package:analyzer/src/dart/analysis/driver.dart:1431:63)
#70     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#71     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#72     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1473:37)
#73     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1124:39)

#74     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)

#75     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#76     new AnalysisServer (package:analysis_server/src/analysis_server.dart:215:29)
#77     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:85:26)
#78     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#79     Driver.startAnalysisServer. (package:analysis_server/src/server/driver.dart:526:21)
#80     _rootRun (dart:async/zone.dart:1124:13)
#81     _CustomZone.run (dart:async/zone.dart:1021:19)
#82     _runZoned (dart:async/zone.dart:1516:10)
#83     runZoned (dart:async/zone.dart:1463:12)
#84     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:604:12)
#85     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#86     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#87     main (file:...redacted...)
#88     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#89     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#90     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#91     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#92     Future._complete (dart:async/future_impl.dart:473:7)
#93     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#94     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#95     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#96     Dropbox.writeRow (package:dart.tools.silo/dropbox.dart)
#97     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#98     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#99     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#100    Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#101    Future._complete (dart:async/future_impl.dart:473:7)
#102    _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#103    _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#104    _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#105    _SiloFile.save (package:dart.tools.silo/dropbox.dart)
#106    _RootZone.runUnary (dart:async/zone.dart:1379:54)
#107    _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#108    Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#109    Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#110    Future._completeWithValue (dart:async/future_impl.dart:483:5)
#111    Future._asyncComplete. (dart:async/future_impl.dart:513:7)
#112    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#113    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#114    _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#115    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

#0      AnalysisDriver._computeAnalysisResult. (package:analyzer/src/dart/analysis/driver.dart:1467:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#3      AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1473:37)
#4      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1124:39)

#5      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)

#6      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#7      new AnalysisServer (package:analysis_server/src/analysis_server.dart:215:29)
#8      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:85:26)
#9      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#10     Driver.startAnalysisServer. (package:analysis_server/src/server/driver.dart:526:21)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:604:12)
#16     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#17     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#18     main (file:...redacted...)
#19     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#23     Future._complete (dart:async/future_impl.dart:473:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#26     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#27     Dropbox.writeRow (package:dart.tools.silo/dropbox.dart)
#28     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#32     Future._complete (dart:async/future_impl.dart:473:7)
#33     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#34     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#35     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#36     _SiloFile.save (package:dart.tools.silo/dropbox.dart)
#37     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#41     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#42     Future._asyncComplete. (dart:async/future_impl.dart:513:7)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by stereotype441** [comment]
Internal bug reports:
- https://buganizer.corp.google.com/issues/123599081
- https://buganizer.corp.google.com/issues/123589861
- https://buganizer.corp.google.com/issues/123645437

**Comment by scheglov** [comment]
Looks like https://dart-review.googlesource.com/c/sdk/+/88881 uses _workspacePackage, added in https://dart-review.googlesource.com/c/sdk/+/88127, and this package might be null.

There is also https://dart-review.googlesource.com/c/sdk/+/89167 that adds `PubWorkspacePackage`, but probably not fixing this issue.

**Comment by stereotype441** [comment]
@srawlins can you have a look?

**Comment by srawlins** [comment]
I can look today. I think it will not be hard to fix.
