### ISSUE TITLE
Resynthesizer: type 'DynamicElementImpl' is not a subtype of type 'ElementHandle'

### ISSUE THREAD

**Issue by kika** [dart-lang/sdk#35838]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-182.5107.16.33.5199772`
- `2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b`
- `AI-182.5107.16.33.5199772, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1024x1280, 2560x1440, 1024x1280`

Hey, it's me again with my hundreds of exceptions a day from dart analyzer! Today it's something new, haven't seen it before (not that I look at each and every one of them, I'm now clicking on "Restart analyzer" button faster than Olympic shooter).

# Exception

```
Dart analysis server, SDK version 2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b, server version 1.21.1, error: Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart context: exception_20190202_202205_212
type 'DynamicElementImpl' is not a subtype of type 'ElementHandle'
#0      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1000:19)
#1      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:978:15)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1372:28)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:472:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7162:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7059:5)
#6      _ParameterElementImpl&VariableElementImpl&ParameterElementMixin.appendToWithoutDelimiters (package:analyzer/src/dart/element/element.dart:7263:18)
#7      ExecutableElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:3885:19)
#8      MethodElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:6079:11)
#9      ElementImpl.toString (package:analyzer/src/dart/element/element.dart:3164:5)
#10     _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:836:19)
#11     new _ElementMismatchException (package:analyzer/src/generated/declaration_resolver.dart:971:65)
#12     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:52:17)
#13     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:597:31)
#14     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:118:7)
#15     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#16     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:117:11)
#17     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#20     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1431:63)
#21     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#22     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#23     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1203:17)
<asynchronous suspension>
#24     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)
<asynchronous suspension>
#25     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#26     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#27     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#28     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#29     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#35     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#36     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#37     main (file:///b/rr/tmpFYAHZv/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#38     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#39     main (file:///b/rr/tmpFYAHZv/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#40     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1549167720737 <= {"id":"63","result":{"assists":[{"message":"Convert to async function body","edits":[{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","fileStamp":0,"ed
1549167722387 => {"id":"64","method":"analysis.updateContent","params":{"files":{"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart":{"type":"add","content":"part of project_widgets
1549167722387 => {"id":"65","method":"completion.getSuggestions","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":2205},"clientRequestTime":1549167722
1549167722388 <= {"id":"64","result":{}}
1549167722389 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1549167722492 <= {"id":"65","result":{"id":"15"}}
1549167722492 <= {"event":"completion.results","params":{"id":"15","replacementOffset":2205,"replacementLength":0,"results":[],"isLast":true}}
1549167722500 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1549167722677 => {"id":"66","method":"analysis.updateContent","params":{"files":{"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart":{"type":"add","content":"part of project_widgets
1549167722677 => {"id":"67","method":"completion.getSuggestions","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":2206},"clientRequestTime":1549167722
1549167722678 <= {"id":"66","result":{}}
1549167722678 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1549167722777 <= {"id":"67","result":{"id":"16"}}
1549167722777 <= {"event":"completion.results","params":{"id":"16","replacementOffset":2206,"replacementLength":0,"results":[],"isLast":true}}
1549167722785 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1549167722803 => {"id":"68","method":"edit.getAssists","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":2206,"length":0},"clientRequestTime":154916772
1549167722804 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1549167722902 <= {"id":"68","result":{"assists":[]}}
1549167722905 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1549167723478 => {"id":"69","method":"analysis.updateContent","params":{"files":{"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart":{"type":"add","content":"part of project_widgets
1549167723479 <= {"id":"69","result":{}}
1549167723479 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1549167723489 => {"id":"70","method":"edit.getAssists","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":2209,"length":0},"clientRequestTime":154916772
1549167723601 <= {"id":"70","result":{"assists":[]}}
1549167723609 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1549167725104 => {"id":"71","method":"analysis.updateContent","params":{"files":{"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart":{"type":"add","content":"part of project_widgets
1549167725109 <= {"id":"71","result":{}}
1549167725109 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1549167725112 => {"id":"72","method":"edit.getAssists","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":2205,"length":0},"clientRequestTime":154916772
1549167725220 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart context: exception_20190202_202205
```

**Comment by srawlins** [comment]
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).
