### ISSUE TITLE
Error run test_sample_asynchronous_extension.dart

### ISSUE THREAD

**Issue by micrcx** [dart-lang/sdk#35839]
When executing the $ dart test_sample_asynchronous_extension.dart command, an "Unhandled exception" error occurs:
```
michael_k@Dell-55RFD12 ~/Downloads/sdk-master/samples/sample_extension $ dart test_sample_asynchronous_extension.dart
Unhandled exception:
type 'Future<dynamic>' is not a subtype of type 'Future<List<int>>'
#0      RandomArray.randomArray (file:///home/michael_k/Downloads/sdk-master/samples/sample_extension/sample_asynchronous_extension.dart:32:5)
#1      main (file:///home/michael_k/Downloads/sdk-master/samples/sample_extension/test_sample_asynchronous_extension.dart:17:5)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
michael_k@Dell-55RFD12 ~/Downloads/sdk-master/samples/sample_extension $
```
Dart version: 2.2.0-dev.1.1:

```
michael_k@Dell-55RFD12 ~/Downloads/sdk-master/samples/sample_extension $ dart --version
Dart VM version: 2.2.0-dev.1.1 (Unknown timestamp) on "linux_x64"

```

**Comment by srawlins** [comment]
`test_sample_asynchronous_extension.dart` doesn't exist any more, but I get crashes on anything I try to run in there:

```none
$ xcodebuild/ReleaseX64/dart samples/sample_extension/test/sample_extension_test.dart 
+ xcodebuild/ReleaseX64/dart /var/folders/84/mf667nnx3k72cb2h2b2btt6r005w15/T/sample_extension_jabd4S/test_sample_synchronous_extension.dart
Failing process stdout: 
Failing process stderr: dlopen(libsample_extension.dylib, 1): image not founderror: library handler failed

End failing process stderr
Unhandled exception:
Expect.fail('Test failed with exit code 254')
#0      Expect._fail (package:expect/expect.dart:665:5)
#1      Expect.fail (package:expect/expect.dart:275:5)
#2      run (file:///Users/srawlins/code/dart-sdk/sdk/samples/sample_extension/test/sample_extension_test_helper.dart:43:12)
<asynchronous suspension>
#3      testNativeExtensions (file:///Users/srawlins/code/dart-sdk/sdk/samples/sample_extension/test/sample_extension_test_helper.dart:85:13)
<asynchronous suspension>
#4      main (file:///Users/srawlins/code/dart-sdk/sdk/samples/sample_extension/test/sample_extension_test.dart:10:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Does something need to be built first?

CC @sjindel-google who has been in here most recently.

**Comment by sjindel-google** [comment]
If you've built both "runtime" and "create_sdk", it should work. I'm not sure if the sample-extension library is built with "create_sdk" alone.

**Comment by srawlins** [comment]
Ah, that fixes it; thanks! Now the two programs print:

```none
$ xcodebuild/ReleaseX64/dart samples/sample_extension/test/sample_extension_app_snapshot_test.dart 
+ xcodebuild/ReleaseX64/dart --snapshot=/var/folders/84/mf667nnx3k72cb2h2b2btt6r005w15/T/sample_extension_KW8ntz/test_sample_synchronous_extension.dart.snapshot --snapshot-kind=app-jit /var/folders/84/mf667nnx3k72cb2h2b2btt6r005w15/T/sample_extension_KW8ntz/test_sample_synchronous_extension.dart
+ xcodebuild/ReleaseX64/dart /var/folders/84/mf667nnx3k72cb2h2b2btt6r005w15/T/sample_extension_KW8ntz/test_sample_synchronous_extension.dart.snapshot
+ xcodebuild/ReleaseX64/dart --snapshot=/var/folders/84/mf667nnx3k72cb2h2b2btt6r005w15/T/sample_extension_KW8ntz/test_sample_asynchronous_extension.dart.snapshot --snapshot-kind=app-jit /var/folders/84/mf667nnx3k72cb2h2b2btt6r005w15/T/sample_extension_KW8ntz/test_sample_asynchronous_extension.dart
+ xcodebuild/ReleaseX64/dart /var/folders/84/mf667nnx3k72cb2h2b2btt6r005w15/T/sample_extension_KW8ntz/test_sample_asynchronous_extension.dart.snapshot
$ xcodebuild/ReleaseX64/dart samples/sample_extension/test/sample_extension_test.dart 
+ xcodebuild/ReleaseX64/dart /var/folders/84/mf667nnx3k72cb2h2b2btt6r005w15/T/sample_extension_Mha41Y/test_sample_synchronous_extension.dart
+ xcodebuild/ReleaseX64/dart /var/folders/84/mf667nnx3k72cb2h2b2btt6r005w15/T/sample_extension_Mha41Y/test_sample_asynchronous_extension.dart
```

**Comment by srawlins** [comment]
I cannot reproduce this; I think it has since been fixed. Please re-open if you encounter this again.
