### ISSUE TITLE
FixProcessor: type 'MixinDeclarationImpl' is not a subtype of type 'ClassDeclaration'

### ISSUE THREAD

**Issue by praveen-francium** [dart-lang/sdk#35857]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-183.5429.30`
- `2.1.0-dev.9.4`
- `IC-183.5429.30, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-43-generic, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, FATAL error: Failed to handle request: {id: 567, method: edit.getFixes, params: {file: /home/praveen/workspace/mortgage_agent_app/lib/scopped_models/user_model.dart, offset: 6534}, clientRequestTime: 1549342837911}
type 'MixinDeclarationImpl' is not a subtype of type 'ClassDeclaration'
#0      FixProcessor._addFix_undefinedMethod_create (package:analysis_server/src/services/correction/fix_internal.dart:3315:9)
<asynchronous suspension>
#1      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:535:13)
<asynchronous suspension>
#2      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:89:41)
<asynchronous suspension>
#3      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:580:49)
<asynchronous suspension>
#4      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:252:32)
<asynchronous suspension>
#5      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:360:9)
#6      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:645:45)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#8      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:641:50)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1500:12)
#13     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:640:5)
#14     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#16     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#17     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#26     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#27     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#28     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#35     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#36     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#37     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#38     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#39     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#40     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#41     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#43     _rootRunUnary (dart:async/zone.dart:1132:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#48     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#49     _StreamController._add (dart:async/stream_controller.dart:639:7)
#50     _StreamController.add (dart:async/stream_controller.dart:585:5)
#51     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#52     _rootRunUnary (dart:async/zone.dart:1136:13)
#53     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#57     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#58     _StreamController._add (dart:async/stream_controller.dart:639:7)
#59     _StreamController.add (dart:async/stream_controller.dart:585:5)
#60     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#61     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#64     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#65     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by stereotype441** [comment]
This was fixed by @scheglov in 2784473939b664efa46863ad85147745447ba796.
