### ISSUE TITLE
Crash when accidentally removed closing `}`

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#35900]
@danrubel 

Analyzer Feedback from IntelliJ

## Version information

- `IDEA 191.SNAPSHOT`
- `2.2.0-edge.ac95355fdb6075125b0a1536edf8a7efe7fddeef`
- `IC-191.SNAPSHOT, JRE 1.8.0_112-b16x64 Oracle Corporation, OS Mac OS X(x86_64) v10.14.3, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.ac95355fdb6075125b0a1536edf8a7efe7fddeef, server version 1.23.0, error: Captured exception
RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core/runtime/libstring_patch.dart:387:7)
#1      unescapeLastStringPart (package:front_end/src/fasta/quote.dart:132:24)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:257:17)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4797:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4722:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3997:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3930:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3742:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:4912:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4884:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4865:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4844:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4580:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3991:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3930:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3742:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#18     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3679:13)
#19     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5191:16)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3513:14)
#21     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#22     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5579:15)
#23     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3517:14)
#24     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#25     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5287:15)
#26     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3529:14)
#27     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#28     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3408:15)
#29     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3062:15)
#30     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2932:15)
#31     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2737:15)
#32     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1761:13)
#33     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1721:14)
#34     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:573:14)
#35     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:465:14)
#36     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#37     ParserAdapter.parseCompilationUnit2 (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/parser_fasta.dart:189:32)
#38     ParserAdapter.parseCompilationUnit (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/parser_fasta.dart:184:12)
#39     _File._parse (package:analyzer/src/services/available_declarations.dart:1339:23)
#40     _File.refresh (package:analyzer/src/services/available_declarations.dart:966:30)
#41     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:600:12)
#42     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:466:7)
#43     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:163:13)
<asynchronous suspension>
#44     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#45     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#46     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#47     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#48     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#49     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#50     _rootRun (dart:async/zone.dart:1124:13)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _runZoned (dart:async/zone.dart:1516:10)
#53     runZoned (dart:async/zone.dart:1463:12)
#54     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#55     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#56     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#57     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:12:11)
#58     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#59     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:10:10)
#60     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#61     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/cp/_32g44l548q8d0bfj4_l9s3m003ky_/T/report2.txt.

**Comment by bwilkerson** [comment]
Do you have a test case to reproduce the behavior? Was the curly brace part of a string interpolation, map literal or block?

**Comment by scheglov** [comment]
It was in a string interpolation in `print`, something like this.
`      print('${actualParameter.name}: ${actualParameter.type}');`

I cannot reproduce it reliably.

**Comment by danrubel** [comment]
@scheglov  Thank you for all the information. I am able to repo it locally and am testing a fix.
