### ISSUE TITLE
Command line arguments array is not List<String> in dart2js

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#35925]
Probably not something a lot of people run into, but while doing some profiling, I discovered:

```dart
void main(List<String> args) {
  args = args.toList();
}
```

Compile this with dart2js and run it (I used node):

```
$ dart2js bin/temp.dart
Compiled 7,375,932 characters Dart to 44,509 characters JavaScript in 0.51 seconds
$ node out.js
```

And I get:

```
~/out.js:563
      throw H.wrapException(H.TypeErrorImplementation$(object, function(str, names) {
      ^

TypeError: Instance of 'JSArray': type 'JSArray' is not a subtype of type 'List<String>'
    at Object.wrapException (~/out.js:313:17)
    at Object.assertSubtype (~/out.js:563:15)
    at Object.main (~/out.js:935:9)
    at ~/out.js:1196:9
    at init.currentScript (~/out.js:1176:7)
    at dartProgram (~/out.js:1191:5)
    at Object.<anonymous> (~/out.js:1198:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

Looks like the actual list passed to main at runtime isn't a properly reified List<String>.

**Comment by rakudrama** [comment]
Fixed via cc3c70159dfc6749fe9920df5fd9a78621e43d97
