### ISSUE TITLE
No definition of type bool when using VSCode

### ISSUE THREAD

**Issue by iampapagray** [dart-lang/sdk#35942]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I just created a new flutter app and i got a notfication of this error.

### Versions

- Flutter SDK 0.9.5-pre.1
- Visual Studio Code 1.31.1
- Dart Code 2.22.3

### Analyzer Info

The analyzer was launched using the arguments:

```text
/home/papagray/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.22.3
```

### Exception

Analysis failed: /home/papagray/FlutterProjects/easy_list_app/lib/main.dart context: exception_20190214_105038_831

```text
Bad state: No definition of type bool
#0      SummaryTypeProvider._getType (package:analyzer/src/summary/summary_sdk.dart:357:7)
#1      SummaryTypeProvider.boolType (package:analyzer/src/summary/summary_sdk.dart:150:19)
#2      new ConstantVerifier (package:analyzer/src/generated/resolver.dart:1457:36)
#3      LibraryAnalyzer._computeConstantErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:159:45)
#4      LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:317:5)
#5      LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:111:11)
#6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#7      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:110:15)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#9      LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:109:36)
#10     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#11     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#12     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#13     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#14     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#15     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1046:39)
<asynchronous suspension>
#17     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#18     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#19     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#20     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#21     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#22     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#28     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#29     main (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#30     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#31     main (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#32     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/home/papagray/FlutterProjects/easy_list_app",
        "explicitFileCount": 2,
        "implicitFileCount": 586,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment]
I imagine this is fixed; have not seen further reports. Please re-open if you see this again.
