### ISSUE TITLE
dart2js crash: type error when disabling type inference

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#35963]
It appears we have an invalid invariant in the SSA, but I have only been able to reproduce this when disabling global type inference.

Here is a small repro:
```dart
import 'dart:async';
main() async {
  await Future.wait([new Future((){})]);
}
```

when compiled with `dart2js --disable-type-inference` produces this error:
```
org-dartlang-sdk:///sdk/lib/async/future.dart@13297+1:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: type 'HTypeConversion' is not a subtype of type 'HLocalValue'
#0      HLocalGet.local (sdk-path/pkg/compiler/lib/src/ssa/nodes.dart:2029:28)
#1      SsaInstructionMerger.isEffectivelyPure (sdk-path/pkg/compiler/lib/src/ssa/codegen_helpers.dart:475:71)
#2      SsaInstructionMerger.analyzeInputs (sdk-path/pkg/compiler/lib/src/ssa/codegen_helpers.dart:442:13)
#3      SsaInstructionMerger.visitInstruction (sdk-path/pkg/compiler/lib/src/ssa/codegen_helpers.dart:493:5)
#4      HBaseVisitor.visitCreate (sdk-path/pkg/compiler/lib/src/ssa/nodes.dart:417:32)
#5      HCreate.accept (sdk-path/pkg/compiler/lib/src/ssa/nodes.dart:1572:39)
#6      SsaInstructionMerger.analyzeInputs (sdk-path/pkg/compiler/lib/src/ssa/codegen_helpers.dart:462:19)
#7      SsaInstructionMerger.visitInstruction (sdk-path/pkg/compiler/lib/src/ssa/codegen_helpers.dart:493:5)
#8      HBaseVisitor.visitLocalAccess (sdk-path/pkg/compiler/lib/src/ssa/nodes.dart:452:42)
#9      HBaseVisitor.visitLocalSet (sdk-path/pkg/compiler/lib/src/ssa/nodes.dart:454:36)
#10     HLocalSet.accept (sdk-path/pkg/compiler/lib/src/ssa/nodes.dart:2037:39)
#11     SsaInstructionMerger.tryMergingExpressions (sdk-path/pkg/compiler/lib/src/ssa/codegen_helpers.dart:670:23)
#12     SsaInstructionMerger.tryMergingExpressions (sdk-path/pkg/compiler/lib/src/ssa/codegen_helpers.dart:695:7)
#13     SsaInstructionMerger.visitBasicBlock (sdk-path/pkg/compiler/lib/src/ssa/codegen_helpers.dart:579:5)
#14     HGraphVisitor.visitDominatorTree (sdk-path/pkg/compiler/lib/src/ssa/nodes.dart:137:9)
#15     SsaInstructionMerger.visitGraph (sdk-path/pkg/compiler/lib/src/ssa/codegen_helpers.dart:429:5)
#16     SsaCodeGenerator.preGenerateMethod (sdk-path/pkg/compiler/lib/src/ssa/codegen.dart:361:10)
#17     SsaCodeGenerator.visitGraph (sdk-path/pkg/compiler/lib/src/ssa/codegen.dart:478:5)
#18     SsaCodeGeneratorTask.generateMethod.<anonymous closure> (sdk-path/pkg/compiler/lib/src/ssa/codegen.dart:128:15)
#19     CompilerTask.measure (sdk-path/pkg/compiler/lib/src/common/tasks.dart:62:51)
#20     SsaCodeGeneratorTask.generateMethod (sdk-path/pkg/compiler/lib/src/ssa/codegen.dart:111:12)
#21     SsaCodeGeneratorTask.generateCode (sdk-path/pkg/compiler/lib/src/ssa/codegen.dart:80:14)
#22     SsaFunctionCompiler.compile (sdk-path/pkg/compiler/lib/src/ssa/ssa.dart:48:38)
#23     JavaScriptBackend.codegen (sdk-path/pkg/compiler/lib/src/js_backend/backend.dart:679:26)
#24     KernelCodegenWorkItem.run (sdk-path/pkg/compiler/lib/src/js_model/js_strategy.dart:174:21)
#25     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (sdk-path/pkg/compiler/lib/src/compiler.dart:457:70)
#26     CompilerTask.measureSubtask (sdk-path/pkg/compiler/lib/src/common/tasks.dart:177:35)
#27     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (sdk-path/pkg/compiler/lib/src/compiler.dart:457:32)
#28     CompilerTask.measureSubtask (sdk-path/pkg/compiler/lib/src/common/tasks.dart:177:35)
#29     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (sdk-path/pkg/compiler/lib/src/compiler.dart:455:28)
#30     CompilerDiagnosticReporter.withCurrentElement (sdk-path/pkg/compiler/lib/src/compiler.dart:782:15)
#31     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (sdk-path/pkg/compiler/lib/src/compiler.dart:453:18)
#32     CodegenEnqueuer._forEach (sdk-path/pkg/compiler/lib/src/js_backend/enqueuer.dart:241:12)
#33     CodegenEnqueuer.forEach (sdk-path/pkg/compiler/lib/src/js_backend/enqueuer.dart:256:5)
#34     Compiler.emptyQueue.<anonymous closure> (sdk-path/pkg/compiler/lib/src/compiler.dart:449:16)
#35     CompilerTask.measureSubtask (sdk-path/pkg/compiler/lib/src/common/tasks.dart:177:35)
#36     Compiler.emptyQueue (sdk-path/pkg/compiler/lib/src/compiler.dart:448:14)
#37     Compiler.processQueue.<anonymous closure> (sdk-path/pkg/compiler/lib/src/compiler.dart:474:7)
#38     CompilerTask.measureSubtask (sdk-path/pkg/compiler/lib/src/common/tasks.dart:177:35)
#39     Compiler.processQueue (sdk-path/pkg/compiler/lib/src/compiler.dart:467:14)
#40     Compiler.generateJavaScriptCode (sdk-path/pkg/compiler/lib/src/compiler.dart:376:5)
#41     Compiler.compileFromKernel.<anonymous closure> (sdk-path/pkg/compiler/lib/src/compiler.dart:420:9)
#42     CompilerTask.measureSubtask (sdk-path/pkg/compiler/lib/src/common/tasks.dart:177:35)
#43     Compiler.compileFromKernel (sdk-path/pkg/compiler/lib/src/compiler.dart:394:14)
#44     Compiler.runInternal (sdk-path/pkg/compiler/lib/src/compiler.dart:281:13)
<asynchronous suspension>
#45     Compiler.run.<anonymous closure>.<anonymous closure> (sdk-path/pkg/compiler/lib/src/compiler.dart:223:38)
#46     new Future.sync (dart:async/future.dart:224:31)
#47     Compiler.run.<anonymous closure> (sdk-path/pkg/compiler/lib/src/compiler.dart:223:20)
#48     CompilerTask.measureSubtask (sdk-path/pkg/compiler/lib/src/common/tasks.dart:177:35)
#49     Compiler.run (sdk-path/pkg/compiler/lib/src/compiler.dart:220:41)
#50     CompilerImpl.run.<anonymous closure>.<anonymous closure> (sdk-path/pkg/compiler/lib/src/apiimpl.dart:88:22)
#51     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#52     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#53     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#54     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#55     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#56     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#59     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#60     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)

Finished with a exit code: 253
```

**Comment by hamidrezabstn** [comment]
same here +1

**Comment by sigmundch** [comment]
Note: for anyone running into this issue, if you are using `-O0`, please use `-O1` or above. We believe this issue only happens when disabling optimizations that we normally assume to be on by default.

If your goal is to turn off minification, you can do so via `-O1` or via `--no-minify`.
