### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by mouhannad86** [dart-lang/sdk#35973]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

version: 1.0.0+1
MacOSX

----
```

Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't. Error message was 'NoSuchMethodError: The method 'getReference' was called on null.
Receiver: null
Tried calling: getReference()'. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.15.7/lib/intl_browser.dart:13:8: Error: Not found: 'dart:html'
import "dart:html";
       ^
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:95:25: Error: Type 'HttpRequest' not found.
  void _openHttpRequest(HttpRequest request, String method, String url,
                        ^^^^^^^^^^^
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:30:25: Error: 'HttpRequest' isn't a type.
  final _xhrs = new Set<HttpRequest>();
                        ^^^^^^^^^^^
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.15.7/lib/intl_browser.dart:25:48: Error: Getter not found: 'window'.
  Intl.systemLocale = Intl.canonicalizedLocale(window.navigator.language);
                                               ^^^^^^
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:44:19: Error: Method not found: 'HttpRequest'.
    var xhr = new HttpRequest();
                  ^^^^^^^^^^^
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:55:45: Error: Method not found: 'Blob'.
      var blob = xhr.response == null ? new Blob([]) : xhr.response;
                                            ^^^^
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:56:24: Error: Method not found: 'FileReader'.
      var reader = new FileReader();
                       ^^^^^^^^^^
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:55:49: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
      var blob = xhr.response == null ? new Blob([]) : xhr.response;
                                                ^
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:95:25: Error: 'HttpRequest' isn't a type.
  void _openHttpRequest(HttpRequest request, String method, String url,
                        ^^^^^^^^^^^
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:97:13: Error: The method 'open' isn't defined for the class 'invalid-type'.
Try correcting the name to the name of an existing method, or defining a method named 'open'.
    request.open(method, url, async: asynch, user: user, password: password);
            ^^^^
file:///Users/Mouhannad/Desktop/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:105:11: Error: The method 'abort' isn't defined for the class 'invalid-type'.
Try correcting the name to the name of an existing method, or defining a method named 'abort'.
      xhr.abort();
          ^^^^^
Unhandled exception:
Unsupported operation: Cannot extract a file path from a org-dartlang-untranslatable-uri URI
#0      _Uri.toFilePath (dart:core/uri.dart:2617:7)
#1      _writeDepfile (package:vm/frontend_server.dart:682:32)
<asynchronous suspension>
#2      FrontendCompiler.compile (package:vm/frontend_server.dart:363:15)
<asynchronous suspension>
#3      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:31:22)
<asynchronous suspension>
#4      starter (package:frontend_server/server.dart:133:27)
<asynchronous suspension>
#5      main (file:///b/build/slave/Mac_Engine/build/src/flutter/frontend_server/bin/starter.dart:8:30)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Compiler failed on /Users/Mouhannad/Desktop/earch_quake/lib/main.dart
Error launching application on iPhone XR.

----
```

**Comment by mit-mit** [comment]
@mouhannad86 can you share the output of `flutter --version`?

**Comment by zoechi** [comment]
Could be that the Flutter installation is corrupted. 
Here are some instructions how to fix https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by kevmoo** [comment]
@mouhannad86 are you still having the issue?

**Comment by a-siva** [comment]
Not clear if this is a VM issue, 'dart:html' is not a library that is included in the VM.
