### ISSUE TITLE
Dart Analyzer Error Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#35978]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 191.5532.37`
- `2.1.1-dev.3.2`
- `WS-191.5532.37, JRE 1.8.0_202-release-1483-b24x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3, screens 2560x1440, 1200x1920`

## Exception
```
Dart analysis server, SDK version 2.1.1-dev.3.2, server version 1.22.1, error: type 'CompilationUnitImpl' is not a subtype of type 'ConstructorDeclaration'
#0      new List.from (dart:core/runtime/libarray_patch.dart:52:7)
#1      new _BuiltList.copyAndCheckTypes (file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/built_collection-4.1.0/lib/src/list/built_list.dart:275:21)
#2      new BuiltList.from (file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/built_collection-4.1.0/lib/src/list/built_list.dart:45:18)
#3      new BuiltList (file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/built_collection-4.1.0/lib/src/list/built_list.dart:30:11)
#4      ValueSourceClass.valueClassConstructors (package:built_value_generator/src/value_source_class.dart:198:11)
#5      _$ValueSourceClass.valueClassConstructors (file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/built_value_generator-6.3.0/lib/src/value_source_class.g.dart:119:42)
#6      ValueSourceClass._checkValueClass (package:built_value_generator/src/value_source_class.dart:406:11)
#7      ValueSourceClass.computeErrors (package:built_value_generator/src/value_source_class.dart:282:7)
#8      Checker.check (package:built_value_generator/src/plugin/checker.dart:23:36)
#9      BuiltValueAnalyzerPlugin._processResult (package:built_value_generator/src/plugin/plugin.dart:69:37)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:375:20)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#19     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#20     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#24     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/k3/rpf30xp576gd3b7wdpvvyg2r0000gn/T/report.txt.

**Comment by dgrove** [comment]
this is actually from the built value plguin (rather than the analyzer) -  moved to https://github.com/google/built_value.dart/issues/590
