### ISSUE TITLE
Unable to build 2.1.1 from source: can't assign String to List<CodeSpan>

### ISSUE THREAD

**Issue by ulidtko** [dart-lang/sdk#36019]
Hi!

I'm building Dart SDK 2.1.1 from source using `depot_tools` in a Linux container. The complete build log follows:

```
{docker|rpmbuild} [rpm]⚓ rpmbuild -ba SPECS/dart-sdk.spec 
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.ZcU9Dq
+ umask 022
+ cd /home/builder/rpm/BUILD
+ [[ -d depot_tools ]]
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/builder/rpm/BUILD/depot_tools
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/builder/rpm/BUILD/depot_tools
+ mkdir -p dart-2.1.1
+ cd dart-2.1.1
+ [[ -d sdk ]]
+ fetch dart
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://dart.googlesource.com/sdk.git",
    "managed": False,
    "name": "sdk",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://dart.googlesource.com/sdk.git /home/builder/rpm/BUILD/dart-2.1.1/_gclient_sdk_8K1wh1' in '/home/builder/rpm/BUILD/dart-2.1.1'
Cloning into '/home/builder/rpm/BUILD/dart-2.1.1/_gclient_sdk_8K1wh1'...
remote: Sending approximately 693.81 MiB ...
remote: Counting objects: 921, done
remote: Finding sources: 100% (43/43)
Receiving objects:  74% (607942/817958), 444.30 MiB | 7.50 MiB/s    
[0:01:00] Still working on:
[0:01:00]   sdk
Receiving objects:  76% (621649/817958), 512.79 MiB | 9.02 MiB/s   
[0:01:10] Still working on:
[0:01:10]   sdk
Receiving objects:  78% (641399/817958), 588.32 MiB | 6.14 MiB/s   
[0:01:20] Still working on:
[0:01:20]   sdk
Receiving objects:  95% (780330/817958), 681.97 MiB | 9.51 MiB/s    
[0:01:30] Still working on:
[0:01:30]   sdk
remote: Total 817958 (delta 656360), reused 817955 (delta 656360)
Receiving objects: 100% (817958/817958), 693.26 MiB | 8.62 MiB/s, done.
Resolving deltas:  79% (518555/656360)   
[0:01:40] Still working on:
[0:01:40]   sdk
Resolving deltas:  87% (574121/656360)   
[0:01:50] Still working on:
[0:01:50]   sdk
Resolving deltas: 100% (656360/656360), done.

[0:02:00] Still working on:
[0:02:00]   sdk
Syncing projects:   0% ( 0/ 2) 
[0:02:03] Still working on:
[0:02:03]   sdk
Syncing projects: 100% (84/84), done.                                                  

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --recursive --auto_platform --extract --directory sdk/third_party/firefox_jsshell' in '/home/builder/rpm/BUILD/dart-2.1.1'
0> Downloading sdk/third_party/firefox_jsshell/linux/jsshell.tar.gz...
0> Extracting 5 entries from sdk/third_party/firefox_jsshell/linux/jsshell.tar.gz to sdk/third_party/firefox_jsshell/linux/jsshell
Downloading 1 files took 7.836850 second(s)
Running hooks:  22% ( 2/ 9) 7zip
________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --platform=win32 --extract -s sdk/third_party/7zip.tar.gz.sha1' in '/home/builder/rpm/BUILD/dart-2.1.1'
The current platform doesn't match "win32", skipping.
Running hooks:  33% ( 3/ 9) sysroot_i386
________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --arch i386' in '/home/builder/rpm/BUILD/dart-2.1.1'
Installing Debian Jessie i386 root image: /home/builder/rpm/BUILD/dart-2.1.1/sdk/build/linux/debian_jessie_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/7031a828c5dcedc937bbf375c42daab08ca6162f/debian_jessie_i386_sysroot.tgz
Running hooks:  44% ( 4/ 9) sysroot_amd64
________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --arch amd64' in '/home/builder/rpm/BUILD/dart-2.1.1'
Installing Debian Jessie amd64 root image: /home/builder/rpm/BUILD/dart-2.1.1/sdk/build/linux/debian_jessie_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/7031a828c5dcedc937bbf375c42daab08ca6162f/debian_jessie_amd64_sysroot.tgz
Running hooks:  55% ( 5/ 9) sysroot_amd64
________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --arch arm' in '/home/builder/rpm/BUILD/dart-2.1.1'
Installing Debian Jessie arm root image: /home/builder/rpm/BUILD/dart-2.1.1/sdk/build/linux/debian_jessie_arm-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/7031a828c5dcedc937bbf375c42daab08ca6162f/debian_jessie_arm_sysroot.tgz
Running hooks:  66% ( 6/ 9) sysroot_amd64
________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --arch arm64' in '/home/builder/rpm/BUILD/dart-2.1.1'
Installing Debian Jessie arm64 root image: /home/builder/rpm/BUILD/dart-2.1.1/sdk/build/linux/debian_jessie_arm64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/7031a828c5dcedc937bbf375c42daab08ca6162f/debian_jessie_arm64_sysroot.tgz
Running hooks:  77% ( 7/ 9) download_android_tools
________ running '/usr/bin/python sdk/tools/android/download_android_tools.py' in '/home/builder/rpm/BUILD/dart-2.1.1'
Copying gs://mojo/android/tool/0d320c50b0ed188c7e1182388e2beb623a1d307d.tar.gz...
\ [1 files][412.4 MiB/412.4 MiB]   10.4 MiB/s                                   
Operation completed over 1 objects/412.4 MiB.                                    
Copying gs://mojo/android/tool/e626c47cb82a7439b0eda03ac6e0e9e1e41c6093.tar.gz...
- [1 files][668.3 MiB/668.3 MiB]    7.6 MiB/s                                   
Operation completed over 1 objects/668.3 MiB.                                    
Running ['python', '/home/builder/rpm/BUILD/depot_tools/gsutil.py', 'cp', 'gs://mojo/android/tool/0d320c50b0ed188c7e1182388e2beb623a1d307d.tar.gz', '/home/builder/rpm/BUILD/dart-2.1.1/sdk/third_party/android_tools/sdk.tar.gz']
Extracting Android tools (sdk)
Running ['python', '/home/builder/rpm/BUILD/depot_tools/gsutil.py', 'cp', 'gs://mojo/android/tool/e626c47cb82a7439b0eda03ac6e0e9e1e41c6093.tar.gz', '/home/builder/rpm/BUILD/dart-2.1.1/sdk/third_party/android_tools/ndk.tar.gz']
Extracting Android tools (ndk)
Hook '/usr/bin/python sdk/tools/android/download_android_tools.py' took 193.02 secs
Running hooks: 100% (9/9), done.                  
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
+ cd sdk
+ git fetch --tags
+ git checkout 2.1.1
Previous HEAD position was e7d263b... [fasta] Transform set literals in annotations.
HEAD is now at 265af02... Version 2.1.1
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.d0O0Lw
+ umask 022
+ cd /home/builder/rpm/BUILD
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/builder/rpm/BUILD/depot_tools
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/builder/rpm/BUILD/depot_tools
+ cd dart-2.1.1/sdk
+ ./tools/build.py --mode release --arch x64 create_sdk
Running python /home/builder/rpm/BUILD/dart-2.1.1/sdk/tools/generate_buildfiles.py
ninja -C out/ReleaseX64 create_sdk
ninja: Entering directory `out/ReleaseX64'
[1472/1525] ACTION //utils/kernel-service:kernel-service_snapshot(//build/toolchain/linux:clang_x64)
FAILED: gen/kernel-service.dart.snapshot 
python ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=/home/builder/rpm/BUILD/dart-2.1.1/sdk/.packages --snapshot=gen/kernel-service.dart.snapshot --snapshot-depfile=/home/builder/rpm/BUILD/dart-2.1.1/sdk/out/ReleaseX64/gen/kernel-service.dart.snapshot.d --snapshot-kind=app-jit /home/builder/rpm/BUILD/dart-2.1.1/sdk/out/ReleaseX64/gen/kernel_service.dill --train file:////home/builder/rpm/BUILD/dart-2.1.1/sdk/pkg/compiler/lib/src/dart2js.dart
Command failed: ./dart --deterministic --packages=/home/builder/rpm/BUILD/dart-2.1.1/sdk/.packages --snapshot=gen/kernel-service.dart.snapshot --snapshot-depfile=/home/builder/rpm/BUILD/dart-2.1.1/sdk/out/ReleaseX64/gen/kernel-service.dart.snapshot.d --snapshot-kind=app-jit /home/builder/rpm/BUILD/dart-2.1.1/sdk/out/ReleaseX64/gen/kernel_service.dill --train file:////home/builder/rpm/BUILD/dart-2.1.1/sdk/pkg/compiler/lib/src/dart2js.dart
output: Unhandled exception:
file:////home/builder/rpm/BUILD/dart-2.1.1/sdk/pkg/compiler/lib/src/dump_info.dart:55:29: Error: The argument type 'String' can't be assigned to the parameter type 'List<CodeSpan>'.
 - 'List' is from 'dart:core'.
 - 'CodeSpan' is from 'package:dart2js_info/info.dart' ('file:///home/builder/rpm/BUILD/dart-2.1.1/sdk/third_party/pkg/dart2js_info/lib/info.dart').
Try changing the type of the parameter, or casting the argument to 'List<CodeSpan>'.
          size: size, code: code, outputUnit: _unitInfoForConstant(constant));
                            ^
file:////home/builder/rpm/BUILD/dart-2.1.1/sdk/pkg/compiler/lib/src/dump_info.dart:136:15: Error: The argument type 'String' can't be assigned to the parameter type 'List<CodeSpan>'.
 - 'List' is from 'dart:core'.
 - 'CodeSpan' is from 'package:dart2js_info/info.dart' ('file:///home/builder/rpm/BUILD/dart-2.1.1/sdk/third_party/pkg/dart2js_info/lib/info.dart').
Try changing the type of the parameter, or casting the argument to 'List<CodeSpan>'.
        code: code,
              ^
file:////home/builder/rpm/BUILD/dart-2.1.1/sdk/pkg/compiler/lib/src/dump_info.dart:296:15: Error: The argument type 'String' can't be assigned to the parameter type 'List<CodeSpan>'.
 - 'List' is from 'dart:core'.
 - 'CodeSpan' is from 'package:dart2js_info/info.dart' ('file:///home/builder/rpm/BUILD/dart-2.1.1/sdk/third_party/pkg/dart2js_info/lib/info.dart').
Try changing the type of the parameter, or casting the argument to 'List<CodeSpan>'.
        code: code,
              ^
file:////home/builder/rpm/BUILD/dart-2.1.1/sdk/pkg/compiler/lib/src/dump_info.dart:343:47: Error: Too few positional arguments: 3 required, 2 given.
      OutputUnitInfo info = new OutputUnitInfo(
                                              ^
file:///home/builder/rpm/BUILD/dart-2.1.1/sdk/third_party/pkg/dart2js_info/lib/info.dart:211:3: Context: Found this candidate, but the arguments don't match.
  OutputUnitInfo(this.filename, String name, int size)
  ^
file:////home/builder/rpm/BUILD/dart-2.1.1/sdk/pkg/compiler/lib/src/dump_info.dart:554:17: Error: Method not found: 'BasicInfo.resetIds'.
      BasicInfo.resetIds();
                ^^^^^^^^
file:////home/builder/rpm/BUILD/dart-2.1.1/sdk/pkg/compiler/lib/src/dump_info.dart:634:18: Error: Method not found: 'AllInfoJsonCodec'.
    sink.add(new AllInfoJsonCodec().encode(result));
                 ^^^^^^^^^^^^^^^^
#0      train.<anonymous closure> (file:///home/builder/rpm/BUILD/dart-2.1.1/sdk/pkg/vm/bin/kernel_service.dart:653:7)
#1      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

ninja: build stopped: subcommand failed.
BUILD FAILED
error: Bad exit status from /var/tmp/rpm-tmp.d0O0Lw (%build)

```

This is a new container, fresh checkout, latest `depot_tools` (rev. `18f119bb3a0335fe9fdf8b94e5eebcea527784d9`).

Please advise. The exact same RPMspec (written by me) has built `2.1.0-dev.7.1` no problem.

**Comment by ulidtko** [comment]
Solved by using

    gclient fetch --no-history --with_tags dart
    (cd sdk; gclient sync --no-history --revision %{upstream_version}; )

Instead of

    fetch dart
    (cd sdk; git fetch --tags; git checkout %{upstream_version} )

Looks like `depot_tools` entertain some funny business around git submodules — which breaks the naïve `git checkout`.

**Comment by mraleph** [comment]
@ulidtko if you checkout a specific version of SDK via `git checkout` then you need to rerun `gclient sync` to fetch specific dependencies because `DEPS` file is managed by `git` while the dependencies are managed by `gclient`
