### ISSUE TITLE
error: Handle check failed: saw Instance of 'A' expected Closure

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#36084]
```dart
class A {
  void call(int a, [int b]) {}
}

class B {
  dynamic foo;
}

main() {
  B b = new B();
  b.foo = new A();
  b.foo(1, 2, 3);
}
```

In interpreter this doesn't work correctly:
```
$ out/ReleaseX64/dart --enable-interpreter foo.dart
../../runtime/vm/object.h: 8769: error: Handle check failed: saw Instance of 'A' expected Closure
thread=171662, isolate=foo.dart:main()(0x55c8c9be4900)
  [0x000055c8c7f03dac] dart::Profiler::DumpStackTrace(void*)
  [0x000055c8c7f03dac] dart::Profiler::DumpStackTrace(void*)
  [0x000055c8c8136482] dart::Assert::Fail(char const*, ...)
  [0x000055c8c7f5a281] dart::DRT_InvokeClosureNoSuchMethod(dart::NativeArguments)
  [0x000055c8c7e28771] Unknown symbol
  [0x000055c8c7e2a9b7] dart::Interpreter::Call(dart::RawFunction*, dart::RawArray*, long, dart::RawObject* const*, dart::Thread*)
  [0x000055c8c7f5d50c] dart::RuntimeEntry::InterpretCall(dart::RawFunction*, dart::RawArray*, long, dart::RawObject**, dart::Thread*)
  [0x00007f91829010b4] Unknown symbol
  [0x00007f917e66a05d] Unknown symbol
  [0x00007f917e669e79] Unknown symbol
  [0x00007f917e669235] Unknown symbol
  [0x00007f917e64989c] Unknown symbol
  [0x00007f917e668f13] Unknown symbol
  [0x00007f918290146c] Unknown symbol
  [0x000055c8c7dfd8b7] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  [0x000055c8c7e00c86] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  [0x000055c8c7e313ae] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x000055c8c7e62b5e] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x000055c8c7e631a6] dart::MessageHandler::TaskCallback()
  [0x000055c8c7f91517] dart::ThreadPool::Worker::Loop()
  [0x000055c8c7f913a4] dart::ThreadPool::Worker::Main(unsigned long)
  [0x000055c8c7f00439] Unknown symbol
-- End of DumpStackTrace
Aborted
```

Correct behavior:
```
$ out/ReleaseX64/dart foo.dart
Unhandled exception:
NoSuchMethodError: Class 'A' has no instance method 'call' with matching arguments.
Receiver: Instance of 'A'
Tried calling: call(1, 2, 3)
Found: call(int, [int]) => void
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      main (file:///usr/local/google/home/alexmarkov/work/dart/sdk/foo.dart:13:5)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:300:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

This variant of test doesn't work correctly as well:
```dart
class A {
  void call(int a, [int b]) {}
  void noSuchMethod(Invocation invocation) {
    print('noSuchMethod: $invocation');
  }
}

class B {
  dynamic foo;
}

main() {
  B b = new B();
  b.foo = new A();
  b.foo(1, 2, 3);
}
```

/cc @crelier

**Comment by alexmarkov** [comment]
Another interesting example:

```dart
class A {
  void call(int a) {}
  void noSuchMethod(Invocation invocation) {
    print('noSuchMethod: $invocation');
  }
}

class B {
  dynamic foo;
}

main() {
  B b = new B();
  b.foo = new A();
  b.foo();
}
```

```
$ out/ReleaseX64/dart --enable-interpreter foo.dart
Unhandled exception:
type 'A' is not a subtype of type 'int' of 'a'
#0      A.call (file:///usr/local/google/home/alexmarkov/work/dart/sdk/foo.dart)
#1      main (file:///usr/local/google/home/alexmarkov/work/dart/sdk/foo.dart)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:300:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

Correct behavior:
```
$ out/ReleaseX64/dart foo.dart
noSuchMethod: Instance of '_InvocationMirror'
$ out/ReleaseX64/dart --use-bytecode-compiler foo.dart
noSuchMethod: Instance of '_InvocationMirror'
```

**Comment by crelier** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/97142
