### ISSUE TITLE
Using generic function inside of generic class can produce unexpected type typing.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#36096]
Dart SDK Version: 2.2.0-dev 2.1, 2.1.1-dev.3.2
OS: Windows 10 64 bit

The following code sample declares a generic class with generic function:
``` dart
class Test<X extends num> {
  void printX() {
    print("X: " + X.toString());
  }
  void printT<T extends X>() {
    print("T: " + T.toString());
  }
}

main() {
  Test<int> t1 = new Test<int>();
  t1.printX();
  t1.printT();

  Test<num> t2 = t1;
  t2.printX();
  t2.printT();
}
```
I expect that `T` should extend `X` (i.e. it should be `int` for `t1` and `t2`), however this is not so here - `t2.printX()` prints `int` and `t2.printT()` throws an exception here:
```
X: int
T: int
X: int
Unhandled exception:
type 'num' is not a subtype of type 'int' of 'T'
#0      Test.printT (file:///D:/DART/sdk/tests/co19/src/Language/Generics/test.dart)
#1      main (file:///D:/DART/sdk/tests/co19/src/Language/Generics/test.dart:17:6)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
As far as I understand, this issue should be fixed when inference specification is ready.

**Comment by eernstg** [comment]
@iarkh wrote:
> this issue should be fixed when inference specification is ready

Agreed, but let me mention the expectations: The only outcomes which are affected by inference are the printouts during `t1.printT()` and during `t2.printT()`.

The actual type argument of `t1` and `t2` at `Test` cannot be denoted (in the given scope, there is no syntax derived from `<type>` whose value is that type argument), and hence there is no way type inference could provide such a type argument to the invocations of `printT`.

So it's not plausible that inference will be specified to provide any other value than the statically known value of the type argument of `t1` respectively `t2`, that is `int` for the first invocation of `printT` and `num` for the second. I'd say that the only plausible alternative would be to make it an error to invoke `printT` outside class `Test` at all, but that is of course a breaking change, and hence not so likely.

This actually means that the behavior that you have observed (that would be when running the test program using `dart`, maybe with some options?) is exactly what a specification of type inference is likely to require, which means that the test ought to be adjusted to have `//# 00: compile-time error` in line 17.

With that, the example program would simply be a test that targets type inference, and it would have exactly the same status as any other test targeting type inference ("this is how we think it should work, but we'll need to double-check when the type inference specification has been landed").

Isn't there a suitable place to put such tests, and a suitable status to give them? Presumably, we'll have a lot of co19 tests targeting type inference, and if this is the first one then it could just be put into a new directory (or directory subtree) on that topic.

**Comment by iarkh** [comment]
Initially I was going to put such tests into Language/Generics folder, with the following assertion:

> A generic class is a mapping that accepts a list of actual type argu-
> ments and maps them to a class. Consider a generic class declaration G named C
> with formal type parameter declarations X1 extends B1, . . . , Xm extends Bm,
> and a parameterized type T of the form C<T1, . . . , Tl>.
> It is a compile-time error if m != l. It is a compile-time error if T is not
> well-bounded (14.2).
> Otherwise, said parameterized type C<T1, . . . , Tm> denotes an application
> of the generic class declared by G to the type arguments T1, . . . , Tm. This yields
> a class C0 whose members are equivalent to those of a class declaration which
> is obtained from the declaration G by replacing each occurrence of Xj by Tj.

Regarding the suitable status - I was going just to mark the tests with corresponding $Issue tag - is it enough or not?

**Comment by eernstg** [comment]
I think there is a need for a separate `Language/Inference` or `Language/TypeInference` folder, because some inferred types are not type arguments (e.g., they can be the type of a variable or parameter). Also, some inferred type arguments are not class type arguments but function invocation type arguments (e.g., `myList.map((x) => 42)`), and that's also true for the particular example that we have discussed. So we'd need text about inference, and in particular about inference in the setting where the bound is not statically known.

We could then consider everything in the type inference folder (or folder hierarchy, if needed) to have status "please double-check this when we have landed a specification of inference", and that double-check operation will then (hopefully) only cause a small number of adjustments.
