### ISSUE TITLE
Internal problem: Exported element 'patch' not found in 'dart:_internal'

### ISSUE THREAD

**Issue by kangwang1988** [dart-lang/sdk#36121]
* Dart SDK Version (`dart --version`)
dart --version
Dart VM version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "macos_x64"

I create a hello_flutter project and add a custom_aop_impl package in it.

I want to create two dill files(this error occurs in aot mode only), app.dill works fine:
```
/Users/kylewong/Codes/Flutter/flutter_aop/flutter/bin/cache/dart-sdk/bin/dart /Users/kylewong/Codes/Flutter/flutter_aop/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/kylewong/Codes/Flutter/flutter_aop/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --strong --target=flutter --aot --tfa -Ddart.vm.product=true --packages .packages --output-dill build/aot/app.dill --depfile build/aot/kernel_compile.d package:hello_flutter/main.dart
```

However, when I use `--incremental --initialize-from-dill` to create another dill file without main function, it fails.
```
/Users/kylewong/Codes/Flutter/flutter_aop/flutter/bin/cache/dart-sdk/bin/dart /Users/kylewong/Codes/Flutter/flutter_aop/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/kylewong/Codes/Flutter/flutter_aop/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --strong --target=flutter --aot --tfa -Ddart.vm.product=true --packages .packages --output-dill build/aot/app_aop.dill --depfile build/aot/kernel_compile_aop.d package:custom_aop_impl/custom_aop_impl.dart --incremental --initialize-from-dill=/Users/kylewong/Codes/Flutter/flutter_aop/Projects/hello_flutter/build/aot/app.dill
```
The console gives message below:
```dart
result 0a933bd3-4d38-49b9-91f0-cc8d18a2f267
Unhandled exception:
org-dartlang-sdk:///third_party/dart/sdk/lib/internal/internal.dart:1: Internal problem: Exported element 'patch' not found in 'dart:_internal'.
#0      internalProblem (package:front_end/src/fasta/problems.dart:45:3)
#1      DillLibraryBuilder.finalizeExports (package:front_end/src/fasta/dill/dill_library_builder.dart:233:9)
#2      DillLoader.finalizeExports.<anonymous closure> (package:front_end/src/fasta/dill/dill_loader.dart:99:15)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#4      DillLoader.finalizeExports (package:front_end/src/fasta/dill/dill_loader.dart:97:14)
#5      DillTarget.buildOutlines (package:front_end/src/fasta/dill/dill_target.dart:55:14)
<asynchronous suspension>
#6      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:177:30)
<asynchronous suspension>
#7      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#8      new Future.sync (dart:async/future.dart:224:31)
#9      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#15     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:116:20)
<asynchronous suspension>
#16     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:50:44)
<asynchronous suspension>
#17     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:339:67)
#18     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#19     _rootRun (dart:async/zone.dart:1120:38)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#27     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#28     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

@mraleph

**Comment by kangwang1988** [comment]
I'm closing this issue as I've build the aop.dill using another way.
