### ISSUE TITLE
NPE in dartanalyzer 2.2.0

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#36124]
To reproduce, run Dart SDK `2.2`'s `dartanalyzer` on `ml_linalg` [`6.0.0`](https://storage.googleapis.com/pub-packages/packages/ml_linalg-6.0.0.tar.gz).
````
NoSuchMethodError: The getter 'element' was called on null. Receiver: null Tried calling: element
#0 Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1 StaticTypeAnalyzer._findIteratedType._find (package:analyzer/src/generated/static_type_analyzer.dart:1663:35)
#2 StaticTypeAnalyzer._findIteratedType._find (package:analyzer/src/generated/static_type_analyzer.dart:1681:21)
#3 StaticTypeAnalyzer._findIteratedType (package:analyzer/src/generated/static_type_analyzer.dart:1690:12)
#4 StaticTypeAnalyzer._inferForEachLoopVariableType (package:analyzer/src/generated/static_type_analyzer.dart:1834:33)
#5 StaticTypeAnalyzer.visitDeclaredIdentifier (package:analyzer/src/generated/static_type_analyzer.dart:622:5)
#6 DeclaredIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:3337:49)
#7 ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4837:10)
#8 UnifyingAstVisitor.visitDeclaredIdentifier (package:analyzer/dart/ast/visitor.dart:3305:57)
#9 ScopedVisitor.visitDeclaredIdentifier (package:analyzer/src/generated/resolver.dart:5719:11)
#10 DeclaredIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:3337:49)
#11 ResolverVisitor.visitForEachStatementInScope (package:analyzer/src/generated/resolver.dart:4335:19)
#12 ScopedVisitor.visitForEachStatement (package:analyzer/src/generated/resolver.dart:5772:7)
#13 ForEachStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4836:49)
#14 NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9046:20)
#15 BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1254:17)
#16 ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4835:10)
````

**Comment by bwilkerson** [comment]
I believe that the fix for this is straightforward. We're assuming that `superclass` will never be `null` and that's not true. (Probably because of mixins, but maybe it's never been true because of `Object`.)

In either case, it looks like `StaticTypeAnalyzer._findIteratedType` is trying to do the same thing that `InterfaceTypeImpl.asInstanceOf` was recently added to handle (modulo resolving type parameters to their bounds). If that's true, it would be nice to convert `_findIteratedType` to use `asInstanceOf`.

**Comment by srawlins** [comment]
StaticTypeAnalyzer has been refactored a lot recently; there is no more _findIteratedType.

Additionally, I cannot recreate this  crash when analyzing `lib/` or `test/` in ml_linalg 6.0.0 with Dart 2.5.0-dev.2.1. This has been fixed.
