### ISSUE TITLE
Stream.join gives an incomplete stacktrace compared to toList when a Stream has an error

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#36135]
when calling `join`, the top of the stack trace is at the `join` call site.

when calling `toList`, it's at the point in `_throwingStream` where thrown – as expected

```dart
import 'dart:async';

main() async {
  print('just join');
  try {
    var values = await _throwingStream().join();
    print(values);
  } catch (e, stack) {
    print(stack);
/*
#0      main (file:///Users/kevmoo/source/github/_testHarness/bin/main.dart:6:18)
<asynchronous suspension>
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
 */
  }

  print('toList then join');
  try {
    var values = await _throwingStream().toList();
    print(values);
  } catch (e, stack) {
    print(stack);
/*
#0      _throwingStream (file:///Users/kevmoo/source/github/_testHarness/bin/main.dart:39:3)
<asynchronous suspension>
#1      main (file:///Users/kevmoo/source/github/_testHarness/bin/main.dart:20:24)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
 */
  }
}

Stream<int> _throwingStream() async* {
  for (var i = 0; i < 10; i++) {
    yield i;
  }
  throw 'boo!';
}
```

**Comment by kevmoo** [comment]
CC @lrhn

**Comment by kevmoo** [comment]
CL https://dart-review.googlesource.com/c/sdk/+/95740
