### ISSUE TITLE
DDC error: NoSuchMethodError: The getter 'staticType' was called on null.

### ISSUE THREAD

**Issue by smaifullerton-wk** [dart-lang/sdk#36144]
Confirmed with Dart 2.2.0 on MacOS, and Dart 2.2.0 and 2.1.0 in Docker.

When using DDC to run tests in one of our private repos, I hit the following during the build...

```
[SEVERE] build_web_compilers|ddc on lib/w_flux_browser.dartdevc.module:
Error compiling dartdevc module:react_tracing|lib/w_flux_browser.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
dartdevc arguments: --dart-sdk=/usr/lib/dart --dart-sdk-summary=/usr/lib/dart/lib/_internal/ddc_sdk.sum --modules=amd -o packages/react_tracing/w_flux_browser.ddc.js --module-root=. --library-root=/lib --summary-extension=dartdevc.linked.sum --no-summarize --options=packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s packages/logging/logging.dartdevc.linked.sum -s packages/meta/meta.dartdevc.linked.sum -s packages/w_common/src/common/disposable.dartdevc.linked.sum -s packages/w_common/disposable.dartdevc.linked.sum -s packages/react/react.dartdevc.linked.sum -s packages/w_flux/src/action.dartdevc.linked.sum -s packages/w_flux/w_flux_server.dartdevc.linked.sum -s packages/path/path.dartdevc.linked.sum -s packages/stack_trace/stack_trace.dartdevc.linked.sum -s packages/user_analytics/user_analytics.dartdevc.linked.sum -s packages/intl/date_symbols.dartdevc.linked.sum -s packages/intl/number_symbols.dartdevc.linked.sum -s packages/intl/number_symbols_data.dartdevc.linked.sum -s packages/intl/src/plural_rules.dartdevc.linked.sum -s packages/intl/intl.dartdevc.linked.sum -s packages/collection/src/utils.dartdevc.linked.sum -s packages/collection/src/algorithms.dartdevc.linked.sum -s packages/collection/src/canonicalized_map.dartdevc.linked.sum -s packages/collection/src/comparators.dartdevc.linked.sum -s packages/collection/src/iterable_zip.dartdevc.linked.sum -s packages/collection/src/priority_queue.dartdevc.linked.sum -s packages/collection/collection.dartdevc.linked.sum -s packages/typed_data/typed_buffers.dartdevc.linked.sum -s packages/typed_data/typed_data.dartdevc.linked.sum -s packages/charcode/ascii.dartdevc.linked.sum -s packages/convert/convert.dartdevc.linked.sum -s packages/crypto/crypto.dartdevc.linked.sum -s packages/uuid/aes.dartdevc.linked.sum -s packages/uuid/uuid_util.dartdevc.linked.sum -s packages/uuid/uuid.dartdevc.linked.sum -s packages/dart2_constant/convert.dartdevc.linked.sum -s packages/fixnum/fixnum.dartdevc.linked.sum -s packages/dart2_constant/typed_data.dartdevc.linked.sum -s packages/async/async.dartdevc.linked.sum -s packages/charcode/html_entity.dartdevc.linked.sum -s packages/charcode/charcode.dartdevc.linked.sum -s packages/term_glyph/term_glyph.dartdevc.linked.sum -s packages/source_span/source_span.dartdevc.linked.sum -s packages/string_scanner/string_scanner.dartdevc.linked.sum -s packages/http_parser/http_parser.dartdevc.linked.sum -s packages/http/src/base_client.dartdevc.linked.sum -s packages/http/http.dartdevc.linked.sum -s packages/thrift/thrift.dartdevc.linked.sum -s packages/mime/mime.dartdevc.linked.sum -s packages/w_transport/src/constants.dartdevc.linked.sum -s packages/fluri/fluri.dartdevc.linked.sum -s packages/w_transport/w_transport.dartdevc.linked.sum -s packages/frugal/frugal.dartdevc.linked.sum -s packages/opentracing/src/binary_carrier.dartdevc.linked.sum -s packages/opentracing/opentracing.dartdevc.linked.sum -s packages/protobuf/protobuf.dartdevc.linked.sum -s packages/basictracer_dart/basictracer_dart.dartdevc.linked.sum -s packages/app_intelligence/src/app_data_types/common/meta_data_container.dartdevc.linked.sum -s packages/app_intelligence/app_intelligence_common.dartdevc.linked.sum -s packages/react_tracing/src/w_flux/constants.dartdevc.linked.sum -s packages/w_flux/w_flux.dartdevc.linked.sum -s packages/js/js.dartdevc.linked.sum -s packages/react/react_client/js_interop_helpers.dartdevc.linked.sum -s packages/react/react_client/react_interop.dartdevc.linked.sum -s packages/react/react_dom.dartdevc.linked.sum -s packages/react/react_dom_server.dartdevc.linked.sum -s packages/react/src/ddc_emulated_function_name_bug.dartdevc.linked.sum -s packages/react/react_client.dartdevc.linked.sum -s packages/quiver/core.dartdevc.linked.sum -s packages/over_react/src/component/dummy_component.dartdevc.linked.sum -s packages/pub_semver/pub_semver.dartdevc.linked.sum -s packages/platform_detect/src/browser.dartdevc.linked.sum -s packages/platform_detect/platform_detect.dartdevc.linked.sum -s packages/over_react/src/component_declaration/annotations.dartdevc.linked.sum -s packages/built_value/built_value.dartdevc.linked.sum -s packages/quiver/iterables.dartdevc.linked.sum -s packages/quiver/collection.dartdevc.linked.sum -s packages/built_collection/built_collection.dartdevc.linked.sum -s packages/built_redux/src/action.dartdevc.linked.sum -s packages/built_redux/built_redux.dartdevc.linked.sum -s packages/over_react/component_base.dartdevc.linked.sum -s packages/react_tracing/w_flux.dartdevc.linked.sum --url-mapping=package:react_tracing/w_flux_browser.dart,packages/react_tracing/w_flux_browser.dart --url-mapping=package:react_tracing/src/util.dart,packages/react_tracing/src/util.dart --url-mapping=package:react_tracing/src/w_flux/traced_flux_component.dart,packages/react_tracing/src/w_flux/traced_flux_component.dart package:react_tracing/w_flux_browser.dart package:react_tracing/src/util.dart package:react_tracing/src/w_flux/traced_flux_component.dart
dart --version: 2.2.0 (Unknown timestamp) on "linux_x64"

NoSuchMethodError: The getter 'staticType' was called on null.
Receiver: null
Tried calling: staticType
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      getStaticType (package:dev_compiler/src/analyzer/element_helpers.dart:86:7)
#2      CodeGenerator._bindValue (package:dev_compiler/src/analyzer/code_generator.dart:5035:36)
#3      CodeGenerator._bindLeftHandSide (package:dev_compiler/src/analyzer/code_generator.dart:4990:11)
#4      CodeGenerator._emitOpAssign (package:dev_compiler/src/analyzer/code_generator.dart:3426:15)
#5      CodeGenerator.visitAssignmentExpression (package:dev_compiler/src/analyzer/code_generator.dart:3399:12)
#6      AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:834:49)
#7      CodeGenerator._visitExpression (package:dev_compiler/src/analyzer/code_generator.dart:5853:18)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#9      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#10     CodeGenerator._visitExpressionList (package:dev_compiler/src/analyzer/code_generator.dart:5874:42)
#11     CodeGenerator.visitCascadeExpression (package:dev_compiler/src/analyzer/code_generator.dart:5154:20)
#12     CascadeExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1440:49)
#13     CodeGenerator.visitExpressionStatement (package:dev_compiler/src/analyzer/code_generator.dart:4125:23)
#14     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4259:49)
#15     CodeGenerator._visitStatement (package:dev_compiler/src/analyzer/code_generator.dart:5862:18)
#16     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#17     ListIterable.toList (dart:_internal/iterable.dart:219:19)
#18     CodeGenerator._visitStatementList (package:dev_compiler/src/analyzer/code_generator.dart:5869:41)
#19     CodeGenerator.visitBlock (package:dev_compiler/src/analyzer/code_generator.dart:3617:16)
#20     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1250:49)
#21     CodeGenerator._visitStatement (package:dev_compiler/src/analyzer/code_generator.dart:5862:18)
#22     CodeGenerator._visitScope (package:dev_compiler/src/analyzer/code_generator.dart:5404:18)
#23     CodeGenerator.visitForStatement (package:dev_compiler/src/analyzer/code_generator.dart:5430:44)
#24     ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5455:49)
#25     CodeGenerator._visitStatement (package:dev_compiler/src/analyzer/code_generator.dart:5862:18)
#26     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#27     ListIterable.toList (dart:_internal/iterable.dart:219:19)
#28     CodeGenerator._visitStatementList (package:dev_compiler/src/analyzer/code_generator.dart:5869:41)
#29     CodeGenerator.visitBlock (package:dev_compiler/src/analyzer/code_generator.dart:3617:16)
#30     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1250:49)
#31     CodeGenerator._visitStatement (package:dev_compiler/src/analyzer/code_generator.dart:5862:18)
#32     CodeGenerator._visitScope (package:dev_compiler/src/analyzer/code_generator.dart:5404:18)
#33     CodeGenerator.visitIfStatement (package:dev_compiler/src/analyzer/code_generator.dart:5414:46)
#34     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:6596:49)
#35     CodeGenerator._visitStatement (package:dev_compiler/src/analyzer/code_generator.dart:5862:18)
#36     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#37     ListIterable.toList (dart:_internal/iterable.dart:219:19)
#38     CodeGenerator._visitStatementList (package:dev_compiler/src/analyzer/code_generator.dart:5869:41)
#39     CodeGenerator.visitBlockFunctionBody (package:dev_compiler/src/analyzer/code_generator.dart:3612:21)
#40     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1195:49)
#41     CodeGenerator._emitFunctionScopedBody (package:dev_compiler/src/analyzer/code_generator.dart:2829:22)
#42     CodeGenerator._emitFunctionBody (package:dev_compiler/src/analyzer/code_generator.dart:2812:17)
#43     CodeGenerator._emitFunction (package:dev_compiler/src/analyzer/code_generator.dart:2796:11)
#44     CodeGenerator._emitMethodDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:2592:12)
#45     CodeGenerator._emitClassMethods (package:dev_compiler/src/analyzer/code_generator.dart:1497:23)
#46     CodeGenerator._emitClassDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:852:21)
#47     CodeGenerator.visitClassDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:811:12)
#48     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#49     CodeGenerator._emitTypeDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:544:26)
#50     CodeGenerator.visitCompilationUnit (package:dev_compiler/src/analyzer/code_generator.dart:598:9)
#51     List.forEach (dart:core/runtime/libarray.dart:106:8)
#52     CodeGenerator.compile (package:dev_compiler/src/analyzer/code_generator.dart:336:22)
#53     compileWithAnalyzer (package:dev_compiler/src/analyzer/module_compiler.dart:107:33)
#54     _compile (package:dev_compiler/src/analyzer/command.dart:152:16)
#55     compile (package:dev_compiler/src/analyzer/command.dart:56:18)
#56     compile (package:dev_compiler/src/compiler/shared_command.dart:385:18)
#57     _CompilerWorker.performRequest.<anonymous closure> (file:///tmp/tmpyaVT9t/dart-2.2.0/dart/pkg/dev_compiler/bin/dartdevc.dart:49:39)
#58     _rootRun (dart:async/zone.dart:1124:13)
#59     _CustomZone.run (dart:async/zone.dart:1021:19)
#60     _runZoned (dart:async/zone.dart:1516:10)
#61     runZoned (dart:async/zone.dart:1463:12)
#62     _CompilerWorker.performRequest (file:///tmp/tmpyaVT9t/dart-2.2.0/dart/pkg/dev_compiler/bin/dartdevc.dart:49:24)
<asynchronous suspension>
#63     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#64     _rootRun (dart:async/zone.dart:1124:13)
#65     _CustomZone.run (dart:async/zone.dart:1021:19)
#66     _runZoned (dart:async/zone.dart:1516:10)
#67     runZoned (dart:async/zone.dart:1463:12)
#68     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#69     main (file:///tmp/tmpyaVT9t/dart-2.2.0/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#70     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:296:32)
#71     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Building with the dart2js compiler is successful. 

My tests did fail because of minor typing issues:
- some `new List.unmodifiable()...`s had to be given type arguments
- calls like `.map((param) => param.thing())` had to be updated to type the param

These issues were expected -- I'm upgrading this Dart 1 repo to be Dart 2 compatible. I thought fixing these issues might fix the DDC build, but it didn't. 

Please let me know if I can provide any other info. Thanks!

**Comment by Markzipan** [comment]
This should've been resolved with our swap to a kernel-backed DDC (a long time ago). Please reopen if it hasn't.
