### ISSUE TITLE
Intellij keeps reloading suggestions while using Dart Analyser

### ISSUE THREAD

**Issue by dhavalagile** [dart-lang/sdk#36147]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.2 unknown, screens 1920x1080`

# Exception

Please append the contents of:
file:///private/var/folders/jf/97l8pz291n7f52f72dmv8fch0000gn/T/report.txt

```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Failed to send notification
NoSuchMethodError: The getter 'returnType' was called on null.
Receiver: null
Tried calling: returnType
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      DartUnitOutlineComputer._newGenericTypeAliasOutline (package:analysis_server/src/computer/computer_outline.dart:232:46)
#2      DartUnitOutlineComputer.compute (package:analysis_server/src/computer/computer_outline.dart:68:26)
#3      sendAnalysisNotificationOutline.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:134:41)
#4      _sendNotification.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:171:8)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#6      _sendNotification (package:analysis_server/src/operation/operation_analysis.dart:169:39)
#7      sendAnalysisNotificationOutline (package:analysis_server/src/operation/operation_analysis.dart:121:3)
#8      ServerContextManagerCallbacks.addAnalysisDriver.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:905:13)
#9      new Future.<anonymous closure> (dart:async/future.dart:176:37)
#10     _rootRun (dart:async/zone.dart:1120:38)

**Comment by bwilkerson** [comment]
Thanks for the report!

This was fixed on bleeding edge by https://dart-review.googlesource.com/c/95080.
