### ISSUE TITLE
Error when trying to rename symbol

### ISSUE THREAD

**Issue by earyzhe** [dart-lang/sdk#36149]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Renaming a symbol in VS code

### Request

While responding to request: `edit.getRefactoring`

### Versions

- Flutter SDK 1.2.2-pre.1
- Visual Studio Code 1.31.1
- Dart Code 2.24.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/earyzhe/dev/SDKs/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.24.0
```

### Exception

InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

```text
#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:199:7)
#1      AnalysisSessionImpl.getResolvedLibrary (package:analyzer/src/dart/analysis/session.dart:150:5)
#2      AnalysisSessionHelper._getResolvedLibrary (package:analyzer/src/dart/analysis/session_helper.dart:74:30)
<asynchronous suspension>
#3      AnalysisSessionHelper.getResolvedUnitByElement (package:analyzer/src/dart/analysis/session_helper.dart:48:33)
<asynchronous suspension>
#4      _ClassMemberValidator._getShadowingLocalElement.getLocalElements (package:analysis_server/src/services/refactoring/rename_class_member.dart:267:46)
<asynchronous suspension>
#5      _ClassMemberValidator._getShadowingLocalElement (package:analysis_server/src/services/refactoring/rename_class_member.dart:285:49)
<asynchronous suspension>
#6      _ClassMemberValidator.validate (package:analysis_server/src/services/refactoring/rename_class_member.dart:210:46)
<asynchronous suspension>
#7      RenameClassMemberRefactoringImpl.checkFinalConditions (package:analysis_server/src/services/refactoring/rename_class_member.dart:67:23)
#8      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:829:39)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1500:12)
#13     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:796:5)
#14     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:684:24)
#15     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:373:16)
#16     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:349:45)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:345:50)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1500:12)
#23     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:344:5)
#24     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#26     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#27     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#36     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#37     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#38     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#47     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#48     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#49     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#50     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#51     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#52     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#53     _rootRunUnary (dart:async/zone.dart:1132:38)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#58     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#59     _StreamController._add (dart:async/stream_controller.dart:640:7)
#60     _StreamController.add (dart:async/stream_controller.dart:586:5)
#61     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#62     _rootRunUnary (dart:async/zone.dart:1136:13)
#63     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#67     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#68     _StreamController._add (dart:async/stream_controller.dart:640:7)
#69     _StreamController.add (dart:async/stream_controller.dart:586:5)
#70     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1323:33)
#71     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:844:14)
#72     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#73     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#74     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#75     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/earyzhe/dev/FlutterProjects/dial_in_v1",
        "explicitFileCount": 53,
        "implicitFileCount": 1371,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment]
@bwilkerson Am I right in thinking this is a VS Code issue and I should be handling this error (maybe retrying a few times like we do for the Cancelled error)?

**Comment by bwilkerson** [comment]
I don't think so. I think server should be catching this exception and returning a Cancelled error. Clients should never see, let alone need to handle, server errors (other than possibly by restarting server after a fatal error).

**Comment by DanTup** [comment]
Ah yes, that makes more sense. I had some memory of seeing it being caught, but I think it was as you described - caught internally (probably while I was implementing LSP methods).

**Comment by bwilkerson** [comment]
I think this CL should catch the exception and return an error response: https://dart-review.googlesource.com/c/sdk/+/98200.
