### ISSUE TITLE
Generated error report.

### ISSUE THREAD

**Issue by derekdreery** [dart-lang/sdk#36161]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Linux(amd64) v4.20.12-arch1-1-ARCH unknown, screens 1920x1080, 1080x1920`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: /home/rdodd/devel/phd/patient-notes/lib/list-page.dart context: exception_20190310_125100_329
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ErrorVerifier._checkForImportInternalLibrary (package:analyzer/src/generated/error_verifier.dart:3757:41)
#2      ErrorVerifier.visitImportDirective (package:analyzer/src/generated/error_verifier.dart:928:7)
#3      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:6737:49)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9166:20)
#5      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2564:19)
#6      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:780:10)
#7      ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:542:11)
#8      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2558:49)
#9      LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:349:10)
#10     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:129:9)
#11     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#12     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:128:13)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:127:34)
#15     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#17     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#18     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1438:63)
#19     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#20     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#21     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1216:17)
<asynchronous suspension>
#22     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#23     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#24     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#25     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#26     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#27     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#33     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#34     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#35     main (file:///b/rr/tmpmr462B/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#36     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#37     main (file:///b/rr/tmpmr462B/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#38     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///tmp/report.txt.:

```
1552222259284 <= {"event":"analysis.errors","params":{"file":"/project/lib/main.dart","errors":[]}}
1552222259292 <= {"event":"analysis.errors","params":{"file":"/project/test/widget_test.dart","errors":[]}}
1552222259295 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1552222259868 => {"id":"29197","method":"analysis.updateContent","params":{"files":{"/project/lib/list-page.dart":{"type":"add","content":"import 'package:faker/faker.dart';
1552222259869 <= {"id":"29197","result":{}}
1552222259869 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1552222259873 => {"id":"29198","method":"edit.getAssists","params":{"file":"/project/lib/list-page.dart","offset":179,"length":0},"clientRequestTime":1552222259873}
1552222259885 <= {"event":"analysis.errors","params":{"file":"/project/lib/list-page.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/home/r
1552222259886 <= {"id":"29198","result":{"assists":[{"message":"Add explicit 'show' combinator","edits":[{"file":"/project/lib/list-page.dart","fileStamp":0,"edits":[{"offse
1552222259887 <= {"event":"analysis.highlights","params":{"file":"/project/lib/list-page.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":34},{"type":"BUILT_IN","off
1552222259888 <= {"event":"analysis.navigation","params":{"file":"/project/lib/list-page.dart","regions":[{"offset":7,"length":26,"targets":[0]},{"offset":42,"length":31,"ta
1552222259888 <= {"event":"analysis.closingLabels","params":{"file":"/project/lib/list-page.dart","labels":[{"offset":229,"length":337,"label":"List.generate"},{"offset":290
1552222259888 <= {"event":"analysis.outline","params":{"file":"/project/lib/list-page.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>",
1552222259889 <= {"event":"analysis.overrides","params":{"file":"/project/lib/list-page.dart","overrides":[{"offset":693,"length":11,"superclassMember":{"element":{"kind":"M
1552222259890 <= {"event":"flutter.outline","params":{"file":"/project/lib/list-page.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":2900,"codeOffset":0,"codeLeng
1552222259891 <= {"event":"analysis.errors","params":{"file":"/project/lib/main.dart","errors":[]}}
1552222259891 <= {"event":"analysis.errors","params":{"file":"/project/test/widget_test.dart","errors":[]}}
1552222259891 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1552222259891 <= {"event":"analysis.implemented","params":{"file":"/project/lib/list-page.dart","classes":[],"members":[]}}
1552222259901 => {"id":"29199","method":"edit.getAssists","params":{"file":"/project/lib/list-page.dart","offset":0,"length":2900},"clientRequestTime":1552222259901}
1552222259902 <= {"id":"29199","result":{"assists":[]}}
1552222260030 => {"id":"29200","method":"edit.getAssists","params":{"file":"/project/lib/list-page.dart","offset":0,"length":2900},"clientRequestTime":1552222260030}
1552222260030 => {"id":"29201","method":"edit.getAssists","params":{"file":"/project/lib/list-page.dart","offset":0,"length":2900},"clientRequestTime":1552222260030}
1552222260032 <= {"id":"29200","result":{"assists":[]}}
1552222260032 <= {"id":"29201","result":{"assists":[]}}
1552222260189 => {"id":"29202","method":"analysis.updateContent","params":{"files":{"/project/lib/list-page.dart":{"type":"add","content":"import 'package:faker/faker.dart';
1552222260191 => {"id":"29203","method":"edit.getAssists","params":{"file":"/project/lib/list-page.dart","offset":181,"length":0},"clientRequestTime":1552222260191}
1552222260192 <= {"id":"29202","result":{}}
1552222260192 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1552222260380 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /project/lib/list-page.dart context: exception_20190310_125100_329","stackTrac
```

**Comment by derekdreery** [comment]
It might be caused by the following method, which I am using to treat nullable values as a `Functor` (`Maybe` in haskell, for instance), so I can map the non-null value.

**Comment by srawlins** [comment]
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).
