### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by DanMossa** [dart-lang/sdk#36169]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2048x1152, 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, FATAL error: FileSystemException: Directory listing failed, path = 'C:\Users\Daniel\AppData\Local\.dartServer\.analysis-driver\' (OS Error: The file or directory is corrupted and unreadable.
, errno = 1392)
#0      _Directory._fillWithDirectoryListing (dart:io/runtime/bindirectory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:249:5)
#2      EvictingFileByteStore._cleanUpFolder (package:analyzer/src/dart/analysis/file_byte_store.dart:114:34)
#3      EvictingFileByteStore._cacheCleanUpFunction.<anonymous closure> (package:analyzer/src/dart/analysis/file_byte_store.dart:101:9)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#7      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#8      _StreamController._add (dart:async/stream_controller.dart:640:7)
#9      _StreamController.add (dart:async/stream_controller.dart:586:5)
#10     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\Daniel\AppData\Local\Temp\report1.txt.

Flutter clean did not seem to fix this issue

**Comment by DanMossa** [comment]
Google Drive was doing some weird sync thing.

Issue resolved once I restarted Google Drive
