### ISSUE TITLE
Generated error report when using autocomplete in `import 'xxx.dart'`

### ISSUE THREAD

**Issue by anticafe** [dart-lang/sdk#36184]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1600x900, 1600x900`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: D:\Projects\Flutter\filestring-flutter\fluttersink\lib\singleview\single_view_index.dart context: exception_20190313_143149_028
NoSuchMethodError: Class 'LibraryElementInBuildUnit' has no instance getter 'session'.
Receiver: Instance of 'LibraryElementInBuildUnit'
Tried calling: session
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      LibraryElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3736:48)
#2      LibraryElementInBuildUnit.session (package:analyzer/src/dart/element/element.dart:5206:25)
#3      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:542:30)
#4      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:397:15)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:137:27)
#6      Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1063:12)
#7      AstRewriteVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:83:35)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8671:49)
#9      MapLiteralEntryImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8242:13)
#10     UnifyingAstVisitor.visitNode (package:an

**Comment by srawlins** [comment]
This should have been fixed by 7418238 which is in Dart 2.3.0.
