### ISSUE TITLE
Analysis server getSuggestionDetails() fails in part file

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#36187]
### What I was doing

Trying to accept a completion from SuggestionSets inside a `part` file. Setup was like this:

#### outer.dart

```dart
library danny;

part 'inner.dart';
```

#### inner.dart

```dart
part of danny;

main() {
  ProcessInf // Invoked completion here
}
```

Using yesterday's nightly build of the SDK:

![Screenshot 2019-03-13 at 12 23 47 pm](https://user-images.githubusercontent.com/1078012/54278675-ecabdb80-458a-11e9-800c-8346ff1a980b.png)

### Versions

- Flutter SDK 1.3.10-pre.5
- Visual Studio Code 1.32.1
- Dart Code 2.25.0-dev

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/dantup/Dev/dart-sdk/nightly-2019-03-12/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.25.0-dev
```

### Exception

Failed to handle completion domain request: {id: 184, method: completion.getSuggestionDetails, params: {file: /Users/dantup/Desktop/Dart Mini Sample 1/bin/inner.dart, id: 10, label: max, offset: 17}, clientRequestTime: 1552479605280}

```text
Invalid argument(s): Is a part: /Users/dantup/Desktop/Dart Mini Sample 1/bin/inner.dart
#0      AnalysisDriver.getResolvedLibrary (package:analyzer/src/dart/analysis/driver.dart:847:7)
#1      AnalysisSessionImpl.getResolvedLibrary (package:analyzer/src/dart/analysis/session.dart:151:20)
#2      CompletionDomainHandler.getSuggestionDetails (package:analysis_server/src/domain_completion.dart:199:45)
<asynchronous suspension>
#3      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:254:9)
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _runZoned (dart:async/zone.dart:1516:10)
#7      runZoned (dart:async/zone.dart:1500:12)
#8      CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:250:12)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:337:45)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:50)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:332:5)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#52     _StreamController._add (dart:async/stream_controller.dart:640:7)
#53     _StreamController.add (dart:async/stream_controller.dart:586:5)
#54     _Socket._onData (dart:io/runtime/bin/socket_patch.dart:1774:41)
#55     _rootRunUnary (dart:async/zone.dart:1136:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#61     _StreamController._add (dart:async/stream_controller.dart:640:7)
#62     _StreamController.add (dart:async/stream_controller.dart:586:5)
#63     new _RawSocket.<anonymous closure> (dart:io/runtime/bin/socket_patch.dart:1323:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io/runtime/bin/socket_patch.dart:844:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#67     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/dantup/Desktop/Dart Mini Sample 1",
        "explicitFileCount": 4,
        "implicitFileCount": 195,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/96831

**Comment by DanTup** [comment]
Works great, thanks!
