### ISSUE TITLE
Dart2JS allows "if (null)", at least on DartPad

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#36198]
```dart
void main() {
  if (null) {
    print('Hello');
  } else {
    print('Goodbye');
  }
}
```

... prints `Goodbye`. On the VM I get:

```bash
Unhandled exception:
Failed assertion: boolean expression must not be null
#0      main (file:///tmp/null.dart)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by matanlurey** [comment]
See https://github.com/dart-lang/sdk/issues/36193.

**Comment by rakudrama** [comment]
I'm closing this as a dup of #34147
I'm sure there is a similar issue for other boolean contexts like `&&`.
I'm hoping this all goes away with NNBD.
