### ISSUE TITLE
dart2js not setting default function field

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#36222]
I have the following program:

```dart
typedef int BinaryFunc(int x, int y);

class A {
  const A({this.foo = A.defaultFoo});

  static int defaultFoo(int x, int y) {
    return x + y;
  }

  final BinaryFunc foo;
}

class B<T> {
  T get item => _item;
  T _item;
}

class C extends B<A> {
  bar() {
    print(item.foo(1, 2));
  }
}

class Box {
  final B<Object> b;
  Box(B<Object> b) : this.b = b;

  update(Object o) {
    b._item = o;
  }
}

main() {
  var c = C();
  var box1 = Box(c);

  var b = B<int>();
  var box2 = Box(b);

  box2.update(3);
  box1.update(A());

  c.bar();
}
```

This code works fine in older versions of dart2js (works on Dartpad), but fails on the most current version of dart2js (Dart-to-JavaScript compiler (dart2js) version: 2.2.1-edge.5e1397fc4e7dd8e32a79252a7e780d120c939392).

dart2js emits this code for the class A:

```
  T.A.prototype = {
    foo$2: function(arg0, arg1) {
      return this.foo.call$2(arg0, arg1);
    }
  };
```

but it never sets `this.foo` so when `c.bar()` is run, it crashes with:

 ```
TypeError: Cannot read property 'call$2' of undefined
          throw e;
          ^
TypeError: Cannot read property 'call$2' of undefined
    at A.foo$2 (out.js:1464:23)
    at main (out.js:1221:33)
    at action (/usr/local/google/home/het/Projects/dart/sdk/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (/usr/local/google/home/het/Projects/dart/sdk/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (/usr/local/google/home/het/Projects/dart/sdk/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at out.js:1534:7
    at out.js:1520:7
    at dartProgram (out.js:1531:5)
    at out.js:1538:3
```

**Comment by vsmenon** [comment]
@kevmoo - I've been folding 2.2.1 issues to 2.3.

**Comment by sigmundch** [comment]
@johnniwinther - I bisected this and found that this started failing with 1720704594e0cd15da0050325780f505fc9996f1

**Comment by johnniwinther** [comment]
A fix is in the pipeline: https://dart-review.googlesource.com/c/sdk/+/97082
