### ISSUE TITLE
Dart Analyzer Error: Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by yukixoma** [dart-lang/sdk#36227]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: D:\WORK\FlutterApp\han_van\lib\main.dart context: exception_20190315_141829_710
NoSuchMethodError: Class 'LibraryElementInBuildUnit' has no instance getter 'session'.
Receiver: Instance of 'LibraryElementInBuildUnit'
Tried calling: session
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      LibraryElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3736:48)
#2      LibraryElementInBuildUnit.session (package:analyzer/src/dart/element/element.dart:5206:25)
#3      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:542:30)
#4      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:397:15)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:137:27)
#6      Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1063:12)
#7      AstRewriteVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:83:35)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8671:49)
#9      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2535:16)
#10     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#11     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#12     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#13     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#14     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#15     FunctionElementForLink_Initializer.returnType (package:analyzer/src/summary/link.dart:2852:24)
#16     InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:423:37)
#17     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:303:11)
#18     InstanceMemberInferrer._inferClasses (package:analyzer/src/task/strong_mode.dart:326:9)
#19     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:55:5)
#20     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1638:7)
#21     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#22     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#23     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#24     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#25     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#26     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#27     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#28     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#29     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#30     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#31     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#32     _relink (package:analyzer/src/summary/link.dart:305:57)
#33     link (package:analyzer/src/summary/link.dart:123:3)
#34     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#35     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#36     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#37     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#38     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#39     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#40     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#41     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#42     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#43     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#44     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#45     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#46     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#47     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#48     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#49     _rootRun (dart:async/zone.dart:1124:13)
#50     _CustomZone.run (dart:async/zone.dart:1021:19)
#51     _runZoned (dart:async/zone.dart:1516:10)
#52     runZoned (dart:async/zone.dart:1463:12)
#53     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#54     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#55     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#56     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#57     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#58     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#59     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#60     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\Yuki\AppData\Local\Temp\report2.txt.

**Comment by parlough** [comment]
Seems to be the same issue as https://github.com/dart-lang/sdk/issues/36872

Likely fixed by https://github.com/dart-lang/sdk/commit/7418238239f885ba92093c44a1768f8ec93b121f
