### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by rishav00a** [dart-lang/sdk#36248]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: E:\ImpProj\flutter\battle\lib\main.dart context: exception_20190318_165344_806
NoSuchMethodError: Class 'LibraryElementInBuildUnit' has no instance getter 'session'.
Receiver: Instance of 'LibraryElementInBuildUnit'
Tried calling: session
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      LibraryElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3736:48)
#2      LibraryElementInBuildUnit.session (package:analyzer/src/dart/element/element.dart:5206:25)
#3      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:542:30)
#4      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:397:15)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:137:27)
#6      Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1063:12)
#7      AstRewriteVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:83:35)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8671:49)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9166:20)
#10     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7947:15)
#11     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3544:10)
#12     UnifyingAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:3505:43)
#13     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7942:49)
#14     ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2535:16)
#15     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#16     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#19     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#20     FunctionElementForLink_Initializer.returnType (package:analyzer/src/summary/link.dart:2852:24)
#21     InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:423:37)
#22     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:303:11)
#23     InstanceMemberInferrer._inferClasses (package:analyzer/src/task/strong_mode.dart:326:9)
#24     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:55:5)
#25     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1638:7)
#26     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#27     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#28     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#29     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#30     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#31     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#32     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#33     _relink (package:analyzer/src/summary/link.dart:305:57)
#34     link (package:analyzer/src/summary/link.dart:123:3)
#35     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#36     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#37     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#38     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#39     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#40     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#41     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#42     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#43     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#44     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#45     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#46     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#47     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#48     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#49     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#50     _rootRun (dart:async/zone.dart:1124:13)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _runZoned (dart:async/zone.dart:1516:10)
#53     runZoned (dart:async/zone.dart:1463:12)
#54     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#55     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#56     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#57     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#58     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#59     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#60     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#61     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by slightfoot** [comment]
Same issue just occurred for me: 

## Version information

- `IDEA IU-183.5429.30`
- `2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec`
- `IU-183.5429.30, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2560x1440, 1920x1200, 1920x1200`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec, server version 1.24.0, error: Analysis failed: C:\Users\Simon\Git\arshopping\lib\main.dart
NoSuchMethodError: Class 'LibraryElementInBuildUnit' has no instance getter 'session'.
Receiver: Instance of 'LibraryElementInBuildUnit'
Tried calling: session
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      LibraryElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3742:48)
#2      LibraryElementInBuildUnit.session (package:analyzer/src/dart/element/element.dart:5206:25)
#3      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:542:30)
#4      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:397:15)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:137:27)
#6      Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1063:12)
#7      AstRewriteVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:85:35)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7489:49)
#9      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2541:16)
#10     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5292:36)
#11     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5142:7)
#12     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2223:13)
#13     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2242:18)
#14     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5568:47)
#15     FunctionElementForLink_Initializer.returnType (package:analyzer/src/summary/link.dart:2858:24)
#16     InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:423:37)
#17     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:303:11)
#18     InstanceMemberInferrer._inferClasses (package:analyzer/src/task/strong_mode.dart:326:9)
#19     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:55:5)
#20     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1644:7)
#21     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3816:12)
#22     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3522:15)
#23     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3462:7)
#24     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2223:13)
#25     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2242:18)
#26     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3495:42)
#27     Linker.link (package:analyzer/src/summary/link.dart:4018:35)
#28     _relink (package:analyzer/src/summary/link.dart:305:57)
#29     link (package:analyzer/src/summary/link.dart:123:3)
#30     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#31     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#32     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#33     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#34     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#35     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#36     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#37     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#38     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1216:17)
<asynchronous suspension>
#39     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#40     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#41     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#42     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#43     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#44     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:511:21)
#45     _rootRun (dart:async/zone.dart:1124:13)
#46     _CustomZone.run (dart:async/zone.dart:1021:19)
#47     _runZoned (dart:async/zone.dart:1516:10)
#48     runZoned (dart:async/zone.dart:1463:12)
#49     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:594:12)
#50     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:509:7)
#51     Driver.start (package:analysis_server/src/server/driver.dart:412:7)
#52     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#53     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#54     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#55     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#56     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

**Comment by parlough** [comment]
Seems to be the same issue as https://github.com/dart-lang/sdk/issues/36872

Likely fixed by https://github.com/dart-lang/sdk/commit/7418238239f885ba92093c44a1768f8ec93b121f
