### ISSUE TITLE
Crash while adding /* inside formal parameter list

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#36241]
@danrubel 

Analyzer Feedback from IntelliJ

## Version information

- `IDEA 192.SNAPSHOT`
- `2.2.1-edge.8e550f6a4c098944bf838990618cfa15068ebc1f`
- `IC-192.SNAPSHOT, JRE 1.8.0_112-b16x64 Oracle Corporation, OS Mac OS X(x86_64) v10.14.3, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.8e550f6a4c098944bf838990618cfa15068ebc1f, server version 1.25.0, error: Captured exception
Can't find ')' to match '('.
#0      ErrorToken.lexeme (package:front_end/src/fasta/scanner/error_token.dart:75:24)
#1      _withArgumentsExpectedFunctionBody (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/front_end/lib/src/fasta/fasta_codes_generated.dart:2854:25)
#2      Parser.ensureBlock (package:front_end/src/fasta/parser/parser.dart:2630:20)
#3      Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3439:17)
#4      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3103:15)
#5      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2973:15)
#6      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2778:15)
#7      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1762:13)
#8      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1722:14)
#9      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:574:14)
#10     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#11     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:349:15)
#12     ParserAdapter.parseCompilationUnit2 (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/parser_fasta.dart:185:32)
#13     ParserAdapter.parseCompilationUnit (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/parser_fasta.dart:180:12)
#14     _File._parse (package:analyzer/src/services/available_declarations.dart:1453:23)
#15     _File.refresh (package:analyzer/src/services/available_declarations.dart:1027:30)
#16     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:629:12)
#17     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:494:7)
#18     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:200:13)
<asynchronous suspension>
#19     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#20     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#21     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#22     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#23     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#24     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#30     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#31     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#32     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:12:11)
#33     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#34     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:10:10)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/cp/_32g44l548q8d0bfj4_l9s3m003ky_/T/report.txt.

**Comment by scheglov** [comment]
I typed it on the line `52`.
Once I typed `*` after `/` it crashed. 

```dart
// Copyright (c) 2019, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:analyzer/error/error.dart';
import 'package:analyzer/error/listener.dart';
import 'package:analyzer/src/dart/element/type.dart';
import 'package:analyzer/src/error/codes.dart';
import 'package:analyzer/src/generated/resolver.dart';

class LiteralVerifier {
  final TypeProvider _typeProvider;
  final TypeSystem _typeSystem;
  final ErrorReporter _errorReporter;
  final Function(Expression) _checkForUseOfVoidResult;

  final bool forList;
  final bool forSet;
  final DartType elementType;

  final bool forMap;
  final DartType mapKeyType;
  final DartType mapValueType;

  LiteralVerifier(
    this._typeProvider,
    this._typeSystem,
    this._errorReporter,
    this._checkForUseOfVoidResult, {
    this.forList = false,
    this.forSet = false,
    this.elementType,
    this.forMap = false,
    this.mapKeyType,
    this.mapValueType,
  });

  void verify(CollectionElement element) {
    _verifyElement(element);
    // StaticWarningCode.LIST_ELEMENT_TYPE_NOT_ASSIGNABLE
  }

  /**
   * Verify that the type of the elements of the given [spreadExpression] (the
   * [spreadType]) can be assigned to the element type of the
   * enclosing collection (the [elementType]). If not, report an error with the
   * given [errorCode].
   */
  void _checkForArgumentTypeNotAssignableInSpread(Expression spreadExpression,
      DartType spreadType, DartType elementType/*, ErrorCode errorCode) {
    if (elementType == null) return;
    if (spreadType == null) return;

    if (!elementType.isVoid && _checkForUseOfVoidResult(spreadExpression)) {
      return;
    }

    if (spreadType is InterfaceType) {
      if (spreadType.isDartCoreNull) return;

      if (forList || forSet) {
        var iterableObject = _typeProvider.iterableObjectType;
        if (!_typeSystem.isSubtypeOf(spreadType, iterableObject)) {
          _errorReporter.reportErrorForNode(
            CompileTimeErrorCode.NOT_ITERABLE_SPREAD,
            spreadExpression,
          );
          return;
        }

        InterfaceType iterableType = (spreadType as InterfaceTypeImpl)
            .asInstanceOf(_typeProvider.iterableType.element);
        _checkForAssignable(
          spreadExpression,
          iterableType.typeArguments[0],
          elementType,
          errorCode,
        );
        return;
      }

      if (forMap) {}
      if (_typeSystem.isSubtypeOf(
          spreadType, _typeProvider.mapObjectObjectType)) {
        // TODO(brianwilkerson) Handle spreads involving maps? This method
        //  isn't currently called for maps, but might be if it's reworked as
        //  expected.
//          InterfaceType mapType =
//              (spreadExpressionType as InterfaceTypeImpl)
//                  .asInstanceOf(_typeProvider.mapType.element);
//          if (mapType != null) {
//            List<DartType> typeArguments = mapType.typeArguments;
//            if (typeArguments.length == 2) {
//              _checkForAssignableExpressionAtType(
//                  spreadExpression, typeArguments[0], keyType, errorCode);
//              _checkForAssignableExpressionAtType(
//                  spreadExpression, typeArguments[1], valueType, errorCode);
//              return;
//            }
//          }
      }
    }

    // TODO(scheglov) when do we do this?
//    _checkForAssignable(spreadExpression, spreadType, elementType, errorCode);
  }

  bool _checkForAssignable(Expression expression, DartType expressionType,
      DartType expectedType, ErrorCode errorCode) {
    if (!_typeSystem.isAssignableTo(expressionType, expectedType)) {
      _errorReporter.reportTypeErrorForNode(
        errorCode,
        expression,
        [expressionType, expectedType],
      );
      return false;
    }
    return true;
  }

  /**
   * Verify that the given [element] can be assigned to the [elementType] of the
   * enclosing list or set literal. Report an error with the given [errorCode]
   * if not.
   *
   * This method corresponds to
   * [BestPracticesVerifier.checkForArgumentTypeNotAssignableWithExpectedTypes].
   */
  void _verifyElement(CollectionElement element) {
    if (element is ForElement) {
      _verifyElement(element.body);
    } else if (element is IfElement) {
      _verifyElement(element.thenElement);
      _verifyElement(element.elseElement);
    } else if (element is Expression) {
      var errorCode = forList
          ? StaticWarningCode.LIST_ELEMENT_TYPE_NOT_ASSIGNABLE
          : StaticWarningCode.SET_ELEMENT_TYPE_NOT_ASSIGNABLE;
      _checkForAssignable(element, element.staticType, elementType, errorCode);
    } else if (element is SpreadElement) {
      Expression expression = element.expression;
      _checkForArgumentTypeNotAssignableInSpread(
          expression, expression.staticType, elementType,  null);
    }
  }

//  /**
//   * Verify that the given [element] can be assigned to the [elementType] of the
//   * enclosing list or set literal. Report an error with the given [errorCode]
//   * if not.
//   *
//   * This method corresponds to
//   * [BestPracticesVerifier.checkForArgumentTypeNotAssignableWithExpectedTypes].
//   */
//  void _checkForMapElementTypeNotAssignableWithKeyOrValueType(
//      CollectionElement element,
//      DartType keyType,
//      DartType valueType,
//      ErrorCode keyErrorCode,
//      ErrorCode valueErrorCode) {
//    if (element is ForElement) {
//      _checkForMapElementTypeNotAssignableWithKeyOrValueType(
//          element.body, keyType, valueType, keyErrorCode, valueErrorCode);
//    } else if (element is IfElement) {
//      _checkForMapElementTypeNotAssignableWithKeyOrValueType(
//          element.thenElement,
//          keyType,
//          valueType,
//          keyErrorCode,
//          valueErrorCode);
//      _checkForMapElementTypeNotAssignableWithKeyOrValueType(
//          element.elseElement,
//          keyType,
//          valueType,
//          keyErrorCode,
//          valueErrorCode);
//    } else if (element is MapLiteralEntry) {
//      _checkForArgumentTypeNotAssignableWithExpectedTypes(
//          element.key, keyType, keyErrorCode);
//      _checkForArgumentTypeNotAssignableWithExpectedTypes(
//          element.value, valueType, valueErrorCode);
//    } else if (element is SpreadElement) {
//      Expression expression = element.expression;
//      DartType expressionType = getStaticType(expression);
//      if (expressionType is ParameterizedType) {
//        List<DartType> typeArguments = expressionType.typeArguments;
//        if (typeArguments.length == 2) {
//          _checkForArgumentTypeNotAssignable(
//              expression, keyType, typeArguments[0], keyErrorCode);
//          _checkForArgumentTypeNotAssignable(
//              expression, valueType, typeArguments[1], valueErrorCode);
//        }
//      }
//    }
//  }
}
```

**Comment by srawlins** [comment]
This looks similar to https://github.com/dart-lang/sdk/issues/39161, and otherwise has not been reported again since Dart 2.5.0; please re-open if you see this in a recent version of Dart/Flutter.
