### ISSUE TITLE
Failed to handle request:

### ISSUE THREAD

**Issue by mdtaqi98** [dart-lang/sdk#36259]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3 unknown, screens 1280x800`

# Exception

Please append the contents of:
file:///private/var/folders/tf/gbd9tr755j97qb39mf16lt_w0000gn/T/report.txt

```
Dart analysis server, SDK version 2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec, server version 1.24.0, FATAL error: Failed to handle request: {id: 29, method: edit.getFixes, params: {file: /Users/mdtaqi/Downloads/analise project list/community app/analise_test/lib/screens/Home/People.dart, offset: 214}, clientRequestTime: 1552993726381}
NoSuchMethodError: The getter 'namedNames' was called on null.
Receiver: null
Tried calling: namedNames
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      FixProcessor._addFix_changeArgumentName.getNamedParameterNames (package:analysis_server/src/services/correction/fix_internal.dart:1043:27)
#2      FixProcessor._addFix_changeArgumentName (package:analysis_server/src/services/correction/fix_internal.dart:1059:48)
<asynchronous suspension>
#3      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:473:13)
<asynchronous suspension>
#4      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#5      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:589:46)
<asynchronous suspension>
#6      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:264:32)
<asynchronous suspension>
#7      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:367:9)

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-lang/sdk/commit/9f59f46650a4098698c24e1dceafaa326123911f
