### ISSUE TITLE
CFE: Support `await` in UI as code constructs

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#36277]
The VM-specific `async` transformation needs to handle `await` and `await for` in the UI as code constructs in collection literals.

**Comment by a-siva** [comment]
I presume the failure
```
sivalinuxmach[sdk]>out/DebugX64/dart --enable-experiment=spread-collections tests/language_2/spread_collections/await_test.dart
NoSuchMethodError: The method '&' was called on null.
Receiver: null
Tried calling: &(7)
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      BinaryPrinter.visitVariableGet (package:kernel/binary/ast_to_binary.dart:1279:15)
#2      VariableGet.accept (package:kernel/ast.dart:2258:36)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:371:10)
#4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:56:11)
#5      BinaryPrinter.visitMethodInvocation (package:kernel/binary/ast_to_binary.dart:1384:5)
#6      MethodInvocation.accept (package:kernel/ast.dart:2857:36)
```
is related to this.

**Comment by kmillikin** [comment]
@a-siva, it's likely.  I've started to fix the async transformation.

**Comment by kmillikin** [comment]
Proposed fix is at https://dart-review.googlesource.com/c/sdk/+/98339
