### ISSUE TITLE
Compiling error: Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't.

### ISSUE THREAD

**Issue by dblokhin** [dart-lang/sdk#36272]
I've got this message during compilation flutter app:
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't.
Error message was 'RangeError (index): Index out of range: no indices are valid: 0'.
Stacktrace included '#0      Uint8List.[] (dart:typed_data/runtime/libtyped_data_patch.dart:2177:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:95:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:115:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:426:17)
#4      IncrementalCompiler.initializeFromDill (package:front_end/src/fasta/incremental_compiler.dart:499:14)
<asynchronous suspension>
#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:133:34)
<asynchronous suspension>
#6      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#14     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:116:20)
<asynchronous suspension>
#15     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:50:44)
<asynchronous suspension>
#16     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:339:67)
#17     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#18     _rootRun (dart:async/zone.dart:1120:38)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#25     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#26     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#27     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
'.
This might be a bug.

The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///tmp/initialize_from.dillOWXECR/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.

// then normaly:
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device Android SDK built for x86...
```

Flutter SDK version:
```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale ru_RU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
```
[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/2987318/initialize_from.dill.gz)

**Comment by dblokhin** [comment]
I've just added few lines in Material constructor:
```
MaterialApp(
      debugShowCheckedModeBanner: false,
      showSemanticsDebugger: false,
// added lines >>>
      supportedLocales: [
        const Locale('ru', 'RU'),
      ],
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
// <<< added
      title: 'Kinosov',
      theme: kinosovTheme,
      home: StreamBuilder(...
```

**Comment by jensjoha** [comment]
I can't reproduce, but what happens is, that somehow an empty file was created, and then we tried to load that. I'll make sure we don't issue a warning like this when the file is empty.
