### ISSUE TITLE
CFE: report compile-time errors for invalid spread collections in constants

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#36286]
Certain test cases in language_2/spread_collections/const_error_test pass for wrong reason:

```
tools/test.py --print-passing-stdout -n dartk-linux-debug-x64 language_2/spread_collections/const_error_test/16
```

```
tools/testing/dart/main.dart:1: Warning: Interpreting this as package URI, 'package:test_dart/main.dart'.
Test configuration:
    dartk-linux-debug-x64(architecture: x64, compiler: dartk, mode: debug, runtime: vm, system: linux, vm-options: [], dart2js-options: [], timeout: null, preview-dart-2)
Suites tested: language_2

exit code:
254

stderr:
Unhandled exception:
'file:///[...]/out/DebugX64/generated_tests/language_2/spread_collections/const_error_test_16.dart': error: Not a constant expression: unexpected kernel tag InvalidExpression (19)
#0      main ([...]/out/DebugX64/generated_tests/language_2/spread_collections/const_error_test_16.dart:20:3)
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:300:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
[00:01 | 100% | +    1 | -    0]
```

I think this should be caught in CFE.

This is also causing problems in bytecode generator as error is not reported, but constant evaluator fails to evaluate a constant.

/cc @kmillikin @askeksa-google

**Comment by kmillikin** [comment]
Constant evaluation errors will be caught in the CFE by the Fasta's constant evaluator, which is under the experimental feature flag `constant-update-2018`.  Note that we will have to enable that flag for UI as code tests.

Once we switch that on, there will only be one constant evaluator and the bytecode generator should work fine.

**Comment by kmillikin** [comment]
As far as I can tell, this is fixed by turning on CFE constant evaluation.  The error is now reported by Fasta:

```Error: The element '1' conflicts with another existing element in the set.
out/ReleaseX64/generated_tests/language_2/spread_collections/const_error_test_16.dart:67:9: Context: While analyzing:
  const _ = {...[1], ...[1]}; //# 16: compile-time error
        ^
```
