### ISSUE TITLE
_getCrashDump is broken

### ISSUE THREAD

**Issue by huiyiqun** [dart-lang/sdk#36281]
* Dart SDK Version (`dart --version`)
Dart VM version: 2.1.1 (Unknown timestamp) on "linux_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
any

When I try to debug my stuck application with the Observatory, I meet following error(from the json I got)

```json
{"jsonrpc":"2.0","id":"","error":{"code":-32603,"message":"Internal error","data":{"details":"_getCrashDump: Unexpected exception:type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'\n#0      Message.toUri (dart:_vmservice/message.dart:122:51)\n#1      VMService._getCrashDump (dart:_vmservice:637:27)\n<asynchronous suspension>\n#2      VMService._routeRequestImpl (dart:_vmservice:666:22)\n<asynchronous suspension>\n#3      VMService.routeRequest (dart:_vmservice:656:36)\n<asynchronous suspension>\n#4      Client.onRequest (dart:_vmservice/client.dart:44:13)\n#5      Server._requestHandler (dart:vmservice_io/server.dart:335:12)\n<asynchronous suspension>\n#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)\n#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#9      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)\n#10     _StreamController._add (dart:async/stream_controller.dart:640:7)\n#11     _StreamController.add (dart:async/stream_controller.dart:586:5)\n#12     _HttpServer._handleRequest (dart:_http/http_impl.dart:2664:19)\n#13     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2422:19)\n#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)\n#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#17     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)\n#18     _StreamController._add (dart:async/stream_controller.dart:640:7)\n#19     _StreamController.add (dart:async/stream_controller.dart:586:5)\n#20     _HttpParser._headersEnd (dart:_http/http_parser.dart:372:19)\n#21     _HttpParser._doParse (dart:_http/http_parser.dart:701:15)\n#22     _HttpParser._parse (dart:_http/http_parser.dart:318:7)\n#23     _HttpParser._onData (dart:_http/http_parser.dart:810:5)\n#24     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)\n#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#27     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)\n#28     _StreamController._add (dart:async/stream_controller.dart:640:7)\n#29     _StreamController.add (dart:async/stream_controller.dart:586:5)\n#30     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1722:41)\n#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)\n#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#34     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)\n#35     _StreamController._add (dart:async/stream_controller.dart:640:7)\n#36     _StreamController.add (dart:async/stream_controller.dart:586:5)\n#37     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1284:33)\n#38     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)\n#39     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)\n#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)\n#41     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)\n#42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)\n"}}}
```

**Comment by a-siva** [comment]
_getCrashDump was an internal functionality and support for it has been removed.
