### ISSUE TITLE
Constant evaluation regression with DDK

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#36285]
I'm seeing the following trace when compiling flutter web with DDK:

```
NoSuchMethodError: The getter 'parent' was called on null.
Receiver: null
Tried calling: parent
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      ConstantEvaluator.unevaluated (package:front_end/src/fasta/kernel/constant_evaluator.dart:504:19)
#2      ConstantEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:724:14)
#3      ConstructorInvocation.accept (package:kernel/ast.dart:3017:36)
#4      ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:540:37)
#5      ConstantEvaluator.visitStaticGet.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:1293:20)
#6      ConstantEvaluator.runInsideContext (package:front_end/src/fasta/kernel/constant_evaluator.dart:548:17)
#7      ConstantEvaluator.visitStaticGet.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:1292:18)
#8      ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:1596:16)
#9      ConstantEvaluator.visitStaticGet (package:front_end/src/fasta/kernel/constant_evaluator.dart:1284:12)
#10     StaticGet.accept (package:kernel/ast.dart:2658:36)
#11     ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:540:37)
#12     ConstantEvaluator.evaluate (package:front_end/src/fasta/kernel/constant_evaluator.dart:459:14)
#13     DevCompilerConstants.evaluate (package:dev_compiler/src/kernel/constants.dart:40:34)
#14     ProgramCompiler.visitStaticGet (package:dev_compiler/src/kernel/compiler.dart:3843:30)
#15     StaticGet.accept (package:kernel/ast.dart:2658:36)
#16     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3103:20)
```
fyi - @jakemac53 @askeksa-google @Markzipan @jmesserly

**Comment by vsmenon** [comment]
@Markzipan is bisecting - @jakemac53 believes we were able build with an sdk from Monday.

**Comment by vsmenon** [comment]
@jmesserly suggests explicitly turning on the new kernel constants.

**Comment by jmesserly** [comment]
We could also simply remove this block of code:
```dart
    if (target is Field && target.isConst) {
      var value = _constants.evaluate(target.initializer);
      if (value is PrimitiveConstant) return value.accept(this);
    }
```
Once we enable CFE's constant evaluation, we can simplify it to something like this:
```dart
    if (target is Field && target.isConst) {
      var init = target.initializer;
      if (init is ConstantExpression && init.constant is PrimitiveConstant) {
        return init.accept(this); // inline primitive constants
      }
    }
```
BTW, we probably don't want to inline large Strings, as the code currently does.

**Comment by Markzipan** [comment]
The error occurs between https://dart-review.googlesource.com/c/sdk/+/97116 (no error) and https://github.com/dart-lang/sdk/commit/c10ee9971f478d79a19e2de957d4a6f0eec61983 (error).

This likely has something to do with Fasta's constant evaluator move.

**Comment by vsmenon** [comment]
Is the CFE's constant evaluation something we enable / test out yet?

**Comment by vsmenon** [comment]
I can validate that, if we remove the constant inlining optimization that @jmesserly refers to, flutter_web samples work.

**Comment by vsmenon** [comment]
https://dart-review.googlesource.com/c/sdk/+/97351

**Comment by askeksa-google** [comment]
This particular crash should be fixed by https://dart-review.googlesource.com/c/sdk/+/97326 when that lands.

**Comment by vsmenon** [comment]
I landed @jmesserly 's workaround to unblock us.  

@askeksa-google - can you please update this bug when your CL lands?

**Comment by askeksa-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/97326 has landed now.

**Comment by jmesserly** [comment]
I think this bug will be obsolete once we enable the constants experiment in the CFE.
