### ISSUE TITLE
Crash in parallel marker while iterating new space on arm64

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#36292]
From [this crash](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8918537308185624240/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0):
```
/============================================================================\
| standalone_2/no_lazy_dispatchers_test broke (Pass -> Crash, expected Pass) |
\============================================================================/

--- Command "vm" (took 11.000184s):
DART_CONFIGURATION=ReleaseXARM64 out/ReleaseXARM64/dart --no_lazy_dispatchers --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/no_lazy_dispatchers_test.dart

exit code:
-6

stderr:
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x7373616c437360
version=2.2.1-edge.9910374c2069fd79e888fa06c3d385e92b7e3462 (Tue Mar 19 17:28:00 2019 +0000) on "linux_arm64"
thread=407, isolate=kernel-service(0xaaaad5107200)
  [0x0000aaaaccb209e0] Unknown symbol
  [0x0000aaaaccb209e0] Unknown symbol
  [0x0000aaaaccb28af8] dart::Scavenger::VisitObjectPointers(dart::ObjectPointerVisitor*) const
  [0x0000aaaaccb1f1dc] dart::GCMarker::IterateRoots(dart::ObjectPointerVisitor*)
  [0x0000aaaaccb20ba8] Unknown symbol
  [0x0000aaaacc9d6b10] dart::ThreadPool::Worker::Loop()
  [0x0000aaaacc9d6940] dart::ThreadPool::Worker::Main(unsigned long)
  [0x0000aaaacc943d20] Unknown symbol
  [0x0000ffff9cdbbfc4] Unknown symbol
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -n dartk-linux-release-arm64 standalone_2/no_lazy_dispatchers_test
```

The coredumps are available [here](https://isolateserver.appspot.com/browse?namespace=default-gzip&hash=a8bc0680de47c8a2df679470395443b62ce892fa)

**Comment by mkustermann** [comment]
From the coredump:
```

Thread 7 (Thread 0xffff9c73f150 (LWP 48729)):
#0  0x0000ffff9cdc230c in __pthread_cond_wait (cond=0xaaaad50e2f30, mutex=0xaaaad50e2f00) at pthread_cond_wait.c:186
#1  0x0000aaaacc944388 in dart::Monitor::WaitMicros (this=0xaaaad50e2f00, micros=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:443
#2  0x0000aaaaccafd968 in dart::MonitorLocker::Wait (this=<optimized out>, millis=0) at ../../runtime/vm/lockers.h:169
#3  dart::BackgroundCompiler::Run (this=0xaaaad50e0750) at ../../runtime/vm/compiler/jit/compiler.cc:1530
#4  0x0000aaaacc9d6b10 in dart::ThreadPool::Worker::Loop (this=0xaaaad51340a0) at ../../runtime/vm/thread_pool.cc:381
#5  0x0000aaaacc9d6940 in dart::ThreadPool::Worker::Main (args=187650695970976) at ../../runtime/vm/thread_pool.cc:436
#6  0x0000aaaacc943d20 in dart::ThreadStart (data_ptr=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:134
#7  0x0000ffff9cdbbfc4 in start_thread (arg=0xaaaacc943ca8 <dart::ThreadStart(void*)>) at pthread_create.c:335
#8  0x0000ffff9cc87110 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

Thread 6 (Thread 0xffff9c63f150 (LWP 48730)):
#0  0x0000ffff9cdc230c in __pthread_cond_wait (cond=0xaaaad50e2c90, mutex=0xaaaad50e2c60) at pthread_cond_wait.c:186
#1  0x0000aaaacc944388 in dart::Monitor::WaitMicros (this=0xaaaad50e2c60, micros=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:443
#2  0x0000aaaaccb1fa70 in dart::MonitorLocker::Wait (this=<optimized out>, millis=0) at ../../runtime/vm/lockers.h:169
#3  dart::ThreadBarrier::Sync (this=<optimized out>) at ../../runtime/vm/thread_barrier.h:68
#4  dart::GCMarker::MarkObjects (this=0xaaaad51046c0, page_space=0xaaaad50fd208, collect_code=<optimized out>) at ../../runtime/vm/heap/marker.cc:966
#5  0x0000aaaaccb24d5c in dart::PageSpace::CollectGarbageAtSafepoint (this=0xaaaad50fd208, compact=false, finalize=true, pre_wait_for_sweepers=<optimized out>, pre_safe_point=<optimized out>) at ../../runtime/vm/heap/pages.cc:1125
#6  0x0000aaaaccb24ab4 in dart::PageSpace::CollectGarbage (this=0xaaaad50fd208, compact=false, finalize=true) at ../../runtime/vm/heap/pages.cc:1056
#7  0x0000aaaaccb1c8d8 in dart::Heap::CollectOldSpaceGarbage (this=0xaaaad50fd000, thread=<optimized out>, type=dart::Heap::kMarkSweep, reason=<optimized out>) at ../../runtime/vm/heap/heap.cc:492
#8  0x0000aaaacc9d3c90 in dart::Thread::HandleInterrupts (this=0xaaaad5127700) at ../../runtime/vm/thread.cc:513
#9  0x0000aaaacc99ff88 in dart::DRT_HelperStackOverflow (isolate=<optimized out>, thread=<optimized out>, zone=<optimized out>, arguments=...) at ../../runtime/vm/runtime_entry.cc:2064
#10 dart::DRT_StackOverflow (arguments=...) at ../../runtime/vm/runtime_entry.cc:2020
#11 0x0000ffff9c74146c in ?? ()
#12 0x0000ffff998578e1 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 5 (Thread 0xffff945bf150 (LWP 408)):
#0  0x0000ffff9cdc26ac in __pthread_cond_timedwait (cond=0xaaaad5134530, mutex=0xaaaad5134500, abstime=0xffff945be3d0) at pthread_cond_timedwait.c:198
#1  0x0000aaaacc944370 in dart::Monitor::WaitMicros (this=0xaaaad5134500, micros=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:448
#2  0x0000aaaacc9d6ab4 in dart::MonitorLocker::WaitMicros (this=<optimized out>, micros=137) at ../../runtime/vm/lockers.h:177
#3  dart::ThreadPool::Worker::Loop (this=0xaaaad5134500) at ../../runtime/vm/thread_pool.cc:394
#4  0x0000aaaacc9d6940 in dart::ThreadPool::Worker::Main (args=187650695972096) at ../../runtime/vm/thread_pool.cc:436
#5  0x0000aaaacc943d20 in dart::ThreadStart (data_ptr=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:134
#6  0x0000ffff9cdbbfc4 in start_thread (arg=0xaaaacc943ca8 <dart::ThreadStart(void*)>) at pthread_create.c:335
#7  0x0000ffff9cc87110 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

Thread 4 (Thread 0xffff9b43f150 (LWP 48763)):
#0  0x0000ffff9cdc230c in __pthread_cond_wait (cond=0xaaaad50e3170, mutex=0xaaaad50e3140) at pthread_cond_wait.c:186
#1  0x0000aaaacc944388 in dart::Monitor::WaitMicros (this=0xaaaad50e3140, micros=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:443
#2  0x0000aaaaccb27684 in dart::MonitorLocker::Wait (this=<optimized out>, millis=0) at ../../runtime/vm/lockers.h:169
#3  dart::SafepointHandler::BlockForSafepoint (this=0xaaaad50f5480, T=0xaaaad57e4b00) at ../../runtime/vm/heap/safepoint.cc:195
#4  0x0000aaaacca90908 in dart::Thread::CheckForSafepoint (this=0xaaaad50e3174) at ../../runtime/vm/thread.h:753
#5  dart::CallSpecializer::ApplyClassIds (this=0xffff9b43c448) at ../../runtime/vm/compiler/call_specializer.cc:178
#6  0x0000aaaacca5630c in dart::CallSiteInliner::TryInlining (this=0xffff9b43ca48, function=..., argument_names=..., call_data=0xffff9b43c828, stricter_heuristic=false) at ../../runtime/vm/compiler/backend/inliner.cc:1192
#7  0x0000aaaacca60650 in dart::CallSiteInliner::InlineStaticCalls (this=0xffff9b43ca48) at ../../runtime/vm/compiler/backend/inliner.cc:1496
#8  0x0000aaaacca5c16c in dart::CallSiteInliner::InlineCalls (this=0xffff9b43ca48) at ../../runtime/vm/compiler/backend/inliner.cc:860
#9  0x0000aaaacca5bd84 in dart::FlowGraphInliner::Inline (this=0xffff9b43cb38) at ../../runtime/vm/compiler/backend/inliner.cc:2358
#10 0x0000aaaacca9b004 in dart::CompilerPass_Inlining::DoBody (this=<optimized out>, state=0xffff9b43d050) at ../../runtime/vm/compiler/compiler_pass.cc:285
#11 0x0000aaaacca9aabc in dart::CompilerPass::Run (this=0xaaaacce0c5c8 <dart::compiler_pass_Inlining>, state=0xffff9b43d050) at ../../runtime/vm/compiler/compiler_pass.cc:178
#12 0x0000aaaacca9ad88 in dart::CompilerPass::RunPipeline (mode=<optimized out>, pass_state=0xffff9b43d050) at ../../runtime/vm/compiler/compiler_pass.cc:224
#13 0x0000aaaaccafa85c in dart::CompileParsedFunctionHelper::Compile (this=0xffff9b43d3c8, pipeline=<optimized out>) at ../../runtime/vm/compiler/jit/compiler.cc:674
#14 0x0000aaaaccafb300 in dart::CompileFunctionHelper (pipeline=0xffff9b43df60, function=..., optimized=<optimized out>, osr_id=<optimized out>) at ../../runtime/vm/compiler/jit/compiler.cc:823
#15 0x0000aaaaccafbfd4 in dart::Compiler::CompileOptimizedFunction (thread=0xaaaad57e4b00, function=..., osr_id=<optimized out>) at ../../runtime/vm/compiler/jit/compiler.cc:1074
#16 0x0000aaaaccafd7b4 in dart::BackgroundCompiler::Run (this=0xaaaad50e0660) at ../../runtime/vm/compiler/jit/compiler.cc:1491
#17 0x0000aaaacc9d6b10 in dart::ThreadPool::Worker::Loop (this=0xaaaad5134460) at ../../runtime/vm/thread_pool.cc:381
#18 0x0000aaaacc9d6940 in dart::ThreadPool::Worker::Main (args=187650695971936) at ../../runtime/vm/thread_pool.cc:436
#19 0x0000aaaacc943d20 in dart::ThreadStart (data_ptr=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:134
#20 0x0000ffff9cdbbfc4 in start_thread (arg=0xaaaacc943ca8 <dart::ThreadStart(void*)>) at pthread_create.c:335
#21 0x0000ffff9cc87110 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

Thread 3 (Thread 0xffff9cbc0150 (LWP 48728)):
#0  0x0000ffff9cc872a4 in __GI_epoll_pwait (epfd=5, events=0xffff9cbbf760, maxevents=16, timeout=-1, set=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#1  0x0000aaaacc67be0c in dart::bin::EventHandlerImplementation::Poll (args=187650695700608) at ../../runtime/bin/eventhandler_linux.cc:392
#2  0x0000aaaacc69af8c in dart::bin::ThreadStart (data_ptr=<optimized out>) at ../../runtime/bin/thread_linux.cc:93
#3  0x0000ffff9cdbbfc4 in start_thread (arg=0xaaaacc69af58 <dart::bin::ThreadStart(void*)>) at pthread_create.c:335
#4  0x0000ffff9cc87110 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

Thread 2 (Thread 0xffff9ce2d010 (LWP 48720)):
#0  0x0000ffff9cdc230c in __pthread_cond_wait (cond=0xaaaad50e34d0, mutex=0xaaaad50e34a0) at pthread_cond_wait.c:186
#1  0x0000aaaacc944388 in dart::Monitor::WaitMicros (this=0xaaaad50e34a0, micros=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:443
#2  0x0000aaaacc88ead4 in dart::MonitorLocker::Wait (this=<optimized out>, millis=0) at ../../runtime/vm/lockers.h:169
#3  dart::KernelCompilationRequest::SendAndWaitForResponse (this=<optimized out>, request_tag=<optimized out>, kernel_port=58097154, script_uri=<optimized out>, platform_kernel=<optimized out>, platform_kernel_size=<optimized out>, source_files_count=<optimized out>, source_files=<optimized out>, incremental_compile=<optimized out>, package_config=0xaaaad525ed58 "file:///b/s/w/ir/.packages", multiroot_filepaths=0x0, multiroot_scheme=0x0, experimental_flags=0xaaaad50ecf60) at ../../runtime/vm/kernel_isolate.cc:690
#4  0x0000aaaacc88e5ec in dart::KernelIsolate::CompileToKernel (script_uri=0xffffce58fc4a "/b/s/w/ir/tests/standalone_2/no_lazy_dispatchers_test.dart", platform_kernel=0xaaaacc07dee0 <kPlatformStrongDill> "\220���", platform_kernel_size=5634720, source_file_count=0, source_files=0x0, incremental_compile=false, package_config=0xaaaad525ed58 "file:///b/s/w/ir/.packages", multiroot_filepaths=0x0, multiroot_scheme=0x0) at ../../runtime/vm/kernel_isolate.cc:829
#5  0x0000aaaaccb627d4 in Dart_CompileToKernel (script_uri=0xffffce58fc4a "/b/s/w/ir/tests/standalone_2/no_lazy_dispatchers_test.dart", platform_kernel=0xaaaacc07dee0 <kPlatformStrongDill> "\220���", platform_kernel_size=5634720, incremental_compile=false, package_config=0xaaaad525ed58 "file:///b/s/w/ir/.packages") at ../../runtime/vm/dart_api_impl.cc:5569
#6  0x0000aaaacc678718 in dart::bin::DFE::CompileScript (this=<optimized out>, script_uri=0xaaaad50e34d4 "\001", package_config=0x2 <error: Cannot access memory at address 0x2>, incremental=<optimized out>) at ../../runtime/bin/dfe.cc:194
#7  dart::bin::DFE::CompileAndReadScript (this=<optimized out>, script_uri=0xaaaad50e34d4 "\001", kernel_buffer=0xffffce58ed40, kernel_buffer_size=0xffffce58ed38, error=<optimized out>, exit_code=<optimized out>, package_config=0x2 <error: Cannot access memory at address 0x2>) at ../../runtime/bin/dfe.cc:206
#8  0x0000aaaacc67537c in dart::bin::IsolateSetupHelper (isolate=0xaaaad5106900, is_main_isolate=true, script_uri=0xffffce58fc4a "/b/s/w/ir/tests/standalone_2/no_lazy_dispatchers_test.dart", package_root=<optimized out>, packages_config=<optimized out>, isolate_run_app_snapshot=false, flags=<optimized out>, error=0xffffce58eed8, exit_code=<optimized out>) at ../../runtime/bin/main.cc:268
#9  0x0000aaaacc674000 in dart::bin::CreateIsolateAndSetupHelper (is_main_isolate=true, script_uri=0xffffce58fc4a "/b/s/w/ir/tests/standalone_2/no_lazy_dispatchers_test.dart", main=<optimized out>, package_root=<optimized out>, packages_config=0xffffce58fc36 "/b/s/w/ir/.packages", flags=<optimized out>, callback_data=<optimized out>, error=0xffffce58eed8, exit_code=0xffffce58eecc) at ../../runtime/bin/main.cc:648
#10 0x0000aaaacc673694 in dart::bin::RunMainIsolate (script_name=0xffffce58fc4a "/b/s/w/ir/tests/standalone_2/no_lazy_dispatchers_test.dart", dart_options=0xffffce58efb8) at ../../runtime/bin/main.cc:825
#11 0x0000aaaacc674868 in dart::bin::main (argc=5, argv=<optimized out>) at ../../runtime/bin/main.cc:1177
#12 0x0000aaaacc675144 in main (argc=-720489260, argv=0x80) at ../../runtime/bin/main.cc:1215

Thread 1 (Thread 0xffff946bf150 (LWP 407)):
#0  0x0000ffff9cbf2528 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x0000ffff9cbf39e0 in __GI_abort () at abort.c:89
#2  0x0000aaaacc67f1b8 in dart::bin::segv_handler (signal=<optimized out>, siginfo=0xffff946bd410, context=<optimized out>) at ../../runtime/bin/platform_linux.cc:35
#3  <signal handler called>
#4  0x0000aaaaccb209e0 in dart::RawObject::IsMarked (this=0x7373616c437361) at ../../runtime/vm/raw_object.h:255
#5  dart::MarkingVisitorBase<true>::MarkObject (this=0xaaaad50fed00, raw_obj=0x7373616c437361) at ../../runtime/vm/heap/marker.cc:397
#6  dart::MarkingVisitorBase<true>::VisitPointers (this=0xaaaad50fed00, first=0xffff97581398, last=0xffff975817b0) at ../../runtime/vm/heap/marker.cc:285
#7  0x0000aaaaccb28af8 in dart::RawObject::VisitPointers (this=<optimized out>, visitor=0xaaaad50fed00) at ../../runtime/vm/raw_object.h:436
#8  dart::Scavenger::VisitObjectPointers (this=0xaaaad50fd008, visitor=0xaaaad50fed00) at ../../runtime/vm/heap/scavenger.cc:903
#9  0x0000aaaaccb1f1dc in dart::GCMarker::IterateRoots (this=0xaaaad51046c0, visitor=0xaaaad50fed00) at ../../runtime/vm/heap/marker.cc:561
#10 0x0000aaaaccb20ba8 in dart::ParallelMarkTask::Run (this=0xaaaad50f37c0) at ../../runtime/vm/heap/marker.cc:655
#11 0x0000aaaacc9d6b10 in dart::ThreadPool::Worker::Loop (this=0xaaaad5134320) at ../../runtime/vm/thread_pool.cc:381
#12 0x0000aaaacc9d6940 in dart::ThreadPool::Worker::Main (args=187650695971616) at ../../runtime/vm/thread_pool.cc:436
#13 0x0000aaaacc943d20 in dart::ThreadStart (data_ptr=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:134
#14 0x0000ffff9cdbbfc4 in start_thread (arg=0xaaaacc943ca8 <dart::ThreadStart(void*)>) at pthread_create.c:335
#15 0x0000ffff9cc87110 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89
```

It crashes in the ParallelMarkerTask which iterates the new-space of the "kernel-isolate". The mutator is waiting on a safepoint on thread 4.

I've looked a little bit and it seems that it hits a header word which is not part of an object.

Maybe this is related to the TLABs.

**Comment by rmacnak-google** [comment]
I've iterated manually through new space and it looks correct. The invalid new space address happens well before the active TLABs (two: mutator and background compiler, both with proper filler objects), and I don't see any corruption between new space start and the new space address being visited during the crash. The previous object is a OneByteString whose header and length field both say it is 3 double-words long, but the scavenger appears to have advanced 4 double-words instead and started to interpret string contents as an object header, then interpreting later string contents as the body of a general instance.

**Comment by stuartmorgan** [comment]
Is https://github.com/flutter/flutter/issues/35651 likely to be the same issue as this, or not? The crashing stack looks pretty much the same, but it looks (naively; I'm not familiar with the Dart VM internals) like it might just be a stack that's likely to happen when there's some kind of memory corruption.

**Comment by rmacnak-google** [comment]
No, I think it is a different issue.

**Comment by mkustermann** [comment]
Assumed stale.
