### ISSUE TITLE
dev compiler fails on new test language_2/regress_36084_test

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#36293]
The following tests began failing (needs approval):

dartdevc-checked-linux-release-chrome:language_2/regress_36084_test is new and failed (RuntimeError, expected Pass)
dartdevk-checked-linux-release-chrome:language_2/regress_36084_test is new and failed (RuntimeError, expected Pass)

unapproved_new_test_failures__logs:

/=====================================================================================================================\
| dartdevc-checked-linux-release-chrome:language_2/regress_36084_test is new and failed (RuntimeError, expected Pass) |
\=====================================================================================================================/

--- Command "dartdevc" (took 83ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartdevc --library-root /b/s/w/ir/cache/builder/sdk/tests/language_2 --ignore-unrecognized-flags --no-summarize --no-source-map -o /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dartdevc-checked-sdk/tests_language_2_regress_36084_test/regress_36084_test.js /b/s/w/ir/cache/builder/sdk/tests/language_2/regress_36084_test.dart -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/async_helper.sum=async_helper -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/collection.sum=collection -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/expect.sum=expect -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/js.sum=js -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/matcher.sum=matcher -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/meta.sum=meta -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/path.sum=path -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/stack_trace.sum=stack_trace -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/unittest.sum=unittest (working directory: /b/s/w/ir/cache/builder/sdk/tests/language_2)

exit code:
0

--- Command "chrome" (took 745ms):
/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart tools/testing/dart/launch_browser.dart chrome http://127.0.0.1:44024/root_build/generated_tests/dartdevc-chrome-checked-sdk/tests_language_2_regress_36084_test/test.html?crossOriginPort=44653

Runtime error:
Error: NoSuchMethodError: method not found: 'foo'
Receiver: Instance of 'B'
Arguments: [1, 2, 3]
Receiver: Instance of 'B'
Arguments: [1, 2, 3]
    at Object.dart.throw (http://127.0.0.1:44024/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4547:11)
    at Object.dart.defaultNoSuchMethod (http://127.0.0.1:44024/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4979:15)
    at regress_36084_test.B.new.noSuchMethod (http://127.0.0.1:44024/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:5079:19)
    at Object.dart.noSuchMethod (http://127.0.0.1:44024/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4975:30)
    at callNSM (http://127.0.0.1:44024/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4707:19)
    at Object.dart._checkAndCall (http://127.0.0.1:44024/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4743:12)
    at Object.dart.callMethod (http://127.0.0.1:44024/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4787:17)
    at Object.dart.dsend (http://127.0.0.1:44024/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4790:17)
    at Object.regress_36084_test.main (http://127.0.0.1:44024/root_dart/out/ReleaseX64/generated_compilations/dartdevc-checked-sdk/tests_language_2_regress_36084_test/regress_36084_test.js:71:36)
    at testMainWrapper (http://127.0.0.1:44024/root_build/generated_tests/dartdevc-chrome-checked-sdk/tests_language_2_regress_36084_test/test.html?crossOriginPort=44653:104:56)

exit code:
0

--- To debug locally, run:
/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/cache/builder/sdk/tools/testing/dart/http_server.dart -p 44024 -c 44653 --network 127.0.0.1 --build-directory=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/cache/builder/sdk/.packages

--- Re-run this test:
python tools/test.py -n dartdevc-checked-linux-release-chrome language_2/regress_36084_test

/=====================================================================================================================\
| dartdevk-checked-linux-release-chrome:language_2/regress_36084_test is new and failed (RuntimeError, expected Pass) |
\=====================================================================================================================/

--- Command "dartdevk" (took 64ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartdevc --kernel --ignore-unrecognized-flags --no-summarize --no-source-map -o /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dartdevk-checked-sdk/tests_language_2_regress_36084_test/regress_36084_test.js /b/s/w/ir/cache/builder/sdk/tests/language_2/regress_36084_test.dart -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/async_helper.sum=async_helper -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/collection.sum=collection -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/expect.sum=expect -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/js.sum=js -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/matcher.sum=matcher -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/meta.sum=meta -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/path.sum=path -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/stack_trace.sum=stack_trace -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg/unittest.sum=unittest (working directory: /b/s/w/ir/cache/builder/sdk/tests/language_2)

exit code:
0

--- Command "chrome" (took 195ms):
/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart tools/testing/dart/launch_browser.dart chrome http://127.0.0.1:40450/root_build/generated_tests/dartdevk-chrome-checked-sdk/tests_language_2_regress_36084_test/test.html?crossOriginPort=33830

Runtime error:
Error: NoSuchMethodError: method not found: 'foo'
Receiver: Instance of 'B'
Arguments: [1, 2, 3]
Receiver: Instance of 'B'
Arguments: [1, 2, 3]
    at Object.dart.throw (http://127.0.0.1:40450/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:3861:11)
    at Object.dart.defaultNoSuchMethod (http://127.0.0.1:40450/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:4293:15)
    at regress_36084_test.B.new.noSuchMethod (http://127.0.0.1:40450/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:5050:19)
    at Object.dart.noSuchMethod (http://127.0.0.1:40450/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:4289:30)
    at callNSM (http://127.0.0.1:40450/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:4021:19)
    at Object.dart._checkAndCall (http://127.0.0.1:40450/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:4057:12)
    at Object.dart.callMethod (http://127.0.0.1:40450/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:4101:17)
    at Object.dart.dsend (http://127.0.0.1:40450/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:4104:17)
    at Object.regress_36084_test.main (http://127.0.0.1:40450/root_dart/out/ReleaseX64/generated_compilations/dartdevk-checked-sdk/tests_language_2_regress_36084_test/regress_36084_test.js:74:36)
    at testMainWrapper (http://127.0.0.1:40450/root_build/generated_tests/dartdevk-chrome-checked-sdk/tests_language_2_regress_36084_test/test.html?crossOriginPort=33830:104:56)

exit code:
0

--- To debug locally, run:
/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/cache/builder/sdk/tools/testing/dart/http_server.dart -p 40450 -c 33830 --network 127.0.0.1 --build-directory=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/cache/builder/sdk/.packages

--- Re-run this test:
python tools/test.py -n dartdevk-checked-linux-release-chrome language_2/regress_36084_test

**Comment by jmesserly** [comment]
The VM issue: https://github.com/dart-lang/sdk/issues/36084

DDC had a (similar?) bug, it called nSM on the original object, not on the callable class. I'm testing https://dart-review.googlesource.com/c/sdk/+/97701 now.
