### ISSUE TITLE
Bogus conflicting override error

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#36358]
```
class A {
    dynamic foo() => 'A';
    dynamic get bar => () => 'A';
}

class B extends A {
    dynamic get foo => () => 'B';
    dynamic bar() => 'B';
}

main() {
    var a = new A();
    var b = new B();
    print(a.foo());
    print(b.foo());
    print(a.bar());
    print(b.bar());
}
```

```
a.dart:8:13: Error: Can't declare a member that conflicts with an inherited one.
    dynamic bar() => 'B';
            ^^^
a.dart:3:17: Context: This is the inherited member.
    dynamic get bar => () => 'A';
                ^^^
a.dart:7:17: Error: Can't declare a member that conflicts with an inherited one.
    dynamic get foo => () => 'B';
                ^^^
a.dart:2:13: Context: This is the inherited member.
    dynamic foo() => 'A';
            ^^^
```

Notice that A and B have the same interface.

**Comment by mraleph** [comment]
This was never possible in Dart - you could never override a method with a getter (field) or another way around. 

For fun you can check Dart 1 SDK:

```console
$ /Users/vegorov/homebrew/opt/dart@1/libexec/bin/dart --version
Dart VM version: 1.24.3 (Wed Dec 13 23:26:59 2017) on "macos_x64"

$ /Users/vegorov/homebrew/opt/dart@1/libexec/bin/dart /tmp/test.dart
Unhandled exception:
'file:///tmp/test.dart': error: line 7 pos 5: getter 'foo' of class 'B' conflicts with method 'foo' of super class 'A'
    dynamic get foo => () => 'B';
    ^

#0      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by rmacnak-google** [comment]
The whole point of the language having getters and setters instead of direct field access is to prevent these sorts of implementation details from being part of the interface. Whether a getter is implemented by storage or code is not part of the interface; whether a method is implemented by a regular method or a closure-typed getter is not part of the interface.
