### ISSUE TITLE
Hard to catch exception from writing to a closed socket

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#36417]
* Dart SDK Version (`dart --version`)
Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "linux_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux

This program:
```dart
import 'dart:io';
import 'dart:convert';
import 'dart:async';
import 'dart:isolate';

client(port) async {
  Socket s = await Socket.connect('localhost', port);
  s.add(utf8.encode('hej'));
  s.listen((d) {
    print('client listening');
  });
  await Future.delayed(Duration(seconds: 1));
  await s.destroy();
}

spawnClient(port) async {
  await Isolate.spawn(client, port);
}

main() async {
  ServerSocket ss = await ServerSocket.bind('localhost', 0);
  spawnClient(ss.port);
  Socket s = await ss.first;
  s.listen(
      (d) async {
        print("server listening");
      },
      onDone: () => print('done'),
      onError: (e) {
        print("Listen caught $e");
      });
  s.done.catchError((e) {
    print("s.done failed $e");
  });
  await Future.delayed(Duration(seconds: 2));
  print("Adding");
  s.add(utf8.encode('msg'));
}
```
prints
```
server listening
listening done
Adding
s.done failed SocketException: OS Error: Broken pipe, errno = 32, address = localhost, port = 34737
```

If we try to use addStream the exception goes unhandled
```dart
import 'dart:io';
import 'dart:convert';
import 'dart:async';
import 'dart:isolate';

client(port) async {
  Socket s = await Socket.connect('localhost', port);
  s.add(utf8.encode('hej'));
  s.listen((d) {
    print('client listening');
  });
  await Future.delayed(Duration(seconds: 1));
  await s.destroy();
}

spawnClient(port) async {
  await Isolate.spawn(client, port);
}

main() async {
  ServerSocket ss = await ServerSocket.bind('localhost', 0);
  spawnClient(ss.port);
  Socket s = await ss.first;
  s.listen(
      (d) async {
        print("server listening");
      },
      onDone: () => print('listening done'),
      onError: (e) {
        print("Listen caught $e");
      });
  s.done.catchError((e) {
    print("s.done failed $e");
  });
  await Future.delayed(Duration(seconds: 2));

  StreamController<List<int>> sc;
  sc = StreamController<List<int>>(onListen: () {
    print("onListen");
    sc.add('foo'.codeUnits);
  }, onPause: () {
    print("paused");
  }, onCancel: () {
    print("cancelled");
  });

  await s.addStream(sc.stream);
}
```

prints
```
server listening
listening done
onListen
Unhandled exception:
SocketException: OS Error: Broken pipe, errno = 32, address = localhost, port = 44485
#0      main (file:///usr/local/google/home/sigurdm/projects/blah/bin/socket_sample.dart:47:3)
<asynchronous suspension>
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Process finished with exit code 255
```

**Comment by sigurdm** [comment]
cc: @sortie @lrhn
