### ISSUE TITLE
NoSuchMethodError: The getter 'templateNames' was called on null.

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#36438]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-191.6183.63`
- `2.2.1-edge.725c070632c4910a8ef266e2a39708d2dbddd47d`
- `WS-191.6183.63, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.725c070632c4910a8ef266e2a39708d2dbddd47d, server version 1.25.0, error: Captured exception
NoSuchMethodError: The getter 'templateNames' was called on null.
Receiver: null
Tried calling: templateNames
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _File._readFileDeclarationsFromBytes (package:analyzer/src/services/available_declarations.dart:1435:43)
#2      _File.refresh (package:analyzer/src/services/available_declarations.dart:1055:7)
#3      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:600:14)
#4      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:513:18)
#5      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:208:13)
<asynchronous suspension>
#6      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#7      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#8      new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#9      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#10     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#11     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#17     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#18     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#19     main (file:///Users/devoncarew/projects/dart-lang/sdk/pkg/analysis_server/bin/server.dart:12:11)
#20     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#21     main (file:///Users/devoncarew/projects/dart-lang/sdk/pkg/analysis_server/bin/server.dart:10:10)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/t6/ghq95c9n0xx7qb0kmk21bm6w003j4x/T/report1.txt.

**Comment by devoncarew** [comment]
dupe of https://github.com/dart-lang/sdk/issues/36436
