### ISSUE TITLE
Exception with templateNames

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#36436]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 192.SNAPSHOT`
- `2.2.1-edge.ffee99d79b1c3d57c24c6b06384d7e14208302af`
- `IC-192.SNAPSHOT, JRE 1.8.0_112-b16x64 Oracle Corporation, OS Mac OS X(x86_64) v10.14.3, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.ffee99d79b1c3d57c24c6b06384d7e14208302af, server version 1.25.0, error: Captured exception
NoSuchMethodError: The getter 'templateNames' was called on null.
Receiver: null
Tried calling: templateNames
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      _File._readFileDeclarationsFromBytes (package:analyzer/src/services/available_declarations.dart:1435:43)
#2      _File.refresh (package:analyzer/src/services/available_declarations.dart:1055:7)
#3      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:600:14)
#4      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:635:16)
#5      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:507:7)
#6      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:208:13)
<asynchronous suspension>
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#8      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#9      new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#10     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#11     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#12     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#18     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#19     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#20     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:12:11)
#21     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#22     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:10:10)
#23     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/cp/_32g44l548q8d0bfj4_l9s3m003ky_/T/report.txt.

**Comment by devoncarew** [comment]
I'm seeing this as well.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/98450
