### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by voiddog** [dart-lang/sdk#36455]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.6183.87`
- `2.2.1-edge.2fb6cd9f5ff78fb347795f383a748a1e37d23275`
- `IU-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1680x1050, 2560x1440  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.2fb6cd9f5ff78fb347795f383a748a1e37d23275, server version 1.25.0, error: Captured exception
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      _File._buildFileDeclarations (package:analyzer/src/services/available_declarations.dart:1244:39)
#2      _File.refresh (package:analyzer/src/services/available_declarations.dart:1028:7)
#3      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:629:12)
#4      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:494:7)
#5      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:200:13)
<asynchronous suspension>
#6      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#7      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#8      new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#9      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#10     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#11     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:511:21)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:594:12)
#17     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:509:7)
#18     Driver.start (package:analysis_server/src/server/driver.dart:412:7)
#19     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#20     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#21     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#22     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/dp/jcf93qn12jsbbvbn6z1kxbfm0000gn/T/report.txt.

**Comment by voiddog** [comment]
I get this error by adding the code below:
```dart
typedef FetchEncodeData = Future<Uint8List> function();
```
