### ISSUE TITLE
 FATAL error: Failed to handle request: {id: 3,

### ISSUE THREAD

**Issue by vranacse** [dart-lang/sdk#36451]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec, server version 1.24.0, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\AndroidStudioProjects\flutter_app], excluded: [D:\AndroidStudioProjects\flutter_app\.idea, D:\AndroidStudioProjects\flutter_app\.dart_tool, D:\AndroidStudioProjects\flutter_app\.idea, D:\AndroidStudioProjects\flutter_app\.pub, D:\AndroidStudioProjects\flutter_app\build]}, clientRequestTime: 1554269129980}
NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      _DartNavigationComputerVisitor._addUriDirectiveRegion (package:analysis_server/src/domains/analysis/navigation_dart.dart:361:47)
#2      _DartNavigationComputerVisitor.visitPartDirective (package:analysis_server/src/domains/analysis/navigation_dart.dart:232:5)
#3      PartDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:8299:49)
#4      _DartNavigationComputerVisitor.visitCompilationUnit (package:analysis_server/src/domains/analysis/navigation_dart.dart:149:12)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2170:49)
#6      computeDartNavigation (package:analysis_server/src/domains/analysis/navigation_dart.dart:28:10)
#7      ServerContextManagerCallbacks._computeNavigationParams (package:analysis_server/src/analysis_server.dart:1023:5)
#8      ServerContextManagerCallbacks.addAnalysisDriver.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:832:19)
#9      new Future.<anonymous closure> (dart:async/future.dart:176:37)
#10     _rootRun (dart:async/zone.dart:1120:38)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     Timer._createTimer.<anonymous closure> (dart:async/runtime/lib/timer_patch.dart:21:15)
#18     _Timer._runTimers (dart:isolate/runtime/lib/timer_impl.dart:382:19)
#19     _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:416:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\info\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Thanks for reporting this issue!  This was previously reported in https://github.com/dart-lang/sdk/issues/36182; it  should be fixed now in a recent release  of Dart.
