### ISSUE TITLE
runtime errors in new control_flow_collections tests

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36466]
control_flow_collections/await_for_null_test
control_flow_collections/for_await_test
has runtime errors.

```
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --no-background-compilation --enable-experiment=control-flow-collections,spread-collections,constant-update-2018 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/language_2/control_flow_collections/await_for_null_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
asyncExpectThrows<NoSuchMethodError>(): Did not throw.
#0      asyncExpectThrows.<anonymous closure> (package:async_helper/async_helper.dart:127:5)
#1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#5      Future._complete (dart:async/future_impl.dart:473:7)
#6      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#7      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#8      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#9      main.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/language_2/control_flow_collections/await_for_null_test.dart)
<asynchronous suspension>
#10     asyncExpectThrows (package:async_helper/async_helper.dart:120:17)
#11     main.<anonymous closure> (file:///b/s/w/ir/tests/language_2/control_flow_collections/await_for_null_test.dart:14:5)
<asynchronous suspension>
#12     asyncTest (package:async_helper/async_helper.dart:90:11)
#13     main (file:///b/s/w/ir/tests/language_2/control_flow_collections/await_for_null_test.dart:11:3)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

```
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --no-background-compilation --enable-experiment=control-flow-collections,constant-update-2018 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/language_2/control_flow_collections/for_await_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
NoSuchMethodError: Class 'int' has no instance getter 'keys'.
Receiver: 3
Tried calling: keys
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      Expect.mapEquals (package:expect/expect.dart:334:32)
#2      testMap (file:///b/s/w/ir/tests/language_2/control_flow_collections/for_await_test.dart:60:10)
<asynchronous suspension>
#3      main.<anonymous closure> (file:///b/s/w/ir/tests/language_2/control_flow_collections/for_await_test.dart:17:11)
<asynchronous suspension>
#4      asyncTest (package:async_helper/async_helper.dart:90:11)
#5      main (file:///b/s/w/ir/tests/language_2/control_flow_collections/for_await_test.dart:15:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by aartbik** [comment]
Crashes for 

```dart
Future<void> testMap() async {
  // Await in for-in body value.
  Expect.mapEquals(map,
      {for (var i in [1, 2, 3]) i: await Future.value(i)});
}

```

**Comment by aartbik** [comment]
This is the incoming kernel file. The asyn temporary aliasing seems suspect:

```
          :async_temporary_0 = [@vm.inferred-type.metadata=dart.collection::_InternalLinkedHashMap?] for::map;
          final core::Map<dynamic, dynamic> #t2 = <dynamic, dynamic>{};
          for (core::int i in <core::int>[1, 2, 3]) {
            :async_temporary_0 = i;
            [yield] let dynamic #t3 = asy2::_awaitHelper([@vm.inferred-type.metadata=dart.async::_Future] asy2::Future::value<core::int>(i), :async_op_then, :async_op_error, :async_op) in null;
            [@vm.direct-call.metadata=dart.collection::__InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin::[]=] [@vm.inferred-type.metadata=!? (skip check)] [@vm.call-site-attributes.metadata=receiverType:dart.core::Map<dynamic, dynamic>] #t2.{core::Map::[]=}(:async_temporary_0, :result);
          }
          exp::Expect::mapEquals(:async_temporary_0, block {} =>#t2);

```

**Comment by kmillikin** [comment]
That looks like a bug in the VM-specific async transformation.  I'll fix it.

**Comment by kmillikin** [comment]
[CL 98664](https://dart-review.googlesource.com/c/sdk/+/98664) fixes `for_await_test` at the cost of sometimes using more temporary variables than necessary in the VM's async transformation.  Eventually this should be fixed but that needs a different way to know about liveness.

`await_for_null_test` doesn't seem to have anything to do with control-flow collections.  A similar test with an `await for` statement fails in the same way, so it's not the collection that is the problem.  This seems like a VM issue.

**Comment by kmillikin** [comment]
This test fails in the same way as `await_for_null_test`:

```dart
import 'package:async_helper/async_helper.dart';

void main() {
  asyncTest(() async {
    // Null stream.
    Stream<int> nullStream = null;
    asyncExpectThrows<NoSuchMethodError>(() async {
        await for (var i in nullStream) 1;
    });
  });
}
```

**Comment by dgrove** [comment]
Does this bug need to be split, @a-siva ?

**Comment by a-siva** [comment]
I have created https://github.com/dart-lang/sdk/issues/36483 to track the second issue with await_for_null_test. Since this is an already existing issue and not related to control-flow collections I am not tagging that issue with the 2.3 milestone.

@kmillikin once your CL lands you can close this issue.
