### ISSUE TITLE
Cannot add to an unmodifiable list in _extractDartdocInfoFromUnit

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#36474]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 192.SNAPSHOT`
- `2.2.1-edge.ffee99d79b1c3d57c24c6b06384d7e14208302af`
- `IC-192.SNAPSHOT, JRE 1.8.0_112-b16x64 Oracle Corporation, OS Mac OS X(x86_64) v10.14.3, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.ffee99d79b1c3d57c24c6b06384d7e14208302af, server version 1.25.0, error: Captured exception
Unsupported operation: Cannot add to an unmodifiable list
#0      UnmodifiableListBase.add (dart:_internal/list.dart:114:5)
#1      _File._extractDartdocInfoFromUnit (package:analyzer/src/services/available_declarations.dart:1376:21)
#2      _File.refresh (package:analyzer/src/services/available_declarations.dart:1050:7)
#3      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:643:12)
#4      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:507:7)
#5      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:208:13)
<asynchronous suspension>
#6      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#7      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#8      new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#9      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#10     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#11     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#17     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#18     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#19     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:12:11)
#20     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#21     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:10:10)
#22     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/cp/_32g44l548q8d0bfj4_l9s3m003ky_/T/report9.txt.

**Comment by scheglov** [comment]
Ah, I think I know.

1. We need to create copies of lists from IDL, because by doing this we avoid referencing them, and keeping IDL and ByteBuffer in memory (I'd like to do this for available declarations).

2. We need to clear all `_File` data during refresh. I think I might have missed this at least partially, so you did not do it for templates.

```dart
    templateNames = idlFile.directiveInfo.templateNames.toList();
    templateValues = idlFile.directiveInfo.templateValues.toList();
```

**Comment by bwilkerson** [comment]
Looks like your latest CL addresses this issue, so I've unassigned myself.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/98701 will fix this.
