### ISSUE TITLE
Compiler crashed

### ISSUE THREAD

**Issue by dev-mush** [dart-lang/sdk#36470]
- os: container google/dart:2.1.0 on google cloud build
- dart version: google/dart:2.1.0 on google cloud build

```
The compiler crashed: Assertion failure: Cannot find value BoxLocal(_box_0) in (SyntheticLocal(result)) for j:constructor(AngularLocationService.).
#0 failedAt (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/diagnostics/invariant.dart:49:3)
#1 LocalsHandler.readLocal (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/locals_handler.dart:327:11)
#2 KernelSsaGraphBuilder.buildConstructor.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:607:44)
#3 KernelSsaGraphBuilder.inlinedFrom.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:667:21)
#4 CompilerDiagnosticReporter.withCurrentElement (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:755:15)
#5 KernelSsaGraphBuilder.inlinedFrom (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:665:14)
#6 KernelSsaGraphBuilder.buildConstructor (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:584:7)
#7 KernelSsaGraphBuilder._visitInlinedFunction (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:5434:9)
#8 KernelSsaGraphBuilder._doInline (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:5424:5)
#9 KernelSsaGraphBuilder._tryInlineMethod.doInlining.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:5119:11)
#10 KernelSsaGraphBuilder.inlinedFrom.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:667:21)
#11 CompilerDiagnosticReporter.withCurrentElement (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:755:15)
#12 KernelSsaGraphBuilder.inlinedFrom (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:665:14)
#13 KernelSsaGraphBuilder._tryInlineMethod.doInlining (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:5115:7)
#14 KernelSsaGraphBuilder._tryInlineMethod (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:5126:17)
#15 KernelSsaGraphBuilder._pushStaticInvocation (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:4129:9)
#16 KernelSsaGraphBuilder.visitConstructorInvocation (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:4655:5)
#17 ConstructorInvocation.accept (package:kernel/ast.dart:2985:36)
#18 KernelSsaGraphBuilder.visitPropertySet (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:2972:16)
#19 PropertySet.accept (package:kernel/ast.dart:2357:36)
#20 KernelSsaGraphBuilder.visitConditionalExpression.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:2625:25)
#21 SsaBranchBuilder.buildBranch (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/ssa_branch_builder.dart:91:16)
#22 SsaBranchBuilder._handleDiamondBranch (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/ssa_branch_builder.dart:202:9)
#23 SsaBranchBuilder.handleConditional (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/ssa_branch_builder.dart:122:5)
#24 KernelSsaGraphBuilder.visitConditionalExpression (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:2624:14)
#25 ConditionalExpression.accept (package:kernel/ast.dart:3118:36)
#26 KernelSsaGraphBuilder.visitLet (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:3093:15)
#27 Let.accept (package:kernel/ast.dart:3566:36)
#28 KernelSsaGraphBuilder.visitReturnStatement (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:1473:23)
#29 ReturnStatement.accept (package:kernel/ast.dart:4100:35)
#30 KernelSsaGraphBuilder._visitInlinedFunction (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:5446:30)
#31 KernelSsaGraphBuilder._doInline (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:5424:5)
#32 KernelSsaGraphBuilder._tryInlineMethod.doInlining.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:5119:11)
#33 KernelSsaGraphBuilder.inlinedFrom.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:667:21)
#34 CompilerDiagnosticReporter.withCurrentElement (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:755:15)
#35 KernelSsaGraphBuilder.inlinedFrom (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:665:14)
#36 KernelSsaGraphBuilder._tryInlineMethod.doInlining (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:5115:7)
#37 KernelSsaGraphBuilder._tryInlineMethod (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:5126:17)
#38 KernelSsaGraphBuilder._pushDynamicInvocation (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:4200:11)
#39 KernelSsaGraphBuilder.visitMethodInvocation (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:4423:5)
#40 MethodInvocation.accept (package:kernel/ast.dart:2824:36)
#41 KernelSsaGraphBuilder.visitReturnStatement (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:1473:23)
#42 ReturnStatement.accept (package:kernel/ast.dart:4100:35)
#43 KernelSsaGraphBuilder.visitBlock (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:1406:17)
#44 Block.accept (package:kernel/ast.dart:3679:35)
#45 KernelSsaGraphBuilder.visitIfStatement.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:2035:36)
#46 SsaBranchBuilder.buildBranch (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/ssa_branch_builder.dart:91:16)
#47 SsaBranchBuilder._handleDiamondBranch (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/ssa_branch_builder.dart:202:9)
#48 SsaBranchBuilder.handleIf (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/ssa_branch_builder.dart:116:5)
#49 KernelSsaGraphBuilder.handleIf (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:2048:19)
#50 KernelSsaGraphBuilder.visitIfStatement (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:2033:5)
#51 IfStatement.accept (package:kernel/ast.dart:4067:35)
#52 KernelSsaGraphBuilder.visitBlock (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:1406:17)
#53 Block.accept (package:kernel/ast.dart:3679:35)
#54 KernelSsaGraphBuilder.buildFunctionNode (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:1029:23)
#55 KernelSsaGraphBuilder.build.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:205:15)
#56 CompilerDiagnosticReporter.withCurrentElement (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:755:15)
#57 KernelSsaGraphBuilder.build (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:190:21)
#58 KernelSsaBuilder.build.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/js_model/js_strategy.dart:1168:22)
#59 CompilerTask.measure (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/common/tasks.dart:63:51)
#60 KernelSsaBuilder.build (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/js_model/js_strategy.dart:1155:17)
#61 SsaBuilderTask.build (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/ssa.dart:96:21)
#62 SsaFunctionCompiler.compile (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/ssa/ssa.dart:44:29)
#63 JavaScriptBackend.codegen (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/js_backend/backend.dart:692:26)
#64 KernelCodegenWorkItem.run (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/js_model/js_strategy.dart:1138:21)
#65 Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:434:70)
#66 CompilerTask.measureSubtask (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#67 Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:434:32)
#68 CompilerTask.measureSubtask (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#69 Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:432:28)
#70 CompilerDiagnosticReporter.withCurrentElement (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:755:15)
#71 Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:430:18)
#72 CodegenEnqueuer._forEach (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/js_backend/enqueuer.dart:240:12)
#73 CodegenEnqueuer.forEach (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/js_backend/enqueuer.dart:255:5)
#74 Compiler.emptyQueue.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:426:16)
#75 CompilerTask.measureSubtask (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#76 Compiler.emptyQueue (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:425:14)
#77 Compiler.processQueue.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:451:7)
#78 CompilerTask.measureSubtask (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#79 Compiler.processQueue (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:444:14)
#80 Compiler.generateJavaScriptCode (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:370:5)
#81 Compiler.compileLoadedLibraries.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:395:9)
#82 CompilerTask.measureSubtask (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#83 Compiler.compileLoadedLibraries (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:389:14)
#84 Compiler.runInternal (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:276:5)
<asynchronous suspension>
#85 Compiler.run.<anonymous closure>.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:216:38)
#86 new Future.sync (dart:async/future.dart:224:31)
#87 Compiler.run.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:216:20)
#88 CompilerTask.measureSubtask (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#89 Compiler.run (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/compiler.dart:213:41)
#90 CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///tmp/tmpqIBfjJ/dart-2.1.0/dart/pkg/compiler/lib/src/apiimpl.dart:148:22)
#91 _RootZone.runUnary (dart:async/zone.dart:1379:54)
#92 _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#93 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#94 Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#95 Future._completeWithValue (dart:async/future_impl.dart:486:5)
#96 Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#97 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#98 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#99 _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#100 _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by sigmundch** [comment]
Thanks for filing the issue!

To help us narrow down the cause, Is the source code used to produce this code available publically? Could you provide us with a small example that reproduces this issue?

Thanks!
