### ISSUE TITLE
runtime error language_2/control_flow_collections/await_for_null_test.dart

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36483]
```
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --no-background-compilation --enable-experiment=control-flow-collections,spread-collections,constant-update-2018 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/language_2/control_flow_collections/await_for_null_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
asyncExpectThrows<NoSuchMethodError>(): Did not throw.
#0      asyncExpectThrows.<anonymous closure> (package:async_helper/async_helper.dart:127:5)
#1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#5      Future._complete (dart:async/future_impl.dart:473:7)
#6      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#7      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#8      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#9      main.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/language_2/control_flow_collections/await_for_null_test.dart)
<asynchronous suspension>
#10     asyncExpectThrows (package:async_helper/async_helper.dart:120:17)
#11     main.<anonymous closure> (file:///b/s/w/ir/tests/language_2/control_flow_collections/await_for_null_test.dart:14:5)
<asynchronous suspension>
#12     asyncTest (package:async_helper/async_helper.dart:90:11)
#13     main (file:///b/s/w/ir/tests/language_2/control_flow_collections/await_for_null_test.dart:11:3)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

A simpler test that reproduces the problem

```
import 'package:async_helper/async_helper.dart';

void main() {
  asyncTest(() async {
    // Null stream.
    Stream<int> nullStream = null;
    asyncExpectThrows<NoSuchMethodError>(() async {
        await for (var i in nullStream) 1;
    });
  });
}
```

**Comment by aartbik** [comment]
The parameter has since been changed to "Error" (from "NoSuchMethodError") and the tests pass, so I am assuming this issue is fixed and closed.

unittest-suite-wait-for-done
unittest-suite-success
