### ISSUE TITLE
Crash after recent update of flutter after a dart roll

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#36495]
I updated Flutter, and the analyzer crashed, which I already filed (#36494).  Then, after about 5 minutes it crashed again, with a different stack.  This is the second crash.

## Version information

- `IDEA IC-191.6183.87`
- `2.2.1-edge.896f1c4bb94a390c2969953626980d9de320cd84`
- `IC-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Linux(amd64) v4.19.20-1rodete1-amd64, screens 3840x2160, 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.896f1c4bb94a390c2969953626980d9de320cd84, server version 1.25.0, FATAL error: Bad state: Attempt to modify immutable list
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:579:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

# report.txt

```
1554479682649 => {"id":"34","method":"analysis.updateContent","params":{"files":{"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart":{"type":"add","conte
1554479682650 <= {"id":"34","result":{}}
1554479682650 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1554479682660 => {"id":"35","method":"edit.getAssists","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","offset":699,"length":0},"cli
1554479682682 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","errors":[]}}
1554479682683 <= {"id":"35","result":{"assists":[{"message":"Convert to block documentation comment","edits":[{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/foc
1554479682686 <= {"event":"analysis.highlights","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","regions":[{"type":"DIRECTIVE","offs
1554479682689 <= {"event":"analysis.navigation","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","regions":[{"offset":173,"length":12
1554479682689 <= {"event":"analysis.closingLabels","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","labels":[]}}
1554479682690 <= {"event":"analysis.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","kind":"LIBRARY","outline":{"element":{
1554479682690 <= {"event":"analysis.overrides","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","overrides":[{"offset":17716,"length"
1554479682829 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":858,"uri":"package:flutter/src/widgets/focus_manager.dart","items":[{"label":"FocusNode","element":{"kin
1554479682850 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1554479683008 <= {"event":"analysis.implemented","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","classes":[{"offset":5574,"length":
1554479683330 => {"id":"36","method":"analysis.updateContent","params":{"files":{"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart":{"type":"add","conte
1554479683330 => {"id":"37","method":"completion.getSuggestions","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","offset":701},"clie
1554479683332 <= {"id":"36","result":{}}
1554479683333 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1554479683371 <= {"id":"37","result":{"id":"3"}}
1554479683372 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","errors":[]}}
1554479683374 <= {"event":"completion.results","params":{"id":"3","replacementOffset":701,"replacementLength":0,"results":[],"isLast":true,"includedSuggestionSets":[{"id":904,"relevance":5},{"id":966,
1554479683377 <= {"event":"analysis.highlights","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","regions":[{"type":"DIRECTIVE","offs
1554479683380 <= {"event":"analysis.navigation","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","regions":[{"offset":173,"length":12
1554479683380 <= {"event":"analysis.closingLabels","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","labels":[]}}
1554479683381 <= {"event":"analysis.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","kind":"LIBRARY","outline":{"element":{
1554479683381 <= {"event":"analysis.overrides","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","overrides":[{"offset":17718,"length"
1554479683597 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Bad state: Attempt to modify immutable list\n#0      _FbList.length= (package:analyzer/s
1554479683597 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Bad state: Attempt to modify immutable list\n#0      _FbList.length= (package:analyzer/s
1554479683597 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Bad state: Attempt to modify immutable list\n#0      Driver._captureExceptions.errorFunc
1554479683597 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Bad state: Attempt to modify immutable list\n#0      Driver._captureExceptions.errorFunc
```

**Comment by gspencergoog** [comment]
Closing in favor of consolidating with related crashes: https://github.com/dart-lang/sdk/issues/36496
