### ISSUE TITLE
Crashed when updating Flutter after a Dart roll.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#36494]
Analyzer Feedback from IntelliJ

Crashed when updating Flutter after a dart roll.

## Version information

- `IDEA IC-191.6183.87`
- `2.2.1-edge.896f1c4bb94a390c2969953626980d9de320cd84`
- `IC-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Linux(amd64) v4.19.20-1rodete1-amd64, screens 3840x2160, 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.75b2f9f919e5728902aff39a09223d1cc9402585, server version 1.25.0, error: Failed to handle completion domain request: {id: 2, method: completion.setSubscriptions, params: {subscriptions: [AVAILABLE_SUGGESTION_SETS]}, clientRequestTime: 1554393282501}
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<AvailableSuggestion>(Closure: (Declaration) => AvailableSuggestion)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:78:30)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#4      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:82:8)
#5      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:470:11)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#13     _rootRun (dart:async/zone.dart:1120:38)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## report.txt:

```
1554479405305 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3715]}}
1554479405305 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3716]}}
1554479405305 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3717]}}
1554479405306 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3718]}}
1554479405306 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3719]}}
1554479405306 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3720]}}
1554479405308 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3721]}}
1554479405308 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3722]}}
1554479405309 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3723]}}
1554479405309 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3724]}}
1554479405309 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[1883]}}
1554479405310 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3725]}}
1554479405310 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3726]}}
1554479405310 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3727]}}
1554479405311 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3728]}}
1554479405312 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3729]}}
1554479405313 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3730]}}
1554479405313 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3731]}}
1554479405313 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3732]}}
1554479405314 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3733]}}
1554479405314 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[3734]}}
1554479405336 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/material/stepper.dart","errors":[]}}
1554479405346 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/material/flexible_space_bar.dart","errors":[]}}
1554479405361 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/material/paginated_data_table.dart","errors":[]}}
1554479405370 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/material/color_scheme.dart","errors":[]}}
1554479405422 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/material/chip.dart","errors":[]}}
1554479405464 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/material/scaffold.dart","errors":[]}}
1554479405489 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/material/theme_data.dart","errors":[]}}
1554479405540 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/material/time_picker.dart","errors":[]}}
1554479405560 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {id: 2, method: completion.setSubscriptions, params: {subscriptions: [AVAILABL
```

**Comment by gspencergoog** [comment]
And another crash just a minute later, which might be related.

## Version information

- `IDEA IC-191.6183.87`
- `2.2.1-edge.896f1c4bb94a390c2969953626980d9de320cd84`
- `IC-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Linux(amd64) v4.19.20-1rodete1-amd64, screens 3840x2160, 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.896f1c4bb94a390c2969953626980d9de320cd84, server version 1.25.0, error: Captured exception
Bad state: Attempt to modify immutable list
#0      _FbList.length= (package:analyzer/src/summary/flat_buffers.dart:873:7)
#1      __FbList&Object&ListMixin.add (dart:collection/list.dart:256:15)
#2      _File._extractDartdocInfoFromUnit (package:analyzer/src/services/available_declarations.dart:1378:21)
#3      _File.refresh (package:analyzer/src/services/available_declarations.dart:1050:7)
#4      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:643:12)
#5      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:507:7)
#6      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:208:13)
<asynchronous suspension>
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#8      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#9      new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#10     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#11     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#12     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#18     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#19     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#20     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#21     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#22     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## report.txt

```
1554479992525 <= {"event":"analysis.navigation","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","regions":[{"offset":173,"length":12
1554479992525 <= {"event":"analysis.closingLabels","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","labels":[]}}
1554479992527 <= {"event":"analysis.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","kind":"LIBRARY","outline":{"element":{
1554479992528 <= {"event":"analysis.overrides","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","overrides":[{"offset":17714,"length"
1554479992594 <= {"id":"25","result":{"id":"2"}}
1554479992595 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","errors":[]}}
1554479992597 <= {"event":"completion.results","params":{"id":"2","replacementOffset":739,"replacementLength":0,"results":[],"isLast":true,"includedSuggestionSets":[{"id":904,"relevance":5},{"id":966,
1554479992601 <= {"event":"analysis.highlights","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","regions":[{"type":"DIRECTIVE","offs
1554479992605 <= {"event":"analysis.navigation","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","regions":[{"offset":173,"length":12
1554479992605 <= {"event":"analysis.closingLabels","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","labels":[]}}
1554479992606 <= {"event":"analysis.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","kind":"LIBRARY","outline":{"element":{
1554479992607 <= {"event":"analysis.overrides","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","overrides":[{"offset":17715,"length"
1554479992635 => {"id":"26","method":"analysis.updateContent","params":{"files":{"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart":{"type":"add","conte
1554479992635 => {"id":"27","method":"completion.getSuggestions","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","offset":740},"clie
1554479992693 => {"id":"28","method":"analysis.updateContent","params":{"files":{"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart":{"type":"add","conte
1554479992693 => {"id":"29","method":"completion.getSuggestions","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","offset":741},"clie
1554479992737 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":0,"uri":"package:flutter/src/widgets/focus_manager.dart","items":[{"label":"FocusNode","element":{"kind"
1554479992742 <= {"id":"26","result":{}}
1554479992742 <= {"id":"28","result":{}}
1554479992791 <= {"id":"27","result":{"id":"3"}}
1554479992792 <= {"id":"29","result":{"id":"4"}}
1554479992792 <= {"event":"analysis.errors","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","errors":[]}}
1554479992796 <= {"event":"completion.results","params":{"id":"3","replacementOffset":740,"replacementLength":0,"results":[],"isLast":true,"includedSuggestionSets":[{"id":904,"relevance":5},{"id":966,
1554479992798 <= {"event":"completion.results","params":{"id":"4","replacementOffset":741,"replacementLength":0,"results":[],"isLast":true,"includedSuggestionSets":[{"id":904,"relevance":5},{"id":966,
1554479992810 <= {"event":"analysis.highlights","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","regions":[{"type":"DIRECTIVE","offs
1554479992813 <= {"event":"analysis.navigation","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","regions":[{"offset":173,"length":12
1554479992813 <= {"event":"analysis.closingLabels","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","labels":[]}}
1554479992815 <= {"event":"analysis.outline","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","kind":"LIBRARY","outline":{"element":{
1554479992816 <= {"event":"analysis.overrides","params":{"file":"/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/focus_manager.dart","overrides":[{"offset":17717,"length"
1554479992823 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Bad state: Attempt to modify immutable list\n#0      _FbList.length= (package:analyzer/s
```

**Comment by gspencergoog** [comment]
Closing in favor of consolidating with related crashes: https://github.com/dart-lang/sdk/issues/36496
