### ISSUE TITLE
I'm having this error popping up multiple times a day

### ISSUE THREAD

**Issue by AlexandreRoba** [dart-lang/sdk#36497]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.6183.87`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IU-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1920x1200  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Captured exception
RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core/runtime/libstring_patch.dart:387:7)
#1      unescapeLastStringPart (package:front_end/src/fasta/quote.dart:132:24)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:257:17)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4797:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4722:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3997:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3930:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3742:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:4912:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4884:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4865:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4844:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4580:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3991:14)
#15     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3783:21)
#16     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#17     Parser.parseReturnStatement (package:front_end/src/fasta/parser/parser.dart:3621:13)
#18     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3519:14)
#19     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#20     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5579:15)
#21     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3517:14)
#22     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#23     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5281:13)
#24     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3529:14)
#25     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#26     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5287:15)
#27     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3529:14)
#28     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#29     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3408:15)
#30     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3062:15)
#31     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2932:15)
#32     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2737:15)
#33     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1761:13)
#34     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1721:14)
#35     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:573:14)
#36     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:465:14)
#37     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#38     ParserAdapter.parseCompilationUnit2 (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analyzer/lib/src/generated/parser_fasta.dart:189:32)
#39     ParserAdapter.parseCompilationUnit (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analyzer/lib/src/generated/parser_fasta.dart:184:12)
#40     _File._parse (package:analyzer/src/services/available_declarations.dart:1354:23)
#41     _File.refresh (package:analyzer/src/services/available_declarations.dart:984:30)
#42     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:608:12)
#43     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:473:7)
#44     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:177:13)
<asynchronous suspension>
#45     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#46     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#47     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#48     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#49     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#50     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#51     _rootRun (dart:async/zone.dart:1124:13)
#52     _CustomZone.run (dart:async/zone.dart:1021:19)
#53     _runZoned (dart:async/zone.dart:1516:10)
#54     runZoned (dart:async/zone.dart:1463:12)
#55     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#56     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#57     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#58     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#59     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#60     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#61     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#62     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/xj/7jdppv9579qb2630pntk0y_80000gn/T/report.txt.

**Comment by srawlins** [comment]
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/36168; please follow along there.
