### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by benthillerkus** [dart-lang/sdk#36506]
### What I was doing

I typed in this line from this (https://www.youtube.com/watch?v=oxeYeMHVLII) tutorial:

"final _counterEventController = StreamController\<CounterEvent>();"

### Versions

- Flutter SDK 1.4.11-pre.27
- Visual Studio Code 1.33.0
- Dart Code 2.25.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\src\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.25.0
```

### Exception

Analysis failed: C:\Users\elite\OneDrive\Projekte\Tutorials\simple_todo\lib\counter_bloc.dart context: exception_20190406_181523_958

```text
Bad state: The type parameter T (in dart:async;dart:async/stream_controller.dart;StreamController;T) is out of scope.
#0      _createLinkedType (package:analyzer/src/summary/link.dart:211:7)
#1      _storeTypeArguments (package:analyzer/src/summary/link.dart:400:31)
#2      _createLinkedType (package:analyzer/src/summary/link.dart:193:5)
#3      CompilationUnitElementInBuildUnit._storeLinkedType (package:analyzer/src/summary/link.dart:1662:31)
#4      FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2598:23)
#5      ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:901:20)
#6      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1624:20)
#7      LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3820:12)
#8      LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3523:15)
#9      LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3463:7)
#10     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2205:13)
#11     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2224:18)
#12     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3496:42)
#13     Linker.link (package:analyzer/src/summary/link.dart:4025:35)
#14     _relink (package:analyzer/src/summary/link.dart:307:74)
#15     link (package:analyzer/src/summary/link.dart:124:3)
#16     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#18     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#19     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:72:5)
#20     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#21     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#22     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#23     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#24     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1216:17)
<asynchronous suspension>
#25     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#26     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#27     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#28     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#29     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#30     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#36     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#37     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#38     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#39     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#40     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "C:\\Users\\elite\\OneDrive\\Projekte\\Tutorials\\simple_todo",
        "explicitFileCount": 4,
        "implicitFileCount": 942,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by ThinkDigitalRepair** [comment]
Adding info to this issue.

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Creating a new dart file. Not sure what else caused the crash.

### Versions

- Flutter SDK 1.5.9-pre.15
- Visual Studio Code 1.33.1
- Dart Code 2.26.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/thinkdigital/development/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.26.0
```

### Exception

Failed to handle completion domain request: {id: 10, method: completion.setSubscriptions, params: {subscriptions: [AVAILABLE_SUGGESTION_SETS]}, clientRequestTime: 1556393031522}

```text
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _protocolAvailableSuggestionSet (package:analysis_server/src/domains/completion/available_suggestions.dart:141:35)
#2      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:75:14)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:76:8)
#6      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:482:11)
#7      _rootRunUnary (dart:async/zone.dart:1136:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/thinkdigital/GoogleDrive/Development/IdeaProjects/teddycare/card_settings",
        "explicitFileCount": 29,
        "implicitFileCount": 858,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/thinkdigital/GoogleDrive/Development/IdeaProjects/teddycare",
        "explicitFileCount": 134,
        "implicitFileCount": 1157,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/thinkdigital/GoogleDrive/Development/IdeaProjects/teddycare/card_settings/example",
        "explicitFileCount": 3,
        "implicitFileCount": 659,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment]
This has not been reported again since Flutter 1.5; please re-open if you see this in a recent version of Dart/Flutter.
