### ISSUE TITLE
Bad state: Too many elements

### ISSUE THREAD

**Issue by xuexin** [dart-lang/sdk#36538]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3 unknown, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec, server version 1.24.0, error: Analysis failed: /Users/liaoyuhao/mblock/test/widget_test.dart context: exception_20190409_154007_359
Bad state: Too many elements
#0      List.single (dart:core/runtime/lib/growable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2532:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5292:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5142:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2223:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2242:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5568:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5127:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1646:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3816:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3522:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3462:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2223:13)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2242:18)
#19     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3495:42)
#20     Linker.link (package:analyzer/src/summary/link.dart:4018:35)
#21     _relink (package:analyzer/src/summary/link.dart:305:57)
#22     link (package:analyzer/src/summary/link.dart:123:3)
#23     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#25     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#26     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:511:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:594:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:509:7)
#44     Driver.start (package:analysis_server/src/server/driver.dart:412:7)
#45     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#46     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#47     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#48     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/r_/_9bs4t6n7wd680stmrm0yk8m0000gn/T/report1.txt.
Dart analysis server, SDK version 2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec, server version 1.24.0, error: Analysis failed: /Users/liaoyuhao/mblock/test/widget_test.dart context: exception_20190409_154007_359
Bad state: Too many elements
#0      List.single (dart:core/runtime/lib/growable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2532:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5292:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5142:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2223:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2242:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5568:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5127:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1646:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3816:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3522:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3462:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2223:13)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2242:18)
#19     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3495:42)
#20     Linker.link (package:analyzer/src/summary/link.dart:4018:35)
#21     _relink (package:analyzer/src/summary/link.dart:305:57)
#22     link (package:analyzer/src/summary/link.dart:123:3)
#23     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#25     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#26     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:511:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:594:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:509:7)
#44     Driver.start (package:analysis_server/src/server/driver.dart:412:7)
#45     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#46     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#47     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#48     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)

```
1554795545502 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1554795545504 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["/Users/liaoyuhao/mblock"],"excluded":["/Users/liaoyuhao/mblock/.idea","/Users/liaoyuhao/mblock/.dart_tool","/User
1554795545504 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["/Users/liaoyuhao/mblock/lib/module/mb_base_page.dart"]},"clientRequestTime":1554795543704}
1554795545504 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/Users/liaoyuhao/mblock/lib/module/mb_base_page.dart"],"CLOSING_LABELS":["/Users/liaoyuhao/mblo
1554795545510 <= {"id":"1"}
1554795545515 <= {"id":"2"}
1554795547067 <= {"event":"analysis.errors","params":{"file":"/Users/liaoyuhao/mblock/pubspec.yaml","errors":[]}}
1554795551123 => {"id":"6","method":"edit.listPostfixCompletionTemplates","clientRequestTime":1554795551123}
1554795558392 => {"id":"7","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":["/Users/liaoyuhao/mblock/lib/module/mb_base_page.dart"]}}}
1554795558714 => {"id":"8","method":"analysis.setAnalysisRoots","params":{"included":["/Users/liaoyuhao/mblock"],"excluded":["/Users/liaoyuhao/mblock/.idea","/Users/liaoyuhao/mblock/.dart_tool","/User
1554795575676 => {"id":"9","method":"edit.getAssists","params":{"file":"/Users/liaoyuhao/mblock/lib/module/mb_base_page.dart","offset":2751,"length":0},"clientRequestTime":1554795575676}
1554795581501 <= {"id":"3"}
1554795581506 <= {"id":"4"}
1554795581517 <= {"id":"5"}
1554795581526 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1554795581974 => {"id":"10","method":"edit.getAssists","params":{"file":"/Users/liaoyuhao/mblock/lib/module/mb_base_page.dart","offset":2630,"length":0},"clientRequestTime":1554795581974}
1554795583076 => {"id":"11","method":"search.findElementReferences","params":{"file":"/Users/liaoyuhao/mblock/lib/module/mb_base_page.dart","offset":2627,"includePotential":true},"clientRequestTime":1
1554795584509 <= {"id":"7"}
1554795591886 => {"id":"12","method":"edit.getAssists","params":{"file":"/Users/liaoyuhao/mblock/lib/module/mb_base_page.dart","offset":2632,"length":0},"clientRequestTime":1554795591886}
1554795594279 => {"id":"13","method":"edit.getAssists","params":{"file":"/Users/liaoyuhao/mblock/lib/module/mb_base_page.dart","offset":2635,"length":0},"clientRequestTime":1554795594279}
1554795594975 => {"id":"14","method":"edit.getAssists","params":{"file":"/Users/liaoyuhao/mblock/lib/module/mb_base_page.dart","offset":2627,"length":13},"clientRequestTime":1554795594975}
1554795605634 <= {"id":"8"}
1554795605645 <= {"id":"6","result":{"templates":[{"name":"assert","key":".assert","example":"expr.assert -> assert(expr);"},{"name":"fori","key":".fori","example":"limit.fori -> for(var i = 0; i < li
1554795606310 <= {"id":"11","result":{}}
1554795606311 <= {"id":"9","result":{"assists":[]}}
1554795606311 <= {"id":"10","result":{"assists":[]}}
1554795606311 <= {"id":"12","result":{"assists":[]}}
1554795606312 <= {"id":"13","result":{"assists":[]}}
1554795606312 <= {"id":"14","result":{"assists":[]}}
1554795607446 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/liaoyuhao/mblock/test/widget_test.dart context: exception_20190409_154007_359","stackTrace":"Bad s
```

**Comment by xuexin** [comment]
Anyone can help？
This issue has been around and the plugin is completely unusable.
