### ISSUE TITLE
Assertion failure in timer_impl during slow hot reload

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#36612]
When hot reload syncs a large number of assets, we are reliably seeing a failed assertion in timer_impl. To reproduce:

1. Comment out all assets in the flutter_gallery pubspec.
2. flutter run flutter_gallery.
3. Uncomment all assets and perform hot reload.

Also see google3 issue b/130403939

```
{details: 'dart:isolate-patch/timer_impl.dart': Failed assertion: line 442: '<optimized out>': is not true.
           #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
           #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
           #2      _Timer._createTimerHandler (dart:isolate-patch/timer_impl.dart:442:12)
           #3      _Timer._notifyZeroHandler (dart:isolate-patch/timer_impl.dart:255:7)
           #4      _Timer._enqueue (dart:isolate-patch/timer_impl.dart:242:7)
           #5      _Timer._createTimer (dart:isolate-patch/timer_impl.dart:180:11)
           #6      new _Timer (dart:isolate-patch/timer_impl.dart:185:12)
           #7      _Timer._factory (dart:isolate-patch/timer_impl.dart:462:16)
           #8      Timer._createTimer (dart:async-patch/timer_patch.dart:20:34)
           #9      _RootZone.createTimer (dart:async/zone.dart:1403:18)
           #10     new Timer (dart:async/timer.dart:49:27)
           #11     new Future.delayed (dart:async/future.dart:311:9)
           #12     BindingBase.registerServiceExtension.<anonymous closure>.<anonymous closure> (package:flutter/src/foundation/binding.dart:505:9)
           #13     debugInstrumentAction (package:flutter/src/foundation/debug.dart:62:18)
           #14     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:504:13)
           #15     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
           #16     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:486:45)
           #17     _runExtension (dart:developer-patch/developer.dart:84:23)
           #18     _Timer._enqueue (dart:isolate-patch/timer_impl.dart:232:3)
           #19     _Timer._createTimer (dart:isolate-patch/timer_impl.dart:180:11)
           #20     new _Timer (dart:isolate-patch/timer_impl.dart:185:12)
           #21     _Timer._factory (dart:isolate-patch/timer_impl.dart:462:16)
           #22     Timer._createTimer (dart:async-patch/timer_patch.dart:20:34)
           #23     _RootZone.createTimer (dart:async/zone.dart:1403:18)
           #24     new Timer (dart:async/timer.dart:49:27)
           #25     new Future.delayed (dart:async/future.dart:311:9)
           #26     BindingBase.registerServiceExtension.<anonymous closure>.<anonymous closure> (package:flutter/src/foundation/binding.dart:505:9)
           #27     debugInstrumentAction (package:flutter/src/foundation/debug.dart:62:18)
           #28     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:504:13)
           #29     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
           #30     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:486:45)
           #31     _runExtension (dart:developer-patch/developer.dart:84:23)
           #32     _Timer._createTimer (dart:isolate-patch/timer_impl.dart:173:51)
           #33     new _Timer (dart:isolate-patch/timer_impl.dart:185:12)
           #34     _Timer._factory (dart:isolate-patch/timer_impl.dart:462:16)
           #35     Timer._createTimer (dart:async-patch/timer_patch.dart:20:34)
           #36     _RootZone.createTimer (dart:async/zone.dart:1403:18)
           #37     new Timer (dart:async/timer.dart:49:27)
           #38     new Future.delayed (dart:async/future.dart:311:9)
           #39     BindingBase.registerServiceExtension.<anonymous closure>.<anonymous closure> (package:flutter/src/foundation/binding.dart:505:9)
           #40     debugInstrumentAction (package:flutter/src/foundation/debug.dart:62:18)
           #41     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:504:13)
           #42     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
           #43     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:486:45)
           #44     _runExtension (dart:developer-patch/developer.dart:84:23)
           #45     Timer._createTimer (dart:async-patch/timer_patch.dart:9:3)
           #46     _RootZone.createTimer (dart:async/zone.dart:1403:18)
           #47     new Timer (dart:async/timer.dart:49:27)
           #48     new Future.delayed (dart:async/future.dart:311:9)
           #49     BindingBase.registerServiceExtension.<anonymous closure>.<anonymous closure> (package:flutter/src/foundation/binding.dart:505:9)
           #50     debugInstrumentAction (package:flutter/src/foundation/debug.dart:62:18)
           #51     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:504:13)
           #52     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
           #53     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:486:45)
           #54     _runExtension (dart:developer-patch/developer.dart:84:23)
           #55     new Future.delayed (dart:async/future.dart:309:3)
           #56     BindingBase.registerServiceExtension.<anonymous closure>.<anonymous closure> (package:flutter/src/foundation/binding.dart:505:9)
           #57     debugInstrumentAction (package:flutter/src/foundation/debug.dart:62:18)
           #58     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:504:13)
           #59     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
           #60     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:486:45)
           #61     _runExtension (dart:developer-patch/developer.dart:84:23)
           #62     BindingBase.registerServiceExtension.<anonymous closure>.<anonymous closure> (package:flutter/src/foundation/binding.dart:488:14)
           #63     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:492:8)
           #64     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
           #65     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:486:45)
           #66     _runExtension (dart:developer-patch/developer.dart:84:23)
           #67     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:486:45)
           #68     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
           #69     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:486:45)
           #70     _runExtension (dart:developer-patch/developer.dart:84:23)
           #71     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:486:45)
           #72     _runExtension (dart:developer-patch/developer.dart:84:23)
           #73     _runExtension (dart:developer-patch/developer.dart:69:1)
```

**Comment by jonahwilliams** [comment]
cc @a-siva

**Comment by rmacnak-google** [comment]
Hm, it looks like the timer implementation is being re-entered because a service extension creates some timers. I thought we had arranged the service extensions have their execution delayed until the next turn of the event loop.
