### ISSUE TITLE
Analysis server terminated (IntelliJ)

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/sdk#36624]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.6183.87`
- `2.2.0`
- `IC-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-141-generic, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.0, server version 1.23.0, error: Exception while using a AvoidShadowingTypeParameters to visit a GenericTypeAliasImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'typeParameters' was called on null.
Receiver: null
Tried calling: typeParameters
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _Visitor.visitGenericTypeAlias (package:linter/src/rules/avoid_shadowing_type_parameters.dart:65:27)
#2      GenericTypeAliasImpl.accept (package:analyzer/src/dart/ast/ast.dart:6304:20)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:743:14)
#4      LinterVisitor.visitGenericTypeAlias (package:analyzer/src/lint/linter_visitor.dart:353:5)
#5      GenericTypeAliasImpl.accept (package:analyzer/src/dart/ast/ast.dart:6304:20)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9046:20)
#7      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2446:21)
#8      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:758:10)
#9      LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#10     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439:49)
#11     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:290:10)
#12     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:160:11)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:155:35)
#15     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#17     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#18     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1438:63)
#19     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#20     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#21     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1216:17)
<asynchronous suspension>
#22     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#23     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#24     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#25     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#26     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#27     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#33     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#34     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#35     main (file:///tmp/tmpyaVT9t/dart-2.2.0/dart/pkg/analysis_server/bin/server.dart:12:11)
#36     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#37     main (file:///tmp/tmpyaVT9t/dart-2.2.0/dart/pkg/analysis_server/bin/server.dart:10:10)
#38     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

I tried to define a `typedef` like this (I was experimenting with what's possible, I know this is not valid):

```dart
typedef EntanglingTextBox = TextBoxModel & Entanglement<TextBoxModel>;
```

`TextBoxModel` is just a normal class... `Entanglement` is a mixin with an unbounded type parameter.

IntelliJ just went nuts: the analyser kept trying to restart and crash again. I had to turn off all inspections to make it stop doing that.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.2; please re-open if you see this in a recent version of Dart/Flutter.
