### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by kaushiksamanta** [dart-lang/sdk#36623]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.6183.87`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IC-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Failed to handle completion domain request: {id: 2, method: completion.setSubscriptions, params: {subscriptions: [AVAILABLE_SUGGESTION_SETS]}, clientRequestTime: 1555194015615}
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<AvailableSuggestion>(Closure: (Declaration) => AvailableSuggestion)
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:85:30)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#4      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:89:8)
#5      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:383:11)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#13     _rootRun (dart:async/zone.dart:1120:38)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#24     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/my/lqgvw_xj0dd8p6lzxcj_jy7w0000gn/T/report.txt.

**Comment by srawlins** [comment]
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).
