### ISSUE TITLE
RuntimeError for service/reload_sources_test on app-kernel-linux-debug-x64

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#36631]
Checked locally since the [first failing build](https://ci.chromium.org/p/dart/builders/ci.sandbox/app-kernel-linux-debug-x64/2884) had a few commits in it, RTE in test started after enabling of constant-update-2018 (commit e9ca6a53).

Here's an [example log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8916149024710305888/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0):

```
/========================================================================\
  | service/reload_sources_test failed again (RuntimeError, expected Pass) |
  \========================================================================/
  --- Command "app_jit" (took 40.000088s):
  DART_CONFIGURATION=DebugX64 out/DebugX64/dart --snapshot=/b/s/w/ir/cache/builder/sdk/out/DebugX64/generated_compilations/app_jitk/runtime_observatory_tests_service_reload_sources_test/out.jitsnapshot --snapshot-kind=app-jit --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/reload_sources_test.dart
  exit code:
  0
  stdout:
  ** Launching SERVICE_TEST_TESTEE=true out/DebugX64/dart --profiler --snapshot=/b/s/w/ir/cache/builder/sdk/out/DebugX64/generated_compilations/app_jitk/runtime_observatory_tests_service_reload_sources_test/out.jitsnapshot --snapshot-kind=app-jit --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --enable-vm-service:0 /b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/reload_sources_test.dart
  >testee>out> Observatory listening on http://127.0.0.1:40985/
  ** Signaled to run test queries on http://127.0.0.1:40985/
  >testee>out>
  Loading VM...
  Done loading VM
  Running reload_sources_test.dart [1/10]
  Paused with PauseBreakpoint
  Running reload_sources_test.dart [2/10]
  Running reload_sources_test.dart [3/10]
  Paused with PauseBreakpoint
  Running reload_sources_test.dart [4/10]
  >testee>out> 1
  Running reload_sources_test.dart [5/10]
  Running reload_sources_test.dart [6/10]
  Paused with PausePostRequest
  Running reload_sources_test.dart [7/10]
  Running reload_sources_test.dart [8/10]
  Running reload_sources_test.dart [9/10]
  Running reload_sources_test.dart [10/10]
  All service tests completed successfully.
  ** Killing script
  ** Process exited
  --- Command "vm" (took 07.000853s):
  DART_CONFIGURATION=DebugX64 out/DebugX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/DebugX64/generated_compilations/app_jitk/runtime_observatory_tests_service_reload_sources_test/out.jitsnapshot
  exit code:
  255
  stdout:
  ** Launching SERVICE_TEST_TESTEE=true out/DebugX64/dart --profiler --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --enable-vm-service:0 /b/s/w/ir/cache/builder/sdk/out/DebugX64/generated_compilations/app_jitk/runtime_observatory_tests_service_reload_sources_test/out.jitsnapshot
  >testee>out>
  ** Signaled to run test queries on http://127.0.0.1:33413/
  >testee>out> Observatory listening on http://127.0.0.1:33413/
  Loading VM...
  Done loading VM
  Running out.jitsnapshot [1/10]
  Paused with PauseBreakpoint
  Running out.jitsnapshot [2/10]
  >testee>err> ../../runtime/vm/object.h: 5920: error: expected: cls.is_finalized() || cls.is_prefinalized()
  >testee>err> version=2.2.1-edge.ec0447db5d27049f5bb87d639e043993a76593cd (Mon Apr 15 02:17:44 2019 +0000) on "linux_x64"
  >testee>err> thread=26378, isolate=main(0x55dcd2cec900)
  >testee>err>   pc 0x000055dcd0b48e6c fp 0x00007fbc6d6fa8a0 dart::Profiler::DumpStackTrace(void*)
  >testee>err>   pc 0x000055dcd0e25502 fp 0x00007fbc6d6fa980 dart::Assert::Fail(char const*, ...)
  >testee>err>   pc 0x000055dcd0aef8c6 fp 0x00007fbc6d6fa9c0 out/DebugX64/dart+0x17c88c6
  >testee>err>   pc 0x000055dcd0aef96f fp 0x00007fbc6d6faa30 dart::Instance::CanonicalizeHash() const
  >testee>err>   pc 0x000055dcd0b04fe6 fp 0x00007fbc6d6faaa0 dart::Array::CanonicalizeHash() const
  >testee>err>   pc 0x000055dcd0b1e835 fp 0x00007fbc6d6faad0 out/DebugX64/dart+0x17f7835
  >testee>err>   pc 0x000055dcd0b1e5c0 fp 0x00007fbc6d6fab40 out/DebugX64/dart+0x17f75c0
  >testee>err>   pc 0x000055dcd0b1e4dd fp 0x00007fbc6d6faba0 out/DebugX64/dart+0x17f74dd
  >testee>err>   pc 0x000055dcd0b1e149 fp 0x00007fbc6d6fac20 out/DebugX64/dart+0x17f7149
  >testee>err>   pc 0x000055dcd0aa33ae fp 0x00007fbc6d6fac50 out/DebugX64/dart+0x177c3ae
  >testee>err>   pc 0x000055dcd0aa2e82 fp 0x00007fbc6d6face0 dart::Class::InsertCanonicalConstant(dart::Zone*, dart::Instance const&) const
  >testee>err>   pc 0x000055dcd0af0187 fp 0x00007fbc6d6fad50 dart::Instance::CheckAndCanonicalize(dart::Thread*, char const**) const
  >testee>err>   pc 0x000055dcd0d76d0d fp 0x00007fbc6d6fad80 dart::kernel::TranslationHelper::Canonicalize(dart::Instance const&)
  >testee>err>   pc 0x000055dcd0d4bc76 fp 0x00007fbc6d6fae30 dart::kernel::ConstantHelper::ReadConstantTable()
  >testee>err>   pc 0x000055dcd0a55de0 fp 0x00007fbc6d6fafd0 dart::kernel::KernelLoader::ReadConstantTable()
  >testee>err>   pc 0x000055dcd0a549d6 fp 0x00007fbc6d6fb120 dart::kernel::KernelLoader::LoadProgram(bool)
  >testee>err>   pc 0x000055dcd0a53f84 fp 0x00007fbc6d6fb590 dart::kernel::KernelLoader::LoadEntireProgram(dart::kernel::Program*, bool)
  >testee>err>   pc 0x000055dcd0a349b4 fp 0x00007fbc6d6fb700 dart::IsolateReloadContext::Reload(bool, char const*, char const*, unsigned char const*, long)
  >testee>err>   pc 0x000055dcd0a2a565 fp 0x00007fbc6d6fb760 dart::Isolate::ReloadSources(dart::JSONStream*, bool, char const*, char const*, bool)
  >testee>err>   pc 0x000055dcd0bcde8c fp 0x00007fbc6d6fb7a0 out/DebugX64/dart+0x18a6e8c
  >testee>err>   pc 0x000055dcd0bc3829 fp 0x00007fbc6d6fc160 dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
  >testee>err>   pc 0x000055dcd0bc43b0 fp 0x00007fbc6d6fc1a0 dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
  >testee>err>   pc 0x000055dcd0a25a9c fp 0x00007fbc6d6fcbf0 dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  >testee>err>   pc 0x000055dcd0a67598 fp 0x00007fbc6d6fcc70 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  >testee>err>   pc 0x000055dcd0a67c0f fp 0x00007fbc6d6fccd0 dart::MessageHandler::HandleOOBMessages()
  >testee>err>   pc 0x000055dcd0e00006 fp 0x00007fbc6d6fcd80 Dart_HandleServiceMessages
  >testee>err>   pc 0x000055dcd0a2edc3 fp 0x00007fbc6d6fcde0 dart::Isolate::PauseEventHandler()
  >testee>err>   pc 0x000055dcd09e4d35 fp 0x00007fbc6d6fcf70 dart::Debugger::Pause(dart::ServiceEvent*)
  >testee>err>   pc 0x000055dcd09f2418 fp 0x00007fbc6d6fd090 dart::Debugger::SignalPausedEvent(dart::ActivationFrame*, dart::Breakpoint*)
  >testee>err>   pc 0x000055dcd09f288e fp 0x00007fbc6d6fd0e0 dart::Debugger::PauseStepping()
  >testee>err>   pc 0x000055dcd0bb0946 fp 0x00007fbc6d6fd9d0 dart::DRT_SingleStepHandler(dart::NativeArguments)
  >testee>err>   pc 0x00007fbc6d701197 fp 0x00007fbc6d6fda18 Unknown symbol
  >testee>err>   pc 0x00007fbc6d702eea fp 0x00007fbc6d6fda40 Unknown symbol
...
  >testee>err>   pc 0x00007fbc6fc5ec93 fp 0x00007fbc6d6fe018 Unknown symbol
  >testee>err>   pc 0x00007fbc6d70169a fp 0x00007fbc6d6fe088 Unknown symbol
  >testee>err>   pc 0x000055dcd09de233 fp 0x00007fbc6d6fe130 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  >testee>err>   pc 0x000055dcd09e14d1 fp 0x00007fbc6d6fe1a0 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  >testee>err>   pc 0x000055dcd0a25b1e fp 0x00007fbc6d6febf0 dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  >testee>err>   pc 0x000055dcd0a67598 fp 0x00007fbc6d6fec70 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  >testee>err>   pc 0x000055dcd0a68306 fp 0x00007fbc6d6fecf0 dart::MessageHandler::TaskCallback()
  >testee>err>   pc 0x000055dcd0c0073c fp 0x00007fbc6d6fed40 dart::ThreadPool::Worker::Loop()
  >testee>err>   pc 0x000055dcd0c0021b fp 0x00007fbc6d6fed90 dart::ThreadPool::Worker::Main(unsigned long)
  >testee>err>   pc 0x000055dcd0b42b85 fp 0x00007fbc6d6feed0 out/DebugX64/dart+0x181bb85
  >testee>err> -- End of DumpStackTrace
  ** Killing script
  Unexpected exception in service tests: NetworkRpcException(Canceling request: WebSocket closed(id: 8 method: reloadSources params: {pause: true, isolateId: isolates/661135017}))
  #0      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/test_helper.dart:334:13)
  <asynchronous suspension>
  #1      _rootRunUnary (dart:async/zone.dart:1132:38)
  #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
  #3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
  #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
  #5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
  #6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
  #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
  #8      _rootRun (dart:async/zone.dart:1124:13)
  #9      _CustomZone.run (dart:async/zone.dart:1021:19)
  #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
  #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
  stderr:
  Unhandled exception:
  NetworkRpcException(Canceling request: WebSocket closed(id: 8 method: reloadSources params: {pause: true, isolateId: isolates/661135017}))
  #0      _ServiceTesterRunner.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/test_helper.dart:334:13)
  <asynchronous suspension>
  #1      _rootRunUnary (dart:async/zone.dart:1132:38)
  #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
  #3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
  #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
  #5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
  #6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
  #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
  #8      _rootRun (dart:async/zone.dart:1124:13)
  #9      _CustomZone.run (dart:async/zone.dart:1021:19)
  #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
  #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
  --- Re-run this test:
  python tools/test.py -n app_jitk-linux-debug-x64 service/reload_sources_test
```

Approving failure for now to clear redness from bot.

**Comment by liamappelbe** [comment]
Looks like this was fixed when some similar bugs were fixed.
