### ISSUE TITLE
Invalid compile time error then crash from DDK using the CFE

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#36656]
This is likely related to https://github.com/dart-lang/sdk/issues/36644, but manifests in a different way. Some differences include:

- This gives a compile error before the crash (but its an invalid compile error, it has two different versions of the same class that aren't equal to each other)
- This is _not_ fixed by dropping down to a single worker like the other issue

On incremental edits to the `SUNGLASSES` string in `lib/demo/animation/sections.dart` in the flutter gallery example I am getting the following error:

```
Error compiling dartdevc module:flutter_web.examples.gallery|lib/demo/animation/home.ddc.js

packages/flutter_web.examples.gallery/demo/animation/home.dart:341:20: Error: The argument type 'Section/*1*/' can't be assigned to the parameter type 'Section/*2*/'.
 - 'Section/*1*/' is from 'package:flutter_web.examples.gallery/demo/animation/sections.dart' ('packages/flutter_web.examples.gallery/demo/animation/sections.dart').
 - 'Section/*2*/' is from 'package:flutter_web.examples.gallery/demo/animation/sections.dart' ('packages/flutter_web.examples.gallery/demo/animation/sections.dart').
Try changing the type of the parameter, or casting the argument to 'Section/*2*/'.
          section: section,
                   ^
packages/flutter_web.examples.gallery/demo/animation/home.dart:525:40: Error: The argument type 'SectionDetail/*1*/' can't be assigned to the parameter type 'SectionDetail/*2*/'.
 - 'SectionDetail/*1*/' is from 'package:flutter_web.examples.gallery/demo/animation/sections.dart' ('packages/flutter_web.examples.gallery/demo/animation/sections.dart').
 - 'SectionDetail/*2*/' is from 'package:flutter_web.examples.gallery/demo/animation/sections.dart' ('packages/flutter_web.examples.gallery/demo/animation/sections.dart').
Try changing the type of the parameter, or casting the argument to 'SectionDetail/*2*/'.
      return SectionDetailView(detail: detail);
                                       ^
packages/flutter_web.examples.gallery/demo/animation/home.dart:537:52: Error: The argument type 'Section/*1*/' can't be assigned to the parameter type 'Section/*2*/'.
 - 'Section/*1*/' is from 'package:flutter_web.examples.gallery/demo/animation/sections.dart' ('packages/flutter_web.examples.gallery/demo/animation/sections.dart').
 - 'Section/*2*/' is from 'package:flutter_web.examples.gallery/demo/animation/sections.dart' ('packages/flutter_web.examples.gallery/demo/animation/sections.dart').
Try changing the type of the parameter, or casting the argument to 'Section/*2*/'.
            child: SectionCard(section: allSections[index]),

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/usr/local/google/home/jakemac/dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/flutter_web.examples.gallery/demo/animation/home.ddc.js --source-map -s packages/meta/meta.ddc.dill=packages/meta/meta -s packages/collection/src/utils.ddc.dill=packages/collection/src/utils -s packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms -s packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip -s packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators -s packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue -s packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map -s packages/collection/collection.ddc.dill=packages/collection/collection -s packages/vector_math/hash.ddc.dill=packages/vector_math/hash -s packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 -s packages/flutter_web_ui/src/alarm_clock.ddc.dill=packages/flutter_web_ui/src/alarm_clock -s packages/flutter_web/io.ddc.dill=packages/flutter_web/io -s packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers -s packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions -s packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation -s packages/flutter_web/src/services/clipboard.ddc.dill=packages/flutter_web/src/services/clipboard -s packages/flutter_web/services.ddc.dill=packages/flutter_web/services -s packages/flutter_web/src/scheduler/binding.ddc.dill=packages/flutter_web/src/scheduler/binding -s packages/flutter_web/scheduler.ddc.dill=packages/flutter_web/scheduler -s packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation -s packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics -s packages/flutter_web/src/gestures/arena.ddc.dill=packages/flutter_web/src/gestures/arena -s packages/flutter_web/gestures.ddc.dill=packages/flutter_web/gestures -s packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation -s packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation -s packages/flutter_web/src/cupertino/activity_indicator.ddc.dill=packages/flutter_web/src/cupertino/activity_indicator -s packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino -s packages/flutter_web/material.ddc.dill=packages/flutter_web/material -s packages/flutter_web.examples.gallery/demo/animation/sections.ddc.dill=packages/flutter_web.examples.gallery/demo/animation/sections -s packages/flutter_web.examples.gallery/demo/animation/widgets.ddc.dill=packages/flutter_web.examples.gallery/demo/animation/widgets --packages file:///tmp/kernel_builder_HZQIXK/.packages --module-name packages/flutter_web.examples.gallery/demo/animation/home --multi-root-scheme org-dartlang-app --multi-root . --track-widget-creation --inline-source-map package:flutter_web.examples.gallery/demo/animation/home.dart
    dart --version: 2.2.1-dev.4.2 (Thu Apr 11 22:14:37 2019 +0200) on "linux_x64"

Bad state: Could not find module name for library "#lib1" from component "null".
#0      ProgramCompiler.libraryToModule (package:dev_compiler/src/kernel/compiler.dart:343:7)
#1      _ProgramCompiler&Object&SharedCompiler.emitImportsAndExtensionSymbols (package:dev_compiler/src/compiler/shared_compiler.dart:430:27)
#2      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:289:5)
#3      _compile (package:dev_compiler/src/kernel/command.dart:317:27)
<asynchronous suspension>
#4      compile (package:dev_compiler/src/kernel/command.dart:41:18)
<asynchronous suspension>
#5      compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#6      _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:54:39)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:54:24)
<asynchronous suspension>
#12     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#18     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

```

**Comment by jakemac53** [comment]
Note that you need to run without https://dart-review.googlesource.com/c/sdk/+/99442 in order to repro this issue - that does hide it effectively.

**Comment by jmesserly** [comment]
yeah that does appear to be the same issue: old Classes/DartTypes are hanging around.

Any theory about why DDC's backend crashes? DDC is supposed to stop compiling once it sees a compile error, and not attempt to generate JS code. Strange.

**Comment by jakemac53** [comment]
> Any theory about why DDC's backend crashes? DDC is supposed to stop compiling once it sees a compile error, and not attempt to generate JS code. Strange.

I actually filed a different bug for that already https://github.com/dart-lang/sdk/issues/36463

**Comment by vsmenon** [comment]
Let's go ahead and merge this into #36644 for now.  I think this is the same fundamental issue around incremental compile.
