### ISSUE TITLE
I got this error editing the Flutter SDK

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#36668]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.6183.87`
- `2.2.1-edge.bc99f1ca2819c67a5260929b03c3d7ed24943b58`
- `IU-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.bc99f1ca2819c67a5260929b03c3d7ed24943b58, server version 1.26.0, error: Captured exception
Unsupported operation: unsupported initializer: BinaryExpressionImpl :: super() < Object > [message]
#0      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:1227:9)
#1      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2530:14)
#2      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2466:14)
#3      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3154:13)
#4      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3042:15)
#5      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2844:15)
#6      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1828:13)
#7      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1788:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:640:14)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:532:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:347:15)
#11     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:194:32)
#12     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:189:12)
#13     _File._parse (package:analyzer/src/services/available_declarations.dart:1595:23)
#14     _File.refresh (package:analyzer/src/services/available_declarations.dart:1044:30)
#15     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:634:12)
#16     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:498:7)
#17     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:219:13)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#23     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#29     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#30     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#31     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#32     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#33     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#34     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/pl/5yqcvds916b39jxc_pb66y700025bq/T/report.txt.

**Comment by srawlins** [comment]
Although this issue is older, it looks like more context has been added in duplicate issue, https://github.com/dart-lang/sdk/issues/37693.
