### ISSUE TITLE
Dart analysis server: type 'LocalVariableElementImpl' is not a subtype of type 'ExecutableElement'

### ISSUE THREAD

**Issue by matthewlloyd** [dart-lang/sdk#36685]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.6707.61`
- `2.2.1-edge.cf4444b803a376bb1ad6442e1f09434a4d58167b`
- `IC-191.6707.61, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.cf4444b803a376bb1ad6442e1f09434a4d58167b, server version 1.26.0, FATAL error: Failed to handle request: {id: 22243, method: edit.getFixes, params: {file: /Users/<redacted>/flutter_app/lib/tab_forecast.dart, offset: 2900}, clientRequestTime: 1555796378760}
type 'LocalVariableElementImpl' is not a subtype of type 'ExecutableElement'
#0      FixProcessor._addFix_convertToNamedArgument (package:analysis_server/src/services/correction/fix_internal.dart:1322:9)
<asynchronous suspension>
#1      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:459:13)
<asynchronous suspension>
#2      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#3      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:639:46)
<asynchronous suspension>
#4      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:741:14)
<asynchronous suspension>
#5      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:277:32)
<asynchronous suspension>
#6      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:380:9)
#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:337:45)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#9      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:50)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1500:12)
#14     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:332:5)
#15     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#17     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#18     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#49     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#50     _StreamController._add (dart:async/stream_controller.dart:640:7)
#51     _StreamController.add (dart:async/stream_controller.dart:586:5)
#52     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#53     _rootRunUnary (dart:async/zone.dart:1136:13)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#58     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#59     _StreamController._add (dart:async/stream_controller.dart:640:7)
#60     _StreamController.add (dart:async/stream_controller.dart:586:5)
#61     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#62     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#63     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#64     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#65     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

1555796378065 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1555796378077 => {"id":"22240","method":"edit.getAssists","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","offset":2914,"length":0},"clientRequestTime":15557963
1555796378087 <= {"event":"analysis.errors","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/User
1555796378089 <= {"id":"22240","result":{"assists":[{"message":"Convert to an int literal","edits":[{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","fileStamp":0,"edits"
1555796378092 <= {"event":"analysis.highlights","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","regions":[{"type":"DIRECTIVE","offset":1,"length":17},{"type":"
1555796378094 <= {"event":"analysis.navigation","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","regions":[{"offset":8,"length":9,"targets":[0]},{"offset":27,"l
1555796378094 <= {"event":"analysis.closingLabels","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","labels":[{"offset":2733,"length":145,"label":"Row"},{"offset
1555796378095 <= {"event":"analysis.outline","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","n
1555796378095 <= {"event":"analysis.overrides","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","overrides":[{"offset":2231,"length":5,"superclassMember":{"eleme
1555796378099 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":739,"uri":"package:flutter_app/tab_forecast.dart","items":[{"label":"TabForecast","element":{"kind":"CLA
1555796378099 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1555796378099 <= {"event":"analysis.implemented","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","classes":[],"members":[]}}
1555796378399 => {"id":"22241","method":"analysis.updateContent","params":{"files":{"/Users/<redacted>/flutter_app/lib/tab_forecast.dart":{"type":"add","content":"\nimport 'dart:ui';\
1555796378409 <= {"id":"22241","result":{}}
1555796378409 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1555796378428 <= {"event":"analysis.errors","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"
1555796378429 => {"id":"22242","method":"edit.getAssists","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","offset":2916,"length":0},"clientRequestTime":15557963
1555796378430 <= {"event":"analysis.highlights","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","regions":[{"type":"DIRECTIVE","offset":1,"length":17},{"type":"
1555796378432 <= {"event":"analysis.navigation","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","regions":[{"offset":8,"length":9,"targets":[0]},{"offset":27,"l
1555796378432 <= {"event":"analysis.closingLabels","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","labels":[{"offset":2733,"length":145,"label":"Row"},{"offset
1555796378433 <= {"event":"analysis.outline","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","n
1555796378433 <= {"event":"analysis.overrides","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","overrides":[{"offset":2231,"length":5,"superclassMember":{"eleme
1555796378435 <= {"id":"22242","result":{"assists":[]}}
1555796378439 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":739,"uri":"package:flutter_app/tab_forecast.dart","items":[{"label":"TabForecast","element":{"kind":"CLA
1555796378439 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1555796378439 <= {"event":"analysis.implemented","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","classes":[],"members":[]}}
1555796378760 => {"id":"22243","method":"edit.getFixes","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","offset":2900},"clientRequestTime":1555796378760}
1555796378795 => {"id":"22244","method":"edit.getFixes","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","offset":2915},"clientRequestTime":1555796378795}
1555796378795 => {"id":"22245","method":"edit.getFixes","params":{"file":"/Users/<redacted>/flutter_app/lib/tab_forecast.dart","offset":2915},"clientRequestTime":1555796378795}
1555796378987 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 22243, method: edit.getFixes, params: {file: /Users/<redacted>/flutter_app/
```

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.2; please re-open if you see this in a recent version of Dart/Flutter.
