### ISSUE TITLE
Dart Analyzer keeps crashing after automatically restarting and slows my complete IDE down.

### ISSUE THREAD

**Issue by nilsegger** [dart-lang/sdk#36684]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-191.6707.60`
- `2.2.0`
- `WS-191.6707.60, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Linux(amd64) v4.18.0-17-generic, screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.0, server version 1.23.0, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [/home/nils/weasel/sharedlib], excluded: [/home/nils/weasel/sharedlib/.idea, /home/nils/weasel/sharedlib/.dart_tool, /home/nils/weasel/sharedlib/.pub, /home/nils/weasel/sharedlib/build]}, clientRequestTime: 1555771833982}
NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _DartNavigationComputerVisitor._addUriDirectiveRegion (package:analysis_server/src/domains/analysis/navigation_dart.dart:361:47)
#2      _DartNavigationComputerVisitor.visitPartDirective (package:analysis_server/src/domains/analysis/navigation_dart.dart:232:5)
#3      PartDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:9453:49)
#4      _DartNavigationComputerVisitor.visitCompilationUnit (package:analysis_server/src/domains/analysis/navigation_dart.dart:149:12)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439:49)
#6      computeDartNavigation (package:analysis_server/src/domains/analysis/navigation_dart.dart:28:10)
#7      ServerContextManagerCallbacks._computeNavigationParams (package:analysis_server/src/analysis_server.dart:1034:5)
#8      ServerContextManagerCallbacks.addAnalysisDriver.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:843:19)
#9      new Future.<anonymous closure> (dart:async/future.dart:176:37)
#10     _rootRun (dart:async/zone.dart:1120:38)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#18     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#19     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by nilsegger** [comment]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-191.6707.60`
- `2.2.0`
- `WS-191.6707.60, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Linux(amd64) v4.18.0-17-generic, screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.0, server version 1.23.0, error: Failed to handle completion domain request: {id: 2, method: completion.setSubscriptions, params: {subscriptions: [AVAILABLE_SUGGESTION_SETS]}, clientRequestTime: 1555773904038}
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<AvailableSuggestion>(Closure: (Declaration) => AvailableSuggestion)
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:74:30)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#4      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:78:8)
#5      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:390:11)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#13     _rootRun (dart:async/zone.dart:1120:38)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#24     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///tmp/report1.txt.

**Comment by srawlins** [comment]
Thanks for reporting this issue!  This was previously reported in https://github.com/dart-lang/sdk/issues/36182; it  should be fixed now in a recent release  of Dart.
