### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by sherifhasan** [dart-lang/sdk#36709]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.5429.30.34.5452501`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-183.5429.30.34.5452501, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: E:\silverkey_seven\App\vendor\lib\main.dart context: exception_20190423_122253_050
NoSuchMethodError: Class 'LibraryElementInBuildUnit' has no instance getter 'session'.
Receiver: Instance of 'LibraryElementInBuildUnit'
Tried calling: session
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      LibraryElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3736:48)
#2      LibraryElementInBuildUnit.session (package:analyzer/src/dart/element/element.dart:5206:25)
#3      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:542:30)
#4      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:397:15)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:137:27)
#6      Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1063:12)
#7      AstRewriteVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:83:35)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8671:49)
#9      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2535:16)
#10     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#11     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#12     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#13     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#14     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#15     FunctionElementForLink_Initializer.returnType (package:analyzer/src/summary/link.dart:2852:24)
#16     InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:423:37)
#17     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:303:11)
#18     InstanceMemberInferrer._inferClasses (package:analyzer/src/task/strong_mode.dart:326:9)
#19     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:55:5)
#20     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1638:7)
#21     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#22     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#23     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#24     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#25     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#26     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#27     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#28     _relink (package:analyzer/src/summary/link.dart:305:57)
#29     link (package:analyzer/src/summary/link.dart:123:3)
#30     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#31     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#32     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#33     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1624:23)
#34     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#35     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#36     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#37     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#38     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#39     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#40     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#41     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#42     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#43     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _runZoned (dart:async/zone.dart:1516:10)
#47     runZoned (dart:async/zone.dart:1463:12)
#48     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#49     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#50     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#51     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#52     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#53     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#54     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#55     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by parlough** [comment]
Seems to be the same issue as https://github.com/dart-lang/sdk/issues/36872

Likely fixed by https://github.com/dart-lang/sdk/commit/7418238239f885ba92093c44a1768f8ec93b121f
