### ISSUE TITLE
NPE from _protocolAvailableSuggestionSet (Flutter SDK 1.5.5-pre.15)

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#36725]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Doing some web-based stuff. 

### Versions

- Flutter SDK 1.5.5-pre.15
- Visual Studio Code 1.33.1
- Dart Code 2.26.0-beta.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
c:\git\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.26.0-beta.1
```

### Exception

Failed to handle completion domain request: {id: 3, method: completion.setSubscriptions, params: {subscriptions: [AVAILABLE_SUGGESTION_SETS]}, clientRequestTime: 1556064695056}

```text
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _protocolAvailableSuggestionSet (package:analysis_server/src/domains/completion/available_suggestions.dart:141:35)
#2      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:75:14)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:76:8)
#6      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:482:11)
#7      _rootRunUnary (dart:async/zone.dart:1136:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "C:\\git\\secret_directory_name\\examples\\filipino_cuisine",
        "explicitFileCount": 3,
        "implicitFileCount": 2091,
        "workItemQueueLength": 3,
        "cacheEntryExceptions": []
    }
]
```

**Comment by devoncarew** [comment]
@scheglov @stereotype441 this is a crash from a recent Dart SDK, so likely still relevant (and w/ accurate the line numbers).

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/100461

**Comment by stereotype441** [comment]
For the record, here's @scheglov's analysis of what would likely trigger this exception: "It happened when something was a library, and then became a part, e.g. when you write "part of" in an empty file. I think it happens only once for such situation, i.e. does not stick in the invalid state, because subsequent changes see it as a part and ignore."
