### ISSUE TITLE
string out of bounds in AstBuilder.endLiteralString / unescapeLastStringPart (2.2.0-edge.)

### ISSUE THREAD

**Issue by pcccccc** [dart-lang/sdk#36742]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.6707.61`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IU-191.6707.61, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1920x1080, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Captured exception
RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core/runtime/libstring_patch.dart:387:7)
#1      unescapeLastStringPart (package:front_end/src/fasta/quote.dart:132:24)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:257:17)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4797:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4722:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3997:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3930:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3742:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:4912:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4884:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4865:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4844:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4580:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3991:14)
#15     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3783:21)
#16     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#17     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3679:13)
#18     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5191:16)
#19     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3513:14)
#20     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#21     Parser.parseStatementsInSwitchCase (package:front_end/src/fasta/parser/parser.dart:5934:17)
#22     Parser.parseSwitchBlock (package:front_end/src/fasta/parser/parser.dart:5893:15)
#23     Parser.parseSwitchStatement (package:front_end/src/fasta/parser/parser.dart:5824:13)
#24     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3543:14)
#25     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#26     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3408:15)
#27     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3062:15)
#28     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2932:15)
#29     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2737:15)
#30     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1761:13)
#31     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1721:14)
#32     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:573:14)
#33     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:465:14)
#34     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#35     ParserAdapter.parseCompilationUnit2 (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analyzer/lib/src/generated/parser_fasta.dart:189:32)
#36     ParserAdapter.parseCompilationUnit (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analyzer/lib/src/generated/parser_fasta.dart:184:12)
#37     _File._parse (package:analyzer/src/services/available_declarations.dart:1354:23)
#38     _File.refresh (package:analyzer/src/services/available_declarations.dart:984:30)
#39     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:608:12)
#40     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:473:7)
#41     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:177:13)
<asynchronous suspension>
#42     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#43     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#44     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#45     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#46     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#47     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _runZoned (dart:async/zone.dart:1516:10)
#51     runZoned (dart:async/zone.dart:1463:12)
#52     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#53     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#54     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#55     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#56     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#57     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#58     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#59     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/8s/kg89zqss193btvf6zcrnz9vm0000gn/T/report2.txt.

**Comment by devoncarew** [comment]
cc @danrubel @kmillikin

**Comment by danrubel** [comment]
The stack trace looks very similar to https://github.com/dart-lang/sdk/issues/35900, so I think that this has been fixed by https://dart-review.googlesource.com/c/sdk/+/95043. Please re-open if this is not the case
