### ISSUE TITLE
xx

### ISSUE THREAD

**Issue by 1149897313** [dart-lang/sdk#36743]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `1.24.2`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Administrator\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Analysis failed: D:\flutter\flutter_wanandroid-master\test\widget_test.dart
Invalid argument(s): Cannot serialize an instance of GenericFunctionTypeImpl
#0      AbstractConstExprSerializer.serializeTypeName (package:analyzer/src/summary/summarize_const_expr.dart:211)
#1      AbstractConstExprSerializer._serializeListLiteral (package:analyzer/src/summary/summarize_const_expr.dart:550)
#2      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:356)
#3      AbstractConstExprSerializer.serialize (package:analyzer/src/summary/summarize_const_expr.dart:139)
#4      _SummarizeAstVisitor.serializeConstExpr (package:analyzer/src/summary/summarize_ast.dart:557)
#5      _SummarizeAstVisitor.serializeFunctionBody (package:analyzer/src/summary/summarize_ast.dart:755)
#6      _SummarizeAstVisitor.serializeInitializerFunction (package:analyzer/src/summary/summarize_ast.dart:828)
#7      _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:1029)
#8      _SummarizeAstVisitor.visitFieldDeclaration (package:analyzer/src/summary/summarize_ast.dart:1210)
#9      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399)
#10     _SummarizeAstVisitor.serializeClass (package:an

**Comment by devoncarew** [comment]
Thanks for the report! The sdk version - `SDK version 1.24.2` - is pretty old; closing as this isn't something we'll take action on.
