### ISSUE TITLE
RangeError from ExprBuilder._buildArguments / SummaryResynthesizerContext (2.2.0-edge)

### ISSUE THREAD

**Issue by Snsaiu** [dart-lang/sdk#36753]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.5429.30.34.5452501`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-183.5429.30.34.5452501, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1368x912`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: C:\Users\Saiu\Dev\Gitee\HeyPiPiMobile\PiPi_Mobile\lib\helper\StyleHelper.dart context: exception_20190426_024837_155
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libarray.dart:161:52)
#1      ExprBuilder._buildArguments (package:analyzer/src/summary/expr_builder.dart:305:34)
#2      ExprBuilder._pushInvokeMethodRef (package:analyzer/src/summary/expr_builder.dart:680:34)
#3      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:179:11)
#4      _UnitResynthesizer._buildConstExpression (package:analyzer/src/summary/resynthesize.dart:1607:47)
#5      SummaryResynthesizerContext.buildExpression (package:analyzer/src/summary/resynthesize.dart:422:30)
#6      _ConstFieldElementImpl&FieldElementImpl&ConstVariableElement.constantInitializer (package:analyzer/src/dart/element/element.dart:2308:14)
#7      ConstantEvaluationEngine.computeDependencies (package:analyzer/src/dart/constant/evaluation.dart:307:41)
#8      _ConstantNode.computeDependencies (package:analyzer/src/dart/constant/compute.dart:59:22)
#9      Node.getDependencies (package:analyzer/src/summary/link.dart:4097:40)
#10     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2170:40)
#11     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#12     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#13     computeConstants (package:analyzer/src/dart/constant/compute.dart:38:41)
#14     LibraryAnalyzer._computeConstants (package:analyzer/src/dart/analysis/library_analyzer.dart:187:5)
#15     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:125:5)
#16     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#19     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1438:63)
#20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#21     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1216:17)
<asynchronous suspension>
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#24     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#25     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#26     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#27     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#28     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#34     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#35     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#36     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#37     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#38     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#39     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\Saiu\AppData\Local\Temp\report1.txt.

**Comment by srawlins** [comment]
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).
