### ISSUE TITLE
dart analysis server has terminated frequently [VS Code]

### ISSUE THREAD

**Issue by diegoeddy** [dart-lang/sdk#36764]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.6707.61`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IU-191.6707.61, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1920x1080, 2560x1440  Retina`

console displayed: nw_path_close_fd Failed to close guarded necp fd 8 [9: Bad file descriptor]

**Comment by diegoeddy** [comment]
When I opened the project with VSCode, it shows the log:

[18:03:12 GMT+0800 (CST)] [General] [Info] Activating Flutter extension for Flutter project...
[18:03:27 GMT+0800 (CST)] [General] [Error] [Analyzer] Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
[18:03:43 GMT+0800 (CST)] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:406:19)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at Analyzer.sendMessage (/Users/siyuaniosdeveloper/.vscode/extensions/dart-code.dart-code-2.25.1/out/src/services/stdio_service.js:72:28)
	at Analyzer.sendMessage (/Users/siyuaniosdeveloper/.vscode/extensions/dart-code.dart-code-2.25.1/out/src/analysis/analyzer.js:109:19)
	at sendRequest.Promise (/Users/siyuaniosdeveloper/.vscode/extensions/dart-code.dart-code-2.25.1/out/src/services/stdio_service.js:64:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/Users/siyuaniosdeveloper/.vscode/extensions/dart-code.dart-code-2.25.1/out/src/services/stdio_service.js:57:16)
	at Analyzer.editGetFixes (/Users/siyuaniosdeveloper/.vscode/extensions/dart-code.dart-code-2.25.1/out/src/analysis/analyzer_gen.js:528:21)
	at provideCodeActions.Promise (/Users/siyuaniosdeveloper/.vscode/extensions/dart-code.dart-code-2.25.1/out/src/providers/fix_code_action_provider.js:18:27)
	at new Promise (<anonymous>)
	at FixCodeActionProvider.provideCodeActions (/Users/siyuaniosdeveloper/.vscode/extensions/dart-code.dart-code-2.25.1/out/src/providers/fix_code_action_provider.js:17:16)
	at define.provideCodeActions.a.asPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:587:847)
	at t.asPromise.Promise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:49:430)
	at new Promise (<anonymous>)
	at Object.t.asPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:49:402)
	at D.provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/ex…

**Comment by devoncarew** [comment]
It looks like this exception is coming from VS Code itself - the dart plugin.

Through this error (from the analysis server and the underlying VM?) looks suspicious '[Analyzer] Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.'.

**Comment by devoncarew** [comment]
cc @DanTup

**Comment by devoncarew** [comment]
Adding the analyzer label for now until we move the issue.
