### ISSUE TITLE
bad state: Too many elements from ExprBuilder.build / DependencyWalker (2.2.0-edge)

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#36767]
This occurred twice when I opened the flutter_gallery project using Flutter SDK v1.2.1. I had enabled the experimental option to do Gradle analysis, but that shouldn't affect Dart.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA 191.6183.87.35.5487692`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-191.6183.87.35.5487692, JRE 1.8.0_202-release-1483-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: /Users/messick/src/flutter/flutter/examples/flutter_gallery/test/demo/material/drawer_demo_test.dart context: exception_20190426_062141_691
Bad state: Too many elements
#0      List.single (dart:core/runtime/libgrowable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2526:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5121:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1640:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#18     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#19     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#20     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#21     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#22     _relink (package:analyzer/src/summary/link.dart:305:57)
#23     link (package:analyzer/src/summary/link.dart:123:3)
#24     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#25     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#26     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1624:23)
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#44     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#45     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#46     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#47     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#48     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/yg/474plv091g1cqnz98j05v0y4003j5d/T/report1.txt.

```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: ...src/flutter/flutter/examples/flutter_gallery/test/demo/material/drawer_demo_test.dart context: exception_20190426_062141_691
Bad state: Too many elements
#0      List.single (dart:core/runtime/libgrowable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2526:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5121:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1640:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#18     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#19     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#20     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#21     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#22     _relink (package:analyzer/src/summary/link.dart:305:57)
#23     link (package:analyzer/src/summary/link.dart:123:3)
#24     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#25     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#26     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1624:23)
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#44     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#45     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#46     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#47     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#48     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
```
1556284895181 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1321,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/simple_smoke_test.da
1556284895187 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1322,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/live_smoketest.dart"
1556284895194 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1323,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/drawer_test.dart","i
1556284895200 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1324,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/pesto_test.dart","it
1556284895201 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1325,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/smoke_test.dart","it
1556284895207 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1326,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/example_code_parser_
1556284895209 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1327,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/calculator/logic.dar
1556284895216 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1328,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/calculator/smoke_tes
1556284895224 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1329,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/flutter_test_config.
1556284895230 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1330,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/update_test.dart","i
1556284895232 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1331,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/demo/material/drawer
1556284895239 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1332,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/demo/material/text_f
1556284895241 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1333,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/demo/material/chip_d
1556284895246 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1334,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test/demo/material/expans
1556284895248 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1335,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_p
1556284895253 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1336,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_p
1556284895255 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1337,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test_driver/scroll_perf_t
1556284895260 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1338,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_p
1556284895262 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1339,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test_driver/scroll_perf.d
1556284895271 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1340,"uri":"file://...src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_p
1556284896637 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: ...src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_perf_test.dart contex
1556284897366 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: ...src/flutter/flutter/examples/flutter_gallery/test_driver/scroll_perf.dart context: excepti
1556284897801 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: ...src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_perf_with_semantics.d
1556284898212 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: ...src/flutter/flutter/examples/flutter_gallery/test_driver/scroll_perf_test.dart context: ex
1556284898928 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: ...src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_perf.dart context: ex
1556284899401 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: ...src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_perf_with_semantics_t
1556284899907 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: ...src/flutter/flutter/examples/flutter_gallery/test/demo/material/expansion_panels_demo_test
1556284900678 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: ...src/flutter/flutter/examples/flutter_gallery/test/demo/material/chip_demo_test.dart contex
1556284901310 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: ...src/flutter/flutter/examples/flutter_gallery/test/demo/material/text_form_field_demo_test.
1556284901787 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: ...src/flutter/flutter/examples/flutter_gallery/test/demo/material/drawer_demo_test.dart cont
```

**Comment by stevemessick** [comment]
Forgot to mention: my copy of flutter_gallery came from my local Flutter repo, which is sync'd to master (not 1.2.1). Feel free to close this if that kind of incompatibility isn't interesting.

**Comment by devoncarew** [comment]
@stereotype441, this looks like it's from a recent build, and we've seen at least two reports of this from users.

**Comment by stereotype441** [comment]
Actually the build is from Feb 12 (2.5 months ago).  I suspect this is a bug in summaries that was later fixed.  @stevemessick would you mind rechecking with a more recent build (preferably one of the Dart 2.3 build candidates)?

**Comment by devoncarew** [comment]
@stereotype441, this is almost certainly from the last stable flutter release.

> I suspect this is a bug in summaries that was later fixed.

We should keep this open until the next flutter stable release, and see if there continue to be reports of this.

**Comment by srawlins** [comment]
This issue was reported _a lot_ during 2.2.0 and 2.2.1, but never since then. Closing this as stale; please re-open if you encounter this on the latest version of Dart (or Flutter).
