### ISSUE TITLE
Dart analysis server: type 'IfElementImpl' is not a subtype of type 'Expression'

### ISSUE THREAD

**Issue by matthewlloyd** [dart-lang/sdk#36772]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.6707.61`
- `2.2.1-edge.7adad2a245bf526675ec2fbf7d11382f238ac5a5`
- `IC-191.6707.61, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.7adad2a245bf526675ec2fbf7d11382f238ac5a5, server version 1.26.0, error: Failed to send notification
type 'IfElementImpl' is not a subtype of type 'Expression'
#0      FlutterOutlineComputer._createOutline (package:analysis_server/src/flutter/flutter_outline_computer.dart:205:42)
#1      FlutterOutlineComputer._createOutline (package:analysis_server/src/flutter/flutter_outline_computer.dart:197:23)
#2      FlutterOutlineComputer._createOutline (package:analysis_server/src/flutter/flutter_outline_computer.dart:197:23)
#3      _FlutterOutlineBuilder.visitExpression (package:analysis_server/src/flutter/flutter_outline_computer.dart:378:28)
#4      GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:370:7)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5998:15)
#6      ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8539:18)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:438:10)
#8      GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:510:39)
#9      GeneralizingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:482:51)
#10     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8535:49)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7571:20)
#12     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1122:17)
#13     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:438:10)
#14     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:510:39)
#15     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#16     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1118:49)
#17     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1077:13)
#18     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:438:10)
#19     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:317:45)
#20     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:55)
#21     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1073:49)
#22     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7011:12)
#23     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:438:10)
#24     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:137:47)
#25     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:230:43)
#26     GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:186:43)
#27     GeneralizingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:412:55)
#28     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7002:49)
#29     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7571:20)
#30     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1591:13)
#31     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:438:10)
#32     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:137:47)
#33     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:230:43)
#34     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:205:7)
#35     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:423:7)
#36     GeneralizingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:184:7)
#37     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1561:49)
#38     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7571:20)
#39     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2173:21)
#40     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:438:10)
#41     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:51)
#42     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2152:49)
#43     FlutterOutlineComputer.compute (package:analysis_server/src/flutter/flutter_outline_computer.dart:66:23)
#44     sendFlutterNotificationOutline.<anonymous closure> (package:analysis_server/src/flutter/flutter_notifications.dart:14:48)
#45     _sendNotification.<anonymous closure> (package:analysis_server/src/flutter/flutter_notifications.dart:31:8)
#46     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#47     _sendNotification (package:analysis_server/src/flutter/flutter_notifications.dart:29:39)
#48     sendFlutterNotificationOutline (package:analysis_server/src/flutter/flutter_notifications.dart:12:3)
#49     ServerContextManagerCallbacks.addAnalysisDriver.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:899:13)
#50     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#51     _rootRun (dart:async/zone.dart:1120:38)
#52     _CustomZone.run (dart:async/zone.dart:1021:19)
#53     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#54     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#55     _rootRun (dart:async/zone.dart:1124:13)
#56     _CustomZone.run (dart:async/zone.dart:1021:19)
#57     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#58     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#59     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#60     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

1556299019125 <= {"event":"analysis.outline","params":{"file":"/<redacted>/redacted.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","n
1556299019125 <= {"event":"analysis.overrides","params":{"file":"/<redacted>/redacted.dart","overrides":[{"offset":1046,"length":5,"superclassMember":{"eleme
1556299019128 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":830,"uri":"package:flutter_app/redacted.dart","items":[{"label":"CustomListTile","element":{"kind":"
1556299019128 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1556299019128 <= {"event":"analysis.implemented","params":{"file":"/<redacted>/redacted.dart","classes":[],"members":[]}}
1556299019242 => {"id":"1718","method":"analysis.updateContent","params":{"files":{"/<redacted>/redacted.dart":{"type":"remove"}}},"clientRequestTime":155629
1556299019250 <= {"id":"1718","result":{}}
1556299019250 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1556299019324 <= {"event":"analysis.errors","params":{"file":"/<redacted>/redacted.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/User
1556299019332 <= {"event":"analysis.highlights","params":{"file":"/<redacted>/redacted.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":40},{"type":"
1556299019353 <= {"event":"analysis.navigation","params":{"file":"/<redacted>/redacted.dart","regions":[{"offset":7,"length":32,"targets":[0]},{"offset":48,"
1556299019353 <= {"event":"analysis.closingLabels","params":{"file":"/<redacted>/redacted.dart","labels":[{"offset":1087,"length":1074,"label":"GestureDetect
1556299019355 <= {"event":"analysis.outline","params":{"file":"/<redacted>/redacted.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","n
1556299019356 <= {"event":"analysis.overrides","params":{"file":"/<redacted>/redacted.dart","overrides":[{"offset":1046,"length":5,"superclassMember":{"eleme
1556299019364 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":830,"uri":"package:flutter_app/redacted.dart","items":[{"label":"CustomListTile","element":{"kind":"
1556299019368 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1556299019368 <= {"event":"analysis.implemented","params":{"file":"/<redacted>/redacted.dart","classes":[],"members":[]}}
1556299129964 => {"id":"1719","method":"edit.getAssists","params":{"file":"/<redacted>/redacted.dart","offset":12077,"length":0},"clientRequestTime":15562991
1556299129967 <= {"id":"1719","result":{"assists":[]}}
1556299165684 => {"id":"1720","method":"analysis.getHover","params":{"file":"/<redacted>/redacted.dart","offset":12079},"clientRequestTime":1556299165684}
1556299165688 <= {"id":"1720","result":{"hovers":[{"offset":12079,"length":15,"containingLibraryPath":"/Users/redacted/flutter/bin/cache/pkg/sky_engine/lib/core/core.dart","containingLibraryName":"dart.cor
1556299285652 => {"id":"1721","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":["/<redacted>/redacted.dart"]}}}
1556299285655 <= {"id":"1721"}
1556299285656 <= {"event":"analysis.errors","params":{"file":"/<redacted>/redacted.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/User
1556299285664 <= {"event":"analysis.highlights","params":{"file":"/<redacted>/redacted.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":40},{"type":"
1556299285670 <= {"event":"analysis.navigation","params":{"file":"/<redacted>/redacted.dart","regions":[{"offset":7,"length":32,"targets":[0]},{"offset":48,"
1556299285671 <= {"event":"analysis.closingLabels","params":{"file":"/<redacted>/redacted.dart","labels":[{"offset":1087,"length":1074,"label":"GestureDetect
1556299285673 <= {"event":"analysis.outline","params":{"file":"/<redacted>/redacted.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","n
1556299285673 <= {"event":"analysis.overrides","params":{"file":"/<redacted>/redacted.dart","overrides":[{"offset":1046,"length":5,"superclassMember":{"eleme
1556299285685 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to send notification","stackTrace":"type 'IfElementImpl' is not a subtype of type 'Expression'\n#0      FlutterOutl
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/100629
