### ISSUE TITLE
exception thrown while listing directories in setAnalysisRoots (2.2.0-edge)

### ISSUE THREAD

**Issue by diegoeddy** [dart-lang/sdk#36785]
## Version information

- `IDEA IU-191.6707.61`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IU-191.6707.61, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1920x1080, 2560x1440  Retina`

## Exception

Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: FileSystemException(path=/Users/siyuaniosdeveloper/Documents/codeSpace/openfire/ios/Pods/Headers/Public/Chilkat/CkoPfx.h; message=Directory listing failed)

```
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:334:7)
#1      _OverlayFolder.getChildren (package:analyzer/file_system/overlay_file_system.dart:334:10)
#2      ContextRootImpl._includedFilesInFolder (package:analyzer/src/dart/analysis/context_root.dart:79:38)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:145:32)
#5      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:145:32)
#6      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:145:32)
#7      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:145:32)
#8      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:145:32)
#9      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:145:32)
#10     DeclarationsContext._scheduleContextFiles (package:analyzer/src/services/available_declarations.dart:326:22)
#11     DeclarationsTracker.addContext (package:analyzer/src/services/available_declarations.dart:432:25)
#12     AnalysisServer._addContextsToDeclarationsTracker (package:analysis_server/src/analysis_server.dart:712:29)
#13     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:529:5)
#14     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:393:14)
#15     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:322:16)
#16     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:349:45)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:345:50)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1500:12)
#23     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:344:5)
#24     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#26     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#27     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#36     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#37     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#38     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#47     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#48     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#49     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#50     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#51     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#52     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#53     _rootRunUnary (dart:async/zone.dart:1132:38)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#58     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#59     _StreamController._add (dart:async/stream_controller.dart:640:7)
#60     _StreamController.add (dart:async/stream_controller.dart:586:5)
#61     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#62     _rootRunUnary (dart:async/zone.dart:1136:13)
#63     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#67     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#68     _StreamController._add (dart:async/stream_controller.dart:640:7)
#69     _StreamController.add (dart:async/stream_controller.dart:586:5)
#70     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1323:33)
#71     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:844:14)
#72     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#73     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#74     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#75     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by devoncarew** [comment]
If we fail while listing some subdirectories, should we silently ignore it (just not traverse into those dirs)? Should we return an error to the client from the `setAnalysisRoots` call?

Currently we're throwing an exception in this case.

**Comment by bwilkerson** [comment]
It is within the spirit of the spec. if we ignore the failure, as long as we check later to see whether it has become possible to traverse the directory.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.3; please re-open if you see this in a recent version of Dart/Flutter.
