### ISSUE TITLE
InconsistentAnalysisException: Requested result might be inconsistent with... during code completion (2.2.0-edge)

### ISSUE THREAD

**Issue by zhangzhenxi** [dart-lang/sdk#36789]
Analyzer Feedback from IntelliJ

flutter doctor -v result :
```
flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/zhenxi/env/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhenxi/env/android/sdk
    • Android NDK at /Users/zhenxi/env/android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/zhenxi/env/android/sdk
    • ANDROID_SDK_ROOT = /Users/zhenxi/env/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.0.3
    • Dart plugin version 191.7019

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 43F7C643-0DBB-4D0D-AC86-7B161501EE4D • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

## Version information

- `IDEA IU-191.6707.61`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IU-191.6707.61, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Failed to handle completion domain request: {id: 569, method: completion.getSuggestionDetails, params: {file: /Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart, id: 409, label: WidgetBuilder, offset: 411}, clientRequestTime: 1556462502697}
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:199:7)
#1      AnalysisSessionImpl.getLibraryByUri (package:analyzer/src/dart/analysis/session.dart:108:5)
<asynchronous suspension>
#2      CompletionDomainHandler.getSuggestionDetails (package:analysis_server/src/domain_completion.dart:179:49)
<asynchronous suspension>
#3      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:210:9)
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _runZoned (dart:async/zone.dart:1516:10)
#7      runZoned (dart:async/zone.dart:1500:12)
#8      CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:206:12)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:349:45)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:345:50)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:344:5)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#52     _StreamController._add (dart:async/stream_controller.dart:640:7)
#53     _StreamController.add (dart:async/stream_controller.dart:586:5)
#54     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#55     _rootRunUnary (dart:async/zone.dart:1136:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#61     _StreamController._add (dart:async/stream_controller.dart:640:7)
#62     _StreamController.add (dart:async/stream_controller.dart:586:5)
#63     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1323:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:844:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#67     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

For additional log information, report.txt: 

```
1556462502837 => {"id":"570","method":"analysis.updateContent","params":{"files":{"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart":{"type":"add","content":"import 'package:cached_network
1556462502853 => {"id":"571","method":"edit.getAssists","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","offset":424,"length":0},"clientRequestTime":1556462502853}
1556462502867 => {"id":"572","method":"analysis.getHover","params":{"file":"/Users/zhenxi/env/flutter/packages/flutter/lib/src/widgets/framework.dart","offset":15026},"clientRequestTime":1556462502867
1556462502945 <= {"id":"567","result":{"hovers":[{"offset":15026,"length":6,"containingLibraryPath":"/Users/zhenxi/env/flutter/packages/flutter/lib/src/widgets/framework.dart","containingLibraryName":
1556462502945 <= {"id":"568","result":{"hovers":[{"offset":15026,"length":6,"containingLibraryPath":"/Users/zhenxi/env/flutter/packages/flutter/lib/src/widgets/framework.dart","containingLibraryName":
1556462502946 <= {"id":"570","result":{}}
1556462502992 <= {"event":"analysis.errors","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/
1556462502994 <= {"id":"571","result":{"assists":[]}}
1556462502996 <= {"event":"analysis.highlights","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":64},{"type":"BUILT_IN
1556462502999 <= {"event":"analysis.navigation","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","regions":[{"offset":7,"length":56,"targets":[0]},{"offset":72,"length":
1556462503000 <= {"event":"analysis.closingLabels","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","labels":[{"offset":546,"length":676,"label":"Card"},{"offset":566,"l
1556462503001 <= {"event":"analysis.outline","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<u
1556462503001 <= {"event":"analysis.overrides","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","overrides":[{"offset":505,"length":5,"superclassMember":{"element":{"kin
1556462503072 => {"id":"573","method":"analysis.getHover","params":{"file":"/Users/zhenxi/env/flutter/packages/flutter/lib/src/widgets/framework.dart","offset":15026},"clientRequestTime":1556462503072
1556462503161 <= {"id":"572","result":{"hovers":[{"offset":15026,"length":6,"containingLibraryPath":"/Users/zhenxi/env/flutter/packages/flutter/lib/src/widgets/framework.dart","containingLibraryName":
1556462503274 => {"id":"574","method":"analysis.updateContent","params":{"files":{"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart":{"type":"add","content":"import 'package:cached_network
1556462503276 => {"id":"575","method":"edit.getAssists","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","offset":425,"length":0},"clientRequestTime":1556462503276}
1556462503370 <= {"id":"573","result":{"hovers":[{"offset":15026,"length":6,"containingLibraryPath":"/Users/zhenxi/env/flutter/packages/flutter/lib/src/widgets/framework.dart","containingLibraryName":
1556462503370 <= {"id":"574","result":{}}
1556462503379 => {"id":"576","method":"analysis.getHover","params":{"file":"/Users/zhenxi/env/flutter/packages/flutter/lib/src/widgets/framework.dart","offset":156941},"clientRequestTime":155646250337
1556462503418 <= {"event":"analysis.errors","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/
1556462503419 <= {"id":"575","result":{"assists":[]}}
1556462503419 <= {"event":"analysis.highlights","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":64},{"type":"BUILT_IN
1556462503421 <= {"event":"analysis.navigation","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","regions":[{"offset":7,"length":56,"targets":[0]},{"offset":72,"length":
1556462503421 <= {"event":"analysis.closingLabels","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","labels":[{"offset":547,"length":676,"label":"Card"},{"offset":567,"l
1556462503422 <= {"event":"analysis.outline","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<u
1556462503423 <= {"event":"analysis.overrides","params":{"file":"/Users/zhenxi/work/wdy/wdy_app/lib/ad/list/item/ad_card.dart","overrides":[{"offset":506,"length":5,"superclassMember":{"element":{"kin
1556462503623 <= {"id":"576","result":{"hovers":[{"offset":156941,"length":13,"containingLibraryPath":"/Users/zhenxi/env/flutter/packages/flutter/lib/src/widgets/framework.dart","containingLibraryName
1556462503626 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1556462503637 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {id: 569, method: completion.getSuggestionDetails, params: {file: /Users/zhenx
```

**Comment by srawlins** [comment]
Thanks for reporting this issue! This has been previously reported at https://github.com/dart-lang/sdk/issues/36618; please follow along there.

**Comment by farhanroy** [comment]
i have same error how to solve it fuck
