### ISSUE TITLE
Dart analysis server: Invalid argument(s): Is a part:

### ISSUE THREAD

**Issue by matthewlloyd** [dart-lang/sdk#36791]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.6707.61`
- `2.2.1-edge.7adad2a245bf526675ec2fbf7d11382f238ac5a5`
- `IC-191.6707.61, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.7adad2a245bf526675ec2fbf7d11382f238ac5a5, server version 1.26.0, error: Failed to handle completion domain request: {id: 1397, method: completion.getSuggestionDetails, params: {file: <redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart, id: 332, label: BoxShape.circle, offset: 9501}, clientRequestTime: 1556473514767}
Invalid argument(s): Is a part: <redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart
#0      AnalysisDriver.getResolvedLibrary (package:analyzer/src/dart/analysis/driver.dart:858:7)
#1      AnalysisSessionImpl.getResolvedLibrary (package:analyzer/src/dart/analysis/session.dart:151:20)
#2      CompletionDomainHandler.getSuggestionDetails (package:analysis_server/src/domain_completion.dart:205:45)
<asynchronous suspension>
#3      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:271:9)
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _runZoned (dart:async/zone.dart:1516:10)
#7      runZoned (dart:async/zone.dart:1500:12)
#8      CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:267:12)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:337:45)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:50)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:332:5)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#52     _StreamController._add (dart:async/stream_controller.dart:640:7)
#53     _StreamController.add (dart:async/stream_controller.dart:586:5)
#54     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#55     _rootRunUnary (dart:async/zone.dart:1136:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#61     _StreamController._add (dart:async/stream_controller.dart:640:7)
#62     _StreamController.add (dart:async/stream_controller.dart:586:5)
#63     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

1556473512629 <= {"event":"analysis.navigation","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","regions":[{"offset":174,
1556473512629 <= {"event":"analysis.closingLabels","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","labels":[]}}
1556473512630 <= {"event":"analysis.outline","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","kind":"PART","libraryName":
1556473512630 <= {"event":"analysis.overrides","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","overrides":[]}}
1556473512632 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1556473512632 <= {"event":"analysis.implemented","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","classes":[],"members":[
1556473512876 => {"id":"1391","method":"edit.getAssists","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","offset":9500,"l
1556473512878 <= {"id":"1391","result":{"assists":[]}}
1556473512893 => {"id":"1392","method":"edit.getFixes","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","offset":9492},"cl
1556473512974 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 1392, method: edit.getFixes, params: {file: <redacted>/flutter_app/p
1556473513687 => {"id":"1393","method":"edit.getFixes","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","offset":9501},"cl
1556473513756 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 1393, method: edit.getFixes, params: {file: <redacted>/flutter_app/p
1556473513795 => {"id":"1394","method":"edit.getAssists","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","offset":9501,"l
1556473513797 <= {"id":"1394","result":{"assists":[]}}
1556473513936 => {"id":"1395","method":"analysis.updateContent","params":{"files":{"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart":{"type"
1556473513936 => {"id":"1396","method":"completion.getSuggestions","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","offse
1556473513936 <= {"id":"1395","result":{}}
1556473513937 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1556473513959 <= {"id":"1396","result":{"id":"355"}}
1556473513960 <= {"event":"analysis.errors","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","errors":[{"severity":"ERROR"
1556473513962 <= {"event":"completion.results","params":{"id":"355","replacementOffset":9501,"replacementLength":1,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"hashCode","selectionOf
1556473513963 <= {"event":"analysis.highlights","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","regions":[{"type":"DIREC
1556473513965 <= {"event":"analysis.navigation","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","regions":[{"offset":174,
1556473513965 <= {"event":"analysis.closingLabels","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","labels":[]}}
1556473513966 <= {"event":"analysis.outline","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","kind":"PART","libraryName":
1556473513966 <= {"event":"analysis.overrides","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","overrides":[]}}
1556473513968 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1556473513969 <= {"event":"analysis.implemented","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart","classes":[],"members":[
1556473514767 => {"id":"1397","method":"completion.getSuggestionDetails","params":{"file":"<redacted>/flutter_app/plugins/packages/google_maps_flutter/lib/src/google_map.dart",
1556473514770 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {id: 1397, method: completion.getSuggestionDetails, params: {file: /Users/
```

**Comment by srawlins** [comment]
Thanks for reporting this issue! This has been previously been reported  in https://github.com/dart-lang/sdk/issues/36566; follow along there.
