### ISSUE TITLE
co19_2/LibTest/io/WebSocket/pingInterval_A01_t01 fails on vm-kernel-mac-debug-simdbc64 bot

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#36805]
```
  /=============================================================================================\
  | co19_2/LibTest/io/WebSocket/pingInterval_A01_t01 failed again (RuntimeError, expected Pass) |
  \=============================================================================================/
  --- Command "vm_compile_to_kernel []" (took 832ms):
  DART_CONFIGURATION=DebugSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/DebugSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_WebSocket_pingInterval_A01_t01/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/WebSocket/pingInterval_A01_t01.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true
  exit code:
  0
  --- Command "vm" (took 03.000729s):
  DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_WebSocket_pingInterval_A01_t01/out.dill
  exit code:
  255
  stderr:
  Unhandled exception:
  Bad state: Cannot add event after closing
  #0      _StreamController.add (dart:async/stream_controller.dart:585:24)
  #1      _WebSocketConsumer.add (dart:_http/websocket_impl.dart:953:17)
  #2      _WebSocketImpl.pingInterval=.<anonymous closure> (dart:_http/websocket_impl.dart:1198:17)
  #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
  #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
  #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
  #6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
  --- Re-run this test:
  python tools/test.py -n dartk-mac-debug-simdbc64 co19_2/LibTest/io/WebSocket/pingInterval_A01_t01
```

This test was failing for a while, but it was previously treated as flaky. Now our testing infra decided that it is no longer flaky and turned bot red. We need to investigate why it fails on that bot and whether this failure is a real bug or a problem in a test.

/cc @whesse

**Comment by alexmarkov** [comment]
In status files this test was marked as `RuntimeError, Pass` since
https://dart-review.googlesource.com/c/sdk/+/79661

/cc @athomas

**Comment by alexmarkov** [comment]
`simdbc64` architecture was discontinued.
