### ISSUE TITLE
DBC crashes with --profiler --profile-vm=false

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#36830]
./out/ReleaseSIMDBC64/dart --profiler --profile-vm=false ~/hello.dart

```
Thread 4 "dart" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff623f700 (LWP 144140)]
dart::ProfilerDartStackWalker::CallerPC (this=<optimized out>, interp=<optimized out>) at ../../runtime/vm/profiler.cc:670
670	    return reinterpret_cast<uword*>(*caller_pc_ptr);
(gdb) bt
#0  dart::ProfilerDartStackWalker::CallerPC (this=<optimized out>, interp=<optimized out>) at ../../runtime/vm/profiler.cc:670
#1  dart::ProfilerDartStackWalker::walk (this=0x7ffff623cdd8) at ../../runtime/vm/profiler.cc:653
#2  0x0000555556d3955c in dart::CollectSample (sample=<optimized out>, native_stack_walker=<optimized out>, pc=<optimized out>, fp=0, 
    sp=<optimized out>, counters=<optimized out>, isolate=<optimized out>, exited_dart_code=<optimized out>, 
    in_dart_code=<optimized out>, dart_stack_walker=<optimized out>) at ../../runtime/platform/atomic_linux.h:34
#3  dart::Profiler::SampleThread (thread=0x555557cb1200, state=...) at ../../runtime/vm/profiler.cc:1413
#4  0x0000555556dcd0b6 in dart::ThreadInterrupterLinux::ThreadInterruptSignalHandler (signal=<optimized out>, info=<optimized out>, 
    context_=<optimized out>) at ../../runtime/vm/thread_interrupter_linux.cc:43
#5  <signal handler called>
#6  dart::Simulator::Call (this=<optimized out>, code=..., arguments_descriptor=..., arguments=..., thread=<optimized out>)
    at ../../runtime/vm/simulator_dbc.cc:1845
#7  0x0000555556c2eb01 in dart::DartEntry::InvokeFunction (function=..., arguments=..., arguments_descriptor=..., 
    current_sp=<optimized out>) at ../../runtime/vm/dart_entry.cc:188
#8  0x0000555556c31ed6 in dart::DartLibraryCalls::HandleMessage (handler=..., message=...) at ../../runtime/vm/dart_entry.cc:691
#9  0x0000555556c64efb in dart::IsolateMessageHandler::HandleMessage (this=0x555557c901c0, message=0x555557c46100)
    at ../../runtime/vm/isolate.cc:635
#10 0x0000555556c96c6e in dart::MessageHandler::HandleMessages (this=0x555557c901c0, ml=0x7ffff623ed60, allow_normal_messages=false, 
    allow_multiple_normal_messages=<optimized out>) at ../../runtime/vm/message_handler.cc:217
#11 0x0000555556c972b6 in dart::MessageHandler::TaskCallback (this=0x555557c901c0) at ../../runtime/vm/message_handler.cc:417
#12 0x0000555556dcdbc7 in dart::ThreadPool::Worker::Loop (this=0x555557c3a000) at ../../runtime/vm/thread_pool.cc:381
#13 0x0000555556dcda82 in dart::ThreadPool::Worker::Main (args=93825033019392) at ../../runtime/vm/thread_pool.cc:436
#14 0x0000555556d34989 in dart::ThreadStart (data_ptr=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:134
#15 0x00007ffff79bf494 in start_thread (arg=0x7ffff623f700) at pthread_create.c:333
#16 0x00007ffff71f5a8f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by sjindel-google** [comment]
DBC is obsolete.
