### ISSUE TITLE
triple shift assignment operator in DDC runtime

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#36847]
After landing a fix for [triple shift compilation error](https://dart-review.googlesource.com/c/sdk/+/101223), these tests which were failing with CompilationError are now failing with RuntimeError:

* dartdevc-checked-linux-release-chrome:co19_2/Language/Expressions/Assignment/Compound_Assignment/expression_assignment_t12 failed again (CompileTimeError -> RuntimeError, expected Pass)
* dartdevc-checked-linux-release-chrome:co19_2/Language/Expressions/Assignment/Compound_Assignment/indexed_expression_assignment_t12 failed again (CompileTimeError -> RuntimeError, expected Pass)

--- Command "dartdevc" (took 156ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartdevc --enable-experiment=triple-shift --library-root /b/s/w/ir/tests/co19_2/src/Language/Expressions/Assignment/Compound_Assignment --ignore-unrecognized-flags --no-summarize --no-source-map -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartdevc-checked-sdk/tests_co19_2_src_Language_Expressions_Assignment_Compound_Assignment_expression_assignment_t12/expression_assignment_t12.js /b/s/w/ir/tests/co19_2/src/Language/Expressions/Assignment/Compound_Assignment/expression_assignment_t12.dart -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg/async_helper.sum=async_helper -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg/collection.sum=collection -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg/expect.sum=expect -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg/js.sum=js -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg/matcher.sum=matcher -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg/meta.sum=meta -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg/path.sum=path -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg/stack_trace.sum=stack_trace -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg/unittest.sum=unittest (working directory: /b/s/w/ir/tests/co19_2/src/Language/Expressions/Assignment/Compound_Assignment)

exit code:
0

--- Command "chrome" (took 234ms):
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart tools/testing/dart/launch_browser.dart chrome http://127.0.0.1:38999/root_build/generated_tests/dartdevc-chrome-checked-sdk/tests_co19_2_src_Language_Expressions_Assignment_Compound_Assignment_expression_assignment_t12/test.html?crossOriginPort=38223

Runtime error:
Error: NoSuchMethodError: method not found: '>>>'
Receiver: 3
Arguments: [3]
Receiver: 3
Arguments: [3]
    at Object.dart.throw (http://127.0.0.1:38999/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4559:11)
    at Object.dart.defaultNoSuchMethod (http://127.0.0.1:38999/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4992:15)
    at Number.noSuchMethod (http://127.0.0.1:38999/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:5093:19)
    at Object.dart.noSuchMethod (http://127.0.0.1:38999/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4988:30)
    at Object.dart.callMethod (http://127.0.0.1:38999/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4795:19)
    at Object.dart.dsend (http://127.0.0.1:38999/root_build/gen/utils/dartdevc/js/amd/dart_sdk.js:4803:17)
    at Object.expression_assignment_t12.check (http://127.0.0.1:38999/root_dart/out/ReleaseX64/generated_compilations/dartdevc-checked-sdk/tests_co19_2_src_Language_Expressions_Assignment_Compound_Assignment_expression_assignment_t12/expression_assignment_t12.js:105:25)
    at Object.expression_assignment_t12.main (http://127.0.0.1:38999/root_dart/out/ReleaseX64/generated_compilations/dartdevc-checked-sdk/tests_co19_2_src_Language_Expressions_Assignment_Compound_Assignment_expression_assignment_t12/expression_assignment_t12.js:113:31)
    at testMainWrapper (http://127.0.0.1:38999/root_build/generated_tests/dartdevc-chrome-checked-sdk/tests_co19_2_src_Language_Expressions_Assignment_Compound_Assignment_expression_assignment_t12/test.html?crossOriginPort=38223:104:70)

exit code:
0

--- To debug locally, run:
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/tools/testing/dart/http_server.dart -p 38999 -c 38223 --network 127.0.0.1 --build-directory=/b/s/w/ir/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/.packages

--- Re-run this test:
python tools/test.py -n dartdevc-checked-linux-release-chrome co19_2/Language/Expressions/Assignment/Compound_Assignment/expression_assignment_t12

**Comment by nshahan** [comment]
The triple shift implementation has finally landed and these tests are now passing.
