### ISSUE TITLE
Analyzer crash if the name `Never` is imported from a user-defined library

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36846]
The following code crashes the analyzer:
```
test.dart:
  import 'declares_never.dart';
  Never f() => throw 'foo';

declares_never.dart:
  class Never {}
```
Stacktrace:
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:530:31)
#2      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:398:15)
#3      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#4      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#6      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#7      Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1065:12)
#8      TypeNameResolver.resolveTypeName (package:analyzer/src/generated/resolver.dart:6339:33)
#9      TypeResolverVisitor.visitTypeName (package:analyzer/src/generated/resolver.dart:8104:23)
#10     TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10078:49)
#11     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4758:18)
#12     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3312:10)
#13     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8073:11)
#14     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3214:59)
#15     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5921:11)
#16     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5914:7)
#17     TypeResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7867:11)
#18     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4753:49)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7570:20)
#20     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2172:21)
#21     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3312:10)
#22     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8073:11)
#23     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:3122:51)
#24     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2151:49)
#25     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:651:10)
#26     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:137:7)
#27     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#28     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:136:11)
#29     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:103:14)
#30     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#31     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:102:43)
#32     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1450:63)
#33     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#34     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1427:20)
#35     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:673:41)
<asynchronous suspension>
#36     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:58)
<asynchronous suspension>
#37     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:169:11)
<asynchronous suspension>
#38     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#39     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:754:21)
#40     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:413:40)
#41     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#44     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#45     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:348:9)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1486:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1427:20)
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:673:41)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:58)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:169:11)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:754:21)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:413:40)
#9      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:348:9)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by stereotype441** [comment]
Bisects to 40a06c3a774a341504e6cbdf74179261876c6695.  @bwilkerson can you take a look?

**Comment by bwilkerson** [comment]
The immediate problem is easy enough to fix, and I have sent out a CL to fix it to unblock the roll, but it raises some questions that I think we should look into.

Why don't we need to special case `dynamic` in a similar way? Does it not appear in the namespace for `dart:core`, or does it somehow have a library associated with it? (I don't think the latter is possible because we have a single instance that's shared across all instantiations of the SDK's element model.)

Are there other places where we're assuming that an element will have a library that need to be similarly updated?

Should we re-work the logic so that we can have multiple instances of these special element classes (dynamic and Never) so that they can have a library associated with them?

**Comment by zanderso** [comment]
This issue is blocking the roll of Flutter into Fuchsia. Please either land the fix, or revert https://github.com/dart-lang/sdk/commit/40a06c3a774a341504e6cbdf74179261876c6695.

**Comment by bwilkerson** [comment]
I am creating a revert.

**Comment by bwilkerson** [comment]
Reverted in the SDK repo as of https://dart-review.googlesource.com/c/sdk/+/101640.

**Comment by bwilkerson** [comment]
The change has been re-landed without the bug that blocked the roll. Let me know if it causes any problem for future rolls.
