### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by CodeJxer** [dart-lang/sdk#36872]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4 unknown, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: /Users/liaozhixin/AndroidStudioProjects/dianqianlife/test/widget_test.dart context: exception_20190507_203237_875
NoSuchMethodError: Class 'LibraryElementInBuildUnit' has no instance getter 'session'.
Receiver: Instance of 'LibraryElementInBuildUnit'
Tried calling: session
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      LibraryElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3736:48)
#2      LibraryElementInBuildUnit.session (package:analyzer/src/dart/element/element.dart:5206:25)
#3      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:542:30)
#4      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:397:15)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:137:27)
#6      Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1063:12)
#7      AstRewriteVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:83:35)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8671:49)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9166:20)
#10     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7947:15)
#11     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3544:10)
#12     UnifyingAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:3505:43)
#13     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7942:49)
#14     ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2535:16)
#15     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#16     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#19     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#20     FunctionElementForLink_Initializer.returnType (package:analyzer/src/summary/link.dart:2852:24)
#21     InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:423:37)
#22     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:303:11)
#23     InstanceMemberInferrer._inferClasses (package:analyzer/src/task/strong_mode.dart:326:9)
#24     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:55:5)
#25     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1638:7)
#26     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#27     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#28     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#29     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#30     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#31     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#32     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#33     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#34     _relink (package:analyzer/src/summary/link.dart:305:57)
#35     link (package:analyzer/src/summary/link.dart:123:3)
#36     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#37     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#38     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#39     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#40     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#41     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#42     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#43     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#44     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#45     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#46     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#47     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#48     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#49     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#50     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#51     _rootRun (dart:async/zone.dart:1124:13)
#52     _CustomZone.run (dart:async/zone.dart:1021:19)
#53     _runZoned (dart:async/zone.dart:1516:10)
#54     runZoned (dart:async/zone.dart:1463:12)
#55     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#56     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#57     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#58     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#59     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#60     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#61     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#62     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/nn/_pvqc65s7ql9h6wmlltzdvnh0000gn/T/report1.txt.

**Comment by parlough** [comment]
This should have been fixed by https://github.com/dart-lang/sdk/commit/7418238239f885ba92093c44a1768f8ec93b121f which is in the latest Dart releases(2.3.0 and up)

**Comment by srawlins** [comment]
Agreed. This issue has not been reported [since May 9](https://github.com/dart-lang/sdk/issues?utf8=%E2%9C%93&q=is%3Aissue+%22%27LibraryElementInBuildUnit%27+has+no+instance+getter+%27session%27.%22+).
