### ISSUE TITLE
dart2js crashes on flutter_web with `-O0`

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#36877]
sdk version: 2.3.0-dev.0.5

The following hello world flutter_web project:

```dart
import 'package:flutter_web/material.dart';
import 'package:flutter_web_ui/ui.dart' as ui;

main() async {
  await ui.webOnlyInitializePlatform();
  runApp(new Text(
    'Hello World',
    textDirection: TextDirection.ltr,
    style: TextStyle(color: Colors.orange),
  ));
}
```

With this pubspec.yaml:

```yaml
name: repro
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web.git
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web.git
      path: packages/flutter_web_ui
```

Gives the following stack trace for `dart2js web/main.dart -o web/main.dart.js -O0`:

```
org-dartlang-sdk:///sdk/lib/html/dart2js/html_dart2js.dart@576354+1:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.3.0-dev.0.5), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: type 'HTypeConversion' is not a subtype of type 'HLocalValue'
#0      HLocalGet.local (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2217:28)
#1      SsaInstructionMerger.isEffectivelyPure (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:661:71)
#2      SsaInstructionMerger.analyzeInputs (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:628:13)
#3      SsaInstructionMerger.visitInstruction (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:680:5)
#4      HBaseVisitor.visitInvokeBinary (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:420:44)
#5      HBaseVisitor.visitRelational (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:427:40)
#6      HBaseVisitor.visitIdentity (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:477:36)
#7      SsaInstructionMerger.visitIdentity (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:734:13)
#8      HIdentity.accept (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2936:39)
#9      SsaInstructionMerger.analyzeInputs (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:648:19)
#10     SsaInstructionMerger.visitInstruction (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:680:5)
#11     HBaseVisitor.visitNot (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:528:26)
#12     HNot.accept (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2821:39)
#13     SsaInstructionMerger.analyzeInputs (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:648:19)
#14     SsaInstructionMerger.visitInstruction (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:680:5)
#15     HBaseVisitor.visitControlFlow (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:425:42)
#16     HBaseVisitor.visitConditionalBranch (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:424:54)
#17     HBaseVisitor.visitIf (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:479:24)
#18     HIf.accept (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2737:39)
#19     SsaInstructionMerger.tryMergingExpressions (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:802:16)
#20     SsaInstructionMerger.visitBasicBlock (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:773:5)
#21     HGraphVisitor.visitDominatorTree (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:136:9)
#22     SsaInstructionMerger.visitGraph (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:615:5)
#23     SsaCodeGenerator.preGenerateMethod.runPhase.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:369:59)
#24     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#25     SsaCodeGenerator.preGenerateMethod.runPhase (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:369:20)
#26     SsaCodeGenerator.preGenerateMethod (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:381:13)
#27     SsaCodeGenerator.visitGraph (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:451:5)
#28     SsaCodeGeneratorTask.generateMethod.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:139:15)
#29     CompilerTask.measure (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:64:51)
#30     SsaCodeGeneratorTask.generateMethod (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:120:12)
#31     SsaCodeGeneratorTask.generateCode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:87:14)
#32     SsaFunctionCompiler.compile (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/ssa.dart:50:38)
#33     JavaScriptBackend.codegen (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/backend.dart:669:26)
#34     KernelCodegenWorkItem.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/js_strategy.dart:164:21)
#35     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:466:70)
#36     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#37     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:466:32)
#38     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#39     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:464:28)
#40     CompilerDiagnosticReporter.withCurrentElement (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:784:15)
#41     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:462:18)
#42     CodegenEnqueuer._forEach (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:257:12)
#43     CodegenEnqueuer.forEach (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:273:5)
#44     Compiler.emptyQueue.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:458:16)
#45     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#46     Compiler.emptyQueue (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:457:14)
#47     Compiler.processQueue.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:483:7)
#48     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#49     Compiler.processQueue (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:476:14)
#50     Compiler.generateJavaScriptCode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:384:5)
#51     Compiler.compileFromKernel.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:429:9)
#52     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#53     Compiler.compileFromKernel (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:403:14)
#54     Compiler.runInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:272:13)
<asynchronous suspension>
#55     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:223:38)
#56     new Future.sync (dart:async/future.dart:224:31)
#57     Compiler.run.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:223:20)
#58     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#59     Compiler.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:220:41)
#60     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/apiimpl.dart:91:22)
#61     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#62     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#63     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#64     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#65     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#66     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#67     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#68     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#69     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:
```

**Comment by jakemac53** [comment]
All other optimization levels appear to work

**Comment by jakemac53** [comment]
cc @kevmoo @sigmundch

**Comment by sigmundch** [comment]
Yes, unfortunately we've had issues with -O0 in the past, we recommend not using it for now (it is mainly used for dart2js developers to debug what happens when we disable basic optimizations, but it is not recommended).  Most people that have used this were trying to turn off minification, if that's the goal, we recommend to use `-O1` or to pass `--no-minify` instead.

I'll close this bug because we are tracking the crash above, here: https://github.com/dart-lang/sdk/issues/35963

**Comment by sigmundch** [comment]
@jakemac53 - I noticed that a lot of users that run into this, they do from webdev. I am guessing it was because they want to try to disable minification. Is there documentation somewhere that may be encouraging them to use `-O0`? If so, could we change it to say `-O1`?
