### ISSUE TITLE
Analysis diagnostic server /contexts does not work in LSP mode

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#36926]
Dart 2.3.0

- Run the analysis server with `--lsp`.
- Start the diagnostic server by making a `dart/diangosticServer` request.
- Navigate to `localhost:<server port>/contexts`

Result:

```
500 Oops
type 'LspAnalysisServer' is not a subtype of type 'AnalysisServer' in type cast

#0      ContextsPage.generateContent (package:analysis_server/src/status/diagnostics.dart:554:41)
<asynchronous suspension>
#1      DiagnosticPageWithNav.generateContainer.<anonymous closure> (package:analysis_server/src/status/diagnostics.dart:703:13)
<asynchronous suspension>
#2      Page.asyncDiv (package:analysis_server/src/status/pages.dart:43:15)
<asynchronous suspension>
#3      DiagnosticPageWithNav.generateContainer (package:analysis_server/src/status/diagnostics.dart:701:11)
<asynchronous suspension>
#4      DiagnosticPage.generatePage (package:analysis_server/src/status/diagnostics.dart:659:11)
<asynchronous suspension>
#5      Page.generate (package:analysis_server/src/status/pages.dart:67:12)
<asynchronous suspension>
#6      Site.handleGetRequest (package:analysis_server/src/status/pages.dart:171:37)
<asynchronous suspension>
#7      HttpAnalysisServer._handleGetRequest (package:analysis_server/src/server/http_server.dart:123:23)
<asynchronous suspension>
#8      HttpAnalysisServer._handleServer.<anonymous closure> (package:analysis_server/src/server/http_server.dart:135:15)
<asynchronous suspension>
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#14     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#15     _StreamController._add (dart:async/stream_controller.dart:640:7)
#16     _StreamController.add (dart:async/stream_controller.dart:586:5)
#17     _HttpServer._handleRequest (dart:_http/http_impl.dart:2656:19)
#18     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2414:19)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#25     _StreamController._add (dart:async/stream_controller.dart:640:7)
#26     _StreamController.add (dart:async/stream_controller.dart:586:5)
#27     _HttpParser._headersEnd (dart:_http/http_parser.dart:372:19)
#28     _HttpParser._doParse (dart:_http/http_parser.dart:701:15)
#29     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#30     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#37     _StreamController._add (dart:async/stream_controller.dart:640:7)
#38     _StreamController.add (dart:async/stream_controller.dart:586:5)
#39     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#40     _rootRunUnary (dart:async/zone.dart:1136:13)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#45     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#46     _StreamController._add (dart:async/stream_controller.dart:640:7)
#47     _StreamController.add (dart:async/stream_controller.dart:586:5)
#48     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#49     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by bwilkerson** [comment]
@DanTup

**Comment by natebosch** [comment]
Caused by https://github.com/dart-lang/sdk/issues/36926

Should be fixed by https://dart-review.googlesource.com/c/sdk/+/102244

**Comment by DanTup** [comment]
Fixed better by https://dart-review.googlesource.com/c/sdk/+/102620 :-)
