### ISSUE TITLE
ReleaseSIMDBC64 fails in service/get_cpu_profile_timeline_rpc_test failed

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36932]
```
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=out/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseSIMDBC64/generated_compilations/dartk/runtime_observatory_tests_service_get_cpu_profile_timeline_rpc_test/out.dill /b/s/w/ir/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 02.000886s):
DART_CONFIGURATION=ReleaseSIMDBC64 out/ReleaseSIMDBC64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseSIMDBC64/generated_compilations/dartk/runtime_observatory_tests_service_get_cpu_profile_timeline_rpc_test/out.dill

exit code:
255

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseSIMDBC64/dart --disable-service-auth-codes --profiler --profiler=true --profile-vm=false --timeline_recorder=ring --timeline_streams=Profiler --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages --enable-vm-service:0 /b/s/w/ir/out/ReleaseSIMDBC64/generated_compilations/dartk/runtime_observatory_tests_service_get_cpu_profile_timeline_rpc_test/out.dill
>testee>out> Observatory listening on http://127.0.0.1:45241/
>testee>err>
>testee>err> ===== CRASH =====
>testee>err> si_signo=Segmentation fault(11), si_code=128, si_addr=(nil)
>testee>err> version=2.3.0-edge.54a541706dcba0659b0d75685f3a6bcbf3007b65 (Sat May 11 00:12:08 2019 +0000) on "linux_dbc"
>testee>err> thread=24225, isolate=vm-service(0x56076fecf200)
>testee>err> Stack dump aborted because GetAndValidateThreadStackBounds failed.
** Killing script
Unexpected exception in service tests: Testee exited with -6
#0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/runtime/observatory/tests/service/test_helper.dart:256:11)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

stderr:
Unhandled exception:
Testee exited with -6
#0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/runtime/observatory/tests/service/test_helper.dart:256:11)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by ZichangG** [comment]
Instead of considering this as a failure, get_cpu_profile_timeline_rpc_test should not run on simdbc.

**Comment by ZichangG** [comment]
all profiler tests should be not be run on simdbc, therefore skip this test.
