### ISSUE TITLE
Exception from analysis server

### ISSUE THREAD

**Issue by sarahec** [dart-lang/sdk#36942]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Opening a Dart file that had previously passed analysis. I had used IntelliJ IDEA briefly,
then the analyzer started crashing so I closed it and returned to VSCode. 

This happens with both the Flutter-supplied 2.3.0 SDK and if I install the current 2.3.0 release
using Homebrew.

(Apologies if this is a duplicate. I haven't seen any other issues with this particular backtrace among the recent ones.)

### Versions

- Flutter SDK 1.5.4-hotfix.2
- Visual Studio Code 1.33.1
- Dart Code 3.0.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/rdclark/development/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.0.1
```

### Exception

Captured exception

```text
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:579:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      Future._propagateToListeners (dart:async/future_impl.dart:555:16)
#3      Future._completeError (dart:async/future_impl.dart:491:5)
#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#5      _Completer.completeError (dart:async/future_impl.dart:27:5)
#6      _AsyncAwaitCompleter.completeError.<anonymous closure> (dart:async-patch/async_patch.dart:43:20)
#7      _rootRun (dart:async/zone.dart:1120:38)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by sarahec** [comment]
Will replace with a better report
