### ISSUE TITLE
Failure in service/get_cpu_profile_timeline_rpc test

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#36948]
The test `service/get_cpu_profile_timeline_rpc_test` finally started failing enough that the `vm-kernel-linux-release-simdbc64` bot went red over the weekend. Before it went red, it had been flaky since commit 5393ce7d3, which modified the test, and so assigning the bug to Ryan. Meanwhile, approving the error to clear the red.

Here's an example [failure log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8914527958128292800/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0):

```
/=======================================================================================\
  | service/get_cpu_profile_timeline_rpc_test broke (Pass -> RuntimeError, expected Pass) |
  \=======================================================================================/

  --- Command "vm_compile_to_kernel []" (took 02.000892s):
  DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=out/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseSIMDBC64/generated_compilations/dartk/runtime_observatory_tests_service_get_cpu_profile_timeline_rpc_test/out.dill /b/s/w/ir/runtime/observatory/tests/service/get_cpu_profile_timeline_rpc_test.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

  exit code:
  0

  --- Command "vm" (took 929ms):
  DART_CONFIGURATION=ReleaseSIMDBC64 out/ReleaseSIMDBC64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseSIMDBC64/generated_compilations/dartk/runtime_observatory_tests_service_get_cpu_profile_timeline_rpc_test/out.dill

  exit code:
  255

  stdout:
  ** Launching SERVICE_TEST_TESTEE=true out/ReleaseSIMDBC64/dart --disable-service-auth-codes --profiler --profiler=true --profile-vm=false --timeline_recorder=ring --timeline_streams=Profiler --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages --enable-vm-service:0 /b/s/w/ir/out/ReleaseSIMDBC64/generated_compilations/dartk/runtime_observatory_tests_service_get_cpu_profile_timeline_rpc_test/out.dill
  >testee>err>
  >testee>err> ===== CRASH =====
  >testee>err> si_signo=Segmentation fault(11), si_code=128, si_addr=(nil)
  >testee>err> version=2.3.0-edge.03776172c120c27af5d9911129c2c2e1b48bed9c (Thu May 2 23:22:33 2019 +0000) on "linux_dbc"
  >testee>err> thread=9324, isolate=kernel-service(0x56205f3a2400)
  >testee>err> Stack dump aborted because GetAndValidateThreadStackBounds failed.
  ** Killing script
  Unexpected exception in service tests: Testee exited with -6
  #0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/runtime/observatory/tests/service/test_helper.dart:256:11)
  #1      _rootRunUnary (dart:async/zone.dart:1132:38)
  #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
  #3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
  #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
  #5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
  #6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
  #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
  #8      _rootRun (dart:async/zone.dart:1124:13)
  #9      _CustomZone.run (dart:async/zone.dart:1021:19)
  #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
  #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

  stderr:
  Unhandled exception:
  Testee exited with -6
  #0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/runtime/observatory/tests/service/test_helper.dart:256:11)
  #1      _rootRunUnary (dart:async/zone.dart:1132:38)
  #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
  #3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
  #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
  #5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
  #6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
  #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
  #8      _rootRun (dart:async/zone.dart:1124:13)
  #9      _CustomZone.run (dart:async/zone.dart:1021:19)
  #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
  #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

  --- Re-run this test:
  python tools/test.py -n dartk-linux-release-simdbc64 service/get_cpu_profile_timeline_rpc_test
```

**Comment by sstrickl** [comment]
Actually, looking at the approval log, you already approved an RTE result on May 2, and AFAICT that's still active as there are no unapproved failures. Given that, I'm unsure why this is making the bot red. Am going to close this, but if the bot continues to be red despite the previous approvals, I'm going to reopen and change to be a CI-related bug.
