### ISSUE TITLE
Frequent Dart Analysis Exception

### ISSUE THREAD

**Issue by giengus** [dart-lang/sdk#36968]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.7141.44`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IC-191.7141.44, JRE 1.8.0_202-release-1483-b49x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2560x1440, 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Failed to handle completion domain request: {id: 667, method: completion.getSuggestionDetails, params: {file: D:\dev\actiontrak_rms\lib\screens\keep_screen.dart, id: 418, label: BuildContext, offset: 1710}, clientRequestTime: 1557853757937}
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:199:7)
#1      AnalysisSessionImpl.getLibraryByUri (package:analyzer/src/dart/analysis/session.dart:108:5)
<asynchronous suspension>
#2      CompletionDomainHandler.getSuggestionDetails (package:analysis_server/src/domain_completion.dart:179:49)
<asynchronous suspension>
#3      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:210:9)
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _runZoned (dart:async/zone.dart:1516:10)
#7      runZoned (dart:async/zone.dart:1500:12)
#8      CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:206:12)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:349:45)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:345:50)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:344:5)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#52     _StreamController._add (dart:async/stream_controller.dart:640:7)
#53     _StreamController.add (dart:async/stream_controller.dart:586:5)
#54     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#55     _rootRunUnary (dart:async/zone.dart:1136:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#61     _StreamController._add (dart:async/stream_controller.dart:640:7)
#62     _StreamController.add (dart:async/stream_controller.dart:586:5)
#63     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1323:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:844:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#67     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

```
1557853756809 <= {"event":"analysis.highlights","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":53},{"type":"BUILT_IN","of
1557853756812 <= {"event":"analysis.navigation","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","regions":[{"offset":7,"length":45,"targets":[0]},{"offset":61,"length":40,"t
1557853756812 <= {"event":"analysis.closingLabels","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","labels":[{"offset":733,"length":1114,"label":"BlocBuilder"},{"offset":840
1557853756813 <= {"event":"analysis.outline","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>"
1557853756813 <= {"event":"analysis.overrides","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","overrides":[{"offset":522,"length":11,"superclassMember":{"element":{"kind":"
1557853756814 <= {"event":"flutter.outline","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":1855,"codeOffset":0,"codeLen
1557853756818 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":693,"uri":"package:actiontrak_rms/screens/keep_screen.dart","items":[{"label":"KeepScreen","element":{"k
1557853756818 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1557853756818 <= {"event":"analysis.implemented","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","classes":[],"members":[]}}
1557853757923 => {"id":"666","method":"analysis.getHover","params":{"file":"D:\\src\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart","offset":80499},"clientRequestTime":1557853757923}
1557853757924 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1557853757937 => {"id":"667","method":"completion.getSuggestionDetails","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","id":418,"label":"BuildContext","offset":1710},"clien
1557853758147 => {"id":"668","method":"analysis.getHover","params":{"file":"D:\\src\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart","offset":80499},"clientRequestTime":1557853758147}
1557853758221 => {"id":"669","method":"analysis.updateContent","params":{"files":{"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart":{"type":"add","content":"import 'package:actiontrak_rms/bloc
1557853758289 <= {"id":"666","result":{"hovers":[{"offset":80499,"length":12,"containingLibraryPath":"D:\\src\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart","containingLibraryName":""
1557853758291 <= {"id":"669","result":{}}
1557853758397 => {"id":"670","method":"edit.getFixes","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","offset":1710},"clientRequestTime":1557853758397}
1557853758473 => {"id":"671","method":"edit.getAssists","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","offset":1722,"length":0},"clientRequestTime":1557853758473}
1557853758620 <= {"id":"668","result":{"hovers":[{"offset":80499,"length":12,"containingLibraryPath":"D:\\src\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart","containingLibraryName":""
1557853758644 <= {"event":"analysis.errors","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":"D:\\dev
1557853758644 <= {"id":"670","result":{"fixes":[]}}
1557853758646 <= {"id":"671","result":{"assists":[]}}
1557853758647 <= {"event":"analysis.highlights","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":53},{"type":"BUILT_IN","of
1557853758657 <= {"event":"analysis.navigation","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","regions":[{"offset":7,"length":45,"targets":[0]},{"offset":61,"length":40,"t
1557853758657 <= {"event":"analysis.closingLabels","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","labels":[{"offset":733,"length":1125,"label":"BlocBuilder"},{"offset":840
1557853758658 <= {"event":"analysis.outline","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>"
1557853758659 <= {"event":"analysis.overrides","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","overrides":[{"offset":522,"length":11,"superclassMember":{"element":{"kind":"
1557853758660 <= {"event":"flutter.outline","params":{"file":"D:\\dev\\actiontrak_rms\\lib\\screens\\keep_screen.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":1866,"codeOffset":0,"codeLen
1557853758662 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1557853758678 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {id: 667, method: completion.getSuggestionDetails, params: {file: D:\\dev\\act
```

**Comment by srawlins** [comment]
Thanks for reporting this issue! This has been previously reported at https://github.com/dart-lang/sdk/issues/36467; please follow along there.

**Comment by srawlins** [comment]
Or... #36618, but  one or the other.
