### ISSUE TITLE
Analyzer keeps restarting and crashing

### ISSUE THREAD

**Issue by ZeBrody** [dart-lang/sdk#36962]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.6707.61`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `IC-191.6707.61, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: Captured exception
Unsupported operation: unsupported initializer: IndexExpressionImpl :: super()[msg]
#0      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:1236:9)
#1      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2551:14)
#2      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2487:14)
#3      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3176:13)
#4      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3064:15)
#5      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2865:15)
#6      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1846:13)
#7      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1806:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:640:14)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:532:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:347:15)
#11     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:194:32)
#12     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:189:12)
#13     _File._parse (package:analyzer/src/services/available_declarations.dart:1595:23)
#14     _File.refresh (package:analyzer/src/services/available_declarations.dart:1044:30)
#15     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:591:14)
#16     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:504:18)
#17     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:219:13)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2140:35)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2090:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#23     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#29     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#30     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#31     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#32     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#33     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#34     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\Yannick\AppData\Local\Temp\report.txt.

**Comment by ZeBrody** [comment]
Crashing was caused by missing brackets in a super call
`MyClass(String a) : super[a];
instead of
MyClass(String a) : super([a]); `
