### ISSUE TITLE
Misplaced colon in a getter declaration crashes the analyzer

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#36961]
Reported by @sarahec at https://github.com/Dart-Code/Dart-Code/issues/1705. Reproduces on the current nightly build. (cc @bwilkerson @scheglov)

---

Dart release 2.3.0
Pedantic mode rules in effect

In VSCode, Android Studio, and on the command line, the Analyzer will terminate unexpectedly when it sees the following typo:

```dart
abstract class X {
  get checkpoint: // <<< This ":" is enough to crash the analyzer 
}
```

The stack trace is:
```
[11:55:46 GMT-0700 (PDT)] [General] [Error] [Analyzer] Captured exception
[11:55:46 GMT-0700 (PDT)] [General] [Error] [Analyzer] NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1075:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2631:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:428:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1032:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1560:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7550:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:475:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22:8)
#9      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:476:46)
#10     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:475:26)
#12     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:231:32)
#13     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#14     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:227:20)
#15     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:300:9)
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1080:22)
```

**Comment by scheglov** [comment]
Looks like a parser recovery problem. This code `get checkpoint:` is parsed as a constructor, with different `returnType` than `X`, and no parameters.

@danrubel 

![image](https://user-images.githubusercontent.com/384794/57747470-ec1ae880-7692-11e9-92c9-0165f8da17bf.png)
