### ISSUE TITLE
Bad state: Too many elements

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#36972]
I did a fresh install of IntelliJ 2019.1.2, added the Dart (v191.7141.49) and Flutter (v35.3.3) plugins, restarted, and opened the flutter-gallery project. I got two analysis errors during initialization. I didn't even move the mouse.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.7141.44`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IU-191.7141.44, JRE 1.8.0_202-release-1483-b49x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: /Users/messick/src/flutter/flutter/examples/flutter_gallery/test/demo/material/drawer_demo_test.dart context: exception_20190514_154423_623
Bad state: Too many elements
#0      List.single (dart:core/runtime/libgrowable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2526:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5121:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1640:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#18     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#19     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#20     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#21     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#22     _relink (package:analyzer/src/summary/link.dart:305:57)
#23     link (package:analyzer/src/summary/link.dart:123:3)
#24     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#25     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#26     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1624:23)
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#44     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#45     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#46     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#47     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#48     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/yg/474plv091g1cqnz98j05v0y4003j5d/T/report.txt.
DONE

```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: /Users/messick/src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_perf_test.dart context: exception_20190514_154418_269
Bad state: Too many elements
#0      List.single (dart:core/runtime/libgrowable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2526:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5121:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1640:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#18     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#19     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#20     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#21     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#22     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#23     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#24     _relink (package:analyzer/src/summary/link.dart:305:57)
#25     link (package:analyzer/src/summary/link.dart:123:3)
#26     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#27     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#28     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#29     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1624:23)
#30     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#31     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#32     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#33     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#34     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#35     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#36     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#37     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#38     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#39     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _runZoned (dart:async/zone.dart:1516:10)
#43     runZoned (dart:async/zone.dart:1463:12)
#44     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#45     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#46     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#47     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#48     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#49     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#50     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
```
1557873856883 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1317,"uri":"package:flutter_gallery/demo/transformations/transformations_demo_inertial_motion.dart","ite
1557873856884 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1311,"uri":"package:flutter_gallery/demo/transformations/transformations_demo.dart","items":[{"label":"B
1557873856887 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1318,"uri":"package:flutter_gallery/demo/transformations/transformations_demo_gesture_transformable.dart
1557873856893 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1310,"uri":"package:flutter_gallery/demo/pesto_demo.dart","items":[{"label":"RecipeIngredient","element"
1557873856893 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1309,"uri":"package:flutter_gallery/demo/contacts_demo.dart","items":[{"label":"snapping","element":{"ki
1557873856900 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1319,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test_memory/memory_nav.da
1557873856906 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1320,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test_memory/back_button.d
1557873856909 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1321,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/example_code_display
1557873856918 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1322,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/accessibility_test.d
1557873856922 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1323,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/simple_smoke_test.da
1557873856928 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1324,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/live_smoketest.dart"
1557873856930 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1325,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/drawer_test.dart","i
1557873856936 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1326,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/pesto_test.dart","it
1557873856940 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1327,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/smoke_test.dart","it
1557873856949 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1328,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/example_code_parser_
1557873856964 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1329,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/calculator/logic.dar
1557873856983 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1330,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/calculator/smoke_tes
1557873856992 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1331,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/flutter_test_config.
1557873857001 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1332,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/update_test.dart","i
1557873857009 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1333,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/demo/material/drawer
1557873857015 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1334,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/demo/material/text_f
1557873857024 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1335,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/demo/material/chip_d
1557873857026 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1336,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test/demo/material/expans
1557873857032 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1337,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_p
1557873857034 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1338,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_p
1557873857041 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1339,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test_driver/scroll_perf_t
1557873857045 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1340,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_p
1557873857055 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1341,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test_driver/scroll_perf.d
1557873857059 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1342,"uri":"file:///Users/messick/src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_p
1557873858316 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/messick/src/flutter/flutter/examples/flutter_gallery/test_driver/transitions_perf_test.dart contex
```

**Comment by stevemessick** [comment]
What I did not do was set my Flutter SDK to master. After doing that the problem is resolved. I think this is a known version incompatibility, so closing this issue.
