### ISSUE TITLE
Type 'ParameterElementImpl' is not a subtype of type 'ExecutableElement'.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#37005]
```dart
typedef F1 = void Function({int aaa});
typedef F2 = void Function({int aaa});

main(F1 f1, F2 f2) {
  f1(aaa: 1);
  f2(aaa: 1);
}
```

  I think this happened during typing `f1(aaa:`

Analyzer Feedback from IntelliJ

## Version information

- `IDEA 192.SNAPSHOT`
- `2.3.1-edge.6805bb52ea2a06a0d3d30625a3a8ac7e49145062`
- `IC-192.SNAPSHOT, JRE 1.8.0_202-b08x64 Oracle Corporation, OS Mac OS X(x86_64) v10.14.4, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.1-edge.6805bb52ea2a06a0d3d30625a3a8ac7e49145062, server version 1.26.1, FATAL error: Failed to handle request: {id: 64242, method: edit.getFixes, params: {file: /Users/scheglov/dart/test/bin/test.dart, offset: 105}, clientRequestTime: 1558282718881}
type 'ParameterElementImpl' is not a subtype of type 'ExecutableElement'
#0      FixProcessor._addFix_convertToNamedArgument (package:analysis_server/src/services/correction/fix_internal.dart:1322:9)
<asynchronous suspension>
#1      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:459:13)
<asynchronous suspension>
#2      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#3      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:639:46)
<asynchronous suspension>
#4      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:741:14)
<asynchronous suspension>
#5      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:277:32)
<asynchronous suspension>
#6      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:380:9)
#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:318:45)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#9      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:314:50)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1500:12)
#14     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:313:5)
#15     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#17     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#18     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#49     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#50     _StreamController._add (dart:async/stream_controller.dart:640:7)
#51     _StreamController.add (dart:async/stream_controller.dart:586:5)
#52     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#53     _rootRunUnary (dart:async/zone.dart:1136:13)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#58     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#59     _StreamController._add (dart:async/stream_controller.dart:640:7)
#60     _StreamController.add (dart:async/stream_controller.dart:586:5)
#61     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#62     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#63     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#64     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#65     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

For additional log information, please append the contents of
file:///private/var/folders/5_/801pkmkn457fzp_twzmc2g88003ky_/T/report1.txt.

**Comment by pq** [comment]
@scheglov: this doesn't repro for me anymore.  Perhaps it's fixed?

**Comment by scheglov** [comment]
No, it was not.
My guess about the repro test case was wrong.

https://dart-review.googlesource.com/c/sdk/+/115270
