### ISSUE TITLE
commit

### ISSUE THREAD

**Issue by sqzxcv** [dart-lang/sdk#37015]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.5429.30.34.5452501`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-183.5429.30.34.5452501, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1920x1080, 1080x1920`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: Captured exception
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1097:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2631:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:438:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1054:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1560:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7550:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:485:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22:8)
#9      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:484:46)
#10     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:483:26)
#12     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:231:32)
#13     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#14     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:227:20)
#15     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:300:9)
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1091:22)
<asynchronous suspension>
#17     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2160:24)
<asynchronous suspension>
#18     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2090:5)
#19     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#20     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#21     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#22     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#28     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#29     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#30     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#31     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#32     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/wg/h93_yfsx5vv4czyqddf9fzk40000gn/T/report.txt.

**Comment by DanTup** [comment]
Possibly a dupe of https://github.com/dart-lang/sdk/issues/36961?
