### ISSUE TITLE
Dart2js crashed when compiling code with ... statement

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#37010]
* This tracker is for issues related to:
dart2js

* Dart SDK Version (`dart --version`)
2.3

* Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOS

When compiling:
```
const _set1 = const <String> {"a", "b"};

final _set2 = <String> {..._set1,
  "c", "d"};

void main() {
  print(_set2);
}
```

It causes:

```
Internal Error: The compiler crashed when compiling this element.
final _set2 = <String> {..._set1,
      ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.3.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The method 'add' was called on null.
Receiver: null
Tried calling: add(Instance of 'VariableDeclaration')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      StaticTypeVisitor.visitVariableDeclaration (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ir/static_type.dart:1361:23)
#2      VariableDeclaration.accept (package:kernel/ast.dart:4647:35)
#3      StaticTypeBase.visitNode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ir/static_type_base.dart:76:18)
#4      StaticTypeVisitor.visitBlock (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ir/static_type.dart:956:22)
#5      Block.accept (package:kernel/ast.dart:3941:35)
#6      StaticTypeBase.visitNode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ir/static_type_base.dart:76:18)
#7      StaticTypeVisitor.visitBlockExpression (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ir/static_type.dart:928:5)
#8      BlockExpression.accept (package:kernel/ast.dart:3828:36)
#9      StaticTypeBase.visitNode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ir/static_type_base.dart:76:18)
#10     StaticTypeVisitor.visitField (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ir/static_type.dart:1352:5)
#11     Field.accept (package:kernel/ast.dart:1309:32)
#12     KernelToElementMapImpl.computeWorldImpact (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:1391:12)
#13     KernelWorkItem.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/kernel_strategy.dart:300:47)
#14     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#15     KernelWorkItem.run.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/kernel_strategy.dart:299:28)
#16     CompilerTask.measure (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:64:51)
#17     KernelWorkItem.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/kernel_strategy.dart:274:26)
#18     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:466:70)
#19     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
...
```

**Comment by sigmundch** [comment]
Thanks for filing the issue and providing the small repro case!

Turns out we have landed a fix in 9ac7bd7. This fix is available on the dev channel (2.3.1-dev.0.0), but it hasn't been released on the stable channel yet. Issue #36998 has a request to get this cherry-picked and released in the stable channel as well.
