### ISSUE TITLE
Dart is crashing with a confusing error

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#37027]
The Dart VM is crashing when trying to invoke the main Dart Sass binary. To reproduce:

```shellsession
$ git clone -b dart-sdk-bug git://github.com/sass/dart-sass
$ cd dart-sass
$ pub get
$ dart bin/sass.dart
Unsupported operation: serialization of generic Expressions
#0      BinaryPrinter.defaultExpression (package:kernel/binary/ast_to_binary.dart:2100:5)
#1      _ForInElement&Expression&ControlFlowElement.accept (package:front_end/src/fasta/kernel/collections.dart:53:44)
#2      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:375:10)
#3      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:56:11)
#4      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:294:7)
#5      BinaryPrinter.visitArguments (package:kernel/binary/ast_to_binary.dart:1453:5)
#6      Arguments.accept (package:kernel/ast.dart:2748:30)
#7      BinaryPrinter.writeArgumentsNode (package:kernel/binary/ast_to_binary.dart:389:10)
#8      BinaryPrinter.visitMethodInvocation (package:kernel/binary/ast_to_binary.dart:1409:5)
#9      MethodInvocation.accept (package:kernel/ast.dart:2864:36)
#10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:375:10)
#11     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:56:11)
#12     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:461:7)
#13     BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1945:5)
#14     BinaryPrinter.visitLet (package:kernel/binary/ast_to_binary.dart:1690:5)
#15     Let.accept (package:kernel/ast.dart:3797:36)
#16     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:375:10)
#17     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:56:11)
#18     BinaryPrinter.visitLet (package:kernel/binary/ast_to_binary.dart:1691:5)
#19     Let.accept (package:kernel/ast.dart:3797:36)
#20     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:375:10)
#21     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:56:11)
#22     BinaryPrinter.visitFieldInitializer (package:kernel/binary/ast_to_binary.dart:1230:5)
#23     FieldInitializer.accept (package:kernel/ast.dart:1870:37)
#24     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:375:10)
#25     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:56:11)
#26     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:294:7)
#27     BinaryPrinter.visitConstructor (package:kernel/binary/ast_to_binary.dart:1128:5)
#28     Constructor.accept (package:kernel/ast.dart:1405:32)
#29     BinaryPrinter.writeConstructorNode (package:kernel/binary/ast_to_binary.dart:424:10)
#30     BinaryPrinter.writeConstructorNodeList (package:kernel/binary/ast_to_binary.dart:330:7)
#31     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1086:5)
#32     Class.accept (package:kernel/ast.dart:1010:30)
#33     BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:417:10)
#34     BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:321:7)
#35     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:921:5)
#36     Library.accept (package:kernel/ast.dart:435:30)
#37     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:396:10)
#38     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49:31)
#39     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:537:5)
#40     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:69:11)
#41     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:593:11) <asynchronous suspension>
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

The issue reproduces with [the HEAD commit on the `dart-sdk-bug` branch](https://github.com/sass/dart-sass/commit/175db561fc3d9b1de62d8884e121f3497c6b99f3), but it does *not* reproduce with the previous commit. Unfortunately, I haven't been able to narrow it down any further, since the error output doesn't provide any more information on the issue. If I introduce any compile-time error, it seems to take precedence in the output, so I also can't easily binary-search the new code to see what caused the issue.

This is blocking important feature work on Dart Sass. Please let me know ASAP if there's a workaround I can use to get unblocked.

I've tested this with Dart 2.3.0 and 2.3.1-dev.0.0.

**Comment by kmillikin** [comment]
Thanks for the report.  It's this code in `lib/src/util/limited_map_view.dart`:

```dart
  LimitedMapView.whitelist(this._map, Set<K> whitelist)
      : _keys = {for (var key in whitelist) if (_map.containsKey(key)) key};
```

It looks like we don't compile the loop set element in the initializer correctly.

**Comment by nex3** [comment]
Thanks, that gives me enough to get unblocked.

**Comment by kmillikin** [comment]
This is fixed in the SDK HEAD.  For anyone else who encounters this issue, there are several ways to workaround it:

* Don't use control-flow elements in the intializer (something like `_keys = whitelist.filter(_map.containsKey).toSet()`).

* Make the field non-final and put the initialization in the constructor body.

* Put the set literal expression in a closure or a static helper function that's called in the initializer (this is untested, but it should work).
