### ISSUE TITLE
Possible bug in kernel binary writer/reader or VM bug

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#37042]
From flutter's CI, see [here](https://cirrus-ci.com/task/6283958203973632):
```
...
sdk\dev\automated_tests\test_smoke_test\missing_import_test.broken_dart                                                                                      
09:25 +0: loading C:\Windows\Temp\flutter sdk\dev\automated_tests\test_smoke_test\missing_import_test.broken_dart                                                                                      
09:25 +0 -1: loading C:\Windows\Temp\flutter sdk\dev\automated_tests\test_smoke_test\missing_import_test.broken_dart [E]                                                                               
  Failed to load "C:\Windows\Temp\flutter sdk\dev\automated_tests\test_smoke_test\missing_import_test.broken_dart":
  Compilation failed
  Test: C:\Windows\Temp\flutter sdk\dev\automated_tests\test_smoke_test\missing_import_test.broken_dart
  Shell: C:\Windows\Temp\flutter sdk\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe
09:25 +0 -1: Some tests failed.                                                                                                                                                                        
Exhausted heap space, trying to allocate 34359738384 bytes.
Compiler message:
Warning: Tried to initialize from a previous compilation (file:///C:/Windows/Temp/flutter%20sdk/dev/automated_tests/build/testfile.dill), but couldn't.
Error message was 'Out of Memory'.
Stacktrace included '#0      List._grow (dart:core-patch/growable_array.dart)
#1      BinaryBuilder._indexComponents (package:kernel/binary/ast_from_binary.dart:168:22)
#2      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:36)
#3      IncrementalCompiler.initializeFromDill (package:front_end/src/fasta/incremental_compiler.dart:618:14)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:775:12183)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
'.
This might be a bug.
The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///C:/Users/ContainerAdministrator/AppData/Local/Temp/initialize_from.dill72253760-7b52-11e9-a94c-f6594dc1d850/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.
test_smoke_test/missing_import_test.broken_dart:9:3: Error: Method not found: 'fail'.
  fail(); // inspired by https://github.com/flutter/flutter/issues/2698
  ^^^^
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 0 (expected: non-zero).
Command: ..\..\bin\flutter.bat test test_smoke_test\missing_import_test.broken_dart
Relative working directory: dev\automated_tests
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
C:\Windows\Temp\flutter sdk>if 1 NEQ 0 exit /b 1 
```

**Comment by mkustermann** [comment]
Notice it's try to allocate 32 GB of memory.

/cc @jensjoha

**Comment by a-siva** [comment]
Changing priority as it has been hit again, this time in a flutter test.

**Comment by jensjoha** [comment]
I think this is what's happening:

* The test launch several flutter instances at once:
https://github.com/flutter/flutter/blob/2ad5376a06ee138e63266bd55dc3d33fc7b1c3eb/dev/bots/test.dart#L106-L149

* One test instance starts writing or overwriting the testfile.dill
* Another test instance reads it before the first one finishes and thus reads incomplete data.
* Basically the first thing the dill reader does is to look at the end of the file and read that as an index of the file - but because the file wasn't finished writing when it was read, it reads "arbitrary data" --- which here instructs it that it has to create a list with size x billion (or whatever).

While we could theoretically have some checksum or whatever to discover this, it's really a flutter issue (it asks us to read an incomplete file) (and one that I probably created, but still).

**Comment by jensjoha** [comment]
(okay, I may have closed it too soon --- I'm reopening until I have either filed a bug in flutter or created a pull request in flutter).

**Comment by jensjoha** [comment]
While it's not in yet, I have a PR in flutter at https://github.com/flutter/flutter/pull/35871. Closing this issue.
