### ISSUE TITLE
Error with Dart analyzer in Android Studio 3.5 Beta 2

### ISSUE THREAD

**Issue by vistiyos** [dart-lang/sdk#37045]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 191.6707.61.35.5549111`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-191.6707.61.35.5549111, JRE 1.8.0_202-release-1483-b02x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1920x1200  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: FileSystemException(path=/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/Flutter/App.framework/flutter_assets/packages/cupertino_icons/assets/CupertinoIco; message=Directory listing failed)
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:334:7)
#1      _OverlayFolder.getChildren (package:analyzer/file_system/overlay_file_system.dart:334:10)
#2      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1144:32)
#3      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#4      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#5      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#6      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#7      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#8      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#9      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#10     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#11     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#12     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#13     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#14     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#15     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#16     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#17     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#18     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#19     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#20     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#21     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#22     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#23     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#24     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#25     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#26     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#27     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#28     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#29     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#30     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#31     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#32     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#33     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#34     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#35     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#36     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#37     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#38     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#39     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#40     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#41     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#42     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#43     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#44     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#45     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#46     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#47     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#48     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#49     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#50     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#51     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#52     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#53     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#54     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#55     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#56     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#57     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#58     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#59     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#60     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#61     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#62     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#63     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#64     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#65     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#66     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#67     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#68     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#69     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#70     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#71     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#72     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#73     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#74     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#75     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#76     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#77     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#78     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#79     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#80     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#81     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#82     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#83     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#84     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#85     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#86     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#87     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#88     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#89     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#90     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#91     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#92     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#93     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#94     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#95     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#96     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#97     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#98     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#99     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#100    ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#101    ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1158:25)
#102    ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1191:16)
#103    ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:736:9)
#104    AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:521:22)
#105    AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:390:14)
#106    AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:324:16)
#107    AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:337:45)
#108    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#109    AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:50)
#110    _rootRun (dart:async/zone.dart:1124:13)
#111    _CustomZone.run (dart:async/zone.dart:1021:19)
#112    _runZoned (dart:async/zone.dart:1516:10)
#113    runZoned (dart:async/zone.dart:1500:12)
#114    AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:332:5)
#115    ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#116    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#117    ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#118    ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#119    _rootRunUnary (dart:async/zone.dart:1132:38)
#120    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#121    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#122    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#123    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#124    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#125    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#126    _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#127    _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#128    _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#129    StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#130    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#131    _rootRunUnary (dart:async/zone.dart:1132:38)
#132    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#133    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#134    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#135    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#136    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#137    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#138    _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#139    _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#140    _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#141    _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#142    _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#143    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#144    _rootRunUnary (dart:async/zone.dart:1132:38)
#145    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#146    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#147    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#148    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#149    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#150    _StreamController._add (dart:async/stream_controller.dart:640:7)
#151    _StreamController.add (dart:async/stream_controller.dart:586:5)
#152    _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#153    _rootRunUnary (dart:async/zone.dart:1136:13)
#154    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#155    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#156    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#157    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#158    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#159    _StreamController._add (dart:async/stream_controller.dart:640:7)
#160    _StreamController.add (dart:async/stream_controller.dart:586:5)
#161    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#162    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#163    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#164    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#165    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#166    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

For additional log information, please append the contents of
file:///private/var/folders/xs/v57xh97d0176ykd91khn8w5c0000gn/T/report.txt.

```
1558470572485 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572567 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572570 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572617 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572633 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572671 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572674 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572754 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572769 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572814 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572818 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572879 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572883 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572929 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572932 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572990 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470572995 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573061 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573066 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573106 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573110 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573177 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573181 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573243 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573248 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573318 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573325 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573412 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573452 <= {"event":"analysis.errors","params":{"file":"/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/ios/.symlinks/plugins/health_data
1558470573498 <= {"id":"4","error":{"code":"SERVER_ERROR","message":"FileSystemException(path=/Users/vistiyos/PiKT/health-data-flutter-plugin/example/ios/.symlinks/plugins/health_data_plugin/example/i
```

**Comment by DanTup** [comment]
This appears to be the same as https://github.com/dart-lang/sdk/issues/36919.
