### ISSUE TITLE
Internal Error: The compiler crashed when compiling this element. 

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#37047]
Hey Guys I have managed to reproduce this in a very consistent fashion.

Environment:
Dart 2.3.0

Step 1: ```pub run test test/handler/handler_test.dart``` code in this [gist](https://gist.github.com/rayk/b13a74f5c1df0b5c71b7ab3e70400696)

```
00:00 +0: compiling test/handler/handler_test.dart
/private/var/folders/4g/5hhdm40x43zd7r_43429rgyr0000gn/T/dart_test_TEdbu5/runInBrowser.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.3.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      TypeVariableLocal.name (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/closure.dart:350:43)
#2      JsKernelToElementMap._constructClosureField (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/element_map_impl.dart:2101:47)
#3      JsKernelToElementMap._buildClosureClassFields (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/element_map_impl.dart:2012:9)
#4      JsKernelToElementMap.constructClosureClass (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/element_map_impl.dart:1922:5)
#5      JsClosedWorldBuilder.buildClosureClass (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/js_world_builder.dart:411:59)
#6      ClosureDataBuilder._produceSyntheticElements (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/closure.dart:390:28)
#7      ClosureDataBuilder.createClosureEntities.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/closure.dart:336:51)
#8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#9      ClosureDataBuilder.createClosureEntities (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/closure.dart:302:19)
#10     JsClosedWorldBuilder.convertClosedWorld (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/js_world_builder.dart:163:41)
#11     JsBackendStrategy.createJClosedWorld (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/js_strategy.dart:77:31)
#12     Compiler.closeResolution (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:451:25)
#13     Compiler.computeClosedWorld (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:357:32)
#14     Compiler.compileFromKernel.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:405:17)
#15     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#16     Compiler.compileFromKernel.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:404:43)
#17     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#18     Compiler.compileFromKernel (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:403:14)
#19     Compiler.runInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:272:13)
<asynchronous suspension>
#20     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:223:38)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     Compiler.run.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:223:20)
#23     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#24     Compiler.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:220:41)
#25     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/apiimpl.dart:91:22)
#26     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)


00:00 +0 -1: compiling test/handler/handler_test.dart [E]
  Failed to load "test/handler/handler_test.dart": dart2js failed.
00:00 +0 -1: Some tests failed.
```

I have tried all the classic fixes, 
1. ```pub run build_runner clean```
2. Building via build_runner -- BTW the build.yaml is [here](https://gist.github.com/rayk/b13a74f5c1df0b5c71b7ab3e70400696#file-build-yaml)
3. clear the pub cache etc.

All of which lead back to the same consistent result. 
- Key point this problem is just related to this file in the problem the other appear fine.

Thanks in advance
Ray

**Comment by sigmundch** [comment]
@rayk thanks for filing the issue. I'm having trouble reproducing this locally. The files have dependencies on other files not availble on the gist. If I comment those out and declare my own pubspec, I still don't see the issue. Maybe I'm using a different version of package:test?

Would you be able to paste here the code for `runInBrowser.dart` (which I believe is generated by package:test)?

My guess is that maybe package test has some generated code that is triggering an issue in dart2js, but I am not sure.

**Comment by rayk** [comment]
Hey guys, I am thinking this one is erroneous or ephemeral. As now I am having problems reproducing it. Follow on @sigmundch reply I run the test again to get ahold of the ```runInBrowser.dart``` and I am not able to reproduce the error.

So I am going to close this issue and reopen it the problem appears again...

Thanks again for looking at it.
