### ISSUE TITLE
Dart analysis error

### ISSUE THREAD

**Issue by vikramkapoor** [dart-lang/sdk#37059]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.5429.30.34.5452501`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-183.5429.30.34.5452501, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1440x900`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, FATAL error: FileSystemException: Directory listing failed, path = 'C:\Users\vkapo\AppData\Local\.dartServer\.analysis-driver\c8\' (OS Error: The file or directory is corrupted and unreadable.
, errno = 1392)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:249:5)
#2      EvictingFileByteStore._cleanUpFolder (package:analyzer/src/dart/analysis/file_byte_store.dart:114:34)
#3      EvictingFileByteStore._cacheCleanUpFunction.<anonymous closure> (package:analyzer/src/dart/analysis/file_byte_store.dart:101:9)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#7      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#8      _StreamController._add (dart:async/stream_controller.dart:640:7)
#9      _StreamController.add (dart:async/stream_controller.dart:586:5)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\vkapo\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
This has been reported as recently as Dart 2.5.0.

**Comment by srawlins** [comment]
This has been reported as recently as Dart 2.6.1.

**Comment by keertip** [comment]
And still there in Dart 2.7.0-dev.2.1.

**Comment by srawlins** [comment]
And 2.8.1. https://github.com/dart-lang/sdk/issues/41863

**Comment by srawlins** [comment]
I don't think this has been reported recently; closing for now. Please open a new issue if you see this crash on a recent version of Dart.
