### ISSUE TITLE
Performing Error 

### ISSUE THREAD

**Issue by widoko** [dart-lang/sdk#37055]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.7141.44`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `IU-191.7141.44, JRE 1.8.0_202-release-1483-b49x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: Captured exception
Internal problem: Compiler cannot run without a compiler context.
Tip: Are calls to the compiler wrapped in CompilerContext.runInContext?
#0      CompilerContext.current (package:front_end/src/fasta/compiler_context.dart:111:7)
#1      internalProblem (package:front_end/src/fasta/problems.dart:45:25)
#2      unhandled (package:front_end/src/fasta/problems.dart:58:10)
#3      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#4      unescapeString (package:front_end/src/fasta/quote.dart:138:17)
#5      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1273:22)
#6      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4814:14)
#7      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4739:13)
#8      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4159:14)
#9      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4092:12)
#10     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3888:13)
#11     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3860:13)
#12     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3825:13)
#13     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5209:16)
#14     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5130:12)
#15     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3730:14)
#16     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3640:20)
#17     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3545:15)
#18     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2426:13)
#19     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2329:14)
#20     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:556:14)
#21     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:347:15)
#22     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:194:32)
#23     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:189:12)
#24     _File._parse (package:analyzer/src/services/available_declarations.dart:1595:23)
#25     _File.refresh (package:analyzer/src/services/available_declarations.dart:1044:30)
#26     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:634:12)
#27     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:498:7)
#28     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:219:13)
<asynchronous suspension>
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2140:35)
<asynchronous suspension>
#30     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2090:5)
#31     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#32     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#33     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#34     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#40     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#41     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#42     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#43     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#44     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\widok\AppData\Local\Temp\report.txt.

**Comment by bwilkerson** [comment]
@danrubel

**Comment by danrubel** [comment]
@bwilkerson Unfortunately the lack of a compiler context is masking the underlying problem. See the throw statement in [CompilerContext.current](https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/compiler_context.dart#L104). It appears that I need to make a call to [CompilerContext.runWithDefaultOptions](https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/compiler_context.dart#L138) somewhere in the AnalysisServer framework. I think it only needs to be run once, early on, to set the default options. Any suggestions as to where?

**Comment by bwilkerson** [comment]
The earliest possible place is in `analysis_server/lib/src/server/driver.dart`, in the `start` method.

**Comment by danrubel** [comment]
I've added some code in https://dart-review.googlesource.com/c/sdk/+/103562 that should uncover the underlying problem. This issue will be closed when that change lands, but please reopen this or a new issue with what will hopefully be a more illuminating error message.

**Comment by widoko** [comment]
Thank you for the response, well I will update from the code in https://dart-review.googlesource.com/c/sdk/+/103562, we see what new problems will reappear. Thanks.
