### ISSUE TITLE
Corrupt filename in Dart analyzer (see AnalysisException)

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#37058]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Tidying up imports: switching from 'raw' import to `package:` import in https://github.com/timsneath/cambridge/blob/master/spectrum/lib/spectrum/display.dart

### Versions

- Flutter SDK 1.6.1-pre.84
- Visual Studio Code 1.34.0
- Dart Code 3.1.0-alpha.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/timsneath/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.1.0-alpha.1
```

### Exception (fatal)

Failed to handle request: {id: 8424, method: edit.getFixes, params: {file: /Users/timsneath/git/me/cambridge/spectrum/lib/spectrum/display.dart, offset: 161}, clientRequestTime: 1558545833551}

```text
AnalysisException: Cannot analyze "/Users/timsneath/git/me/cambridge/spectrum/lib/spectru%20/spectrumcolor.dart"

#0      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:72:7)
<asynchronous suspension>
#1      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:82:23)
<asynchronous suspension>
#2      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:52:18)
#3      FixProcessor._addFix_createImportUri (package:analysis_server/src/services/correction/fix_internal.dart:2057:31)
<asynchronous suspension>
#4      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:277:13)
<asynchronous suspension>
#5      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#6      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:639:46)
<asynchronous suspension>
#7      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:741:14)
<asynchronous suspension>
#8      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:277:32)
<asynchronous suspension>
#9      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:380:9)
#10     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:318:45)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#12     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:314:50)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1500:12)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:313:5)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#47     _rootRunUnary (dart:async/zone.dart:1132:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#52     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#53     _StreamController._add (dart:async/stream_controller.dart:640:7)
#54     _StreamController.add (dart:async/stream_controller.dart:586:5)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#56     _rootRunUnary (dart:async/zone.dart:1136:13)
#57     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#61     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#62     _StreamController._add (dart:async/stream_controller.dart:640:7)
#63     _StreamController.add (dart:async/stream_controller.dart:586:5)
#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#68     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/timsneath/git/me/cambridge/spectrum",
        "explicitFileCount": 10,
        "implicitFileCount": 828,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment]
This is a very old issue - there were some dupes reported all in 2019 but seemingly nothing since. I think it's very likely this was fixed a long time ago, but if anyone sees this on a modern SDK, please post back and we can reopen.
