### ISSUE TITLE
Analysis server error when typing in VS Code

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#37066]
Happens on 2.3 and on the nightly from this morning.

I was typing `@soloTest` on line 194 of this file [initialization_test.dart](https://github.com/dart-lang/sdk/files/3212730/initialization_test.dart.txt) in `sdk/pkg/analysis_server/test/lsp/initialization_test.dart`.

The error/strack trace don't look too useful though.

### Versions

- Flutter SDK 1.6.0
- Visual Studio Code 1.34.0
- Dart Code 3.1.0-dev

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/dantup/Dev/dart-sdk/nightly-2019-05-23/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.1.0-dev
```

### Exception

Captured exception

```text
NoSuchMethodError: The getter 'next' was called on null.
Receiver: null
Tried calling: next
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:605:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      Future._propagateToListeners (dart:async/future_impl.dart:555:16)
#3      Future._completeError (dart:async/future_impl.dart:491:5)
#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#5      _Completer.completeError (dart:async/future_impl.dart:27:5)
#6      _AsyncAwaitCompleter.completeError.<anonymous closure> (dart:async-patch/async_patch.dart:43:20)
#7      _rootRun (dart:async/zone.dart:1120:38)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

```
[3:39:05 PM]: ==> {"id":"53","method":"analysis.updateContent","params":{"files":{"/Users/dantup/Dev/Google/dart-sdk/sdk/pkg/analysis_server/test/lsp/initialization_test.dart":{"edits":[{"id":"","length":0,"offset":7270,"replacement":"@"}],"type":"change"}}},"clientRequestTime":1558622345040}
[3:39:05 PM]: <== {"id":"53","result":{}}
[3:39:05 PM]: <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[3:39:05 PM]: <== {"event":"analysis.errors","params":{"file":"/Users/dantup/Dev/Google/dart-sdk/sdk/pkg/analysis_server/test/lsp/initialization_test.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/Users/dantup/Dev/Google/dart-sdk/sdk/pkg/analysis_server/test/lsp/initialization_test.dart","offset":7537,"length":21,"startLine":1,"startColumn":7538},"message":"Expected to find ';'.","code":"expected_token","hasFix":true},{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/Users/dantup/Dev/Google/dart-sdk/sdk/pkg/analysis_server/test/lsp/initialization_test.dart","offset":7559,"length":4,"startLine":1,"startColumn":7560},"message":"Expected an identifier.","code":"missing_identifier","hasFix":false},{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/Users/dantup/Dev/Google/dart-sdk/sdk/pkg/analysis_server/test/lsp/initialization_test.dart","offset":7328,"length":5,"startLine":1,"startColumn":7329},"message":"Methods must have an explicit list of parameters.","correction":"Try adding a parameter list.","code":"missing_method_parameters","hasFix":false}]}}
[3:39:05 PM]: <== {"event":"analysis.occurrences","params":{"file":"/Users/dantup/Dev/Google/dart-sdk/sdk/pkg/analysis_server/test/lsp/initialization_test.dart","occurrences":[]}}
[3:39:05 PM]: <== {"event":"analysis.closingLabels","params":{"file":"/Users/dantup/Dev/Google/dart-sdk/sdk/pkg/analysis_server/test/lsp/initialization_test.dart","labels":[]}}
[3:39:05 PM]: <== {"event":"analysis.folding","params":{"file":"/Users/dantup/Dev/Google/dart-sdk/sdk/pkg/analysis_server/test/lsp/initialization_test.dart","regions":[]}}
[3:39:05 PM]: <== {"event":"analysis.outline","params":{"file":"/Users/dantup/Dev/Google/dart-sdk/sdk/pkg/analysis_server/test/lsp/initialization_test.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{"file":"/Users/dantup/Dev/Google/dart-sdk/sdk/pkg/analysis_server/test/lsp/initialization_test.dart","offset":0,"length":0,"startLine":1,"startColumn":1},"flags":0},"offset":0,"length":0,"codeOffset":0,"codeLength":0}}}
[3:39:05 PM]: <== {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The getter 'next' was called on null.\nReceiver: null\nTried calling: next\n#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)\n#1      Parser.parseLiteralFunctionSuffix (package:front_end/src/fasta/parser/parser.dart:4471:38)\n#2      Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4503:14)\n#3      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4177:14)\n#4      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4066:12)\n#5      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3862:13)\n#6      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3834:13)\n#7      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3799:13)\n#8      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5202:16)\n#9      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5113:12)\n#10     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3704:14)\n#11     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3607:20)\n#12     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3512:15)\n#13     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3161:15)\n#14     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3024:15)\n#15     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2800:15)\n#16     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1774:13)\n#17     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1734:14)\n#18     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parse…
[3:39:05 PM]: ==> {"id":"54","method":"diagnostic.getDiagnostics","clientRequestTime":1558622345073}
[3:39:05 PM]: <== {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The getter 'next' was called on null.\nReceiver: null\nTried calling: next\n#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)\n#1      Parser.parseLiteralFunctionSuffix (package:front_end/src/fasta/parser/parser.dart:4471:38)\n#2      Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4503:14)\n#3      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4177:14)\n#4      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4066:12)\n#5      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3862:13)\n#6      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3834:13)\n#7      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3799:13)\n#8      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5202:16)\n#9      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5113:12)\n#10     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3704:14)\n#11     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3607:20)\n#12     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3512:15)\n#13     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3161:15)\n#14     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3024:15)\n#15     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2800:15)\n#16     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1774:13)\n#17     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1734:14)\n#18     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parse…
[3:39:05 PM]: ==> {"id":"55","method":"diagnostic.getDiagnostics","clientRequestTime":1558622345082}
[3:39:05 PM]: <== {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The getter 'next' was called on null.\nReceiver: null\nTried calling: next\n#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:605:7)\n#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)\n#2      Future._propagateToListeners (dart:async/future_impl.dart:555:16)\n#3      Future._completeError (dart:async/future_impl.dart:491:5)\n#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)\n#5      _Completer.completeError (dart:async/future_impl.dart:27:5)\n#6      _AsyncAwaitCompleter.completeError.<anonymous closure> (dart:async-patch/async_patch.dart:43:20)\n#7      _rootRun (dart:async/zone.dart:1120:38)\n#8      _CustomZone.run (dart:async/zone.dart:1021:19)\n#9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)\n#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)\n#11     _rootRun (dart:async/zone.dart:1124:13)\n#12     _CustomZone.run (dart:async/zone.dart:1021:19)\n#13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)\n#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)\n#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)\n#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)\n#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)\n#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)\n#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)\n"}}
[3:39:05 PM]: ==> {"id":"56","method":"diagnostic.getDiagnostics","clientRequestTime":1558622345084}
[3:39:05 PM]: <== {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The getter 'next' was called on null.\nReceiver: null\nTried calling: next\n#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:605:7)\n#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)\n#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)\n#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)\n#4      _rootRun (dart:async/zone.dart:1124:13)\n#5      _CustomZone.run (dart:async/zone.dart:1021:19)\n#6      _CustomZone.runGuarded (dart:async/zone.dart:923:7)\n#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)\n#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)\n#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)\n#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)\n#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)\n#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)\n"}}
[3:39:05 PM]: ==> {"id":"57","method":"diagnostic.getDiagnostics","clientRequestTime":1558622345085}
[3:39:05 PM]: Unhandled exception:
NoSuchMethodError: The getter 'next' was called on null.
Receiver: null
Tried calling: next
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:605:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by DanTup** [comment]
Actually, in the server response was a better stack:

```
NoSuchMethodError: The getter 'next' was called on null.
Receiver: null
Tried calling: next
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      Parser.parseLiteralFunctionSuffix (package:front_end/src/fasta/parser/parser.dart:4471:38)
#2      Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4503:14)
#3      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4177:14)
#4      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4066:12)
#5      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3862:13)
#6      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3834:13)
#7      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3799:13)
#8      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5202:16)
#9      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5113:12)
#10     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3704:14)
#11     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3607:20)
#12     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3512:15)
#13     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3161:15)
#14     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3024:15)
#15     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2800:15)
#16     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1774:13)
#17     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1734:14)
#18     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parse…

```

**Comment by bwilkerson** [comment]
@danrubel

**Comment by srawlins** [comment]
This has not been reported again recently; please re-open if you see this in a recent version of Dart/Flutter.
