### ISSUE TITLE
[vm/ffi] dartkb x64 callback exception test fails in product mode

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#37078]
Looks like the way we test exceptions in callbacks is not supported in product mode.

ffi/function_callbacks_test/01 | New test RuntimeError (expected Pass)
-- | --
ffi/function_callbacks_test/02 | New test RuntimeError (expected Pass)

on configurations dartkb-compile-linux-product-x64 dartkb-interpret-linux-product-x64 dartkb-mixed-linux-product-x64 

```dart
stdout:
Expect "unhandled exception" error message to follow.
==================== UNHANDLED EXCEPTION FROM FFI CALLBACK ====================
 ** Native callbacks should not throw exceptions because they cannot be
    propagated into native code. **
EXCEPTION: NoSuchMethodError: The method 'FfiCallback' was called on null.
Receiver: null
Tried calling: FfiCallback()
#0      FfiCallback (dart:ffi)
#1      FfiTrampoline (dart:ffi)
#2      Test.run (file:///b/s/w/ir/out/ProductX64/generated_tests/ffi/function_callbacks_test_02.dart:35:31)
#3      main.async_op.<anonymous closure> (file:///b/s/w/ir/out/ProductX64/generated_tests/ffi/function_callbacks_test_02.dart:188:29)
#4      _GrowableList.forEach (dart:core-patch/growable_array.dart:278:8)
#5      main (file:///b/s/w/ir/out/ProductX64/generated_tests/ffi/function_callbacks_test_02.dart:188:12)
#6      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart)
#7      main (file:///b/s/w/ir/out/ProductX64/generated_tests/ffi/function_callbacks_test_02.dart:187:9)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart)

stderr:
Unhandled exception:
Invalid argument(s): Failed to lookup symbol (/b/s/w/ir/out/ProductX64/libffi_test_functions.so: undefined symbol: TestCallbackOutsideIsolate)
#0      DynamicLibrary.lookup (dart:ffi/dynamic_library.dart)
#1      DynamicLibrary.lookupFunction (dart:ffi/dynamic_library.dart)
#2      Test.run (file:///b/s/w/ir/out/ProductX64/generated_tests/ffi/function_callbacks_test_02.dart:34:9)
#3      testCallbackOutsideIsolate (file:///b/s/w/ir/out/ProductX64/generated_tests/ffi/function_callbacks_test_02.dart:169:73)
#4      main (file:///b/s/w/ir/out/ProductX64/generated_tests/ffi/function_callbacks_test_02.dart:196:4)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart)
#6      main (file:///b/s/w/ir/out/ProductX64/generated_tests/ffi/function_callbacks_test_02.dart:187:9)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart)

--- Re-run this test:
python tools/test.py -n dartkb-compile-linux-product-x64 ffi/function_callbacks_test/02
```

Cause: landing ffi callbacks on x64 https://github.com/dart-lang/sdk/commit/225a30163700d03111079cf63e2c1cda455f8d9b

I will approve these new failing tests for now.

/cc @sjindel-google

**Comment by sjindel-google** [comment]
The symbol it's looking for was disabled in product mode, but for no good reason.
The should should work fine after https://dart-review.googlesource.com/c/sdk/+/103800
