### ISSUE TITLE
Dart Analyzer Error 	Encountered a Dart Analysis Server error

### ISSUE THREAD

**Issue by missXb** [dart-lang/sdk#37077]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.7141.44`
- `2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec`
- `IU-191.7141.44, JRE 1.8.0_202-release-1483-b49x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec, server version 1.24.0, error: Captured exception
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      _File._buildFileDeclarations (package:analyzer/src/services/available_declarations.dart:1244:39)
#2      _File.refresh (package:analyzer/src/services/available_declarations.dart:1028:7)
#3      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:629:12)
#4      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:494:7)
#5      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:200:13)
<asynchronous suspension>
#6      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#7      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#8      new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#9      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#10     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#11     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:511:21)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:594:12)
#17     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:509:7)
#18     Driver.start (package:analysis_server/src/server/driver.dart:412:7)
#19     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#20     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#21     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#22     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\iLXB\AppData\Local\Temp\report.txt.

**Comment by parlough** [comment]
I believe this is fixed, was the same issue as https://github.com/dart-lang/sdk/issues/36439 so fixed by https://dart-review.googlesource.com/c/sdk/+/98436 which was https://github.com/dart-lang/sdk/commit/0d0f5916f7fc3d0a1267d7b398c9364e88c09a8a

If you update to 2.3.1 or the dev channel you should be good now.
