### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by joe776** [dart-lang/sdk#37099]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Editing code accesing a map inside a lambda.

### Versions

- Dart SDK 2.3.2-dev.0.0
- Visual Studio Code 1.34.0
- Dart Code 3.0.2

### Analyzer Info

The analyzer was launched using the arguments:

```text
/usr/local/Cellar/dart/2.3.2-dev.0.0/libexec/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.0.2
```

### Exception

Exception while using a UnrelatedTypeEqualityChecks to visit a BinaryExpressionImpl in ExpressionStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in ArgumentListImpl in MethodInvocationImpl in AssignmentExpressionImpl in ExpressionStatementImpl in BlockImpl in IfStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl

```text
NoSuchMethodError: The getter 'isObject' was called on null.
Receiver: null
Tried calling: isObject
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      DartTypeUtilities.unrelatedTypes (package:linter/src/util/dart_type_utilities.dart:370:38)
#2      _hasNonComparableOperands (package:linter/src/rules/unrelated_type_equality_checks.dart:145:25)
#3      _Visitor.visitBinaryExpression (package:linter/src/rules/unrelated_type_equality_checks.dart:191:9)
#4      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1003:49)
#5      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#6      LinterVisitor.visitBinaryExpression (package:analyzer/src/lint/linter_visitor.dart:59:5)
#7      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1003:49)
#8      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3776:18)
#9      RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:831:10)
#10     LinterVisitor.visitExpressionStatement (package:analyzer/src/lint/linter_visitor.dart:234:11)
#11     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3772:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7568:20)
#13     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1121:17)
#14     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:663:10)
#15     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:66:11)
#16     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1117:49)
#17     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1076:13)
#18     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:669:10)
#19     LinterVisitor.visitBlockFunctionBody (package:analyzer/src/lint/linter_visitor.dart:72:11)
#20     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1072:49)
#21     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4901:12)
#22     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:909:10)
#23     LinterVisitor.visitFunctionExpression (package:analyzer/src/lint/linter_visitor.dart:312:11)
#24     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4895:49)
#25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7568:20)
#26     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#27     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:621:10)
#28     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#29     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7138:20)
#30     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1053:10)
#31     LinterVisitor.visitMethodInvocation (package:analyzer/src/lint/linter_visitor.dart:456:11)
#32     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7131:49)
#33     AssignmentExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:753:21)
#34     RecursiveAstVisitor.visitAssignmentExpression (package:analyzer/dart/ast/visitor.dart:645:10)
#35     LinterVisitor.visitAssignmentExpression (package:analyzer/src/lint/linter_visitor.dart:48:11)
#36     AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:748:49)
#37     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3776:18)
#38     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:831:10)
#39     LinterVisitor.visitExpressionStatement (package:analyzer/src/lint/linter_visitor.dart:234:11)
#40     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3772:49)
#41     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7568:20)
#42     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1121:17)
#43     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:663:10)
#44     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:66:11)
#45     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1117:49)
#46     IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5585:21)
#47     RecursiveAstVisitor.visitIfStatement (package:analyzer/dart/ast/visitor.dart:957:10)
#48     LinterVisitor.visitIfStatement (package:analyzer/src/lint/linter_visitor.dart:360:11)
#49     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5580:49)
#50     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7568:20)
#51     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1121:17)
#52     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:663:10)
#53     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:66:11)
#54     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1117:49)
#55     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1076:13)
#56     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:669:10)
#57     LinterVisitor.visitBlockFunctionBody (package:analyzer/src/lint/linter_visitor.dart:72:11)
#58     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1072:49)
#59     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7008:12)
#60     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1047:10)
#61     LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:450:11)
#62     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6999:49)
#63     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7568:20)
#64     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1590:13)
#65     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:699:10)
#66     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:102:11)
#67     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1560:49)
#68     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7568:20)
#69     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2167:21)
#70     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:723:10)
#71     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#72     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#73     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:338:10)
#74     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:188:11)
#75     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#76     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:183:35)
#77     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:108:14)
#78     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#79     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:43)
#80     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1450:63)
#81     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#82     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1427:20)
#83     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1227:17)
<asynchronous suspension>
#84     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2162:24)
<asynchronous suspension>
#85     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2092:5)
#86     new AnalysisServer (package:analysis_server/src/analysis_server.dart:207:29)
#87     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#88     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#89     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#90     _rootRun (dart:async/zone.dart:1124:13)
#91     _CustomZone.run (dart:async/zone.dart:1021:19)
#92     _runZoned (dart:async/zone.dart:1516:10)
#93     runZoned (dart:async/zone.dart:1463:12)
#94     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:593:12)
#95     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#96     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#97     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#98     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#99     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#100    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#101    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/joerg/workspaces/finiti/who/webapp/src/main/dart",
        "explicitFileCount": 104,
        "implicitFileCount": 2287,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/joerg/workspaces/finiti/who/webapp/src/main",
        "explicitFileCount": 0,
        "implicitFileCount": 197,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment]
Thanks for reporting this. Apologies that we didn't get to this crash before it became stale. I'll close this, but please re-open if you see it again on a recent version of Dart.
