### ISSUE TITLE
Flutter web - We're sorry, you've found a bug in our compiler.

### ISSUE THREAD

**Issue by NicolasDionB** [dart-lang/sdk#37112]
dartdevc -k arguments: --dart-sdk-summary=D:\_Utils\Flutter\SDK\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/live_app/widgets/themes/app_theme.ddc.js --source-map -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/meta/meta.ddc.dill=packages/meta/meta -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/io.ddc.dill=packages/flutter_web/io -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/src/services/clipboard.ddc.dill=packages/flutter_web/src/services/clipboard -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/services.ddc.dill=packages/flutter_web/services -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/collection/src/utils.ddc.dill=packages/collection/src/utils -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/collection/collection.ddc.dill=packages/collection/collection -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/src/scheduler/binding.ddc.dill=packages/flutter_web/src/scheduler/binding -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/scheduler.ddc.dill=packages/flutter_web/scheduler -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/src/gestures/arena.ddc.dill=packages/flutter_web/src/gestures/arena -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/gestures.ddc.dill=packages/flutter_web/gestures -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/vector_math/hash.ddc.dill=packages/vector_math/hash -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/src/cupertino/activity_indicator.ddc.dill=packages/flutter_web/src/cupertino/activity_indicator -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/flutter_web/material.ddc.dill=packages/flutter_web/material -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/live_app/util/color/tiny_color/hsl_color.ddc.dill=packages/live_app/util/color/tiny_color/hsl_color -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/live_app/util/color/pigment/pigment.ddc.dill=packages/live_app/util/color/pigment/pigment -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/live_app/util/color/tiny_color/conversion.ddc.dill=packages/live_app/util/color/tiny_color/conversion -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/live_app/util/color/tiny_color/tiny_color.ddc.dill=packages/live_app/util/color/tiny_color/tiny_color -s C:\Users\nicolas.dion\AppData\Local\Temp\scratch_space0dc91e0b-821e-11e9-8341-d8fc93281c47\packages/live_app/util/color/material_color.ddc.dill=packages/live_app/util/color/material_color --packages file:///C:/Users/NICOLA~1.DIO/AppData/Local/Temp/kernel_builder_0dc91e0c-821e-11e9-8341-d8fc93281c47/.packages --module-name packages/live_app/widgets/themes/app_theme --multi-root-scheme org-dartlang-app --multi-root . --track-widget-creation --inline-source-map package:live_app/widgets/themes/app_theme_data.dart package:live_app/widgets/themes/app_theme.dart
    dart --version: 2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "windows_x64"

Crash when compiling packages/live_app/widgets/themes/app_theme.dart,
at character offset 2594:
Bad state: No element
#0      List.last (dart:core-patch/array.dart:121:5)
#1      Source.getLocation (package:kernel/ast.dart:6050:59)
#2      Component.getLocation (package:kernel/ast.dart:5812:31)
#3      _getLocationInComponent (package:kernel/ast.dart:6165:22)
#4      Constructor._getLocationInEnclosingFile (package:kernel/ast.dart:1430:12)
#5      TreeNode.location (package:kernel/ast.dart:165:12)
#6      BodyBuilder.throwNoSuchMethodError (package:front_end/src/fasta/kernel/body_builder.dart:1488:27)
#7      BodyBuilder.buildStaticInvocation (package:front_end/src/fasta/kernel/body_builder.dart:3335:13)
#8      BodyBuilder.buildConstructorInvocation (package:front_end/src/fasta/kernel/body_builder.dart:3654:24)
#9      KernelTypeUseGenerator.doInvocation (package:front_end/src/fasta/kernel/kernel_expression_generator.dart:1370:19)
#10     BodyBuilder.finishSend (package:front_end/src/fasta/kernel/body_builder.dart:1304:23)
#11     BodyBuilder.handleSend (package:front_end/src/fasta/kernel/body_builder.dart:1297:12)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4862:14)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4597:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4153:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4092:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3888:13)
#17     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3913:17)
#18     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3860:13)
#19     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3825:13)
#20     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5209:16)
#21     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3650:14)
#22     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3640:20)
#23     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3545:15)
#24     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:834:14)
#25     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:587:5)
#26     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3198:14)
#27     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3064:15)
#28     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2865:15)
#29     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1846:13)
#30     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1806:14)
#31     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:640:14)
#32     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:532:14)
#33     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:347:15)
#34     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:278:14)
<asynchronous suspension>
#35     Loader.buildBodies (package:front_end/src/fasta/loader.dart:186:15)
<asynchronous suspension>
#36     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:301:20)
<asynchronous suspension>
#37     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#38     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:299:12)
<asynchronous suspension>
#39     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:308:28)
<asynchronous suspension>
#40     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#41     new Future.sync (dart:async/future.dart:224:31)
#42     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _runZoned (dart:async/zone.dart:1516:10)
#46     runZoned (dart:async/zone.dart:1463:12)
#47     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#48     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:127:20)
<asynchronous suspension>
#49     _compile (package:dev_compiler/src/kernel/command.dart:268:64)
<asynchronous suspension>
#50     compile (package:dev_compiler/src/kernel/command.dart:41:18)
<asynchronous suspension>
#51     compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#52     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:54:39)
#53     _rootRun (dart:async/zone.dart:1124:13)
#54     _CustomZone.run (dart:async/zone.dart:1021:19)
#55     _runZoned (dart:async/zone.dart:1516:10)
#56     runZoned (dart:async/zone.dart:1463:12)
#57     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:54:24)
<asynchronous suspension>
#58     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#59     _rootRun (dart:async/zone.dart:1124:13)
#60     _CustomZone.run (dart:async/zone.dart:1021:19)
#61     _runZoned (dart:async/zone.dart:1516:10)
#62     runZoned (dart:async/zone.dart:1463:12)
#63     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#64     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#65     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:842:7)
#1      DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:587:5)
#2      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3198:14)
#3      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3064:15)
#4      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2865:15)
#5      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1846:13)
#6      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1806:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:640:14)
#8      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:532:14)
#9      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:347:15)
#10     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:278:14)
<asynchronous suspension>
#11     Loader.buildBodies (package:front_end/src/fasta/loader.dart:186:15)
<asynchronous suspension>
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:301:20)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#14     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:299:12)
<asynchronous suspension>
#15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:308:28)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#17     new Future.sync (dart:async/future.dart:224:31)
#18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#24     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:127:20)
<asynchronous suspension>
#25     _compile (package:dev_compiler/src/kernel/command.dart:268:64)
<asynchronous suspension>
#26     compile (package:dev_compiler/src/kernel/command.dart:41:18)
<asynchronous suspension>
#27     compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#28     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:54:39)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:54:24)
<asynchronous suspension>
#34     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#40     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

**Comment by NicolasDionB** [comment]
More details with this bug report, it happens when I define the "actionsIconTheme" property on AppBarTheme. Same if I define it on the AppBar widget directly.

**Comment by laptopmutia** [comment]
the stacktrace should be wrapped on code tag because u mentioning all other issue with that `#number`

**Comment by modulovalue** [comment]
@lrhn looks like we can close this since there are no repro steps and after 7 years it's very stale and most likely already fixed.
