### ISSUE TITLE
Regression test for flaky crash of ffi/function_callbacks_test/00 in GC

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#37133]
[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8911936099078552096/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0)

```
  --- Command "vm" (took 02.000272s):
  DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --optimization-counter-threshold=5 --random-seed=1982458737 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseX64/generated_tests/ffi/function_callbacks_test_00.dart
  exit code:
  -6
  stderr:
  ===== CRASH =====
  si_signo=Segmentation fault(11), si_code=1, si_addr=0x30
  version=2.3.2-edge.a620c56e8db83ef5330b030178d2a7ddde6dfde6 (Fri May 31 14:20:24 2019 +0000) on "linux_x64"
  thread=18908, isolate=main(0x55fbc33d0100)
    pc 0x000055fbc250842f fp 0x00007f88b53beac0 out/ReleaseX64/dart+0x1a2142f
    pc 0x000055fbc237e8e0 fp 0x00007f88b53beb50 dart::StackFrame::VisitObjectPointers(dart::ObjectPointerVisitor*)
    pc 0x000055fbc238d73c fp 0x00007f88b53bec70 dart::Thread::VisitObjectPointers(dart::ObjectPointerVisitor*, dart::ValidationPolicy)
    pc 0x000055fbc23903be fp 0x00007f88b53becb0 dart::ThreadRegistry::VisitObjectPointers(dart::ObjectPointerVisitor*, dart::ValidationPolicy)
    pc 0x000055fbc2506a78 fp 0x00007f88b53bed40 dart::GCMarker::IterateRoots(dart::ObjectPointerVisitor*)
    pc 0x000055fbc2507f7f fp 0x00007f88b53bedb0 out/ReleaseX64/dart+0x1a20f7f
    pc 0x000055fbc2390057 fp 0x00007f88b53bede0 dart::ThreadPool::Worker::Loop()
    pc 0x000055fbc238ff15 fp 0x00007f88b53bee20 dart::ThreadPool::Worker::Main(unsigned long)
    pc 0x000055fbc22f8b69 fp 0x00007f88b53beed0 out/ReleaseX64/dart+0x1811b69
  -- End of DumpStackTrace
  --- Re-run this test:
  python tools/test.py -n dartk-optcounter-linux-release-x64 ffi/function_callbacks_test/00
```

Repro steps:

1. To generate the test, run it once with '-k':

```
tools/test.py -k -n dartk-optcounter-linux-release-x64 ffi/function_callbacks_test/00
```

2. Run the following bash script to execute test in a loop:

```
set -e
for i in {1..1000}; do
  echo "========= $i ========="
  out/ReleaseX64/dart --optimization-counter-threshold=5 --random-seed=1982458737 out/ReleaseX64/generated_tests/ffi/function_callbacks_test_00.dart
done
```

Crash was reproduced after 78 and then 55 iterations.

/cc @dcharkes @sjindel-google

**Comment by mkustermann** [comment]
There's more of those callback tests flakily crashing, e.g.
```
/=======================================================\
| ffi/function_callbacks_test/03 succeeded again (Pass) |
\=======================================================/

--- Command "vm" (took 07.000860s):
DART_CONFIGURATION=ProductX64 xcodebuild/ProductX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ProductX64/generated_tests/ffi/function_callbacks_test_03.dart

exit code:
-6

stderr:
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x30

--- Re-run this test:
python tools/test.py -n dartk-mac-product-x64 ffi/function_callbacks_test/03
```

**Comment by sjindel-google** [comment]
Thanks for the script Alex, I was able to reproduce it locally in RR.

**Comment by sjindel-google** [comment]
I've landed https://dart-review.googlesource.com/c/sdk/+/104822 to fix the underlying bug, but I'll keep the issue open to create a regression test.

**Comment by sjindel-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/105590

**Comment by dcharkes** [comment]
@sjindel-google landing this created a crash: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8910409401946450944/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0

```
/=====================================================================\
| ffi/function_callbacks_test/00 broke (Pass -> Crash, expected Pass) |
\=====================================================================/

--- Command "vm" (took 03.000421s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --no-background-compilation --hot-reload-test-mode --enable-testing-pragmas --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/DebugX64/generated_tests/ffi/function_callbacks_test_00.dart

exit code:
-6

stdout:
Expect "unhandled exception" error message to follow.
==================== UNHANDLED EXCEPTION FROM FFI CALLBACK ====================
 ** Native callbacks should not throw exceptions because they cannot be
    propagated into native code. **
EXCEPTION: NoSuchMethodError: The method 'FfiCallback' was called on null.
Receiver: null
Tried calling: FfiCallback()
#0      FfiCallback (dart:ffi)
#1      FfiTrampoline (dart:ffi)
#2      Test.run (file:///b/s/w/ir/cache/builder/sdk/out/DebugX64/generated_tests/ffi/function_callbacks_test_00.dart:38:32)
#3      main.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/out/DebugX64/generated_tests/ffi/function_callbacks_test_00.dart:196:30)
#4      List.forEach (dart:core-patch/growable_array.dart:278:8)
#5      main (file:///b/s/w/ir/cache/builder/sdk/out/DebugX64/generated_tests/ffi/function_callbacks_test_00.dart:196:13)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

==================== UNHANDLED EXCEPTION FROM FFI CALLBACK ====================
 ** Native callbacks should not throw exceptions because they cannot be
    propagated into native code. **

stderr:
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x2
version=2.3.3-edge.43382ded6d8fcc5c75189e1aad9de14da0ec55c6 (Mon Jun 17 10:47:00 2019 +0000) on "linux_x64"
thread=26720, isolate=main(0x560565ed6c00)
  pc 0x000056056417bc7f fp 0x00007fb85957c7e0 out/DebugX64/dart+0x1c62c7f
  pc 0x0000560563f8c660 fp 0x00007fb85957c890 dart::StackFrame::VisitObjectPointers(dart::ObjectPointerVisitor*)
  pc 0x0000560563fa289c fp 0x00007fb85957c9b0 dart::Thread::VisitObjectPointers(dart::ObjectPointerVisitor*, dart::ValidationPolicy)
  pc 0x0000560563fa85ce fp 0x00007fb85957ca00 dart::ThreadRegistry::VisitObjectPointers(dart::ObjectPointerVisitor*, dart::ValidationPolicy)
  pc 0x000056056417baa6 fp 0x00007fb85957ca60 dart::Become::FollowForwardingPointers(dart::Thread*)
  pc 0x000056056417b7e1 fp 0x00007fb85957cb40 dart::Become::ElementsForwardIdentity(dart::Array const&, dart::Array const&)
  pc 0x0000560563dd6e37 fp 0x00007fb85957ccd0 dart::IsolateReloadContext::Commit()
  pc 0x0000560563dd4105 fp 0x00007fb85957ccf0 dart::IsolateReloadContext::FinalizeLoading()
  pc 0x0000560563dd2347 fp 0x00007fb85957ce60 dart::IsolateReloadContext::Reload(bool, char const*, char const*, unsigned char const*, long)
  pc 0x0000560563dc7fa5 fp 0x00007fb85957cec0 dart::Isolate::ReloadSources(dart::JSONStream*, bool, char const*, char const*, bool)
  pc 0x0000560563f5c93e fp 0x00007fb85957d0c0 dart::DRT_StackOverflow(dart::NativeArguments)
  pc 0x00007fb859681197 fp 0x00007fb85957d108 Unknown symbol
  pc 0x00007fb8562fde04 fp 0x00007fb85957d178 Unknown symbol
  pc 0x00007fb8562fd683 fp 0x00007fb85957d1e8 Unknown symbol
  pc 0x00007fb854906fee fp 0x00007fb85957d2a0 Unknown symbol
  pc 0x00007fb8562fd290 fp 0x00007fb85957d308 Unknown symbol
  pc 0x00007fb854905b4b fp 0x00007fb85957d338 Unknown symbol
  pc 0x00007fb8562fb1f3 fp 0x00007fb85957d3a0 Unknown symbol
  pc 0x00007fb8596816a0 fp 0x00007fb85957d400 Unknown symbol
  pc 0x0000000000000000 fp 0x00007fb85957d410 Unknown symbol
  pc 0x00007fb854a00cd1 fp 0x00007fb85957d440 /b/s/w/ir/cache/builder/sdk/out/DebugX64/libffi_test_functions.so+0x61cd1
  pc 0x00007fb85490cdd1 fp 0x00007fb85957d460 Unknown symbol
  pc 0x00007fb85490cd81 fp 0x00007fb85957d490 Unknown symbol
  pc 0x00007fb8562cb01f fp 0x00007fb85957d4d0 Unknown symbol
  pc 0x00007fb85490c7fa fp 0x00007fb85957d520 Unknown symbol
  pc 0x00007fb85490c54e fp 0x00007fb85957d568 Unknown symbol
  pc 0x00007fb8562fb470 fp 0x00007fb85957d5c0 Unknown symbol
  pc 0x00007fb8562f6862 fp 0x00007fb85957d658 Unknown symbol
  pc 0x00007fb8562eb51c fp 0x00007fb85957d690 Unknown symbol
  pc 0x00007fb8562f611b fp 0x00007fb85957d6c8 Unknown symbol
  pc 0x00007fb8562f4c19 fp 0x00007fb85957d720 Unknown symbol
  pc 0x00007fb8562f4770 fp 0x00007fb85957d760 Unknown symbol
  pc 0x00007fb8562eb51c fp 0x00007fb85957d798 Unknown symbol
  pc 0x00007fb8562f3824 fp 0x00007fb85957d7e0 Unknown symbol
  pc 0x00007fb8562cb01f fp 0x00007fb85957d820 Unknown symbol
  pc 0x00007fb8562f34d3 fp 0x00007fb85957d858 Unknown symbol
  pc 0x00007fb85968173a fp 0x00007fb85957d8c8 Unknown symbol
  pc 0x0000560563d767c5 fp 0x00007fb85957d970 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  pc 0x0000560563d79a81 fp 0x00007fb85957d9e0 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  pc 0x0000560563dc41b9 fp 0x00007fb85957dbe0 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)
  pc 0x0000560563e06610 fp 0x00007fb85957dc70 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x0000560563e07426 fp 0x00007fb85957dcf0 dart::MessageHandler::TaskCallback()
  pc 0x0000560563fa7acc fp 0x00007fb85957dd40 dart::ThreadPool::Worker::Loop()
  pc 0x0000560563fa75a4 fp 0x00007fb85957dd90 dart::ThreadPool::Worker::Main(unsigned long)
  pc 0x0000560563ee4c95 fp 0x00007fb85957ded0 out/DebugX64/dart+0x19cbc95
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -n dartk-reload-linux-debug-x64 ffi/function_callbacks_test/00
```

**Comment by sjindel-google** [comment]
Filed #37311, which appears to be a separate bug than the original issue.
