### ISSUE TITLE
Crash when trying to update flutter for web project

### ISSUE THREAD

**Issue by lordgreg** [dart-lang/sdk#37131]
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Crash when trying to update flutter for web project

### Versions

- Flutter SDK 1.6.7-pre.45
- Visual Studio Code 1.34.0
- Dart Code 3.0.2

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/USER_NAME/Library/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.0.2
```

### Exception

Failed to handle completion domain request: {id: 5398, method: completion.getSuggestions, params: {file: /Users/USER_NAME/Projects/____/MY_FLUTTER_WEB_PROJECT/web/main.dart, offset: 124}, clientRequestTime: 1559310998893}

```text
NoSuchMethodError: The getter 'librarySource' was called on null.
Receiver: null
Tried calling: librarySource
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      createExistingImportsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:94:52)
#2      CompletionDomainHandler.processRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:403:11)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#8      Future._complete (dart:async/future_impl.dart:473:7)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#12     CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart)
<asynchronous suspension>
#13     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#14     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#20     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:45)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:317:50)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1500:12)
#27     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:316:5)
#28     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#29     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#30     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#31     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#40     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#41     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#42     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#49     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#50     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#51     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#52     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#53     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#54     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#55     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#56     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#57     _rootRunUnary (dart:async/zone.dart:1132:38)
#58     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#62     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#63     _StreamController._add (dart:async/stream_controller.dart:640:7)
#64     _StreamController.add (dart:async/stream_controller.dart:586:5)
#65     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#66     _rootRunUnary (dart:async/zone.dart:1136:13)
#67     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#68     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#69     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#70     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#71     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#72     _StreamController._add (dart:async/stream_controller.dart:640:7)
#73     _StreamController.add (dart:async/stream_controller.dart:586:5)
#74     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#75     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#76     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#77     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#78     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#79     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/USER_NAME/Projects/____/MY_FLUTTER_WEB_PROJECT",
        "explicitFileCount": 48,
        "implicitFileCount": 1494,
        "workItemQueueLength": 47,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment]
This has not been reported again since Flutter 1.6; please re-open if you see this in a recent version of Dart/Flutter.
