### ISSUE TITLE
Dart Analysis Server crash on flutter plugin development

### ISSUE THREAD

**Issue by leoneparise** [dart-lang/sdk#37148]
I'm developing a new plugin for flutter framework. When I do a `pod install`, which create a `.symlinks` into `example/ios` folder, it crashes the Dart Analysis Server.

Is there a way to prevent the analyzer to follow the `.symlinks` folder?.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5522156`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-183.6156.11.34.5522156, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: FileSystemException(path=/Users/leone/Development/Workspaces/Other/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/wallet_core/example/ios/.symlinks/plugins/path_provider/example/android/app/src/main/java/io/flutter/plugins/pathproviderexample/MainActivity; message=Directory listing failed)
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:334:7)
#1      _OverlayFolder.getChildren (package:analyzer/file_system/overlay_file_system.dart:334:10)
#2      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1144:32)
#3      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#4      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#5      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#6      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#7      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#8      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#9      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#10     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#11     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#12     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#13     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#14     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#15     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#16     ContextManagerImpl

**Comment by DanTup** [comment]
This is the same issue as https://github.com/dart-lang/sdk/issues/36919.

**Comment by DanTup** [comment]
It turns out this issue is fixed, but the fix hasn't made the Flutter stable channel. You could try switching to beta/dev as a short-term fix until the fix reaches stable.
