### ISSUE TITLE
Crash with DDK

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#37145]
```
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/Users/kevmoo/homebrew/Cellar/dart/2.3.2-dev.0.0/libexec/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o web/main.ddc.js --source-map -s packages/meta/meta.ddc.dill=packages/meta/meta -s packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui -s packages/collection/src/utils.ddc.dill=packages/collection/src/utils -s packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms -s packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip -s packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators -s packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue -s packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map -s packages/collection/collection.ddc.dill=packages/collection/collection -s packages/flutter_web/io.ddc.dill=packages/flutter_web/io -s packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers -s packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions -s packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation -s packages/flutter_web/src/services/clipboard.ddc.dill=packages/flutter_web/src/services/clipboard -s packages/flutter_web/services.ddc.dill=packages/flutter_web/services -s packages/flutter_web/src/scheduler/binding.ddc.dill=packages/flutter_web/src/scheduler/binding -s packages/flutter_web/scheduler.ddc.dill=packages/flutter_web/scheduler -s packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation -s packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics -s packages/flutter_web/src/gestures/arena.ddc.dill=packages/flutter_web/src/gestures/arena -s packages/flutter_web/gestures.ddc.dill=packages/flutter_web/gestures -s packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation -s packages/vector_math/hash.ddc.dill=packages/vector_math/hash -s packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 -s packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation -s packages/flutter_web/src/cupertino/activity_indicator.ddc.dill=packages/flutter_web/src/cupertino/activity_indicator -s packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino -s packages/flutter_web/material.ddc.dill=packages/flutter_web/material -s packages/provider/provider.ddc.dill=packages/provider/provider -s packages/graphs/graphs.ddc.dill=packages/graphs/graphs -s packages/vote/src/ballot.ddc.dill=packages/vote/src/ballot -s packages/knarly/main.ddc.dill=packages/knarly/main --packages file:///var/folders/c0/jv6k5x0j57vcwkdx6rcjgj3w0071_k/T/kernel_builder_TK0zEI/.packages --module-name web/main --multi-root-scheme org-dartlang-app --multi-root . --track-widget-creation --inline-source-map web/main.dart
    dart --version: 2.3.2-dev.0.0 (Tue May 21 22:23:41 2019 +0200) on "macos_x64"

Crash when compiling null,
at character offset null:
Cannot add a child to root because this name already has a child named package:knarly/src/vote_town_widget.dart
#0      CanonicalName.adoptChild (package:kernel/canonical_name.dart:149:7)
#1      Component.adoptChildren (package:kernel/ast.dart:5770:16)
#2      new Component (package:kernel/ast.dart:5758:5)
#3      KernelTarget.link (package:front_end/src/fasta/kernel/kernel_target.dart:343:64)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:269:11)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:249:12)
<asynchronous suspension>
#7      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:299:52)
<asynchronous suspension>
#8      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#16     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:127:20)
<asynchronous suspension>
#17     _compile (package:dev_compiler/src/kernel/command.dart:273:64)
<asynchronous suspension>
#18     compile (package:dev_compiler/src/kernel/command.dart:41:18)
<asynchronous suspension>
#19     compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#20     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#26     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#32     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)


#0      CanonicalName.adoptChild (package:kernel/canonical_name.dart:149:7)
#1      Component.adoptChildren (package:kernel/ast.dart:5770:16)
#2      new Component (package:kernel/ast.dart:5758:5)
#3      KernelTarget.link (package:front_end/src/fasta/kernel/kernel_target.dart:343:64)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:269:11)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:249:12)
<asynchronous suspension>
#7      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:299:52)
<asynchronous suspension>
#8      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#16     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:127:20)
<asynchronous suspension>
#17     _compile (package:dev_compiler/src/kernel/command.dart:273:64)
<asynchronous suspension>
#18     compile (package:dev_compiler/src/kernel/command.dart:41:18)
<asynchronous suspension>
#19     compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#20     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#26     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#32     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by Markzipan** [comment]
Closing this for now - But please revive if this still reproduces.
