### ISSUE TITLE
"Missing canonical name" frontend_server crash when using config imports and constants

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#37149]
The failure log is from the CI task: https://cirrus-ci.com/task/6488592017260544

```
[gradle_plugin_test] [STDOUT] Unhandled exception:
[gradle_plugin_test] [STDOUT] Invalid argument(s): Missing canonical name for Reference to typedef _ComputeImpl = <Q extends dart.core::Object = dynamic, R extends dart.core::Object = dynamic>((Q) ??? dart.async::FutureOr<R>, Q, {debugLabel: dart.core::String}) ??? dart.async::Future<R>;
[gradle_plugin_test] [STDOUT] 
[gradle_plugin_test] [STDOUT] #0      BinaryPrinter.writeNullAllowedReference (package:kernel/binary/ast_to_binary.dart:819:9)
[gradle_plugin_test] [STDOUT] #1      BinaryPrinter.visitTypedefType (package:kernel/binary/ast_to_binary.dart:2064:5)
[gradle_plugin_test] [STDOUT] #2      TypedefType.accept (package:kernel/ast.dart:5073:34)
[gradle_plugin_test] [STDOUT] #3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:378:10)
[gradle_plugin_test] [STDOUT] #4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
[gradle_plugin_test] [STDOUT] #5      BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:464:7)
[gradle_plugin_test] [STDOUT] #6      BinaryPrinter.visitFunctionType (package:kernel/binary/ast_to_binary.dart:2042:7)
[gradle_plugin_test] [STDOUT] #7      FunctionType.accept (package:kernel/ast.dart:4956:34)
[gradle_plugin_test] [STDOUT] #8      BinaryPrinter.writeDartType (package:kernel/binary/ast_to_binary.dart:266:10)
[gradle_plugin_test] [STDOUT] #9      CallSiteAttributesMetadataRepository.writeToBinary (package:vm/metadata/call_site_attributes.dart:34:10)
[gradle_plugin_test] [STDOUT] #10     BinaryPrinter._writeNodeMetadataImpl (package:kernel/binary/ast_to_binary.dart:602:18)
[gradle_plugin_test] [STDOUT] #11     BinaryPrinter._writeNodeMetadata (package:kernel/binary/ast_to_binary.dart:577:5)
[gradle_plugin_test] [STDOUT] #12     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:376:7)
[gradle_plugin_test] [STDOUT] #13     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
[gradle_plugin_test] [STDOUT] #14     BinaryPrinter.visitVariableSet (package:kernel/binary/ast_to_binary.dart:1332:7)
[gradle_plugin_test] [STDOUT] #15     VariableSet.accept (package:kernel/ast.dart:2292:36)
[gradle_plugin_test] [STDOUT] #16     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:378:10)
[gradle_plugin_test] [STDOUT] #17     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
[gradle_plugin_test] [STDOUT] #18     BinaryPrinter.visitExpressionStatement (package:kernel/binary/ast_to_binary.dart:1742:5)
[gradle_plugin_test] [STDOUT] #19     ExpressionStatement.accept (package:kernel/ast.dart:3913:35)
[gradle_plugin_test] [STDOUT] #20     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:378:10)
[gradle_plugin_test] [STDOUT] #21     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
[gradle_plugin_test] [STDOUT] #22     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:297:7)
[gradle_plugin_test] [STDOUT] #23     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1750:5)
[gradle_plugin_test] [STDOUT] #24     Block.accept (package:kernel/ast.dart:3941:35)
[gradle_plugin_test] [STDOUT] #25     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:378:10)
[gradle_plugin_test] [STDOUT] #26     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
[gradle_plugin_test] [STDOUT] #27     BinaryPrinter.visitLabeledStatement (package:kernel/binary/ast_to_binary.dart:1784:5)
[gradle_plugin_test] [STDOUT] #28     LabeledStatement.accept (package:kernel/ast.dart:4044:35)
[gradle_plugin_test] [STDOUT] #29     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:378:10)
[gradle_plugin_test] [STDOUT] #30     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
[gradle_plugin_test] [STDOUT] #31     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:297:7)
[gradle_plugin_test] [STDOUT] #32     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1750:5)
[gradle_plugin_test] [STDOUT] #33     Block.accept (package:kernel/ast.dart:3941:35)
[gradle_plugin_test] [STDOUT] #34     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:378:10)
[gradle_plugin_test] [STDOUT] #35     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
[gradle_plugin_test] [STDOUT] #36     BinaryPrinter.visitTryCatch (package:kernel/binary/ast_to_binary.dart:1901:5)
[gradle_plugin_test] [STDOUT] #37     TryCatch.accept (package:kernel/ast.dart:4387:35)
[gradle_plugin_test] [STDOUT] #38     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:378:10)
[gradle_plugin_test] [STDOUT] #39     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
[gradle_plugin_test] [STDOUT] #40     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:464:7)
[gradle_plugin_test] [STDOUT] #41     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1291:5)
[gradle_plugin_test] [STDOUT] #42     FunctionNode.accept (package:kernel/ast.dart:2115:30)
[gradle_plugin_test] [STDOUT] #43     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:385:10)
[gradle_plugin_test] [STDOUT] #44     BinaryPrinter.visitFunctionDeclaration (package:kernel/binary/ast_to_binary.dart:1977:5)
[gradle_plugin_test] [STDOUT] #45     FunctionDeclaration.accept (package:kernel/ast.dart:4682:35)
[gradle_plugin_test] [STDOUT] #46     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:378:10)
[gradle_plugin_test] [STDOUT] #47     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
[gradle_plugin_test] [STDOUT] #48     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:297:7)
[gradle_plugin_test] [STDOUT] #49     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1750:5)
[gradle_plugin_test] [STDOUT] #50     Block.accept (package:kernel/ast.dart:3941:35)
[gradle_plugin_test] [STDOUT] #51     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:378:10)
[gradle_plugin_test] [STDOUT] #52     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
[gradle_plugin_test] [STDOUT] #53     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:464:7)
[gradle_plugin_test] [STDOUT] #54     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1291:5)
[gradle_plugin_test] [STDOUT] #55     FunctionNode.accept (package:kernel/ast.dart:2115:30)
[gradle_plugin_test] [STDOUT] #56     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:385:10)
[gradle_plugin_test] [STDOUT] #57     BinaryPrinter.writeOptionalFunctionNode (package:kernel/binary/ast_to_binary.dart:473:7)
[gradle_plugin_test] [STDOUT] #58     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1167:5)
[gradle_plugin_test] [STDOUT] #59     Procedure.accept (package:kernel/ast.dart:1777:32)
[gradle_plugin_test] [STDOUT] #60     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:406:10)
[gradle_plugin_test] [STDOUT] #61     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:306:7)
[gradle_plugin_test] [STDOUT] #62     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1095:5)
[gradle_plugin_test] [STDOUT] #63     Class.accept (package:kernel/ast.dart:1010:30)
[gradle_plugin_test] [STDOUT] #64     BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:420:10)
[gradle_plugin_test] [STDOUT] #65     BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:324:7)
[gradle_plugin_test] [STDOUT] #66     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:928:5)
[gradle_plugin_test] [STDOUT] #67     Library.accept (package:kernel/ast.dart:435:30)
[gradle_plugin_test] [STDOUT] #68     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:399:10)
[gradle_plugin_test] [STDOUT] #69     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:52:31)
[gradle_plugin_test] [STDOUT] #70     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:540:5)
[gradle_plugin_test] [STDOUT] #71     FrontendCompiler.writeDillFile (package:vm/frontend_server.dart:433:13)
[gradle_plugin_test] [STDOUT] <asynchronous suspension>
[gradle_plugin_test] [STDOUT] #72     FrontendCompiler.compile (package:vm/frontend_server.dart:371:13)
[gradle_plugin_test] [STDOUT] <asynchronous suspension>
[gradle_plugin_test] [STDOUT] #73     _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:31:22)
[gradle_plugin_test] [STDOUT] <asynchronous suspension>
[gradle_plugin_test] [STDOUT] #74     starter (package:frontend_server/server.dart:128:27)
[gradle_plugin_test] [STDOUT] <asynchronous suspension>
[gradle_plugin_test] [STDOUT] #75     main (file:///b/s/w/ir/k/src/flutter/frontend_server/bin/starter.dart:8:30)
[gradle_plugin_test] [STDOUT] <asynchronous suspension>
[gradle_plugin_test] [STDOUT] #76     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
[gradle_plugin_test] [STDOUT] #77     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
[gradle_plugin_test] [STDOUT] 
[gradle_plugin_test] [STDOUT] Compiler terminated unexpectedly.
[gradle_plugin_test] [STDOUT] 
[gradle_plugin_test] [STDOUT] FAILURE: Build failed with an exception.
```

This occurred in the PR https://github.com/flutter/flutter/pull/33663, specifically on https://github.com/flutter/flutter/pull/33663/commits/d1ad89a66de775708800b03379b38fd953b09ea4#diff-9c8178fbc28fe11397bd57df314a2643R47

isolates.dart
```
import '_isolates_io.dart'
  if (dart.library.html) '_isolates_web.dart' as _isolates;

typedef _ComputeImpl = Future<R> Function<Q, R>(ComputeCallback<Q, R> callback, Q message, { String debugLabel })

const _ComputeImpl compute = _isolates.compute;
```

_isolates_io.dart
```
Future<R> compute<Q, R>(isolates.ComputeCallback<Q, R> callback, Q message, { String debugLabel }) async {
  ...
}
```

**Comment by jensjoha** [comment]
Reproduction:
Change "final" to "const" @ https://github.com/flutter/flutter/blob/fa174a123fb603332e4870ccdd80bff9a1889f5b/packages/flutter/lib/src/foundation/isolates.dart#L49

Run something like
```
/path/to/flutter/bin/cache/dart-sdk/bin/dart pkg/vm/bin/frontend_server_starter.dart --sdk-root /path/to/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --strong --target=flutter --aot --tfa --output-dill issue_37149_test.dill --packages /path/to/flutter/examples/flutter_gallery/.packages/path/to/flutter/examples/flutter_gallery/lib/main.dart
```
from the dart sdk.

You get the crash.

Notice, though, that if you remove the "--tfa" it works fine (i.e. doesn't crash).

I'll try to investigate a little further, but the "tfa" thing is a pkg/vm special and I don't know much about it... It's owned by the VM.

**Comment by jensjoha** [comment]
It seems to me that the type flow transformer doesn't know about the call site attribute metadata stuff (notice this part of the stacktrace: `CallSiteAttributesMetadataRepository.writeToBinary (package:vm/metadata/call_site_attributes.dart:34:10)`).
So I think something like this is happening:
A call site attribute is added that (via a FunctionType) points to the typedef.
The typedef is not otherwise used and thus removed.
The component is attempted serialized, but when we get to the metadata it fails because it points to something that was removed...
@alexmarkov @mraleph I'm removing area-front-end and adding to area-vm instead.

**Comment by mraleph** [comment]
@alexmarkov could you take a look at this? I guess tree-shaker needs to prune call-site attributes if they refer to shaken things.

**Comment by alexmarkov** [comment]
@mraleph Call site annotator runs after TFA tree shaker, so tree shaker can't possibly prune attributes which are added later. Maybe call site annotator should prune function types to avoid referencing removed typedefs. I'll take a look.

**Comment by alexmarkov** [comment]
The problem is that `type` field was added to ConstantExpression nodes (in 4ab4545ff707a5c4d2525727d326bedaa73caad2), but TFA tree shaker was not updated to visit that field. This results in dangling references to typedefs.

Call site annotator can obtain that type via `ConstantExpression.getStaticType()`. Even without call site annotator, serialization of ConstantExpression crashes when `type` is written.

https://dart-review.googlesource.com/c/sdk/+/106384 should fix the problem.
