### ISSUE TITLE
Error in AssistProcessor when computing code fixes for LSP

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#37159]
When computing code fixes in the LSP server, I've started seeing this failure.

The issue seems to be that in the `_addProposal_convertMapFromIterableToForLiteral` method, `creation.staticElement` returns `null`. So far I'm unable to reproduce it outside of LSP (even though it seems like it should repro without it).

```
[Error - 11:22:15 AM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 11:22:15 AM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AssistProcessor._addProposal_convertMapFromIterableToForLiteral (package:analysis_server/src/services/correction/assist_internal.dart:977:17)
<asynchronous suspension>
#2      AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:155:13)
<asynchronous suspension>
#3      CodeActionHandler._getAssistActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:141:39)
<asynchronous suspension>
#4      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:166:7)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#6      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:153:70)
#7      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:63:18)
#8      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:216:12)
#9      CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:60:26)
#10     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:216:12)
#11     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:59:26)
#12     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:216:12)
#13     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:56:17)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#24     _MessageHandler&Object&Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#25     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#31     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#32     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

If I tweak the code to print the source it's processing like this:

```dart
if (element == null) {
  throw 'Element was null! ${creation}\n\n${creation.toSource()}';
}
```

This is what it prints:

```
[Error - 11:25:01 AM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 11:25:01 AM] An error occurred while handling textDocument/codeAction request: Element was null! new Row(children: <Widget>[new Text('a'), new Text('b')])

new Row(children: <Widget>[new Text('a'), new Text('b')])
#0      AssistProcessor._addProposal_convertMapFromIterableToForLiteral (package:analysis_server/src/services/correction/assist_internal.dart:975:7)
<asynchronous suspension>
```

The full file looks like this:

```dart
import 'dart:io';

main() async {
  print("test");
  var b = [1, 2].map((i) => i == 0).toList();

  print(b.length);

  print(stdin);

  await 1;
}

Widget build(BuildContext context) {
  return new Row(
    // Row       1:9
    children: <Widget>[
      // Widget[]  2:14
      new Text('a'),
      new Text('b'),
    ], // /Widget[] 5:5
  ); // /Row      6:3
}
```

**Comment by DanTup** [comment]
@bwilkerson @scheglov FYI... I can't figure out why I can't hit this for non-LSP using the same code (same source I have open, and running server from same code locally, just without `--lsp`).

FWIW, this is *not* a Flutter project, it's just a random Dart CLI app I use for testing (so the Row class etc. does not resolve and there are errors in the file).

**Comment by DanTup** [comment]
I hit it again when selecting the highlighted text.

When double-clicking the word "ProcessResult" here, VS Code sent a request for code actions, and this crash happened.

![Screenshot 2019-06-25 at 7 50 07 am](https://user-images.githubusercontent.com/1078012/60075811-0cbc7080-971e-11e9-825e-f6967ea52e46.png)

```
[Error - 7:47:23 AM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 7:47:23 AM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AssistProcessor._addProposal_convertMapFromIterableToForLiteral (package:analysis_server/src/services/correction/assist_internal.dart:974:17)
<asynchronous suspension>
#2      AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:155:13)
<asynchronous suspension>
#3      CodeActionHandler._getAssistActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:142:39)
<asynchronous suspension>
#4      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:167:7)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#6      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:154:70)
#7      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:64:18)
#8      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:217:12)
#9      CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:61:26)
#10     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:217:12)
#11     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:60:26)
#12     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:217:12)
#13     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:57:17)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/107307

**Comment by DanTup** [comment]
Thanks! Hopefully NNBD will help here in future!

I'm not sure why this didn't repro for non-LSP though, maybe something was handling the error somewhere.. I didn't dig too far.
