### ISSUE TITLE
Cookie validate failed

### ISSUE THREAD

**Issue by uaex** [dart-lang/sdk#37166]
Case: response contains a cookie like `urlgen="{\"abcdef\":123456}"` 
I catch an exception from http_headers.dart _validate() 
`new FormatException(
            "Invalid character in cookie value, code unit: '$codeUnit'"); `
codeUnit is 92("\\")
after all we can't decide what we received, how should we avoid it? 🤔

**Comment by devoncarew** [comment]
Can you add a stack trace to help illustrate the issue?

**Comment by uaex** [comment]
`Cookie.fromSetCookieValue("urlgen=\"{\\\"abcdef\\\":123456}\"");`
Stack:
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: FormatException: Invalid character in cookie value, code unit: '92'
#0      _Cookie._validate (dart:_http/http_headers.dart:999:9)
#1      _Cookie._parseSetCookieValue (dart:_http/http_headers.dart:933:5)
#2      new _Cookie.fromSetCookieValue (dart:_http/http_headers.dart:849:5)
#3      new Cookie.fromSetCookieValue (dart:_http:975:16)
#4      _MyHomePageState.doIWant (package:my_app/main.dart:182:12)
...

**Comment by hygehyge** [comment]
I have a similar issue.
When I get a cookie with white space(32), http_headers_impl.dart _validate throws FormatException.
Below is a minimum code that reproduce the isuue.
`Cookie.fromSetCookieValue('CSPWSERVERID=Cache for Windows (x86-64) 2017.2 (Build 744U) Fri Sep 29 2017 10:58:27 EDT');`

Stack trace:

```
#0      _Cookie._validate (dart:_http/http_headers.dart:1009:9)
#1      _Cookie._parseSetCookieValue (dart:_http/http_headers.dart:933:5)
#2      new _Cookie.fromSetCookieValue (dart:_http/http_headers.dart:849:5)
#3      new Cookie.fromSetCookieValue (dart:_http:975:16)
```
