### ISSUE TITLE
[vm/ffi] Windows --use-slow-path corrupts argument

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#37175]
One of the tests returned a different value on the CL which forces Dart FFI to be entering and exiting safe points through slow paths.

The root cause seems to be that one of the arguments got corrupted.
```dart
SumSmallNumbers(0, 0, -2147483648, 0, 0, 225750201)
```

Should have been:
```dart
SumSmallNumbers(0, 0, -2147483648, 0, 0, 0)
```

Full test result:
```
/=====================================================================\
| ffi/function_test/2 is new and failed (RuntimeError, expected Pass) |
\=====================================================================/

--- Command "vm" (took 01.000838s):
set DART_CONFIGURATION=DebugX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\cache\builder\sdk\out\DebugX64\crashpad_handler.exe & out\DebugX64\dart.exe --no-background-compilation --use-slow-path --ignore-unrecognized-flags --packages=C:\b\s\w\ir\cache\builder\sdk\.packages C:\b\s\w\ir\cache\builder\sdk\tests\ffi\function_test.dart

exit code:
255

stdout:
SumPlus42(3, 4)
returning 49
IntComputation(125, 250, 500, 1000)
returning 625
IntComputation(0, 0, 0, 9223372036854775807)
returning 9223372036854775807
IntComputation(0, 0, 0, -9223372036854775808)
returning -9223372036854775808
UintComputation(0, 0, 0, 9223372036854775807)
returning 9223372036854775807
UintComputation(0, 0, 0, 9223372036854775808)
returning 9223372036854775808
UintComputation(0, 0, 0, 18446744073709551615)
returning 18446744073709551615
SumSmallNumbers(-128, 0, 0, 0, 65512, 38800638)
returning 38866022
SumSmallNumbers(127, 0, 0, 0, 16001, 1073770285)
returning 1073786413
SumSmallNumbers(0, 0, 0, 0, 16001, 1073770285)
returning 1073786286
SumSmallNumbers(0, 0, 0, 255, 62816, 38800638)
returning 38863709
SumSmallNumbers(0, -32768, 0, 0, 62816, 38800638)
returning 38830686
SumSmallNumbers(0, 32767, 0, 0, 62816, 38800638)
returning 38896221
SumSmallNumbers(0, 0, 0, 0, 62816, 38800638)
returning 38863454
SumSmallNumbers(0, 0, 0, 0, 3768, 0)
returning 3768
SumSmallNumbers(0, 0, -2147483648, 0, 0, 225750201)
returning -1921733447

stderr:
Unhandled exception:
Expect.equals(expected: <-2147483648>, actual: <-1921733447>) fails.
#0      Expect._fail (package:expect/expect.dart:655:5)
#1      Expect.equals (package:expect/expect.dart:126:5)
#2      testTruncation (file:///C:/b/s/w/ir/cache/builder/sdk/tests/ffi/function_test.dart:202:10)
#3      main (file:///C:/b/s/w/ir/cache/builder/sdk/tests/ffi/function_test.dart:26:5)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -n dartk-win-debug-x64 ffi/function_test/2
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8911417336176888912/+/steps/test_results/0/logs/unapproved_new_test_failures__logs_/0

**Comment by dcharkes** [comment]
https://github.com/dart-lang/sdk/blob/master/runtime/vm/compiler/backend/il_x64.cc#L960-L966

```c++
  // All arguments to the function call are in the right location here.

  // Update information in the thread object and enter a safepoint.
  __ TransitionGeneratedToNative(target_address, FPREG);

  __ CallCFunction(target_address);

  // Update information in the thread object and leave the safepoint.
  __ TransitionNativeToGenerated();
```

This function might not properly preserve the stack and or registers:

https://github.com/dart-lang/sdk/blob/master/runtime/vm/compiler/assembler/assembler_x64.cc#L168

```c++
void Assembler::TransitionGeneratedToNative(Register destination_address,
                                            Register new_exit_frame) {
  // Save exit frame information to enable stack walking.
  movq(Address(THR, Thread::top_exit_frame_info_offset()), new_exit_frame);

  movq(Assembler::VMTagAddress(), destination_address);
  movq(Address(THR, compiler::target::Thread::execution_state_offset()),
       Immediate(compiler::target::Thread::native_execution_state()));

  // Compare and swap the value at Thread::safepoint_state from unacquired to
  // acquired. If the CAS fails, go to a slow-path stub.
  Label done;
  if (!FLAG_use_slow_path) {
    // Slow path.
  }

  movq(TMP,
       Address(THR, compiler::target::Thread::enter_safepoint_stub_offset()));
  movq(TMP, FieldAddress(TMP, compiler::target::Code::entry_point_offset()));
  CallCFunction(TMP);

  Bind(&done);
}
```

**Comment by dcharkes** [comment]
It looks like the stub itself properly keeps the stack intact.

```c++
void StubCodeCompiler::GenerateEnterSafepointStub(Assembler* assembler) {
  RegisterSet all_registers;
  all_registers.AddAllGeneralRegisters();
  __ PushRegisters(all_registers.cpu_registers(),
                   all_registers.fpu_registers());

  __ EnterFrame(0);
  __ ReserveAlignedFrameSpace(0);
  __ movq(RAX, Address(THR, kEnterSafepointRuntimeEntry.OffsetFromThread()));
  __ CallCFunction(RAX);
  __ LeaveFrame();

  __ PopRegisters(all_registers.cpu_registers(), all_registers.fpu_registers());
  __ ret();
}
```

```
0000000004643C20  sub         rsp,100h  
0000000004643C27  movups      xmmword ptr [rsp],xmm0  
0000000004643C2B  movups      xmmword ptr [rsp+10h],xmm1  
0000000004643C30  movups      xmmword ptr [rsp+20h],xmm2  
0000000004643C35  movups      xmmword ptr [rsp+30h],xmm3  
0000000004643C3A  movups      xmmword ptr [rsp+40h],xmm4  
0000000004643C3F  movups      xmmword ptr [rsp+50h],xmm5  
0000000004643C44  movups      xmmword ptr [rsp+60h],xmm6  
0000000004643C49  movups      xmmword ptr [rsp+70h],xmm7  
0000000004643C4E  movups      xmmword ptr [rsp+80h],xmm8  
0000000004643C57  movups      xmmword ptr [rsp+90h],xmm9  
0000000004643C60  movups      xmmword ptr [rsp+0A0h],xmm10  
0000000004643C69  movups      xmmword ptr [rsp+0B0h],xmm11  
0000000004643C72  movups      xmmword ptr [rsp+0C0h],xmm12  
0000000004643C7B  movups      xmmword ptr [rsp+0D0h],xmm13  
0000000004643C84  movups      xmmword ptr [rsp+0E0h],xmm14  
0000000004643C8D  movups      xmmword ptr [rsp+0F0h],xmm15  
0000000004643C96  push        r15  
0000000004643C98  push        r14  
0000000004643C9A  push        r13  
0000000004643C9C  push        r12  
0000000004643C9E  push        r11  
0000000004643CA0  push        r10  
0000000004643CA2  push        r9  
0000000004643CA4  push        r8  
0000000004643CA6  push        rdi  
0000000004643CA7  push        rsi  
0000000004643CA8  push        rbx  
0000000004643CA9  push        rdx  
0000000004643CAA  push        rcx  
0000000004643CAB  push        rax  
0000000004643CAC  push        rbp  
0000000004643CAD  mov         rbp,rsp  
0000000004643CB0  and         rsp,0FFFFFFFFFFFFFFF0h  
0000000004643CB4  mov         rax,qword ptr [r14+460h]  
0000000004643CBB  sub         rsp,20h  
0000000004643CBF  call        rax  
0000000004643CC1  mov         rsp,rbp  
0000000004643CC4  pop         rbp  
0000000004643CC5  pop         rax  
0000000004643CC6  pop         rcx  
0000000004643CC7  pop         rdx  
0000000004643CC8  pop         rbx  
0000000004643CC9  pop         rsi  
0000000004643CCA  pop         rdi  
0000000004643CCB  pop         r8  
0000000004643CCD  pop         r9  
0000000004643CCF  pop         r10  
0000000004643CD1  pop         r11  
0000000004643CD3  pop         r12  
0000000004643CD5  pop         r13  
0000000004643CD7  pop         r14  
0000000004643CD9  pop         r15  
0000000004643CDB  movups      xmm0,xmmword ptr [rsp]  
0000000004643CDF  movups      xmm1,xmmword ptr [rsp+10h]  
0000000004643CE4  movups      xmm2,xmmword ptr [rsp+20h]  
0000000004643CE9  movups      xmm3,xmmword ptr [rsp+30h]  
0000000004643CEE  movups      xmm4,xmmword ptr [rsp+40h]  
0000000004643CF3  movups      xmm5,xmmword ptr [rsp+50h]  
0000000004643CF8  movups      xmm6,xmmword ptr [rsp+60h]  
0000000004643CFD  movups      xmm7,xmmword ptr [rsp+70h]  
0000000004643D02  movups      xmm8,xmmword ptr [rsp+80h]  
0000000004643D0B  movups      xmm9,xmmword ptr [rsp+90h]  
0000000004643D14  movups      xmm10,xmmword ptr [rsp+0A0h]  
0000000004643D1D  movups      xmm11,xmmword ptr [rsp+0B0h]  
0000000004643D26  movups      xmm12,xmmword ptr [rsp+0C0h]  
0000000004643D2F  movups      xmm13,xmmword ptr [rsp+0D0h]  
0000000004643D38  movups      xmm14,xmmword ptr [rsp+0E0h]  
0000000004643D41  movups      xmm15,xmmword ptr [rsp+0F0h]  
0000000004643D4A  add         rsp,100h  
0000000004643D51  ret 
```

**Comment by dcharkes** [comment]
Stack just before executing the safepoint stub:

```
0x000000000C17F4A8  00 00 00 00 00 00 00 00  ........
0x000000000C17F4B0  00 00 00 00 00 00 00 00  ........
0x000000000C17F4B8  51 3c 48 0b 00 00 00 00  Q<H.....
0x000000000C17F4C0  21 87 ae 0a 00 00 00 00  !.®.....
0x000000000C17F4C8  a0 c5 ed 04 00 00 00 00   Åí.....
0x000000000C17F4D0  03 00 00 00 00 00 00 00  ........
0x000000000C17F4D8  3f 3c 48 0b 00 00 00 00  ?<H.....                         <= RSP in call to SumSmallNumbers
0x000000000C17F4E0  98 f5 17 0c 00 00 00 00  ˜õ...... -> backed up RSP or RBP <= RSP after adding shadow space before call to SumSmallNumbers
0x000000000C17F4E8  40 f5 17 0c 00 00 00 00  @õ...... -> backed up RSP or RBP
0x000000000C17F4F0  02 00 00 00 00 00 00 00  ........
0x000000000C17F4F8  39 3c 48 0b 00 00 00 00  9<H.....                         <= RSP after executing stub
0x000000000C17F500  e8 ff ff ff ff ff ff ff  èÿÿÿÿÿÿÿ // The two values that  <= RSP after returning from stub
0x000000000C17F508  fe 0c 68 04 00 00 00 00  þ.h..... // do get passed instead.
0x000000000C17F510  06 22 01 40 01 00 00 00  .".@....
0x000000000C17F518  68 f5 17 0c 00 00 00 00  hõ...... -> backed up RSP or RBP
0x000000000C17F520  05 00 00 00 00 00 00 00  ........ // The two arguments    <= RSP before calling stub
0x000000000C17F528  06 00 00 00 00 00 00 00  ........ // passed by stack that don't get passed properly.
0x000000000C17F530  21 87 ae 0a 00 00 00 00  !.®.....
0x000000000C17F538  41 00 9c 02 00 00 00 00  A.œ.....
0x000000000C17F540  98 f5 17 0c 00 00 00 00  ˜õ...... -> backed up RSP or RBP
0x000000000C17F548  0a 3c 48 0b 00 00 00 00  .<H.....
0x000000000C17F550  01 00 00 00 00 00 00 00  ........ // unboxed arguments
0x000000000C17F558  02 00 00 00 00 00 00 00  ........ //
0x000000000C17F560  03 00 00 00 00 00 00 00  ........ //
0x000000000C17F568  04 00 00 00 00 00 00 00  ........ //
0x000000000C17F570  05 00 00 00 00 00 00 00  ........ //
0x000000000C17F578  06 00 00 00 00 00 00 00  ........ //
0x000000000C17F580  2e 3c 00 80 01 00 00 00  .<.€....
0x000000000C17F588  e1 1d af 0a 00 00 00 00  á.¯.....
0x000000000C17F590  c1 54 ad 0a 00 00 00 00  ÁT......
0x000000000C17F598  00 f6 17 0c 00 00 00 00  .ö......
0x000000000C17F5A0  30 0e 48 0b 00 00 00 00  0.H.....
0x000000000C17F5A8  0c 00 00 00 00 00 00 00  ........ // boxed arguments
0x000000000C17F5B0  0a 00 00 00 00 00 00 00  ........ //
0x000000000C17F5B8  08 00 00 00 00 00 00 00  ........ //
0x000000000C17F5C0  06 00 00 00 00 00 00 00  ........ //
0x000000000C17F5C8  04 00 00 00 00 00 00 00  ........ //
0x000000000C17F5D0  02 00 00 00 00 00 00 00  ........ //
```

Looks like it enters a frame but does not exit?

**Comment by dcharkes** [comment]
```
000000000B483C2E  mov         r11,qword ptr [r11+7]       RSP = 000000000C17F520
000000000B483C32  sub         rsp,20h  // shadow space    RSP = 000000000C17F500
000000000B483C36  call        r11      // call to stub    RSP = 000000000C17F500 <- shadow space not removed
000000000B483C39  sub         rsp,20h  // shadow space    RSP = 000000000C17F520
000000000B483C3D  call        rax      // call through FFI  which uses wrong values
```

**Comment by sjindel-google** [comment]
Is this related to https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-win-release-x64/5895?

**Comment by dcharkes** [comment]
> Is this related to https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-win-release-x64/5895?

Yes, I approved that failure right?

**Comment by sjindel-google** [comment]
I didn't know you approved it -- I thought it was a flaky crash.

**Comment by dcharkes** [comment]
This was a build before the fix landed.

**Comment by sjindel-google** [comment]
Still waiting on the regression test: https://dart-review.googlesource.com/c/sdk/+/105301
