### ISSUE TITLE
VSCode crash

### ISSUE THREAD

**Issue by duzenko** [dart-lang/sdk#37209]
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Opened the flutter plugins repo in VS code

### Request

While responding to request: `analysis.setAnalysisRoots`

### Versions

- Flutter SDK 1.5.4-hotfix.2
- Visual Studio Code 1.33.1
- Dart Code 3.1.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Applications/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.1.0
```

### Exception

FileSystemException(path=/Users/a/Documents/flutterplugins/packages/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/Resources/GoogleMaps.bundle/bubble_right@3x.p; message=Directory listing failed)

```text
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:334:7)
#1      _OverlayFolder.getChildren (package:analyzer/file_system/overlay_file_system.dart:334:10)
#2      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1144:32)
#3      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#4      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#5      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#6      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#7      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#8      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#9      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#10     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#11     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#12     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#13     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#14     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#15     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#16     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#17     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#18     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#19     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#20     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#21     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#22     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#23     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#24     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#25     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#26     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#27     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#28     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#29     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#30     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#31     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#32     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#33     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#34     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#35     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#36     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#37     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#38     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#39     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#40     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#41     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#42     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#43     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#44     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#45     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#46     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#47     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#48     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#49     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#50     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#51     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#52     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#53     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#54     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#55     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#56     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#57     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#58     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#59     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#60     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#61     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#62     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#63     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#64     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#65     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#66     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#67     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#68     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#69     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#70     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#71     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#72     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#73     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#74     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#75     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#76     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#77     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#78     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#79     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#80     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#81     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#82     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#83     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#84     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#85     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#86     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#87     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#88     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#89     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#90     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#91     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#92     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#93     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#94     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#95     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#96     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#97     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#98     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#99     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1158:25)
#100    ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1191:16)
#101    ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:736:9)
#102    AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:521:22)
#103    AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:390:14)
#104    AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:324:16)
#105    AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:337:45)
#106    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#107    AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:50)
#108    _rootRun (dart:async/zone.dart:1124:13)
#109    _CustomZone.run (dart:async/zone.dart:1021:19)
#110    _runZoned (dart:async/zone.dart:1516:10)
#111    runZoned (dart:async/zone.dart:1500:12)
#112    AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:332:5)
#113    ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#114    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#115    ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#116    ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#117    _rootRunUnary (dart:async/zone.dart:1132:38)
#118    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#119    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#120    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#121    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#122    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#123    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#124    _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#125    _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#126    _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#127    StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#128    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#129    _rootRunUnary (dart:async/zone.dart:1132:38)
#130    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#131    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#132    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#133    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#134    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#135    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#136    _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#137    _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#138    _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#139    _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#140    _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#141    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#142    _rootRunUnary (dart:async/zone.dart:1132:38)
#143    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#144    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#145    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#146    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#147    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#148    _StreamController._add (dart:async/stream_controller.dart:640:7)
#149    _StreamController.add (dart:async/stream_controller.dart:586:5)
#150    _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#151    _rootRunUnary (dart:async/zone.dart:1136:13)
#152    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#153    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#154    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#155    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#156    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#157    _StreamController._add (dart:async/stream_controller.dart:640:7)
#158    _StreamController.add (dart:async/stream_controller.dart:586:5)
#159    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#160    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#161    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#162    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#163    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#164    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by devoncarew** [comment]
Thanks for the report! This issue has been addressed in the flutter master channel, and will make it's way through to the next stable release.

@aadilmaan @kf6gpe - we're seeing several reports of this issue - fixed a month ago or more on dart-lang/sdk master. This would be a good candidate for a cherry-pick into flutter stable. I'm not sure of the maturity of that process - if cherry-picking is really possible at this point.
