### ISSUE TITLE
analysis server crash - SDK 1.20

### ISSUE THREAD

**Issue by vikas-volansys** [dart-lang/sdk#37248]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.7479.19`
- `1.20.1`
- `IC-191.7479.19, JRE 1.8.0_202-release-1483-b58x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-50-generic, screens 1600x900`

## Exception
```
Dart analysis server, SDK version 1.20.1, server version 1.17.0, error: Task failed: ResolveDirectiveElementsTask for source /home/vikas/Rheemconnect/econet/econet_gateway/lib/econet_gateway.dart
Unexpected exception while performing ResolveDirectiveElementsTask for source /home/vikas/Rheemconnect/econet/econet_gateway/lib/econet_gateway.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:351)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1184)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1182)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:894)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'imports'.

NoSuchMethodError: method not found: 'imports'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      DirectiveResolver.visitImportDirective (package:analyzer/src/generated/resolver.dart:2955)
#3      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:5877)
#4      DirectiveResolver.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:2935)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2445)
#6      ResolveDirectiveElementsTask.internalPerform (package:analyzer/src/task/dart.dart:4985)
#7      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#8      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#9      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#10     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#11     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1184)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#13     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1182)
#14     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)
#15     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:894)
#16     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#17     _rootRun (dart:async/zone.dart:1146)
#18     _CustomZone.run (dart:async/zone.dart:1026)
#19     _CustomZone.runGuarded (dart:async/zone.dart:924)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#21     _rootRun (dart:async/zone.dart:1150)
#22     _CustomZone.run (dart:async/zone.dart:1026)
#23     _CustomZone.runGuarded (dart:async/zone.dart:924)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#25     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by kevmoo** [comment]
We don't support this SDK. Please upgrade to Dart 2.3+
