### ISSUE TITLE
VS Code Analysis Service failed 

### ISSUE THREAD

**Issue by taojigu** [dart-lang/sdk#37249]
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

No special operation , it just happen when I am working. 

### Request

While responding to request: `analysis.setAnalysisRoots`

### Versions

- Flutter SDK 1.5.4-hotfix.2
- Visual Studio Code 1.35.1
- Dart Code 3.1.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/lianjia/Documents/software/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.1.0
```

### Exception

FileSystemException(path=/Users/lianjia/Documents/gerrit/ljplugin/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/.symlinks/plugins/flutter_custom_report/example/ios/Pods/LJBaseCrashReporter/LJBaseCrashReporter/Framework/Sources/Release/LJBaseCrashReporterSources.framework/Versions/Current/Headers/LJBaseCrashReporterWeakObjectWrappe; message=Directory listing failed)

```text
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:334:7)
#1      _OverlayFolder.getChildren (package:analyzer/file_system/overlay_file_system.dart:334:10)
#2      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1144:32)
#3      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#4      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#5      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#6      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#7      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#8      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#9      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#10     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#11     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#12     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#13     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#14     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#15     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#16     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#17     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#18     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#19     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#20     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#21     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#22     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#23     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#24     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#25     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#26     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#27     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#28     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#29     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#30     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#31     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#32     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#33     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#34     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#35     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#36     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#37     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#38     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#39     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#40     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#41     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#42     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#43     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#44     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#45     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#46     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#47     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#48     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#49     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#50     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#51     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#52     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#53     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#54     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#55     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#56     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#57     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#58     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#59     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#60     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#61     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#62     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#63     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#64     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#65     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#66     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#67     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#68     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#69     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#70     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#71     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#72     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#73     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#74     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#75     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#76     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#77     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#78     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#79     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#80     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#81     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#82     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#83     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#84     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#85     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#86     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#87     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#88     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#89     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#90     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1158:25)
#91     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1191:16)
#92     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:736:9)
#93     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:521:22)
#94     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:390:14)
#95     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:324:16)
#96     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:337:45)
#97     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#98     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:50)
#99     _rootRun (dart:async/zone.dart:1124:13)
#100    _CustomZone.run (dart:async/zone.dart:1021:19)
#101    _runZoned (dart:async/zone.dart:1516:10)
#102    runZoned (dart:async/zone.dart:1500:12)
#103    AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:332:5)
#104    ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#105    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#106    ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#107    ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#108    _rootRunUnary (dart:async/zone.dart:1132:38)
#109    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#110    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#111    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#112    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#113    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#114    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#115    _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#116    _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#117    _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#118    StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#119    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#120    _rootRunUnary (dart:async/zone.dart:1132:38)
#121    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#122    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#123    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#124    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#125    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#126    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#127    _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#128    _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#129    _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#130    _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#131    _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#132    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#133    _rootRunUnary (dart:async/zone.dart:1132:38)
#134    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#135    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#136    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#137    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#138    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#139    _StreamController._add (dart:async/stream_controller.dart:640:7)
#140    _StreamController.add (dart:async/stream_controller.dart:586:5)
#141    _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#142    _rootRunUnary (dart:async/zone.dart:1136:13)
#143    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#144    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#145    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#146    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#147    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#148    _StreamController._add (dart:async/stream_controller.dart:640:7)
#149    _StreamController.add (dart:async/stream_controller.dart:586:5)
#150    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#151    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#152    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#153    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#154    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#155    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/lianjia/Documents/gerrit/ljplugin/flutter_custom_report",
        "explicitFileCount": 1,
        "implicitFileCount": -1,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment]
This is the same as #36919 and the fix should be in the latest stable version of Flutter.
