### ISSUE TITLE
Flaky crashes with exit code -8

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#37257]
These flaky crashes appear on different tests after 1e24fe7d699a1c36be142afa21859c6a9c82d035.
They can be reproduced at 1e24fe7d699a1c36be142afa21859c6a9c82d035, but no crashes at the previous f005bd5a3eded7dffe90e6fb2e7ea12db631fe21.

Repro:

```
tools/build.py -a x64 -m product runtime
tools/test.py --repeat 1000 -n dartk-linux-product-x64 lib_2/mirrors/library_declarations_test/none
```

```
[00:01 |   0% | +    9 | -    0]
FAILED: dartk-vm product_x64 lib_2/mirrors/library_declarations_test/none
Expected: RuntimeError
Actual: Crash

--- Command "vm" (took 228ms):
DART_CONFIGURATION=ProductX64 out/ProductX64/dart --ignore-unrecognized-flags --packages=/usr/local/google/home/alexmarkov/work/dart/sdk/.packages /usr/local/google/home/alexmarkov/work/dart/sdk/out/ProductX64/generated_tests/lib_2/mirrors/library_declarations_test_none.dart

exit code:
-8

--- Re-run this test:
python tools/test.py -n dartk-linux-product-x64 lib_2/mirrors/library_declarations_test/none
```

From debugger:
```
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x000055abcfcc82d3 in dart::Cids::CreateHelper (this=0x55abd265c078, zone=<optimized out>, ic_data=..., argument_number=<optimized out>, include_targets=true)
    at ../../runtime/vm/compiler/backend/il.cc:791
791	../../runtime/vm/compiler/backend/il.cc: No such file or directory.
[Current thread is 1 (Thread 0x7fa6179be700 (LWP 66735))]
(gdb) bt
#0  0x000055abcfcc82d3 in dart::Cids::CreateHelper (this=0x55abd265c078, zone=<optimized out>, ic_data=..., argument_number=<optimized out>, include_targets=true)
    at ../../runtime/vm/compiler/backend/il.cc:791
#1  0x000055abcfcd1956 in dart::CallTargets::CreateAndExpand (zone=0x55abd1e04400, ic_data=...) at ../../runtime/vm/compiler/backend/il.cc:3758
#2  0x000055abcfd9dcbf in dart::JitCallSpecializer::VisitInstanceCall (this=0x7fa6179bd780, instr=0x55abd2650d10)
    at ../../runtime/vm/compiler/jit/jit_call_specializer.cc:125
#3  0x000055abcfcca6c9 in dart::FlowGraphVisitor::VisitBlocks (this=0x7fa6179bd780) at ../../runtime/vm/compiler/backend/il.cc:1253
#4  0x000055abcfd3642d in dart::CompilerPass_ApplyICData::DoBody (this=<optimized out>, state=0x55abd1e04400) at ../../runtime/vm/compiler/compiler_pass.cc:307
#5  0x000055abcfd35f77 in dart::CompilerPass::Run (this=0x55abd00c0bd8 <dart::compiler_pass_ApplyICData>, state=0x7fa6179bd508)
    at ../../runtime/vm/compiler/compiler_pass.cc:178
#6  0x000055abcfd3617f in dart::CompilerPass::RunPipeline (mode=<optimized out>, pass_state=0x7fa6179bd508) at ../../runtime/vm/compiler/compiler_pass.cc:237
#7  0x000055abcfd9b45e in dart::CompileParsedFunctionHelper::Compile (this=0x7fa6179bdae8, pipeline=0x55abd1dcb600) at ../../runtime/vm/compiler/jit/compiler.cc:679
#8  0x000055abcfd9c1c2 in dart::CompileFunctionHelper (pipeline=<optimized out>, function=..., optimized=true, osr_id=<optimized out>)
    at ../../runtime/vm/compiler/jit/compiler.cc:827
#9  0x000055abcfd9d12b in dart::Compiler::CompileOptimizedFunction (thread=<optimized out>, function=..., osr_id=-1) at ../../runtime/vm/compiler/jit/compiler.cc:1023
#10 dart::BackgroundCompiler::Run (this=<optimized out>) at ../../runtime/vm/compiler/jit/compiler.cc:1294
#11 0x000055abcfc82f4a in dart::ThreadPool::Worker::Loop (this=0x55abd1da6120) at ../../runtime/vm/thread_pool.cc:381
#12 0x000055abcfc82e0d in dart::ThreadPool::Worker::Main (args=94196448518432) at ../../runtime/vm/thread_pool.cc:436
#13 0x000055abcfc1d393 in dart::ThreadStart (data_ptr=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:134
#14 0x00007fa6184a1c73 in start_thread (arg=<optimized out>) at pthread_create.c:486
#15 0x00007fa617c4bdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

/cc @rmacnak-google @mkustermann

**Comment by mkustermann** [comment]
Guess the underlying issue has been fixed and we can close this issue?
