### ISSUE TITLE
HttpClient refuses to download content when sent without headers

### ISSUE THREAD

**Issue by SoptikHa2** [dart-lang/sdk#37309]
Dart 2.3.1
Linux

I'm trying to make an wrapper for a website. Whether I use `http` library or dart `HttpClient`, I'm unable to get this url: `https://www.strava.cz/foxisapi/foxisapi.dll/istravne.istravne.process?xmljidelnickyA&zarizeni=0158`.

Firefox and curl both get it without problems. I believe the problem might be that the website does not send any headers.

Exception:

```
HttpException: Invalid request method, uri = https://www.strava.cz/foxisapi/foxisapi.dll/istravne.istravne.process?xmljidelnickyA&zarizeni=0158
#0      _HttpParser._doParse (dart:_http/http_parser.dart:428:15)
#1      _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#2      _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#6      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#7      _StreamController._add (dart:async/stream_controller.dart:640:7)
#8      _StreamController.add (dart:async/stream_controller.dart:586:5)
#9      _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#13     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#14     _StreamController._add (dart:async/stream_controller.dart:640:7)
#15     _StreamController.add (dart:async/stream_controller.dart:586:5)
#16     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

```dart
HttpClient client = new HttpClient();
    client.getUrl(Uri.parse(url)).then((HttpClientRequest request) {
      return request.close();
    }).then((HttpClientResponse response) {
      print(response.toString());
    });
```

**Comment by srawlins** [comment]
I tried the above URL and see the HttpException. When the exception is thrown, the `_buffer` contains char codes that map to this string:

```none
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
  <META HTTP-EQUIV="content-type" CONTENT="text/html; charset=windows-1250">
  <TITLE>iPROVIS</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<BASEFONT FACE="Arial CE,Helvetica CE,Arial,Helvetica,sans-serif">

<TABLE>
  <TR>
    <TD>Dolo k chybì aplikace.</TD>
  </TR>
</TABLE>

</BODY>
</HTML>
```

It chokes reading character 60, which is the `"` in `Transitional//EN">`.

**Comment by mraleph** [comment]
The server is responding with `HTTP/0.9` which `HttpClient` does not understand. The response does not start with `HTTP/1.1` status line.
