### ISSUE TITLE
CFE crash on new dart2js code using UI-as-code

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#37302]
This code seems to run fine without creating a dill file.

Patch https://dart-review.googlesource.com/c/sdk/+/106428 (patchset 2) and run:
```
tools/test.py -n unittest-asserts-release-linux pkg/front_end/test/incremental_dart2js_load_from_dill_test
```

The error location is the identifer __asCheck__ in the getter declaration:
```
  BackendImpact _asCheck;

  BackendImpact get asCheck {
    return _asCheck ??= new BackendImpact(staticUses: [
      _commonElements.throwRuntimeError,
    ], otherImpacts: [
      if (_newRti) usesNewRti
    ]);
  }
```

```
Unhandled exception:
Crash when compiling file:///usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/js_backend/backend_impact.dart,
at character offset 6328:
NoSuchMethodError: The getter 'typeSchemaEnvironment' was called on null.
Receiver: null
Tried calling: typeSchemaEnvironment
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      new CollectionTransformer (package:front_end/src/fasta/kernel/transform_collections.dart:93:54)
#2      SourceLoader.transformPostInference (package:front_end/src/fasta/source/source_loader.dart:1051:49)
#3      BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:770:22)
#4      DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:772:14)
#5      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:805:7)
#6      DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:590:5)
#7      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3267:14)
#8      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3126:15)
#9      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2902:15)
#10     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1793:13)
#11     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1753:14)
#12     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#13     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#14     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
```

I was able to work around the issue by avoiding the UI-as-code expression (patchset 3).

**Comment by mraleph** [comment]
The test itself seems broken - it runs compiler in "legacyMode" (which is defined as `legacyMode: !strong` - which has not been true ever since legacyMode got repurposed to mean something completely different). 

@jensjoha you seems to be the last one who changed this test. Could you clean it up and remove non-strong code paths?

**Comment by rakudrama** [comment]
The crash at that location in the FE still exists

The try job for https://dart-review.googlesource.com/c/sdk/+/106941/3 fails:
https://ci.chromium.org/p/dart/builders/try/front-end-linux-release-x64-try/19650
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8910006462587146096/+/steps/unit_tests/0/stdout
```
FAILED: dartk-vm release_x64 pkg/front_end/tool/incremental_perf_test
Expected: Slow Pass
Actual: RuntimeError

--- Command "vm" (took 42.000101s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart --enable_asserts --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/incremental_perf_test.dart

exit code:
255

stdout:
Initial compilation took: 1341.603ms
Change 'mainlib' - Incremental compilation took: 9.914ms
Initial compilation took: 582.0ms
Change 'mainlib' - Incremental compilation took: 5.546ms
Initial compilation took: 270.235ms
Change 'mainlib' - Incremental compilation took: 18.724ms
Initial compilation took: 22553.93ms
Change 'mainlib' - Incremental compilation took: 60.3ms
Change 'optionslib' - Incremental compilation took: 6081.809ms

stderr:
Unhandled exception:
Crash when compiling org-dartlang-overlay:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/namer_names.dart,
at character offset 3726:
NoSuchMethodError: The getter 'typeSchemaEnvironment' was called on null.
Receiver: null
Tried calling: typeSchemaEnvironment
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      new CollectionTransformer (package:front_end/src/fasta/kernel/transform_collections.dart:93:54)
#2      SourceLoader.transformListPostInference (package:front_end/src/fasta/source/source_loader.dart:1062:41)
#3      BodyBuilder.finishConstructor (package:front_end/src/fasta/kernel/body_builder.dart:1192:20)
#4      BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:893:7)
#5      DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:778:14)
#6      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:811:7)
#7      DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:596:5)
#8      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3267:14)
#9      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3126:15)
#10     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2902:15)
#11     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1793:13)
#12     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1753:14)
#13     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#14     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#15     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#16     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:292:18)
```

**Comment by rakudrama** [comment]
Use this patch instead. I'm not going to add patchsets and eventually commit it:
https://dart-review.googlesource.com/c/sdk/+/107061

**Comment by mraleph** [comment]
I would guess that it is still a problem with a test - it probably creates a legacyMode Kernel target. 

We should maybe just kill this (e.g. remove legacyMode from the target).
