### ISSUE TITLE
Unsupported operation: unsupported initializer: IndexExpressionImpl 

### ISSUE THREAD

**Issue by thanhhuan1990** [dart-lang/sdk#37330]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5522156`
- `2.4.0`
- `AI-183.6156.11.34.5522156, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1440x900, 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
Unsupported operation: unsupported initializer: IndexExpressionImpl :: super()[requests]
#0      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:1333:9)
#1      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2578:14)
#2      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2515:14)
#3      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3241:13)
#4      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3122:15)
#5      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2898:15)
#6      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1783:13)
#7      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1743:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#11     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#12     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#13     _File._parse (package:analyzer/src/services/available_declarations.dart:1656:23)
#14     _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#15     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:601:14)
#16     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:514:18)
#17     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#23     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#29     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#30     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#31     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#32     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#33     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#41     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#42     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#43     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#44     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#45     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/69/r_nh2ysj7sj71dnl2ybgbq1r0000gn/T/report.txt.

**Comment by danrubel** [comment]
Fixed in https://github.com/dart-lang/sdk/issues/37285.
