### ISSUE TITLE
Encountered a Dart Analysis Server error

### ISSUE THREAD

**Issue by Kay-coding** [dart-lang/sdk#37341]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5522156`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-183.6156.11.34.5522156, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 2560x1440  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: Analysis failed: /Volumes/TDEx/wkl/wkl/wkl/follow_app/lib/src/page/ploy_selection_page.dart context: exception_20190624_174149_730
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      ErrorVerifier._checkMixinInference (package:analyzer/src/generated/error_verifier.dart:5711:36)
#2      ErrorVerifier._checkClassInheritance (package:analyzer/src/generated/error_verifier.dart:1448:7)
#3      ErrorVerifier.visitClassDeclaration (package:analyzer/src/generated/error_verifier.dart:505:9)
#4      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1560:49)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7550:20)
#6      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2168:21)
#7      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:723:10)
#8      ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:549:11)
#9      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2147:49)
#10     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:385:10)
#11     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:146:9)
#12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#13     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:145:13)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#15     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:144:34)
#16     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:14)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:43)
#19     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1450:63)
#20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#21     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1427:20)
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1247:33)
<asynchronous suspension>
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2160:24)
<asynchronous suspension>
#24     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2090:5)
#25     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#26     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#27     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#28     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#34     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#35     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#36     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#37     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#38     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/sh/654frsgx7rj8vqh7y4myd7xm0000gn/T/report2.txt.

**Comment by MichaelRFairhurst** [comment]
Our fuzzer just caught this, giving us a repro: #38278 

We also now know that this is fixed by summary2 and can close this once that has fully landed.

**Comment by srawlins** [comment]
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).
