### ISSUE TITLE
Flaky infra failures during "find tests that began failing" / "find unapproved passing tests" steps

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#37352]
From time to time our bots fail with infra (purple) failure

```
Infra Failure
recipe infra failure: Uncaught Exception: OSError(22, 'Invalid argument')
```

Step execution details:
```
/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart tools/bots/compare_results.dart --flakiness-data /b/s/w/ir/tmp/t/tmpzXsTI0 --human --verbose /b/s/w/ir/cache/builder/sdk/LATEST/results.json /b/s/w/ir/tmp/t/tmpsmdQ7v /b/s/w/ir/cache/builder/sdk/LATEST/approved_results.json --logs /b/s/w/ir/tmp/t/tmpaNJIkK --logs-only --changed --failing
in dir /b/s/w/ir/cache/builder/sdk
full environment:
  ANALYZER_STATE_LOCATION_OVERRIDE: /b/s/w/ir/k/recipe_cleanup/analysis-cache
  Apple_PubSub_Socket_Render: /private/tmp/com.apple.launchd.BDy6yxGgrK/Render
  BOTO_CONFIG: /b/s/w/ir/tmp/gsutil-task/.boto
  BUILDBUCKET_EXPERIMENTAL: FALSE
  CIPD_CACHE_DIR: /b/s/cipd_cache/cache
  CIPD_PROTOCOL: v2
  DEVSHELL_CLIENT_PORT: 59468
  DOCKER_CONFIG: /b/s/w/ir/tmp/docker-cfg-task
  DOCKER_TMPDIR: /b/s/w/ir/tmp/docker-tmp-task
  GIT_CONFIG_NOSYSTEM: 1
  GIT_TERMINAL_PROMPT: 0
  HOME: /Users/chrome-bot
  INFRA_GIT_WRAPPER_HOME: /b/s/w/ir/tmp/git-home-task
  LOGDOG_COORDINATOR_HOST: logs.chromium.org
  LOGDOG_STREAM_PREFIX: buildbucket/cr-buildbucket.appspot.com/8909738097010534176
  LOGDOG_STREAM_PROJECT: dart
  LOGDOG_STREAM_SERVER_PATH: unix:/b/s/w/ir/tmp/ld.sock
  LOGNAME: chrome-bot
  LUCI_CONTEXT: /b/s/w/ir/tmp/luci_context.740694097
  MAC_CHROMIUM_TMPDIR: /b/s/w/ir/tmp/t
  NO_GCE_CHECK: False
  PATH: /b/s/w/ir/cipd_bin_packages:/b/s/w/ir/cipd_bin_packages/bin:/b/s/cipd_cache/bin:/opt/local/bin:/opt/local/sbin:/usr/local/sbin:/usr/local/git/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  PWD: /b/s/w/ir/k
  PYTHONIOENCODING: UTF-8
  PYTHONUNBUFFERED: 1
  SHELL: /bin/bash
  SHLVL: 1
  SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.uckososCXs/Listeners
  SWARMING_BOT_ID: vm19-m9
  SWARMING_HEADLESS: 1
  SWARMING_SERVER: https://chromium-swarm.appspot.com
  SWARMING_TASK_ID: 45a4069301f5e911
  TEMP: /b/s/w/ir/tmp/t
  TEMPDIR: /b/s/w/ir/tmp/t
  TMP: /b/s/w/ir/tmp/t
  TMPDIR: /b/s/w/ir/tmp/t
  USER: chrome-bot
  VERSIONER_PYTHON_PREFER_32_BIT: no
  VERSIONER_PYTHON_VERSION: 2.7
  VPYTHON_VIRTUALENV_ROOT: /b/s/w/ir/cache/vpython
  XPC_FLAGS: 0x0
  XPC_SERVICE_NAME: 0
  _: /b/s/w/ir/cipd_bin_packages/vpython
  __CF_USER_TEXT_ENCODING: 0x1F4:0x0:0x0

Step had exception.
```

RECIPE CRASH:
```
The recipe has crashed at point 'Uncaught exception'!

Traceback (most recent call last):
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/engine.py", line 450, in run_steps
    raw_result = recipe_obj.run_steps(api, engine)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/recipe_deps.py", line 706, in run_steps
    properties_def, api=api)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 89, in invoke_with_properties
    arg_names, **additional_args)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 52, in _invoke_with_properties
    return callable_obj(*props, **additional_args)
  File "/b/s/w/ir/kitchen-checkout/build/scripts/slave/recipes/dart/neo.py", line 79, in RunSteps
    _run_steps_impl(api)
  File "/b/s/w/ir/kitchen-checkout/build/scripts/slave/recipes/dart/neo.py", line 123, in _run_steps_impl
    api.dart.test(test_data=TEST_MATRIX)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 615, in _inner
    ret = func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/build/scripts/slave/recipe_modules/dart/api.py", line 643, in test
    self._run_steps(config, isolate_hashes, builder, global_config)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 608, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/build/scripts/slave/recipe_modules/dart/api.py", line 770, in _run_steps
    self._process_test_results(test_steps, global_config)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 608, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/build/scripts/slave/recipe_modules/dart/api.py", line 849, in _process_test_results
    self._present_results(logs_str, results_str, flaky_json_str)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 608, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/build/scripts/slave/recipe_modules/dart/api.py", line 525, in _present_results
    stdout=self.m.raw_io.output_text(add_output_log=True)).stdout
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 649, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_modules/step/api.py", line 353, in __call__
    step_test_data=step_test_data,
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 235, in run_step
    return self._engine.run_step(step)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/engine.py", line 685, in _run_step
    step_data.name_tokens, debug_log, rendered_step)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/step_runner/subproc.py", line 176, in run
    **extra_kwargs)
  File "/b/s/w/ir/cache/vpython/0be37a/lib/python2.7/site-packages/gevent/subprocess.py", line 658, in __init__
    reraise(*exc_info)
  File "/b/s/w/ir/cache/vpython/0be37a/lib/python2.7/site-packages/gevent/subprocess.py", line 627, in __init__
    restore_signals, start_new_session)
  File "/b/s/w/ir/cache/vpython/0be37a/lib/python2.7/site-packages/gevent/subprocess.py", line 1488, in _execute_child
    data = errpipe_read.read()
  File "/b/s/w/ir/cache/vpython/0be37a/lib/python2.7/site-packages/gevent/_fileobjectposix.py", line 136, in readall
    data = self.__read(DEFAULT_BUFFER_SIZE)
  File "/b/s/w/ir/cache/vpython/0be37a/lib/python2.7/site-packages/gevent/_fileobjectposix.py", line 127, in __read
    return _read(self._fileno, n)
OSError: [Errno 22] Invalid argument
```

[failure 1](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-mac-release-simdbc64/3226)
[failure 2](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-mac-debug-x64/2333)
[failure 3](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-mac-product-x64/3437)
[failure 4](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-mac-debug-x64/2173)

/cc @whesse @athomas

**Comment by athomas** [comment]
This is a flake in the underlying infrastructure. I've reported https://crbug.com/980535 to track this.

**Comment by athomas** [comment]
There is a fix in place in the recipe engine now.
