### ISSUE TITLE
Analyzer assist_internal.dart: NoSuchMethodError: The getter 'name' was called on null

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#37356]
When double-clicking the word "ProcessResult" here, VS Code sent a request for code actions, and this crash happened.

![Screenshot 2019-06-25 at 7 50 07 am](https://user-images.githubusercontent.com/1078012/60075811-0cbc7080-971e-11e9-825e-f6967ea52e46.png)

```
[Error - 7:47:23 AM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 7:47:23 AM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AssistProcessor._addProposal_convertMapFromIterableToForLiteral (package:analysis_server/src/services/correction/assist_internal.dart:974:17)
<asynchronous suspension>
#2      AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:155:13)
<asynchronous suspension>
#3      CodeActionHandler._getAssistActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:142:39)
<asynchronous suspension>
#4      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:167:7)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#6      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:154:70)
#7      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:64:18)
#8      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:217:12)
#9      CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:61:26)
#10     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:217:12)
#11     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:60:26)
#12     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:217:12)
#13     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:57:17)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#24     _MessageHandler&Object&Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#25     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#31     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#32     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by DanTup** [comment]
Oops, I already opened this at #37159.
