### ISSUE TITLE
Error compiling dartdevc

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#37367]
Trying to run `webdev serve` when developing Dart Devtools.

Error:
dartdevc -k arguments: --dart-sdk-summary=/Users/kenzieschmoll/homebrew/Cellar/dart/2.5.0-dev.0.0/libexec/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/devtools/src/timeline/cpu_profiler_view.ddc.js --source-map --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/devtools/src/trees.ddc.dill=packages/devtools/src/trees --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/stream_transform/src/aggregate_sample.ddc.dill=packages/stream_transform/src/aggregate_sample --summary=packages/vm_service_lib/vm_service_lib.ddc.dill=packages/vm_service_lib/vm_service_lib --summary=packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols --summary=packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols --summary=packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data --summary=packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules --summary=packages/intl/intl.ddc.dill=packages/intl/intl --summary=packages/devtools/src/utils.ddc.dill=packages/devtools/src/utils --summary=packages/devtools/src/vm_service_wrapper.ddc.dill=packages/devtools/src/vm_service_wrapper --summary=packages/devtools/src/ui/analytics_constants.ddc.dill=packages/devtools/src/ui/analytics_constants --summary=packages/devtools/src/ui/fake_flutter/collections.ddc.dill=packages/devtools/src/ui/fake_flutter/collections --summary=packages/devtools/src/ui/fake_flutter/dart_ui/dart_ui.ddc.dill=packages/devtools/src/ui/fake_flutter/dart_ui/dart_ui --summary=packages/devtools/src/ui/fake_flutter/fake_flutter.ddc.dill=packages/devtools/src/ui/fake_flutter/fake_flutter --summary=packages/devtools/src/ui/flutter_html_shim.ddc.dill=packages/devtools/src/ui/flutter_html_shim --summary=packages/devtools/src/ui/theme.ddc.dill=packages/devtools/src/ui/theme --summary=packages/devtools/src/ui/icons.ddc.dill=packages/devtools/src/ui/icons --summary=packages/devtools/src/service_extensions.ddc.dill=packages/devtools/src/service_extensions --summary=packages/devtools/src/service_registrations.ddc.dill=packages/devtools/src/service_registrations --summary=packages/devtools/src/core/message_bus.ddc.dill=packages/devtools/src/core/message_bus --summary=packages/pedantic/pedantic.ddc.dill=packages/pedantic/pedantic --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=packages/path/path.ddc.dill=packages/path/path --summary=packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=packages/source_span/source_span.ddc.dill=packages/source_span/source_span --summary=packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --summary=packages/http/src/base_client.ddc.dill=packages/http/src/base_client --summary=packages/http/http.ddc.dill=packages/http/http --summary=packages/devtools/src/inspector/flutter_widget.ddc.dill=packages/devtools/src/inspector/flutter_widget --summary=packages/devtools/src/connected_app.ddc.dill=packages/devtools/src/connected_app --summary=packages/devtools/src/timeline/cpu_profile_model.ddc.dill=packages/devtools/src/timeline/cpu_profile_model --summary=packages/devtools/src/ui/elements.ddc.dill=packages/devtools/src/ui/elements --packages=file:///var/folders/47/2t86yx_91cg501qq6zk1qngh00fv4z/T/kernel_builder_vbK8uV/.packages --module-name=packages/devtools/src/timeline/cpu_profiler_view --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:devtools/src/timeline/cpu_profiler_view.dart
    dart --version: 2.5.0-dev.0.0 (Thu Jun 20 22:29:29 2019 +0200) on "macos_x64"

Bad state: Could not find module name for library "#lib3" from component "null".
#0      ProgramCompiler.libraryToModule (package:dev_compiler/src/kernel/compiler.dart:362:7)
#1      _ProgramCompiler&Object&SharedCompiler.emitImportsAndExtensionSymbols (package:dev_compiler/src/compiler/shared_compiler.dart:440:27)
#2      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:308:5)
#3      _compile (package:dev_compiler/src/kernel/command.dart:344:27)
<asynchronous suspension>
#4      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#5      compile (package:dev_compiler/src/compiler/shared_command.dart:409:12)
#6      _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#12     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#18     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by kenzieschmoll** [comment]
closing - was able to fix by running `pub run build_runner clean`
