### ISSUE TITLE
NPE from Parser.parseLiteralFunctionSuffix (package:front_end/src/fasta/parser/parser.dart:4569:38)

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#37398]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.7479.19`
- `2.5.0-edge.499bb051f01cabd550a0d2623929a2d459aa88b8`
- `IC-191.7479.19, JRE 1.8.0_202-release-1483-b58x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.499bb051f01cabd550a0d2623929a2d459aa88b8, server version 1.27.1, error: Captured exception
NoSuchMethodError: The getter 'next' was called on null.
Receiver: null
Tried calling: next
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      Parser.parseLiteralFunctionSuffix (package:front_end/src/fasta/parser/parser.dart:4569:38)
#2      Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4601:14)
#3      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4288:14)
#4      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:4009:21)
#5      Parser.parseAwaitExpression (package:front_end/src/fasta/parser/parser.dart:5747:13)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4130:14)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3965:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3937:13)
#9      Parser.parseVariableInitializerOpt (package:front_end/src/fasta/parser/parser.dart:2509:15)
#10     Parser.parseOptionallyInitializedIdentifier (package:front_end/src/fasta/parser/parser.dart:5373:13)
#11     Parser.parseVariablesDeclarationRest (package:front_end/src/fasta/parser/parser.dart:5354:13)
#12     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5347:15)
#13     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3719:14)
#14     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3709:20)
#15     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3614:15)
#16     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2456:13)
#17     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2336:14)
#18     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:491:14)
#19     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#20     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#21     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#22     _File._parse (package:analyzer/src/services/available_declarations.dart:1656:23)
#23     _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#24     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:642:10)
#25     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:508:7)
#26     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#27     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2168:35)
<asynchronous suspension>
#28     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2118:5)
#29     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#30     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#31     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#32     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#38     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#39     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#40     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#42     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#43     new Future.sync (dart:async/future.dart:224:31)
#44     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#45     _rootRun (dart:async/zone.dart:1124:13)
#46     _CustomZone.run (dart:async/zone.dart:1021:19)
#47     _runZoned (dart:async/zone.dart:1516:10)
#48     runZoned (dart:async/zone.dart:1463:12)
#49     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#50     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#51     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#52     main (file:///Users/devoncarew/projects/dart-lang/sdk/pkg/analysis_server/bin/server.dart:12:11)
#53     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#54     main (file:///Users/devoncarew/projects/dart-lang/sdk/pkg/analysis_server/bin/server.dart:10:10)
#55     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/t6/ghq95c9n0xx7qb0kmk21bm6w003j4x/T/report.txt.

**Comment by devoncarew** [comment]
This is from an SDK built from head.

**Comment by bwilkerson** [comment]
@danrubel

**Comment by danrubel** [comment]
I looked at the code but didn't see anything amiss. Any information on how to reproduce this?

**Comment by danrubel** [comment]
Please reopen if you can figure out how to reproduce this.
