### ISSUE TITLE
Unsupported operation: unsupported initializer: IndexExpressionImpl

### ISSUE THREAD

**Issue by satyajitghana** [dart-lang/sdk#37390]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5522156`
- `2.3.2-edge.e3edfd36b2aa7ff4e98fe541ef5666ef2e70d17e`
- `AI-183.6156.11.34.5522156, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.3.2-edge.e3edfd36b2aa7ff4e98fe541ef5666ef2e70d17e, server version 1.26.1, error: Captured exception
Unsupported operation: unsupported initializer: IndexExpressionImpl :: super()[]
#0      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:1261:9)
#1      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2504:14)
#2      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2440:14)
#3      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3161:13)
#4      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3042:15)
#5      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2818:15)
#6      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1781:13)
#7      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1741:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:575:14)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#11     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#12     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#13     _File._parse (package:analyzer/src/services/available_declarations.dart:1633:23)
#14     _File.refresh (package:analyzer/src/services/available_declarations.dart:1071:30)
#15     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:639:10)
#16     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:505:7)
#17     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:225:13)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2142:35)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2092:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#23     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:532:21)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:617:12)
#29     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:530:7)
#30     Driver.start (package:analysis_server/src/server/driver.dart:435:7)
#31     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#32     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#33     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#34     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\shadowleaf\AppData\Local\Temp\report.txt.

## content of ``report.txt``
```
Dart analysis server, SDK version 2.3.2-edge.e3edfd36b2aa7ff4e98fe541ef5666ef2e70d17e, server version 1.26.1, error: Captured exception
Unsupported operation: unsupported initializer: IndexExpressionImpl :: super()[]
#0      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:1261:9)
#1      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2504:14)
#2      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2440:14)
#3      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3161:13)
#4      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3042:15)
#5      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2818:15)
#6      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1781:13)
#7      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1741:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:575:14)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#11     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#12     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#13     _File._parse (package:analyzer/src/services/available_declarations.dart:1633:23)
#14     _File.refresh (package:analyzer/src/services/available_declarations.dart:1071:30)
#15     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:639:10)
#16     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:505:7)
#17     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:225:13)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2142:35)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2092:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#23     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:532:21)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:617:12)
#29     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:530:7)
#30     Driver.start (package:analysis_server/src/server/driver.dart:435:7)
#31     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#32     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#33     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#34     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```
```
1561665199199 <= {"event":"analysis.closingLabels","params":{"file":"D:\\FlutterProjects\\upload\\bloc\\upload_event.dart","labels":[]}}
1561665199199 <= {"event":"analysis.outline","params":{"file":"D:\\FlutterProjects\\lib\\upload\\bloc\\upload_event.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT"
1561665199199 <= {"event":"analysis.overrides","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","overrides":[{"offset":336,"length":8,"superclassMember":{"ele
1561665199200 <= {"event":"flutter.outline","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":709,"codeOff
1561665199202 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1561665199204 <= {"event":"analysis.implemented","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","classes":[{"offset":103,"length":11}],"members":[]}}
1561665199212 => {"id":"99776","method":"edit.getAssists","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","offset":633,"length":73},"clientRequestTime":15616
1561665199215 <= {"id":"99776","result":{"assists":[]}}
1561665199460 => {"id":"99777","method":"edit.getAssists","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","offset":633,"length":73},"clientRequestTime":15616
1561665199462 <= {"id":"99777","result":{"assists":[]}}
1561665199500 => {"id":"99778","method":"analysis.updateContent","params":{"files":{"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart":{"type":"add","content":"import 'package:e
1561665199502 <= {"id":"99778","result":{}}
1561665199502 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1561665199503 => {"id":"99779","method":"edit.getAssists","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","offset":705,"length":0},"clientRequestTime":156166
1561665199510 <= {"event":"analysis.errors","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location"
1561665199510 <= {"id":"99779","result":{"assists":[]}}
1561665199516 <= {"event":"analysis.errors","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\register\\bloc\\register_event.dart","errors":[]}}
1561665199516 <= {"event":"analysis.highlights","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","regions":[]}}
1561665199516 <= {"event":"analysis.navigation","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","regions":[],"targets":[],"files":[]}}
1561665199516 <= {"event":"analysis.closingLabels","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","labels":[]}}
1561665199516 <= {"event":"analysis.outline","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT"
1561665199516 <= {"event":"analysis.overrides","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","overrides":[]}}
1561665199516 <= {"event":"flutter.outline","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\upload\\bloc\\upload_event.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":0,"codeOffse
1561665199517 <= {"event":"analysis.highlights","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\register\\bloc\\register_event.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":42},{"
1561665199517 <= {"event":"analysis.navigation","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\register\\bloc\\register_event.dart","regions":[{"offset":7,"length":34,"targets":[0]},{"offse
1561665199517 <= {"event":"analysis.closingLabels","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\register\\bloc\\register_event.dart","labels":[]}}
1561665199517 <= {"event":"analysis.outline","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\register\\bloc\\register_event.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_U
1561665199518 <= {"event":"analysis.overrides","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\register\\bloc\\register_event.dart","overrides":[{"offset":356,"length":8,"superclassMember":{
1561665199518 <= {"event":"flutter.outline","params":{"file":"D:\\FlutterProjects\\PROJECT_NAME\\lib\\register\\bloc\\register_event.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":938,"cod
1561665199529 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Unsupported operation: unsupported initializer: IndexExpressionImpl :: super()[]\n#0    
```

**Comment by mhadaily** [comment]
I have got similar issue
```Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.7479.19`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `IU-191.7479.19, JRE 1.8.0_202-release-1483-b58x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 2560x1440, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: Failed to handle completion domain request: {id: 2, method: completion.setSubscriptions, params: {subscriptions: [AVAILABLE_SUGGESTION_SETS]}, clientRequestTime: 1561963416783}
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _protocolAvailableSuggestionSet (package:analysis_server/src/domains/completion/available_suggestions.dart:141:35)
#2      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:75:14)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:76:8)
#6      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:482:11)
#7      _rootRunUnary (dart:async/zone.dart:1136:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/dv/wl5yfy6s6_b43yjpk82659c40000gn/T/report.txt.```


and report.text file 

```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: Failed to handle completion domain request: {id: 2, method: completion.setSubscriptions, params: {subscriptions: [AVAILABLE_SUGGESTION_SETS]}, clientRequestTime: 1561963416783}
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _protocolAvailableSuggestionSet (package:analysis_server/src/domains/completion/available_suggestions.dart:141:35)
#2      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:75:14)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:76:8)
#6      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:482:11)
#7      _rootRunUnary (dart:async/zone.dart:1136:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

```
1561967605119 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[968]}}
1561967605120 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[969]}}
1561967605125 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[970]}}
1561967605127 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[971]}}
1561967605130 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[972]}}
1561967605131 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[973]}}
1561967605136 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[976]}}
1561967605137 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[976]}}
1561967605140 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[976]}}
1561967605141 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[977]}}
1561967605142 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[978]}}
1561967605273 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1561967613573 <= {"event":"analysis.flushResults","params":{"files":["/Users/majid/Projects/Futurehome/smarthome-app/ios/Podfile.lock"]}}
1561967613573 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1561967613652 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1561967633924 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":960,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/shared_preference
1561967633924 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":961,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/shared_preference
1561967633925 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":962,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/shared_preference
1561967633925 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":963,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/shared_preference
1561967633925 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":964,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/shared_preference
1561967633926 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":965,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/shared_preference
1561967633926 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":966,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/firebase_analytic
1561967633926 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":967,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/firebase_analytic
1561967633927 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":968,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/firebase_analytic
1561967633929 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":969,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/firebase_analytic
1561967633929 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":970,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/firebase_analytic
1561967633929 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":971,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/firebase_analytic
1561967633930 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":972,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/firebase_analytic
1561967633930 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":973,"uri":"file:///Users/majid/Projects/Futurehome/smarthome-app/ios/.symlinks/plugins/firebase_analytic
1561967633941 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {id: 2, method: completion.setSubscriptions, params: {subscriptions: [AVAILABL
```

**Comment by danrubel** [comment]
https://github.com/dart-lang/sdk/issues/37285
