### ISSUE TITLE
Once flaky failure in lib_2/isolate/spawn_uri_exported_main_test on vm-dartkb-linux-debug-simarm64 now failing consistently

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#37407]
Last few builds on the vm-dartkb-linux-debug-simarm64 bot shows the following failure in lib_2/isolate/spawn_uri_exported_main_test ([example log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8909356850170312832/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0)):

```
/===========================================================================================================================\
| dartkb-compile-linux-debug-simarm64:lib_2/isolate/spawn_uri_exported_main_test failed again (RuntimeError, expected Pass) |
\===========================================================================================================================/

  --- Command "vm_compile_to_kernel []" (took 02.000525s):
  DART_CONFIGURATION=DebugSIMARM64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=out/DebugSIMARM64/vm_platform_strong.dill -o /b/s/w/ir/out/DebugSIMARM64/generated_compilations/dartkb/tests_lib_2_isolate_spawn_uri_exported_main_test/out.dill /b/s/w/ir/tests/lib_2/isolate/spawn_uri_exported_main_test.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true --gen-bytecode --drop-ast --bytecode-options=source-positions,local-var-info

  exit code:
  0

  --- Command "vm" (took 34.000448s):
  DART_CONFIGURATION=DebugSIMARM64 out/DebugSIMARM64/dart --use_bytecode_compiler --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/DebugSIMARM64/generated_compilations/dartkb/tests_lib_2_isolate_spawn_uri_exported_main_test/out.dill

  exit code:
  255

  stdout:
  Spawning isolate.

  stderr:
  Unhandled exception:
  Expect.fail('Isolate was not spawned successfully.')
  #0      Expect._fail (package:expect/expect.dart:655:5)
  #1      Expect.fail (package:expect/expect.dart:272:5)
  #2      main.<anonymous closure> (file:///b/s/w/ir/tests/lib_2/isolate/spawn_uri_exported_main_test.dart:10:12)
  #3      Timer._createTimer.<anonymous closure> (org-dartlang-sdk:///runtime/lib/timer_patch.dart)
  #4      _Timer._runTimers (org-dartlang-sdk:///runtime/lib/timer_impl.dart)
  #5      _Timer._handleMessage (org-dartlang-sdk:///runtime/lib/timer_impl.dart)
  #6      _RawReceivePortImpl._handleMessage (org-dartlang-sdk:///runtime/lib/isolate_patch.dart)

  --- Re-run this test:
  python tools/test.py -n dartkb-compile-linux-debug-simarm64 lib_2/isolate/spawn_uri_exported_main_test
```

It's been in the "ignored flaky test failures" log since at least mid-April, but it's now consistent enough to cause reds on the CI console. Approving the failure for now and filing this issue so it doesn't get lost.

**Comment by a-siva** [comment]
I think we should disable running of all tests which use spawnURI when the simulator architecture is used. It makes no sense to run have the kernel isolate compile the URI specified in spawnURI running on a simulator, would be slower to execute and lead to Timeouts .
Also the options --use_bytecode_compiler is not supported when running directly from sources in dartkb mode, the step to compile the spawnURI source with --use-bytecode-compiler will fail in all these simulator architectures.

**Comment by a-siva** [comment]
Submitted https://dart-review.googlesource.com/c/sdk/+/107832 to skip spawnURI tests from lib_2 when running on a simulator (simarm, simarm64 and simdbc64)
