### ISSUE TITLE
Default value of type Set in mock causes crash

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#37401]
With Analyzer using summary2 we support sets as constant values, and in google3 we have code `{Set<String> fields = const {}}`. This causes problems for DDC mock generation.

```dart
class A {
  void f({Set<int> a = const {}}) {
    print('a: $a');
  }
}

class B implements A {
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
```

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: -o test.js test.dart
    dart --version: 2.3.3-edge.c1b56a9ea0373b6498d17618f1bca6b4ffe5560a (Sat Jun 15 01:02:50 2019 +0000) on "macos_x64"
```
Unsupported operation: tried to generate an unreachable node: `Set<int> ({})`
#0      CodeGenerator._unreachable (package:dev_compiler/src/analyzer/code_generator.dart:6363:5)
#1      CodeGenerator._emitDartObject (package:dev_compiler/src/analyzer/code_generator.dart:4556:12)
#2      CodeGenerator._emitArgumentInitializers (package:dev_compiler/src/analyzer/code_generator.dart:2503:26)
#3      CodeGenerator._implementMockMember (package:dev_compiler/src/analyzer/code_generator.dart:1674:19)
#4      CodeGenerator._emitClassMethods.<anonymous closure> (package:dev_compiler/src/analyzer/code_generator.dart:1503:21)
#5      MappedIterator.moveNext (dart:_internal/iterable.dart:392:18)
#6      List.addAll (dart:core-patch/growable_array.dart:193:13)
#7      CodeGenerator._emitClassMethods (package:dev_compiler/src/analyzer/code_generator.dart:1502:15)
#8      CodeGenerator._emitClassDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:819:21)
#9      CodeGenerator.visitClassDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:778:12)
#10     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1560:49)
#11     CodeGenerator._emitTypeDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:511:26)
#12     CodeGenerator.visitCompilationUnit (package:dev_compiler/src/analyzer/code_generator.dart:565:9)
#13     List.forEach (dart:core-patch/array.dart:106:8)
#14     CodeGenerator.compile (package:dev_compiler/src/analyzer/code_generator.dart:318:22)
#15     compileWithAnalyzer (package:dev_compiler/src/analyzer/module_compiler.dart:108:33)
#16     _compile (package:dev_compiler/src/analyzer/command.dart:152:16)
#17     compile (package:dev_compiler/src/analyzer/command.dart:56:18)
#18     compile (package:dev_compiler/src/compiler/shared_command.dart:413:18)
#19     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:32:24)
<asynchronous suspension>
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```

**Comment by vsmenon** [comment]
I think we need to:

- Implement `_emitConstSet` as we do [`emitConstList`](https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/analyzer/code_generator.dart#L5760) but using `constSet` instead of `constList`.

- Add a clause [here](https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/analyzer/code_generator.dart#L4514) to handle the constant set case and call the above method.
