### ISSUE TITLE
dart:io WebSocket pinger doesn't stop on close

### ISSUE THREAD

**Issue by nailgilaziev** [dart-lang/sdk#37417]
After manually close connection `Unhandled Exception` is thrown in console because internal pinger mechanism doesn't stopped and trying to write to a closed connection

Code for reproducing is [here](https://github.com/nailgilaziev/ws_change_network_reaction/blob/issue_pinger_fail/lib/main.dart)

Steps to reproduce
1) press connect - see logs
2) write something and press send - see logs all fine
3) press disconnect button - see logs all fine
4) after some time < pingPeriod you see in logs `Unhandled exception`

```
flutter: 2019-07-01 22:45:59.939081   connect to ws://echo.websocket.org requested
flutter: 2019-07-01 22:46:00.818037   connect successfully established
flutter: 2019-07-01 22:46:05.524257   sended hi
flutter: 2019-07-01 22:46:05.723180   ws.listen received = hi
flutter: 2019-07-01 22:46:08.099786   manual disconnect pressed
flutter: 2019-07-01 22:46:08.124462   ws.done.then with details:
readyState:1 closeCode:null closeReason:null
flutter: 2019-07-01 22:46:08.125307   ws closed successfully
flutter: 2019-07-01 22:46:08.129901   wsSubscription closed successfully
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:585:24)
#1      _WebSocketConsumer.add (dart:_http/websocket_impl.dart:953:17)
#2      _WebSocketImpl.pingInterval=.<anonymous closure> (dart:_http/websocket_impl.dart:1198:17)
#3      _rootRun (dart:async/zone.dart:1120:38)
#4      _CustomZone.run (dart:async/zone.dart:1021:19)
#5      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
PS Why after closing connection `ws.done.then` callback called with `readyState:1`? This is another issue https://github.com/dart-lang/sdk/issues/33362  

*Environment:*
```
Flutter 1.7.12-pre.43 • channel master • https://github.com/flutter/flutter.git
Framework • revision ddd5ccd011 (3 hours ago) • 2019-07-01 08:28:34 -0700
Engine • revision e96900df2f
Tools • Dart 2.4.0
MacOS Mojave 10.14.5 (18F203)
iPhone 6 plus iOS 12.3.1
```

**Comment by ZichangG** [comment]
I will close this issue. Please checks the updates on the other one.

**Comment by nailgilaziev** [comment]
Other issue is created later than this one. 
You can’t reproduce issue there - no reproducible steps.
But you closed this issue. Hm...:)

**Comment by ZichangG** [comment]
I closed because it is a duplicate. Just leave one copy alive.
