### ISSUE TITLE
dart2js: serialization failure with ContainerTypeMask for very large array

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#37429]
https://dart-review.googlesource.com/c/sdk/+/107922/2 fails

Patch the cl and run `tools/test.py -n dart2js-hostasserts-linux-x64-d8 language_2/list_test`

The crash is in serializing a ContainerTypeMask with a large size that originates from the expression `new List(0x7ffffffffffff000)`.

```
The compiler crashed: 'package:compiler/src/serialization/abstract_sink.dart': Failed assertion: line 237 pos 12: 'value >= 0 && value >> 30 == 0': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      AbstractDataSink.writeInt (package:compiler/src/serialization/abstract_sink.dart:237:12)
#3      DataSinkMixin.writeIntOrNull (package:compiler/src/serialization/mixins.dart:395:7)
#4      ContainerTypeMask.writeToDataSink (package:compiler/src/inferrer/typemasks/container_type_mask.dart:56:10)
#5      CommonMasks.writeAbstractValueToDataSink.<anonymous closure> (package:compiler/src/inferrer/typemasks/masks.dart:867:42)
#6      AbstractDataSink.writeCached.<anonymous closure> (package:compiler/src/serialization/abstract_sink.dart:99:31)
#7      IndexedSink.write (package:compiler/src/serialization/helpers.dart:355:17)
#8      AbstractDataSink.writeCached (package:compiler/src/serialization/abstract_sink.dart:99:10)
#9      CommonMasks.writeAbstractValueToDataSink (package:compiler/src/inferrer/typemasks/masks.dart:866:10)
#10     GlobalTypeInferenceMemberResultImpl.writeToDataSink (package:compiler/src/inferrer/types.dart:438:25)
#11     GlobalTypeInferenceResultsImpl.writeToDataSink.<anonymous closure> (package:compiler/src/inferrer/types.dart:264:20)
#12     DataSinkMixin.writeMemberMap.<anonymous closure> (package:compiler/src/serialization/mixins.dart:529:10)
#13     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#14     DataSinkMixin.writeMemberMap (package:compiler/src/serialization/mixins.dart:527:11)
#15     GlobalTypeInferenceResultsImpl.writeToDataSink (package:compiler/src/inferrer/types.dart:261:10)
#16     serializeGlobalTypeInferenceResults (package:compiler/src/serialization/task.dart:32:11)
#17     BytesInMemorySerializationStrategy.serializeData (package:compiler/src/serialization/strategies.dart:59:5)
#18     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:431:37)
```

The options to fix this are:

1. Serialize the container length with a method capable of serializing all lengths. This may include constants from constant-folding to values outside the int64 range.
2. Constrain the discovered length to the range of values that may be serialized.

/cc @johnniwinther WDYT?

**Comment by rakudrama** [comment]
Fixed via 327f5eb82653e3ccfe0b5920af5c8e01335cee12
