### ISSUE TITLE
Error tokens sometimes causing parser to crash during error recovery

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#37491]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.7479.19`
- `2.5.0-dev.1.0`
- `IU-191.7479.19, JRE 1.8.0_202-release-1483-b58x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.5.0-dev.1.0, server version 1.27.1, error: Captured exception
Can't find ')' to match '('.
#0      ErrorToken.lexeme (package:front_end/src/fasta/scanner/error_token.dart:75:24)
#1      _withArgumentsExpectedClassMember (package:front_end/src/fasta/fasta_codes_generated.dart:3018:25)
#2      Parser.reportRecoverableErrorWithToken (package:front_end/src/fasta/parser/parser.dart:6365:18)
#3      Parser.recoverFromInvalidClassMember (package:front_end/src/fasta/parser/parser.dart:6315:7)
#4      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3085:16)
#5      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2902:15)
#6      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1793:13)
#7      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1753:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#11     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#12     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#13     _File._parse (package:analyzer/src/services/available_declarations.dart:1656:23)
#14     _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#15     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:601:14)
#16     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:636:16)
#17     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:508:7)
#18     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#19     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2168:35)
<asynchronous suspension>
#20     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2118:5)
#21     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#22     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#23     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#24     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#30     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#31     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#32     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#33     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#34     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#35     new Future.sync (dart:async/future.dart:224:31)
#36     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#42     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#43     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#44     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#46     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/c0/jv6k5x0j57vcwkdx6rcjgj3w0071_k/T/report.txt.

**Comment by kevmoo** [comment]
Related to https://github.com/dart-lang/sdk/issues/36840 ?

**Comment by kevmoo** [comment]
Reported by 2 other folks recently. CC @devoncarew @stereotype441

**Comment by bwilkerson** [comment]
@danrubel

**Comment by kevmoo** [comment]
Looks a lot like https://github.com/dart-lang/sdk/issues/36241

Hit this again!

**Comment by devoncarew** [comment]
@kevmoo, thanks for the ping - I agree w/ your prioritization. @danrubel is OOO this week; I asked him to take a look when he's back.

**Comment by danrubel** [comment]
This should prevent this error from occurring again, but similar errors could.
https://dart-review.googlesource.com/c/sdk/+/110100
More work to be done.

**Comment by danrubel** [comment]
I could not reproduce this, but as of https://dart-review.googlesource.com/c/sdk/+/110100, all error tokens are prepended to the token stream, and this *should* not occur again. Please reopen this or a new issue if this is still a problem.
