### ISSUE TITLE
Shadow node is left in the Kernel AST post recovery crashing transformations

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#37512]
Reproduction:

```dart
void foo(List<int> items) {
  for (final item : items);
}
```

Causes: 

```console
$ pkg/front_end/tool/fasta compile -t vm -o /tmp/test.dill /tmp/recovery.dart
file:///tmp/recovery.dart:4:19: Error: The final variable ':' must be initialized.
Try adding an initializer ('= <expression>') to the declaration.
  for (final item : items);
                  ^
file:///tmp/recovery.dart:4:19: Error: For-in loops use 'in' rather than a colon.
Try replacing the colon with the keyword 'in'.
  for (final item : items);
                  ^
Unhandled exception:
Crash when compiling null,
at character offset null:
file:///tmp/recovery.dart:4:19: Internal problem: Unsupported operation: 'accept'.
  for (final item : items);
                  ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:45:3)
#1      unsupported (package:front_end/src/fasta/problems.dart:72:10)
#2      SyntheticExpressionJudgment.accept (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1287:5)
#3      VariableDeclaration.visitChildren (package:kernel/ast.dart:4667:18)
#4      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:423:10)
#5      Visitor.defaultTreeNode (package:kernel/visitor.dart:337:39)
#6      TreeVisitor.defaultStatement (package:kernel/visitor.dart:198:41)
#7      TreeVisitor.visitVariableDeclaration (package:kernel/visitor.dart:220:7)
#8      VariableDeclaration.accept (package:kernel/ast.dart:4661:35)
#9      ForInStatement.visitChildren (package:kernel/ast.dart:4223:15)
#10     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:423:10)
#11     Visitor.defaultTreeNode (package:kernel/visitor.dart:337:39)
```

**Comment by mraleph** [comment]
This has been fixed, now we just get

```
/tmp/code.dart:2:19: Error: The final variable ':' must be initialized.
Try adding an initializer ('= expression') to the declaration.
  for (final item : items);
                  ^
/tmp/code.dart:2:19: Error: For-in loops use 'in' rather than a colon.
Try replacing the colon with the keyword 'in'.
  for (final item : items);
```
