### ISSUE TITLE
Exception: Can't find '}' to match '${' from Driver._captureExceptions

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#37528]
### What I was doing

Opening the https://github.com/JetBrains/intellij-plugins repo, in the `Dart/` directory.

I haven’t checked, but assume that the only Dart code in the Dart IntelliJ plugin repo are small samples to test the IntelliJ’s plugins parser.

### Versions

- Dart SDK 2.5.0-edge.ebbfb48e159fc03a8cc9b94b2a07a08567d28729
- Visual Studio Code 1.36.1
- Dart Code 3.2.0

### Exception

Captured exception

```text
Can't find '}' to match '${'.
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:615:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      Future._propagateToListeners (dart:async/future_impl.dart:555:16)
#3      Future._completeError (dart:async/future_impl.dart:491:5)
#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#5      _Completer.completeError (dart:async/future_impl.dart:27:5)
#6      _AsyncAwaitCompleter.completeError.<anonymous closure> (dart:async-patch/async_patch.dart:43:20)
#7      _rootRun (dart:async/zone.dart:1120:38)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by bwilkerson** [comment]
@danrubel That looks like the message from the parser error code `UnmatchedToken`, but if so how it ended up getting thrown as an exception is beyond me.

**Comment by danrubel** [comment]
Hopefully the above change will help provide better insight into the underlying issue.
