### ISSUE TITLE
The getter 'isVoid' was called on null in ErrorVerifier._checkForInvalidAssignment

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#37535]
```json
{"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/test/src/services/flutter/widget_descriptions_test.dart context: exception_20190715_130601_333","stackTrace":"NoSuchMethodError: The getter 'isVoid' was called on null.\nReceiver: null\nTried calling: isVoid\n#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)\n#1      ErrorVerifier._checkForInvalidAssignment (package:analyzer/src/generated/error_verifier.dart:3870:19)\n#2      ErrorVerifier.visitVariableDeclaration (package:analyzer/src/generated/error_verifier.dart:1414:5)\n#3      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10506:49)\n#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7662:20)\n#5      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10608:16)\n#6      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1308:10)\n#7      ErrorVerifier.visitVariableDeclarationList (package:analyzer/src/generated/error_verifier.dart:1447:11)\n#8      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10602:15)\n#9      FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4088:17)\n#10     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:857:10)\n#11     ErrorVerifier.visitFieldDeclaration (package:analyzer/src/generated/error_verifier.dart:722:13)\n#12     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4083:49)\n#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7662:20)\n#14     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)\n#15     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)\n#16     ErrorVerifier.visitClassDeclaration (package:analyzer/src/generated/error_verifier.dart:537:13)\n#17     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)\n#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7662:20)\n#19     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)\n#20     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)\n#21     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:576:11)\n#22     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)\n#23     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:418:10)\n#24     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:173:9)\n#25     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)\n#26     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:172:13)\n#27     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)\n#28     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:171:34)\n#29     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:112:14)\n#30     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)\n#31     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:111:43)\n#32     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1451:63)\n#33     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)\n#34     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1428:20)\n#35     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1228:17)\n<asynchronous suspension>\n#36     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2188:24)\n<asynchronous suspension>\n#37     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2118:5)\n#38     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)\n#39     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)\n#40     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)\n#41     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)\n#42     _rootRun (dart:async/zone.dart:1124:13)\n#43     _CustomZone.run (dart:async/zone.dart:1021:19)\n#44     _runZoned (dart:async/zone.dart:1516:10)\n#45     runZoned (dart:async/zone.dart:1463:12)\n#46     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)\n#47     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)\n#48     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)\n#49     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)\n#50     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)\n#51     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)\n#52     new Future.sync (dart:async/future.dart:224:31)\n#53     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)\n#54     _rootRun (dart:async/zone.dart:1124:13)\n#55     _CustomZone.run (dart:async/zone.dart:1021:19)\n#56     _runZoned (dart:async/zone.dart:1516:10)\n#57     runZoned (dart:async/zone.dart:1463:12)\n#58     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)\n#59     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)\n#60     Driver.start (package:analysis_server/src/server/driver.dart:439:21)\n#61     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:12:11)\n#62     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)\n#63     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:10:10)\n#64     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)\n#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)\n\n"}}
```

**Comment by bwilkerson** [comment]
Do you know how to reproduce this? I've tried a couple of ways and can't find a way to get a variable element whose type is not set.

**Comment by scheglov** [comment]
No, I lost the context :-(

**Comment by srawlins** [comment]
Closing as stale `.isVoid` is deprecated as well.
