### ISSUE TITLE
vm/dart/byte_array_test failing in hot-reload

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37548]
This appears to have started after 

```
[VM/runtime] Enable FLAG_unopt_megamorphic_calls by default, this fixes
             the recent regression seen in flutter hot reload benchmarks
	     after the roll of Dart BE into flutter post 1.7 release.

Change-Id: I188fa4aafdd7cdfa6b793de9d7ab00c9dae05409
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/109361
Reviewed-by: Ryan Macnak <rmacnak@google.com>
Commit-Queue: Siva Annamalai <asiva@google.com>
```

See logs:

https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-reload-linux-release-x64/5873
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-reload-linux-release-x64/5874
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-reload-linux-release-x64/5875

**Comment by a-siva** [comment]
There seems to be an issue with resetting the switchable calls state during reload.
```
out/ReleaseX64/dart --no-unopt-megamorphic-calls --hot-reload-test-mode --optimization_counter_threshold=10 --disable_alloc_stubs_after_gc --no-background-compilation runtime/tests/vm/dart/byte_array_test.dart
sivalinuxmach[sdk]>out/ReleaseX64/dart --hot-reload-test-mode --optimization_counter_threshold=10 --disable_alloc_stubs_after_gc --no-background-compilation runtime/tests/vm/dart/byte_array_test.dart
Unhandled exception:
type 'int' is not a subtype of type 'double' of 'value'
#0      Float32List.[]= (dart:typed_data-patch/typed_data_patch.dart)
#1      Lists.copy (dart:_internal-patch/internal_patch.dart:88:12)
#2      __Float32List&_TypedList&_DoubleListMixin&_TypedDoubleListMixin.setRange (dart:typed_data-patch/typed_data_patch.dart:774:17)
#3      __Float32List&_TypedList&_DoubleListMixin&_TypedDoubleListMixin.sublist (dart:typed_data-patch/typed_data_patch.dart:820:12)
#4      ByteArrayTest.testFloat32ListImpl (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/runtime/tests/vm/dart/byte_array_test.dart:1117:24)
#5      ByteArrayTest.testFloat32List (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/runtime/tests/vm/dart/byte_array_test.dart:1143:5)
#6      ByteArrayTest.testMain (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/runtime/tests/vm/dart/byte_array_test.dart:4638:5)
#7      main (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/runtime/tests/vm/dart/byte_array_test.dart:4658:19)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```

**Comment by mkustermann** [comment]
@rmacnak-google @a-siva If it takes longer to find the issue, we should consider disabling unopt megamorphic calls again to avoid rolling this into flutter.

**Comment by rmacnak-google** [comment]
An indexed get was specialized for Int64List.[] based on the single entry in the ICData, and guarded with a CheckClass for the dozen typed data array classes because of on CallTargets (ICData + MegamorphicCache). When a Float32List later came by, the CheckClass passed and the rest of the function saw an int instead of a double.
