### ISSUE TITLE
Incremental compiler appears to be in an inconsistent state

### ISSUE THREAD

**Issue by magnus-h-business** [dart-lang/sdk#37540]
[SEVERE]build_web_compilers:ddc on lib/single_ui/raw_workout_list_tile.ddc.module (cached): Error compiling dartdevc module:cg_analytics_flutter|lib/single_ui/raw_workout_list_tile.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
```
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/usr/lib/dart/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/cg_analytics_flutter/single_ui/raw_workout_list_tile.ddc.js --source-map -s packages/meta/meta.ddc.dill=packages/meta/meta -s packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers -s packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui -s packages/flutter_web/io.ddc.dill=packages/flutter_web/io -s packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions -s packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation -s packages/flutter_web/src/services/clipboard.ddc.dill=packages/flutter_web/src/services/clipboard -s packages/flutter_web/services.ddc.dill=packages/flutter_web/services -s packages/collection/src/utils.ddc.dill=packages/collection/src/utils -s packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms -s packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip -s packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators -s packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue -s packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map -s packages/collection/collection.ddc.dill=packages/collection/collection -s packages/flutter_web/src/scheduler/binding.ddc.dill=packages/flutter_web/src/scheduler/binding -s packages/flutter_web/scheduler.ddc.dill=packages/flutter_web/scheduler -s packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation -s packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics -s packages/flutter_web/src/gestures/arena.ddc.dill=packages/flutter_web/src/gestures/arena -s packages/flutter_web/gestures.ddc.dill=packages/flutter_web/gestures -s packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation -s packages/vector_math/hash.ddc.dill=packages/vector_math/hash -s packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 -s packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation -s packages/flutter_web/src/cupertino/action_sheet.ddc.dill=packages/flutter_web/src/cupertino/action_sheet -s packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino -s packages/flutter_web/material.ddc.dill=packages/flutter_web/material -s packages/cg_analytics_flutter/constants.ddc.dill=packages/cg_analytics_flutter/constants -s packages/cg_analytics_flutter/single_ui/header_text.ddc.dill=packages/cg_analytics_flutter/single_ui/header_text -s packages/cg_analytics_flutter/data/workout.ddc.dill=packages/cg_analytics_flutter/data/workout --packages file:///tmp/kernel_builder_HDGAKR/.packages --module-name packages/cg_analytics_flutter/single_ui/raw_workout_list_tile --multi-root-scheme org-dartlang-app --multi-root . --track-widget-creation --inline-source-map package:cg_analytics_flutter/single_ui/raw_workout_list_tile.dart
    dart --version: 2.3.1-dev.0.0 (Unknown timestamp) on "linux_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:100:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:120:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:440:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:392:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:233:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:232:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:41:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///tmp/tmp5tIaVF/dart-2.3.1-dev.0.0/dart/pkg/dev_compiler/bin/dartdevc.dart:54:39)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///tmp/tmp5tIaVF/dart-2.3.1-dev.0.0/dart/pkg/dev_compiler/bin/dartdevc.dart:54:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///tmp/tmp5tIaVF/dart-2.3.1-dev.0.0/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

I did a lot of refactoring (removed and renamed classes) before this bug happened. I had used webdev serve --auto restart so there were a lot of builds that rightfully failed before this happened.

**Comment by magnus-h-business** [comment]
A flutter clean solved the problem.

**Comment by vsmenon** [comment]
@jakemac53 - looks like we're getting an invalid dill?

**Comment by jakemac53** [comment]
cc @jensjoha

**Comment by jensjoha** [comment]
Seems to be the same as https://github.com/dart-lang/build/issues/2362 --- the file we're trying to load from is empty. (Why that is, I don't know)

**Comment by vsmenon** [comment]
Merging to:

https://github.com/dart-lang/sdk/issues/38102
