### ISSUE TITLE
dartfix should fast fail on analysis server crashes

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#37546]
When I run dartfix on a package, I see lots of exceptions back from the analysis server. These are all because the migration engine is a work in progress, however, I think that:

- dartfix should likely fail in the first exception (or first few?)
- it should then not offer the ‘files changed’ and ‘Rerun with --overwrite to apply these changes’ options at the end - it should just be a failure in the tool.

```
 • UnimplementedError: Decorating List<FileSystemEntity>

#0      new DecoratedType.forElement.decorate (package:nnbd_migration/src/decorated_type.dart:112:11)
#1      new DecoratedType.forElement.decorate (package:nnbd_migration/src/decorated_type.dart:106:33)
#2      new DecoratedType.forElement (package:nnbd_migration/src/decorated_type.dart:134:31)
#3      Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:177:26)
#4      Variables.decoratedElementType (package:nnbd_migration/src/variables.dart:41:43)
#5      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:140:38)
#6      EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:598:22)
#7      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7226:49)
#8      ForEachPartsImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261:16)
#9      ForEachPartsWithDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4300:11)
#10     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)

…

#125    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#126    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#127    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#128    _StreamController._add (dart:async/stream_controller.dart:640:7)
#129    _StreamController.add (dart:async/stream_controller.dart:586:5)
#130    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1335:33)
#131    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:856:14)
#132    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#133    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#134    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#135    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)



Files to be changed:
  analysis_options.yaml
  tool/perf.dart
  lib/src/build_mode.dart
  lib/src/analyzer_impl.dart
  lib/src/driver.dart
  lib/src/error_severity.dart
  lib/starter.dart
  bin/analyzer.dart
  test/analysis_options_test.dart
  test/mocks.dart
  test/driver_test.dart

Rerun with --overwrite to apply these changes.
```

cc @danrubel

**Comment by bwilkerson** [comment]
`dartfix` is temporarily in a mode in which it intentionally does _not_ fail on the first error discovered by the migration engine expressly so that we will get back information about as many errors as possible (controlled by `NonNullableFix._usePermissiveMode` in case you want to try changing it). This has significantly improved our velocity as we develop the engine, but is definitely _not_ the mode we intend to use when we ship the tool. When the migration engine is far enough along that it makes sense for other people to try it out I'm sure we'll switch the default.

**Comment by devoncarew** [comment]
Gotcha. Sounds like the UI is a temporary state while under development, and that we'll just want to ensure that errors are handled appropriately down the road.

**Comment by devoncarew** [comment]
Closing as we're not currently shipping this tool.
