### ISSUE TITLE
NPE in ResolverVisitor.visitDefaultFormalParameter (SDK 2.3.0-edge.a16685)

### ISSUE THREAD

**Issue by HappyGhostz** [dart-lang/sdk#37561]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 2560x1440, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: Analysis failed: /Users/chenping.zhao/work/food_mex_mobile/lib/integrated/orders/base/connectivity_detector.dart context: exception_20190718_132322_284
NoSuchMethodError: The getter 'initializer' was called on null.
Receiver: null
Tried calling: initializer
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      ResolverVisitor.visitDefaultFormalParameter (package:analyzer/src/generated/resolver.dart:4257:17)
#2      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3070:15)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7550:20)
#4      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4349:17)
#5      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4711:10)
#6      UnifyingAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:3201:59)
#7      ScopedVisitor.visitFormalParameterList (package:analyzer/src/generated/resolver.dart:5825:11)
#8      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4345:49)
#9      GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5263:18)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4711:10)
#11     UnifyingAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:3235:59)
#12     ScopedVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:5969:13)
#13     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5256:20)
#14     FunctionTypeAliasImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5051:18)
#15     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4711:10)
#16     UnifyingAstVisitor.visitFunctionTypeAlias (package:analyzer/dart/ast/visitor.dart:3228:55)
#17     ScopedVisitor.visitFunctionTypeAliasInScope (package:analyzer/src/generated/resolver.dart:5937:11)
#18     ResolverVisitor.visitFunctionTypeAliasInScope (package:analyzer/src/generated/resolver.dart:4519:11)
#19     ScopedVisitor.visitFunctionTypeAlias (package:analyzer/src/generated/resolver.dart:5930:7)
#20     ResolverVisitor.visitFunctionTypeAlias (package:analyzer/src/generated/resolver.dart:4511:13)
#21     FunctionTypeAliasImpl.accept (package:analyzer/src/dart/ast/ast.dart:5046:49)
#22     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:4150:23)
#23     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2147:49)
#24     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:654:10)
#25     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:136:7)
#26     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#27     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:135:11)
#28     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:14)
#29     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#30     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:43)
#31     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1450:63)
#32     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#33     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1427:20)
#34     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1247:33)
<asynchronous suspension>
#35     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2160:24)
<asynchronous suspension>
#36     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2090:5)
#37     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#38     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#39     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#40     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#46     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#47     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#48     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#49     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#50     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#51     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/3g/6m2gs_hn23lc4y8q1xf43pgm0000gq/T/report.txt.

**Comment by devoncarew** [comment]
2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e is an older SDK version now that 2.4.0 is out, so the crash may be obsolete.

**Comment by HappyGhostz** [comment]
ok thanks
