### ISSUE TITLE
Class 'FunctionElementForLink_Synthetic' has no instance getter 'identifier' on SDK 2.5.0-edge.

### ISSUE THREAD

**Issue by krooq** [dart-lang/sdk#37578]
Origninally posted here: https://github.com/Dart-Code/Dart-Code/issues/1879

The following will pass static analysis, compile and run however dart code will not understand anything in the usage.dart file.

```
// func.dart
final f = <A,B>(A a) => (B b) => a;
// usage.dart
import 'func.dart';
int a = 1;
String b = "string";
final result= f<int,String>(a)(b);
main(){
    print(result); // prints "1"
}
```

Strangely if the function f is in the same file as the usage or even if the part and part of directives are used instead of import then usage.dart is parsed fine.
Also if the file is declared in a top level library file e.g. library func for example, then this library can be imported and used without issue.
Function literals with single type parameters seem to be imported fine.

//importing and using causes no issue
`final f = <A>(A a) => (String b) => a;`
Providing an explicit type signature to the function literal avoids the issue too.

//importing and using causes no issue
`final A Function(B) Function(A) f = <A,B>(A a) => (B b) => a;`
Difficult to place this bug, similar behavior was observed in Android Studio.

Using:
Dart 2.4.0
Dart Code 3.2.1

**Comment by devoncarew** [comment]
I can reproduce this on `- Dart SDK 2.5.0-edge.75f6822c704045aaaa47a84d0711324a05a44ce3`, and see the following exception:

```text
NoSuchMethodError: Class 'FunctionElementForLink_Synthetic' has no instance getter 'identifier'.
Receiver: Instance of 'FunctionElementForLink_Synthetic'
Tried calling: identifier
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      FunctionElementForLink_Synthetic.noSuchMethod (package:analyzer/src/summary/link.dart:3148:48)
#2      FunctionElementForLink_Synthetic.identifier (package:analyzer/src/dart/element/element.dart:3572:14)
#3      new ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3946:54)
#4      ElementImpl.location (package:analyzer/src/dart/element/element.dart:3643:29)
#5      ElementImpl.== (package:analyzer/src/dart/element/element.dart:3713:16)
#6      TypeParameterTypeImpl.== (package:analyzer/src/dart/element/type.dart:3119:51)
#7      TypeParameterTypeImpl.substitute2 (package:analyzer/src/dart/element/type.dart:3272:67)
#8      TypeImpl.substitute (package:analyzer/src/dart/element/type.dart:3080:12)
#9      _FunctionTypeImplLazy.substitute2 (package:analyzer/src/dart/element/type.dart:3718:18)
#10     _FunctionTypeImplLazy.returnType (package:analyzer/src/dart/element/type.dart:3574:41)
#11     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:786:42)
#12     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:581:16)
#13     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:75:7)
#14     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:523:31)
#15     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
#16     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:4830:10)
#17     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
#18     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:4828:18)
#19     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
#20     ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2563:16)
#21     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5384:36)
#22     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5227:7)
#23     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2225:13)
#24     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2244:18)
#25     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5660:47)
#26     TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5212:48)
#27     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1641:16)
#28     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3867:12)
#29     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3567:15)
#30     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3507:7)
#31     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2225:13)
#32     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2244:18)
#33     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3540:42)
#34     Linker.link (package:analyzer/src/summary/link.dart:4072:35)
#35     _relink (package:analyzer/src/summary/link.dart:311:74)
#36     link (package:analyzer/src/summary/link.dart:125:3)
#37     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:220:25)
#38     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#39     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:219:12)
#40     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1641:23)
#41     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1438:30)
#42     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#43     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1428:20)
#44     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1248:33)
<asynchronous suspension>
#45     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2188:24)
<asynchronous suspension>
#46     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2118:5)
#47     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#48     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#49     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#50     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#51     _rootRun (dart:async/zone.dart:1124:13)
#52     _CustomZone.run (dart:async/zone.dart:1021:19)
#53     _runZoned (dart:async/zone.dart:1516:10)
#54     runZoned (dart:async/zone.dart:1463:12)
#55     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#56     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#57     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#58     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#59     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#60     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#61     new Future.sync (dart:async/future.dart:224:31)
#62     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#63     _rootRun (dart:async/zone.dart:1124:13)
#64     _CustomZone.run (dart:async/zone.dart:1021:19)
#65     _runZoned (dart:async/zone.dart:1516:10)
#66     runZoned (dart:async/zone.dart:1463:12)
#67     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#68     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#69     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#70     main (file:///Users/devoncarew/projects/dart-lang/sdk/pkg/analysis_server/bin/server.dart:12:11)
#71     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#72     main (file:///Users/devoncarew/projects/dart-lang/sdk/pkg/analysis_server/bin/server.dart:10:10)
#73     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by devoncarew** [comment]
Repro case:

[foo.zip](https://github.com/dart-lang/sdk/files/3412862/foo.zip)

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.5; please re-open if you see this in a recent version of Dart/Flutter.
