### ISSUE TITLE
'ConstructorElementImpl' is not a subtype of type 'MethodElement' (SDK 2.4.0)

### ISSUE THREAD

**Issue by duzenko** [dart-lang/sdk#37580]
I got a Dart Analyzer Error in Anroid Studio console that prompted to "Open issue submission form?"
However it fails to open anything due to the HTTP error
The url was:
```
https://github.com/dart-lang/sdk/issues/new?body=Analyzer+Feedback+from+IntelliJ%0A%0A%23%23+Version+information%0A%0A-+%60IDEA+AI-183.6156.11.34.5692245%60%0A-+%602.4.0%60%0A-+%60AI-183.6156.11.34.5692245%2C+JRE+1.8.0_212-b04x32+%2C+OS+Windows+10%28x86%29+v10.0+%2C+screens+3840x2160%2C+3840x2160%60%0A%0A%23%23+Exception%0A%60%60%60%0ADart+analysis+server%2C+SDK+version+2.4.0%2C+server+version+1.27.1%2C+error%3A+Analysis+failed%3A+D%3A%5Cdev%5Cpavement%5Clib%5Cutil%5CFutureResult.dart+context%3A+exception_20190719_135148_046%0AElement+mismatch+in+D%3A%5Cdev%5Cpavement%5Clib%5Cutil%5CFutureResult.dart+at+class+FutureResult%3CT%3E%0A%230++++++DeclarationResolver.resolve+%28package%3Aanalyzer%2Fsrc%2Fgenerated%2Fdeclaration_resolver.dart%3A49%3A7%29%0A%231++++++LibraryAnalyzer._resolveFile+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Flibrary_analyzer.dart%3A659%3A31%29%0A%232++++++LibraryAnalyzer.analyzeSync.%3Canonymous+closure%3E+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Flibrary_analyzer.dart%3A155%3A7%29%0A%233++++++__InternalLinkedHashMap%26_HashVMBase%26MapMixin%26_LinkedHashMapMixin.forEach+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A367%3A8%29%0A%234++++++LibraryAnalyzer.analyzeSync+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Flibrary_analyzer.dart%3A154%3A11%29%0A%235++++++LibraryAnalyzer.analyze.%3Canonymous+closure%3E+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Flibrary_analyzer.dart%3A108%3A14%29%0A%236++++++_PerformanceTagImpl.makeCurrentWhile+%28package%3Aanalyzer%2Fsrc%2Fgenerated%2Futilities_general.dart%3A258%3A15%29%0A%237++++++LibraryAnalyzer.analyze+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Flibrary_analyzer.dart%3A107%3A43%29%0A%238++++++AnalysisDriver._computeAnalysisResult.%3Canonymous+closure%3E+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fdriver.dart%3A1418%3A63%29%0A%239++++++PerformanceLog.run+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fperformance_logger.dart%3A34%3A15%29%0A%2310+++++AnalysisDriver._computeAnalysisResult+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fdriver.dart%3A1395%3A20%29%0A%2311+++++AnalysisDriver.performWork+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fdriver.dart%3A1195%3A17%29%0A%3Casynchronous+suspension%3E%0A%2312+++++AnalysisDriverScheduler._run+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fdriver.dart%3A2132%3A24%29%0A%3Casynchronous+suspension%3E%0A%2313+++++AnalysisDriverScheduler.start+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fdriver.dart%3A2062%3A5%29%0A%2314+++++new+AnalysisServer+%28package%3Aanalysis_server%2Fsrc%2Fanalysis_server.dart%3A208%3A29%29%0A%2315+++++SocketServer.createAnalysisServer+%28package%3Aanalysis_server%2Fsrc%2Fsocket_server.dart%3A86%3A26%29%0A%2316+++++StdioAnalysisServer.serveStdio+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fstdio_server.dart%3A37%3A18%29%0A%2317+++++Driver.startAnalysisServer.%3Canonymous+closure%3E+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A542%3A21%29%0A%2318+++++_rootRun+%28dart%3Aasync%2Fzone.dart%3A1124%3A13%29%0A%2319+++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1021%3A19%29%0A%2320+++++_runZoned+%28dart%3Aasync%2Fzone.dart%3A1516%3A10%29%0A%2321+++++runZoned+%28dart%3Aasync%2Fzone.dart%3A1463%3A12%29%0A%2322+++++Driver._captureExceptions+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A627%3A12%29%0A%2323+++++Driver.startAnalysisServer+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A540%3A7%29%0A%2324+++++Driver.start.%3Canonymous+closure%3E+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A444%3A9%29%0A%2325+++++_AsyncAwaitCompleter.start+%28dart%3Aasync-patch%2Fasync_patch.dart%3A49%3A6%29%0A%2326+++++Driver.start.%3Canonymous+closure%3E+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A439%3A43%29%0A%2327+++++CompilerContext.runInContext.%3Canonymous+closure%3E.%3Canonymous+closure%3E+%28package%3Afront_end%2Fsrc%2Ffasta%2Fcompiler_context.dart%3A122%3A46%29%0A%2328+++++new+Future.sync+%28dart%3Aasync%2Ffuture.dart%3A224%3A31%29%0A%2329+++++CompilerContext.runInContext.%3Canonymous+closure%3E+%28package%3Afront_end%2Fsrc%2Ffasta%2Fcompiler_context.dart%3A122%3A19%29%0A%2330+++++_rootRun+%28dart%3Aasync%2Fzone.dart%3A1124%3A13%29%0A%2331+++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1021%3A19%29%0A%2332+++++_runZoned+%28dart%3Aasync%2Fzone.dart%3A1516%3A10%29%0A%2333+++++runZoned+%28dart%3Aasync%2Fzone.dart%3A1463%3A12%29%0A%2334+++++CompilerContext.runInContext+%28package%3Afront_end%2Fsrc%2Ffasta%2Fcompiler_context.dart%3A121%3A12%29%0A%2335+++++CompilerContext.runWithDefaultOptions+%28package%3Afront_end%2Fsrc%2Ffasta%2Fcompiler_context.dart%3A140%3A56%29%0A%2336+++++Driver.start+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A439%3A21%29%0A%2337+++++main+%28file%3A%2F%2F%2FC%3A%2Fb%2Fs%2Fw%2Fir%2Fk%2Fsrc%2Fthird_party%2Fdart%2Fpkg%2Fanalysis_server%2Fbin%2Fserver.dart%3A12%3A11%29%0A%2338+++++_AsyncAwaitCompleter.start+%28dart%3Aasync-patch%2Fasync_patch.dart%3A49%3A6%29%0A%2339+++++main+%28file%3A%2F%2F%2FC%3A%2Fb%2Fs%2Fw%2Fir%2Fk%2Fsrc%2Fthird_party%2Fdart%2Fpkg%2Fanalysis_server%2Fbin%2Fserver.dart%3A10%3A10%29%0A%2340+++++_startIsolate.%3Canonymous+closure%3E+%28dart%3Aisolate-patch%2Fisolate_patch.dart%3A299%3A32%29%0A%2341+++++_RawReceivePortImpl._handleMessage+%28dart%3Aisolate-patch%2Fisolate_patch.dart%3A172%3A12%29%0A%0ACaused+by+type+%27ConstructorElementImpl%27+is+not+a+subtype+of+type+%27MethodElement%27+in+type+cast%0A%230++++++MethodElementHandle.actualElement+%28package%3Aanalyzer%2Fsrc%2Fdart%2Felement%2Fhandle.dart%3A1021%3A58%29%0A%231++++++MethodElementHandle.isStatic+%28package%3Aanalyzer%2Fsrc%2Fdart%2Felement%2Fhandle.dart%3A1027%3A24%29%0A%232++++++_ReferenceInfo._buildType+%28package%3Aanalyzer%2Fsrc%2Fsummary%2Fresynthesize.dart%3A1137%3A58%29%0A%233++++++_ReferenceInfo.buildType+%28package%3Aanalyzer%2Fsrc%2Fsummary%2Fresynthesize.dart%3A1002%3A15%29%0A%234++++++_UnitResynthesizer.buildType+%28package%3Aanalyzer%2Fsrc%2Fsummary%2Fresynthesize.dart%3A1397%3A30%29%0A%235++++++_UnitResynthesizer.buildLinkedType+%28package%3Aanalyzer%2Fsrc%2Fsummary%2Fresynthesize.dart%3A1349%3A12%29%0A%236++++++SummaryResynthesizerContext.resolveLinkedType+%28package%3Aanalyzer%2Fsrc%2Fsummary%2Fresynthesize.dart%3A488%3A30%29%0A%237++++++NonParameterVariableElementImpl.type+%28package%3Aanalyzer%2Fsrc%2Fdart%2Felement%2Felement.dart%3A8055%3A12%29%0A%238++++++PropertyInducingElementImpl.type+%28package%3Aanalyzer%2Fsrc%2Fdart%2Felement%2Felement.dart%3A9230%3A18%29%0A%239++++++DeclarationResolver.visitVariableDeclarationList+%28package%3Aanalyzer%2Fsrc%2Fgenerated%2Fdeclaration_resolver.dart%3A481%3A56%29%0A%2310+++++VariableDeclarationListImpl.accept+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fast%2Fast.dart%3A10620%3A15%29%0A%2311+++++FieldDeclarationImpl.visitChildren+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fast%2Fast.dart%3A4004%3A17%29%0A%2312+++++RecursiveAstVisitor.visitFieldDeclaration+%28package%3Aanalyzer%2Fdart%2Fast%2Fvisitor.dart%3A853%3A10%29%0A%2313+++++DeclarationResolver.visitFieldDeclaration+%28package%3Aanalyzer%2Fsrc%2Fgenerated%2Fdeclaration_resolver.dart%3A188%3A11%29%0A%2314+++++FieldDeclarationImpl.accept+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fast%2Fast.dart%3A3999%3A49%29%0A%2315+++++NodeListImpl.accept+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fast%2Fast.dart%3A7676%3A20%29%0A%2316+++++ClassDeclarationImpl.visitChildren+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fast%2Fast.dart%3A1590%3A13%29%0A%2317+++++RecursiveAstVisitor.visitClassDeclaration+%28package%3Aanalyzer%2Fdart%2Fast%2Fvisitor.dart%3A703%3A10%29%0A%2318+++++DeclarationResolver.visitClassDeclaration.%3Canonymous+closure%3E+%28package%3Aanalyzer%2Fsrc%2Fgenerated%2Fdeclaration_resolver.dart%3A84%3A13%29%0A%2319+++++DeclarationResolver._walk+%28package%3Aanalyzer%2Fsrc%2Fgenerated%2Fdeclaration_resolver.dart%3A549%3A13%29%0A%2320+++++DeclarationResolver.visitClassDeclaration+%28package%3Aanalyzer%2Fsrc%2Fgenerated%2Fdeclaration_resolver.dart%3A83%3A5%29%0A%2321+++++ClassDeclarationImpl.accept+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fast%2Fast.dart%3A1560%3A49%29%0A%2322+++++NodeListImpl.accept+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fast%2Fast.dart%3A7676%3A20%29%0A%2323+++++CompilationUnitImpl.visitChildren+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fast%2Fast.dart%3A2167%3A21%29%0A%2324+++++RecursiveAstVisitor.visitCompilationUnit+%28package%3Aanalyzer%2Fdart%2Fast%2Fvisitor.dart%3A727%3A10%29%0A%2325+++++CompilationUnitImpl.accept+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fast%2Fast.dart%3A2146%3A49%29%0A%2326+++++DeclarationResolver.resolve+%28package%3Aanalyzer%2Fsrc%2Fgenerated%2Fdeclaration_resolver.dart%3A46%3A12%29%0A%2327+++++LibraryAnalyzer._resolveFile+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Flibrary_analyzer.dart%3A659%3A31%29%0A%2328+++++LibraryAnalyzer.analyzeSync.%3Canonymous+closure%3E+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Flibrary_analyzer.dart%3A155%3A7%29%0A%2329+++++__InternalLinkedHashMap%26_HashVMBase%26MapMixin%26_LinkedHashMapMixin.forEach+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A367%3A8%29%0A%2330+++++LibraryAnalyzer.analyzeSync+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Flibrary_analyzer.dart%3A154%3A11%29%0A%2331+++++LibraryAnalyzer.analyze.%3Canonymous+closure%3E+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Flibrary_analyzer.dart%3A108%3A14%29%0A%2332+++++_PerformanceTagImpl.makeCurrentWhile+%28package%3Aanalyzer%2Fsrc%2Fgenerated%2Futilities_general.dart%3A258%3A15%29%0A%2333+++++LibraryAnalyzer.analyze+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Flibrary_analyzer.dart%3A107%3A43%29%0A%2334+++++AnalysisDriver._computeAnalysisResult.%3Canonymous+closure%3E+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fdriver.dart%3A1418%3A63%29%0A%2335+++++PerformanceLog.run+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fperformance_logger.dart%3A34%3A15%29%0A%2336+++++AnalysisDriver._computeAnalysisResult+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fdriver.dart%3A1395%3A20%29%0A%2337+++++AnalysisDriver.performWork+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fdriver.dart%3A1195%3A17%29%0A%3Casynchronous+suspension%3E%0A%2338+++++AnalysisDriverScheduler._run+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fdriver.dart%3A2132%3A24%29%0A%3Casynchronous+suspension%3E%0A%2339+++++AnalysisDriverScheduler.start+%28package%3Aanalyzer%2Fsrc%2Fdart%2Fanalysis%2Fdriver.dart%3A2062%3A5%29%0A%2340+++++new+AnalysisServer+%28package%3Aanalysis_server%2Fsrc%2Fanalysis_server.dart%3A208%3A29%29%0A%2341+++++SocketServer.createAnalysisServer+%28package%3Aanalysis_server%2Fsrc%2Fsocket_server.dart%3A86%3A26%29%0A%2342+++++StdioAnalysisServer.serveStdio+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fstdio_server.dart%3A37%3A18%29%0A%2343+++++Driver.startAnalysisServer.%3Canonymous+closure%3E+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A542%3A21%29%0A%2344+++++_rootRun+%28dart%3Aasync%2Fzone.dart%3A1124%3A13%29%0A%2345+++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1021%3A19%29%0A%2346+++++_runZoned+%28dart%3Aasync%2Fzone.dart%3A1516%3A10%29%0A%2347+++++runZoned+%28dart%3Aasync%2Fzone.dart%3A1463%3A12%29%0A%2348+++++Driver._captureExceptions+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A627%3A12%29%0A%2349+++++Driver.startAnalysisServer+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A540%3A7%29%0A%2350+++++Driver.start.%3Canonymous+closure%3E+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A444%3A9%29%0A%2351+++++_AsyncAwaitCompleter.start+%28dart%3Aasync-patch%2Fasync_patch.dart%3A49%3A6%29%0A%2352+++++Driver.start.%3Canonymous+closure%3E+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A439%3A43%29%0A%2353+++++CompilerContext.runInContext.%3Canonymous+closure%3E.%3Canonymous+closure%3E+%28package%3Afront_end%2Fsrc%2Ffasta%2Fcompiler_context.dart%3A122%3A46%29%0A%2354+++++new+Future.sync+%28dart%3Aasync%2Ffuture.dart%3A224%3A31%29%0A%2355+++++CompilerContext.runInContext.%3Canonymous+closure%3E+%28package%3Afront_end%2Fsrc%2Ffasta%2Fcompiler_context.dart%3A122%3A19%29%0A%2356+++++_rootRun+%28dart%3Aasync%2Fzone.dart%3A1124%3A13%29%0A%2357+++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1021%3A19%29%0A%2358+++++_runZoned+%28dart%3Aasync%2Fzone.dart%3A1516%3A10%29%0A%2359+++++runZoned+%28dart%3Aasync%2Fzone.dart%3A1463%3A12%29%0A%2360+++++CompilerContext.runInContext+%28package%3Afront_end%2Fsrc%2Ffasta%2Fcompiler_context.dart%3A121%3A12%29%0A%2361+++++CompilerContext.runWithDefaultOptions+%28package%3Afront_end%2Fsrc%2Ffasta%2Fcompiler_context.dart%3A140%3A56%29%0A%2362+++++Driver.start+%28package%3Aanalysis_server%2Fsrc%2Fserver%2Fdriver.dart%3A439%3A21%29%0A%2363+++++main+%28file%3A%2F%2F%2FC%3A%2Fb%2Fs%2Fw%2Fir%2Fk%2Fsrc%2Fthird_party%2Fdart%2Fpkg%2Fanalysis_server%2Fbin%2Fserver.dart%3A12%3A11%29%0A%2364+++++_AsyncAwaitCompleter.start+%28dart%3Aasync-patch%2Fasync_patch.dart%3A49%3A6%29%0A%2365+++++main+%28file%3A%2F%2F%2FC%3A%2Fb%2Fs%2Fw%2Fir%2Fk%2Fsrc%2Fthird_party%2Fdart%2Fpkg%2Fanalysis_server%2Fbin%2Fserver.dart%3A10%3A10%29%0A%2366+++++_startIsolate.%3Canonymous+closure%3E+%28dart%3Aisolate-patch%2Fisolate_patch.dart%3A299%3A32%29%0A%2367+++++_RawReceivePortImpl._handleMessage+%28dart%3Aisolate-patch%2Fisolate_patch.dart%3A172%3A12%29%0A%60%60%60%0A%0AFor+additional+log+information%2C+please+append+the+contents+of%0Afile%3A%2F%2FC%3A%5CUsers%5Canton.duzenko%5CAppData%5CLocal%5CTemp%5Creport.txt.
```

**Comment by devoncarew** [comment]
It looks like the url is 13k long; when reproing this, the github headers don't say what their limit is.

Here's the decoded exception text:

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_212-b04x32 , OS Windows 10(x86) v10.0 , screens 3840x2160, 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: D:\dev\pavement\lib\util\FutureResult.dart context: exception_20190719_135148_046
Element mismatch in D:\dev\pavement\lib\util\FutureResult.dart at class FutureResult<T>
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:659:31)
#2      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:155:7)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#4      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:154:11)
#5      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:108:14)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#7      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:43)
#8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1418:63)
#9      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
#11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1195:17)
<asynchronous suspension>
#12     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
<asynchronous suspension>
#13     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#14     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#15     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#16     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#17     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#23     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#24     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#25     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#26     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#27     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#35     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#36     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#37     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#38     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#39     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Caused by type 'ConstructorElementImpl' is not a subtype of type 'MethodElement' in type cast
#0      MethodElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:1021:58)
#1      MethodElementHandle.isStatic (package:analyzer/src/dart/element/handle.dart:1027:24)
#2      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1137:58)
#3      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:1002:15)
#4      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1397:30)
#5      _UnitResynthesizer.buildLinkedType (package:analyzer/src/summary/resynthesize.dart:1349:12)
#6      SummaryResynthesizerContext.resolveLinkedType (package:analyzer/src/summary/resynthesize.dart:488:30)
#7      NonParameterVariableElementImpl.type (package:analyzer/src/dart/element/element.dart:8055:12)
#8      PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:9230:18)
#9      DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/declaration_resolver.dart:481:56)
#10     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10620:15)
#11     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4004:17)
#12     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:853:10)
#13     DeclarationResolver.visitFieldDeclaration (package:analyzer/src/generated/declaration_resolver.dart:188:11)
#14     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3999:49)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#16     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1590:13)
#17     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:703:10)
#18     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:84:13)
#19     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:549:13)
#20     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:83:5)
#21     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1560:49)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#23     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2167:21)
#24     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:727:10)
#25     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#26     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:46:12)
#27     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:659:31)
#28     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:155:7)
#29     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#30     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:154:11)
#31     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:108:14)
#32     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#33     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:43)
#34     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1418:63)
#35     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#36     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
#37     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1195:17)
<asynchronous suspension>
#38     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
<asynchronous suspension>
#39     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#40     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#41     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#42     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#43     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _runZoned (dart:async/zone.dart:1516:10)
#47     runZoned (dart:async/zone.dart:1463:12)
#48     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#49     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#50     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#51     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#52     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#53     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#54     new Future.sync (dart:async/future.dart:224:31)
#55     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#56     _rootRun (dart:async/zone.dart:1124:13)
#57     _CustomZone.run (dart:async/zone.dart:1021:19)
#58     _runZoned (dart:async/zone.dart:1516:10)
#59     runZoned (dart:async/zone.dart:1463:12)
#60     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#61     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#62     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#63     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#64     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#65     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#66     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#67     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by MichaelRFairhurst** [comment]
Likely the same as fuzz crash #38090

**Comment by duzenko** [comment]
Closing as ignored
