### ISSUE TITLE
'CompilationUnitElementImpl' is not a subtype of type 'ClassElement' in ErrorVerifier._findOverriddenMemberThatMustCallSuper (SDK 2.4.0)

### ISSUE THREAD

**Issue by duzenko** [dart-lang/sdk#37592]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_212-b04x32 , OS Windows 10(x86) v10.0 , screens 3840x2160, 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: D:\dev\pavement\lib\bids\models.dart context: exception_20190722_133904_943
type 'CompilationUnitElementImpl' is not a subtype of type 'ClassElement'
#0      ErrorVerifier._findOverriddenMemberThatMustCallSuper (package:analyzer/src/generated/error_verifier.dart:6112:18)
#1      ErrorVerifier._checkForMustCallSuper (package:analyzer/src/generated/error_verifier.dart:4449:29)
#2      ErrorVerifier.visitMethodDeclaration (package:analyzer/src/generated/error_verifier.dart:1054:7)
#3      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7107:49)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#5      ExtensionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3923:14)
#6      RecursiveAstVisitor.visitExtensionDeclaration (package:analyzer/dart/ast/visitor.dart:847:10)
#7      ExtensionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3916:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#9      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2167:21)
#10     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:727:10)
#11     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:572:11)
#12     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#13     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:410:10)
#14     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:169:9)
#15     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#16     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:168:13)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:167:34)
#19     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:108:14)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:43)
#22     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1418:63)
#23     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#24     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
#25     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1215:33)
<asynchronous suspension>
#26     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
<asynchronous suspension>
#27     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#28     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#29     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#30     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#31     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#37     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#38     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#39     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#40     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#41     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#42     new Future.sync (dart:async/future.dart:224:31)
#43     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _runZoned (dart:async/zone.dart:1516:10)
#47     runZoned (dart:async/zone.dart:1463:12)
#48     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#49     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#50     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#51     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#52     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#53     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#54     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\anton.duzenko\AppData\Local\Temp\report1.txt.

**Comment by srawlins** [comment]
Thanks for reporting this issue! This was fixed with #41492.
