### ISSUE TITLE
dart2js js-interop crashes when trying to call function

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#37599]
Consider the following example:

**main.dart**:
```dart
import 'dart:js';

void main() {
  var m = allowInterop((x) => x + 1);
  context.callMethod('test', [m]);
}
```

**index.html**:
```html
<script>
  window.test = function(m) {
    console.log(m(1));
  }
</script>

<script src="main.dart.js"></script>
```

I expect this to print "2" to the console, instead I get this:

```
main.dart.js:502 Uncaught NoSuchMethodError: method not found: 'call'
Receiver: Instance of 'JavaScriptFunction'
Arguments: [1]
    at Object.wrapException (file:///usr/local/google/home/het/Projects/dart2js_example/main.dart.js:502:17)
    at JavaScriptObject.noSuchMethod$1 (file:///usr/local/google/home/het/Projects/dart2js_example/main.dart.js:2399:15)
    at Object.noSuchMethod$1$ (file:///usr/local/google/home/het/Projects/dart2js_example/main.dart.js:1814:42)
    at Object.Primitives_functionNoSuchMethod (file:///usr/local/google/home/het/Projects/dart2js_example/main.dart.js:382:16)
    at Object.Primitives__genericApplyFunction2 (file:///usr/local/google/home/het/Projects/dart2js_example/main.dart.js:441:18)
    at Object.Primitives_applyFunction (file:///usr/local/google/home/het/Projects/dart2js_example/main.dart.js:416:16)
    at Object.Function_apply (file:///usr/local/google/home/het/Projects/dart2js_example/main.dart.js:2022:16)
    at _callDartFunction (file:///usr/local/google/home/het/Projects/dart2js_example/main.dart.js:2224:31)
    at file:///usr/local/google/home/het/Projects/dart2js_example/main.dart.js:3589:18
    at window.test (file:///usr/local/google/home/het/Projects/dart2js_example/index.html:3:17)
```

I can't use `package:js` because this is for code that lives in a `dart:` library.

**Comment by hterkelsen** [comment]
@rakudrama @sigmundch is this a bug or am I using js-interop incorrectly?

**Comment by rakudrama** [comment]
The dependency tracking for several aspects of JS-interop are broken, so it only works if you do several JS-interop things to get all the parts. You could try adding a useless `@JS()` class.

But since you are inside a `dart:` library, you could use the pre-js-interop method `convertDartClosureToJS`, examples can be found in `dart:html`.

**Comment by natebosch** [comment]
`allowInterop` is _only_ for `package:js`.

**Comment by hterkelsen** [comment]
@natebosch thanks! Getting rid of the `allowInterop` usages fixed my issue
