### ISSUE TITLE
Flutter for web builds fail when const_update_2018 flag is turned on by default

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#37605]
The flutter for web engine builds fail with the following error when the const_update_2018 flag
is enabled. To reproduce checkout a flutter engine client and make local changes in
third_party/dart to enable const_update_2018 flag in the front end and try to build as follows
flutter/tools/gn --full-dart-sdk
ninja -C out/host_debug

This should trigger the error:
```
Command failed: /usr/local/google/home/asiva/workspace/flutter-roll/engine/src/t
hird_party/dart/tools/sdks/dart-sdk/bin/dart --packages=/usr/local/google/home/a
siva/workspace/flutter-roll/engine/src/third_party/dart/.packages --dfe=/usr/loc
al/google/home/asiva/workspace/flutter-roll/engine/src/third_party/dart/tools/sd
ks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /usr/local/google/home/as
iva/workspace/flutter-roll/engine/src/flutter/web_sdk/flutter_kernel_sdk.dart --
output=/usr/local/google/home/asiva/workspace/flutter-roll/engine/src/out/host_d
ebug/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --libraries=/usr/local/google/h
ome/asiva/workspace/flutter-roll/engine/src/out/host_debug/flutter_web_sdk/libra
ries.json
output: Unhandled exception:
Unsupported operation: Encountered an unevaluated constant: #C3 = eval const dar
t.core::bool::fromEnvironment(#C1, defaultValue: #C2)

#0      ProgramCompiler.visitUnevaluatedConstant (package:dev_compiler/src/kerne
l/compiler.dart:5379:7)
#1      UnevaluatedConstant.accept (package:kernel/ast.dart:5898:34)
#2      ProgramCompiler.visitConstantExpression (package:dev_compiler/src/kernel
/compiler.dart:3783:21)
#3      ConstantExpression.accept (package:kernel/ast.dart:3785:36)
#4      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compil
er.dart:3104:20)
#5      ProgramCompiler._visitInitializer (package:dev_compiler/src/kernel/compi
ler.dart:1564:11)
#6      ProgramCompiler._emitStaticFieldInitializer.<anonymous closure> (package
:dev_compiler/src/kernel/compiler.dart:2090:19)
#7      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.
dart:2098:25)
#8      ProgramCompiler._emitStaticFieldInitializer (package:dev_compiler/src/ke
rnel/compiler.dart:2088:22)
#9      ProgramCompiler._emitLazyFields (package:dev_compiler/src/kernel/compile
r.dart:2065:43)
#10     ProgramCompiler._emitTopLevelFields (package:dev_compiler/src/kernel/com
piler.dart:2051:21)
#11     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.d
art:394:7)
#12     Iterable.forEach (dart:core/iterable.dart:277:30)
#13     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dar
t:298:15)
#14     main (file:///usr/local/google/home/asiva/workspace/flutter-roll/engine/
src/flutter/web_sdk/flutter_kernel_sdk.dart:79:11)
<asynchronous suspension>
#15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart
:303:32)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:172:12)

[41/55] ACTION //third_party/dart/utils...t2js(//build/toolchain/linux:clang_x64
)
ninja: build stopped: subcommand failed.

```

**Comment by a-siva** [comment]
Change needed to trigger the failure
```
diff --git a/pkg/front_end/lib/src/api_prototype/experimental_flags.dart b/pkg/front_end/lib/src/api_prototype/experimental_flags.dart
index 5c2f97e7c9..e7df869ee6 100644
--- a/pkg/front_end/lib/src/api_prototype/experimental_flags.dart
+++ b/pkg/front_end/lib/src/api_prototype/experimental_flags.dart
@@ -44,7 +44,7 @@ ExperimentalFlag parseExperimentalFlag(String flag) {
 }
 
 const Map<ExperimentalFlag, bool> defaultExperimentalFlags = {
-  ExperimentalFlag.constantUpdate2018: false,
+  ExperimentalFlag.constantUpdate2018: true,
   ExperimentalFlag.controlFlowCollections: true,
   ExperimentalFlag.extensionMethods: false,
   ExperimentalFlag.nonNullable: false,

```

**Comment by nshahan** [comment]
I was able to repro this locally and have a fix locally that allows the build to complete. I will work on getting it landed ASAP.
