### ISSUE TITLE
Timeouts on new vm-dartkb-linux-release-x64-abi bot

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#37630]
The `vm-dartkb-linux-release-x64-abi` bot started to have infra failures caused by timeouts, see for example (vm-dartkb-linux-release-x64-abi/252)[https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-dartkb-linux-release-x64-abi/252].

This can be reproduced locally by:
```
% tools/gn.py '--mode=release' '--arch=x64' --bytecode
% ninja -C out/ReleaseX64 -j200 -l64 create_sdk_with_abi_versions
% mkdir -p out/ReleaseX64/test/logs
% python tools/test.py -t60 -m release -c dartkb --vm-options "--enable-interpreter --use-abi-version=6" lib_2/collection/hash_map_test
...
#1  0x00005555a931a7c5 dart::bin::EventHandlerImplementation::Poll(unsigned long)
#2  0x00005555a9362f05 dart::bin::ThreadStart(void*)
#3  0x00007face6908c73 start_thread
#4  0x00007face60b2def __clone
TID 121685:
#0  0x00007face690ecdc pthread_cond_wait@@GLIBC_2.3.2
#1  0x00005555a964d8a8 dart::Monitor::WaitMicros(long)
#2  0x00005555a98401ca dart::BackgroundCompiler::Run()
#3  0x00005555a96e5637 dart::ThreadPool::Worker::Loop()
#4  0x00005555a96e54d5 dart::ThreadPool::Worker::Main(unsigned long)
#5  0x00005555a964d199 dart::ThreadStart(void*)
#6  0x00007face6908c73 start_thread
#7  0x00007face60b2def __clone
TID 121686:
#0  0x00007face690ecdc pthread_cond_wait@@GLIBC_2.3.2
#1  0x00005555a964d8a8 dart::Monitor::WaitMicros(long)
#2  0x00005555a98401ca dart::BackgroundCompiler::Run()
#3  0x00005555a96e5637 dart::ThreadPool::Worker::Loop()
#4  0x00005555a96e54d5 dart::ThreadPool::Worker::Main(unsigned long)
#5  0x00005555a964d199 dart::ThreadStart(void*)
#6  0x00007face6908c73 start_thread
#7  0x00007face60b2def __clone
TID 121687:
#0  0x00007face690ecdc pthread_cond_wait@@GLIBC_2.3.2
#1  0x00005555a964d8a8 dart::Monitor::WaitMicros(long)
#2  0x00005555a98401ca dart::BackgroundCompiler::Run()
#3  0x00005555a96e5637 dart::ThreadPool::Worker::Loop()
#4  0x00005555a96e54d5 dart::ThreadPool::Worker::Main(unsigned long)
#5  0x00005555a964d199 dart::ThreadStart(void*)
#6  0x00007face6908c73 start_thread
#7  0x00007face60b2def __clone
TID 121688:
#0  0x00007face690ecdc pthread_cond_wait@@GLIBC_2.3.2
#1  0x00005555a964d8a8 dart::Monitor::WaitMicros(long)
#2  0x00005555a98401ca dart::BackgroundCompiler::Run()
#3  0x00005555a96e5637 dart::ThreadPool::Worker::Loop()
#4  0x00005555a96e54d5 dart::ThreadPool::Worker::Main(unsigned long)
#5  0x00005555a964d199 dart::ThreadStart(void*)
#6  0x00007face6908c73 start_thread
#7  0x00007face60b2def __clone

stderr:
kernel-service: Error: Unhandled exception:
NoSuchMethodError: Class 'bool' has no instance method 'cast'.
Receiver: false
Tried calling: cast<String>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:502:39)
<asynchronous suspension>
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Unhandled exception:
NoSuchMethodError: Class 'bool' has no instance method 'cast'.
Receiver: false
Tried calling: cast<String>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:502:39)
<asynchronous suspension>
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

--- Re-run this test:
python tools/test.py -m release -c dartkb -t 60 --vm-options "--enable-interpreter --use-abi-version=6" lib_2/collection/hash_map_test                                                                                                                       

Done dartkb-vm release_x64 lib_2/collection/hash_map_test: fail
```

So there seems to be some issue with starting the kernel service.

I'm not quite sure what this bot is testing.  @liamappelbe @a-siva maybe you know what's happening here?

**Comment by liamappelbe** [comment]
I think this was broken by [this change](https://dart-review.googlesource.com/c/sdk/+/108723) to the load request format, but that was 2 weeks ago. Looking at the dashboard, the ABI bot did turn purple when that CL was submitted, but I think at the time I just assumed the timeouts were due to having too many old ABI versions active (the bot runs a test suite for all the supported versions, and it's already running close to its time limit). So we just bumped the oldest supported version and the bot went green again.

The change to the request format is not backwards compatible, so I think the fix is to bump the ABI version and also the oldest supported version to the same number. This is what we should have done when the CL initially went in.

I'm also concerned that the bot isn't turning red when it should be. If you look at the test stdout for the times when it was green in between those 2 purple sections (eg [this](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8907000346533704976/+/steps/run_tests/0/stdout)), there are a lot of failures. Not sure why they're not reflected in the bot status.

**Comment by mkustermann** [comment]
So the [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8907000346533704976/+/steps/run_tests/0/stdout) says:
```
=== Running tests without an ABI version ===
python /b/s/w/ir/cache/builder/sdk/tools/test.py --compiler=dartkb --mode=release --write-results --write-logs --output_directory=/b/s/w/ir/cache/builder/sdk/tools/../out/ReleaseX64/test/logs --vm-options=--enable-interpreter lib_2

Test configuration:
    custom configuration(architecture: x64, compiler: dartkb, mode: release, runtime: vm, system: linux, vm-options: [--enable-interpreter], preview-dart-2)
Suites tested: lib_2

...
FAILED: dartkb-vm release_x64 lib_2/math/low_test
Expected: Pass
Actual: Crash
...

===
=== 7 tests failed
===

[05:48 | 100% | +  741 | -    7]
```

There are several issues here:
* The build is marked **green** (see [build](https://ci.chromium.org/b/8907000346533704976))
* There are several `tools/test.py` invocations inside that log, of which all seem to fail
* The way `tools/test.py` is invoked is via `--compiler=dartkb --mode=release`, which - to the best of my knowledge - uses status files (which are neither maintained nor tested on CQ/CI)

@whesse @athomas Could you work with @liamappelbe to get to the bottom of this?

**Comment by liamappelbe** [comment]
Actually that part of the log you've quoted is working ok. It's fine for some of the tests to fail. What matters is whether the failures are _different_ between no ABI version vs some ABI version. run_abi_tests.py diffs the results.json files for each test to produce an overall results.json file for the bot.

For example, in [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8907000346533704976/+/steps/run_tests/0/stdout) version 7 is working fine (it has exactly the same failures as no ABI version). The issue is that version 6 is failing, but [results.json is empty](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8907000346533704976/+/steps/test_results/0/logs/results.json/0) (it should contain a list of all the tests that have different results).

From my investigation so far, I've found that results.json is produced correctly when running locally (containing only the tests whose results differ between ABI versions). But it seems that on the bot it's always empty. @athomas helped design this system, so I'll talk to him about it when he's back from vacation.
