### ISSUE TITLE
dart2js crash on generic method definition

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37634]
On current bleeding edge, dart2js crashes on the small program below with the following error message:

```
Internal Error: Runtime type information not available for type_variable_local(foo.T) in (j:anonymous_closure_local(foo_closure), type_variable_local(call.X)) for j:closure_call(foo_closure.call).
void foo<S, T>() {
     ^
The compiler is broken.
```

See below for full crash trace.

```dart
import 'dart:core';

void foo<S, T>() {
  dynamic g = <X extends T>() => (null as X);
  X Function<X extends S>() f = g;

}
void main() {
  foo<int, int>();
}
```

```
leafp-macbookpro:tmp leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dart2js  ~/tmp/test2.dart
test2.dart:8:6:
Internal Error: Runtime type information not available for type_variable_local(foo.T) in (j:anonymous_closure_local(foo_closure), type_variable_local(call.X)) for j:closure_call(foo_closure.call).
void foo<S, T>() {
     ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.5.0-edge.b9ab8efca69018ef7e33ee42209f046c730eb04e), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Unhandled exception:
Assertion failure: Runtime type information not available for type_variable_local(foo.T) in (j:anonymous_closure_local(foo_closure), type_variable_local(call.X)) for j:closure_call(foo_closure.call).
#0      failedAt (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:49:3)
#1      LocalsHandler.readLocal (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/locals_handler.dart:326:11)
#2      TypeBuilder.addTypeVariableReference.readAsParameter (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:177:12)
#3      TypeBuilder.addTypeVariableReference (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:188:31)
#4      TypeBuilder.analyzeTypeArgument (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/type_builder.dart:262:14)
#5      KernelSsaGraphBuilder._assertIsType (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:5273:54)
#6      KernelSsaGraphBuilder._checkTypeVariableBounds (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1490:13)
#7      KernelSsaGraphBuilder._potentiallyAddFunctionParameterTypeChecks (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1437:7)
#8      KernelSsaGraphBuilder._openFunction (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1678:7)
#9      KernelSsaGraphBuilder._buildFunctionNode (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1277:5)
#10     KernelSsaGraphBuilder.build.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:485:13)
#11     CompilerDiagnosticReporter.withCurrentElement (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:751:15)
#12     KernelSsaGraphBuilder.build (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:437:21)
#13     KernelSsaBuilder.build.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/js_model/js_strategy.dart:515:22)
#14     CompilerTask.measure (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/common/tasks.dart:64:51)
#15     KernelSsaBuilder.build (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/js_model/js_strategy.dart:497:18)
#16     SsaBuilderTask.build (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/ssa.dart:287:21)
#17     SsaFunctionCompiler.compile (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/ssa/ssa.dart:78:29)
#18     OnDemandCodegenResults.getCodegenResults (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/common/codegen.dart:451:30)
#19     JsBackendStrategy.generateCode (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/js_model/js_strategy.dart:333:43)
#20     KernelCodegenWorkItem.run (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/js_model/js_strategy.dart:464:29)
#21     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:468:70)
#22     CompilerTask.measureSubtask (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#23     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:468:32)
#24     CompilerTask.measureSubtask (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#25     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:466:28)
#26     CompilerDiagnosticReporter.withCurrentElement (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:751:15)
#27     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:464:18)
#28     CodegenEnqueuer._forEach (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:257:12)
#29     CodegenEnqueuer.forEach (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:273:5)
#30     Compiler.emptyQueue.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:460:16)
#31     CompilerTask.measureSubtask (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#32     Compiler.emptyQueue (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:459:14)
#33     Compiler.processQueue.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:485:7)
#34     CompilerTask.measureSubtask (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#35     Compiler.processQueue (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:478:14)
#36     Compiler.runCodegenEnqueuer (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:391:5)
#37     Compiler.generateJavaScriptCode (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:282:9)
<asynchronous suspension>
#38     Compiler.compileFromKernel.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:441:9)
#39     CompilerTask.measureSubtask (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#40     Compiler.compileFromKernel (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:414:14)
#41     Compiler.runInternal (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:255:13)
<asynchronous suspension>
#42     Compiler.run.<anonymous closure>.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:210:38)
#43     new Future.sync (dart:async/future.dart:224:31)
#44     Compiler.run.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:210:20)
#45     CompilerTask.measureSubtask (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#46     Compiler.run (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/compiler.dart:207:41)
#47     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/compiler/lib/src/apiimpl.dart:91:22)
#48     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#49     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#50     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#51     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#52     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#53     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#54     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by sigmundch** [comment]
This is currently working in the latest version of dart2js, woohoo! Not sure when precisely it was fixed though.
