### ISSUE TITLE
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception UnimplementedError: Encoding "null"

### ISSUE THREAD

**Issue by FlutterForefront** [dart-lang/sdk#37641]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
UnimplementedError: Encoding "null"
#0      translateErrorToken (package:front_end/src/scanner/errors.dart:172:7)
#1      Scanner.tokenize (package:analyzer/src/dart/scanner/scanner.dart:171:9)
#2      _File._parse (package:analyzer/src/services/available_declarations.dart:1652:25)
#3      _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#4      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:642:10)
#5      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:508:7)
#6      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#8      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#9      new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#10     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#11     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#12     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#18     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#19     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#20     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#21     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#22     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#30     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#31     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#32     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#33     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#34     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\admin\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Apologies that we did not get a chance to look at this crash. Please re-open if you see this again with a recent version of Dart.
