### ISSUE TITLE
Issue check please

### ISSUE THREAD

**Issue by FlutterForefront** [dart-lang/sdk#37642]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.3.2-edge.e3edfd36b2aa7ff4e98fe541ef5666ef2e70d17e`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.3.2-edge.e3edfd36b2aa7ff4e98fe541ef5666ef2e70d17e, server version 1.26.1, error: Captured exception
UnimplementedError: Encoding "null"
#0      translateErrorToken (package:front_end/src/scanner/errors.dart:172:7)
#1      Scanner.tokenize (package:analyzer/src/dart/scanner/scanner.dart:171:9)
#2      _File._parse (package:analyzer/src/services/available_declarations.dart:1629:25)
#3      _File.refresh (package:analyzer/src/services/available_declarations.dart:1071:30)
#4      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:598:14)
#5      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:633:16)
#6      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:505:7)
#7      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:225:13)
<asynchronous suspension>
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2142:35)
<asynchronous suspension>
#9      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2092:5)
#10     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#11     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#12     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#13     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:532:21)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:617:12)
#19     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:530:7)
#20     Driver.start (package:analysis_server/src/server/driver.dart:435:7)
#21     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#22     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#23     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\admin\AppData\Local\Temp\report1.txt.

**Comment by srawlins** [comment]
Thanks for reporting this issue again. The original will suffice. Please follow along there if interested. https://github.com/dart-lang/sdk/issues/37641
