### ISSUE TITLE
Bad state: Element not contained in compilation unit: Never, analyzing the `sdk/pkg/analyzer` project, on a sdk built from head

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#37652]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.5728.98`
- `2.5.0-edge.bcfe26cba02191069f2190455393b74cb2f81b81`
- `IC-192.5728.98, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.bcfe26cba02191069f2190455393b74cb2f81b81, server version 1.27.1, error: Analysis failed: /Users/devoncarew/projects/dart-lang/sdk/pkg/analyzer/lib/src/error/codes.dart context: exception_20190726_152000_755
Bad state: Element not contained in compilation unit: Never
#0      getUnitElement (package:analyzer/src/dart/analysis/index.dart:28:3)
#1      _IndexAssembler._getElementInfo.<anonymous closure> (package:analyzer/src/dart/analysis/index.dart:346:44)
#2      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#3      _IndexAssembler._getElementInfo (package:analyzer/src/dart/analysis/index.dart:345:23)
#4      _IndexAssembler.addElementRelation (package:analyzer/src/dart/analysis/index.dart:235:32)
#5      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:499:15)
#6      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:451:7)
#7      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:758:5)
#8      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8963:49)
#9      CommentReferenceImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1969:18)
#10     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#11     GeneralizingAstVisitor.visitCommentReference (package:analyzer/dart/ast/visitor.dart:196:53)
#12     CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:1965:49)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7667:20)
#14     CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1904:17)
#15     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#16     GeneralizingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:193:35)
#17     CommentImpl.accept (package:analyzer/src/dart/ast/ast.dart:1900:49)
#18     AnnotatedNodeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:152:17)
#19     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4092:11)
#20     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#21     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#22     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#23     GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:183:43)
#24     GeneralizingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:284:53)
#25     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4088:49)
#26     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7667:20)
#27     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#28     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#29     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#30     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#31     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:202:7)
#32     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:427:7)
#33     GeneralizingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:181:7)
#34     _IndexContributor.visitClassDeclaration (package:analyzer/src/dart/analysis/index.dart:564:11)
#35     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#36     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7667:20)
#37     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#38     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#39     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:199:51)
#40     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#41     _IndexAssembler.assemble (package:analyzer/src/dart/analysis/index.dart:262:10)
#42     indexUnit (package:analyzer/src/dart/analysis/index.dart:35:32)
#43     AnalysisDriver._serializeResolvedUnit (package:analyzer/src/dart/analysis/driver.dart:1827:11)
#44     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1458:15)
#45     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#46     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1428:20)
#47     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1248:33)
<asynchronous suspension>
#48     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2188:24)
<asynchronous suspension>
#49     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2118:5)
#50     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#51     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#52     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#53     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:550:21)
#54     _rootRun (dart:async/zone.dart:1124:13)
#55     _CustomZone.run (dart:async/zone.dart:1021:19)
#56     _runZoned (dart:async/zone.dart:1516:10)
#57     runZoned (dart:async/zone.dart:1463:12)
#58     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:635:12)
#59     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:548:7)
#60     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:452:9)
#61     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#62     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:447:43)
#63     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#64     new Future.sync (dart:async/future.dart:224:31)
#65     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#66     _rootRun (dart:async/zone.dart:1124:13)
#67     _CustomZone.run (dart:async/zone.dart:1021:19)
#68     _runZoned (dart:async/zone.dart:1516:10)
#69     runZoned (dart:async/zone.dart:1463:12)
#70     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#71     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#72     Driver.start (package:analysis_server/src/server/driver.dart:447:21)
#73     main (file:///Users/devoncarew/projects/dart-lang/sdk/pkg/analysis_server/bin/server.dart:12:11)
#74     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#75     main (file:///Users/devoncarew/projects/dart-lang/sdk/pkg/analysis_server/bin/server.dart:10:10)
#76     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#77     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by lambdabaa** [comment]
I also just ran into this on analysis server startup.

**Comment by devoncarew** [comment]
Assumed fix from recent changes.

**Comment by devoncarew** [comment]
fixed in https://dart-review.googlesource.com/c/sdk/+/110943
