### ISSUE TITLE
Error compiling dartdevc module

### ISSUE THREAD

**Issue by yuxizhe** [dart-lang/sdk#37659]
Working on a Flutter Web project and got this exception.

```
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=G:\Users\yu\Documents\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web.examples.hello_world/components/appCard.ddc.js --source-map --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web.examples.hello_world/util/args.ddc.dill=packages/flutter_web.examples.hello_world/util/args --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/meta/meta.ddc.dill=packages/meta/meta --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/io.ddc.dill=packages/flutter_web/io --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/src/services/clipboard.ddc.dill=packages/flutter_web/src/services/clipboard --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/services.ddc.dill=packages/flutter_web/services --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/collection/collection.ddc.dill=packages/collection/collection --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/src/scheduler/binding.ddc.dill=packages/flutter_web/src/scheduler/binding --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/scheduler.ddc.dill=packages/flutter_web/scheduler --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/src/gestures/arena.ddc.dill=packages/flutter_web/src/gestures/arena --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/gestures.ddc.dill=packages/flutter_web/gestures --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/src/cupertino/action_sheet.ddc.dill=packages/flutter_web/src/cupertino/action_sheet --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino --summary=G:\Users\yu\AppData\Local\Temp\scratch_space5a961bea-b1e5-11e9-8041-d0abd53f799b\packages/flutter_web/material.ddc.dill=packages/flutter_web/material --packages=file:///G:/Users/yu/AppData/Local/Temp/kernel_builder_67f6ebfd-b1e5-11e9-8041-d0abd53f799b/.packages --module-name=packages/flutter_web.examples.hello_world/components/appCard --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:flutter_web.examples.hello_world/components/appCard.dart
    dart --version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"

Crash when compiling packages/flutter_web.examples.hello_world/components/appCard.dart,
at character offset 428:
NoSuchMethodError: The getter 'file' was called on null.
Receiver: null
Tried calling: file
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      BodyBuilder.throwNoSuchMethodError (package:front_end/src/fasta/kernel/body_builder.dart:1490:36)
#2      BodyBuilder.buildStaticInvocation (package:front_end/src/fasta/kernel/body_builder.dart:3347:13)
#3      BodyBuilder.buildConstructorInvocation (package:front_end/src/fasta/kernel/body_builder.dart:3666:24)
#4      KernelTypeUseGenerator.doInvocation (package:front_end/src/fasta/kernel/kernel_expression_generator.dart:1376:19)
#5      BodyBuilder.finishSend (package:front_end/src/fasta/kernel/body_builder.dart:1306:23)
#6      BodyBuilder.handleSend (package:front_end/src/fasta/kernel/body_builder.dart:1299:12)
#7      Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4940:14)
#8      Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#9      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#10     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#11     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#12     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#13     Parser.parseLiteralListSuffix (package:front_end/src/fasta/parser/parser.dart:4438:19)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4278:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#18     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5007:15)
#19     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4979:12)
#20     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4960:14)
#21     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4939:13)
#22     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#23     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#24     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#25     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#26     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#27     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5007:15)
#28     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4979:12)
#29     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4960:14)
#30     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4939:13)
#31     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#32     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#33     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#34     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#35     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#36     Parser.parseLiteralListSuffix (package:front_end/src/fasta/parser/parser.dart:4438:19)
#37     Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4627:12)
#38     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4283:14)
#39     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#40     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#41     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#42     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5007:15)
#43     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4979:12)
#44     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4960:14)
#45     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4939:13)
#46     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#47     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#48     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#49     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#50     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#51     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5007:15)
#52     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4979:12)
#53     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4960:14)
#54     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4939:13)
#55     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#56     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#57     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#58     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#59     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#60     Parser.parseReturnStatement (package:front_end/src/fasta/parser/parser.dart:3840:13)
#61     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3723:14)
#62     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3705:20)
#63     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3610:15)
#64     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:802:14)
#65     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:590:5)
#66     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3263:14)
#67     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3122:15)
#68     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2898:15)
#69     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1783:13)
#70     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1743:14)
#71     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#72     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#73     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#74     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:283:14)
<asynchronous suspension>
#75     Loader.buildBodies (package:front_end/src/fasta/loader.dart:186:15)
<asynchronous suspension>
#76     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:302:20)
<asynchronous suspension>
#77     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#78     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:300:12)
<asynchronous suspension>
#79     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:325:28)
<asynchronous suspension>
#80     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#81     new Future.sync (dart:async/future.dart:224:31)
#82     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#83     _rootRun (dart:async/zone.dart:1124:13)
#84     _CustomZone.run (dart:async/zone.dart:1021:19)
#85     _runZoned (dart:async/zone.dart:1516:10)
#86     runZoned (dart:async/zone.dart:1463:12)
#87     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#88     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:133:20)
<asynchronous suspension>
#89     _compile (package:dev_compiler/src/kernel/command.dart:285:64)
<asynchronous suspension>
#90     compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#91     compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#92     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#93     _rootRun (dart:async/zone.dart:1124:13)
#94     _CustomZone.run (dart:async/zone.dart:1021:19)
#95     _runZoned (dart:async/zone.dart:1516:10)
#96     runZoned (dart:async/zone.dart:1463:12)
#97     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#98     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#99     _rootRun (dart:async/zone.dart:1124:13)
#100    _CustomZone.run (dart:async/zone.dart:1021:19)
#101    _runZoned (dart:async/zone.dart:1516:10)
#102    runZoned (dart:async/zone.dart:1463:12)
#103    AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#104    main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#105    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#106    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:810:7)
#1      DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:590:5)
#2      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3263:14)
#3      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3122:15)
#4      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2898:15)
#5      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1783:13)
#6      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1743:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#8      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#9      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#10     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:283:14)
<asynchronous suspension>
#11     Loader.buildBodies (package:front_end/src/fasta/loader.dart:186:15)
<asynchronous suspension>
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:302:20)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#14     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:300:12)
<asynchronous suspension>
#15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:325:28)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#17     new Future.sync (dart:async/future.dart:224:31)
#18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#24     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:133:20)
<asynchronous suspension>
#25     _compile (package:dev_compiler/src/kernel/command.dart:285:64)
<asynchronous suspension>
#26     compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#27     compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#28     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#34     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#40     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```

**Comment by bakboem** [comment]
I have the same problem.
