### ISSUE TITLE
Parser crash: assert in literal

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#37674]
Repro: `n=<.["$assert`

```
NoSuchMethodError: The getter 'isSynthetic' was called on null.
Receiver: null
Tried calling: isSynthetic, #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      Parser.parseLiteralListSuffix (package:front_end/src/fasta/parser/parser.dart:4450:35)
#2      Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4622:12)
#3      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4291:14)
#4      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4180:12)
#5      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3968:13)
#6      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3940:13)
#7      ClassMemberParser.skipExpression (package:front_end/src/fasta/parser/class_member_parser.dart:42:23)
#8      ClassMemberParser.parseExpression (package:front_end/src/fasta/parser/class_member_parser.dart:24:12)
#9      Parser.parseFieldInitializerOpt (package:front_end/src/fasta/parser/parser.dart:2482:15)
#10     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2387:13)
#11     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2344:12)
#12     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:491:14)
#13     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#14     main (file:///home/mfairhurst/dart/dust/example/analyzer/bin/parser_fuzz.dart:13:8)
<asynchronous suspension>
#15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by MichaelRFairhurst** [comment]
@danrubel
