### ISSUE TITLE
co19_2/LibTest/isolate/ReceivePort/transform_A01_t01 failing on KBC bot

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37679]
Specific builder is `vm-dartkb-linux-debug-x64`, logs: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8906427615905157296/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0

```
/=========================================================================================================================================\
| dartkb-mixed-linux-debug-x64:co19_2/LibTest/isolate/ReceivePort/transform_A01_t01 failed again (RuntimeError -> Timeout, expected Pass) |
\=========================================================================================================================================/

--- Command "vm" (took 08:00.000072s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --no-background-compilation --enable_interpreter --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/isolate/ReceivePort/transform_A01_t01.dart

exit code:
null

diagnostics:
Process list including children: [30929]
Trying to capture stack trace for pid 30929
PID 30929 - process
TID 30929:
#0  0x00007f2fef854360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x000055f4b14ab7f4 dart::Monitor::WaitMicros(long)
#2  0x000055f4b138f57a dart::Isolate::WaitForOutstandingSpawns()
#3  0x000055f4b19b65f7 Dart_ShutdownIsolate
#4  0x000055f4b10ae4af dart::bin::ErrorExit(int, char const*, ...)
#5  0x000055f4b10b53a5 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
#6  0x000055f4b10b6382 dart::bin::main(int, char**)
#7  0x000055f4b10b7029 main
#8  0x00007f2feef8c830 __libc_start_main
#9  0x000055f4b10ae029 _start
TID 30930:
#0  0x00007f2fef073a13 epoll_wait
#1  0x000055f4b10b9505 dart::bin::EventHandlerImplementation::Poll(unsigned long)
#2  0x000055f4b1109375 dart::bin::ThreadStart(void*)
#3  0x00007f2fef84e6ba start_thread
#4  0x00007f2fef07341d __clone
TID 30935:
#0  0x00007f2fef854709 pthread_cond_timedwait@@GLIBC_2.3.2
#1  0x000055f4b14ab7cd dart::Monitor::WaitMicros(long)
#2  0x000055f4b1761c3d dart::SafepointHandler::SafepointThreads(dart::Thread*)
#3  0x000055f4b17506eb dart::HeapIterationScope::HeapIterationScope(dart::Thread*, bool)
#4  0x000055f4b1752ae3 dart::Heap::Verify(dart::MarkExpectation) const
#5  0x000055f4b12ef0a2 dart::Deserializer::ReadIsolateSnapshot(dart::ObjectStore*)
#6  0x000055f4b12f0018 dart::FullSnapshotReader::ReadIsolateSnapshot()
#7  0x000055f4b13286cc dart::Dart::InitializeIsolate(unsigned char const*, unsigned char const*, unsigned char const*, unsigned char const*, unsigned char const*, long, void*)
#8  0x000055f4b19b5e98 dart::CreateIsolate(dart::IsolateGroup*, char const*, void*, char**)
#9  0x000055f4b19b5a90 dart::CreateWithinExistingIsolateGroup(dart::IsolateGroup*, char const*, char**)
#10 0x000055f4b1270fe2 dart::SpawnIsolateTask::Run()
#11 0x000055f4b156e76c dart::ThreadPool::Worker::Loop()
#12 0x000055f4b156e254 dart::ThreadPool::Worker::Main(unsigned long)
#13 0x000055f4b14aaa15 dart::ThreadStart(void*)
#14 0x00007f2fef84e6ba start_thread
#15 0x00007f2fef07341d __clone



stderr:
Unhandled exception:
type '_AsBroadcastStream<dynamic>' is not a subtype of type 'Stream<int>' of 'stream'
#0      _StreamHandlerTransformer.bind (org-dartlang-sdk:///sdk/lib/async/stream_transformers.dart)
#1      Stream.transform (org-dartlang-sdk:///sdk/lib/async/stream.dart)
#2      check (file:///b/s/w/ir/tests/co19_2/src/LibTest/isolate/ReceivePort/transform_A01_t01.dart:28:17)
#3      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/isolate/ReceivePort/transform_A01_t01.dart:55:3)
#4      _startIsolate.<anonymous closure> (org-dartlang-sdk:///runtime/lib/isolate_patch.dart)
#5      _RawReceivePortImpl._handleMessage (org-dartlang-sdk:///runtime/lib/isolate_patch.dart)

--- Re-run this test:
python tools/test.py -n dartkb-mixed-linux-debug-x64 co19_2/LibTest/isolate/ReceivePort/transform_A01_t01
```

**Comment by alexmarkov** [comment]
The following tests also timed out with similar stack traces:

```
co19_2/LibTest/isolate/ReceivePort/firstWhere_A01_t01
co19_2/LibTest/isolate/ReceivePort/firstWhere_A02_t01
co19_2/LibTest/isolate/ReceivePort/transform_A01_t02
```

[log1](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8906403312478310208/+/steps/deflaking/0/steps/vm_interpreter_co19_tests/0/stdout)
[log2](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8906431987303886352/+/steps/deflaking/0/steps/vm_interpreter_co19_tests/0/stdout)

**Comment by alexmarkov** [comment]
Bytecode mode is removed from Dart VM.
