### ISSUE TITLE
Dart Analyzer throws when use mixin

### ISSUE THREAD

**Issue by MxSoul** [dart-lang/sdk#37677]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1440x900, 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: /Users/maxiao/Documents/Develop/FlutterWorkPlace/FlutterHighAvailable/lib/src/recorder/fps_recorder.dart context: exception_20190731_160638_439
NoSuchMethodError: The getter 'library' was called on null.
Receiver: null
Tried calling: library
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      ErrorVerifier._hasConcreteSuperMethod.<anonymous closure> (package:analyzer/src/generated/error_verifier.dart:6265:62)
#2      ListIterable.any (dart:_internal/iterable.dart:89:15)
#3      ErrorVerifier._hasConcreteSuperMethod (package:analyzer/src/generated/error_verifier.dart:6264:25)
#4      ErrorVerifier._checkForMustCallSuper (package:analyzer/src/generated/error_verifier.dart:4450:28)
#5      ErrorVerifier.visitMethodDeclaration (package:analyzer/src/generated/error_verifier.dart:1054:7)
#6      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7107:49)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#8      MixinDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7345:13)
#9      RecursiveAstVisitor.visitMixinDeclaration (package:analyzer/dart/ast/visitor.dart:1069:10)
#10     ErrorVerifier.visitMixinDeclaration (package:analyzer/src/generated/error_verifier.dart:1114:13)
#11     MixinDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7336:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#13     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2167:21)
#14     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:727:10)
#15     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:572:11)
#16     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#17     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:410:10)
#18     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:169:9)
#19     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#20     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:168:13)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:167:34)
#23     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:108:14)
#24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#25     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:43)
#26     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1418:63)
#27     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#28     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1215:33)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#41     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#42     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#43     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#45     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#46     new Future.sync (dart:async/future.dart:224:31)
#47     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _runZoned (dart:async/zone.dart:1516:10)
#51     runZoned (dart:async/zone.dart:1463:12)
#52     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#53     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#54     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#55     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#56     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#57     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#58     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/j8/ntxdmvn93c729d2g1z812h9h0000gp/T/report2.txt.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/111460
