### ISSUE TITLE
Occasionally blank exception text

### ISSUE THREAD

**Issue by ozzy1873** [dart-lang/sdk#37695]
Occasionally a ClientException is thrown with no error message, which makes debugging difficult. My app has an error handler which catches the exception with onError: (error, stackTrace). The stack trace is always there, but the error parameter is sometimes blank. I have not been able to replicate the error myself, but I get several error reports each day. How should this exception be handled?

```
The stack trace is always:
#0      IOClient.send (package:http/src/io_client.dart:65)
<asynchronous suspension>
dart-lang/http#1      RetryClient.send (package:http_retry/http_retry.dart:97)
<asynchronous suspension>
dart-lang/http#2      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169)
<asynchronous suspension>
dart-lang/http#3      BaseClient.post (package:http/src/base_client.dart:54)
...or...
dart-lang/http#3      BaseClient.get (package:http/src/base_client.dart:32)
```

**Comment by fpv999** [comment]
I have this error on production server endpoint (line numbers do not correspond to original, as I've added dozen of prints):
```
flutter: Exception occured:  stackTrace: #0      IOClient.send (package:http/src/io_client.dart:70:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:178:38)
<asynchronous suspension>
#2      BaseClient.get (package:http/src/base_client.dart:32:7)
```
...

as I cannot share URL on public, I may only say that it works via browser or postman/Insomnia.
Typical answer from server should be like this:

```
HTTP/1.1 200 OK
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Sat, 19 Oct 2019 23:46:55 GMT

```

Maybe this will help somehow?

**Comment by vualeks** [comment]
I'm also having this issue with api requests on an IIS server that has some MS .NET service. It's working fine on postman/android/ios, but not here. Could it be related to some non standard formatted response from the server, unexpected weird headers?

**Comment by robson-cervantes** [comment]
Any updates in this thread?

**Comment by argigentarna** [comment]
> I'm also having this issue with api requests on an IIS server that has some MS .NET service. It's working fine on postman/android/ios, but not here. Could it be related to some non standard formatted response from the server, unexpected weird headers?

Mee too, anyone can help?

**Comment by kokizzu** [comment]
same problem but always happened not occasional, tested with latest http package:
```
import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

void main(List<String> arguments) async {
  print('hit api start');
  hitApi();
  print('hit api end');
}

void hitApi() {
  http.post(
    // API_URL + API_Login,
    'https://xx.co.id:2020/xx/mobileapi/login',
    headers: {
      // "Accept": 'application/json',
      "Content-Type": "application/json",
      "x-api-key": "x.y.jbOfRigeCCFN2Lq0O2xVeIcTHNWpQBlI0ctmDiQBdBg",
    },
    body: json.encode({
        "nik": "on ff",
    }),
  ).then((response) => {
    print("status code");
    print(response.statusCode);
    print("status body");
    print(response.body);

  })
}
```
the error:
```
Unhandled exception:

#0      IOClient.send (package:http/src/io_client.dart:64:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171:38)
#2      BaseClient.post (package:http/src/base_client.dart:56:5)
#3      post.<anonymous closure> (package:http/http.dart:70:34)
#4      _withClient (package:http/http.dart:167:20)
#5      post (package:http/http.dart:70:3)
#6      hitApi (file:///tmp/test.dart:13:3)
#7      main (file:///tmp/test.dart:8:3)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by LYYLeo** [comment]
We are facing the same problem, it can always reproduce with HttpClient(dart:io packet) and our server(IIS with .net core service), and the endpoint is work fine on Browser, Postman, curl, Android, iOS native project, but just dart sdk client can't receive the response normally.

We can provide the endpoint for test, please help us to resolve this issue, thanks a lot.

### Target Endpoint

https://dev-contract-spi.epictech.com.tw/api/Company/GetCompanies

### Test Function

```dart
import 'dart:convert';
import 'dart:io';

void testHttpGet() async {
  var client = HttpClient();
  var uri = Uri.parse('https://dev-contract-spi.epictech.com.tw/api/Company/GetCompanies');
  try {
    print('Test started');
    var request = await client.getUrl(uri);
    print('Request prepared');
    var response = await request.close();
    print('Response received');
    var content = await response.transform(utf8.decoder).first;
    print('Http get success:\n$content');
  } catch(e, stacktrace) {
    print('Http exception:\nInstance of: ${e.runtimeType}\nMessage: ${e.message}\nUri: ${e.uri}');
    print('Http stacktrace:\n$stacktrace');
  }
}
```

### Test Log

```bash
Test started
Request prepared
Http exception:
Instance of: HttpException
Message: 
Uri: https://dev-contract-spi.epictech.com.tw/api/Company/GetCompanies
Http stacktrace:
```

### About this service

```bash
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: text/plain; charset=utf-8
< Server: Microsoft-IIS/10.0
< X-Powered-By: ASP.NET
```

### Dart SDK Info

```bash
$ dart --version
Dart VM version: 2.8.1 (stable) (Thu Apr 30 09:25:21 2020 +0200) on "macos_x64"
```

**Comment by changyuhao625** [comment]
> We are facing the same problem, it can always reproduce with HttpClient(dart:io packet) and our server(IIS with .net core service), and the endpoint is work fine on Browser, Postman, curl, Android, iOS native project, but just dart sdk client can't receive the response normally.
> 
> We can provide the endpoint for test, please help us to resolve this issue, thanks a lot.
> 
> ### Target Endpoint
> https://dev-contract-spi.epictech.com.tw/api/Company/GetCompanies
> 
> ### Test Function
> ```dart
> import 'dart:convert';
> import 'dart:io';
> 
> void testHttpGet() async {
>   var client = HttpClient();
>   var uri = Uri.parse('https://dev-contract-spi.epictech.com.tw/api/Company/GetCompanies');
>   try {
>     print('Test started');
>     var request = await client.getUrl(uri);
>     print('Request prepared');
>     var response = await request.close();
>     print('Response received');
>     var content = await response.transform(utf8.decoder).first;
>     print('Http get success:\n$content');
>   } catch(e, stacktrace) {
>     print('Http exception:\nInstance of: ${e.runtimeType}\nMessage: ${e.message}\nUri: ${e.uri}');
>     print('Http stacktrace:\n$stacktrace');
>   }
> }
> ```
> 
> ### Test Log
> ```shell
> Test started
> Request prepared
> Http exception:
> Instance of: HttpException
> Message: 
> Uri: https://dev-contract-spi.epictech.com.tw/api/Company/GetCompanies
> Http stacktrace:
> ```
> 
> ### About This Service
> ```shell
> < HTTP/1.1 200 OK
> < Transfer-Encoding: chunked
> < Content-Type: text/plain; charset=utf-8
> < Server: Microsoft-IIS/10.0
> < X-Powered-By: ASP.NET
> ```
> 
> ### Dart SDK Info
> ```shell
> $ dart --version
> Dart VM version: 2.8.1 (stable) (Thu Apr 30 09:25:21 2020 +0200) on "macos_x64"
> ```

Hi,
this issue is because of your response header "Transfer-Encoding:chunked",
Dart isn't support "Transfer-Encoding", you must give the content-length for your response header and "Transfer-Encoding" would be removed automatically.

**Comment by tyfoo1603** [comment]
@changyuhao625 Hi, I tried your solution. But the error still there.

**Test Log**
flutter: httpclient Error: HttpException: , uri = https://www.xxxxxxx.com/api/spacebar-widgets/1
flutter: Http exception:
Instance of: HttpException
Message:
Uri: https://www.xxxxxxx.com/api/spacebar-widgets/1
flutter: Http stacktrace:
flutter: StackTrace:


<img width="755" alt="Screenshot 2020-11-22 at 2 30 16 PM" src="https://user-images.githubusercontent.com/68138122/99896843-4147a980-2ccf-11eb-9090-a08facb6562e.png">

**Dart SDK Info**
Dart SDK version: 2.12.0-62.0.dev (dev) (Thu Nov 19 10:08:53 2020 -0800) on "macos_x64"

**Comment by su-khi** [comment]
I've the same issue. The issue started as soon as we switched from HTTP to HTTPS on IIS 10.0. The problem is not with the generic HTTPS since the other HTTPS end-points e.g. Azure/AWS works well.

**Comment by naiteon** [comment]
Problem is flutter http client does not fully support http 1.1, more specifically it does not support chunked responses. Solution for us was to add chunked_transfer_encoding off; in our webserver (nginx) in the php/fastcgi location in the config file.

**Comment by cminhtruong** [comment]
> I'm also having this issue with api requests on an IIS server that has some MS .NET service. It's working fine on postman/android/ios, but not here. Could it be related to some non standard formatted response from the server, unexpected weird headers?

I think it's just with IIS server. I've got the same issue by connecting via a Https post and I cannot go through it. Always received a HttpException with blank message but the ConnectionState is done.

**Comment by kuhnroyal** [comment]
I just had the same error captured in Sentry, blank HttpException without any message and so on. Not using IIS but the OP probably wasn't either since he said this happened occasionally.
Interestingly prior to the exception but after the request, there is memory pressure logged for the app (Flutter obviously).

So this is what happened for me:
1. request started
2. memory pressure from OS
3. blank HttpException

**Comment by yakeer** [comment]
Same here. Happens on iOS simulator only, android emulator working fine. Device iOS working fine as well.
Will appreciate some help on this.

**Comment by naiteon** [comment]
I also was using VSCode on my Mac. Solved this. The flutter http client DOES NOT SUPPORT http 1.1 fully. Http 1.1 determines that CHUCKED responses are always permissive. Most webservers nowadays when used with as proxy for other applications such as php thru fast cgi or other backend engines USUALLY SEND RESPONSES AS CHUNKED. Simply disable chunked responses from your webserver. Since ours is a nginx we added chunked_transfer_encoding off; in our webserver and the problem was gone for good.

**Comment by FabioPaganoAPSystem** [comment]
In my case (sometimes appeared error "HttpException: Connection closed before full header was received" instead of blank) the call was to an https address using Microsoft Internet Information Services as backend, in the SSL settings of the website in IIS i had mistakenly set "Client certificates: Accept" instead of "Client certificates: Ignore", setting "Ignore" solved the problem.

**Comment by FabioPagano** [comment]
In my case (sometimes appeared error "HttpException: Connection closed before full header was received" instead of blank) the call was to an https address using Microsoft Internet Information Services as backend, in the SSL settings of the website in IIS i had mistakenly set "Client certificates: Accept" instead of "Client certificates: Ignore", setting "Ignore" solved the problem.

**Comment by ianbeemsterboerr** [comment]
I am running in to the same issue where I have a Azure App Service hosted backend (as far as I know this isn't IIS, since I am hosting in a linux environment with Kestrel enabled. I see a very clear difference between having Client Certificate Mode in the App Service set to Require/Allow and Ignore. If I ignore the client certificate I get a response in my Flutter app. If I Require or Allow the certificate it stops working and I get a empty HttpException with no message. I can't ignore the client certificate because that's my way of authenticating users. Does anyone know of a workaround for this issue?

**Comment by meisme-dev** [comment]
I have this issue trying to use Microsoft's Xbox Live API
