### ISSUE TITLE
Cannot serialize an instance of GenericFunctionTypeImpl

### ISSUE THREAD

**Issue by hpoit** [dart-lang/sdk#37703]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-192.5728.87`
- `2.0.0-dev.3.0`
- `WS-192.5728.87, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 1280x800`

## Exception
```
Dart analysis server, SDK version 2.0.0-dev.3.0, server version 1.18.4, error: Analysis failed: /Users/kevinliu/WebstormProjects/icasaa__AngularDart_Firebase/web/main.dart
Invalid argument(s): Cannot serialize an instance of GenericFunctionTypeImpl
#0      AbstractConstExprSerializer.serializeTypeName (package:analyzer/src/summary/summarize_const_expr.dart:211)
#1      AbstractConstExprSerializer._serializeMapLiteral (package:analyzer/src/summary/summarize_const_expr.dart:571)
#2      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:359)
#3      AbstractConstExprSerializer.serialize (package:analyzer/src/summary/summarize_const_expr.dart:139)
#4      _SummarizeAstVisitor.serializeConstExpr (package:analyzer/src/summary/summarize_ast.dart:551)
#5      _SummarizeAstVisitor.serializeFunctionBody (package:analyzer/src/summary/summarize_ast.dart:715)
#6      _SummarizeAstVisitor.serializeInitializerFunction (package:analyzer/src/summary/summarize_ast.dart:784)
#7      _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:984)
#8      _SummarizeAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/src/summary/summarize_ast.dart:1354)
#9      TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10344)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8003)
#11     _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:519)
#12     serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22)
#13     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:431)
#14     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#15     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:430)
#16     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:768)
#17     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:554)
#18     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:492)
#19     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:768)
#20     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:554)
#21     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:492)
#22     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:768)
#23     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:554)
#24     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:492)
#25     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:768)
#26     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:554)
#27     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:492)
#28     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:768)
#29     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:554)
#30     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:492)
#31     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:768)
#32     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:554)
#33     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:492)
#34     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:768)
#35     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:554)
#36     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:497)
#37     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:768)
#38     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:554)
#39     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:492)
#40     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:729)
#41     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1074)
<asynchronous suspension>
#42     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:960)
<asynchronous suspension>
#43     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1717)
<asynchronous suspension>
#44     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1660)
#45     new AnalysisServer (package:analysis_server/src/analysis_server.dart:378)
#46     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#47     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#48     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:430)
#49     _rootRun (dart:async/zone.dart:1124)
#50     _CustomZone.run (dart:async/zone.dart:1021)
#51     runZoned (dart:async/zone.dart:1499)
#52     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:470)
#53     Driver.start (package:analysis_server/src/server/driver.dart:429)
#54     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#55     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

For additional log information, please append the contents of
file:///private/var/folders/d2/fvp3pdj96h55gg8wsc99vmrc0000gn/T/report.txt.

**Comment by a-siva** [comment]
Bumping priority to P1 as it is a crash and has been seen multiple times.
