### ISSUE TITLE
I just get it after upgrading flutter plugin to 38.1

### ISSUE THREAD

**Issue by Jay-Tillu** [dart-lang/sdk#37730]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, FATAL error: FileSystemException: Directory listing failed, path = 'C:\Users\devel\AppData\Local\.dartServer\.analysis-driver\15\*' (OS Error: The file or directory is corrupted and unreadable.
, errno = 1392)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:249:5)
#2      EvictingFileByteStore._cleanUpFolder (package:analyzer/src/dart/analysis/file_byte_store.dart:114:34)
#3      EvictingFileByteStore._cacheCleanUpFunction.<anonymous closure> (package:analyzer/src/dart/analysis/file_byte_store.dart:101:9)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#7      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#8      _StreamController._add (dart:async/stream_controller.dart:640:7)
#9      _StreamController.add (dart:async/stream_controller.dart:586:5)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\devel\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Thanks for reporting this issue! This has been previously reported at https://github.com/dart-lang/sdk/issues/37059; please follow along there.
