### ISSUE TITLE
Failed to handle completion domain request: {method: completion.getSuggestionDetails}

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#37734]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Writing a small FFI sample. Code at the time (mid-typing):
```
import 'dart:ffi' as ffi;

typedef enableraw_func = ffi.Vod


final termlib = ffi.DynamicLibrary.open('termlib');
```

### Versions

- Flutter SDK 1.8.2-pre.129
- Visual Studio Code 1.36.1
- Dart Code 3.3.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
c:\git\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.3.0
```

### Exception

Failed to handle completion domain request: {id: 1888, method: completion.getSuggestionDetails, params: {file: C:\git\kilo\termlib\termlib.dart, id: 81, label: Void, offset: 58}, clientRequestTime: 1564956125086}

```text
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<void>(Instance of 'SyntacticScopeNamesCollector')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      SyntacticScopeNamesCollector.visitGenericTypeAlias (package:analyzer_plugin/src/utilities/change_builder/dart/syntactic_scope.dart:220:23)
#2      GenericTypeAliasImpl.accept (package:analyzer/src/dart/ast/ast.dart:5537:20)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#4      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#5      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#6      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#7      importLibraryElementImpl (package:analyzer_plugin/src/utilities/change_builder/dart/import_library_element.dart:58:25)
#8      DartFileEditBuilderImpl.importLibraryElement (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1267:19)
#9      CompletionDomainHandler.getSuggestionDetails.<anonymous closure> (package:analysis_server/src/domain_completion.dart:235:32)
#10     DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:56:20)
#11     ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#12     DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:53:18)
#13     CompletionDomainHandler.getSuggestionDetails (package:analysis_server/src/domain_completion.dart:234:23)
<asynchronous suspension>
#14     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:279:9)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#20     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1500:12)
#27     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#28     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#29     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#30     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#31     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#40     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#41     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#42     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#49     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#50     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#51     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#52     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#53     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#54     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#55     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#56     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#57     _rootRunUnary (dart:async/zone.dart:1132:38)
#58     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#62     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#63     _StreamController._add (dart:async/stream_controller.dart:640:7)
#64     _StreamController.add (dart:async/stream_controller.dart:586:5)
#65     _Socket._onData (dart:io-patch/socket_patch.dart:1787:41)
#66     _rootRunUnary (dart:async/zone.dart:1136:13)
#67     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#68     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#69     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#70     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#71     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#72     _StreamController._add (dart:async/stream_controller.dart:640:7)
#73     _StreamController.add (dart:async/stream_controller.dart:586:5)
#74     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1335:33)
#75     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:856:14)
#76     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#77     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#78     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#79     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "C:\\git\\kilo",
        "explicitFileCount": 2,
        "implicitFileCount": 181,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by stereotype441** [comment]
The code that was crashing here was removed in 4f8f592b51990612335b66dccd5269aab09b96dd, so this crash should not be possible anymore.
