### ISSUE TITLE
FunctionTypedFormalParameter with null identifier

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#37733]
@MichaelRFairhurst used fuzz tester and found the following code that crashes Analyzer (in both summary1 and summary2).

```dart
typedef K=Function(<>($
```

This causes the parser to produce `FunctionTypedFormalParameter` with `null` identifier.
![image](https://user-images.githubusercontent.com/384794/62429630-e0edbc80-b6c5-11e9-88af-dd32d656a110.png)

This causes NPE later, but I think should be fixed on the parser level to not produce invalid AST in the first place.

**Comment by bwilkerson** [comment]
What AST structure do you think we should be producing here?

**Comment by scheglov** [comment]
I don't know.

On top-level code `<>($` produces `#synthetic_function_1($) {}`. So, it generates a synthetic name. In other places we insert empty `SimpleIdentifier` to recover.

OTOH, `<T>($` is parsed as `T; #synthetic_function_2($) {}`, where `T` is a top-level variable declaration, and it seems that we OK with dropping invalid tokens `<` and `>`.

So, it could be either using an empty identifier for this function type formal parameter, or dropping some tokens. I don't really have a preference, I just want the resulting AST to be the spec conformant, and have nodes where the spec says that there definitely must be a node.

**Comment by bwilkerson** [comment]
> ... I just want the resulting AST to be the spec conformant, and have nodes where the spec says that there definitely must be a node.

I totally agree. The question was merely attempting to determine which AST we want to build in this case.

I also agree that the question is what to do with `<>($`. If we recover (on finding the `<`) by finishing the type alias as `typedef K=Function();`, then yes, we're looking at the bad code as a top-level declaration. Should we drop the `<>`, or should we interpret that as a poorly formed type, something like `_s_<_s_>` (where `_s_` is some synthetic identifier)? Or perhaps we should just drop all of the tokens until we can find something that can validly start a top-level declaration.

I don't have a strong opinion in this case because the text is something that users are unlikely to type during normal development.

**Comment by MichaelRFairhurst** [comment]
Notably, I don't think the $ is important to the fuzz case. It looks like
it isn't required for the crash and my simplifier didn't remove it?

And this also crashes for what I think is the same reason:

typedef T=Function<R>((

So it can be hard to guage likilhood by one example. @scheglov, did you get
far enough in your research to identify what exactly is required to get
into this broken state?

>

**Comment by MichaelRFairhurst** [comment]
This also fails:

typedef K=Function(<a>());

**Comment by scheglov** [comment]
I have not tried to simplify this code.
Looks like you just did it :-)

**Comment by MichaelRFairhurst** [comment]
Ha sorry.

To clarify, the tools can only simplify in terms of removing characters (I
tried an approach where it reduced coverage, but that led to strange
results). This creates two problems when we try to guess how likely a crash
is:

1. sometimes removing characters creates code that is less likely for users
to type. The repro doesn't show what users must _not_ type to crash, it
only shows what users _must_ type to get a crash. So the code may look like
nobody would ever write it, but that's just because it wasn't written by a
human, not because nobody will ever trigger the crash.

2. the repro will only be one example. Where that one example may look
contrived, sometimes it is just a very unlikely example. For instance, the
parser issue that Dan fixed was `n=<.["\$assert`. However, once Dan went to
fix the bug he saw that it also would occur for any expression <.[], or
<.[", etc.

I did the manual work of making the repro more human to undo any bias in
#1, and I was lucky that the fuzzer found a second example to reduce bias
in #2. However, we will only really know the likelihood of the repro once a
human does the work of figuring out #2 :(

I don't want to push any priorities on anyone, just was wondering
Konstantin if you'd already used your supreme developer skills to do so :)

**Comment by MichaelRFairhurst** [comment]
In other news if anyone is willing to advise or brainstorm solutions for
problems #1 and #2, I'm all ears :)

In theory I'd love if I could add an "exemplify" subcommand to dust that
spits out different repros that are distinct by some definition, and can
find them in a reasonable amount of time. I don't know how feasible this
is. I think a good result would maybe be worthy of publishing as a paper :)

>

**Comment by scheglov** [comment]
The AST that is produced with the fix also does not satisfy the spec.
![image](https://user-images.githubusercontent.com/384794/63391995-acd2f680-c369-11e9-80bd-e0e8c453129c.png)


See `19.1 Static Types`, about `<functionTypeTail>`.
Only `typedIdentifier` or `type` can be used in `parameterTypeList`.
You cannot use `functionFormalParameter` or `fieldFormalParameter`.
![image](https://user-images.githubusercontent.com/384794/63391847-fcfd8900-c368-11e9-91b6-8b273141109c.png)

These other kinds of parameters described in `9.2.1 Required Formals`.
But they cannot be used for `Function`.
![image](https://user-images.githubusercontent.com/384794/63391951-72695980-c369-11e9-82eb-4f0f7196bc93.png)

**Comment by scheglov** [comment]
Similarly, unexpected `FieldFormalParameter` in `FunctionTypeAlias` causes an exception.

```dart
typedef F(this.a);
```

results in:
```
  UnimplementedError: (FieldFormalParameterImpl) this.a
  #0      _TypeCollector.visitParameter (package:analyzer/src/summary2/simply_bounded.dart:311:7)
  #1      _TypeCollector.visitParameters (package:analyzer/src/summary2/simply_bounded.dart:317:7)
  #2      SimplyBoundedDependencyWalker._collectTypedefRhsTypes (package:analyzer/src/summary2/simply_bounded.dart:132:17)
  #3      SimplyBoundedDependencyWalker.getNode (package:analyzer/src/summary2/simply_bounded.dart:94:11)
  #4      computeSimplyBounded (package:analyzer/src/summary2/simply_bounded.dart:26:27)
  #5      Linker._resolveTypes (package:analyzer/src/summary2/link.dart:254:5)
  #6      Linker._buildOutlines (package:analyzer/src/summary2/link.dart:99:5)
  #7      Linker.link (package:analyzer/src/summary2/link.dart:83:5)
  #8      link (package:analyzer/src/summary2/link.dart:35:10)
```

Although in this case the spec does not limit what kinds of parameters are allowed in type aliases. So, formally the parser is correct. Hm... Maybe summary2 should tolerate it?

**Comment by bwilkerson** [comment]
My opinion is that summary2 should supports the AST structure that analyzer defines (which is a superset of the Dart grammar). If the AST supports field formal parameters inside function type aliases (and I suspect it does), and if the `AstBuilder` will actually produce that structure, then yes, summary2 should also support it.

**Comment by scheglov** [comment]
Support for FunctionTypedFormalParameter in GenericFunctionType.
https://dart-review.googlesource.com/c/sdk/+/114120
