### ISSUE TITLE
CreateProcessW failed 193: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by blasten** [dart-lang/sdk#37751]
According to the [documentation](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw#parameters) for `CreateProcessW`:  " If you are using a long file name that contains a space, use quoted strings to indicate where the file name ends and the arguments begin; otherwise, the file name is ambiguous."

However, it looks like the [current implementation](https://github.com/dart-lang/sdk/blob/971f4845d75269a9c8308d59d3c21d1522999d88/runtime/bin/process_win.cc#L436) for starting processes doesn't add the quotes.

As a result, if you try to run the program `C:\Program Files\foo.exe` and there is another file named  `C:\Program`, Windows resolves the path as `C:\Program`, but since it isn't a valid Win32 program, then we get the error: "CreateProcessW failed 193: %1 is not a valid Win32 application".

Causes: https://github.com/flutter/flutter/issues/19359

cc @zanderso

**Comment by zanderso** [comment]
I suspect the argument escapes [here](https://github.com/dart-lang/sdk/blob/master/runtime/bin/process_patch.dart#L250) performed by `_windowsArgumentEscape` should apply not only to the arguments, but also to the executable path (`_path`).

/cc @sortie

**Comment by liudonghua123** [comment]
I have the similar problem.

```shell
D:\code\dart\dart-pad-docker\dart-services>grind deploy
grinder running setup-flutter-sdk sdk-init update-docker-version generate-protos analyze build-project-templates build-storage-artifacts test fuzz validate-storage-artifacts deploy

setup-flutter-sdk
Flutter SDK configuration: {flutter_sdk: {version: 2.0.1}}

git checkout master
Your branch is up to date with 'origin/master'.
Previous HEAD position was c5a4b4029 Store symlinks in package archive (#77184) (#77194)
Switched to branch 'master'
git fetch --tags
git checkout 2.0.1
Note: checking out '2.0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c5a4b4029 Store symlinks in package archive (#77184) (#77194)
  D:\code\dart\dart-pad-docker\dart-services\flutter-sdk\bin\flutter doctor
CreateProcessW failed 193

ProcessException: %1 is not a valid Win32 application.

  Command: D:\code\dart\dart-pad-docker\dart-services\flutter-sdk\bin\flutter doctor
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      runWithLogging (file:///D:/code/dart/dart-pad-docker/dart-services/tool/grind.dart:343:30)
#3      setupFlutterSdk (file:///D:/code/dart/dart-pad-docker/dart-services/tool/grind.dart:271:9)
<asynchronous suspension>
#4      Grinder._invokeTask.<anon> (package:grinder/src/grinder.dart)
<asynchronous suspension>

D:\code\dart\dart-pad-docker\dart-services>
D:\code\dart\dart-pad-docker\dart-services>where flutter
D:\apps\flutter\bin\flutter
D:\apps\flutter\bin\flutter.bat

D:\code\dart\dart-pad-docker\dart-services>D:\apps\flutter\bin\flutter -h
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]
D:\code\dart\dart-pad-docker\dart-services>D:\apps\flutter\bin\flutter.bat -h
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]
D:\code\dart\dart-pad-docker\dart-services>
```

**Comment by Tokenyet** [comment]
I'm wondering If `run` designed to run `executable`? According to this change, this will break the pure commands. example:

```
// Not working
processManager.run(['tasklist | findstr svchost.exe'], runInShell: true);
// Neither(note)
processManager.run(['', 'tasklist | findstr svchost.exe'], runInShell: true);
```

So there is no possible to use this kind of command, only for pure `Process`.
```
// Working
Process.run('tasklist | findstr svchost.exe', [], runInShell: true);
// Not working (note)
Process.run('', ['tasklist | findstr svchost.exe'], runInShell: true); 
```

Note: After viewing source code, I want to bypass this change, but It's not possible, `Process.run`  with empty executable will give a double quote with empty space, see below:

```
'" "tasklist' is not recognized as an internal or external command,
```

So I personally don't like the change, this lost the command feature in Windows.
