### ISSUE TITLE
error while running "flutter pub run build_runner watch"

### ISSUE THREAD

**Issue by ArchangelXu** [dart-lang/sdk#37768]
* Dart SDK Version (`dart --version`)
2.4.0
* Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOSX
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Chrome

console logs:
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/Users/xumingke/Library/flutter/bin/cache/dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/charcode/html_entity.ddc.js --source-map --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --packages=file:///var/folders/_q/cdbqm6395k904qt5gbl7pd8h0000gn/T/kernel_builder_RhENZZ/.packages --module-name=packages/charcode/html_entity --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:charcode/html_entity.dart
    dart --version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "macos_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:391:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:233:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:246:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

[WARNING] build_web_compilers:entrypoint on web/main.dart:
Unable to read charcode|lib/html_entity.ddc.js, check your console or the `.dart_tool/build/generated/charcode/lib/html_entity.ddc.js.errors` log file.
[SEVERE] build_web_compilers:ddc on package:charcode/charcode.ddc.module:
Error compiling dartdevc module:charcode|lib/charcode.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/Users/xumingke/Library/flutter/bin/cache/dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/charcode/charcode.ddc.js --source-map --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --packages=file:///var/folders/_q/cdbqm6395k904qt5gbl7pd8h0000gn/T/kernel_builder_DKHaN0/.packages --module-name=packages/charcode/charcode --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:charcode/charcode.dart
    dart --version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "macos_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:391:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:233:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:246:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

[WARNING] build_web_compilers:entrypoint on web/main.dart:
Unable to read charcode|lib/charcode.ddc.js, check your console or the `.dart_tool/build/generated/charcode/lib/charcode.ddc.js.errors` log file.
[SEVERE] build_web_compilers:ddc on package:source_span/source_span.ddc.module:
Error compiling dartdevc module:source_span|lib/source_span.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/Users/xumingke/Library/flutter/bin/cache/dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/source_span/source_span.ddc.js --source-map --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=packages/path/path.ddc.dill=packages/path/path --packages=file:///var/folders/_q/cdbqm6395k904qt5gbl7pd8h0000gn/T/kernel_builder_2whEfd/.packages --module-name=packages/source_span/source_span --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:source_span/src/colors.dart package:source_span/src/location_mixin.dart package:source_span/src/span.dart package:source_span/src/span_with_context.dart package:source_span/src/highlighter.dart package:source_span/src/span_exception.dart package:source_span/src/file.dart package:source_span/src/location.dart package:source_span/src/utils.dart package:source_span/source_span.dart package:source_span/src/span_mixin.dart
    dart --version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "macos_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_bin

**Comment by ArchangelXu** [comment]
Solved... 
It was a case-sensitive matter: I created a User.dart file to declear a User class. But inside the file I write "part 'user.g.dart';" not "part 'User.g.dart';"......
After changing that line, everything is fine.
