### ISSUE TITLE
[vm/ffi] type 'Int8List' is not a subtype of type 'TypedData'

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37761]
This failure happens on the KBC bots:

```
/===============================================================================================================\
| dartkb-compile-linux-release-x64:ffi/external_typed_data_test is new and failed (RuntimeError, expected Pass) |
\===============================================================================================================/

--- Command "vm" (took 437ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --use_bytecode_compiler --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/ffi/external_typed_data_test.dart

exit code:
255

stderr:
Unhandled exception:
type 'Int8List' is not a subtype of type 'TypedData'
#0      Pointer.asExternalTypedData (org-dartlang-sdk:///runtime/lib/ffi_patch.dart)
#1      testInt8Load (file:///b/s/w/ir/tests/ffi/external_typed_data_test.dart:45:23)
#2      main (file:///b/s/w/ir/tests/ffi/external_typed_data_test.dart:12:3)
#3      _startIsolate.<anonymous closure> (org-dartlang-sdk:///runtime/lib/isolate_patch.dart)
#4      _RawReceivePortImpl._handleMessage (org-dartlang-sdk:///runtime/lib/isolate_patch.dart)

--- Re-run this test:
python tools/test.py -n dartkb-compile-linux-release-x64 ffi/external_typed_data_test
```

**Comment by sjindel-google** [comment]
This also shows up as a crash in debug mode:

```

/======================================================================================================\
| dartkb-compile-linux-debug-x64:ffi/external_typed_data_test is new and failed (Crash, expected Pass) |
\======================================================================================================/

--- Command "vm" (took 03.000812s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --no-background-compilation --use_bytecode_compiler --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/ffi/external_typed_data_test.dart

exit code:
-6

stderr:
../../runtime/vm/object.cc: 2638: error: expected: is_declaration_loaded()
version=2.5.0-edge.ddd83d256f2423ad4218bf5fee154977ff1e2e55 (Tue Aug 6 15:38:27 2019 +0000) on "linux_x64"
thread=10919, isolate=main(0x56033a6e8100)
  pc 0x000056033969796c fp 0x00007f8be3ebe230 dart::Profiler::DumpStackTrace(void*)
  pc 0x00005603392b4bb2 fp 0x00007f8be3ebe310 dart::Assert::Fail(char const*, ...)
  pc 0x00005603395d9f1f fp 0x00007f8be3ebe380 dart::Class::ComputeNumTypeArguments() const
  pc 0x00005603395da03d fp 0x00007f8be3ebe3b0 dart::Class::NumTypeArguments() const
  pc 0x00005603395e22a2 fp 0x00007f8be3ebe430 dart::Instance::IsInstanceOf(dart::AbstractType const&, dart::TypeArguments const&, dart::TypeArguments const&) const
  pc 0x0000560339701288 fp 0x00007f8be3ebe610 dart::DRT_TypeCheck(dart::NativeArguments)
  pc 0x00007f8be3ec1197 fp 0x00007f8be3ebe658 Unknown symbol
  pc 0x00007f8be0b2ca57 fp 0x00007f8be3ebe6d8 Unknown symbol
  pc 0x00007f8be0b2c0ed fp 0x00007f8be3ebe710 Unknown symbol
  pc 0x00007f8be0b2be34 fp 0x00007f8be3ebe730 Unknown symbol
  pc 0x00007f8be0b2bd67 fp 0x00007f8be3ebe770 Unknown symbol
  pc 0x00007f8be0b2bb77 fp 0x00007f8be3ebe7a8 Unknown symbol
  pc 0x00007f8be0b2ae23 fp 0x00007f8be3ebe7e8 Unknown symbol
  pc 0x00007f8be0b0a0ba fp 0x00007f8be3ebe828 Unknown symbol
  pc 0x00007f8be0b2ab76 fp 0x00007f8be3ebe858 Unknown symbol
  pc 0x00007f8be3ec173a fp 0x00007f8be3ebe8c8 Unknown symbol
  pc 0x0000560339516fe5 fp 0x00007f8be3ebe970 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  pc 0x000056033951a2d1 fp 0x00007f8be3ebe9e0 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  pc 0x000056033956cd39 fp 0x00007f8be3ebebe0 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)
  pc 0x00005603395afd9e fp 0x00007f8be3ebec70 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x00005603395b0ce6 fp 0x00007f8be3ebecf0 dart::MessageHandler::TaskCallback()
  pc 0x00005603397554cc fp 0x00007f8be3ebed40 dart::ThreadPool::Worker::Loop()
  pc 0x0000560339754fb4 fp 0x00007f8be3ebed90 dart::ThreadPool::Worker::Main(unsigned long)
  pc 0x00005603396917b5 fp 0x00007f8be3ebeed0 out/DebugX64/dart+0x1b0a7b5
-- End of DumpStackTrace
```

**Comment by sjindel-google** [comment]
Turned out to be a missing class finalization check.
