### ISSUE TITLE
DDC breaks on fields defined by extensions

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#37760]
The DDC compiler is making the assumption that fields can only be defined in classes, which is no longer true with extensions.

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8905867976936903264/+/steps/test_results/0/logs/unapproved_new_test_failures__logs_/0

```
type 'ExtensionElementImpl' is not a subtype of type 'ClassElement' in type cast
#0      CodeGenerator._emitSetField (package:dev_compiler/src/analyzer/code_generator.dart:3589:44)
#1      CodeGenerator._emitSet (package:dev_compiler/src/analyzer/code_generator.dart:3501:16)
#2      CodeGenerator.visitAssignmentExpression (package:dev_compiler/src/analyzer/code_generator.dart:3409:52)
#3      AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:747:49)
#4      CodeGenerator._visitExpression (package:dev_compiler/src/analyzer/code_generator.dart:5816:18)
#5      CodeGenerator._emitArgumentList (package:dev_compiler/src/analyzer/code_generator.dart:4068:18)
#6      CodeGenerator._emitFunctionCall (package:dev_compiler/src/analyzer/code_generator.dart:3927:16)
#7      CodeGenerator.visitMethodInvocation (package:dev_compiler/src/analyzer/code_generator.dart:3676:14)
#8      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7234:49)
#9      CodeGenerator.visitExpressionStatement (package:dev_compiler/src/analyzer/code_generator.dart:4114:23)
#10     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3766:49)
#11     CodeGenerator._visitStatement (package:dev_compiler/src/analyzer/code_generator.dart:5830:18)
#12     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#13     ListIterable.toList (dart:_internal/iterable.dart:219:19)
#14     CodeGenerator._visitStatementList (package:dev_compiler/src/analyzer/code_generator.dart:5837:41)
#15     CodeGenerator.visitBlockFunctionBody (package:dev_compiler/src/analyzer/code_generator.dart:3629:25)
#16     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#17     CodeGenerator._emitFunctionScopedBody (package:dev_compiler/src/analyzer/code_generator.dart:2845:22)
#18     CodeGenerator._emitSyncFunctionBody (package:dev_compiler/src/analyzer/code_generator.dart:2794:17)
#19     CodeGenerator._emitFunction (package:dev_compiler/src/analyzer/code_generator.dart:2777:11)
#20     CodeGenerator._emitFunctionExpression (package:dev_compiler/src/analyzer/code_generator.dart:2757:12)
#21     CodeGenerator.visitFunctionDeclaration (package:dev_compiler/src/analyzer/code_generator.dart:2613:14)
#22     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4932:49)
#23     CodeGenerator.visitCompilationUnit (package:dev_compiler/src/analyzer/code_generator.dart:561:30)
#24     List.forEach (dart:core-patch/array.dart:110:8)
#25     CodeGenerator.compile (package:dev_compiler/src/analyzer/code_generator.dart:316:22)
#26     compileWithAnalyzer (package:dev_compiler/src/analyzer/module_compiler.dart:108:33)
#27     _compile (package:dev_compiler/src/analyzer/command.dart:152:16)
#28     compile (package:dev_compiler/src/analyzer/command.dart:56:18)
#29     compile (package:dev_compiler/src/compiler/shared_command.dart:413:18)
#30     runBatch (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:92:22)
<asynchronous suspension>
#31     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:30:11)
<asynchronous suspension>
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```

/cc @vsmenon for triage

**Comment by sigmundch** [comment]
marking as not planned: this is implemented in ddc-kernel, but will not be be implemented in ddc-legacy.
