### ISSUE TITLE
Sorry, no idea what I was doing when this happened.

### ISSUE THREAD

**Issue by barrycarr** [dart-lang/sdk#37803]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.5728.98`
- `2.4.0`
- `IU-192.5728.98, JRE 1.8.0_152-release-b886x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2560x1440, 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Failed to handle completion domain request: {id: 12930, method: completion.getSuggestions, params: {file: C:\Users\Barry\IdeaProjects\analog_memo\lib\widgets\voiceNote.dart, offset: 163}, clientRequestTime: 1565456789877}
NoSuchMethodError: The getter 'returnType' was called on null.
Receiver: null
Tried calling: returnType
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _LocalVisitor.declaredGenericTypeAlias (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:237:36)
#2      LocalDeclarationVisitor.visitCompilationUnit.<anonymous closure> (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:130:9)
#3      _NodeListImpl&Object&ListMixin.forEach (dart:collection/list.dart:63:13)
#4      LocalDeclarationVisitor.visitCompilationUnit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:104:23)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#6      LocalDeclarationVisitor.visit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:70:12)
#7      LocalReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:66:17)
<asynchronous suspension>
#8      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:138:31)
<asynchronous suspension>
#9      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:122:42)
<asynchronous suspension>
#10     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#11     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#17     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:45)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:317:50)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1500:12)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:316:5)
#25     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#28     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#41     _rootRunUnary (dart:async/zone.dart:1132:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#46     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#47     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#48     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#49     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#50     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#51     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#52     _Co...
```

For additional log information, please append the contents of
file://C:\Users\Barry\AppData\Local\Temp\report.txt.
[report.txt](https://github.com/dart-lang/sdk/files/3489137/report.txt)

**Comment by srawlins** [comment]
Thank you for reporting! I think this is a duplicate  of https://github.com/dart-lang/sdk/issues/37555.
