### ISSUE TITLE
Analysis server crashes on startup with Could not initialize the library map

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/sdk#37818]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.7141.44`
- `2.5.0-dev.2.0`
- `IU-191.7141.44, JRE 1.8.0_202-release-1483-b49x64 JetBrains s.r.o, OS Linux(amd64) v4.19.37-5+deb10u1rodete1-amd64, screens 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.5.0-dev.2.0, server version 1.27.2, error: Could not initialize the library map from [/usr/local/google/home/ariaye/sdk/lib/_internal/sdk_library_metadata/lib/libraries.dart, /usr/local/google/home/ariaye/sdk/lib/_internal/libraries.dart]

FileSystemException(path=/usr/local/google/home/ariaye/sdk/lib/_internal/libraries.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:249:18)
#2      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:623:41)
#3      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:493:18)
#4      ContextBuilder.findSdk.<anonymous closure> (package:analyzer/src/context/builder.dart:411:36)
#5      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
#6      DartSdkManager.getSdk (package:analyzer/src/generated/sdk.dart:146:19)
#7      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:410:23)
#8      ContextBuilder.createSourceFactory (package:analyzer/src/context/builder.dart:288:19)
#9      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:185:16)
#10     ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:773:48)
#11     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1154:19)
#12     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1216:16)
#13     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:756:9)
#14     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:500:22)
#15     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:385:14)
#16     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:319:16)
#17     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1500:12)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#25     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#28     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#41     _rootRunUnary (dart:async/zone.dart:1132:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#46     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#47     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#48     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#49     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#50     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#51     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#52     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#53     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#54     _rootRunUnary (dart:async/zone.dart:1132:38)...
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by lambdabaa** [comment]
Closing as dupe of #33602.
