### ISSUE TITLE
Defend against null includedSuggestionRelevanceTags

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/sdk#37841]
Encountered in a set of analysis server tests where a subscription is not set for available suggestions:

```
NoSuchMethodError: The method 'add' was called on null.
Receiver: null
Tried calling: add(Instance of 'IncludedSuggestionRelevanceTag')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      CompletionRanking.rerank.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_ranking.dart:171:14)
#2      List.forEach (dart:core-patch/growable_array.dart:283:8)
```

**Comment by lambdabaa** [comment]
https://dart-review.googlesource.com/c/sdk/+/112927
