### ISSUE TITLE
Invalid code may crash analysis server

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#37877]
Writing this invalid code and saving file causes Analysis Server crash
```
main() {
  var foo = "<html>$void</html>";
}
```

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.9dcd7267bacd0924e2bd17a8519e74d0ea480e94, server version 1.27.2, error: Captured exception
Internal problem: Unhandled </html>" in analyzeQuote.
#0      internalProblem (package:front_end/src/fasta/problems.dart:45:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:58:10)
#2      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#3      unescapeString (package:front_end/src/fasta/quote.dart:138:17)
#4      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1415:22)
#5      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4891:14)
#6      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4816:13)
#7      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#8      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#9      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#10     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#11     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#12     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5314:16)
#13     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5225:12)
#14     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3814:14)
#15     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#16     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#17     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2460:13)
#18     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2340:14)
#19     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:493:14)
#20     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#21     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#22     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#23     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#24     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#25     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#26     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#27     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#28     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#29     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#30     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#31     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#32     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#33     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:552:21)
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1463:12)
#38     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:667:12)
#39     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:550:7)
#40     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:454:9)
#41     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#42     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:449:43)
#43     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#44     new Future.sync (dart:async/future.dart:224:31)
#45     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#46     _rootRun (dart:async/zone.dart:1124:13)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _runZoned (dart:async/zone.dart:1516:10)
#49     runZoned (dart:async/zone.dart:1463:12)
#50     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#51     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#52     Driver.start (package:analysis_server/src/server/driver.dart:449:21)
#53     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#54     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#55     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bi...
```

**Comment by bwilkerson** [comment]
@danrubel It appears that the parser sees `void` and "forgets" that it's parsing an interpolated string. Hence, when it finds the last segment of the interpolated string it treats it as a single literal string, which causes problems.
