### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by feinstein** [dart-lang/sdk#37879]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.5728.98`
- `2.4.0`
- `IU-192.5728.98, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in ConditionalExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ArgumentListImpl in MethodInvocationImpl in AwaitExpressionImpl in ExpressionStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      _NodeListImpl&Object&ListMixin.first (dart:collection/list.dart:75:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#6      ConditionalExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2281:22)
#7      RecursiveAstVisitor.visitConditionalExpression (package:analyzer/dart/ast/visitor.dart:733:10)
#8      LinterVisitor.visitConditionalExpression (package:analyzer/src/lint/linter_visitor.dart:132:11)
#9      ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:2276:15)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#11     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#12     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#13     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#15     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#16     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:625:10)
#17     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#18     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#19     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:991:10)
#20     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#21     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#22     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#23     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#24     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#25     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#26     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#27     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#28     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:625:10)
#29     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#30     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#31     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:991:10)
#32     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#33     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#34     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#35     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#36     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#37     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#38     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#39     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#40     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:625:10)
#41     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#42     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#43     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:991:10)
#44     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#45     InstanceCreationExpressionIm...
```

For additional log information, please append the contents of
file://C:\Users\MICHEL~2\AppData\Local\Temp\report.txt.

**Comment by a-siva** [comment]
Could be related to https://github.com/dart-lang/sdk/issues/33450

**Comment by stereotype441** [comment]
Looks like this was fixed in https://github.com/dart-lang/linter/commit/00c8317a3874cc0a1cb0e07597e379fea400306c
