### ISSUE TITLE
Exception when typing in a new EOL documentation comment

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#37878]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 193.SNAPSHOT`
- `2.5.0-edge.b0968395f13ec42bdbe671fd504be4c7629bbb9e`
- `IC-193.SNAPSHOT, JRE 1.8.0_211-b12x64 Oracle Corporation, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.b0968395f13ec42bdbe671fd504be4c7629bbb9e, server version 1.27.2, error: Failed to handle completion domain request: {id: 2491, method: completion.getSuggestions, params: {file: /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart, offset: 13063}, clientRequestTime: 1565891768196}
NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      constructQuery (package:analysis_server/src/services/completion/dart/completion_ranking_internal.dart:163:41)
#2      CompletionRanking.predict (package:analysis_server/src/services/completion/dart/completion_ranking.dart:74:19)
<asynchronous suspension>
#3      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:99:35)
<asynchronous suspension>
#4      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:122:42)
<asynchronous suspension>
#5      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#6      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1500:12)
#11     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamController._sendData (dart:async/stream_controller.d...
```

For additional log information, please append the contents of
file:///private/var/folders/5_/801pkmkn457fzp_twzmc2g88003ky_/T/report9.txt.

```
Dart analysis server, SDK version 2.5.0-edge.b0968395f13ec42bdbe671fd504be4c7629bbb9e, server version 1.27.2, error: Failed to handle completion domain request: {id: 2491, method: completion.getSuggestions, params: {file: /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart, offset: 13063}, clientRequestTime: 1565891768196}
NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      constructQuery (package:analysis_server/src/services/completion/dart/completion_ranking_internal.dart:163:41)
#2      CompletionRanking.predict (package:analysis_server/src/services/completion/dart/completion_ranking.dart:74:19)
<asynchronous suspension>
#3      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:99:35)
<asynchronous suspension>
#4      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:122:42)
<asynchronous suspension>
#5      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#6      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1500:12)
#11     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#55     _StreamController._add (dart:async/stream_controller.dart:640:7)
#56     _StreamController.add (dart:async/stream_controller.dart:586:5)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:1791:41)
#58     _rootRunUnary (dart:async/zone.dart:1136:13)
#59     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#63     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#64     _StreamController._add (dart:async/stream_controller.dart:640:7)
#65     _StreamController.add (dart:async/stream_controller.dart:586:5)
#66     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1339:33)
#67     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:860:14)
#68     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#69     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#70     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```
1565891768149 <= 			[librariesTotal: 0][librariesLoaded: 0][inputsTimer: 0 ms][librariesLinked: 0][librariesLinkedTimer: 0 ms][bytesGet: 0][bytesPut: 0]
1565891768149 <= 		--- Prepare linked bundles in 0 ms.
1565891768155 <= 		Computed new analysis result.
1565891768155 <= 	--- Compute analysis result for /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/benchmark/integration/log_file_input_converter.dart in 4 ms.
1565891768155 <= {"event":"analysis.errors","params":{"file":"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/benchmark/integration/log_file_input_converter.dart","errors":[]}}
1565891768155 <= 	+++ Compute analysis result for /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/benchmark/integration/input_converter.dart.
1565891768155 <= 		+++ Prepare linked bundles.
1565891768155 <= 			[librariesTotal: 0][librariesLoaded: 0][inputsTimer: 0 ms][librariesLinked: 0][librariesLinkedTimer: 0 ms][bytesGet: 0][bytesPut: 0]
1565891768155 <= 		--- Prepare linked bundles in 0 ms.
1565891768161 => {"id":"2490","method":"analysis.updateContent","params":{"files":{"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart":{"type":"add","content":"//
1565891768185 <= 		Computed new analysis result.
1565891768185 <= 	--- Compute analysis result for /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/benchmark/integration/input_converter.dart in 33 ms.
1565891768185 <= {"event":"analysis.errors","params":{"file":"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/benchmark/integration/input_converter.dart","errors":[{"severity":"INFO","type
1565891768188 <= {"id":"2490","result":{}}
1565891768189 <= 	+++ Verify API signature of /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart.
1565891768196 <= 		+++ Create unlinked for /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart.
1565891768196 => {"id":"2491","method":"completion.getSuggestions","params":{"file":"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart","offset":13063},"clientReq
1565891768200 <= 		--- Create unlinked for /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart in 4 ms.
1565891768200 <= 	--- Verify API signature of /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart in 11 ms.
1565891768201 <= 	+++ Compute analysis result for /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart.
1565891768201 <= 		+++ Prepare linked bundles.
1565891768204 <= 			[librariesTotal: 612][librariesLoaded: 612][inputsTimer: 0 ms][librariesLinked: 0][librariesLinkedTimer: 0 ms][bytesGet: 13430024][bytesPut: 0]
1565891768204 <= 		--- Prepare linked bundles in 2 ms.
1565891768321 => {"id":"2492","method":"analysis.updateContent","params":{"files":{"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart":{"type":"add","content":"//
1565891768324 => {"id":"2493","method":"completion.getSuggestions","params":{"file":"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart","offset":13064},"clientReq
1565891768370 <= 		Computed new analysis result.
1565891768370 <= 	--- Compute analysis result for /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart in 169 ms.
1565891768371 <= {"id":"2491","result":{"id":"267"}}
1565891768372 <= {"event":"analysis.errors","params":{"file":"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/type_system.dart","errors":[{"severity":"INFO","type":"TODO","locat
1565891768430 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {id: 2491, method: completion.getSuggestions, params: {file: /Users/scheglov/S
```

**Comment by lambdabaa** [comment]
https://dart-review.googlesource.com/c/sdk/+/113285

**Comment by lambdabaa** [comment]
Fix landed about a month ago but I forgot to close.
