### ISSUE TITLE
The ffi/function_test/{3,4} tests have started crashing

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#37873]
From [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8905134883136152784/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0):
```

/==========================================================\
| ffi/function_test/3 broke (Pass -> Crash, expected Pass) |
\==========================================================/

--- Command "vm_compile_to_kernel []" (took 689ms):
DART_CONFIGURATION=DebugSIMDBC64 /b/s/w/ir/cache/builder/sdk/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/DebugSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/cache/builder/sdk/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_ffi_function_test.dart_3/out.dill /b/s/w/ir/cache/builder/sdk/tests/ffi/function_test.dart --packages=/b/s/w/ir/cache/builder/sdk/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 11.000398s):
DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --hot-reload-test-mode --write-protect-code --no-dual-map-code --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_ffi_function_test.dart_3/out.dill

exit code:
-6

stdout:
...
NoSuchMethodError: The method 'FfiTrampoline' was called on null.
Receiver: null
Tried calling: FfiTrampoline(), #0      FfiTrampoline (dart:ffi)
#1      testException (file:///b/s/w/ir/cache/builder/sdk/tests/ffi/function_test.dart:442:14)
#2      main (file:///b/s/w/ir/cache/builder/sdk/tests/ffi/function_test.dart:44:5)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
...
val[1] = 1337
returning 0x7fe530504608

stderr:
../../runtime/vm/object.cc: 15287: error: expected: !is_optimized() || (pc_offset == EntryPoint() - PayloadStart())
version=2.5.0-edge.a2de29095e24496d29576bdc3e9bae9855d9f68a (Wed Aug 14 15:47:09 2019 +0000) on "macos_dbc"
thread=3331, isolate=main(0x7fe53085c000)
  pc 0x0000000101d41e34 fp 0x0000700008383740 dart::Profiler::DumpStackTrace(void*)
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -n dartk-reload-mac-debug-simdbc64 ffi/function_test/3
```

**Comment by sjindel-google** [comment]
This test appears to only fail on DBC, which has been decommissioned, so I don't think it's necessary to fix it.
