### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vladimirdjokic76** [dart-lang/sdk#37914]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Exception while using a AvoidRenamingMethodParameters to visit a MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _Visitor.visitMethodDeclaration (package:linter/src/rules/avoid_renaming_method_parameters.dart:84:25)
#2      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7107:49)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#4      LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:449:5)
#5      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7107:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#7      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1590:13)
#8      RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:703:10)
#9      LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:102:11)
#10     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1560:49)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2167:21)
#13     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:727:10)
#14     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#15     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#16     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:350:10)
#17     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:200:11)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:195:35)
#20     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:108:14)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:43)
#23     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1418:63)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#25     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
#26     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1077:33)
<asynchronous suspension>
#27     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
<asynchronous suspension>
#28     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#29     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#30     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#31     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#32     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#38     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#39     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#40     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#42     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#43     new Future.sync (dart:async/future.dart:224:31)
#44     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#45     _rootRun (dart:async/zone.dart:1124:13)
#46     _CustomZone.run (dart:async/zone.dart:1021:19)
#47     _runZoned (dart:async/zone.dart:1516:10)
#48     runZoned (dart:async/zone.dart:1463:12)
#49     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#50     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#51     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#52     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#53     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#54     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#55     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/bp/70836ksx70704lzkfsp_w9g00000gn/T/report.txt.

**Comment by srawlins** [comment]
This error has not been reported since Dart 2.4.0. Please re-open if you hit this crash on a recent version of Dart.
