### ISSUE TITLE
Analysis Server: NoSuchMethodError: The getter 'next' was called on null.

### ISSUE THREAD

**Issue by matthewlloyd** [dart-lang/sdk#37922]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.5728.98`
- `2.4.0`
- `IU-192.5728.98, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
NoSuchMethodError: The getter 'next' was called on null.
Receiver: null
Tried calling: next
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      Parser.parseLiteralFunctionSuffix (package:front_end/src/fasta/parser/parser.dart:4577:38)
#2      Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4609:14)
#3      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4283:14)
#4      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#5      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#6      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#7      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3898:13)
#8      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5307:16)
#9      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5218:12)
#10     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3803:14)
#11     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3705:20)
#12     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3610:15)
#13     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3259:15)
#14     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3122:15)
#15     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2898:15)
#16     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1783:13)
#17     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1743:14)
#18     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#19     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#20     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#21     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#22     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#23     _File._parse (package:analyzer/src/services/available_declarations.dart:1656:23)
#24     _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#25     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:642:10)
#26     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:508:7)
#27     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#28     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#29     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#30     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#31     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#32     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#33     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1463:12)
#38     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#39     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#40     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#41     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#42     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#43     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#44     new Future.sync (dart:async/future.dart:224:31)
#45     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#46     _rootRun (dart:async/zone.dart:1124:13)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _runZoned (dart:async/zone.dart:1516:10)
#49     runZoned (dart:async/zone.dart:1463:12)
#50     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#51     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#52     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#53     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#54     _AsyncAwaitCompleter.start (dart:async-patch/async_...
```

**Comment by srawlins** [comment]
Thank you for reporting this issue! This was previously reported in https://github.com/dart-lang/sdk/issues/37066; please follow along there.
