### ISSUE TITLE
fuzz: analyzer extensions Class 'ExtensionElementForLink' has no instance getter 'accessors'

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#37941]
`extension; v=1.`

causes

```
Unhandled exception:
NoSuchMethodError: Class 'ExtensionElementForLink' has no instance getter 'accessors'.
Receiver: Instance of 'ExtensionElementForLink'
Tried calling: accessors
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ExtensionElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:2583:48)
#2      ExtensionElementForLink.accessors (package:analyzer/src/dart/element/element.dart:4989:37)
#3      ExtensionMemberResolver._getExtensionsWithMember.checkExtension (package:analyzer/src/dart/resolver/extension_member_resolver.dart:325:40)
#4      ExtensionMemberResolver._getExtensionsWithMember (package:analyzer/src/dart/resolver/extension_member_resolver.dart:358:21)
#5      ExtensionMemberResolver._getApplicable (package:analyzer/src/dart/resolver/extension_member_resolver.dart:258:22)
#6      ExtensionMemberResolver.findExtension (package:analyzer/src/dart/resolver/extension_member_resolver.dart:41:22)
#7      ElementResolver._lookUpGetter (package:analyzer/src/generated/element_resolver.dart:1271:35)
#8      ElementResolver._resolveProperty (package:analyzer/src/generated/element_resolver.dart:1722:11)
#9      ElementResolver._resolvePropertyAccess (package:analyzer/src/generated/element_resolver.dart:1809:20)
```

**Comment by bwilkerson** [comment]
This should be fixed by https://dart-review.googlesource.com/c/sdk/+/113952. Test added in https://dart-review.googlesource.com/c/sdk/+/114180.
