### ISSUE TITLE
fuzz: analyzer extensions crash on super operator

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#37942]
`extension<T>on T{ f(){ super+ 1; } }`

causes:

```
Unhandled exception:
Bad state: No element
#0      List.last (dart:core-patch/growable_array.dart:225:5)
#1      InheritanceManager3.getMember (package:analyzer/src/dart/element/inheritance_manager3.dart:239:31)
#2      ElementResolver._resolveBinaryExpression.lookupIn (package:analyzer/src/generated/element_resolver.dart:1598:56)
#3      ElementResolver._resolveBinaryExpression (package:analyzer/src/generated/element_resolver.dart:1609:17)
#4      ElementResolver.visitBinaryExpression (package:analyzer/src/generated/element_resolver.dart:193:7)
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/114185
