### ISSUE TITLE
stdout.flush results in Bad state: StreamSink is bound to a stream when used inside an infinite loop

### ISSUE THREAD

**Issue by pacifio** [dart-lang/sdk#37940]
My dart code
```dart
void main(){
while (true) {
    stdout.write("Hello from std");
    stdout.flush();
  }
}
```

Error
```dart
Bad state: StreamSink is bound to a stream
#0      _StreamSinkImpl._controller (dart:io/io_sink.dart:236:7)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:156:5)
#2      _IOSinkImpl.write (dart:io/io_sink.dart:289:5)
#3      _StdSink.write (dart:io/stdio.dart:337:11)
```

What causes this ?

**Comment by vsmenon** [comment]
See:

https://api.dartlang.org/dev/2.5.0-dev.2.1/dart-io/Stdout/flush.html

You need to `await` the `flush`.  E.g.:

```dart
import 'dart:io';

void main() async {
  while (true) {
    stdout.write("Hello from std");
    await stdout.flush();
  }
}
```
