### ISSUE TITLE
Element mismatch in DeclarationResolver (again)

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#37979]
Well..

I have no idea what's going on. I was just using Flutter, hot reloading things, etc and it suddenly crashed, I clicked on the pop up and it opened this issue. Every other related issue has been closed. So that seems like a regression?
 

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6262.58`
- `2.5.0-edge.027071318ff1333fefcf7b4e475c10a8f68ebc0d`
- `IU-192.6262.58, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.027071318ff1333fefcf7b4e475c10a8f68ebc0d, server version 1.27.2, error: Analysis failed: /Users/bernardoferrari/Documents/material/lib/main.dart context: exception_20190822_223912_157
Element mismatch in /Users/bernardoferrari/Documents/material/lib/main.dart at class _MyHomePageState extends State<MyHomePage>
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:657:31)
#2      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#4      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#5      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#7      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#9      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
<asynchronous suspension>
#12     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#13     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#14     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#15     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#16     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#17     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#23     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#24     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#25     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#26     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#27     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#35     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#36     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#37     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#38     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#39     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Caused by type 'ConstructorElementImpl' is not a subtype of type 'MethodElement' in type cast
#0      MethodElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:1024:58)
#1      MethodElementHandle.isStatic (package:analyzer/src/dart/element/handle.dart:1030:24)
#2      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1137:58)
#3      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:976:15)
#4      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:1001:15)
#5      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1397:30)
#6      _UnitResynthesizer.buildLinkedType (package:analyzer/src/summary/resynthesize.dart:1349:12)
#7      SummaryResynthesizerContext.resolveLinkedType (package:analyzer/src/summary/resynthesize.dart:488:30)
#8      NonParameterVariableElementImpl.type (package:analyzer/src/dart/element/element.dart:8591:12)
#9      PropertyInducingElementImpl.typ...
```

Additional info:
```
Dart analysis server, SDK version 2.5.0-edge.027071318ff1333fefcf7b4e475c10a8f68ebc0d, server version 1.27.2, error: Analysis failed: /Users/bernardoferrari/Documents/material/lib/main.dart context: exception_20190822_223912_157
Element mismatch in /Users/bernardoferrari/Documents/material/lib/main.dart at class _MyHomePageState extends State<MyHomePage>
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:657:31)
#2      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#4      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#5      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#7      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#9      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
<asynchronous suspension>
#12     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#13     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#14     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#15     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#16     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#17     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#23     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#24     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#25     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#26     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#27     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#35     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#36     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#37     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#38     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#39     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Caused by type 'ConstructorElementImpl' is not a subtype of type 'MethodElement' in type cast
#0      MethodElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:1024:58)
#1      MethodElementHandle.isStatic (package:analyzer/src/dart/element/handle.dart:1030:24)
#2      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1137:58)
#3      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:976:15)
#4      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:1001:15)
#5      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1397:30)
#6      _UnitResynthesizer.buildLinkedType (package:analyzer/src/summary/resynthesize.dart:1349:12)
#7      SummaryResynthesizerContext.resolveLinkedType (package:analyzer/src/summary/resynthesize.dart:488:30)
#8      NonParameterVariableElementImpl.type (package:analyzer/src/dart/element/element.dart:8591:12)
#9      PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:9762:18)
#10     DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/declaration_resolver.dart:491:56)
#11     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10613:15)
#12     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4097:17)
#13     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:857:10)
#14     DeclarationResolver.visitFieldDeclaration (package:analyzer/src/generated/declaration_resolver.dart:198:11)
#15     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4092:49)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#17     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#18     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#19     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:84:13)
#20     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:559:13)
#21     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:83:5)
#22     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#24     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#25     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#26     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#27     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:46:12)
#28     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:657:31)
#29     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#30     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#31     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#32     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#33     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#34     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#35     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#36     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#37     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#38     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
<asynchronous suspension>
#39     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#40     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#41     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#42     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#43     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#44     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#45     _rootRun (dart:async/zone.dart:1124:13)
#46     _CustomZone.run (dart:async/zone.dart:1021:19)
#47     _runZoned (dart:async/zone.dart:1516:10)
#48     runZoned (dart:async/zone.dart:1463:12)
#49     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#50     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#51     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#52     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#53     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#54     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#55     new Future.sync (dart:async/future.dart:224:31)
#56     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#57     _rootRun (dart:async/zone.dart:1124:13)
#58     _CustomZone.run (dart:async/zone.dart:1021:19)
#59     _runZoned (dart:async/zone.dart:1516:10)
#60     runZoned (dart:async/zone.dart:1463:12)
#61     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#62     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#63     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#64     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#65     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#66     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#67     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
```
1566524349760 <= {"event":"analysis.errors","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/Users
1566524349761 <= {"id":"1033","result":{"assists":[]}}
1566524349761 <= {"event":"analysis.highlights","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":39},{"type":"BUILT_IN","of
1566524349762 <= {"event":"analysis.navigation","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","regions":[{"offset":7,"length":31,"targets":[0]},{"offset":46,"length":4,"ta
1566524349762 <= {"event":"analysis.closingLabels","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","labels":[{"offset":224,"length":173,"label":"MaterialApp"},{"offset":279,
1566524349763 <= {"event":"analysis.outline","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>"
1566524349764 <= {"event":"analysis.overrides","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","overrides":[{"offset":183,"length":5,"superclassMember":{"element":{"kind":"M
1566524349765 <= {"event":"flutter.outline","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":4496,"codeOffset":0,"codeLen
1566524349781 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":680,"uri":"package:material/main.dart","items":[{"label":"MyHomePage","declaringLibraryUri":"package:mat
1566524349812 <= {"event":"analysis.errors","params":{"file":"/Users/bernardoferrari/Documents/material/test/widget_test.dart","errors":[]}}
1566524349813 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1566524349813 <= {"event":"analysis.implemented","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","classes":[],"members":[]}}
1566524350067 => {"id":"1034","method":"edit.getFixes","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","offset":1618},"clientRequestTime":1566524350067}
1566524350068 <= {"id":"1034","result":{"fixes":[{"error":{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","offset":1618,"lengt
1566524350074 => {"id":"1035","method":"edit.getAssists","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","offset":1619,"length":0},"clientRequestTime":1566524350073}
1566524350075 <= {"id":"1035","result":{"assists":[]}}
1566524350964 => {"id":"1036","method":"edit.getAssists","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","offset":1586,"length":0},"clientRequestTime":1566524350964}
1566524350965 <= {"id":"1036","result":{"assists":[]}}
1566524351277 => {"id":"1037","method":"edit.getAssists","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","offset":1585,"length":0},"clientRequestTime":1566524351277}
1566524351278 <= {"id":"1037","result":{"assists":[]}}
1566524351918 => {"id":"1038","method":"analysis.updateContent","params":{"files":{"/Users/bernardoferrari/Documents/material/lib/main.dart":{"type":"add","content":"import 'package:flutter/material.d
1566524351919 <= {"id":"1038","result":{}}
1566524351923 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1566524351928 => {"id":"1039","method":"edit.getAssists","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","offset":1584,"length":0},"clientRequestTime":1566524351928}
1566524351952 => {"id":"1040","method":"edit.getAssists","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","offset":1621,"length":0},"clientRequestTime":1566524351952}
1566524351952 => {"id":"1041","method":"edit.getAssists","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","offset":1621,"length":0},"clientRequestTime":1566524351952}
1566524351952 => {"id":"1042","method":"edit.getAssists","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","offset":1621,"length":0},"clientRequestTime":1566524351952}
1566524351952 => {"id":"1043","method":"edit.getAssists","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","offset":1621,"length":0},"clientRequestTime":1566524351952}
1566524352252 => {"id":"1044","method":"edit.getAssists","params":{"file":"/Users/bernardoferrari/Documents/material/lib/main.dart","offset":1620,"length":0},"clientRequestTime":1566524352252}
1566524352297 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/bernardoferrari/Documents/material/lib/main.dart context: exception_20190822_223912_157","stackTra
```

**Comment by MichaelRFairhurst** [comment]
Likely the same as the fuzz crash #38090

**Comment by bernaferrari** [comment]
Probably.. should I close?

**Comment by srawlins** [comment]
They seem different enough... I'd be happy to keep this one open.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.5; please re-open if you see this in a recent version of Dart/Flutter.
