### ISSUE TITLE
Analysis server exception on editing a hex value

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/sdk#37976]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Editing a Color constructor with a Hex value.

```dart
AppBar(
  elevation: 0,
  backgroundColor: Color(0x), // <- Editing this constructor argument causes the exception
)
```

### Versions

- Flutter SDK 1.9.4-pre.37
- Visual Studio Code 1.37.1
- Dart Code 3.3.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/brettmorgan/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.3.0
```

### Exception

Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl

```text
Bad state: No element
#0      ListMixin.first (dart:collection/list.dart:76:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6182:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:725:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:395:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6182:15)
#6      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7431:18)
#7      RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#8      LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:480:11)
#9      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7426:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7672:20)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#14     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#15     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#16     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:396:11)
#17     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6182:15)
#18     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7431:18)
#19     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#20     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:480:11)
#21     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7426:49)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7672:20)
#23     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#24     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#25     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#26     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#27     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#28     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:396:11)
#29     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6182:15)
#30     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8640:18)
#31     RecursiveAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:1164:10)
#32     LinterVisitor.visitReturnStatement (package:analyzer/src/lint/linter_visitor.dart:553:11)
#33     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8636:49)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7672:20)
#35     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#36     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#37     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:66:11)
#38     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#39     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#40     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#41     LinterVisitor.visitBlockFunctionBody (package:analyzer/src/lint/linter_visitor.dart:72:11)
#42     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#43     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7112:12)
#44     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1061:10)
#45     LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:462:11)
#46     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7103:49)
#47     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7672:20)
#48     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#49     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#50     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:102:11)
#51     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#52     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7672:20)
#53     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#54     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#55     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#56     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#57     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:353:10)
#58     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:206:11)
#59     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#60     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:201:35)
#61     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#62     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#63     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#64     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1260:63)
#65     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#66     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#67     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:927:33)
<asynchronous suspension>
#68     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1923:24)
<asynchronous suspension>
#69     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#70     new AnalysisServer (package:analysis_server/src/analysis_server.dart:219:29)
#71     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#72     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#73     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:589:21)
#74     _rootRun (dart:async/zone.dart:1124:13)
#75     _CustomZone.run (dart:async/zone.dart:1021:19)
#76     _runZoned (dart:async/zone.dart:1516:10)
#77     runZoned (dart:async/zone.dart:1463:12)
#78     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:706:12)
#79     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:587:7)
#80     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:488:9)
#81     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#82     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:483:43)
#83     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#84     new Future.sync (dart:async/future.dart:224:31)
#85     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#86     _rootRun (dart:async/zone.dart:1124:13)
#87     _CustomZone.run (dart:async/zone.dart:1021:19)
#88     _runZoned (dart:async/zone.dart:1516:10)
#89     runZoned (dart:async/zone.dart:1463:12)
#90     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#91     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#92     Driver.start (package:analysis_server/src/server/driver.dart:483:21)
#93     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#94     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#95     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#96     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#97     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/brettmorgan/flutter-apps/flutter_landmarks_material",
        "explicitFileCount": 6,
        "implicitFileCount": 674,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment]
I cannot reproduce this crash. Please re-open if you can reproduce on a recent version of Dart.
