### ISSUE TITLE
Exception in FlowModel

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#37983]
The exception occurred after I restarted analysis server after building the SDK on Fri Aug 23 08:06:23 PDT 2019.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6262.58`
- `2.5.0-edge.d53867d259a760c4e69ee7e1ba53196e560160e6`
- `IC-192.6262.58, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.d53867d259a760c4e69ee7e1ba53196e560160e6, server version 1.27.2, error: Analysis failed: /Users/brianwilkerson/src/dart/personal/test_package/lib/error_codes_without_fixes.dart context: exception_20190823_081218_299
NoSuchMethodError: The getter 'promotedType' was called on null.
Receiver: null
Tried calling: promotedType
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      FlowModel._removePromotedAll (package:front_end/src/fasta/flow_analysis/flow_analysis.dart:949:16)
#2      FlowModel.removePromotedAll (package:front_end/src/fasta/flow_analysis/flow_analysis.dart:792:9)
#3      FlowAnalysis.forEach_bodyBegin (package:front_end/src/fasta/flow_analysis/flow_analysis.dart:329:25)
#4      ResolverVisitor.visitForStatementInScope (package:analyzer/src/generated/resolver.dart:3973:28)
#5      ScopedVisitor.visitForStatement (package:analyzer/src/generated/resolver.dart:5472:7)
#6      ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4771:49)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7672:20)
#8      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#9      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4269:10)
#10     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#11     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:5182:13)
#12     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#13     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#14     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4269:10)
#15     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3131:55)
#16     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5193:13)
#17     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:3508:13)
#18     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#19     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5087:12)
#20     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4269:10)
#21     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3263:57)
#22     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5519:13)
#23     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:4032:13)
#24     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5081:49)
#25     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4940:26)
#26     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4269:10)
#27     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3256:59)
#28     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5512:11)
#29     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:4007:11)
#30     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5505:7)
#31     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:3998:13)
#32     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4933:49)
#33     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:3594:23)
#34     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#35     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:698:10)
#36     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#37     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#38     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#39     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#40     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#41     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#42     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1260:63)
#43     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#44     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#45     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#46     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1931:24)
<asynchronous suspension>
#47     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1865:5)
#48     new AnalysisServer (package:analysis_server/src/analysis_server...
```

For additional log information, please append the contents of
file:///private/var/folders/_z/xg4j4cl517zc6rm212d2pjsc003j4q/T/report4.txt.

@stereotype441

**Comment by stereotype441** [comment]
@bwilkerson Did you have NNBD enabled?  If not, then I want to classify this as a P1, because we only want flow analysis to be run in NNBD-enabled code.

**Comment by bwilkerson** [comment]
Yes. I should have said so in the original post. That's a test package that I use for trying out experimental features, including nnbd.

**Comment by stereotype441** [comment]
Fix out for review: https://dart-review.googlesource.com/c/sdk/+/115262
