### ISSUE TITLE
Can we able to build sdk on WSL on Windows 10 for android ?

### ISSUE THREAD

**Issue by canewsin** [dart-lang/sdk#37997]
I want to build dart-vm for android, is it possible to build it on wsl when i run to build normal sdk 
`sudo python ./tools/build.py --mode release --arch x64 create_sdk`
it gives me error 
```
Running python /home/pramukesh/dart-sdk/sdk/tools/generate_buildfiles.py
Traceback (most recent call last):
  File "/home/pramukesh/dart-sdk/sdk/tools/gn.py", line 559, in <module>
    sys.exit(Main(sys.argv))
  File "/home/pramukesh/dart-sdk/sdk/tools/gn.py", line 546, in Main
    results = pool.map(RunCommand, commands, chunksize=1)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
OSError: [Errno 13] Permission denied
gn gen --check in out/ReleaseX64
Traceback (most recent call last):
  File "/home/pramukesh/dart-sdk/sdk/tools/gn.py", line 559, in <module>
    sys.exit(Main(sys.argv))
  File "/home/pramukesh/dart-sdk/sdk/tools/gn.py", line 546, in Main
    results = pool.map(RunCommand, commands, chunksize=1)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
OSError: [Errno 13] Permission denied
Tried to run GN, but it failed. Try running it manually:
        $ python /home/pramukesh/dart-sdk/sdk/tools/gn.py -m release -a x64 --os host -v
Traceback (most recent call last):
  File "./tools/build.py", line 366, in <module>
    sys.exit(Main())
  File "./tools/build.py", line 341, in Main
    BuildOneConfig(options, targets, target_os, mode, arch))
  File "./tools/build.py", line 280, in BuildOneConfig
    if UseGoma(out_dir):
  File "./tools/build.py", line 227, in UseGoma
    return 'use_goma = true' in open(args_gn, 'r').read()
IOError: [Errno 2] No such file or directory: 'out/ReleaseX64/args.gn'
```

Even Building in Windows Gave me Error

```
C:\flutter\dart-sdk\sdk>python tools/build.py --mode release --arch x64 create_sdk -v
Running python C:\flutter\dart-sdk\sdk\tools\generate_buildfiles.py
Command failed: C:\flutter\dart-sdk\sdk\buildtools\gn.exe gen out\DebugIA32 --ide=vs --args=exclude_kernel_service=false is_product=false dart_runtime_mode="develop" dart_use_crashpad=false dart_platform_bytecode=false use_goma=false dart_platform_sdk=false is_msan=false is_release=false is_clang=false dart_stripped_binary="exe.stripped/dart" dart_target_arch="ia32" dart_use_tcmalloc=false goma_dir="None" dart_debug=true host_cpu="x86" dart_snapshot_kind="kernel" is_tsan=false target_os="win" dart_vm_code_coverage=false dart_use_fallback_root_certificates=true target_cpu="x86" is_asan=false is_debug=true dartaotruntime_stripped_binary="exe.stripped/dartaotruntime" gen_snapshot_stripped_binary="exe.stripped/gen_snapshot"
output: ERROR at //BUILD.gn:5:1: Can't load input file.
import("build/config/gclient_args.gni")
^-------------------------------------
Unable to load:
  C:/flutter/dart-sdk/sdk/build/config/gclient_args.gni
I also checked in the secondary tree for:
  C:/flutter/dart-sdk/sdk/build/secondary/build/config/gclient_args.gni
ninja -C out\ReleaseX64 -v create_sdk
ninja: error: loading 'build.ninja': The system cannot find the file specified.

ninja: Entering directory `out\ReleaseX64'
BUILD FAILED
```

**Comment by vsmenon** [comment]
This isn't supported at this point.  Merging into:

https://github.com/dart-lang/sdk/issues/31754
