### ISSUE TITLE
BUG for RandomAccessFile.readIntoSync(List<int>)

### ISSUE THREAD

**Issue by v7lin** [dart-lang/sdk#38015]
dart code:

```dart
    List<int> buffer = List<int>(4);
    RandomAccessFile raf = await file.open();
    for (int i = 0; i < length; i += buffer.length) {
      print('read [$i, ${math.min(length, i + buffer.length)})');
      raf.readIntoSync(buffer, i);
      print('${buffer.join(',')}');
    }
```

command:

```shell
flutter pub pub run test/tools/zip/main.dart --file zip/config.hdpi.apk
```

log: 

```
read [0, 4)
80,75,3,4
read [4, 8)
80,75,3,4
read [8, 12)
Unhandled exception:
RangeError (start): Invalid value: Not in range 0..4, inclusive: 8
#0      RangeError.checkValidRange (dart:core/errors.dart:328:7)
#1      _RandomAccessFile.readIntoSync (dart:io/file_impl.dart:797:22)
#2      ZipFile.open (file:///Users/v7lin/xxx/flutter_router/example/test/tools/zip/zip_file.dart:25:11)
<asynchronous suspension>
#3      main (file:///Users/v7lin/xxx/flutter_router/example/test/tools/zip/main.dart:15:11)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
pub finished with exit code 255
```

flutter for macOS Mojave
```
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (6 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```

**Comment by mraleph** [comment]
Please refer to the documentation of for [RandomAccessFile.readIntoSync](https://api.dartlang.org/dev/2.5.0-dev.2.1/dart-io/RandomAccessFile/readIntoSync.html). The second parameter is not a position in the file, but a position in the buffer from which you should be filling it in with bytes from file. If you want to read the file starting from specified position you need to use [RandomAccessFile.setPositionSync](https://api.dartlang.org/dev/2.5.0-dev.2.1/dart-io/RandomAccessFile/setPositionSync.html)

**Comment by v7lin** [comment]
thanks
