### ISSUE TITLE
 FATAL error: Failed to handle request: {id: 1784, method: edit.getFixes, 

### ISSUE THREAD

**Issue by viveky259259** [dart-lang/sdk#38025]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, FATAL error: Failed to handle request: {id: 1784, method: edit.getFixes, params: {file: /Users/stringsway/Documents/projects/flutter/ques_edu_app/lib/user_profile/user_profile.dart, offset: 536}, clientRequestTime: 1566923947737}
AnalysisException: Cannot analyze "/Users/stringsway/Documents/projects/flutter/ques_edu_app/lib/contact%20&%20about/contact.dart"

#0      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:72:7)
<asynchronous suspension>
#1      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:82:23)
<asynchronous suspension>
#2      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:52:18)
#3      FixProcessor._addFix_createImportUri (package:analysis_server/src/services/correction/fix_internal.dart:2061:31)
<asynchronous suspension>
#4      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:281:13)
<asynchronous suspension>
#5      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#6      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:649:46)
<asynchronous suspension>
#7      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:751:14)
<asynchronous suspension>
#8      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:278:32)
<asynchronous suspension>
#9      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:381:9)
#10     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:45)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#12     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:317:50)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1500:12)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:316:5)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#47     _rootRunUnary (dart:async/zone.dart:1132:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#51     _BufferingStreamSubsc...
```

For additional log information, please append the contents of
file:///private/var/folders/l1/7_7143m94vg29zb4k_tykbzm0000gn/T/report.txt.

**Comment by srawlins** [comment]
Thanks for reporting this issue. This was previously reported at https://github.com/dart-lang/sdk/issues/37058; please follow along there.

**Comment by srawlins** [comment]
Duplicate #37058
