### ISSUE TITLE
Continuous errors from IntelliJ .

### ISSUE THREAD

**Issue by g5becks** [dart-lang/sdk#38024]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6262.58`
- `2.4.1`
- `IU-192.6262.58, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1080x2560, 1280x800, 2560x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.1, server version 1.27.1, error: Analysis failed: /Users/garybecks/dev/deadline.dart/deadline/lib/src/task/task_args_converter.dart context: exception_20190827_092150_011
RangeError: Invalid type parameter index
#0      _ClassElementImpl&AbstractClassElementImpl&TypeParameterizedElementMixin.getTypeParameterType (package:analyzer/src/dart/element/element.dart:9737:7)
#1      _ExecutableElementImpl&ElementImpl&TypeParameterizedElementMixin.getTypeParameterType (package:analyzer/src/dart/element/element.dart:9733:12)
#2      _GenericFunctionTypeElementImpl&ElementImpl&TypeParameterizedElementMixin.getTypeParameterType (package:analyzer/src/dart/element/element.dart:9733:12)
#3      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1373:12)
#4      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:496:30)
#5      GenericFunctionTypeElementImpl.returnType (package:analyzer/src/dart/element/element.dart:5420:58)
#6      _FunctionTypeImplLazy.baseReturnType (package:analyzer/src/dart/element/type.dart:3474:57)
#7      _FunctionTypeImplLazy.returnType (package:analyzer/src/dart/element/type.dart:3562:36)
#8      ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:4542:65)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4999:49)
#10     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8644:18)
#11     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4770:10)
#12     UnifyingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:3380:51)
#13     ResolverVisitor.visitReturnStatement (package:analyzer/src/generated/resolver.dart:4822:11)
#14     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8640:49)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#16     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1121:17)
#17     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4770:10)
#18     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3116:31)
#19     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:5658:13)
#20     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1117:49)
#21     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1076:13)
#22     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4770:10)
#23     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3119:55)
#24     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5669:13)
#25     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:4114:13)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1072:49)
#27     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7116:12)
#28     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4770:10)
#29     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3321:55)
#30     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:6112:11)
#31     ResolverVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:4720:11)
#32     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:6105:7)
#33     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:4711:13)
#34     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7107:49)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#36     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:5735:18)
#37     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5713:11)
#38     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:4150:13)
#39     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1560:49)
#40     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:4209:23)
#41     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#42     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:692:10)
#43     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:155:7)
#44     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#45     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:154:11)
#46     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:108:14)
#47     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#48     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysi...
```

For additional log information, please append the contents of
file:///private/var/folders/zx/6whmtxyn5dg4327vcl7k9dwh0000gn/T/report.txt.

**Comment by MichaelRFairhurst** [comment]
It looks like we've hit this before (most likely) with this fuzz crash #38097 

It seems the underlying issue is that we have an issue with inferring generic function types as parameters of top level initializers.

If that is indeed what you're hitting, you should be able to work around it by specifying a type, so that

```dart
var o = (Function<T>(T) f) { ... };
```

becomes

```dart
Function(Function<T>(T)) o = (Function<T>(T) f) { ... };
```

**Comment by srawlins** [comment]
Since the analyzer moved to its new "Summary2" format, this has been fixed.
