### ISSUE TITLE
analyzer fuzz crash: metadata called on null in function typed list literal

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38047]
`s=<Function((T)=`

Note: this fails summary 1 and summary 2

```
_ElementMismatchException: Element mismatch in /home/mfairhurst/dart/test/lib/test.dart at List<dynamic Function({: dynamic Function(dynamic)})> ()
Caused by NoSuchMethodError: The setter 'metadata=' was called on null.
Receiver: null
Tried calling: metadata=_ImmutableList len:0
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _BaseElementBuilder.visitFunctionTypedFormalParameter (package:analyzer/src/dart/element/builder.dart:1510:13)
#2      FunctionTypedFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:5332:15)
#3      _BaseElementBuilder.visitDefaultFormalParameter (package:analyzer/src/dart/element/builder.dart:1454:21)
#4      LocalElementBuilder.visitDefaultFormalParameter (package:analyzer/src/dart/element/builder.dart:1204:11)
#5      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3063:15)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7662:20)
#7      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4546:17)
#8      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:887:10)
#9      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4542:49)
#10     GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5457:18)
#11     _BaseElementBuilder._visitChildren (package:analyzer/src/dart/element/builder.dart:1686:14)
#12     _BaseElementBuilder.visitGenericFunctionType (package:analyzer/src/dart/element/builder.dart:1518:5)
#13     DeclarationResolver.visitGenericFunctionType (package:analyzer/src/generated/declaration_resolver.dart:284:30)
#14     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5450:20)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7662:20)
#16     TypeArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10053:16)
#17     RecursiveAstVisitor.visitTypeArgumentList (package:analyzer/dart/ast/visitor.dart:1278:10)
#18     TypeArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10049:49)
#19     TypedLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10096:21)
#20     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6816:11)
#21     RecursiveAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:1049:10)
#22     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6812:49)
```

**Comment by DanTup** [comment]
@MichaelRFairhurst I noticed this because it was tagged as LSP (although, I'm not sure from the stack trace it actually is LSP related). I can't reproduce any issue by pasting the code `s=<Function((T)=` into a file using the latest analyzer. Is it possible this is fixed, or is there more to reproducing it?

**Comment by bwilkerson** [comment]
Knowing Mike, the test code above ought to be sufficient to reproduce the bug. If it can't be reproduced then I'd conclude that the bug has been fixed, so I'm closing this issue.
