### ISSUE TITLE
analyzer fuzz crash: typeArguments called on null in const list for ftype arg default value

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38042]
`C<Function([List mylist = const[]])> c;`

Note: this fails both summary 1 & summary 2

```
NoSuchMethodError: The getter 'typeArguments' was called on null.                
Receiver: null                                                                   
Tried calling: typeArguments                                                     
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)             
#1      ConstantVerifier.visitListLiteral (package:analyzer/src/dart/constant/constant_verifier.dart:151:39)
#2      ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6817:49)  
#3      DefaultFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3068:20)
#4      RecursiveAstVisitor.visitDefaultFormalParameter (package:analyzer/dart/ast/visitor.dart:773:10)
#5      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3063:15)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7667:20)
```

**Comment by kallentu** [comment]
Doesn't seem to crash anymore. Closing.
