### ISSUE TITLE
Analyzer fuzz crash: for element in annotation

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38052]
`V(@({for(v t`

Note: this fails with both summary1 and summary 2

```
Tried calling: []("t")                                                           
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)             
#1      ErrorVerifier._checkDuplicateIdentifier (package:analyzer/src/generated/error_verifier.dart:1776:29)
#2      ErrorVerifier._checkDuplicateIdentifier (package:analyzer/src/generated/error_verifier.dart:1733:9)
#3      ErrorVerifier._checkDuplicateVariables (package:analyzer/src/generated/error_verifier.dart:1860:7)
#4      ErrorVerifier.visitForPartsWithDeclarations (package:analyzer/src/generated/error_verifier.dart:786:7)
#5      ForPartsWithDeclarationsImpl.accept (package:analyzer/src/dart/ast/ast.dart:4671:15)
#6      ForElementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4384:20)
#7      RecursiveAstVisitor.visitForElement (package:analyzer/dart/ast/visitor.dart:881:10)
#8      ForElementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4380:49)   
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7662:20)     
#10     SetOrMapLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8752:15)
```

**Comment by scheglov** [comment]
Cannot reproduce on the bleeding edge.
