### ISSUE TITLE
Analyzer fuzz crash: Invalid const evaluation of malformed binary operators

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38055]
`const t=a.<c/d`

It looks like the `<` is important, and somehow the `a.` is important, and it's important that there is no identifier between the `.` and the `<`. As for `+`, it can be `+`, `*`, etc. Something in the recovery is likely triggering a broken const expression that is likely more general than this specific case.

Note: this fails both summary1 and summary 2

```
NoSuchMethodError: The getter 'type' was called on null.                         
Receiver: null                                                                   
Tried calling: type                                                              
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)             
#1      ConstantVisitor.visitBinaryExpression (package:analyzer/src/dart/constant/evaluation.dart:1046:44)#2      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:997:49)
#3      ConstantVisitor.visitBinaryExpression (package:analyzer/src/dart/constant/evaluation.dart:1047:50)
#4      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:997:49)
#5      ConstantEvaluationEngine.computeConstantValue (package:analyzer/src/dart/constant/evaluation.dart:169:28)
#6      _ConstantWalker.evaluate (package:analyzer/src/dart/constant/compute.dart:74:22)
#7      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2225:13)
#8      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2244:18)   
#9      computeConstants (package:analyzer/src/dart/constant/compute.dart:35:41) 
#10     LibraryAnalyzer._computeConstants (package:analyzer/src/dart/analysis/library_analyzer.dart:254:5)
```

**Comment by kallentu** [comment]
Doesn't seem to crash anymore. Closing.
