### ISSUE TITLE
Analyzer fuzz crash: optional parameter in new function type deeply buried in old function type

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38063]
Note: this only fails in summary1 and therefore is lower priority as we will soon be moving to summary 2

```dart
f(
  void f2(
    Function({T t}) f3()
  )
) {}
```

```
NoSuchMethodError: The getter 'initializer' was called on null.                  
Receiver: null                                                                   
Tried calling: initializer                                                       
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)             
#1      ResolverVisitor.visitDefaultFormalParameter (package:analyzer/src/generated/resolver.dart:4364:17)
#2      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3063:15)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7662:20)     
#4      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4546:17)
#5      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4870:10)
#6      UnifyingAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:3243:59)
#7      ScopedVisitor.visitFormalParameterList (package:analyzer/src/generated/resolver.dart:6009:11)
#8      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4542:49)
#9      GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5457:18)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4870:10)
```

**Comment by srawlins** [comment]
Summary1 is no longer. Closing as obsolete.
