### ISSUE TITLE
Analyzer fuzz crash: wrong number of type arguments supplied

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38072]
```dart
typedef F3<X> = Function<T>();
class A<T> extends A<F3<Z, R>> {}
```

Note: this crash only occurs in summary1 which is soon to be replaced with summary2, making this lower priority.

```
Invalid argument(s): Wrong number of type arguments supplied                     
#0      GenericTypeAliasElementImpl.doInstantiate (package:analyzer/src/dart/element/element.dart:6092:7)
#1      GenericTypeAliasElementForLink.buildType (package:analyzer/src/summary/link.dart:3461:44)
#2      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1471:24)
#3      CompilationUnitElementForLink.resolveTypeRef.getTypeArgument (package:analyzer/src/summary/link.dart:1459:18)
#4      new List.generate (dart:core/list.dart:163:28)                           
#5      ClassElementForLink_Class.buildType (package:analyzer/src/summary/link.dart:868:15)
#6      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1471:24)
#7      CompilationUnitElementForLink.resolveTypeRef.getTypeArgument (package:analyzer/src/summary/link.dart:1459:18)
#8      new List.generate (dart:core/list.dart:163:28)                           
#9      ClassElementForLink_Class.buildType (package:analyzer/src/summary/link.dart:868:15)
#10     CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1471:24)
```

**Comment by srawlins** [comment]
This has been previously reported by users, e.g. https://github.com/dart-lang/sdk/issues/36213

**Comment by srawlins** [comment]
Summary1 is no longer. Closing as obsolete.
