### ISSUE TITLE
analyzer fuzz crash: type parameters called on null

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38075]
another one where I debated not filing because we know there are issues with this system in the analyzer.

Additionally, this only fails summary 1, making it lower priority.

```
typedef F3<X=class A<t c extends A<F3>                                           
NoSuchMethodError: The getter 'typeParameters' was called on null.               
Receiver: null                                                                   
Tried calling: typeParameters                                                    
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)             
#1      GenericTypeAliasElementForLink.unlinkedTypeParams (package:analyzer/src/summary/link.dart:3435:47)
#2      _GenericTypeAliasElementForLink&Object&TypeParameterizedElementMixin.typeParameters (package:analyzer/src/dart/element/element.dart:9964:46)
#3      _FunctionTypeImplLazy.typeFormals (package:analyzer/src/dart/element/type.dart:3602:58)
#4      TypeSystem.typeFormalsAsElements (package:analyzer/src/generated/type_system.dart:2311:19)
#5      Dart2TypeSystem.instantiateToBounds (package:analyzer/src/generated/type_system.dart:355:46)
#6      GenericTypeAliasElementForLink.buildType (package:analyzer/src/summary/link.dart:3459:14)
#7      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1471:24)
#8      CompilationUnitElementForLink.resolveTypeRef.getTypeArgument (package:analyzer/src/summary/link.dart:1459:18)
#9      new List.generate (dart:core/list.dart:163:28)                           
#10     ClassElementForLink_Class.buildType (package:analyzer/src/summary/link.dart:868:15)
```

**Comment by srawlins** [comment]
Only on summary1.
