### ISSUE TITLE
analyzer fuzz crash: Annotated type parameter

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38070]
`l(<@>(`

or perhaps more reasonably

`f(<@C() f>()) {}`

@leafpetersen is this approaching valid code?

Note: this crash is only occurring in summary1 which is soon to be replaced with summary 2, making this lower priority unless it is somehow high importance in the meantime.

```
ried calling: element=null                                                      
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)             
#1      ElementResolver._resolveAnnotations (package:analyzer/src/generated/element_resolver.dart:1835:25)
#2      ElementResolver.resolveMetadata (package:analyzer/src/generated/element_resolver.dart:1771:5)
#3      ElementResolver.visitTypeParameter (package:analyzer/src/generated/element_resolver.dart:879:5)
#4      TypeParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:10242:49)
#5      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4871:10)
#6      UnifyingAstVisitor.visitTypeParameter (package:analyzer/dart/ast/visitor.dart:3460:47)
#7      TypeParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:10242:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7662:20)     
#9      TypeParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10292:21)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4870:10)
```

**Comment by srawlins** [comment]
Summary1 is no longer. Closing as obsolete.
