### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by BugsBunnyBR** [dart-lang/sdk#38071]
When I copy pasted a constructor from a widget to another.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.027071318ff1333fefcf7b4e475c10a8f68ebc0d`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1280x800  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.027071318ff1333fefcf7b4e475c10a8f68ebc0d, server version 1.27.2, error: Analysis failed: /Users/juliocotta/git/schedule_app/lib/com/schedule/app/admin/admin_home_page.dart context: exception_20190828_004722_635
NoSuchMethodError: The getter 'kind' was called on null.
Receiver: null
Tried calling: kind
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Member.kind (package:analyzer/src/dart/element/member.dart:465:40)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:466:40)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:452:7)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:752:7)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8969:49)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6629:13)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:396:31)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6625:49)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7428:12)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#12     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#13     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#14     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#15     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#16     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#18     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#19     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#20     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140:45)
#21     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#22     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:669:24)
#23     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
#24     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#25     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#26     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#27     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#28     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#29     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#30     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#32     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#33     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#34     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140:45)
#35     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#36     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#37     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#38     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#39     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#40     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#41     GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:374:7)
#42     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#43     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8638:18)
#44     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#45     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#46     GeneralizingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:486:51)
#47     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8634:49)
#48     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#49     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#50     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#51     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#52     GeneralizingAstVisitor.visitBlock (package:an...
```

For additional log information, please append the contents of
file:///private/var/folders/8n/dt6g202d30n3wp4ybzd_wtfc0000gn/T/report.txt.

**Comment by scheglov** [comment]
Thank you, I can reproduce it.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/116865
