### ISSUE TITLE
Analyzer fuzz crash: for in loop in field initializer shadowing other field

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38074]
```dart
class C{
  s;
  t = [ for(s in []) ];
}
```

Note: this only occurs in summary 1

```
type 'PrefixedIdentifierImpl' is not a subtype of type 'SimpleIdentifier'        
#0      ExprBuilder._forEachPartsWithIdentifier (package:analyzer/src/summary/expr_builder.dart:652:22)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:366:11)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2545:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5384:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5227:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2225:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2244:18)   
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5660:47)
#8      FunctionElementForLink_Initializer.returnType (package:analyzer/src/summary/link.dart:2894:24)
#9      InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:442:33)
#10     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:312:11)
```

**Comment by srawlins** [comment]
If this only occurred in summary1, can we close?
