### ISSUE TITLE
Analyzer fuzz issue: Element not found in summary

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38085]
These two code examples fail the analyzer fuzz script but don't fail the analyzer itself. They also only fail for summary 1 which is soon to be sunsetted for summary 2.

Filing mostly to ask @scheglov if he thinks there's an underlying cause here we sholud be concerned about in the meantime, but I'm assuming the answer is no.

`class{C()s=C#(`
`class B{e.e{}d=if(`

```
Exception: Element not found in summary: package:test/test.dart;package:test/test.dart;C
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:338:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:359:42)
#2      ExecutableElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:570:13)
#3      MethodElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:1024:44)
#4      MethodElementHandle.isStatic (package:analyzer/src/dart/element/handle.dart:1030:24)
#5      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1137:58)
#6      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:976:15)
#7      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:1001:15)
#8      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1397:30)
#9      _UnitResynthesizer.buildLinkedType (package:analyzer/src/summary/resynthesize.dart:1349:12)
#10     SummaryResynthesizerContext.resolveLinkedType (package:analyzer/src/summary/resynthesize.dart:488:30)
```

**Comment by srawlins** [comment]
Summary1 has left the building.
