### ISSUE TITLE
Analyzer fuzz crash: NoSuchMethodError for getSetter on Enum

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38086]
```dart
enum E {}
v = E.a;
```

Note: this only fails in summary 1 which is soon to be replaced by summary 2 making this lower priority.

```
NoSuchMethodError: Class 'ClassElementForLink_Enum' has no instance method 'getSetter' with matching arguments.
Receiver: Instance of 'ClassElementForLink_Enum'
Tried calling: getSetter("a")
Found: getSetter(String) => PropertyAccessorElement
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      ClassElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:554:48)
#2      ClassElementForLink_Enum.getSetter (package:analyzer/src/dart/element/element.dart:187:27)
#3      ElementResolver._resolveElement (package:analyzer/src/generated/element_resolver.dart:1686:30)
#4      ElementResolver._resolvePropertyAccess (package:analyzer/src/generated/element_resolver.dart:1772:25)
#5      ElementResolver.visitPrefixedIdentifier (package:analyzer/src/generated/element_resolver.dart:667:5)
#6      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8305:49)
#7      ResolverVisitor.visitPrefixedIdentifier (package:analyzer/src/generated/resolver.dart:4276:10)
#8      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8305:49)
#9      ResolverVisitor.visitAssignmentExpression (package:analyzer/src/generated/resolver.dart:3388:11)
#10     AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:747:49)
```

**Comment by srawlins** [comment]
Closing as a summary1-only bug.
