### ISSUE TITLE
Analyzer fuzz crash: empty type parameters for new fn type as type arg

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38087]
`T<void Function<>()> x;`

Note: this only fails for summary1 which is soon to be replaced with summary 2, likely making this lower priority.

```
NoSuchMethodError: The getter 'bound' was called on null.                        
Receiver: null                                                                   
Tried calling: bound                                                             
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)             
#1      ErrorVerifier._checkForTypeParameterSupertypeOfItsBound (package:analyzer/src/generated/error_verifier.dart:5503:30)
#2      ErrorVerifier.visitTypeParameter (package:analyzer/src/generated/error_verifier.dart:1391:5)
#3      TypeParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:10242:49)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7662:20)     
#5      TypeParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10292:21)
#6      RecursiveAstVisitor.visitTypeParameterList (package:analyzer/dart/ast/visitor.dart:1296:10)
#7      ErrorVerifier.visitTypeParameterList (package:analyzer/src/generated/error_verifier.dart:1402:11)
```

**Comment by srawlins** [comment]
Summary1 is no longer. Closing as obsolete.
