### ISSUE TITLE
Analyzer fuzz crash: generic function typed param in initializer

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38097]
Note: user seems to have hit this yesterday: #38024. I found this a few days ago. This is a good example that the fuzzer finds real issues that users will actually hit (at least sometimes).

`var o = (Function<T>(T) f) {};`

Note: this only fails for summary1 which will soon be replaced by summary 2 potentially making this lower priority.

```
RangeError: Invalid type parameter index                                         
#0      _ExecutableElementImpl&ElementImpl&TypeParameterizedElementMixin.getTypeParameterType (package:analyzer/src/dart/element/element.dart:10283:7)
#1      _GenericFunctionTypeElementImpl&ElementImpl&TypeParameterizedElementMixin.getTypeParameterType (package:analyzer/src/dart/element/element.dart:10279:12)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1373:12)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:496:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:9170:14)
```

**Comment by MichaelRFairhurst** [comment]
Note: this is also *valid* code.

**Comment by srawlins** [comment]
Summary1 is no longer. Closing as obsolete.
