### ISSUE TITLE
Parser fuzz assertion failure: Confused by 0x1f, ascii code 31

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38112]
This repro can't be written out because it involves the unprintable character `0x1f` (or 31).

In fact, that's all it is! Just that one character is all that's required to trigger this.

I'm guessing this is an off-by-one error because charcode 32 is the first printable ascii character.

I did not put type-bug because I don't know if this is causing any bugs given that 0x31 is not a valid character in a dart program.

```
'package:front_end/src/fasta/scanner/abstract_scanner.dart': Failed assertion: line 1426 pos 14: 'comments == null || token.isSynthetic || token is ErrorToken': is not true.,
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)    
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)       
#2      AbstractScanner.appendToken (package:front_end/src/fasta/scanner/abstract_scanner.dart:1426:14)
#3      AbstractScanner.unexpected (package:front_end/src/fasta/scanner/abstract_scanner.dart:1764:7)
#4      AbstractScanner.bigSwitch (package:front_end/src/fasta/scanner/abstract_scanner.dart:829:12)
#5      AbstractScanner.bigHeaderSwitch (package:front_end/src/fasta/scanner/abstract_scanner.dart:645:14)
#6      AbstractScanner.tokenize (package:front_end/src/fasta/scanner/abstract_scanner.dart:622:18)
#7      _tokenizeAndRecover (package:front_end/src/fasta/scanner.dart:100:26) 
```

**Comment by MichaelRFairhurst** [comment]
@danrubel

**Comment by MichaelRFairhurst** [comment]
Reopening, I think my original repro was incorrect. Going to confirm before I close.
