### ISSUE TITLE
Analyzer fuzz assertion failure: Expected all legacy types, but got Never (BottomTypeImpl)

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38120]
`m={throw`

This leads to a bug:

```dart
var m = {throw ''};                                                              
                                                                                 
void main() {                                                                    
  m.add(null); // The literal 'null' with type 'Null' isn't of expected type 'Never'
}
```

This is a valid program but we incorrectly reject it.

```
Bad state: Expected all legacy types, but got Never (BottomTypeImpl)             
#0      LegacyTypeAsserter._assertLegacyType (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:161:5)
#1      List.forEach (dart:core-patch/array.dart:110:8)                          
#2      LegacyTypeAsserter._assertLegacyType (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:148:26)
#3      LegacyTypeAsserter.visitVariableDeclaration (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:117:5)
#4      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10517:49)
```

**Comment by lrhn** [comment]
The type of `throw` in legacy code should be `Null`, not `Never`.

If legacy code *directly* refers to `Never` (which is likely going possible, if not before then when we get type aliases), then `Never*` should probably be converted to `Null`.
