### ISSUE TITLE
Dart analysis server

### ISSUE THREAD

**Issue by Jatin9098** [dart-lang/sdk#38134]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: D:\JATINDER KUMAR\Flutter Projects\**\MonitoringDevelopment.dart context: exception_20190830_114923_834
Bad state: Element not contained in compilation unit: Never
#0      getUnitElement (package:analyzer/src/dart/analysis/index.dart:28:3)
#1      _IndexAssembler._getElementInfo.<anonymous closure> (package:analyzer/src/dart/analysis/index.dart:346:44)
#2      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#3      _IndexAssembler._getElementInfo (package:analyzer/src/dart/analysis/index.dart:345:23)
#4      _IndexAssembler.addElementRelation (package:analyzer/src/dart/analysis/index.dart:235:32)
#5      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:499:15)
#6      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:451:7)
#7      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:759:5)
#8      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8976:49)
#9      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#10     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#11     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:55)
#12     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:267:41)
#13     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:617:11)
#14     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#15     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#17     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#18     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#19     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:143:45)
#20     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#21     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#22     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#23     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:55)
#24     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:267:41)
#25     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:617:11)
#26     GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:374:7)
#27     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#28     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#29     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#30     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:55)
#31     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:267:41)
#32     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:617:11)
#33     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#34     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#36     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#37     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#38     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:143:45)
#39     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#40     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#41     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#42     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:55)
#43     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:267:41)
#44     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:617:11)
#45     GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:374:7)
#46     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#47     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#48     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#49     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:55)
#50     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:267:41)...
```

For additional log information, please append the contents of
file://C:\Users\DELL\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Thanks for reporting this issue! This was previously reported as https://github.com/dart-lang/sdk/issues/37652 and was subsequently fixed; the fix should be in upcoming 2.5.0 release.
