### ISSUE TITLE
Printing values to console and quoting

### ISSUE THREAD

**Issue by timothystone** [dart-lang/sdk#38156]
[report.txt](https://github.com/dart-lang/sdk/files/3562703/report.txt)
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6262.58`
- `2.4.0`
- `IU-192.6262.58, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
Internal problem: Unhandled )' in analyzeQuote.
#0      internalProblem (package:front_end/src/fasta/problems.dart:45:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:58:10)
#2      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#3      unescapeString (package:front_end/src/fasta/quote.dart:138:17)
#4      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1370:22)
#5      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#6      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#7      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4239:14)
#8      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#9      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#10     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#11     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5007:15)
#12     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4979:12)
#13     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4960:14)
#14     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4939:13)
#15     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#16     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#17     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#18     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#19     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#20     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3898:13)
#21     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5307:16)
#22     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3715:14)
#23     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3705:20)
#24     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3610:15)
#25     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3259:15)
#26     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3122:15)
#27     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2898:15)
#28     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1783:13)
#29     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1743:14)
#30     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#31     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#32     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#33     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#34     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#35     _File._parse (package:analyzer/src/services/available_declarations.dart:1656:23)
#36     _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#37     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:601:14)
#38     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:636:16)
#39     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:508:7)
#40     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#41     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#42     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#43     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#44     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#45     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#46     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#47     _rootRun (dart:async/zone.dart:1124:13)
#48     _CustomZone.run (dart:async/zone.dart:1021:19)
#49     _runZoned (dart:async/zone.dart:1516:10)
#50     runZoned (dart:async/zone.dart:1463:12)
#51     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#52     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#53     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#54     _AsyncAwaitCompleter.start (dart:async-patch/async_pa...
```

For additional log information, please append the contents of
file:///private/var/folders/yk/m08xxlh903gbm52f8vhv6c4w0000gn/T/report.txt.

**Comment by srawlins** [comment]
This has not been reported since Dart 2.5.0. Please re-open if you see this crash on a recent version of Dart.
