### ISSUE TITLE
We're sorry, you've found a bug in our compiler.

### ISSUE THREAD

**Issue by KumarSunil17** [dart-lang/sdk#38179]
```
 dartdevc -k arguments: --dart-sdk-summary=D:\Android\build-tools\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summa
rize -o C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/pages/dashboard/dashboar
d_page.ddc.js --source-map --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/meta/meta.d
dc.dill=packages/meta/meta --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web
_ui/ui.ddc.dill=packages/flutter_web_ui/ui --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\pack
ages/flutter_web/io.ddc.dill=packages/flutter_web/io --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a3
6b90a\packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space5
9af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions --summar
y=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/foundation.ddc.dill=packages/flutt
er_web/foundation --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/src/phys
ics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space
59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics --summary=C:\Users\Kumar Sunil\AppData\Loca
l\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=C:\Users\Kumar Suni
l\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_mat
h_64 --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/src/animation/animati
on.ddc.dill=packages/flutter_web/src/animation/animation --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107
d1a36b90a\packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4
257-ce32-11e9-9cd2-107d1a36b90a\packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\Kumar Sunil\AppDa
ta\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
--summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/collection/src/comparators.ddc.dill=pa
ckages/collection/src/comparators --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/coll
ection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-c
e32-11e9-9cd2-107d1a36b90a\packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\Kumar Su
nil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/collection/collection.ddc.dill=packages/collection/collection --s
ummary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/animation.ddc.dill=packages/f
lutter_web/animation --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/src/c
upertino/action_sheet.ddc.dill=packages/flutter_web/src/cupertino/action_sheet --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4
257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino --summary=C:\Users\Kumar Sunil\AppData\Local
\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/material.ddc.dill=packages/flutter_web/material --summary=C:\Users\Kum
ar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/utils/pojos/user.ddc.dill=packages/fitwallet
_admin/utils/pojos/user --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admi
n/utils/constants/constants.ddc.dill=packages/fitwallet_admin/utils/constants/constants --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_s
pace59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/utils/apiServicess/AllUserSession.ddc.dill=packages/fitwallet_admin/utils/apiServ
icess/AllUserSession --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/u
tils/constants/page_route.ddc.dill=packages/fitwallet_admin/utils/constants/page_route --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_sp
ace59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/pages/drawer_pages/user_page/user_datasource.ddc.dill=packages/fitwallet_admin/pag
es/drawer_pages/user_page/user_datasource --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packa
ges/fitwallet_admin/pages/drawer_pages/user_page/users_page.ddc.dill=packages/fitwallet_admin/pages/drawer_pages/user_page/users_page --summary=C:\
Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/pedantic/pedantic.ddc.dill=packages/pedantic/pedant
ic --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/charcode/ascii.ddc.dill=packages/ch
arcode/ascii --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/charcode/html_entity.ddc.
dill=packages/charcode/html_entity --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/cha
rcode/charcode.ddc.dill=packages/charcode/charcode --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b
90a\packages/path/path.ddc.dill=packages/path/path --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b
90a\packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=C:\Users\Kumar Sunil\App
Data\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/source_span/source_span.ddc.dill=packages/source_span/source_span --summ
ary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/string_scanner/src/eager_span_scanner.ddc.di
ll=packages/string_scanner/src/eager_span_scanner --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b9
0a\packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-c
e32-11e9-9cd2-107d1a36b90a\packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --summary=C:\Users\Kumar Sunil\AppData\Local\
Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/http/src/base_client.ddc.dill=packages/http/src/base_client --summary=C:\Users\Kuma
r Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/http/http.ddc.dill=packages/http/http --summary=C:\Users\Kuma
r Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/utils/apiServicess/LoginSession.ddc.dill=pack
ages/fitwallet_admin/utils/apiServicess/LoginSession --packages=file:///C:/Users/Kumar%20Sunil/AppData/Local/Temp/kernel_builder_a50232f4-ce32-11e9
-9cd2-107d1a36b90a/.packages --module-name=packages/fitwallet_admin/pages/dashboard/dashboard_page --multi-root-scheme=org-dartlang-app --multi-roo
t=. --track-widget-creation --inline-source-map --libraries-file=file:///D:/Android/build-tools/flutter/bin/cache/dart-sdk/lib/libraries.json packa
ge:fitwallet_admin/pages/login/login_page.dart package:fitwallet_admin/pages/dashboard/dashboard_page.dart
    dart --version: 2.5.0-dev.4.0.flutter-35382f9b14 (Wed Aug 28 18:50:51 2019 +0000) on "windows_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2207:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:393:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:271:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:276:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




[SEVERE]build_web_compilers:ddc on web/main.ddc.module (cached): Error compiling dartdevc module:fitwallet_admin|web/main.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=D:\Android\build-tools\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summa
rize -o C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\web/main.ddc.js --source-map --summary=C:\Users\K
umar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/meta/meta.ddc.dill=packages/meta/meta --summary=C:\Users\K
umar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui --su
mmary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/io.ddc.dill=packages/flutter_w
eb/io --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/typed_data/typed_buffers.ddc.dil
l=packages/typed_data/typed_buffers --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fl
utter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scrat
ch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation --summary=C:\Users\Kumar Suni
l\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=C:\Us
ers\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/vector_math/vector_math_64.ddc.dill=packages/vector_m
ath/vector_math_64 --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/src/phy
sics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_spac
e59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics --summary=C:\Users\Kumar Sunil\AppData\Loc
al\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/
animation --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/collection/src/utils.ddc.dil
l=packages/collection/src/utils --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/collec
tion/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9
cd2-107d1a36b90a\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\Users\Kumar Sunil\AppData\Local\Te
mp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=C:\
Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/collection/src/priority_queue.ddc.dill=packages/col
lection/src/priority_queue --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/collection/
src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce
32-11e9-9cd2-107d1a36b90a\packages/collection/collection.ddc.dill=packages/collection/collection --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\
scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation --summary=C:\Users\Kumar S
unil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutter_web/src/cupertino/action_sheet.ddc.dill=packages/flutter
_web/src/cupertino/action_sheet --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/flutte
r_web/cupertino.ddc.dill=packages/flutter_web/cupertino --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d
1a36b90a\packages/flutter_web/material.ddc.dill=packages/flutter_web/material --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af42
57-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/utils/constants/page_route.ddc.dill=packages/fitwallet_admin/utils/constants/page_route --s
ummary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/pages/drawer_pages/home_p
age/home_page.ddc.dill=packages/fitwallet_admin/pages/drawer_pages/home_page/home_page --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_sp
ace59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/utils/pojos/user.ddc.dill=packages/fitwallet_admin/utils/pojos/user --summary=C:\U
sers\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/utils/constants/constants.ddc.dill=p
ackages/fitwallet_admin/utils/constants/constants --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b9
0a\packages/fitwallet_admin/utils/apiServicess/AllUserSession.ddc.dill=packages/fitwallet_admin/utils/apiServicess/AllUserSession --summary=C:\User
s\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/pages/drawer_pages/user_page/user_datas
ource.ddc.dill=packages/fitwallet_admin/pages/drawer_pages/user_page/user_datasource --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_spac
e59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/pages/drawer_pages/user_page/users_page.ddc.dill=packages/fitwallet_admin/pages/draw
er_pages/user_page/users_page --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/pedantic
/pedantic.ddc.dill=packages/pedantic/pedantic --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\p
ackages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d
1a36b90a\packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af42
57-ce32-11e9-9cd2-107d1a36b90a\packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scr
atch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/path/path.ddc.dill=packages/path/path --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scr
atch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_g
lyph_set --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/source_span/source_span.ddc.d
ill=packages/source_span/source_span --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/s
tring_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scra
tch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=C:\Users\Kumar Sunil
\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --
summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/http/src/base_client.ddc.dill=packages/h
ttp/src/base_client --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/http/http.ddc.dill
=packages/http/http --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/ut
ils/apiServicess/LoginSession.ddc.dill=packages/fitwallet_admin/utils/apiServicess/LoginSession --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\s
cratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin/pages/dashboard/dashboard_page.ddc.dill=packages/fitwallet_admin/pages/da
shboard/dashboard_page --summary=C:\Users\Kumar Sunil\AppData\Local\Temp\scratch_space59af4257-ce32-11e9-9cd2-107d1a36b90a\packages/fitwallet_admin
/main.ddc.dill=packages/fitwallet_admin/main --packages=file:///C:/Users/Kumar%20Sunil/AppData/Local/Temp/kernel_builder_a50232f7-ce32-11e9-9cd2-10
7d1a36b90a/.packages --module-name=web/main --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libra
ries-file=file:///D:/Android/build-tools/flutter/bin/cache/dart-sdk/lib/libraries.json web/main.dart
    dart --version: 2.5.0-dev.4.0.flutter-35382f9b14 (Wed Aug 28 18:50:51 2019 +0000) on "windows_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2207:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:393:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:271:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:276:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




[SEVERE] Failed after 678ms
```

**Comment by lrhn** [comment]
Same issue as #38180
