### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by sinegovsky-ivan** [dart-lang/sdk#38173]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-192.6262.59`
- `2.2.0`
- `WS-192.6262.59, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900, 1080x1920, 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.2.0, server version , FATAL error: FormatException: Could not find an option named "enable-completion-model".
#0      Parser.validate (package:args/src/parser.dart:261:21)
#1      Parser.parseLongOption (package:args/src/parser.dart:250:7)
#2      Parser.parse (package:args/src/parser.dart:90:11)
#3      ArgParser.parse (package:args/src/arg_parser.dart:307:45)
#4      CommandLineParser.parse (package:analysis_server/src/server/driver.dart:101:15)
#5      Driver.start (package:analysis_server/src/server/driver.dart:323:33)
#6      main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/92/9r4fzjtn36zb1vzcxlq6hts54970jv/T/report.txt.

**Comment by srawlins** [comment]
This issue hasn't been reported since Dart 2.4.0. Please re-open if you see this crash on a recent version of Dart.
