### ISSUE TITLE
update_static_error_tests.dart throws on file deletion, probably doesn't have to

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#38189]
This looks like the script `update_static_error_tests.dart` is at times expecting a file to exist, trying to delete it, and then throwing if it doesn't exist. Maybe it could just accept that the file does not exist?

```dart
> dart pkg/test_runner/tool/update_static_error_tests.dart -u "language_2/name_conflicts/name_conflict_test.dart"                                                                                                                                                                                          [13:49]
tests/language_2/name_conflicts/name_conflict_test.dart (Running CFE...)Unhandled exception:
FileSystemException: Cannot delete file, path = 'tests/language_2/name_conflicts/name_conflict_test.dart.dill' (OS Error: No such file or directory, errno = 2)
#0      _File._delete.<anonymous closure> (dart:io/file_impl.dart:291:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

It looks like the following will do, and it will preserve the property that we get the exception when there is a problem with the permissions or ownership:

```
@@ -203,7 +203,8 @@ Future<List<StaticError>> _runCfe(String path, List<String> options) async {
 
   // Running the above command generates a dill file next to the test, which we
   // don't want, so delete it.
-  await File("$path.dill").delete();
+  var dillFile = File("$path.dill");
+  if (await dillFile.exists()) await dillFile.delete();
 
   return errors;
 }
```

@munificent, WDYT?

**Comment by munificent** [comment]
It's safer to catch the FileSystemException exception thrown by `delete()`. Checking for `exists()` first and then calling `delete()` still potentially exposes the code to a race condition where the file is deleted between those two steps.
