### ISSUE TITLE
analyzer fuzz crash: parameterizing extension name for inference

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38195]
```dart
var c=B<T>();
extension B {}
```

@bwilkerson @pq 

```
Unhandled exception:
NoSuchMethodError: Class 'ExtensionElementForLink' has no instance getter 'typeParameters'.
Receiver: Instance of 'ExtensionElementForLink'
Tried calling: typeParameters
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ExtensionElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:2698:48)
#2      ExtensionElementForLink.typeParameters (package:analyzer/src/dart/element/element.dart:10219:34)
#3      ExtensionMemberResolver.setOverrideReceiverContextType (package:analyzer/src/dart/resolver/extension_member_resolver.dart:154:34)
#4      ResolverVisitor.visitExtensionOverride (package:analyzer/src/generated/resolver.dart:3809:35)
#5      ExtensionOverrideImpl.accept (package:analyzer/src/dart/ast/ast.dart:4011:20)
#6      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2568:16)
#7      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5499:36)
#8      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5342:7)
#9      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2230:13)
#10     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2249:18)
#11     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5778:47)
#12     TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5327:48)
#13     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1645:16)
#14     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3985:12)
#15     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3685:15)
#16     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3625:7)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2230:13)
#18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2249:18)
#19     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3658:42)
#20     Linker.link (package:analyzer/src/summary/link.dart:4190:35)
#21     _relink (package:analyzer/src/summary/link.dart:312:74)
#22     link (package:analyzer/src/summary/link.dart:126:3)
#23     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:220:25)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#25     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:219:12)
#26     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:98:7)
#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1439:29)
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1246:30)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:927:33)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1931:24)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1865:5)
#34     main (file:///usr/local/google/home/mfairhurst/dust/example/analyzer/bin/analyzer_fuzz.dart:65:13)
<asynchronous suspension>
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by bwilkerson** [comment]
This is a summary1 issue, and we are now officially on summary2.  As far as I can tell, this is no longer occurring.
