### ISSUE TITLE
Analyzer fuzz crash: CompilationUnitElementInBuildUnit has no method inheritsCovariant

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38201]
This only fails in summary 1.

```dart
class C<T> {
  var o = (R f(void this({p = null}))) {};
}
```

I'm not really sure what's going on here. `f` must have a return type, and `f`'s first parameter must be this function type named `this`, even though that's illegal, and the `this` function must have a named parameter.

There may be a less contrived repro though.

```
Unhandled exception:
NoSuchMethodError: Class 'CompilationUnitElementInBuildUnit' has no instance method 'inheritsCovariant' with matching arguments.
Receiver: Instance of 'CompilationUnitElementInBuildUnit'
Tried calling: inheritsCovariant(0)
Found: inheritsCovariant(int) => bool
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      CompilationUnitElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:1356:48)
#2      CompilationUnitElementInBuildUnit.inheritsCovariant (package:analyzer/src/dart/element/element.dart:9798:8)
#3      ParameterElementImpl.inheritsCovariant (package:analyzer/src/dart/element/element.dart:8808:12)
#4      ParameterElementImpl.isCovariant (package:analyzer/src/dart/element/element.dart:8872:34)
#5      _TypeSubstitutor._parameterElement (package:analyzer/src/dart/element/type_algebra.dart:458:46)
#6      _TypeSubstitutor.visitFunctionType.<anonymous closure> (package:analyzer/src/dart/element/type_algebra.dart:352:14)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#8      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#9      _TypeSubstitutor.visitFunctionType (package:analyzer/src/dart/element/type_algebra.dart:353:8)
#10     DartTypeVisitor.visit (package:analyzer/src/dart/element/type_visitor.dart:39:22)
```

**Comment by bwilkerson** [comment]
Given that summary2 has now been enabled on bleeding edge, I suspect we can close this.
