### ISSUE TITLE
analyzer fuzz crash: binary operator on extension name

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38203]
```dart
extension E on A {}
var x = E < b;
```

@pq @bwilkerson 

```
Unhandled exception:
NoSuchMethodError: The getter 'isDartCoreInt' was called on null.
Receiver: null
Tried calling: isDartCoreInt
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      TypeSystem.refineBinaryExpressionType (package:analyzer/src/generated/type_system.dart:2618:18)
#2      Dart2TypeSystem.refineBinaryExpressionType (package:analyzer/src/generated/type_system.dart:804:18)
#3      StaticTypeAnalyzer.visitBinaryExpression (package:analyzer/src/generated/static_type_analyzer.dart:420:32)
#4      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:997:49)
#5      ResolverVisitor.visitBinaryExpression (package:analyzer/src/generated/resolver.dart:3472:10)
#6      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:997:49)
#7      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2568:16)
#8      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5499:36)
#9      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5342:7)
#10     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2230:13)
#11     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2249:18)
#12     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5778:47)
#13     TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5327:48)
#14     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1645:16)
#15     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3985:12)
#16     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3685:15)
#17     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3625:7)
#18     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2230:13)
#19     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2249:18)
#20     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3658:42)
```

**Comment by bwilkerson** [comment]
It looks like `E` doesn't have a static type. We probably need to generate a diagnostic saying that it isn't valid to reference an extension in this location (when resolving `E`) and then give it a type of `dynamic` to prevent follow-on errors.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/116055
