### ISSUE TITLE
Analyzer fails for a project, showing that anything defined in another file is undefined

### ISSUE THREAD

**Issue by Klikini** [dart-lang/sdk#38249]
This crash has been happening for a couple years, but WebStorm finally offered a link to report it so here it is!

Repo that causes this crash: https://gitlab.com/ChildrenOfUr/coUclient

Please let me know if you need any more information...having the analyzer work on this project again would be amazing.

---

Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-192.6262.59`
- `2.4.0`
- `WS-192.6262.59, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Linux(amd64) v5.2.10-1-default, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, FATAL error: Failed to handle request: {id: 23, method: edit.getFixes, params: {file: /home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart, offset: 8755}, clientRequestTime: 1567796182428}
Invalid argument(s): Is a part: /home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart
#0      AnalysisDriver.getResolvedLibrary (package:analyzer/src/dart/analysis/driver.dart:849:7)
#1      AnalysisSessionImpl.getResolvedLibrary (package:analyzer/src/dart/analysis/session.dart:137:20)
#2      AnalysisSessionHelper._getResolvedLibrary (package:analyzer/src/dart/analysis/session_helper.dart:74:30)
<asynchronous suspension>
#3      AnalysisSessionHelper.getElementDeclaration (package:analyzer/src/dart/analysis/session_helper.dart:41:33)
<asynchronous suspension>
#4      FixProcessor._addFix_createField (package:analysis_server/src/services/correction/fix_internal.dart:1855:29)
<asynchronous suspension>
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:477:13)
<asynchronous suspension>
#6      DartFixContributor._computeFixAllFixes (package:analysis_server/src/services/correction/fix_internal.dart:114:53)
<asynchronous suspension>
#7      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:71:37)
<asynchronous suspension>
#8      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:649:46)
<asynchronous suspension>
#9      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:751:14)
<asynchronous suspension>
#10     EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:278:32)
<asynchronous suspension>
#11     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:381:9)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:317:50)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:316:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.ru...
```

Contents of file:///tmp/report.txt:

```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, FATAL error: Failed to handle request: {id: 23, method: edit.getFixes, params: {file: /home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart, offset: 8755}, clientRequestTime: 1567796182428}
Invalid argument(s): Is a part: /home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart
#0      AnalysisDriver.getResolvedLibrary (package:analyzer/src/dart/analysis/driver.dart:849:7)
#1      AnalysisSessionImpl.getResolvedLibrary (package:analyzer/src/dart/analysis/session.dart:137:20)
#2      AnalysisSessionHelper._getResolvedLibrary (package:analyzer/src/dart/analysis/session_helper.dart:74:30)
<asynchronous suspension>
#3      AnalysisSessionHelper.getElementDeclaration (package:analyzer/src/dart/analysis/session_helper.dart:41:33)
<asynchronous suspension>
#4      FixProcessor._addFix_createField (package:analysis_server/src/services/correction/fix_internal.dart:1855:29)
<asynchronous suspension>
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:477:13)
<asynchronous suspension>
#6      DartFixContributor._computeFixAllFixes (package:analysis_server/src/services/correction/fix_internal.dart:114:53)
<asynchronous suspension>
#7      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:71:37)
<asynchronous suspension>
#8      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:649:46)
<asynchronous suspension>
#9      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:751:14)
<asynchronous suspension>
#10     EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:278:32)
<asynchronous suspension>
#11     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:381:9)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:317:50)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:316:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#55     _StreamController._add (dart:async/stream_controller.dart:640:7)
#56     _StreamController.add (dart:async/stream_controller.dart:586:5)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#58     _rootRunUnary (dart:async/zone.dart:1136:13)
#59     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#63     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#64     _StreamController._add (dart:async/stream_controller.dart:640:7)
#65     _StreamController.add (dart:async/stream_controller.dart:586:5)
#66     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1335:33)
#67     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:856:14)
#68     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#69     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#70     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

1567796129507 <= {"event":"analysis.errors","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/systems/commands.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"f
1567796129508 <= {"event":"analysis.errors","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/systems/quest_manager.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location
1567796129510 <= {"event":"analysis.errors","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/systems/gps.dart","errors":[{"severity":"ERROR","type":"STATIC_TYPE_WARNING","location":{"f
1567796129511 <= {"event":"analysis.errors","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/systems/clock.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"file
1567796129512 <= {"event":"analysis.errors","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/systems/weather.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"fi
1567796129513 <= {"event":"analysis.errors","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/systems/homestreet.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/ho
1567796129514 <= {"event":"analysis.errors","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/ui_templates/interactions_menu.dart","errors":[{"severity":"ERROR","type":"STATIC_W
1567796129517 <= {"event":"analysis.errors","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/useitem_window.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING",
1567796129517 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1567796175828 => {"id":"18","method":"analysis.setPriorityFiles","params":{"files":["/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart"]},"clientRequestTime":156779617
1567796175829 => {"id":"19","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart"],"CLOSING_
1567796175829 <= {"id":"18"}
1567796175835 <= {"id":"19"}
1567796175837 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1567796175941 <= {"event":"analysis.errors","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart","errors":[{"severity":"ERROR","type":"STATIC_TYPE_WARN
1567796175981 <= {"event":"analysis.highlights","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart","regions":[{"type":"DIRECTIVE","offset":0,"length"
1567796176022 <= {"event":"analysis.navigation","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart","regions":[{"offset":8,"length":9,"targets":[0]},{
1567796176034 <= {"event":"analysis.closingLabels","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart","labels":[]}}
1567796176064 <= {"event":"analysis.outline","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart","kind":"PART","libraryName":"couclient","outline":{"e
1567796176071 <= {"event":"analysis.overrides","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart","overrides":[]}}
1567796176073 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1567796176551 => {"id":"20","method":"edit.getAssists","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart","offset":9328,"length":0},"clientRequestTim
1567796177748 <= {"id":"20","result":{"assists":[]}}
1567796178844 => {"id":"21","method":"edit.getFixes","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart","offset":8959},"clientRequestTime":1567796178
1567796178936 <= {"id":"21","result":{"fixes":[{"error":{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.da
1567796179769 <= {"event":"analysis.implemented","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart","classes":[],"members":[]}}
1567796181046 => {"id":"22","method":"edit.getFixes","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart","offset":8959},"clientRequestTime":1567796181
1567796181164 <= {"id":"22","result":{"fixes":[{"error":{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.da
1567796182428 => {"id":"23","method":"edit.getFixes","params":{"file":"/home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart","offset":8755},"clientRequestTime":1567796182
1567796182494 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 23, method: edit.getFixes, params: {file: /home/andy/Documents/CoU/VCS/coUclient/lib/src/dis
```

(The JSON lines really cut off like that in the text file!)

Here's what this looks like:

![image](https://user-images.githubusercontent.com/1693960/64455303-f97d3800-d0b2-11e9-8cc8-4bd1fe4155a4.png)

This project compiles fine using `webdev`, but the analyzer just doesn't like it.

**Comment by srawlins** [comment]
Does this occur when you move a file? To a new directory, perhaps?

**Comment by Klikini** [comment]
@srawlins No, I didn't move anything. I can reproduce it with freshly cloned repos.

I think it's the size of the project because it works with our other projects that have the same structure but far fewer files.

**Comment by srawlins** [comment]
Does the crash always reference /home/andy/Documents/CoU/VCS/coUclient/lib/src/display/windows/mailbox_window.dart ?

**Comment by Klikini** [comment]
No, it seems to be random files. I just opened the project again (after upgrading the SDK to 2.5.0), analyzed, opened a file, and got this:

```
Dart analysis server, SDK version 2.4.1, server version 1.27.2, FATAL error: Failed to handle request: {id: 16, method: edit.getFixes, params: {file: /home/andy/Documents/CoU/VCS/coUclient/lib/src/display/overlays/overlay.dart, offset: 351}, clientRequestTime: 1568172369300}
Invalid argument(s): Is a part: /home/andy/Documents/CoU/VCS/coUclient/lib/src/display/overlays/overlay.dart
#0      AnalysisDriver.getResolvedLibrary (package:analyzer/src/dart/analysis/driver.dart:715:7)
#1      AnalysisSessionImpl.getResolvedLibrary (package:analyzer/src/dart/analysis/session.dart:143:20)
#2      AnalysisSessionHelper._getResolvedLibrary (package:analyzer/src/dart/analysis/session_helper.dart:74:30)
<asynchronous suspension>
#3      AnalysisSessionHelper.getElementDeclaration (package:analyzer/src/dart/analysis/session_helper.dart:41:33)
<asynchronous suspension>
#4      FixProcessor._addFix_createField (package:analysis_server/src/services/correction/fix_internal.dart:1856:29)
<asynchronous suspension>
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:477:13)
<asynchronous suspension>
#6      DartFixContributor._computeFixAllFixes (package:analysis_server/src/services/correction/fix_internal.dart:114:53)
<asynchronous suspension>
#7      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:71:37)
<asynchronous suspension>
#8      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:651:46)
<asynchronous suspension>
#9      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:757:14)
<asynchronous suspension>
#10     EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:280:32)
<asynchronous suspension>
#11     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:383:9)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded...
```

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.8; please re-open if you see this in a recent version of Dart/Flutter.
