### ISSUE TITLE
kernel fuzz crash: wrapInProblem was called on null

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38253]
```dart
var a = (){
  g f(){
    return;
  }
}
```

```
Unhandled exception:
Crash when compiling null,
at character offset null:
NoSuchMethodError: The method 'wrapInProblem' was called on null.
Receiver: null
Tried calling: wrapInProblem(Instance of 'NullLiteral', Instance of 'MessageCode', 1)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ClosureContext.checkValidReturn (package:front_end/src/fasta/type_inference/type_inferrer.dart:268:46)
#2      ClosureContext.handleReturn (package:front_end/src/fasta/type_inference/type_inferrer.dart:359:9)
#3      InferenceVisitor.visitReturnJudgment (package:front_end/src/fasta/kernel/inference_visitor.dart:1779:20)
#4      ReturnJudgment.acceptInference (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1183:20)
#5      ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1553:24)
#6      InferenceVisitor.visitBlockJudgment (package:front_end/src/fasta/kernel/inference_visitor.dart:103:16)
#7      BlockJudgment.acceptInference (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:283:20)
#8      ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1553:24)
#9      TypeInferrerImpl.inferLocalFunction (package:front_end/src/fasta/type_inference/type_inferrer.dart:1925:5)
#10     InferenceVisitor.visitFunctionNodeJudgment (package:front_end/src/fasta/kernel/inference_visitor.dart:478:21)
```

**Comment by Nolence** [comment]
Trying to move a medium sized project to semi-null safety I encountered this issue. Not sure where it's coming from either
