### ISSUE TITLE
DDC build: _IoFileSystemEntity.readAsBytes  throws no such file or directory

### ISSUE THREAD

**Issue by venshine** [dart-lang/sdk#38263]
```
    dartdevc -k arguments: --dart-sdk-summary=/Users/fengwenxuan/Work/flutter/bin/cache/dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/DXMFlutterWeb/qr_page.ddc.js --source-map --summary=packages/DXMFlutterWeb/QrModel.ddc.dill=packages/DXMFlutterWeb/QrModel --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui --summary=packages/flutter_web/io.ddc.dill=packages/flutter_web/io --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions --summary=packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation --summary=packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics --summary=packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation --summary=packages/flutter_web/src/cupertino/action_sheet.ddc.dill=packages/flutter_web/src/cupertino/action_sheet --summary=packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino --summary=packages/flutter_web/material.ddc.dill=packages/flutter_web/material --summary=packages/DXMFlutterWeb/Utils.ddc.dill=packages/DXMFlutterWeb/Utils --packages=file:///var/folders/v6/zg_qh0d56wz55fwmy2vhplxncvxx_y/T/kernel_builder_nJdUxn/.packages --module-name=packages/DXMFlutterWeb/qr_page --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///Users/fengwenxuan/Work/flutter/bin/cache/dart-sdk/lib/libraries.json package:DXMFlutterWeb/qr_page.dart
    dart --version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "macos_x64"

FileSystemException(uri=file://packages/DXMFlutterWeb/QrModel.ddc.dill; message=No such file or directory)
#0      _IoFileSystemEntity.readAsBytes (package:front_end/src/api_prototype/standard_file_system.dart:68:7)
<asynchronous suspension>
#1      MultiRootFileSystemEntity.readAsBytes (package:build_integration/file_system/multi_root.dart:78:61)
<asynchronous suspension>
#2      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:229:61)
<asynchronous suspension>
#3      _compile (package:dev_compiler/src/kernel/command.dart:246:27)
<asynchronous suspension>
#4      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#5      compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#6      _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     _CompilerWorker.performRequest (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#12     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#18     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




[SEVERE]build_web_compilers:ddc on lib/main.ddc.module (cached): Error creating DXMFlutterWeb|lib/main.ddc.dillError creating kernel summary for module:DXMFlutterWeb|lib/main.ddc.dill

Response:--dart-sdk-summary=file:///Users/fengwenxuan/Work/flutter/bin/cache/dart-sdk/lib/_internal/ddc_sdk.dill --output=/private/var/folders/v6/zg_qh0d56wz55fwmy2vhplxncvxx_y/T/scratch_spaceEd6lu6/packages/DXMFlutterWeb/main.ddc.dill --packages-file=file:///var/folders/v6/zg_qh0d56wz55fwmy2vhplxncvxx_y/T/kernel_builder_ddWtyX/.packages --multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///Users/fengwenxuan/Work/flutter/bin/cache/dart-sdk/lib/libraries.json --reuse-compiler-result --use-incremental-compiler --input-summary=org-dartlang-app:///packages/flutter_web/material.ddc.dill --input-summary=org-dartlang-app:///packages/meta/meta.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_web_ui/ui.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_web/foundation.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/vector_math_64.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_web/cupertino.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_web/animation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_web/src/foundation/assertions.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/hash.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_web/src/cupertino/action_sheet.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_web/src/animation/animation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_web/physics.ddc.dill --input-summary=org-dartlang-app:///packages/collection/collection.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_web/io.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_buffers.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_web/src/physics/clamped_simulation.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/algorithms.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/utils.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/iterable_zip.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/comparators.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/priority_queue.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/canonicalized_map.ddc.dill --source=package:DXMFlutterWeb/main.dart
FileSystemException(uri=org-dartlang-app:///packages/flutter_web/material.ddc.dill; message=File not found)
#0      initializeIncrementalCompiler (package:front_end/src/api_unstable/bazel_worker.dart:183:13)
<asynchronous suspension>
#1      computeKernel (file:///b/s/w/ir/k/src/third_party/dart/utils/bazel/kernel_worker.dart:250:19)
<asynchronous suspension>
#2      KernelWorker.performRequest (file:///b/s/w/ir/k/src/third_party/dart/utils/bazel/kernel_worker.dart:58:26)
<asynchronous suspension>
#3      AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _runZoned (dart:async/zone.dart:1516:10)
#7      runZoned (dart:async/zone.dart:1463:12)
#8      AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#9      main (file:///b/s/w/ir/k/src/third_party/dart/utils/bazel/kernel_worker.dart:35:30)
<asynchronous suspension>
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




[SEVERE]build_web_compilers:ddc on lib/store_page.ddc.module (cached): Error compiling dartdevc module:DXMFlutterWeb|lib/store_page.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
```

**Comment by vsmenon** [comment]
@jakemac53 @natebosch 

I haven't seen this variant yet (see https://github.com/dart-lang/sdk/issues/38102).

**Comment by jakemac53** [comment]
Hmm ya me either. We definitely shouldn't even attempt to compile if any transitive dep is missing (due to failed compilation or otherwise). We would get a failure when computing the digest for it which is well before this.

We do use a temp directory so I don't know if some operating systems are cleaning that up in the middle of our build or something? Or there is possibly some race condition somewhere in the temp file creation but I don't see one.

**Comment by vsmenon** [comment]
What can we do on the DDC side to fail more gracefully?  E.g., if `initializeIncrementalCompiler` throws, should we catch and return an exit code?  Can `build` give a better message?

Similar for kernel_worker?

**Comment by vsmenon** [comment]
Let's merge this as well:

https://github.com/dart-lang/sdk/issues/38102
