### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by abnormalbbk** [dart-lang/sdk#38267]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-60-generic, screens 1366x768, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: /home/abnormalbbk/freelance/personal/musa/flutter-foodapp/lib/network/api_service.dart context: exception_20190909_171414_780
NoSuchMethodError: The getter 'isInSdk' was called on null.
Receiver: null
Tried calling: isInSdk
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:530:62)
#2      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:398:15)
#3      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#4      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#6      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#7      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#8      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#9      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#10     Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1065:12)
#11     TypeNameResolver.resolveTypeName (package:analyzer/src/generated/resolver.dart:6363:33)
#12     TypeResolverVisitor.visitTypeName (package:analyzer/src/generated/resolver.dart:8152:23)
#13     TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10184:49)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#15     TypeArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10071:16)
#16     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3339:10)
#17     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8121:11)
#18     UnifyingAstVisitor.visitTypeArgumentList (package:analyzer/dart/ast/visitor.dart:3439:53)
#19     TypeArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10067:49)
#20     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7245:21)
#21     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3339:10)
#22     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8121:11)
#23     UnifyingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:3324:53)
#24     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7239:49)
#25     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8644:18)
#26     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3339:10)
#27     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8121:11)
#28     UnifyingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:3380:51)
#29     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8640:49)
#30     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#31     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1121:17)
#32     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3339:10)
#33     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8121:11)
#34     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3116:31)
#35     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:5658:13)
#36     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1117:49)
#37     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1076:13)
#38     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3339:10)
#39     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8121:11)
#40     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3119:55)
#41     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5669:13)
#42     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1072:49)
#43     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7116:12)
#44     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3339:10)
#45     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:8121:11)
#46     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3321:55)
#47     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:6112:11)
#48     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:6105:7)
#49     TypeResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:7963:11)
#50     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7107:49)
#51     TypeResolverVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:7814:16)
#52     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/re...
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by srawlins** [comment]
This hasn't been reported since Dart 2.5.0. Please re-open if you see this with a recent version of Dart.
