### ISSUE TITLE
New get_cpu_samples_rpc_test failing on mac

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#38264]
Test is currently failing on vm-kernel-mac-debug-simdbc64, vm-kernel-mac-debug-x64, vm-kernel-mac-release-x64, and pkg-mac-release. Approving for now and assigning the issue to bkyoni since he added the functionality and test.

[Example logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8903000256977234032/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0):

```
/==============================================================================================\
| pkg/vm_service/test/get_cpu_samples_rpc_test is new and failed (RuntimeError, expected Pass) |
\==============================================================================================/

--- Command "vm" (took 06.000305s):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart-sdk/bin/dart --enable_asserts --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/pkg/vm_service/test/get_cpu_samples_rpc_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: (setUpAll)[0m
** Launching SERVICE_TEST_TESTEE=true xcodebuild/ReleaseX64/dart-sdk/bin/dart --disable-service-auth-codes --profiler --profiler=true --profile-vm=false --enable_asserts --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --enable-vm-service:0 /b/s/w/ir/cache/builder/sdk/pkg/vm_service/test/get_cpu_samples_rpc_test.dart
>testee>out> Observatory listening on http://127.0.0.1:49545/
>testee>out> Testee doing something.
>testee>out> Testee did something.
** Signaled to run test queries on http://127.0.0.1:49545/
>testee>out>
Done loading VM
00:03 [32m+0[0m: get_cpu_samples_rpc_test.dart[0m
get_cpu_samples_rpc_test.dart [1/1]
00:03 [32m+0[0m[31m -1[0m: get_cpu_samples_rpc_test.dart [1m[31m[E][0m[0m
  Expected: a value greater than <10>
    Actual: <0>
     Which: is not a value greater than <10>
  Should have many samples

  package:test_api/src/frontend/expect.dart 153:30        fail
  package:test_api/src/frontend/expect.dart 147:3         _expect
  package:test_api/src/frontend/expect.dart 59:3          expect
  pkg/vm_service/test/get_cpu_samples_rpc_test.dart 36:3  checkSamples
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                            _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 80:23                 _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart               Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1124:13                            _rootRun
  dart:async/zone.dart 1021:19                            _CustomZone.run
  dart:async/zone.dart 1516:10                            _runZoned
  dart:async/zone.dart 1463:12                            runZoned
  package:test_api/src/backend/invoker.dart 247:5         Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 166:33       Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                            _rootRun
  dart:async/zone.dart 1021:19                            _CustomZone.run
  dart:async/zone.dart 1516:10                            _runZoned
  dart:async/zone.dart 1463:12                            runZoned
  package:test_api/src/backend/declarer.dart 165:13       Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                            _CustomZone.registerCallback
  dart:async/zone.dart 962:22                             _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                             new Timer
  dart:async/timer.dart 87:9                              Timer.run
  dart:async/future.dart 174:11                           new Future
  package:test_api/src/backend/invoker.dart 399:21        Invoker._onRun.<fn>.<fn>.<fn>

00:03 [32m+0[0m[31m -1[0m: (tearDownAll)[0m
All service tests completed successfully.
** Killing script
00:03 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m

stderr:
Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

--- Re-run this test:
python tools/test.py -n unittest-asserts-release-mac pkg/vm_service/test/get_cpu_samples_rpc_test
```

**Comment by bkonyi** [comment]
Looks like this is related to some issue with signal blocking on MacOS:

- https://github.com/dart-lang/sdk/issues/36908
- https://github.com/dart-lang/sdk/issues/26416

This doesn't look like it's something that can be easily resolved, so we'll just have to leave this marked as failing.
