### ISSUE TITLE
analyzer fuzz crash: mixin on itself with type parameters

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38278]
This only fails for summary1. Still, filing on the unlikely chance that we have to roll back summary2.

```dart
class C<T>{}
class C=A with C;
```

Looks like a user has hit this before: #37341

This is great. We now know we can close that issue once we are confident in summary2.

```
Unhandled exception:
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ErrorVerifier._checkMixinInference (package:analyzer/src/generated/error_verifier.dart:5419:36)
#2      ErrorVerifier._checkClassInheritance (package:analyzer/src/generated/error_verifier.dart:1495:7)
#3      ErrorVerifier.visitClassTypeAlias (package:analyzer/src/generated/error_verifier.dart:575:7)
#4      ClassTypeAliasImpl.accept (package:analyzer/src/dart/ast/ast.dart:1806:49)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#6      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#7      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#8      ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:599:11)
#9      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#10     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:404:10)
```

**Comment by srawlins** [comment]
Summary1 is no longer. Closing as obsolete.
