### ISSUE TITLE
Analyzer fuzz crash: invalid typedef reference in set literal

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38275]
```dart
typedef F1=F;
F1 f(){}
var o = {f()};
```

Note: this fails on both summary1 and summary2.

Another note: without the `{}`s, on summary 1 it produces #38075

```
Unhandled exception:
NoSuchMethodError: The getter 'syntheticReturnType' was called on null.
Receiver: null
Tried calling: syntheticReturnType
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      GenericTypeAliasElementForLink.returnType (package:analyzer/src/summary/link.dart:3423:41)
#2      _FunctionTypeImplLazy.baseReturnType (package:analyzer/src/dart/element/type.dart:3279:57)
#3      _FunctionTypeImplLazy.returnType (package:analyzer/src/dart/element/type.dart:3370:36)
#4      UnknownInferredType.isUnknown (package:analyzer/src/generated/type_system.dart:2976:29)
#5      UnknownInferredType.isKnown (package:analyzer/src/generated/type_system.dart:2965:42)
#6      GenericInferrer._chooseTypeFromConstraints (package:analyzer/src/generated/type_system.dart:1492:29)
#7      GenericInferrer._inferTypeParameterFromAll (package:analyzer/src/generated/type_system.dart:1594:18)
#8      GenericInferrer.infer (package:analyzer/src/generated/type_system.dart:1339:30)
#9      Dart2TypeSystem.inferGenericFunctionOrType2 (package:analyzer/src/generated/type_system.dart:337:21)
#10     Dart2TypeSystem.inferGenericFunctionOrType (package:analyzer/src/generated/type_system.dart:264:25)
```

**Comment by scheglov** [comment]
Cannot reproduce with summary2 on the bleeding edge.
