### ISSUE TITLE
dart2js/kernel fuzz crash:

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38271]
`o(=:` and `c{@`

```
Unhandled exception:
Crash when compiling file://case.dart,
at character offset 3:
RangeError: Value not in range: 5
#0      _StringBase.substring (dart:core-patch/string_patch.dart:386:7)
#1      Source.getTextLine (package:kernel/ast.dart:6577:25)
#2      SourceFile.getLocationMessage (package:compiler/src/io/source_file.dart:148:42)
#3      FormattingDiagnosticHandler.report (package:compiler/src/source_file_provider.dart:296:20)
#4      CompilerImpl.callUserHandler.<anonymous closure> (package:compiler/src/apiimpl.dart:179:17)
#5      CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#6      CompilerImpl.callUserHandler (package:compiler/src/apiimpl.dart:178:23)
#7      CompilerImpl._reportDiagnosticMessage (package:compiler/src/apiimpl.dart:170:7)
#8      CompilerImpl.reportDiagnostic (package:compiler/src/apiimpl.dart:155:5)
#9      CompilerDiagnosticReporter.reportDiagnostic (package:compiler/src/compiler.dart:732:14)
#10     CompilerDiagnosticReporter.reportDiagnosticInternal (package:compiler/src/compiler.dart:727:5)
```

Note how this one says "at character offset null"

`t=(){@`

Unhandled exception:
Crash when compiling null,
at character offset null:
RangeError: Value not in range: 7
#0      _StringBase.substring (dart:core-patch/string_patch.dart:386:7)
#1      Source.getTextLine (package:kernel/ast.dart:6577:25)
#2      SourceFile.getLocationMessage (package:compiler/src/io/source_file.dart:148:42)
#3      FormattingDiagnosticHandler.report (package:compiler/src/source_file_provider.dart:296:20)
#4      CompilerImpl.callUserHandler.<anonymous closure> (package:compiler/src/apiimpl.dart:179:17)
#5      CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#6      CompilerImpl.callUserHandler (package:compiler/src/apiimpl.dart:178:23)
#7      CompilerImpl._reportDiagnosticMessage (package:compiler/src/apiimpl.dart:170:7)
#8      CompilerImpl.reportDiagnostic (package:compiler/src/apiimpl.dart:155:5)
#9      CompilerDiagnosticReporter.reportDiagnostic (package:compiler/src/compiler.dart:732:14)
#10     CompilerDiagnosticReporter.reportDiagnosticInternal (package:compiler/src/compiler.dart:727:5)
```

**Comment by vsmenon** [comment]
same here - @johnniwinther - cfe issue?

**Comment by johnniwinther** [comment]
I think it is both. CFE shouldn't crash on out-of-range indices and dart2js shouldn't provide out-of-range positions.
