### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by Jrank2013** [dart-lang/sdk#38273]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6603.28`
- `2.6.0-edge.ec7ec4ecf7fb388c8bc6d074acb65e7d5605ff05`
- `IU-192.6603.28, JRE 11.0.3+12-b304.56x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2560x1440, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.ec7ec4ecf7fb388c8bc6d074acb65e7d5605ff05, server version 1.27.3, error: NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      RangeFactory.node (package:analyzer_plugin/utilities/range_factory.dart:69:33)
#2      InlineMethodRefactoringImpl._prepareMethodParts (package:analysis_server/src/services/refactoring/inline_method.dart:396:53)
#3      InlineMethodRefactoringImpl.checkInitialConditions (package:analysis_server/src/services/refactoring/inline_method.dart:294:22)
<asynchronous suspension>
#4      _RefactoringManager._init (package:analysis_server/src/edit/edit_domain.dart:1202:36)
<asynchronous suspension>
#5      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:988:13)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1500:12)
#10     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:985:5)
#11     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:863:24)
#12     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:393:16)
#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:335:45)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#15     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:331:50)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1500:12)
#20     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:330:5)
#21     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#23     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#24     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#32     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#33     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#34     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#35     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#37     _rootRunUnary (dart:async/zone.dart:1132:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#42     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#43     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#44     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#45     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#46     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#47     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#48     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#56     _StreamController._add (dart:async/stream_controller.dart:640:7)
#57     _StreamController.add (dart:async/stream_controller.dart:586:5)
#58     _Socket._onData (dart:io-patch/socket_pat...
```

For additional log information, please append the contents of
file:///private/var/folders/sj/j7924lrj5sv89xy21m_3j9pc0000gn/T/report.txt.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/116881
