### ISSUE TITLE
dart2js/kernel fuzz crash: RangeError in getLocation

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38270]
`od(=:`

```
Unhandled exception:
Crash when compiling file://case.dart,
at character offset 4:
RangeError (offset): Invalid value: Not in range 0..6, inclusive: 7
#0      RangeError.checkValueInInterval (dart:core/errors.dart:281:7)
#1      Source.getLocation (package:kernel/ast.dart:6597:16)
#2      SourceFile.getLocationMessage (package:compiler/src/io/source_file.dart:116:48)
#3      FormattingDiagnosticHandler.report (package:compiler/src/source_file_provider.dart:296:20)
#4      CompilerImpl.callUserHandler.<anonymous closure> (package:compiler/src/apiimpl.dart:179:17)
#5      CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
```

**Comment by vsmenon** [comment]
@johnniwinther - not sure if this is a dart2js issue or cfe one.

**Comment by johnniwinther** [comment]
I think it is both. CFE shouldn't crash on out-of-range indices and dart2js shouldn't provide out-of-range positions.

**Comment by osa1** [comment]
Simple non-fuzz program that triggers the same crash in current main branch (60fec9c7204):

```dart
void main() {
  print("".runtimeType());
}
```

**Comment by sigmundch** [comment]
Good repro!

Turns out the issue here is that the CFE is either reporting the error at the wrong start location or using an inappropriate length.

Today it uses the start location where the `(` starts after the property name, but includes the length of the property name `runtimeType` as the length of the error.

On the example above, this overflows beyond the buffer size. If you add extra text on the same line, you can see the error shifted. That is:

Input:
```dart
void main() {
  print("".runtimeType());//extra buffer of text
}
```

Reports this error on the VM:
```
repro.dart:2:23: Error: 'runtimeType' isn't a function or method and can't be invoked.
  print("".runtimeType());//extra buffer of text
                      ^^^^^^^^^^^
```

This originates here: https://github.com/dart-lang/sdk/blob/69b4bc43abb49b7e25c0793bac72efa8a3eb7470/pkg/front_end/lib/src/fasta/type_inference/inference_visitor_base.dart#L4120

My guess is that the start offset here needs to be adjusted, but I defer to the CFE team to decide (FYI @johnniwinther)
