### ISSUE TITLE
DDK build crash when loading empty dill file

### ISSUE THREAD

**Issue by DuEyE** [dart-lang/sdk#38272]
```
[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 1.1s
[INFO]
[INFO] Starting daemon...
[WARNING] Configuring `build_vm_compilers:entrypoint` in target `smartmirror_dueye:smartmirror_dueye` but this is not a known Builder
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 648ms
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 7.7s
[SEVERE] Configuring `build_vm_compilers:entrypoint` in target `smartmirror_dueye:smartmirror_dueye` but this is not a known Builder
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 648ms
[INFO]
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 7.7s
[INFO]
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 2ms
[INFO]
[INFO] Registering build targets...
[INFO] Starting initial build...
[INFO] Starting resource servers...
[INFO] Serving DevTools at http://127.0.0.1:53487
[INFO] Serving `web` on http://127.0.0.1:53478
[INFO] About to build [web]...
[INFO] Running build...
[INFO] Running build completed, took 450ms
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 367ms
[SEVERE]build_web_compilers:entrypoint on web/main.dart (cached): AssetNotFoundException: smartmirror_dueye|web/main.ddc.js
[SEVERE]build_web_compilers:ddc on web/main.ddc.module (cached): Error compiling dartdevc module:smartmirror_dueye|web/main.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\Users\benutzer\AppData\Local\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\web/main.ddc.js --source-map --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/smartmirror_dueye/WeatherCurrent.ddc.dill=packages/smartmirror_dueye/WeatherCurrent --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/meta/meta.ddc.dill=packages/meta/meta --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/io.ddc.dill=packages/flutter_web/io --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/collection.ddc.dill=packages/collection/collection --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/src/cupertino/action_sheet.ddc.dill=packages/flutter_web/src/cupertino/action_sheet --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/material.ddc.dill=packages/flutter_web/material --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/pedantic/pedantic.ddc.dill=packages/pedantic/pedantic --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/path/path.ddc.dill=packages/path/path --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/source_span/source_span.ddc.dill=packages/source_span/source_span --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/http/src/base_client.ddc.dill=packages/http/src/base_client --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/http/http.ddc.dill=packages/http/http --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/smartmirror_dueye/weatherWidget.ddc.dill=packages/smartmirror_dueye/weatherWidget --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/date_time_patterns.ddc.dill=packages/intl/date_time_patterns --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/intl.ddc.dill=packages/intl/intl --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/date_symbol_data_local.ddc.dill=packages/intl/date_symbol_data_local --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/smartmirror_dueye/clock.ddc.dill=packages/smartmirror_dueye/clock --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/smartmirror_dueye/main.ddc.dill=packages/smartmirror_dueye/main --packages=file:///C:/Users/benutzer/AppData/Local/Temp/kernel_builder_6f2f5f51-d316-11e9-bcae-1c1b0d222c1f/.packages --module-name=web/main --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///C:/Users/benutzer/AppData/Local/flutter/bin/cache/dart-sdk/lib/libraries.json web/main.dart
    dart --version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"

RangeError (index): Index out of range: no indices are valid: 0
[38;5;244m#0      Uint8List.[]  (dart:typed_data-patch/typed_data_patch.dart:2188:7)[39;49m
[38;5;248m#1      BinaryBuilder.readByte[39;49m
[38;5;248m#2      BinaryBuilder.readUint32[39;49m
[38;5;248m#3      BinaryBuilder.readComponent[39;49m
[38;5;248m#4      ProcessedOptions.loadComponent[39;49m
[38;5;248m#5      initializeIncrementalCompiler[39;49m
<asynchronous suspension>
[38;5;248m#6      _compile  (package:dev_compiler/src/kernel/command.dart:246:27)[39;49m
<asynchronous suspension>
[38;5;248m#7      compile  (package:dev_compiler/src/kernel/command.dart:42:18)[39;49m
<asynchronous suspension>
[38;5;248m#8      compile  (package:dev_compiler/src/compiler/shared_command.dart:401:12)[39;49m
[38;5;248m#9      _CompilerWorker.performRequest.<anonymous closure>  (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:39)[39;49m
[38;5;244m#10     _rootRun  (dart:async/zone.dart:1124:13)[39;49m
[38;5;244m#11     _CustomZone.run  (dart:async/zone.dart:1021:19)[39;49m
[38;5;244m#12     _runZoned  (dart:async/zone.dart:1516:10)[39;49m
[38;5;244m#13     runZoned  (dart:async/zone.dart:1463:12)[39;49m
[38;5;248m#14     _CompilerWorker.performRequest  (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:24)[39;49m
<asynchronous suspension>
[38;5;248m#15     AsyncWorkerLoop.run.<anonymous closure>[39;49m
[38;5;244m#16     _rootRun  (dart:async/zone.dart:1124:13)[39;49m
[38;5;244m#17     _CustomZone.run  (dart:async/zone.dart:1021:19)[39;49m
[38;5;244m#18     _runZoned  (dart:async/zone.dart:1516:10)[39;49m
[38;5;244m#19     runZoned  (dart:async/zone.dart:1463:12)[39;49m
[38;5;248m#20     AsyncWorkerLoop.run[39;49m
<asynchronous suspension>
[38;5;248m#21     main  (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)[39;49m
<asynchronous suspension>
[38;5;244m#22     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:297:32)[39;49m
[38;5;244m#23     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)[39;49m

[SEVERE]build_web_compilers:ddc on lib/main.ddc.module (cached): Error compiling dartdevc module:smartmirror_dueye|lib/main.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\Users\benutzer\AppData\Local\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/smartmirror_dueye/main.ddc.js --source-map --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/meta/meta.ddc.dill=packages/meta/meta --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/io.ddc.dill=packages/flutter_web/io --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/collection/collection.ddc.dill=packages/collection/collection --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/src/cupertino/action_sheet.ddc.dill=packages/flutter_web/src/cupertino/action_sheet --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/flutter_web/material.ddc.dill=packages/flutter_web/material --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/date_time_patterns.ddc.dill=packages/intl/date_time_patterns --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/intl.ddc.dill=packages/intl/intl --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/intl/date_symbol_data_local.ddc.dill=packages/intl/date_symbol_data_local --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/smartmirror_dueye/clock.ddc.dill=packages/smartmirror_dueye/clock --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/smartmirror_dueye/WeatherCurrent.ddc.dill=packages/smartmirror_dueye/WeatherCurrent --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/pedantic/pedantic.ddc.dill=packages/pedantic/pedantic --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/path/path.ddc.dill=packages/path/path --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/source_span/source_span.ddc.dill=packages/source_span/source_span --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/http/src/base_client.ddc.dill=packages/http/src/base_client --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/http/http.ddc.dill=packages/http/http --summary=C:\Users\benutzer\AppData\Local\Temp\scratch_spaced28a796d-d313-11e9-bcae-1c1b0d222c1f\packages/smartmirror_dueye/weatherWidget.ddc.dill=packages/smartmirror_dueye/weatherWidget --packages=file:///C:/Users/benutzer/AppData/Local/Temp/kernel_builder_6f2f5f50-d316-11e9-bcae-1c1b0d222c1f/.packages --module-name=packages/smartmirror_dueye/main --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///C:/Users/benutzer/AppData/Local/flutter/bin/cache/dart-sdk/lib/libraries.json package:smartmirror_dueye/main.dart
    dart --version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"

RangeError (index): Index out of range: no indices are valid: 0
[38;5;244m#0      Uint8List.[]  (dart:typed_data-patch/typed_data_patch.dart:2188:7)[39;49m
[38;5;248m#1      BinaryBuilder.readByte[39;49m
[38;5;248m#2      BinaryBuilder.readUint32[39;49m
[38;5;248m#3      BinaryBuilder.readComponent[39;49m
[38;5;248m#4      ProcessedOptions.loadComponent[39;49m
[38;5;248m#5      initializeIncrementalCompiler[39;49m
<asynchronous suspension>
[38;5;248m#6      _compile  (package:dev_compiler/src/kernel/command.dart:246:27)[39;49m
<asynchronous suspension>
[38;5;248m#7      compile  (package:dev_compiler/src/kernel/command.dart:42:18)[39;49m
<asynchronous suspension>
[38;5;248m#8      compile  (package:dev_compiler/src/compiler/shared_command.dart:401:12)[39;49m
[38;5;248m#9      _CompilerWorker.performRequest.<anonymous closure>  (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:39)[39;49m
[38;5;244m#10     _rootRun  (dart:async/zone.dart:1124:13)[39;49m
[38;5;244m#11     _CustomZone.run  (dart:async/zone.dart:1021:19)[39;49m
[38;5;244m#12     _runZoned  (dart:async/zone.dart:1516:10)[39;49m
[38;5;244m#13     runZoned  (dart:async/zone.dart:1463:12)[39;49m
[38;5;248m#14     _CompilerWorker.performRequest  (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:24)[39;49m
<asynchronous suspension>
[38;5;248m#15     AsyncWorkerLoop.run.<anonymous closure>[39;49m
[38;5;244m#16     _rootRun  (dart:async/zone.dart:1124:13)[39;49m
[38;5;244m#17     _CustomZone.run  (dart:async/zone.dart:1021:19)[39;49m
[38;5;244m#18     _runZoned  (dart:async/zone.dart:1516:10)[39;49m
[38;5;244m#19     runZoned  (dart:async/zone.dart:1463:12)[39;49m
[38;5;248m#20     AsyncWorkerLoop.run[39;49m
<asynchronous suspension>
[38;5;248m#21     main  (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)[39;49m
<asynchronous suspension>
[38;5;244m#22     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:297:32)[39;49m
[38;5;244m#23     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)[39;49m

[SEVERE] Failed after 897ms
```

**Comment by mraleph** [comment]
Looks like an attempt to load an empty kernel file to me /cc @vsmenon

**Comment by vsmenon** [comment]
FYI - @jakemac53 @natebosch 

Merging into:

https://github.com/dart-lang/sdk/issues/38102
