### ISSUE TITLE
analyzer fuzz crash: extension cast to class fails

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38277]
This only fails for summary1. I'm filing but we should only fix if for some reason we have to roll back summary2.

```dart
o=E1.`v
extension E1{{
```

```
type 'ExtensionElementForLink' is not a subtype of type 'ClassElementForLink_Class'
#0      CompilationUnitElementInBuildUnit.addReference (package:analyzer/src/summary/link.dart:1577:33)
#1      _createLinkedType (package:analyzer/src/summary/link.dart:237:42)
#2      CompilationUnitElementInBuildUnit._storeLinkedType (package:analyzer/src/summary/link.dart:1686:31)
#3      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5326:25)
#4      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1645:16)
#5      LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3985:12)
#6      LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3685:15)
#7      LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3625:7)
#8      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2230:13)
```

**Comment by srawlins** [comment]
Summary1 is no longer. Closing as obsolete.
