### ISSUE TITLE
Crash when compiling null, at character offset null: type 'DillClassBuilder' is not a subtype of type 'SourceClassBuilder'

### ISSUE THREAD

**Issue by Elvis5566** [dart-lang/sdk#38289]
I have a web project and path dependent package 'common_all'.
I also use [inject_generator](https://github.com/google/inject.dart) for DI,
and define common_all in common_all_module.dart
command `pub run build_runner build` can generate code I need successfully.
However, if I import 'package:common_all/common_all_module.dart' in web/main.dart.
I'll get an error:
```
[SEVERE] build_web_compilers:entrypoint on web/main.dart (cached):

AssetNotFoundException: common_all|lib/common_all_module.ddc.js
[SEVERE] build_web_compilers:ddc on package:common_all/common_all_module.ddc.module (cached):
Error compiling dartdevc module:common_all|lib/common_all_module.ddc.js
```
I've tried inject_generator in a smaller web project,
and it works well, do I need to provide other packages I used to help to analyze this issue?

Thanks

* Dart SDK Version: 2.4.1, MacOSX
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
build_runner: 1.6.9
build_web_compilers: 2.3.0

```
    dartdevc -k arguments: --dart-sdk-summary=/usr/local/Cellar/dart/2.4.1/libexec/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/common_all/common_all_module.ddc.js --source-map --summary=packages/common_all/enum/enum.ddc.dill=packages/common_all/enum/enum --summary=packages/common_all/enum/staff_type.ddc.dill=packages/common_all/enum/staff_type --summary=packages/json_annotation/json_annotation.ddc.dill=packages/json_annotation/json_annotation --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/geo/geo.ddc.dill=packages/geo/geo --summary=packages/common_all/json/json_base.ddc.dill=packages/common_all/json/json_base --summary=packages/common_all/json/coordinate.ddc.dill=packages/common_all/json/coordinate --summary=packages/common_all/orm/mixin/broadcast_message.ddc.dill=packages/common_all/orm/mixin/broadcast_message --summary=packages/common_all/json/channel_broadcast_content.ddc.dill=packages/common_all/json/channel_broadcast_content --summary=packages/validators/src/helpers.ddc.dill=packages/validators/src/helpers --summary=packages/validators/validators.ddc.dill=packages/validators/validators --summary=packages/inject/inject.ddc.dill=packages/inject/inject --summary=packages/common_all/image_downloader.ddc.dill=packages/common_all/image_downloader --summary=packages/common_all/socket/socket_message.ddc.dill=packages/common_all/socket/socket_message --summary=packages/common_all/json/socket_message/broadcast_command.ddc.dill=packages/common_all/json/socket_message/broadcast_command --summary=packages/common_all/misc/vd_size.ddc.dill=packages/common_all/misc/vd_size --summary=packages/common_all/photo_info.ddc.dill=packages/common_all/photo_info --summary=packages/common_all/service/vd_response.ddc.dill=packages/common_all/service/vd_response --summary=packages/common_all/service/client.ddc.dill=packages/common_all/service/client --summary=packages/common_all/service/service.ddc.dill=packages/common_all/service/service --summary=packages/common_all/service/endpoint.ddc.dill=packages/common_all/service/endpoint --summary=packages/common_all/app_info.ddc.dill=packages/common_all/app_info --summary=packages/common_all/json/lat_lng_bound.ddc.dill=packages/common_all/json/lat_lng_bound --summary=packages/common_all/util/poly_util.ddc.dill=packages/common_all/util/poly_util --summary=packages/common_all/socket/socket_message_handler.ddc.dill=packages/common_all/socket/socket_message_handler --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/moor/src/runtime/exceptions.ddc.dill=packages/moor/src/runtime/exceptions --summary=packages/moor/sqlite_keywords.ddc.dill=packages/moor/sqlite_keywords --summary=packages/moor/moor.ddc.dill=packages/moor/moor --summary=packages/common_all/orm/converter/lat_lng_bound_converter.ddc.dill=packages/common_all/orm/converter/lat_lng_bound_converter --summary=packages/pedantic/pedantic.ddc.dill=packages/pedantic/pedantic --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=packages/path/path.ddc.dill=packages/path/path --summary=packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=packages/source_span/source_span.ddc.dill=packages/source_span/source_span --summary=packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --summary=packages/http/src/base_client.ddc.dill=packages/http/src/base_client --summary=packages/http/http.ddc.dill=packages/http/http --summary=packages/common_all/service/client_http.ddc.dill=packages/common_all/service/client_http --summary=packages/common_all/json/socket_message/join_channel_command.ddc.dill=packages/common_all/json/socket_message/join_channel_command --summary=packages/common_all/json/socket_message/leave_channel_command.ddc.dill=packages/common_all/json/socket_message/leave_channel_command --summary=packages/common_all/json/reset_password_param.ddc.dill=packages/common_all/json/reset_password_param --summary=packages/google_maps_webservice/src/core.ddc.dill=packages/google_maps_webservice/src/core --summary=packages/google_maps_webservice/directions.ddc.dill=packages/google_maps_webservice/directions --summary=packages/common_all/enum/route_plan_mode.ddc.dill=packages/common_all/enum/route_plan_mode --summary=packages/google_maps_webservice/places.ddc.dill=packages/google_maps_webservice/places --summary=packages/common_all/orm/mixin/has_avatar.ddc.dill=packages/common_all/orm/mixin/has_avatar --summary=packages/common_all/orm/mixin/message_sender.ddc.dill=packages/common_all/orm/mixin/message_sender --summary=packages/common_all/operation_queue.ddc.dill=packages/common_all/operation_queue --summary=packages/common_all/enum/participant_state.ddc.dill=packages/common_all/enum/participant_state --summary=packages/common_all/json/login_param.ddc.dill=packages/common_all/json/login_param --summary=packages/uuid/uuid_util.ddc.dill=packages/uuid/uuid_util --summary=packages/convert/convert.ddc.dill=packages/convert/convert --summary=packages/crypto/crypto.ddc.dill=packages/crypto/crypto --summary=packages/uuid/uuid.ddc.dill=packages/uuid/uuid --summary=packages/common_all/service/location_iq_manager.ddc.dill=packages/common_all/service/location_iq_manager --summary=packages/common_all/orm/converter/list_coordinate_converter.ddc.dill=packages/common_all/orm/converter/list_coordinate_converter --summary=packages/mobx/mobx.ddc.dill=packages/mobx/mobx --summary=packages/common_all/store/page_store.ddc.dill=packages/common_all/store/page_store --summary=packages/common_all/orm/converter/coordinate_converter.ddc.dill=packages/common_all/orm/converter/coordinate_converter --summary=packages/common_all/json/socket_message/join_route_channel_command.ddc.dill=packages/common_all/json/socket_message/join_route_channel_command --summary=packages/common_all/enum/delegate_type.ddc.dill=packages/common_all/enum/delegate_type --summary=packages/common_all/json/google_map_elevation.ddc.dill=packages/common_all/json/google_map_elevation --summary=packages/common_all/util/uuid_util.ddc.dill=packages/common_all/util/uuid_util --summary=packages/common_all/json/follow_status.ddc.dill=packages/common_all/json/follow_status --summary=packages/common_all/service/vd_response_state.ddc.dill=packages/common_all/service/vd_response_state --summary=packages/common_all/json/socket_message/join_organization_channel_command.ddc.dill=packages/common_all/json/socket_message/join_organization_channel_command --summary=packages/common_all/orm/mixin/column_deleted.ddc.dill=packages/common_all/orm/mixin/column_deleted --summary=packages/common_all/enum/gender.ddc.dill=packages/common_all/enum/gender --summary=packages/event_bus/event_bus.ddc.dill=packages/event_bus/event_bus --summary=packages/common_all/enum/setting_unit_type.ddc.dill=packages/common_all/enum/setting_unit_type --summary=packages/common_all/orm/converter/vd_json_converter.ddc.dill=packages/common_all/orm/converter/vd_json_converter --summary=packages/common_all/device_info.ddc.dill=packages/common_all/device_info --summary=packages/common_all/generated/assets.ddc.dill=packages/common_all/generated/assets --summary=packages/common_all/enum/weather.ddc.dill=packages/common_all/enum/weather --summary=packages/common_all/enum/staff_state.ddc.dill=packages/common_all/enum/staff_state --summary=packages/common_all/orm/mixin/column_dirty.ddc.dill=packages/common_all/orm/mixin/column_dirty --summary=packages/common_all/vd_string_parser.ddc.dill=packages/common_all/vd_string_parser --summary=packages/common_all/orm/converter/list_string_converter.ddc.dill=packages/common_all/orm/converter/list_string_converter --summary=packages/common_all/event_bus/event_bus_list_update.ddc.dill=packages/common_all/event_bus/event_bus_list_update --summary=packages/common_all/json/location_iq_reverse_geocoding_response.ddc.dill=packages/common_all/json/location_iq_reverse_geocoding_response --summary=packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols --summary=packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols --summary=packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data --summary=packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules --summary=packages/intl/intl.ddc.dill=packages/intl/intl --summary=packages/common_all/util/date_time_util.ddc.dill=packages/common_all/util/date_time_util --summary=packages/common_all/orm/converter/route_plan_mode_converter.ddc.dill=packages/common_all/orm/converter/route_plan_mode_converter --summary=packages/common_all/event_bus/event_bus_object_update.ddc.dill=packages/common_all/event_bus/event_bus_object_update --summary=packages/common_all/store/date_time_picker_store.ddc.dill=packages/common_all/store/date_time_picker_store --summary=packages/common_all/util/list_util.ddc.dill=packages/common_all/util/list_util --summary=packages/common_all/json/sign_up_param.ddc.dill=packages/common_all/json/sign_up_param --summary=packages/common_all/util/http_util.ddc.dill=packages/common_all/util/http_util --summary=packages/common_all/vd_persistent.ddc.dill=packages/common_all/vd_persistent --summary=packages/logging/logging.ddc.dill=packages/logging/logging --summary=packages/common_all/vd_logger.ddc.dill=packages/common_all/vd_logger --summary=packages/common_all/util/json_util.ddc.dill=packages/common_all/util/json_util --summary=packages/common_all/orm/converter/participant_state_converter.ddc.dill=packages/common_all/orm/converter/participant_state_converter --summary=packages/common_all/orm/converter/gender_converter.ddc.dill=packages/common_all/orm/converter/gender_converter --summary=packages/common_all/orm/converter/staff_state_converter.ddc.dill=packages/common_all/orm/converter/staff_state_converter --summary=packages/common_all/json/org_request_to_join_param.ddc.dill=packages/common_all/json/org_request_to_join_param --summary=packages/common_all/json/socket_message/join_event_channel_command.ddc.dill=packages/common_all/json/socket_message/join_event_channel_command --summary=packages/common_all/orm/converter/staff_type_converter.ddc.dill=packages/common_all/orm/converter/staff_type_converter --summary=packages/common_all/enum/stop_tag.ddc.dill=packages/common_all/enum/stop_tag --summary=packages/common_all/enum/default_image_folder.ddc.dill=packages/common_all/enum/default_image_folder --summary=packages/common_all/json/s3_policy.ddc.dill=packages/common_all/json/s3_policy --summary=packages/async/async.ddc.dill=packages/async/async --summary=packages/common_all/service/s3_server.ddc.dill=packages/common_all/service/s3_server --summary=packages/common_all/json/join_channel_response.ddc.dill=packages/common_all/json/join_channel_response --summary=packages/common_all/orm/converter/delegate_type_converter.ddc.dill=packages/common_all/orm/converter/delegate_type_converter --packages=file:///var/folders/5b/k29x63jd4_99610nychktt7w0000gn/T/kernel_builder_wFUqyi/.packages --module-name=packages/common_all/common_all_module --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///usr/local/Cellar/dart/2.4.1/libexec/lib/libraries.json package:common_all/orm/staff.g.dart package:common_all/orm/staff_conversation.dart package:common_all/orm/simple_user.g.dart package:common_all/store/staff_profile_store.g.dart package:common_all/store/participant_store.dart package:common_all/orm/saved_route.g.dart package:common_all/json/converter.dart package:common_all/orm/route_like.g.dart package:common_all/store/login_store.dart package:common_all/db/vd_database.dart package:common_all/orm/staff_message.dart package:common_all/vd_date_time.dart package:common_all/store/login_store.g.dart package:common_all/orm/weather_forecast.dart package:common_all/json/update_object_response.dart package:common_all/store/participant_store.g.dart package:common_all/util/photo_util.dart package:common_all/orm/db_route.dart package:common_all/orm/staff.dart package:common_all/orm/time.g.dart package:common_all/store/forgot_password_store.dart package:common_all/orm/team.dart package:common_all/orm/mixin/message.dart package:common_all/orm/payment.dart package:common_all/orm/workout_summary.g.dart package:common_all/orm/sos.dart package:common_all/orm/staff_conversation_member.dart package:common_all/orm/time.dart package:common_all/json/db_stop.g.dart package:common_all/orm/mixin/db_save.dart package:common_all/orm/mixin/column_updated_at.dart package:common_all/orm/event.g.dart package:common_all/store/profile_store.dart package:common_all/orm/payment.g.dart package:common_all/orm/follow_stat.dart package:common_all/orm/user.g.dart package:common_all/service/google_map_manager.dart package:common_all/orm/ride_summary.g.dart package:common_all/orm/hidden_event.dart package:common_all/store/setting_store.g.dart package:common_all/store/profile_store.g.dart package:common_all/db/vd_database.g.dart package:common_all/orm/converter/db_stop_converter.dart package:common_all/socket/handler/ride_summary_update_handler.dart package:common_all/orm/organization.g.dart package:common_all/socket/handler/staff_message_update_handler.dart package:common_all/json/get_organizations_response.dart package:common_all/orm/staff_conversation.g.dart package:common_all/socket/handler/join_event_channel_response_handler.dart package:common_all/orm/mixin/column_comment_read_time.dart package:common_all/orm/mixin/task/has_task.dart package:common_all/json/user_response.g.dart package:common_all/store/sign_up_store.g.dart package:common_all/orm/achievement.g.dart package:common_all/store/sos_assign_store.g.dart package:common_all/orm/mixin/task/upload_photo_list_to_s3_task.dart package:common_all/orm/team_member.g.dart package:common_all/json/user_response.dart package:common_all/store/team_creator_store.dart package:common_all/orm/mixin/column_created_at.dart package:common_all/json/login_response.dart package:common_all/store/stop_editor_store.dart package:common_all/orm/staff_message.g.dart package:common_all/store/request_sent_store.g.dart package:common_all/store/forgot_password_store.g.dart package:common_all/store/team_store.dart package:common_all/socket/handler/join_route_channel_response_handler.dart package:common_all/orm/workout_summary.dart package:common_all/orm/participant.dart package:common_all/orm/staff_conversation_member.g.dart package:common_all/store/select_org_store.dart package:common_all/store/team_creator_store.g.dart package:common_all/socket/handler/notification_update_handler.dart package:common_all/orm/mixin/task/upload_photo_to_s3_task.dart package:common_all/orm/hidden_event.g.dart package:common_all/orm/user_message.dart package:common_all/store/event_editor_store.g.dart package:common_all/store/setting_store.dart package:common_all/store/route_editor_store.dart package:common_all/orm/team_member.dart package:common_all/store/staff_profile_store.dart package:common_all/orm/user.dart package:common_all/orm/user_conversation.g.dart package:common_all/store/route_editor_store.g.dart package:common_all/orm/organization.dart package:common_all/store/sign_up_store.dart package:common_all/orm/db_route.g.dart package:common_all/store/event_route_editor_base_store.dart package:common_all/orm/mixin/db_dirty_save.dart package:common_all/json/login_response.g.dart package:common_all/socket/handler/list_socket_message_handler.dart package:common_all/orm/achievement.dart package:common_all/orm/team.g.dart package:common_all/store/team_viewer_store.g.dart package:common_all/orm/ride_summary.dart package:common_all/socket/socket_manager.dart package:common_all/socket/handler/channel_broadcast_handler.dart package:common_all/orm/mixin/conversation.dart package:common_all/orm/user_conversation.dart package:common_all/socket/handler/join_organization_channel_response_handler.dart package:common_all/socket/handler/message_update_handler.dart package:common_all/socket/handler/user_update_handler.dart package:common_all/orm/mixin/task/elevation_task.dart package:common_all/store/staff_profile_setting_store.g.dart package:common_all/socket/handler/team_member_update_handler.dart package:common_all/store/event_route_editor_base_store.g.dart package:common_all/orm/mixin/column_channel_sync_time.dart package:common_all/json/update_list_response.dart package:common_all/orm/weather_forecast.g.dart package:common_all/json/update_list_response.g.dart package:common_all/store/team_viewer_store.dart package:common_all/event_bus/user_message_update.dart package:common_all/store/stop_editor_store.g.dart package:common_all/event_bus/staff_message_update.dart package:common_all/json/update_object_response.g.dart package:common_all/store/event_editor_store.dart package:common_all/orm/simple_user.dart package:common_all/orm/follow_stat.g.dart package:common_all/store/team_store.g.dart package:common_all/orm/notification.g.dart package:common_all/orm/notification.dart package:common_all/orm/sos.g.dart package:common_all/store/request_sent_store.dart package:common_all/store/sos_assign_store.dart package:common_all/orm/event.dart package:common_all/orm/converter/list_stop_converter.dart package:common_all/orm/participant.g.dart package:common_all/orm/saved_route.dart package:common_all/store/staff_profile_setting_store.dart package:common_all/json/db_stop.dart package:common_all/json/get_organizations_response.g.dart package:common_all/orm/route_like.dart package:common_all/common_all_module.dart package:common_all/service/vd_server.dart package:common_all/store/select_org_store.g.dart package:common_all/orm/user_message.g.dart package:common_all/orm/mixin/column_comment_load_time.dart package:common_all/db_syncer.dart
    dart --version: 2.4.1 (Wed Aug 7 13:15:56 2019 +0200) on "macos_x64"

Crash when compiling null,
at character offset null:
type 'DillClassBuilder' is not a subtype of type 'SourceClassBuilder'
#0      KernelTarget.installForwardingConstructors (package:front_end/src/fasta/kernel/kernel_target.dart:462:37)
dart-lang/build#1      KernelTarget.installSyntheticConstructors (package:front_end/src/fasta/kernel/kernel_target.dart:403:11)
dart-lang/build#2      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:266:7)
<asynchronous suspension>
dart-lang/build#3      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
dart-lang/build#4      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:249:12)
<asynchronous suspension>
dart-lang/build#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:316:52)
<asynchronous suspension>
dart-lang/build#6      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
dart-lang/build#7      new Future.sync (dart:async/future.dart:224:31)
dart-lang/build#8      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
dart-lang/build#9      _rootRun (dart:async/zone.dart:1124:13)
dart-lang/build#10     _CustomZone.run (dart:async/zone.dart:1021:19)
dart-lang/build#11     _runZoned (dart:async/zone.dart:1516:10)
dart-lang/build#12     runZoned (dart:async/zone.dart:1463:12)
dart-lang/build#13     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
dart-lang/build#14     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:133:20)
<asynchronous suspension>
dart-lang/build#15     _compile (package:dev_compiler/src/kernel/command.dart:285:64)
<asynchronous suspension>
dart-lang/build#16     compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
dart-lang/build#17     compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
dart-lang/build#18     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:39)
dart-lang/build#19     _rootRun (dart:async/zone.dart:1124:13)
dart-lang/build#20     _CustomZone.run (dart:async/zone.dart:1021:19)
dart-lang/build#21     _runZoned (dart:async/zone.dart:1516:10)
dart-lang/build#22     runZoned (dart:async/zone.dart:1463:12)
dart-lang/build#23     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
dart-lang/build#24     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
dart-lang/build#25     _rootRun (dart:async/zone.dart:1124:13)
dart-lang/build#26     _CustomZone.run (dart:async/zone.dart:1021:19)
dart-lang/build#27     _runZoned (dart:async/zone.dart:1516:10)
dart-lang/build#28     runZoned (dart:async/zone.dart:1463:12)
dart-lang/build#29     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
dart-lang/build#30     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
dart-lang/build#31     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
dart-lang/build#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


#0      KernelTarget.installForwardingConstructors (package:front_end/src/fasta/kernel/kernel_target.dart:462:37)
dart-lang/build#1      KernelTarget.installSyntheticConstructors (package:front_end/src/fasta/kernel/kernel_target.dart:403:11)
dart-lang/build#2      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:266:7)
<asynchronous suspension>
dart-lang/build#3      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
dart-lang/build#4      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:249:12)
<asynchronous suspension>
dart-lang/build#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:316:52)
<asynchronous suspension>
dart-lang/build#6      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
dart-lang/build#7      new Future.sync (dart:async/future.dart:224:31)
dart-lang/build#8      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
dart-lang/build#9      _rootRun (dart:async/zone.dart:1124:13)
dart-lang/build#10     _CustomZone.run (dart:async/zone.dart:1021:19)
dart-lang/build#11     _runZoned (dart:async/zone.dart:1516:10)
dart-lang/build#12     runZoned (dart:async/zone.dart:1463:12)
dart-lang/build#13     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
dart-lang/build#14     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:133:20)
<asynchronous suspension>
dart-lang/build#15     _compile (package:dev_compiler/src/kernel/command.dart:285:64)
<asynchronous suspension>
dart-lang/build#16     compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
dart-lang/build#17     compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
dart-lang/build#18     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:39)
dart-lang/build#19     _rootRun (dart:async/zone.dart:1124:13)
dart-lang/build#20     _CustomZone.run (dart:async/zone.dart:1021:19)
dart-lang/build#21     _runZoned (dart:async/zone.dart:1516:10)
dart-lang/build#22     runZoned (dart:async/zone.dart:1463:12)
dart-lang/build#23     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
dart-lang/build#24     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
dart-lang/build#25     _rootRun (dart:async/zone.dart:1124:13)
dart-lang/build#26     _CustomZone.run (dart:async/zone.dart:1021:19)
dart-lang/build#27     _runZoned (dart:async/zone.dart:1516:10)
dart-lang/build#28     runZoned (dart:async/zone.dart:1463:12)
dart-lang/build#29     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
dart-lang/build#30     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
dart-lang/build#31     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
dart-lang/build#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by jakemac53** [comment]
cc @vsmenon @jensjoha

**Comment by Elvis5566** [comment]
turns out we have something like this causes crash.
```dart
abstract class A with store
abstract class B extends A with store
```

**Comment by jensjoha** [comment]
The initially reported crash seems like https://github.com/flutter/flutter/issues/40966 which was fixed with https://github.com/dart-lang/sdk/commit/fdda2729c330ceecc926476cfb8987700c03e3c0.

I don't understand the latest comment, but it sounds like a potential new bug. I'll close this issue for now --- feel free to re-open if I'm wrong.

**Comment by nydlmaster** [comment]
Just had a similar issue. In my case there was a type in one of the imports.I had "F" instead of "f" in one if the import files. Just double check all the imports (cases, spaces, underscores, etc) thoroughly .
