### ISSUE TITLE
Error compiling dartdevc module:jpush_flutter|lib/jpush_flutter.ddc.js  

### ISSUE THREAD

**Issue by ZhangDubhe** [dart-lang/sdk#38290]
``` 
   dartdevc -k arguments: --dart-sdk-summary=/Users/dubhe/development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
    --modules=amd --no-summarize -o packages/jpush_flutter/jpush_flutter.ddc.js --source-map
    --summary=packages/platform/platform.ddc.dill=packages/platform/platform --summary=packages/meta/meta.ddc.dill=packages/meta/meta
    --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web
    --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation
    --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
    --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
    --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
    --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue
    --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
    --summary=packages/collection/collection.ddc.dill=packages/collection/collection
    --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash
    --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64
    --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena
    --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures
    --packages=file:///var/folders/zz/ljb3lm89099_l7f1cm4mj_1w0000gn/T/kernel_builder_IXKUeC/.packages
    --module-name=packages/jpush_flutter/jpush_flutter --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation
    --inline-source-map --libraries-file=libraries.json package:jpush_flutter/jpush_flutter.dart
    dart --version: 2.5.0-dev.4.0.flutter-be66176534 (Thu Sep 5 15:05:53 2019 +0000) on "macos_x64"

FormatException: Bad UTF-8 encoding 0xa6 (at offset 0)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:530:13)
#1      Utf8Decoder.convert (dart:convert/utf.dart:327:13)
#2      Utf8Codec.decode (dart:convert/utf.dart:59:56)
#3      ProgramCompiler.visitAssertStatement (package:dev_compiler/src/kernel/compiler.dart:3293:32)
#4      ProgramCompiler._initializeFields (package:dev_compiler/src/kernel/compiler.dart:1593:20)
#5      ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1466:14)
#6      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1430:19)
#7      ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:2989:24)
#8      ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1429:15)
#9      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2156:25)
#10     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:2979:18)
#11     ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1427:16)
#12     ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:895:38)
#13     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:535:19)
#14     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:477:21)
#15     List.forEach (dart:core-patch/growable_array.dart:283:8)
#16     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:423:23)
#17     Iterable.forEach (dart:core/iterable.dart:277:30)
#18     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:316:15)
#19     _compile (package:dev_compiler/src/kernel/command.dart:387:27)
<asynchronous suspension>
#20     compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#21     compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#22     _CompilerWorker.performRequest.<anonymous closure>
(file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     _CompilerWorker.performRequest (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#28     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#34     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




Error compiling dartdevc module:getti_app|lib/pages/learning/quiz/quiz_types/draggable/draggable_items.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/Users/dubhe/development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
    --modules=amd --no-summarize -o packages/getti_app/pages/learning/quiz/quiz_types/draggable/draggable_items.ddc.js --source-map
    --summary=packages/meta/meta.ddc.dill=packages/meta/meta
    --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web
    --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation
    --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash
    --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64
    --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation
    --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics
    --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
    --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
    --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
    --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue
    --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
    --summary=packages/collection/collection.ddc.dill=packages/collection/collection
    --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena
    --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures
    --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web
    --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting
    --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding
    --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics
    --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation
    --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation
    --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size
    --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering
    --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions
    --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets
    --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet
    --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino
    --summary=packages/flutter/material.ddc.dill=packages/flutter/material
    --packages=file:///var/folders/zz/ljb3lm89099_l7f1cm4mj_1w0000gn/T/kernel_builder_dkBs1N/.packages
    --module-name=packages/getti_app/pages/learning/quiz/quiz_types/draggable/draggable_items --multi-root-scheme=org-dartlang-app
    --multi-root=. --track-widget-creation --inline-source-map --libraries-file=libraries.json
    package:getti_app/pages/learning/quiz/quiz_types/draggable/draggable_items.dart
    dart --version: 2.5.0-dev.4.0.flutter-be66176534 (Thu Sep 5 15:05:53 2019 +0000) on "macos_x64"

FormatException: Bad UTF-8 encoding 0x81 (at offset 0)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:530:13)
#1      Utf8Decoder.convert (dart:convert/utf.dart:327:13)
#2      Utf8Codec.decode (dart:convert/utf.dart:59:56)
#3      ProgramCompiler.visitAssertStatement (package:dev_compiler/src/kernel/compiler.dart:3293:32)
#4      ProgramCompiler._initializeFields (package:dev_compiler/src/kernel/compiler.dart:1593:20)
#5      ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1466:14)
#6      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1430:19)
#7      ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:2989:24)
#8      ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1429:15)
#9      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2156:25)
#10     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:2979:18)
#11     ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1427:16)
#12     ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:895:38)
#13     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:535:19)
#14     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:477:21)
#15     List.forEach (dart:core-patch/growable_array.dart:283:8)
#16     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:423:23)
#17     Iterable.forEach (dart:core/iterable.dart:277:30)
#18     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:316:15)
#19     _compile (package:dev_compiler/src/kernel/command.dart:387:27)
<asynchronous suspension>
#20     compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#21     compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#22     _CompilerWorker.performRequest.<anonymous closure>
(file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     _CompilerWorker.performRequest (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#28     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#34     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




                                                                        
AssetNotFoundException: jpush_flutter|lib/jpush_flutter.ddc.js          
Failed after 1m 25s 
```

**Comment by vsmenon** [comment]
@Markzipan - can you take a look when you get a chance?

**Comment by vsmenon** [comment]
Consolidating to https://github.com/dart-lang/sdk/issues/39271
