### ISSUE TITLE
get this issue for completion

### ISSUE THREAD

**Issue by Zuhdan** [dart-lang/sdk#38293]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-192.6262.59`
- `2.4.0`
- `WS-192.6262.59, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Linux(amd64) v5.0.0-25-generic, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, FATAL error: Failed to handle request: {id: 1070, method: edit.getStatementCompletion, params: {file: /home/nemo/WebstormProjects/ayorent/lib/src/networking/ayorent_api.dart, offset: 331}, clientRequestTime: 1568133353102}
NoSuchMethodError: The getter 'rightParenthesis' was called on null.
Receiver: null
Tried calling: rightParenthesis
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      StatementCompletionProcessor._complete_functionDeclaration.computeExitPos (package:analysis_server/src/services/completion/statement/statement_completion.dart:703:35)
#2      StatementCompletionProcessor._complete_functionDeclaration (package:analysis_server/src/services/completion/statement/statement_completion.dart:718:36)
#3      StatementCompletionProcessor.compute (package:analysis_server/src/services/completion/statement/statement_completion.dart:210:13)
<asynchronous suspension>
#4      EditDomainHandler.getStatementCompletion (package:analysis_server/src/edit/edit_domain.dart:355:56)
<asynchronous suspension>
#5      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:398:9)
#6      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:45)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#8      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:317:50)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1500:12)
#13     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:316:5)
#14     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#16     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#17     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#26     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#27     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#28     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#35     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#36     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#37     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#38     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#39     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#40     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#41     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#43     _rootRunUnary (dart:async/zone.dart:1132:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#48     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#49     _StreamController._add (dart:async/stream_controller.dart:640:7)
#50     _StreamController.add (dart:async/stream_controller.dart:586:5)
#51     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#52     _rootRunUnary (dart:async/zone.dart:1136:13)
#53     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#55     _BufferingStreamSubscription._sendD...
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.4.0. Please re-open if you see this crash again.
