### ISSUE TITLE
Kernel nullable cascade operator error

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#38300]
Now that [the parser handles the nullable cascade operator](https://dart-review.googlesource.com/c/sdk/+/116089), the kernel code needs to be updated to handle it as well. Here's one of the test failures I'm seeing...
```
co19_2/LanguageFeatures/nnbd/static_errors_A11_t01

--- Command "vm" (took 699ms):
DART_CONFIGURATION=ProductX64 out/ProductX64/dart --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LanguageFeatures/nnbd/static_errors_A11_t01.dart

exit code:
255

stderr:
Unhandled exception:
NoSuchMethodError: The method 'test' was called on null.
Receiver: null
Tried calling: test()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      main (file:///b/s/w/ir/tests/co19_2/src/LanguageFeatures/nnbd/static_errors_A11_t01.dart:25:9)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

--- Re-run this test:
python tools/test.py -n dartk-linux-product-x64 co19_2/LanguageFeatures/nnbd/static_errors_A11_t01
```

**Comment by johnniwinther** [comment]
This seems to be working now.
