### ISSUE TITLE
Analyzer fuzz crash: inferring return type in inherited parameterized method

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38309]
```dart
class A<T>{
  A<R> f<R>() => null;
}

class B extends A {
  f<R extends Object>() => null;
}
```

this fails on summary2.

```
Unhandled exception:
type 'TypeParameterMember' is not a subtype of type 'TypeParameterElementImpl'
#0      LinkingBundleContext.writeType (package:analyzer/src/summary2/linking_bundle_context.dart:99:32)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#2      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#3      LinkingBundleContext.writeType (package:analyzer/src/summary2/linking_bundle_context.dart:95:67)
#4      AstBinaryWriter._writeType (package:analyzer/src/summary2/ast_binary_writer.dart:1659:28)
#5      AstBinaryWriter._writeActualReturnType (package:analyzer/src/summary2/ast_binary_writer.dart:1633:32)
#6      AstBinaryWriter.visitMethodDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:946:5)
#7      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7103:49)
#8      AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:1653:31)
#9      AstBinaryWriter._storeClassOrMixinDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:1484:43)
#10     AstBinaryWriter.visitClassDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:221:7)
```

**Comment by scheglov** [comment]
Cannot reproduce on the bleeding edge.
We also have removed `TypeParameterMember` recently.
