### ISSUE TITLE
Web compiler failed to compile existing flutter app

### ISSUE THREAD

**Issue by Pareshoct7** [dart-lang/sdk#38313]
Here is log 

```
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:436:29)
#1      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:446:5)
#2      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:398:10)
#3      ProcessedOptions.loadInputSummaries.<anonymous closure> (package:front_end/src/base/processed_options.dart:360:35)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:360:67)
<asynchronous suspension>
#7      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:95:50)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#9      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:69:10)
<asynchronous suspension>
#10     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:49:18)
<asynchronous suspension>
#11     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:136:20)
<asynchronous suspension>
#12     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#13     new Future.sync (dart:async/future.dart:224:31)
#14     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#20     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:134:10)
#21     generateKernel (package:front_end/src/kernel_generator_impl.dart:48:32)
<asynchronous suspension>
#22     compile (package:front_end/src/api_unstable/ddc.dart:302:13)
<asynchronous suspension>
#23     _compile (package:dev_compiler/src/kernel/command.dart:320:20)
<asynchronous suspension>
#24     compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#25     compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#26     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     _CompilerWorker.performRequest (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#32     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#38     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




                                                                        
AssetNotFoundException: http|lib/http.ddc.dill                          
Error creating kaledate|lib/main.ddc.dill                               
Error creating kernel summary for module:kaledate|lib/main.ddc.dill     

Response:--dart-sdk-summary=file:///Users/Paresh/development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--output=/private/var/folders/td/v2s79nf94vz7z73swq0h3_qh0000gp/T/scratch_spacem8m7KQ/packages/kaledate/main.ddc.dill --packages-file=file:///var/folders/td/v2s79nf94vz7z73swq0h3_qh0000gp/T/kernel_builder_WS4d5s/.packages
--multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///Users/Paresh/development/flutter/bin/cache/flutter_web_sdk/libraries.json
--input-summary=org-dartlang-app:///packages/cloud_firestore/cloud_firestore.ddc.dill --input-summary=org-dartlang-app:///packages/time_machine/src/platforms/web.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/gestures.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/material.ddc.dill
--input-summary=org-dartlang-app:///packages/firebase_messaging/firebase_messaging.ddc.dill --input-summary=org-dartlang-app:///packages/firebase_auth/firebase_auth.ddc.dill
--input-summary=org-dartlang-app:///packages/intl/intl.ddc.dill --input-summary=org-dartlang-app:///packages/meta/meta.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/foundation.ddc.dill
--input-summary=org-dartlang-app:///packages/collection/collection.ddc.dill --input-summary=org-dartlang-app:///packages/firebase_core/firebase_core.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/cupertino.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter_local_notifications/flutter_local_notifications.ddc.dill --input-summary=org-dartlang-app:///packages/queries/collections.ddc.dill
--input-summary=org-dartlang-app:///packages/google_sign_in/google_sign_in.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_facebook_login/flutter_facebook_login.ddc.dill
--input-summary=org-dartlang-app:///packages/dio/dio.ddc.dill --input-summary=org-dartlang-app:///packages/json_annotation/json_annotation.ddc.dill
--input-summary=org-dartlang-app:///packages/shared_preferences/shared_preferences.ddc.dill --input-summary=org-dartlang-app:///packages/fluttertoast/fluttertoast.ddc.dill
--input-summary=org-dartlang-app:///packages/path/path.ddc.dill --input-summary=org-dartlang-app:///packages/geocoder/geocoder.ddc.dill --input-summary=org-dartlang-app:///packages/google_places_picker/google_places_picker.ddc.dill
--input-summary=org-dartlang-app:///packages/image_picker/image_picker.ddc.dill --input-summary=org-dartlang-app:///packages/firebase_storage/firebase_storage.ddc.dill
--input-summary=org-dartlang-app:///packages/time_machine/src/ambiguous_time_error.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/gestures/arena.ddc.dill
--input-summary=org-dartlang-app:///packages/path_provider/path_provider.ddc.dill --input-summary=org-dartlang-app:///packages/flutter_image_compress/flutter_image_compress.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/widgets.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/vector_math_64.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/semantics.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/rendering.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/animation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/painting.ddc.dill
--input-summary=org-dartlang-app:///packages/platform/platform.ddc.dill --input-summary=org-dartlang-app:///packages/sqflite/sqflite.ddc.dill --input-summary=org-dartlang-app:///packages/intl/date_symbols.ddc.dill
--input-summary=org-dartlang-app:///packages/intl/number_symbols_data.ddc.dill --input-summary=org-dartlang-app:///packages/intl/number_symbols.ddc.dill --input-summary=org-dartlang-app:///packages/intl/src/plural_rules.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/src/foundation/_bitfield_web.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/algorithms.ddc.dill
--input-summary=org-dartlang-app:///packages/collection/src/utils.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/iterable_zip.ddc.dill
--input-summary=org-dartlang-app:///packages/collection/src/comparators.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/priority_queue.ddc.dill
--input-summary=org-dartlang-app:///packages/collection/src/canonicalized_map.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/cupertino/action_sheet.ddc.dill
--input-summary=org-dartlang-app:///packages/function_types/function_types.ddc.dill --input-summary=org-dartlang-app:///packages/google_sign_in/widgets.ddc.dill
--input-summary=org-dartlang-app:///packages/google_sign_in/src/common.ddc.dill --input-summary=org-dartlang-app:///packages/cookie_jar/cookie_jar.ddc.dill --input-summary=org-dartlang-app:///packages/geocoder/services/base.ddc.dill
--input-summary=org-dartlang-app:///packages/geocoder/services/distant_google.ddc.dill --input-summary=org-dartlang-app:///packages/geocoder/model.ddc.dill
--input-summary=org-dartlang-app:///packages/geocoder/services/local.ddc.dill --input-summary=org-dartlang-app:///packages/codable/codable.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/widgets/actions.ddc.dill
--input-summary=org-dartlang-app:///packages/vector_math/hash.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/semantics/binding.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/src/rendering/animated_size.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/animation/animation.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/src/painting/_network_image_web.ddc.dill --input-summary=org-dartlang-app:///packages/diacritic/diacritic.ddc.dill
--input-summary=org-dartlang-app:///packages/vector_math/vector_math.ddc.dill --input-summary=org-dartlang-app:///packages/sqflite/sql.ddc.dill --input-summary=org-dartlang-app:///packages/sqflite/src/constant.ddc.dill
--input-summary=org-dartlang-app:///packages/sqflite/utils/utils.ddc.dill --input-summary=org-dartlang-app:///packages/sqflite/sqlite_api.ddc.dill --input-summary=org-dartlang-app:///packages/sqflite/src/collection_utils.ddc.dill
--input-summary=org-dartlang-app:///packages/sqflite/src/sql_builder.ddc.dill --input-summary=org-dartlang-app:///packages/synchronized/src/basic_lock.ddc.dill
--input-summary=org-dartlang-app:///packages/typed_data/typed_buffers.ddc.dill --input-summary=org-dartlang-app:///packages/after_layout/after_layout.ddc.dill --input-summary=org-dartlang-app:///packages/codable/cast.ddc.dill
--input-summary=org-dartlang-app:///packages/uuid/uuid.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/physics.ddc.dill --input-summary=org-dartlang-app:///packages/auto_size_text/auto_size_text.ddc.dill
--input-summary=org-dartlang-app:///packages/uuid/uuid_util.ddc.dill --input-summary=org-dartlang-app:///packages/crypto/crypto.ddc.dill --input-summary=org-dartlang-app:///packages/convert/convert.ddc.dill
--input-summary=org-dartlang-app:///packages/http/src/base_client.ddc.dill --input-summary=org-dartlang-app:///packages/http_parser/http_parser.ddc.dill --input-summary=org-dartlang-app:///packages/async/async.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/src/physics/clamped_simulation.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_data.ddc.dill
--input-summary=org-dartlang-app:///packages/charcode/ascii.ddc.dill --input-summary=org-dartlang-app:///packages/pedantic/pedantic.ddc.dill --input-summary=org-dartlang-app:///packages/string_scanner/src/eager_span_scanner.ddc.dill
--input-summary=org-dartlang-app:///packages/source_span/source_span.ddc.dill --input-summary=org-dartlang-app:///packages/charcode/charcode.ddc.dill
--input-summary=org-dartlang-app:///packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill --input-summary=org-dartlang-app:///packages/charcode/html_entity.ddc.dill --source=package:kaledate/main.dart
Crash when compiling package:kaledate/main.dart,
at character offset null:
Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:436:29)
#1      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:446:5)
#2      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:398:10)
#3      ProcessedOptions.loadInputSummaries.<anonymous closure> (package:front_end/src/base/processed_options.dart:360:35)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:360:67)
<asynchronous suspension>
#7      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:95:50)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#9      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:69:10)
<asynchronous suspension>
#10     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:49:18)
<asynchronous suspension>
#11     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:136:20)
<asynchronous suspension>
#12     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#13     new Future.sync (dart:async/future.dart:224:31)
#14     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#20     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:134:10)
#21     generateKernel (package:front_end/src/kernel_generator_impl.dart:48:32)
<asynchronous suspension>
#22     _compile (package:front_end/src/api_unstable/bazel_worker.dart:265:10)
#23     compileSummary (package:front_end/src/api_unstable/bazel_worker.dart:274:33)
<asynchronous suspension>
#24     computeKernel (file:///b/s/w/ir/k/src/third_party/dart/utils/bazel/kernel_worker.dart:351:20)
<asynchronous suspension>
#25     KernelWorker.performRequest (file:///b/s/w/ir/k/src/third_party/dart/utils/bazel/kernel_worker.dart:69:26)
<asynchronous suspension>
#26     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#32     main (file:///b/s/w/ir/k/src/third_party/dart/utils/bazel/kernel_worker.dart:38:48)
<asynchronous suspension>
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by mraleph** [comment]
@vsmenon empty Kernel blob again

**Comment by Pareshoct7** [comment]
The full log is here in attachment

[log.txt](https://github.com/dart-lang/sdk/files/3599454/log.txt)

**Comment by vsmenon** [comment]
dup of https://github.com/dart-lang/sdk/issues/38102
