### ISSUE TITLE
VSCode Dart code completions 'The Dart Analyzer has terminated'

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/sdk#38316]
* Dart VM version: 2.6.0-dev.0.0 (Tue Sep 10 12:55:30 2019 +0200) on "macos_x64"
 * Dart Code 3.4.1
 * VS Code 1.38.0

Since enabling the  code completions preview [following these instructions](https://github.com/dart-lang/sdk/wiki/Previewing-Dart-code-completions-powered-by-machine-learning) my analyzer instantly dies, restarting it and restarting VS Code does not fix the issue.

```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.4.1
Flutter extension: 3.4.1 (not activated)
VS Code: 1.38.0
Platform: mac
HTTP_PROXY: undefined
NO_PROXY: undefined

Wed Sep 11 2019 [09:51:25 GMT+0100 (British Summer Time)] Log file started
[9:51:25 AM] [General] [Info] Searching for SDKs...
[9:51:25 AM] [General] [Info] Environment PATH:
[9:51:25 AM] [General] [Info]     /Users/jimmyff/google-cloud-sdk/bin
[9:51:25 AM] [General] [Info]     //chromium_depot_tools
[9:51:25 AM] [General] [Info]     /Users/jimmyff/flutter-sdk/bin
[9:51:25 AM] [General] [Info]     /usr/local/sbin
[9:51:25 AM] [General] [Info]     /usr/local/bin
[9:51:25 AM] [General] [Info]     /usr/bin
[9:51:25 AM] [General] [Info]     /bin
[9:51:25 AM] [General] [Info]     /usr/sbin
[9:51:25 AM] [General] [Info]     /sbin
[9:51:25 AM] [General] [Info]     /Applications/VMware Fusion.app/Contents/Public
[9:51:25 AM] [General] [Info]     /usr/local/git/bin
[9:51:25 AM] [General] [Info]     ~/.pub-cache/bin
[9:51:25 AM] [General] [Info] Searching for flutter
[9:51:25 AM] [General] [Info]     Looking for flutter in:
[9:51:25 AM] [General] [Info]         /Users/jimmyff/google-cloud-sdk/bin
[9:51:25 AM] [General] [Info]         //chromium_depot_tools
[9:51:25 AM] [General] [Info]         /chromium_depot_tools/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin
[9:51:25 AM] [General] [Info]         /usr/local/sbin
[9:51:25 AM] [General] [Info]         /usr/local/bin
[9:51:25 AM] [General] [Info]         /usr/bin
[9:51:25 AM] [General] [Info]         /bin
[9:51:25 AM] [General] [Info]         /usr/sbin
[9:51:25 AM] [General] [Info]         /sbin
[9:51:25 AM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public
[9:51:25 AM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public/bin
[9:51:25 AM] [General] [Info]         /usr/local/git/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/.pub-cache/bin
[9:51:25 AM] [General] [Info]     Found at:
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin
[9:51:25 AM] [General] [Info]     Candidate paths to be post-filtered:
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk
[9:51:25 AM] [General] [Info]     Found at /Users/jimmyff/flutter-sdk
[9:51:25 AM] [General] [Info]     Returning SDK path /Users/jimmyff/flutter-sdk for flutter
[9:51:25 AM] [General] [Info] Searching for dart
[9:51:25 AM] [General] [Info]     Looking for dart in:
[9:51:25 AM] [General] [Info]         /Users/jimmyff/google-cloud-sdk/bin
[9:51:25 AM] [General] [Info]         //chromium_depot_tools
[9:51:25 AM] [General] [Info]         /chromium_depot_tools/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin
[9:51:25 AM] [General] [Info]         /usr/local/sbin
[9:51:25 AM] [General] [Info]         /usr/local/bin
[9:51:25 AM] [General] [Info]         /usr/bin
[9:51:25 AM] [General] [Info]         /bin
[9:51:25 AM] [General] [Info]         /usr/sbin
[9:51:25 AM] [General] [Info]         /sbin
[9:51:25 AM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public
[9:51:25 AM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public/bin
[9:51:25 AM] [General] [Info]         /usr/local/git/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/.pub-cache/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin/cache/dart-sdk
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin/cache/dart-sdk/bin
[9:51:25 AM] [General] [Info]     Found at:
[9:51:25 AM] [General] [Info]         /usr/local/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin/cache/dart-sdk/bin
[9:51:25 AM] [General] [Info] Following symlink: /usr/local/bin/dart ==> /usr/local/Cellar/dart/2.6.0-dev.0.0/libexec/bin/dart
[9:51:25 AM] [General] [Info]     Candidate paths to be post-filtered:
[9:51:25 AM] [General] [Info]         /usr/local/Cellar/dart/2.6.0-dev.0.0/libexec
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin/cache/dart-sdk
[9:51:25 AM] [General] [Info]     Found at /usr/local/Cellar/dart/2.6.0-dev.0.0/libexec
[9:51:25 AM] [General] [Info]     Returning SDK path /usr/local/Cellar/dart/2.6.0-dev.0.0/libexec for dart
[9:51:25 AM] [General] [Info] Extension:Startup timing: 19ms
[9:51:25 AM] [General] [Info] Done!
[9:51:25 AM] [General] [Info] Analyzer:Startup timing: 363ms
[9:51:34 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:406:19)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at module.exports.t.Analyzer.sendMessage (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:41338)
	at module.exports.t.Analyzer.sendMessage (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:36662)
	at module.exports.t.StdIOService.sendRequest.Promise (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:41146)
	at new Promise (<anonymous>)
	at module.exports.t.Analyzer.sendRequest (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:40958)
	at module.exports.t.Analyzer.editGetFixes (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:275728)
	at module.exports.t.FixCodeActionProvider.<anonymous> (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:405233)
	at Generator.next (<anonymous>)
	at module.exports.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:404769)
	at new Promise (<anonymous>)
	at module.exports.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:404546)
	at module.exports.t.FixCodeActionProvider.provideCodeActions (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:405074)
	at module.exports.t.RankingCodeActionProvider.provideCodeActions.r.codeActionProviders.filter.map.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:410277)
	at Array.map (<anonymous>)
	at module.exports.t.RankingCodeActionProvider.<anonymous> (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:410268)
	at Generator.next (<anonymous>)
	at module.exports.…
[9:51:34 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:406:19)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at module.exports.t.Analyzer.sendMessage (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:41338)
	at module.exports.t.Analyzer.sendMessage (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:36662)
	at module.exports.t.StdIOService.sendRequest.Promise (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:41146)
	at new Promise (<anonymous>)
	at module.exports.t.Analyzer.sendRequest (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:40958)
	at module.exports.t.Analyzer.editGetAssists (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:275451)
	at module.exports.t.AssistCodeActionProvider.<anonymous> (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:368204)
	at Generator.next (<anonymous>)
	at module.exports.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:367745)
	at new Promise (<anonymous>)
	at module.exports.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:367522)
	at module.exports.t.AssistCodeActionProvider.provideCodeActions (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:368046)
	at module.exports.t.RankingCodeActionProvider.provideCodeActions.r.codeActionProviders.filter.map.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:410277)
	at Array.map (<anonymous>)
	at module.exports.t.RankingCodeActionProvider.<anonymous> (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:410268)
	at Generator.next (<anonymous>)
	at module.…
[9:51:25 AM] [General] [Info] Searching for SDKs...
[9:51:25 AM] [General] [Info] Environment PATH:
[9:51:25 AM] [General] [Info]     /Users/jimmyff/google-cloud-sdk/bin
[9:51:25 AM] [General] [Info]     //chromium_depot_tools
[9:51:25 AM] [General] [Info]     /Users/jimmyff/flutter-sdk/bin
[9:51:25 AM] [General] [Info]     /usr/local/sbin
[9:51:25 AM] [General] [Info]     /usr/local/bin
[9:51:25 AM] [General] [Info]     /usr/bin
[9:51:25 AM] [General] [Info]     /bin
[9:51:25 AM] [General] [Info]     /usr/sbin
[9:51:25 AM] [General] [Info]     /sbin
[9:51:25 AM] [General] [Info]     /Applications/VMware Fusion.app/Contents/Public
[9:51:25 AM] [General] [Info]     /usr/local/git/bin
[9:51:25 AM] [General] [Info]     ~/.pub-cache/bin
[9:51:25 AM] [General] [Info] Searching for flutter
[9:51:25 AM] [General] [Info]     Looking for flutter in:
[9:51:25 AM] [General] [Info]         /Users/jimmyff/google-cloud-sdk/bin
[9:51:25 AM] [General] [Info]         //chromium_depot_tools
[9:51:25 AM] [General] [Info]         /chromium_depot_tools/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin
[9:51:25 AM] [General] [Info]         /usr/local/sbin
[9:51:25 AM] [General] [Info]         /usr/local/bin
[9:51:25 AM] [General] [Info]         /usr/bin
[9:51:25 AM] [General] [Info]         /bin
[9:51:25 AM] [General] [Info]         /usr/sbin
[9:51:25 AM] [General] [Info]         /sbin
[9:51:25 AM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public
[9:51:25 AM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public/bin
[9:51:25 AM] [General] [Info]         /usr/local/git/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/.pub-cache/bin
[9:51:25 AM] [General] [Info]     Found at:
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin
[9:51:25 AM] [General] [Info]     Candidate paths to be post-filtered:
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk
[9:51:25 AM] [General] [Info]     Found at /Users/jimmyff/flutter-sdk
[9:51:25 AM] [General] [Info]     Returning SDK path /Users/jimmyff/flutter-sdk for flutter
[9:51:25 AM] [General] [Info] Searching for dart
[9:51:25 AM] [General] [Info]     Looking for dart in:
[9:51:25 AM] [General] [Info]         /Users/jimmyff/google-cloud-sdk/bin
[9:51:25 AM] [General] [Info]         //chromium_depot_tools
[9:51:25 AM] [General] [Info]         /chromium_depot_tools/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin
[9:51:25 AM] [General] [Info]         /usr/local/sbin
[9:51:25 AM] [General] [Info]         /usr/local/bin
[9:51:25 AM] [General] [Info]         /usr/bin
[9:51:25 AM] [General] [Info]         /bin
[9:51:25 AM] [General] [Info]         /usr/sbin
[9:51:25 AM] [General] [Info]         /sbin
[9:51:25 AM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public
[9:51:25 AM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public/bin
[9:51:25 AM] [General] [Info]         /usr/local/git/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/.pub-cache/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin/cache/dart-sdk
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin/cache/dart-sdk/bin
[9:51:25 AM] [General] [Info]     Found at:
[9:51:25 AM] [General] [Info]         /usr/local/bin
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin/cache/dart-sdk/bin
[9:51:25 AM] [General] [Info] Following symlink: /usr/local/bin/dart ==> /usr/local/Cellar/dart/2.6.0-dev.0.0/libexec/bin/dart
[9:51:25 AM] [General] [Info]     Candidate paths to be post-filtered:
[9:51:25 AM] [General] [Info]         /usr/local/Cellar/dart/2.6.0-dev.0.0/libexec
[9:51:25 AM] [General] [Info]         /Users/jimmyff/flutter-sdk/bin/cache/dart-sdk
[9:51:25 AM] [General] [Info]     Found at /usr/local/Cellar/dart/2.6.0-dev.0.0/libexec
[9:51:25 AM] [General] [Info]     Returning SDK path /usr/local/Cellar/dart/2.6.0-dev.0.0/libexec for dart
[9:51:25 AM] [General] [Info] Extension:Startup timing: 19ms
[9:51:25 AM] [General] [Info] Done!
[9:51:25 AM] [General] [Info] Analyzer:Startup timing: 363ms
[9:51:34 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:406:19)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at module.exports.t.Analyzer.sendMessage (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:41338)
	at module.exports.t.Analyzer.sendMessage (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:36662)
	at module.exports.t.StdIOService.sendRequest.Promise (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:41146)
	at new Promise (<anonymous>)
	at module.exports.t.Analyzer.sendRequest (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:40958)
	at module.exports.t.Analyzer.editGetFixes (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:275728)
	at module.exports.t.FixCodeActionProvider.<anonymous> (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:405233)
	at Generator.next (<anonymous>)
	at module.exports.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:404769)
	at new Promise (<anonymous>)
	at module.exports.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:404546)
	at module.exports.t.FixCodeActionProvider.provideCodeActions (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:405074)
	at module.exports.t.RankingCodeActionProvider.provideCodeActions.r.codeActionProviders.filter.map.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:410277)
	at Array.map (<anonymous>)
	at module.exports.t.RankingCodeActionProvider.<anonymous> (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:410268)
	at Generator.next (<anonymous>)
	at module.exports.…
[9:51:34 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:406:19)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at module.exports.t.Analyzer.sendMessage (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:41338)
	at module.exports.t.Analyzer.sendMessage (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:36662)
	at module.exports.t.StdIOService.sendRequest.Promise (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:41146)
	at new Promise (<anonymous>)
	at module.exports.t.Analyzer.sendRequest (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:40958)
	at module.exports.t.Analyzer.editGetAssists (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:275451)
	at module.exports.t.AssistCodeActionProvider.<anonymous> (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:368204)
	at Generator.next (<anonymous>)
	at module.exports.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:367745)
	at new Promise (<anonymous>)
	at module.exports.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:367522)
	at module.exports.t.AssistCodeActionProvider.provideCodeActions (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:368046)
	at module.exports.t.RankingCodeActionProvider.provideCodeActions.r.codeActionProviders.filter.map.r (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:410277)
	at Array.map (<anonymous>)
	at module.exports.t.RankingCodeActionProvider.<anonymous> (/Users/jimmyff/.vscode/extensions/dart-code.dart-code-3.4.1/out/dist/extension.js:1:410268)
	at Generator.next (<anonymous>)
	at module.…

```

**Comment by jimmyff** [comment]
I used the VS Code UI to enter the `analyzerAdditionalArgs` and included the prefix --, since removing this it no longer crashes
