### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by firovski** [dart-lang/sdk#38318]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1080, 1920x1200  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Bad state: No element
#0      List.first (dart:core-patch/growable_array.dart:216:5)
#1      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:208:23)
#2      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:766:48)
#3      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1154:19)
#4      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1216:16)
#5      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:756:9)
#6      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:496:22)
#7      AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:389:14)
#8      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:323:16)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:45)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:317:50)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:316:5)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#52     _StreamController._add (dart:async/stream_controller.dart:640:7)
#53     _StreamController.add (dart:async/stream_controller.dart:586:5)
#54     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#55     _rootRunUnary (dart:async/zone.dart:1136:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#61     _StreamController._add (dart:async/stream_controller.dart:640:7)
#62     _StreamController.add (dart:async/stream_controller.dart:586:5)
#63     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1335:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:856:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information, please append the contents of
file:///private/var/folders/7j/n0nb1jgn6yn57v9qkv8rzlnc0000gp/T/report.txt.

**Comment by srawlins** [comment]
This is happening in 2.6.0 as well.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.6.0. Please re-open if you see this crash again.
