### ISSUE TITLE
Dart Analyzer Error 		Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by GanLuo96214** [dart-lang/sdk#38331]
## Version information

- `IDEA IU-192.6603.28`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IU-192.6603.28, JRE 11.0.3+12-b304.56x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1200  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/gl/Documents/source/flutter/water_purifier_debug/lib/main.dart
NoSuchMethodError: The getter 'kind' was called on null.
Receiver: null
Tried calling: kind
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Member.kind (package:analyzer/src/dart/element/member.dart:475:40)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:466:40)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:452:7)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:752:7)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8969:49)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6629:13)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:396:31)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6625:49)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7428:12)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#12     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#13     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#14     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#15     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#16     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#18     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#19     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#20     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140:45)
#21     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#22     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:669:24)
#23     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
#24     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8638:18)
#25     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#26     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#27     GeneralizingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:486:51)
#28     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8634:49)
#29     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#30     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#31     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#32     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#33     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:162:31)
#34     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#35     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#36     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#37     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#38     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:165:55)
#39     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#40     ConstructorDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2634:12)
#41     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#42     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#43     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#44     GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:183:43)
#45     GeneralizingAstVisitor.visitConstructorDeclaration (package:analyzer/dart/ast/visitor.dart:213:7)
#46     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2624:15)
#47     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#48     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#49     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#50     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#51     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#52     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:202:7)
#53     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:427:7)
#54     GeneralizingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:181:7)
#55     _IndexContributor.visitClassDeclaration (package:analyzer/src/dart/analysis/index.dart:566:11)
#56     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#57     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#58     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#59     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#60     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:199:51)
#61     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#62     _IndexAssembler.assemble (package:analyzer/src/dart/analysis/index.dart:262:10)
#63     indexUnit (package:analyzer/src/dart/analysis/index.dart:35:32)
#64     AnalysisDriver._serializeResolvedUnit (package:analyzer/src/dart/analysis/driver.dart:1610:11)
#65     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1266:15)
#66     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#67     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#68     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
<asynchronous suspension>
#69     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#70     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#71     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#72     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#73     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#74     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#75     _rootRun (dart:async/zone.dart:1124:13)
#76     _CustomZone.run (dart:async/zone.dart:1021:19)
#77     _runZoned (dart:async/zone.dart:1516:10)
#78     runZoned (dart:async/zone.dart:1463:12)
#79     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#80     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#81     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#82     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#83     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#84     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#85     new Future.sync (dart:async/future.dart:224:31)
#86     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#87     _rootRun (dart:async/zone.dart:1124:13)
#88     _CustomZone.run (dart:async/zone.dart:1021:19)
#89     _runZoned (dart:async/zone.dart:1516:10)
#90     runZoned (dart:async/zone.dart:1463:12)
#91     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#92     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#93     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#94     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#95     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#96     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#97     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#98     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```

```
1568229160203 => {"id":"21","method":"analysis.updateContent","params":{"files":{"/Users/gl/Documents/source/flutter/water_purifier_debug/lib/main.dart":{"type":"add","content":"import 'dart:async';\n
1568229160215 => {"id":"22","method":"edit.getAssists","params":{"file":"/Users/gl/Documents/source/flutter/water_purifier_debug/lib/main.dart","offset":13160,"length":0},"clientRequestTime":156822916
1568229160237 <= {"id":"21","result":{}}
1568229160238 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1568229160425 <= {"id":"22","result":{"assists":[]}}
1568229160428 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":727,"uri":"package:water_purifier_debug/main.dart","items":[{"label":"http_server","declaringLibraryUri"
1568229160429 <= {"event":"analysis.errors","params":{"file":"/Users/gl/Documents/source/flutter/water_purifier_debug/test/widget_test.dart","errors":[]}}
1568229160429 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1568229160633 => {"id":"23","method":"analysis.updateContent","params":{"files":{"/Users/gl/Documents/source/flutter/water_purifier_debug/lib/main.dart":{"type":"remove"}}},"clientRequestTime":1568229
1568229160633 => {"id":"24","method":"edit.getAssists","params":{"file":"/Users/gl/Documents/source/flutter/water_purifier_debug/lib/main.dart","offset":13160,"length":0},"clientRequestTime":156822916
1568229160635 <= {"id":"23","result":{}}
1568229160636 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1568229160716 <= {"id":"24","result":{"assists":[]}}
1568229160718 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":727,"uri":"package:water_purifier_debug/main.dart","items":[{"label":"http_server","declaringLibraryUri"
1568229160718 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1568229161636 => {"id":"25","method":"analysis.updateContent","params":{"files":{"/Users/gl/Documents/source/flutter/water_purifier_debug/lib/main.dart":{"type":"add","content":"import 'dart:async';\n
1568229161636 => {"id":"26","method":"completion.getSuggestions","params":{"file":"/Users/gl/Documents/source/flutter/water_purifier_debug/lib/main.dart","offset":13160},"clientRequestTime":1568229161
1568229161638 <= {"id":"25","result":{}}
1568229161639 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1568229161714 <= {"id":"26","result":{"id":"1"}}
1568229161714 <= {"event":"completion.results","params":{"id":"1","replacementOffset":13160,"replacementLength":0,"results":[],"isLast":true,"includedSuggestionSets":[],"includedElementKinds":[],"incl
1568229161717 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":727,"uri":"package:water_purifier_debug/main.dart","items":[{"label":"http_server","declaringLibraryUri"
1568229161718 <= {"event":"analysis.errors","params":{"file":"/Users/gl/Documents/source/flutter/water_purifier_debug/test/widget_test.dart","errors":[]}}
1568229161718 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1568229162034 => {"id":"27","method":"edit.getAssists","params":{"file":"/Users/gl/Documents/source/flutter/water_purifier_debug/lib/main.dart","offset":13160,"length":0},"clientRequestTime":156822916
1568229162038 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1568229162139 <= {"id":"27","result":{"assists":[]}}
1568229162141 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1568229162147 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1568229162234 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/gl/Documents/source/flutter/water_purifier_debug/lib/main.dart","stackTrace":"NoSuchMethodError: T
```

# repeat
```dart

void main() => runApp(App());

func App(){

}

class A {

  int A1;

  A({
    @required this.A1,
  });

}

class B {

  int B1;

  A({
    @required this.B1,
  });

  factory A.fromJson(Map<String, dynamic> json) {
    return A(
      B1: 1,
    );
  }

}

```

**Comment by keertip** [comment]
Thanks for the report.
