### ISSUE TITLE
Analyzer fuzz crash: extension invoked in const context

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38369]
```dart
@R(E(null).f()) // crashes
extension E on Object {}

const e = E(null).f(); // crashes
```

```
Unhandled exception:
Exception: Missing implementation of visitExtensionOverrideImpl
#0      ThrowingAstVisitor._throw (package:analyzer/dart/ast/visitor.dart:2099:5)
#1      ThrowingAstVisitor.visitExtensionOverride (package:analyzer/dart/ast/visitor.dart:1844:55)
#2      ExtensionOverrideImpl.accept (package:analyzer/src/dart/ast/ast.dart:4012:20)
#3      AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:1653:31)
#4      AstBinaryWriter.visitArgumentList (package:analyzer/src/summary2/ast_binary_writer.dart:71:31)
#5      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#6      AstBinaryWriter.visitAnnotation (package:analyzer/src/summary2/ast_binary_writer.dart:53:37)
#7      AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:285:49)
#8      AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:1653:31)
#9      AstBinaryWriter._storeAnnotatedNode (package:analyzer/src/summary2/ast_binary_writer.dart:1472:38)
#10     AstBinaryWriter._storeDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:1500:5)
```

**Comment by MichaelRFairhurst** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/117124
