### ISSUE TITLE
dart analysis server crashing constantly

### ISSUE THREAD

**Issue by allenbrunson** [dart-lang/sdk#38367]
i just updated to flutter 1.9.1 hotfix 2, and the dart analysis server is crashing constantly, and also using way more cpu time than usual, spinning up the fans a lot.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1200`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Failed to handle completion domain request: {id: 77, method: completion.getSuggestions, params: {file: /Users/allen/dart/dartlib/touchlib/lib/widgets/net_response_widget.dart, offset: 1692}, clientRequestTime: 1568328802329}
Exception: Element not found in summary: dart:core;dart:core;Never
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:338:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:359:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:34:43)
#3      ElementHandle.librarySource (package:analyzer/src/dart/element/handle.dart:462:31)
#4      createExistingImportsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:101:19)
#5      CompletionDomainHandler.processRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:403:11)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#14     CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart)
<asynchronous suspension>
#15     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#16     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1500:12)
#21     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#22     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#30     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#31     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#32     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#33     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#42     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#43     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#44     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#52     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#53     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#54     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#55     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#56     _Utf8...
```

For additional log information, please append the contents of
file:///private/var/folders/c4/6g25_59s4hn74_x13_6l51z00000gn/T/report.txt.

**Comment by scheglov** [comment]
It was fixed in ce7232cd0f7a6739d2021520bfc4277a95e8b4e3 and 2ada1edb59003ed02236efcb06ac671c7c30fdb8.
