### ISSUE TITLE
[kernel] 'Type parameter is not indexed' error when compiling some mocked generic functions.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#38384]
Snippet:
```
class Built<X, Y> {}

class Foo {
  foo<S extends Built<S, B>, B extends Built<S, B>>() {
  }
}

class Mock {
  noSuchMethod(Invocation i) {}
}

class MockFoo extends Mock implements Foo {}

main() {}
```

Passes in DDC but crashes in CFE with:
```
Invalid argument(s): Type parameter B is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:2533:8)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2101:38)
#2      TypeParameterType.accept (package:kernel/ast.dart:5559:42)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:388:10)
#4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#5      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:298:7)
#6      BinaryPrinter.visitInterfaceType (package:kernel/binary/ast_to_binary.dart:2041:7)
#7      InterfaceType.accept (package:kernel/ast.dart:5272:42)
#8      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:388:10)
#9      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#10     BinaryPrinter.visitTypeParameter (package:kernel/binary/ast_to_binary.dart:2118:5)
#11     TypeParameter.accept (package:kernel/ast.dart:5771:38)
#12     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:388:10)
#13     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#14     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:298:7)
#15     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1307:5)
#16     FunctionNode.accept (package:kernel/ast.dart:2323:38)
#17     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:395:10)
#18     BinaryPrinter.writeOptionalFunctionNode (package:kernel/binary/ast_to_binary.dart:490:7)
#19     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1189:5)
#20     Procedure.accept (package:kernel/ast.dart:1988:40)
#21     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:416:10)
#22     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:307:7)
#23     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1117:5)
#24     Class.accept (package:kernel/ast.dart:1038:38)
#25     BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:430:10)
#26     BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:325:7)
#27     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:949:5)
#28     Library.accept (package:kernel/ast.dart:464:38)
#29     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:409:10)
#30     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:52:31)
#31     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:557:5)
#32     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:75:11)
```

**Comment by leafpetersen** [comment]
Are you sure that's the right repro?  That example does crash the CFE, but it's also rejected by DDC and the analyzer.

**Comment by Markzipan** [comment]
Sorry about that - overzealous deleting here. I've updated the original with the real repro.

**Comment by askeksa-google** [comment]
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/118047
