### ISSUE TITLE
Analyzer fuzz crash: unsupported operation, cascade on extension override

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38417]
```dart
extension C on Object {
  int get y => 0;
}

var x = C(null)..y;
```

```
Unhandled exception:
Unsupported operation: cascaded extension override
#0      ElementResolver.visitPropertyAccess (package:analyzer/src/generated/element_resolver.dart:697:9)
#1      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8492:49)
#2      ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:4254:10)
#3      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8492:49)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#5      CascadeExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1278:22)
#6      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4215:10)
#7      UnifyingAstVisitor.visitCascadeExpression (package:analyzer/dart/ast/visitor.dart:3140:55)
#8      ResolverVisitor.visitCascadeExpression (package:analyzer/src/generated/resolver.dart:3482:11)
#9      CascadeExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1273:49)
#10     AstResolver.resolve (package:analyzer/src/summary2/ast_resolver.dart:60:10)
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/117461
