### ISSUE TITLE
Analyzer crash in _addFix_importLibrary_withExtension: ListLiteralImpl not a subtype of SimpleIdentifier

### ISSUE THREAD

**Issue by hpoit** [dart-lang/sdk#38437]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-192.6262.59`
- `2.6.0-dev.0.0`
- `WS-192.6262.59, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900, 1280x800`

## Exception
```
Dart analysis server, SDK version 2.6.0-dev.0.0, server version 1.27.3, FATAL error: Failed to handle request: {id: 1446, method: edit.getFixes, params: {file: /Users/johnappleseed/WebstormProjects/app1_v0.0.5/lib/src/realty/realty_service.dart, offset: 1636}, clientRequestTime: 1568743749079}
type 'ListLiteralImpl' is not a subtype of type 'SimpleIdentifier' in type cast
#0      FixProcessor._addFix_importLibrary_withExtension (package:analysis_server/src/services/correction/fix_internal.dart:2728:34)
<asynchronous suspension>
#1      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:466:13)
<asynchronous suspension>
#2      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:67:41)
<asynchronous suspension>
#3      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:656:46)
<asynchronous suspension>
#4      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:763:14)
<asynchronous suspension>
#5      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:283:32)
<asynchronous suspension>
#6      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:387:9)
#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:335:45)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#9      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:331:50)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1500:12)
#14     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:330:5)
#15     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#17     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#18     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#50     _StreamController._add (dart:async/stream_controller.dart:640:7)
#51     _StreamController.add (dart:async/stream_controller.dart:586:5)
#52     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#53     _rootRunUnary (dart:async/zone.dart:1136:13)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _CustomZ...
```

For additional log information, please append the contents of
file:///private/var/folders/51/h377tw1x4plf6mxbd6pn_1yr0000gn/T/report.txt.

**Comment by DanTup** [comment]
I just saw this too. I can repro with this code:

```dart
main() {
  testUsingContext('Chrome device is available when Chrome is available', () async {
    final Future<List<Device> devices = await deviceManager.getAllConnectedDevices().toList();
    expect(devices, contains(isInstanceOf<ChromeDevice>()));
  });
}
```

`getFixes` was invoked after the `>` in `Future<List<Device> devices` (I deleted the second `>` as I was removing the `Future` wrapping the code as I added the `await`).

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/123480
