### ISSUE TITLE
dart issue

### ISSUE THREAD

**Issue by xzhangxian1008** [dart-lang/sdk#38447]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
NoSuchMethodError: The setter 'previous=' was called on null.
Receiver: null
Tried calling: previous=Instance of 'SimpleToken'
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      SimpleToken.setNext (package:front_end/src/scanner/token.dart:599:11)
#2      scannerRecovery (package:front_end/src/fasta/scanner/recover.dart:205:16)
#3      _tokenizeAndRecover (package:front_end/src/fasta/scanner.dart:103:14)
#4      scanString (package:front_end/src/fasta/scanner.dart:95:10)
#5      Scanner.tokenize (package:analyzer/src/dart/scanner/scanner.dart:146:34)
#6      _File._parse (package:analyzer/src/services/available_declarations.dart:1652:25)
#7      _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#8      DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:615:14)
#9      _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1474:20)
#10     _File.refresh (package:analyzer/src/services/available_declarations.dart:1088:21)
#11     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:601:14)
#12     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:514:18)
#13     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#14     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#15     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#16     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#17     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#18     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#19     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#25     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#26     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#27     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#28     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#29     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#37     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#38     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#39     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#40     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#41     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\xzx\AppData\Local\Temp\report.txt.

**Comment by dgrove** [comment]
This is from a fairly old version of Dart. Does it reproduce with Dart 2.6?

**Comment by xzhangxian1008** [comment]
> This is from a fairly old version of Dart. Does it reproduce with Dart 2.6?

My dart version is 2.5.Is the problem related with the dart version?Should I uninstall the dart and install it again?

**Comment by xzhangxian1008** [comment]
> This is from a fairly old version of Dart. Does it reproduce with Dart 2.6?

I have solved my problem after reinstalling my flutter.There may be something wrong in my flutter.

**Comment by srawlins** [comment]
The version of Dart in this bug report is 2.4.0. It looks like you've since bumped to 2.5.0 (perhaps via Flutter upgrade).

Please re-open if you encounter this again.
