### ISSUE TITLE
Failed to handle completion domain request

### ISSUE THREAD

**Issue by praharshbhatt** [dart-lang/sdk#38476]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.6.0-edge.7799f424f4a2ba35ce9f64593e5e593a1a553f67`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.7799f424f4a2ba35ce9f64593e5e593a1a553f67, server version 1.27.3, error: Failed to handle completion domain request: {id: 1493, method: completion.getSuggestionDetails, params: {file: D:\Multiverse_Projects\Flutter\Projects\recomposer2\recomposer2\lib\screens\login.dart, id: 1381, label: roundedShape, offset: 3618}, clientRequestTime: 1568873867535}
NoSuchMethodError: The getter 'source' was called on null.
Receiver: null
Tried calling: source
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      DartFileEditBuilderImpl.importLibraryElement (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1298:34)
#2      CompletionDomainHandler.getSuggestionDetails.<anonymous closure> (package:analysis_server/src/domain_completion.dart:204:32)
#3      DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:54:20)
#4      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#5      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:51:18)
#6      CompletionDomainHandler.getSuggestionDetails (package:analysis_server/src/domain_completion.dart:203:23)
<asynchronous suspension>
#7      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:242:9)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1500:12)
#12     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:238:12)
#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:335:45)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#15     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:331:50)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1500:12)
#20     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:330:5)
#21     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#23     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#24     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#32     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#33     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#34     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#35     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#37     _rootRunUnary (dart:async/zone.dart:1132:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#42     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#43     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#44     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#45     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#46     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#47     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#48     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#53     _BufferingStreamSubscription._sendData (d...
```

For additional log information, please append the contents of
file://C:\Users\prahu\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.7.0. Please re-open if you see this crash again.
