### ISSUE TITLE
Error analyzing

### ISSUE THREAD

**Issue by TobiasHeidingsfeld** [dart-lang/sdk#38498]
### What I was doing

Coding

### Versions

- Flutter SDK 1.10.6-pre.19
- Visual Studio Code 1.38.1
- Dart Code 3.4.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\Tools\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.4.1
```

### Exception

Analysis failed: C:\Repo\Hoops\HoopsGit\server\hoops_server\bin\hoopsserver.dart context: exception_20190920_185605_886

```text
NoSuchMethodError: Class 'NamedTypeBuilder' has no instance getter 'isBottom'.
Receiver: Instance of 'NamedTypeBuilder'
Tried calling: isBottom
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      TypeBuilder.noSuchMethod (package:analyzer/src/summary2/type_builder.dart:16:18)
#2      NamedTypeBuilder.isBottom (package:analyzer/dart/element/type.dart:44:12)
#3      LinkingBundleContext.writeType (package:analyzer/src/summary2/linking_bundle_context.dart:81:14)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      LinkingBundleContext.writeType (package:analyzer/src/summary2/linking_bundle_context.dart:96:67)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#8      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#9      LinkingBundleContext.writeType (package:analyzer/src/summary2/linking_bundle_context.dart:96:67)
#10     AstBinaryWriter._writeType (package:analyzer/src/summary2/ast_binary_writer.dart:1674:28)
#11     AstBinaryWriter._writeActualType (package:analyzer/src/summary2/ast_binary_writer.dart:1654:26)
#12     AstBinaryWriter.visitVariableDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:1398:5)
#13     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10539:49)
#14     AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:1668:31)
#15     AstBinaryWriter.visitVariableDeclarationList (package:analyzer/src/summary2/ast_binary_writer.dart:1407:42)
#16     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10635:15)
#17     AstBinaryWriter.visitFieldDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:540:44)
#18     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4095:49)
#19     AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:1668:31)
#20     AstBinaryWriter._storeClassOrMixinDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:1499:43)
#21     AstBinaryWriter.visitClassDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:221:7)
#22     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#23     AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:1668:31)
#24     AstBinaryWriter.visitCompilationUnit (package:analyzer/src/summary2/ast_binary_writer.dart:286:37)
#25     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#26     AstBinaryWriter.writeUnit (package:analyzer/src/summary2/ast_binary_writer.dart:1457:19)
#27     Linker._createLinkingBundle (package:analyzer/src/summary2/link.dart:183:37)
#28     Linker.link (package:analyzer/src/summary2/link.dart:86:5)
#29     link (package:analyzer/src/summary2/link.dart:35:10)
#30     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:318:26)
#31     SetMixin.forEach (dart:collection/set.dart:146:30)
#32     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:273:32)
#33     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:370:17)
#34     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#35     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:368:12)
#36     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:95:7)
#37     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1439:29)
#38     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1246:30)
#39     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#40     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#41     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
<asynchronous suspension>
#42     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1931:24)
<asynchronous suspension>
#43     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1865:5)
#44     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#45     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#46     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#47     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:568:21)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _runZoned (dart:async/zone.dart:1516:10)
#51     runZoned (dart:async/zone.dart:1463:12)
#52     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:685:12)
#53     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:566:7)
#54     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:467:9)
#55     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#56     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:462:43)
#57     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#58     new Future.sync (dart:async/future.dart:224:31)
#59     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#60     _rootRun (dart:async/zone.dart:1124:13)
#61     _CustomZone.run (dart:async/zone.dart:1021:19)
#62     _runZoned (dart:async/zone.dart:1516:10)
#63     runZoned (dart:async/zone.dart:1463:12)
#64     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#65     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:142:56)
#66     Driver.start (package:analysis_server/src/server/driver.dart:462:21)
#67     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#68     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#69     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#70     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "C:\\Repo\\Hoops\\HoopsGit\\copy\\powerflutter_server",
        "explicitFileCount": 9,
        "implicitFileCount": -9,
        "workItemQueueLength": 9,
        "cacheEntryExceptions": []
    },
    {
        "name": "C:\\Repo\\Hoops\\HoopsGit\\copy\\powerflutter_code_generation",
        "explicitFileCount": 3,
        "implicitFileCount": -3,
        "workItemQueueLength": 3,
        "cacheEntryExceptions": []
    },
    {
        "name": "C:\\Repo\\Hoops\\HoopsGit\\client\\hoops",
        "explicitFileCount": 30,
        "implicitFileCount": -30,
        "workItemQueueLength": 30,
        "cacheEntryExceptions": []
    },
    {
        "name": "C:\\Repo\\Hoops\\HoopsGit\\copy\\powerflutter",
        "explicitFileCount": 11,
        "implicitFileCount": -11,
        "workItemQueueLength": 11,
        "cacheEntryExceptions": []
    },
    {
        "name": "C:\\Repo\\Hoops\\HoopsGit\\server\\hoops_server",
        "explicitFileCount": 2,
        "implicitFileCount": 378,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    },
    {
        "name": "C:\\Repo\\Hoops\\HoopsGit\\shared\\hoops_shared",
        "explicitFileCount": 3,
        "implicitFileCount": -3,
        "workItemQueueLength": 3,
        "cacheEntryExceptions": []
    },
    {
        "name": "C:\\Repo\\Hoops\\HoopsGit\\copy\\powerflutter_base",
        "explicitFileCount": 10,
        "implicitFileCount": -10,
        "workItemQueueLength": 10,
        "cacheEntryExceptions": []
    },
    {
        "name": "C:\\Repo\\Hoops\\HoopsGit\\server\\hoops_admin",
        "explicitFileCount": 6,
        "implicitFileCount": -6,
        "workItemQueueLength": 6,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment]
Looks like the first report with this error.

**Comment by srawlins** [comment]
FYI @scheglov , top of the stack trace says summary2.

**Comment by scheglov** [comment]
I will not able to reproduce this errors, and fix it correspondingly, without a test case on which it crashes like this :-(

**Comment by srawlins** [comment]
@TobiasHeidingsfeld is there any way you can paste the contents of hoopsserver.dart? Or maybe minimally reproduce with a smaller file?

**Comment by TobiasHeidingsfeld** [comment]
I happens now on a lot of files. Here is same file where it happens:
import 'package:poker_shared/poker_shared.dart';
import 'package:powerflutter_server/powerflutter_server.dart';

class PokerClient extends PowerClient {
  PokerUser get user => store.get("user", () => null);
  set user(PokerUser value) => store.set("user", value);

  PokerCard get card1 => store.get("card1", () => null);
  set card1(PokerCard value) => store.set("card1", value);

  PokerCard get card2 => store.get("card2", () => null);
  set card2(PokerCard value) => store.set("card2", value);

  HandScore get hand => store.get("hand", () => null);
  set hand(HandScore value) => store.set("hand", value);

  @override
  void created() {}

  @override
  void dispose() {
    Power.getDI<PowerDB>().save(user);
   
  }
}

**Comment by scheglov** [comment]
Well, I tried this file, but cannot reproduce. This is actually expected, because the error like this happens with types, and types move across libraries, and just standalone file is not enough. I might have to have much more files (and I don't know which). Ideally, if I get the complete project, but this might be not what you comfortable to do. If you choose to send something, you can do this to my e-mail `scheglov@google.com`. Obviously, I don't have any interest in your IP and will remove it once I'm done fixing the issue.

As a possible work around, you might also try to remove `~/.dartServer` or `C:\Users\scheglov\AppData\Local\.dartServer` on Windows and restart the Dart Analysis Server (maybe just restart your IDE). So, everything will be re-analyzed and if the issue was caused by a temporary invalid state of code, it will be gone.

**Comment by TobiasHeidingsfeld** [comment]
I narrowed it down to:
import 'package:powerflutter_server/powerflutter_server.dart';
causing the error on a fresh and otherwise empty project

**Comment by TobiasHeidingsfeld** [comment]
deleting /.dartServer seems to fix the issue for now

**Comment by scheglov** [comment]
`powerflutter_server` does not seem to be published at the moment.

Good to know that it works for now.
Hopefully if it happens for other users, we might get better luck with narrower test cases.

**Comment by TobiasHeidingsfeld** [comment]
The problem comes again and again very quickly. I can confirm that it DOES NOT happen on stable but does happen on dev and master channels. So something must have changed there causing the bug

**Comment by scheglov** [comment]
I need your help to find and fix this.

If there is a project on which it is reliably reproducible, please send it to my email.

If there is no such project, I might get some data from a file like `exception_20190920_185605_886` that is put into `.dartServer` directory (probably in a sub-dir). Note, that it also contains portion of your source code. So, you might not want to share it completely public.

**Comment by TobiasHeidingsfeld** [comment]
I just send the exception file (the one mentioned was deleted but should be the same error poping up again and again)

**Comment by scheglov** [comment]
Thank you!
I was able to reproduce it, but have not looked yet into details.
Will look tomorrow.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/119166

**Comment by TobiasHeidingsfeld** [comment]
Will a fix come soon (on master?)? Or can I fixed it by chaning my code somehow to not trigger the bug?
