### ISSUE TITLE
Analyzer fuzz crash: invoking extension override with no call method

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38505]
```dart
extension E on Object {}
f() {
  E(null)();
}
```

Adding call() to E fixes the crash.

```
NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ElementResolver.visitFunctionExpressionInvocation (package:analyzer/src/generated/element_resolver.dart:406:29)
#2      FunctionExpressionInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5152:15)
#3      ResolverVisitor.visitFunctionExpressionInvocation (package:analyzer/src/generated/resolver.dart:3993:10)
#4      FunctionExpressionInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5152:15)
#5      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3772:18)
#6      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4215:10)
#7      UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3214:59)
#8      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3768:49)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#10     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/118481
