### ISSUE TITLE
Analyzer fuzz crash: duplicate library element with one library annotation

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38506]
```dart
library c;
@foo
library c;
```

One interesting note is that it must be the 2nd `library` that is annotated or the bad state is not found.

doesn't fails for classes. I didn't check enums/extensions/mixins/etc etc. though those may have similar problems.

```
Unhandled exception:
_ElementMismatchException: Element mismatch in /test/lib/test.dart at /test/lib/test.dart
Caused by Bad state: Found 1 annotation nodes and 0 element annotations
#0      DeclarationResolver.resolveAnnotations (package:analyzer/src/generated/declaration_resolver.dart:578:7)
#1      DeclarationResolver.visitLibraryDirective (package:analyzer/src/generated/declaration_resolver.dart:356:5)
#2      LibraryDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:6687:49)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#4      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2160:19)
#5      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#6      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#7      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:45:12)
#8      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:654:31)
#9      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:160:7)
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/125521
