### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by wangwanchao** [dart-lang/sdk#38515]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `<NO SDK>`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version , FATAL error: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      FolderBasedDartSdk.getSdkProperty (package:analyzer/src/dart/sdk/sdk.dart:697:14)
#2      FolderBasedDartSdk.defaultSdkDirectory (package:analyzer/src/dart/sdk/sdk.dart:684:26)
#3      Driver._getSdkPath (package:analysis_server/src/server/driver.dart:758:33)
#4      Driver.start (package:analysis_server/src/server/driver.dart:394:28)
#5      main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/92/w1t6hptx5fq4_7nd87v8xy8w0000gn/T/report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.4.0. Please re-open if you see this crash again.
