### ISSUE TITLE
Failed to handle completion domain request

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#38513]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing
At end of following line:
```dart
typedef setConsoleCursorInfo = Int8 Function(Int32 hConsoleOutput, Pointer<CONSOLE_CURSOR_INFO>)
```
### Versions

- Flutter SDK 1.10.6-pre.26
- Visual Studio Code 1.38.1
- Dart Code 3.4.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
c:\git\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.4.1
```

### Exception

Failed to handle completion domain request: {id: 11009, method: completion.getSuggestions, params: {file: C:\git\dart_console\lib\src\ffi\win\kernel.dart, offset: 1880}, clientRequestTime: 1569104326375}

```text
NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _OpTypeAstVisitor.visitSimpleFormalParameter (package:analyzer_plugin/src/utilities/completion/optype.dart:1059:30)
#2      _OpTypeAstVisitor.visitFormalParameterList (package:analyzer_plugin/src/utilities/completion/optype.dart:713:7)
#3      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4554:49)
#4      new OpType.forCompletion (package:analyzer_plugin/src/utilities/completion/optype.dart:152:16)
#5      DartCompletionRequestImpl.opType (package:analysis_server/src/services/completion/dart/completion_manager.dart:390:21)
#6      DartCompletionManager._addIncludedElementKinds (package:analysis_server/src/services/completion/dart/completion_manager.dart:198:26)
#7      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:133:7)
<asynchronous suspension>
#8      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:121:42)
<asynchronous suspension>
#9      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:356:5)
<asynchronous suspension>
#10     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:245:9)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1500:12)
#15     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:238:12)
#16     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:335:45)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:331:50)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1500:12)
#23     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:330:5)
#24     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#26     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#27     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#36     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#37     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#38     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#47     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#48     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#49     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#50     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#51     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#52     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#53     _rootRunUnary (dart:async/zone.dart:1132:38)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#58     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#59     _StreamController._add (dart:async/stream_controller.dart:640:7)
#60     _StreamController.add (dart:async/stream_controller.dart:586:5)
#61     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#62     _rootRunUnary (dart:async/zone.dart:1136:13)
#63     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#67     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#68     _StreamController._add (dart:async/stream_controller.dart:640:7)
#69     _StreamController.add (dart:async/stream_controller.dart:586:5)
#70     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
#71     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
#72     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#73     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#74     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#75     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "C:\\git\\dart_console\\example",
        "explicitFileCount": 10,
        "implicitFileCount": 154,
        "workItemQueueLength": 10,
        "cacheEntryExceptions": []
    },
    {
        "name": "C:\\git\\dart_console",
        "explicitFileCount": 12,
        "implicitFileCount": 356,
        "workItemQueueLength": 12,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment]
I just attempted to reproduce with the following code
```
class Int8 {}
class Int32 {}
class Pointer<T> {}
class CONSOLE_CURSOR_INFO {}

typedef setConsoleCursorInfo = Int8 Function(Int32 hConsoleOutput, Pointer<CONSOLE_CURSOR_INFO>)
```
I attempted to complete both before and after the closing paren and there was no exception. Given how long ago this issue was opened, I'm going to assume that the bug has been fixed.
