### ISSUE TITLE
dart:ffi hello_world example for windows not working

### ISSUE THREAD

**Issue by phanirithvij** [dart-lang/sdk#38516]
* Dart SDK Version `Dart VM version: 2.5.0 (Fri Sep 6 20:39:27 2019 +0200) on "windows_x64"`
* Windows

To reproduce
- install stable dart-sdk from https://dart.dev/get-dart
- `git clone https://github.com/dart-lang/samples`
- `cd samples/ffi/hello_world/c`
- `make dylib`

Which `gcc` do I use on windows?
Right now I'm using [`msys2`](https://www.msys2.org/) i.e. `msys64, mingw32-make.exe`
And it doesn't recognise `-undefined supress` and `-flat_namespace`

```shell
$ gcc -dynamiclib -undefined suppress -flat_namespace hello.o -o ../hello_world.dylib
gcc: error: suppress: No such file or directory
gcc: error: unrecognized command line option '-flat_namespace'
mingw32-make: *** [Makefile:8: dylib] Error 1
```

**Comment by phanirithvij** [comment]
It is creating a dynamiclib without `-undefined suppress -flat_namespace` but the dart:ffi DynamicLibrary.lookup fails on such dynamiclib
```dart
Unhandled exception:
Invalid argument(s): Failed to lookup symbol (127)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:29)
#1      main (file:///D:/Projects/fun/dart-u-bastard/samples/ffi/hello_world/hello.dart:17:8)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by phanirithvij** [comment]
This was my mistake the process of making a shared library in windows is

```shell
gcc -shared -o hello_world.dll hello.o
```
So, the Makefile now should look like

```makefile
hello: hello.o
	gcc -o a.out hello.o

hello.o: hello.c
	gcc -c hello.c

dll: hello.o
	gcc -shared hello.o -o ../hello_world.dll

clean:
	rm a.out hello.o ../hello_world.dll
```
And in `hello.dart` use
```dart
final dylib = ffi.DynamicLibrary.open('hello_world.dll');
```

**Comment by phanirithvij** [comment]
It works. But I'm leaving this open for now till the docs get updated.

**Comment by phanirithvij** [comment]
Moved to https://github.com/dart-lang/samples/issues/7
