### ISSUE TITLE
Crash when formatting: [DuplicatedDeclarationCause] Previous declaration of 'z'.

### ISSUE THREAD

**Issue by sortie** [dart-lang/sdk#38523]
I found a compiler crash in the front end when compiling an invalid program using Dart 2.5.0 on linux-x64. It also happens with the latest bleeding SDK built from f546362691fe17b38298e5d9baa25c0c292f5448. It happens when I have two files `a.dart` and `b.dart` that's part of the same library.

```dart
library l;

part "b.dart";
```

```dart
// x

part of l;

x() {
  y(z, {z}) {}
}
```

This is the smallest reproducible example I've found. The program is invalid because it defines the named parameter z which is also the name of a regular parameter. The crash does not happen if I use b.dart as the main program (without the part). The crash does not happen if the inner function is moved outside of the outer function. The crash does not happen if the comment at the start of `b.dart` is removed (if you can't reproduce it, try add a lot more x's at the top).

The crash can be reproduced using:

```bash
dart a.dart
```
Fasta crashes as follows:

```
Crash when formatting: [DuplicatedDeclarationCause] Previous declaration of 'z'.
RangeError: Value not in range: 28
#0      _StringBase.substring (dart:core-patch/string_patch.dart:386:7)
#1      Source.getTextLine (package:kernel/ast.dart:6483:25)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:86:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:203:9)
#5      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:208:31)
#6      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:224:29)
#7      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:68:13)
#8      Loader.addMessage (package:front_end/src/fasta/loader.dart:320:20)
#9      Loader.addProblem (package:front_end/src/fasta/loader.dart:271:12)
#10     LibraryBuilder.addProblem (package:front_end/src/fasta/builder/library_builder.dart:128:19)
#11     SourceLibraryBuilder.addProblem (package:front_end/src/fasta/source/source_library_builder.dart:1199:47)
#12     BodyBuilder.addProblem (package:front_end/src/fasta/kernel/body_builder.dart:5400:13)
#13     BodyBuilder.reportDuplicatedDeclaration (package:front_end/src/fasta/kernel/body_builder.dart:5429:5)
#14     FormalParameters.computeFormalParameterScope (package:front_end/src/fasta/kernel/body_builder.dart:5762:16)
#15     BodyBuilder.endFormalParameters (package:front_end/src/fasta/kernel/body_builder.dart:3186:19)
#16     Parser.parseFormalParametersRest (package:front_end/src/fasta/parser/parser.dart:1280:14)
#17     Parser.parseFormalParametersRequiredOpt (package:front_end/src/fasta/parser/parser.dart:1206:12)
#18     Parser.parseNamedFunctionRest (package:front_end/src/fasta/parser/parser.dart:3430:13)
#19     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5266:16)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3726:14)
#21     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#22     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#23     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:867:14)
#24     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:330:5)
#25     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2462:14)
#26     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2340:14)
#27     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:493:14)
#28     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#29     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:305:18)
<asynchronous suspension>
#30     Loader.buildBodies (package:front_end/src/fasta/loader.dart:227:15)
<asynchronous suspension>
#31     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:301:20)
<asynchronous suspension>
#32     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#33     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:299:12)
<asynchronous suspension>
#34     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:38)
<asynchronous suspension>
#35     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#36     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:69:10)
<asynchronous suspension>
#37     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:49:18)
<asynchronous suspension>
#38     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:134:20)
<asynchronous suspension>
#39     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#40     new Future.sync (dart:async/future.dart:224:31)
#41     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#42     _rootRun (dart:async/zone.dart:1124:13)
#43     _CustomZone.run (dart:async/zone.dart:1021:19)
#44     _runZoned (dart:async/zone.dart:1516:10)
#45     runZoned (dart:async/zone.dart:1463:12)
#46     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#47     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:132:10)
#48     generateKernel (package:front_end/src/kernel_generator_impl.dart:48:32)
<asynchronous suspension>
#49     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:98:17)
<asynchronous suspension>
#50     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:317:17)
<asynchronous suspension>
#51     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:155:45)
<asynchronous suspension>
#52     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#53     _rootRun (dart:async/zone.dart:1120:38)
#54     _CustomZone.run (dart:async/zone.dart:1021:19)
#55     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#56     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#57     _rootRun (dart:async/zone.dart:1124:13)
#58     _CustomZone.run (dart:async/zone.dart:1021:19)
#59     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#60     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#61     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#62     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#63     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Crash when compiling file:///tmp/b.dart,
at character offset 20:
Crash when compiling file:///tmp/a.dart,
at character offset 28:
RangeError: Value not in range: 28
#0      _StringBase.substring (dart:core-patch/string_patch.dart:386:7)
#1      Source.getTextLine (package:kernel/ast.dart:6483:25)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:86:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:203:9)
#5      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:208:31)
#6      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:224:29)
#7      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:68:13)
#8      Loader.addMessage (package:front_end/src/fasta/loader.dart:320:20)
#9      Loader.addProblem (package:front_end/src/fasta/loader.dart:271:12)
#10     LibraryBuilder.addProblem (package:front_end/src/fasta/builder/library_builder.dart:128:19)
#11     SourceLibraryBuilder.addProblem (package:front_end/src/fasta/source/source_library_builder.dart:1199:47)
#12     BodyBuilder.addProblem (package:front_end/src/fasta/kernel/body_builder.dart:5400:13)
#13     BodyBuilder.reportDuplicatedDeclaration (package:front_end/src/fasta/kernel/body_builder.dart:5429:5)
#14     FormalParameters.computeFormalParameterScope (package:front_end/src/fasta/kernel/body_builder.dart:5762:16)
#15     BodyBuilder.endFormalParameters (package:front_end/src/fasta/kernel/body_builder.dart:3186:19)
#16     Parser.parseFormalParametersRest (package:front_end/src/fasta/parser/parser.dart:1280:14)
#17     Parser.parseFormalParametersRequiredOpt (package:front_end/src/fasta/parser/parser.dart:1206:12)
#18     Parser.parseNamedFunctionRest (package:front_end/src/fasta/parser/parser.dart:3430:13)
#19     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5266:16)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3726:14)
#21     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#22     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#23     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:867:14)
#24     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:330:5)
#25     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2462:14)
#26     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2340:14)
#27     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:493:14)
#28     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#29     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:305:18)
<asynchronous suspension>
#30     Loader.buildBodies (package:front_end/src/fasta/loader.dart:227:15)
<asynchronous suspension>
#31     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:301:20)
<asynchronous suspension>
#32     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#33     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:299:12)
<asynchronous suspension>
#34     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:38)
<asynchronous suspension>
#35     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#36     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:69:10)
<asynchronous suspension>
#37     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:49:18)
<asynchronous suspension>
#38     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:134:20)
<asynchronous suspension>
#39     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#40     new Future.sync (dart:async/future.dart:224:31)
#41     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#42     _rootRun (dart:async/zone.dart:1124:13)
#43     _CustomZone.run (dart:async/zone.dart:1021:19)
#44     _runZoned (dart:async/zone.dart:1516:10)
#45     runZoned (dart:async/zone.dart:1463:12)
#46     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#47     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:132:10)
#48     generateKernel (package:front_end/src/kernel_generator_impl.dart:48:32)
<asynchronous suspension>
#49     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:98:17)
<asynchronous suspension>
#50     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:317:17)
<asynchronous suspension>
#51     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:155:45)
<asynchronous suspension>
#52     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#53     _rootRun (dart:async/zone.dart:1120:38)
#54     _CustomZone.run (dart:async/zone.dart:1021:19)
#55     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#56     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#57     _rootRun (dart:async/zone.dart:1124:13)
#58     _CustomZone.run (dart:async/zone.dart:1021:19)
#59     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#60     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#61     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#62     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#63     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


#0      format (package:front_end/src/fasta/command_line_reporting.dart:97:5)
#1      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:203:9)
#2      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:208:31)
#3      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:224:29)
#4      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:68:13)
#5      Loader.addMessage (package:front_end/src/fasta/loader.dart:320:20)
#6      Loader.addProblem (package:front_end/src/fasta/loader.dart:271:12)
#7      LibraryBuilder.addProblem (package:front_end/src/fasta/builder/library_builder.dart:128:19)
#8      SourceLibraryBuilder.addProblem (package:front_end/src/fasta/source/source_library_builder.dart:1199:47)
#9      BodyBuilder.addProblem (package:front_end/src/fasta/kernel/body_builder.dart:5400:13)
#10     BodyBuilder.reportDuplicatedDeclaration (package:front_end/src/fasta/kernel/body_builder.dart:5429:5)
#11     FormalParameters.computeFormalParameterScope (package:front_end/src/fasta/kernel/body_builder.dart:5762:16)
#12     BodyBuilder.endFormalParameters (package:front_end/src/fasta/kernel/body_builder.dart:3186:19)
#13     Parser.parseFormalParametersRest (package:front_end/src/fasta/parser/parser.dart:1280:14)
#14     Parser.parseFormalParametersRequiredOpt (package:front_end/src/fasta/parser/parser.dart:1206:12)
#15     Parser.parseNamedFunctionRest (package:front_end/src/fasta/parser/parser.dart:3430:13)
#16     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5266:16)
#17     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3726:14)
#18     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#19     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#20     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:867:14)
#21     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:330:5)
#22     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2462:14)
#23     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2340:14)
#24     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:493:14)
#25     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#26     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:305:18)
<asynchronous suspension>
#27     Loader.buildBodies (package:front_end/src/fasta/loader.dart:227:15)
<asynchronous suspension>
#28     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:301:20)
<asynchronous suspension>
#29     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#30     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:299:12)
<asynchronous suspension>
#31     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:38)
<asynchronous suspension>
#32     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#33     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:69:10)
<asynchronous suspension>
#34     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:49:18)
<asynchronous suspension>
#35     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:134:20)
<asynchronous suspension>
#36     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#37     new Future.sync (dart:async/future.dart:224:31)
#38     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#39     _rootRun (dart:async/zone.dart:1124:13)
#40     _CustomZone.run (dart:async/zone.dart:1021:19)
#41     _runZoned (dart:async/zone.dart:1516:10)
#42     runZoned (dart:async/zone.dart:1463:12)
#43     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#44     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:132:10)
#45     generateKernel (package:front_end/src/kernel_generator_impl.dart:48:32)
<asynchronous suspension>
#46     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:98:17)
<asynchronous suspension>
#47     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:317:17)
<asynchronous suspension>
#48     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:155:45)
<asynchronous suspension>
#49     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#50     _rootRun (dart:async/zone.dart:1120:38)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#53     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#54     _rootRun (dart:async/zone.dart:1124:13)
#55     _CustomZone.run (dart:async/zone.dart:1021:19)
#56     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#57     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#58     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#59     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:875:7)
#1      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:330:5)
#2      Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2462:14)
#3      Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2340:14)
#4      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:493:14)
#5      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#6      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:305:18)
<asynchronous suspension>
#7      Loader.buildBodies (package:front_end/src/fasta/loader.dart:227:15)
<asynchronous suspension>
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:301:20)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#10     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:299:12)
<asynchronous suspension>
#11     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:38)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#13     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:69:10)
<asynchronous suspension>
#14     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:49:18)
<asynchronous suspension>
#15     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:134:20)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#17     new Future.sync (dart:async/future.dart:224:31)
#18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#24     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:132:10)
#25     generateKernel (package:front_end/src/kernel_generator_impl.dart:48:32)
<asynchronous suspension>
#26     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:98:17)
<asynchronous suspension>
#27     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:317:17)
<asynchronous suspension>
#28     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:155:45)
<asynchronous suspension>
#29     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#30     _rootRun (dart:async/zone.dart:1120:38)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#37     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#38     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#39     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by jensjoha** [comment]
Thanks! Fixed in https://dart-review.googlesource.com/c/sdk/+/118448.

**Comment by sortie** [comment]
Happy to report any issues I come across! Thanks Jens for the quick fix!
