### ISSUE TITLE
dart2native crashes when passing unknown flag

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#38525]
```
$ ~/tmp/dart-sdk-be/bin/dart2native -v
Unhandled exception:
FormatException: Could not find an option or flag "-v".
#0      Parser.validate (package:args/src/parser.dart:261:21)
#1      Parser.parseSoloOption (package:args/src/parser.dart:134:7)
#2      Parser.parse (package:args/src/parser.dart:88:11)
#3      ArgParser.parse (package:args/src/arg_parser.dart:320:45)
#4      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dart2native/bin/dart2native.dart:100:40)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#6      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dart2native/bin/dart2native.dart:78:18)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
$
```

It would be nice to catch this, and just show the output of `-h`

**Comment by cskau-g** [comment]
This is now fixed in [0b7a78d](https://dart.googlesource.com/sdk/+/0b7a78d0a611c3b5e2f9e1dc2e85579d4f6f2562#)
