### ISSUE TITLE
Android studio error

### ISSUE THREAD

**Issue by carmas123** [dart-lang/sdk#38531]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2560x1440  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: /Users/isigest/Documents/Develop/Flutter/isigestmobile/lib/widget/fabTickerProviderStateMixin.dart context: exception_20190923_185452_920
NoSuchMethodError: The getter 'library' was called on null.
Receiver: null
Tried calling: library
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      ErrorVerifier._hasConcreteSuperMethod.<anonymous closure> (package:analyzer/src/generated/error_verifier.dart:6265:62)
#2      ListIterable.any (dart:_internal/iterable.dart:89:15)
#3      ErrorVerifier._hasConcreteSuperMethod (package:analyzer/src/generated/error_verifier.dart:6264:25)
#4      ErrorVerifier._checkForMustCallSuper (package:analyzer/src/generated/error_verifier.dart:4450:28)
#5      ErrorVerifier.visitMethodDeclaration (package:analyzer/src/generated/error_verifier.dart:1054:7)
#6      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7107:49)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#8      MixinDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7345:13)
#9      RecursiveAstVisitor.visitMixinDeclaration (package:analyzer/dart/ast/visitor.dart:1069:10)
#10     ErrorVerifier.visitMixinDeclaration (package:analyzer/src/generated/error_verifier.dart:1114:13)
#11     MixinDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7336:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#13     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2167:21)
#14     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:727:10)
#15     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:572:11)
#16     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#17     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:410:10)
#18     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:169:9)
#19     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#20     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:168:13)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:167:34)
#23     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:108:14)
#24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#25     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:43)
#26     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1418:63)
#27     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#28     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1215:33)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#41     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#42     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#43     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#45     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#46     new Future.sync (dart:async/future.dart:224:31)
#47     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _runZoned (dart:async/zone.dart:1516:10)
#51     runZoned (dart:async/...
```

For additional log information, please append the contents of
file:///private/var/folders/s3/9yzt3t4j7sxfy14zm7d6pfr80000gn/T/report.txt.

**Comment by srawlins** [comment]
Thanks for reporting this issue, @carmas123 . Do you know what odd code `fabTickerProviderStateMixin.dart` may have had in it that triggered this explosion? A weird method declaration?

**Comment by carmas123** [comment]
Oh, I don't know, this is my source code:

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';

typedef bool OnScrollFab(ScrollNotification notification);

mixin FabTickerProviderStateMixin<T extends StatefulWidget> on TickerProviderStateMixin<T> {
  AnimationController _animationController;
  Animation<double> _animation;
  bool _fabVisible = true;
  Timer _showDebounce;

  @override
  void initState() {
    _animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 180),
    );

    _animation = CurvedAnimation(
      parent: _animationController,
      curve: Interval(0.0, 1.0, curve: Curves.linear),
    );
    _animationController.forward();
    super.initState();
  }

  Widget buildFab(IconData icon, {VoidCallback onPressed}) {
    return ScaleTransition(
        scale: _animation,
        alignment: FractionalOffset.center,
        child: FloatingActionButton(
          heroTag: null,
          child: Icon(
            icon,
            color: Colors.white,
          ),
          onPressed: onPressed,
        ));
  }

  bool onScrollFab(ScrollNotification notification) {
    if (_showDebounce?.isActive ?? false) _showDebounce.cancel();
    if (notification is UserScrollNotification) {
      if (notification.direction == ScrollDirection.idle) {
        if (!_fabVisible) {
          _showDebounce = Timer(const Duration(seconds: 1), () {
            if (mounted) {
              setState(() {
                _fabVisible = true;
                _animationController.forward();
              });
            }
          });
        }
      } else {
        if (_fabVisible) {
          if (mounted) {
            setState(() {
              _fabVisible = false;
              _animationController.reverse();
            });
          }
        }
      }
    }
    return false;
  }

  @override
  void dispose() {
    _showDebounce?.cancel();
    super.dispose();
  }
}

```

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.4.0. Please re-open if you see this crash again.
