### ISSUE TITLE
language_2/extension_methods/static_extension_operators_test crash

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#38541]
`language_2/extension_methods/static_extension_operators_test` crashes with an assertion failure (missing initializer on parameter).

@alexmarkov : I don't know if the problem is an invalid AST from CFE or an unexpected AST in the flow analysis.

```
/=======================================================================================================\
| language_2/extension_methods/static_extension_operators_test failed again (DartkCrash, expected Pass) |
\=======================================================================================================/

--- Command "vm_compile_to_kernel []" (took 640ms):
DART_CONFIGURATION=ReleaseAndroidARM64 /b/swarming/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseAndroidARM64/vm_platform_strong.dill -o /b/swarming/w/ir/out/ReleaseAndroidARM64/generated_compilations/dartkp/tests_language_2_extension_methods_static_extension_operators_test/out.dill /b/swarming/w/ir/tests/language_2/extension_methods/static_extension_operators_test.dart --enable-experiment=extension-methods --packages=/b/swarming/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
253

stderr:
Assertion failed.
#0      assertx (package:vm/transformations/type_flow/utils.dart:34:5)
#1      SummaryCollector._declareParameter (package:vm/transformations/type_flow/summary_collector.dart:625:7)
#2      SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:421:9)
#3      TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1413:52)
#4      _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:241:42)
#5      _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:175:14)
#6      _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1299:32)
#7      TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1506:23)
#8      Call.apply (package:vm/transformations/type_flow/summary.dart:210:31)
#9      Summary.apply (package:vm/transformations/type_flow/summary.dart:602:33)
#10     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:250:24)
#11     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:175:14)
#12     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1299:32)
#13     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1279:7)
#14     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1426:14)
#15     transformComponent (package:vm/transformations/type_flow/transformer.dart:70:20)
#16     _runGlobalTransformations (package:vm/kernel_front_end.dart:369:5)
<asynchronous suspension>
#17     compileToKernel (package:vm/kernel_front_end.dart:298:11)
<asynchronous suspension>
#18     runCompiler (package:vm/kernel_front_end.dart:215:25)
<asynchronous suspension>
#19     compile (file:///b/swarming/w/ir/pkg/vm/bin/gen_kernel.dart:39:10)
<asynchronous suspension>
#20     runBatchModeCompiler.<anonymous closure> (file:///b/swarming/w/ir/pkg/vm/bin/gen_kernel.dart:57:28)
<asynchronous suspension>
#21     runBatch (package:kernel/src/tool/batch_util.dart:38:35)
<asynchronous suspension>
#22     runBatchModeCompiler (file:///b/swarming/w/ir/pkg/vm/bin/gen_kernel.dart:43:9)
<asynchronous suspension>
#23     main (file:///b/swarming/w/ir/pkg/vm/bin/gen_kernel.dart:32:11)
<asynchronous suspension>
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

--- Re-run this test:
python tools/test.py -n dartkp-android-release-arm64 language_2/extension_methods/static_extension_operators_test
```

**Comment by johnniwinther** [comment]
It looks like a bug in handling default values on extension methods.

**Comment by alexmarkov** [comment]
It seems like there is a non-null `initializer` on a required positional parameter (in `function.positionalParameters[i]` where `i < function.requiredParameterCount` and `function` is a `FunctionNode`).

The assertion is a sanity check to ensure that TFA doesn't need to handle initializers on required parameters.

Is there a reason to have such `initializer`?

**Comment by johnniwinther** [comment]
No. I found a bug in CFE that might be the culprit.
