### ISSUE TITLE
Analyzer fuzz crash: extension member in annotation context

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38551]
```dart
@A(E1.v1)
class C {}

extension E1 {
  int get v1 => 0;
}
```

```
Unhandled exception:
_ElementMismatchException: Element mismatch in /test/lib/test.dart at /test/lib/test.dart
Caused by Bad state: ExtensionElementImpl
#0      _ElementRequest._accessor (package:analyzer/src/summary2/linked_element_factory.dart:260:5)
#1      _ElementRequest.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:184:14)
#2      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:72:45)
#3      LinkedBundleContext.elementOfIndex (package:analyzer/src/summary2/linked_bundle_context.dart:97:27)
#4      AstBinaryReader._getElement (package:analyzer/src/summary2/ast_binary_reader.dart:114:26)
#5      AstBinaryReader._elementOfComponents (package:analyzer/src/summary2/ast_binary_reader.dart:100:19)
#6      AstBinaryReader._read_simpleIdentifier (package:analyzer/src/summary2/ast_binary_reader.dart:1420:25)
#7      AstBinaryReader._readNode (package:analyzer/src/summary2/ast_binary_reader.dart:1853:16)
#8      AstBinaryReader._read_prefixedIdentifier (package:analyzer/src/summary2/ast_binary_reader.dart:1308:7)
#9      AstBinaryReader._readNode (package:analyzer/src/summary2/ast_binary_reader.dart:1839:16)
#10     AstBinaryReader._readNodeList (package:analyzer/src/summary2/ast_binary_reader.dart:1914:19)
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/125520
