### ISSUE TITLE
Analyzer fuzz crash: invalid super syntax in const constructor

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38550]
```dart
class D {
  const D(): super."";
}
```

Without `const`, this causes #38041, so these are likely related.

```
Unhandled exception:
NoSuchMethodError: The getter 'endToken' was called on null.
Receiver: null
Tried calling: endToken
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SuperConstructorInvocationImpl.endToken (package:analyzer/src/dart/ast/ast.dart:9491:39)
#2      _UnitApiSignatureComputer.addClassOrMixin (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:38:65)
#3      _UnitApiSignatureComputer.compute (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:128:9)
#4      computeUnlinkedApiSignature (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:15:12)
#5      FileState.serializeAstUnlinked2 (package:analyzer/src/dart/analysis/file_state.dart:781:21)
#6      FileState._refresh2.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:650:30)
#7      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#8      FileState._refresh2 (package:analyzer/src/dart/analysis/file_state.dart:649:26)
#9      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:401:14)
#10     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:964:12)
```

**Comment by scheglov** [comment]
Yes, this issue has the same underlaying issue as #38041 - `SuperConstructorInvocation` with `null` as `argumentList`.
