### ISSUE TITLE
Error analyzing

### ISSUE THREAD

**Issue by TobiasHeidingsfeld** [dart-lang/sdk#38565]
**The problem comes again and again very quickly. I can confirm that it _DOES NOT_ happen on stable but does happen on dev and master channels. So something must have changed there causing the bug:**

Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Coding

### Versions

- Flutter SDK 1.10.5
- Visual Studio Code 1.38.1
- Dart Code 3.4.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\Tools\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.4.1
```

### Exception

Analysis failed: C:\Repo\lightmyfire\powerflutter\powerflutter_server\lib\src\database\power_query.dart context: exception_20190925_174606_228

```text
NoSuchMethodError: Class 'NamedTypeBuilder' has no instance getter 'isBottom'.
Receiver: Instance of 'NamedTypeBuilder'
Tried calling: isBottom
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      TypeBuilder.noSuchMethod (package:analyzer/src/summary2/type_builder.dart:16:18)
#2      NamedTypeBuilder.isBottom (package:analyzer/dart/element/type.dart:44:12)
#3      LinkingBundleContext.writeType (package:analyzer/src/summary2/linking_bundle_context.dart:81:14)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      LinkingBundleContext.writeType (package:analyzer/src/summary2/linking_bundle_context.dart:96:67)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#8      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#9      LinkingBundleContext.writeType (package:analyzer/src/summary2/linking_bundle_context.dart:96:67)
#10     AstBinaryWriter._writeType (package:analyzer/src/summary2/ast_binary_writer.dart:1674:28)
#11     AstBinaryWriter._writeActualType (package:analyzer/src/summary2/ast_binary_writer.dart:1654:26)
#12     AstBinaryWriter.visitVariableDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:1398:5)
#13     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10539:49)
#14     AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:1668:31)
#15     AstBinaryWriter.visitVariableDeclarationList (package:analyzer/src/summary2/ast_binary_writer.dart:1407:42)
#16     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10635:15)
#17     AstBinaryWriter.visitFieldDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:540:44)
#18     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4095:49)
#19     AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:1668:31)
#20     AstBinaryWriter._storeClassOrMixinDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:1499:43)
#21     AstBinaryWriter.visitClassDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:221:7)
#22     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#23     AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:1668:31)
#24     AstBinaryWriter.visitCompilationUnit (package:analyzer/src/summary2/ast_binary_writer.dart:286:37)
#25     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#26     AstBinaryWriter.writeUnit (package:analyzer/src/summary2/ast_binary_writer.dart:1457:19)
#27     Linker._createLinkingBundle (package:analyzer/src/summary2/link.dart:183:37)
#28     Linker.link (package:analyzer/src/summary2/link.dart:86:5)
#29     link (package:analyzer/src/summary2/link.dart:35:10)
#30     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:318:26)
#31     SetMixin.forEach (dart:collection/set.dart:146:30)
#32     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:273:32)
#33     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:370:17)
#34     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#35     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:368:12)
#36     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:95:7)
#37     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1439:29)
#38     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1246:30)
#39     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#40     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#41     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#42     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1931:24)
<asynchronous suspension>
#43     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1865:5)
#44     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#45     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#46     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#47     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:568:21)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _runZoned (dart:async/zone.dart:1516:10)
#51     runZoned (dart:async/zone.dart:1463:12)
#52     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:685:12)
#53     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:566:7)
#54     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:467:9)
#55     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#56     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:462:43)
#57     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#58     new Future.sync (dart:async/future.dart:224:31)
#59     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#60     _rootRun (dart:async/zone.dart:1124:13)
#61     _CustomZone.run (dart:async/zone.dart:1021:19)
#62     _runZoned (dart:async/zone.dart:1516:10)
#63     runZoned (dart:async/zone.dart:1463:12)
#64     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#65     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:142:56)
#66     Driver.start (package:analysis_server/src/server/driver.dart:462:21)
#67     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#68     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#69     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#70     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "C:\\Repo\\lightmyfire\\powerflutter\\powerflutter_server",
        "explicitFileCount": 11,
        "implicitFileCount": 398,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment]
Sorry, I mis-read the last part of your message as being on dev but further up you said master. Can you try pulling latest? I just did and I get this version:

```
Flutter 1.10.7-pre.99 • channel master • https://github.com/DanTup/flutter.git
Framework • revision 2de1e4f4a1 (8 hours ago) • 2019-09-30 22:05:53 -0400
Engine • revision 4981512815
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 692230b484)
```

The Dart version listed there is from 16 hours ago, which should include the fix.

**Comment by escamoteur** [comment]
Just did this I'm no on

```
Flutter 1.10.7-pre.99 • channel master • https://github.com/flutter/flutter
Framework • revision 2de1e4f4a1 (8 hours ago) • 2019-09-30 22:05:53 -0400
Engine • revision 4981512815
Tools • Dart 2.6.0 (build 2.6.0-dev.4.0 692230b484)
````

No change

**Comment by DanTup** [comment]
Ok, thanks for testing. Deleting your ~/.dartServer folder might help (see https://github.com/dart-lang/sdk/issues/38498#issuecomment-533927706), though I'm not sure if that means the bug isn't totally fixed. @scheglov might be interested in an exact project that reproduces this if you can share if it's not fixed.

**Comment by escamoteur** [comment]
uhm, where is the `dartServer` folder on Windows?

**Comment by DanTup** [comment]
> As a possible work around, you might also try to remove `~/.dartServer` or `C:\Users\scheglov\AppData\Local\.dartServer` on Windows 

Some of those folders may be hidden by default though.

**Comment by escamoteur** [comment]
I deleted the folder, no change.
I can share the project privately if this is ok. if @scheglov is interested I can add him to the project temporatily

**Comment by scheglov** [comment]
It looks that the exception is actually different.

Let's start with sharing the exception log, it worked the previous time.
There are files like `exception_20191001_112627_785` in your `.dartServer` directory.
Send one of the (most probably all of the are for the same exception, but might be not) to me - `scheglov@google.com`.

```
NoSuchMethodError: The getter 'isBottom' was called on null.
           Receiver: null
           Tried calling: isBottom
           #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
           #1      _isLegacyBottom (package:analyzer/src/generated/type_system.dart:62:13)
           #2      GenericInferrer._matchSubtypeOf (package:analyzer/src/generated/type_system.dart:1790:9)
           #3      GenericInferrer.tryMatchSubtypeOf (package:analyzer/src/generated/type_system.dart:1411:20)
           #4      GenericInferrer.constrainArgument (package:analyzer/src/generated/type_system.dart:1238:5)
           #5      Dart2TypeSystem.inferGenericFunctionOrType (package:analyzer/src/generated/type_system.dart:293:16)
           #6      ElementResolver._resolveAnnotationConstructor (package:analyzer/src/generated/element_resolver.dart:1279:41)
           #7      ElementResolver._resolveAnnotationElement (package:analyzer/src/generated/element_resolver.dart:1341:23)
           #8      ElementResolver.visitSimpleIdentifier (package:analyzer/src/generated/element_resolver.dart:873:7)
```

**Comment by escamoteur** [comment]
nope, there isn't or is this Nope, there isn't any such file, sorry

**Comment by escamoteur** [comment]
Unfortunately I have to go for an hour or so

**Comment by DanTup** [comment]
> nope, there isn't or is this Nope, there isn't any such file, sorry

Is this just because above I suggested trying deleting the `dartServer` folder? If you reproduce it again, hopefully it'll write new ones.

**Comment by escamoteur** [comment]
I did a 'flutter analyze' again all the error output but no file. The large error log I attached did not help?

**Comment by scheglov** [comment]
Ah, with `flutter analyze` you might not get exception files written, not sure.
So, yeah, I guess I need access to the repo to be able to reproduce.

**Comment by escamoteur** [comment]
@scheglov I just added you to the Repo which is not to be published. You can ping me on Discord if you need help. 
The project is the aartos folder.

**Comment by scheglov** [comment]
Thank you, I can reproduce the issue in my IDE.
I will set up reproducing it without analyzer, so that I can debug it.

**Comment by scheglov** [comment]
This was caused by https://dart-review.googlesource.com/c/sdk/+/118901

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/119534 will fix the crash.

**Comment by escamoteur** [comment]
@scheglov when will that land in master of Flutter?
Can you delete my project?

**Comment by scheglov** [comment]
I don't know about the release process. @mit-mit 

I deleted your project.
