### ISSUE TITLE
The method 'withNullability' was called on null. Receiver: null

### ISSUE THREAD

**Issue by timrijckaert** [dart-lang/sdk#38589]
Dart Analyzer fails on this file.  
I have noticed that if you remove the return from the `parse` method it works again.

```
import 'package:vrt_nws/app/app.dart';

import 'parser.dart';

class VRTUrlParser with VRTRouteParser {
  final VRTDomainHelper _vrtDomainHelper;

  VRTUrlParser(this._vrtDomainHelper);

  @override
  bool canParse(String input) {
    final uri = Uri.tryParse(input);
    final isNotNull = uri != null;
    final hasScheme = uri?.hasScheme;
    final isHttp = uri?.isScheme("HTTP");
    final isHttps = uri?.isScheme("HTTPS");
    return isNotNull && hasScheme && (isHttp || isHttps);
  }

  @override
  VRTRoute parse(String input) {
    final uri = Uri.tryParse(input);
    return _vrtDomainHelper.isInVRTDomain(input) ? WebDetailUrlRoute(uri.toString()) : External(input);
  }
}
```

Crashlog from Intellij

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.7479.19`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IU-191.7479.19, JRE 1.8.0_202-release-1483-b58x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 2560x1440  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/timrijckaert/Documents/VRT/Flutter/vrt-nws/lib/app/navigation/vrt_url_parser.dart
NoSuchMethodError: The method 'withNullability' was called on null.
Receiver: null
Tried calling: withNullability(Instance of 'NullabilitySuffix')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      InterfaceLeastUpperBoundHelper.compute (package:analyzer/src/generated/type_system.dart:2066:19)
#2      Dart2TypeSystem._interfaceLeastUpperBound (package:analyzer/src/generated/type_system.dart:987:19)
#3      TypeSystem.getLeastUpperBound (package:analyzer/src/generated/type_system.dart:2405:14)
#4      StaticTypeAnalyzer._analyzeLeastUpperBoundTypes (package:analyzer/src/generated/static_type_analyzer.dart:1179:21)
#5      StaticTypeAnalyzer._analyzeLeastUpperBound (package:analyzer/src/generated/static_type_analyzer.dart:1159:5)
#6      StaticTypeAnalyzer.visitConditionalExpression (package:analyzer/src/generated/static_type_analyzer.dart:461:5)
#7      ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:2270:15)
#8      ResolverVisitor.visitConditionalExpression (package:analyzer/src/generated/resolver.dart:3640:10)
#9      ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:2270:15)
#10     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8638:18)
#11     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#12     UnifyingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:3395:51)
#13     ResolverVisitor.visitReturnStatement (package:analyzer/src/generated/resolver.dart:4326:11)
#14     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8634:49)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#16     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#17     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#18     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#19     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:5171:13)
#20     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#21     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#22     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#23     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3131:55)
#24     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5182:13)
#25     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:3508:13)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#27     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7110:12)
#28     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#29     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3336:55)
#30     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:5669:11)
#31     ResolverVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:4207:11)
#32     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:5662:7)
#33     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:4198:13)
#34     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7101:49)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#36     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:5248:18)
#37     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5226:11)
#38     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3552:13)
#39     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#40     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:3594:23)
#41     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#42     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:698:10)
#43     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#44     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#45     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#46     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#47     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#48     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#49     AnalysisDriver._computeA...
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I cannot reproduce, because the crash happens when we compute the return type using declarations of classes (?) `WebDetailUrlRoute` and `External`, which I don't have. If you could provide more information, with full declarations of these classes (I need only extended, implemented interfaces, mixins, but not methods or their bodies). If you don't want to share this publically, you could send it to `scheglov@google.com`. It might be that we have already fixed this in the bleeding edge of Analyzer.

**Comment by timrijckaert** [comment]
No problem,  nothing exciting in these classes.

```
mixin VRTRoute {}

class WebDetailUrlRoute implements VRTRoute {
  final String decodedUrl;

  const WebDetailUrlRoute(this.decodedUrl);

  @override
  String toString() => 'WebDetailUrlRoute{decodedUrl: $decodedUrl}';
}

class External implements VRTRoute {
  final String url;

  const External(this.url);
}

**Comment by scheglov** [comment]
Thank you, I can reproduce it.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/119181

**Comment by timrijckaert** [comment]
When will this be available on stable?

**Comment by mit-mit** [comment]
We don't generally release on a fixed schedule, but I would expect this to reach stable within a few weeks.
