### ISSUE TITLE
We're sorry, you've found a bug in our compiler.

### ISSUE THREAD

**Issue by PavelPZ** [dart-lang/sdk#38599]
Flutter MASTER channel, v 1.10.7-pre.29

Trying to use (and compile) code with protobuf package dependency to Flutter WEB.

'''
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=c:\flutter\bin\cache\flutter_web_sdk/kernel/flutter_ddc_sdk.dill
    --modules=amd --no-summarize -o
    C:\Users\pzika\AppData\Local\Temp\scratch_space289505ad-e094-11e9-9313-db099baf4562\packages/charcode/charcod    e.ddc.js --source-map
    --summary=C:\Users\pzika\AppData\Local\Temp\scratch_space289505ad-e094-11e9-9313-db099baf4562\packages/charco    de/ascii.ddc.dill=packages/charcode/ascii
    --summary=C:\Users\pzika\AppData\Local\Temp\scratch_space289505ad-e094-11e9-9313-db099baf4562\packages/charco    de/html_entity.ddc.dill=packages/charcode/html_entity
    --packages=file:///C:/Users/pzika/AppData/Local/Temp/kernel_builder_34d736af-e094-11e9-9313-db099baf4562/.pac    kages --module-name=packages/charcode/charcode --multi-root-scheme=org-dartlang-app --multi-root=.
    --track-widget-creation --inline-source-map
    --libraries-file=file:///c:/flutter/bin/cache/flutter_web_sdk/libraries.json package:charcode/charcode.dart
    dart --version: 2.6.0-dev.3.0.flutter-53564db036 (Thu Sep 26 10:36:51 2019 +0000) on "windows_x64"

Crash when compiling package:charcode/charcode.dart,
at character offset null:
Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:447:29)
#1      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:457:5)
#2      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:396:10)
#3      ProcessedOptions.loadInputSummaries.<anonymous closure>
(package:front_end/src/base/processed_options.dart:358:35)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:358:67)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#23     ProcessedOptions._readAsBytes (package:front_end/src/base/processed_options.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:447:29)
#1      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:457:5)
#2      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:396:10)
#3      ProcessedOptions.loadInputSummaries.<anonymous closure>
(package:front_end/src/base/processed_options.dart:358:35)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:358:67)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#23     ProcessedOptions._readAsBytes (package:front_end/src/base/processed_options.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

Error compiling dartdevc module:charcode|lib/html_entity.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=c:\flutter\bin\cache\flutter_web_sdk/kernel/flutter_ddc_sdk.dill
    --modules=amd --no-summarize -o
    C:\Users\pzika\AppData\Local\Temp\scratch_space289505ad-e094-11e9-9313-db099baf4562\packages/charcode/html_en    tity.ddc.js --source-map
    --summary=C:\Users\pzika\AppData\Local\Temp\scratch_space289505ad-e094-11e9-9313-db099baf4562\packages/charco    de/ascii.ddc.dill=packages/charcode/ascii
    --packages=file:///C:/Users/pzika/AppData/Local/Temp/kernel_builder_2eae814f-e094-11e9-9313-db099baf4562/.pac    kages --module-name=packages/charcode/html_entity --multi-root-scheme=org-dartlang-app --multi-root=.
    --track-widget-creation --inline-source-map
    --libraries-file=file:///c:/flutter/bin/cache/flutter_web_sdk/libraries.json
    package:charcode/html_entity.dart
    dart --version: 2.6.0-dev.3.0.flutter-53564db036 (Thu Sep 26 10:36:51 2019 +0000) on "windows_x64"

Crash when compiling package:charcode/html_entity.dart,
at character offset null:
Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:447:29)
#1      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:457:5)
#2      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:396:10)
#3      ProcessedOptions.loadInputSummaries.<anonymous closure>
(package:front_end/src/base/processed_options.dart:358:35)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:358:67)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#23     ProcessedOptions._readAsBytes (package:front_end/src/base/processed_options.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:447:29)
#1      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:457:5)
#2      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:396:10)
#3      ProcessedOptions.loadInputSummaries.<anonymous closure>
(package:front_end/src/base/processed_options.dart:358:35)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:358:67)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#23     ProcessedOptions._readAsBytes (package:front_end/src/base/processed_options.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:http/http.dart';` from utils|lib/http.dart at 2:1

AssetNotFoundException: utils|lib/http.ddc.dill

AssetNotFoundException: utils|lib/http.ddc.dill
Error compiling dartdevc module:source_span|lib/source_span.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=c:\flutter\bin\cache\flutter_web_sdk/kernel/flutter_ddc_sdk.dill
    --modules=amd --no-summarize -o
    C:\Users\pzika\AppData\Local\Temp\scratch_space289505ad-e094-11e9-9313-db099baf4562\packages/source_span/sour    ce_span.ddc.js --source-map
    --summary=C:\Users\pzika\AppData\Local\Temp\scratch_space289505ad-e094-11e9-9313-db099baf4562\packages/charco    de/ascii.ddc.dill=packages/charcode/ascii
    --summary=C:\Users\pzika\AppData\Local\Temp\scratch_space289505ad-e094-11e9-9313-db099baf4562\packages/charco    de/html_entity.ddc.dill=packages/charcode/html_entity
    --summary=C:\Users\pzika\AppData\Local\Temp\scratch_space289505ad-e094-11e9-9313-db099baf4562\packages/charco    de/charcode.ddc.dill=packages/charcode/charcode
    --summary=C:\Users\pzika\AppData\Local\Temp\scratch_space289505ad-e094-11e9-9313-db099baf4562\packages/term_g    lyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set
    --summary=C:\Users\pzika\AppData\Local\Temp\scratch_space289505ad-e094-11e9-9313-db099baf4562\packages/path/p    ath.ddc.dill=packages/path/path
    --packages=file:///C:/Users/pzika/AppData/Local/Temp/kernel_builder_34d736b6-e094-11e9-9313-db099baf4562/.pac    kages --module-name=packages/source_span/source_span --multi-root-scheme=org-dartlang-app --multi-root=.
    --track-widget-creation --inline-source-map
    --libraries-file=file:///c:/flutter/bin/cache/flutter_web_sdk/libraries.json
    package:source_span/src/colors.dart package:source_span/src/location_mixin.dart
    package:source_span/src/span.dart package:source_span/src/span_with_context.dart
    package:source_span/src/highlighter.dart package:source_span/src/span_exception.dart
    package:source_span/src/file.dart package:source_span/src/location.dart package:source_span/src/utils.dart
    package:source_span/source_span.dart package:source_span/src/span_mixin.dart
    dart --version: 2.6.0-dev.3.0.flutter-53564db036 (Thu Sep 26 10:36:51 2019 +0000) on "windows_x64"

Crash when compiling package:source_span/src/colors.dart,
at character offset null:
Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:447:29)
#1      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:457:5)
#2      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:396:10)
#3      ProcessedOptions.loadInputSummaries.<anonymous closure>
(package:front_end/src/base/processed_options.dart:358:35)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:358:67)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#23     ProcessedOptions._readAsBytes (package:front_end/src/base/processed_options.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:447:29)
#1      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:457:5)
#2      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:396:10)
#3      ProcessedOptions.loadInputSummaries.<anonymous closure>
(package:front_end/src/base/processed_options.dart:358:35)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:358:67)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#23     ProcessedOptions._readAsBytes (package:front_end/src/base/processed_options.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

'''

**Comment by PavelPZ** [comment]
I'm not 100% sure, but with the two-day old flutter SDK everything was fine.

**Comment by natebosch** [comment]
Note that in github a code fence uses backtick `` ` ``, not single quote `'`

This looks really similar to https://github.com/dart-lang/sdk/issues/38102

**Comment by htueko** [comment]
dartdevc -k arguments: --dart-sdk-summary=/home/htueko/Development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd
    --no-summarize -o packages/htueko/view/navigation_header.ddc.js --source-map --summary=packages/meta/meta.ddc.dill=packages/meta/meta
    --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web
    --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash
    --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64
    --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation
    --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
    --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
    --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
    --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue
    --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
    --summary=packages/collection/collection.ddc.dill=packages/collection/collection
    --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena
    --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures
    --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web
    --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting
    --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding
    --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics
    --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation
    --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation
    --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size
    --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering
    --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions
    --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets
    --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet
    --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino --summary=packages/flutter/material.ddc.dill=packages/flutter/material
    --summary=packages/htueko/view/profile_image.ddc.dill=packages/htueko/view/profile_image
    --summary=packages/htueko/helper/responsive.ddc.dill=packages/htueko/helper/responsive --packages=file:///tmp/kernel_builder_LZLEKB/.packages
    --module-name=packages/htueko/view/navigation_header --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map
    --libraries-file=file:///home/htueko/Development/flutter/bin/cache/flutter_web_sdk/libraries.json package:htueko/view/navigation_header.dart
    dart --version: 2.6.0-dev.1.0.flutter-cb80ea7ba9 (Tue Sep 17 21:20:16 2019 +0000) on "linux_x64"

**Comment by vsmenon** [comment]
Dup of https://github.com/dart-lang/sdk/issues/38102
