### ISSUE TITLE
raw_datagram_read_all_test has begun failing on dartk-reload-linux-debug-x64

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#38594]
The failure is not flaky.

From https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8901241222814635632/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0

```
/=======================================================================================\
| standalone_2/io/raw_datagram_read_all_test failed again (RuntimeError, expected Pass) |
\=======================================================================================/

--- Command "vm" (took 07.000465s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --hot-reload-test-mode --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/io/raw_datagram_read_all_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.isNull(actual: <Instance of 'Datagram'>) fails.
#0      Expect._fail (package:expect/expect.dart:665:5)
#1      Expect.isNull (package:expect/expect.dart:153:5)
#2      main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/raw_datagram_read_all_test.dart:33:18)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

--- Re-run this test:
python tools/test.py -n dartk-reload-linux-debug-x64 standalone_2/io/raw_datagram_read_all_test
```

**Comment by sjindel-google** [comment]
I will approve the failure.

**Comment by askeksa-google** [comment]
This test went green again shortly after (in the test run for https://github.com/dart-lang/sdk/commit/75eb947bc87d1887d52fdb84e84bb67d2b78ee0c). Closing.
