### ISSUE TITLE
Analysis error

### ISSUE THREAD

**Issue by Dinesh41** [dart-lang/sdk#38606]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6603.28`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IC-192.6603.28, JRE 11.0.3+12-b304.56x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Captured exception
RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core/runtime/libstring_patch.dart:387:7)
#1      unescapeLastStringPart (package:front_end/src/fasta/quote.dart:132:24)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:257:17)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4797:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4722:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3997:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3930:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3742:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:4912:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4884:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4865:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4844:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4580:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3991:14)
#15     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3783:21)
#16     Parser.parseExpressionWithoutCascade (package:front_end/src/fasta/parser/parser.dart:3723:11)
#17     Parser.parseConditionalExpressionRest (package:front_end/src/fasta/parser/parser.dart:3733:13)
#18     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3807:19)
#19     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#20     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3679:13)
#21     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5191:16)
#22     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3513:14)
#23     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#24     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3408:15)
#25     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3241:13)
#26     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3173:13)
#27     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4073:16)
#28     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4032:14)
#29     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3930:12)
#30     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3742:13)
#31     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#32     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:4912:15)
#33     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4884:12)
#34     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4865:14)
#35     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4844:13)
#36     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4580:12)
#37     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3991:14)
#38     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3783:21)
#39     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#40     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3679:13)
#41     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5191:16)
#42     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3513:14)
#43     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#44     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3408:15)
#45     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3241:13)
#46     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3173:13)
#47     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4073:16)
#48     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4032:14)
#49     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3930:12)
#50     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3742:13)
#51     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#52     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:4912:15)
#53...
```

For additional log information, please append the contents of
file://C:\Users\Dinesh\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).
