### ISSUE TITLE
ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl

### ISSUE THREAD

**Issue by debasiskoley** [dart-lang/sdk#38608]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      _NodeListImpl&Object&ListMixin.first (dart:collection/list.dart:75:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#6      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#7      RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#8      LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#9      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:625:10)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#14     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#15     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:991:10)
#16     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#17     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#19     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6831:15)
#20     RecursiveAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:1045:10)
#21     LinterVisitor.visitListLiteral (package:analyzer/src/lint/linter_visitor.dart:438:11)
#22     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6826:49)
#23     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#24     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#25     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#26     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#28     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#29     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:625:10)
#30     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#31     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#32     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:991:10)
#33     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#34     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#35     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8644:18)
#36     RecursiveAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:1160:10)
#37     LinterVisitor.visitReturnStatement (package:analyzer/src/lint/linter_visitor.dart:541:11)
#38     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8640:49)
#39     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#40     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1121:17)
#41     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:667:10)
#42     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:66:11)
#43     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1117:49)
#44     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1076:13)
#45     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:673:10)
#46     LinterVisitor.visitBlockFunctionBody (package:analyzer/src/lint/linter_visitor.dart:72:11)
#47     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1072:49)
#48     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7116:12)
#49     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1057...
```

For additional log information, please append the contents of
file:///private/var/folders/z4/bmkpbnd91ns43t4kzc6xk3dh0000gn/T/report2.txt.

**Comment by bwilkerson** [comment]
@pq

**Comment by pq** [comment]
Thanks for the report @debasiskoley!
