### ISSUE TITLE
[vm/wasm] 

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#38609]
@liamappelbe it looks like the test expectations are not set up correctly for cross-vm-linux-release-arm64.

[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8901212882148240768/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0):

```
/=================================================================================\
| lib_2/wasm/fn_import_error_test is new and failed (RuntimeError, expected Pass) |
\=================================================================================/

--- Command "vm" (took 08.000815s):
DART_CONFIGURATION=ReleaseXARM64 out/ReleaseXARM64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/lib_2/wasm/fn_import_error_test.dart

exit code:
255

stderr:
Unhandled exception:
Unsupported operation: WASM is disabled
#0      _NativeWasmModule._init (dart:wasm-patch/wasm_patch.dart:62:54)
#1      new _NativeWasmModule (dart:wasm-patch/wasm_patch.dart:55:5)
#2      new WasmModule (dart:wasm-patch/wasm_patch.dart:33:12)
#3      main (file:///b/s/w/ir/tests/lib_2/wasm/fn_import_error_test.dart:27:3)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

--- Re-run this test:
python tools/test.py -n dartk-linux-release-arm64 lib_2/wasm/fn_import_error_test

...
```

**Comment by liamappelbe** [comment]
WASM is behind a flag, so these failures should just be approved.
