### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by sunyuping** [dart-lang/sdk#38605]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6603.28`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `IU-192.6603.28, JRE 11.0.3+12-b304.56x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900, 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: FileSystemException(path=/Users/sunyuping/workspace/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/.symlinks/plugins/banma_flutter_map/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcse; message=Directory listing failed)
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:334:7)
#1      _OverlayFolder.getChildren (package:analyzer/file_system/overlay_file_system.dart:334:10)
#2      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1144:32)
#3      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#4      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#5      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#6      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#7      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#8      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#9      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#10     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#11     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#12     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#13     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#14     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#15     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#16     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#17     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#18     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#19     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#20     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#21     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#22     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#23     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#24     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#25     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#26     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#27     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#28     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#29     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#30     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#31     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#32     ContextManagerImpl._createContext.checkManifestFil...
```

For additional log information, please append the contents of
file:///private/var/folders/43/55xv2mld0fnfg20fhnv_3d1h0000gp/T/report1.txt.

**Comment by srawlins** [comment]
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).
