### ISSUE TITLE
Invalid code causes a crash in CFE

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#38600]
The following piece of code
```
class C<T> {}

extension try<T> on C<T> {
}

main() {
  C c = new C<int>();
}
```
when run causes a crash with the following stack trace:

```
Crash when compiling file:///tmp/junk.dart,
at character offset null:
type 'ParserRecovery' is not a subtype of type 'TypeBuilder'
#0      OutlineBuilder.endExtensionDeclaration (package:front_end/src/fasta/source/outline_builder.dart:674:17)
#1      Parser.parseExtension (package:front_end/src/fasta/parser/parser.dart:2144:14)
#2      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:614:18)
#3      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#4      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#5      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:289:37)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#15     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


#0      OutlineBuilder.endExtensionDeclaration (package:front_end/src/fasta/source/outline_builder.dart:674:17)
#1      Parser.parseExtension (package:front_end/src/fasta/parser/parser.dart:2144:14)
#2      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:614:18)
#3      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#4      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#5      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:289:37)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#15     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```

**Comment by a-siva** [comment]
Command line used:

`dart --enable-experiment=extension-methods /tmp/junk.dart`
