### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by sovoereign** [dart-lang/sdk#38631]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: E:\Farhana_Sample\lotus\lotus_24\lotus\lib\drawer\myprofile.dart context: exception_20190928_130102_786
Bad state: Element not contained in compilation unit: Never
#0      getUnitElement (package:analyzer/src/dart/analysis/index.dart:28:3)
#1      _IndexAssembler._getElementInfo.<anonymous closure> (package:analyzer/src/dart/analysis/index.dart:346:44)
#2      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#3      _IndexAssembler._getElementInfo (package:analyzer/src/dart/analysis/index.dart:345:23)
#4      _IndexAssembler.addElementRelation (package:analyzer/src/dart/analysis/index.dart:235:32)
#5      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:499:15)
#6      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:451:7)
#7      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:759:5)
#8      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8976:49)
#9      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#10     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#11     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:55

**Comment by devoncarew** [comment]
dup of https://github.com/dart-lang/sdk/issues/38488
