### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by aqibgatoo** [dart-lang/sdk#38645]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: Analysis failed: /Users/aqibgatoo/development/musalleen/manzimyoor/lib/src/screens/tabs/user_profile_tab.dart context: exception_20190930_110914_792
type 'FieldElementImpl' is not a subtype of type 'ExecutableElement' in type cast
#0      ExecutableElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:567:27)
#1      ConstructorElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:281:13)
#2      ConstructorElementHandle.enclosingElement (package:analyzer/src/dart/element/handle.dart:284:40)
#3      ExprBuilder._buildCreation (package:analyzer/src/summary/expr_builder.dart:438:42)
#4      ExprBuilder._pushInvokeMethodRef (package:analyzer/src/summary/expr_builder.dart:868:13)
#5      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:201:11)
#6      _UnitResynthesizer._buildConstExpression (package:analyzer/src/summary/resynthesize.dart:1607:47)
#7      SummaryResynthesizerContext.buildExpression (package:analyzer/src/summary/resynthesize.dart:422:30)
#8      _DefaultParameterElementImpl&ParameterElementImpl&ConstVariableElement.constantInitializer (package:analyzer/src/dart/element/element.dart:2828:12)
#9      ConstantEvaluationEngine.computeDependencies (package:analyzer/src/dart/constant/evaluation.dart:308:41)
#10     _ConstantNode.computeDependencies (package:analyzer/src/dart/constant/compute.dart:58:22)
#11     Node.getDependencies (package:analyzer/src/summary/link.dart:4110:40)
#12     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2158:40)
#13     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2224:18)
#14     computeConstants (package:analyzer/src/dart/constant/compute.dart:37:41)
#15     LibraryAnalyzer._computeConstants (package:analyzer/src/dart/analysis/library_analyzer.dart:222:5)
#16     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:142:5)
#17     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:14)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:43)
#20     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1450:63)
#21     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#22     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1427:20)
#23     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1227:17)
<asynchronous suspension>
#24     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2160:24)
<asynchronous suspension>
#25     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2090:5)
#26     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#27     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#28     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#29     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#35     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#36     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#37     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#38     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#39     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/wc/kj98r0lj5cqgwd4rj766d7l80000gn/T/report.txt.

**Comment by srawlins** [comment]
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).
