### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by Hazim6163** [dart-lang/sdk#38644]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.6.0-edge.69b5681546c68ab85e2ce6d3e7b92ed7d113e7c1`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.69b5681546c68ab85e2ce6d3e7b92ed7d113e7c1, server version 1.27.3, FATAL error: Failed to handle request: {id: 6422, method: edit.getFixes, params: {file: F:\flutter\redux_notes\redux_notes\lib\actions.dart, offset: 145}, clientRequestTime: 1569817943973}
type 'DefaultFormalParameterImpl' is not a subtype of type 'FormalParameterList' in type cast
#0      FixProcessor._addFix_removeUnusedField (package:analysis_server/src/services/correction/fix_internal.dart:3569:34)
#1      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#2      FixProcessor._addFix_removeUnusedField (package:analysis_server/src/services/correction/fix_internal.dart:3528:41)
#3      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:379:13)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:205:28)
#6      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:67:33)
#9      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:656:46)
#10     _asyn

**Comment by devoncarew** [comment]
dup of https://github.com/dart-lang/sdk/issues/39099
