### ISSUE TITLE
corelib_2/bigint_from_test/3 failing on vm-kernel-reload-mac-release-simdbc64

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#38649]
It has been flaky since at least Sept. 18, but now it's turning the CI build red. Here's an
[example log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8900901572484050368/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0) showing the failure:

```
/=========================================================================\
| corelib_2/bigint_from_test/3 failed again (RuntimeError, expected Pass) |
\=========================================================================/

--- Command "vm_compile_to_kernel []" (took 825ms):
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_corelib_2_bigint_from_test.dart_3/out.dill /b/s/w/ir/tests/corelib_2/bigint_from_test.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 05.000589s):
DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --hot-reload-test-mode --optimization-counter-threshold=5 --no-background-compilation --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_corelib_2_bigint_from_test.dart_3/out.dill

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <4611686018427387900>, actual: <4611686018427387903>) fails.
#0      Expect._fail (package:expect/expect.dart:665:5)
#1      Expect.equals (package:expect/expect.dart:123:7)
#2      testInt (file:///b/s/w/ir/tests/corelib_2/bigint_from_test.dart:73:10)
#3      main (file:///b/s/w/ir/tests/corelib_2/bigint_from_test.dart:23:5)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

--- Re-run this test:
python tools/test.py -n dartk-reload-mac-release-simdbc64 corelib_2/bigint_from_test/3
```

Unlike #37529, this isn't a crash but an actual wrong generated value. Looking at older issues, this may be a regression related to #34901? Approving for now to turn the builder green.

**Comment by alexmarkov** [comment]
`simdbc64` architecture was discontinued and `dartk-reload-mac-release-simdbc64` bot was removed.
