### ISSUE TITLE
analyzer fuzz crash: Reassignment through `++` on extension override tearoff

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38653]
```dart
f(){
  E(null).v++;
}
extension E on Object{
  v() {}
}
```

Interestingly (to me), this doesn't fail without it being an extension override.

```
Unhandled exception:
type 'MethodElementImpl' is not a subtype of type 'PropertyAccessorElement'
#0      ElementResolver.visitPropertyAccess (package:analyzer/src/generated/element_resolver.dart:714:35)
#1      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8492:49)
#2      ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:4303:10)
#3      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8492:49)
#4      PostfixExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8217:15)
#5      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4264:10)
#6      UnifyingAstVisitor.visitPostfixExpression (package:analyzer/dart/ast/visitor.dart:3375:55)
#7      PostfixExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:8213:49)
#8      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3772:18)
#9      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4264:10)
#10     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3214:59)
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/119700
