### ISSUE TITLE
Exception while using a PreferVoidToNull to visit a TypeNameImpl

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#38668]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6817.14`
- `2.6.0-edge.6ff8d2199da265e0aa2e3ca0b677956db3d42231`
- `IC-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.6ff8d2199da265e0aa2e3ca0b677956db3d42231, server version 1.27.3, error: Exception while using a PreferVoidToNull to visit a TypeNameImpl in SimpleFormalParameterImpl in FormalParameterListImpl in GenericFunctionTypeImpl in FieldFormalParameterImpl in FormalParameterListImpl in ConstructorDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'isDartCoreNull' was called on null.
Receiver: null
Tried calling: isDartCoreNull
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _Visitor.visitTypeName (package:linter/src/rules/prefer_void_to_null.dart:71:20)
#2      TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10199:49)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:725:14)
#4      LinterVisitor.visitTypeName (package:analyzer/src/lint/linter_visitor.dart:666:5)
#5      TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10199:49)
#6      SimpleFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8899:12)
#7      RecursiveAstVisitor.visitSimpleFormalParameter (package:analyzer/dart/ast/visitor.dart:1188:10)
#8      LinterVisitor.visitSimpleFormalParameter (package:analyzer/src/lint/linter_visitor.dart:571:11)
#9      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:8894:15)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#11     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4558:17)
#12     RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:887:10)
#13     LinterVisitor.visitFormalParameterList (package:analyzer/src/lint/linter_visitor.dart:288:11)
#14     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4554:49)
#15     GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5468:18)
#16     RecursiveAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:947:10)
#17     LinterVisitor.visitGenericFunctionType (package:analyzer/src/lint/linter_visitor.dart:348:11)
#18     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5461:20)
#19     FieldFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4231:12)
#20     RecursiveAstVisitor.visitFieldFormalParameter (package:analyzer/dart/ast/visitor.dart:863:10)
#21     LinterVisitor.visitFieldFormalParameter (package:analyzer/src/lint/linter_visitor.dart:264:11)
#22     FieldFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:4226:49)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#24     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4558:17)
#25     RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:887:10)
#26     LinterVisitor.visitFormalParameterList (package:analyzer/src/lint/linter_visitor.dart:288:11)
#27     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4554:49)
#28     ConstructorDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2633:18)
#29     RecursiveAstVisitor.visitConstructorDeclaration (package:analyzer/dart/ast/visitor.dart:743:10)
#30     LinterVisitor.visitConstructorDeclaration (package:analyzer/src/lint/linter_visitor.dart:144:11)
#31     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2626:15)
#32     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#33     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#34     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#35     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:102:11)
#36     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#37     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#38     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#39     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#40     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#41     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#42     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:351:10)
#43     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:204:11)
#44     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#45     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:199:35)
#46     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:117:14)
#47     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#48     LibraryAnalyzer.analyze (package:analyzer/src...
```

For additional log information, please append the contents of
file:///private/var/folders/59/h7pc84z90xnfgjn6fjb8nmt00000gn/T/report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.6.0. Please re-open if you see this crash again.
