### ISSUE TITLE
NoSuchMethodError: The method 'FfiTrampoline' was called on null.

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#38671]
Thank for FFI and dart2native.
Code [here (gist)](https://gist.github.com/ykmnkmi/365bbd025ae3489211b505bcc45dfe57).
Trying calling winmm.dll [PlaySound (MS Docs)](https://docs.microsoft.com/en-us/previous-versions/dd743680(v%3Dvs.85)) function, but got this error:
```Unhandled exception:
NoSuchMethodError: The method 'FfiTrampoline' was called on null.
Receiver: null
Tried calling: FfiTrampoline()
#0      FfiTrampoline (dart:ffi)
#1      PlaySound.file (file:///C:/Users/ykmnkmi/Desktop/play_sound/bin/main.dart:17:17)
#2      main (file:///C:/Users/ykmnkmi/Desktop/play_sound/bin/main.dart:29:25)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)```
and don't know what to do 😞

**Comment by ykmnkmi** [comment]
Solved: hmod don't be null
