### ISSUE TITLE
Invalid argument(s): argumentTypes.length (0) != typeFormals.length (1)

### ISSUE THREAD

**Issue by griks-lab** [dart-lang/sdk#38686]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6817.14`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IU-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2560x1080, 1680x1050`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: Failed to handle request: {id: 31316, method: edit.isPostfixCompletionApplicable, params: {file: /Users/rodrigorahman/Documents/workstation/projetos/Kafex/project/kafex/lib/src/pages/login/login_page.dart, offset: 5233, key: .if}, clientRequestTime: 1569980240737}
Invalid argument(s): argumentTypes.length (0) != typeFormals.length (1)
#0      _FunctionTypeImplLazy.instantiate (package:analyzer/src/dart/element/type.dart:3457:7)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:554:24)
#2      ListMixin.firstWhere (dart:collection/list.dart:138:15)
#3      PostfixCompletionProcessor._findOuterExpression (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:544:28)
#4      PostfixCompletionProcessor.findBoolExpression (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:448:7)
#5      DartPostfixCompletion.isBoolContext (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:209:22)
#6      PostfixCompletionProcessor.isApplicable (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:487:23)
<asynchronous suspension>
#7      EditDomainHandler.isPostfixCompletionApplicable (package:analysis_server/src/edit/edit_domain.dart:484:31)
<asynchronous suspension>
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:403:9)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#52     _StreamContro...
```

For additional log information, please append the contents of
file:///private/var/folders/6b/sd1n39095wdgm4fmqwzb2hkw0000gn/T/report.txt.

**Comment by parlough** [comment]
Shouldn't occur anymore due to restructuring away from .type: https://github.com/dart-lang/sdk/commit/e978b32a7ee66912b1133f6174a8002dc705b9b6#diff-e9938c1f48ad5679902e744be5eba7c4L554
