### ISSUE TITLE
error: type '_PropertySelector' is not a subtype of type '_MethodSelector'

### ISSUE THREAD

**Issue by eightpigs** [dart-lang/sdk#38688]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6817.14`
- `2.6.0-edge.6ff8d2199da265e0aa2e3ca0b677956db3d42231`
- `IU-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Linux(amd64) v5.3.1-arch1-1-ARCH, screens 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.6ff8d2199da265e0aa2e3ca0b677956db3d42231, server version 1.27.3, error: type '_PropertySelector' is not a subtype of type '_MethodSelector'
#0      new CallChainVisitor (package:dart_style/src/call_chain_visitor.dart:151:11)
#1      SourceVisitor.visitPropertyAccess (package:dart_style/src/source_visitor.dart:2109:5)
#2      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8492:49)
#3      SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#4      SourceVisitor.visitBinaryExpression.traverse (package:dart_style/src/source_visitor.dart:439:9)
#5      SourceVisitor.visitBinaryExpression.traverse (package:dart_style/src/source_visitor.dart:431:17)
#6      SourceVisitor.visitBinaryExpression (package:dart_style/src/source_visitor.dart:447:13)
#7      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:997:49)
#8      SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#9      SourceVisitor.visitBinaryExpression.traverse (package:dart_style/src/source_visitor.dart:439:9)
#10     SourceVisitor.visitBinaryExpression.traverse (package:dart_style/src/source_visitor.dart:437:17)
#11     SourceVisitor.visitBinaryExpression (package:dart_style/src/source_visitor.dart:447:13)
#12     BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:997:49)
#13     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#14     SourceVisitor.visitReturnStatement.<anonymous closure> (package:dart_style/src/source_visitor.dart:2130:7)
#15     SourceVisitor._simpleStatement (package:dart_style/src/source_visitor.dart:3194:9)
#16     SourceVisitor.visitReturnStatement (package:dart_style/src/source_visitor.dart:2128:5)
#17     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8652:49)
#18     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#19     SourceVisitor.visitBlock (package:dart_style/src/source_visitor.dart:496:7)
#20     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#21     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#22     SourceVisitor.visitBlockFunctionBody (package:dart_style/src/source_visitor.dart:529:5)
#23     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#24     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#25     SourceVisitor._visitBody (package:dart_style/src/source_visitor.dart:2664:5)
#26     SourceVisitor.visitFunctionExpression (package:dart_style/src/source_visitor.dart:1486:5)
#27     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5082:49)
#28     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#29     ArgumentListVisitor.visit (package:dart_style/src/argument_list_visitor.dart:207:18)
#30     SourceVisitor.visitArgumentList (package:dart_style/src/source_visitor.dart:332:37)
#31     _MethodSelector.writeSelector (package:dart_style/src/call_chain_visitor.dart:486:10)
#32     _Selector.write (package:dart_style/src/call_chain_visitor.dart:439:5)
#33     CallChainVisitor.visit (package:dart_style/src/call_chain_visitor.dart:254:19)
#34     SourceVisitor.visitMethodInvocation (package:dart_style/src/source_visitor.dart:1978:34)
#35     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7245:49)
#36     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#37     SourceVisitor.visitReturnStatement.<anonymous closure> (package:dart_style/src/source_visitor.dart:2130:7)
#38     SourceVisitor._simpleStatement (package:dart_style/src/source_visitor.dart:3194:9)
#39     SourceVisitor.visitReturnStatement (package:dart_style/src/source_visitor.dart:2128:5)
#40     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8652:49)
#41     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#42     SourceVisitor.visitBlock (package:dart_style/src/source_visitor.dart:496:7)
#43     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#44     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#45     SourceVisitor.visitIfStatement.visitClause (package:dart_style/src/source_visitor.dart:1704:9)
#46     SourceVisitor.visitIfStatement (package:dart_style/src/source_visitor.dart:1727:16)
#47     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5771:49)
#48     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#49     SourceVisitor.visitBlock (package:dart_style/src/source_visitor.dart:496:7)
#50     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#51     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:2416:10)
#52     SourceVisitor.visitIfStatement.visitClause (package:dart_style/src/source_visitor.dart:1704:9)
#53     SourceVisitor.visitIfStatement (package:dart_style/src/source_visitor.dart:1727:16)
#54     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5771:49)
#55     SourceVisitor.visit (package:dart_styl...
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.6; please re-open if you see this in a recent version of Dart/Flutter.
