### ISSUE TITLE
another AS reported crash

### ISSUE THREAD

**Issue by GitHubStuff** [dart-lang/sdk#38682]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2560x1440, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Failed to handle completion domain request: {id: 482, method: completion.getSuggestions, params: {file: /Users/steven/Documents/Ensure360/Ensure360Caregiver/lib/mqtt/mqtt_connect.dart, offset: 1597}, clientRequestTime: 1569958731854}
NoSuchMethodError: The getter 'isSynthetic' was called on null.
Receiver: null
Tried calling: isSynthetic
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _KeywordVisitor._isPreviousTokenSynthetic (package:analysis_server/src/services/completion/dart/keyword_contributor.dart:932:28)
#2      _KeywordVisitor.visitIfStatement (package:analysis_server/src/services/completion/dart/keyword_contributor.dart:440:9)
#3      IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5768:49)
#4      KeywordContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/keyword_contributor.dart:44:10)
<asynchronous suspension>
#5      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:145:31)
<asynchronous suspension>
#6      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:122:42)
<asynchronous suspension>
#7      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#8      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1500:12)
#13     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#14     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#16     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1500:12)
#21     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#22     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#37     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#38     _rootRunUnary (dart:async/zone.dart:1132:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#46     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#47     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#48     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#49     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#50     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#51     _rootRunUnary (dart:async/zone.dart:1132:38)
#52     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dar...
```

For additional log information, please append the contents of
file:///private/var/folders/kq/qd9zc3ld16q0kx6l8l666qt40000gn/T/report1.txt.

**Comment by srawlins** [comment]
Thanks for reporting this issue; no need to report twice; we'll track the first bug.
