### ISSUE TITLE
Analysis Server --lsp can't handle extension methods

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#38694]
```
dartanalyzer version 2.6.0-edge.2c3f0fc359fda017565a5f23df7800a797f4c295
```

I'm running with `--lsp`. Any time I have an `extension` in my file, the analysis server won't analyze it. I get "Invalid file path" errors. Removing the extension causes it to start working, but then adding it back and it stops working.

The SDK at this commit generally has extension methods enabled. `dartanalyzer` CLI works correctly on this file.

Here is the instrumentation log:

```
1570039610328:Ver:1547748735539124457393:unknown:unknown:1.27.3:2.6.0-edge.2c3f0fc359fda017565a5f23df7800a797f4c295
1570039610482:Req:{"method"::"initialize","jsonrpc"::"2.0","id"::1,"params"::{"rootUri"::"file::///usr/local/google/home/nbosch/projects/dart_repro","initializationOptions"::{"onlyAnalyzeProjectsWithOpenFiles"::true},"capabilities"::{"workspace"::{"applyEdit"::true},"textDocument"::{"completion"::{"completionItem"::{"snippetSupport"::false}},"synchronization"::{"willSaveWaitUntil"::false,"willSave"::false,"didSave"::false},"codeAction"::{"codeActionLiteralSupport"::{"codeActionKind"::{"valueSet"::["quickfix","refactor","source"]}}},"signatureHelp"::{"dynamicRegistration"::false},"definition"::{"dynamicRegistration"::false}}},"processId"::30422,"trace"::"off"}}
1570039610622:Res:{"id"::1,"jsonrpc"::"2.0","result"::{"capabilities"::{"textDocumentSync"::{"openClose"::true,"change"::2,"willSave"::false,"willSaveWaitUntil"::false},"hoverProvider"::true,"completionProvider"::{"resolveProvider"::true,"triggerCharacters"::[".","=","(","$"]},"signatureHelpProvider"::{"triggerCharacters"::[]},"definitionProvider"::true,"implementationProvider"::true,"referencesProvider"::true,"documentHighlightProvider"::true,"documentSymbolProvider"::true,"workspaceSymbolProvider"::true,"codeActionProvider"::{"codeActionKinds"::["source","source.organizeImports","source.sortMembers","quickfix"]},"documentFormattingProvider"::true,"documentRangeFormattingProvider"::false,"documentOnTypeFormattingProvider"::{"firstTriggerCharacter"::"}","moreTriggerCharacter"::[";"]},"renameProvider"::true,"foldingRangeProvider"::true,"executeCommandProvider"::{"commands"::["edit.sortMembers","edit.organizeImports","edit.sendWorkspaceEdit","refactor.perform"]},"workspace"::{"workspaceFolders"::{"supported"::true,"changeNotifications"::true}}}}}
1570039610632:Req:{"method"::"initialized","jsonrpc"::"2.0","params"::{}}
1570039610654:Req:{"method"::"textDocument/didOpen","jsonrpc"::"2.0","params"::{"textDocument"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/web/main.dart","version"::1,"languageId"::"dart","text"::"void main() {\n  'Foo'.doStuff();\n}\n\nextension Foo on String {\n  void doStuff() {\n    print(this);\n  }\n}"}}}
1570039613247:Req:{"method"::"textDocument/documentHighlight","jsonrpc"::"2.0","id"::2,"params"::{"textDocument"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/web/main.dart"},"position"::{"character"::5,"line"::4}}}
1570039613273:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::true},"jsonrpc"::"2.0"}
1570039614226:Res:{"id"::2,"jsonrpc"::"2.0","error"::{"code"::-32003,"message"::"Invalid file path","data"::"/usr/local/google/home/nbosch/projects/dart_repro/web/main.dart"}}
1570039614705:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/foo.dart","diagnostics"::[]},"jsonrpc"::"2.0"}
1570039614714:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::false},"jsonrpc"::"2.0"}
1570039667444:Req:{"method"::"textDocument/definition","jsonrpc"::"2.0","id"::3,"params"::{"textDocument"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/web/main.dart"},"position"::{"character"::8,"line"::1}}}
1570039667447:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::true},"jsonrpc"::"2.0"}
1570039667481:Res:{"id"::3,"jsonrpc"::"2.0","error"::{"code"::-32003,"message"::"Invalid file path","data"::"/usr/local/google/home/nbosch/projects/dart_repro/web/main.dart"}}
1570039667485:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::false},"jsonrpc"::"2.0"}
1570039802079:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/web/main.dart~:add
1570039802092:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/web/main.dart~:remove
1570039802093:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/web/main.dart~","diagnostics"::[]},"jsonrpc"::"2.0"}
1570039802093:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/web/main.dart:modify
1570039802094:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::true},"jsonrpc"::"2.0"}
1570039802154:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::false},"jsonrpc"::"2.0"}
1570039802198:Req:{"method"::"textDocument/didChange","jsonrpc"::"2.0","params"::{"contentChanges"::[{"range"::{"end"::{"character"::1,"line"::8},"start"::{"character"::1,"line"::2}},"text"::"","rangeLength"::69}],"textDocument"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/web/main.dart","version"::2}}}
1570039802203:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::true},"jsonrpc"::"2.0"}
1570039802393:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/web/main.dart","diagnostics"::[{"range"::{"start"::{"line"::1,"character"::8},"end"::{"line"::1,"character"::15}},"severity"::1,"code"::"undefined_method","source"::"dart","message"::"The method 'doStuff' isn't defined for the class 'String'.\nTry correcting the name to the name of an existing method, or defining a method named 'doStuff'."}]},"jsonrpc"::"2.0"}
1570039802399:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::false},"jsonrpc"::"2.0"}
1570039804307:Req:{"method"::"textDocument/didChange","jsonrpc"::"2.0","params"::{"contentChanges"::[{"range"::{"end"::{"character"::1,"line"::2},"start"::{"character"::1,"line"::2}},"text"::"\n\nextension Foo on String {\n  void doStuff() {\n    print(this);\n  }\n}","rangeLength"::0}],"textDocument"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/web/main.dart","version"::3}}}
1570039804308:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::true},"jsonrpc"::"2.0"}
1570039804354:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/web/main.dart:modify
1570039804389:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::false},"jsonrpc"::"2.0"}
1570039856311:Req:{"method"::"textDocument/documentHighlight","jsonrpc"::"2.0","id"::4,"params"::{"textDocument"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/web/main.dart"},"position"::{"character"::0,"line"::1}}}
1570039856312:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::true},"jsonrpc"::"2.0"}
1570039856368:Res:{"id"::4,"jsonrpc"::"2.0","error"::{"code"::-32003,"message"::"Invalid file path","data"::"/usr/local/google/home/nbosch/projects/dart_repro/web/main.dart"}}
1570039856371:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::false},"jsonrpc"::"2.0"}
1570039857103:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/.git/index.lock:add
1570039857104:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/.git/index.lock:remove
1570039857116:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/.git/index.lock:add
1570039857116:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/.git/index.lock:remove
1570039861922:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/.git/index.lock:add
1570039861924:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/.git/index.lock:remove
1570039863807:Req:{"method"::"textDocument/didOpen","jsonrpc"::"2.0","params"::{"textDocument"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/pubspec.yaml","version"::1,"languageId"::"yaml","text"::"name:: dart_repro\n\nenvironment::\n  sdk:: \">=2.3.0 <3.0.0\"\n\ndependencies::\n  js:: any\n\ndev_dependencies::\n  build_runner:: any\n  build_web_compilers:: any"}}}
1570039863808:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::true},"jsonrpc"::"2.0"}
1570039863811:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::false},"jsonrpc"::"2.0"}
1570039867697:Req:{"method"::"textDocument/didChange","jsonrpc"::"2.0","params"::{"contentChanges"::[{"range"::{"end"::{"character"::13,"line"::3},"start"::{"character"::12,"line"::3}},"text"::"6","rangeLength"::1}],"textDocument"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/pubspec.yaml","version"::2}}}
1570039867698:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::true},"jsonrpc"::"2.0"}
1570039867700:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::false},"jsonrpc"::"2.0"}
1570039867857:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/pubspec.yaml~:add
1570039867900:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/pubspec.yaml~:remove
1570039867901:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/pubspec.yaml~","diagnostics"::[]},"jsonrpc"::"2.0"}
1570039867901:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/pubspec.yaml:modify
1570039867957:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::true},"jsonrpc"::"2.0"}
1570039870286:Watch:/usr/local/google/home/nbosch/projects/dart_repro:/usr/local/google/home/nbosch/projects/dart_repro/pubspec.yaml:modify
1570039870549:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///usr/local/google/home/nbosch/projects/dart_repro/foo.dart","diagnostics"::[]},"jsonrpc"::"2.0"}
1570039870553:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::false},"jsonrpc"::"2.0"}
```

**Comment by natebosch** [comment]
Even more confusing, depending on the _content_ of the extension it can start working.

Doesn't work, see above:

```dart
void main() {
  'Foo'.doStuff();
}

extension Foo on String {
  void doStuff() {
    print(this);
  }
}
```

Adding 1 throw statement makes it work:

```dart
void main() {
  'Foo'.doStuff();
}

extension Foo on String {
  void doStuff() {
    print(this);
    throw 'sad';
  }
}
```

Removing the throw brings the behavior back to what it was.

**Comment by bwilkerson** [comment]
I don't see the same behavior running in IntelliJ with a build from this morning. I'm not sure what the important difference is. @DanTup Any ideas?

**Comment by DanTup** [comment]
We had an issue where extension methods weren't mapped onto a valid SymbolKind. The fix for that is here:

https://github.com/dart-lang/sdk/commit/3cffdaa01e654b7929efac376282891c82977c7b

What I can't explain though, is why you get this weird error, since I got the error:

```
[Error - 8:05:15 AM] Request textDocument/documentSymbol failed.
  Message: An error occurred while handling textDocument/documentSymbol request
  Code: -32001 
[Error - 8:05:15 AM] An error occurred while handling textDocument/documentSymbol request: kind is required but was not provided
#0      new DocumentSymbol (package:analysis_server/lsp_protocol/protocol_generated.dart:5775:7)
#1      DocumentSymbolHandler._asDocumentSymbol (package:analysis_server/src/lsp/handlers/handler_document_symbols.dart:80:16)
#2      DocumentSymbolHandler._getSymbols.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_document_symbols.dart:130:32)
```

But also - I can't reproduce with the latest nightly (which includes the fix). But the hash given above looks like it should already include the fix. @natebosch - could you try on the nightly from https://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/ just to ensure we're on the exact same version? (and ensure you're not running the server from source or something that might affect that - the hash in the log matches what you gave, but I think that's just the SDK version and wouldn't reflect if you were running from source or an older snapshot).

**Comment by natebosch** [comment]
I installed the nightly - `dartanalyzer version 2.6.0-edge.c1f691c7973fdd9d31179097b6e7ff2b3b1d2931` and it does not repro.

I also can't repro on `dartanalyzer version 2.6.0-dev.5.0`.

I also did a fresh local build by removing the `out` directory and then `tools/build.py --mode release --arch x64 create_sdk`. It's version `dartanalyzer version 2.6.0-edge.2c3f0fc359fda017565a5f23df7800a797f4c295`. The problem no longer repros there either.

I had this very consistently reproducible before, but I guess we'll need to chalk it up to something strange in my local build? Or maybe there is some difference around the summary cache where after I had it working with another SDK it no longer is broken on the original one?

Either way, if I can't get it to show up again I don't think we can diagnose.

**Comment by DanTup** [comment]
> I had this very consistently reproducible before, but I guess we'll need to chalk it up to something strange in my local build?

I'm not very familiar with building the SDK locally (I tend to use nightlies and run the server from source), but is it possible you might have had a stale analysis_server snapshot file?

> Or maybe there is some difference around the summary cache where after I had it working with another SDK it no longer is broken on the original one?

I'm not familiar with what this is, though the bug linked above was directly in the server implementation code (it seems like the same issue, though why it would generate the error it did still puzzles me).

If you see it again let me know and we'll go from there.
