### ISSUE TITLE
Dart Analysis Server error

### ISSUE THREAD

**Issue by alectogeek** [dart-lang/sdk#38738]
Happened because of my typo:
`return <List<Section>, List<Category>>(sections, categories);`
instead of 
`return Tuple2<List<Section>, List<Category>>(sections, categories);`

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2560x1440, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
NoSuchMethodError: The getter 'next' was called on null.
Receiver: null
Tried calling: next
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Parser.parseLiteralFunctionSuffix (package:front_end/src/fasta/parser/parser.dart:4576:38)
#2      Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4608:14)
#3      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4295:14)
#4      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#5      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#6      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#7      Parser.parseReturnStatement (package:front_end/src/fasta/parser/parser.dart:3851:13)
#8      Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3734:14)
#9      Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#10     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#11     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3269:15)
#12     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#13     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#14     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#15     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#16     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#17     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#18     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#19     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#20     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#21     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#22     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#23     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:660:14)
#24     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:695:16)
#25     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#26     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#27     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#28     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#29     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#30     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#31     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#32     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#38     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#39     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#40     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#42     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#43     new Future.sync (dart:async/future.dart:224:31)
#44     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#45     _rootRun (dart:async/zone.dart:1124:13)
#46     _CustomZone.run (dart:async/zone.dart:1021:19)
#47     _runZoned (dart:async/zone.dart:1516:10)
#48     runZoned (dart:async/zone.dart:1463:12)
#49     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#50     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#51     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#52     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#53     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#54     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysi...
```

**Comment by keertip** [comment]
Thank you for reporting this issue! This was previously reported in #37066, please follow along there.
