### ISSUE TITLE
dart analyzer crash ( dart 2.6.0 )

### ISSUE THREAD

**Issue by sahandevs** [dart-lang/sdk#38736]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35, server version 1.27.3, error: Failed to handle completion domain request: {id: 442, method: completion.getSuggestions, params: {file: C:\Users\Sahand\AndroidStudioProjects\playground\lib\main.dart, offset: 763}, clientRequestTime: 1570444861560}
NoSuchMethodError: The getter 'staticElement' was called on null.
Receiver: null
Tried calling: staticElement
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _LocalVisitor._staticTypeOfIdentifier (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:572:12)
#2      _LocalVisitor._addLocalSuggestion_includeReturnValueSuggestions (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:443:9)
#3      _LocalVisitor.declaredExtension (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:167:7)
#4      LocalDeclarationVisitor.visitCompilationUnit.<anonymous closure> (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:113:9)
#5      ListMixin.forEach (dart:collection/list.dart:63:13)
#6      LocalDeclarationVisitor.visitCompilationUnit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:106:23)
#7      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#8      LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:218:18)
#9      GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#10     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#11     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:202:7)
#12     GeneralizingAstVisitor.visitExtensionDeclaration (package:analyzer/dart/ast/visitor.dart:278:7)
#13     ExtensionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3928:49)
#14     LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:218:18)
#15     LocalDeclarationVisitor.visitMethodDeclaration (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:211:5)
#16     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7108:49)
#17     LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:218:18)
#18     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#19     GeneralizingAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:268:7)
#20     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3583:15)
#21     LocalDeclarationVisitor.visit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:72:12)
#22     LocalReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:67:17)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#29     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#37     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by parlough** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/38798

Should be fixed by https://github.com/dart-lang/sdk/commit/b08d7756bd1d935af31c868af44653269b79f0ed but the relevant code has changed a lot either way making this error rather stale.
