### ISSUE TITLE
True output divergences

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#38741]
```
Isolate (/b/s/w/itzeKBvn/dart_fuzzDWVNFP) FP NO-FFI FLAT : KBC-CMP-SRC-ReleaseX64 - JIT-SLOWPATH-DebugX64: !DIVERGENCE! 1.59:139047971 (output)

-- BEGIN REPRODUCE  --

dartfuzz.dart --fp --no-ffi --flat --seed 139047971 /b/s/w/itzeKBvn/dart_fuzzDWVNFP/fuzz.dart

-- RUN 1 --

/b/s/w/ir/out/ReleaseX64/dart --use-bytecode-compiler --old_gen_heap_size=128 /b/s/w/itzeKBvn/dart_fuzzDWVNFP/fuzz.dart

-- RUN 2 --

/b/s/w/ir/out/DebugX64/dart --use-slow-path --old_gen_heap_size=128 /b/s/w/itzeKBvn/dart_fuzzDWVNFP/fuzz.dart

-- END REPRODUCE  --

```

**Comment by aartbik** [comment]
Another one, filing under same bug, but we can split after triaging.

```
Isolate (/b/s/w/itkj5RV2/dart_fuzzEUYAVG) NO-FP NO-FFI FLAT : KBC-CMP-SLOWPATH-DebugX64 - JIT-DET-DebugIA32: !DIVERGENCE! 1.59:109905974 (output)

-- BEGIN REPRODUCE  --

dartfuzz.dart --no-fp --no-ffi --flat --seed 109905974 /b/s/w/itkj5RV2/dart_fuzzEUYAVG/fuzz.dart

-- RUN 1 --

/b/s/w/ir/pkg/vm/tool/gen_kernel --gen-bytecode --platform=/b/s/w/ir/out/DebugX64/vm_platform_strong.dill -o /b/s/w/itkj5RV2/dart_fuzzEUYAVG/out.dill /b/s/w/itkj5RV2/dart_fuzzEUYAVG/fuzz.dart
/b/s/w/ir/out/DebugX64/dart --use-bytecode-compiler --use-slow-path --old_gen_heap_size=128 /b/s/w/itkj5RV2/dart_fuzzEUYAVG/out.dill

-- RUN 2 --

/b/s/w/ir/out/DebugIA32/dart --deterministic --old_gen_heap_size=128 /b/s/w/itkj5RV2/dart_fuzzEUYAVG/fuzz.dart

-- END REPRODUCE  --
```

**Comment by aartbik** [comment]
One more, adding here for now, we can split this into new bug if required after triaging.

```
FP FFI FLAT : KBC-CMP-SRC-DebugX64 - KBC-MIX-O3-SLOWPATH-ReleaseX64: !DIVERGENCE! 1.59:2010734172 (output)

-- BEGIN REPRODUCE  --

dartfuzz.dart --fp --ffi --flat --seed 2010734172 /b/s/w/itnlQ5Xw/dart_fuzzEGEXZY/fuzz.dart

-- RUN 1 --

/b/s/w/ir/out/DebugX64/dart --use-bytecode-compiler --old_gen_heap_size=128 /b/s/w/itnlQ5Xw/dart_fuzzEGEXZY/fuzz.dart

-- RUN 2 --

/b/s/w/ir/pkg/vm/tool/gen_kernel --gen-bytecode --platform=/b/s/w/ir/out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/itnlQ5Xw/dart_fuzzEGEXZY/out.dill /b/s/w/itnlQ5Xw/dart_fuzzEGEXZY/fuzz.dart
/b/s/w/ir/out/ReleaseX64/dart --enable-interpreter --optimization_level=3 --use-slow-path --old_gen_heap_size=128 /b/s/w/itnlQ5Xw/dart_fuzzEGEXZY/out.dill

-- END REPRODUCE  --

```

**Comment by aartbik** [comment]
I was unable to repro 139047971 (first output dependences); all execution mode agree on the output.

**Comment by aartbik** [comment]
I can repro 109905974 (second output dependence), where IA32 run disagrees with most others.

```
< X3().run() throws
27c26
< 5
---
> 26

```

**Comment by fizaaluthra** [comment]
Able to reproduce 2010734172 (third divergence).
Run 2 throws an exception similar to the one above for 109905974. 

```NoSuchMethodError: Class 'int' has no instance method '<' with matching arguments.
Receiver: 0
Tried calling: <(0)
Found: <(num) => bool
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Int32x4List.[] (dart:typed_data-patch/typed_data_patch.dart:2822:15)
#2      _TypedListIterator.moveNext (dart:typed_data-patch/typed_data_patch.dart:3689:24)
#3      StringBuffer.writeAll (dart:core-patch/string_buffer_patch.dart:94:19)
#4      IterableBase.iterableToFullString (dart:collection/iterable.dart:267:14)
#5      ListBase.listToString (dart:collection/list.dart:29:20)
#6      _TypedListBase.toString (dart:typed_data-patch/typed_data_patch.dart:101:33)
#7      _StringBase._interpolate (dart:core-patch/string_patch.dart:854:23)
#8      main (file:///usr/local/google/home/fizaaluthra/dart-sdk/sdk/fuzz.dart)```

**Comment by fizaaluthra** [comment]
Also not able to reproduce 139047971 (first divergence). 
However, it seems to happen intermittently when I revert back to some older commits.

**Comment by aartbik** [comment]
The intrinsified graph looks healthy at first glance. The unexpected exception happens while deoptimizing in moveNext for the following code

```dart
           for (Int32x4 loc2 in new Int32x4List(27)) {
              var31 = fld1_3;
            }
```

as traced below. 

```
== Deoptimizing code for 'dart:typed_data__TypedListIterator@6027147_moveNext', code & frame, 
Eager deopt fp=00007f9dbf9fd580 pc=00007f9dbac8f95a
Deoptimizing (reason 14 'GuardField') at pc=00007f9dbac8f95a fp=00007f9dbf9fd580 'dart:typed_data__TypedListIterator@6027147_moveNext' (count 0)
Deoptimizing 'dart:core_NoSuchMethodError_NoSuchMethodError.withInvocation' (count 1)
Deoptimizing 'dart:core_Object_noSuchMethod' (count 1)
Deoptimizing 'dart:core_Null_<' (count 1)
Deoptimizing 'dart:typed_data__Int32x4List@6027147_[]' (count 1)
Deoptimizing 'dart:typed_data__TypedListIterator@6027147_moveNext' (count 1)
  Function: dart:core_NoSuchMethodError_NoSuchMethodError.withInvocation
  Line 0: '<optimized out>'
  Deopt args: 0
Deopt for field guard (field Field <NoSuchMethodError._receiver@0150898>: final)
Deopt for field guard (field Field <_InvocationMirror@0150898._type@0150898>:)
NoSuchMethodError: Class 'int' has no instance method '<' with matching arguments.
Receiver: 17
Tried calling: <(0)
Found: <(num) => bool
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Int32x4List.[] (dart:typed_data-patch/typed_data_patch.dart:2822:15)

```

**Comment by aartbik** [comment]
@mraleph can you have a look, this one is a bit puzzling

**Comment by mraleph** [comment]
There is a bug in the `jit_call_specializer.cc` when converting calls - there is a disagreement between dynamic type feedback and compile time types. We have call like this: 

```
v32 <- InstanceCall:12( <<0>, v29, v31 IC[2: _Smi@0150898, _Smi@0150898 cnt:0 trgt:'_IntegerImplementation@0150898.<' | Null, _Smi@0150898 cnt:1 trgt:'Null.<'])
```

which we end up transforming into a static call to `Null.<` without class check, because `FlowGraph::CheckForInstanceCall` returns that no check is necessary based on the information available in compile types. We know that `v29` is actually a `_Smi`. 

However the feedback we have disagrees with this: because call count of the first entry is zero we consider this ICData to be monomorphic. 

There is code in the `jit_call_specializer.cc` that tries to deal with this, but it does not skip 0 count entries (which can only occur for arithmetic operators AFAIK).

I think this

```diff
diff --git a/runtime/vm/compiler/backend/flow_graph.cc b/runtime/vm/compiler/backend/flow_graph.cc
index 39e8dc52e4..5016129d54 100644
--- a/runtime/vm/compiler/backend/flow_graph.cc
+++ b/runtime/vm/compiler/backend/flow_graph.cc
@@ -400,6 +400,9 @@ FlowGraph::ToCheck FlowGraph::CheckForInstanceCall(
     Class& cls = Class::Handle(zone());
     Function& fun = Function::Handle(zone());
     for (intptr_t i = 0, len = data->NumberOfChecks(); i < len; i++) {
+      if (!data->IsUsedAt(i)) {
+        continue;
+      }
       fun = data->GetTargetAt(i);
       cls = fun.Owner();
       if (data->GetReceiverClassIdAt(i) == cid || cls.id() == cid) {
```

should fix it.

**Comment by aartbik** [comment]
Thanks @mraleph
