### ISSUE TITLE
Analyzer fuzz crash: function literal in annotation argument for generic class

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38744]
```dart
@F(() {})
class C {}
class F<T> {
  const F(Function(T) t);
}
```

```
Unhandled exception:
NoSuchMethodError: The getter 'isBottom' was called on null.
Receiver: null
Tried calling: isBottom
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _isLegacyBottom (package:analyzer/src/generated/type_system.dart:62:13)
#2      GenericInferrer._matchSubtypeOf (package:analyzer/src/generated/type_system.dart:1790:9)
#3      GenericInferrer.tryMatchSubtypeOf (package:analyzer/src/generated/type_system.dart:1411:20)
#4      GenericInferrer.constrainArgument (package:analyzer/src/generated/type_system.dart:1238:5)
#5      Dart2TypeSystem.inferGenericFunctionOrType (package:analyzer/src/generated/type_system.dart:293:16)
#6      ElementResolver._resolveAnnotationConstructor (package:analyzer/src/generated/element_resolver.dart:1279:41)
#7      ElementResolver._resolveAnnotationElement (package:analyzer/src/generated/element_resolver.dart:1341:23)
#8      ElementResolver.visitSimpleIdentifier (package:analyzer/src/generated/element_resolver.dart:873:7)
#9      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8987:49)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4265:10)
```

**Comment by DanTup** [comment]
This was raised in the Dart-Code repo, which I think may be the same (there are annotations with calls to constructors):

https://github.com/Dart-Code/Dart-Code/issues/2026

**Comment by scheglov** [comment]
Cannot reproduce, possibly the same as 38565.
The change that caused it was reverted in cb9a35ca53911e19ea231df216d014ce4520aa6e.
