### ISSUE TITLE
I want to call gen_kernel to generate kernel with bytecode, but it failed

### ISSUE THREAD

**Issue by waruqi** [dart-lang/sdk#38762]
```console
.//third_party/dart/pkg/vm/tool/gen_kernel --gen-bytecode --platform=./out/android_release_arm64//vm_platform_strong.dill -o /tmp/app.dill ../../projects/jsonexample/lib/main.dart 
```

The errors:

```
../../flutter/packages/flutter/lib/painting.dart:20:1: Error: Not found: 'dart:ui'
export 'dart:ui' show Shadow, PlaceholderAlignment;
^
../../flutter/packages/flutter/lib/src/animation/animation.dart:61:20: Error: Type 'VoidCallback' not found.
  void addListener(VoidCallback listener);
                   ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/animation/animation.dart:70:23: Error: Type 'VoidCallback' not found.
  void removeListener(VoidCallback listener);
                      ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/animation/animation.dart:61:20: Error: 'VoidCallback' isn't a type.
  void addListener(VoidCallback listener);
                   ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/animation/animation.dart:70:23: Error: 'VoidCallback' isn't a type.
  void removeListener(VoidCallback listener);
                      ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/animation/animation_controller.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show lerpDouble;
       ^
../../flutter/packages/flutter/lib/src/animation/animation_controller.dart:859:14: Error: Method not found: 'lerpDouble'.
      return ui.lerpDouble(max, min, t);
             ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/animation/animation_controller.dart:862:14: Error: Method not found: 'lerpDouble'.
      return ui.lerpDouble(min, max, t);
```

**Comment by waruqi** [comment]
But I modify platform to `--platform==$enginesrc/out/android_release_arm64/flutter_patched_sdk/platform_strong.dill`, it crashed.

my gen_kernel script
```bash
#!/bin/bash
enginesrc=~/projects/working/flutter/engine/src
outputfile=$1
$enginesrc/third_party/dart/pkg/vm/tool/gen_kernel --gen-bytecode --platform==$enginesrc/out/android_release_arm64/flutter_patched_sdk/platform_strong.dill \
    --packages=.packages -o $outputfile lib/main.dart
```

```console
$ cd flutter/projects/jsonexample
$ ./gen_kernel /tmp/app.dill
Unhandled exception:
Crash when compiling package:jsonexample/main.dart,
at character offset null:
RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:393:10)
#5      ProcessedOptions.loadLinkDependencies.<anonymous closure> (package:front_end/src/base/processed_options.dart:377:35)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#7      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#8      ProcessedOptions.loadLinkDependencies (package:front_end/src/base/processed_options.dart:377:67)
<asynchronous suspension>
#9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:109:48)
<asynchronous suspension>
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:69:10)
<asynchronous suspension>
#12     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:60:35)
<asynchronous suspension>
#13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:134:20)
<asynchronous suspension>
#14     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#15     new Future.sync (dart:async/future.dart:224:31)
#16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#22     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:132:10)
#23     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:59:32)
<asynchronous suspension>
#24     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:51:17)
<asynchronous suspension>
#25     compileToKernel (package:vm/kernel_front_end.dart:281:41)
<asynchronous suspension>
#26     runCompiler (package:vm/kernel_front_end.dart:215:27)
<asynchronous suspension>
#27     compile (file:///Users/ruki/projects/working/flutter/engine/src/third_party/dart/pkg/vm/bin/gen_kernel.dart:39:10)
<asynchronous suspension>
#28     main (file:///Users/ruki/projects/working/flutter/engine/src/third_party/dart/pkg/vm/bin/gen_kernel.dart:34:16)
<asynchronous suspension>
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by waruqi** [comment]
I have resolved this problem.

```console
$flutterdir/bin/cache/dart-sdk/bin/dart \
    $flutterdir/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --gen-bytecode \
    --sdk-root $flutterdir/bin/cache/artifacts/engine/common/flutter_patched_sdk/ \
    --strong --target=flutter --no-link-platform --packages .packages \
    --output-dill $outputdir/app.dill --filesystem-scheme org-dartlang-root package:jsonexample/main.dart
```
