### ISSUE TITLE
Android Studio - Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by mileskrell** [dart-lang/sdk#38776]
While working on a Flutter project in Android Studio, an error was reported (though I didn't actually notice any problems, or even what triggered it). Anyway, it provided a link to open an issue with the following content, so I figured I might as well.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1200`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/mileskrell/StudioProjects/flutter_client_main/lib/Home/home.dart context: exception_20191008_173518_190
NoSuchMethodError: Class 'ClassElementForLink_Enum' has no instance method 'getSetter' with matching arguments.
Receiver: Instance of 'ClassElementForLink_Enum'
Tried calling: getSetter("const")
Found: getSetter(String) => PropertyAccessorElement
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ClassElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:554:48)
#2      ClassElementForLink_Enum.getSetter (package:analyzer/src/dart/element/element.dart:187:27)
#3      ElementResolver._resolveElement (package:analyzer/src/generated/element_resolver.dart:1686:30)
#4      ElementResolver._resolvePropertyAccess (package:analyzer/src/generated/element_resolver.dart:1772:25)
#5      ElementResolver.visitPrefixedIdentifier (package:analyzer/src/generated/element_resolver.dart:667:5)
#6      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8305:49)
#7      ResolverVisitor.visitPrefixedIdentifier (package:analyzer/src/generated/resolver.dart:4276:10)
#8      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8305:49)
#9      ResolverVisitor.visitAssignmentExpression (package:analyzer/src/generated/resolver.dart:3388:11)
#10     AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:747:49)
#11     ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2564:16)
#12     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5387:36)
#13     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5230:7)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#15     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#16     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5666:47)
#17     TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5215:48)
#18     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1642:16)
#19     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3870:12)
#20     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3570:15)
#21     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3510:7)
#22     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#23     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#24     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#25     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3543:42)
#26     Linker.link (package:analyzer/src/summary/link.dart:4075:35)
#27     _relink (package:analyzer/src/summary/link.dart:312:74)
#28     link (package:analyzer/src/summary/link.dart:126:3)
#29     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:220:25)
#30     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#31     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:219:12)
#32     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:98:7)
#33     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1429:29)
#34     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1245:30)
#35     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#36     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#37     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#38     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#39     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#40     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#41     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#42     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#43     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _runZoned (dart:async/zone.dart:1516:10)
#47     runZoned (dart:async/zone.dart:1463:12)
#48     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#49     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#50     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#51     _AsyncAwaitCompleter.start (da...
```

For additional log information, please append the contents of
file:///private/var/folders/n1/35ydy6gx1f15qdm0fcfkrrvm0000gp/T/report.txt.

---

I'm including report.txt [here](https://github.com/dart-lang/sdk/files/3704637/report.txt).

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.5.0. Please re-open if you see this crash again.
