### ISSUE TITLE
dart2js crashes if `const []` is both `List<T1>` and `List<FutureOr<T2>>`

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#38821]
The following code crashes dart2js:

```dart
import 'dart:async';

void main() {
  List<String> xs = const [];
  List<FutureOr<int>> ys = const [];
  print(xs);
  print(ys);
}
```

You can replace `String` and `int` with whatever you want. The issue disappears if either `xs` or `ys` is removed or if either `const` is removed.

Here's the stack trace:
```
Unhandled exception:                                                                                                                                          
NoSuchMethodError: The method '>' was called on null.                                                                                                         
Receiver: null                                                                                                                                                
Tried calling: >(1)                                                                                                                                           
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)                                                                                          
#1      int.< (dart:core-patch/integers.dart:95:18)                                                                                                           
#2      int.compareTo (dart:core-patch/integers.dart:197:14)                                                                                                  
#3      _DartTypeOrdering.compare (package:compiler/src/js_emitter/constant_ordering.dart:238:38)                                                             
#4      _ConstantOrdering.compareLists (package:compiler/src/js_emitter/constant_ordering.dart:50:18)                                                         
#5      _DartTypeOrdering._compareTypeArguments (package:compiler/src/js_emitter/constant_ordering.dart:304:30)                                               
#6      _DartTypeOrdering.visitInterfaceType (package:compiler/src/js_emitter/constant_ordering.dart:280:12)                                                  
#7      InterfaceType.accept (package:compiler/src/elements/types.dart:208:15)                                                                                
#8      _DartTypeOrdering.compare (package:compiler/src/js_emitter/constant_ordering.dart:241:11)                                                             
#9      _ConstantOrdering.compareDartTypes (package:compiler/src/js_emitter/constant_ordering.dart:75:30)                                                     
#10     _ConstantOrdering.visitList (package:compiler/src/js_emitter/constant_ordering.dart:121:12)                                                           
#11     ListConstantValue.accept (package:compiler/src/constants/values.dart:594:56)                                                                          
#12     _ConstantOrdering.compareValues (package:compiler/src/js_emitter/constant_ordering.dart:36:14)                                                        
#13     _ConstantOrdering.compare (package:compiler/src/js_emitter/constant_ordering.dart:30:52)                                                              
#14     ModelEmitter.compareConstants (package:compiler/src/js_emitter/startup_emitter/model_emitter.dart:157:30)                                             
#15     EmitterImpl.compareConstants (package:compiler/src/js_emitter/startup_emitter/emitter.dart:215:21)                                                    
#16     Sort._insertionSort (dart:_internal/sort.dart:69:36)                                                                                                  
#17     Sort._doSort (dart:_internal/sort.dart:58:7)                                                                                                          
#18     Sort._dualPivotQuicksort (dart:_internal/sort.dart:294:5)                                                                                             
#19     Sort._doSort (dart:_internal/sort.dart:60:7)                                                                                                          
#20     Sort.sort (dart:_internal/sort.dart:33:5)                                                                                                             
#21     ListMixin.sort (dart:collection/list.dart:335:10)
#22     CodegenWorldImpl.getConstantsForEmission (package:compiler/src/universe/codegen_world_builder.dart:894:14)                                           
#23     Collector.computeNeededConstants (package:compiler/src/js_emitter/program_builder/collector.dart:128:23)                                             
#24     Collector.collect (package:compiler/src/js_emitter/program_builder/collector.dart:314:5)                                                             
#25     ProgramBuilder.buildProgram (package:compiler/src/js_emitter/program_builder/program_builder.dart:180:15)                                            
#26     EmitterImpl.emitProgram.<anonymous closure> (package:compiler/src/js_emitter/startup_emitter/emitter.dart:193:29)                                    
#27     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)                                                                          
#28     EmitterImpl.emitProgram (package:compiler/src/js_emitter/startup_emitter/emitter.dart:192:29)                                                        
#29     CodeEmitterTask.assembleProgram.<anonymous closure> (package:compiler/src/js_emitter/code_emitter_task.dart:149:26)                                  
#30     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#31     CodeEmitterTask.assembleProgram (package:compiler/src/js_emitter/code_emitter_task.dart:118:12)                                                      
#32     JsBackendStrategy.assembleProgram (package:compiler/src/js_model/js_strategy.dart:374:35)
#33     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:399:39)                                                                              
#34     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:282:9)                                                                           
<asynchronous suspension>
#35     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:441:9)                                                            
#36     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)                                                                          
#37     Compiler.compileFromKernel (package:compiler/src/compiler.dart:414:14)
#38     Compiler.runInternal (package:compiler/src/compiler.dart:255:13)
<asynchronous suspension>
#39     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:210:38)                                                     
#40     new Future.sync (dart:async/future.dart:224:31)
#41     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:210:20)                                                                         
#42     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)                                                                          
#43     Compiler.run (package:compiler/src/compiler.dart:207:41)
#44     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)                                                   
#45     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)                                                                
#48     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#50     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)                                                                        
#51     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#52     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#53     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)                                                                          
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

cc @sigmundch

**Comment by lrhn** [comment]
It crashes even if the type of `xs` is `List<String>`. It looks more like the `_DartTypeKindVisitor.kind` of one of the constants is `null`.
