### ISSUE TITLE
Analyzer crash on extension method doc reference

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#38839]
The area of code at this offset is below; the offset refers to `[extensionNumber]`.

```dart
extension SimpleStringExtension on String {
  /// Print this and [another].
  /// Refer to [indexOf], from [String].
  /// Also refer to [extensionNumber].
  void doStuff(String another) {
    print(this + another);
  }

  int get extensionNumber => 3;
}
```

--snip--

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6817.14`
- `2.6.0-dev.7.0`
- `IC-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-dev.7.0, server version 1.27.3, FATAL error: Failed to handle request: {id: 3783, method: edit.getFixes, params: {file: /Users/jcollins/dart/dartdoc/testing/test_package/lib/example.dart, offset: 14213}, clientRequestTime: 1570815484519}
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      FixProcessor._addFix_updateSdkConstraints (package:analysis_server/src/services/correction/fix_internal.dart:4387:23)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#3      FixProcessor._addFix_updateSdkConstraints (package:analysis_server/src/services/correction/fix_internal.dart:4369:44)
#4      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:344:13)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:204:28)
#7      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:69:41)
#8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#9      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:66:33)
#10     EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:656:46)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information, please append the contents of
file:///private/var/folders/w1/ynzyqn915kng3c3psc6b9js0000b33/T/report.txt.

**Comment by jcollins-g** [comment]
This is from the testing/test_package subdirectory inside Dartdoc.  The pubspec.yaml:

```yaml
name: test_package
homepage: http://github.com/dart-lang
description: Best package ever.
version: 0.0.1
dependencies:
  meta: ^1.0.0
  args: ^1.5.0
  test_package_imported:
    path: "../test_package_imported"
```
