### ISSUE TITLE
Migration: EdgeBuilder should looks up compound assignments using getter type

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#38847]
The following code crashes the migration tool:
```dart
abstract class _C<T> {
  _D<T> get x;
  void set x(Iterable<T> value);
}
class _D<T> implements Iterable<T> {
  noSuchMethod(invocation) => super.noSuchMethod(invocation);
  _D<T> operator+(int i) => this;
}
_f(_C<int>/*?*/ c) => c?.x += 1;
```
The crash is in the EdgeBuilder phase, during a call to `DecoratedClassHierarchy.getDecoratedSupertype`.  It looks like what's happening is that it's trying to look up `operator+` using the setter type of `_C.x` (which is `Iterable<int>`).  It should be trying to look it up on the getter type (which is `_D<int>`).

**Comment by srawlins** [comment]
It still crashes:

```none
Bad state: Unrelated types: abstract class Iterable<E> and class _D<T> implements Iterable<T*>*                                                                  
                                                                                                                                                                 
#0      DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:67:10)                                          
#1      DecoratedClassHierarchy.asInstanceOf (package:nnbd_migration/src/decorated_class_hierarchy.dart:38:18)                                                   
#2      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:234:16)
#3      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2238:48)
#4      EdgeBuilder.visitAssignmentExpression (package:nnbd_migration/src/edge_builder.dart:383:26)
#5      AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:722:49)
#6      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2104:22)
#7      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2218:20)
#8      EdgeBuilder.visitExpressionFunctionBody (package:nnbd_migration/src/edge_builder.dart:760:5)
#9      ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3500:15)
#10     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2104:22)
#11     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:879:25)
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
