### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Rohitkumar2689** [dart-lang/sdk#38856]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 8(amd64) v6.2 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Failed to handle completion domain request: {id: 1468, method: completion.getSuggestionDetails, params: {file: F:\work\flutter_app_001\lib\main.dart, id: 374, label: Column, offset: 1489}, clientRequestTime: 1570967216547}
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:199:7)
#1      AnalysisSessionImpl.getLibraryByUri (package:analyzer/src/dart/analysis/session.dart:108:5)
<asynchronous suspension>
#2      CompletionDomainHandler.getSuggestionDetails (package:analysis_server/src/domain_completion.dart:179:49)
<asynchronous suspension>
#3      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:210:9)
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _runZoned (dart:async/zone.dart:1516:10)
#7      runZoned (dart:async/zone.dart:1500:12)
#8      CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:206:12)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:349:45)
#10     _PerformanceTagImpl.makeCurrent

**Comment by srawlins** [comment]
This is a very old version of Dart (or Flutter), and has likely been fixed (similar to https://github.com/dart-lang/sdk/issues/35456); please upgrade to a modern version of dart and please re-open if you hit this again.
