### ISSUE TITLE
UnimplementedError - AstBuilder.endClassConstructor

### ISSUE THREAD

**Issue by NorbertSandor** [dart-lang/sdk#38858]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-65-generic, screens 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35, server version 1.27.3, error: Captured exception
UnimplementedError
#0      AstBuilder.endClassConstructor (package:analyzer/src/fasta/ast_builder.dart:1688:7)
#1      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3410:20)
#2      Parser.parseInvalidOperatorDeclaration (package:front_end/src/fasta/parser/parser.dart:6478:19)
#3      Parser.recoverFromInvalidMember (package:front_end/src/fasta/parser/parser.dart:6521:14)
#4      Parser.parseClassOrMixinOrExtensionMemberImpl (package:front_end/src/fasta/parser/parser.dart:3163:16)
#5      Parser.parseClassOrMixinOrExtensionBody (package:front_end/src/fasta/parser/parser.dart:2942:15)
#6      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1803:13)
#7      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1762:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#11     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:159:32)
#12     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:154:12)
#13     _File._parse (package:analyzer/src/services/available_declarations.dart:1842:23)
#14     _File.refresh (package:analyzer/src/services/available_declarations.dart:1163:30)
#15     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#16     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#17     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:281:13)
#18     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#19     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:280:27)
#20     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1906:35)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#28     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#29     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#30     Monitor.signal (package:analyzer/src/dart/analysis/status.dart)
#31     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#36     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#37     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#45     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by srawlins** [comment]
This exception should not be thrown any longer, as per https://github.com/dart-lang/sdk/issues/39230.
