### ISSUE TITLE
IntelliJ told me to add this

### ISSUE THREAD

**Issue by Tinhorn** [dart-lang/sdk#38881]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      ListMixin.first (dart:collection/list.dart:76:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#6      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#7      RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#8      LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#9      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#14     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#15     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#16     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#17     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#19     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6825:15)
#20     RecursiveAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:1049:10)
#21     LinterVisitor.visitListLiteral (package:analyzer/src/lint/linter_visitor.dart:438:11)
#22     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6820:49)
#23     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#24     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#25     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#26     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#28     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#29     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#30     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#31     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#32     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#33     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#34     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#35     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#36     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#37     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#38     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#39     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#40     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#41     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#42     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#43     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#44     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#45     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#46     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#47     NodeListImpl....
```

For additional log information, please append the contents of
file://C:\Users\lovel\AppData\Local\Temp\report.txt.
[report.txt](https://github.com/dart-lang/sdk/files/3726872/report.txt)

**Comment by srawlins** [comment]
Thanks for reporting this! This was previously reported at https://github.com/dart-lang/sdk/issues/37879, but we don't have any additional details; can you provide any more details about what you were doing at the time of the crash? Thanks!

**Comment by Tinhorn** [comment]
I was using Flutter to develop an app. I changed something and was waiting
for the hot reload to reflect the changes in the app. There was a compile
error instead and I looked back in the IDE and I saw the error report on
the bottom right

**Comment by parlough** [comment]
Should be fixed by https://github.com/dart-lang/linter/commit/00c8317a3874cc0a1cb0e07597e379fea400306c
