### ISSUE TITLE
Error AndroidStudio when import

### ISSUE THREAD

**Issue by davidacaceres** [dart-lang/sdk#38883]
[report.txt](https://github.com/dart-lang/sdk/files/3727334/report.txt)
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2048x1152`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<void>(Instance of '_OccurrencesVisitor')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ExtractLocalRefactoringImpl._prepareOccurrences (package:analysis_server/src/services/refactoring/extract_local.dart:520:23)
#2      ExtractLocalRefactoringImpl.checkInitialConditions (package:analysis_server/src/services/refactoring/extract_local.dart:96:5)
#3      _RefactoringManager._init (package:analysis_server/src/edit/edit_domain.dart:1196:36)
<asynchronous suspension>
#4      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:982:13)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1500:12)
#9      _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:979:5)
#10     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:857:24)
#11     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:389:16)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#55     _StreamController._add (dart:async/stream_controller.dart:640:7)
#56     _StreamController.add (dart:async/stream_controller.dart:586:5)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:1791:41)
#58     _rootRunUnary (dart:async/zone.dart:1136:13)
#59...
```

For additional log information, please append the contents of
file://D:\Usuarios\dcaceres.SISDEF\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Thanks for the report! This was previously reported at https://github.com/dart-lang/sdk/issues/37220, but it's good to know this is still a problem with Dart 2.5.0; can you give any details into what you are doing at the time of the crash? Trying a refactoring or adding an import? Thanks!

**Comment by davidacaceres** [comment]
I was adding imports

**Comment by srawlins** [comment]
@danrubel has more details with a repro at https://github.com/dart-lang/sdk/issues/39211.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.5.0. Please re-open if you see this crash again.
