### ISSUE TITLE
Dart Analyzer Error 			Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by nne998** [dart-lang/sdk#38909]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553, server version 1.27.3, error: Analysis failed: /Users/tony/Library/Mobile Documents/com~apple~CloudDocs/yunpan/code/flutter_projects/flutter_test3/test/widget_test.dart context: exception_20191016_105720_289
UnimplementedError: FunctionTypedFormalParameterImpl
#0      TypesBuilder._declaration (package:analyzer/src/summary2/types_builder.dart:137:7)
#1      TypesBuilder.build (package:analyzer/src/summary2/types_builder.dart:48:7)
#2      Linker._resolveTypes (package:analyzer/src/summary2/link.dart:252:30)
#3      Linker._buildOutlines (package:analyzer/src/summary2/link.dart:99:5)
#4      Linker.link (package:analyzer/src/summary2/link.dart:83:5)
#5      link (package:analyzer/src/summary2/link.dart:35:10)
#6      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:187:26)
#7      SetMixin.forEach (dart:collection/set.dart:146:30)
#8      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:142:32)
#9      SetMixin.forEach (dart:collection/set.dart:146:30)
#10     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:142:32)
#11     SetMixin.forEach (dart:collection/set.dart:146:30)
#12     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:142:32)
#13     SetMixin.forEach (dart:collection/set.dart:146:30)
#14     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:142:32)
#15     SetMixin.forEach (dart:collection/set.dart:146:30)
#16     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:142:32)
#17     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:239:17)
#18     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#19     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:237:12)
#20     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1446:23)
#21     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1243:30)
#22     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#23     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1232:20)
#24     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1062:33)
#25     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#31     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#38     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#39     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/ms/fxtqvqx51n9dk5gbq2l5fnbr0000gn/T/report.txt.

**Comment by srawlins** [comment]
Hi @nne998 thanks for reporting this issue! Do you know if you were doing anything specific at the time, something with a function-typed paramater (like the `cb` in `void f(int Function() cb) {}`)? Thanks!

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.6.0. Please re-open if you see this crash again.
