### ISSUE TITLE
POST PROBLEMS

### ISSUE THREAD

**Issue by radheyshyams** [dart-lang/sdk#38936]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: F:\Ouctus\flutter_login_app\lib\login_page.dart context: exception_20191017_130419_691
NoSuchMethodError: The getter 'kind' was called on null.
Receiver: null
Tried calling: kind
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Member.kind (package:analyzer/src/dart/element/member.dart:475:40)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:466:40)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:452:7)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:752:7)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8969:49)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6629:13)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:396:31)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6625:49)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7428:12)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#12     GeneralizingAstVisitor.visi

**Comment by srawlins** [comment]
Thanks for reporting this problem! This was previously reported at https://github.com/dart-lang/sdk/issues/38488; please follow along there.
