### ISSUE TITLE
class MyFunction extends void Function may cause dart analysis error

### ISSUE THREAD

**Issue by chengenzhao** [dart-lang/sdk#38948]
Analyzer Feedback from IntelliJ
<img width="838" alt="AFDAECE079CA0A7E4009E81E340CCD89" src="https://user-images.githubusercontent.com/5525436/67026174-dd50ca00-f139-11e9-9491-8c27bdeb5790.png">

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1280x800  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
type 'GenericFunctionTypeImpl' is not a subtype of type 'TypeName'
#0      AstBuilder.handleClassExtends (package:analyzer/src/fasta/ast_builder.dart:2190:14)
#1      Parser.parseClassExtendsOpt (package:front_end/src/fasta/parser/parser.dart:1913:16)
#2      Parser.parseClassHeaderOpt (package:front_end/src/fasta/parser/parser.dart:1803:13)
#3      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1791:13)
#4      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#5      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#6      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#7      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#8      ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#9      ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#10     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#11     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#12     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#13     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#14     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#15     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#16     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#17     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#18     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#19     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#20     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#26     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#27     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#28     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#29     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#30     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#31     new Future.sync (dart:async/future.dart:224:31)
#32     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#38     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#39     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#40     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#41     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#42     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/xj/0q8k884x1fqg69bnwrfnnt0w0000gn/T/report.txt.

**Comment by srawlins** [comment]
Thanks for the excellent reproduction!

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.5; please re-open if you see this in a recent version of Dart/Flutter.
