### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by KevinRen** [dart-lang/sdk#38962]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1920x1080, 1920x1200  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Failed to handle completion domain request: {id: 13161, method: completion.getSuggestionDetails, params: {file: /Users/kevinren/work/syhospital_patient/lib/components/im/message/goEvaluate.dart, id: 1213, label: Function, offset: 401}, clientRequestTime: 1571383447869}
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<void>(Instance of 'SyntacticScopeNamesCollector')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SyntacticScopeNamesCollector.visitGenericTypeAlias (package:analyzer_plugin/src/utilities/change_builder/dart/syntactic_scope.dart:220:23)
#2      GenericTypeAliasImpl.accept (package:analyzer/src/dart/ast/ast.dart:5537:20)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#4      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#5      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#6      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#7      importLibraryElementImpl (package:analyzer_plugin/src/utilities/change_builder/dart/import_library_element.dart:58:25)
#8      DartFileEditBuilderImpl.importLibraryElement (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1273:19)
#9      CompletionDomainHandler.getSuggestionDetails.<anonymous closure> (package:analysis_server/src/domain_completion.dart:235:32)
#10     DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:56:20)
#11     ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#12     DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:53:18)
#13     CompletionDomainHandler.getSuggestionDetails (package:analysis_server/src/domain_completion.dart:234:23)
<asynchronous suspension>
#14     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:279:9)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#20     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1500:12)
#27     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#28     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#29     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#30     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#31     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#40     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#41     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#42     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#49     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#50     _EventSinkWrapper.add (dart:async/stream_...
```

For additional log information, please append the contents of
file:///private/var/folders/x0/4nm89tb9013frjkqmr89w1lc0000gn/T/report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.5.0. Please re-open if you see this crash again.
