### ISSUE TITLE
X64 AoT segfault with bytecode compiler

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#38965]
Link to failure: https://chromium-swarm.appspot.com/task?id=47f5ac100a855510&w=true

Reproduces both in debug and release in AoT, does not reproduce in jit.

AoT stacktrace repro to find offending line Dart code:

```
out/ReleaseX64/dart runtime/tools/dartfuzz/dartfuzz.dart --fp --no-ffi --flat --seed 3281560522 abc.dart
out/ReleaseX64/dart pkg/vm/bin/gen_kernel.dart --platform out/ReleaseX64/vm_platform_strong.dill --aot -o abc.dill abc.dart
out/ReleaseX64/gen_snapshot --snapshot_kind=app-aot-assembly --assembly=abc.S abc.dill
gcc -shared -o abc.so abc.S
out/ReleaseX64/dart_precompiled_runtime abc.so
gdb --args out/ReleaseX64/dart_precompiled_runtime abc.so
```

Minimal example:

```dart
int a = -1;

main() {
  false ? (-0.0 as int) : (++a);
}
```

It needs the conditional, it needs `a` to be negative, it needs a negative double and the cast in the dead branch of the conditional, and `a` should be outside main.

```
        ;; v12 <- LoadStaticField(v14) T{int?}
        ;; Inlined [::.get_a]
0x7fc8fbeb4d5d    488b511f               movq rdx,[rcx+0x1f]     // load the 'boxed double' which is actually a int=-1 encoded as a smi=-2
        ;; v24 <- UnboxedConstant(#1.0) T{_Double}
        ;; Inlined [::.get_a]
0x7fc8fbeb4d61    498b8fe7c80000         movq rcx,[pp+0xc8e7]
0x7fc8fbeb4d68    f20f104107             movsd xmm0,[rcx+0x7]
        ;; v20 <- Unbox(v12 T{_Double}) T{_Double}
        ;; Inlined [::.get_a]
0x7fc8fbeb4d6d    f20f104a07             movsd xmm1,[rdx+0x7]    // segfaults, rdx == 0xfffffffffffffffe, tries to unbox double but no double.
```

Somewhere halfway the compiler passes something looks curious:

```
*** BEGIN CFG
After Inlining
==== file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/abc.dart_::_main
B0[graph]:0 {
      v0 <- Constant(#null) T{Null?}
      v1 <- Constant(#<optimized out>)
      v4 <- Constant(#1) T{_Smi}
      v14 <- Constant(#Field <::.a>: static) T{Field}
}
B1[function entry]:2
    CheckStackOverflow:6(stack=0, loop=0)
    goto:8 B2
B2[join]:4 pred(B1)
    InitStaticField:4(v14)
    v12 <- LoadStaticField(v14) T{int?}          // v12 is Int here
    CheckNull:12(v12 T{_Double}) T{_Double}      // v12 is double from here on.
    v7 <- SmiToDouble(v4) T{_Double}
    v5 <- BinaryDoubleOp(+, v12 T{_Double}, v7) T{_Double}
    StoreStaticField(a, v5)
    Return:16(v0)
*** END CFG
```

It concluded that the getter of `a` returns double, instead of int.

```
*** BEGIN CFG
After ApplyClassIds
==== file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/abc.dart_::_main
B0[graph]:0 {
      v0 <- Constant(#null) T{Null?}
      v1 <- Constant(#<optimized out>)
      v4 <- Constant(#1) T{_Smi}
}
B1[function entry]:2
    CheckStackOverflow:6(stack=0, loop=0)
    goto:8 B2
B2[join]:4 pred(B1)
    v2 <- StaticCall:10( get:a<0> , result_type = T{_Double}) T{_Double}
    CheckNull:12(v2) T{_Double}
    v7 <- SmiToDouble(v4) T{_Double}
    v5 <- BinaryDoubleOp(+, v2, v7) T{_Double}
    StoreStaticField(a, v5)
    Return:16(v0)
*** END CFG
```

Which is constructed from the bytecode:

```
*** BEGIN CFG
Constructed from bytecode
==== file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/abc.dart_::_main
B0[graph]:0
B1[function entry]:2
    CheckStackOverflow:6(stack=0, loop=0)
    goto:8 B2
B2[join]:4 pred(B1)
    t0 <- StaticCall:10( get:a<0> , result_type = T{_Double})  // The bytecode compiler told us that the getter of `a` is Double.
    t0 <- StoreLocal(var2 @-2, t0)
    PushArgument(t0)
    t1 <- Constant(#1)
    PushArgument(t1)
    t2 <- LoadLocal(var2 @-2)
    t3 <- LoadLocal(:t2 @-5)
    CheckNull:12(t3)
    DropTemps(1)
    t0 <- StaticCall:14( +<0> t0, t1, using unchecked entrypoint, recognized_kind = Integer_add, result_type = T{int})
    t0 <- StoreLocal(var1 @-1, t0)
    t1 <- LoadLocal(var1 @-1)
    StoreStaticField(a, t1)
    StoreLocal(var0 @0, t0)
    t0 <- LoadLocal(var0 @0)
    DropTemps(1)
    t0 <- Constant(#null)
    Return:16(t0)
*** END CFG
```

The byte code dumped with `dump_kernel.dart`:

```
main = <No Member>;
 [@vm.bytecode=
BytecodeMetadata {
Bytecode (version: stable)
Main library: file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/abc.dart
Library 'file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/abc.dart'
    name ''
    script 'file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/abc.dart'(source: import-uri 'file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/abc.dart', 57 text chars, 7 line starts)

Class '', script = 'file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/abc.dart'(source: import-uri 'file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/abc.dart', 57 text chars, 7 line starts)

Field 'a', type = dart:core::int, getter = 'get:a', reflectable, static, pos = 4, end-pos = 10
    initializer
Bytecode {
  Entry                0
# source position 4
  CheckStack           0
  DebugCheck
  PushInt              1
# source position 8
  UncheckedDirectCall  CP#0, 1
# source position 4
  ReturnTOS
}
ConstantPool {
  [0] = DirectCall 'dart:core::_IntegerImplementation::unary-', ArgDesc num-args 1, num-type-args 0, names null
  [1] = Reserved
}

    attributes const <dynamic> ['vm.inferred-type.metadata', const <dynamic> [const -1, null, const 3, const 7, null, const 6]]

Function 'main', static, reflectable, debuggable, pos = 13, end-pos = 55
    parameters [] (required: 0)
    return-type dynamic
    attributes const <dynamic> ['vm.inferred-type.metadata', const <dynamic> [const 9, dart:core::_Double, const 4, const 9, null, const 3, const 20, null, const 6]]

Bytecode {
  Entry                3
# source position 13
# scope (pc 2-36 pos 17-55 context-level -1)
  CheckStack           0
# source position 17
  DebugCheck
  Jump                 L1
L1:
# source position 51
  DirectCall           CP#6, 0      // I think this is the corresponding call, no types mentioned here.
  StoreLocal           r2
  PushInt              1
  Push                 r2
# source position 49
  NullCheck            CP#8
  UncheckedDirectCall  CP#9, 2
  StoreLocal           r1
  Push                 r1
# source position 51
  StoreStaticTOS       CP#11
  PopLocal             r0
  Push                 r0
  Drop1
  PushNull
# source position 55
  ReturnTOS
}
ConstantPool {
  [0] = ObjectRef const 0.0
  [1] = DirectCall 'dart:core::_Double::unary-', ArgDesc num-args 1, num-type-args 0, names null
  [2] = Reserved
  [3] = Type dart:core::int
  [4] = ObjectRef ' in type cast'
  [5] = SubtypeTestCache
  [6] = DirectCall 'file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/abc.dart::get:a', ArgDesc num-args 0, num-type-args 0, names null
  [7] = Reserved
  [8] = ObjectRef '+'
  [9] = DirectCall 'dart:core::_IntegerImplementation::+', ArgDesc num-args 2, num-type-args 0, names null
  [10] = Reserved
  [11] = StaticField file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/abc.dart::a (field)
}
```

When reading the bytecode and constructing the IL the type seems to be correctly int in `runtime/vm/compiler/frontend/bytecode_flow_graph_builder.cc:903`.

```
call->ToCString()
0x7ffff47a0c28 "StaticCall:12( get:a<0> )"
call->ComputeType().ToCString()
0x7ffff47a0c80 "T{int?}"
```

However `GetInferredType(pc_)` returns `cid`=50 which is `kDoubleCid`.

Which gets picked up from `inferred_types_attribute_` which is set in `runtime/vm/compiler/frontend/bytecode_flow_graph_builder.cc:2288`.

```c++
  inferred_types_attribute_ ^= BytecodeReader::GetBytecodeAttribute(
      function(), Symbols::vm_inferred_type_metadata());
```

Which probably refers to the following section in the bytecode, which contains `_Double`:

```
Function 'main', static, reflectable, debuggable, pos = 13, end-pos = 55
    parameters [] (required: 0)
    return-type dynamic
    attributes const <dynamic> ['vm.inferred-type.metadata', const <dynamic> [const 9, dart:core::_Double, const 4, const 9, null, const 3, const 20, null, const 6]]
```

Which seems to be emitted by the TFA.

Running in the dart debugger hits an assert `pkg/vm/lib/bytecode/gen_bytecode.dart:1706`:

```
$ out/ReleaseX64/dart --enable-asserts pkg/vm/bin/gen_kernel.dart --platform=out/ReleaseX64/vm_platform_strong.dill --aot -o=abc.dill abc.dart
[--platform=out/ReleaseX64/vm_platform_strong.dill, --aot, -o=abc.dill, abc.dart]
8
TypeLiteralConstant(dart.core::_Double*)
4
Unhandled exception:
'package:vm/bytecode/gen_bytecode.dart': Failed assertion: line 1707 pos 12: 'inferredTypesAttribute.isEmpty ||
        (inferredTypesAttribute[inferredTypesAttribute.length - 3]
                    as IntConstant)
                .value <
            pc': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      BytecodeGenerator._appendInferredType (package:vm/bytecode/gen_bytecode.dart:1707:12)
#3      BytecodeGenerator._genDirectCall (package:vm/bytecode/gen_bytecode.dart:1258:7)
#4      BytecodeGenerator.visitStaticGet (package:vm/bytecode/gen_bytecode.dart:3537:9)
#5      StaticGet.accept (package:kernel/ast.dart:3059:44)
```

It tries to add a type for the same `pc` twice:

```
pc
8
md
InferredType (dart.core::_Double (skip check))
node
MethodInvocationImpl (0.0.{dart.core::double::unary-}())
pc
8
md
InferredType (int?)
node
StaticGet (#lib1::a)
```

**Comment by dcharkes** [comment]
@aartbik can we add `--enable-asserts` when calling `gen_kernel.dart` in the fuzzer. That would have saved me backtracking all the way from a segfault to the frontend.

**Comment by dcharkes** [comment]
@alexmarkov I wrote a fix in https://dart-review.googlesource.com/c/sdk/+/122147, but maybe the check should be some place else, PTAL.

**Comment by aartbik** [comment]
@dcharkes the nightly infrastructure uses "/pkg/vm/tool/precompiler2" so it requires a bit of extra work to get the -enable-asserts as dart option, but it is a good idea!
