### ISSUE TITLE
SocketException: OS Error: Access is denied.

### ISSUE THREAD

**Issue by enhsuld** [dart-lang/sdk#38972]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.6183.87`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IU-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [D:\workspace\HYRD], excluded: [D:\workspace\HYRD\.idea, D:\workspace\HYRD\.dart_tool, D:\workspace\HYRD\.pub, D:\workspace\HYRD\build]}, clientRequestTime: 1571402440420}
SocketException: OS Error: Access is denied.
, errno = 5, port = 0
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:418:31)
#1      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:350:7)
#2      _rootRunBinary (dart:async/zone.dart:1148:13)
#3      _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#4      runZoned.<anonymous closure> (dart:async/zone.dart:1479:21)
#5      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#6      _nullErrorHandler (dart:async/stream_impl.dart:572:16)
#7      _rootRunBinary (dart:async/zone.dart:1144:38)
#8      _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#9      _CustomZone.runBinaryGuarded (dart:async/zone.dart:939:7)
#10     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:355:15)
#11     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373:16)
#12     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:272:7)
#13     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:137:11)
#14     _ForwardingStream._handleError (dart:async/stream_pipe.dart:102:10)
#15     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:168:13)
#16     _rootRunBinary (dart:async/zone.dart:1144:38)
#17     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#18     _CustomZone.runBinaryGuarded (dart:async/zone.dart:939:7)
#19     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:355:15)
#20     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373:16)
#21     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:272:7)
#22     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:768:19)
#23     _StreamController._addError (dart:async/stream_controller.dart:648:7)
#24     _StreamController.addError (dart:async/stream_controller.dart:600:5)
#25     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1352:23)
#26     _rootRunBinary (dart:async/zone.dart:1148:13)
#27     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#28     _CustomZone.runBinaryGuarded (dart:async/zone.dart:939:7)
#29     _CustomZone.bindBinaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:974:33)
#30     _NativeSocket.reportError (dart:io-patch/socket_patch.dart:1101:32)
#31     _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:939:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\suld\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.5.0. Please re-open if you see this crash again.
