### ISSUE TITLE
Analyzer fuzz crash: function declaration with no element

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38991]
```dart
f(bool b) {
  if (b)
    t() {}
}
```

This looks like a regression. Perhaps caused by https://dart-review.googlesource.com/c/sdk/+/121643 @scheglov 

```
Unhandled exception:
NoSuchMethodError: The method 'setCodeRange' was called on null.
Receiver: null
Tried calling: setCodeRange(11, 6)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ResolutionVisitor._setCodeRange (package:analyzer/src/dart/resolver/resolution_visitor.dart:1194:13)
#2      ResolutionVisitor.visitFunctionDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:492:7)
#3      FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4939:49)
#4      FunctionDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4987:27)
#5      RecursiveAstVisitor.visitFunctionDeclarationStatement (package:analyzer/dart/ast/visitor.dart:917:10)
#6      FunctionDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4983:15)
#7      IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5781:21)
#8      RecursiveAstVisitor.visitIfStatement (package:analyzer/dart/ast/visitor.dart:971:10)
#9      IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5776:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7693:20)
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/122281
