### ISSUE TITLE
Analyzer fuzz crash: dynamic member on FFI struct

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38993]
@dcharkes this FFI analysis crashes the dart analyzer:

```dart
import "dart:ffi";

class C extends Struct {
  dynamic x;
}
```

Results in

```
Unhandled exception:
type 'DynamicElementImpl' is not a subtype of type 'ClassElement'
#0      FfiVerifier._validateFieldsInStruct (package:analyzer/src/generated/ffi_verifier.dart:269:42)
#1      FfiVerifier.visitFieldDeclaration (package:analyzer/src/generated/ffi_verifier.dart:100:7)
#2      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4095:49)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7693:20)
#4      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#5      RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#6      FfiVerifier.visitClassDeclaration (package:analyzer/src/generated/ffi_verifier.dart:85:11)
#7      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7693:20)
#9      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#10     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
```

**Comment by dcharkes** [comment]
Thanks for reporting, I'll fix it!
