### ISSUE TITLE
Analyzer fuzz crash: annotated type argument in function type

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38992]
```dart
Function<@A T>() x;
```

Another likely regression

```
Unhandled exception:
Bad state: Found 1 annotation nodes and 0 element annotations
#0      ResolutionVisitor._setElementAnnotations (package:analyzer/src/dart/resolver/resolution_visitor.dart:1257:7)
#1      ResolutionVisitor.visitTypeParameter (package:analyzer/src/dart/resolver/resolution_visitor.dart:911:5)
#2      TypeParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:10288:49)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7693:20)
#4      TypeParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10338:21)
#5      RecursiveAstVisitor.visitTypeParameterList (package:analyzer/dart/ast/visitor.dart:1296:10)
#6      TypeParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10334:49)
#7      ResolutionVisitor.visitGenericFunctionType.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:678:32)
#8      ResolutionVisitor._withNameScope (package:analyzer/src/dart/resolver/resolution_visitor.dart:1245:8)
#9      ResolutionVisitor.visitGenericFunctionType.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:676:9)
#10     ResolutionVisitor._withElementWalker (package:analyzer/src/dart/resolver/resolution_visitor.dart:1234:8)

```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/125527
