### ISSUE TITLE
 Analyzer assertion failure: autocompleting incomplete function definition yields wrong offset info

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#39002]
Repro: `f(^`

Autocomplete at the `^`.

This fails an assertion:

```
Unhandled exception:
server error: {event: server.error, params: {isFatal: false, message: Failed to handle completion domain request: {id: 0, method: completion.getSuggestions, params: {file: /project/bin/test.dart, offset: 2}}, stackTrace: 'package:analyzer_plugin/src/utilities/completion/completion_target.dart': Failed assertion: line 404 pos 12: 'node.offset < offset && offset < node.end': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      CompletionTarget.findFormalParameter (package:analyzer_plugin/src/utilities/completion/completion_target.dart:404:12)
#3      _OpTypeAstVisitor.visitFormalParameterList (package:analyzer_plugin/src/utilities/completion/optype.dart:695:38)
#4      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4558:49)
#5      new OpType.forCompletion (package:analyzer_plugin/src/utilities/completion/optype.dart:152:16)
#6      DartCompletionRequestImpl.opType (package:analysis_server/src/services/completion/dart/completion_manager.dart:390:21)
#7      DartCompletionRequestImpl.includeIdentifiers (package:analysis_server/src/services/completion/dart/completion_manager.dart:372:12)
#8      InheritedReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/inherited_reference_contributor.dart:59:18)
<asynchronous suspension>
#9      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:145:31)
<asynchronous suspension>
#10     CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:121:42)
```

**Comment by bwilkerson** [comment]
This is no longer producing an exception.
