### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by SwissCheese5** [dart-lang/sdk#39013]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6817.14`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IC-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
Internal problem: Unhandled {recordPath != null ? 'Recording saved' : 'Recording'}  in analyzeQuote.
#0      internalProblem (package:front_end/src/fasta/problems.dart:45:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:58:10)
#2      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#3      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1421:21)
#4      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#5      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#6      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#7      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#8      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#9      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#10     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#11     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#12     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4968:14)
#13     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4947:13)
#14     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4674:12)
#15     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4245:14)
#16     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#17     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#18     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#19     Parser.parseLiteralListSuffix (package:front_end/src/fasta/parser/parser.dart:4437:19)
#20     Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4626:12)
#21     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4295:14)
#22     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#23     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#24     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#25     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#26     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#27     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4968:14)
#28     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4947:13)
#29     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4674:12)
#30     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4245:14)
#31     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#32     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#33     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#34     Parser.parseLiteralListSuffix (package:front_end/src/fasta/parser/parser.dart:4437:19)
#35     Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4626:12)
#36     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4295:14)
#37     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#38     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#39     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#40     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#41     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#42     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4968:14)
#43     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4947:13)
#44     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4674:12)
#45     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4245:14)
#46     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#47     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#48     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#49     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#50     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#51     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4968:14)
#52     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4947:13)
#53     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4674:12)
#54     Pars...
```

**Comment by srawlins** [comment]
Hi @SwissCheese5 thanks for opening this issue! We haven't seen this parsing bug before; please let us know if you can reproduce this in any way... But maybe our recent fuzzing work will detect this. CC @MichaelRFairhurst

**Comment by SwissCheese5** [comment]
Couldn't really tell you tbh. It was quite random while typing `recordPath != null ? 'Recording saved' : 'Recording'`
I was not writing it in order, i believe i was editting the if statement last before it happened.

**Comment by srawlins** [comment]
This hasn't been seen again since Dart 2.5.0. Please re-open if you see this crash again on a recent version of Dart.
