### ISSUE TITLE
Analysis fuzz crash: autocomplete member of malformed typedef

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#39021]
```
typedef F=;
g(F.^
```

autocomplete at the ^

```
Unhandled exception:
server error: {event: server.error, params: {isFatal: false, message: Failed to handle completion domain request: {id: 0, method: completion.getSuggestions, params: {file: /project/bin/test.dart, offset: 17}}, stackTrace: NoSuchMethodError: The getter 'returnType' was called on null.
Receiver: null
Tried calling: returnType
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _LocalBestTypeVisitor.declaredGenericTypeAlias (package:analysis_server/src/services/completion/dart/type_member_contributor.dart:187:58)
#2      LocalDeclarationVisitor.visitCompilationUnit.<anonymous closure> (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:135:9)
#3      ListMixin.forEach (dart:collection/list.dart:67:13)
#4      LocalDeclarationVisitor.visitCompilationUnit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:106:23)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#6      LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:218:18)
#7      LocalDeclarationVisitor.visitFunctionDeclaration (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:186:5)
#8      FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4939:49)
#9      LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:218:18)
#10     LocalDeclarationVisitor.visitFunctionExpression (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:192:5)
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/125526
