### ISSUE TITLE
Analyzer fuzz crash: autocomplete in for loop with class name as variable

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#39025]
```dart
class C{
  f() {
   for(C in n()) {
     ^
    }
  }
}
```

```
Unhandled exception:
server error: {event: server.error, params: {isFatal: false, message: Failed to handle completion domain request: {id: 0, method: completion.getSuggestions, params: {file: /project/bin/test.dart, offset: 35}}, stackTrace: type 'ClassElementImpl' is not a subtype of type 'LocalVariableElement' in type cast
#0      _LocalVisitor.declaredLocalVar (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:293:33)
#1      LocalDeclarationVisitor.visitForStatement (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:170:9)
#2      ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4777:49)
#3      LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:218:18)
#4      LocalDeclarationVisitor.visitBlock (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:82:5)
#5      BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#6      LocalDeclarationVisitor.visit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:72:12)
#7      LocalReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:69:17)
<asynchronous suspension>
#8      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:145:31)
<asynchronous suspension>
#9      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:121:42)
<asynchronous suspension>
#10     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:356:5)
```

**Comment by jcollins-g** [comment]
I think I just ran into this crash interactively using the analysis server in Intellij.

## Exception
```
Dart analysis server, SDK version 2.6.0-dev.8.0, server version 1.27.3, error: Failed to handle completion domain request: {id: 13095, method: completion.getSuggestions, params: {file: /Users/jcollins/dart/sdk/sdk/pkg/analyzer/lib/src/dart/resolver/scope.dart, offset: 13406}, clientRequestTime: 1571762026838}
type 'ClassElementImpl' is not a subtype of type 'LocalVariableElement' in type cast
#0      _LocalVisitor.declaredLocalVar (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:293:33)
#1      LocalDeclarationVisitor.visitForStatement (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:170:9)
#2      ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4772:49)
#3      LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:218:18)
#4      LocalDeclarationVisitor.visitBlock (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:82:5)
#5      BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#6      LocalDeclarationVisitor.visit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:72:12)
#7      LocalReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:69:17)
<asynchronous suspension>
#8      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:145:31)
<asynchronous suspension>
#9      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:121:42)
<asynchronous suspension>
#10     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:356:5)
<asynchronous suspension>
#11     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:245:9)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:238:12)
#17     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:335:45)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:331:50)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1500:12)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:330:5)
#25     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#28     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#41     _rootRunUnary (dart:async/zone.dart:1132:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#46     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#47     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#48     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#49     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#50     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#51     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#52...
```

For additional log information, please append the contents of
file:///private/var/folders/w1/ynzyqn915kng3c3psc6b9js0000b33/T/report.txt.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/125525
