### ISSUE TITLE
Parser fuzz crash: value not in range for endLiteralString

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#39035]
```dart
M("${)=
```

```
Unhandled exception:
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:392:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1644:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:5102:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:5027:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4460:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4393:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:4173:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:4145:13)
#9      Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3784:15)
#10     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2497:13)
```

**Comment by devoncarew** [comment]
Note, we may be seeing this crash from user reports as well.

**Comment by jensjoha** [comment]
This crashes CFE as well.
