### ISSUE TITLE
Analyzer fuzz crash: Compiler cannot run without a compiler context

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#39037]
`{@"$6`

I'm assuming this is an analyzer issue?

```
Unhandled exception:
Internal problem: Compiler cannot run without a compiler context.
Tip: Are calls to the compiler wrapped in CompilerContext.runInContext?
#0      CompilerContext.current (package:front_end/src/fasta/compiler_context.dart:113:7)
#1      internalProblem (package:front_end/src/fasta/problems.dart:45:25)
#2      unhandled (package:front_end/src/fasta/problems.dart:58:10)
#3      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#4      unescapeString (package:front_end/src/fasta/quote.dart:138:17)
#5      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1644:22)
#6      ForwardingListener.endLiteralString (package:front_end/src/fasta/parser/forwarding_listener.dart:814:15)
#7      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:5102:14)
#8      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:5027:13)
#9      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4460:14)
#10     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4393:12)
#11     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:4173:13)
#12     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:4145:13)
#13     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:4110:13)
#14     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5523:16)
#15     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5429:12)
#16     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:4015:14)
#17     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3924:20)
#18     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5903:15)
#19     Parser.parseInvalidBlock (package:front_end/src/fasta/parser/parser.dart:5928:13)
#20     Parser.parseInvalidTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:6626:14)
#21     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:511:12)
#22     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#23     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:159:32)
#24     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:154:12)
#25     _File._parse (package:analyzer/src/services/available_declarations.dart:1863:23)
#26     _File.refresh (package:analyzer/src/services/available_declarations.dart:1184:30)
#27     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:691:14)
#28     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:726:16)
#29     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:587:7)
#30     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:281:13)
<asynchronous suspension>
#31     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1906:35)
<asynchronous suspension>
#32     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1860:5)
#33     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#34     AbstractAnalysisTest.createAnalysisServer (file:///usr/local/google/home/mfairhurst/dart-sdk/sdk/pkg/analysis_server/test/analysis_abstract.dart:131:16)
#35     AbstractAnalysisTest.setUp (file:///usr/local/google/home/mfairhurst/dart-sdk/sdk/pkg/analysis_server/test/analysis_abstract.dart:218:14)
#36     AbstractCompletionDomainTest.setUp (file:///usr/local/google/home/mfairhurst/dart-sdk/sdk/pkg/analysis_server/test/domain_completion_util.dart:126:11)
#37     CompletionDomainHandlerListTokenDetailsTest.setUp (file:///usr/local/google/home/mfairhurst/dart-sdk/sdk/pkg/analysis_server/test/domain_completion_test.dart:884:11)
#38     ExhaustiveCompleter.completeAll (file:///usr/local/google/home/mfairhurst/dart-sdk/sdk/pkg/analysis_server/tool/completion_fuzz.dart:15:11)
<asynchronous suspension>
#39     main (file:///usr/local/google/home/mfairhurst/dart-sdk/sdk/pkg/analysis_server/tool/completion_fuzz.dart:10:25)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by jensjoha** [comment]
Yeah, the function in the front_end you're calling ("unescapeString") ultimately tries to report an error which requires a CompilerContext which wasn't setup.
