### ISSUE TITLE
Parser fuzz crash: unimplemented parse in mixin

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#39032]
```dart
mixin{=:
```

```
Unhandled exception:
UnimplementedError: name is an instance of _OperatorName in endClassConstructor
#0      AstBuilder.endClassConstructor (package:analyzer/src/fasta/ast_builder.dart:688:7)
#1      AstBuilder.endMixinConstructor (package:analyzer/src/fasta/ast_builder.dart:1738:5)
#2      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3421:20)
#3      Parser.parseInvalidOperatorDeclaration (package:front_end/src/fasta/parser/parser.dart:6477:19)
#4      Parser.recoverFromInvalidMember (package:front_end/src/fasta/parser/parser.dart:6520:14)
#5      Parser.parseClassOrMixinOrExtensionMemberImpl (package:front_end/src/fasta/parser/parser.dart:3165:16)
#6      Parser.parseClassOrMixinOrExtensionBody (package:front_end/src/fasta/parser/parser.dart:2944:15)
#7      Parser.parseMixin (package:front_end/src/fasta/parser/parser.dart:1973:13)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:611:18)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
```

**Comment by srawlins** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/39230
