### ISSUE TITLE
Parser fuzz crash: isSynthetic called on null in list literal suffix

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#39058]
`{<[](`

```
Unhandled exception:
NoSuchMethodError: The getter 'isSynthetic' was called on null.
Receiver: null
Tried calling: isSynthetic
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Parser.parseLiteralListSuffix (package:front_end/src/fasta/parser/parser.dart:4663:35)
#2      Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4836:12)
#3      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4504:14)
#4      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4393:12)
#5      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:4173:13)
#6      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:4145:13)
#7      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:4110:13)
#8      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5523:16)
#9      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5429:12)
#10     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:4015:14)

**Comment by MichaelRFairhurst** [comment]
Also failed assertion:

```
Unhandled exception:
'package:front_end/src/fasta/parser/parser.dart': Failed assertion: line 4627 pos 12: 'optional('[', token) || optional('[]', token)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      Parser.parseLiteralListSuffix (package:front_end/src/fasta/parser/parser.dart:4627:12)
#3      Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4836:12)
#4      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4504:14)
#5      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4393:12)
#6      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:4173:13)
#7      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:4145:13)
#8      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:4110:13)
#9      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5523:16)
#10     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5429:12)
```
