### ISSUE TITLE
Parser fuzz assertion failure: optional('}') is not true

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#39060]
`{s A<}>`

```
Unhandled exception:
'package:front_end/src/fasta/parser/parser.dart': Failed assertion: line 5915 pos 12: 'optional('}', token)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5915:12)
#3      Parser.parseInvalidBlock (package:front_end/src/fasta/parser/parser.dart:5928:13)
#4      Parser.parseInvalidTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:6626:14)
#5      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:511:12)
#6      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#7      ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:159:32)
#8      ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:154:12)
#9      _File._parse (package:analyzer/src/services/available_declarations.dart:1863:23)
#10     _File.refresh (package:analyzer/src/services/available_declarations.dart:1184:30)
```

**Comment by jensjoha** [comment]
A more standalone reproduction:
```
main() {
  {s A<}>
}
```

**Comment by jensjoha** [comment]
https://dart-review.googlesource.com/c/sdk/+/122864/
