### ISSUE TITLE
RangeError: Value not in range: 1 from AstBuilder.endLiteralString / unescapeString, 2.5.0-edge.1ef83b86ae63

### ISSUE THREAD

**Issue by right7ctrl** [dart-lang/sdk#39092]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.5728.98`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IC-192.5728.98, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 2560x1440  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:392:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1415:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4968:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4947:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4674:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4245:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#18     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#19     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5315:16)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3726:14)
#21     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#22     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#23     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3269:15)
#24     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#25     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#26     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#27     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#28     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#29     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#30     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#31     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#32     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#33     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#34     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#35     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#36     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#37     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#38     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#39     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#40     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#41     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#42     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#43     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _runZoned (dart:async/zone.dart:1516:10)
#47     runZoned (dart:async/zone.dart:1463:12)
#48     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#49     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#50     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#51     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#52     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#53     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fas...
```

For additional log information, please append the contents of
file:///private/var/folders/kg/0pbfvm290d30vtsm5p3k8s7h0000gn/T/report.txt.

**Comment by devoncarew** [comment]
cc @jensjoha, @johnniwinther for additional triage

**Comment by jensjoha** [comment]
Probably related to https://github.com/dart-lang/sdk/issues/39035.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.5.0; please re-open if you see this in a recent version of Dart/Flutter.
