### ISSUE TITLE
Bad state: No element from _Visitor.visitInstanceCreationExpression / LinterVisitor._runSubscriptions, 2.5.0-edge.1ef83b86ae

### ISSUE THREAD

**Issue by HiroyukTamura** [dart-lang/sdk#39098]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ExpressionFunctionBodyImpl in FunctionExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in AssignmentExpressionImpl in ExpressionStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      ListMixin.first (dart:collection/list.dart:76:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#7      ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#8      RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#9      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.da

**Comment by devoncarew** [comment]
Ah, this is on the stack trace:

```
package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52
```

cc @pq

**Comment by pq** [comment]
This one was fixed w/ https://github.com/dart-lang/linter/commit/00c8317a3874cc0a1cb0e07597e379fea400306c and newer SDKs should be OK.

Sorry for the inconvenience @HiroyukTamura and thanks for the report!
