### ISSUE TITLE
allocation sinking rematerialization does not treat unboxed double fields correctly

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#39112]
It should ensure mutable box by cloning a value being stored into a field in `DeferredObject::Fill`. 

Reproduction:

```dart
import 'package:expect/expect.dart';

const magicDouble = 42.0;

class C {
  double d = magicDouble;
}

class NoopSink {
  void leak(C c) { }
}



class RealSink {
  static C o;
  void leak(C c) {
    o = c;
  }
}

void foo(sink) {
  sink.leak(C());
}

void main(List<String> args) {
  var c = C();
  for (var i = 0; i < 10000; i++)
    c.d = 2.0;

  for (var i = 0; i < 10000; i++) {
    foo(NoopSink());
  }

  foo(RealSink());
  RealSink.o.d += 1234.0;
  final TWO = args.length > 1024 ? "~" : 2;
  Expect.equals(double.parse("4${TWO}.0"), magicDouble);
}
```

```console
$ dart --packages=$HOME/src/dart/sdk/.packages --deterministic test.dart
Unhandled exception:
Expect.equals(expected: <42.0>, actual: <1276.0>) fails.
#0      Expect._fail (package:expect/expect.dart:665:5)
#1      Expect.equals (package:expect/expect.dart:126:5)
#2      main (file:///Users/vegorov/test.dart:38:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by sjindel-google** [comment]
@mkustermann this is not the same but related to the issue we were discussing earlier.

That issue was due to the fact that `FLAG_unbox_numeric_fields` wasn't respected by the interpreter, and was accidentally set to `false` by default when removing DBC code.
