### ISSUE TITLE
NPE from FixProcessor._addFix_createGetterm, 2.6.0-edge.f020ce5d23

### ISSUE THREAD

**Issue by ReniDelonzek** [dart-lang/sdk#39130]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.f020ce5d23a50c05b10c372d99a3f7a878420c78`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.f020ce5d23a50c05b10c372d99a3f7a878420c78, server version 1.27.3, FATAL error: Failed to handle request: {id: 16131, method: edit.getFixes, params: {file: /Users/reni/Downloads/Projetos/UniPrint/uniprint/lib/src/models/ArquivoImpressao.dart, offset: 431}, clientRequestTime: 1572072779149}
NoSuchMethodError: The getter 'node' was called on null.
Receiver: null
Tried calling: node
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      FixProcessor._addFix_createGetter (package:analysis_server/src/services/correction/fix_internal.dart:2172:33)
<asynchronous suspension>
#2      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:468:13)
<asynchronous suspension>
#3      DartFixContributor._computeFixAllFixes (package:analysis_server/src/services/correction/fix_internal.dart:111:53)
<asynchronous suspension>
#4      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:37)
<asynchronous suspension>
#5      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:656:46)
<asynchronous suspension>
#6      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:763:14)
<asynchronous suspension>
#7      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:283:32)
<asynchronous suspension>
#8      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:387:9)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:335:45)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:331:50)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:330:5)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#52     _StreamController._add (dart:async/stream_controller.dart:640:7)
#53     _Strea...
```

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.6.0. Please re-open if you see this crash again.
