### ISSUE TITLE
Dart Analyzer Error, Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by AnthonyNTK** [dart-lang/sdk#39135]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.1bd6e20d769bf7d75a2dc8768bfbe4a2e2948977`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1080x1920`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.1bd6e20d769bf7d75a2dc8768bfbe4a2e2948977, server version 1.27.3, error: Analysis failed: C:\Users\UU\AndroidStudioProjects\flutter_linkarise\lib\screens\widgets\bottom_navy_bar.dart context: exception_20191028_003433_545
type 'DefaultParameterElementImpl' is not a subtype of type 'FieldFormalParameterElementImpl'
#0      ResolutionVisitor.visitFieldFormalParameter (package:analyzer/src/dart/resolver/resolution_visitor.dart:431:7)
#1      FieldFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:4130:49)
#2      ResolutionVisitor.visitDefaultFormalParameter (package:analyzer/src/dart/resolver/resolution_visitor.dart:345:21)
#3      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3008:15)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7516:20)
#5      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4458:17)
#6      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:887:10)
#7      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4454:49)
#8      ResolutionVisitor.visitFunctionDeclaration.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:519:36)
#9      ResolutionVisitor._withNameScope (package:analyzer/src/dart/resolver/resolution_visitor.dart:1186:8)
#10     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:512:11)
#11     ResolutionVisitor._withElementWalker (package:analyzer/src/dart/resolver/resolution_visitor.dart:1175:8)
#12     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:507:7)
#13     ResolutionVisitor._withElementHolder (package:analyzer/src/dart/resolver/resolution_visitor.dart:1164:8)
#14     ResolutionVisitor.visitFunctionDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:506:5)
#15     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4831:49)
#16     FunctionDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4879:27)
#17     RecursiveAstVisitor.visitFunctionDeclarationStatement (package:analyzer/dart/ast/visitor.dart:917:10)
#18     FunctionDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4875:15)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7516:20)
#20     ResolutionVisitor.visitBlock (package:analyzer/src/dart/resolver/resolution_visitor.dart:149:18)
#21     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1073:49)
#22     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1032:13)
#23     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#24     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1028:49)
#25     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:531:31)
#26     ResolutionVisitor._withElementWalker (package:analyzer/src/dart/resolver/resolution_visitor.dart:1175:8)
#27     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:530:13)
#28     ResolutionVisitor._withNameScope (package:analyzer/src/dart/resolver/resolution_visitor.dart:1186:8)
#29     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:512:11)
#30     ResolutionVisitor._withElementWalker (package:analyzer/src/dart/resolver/resolution_visitor.dart:1175:8)
#31     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:507:7)
#32     ResolutionVisitor._withElementHolder (package:analyzer/src/dart/resolver/resolution_visitor.dart:1164:8)
#33     ResolutionVisitor.visitFunctionDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:506:5)
#34     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4831:49)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7516:20)
#36     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2111:21)
#37     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#38     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2090:49)
#39     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:645:10)
#40     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:152:7)
#41     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#42     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:151:11)
#43     LibraryAnalyzer....
```

For additional log information, please append the contents of
file://C:\Users\UU\AppData\Local\Temp\report.txt.

**Comment by AnthonyNTK** [comment]
Report.txt

```
Dart analysis server, SDK version 2.6.0-edge.1bd6e20d769bf7d75a2dc8768bfbe4a2e2948977, server version 1.27.3, error: Analysis failed: C:\Users\UU\AndroidStudioProjects\flutter_linkarise\lib\screens\widgets\bottom_navy_bar.dart context: exception_20191028_003433_545
type 'DefaultParameterElementImpl' is not a subtype of type 'FieldFormalParameterElementImpl'
#0      ResolutionVisitor.visitFieldFormalParameter (package:analyzer/src/dart/resolver/resolution_visitor.dart:431:7)
#1      FieldFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:4130:49)
#2      ResolutionVisitor.visitDefaultFormalParameter (package:analyzer/src/dart/resolver/resolution_visitor.dart:345:21)
#3      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3008:15)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7516:20)
#5      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4458:17)
#6      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:887:10)
#7      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4454:49)
#8      ResolutionVisitor.visitFunctionDeclaration.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:519:36)
#9      ResolutionVisitor._withNameScope (package:analyzer/src/dart/resolver/resolution_visitor.dart:1186:8)
#10     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:512:11)
#11     ResolutionVisitor._withElementWalker (package:analyzer/src/dart/resolver/resolution_visitor.dart:1175:8)
#12     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:507:7)
#13     ResolutionVisitor._withElementHolder (package:analyzer/src/dart/resolver/resolution_visitor.dart:1164:8)
#14     ResolutionVisitor.visitFunctionDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:506:5)
#15     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4831:49)
#16     FunctionDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4879:27)
#17     RecursiveAstVisitor.visitFunctionDeclarationStatement (package:analyzer/dart/ast/visitor.dart:917:10)
#18     FunctionDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4875:15)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7516:20)
#20     ResolutionVisitor.visitBlock (package:analyzer/src/dart/resolver/resolution_visitor.dart:149:18)
#21     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1073:49)
#22     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1032:13)
#23     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#24     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1028:49)
#25     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:531:31)
#26     ResolutionVisitor._withElementWalker (package:analyzer/src/dart/resolver/resolution_visitor.dart:1175:8)
#27     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:530:13)
#28     ResolutionVisitor._withNameScope (package:analyzer/src/dart/resolver/resolution_visitor.dart:1186:8)
#29     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:512:11)
#30     ResolutionVisitor._withElementWalker (package:analyzer/src/dart/resolver/resolution_visitor.dart:1175:8)
#31     ResolutionVisitor.visitFunctionDeclaration.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:507:7)
#32     ResolutionVisitor._withElementHolder (package:analyzer/src/dart/resolver/resolution_visitor.dart:1164:8)
#33     ResolutionVisitor.visitFunctionDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:506:5)
#34     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4831:49)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7516:20)
#36     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2111:21)
#37     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#38     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2090:49)
#39     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:645:10)
#40     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:152:7)
#41     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#42     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:151:11)
#43     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:114:14)
#44     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#45     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:113:43)
#46     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1261:63)
#47     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#48     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1237:20)
#49     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1047:17)
<asynchronous suspension>
#50     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1926:24)
<asynchronous suspension>
#51     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1860:5)
#52     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#53     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#54     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#55     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:575:21)
#56     _rootRun (dart:async/zone.dart:1124:13)
#57     _CustomZone.run (dart:async/zone.dart:1021:19)
#58     _runZoned (dart:async/zone.dart:1516:10)
#59     runZoned (dart:async/zone.dart:1463:12)
#60     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:694:12)
#61     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:573:7)
#62     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#63     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#64     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#65     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#66     new Future.sync (dart:async/future.dart:222:31)
#67     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#68     _rootRun (dart:async/zone.dart:1124:13)
#69     _CustomZone.run (dart:async/zone.dart:1021:19)
#70     _runZoned (dart:async/zone.dart:1516:10)
#71     runZoned (dart:async/zone.dart:1463:12)
#72     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#73     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:142:56)
#74     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#75     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#76     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#77     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#78     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#79     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
1572194071856 <= {"event":"analysis.implemented","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","classes":[],"members":[]}}
1572194072072 => {"id":"22903","method":"analysis.updateContent","params":{"files":{"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart":{"type":"add"
1572194072080 <= {"id":"22903","result":{}}
1572194072136 => {"id":"22904","method":"edit.getAssists","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","offset":92,"length":0
1572194072201 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","errors":[{"severity":"ERROR","type"
1572194072203 <= {"id":"22904","result":{"assists":[]}}
1572194072207 <= {"event":"analysis.highlights","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","regions":[{"type":"DIRECTIVE","
1572194072209 <= {"event":"analysis.navigation","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","regions":[{"offset":7,"length":
1572194072210 <= {"event":"analysis.outline","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","kind":"LIBRARY","outline":{"elemen
1572194072211 <= {"event":"analysis.overrides","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","overrides":[{"offset":2271,"leng
1572194072213 <= {"event":"flutter.outline","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","outline":{"kind":"DART_ELEMENT","of
1572194072219 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1462,"uri":"package:flutter_linkarise/screens/widgets/bottom_navy_bar.dart","items":[{"label":"List","de
1572194072221 <= {"event":"analysis.implemented","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","classes":[],"members":[]}}
1572194072507 => {"id":"22905","method":"analysis.updateContent","params":{"files":{"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart":{"type":"add"
1572194072513 <= {"id":"22905","result":{}}
1572194072623 => {"id":"22906","method":"edit.getAssists","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","offset":91,"length":0
1572194072658 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","errors":[{"severity":"INFO","type":
1572194072660 <= {"id":"22906","result":{"assists":[]}}
1572194072661 <= {"event":"analysis.highlights","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","regions":[{"type":"DIRECTIVE","
1572194072663 <= {"event":"analysis.navigation","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","regions":[{"offset":7,"length":
1572194072664 <= {"event":"analysis.outline","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","kind":"LIBRARY","outline":{"elemen
1572194072665 <= {"event":"analysis.overrides","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","overrides":[{"offset":2270,"leng
1572194072668 <= {"event":"flutter.outline","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","outline":{"kind":"DART_ELEMENT","of
1572194072672 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1462,"uri":"package:flutter_linkarise/screens/widgets/bottom_navy_bar.dart","items":[{"label":"List","de
1572194072672 <= {"event":"analysis.implemented","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","classes":[],"members":[]}}
1572194072962 => {"id":"22907","method":"analysis.updateContent","params":{"files":{"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart":{"type":"add"
1572194072971 <= {"id":"22907","result":{}}
1572194073343 => {"id":"22908","method":"analysis.updateContent","params":{"files":{"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart":{"type":"add"
1572194073407 => {"id":"22909","method":"edit.getAssists","params":{"file":"C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart","offset":578,"length":
1572194073660 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: C:\\Users\\UU\\AndroidStudioProjects\\flutter_linkarise\\lib\\screens\\widgets\\bottom_navy_bar.dart cont
```

```

**Comment by devoncarew** [comment]
dup of https://github.com/dart-lang/sdk/issues/39099
