### ISSUE TITLE
?

### ISSUE THREAD

**Issue by linyu92** [dart-lang/sdk#39134]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: Failed to handle request: {id: 213, method: edit.getFixes, params: {file: /Users/levi/Desktop/Fullter/flutter_live_room/FlutterLiveRoom/example/lib/components/creating_component.dart, offset: 4253}, clientRequestTime: 1572151931600}
NoSuchMethodError: The getter 'kind' was called on null.
Receiver: null
Tried calling: kind
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Member.kind (package:analyzer/src/dart/element/member.dart:475:40)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:466:40)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:452:7)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:752:7)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8969:49)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6629:13)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:396:31)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6625:49)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7428:12)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#12     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#13     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#14     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#15     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#16     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#18     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#19     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#20     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140:45)
#21     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#22     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#23     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#24     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#25     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#26     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#27     GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:374:7)
#28     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#29     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8638:18)
#30     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#31     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#32     GeneralizingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:486:51)
#33     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8634:49)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#35     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#36     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#37     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#38     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:162:31)
#39     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#40     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#41     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#42     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#43     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:165:55)
#44     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#45     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7110:12)
#46     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#47     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#48     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#49     GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:183:43)
#50     GeneralizingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:416:55)
#51     MethodDeclaratio...
```

For additional log information, please append the contents of
file:///private/var/folders/yj/zys1d67x1jdf1xbgt4q31bj40000gn/T/report1.txt.

**Comment by devoncarew** [comment]
dup of https://github.com/dart-lang/sdk/issues/39133
