### ISSUE TITLE
we should only pass absolute file paths to `flutter.setSubscriptions`

### ISSUE THREAD

**Issue by uzhvij** [dart-lang/sdk#39148]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Invalid argument(s): Only absolute paths are supported: lib\AbstractDataProvider.dart
#0      AnalysisDriver._throwIfNotAbsolutePath (package:analyzer/src/dart/analysis/driver.dart:1698:7)
#1      AnalysisDriver.getResult (package:analyzer/src/dart/analysis/driver.dart:783:5)
#2      AbstractAnalysisServer.getResolvedUnit (package:analysis_server/src/analysis_server_abstract.dart:284:10)
#3      AnalysisServer.setFlutterSubscriptions (package:analysis_server/src/analysis_server.dart:537:9)
#4      FlutterDomainHandler.setSubscriptions (package:analysis_server/src/flutter/flutter_domain.dart:117:12)
#5      FlutterDomainHandler.handleRequest (package:analysis_server/src/flutter/flutter_domain.dart:75:16)
#6      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#8      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1500:12)
#13     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#14     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#16     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#17     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#26     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#27     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#28     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#35     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#36     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#37     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#38     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#39     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#40     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#41     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#43     _rootRunUnary (dart:async/zone.dart:1132:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#48     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#49     _StreamController._add (dart:async/stream_controller.dart:640:7)
#50     _StreamController.add (dart:async/stream_controller.dart:586:5)
#51     _Socket._onData (dart:io-patch/socket_patch.dart:1791:41)
#52     _rootRunUnary (dart:async/zone.dart:1136:13)
#53     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#57     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#58     _StreamController._add (dart:async/stream_controller.dart:640:7)
#59     _StreamController.add (dart:async/stream_controller.dart:586:5)
#60     ne...
```

For additional log information, please append the contents of
file://C:\Users\Alex\AppData\Local\Temp\report.txt.

**Comment by devoncarew** [comment]
Interesting; re:

```
Invalid argument(s): Only absolute paths are supported: lib\AbstractDataProvider.dart
#0      AnalysisDriver._throwIfNotAbsolutePath (package:analyzer/src/dart/analysis/driver.dart:1698:7)
```

@scheglov - does this mean that we're passing a non-absolute path into `flutter.setSubscriptions` from the IntelliJ plugin?

**Comment by scheglov** [comment]
Yes, it looks to me as well that we pass non-absolute path(s) to DAS.

**Comment by devoncarew** [comment]
@mit-mit - can you re-enable the move bot for this repo?

**Comment by devoncarew** [comment]
> Yes, it looks to me as well that we pass non-absolute path(s) to DAS.

OK; cc @jacob314. From looking at the code, we're calling VirtualFile.getCanonicalPath(). I don't see any absolute related APIs. The canonical API may generally return absolute paths except in some circumstances (like light virtual files?). We should either switch to a different API, or guard against sending in non-absolute paths for the outlier files. 

cc @alexander-doroshko for clarification about how to get an absoluate path from a VirtualFile.

**Comment by alexander-doroshko** [comment]
This may be a temporary in-memory file, HTTP-remote file, file inside a zip, etc. Analysis Server can work only with local files, so I think you should check for `isInLocalFileSystem()` and not send file path to the server if it's not. In Dart plugin we do it in `DartAnalysisServerService#isLocalAnalyzableFile()`.

**Comment by alexander-doroshko** [comment]
@devoncarew Why `area-intellij`? I suppose the request comes from the Flutter plugin.

**Comment by devoncarew** [comment]
Yeah, that's just a temporary marker to get this issue off the un-triaged queue. This issue should be moved to the flutter/flutter-intellij repo; we hope to re-enable the bot to help us do that soon.

**Comment by alexander-doroshko** [comment]
@devoncarew Move to flutter-intellij?
