### ISSUE TITLE
Function typedef in type test causes runtime error when running dart2js compiled output

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#39150]
Repro:
Compile this code with dart2js and run.

```dart
import 'dart:async';

typedef F = Future<Null> Function();

void main() {
  print(f is F);
}

FutureOr<Null> f() async => null;
```

The is check causes the following runtime error:

```
TypeError: Cannot use 'in' operator to search for '$isFuture' in undefined
    at Object._isSubtype (/Users/nshahan/code/test_files/out.js:1111:37)
    at Object._isFunctionSubtype (/Users/nshahan/code/test_files/out.js:1137:14)
    at Object.functionTypeTest (/Users/nshahan/code/test_files/out.js:810:16)
    at Object.main (/Users/nshahan/code/test_files/out.js:1930:28)
    at /Users/nshahan/code/test_files/out.js:2908:9
    at /Users/nshahan/code/test_files/out.js:2888:7
    at dartProgram (/Users/nshahan/code/test_files/out.js:2903:5)
    at Object.<anonymous> (/Users/nshahan/code/test_files/out.js:2910:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

I see the same failure in the latest stable and bleeding edge.

**Comment by sigmundch** [comment]
this is thankgfully working better in the new RTI at this time.

/cc @rakudrama - I wouldn't try to fix this in the old RTI, but just wanted to put this on your radar in case it becomes an issue when implementing the is-test optimizations

**Comment by joshualitt** [comment]
Closing because this is not an issue in the new rti.
