### ISSUE TITLE
NPE in LibraryImportScope._createImportedNamespaces, 2.7.0-edge.6354b0b97d

### ISSUE THREAD

**Issue by tieorange** [dart-lang/sdk#39162]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.7.0-edge.6354b0b97dced6c0cdee8f22009b4351f0095d75`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050, 2560x1440  Retina`

## Exception
```
Dart analysis server, SDK version 2.7.0-edge.6354b0b97dced6c0cdee8f22009b4351f0095d75, server version 1.27.3, error: Analysis failed: /Users/tieorange/Documents/FlutterProjects/tecash/test/widget_test.dart context: exception_20191029_140326_152
NoSuchMethodError: The getter 'imports' was called on null.
Receiver: null
Tried calling: imports
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      LibraryImportScope._createImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:509:52)
#2      new LibraryImportScope (package:analyzer/src/dart/resolver/scope.dart:403:5)
#3      new LibraryScope (package:analyzer/src/dart/resolver/scope.dart:619:19)
#4      LibraryBuilder.buildElement (package:analyzer/src/summary2/library_builder.dart:212:13)
#5      Linker._computeLibraryScopes (package:analyzer/src/summary2/link.dart:170:15)
#6      Linker._buildOutlines (package:analyzer/src/summary2/link.dart:97:5)
#7      Linker.link (package:analyzer/src/summary2/link.dart:83:5)
#8      link (package:analyzer/src/summary2/link.dart:35:10)
#9      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:183:26)
#10     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:235:17)
#11     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#12     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:233:12)
#13     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:84:5)
#14     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1439:29)
#15     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:30)
#16     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#17     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1237:20)
#18     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1067:33)
<asynchronous suspension>
#19     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1926:24)
<asynchronous suspension>
#20     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1860:5)
#21     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#22     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#23     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#24     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:575:21)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:694:12)
#30     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:573:7)
#31     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#32     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#33     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#34     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#35     new Future.sync (dart:async/future.dart:222:31)
#36     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#42     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:142:56)
#43     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#44     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#46     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/h9/pxr_mp395_jdg964xrdx8jlw0000gn/T/report.txt.

**Comment by scheglov** [comment]
@tieorange There is an exception dump in `exception_20191029_140326_152` in `~/.dartServer/.analysis-driver` on your computer. Could you please send it to scheglov@google.com? It might have information necessary to reproduce and fix the issue.

**Comment by Rodsevich** [comment]
Same error here while trying to
```dart
var errors = await lib.session.getErrors(p.normalize(p.absolute(path)));
```
How do I find out the exception dump location?

**Comment by scheglov** [comment]
@Rodsevich if you run analyzer programmatically, then you know what codebase you analyze. If you could send me this codebase (which I of course will not use for anything other than reproducing the issue) and the analysis code, then I would be able to reproduce the issue and fix it.
