### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by ChanakaWeerasinghe** [dart-lang/sdk#39179]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.5728.98`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IU-192.5728.98, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: Failed to handle request: {id: 3874, method: edit.getFixes, params: {file: /Users/chanaka/my_app/lib/lib/api/payments_api.dart, offset: 32782}, clientRequestTime: 1572426473557}
Invalid argument(s): Element (ClassElementImpl) class PaymentsApi is not defined in this library.
#0      ResolvedLibraryResultImpl.getElementDeclaration.<anonymous closure> (package:analyzer/src/dart/analysis/results.dart:185:9)
#1      ListMixin.firstWhere (dart:collection/list.dart:143:38)
#2      ResolvedLibraryResultImpl.getElementDeclaration (package:analyzer/src/dart/analysis/results.dart:182:28)
#3      AnalysisSessionHelper.getElementDeclaration (package:analyzer/src/dart/analysis/session_helper.dart:42:28)
<asynchronous suspension>
#4      FixProcessor._addFix_createField (package:analysis_server/src/services/correction/fix_internal.dart:1856:29)
<asynchronous suspension>
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:477:13)
<asynchronous suspension>
#6      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#7      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:651:46)
<asynchronous suspension>
#8      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:757:14)
<asynchronous suspension>
#9      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:280:32)
<asynchronous suspension>
#10     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:383:9)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1500:12)
#18     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#19     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#22     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#30     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#31     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#32     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#33     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#34     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#35     _rootRunUnary (dart:async/zone.dart:1132:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#40     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#41     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#42     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#43     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#44     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#45     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#46     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#48     _rootRunUnary (dart:async/zone.dart:1132:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#52     _BufferingStreamSubscription._add (dart:asy...
```

For additional log information, please append the contents of
file:///private/var/folders/q5/sgvybppx15s4qqvb23q7qcx80000gn/T/report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.5.0. Please re-open if you see this crash again.
