### ISSUE TITLE
Type Variables error

### ISSUE THREAD

**Issue by davidsowerby** [dart-lang/sdk#39182]
The Analyzer failure and feedback below appeared at the same time as an error (the error caused by my lack of understanding - no problem with the error itself):

```
Compiler message:
lib/common/data.dart:55:88: Error: Type variables can't be used as constants.
  ModelConnector({@required this.binding, this.converter =  const PassThroughConnector<VIEW>() as ModelViewConverter<MODEL, VIEW>});
                                                                                       ^^^^
lib/common/data.dart:55:96: Error: Constant evaluation error:
  ModelConnector({@required this.binding, this.converter =  const PassThroughConnector<VIEW>() as ModelViewConverter<MODEL, VIEW>});
```

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-65-generic, screens 1920x1080, 1600x900`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553, server version 1.27.3, error: Analysis failed: /home/david/git/club.kayman/flutter/lib/common/data.dart context: exception_20191030_164007_885
NoSuchMethodError: The getter 'isDartCoreNull' was called on null.
Receiver: null
Tried calling: isDartCoreNull
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Dart2TypeSystem.isSubtypeOf (package:analyzer/src/generated/type_system.dart:600:12)
#2      Dart2TypeSystem._isInterfaceSubtypeOf (package:analyzer/src/generated/type_system.dart:985:14)
#3      Dart2TypeSystem._isInterfaceSubtypeOf (package:analyzer/src/generated/type_system.dart:1007:9)
#4      Dart2TypeSystem.isSubtypeOf (package:analyzer/src/generated/type_system.dart:718:14)
#5      DartObjectImpl.castToType (package:analyzer/src/dart/constant/value.dart:252:21)
#6      DartObjectComputer.castToType (package:analyzer/src/dart/constant/evaluation.dart:1765:27)
#7      ConstantVisitor.visitAsExpression (package:analyzer/src/dart/constant/evaluation.dart:1034:34)
#8      AsExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:458:49)
#9      ConstantEvaluationEngine.computeConstantValue (package:analyzer/src/dart/constant/evaluation.dart:170:28)
#10     _ConstantWalker.evaluate (package:analyzer/src/dart/constant/compute.dart:74:22)
#11     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:108:13)
#12     DependencyWalker.walk (package:analyzer/src/summary/link.dart:127:18)
#13     computeConstants (package:analyzer/src/dart/constant/compute.dart:35:41)
#14     LibraryAnalyzer._computeConstants (package:analyzer/src/dart/analysis/library_analyzer.dart:245:5)
#15     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:158:5)
#16     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:113:14)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:112:43)
#19     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1256:63)
#20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#21     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1232:20)
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1062:33)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#29     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#37     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///tmp/report1.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.6.0. Please re-open if you see this crash again.
