### ISSUE TITLE
Crash in LanguageModel.load while editing in IntelliJ

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#39186]
I got this analyzer crash while editing the Flutter repo. This may be a result of changing git branches in the Flutter repo, which updates the Dart SDK while IntelliJ is running the analyzer.

## Version information

- `IDEA IC-192.7142.36`
- `2.7.0-edge.d3a5b8235557ea72b2e69c5647d512fd2cec3fbd`
- `IC-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Linux(amd64) v4.19.67-2rodete2-amd64, screens 3840x2160, 3840x2160`

Flutter version info (in case that helps):
```
Flutter 1.10.15-pre.343 • channel disabled_inkwell • git@github.com:gspencergoog/flutter.git
Framework • revision 8cd4743a9b (7 minutes ago) • 2019-10-30 13:44:17 -0700
Engine • revision 5051bef17b
Tools • Dart 2.6.0 (build 2.6.0-dev.8.2 d3a5b82355)
```

## Exception
```
Dart analysis server, SDK version 2.7.0-edge.0b96f9f9ae610c354e7dc2df51455e5404178b08, server version 1.27.4, FATAL error: Invalid argument(s): Failed to load dynamic library (/usr/local/google/home/gspencer/code/flutter/bin/cache/dart-sdk/bin/snapshots/libtensorflowlite_c-linux64.so: cannot open shared object file: No such file or directory)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:10:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:19:12)
#2      tflitelib.<anonymous closure> (package:tflite_native/src/bindings/dlib.dart:55:25)
#3      tflitelib (package:tflite_native/src/bindings/dlib.dart:56:2)
#4      tflitelib (package:tflite_native/src/bindings/dlib.dart:40:16)
#5      TFL_NewModelFromFile (package:tflite_native/src/bindings/model.dart:21:72)
#6      TFL_NewModelFromFile (package:tflite_native/src/bindings/model.dart:21:49)
#7      new Model.fromFile (package:tflite_native/src/model.dart:26:19)
#8      new Interpreter.fromFile (package:tflite_native/src/interpreter.dart:35:25)
#9      new LanguageModel.load (package:analysis_server/src/services/completion/dart/language_model.dart:35:25)
#10     entrypoint.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_ranking.dart:36:31)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#15     _StreamController._add (dart:async/stream_controller.dart:640:7)
#16     _StreamController.add (dart:async/stream_controller.dart:586:5)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## Log File
<details>
<pre>
```
1572467964907 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":861,"uri":"dart:_http","items":[{"label":"HttpOverrides","declaringLibraryUri":"dart:_http","element":{"
1572467964926 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2046,"uri":"dart:core","items":[{"label":"TypeError","declaringLibraryUri":"dart:core","element":{"kind"
1572467965451 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4,"uri":"dart:ui","items":[{"label":"TextBaseline","declaringLibraryUri":"dart:ui","element":{"kind":"EN
1572467965513 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2047,"uri":"dart:convert","items":[{"label":"Codec","declaringLibraryUri":"dart:convert","element":{"kin
1572467965742 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2029,"uri":"dart:math","items":[{"label":"atan2","declaringLibraryUri":"dart:math","element":{"kind":"FU
1572467965749 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2045,"uri":"dart:developer","items":[{"label":"TimelineSyncFunction","declaringLibraryUri":"dart:develop
1572467965749 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1622,"uri":"dart:ffi","items":[{"label":"Int32Pointer","declaringLibraryUri":"dart:ffi","element":{"kind
1572467965807 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2049,"uri":"dart:async","items":[{"label":"ControllerCancelCallback","declaringLibraryUri":"dart:async",
1572467965831 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2033,"uri":"dart:io","items":[{"label":"Stdout","declaringLibraryUri":"dart:io","element":{"kind":"CLASS
1572467966250 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":863,"uri":"dart:_internal","items":[{"label":"UnmodifiableListMixin","declaringLibraryUri":"dart:_intern
1572467966256 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2032,"uri":"dart:isolate","items":[{"label":"Capability","declaringLibraryUri":"dart:isolate","element":
1572467966265 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2026,"uri":"dart:typed_data","items":[{"label":"UnmodifiableUint32ListView","declaringLibraryUri":"dart:
1572467966277 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":808,"uri":"dart:collection","items":[{"label":"MapView","declaringLibraryUri":"dart:collection","element
1572467966430 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":861,"uri":"dart:_http","items":[{"label":"HttpOverrides","declaringLibraryUri":"dart:_http","element":{"
1572467966447 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2046,"uri":"dart:core","items":[{"label":"TypeError","declaringLibraryUri":"dart:core","element":{"kind"
1572467967045 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4,"uri":"dart:ui","items":[{"label":"TextBaseline","declaringLibraryUri":"dart:ui","element":{"kind":"EN
1572467967079 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2047,"uri":"dart:convert","items":[{"label":"Codec","declaringLibraryUri":"dart:convert","element":{"kin
1572467967117 => {"id":"169","method":"server.shutdown","clientRequestTime":1572467967117}
1572467967292 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2029,"uri":"dart:math","items":[{"label":"atan2","declaringLibraryUri":"dart:math","element":{"kind":"FU
1572467967299 <= {"id":"169"}
1572467967537 started analysis server:
  /usr/local/google/home/gspencer/code/flutter/bin/cache/dart-sdk/bin/dart /usr/local/google/home/gspencer/code/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=Intel
1572467967922 <= {"event":"server.connected","params":{"version":"1.27.4","pid":194679}}
1572467968031 <= {"id":"0","result":{"version":"1.27.4"}}
1572467968031 => {"id":"1","method":"completion.setSubscriptions","params":{"subscriptions":["AVAILABLE_SUGGESTION_SETS"]},"clientRequestTime":1572467967540}
1572467968031 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1572467968032 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["/usr/local/google/home/gspencer/code/flutter/dev/benchmarks/complex_layout","/usr/local/google/home/gspencer/code
1572467968032 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/list_tile_test.dart","/usr/local/google/
1572467968032 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/usr/local/google/home/gspencer/code/flutter/packages/flutter/test/material/list_tile_test.dart
1572467968032 => {"id":"6","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":["/usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/material/material.dart","/us
</pre>
</details>
For additional log information, please append the contents of
file:///tmp/report1.txt.

**Comment by gspencergoog** [comment]
Yes, it does exist.  Here's the `cksum` of it:
```
845447099 2185208 /usr/local/google/home/gspencer/code/flutter/bin/cache/dart-sdk/bin/snapshots/libtensorflowlite_c-linux64.so
```

**Comment by lambdabaa** [comment]
Hrm then this is definitely a result of updating the Dart SDK during an analysis session. We should make it so that analysis server doesn't crash when the dynamic library is not found though.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.7.0. Please re-open if you see this crash again.
