### ISSUE TITLE
Metadata on type parameter of function type crashes the analyzer

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39190]
Consider the following program:

```dart
void Function<@deprecated X>(X x) f;

main() {
  f = <X>(X x) {};
}
```

With the `dartanalyzer` from decca61f8c01cc4dbe483549bccaeb1c583ea4a2, this program causes an exception to be thrown:

```
Unhandled exception:
Bad state: Found 1 annotation nodes and 0 element annotations
#0      ResolutionVisitor._setElementAnnotations (package:analyzer/src/dart/resolver/resolution_visitor.dart:1223:7)
#1      ResolutionVisitor.visitTypeParameter (package:analyzer/src/dart/resolver/resolution_visitor.dart:896:5)
#2      TypeParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:10031:49)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7493:20)
#4      TypeParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10081:21)
#5      RecursiveAstVisitor.visitTypeParameterList (package:analyzer/dart/ast/visitor.dart:1296:10)
#6      TypeParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10077:49)
#7      ResolutionVisitor.visitGenericFunctionType.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:664:32)
#8      ResolutionVisitor._withNameScope (package:analyzer/src/dart/resolver/resolution_visitor.dart:1203:8)
#9      ResolutionVisitor.visitGenericFunctionType.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:662:9)
#10     ResolutionVisitor._withElementWalker (package:analyzer/src/dart/resolver/resolution_visitor.dart:1192:8)
#11     ResolutionVisitor.visitGenericFunctionType.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:661:7)
#12     ResolutionVisitor._withElementHolder (package:analyzer/src/dart/resolver/resolution_visitor.dart:1181:8)
#13     ResolutionVisitor.visitGenericFunctionType (package:analyzer/src/dart/resolver/resolution_visitor.dart:660:5)
#14     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5315:20)
#15     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10392:12)
```

I'm proposing in dart-lang/language#656 that we do not support this feature. If we decide to do that then this would be a request to detect the situation and emit a compile-time error, so this issue is blocked on dart-lang/language#656.

**Comment by eernstg** [comment]
Closing; the reported crash does not occur any more, and the decision about raising a compile-time error is handled via https://github.com/dart-lang/language/issues/656.
