### ISSUE TITLE
Parser assertion failure: 'token.next == name': is not true.

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#39202]
```
() async => a b < c $? >
```

```
'package:_fe_analyzer_shared/src/parser/parser_impl.dart': Failed assertion: line 2424 pos 12: 'token.next == name': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      Parser.parseFields (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2424:12)
#3      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2380:12)
#4      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:495:14)
#5      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#6      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:296:37)
<asynchronous suspension>
#7      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:255:13)
[...]
```

**Comment by jensjoha** [comment]
This was fixed in c75e5e4cf45f4ee4d8e8fb1c45cdb87bb5eb5b57.
