### ISSUE TITLE
NNBD Migrator crashes with --outputDir on path package

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#39203]
Run the migrator on the path package with `--outputDir`, something like:

```none
$ $SDK/xcodebuild/ReleaseX64/dart-sdk/bin/dart \
      $SDK/pkg/dartfix/bin/dartfix.dart \
      --fix=non-nullable \
      --overwrite \
      --outputDir nnbd-i13n \
      .
```

I get the following crash:

```none
Fatal Server Error: Failed to handle request: {id: 2, method: edit.dartfix, params: {included: [/Users/srawlins/code/dart-path], includedFixes: [non-nullable
], outputDir: /Users/srawlins/code/dart-path/nnbd-i13n}}                                                                                                     
NoSuchMethodError: The getter 'source' was called on null.
Receiver: null
Tried calling: source
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      InfoBuilder._computeUpstreamTriggeredDetails (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:309:33)
#2      InfoBuilder._explainUnit (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:381:13)
#3      InfoBuilder.explainMigration (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:73:21)                                              
<asynchronous suspension>
#4      NonNullableFix._generateOutput (package:analysis_server/src/edit/fix/non_nullable_fix.dart:225:49)                                                  
<asynchronous suspension>
#5      NonNullableFix.finish (package:analysis_server/src/edit/fix/non_nullable_fix.dart:84:13)                                                            
<asynchronous suspension>
#6      FixCodeProcessor.finishCodeTasks (package:analysis_server/src/edit/fix/fix_code_task.dart:40:18)                                                    
<asynchronous suspension>
```

**Comment by srawlins** [comment]
Oops. This was fixed a while ago.
