### ISSUE TITLE
Environment problem or compiler bug?

### ISSUE THREAD

**Issue by skillitzimberg** [dart-lang/sdk#39241]
* Dart SDK Version (`dart --version`)
`Dart VM version: 2.5.1 (Fri Sep 27 12:28:49 2019 +0200) on "macos_x64"`
* Using Chrome

I'm on macOS Mojave (10.14.6).

$HOME = `/Users/ForeignFood`.

I have the Flutter SDK at `$HOME/flutter`.

I also have a `$HOME/.pub-cache`.

In my PATH are both:
`/Users/ForeignFood/flutter/bin` and `/Users/ForeignFood/.pub-cache/bin`.

I have a Flutter web app at `$HOME/development/<my_app>/<flutter_web_app>`.

I'm not sure what to include here . . .

```
flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Error compiling dartdevc module:web_flutter|lib/widgets/dropdown_lists.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/Users/ForeignFood/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd
    --no-summarize -o packages/web_flutter/widgets/dropdown_lists.ddc.js --source-map
    --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash
    --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64
    --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation
    --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics --summary=packages/meta/meta.ddc.dill=packages/meta/meta
    --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web
    --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation
    --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
    --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
    --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
    --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue
    --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
    --summary=packages/collection/collection.ddc.dill=packages/collection/collection
    --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena
    --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures
    --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web
    --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting
    --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding
    --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics
    --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation
    --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation
    --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size
    --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering
    --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions
    --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets
    --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet
    --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino
    --summary=packages/flutter/material.ddc.dill=packages/flutter/material
    --summary=packages/web_flutter/widgets/dropdown_form_field.ddc.dill=packages/web_flutter/widgets/dropdown_form_field
    --summary=packages/provider/provider.ddc.dill=packages/provider/provider
    --summary=packages/json_annotation/json_annotation.ddc.dill=packages/json_annotation/json_annotation
    --summary=packages/web_flutter/model/unix_time_date_time_converter.ddc.dill=packages/web_flutter/model/unix_time_date_time_converter
    --summary=packages/js/js_util.ddc.dill=packages/js/js_util --summary=packages/js/js.ddc.dill=packages/js/js
    --summary=packages/firebase/src/app.ddc.dill=packages/firebase/src/app
    --summary=packages/firebase/firestore.ddc.dill=packages/firebase/firestore
    --summary=packages/web_flutter/model/model.ddc.dill=packages/web_flutter/model/model
    --packages=file:///var/folders/k6/7fb38mks7mb0zcf10kth0l380000gn/T/kernel_builder_xlfBJp/.packages
    --module-name=packages/web_flutter/widgets/dropdown_lists --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation
    --inline-source-map --libraries-file=file:///Users/ForeignFood/flutter/bin/cache/flutter_web_sdk/libraries.json
    --used-inputs-file=/var/folders/k6/7fb38mks7mb0zcf10kth0l380000gn/T/ddk_builder_xzs3b0/used_inputs.txt
    package:web_flutter/widgets/dropdown_lists.dart
    dart --version: 2.6.0-dev.1.0.flutter-d6c6d12ebf (Fri Oct 4 10:11:30 2019 +0000) on "macos_x64"

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:448:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:459:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:161:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:458:14)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:396:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:207:29)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
                                                 
AssetNotFoundException: web_flutter|lib/widgets/dropdown_lists.ddc.js   
Failed after 418ms
```

**Comment by vsmenon** [comment]
De-dupping to:

https://github.com/dart-lang/sdk/issues/38102

fyi - @jakemac53
