### ISSUE TITLE
NNBD migration tool crashes on "false ? [] : null"

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#39269]
Take:

```dart
main() {
  false ? [] : null;
}
```

Run:

```
$ dart ~/dev/dart/sdk/pkg/dartfix/bin/dartfix.dart --fix=non-nullable ~/temp/
```

And I get:

```
 • UnimplementedError: LUB/GLB with substitution in "false ? [] : null" on line 2 of "/Users/rnystrom/Documents/temp/lib/temp.dart"

#0      EdgeBuilder._unimplemented (package:nnbd_migration/src/edge_builder.dart:2093:5)
#1      EdgeBuilder._decorateUpperOrLowerBound (package:nnbd_migration/src/edge_builder.dart:1485:13)
#2      EdgeBuilder.visitConditionalExpression (package:nnbd_migration/src/edge_builder.dart:514:23)
#3      ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:2199:15)
#4      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3657:18)
#5      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#6      PermissiveModeVisitor.visitNode (package:nnbd_migration/src/utilities/permissive_mode.dart:39:22)
#7      GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#8      GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:271:59)
#9      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3653:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7494:20)
#11     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1078:17)
#12     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#13     PermissiveModeVisitor.visitNode (package:nnbd_migration/src/utilities/permissive_mode.dart:39:22)
#14     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#15     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:162:31)
#16     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1074:49)
#17     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1033:13)
#18     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#19     PermissiveModeVisitor.visitNode (package:nnbd_migration/src/utilities/permissive_mode.dart:39:22)
#20     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#21     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:165:55)
#22     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1029:49)
#23     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:664:35)
...
```

**Comment by bwilkerson** [comment]
@MichaelRFairhurst I believe this is on your short list.

**Comment by MichaelRFairhurst** [comment]
https://dart-review.googlesource.com/c/sdk/+/128082
