### ISSUE TITLE
Dart analysis server error

### ISSUE THREAD

**Issue by debasiskoley** [dart-lang/sdk#39272]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1280x800`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Exception while using a UnnecessaryOverrides to visit a MethodDeclarationImpl in ExtensionDeclarationImpl in CompilationUnitImpl
type 'ExtensionDeclarationImpl' is not a subtype of type 'ClassOrMixinDeclaration' in type cast
#0      DartTypeUtilities.lookUpInheritedConcreteGetter (package:linter/src/util/dart_type_utilities.dart:198:20)
#1      _UnnecessaryGetterOverrideVisitor.getInheritedElement (package:linter/src/rules/unnecessary_overrides.dart:166:25)
#2      _AbstractUnnecessaryOverrideVisitor.visitMethodDeclaration (package:linter/src/rules/unnecessary_overrides.dart:106:23)
#3      _Visitor.visitMethodDeclaration (package:linter/src/rules/unnecessary_overrides.dart:274:15)
#4      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7101:49)
#5      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#6      LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:449:5)
#7      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7101:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#9      ExtensionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3933:14)
#10     RecursiveAstVisitor.visitExtensionDeclaration (package:analyzer/dart/ast/visitor.dart:845:10)
#11     ExtensionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3926:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#13     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#14     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#15     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#16     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#17     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:353:10)
#18     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:206:11)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#20     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:201:35)
#21     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#23     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#24     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#25     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#26     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#27     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:927:33)
<asynchronous suspension>
#28     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#29     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#30     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#31     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#32     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#33     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1463:12)
#38     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#39     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#40     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#41     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#42     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#43     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#44     new Future.sync (dart:async/future.dart:224:31)
#45     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#46     _rootRun (dart:async/zone.dart:1124:13)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _runZoned (dart:async/zone.dart:1516:10)
#49     runZoned (dart:async/zone.dart:1463:12)
#50     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#51     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta...
```

For additional log information, please append the contents of
file:///private/var/folders/35/_vtky_653q59523yd_3hqznh0000gn/T/report1.txt.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.5; please re-open if you see this in a recent version of Dart/Flutter.
