### ISSUE TITLE
Bytecode needs to check for type arguments passed to closures in prologue

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#39283]
For this example:
```dart
class A {
  dynamic foo(a) {
    baz() {
      print('a $a');
    }
    return baz;
  }
}

main() {
  dynamic x = A().foo(1);
  x<List>();
}
```

Default:
```
% rm -rf out/ReleaseX64
% tools/build.py -ax64 -mrelease runtime_kernel
% out/ReleaseX64/dart test.dart
Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function 'A.foo.baz'
Receiver: Closure: () => Null
Tried calling: A.foo.baz<List<dynamic>>()
Found: A.foo.baz() => Null
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      main (../test.dart:12:4)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
Bytecode:
```
% rm -rf out/ReleaseX64
% tools/gn.py -mrelease --bytecode -ax64
% tools/build.py -ax64 -mrelease runtime_kernel
% out/ReleaseX64/dart test.dart
a 1
```

^^^ This should have thrown an exception instead.

/cc @alexmarkov @a-siva @mraleph

**Comment by mkustermann** [comment]
The unoptimized IR shows a clear difference:

AST:
```
B0[graph]:0
B1[function entry]:2
    t0 <- LoadLocal(:arg_desc @0)
    t0 <- LoadField(t0 . ArgumentsDescriptor.type_args_len {final})
    t1 <- Constant(#0)
    Branch if StrictCompare:8(===, t0, t1) goto (4, 5) 
B4[target]:12
    goto:16 B3
B3[join]:6 pred(B4)
    t0 <- LoadLocal(:arg_desc @0)
    t0 <- LoadField(t0 . ArgumentsDescriptor.count {final})
    t1 <- LoadLocal(:t0 @-5)
    t2 <- Constant(#1)
    Branch if StrictCompare:22(===, t1, t2) goto (7, 8) 
B7[target]:26
    t1 <- LoadLocal(:arg_desc @0)
    t1 <- LoadField(t1 . ArgumentsDescriptor.positional_count {final})
    Branch if StrictCompare:30(===, t0, t1) goto (9, 10)
<normal body>
```

Bytecode:
```
B0[graph]:0
B1[function entry]:2
    t0 <- LoadLocal(:arg_desc @-4)
    t0 <- LoadField(t0 . ArgumentsDescriptor.positional_count {final})
    t1 <- Constant(#1)
    Branch if StrictCompare:10(===, t0, t1) goto (5, 6) 
B5[target]:14
    t0 <- LoadLocal(:arg_desc @-4)
    t0 <- LoadField(t0 . ArgumentsDescriptor.count {final})
    t1 <- Constant(#1)
    Branch if StrictCompare:18(===, t0, t1) goto (7, 8) 
<normal body>
```
