### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by omontoya** [dart-lang/sdk#39309]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35, server version 1.27.3, error: Analysis failed: /Users/omontoya/omtreksoft/flutter_stores/lib/ui/shop/product_details.dart context: exception_20191108_153856_812
type 'MultiplyDefinedElementImpl' is not a subtype of type 'ElementImpl' in type cast
#0      LinkingBundleContext.indexOfElement (package:analyzer/src/summary2/linking_bundle_context.dart:60:30)
#1      AstBinaryWriter._indexOfElement (package:analyzer/src/summary2/ast_binary_writer.dart:1483:28)
#2      AstBinaryWriter._componentsOfElement (package:analyzer/src/summary2/ast_binary_writer.dart:1478:24)
#3      AstBinaryWriter.visitAnnotation (package:analyzer/src/summary2/ast_binary_writer.dart:47:29)
#4      AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:285:49)
#5      AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:1668:31)
#6      AstBinaryWriter._storeAnnotatedNode (package:analyzer/src/summary2/ast_binary_writer.dart:1487:38)
#7      AstBinaryWriter._storeDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:1515:5)
#8      AstBinaryWriter._storeCompilationUnitMember (package:analyzer/src/summary2/ast_binary_writer.dart:1508:5)
#9      AstBinaryWriter._storeNamedCompilationUnitMember (package:analyzer/src/summary2/ast_binary_writer.dart:1580:5)
#10     AstBinaryWriter._storeClassOrMixinDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:1502:5)
#11     AstBinaryWriter.visitClassDeclaration (package:analyzer/src/summary2/ast_binary_writer.dart:221:7)
#12     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#13     AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:1668:31)
#14     AstBinaryWriter.visitCompilationUnit (package:analyzer/src/summary2/ast_binary_writer.dart:286:37)
#15     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#16     AstBinaryWriter.writeUnit (package:analyzer/src/summary2/ast_binary_writer.dart:1457:19)
#17     Linker._createLinkingBundle (package:analyzer/src/summary2/link.dart:183:37)
#18     Linker.link (package:analyzer/src/summary2/link.dart:86:5)
#19     link (package:analyzer/src/summary2/link.dart:35:10)
#20     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:187:26)
#21     SetMixin.forEach (dart:collection/set.dart:146:30)
#22     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:142:32)
#23     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:239:17)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#25     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:237:12)
#26     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:88:5)
#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1439:29)
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:30)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1237:20)
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1047:17)
#32     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#38     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#39     _rootRun (dart:async/zone.dart:1124:13)
#40     _CustomZone.run (dart:async/zone.dart:1021:19)
#41     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#46     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/j7/1rxg6ybs6nl9szz0jhcc8g7c0000gn/T/report.txt.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.6; please re-open if you see this in a recent version of Dart/Flutter.
