### ISSUE TITLE
"No compilation service available; cannot evaluate from source" when evaluating on Linux

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#39330]
I sometimes this see failure in Dart-Code's debugger integration tests (most recently on Linux, but I don't know if it's always there). I don't know if it matters, but this is in a Flutter project.

I have a file like this:

```dart
import 'package:flutter/material.dart';

class Person {
  String get kind => "Person";
  String get throws => throw "Oops!";
}

class Danny extends Person {
  String get name => "Danny";
}

main() {
  var danny = Danny();
  print(danny.name); // BREAKPOINT1

  runApp(MyApp());
}
```

My test puts a breakpoint on the line with `BREAKPOINT1` and then looks for a variable named `danny` in the variables for the top stack frame, and then tries to get get its field and getters. It sends (individual, concurrent) requests to `evaluate` the fields `hashCode`, `kind`, `name`, `runtimeType`, `throws` but sometimes it gets an error back like this:

```js
{
	"jsonrpc": "2.0",
	"error": {
		"code": 113,
		"message": "Extension error",
		"data": {
			"request": {
				"method": "evaluate",
				"params": {
					"disableBreakpoints": "true",
					"expression": "name",
					"isolateId": "isolates\/110307640286607",
					"targetId": "objects\/33"
				}
			},
			"details": "evaluate: No compilation service available; cannot evaluate from source."
		}
	},
	"id": "499"
}
```

Here's a log that shows the requests for each field, and all but one of them are successful, but `name` fails:

```
==> {"id":"497","method":"evaluate","params":{"disableBreakpoints":true,"expression":"hashCode","isolateId":"isolates/110307640286607","targetId":"objects/33"}}
==> {"id":"498","method":"evaluate","params":{"disableBreakpoints":true,"expression":"kind","isolateId":"isolates/110307640286607","targetId":"objects/33"}}
==> {"id":"499","method":"evaluate","params":{"disableBreakpoints":true,"expression":"name","isolateId":"isolates/110307640286607","targetId":"objects/33"}}
==> {"id":"500","method":"evaluate","params":{"disableBreakpoints":true,"expression":"runtimeType","isolateId":"isolates/110307640286607","targetId":"objects/33"}}
==> {"id":"501","method":"evaluate","params":{"disableBreakpoints":true,"expression":"throws","isolateId":"isolates/110307640286607","targetId":"objects/33"}}
<== {"jsonrpc":"2.0", "result":{"type":"@Instance","_vmType":"String","class":{"type":"@Class","fixedId":true,"id":"classes\/75","name":"_OneByteString","_vmName":"_OneByteString@0150898"},"kind":"String","id":"objects\/66","length":6,"valueAsString":"Person"},"id":"498"}
<== {"jsonrpc":"2.0", "result":{"type":"@Instance","_vmType":"Smi","class":{"type":"@Class","fixedId":true,"id":"classes\/48","name":"_Smi","_vmName":"_Smi@0150898"},"kind":"Int","fixedId":true,"id":"objects\/int-236206786","valueAsString":"236206786"},"id":"497"}
<== {"jsonrpc":"2.0", "error":{"code":113,"message":"Extension error","data":{"request":{"method":"evaluate","params":{"disableBreakpoints":"true","expression":"name","isolateId":"isolates\/110307640286607","targetId":"objects\/33"}},"details":"evaluate: No compilation service available; cannot evaluate from source."}},"id":"499"}
<== {"jsonrpc":"2.0", "result":{"type":"@Instance","_vmType":"Type","class":{"type":"@Class","fixedId":true,"id":"classes\/42","name":"_Type","_vmName":"_Type@0150898"},"kind":"Type","fixedId":true,"id":"classes\/3851\/types\/0","typeClass":{"type":"@Class","fixedId":true,"id":"classes\/3851","name":"Danny"},"name":"Danny"},"id":"500"}
```

**Comment by ZichangG** [comment]
Is it easy to reproduce?
I ran several times with your example but were not able to reproduce the problem.

**Comment by DanTup** [comment]
I don't know about reproducing it on-demand, but it does seem to happen a lot. For example I just checked the logs from the last run and it's there (for Flutter dev channel):

https://test-results.dartcode.org/logs/master/9deb0056388362a5ced13e444b86b41c9d172fce/linux/flutter_debug_dev_insiders/flutter_run_debugger_launch_on_flutter_tester_includes_getters_in_variables_when_stopped_at_a_breakpoint.txt

This log contains all traffic from all parts of the extension so it's quite big - but you can search for `"No compilation service available"`. There were multiple evaluates going on at the same time, I don't know if there's a race (I'm not familiar with how this works):

```
==> {"id":"497","method":"evaluate","params":{"disableBreakpoints":true,"expression":"hashCode","isolateId":"isolates/4000656864453823","targetId":"objects/33"}}
==> {"id":"498","method":"evaluate","params":{"disableBreakpoints":true,"expression":"kind","isolateId":"isolates/4000656864453823","targetId":"objects/33"}}
==> {"id":"499","method":"evaluate","params":{"disableBreakpoints":true,"expression":"name","isolateId":"isolates/4000656864453823","targetId":"objects/33"}}
==> {"id":"500","method":"evaluate","params":{"disableBreakpoints":true,"expression":"runtimeType","isolateId":"isolates/4000656864453823","targetId":"objects/33"}}
==> {"id":"501","method":"evaluate","params":{"disableBreakpoints":true,"expression":"throws","isolateId":"isolates/4000656864453823","targetId":"objects/33"}}
<== {"jsonrpc":"2.0", "result":{"type":"@Instance","_vmType":"Smi","class":{"type":"@Class","fixedId":true,"id":"classes\/48","name":"_Smi","_vmName":"_Smi@0150898"},"kind":"Int","fixedId":true,"id":"objects\/int-638999259","valueAsString":"638999259"},"id":"497"}
<== {"jsonrpc":"2.0", "error":{"code":113,"message":"Extension error","data":{"request":{"method":"evaluate","params":{"disableBreakpoints":"true","expression":"kind","isolateId":"isolates\/4000656864453823","targetId":"objects\/33"}},"details":"evaluate: No compilation service available; cannot evaluate from source."}},"id":"498"}
<== {"jsonrpc":"2.0", "result":{"type":"@Instance","_vmType":"String","class":{"type":"@Class","fixedId":true,"id":"classes\/75","name":"_OneByteString","_vmName":"_OneByteString@0150898"},"kind":"String","id":"objects\/66","length":5,"valueAsString":"Danny"},"id":"499"}
<== {"jsonrpc":"2.0", "result":{"type":"@Instance","_vmType":"Type","class":{"type":"@Class","fixedId":true,"id":"classes\/42","name":"_Type","_vmName":"_Type@0150898"},"kind":"Type","fixedId":true,"id":"classes\/3878\/types\/0","typeClass":{"type":"@Class","fixedId":true,"id":"classes\/3878","name":"Danny"},"name":"Danny"},"id":"500"}
<== {"jsonrpc":"2.0", "result":{"type":"@Error","_vmType":"UnhandledException","kind":"UnhandledException","id":"objects\/67","message":"Unhandled exception:\nOops!\n#0      Person.throws (package:hello_world\/getters.dart:5:24)\n#1      Danny.Eval ()\n#2      main (package:hello_world\/getters.dart:14:15)\n#3      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui\/hooks.dart:239:25)\n#4      _rootRun (dart:async\/zone.dart:1126:13)\n#5      _CustomZone.run (dart:async\/zone.dart:1023:19)\n#6      _runZoned (dart:async\/zone.dart:1518:10)\n#7      runZoned (dart:async\/zone.dart:1502:12)\n#8      _runMainZoned.<anonymous closure> (dart:ui\/hooks.dart:231:5)\n#9      _startIsolate.<anonymous closure> (dart:isolate-patch\/isolate_patch.dart:307:19)\n#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch\/isolate_patch.dart:174:12)\n"},"id":"501"}
```

Interestingly it's the same `kind` field in this failure too (which is likely always the second request sent out of the batch of 5). I think it's been this every time I've seen it recently (since my test fails asserting the value of the returned `kind`).
