### ISSUE TITLE
RangeError (end): Invalid value: Not in range 0..50, inclusive: 56 from LanguageModel.predictWithScores

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#39352]
RangeError (end): Invalid value: Not in range 0..50, inclusive: 56 from LanguageModel.predictWithScores

@lambdabaa - I saw this on an external Dart SDK (one built from master this morning). Do you know why I would have seen this? (and, we should harden the logic here)

## Version information

- `IDEA IC-192.7142.36`
- `2.7.0-edge.d45c3d15cb3cea0104a87697c085259666eec528`
- `IC-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.7.0-edge.d45c3d15cb3cea0104a87697c085259666eec528, server version 1.27.4, FATAL error: RangeError (end): Invalid value: Not in range 0..50, inclusive: 56
#0      RangeError.checkValidRange (dart:core/errors.dart:333:9)
#1      _TypedDoubleListMixin.setRange (dart:typed_data-patch/typed_data_patch.dart:754:18)
#2      _DoubleListMixin.setAll (dart:typed_data-patch/typed_data_patch.dart:735:5)
#3      LanguageModel._transformInput (package:analysis_server/src/services/completion/dart/language_model.dart:97:9)
#4      LanguageModel.predictWithScores (package:analysis_server/src/services/completion/dart/language_model.dart:74:21)
#5      entrypoint.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_ranking.dart:39:34)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#10     _StreamController._add (dart:async/stream_controller.dart:640:7)
#11     _StreamController.add (dart:async/stream_controller.dart:586:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

cc @bwilkerson

**Comment by devoncarew** [comment]
Actually, this was from a dart sdk from flutter:

```
[✓] Flutter (Channel master, v1.10.17-pre.60, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.10.17-pre.60 at /Users/devoncarew/projects/flutter/flutter
    • Framework revision 99055c754a (3 hours ago), 2019-11-12 08:04:48 -0800
    • Engine revision 31cd2dfca2
    • Dart version 2.7.0
```
