### ISSUE TITLE
flutter.setWidgetPropertyValue throws an exception rather than returning the input was invalid

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#39357]
Repro steps: call flutter.setWidgetPropertyValue
passing in an expression that is invalid. For example, add multiple trailing commas to the expression passed in or otherwise create code that will not parse so that dartfmt throws an exception. The exception occurs when dartfmt is run to format the code for the edited expression.
The analyzer fails to apply the completion in this case which is a good thing but throws an internal exception rather than reporting that the expression passed in was invalid.

Ideally, the analyzer would return an error to the analysis server client indicating that the expression is invalid which then could be surfaced to the user.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.7142.36`
- `2.7.0-edge.8bdca37e98a59bdb7f52daea9da838b1a60c1cdf`
- `IC-192.7142.36, JRE 1.8.0_221-b11x64 Oracle Corporation, OS Mac OS X(x86_64) v10.14.6, screens 1920x1200  Retina`

## Exception
```
Dart analysis server, SDK version 2.7.0-edge.8bdca37e98a59bdb7f52daea9da838b1a60c1cdf, server version 1.27.4, FATAL error: Failed to handle request: {id: 139, method: flutter.setWidgetPropertyValue, params: {id: 850, value: {expression: recipe.author'}}}
Could not format because the source could not be parsed:

line 318, column 65: Unterminated string literal.
    ╷
318 │                         Text(recipe.author', style: authorStyle),
    │                                                                 ^
    ╵
line 319, column 23: Expected to find ')'.
    ╷
319 │                       ],
    │                       ^
    ╵
#0      ErrorListener.throwIfErrors (package:dart_style/src/error_listener.dart:28:5)
#1      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:122:19)
#2      DartFileEditBuilderImpl.format (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1267:43)
#3      PropertyDescription._formatEnclosingFunctionBody (package:analysis_server/src/services/flutter/property.dart:322:13)
#4      PropertyDescription.changeValue.<anonymous closure> (package:analysis_server/src/services/flutter/property.dart:133:7)
#5      DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:54:20)
#6      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#7      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:51:18)
#8      PropertyDescription.changeValue (package:analysis_server/src/services/flutter/property.dart:120:25)
<asynchronous suspension>
#9      WidgetDescriptions.setPropertyValue (package:analysis_server/src/services/flutter/widget_descriptions.dart:80:35)
<asynchronous suspension>
#10     FlutterDomainHandler.setPropertyValue (package:analysis_server/src/flutter/flutter_domain.dart:89:57)
<asynchronous suspension>
#11     FlutterDomainHandler.handleRequest (package:analysis_server/src/flutter/flutter_domain.dart:71:9)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:332:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:328:50)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:327:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#48     _SinkTransfor...
```

For additional log information, please append the contents of
file:///private/var/folders/pl/5yqcvds916b39jxc_pb66y700025bq/T/report2.txt.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/125129
