### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by HudsonAfonso** [dart-lang/sdk#39364]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.7142.36`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IU-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1080, 1440x900, 2560x1440  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ConditionalExpressionImpl in ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ConditionalExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ExpressionFunctionBodyImpl in FunctionExpressionImpl in NamedExpressionImpl in ArgumentListImpl in MethodInvocationImpl in ExpressionStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      ListMixin.first (dart:collection/list.dart:76:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#6      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#7      RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#8      LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#9      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#14     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#15     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#16     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#17     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#18     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#19     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#20     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#21     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#23     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#24     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#25     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#26     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#27     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#28     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#29     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#30     ConditionalExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2275:22)
#31     RecursiveAstVisitor.visitConditionalExpression (package:analyzer/dart/ast/visitor.dart:731:10)
#32     LinterVisitor.visitConditionalExpression (package:analyzer/src/lint/linter_visitor.dart:132:11)
#33     ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:2270:15)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#35     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6825:15)
#36     RecursiveAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:1049:10)
#37     LinterVisitor.visitListLiteral (package:analyzer/src/lint/linter_visitor.dart:438:11)
#38     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6820:49)
#39     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#40     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#41     LinterVisitor.visitNamedExpression (package:analyz...
```

For additional log information, please append the contents of
file:///private/var/folders/fv/ybc1939142v07032hw4k8tw00000gn/T/report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.5.0. Please re-open if you see this crash again.
