### ISSUE TITLE
Various vm/cc/ test failures (crash) on dartkb

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#39388]
New fails:

@alexmarkov  @stefantsov 
```
dartkb-interpret-linux-release-x64:vm/cc/DartAPI_FieldAccess broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/EvalExpression broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/FrameLookup broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/FunctionWithBreakpointNotInlined broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/GuardFieldConstructorTest broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/GuardFieldFinalListTest broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/GuardFieldFinalVariableLengthListTest broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/GuardFieldSimpleTest broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/IsolateReload_ConstructorChanged broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/IsolateReload_PendingSuperCall broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/IsolateReload_PendingUnqualifiedCall_InstanceToStatic failed again (Fail -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/IsolateReload_PendingUnqualifiedCall_StaticToInstance failed again (Fail -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/LoadOptimizer_RedundantStoresAndLoads broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/Profiler_BinaryOperatorSourcePosition broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/Profiler_BinaryOperatorSourcePositionOptimized broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/Profiler_SourcePosition broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/Profiler_SourcePositionOptimized broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/Service_Code broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/Service_PcDescriptors broke (Pass -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/SourceReport_Coverage_Issue35453_NoSuchMethod failed again (Fail -> Crash, expected Pass)
dartkb-interpret-linux-release-x64:vm/cc/ValidateStackFrameIteration broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/DartAPI_FieldAccess broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/EvalExpression broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/FrameLookup broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/FunctionWithBreakpointNotInlined broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/GuardFieldConstructorTest broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/GuardFieldFinalListTest broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/GuardFieldFinalVariableLengthListTest broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/GuardFieldSimpleTest broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/IsolateReload_ConstructorChanged broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/IsolateReload_PendingSuperCall broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/IsolateReload_PendingUnqualifiedCall_InstanceToStatic failed again (Fail -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/IsolateReload_PendingUnqualifiedCall_StaticToInstance failed again (Fail -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/LoadOptimizer_RedundantStoresAndLoads broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/Profiler_BinaryOperatorSourcePosition broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/Profiler_BinaryOperatorSourcePositionOptimized broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/Profiler_SourcePosition broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/Profiler_SourcePositionOptimized broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/Service_Code broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/Service_PcDescriptors broke (Pass -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/SourceReport_Coverage_Issue35453_NoSuchMethod failed again (Fail -> Crash, expected Pass)
dartkb-mixed-linux-release-x64:vm/cc/ValidateStackFrameIteration broke (Pass -> Crash, expected Pass)

```

**Comment by aartbik** [comment]
They all seem to be segfault:

```dart
si_signo=Segmentation fault(11), si_code=1, si_addr=0x17

[exit     : sp(0) fp(0x7f2d6c5fd350) pc(0)]
[dart     : sp(0x7f2d6c5fd360) fp(0x7f2d6c5fd3a0) pc(0x7f2d6a47bb0f) *package:kernel/ast.dart_ThisExpression_getStaticType ]
[dart     : sp(0x7f2d6c5fd3b0) fp(0x7f2d6c5fd400) pc(0x7f2d6a47cea4) *package:vm/bytecode/generics.dart_::_getStaticType ]
[dart     : sp(0x7f2d6c5fd410) fp(0x7f2d6c5fd450) pc(0x7f2d6a5d2955) *package:vm/bytecode/gen_bytecode.dart_BytecodeGenerator__genInstanceCall@29193688 ]
[dart     : sp(0x7f2d6c5fd460) fp(0x7f2d6c5fd4f0) pc(0x7f2d6aa2a2cf) package:vm/bytecode/gen_bytecode.dart_BytecodeGenerator_visitPropertySet ]
[dart     : sp(0x7f2d6c5fd500) fp(0x7f2d6c5fd520) pc(0x7f2d6a8b8c32) *package:kernel/ast.dart_PropertySet_accept ]
[dart     : sp(0x7f2d6c5fd530) fp(0x7f2d6c5fd570) pc(0x7f2d6aa14fe6) *package:vm/bytecode/gen_bytecode.dart_BytecodeGenerator__generateNode@29193688 ]
[dart     : sp(0x7f2d6c5fd580) fp(0x7f2d6c5fd5b0) pc(0x7f2d6a389e2c) *package:vm/bytecode/gen_bytecode.dart_BytecodeGenerator_visitExpressionStatement ]
[dart     : sp(0x7f2d6c5fd5c0) fp(0x7f2d6c5fd5e0) pc(0x7f2d6a6ea501) *package:kernel/ast.dart_ExpressionStatement_accept ]
[dart     : sp(0x7f2d6c5fd5f0) fp(0x7f2d6c5fd630) pc(0x7f2d6aa14fe6) *package:vm/bytecode/gen_bytecode.dart_BytecodeGenerator__generateNode@29193688 ]
[dart     : sp(0x7f2d6c5fd640) fp(0x7f2d6c5fd678) pc(0x7f2d6a9d29f0) *package:vm/bytecode/gen_bytecode.dart_BytecodeGenerator__generateNodeList@29193688 ]
[dart     : sp(0x7f2d6c5fd688) fp(0x7f2d6c5fd6a8) pc(0x7f2d6a6cf8f8) *package:vm/bytecode/gen_bytecode.dart_BytecodeGenerator_visitBlock ]
[dart     : sp(0x7f2d6c5fd6b8) fp(0x7f2d6c5fd6d8) pc(0x7f2d6a6ea241) *package:kernel/ast.dart_Block_accept ]
[dart     : sp(0x7f2d6c5fd6e8) fp(0x7f2d6c5fd728) pc(0x7f2d6aa14fe6) *package:vm/bytecode/gen_bytecode.dart_BytecodeGenerator__generateNode@29193688 ]
[dart     : sp(0x7f2d6c5fd738) fp(0x7f2d6c5fd7f8) pc(0x7f2d6a390665) *package:vm/bytecode/gen_bytecode.dart_BytecodeGenerator_defaultMember ]
[dart     : sp(0x7f2d6c5fd808) fp(0x7f2d6c5fd828) pc(0x7f2d6a709bfc) *package:kernel/visitor.dart_TreeVisitor_visitConstructor ]
[dart     : sp(0x7f2d6c5fd838) fp(0x7f2d6c5fd868) pc(0x7f2d6a99a13c) package:kernel/ast.dart_Constructor_accept ]
[dart     : sp(0x7f2d6c5fd878) fp(0x7f2d6c5fd8c0) pc(0x7f2d6a41347b) *package:vm/bytecode/gen_bytecode.dart_BytecodeGenerator_visitClass ]
[dart     : sp(0x7f2d6c5fd8d0) fp(0x7f2d6c5fd900) pc(0x7f2d6a99a26c) package:kernel/ast.dart_Class_accept ]
[dart     : sp(0x7f2d6c5fd910) fp(0x7f2d6c5fd948) pc(0x7f2d6a39168b) *package:kernel/ast.dart_::_visitList ]
[dart     : sp(0x7f2d6c5fd958) fp(0x7f2d6c5fd990) pc(0x7f2d6a9bd6eb) package:vm/bytecode/gen_bytecode.dart_BytecodeGenerator_visitLibrary ]
[dart     : sp(0x7f2d6c5fd9a0) fp(0x7f2d6c5fda38) pc(0x7f2d6a9bf969) package:vm/bytecode/gen_bytecode.dart_::_generateBytecode_<anonymous closure> ]
[dart     : sp(0x7f2d6c5fda48) fp(0x7f2d6c5fdac8) pc(0x7f2d6a999032) dart:developer_Timeline_timeSync ]
[dart     : sp(0x7f2d6c5fdad8) fp(0x7f2d6c5fdb50) pc(0x7f2d6a9c0238) package:vm/bytecode/gen_bytecode.dart_::_generateBytecode ]
[dart     : sp(0x7f2d6c5fdb60) fp(0x7f2d6c5fdbb0) pc(0x7f2d6a3833d6) file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart_Compiler_compile_<anonymous closure>__async_op_<anonymous closure> ]
[dart     : sp(0x7f2d6c5fdbc0) fp(0x7f2d6c5fdc50) pc(0x7f2d6a9bad6c) package:vm/kernel_front_end.dart_::_runWithFrontEndCompilerContext__async_op_<anonymous closure>__async_op ]
[dart     : sp(0x7f2d6c5fdc60) fp(0x7f2d6c5fdc88) pc(0x7f2d6a37a6d7) dart:core__Closure@0150898_call ]
[dart     : sp(0x7f2d6c5fdc98) fp(0x7f2d6c5fdcb8) pc(0x7f2d6a37a799) dart:async__AsyncAwaitCompleter@9048458_start ]
[dart     : sp(0x7f2d6c5fdcc8) fp(0x7f2d6c5fdd38) pc(0x7f2d6a9bb2ed) package:vm/kernel_front_end.dart_::_runWithFrontEndCompilerContext__async_op_<anonymous closure> ]
[dart     : sp(0x7f2d6c5fdd48) fp(0x7f2d6c5fdde0) pc(0x7f2d6a959049) package:front_end/src/fasta/compiler_context.dart_CompilerContext_runWithOptions_<anonymous closure>__async_op ]
[dart     : sp(0x7f2d6c5fddf0) fp(0x7f2d6c5fde30) pc(0x7f2d6a400560) dart:core__Closure@0150898_call ]
[dart     : sp(0x7f2d6c5fde40) fp(0x7f2d6c5fde88) pc(0x7f2d6a9c487f) dart:async_::__asyncThenWrapperHelper@9048458_<anonymous closure> ]
[dart     : sp(0x7f2d6c5fde98) fp(0x7f2d6c5fdf00) pc(0x7f2d6aa9aff2) dart:async_::__rootRunUnary@9048458 ]
[dart     : sp(0x7f2d6c5fdf10) fp(0x7f2d6c5fdf78) pc(0x7f2d6aa8adcb) dart:async_::__rootRunUnary@9048458__rootRunUnary@9048458 ]
[dart     : sp(0x7f2d6c5fdf88) fp(0x7f2d6c5fe000) pc(0x7f2d6aa8a70c) dart:async__CustomZone@9048458_runUnary ]
[dart     : sp(0x7f2d6c5fe010) fp(0x7f2d6c5fe040) pc(0x7f2d6aa8f2e0) dart:async__FutureListener@9048458_handleValue ]
[dart     : sp(0x7f2d6c5fe050) fp(0x7f2d6c5fe0d0) pc(0x7f2d6aa8f5ab) dart:async__Future@9048458__propagateToListeners@9048458_handleValueCallback ]
[dart     : sp(0x7f2d6c5fe0e0) fp(0x7f2d6c5fe150) pc(0x7f2d6aa90b9b) dart:async__Future@9048458__propagateToListeners@9048458 ]
[dart     : sp(0x7f2d6c5fe160) fp(0x7f2d6c5fe188) pc(0x7f2d6a858378) dart:async__Future@9048458__completeWithValue@9048458 ]
[dart     : sp(0x7f2d6c5fe198) fp(0x7f2d6c5fe1e0) pc(0x7f2d6aa93690) dart:async__AsyncAwaitCompleter@9048458_complete ]
[dart     : sp(0x7f2d6c5fe1f0) fp(0x7f2d6c5fe210) pc(0x7f2d6aa9d0e6) dart:async_::__completeOnAsyncReturn@9048458 ]
[dart     : sp(0x7f2d6c5fe220) fp(0x7f2d6c5fe2b8) pc(0x7f2d6a9478a8) package:front_end/src/base/processed_options.dart_ProcessedOptions_validateOptions__async_op ]
[dart     : sp(0x7f2d6c5fe2c8) fp(0x7f2d6c5fe308) pc(0x7f2d6a400560) dart:core__Closure@0150898_call ]
[dart     : sp(0x7f2d6c5fe318) fp(0x7f2d6c5fe360) pc(0x7f2d6a9c487f) dart:async_::__asyncThenWrapperHelper@9048458_<anonymous closure> ]
[dart     : sp(0x7f2d6c5fe370) fp(0x7f2d6c5fe3d8) pc(0x7f2d6aa9aff2) dart:async_::__rootRunUnary@9048458 ]
[dart     : sp(0x7f2d6c5fe3e8) fp(0x7f2d6c5fe450) pc(0x7f2d6aa8adcb) dart:async_::__rootRunUnary@9048458__rootRunUnary@9048458 ]
[dart     : sp(0x7f2d6c5fe460) fp(0x7f2d6c5fe4d8) pc(0x7f2d6aa8a70c) dart:async__CustomZone@9048458_runUnary ]
[dart     : sp(0x7f2d6c5fe4e8) fp(0x7f2d6c5fe518) pc(0x7f2d6aa8f2e0) dart:async__FutureListener@9048458_handleValue ]
[dart     : sp(0x7f2d6c5fe528) fp(0x7f2d6c5fe5a8) pc(0x7f2d6aa8f5ab) dart:async__Future@9048458__propagateToListeners@9048458_handleValueCallback ]
[dart     : sp(0x7f2d6c5fe5b8) fp(0x7f2d6c5fe628) pc(0x7f2d6aa90b9b) dart:async__Future@9048458__propagateToListeners@9048458 ]
[dart     : sp(0x7f2d6c5fe638) fp(0x7f2d6c5fe660) pc(0x7f2d6a858378) dart:async__Future@9048458__completeWithValue@9048458 ]
[dart     : sp(0x7f2d6c5fe670) fp(0x7f2d6c5fe6a8) pc(0x7f2d6a8580d1) dart:async__Future@9048458__asyncComplete@9048458_<anonymous closure> ]
[dart     : sp(0x7f2d6c5fe6b8) fp(0x7f2d6c5fe718) pc(0x7f2d6aa9b338) dart:async_::__rootRun@9048458 ]
[dart     : sp(0x7f2d6c5fe728) fp(0x7f2d6c5fe788) pc(0x7f2d6aa8b6e3) dart:async_::__rootRun@9048458__rootRun@9048458 ]
[dart     : sp(0x7f2d6c5fe798) fp(0x7f2d6c5fe808) pc(0x7f2d6aa8b109) dart:async__CustomZone@9048458_run ]
[dart     : sp(0x7f2d6c5fe818) fp(0x7f2d6c5fe860) pc(0x7f2d6aa8911a) dart:async__CustomZone@9048458_bindCallback_<anonymous closure> ]
[dart     : sp(0x7f2d6c5fe870) fp(0x7f2d6c5fe898) pc(0x7f2d6aa7b9a4) dart:async_::__microtaskLoop@9048458 ]
[dart     : sp(0x7f2d6c5fe8a8) fp(0x7f2d6c5fe8e0) pc(0x7f2d6aa7bb52) dart:async_::__startMicrotaskLoop@9048458 ]
[dart     : sp(0x7f2d6c5fe8f0) fp(0x7f2d6c5fe920) pc(0x7f2d6aa7be37) dart:async_::__startMicrotaskLoop@9048458__startMicrotaskLoop@9048458 ]
[dart     : sp(0x7f2d6c5fe930) fp(0x7f2d6c5fe958) pc(0x7f2d6aa7bf41) dart:isolate_::__runPendingImmediateCallback@1026248 ]
[dart     : sp(0x7f2d6c5fe968) fp(0x7f2d6c5fe978) pc(0x7f2d6aa9d4a5) dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]
[entry    : sp(0x7f2d6c5fe988) fp(0x7f2d6c5fe9e8) pc(0x7f2d6c60147c)]

```

**Comment by alexmarkov** [comment]
Stack trace from the debugger:

```
#0  dart::TypedDataBase::DataAddr (this=0x555559eef178, byte_offset=0) at ../../runtime/vm/compiler/../object.h:8957
#1  dart::CatchEntryMovesMapReader::ReadMovesForPcOffset (this=<optimized out>, pc_offset=308) at ../../runtime/vm/exceptions.cc:388
#2  dart::ExceptionHandlerFinder::ReadCompressedCatchEntryMoves (this=<optimized out>) at ../../runtime/vm/exceptions.cc:324
#3  dart::ExceptionHandlerFinder::Find (this=0x7ffff27fd0c8) at ../../runtime/vm/exceptions.cc:202
#4  0x0000555558c23dca in dart::ThrowExceptionHelper (thread=<optimized out>, incoming_exception=..., existing_stacktrace=..., is_rethrow=false) at ../../runtime/vm/exceptions.cc:694
#5  0x0000555558c23bd4 in dart::Exceptions::Throw (thread=0x555559c95700, exception=...) at ../../runtime/vm/exceptions.cc:890
#6  0x0000555558d3fbb6 in dart::DRT_HelperThrow (isolate=<optimized out>, thread=0x555559eeed00, zone=<optimized out>, arguments=...) at ../../runtime/vm/runtime_entry.cc:976
#7  0x0000555558d3fb81 in dart::DRT_Throw (arguments=...) at ../../runtime/vm/runtime_entry.cc:974
#8  0x00007ffff6e00ff8 in ?? ()
```

There are 2 problems:

1. Dart exception is thrown when bytecode generator calls `ThisExpression.getStaticType`. This is most likely related to the change made by @stefantsov .

2. We're running in JIT mode, but trying to use `ReadCompressedCatchEntryMoves`, which is intended for AOT only. This happens because `DART_PRECOMPILER` is defined when building `run_vm_tests`. As a result, it crashes while throwing Dart exception.

**Comment by alexmarkov** [comment]
Fix for Dart exception: https://dart-review.googlesource.com/c/sdk/+/125230.
