### ISSUE TITLE
Suddenly not getting code hinting in Android Studio

### ISSUE THREAD

**Issue by FlashJonas** [dart-lang/sdk#39385]
Have restarted and upgraded AS and Flutter.
As soon as I start writing, I see that there is an error within AS. Clicking it generates the logs below.

("Dart Analyzer Error Encountered a Dart Analysis Server error.")

Analyzer Feedback from IntelliJ

## Version information (1/2 191.8026.42.35.5900203)

- `IDEA AI-191.8026.42.35.5900203`
- `2.7.0-edge.fa4379946109467c8a48f20f19d83d7c72968a3e`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 2560x1440, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.7.0-edge.fa4379946109467c8a48f20f19d83d7c72968a3e, server version 1.27.4, FATAL error: RangeError (end): Invalid value: Not in range 0..50, inclusive: 100
#0      RangeError.checkValidRange (dart:core/errors.dart:333:9)
#1      _TypedDoubleListMixin.setRange (dart:typed_data-patch/typed_data_patch.dart:754:18)
#2      _DoubleListMixin.setAll (dart:typed_data-patch/typed_data_patch.dart:735:5)
#3      LanguageModel._transformInput (package:analysis_server/src/services/completion/dart/language_model.dart:97:9)
#4      LanguageModel.predictWithScores (package:analysis_server/src/services/completion/dart/language_model.dart:74:21)
#5      entrypoint.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_ranking.dart:39:34)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#10     _StreamController._add (dart:async/stream_controller.dart:640:7)
#11     _StreamController.add (dart:async/stream_controller.dart:586:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/06/r0my7ghn563gh84vv666w5fh0000gn/T/report.txt.

Analyzer Feedback from IntelliJ

## Version information  (2/2 191.8026.42.35.5977832)

- `IDEA AI-191.8026.42.35.5977832`
- `2.7.0-edge.fa4379946109467c8a48f20f19d83d7c72968a3e`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 2560x1440, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.7.0-edge.fa4379946109467c8a48f20f19d83d7c72968a3e, server version 1.27.4, FATAL error: RangeError (end): Invalid value: Not in range 0..50, inclusive: 100
#0      RangeError.checkValidRange (dart:core/errors.dart:333:9)
#1      _TypedDoubleListMixin.setRange (dart:typed_data-patch/typed_data_patch.dart:754:18)
#2      _DoubleListMixin.setAll (dart:typed_data-patch/typed_data_patch.dart:735:5)
#3      LanguageModel._transformInput (package:analysis_server/src/services/completion/dart/language_model.dart:97:9)
#4      LanguageModel.predictWithScores (package:analysis_server/src/services/completion/dart/language_model.dart:74:21)
#5      entrypoint.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_ranking.dart:39:34)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#10     _StreamController._add (dart:async/stream_controller.dart:640:7)
#11     _StreamController.add (dart:async/stream_controller.dart:586:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/06/r0my7ghn563gh84vv666w5fh0000gn/T/report1.txt.

**Comment by FlashJonas** [comment]
Reverted my Flutter channel to solve it:
(Seems to be an issue on dev-channel)
```
flutter channel stable
flutter upgrade
```
