### ISSUE TITLE
Dart Analyzer Error 			Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by amitkanyan** [dart-lang/sdk#39392]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553, server version 1.27.3, FATAL error: Failed to handle request: {id: 3222, method: edit.getFixes, params: {file: /Users/pro/Documents/Amit's project/Flutter/restrosurvey/lib/ViewClasses/add_bill.dart, offset: 8280}, clientRequestTime: 1573804557661}
RangeError: Index: -2, Size: 2
#0      NodeListImpl.[] (package:analyzer/src/dart/ast/ast.dart:7665:7)
#1      RangeFactory.nodeInList (package:analyzer_plugin/utilities/range_factory.dart:86:25)
#2      FixProcessor._addFix_removeUnusedElement (package:analysis_server/src/services/correction/fix_internal.dart:3612:33)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#4      FixProcessor._addFix_removeUnusedElement (package:analysis_server/src/services/correction/fix_internal.dart:3591:43)
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:376:13)
#6      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#7      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:205:28)
#8      DartFixContributor._computeFixAllFixes (package:analysis_server/src/services/correction/fix_internal.dart:112:53)
#9      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#10     DartFixContributor._computeFixAllFixes (package:analysis_server/src/services/correction/fix_internal.dart:78:40)
#11     DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:71:37)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#21     FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart)
#22     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#29     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#30     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#31     FixProcessor._addFix_removeUnusedElement (package:analysis_server/src/services/correction/fix_internal.dart)
#32     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#38     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#39     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#40     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#41     ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart)
#42     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#43     _rootRunUnary (dart:async/zone.dart:1132:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#45     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#47     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#48     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#49     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#50     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#51     DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart)
#52     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#53     _rootRunUnary (dart:async/zone.dart:1132:38)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#56     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#57     Future._...
```

For additional log information, please append the contents of
file:///private/var/folders/lj/9vs3v9bn4_b3wzlp979vzgnw0000gn/T/report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.6.0. Please re-open if you see this crash again.
