### ISSUE TITLE
[Infra] Timeout when approving failures

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#39398]
```
tools/sdks/dart-sdk/bin/dart tools/approve_results.dart -b vm-kernel-*
Selected bot: vm-kernel-asan-linux-release-x64
Selected bot: vm-kernel-ast-linux-debug-ia32
Selected bot: vm-kernel-ast-linux-debug-x64
Selected bot: vm-kernel-ast-linux-release-ia32
Selected bot: vm-kernel-ast-linux-release-simarm
Selected bot: vm-kernel-ast-linux-release-simarm64
Selected bot: vm-kernel-ast-linux-release-x64
Selected bot: vm-kernel-ast-win-debug-x64
Selected bot: vm-kernel-ast-win-release-x64
Selected bot: vm-kernel-checked-linux-release-x64
Selected bot: vm-kernel-linux-debug-ia32
Selected bot: vm-kernel-linux-debug-x64
Selected bot: vm-kernel-linux-product-x64
Selected bot: vm-kernel-linux-release-ia32
Selected bot: vm-kernel-linux-release-simarm
Selected bot: vm-kernel-linux-release-simarm64
Selected bot: vm-kernel-linux-release-x64
Selected bot: vm-kernel-mac-debug-x64
Selected bot: vm-kernel-mac-product-x64
Selected bot: vm-kernel-mac-release-x64
Selected bot: vm-kernel-optcounter-threshold-linux-release-ia32
Selected bot: vm-kernel-optcounter-threshold-linux-release-x64
Selected bot: vm-kernel-precomp-android-release-arm
Selected bot: vm-kernel-precomp-android-release-arm64
Selected bot: vm-kernel-precomp-android-release-arm_x64
Selected bot: vm-kernel-precomp-ast-linux-debug-x64
Selected bot: vm-kernel-precomp-ast-linux-release-simarm64
Selected bot: vm-kernel-precomp-ast-linux-release-simarm_x64
Selected bot: vm-kernel-precomp-ast-linux-release-x64
Selected bot: vm-kernel-precomp-bare-linux-release-simarm
Selected bot: vm-kernel-precomp-bare-linux-release-simarm64
Selected bot: vm-kernel-precomp-bare-linux-release-x64
Selected bot: vm-kernel-precomp-linux-debug-simarm_x64
Selected bot: vm-kernel-precomp-linux-debug-x64
Selected bot: vm-kernel-precomp-linux-product-x64
Selected bot: vm-kernel-precomp-linux-release-simarm
Selected bot: vm-kernel-precomp-linux-release-simarm64
Selected bot: vm-kernel-precomp-linux-release-x64
Selected bot: vm-kernel-precomp-mac-release-simarm64
Selected bot: vm-kernel-precomp-mac-release-simarm_x64
Selected bot: vm-kernel-precomp-obfuscate-linux-release-x64
Selected bot: vm-kernel-precomp-win-release-x64
Selected bot: vm-kernel-reload-linux-debug-x64
Selected bot: vm-kernel-reload-linux-release-x64
Selected bot: vm-kernel-reload-rollback-linux-debug-x64
Selected bot: vm-kernel-reload-rollback-linux-release-x64
Selected bot: vm-kernel-win-debug-ia32
Selected bot: vm-kernel-win-debug-x64
Selected bot: vm-kernel-win-product-x64
Selected bot: vm-kernel-win-release-ia32
Selected bot: vm-kernel-win-release-x64
Unhandled exception:
Exception: Failed to run: python /usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gsutil.py [cat, gs://dart-test-results/builders/vm-kernel-precomp-linux-release-simarm/latest]
exitCode: 1
stdout:

stderr:
Traceback (most recent call last):
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gsutil.py", line 120, in <module>
    RunMain()
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gsutil.py", line 117, in RunMain
    sys.exit(gslib.__main__.main())
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/__main__.py", line 404, in main
    perf_trace_token=perf_trace_token, user_project=user_project)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/__main__.py", line 587, in _RunNamedCommandAndHandleExceptions
    user_project=user_project)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/command_runner.py", line 372, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/commands/cat.py", line 145, in RunCommand
    end_byte=end_byte)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/utils/cat_helper.py", line 140, in CatUrlStrings
    provider=storage_url.scheme)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/cloud_api_delegator.py", line 282, in GetObjectMedia
    decryption_tuple=decryption_tuple)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/gcs_json_api.py", line 988, in GetObjectMedia
    decryption_tuple=decryption_tuple)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/gcs_json_api.py", line 1077, in _PerformDownload
    additional_headers=additional_headers, use_chunks=False)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/third_party/apitools/apitools/base/py/transfer.py", line 524, in StreamMedia
    additional_headers=additional_headers)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/third_party/apitools/apitools/base/py/transfer.py", line 413, in __GetChunk
    retries=self.num_retries)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 356, in MakeRequest
    max_retry_wait, total_wait_sec))
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/utils/retry_util.py", line 74, in RetriesInDataTransferHandler
    http_wrapper.RethrowExceptionHandler(retry_args)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 346, in MakeRequest
    check_response_func=check_response_func)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 396, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/gcs_json_media.py", line 502, in NewRequest
    connection_type=connection_type)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/third_party/oauth2client/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/third_party/oauth2client/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1694, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/gcs_json_media.py", line 409, in OverrideRequest
    headers)
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/gcs_json_media.py", line 624, in _conn_request
    response = conn.getresponse()
  File "/usr/local/google/home/alexmarkov/work/dart/sdk/third_party/gsutil/gslib/gcs_json_media.py", line 328, in getresponse
    orig_response = httplib.HTTPConnection.getresponse(self)
  File "/usr/lib/python2.7/httplib.py", line 1148, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 404, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 754, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 641, in read
    v = self._sslobj.read(len)
ssl.SSLError: ('The read operation timed out',)

#0      runGsutil.<anonymous closure> (file:///usr/local/google/home/alexmarkov/work/dart/sdk/tools/bots/results.dart:50:7)
<asynchronous suspension>
#1      new Future.sync (dart:async/future.dart:224:31)
#2      Pool.withResource.<anonymous closure> (package:pool/pool.dart:126:18)
#3      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

/cc @athomas @whesse

**Comment by alexmarkov** [comment]
More narrow approval also times out:

```
tools/sdks/dart-sdk/bin/dart tools/approve_results.dart -b vm-kernel-ast-*
```

**Comment by athomas** [comment]
approve_results.dart is now replaced by the new approvals UI.
