### ISSUE TITLE
The method 'getLibraries' was called on null

### ISSUE THREAD

**Issue by alekskuzmin** [dart-lang/sdk#39420]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows ***`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: Failed to handle request: {id: 240, method: edit.getFixes, params: {file: ***.dart, offset: 267}, clientRequestTime: 1574046100793}
NoSuchMethodError: The method 'getLibraries' was called on null.
Receiver: null
Tried calling: getLibraries("***.dart")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      TopLevelDeclarationsProvider.get (package:analysis_server/src/services/correction/fix/dart/top_level_declarations.dart:78:41)
#2      EditDomainHandler._computeDartFixes.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:644:29)
#3      DartFixContextImpl.getTopLevelDeclarations (package:analysis_server/src/services/correction/fix.dart:131:12)
#4      FixProcessor._addFix_importLibrary_withElement (package:analysis_server/src/services/correction/fix_internal.dart:2476:34)
<asynchronous suspension>
#5      FixProcessor._addFix_importLibrary_withFunction (package:analysis_server/src/services/correction/fix_internal.dart:2520:13)
<asynchronous suspension>
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:482:13)
<asynchronous suspension>

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.5.0. Please re-open if you see this crash again.
