### ISSUE TITLE
Crash when compiling package:test/src/executable.dart

### ISSUE THREAD

**Issue by kangwang1988** [dart-lang/sdk#39421]
I'm encountering crash when use `pub run test` command, the error message is given below:
```shell
kylewong@KyleWongdeMacBook-Pro aspectd % pub run test test/aspectd_patch_test.dart 
Failed to precompile test:test:
Crash when compiling package:test/src/executable.dart,
at character offset null:
Unhandled type: InvalidType
#0      Types.performNullabilityAwareSubtypeCheck (package:front_end/src/fasta/kernel/types.dart:221:7)
#1      Types.areTypeArgumentsOfSubtypeKernel (package:front_end/src/fasta/kernel/types.dart:247:29)
#2      IsInterfaceSubtypeOf.isInterfaceRelated (package:front_end/src/fasta/kernel/types.dart:358:10)
#3      Types.performNullabilityAwareSubtypeCheck (package:front_end/src/fasta/kernel/types.dart:112:26)
#4      Types.isSubtypeOfKernel (package:front_end/src/fasta/kernel/types.dart:50:26)
#5      ClassBuilderImpl._checkTypes (package:front_end/src/fasta/builder/class_builder.dart:1486:15)
#6      ClassBuilderImpl.checkGetterOverride (package:front_end/src/fasta/builder/class_builder.dart:1719:5)
#7      ClassBuilderImpl.checkOverride (package:front_end/src/fasta/builder/class_builder.dart:1098:9)
#8      DelayedOverrideCheck.check.callback (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2060:20)
#9      DelayedOverrideCheck.check (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2153:13)
#10     SourceLoader.checkOverrides (package:front_end/src/fasta/source/source_loader.dart:918:25)
#11     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:277:14)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#13     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:250:12)
#14     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:125:28)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#16     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#17     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#18     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#19     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#20     new Future.sync (dart:async/future.dart:224:31)
#21     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1465:12)
#26     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#27     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#28     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#29     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#30     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:338:17)
#31     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:162:45)
#32     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#33     _rootRun (dart:async/zone.dart:1122:38)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#37     _rootRun (dart:async/zone.dart:1126:13)
#38     _CustomZone.run (dart:async/zone.dart:1023:19)
#39     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#40     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#41     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#42     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)


#0      Types.performNullabilityAwareSubtypeCheck (package:front_end/src/fasta/kernel/types.dart:221:7)
#1      Types.areTypeArgumentsOfSubtypeKernel (package:front_end/src/fasta/kernel/types.dart:247:29)
#2      IsInterfaceSubtypeOf.isInterfaceRelated (package:front_end/src/fasta/kernel/types.dart:358:10)
#3      Types.performNullabilityAwareSubtypeCheck (package:front_end/src/fasta/kernel/types.dart:112:26)
#4      Types.isSubtypeOfKernel (package:front_end/src/fasta/kernel/types.dart:50:26)
#5      ClassBuilderImpl._checkTypes (package:front_end/src/fasta/builder/class_builder.dart:1486:15)
#6      ClassBuilderImpl.checkGetterOverride (package:front_end/src/fasta/builder/class_builder.dart:1719:5)
#7      ClassBuilderImpl.checkOverride (package:front_end/src/fasta/builder/class_builder.dart:1098:9)
#8      DelayedOverrideCheck.check.callback (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2060:20)
#9      DelayedOverrideCheck.check (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2153:13)
#10     SourceLoader.checkOverrides (package:front_end/src/fasta/source/source_loader.dart:918:25)
#11     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:277:14)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#13     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:250:12)
#14     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:125:28)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#16     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#17     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#18     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#19     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#20     new Future.sync (dart:async/future.dart:224:31)
#21     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1465:12)
#26     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#27     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#28     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#29     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#30     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:338:17)
#31     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:162:45)
#32     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#33     _rootRun (dart:async/zone.dart:1122:38)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#37     _rootRun (dart:async/zone.dart:1126:13)
#38     _CustomZone.run (dart:async/zone.dart:1023:19)
#39     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#40     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#41     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#42     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

The test package I'm using is test: 1.9.4
```
test:file:///Users/kylewong/.pub-cache/hosted/pub.flutter-io.cn/test-1.9.4/lib/
test_api:file:///Users/kylewong/.pub-cache/hosted/pub.flutter-io.cn/test_api-0.2.11/lib/
test_core:file:///Users/kylewong/.pub-cache/hosted/pub.flutter-io.cn/test_core-0.2.15/lib/
```

The flutter doctor -v output is:
```shell
kylewong@KyleWongdeMacBook-Pro aspectd % flutter doctor -v
[✓] Flutter (Channel master, v1.12.3-pre.48, on Mac OS X 10.15.1 19B88, locale en-CN)
    • Flutter version 1.12.3-pre.48 at /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
    • Framework revision 802bd5514f (11 hours ago), 2019-11-17 11:11:51 -0500
    • Engine revision 4da0645df1
    • Dart version 2.7.0
```
The corresponding dart sdk revision is: 8617da2bf0b840608850fd66e8f3a859c493770c

@mraleph

**Comment by stefantsov** [comment]
@mraleph Nope, it's a new one :)  I'll take a look.

**Comment by stefantsov** [comment]
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/125268/.  I'm currently confirming that it fixes the reported crash.

**Comment by stefantsov** [comment]
It seems that I can't reproduce the original issue without the test file itself, but the test case in the proposed CL crashes with a similar stack trace to the reported one.  So, the proposed fix might fix the original issue as well.

**Comment by stefantsov** [comment]
The CL has landed: https://github.com/dart-lang/sdk/commit/203583b41b58213a2148e7134ab3e3330850511a.  @kangwang1988 could you confirm that the command doesn't crash on Dart SDK revision 203583b41b58213a2148e7134ab3e3330850511a or later?
