### ISSUE TITLE
lib_2/isolate/message_const_type_arguments_2_test fails with bytecode and app-jit snapshot

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#39435]
Repro:
```
rm -rf out
tools/gn.py -m release -a x64 --bytecode
tools/build.py -a x64 -m release runtime
tools/test.py -n app_jitk-linux-release-x64 lib_2/isolate/message_const_type_arguments_2_test
```

```
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:665:5)
#1      Expect.isTrue (package:expect/expect.dart:135:5)
#2      main (file:///.../tests/lib_2/isolate/message_const_type_arguments_2_test.dart:145:10)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

It starts failing since 20962e656be0507de52440bdab43e65e59720ba1.
/cc @mkustermann @rmacnak-google

**Comment by mkustermann** [comment]
Since it seemingly started with my commit, I can take a look.

Will see if it was actually caused by that CL or is something else. I vaguely remember having seen this particular failure before somewhere.

**Comment by alexmarkov** [comment]
Bytecode mode is removed from Dart VM.
