### ISSUE TITLE
creating a mock class

### ISSUE THREAD

**Issue by GitHubStuff** [dart-lang/sdk#39452]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 2560x1440, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/steven/Downloads/AtmosBlocV2/lib/screens/login_screen.dart context: exception_20191119_162349_078
Exception: Element not found in summary: package:flutter_template/server_side/api_helper.dart;package:flutter_template/server_side/api_helper.dart;ApiResponse
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:338:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:359:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:34:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:116:29)
#4      _ReferenceInfo._buildType.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:1043:48)
#5      InterfaceTypeImpl.typeArguments (package:analyzer/src/dart/element/type.dart:1600:26)
#6      InterfaceTypeImpl.substitute2 (package:analyzer/src/dart/element/type.dart:2264:34)
#7      _FunctionTypeImplStrict.substitute2.transformType (package:analyzer/src/dart/element/type.dart:3690:13)
#8      _FunctionTypeImplStrict.substitute2.transformParameter (package:analyzer/src/dart/element/type.dart:3699:34)
#9      _transformOrShare (package:analyzer/src/dart/element/type.dart:29:32)
#10     _FunctionTypeImplStrict.substitute2 (package:analyzer/src/dart/element/type.dart:3709:25)
#11     _FunctionTypeImplStrict.instantiate.transformParameter (package:analyzer/src/dart/element/type.dart:3643:26)
#12     _transformOrShare (package:analyzer/src/dart/element/type.dart:29:32)
#13     _FunctionTypeImplStrict.instantiate (package:analyzer/src/dart/element/type.dart:3656:9)
#14     MethodInvocationResolver._instantiateFunctionType (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:203:27)
#15     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:763:30)
#16     MethodInvocationResolver._resolveReceiverInterfaceType (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:482:14)
#17     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:127:7)
#18     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:549:31)
#19     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
#20     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:4219:10)
#21     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
#22     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3770:18)
#23     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#24     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3214:59)
#25     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3766:49)
#26     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#27     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#28     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#29     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#30     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:5171:13)
#31     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#32     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#33     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#34     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3131:55)
#35     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5182:13)
#36     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:3508:13)
#37     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#38     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5085:12)
#39     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#40     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3263:57)
#41     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5533:15)
#42     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:4021:13)
#43     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5079:49)
#44     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#45     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#46     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3345:51)
#47     ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:4252:11)
#48     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:...
```

For additional log information, please append the contents of
file:///private/var/folders/kq/qd9zc3ld16q0kx6l8l666qt40000gn/T/report.txt.

**Comment by srawlins** [comment]
This is an issue likely fixed by a new version of summaries, Summary2. Please upgrade Dart to version 2.6.0, and re-open if this issue occurs again.
