### ISSUE TITLE
Error: ProcessException: %1 is not a valid Win32 application. Trying to connect to Flutter-Dart VM using vm_service.

### ISSUE THREAD

**Issue by rubencg195** [dart-lang/sdk#39455]
## Description

1. I am trying to run flutter and connect to the dart VM using the vm_service dart library but first I am trying to test running Flutter from Dart. When I run a simple **_flutter --version_**  command from Dart **_Process.start_** function, it gives the following error. This issue was created because it was closed on the flutter GitHub due to be a dart-specific issue.  https://github.com/flutter/flutter/issues/45114

**_ProcessException: %1 is not a valid Win32 application._**

2. Also, how can I trigger hot reload/restart using this library?

## Steps to Reproduce

The commands that fail are the following:

```
ProcessResult process2 = await Process.run('${flutterSDK}/flutter', [
    '--version',
]);
```

```
Process process = await Process.start('${flutterSDK}/flutter', [
    '--version', 
]);
```

The complete code is the following:

```
library service_tester;
import 'dart:async';
import 'dart:collection';
import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as path;
import 'package:pedantic/pedantic.dart';
import 'package:vm_service/vm_service.dart';
import 'package:vm_service/vm_service_io.dart';
// import 'package:test/test.dart';

final String host = 'localhost';
final int port = 7575;
VmService serviceClient;

void main() async {
  Directory current = Directory.current;
  String sdk = path.dirname(path.dirname(Platform.resolvedExecutable));
  String flutterSDK = "C:/flutter/bin";

  print('Using sdk at ${sdk}.');
  print('Directory ${current.path}.');
  
  //FAILS
  ProcessResult process2 = await Process.run('${flutterSDK}/flutter', [
    '--version',
  ]);

  //FAILS
  Process process = await Process.start('${flutterSDK}/flutter', [
    '--version',
  ]);

  print('dart process started');
  process.exitCode.then((code) => print('vm exited: ${code}'));
  process.stdout.transform(utf8.decoder).listen(print);
  process.stderr.transform(utf8.decoder).listen(print);
}
```

**Target Platform:** Windows 10
**Target OS version/browser:**  Version	10.0.18362 Build 18362
**Devices:** No device

Flutter 1.10.6-pre.29 • channel unknown • unknown source
Framework • revision 919cc97f6a (8 weeks ago) • 2019-09-20 14:57:05 -0700
Engine • revision 99092a0436
Tools • Dart 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)

## Logs

```
Using sdk at C:\Program Files\Dart\dart-sdk.
Directory C:\Users\xxxx\Documents\Github\demo
CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:/flutter/bin/flutter --version
#0      main (file:///C:/Users/xxxx/Documents/Github/demo/testingDartVM.dart:35:28)
<asynchronous suspension>
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```

Here is are the logs from `flutter doctor -v`

```
[√] Flutter (Channel unknown, v1.10.6-pre.29, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.10.6-pre.29 at C:\flutter
    • Framework revision 919cc97f6a (9 weeks ago), 2019-09-20 14:57:05 -0700
    • Engine revision 99092a0436
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = C:\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\ruben\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 78.0.3904.97
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by liudonghua123** [comment]
Recently, I run into the same error. See https://github.com/dart-lang/sdk/issues/37751#issuecomment-800369852.

**Comment by sortie** [comment]
Does it work if you pass `runInShell: true` to `Process.run`? The file called `flutter` is a Unix script and on Windows you want to invoke `flutter.bat` through your Windows shell. The main problem I think I see here is that the Windows error message didn't have the %1 substituted.

Your Flutter and Dart versions appear to be a good bit old btw.

**Comment by liudonghua123** [comment]
@sortie Thanks, I was running/debugging https://github.com/dart-lang/dart-pad and https://github.com/dart-lang/dart-services. And I think the flutter(2.0.1)/dart(1.12.0) is not old currently.

Passing `runInShell: true` seems works now.

**Comment by dcharkes** [comment]
Note to self: I got this error forgetting to pass in `.bat` after `bin/dart` the Flutter context as well.

Thanks @sortie for the hint.
