### ISSUE TITLE
There are no highlights of any error.

### ISSUE THREAD

**Issue by apalmeira** [dart-lang/sdk#39480]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.6.1`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1440x900, 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.1, server version 1.27.3, error: Analysis failed: /Users/agustinpalmeira/Documents/Projects/obtaincare/consumer-mobile-tool/obtain_care/test/widget_test.dart context: exception_20191121_123158_020
Bad state: No definition of type String
#0      TypeProviderImpl._getClassElement (package:analyzer/src/dart/element/type_provider.dart:410:7)
#1      TypeProviderImpl._getType (package:analyzer/src/dart/element/type_provider.dart:418:19)
#2      TypeProviderImpl.stringType (package:analyzer/src/dart/element/type_provider.dart:317:21)
#3      StaticTypeAnalyzer.visitSimpleStringLiteral (package:analyzer/src/generated/static_type_analyzer.dart:1155:56)
#4      SimpleStringLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:9159:49)
#5      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4335:10)
#6      UnifyingAstVisitor.visitSimpleStringLiteral (package:analyzer/dart/ast/visitor.dart:3413:59)
#7      SimpleStringLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:9159:49)
#8      AstResolver.resolve (package:analyzer/src/summary2/ast_resolver.dart:70:10)
#9      ConstantInitializersResolver._resolveVariable (package:analyzer/src/summary2/top_level_inference.dart:95:21)
#10     ConstantInitializersResolver._resolveClassFields (package:analyzer/src/summary2/top_level_inference.dart:70:7)
#11     List.forEach (dart:core-patch/growable_array.dart:283:8)
#12     ConstantInitializersResolver.perform (package:analyzer/src/summary2/top_level_inference.dart:55:20)
#13     Linker._resolveConstantInitializers (package:analyzer/src/summary2/link.dart:225:40)
#14     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:104:5)
#15     Linker.link (package:analyzer/src/summary2/link.dart:83:5)
#16     link (package:analyzer/src/summary2/link.dart:35:10)
#17     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:183:26)
#18     SetMixin.forEach (dart:collection/set.dart:146:30)
#19     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:138:32)
#20     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:235:17)
#21     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#22     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:233:12)
#23     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:84:5)
#24     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1439:29)
#25     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:30)
#26     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#27     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1237:20)
#28     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1067:33)
<asynchronous suspension>
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1926:24)
<asynchronous suspension>
#30     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1860:5)
#31     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#32     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#33     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#34     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:575:21)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:694:12)
#40     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:573:7)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#42     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#43     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#44     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#45     new Future.sync (dart:async/future.dart:224:31)
#46     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#47     _rootRun (dart:async/zone.dart:1124:13)
#48     _CustomZone.run (dart:async/zone.dart:1021:19)
#49     _runZoned (dart:async/zone.dart:1516:10)
#50     runZoned (dart:async/zone.dart:1463:12)
#51     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#52     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:142:56)
#53     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#54     main (file:///b/...
```

For additional log information, please append the contents of
file:///private/var/folders/l_/j7mzmh752qgdpnd0nfmbf9xr0000gn/T/report.txt.

**Comment by Niggelgame** [comment]
Hey, I am currently having the same issue - would it be possible to share us how you fixed it? (If you could get it to work again)

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.6.1. Please re-open if you see this crash again.
