### ISSUE TITLE
Analyzer gives `Missing library` when loading files via configurable import

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#39509]
I am trying to make the pana platform analysis robust in the presence of configurable imports,
My idea is to do the analysis once for each platform with the right DeclaredVariables set for that platform.

But it seems that the Analyzer is not able to find the files that are loaded as the conditional part of an import:
```dart
import 'package:analyzer/dart/analysis/context_builder.dart';
import 'package:analyzer/dart/analysis/context_locator.dart';
import 'package:analyzer/dart/analysis/declared_variables.dart';

main() async {
  final analysisContext = ContextBuilder().createContext(
    contextRoot:
        ContextLocator().locateRoots(includedPaths: ['example/']).first,
    sdkPath: '/usr/local/google/home/sigurdm/Downloads/dart-sdk',
    declaredVariables: DeclaredVariables.fromMap({'dart.library.html': 'true'}),
  );
  print((await analysisContext.currentSession
          .getLibraryByUri('package:example/main.dart'))
      .imports);
}
```

```
Unhandled exception:
Invalid argument(s): Missing library: package:example/helper_web.dart
Available libraries: [dart:async, dart:collection, dart:convert, dart:core, dart:_internal, dart:math, dart:typed_data, package:example/helper_stub.dart, package:example/main.dart]
#0      _ElementRequest._createLibraryElement (package:analyzer/src/summary2/linked_element_factory.dart:292:7)
#1      _ElementRequest.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:147:14)
#2      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:72:45)
#3      LinkedElementFactory.libraryOfUri (package:analyzer/src/summary2/linked_element_factory.dart:104:12)
#4      LinkedUnitContext.directiveLibrary (package:analyzer/src/summary2/linked_unit_context.dart:137:41)
#5      ImportElementImpl.importedLibrary (package:analyzer/src/dart/element/element.dart:5050:47)
#6      LibraryElementImpl.imports.<anonymous closure> (package:analyzer/src/dart/element/element.dart:5482:23)
#7      ListMixin.any (dart:collection/list.dart:130:15)
#8      LibraryElementImpl.imports (package:analyzer/src/dart/element/element.dart:5481:30)
#9      LibraryImportScope._createImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:509:52)
#10     new LibraryImportScope (package:analyzer/src/dart/resolver/scope.dart:403:5)
#11     new LibraryScope (package:analyzer/src/dart/resolver/scope.dart:619:19)
#12     LibraryBuilder.buildElement (package:analyzer/src/summary2/library_builder.dart:212:13)
#13     Linker._computeLibraryScopes (package:analyzer/src/summary2/link.dart:170:15)
#14     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:97:5)
#15     Linker.link (package:analyzer/src/summary2/link.dart:83:5)
#16     link (package:analyzer/src/summary2/link.dart:35:10)
#17     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:183:26)
#18     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:235:17)
#19     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#20     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:233:12)
#21     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:84:5)
#22     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1439:29)
#23     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1380:28)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#25     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1378:20)
#26     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:999:34)
<asynchronous suspension>
#27     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1926:24)
<asynchronous suspension>
#28     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1860:5)
#29     ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:77:17)
#30     main (package:analyzer_configurable_imports/analyze.dart:6:44)
<asynchronous suspension>
#31     main (file:///usr/local/google/home/sigurdm/projects/analyzer_configurable_imports/bin/main.dart:3:11)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

`example/main.dart` looks like this:
```dart
import 'helper_stub.dart' if (dart.library.html) "helper_web.dart";
```
And both `helper_stub.dart` and `helper_web.dart` exists in the file system.

I have made a small reproducing example available:
https://github.com/sigurdm/analyzer_configurable_imports

`dart --version`: `Dart VM version: 2.7.0-dev.0.0 (Tue Nov 5 12:57:33 2019 +0100) on "linux_x64"`
Analyzer version: "0.39.1"

**Comment by sigurdm** [comment]
cc @stereotype441

**Comment by stereotype441** [comment]
@scheglov can you look into this?  It looks like a bug in summaries

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/126440
