### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by Yangzhuren** [dart-lang/sdk#39511]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 1280x800, 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/yangxian/work/flutter/flutter_base_components/lib/ui/list/index.dart context: exception_20191125_170131_056
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ScopedVisitor.visitFunctionTypedFormalParameter (package:analyzer/src/generated/resolver.dart:5562:84)
#2      FunctionTypedFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:5340:15)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#4      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4555:17)
#5      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3354:10)
#6      UnifyingAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:3243:59)
#7      ScopedVisitor.visitFormalParameterList (package:analyzer/src/generated/resolver.dart:5440:11)
#8      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4551:49)
#9      GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5465:18)
#10     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3354:10)
#11     UnifyingAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:3277:59)
#12     ScopedVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:5598:15)
#13     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5458:20)
#14     GenericTypeAliasImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5545:20)
#15     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3354:10)
#16     UnifyingAstVisitor.visitGenericTypeAlias (package:analyzer/dart/ast/visitor.dart:3280:53)
#17     ScopedVisitor.visitGenericTypeAlias (package:analyzer/src/generated/resolver.dart:5617:15)
#18     GenericTypeAliasImpl.accept (package:analyzer/src/dart/ast/ast.dart:5537:20)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#20     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#21     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3354:10)
#22     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:3158:51)
#23     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#24     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:660:10)
#25     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#26     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#27     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#28     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#29     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#30     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#31     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#32     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#33     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#34     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
<asynchronous suspension>
#35     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#36     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#37     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#38     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#39     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#40     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#46     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#47     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#48     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#49     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#50     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#51     new Future...
```

For additional log information, please append the contents of
file:///private/var/folders/v5/lj_nkkjx53q5hfg6r4tr83z40000gn/T/report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.5.0. Please re-open if you see this crash again.
