### ISSUE TITLE
The `service/verify_http_timeline_test` tests seems to be failing sometimes

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#39568]
From [this build](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-linux-release-simarm64/7317):
```

/==============================================================================\
| service/verify_http_timeline_test failed again (RuntimeError, expected Pass) |
\==============================================================================/

--- Command "vm_compile_to_kernel []" (took 05.000608s):
DART_CONFIGURATION=ReleaseSIMARM64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=out/ReleaseSIMARM64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartk/runtime_observatory_tests_service_verify_http_timeline_test/out.dill /b/s/w/ir/runtime/observatory/tests/service/verify_http_timeline_test.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 04.000462s):
DART_CONFIGURATION=ReleaseSIMARM64 out/ReleaseSIMARM64/dart --timeline_streams=Dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartk/runtime_observatory_tests_service_verify_http_timeline_test/out.dill

exit code:
255

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseSIMARM64/dart --write-service-info=file:///b/s/w/itH97g4S/dart_serviceZACHZC/service_info.json --profiler --timeline_streams=Dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages --enable-vm-service:0 /b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartk/runtime_observatory_tests_service_verify_http_timeline_test/out.dill
>testee>out> Observatory listening on http://127.0.0.1:37739/abXJ_iiVAzA=/
>testee>err> Unhandled exception:
>testee>err> OS Error: Connection reset by peer, errno = 104
>testee>err> #0      testMain.<anonymous closure> (file:///b/s/w/ir/runtime/observatory/tests/service/verify_http_timeline_test.dart:96:17)
>testee>err> <asynchronous suspension>
>testee>err> #1      executeWithRandomDelay.<anonymous closure> (file:///b/s/w/ir/runtime/observatory/tests/service/verify_http_timeline_test.dart:46:16)
>testee>err> #2      _RootZone.runUnary (dart:async/zone.dart:1381:54)
>testee>err> #3      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
>testee>err> #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
>testee>err> #5      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
>testee>err> #6      Future._complete (dart:async/future_impl.dart:516:7)
>testee>err> #7      new Future.delayed.<anonymous closure> (dart:async/future.dart:313:16)
>testee>err> #8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
>testee>err> #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
>testee>err> #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
>testee>err> #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
** Killing script
Unexpected exception in service tests: Testee exited with 255
#0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/runtime/observatory/tests/service/test_helper.dart:244:11)
<asynchronous suspension>
#1      _rootRunUnary (dart:async/zone.dart:1134:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#8      _rootRun (dart:async/zone.dart:1126:13)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

stderr:
Unhandled exception:
Testee exited with 255
#0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/runtime/observatory/tests/service/test_helper.dart:244:11)
<asynchronous suspension>
#1      _rootRunUnary (dart:async/zone.dart:1134:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#8      _rootRun (dart:async/zone.dart:1126:13)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

--- Re-run this test:
python tools/test.py -n dartk-linux-release-simarm64 service/verify_http_timeline_test
```

/cc @bkonyi

**Comment by mkustermann** [comment]
I'll approve this failure:


| BOT                              | TEST                              | RESULT       | EXPECTED | 
| -------------------------------- | --------------------------------- | ------------ | -------- | 
| vm-kernel-linux-release-simarm64 | service/verify_http_timeline_test | RuntimeError | Pass     |

**Comment by sstrickl** [comment]
Am approving this failure:

| BOT                                  | TEST                              | RESULT       | EXPECTED | 
| ------------------------------------ | --------------------------------- | ------------ | -------- | 
| vm-kernel-ast-linux-release-simarm64 | service/verify_http_timeline_test | RuntimeError | Pass     |

Since `executeWithRandomDelay` already ignores other exceptions that might happen due to the random delay, my guess is that OSError just needs to be added to this. Will send Ben a CL to review with this change.
