### ISSUE TITLE
Auto generated error report

### ISSUE THREAD

**Issue by duzenko** [dart-lang/sdk#39635]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_212-b04x32 , OS Windows 10(x86) v10.0 , screens 3840x2160, 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: Failed to handle request: {id: 16184, method: edit.getFixes, params: {file: D:\dev\pavement\lib\map\mapEntities.dart, offset: 2419}, clientRequestTime: 1575460921123}
NoSuchMethodError: The method 'endsWith' was called on null.
Receiver: null
Tried calling: endsWith("es")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      DartEditBuilderImpl._getBaseNameFromUnwrappedExpression (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:868:16)
#2      DartEditBuilderImpl._getBaseNameFromExpression (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:814:12)
#3      DartEditBuilderImpl._getVariableNameSuggestionsForExpression (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:934:11)
#4      DartEditBuilderImpl._getParameterNameSuggestions (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:916:9)
#5      DartEditBuilderImpl.writeParameterMatchingArgument (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:604:11)
#6      DartEditBuilderImpl.writeParametersMatchingArguments (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:671:7)
#7      FixProcessor._addFix_undefinedMethod_create.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/correction/fix_internal.dart:3846:19)
#8      DartFileEditBuilderImpl.addInsertion.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1179:41)
#9      FileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:312:16)
#10     DartFileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1178:13)
#11     FixProcessor._addFix_undefinedMethod_create.<anonymous closure> (package:analysis_server/src/services/correction/fix_internal.dart:3828:17)
#12     DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:56:20)
#13     ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#14     DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:53:18)
#15     FixProcessor._addFix_undefinedMethod_create (package:analysis_server/src/services/correction/fix_internal.dart:3826:27)
<asynchronous suspension>
#16     FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:538:13)
<asynchronous suspension>
#17     DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#18     EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:651:46)
<asynchronous suspension>
#19     EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:757:14)
<asynchronous suspension>
#20     EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:280:32)
<asynchronous suspension>
#21     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:383:9)
#22     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#30     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#31     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#32     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#33     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#41     _StringAdapterSink.add (dart:convert/string_conver...
```

For additional log information, please append the contents of
file://T:\_sys\report.txt.

**Comment by srawlins** [comment]
Apologies that we didn't get a chance to investigate this issue before it became stale. Please re-open if you see this on a recent version of Dart.
