### ISSUE TITLE
run ffi sqlite sample failed 

### ISSUE THREAD

**Issue by netroby** [dart-lang/sdk#39679]
```
PS D:\workspace\netroby\dart-sdk\samples\ffi\sqlite> pub run .\example\main.dart
Unhandled exception:
Invalid argument(s): Failed to load dynamic library (126)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      dlopenPlatformSpecific (file:///D:/workspace/netroby/dart-sdk/samples/ffi/sqlite/lib/src/ffi/dylib_utils.dart:19:25)
#3      new _SQLiteBindings (file:///D:/workspace/netroby/dart-sdk/samples/ffi/sqlite/lib/src/bindings/bindings.dart:332:14)
#4      bindings (file:///D:/workspace/netroby/dart-sdk/samples/ffi/sqlite/lib/src/bindings/bindings.dart:394:53)
#5      new Database (file:///D:/workspace/netroby/dart-sdk/samples/ffi/sqlite/lib/src/database.dart:33:9)
#6      main (file:///D:/workspace/netroby/dart-sdk/samples/ffi/sqlite/example/main.dart:8:16)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

my dart version

```
PS D:\workspace\netroby\dart-sdk\samples\ffi\sqlite> dart --version
Dart VM version: 2.7.0-dev.2.1 (Mon Dec 2 20:10:59 2019 +0100) on "windows_x64"
PS D:\workspace\netroby\dart-sdk\samples\ffi\sqlite> pub version
Pub 2.7.0-dev.2.1
```

**Comment by dcharkes** [comment]
Hey @netroby, I see you've already made it work.

Would you like to contribute your patch? (See [contributing.md](https://github.com/dart-lang/sdk/blob/master/CONTRIBUTING.md).)

**Comment by netroby** [comment]
@dcharkes see https://github.com/dart-lang/sdk/pull/39680
