### ISSUE TITLE
Getting problem in creating new project

### ISSUE THREAD

**Issue by saur099** [dart-lang/sdk#39715]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: Analysis failed: C:\Users\Dell\AndroidStudioProjects\gold_app\lib\main.dart context: exception_20191209_132834_051
FileSystemException: Exists failed, path = 'C:\Users\Dell\AndroidStudioProjects\gold_app\lib\READONLY' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:99:7)
#1      _PhysicalResource.exists (package:analyzer/file_system/physical_file_system.dart:369:29)
#2      _OverlayFolder.exists (package:analyzer/file_system/overlay_file_system.dart:284:32)
#3      BazelWorkspace.find (package:analyzer/src/workspace/bazel.dart:312:26)
#4      ContextBuilder.createWorkspace (package:analyzer/src/context/builder.dart:678:42)
#5      new BestPracticesVerifier (package:analyzer/src/generated/resolver.dart:316:24)
#6      LibraryAnalyzer._computeHints (package:analyzer/src/dart/analysis/library_analyzer.dart:249:21)
#7      LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:166:11)
#8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#9      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:165:15)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#11     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:151:35)
#12     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:14)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:43)
#15     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1450:63)
#16     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#17     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1427:20)
#18     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1227:17)
<asynchronous suspension>
#19     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2160:24)
<asynchronous suspension>
#20     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2090:5)
#21     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#22     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#23     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#24     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#30     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#31     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#32     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#33     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#34     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\Dell\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Dart 2.3.0 was released over 6 months ago; please upgrade Dart (or Flutter) to a recent version. Feel free to re-open this issue if it occurs again.
