### ISSUE TITLE
dartanalyzer crashes "Bad state: Members must be created from a declarations."

### ISSUE THREAD

**Issue by leisim** [dart-lang/sdk#39752]
Analyzing the following code using `dartanalyzer example.dart` crashes the analyzer:

```dart
void test<T>(T value) {
  if (value is num) {
    if (value is int) {}
  }
}
```

Error message: "Bad state: Members must be created from a declarations."

<details>
<summary>Stacktrace</summary>

```
Analyzing example.dart...
Loaded analysis options from C:\Users\...\analysis_options.yaml
Unhandled exception:
Bad state: Members must be created from a declarations.
#0      new Member (package:analyzer/src/dart/element/member.dart:434:7)
#1      new TypeParameterMember (package:analyzer/src/dart/element/member.dart:1051:9)
#2      Dart2TypeSystem.tryPromoteToType (package:analyzer/src/generated/type_system.dart:1450:26)
#3      TypePromotionManager._promote (package:analyzer/src/generated/type_promotion_manager.dart:253:42)
#4      TypePromotionManager._promoteTypes (package:analyzer/src/generated/type_promotion_manager.dart:273:9)
#5      TypePromotionManager.visitIfStatement_thenStatement (package:analyzer/src/generated/type_promotion_manager.dart:114:9)
#6      ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:3867:23)
#7      IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5622:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7511:20)
#9      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4033:10)
#11     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#12     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:4964:13)
#13     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:5506:7)
#14     ResolverVisitor.visitIfStatement.<anonymous closure> (package:analyzer/src/generated/resolver.dart:3871:11)
#15     TypePromotionManager.visitIfStatement_thenStatement (package:analyzer/src/generated/type_promotion_manager.dart:119:10)
#16     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:3867:23)
#17     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5622:49)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7511:20)
#19     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#20     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4033:10)
#21     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#22     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:4964:13)
#23     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#24     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1042:13)
#25     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4033:10)
#26     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3131:55)
#27     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:4975:13)
#28     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:3206:13)
#29     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#30     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4968:12)
#31     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4033:10)
#32     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3263:57)
#33     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5300:13)
#34     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3782:13)
#35     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4962:49)
#36     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4825:26)
#37     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4033:10)
#38     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3256:59)
#39     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5293:11)
#40     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:3754:11)
#41     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5286:7)
#42     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:3736:13)
#43     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4818:49)
#44     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:3291:23)
#45     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2091:49)
#46     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:717:10)
#47     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:153:7)
#48     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#49     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:152:11)
#50     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#51     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#52     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#53     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1275:63)
#54     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#55     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1251:20)
#56     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:548:41)
<asynchronous suspension>
#57     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:58)
<asynchronous suspension>
#58     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#59     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#60     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:705:21)
#61     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:364:40)
#62     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#63     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#65     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#66     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:389:9)
#67     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#68     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#69     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1311:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1251:20)
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:548:41)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:58)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:705:21)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:364:40)
#9      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:389:9)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

</details>

This bug is a big problem for me because it gives my package a huge pana penalty on pub.dev.

Dart VM version: 2.7.0 (Mon Dec 2 20:10:59 2019 +0100) on "windows_x64"

**Comment by vsmenon** [comment]
Thanks, I can repro this crash on (command line dartanalyzer without flags and with the example above):

 2.8.0-edge.a17884aff0db71c63736aabb6ab527e41ed563e6

fyi @stereotype441 - stack trace looks like type promotion problem.

**Comment by stereotype441** [comment]
@scheglov would you mind taking a look at this?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/128240

**Comment by leisim** [comment]
@scheglov Thank you for the fast fix. How long do you think will it take until this fix arrives on pub.dev?

**Comment by scheglov** [comment]
It will probably take some time to publish new `analyzer` and for `pana` to start using it. @kevmoo @stereotype441
