### ISSUE TITLE
[dart:io] socket endian changes broke mac tests

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#39782]
d30be47a2064c023aa5d31e12480536e22912ca7 [dart:io] RawSocketOption.fromInt should follow the same endian as host

dartk...
Pass -> RuntimeError (expected Pass)
standalone_2/io/raw_datagram_socket_test

```
/======================================================================================\
| standalone_2/io/raw_datagram_socket_test broke (Pass -> RuntimeError, expected Pass) |
\======================================================================================/

--- Command "vm" (took 868ms):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/io/raw_datagram_socket_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
OS Error: Can't assign requested address, errno = 49
#0      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1194:25)
#1      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2088:56)
#2      testDatagramSocketMulticastIf.test (file:///b/s/w/ir/tests/standalone_2/io/raw_datagram_socket_test.dart:134:12)
<asynchronous suspension>
#3      testDatagramSocketMulticastIf (file:///b/s/w/ir/tests/standalone_2/io/raw_datagram_socket_test.dart:148:7)
#4      main (file:///b/s/w/ir/tests/standalone_2/io/raw_datagram_socket_test.dart:399:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

--- Re-run this test:
python tools/test.py -n dartk-mac-release-x64 standalone_2/io/raw_datagram_socket_test
```

Related bug: https://github.com/dart-lang/sdk/issues/39691.

Approving failures to turn bot green.

**Comment by a-siva** [comment]
This CL https://dart-review.googlesource.com/c/sdk/+/128367 fixes the Mac test issue.
