### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by cjamcu** [dart-lang/sdk#39805]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.2, screens 1280x800`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: Failed to handle request: {id: 14587, method: flutter.getWidgetDescription, params: {file: /Users/cjamcu/AndroidStudioProjects/movies/movies/lib/search/search_delegate.dart, offset: 485}}
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:182:7)
#1      AnalysisSessionImpl.getLibraryByUri (package:analyzer/src/dart/analysis/session.dart:100:5)
<asynchronous suspension>
#2      AnalysisSessionHelper.getClass (package:analyzer/src/dart/analysis/session_helper.dart:27:40)
<asynchronous suspension>
#3      _WidgetDescriptionComputer._fetchClassElements (package:analysis_server/src/services/flutter/widget_descriptions.dart:399:43)
<asynchronous suspension>
#4      _WidgetDescriptionComputer.compute (package:analysis_server/src/services/flutter/widget_descriptions.dart:146:11)
<asynchronous suspension>
#5      WidgetDescriptions.getDescription (package:analysis_server/src/services/flutter/widget_descriptions.dart:46:44)
<asynchronous suspension>
#6      FlutterDomainHandler.getWidgetDescription (package:analysis_server/src/flutter/flutter_domain.dart:39:33)
<asynchronous suspension>
#7      FlutterDomainHandler.handleRequest (package:analysis_server/src/flutter/flutter_domain.dart:67:9)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1500:12)
#15     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#27     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#28     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#29     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#30     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#31     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#40     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#41     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#42     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#43     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#45     _rootRunUnary (dart:async/zone.dart:1132:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#50     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#51     _StreamController._add (dart:async/stream_controller.dart:640:7)
#52     _StreamController.add (dart:async/stream_controller.dart:586:5)
#53     _So...
```

For additional log information, please append the contents of
file:///private/var/folders/cs/_sd2qzp157g72tgpx13hh3l40000gn/T/report1.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.5.0. Please re-open if you see this crash again.
