### ISSUE TITLE
DartkCrash : NoSuchMethodError: The getter 'single' was called on null

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#39817]
nnbd/static_errors/unchecked_use_of_nullable_test_199 fails with an error
```
Crash when compiling null,
at character offset null:
NoSuchMethodError: The getter 'single' was called on null.
Receiver: null
Tried calling: single
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      TypeEnvironment.forInElementType (package:kernel/type_environment.dart:12
6:28)
#2      RecursiveContinuationRewriter.visitForInStatement (package:kernel/transfo
rmations/continuation.dart:163:45)
#3      AsyncRewriterBase.visitForInStatement (package:kernel/transformations/con
tinuation.dart:929:13)
#4      ForInStatement.accept (package:kernel/ast.dart:4852:43)
#5      AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation
.dart:513:17)
#6      Block.accept (package:kernel/ast.dart:4572:43)
#7      AsyncRewriterBase.visitDelimited (package:kernel/transformations/continua
tion.dart:598:10)
#8      AsyncRewriterBase.buildWrappedBody (package:kernel/transformations/contin
uation.dart:474:24)
#9      AsyncRewriterBase.setupAsyncContinuations (package:kernel/transformations
/continuation.dart:426:39)
#10     AsyncFunctionRewriter.rewrite (package:kernel/transformations/continuatio
n.dart:1170:5)
#11     RecursiveContinuationRewriter.visitFunctionNode (package:kernel/transform
ations/continuation.dart:127:14)
#12     FunctionNode.accept (package:kernel/ast.dart:2541:38)
#13     Procedure.transformChildren (package:kernel/ast.dart:2195:27)
#14     Transformer.defaultTreeNode (package:kernel/visitor.dart:643:10)
#15     TreeVisitor.defaultMember (package:kernel/visitor.dart:230:35)
#16     TreeVisitor.visitProcedure (package:kernel/visitor.dart:232:39)
#17     RecursiveContinuationRewriter.visitProcedure (package:kernel/transformati
ons/continuation.dart:101:51)
#18     Procedure.accept (package:kernel/ast.dart:2182:40)
#19     transformList (package:kernel/ast.dart:7204:27)
#20     Library.transformChildren (package:kernel/ast.dart:572:5)
#21     Transformer.defaultTreeNode (package:kernel/visitor.dart:643:10)
#22     TreeVisitor.visitLibrary (package:kernel/visitor.dart:254:35)
#23     RecursiveContinuationRewriter.visitLibrary (package:kernel/transformation
s/continuation.dart:109:28)
#24     Library.accept (package:kernel/ast.dart:552:38)
#25     RecursiveContinuationRewriter.rewriteLibrary (package:kernel/transformati
ons/continuation.dart:81:17)
#26     transformLibraries (package:kernel/transformations/continuation.dart:39:1
4)
#27     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.d
art:155:5)
#28     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/
kernel_target.dart:825:19)
#29     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fa
sta/kernel/kernel_target.dart:311:7)
<asynchronous suspension>
#30     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#31     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_ta
rget.dart:301:12)
#32     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_
generator_impl.dart:149:38)
<asynchronous suspension>
#33     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#34     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:
70:10)
#35     generateKernel.<anonymous closure> (package:front_end/src/kernel_generato
r_impl.dart:50:18)
#36     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src
/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#37     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (pac
kage:front_end/src/fasta/compiler_context.dart:123:46)
#38     new Future.sync (dart:async/future.dart:224:31)
#39     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/f
asta/compiler_context.dart:123:19)
#40     _rootRun (dart:async/zone.dart:1126:13)
#41     _CustomZone.run (dart:async/zone.dart:1023:19)
#42     _runZoned (dart:async/zone.dart:1518:10)
#43     runZoned (dart:async/zone.dart:1465:12)
#44     CompilerContext.runInContext (package:front_end/src/fasta/compiler_contex
t.dart:122:12)
#45     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_cont
ext.dart:133:10)
#46     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#47     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dar
t:99:17)
#48     SingleShotCompilerWrapper.compileInternal (file:///usr/local/google/home/
asiva/workspace/dart-nnbd/sdk/pkg/vm/bin/kernel_service.dart:359:17)
#49     Compiler.compile.<anonymous closure> (file:///usr/local/google/home/asiva
/workspace/dart-nnbd/sdk/pkg/vm/bin/kernel_service.dart:163:45)
#50     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#51     _rootRun (dart:async/zone.dart:1122:38)
#52     _CustomZone.run (dart:async/zone.dart:1023:19)
#53     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#54     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart
:965:23)
#55     _rootRun (dart:async/zone.dart:1126:13)
#56     _CustomZone.run (dart:async/zone.dart:1023:19)
#57     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23
)
#58     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart
:23:15)
#59     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#60     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart
:174:12)

```

**Comment by stefantsov** [comment]
It appears to be not only an NNBD-related issue.  Here's the proposed fix: https://dart-review.googlesource.com/c/sdk/+/128664.
