### ISSUE TITLE
type '_Invocation' is not a subtype of type '_InvocationMirror' in type cast

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#39815]
nnbd/static_errors/unchecked_use_of_nullable_test_05 fails with the following error
`type '_Invocation' is not a subtype of type '_InvocationMirror' in type cast`

```
Unhandled exception:
type '_Invocation' is not a subtype of type '_InvocationMirror' in type cast
#0      new NoSuchMethodError.withInvocation (dart:core-patch/errors_patch.dart:190:34)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:15)
#2      main (file:///usr/local/google/home/asiva/workspace/dart-nnbd/sdk/out/DebugX64NNBD/generated_tests/language/nnbd/static_errors/unchecked_use_of_nullable_test_05.dart:20:5)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

**Comment by a-siva** [comment]
This is fixed.
