### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#39816]
nnbd/static_errors/unchecked_use_of_nullable_test_30 fails with the error
"Null check operator used on a null value"

```
Unhandled exception:
Null check operator used on a null value
#0      main (file:///usr/local/google/home/asiva/workspace/dart-nnbd/sdk/out/DebugX64NNBD/generated_tests/language/nnbd/static_errors/unchecked_use_of_nullable_test_30.dart:47:7)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

**Comment by leafpetersen** [comment]
The runtime behavior is correct, it looks like the test was designed with static behavior only in mind.  I will fix the test.

**Comment by leafpetersen** [comment]
https://dart-review.googlesource.com/c/sdk/+/128777
