### ISSUE TITLE
Error: The argument type 'Null' can't be assigned to the parameter type 'int'

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#39822]
language/nnbd/resolution/null_assertion_null_type_test fails with the error

```
tests/language/nnbd/resolution/null_assertion_null_type_test.dart:16:6: Error: The argument type 'Null' can't be assigned to the parameter type 'int'.
  f(n!);
     ^
```

**Comment by stefantsov** [comment]
Proposed fix for the CFE: https://dart-review.googlesource.com/c/sdk/+/128661/.  With that fix patched in, the program similar to one in the test case throws an exception as follows:

```
$ cat /tmp/asdf.dart
void f(int i) {
  print(i);
}

void g(Null n) {
   // Statically ok because `Never <: int`.  Throws at runtime.
  f(n!);
}

main() {
  g(null);
}
$ out/ReleaseX64NNBD/dart --enable-experiment=non-nullable /tmp/asdf.dart
Unhandled exception:
Null check operator used on a null value
#0      g (file:///tmp/asdf.dart:7:6)
#1      main (file:///tmp/asdf.dart:11:3)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```
