### ISSUE TITLE
Expect.type([null] is! List<int>) fails on Instance(length:1) of '_GrowableList'

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#39820]
nnbd/syntax/nullable_type_test fails with the following error

```
stderr:
Unhandled exception:
Expect.type([null] is! List<int>) fails on Instance(length:1) of '_GrowableList'
#0      Expect._fail (package:expect/expect.dart:665:5)
#1      Expect.notType (package:expect/expect.dart:632:5)
#2      main (file:///usr/local/google/home/asiva/workspace/dart-nnbd/sdk/tests/l
anguage/nnbd/syntax/nullable_type_test.dart:18:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:
307:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart
:174:12)

```

**Comment by leafpetersen** [comment]
This test looks correct to me.  Is it possible it is incorrectly being run in weak checking mode?  cc @munificent

**Comment by munificent** [comment]
If this test should only be run in strong checking mode, then adding this to the test:

```dart
// Requirements=nnbd-strong
```

Will cause to be automatically skipped on all weak-checking configurations.
