### ISSUE TITLE
Web: Flutter run failed "Error compiling dartdevc module"

### ISSUE THREAD

**Issue by alexfanchina** [dart-lang/sdk#39831]
When enabling flutter web and running through `flutter run -d chrome` it fails because of `Error compiling dartdevc module:syncfusion_flutter_charts|lib/charts.ddc.js`. Is there a quick fix to this?

## Version
System: macOS Catalina 10.15.2
```
Flutter 1.13.3-pre.44 • channel master • https://github.com/flutter/flutter.git
Framework • revision 86982e195e (5 hours ago) • 2019-12-17 11:07:26 -0500
Engine • revision bdd4e4d948
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 fe9f30c389)
```

## Log
```
[   +9 ms] Error compiling dartdevc module:syncfusion_flutter_charts|lib/charts.ddc.js

           packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:24:9: Error: Expected 0 type arguments.
             final Point<double> innerRadiusStartPoint = Point<double>(
                   ^^^^^
           packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:24:47: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
             final Point<double> innerRadiusStartPoint = Point<double>(
                                                         ^^^^^
           packages/syncfusion_flutter_charts/charts.dart:8:1: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
           import 'dart:ui';
           ^^^^^
           packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:27:9: Error: Expected 0 type arguments.
             final Point<double> innerRadiusEndPoint = Point<double>(
                   ^^^^^
           packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:27:45: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
             final Point<double> innerRadiusEndPoint = Point<double>(
                                                       ^^^^^
           packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:31:9: Error: Expected 0 type arguments.
             final Point<double> radiusStartPoint = Point<double>(
                   ^^^^^
           packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:31:42: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
             final Point<double> radiusStartPoint = Point<double>(
                                                    ^^^^^

[   +3 ms] AssetNotFoundException: syncfusion_flutter_charts|lib/charts.ddc.js
[        ] #0      bootstrapDdc (package:build_web_compilers/src/dev_compiler_bootstrap.dart:147:34)
           <asynchronous suspension>
           #1      FlutterWebEntrypointBuilder.build (package:flutter_tools/src/build_runner/build_script.dart:232:11)
           #2      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
           #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
           #4      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
           #5      Future.wait (dart:async/future.dart:393:26)
           #6      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
           #7      _rootRun (dart:async/zone.dart:1126:13)
           #8      _CustomZone.run (dart:async/zone.dart:1023:19)
           #9      _runZoned (dart:async/zone.dart:1518:10)
           #10     runZoned (dart:async/zone.dart:1502:12)
           #11     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
           #12     runBuilder (package:build/src/generate/run_builder.dart:61:9)
           #13     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:491:19)
           #14     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
           #15     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:489:23)
           <asynchronous suspension>
           #16     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #17     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:446:22)
           #18     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #19     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:442:17)
           #20     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:380:38)
           #21     MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
           #22     Future.wait (dart:async/future.dart:393:26)
           #23     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:379:36)
           #24     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:325:20)
           <asynchronous suspension>
           #25     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner_core/src/generate/performance_tracker.dart:184:15)
           #26     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:321:47)
           <asynchronous suspension>
           #27     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #28     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:315:32)
           #29     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
           #30     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:272:26)
           #31     _rootRun (dart:async/zone.dart:1126:13)
           #32     _CustomZone.run (dart:async/zone.dart:1023:19)
           #33     _runZoned (dart:async/zone.dart:1518:10)
           #34     runZoned (dart:async/zone.dart:1502:12)
           #35     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:267:5)
           #36     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:214:24)
           #37     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:97:56)
           #38     BuildRunnerDaemonBuilder.build (package:build_runner/src/daemon/daemon_builder.dart:111:35)
           #39     Server._build.<anonymous closure> (package:build_daemon/src/server.dart:122:25)
           #40     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #41     Server._build (package:build_daemon/src/server.dart:119:13)
           #42     Server.listen.<anonymous closure>.<anonymous closure> (package:build_daemon/src/server.dart:85:17)
           <asynchronous suspension>
           #43     _rootRunUnary (dart:async/zone.dart:1134:38)
           #44     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
           #48     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
           #49     _StreamController._add (dart:async/stream_controller.dart:649:7)
           #50     _StreamController.add (dart:async/stream_controller.dart:595:5)
           #51     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
           #52     _rootRunUnary (dart:async/zone.dart:1134:38)
           #53     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
           #57     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
           #58     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
           #59     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
           #60     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
           #61     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
           #62     _rootRunUnary (dart:async/zone.dart:1134:38)
           #63     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
           #67     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
           #68     _StreamController._add (dart:async/stream_controller.dart:649:7)
           #69     _StreamController.add (dart:async/stream_controller.dart:595:5)
           #70     _Socket._onData (dart:io-patch/socket_patch.dart:1873:41)
           #71     _rootRunUnary (dart:async/zone.dart:1138:13)
           #72     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #73     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #74     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #75     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
           #76     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
           #77     _StreamController._add (dart:async/stream_controller.dart:649:7)
           #78     _StreamController.add (dart:async/stream_controller.dart:595:5)
           #79     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1415:33)
           #80     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
           #81     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
           #82     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
           #83     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

[  +12 ms] Failed after 311ms
[  +15 ms] Building application for the web... (completed in 12.0s)
[   +1 ms] "flutter run" took 16,013ms.
Failed to build application for the Web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DwdsResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:660:7)
<asynchronous suspension>
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:529:37)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:33:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:292:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:33:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:292:13)
#23     IosProject.isSwift (package:flutter_tools/src/project.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#25     _rootRunUnary (dart:async/zone.dart:1134:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#31     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:33:15)
#32     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:292:13)
#33     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#34     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#35     _rootRunUnary (dart:async/zone.dart:1134:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#40     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:33:15)
#42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:292:13)
#43     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#44     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#45     _rootRunUnary (dart:async/zone.dart:1134:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#49     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#50     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#51     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:33:15)
#52     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:292:13)
#53     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#54     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#55     _rootRunUnary (dart:async/zone.dart:1134:38)
#56     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#57     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#58     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#59     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#60     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#61     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#62     _rootRunUnary (dart:async/zone.dart:1134:38)
#63     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#64     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#65     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#66     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#67     Future._complete (dart:async/future_impl.dart:516:7)
#68     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:207:14)
#69     _rootRun (dart:async/zone.dart:1122:38)
#70     _CustomZone.run (dart:async/zone.dart:1023:19)
#71     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#72     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#73     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:15)
#74     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:286:7)
#75     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#76     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#77     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#78     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#79     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#80     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#81     _rootRun (dart:async/zone.dart:1122:38)
#82     _CustomZone.run (dart:async/zone.dart:1023:19)
#83     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#84     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#85     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:15)
#86     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:286:7)
#87     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:781:19)
#88     _StreamController._closeUnchecked (dart:async/stream_controller.dart:638:7)
#89     _StreamController.close (dart:async/stream_controller.dart:631:5)
#90     _Socket._onData (dart:io-patch/socket_patch.dart:1880:21)
#91     _rootRunUnary (dart:async/zone.dart:1138:13)
#92     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#93     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#94     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#95     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#96     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#97     _StreamController._add (dart:async/stream_controller.dart:649:7)
#98     _StreamController.add (dart:async/stream_controller.dart:595:5)
#99     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1422:35)
#100    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:912:18)
#101    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#102    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#103    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#104    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by vsmenon** [comment]
@ferhatb @yjbanov 

Looks like there are colliding definitions of `Point` in `dart:math` and here:

https://github.com/flutter/engine/blob/708fc625d71567755b2d45483158f7bb1edb0ce4/lib/web_ui/lib/src/ui/geometry.dart#L1763

**Comment by alexfanchina** [comment]
> @ferhatb @yjbanov
> 
> Looks like there are colliding definitions of `Point` in `dart:math` and here:
> 
> https://github.com/flutter/engine/blob/708fc625d71567755b2d45483158f7bb1edb0ce4/lib/web_ui/lib/src/ui/geometry.dart#L1763

Nice catch. Any workaround solutions?

**Comment by vsmenon** [comment]
If you have access to the file that's importing both, you can use `show` or `hide` or a prefix (`as`).  E.g., if you want the version in `dart:math`, you could do:

```dart
import 'dart:math';
import 'dart:ui' hide Point;
```

See https://dart.dev/guides/language/language-tour#libraries-and-visibility

**Comment by devoncarew** [comment]
Thanks for the report! Closing this as I believe the solution is to modify user source.
