### ISSUE TITLE
Dart Analysis server terminated 

### ISSUE THREAD

**Issue by Akash4097** [dart-lang/sdk#39870]
Recently i am facing the problem of 

> lost connection(given in screenshot) and also Dart analysis server terminated problem

![2019-12-19_21-57-31](https://user-images.githubusercontent.com/12380680/71190571-d74aa700-22aa-11ea-990e-83e2dd522b99.png)

`flutter doctor`

cmd gives all green tick, i face this problem in both VS  code and anroid studio..
here is the log from VS code:

`Dart Code extension: 3.7.1
Flutter extension: 3.7.1 (not activated)
VS Code: 1.41.1
Platform: win
HTTP_PROXY: undefined
NO_PROXY: undefined

Sun Dec 22 2019 [20:32:54 GMT+0530 (India Standard Time)] Log file started
[8:32:54 PM] [General] [Info] Searching for SDKs...
[8:32:54 PM] [General] [Info] Environment PATH:
[8:32:54 PM] [General] [Info]     C:\Windows\system32
[8:32:54 PM] [General] [Info]     C:\Windows
[8:32:54 PM] [General] [Info]     C:\Windows\System32\Wbem
[8:32:54 PM] [General] [Info]     C:\Windows\System32\WindowsPowerShell\v1.0\
[8:32:54 PM] [General] [Info]     C:\Windows\System32\OpenSSH\
[8:32:54 PM] [General] [Info]     C:\Program Files\Git\cmd
[8:32:54 PM] [General] [Info]     C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
[8:32:54 PM] [General] [Info]     C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
[8:32:54 PM] [General] [Info]     C:\src\flutter\bin
[8:32:54 PM] [General] [Info]     C:\Users\Akash\AppData\Local\Programs\Python\Python38-32\Scripts\
[8:32:54 PM] [General] [Info]     C:\Users\Akash\AppData\Local\Programs\Python\Python38-32\
[8:32:54 PM] [General] [Info]     C:\Users\Akash\AppData\Local\Microsoft\WindowsApps
[8:32:54 PM] [General] [Info]     C:\Users\Akash\AppData\Local\Programs\Microsoft VS Code\bin
[8:32:54 PM] [General] [Info]     C:\src\flutter\bin
[8:32:54 PM] [General] [Info] Found Flutter project at C:\Users\Akash\Desktop\hw\hw:
			Mobile? false
			Web? false
			Create Trigger? true
			Flutter Repo? false
[8:32:54 PM] [General] [Info] Searching for flutter.bat
[8:32:54 PM] [General] [Info]     Looking for flutter.bat in:
[8:32:54 PM] [General] [Info]         C:\Users\Akash\Desktop\hw\hw
[8:32:54 PM] [General] [Info]         C:\Users\Akash\Desktop\hw\hw\bin
[8:32:54 PM] [General] [Info]         C:\Users\Akash\Desktop\hw\hw\.flutter
[8:32:54 PM] [General] [Info]         C:\Users\Akash\Desktop\hw\hw\.flutter\bin
[8:32:54 PM] [General] [Info]         C:\Users\Akash\Desktop\hw\hw\vendor\flutter
[8:32:54 PM] [General] [Info]         C:\Users\Akash\Desktop\hw\hw\vendor\flutter\bin
[8:32:54 PM] [General] [Info]         C:\Windows\system32
[8:32:54 PM] [General] [Info]         C:\Windows\system32\bin
[8:32:54 PM] [General] [Info]         C:\Windows
[8:32:54 PM] [General] [Info]         C:\Windows\bin
[8:32:54 PM] [General] [Info]         C:\Windows\System32\Wbem
[8:32:54 PM] [General] [Info]         C:\Windows\System32\Wbem\bin
[8:32:54 PM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\
[8:32:54 PM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\bin
[8:32:54 PM] [General] [Info]         C:\Windows\System32\OpenSSH\
[8:32:54 PM] [General] [Info]         C:\Windows\System32\OpenSSH\bin
[8:32:54 PM] [General] [Info]         C:\Program Files\Git\cmd
[8:32:54 PM] [General] [Info]         C:\Program Files\Git\cmd\bin
[8:32:54 PM] [General] [Info]         C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
[8:32:54 PM] [General] [Info]         C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR\bin
[8:32:54 PM] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
[8:32:54 PM] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\bin
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Programs\Python\Python38-32\Scripts\
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Programs\Python\Python38-32\Scripts\bin
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Programs\Python\Python38-32\
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Programs\Python\Python38-32\bin
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Microsoft\WindowsApps
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Microsoft\WindowsApps\bin
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Programs\Microsoft VS Code\bin
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin
[8:32:54 PM] [General] [Info]     Found at:
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin
[8:32:54 PM] [General] [Info]     Candidate paths to be post-filtered:
[8:32:54 PM] [General] [Info]         C:\src\flutter
[8:32:54 PM] [General] [Info]         C:\src\flutter
[8:32:54 PM] [General] [Info]     Found at C:\src\flutter
[8:32:54 PM] [General] [Info]     Returning SDK path C:\src\flutter for flutter.bat
[8:32:54 PM] [General] [Info] Searching for dart.exe
[8:32:54 PM] [General] [Info]     Looking for dart.exe in:
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk\bin
[8:32:54 PM] [General] [Info]         C:\Windows\system32
[8:32:54 PM] [General] [Info]         C:\Windows\system32\bin
[8:32:54 PM] [General] [Info]         C:\Windows
[8:32:54 PM] [General] [Info]         C:\Windows\bin
[8:32:54 PM] [General] [Info]         C:\Windows\System32\Wbem
[8:32:54 PM] [General] [Info]         C:\Windows\System32\Wbem\bin
[8:32:54 PM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\
[8:32:54 PM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\bin
[8:32:54 PM] [General] [Info]         C:\Windows\System32\OpenSSH\
[8:32:54 PM] [General] [Info]         C:\Windows\System32\OpenSSH\bin
[8:32:54 PM] [General] [Info]         C:\Program Files\Git\cmd
[8:32:54 PM] [General] [Info]         C:\Program Files\Git\cmd\bin
[8:32:54 PM] [General] [Info]         C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
[8:32:54 PM] [General] [Info]         C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR\bin
[8:32:54 PM] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
[8:32:54 PM] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\bin
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Programs\Python\Python38-32\Scripts\
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Programs\Python\Python38-32\Scripts\bin
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Programs\Python\Python38-32\
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Programs\Python\Python38-32\bin
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Microsoft\WindowsApps
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Microsoft\WindowsApps\bin
[8:32:54 PM] [General] [Info]         C:\Users\Akash\AppData\Local\Programs\Microsoft VS Code\bin
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk\bin
[8:32:54 PM] [General] [Info]     Found at:
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk\bin
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk\bin
[8:32:54 PM] [General] [Info]     Candidate paths to be post-filtered:
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk
[8:32:54 PM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk
[8:32:54 PM] [General] [Info]     Found at C:\src\flutter\bin\cache\dart-sdk
[8:32:54 PM] [General] [Info]     Returning SDK path C:\src\flutter\bin\cache\dart-sdk for dart.exe
[8:32:54 PM] [General] [Info] Activating Flutter extension for Flutter project...
[8:32:54 PM] [General] [Info] Extension:Startup timing: 64ms
[8:32:54 PM] [General] [Info] Analyzer:Startup timing: 625ms
[8:32:57 PM] [General] [Info] Skipping package fetch because project creation is in progress
[8:33:00 PM] [General] [Info] Checking 1 projects for supported platforms
[8:33:00 PM] [General] [Info] Supported platforms for the workspace are ios, android
[8:33:03 PM] [General] [Info] Analyzer:FirstAnalysis timing: 5744ms
[8:35:03 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.editGetFixes (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:290549)
	at t.FixCodeActionProvider.<anonymous> (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:436166)
	at Generator.next (<anonymous>)
	at c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:435700
	at new Promise (<anonymous>)
	at r (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:435445)
	at t.FixCodeActionProvider.provideCodeActions (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:436006)
	at c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:441239
	at Array.map (<anonymous>)
	at t.RankingCodeActionProvider.<anonymous> (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:441230)
	at Generator.next (<anonymous>)
	at c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:440679
	at new Promise (<anonymous>)
	at r (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:440424)
	at t.RankingCodeActionProvider.provideCodeActions (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\…
[8:35:03 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.editGetAssists (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:290272)
	at t.AssistCodeActionProvider.<anonymous> (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:397337)
	at Generator.next (<anonymous>)
	at c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:396876
	at new Promise (<anonymous>)
	at r (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:396621)
	at t.AssistCodeActionProvider.provideCodeActions (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:397178)
	at c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:441239
	at Array.map (<anonymous>)
	at t.RankingCodeActionProvider.<anonymous> (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:441230)
	at Generator.next (<anonymous>)
	at c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:440679
	at new Promise (<anonymous>)
	at r (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:440424)
	at t.RankingCodeActionProvider.provideCodeActions (c:\Users\Akash\.vscode\extensions\dart-code.dart-code-3.7.1\o…
`

**Comment by devoncarew** [comment]
Can you share the version of the Dart sdk, the flutter version, and the dart-code plugin's version?

**Comment by Akash4097** [comment]
Hello @devoncarew ,
Dart SDK: 2.7.0-dev.2.1
flutter version: 1.12.13+hotfix.5
dart-code plugin version: 191.8593

**Comment by Akash4097** [comment]
is their any solution to this problem??  @devoncarew

**Comment by Akash4097** [comment]
i am closing this issue as it got solved here: https://github.com/flutter/flutter/issues/46616

**Comment by Akash4097** [comment]
i am closing this issue as it got solved here: flutter/flutter#46616
