### ISSUE TITLE
i dont have any idea of this issue what this 

### ISSUE THREAD

**Issue by Mostafa-SA-developer** [dart-lang/sdk#39887]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.8.0-edge.fe9f30c3896e7146195ea52434c5082b309b6ee0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.fe9f30c3896e7146195ea52434c5082b309b6ee0, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:708:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file://C:\Users\lenovo\AppData\Local\Temp\report.txt.

**Comment by devoncarew** [comment]
Thanks for the report; this looks like a dup of #39499.
