### ISSUE TITLE
Output divergence JIT-O3-SLOWPATH-DebugSIMARM - AOT-ReleaseX64

### ISSUE THREAD

**Issue by fizaaluthra** [dart-lang/sdk#39891]
```
Isolate (/b/s/w/it0Qw2h6/dart_fuzzDZWDNI) NO-FP NO-FFI FLAT : JIT-O3-SLOWPATH-DebugSIMARM - AOT-ReleaseX64: !DIVERGENCE! 1.82:604801844 (output)

-- BEGIN REPRODUCE  --

DART SDK REVISION: 

dartfuzz.dart --no-fp --no-ffi --flat --seed 604801844 /b/s/w/it0Qw2h6/dart_fuzzDZWDNI/fuzz.dart

-- RUN 1 --

/b/s/w/ir/out/DebugSIMARM/dart --optimization_level=3 --use-slow-path --old_gen_heap_size=128 /b/s/w/it0Qw2h6/dart_fuzzDZWDNI/fuzz.dart

-- RUN 2 --

DART_CONFIGURATION='ReleaseX64' DART_VM_FLAGS='--enable-asserts' /b/s/w/ir/pkg/vm/tool/precompiler2 /b/s/w/it0Qw2h6/dart_fuzzDZWDNI/fuzz.dart /b/s/w/it0Qw2h6/dart_fuzzDZWDNI/snapshot
/b/s/w/ir/pkg/vm/tool/dart_precompiled_runtime2 /b/s/w/it0Qw2h6/dart_fuzzDZWDNI/snapshot

-- END REPRODUCE  --

```
Was able to reproduce locally on commit [43f74824c2f10806c92143b0bb5c2c3bea58c7a0](https://github.com/dart-lang/sdk/commit/43f74824c2f10806c92143b0bb5c2c3bea58c7a0). 

Difference in output:
```
6d5
< fooE1(var67).foo1_Extension1() throws
66c65
< Expando:
---
> Expando:z
```

Also executed the program in JIT-ReleaseX64. JIT-O3-SLOWPATH-DebugSIMARM and JIT-ReleaseX64 agree, and AOT-ReleaseX64 disagrees with both.

**Comment by fizaaluthra** [comment]
Another one:
```
Isolate (/b/s/w/itL9VE4b/dart_fuzzIAEGXO) NO-FP NO-FFI FLAT : AOT-ReleaseX64 - JIT-DebugSIMARM: !DIVERGENCE! 1.82:1842206042 (output)

-- BEGIN REPRODUCE  --

DART SDK REVISION: 

dartfuzz.dart --no-fp --no-ffi --flat --seed 1842206042 /b/s/w/itL9VE4b/dart_fuzzIAEGXO/fuzz.dart

-- RUN 1 --

DART_CONFIGURATION='ReleaseX64' DART_VM_FLAGS='--enable-asserts' /b/s/w/ir/pkg/vm/tool/precompiler2 /b/s/w/itL9VE4b/dart_fuzzIAEGXO/fuzz.dart /b/s/w/itL9VE4b/dart_fuzzIAEGXO/snapshot
/b/s/w/ir/pkg/vm/tool/dart_precompiled_runtime2 /b/s/w/itL9VE4b/dart_fuzzIAEGXO/snapshot

-- RUN 2 --

/b/s/w/ir/out/DebugSIMARM/dart --old_gen_heap_size=128 /b/s/w/itL9VE4b/dart_fuzzIAEGXO/fuzz.dart

-- END REPRODUCE  --
```

**Comment by aam** [comment]
Smaller repro:
```
import 'dart:typed_data';

main() {
   print(Int32x4(34, 29, 44, 35).withFlagZ(null));
}
```

```
╰─➤  DART_CONFIGURATION='ReleaseX64' DART_VM_FLAGS='--enable-asserts' pkg/vm/tool/precompiler2 withflagznull.dart snapshot
pkg/vm/tool/dart_precompiled_runtime2 snapshot

[00000022, 0000001d, 00000000, 00000023]
```

```
╰─➤  out/ReleaseX64/dart withflagznull.dart                                                                                               255 ↵
Unhandled exception:
Invalid argument(s)
#0      Int32x4.withFlagZ (dart:typed_data-patch/typed_data_patch.dart:3651:54)
#1      main (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/withflagznull.dart:4:34)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by aam** [comment]
https://github.com/dart-lang/sdk/blob/d0457488dfb00f146eb947378c0b6613e328b5e5/runtime/lib/simd128.cc#L581 enforces non-null argument for `Int32x4.withFlagZ`. 
aot pipeline(https://github.com/dart-lang/sdk/blob/master/runtime/vm/compiler/backend/il_x64.cc#L4613) doesn't seem to enforce non-nullness.

**Comment by aam** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/39812
