### ISSUE TITLE
Dart Analyzer Error Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by azhar-rafiq** [dart-lang/sdk#39902]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: Analysis failed: /Users/azharrafiq/GenomStudio/med_stud_games/test/widget_test.dart context: exception_20191223_010344_180
Bad state: No definition of type Stream
#0      SummaryTypeProvider._getType (package:analyzer/src/summary/summary_sdk.dart:377:7)
#1      SummaryTypeProvider.streamType (package:analyzer/src/summary/summary_sdk.dart:327:21)
#2      SdkConstraintVerifier.visitSimpleIdentifier (package:analyzer/src/hint/sdk_constraint_verifier.dart:205:38)
#3      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8850:49)
#4      TypeNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10062:12)
#5      RecursiveAstVisitor.visitTypeName (package:analyzer/dart/ast/visitor.dart:1270:10)
#6      TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10058:49)
#7      FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4743:18)
#8      RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:897:10)
#9      FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4738:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7550:20)
#11     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2168:21)
#12     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:723:10)
#13     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2147:49)
#14     LibraryAnalyzer._computeHints (package:analyzer/src/dart/analysis/library_analyzer.dart:291:12)
#15     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:166:11)
#16     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#17     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:165:15)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:151:35)
#20     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:14)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:43)
#23     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1450:63)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#25     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1427:20)
#26     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1247:33)
<asynchronous suspension>
#27     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2160:24)
<asynchronous suspension>
#28     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2090:5)
#29     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#30     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#31     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#32     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#38     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#39     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#40     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#41     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#42     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/pn/d3mw_b7x1z5crpb4ngyv4bz40000gn/T/report.txt.

**Comment by srawlins** [comment]
Dart 2.3.0 was released over 6 months ago; please upgrade Dart (or Flutter) to a recent version. Feel free to re-open this issue if it occurs again.
