### ISSUE TITLE
while Launching lib\main.dart on Chrome in debug mode...

### ISSUE THREAD

**Issue by ajs-sonawane** [dart-lang/sdk#39921]
Bad state: Tried to use a deleted ScratchSpace!

The specific exception that was encountered was:

FileSystemException(uri=file:///C:/Users/ABHIJEET/AppData/Local/Temp/scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8/packages/meta/meta.ddc.dill; message=The system cannot find the path specified.
)

the log.. 
------------------- %< --------------------
    dartdevc -k arguments: --kernel --dart-sdk-summary=C:\src\flutter\bin\cache\flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\src\widgets\actions.ddc.js --source-map --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\meta\meta.ddc.dill=packages/meta/meta --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\typed_data\typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\src\foundation\_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\foundation.ddc.dill=packages/flutter/foundation --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\vector_math\hash.ddc.dill=packages/vector_math/hash --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\vector_math\vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\collection\src\utils.ddc.dill=packages/collection/src/utils --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\collection\src\algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\collection\src\iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\collection\src\comparators.ddc.dill=packages/collection/src/comparators --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\collection\src\priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\collection\src\canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\collection\collection.ddc.dill=packages/collection/collection --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\src\gestures\arena.ddc.dill=packages/flutter/src/gestures/arena --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\gestures.ddc.dill=packages/flutter/gestures --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\src\painting\_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\painting.ddc.dill=packages/flutter/painting --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\src\physics\clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\physics.ddc.dill=packages/flutter/physics --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\src\semantics\binding.ddc.dill=packages/flutter/src/semantics/binding --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\semantics.ddc.dill=packages/flutter/semantics --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\src\animation\animation.ddc.dill=packages/flutter/src/animation/animation --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\animation.ddc.dill=packages/flutter/animation --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\src\rendering\animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=C:\Users\ABHIJEET\AppData\Local\Temp\scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8\packages\flutter\rendering.ddc.dill=packages/flutter/rendering --packages=file:///C:/Users/ABHIJEET/AppData/Local/Temp/kernel_builder_8fd9fa01-26cf-11ea-a2cd-54bf641967e8/.packages --module-name=packages/flutter/src/widgets/actions --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=C:\Users\ABHIJEET\AppData\Local\Temp\ddk_builder_8fd9fa00-26cf-11ea-a2cd-54bf641967e8\used_inputs.txt package:flutter/src/widgets/pages.dart package:flutter/src/widgets/draggable_scrollable_sheet.dart package:flutter/src/widgets/platform_view.dart package:flutter/src/widgets/focus_traversal.dart package:flutter/src/widgets/viewport.dart package:flutter/src/widgets/basic.dart package:flutter/src/widgets/scroll_position.dart package:flutter/src/widgets/visibility.dart package:flutter/src/widgets/nested_scroll_view.dart package:flutter/src/widgets/grid_paper.dart package:flutter/src/widgets/automatic_keep_alive.dart package:flutter/src/widgets/placeholder.dart package:flutter/src/widgets/app.dart package:flutter/src/widgets/overscroll_indicator.dart package:flutter/src/widgets/list_wheel_scroll_view.dart package:flutter/src/widgets/safe_area.dart package:flutter/src/widgets/scroll_metrics.dart package:flutter/src/widgets/route_notification_messages.dart package:flutter/src/widgets/title.dart package:flutter/src/widgets/form.dart package:flutter/src/widgets/localizations.dart package:flutter/src/widgets/icon.dart package:flutter/src/widgets/drag_target.dart package:flutter/src/widgets/image_icon.dart package:flutter/src/widgets/image.dart package:flutter/src/widgets/sliver_persistent_header.dart package:flutter/src/widgets/banner.dart package:flutter/src/widgets/will_pop_scope.dart package:flutter/src/widgets/ticker_provider.dart package:flutter/src/widgets/scroll_position_with_single_context.dart package:flutter/src/widgets/binding.dart package:flutter/src/widgets/animated_switcher.dart package:flutter/src/widgets/spacer.dart package:flutter/src/widgets/media_query.dart package:flutter/src/widgets/value_listenable_builder.dart package:flutter/src/widgets/scroll_physics.dart package:flutter/src/widgets/size_changed_layout_notifier.dart package:flutter/src/widgets/orientation_builder.dart package:flutter/src/widgets/focus_manager.dart package:flutter/src/widgets/layout_builder.dart package:flutter/src/widgets/icon_theme.dart package:flutter/src/widgets/table.dart package:flutter/src/widgets/scroll_configuration.dart package:flutter/src/widgets/animated_list.dart package:flutter/src/widgets/routes.dart package:flutter/src/widgets/dismissible.dart package:flutter/src/widgets/heroes.dart package:flutter/src/widgets/scroll_activity.dart package:flutter/src/widgets/scroll_context.dart package:flutter/src/widgets/scrollbar.dart package:flutter/src/widgets/editable_text.dart package:flutter/src/widgets/sliver.dart package:flutter/src/widgets/single_child_scroll_view.dart package:flutter/src/widgets/transitions.dart package:flutter/src/widgets/actions.dart package:flutter/src/widgets/annotated_region.dart package:flutter/src/widgets/framework.dart package:flutter/src/widgets/constants.dart package:flutter/src/widgets/inherited_theme.dart package:flutter/src/widgets/focus_scope.dart package:flutter/src/widgets/scroll_controller.dart package:flutter/src/widgets/icon_data.dart package:flutter/src/widgets/sliver_layout_builder.dart package:flutter/src/widgets/status_transitions.dart package:flutter/src/widgets/color_filter.dart package:flutter/src/widgets/notification_listener.dart package:flutter/src/widgets/scroll_notification.dart package:flutter/src/widgets/scroll_simulation.dart package:flutter/src/widgets/gesture_detector.dart package:flutter/src/widgets/scrollable.dart package:flutter/src/widgets/bottom_navigation_bar_item.dart package:flutter/src/widgets/page_view.dart package:flutter/src/widgets/texture.dart package:flutter/src/widgets/semantics_debugger.dart package:flutter/src/widgets/navigator.dart package:flutter/src/widgets/performance_overlay.dart package:flutter/src/widgets/text_selection.dart package:flutter/src/widgets/unique_widget.dart package:flutter/src/widgets/modal_barrier.dart package:flutter/src/widgets/scroll_view.dart package:flutter/src/widgets/fade_in_image.dart package:flutter/src/widgets/inherited_notifier.dart package:flutter/src/widgets/widget_inspector.dart package:flutter/src/widgets/image_filter.dart package:flutter/src/widgets/async.dart package:flutter/src/widgets/widget_span.dart package:flutter/src/widgets/inherited_model.dart package:flutter/src/widgets/text.dart package:flutter/src/widgets/animated_size.dart package:flutter/src/widgets/implicit_animations.dart package:flutter/src/widgets/debug.dart package:flutter/src/widgets/overlay.dart package:flutter/src/widgets/raw_keyboard_listener.dart package:flutter/src/widgets/icon_theme_data.dart package:flutter/src/widgets/preferred_size.dart package:flutter/src/widgets/primary_scroll_controller.dart package:flutter/src/widgets/shortcuts.dart package:flutter/src/widgets/animated_cross_fade.dart package:flutter/src/widgets/container.dart package:flutter/src/widgets/page_storage.dart package:flutter/src/widgets/sliver_prototype_extent_list.dart package:flutter/src/widgets/tween_animation_builder.dart package:flutter/src/widgets/navigation_toolbar.dart
    dart --version: 2.8.0-dev.0.0.flutter-886615d0f9 (Fri Dec 20 11:07:10 2019 +0000) on "windows_x64"

FileSystemException(uri=file:///C:/Users/ABHIJEET/AppData/Local/Temp/scratch_space8fd9f9ff-26cf-11ea-a2cd-54bf641967e8/packages/meta/meta.ddc.dill; message=The system cannot find the path specified.
)
---------------------------
#0      _IoFileSystemEntity.readAsBytes  (package:front_end/src/api_prototype/standard_file_system.dart:68:7)
#1      MultiRootFileSystemEntity.readAsBytes  (package:build_integration/file_system/multi_root.dart:78:61)
<asynchronous suspension>
#2      initializeIncrementalCompiler  (package:front_end/src/api_unstable/modular_incremental_compilation.dart:203:55)
<asynchronous suspension>
#3      initializeIncrementalCompiler  (package:front_end/src/api_unstable/ddc.dart:163:10)
#4      _compile  (package:dev_compiler/src/kernel/command.dart:295:27)
#5      compile  (package:dev_compiler/src/kernel/command.dart:46:18)
#6      compile  (package:dev_compiler/src/compiler/shared_command.dart:410:10)
#7      _CompilerWorker.performRequest.<anonymous closure>  (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#8      _rootRun  (dart:async/zone.dart:1126:13)
#9      _CustomZone.run  (dart:async/zone.dart:1023:19)
#10     _runZoned  (dart:async/zone.dart:1518:10)
#11     runZoned  (dart:async/zone.dart:1465:12)
#12     _CompilerWorker.performRequest  (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#13     AsyncWorkerLoop.run.<anonymous closure>  (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#14     _rootRun  (dart:async/zone.dart:1126:13)
#15     _CustomZone.run  (dart:async/zone.dart:1023:19)
#16     _runZoned  (dart:async/zone.dart:1518:10)
#17     runZoned  (dart:async/zone.dart:1465:12)
#18     AsyncWorkerLoop.run  (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#19     main  (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#20     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:303:32)
#21     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)

Failed to build application for the Web.

-------------------------
flutter doctor -v

[√] Flutter (Channel master, v1.13.6-pre.23, on Microsoft Windows [Version 10.0.18362.535], locale en-IN)
    • Flutter version 1.13.6-pre.23 at C:\src\flutter
    • Framework revision 6e72facad1 (10 hours ago), 2019-12-24 10:54:04 -0800
    • Engine revision 33813929e3
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\ABHIJEET\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\ABHIJEET\AppData\Local\Android\Sdk
    • Java binary at: D:\installs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at D:\installs\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by devoncarew** [comment]
Not quite sure where to triage this to...

**Comment by natebosch** [comment]
cc @jonahwilliams @jakemac53 

This looks like a misuse of `ScratchSpace`. @jonahwilliams - do you know if this is coming strictly from `build_modules`, or is there other uses of `package:scratch_space` that could be the problem?

**Comment by jonahwilliams** [comment]
I'm not using a scratch space directly in the flutter tool or in the flutter web build script

**Comment by jakemac53** [comment]
This might just be a slightly different manifestation of https://github.com/dart-lang/sdk/issues/38102, possibly pointing at more of a root cause?

One theory could be that we are for some reason considering a build step to be completed before it is actually done (for an unknown reason). Meanwhile the compiler is actually still running, and the scratch_space gets deleted out from under it.

**Comment by jakemac53** [comment]
@ajs-sonawane  is it possible to get a full log for this (I realize it might be quite verbose).

**Comment by ILoveScratch2** [comment]
Does it still have problems?

**Comment by jakemac53** [comment]
closing this as stale
