### ISSUE TITLE
Dart Analysis server has terminated 

### ISSUE THREAD

**Issue by MahmoudElbokl** [dart-lang/sdk#39946]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.7.0-dev.2.1`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file://C:\Users\M\AppData\Local\Temp\report1.txt.

**Comment by devoncarew** [comment]
Thanks for the report; this looks like a dup of https://github.com/dart-lang/sdk/issues/39499.
