### ISSUE TITLE
Inconsistent behavior of DynamicLibrary.open() on Mac and Linux when loading library with relative paths and compiled to native

### ISSUE THREAD

**Issue by javaddict** [dart-lang/sdk#39954]
I am trying the [hello world](https://github.com/dart-lang/samples/tree/master/ffi/hello_world) example on a Mac and a Linux. Dart `2.7.0` is used.

In the source:
* The main dart file `hello.dart` is in the directory `hello_world`.
* The library is in `hello_world/hello_library`.
* The relative path `./hello_library/libhello.dylib`(or `./hello_library/libhello.so`) is passed to `DynamicLibrary.open()`.

Here is the result:

* If I `dart hello.dart` at the directory of `hello_world`, it works both on Mac and Linux.
* If I `dart hello.dart` at the directory that is not `hello_world`, it works neither on Mac nor on Linux.

So far the results are consistent.

Then when I `dart2native hello.dart` to produce `hello.exe`:
* If I run `hello.exe` at the directory of `hello_world`, it works both on Mac and Linux.
* If I run `hello.exe` at the directory that is not `hello_world`, **it works on Mac but not on Linux**.

P.S.: To reproduce this on Mac, one may need to remove the signature of `dartaotruntime` so the system won't complain about the signature of `libhello.dylib` and the no-relative-path rule.

**Comment by a-siva** [comment]
I tried the above with the latest version of Dart on my linux machine and running hello.exe at a directory that is not hello_world works just fine.

**Comment by javaddict** [comment]
I did it again and still no luck.
```
Unhandled exception:
Invalid argument(s): Failed to load dynamic library (./hello_library/libhello.so: cannot open shared object file: No such file or directory)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      main (file:///ssd/ckchen/samples/ffi/hello_world/hello.dart:18)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174)
```
Anything I can check on my Linux?

**Comment by Sunbreak** [comment]
Seems related https://github.com/flutter/flutter/issues/76499

**Comment by hmbenhaim** [comment]
I have the same issue I'm running realm that loads dynamic lib on my mac and it is working just fine,
when i run it on docker (Linux) and it says ```Invalid argument(s): Failed to load dynamic library 'binary/linux/librealm_dart.so': libz.so.1: cannot open shared object file: No such file or directoryz``` and i have check this exact diretory with ```await File("binary/linux/librealm_dart.so").exists()``` and it returned ```true``` which is mean the file absolutely there

**Comment by c0c4i** [comment]
@hmbenhaim I have the same problem and today I opened an issue, did you already solve the issue?
Thank you so much :)

**Comment by hmbenhaim** [comment]
> @hmbenhaim I have the same problem and today I opened an issue, did you already solve the issue?

Sorry :( I did not solve this issue, I just used a different library.
