### ISSUE TITLE
Dart analyzer crashes when using ?. operator

### ISSUE THREAD

**Issue by hongyiweiwu** [dart-lang/sdk#39986]
**Dart SDK version**: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "macos_x64"
**Operating system**: MacOSX

**Minimal example**:
Running `dart analyzer --verbose --enable-experiment=non-nullable <filename>` on the file containing the following code
```
class A {
    final String str;
    const A({required this.str});
}

final c = ([A? meta]) => meta?.str;
```
yields
```
Analyzing <filename>...
Loaded analysis options from <analysisOptionsFilename>
Unhandled exception:
NoSuchMethodError: The getter 'flow' was called on null.
Receiver: null
Tried calling: flow
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:1880:21)
#2      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:49)
#3      ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3503:18)
#4      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1823:10)
#5      UnifyingAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:3211:65)
#6      ResolverVisitor.visitExpressionFunctionBody (package:analyzer/src/generated/resolver.dart:1279:13)
#7      PartialResolverVisitor.visitExpressionFunctionBody (package:analyzer/src/generated/resolver.dart:380:11)
#8      ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3499:15)
#9      FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4962:12)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1823:10)
#11     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3263:57)
#12     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3114:15)
#13     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:1572:13)
#14     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4956:49)
#15     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10340:19)
#16     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1823:10)
#17     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3466:59)
#18     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:3357:11)
#19     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:2118:11)
#20     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10334:49)
#21     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7498:20)
#22     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10436:16)
#23     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1823:10)
#24     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3470:7)
#25     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:2144:11)
#26     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10430:15)
#27     TopLevelVariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9708:20)
#28     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1823:10)
#29     UnifyingAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3448:7)
#30     PartialResolverVisitor.visitTopLevelVariableDeclaration (package:analyzer/src/generated/resolver.dart:394:11)
#31     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:9703:15)
#32     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:1079:23)
#33     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2087:49)
#34     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:699:10)
#35     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:155:7)
#36     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#37     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:154:11)
#38     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:123:14)
#39     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#40     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:122:43)
#41     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1277:63)
#42     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#43     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1253:20)
#44     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:550:41)
<asynchronous suspension>
#45     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:58)
<asynchronous suspension>
#46     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#47     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#48     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:705:21)
#49     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:364:40)
#50     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#51     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#52     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#53     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#54     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:391:9)
#55     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#56     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#57     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1313:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1253:20)
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:550:41)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:58)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:705:21)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:364:40)
#9      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:391:9)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```
The analysis option file looks like
```
analyzer:
  enable-experiment:
    - non-nullable
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const
    - prefer_conditional_assignment
    - prefer_if_null_operators
    - prefer_null_aware_operators
```

Any help would be appreciated. Thank you!

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Cannot reproduce this the latest analyzer.
