### ISSUE TITLE
Analyzer Feedback - readSync failed

### ISSUE THREAD

**Issue by douglasnatanmartins** [dart-lang/sdk#39984]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.8.0-edge.1db1a837f8c9e7e4e12c968efd98510527feae6b`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768, 1366x768`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.1db1a837f8c9e7e4e12c968efd98510527feae6b, server version , error: FileSystemException(path=D:\ProjetosFlutter\app_delivery\.packages; message=readSync failed)
#0      _PhysicalFile.readAsBytesSync (package:analyzer/file_system/physical_file_system.dart:202:7)
#1      _OverlayFile.readAsBytesSync (package:analyzer/file_system/overlay_file_system.dart:238:18)
#2      ContextBuilder.findPackagesFromFile (package:analyzer/src/context/builder.dart:284:38)
#3      ContextBuilder.createPackageMap (package:analyzer/src/context/builder.dart:245:12)
#4      SimpleWorkspace.packages (package:analyzer/src/workspace/simple.dart:41:28)
#5      SimpleWorkspace.packageMap (package:analyzer/src/workspace/simple.dart:36:51)
#6      SimpleWorkspace.packageUriResolver (package:analyzer/src/workspace/simple.dart:47:39)
#7      SimpleWorkspace.createSourceFactory (package:analyzer/src/workspace/simple.dart:59:19)
#8      ContextBuilder.getAnalysisOptions (package:analyzer/src/context/builder.dart:362:45)
#9      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:143:9)
#10     ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:750:48)
#11     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1168:19)
#12     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1230:16)
#13     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:780:9)
#14     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:472:22)
#15     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:384:14)
#16     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:318:16)
#17     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:315:45)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:254:15)
#19     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:311:50)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _runZoned (dart:async/zone.dart:1518:10)
#23     runZoned (dart:async/zone.dart:1502:12)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:310:5)
#25     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:254:15)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#28     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#29     _rootRunUnary (dart:async/zone.dart:1134:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#41     _rootRunUnary (dart:async/zone.dart:1134:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#46     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#47     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#48     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#49     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#50     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#51     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#52     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#53     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#54     _rootRunUnary (dart:async/zone.dart:1134:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#57     _BufferingStreamSubscription....
```

For additional log information, please append the contents of
file://C:\Users\dougl\AppData\Local\Temp\report1.txt.

**Comment by srawlins** [comment]
Apologies that we did not get a chance to investigate this crash; please re-open if you see this on a recent version of Dart.
