### ISSUE TITLE
Analyzer assertion failure:  Bad state: Expected all legacy types

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#39996]
This is only an error at head; before head it seems to be covered up by #39937.  It seems likely to be related to #38307.

```
jcollins-macbookpro2:t6 jcollins$ cat test.dart
void tryThis({void Function(bool isWorking) onMaybeWorking}) {
  onMaybeWorking?.call(true);
}

jcollins-macbookpro2:t6 jcollins$ dart --enable-asserts ~/dart/sdk/sdk/pkg/analyzer_cli/bin/analyzer.dart test.dart
Analyzing test.dart...
Unhandled exception:
Bad state: Expected all legacy types, but got void Function(bool*) (FunctionTypeImpl)
#0      LegacyTypeAsserter._assertLegacyType (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:146:5)
#1      LegacyTypeAsserter.visitInvocationExpression (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:86:5)
#2      GeneralizingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:420:7)
#3      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7083:49)
#4      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3672:18)
#5      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#6      GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#7      GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:271:59)
#8      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3668:49)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7520:20)
#10     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1085:17)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#12     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#13     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:162:31)
#14     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1081:49)
#15     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1040:13)
#16     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#17     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#18     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:165:55)
#19     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1036:49)
#20     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4975:12)
#21     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#22     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#23     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#24     LegacyTypeAsserter.visitExpression (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:69:11)
#25     GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:332:57)
#26     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4969:49)
#27     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4832:26)
#28     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#29     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#30     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#31     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:202:7)
#32     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:427:7)
#33     GeneralizingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:325:7)
#34     LegacyTypeAsserter.visitFunctionDeclaration (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:81:11)
#35     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4825:49)
#36     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7520:20)
#37     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2102:21)
#38     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#39     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:199:51)
#40     LegacyTypeAsserter.visitCompilationUnit (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:55:13)
#41     LegacyTypeAsserter.assertLegacyTypes (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:152:26)
#42     Iterable.every (dart:core/iterable.dart:349:16)
#43     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:203:25)
#44     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:123:14)
#45     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#46     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:122:43)
#47     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1278:63)
#48     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#49     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1254:20)
#50     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:551:41)
<asynchronous suspension>
#51     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:58)
<asynchronous suspension>
#52     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#53     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#54     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:662:21)
#55     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:361:40)
#56     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#57     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#58     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#59     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#60     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:391:9)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#63     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#64     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1314:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1254:20)
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:551:41)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:58)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:662:21)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:361:40)
#9      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:391:9)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
jcollins-macbookpro2:t6 jcollins$ dart --version
Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "macos_x64"
jcollins-macbookpro2:t6 jcollins$
```

**Comment by jcollins-g** [comment]
This is the root cause of dart-lang/dartdoc#2104.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by jcollins-g** [comment]
i think i may have a fix.  looking to add a proper unit test now.

**Comment by jcollins-g** [comment]
https://dart-review.googlesource.com/c/sdk/+/130581
