### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by ovestoerholt** [dart-lang/sdk#40082]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6071332`
- `2.7.0-dev.2.1`
- `AI-192.7142.36.36.6071332, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.2, screens 3440x1440`

## Exception
```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version 1.27.4, error: FormatException: Invalid MIME type (at character 11)
data:.dart
          ^

#0      UriData._parse (dart:core/uri.dart:3760:7)
#1      Uri.parse (dart:core/uri.dart:802:24)
#2      _Uri.resolve (dart:core/uri.dart:2611:27)
#3      PackagesBase.resolve (package:package_config/src/packages_impl.dart:52:24)
#4      SourceFactoryImpl._internalResolveUri (package:analyzer/src/context/source.dart:236:23)
#5      SourceFactoryImpl.forUri2 (package:analyzer/src/context/source.dart:125:16)
#6      FileSystemState.hasUri (package:analyzer/src/dart/analysis/file_state.dart:895:41)
#7      AnalysisDriver.getResult (package:analyzer/src/dart/analysis/driver.dart:786:19)
#8      AbstractAnalysisServer.getResolvedUnit (package:analysis_server/src/analysis_server_abstract.dart:284:10)
#9      AnalysisServer.setFlutterSubscriptions (package:analysis_server/src/analysis_server.dart:533:9)
#10     FlutterDomainHandler.setSubscriptions (package:analysis_server/src/flutter/flutter_domain.dart:117:12)
#11     FlutterDomainHandler.handleRequest (package:analysis_server/src/flutter/flutter_domain.dart:75:16)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:329:50)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _runZoned (dart:async/zone.dart:1518:10)
#18     runZoned (dart:async/zone.dart:1502:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:328:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#36     _rootRunUnary (dart:async/zone.dart:1134:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#49     _rootRunUnary (dart:async/zone.dart:1134:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#55     _StreamController._add (dart:async/stream_controller.dart:642:7)
#56     _StreamController.add (dart:async/stream_controller.dart:588:5)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
#58     _rootRunUnary (dart:async/zone.dart:1138:13)
#59     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#61     _BufferingStreamSubscription._sendData (dart:asy...
```

For additional log information, please append the contents of
file:///private/var/folders/9b/k0wg7y715ysf4p6g6_w6_dyc0000gn/T/report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.7.0. Please re-open if you see this crash again.
