### ISSUE TITLE
Does the ClosedWorldClassHierarchy failure reflect inconsistent information produced in class_hierarchy_builder?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#40092]
In a fresh commit (a4207fd03cfc2c8b082ee7eb7b023773c5f18069), assume that this library is added as `tests/language_2/scratch_test.dart`:

```dart
// SharedOptions=--enable-experiment=nonfunction-type-aliases

typedef T<X> = Object;
class D1<X> extends T<X> {}

main() {}
```

We then get an internal error on running:

```
> python tools/test.py -n fasta-linux language_2/scratch_test.dart
```

namely:

```
stderr:
Unhandled exception:
  Crash when compiling null,
at character offset null:
'package:kernel/type_algebra.dart': Failed assertion: line 228 pos 12: 'parameters.length == types.length': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      Substitution.fromPairs (package:kernel/type_algebra.dart:228:12)
#3      ClosedWorldClassHierarchy._recordSuperTypes (package:kernel/class_hierarchy.dart:1249:39)
#4      ClosedWorldClassHierarchy._initializeTopologicallySortedClasses (package:kernel/class_hierarchy.dart:956:9)
#5      ClosedWorldClassHierarchy._initialize (package:kernel/class_hierarchy.dart:929:5)
#6      new ClassHierarchy (package:kernel/class_hierarchy.dart:36:9)
#7      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:890:23)
#8      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:275:14)
```

It looks like the work done on substitutions in 'class_hierarchy_builder.dart' is not transferred to the `ClosedWorldClassHierarchy`.

@johnniwinther, it would be great if you could provide your take on where this scenario breaks some invariants.

**Comment by eernstg** [comment]
Resolved. Thanks, @johnniwinther!
