### ISSUE TITLE
CFE crashes on late variables in for loops when the lowering is enabled

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#40093]
The following program makes the CFE crash when the following flags are set: `--enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong --force-late-lowering`.

```dart
foo() {
  for (late int x = 0; i < 10; ++i) {
    print(i);
  }
}
```

The program does contain an error, and the error is reported, but the compiler shouldn't crash.

<details>
<summary>Click to expand</summary>

```
$ sdk/bin/dart pkg/front_end/tool/fasta.dart compile --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong --force-late-lowering /tmp/asdf2.dart
Running: .../sdk/bin/dart --enable-asserts .../pkg/front_end/tool/_fasta/compile.dart --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong --force-late-lowering /t
mp/asdf2.dart
/tmp/asdf2.dart:2:8: Error: Can't have modifier 'late' here.
Try removing 'late'.
  for (late int x = 0; i < 10; ++i) {
       ^^^^
/tmp/asdf2.dart:2:24: Error: Getter not found: 'i'.
  for (late int x = 0; i < 10; ++i) {
                       ^
/tmp/asdf2.dart:2:34: Error: Getter not found: 'i'.
  for (late int x = 0; i < 10; ++i) {
                                 ^
/tmp/asdf2.dart:3:11: Error: Getter not found: 'i'.
    print(i);
          ^
Unhandled exception:
Crash when compiling file:///tmp/asdf2.dart,
at character offset 4:
type 'FunctionDeclaration' is not a subtype of type 'VariableDeclaration'
#0      InferenceVisitor.visitForStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:976:13)
#1      ForStatement.accept (package:kernel/ast.dart:4814:43)
#2      TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:2895:24)
#3      InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:299:20)
#4      InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:320:30)
#5      Block.accept (package:kernel/ast.dart:4578:43)
#6      TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:2895:24)
#7      TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:1796:39)
#8      BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:929:28)
#9      DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:908:14)
#10     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:941:7)
#11     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:352:5)
#12     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2523:14)
#13     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2377:14)
#14     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:495:14)
#15     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#16     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:333:14)
<asynchronous suspension>
#17     Loader.buildBodies (package:front_end/src/fasta/loader.dart:243:15)
#18     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:304:20)
#19     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#20     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:302:12)
#21     CompileTask.compile (file://.../pkg/front_end/tool/_fasta/entry_points.dart:272:28)
<asynchronous suspension>
#22     compile.<anonymous closure>.<anonymous closure> (file://.../pkg/front_end/tool/_fasta/entry_points.dart:226:25)
#23     withGlobalOptions.<anonymous closure> (file://.../pkg/front_end/tool/_fasta/command_line.dart:520:13)
#24     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#25     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#28     _rootRun (dart:async/zone.dart:1126:13)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _runZoned (dart:async/zone.dart:1518:10)
#31     runZoned (dart:async/zone.dart:1465:12)
#32     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#33     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#34     withGlobalOptions (file://.../pkg/front_end/tool/_fasta/command_line.dart:513:26)
#35     compile.<anonymous closure> (file://.../pkg/front_end/tool/_fasta/entry_points.dart:219:18)
#36     runProtectedFromAbort (file://.../pkg/front_end/tool/_fasta/command_line.dart:568:24)
#37     compile (file://.../pkg/front_end/tool/_fasta/entry_points.dart:218:16)
#38     compileEntryPoint (file://.../pkg/front_end/tool/_fasta/entry_points.dart:77:11)
#39     main (file://.../pkg/front_end/tool/_fasta/compile.dart:7:33)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:946:7)
#1      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:352:5)
#2      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2523:14)
#3      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2377:14)
#4      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:495:14)
#5      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#6      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:333:14)
<asynchronous suspension>
#7      Loader.buildBodies (package:front_end/src/fasta/loader.dart:243:15)
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:304:20)
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#10     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:302:12)
#11     CompileTask.compile (file://.../pkg/front_end/tool/_fasta/entry_points.dart:272:28)
<asynchronous suspension>
#12     compile.<anonymous closure>.<anonymous closure> (file://.../pkg/front_end/tool/_fasta/entry_points.dart:226:25)
#13     withGlobalOptions.<anonymous closure> (file://.../pkg/front_end/tool/_fasta/command_line.dart:520:13)
#14     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#16     new Future.sync (dart:async/future.dart:224:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#24     withGlobalOptions (file://.../pkg/front_end/tool/_fasta/command_line.dart:513:26)
#25     compile.<anonymous closure> (file://.../pkg/front_end/tool/_fasta/entry_points.dart:219:18)
#26     runProtectedFromAbort (file://.../pkg/front_end/tool/_fasta/command_line.dart:568:24)
#27     compile (file://.../pkg/front_end/tool/_fasta/entry_points.dart:218:16)
#28     compileEntryPoint (file://.../pkg/front_end/tool/_fasta/entry_points.dart:77:11)
#29     main (file://.../pkg/front_end/tool/_fasta/compile.dart:7:33)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by lrhn** [comment]
@eernstg Why can't you have `late` there? It's probably stupid and unnecessary, but I don't see why it's illegal. Is it just an accident of grammar or is it deliberate?

**Comment by eernstg** [comment]
You _can_ have it:

```
<forStatement> ::= 'await'? 'for' '(' <forLoopParts> ')' <statement>

<forLoopParts> ::= <metadata> <declaredIdentifier> 'in' <expression>
    |    <metadata> <identifier> 'in' <expression>
    |    <forInitializerStatement> <expression>? ';' <expressionList>?

<forInitializerStatement> ::= <localVariableDeclaration>
    |    <expression>? ';'
```

and `<localVariableDeclaration>` does admit the modifier `late`.

I believe we had another discussion about `late` in a for-in statement, but I can't immediately find that issue. I think we concluded that `late` should not be allowed in that case,

**Comment by johnniwinther** [comment]
The variable declarations of for statements don't reside in statement-space and are therefore difficult to lower (into a collection of locals and local functions). Given that it serves almost no purpose to the have a late local declaration in for and for-in statements (and since you can always use a predefined late local if you really want to) we agreed that we wouldn't support it.

If we find a use case that carries the weight of the implementation complexity we can always add support for it later.

**Comment by eernstg** [comment]
Found it: dart-lang/language#702 changed the nnbd spec to make `late` a compile-time error when it occurs on a variable which is the iteration variable of a for-in or a C-style for statement.
