### ISSUE TITLE
dart2js fails on language_2/regress/regress40066_test in production mode

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#40100]
In https://dart-review.googlesource.com/c/sdk/+/131200 I'm going to add the following regression test (for https://github.com/dart-lang/sdk/issues/40066):

```dart
import "package:expect/expect.dart";

class A<T> {
  foo(T x) {
    print('T = $T');
    print('x.runtimeType = ${x.runtimeType}');
    print('x is T = ${x is T}');
  }
}

typedef IntFunc = void Function(int);
typedef StringFunc = void Function(String);

void main() {
  void inner<S>(S y) {}

  IntFunc innerOfInt = inner;
  A a = new A<IntFunc>();
  a.foo(innerOfInt);

  StringFunc innerOfString = inner;
  Expect.throwsTypeError(() {
    a.foo(innerOfString);
  });
}
```

dart2js fails on that test in dart2js-minified-strong-linux-x64-d8-try configuration:
```
 /==================================================================================================================\
 | dart2js-production-linux-d8:language_2/regress/regress40066_test is new and failed (RuntimeError, expected Pass) |
 \==================================================================================================================/
 --- Command "dart2js" (took 01.000441s):
 DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart2js --test-mode --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/language_2/regress/regress40066_test.dart -O3 --out=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_language_2_regress_regress40066_test/regress40066_test.js
 exit code:
 0
 stdout:
 Compiled 7,818,701 characters Dart to 39,976 characters JavaScript in 1.44 seconds
 Dart file /b/s/w/ir/tests/language_2/regress/regress40066_test.dart compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js-sdk/tests_language_2_regress_regress40066_test/regress40066_test.js
 --- Command "d8" (took 83ms):
 DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/third_party/d8/linux/d8 out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_language_2_regress_regress40066_test/regress40066_test.js
 exit code:
 1
 stdout:
 T = (int) => void
 x.runtimeType = (dynamic) => void
 x is T = true
 T = (int) => void
 x.runtimeType = (dynamic) => void
 x is T = true
 out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: Expect.throws(TypeError) fails: Did not throw
           throw e;
           ^
 Expect.throws(TypeError) fails: Did not throw
     at Object.b (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_language_2_regress_regress40066_test/regress40066_test.js:98:3)
     at Object.aB (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_language_2_regress_regress40066_test/regress40066_test.js:1008:24)
     at Object.bB (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_language_2_regress_regress40066_test/regress40066_test.js:1006:77)
     at Object.bC (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_language_2_regress_regress40066_test/regress40066_test.js:1007:18)
     at bb (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_language_2_regress_regress40066_test/regress40066_test.js:1013:3)
     at action (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
     at eventLoop (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
     at self.dartMainRunner (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
     at /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_language_2_regress_regress40066_test/regress40066_test.js:1265:39
     at /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-sdk/tests_language_2_regress_regress40066_test/regress40066_test.js:1261:55
 --- Re-run this test:
 python tools/test.py -n dart2js-production-linux-d8 --dart2js-batch language_2/regress/regress40066_test
```

It passes on other dart2js trybots, such as dart2js-strong-hostasserts-linux-ia32-d8-try.

Also, if more prints are added to the test:

```dart
import "package:expect/expect.dart";

class A<T> {
  foo(T x) {
    print('T = $T');
    print('x.runtimeType = ${x.runtimeType}');
    print('x is T = ${x is T}');
  }
}

typedef IntFunc = void Function(int);
typedef StringFunc = void Function(String);

void main() {
  void inner<S>(S y) {
    print('S = $S');
    print('y is S = ${y is S}');
    print('y.runtimeType = ${y.runtimeType}');
  }

  IntFunc innerOfInt = inner;
  innerOfInt(42);
  A a = new A<IntFunc>();
  a.foo(innerOfInt);

  StringFunc innerOfString = inner;
  innerOfString('hi');
  Expect.throwsTypeError(() {
    a.foo(innerOfString);
  });
}
```

then compiler crashes:

```
The compiler crashed: Assertion failure: Local function type variables are not supported.
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      JsToFrontendMapImpl.toBackendTypeVariable (package:compiler/src/js_model/js_world_builder.dart:714:7)
#2      JsToFrontendMapImpl.toBackendEntity (package:compiler/src/js_model/js_world_builder.dart:687:14)
#3      _TypeConverter.visitTypeVariableType (package:compiler/src/js_model/js_world_builder.dart:803:42)
#4      TypeVariableType.accept (package:compiler/src/elements/types.dart:416:15)
#5      _TypeConverter.visit (package:compiler/src/js_model/js_world_builder.dart:751:17)
#6      JsToFrontendMapImpl.toBackendType (package:compiler/src/js_model/js_world_builder.dart:680:16)
#7      JsClosedWorldBuilder._convertBackendUsage.<anonymous closure> (package:compiler/src/js_model/js_world_builder.dart:255:15)
#8      MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#9      new LinkedHashSet.from (dart:collection/linked_hash_set.dart:102:27)
#10     Iterable.toSet (dart:core/iterable.dart:412:18)
#11     JsClosedWorldBuilder._convertBackendUsage (package:compiler/src/js_model/js_world_builder.dart:257:8)
#12     JsClosedWorldBuilder.convertClosedWorld (package:compiler/src/js_model/js_world_builder.dart:65:9)
#13     JsBackendStrategy.createJClosedWorld (package:compiler/src/js_model/js_strategy.dart:180:52)
#14     Compiler.closeResolution (package:compiler/src/compiler.dart:445:25)
#15     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:355:9)
#16     Compiler.compileFromKernel.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:407:17)
#17     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#18     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:406:43)
#19     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#20     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#21     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#22     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#25     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#26     Compiler.run (package:compiler/src/compiler.dart:209:41)
#27     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#28     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#32     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#33     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

/cc @sigmundch @rakudrama

**Comment by rakudrama** [comment]
'production' mode ignores type checks that you didn't write (i.e. all checks except 'x is T' and 'x as T').
The failure to throw on a TypeError is expected in this mode.

The compiler crash is not expected. It looks like an oversight.
