### ISSUE TITLE
Analysis server has terminated

### ISSUE THREAD

**Issue by wilburt** [dart-lang/sdk#40128]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.8.0-edge.c547f5d933e5a10e18b1b26b54a6249e88fa0f1c`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1200  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.c547f5d933e5a10e18b1b26b54a6249e88fa0f1c, server version 1.27.4, FATAL error: RangeError (index): Invalid value: Not in range 0..2, inclusive: 3
#0      List.[] (dart:core-patch/array.dart:15:52)
#1      _FbGenericList.[] (package:analyzer/src/summary/flat_buffers.dart:854:20)
#2      LinkedUnitContext.getInformativeData (package:analyzer/src/summary2/linked_unit_context.dart:434:27)
#3      AstBinaryReader._declaredIdentifier (package:analyzer/src/summary2/ast_binary_reader.dart:80:40)
#4      AstBinaryReader._read_functionDeclaration (package:analyzer/src/summary2/ast_binary_reader.dart:785:9)
#5      AstBinaryReader._readNode (package:analyzer/src/summary2/ast_binary_reader.dart:1782:16)
#6      AstBinaryReader._readNodeList (package:analyzer/src/summary2/ast_binary_reader.dart:1935:19)
#7      AstBinaryReader._read_compilationUnit (package:analyzer/src/summary2/ast_binary_reader.dart:366:23)
#8      AstBinaryReader._readNode (package:analyzer/src/summary2/ast_binary_reader.dart:1720:16)
#9      AstBinaryReader.readNode (package:analyzer/src/summary2/ast_binary_reader.dart:60:14)
#10     LinkedUnitContext._ensureUnitWithDeclarations (package:analyzer/src/summary2/linked_unit_context.dart:1073:26)
#11     LinkedUnitContext.unit_withDeclarations (package:analyzer/src/summary2/linked_unit_context.dart:96:5)
#12     _ElementRequest._createLibraryElement (package:analyzer/src/summary2/linked_element_factory.dart:357:27)
#13     _ElementRequest.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:200:14)
#14     LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:106:45)
#15     LinkedElementFactory.libraryOfUri (package:analyzer/src/summary2/linked_element_factory.dart:138:12)
#16     LinkedUnitContext.directiveLibrary (package:analyzer/src/summary2/linked_unit_context.dart:141:41)
#17     ImportElementImpl.importedLibrary (package:analyzer/src/dart/element/element.dart:5123:47)
#18     LibraryElementImpl.imports.<anonymous closure> (package:analyzer/src/dart/element/element.dart:5550:23)
#19     ListMixin.any (dart:collection/list.dart:132:15)
#20     LibraryElementImpl.imports (package:analyzer/src/dart/element/element.dart:5549:30)
#21     LibraryImportScope._createImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:497:52)
#22     new LibraryImportScope (package:analyzer/src/dart/resolver/scope.dart:401:5)
#23     new LibraryScope (package:analyzer/src/dart/resolver/scope.dart:608:15)
#24     LibraryBuilder.buildElement (package:analyzer/src/summary2/library_builder.dart:212:13)
#25     Linker._computeLibraryScopes (package:analyzer/src/summary2/link.dart:162:15)
#26     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:90:5)
#27     Linker.link (package:analyzer/src/summary2/link.dart:76:5)
#28     link (package:analyzer/src/summary2/link.dart:32:10)
#29     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:173:26)
#30     SetMixin.forEach (dart:collection/set.dart:148:30)
#31     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:128:32)
#32     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:225:17)
#33     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#34     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:223:12)
#35     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:79:5)
#36     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1480:25)
#37     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1265:30)
#38     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#39     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1254:20)
#40     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1336:37)
#41     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:977:39)
<asynchronous suspension>
#42     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1979:24)
<asynchronous suspension>
#43     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1913:5)
#44     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#45     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:84:22)
#46     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#47     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:604:21)
#48     _rootRun (dart:async/zone.dart:1126:13)
#49     _CustomZone.run (dart:async/zone.dart:1023:19)
#50     _runZoned (dart:async/zone.dart:1518:10)
#51     runZoned (dart:async/zone.dart:1465:12)
#52     Driver._captureExceptions (package:analysis_server/src/serv...
```

**Comment by srawlins** [comment]
Reported as recently as Dart 2.12.0-dev

**Comment by srawlins** [comment]
Sorry we did not get to this report; please re-open if you see this again on a new release of Dart.
