### ISSUE TITLE
I dont understand why I am getting this error every 5 minutes

### ISSUE THREAD

**Issue by danielsanchezsa** [dart-lang/sdk#40136]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.3, screens 1920x1080, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/danielsanchezsanchez/Dropbox/Danny/Files/Flutter/MAC/Clima/lib/screens/loading_screen.dart
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<DartObjectImpl>(Instance of 'ConstantVisitor')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:717:53)
#2      ConstantVisitor.visitInstanceCreationExpression (package:analyzer/src/dart/constant/evaluation.dart:1200:29)
#3      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#4      ConstantEvaluationEngine.computeConstantValue (package:analyzer/src/dart/constant/evaluation.dart:184:14)
#5      _ConstantWalker.evaluate (package:analyzer/src/dart/constant/compute.dart:74:22)
#6      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#7      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#8      computeConstants (package:analyzer/src/dart/constant/compute.dart:35:41)
#9      LibraryAnalyzer._computeConstants (package:analyzer/src/dart/analysis/library_analyzer.dart:256:5)
#10     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:169:5)
#11     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#13     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#14     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#15     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#16     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#17     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#23     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#29     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#30     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#31     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#32     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#33     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#41     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#42     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#43     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#44     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#45     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/b6/2zyg8fxs6qs445ycx1fjdg9c0000gn/T/report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.5.0. Please re-open if you see this crash again.
