### ISSUE TITLE
Analyzer crash

### ISSUE THREAD

**Issue by CodeJxer** [dart-lang/sdk#40154]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6817.14`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IC-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.2, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: Failed to handle request: {id: 805, method: edit.getFixes, params: {file: /Users/liaozhixin/Documents/work/殿前生活APP/code/flutter_mall/lib/page/home/home_page.dart, offset: 1790}, clientRequestTime: 1579070453968}
NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      RangeFactory.node (package:analyzer_plugin/utilities/range_factory.dart:69:33)
#2      FixProcessor._addFix_useStaticAccess.<anonymous closure> (package:analysis_server/src/services/correction/fix_internal.dart:4014:36)
#3      DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:56:20)
#4      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#5      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:53:18)
#6      FixProcessor._addFix_useStaticAccess (package:analysis_server/src/services/correction/fix_internal.dart:4013:25)
<asynchronous suspension>
#7      FixProcessor._addFix_useStaticAccess_method (package:analysis_server/src/services/correction/fix_internal.dart:4033:15)
<asynchronous suspension>
#8      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:495:13)
<asynchronous suspension>
#9      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#10     EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:651:46)
<asynchronous suspension>
#11     EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:757:14)
<asynchronous suspension>
#12     EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:280:32)
<asynchronous suspension>
#13     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:383:9)
#14     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#16     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1500:12)
#21     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#22     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#37     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#38     _rootRunUnary (dart:async/zone.dart:1132:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#46     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#47     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#48     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#49     _ConverterStreamEventSink...
```

For additional log information, please append the contents of
file:///private/var/folders/w6/xk2j42rs6qbb4mp40jj9qqgm0000gn/T/report.txt.

**Comment by srawlins** [comment]
Apologies that we did not get to this crash; please re-open if it happens again on a recent version of Dart.
