### ISSUE TITLE
New RTI is throwing assertion failures for a couple Dart Sass tests

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#40152]
A couple Dart Sass tests started failing with 2.8.0-dev.2.0. I've confirmed that it's because of the new dart2js RTI (it doesn't reproduce when we pass `--use-old-rti`), but because it's so closely tied to the type resolution stuff I'm having trouble reproducing it in a minimal form.

## Reproducing

1. Make sure you have [Node.js](https://nodejs.org/en/) installed.

2. Check out Dart Sass:

   ```shellsession
   $ git clone git://github.com/sass/dart-sass
   $ cd dart-sass
   $ pub get
   ```

3. Add `rethrow;` to this `catch` block to make sure you see full stack traces:

   https://github.com/sass/dart-sass/blob/ca63b1ba7d7a9ec3ae376b7d75833110a9b84ac8/lib/src/node.dart#L165-L167

4. Run `git grep dart-lang/sdk#40152` and delete any code that was added to work around this issue.

5. Compile to JS:

   ```shellsession
   $ pub run grinder before-test
   ```

6. Run one of the failing tests:

   ```shellsession
   $ pub run test test/node_api/importer_test.dart -n 'cascade through importers' --js-trace
   ```

## What I've figured out so far

<details>
<summary>Here's an example of the error in question:</summary>

```
00:08 +0 -1: [Node.js] imports cascade through importers [E]                                                                                                                                              
  Assertion failed
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 764:17     Object.wrapException
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 1285:17    Object.assertHelper
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 2920:11    Object._Parser_handleIdentifer
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 2738:17    Object._Parser_parse
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 2568:19    Object._Universe__parseRecipe
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 2547:15    Object._Universe_evalInEnvironment
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 13223:16   Rti._eval$1
  build/npm/sass.dart.js 22407:95                                                   CastList.get$iterator
  build/npm/sass.dart.js 3778:44                                                    Object.get$iterator$ax
  build/npm/sass.dart.js 5919:19                                                    Object.List_List$from
  ===== asynchronous gap ===========================
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 15875:155  _CustomZone.registerBinaryCallback$3$1
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 3851:30    Object._wrapJsFunctionForAsync
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 25838:29   Invoker_waitForOutstandingCallbacks_closure.call$0
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 4287:16    StaticClosure._rootRun
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 15827:114  _CustomZone.run$1$1
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 4463:89    Object._runZoned
  ===== asynchronous gap ===========================
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 15875:155  _CustomZone.registerBinaryCallback$3$1
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 3851:30    Object._wrapJsFunctionForAsync
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 25415:29   Declarer_test_closure.call$0
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 26027:116  <fn>
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 3843:15    _wrapJsFunctionForAsync_closure.$protected
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 13395:12   _wrapJsFunctionForAsync_closure.call$2
  ===== asynchronous gap ===========================
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 15875:155  _CustomZone.registerBinaryCallback$3$1
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 3851:30    Object._wrapJsFunctionForAsync
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 26018:29   Invoker__onRun____closure.call$0
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 13726:50   Future_Future_closure.call$0
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 24258:16   StackZoneSpecification._stack_zone_specification$_run$1$2
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 24301:26   StackZoneSpecification__registerCallback_closure.call$0
  ===== asynchronous gap ===========================
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 15857:123  _CustomZone.registerCallback$1$1
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 15784:71   _CustomZone.bindCallbackGuarded$1
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 4253:44    Object.Timer_Timer
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 3855:9     Object.Future_Future
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 25976:17   <fn>
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 3843:15    _wrapJsFunctionForAsync_closure.$protected
  ===== asynchronous gap ===========================
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 15875:155  _CustomZone.registerBinaryCallback$3$1
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 3851:30    Object._wrapJsFunctionForAsync
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 25965:29   Invoker__onRun___closure.call$0
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 4287:16    StaticClosure._rootRun
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 15827:114  _CustomZone.run$1$1
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 4463:89    Object._runZoned
```

</details>

Note that there are two different JS files present in this stack trace: one of these is the output of compiling Dart Sass to a JS library that can be distributed on npm, and the other is the result of the `test` package compiling my test code to JS. My test code then loads the JS-compiled Dart Sass package and tests it like any other JavaScript API. I've determined that the error goes away even if only the Dart Sass library is compiled with `--use-old-rti`.

Only two tests are triggering this assertion. One of them is "imports cascade through importers":

https://github.com/sass/dart-sass/blob/ca63b1ba7d7a9ec3ae376b7d75833110a9b84ac8/test/node_api/importer_test.dart#L42-L59

The other is "the previous URL is the imported string for imports from importers":

https://github.com/sass/dart-sass/blob/ca63b1ba7d7a9ec3ae376b7d75833110a9b84ac8/test/node_api/importer_test.dart#L390-L402

The commonality seems to be that these are the only tests that pass a list to the `importer` option. Using this information, this is the smallest test I've been able to create that still produces the assertion error:

```dart
test("throws assertion error", () {
  renderSync(RenderOptions(
      data: "",
      importer: [allowInterop((Object url, void _) => null)]));
});
```

**Comment by sigmundch** [comment]
Thanks @nex3 for the detailed repro instructions and the helpful investigation!

@fishythefish - could you take a look?

**Comment by fishythefish** [comment]
We're attempting to evaluate the type variable (recipe) `"ListMixin.E"` against a `CastList` RTI. However, `CastList` doesn't appear in the type metadata (or indeed, anywhere in the compiled test code), causing us to hit an assert.

Note, however, that everything we need *does* appear in the compiled Dart Sass code.

> Note that there are two different JS files present in this stack trace: one of these is the output of compiling Dart Sass to a JS library that can be distributed on npm, and the other is the result of the test package compiling my test code to JS. My test code then loads the JS-compiled Dart Sass package and tests it like any other JavaScript API.

I'm not sure how this loading is currently done, but when the test code loads the Dart Sass package, it needs to be able to do it in a way that's aware that the type information needs to be merged in as well (cf. the deferred loading mechanism).

Per the stack trace, the Sass library invokes `List.from` on what is apparently the result of a `List.castFrom`, hence the following portion of the stack trace:
```
  build/npm/sass.dart.js 22407:95                                                   CastList.get$iterator
  build/npm/sass.dart.js 3778:44                                                    Object.get$iterator$ax
  build/npm/sass.dart.js 5919:19                                                    Object.List_List$from
```
In order to get the element type, this tries to eval the `"ListMixin.E"` recipe against the RTI for the list. 
However, we entered `sass.dart.js` via the compiled test code, and for whatever reason, when `sass.dart.js` says `H.instanceType(receiver)._eval$1(...)`, it doesn't get the one in `sass.dart.js` (which would have access to the right metadata and would presumably work correctly), but the one emitted in the compiled test code:
```
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 2920:11    Object._Parser_handleIdentifer
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 2738:17    Object._Parser_parse
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 2568:19    Object._Universe__parseRecipe
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 2547:15    Object._Universe_evalInEnvironment
  /tmp/dart_test_IRHZCY/test_QKVGWD/importer_test.dart.node_test.dart.js 13223:16   Rti._eval$1
```

@sigmundch: I'm not sure how best to proceed here. As far as I can tell, everything would work if `sass.dart.js` entered the right RTI code, and I don't grok how this code is loaded well enough to understand why it doesn't.

**Comment by sigmundch** [comment]
/cc @rakudrama and I were brainstorming a bit.

It seems here that importer_test and sass are communicating via JS-interop and as a result we could be getting the RTI of List objects leaking from one program to the other (which generally doesn't happen except for JSArray). @rakudrama thinks that this might be addressed if we start using symbols to encode the `$ti` property of JSArray.

@rakudrama is going to look a bit deeper too

**Comment by sigmundch** [comment]
I was able to create a small repro as follows:
**a.dart**:
```dart
mport 'package:js/js.dart';                                                                                                                                                                           
import 'f.dart'; // bogus import prevents a different error in a.js                                                                                                                                                                                      
                                                                                                                                                                                                       
@JS('callOther')                                                                                                                                                                                       
external callOther(List<Function> args);                                                                                                                                                               
                                                                                                                                                                                                       
main() {                                                                                                                                                                                               
  callOther([allowInterop(() => 3)]);                                                                                                                                                                  
}
```

**b.dart**:
```dart
import 'package:js/js.dart';                                                                                                                                                                           
import 'f.dart';                                                                                                                                                                                       
                                                                                                                                                                                                       
@JS('callOther')                                                                                                                                                                                       
external set callOther(x);                                                                                                                                                                             
                                                                                                                                                                                                       
callOtherImpl(List<dynamic> x) {                                                                                                                                                                       
  print("called!");                                                                                                                                                                                    
  List<JSFunction>.unmodifiable(x.cast<JSFunction>());                                                                                                                                                 
}                                                                                                                                                                                                      
main() {                                                                                                                                                                                               
  print("loading b");                                                                                                                                                                                  
  callOther = allowInterop(callOtherImpl);                                                                                                                                                             
}                                                                                                                                                                                                      
```

**f.dart**:
```dart
import 'package:js/js.dart';                                                                                                                                                                           
                                                                                                                                                                                                       
@JS("Function")                                                                                                                                                                                        
class JSFunction implements Function {                                                                                                                                                                 
  external JSFunction(String arg1, [String arg2, String arg3]);                                                                                                                                        
                                                                                                                                                                                                       
  // Note that this just invokes the function with the given arguments, rather                                                                                                                         
  // than calling `Function.prototype.call()`. See sdk#31271.                                                                                                                                          
  external Object call([Object arg1, Object arg2, Object arg3]);                                                                                                                                       
                                                                                                                                                                                                       
  external Object apply(Object thisArg, [List<Object> args]);                                                                                                                                          
}
```

```
> dart2js --server-mode a.dart -oa.js
> dart2js --server-mode b.dart -ob.js
> d8 path-to-preambles.js b.js a.js
```

This prints:
```
loading b                                                                                                                                                                                              
called!                                                                                                                                                                                                
/path/to/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: TypeError: Cannot read property 'ListMixin.E' of undefined                                       
          throw e;                                                                                                                                                                                     
          ^                                                                                                                                                                                            
TypeError: Cannot read property 'ListMixin.E' of undefined                                                                                                                                             
    at Object._Parser_handleIdentifer (a.js:1633:64)                                                                                                                                                   
    at Object._Parser_parse (a.js:1468:17)                                                                                                                                                             
    at Object._Universe__parseRecipe (a.js:1320:19)                                                                                                                                                    
    at Object._Universe_evalInEnvironment (a.js:1302:15)                                                                                                                                               
    at Rti._eval$1 (a.js:2829:16)                                                                                                                                                                      
    at CastList.get$iterator (b.js:3493:79)                                                                                                                                                            
    at Object.get$iterator$a (b.js:2447:43)                                                                                                                                                            
    at Object.List_List$from (b.js:2687:19)                                                                                                                                                            
    at StaticClosure.callOtherImpl (b.js:2858:69)                                                                                                                                                      
    at Object.Primitives_applyFunction (b.js:348:30)                                                                                                                                                                                                   
```

**Comment by rakudrama** [comment]
Thanks for the smaller repro. I'll take it from here.

**Comment by rakudrama** [comment]
Fix available: https://dart-review.googlesource.com/c/sdk/+/131902
I'll commit it once the tree is open.

**Comment by rakudrama** [comment]
The fix is committed.

**Comment by nex3** [comment]
Fix confirmed! Thanks a bunch for the quick turnaround!
