### ISSUE TITLE
server error 500

### ISSUE THREAD

**Issue by Miamoto-Musashi** [dart-lang/sdk#40158]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.8.0-edge.bebc7d3af5bded5ea3f549e90b42c264fe9d1d45`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.2, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.bebc7d3af5bded5ea3f549e90b42c264fe9d1d45, server version 1.27.4, error: type 'ParsedDartFile' is not a subtype of type 'ParsedMoorFile' in type cast
#0      _MoorBaseRequest.parsedMoor (package:moor_generator/src/backends/plugin/services/requests.dart:23:31)
#1      MoorNavigationContributor.computeNavigation (package:moor_generator/src/backends/plugin/services/navigation.dart:20:19)
#2      NavigationGenerator.generateNavigationNotification (package:analyzer_plugin/utilities/navigation/navigation.dart:91:21)
#3      NavigationMixin.sendNavigationNotification (package:analyzer_plugin/plugin/navigation_mixin.dart:97:21)
<asynchronous suspension>
#4      ServerPlugin._sendNotificationForFile (package:analyzer_plugin/plugin/plugin.dart:747:9)
#5      ServerPlugin.sendNotificationsForSubscriptions.<anonymous closure> (package:analyzer_plugin/plugin/plugin.dart:581:9)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#7      ServerPlugin.sendNotificationsForSubscriptions (package:analyzer_plugin/plugin/plugin.dart:579:19)
#8      ServerPlugin.handleAnalysisSetSubscriptions (package:analyzer_plugin/plugin/plugin.dart:355:5)
<asynchronous suspension>
#9      ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:660:24)
<asynchronous suspension>
#10     ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:720:24)
<asynchronous suspension>
#11     PluginIsolateChannel.listen.onData (package:analyzer_plugin/src/channel/isolate_channel.dart:127:18)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#16     _StreamController._add (dart:async/stream_controller.dart:649:7)
#17     _StreamController.add (dart:async/stream_controller.dart:595:5)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file:///private/var/folders/ny/xp6sbyk17_v_bjftblhb5hvw0000gp/T/report.txt.

**Comment by parlough** [comment]
I believe this is likely an issue with the analyzer plugin(moor_generator) you are using. Likely want to file the issue on their repository if this is still hapenning: https://github.com/simolus3/moor

**Comment by srawlins** [comment]
Agreed.
