### ISSUE TITLE
Config dartdevk-weak-linux-release-chrome crashes due to missing files

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#40237]
Consider the following test:

```dart
void main() {}
```

Anything will do, apparently. The setup is as follows, with the root of the sdk as current directory (omitting a bit of output that looks normal):

```dart
> ls tests/lib/typed_data/tiny_test.dart
tests/lib/typed_data/tiny_test.dart
> git sha1
6654aa789538615886acc8c1bb2c6141b1936e13
> rm -rf out
> tools/build.py -m release create_sdk
> tools/build.py -m release --nnbd create_sdk
> tools/test.py -n dartdevk-weak-linux-release-chrome --enable-experiment=non-nullable --nnbd=weak lib/typed_data/tiny
```

Using `--nnbd=strong` makes no difference, in both cases we get a crash with the following output:

<details>
<summary>Output (click to expand)</summary>

```
Test configuration:
    dartdevk-weak-linux-release-chrome(architecture: x64, compiler: dartdevk, mode: release, runtime: chrome, system: linux, nnbd: weak, enable-experiment: [non-nullable], enable-asserts, checked, use-sdk)
Suites tested: lib

FAILED: dartdevk-chrome-checked release_x64 lib/typed_data/tiny_test
Expected: Pass
Actual: Crash
Unexpected compile error.

--- Command "dartdevk" (took 191ms):
DART_CONFIGURATION=ReleaseX64NNBD out/ReleaseX64NNBD/dart-sdk/bin/dartdevc --enable-experiment=non-nullable --enable-experiment=non-nullable --ignore-unrecognized-flags --no-summarize --no-source-map -o /usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64NNBD/generated_compilations/dartdevk-checked-sdk/tests_lib_typed_data_tiny_test/tiny_test.js /usr/local/google/home/eernst/devel/dart/work/sdk/tests/lib/typed_data/tiny_test.dart -s /usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/async_helper.dill=async_helper -s /usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/expect.dill=expect -s /usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/js.dill=js -s /usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/meta.dill=meta (working directory: /usr/local/google/home/eernst/devel/dart/work/sdk/tests/lib/typed_data)

exit code:
253

stdout:
Error: Error when reading 'out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/async_helper.dill': No such file or directory
Error: Error when reading 'out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/expect.dill': No such file or directory
Error: Error when reading 'out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/js.dill': No such file or directory
Error: Error when reading 'out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/meta.dill': No such file or directory
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --enable-experiment=non-nullable --enable-experiment=non-nullable --ignore-unrecognized-flags --no-summarize --no-source-map -o /usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64NNBD/generated_compilations/dartdevk-checked-sdk/tests_lib_typed_data_tiny_test/tiny_test.js /usr/local/google/home/eernst/devel/dart/work/sdk/tests/lib/typed_data/tiny_test.dart -s /usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/async_helper.dill=async_helper -s /usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/expect.dill=expect -s /usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/js.dill=js -s /usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/meta.dill=meta
    dart --version: 2.8.0-edge.6654aa789538615886acc8c1bb2c6141b1936e13 (Mon Jan 20 16:59:11 2020 +0100) on "linux_x64"

Crash when compiling org-dartlang-app:/tests/lib/typed_data/tiny_test.dart,
at character offset null:
Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:414:10)
#5      ProcessedOptions.loadInputSummaries.<anonymous closure> (package:front_end/src/base/processed_options.dart:376:35)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#7      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#8      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:376:67)
<asynchronous suspension>
#9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:89:50)
<asynchronous suspension>
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#14     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#15     new Future.sync (dart:async/future.dart:224:31)
#16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#22     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#23     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#24     compile (package:front_end/src/api_unstable/ddc.dart:194:13)
#25     _compile (package:dev_compiler/src/kernel/command.dart:330:20)
<asynchronous suspension>
#26     compile (package:dev_compiler/src/kernel/command.dart:46:18)
#27     compile (package:dev_compiler/src/compiler/shared_command.dart:375:10)
#28     runBatch (file:///usr/local/google/home/eernst/devel/dart/work/sdk/pkg/dev_compiler/bin/dartdevc.dart:92:22)
#29     main (file:///usr/local/google/home/eernst/devel/dart/work/sdk/pkg/dev_compiler/bin/dartdevc.dart:30:11)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)


#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:414:10)
#5      ProcessedOptions.loadInputSummaries.<anonymous closure> (package:front_end/src/base/processed_options.dart:376:35)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#7      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#8      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:376:67)
<asynchronous suspension>
#9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:89:50)
<asynchronous suspension>
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#14     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#15     new Future.sync (dart:async/future.dart:224:31)
#16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#22     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#23     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#24     compile (package:front_end/src/api_unstable/ddc.dart:194:13)
#25     _compile (package:dev_compiler/src/kernel/command.dart:330:20)
<asynchronous suspension>
#26     compile (package:dev_compiler/src/kernel/command.dart:46:18)
#27     compile (package:dev_compiler/src/compiler/shared_command.dart:375:10)
#28     runBatch (file:///usr/local/google/home/eernst/devel/dart/work/sdk/pkg/dev_compiler/bin/dartdevc.dart:92:22)
#29     main (file:///usr/local/google/home/eernst/devel/dart/work/sdk/pkg/dev_compiler/bin/dartdevc.dart:30:11)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)

--- Re-run this test:
python tools/test.py -n dartdevk-weak-linux-release-chrome --nnbd strong --enable-experiment non-nullable lib/typed_data/tiny_test

[00:00 | 100% | +    0 | -    1]
```
</details>

This occurs locally, but the trybot which indicates configuration 'dartdevk-weak-linux-release-chrome' does not report a crash, it says `Error: Expect.equals(expected: <true>, actual: <false>) fails` ([log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8890729253863586688/+/steps/test_results/0/logs/new_test_failures__logs_/0)).

The crash seems to arise because of an 'Error when reading ...' some `*.dill` files.

I'm reporting this because the output suggests so, and because it also happens after deleting all of `out` and rebuilding created_sdk with and without nnbd, in two separate repositories (the other one at be060649cd38a8581a5347b8f25fb37358c3926d, again: a fresh commit right now).

It could be an issue with dartdevk, it could be the test runner which creates the `-s` options pointing to those non-existing files. Tentatively, I'll label it as area-dartdev.

**Comment by eernstg** [comment]
Solved, thanks @athomas! ;-)

Turns out that it is necessary to run the following extra command locally, in order to have a complete build:

```
> tools/build.py -m release --nnbd dartdevc_test
```
