### ISSUE TITLE
Internal exception when analyzing tests/lib/mirrors/metadata_allowed_values_test.dart

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#40282]
```
./out/ReleaseX64NNBD/dart-sdk/bin/dartanalyzer --enable-experiment=non-nullable  tests/lib/mirrors/metadata_allowed_values_test.dart
```

```
Analyzing tests/lib/mirrors/metadata_allowed_values_test.dart...
Unhandled exception:
NoSuchMethodError: The method 'functionExpression_begin' was called on null.
Receiver: null
Tried calling: functionExpression_begin(Instance of 'FunctionExpressionImpl')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:1276:30)
#2      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4967:49)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7518:20)
#4      ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:363:16)
#5      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1543:10)
#6      UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:3107:45)
#7      ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:629:11)
#8      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:359:49)
#9      ResolverVisitor.visitAnnotation (package:analyzer/src/generated/resolver.dart:576:21)
#10     AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:284:49)
#11     AstResolver.resolve (package:analyzer/src/summary2/ast_resolver.dart:80:10)
#12     MetadataResolver.visitAnnotation (package:analyzer/src/summary2/metadata_resolver.dart:28:17)
#13     AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:284:49)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7518:20)
#15     MetadataResolver.visitClassDeclaration (package:analyzer/src/summary2/metadata_resolver.dart:33:19)
#16     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1519:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7518:20)
#18     MetadataResolver.visitCompilationUnit (package:analyzer/src/summary2/metadata_resolver.dart:53:23)
#19     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2095:49)
#20     LibraryBuilder.resolveMetadata (package:analyzer/src/summary2/library_builder.dart:250:23)
#21     Linker._resolveMetadata (package:analyzer/src/summary2/link.dart:223:15)
#22     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:98:5)
#23     Linker.link (package:analyzer/src/summary2/link.dart:76:5)
#24     link (package:analyzer/src/summary2/link.dart:32:10)
#25     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:173:26)
#26     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:225:17)
#27     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#28     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:223:12)
#29     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:79:5)
#30     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1480:25)
#31     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1411:28)
#32     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#33     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#34     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1004:34)
<asynchronous suspension>
#35     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1979:24)
<asynchronous suspension>
#36     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1913:5)
#37     Driver._createContextAndAnalyze (package:analyzer_cli/src/driver.dart:583:15)
#38     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:249:9)
<asynchronous suspension>
#39     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:184:20)
<asynchronous suspension>
#40     Driver.start (package:analyzer_cli/src/driver.dart:145:38)
#41     main (file:///usr/local/google/home/rmacnak/dart2/sdk/pkg/analyzer_cli/bin/analyzer.dart:18:17)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
```

**Comment by srawlins** [comment]
Thanks for the report; apologies for not getting to this; closing as stale, but please re-open if you can reproduce this on a recent version of Dart.
