### ISSUE TITLE
Migration preview crashes with large removed region near top of file

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40297]
Note that https://dart-review.googlesource.com/c/sdk/+/133081 works around this issue, so to repro, either check out a version prior to that CL, or revert it.

With the following input:
```dart
class C {
  int hash(Iterable<int> elements) {
    if (elements == null) {
      return null.hashCode;
    }
    return 0;
  }
}

List<int> x = [null];
```
the migration tool wants to delete the three lines comprising the "if" statement.  This causes the preview tool to crash when trying to render the preview page.  The exception message and stacktrace are as follows:
```
RangeError: Value not in range: -7
#0      _StringBase.substring (dart:core-patch/string_patch.dart:388:7)
#1      UnitRenderer._computeNavigationContent (package:analysis_server/src/edit/nnbd_migration/unit_renderer.dart:138:39)
#2      UnitRenderer.render (package:analysis_server/src/edit/nnbd_migration/unit_renderer.dart:41:21)
#3      DartFilePage.generatePage (package:analysis_server/src/edit/preview/dart_file_page.dart:31:24)
#4      Page.generate (package:analysis_server/src/status/pages.dart:68:12)
<asynchronous suspension>
#5      PreviewSite.respond (package:analysis_server/src/edit/preview/preview_site.dart:189:31)
#6      PreviewSite.handleGetRequest (package:analysis_server/src/edit/preview/preview_site.dart:115:24)
#7      HttpPreviewServer._handleGetRequest (package:analysis_server/src/edit/preview/http_preview_server.dart:68:22)
#8      HttpPreviewServer._handleServer.<anonymous closure> (package:analysis_server/src/edit/preview/http_preview_server.dart:76:15)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#15     _StreamController._add (dart:async/stream_controller.dart:649:7)
#16     _StreamController.add (dart:async/stream_controller.dart:595:5)
#17     _HttpServer._handleRequest (dart:_http/http_impl.dart:2831:19)
#18     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2590:19)
#19     _rootRunUnary (dart:async/zone.dart:1134:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#24     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#25     _StreamController._add (dart:async/stream_controller.dart:649:7)
#26     _StreamController.add (dart:async/stream_controller.dart:595:5)
#27     _HttpParser._headersEnd (dart:_http/http_parser.dart:374:19)
#28     _HttpParser._doParse (dart:_http/http_parser.dart:703:15)
#29     _HttpParser._parse (dart:_http/http_parser.dart:320:7)
#30     _HttpParser._onData (dart:_http/http_parser.dart:812:5)
#31     _rootRunUnary (dart:async/zone.dart:1134:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#37     _StreamController._add (dart:async/stream_controller.dart:649:7)
#38     _StreamController.add (dart:async/stream_controller.dart:595:5)
#39     _Socket._onData (dart:io-patch/socket_patch.dart:1873:41)
#40     _rootRunUnary (dart:async/zone.dart:1138:13)
#41     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#46     _StreamController._add (dart:async/stream_controller.dart:649:7)
#47     _StreamController.add (dart:async/stream_controller.dart:595:5)
#48     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1415:33)
#49     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
I believe what's happening is that the tool is trying to produce overlays to allow the user to add hints to types within the removed code, causing some bogus offsets to be computed, some of which are negative.  Probably we just shouldn't produce these overlays at all for removed code, since the hints they suggest wouldn't have any effect.

(Note: one possible way to do this would be to make the FixBuilder responsible for generating information about where hints may be added/deleted; this information could be communicated using an `AtomicEdit` object that makes no change.)

**Comment by stereotype441** [comment]
Fixed in d81549e2b24567a0d1983fab2d10d16531ff4bf0.
