### ISSUE TITLE
new rti & ssa: invalid variable reuse in codegen?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#40349]
@cbracken noticed that quiver unit tests failed with an assertion failure from
the new RTI.

The original failure is here:
https://travis-ci.org/google/quiver-dart/jobs/642178912

The issue is easy to run locally in d8 by simply by cloning quiver-dart, then
compiling and running `test/collection/delegates/queue_test.dart` directly.

Here is a small repro w/o quiver:
```dart
import 'dart:collection' show Queue;

abstract class Base<T> {
  Queue<T> get delegate;
  method(T t) => delegate.addFirst(t);
}

class Wrapper extends Base<String> {
  final Queue<String> _a;
  Wrapper(this._a);
  Queue<String> get delegate => _a;
}

dynamic mya = Wrapper(Queue<String>.from(['a', 'b', 'cc']));

void main() {
  mya.method('d');
}
```

The error we get is:
```
TypeError: Cannot read property 'Base.T' of undefined
    at Object._Parser_handleIdentifier (out.js:1329:64)
    at Object._Parser_parse (out.js:1164:17)
    at Object._Universe__parseRecipe (out.js:1016:19)
    at Object._Universe_evalInEnvironment (out.js:998:15)
    at Rti._eval$1 (out.js:2253:16)
    at main (out.js:2050:63)
```

The output of `main` makes me think that we have an SSA bug: 
```js
t2.$ti._precomputed1._check(H._instanceType(t1)._eval$1("Base.T")._check("d"));
t1 = t2._head;
t3 = t2._table;
t1 = (t1 - 1 & t3.length - 1) >>> 0;
t2._head = t1;
C.JSArray_methods.$indexSet(t3, t1, H._instanceType(t1)._eval$1("Base.T")._check("d"));
```

it seems like we are reusing `t1`, but we still have a remaining use for the
`_eval` later in the code.

You can hide the issue by disabling implicit checks or disabling inlining.

@fishythefish @rakudrama

**Comment by sigmundch** [comment]
@rakudrama and I discussed this a bit this morning. We believe there is some broken invariant in generate-at-use/variable-allocator that needs fixing. I'll try to provide more details as I investigate

**Comment by sigmundch** [comment]
@rakudrama found the underlying issue - I landed a change with a fix and a regression test here: https://github.com/dart-lang/sdk/commit/bf6c439e9abb6c95449850319d773e8eba5ef94f

The regression test is similar to the sample above but removes the use of `Queue` entirely.
