### ISSUE TITLE
DDC compiler crash

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40373]
See https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/1641/co19/LanguageFeatures/nnbd/static_errors_A16_t01

DDC Crashes on the following code (co19/LanguageFeatures/nnbd/static_errors_A16_t01)
```dart
import "../../Utils/expect.dart";

class C {
  num pi = 3.14;
  late num p1 = this.pi;
  late final p2 = this.pi;
}

main() {
  Expect.equals(3.14, new C().p1);
  Expect.equals(3.14, new C().p2);
}

```

Another crash https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/1641/co19/LanguageFeatures/nnbd/static_errors_A18_t01
Test is
```dart
import "../../Utils/expect.dart";

late final g;

class C {
  static late final s;
  late final v;
}

main() {
  late final l;

  g = "Lily";
  C.s = "was";
  new C().v = "here";
  l = "Run, Forrest, run";

  Expect.equals("Lily", g);
  Expect.equals("was", C.s);
  Expect.equals("here", C().v);
  Expect.equals("Run, Forrest, run", l);
}
```

**Comment by vsmenon** [comment]
This is the trace:

```
#0      internalProblem (package:front_end/src/fasta/problems.dart:46:3)
#1      unsupported (package:front_end/src/fasta/problems.dart:73:10)
#2      ImplicitFieldType.withNullability (package:front_end/src/fasta/kernel/implicit_field_type.dart:53:12)
#3      AbstractLateFieldEncoding.type= (package:front_end/src/fasta/builder/field_builder.dart:769:25)
#4      SourceFieldBuilder.fieldType= (package:front_end/src/fasta/builder/field_builder.dart:314:20)
#5      SourceLibraryBuilder.addField (package:front_end/src/fasta/source/source_library_builder.dart:2065:20)
#6      SourceLibraryBuilder.addFields (package:front_end/src/fasta/source/source_library_builder.dart:766:7)
#7      OutlineBuilder.endClassFields (package:front_end/src/fasta/source/outline_builder.dart:1741:20)
```

I think this is a known issue?  @johnniwinther
