### ISSUE TITLE
[dart:core] Calling `Uri.decodeComponent` with non-ASCII input throws error

### ISSUE THREAD

**Issue by pd4d10** [dart-lang/sdk#40410]
Dart code as follows would throw error:
```dart
print(Uri.decodeComponent('中'));
```
```
Unhandled exception:
Invalid argument(s): Illegal percent encoding in URI
#0      _Uri._uriDecode (dart:core/uri.dart:2953:11)
#1      Uri.decodeComponent (dart:core/uri.dart:1122:17)
#2      main (file:///tmp/test.dart:2:13)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```
While it works in JavaScript:
```js
console.log(decodeURIComponent('中'))
// "中"
```

**Comment by lrhn** [comment]
It seems Dart is more validating of its input than JavaScript in this case.
Should we change it?

**Comment by pd4d10** [comment]
Thanks.

Personally I don't have a strong will to change it... Just found this inconsistent behavior and report it here

Is there any web standard for URI encode and decode? I think following the standard would be fine.

**Comment by lrhn** [comment]
There is the JavaScript built-in implementation, and obviously it would be nice to be able to use that when compiling to JavaScript.

I'm not sure there is a *standard*. If you look for it, there are a lot of alternative implementations even for JavaScript, with various differences that some people prefer.
