### ISSUE TITLE
Inline method doesn't work in such case

### ISSUE THREAD

**Issue by tieorange** [dart-lang/sdk#40438]
```
static final Map<String, PageRoute Function(RouteSettings)> _routes = {
    mapRoute(AppRoute.home): (settings) =>
        DefaultTransition(settings: settings, screen: HomePage()),
    mapRoute(AppRoute.pagesList): (settings) => DefaultTransition(
          settings: settings,
          screen: PagesListPage(args: settings.arguments as PagesListNavArgs),
        ),
    mapRoute(AppRoute.uploadingPicture): (settings) =>
        DefaultTransition(settings: settings, screen: UploadingPage())
  };

	// TODO: Inline this method
  static String mapRoute(AppRoute route) {
    return route.toString();
  }
```

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.8.0-edge.fc3af737c75931908521e9c36358a151408d6084`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.fc3af737c75931908521e9c36358a151408d6084, server version 1.27.4, error: NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<void>(Instance of 'VisibleRangesComputer')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      VisibleRangesComputer.forNode (package:analysis_server/src/services/refactoring/visible_ranges_computer.dart:70:10)
#2      _getNamesConflictingAt (package:analysis_server/src/services/refactoring/inline_method.dart:158:49)
#3      _getMethodSourceForInvocation (package:analysis_server/src/services/refactoring/inline_method.dart:123:34)
#4      _ReferenceProcessor._inlineMethodInvocation (package:analysis_server/src/services/refactoring/inline_method.dart:530:25)
#5      _ReferenceProcessor._process (package:analysis_server/src/services/refactoring/inline_method.dart:599:7)
#6      InlineMethodRefactoringImpl.checkFinalConditions (package:analysis_server/src/services/refactoring/inline_method.dart:258:17)
#7      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1008:39)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1126:13)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10     _runZoned (dart:async/zone.dart:1518:10)
#11     runZoned (dart:async/zone.dart:1502:12)
#12     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:975:5)
#13     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:853:24)
#14     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:388:16)
#15     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:313:45)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#17     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:309:50)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1502:12)
#22     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:308:5)
#23     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#25     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#26     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#27     _rootRunUnary (dart:async/zone.dart:1134:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#35     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#36     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#37     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#39     _rootRunUnary (dart:async/zone.dart:1134:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#41     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#44     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#45     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#46     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#47     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#48     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#49     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#50     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#51     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#52     _rootRunUnary (dart:async/zone.dart:1134:38)
#53     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#57     _SyncStreamC...
```

For additional log information, please append the contents of
file:///private/var/folders/h9/pxr_mp395_jdg964xrdx8jlw0000gn/T/report.txt.

**Comment by bwilkerson** [comment]
This no longer throws an exception, so it appears that this bug was fixed.
