### ISSUE TITLE
dart2js compiler crashes in training run while the SDK is being built

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#40463]
Patching in this CL https://dart-review.googlesource.com/c/sdk/+/134112 which flips all the VM libraries ot the NNBD and this CL https://dart-review.googlesource.com/c/sdk/+/134384 which works around an issues in CFE (https://github.com/dart-lang/sdk/issues/40460) we get an error from dart2js when tryingto build the sdk.

Here are the details:

```
[2274/2316] ACTION //utils/compiler:dart2js(//build/toolchain/mac:clang_x64)
FAILED: gen/dart2js.dart.snapshot
python ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.packages --snapshot=gen/dart2js.dart.snapshot --snapshot-depfile=/Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/dart2js.dart.snapshot.d --snapshot-kind=app-jit /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/utils/compiler/dart2js.dart.dill --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.packages --libraries-spec=/Users/scheglov/Source/Dart/sdk.git/sdk/sdk_nnbd/lib/libraries.json --enable-experiment=non-nullable /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/utils/compiler/dart2js.dart
Command failed: ./dart --deterministic --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.packages --snapshot=gen/dart2js.dart.snapshot --snapshot-depfile=/Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/dart2js.dart.snapshot.d --snapshot-kind=app-jit /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/utils/compiler/dart2js.dart.dill --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.packages --libraries-spec=/Users/scheglov/Source/Dart/sdk.git/sdk/sdk_nnbd/lib/libraries.json --enable-experiment=non-nullable /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/utils/compiler/dart2js.dart
output: The compiler crashed: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
#0      _BuildJsonListener.pushContainer (dart:convert-patch/convert_patch.dart:129:15)
#1      _BuildJsonListener.beginObject (dart:convert-patch/convert_patch.dart:156:5)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:860:20)
#3      _parseJson (dart:convert-patch/convert_patch.dart:30:10)
#4      JsonDecoder.convert (dart:convert/json.dart:498:36)
#5      JsonCodec.decode (dart:convert/json.dart:156:41)
#6      jsonDecode (dart:convert/json.dart:96:10)
#7      LibrariesSpecification.parse (package:front_end/src/base/libraries_specification.dart:126:22)
#8      getSupportedLibraryNames (package:front_end/src/api_unstable/dart2js.dart:223:33)
#9      CompilerImpl.setupSdk.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:74:36)
```

**Comment by a-siva** [comment]
marking as P0 because it is blocking the VM from turning on NNBB versions of the library and building a SDK.

**Comment by sigmundch** [comment]
This first error seems like a bug in the migration of the convert_patch in https://github.com/dart-lang/sdk/blob/master/sdk_nnbd/lib/_internal/vm/lib/convert_patch.dart#L118

The type of `List<String>` should be `List<dynamic>` or `List<Object?>` because entries in the stack can be either Map or Strings. Changing the code from:
```dart
final List<String> stack = <String>[];
```

to:

```dart
final List<Object?> stack = [];
```

Fixes this first issue for me. There are more issues after that, I'll continue investigating.

**Comment by sigmundch** [comment]
The second issue came from the biging_patch.dart. All the static properties used for caching the last _divRem call are not used as a late field, but as nulllable values. Technically it is not correct to simply switching all of them to use nullable types (since some are used unguarded in non-nullable contexts), but for some reason that alone fixes the build (see https://github.com/dart-lang/sdk/blob/master/sdk_nnbd/lib/_internal/vm/lib/bigint_patch.dart#L110).
