### ISSUE TITLE
We're sorry, you've found a bug in our compiler.

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#40477]
dartdevc -k arguments: --kernel --dart-sdk-summary=/Users/rayk/devlibs/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o packages/sysmodeller/main_web_entrypoint.ddc.js --source-map --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation --summary=packages/built_value/built_value.ddc.dill=packages/built_value/built_value --summary=packages/sysmodeller/model/user.ddc.dill=packages/sysmodeller/model/user --summary=packages/sysmodeller/services/namespace/service.ddc.dill=packages/sysmodeller/services/namespace/service --summary=packages/sysmodeller/store/store.ddc.dill=packages/sysmodeller/store/store --summary=packages/uuid/uuid_util.ddc.dill=packages/uuid/uuid_util --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/convert/convert.ddc.dill=packages/convert/convert --summary=packages/crypto/crypto.ddc.dill=packages/crypto/crypto --summary=packages/uuid/uuid.ddc.dill=packages/uuid/uuid --summary=packages/sysmodeller/config/config.ddc.dill=packages/sysmodeller/config/config --summary=packages/async/async.ddc.dill=packages/async/async --summary=packages/stream_channel/stream_channel.ddc.dill=packages/stream_channel/stream_channel --summary=packages/sysmodeller/services/account/service.ddc.dill=packages/sysmodeller/services/account/service --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino --summary=packages/flutter/material.ddc.dill=packages/flutter/material --summary=packages/sprintf/sprintf.ddc.dill=packages/sprintf/sprintf --summary=packages/i18n_extension/i18n_extension.ddc.dill=packages/i18n_extension/i18n_extension --summary=packages/nested/nested.ddc.dill=packages/nested/nested --summary=packages/provider/provider.ddc.dill=packages/provider/provider --summary=packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols --summary=packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols --summary=packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data --summary=packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules --summary=packages/intl/intl.ddc.dill=packages/intl/intl --summary=packages/intl/date_symbol_data_custom.ddc.dill=packages/intl/date_symbol_data_custom --summary=packages/flutter_localizations/flutter_localizations.ddc.dill=packages/flutter_localizations/flutter_localizations --summary=packages/sysmodeller/services/authorization/service.ddc.dill=packages/sysmodeller/services/authorization/service --summary=packages/lumberdash/lumberdash.ddc.dill=packages/lumberdash/lumberdash --summary=packages/sysmodeller/services/logger/log_provider.ddc.dill=packages/sysmodeller/services/logger/log_provider --summary=packages/sysmodeller/services/logger/service.ddc.dill=packages/sysmodeller/services/logger/service --summary=packages/sysmodeller/app/feature/drawer_menu/drawer_menu.ddc.dill=packages/sysmodeller/app/feature/drawer_menu/drawer_menu --summary=packages/quiver/core.ddc.dill=packages/quiver/core --summary=packages/firebase_core_platform_interface/firebase_core_platform_interface.ddc.dill=packages/firebase_core_platform_interface/firebase_core_platform_interface --summary=packages/firebase_core/firebase_core.ddc.dill=packages/firebase_core/firebase_core --summary=packages/firebase_auth_platform_interface/firebase_auth_platform_interface.ddc.dill=packages/firebase_auth_platform_interface/firebase_auth_platform_interface --summary=packages/firebase_auth/firebase_auth.ddc.dill=packages/firebase_auth/firebase_auth --summary=packages/sysmodeller/services/authentication/service.ddc.dill=packages/sysmodeller/services/authentication/service --summary=packages/sysmodeller/components/components.ddc.dill=packages/sysmodeller/components/components --summary=packages/sysmodeller/app/app.ddc.dill=packages/sysmodeller/app/app --summary=packages/sysmodeller/main.ddc.dill=packages/sysmodeller/main --summary=packages/flutter_web_plugins/flutter_web_plugins.ddc.dill=packages/flutter_web_plugins/flutter_web_plugins --summary=packages/js/js_util.ddc.dill=packages/js/js_util --summary=packages/js/js.ddc.dill=packages/js/js --summary=packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=packages/path/path.ddc.dill=packages/path/path --summary=packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=packages/source_span/source_span.ddc.dill=packages/source_span/source_span --summary=packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner --summary=packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --summary=packages/firebase/src/app.ddc.dill=packages/firebase/src/app --summary=packages/firebase/firebase.ddc.dill=packages/firebase/firebase --summary=packages/firebase_core_web/firebase_core_web.ddc.dill=packages/firebase_core_web/firebase_core_web --summary=packages/firebase_auth_web/firebase_auth_web.ddc.dill=packages/firebase_auth_web/firebase_auth_web --summary=packages/sysmodeller/generated_plugin_registrant.ddc.dill=packages/sysmodeller/generated_plugin_registrant --packages=file:///var/folders/hh/thyw7j2x3d17p2cmlq3xtgw80000gn/T/kernel_builder_YZKnRu/.packages --module-name=packages/sysmodeller/main_web_entrypoint --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///Users/rayk/devlibs/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=/var/folders/hh/thyw7j2x3d17p2cmlq3xtgw80000gn/T/ddk_builder_1Dj5m6/used_inputs.txt package:sysmodeller/main_web_entrypoint.dart
    dart --version: 2.8.0-dev.0.0.flutter-c547f5d933 (Fri Dec 27 00:43:14 2019 +0000) on "macos_x64"

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:164:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:414:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:295:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:46:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:410:10)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Failed after 2.2s

**Comment by rayk** [comment]
Same as #40359 , was fixed after a ```flutter upgrade``` .

This issue is not appearing in flutter/flutter@c3f590a
