### ISSUE TITLE
'package:front_end/src/fasta/kernel/class_hierarchy_builder.dart': Failed assertion: line 2477 pos 9: 'instance != null': No instance of #lib1::D1* as dart.core::Object found for dart.core::Object::toString

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#40506]
After we opt-in the core libraries we run into a compiler crash on couple of tests

Here is an example

```
/============================================================================================================================\
| language_2/nonfunction_type_aliases/usage_type_variable_error_test failed again (CompileTimeError -> Crash, expected Pass) |
\============================================================================================================================/

--- Command "fasta" (took 244ms):
(cd /b/s/w/ir/ ; DART_CONFIGURATION=ReleaseX64NNBD ./out/ReleaseX64NNBD/dart ./pkg/front_end/tool/_fasta/compile.dart --verify -o ./out/ReleaseX64NNBD/generated_compilations/fasta/tests_language_2_nonfunction_type_aliases_usage_type_variable_error_test/out.dill --platform ./out/ReleaseX64NNBD/vm_platform_strong.dill --enable-experiment=non-nullable,nonfunction-type-aliases --packages=./.packages ./tests/language_2/nonfunction_type_aliases/usage_type_variable_error_test.dart )

exit code:
253

stdout:
tests/language_2/nonfunction_type_aliases/usage_type_variable_error_test.dart:47:16: Error: The type 'T' can't be mixed in.
abstract class D2 extends C with T {}
               ^
tests/language_2/nonfunction_type_aliases/usage_type_variable_error_test.dart:49:16: Error: The type 'T' can't be mixed in.
abstract class D4 = C with T;
               ^
tests/language_2/nonfunction_type_aliases/usage_type_variable_error_test.dart:46:7: Error: The type 'T' can't be used as supertype.
class D1 extends T {}
      ^
tests/language_2/nonfunction_type_aliases/usage_type_variable_error_test.dart:47:16: Error: The type 'T' can't be used as supertype.
abstract class D2 extends C with T {}
               ^
tests/language_2/nonfunction_type_aliases/usage_type_variable_error_test.dart:48:16: Error: The type 'T' can't be used as supertype.
abstract class D3 implements T {}
               ^
tests/language_2/nonfunction_type_aliases/usage_type_variable_error_test.dart:49:16: Error: The type 'T' can't be used as supertype.
abstract class D4 = C with T;
               ^

stderr:
Unhandled exception:
  Crash when compiling null,
at character offset null:
'package:front_end/src/fasta/kernel/class_hierarchy_builder.dart': Failed assertion: line 2477 pos 9: 'instance != null': No instance of #lib1::D1* as dart.core::Object found for dart.core::Object::toString.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      InterfaceConflict.computeMemberType (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2477:9)
#3      InterfaceConflict.check (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2508:32)
#4      SourceLoader.checkAbstractMembers (package:front_end/src/fasta/source/source_loader.dart:1007:30)
#5      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:316:14)
<asynchronous suspension>
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#7      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:288:12)
#8      CompileTask.buildOutline (file:///b/s/w/ir/pkg/front_end/tool/_fasta/entry_points.dart:306:38)
<asynchronous suspension>
#9      CompileTask.compile (file:///b/s/w/ir/pkg/front_end/tool/_fasta/entry_points.dart:318:39)
#10     BatchCompiler.batchCompileImpl (file:///b/s/w/ir/pkg/front_end/tool/_fasta/entry_points.dart:189:16)
#11     BatchCompiler.batchCompileArguments.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/pkg/front_end/tool/_fasta/entry_points.dart:164:39)
#12     withGlobalOptions.<anonymous closure> (file:///b/s/w/ir/pkg/front_end/tool/_fasta/command_line.dart:513:13)
#13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#14     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#15     new Future.sync (dart:async/future.dart:222:31)
#16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#17     _rootRun (dart:async/zone.dart:1134:13)
#18     _CustomZone.run (dart:async/zone.dart:1038:19)
#19     _runZoned (dart:async/zone.dart:1537:10)
#20     runZoned (dart:async/zone.dart:1480:12)
#21     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#22     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#23     withGlobalOptions (file:///b/s/w/ir/pkg/front_end/tool/_fasta/command_line.dart:506:26)
#24     BatchCompiler.batchCompileArguments.<anonymous closure> (file:///b/s/w/ir/pkg/front_end/tool/_fasta/entry_points.dart:163:15)
#25     runProtectedFromAbort (file:///b/s/w/ir/pkg/front_end/tool/_fasta/command_line.dart:561:24)
#26     BatchCompiler.batchCompileArguments (file:///b/s/w/ir/pkg/front_end/tool/_fasta/entry_points.dart:162:12)
#27     BatchCompiler.run (file:///b/s/w/ir/pkg/front_end/tool/_fasta/entry_points.dart:144:19)
<asynchronous suspension>
#28     batchEntryPoint (file:///b/s/w/ir/pkg/front_end/tool/_fasta/entry_points.dart:129:8)
#29     main (file:///b/s/w/ir/pkg/front_end/tool/_fasta/batch.dart:7:33)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
```

**Comment by johnniwinther** [comment]
The test is for the `nonfunction-type-alias` experiment so it is not of high priority.

**Comment by johnniwinther** [comment]
This seems to have been fixed.
