### ISSUE TITLE
Dart does not throw compile error when function with Null return value returns int.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40513]
Dart VM version: 2.8.0-edge.aadcb4418b1a7ccbb74a7cc925ad55020ce4a924 (Thu Feb 6 02:00:49 2020 +0000) on "linux_x64"

The following test example declares two methods which return incorrect values:
``` dart
class A {
  Null getNull() => 1;
  String getString() => 1;
}

main() {
  print(A().getNull());
}
```
Analyzer throws two compile errors here (for  `Null getNull() => 1;` and `String getString() => 1;` lines).

It expected that dart should behave in the same way, however this is not so: it throws compile error for `String getString() => 1;` line only.

Sample output is:

> $  dartanalyzer test.dart
> Analyzing test.dart...
>   error • The literal '1' with type 'int' isn't of expected type 'Null'. • test.dart:2:21 • invalid_cast_literal
>   error • A value of type 'int' can't be returned from method 'getString' because it has a return type of 'String'. • test.dart:3:25 • return_of_invalid_type
> 2 errors found.
> $  dart test.dart
> test.dart:3:25: Error: A value of type 'int' can't be assigned to a variable of type 'String'.
>   String getString() => 1;
>                         ^

If I change source to the following, runtime exception is thrown instead of compile error here:
``` dart
class A {
  Null getNull() => 1;
}

main() {
  print(A().getNull());
}
```
Sample output is:

> $  dart test.dart
> Unhandled exception:
> type 'int' is not a subtype of type 'Null'
> #0      A.getNull (file:///home/iarkh/dart/dart-sdk/sdk/tests/co191/src/LanguageFeatures/nnbd/test.dart:2:21)
> #1      main (file:///home/iarkh/dart/dart-sdk/sdk/tests/co191/src/LanguageFeatures/nnbd/test.dart:6:13)
> #2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
> #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
> $  dartanalyzer test.dart
> Analyzing test.dart...
>   error • The literal '1' with type 'int' isn't of expected type 'Null'. • test.dart:2:21 • invalid_cast_literal
> 1 error found.

**Comment by johnniwinther** [comment]
The CFE currently only produces nnbd-specific warnings and error behind a special `--force-nnbd-checks' flag.

To check `foo.dart` in weak mode run:
```
dart pkg/front_end/tool/fasta.dart compile --enable-experiment=non-nullable --force-nnbd-checks foo.dart
``` 
and to check `foo.dart` in strong mode run:
```
dart pkg/front_end/tool/fasta.dart compile --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong foo.dart
```
where `pkg/front_end/tool/fasta.dart` is in the Dart repo.

This generates a `foo.dart.dill` file next to `foo.dart` which can be run with the VM using
```
dart foo.dart.dill
```

The flag will be removed once it is not blocking development on the nnbd sdk due to false positives.

**Comment by lrhn** [comment]
I believe this should be an error pre-NNBD as well.
The type `int` is assignable to `Null` only through a down-cast, and the type of the literal `1` is *exact*, so we do not allow a downcast (since it's *known* to fail at runtime).

The analyzer does give an error for `Null x = 1;`.

**Comment by stefantsov** [comment]
Because the expected error message is emitted in NNBD mode when the `--force-nnbd-checks` flag is enabled, the issue isn't an NNBD issue.  Removing the `NNBD` flag.
