### ISSUE TITLE
nnbd override check error

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#40512]
I'm still seeing the following with Flutter (running on [unforked ddc](https://dart-review.googlesource.com/c/sdk/+/134562) with nnbd) after yesterday's fixes:

```
AssetNotFoundException: flutter|lib/src/widgets/actions.ddc.js          
Error compiling dartdevc module:flutter|lib/material.ddc.js             

packages/flutter/src/material/dropdown.dart:1037:7: Error: Applying the mixin 'WidgetsBindingObserver' to 'State' introduces an erroneous override of
'toString'.
class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindingObserver {
      ^^^^^^^^^^^^^^^^^^^^
packages/flutter/src/widgets/binding.dart: Context: The method 'WidgetsBindingObserver.toString' has fewer named arguments than those of overridden
method 'DiagnosticableMixin.toString'.
packages/flutter/src/foundation/diagnostics.dart: Context: This is the overridden method ('toString').


                                                                        
                                                                        
AssetNotFoundException: flutter|lib/src/widgets/actions.ddc.js          
Error compiling dartdevc module:flutter|lib/src/widgets/actions.ddc.js  

packages/flutter/src/widgets/focus_manager.dart:366:7: Error: Applying the mixin 'ChangeNotifier' to 'Object with DiagnosticableTreeMixin' introduces
an erroneous override of 'toString'.
class FocusNode with DiagnosticableTreeMixin, ChangeNotifier {
      ^^^^^^^^^
packages/flutter/src/foundation/change_notifier.dart: Context: The method 'ChangeNotifier.toString' has fewer named arguments than those of
overridden method 'DiagnosticableTreeMixin.toString'.
packages/flutter/src/foundation/diagnostics.dart: Context: This is the overridden method ('toString').
```

I can repro with (sdk opted in):

baz.dart (opted out):
```dart
// @dart = 2.6
import 'baz2.dart';

class C extends Object with A, B {
}

void main() {
  print(B());
  print(C());
}
```

baz2.dart (opted out):
```dart
// @dart = 2.6
library baz2;

mixin A {
  String toString({String s = "hello"}) => s;
}

class B extends Object {
}
```

where the two files are compiled separately.  I don't see the problem if they are compiled together.

**Comment by vsmenon** [comment]
fyi - @johnniwinther - only issue I'm hitting so far with flutter web.

**Comment by vsmenon** [comment]
I can repro without my unfork CL if I add opt-out `@dart` to examples above (updated).  You'll need to build with  `--nnbd`.  Then, with the `ddb` tool in `pkg/dev_compiler/tools`:

```
>  ddb -d --nnbd weak baz2.dart

>  ddb -d --nnbd weak -s baz2.dill baz.dart

org-dartlang-app:/baz.dart:5:7: Error: Applying the mixin 'B' to 'Object with A' introduces an erroneous override of 'toString'.
class C extends Object with A, B {
      ^
org-dartlang-app:/baz2.dart:8:7: Context: The method 'B.toString' has fewer named arguments than those of overridden method 'A.toString'.
class B extends Object {
      ^
org-dartlang-app:/baz2.dart:5:10: Context: This is the overridden method ('toString').
  String toString({String s = "hello"}) => s;
         ^
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --kernel --modules=common --dart-sdk-summary=/Users/vsm/dart/sdk/xcodebuild/ReleaseX64NNBD/dart-sdk/lib/_internal/ddc_sdk.dill --summary=baz2.dill --enable-experiment=non-nullable -o /Users/vsm/ddctest/baz.js /Users/vsm/ddctest/baz.dart
    dart --version: 2.8.0-dev.3.0 (Thu Jan 16 14:59:50 2020 +0100) on "macos_x64"

Crash when compiling null,
at character offset null:
'package:front_end/src/fasta/kernel/forwarding_node.dart': Failed assertion: line 467 pos 12: 'candidate is! DelayedMember': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      ForwardingNode.getCandidateAt (package:front_end/src/fasta/kernel/forwarding_node.dart:467:12)
#3      ForwardingNode._computeCovarianceFixes (package:front_end/src/fasta/kernel/forwarding_node.dart:108:28)
#4      ForwardingNode.finalize (package:front_end/src/fasta/kernel/forwarding_node.dart:69:24)
#5      AbstractMemberOverridingImplementation.check (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2684:12)
#6      SourceLoader.checkAbstractMembers (package:front_end/src/fasta/source/source_loader.dart:1007:30)
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:316:14)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:288:12)
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:108:28)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#12     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#13     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#14     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#16     new Future.sync (dart:async/future.dart:224:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#24     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#25     compile (package:front_end/src/api_unstable/ddc.dart:194:13)
#26     _compile (package:dev_compiler/src/kernel/command.dart:329:20)
<asynchronous suspension>
#27     compile (package:dev_compiler/src/kernel/command.dart:45:18)
#28     compile (package:dev_compiler/src/compiler/shared_command.dart:391:10)
#29     main (file:///Users/vsm/dart/sdk/pkg/dev_compiler/bin/dartdevc.dart:32:24)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)


#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      ForwardingNode.getCandidateAt (package:front_end/src/fasta/kernel/forwarding_node.dart:467:12)
#3      ForwardingNode._computeCovarianceFixes (package:front_end/src/fasta/kernel/forwarding_node.dart:108:28)
#4      ForwardingNode.finalize (package:front_end/src/fasta/kernel/forwarding_node.dart:69:24)
#5      AbstractMemberOverridingImplementation.check (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2684:12)
#6      SourceLoader.checkAbstractMembers (package:front_end/src/fasta/source/source_loader.dart:1007:30)
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:316:14)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:288:12)
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:108:28)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#12     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#13     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#14     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#16     new Future.sync (dart:async/future.dart:224:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#24     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#25     compile (package:front_end/src/api_unstable/ddc.dart:194:13)
#26     _compile (package:dev_compiler/src/kernel/command.dart:329:20)
<asynchronous suspension>
#27     compile (package:dev_compiler/src/kernel/command.dart:45:18)
#28     compile (package:dev_compiler/src/compiler/shared_command.dart:391:10)
#29     main (file:///Users/vsm/dart/sdk/pkg/dev_compiler/bin/dartdevc.dart:32:24)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

**Comment by johnniwinther** [comment]
This might have been fixed by https://dart-review.googlesource.com/c/sdk/+/135303

@vsmenon Can you verify?

**Comment by vsmenon** [comment]
This is likely fixed now.  I was able to build Flutter last Friday without the original error.  I will close and re-open if I see it again.
