### ISSUE TITLE
read_dill_from_binary_md_test fails with extension methods

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#40629]
`pkg/front_end/test/read_dill_from_binary_md_test` is failing on https://dart-review.googlesource.com/c/sdk/+/134960/6 with the following trace:

```
Test configuration:
    cfe-unittest-asserts-release-linux(architecture: x64, compiler: dartk, mode: release, runtime: vm, system: linux, builder-tag: cfe, timeout: 240, enable-asserts, use-sdk)
Suites tested: pkg

FAILED: dartk-vm release_x64 pkg/front_end/test/read_dill_from_binary_md_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 16.000806s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart --enable_asserts --ignore-unrecognized-flags --packages=/usr/local/google/home/fishythefish/dart-sdk/sdk/.packages /usr/local/google/home/fishythefish/dart-sdk/sdk/pkg/front_end/test/read_dill_from_binary_md_test.dart

exit code:
255

stdout:
Compiled dart2js in 8515 ms
Read binary.md in 18 ms

stderr:
Unhandled exception:
Unexpected tag. Expected 115 but got 164 (around 1064885).
#0      BinaryMdDillReader._checkTag (file:///usr/local/google/home/fishythefish/dart-sdk/sdk/pkg/front_end/test/binary_md_dill_reader.dart:564:11)
#1      BinaryMdDillReader._readBinary (file:///usr/local/google/home/fishythefish/dart-sdk/sdk/pkg/front_end/test/binary_md_dill_reader.dart:533:9)
#2      BinaryMdDillReader._readBinary (file:///usr/local/google/home/fishythefish/dart-sdk/sdk/pkg/front_end/test/binary_md_dill_reader.dart:519:24)
#3      BinaryMdDillReader._readBinary (file:///usr/local/google/home/fishythefish/dart-sdk/sdk/pkg/front_end/test/binary_md_dill_reader.dart:531:25)
#4      BinaryMdDillReader._readBinary (file:///usr/local/google/home/fishythefish/dart-sdk/sdk/pkg/front_end/test/binary_md_dill_reader.dart:519:24)
#5      BinaryMdDillReader._readDill (file:///usr/local/google/home/fishythefish/dart-sdk/sdk/pkg/front_end/test/binary_md_dill_reader.dart:146:25)
#6      BinaryMdDillReader.attemptRead (file:///usr/local/google/home/fishythefish/dart-sdk/sdk/pkg/front_end/test/binary_md_dill_reader.dart:43:12)
#7      testDart2jsCompile (file:///usr/local/google/home/fishythefish/dart-sdk/sdk/pkg/front_end/test/read_dill_from_binary_md_test.dart:37:22)
<asynchronous suspension>
#8      main (file:///usr/local/google/home/fishythefish/dart-sdk/sdk/pkg/front_end/test/read_dill_from_binary_md_test.dart:19:9)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n cfe-unittest-asserts-release-linux pkg/front_end/test/read_dill_from_binary_md_test
```

Tag `115` seems to be `Extension`, and I'm not sure what `164` corresponds to.

This stack of changes enables and uses extension methods in the dart2js codebase for the first time, which is probably why this went unnoticed until now.

**Comment by jensjoha** [comment]
Thanks! I'll fix it when I get a chance. Probably next week.

**Comment by jensjoha** [comment]
Turned out I had a little time today, and that it was an easy fix :)
