### ISSUE TITLE
Memory leak of dart::bin::File in dart:io

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#40648]
```
=================================================================
==61235==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 96 byte(s) in 3 object(s) allocated from:
    #0 0x55f6b110ac76 in operator new(unsigned long) /b/s/w/ir/kitchen-workdir/llvm-project/compiler-rt/lib/lsan/lsan_interceptors.cc:224:35
    #1 0x55f6b1139834 in dart::bin::File::OpenFD(int) ../../out/ReleaseLSANX64/../../runtime/bin/file_linux.cc:206:10
    #2 0x55f6b1139834 in dart::bin::File::Open(dart::bin::Namespace*, char const*, dart::bin::File::FileOpenMode) ../../out/ReleaseLSANX64/../../runtime/bin/file_linux.cc:244
    #3 0x55f6b1136485 in dart::bin::File::OpenRequest(dart::bin::CObjectArray const&) ../../out/ReleaseLSANX64/../../runtime/bin/file.cc:923:16
    #4 0x55f6b11169c2 in dart::bin::IOServiceCallback(long, _Dart_CObject*) ../../out/ReleaseLSANX64/../../runtime/bin/io_service.cc:44:7
    #5 0x55f6b1362e12 in dart::NativeMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >) ../../out/ReleaseLSANX64/../../runtime/vm/native_message_handler.cc:41:3
    #6 0x55f6b136047d in dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) ../../out/ReleaseLSANX64/../../runtime/vm/message_handler.cc:232:16
    #7 0x55f6b1360c7f in dart::MessageHandler::TaskCallback() ../../out/ReleaseLSANX64/../../runtime/vm/message_handler.cc:446:20
    #8 0x55f6b1470776 in dart::ThreadPool::Worker::Loop() ../../out/ReleaseLSANX64/../../runtime/vm/thread_pool.cc:382:11
    #9 0x55f6b14705fd in dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseLSANX64/../../runtime/vm/thread_pool.cc:434:27
    #10 0x55f6b13e83c5 in dart::ThreadStart(void*) ../../out/ReleaseLSANX64/../../runtime/vm/os_thread_linux.cc:138:5
    #11 0x7f20d241cfb6 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8fb6)

Indirect leak of 12 byte(s) in 3 object(s) allocated from:
    #0 0x55f6b110ac76 in operator new(unsigned long) /b/s/w/ir/kitchen-workdir/llvm-project/compiler-rt/lib/lsan/lsan_interceptors.cc:224:35
    #1 0x55f6b1139841 in dart::bin::File::OpenFD(int) ../../out/ReleaseLSANX64/../../runtime/bin/file_linux.cc:206:19
    #2 0x55f6b1139841 in dart::bin::File::Open(dart::bin::Namespace*, char const*, dart::bin::File::FileOpenMode) ../../out/ReleaseLSANX64/../../runtime/bin/file_linux.cc:244
    #3 0x55f6b1136485 in dart::bin::File::OpenRequest(dart::bin::CObjectArray const&) ../../out/ReleaseLSANX64/../../runtime/bin/file.cc:923:16
    #4 0x55f6b11169c2 in dart::bin::IOServiceCallback(long, _Dart_CObject*) ../../out/ReleaseLSANX64/../../runtime/bin/io_service.cc:44:7
    #5 0x55f6b1362e12 in dart::NativeMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >) ../../out/ReleaseLSANX64/../../runtime/vm/native_message_handler.cc:41:3
    #6 0x55f6b136047d in dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) ../../out/ReleaseLSANX64/../../runtime/vm/message_handler.cc:232:16
    #7 0x55f6b1360c7f in dart::MessageHandler::TaskCallback() ../../out/ReleaseLSANX64/../../runtime/vm/message_handler.cc:446:20
    #8 0x55f6b1470776 in dart::ThreadPool::Worker::Loop() ../../out/ReleaseLSANX64/../../runtime/vm/thread_pool.cc:382:11
    #9 0x55f6b14705fd in dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseLSANX64/../../runtime/vm/thread_pool.cc:434:27
    #10 0x55f6b13e83c5 in dart::ThreadStart(void*) ../../out/ReleaseLSANX64/../../runtime/vm/os_thread_linux.cc:138:5
    #11 0x7f20d241cfb6 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8fb6)

SUMMARY: LeakSanitizer: 108 byte(s) leaked in 6 allocation(s).

--- Re-run this test:
python tools/test.py -n dartk-lsan-linux-release-x64 standalone_2/io/file_test
```

**Comment by sortie** [comment]
Thanks for the bug. I'll take a look at the issue next week.

**Comment by rmacnak-google** [comment]
This test started passing after changes to the test in 3d6c8ccbdaa57b17dcb7293e82cfba413fff0d34. Reverting that commit locally reveals the leak can still occur.

**Comment by sortie** [comment]
@zichangg Is this something you'd want to look into?

**Comment by zichangg** [comment]
I investigated a bit but somehow didn't finish.

**Comment by a-siva** [comment]
File* C objects created from asynchronous file requests are leaked if the isolate shutdowns before the reply from the IO thread is processed and the File* C object is assigned to the Dart file object using File_SetPointer.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/210761

**Comment by a-siva** [comment]
Fix for this landed (see CL above), closing this.
