### ISSUE TITLE
Crash migrating package:flutter

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40670]
```
[ 2m 44.438s] Server Error: Exception while running dartfix: RangeError (start): Invalid value: Not in range 0..3374, inclusive: 3890
#0      RangeError.checkValidRange (dart:core/errors.dart:337:7)
#1      _StringBase.replaceRange (dart:core-patch/string_patch.dart:595:22)
#2      InfoBuilder._explainUnit (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:584:27)
#3      InfoBuilder.explainMigration (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:78:27)
<asynchronous suspension>
#4      MigrationState.refresh (package:analysis_server/src/edit/nnbd_migration/migration_state.dart:42:49)
#5      NonNullableFix.finish (package:analysis_server/src/edit/fix/non_nullable_fix.dart:80:17)
#6      FixCodeProcessor.finishCodeTasks (package:analysis_server/src/edit/fix/fix_code_task.dart:32:18)
#7      EditDartFix.compute (package:analysis_server/src/edit/edit_dartfix.dart:145:13)
<asynchronous suspension>
#8      EditDomainHandler.dartfix (package:analysis_server/src/edit/edit_domain.dart:106:41)
#9      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:376:9)
#10     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:316:45)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#12     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:312:50)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1502:12)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:311:5)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#22     _rootRunUnary (dart:async/zone.dart:1134:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#34     _rootRunUnary (dart:async/zone.dart:1134:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#47     _rootRunUnary (dart:async/zone.dart:1134:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#53     _StreamController._add (dart:async/stream_controller.dart:649:7)
#54     _StreamController.add (dart:async/stream_controller.dart:595:5)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1870:41)
#56     _rootRunUnary (dart:async/zone.dart:1138:13)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#61     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#62     _StreamController._add (dart:async/stream_controller.dart:649:7)
#63     _StreamController.add (dart:async/stream_controller.dart:595:5)
#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1415:33)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#68     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ 2m 44.438s] #0      RangeError.checkValidRange (dart:core/errors.dart:337:7)
#1      _StringBase.replaceRange (dart:core-patch/string_patch.dart:595:22)
#2      InfoBuilder._explainUnit (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:584:27)
#3      InfoBuilder.explainMigration (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:78:27)
<asynchronous suspension>
#4      MigrationState.refresh (package:analysis_server/src/edit/nnbd_migration/migration_state.dart:42:49)
#5      NonNullableFix.finish (package:analysis_server/src/edit/fix/non_nullable_fix.dart:80:17)
#6      FixCodeProcessor.finishCodeTasks (package:analysis_server/src/edit/fix/fix_code_task.dart:32:18)
#7      EditDartFix.compute (package:analysis_server/src/edit/edit_dartfix.dart:145:13)
<asynchronous suspension>
#8      EditDomainHandler.dartfix (package:analysis_server/src/edit/edit_domain.dart:106:41)
#9      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:376:9)
#10     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:316:45)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#12     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:312:50)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1502:12)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:311:5)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#22     _rootRunUnary (dart:async/zone.dart:1134:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#34     _rootRunUnary (dart:async/zone.dart:1134:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#47     _rootRunUnary (dart:async/zone.dart:1134:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#53     _StreamController._add (dart:async/stream_controller.dart:649:7)
#54     _StreamController.add (dart:async/stream_controller.dart:595:5)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1870:41)
#56     _rootRunUnary (dart:async/zone.dart:1138:13)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#61     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#62     _StreamController._add (dart:async/stream_controller.dart:649:7)
#63     _StreamController.add (dart:async/stream_controller.dart:595:5)
#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1415:33)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#68     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by farheen21** [comment]
can you please provide some extra information related to this bug
