### ISSUE TITLE
dart2js crashes when compiling flutter_frontend_server with -O4

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#40688]
```
jonahwilliams-macbookpro2:src jonahwilliams$ out/host_debug_unopt/dart-sdk/bin/dart2js flutter/flutter_frontend_server/bin/starter.dart -o4
^C
jonahwilliams-macbookpro2:src jonahwilliams$ out/host_debug_unopt/dart-sdk/bin/dart2js flutter/flutter_frontend_server/bin/starter.dart -O4
third_party/dart/pkg/front_end/lib/src/fasta/compiler_context.dart:129:20:
Internal Error: Runtime type information not available for type_variable_local(runWithOptions.T) in (local(CompilerContext.runWithOptions#c), j:anonymous_closure_local(CompilerContext_runWithOptions_closure)) for j:closure_call(CompilerContext_runWithOptions_closure.call).
  static Future<T> runWithOptions<T>(
                   ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.8.0-edge.8bead5d8e824330cad4ebba7c39b368a116ea2ec), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Unhandled exception:
Assertion failure: Runtime type information not available for type_variable_local(runWithOptions.T) in (local(CompilerContext.runWithOptions#c), j:anonymous_closure_local(CompilerContext_runWithOptions_closure)) for j:closure_call(CompilerContext_runWithOptions_closure.call).
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      LocalsHandler.readLocal (package:compiler/src/ssa/locals_handler.dart:326:11)
#2      TypeBuilder._buildEnvironmentForType (package:compiler/src/ssa/type_builder.dart:377:12)
#3      TypeBuilder.analyzeTypeArgumentNewRti (package:compiler/src/ssa/type_builder.dart:295:9)
#4      KernelSsaGraphBuilder._buildGenerator (package:compiler/src/ssa/builder_kernel.dart:1396:31)
#5      KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder_kernel.dart:1296:7)
#6      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:495:13)
#7      CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#8      KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:447:21)
#9      KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:515:22)
#10     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#11     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:497:18)
#12     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:356:21)
#13     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:80:29)
#14     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:453:30)
#15     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:333:43)
#16     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:464:29)
#17     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:70)
#18     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#19     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:32)
#20     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#21     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:28)
#22     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#23     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:456:18)
#24     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:266:12)
#25     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:282:5)
#26     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:452:16)
#27     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#28     Compiler.emptyQueue (package:compiler/src/compiler.dart:451:14)
#29     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:477:7)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#31     Compiler.processQueue (package:compiler/src/compiler.dart:470:14)
#32     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:382:5)
#33     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:284:9)
#34     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:432:9)
#35     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#36     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#37     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#38     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#39     new Future.sync (dart:async/future.dart:224:31)
#40     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#41     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#42     Compiler.run (package:compiler/src/compiler.dart:209:41)
#43     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#44     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#45     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#47     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#48     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#49     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by jonahwilliams** [comment]
happens on a local engine checkout on macOS

**Comment by sigmundch** [comment]
@jonahwilliams - I'd love to get some additional context.

Is this for some experiment or some upcoming feature? Is this working for you with lower optimization levels? For instance, it may be possible to circumvent this specific compile-time error with the `--disable-rti-optimization` flag.

In part, I'm trying to get some clarity on how we should prioritize this issue. But in part, I want to make sure you are exploring something we currently support. In particular, long ago we had support for compiling and running dart2js itself in JavaScript, but that has not been maintained for a long time, and a result I fear that common pieces like the CFE, might not run properly in JS today (e.g. anywhere where we depend on low-level 64-bits could go off-rails pretty easily). 

/cc @fishythefish re the optimization issue.

**Comment by fishythefish** [comment]
cc @rakudrama

**Comment by jonahwilliams** [comment]
This is just for experimentation, so it is not a high priority. Building with the default optimization level (O2?) works fine and I'm otherwise able to run the CFE compiled to JavaScript: https://jonahwilliams.github.io/ . I'll try with `--disable-rti-optimization` when I'm back in the office tomorrow

**Comment by sigmundch** [comment]
There is a high chance we've fixed this when fixing other issues with the rti optimizations.

I tried rerunning the command above and I was getting failures for different reasons (frontend-server depends on the VM CFE target, which embeds ffi in some of it's transformations). After removing those dependencies, I was able to get it to compile without errors. I'm going to close this optimistically, but please follow up if this is still an issue.
