### ISSUE TITLE
Dart should give compile error for WhereIterables

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#40708]
This happens VERY OFTEN with Flutter developers.

Check this simple code:

```dart
void main(List<String> arguments) async {
  var aList = <int>[1, 2, 3];

  aList = aList.where((element) => element.isEven);

  print(aList);
}
```

It compiles properly but gives runtime error:

```Unhandled exception:
type 'WhereIterable<int>' is not a subtype of type 'List<int>'
#0      main (file:///C:/Users/shina/Desenvolvimento/dart_projects/tests_dart/example/main.dart:31:3)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

Well, if "where" doesn't return an `List`, why do the compiler let it be assigned to a `List<int>`?
It would save us tons of hours of developemnt trying to debug that.

**Comment by shinayser** [comment]
It seems that this will be fixed on NNBD release. 
Source: https://github.com/dart-lang/language/issues/192
