### ISSUE TITLE
cfe stacktrace with nnbd

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#40707]
This is an odd, but consistent stack trace I get when doing a hot reload / frontend_server compile with flutter web with the DDC unfork CL patched in (https://dart-review.googlesource.com/c/sdk/+/134562).

I don't see a use of `typeArguments` in the line in question.  All libraries (other than the SDK) are opted out.  I'm changing a string and recompiling.

```
Unhandled exception:                                                    
Crash when compiling null,                                              
at character offset null:                                               
NoSuchMethodError: The getter 'typeArguments' was called on null.       
Receiver: null                                                          
Tried calling: typeArguments                                            
#0      Reference.asClass (package:kernel/ast.dart:240:7)               
#1      Supertype.classNode (package:kernel/ast.dart:6788:36)           
#2      Substitution.fromSupertype (package:kernel/type_algebra.dart:203:19)
#3      SourceClassBuilder._addMissingNoSuchMethodForwarders            
(package:front_end/src/fasta/source/source_class_builder.dart:544:50)
#4      SourceClassBuilder.addNoSuchMethodForwarders                    
(package:front_end/src/fasta/source/source_class_builder.dart:668:15)
#5      SourceLoader.addNoSuchMethodForwarders (package:front_end/src/fasta/source/source_loader.dart:1036:21)
#6      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:317:14)
<asynchronous suspension>                                               
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:287:12)
#10     IncrementalCompiler.computeDelta.<anonymous closure>            
(package:front_end/src/fasta/incremental_compiler.dart:233:52)
<asynchronous suspension>                                               
#11     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
#12     CompilerContext.runInContext.<anonymous closure>.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:46)
#13     new Future.sync (dart:async/future.dart:224:31)                 
#14     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#15     _rootRun (dart:async/zone.dart:1126:13)                         
#16     _CustomZone.run (dart:async/zone.dart:1023:19)                  
#17     _runZoned (dart:async/zone.dart:1518:10)                        
#18     runZoned (dart:async/zone.dart:1465:12)                         
#19     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#20     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:175:20)
#21     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:58:46)
#22     FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:832:47)
<asynchronous suspension>                                               
#23     _FlutterFrontendCompiler.recompileDelta (package:flutter_frontend_server/server.dart:43:22)
#24     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1198:20)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#30     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#31     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#32     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#33     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#34     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#46     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#50     _StreamController._add (dart:async/stream_controller.dart:649:7)
#51     _StreamController.add (dart:async/stream_controller.dart:595:5) 
#52     _Socket._onData (dart:io-patch/socket_patch.dart:1870:41)       
#53     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#56     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#57     _StreamController._add (dart:async/stream_controller.dart:649:7)
#58     _StreamController.add (dart:async/stream_controller.dart:595:5) 
#59     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1415:33)
#60     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)       
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)   
#63     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#64     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

This is patched onto a recent version of flutter / dart (commit https://github.com/dart-lang/sdk/commit/e187e42593e86f2e23a197ec2a9190e2690a3096).

**Comment by yjbanov** [comment]
I'm seeing this in Flutter on a pre-NNBD SDK. To reproduce sync to https://github.com/flutter/flutter/commit/159710ecc5ef59f31ee535a4bc970eaaa809f075, then run:

```
cd dev/benchmarks/macrobenchmarks
flutter run --local-engine=host_debug_unopt -d web-server --web-port=8080 lib/web_benchmarks.dart
```

Edit the `kMaxSampleCount` constant in `dev/benchmarks/macrobenchmarks/lib/src/web/recorder.dart`. Hit Shift + R on the command line (to kick off hot restart).

Result: the stack trace like the one in the original issue description.

**Comment by vsmenon** [comment]
This might become a blocker for unfork:

https://github.com/flutter/engine/pull/17818

Siva restarted the run on the failing bot, but we were seeing:

```
00:09 +85: loading /tmp/master_framework/flutter/packages/flutter/test/examples/sector_layout_test.dart                                                                                                
00:09 +85: loading /tmp/master_framework/flutter/packages/flutter/test/material/expansion_tile_test.dart                                                                                               
00:09 +85: /tmp/master_framework/flutter/packages/flutter/test/examples/sector_layout_test.dart: Sector layout can paint                                                                               Unhandled exception:
Crash when compiling null,
at character offset null:
NoSuchMethodError: The getter 'typeArguments' was called on null.
Receiver: null
Tried calling: typeArguments
#0      Substitution.fromSupertype (package:kernel/type_algebra.dart:201:19)
#1      SourceClassBuilder._addMissingNoSuchMethodForwarders (package:front_end/src/fasta/source/source_class_builder.dart:809:50)
#2      SourceClassBuilder.addNoSuchMethodForwarders (package:front_end/src/fasta/source/source_class_builder.dart:933:15)
#3      SourceLoader.addNoSuchMethodForwarders (package:front_end/src/fasta/source/source_loader.dart:1035:21)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:325:14)
<asynchronous suspension>
#5      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#7      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:292:12)
#8      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:276:52)
<asynchronous suspension>
#9      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
#10     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#11     new Future.sync (dart:async/future.dart:222:31)
#12     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZoned (dart:async/zone.dart:1550:10)
#17     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#18     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:213:20)
#19     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:68:46)
#20     FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:854:47)
<asynchronous suspension>
#21     _FlutterFrontendCompiler.recompileDelta (package:flutter_frontend_server/server.dart:45:22)
#22     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1226:20)
```

**Comment by vsmenon** [comment]
fyi - @franklinyow

**Comment by a-siva** [comment]
I have seen a similar stack trace when running the flutter tests with the unforked dart CL merged in, it does not reproduce consistently


```
Crash when compiling null,
at character offset null:
NoSuchMethodError: The getter 'typeArguments' was called on null.
Receiver: null
Tried calling: typeArguments
#0      Substitution.fromSupertype (package:kernel/type_algebra.dart:201:19)
#1      SourceClassBuilder._addMissingNoSuchMethodForwarders (package:front_end/src/fasta/source/source_class_builder.dart:809:50)
#2      SourceClassBuilder.addNoSuchMethodForwarders (package:front_end/src/fasta/source/source_class_builder.dart:933:15)
#3      SourceLoader.addNoSuchMethodForwarders (package:front_end/src/fasta/source/source_loader.dart:1035:21)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:325:14)
<asynchronous suspension>
#5      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#7      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:292:12)
#8      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:276:52)
<asynchronous suspension>
#9      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
#10     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#11     new Future.sync (dart:async/future.dart:222:31)
#12     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.d
```art:123:19)

**Comment by johnniwinther** [comment]
@jensjoha can you take a look at this? My suspicion is that there is an inconsistency in the class hierarchy between incremental compilation delta; the members found through `getInterfaceMembers`, `getDispatchTargets` and `getDeclaredMembers` have enclosing classes that are not found as supertypes.

**Comment by jensjoha** [comment]
I can't seem to reproduce any of this. Does anyone have a more specific reproduction?

**Comment by vsmenon** [comment]
I'm only able to repro with flutter with the unfork cl patched in so far.

With that, if I checkout and cd into [gallery](https://github.com/flutter/gallery) :
```
> flutter run -d chrome
```

I edit `lib/routes.dart` to add `// @dart=2.9` to the top of that file, and I press "r" to trigger a hot restart.

I get the error below:

[cfe_error.txt](https://github.com/dart-lang/sdk/files/4528903/cfe_error.txt)

This is the top of the trace:
```
Unhandled exception:                                                    
Crash when compiling null,                                              
at character offset null:                                               
NoSuchMethodError: The getter 'typeArguments' was called on null.       
Receiver: null                                                          
Tried calling: typeArguments                                            
#0      Reference.asClass (package:kernel/ast.dart:236:28)              
#1      Supertype.classNode (package:kernel/ast.dart:7894:36)           
#2      Substitution.fromSupertype (package:kernel/type_algebra.dart:203:19)
#3      SourceClassBuilder._addMissingNoSuchMethodForwarders (package:front_end/src/fasta/source/source_class_builder.dart:809:50)
#4      SourceClassBuilder.addNoSuchMethodForwarders (package:front_end/src/fasta/source/source_class_builder.dart:933:15)
#5      SourceLoader.addNoSuchMethodForwarders (package:front_end/src/fasta/source/source_loader.dart:1035:21)
#6      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:325:14)
<asynchronous suspension>                                               
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:292:12)
#10     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:276:52)
<asynchronous suspension>                                               
#11     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
#12     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#13     new Future.sync (dart:async/future.dart:222:31)                 
#14     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
```

**Comment by jensjoha** [comment]
Can I get a link to something specific to checkout?

**Comment by vsmenon** [comment]
To repro the above, you'll need a standard flutter framework and engine checkout, and you'd need to apply @a-siva 's PR to engine and build:

https://github.com/flutter/engine/pull/17818

With that, I checkout gallery (see link above), and run:

> flutter run  --local-engine=host_debug_unopt -d chrome

**Comment by vsmenon** [comment]
Note, Siva's PR is pointing to this branch of the Dart SDK (with the unfork applied):

https://dart.googlesource.com/sdk/+/refs/heads/nnbd-unfork

Perhaps possible to trigger via a frontend_server test?  I seem to hit the error reliably when I switch the Dart language version (`// @dart=2.9`) on a file upstream from the entry point.

**Comment by jensjoha** [comment]
So something like this?

```
cd [...]/flutter/engine/src/flutter
git checkout 2ecf2e7026134974f12701472f3017185a7c61da
git checkout -b a-siva-dart-roll
git pull https://github.com/a-siva/engine.git dart-roll
./flutter/tools/gn --unoptimized --full-dart-sdk
ninja -C out/host_debug_unopt

cd [...]/where/you/have/gallary
flutter run --local-engine=host_debug_unopt -d chrome

edit lib/routes.dart to add // @dart=2.9 to the top of that file, and press "r" to trigger a hot restart.
```

 --- I don't get a crash from that...

**Comment by vsmenon** [comment]
Hmm.  You may need a `gclient sync` have pulling Siva's PR.

**Comment by vsmenon** [comment]
Also, you may be able to repro by running the `build_and_test_linux_unopt_debug` bot tests that are failing on the PR itself:

https://github.com/flutter/engine/pull/17818

**Comment by vsmenon** [comment]
Marking this a P0 as it's the only Flutter blocker left for NNBD unfork.  

@johnniwinther @jensjoha @a-siva - can we set up a meeting on Monday if the CFE team cannot repro themselves?

**Comment by jensjoha** [comment]
I had forgotten about the gclient sync... I can reproduce now, and will look into it on Monday.

**Comment by vsmenon** [comment]
Great - thanks!

**Comment by jensjoha** [comment]
Smaller reproduction at https://dart-review.googlesource.com/c/sdk/+/144764.

**Comment by jensjoha** [comment]
Notice that - at least for this smaller reproduction - it doesn't matter whether "enableNullSafety" is on in the target flags (but it has to use that sdk), but that trackWidgetCreation has to be enabled, and that it's going weird stuff with that when it crashes (package:flutter/src/widgets/widget_inspector.dart::_HasCreationLocation).

**Comment by johnniwinther** [comment]
A CL is in progress: https://dart-review.googlesource.com/c/sdk/+/144821

**Comment by vsmenon** [comment]
Thanks for the repro and turnaround!  I've rolled to Flutter PR past this commit to see if this gets us green:

https://github.com/flutter/engine/pull/17818
