### ISSUE TITLE
Analyser crash

### ISSUE THREAD

**Issue by bhaskar106** [dart-lang/sdk#40747]
Every time I do anything with flutter the following crash is occuring.
even with `flutter doctor` the below crash is produced.

[10:59:03 am] [Analyzer] [Error] 
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x28
version=2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "linux_x64"
thread=15273, isolate=main(0x3622ef0)
Stack dump aborted because GetAndValidateThreadStackBounds failed.
[10:59:03 am] [Analyzer] [Error] Aborted (core dumped)
[10:59:03 am] [Analyzer] [Info] Process terminated! 134, null
[10:59:03 am] [FlutterDaemon] [Error] 
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x28
version=2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "linux_x64"
thread=15276, isolate=main(0x1de3e30)
Stack dump aborted because GetAndValidateThreadStackBounds failed.

[10:59:03 am] [FlutterDaemon] [Error] /home/sanju/flutter/bin/flutter: line 192: 15270 Aborted                 (core dumped) "$DART" --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
[10:59:03 am] [FlutterDaemon] [Info] Process terminated! 134, null
[10:59:15 am] [Analyzer] [Info] ==> {"id":"4","method":"edit.getFixes","params":{"file":"/home/sanju/Documents/Flutterprojects/emailapp/lib/main.dart","offset":0},"clientRequestTime":1582522155974}
[10:59:15 am] [Analyzer] [Info] ==> {"id":"5","method":"edit.getAssists","params":{"file":"/home/sanju/Documents/Flutterprojects/emailapp/lib/main.dart","length":0,"offset":0},"clientRequestTime":1582522155979}
[10:59:15 am] [Analyzer] [Info] ==> {"id":"6","method":"edit.getAvailableRefactorings","params":{"file":"/home/sanju/Documents/Flutterprojects/emailapp/lib/main.dart","length":0,"offset":0},"clientRequestTime":1582522155980}
[10:59:15 am] [Analyzer] [Info] ==> {"id":"7","method":"analysis.setPriorityFiles","params":{"files":["/home/sanju/Documents/Flutterprojects/emailapp/lib/main.dart"]},"clientRequestTime":1582522155982}
[10:59:15 am] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at b.sendMessage (/home/sanju/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js:1:58996)
	at b.sendMessage (/home/sanju/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js:1:53518)
	at /home/sanju/.vsc…
[10:59:15 am] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at b.sendMessage (/home/sanju/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js:1:58996)
	at b.sendMessage (/home/sanju/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js:1:53518)
	at /home/sanju/.vsc…
[10:59:15 am] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at b.sendMessage (/home/sanju/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js:1:58996)
	at b.sendMessage (/home/sanju/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js:1:53518)
	at /home/sanju/.vsc…
[10:59:16 am] [Analyzer] [Info] ==> {"id":"8","method":"edit.getFixes","params":{"file":"/home/sanju/Documents/Flutterprojects/emailapp/lib/main.dart","offset":971},"clientRequestTime":1582522156161}
[10:59:16 am] [Analyzer] [Info] ==> {"id":"9","method":"edit.getAssists","params":{"file":"/home/sanju/Documents/Flutterprojects/emailapp/lib/main.dart","length":0,"offset":971},"clientRequestTime":1582522156163}
[10:59:16 am] [Analyzer] [Info] ==> {"id":"10","method":"edit.getAvailableRefactorings","params":{"file":"/home/sanju/Documents/Flutterprojects/emailapp/lib/main.dart","length":0,"offset":971},"clientRequestTime":1582522156167}

**Comment by cyberpwnn** [comment]
This has been going on for months now. Could we get some more information on this?

```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[5:24:35 PM] [Analyzer] [Info] ==> {"id":"383","method":"analysis.getHover","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\constant.dart","offset":310},"clientRequestTime":1585862675447}
[5:24:35 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[5:24:35 PM] [Analyzer] [Info] ==> {"id":"384","method":"edit.getFixes","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\constant.dart","offset":310},"clientRequestTime":1585862675458}
[5:24:35 PM] [Analyzer] [Info] ==> {"id":"385","method":"edit.getAssists","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\constant.dart","length":0,"offset":310},"clientRequestTime":1585862675459}
[5:24:35 PM] [Analyzer] [Info] ==> {"id":"386","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\constant.dart","length":0,"offset":310},"clientRequestTime":1585862675460}
[5:24:35 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[5:24:35 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[5:24:35 PM] [Analyzer] [Info] ==> {"id":"387","method":"analysis.updateContent","params":{"files":{"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\constant.dart":{"edits":[{"id":"","length":1,"offset":309,"replacement":""}],"type":"change"}}},"clientRequestTime":1585862675678}
[5:24:35 PM] [Analyzer] [Info] ==> {"id":"388","method":"analysis.updateContent","params":{"files":{"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\constant.dart":{"edits":[{"id":"","length":0,"offset":309,"replacement":"7"}],"type":"change"}}},"clientRequestTime":1585862675744}
[5:24:35 PM] [Analyzer] [Info] ==> {"id":"389","method":"edit.getFixes","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\constant.dart","offset":310},"clientRequestTime":1585862675995}
[5:24:35 PM] [Analyzer] [Info] ==> {"id":"390","method":"edit.getAssists","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\constant.dart","length":0,"offset":310},"clientRequestTime":1585862675996}
[5:24:35 PM] [Analyzer] [Info] ==> {"id":"391","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\constant.dart","length":0,"offset":310},"clientRequestTime":1585862675997}
[5:24:35 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[5:24:35 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[5:24:37 PM] [Analyzer] [Info] ==> {"id":"392","method":"edit.format","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\constant.dart","lineLength":130,"selectionLength":0,"selectionOffset":0},"clientRequestTime":1585862677098}
```

**Comment by srawlins** [comment]
Apologies that we did not get a chance to look at this crash. Please re-open if you see this again with a recent version of Dart.
