### ISSUE TITLE
JIT-OPTCOUNTER-SLOWPATH-DebugX64: expected: ValueFromRawSmi(raw_smi) == value

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#40754]
Reproduction Info:

```DART SDK REVISION: Dart VM version: 2.8.0-edge.ce5fb94014d4859ace1d1732ac7c51599010a6ea (Sun Feb 23 21:32:44 2020 +0000) on "linux_x64"


dart runtime/tools/dartfuzz/dartfuzz.dart --no-fp --no-ffi --no-flat --seed 1031911076 fuzz.dart

out/DebugX64/dart --optimization_counter_threshold=1 --use-slow-path --old_gen_heap_size=128 fuzz.dart
```

Stack trace:

```
../../runtime/vm/object.h: 7973: error: expected: ValueFromRawSmi(raw_smi) == value
version=2.8.0-edge.ce5fb94014d4859ace1d1732ac7c51599010a6ea (Sun Feb 23 21:32:44 2020 +0000) on "linux_x64"
thread=8849, isolate=main(0x5636007caa00)
isolate_instructions=5635fe0fbce0, vm_instructions=5635fe0fbce0
  pc 0x00005635fe4d118c fp 0x00007ff6f6ffd8c0 dart::Profiler::DumpStackTrace(void*)
  pc 0x00005635fe0f9562 fp 0x00007ff6f6ffd9a0 dart::Assert::Fail(char const*, ...)
  pc 0x00005635fe6b59f5 fp 0x00007ff6f6ffd9d0 /b/s/w/ir/out/DebugX64/dart+0x1f0a9f5
  pc 0x00005635fe6b5484 fp 0x00007ff6f6ffda40 /b/s/w/ir/out/DebugX64/dart+0x1f0a484
  pc 0x00005635fe6ab605 fp 0x00007ff6f6ffdf00 /b/s/w/ir/out/DebugX64/dart+0x1f00605
  pc 0x00005635fe6a8a65 fp 0x00007ff6f6ffdfe0 dart::RangeAnalysis::EliminateRedundantBoundsChecks()
  pc 0x00005635fe6a7ba1 fp 0x00007ff6f6ffe050 dart::RangeAnalysis::Analyze()
  pc 0x00005635fe6e621a fp 0x00007ff6f6ffe190 /b/s/w/ir/out/DebugX64/dart+0x1f3b21a
  pc 0x00005635fe6e5643 fp 0x00007ff6f6ffe230 dart::CompilerPass::Run(dart::CompilerPassState*) const
  pc 0x00005635fe6e5bae fp 0x00007ff6f6ffe250 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)
  pc 0x00005635fe76b429 fp 0x00007ff6f6ffe970 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  pc 0x00005635fe76c36f fp 0x00007ff6f6ffeb90 /b/s/w/ir/out/DebugX64/dart+0x1fc136f
  pc 0x00005635fe76cefc fp 0x00007ff6f6ffec30 dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)
  pc 0x00005635fe76df97 fp 0x00007ff6f6ffece0 dart::BackgroundCompiler::Run()
  pc 0x00005635fe58af8c fp 0x00007ff6f6ffed30 dart::ThreadPool::Worker::Loop()
  pc 0x00005635fe58aa91 fp 0x00007ff6f6ffed80 dart::ThreadPool::Worker::Main(unsigned long)
  pc 0x00005635fe4caf92 fp 0x00007ff6f6ffeed0 /b/s/w/ir/out/DebugX64/dart+0x1d1ff92
-- End of DumpStackTrace
```

cc/ @alexmarkov

**Comment by sstrickl** [comment]
Using ASSERT_EQUAL instead:

```bash
$ dart runtime/tools/dartfuzz/dartfuzz.dart --no-fp --no-ffi --no-flat --seed 1031911076 fuzz.dart

$ out/DebugX64/dart --optimization_counter_threshold=1 --use-slow-path --old_gen_heap_size=128 fuzz.dart
<...>
../../runtime/vm/object.h: 8007: error: expected "value" = 9223372034707292161, actual "ValueFromRawSmi(raw_smi)" = -2147483647
```

Unsurprising, as the original value was a 63 bit int, so when shifted left 1 than (arithmetically) right 1, it becomes negative.

Only thing we could really do is add `ASSERT(Utils::IsInt(kSmiBits, value))`, but then we don't even get through `python tools/build.py -m debug -a x64 runtime_kernel` without it triggering:

```bash
$ ninja -C out/DebugX64 -j1000 -l64 runtime_kernel runtime_precompiled
ninja: Entering directory `out/DebugX64'
[703/717] ACTION //utils/kernel-service:kernel-service_snapshot(//build/toolchain/linux:clang_x64)
FAILED: gen/kernel-service.dart.snapshot 
python ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=/.../home/sstrickl/dart/sdk/.packages --snapshot=gen/kernel-service.dart.snapshot --snapshot-depfile=/.../home/sstrickl/dart/sdk/out/DebugX64/gen/kernel-service.dart.snapshot.d --snapshot-kind=app-jit /.../home/sstrickl/dart/sdk/out/DebugX64/gen/utils/kernel-service/kernel-service_snapshot.dart.dill --train file:///.../home/sstrickl/dart/sdk/pkg/compiler/lib/src/dart2js.dart
Command failed: ./dart --deterministic --packages=/.../home/sstrickl/dart/sdk/.packages --snapshot=gen/kernel-service.dart.snapshot --snapshot-depfile=/.../home/sstrickl/dart/sdk/out/DebugX64/gen/kernel-service.dart.snapshot.d --snapshot-kind=app-jit /.../home/sstrickl/dart/sdk/out/DebugX64/gen/utils/kernel-service/kernel-service_snapshot.dart.dill --train file:///.../home/sstrickl/dart/sdk/pkg/compiler/lib/src/dart2js.dart
output: ../../runtime/vm/object.h: 8005: error: expected: Utils::IsInt(kSmiBits, value)
version=2.8.0-edge.043d08a6b1614bf42834b8ae90991415ffa99e7f (Fri Feb 28 09:39:06 2020 +0000) on "linux_x64"
thread=105577, isolate=main(0x55ba6ce75400)
isolate_instructions=55ba6abfb100, vm_instructions=55ba6abfb100
  pc 0x000055ba6b09b246 fp 0x00007f5c6e9fbfe0 dart::Profiler::DumpStackTrace(bool)
  pc 0x000055ba6b09b184 fp 0x00007f5c6e9fc120 dart::Profiler::DumpStackTrace(void*)
  pc 0x000055ba6b72dac5 fp 0x00007f5c6e9fc140 Dart_DumpNativeStackTrace
  pc 0x000055ba6abf7e33 fp 0x00007f5c6e9fc2f0 dart::Assert::Fail(char const*, ...)
  pc 0x000055ba6adee950 fp 0x00007f5c6e9fc370 ./dart+0x1cb5950
  pc 0x000055ba6b2dd354 fp 0x00007f5c6e9fc560 ./dart+0x21a4354
  pc 0x000055ba6b2da242 fp 0x00007f5c6e9fc670 dart::RangeAnalysis::EliminateRedundantBoundsChecks()
  pc 0x000055ba6b2d96c8 fp 0x00007f5c6e9fc6d0 dart::RangeAnalysis::Analyze()
  pc 0x000055ba6b3209c5 fp 0x00007f5c6e9fc820 ./dart+0x21e79c5
  pc 0x000055ba6b31e492 fp 0x00007f5c6e9fc8f0 dart::CompilerPass::Run(dart::CompilerPassState*) const
  pc 0x000055ba6b31ec61 fp 0x00007f5c6e9fc910 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)
  pc 0x000055ba6b3bb23c fp 0x00007f5c6e9fd370 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  pc 0x000055ba6b3bc0ae fp 0x00007f5c6e9fd720 ./dart+0x22830ae
  pc 0x000055ba6b3bcc16 fp 0x00007f5c6e9fd7e0 dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)
  pc 0x000055ba6b11df0f fp 0x00007f5c6e9fd870 ./dart+0x1fe4f0f
  pc 0x000055ba6b11dc25 fp 0x00007f5c6e9fd9a0 dart::DRT_OptimizeInvokedFunction(dart::NativeArguments)
  pc 0x00007f5c6ea01097 fp 0x00007f5c6e9fd9e0 Unknown symbol
  pc 0x00007f5c6ea014ad fp 0x00007f5c6e9fda18 Unknown symbol
  pc 0x00007f5c6c4a9f64 fp 0x00007f5c6e9fda78 Unknown symbol
  pc 0x00007f5c6c4a9b6e fp 0x00007f5c6e9fdaf0 Unknown symbol
  pc 0x00007f5c6c4a96f6 fp 0x00007f5c6e9fdb48 Unknown symbol
  pc 0x00007f5c6c4ae34d fp 0x00007f5c6e9fdba0 Unknown symbol
  pc 0x00007f5c6c4a62ce fp 0x00007f5c6e9fdc00 Unknown symbol
  pc 0x00007f5c6c4a408f fp 0x00007f5c6e9fdc48 Unknown symbol
  pc 0x00007f5c6c4a1e32 fp 0x00007f5c6e9fdca8 Unknown symbol
  pc 0x00007f5c6c4a03c8 fp 0x00007f5c6e9fdd48 Unknown symbol
  pc 0x00007f5c6c4830a0 fp 0x00007f5c6e9fddc8 Unknown symbol
  pc 0x00007f5c6c482e90 fp 0x00007f5c6e9fde40 Unknown symbol
  pc 0x00007f5c6c4827a9 fp 0x00007f5c6e9fdee8 Unknown symbol
  pc 0x00007f5c6c4822f4 fp 0x00007f5c6e9fdf38 Unknown symbol
  pc 0x00007f5c6c481eb1 fp 0x00007f5c6e9fdfb0 Unknown symbol
  pc 0x00007f5c6c480eb2 fp 0x00007f5c6e9fe030 Unknown symbol
  pc 0x00007f5c6dc82895 fp 0x00007f5c6e9fe078 Unknown symbol
  pc 0x00007f5c6dc825ba fp 0x00007f5c6e9fe0c8 Unknown symbol
  pc 0x00007f5c6dcf0903 fp 0x00007f5c6e9fe140 Unknown symbol
  pc 0x00007f5c6dcf0676 fp 0x00007f5c6e9fe1b0 Unknown symbol
  pc 0x00007f5c6dcefc56 fp 0x00007f5c6e9fe250 Unknown symbol
  pc 0x00007f5c6dcfa8ff fp 0x00007f5c6e9fe2b0 Unknown symbol
  pc 0x00007f5c6dc821e8 fp 0x00007f5c6e9fe2f0 Unknown symbol
  pc 0x00007f5c6dc81e34 fp 0x00007f5c6e9fe330 Unknown symbol
  pc 0x00007f5c6dc81d27 fp 0x00007f5c6e9fe370 Unknown symbol
  pc 0x00007f5c6dcf6f83 fp 0x00007f5c6e9fe3b0 Unknown symbol
  pc 0x00007f5c6dca871d fp 0x00007f5c6e9fe3d8 Unknown symbol
  pc 0x00007f5c6ea0157a fp 0x00007f5c6e9fe448 Unknown symbol
  pc 0x000055ba6aed1317 fp 0x00007f5c6e9fe5e0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  pc 0x000055ba6aed0d76 fp 0x00007f5c6e9fe640 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
  pc 0x000055ba6aed4042 fp 0x00007f5c6e9fe740 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  pc 0x000055ba6af4a1d4 fp 0x00007f5c6e9fea30 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)
  pc 0x000055ba6afb79e2 fp 0x00007f5c6e9feb20 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x000055ba6afb8655 fp 0x00007f5c6e9fec40 dart::MessageHandler::TaskCallback()
  pc 0x000055ba6afb9883 fp 0x00007f5c6e9fec70 ./dart+0x1e80883
  pc 0x000055ba6b180877 fp 0x00007f5c6e9fed10 dart::ThreadPool::Worker::Loop()
  pc 0x000055ba6b180567 fp 0x00007f5c6e9fee00 dart::ThreadPool::Worker::Main(unsigned long)
  pc 0x000055ba6b092ac4 fp 0x00007f5c6e9fee70 ./dart+0x1f59ac4
-- End of DumpStackTrace
[exit     : sp(0) fp(0x7f5c6e9fd9e0) pc(0)]
[stub     : sp(0x7f5c6e9fd9f0) fp(0x7f5c6e9fda18) pc(0x7f5c6ea014ad)]
[dart     : sp(0x7f5c6e9fda28) fp(0x7f5c6e9fda78) pc(0x7f5c6c4a9f64) dart:core__StringBase@0150898_createFromCharCodes ]
[dart     : sp(0x7f5c6e9fda88) fp(0x7f5c6e9fdaf0) pc(0x7f5c6c4a9b6e) dart:core_String_String.fromCharCodes ]
[dart     : sp(0x7f5c6e9fdb00) fp(0x7f5c6e9fdb48) pc(0x7f5c6c4a96f6) dart:convert__JsonUtf8Parser@10003594_getString ]
[dart     : sp(0x7f5c6e9fdb58) fp(0x7f5c6e9fdba0) pc(0x7f5c6c4ae34d) *dart:convert__ChunkedJsonParser@10003594_parseString ]
[dart     : sp(0x7f5c6e9fdbb0) fp(0x7f5c6e9fdc00) pc(0x7f5c6c4a62ce) dart:convert__ChunkedJsonParser@10003594_parse ]
[dart     : sp(0x7f5c6e9fdc10) fp(0x7f5c6e9fdc48) pc(0x7f5c6c4a408f) dart:convert__JsonUtf8Decoder@10003594_convert ]
[dart     : sp(0x7f5c6e9fdc58) fp(0x7f5c6e9fdca8) pc(0x7f5c6c4a1e32) package:package_config/src/package_config_json.dart_::_parsePackageConfigBytes ]
[dart     : sp(0x7f5c6e9fdcb8) fp(0x7f5c6e9fdd48) pc(0x7f5c6c4a03c8) package:package_config/src/package_config_io.dart_::_readAnyConfigFileUri__async_op ]
[dart     : sp(0x7f5c6e9fdd58) fp(0x7f5c6e9fddc8) pc(0x7f5c6c4830a0) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x7f5c6e9fddd8) fp(0x7f5c6e9fde40) pc(0x7f5c6c482e90) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x7f5c6e9fde50) fp(0x7f5c6e9fdee8) pc(0x7f5c6c4827a9) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x7f5c6e9fdef8) fp(0x7f5c6e9fdf38) pc(0x7f5c6c4822f4) dart:async__FutureListener@4048458_handleValue ]
[dart     : sp(0x7f5c6e9fdf48) fp(0x7f5c6e9fdfb0) pc(0x7f5c6c481eb1) dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]
[dart     : sp(0x7f5c6e9fdfc0) fp(0x7f5c6e9fe030) pc(0x7f5c6c480eb2) dart:async__Future@4048458__propagateToListeners@4048458 ]
[dart     : sp(0x7f5c6e9fe040) fp(0x7f5c6e9fe078) pc(0x7f5c6dc82895) dart:async__Future@4048458__completeWithValue@4048458 ]
[dart     : sp(0x7f5c6e9fe088) fp(0x7f5c6e9fe0c8) pc(0x7f5c6dc825ba) dart:async__Future@4048458__asyncComplete@4048458_<anonymous closure> ]
[dart     : sp(0x7f5c6e9fe0d8) fp(0x7f5c6e9fe140) pc(0x7f5c6dcf0903) dart:async_::__rootRun@4048458 ]
[dart     : sp(0x7f5c6e9fe150) fp(0x7f5c6e9fe1b0) pc(0x7f5c6dcf0676) dart:async_::__rootRun@4048458__rootRun@4048458 ]
[dart     : sp(0x7f5c6e9fe1c0) fp(0x7f5c6e9fe250) pc(0x7f5c6dcefc56) dart:async__CustomZone@4048458_run ]
[dart     : sp(0x7f5c6e9fe260) fp(0x7f5c6e9fe2b0) pc(0x7f5c6dcfa8ff) dart:async__CustomZone@4048458_bindCallback_<anonymous closure> ]
[dart     : sp(0x7f5c6e9fe2c0) fp(0x7f5c6e9fe2f0) pc(0x7f5c6dc821e8) dart:async_::__microtaskLoop@4048458 ]
[dart     : sp(0x7f5c6e9fe300) fp(0x7f5c6e9fe330) pc(0x7f5c6dc81e34) dart:async_::__startMicrotaskLoop@4048458 ]
[dart     : sp(0x7f5c6e9fe340) fp(0x7f5c6e9fe370) pc(0x7f5c6dc81d27) dart:async_::__startMicrotaskLoop@4048458__startMicrotaskLoop@4048458 ]
[dart     : sp(0x7f5c6e9fe380) fp(0x7f5c6e9fe3b0) pc(0x7f5c6dcf6f83) dart:isolate_::__runPendingImmediateCallback@1026248 ]
[dart     : sp(0x7f5c6e9fe3c0) fp(0x7f5c6e9fe3d8) pc(0x7f5c6dca871d) dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]
[entry    : sp(0x7f5c6e9fe3e8) fp(0x7f5c6e9fe448) pc(0x7f5c6ea0157a)]

ninja: build stopped: subcommand failed.
ninja -C out/DebugX64 -j1000 -l64 runtime_kernel done.
```

**Comment by sstrickl** [comment]
Double-checking on other architectures, though, I see it doesn't reproduce on SIMARM or SIMARM64, so digging deeper to see if I can trim down the example and see what's happening differently on X64 vs. those. (Hopefully not something going to/from float and back, since we already know there are float bit differences between the various architectures in certain cases.)

**Comment by sstrickl** [comment]
To provide slightly more detail from a -d0 build:

```
Thread 2 received signal SIGABRT, Aborted.
[Switching to Thread 126223.126227]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Ingen sådan fil eller filkatalog.
(rr) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fdd9fb42535 in __GI_abort () at abort.c:79
#2  0x0000556c95b82e3d in dart::Assert::Fail (this=0x7fdd9dffd410, format=0x556c945693e7 "expected \"%s\" = %s, actual \"%s\" = %s") at ../../runtime/platform/assert.cc:44
#3  0x0000556c95d799aa in dart::Smi::New (value=9223372034707292161) at ../../runtime/vm/object.h:8007
#4  0x0000556c96273c23 in dart::BoundsCheckGeneralizer::GenerateInvariant (this=0x7fdd9dffd8c8, induc=0x7fdd9ca3b338) at ../../runtime/vm/compiler/backend/range_analysis.cc:978
#5  0x0000556c962736e7 in dart::BoundsCheckGeneralizer::InductionVariableUpperBound (this=0x7fdd9dffd8c8, phi=0x7fdd9e8f8e80, loop=0x7fdd9d543838, induc=0x7fdd9ca3b4b8, point=0x7fdd9d55f468) at ../../runtime/vm/compiler/backend/range_analysis.cc:1067
#6  0x0000556c962733ce in dart::BoundsCheckGeneralizer::ConstructBound (this=0x7fdd9dffd8c8, phi_bound_func=(class dart::Definition *(dart::BoundsCheckGeneralizer::*)(class dart::BoundsCheckGeneralizer * const, class dart::PhiInstr *, class dart::LoopInfo *, class dart::InductionVar *, class dart::Instruction *)) 0x556c96273610 <dart::BoundsCheckGeneralizer::InductionVariableUpperBound(dart::PhiInstr*, dart::LoopInfo*, dart::InductionVar*, dart::Instruction*)>, value=0x7fdd9e8f8e80, point=0x7fdd9d55f468) at ../../runtime/vm/compiler/backend/range_analysis.cc:1012
#7  0x0000556c96272390 in dart::BoundsCheckGeneralizer::ConstructUpperBound (this=0x7fdd9dffd8c8, value=0x7fdd9e8f8e80, point=0x7fdd9d55f468) at ../../runtime/vm/compiler/backend/range_analysis.cc:933
#8  0x0000556c96267de0 in dart::BoundsCheckGeneralizer::TryGeneralize (this=0x7fdd9dffd8c8, check=0x7fdd9d55f468) at ../../runtime/vm/compiler/backend/range_analysis.cc:752
#9  0x0000556c962651f2 in dart::RangeAnalysis::EliminateRedundantBoundsChecks (this=0x7fdd9dffd9f0) at ../../runtime/vm/compiler/backend/range_analysis.cc:1353
#10 0x0000556c96264678 in dart::RangeAnalysis::Analyze (this=0x7fdd9dffd9f0) at ../../runtime/vm/compiler/backend/range_analysis.cc:35
#11 0x0000556c962ab975 in dart::CompilerPass_RangeAnalysis::DoBody (this=0x556c9697e8d8 <dart::compiler_pass_RangeAnalysis>, state=0x7fdd9dffe318) at ../../runtime/vm/compiler/compiler_pass.cc:462
#12 0x0000556c962a9442 in dart::CompilerPass::Run (this=0x556c9697e8d8 <dart::compiler_pass_RangeAnalysis>, state=0x7fdd9dffe318) at ../../runtime/vm/compiler/compiler_pass.cc:196
#13 0x0000556c962a9c11 in dart::CompilerPass::RunPipeline (mode=dart::CompilerPass::kJIT, pass_state=0x7fdd9dffe318) at ../../runtime/vm/compiler/compiler_pass.cc:332
#14 0x0000556c963461ec in dart::CompileParsedFunctionHelper::Compile (this=0x7fdd9dffe808, pipeline=0x7fdd9f402548) at ../../runtime/vm/compiler/jit/compiler.cc:617
#15 0x0000556c9634705e in dart::CompileFunctionHelper (pipeline=0x7fdd9f402548, function=..., optimized=true, osr_id=-1) at ../../runtime/vm/compiler/jit/compiler.cc:755
#16 0x0000556c96347bc6 in dart::Compiler::CompileOptimizedFunction (thread=0x556c982dd800, function=..., osr_id=-1) at ../../runtime/vm/compiler/jit/compiler.cc:949
#17 0x0000556c963487e3 in dart::BackgroundCompiler::Run (this=0x556c982c41c0) at ../../runtime/vm/compiler/jit/compiler.cc:1210
#18 0x0000556c9634b1a9 in dart::BackgroundCompilerTask::Run (this=0x556c9829c0e0) at ../../runtime/vm/compiler/jit/compiler.cc:1286
```

**Comment by sstrickl** [comment]
Hmm, so that _is_ an issue (generating non-Smi ranges when a Smi range is requested) and I do have a fix for that, but that particular use of the Mint value is being pulled from the induction variable's offset, which in this case comes directly from the constant and is not checked for being a Smi at that point.

So the induction variable is being treated as a Smi despite starting at a Mint value, and that needs to be appropriately handled. Digging through the code to see if _all_ induction variables are assumed to be Smis, in which case we can just ASSERT in the constructor, or if we do sometimes use int64 induction variables in the analysis.

**Comment by sstrickl** [comment]
The fix is just to check in `GetSmiInduction` that the initial value is indeed a Smi in addition to all the other checks. Creating a CL with that small fix.

**Comment by bkonyi** [comment]
Thanks for investigating this Teagan! =)
