### ISSUE TITLE
Crash in dev_compiler when finding the source location of file with error

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40789]
Was able to work-around with this

```diff
diff --git a/pkg/front_end/lib/src/fasta/messages.dart b/pkg/front_end/lib/src/fasta/messages.dart
index a689553179..9677b0469e 100644
--- a/pkg/front_end/lib/src/fasta/messages.dart
+++ b/pkg/front_end/lib/src/fasta/messages.dart
@@ -13,7 +13,13 @@ export 'fasta_codes.dart';
 bool get isVerbose => CompilerContext.current.options.verbose;

 Location getLocation(Uri uri, int charOffset) {
-  return CompilerContext.current.uriToSource[uri]?.getLocation(uri, charOffset);
+  try {
+    return CompilerContext.current.uriToSource[uri]?.getLocation(
+        uri, charOffset);
+  } on RangeError catch (e) {
+    print('wah? $e');
+    return null;
+  }
 }

 Location getLocationFromUri(Uri uri, int charOffset) {
```

Error output

```
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --kernel --dart-sdk-summary=/Users/kevmoo/github/dart/sdk/xcodebuild/ReleaseX64/dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/vector_math/vector_math.ddc.js --source-map --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash --packages=file:///var/folders/c0/jv6k5x0j57vcwkdx6rcjgj3w0071_k/T/kernel_builder_mAXhq4/.packages --module-name=packages/vector_math/vector_math --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///Users/kevmoo/github/dart/sdk/xcodebuild/ReleaseX64/dart-sdk/lib/libraries.json --used-inputs-file=/var/folders/c0/jv6k5x0j57vcwkdx6rcjgj3w0071_k/T/ddk_builder_wTjj8n/used_inputs.txt package:vector_math/src/vector_math/matrix4.dart package:vector_math/vector_math.dart package:vector_math/src/vector_math/quaternion.dart package:vector_math/src/vector_math/triangle.dart package:vector_math/src/vector_math/opengl.dart package:vector_math/src/vector_math/aabb3.dart package:vector_math/src/vector_math/colors.dart package:vector_math/src/vector_math/sphere.dart package:vector_math/src/vector_math/error_helpers.dart package:vector_math/src/vector_math/aabb2.dart package:vector_math/src/vector_math/vector.dart package:vector_math/src/vector_math/plane.dart package:vector_math/src/vector_math/ray.dart package:vector_math/src/vector_math/vector3.dart package:vector_math/src/vector_math/matrix3.dart package:vector_math/src/vector_math/quad.dart package:vector_math/src/vector_math/vector4.dart package:vector_math/src/vector_math/utilities.dart package:vector_math/src/vector_math/intersection_result.dart package:vector_math/src/vector_math/vector2.dart package:vector_math/src/vector_math/frustum.dart package:vector_math/src/vector_math/constants.dart package:vector_math/src/vector_math/obb3.dart package:vector_math/src/vector_math/third_party/noise.dart package:vector_math/src/vector_math/matrix2.dart
    dart --version: 2.8.0-edge.7072c21353b42049718a1f338336bd9a721097b8 (Wed Feb 26 09:11:54 2020 -0800) on "macos_x64"

Crash when compiling null,
at character offset null:
RangeError (offset): Invalid value: Not in range 0..1826, inclusive: 11278
#0      RangeError.checkValueInInterval (dart:core/errors.dart:290:7)
#1      Source.getLocation (package:kernel/ast.dart:7633:16)
#2      getLocation (package:front_end/src/fasta/messages.dart:16:52)
#3      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:207:47)
#4      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:230:29)
#5      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:69:13)
#6      Loader.addMessage (package:front_end/src/fasta/loader.dart:320:20)
#7      Loader.addProblem (package:front_end/src/fasta/loader.dart:282:12)
#8      LibraryBuilderImpl.addProblem (package:front_end/src/fasta/builder/library_builder.dart:284:19)
#9      SourceLibraryBuilder.addProblem (package:front_end/src/fasta/source/source_library_builder.dart:1435:47)
#10     SourceLibraryBuilder.checkInitializersInFormals (package:front_end/src/fasta/source/source_library_builder.dart:3197:11)
#11     ClassBuilderImpl.checkTypesInOutline.<anonymous closure> (package:front_end/src/fasta/builder/class_builder.dart:898:17)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#13     Scope.forEach (package:front_end/src/fasta/scope.dart:418:12)
#14     ClassBuilderImpl.forEach (package:front_end/src/fasta/builder/class_builder.dart:439:11)
#15     ClassBuilderImpl.checkTypesInOutline (package:front_end/src/fasta/builder/class_builder.dart:886:5)
#16     SourceLibraryBuilder.checkTypesInOutline (package:front_end/src/fasta/source/source_library_builder.dart:3559:21)
#17     SourceLoader.checkTypes.<anonymous closure> (package:front_end/src/fasta/source/source_loader.dart:983:16)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#19     SourceLoader.checkTypes (package:front_end/src/fasta/source/source_loader.dart:979:14)
#20     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:316:14)
<asynchronous suspension>
#21     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#22     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#23     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:290:12)
#24     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:233:52)
<asynchronous suspension>
#25     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
#26     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#29     _rootRun (dart:async/zone.dart:1126:13)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _runZoned (dart:async/zone.dart:1518:10)
#32     runZoned (dart:async/zone.dart:1465:12)
#33     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#34     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:175:20)
#35     _compile (package:dev_compiler/src/kernel/command.dart:336:58)
<asynchronous suspension>
#36     compile (package:dev_compiler/src/kernel/command.dart:45:18)
#37     compile (package:dev_compiler/src/compiler/shared_command.dart:391:10)
#38     _CompilerWorker.performRequest.<anonymous closure> (file:///Users/kevmoo/github/dart/sdk/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#39     _rootRun (dart:async/zone.dart:1126:13)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _runZoned (dart:async/zone.dart:1518:10)
#42     runZoned (dart:async/zone.dart:1465:12)
#43     _CompilerWorker.performRequest (file:///Users/kevmoo/github/dart/sdk/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#44     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#45     _rootRun (dart:async/zone.dart:1126:13)
#46     _CustomZone.run (dart:async/zone.dart:1023:19)
#47     _runZoned (dart:async/zone.dart:1518:10)
#48     runZoned (dart:async/zone.dart:1465:12)
#49     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#50     main (file:///Users/kevmoo/github/dart/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#51     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by kevmoo** [comment]
CC @johnniwinther @vsmenon
