### ISSUE TITLE
from android studio

### ISSUE THREAD

**Issue by MateusPedrosoSilva** [dart-lang/sdk#40814]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6200805`
- `2.7.0`
- `AI-192.7142.36.36.6200805, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.3, screens 2048x1152  Retina`

## Exception
```
Dart analysis server, SDK version 2.7.0, server version 1.27.4, error: NoSuchMethodError: The getter 'source' was called on null.
Receiver: null
Tried calling: source
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      SearchMatchImpl.forSearchResult (package:analysis_server/src/services/search/search_engine_internal.dart:248:26)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#4      SearchEngineImpl.searchReferences (package:analysis_server/src/services/search/search_engine_internal.dart:122:60)
<asynchronous suspension>
#5      MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:145:49)
<asynchronous suspension>
#6      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1029:41)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1126:13)
#8      _CustomZone.run (dart:async/zone.dart:1023:19)
#9      _runZoned (dart:async/zone.dart:1518:10)
#10     runZoned (dart:async/zone.dart:1502:12)
#11     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:985:5)
#12     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:863:24)
#13     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:393:16)
#14     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:45)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#16     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:329:50)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1502:12)
#21     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:328:5)
#22     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#26     _rootRunUnary (dart:async/zone.dart:1134:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#37     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#38     _rootRunUnary (dart:async/zone.dart:1134:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#46     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#47     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#48     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#49     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#50     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#51     _rootRunUnary (dart:async/zone.dart:1134:38)
#52     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#56     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#57     _StreamController._add (dart:async/stream_controller.dart:642:7)
#58     _StreamController.add (dart:async/stream_controller.dart:588:5)
#59     _Socket._onData (dart:io-patch/so...
```

For additional log information, please append the contents of
file:///private/var/folders/23/2t_slfzj6nn87gvvmm0lpn740000gn/T/report.txt.

**Comment by srawlins** [comment]
Apologies that we did not get a chance to investigate this crash; please re-open if you see this on a recent version of Dart.
