### ISSUE TITLE
-1 offset unexpectedly returned for Navigation* objects

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#40827]
Exact problem details to follow:  https://github.com/dart-lang/sdk/issues/40146#issuecomment-592656409

**Comment by jcollins-g** [comment]
Pages that fail to load show on the console:

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by jcollins-g** [comment]
```
500 Exception in preview
We're sorry, but you've encountered a bug in the preview tool. Please visit github.com/dart-lang/sdk/issues/new to report the issue and include the stack trace below.

RangeError: Value not in range: -1

#0      _StringBase.substring (dart:core-patch/string_patch.dart:393:7)
#1      UnitRenderer._computeNavigationContent (package:analysis_server/src/edit/nnbd_migration/unit_renderer.dart:122:39)
#2      UnitRenderer.render (package:analysis_server/src/edit/nnbd_migration/unit_renderer.dart:44:28)
#3      DartFilePage.generatePage (package:analysis_server/src/edit/preview/dart_file_page.dart:31:24)
#4      Page.generate (package:analysis_server/src/status/pages.dart:68:12)
<asynchronous suspension>
#5      PreviewSite.respond (package:analysis_server/src/edit/preview/preview_site.dart:207:31)
#6      PreviewSite.handleGetRequest (package:analysis_server/src/edit/preview/preview_site.dart:131:24)
#7      HttpPreviewServer._handleGetRequest (package:analysis_server/src/edit/preview/http_preview_server.dart:68:22)
#8      HttpPreviewServer._handleServer.<anonymous closure> (package:analysis_server/src/edit/preview/http_preview_server.dart:76:15)
#9      _rootRunUnary (dart:async/zone.dart:1142:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1045:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:950:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:350:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:280:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:778:19)
#15     _StreamController._add (dart:async/stream_controller.dart:649:7)
#16     _StreamController.add (dart:async/stream_controller.dart:596:5)
#17     _HttpServer._handleRequest (dart:_http/http_impl.dart:2832:19)
#18     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2587:19)
#19     _rootRunUnary (dart:async/zone.dart:1142:47)
#20     _CustomZone.runUnary (dart:async/zone.dart:1045:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:950:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:350:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:280:7)
#24     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:778:19)
#25     _StreamController._add (dart:async/stream_controller.dart:649:7)
#26     _StreamController.add (dart:async/stream_controller.dart:596:5)
#27     _HttpParser._headersEnd (dart:_http/http_parser.dart:372:19)
#28     _HttpParser._doParse (dart:_http/http_parser.dart:706:15)
#29     _HttpParser._parse (dart:_http/http_parser.dart:315:7)
#30     _HttpParser._onData (dart:_http/http_parser.dart:815:5)
#31     _rootRunUnary (dart:async/zone.dart:1142:47)
#32     _CustomZone.runUnary (dart:async/zone.dart:1045:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:950:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:350:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:280:7)
#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:778:19)
#37     _StreamController._add (dart:async/stream_controller.dart:649:7)
#38     _StreamController.add (dart:async/stream_controller.dart:596:5)
#39     _Socket._onData (dart:io-patch/socket_patch.dart:1887:41)
#40     _rootRunUnary (dart:async/zone.dart:1150:13)
#41     _CustomZone.runUnary (dart:async/zone.dart:1045:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:950:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:350:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:280:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:778:19)
#46     _StreamController._add (dart:async/stream_controller.dart:649:7)
#47     _StreamController.add (dart:async/stream_controller.dart:596:5)
#48     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1423:33)
#49     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:926:14)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:117:13)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:5)
```

**Comment by jcollins-g** [comment]
https://dart-review.googlesource.com/c/sdk/+/138047 deals with the immediate cause of the bug, but why we get a -1 offset here still needs to be looked into.

**Comment by jcollins-g** [comment]
Changed description -- downgraded to P2 as the `-1` offset values don't immediately block usage of the tool and may or may not be legitimate.

**Comment by srawlins** [comment]
I think this has been as resolved as it is going to be. We can look more if users report it again.
