### ISSUE TITLE
Fuchsia tests are crashing with current isolate being NULL

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#40836]
https://dart-review.googlesource.com/c/sdk/+/126646 introduced the notion of GC working without a current isolate and working solely with isolate groups but all weak persistent callbacks currently work with the notion of having a current isolate being available. The above assertion of having no current isolate breaks the callback code.

```
[00046.662414][1711][2057][klog] INFO:    #2    0x000002ae33f4394c in dart::Assert::Fail(char const*, ...) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/platform/assert.cc:44 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x29394c sp 0x9daa5da4f0
[00046.662618][1711][2057][klog] INFO:    #3    0x000002ae343553c9 in Dart_IsolateServiceId /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/dart_api_impl.cc:1495 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x6a53c9 sp 0x9daa5da5d0
[00046.662710][1711][2057][klog] INFO:    #4    0x000002ae33f1e381 in zircon::dart::Handle::~Handle() /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../flutter/shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/handle.cc:56 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x26e381 sp 0x9daa5da600
[00046.662808][1711][2057][klog] INFO:    #5    0x000002ae33f1e6fe in zircon::dart::Handle::~Handle() /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../flutter/shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/handle.cc:54 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x26e6fe sp 0x9daa5da650
[00046.662875][1711][2057][klog] INFO:    #6    0x000002ae34350c72 in dart::FinalizablePersistentHandle::Finalize(dart::IsolateGroup*, dart::FinalizablePersistentHandle*) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/dart_api_impl.cc:713 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x6a0c72 sp 0x9daa5da670
[00046.662951][1711][2057][klog] INFO:    #7.4  0x000002ae340f993c in dart::Handles<4, 64, 0>::HandlesBlock::Visit(dart::HandleVisitor*) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/handles_impl.h:302 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x44993c sp 0x9daa5da690
[00046.662951][1711][2057][klog] INFO:    #7.3  0x000002ae340f993c in dart::Handles<4, 64, 0>::Visit(dart::HandleVisitor*) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/handles_impl.h:55 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x44993c sp 0x9daa5da690
[00046.662951][1711][2057][klog] INFO:    #7.2  0x000002ae340f993c in dart::FinalizablePersistentHandles::VisitHandles(dart::HandleVisitor*) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/dart_api_state.h:513 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x44993c sp 0x9daa5da690
[00046.662951][1711][2057][klog] INFO:    #7.1  0x000002ae340f993c in dart::ApiState::VisitWeakHandlesUnlocked(dart::HandleVisitor*) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/dart_api_state.h:720 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x44993c sp 0x9daa5da690
[00046.662951][1711][2057][klog] INFO:    #7    0x000002ae340f993c in dart::IsolateGroup::VisitWeakPersistentHandles(dart::HandleVisitor*) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/isolate.cc:2558 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x44993c sp 0x9daa5da690
[00046.663026][1711][2057][klog] INFO:    #8.1  0x000002ae343465be in dart::Scavenger::IterateWeakRoots(dart::IsolateGroup*, dart::HandleVisitor*) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/heap/scavenger.cc:699 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x6965be sp 0x9daa5da6d0
[00046.663026][1711][2057][klog] INFO:    #8    0x000002ae343465be in dart::Scavenger::Scavenge() /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/heap/scavenger.cc:1086 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x6965be sp 0x9daa5da6d0
[00046.663105][1711][2057][klog] INFO:    #9    0x000002ae3433bb8f in dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::Heap::GCReason) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/heap/heap.cc:521 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x68bb8f sp 0x9daa5da860
[00046.663179][1711][2057][klog] INFO:    #10.1 0x000002ae3433a581 in dart::Heap::CollectGarbage(dart::Heap::Space) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/heap/heap.cc:594 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x68a581 sp 0x9daa5da940
[00046.663179][1711][2057][klog] INFO:    #10   0x000002ae3433a581 in dart::Heap::AllocateNew(long) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/heap/heap.cc:135 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x68a581 sp 0x9daa5da940
[00046.663262][1711][2057][klog] INFO:    #11.1 0x000002ae3410f5a1 in dart::Heap::Allocate(long, dart::Heap::Space) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/heap/heap.h:85 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x45f5a1 sp 0x9daa5da980
[00046.663262][1711][2057][klog] INFO:    #11   0x000002ae3410f5a1 in dart::Object::Allocate(long, long, dart::Heap::Space) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/object.cc:2563 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x45f5a1 sp 0x9daa5da980
[00046.663339][1711][2057][klog] INFO:    #12.1 0x000002ae3415cf93 in dart::OneByteString::New(long, dart::Heap::Space) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/object.cc:21500 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x4acf93 sp 0x9daa5da9d0
[00046.663339][1711][2057][klog] INFO:    #12   0x000002ae3415cf93 in dart::String::FromUTF8(unsigned char const*, long, dart::Heap::Space) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/object.cc:20759 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x4acf93 sp 0x9daa5da9d0
[00046.663414][1711][2057][klog] INFO:    #13   0x000002ae343043fc in dart::kernel::TranslationHelper::DartString(dart::kernel::StringIndex, dart::Heap::Space) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_translation_helper.cc:364 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x6543fc sp 0x9daa5daa30
[00046.663488][1711][2057][klog] INFO:    #14.2 0x000002ae3430d564 in dart::kernel::TranslationHelper::DartString(dart::kernel::StringIndex) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_translation_helper.h:122 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x65d564 sp 0x9daa5daa80
[00046.663488][1711][2057][klog] INFO:    #14.1 0x000002ae3430d564 in dart::kernel::TranslationHelper::DartMethodName(dart::kernel::NameIndex, dart::kernel::StringIndex) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_translation_helper.cc:508 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x65d564 sp 0x9daa5daa80
[00046.663488][1711][2057][klog] INFO:    #14   0x000002ae3430d564 in dart::kernel::KernelReaderHelper::ReadNameAsMethodName() /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_translation_helper.cc:1924 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x65d564 sp 0x9daa5daa80
[00046.663560][1711][2057][klog] INFO:    #15   0x000002ae342ec7b3 in dart::kernel::StreamingFlowGraphBuilder::BuildMethodInvocation(dart::TokenPosition*) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:2898 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x63c7b3 sp 0x9daa5daab0
[00046.663634][1711][2057][klog] INFO:    #16   0x000002ae342e5eb7 in dart::kernel::StreamingFlowGraphBuilder::BuildExpression(dart::TokenPosition*) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:1296 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x635eb7 sp 0x9daa5dab90
[00046.663707][1711][2057][klog] INFO:    #17   0x000002ae342f21d9 in dart::kernel::StreamingFlowGraphBuilder::BuildReturnStatement() /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:4663 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x6421d9 sp 0x9daa5dabf0
[00046.663778][1711][2057][klog] INFO:    #18   0x000002ae342e81b0 in dart::kernel::StreamingFlowGraphBuilder::BuildStatement() /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:1426 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x6381b0 sp 0x9daa5dac40
[00046.663844][1711][2057][klog] INFO:    #19   0x000002ae342e99fd in dart::kernel::StreamingFlowGraphBuilder::BuildFunctionBody(dart::Function const&, dart::LocalVariable*, bool) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:840 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x6399fd sp 0x9daa5dac80
[00046.663916][1711][2057][klog] INFO:    #20   0x000002ae342ea036 in dart::kernel::StreamingFlowGraphBuilder::BuildGraphOfFunction(bool) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:991 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x63a036 sp 0x9daa5dad10
[00046.663990][1711][2057][klog] INFO:    #21   0x000002ae342ea5a9 in dart::kernel::StreamingFlowGraphBuilder::BuildGraph() /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:1147 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x63a5a9 sp 0x9daa5daea0
[00046.664065][1711][2057][klog] INFO:    #22   0x000002ae342f9fcc in dart::kernel::FlowGraphBuilder::BuildGraph() /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/frontend/kernel_to_il.cc:806 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x649fcc sp 0x9daa5db110
[00046.664139][1711][2057][klog] INFO:    #23   0x000002ae34322903 in dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*>*, long, bool) /usr/local/google/home/kaushikiska/Code/engine/src/out/fuchsia_release_x64/../../third_party/dart/runtime/vm/compiler/jit/compiler.cc:139 <<VMO#36068=g3_dart_jit_product_runner.cmx>>+0x672903 sp 0x9daa5db380

```

**Comment by a-siva** [comment]
To get the Flutter roll into google3 going a temporary patch was added to disable the NoActiveIsolateScope code around the GC calls.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/137880 workaround CL.

**Comment by a-siva** [comment]
Another stack trace that exhibits the same problem in a different path

```
[00175.328636][1724][2690][klog] INFO:    #1    0x00008000cb137b20 in <libc.so>+0x4db20 sp 0x8fe05a90
[00175.328877][1724][2690][klog] INFO:    #2    0x0000000065ed713c in dart::Assert::Fail(char const*, ...) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/platform/assert.cc:44 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x4e013c sp 0x8fe05a90
[00175.329356][1724][2690][klog] INFO:    #3    0x00000000663fabf8 in Dart_EnterIsolate /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/dart_api_impl.cc:1512 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0xa03bf8 sp 0x8fe05b90
[00175.329548][1724][2690][klog] INFO:    #4.1  0x0000000065e2a28c in tonic::DartIsolateScope::DartIsolateScope(_Dart_Isolate*) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../flutter/third_party/tonic/scopes/dart_isolate_scope.cc:16 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x43328c sp 0x8fe05bd0
[00175.329548][1724][2690][klog] INFO:    #4    0x0000000065e2a28c in tonic::DartPersistentValue::Clear() /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../flutter/third_party/tonic/dart_persistent_value.cc:46 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x43328c sp 0x8fe05bd0
[00175.329756][1724][2690][klog] INFO:    #5.1  0x0000000065e2bd38 in tonic::DartPersistentValue::~DartPersistentValue() /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../flutter/third_party/tonic/dart_persistent_value.cc:27 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x434d38 sp 0x8fe05c30
[00175.329756][1724][2690][klog] INFO:    #5    0x0000000065e2bd38 in zircon::dart::Handle::~Handle() /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../flutter/shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/handle.cc:48 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x434d38 sp 0x8fe05c30
[00175.329963][1724][2690][klog] INFO:    #6    0x0000000065e2bde4 in zircon::dart::Handle::~Handle() /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../flutter/shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/handle.cc:43 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x434de4 sp 0x8fe05c70
[00175.330150][1724][2690][klog] INFO:    #7.2  0x00000000663e204c in dart::FinalizablePersistentHandle::Finalize(dart::IsolateGroup*, dart::FinalizablePersistentHandle*) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/dart_api_impl.cc:713 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9eb04c sp 0x8fe05c90
[00175.330150][1724][2690][klog] INFO:    #7.1  0x00000000663e204c in dart::FinalizablePersistentHandle::UpdateUnreachable(dart::IsolateGroup*) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/dart_api_state.h:227 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9eb04c sp 0x8fe05c90
[00175.330150][1724][2690][klog] INFO:    #7    0x00000000663e204c in dart::MarkingWeakVisitor::VisitHandle(unsigned long) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/heap/marker.cc:358 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9eb04c sp 0x8fe05c90
[00175.330340][1724][2690][klog] INFO:    #8.6  0x00000000663e1ca4 in dart::Handles<4, 64, 0>::HandlesBlock::Visit(dart::HandleVisitor*) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/handles_impl.h:302 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9eaca4 sp 0x8fe05cb0
[00175.330340][1724][2690][klog] INFO:    #8.5  0x00000000663e1ca4 in dart::Handles<4, 64, 0>::Visit(dart::HandleVisitor*) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/handles_impl.h:55 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9eaca4 sp 0x8fe05cb0
[00175.330340][1724][2690][klog] INFO:    #8.4  0x00000000663e1ca4 in dart::FinalizablePersistentHandles::VisitHandles(dart::HandleVisitor*) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/dart_api_state.h:513 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9eaca4 sp 0x8fe05cb0
[00175.330340][1724][2690][klog] INFO:    #8.3  0x00000000663e1ca4 in dart::ApiState::VisitWeakHandlesUnlocked(dart::HandleVisitor*) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/dart_api_state.h:720 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9eaca4 sp 0x8fe05cb0
[00175.330340][1724][2690][klog] INFO:    #8.2  0x00000000663e1ca4 in dart::IsolateGroup::VisitWeakPersistentHandles(dart::HandleVisitor*) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/isolate.cc:2560 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9eaca4 sp 0x8fe05cb0
[00175.330340][1724][2690][klog] INFO:    #8.1  0x00000000663e1ca4 in dart::GCMarker::ProcessWeakHandles(dart::Thread*) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/heap/marker.cc:471 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9eaca4 sp 0x8fe05cb0
[00175.330340][1724][2690][klog] INFO:    #8    0x00000000663e1ca4 in dart::GCMarker::IterateWeakRoots(dart::Thread*) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/heap/marker.cc:449 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9eaca4 sp 0x8fe05cb0
[00175.330572][1724][2690][klog] INFO:    #9    0x00000000663e3e24 in dart::ParallelMarkTask::RunEnteredIsolateGroup() /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/heap/marker.cc:649 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9ece24 sp 0x8fe05da0
[00175.330806][1724][2690][klog] INFO:    #10   0x00000000663e4260 in dart::ParallelMarkTask::Run() /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/heap/marker.cc:573 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9ed260 sp 0x8fe05e80
[00175.331015][1724][2690][klog] INFO:    #11.1 0x00000000663cb1e4 in dart::ThreadPool::Worker::Loop() /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/thread_pool.cc:382 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9d41e4 sp 0x8fe05ed0
[00175.331015][1724][2690][klog] INFO:    #11   0x00000000663cb1e4 in dart::ThreadPool::Worker::Main(unsigned long) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/thread_pool.cc:434 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x9d41e4 sp 0x8fe05ed0
[00175.331249][1724][2690][klog] INFO:    #12   0x0000000066356bd0 in dart::ThreadStart(void*) /b/s/w/ir/cache/builder/src/out/fuchsia_profile_arm64/../../third_party/dart/runtime/vm/os_thread_fuchsia.cc:108 <<VMO#201682=g3_flutter_aot_runner.cmx>>+0x95fbd0 sp 0x8fe05f70
[00175.331460][1724][2690][klog] INFO:    #13   0x00008000cb142a98 in <libc.so>+0x58a98 sp 0x8fe05fd0
[00175.331737][1724][2690][klog] INFO:    #14   0x00008000cb184338 in <libc.so>+0x9a338 sp 0x8fe05fe0
```

**Comment by mkustermann** [comment]
With Ryan's latest changes I think this issue can be closed.
