### ISSUE TITLE
non-nullable enabled crash

### ISSUE THREAD

**Issue by flukejones** [dart-lang/sdk#40837]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6165589`
- `2.7.0`
- `AI-192.7142.36.36.6165589, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 3440x1440`

## Exception
```
Dart analysis server, SDK version 2.7.0, server version 1.27.4, FATAL error: NoSuchMethodError: The method 'functionExpression_begin' was called on null.
Receiver: null
Tried calling: functionExpression_begin(Instance of 'FunctionExpressionImpl')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3765:30)
#2      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4962:49)
#3      AstResolver.resolve (package:analyzer/src/summary2/ast_resolver.dart:80:10)
#4      ConstantInitializersResolver._resolveVariable (package:analyzer/src/summary2/top_level_inference.dart:94:21)
#5      ConstantInitializersResolver._resolveClassFields (package:analyzer/src/summary2/top_level_inference.dart:69:7)
#6      List.forEach (dart:core-patch/growable_array.dart:285:8)
#7      ConstantInitializersResolver.perform (package:analyzer/src/summary2/top_level_inference.dart:54:20)
#8      Linker._resolveConstantInitializers (package:analyzer/src/summary2/link.dart:224:40)
#9      Linker._buildOutlines (package:analyzer/src/summary2/link.dart:103:5)
#10     Linker.link (package:analyzer/src/summary2/link.dart:82:5)
#11     link (package:analyzer/src/summary2/link.dart:34:10)
#12     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:179:26)
#13     SetMixin.forEach (dart:collection/set.dart:148:30)
#14     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:134:32)
#15     SetMixin.forEach (dart:collection/set.dart:148:30)
#16     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:134:32)
#17     SetMixin.forEach (dart:collection/set.dart:148:30)
#18     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:134:32)
#19     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:231:17)
#20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#21     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:229:12)
#22     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:80:5)
#23     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1453:29)
#24     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1262:30)
#25     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#26     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1251:20)
#27     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1317:37)
#28     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:974:39)
<asynchronous suspension>
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1940:24)
<asynchronous suspension>
#30     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1874:5)
#31     new AnalysisServer (package:analysis_server/src/analysis_server.dart:223:29)
#32     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#33     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#34     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:619:21)
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _runZoned (dart:async/zone.dart:1518:10)
#38     runZoned (dart:async/zone.dart:1465:12)
#39     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:735:12)
#40     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:617:7)
#41     Driver.start (package:analysis_server/src/server/driver.dart:515:7)
#42     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#43     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#44     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:i...
```

[report.txt](https://github.com/dart-lang/sdk/files/4269995/report.txt)

Unsure what else I can add. I was performing a build when it crashed.

**Comment by flukejones** [comment]
Actually it appears to happen whenever I use "Find Usages" on a function.

**Comment by scheglov** [comment]
"Find Usages" uses index, and index requires resolution, and analyzer crashed during resolution.

I was able to reproduce this.
It happens when you have a closure (function expression) outside a top-level declaration.

```dart
class A {
  const A(_);
}

A@(() => 0)
class B {}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/139149
