### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by chtdomo** [dart-lang/sdk#40843]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.8.0-edge.dda5bcee00d3614e5ec7d2e5de17b3fd2450f204`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.3, screens 1920x1080, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.dda5bcee00d3614e5ec7d2e5de17b3fd2450f204, server version 1.27.4, error: FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:512:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:32:10)
#3      JsonDecoder.convert (dart:convert/json.dart:495:36)
#4      JsonCodec.decode (dart:convert/json.dart:153:41)
#5      _PackageConfigJsonParser.parse (package:analyzer/src/context/package_config_json.dart:113:30)
#6      parsePackageConfigJson (package:analyzer/src/context/package_config_json.dart:13:49)
#7      parsePackageConfigJsonFile (package:analyzer/src/context/packages.dart:72:20)
#8      parsePackagesFile (package:analyzer/src/context/packages.dart:127:14)
#9      ContextManagerImpl._computeFolderDisposition (package:analysis_server/src/context_manager.dart:951:29)
#10     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:992:9)
#11     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1084:16)
#12     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1092:13)
#13     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1092:13)
#14     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:646:9)
#15     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:473:22)
#16     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:363:14)
#17     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:301:16)
#18     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:316:45)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#20     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:312:50)
#21     _rootRun (dart:async/zone.dart:1126:13)
#22     _CustomZone.run (dart:async/zone.dart:1023:19)
#23     _runZoned (dart:async/zone.dart:1518:10)
#24     runZoned (dart:async/zone.dart:1502:12)
#25     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:311:5)
#26     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#27     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#28     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#29     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#30     _rootRunUnary (dart:async/zone.dart:1134:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#35     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#36     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#37     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#38     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#39     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#40     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#42     _rootRunUnary (dart:async/zone.dart:1134:38)
#43     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#47     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#48     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#49     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#50     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#51     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#52     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#53     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#54     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#55     _rootRunUnary (dart:async/zone.dart:1134:38)
#56     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#59...
```

For additional log information, please append the contents of
file:///private/var/folders/qt/ywc72tf571j4jh2wnxdrt0nc0000gn/T/report.txt.

**Comment by srawlins** [comment]
Apologies that we did not get a chance to investigate this crash; please re-open if you see this on a recent version of Dart.
