### ISSUE TITLE
FileSystemException(path=artifacts\flutter_web.dill; message=Cannot open file)

### ISSUE THREAD

**Issue by liudonghua123** [dart-lang/sdk#40887]
I want to run DartPad locally on my Windows 10. Firstly I got https://github.com/dart-lang/dart-pad/issues/1493#issuecomment-594403333. Then I added bat/cmd extension to some executables.

The I changed the following code to run dart-services.

```diff
D:\code\flutter\dart-services>git diff
warning: LF will be replaced by CRLF in pubspec.lock.
The file will have its original line endings in your working directory
diff --git a/flutter b/flutter
deleted file mode 160000
index 67826bd..0000000
--- a/flutter
+++ /dev/null
@@ -1 +0,0 @@
-Subproject commit 67826bdce54505760fe83b7ead70bdb5af6fe9f2
diff --git a/flutter b/flutter
new file mode 120000
index 0000000..d17e46d
--- /dev/null
+++ b/flutter
@@ -0,0 +1 @@
+d:/apps/flutter
\ No newline at end of file
diff --git a/lib/src/compiler.dart b/lib/src/compiler.dart
index 0b932be..86c76ef 100644
--- a/lib/src/compiler.dart
+++ b/lib/src/compiler.dart
@@ -29,10 +29,10 @@ class Compiler {
   final BazelWorkerDriver _ddcDriver;

   Compiler(this._sdk, this._flutterSdk, this._flutterWebManager)
-      : _dartdevcPath = path.join(_flutterSdk.sdkPath, 'bin', 'dartdevc'),
+      : _dartdevcPath = path.join(_flutterSdk.sdkPath, 'bin', 'dartdevc.bat'),
         _ddcDriver = BazelWorkerDriver(
             () => Process.start(
-                  path.join(_flutterSdk.sdkPath, 'bin', 'dartdevc'),
+                  path.join(_flutterSdk.sdkPath, 'bin', 'dartdevc.bat'),
                   <String>['--persistent_worker'],
                 ),
             maxWorkers: 1);
@@ -79,7 +79,7 @@ class Compiler {
       final mainJs = File(path.join(temp.path, '$kMainDart.js'));
       final mainSourceMap = File(path.join(temp.path, '$kMainDart.js.map'));

-      final dart2JSPath = path.join(_sdk.sdkPath, 'bin', 'dart2js');
+      final dart2JSPath = path.join(_sdk.sdkPath, 'bin', 'dart2js.bat');
       _logger.info('About to exec: $dart2JSPath $arguments');

       final result = await Process.run(dart2JSPath, arguments,
diff --git a/lib/src/flutter_web.dart b/lib/src/flutter_web.dart
index 1a94a50..903e281 100644
--- a/lib/src/flutter_web.dart
+++ b/lib/src/flutter_web.dart
@@ -128,7 +128,7 @@ $_samplePackageName:lib/
     //
     // The value should be an available port number.
     final result = await Process.start(
-      path.join(flutterSdk.flutterBinPath, 'flutter'),
+      path.join(flutterSdk.flutterBinPath, 'flutter.bat'),
       ['pub', 'get'],
       workingDirectory: _projectDirectory.path,
       environment: {'DART_VM_OPTIONS': '--enable-vm-service=$observatoryPort'},
......
```

After that I tried to run flutter snippets. However I got the following errors on console.
```
D:\code\flutter\dart-services>dart bin/server_dev.dart --port 8082
[INFO] common_server: Beginning CommonServer init().
[INFO] analysis_server: AnalysisServerWrapper ctor
[INFO] analysis_server: AnalysisServerWrapper ctor
[INFO] analysis_server: About to start with server with SDK path `D:\apps\Dart\dart-sdk` and args: [--dartpad, --client-id=DartPad, --client-version=2.7.1]
[INFO] rpc: Adding /dartservices/v1 to set of valid APIs.
[INFO] services: Listening on port 8082
[FINE] analysis_server: About to send analysis.updateContent
[FINE] analysis_server:   (C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad3dc191e2-5e87-11ea-9496-8c1645895bf6\main.dart)
[FINE] analysis_server: About to send analysis.updateContent remove overlays:
[FINE] analysis_server:   {C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad3dc191e2-5e87-11ea-9496-8c1645895bf6\main.dart}
[INFO] common_server: Dart analysis server initialized.
[INFO] analysis_server: About to start with server with SDK path `D:\code\flutter\dart-services\flutter/bin\cache/dart-sdk` and args: [--dartpad, --client-id=DartPad, --client-version=2.7.0]
[FINE] analysis_server: About to send analysis.updateContent
[FINE] analysis_server:   (C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad3dc191e2-5e87-11ea-9496-8c1645895bf6\main.dart)
[FINE] analysis_server: About to send analysis.updateContent remove overlays:
[FINE] analysis_server:   {C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad3dc191e2-5e87-11ea-9496-8c1645895bf6\main.dart}
[INFO] common_server: Flutter analysis server initialized.
[INFO] rpc: Enabling Discovery API Service for api: /dartservices/v1
[INFO] rpc: Adding /discovery/v1 to set of valid APIs.
[INFO] rpc: Invoking API: /dartservices/v1 with HTTP method: POST on url: http://127.0.0.1:8082/api/dartservices/v1/compileDDC?alt=json.
[FINER] rpc:
Request for API /dartservices/v1:
  Method: POST
  Path: /api/dartservices/v1/compileDDC
    accept: */*
    accept-encoding: gzip, deflate, br
    accept-language: en-US,en;q=0.9,zh;q=0.8,zh-CN;q=0.7
    connection: keep-alive
    content-length: 690
    content-type: application/json; charset=utf-8
    host: 127.0.0.1:8082
    origin: http://localhost:8000
    referer: http://localhost:8000/
    sec-fetch-dest: empty
    sec-fetch-mode: cors
    sec-fetch-site: cross-site
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
  Body:
    {source: import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text('Hello, World!', style: Theme.of(context).textTheme.headline4);
  }
}
}

[FINE] rpc:
Invoking method: compileDDC with:
  Positional Parameters:
    Instance of 'CompileRequest'
  Named Parameters:

[INFO] flutter_web: creating flutter web pubspec
[INFO] flutter_web: running flutter pub get (C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad3dc191e2-5e87-11ea-9496-8c1645895bf6)
[INFO] flutter_web: Instance of '_StdStream'
[INFO] common_server: CACHE: MISS for compileDDC
[INFO] compiler: Temp directory created: C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad48eb4b2f-5e87-11ea-9496-8c1645895bf6
[INFO] compiler: About to exec "D:\code\flutter\dart-services\flutter/bin\cache/dart-sdk\bin\dartdevc.bat --modules=amd -s artifacts\flutter_web.dill -s D:\code\flutter\dart-services\flutter/bin/cache/flutter_web_sdk/flutter_web_sdk/kernel/flutter_ddc_sdk.dill -o C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad48eb4b2f-5e87-11ea-9496-8c1645895bf6\main.dart.js --module-name dartpad_main C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad48eb4b2f-5e87-11ea-9496-8c1645895bf6\bootstrap.dart --packages=C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad3dc191e2-5e87-11ea-9496-8c1645895bf6\.packages"
[INFO] compiler: Compiling: import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text('Hello, World!', style: Theme.of(context).textTheme.headline4);
  }
}

[INFO] compiler: temp folder removed: C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad48eb4b2f-5e87-11ea-9496-8c1645895bf6
[WARNING] rpc:
Response
  Status Code: 400
  Headers:
    access-control-allow-credentials: true
    access-control-allow-origin: *
    cache-control: no-cache, no-store, must-revalidate
    content-type: application/json; charset=utf-8
    expires: 0
    pragma: no-cache
  Exception:
    RPC Error with status: 400 and message: We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=D:\code\flutter\dart-services\flutter\bin\cache\dart-sdk --modules=amd -s artifacts\flutter_web.dill -s D:\code\flutter\dart-services\flutter/bin/cache/flutter_web_sdk/flutter_web_sdk/kernel/flutter_ddc_sdk.dill -o C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad48eb4b2f-5e87-11ea-9496-8c1645895bf6\main.dart.js --module-name dartpad_main C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad48eb4b2f-5e87-11ea-9496-8c1645895bf6\bootstrap.dart --packages=C:\Users\LIUD~1.H\AppData\Local\Temp\dartpad3dc191e2-5e87-11ea-9496-8c1645895bf6\.packages
    dart --version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "windows_x64"

    ```
    FileSystemException(path=artifacts\flutter_web.dill; message=Cannot open file)
    #0      _PhysicalFile.readAsBytesSync (package:analyzer/file_system/physical_file_system.dart:202:7)
    #1      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:191:21)
    #2      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:140:43)
    #3      List.forEach (dart:core-patch/growable_array.dart:285:8)
    #4      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:140:18)
    #5      new CompilerAnalysisDriver (package:dev_compiler/src/analyzer/driver.dart:75:9)
    #6      _compile (package:dev_compiler/src/analyzer/command.dart:135:22)
    #7      compile (package:dev_compiler/src/analyzer/command.dart:56:18)
    #8      compile (package:dev_compiler/src/compiler/shared_command.dart:410:18)
    #9      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
    #10     _rootRun (dart:async/zone.dart:1126:13)
    #11     _CustomZone.run (dart:async/zone.dart:1023:19)
    #12     _runZoned (dart:async/zone.dart:1518:10)
    #13     runZoned (dart:async/zone.dart:1465:12)
    #14     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
    #15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
    #16     _rootRun (dart:async/zone.dart:1126:13)
    #17     _CustomZone.run (dart:async/zone.dart:1023:19)
    #18     _runZoned (dart:async/zone.dart:1518:10)
    #19     runZoned (dart:async/zone.dart:1465:12)
    #20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
    <asynchronous suspension>
    #21     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
    #22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
    #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
    
    ```
#0      _convertBadRequest (package:dart_services/src/common_server.dart:130:7)
<asynchronous suspension>
#1      CommonServer.compileDDC (package:dart_services/src/common_server.dart:68:7)
#2      _InstanceMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:327:37)
#3      _InstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:323:25)
#4      ApiConfigMethod.invokeWithBody (package:rpc/src/config/method.dart:320:22)
<asynchronous suspension>
#5      ApiConfigMethod.invokeHttpRequest.<anonymous closure> (package:rpc/src/config/method.dart:174:21)
#6      _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#7      _rootRun (dart:async/zone.dart:1126:13)
#8      _CustomZone.run (dart:async/zone.dart:1023:19)
#9      _runZoned (dart:async/zone.dart:1518:10)
#10     runZoned (dart:async/zone.dart:1465:12)
#11     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#12     fork (package:gcloud/service_scope.dart:104:30)
#13     ApiConfigMethod.invokeHttpRequest (package:rpc/src/config/method.dart:164:12)
#14     ApiConfig.handleHttpRequest (package:rpc/src/config/api.dart:38:25)
#15     ApiServer.handleHttpApiRequest (package:rpc/src/server.dart:123:30)
#16     EndpointsServer._apiHandler (package:dart_services/services_dev.dart:144:10)
#17     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:70:46)
#18     new Future.sync (dart:async/future.dart:224:31)
#19     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:70:23)
#20     _rootRunUnary (dart:async/zone.dart:1134:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#25     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:389:9)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

2020-03-05T10:16:03.619464  0:00:10.567404 POST    [400] /api/dartservices/v1/compileDDC?alt=json
```

**Comment by mraleph** [comment]
I think this is most likely issue with dart-pad setup itself (Flutter platform file is missing - it probably needs to be copied into the right location from your Flutter installation) - so you need to ask at dart-lang/dart-pad issue.

**Comment by liudonghua123** [comment]
Hi @mraleph, Where the location of the files in flutter need I to copy to?
