### ISSUE TITLE
List.insert() on VM fails under NNBD

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#40913]
Take this little Dart program:

```dart
main() {
  var list = <int>[1, 2, 3];
  list.insert(1, 4);
  print(list);
}
```

Run it with an NNBD build of the VM like:

```sh
./xcodebuild/ReleaseX64NNBD/dart-sdk/bin/dart --null-safety --enable-experiment=non-nullable temp.dart
```

Behold:

```
Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      List.length= (dart:core-patch/growable_array.dart:120:12)
#1      List.insert (dart:core-patch/growable_array.dart:18:10)
#2      main (file:///Users/rnystrom/Documents/temp.dart:3:8)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
```

In the VM patch file, the implementation of _GrowableList<T>.insert() looks like:

```dart
  void insert(int index, T element) {
    if ((index < 0) || (index > length)) {
      throw new RangeError.range(index, 0, length);
    }
    if (index == this.length) {
      add(element);
      return;
    }
    int oldLength = this.length;
    this.length++; // <--
    Lists.copy(this, index, this, index + 1, oldLength - index);
    this[index] = element;
  }
```

The marked line isn't valid when T is a non-nullable type.

**Comment by lrhn** [comment]
Workarounds could include the VM having an internal `_grow` method which works even on non-nullable lists, or a general rewrite like:
```dart
void insert(int index, T element) {
    if ((index < 0) || (index > length)) {
      throw new RangeError.range(index, 0, length);
    }
    add(element);
    if (index == length) return;
    Lists.copy(this, index, this, index + 1, length - (index + 1));
    this[index] = element;
  }

**Comment by crelier** [comment]
Thanks for the report and for the suggestions for fixing.
Fix sent for review: https://dart-review.googlesource.com/c/sdk/+/139563
