### ISSUE TITLE
Compiler crash: `Type parameter T is not indexed` in generic higher-order extension method

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#40918]
**dart version:** 2.7.0

**code:**
```
import 'dart:isolate';

extension Pmap<T, U> on List<T> {
  static void _process(SendPort sendPort) async {
    var receivePort = new ReceivePort();
    sendPort.send(receivePort.sendPort);
    U Function(T input) mapper = await receivePort.first;
    await for (T input in receivePort) {
      sendPort.send(mapper(input));
    }
  }

  Stream<U> pmap(U Function(T input) mapper, {int parallel = 1}) async* {
    ReceivePort receivePort = new ReceivePort();
    Isolate isolate = await Isolate.spawn(_process, receivePort.sendPort);
    SendPort sendPort = await receivePort.first;
    for (T item in this) {
      sendPort.send(item);
    }
    await for (U result in receivePort) {
      yield result;
    }
    isolate.kill();
  }
}

void main() async {
  List<int> foo = [1, 2, 3, 4];
  int mapper(int x) => x * x;
  Stream<int> results = foo.pmap(mapper);
  await for (int value in results) {
    print(value);
  }
}
```

**error:**
```
Invalid argument(s): Type parameter T is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:2573:8)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2125:38)
#2      TypeParameterType.accept (package:kernel/ast.dart:5996:42)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:392:10)
#4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#5      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:302:7)
#6      BinaryPrinter.visitFunctionType (package:kernel/binary/ast_to_binary.dart:2095:7)
#7      FunctionType.accept (package:kernel/ast.dart:5720:42)
#8      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:392:10)
#9      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#10     BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:2000:5)
#11     BinaryPrinter.visitVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1987:5)
#12     VariableDeclaration.accept (package:kernel/ast.dart:5292:43)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:392:10)
#14     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#15     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:302:7)
#16     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1799:5)
#17     Block.accept (package:kernel/ast.dart:4519:43)
#18     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:392:10)
#19     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#20     BinaryPrinter.visitLabeledStatement (package:kernel/binary/ast_to_binary.dart:1833:5)
#21     LabeledStatement.accept (package:kernel/ast.dart:4633:43)
#22     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:392:10)
#23     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#24     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:302:7)
#25     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1799:5)
#26     Block.accept (package:kernel/ast.dart:4519:43)
#27     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:392:10)
#28     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#29     BinaryPrinter.visitTryCatch (package:kernel/binary/ast_to_binary.dart:1950:5)
#30     TryCatch.accept (package:kernel/ast.dart:4984:43)
#31     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:392:10)
#32     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#33     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:485:7)
#34     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1324:5)
#35     FunctionNode.accept (package:kernel/ast.dart:2499:38)
#36     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:399:10)
#37     BinaryPrinter.visitFunctionDeclaration (package:kernel/binary/ast_to_binary.dart:2026:5)
#38     FunctionDeclaration.accept (package:kernel/ast.dart:5328:43)
#39     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:392:10)
#40     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#41     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:302:7)
#42     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1799:5)
#43     Block.accept (package:kernel/ast.dart:4519:43)
#44     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:392:10)
#45     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:59:11)
#46     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:485:7)
#47     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1324:5)
#48     FunctionNode.accept (package:kernel/ast.dart:2499:38)
#49     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:399:10)
#50     BinaryPrinter.writeOptionalFunctionNode (package:kernel/binary/ast_to_binary.dart:494:7)
#51     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1200:5)
#52     Procedure.accept (package:kernel/ast.dart:2140:40)
#53     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:420:10)
#54     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:311:7)
#55     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:963:5)
#56     Library.accept (package:kernel/ast.dart:532:38)
#57     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:413:10)
#58     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:52:31)
#59     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:562:7)
#60     Timeline.timeSync (dart:developer/timeline.dart:163:22)
#61     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:546:14)
#62     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:75:11)
#63     _processLoadRequest (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:724:41)
<asynchronous suspension>
#64     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by jensjoha** [comment]
7ac22948e58af221fdc92a4b7f2aa4b9df0131c7 fixes it so this doesn't crash the compiler, but the code has errors and cannot be run as is.
