### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by antoniosap** [dart-lang/sdk#40944]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.8.0-edge.fc3af737c75931908521e9c36358a151408d6084`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Linux(amd64) v5.3.0-40-generic, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.fc3af737c75931908521e9c36358a151408d6084, server version 1.27.4, error: Invalid argument(s): Is a part: package:app_waste_2/models/favorites_specs.g_1_.dart
#0      AnalysisDriver.getResolvedLibraryByUri (package:analyzer/src/dart/analysis/driver.dart:754:7)
#1      AnalysisSessionImpl.getResolvedLibraryByElement (package:analyzer/src/dart/analysis/session.dart:169:20)
#2      MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:86:12)
#3      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1019:41)
<asynchronous suspension>
#4      _rootRun (dart:async/zone.dart:1126:13)
#5      _CustomZone.run (dart:async/zone.dart:1023:19)
#6      _runZoned (dart:async/zone.dart:1518:10)
#7      runZoned (dart:async/zone.dart:1502:12)
#8      _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:975:5)
#9      EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:853:24)
#10     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:388:16)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:313:45)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:309:50)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1502:12)
#18     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:308:5)
#19     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#21     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#22     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#23     _rootRunUnary (dart:async/zone.dart:1134:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#30     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#31     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#32     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#33     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#34     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#35     _rootRunUnary (dart:async/zone.dart:1134:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#40     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#41     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#42     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#43     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#44     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#45     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#46     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#48     _rootRunUnary (dart:async/zone.dart:1134:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#53     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#54     _StreamController._add (dart:async/stream_controller.dart:649:7)
#55     _StreamController.add (dart:async/stream_controller.dart:595:5)
#56     _Socket._onData (dart:io-patch/socket_patch.dart:1873:41)
#57     _rootRunUnary (dart:async/zone.dart:1138:13)
#58     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#60     _BufferingStreamSubscription._sendData (dart:a...
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.8; please re-open if you see this in a recent version of Dart/Flutter.
