### ISSUE TITLE
Type testing stubs for generic types with type parameters do not fully test types of type parameters

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#40964]
```dart
import "package:expect/expect.dart";

class A<T> {
  test(x) => x as B<T>;
}

class B<T> {
}

class C<T> {
}

main() {
  final a = A<C<int>>();
  a.test(new B<C<int>>());
  Expect.throwsCastError(() => a.test(new B<C<num>>()));
}
```

This test fails in AOT mode (but works in JIT):
```
pkg/vm/tool/precompiler2 foo.dart foo.snapshot && pkg/vm/tool/dart_precompiled_runtime2 foo.snapshot
Unhandled exception:
Expect.throws(CastError) fails: Did not throw
#0      Expect._fail (package:expect/expect.dart:682)
#1      Expect.throws (package:expect/expect.dart:585)
#2      Expect.throwsCastError (package:expect/expect.dart:598)
#3      main (file:///.../foo.dart:17)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168)
```

This happens because type testing stub for a generic type with type parameter `B<T>`, when testing if `B<X>` is assignable to `B<T>`, only tests if `X.type_class_id == T.type_class_id`, but it doesn't test that `X.arguments` are compatible with `T.arguments`.

https://github.com/dart-lang/sdk/blob/bef363bfb7d6364ddbaabd691c0fdc963cff8cc6/runtime/vm/type_testing_stubs.cc#L437-L446

/cc @mkustermann

**Comment by mkustermann** [comment]
I can take a look at this.

**Comment by crelier** [comment]
Thanks Martin!

**Comment by mkustermann** [comment]
I think this should be fixed now.
