### ISSUE TITLE
ClassMirror.declarations throws in NNBD

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#40997]
This is breaking for the `HavingMatcher` from `package:matcher`.

Repro program:

```dart
import 'dart:mirrors';

void main() {
  var myList = [1, 2, 3];
  var classMirror = reflect(myList).type;
  print(classMirror.declarations[#length]);
}
```

When enabling the non-nullable experiment with the `--null_safety` flag on the VM, this program gives the following exception:

```
Unhandled exception:
type 'Null' is not a subtype of type 'Type' of 'function result'
#0      _ClassMirror._nativeMixinInstantiated (dart:mirrors-patch/mirrors_impl.dart)
#1      _ClassMirror.mixin (dart:mirrors-patch/mirrors_impl.dart:500:22)
#2      _ClassMirror.declarations (dart:mirrors-patch/mirrors_impl.dart:575:35)
#3      main (file:///home/jakemac/matcher/bin/repro.dart:6:21)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
```

**Comment by rmacnak-google** [comment]
I think this is a bug in the mirrors implementation rather than the NNBD implementation.

**Comment by alexmarkov** [comment]
Verified that example above works fine with `--enable-experiment=non-nullable --null-safety`.
