### ISSUE TITLE
After configuring the dart SDK path in android studio. It shows error like this.

### ISSUE THREAD

**Issue by GOPINATHSWAMINATHAN** [dart-lang/sdk#41010]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.8.0-edge.9983424a3c50c623730fd43b4ce263df660eb455`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Analysis failed: /Users/gopinath/Desktop/fluttercidproject/newdriverappflutter/cidexdriver/test/widget_test.dart
Invalid argument(s): Cannot serialize an instance of GenericFunctionTypeImpl
#0      AbstractConstExprSerializer.serializeTypeName (package:analyzer/src/summary/summarize_const_expr.dart:211)
#1      AbstractConstExprSerializer._serializeListLiteral (package:analyzer/src/summary/summarize_const_expr.dart:550)
#2      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:356)
#3      AbstractConstExprSerializer.serialize (package:analyzer/src/summary/summarize_const_expr.dart:139)
#4      _SummarizeAstVisitor.serializeConstExpr (package:analyzer/src/summary/summarize_ast.dart:557)
#5      _SummarizeAstVisitor.serializeFunctionBody (package:analyzer/src/summary/summarize_ast.dart:755)
#6      _SummarizeAstVisitor.serializeInitializerFunction (package:analyzer/src/summary/summarize_ast.dart:828)
#7      _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:1029)
#8      _SummarizeAstVisitor.visitFieldDeclaration (package:analyzer/src/summary/summarize_ast.dart:1210)
#9      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399)
#10     _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:472)
#11     _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1076)
#12     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#14     _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:525)
#15     serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22)
#16     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:473)
#17     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#18     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:472)
#19     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:805)
#20     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:593)
#21     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:531)
#22     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:805)
#23     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:593)
#24     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:531)
#25     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:805)
#26     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:593)
#27     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:531)
#28     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:805)
#29     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:593)
#30     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:531)
#31     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:805)
#32     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:593)
#33     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:536)
#34     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:805)
#35     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:593)
#36     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:531)
#37     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:766)
#38     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:954)
#39     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:854)
<asynchronous suspension>
#40     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#41     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#42     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#43     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#44     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#45     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#46     _rootRun (dart:async/zone.dart:1120)
#47     _CustomZone.run (dart:async/zone.dart:1001)
#48     runZoned (dart:async/zone.dart:1467)
#49     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#50     Driver.start (package:analysis_server/src/server/driver.dart:473)
#51     main (file:///Users/whesse/dart/sdk/pkg/analysis_server/bin/server.dart:12)
#52     _startIsolate.<anonymous closure> (dart:isolate-patch/isola...
```

For additional log information, please append the contents of
file:///private/var/folders/rg/86ls6m0n1c5b5r19cgmk53c40000gn/T/report.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.8.0. Please re-open if you see this crash again.
