### ISSUE TITLE
Unable to extract variable

### ISSUE THREAD

**Issue by avi-mastov** [dart-lang/sdk#41013]
Expression type was dynamic (result of `this["..."]` where `this` is `MapObject`.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.7.0`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.3, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.7.0, server version 1.27.4, error: NoSuchMethodError: The method 'endsWith' was called on null.
Receiver: null
Tried calling: endsWith("s")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _getBaseNameFromUnwrappedExpression (package:analysis_server/src/services/correction/name_suggestion.dart:214:14)
#2      _getBaseNameFromExpression (package:analysis_server/src/services/correction/name_suggestion.dart:161:10)
#3      getVariableNameSuggestionsForExpression (package:analysis_server/src/services/correction/name_suggestion.dart:52:33)
#4      ExtractLocalRefactoringImpl._prepareNames (package:analysis_server/src/services/refactoring/extract_local.dart:488:20)
#5      ExtractLocalRefactoringImpl.checkInitialConditions (package:analysis_server/src/services/refactoring/extract_local.dart:102:5)
#6      _RefactoringManager._init (package:analysis_server/src/edit/edit_domain.dart:1202:36)
<asynchronous suspension>
#7      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:988:13)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1126:13)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10     _runZoned (dart:async/zone.dart:1518:10)
#11     runZoned (dart:async/zone.dart:1502:12)
#12     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:985:5)
#13     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:863:24)
#14     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:393:16)
#15     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:45)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#17     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:329:50)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1502:12)
#22     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:328:5)
#23     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#25     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#26     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#27     _rootRunUnary (dart:async/zone.dart:1134:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#35     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#36     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#37     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#39     _rootRunUnary (dart:async/zone.dart:1134:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#41     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#44     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#45     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#46     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#47     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#48     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#49     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#50     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#51     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#52     _rootRunUnary (dart:async/zone.dart:1134:38)
#53     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#57     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart...
```

For additional log information, please append the contents of
file:///private/var/folders/dp/h6plz3hn5_g18rrzdgr32wv80000gn/T/report.txt.

**Comment by srawlins** [comment]
Apologies that we did not get a chance to look at this crash. Please re-open if you see this again with a recent version of Dart.
