### ISSUE TITLE
Migration: NPE in assertion in stack trace builder

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41021]
Occurring in package:collection.

```
Exception while running dartfix: NoSuchMethodError: The getter 'targetNode' was called on null.\nReceiver: null\nTried calling: targetNode\n#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)\n#1      InfoBuilder._computeTraceInfo (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:520:27)\n#2      InfoBuilder._computeTraces (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:547:37)\n#3      InfoBuilder._explainUnit (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:675:48)\n#4      InfoBuilder.explainMigration (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:97:27)\n<asynchronous suspension>\n#5      MigrationState.refresh
```

**Comment by stereotype441** [comment]
I'm not able to replicate this with fcefb8258ec.  @MichaelRFairhurst can you provide more detailed repro instructions?

**Comment by MichaelRFairhurst** [comment]
You likely need to enable asserts. Providing '--debug' will do that for you

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
