### ISSUE TITLE
Migration: Failed assertion in stack trace builder

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41020]
```
Exception while running dartfix: 'package:analysis_server/src/edit/nnbd_migration/info_builder.dart': Failed assertion: line 545 pos 16: 'reason.sourceNode.isNullable': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      InfoBuilder._computeTraces (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:545:16)
#3      InfoBuilder._explainUnit (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:680:48)
#4      InfoBuilder.explainMigration (package:analysis_server/src/edit/nnbd_migration/info_builder.dart:97:27)
<asynchronous suspension>
#5      MigrationState.refresh (package:analysis_server/src/edit/nnbd_migration/migration_state.dart:52:49)
#6      NonNullableFix.finish (package:analysis_server/src/edit/fix/non_nullable_fix.dart:96:17)
#7      FixCodeProcessor.finishCodeTasks (package:analysis_server/src/edit/fix/fix_code_task.dart:32:18)
#8      EditDartFix.runAllTasks (package:analysis_server/src/edit/edit_dartfix.dart:177:13)
<asynchronous suspension>
#9
```

```dart
class C<T extends Object/*!*/> {}                                                
                                                                                 
C<int /*?*/ > c;                                                                 
                                                                                 
Map<int, String> x = {};                                                         
String/*!*/ y = x[0];
```

**Comment by stereotype441** [comment]
https://dart-review.googlesource.com/c/sdk/+/139317
