### ISSUE TITLE
Flutter RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by pnk0006** [dart-lang/sdk#41031]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `1.24.3`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.2, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Captured exception
NoSuchMethodError: The getter 'libraryNameOffset' was called on null.
Receiver: null
Tried calling: libraryNameOffset
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      FileState.isPart (package:analyzer/src/dart/analysis/file_state.dart:243)
#3      _TopLevelNameDeclarationsTask.perform (package:analyzer/src/dart/analysis/driver.dart:1991)
<asynchronous suspension>
#4      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:821)
<asynchronous suspension>
#5      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#6      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#7      new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#8      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#9      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#10     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#11     _rootRun (dart:async/zone.dart:1120)
#12     _CustomZone.run (dart:async/zone.dart:1001)
#13     runZoned (dart:async/zone.dart:1467)
#14     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#15     Driver.start (package:analysis_server/src/server/driver.dart:473)
#16     main (file:///Users/whesse/dart/sdk/pkg/analysis_server/bin/server.dart:12)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

For additional log information, please append the contents of
file:///private/var/folders/5b/3nrqvs010lg4__l_86v2wdzr0000gn/T/report1.txt.

**Comment by srawlins** [comment]
Dart 1.24 is quite old. This issue may be fixed in a more recent version of Dart. Please re-open if you see this issue on a recent version of Dart.

**Comment by ditistijn** [comment]
I'm having the same problem. Stopped working after I rebuilt the app for iOS. Tried flutter clean and upgrade. Nothing resolves this issue. I am on the master channel.
