### ISSUE TITLE
Failures on Check for importedLibrary is null in importLibraryElement().

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#41049]
There are new test failures on [Check for importedLibrary is null in importLibraryElement().](https://github.com/dart-lang/sdk/commit/7079c49b054e211b6efac6964574e65635e5da43).

The tests
```
co19_2/LibTest/io/FileSystemCreateEvent/path_A01_t01 RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-mac-release-x64
```

**Comment by dcharkes** [comment]
```
--- Command "vm" (took 678ms):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/path_A01_t01.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: </b/s/w/itNlFoSb/path_A01_t01_N6XyZ6/path_A01_t01_jMvCwb/bNhxz7>, actual: </b/s/w/itNlFoSb/path_A01_t01_N6XyZ6/path_A01_t01_jMvCwb>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.equals (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:30:5)
#2      _main.<anonymous closure> (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/path_A01_t01.dart:32:16)
#3      testFileSystemEvent (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:53:7)
<asynchronous suspension>
#4      _main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/path_A01_t01.dart:28:9)
#5      inSandbox (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:24:22)
#6      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/path_A01_t01.dart:20:9)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartk-mac-release-x64 co19_2/LibTest/io/FileSystemCreateEvent/path_A01_t01
```

This change made the location of the thrown exception change.

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8885727033799883632/+/steps/test_results/0/logs/new_test_failures__logs_/0

**Comment by scheglov** [comment]
I don't think that this has anything with the analyzer / DAS changes.

**Comment by cskau-g** [comment]
I'm curious, was this ever addressed?
I'm now seeing the exact same failure for a different set of CLs:
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-mac-release-x64/8757

**Comment by aam** [comment]
I believe the culprit is with test itself which relies on how quickly directory watching events are processed. That create temp directory event for https://github.com/dart-lang/co19/blob/master/LibTest/io/FileSystemCreateEvent/path_A01_t01.dart#L24 is sent and processed before one that comes for child temp directory https://github.com/dart-lang/co19/blob/master/LibTest/io/FileSystemCreateEvent/path_A01_t01.dart#L30.

The failure of the test happens when parent temp directory event comes after directory listener is created.

https://github.com/dart-lang/co19/issues/672 was created to track this on co19 side of things.

**Comment by zichangg** [comment]
Another witness: https://dart-ci.appspot.com/log/vm-kernel-mac-release-x64/dartk-mac-release-x64/8810/co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t02

This failed with the same reason.
