### ISSUE TITLE
starting the app this message come out

### ISSUE THREAD

**Issue by Miamoto-Musashi** [dart-lang/sdk#41113]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.7.0`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.3, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.7.0, server version 1.27.4, error: type 'ParsedDartFile' is not a subtype of type 'ParsedMoorFile' in type cast
#0      _MoorBaseRequest.parsedMoor (package:moor_generator/src/backends/plugin/services/requests.dart:23:31)
#1      MoorNavigationContributor.computeNavigation (package:moor_generator/src/backends/plugin/services/navigation.dart:20:19)
#2      NavigationGenerator.generateNavigationNotification (package:analyzer_plugin_fork/utilities/navigation/navigation.dart:91:21)
#3      NavigationMixin.sendNavigationNotification (package:analyzer_plugin_fork/plugin/navigation_mixin.dart:97:21)
<asynchronous suspension>
#4      ServerPlugin._sendNotificationForFile (package:analyzer_plugin_fork/plugin/plugin.dart:747:9)
#5      ServerPlugin.sendNotificationsForSubscriptions.<anonymous closure> (package:analyzer_plugin_fork/plugin/plugin.dart:581:9)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#7      ServerPlugin.sendNotificationsForSubscriptions (package:analyzer_plugin_fork/plugin/plugin.dart:579:19)
#8      ServerPlugin.handleAnalysisSetSubscriptions (package:analyzer_plugin_fork/plugin/plugin.dart:355:5)
<asynchronous suspension>
#9      ServerPlugin._getResponse (package:analyzer_plugin_fork/plugin/plugin.dart:660:24)
<asynchronous suspension>
#10     ServerPlugin._onRequest (package:analyzer_plugin_fork/plugin/plugin.dart:720:24)
<asynchronous suspension>
#11     PluginIsolateChannel.listen.onData (package:analyzer_plugin_fork/src/channel/isolate_channel.dart:127:18)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#16     _StreamController._add (dart:async/stream_controller.dart:642:7)
#17     _StreamController.add (dart:async/stream_controller.dart:588:5)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file:///private/var/folders/ny/xp6sbyk17_v_bjftblhb5hvw0000gp/T/report.txt.

**Comment by devoncarew** [comment]
It looks like you're using a `package:moor_generator` analyzer plugin. Can you re-file this issue with that package?

**Comment by Miamoto-Musashi** [comment]
Yes, I can do can you help me with this?

**Comment by devoncarew** [comment]
Are you developing the package or using it? If using it, I'd file an issue against it's repo.
