### ISSUE TITLE
NoSuchMethodError: The method 'toFilePath' was called on null when generating docs

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#41159]
The dartdoc step during SDK creation is failing with a NoSuchMethodError in NNBD mode

```
asiva-desktop[sdk]>out/DebugX64/dart-sdk/bin/dart third_party/pkg/dartdoc/bin/dartdoc.dart --sdk-docs --output out/DebugX64/gen-dartdocs --footer tools/bots/dartdoc_footer.html --rel-canonical-prefix=https://api.dartlang.org/stable
Documenting Dart...
parsing /usr/local/google/home/asiva/workspace/dart-nnbd/sdk/out/DebugX64/dart-sdk/lib/async/async.dart...
parsing /usr/local/google/home/asiva/workspace/dart-nnbd/sdk/out/DebugX64/dart-sdk/lib/collection/collection.dart...



asiva-desktop[sdk]>out/DebugX64NNBD/dart-sdk/bin/dart third_party/pkg/dartdoc/bin/dartdoc.dart --sdk-docs --output out/DebugX64NNBD/gen-dartdocs --footer tools/bots/dartdoc_footer.html --rel-canonical-prefix=https://api.dartlang.org/stable
Unhandled exception:
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Templates.fromContext (package:dartdoc/src/generator/templates.dart:200:55)
<asynchronous suspension>
#2      initHtmlGenerator (package:dartdoc/src/generator/html_generator.dart:22:35)
#3      Dartdoc.fromContext (package:dartdoc/dartdoc.dart:131:27)
#4      main (file:///usr/local/google/home/asiva/workspace/dart-nnbd/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart:90:23)
<asynchronous suspension>
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
```

**Comment by a-siva** [comment]
@liamappelbe this can be closed correct?

**Comment by liamappelbe** [comment]
Yep. Fixed by https://dart-review.googlesource.com/c/sdk/+/140773
