### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<String>?' of '_parts@0150898'

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#41163]
All the tests in dartkb bots are failing with the following error.

```
pkg/vm/tool/gen_kernel --no-aot --platform=out/ReleaseSIMARM64/vm_platform_strong.dill -o /tmp/out.dill  tests/co19_2/src/Language/Classes/Abstract_Instance_Members/inherited_t07.dart -Ddart.developer.causal_async_stacks=true --gen-bytecode --drop-ast --bytecode-options=source-positions,annotations,local-var-info,debugger-stops

out/ReleaseSIMARM64/dart --enable_interpreter --compilation-counter-threshold=-1 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /tmp/out.dill
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'List<String>?' of '_parts@0150898'
#0      StringBuffer._addPart (dart:core-patch/string_buffer_patch.dart:168:7)
#1      StringBuffer.write (dart:core-patch/string_buffer_patch.dart:67:5)
#2      ListIterable.join (dart:_internal/iterable.dart:155:16)
#3      _Uri._makePath (dart:core/uri.dart:2209:12)
#4      new _Uri (dart:core/uri.dart:1525:12)
#5      _Uri._makeFileUri (dart:core/uri.dart:1762:14)
#6      new _Uri.directory (dart:core/uri.dart:1707:11)
#7      _setWorkingDirectory (dart:_builtin:577:27)

```

**Comment by a-siva** [comment]
See https://dart-review.googlesource.com/c/sdk/+/138902/7 for test results.
