### ISSUE TITLE
type '(ProcessSignal) => dynamic' is not a subtype of type '((dynamic) => void)?' of 'onData'

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#41162]
Patch in the CL https://dart-review.googlesource.com/c/sdk/+/138902
and  run the following commands

python -u tools/gn.py '--mode=release' '--arch=x64' --bytecode
ninja -C out/ReleaseX64 runtime

This resulst in the following error:

```
Unhandled exception:
type '(ProcessSignal) => dynamic' is not a subtype of type '((dynamic) => void)?' of 'onData'
#0      _registerSignalHandler (dart:vmservice_io:229:61)
#1      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#2      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#3      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'FutureOr<List<InternetAddress>>'
#0      _NativeSocket.lookup.<anonymous closure> (dart:io-patch/socket_patch.dart:396:9)
#1      _rootRunUnary (dart:async/zone.dart:1162:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1064:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:557:7)
#8      _rootRun (dart:async/zone.dart:1154:13)
#9      _CustomZone.run (dart:async/zone.dart:1057:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:985:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:117:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:5)

ninja: build stopped: subcommand failed.
```

**Comment by crelier** [comment]
The state of the bytecode pipeline is unclear at this point.

**Comment by a-siva** [comment]
What should we do when we unfork as these bots will stop building with this error.

**Comment by alexmarkov** [comment]
This is similar to https://github.com/dart-lang/sdk/issues/41163.
Let me take a look.
