### ISSUE TITLE
what happened？

### ISSUE THREAD

**Issue by xiaogou56** [dart-lang/sdk#41196]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.3.0-edge.ee2609db704edc13b555d29c7d4ea5bfc404eceb`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.2, screens 1536x960  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.ee2609db704edc13b555d29c7d4ea5bfc404eceb, server version 1.26.0, error: Failed to handle completion domain request: {id: 1, method: completion.setSubscriptions, params: {subscriptions: [AVAILABLE_SUGGESTION_SETS]}, clientRequestTime: 1585121452033}
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _protocolAvailableSuggestionSet (package:analysis_server/src/domains/completion/available_suggestions.dart:141:35)
#2      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:75:14)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:76:8)
#6      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:482:11)
#7      _rootRunUnary (dart:async/zone.dart:1136:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/wr/p4d1x9j92671jy12_1bzq5w40000gn/T/report1.txt.

**Comment by srawlins** [comment]
Apologies that we didn't get to this issue before it became stale. Please re-open if you encounter this on a recent version of Dart.
