### ISSUE TITLE
Crash when compiling ... Tried calling: accept<DartType>(Instance of '_TypeSchemaEliminationVisitor')

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#41199]
`pub version`
`Pub 2.8.0-dev.17.0`

Edit: run the example in the first comment.

`dart bird/code/example/code/fp/crash.dart`
```
Crash when compiling [...]bird/bird/code/example/code/fp/crash.dart,
at character offset 571:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<DartType>(Instance of '_TypeSchemaEliminationVisitor')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ReplacementVisitor.visitInterfaceType (package:kernel/src/replacement_visitor.dart:134:53)
#2      InterfaceType.accept (package:kernel/ast.dart:6478:42)
#3      _TypeSchemaEliminationVisitor.run (package:front_end/src/fasta/type_inference/type_schema_elimination.dart:75:30)
#4      greatestClosure (package:front_end/src/fasta/type_inference/type_schema_elimination.dart:25:35)
#5      new ClosureContext (package:front_end/src/fasta/type_inference/type_inferrer.dart:158:9)
#6      TypeInferrerImpl.inferLocalFunction (package:front_end/src/fasta/type_inference/type_inferrer.dart:2541:41)
#7      InferenceVisitor.visitFunctionNode (package:front_end/src/fasta/kernel/inference_visitor.dart:1039:21)
#8      InferenceVisitor.visitFunctionExpression (package:front_end/src/fasta/kernel/inference_visitor.dart:1064:9)
#9      FunctionExpression.accept1 (package:kernel/ast.dart:4920:9)
#10     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1926:27)
#11     TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2191:44)
#12     TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2014:12)
#13     TypeInferrerImpl._inferFunctionInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2750:40)
#14     TypeInferrerImpl.inferMethodInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:3129:16)
#15     InferenceVisitor.visitExpressionInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:2331:21)
#16     ExpressionInvocation.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:854:20)
#17     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1924:27)
#18     TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2191:44)
#19     TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2014:12)
#20     InferenceVisitor.visitStaticInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:5032:49)
#21     StaticInvocation.accept1 (package:kernel/ast.dart:3792:9)
#22     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1926:27)
#23     InferenceVisitor.visitExpressionStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:705:49)
#24     ExpressionStatement.accept (package:kernel/ast.dart:5121:43)
#25     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3307:24)
#26     InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:301:20)
#27     InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:322:30)
#28     Block.accept (package:kernel/ast.dart:5154:43)
#29     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3307:24)
#30     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:1967:39)
#31     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:956:28)
#32     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:916:14)
#33     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:954:7)
#34     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:353:5)
#35     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2544:14)
#36     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2382:14)
#37     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:500:14)
#38     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
#39     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:347:14)
<asynchronous suspension>
#40     Loader.buildBodies (package:front_end/src/fasta/loader.dart:238:15)
#41     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:347:20)
#42     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#43     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:345:12)
#44     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:140:38)
<asynchronous suspension>
#45     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#46     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#47     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#48     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#49     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#50     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#51     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#52     new Future.sync (dart:async/future.dart:224:31)
#53     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#54     _rootRun (dart:async/zone.dart:1147:13)
#55     _CustomZone.run (dart:async/zone.dart:1040:19)
#56     _runZoned (dart:async/zone.dart:1539:10)
#57     runZoned (dart:async/zone.dart:1486:12)
#58     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#59     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#60     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#61     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#62     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:400:17)
#63     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:168:45)
#64     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#65     _rootRun (dart:async/zone.dart:1143:38)
#66     _CustomZone.run (dart:async/zone.dart:1040:19)
#67     _CustomZone.runGuarded (dart:async/zone.dart:942:7)
#68     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:982:23)
#69     _rootRun (dart:async/zone.dart:1147:13)
#70     _CustomZone.run (dart:async/zone.dart:1040:19)
#71     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:966:23)
#72     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#73     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#74     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#75     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:959:7)
#1      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:353:5)
#2      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2544:14)
#3      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2382:14)
#4      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:500:14)
#5      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
#6      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:347:14)
<asynchronous suspension>
#7      Loader.buildBodies (package:front_end/src/fasta/loader.dart:238:15)
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:347:20)
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#10     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:345:12)
#11     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:140:38)
<asynchronous suspension>
#12     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#14     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#15     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#16     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#17     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#18     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#19     new Future.sync (dart:async/future.dart:224:31)
#20     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#21     _rootRun (dart:async/zone.dart:1147:13)
#22     _CustomZone.run (dart:async/zone.dart:1040:19)
#23     _runZoned (dart:async/zone.dart:1539:10)
#24     runZoned (dart:async/zone.dart:1486:12)
#25     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#26     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#27     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#28     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#29     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:400:17)
#30     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:168:45)
#31     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#32     _rootRun (dart:async/zone.dart:1143:38)
#33     _CustomZone.run (dart:async/zone.dart:1040:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:942:7)
#35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:982:23)
#36     _rootRun (dart:async/zone.dart:1147:13)
#37     _CustomZone.run (dart:async/zone.dart:1040:19)
#38     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:966:23)
#39     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#40     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#41     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by modulovalue** [comment]
A self-contained example that leads to that crash:

(Sorry, I didn't see a way to reduce it even further)

```dart
abstract class Kind<Z, A> {}

abstract class ForFunctor {}

extension<F extends ForFunctor, A> on Kind<F, A> {
  Functor<F, A> get DF => this as Functor<F, A>;
}

abstract class Functor<F extends ForFunctor, A> {
  Kind<F, C> fmap<C>(C Function(A) f);
}

extension KindIDMonadFix<A> on Kind<ForId, A> {
  Id<A> get D => this as Id<A>;
}

abstract class ForMonad implements ForFunctor {}

extension<F extends ForMonad, A> on Kind<F, A> {
  Monad<F, A> get DMonad => this as Monad<F, A>;
}

abstract class Monad<F extends ForMonad, A> implements Functor<F, A> {
  Kind<F, C> bind<C>(Kind<F, C> Function(A) f);
}

extension KindFreeFix<F, A> on Kind<Kind<ForFree, F>, A> {
  Free<F, A> get D => this as Free<F, A>;
}

abstract class ForFree {}

abstract class PartFree<F> implements Kind<ForFree, F>, ForMonad {}

abstract class Free<F, A> implements Kind<PartFree<F>, A>, Monad<PartFree<F>, A> {
  factory Free(Kind<F, A> a) => Bind(a, (A a) => Pure(a));

  Kind<G, A> run<G extends ForMonad>(
    Kind<G, A> Function(A) pure,
    Kind<G, B> Function<B>(Kind<F, B>) eval,
  ) =>
      fold(pure, <B>(sub, cont) {
        return eval(sub).DMonad.bind((a) => cont(a).run(pure, eval));
      });

  const Free._sub();

  R fold<R>(R Function(A) pure, R Function<B>(Kind<F, B> p, Free<F, A> Function(B) f) bind);
}

class Pure<F, A> extends Free<F, A> {
  final A a;

  const Pure(this.a) : super._sub();

  @override
  R fold<R>(R Function(A p1) pure, R Function<B2>(Kind<F, B2> p, Free<F, A> Function(B2 p1) f) _) => pure(a);

  @override
  Free<F, C> fmap<C>(C Function(A) f) => Pure(f(a));

  @override
  Free<F, C> bind<C>(Kind<PartFree<F>, C> Function(A) f) => KindFreeFix(f(a)).D;
}

class Bind<F, A, B> extends Free<F, A> {
  final Kind<F, B> p;
  final Kind<PartFree<F>, A> Function(B) cont;

  const Bind(this.p, this.cont) : super._sub();

  @override
  R fold<R>(R Function(A p1) _, R Function<B2>(Kind<F, B2> p, Free<F, A> Function(B2 p1) f) bind) =>
      bind(p, (B a) => KindFreeFix(cont(a)).D);

  @override
  Free<F, C> fmap<C>(C Function(A) f) => KindFreeFix(bind((a) => Pure(f(a)))).D;

  @override
  Free<F, C> bind<C>(Kind<PartFree<F>, C> Function(A) f) => Bind(p, (B a) => cont(a).DMonad.bind(f));
}

abstract class ForId implements ForMonad {}

class Id<A> implements Kind<ForId, A>, Monad<ForId, A> {
  final A value;

  const Id(this.value);

  @override
  Kind<ForId, C> bind<C>(Kind<ForId, C> Function(A) f) => f(value);

  @override
  Kind<ForId, C> fmap<C>(C Function(A) f) => Id(f(value));
}

abstract class ForBanking {}

class BankingDsl<A> implements Kind<ForBanking, A> {
  final Kind<ForId, A> Function(BankingAlgebra) visit;

  const BankingDsl(this.visit);
}

class BankingAlgebra {
  Kind<ForId, String> accounts() => const Id("abc");
}

void main() {
  print(Free(BankingDsl((v) => v.accounts())).run((a) => Id(a), <B>(a) => (a as BankingDsl<B>).visit(BankingAlgebra())));
}
```

**Comment by modulovalue** [comment]
Hey @stefantsov, did you get a chance to look into it?

**Comment by stefantsov** [comment]
Sorry for the delayed response.  I haven't yet looked into the issue, but will try to come up with the fix sometime this week.

**Comment by stefantsov** [comment]
I was able to construct a small repro:

```dart
foo<X>(Map<X, Y> Function<Y>() f) => null;
baz() => foo(<Z>() => <dynamic, Z>{});
```

It seems that there is an issue in how we handle not-yet-inferred types in type substitutions.

**Comment by stefantsov** [comment]
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/144361
