### ISSUE TITLE
Failures on Reland "[dart:io] Fix hanging on zero-length datagram"

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#41240]
There are new test failures on [Reland "[dart:io] Fix hanging on zero-length datagram"](https://github.com/dart-lang/sdk/commit/fdf4762c9946bf0b239b6ca90c6c8ff8f4cdeaeb).

The tests
```
vm/cc/Service_Profile Crash (expected Pass)
```
are failing on configurations
```
dartk-asan-linux-release-x64
```

Log:
```
/============================================================\
| vm/cc/Service_Profile broke (Pass -> Crash, expected Pass) |
\============================================================/

--- Command "run_vm_unittest" (took 02.000539s):
DART_CONFIGURATION=ReleaseASANX64 out/ReleaseASANX64/run_vm_tests --dfe=/b/s/w/ir/cache/builder/sdk/out/ReleaseASANX64/gen/kernel-service.dart.snapshot --ignore-unrecognized-flags Service_Profile

exit code:
-6

stdout:
Running test: Service_Profile
Done: Service_Profile

stderr:
=================================================================
==6977==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 96 byte(s) in 3 object(s) allocated from:
    #0 0x55fe32c48fe1 in strdup ../recipe_cleanup/clangshYTOG/llvm_build_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/asan/asan_interceptors.cpp:452:3
    #1 0x55fe3392ba98 in dart::NativeSymbolResolver::LookupSharedObject(unsigned long, unsigned long*, char**) ../../out/ReleaseASANX64/../../runtime/vm/native_symbol_linux.cc:56:15
    #2 0x55fe33af2973 in dart::ProfileCode::SetFunctionAndName(dart::ProfileFunctionTable*) ../../out/ReleaseASANX64/../../runtime/vm/profiler_service.cc:648:11
    #3 0x55fe33afefa5 in dart::ProfileBuilder::BuildFunctionTable() ../../out/ReleaseASANX64/../../runtime/vm/profiler_service.cc:1159:13
    #4 0x55fe33af65f1 in dart::ProfileBuilder::Build() ../../out/ReleaseASANX64/../../runtime/vm/profiler_service.cc:1012:5
    #5 0x55fe33af9dfa in dart::Profile::Build(dart::Thread*, dart::SampleFilter*, dart::SampleBuffer*) ../../out/ReleaseASANX64/../../runtime/vm/profiler_service.cc:1544:11
    #6 0x55fe33af9dfa in dart::ProfilerService::PrintJSONImpl(dart::Thread*, dart::JSONStream*, dart::SampleFilter*, dart::SampleBuffer*, bool) ../../out/ReleaseASANX64/../../runtime/vm/profiler_service.cc:1839:11
    #7 0x55fe33afa196 in dart::ProfilerService::PrintJSON(dart::JSONStream*, long, long, bool) ../../out/ReleaseASANX64/../../runtime/vm/profiler_service.cc:1865:3
    #8 0x55fe33c2f6ec in dart::GetCpuSamples(dart::Thread*, dart::JSONStream*) ../../out/ReleaseASANX64/../../runtime/vm/service.cc:3891:3
    #9 0x55fe33c27374 in dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool) ../../out/ReleaseASANX64/../../runtime/vm/service.cc:929:11
    #10 0x55fe33c28160 in dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&) ../../out/ReleaseASANX64/../../runtime/vm/service.cc:977:38
    #11 0x55fe32fc14d6 in dart::HandleIsolateMessage(dart::Isolate*, dart::Array const&) ../../out/ReleaseASANX64/../../runtime/vm/service_test.cc:136:3
    #12 0x55fe32fc14d6 in dart::Dart_TestHelperService_Profile(dart::Thread*) ../../out/ReleaseASANX64/../../runtime/vm/service_test.cc:721:3
    #13 0x55fe32fc14d6 in dart::Dart_TestService_Profile() ../../out/ReleaseASANX64/../../runtime/vm/service_test.cc:686:1
    #14 0x55fe32c8bb19 in dart::TestCase::Run() ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:52:3
    #15 0x55fe32c8be2f in dart::TestCaseBase::RunTest() ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:64:11
    #16 0x55fe33076d32 in dart::TestCaseBase::RunAll() ../../out/ReleaseASANX64/../../runtime/vm/unit_test.cc:86:13
    #17 0x55fe32c8cbee in dart::Main(int, char const**) ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:394:3
    #18 0x55fe32c8c30a in main ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:425:29
    #19 0x7fc4e9a4882f in __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:291

SUMMARY: AddressSanitizer: 96 byte(s) leaked in 3 allocation(s).

--- Re-run this test:
python tools/test.py -n dartk-asan-linux-release-x64 vm/cc/Service_Profile
```

/cc @ZichangG @rmacnak-google

**Comment by rmacnak-google** [comment]
I think this is unrelated to the dart:io change, just that there's a change in timing.

**Comment by ZichangG** [comment]
https://dart-review.googlesource.com/c/sdk/+/141400

There is a field which is not freed. I don't understand why this test starts failing now. I switched back to commits before my change. The test was broken then.
