### ISSUE TITLE
CFE and analyzer crashes on syntactically malformed program

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#41265]
The following malformed program causes a crash in the CFE:

```dart
class A<T> {}

mixin M<T> {}

// Note extraneous trailing "Function()>" on the next line
class DND1 extends Object with M<dynamic> Function()> {
}
```

See also https://github.com/dart-lang/sdk/issues/41264

Stacktrace below:

```
Crash when compiling file:///Users/leafp/tmp/test4.dart,
at character offset null:
type 'FunctionTypeBuilder' is not a subtype of type 'NamedTypeBuilder' of 'value'
#0      StackImpl.popList (package:_fe_analyzer_shared/src/parser/stack_listener.dart:574:13)
#1      FixedNullableList.pop (package:_fe_analyzer_shared/src/parser/stack_listener.dart:657:18)
#2      OutlineBuilder.endTypeList (package:front_end/src/fasta/source/outline_builder.dart:1369:54)
#3      Parser.parseTypeList (package:_fe_analyzer_shared/src/parser/parser_impl.dart:968:14)
#4      Parser.parseWithClauseOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1156:15)
#5      Parser.parseClassHeaderOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1833:13)
#6      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1819:13)
#7      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1784:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:579:14)
#9      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:475:14)
#10     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:335:37)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:250:13)
#13     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:292:20)
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#15     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:291:12)
#16     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:99:28)
<asynchronous suspension>
#17     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#19     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#20     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#21     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#22     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#23     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#24     new Future.sync (dart:async/future.dart:222:31)
#25     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#26     _rootRun (dart:async/zone.dart:1154:13)
#27     _CustomZone.run (dart:async/zone.dart:1057:19)
#28     _runZoned (dart:async/zone.dart:1557:10)
#29     runZoned (dart:async/zone.dart:1500:12)
#30     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#31     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#32     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#33     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#34     SingleShotCompilerWrapper.compileInternal (file:///Users/leafp/src/dart-repo/sdk/pkg/vm/bin/kernel_service.dart:400:17)
#35     Compiler.compile.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/vm/bin/kernel_service.dart:168:45)
#36     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#37     _rootRun (dart:async/zone.dart:1146:47)
#38     _CustomZone.run (dart:async/zone.dart:1057:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:961:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1001:23)
#41     _rootRun (dart:async/zone.dart:1154:13)
#42     _CustomZone.run (dart:async/zone.dart:1057:19)
#43     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:985:23)
#44     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#45     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#46     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)


#0      StackImpl.popList (package:_fe_analyzer_shared/src/parser/stack_listener.dart:574:13)
#1      FixedNullableList.pop (package:_fe_analyzer_shared/src/parser/stack_listener.dart:657:18)
#2      OutlineBuilder.endTypeList (package:front_end/src/fasta/source/outline_builder.dart:1369:54)
#3      Parser.parseTypeList (package:_fe_analyzer_shared/src/parser/parser_impl.dart:968:14)
#4      Parser.parseWithClauseOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1156:15)
#5      Parser.parseClassHeaderOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1833:13)
#6      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1819:13)
#7      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1784:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:579:14)
#9      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:475:14)
#10     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:335:37)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:250:13)
#13     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:292:20)
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#15     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:291:12)
#16     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:99:28)
<asynchronous suspension>
#17     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#19     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#20     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#21     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#22     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#23     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#24     new Future.sync (dart:async/future.dart:222:31)
#25     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#26     _rootRun (dart:async/zone.dart:1154:13)
#27     _CustomZone.run (dart:async/zone.dart:1057:19)
#28     _runZoned (dart:async/zone.dart:1557:10)
#29     runZoned (dart:async/zone.dart:1500:12)
#30     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#31     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#32     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#33     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#34     SingleShotCompilerWrapper.compileInternal (file:///Users/leafp/src/dart-repo/sdk/pkg/vm/bin/kernel_service.dart:400:17)
#35     Compiler.compile.<anonymous closure> (file:///Users/leafp/src/dart-repo/sdk/pkg/vm/bin/kernel_service.dart:168:45)
#36     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#37     _rootRun (dart:async/zone.dart:1146:47)
#38     _CustomZone.run (dart:async/zone.dart:1057:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:961:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1001:23)
#41     _rootRun (dart:async/zone.dart:1154:13)
#42     _CustomZone.run (dart:async/zone.dart:1057:19)
#43     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:985:23)
#44     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#45     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#46     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
```

**Comment by johnniwinther** [comment]
@jensjoha This seems to be a bad interplay between error recovery and that stack expectations in the outline builder.

**Comment by jensjoha** [comment]
This also crashes the analyzer btw. So /cc @stereotype441 .

As I read the spec, except for the extraneous ">" this is syntactically valid (so I'm thinking not a parser issue):
```
[...]
with <typeNotVoidList>

<typeNotVoidList> ::= <typeNotVoid> (‘,’ <typeNotVoid>)*

<typeNotVoid> ::= <functionType> ‘?’?
| <typeNotVoidNotFunction>

<functionType> ::= <functionTypeTails>
| <typeNotFunction> <functionTypeTails>

<functionTypeTails> ::= <functionTypeTail> ‘?’? <functionTypeTails>
| <functionTypeTail>

<functionTypeTail> ::= Function <typeParameters>? <parameterTypeList>

[...]
```

It's a `typeNotVoidList` with one entry; the `typeNotVoid` is a `functionType` which is a `<typeNotFunction> <functionTypeTails>`... Or am I reading it wrong?

On the front-end side it's easily fixed by replacing a few `NamedTypeBuilder` with `TypeBuilder`.

**Comment by leafpetersen** [comment]
@jensjoha I think what you are saying is that the following program is **syntactically** well-formed:
```dart
class DND1 extends Object with M<dynamic> Function() {
}
```
I agree - mixing in a function type is a static error which should be reported at some point, but it's not syntactically invalid.

The original example above though, is syntactically invalid, right?  And in any case, shouldn't crash.

**Comment by jensjoha** [comment]
> @jensjoha I think what you are saying is that the following program is **syntactically** well-formed:
> 
> ```dart
> class DND1 extends Object with M<dynamic> Function() {
> }
> ```
> 
> I agree - mixing in a function type is a static error which should be reported at some point, but it's not syntactically invalid.

Yes, if I was unclear on that, I apologize. I was merely trying to confirm that this was not a parser issue (e.g. Johnni talked about error recovery). It seems we're in agreement.

> The original example above though, is syntactically invalid, right?
Yes, there's an extraneous trailing ">".

> And in any case, shouldn't crash.

Agreed. The CFE is fixed with 9f06c32b45a8e39fc74b40e60782391c34d07a2d but the analyzer still crashes. I'll update the title an (tentatively assign @stereotype441).

**Comment by jensjoha** [comment]
For a little more context here's some test-cases and stack-traces from analyzer:

```
$ ls analyzeme/
t.dart

$ cat analyzeme/t.dart 
class A<T> {}

mixin M<T> {}

class DND1 extends Object with M<dynamic> Function() {
}


$ out/ReleaseX64/dart pkg/analysis_server/bin/server.dart --train-using analyzeme/
Analyzing with an empty driver cache:
Analyzing analyzeme/...
Unhandled exception:
type 'GenericFunctionTypeImpl' is not a subtype of type 'TypeName' of 'value'
#0      StackImpl.popList (package:_fe_analyzer_shared/src/parser/stack_listener.dart:574:13)
#1      AstBuilder.popTypedList (package:analyzer/src/fasta/ast_builder.dart:3524:11)
#2      AstBuilder.endTypeList (package:analyzer/src/fasta/ast_builder.dart:2158:10)
#3      Parser.parseTypeList (package:_fe_analyzer_shared/src/parser/parser_impl.dart:968:14)
#4      Parser.parseWithClauseOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1157:15)
#5      Parser.parseClassHeaderOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1834:13)
#6      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#7      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1785:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:579:14)
#9      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:475:14)
#10     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
#11     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:158:32)
#12     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:153:12)
#13     parseString (package:analyzer/dart/analysis/utilities.dart:126:21)
#14     _File._parse (package:analyzer/src/services/available_declarations.dart:1872:12)
#15     _File.refresh (package:analyzer/src/services/available_declarations.dart:1194:30)
#16     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:697:14)
#17     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:599:18)
#18     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:296:13)
#19     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1955:35)
<asynchronous suspension>
#20     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1898:5)
#21     new AnalysisServer (package:analysis_server/src/analysis_server.dart:153:29)
#22     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:82:22)
#23     DevAnalysisServer.initServer (package:analysis_server/src/server/dev_server.dart:34:18)
#24     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:575:17)
#25     Driver.start (package:analysis_server/src/server/driver.dart:494:7)
#26     main (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/analysis_server/bin/server.dart:10:11)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


$ vim analyzeme/t.dart

$ cat analyzeme/t.dart 
class A<T> {}

mixin M<T> {}

class DND1 implements M<dynamic> Function() {
}

$ out/ReleaseX64/dart pkg/analysis_server/bin/server.dart --train-using analyzeme/
Analyzing with an empty driver cache:
Analyzing analyzeme/...
Unhandled exception:
type 'GenericFunctionTypeImpl' is not a subtype of type 'TypeName' of 'value'
#0      StackImpl.popList (package:_fe_analyzer_shared/src/parser/stack_listener.dart:574:13)
#1      AstBuilder.popTypedList (package:analyzer/src/fasta/ast_builder.dart:3524:11)
#2      AstBuilder.handleClassOrMixinImplements (package:analyzer/src/fasta/ast_builder.dart:2436:35)
#3      Parser.parseClassOrMixinImplementsOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1969:14)
#4      Parser.parseClassHeaderOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1835:13)
#5      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#6      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1785:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:579:14)
#8      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:475:14)
#9      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
#10     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:158:32)
#11     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:153:12)
#12     parseString (package:analyzer/dart/analysis/utilities.dart:126:21)
#13     _File._parse (package:analyzer/src/services/available_declarations.dart:1872:12)
#14     _File.refresh (package:analyzer/src/services/available_declarations.dart:1194:30)
#15     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:697:14)
#16     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:599:18)
#17     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:296:13)
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1955:35)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1898:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:153:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:82:22)
#22     DevAnalysisServer.initServer (package:analysis_server/src/server/dev_server.dart:34:18)
#23     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:575:17)
#24     Driver.start (package:analysis_server/src/server/driver.dart:494:7)
#25     main (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/analysis_server/bin/server.dart:10:11)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

$ vim analyzeme/t.dart

$ cat analyzeme/t.dart 
class A<T> {}

mixin M<T> {}

class DND1 extends M<dynamic> Function() {
}

$ out/ReleaseX64/dart pkg/analysis_server/bin/server.dart --train-using analyzeme/
Analyzing with an empty driver cache:
Analyzing analyzeme/...
Unhandled exception:
type 'GenericFunctionTypeImpl' is not a subtype of type 'TypeName'
#0      AstBuilder.handleClassExtends (package:analyzer/src/fasta/ast_builder.dart:2374:14)
#1      Parser.parseClassExtendsOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1945:16)
#2      Parser.parseClassHeaderOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1833:13)
#3      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#4      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1785:14)
#5      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:579:14)
#6      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:475:14)
#7      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
#8      ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:158:32)
#9      ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:153:12)
#10     parseString (package:analyzer/dart/analysis/utilities.dart:126:21)
#11     _File._parse (package:analyzer/src/services/available_declarations.dart:1872:12)
#12     _File.refresh (package:analyzer/src/services/available_declarations.dart:1194:30)
#13     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:697:14)
#14     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:599:18)
#15     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:296:13)
#16     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1955:35)
<asynchronous suspension>
#17     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1898:5)
#18     new AnalysisServer (package:analysis_server/src/analysis_server.dart:153:29)
#19     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:82:22)
#20     DevAnalysisServer.initServer (package:analysis_server/src/server/dev_server.dart:34:18)
#21     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:575:17)
#22     Driver.start (package:analysis_server/src/server/driver.dart:494:7)
#23     main (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/analysis_server/bin/server.dart:10:11)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by jensjoha** [comment]
Well --- the first thing that Leaf reported was a bug in both fasta and analyzer. The bug in fasta was fixed and left the bugs in analyzer. Now it's a bug / bugs in analyzer.

2 of the 3 stacktraces I posted above does technically crash in "package:_fe_analyzer_shared", but only because analyzer instructs it to (by giving it a list that can contain TypeName when there's actually a GenericFunctionTypeImpl on the stack).

**Comment by srawlins** [comment]
I see, thanks @jensjoha !

**Comment by stereotype441** [comment]
Unassigning myself because I’m not actively working on this issue right now.

**Comment by srawlins** [comment]
Regarding [Jens's three test cases](https://github.com/dart-lang/sdk/issues/41265#issuecomment-614471086):

```dart
class A<T> {}

mixin M<T> {}

class DND1 extends Object with M<dynamic> Function() {
}
```

Analyzer no longer crashes and instead reports:

> error • a.dart:5:32 • Expected a mixin name. Try using a mixin name, possibly with type arguments. • expected_named_type

---

```dart
class A<T> {}

mixin M<T> {}

class DND1 implements M<dynamic> Function() {
}
```

Analyzer no longer crashes and instead reports:

> error • a.dart:5:23 • Expected the name of a class or mixin. Try using a class or mixin name, possibly with type arguments. • expected_named_type

---

```dart
class A<T> {}

mixin M<T> {}

class DND1 extends M<dynamic> Function() {
}
```

Analyzer no longer crashes and instead reports:

> error • a.dart:5:20 • Expected a class name. Try using a class name, possibly with type arguments. • expected_named_type
