### ISSUE TITLE
UnimplementedError: name is an instance of PrefixedIdentifierImpl in endClassMethod from SDK 2.7.0

### ISSUE THREAD

**Issue by sherifhasan** [dart-lang/sdk#41274]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.7.0`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.7.0, server version 1.27.4, FATAL error: UnimplementedError: name is an instance of PrefixedIdentifierImpl in endClassMethod
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file://C:\Users\sheri\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.7; please re-open if you see this in a recent version of Dart/Flutter.
