### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by Spoetnic** [dart-lang/sdk#41297]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.8.0-edge.9983424a3c50c623730fd43b4ce263df660eb455`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.3, screens 1792x1120, 1920x1200  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.9983424a3c50c623730fd43b4ce263df660eb455, server version 1.27.4, error: The formatter produced unexpected output. Input was:
import 'package:bitcoin_ticker/services/networking.dart';

const List<String> currenciesList = [
  'AUD',
  'BRL',
  'CAD',
  'CNY',
  'EUR',
  'GBP',
  'HKD',
  'IDR',
  'ILS',
  'INR',
  'JPY',
  'MXN',
  'NOK',
  'NZD',
  'PLN',
  'RON',
  'RUB',
  'SEK',
  'SGD',
  'USD',
  'ZAR'
];

const List<String> cryptoList = [
  'BTC',
  'ETH',
  'LTC',
];

const String coinApiKey = '';

class CoinData {
  Future<double> getCurrencyValueForCrypto(
    String currency,
    String crypto,
  ) async {
    String url =
        'https://rest.coinapi.io/v1/exchangerate/$crypto/$currency?apikey=$coinApiKey';
    var coinData = await httpGetJson(url);

    double rate = coinData?['rate'];
    return rate;
//    return Random().nextDouble() * 100;
  }
}

Which formatted to:
import 'package:bitcoin_ticker/services/networking.dart';

const List<String> currenciesList = [
  'AUD',
  'BRL',
  'CAD',
  'CNY',
  'EUR',
  'GBP',
  'HKD',
  'IDR',
  'ILS',
  'INR',
  'JPY',
  'MXN',
  'NOK',
  'NZD',
  'PLN',
  'RON',
  'RUB',
  'SEK',
  'SGD',
  'USD',
  'ZAR'
];

const List<String> cryptoList = [
  'BTC',
  'ETH',
  'LTC',
];

const String coinApiKey = '';

class CoinData {
  Future<double> getCurrencyValueForCrypto(
    String currency,
    String crypto,
  ) async {
    String url =
        'https://rest.coinapi.io/v1/exchangerate/$crypto/$currency?apikey=$coinApiKey';
    var coinData = await httpGetJson(url);

    double rate = coinData['rate'];
    return rate;
//    return Random().nextDouble() * 100;
  }
}

#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:158:7)
#1      EditDomainHandler.format (package:analysis_server/src/edit/edit_domain.dart:146:35)
#2      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:364:16)
#3      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:316:45)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#5      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:312:50)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1502:12)
#10     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:311:5)
#11     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#13     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#14     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#22     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#23     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#24     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#25     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#27     _rootRunUnary (dart:async/zone.dart:1134:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#35     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#36     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#37     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#38     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#40     _rootRunUnary (dart:async/zone.dart:1134:38)
#41     _CustomZone.runUnary (dart:asyn...
```

**Comment by srawlins** [comment]
Apologies that we did not get a chance to look at this crash. Please re-open if you see this again with a recent version of Dart.
