### ISSUE TITLE
vm/dart/use_bare_instructions_flag_test broke (Pass -> RuntimeError, expected Pass)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#41315]
With the NNBD unfork CL at https://dart-review.googlesource.com/c/sdk/+/138902 we see an error in vm/dart/use_bare_instructions_flag_test on vm-kernel-precomp-win-release-x64-try configuration

The error is as follows:

```
--- Command "vm_compile_to_kernel []" (took 04.000265s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & C:\b\s\w\ir\pkg\vm\tool\gen_kernel.bat --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o C:\b\s\w\ir\out\ReleaseX64\generated_compilations\dartkp\runtime_tests_vm_dart_use_bare_instructions_flag_test\out.dill C:\b\s\w\ir\runtime\tests\vm\dart\use_bare_instructions_flag_test.dart --packages=C:\b\s\w\ir\.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "precompiler" (took 05.000734s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & out\ReleaseX64\gen_snapshot --snapshot-kind=app-aot-elf --elf=C:/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp/runtime_tests_vm_dart_use_bare_instructions_flag_test/out.aotsnapshot --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\out\ReleaseX64\generated_compilations\dartkp\runtime_tests_vm_dart_use_bare_instructions_flag_test\out.dill

exit code:
0

--- Command "remove_kernel_file" (took 78ms):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & cmd.exe /c del C:\b\s\w\ir\out\ReleaseX64\generated_compilations\dartkp\runtime_tests_vm_dart_use_bare_instructions_flag_test\out.dill

exit code:
0

--- Command "vm" (took 39.000475s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & out\ReleaseX64\dart_precompiled_runtime.exe --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp/runtime_tests_vm_dart_use_bare_instructions_flag_test/out.aotsnapshot

exit code:
255

stdout:
Running .\pkg\vm\tool\gen_kernel.bat --aot --platform=out\ReleaseX64\vm_platform_strong.dill -o C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\kernel_dump.dill .\pkg/kernel/bin/dump.dart
Running out\ReleaseX64\gen_snapshot.exe --use-bare-instructions --snapshot-kind=app-aot-elf --elf=C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\bare.snapshot C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\kernel_dump.dill
Running out\ReleaseX64\gen_snapshot.exe --no-use-bare-instructions --snapshot-kind=app-aot-elf --elf=C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\non_bare.snapshot C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\kernel_dump.dill
Running out\ReleaseX64\dart_precompiled_runtime.exe --use-bare-instructions C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\bare.snapshot C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\kernel_dump.dill C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\bare-out1.txt
Running out\ReleaseX64\dart_precompiled_runtime.exe --no-use-bare-instructions C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\bare.snapshot C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\kernel_dump.dill C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\bare-out2.txt
Running out\ReleaseX64\dart_precompiled_runtime.exe --use-bare-instructions C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\non_bare.snapshot C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\kernel_dump.dill C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\non-bare-out1.txt
Running out\ReleaseX64\dart_precompiled_runtime.exe --no-use-bare-instructions C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\non_bare.snapshot C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\kernel_dump.dill C:\b\s\w\itc5h4xk\bare-flag-test735c7918-7499-11ea-b789-b2e7f30a0231\non-bare-out2.txt
Subcommand stderr:
c:\b\s\w\ir\cache\builder\sdk\runtime\vm\runtime_entry.cc: 1020: error: unreachable code

version=2.8.0-edge.6e53ac6e4c7b3d94de5ee0370a538b03dafded1c (be) (Thu Apr 2 01:39:10 2020 +0000) on "windows_x64"

pid=7524, thread=6876, isolate=main(00000125337DC2D0)

isolate_instructions=125350c7000, vm_instructions=125350c2000

  pc 0x00007ff66ae3006c fp 0x00000005e31fece0 Dart_CurrentIsolate+0x93bbc

-- End of DumpStackTrace

[exit     : sp(0) fp(0x5e31fee80) pc(0)]

[stub     : sp(0x5e31fee90) fp(0x5e31feeb0) pc(0x125350c55f2)]

[dart     : sp(0x5e31feec0) fp(0x5e31feee0) pc(0x12535116fca) *dart:core__Uri@0150898_init_hashCode ]

[dart     : sp(0x5e31feef0) fp(0x5e31fef10) pc(0x125351c6ee6) *dart:core__Uri@0150898_get_hashCode ]

[dart     : sp(0x5e31fef20) fp(0x5e31fef38) pc(0x125350ef7e3) *dart:collection___InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin&_HashBase&_OperatorEqualsAndHashCode@3220832__hashCode@3220832 ]

[dart     : sp(0x5e31fef48) fp(0x5e31fef78) pc(0x125350eeef2) *dart:collection___InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin@3220832_[]= ]

[dart     : sp(0x5e31fef88) fp(0x5e31ff008) pc(0x12535230089) *package:kernel/binary/ast_from_binary.dart_BinaryBuilder_readUriToSource ]

[dart     : sp(0x5e31ff018) fp(0x5e31ff060) pc(0x1253523383f) *package:kernel/binary/ast_from_binary.dart_BinaryBuilder__readOneComponent@20015961 ]

[dart     : sp(0x5e31ff070) fp(0x5e31ff0d8) pc(0x1253523430a) *package:kernel/binary/ast_from_binary.dart_BinaryBuilder_readComponent_<anonymous closure> ]

[dart     : sp(0x5e31ff0e8) fp(0x5e31ff188) pc(0x125351582b4) *dart:developer_Timeline_timeSync ]

[dart     : sp(0x5e31ff198) fp(0x5e31ff1d8) pc(0x12535206e2c) *package:kernel/binary/ast_from_binary.dart_BinaryBuilder_readComponent ]

[dart     : sp(0x5e31ff1e8) fp(0x5e31ff218) pc(0x12535206cfa) *package:kernel/kernel.dart_::_loadComponentFromBytes ]

[dart     : sp(0x5e31ff228) fp(0x5e31ff258) pc(0x125351d982f) *package:kernel/kernel.dart_::_loadComponentFromBinary ]

[dart     : sp(0x5e31ff268) fp(0x5e31ff2b0) pc(0x125351d96eb) *package:kernel/src/tool/command_line_util.dart_CommandLineHelper_tryLoadDill ]

[dart     : sp(0x5e31ff2c0) fp(0x5e31ff2e0) pc(0x1253526620d) *file:///C:/b/s/w/ir/pkg/kernel/bin/dump.dart_::_main ]

[dart     : sp(0x5e31ff2f0) fp(0x5e31ff308) pc(0x12535266512) *file:///C:/b/s/w/ir/pkg/kernel/bin/dump.dart_::_main_main ]

[dart     : sp(0x5e31ff318) fp(0x5e31ff338) pc(0x1253526e5ea) *dart:core__Closure@0150898_call ]

[dart     : sp(0x5e31ff348) fp(0x5e31ff378) pc(0x1253513c533) *dart:isolate_::__startIsolate@1026248_<anonymous closure> ]

[dart     : sp(0x5e31ff388) fp(0x5e31ff3a8) pc(0x1253526e5ea) *dart:core__Closure@0150898_call ]

[dart     : sp(0x5e31ff3b8) fp(0x5e31ff3d8) pc(0x12535137ac1) *dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]

[entry    : sp(0x5e31ff3e8) fp(0x5e31ff4f8) pc(0x125350c54e5)]


Subcommand stderr:
c:\b\s\w\ir\cache\builder\sdk\runtime\vm\runtime_entry.cc: 1020: error: unreachable code

version=2.8.0-edge.6e53ac6e4c7b3d94de5ee0370a538b03dafded1c (be) (Thu Apr 2 01:39:10 2020 +0000) on "windows_x64"

pid=6276, thread=5740, isolate=main(0000022720A8B360)

isolate_instructions=2271fbf7000, vm_instructions=2271fbf2000

  pc 0x00007ff66ae3006c fp 0x00000038fa3feb00 Dart_CurrentIsolate+0x93bbc

-- End of DumpStackTrace

[exit     : sp(0) fp(0x38fa3feca0) pc(0)]

[stub     : sp(0x38fa3fecb0) fp(0x38fa3fecd0) pc(0x2271fbf55f2)]

[dart     : sp(0x38fa3fece0) fp(0x38fa3fed00) pc(0x2271fc46fca) *dart:core__Uri@0150898_init_hashCode ]

[dart     : sp(0x38fa3fed10) fp(0x38fa3fed30) pc(0x2271fcf6ee6) *dart:core__Uri@0150898_get_hashCode ]

[dart     : sp(0x38fa3fed40) fp(0x38fa3fed58) pc(0x2271fc1f7e3) *dart:collection___InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin&_HashBase&_OperatorEqualsAndHashCode@3220832__hashCode@3220832 ]

[dart     : sp(0x38fa3fed68) fp(0x38fa3fed98) pc(0x2271fc1eef2) *dart:collection___InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin@3220832_[]= ]

[dart     : sp(0x38fa3feda8) fp(0x38fa3fee28) pc(0x2271fd60089) *package:kernel/binary/ast_from_binary.dart_BinaryBuilder_readUriToSource ]

[dart     : sp(0x38fa3fee38) fp(0x38fa3fee80) pc(0x2271fd6383f) *package:kernel/binary/ast_from_binary.dart_BinaryBuilder__readOneComponent@20015961 ]

[dart     : sp(0x38fa3fee90) fp(0x38fa3feef8) pc(0x2271fd6430a) *package:kernel/binary/ast_from_binary.dart_BinaryBuilder_readComponent_<anonymous closure> ]

[dart     : sp(0x38fa3fef08) fp(0x38fa3fefa8) pc(0x2271fc882b4) *dart:developer_Timeline_timeSync ]

[dart     : sp(0x38fa3fefb8) fp(0x38fa3feff8) pc(0x2271fd36e2c) *package:kernel/binary/ast_from_binary.dart_BinaryBuilder_readComponent ]

[dart     : sp(0x38fa3ff008) fp(0x38fa3ff038) pc(0x2271fd36cfa) *package:kernel/kernel.dart_::_loadComponentFromBytes ]

[dart     : sp(0x38fa3ff048) fp(0x38fa3ff078) pc(0x2271fd0982f) *package:kernel/kernel.dart_::_loadComponentFromBinary ]

[dart     : sp(0x38fa3ff088) fp(0x38fa3ff0d0) pc(0x2271fd096eb) *package:kernel/src/tool/command_line_util.dart_CommandLineHelper_tryLoadDill ]

[dart     : sp(0x38fa3ff0e0) fp(0x38fa3ff100) pc(0x2271fd9620d) *file:///C:/b/s/w/ir/pkg/kernel/bin/dump.dart_::_main ]

[dart     : sp(0x38fa3ff110) fp(0x38fa3ff128) pc(0x2271fd96512) *file:///C:/b/s/w/ir/pkg/kernel/bin/dump.dart_::_main_main ]

[dart     : sp(0x38fa3ff138) fp(0x38fa3ff158) pc(0x2271fd9e5ea) *dart:core__Closure@0150898_call ]

[dart     : sp(0x38fa3ff168) fp(0x38fa3ff198) pc(0x2271fc6c533) *dart:isolate_::__startIsolate@1026248_<anonymous closure> ]

[dart     : sp(0x38fa3ff1a8) fp(0x38fa3ff1c8) pc(0x2271fd9e5ea) *dart:core__Closure@0150898_call ]

[dart     : sp(0x38fa3ff1d8) fp(0x38fa3ff1f8) pc(0x2271fc67ac1) *dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]

[entry    : sp(0x38fa3ff208) fp(0x38fa3ff318) pc(0x2271fbf54e5)]

stderr:
Unhandled exception:
Command failed with unexpected exit code (was 1073741845)
#0      run (file:///C:/b/s/w/ir/runtime/tests/vm/dart/use_flag_test_helper.dart:142)
<asynchronous suspension>
#1      main.<anonymous closure> (file:///C:/b/s/w/ir/runtime/tests/vm/dart/use_bare_instructions_flag_test.dart:85)
#2      _RootZone.runUnary (dart:async/zone.dart:1450)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:143)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686)
#5      Future._propagateToListeners (dart:async/future_impl.dart:715)
#6      Future._completeWithValue (dart:async/future_impl.dart:526)
#7      Future.wait.<anonymous closure> (dart:async/future.dart:412)
#8      _RootZone.runUnary (dart:async/zone.dart:1450)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686)
#11     Future._propagateToListeners (dart:async/future_impl.dart:715)
#12     Future._completeWithValue (dart:async/future_impl.dart:526)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:306)
#15     run (file:///C:/b/s/w/ir/runtime/tests/vm/dart/use_flag_test_helper.dart:0)
#16     _RootZone.runUnary (dart:async/zone.dart:1450)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686)
#19     Future._propagateToListeners (dart:async/future_impl.dart:715)
#20     Future._completeWithValue (dart:async/future_impl.dart:526)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:306)
#23     runHelper (file:///C:/b/s/w/ir/runtime/tests/vm/dart/use_flag_test_helper.dart:0)
#24     _RootZone.runUnary (dart:async/zone.dart:1450)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:143)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686)
#27     Future._propagateToListeners (dart:async/future_impl.dart:715)
#28     Future._completeWithValue (dart:async/future_impl.dart:526)
#29     Future.wait.<anonymous closure> (dart:async/future.dart:412)
#30     _RootZone.runUnary (dart:async/zone.dart:1450)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:143)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686)
#33     Future._propagateToListeners (dart:async/future_impl.dart:715)
#34     Future._completeWithValue (dart:async/future_impl.dart:526)
#35     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:557)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:117)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168)

--- Re-run this test:
python tools/test.py -n dartkp-win-release-x64 vm/dart/use_bare_instructions_flag_test


```

**Comment by alexmarkov** [comment]
Unfork CL landed, but the test `vm/dart/use_bare_instructions_flag_test` is currently passing on `vm-kernel-precomp-win-release-x64` configuration:

`{"name":"vm/dart/use_bare_instructions_flag_test","configuration":"dartkp-win-release-x64","suite":"vm","test_name":"dart/use_bare_instructions_flag_test","time_ms":56703,"result":"Pass","expected":"Pass","matches":true,"bot_name":"dart-tests-win10-2-o0ti","commit_hash":"fcf56eafff012b2a62377ac7f7ea585d1eb8933c","commit_time":1588955424,"build_number":"8985","builder_name":"vm-kernel-precomp-win-release-x64","flaky":false,"previous_flaky":false,"previous_commit_hash":"dd2d040ccb2608e4e320cdb8bdd7a410afb5ade6","previous_commit_time":1588953189,"previous_build_number":"8984","previous_result":"Pass","changed":false}`
