### ISSUE TITLE
Encountered a Dart Analysis Server error on Flutter with Android Studio

### ISSUE THREAD

**Issue by Thamizhan** [dart-lang/sdk#41322]
Analyzer Feedback from IntelliJ

Today I got this issue suddenly at the evening. I was using working on my project since morning but suddenly it popups when I opened an Android native project then reopening my Flutter project.

I tried restarting Android Studio, even tried restarting my computer. But still getting this issue. 

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.8.0-edge.9983424a3c50c623730fd43b4ce263df660eb455`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.9983424a3c50c623730fd43b4ce263df660eb455, server version 1.27.4, error: FormatException: The resolved 'packageUri' must be inside the rootUri, actualy 'file:///' is not in 'file:///Users/thamizhan/Sources/Flutter/beefhouse/gen/packages/_fe_analyzer_shared/', for the package '_fe_analyzer_shared'.
{"configVersion":2,"packages":[{"name":"_fe_analyzer_shared","rootUri":"../...
#0      _PackageConfigJsonParser._parsePackage (package:analyzer/src/context/package_config_json.dart:199:9)
#1      _PackageConfigJsonParser._parsePackages (package:analyzer/src/context/package_config_json.dart:243:9)
#2      _PackageConfigJsonParser.parse (package:analyzer/src/context/package_config_json.dart:116:7)
#3      parsePackageConfigJson (package:analyzer/src/context/package_config_json.dart:13:49)
#4      parsePackageConfigJsonFile (package:analyzer/src/context/packages.dart:72:20)
#5      parsePackagesFile (package:analyzer/src/context/packages.dart:127:14)
#6      ContextManagerImpl._computeFolderDisposition (package:analysis_server/src/context_manager.dart:951:29)
#7      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:992:9)
#8      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1084:16)
#9      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1092:13)
#10     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:646:9)
#11     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:478:22)
#12     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:363:14)
#13     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:301:16)
#14     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:316:45)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#16     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:312:50)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1502:12)
#21     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:311:5)
#22     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#26     _rootRunUnary (dart:async/zone.dart:1134:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#37     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#38     _rootRunUnary (dart:async/zone.dart:1134:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#46     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#47     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#48     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#49     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#50     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#51     _rootRunUnary (dart:async/zone.dart:1134:38)
#52     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_imp...
```

For additional log information, please append the contents of
file:///private/var/folders/2d/7d4sf0v12v74zby6cnr2pzgc0000gn/T/report.txt.

**Comment by Thamizhan** [comment]
Cleaned project with `flutter clean` and deleted gen folder to regenerate, its working fine now.
