### ISSUE TITLE
Unhandled exception even if I handled all errors with try catch

### ISSUE THREAD

**Issue by a188037445** [dart-lang/sdk#41366]
Dart SDK version: 2.7.2
OS: Linux

code:
```dart
import 'dart:async';

import 'package:http/http.dart';

Future<void> main(List<String> args) async {
  final client = Client();
  try {
    final f1 = client.send(Request('GET', Uri.parse('abc')));
    final f2 = client.send(Request('GET', Uri.parse('abc')));
    final resp1 = await f1;
    print(resp1.contentLength);
    final resp2 = await f2;
    print(resp2.contentLength);
    client.close();
  } catch (e) {
    print('caught error');
  }
  print('finish');
}
```
output:
```dart
caught error
finish
Unhandled exception:
Invalid argument(s): No host specified in URI abc
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2276:9)
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2192:7)
#2      IOClient.send (package:http/src/io_client.dart:33:37)
#3      main (file:///home/test/code/dart/test/bin/main.dart:9:23)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#5      main (file:///home/test/code/dart/test/bin/main.dart:5:18)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Process finished with exit code 255
```

**Comment by vsmenon** [comment]
@lrhn 

Not sure what is going on here.  It could be un-awaited operation inside `openUrl`?

**Comment by lrhn** [comment]
The problem is that you are creating two futures, but only wait for one of them.
```dart
  try {
    final f1 = client.send(Request('GET', Uri.parse('abc')));
    final f2 = client.send(Request('GET', Uri.parse('abc')));
    final resp1 = await f1;
    ...
  } catch (e) {
    print('caught error');
  }
```
If awaiting `f1` throws (because the `f1` future completes with an error), then you never get to awaiting `f2`. That means that when the `f2` future completes with an error, that becomes an *unhandled* async error. It gets reported to the current zone. The default behavior is printing the error and crashing the program. That's the error you see reported, and the non-zero error code representing an uncaught async error.

If you have two live futures at the same time, you may want to handle them in parallel:
```dart
  try {
    final f1 = client.send(Request('GET', Uri.parse('abc')));
    final f2 = client.send(Request('GET', Uri.parse('abc')));
    final resps = await Future.wait([f1, f2]);
    ...
  } catch (e) {
    print('caught error');
  }
```
Another alternative is to handle, and *temporarily* ignore, an error on `f2`.
```dart
  final f2  =client.send(Request('GET", Uri.pase('abc')))..catchError((e) {});
```
This means that an error on `f2` is not *unhandled*. It will still get rethrown when you get to `await f2` below.
