### ISSUE TITLE
Migration: pressing "apply migration" produces a 500 error due to a null exception in PreviewSite.performApply

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41391]
When attempting to migrate package csslib using the migration tool, if I click on the preview tool's "Apply Migration" button, I get a dialog box saying `Could not apply migration (Instance of 'minified:ew').`  Digging through Chrome developer tools, I see that the server request produced a 500 error with the following stacktrace:
```
NoSuchMethodError: The method 'hadOriginalContent' was called on null.
Receiver: null
Tried calling: hadOriginalContent("include: package:pedantic/analysis_options.yaml\n\nlinter:\n  rules:\n  - prefer_equal_for_default_values\n  - prefer_generic_function_type_aliases\n  - prefer_typing_uninitialized_variables\n  - slash_for_doc_comments\n  - unnecessary_const\n  - unnecessary_new\n")
#0      Object.noSuchMethod (dart:core-patch&#47;object_patch.dart:51:5)
#1      PreviewSite.performApply (package:analysis_server&#47;src&#47;edit&#47;preview&#47;preview_site.dart:204:35)
#2      PreviewSite.handlePostRequest (package:analysis_server&#47;src&#47;edit&#47;preview&#47;preview_site.dart:172:9)
#3      HttpPreviewServer._handlePostRequest (package:analysis_server&#47;src&#47;edit&#47;preview&#47;http_preview_server.dart:94:23)
#4      HttpPreviewServer._handleServer.&lt;anonymous closure&gt; (package:analysis_server&#47;src&#47;edit&#47;preview&#47;http_preview_server.dart:104:15)
#5      _rootRunUnary (dart:async&#47;zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async&#47;zone.dart:1100:19)
#7      _CustomZone.runUnaryGuarded (dart:async&#47;zone.dart:1005:7)
#8      _BufferingStreamSubscription._sendData (dart:async&#47;stream_impl.dart:350:11)
#9      _BufferingStreamSubscription._add (dart:async&#47;stream_impl.dart:280:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async&#47;stream_controller.dart:783:19)
#11     _StreamController._add (dart:async&#47;stream_controller.dart:654:7)
#12     _StreamController.add (dart:async&#47;stream_controller.dart:596:5)
#13     _HttpServer._handleRequest (dart:_http&#47;http_impl.dart:2870:19)
#14     new _HttpConnection.&lt;anonymous closure&gt; (dart:_http&#47;http_impl.dart:2625:19)
#15     _rootRunUnary (dart:async&#47;zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async&#47;zone.dart:1100:19)
#17     _CustomZone.runUnaryGuarded (dart:async&#47;zone.dart:1005:7)
#18     _BufferingStreamSubscription._sendData (dart:async&#47;stream_impl.dart:350:11)
#19     _BufferingStreamSubscription._add (dart:async&#47;stream_impl.dart:280:7)
#20     _SyncStreamControllerDispatch._sendData (dart:async&#47;stream_controller.dart:783:19)
#21     _StreamController._add (dart:async&#47;stream_controller.dart:654:7)
#22     _StreamController.add (dart:async&#47;stream_controller.dart:596:5)
#23     _HttpParser._headersEnd (dart:_http&#47;http_parser.dart:393:19)
#24     _HttpParser._doParse (dart:_http&#47;http_parser.dart:739:15)
#25     _HttpParser._parse (dart:_http&#47;http_parser.dart:323:7)
#26     _HttpParser._onData (dart:_http&#47;http_parser.dart:852:5)
#27     _rootRunUnary (dart:async&#47;zone.dart:1198:47)
#28     _CustomZone.runUnary (dart:async&#47;zone.dart:1100:19)
#29     _CustomZone.runUnaryGuarded (dart:async&#47;zone.dart:1005:7)
#30     _BufferingStreamSubscription._sendData (dart:async&#47;stream_impl.dart:350:11)
#31     _BufferingStreamSubscription._add (dart:async&#47;stream_impl.dart:280:7)
#32     _SyncStreamControllerDispatch._sendData (dart:async&#47;stream_controller.dart:783:19)
#33     _StreamController._add (dart:async&#47;stream_controller.dart:654:7)
#34     _StreamController.add (dart:async&#47;stream_controller.dart:596:5)
#35     _Socket._onData (dart:io-patch&#47;socket_patch.dart:2015:41)
#36     _rootRunUnary (dart:async&#47;zone.dart:1206:13)
#37     _CustomZone.runUnary (dart:async&#47;zone.dart:1100:19)
#38     _CustomZone.runUnaryGuarded (dart:async&#47;zone.dart:1005:7)
#39     _BufferingStreamSubscription._sendData (dart:async&#47;stream_impl.dart:350:11)
#40     _BufferingStreamSubscription._add (dart:async&#47;stream_impl.dart:280:7)
#41     _SyncStreamControllerDispatch._sendData (dart:async&#47;stream_controller.dart:783:19)
#42     _StreamController._add (dart:async&#47;stream_controller.dart:654:7)
#43     _StreamController.add (dart:async&#47;stream_controller.dart:596:5)
#44     new _RawSocket.&lt;anonymous closure&gt; (dart:io-patch&#47;socket_patch.dart:1551:33)
#45     _NativeSocket.issueReadEvent.issue (dart:io-patch&#47;socket_patch.dart:1038:14)
#46     _microtaskLoop (dart:async&#47;schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async&#47;schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate-patch&#47;isolate_patch.dart:117:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch&#47;isolate_patch.dart:168:5)
```
The server appears to be dead after this point.

**Comment by stereotype441** [comment]
Reproduced with the migration tool as of d8fcc657ee5487f8d9463caa637418f6f581416b

**Comment by MichaelRFairhurst** [comment]
This happens when th emigration tool edits non-dart files.

Temporary fix is to remove the sanity checks for non-dart files, longer term fix is to track non-dart files the same way so that we can sanity check them the same.

I'm not too worried about competing edits to the pubspec, analysis_options, and if they do get corrupted, it's a single easy to fix file. Temporary version should do us just fine for the near to mid term future
