### ISSUE TITLE
Unhandled Exception: Range Error

### ISSUE THREAD

**Issue by cmkweber** [dart-lang/sdk#41414]
While stepping through debugger, this crash occurred. Unfortunately the stack trace is all I have as I don't have a reproducible.

Dart version 2.8.0 (build 2.8.0-dev.20.0 275a76f2fc)
Windows debugging on Android device

```
Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[]  (dart:core-patch/growable_array.dart:146:60)
#1      TypeBuilderComputer.visitFunctionType  (package:front_end/src/fasta/kernel/type_builder_computer.dart:118:46)
#2      FunctionType.accept  (package:kernel/ast.dart:7015:42)
#3      TypeBuilderComputer.visitInterfaceType  (package:front_end/src/fasta/kernel/type_builder_computer.dart:88:43)

#4      InterfaceType.accept  (package:kernel/ast.dart:6907:42)
#5      DillLoader.computeTypeBuilder  (package:front_end/src/fasta/dill/dill_loader.dart:117:17)
#6      computeTypeBuilder  (package:front_end/src/fasta/dill/dill_class_builder.dart:164:24)
#7      DillClassBuilder.supertypeBuilder  (package:front_end/src/fasta/dill/dill_class_builder.dart:66:23)
#8      ClassHierarchyNodeBuilder.build  (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:1470:57)
#9      ClassHierarchyBuilder.getNodeFromClassBuilder  (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:437:10)

#10     ClassHierarchyBuilder.getNodeFromClass  (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:447:9)
#11     ClassHierarchyBuilder.getCombinedMemberSignatureKernel  (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:585:9)
#12     TypeInferrerImpl._getInterfaceMember  (package:front_end/src/fasta/type_inference/type_inferrer.dart:3544:45)
#13     TypeInferrerImpl.findInterfaceMember  (package:front_end/src/fasta/type_inference/type_inferrer.dart:1045:9)
#14     InferenceVisitor._computePropertyGet  (package:front_end/src/fasta/kernel/inference_visitor.dart:3862:18)
#15     InferenceVisitor.visitPropertyGet  (package:front_end/src/fasta/kernel/inference_visitor.dart:4853:44)

#16     PropertyGet.accept1  (package:kernel/ast.dart:3094:9)
#17     TypeInferrerImpl.inferExpression  (package:front_end/src/fasta/type_inference/type_inferrer.dart:1997:27)
#18     InferenceVisitor.visitReturnStatement  (package:front_end/src/fasta/kernel/inference_visitor.dart:4900:61)
#19     ReturnStatement.accept  (package:kernel/ast.dart:6029:43)

#20     TypeInferrerImpl.inferStatement  (package:front_end/src/fasta/type_inference/type_inferrer.dart:3389:24)
#21     TypeInferrerImpl.inferFunctionBody  (package:front_end/src/fasta/type_inference/type_inferrer.dart:2038:39)
#22     BodyBuilder.parseSingleExpression  (package:front_end/src/fasta/kernel/body_builder.dart:1332:49)
#23     SourceLoader.buildExpression  (package:front_end/src/fasta/source/source_loader.dart:404:21)
<asynchronous suspension>

#24     IncrementalCompiler.compileExpression.<anonymous closure>  (package:front_end/src/fasta/incremental_compiler.dart:1646:61)
#25     CompilerContext.runInContext.<anonymous closure>.<anonymous closure>  (package:front_end/src/fasta/compiler_context.dart:123:46)
#26     new Future.sync  (dart:async/future.dart:224:31)
#27     CompilerContext.runInContext.<anonymous closure>  (package:front_end/src/fasta/compiler_context.dart:123:19)
#28     _rootRun  (dart:async/zone.dart:1184:13)
#29     _CustomZone.run  (dart:async/zone.dart:1077:19)
#30     _runZoned  (dart:async/zone.dart:1619:10)

#31     runZoned  (dart:async/zone.dart:1539:10)
#32     CompilerContext.runInContext  (package:front_end/src/fasta/compiler_context.dart:122:12)
#33     IncrementalCompiler.compileExpression  (package:front_end/src/fasta/incremental_compiler.dart:1570:26)
#34     IncrementalCompiler.compileExpression  (package:vm/incremental_compiler.dart:196:23)

#35     FrontendCompiler.compileExpression  (package:frontend_server/frontend_server.dart:887:44)
#36     _FlutterFrontendCompiler.compileExpression  (package:flutter_frontend_server/server.dart:71:22)
#37     listenAndCompile.<anonymous closure>  (package:frontend_server/frontend_server.dart:1257:20)
#38     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1374:10)
#39     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)

#40     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:266:7)
#41     _SinkTransformerStreamSubscription._add  (dart:async/stream_transformers.dart:70:11)
#42     _EventSinkWrapper.add  (dart:async/stream_transformers.dart:17:11)
#43     _StringAdapterSink.add  (dart:convert/string_conversion.dart:238:11)
#44     _LineSplitterSink._addLines  (dart:convert/line_splitter.dart:152:13)

#45     _LineSplitterSink.addSlice  (dart:convert/line_splitter.dart:127:5)
#46     StringConversionSinkMixin.add  (dart:convert/string_conversion.dart:165:5)
#47     _SinkTransformerStreamSubscription._handleData  (dart:async/stream_transformers.dart:122:24)
#48     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1374:10)
#49     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)

#50     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:266:7)
#51     _SinkTransformerStreamSubscription._add  (dart:async/stream_transformers.dart:70:11)
#52     _EventSinkWrapper.add  (dart:async/stream_transformers.dart:17:11)
#53     _StringAdapterSink.add  (dart:convert/string_conversion.dart:238:11)
#54     _StringAdapterSink.addSlice  (dart:convert/string_conversion.dart:243:7)
#55     _Utf8ConversionSink.addSlice  (dart:convert/string_conversion.dart:314:20)

#56     _Utf8ConversionSink.add  (dart:convert/string_conversion.dart:307:5)
#57     _ConverterStreamEventSink.add  (dart:convert/chunked_conversion.dart:74:18)
#58     _SinkTransformerStreamSubscription._handleData  (dart:async/stream_transformers.dart:122:24)
#59     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1374:10)

#60     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)
#61     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:266:7)
#62     _SyncStreamControllerDispatch._sendData  (dart:async/stream_controller.dart:779:19)
#63     _StreamController._add  (dart:async/stream_controller.dart:655:7)
#64     _StreamController.add  (dart:async/stream_controller.dart:597:5)

#65     _Socket._onData  (dart:io-patch/socket_patch.dart:1982:41)
#66     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1374:10)
#67     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)
#68     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:266:7)
#69     _SyncStreamControllerDispatch._sendData  (dart:async/stream_controller.dart:779:19)
#70     _StreamController._add  (dart:async/stream_controller.dart:655:7)

#71     _StreamController.add  (dart:async/stream_controller.dart:597:5)
#72     new _RawSocket.<anonymous closure>  (dart:io-patch/socket_patch.dart:1527:33)
#73     _NativeSocket.issueReadEvent.issue  (dart:io-patch/socket_patch.dart:1019:14)
#74     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
#75     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
#76     _runPendingImmediateCallback  (dart:isolate-patch/isolate_patch.dart:118:13)

#77     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:169:5)
the Dart compiler exited unexpectedly.

Exited (1)

**Comment by cmkweber** [comment]
I was able to obtain a reproducible. It looks like the range error occurs when using:

[StreamController addError](https://api.dart.dev/stable/2.7.2/dart-async/StreamController/addError.html)

It's possible the crash is during Crashlytics error handler, but I was able to reproduce this while paused and stepping through the debugger.

```
import 'dart:async';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/material.dart';

Stream<int> countdown() async*
{
  for(int i = 3; i >= 1; i--) { yield i; await Future.delayed(Duration(seconds: 1)); }
  yield null;
}

class TestStream
{
  StreamController<int> _controller;
  Stream<int> stream;
  StreamSubscription<int> _subscription;

  TestStream()
  {
    _controller = StreamController<int>(onListen: _onListen, onCancel: _onCancel);
    stream = _controller.stream;
  }

  void _onListen() { _subscription = countdown().listen(_onData, onError: _onError); }
  void _onCancel() { _subscription.cancel(); }
  void _onData(int value) { value == null ? _controller.addError(Error()) : _controller.add(value); }
  void _onError(Object error) { _controller.addError(error, StackTrace.current); }
}

void main()
{
  FlutterError.onError = Crashlytics.instance.recordFlutterError;

  runZonedGuarded<Future<void>>(() async
  {
    runApp(
      MaterialApp(
        home: Container(
          alignment: Alignment.center,
          decoration: BoxDecoration(color: Color.fromRGBO(0, 0, 255, 1.0)),
          child: FlatButton(
            color: Colors.white,
            onPressed: () { TestStream().stream.listen((int value) { debugPrint(value.toString()); }); },
            child: Text('crash')
          )
        ),
        title: 'App'
      )
    );
  }, Crashlytics.instance.recordError);
}
