### ISSUE TITLE
Fluttter run: Crash when compiling

### ISSUE THREAD

**Issue by walkerwg** [dart-lang/sdk#41438]
I
Unhandled exception:
Crash when compiling package:flutter/material.dart,
at character offset null:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<DartType>(Instance of '_DemotionNonNullification')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      demoteTypeInLibrary (package:front_end/src/fasta/type_inference/type_demotion.dart:65:14)
#2      TypeInferrerImpl.inferDeclarationType
(package:front_end/src/fasta/type_inference/type_inferrer.dart:1889:14)
#3      InferenceVisitor.visitVariableDeclaration
(package:front_end/src/fasta/kernel/inference_visitor.dart:5296:31)
#4      VariableDeclaration.accept (package:kernel/ast.dart:5436:43)
#5      TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3245:24)
#6      InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:299:20)
#7      InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:320:30)
#8      Block.accept (package:kernel/ast.dart:4663:43)
#9      TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3245:24)
#10     TypeInferrerImpl.inferLocalFunction
(package:front_end/src/fasta/type_inference/type_inferrer.dart:2595:43)
#11     InferenceVisitor.visitFunctionNode (package:front_end/src/fasta/kernel/inference_visitor.dart:1037:21)
#12     InferenceVisitor.visitFunctionExpression
(package:front_end/src/fasta/kernel/inference_visitor.dart:1061:9)
#13     FunctionExpression.accept1 (package:kernel/ast.dart:4464:9)
#14     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1988:27)
#15     SourceFieldBuilder.inferType (package:front_end/src/fasta/builder/field_builder.dart:369:53)
#16     SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:1103:35)
#17     KernelTarget.buildOutlines.<anonymous closure>
(package:front_end/src/fasta/kernel/kernel_target.dart:312:14)
<asynchronous suspension>
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#19     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:288:12)
#20     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:108:28)
<asynchronous suspension>
#21     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#22     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#23     kernelForProgramInternal.<anonymous closure>
(package:front_end/src/api_prototype/kernel_generator.dart:61:35)
#24     CompilerContext.runWithOptions.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#25     CompilerContext.runInContext.<anonymous closure>.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:46)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CompilerContext.runInContext.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:19)
#28     _rootRun (dart:async/zone.dart:1126:13)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _runZoned (dart:async/zone.dart:1518:10)
#31     runZoned (dart:async/zone.dart:1465:12)
#32     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#33     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#34     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:60:32)
#35     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:52:17)
#36     compileToKernel (package:vm/kernel_front_end.dart:319:41)
#37     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:452:54)
#38     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#39     _rootRun (dart:async/zone.dart:1122:38)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#43     _rootRun (dart:async/zone.dart:1126:13)
#44     _CustomZone.run (dart:async/zone.dart:1023:19)
#45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#46     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#47     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#48     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      demoteTypeInLibrary (package:front_end/src/fasta/type_inference/type_demotion.dart:65:14)
#2      TypeInferrerImpl.inferDeclarationType
(package:front_end/src/fasta/type_inference/type_inferrer.dart:1889:14)
#3      InferenceVisitor.visitVariableDeclaration
(package:front_end/src/fasta/kernel/inference_visitor.dart:5296:31)
#4      VariableDeclaration.accept (package:kernel/ast.dart:5436:43)
#5      TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3245:24)
#6      InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:299:20)
#7      InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:320:30)
#8      Block.accept (package:kernel/ast.dart:4663:43)
#9      TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3245:24)
#10     TypeInferrerImpl.inferLocalFunction
(package:front_end/src/fasta/type_inference/type_inferrer.dart:2595:43)
#11     InferenceVisitor.visitFunctionNode (package:front_end/src/fasta/kernel/inference_visitor.dart:1037:21)
#12     InferenceVisitor.visitFunctionExpression
(package:front_end/src/fasta/kernel/inference_visitor.dart:1061:9)
#13     FunctionExpression.accept1 (package:kernel/ast.dart:4464:9)
#14     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1988:27)
#15     SourceFieldBuilder.inferType (package:front_end/src/fasta/builder/field_builder.dart:369:53)
#16     SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:1103:35)
#17     KernelTarget.buildOutlines.<anonymous closure>
(package:front_end/src/fasta/kernel/kernel_target.dart:312:14)
<asynchronous suspension>
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#19     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:288:12)
#20     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:108:28)
<asynchronous suspension>
#21     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#22     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#23     kernelForProgramInternal.<anonymous closure>
(package:front_end/src/api_prototype/kernel_generator.dart:61:35)
#24     CompilerContext.runWithOptions.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#25     CompilerContext.runInContext.<anonymous closure>.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:46)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CompilerContext.runInContext.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:19)
#28     _rootRun (dart:async/zone.dart:1126:13)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _runZoned (dart:async/zone.dart:1518:10)
#31     runZoned (dart:async/zone.dart:1465:12)
#32     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#33     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#34     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:60:32)
#35     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:52:17)
#36     compileToKernel (package:vm/kernel_front_end.dart:319:41)
#37     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:452:54)
#38     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#39     _rootRun (dart:async/zone.dart:1122:38)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#43     _rootRun (dart:async/zone.dart:1126:13)
#44     _CustomZone.run (dart:async/zone.dart:1023:19)
#45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#46     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#47     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#48     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11.

**Comment by walkerwg** [comment]
who can help me with the problem? thanks

**Comment by vsmenon** [comment]
Is this crash really happening when you run `flutter doctor`?  If not, can you add some context on what triggered the crash?

**Comment by walkerwg** [comment]
thank you！i had solved the problem by the way that upgrading some flutter dependicies。because Flutter SDK is not compatible with these dependicies
