### ISSUE TITLE
Dart analysis error (prompted to file by IDE)

### ISSUE THREAD

**Issue by GroovinChip** [dart-lang/sdk#41441]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6308749`
- `2.8.0-edge.dcdc71d7639ae83e011cc8d43121397021e35d08`
- `AI-192.7142.36.36.6308749, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1920x1080, 1600x900`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.dcdc71d7639ae83e011cc8d43121397021e35d08, server version 1.27.4, error: Invalid argument(s): selectionStart must be within text.
#0      new SourceCode (package:dart_style/src/source_code.dart:69:9)
#1      EditDomainHandler.format (package:analysis_server/src/edit/edit_domain.dart:134:16)
#2      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:353:16)
#3      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:319:40)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#5      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:315:50)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZonedGuarded (dart:async/zone.dart:1608:12)
#10     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:314:5)
#11     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#13     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#14     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#22     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#23     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#24     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#25     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#27     _rootRunUnary (dart:async/zone.dart:1192:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#35     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#36     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#37     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#38     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#40     _rootRunUnary (dart:async/zone.dart:1192:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#46     _StreamController._add (dart:async/stream_controller.dart:655:7)
#47     _StreamController.add (dart:async/stream_controller.dart:597:5)
#48     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#49     _rootRunUnary (dart:async/zone.dart:1196:13)
#50     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#55     _StreamController._add (dart:async/stream_controller.dart:655:7)
#56     _StreamController.add (dart:async/stream_controller.dart:597:5)
#57     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#58     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#61     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#62...
```

For additional log information, please append the contents of
file://C:\Users\ReubenT\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Apologies that we did not get a chance to investigate this crash; please re-open if you see this on a recent version of Dart.
