### ISSUE TITLE
dart2js crashes when provided with --enable-experiment=non-nullable

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#41491]
This was discovered in https://github.com/flutter/flutter/pull/54617 while writing an integration test for enable-experiment support (https://github.com/flutter/flutter/issues/52819). The app is not using any null safety features.

```
    • Framework revision 7b44043f9f (33 minutes ago), 2020-04-14 19:09:25 -0700
    • Engine revision deef2663ac
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 c9710e5059)
```

```
PS C:\Users\Jonah\flutter\examples\hello_world> flutter build web --enable-experiment=non-nullable
Target dart2js failed: Exception: org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/js_helper.dart@112647+1:
Internal Error: The member '_installSpecializedAsCheck' was not found in library 'rti'.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.8.0-edge.c9710e5059ad94b7d4f1db951cc515a8d9d09ead), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Assertion failure: The member '_installSpecializedAsCheck' was not found in library 'rti'.
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      KernelElementEnvironment.lookupLibraryMember (package:compiler/src/kernel/element_map_impl.dart:1793:7)
#2      CommonElementsImpl._findLibraryMember (package:compiler/src/common_elements.dart:1003:17)
#3      CommonElementsImpl._findRtiFunction (package:compiler/src/common_elements.dart:1876:7)
#4      CommonElementsImpl.installSpecializedAsCheck (package:compiler/src/common_elements.dart:1961:7)
#5      BackendImpacts.newRtiImpact (package:compiler/src/js_backend/backend_impact.dart:817:29)
#6      BackendImpacts.typeCheck (package:compiler/src/js_backend/backend_impact.dart:477:54)
#7      JavaScriptImpactTransformer.onIsCheck (package:compiler/src/js_backend/impact_transformer.dart:333:29)
#8      JavaScriptImpactTransformer.transformResolutionImpact (package:compiler/src/js_backend/impact_transformer.dart:161:11)
#9      KernelWorkItem.run.<anonymous closure>.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:410:32)
#10     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#11     KernelWorkItem.run.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:402:28)
#12     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#13     KernelWorkItem.run (package:compiler/src/kernel/kernel_strategy.dart:377:26)
#14     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>
(package:compiler/src/compiler.dart:460:70)
#15     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#16     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>
(package:compiler/src/compiler.dart:460:32)
#17     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#18     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:28)
#19     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:456:18)
#21     ResolutionEnqueuer._forEach (package:compiler/src/enqueue.dart:449:12)
#22     ResolutionEnqueuer.forEach (package:compiler/src/enqueue.dart:465:5)
#23     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:452:16)
#24     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#25     Compiler.emptyQueue (package:compiler/src/compiler.dart:451:14)
#26     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:477:7)
#27     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#28     Compiler.processQueue (package:compiler/src/compiler.dart:470:14)
#29     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:339:5)
#30     Compiler.compileFromKernel.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:407:17)
#31     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#32     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:406:43)
#33     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#34     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#35     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#36     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#37     new Future.sync (dart:async/future.dart:224:31)
#38     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#39     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#40     Compiler.run (package:compiler/src/compiler.dart:209:41)
#41     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#42     _RootZone.runUnary (dart:async/zone.dart:1439:54)
#43     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#44     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#45     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#46     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#47     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#50     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)



Compiling lib\main.dart for the Web...                              3.7s
Exception: Failed to compile application for the Web.
PS C:\Users\Jonah\flutter\examples\hello_world>
```

xref https://github.com/flutter/flutter/issues/52819

**Comment by sigmundch** [comment]
In this case, the issue is that the experiment flag is not supported with the regular sdk, you need the nnbd sdk to be able to enable it. After we unfork, this will no longer be an issue.

The change that produces this crash was included in the 2.8 beta release, and it's totally possible that some users may try to pass the experiment flag on a 2.8 SDK and hit this crash.

@vsmenon - should consider creating a cherry pick to provide an error message if someone tries to use the non-nullable experiment before it is on preview?

**Comment by vsmenon** [comment]
I assume the fix is small / simple?  If so, I think it merits a cherry-pick given the crash.

**Comment by franklinyow** [comment]
Looks like this can be closed.  Any thing missing?

**Comment by sigmundch** [comment]
I think there is nothing left to do.

We already unforked, and at this time we decide what to do based on the input.dill file (so we no longer rely on the flag being present.)
