### ISSUE TITLE
corelib/symbol_operator_test/03 needs triple-shift operator

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#41532]
The tests
```
corelib/symbol_operator_test/03
```
needs the triple-shift experiment.

**Comment by cskau-g** [comment]
@johnniwinther, do you mean the test if broken, or is it something that needs to be implemented in VM/CFE/Analyzer/..?

FWIW, the test is currently failing with:
```
Unhandled exception:
Didn't throw: >>>
#0      testSymbolThrows (file:///.../sdk/out/DebugX64C/generated_tests/corelib_2/symbol_operator_test_03.dart:76:5)
#1      main (file:///.../sdk/out/DebugX64C/generated_tests/corelib_2/symbol_operator_test_03.dart:33:3)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
