### ISSUE TITLE
language server throws when handling textDocument/completion request: The method 'processDartdoc' was called on null.

### ISSUE THREAD

**Issue by LongCatIsLooong** [dart-lang/sdk#41564]
Stack trace:
```dart
NoSuchMethodError: The method 'processDartdoc' was called on null.
Receiver: null
Tried calling: processDartdoc("/// Additional constraints to apply to [child] during layout")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      DartUnitHoverComputer.computeDocumentation (package:analysis_server/src/computer/computer_hover.dart:160:26)
#2      createSuggestion (package:analysis_server/src/services/completion/dart/suggestion_builder.dart:46:35)
#3      MemberSuggestionBuilder._addSuggestion (package:analysis_server/src/services/completion/dart/suggestion_builder.dart:506:22)
#4      MemberSuggestionBuilder.addSuggestionForAccessor (package:analysis_server/src/services/completion/dart/suggestion_builder.dart:408:14)
#5      InheritedReferenceContributor._addSuggestionsForType (package:analysis_server/src/services/completion/dart/inherited_reference_contributor.dart:57:27)
#6      InheritedReferenceContributor._computeSuggestionsForClass (package:analysis_server/src/services/completion/dart/inherited_reference_contributor.dart:105:7)
#7      InheritedReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/inherited_reference_contributor.dart:44:14)
#8      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:186:31)
<asynchronous suspension>
#9      CompletionHandler._getItems (package:analysis_server/src/lsp/handlers/handler_completion.dart:156:29)
#10     CompletionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:83:41)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#12     CompletionHandler.handle (package:analysis_server/src/lsp/handlers/handler_completion.dart:83:19)
<asynchronous suspension>
#13     MessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:103:12)
#14     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:142:36)
#15     LspAnalysisServer.handleMessage.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:202:49)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#17     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:197:50)
#18     _rootRun (dart:async/zone.dart:1184:13)
#19     _CustomZone.run (dart:async/zone.dart:1077:19)
#20     _runZoned (dart:async/zone.dart:1619:10)
#21     runZonedGuarded (dart:async/zone.dart:1608:12)
#22     LspAnalysisServer.handleMessage (package:analysis_server/src/lsp/lsp_analysis_server.dart:196:5)
#23     LspByteStreamServerChannel._readMessage.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:87:18)
#24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#25     LspByteStreamServerChannel._readMessage (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:83:47)
#26     LspByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:55:24)
#27     _rootRunUnary (dart:async/zone.dart:1192:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#31     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#32     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#33     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#34     _rootRun (dart:async/zone.dart:1180:38)
#35     _CustomZone.run (dart:async/zone.dart:1077:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#38     _rootRun (dart:async/zone.dart:1184:13)
#39     _CustomZone.run (dart:async/zone.dart:1077:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

The client I am using is [lsp-mode](https://github.com/emacs-lsp/lsp-mode). The first bad Flutter commit seems to be https://github.com/flutter/flutter/pull/54806, which has 3 dart rolls in it: https://github.com/flutter/engine/pull/17680, https://github.com/flutter/engine/pull/17694, and https://github.com/flutter/engine/pull/17698.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/144020

This CL should have fixed the problem. Please let us know if you see it again after the next roll of the SDK in to Flutter.
