### ISSUE TITLE
error: flutter build web

### ISSUE THREAD

**Issue by Haple** [dart-lang/sdk#41570]
Target dart2js failed: Exception:                                       
../flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/surface/recording_canvas.dart:1598:8:
Internal Error: The compiler crashed when compiling this element.
  void transform(Float64List matrix4, ui.Path targetPath) {
       ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system (**Ubuntu 18.04.4 LTS**),

* the Dart SDK build number (2.8.0-edge.eea97179386a9ced7d68452cea158345f4019baa), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      TypeSystem.selectorNeedsUpdate (package:compiler/src/inferrer/type_system.dart:308:17)
#2      KernelTypeGraphBuilder._handleDynamic (package:compiler/src/inferrer/builder_kernel.dart:960:16)
#3      KernelTypeGraphBuilder.handleDynamicInvoke (package:compiler/src/inferrer/builder_kernel.dart:1019:12)
#4      KernelTypeGraphBuilder.visitMethodInvocation (package:compiler/src/inferrer/builder_kernel.dart:923:28)
#5      MethodInvocation.accept (package:kernel/ast.dart:3766:44)
#6      KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder_kernel.dart:258:24)
#7      KernelTypeGraphBuilder.analyzeArguments (package:compiler/src/inferrer/builder_kernel.dart:840:22)
#8      KernelTypeGraphBuilder.visitMethodInvocation (package:compiler/src/inferrer/builder_kernel.dart:907:32)
#9      MethodInvocation.accept (package:kernel/ast.dart:3766:44)
#10     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder_kernel.dart:258:24)
#11     KernelTypeGraphBuilder.visitMethodInvocation (package:compiler/src/inferrer/builder_kernel.dart:906:36)
#12     MethodInvocation.accept (package:kernel/ast.dart:3766:44)
#13     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder_kernel.dart:258:24)
#14     KernelTypeGraphBuilder.visitVariableDeclaration (package:compiler/src/inferrer/builder_kernel.dart:801:11)
#15     VariableDeclaration.accept (package:kernel/ast.dart:6413:43)
#16     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder_kernel.dart:258:24)
#17     KernelTypeGraphBuilder.visitBlock (package:compiler/src/inferrer/builder_kernel.dart:477:7)
#18     Block.accept (package:kernel/ast.dart:5450:43)
#19     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder_kernel.dart:258:24)
#20     KernelTypeGraphBuilder.visitFunctionNode (package:compiler/src/inferrer/builder_kernel.dart:401:5)
#21     FunctionNode.accept (package:kernel/ast.dart:2806:38)
#22     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder_kernel.dart:258:24)
#23     KernelTypeGraphBuilder.run (package:compiler/src/inferrer/builder_kernel.dart:225:12)
#24     InferrerEngine._computeMemberTypeInformation (package:compiler/src/inferrer/inferrer_engine.dart:630:20)
#25     InferrerEngine.analyze.<anonymous closure> (package:compiler/src/inferrer/inferrer_engine.dart:562:14)
#26     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#27     InferrerEngine.analyze (package:compiler/src/inferrer/inferrer_engine.dart:561:15)
#28     InferrerEngine._analyzeAllElements.<anonymous closure>.<anonymous closure>
(package:compiler/src/inferrer/inferrer_engine.dart:502:38)
#29     TypeSystem.withMember (package:compiler/src/inferrer/type_system.dart:125:11)
#30     InferrerEngine._analyzeAllElements.<anonymous closure>
(package:compiler/src/inferrer/inferrer_engine.dart:502:13)
#31     Iterable.forEach (dart:core/iterable.dart:279:30)
#32     InferrerEngine._analyzeAllElements (package:compiler/src/inferrer/inferrer_engine.dart:497:22)
#33     InferrerEngine.runOverAllElements (package:compiler/src/inferrer/inferrer_engine.dart:312:5)
#34     TypeGraphInferrer.analyzeMain (package:compiler/src/inferrer/type_graph_inferrer.dart:68:14)
#35     GlobalTypeInferenceTask.runGlobalTypeInference.<anonymous closure>
(package:compiler/src/inferrer/types.dart:176:41)
#36     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#37     GlobalTypeInferenceTask.runGlobalTypeInference (package:compiler/src/inferrer/types.dart:169:12)
#38     Compiler.performGlobalTypeInference (package:compiler/src/compiler.dart:368:28)
#39     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:411:13)
#40     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#41     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#42     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#43     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#44     new Future.sync (dart:async/future.dart:224:31)
#45     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#46     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#47     Compiler.run (package:compiler/src/compiler.dart:209:41)
#48     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#49     _RootZone.runUnary (dart:async/zone.dart:1439:54)
#50     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#51     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#52     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#53     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#54     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#55     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#56     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#57     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

Compiling lib/main.dart for the Web...                             23.7s
Exception: Failed to compile application for the Web.

**Comment by Haple** [comment]
Do you need more info? I was just trying to build my project (with flutter build web) and this whole thing appeared. After trying to run the command again it worked.
