### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by tareq3** [dart-lang/sdk#41579]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.7.2`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.4, screens 1440x900`

## Exception
```
Dart analysis server, SDK version 2.7.2, server version 1.27.4, FATAL error: Invalid argument(s): Unable to create model.
#0      checkArgument (package:quiver/check.dart:45:5)
#1      new Model.fromFile (package:tflite_native/src/model.dart:28:5)
#2      new Interpreter.fromFile (package:tflite_native/src/interpreter.dart:35:25)
#3      new LanguageModel.load (package:analysis_server/src/services/completion/dart/language_model.dart:35:25)
#4      entrypoint.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_ranking.dart:36:31)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#9      _StreamController._add (dart:async/stream_controller.dart:642:7)
#10     _StreamController.add (dart:async/stream_controller.dart:588:5)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file:///private/var/folders/cj/r2zpdypd413bmg2y5g8bp8gr0000gp/T/report.txt.

**Comment by srawlins** [comment]
Apologies that we did not get a chance to look at this crash. Please re-open if you see this again with a recent version of Dart.
