### ISSUE TITLE
analyzer error

### ISSUE THREAD

**Issue by Harshurp20** [dart-lang/sdk#41586]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.7.0-dev.2.1`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720`

## Exception
```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version 1.27.4, FATAL error: NoSuchMethodError: The method 'functionExpression_begin' was called on null.
Receiver: null
Tried calling: functionExpression_begin(Instance of 'FunctionExpressionImpl')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3765:30)
#2      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4962:49)
#3      AstResolver.resolve (package:analyzer/src/summary2/ast_resolver.dart:80:10)
#4      ConstantInitializersResolver._resolveVariable (package:analyzer/src/summary2/top_level_inference.dart:94:21)
#5      ConstantInitializersResolver._resolveClassFields (package:analyzer/src/summary2/top_level_inference.dart:69:7)
#6      List.forEach (dart:core-patch/growable_array.dart:285:8)
#7      ConstantInitializersResolver.perform (package:analyzer/src/summary2/top_level_inference.dart:54:20)
#8      Linker._resolveConstantInitializers (package:analyzer/src/summary2/link.dart:224:40)
#9      Linker._buildOutlines (package:analyzer/src/summary2/link.dart:103:5)
#10     Linker.link (package:analyzer/src/summary2/link.dart:82:5)
#11     link (package:analyzer/src/summary2/link.dart:34:10)
#12     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:179:26)
#13     SetMixin.forEach (dart:collection/set.dart:148:30)
#14     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:134:32)
#15     SetMixin.forEach (dart:collection/set.dart:148:30)
#16     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:134:32)
#17     SetMixin.forEach (dart:collection/set.dart:148:30)
#18     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:134:32)
#19     SetMixin.forEach (dart:collection/set.dart:148:30)
#20     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:134:32)
#21     SetMixin.forEach (dart:collection/set.dart:148:30)
#22     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:134:32)
#23     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:231:17)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#25     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:229:12)
#26     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1465:23)
#27     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1262:30)
#28     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#29     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1251:20)
#30     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1317:37)
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:974:39)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1940:24)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1874:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:223:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:619:21)
#38     _rootRun (dart:async/zone.dart:1126:13)
#39     _CustomZone.run (dart:async/zone.dart:1023:19)
#40     _runZoned (dart:async/zone.dart:1518:10)
#41     runZoned (dart:async/zone.dart:1465:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:735:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:617:7)
#44     Driver.start (package:analysis_server/src/server/driver.dart:515:7)
#45     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#46     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#47     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#48     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMic...
```

For additional log information, please append the contents of
file://C:\Users\Admin\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.7; please re-open if you see this in a recent version of Dart/Flutter.
