### ISSUE TITLE
Very simple app, just working on the main.dart file. Tried to start the web browser and got the you've found a bug in our compiler message.

### ISSUE THREAD

**Issue by Tim-CCG** [dart-lang/sdk#41633]
```
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/Users/CCG/Developer/fluttersdk/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o packages/martialmaster/main_web_entrypoint.ddc.js --source-map --summary=packages/js/js_util.ddc.dill=packages/js/js_util --summary=packages/js/js.ddc.dill=packages/js/js --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=packages/path/path.ddc.dill=packages/path/path --summary=packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=packages/source_span/source_span.ddc.dill=packages/source_span/source_span --summary=packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --summary=packages/firebase/src/app.ddc.dill=packages/firebase/src/app --summary=packages/firebase/firebase.ddc.dill=packages/firebase/firebase --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures --summary=packages/flutter_web_plugins/flutter_web_plugins.ddc.dill=packages/flutter_web_plugins/flutter_web_plugins --summary=packages/plugin_platform_interface/plugin_platform_interface.ddc.dill=packages/plugin_platform_interface/plugin_platform_interface --summary=packages/cloud_functions_platform_interface/cloud_functions_platform_interface.ddc.dill=packages/cloud_functions_platform_interface/cloud_functions_platform_interface --summary=packages/cloud_functions_web/cloud_functions_web.ddc.dill=packages/cloud_functions_web/cloud_functions_web --summary=packages/quiver/core.ddc.dill=packages/quiver/core --summary=packages/firebase_core_platform_interface/firebase_core_platform_interface.ddc.dill=packages/firebase_core_platform_interface/firebase_core_platform_interface --summary=packages/firebase_core_web/firebase_core_web.ddc.dill=packages/firebase_core_web/firebase_core_web --summary=packages/martialmaster/generated_plugin_registrant.ddc.dill=packages/martialmaster/generated_plugin_registrant --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino --summary=packages/flutter/material.ddc.dill=packages/flutter/material --summary=packages/martialmaster/main.ddc.dill=packages/martialmaster/main --packages=file:///var/folders/yp/kpk9k5js7314fpd17lng5t280000gp/T/kernel_builder_TQqWai/.packages --module-name=packages/martialmaster/main_web_entrypoint --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///Users/CCG/Developer/fluttersdk/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=/var/folders/yp/kpk9k5js7314fpd17lng5t280000gp/T/ddk_builder_6RKmOw/used_inputs.txt package:martialmaster/main_web_entrypoint.dart
    dart --version: 2.7.0-dev.2.1.flutter-a9c77229c2 (Wed Dec 4 11:26:20 2019 +0000) on "macos_x64"
```

**Comment by mraleph** [comment]
@Tim-CCG thanks for the report. I think you have omitted the stack trace of the actual crash. Do you still have it? 

Otherwise there is not enough information to go by.

**Comment by Tim-CCG** [comment]
Sorry about that, I was tinkering with it late at night and wasn’t paying attention. Here is everything that was printed out at the console:

Tim






Launching lib/main.dart on Chrome in debug mode...
Building application for the web...

AssetNotFoundException: martialmaster|lib/main_web_entrypoint.ddc.js
Error compiling dartdevc module:martialmaster|lib/main_web_entrypoint.ddc.js

Failed to initialize incremental compiler, throwing away old state.

This is likely a result of https://github.com/dart-lang/sdk/issues/38102, if
you are consistently seeing this problem please see that issue.

The specific exception that was encountered was:

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:410:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:280:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:45:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:404:12)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)


We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/Users/CCG/Developer/fluttersdk/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o packages/martialmaster/main_web_entrypoint.ddc.js --source-map --summary=packages/js/js_util.ddc.dill=packages/js/js_util --summary=packages/js/js.ddc.dill=packages/js/js --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=packages/path/path.ddc.dill=packages/path/path --summary=packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=packages/source_span/source_span.ddc.dill=packages/source_span/source_span --summary=packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --summary=packages/firebase/src/app.ddc.dill=packages/firebase/src/app --summary=packages/firebase/firebase.ddc.dill=packages/firebase/firebase --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures --summary=packages/flutter_web_plugins/flutter_web_plugins.ddc.dill=packages/flutter_web_plugins/flutter_web_plugins --summary=packages/plugin_platform_interface/plugin_platform_interface.ddc.dill=packages/plugin_platform_interface/plugin_platform_interface --summary=packages/cloud_functions_platform_interface/cloud_functions_platform_interface.ddc.dill=packages/cloud_functions_platform_interface/cloud_functions_platform_interface --summary=packages/cloud_functions_web/cloud_functions_web.ddc.dill=packages/cloud_functions_web/cloud_functions_web --summary=packages/quiver/core.ddc.dill=packages/quiver/core --summary=packages/firebase_core_platform_interface/firebase_core_platform_interface.ddc.dill=packages/firebase_core_platform_interface/firebase_core_platform_interface --summary=packages/firebase_core_web/firebase_core_web.ddc.dill=packages/firebase_core_web/firebase_core_web --summary=packages/martialmaster/generated_plugin_registrant.ddc.dill=packages/martialmaster/generated_plugin_registrant --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino --summary=packages/flutter/material.ddc.dill=packages/flutter/material --summary=packages/martialmaster/main.ddc.dill=packages/martialmaster/main --packages=file:///var/folders/yp/kpk9k5js7314fpd17lng5t280000gp/T/kernel_builder_TQqWai/.packages --module-name=packages/martialmaster/main_web_entrypoint --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///Users/CCG/Developer/fluttersdk/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=/var/folders/yp/kpk9k5js7314fpd17lng5t280000gp/T/ddk_builder_6RKmOw/used_inputs.txt package:martialmaster/main_web_entrypoint.dart
    dart --version: 2.7.0-dev.2.1.flutter-a9c77229c2 (Wed Dec 4 11:26:20 2019 +0000) on "macos_x64"

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:410:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:280:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:45:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:404:12)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)




Failed after 261ms
Finished with error: Failed to build application for the Web.

**Comment by modulovalue** [comment]
Given that this is 6 years old and there's neither a repro nor anything actionable here, it seems like we can close this @mraleph?
