### ISSUE TITLE
applicatie hhsk

### ISSUE THREAD

**Issue by alwinvandalen** [dart-lang/sdk#41637]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.7.2`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.7.2, server version , FATAL error: FileSystemException: Creation failed, path = 'C:\Users\A. van Dalen\AppData\Local\.dartServer' (OS Error: Toegang geweigerd.
, errno = 5)
#0      _Directory.createSync (dart:io/directory_impl.dart:140:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:135:16)
#2      PhysicalResourceProvider.getStateLocation (package:analyzer/file_system/physical_file_system.dart:123:17)
#3      Driver._readUuid (package:analysis_server/src/server/driver.dart:879:43)
#4      Driver.start (package:analysis_server/src/server/driver.dart:491:15)
#5      main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file://C:\Users\A0982~1.VAN\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Apologies that we did not get a chance to look at this crash. Please re-open if you see this again with a recent version of Dart.
