### ISSUE TITLE
IntelliJ: Analyzer crash on Flutter beta (v1.17.0-3.2.pre) channel

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#41650]
My IntelliJ project keeps getting into a state where the analyzer keeps crashing until the editor is restarted. 

Flutter doctor:

```
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.15.4 19E287, locale en)
    • Flutter version 1.17.0-3.2.pre at /Users/ryjohn/code/github/flutter/flutter
    • Framework revision 2a7bc389f2 (3 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ryjohn/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • iPhone 8   • D36F57AC-FB4F-484F-AD5F-950AFF27A034 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.122
    • Web Server • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.7142.36`
- `2.8.0-dev.20.10`
- `IU-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.4, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.0-dev.20.10, server version 1.27.4, FATAL error: FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

For additional log information, please append the contents of
file:///private/var/folders/3q/2gm34ftd37n43w9sxr09h0d000m6cw/T/report.txt.

**Comment by scheglov** [comment]
@johnpryan Any chance to get that file, mentioned as `For additional log information`?
You could send it to me `scheglov@google.com`. Without additional information it is not actionable. I can only guess that it seems that your current directory became unavailable?

**Comment by johnpryan** [comment]
Here's the additional log information from a similar crash:

Dart analysis server, SDK version 2.7.1, server version 1.27.4, FATAL error: FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

```
1588102002895 <= {"id":"51","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102015011 => {"id":"52","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102015012 <= {"id":"52","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102015656 => {"id":"53","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102015657 <= {"id":"53","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102016330 => {"id":"54","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102016331 <= {"id":"54","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102016822 => {"id":"55","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102016824 <= {"id":"55","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102017161 => {"id":"56","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102017162 <= {"id":"56","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102017532 => {"id":"57","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102017534 <= {"id":"57","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102017848 => {"id":"58","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102017849 <= {"id":"58","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102018218 => {"id":"59","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102018220 <= {"id":"59","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102018589 => {"id":"60","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102018591 <= {"id":"60","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102018952 => {"id":"61","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102018953 <= {"id":"61","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102019277 => {"id":"62","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102019278 <= {"id":"62","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102020210 => {"id":"63","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"add","content":"---\ntitle: Subscribe\nla
1588102020211 <= {"id":"63","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102021205 => {"id":"64","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/flutter/website/src/subscribe/index.html":{"type":"remove"}}},"clientRequestTime":1588102021
1588102021205 <= {"id":"64","error":{"code":"SERVER_ERROR","message":"FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)","stackT
1588102055322 <= {"event":"analysis.flushResults","params":{"files":["/Users/ryjohn/code/github/flutter/website/_site/assets/source-maps/_assets/css/_bootstrap_adjust.scss.70288859921400.66172.972750"
1588102070728 => {"id":"65","method":"analysis.updateContent","params":{"files":{"/Users/ryjohn/code/github/dart-lang/dart-pad/lib/embed.dart":{"type":"add","content":"// Copyright (c) 2019, the Dart 
1588102070736 <= {"id":"65","result":{}}
```


This tends to happen when I have two projects open at the same time. In this case I had `flutter/website` and `dart-lang/dart-pad` open. I have IntelliJ configured to use the 2.7.1 Dart SDK

**Comment by scheglov** [comment]
Sigh... The lines in this file are intentionally truncated, and so I don't see the stack trace.

**Comment by johnpryan** [comment]
Are there any flags I could set to disable truncation?

**Comment by scheglov** [comment]
If you open `Registry...` in IntelliJ, and add `--instrumentation-log-file=/Users/scheglov/tmp/das-instrumentation.log` to `dart.server.additional.arguments`, it will generate large files with the requests and responses between IntelliJ and DAS. AFAIK this will include all exceptions.

**Comment by johnpryan** [comment]
I think this is stale. I haven't seen this recently.
