### ISSUE TITLE
analysis server fatal crash loop working on dartdoc

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#41730]
@scheglov 
This started in the middle of editing/refactoring and the server seems to crash repeatedly now.  I will save the state of my tree if you want to take a look.  This crash report is from 6406f79fcb1bb931fb521690e7f7693c1d247eee but have verified it happens on the last two dev releases and 2.8.1 stable, too.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.7142.36`
- `2.9.0-edge.6406f79fcb1bb931fb521690e7f7693c1d247eee`
- `IC-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.4, screens 3840x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.9.0-edge.6406f79fcb1bb931fb521690e7f7693c1d247eee, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ElementResolver._resolvePropertyAccess (package:analyzer/src/generated/element_resolver.dart:1413:48)
#2      ElementResolver.visitPropertyAccess (package:analyzer/src/generated/element_resolver.dart:633:5)
#3      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8425:49)
#4      ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:1505:10)
#5      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8425:49)
#6      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1404:18)
#7      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7148:49)
#8      SpreadElementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9158:18)
#9      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1454:10)
#10     UnifyingAstVisitor.visitSpreadElement (package:analyzer/dart/ast/visitor.dart:3416:47)
#11     ResolverVisitor.visitSpreadElement (package:analyzer/src/generated/resolver.dart:1583:11)
#12     SpreadElementImpl.accept (package:analyzer/src/dart/ast/ast.dart:9153:20)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#14     SetOrMapLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8725:15)
#15     TypedLiteralResolver.resolveSetOrMapLiteral (package:analyzer/src/dart/resolver/typed_literal_resolver.dart:153:10)
#16     ResolverVisitor.visitSetOrMapLiteral (package:analyzer/src/generated/resolver.dart:1548:27)
#17     SetOrMapLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:8704:49)
#18     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10510:19)
#19     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1454:10)
#20     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3466:59)
#21     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:2849:11)
#22     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:1736:11)
#23     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10504:49)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#25     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10610:16)
#26     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1454:10)
#27     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3470:7)
#28     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:1762:11)
#29     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10604:15)
#30     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10658:20)
#31     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1454:10)
#32     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:3474:7)
#33     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10654:15)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#35     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1085:17)
#36     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1454:10)
#37     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#38     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2230:13)
#39     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2785:7)
#40     ResolverVisitor.visitIfStatement.<anonymous closure> (package:analyzer/src/generated/resolver.dart:1288:11)
#41     TypePromotionManager.visitIfStatement_thenStatement (package:analyzer/src/generated/type_promotion_manager.dart:119:10)
#42     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:1284:23)
#43     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5672:49)
#44     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#45     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1085:17)
#46     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1454:10)
#47     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#48     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2230:13)
#49     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1081:49)
#50     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1040:13)
#51     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1454:10)
#52     UnifyingAstVisitor.visitBlockFunctionBody (package:a...
```

For additional log information, please append the contents of
file:///private/var/folders/b8/jg3_spkj02d51bcz3fsb5jjc000b33/T/report10.txt.

[report10.txt](https://github.com/dart-lang/sdk/files/4561087/report10.txt)

**Comment by jcollins-g** [comment]
This could be related to #38067.

**Comment by jcollins-g** [comment]
Closing, this is a duplicate of #38067.  I had added a super call in a mixin unintentionally referencing an interface member; when I stopped doing that, the analyzer stopped crashing.
