### ISSUE TITLE
dart2js crash in set literal following throw

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#41781]
```dart
main() {
  [throw 1, {...[], ...[]}];
}
```
```
Unhandled exception:
Assertion failure: Cannot find value local(main#null) in () for j:method(main).
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      LocalsHandler.readLocal (package:compiler/src/ssa/locals_handler.dart:331:11)
#2      KernelSsaGraphBuilder.visitVariableGet (package:compiler/src/ssa/builder_kernel.dart:3482:29)
#3      VariableGet.accept (package:kernel/ast.dart:2996:44)
#4      KernelSsaGraphBuilder.visitBlockExpression (package:compiler/src/ssa/builder_kernel.dart:3620:16)
#5      BlockExpression.accept (package:kernel/ast.dart:5306:44)
```

**Comment by rakudrama** [comment]
Fixed via a85c8b75204ba8879b0220bf232b94d1ff8bf48c
