### ISSUE TITLE
Crash in package:kernel/transformations/continuation.dart on invalid type

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#41786]
With https://dart-review.googlesource.com/c/sdk/+/146805 :

pkg/front_end/tool/fasta compile --omit-platform --dump-ir pkg/front_end/testcases/general/async_method_with_invalid_type.dart

```
Unhandled exception:
Crash when compiling null,
at character offset null:
unreachable
#0      AsyncRewriterBase.defaultExpression (package:kernel/transformations/continuation.dart:1154:39)
#1      TreeVisitor.visitPropertyGet (package:kernel/visitor.dart:149:43)
#2      PropertyGet.accept (package:kernel/ast.dart:3105:44)
#3      ForInStatement.transformChildren (package:kernel/ast.dart:5849:27)
#4      Transformer.defaultTreeNode (package:kernel/visitor.dart:650:10)
#5      TreeVisitor.defaultStatement (package:kernel/visitor.dart:203:41)
#6      TreeVisitor.visitForInStatement (package:kernel/visitor.dart:215:49)
#7      RecursiveContinuationRewriter.visitForInStatement (package:kernel/transformations/continuation.dart:191:20)
#8      AsyncRewriterBase.visitForInStatement (package:kernel/transformations/continuation.dart:1073:13)
#9      ForInStatement.accept (package:kernel/ast.dart:5833:43)
#10     AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation.dart:655:17)
#11     Block.accept (package:kernel/ast.dart:5463:43)
#12     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:740:10)
#13     AsyncRewriterBase.buildWrappedBody (package:kernel/transformations/continuation.dart:614:24)
#14     AsyncRewriterBase.setupAsyncContinuations (package:kernel/transformations/continuation.dart:566:39)
#15     AsyncFunctionRewriter.rewrite (package:kernel/transformations/continuation.dart:1316:5)
#16     RecursiveContinuationRewriter.visitFunctionNode (package:kernel/transformations/continuation.dart:143:14)
#17     FunctionNode.accept (package:kernel/ast.dart:2819:38)
#18     Procedure.transformChildren (package:kernel/ast.dart:2411:27)
#19     Transformer.defaultTreeNode (package:kernel/visitor.dart:650:10)
#20     TreeVisitor.defaultMember (package:kernel/visitor.dart:230:35)
#21     TreeVisitor.visitProcedure (package:kernel/visitor.dart:232:39)
#22     RecursiveContinuationRewriter.visitProcedure (package:kernel/transformations/continuation.dart:117:51)
#23     Procedure.accept (package:kernel/ast.dart:2398:40)
#24     transformList (package:kernel/ast.dart:8749:27)
#25     Library.transformChildren (package:kernel/ast.dart:626:5)
#26     Transformer.defaultTreeNode (package:kernel/visitor.dart:650:10)
#27     TreeVisitor.visitLibrary (package:kernel/visitor.dart:254:35)
#28     RecursiveContinuationRewriter.visitLibrary (package:kernel/transformations/continuation.dart:125:28)
#29     Library.accept (package:kernel/ast.dart:606:38)
#30     RecursiveContinuationRewriter.rewriteLibrary (package:kernel/transformations/continuation.dart:97:17)
#31     transformLibraries (package:kernel/transformations/continuation.dart:55:14)
#32     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:171:5)
#33     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1110:19)
#34     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:356:7)
<asynchronous suspension>
#35     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#36     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#37     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:346:12)
#38     CompileTask.compile (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:339:28)
<asynchronous suspension>
#39     compile.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:237:25)
#40     withGlobalOptions.<anonymous closure> (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:430:13)
#41     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#42     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#43     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#44     new Future.sync (dart:async/future.dart:224:31)
#45     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#46     _rootRun (dart:async/zone.dart:1184:13)
#47     _CustomZone.run (dart:async/zone.dart:1077:19)
#48     _runZoned (dart:async/zone.dart:1619:10)
#49     runZoned (dart:async/zone.dart:1539:10)
#50     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#51     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#52     withGlobalOptions (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:423:26)
#53     compile.<anonymous closure> (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:230:18)
#54     runProtectedFromAbort (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:478:24)
#55     compile (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:229:16)
#56     compileEntryPoint (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:77:11)
#57     main (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#58     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


#0      AsyncRewriterBase.defaultExpression (package:kernel/transformations/continuation.dart:1154:39)
#1      TreeVisitor.visitPropertyGet (package:kernel/visitor.dart:149:43)
#2      PropertyGet.accept (package:kernel/ast.dart:3105:44)
#3      ForInStatement.transformChildren (package:kernel/ast.dart:5849:27)
#4      Transformer.defaultTreeNode (package:kernel/visitor.dart:650:10)
#5      TreeVisitor.defaultStatement (package:kernel/visitor.dart:203:41)
#6      TreeVisitor.visitForInStatement (package:kernel/visitor.dart:215:49)
#7      RecursiveContinuationRewriter.visitForInStatement (package:kernel/transformations/continuation.dart:191:20)
#8      AsyncRewriterBase.visitForInStatement (package:kernel/transformations/continuation.dart:1073:13)
#9      ForInStatement.accept (package:kernel/ast.dart:5833:43)
#10     AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation.dart:655:17)
#11     Block.accept (package:kernel/ast.dart:5463:43)
#12     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:740:10)
#13     AsyncRewriterBase.buildWrappedBody (package:kernel/transformations/continuation.dart:614:24)
#14     AsyncRewriterBase.setupAsyncContinuations (package:kernel/transformations/continuation.dart:566:39)
#15     AsyncFunctionRewriter.rewrite (package:kernel/transformations/continuation.dart:1316:5)
#16     RecursiveContinuationRewriter.visitFunctionNode (package:kernel/transformations/continuation.dart:143:14)
#17     FunctionNode.accept (package:kernel/ast.dart:2819:38)
#18     Procedure.transformChildren (package:kernel/ast.dart:2411:27)
#19     Transformer.defaultTreeNode (package:kernel/visitor.dart:650:10)
#20     TreeVisitor.defaultMember (package:kernel/visitor.dart:230:35)
#21     TreeVisitor.visitProcedure (package:kernel/visitor.dart:232:39)
#22     RecursiveContinuationRewriter.visitProcedure (package:kernel/transformations/continuation.dart:117:51)
#23     Procedure.accept (package:kernel/ast.dart:2398:40)
#24     transformList (package:kernel/ast.dart:8749:27)
#25     Library.transformChildren (package:kernel/ast.dart:626:5)
#26     Transformer.defaultTreeNode (package:kernel/visitor.dart:650:10)
#27     TreeVisitor.visitLibrary (package:kernel/visitor.dart:254:35)
#28     RecursiveContinuationRewriter.visitLibrary (package:kernel/transformations/continuation.dart:125:28)
#29     Library.accept (package:kernel/ast.dart:606:38)
#30     RecursiveContinuationRewriter.rewriteLibrary (package:kernel/transformations/continuation.dart:97:17)
#31     transformLibraries (package:kernel/transformations/continuation.dart:55:14)
#32     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:171:5)
#33     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1110:19)
#34     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:356:7)
<asynchronous suspension>
#35     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#36     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#37     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:346:12)
#38     CompileTask.compile (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:339:28)
<asynchronous suspension>
#39     compile.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:237:25)
#40     withGlobalOptions.<anonymous closure> (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:430:13)
#41     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#42     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#43     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#44     new Future.sync (dart:async/future.dart:224:31)
#45     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#46     _rootRun (dart:async/zone.dart:1184:13)
#47     _CustomZone.run (dart:async/zone.dart:1077:19)
#48     _runZoned (dart:async/zone.dart:1619:10)
#49     runZoned (dart:async/zone.dart:1539:10)
#50     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#51     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#52     withGlobalOptions (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:423:26)
#53     compile.<anonymous closure> (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:230:18)
#54     runProtectedFromAbort (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:478:24)
#55     compile (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:229:16)
#56     compileEntryPoint (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:77:11)
#57     main (file:///usr/local/google/home/jensj/code/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#58     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by johnniwinther** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/188463
