### ISSUE TITLE
provide a way for classes to opt in into extended stack traces with context information

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#41799]
# Motivation

We have discovered that stable release of Flutter contains a bug in the AOT transformation https://github.com/flutter/flutter/issues/56479, which crashes with the following stack trace

```
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    #1      new StaticTypeContext (package:kernel/type_environment.dart:763:27)
    #2      _TreeShakerPass1.staticTypeContext (package:vm/transformations/type_flow/transformer.dart:752:30)
    #3      _TreeShakerPass1._fixArgumentEvaluationOrder (package:vm/transformations/type_flow/transformer.dart:1007:41)
    #4      _TreeShakerPass1.visitConstructorInvocation (package:vm/transformations/type_flow/transformer.dart:1170:22)
    #5      ConstructorInvocation.accept (package:kernel/ast.dart:3964:44)
    #6      Field.transformChildren (package:kernel/ast.dart:1862:33)
    #7      _TreeShakerPass1.visitField (package:vm/transformations/type_flow/transformer.dart:903:16)
    #8      Field.accept (package:kernel/ast.dart:1847:40)
    #9      transformList (package:kernel/ast.dart:8700:27)
    #10     _TreeShakerPass1.visitClass (package:vm/transformations/type_flow/transformer.dart:856:5)
    #11     Class.accept (package:kernel/ast.dart:1375:38)
    #12     transformList (package:kernel/ast.dart:8700:27)
    #13     Library.transformChildren (package:kernel/ast.dart:627:5)
    #14     Transformer.defaultTreeNode (package:kernel/visitor.dart:650:10)
    #15     TreeVisitor.visitLibrary (package:kernel/visitor.dart:254:35)
    #16     Library.accept (package:kernel/ast.dart:609:38)
    #17     transformList (package:kernel/ast.dart:8700:27)
    #18     Component.transformChildren (package:kernel/ast.dart:8516:5)
    #19     _TreeShakerPass1.transform (package:vm/transformations/type_flow/transformer.dart:764:15)
    #20     TreeShaker.transformComponent (package:vm/transformations/type_flow/transformer.dart:582:12)
    #21     transformComponent (package:vm/transformations/type_flow/transformer.dart:76:7)
    #22     runGlobalTransformations (package:vm/kernel_front_end.dart:425:5)
    #23     compileToKernel (package:vm/kernel_front_end.dart:336:11)
    <asynchronous suspension>
    #24     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:510:54)
    #25     new Future.<anonymous closure> (dart:async/future.dart:176:37)
    #26     _rootRun (dart:async/zone.dart:1180:38)
    #27     _CustomZone.run (dart:async/zone.dart:1077:19)
    #28     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
    #29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
    #30     _rootRun (dart:async/zone.dart:1184:13)
    #31     _CustomZone.run (dart:async/zone.dart:1077:19)
    #32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
    #33     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
    #34     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
    #35     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
    #36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

This stack trace gives us enough information to diagnose the problem - but unfortunately does not give us enough information to provide a work-around for the user - for that we need to know which field is being visited in the AST. 

# Proposal

Add pragma `@pragma('vm:expand-in-stack-trace')` (tentative name), if the class is annotated with this pragma then its methods and methods of all classes that implement or extend it get an expanded context in the stack trace, which would include parameters and the receiver. For example, annotating `TreeVisitor` and `Node` with this annotation would result in the following change to the stack trace:

```
    #6      Field.transformChildren {this = ..., visitor = ...} (package:kernel/ast.dart:1862:33)
    #7      _TreeShakerPass1.visitField {this = ..., field = ... } (package:vm/transformations/type_flow/transformer.dart:903:16)
```

# Alternatives 

V8 has [imperative API](https://v8.dev/docs/stack-trace-api) which allows to customise stack trace formatting and gives developer programmatic access to a representation of the call stack, which includes receiver object for any frame (but does not include way to capture or access other local variables).

Python gives you [programmatic access](https://www.oreilly.com/library/view/python-cookbook/0596001673/ch14s05.html) to the call stack including local variables

# Considerations

1. Calling arbitrary Dart code during stack trace formatting might not be desirable or portable across platforms that Dart supports - that is why we make it an opt-in VM specific feature.
2. For code size reasons we might restrict this feature to JIT builds

**Comment by lrhn** [comment]
If this is a JIT-only feature, then a declarative approach (using annotations or compiler flags) is probably better than an imperative one using code. That code would not even exist on other platforms. Annotations can be ignored.

The format:
```
    #6      Field.transformChildren {this = ..., visitor = ...} (package:kernel/ast.dart:1862:33)
    #7      _TreeShakerPass1.visitField {this = ..., field = ... } (package:vm/transformations/type_flow/transformer.dart:903:16)
```
does not say how to actually write the `...` values. How do you write a `Node` or `visitor` function out? Do you have a way built into the debugger to make string representations of arbitrary objects,  preferably without calling Dart code?

Could it be a debugger feature? Or can the debugger already do this, and what you want is a way to capture the stack trace with extra info for access after execution has ended?


Adding annotations is a reactive approach. I assume you add this annotation when something breaks, then run the code again and hope the same error occurs again. Would people start adding the annotation everywhere while developing, just to make their own life easier (then, maybe, remove it when compiling for production, or that happens automatically if it's not a JIT target).
I think I'd do that.

You cannot add annotations to other people's code, so should there be a way to inject it as well?

Would it be possible to *always* do the expansion for all functions on the stack? At least while debugging?
That could get expensive, so maybe only do it for stack traces associated with throwing an `Error`, and only the first time the error is thrown, when you are also installing the stack trace on the error object.

**Comment by rmacnak-google** [comment]
We already have [programmatic access to stack](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#getstack); you just need to do it from another process or isolate.

**Comment by leafpetersen** [comment]
> 1. lling arbitrary Dart code during stack trace formatting might not be desirable or portable across platforms that Dart supports - that is why we make it an opt-in VM specific feature.

I missed where in your proposal arbitrary Dart code is run during stack trace formatting.  Can you expand?

**Comment by mraleph** [comment]
@lrhn 

> does not say how to actually write the ... values. 

Added the description - for simplicity I assume that there are just results of calling `toString` on the values. 

> Could it be a debugger feature? Or can the debugger already do this, and what you want is a way to capture the stack trace with extra info for access after execution has ended?

Debugger can already do that (as @rmacnak-google points out) the challenge here is how to utilise this functionality in release builds to facilitate post mortem problem analysis. One solution would be that all our tools have some sort of a watchdog isolate that monitors other isolates via service protocol and captures more informative stack traces when errors happen. 

This seems possible to setup and even abstract into utility library) but seems a bit over-engineered. (some of the complexity would stem from the fact that we don't have simple way to "self-attach") 

> Adding annotations is a reactive approach. I assume you add this annotation when something breaks, then run the code again and hope the same error occurs again. Would people start adding the annotation everywhere while developing, just to make their own life easier (then, maybe, remove it when compiling for production, or that happens automatically if it's not a JIT target).

Note that this is not a feature intended for the development - it is for diagnosing crashes which occur in deployment.

@leafpetersen 

> I missed where in your proposal arbitrary Dart code is run during stack trace formatting. Can you expand?

Expanded the section - it now mentions calling `toString`
