### ISSUE TITLE
Failures on [BUILD] - Initial CL to unfork the NNBD Dart SDK...Remove ElementSuggestionBuilder

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#41808]
There are new test failures on [[BUILD] - Initial CL to unfork the NNBD Dart SDK...Remove ElementSuggestionBuilder](https://github.com/dart-lang/sdk/compare/39e0e75fcf141b9948c35cf068df475a9ed8f10c~...03ce33f80c50e1f8168fa4e61468969d8bd4eda5).

The tests
```

vm/dart/causal_stacks/async_throws_stack_non_symbolic_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-linux-product-x64
```
```
stdout:
RegExps for expected stack:
"^#0      throwSync \(.*/utils.dart:16(:3)?\)$"
"^#1      noYields3 \(.*/utils.dart:54(:3)?\)$"
"^#2      noYields2 \(.*/utils.dart:50(:9)?\)$"
"^#3      noYields \(.*/utils.dart:46(:9)?\)$"
"^#4      doTestAwait "
"^#5      doTestsCausal "
"^<asynchronous suspension>$"
"^#6      main "
"^#7      _startIsolate.<anonymous closure> "
"^#8      _RawReceivePortImpl._handleMessage "

Non-symbolic actual stack:
Warning: This VM has been configured to produce stack traces that violate the Dart standard.
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 9036, tid: 140364650903296, name DartWorker
isolate_instructions: 7fa9315ba000 vm_instructions: 7fa9315b6000
    #00 abs 00007fa93164bb42 _kDartIsolateSnapshotInstructions+0x91b42
    #01 abs 00007fa93164bc33 _kDartIsolateSnapshotInstructions+0x91c33
    #02 abs 00007fa93164bde3 _kDartIsolateSnapshotInstructions+0x91de3
    #03 abs 00007fa931642a58 _kDartIsolateSnapshotInstructions+0x88a58
    #04 abs 00007fa931650050 _kDartIsolateSnapshotInstructions+0x96050
    #05 abs 00007fa93162e442 _kDartIsolateSnapshotInstructions+0x74442
    #06 abs 00007fa9316526f3 _kDartIsolateSnapshotInstructions+0x986f3
<asynchronous suspension>
    #07 abs 00007fa931651931 _kDartIsolateSnapshotInstructions+0x97931
    #08 abs 00007fa931651e05 _kDartIsolateSnapshotInstructions+0x97e05
    #09 abs 00007fa9315f6d70 _kDartIsolateSnapshotInstructions+0x3cd70

Actual stack:
#0      throwSync (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart:16)
#1      noYields3 (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart:54)
#2      noYields2 (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart:50)
#3      noYields (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart:46)
#4      doTestAwait (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart:224)
#5      doTestsCausal (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart:311)
#6      _RootZone.runUnary (dart:async/zone.dart:1450)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:143)
<asynchronous suspension>
#8      main (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/async_throws_stack_non_symbolic_test.dart:16)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168)

Expected line 7 to be `^<asynchronous suspension>$` but was `#6      _RootZone.runUnary (dart:async/zone.dart:1450)`

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
Warning: This VM has been configured to produce stack traces that violate the Dart standard.
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 9036, tid: 140364673263488, name Dart_Initialize
isolate_instructions: 7fa9315ba000 vm_instructions: 7fa9315b6000
    #00 abs 00007fa931642f56 _kDartIsolateSnapshotInstructions+0x88f56
    #01 abs 00007fa93164942c _kDartIsolateSnapshotInstructions+0x8f42c
    #02 abs 00007fa93162e442 _kDartIsolateSnapshotInstructions+0x74442
    #03 abs 00007fa9316526f3 _kDartIsolateSnapshotInstructions+0x986f3
<asynchronous suspension>
    #04 abs 00007fa931642b66 _kDartIsolateSnapshotInstructions+0x88b66
<asynchronous suspension>
    #05 abs 00007fa931650050 _kDartIsolateSnapshotInstructions+0x96050
    #06 abs 00007fa93162e442 _kDartIsolateSnapshotInstructions+0x74442
    #07 abs 00007fa9316526f3 _kDartIsolateSnapshotInstructions+0x986f3
<asynchronous suspension>
    #08 abs 00007fa931651931 _kDartIsolateSnapshotInstructions+0x97931
    #09 abs 00007fa931651e05 _kDartIsolateSnapshotInstructions+0x97e05
    #10 abs 00007fa9315f6d70 _kDartIsolateSnapshotInstructions+0x3cd70
```

**Comment by mkustermann** [comment]
There are no failures in the current results, though some tests are skipped in `dartkp` mode.

@cskau-g Could you ensure our stack trace tests cover JIT/AOT and are not skipped except on configurations that really don't make sense. Possibly the status file needs some cleanup.

**Comment by cskau-g** [comment]
I've cleaned up the status files and it looks like things are running as intended.
