### ISSUE TITLE
analyzer issue

### ISSUE THREAD

**Issue by boudgeau** [dart-lang/sdk#41830]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.1.0-edge.8a919426f0e8665a0e6b01c2fcf3113587f8b040`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.1.0-edge.8a919426f0e8665a0e6b01c2fcf3113587f8b040, server version 1.20.5, error: Analysis failed: C:\xampp\htdocs\ninja\flutter-client\lib\constants.dart context: exception_20200510_031021_069
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new LibraryContext.forSingleLibrary.<anonymous closure>.appendLibraryFiles (package:analyzer/src/dart/analysis/library_context.dart:86:42)
#2      new LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:97:27)
#3      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#4      new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:96:14)
#5      PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#6      new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:60:19)
#7      AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1370:16)
<asynchronous suspension>
#8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1234:34)
<asynchronous suspension>
#9      PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1046:39)
<asynchronous suspension>
#12     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#13     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#14     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#15     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#16     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#17     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#23     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#24     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#25     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#26     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#27     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\SAM\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Thanks for reporting this issue. This is a very old version of Dart / Flutter. Please upgrade to a newer version of Dart (or Flutter).
