### ISSUE TITLE
打开项目报错 FileSystemException 

### ISSUE THREAD

**Issue by longqionggaccount** [dart-lang/sdk#41840]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900, 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: FileSystemException(path=/Users/longqiong408/Documents/workspace/HLBOSBusinessSettlementCenter/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/bos_business_settlement_center/example/ios/.symlinks/plugins/flutter_router/example/android/flutter_router_core/src/main/kotlin/com/hellobike/flutter/router/navigator/FRouterDefaultNavigator.; message=Directory listing failed)
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:334:7)
#1      _OverlayFolder.getChildren (package:analyzer/file_system/overlay_file_system.dart:334:10)
#2      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1144:32)
#3      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#4      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#5      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#6      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#7      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#8      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#9      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#10     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#11     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#12     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#13     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#14     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#15     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#16     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#17     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#18     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#19     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#20     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#21     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#22     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#23     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#24     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#25     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#26     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#27     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#28     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#29     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#30     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#31     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#32     ContextManagerImpl._createContext.checkManifestFil...
```

For additional log information, please append the contents of
file:///private/var/folders/rs/k481n4h51r9b4pg37gvs5wfh0000gn/T/report1.txt.

**Comment by srawlins** [comment]
Sorry we did not get to this issue. Closing for now; please open a new issue if you see this in a recent version of Dart.

**Comment by longqionggaccount** [comment]
邮件已收到，谢谢！
