### ISSUE TITLE
Memory leak in Isolate.spawnUri

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#41883]
```
FAILED: dartk-vm release_x64 lib_2/isolate/spawn_uri_nested_vm_test/1
Expected: Pass
Actual: Crash

--- Command "vm" (took 02.000422s):
DART_CONFIGURATION=ReleaseASANX64 out/ReleaseASANX64/dart --no-enable-isolate-groups --ignore-unrecognized-flags --packages=/usr/local/google/home/rmacnak/d\
art3/sdk/.packages /usr/local/google/home/rmacnak/dart3/sdk/tests/lib_2/isolate/spawn_uri_nested_vm_test.dart

exit code:
-6

stdout:
unittest-suite-wait-for-done
[1, 2]
unittest-suite-success

stderr:
=================================================================
==58763==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x56313eb7b43d in operator new(unsigned long) ../recipe_cleanup/clangshYTOG/llvm_build_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-l\
inux-gnu-bins/compiler-rt/lib/asan/asan_new_delete.cpp:99:3
    #1 0x56313eb8aa7a in dart::bin::CreateIsolateGroupAndSetupHelper(bool, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**, int*) .\
./../out/ReleaseASANX64/../../runtime/bin/main.cc:676:25
    #2 0x56313eb8cb1d in dart::bin::CreateIsolateGroupAndSetup(char const*, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**) ../../\
out/ReleaseASANX64/../../runtime/bin/main.cc:727:10
    #3 0x56313ef481bd in dart::SpawnIsolateTask::Run() ../../out/ReleaseASANX64/../../runtime/lib/isolate.cc:308:44
    #4 0x56313f571697 in dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseASANX64/../../runtime/vm/thread_pool.cc:111:15
    #5 0x56313f572d0d in dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseASANX64/../../runtime/vm/thread_pool.cc:275:9
    #6 0x56313f39144e in dart::ThreadStart(void*) ../../out/ReleaseASANX64/../../runtime/vm/os_thread_linux.cc:138:5
    #7 0x7f4580171fb6 in start_thread /build/glibc-oCLvUT/glibc-2.29/nptl/pthread_create.c:486:8

Indirect leak of 58 byte(s) in 1 object(s) allocated from:
    #0 0x56313eb3e8a1 in strdup ../recipe_cleanup/clangshYTOG/llvm_build_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compile\
r-rt/lib/asan/asan_interceptors.cpp:452:3
    #1 0x56313ec141f4 in dart::bin::IsolateData::IsolateData(dart::bin::IsolateGroupData*) ../../out/ReleaseASANX64/../../runtime/bin/isolate_data.cc:43:22
    #2 0x56313eb8aa89 in dart::bin::CreateIsolateGroupAndSetupHelper(bool, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**, int*) .\
./../out/ReleaseASANX64/../../runtime/bin/main.cc:676:29
    #3 0x56313eb8cb1d in dart::bin::CreateIsolateGroupAndSetup(char const*, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**) ../../\
out/ReleaseASANX64/../../runtime/bin/main.cc:727:10
    #4 0x56313ef481bd in dart::SpawnIsolateTask::Run() ../../out/ReleaseASANX64/../../runtime/lib/isolate.cc:308:44
    #5 0x56313f571697 in dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseASANX64/../../runtime/vm/thread_pool.cc:111:15
    #6 0x56313f572d0d in dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseASANX64/../../runtime/vm/thread_pool.cc:275:9
    #7 0x56313f39144e in dart::ThreadStart(void*) ../../out/ReleaseASANX64/../../runtime/vm/os_thread_linux.cc:138:5
    #8 0x7f4580171fb6 in start_thread /build/glibc-oCLvUT/glibc-2.29/nptl/pthread_create.c:486:8

SUMMARY: AddressSanitizer: 82 byte(s) leaked in 2 allocation(s).

--- Re-run this test:
python tools/test.py -n dartk-asan-linux-release-x64 lib_2/isolate/spawn_uri_nested_vm_test/1
```

Maybe the isolate cleanup callback not being called if isolate spawn is interrupted?

**Comment by mkustermann** [comment]
Has this been fixed? When I run this locally asan doesn't seem to report leaks.

**Comment by a-siva** [comment]
I did a query of the test results database to see if this test existed as an approved failure and it does show up in the query:

```

builder_name | suite | test_name | expected | unexpected_result | flaky
	
vm-kernel-asan-linux-release-x64 lib_2 isolate/spawn_uri_nested_vm_test/0 Pass null true
vm-kernel-asan-linux-release-x64 lib_2 isolate/spawn_uri_nested_vm_test/1 Pass Crash true

```

It is marked as flaky probably explaining why it doesn't reproduce easily when run locally.

**Comment by mkustermann** [comment]
After looking for some time, I managed to reproduce it by adding the following change:
```diff
diff --git a/runtime/vm/isolate.cc b/runtime/vm/isolate.cc
index 8993e5f3855..9335b5981d8 100644
--- a/runtime/vm/isolate.cc
+++ b/runtime/vm/isolate.cc
@@ -1894,6 +1894,7 @@ Isolate* Isolate::InitIsolate(const char* name_prefix,
   }
 
   // Add to isolate list. Shutdown and delete the isolate on failure.
+  sleep(1);
   if (!TryMarkIsolateReady(result)) {
     result->LowLevelShutdown();
     Isolate::LowLevelCleanup(result);
```

Will fix it.
