### ISSUE TITLE
[analysis_server_client] ServerLogParams throws

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#42012]
1. subscribe to log events
2. request diagnostic.getServerPort
3. handle notifications via NotificationHandler

```
flutter: RECEIVED: {"event":"server.log","params":{"time":1590057796995,"kind":"REQUEST","data":{"id":"3","method":"diagnostic.getServerPort"},"sdkVersion":"2.9.0-7.0.dev.flutter-39e0e75fcf"}}
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Exception: Expected entry at params
#0      new ServerLogParams.fromJson (package:analysis_server_client/src/protocol/protocol_generated.dart:20583:9)
#1      NotificationHandler.handleEvent (package:analysis_server_client/handler/notification_handler.dart:103:37)
#2      ServerBase.outputProcessor (package:analysis_server_client/src/server_base.dart:154:32)
#3      AnalyzerBox.make.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:services/algebras/implementation/services/analyzer.dart:45:18)
#4      _rootRunUnary (dart:async/zone.dart:1192:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#9      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#10     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#11     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#12     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#13     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#14     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#15     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#16     _rootRunUnary (dart:async/zone.dart:1192:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#25     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:315:20)
#26     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:308:5)
#27     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#28     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#29     _rootRunUnary (dart:async/zone.dart:1192:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#34     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#35     _StreamController._add (dart:async/stream_controller.dart:655:7)
#36     _StreamController.add (dart:async/stream_controller.dart:597:5)
#37     _Socket._onData (dart:io-patch/socket_patch.dart:1989:41)
#38     _rootRunUnary (dart:async/zone.dart:1196:13)
#39     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#43     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#44     _StreamController._add (dart:async/stream_controller.dart:655:7)
#45     _StreamController.add (dart:async/stream_controller.dart:597:5)
#46     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1534:33)
#47     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1036:14)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)

```

**Comment by modulovalue** [comment]
my mistake
