### ISSUE TITLE
dart2js crash on generic closure

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#42016]
The following program crashes the dart2js compiler with the error message enclosed below.  This is a smaller reproduction of a failure on tests about to land [here](https://dart-review.googlesource.com/c/sdk/+/148582).

```dart
import 'dart:async';

class A {
  Function 
      i1<R>() => <T0 extends FutureOr<R>>() {};
}

void main() {
  var n = A();
  print(n.i1<Never>().runtimeType);
}
```

```
leafp-macbookpro:sdk leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dart2js --enable-experiment=non-nullable  --null-safety -o out.js ~/tmp/test.dart
../../../tmp/test.dart:5:7:
Internal Error: Runtime type information not available for type_variable_local(j:type_variable(i1.R)) in (j:anonymous_closure_local(A_i1_closure)) for j:signature(A_i1_closure.:signature).
      i1<R>() => <T0 extends FutureOr<R>>() {};
      ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.9.0-edge.dc1d7c87205d8ebb8c3361417b8911a40b2d95ee), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Unhandled exception:
Assertion failure: Runtime type information not available for type_variable_local(j:type_variable(i1.R)) in (j:anonymous_closure_local(A_i1_closure)) for j:signature(A_i1_closure.:signature).
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      LocalsHandler.readLocal (package:compiler/src/ssa/locals_handler.dart:326:11)
#2      TypeBuilder._buildEnvironmentForType (package:compiler/src/ssa/type_builder.dart:398:12)
#3      TypeBuilder.analyzeTypeArgumentNewRti (package:compiler/src/ssa/type_builder.dart:316:9)
#4      TypeBuilder.analyzeTypeArgument (package:compiler/src/ssa/type_builder.dart:275:14)
#5      KernelSsaGraphBuilder._computeTypeArgumentDefaultValue (package:compiler/src/ssa/builder_kernel.dart:6125:27)
#6      KernelSsaGraphBuilder._addFunctionTypeVariablesIfNeeded (package:compiler/src/ssa/builder_kernel.dart:711:17)
#7      KernelSsaGraphBuilder._openFunction (package:compiler/src/ssa/builder_kernel.dart:1702:5)
#8      KernelSsaGraphBuilder._buildMethodSignatureNewRti (package:compiler/src/ssa/builder_kernel.dart:1279:5)
#9      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:533:13)
#10     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#11     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:451:21)
#12     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:516:22)
#13     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#14     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:498:18)
#15     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:356:21)
#16     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:80:29)
#17     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:453:30)
#18     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:334:43)
#19     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:465:29)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:70)
#21     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:32)
#23     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#24     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:28)
#25     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#26     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:456:18)
#27     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:266:12)
#28     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:282:5)
#29     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:452:16)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#31     Compiler.emptyQueue (package:compiler/src/compiler.dart:451:14)
#32     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:477:7)
#33     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#34     Compiler.processQueue (package:compiler/src/compiler.dart:470:14)
#35     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:382:5)
#36     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:284:9)
#37     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:432:9)
#38     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#39     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#40     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#41     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#42     new Future.sync (dart:async/future.dart:222:31)
#43     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#44     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#45     Compiler.run (package:compiler/src/compiler.dart:209:41)
#46     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#47     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#50     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#51     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#52     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#53     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#54     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#55     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
leafp-macbookpro:sdk leafp$ 
```

**Comment by sigmundch** [comment]
Just tested with the latest version of dart2js and this is already fixed.
