### ISSUE TITLE
dart2js crashes

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42055]
Cf.  https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8879650327866026080/+/steps/test_results/0/logs/new_test_failures__logs_/0, dart2js-hostasserts-strong-linux-x64-d8 crashes on 'conditional_import_test', and so does dart2js-hostasserts-weak-linux-x64-d8.

```
stderr:
Unhandled exception:
Assertion failure
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      Collector.computeNeededDeclarations (package:compiler/src/js_emitter/program_builder/collector.dart:227:55)
#2      Collector.collect (package:compiler/src/js_emitter/program_builder/collector.dart:323:5)
#3      ProgramBuilder.buildProgram (package:compiler/src/js_emitter/program_builder/program_builder.dart:178:15)
#4      EmitterImpl.emitProgram.<anonymous closure> (package:compiler/src/js_emitter/startup_emitter/emitter.dart:197:29)
#5      CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#6      EmitterImpl.emitProgram (package:compiler/src/js_emitter/startup_emitter/emitter.dart:196:29)
#7      CodeEmitterTask.assembleProgram.<anonymous closure> (package:compiler/src/js_emitter/code_emitter_task.dart:150:26)
#8      CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#9      CodeEmitterTask.assembleProgram (package:compiler/src/js_emitter/code_emitter_task.dart:119:12)
#10     JsBackendStrategy.assembleProgram (package:compiler/src/js_model/js_strategy.dart:374:35)
#11     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:390:39)
#12     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:284:9)
#13     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:432:9)
#14     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#15     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#16     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
```

Similarly for 'generic_function_type_object_normalization_test' and 'type_object_normalization_test', e.g.:

```
stdout:
tests/language/nnbd/normalization/generic_function_type_object_normalization_test.dart:150:12:
Internal Error: Runtime type information not available for type_variable_local(j:type_variable(i1.R)) in (j:anonymous_closure_local(NeverTests_i1_closure)) for j:signature(NeverTests_i1_closure.:signature).
  Function i1<R>() =>
           ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

stderr:
Unhandled exception:
Assertion failure: Runtime type information not available for type_variable_local(j:type_variable(i1.R)) in (j:anonymous_closure_local(NeverTests_i1_closure)) for j:signature(NeverTests_i1_closure.:signature).
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      LocalsHandler.readLocal (package:compiler/src/ssa/locals_handler.dart:326:11)
#2      TypeBuilder._buildEnvironmentForType (package:compiler/src/ssa/type_builder.dart:398:12)
#3      TypeBuilder.analyzeTypeArgumentNewRti (package:compiler/src/ssa/type_builder.dart:316:9)
#4      TypeBuilder.analyzeTypeArgument (package:compiler/src/ssa/type_builder.dart:275:14)
#5      KernelSsaGraphBuilder._computeTypeArgumentDefaultValue (package:compiler/src/ssa/builder_kernel.dart:6125:27)
#6      KernelSsaGraphBuilder._addFunctionTypeVariablesIfNeeded (package:compiler/src/ssa/builder_kernel.dart:711:17)
#7      KernelSsaGraphBuilder._openFunction (package:compiler/src/ssa/builder_kernel.dart:1702:5)
#8      KernelSsaGraphBuilder._buildMethodSignatureNewRti (package:compiler/src/ssa/builder_kernel.dart:1279:5)
#9      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:533:13)
#10     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#11     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:451:21)
#12     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:516:22)
#13     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#14     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:498:18)
#15     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:356:21)
#16     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:80:29)
#17     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:453:30)
#18     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:334:43)
#19     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:465:29)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:70)
#21     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:32)
#23     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#24     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:28)
#25     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#26     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:456:18)
#27     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:266:12)
#28     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:282:5)
#29     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:452:16)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#31     Compiler.emptyQueue (package:compiler/src/compiler.dart:451:14)
#32     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:477:7)
#33     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#34     Compiler.processQueue (package:compiler/src/compiler.dart:470:14)
#35     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:382:5)
#36     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:284:9)
#37     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:432:9)
#38     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#39     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#40     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
```

**Comment by sigmundch** [comment]
the tests mentioned above are now passing, so we can close this issue now.
