### ISSUE TITLE
[vm] Misleading stack traces in product mode

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#42062]
Consider the following test:

```dart

void foo() async {
  await foo2();
}

void foo2() async {
  await foo3();
}

void foo3() async {
}

void bar() async {
  await bar2();
}

void bar2() async {
  throw 'error';
}

main() async {
  await foo();
  await bar();
}
```

Running it on the standalone VM built in product mode produces the following stack trace:

```
tools/build.py -a x64 -m product runtime
out/ProductX64/dart foo.dart

Unhandled exception:
error
#0      bar2 (file:///.../foo.dart:18:3)
#1      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:55:6)
#2      bar2 (file:///.../foo.dart:17:10)
#3      bar (file:///.../foo.dart:14:9)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:55:6)
#5      bar (file:///.../foo.dart:13:9)
#6      main (file:///.../foo.dart:23:9)
#7      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#14     foo (file:///.../foo.dart)
#15     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#22     foo2 (file:///.../foo.dart)
#23     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#28     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

The fact that stack trace mentions `foo` (`#14`) and `foo2` (`#22`) is very misleading as they are not callers of `bar` which raised the exception.

This behavior is only visible in product mode because `causal_async_stacks` flag is disabled in product mode.

For comparison, the following is printed by the VM in debug/release mode or with `--causal_async_stacks`:

```
#0      bar2 (file:///.../foo.dart:18:3)
#1      bar (file:///.../foo.dart:14:9)
#2      main (file:///.../foo.dart:23:9)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

The following is printed with `--lazy_async_stacks`:
```
#0      bar2 (file:///usr/local/google/home/alexmarkov/work/dart/sdk/foo.dart:18:3)
#1      bar (file:///usr/local/google/home/alexmarkov/work/dart/sdk/foo.dart:14:9)
#2      main (file:///usr/local/google/home/alexmarkov/work/dart/sdk/foo.dart:23:9)
<asynchronous suspension>
```

We might consider enabling `--lazy_async_stacks` or `--causal_async_stacks` by default in product VM to fix this issue.

/cc @rmacnak-google @mkustermann @cskau-g

**Comment by mkustermann** [comment]
> We might consider enabling --lazy_async_stacks or --causal_async_stacks by default in product VM to fix this issue.

That has been the plan all along. There are a few missing pieces that we'd like to do first. @cskau-g is going to drive this.
