### ISSUE TITLE
Permissive mode exception when migrating package:path

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42139]
Using SDK as of 609c0d35eb84005a84c1de7d0c34c870dc509134, and package:path source as of https://github.com/dart-lang/path/commit/10c778c799b2fc06036cbd0aa0e399ad4eb1ff5b, attemting to migrate package:path results in an exception.

Due to #42138, you can't see the exception itself, however I was able to see what it is by by adding a print statement to `DartFixListener.addDetail`.  The exception is:

```
NoSuchMethodError: The getter 'typeProvider' was called on null.
Receiver: null
Tried calling: typeProvider

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Member._toLegacyType (package:analyzer/src/dart/element/member.dart:623:46)
#2      VariableMember.type (package:analyzer/src/dart/element/member.dart:1070:13)
#3      ResolverVisitor.visitIndexExpression (package:analyzer/src/generated/resolver.dart:1233:57)
#4      IndexExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5955:49)
#5      AssignmentExpressionResolver.resolve (package:analyzer/src/dart/resolver/assignment_expression_resolver.dart:60:11)
#6      ResolverVisitor.visitAssignmentExpression (package:analyzer/src/generated/resolver.dart:635:35)
#7      AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:725:49)
#8      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3706:18)
#9      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#10     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3214:59)
#11     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3702:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#13     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1083:17)
#14     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#15     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#16     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2074:13)
#17     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1079:49)
#18     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1038:13)
#19     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#20     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3131:55)
#21     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2085:13)
#22     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:657:13)
#23     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1034:49)
#24     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5006:12)
#25     FunctionExpressionResolver.resolve (package:analyzer/src/dart/resolver/function_expression_resolver.dart:67:10)
#26     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:1097:37)
#27     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5000:49)
#28     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#29     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:363:16)
#30     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#31     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:3107:45)
#32     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:596:11)
#33     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:359:49)
#34     InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:329:18)
#35     InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:369:7)
#36     InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:347:7)
#37     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:256:5)
#38     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:786:24)
#39     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:494:16)
#40     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:91:7)
#41     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:478:31)
#42     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7148:49)
#43     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1326:10)
#44     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7148:49)
#45     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3706:18)
#46     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#47     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3214:59)
#48     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3702:49)
#49     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#50     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1083:17)
#51     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#52     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#53     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2074:13)
#54     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1079:49)
#55     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1038:13)
#56     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#57     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3131:55)
#58     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2085:13)
#59     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:657:13)
#60     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1034:49)
#61     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5006:12)
#62     FunctionExpressionResolver.resolve (package:analyzer/src/dart/resolver/function_expression_resolver.dart:67:10)
#63     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:1097:37)
#64     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5000:49)
#65     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#66     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:363:16)
#67     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#68     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:3107:45)
#69     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:596:11)
#70     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:359:49)
#71     InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:329:18)
#72     InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:369:7)
#73     InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:347:7)
#74     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:256:5)
#75     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:786:24)
#76     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:494:16)
#77     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:91:7)
#78     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:478:31)
#79     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7148:49)
#80     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1326:10)
#81     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7148:49)
#82     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3706:18)
#83     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#84     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3214:59)
#85     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3702:49)
#86     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#87     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1083:17)
#88     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#89     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#90     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2074:13)
#91     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1079:49)
#92     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1038:13)
#93     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#94     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3131:55)
#95     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2085:13)
#96     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:657:13)
#97     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1034:49)
#98     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5006:12)
#99     FunctionExpressionResolver.resolve (package:analyzer/src/dart/resolver/function_expression_resolver.dart:67:10)
#100    ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:1091:35)
#101    FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5000:49)
#102    FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4863:26)
#103    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1367:10)
#104    UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3256:59)
#105    ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:2416:11)
#106    ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:1081:11)
#107    ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:2409:7)
#108    ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:1050:11)
#109    FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4856:49)
#110    ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:754:23)
#111    CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2125:49)
#112    FixBuilder.visitAll.<anonymous closure> (package:nnbd_migration/src/fix_builder.dart:189:14)
#113    _rootRun (dart:async/zone.dart:1190:13)
#114    _CustomZone.run (dart:async/zone.dart:1093:19)
#115    _runZoned (dart:async/zone.dart:1630:10)
#116    runZoned (dart:async/zone.dart:1550:10)
#117    NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#118    FixBuilder.visitAll (package:nnbd_migration/src/fix_builder.dart:186:35)
#119    NullabilityMigrationImpl.finalizeInput (package:nnbd_migration/src/nullability_migration_impl.dart:128:18)
#120    NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:233:19)
#121    _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:830:21)
#122    _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:778:30)
<asynchronous suspension>
#123    _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:828:13)
<asynchronous suspension>
#124    MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart:401:45)
<asynchronous suspension>
#125    MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart)
#126    MigrationCli._withProgress (package:nnbd_migration/migration_cli.dart:627:21)
#127    MigrationCli.run (package:nnbd_migration/migration_cli.dart:371:11)
#128    main (file:///usr/local/google/home/paulberry/dart1/sdk/pkg/nnbd_migration/bin/migrate.dart:18:39)
#129    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#130    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by stereotype441** [comment]
I've narrowed this down to a short repro:
```dart
abstract class M<V> implements Map<String, V> {}
void f(M<int> m) {
  m['one'] = 1;
}
```
I believe what's happening is the FixBuilder needs to inject some information into `LibraryElementImpl.isNonNullableByDefault` so that it will know that the library is question is being analyzed as though it's already been migrated.  This will make `Member._toLegacyType` essentially a no-op, so it won't hit the code path that leads to the exception.

We're doing similar injection elsewhere in the FixBuilder, so I think this should be fairly straightforward.  Working on a fix now.

**Comment by stereotype441** [comment]
I have a fix awaiting code review: https://dart-review.googlesource.com/c/sdk/+/150260
