### ISSUE TITLE
Permissive mode exception leads to UnimplementedError in DartFixListener.addDetail

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42138]
As of 609c0d35eb84005a84c1de7d0c34c870dc509134, if a permissive mode exception happens when running migration, the error message the user sees is:

```
UnimplementedError: TODO(paulberry)
#0      DartFixListener.addDetail (package:nnbd_migration/src/front_end/dartfix_listener.dart:23:5)
#1      NullabilityMigrationAdapter.reportException (package:nnbd_migration/src/front_end/non_nullable_fix.dart:338:14)
#2      FixBuilder.visitAll (package:nnbd_migration/src/fix_builder.dart:194:18)
#3      NullabilityMigrationImpl.finalizeInput (package:nnbd_migration/src/nullability_migration_impl.dart:128:18)
#4      NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:233:19)
#5      _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:830:21)
#6      _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:778:30)
<asynchronous suspension>
#7      _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:828:13)
<asynchronous suspension>
#8      MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart:401:45)
<asynchronous suspension>
#9      MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart)
#10     MigrationCli._withProgress (package:nnbd_migration/migration_cli.dart:627:21)
#11     MigrationCli.run (package:nnbd_migration/migration_cli.dart:371:11)
#12     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:205:15)
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#14     DartdevRunner.runCommand (package:dartdev/dartdev.dart:62:24)
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#16     new Future.sync (dart:async/future.dart:222:31)
#17     CommandRunner.run (package:args/command_runner.dart:112:14)
#18     main (file:///usr/local/google/home/paulberry/dart-new/sdk/pkg/dartdev/bin/dartdev.dart:14:35)
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by stereotype441** [comment]
Note that at the same time as we fix this, it would be nice to add an implementation of `DartFixListener.addRecommendation`, and then use it for reporting package config exceptions. 
 See TODO comment in https://dart-review.googlesource.com/c/sdk/+/149611.
