### ISSUE TITLE
Migration tool should show a more useful error when there are multiple analysis contexts

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42141]
If migration is attempted on a directory containing multiple analysis contexts, the following exception occurs:

```
Generating migration suggestions...
Bad state: Too many elements
#0      List.single (dart:core-patch/growable_array.dart:237:5)
#1      MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart:378:38)
#2      MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart:372:67)
#3      MigrationCli._withProgress (package:nnbd_migration/migration_cli.dart:627:21)
#4      MigrationCli.run (package:nnbd_migration/migration_cli.dart:371:11)
#5      MigrateCommand.run (package:nnbd_migration/migration_cli.dart:205:15)
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#7      DartdevRunner.runCommand (package:dartdev/dartdev.dart:62:24)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:222:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     main (file:///usr/local/google/home/paulberry/dart-new/sdk/pkg/dartdev/bin/dartdev.dart:14:35)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

In an ideal world the migration tool would be able to handle multiple analysis contexts, however at a minimum we should output a helpful error message to the user rather than crashing.

(See #42140 for one way of reproducing this error)

**Comment by devoncarew** [comment]
This will be addressed by https://dart-review.googlesource.com/c/sdk/+/149664.

**Comment by stereotype441** [comment]
Reopening since the fix was reverted

**Comment by devoncarew** [comment]
re-fixed in https://dart-review.googlesource.com/c/sdk/+/149889
