### ISSUE TITLE
Migration tool encounters assertion failures when attempting to migrate dartdoc

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42142]
Using SDK as of 609c0d35eb84005a84c1de7d0c34c870dc509134, and package:dartdoc source as of https://github.com/dart-lang/dartdoc/commit/1196ef0fddde3f2ac618159d63bddeee487e639c, attempting to migrate package:dartdoc with assertions enabled results in an exception.

To enable assertions while running migration, you need to run it from source, e.g. if `$SDK` is the path to your checkout of the SDK, using: `$SDK/out/ReleaseX64/dart-sdk/bin/dart --enable-asserts $SDK/pkg/nnbd_migration/bin/migrate.dart --skip-pub-outdated`.

The assertion failure looks like this:

```
Unhandled exception:
'package:nnbd_migration/src/front_end/migration_info.dart': Failed assertion: line 115 pos 16: 'offset >= 0': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      new NavigationRegion (package:nnbd_migration/src/front_end/migration_info.dart:115:16)
#3      new NavigationTarget (package:nnbd_migration/src/front_end/migration_info.dart:136:9)
#4      InfoBuilder._targetForRawTarget (package:nnbd_migration/src/front_end/info_builder.dart:441:18)
#5      InfoBuilder._computeNavigationSources.<anonymous closure> (package:nnbd_migration/src/front_end/info_builder.dart:227:18)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#7      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#8      new List.from (dart:core-patch/array_patch.dart:38:29)
#9      new List.of (dart:core-patch/array_patch.dart:68:17)
#10     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#11     InfoBuilder._computeNavigationSources (package:nnbd_migration/src/front_end/info_builder.dart:232:8)
#12     InfoBuilder._explainUnit (package:nnbd_migration/src/front_end/info_builder.dart:312:26)
#13     InfoBuilder.explainMigration (package:nnbd_migration/src/front_end/info_builder.dart:82:22)
<asynchronous suspension>
#14     MigrationState.refresh (package:nnbd_migration/src/front_end/migration_state.dart:60:39)
#15     NonNullableFix.finish (package:nnbd_migration/src/front_end/non_nullable_fix.dart:102:17)
#16     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:833:17)
<asynchronous suspension>
#17     MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart:401:45)
<asynchronous suspension>
#18     MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart)
#19     MigrationCli._withProgress (package:nnbd_migration/migration_cli.dart:627:21)
#20     MigrationCli.run (package:nnbd_migration/migration_cli.dart:371:11)
#21     main (file:///usr/local/google/home/paulberry/dart1/sdk/pkg/nnbd_migration/bin/migrate.dart:18:39)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by srawlins** [comment]
We've migrated; if a similar crash occurs migrating other code, a new bug should be filed.
