### ISSUE TITLE
Migration tool not respecting exclude directives in analysis_options.yaml on Windows

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42140]
Using SDK as of 609c0d35eb84005a84c1de7d0c34c870dc509134, and package:dartdoc source as of https://github.com/dart-lang/dartdoc/commit/1196ef0fddde3f2ac618159d63bddeee487e639c, attempting to migrate package:dartdoc on Windows results in an exception.

The exception can be reproduced on Linux by commenting out three lines from the `exclude` list in dartdoc's `analysis_options.yaml` file:

```diff
diff --git a/analysis_options.yaml b/analysis_options.yaml
index d7d1a23a..f360d4a0 100644
--- a/analysis_options.yaml
+++ b/analysis_options.yaml
@@ -11,9 +11,9 @@ analyzer:
     - 'lib/src/third_party/pkg/**'
     - 'lib/templates/*.html'
     - 'pub.dartlang.org/**'
-    - 'testing/**'
-    - 'testing/test_package_flutter_plugin/**'
-    - 'testing/test_package_export_error/**'
+#    - 'testing/**'
+#    - 'testing/test_package_flutter_plugin/**'
+#    - 'testing/test_package_export_error/**'
 linter:
   rules:
     - always_declare_return_types
```

The exception is:
```
Generating migration suggestions...
Bad state: Too many elements
#0      List.single (dart:core-patch/growable_array.dart:237:5)
#1      MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart:378:38)
#2      MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart:372:67)
#3      MigrationCli._withProgress (package:nnbd_migration/migration_cli.dart:627:21)
#4      MigrationCli.run (package:nnbd_migration/migration_cli.dart:371:11)
#5      MigrateCommand.run (package:nnbd_migration/migration_cli.dart:205:15)
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#7      DartdevRunner.runCommand (package:dartdev/dartdev.dart:62:24)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:222:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     main (file:///usr/local/google/home/paulberry/dart-new/sdk/pkg/dartdev/bin/dartdev.dart:14:35)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

The fact that the bug can be reproduced on Linux by commenting out exclude directives suggests that these directives aren't working properly on Linux.

Note that there are other known problems with exclude directives, e.g. #25551, but I'm not marking this as a duplicate because this is a Windows-specific bug, and the other bugs (to my knowledge) are not Windows-specific.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
