### ISSUE TITLE
Crash analyzing null-aware operator on class with NNBD

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#42178]
Given:

```dart
class C {
  static void m() {}
}

main() {
  C?.m();
}
```

If I run:

```sh
$ dartanalyzer --enable-experiment=non-nullable temp.dart
```

I get:

```
Analyzing /Users/rnystrom/Documents/temp.dart...
Unhandled exception:
NoSuchMethodError: The getter 'isDynamic' was called on null.
Receiver: null
Tried calling: isDynamic
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      TypeSystem.isStrictlyNonNullable (package:analyzer/src/generated/type_system.dart:205:14)
#2      ErrorVerifier._checkForUnnecessaryNullAware (package:analyzer/src/generated/error_verifier.dart:4396:21)
#3      ErrorVerifier.visitMethodInvocation (package:analyzer/src/generated/error_verifier.dart:917:7)
#4      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7148:49)
#5      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3706:18)
#6      RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:833:10)
#7      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3702:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#9      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1083:17)
#10     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#11     ErrorVerifier.visitBlock (package:analyzer/src/generated/error_verifier.dart:392:13)
#12     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1079:49)
#13     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1038:13)
#14     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#15     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1034:49)
#16     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5006:12)
#17     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:923:10)
#18     ErrorVerifier.visitFunctionExpression (package:analyzer/src/generated/error_verifier.dart:723:13)
#19     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5000:49)
#20     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4863:26)
#21     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:911:10)
#22     ErrorVerifier.visitFunctionDeclaration.<anonymous closure> (package:analyzer/src/generated/error_verifier.dart:710:13)
#23     ErrorVerifier._withEnclosingExecutable (package:analyzer/src/generated/error_verifier.dart:5278:16)
#24     ErrorVerifier.visitFunctionDeclaration (package:analyzer/src/generated/error_verifier.dart:688:5)
#25     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4856:49)
#26     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#27     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2132:21)
#28     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#29     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:490:11)
#30     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2125:49)
#31     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:386:10)
#32     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:160:9)
#33     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#34     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:159:13)
#35     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#36     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:158:34)
#37     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:116:14)
#38     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#39     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:115:43)
#40     AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1310:63)
#41     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#42     AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1286:20)
#43     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1237:14)
#44     _rootRun (dart:async/zone.dart:1190:13)
#45     _CustomZone.run (dart:async/zone.dart:1093:19)
#46     _runZoned (dart:async/zone.dart:1630:10)
#47     runZoned (dart:async/zone.dart:1550:10)
#48     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#49     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1236:40)
#50     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:562:41)
#51     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:49)
<asynchronous suspension>
#52     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#53     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#54     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:627:21)
#55     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:352:30)
#56     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#57     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#58     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#59     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#60     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:393:9)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#63     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#64     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

#0      AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1346:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1286:20)
#3      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1237:14)
#4      _rootRun (dart:async/zone.dart:1190:13)
#5      _CustomZone.run (dart:async/zone.dart:1093:19)
#6      _runZoned (dart:async/zone.dart:1630:10)
#7      runZoned (dart:async/zone.dart:1550:10)
#8      NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#9      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1236:40)
#10     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:562:41)
#11     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:49)
<asynchronous suspension>
#12     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#13     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#14     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:627:21)
#15     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:352:30)
#16     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:393:9)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

(The irony of this being a null reference exception is not lost on me. :) )

**Comment by munificent** [comment]
cc @stereotype441 and @scheglov.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/150184
