### ISSUE TITLE
dart2js crashes when using IndexedDB & -O0

### ISSUE THREAD

**Issue by OnAirNetlines** [dart-lang/sdk#42189]
Hello Dartisans!
I have just found a compiler crash in Dart whenever I'm using dart2js with -O0 flag. If I use -O1 or -O2 flag however, the same program compiles.

**OS:** Linux x64
**Installation method:** ZIP file

**Issue is not present in dart version 2.7.2**

_Issue is present in dart version 2.8.1, 2.8.4 & 2.9.0-13.0.dev_

### Code that triggers the issue (bug.dart)
```dart
import "dart:indexed_db" show VersionChangeEvent, Database, Transaction, ObjectStore, CursorWithValue, Request, Cursor;
import "dart:html" show window;

void main() async {
  Database recordingsDatabase = await window.indexedDB.open(
      "recordings",
      version: 1
    );  
}
```

### Stack trace (v2.8.4)
Command:
dart2js -O0 --packages=.packages web/bug.dart --out=web/bug.dart.js

```
org-dartlang-sdk:///sdk/lib/indexed_db/dart2js/indexed_db_dart2js.dart@15440+1:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.8.4), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Unhandled exception:
type 'HAsCheck' is not a subtype of type 'HLocalValue'
#0      HLocalGet.local (package:compiler/src/ssa/nodes.dart:2285:28)
#1      SsaInstructionMerger.isEffectivelyPure (package:compiler/src/ssa/codegen_helpers.dart:770:71)
#2      SsaInstructionMerger.analyzeInputs (package:compiler/src/ssa/codegen_helpers.dart:737:13)
#3      SsaInstructionMerger.visitInstruction (package:compiler/src/ssa/codegen_helpers.dart:789:5)
#4      HBaseVisitor.visitInvokeBinary (package:compiler/src/ssa/nodes.dart:429:44)
#5      HBaseVisitor.visitRelational (package:compiler/src/ssa/nodes.dart:436:40)
#6      HBaseVisitor.visitIdentity (package:compiler/src/ssa/nodes.dart:486:36)
#7      SsaInstructionMerger.visitIdentity (package:compiler/src/ssa/codegen_helpers.dart:843:13)
#8      HIdentity.accept (package:compiler/src/ssa/nodes.dart:3119:39)
#9      SsaInstructionMerger.analyzeInputs (package:compiler/src/ssa/codegen_helpers.dart:757:19)
#10     SsaInstructionMerger.visitInstruction (package:compiler/src/ssa/codegen_helpers.dart:789:5)
#11     HBaseVisitor.visitInvokeBinary (package:compiler/src/ssa/nodes.dart:429:44)
#12     HBaseVisitor.visitRelational (package:compiler/src/ssa/nodes.dart:436:40)
#13     HBaseVisitor.visitIdentity (package:compiler/src/ssa/nodes.dart:486:36)
#14     SsaInstructionMerger.visitIdentity (package:compiler/src/ssa/codegen_helpers.dart:843:13)
#15     HIdentity.accept (package:compiler/src/ssa/nodes.dart:3119:39)
#16     SsaInstructionMerger.analyzeInputs (package:compiler/src/ssa/codegen_helpers.dart:757:19)
#17     SsaInstructionMerger.visitInstruction (package:compiler/src/ssa/codegen_helpers.dart:789:5)
#18     HBaseVisitor.visitNot (package:compiler/src/ssa/nodes.dart:537:26)
#19     HNot.accept (package:compiler/src/ssa/nodes.dart:2990:39)
#20     SsaInstructionMerger.analyzeInputs (package:compiler/src/ssa/codegen_helpers.dart:757:19)
#21     SsaInstructionMerger.visitInstruction (package:compiler/src/ssa/codegen_helpers.dart:789:5)
#22     HBaseVisitor.visitControlFlow (package:compiler/src/ssa/nodes.dart:434:42)
#23     HBaseVisitor.visitConditionalBranch (package:compiler/src/ssa/nodes.dart:433:54)
#24     HBaseVisitor.visitIf (package:compiler/src/ssa/nodes.dart:488:24)
#25     HIf.accept (package:compiler/src/ssa/nodes.dart:2906:39)
#26     SsaInstructionMerger.tryMergingExpressions (package:compiler/src/ssa/codegen_helpers.dart:944:16)
#27     SsaInstructionMerger.visitBasicBlock (package:compiler/src/ssa/codegen_helpers.dart:915:5)
#28     HGraphVisitor.visitDominatorTree (package:compiler/src/ssa/nodes.dart:152:9)
#29     SsaInstructionMerger.visitGraph (package:compiler/src/ssa/codegen_helpers.dart:724:5)
#30     SsaCodeGenerator.preGenerateMethod.runPhase.<anonymous closure> (package:compiler/src/ssa/codegen.dart:382:59)
#31     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#32     SsaCodeGenerator.preGenerateMethod.runPhase (package:compiler/src/ssa/codegen.dart:382:20)
#33     SsaCodeGenerator.preGenerateMethod (package:compiler/src/ssa/codegen.dart:394:13)
#34     SsaCodeGenerator.visitGraph (package:compiler/src/ssa/codegen.dart:463:5)
#35     SsaCodeGeneratorTask.generateMethod.<anonymous closure> (package:compiler/src/ssa/codegen.dart:158:21)
#36     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#37     SsaCodeGeneratorTask.generateMethod (package:compiler/src/ssa/codegen.dart:142:12)
#38     SsaCodeGeneratorTask.generateCode (package:compiler/src/ssa/codegen.dart:98:14)
#39     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:87:38)
#40     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:453:30)
#41     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:333:43)
#42     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:464:29)
#43     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:70)
#44     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#45     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:32)
#46     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#47     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:28)
#48     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#49     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:456:18)
#50     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:266:12)
#51     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:282:5)
#52     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:452:16)
#53     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#54     Compiler.emptyQueue (package:compiler/src/compiler.dart:451:14)
#55     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:477:7)
#56     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#57     Compiler.processQueue (package:compiler/src/compiler.dart:470:14)
#58     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:382:5)
#59     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:284:9)
#60     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:432:9)
#61     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#62     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#63     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#64     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#65     new Future.sync (dart:async/future.dart:224:31)
#66     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#67     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#68     Compiler.run (package:compiler/src/compiler.dart:209:41)
#69     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#70     _RootZone.runUnary (dart:async/zone.dart:1439:54)
#71     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#72     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#73     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#74     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#75     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#76     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#77     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#78     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#79     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

### How I stumbled upon this issue
I discovered this issue when using IndexedDB in my new project. Basically, dart:indexed_db/ObjectStore::openKeyCursor is broken. It should return a Request that, upon success, fills the .value property with a IDBCursor. But instead, as soon as I do `cursorRequest.result as Cursor`, I get that:
```
Uncaught TypeError: Instance of 'IDBCursor': type 'UnknownJavaScriptObject' is not a subtype of type 'Cursor'
```

To debug that problem, I flipped the -O0 switch and here's how I discovered 2 bugs with one program...

Have a nice day!

**Comment by rakudrama** [comment]
I will look at the compiler crash now.

@OnAirNetlines Once that is fixed, how do you reproduce the original error?
If I compile with `-O1`, I don't get the TypeError you describe, but:
"version and onUpgradeNeeded must be specified together"

**Comment by rakudrama** [comment]
Interesting dart2js bug. 4b9c2356e962f1c0d8a5c86b28887ed0d167b981 should fix it.

@OnAirNetlines did you open a separate issue for the IndexedDB problem
