### ISSUE TITLE
[NNBD] Dartanalyzer crash

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42192]
Analyzer with `--enable-experiment=non-nullable` crashes on the following code
```dart
class C {
  static String m() => "id";
}
main() {
  C?.m();
}
```

```
Unhandled exception:
NoSuchMethodError: The getter 'isDynamic' was called on null.
Receiver: null
Tried calling: isDynamic
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      TypeSystem.isStrictlyNonNullable (package:analyzer/src/generated/type_system.dart:205:14)
#2      ErrorVerifier._checkForUnnecessaryNullAware (package:analyzer/src/generated/error_verifier.dart:4396:21)
#3      ErrorVerifier.visitMethodInvocation (package:analyzer/src/generated/error_verifier.dart:917:7)
#4      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7148:49)
#5      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#6      ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:363:16)
#7      RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#8      ErrorVerifier.visitArgumentList (package:analyzer/src/generated/error_verifier.dart:321:11)
#9      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:359:49)
#10     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7155:20)
#11     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1067:10)
#12     ErrorVerifier.visitMethodInvocation (package:analyzer/src/generated/error_verifier.dart:923:11)
#13     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7148:49)
#14     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3706:18)
#15     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:833:10)
#16     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3702:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#18     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1083:17)
#19     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#20     ErrorVerifier.visitBlock (package:analyzer/src/generated/error_verifier.dart:392:13)
#21     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1079:49)
#22     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1038:13)
#23     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#24     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1034:49)
#25     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5006:12)
#26     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:923:10)
#27     ErrorVerifier.visitFunctionExpression (package:analyzer/src/generated/error_verifier.dart:723:13)
#28     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5000:49)
#29     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4863:26)
#30     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:911:10)
#31     ErrorVerifier.visitFunctionDeclaration.<anonymous closure> (package:analyzer/src/generated/error_verifier.dart:710:13)
#32     ErrorVerifier._withEnclosingExecutable (package:analyzer/src/generated/error_verifier.dart:5278:16)
#33     ErrorVerifier.visitFunctionDeclaration (package:analyzer/src/generated/error_verifier.dart:688:5)
#34     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4856:49)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#36     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2132:21)
#37     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#38     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:490:11)
#39     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2125:49)
#40     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:381:10)
#41     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:160:9)
#42     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#43     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:159:13)
#44     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#45     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:158:34)
#46     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:116:14)
#47     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#48     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:115:43)
#49     AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1315:63)
#50     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#51     AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1291:20)
#52     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1242:14)
#53     _rootRun (dart:async/zone.dart:1190:13)
#54     _CustomZone.run (dart:async/zone.dart:1093:19)
#55     _runZoned (dart:async/zone.dart:1630:10)
#56     runZoned (dart:async/zone.dart:1550:10)
#57     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#58     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1241:40)
#59     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:567:41)
#60     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:49)
<asynchronous suspension>
#61     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#62     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#63     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:633:21)
#64     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:353:30)
#65     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#66     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#67     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#68     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#69     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:393:9)
#70     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#71     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#72     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#73     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

#0      AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1351:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1291:20)
#3      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1242:14)
#4      _rootRun (dart:async/zone.dart:1190:13)
#5      _CustomZone.run (dart:async/zone.dart:1093:19)
#6      _runZoned (dart:async/zone.dart:1630:10)
#7      runZoned (dart:async/zone.dart:1550:10)
#8      NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#9      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1241:40)
#10     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:567:41)
#11     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:49)
<asynchronous suspension>
#12     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#13     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#14     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:633:21)
#15     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:353:30)
#16     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:393:9)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
`dartanalyzer version 2.9.0-13.0.dev `

**Comment by scheglov** [comment]
This was fixed in e3c3d4df3233b17250e5444baf7e2cf3e8d70917 as https://github.com/dart-lang/sdk/issues/42178.
