### ISSUE TITLE
CFE: Failures on [Language] Various NNBD Tests.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#42206]
cc @johnniwinther 

There are new test failures on [[Language] Various NNBD Tests.](https://dart-review.googlesource.com/c/sdk/+/150160).

The tests
```
language/closure/param_null_to_object_test RuntimeError (expected Pass)
language/nnbd/const/potentially_constant_types_error_test MissingCompileTimeError (expected Pass)
language/nnbd/const/potentially_constant_types_test CompileTimeError (expected Pass)
language/nnbd/never/never_error_test MissingCompileTimeError (expected Pass)
```
are failing on configurations
```
analyzer-asserts-strong-linux
dart2js-hostasserts-strong-linux-x64-d8
dartdevk-strong-linux-release-chrome
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartkp-strong-linux-release-x64
```

**Comment by johnniwinther** [comment]
Only `language/closure/param_null_to_object_test` is still failing.

**Comment by johnniwinther** [comment]
`language/closure/param_null_to_object_test` is no longer failing.

**Comment by alexmarkov** [comment]
FWIW `language/closure/param_null_to_object_test` is still failing in strong mode on the VM:

```
--- Command "vm" (took 474ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --sound-null-safety --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/language/closure/param_null_to_object_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:698:5)
#1      Expect.isTrue (package:expect/expect.dart:141:5)
#2      main.test (file:///b/s/w/ir/cache/builder/sdk/tests/language/closure/param_null_to_object_test.dart:52:12)
#3      main (file:///b/s/w/ir/cache/builder/sdk/tests/language/closure/param_null_to_object_test.dart:64:7)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartk-strong-linux-release-x64 language/closure/param_null_to_object_test
```

It looks like this test expects closure parameter to be inferred as `Object?`:
```dart
  void test<X extends Null, Y extends Never>() {
    int Function(X) f = (x) => 1; // Runtime type is int Function(Object?)
```

but this is not the case:

```
    function test<X extends core::Null? = core::Null?, Y extends Never = Never>() → void {
      (X%) → core::int f = (X% x) → core::int => 1;
```

Not sure if this is a bug in the test or CFE type inference.

**Comment by johnniwinther** [comment]
Thanks, @alexmarkov,  I'll take a further look into this.
