### ISSUE TITLE
js-interop:

### ISSUE THREAD

**Issue by technokanha** [dart-lang/sdk#42217]
Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
Invalid depfile: D:\jsPackageExapmle\sample_2javascript\.dart_tool\flutter_build\dc46e905574f78c68c9d31664c3779c9\kernel_snapshot.d
Invalid depfile: D:\jsPackageExapmle\sample_2javascript\.dart_tool\flutter_build\dc46e905574f78c68c9d31664c3779c9\kernel_snapshot.d

Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
U
nhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs; messag
e=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      
asFileUri (package:vm/kernel_front_end.dart:599:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:793:21)

<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:546:15)

<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:40:22)
#5      starter (package:flutter_frontend_server/server.dart:178:27)
#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flut
ter_frontend_server/bin/starter.dart:8:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_pa
tch.
dart:168:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by devoncarew** [comment]
@technokanha, I'm not sure what the issue is here. Can you clarify a bit what you were doing and the issue you're seeing? Please also include things like versions used.

If this is a flutter issue, I'd re-file at flutter/flutter. Thanks!

**Comment by natebosch** [comment]
> it sounds like we may want to update the docs for dart:js and related to indicate that they work on the web and not for flutter mobile apps.

I think we should consider this a request for a more descriptive error from the CFE for missing `dart:` imports/exports. Instead of saying `Error: Not found: 'dart:js'` we should say `'dart:js' is not supported on this platform`. Maybe even with a link to some docs about this.

cc @vsmenon 

I don't think it makes sense to try to update docs for each library that has partial platform support.
