### ISSUE TITLE
Handle references without nodes in DartType.toString()

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#42249]
When dumping a partial kernel binary file which references classes not present in that dill file we may need to print `InterfaceType` which contains `Reference className` with `node == null`.

`getClassReferenceFromReference` from `pkg/kernel/lib/text/ast_to_text.dart` explicitly checks if `reference.node != null` and otherwise uses `reference.canonicalName`.

However, when printing `DartType` inside metadata, `DartType.toString()` crashes on such types.

This can be reproduced in the following way:

```dart
main() {
  Map<int, String> x = {};
  x[1] = 'hi';
}
```

```
pkg/vm/tool/gen_kernel --platform=out/ReleaseX64/vm_platform_strong.dill --no-link-platform -o foo.dill foo.dart
tools/sdks/dart-sdk/bin/dart pkg/vm/bin/dump_kernel.dart foo.dill foo.dump
```

```
Reference to dart:core::Map is not bound to an AST node. A class was expected
#0      Reference.asClass (package:kernel/ast.dart:298:7)
#1      InterfaceType.classNode (package:kernel/ast.dart:6960:36)
#2      InterfaceType.toStringInternal (package:kernel/ast.dart:7057:16)
#3      InterfaceType.toString (package:kernel/ast.dart:7030:29)
#4      _StringBase._interpolate (dart:core-patch/string_patch.dart:848:19)
#5      CallSiteAttributesMetadata.toString (package:vm/metadata/call_site_attributes.dart:18:42)
#6      _StringBase._interpolate (dart:core-patch/string_patch.dart:848:19)
#7      Printer.writeMetadata (package:kernel/text/ast_to_text.dart:645:51)
#8      Printer.writeNode (package:kernel/text/ast_to_text.dart:623:9)
#9      Printer.writeExpression (package:kernel/text/ast_to_text.dart:1019:5)
#10     Printer.visitExpressionStatement (package:kernel/text/ast_to_text.dart:1808:5)
#11     ExpressionStatement.accept (package:kernel/ast.dart:5424:43)
#12     Printer.writeNode (package:kernel/text/ast_to_text.dart:626:12)
#13     List.forEach (dart:core-patch/growable_array.dart:289:8)
#14     Printer.writeFunctionBody (package:kernel/text/ast_to_text.dart:786:23)
#15     Printer.writeFunction (package:kernel/text/ast_to_text.dart:751:7)
#16     Printer.visitProcedure (package:kernel/text/ast_to_text.dart:1134:5)
#17     Procedure.accept (package:kernel/ast.dart:2397:40)
#18     Printer.writeNode (package:kernel/text/ast_to_text.dart:626:12)
#19     List.forEach (dart:core-patch/growable_array.dart:289:8)
#20     Printer.writeStandardLibraryContent (package:kernel/text/ast_to_text.dart:463:24)
#21     Printer.writeComponentFile (package:kernel/text/ast_to_text.dart:537:13)
#22     writeComponentToText (package:kernel/kernel.dart:78:8)
#23     main (file:///.../pkg/vm/bin/dump_kernel.dart:55:3)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

`DartType.toString()` used to work in this case. Also, calling `DartType.leakingDebugToString()` instead of `toString()` fixes the problem. However, I'm not sure it makes sense to call `leakingDebugToString()` in order to implement `toString()` in all metadata classes.

It would be useful if `DartType.toString()` would handle references with `node == null`.

@johnniwinther @jensjoha WDYT?

**Comment by johnniwinther** [comment]
I'm working on `toString` currently. I'll ensure that we support references without nodes.

**Comment by johnniwinther** [comment]
The new `toString` has landed so we now handle unbound references.
