### ISSUE TITLE
dart2js: Bug in static type computation

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#42281]
This program crashes under all optimization levels, including `-O0`.

```dart
class ComponentFactory<T> {
  @pragma('dart2js:noInline')
  Type get componentType => T;
}

var mm = {'String': String, 'int': int};
var gf1 = ComponentFactory<int>();
var gf2 = ComponentFactory<dynamic>();
Map<String, ComponentFactory> mf = {'RegExp': ComponentFactory<RegExp>()};

ComponentFactory test(String s, [Map<String, ComponentFactory> mf2]) {
  var f = mf[s];
  if (f == null) {
    var t = mm[s];
    if (mf2 != null) f = mf2[s];
    if (t != null && t != f?.componentType) {
      print('not match $t');
      f = gf2;
    }
  }
  return f;
}

work() {
  Map<String, ComponentFactory> mf2 = {'int': ComponentFactory<num>()};
    
  test('String');
  test('String', mf2);
  test('int');
  test('int', mf2);
  test('RegExp');
  test('RegExp', mf2);
}

main() {
  try {
    work();
  } catch (e, st) {
    print(e);
    print(st);
  }
}
```
`get$componentType` is not in the output.
```
not match String
not match String
not match int
NoSuchMethodError: method not found: 'get$componentType' (f.get$componentType is not a function)
TypeError: f.get$componentType is not a function
    at Object.test (o1.js:3199:15)
    at Object.work (o1.js:3215:9)
    at Object.main (o1.js:3222:11)
    at o1.js:4049:9
    at o1.js:4029:7
    at dartProgram (o1.js:4044:5)
    at o1.js:4051:3

```
Except for `-O0`, the inferred type of the call to `get$componentType` is 'empty'.
Program runs as expected on Dart VM.

**Comment by rakudrama** [comment]
The single DynamicUse for `componentType` registered in the ResolutionWorldBuilder has a wrong receiver type
```
Selector(getter, componentType, arity=0),StrongModeConstraint(k:class(Null),ClassRelation.subtype),[]
```
It would appear that the static type visitor is computing the wrong type for the PropertyGet receiver.

/cc @johnniwinther

**Comment by rakudrama** [comment]
It appears that the static type visitor rewrites the temporary receiver for `f?.componentType`
from a correct type to `Null?`

The static type from Kernel is correct (see `#t21`)
```
static method test(dart.core::String* s, [dart.core::Map<dart.core::String*, #lib1::ComponentFactory<dynamic>*>* mf2 = #C2]) → #lib1::ComponentFactory<dynamic>* {
  #lib1::ComponentFactory<dynamic>* f = #lib1::mf.{dart.core::Map::[]}(s);
  if(f.{#lib1::ComponentFactory::==}(null)) {
    dart.core::Type* t = #lib1::mm.{dart.core::Map::[]}(s);
    if(!mf2.{dart.core::Object::==}(null))
      f = mf2.{dart.core::Map::[]}(s);
    if(!t.{dart.core::Object::==}(null) && !t.{dart.core::Object::==}(let final #lib1::ComponentFactory<dynamic>* #t21 = f in #t21.{#lib1::ComponentFactory::==}(null) ?{dart.core::Type*} null : #t21.{#lib1::ComponentFactory::componentType})) {
      dart.core::print("not match ${t}");
      f = #lib1::gf2;
    }
  }
  return f;
}
```
but after the static type visitor, the type is `Null?`:
```
t.{dart.core::Object::==}(let final dart.core::Null? #t21 = f in #t21.{#lib1::ComponentFactory::==}(null) ?{dart.core::Type*} null : #t21.{#lib1::ComponentFactory::componentType})
```

**Comment by rakudrama** [comment]
After
```dart
  if (f == null) {
    var t = mm[s];
    if (mf2 != null) f = mf2[s];
```
the TypeMap entry for `f` has  single TypeHolder with a `false=` entry.
```
VariableDeclaration(f)->TargetInfo(declaredType=InterfaceType(ComponentFactory<dynamic>*),typeHolders={TypeHolder(declared=InterfaceType(ComponentFactory<dynamic>*),false={InterfaceType(ComponentFactory<dynamic>*)})},declarationsOfInterest={InterfaceType(ComponentFactory<dynamic>*)})
```

**Comment by johnniwinther** [comment]
A CL is in progress: https://dart-review.googlesource.com/c/sdk/+/150935
