### ISSUE TITLE
[NNBD] Strange runtime error for mixin application and `noSuchMethod`

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42285]
The folowing code produces no errors in analyzer (with and without `--enable-experiment=non-nullable`) but a runtime error in VM with `--enable-experiment=non-nullable` and no error in VM without this option
```dart
String console = "";

class A {
  String get g => "g"; // Error here: type 'Null' is not a subtype of type 'String'
}

class C implements A {
  noSuchMethod(Invocation i) {
    console = "C";
  }
}

mixin M on A {
  noSuchMethod(Invocation i) {
    console = "M";
  }
}

class MA extends C with M {
}

main() {
  new MA().g;
}
```
Output is
```
Unhandled exception:                                                                                                                                type 'Null' is not a subtype of type 'String'
#0      C.g (.../co19/LanguageFeatures/Super-mixins/super_invocation_t19.dart:23:14)
#1      main (.../co19/LanguageFeatures/Super-mixins/super_invocation_t19.dart:46:12)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)     
```
Tested on `Dart VM version: 2.9.0-14.0.dev (dev) (Tue Jun 9 09:04:53 2020 +0200) on "windows_x64" `

**Comment by alexmarkov** [comment]
In this test `noSuchMethod` is called in order to implement `A.g`. `noSuchMethod` implicitly returns null, but `A.g` should return `String`, which is non-nullable with null safety enabled. So the exception is thrown at run time.

I think this test should be corrected for NNBD by returning a non-null String from `noSuchMethod` or changing return type of `A.g` to `String?`.

/cc @lrhn @leafpetersen

**Comment by aam** [comment]
I wish we instead of pointing to the source line with `A.g` somehow indicated in the stack trace that `C.g` doesn't actually exist in the source code, that it was implemented by `M.noSuchMethod`

**Comment by leafpetersen** [comment]
Right.  In noSuchMethod forwarding, there's an implicit cast from the return value of `noSuchMethod` to the return type of the method that it's implementing.  So in this case, the generated implementation of `C` is equivalent to this: 

```
class C implements A {
  noSuchMethod(Invocation i) {
    console = "C";
  }
  String get g => noSuchMethod(//something here) as String;
}
```

Since the `noSuchMethod` invocation returns null, the cast to `String` fails.

Depending on the original intent of the test, the correct migration of the test might be to return a string of some kind from `C.noSuchMethod`?

**Comment by lrhn** [comment]
The return type does not seem to be essential to the test. I'd just change `A.g` to return `void`.

But yes, the described behavior is correct for the current code.

**Comment by sgrekhov** [comment]
Thank you. If to change return type of the getter to `String?` or return some string from `noSuchMethod` then the error disapper. But, may be, it makes sense, in such case, at least warn user in analyzer that actual implementation of `noSuchMethod` returns `Null` but missed interface member(s) has non-nullable type? Otherwise it's not obvious to figure out what is wrong and what must be changed in the code to fix the error

**Comment by lrhn** [comment]
Even if all the unimplemented interface methods of a class have non-nullable return types, you can't know for certain that the class won't be invoked dynamically, or that subclasses won't add a nullable method that will also be covered by `noSuchMethod`. The `Mock` class is an example of a class with a fully general `noSuchMethod` method which is then inherited by classes which might only have non-nullable return types.

The `noSuchMethod` method is inherently dynamic. Any attempt to statically type-check it is going to fail often enough that it's better to not try.
