### ISSUE TITLE
[vm/ffi] MSAN failure on handles

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#42314]
```
/=======================================================================\
| ffi_2/vmspecific_handle_test is new and failed (Crash, expected Pass) |
\=======================================================================/

--- Command "vm" (took 11.000154s):
DART_CONFIGURATION=ReleaseMSANX64 out/ReleaseMSANX64/dart --enable-testing-pragmas --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/ffi_2/vmspecific_handle_test.dart

exit code:
-6

stdout:
testHandle
passObjectToC(Instance of 'SomeClass')
result = Instance of 'SomeClass'
HandleReadFieldValue
testClosureCallback Pointer<NativeFunction<(Handle) => Void>>: address=0x7f84c24c2000
ClosureCallbackThroughHandle 0x7f84c24c2000 0x71e000003018
doClosureCallback
() => void
Closure: () => void from Function 'increaseCounter': static.
increaseCounter
ClosureCallbackThroughHandle 0x7f84c24c2000 0x71e00004f818
doClosureCallback
() => void
Closure: () => void from Function 'increaseCounter': static.
increaseCounter
testReturnHandleInCallback
ReturnHandleInCallback 0x7f84c24c200a
returnHandleCallback returning Instance of 'SomeClass'
HandleReadFieldValue
Dart_PropagateError(field_value)
testCallbackReturnException
ReturnHandleInCallback 0x7f84c24c2014
exceptionHandleCallback throwing (Exception: exceptionHandleCallback exception)
callback() returned an error, propagating error
caught (Exception: exceptionHandleCallback exception)
testDeepException
ReturnHandleInCallback 0x7f84c24c201e
callCAgainFromCallback
HandleReadFieldValue
Dart_PropagateError(field_value)
testDeepException2
ReturnHandleInCallback 0x7f84c24c2028
callCAgainFromCallback2
HandleReadFieldValue
Dart_PropagateError(field_value)
callback() returned an error, propagating error
testNull
ReturnHandleInCallback 0x7f84c24c2032
returnHandleCallback returning null
HandleRecursion 1
callback
recurseAbove0(0)
throwing

stderr:
==19168==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x561620b32968 in dart::Api::ClassId(_Dart_Handle*) ../../out/ReleaseMSANX64/../../runtime/vm/dart_api_impl.h:228:9
    #1 0x561620b32968 in dart::Api::IsError(_Dart_Handle*) ../../out/ReleaseMSANX64/../../runtime/vm/dart_api_impl.h:223:27
    #2 0x561620b32968 in Dart_IsError ../../out/ReleaseMSANX64/../../runtime/vm/dart_api_impl.cc:729:10
    #3 0x7f84b6d338ea in HandleRecursion ../../out/ReleaseMSANX64/../../runtime/bin/ffi_test/ffi_test_functions_vmspecific.cc:882:7

SUMMARY: MemorySanitizer: use-of-uninitialized-value ../../out/ReleaseMSANX64/../../runtime/vm/dart_api_impl.h:228:9 in dart::Api::ClassId(_Dart_Handle*)
Exiting

--- Re-run this test:
python tools/test.py -n dartk-msan-linux-release-x64 ffi_2/vmspecific_handle_test
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8877698707636655312/+/steps/test_results/0/logs/new_test_failures__logs_/0

Cause: https://dart-review.googlesource.com/c/sdk/+/145591

**Comment by dcharkes** [comment]
This has to do with poisoning and unpoisoning of the stack when doing FFI calls in which parts of the memory of the stack is sometimes Dart stack and sometimes C stack (see [this discussion](https://dart-review.googlesource.com/c/sdk/+/151222)). The cleanest solution would be to call the MSAN unpoison hooks from the FFI transition/pointer code when the VM is built with MSAN.
