### ISSUE TITLE
Failed to remove build. A program may still be using a file in the directory or the directory itself. To find and stop such a program, see: https://superuser.com/questions/1333118/cant-delete-empty-folder-because-it-is-used

### ISSUE THREAD

**Issue by 065rsh** [dart-lang/sdk#42336]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.8.4`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.8.4, server version 1.27.4, error: FileSystemException: Exists failed, path = 'E:\ACNO\Flutter\jots_mobile\.dart_tool\build' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _PhysicalResource.exists (package:analyzer/file_system/physical_file_system.dart:373:29)
#2      _OverlayFolder.exists (package:analyzer/file_system/overlay_file_system.dart:290:65)
#3      PackageBuildWorkspace.find (package:analyzer/src/workspace/package_build.dart:292:28)
#4      ContextBuilder.createWorkspace (package:analyzer/src/context/builder.dart:508:36)
#5      ContextBuilder.getAnalysisOptions (package:analyzer/src/context/builder.dart:301:24)
#6      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:112:9)
#7      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:769:34)
#8      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1021:19)
#9      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1081:16)
#10     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:644:9)
#11     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:481:22)
#12     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:357:14)
#13     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:296:16)
#14     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:319:40)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#16     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:315:50)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
#19     _runZoned (dart:async/zone.dart:1619:10)
#20     runZonedGuarded (dart:async/zone.dart:1608:12)
#21     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:314:5)
#22     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#26     _rootRunUnary (dart:async/zone.dart:1192:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#37     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#38     _rootRunUnary (dart:async/zone.dart:1192:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#46     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#47     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#48     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#49     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#50     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#51     _rootRunUnary (dart:async/zone.dart:1192:38)
#52     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#56     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#57     _StreamController._add (dart:async/stream_controller.dart:655:7)
#58     _S...
```

For additional log information, please append the contents of
file://C:\Users\Arsh\AppData\Local\Temp\report1.txt.

**Comment by srawlins** [comment]
This crash hasn't been reported since Dart 2.8.4. Please re-open if you see this crash again.

**Comment by Scrobits-Vaibhav** [comment]
i m recently face this crash how to solve it?

**Comment by srawlins** [comment]
@Scrobits-Vaibhav please paste in the logs or stacktrace that you see when you see this occur.
