### ISSUE TITLE
Failures on [cfe] Recompute type parameter type nullability after substitution

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#42344]
There are new test failures on [[cfe] Recompute type parameter type nullability after substitution](https://dart-review.googlesource.com/c/sdk/+/149587).

The tests
```
language/covariant/subtyping_test Crash (expected Pass)
```
are failing on configurations
```
dart2js-hostasserts-strong-linux-x64-d8
dart2js-hostasserts-weak-linux-x64-d8
```

**Comment by johnniwinther** [comment]
cc @fishythefish

**Comment by fishythefish** [comment]
Minimal repro:

```dart
foo<T>() => <S extends T>() => null;

void main() {
  print(foo); // for liveness
}
```

The compiler fails with:

```
Internal Error: Runtime type information not available for type_variable_local(j:type_variable(foo.T)) in (j:anonymous_closure_local(foo_closure), type_variable_local(j:type_variable(call.S))) for j:closure_call(foo_closure.call).
foo<T>() => <S extends T>() => null;
^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Unhandled exception:
Assertion failure: Runtime type information not available for type_variable_local(j:type_variable(foo.T)) in (j:anonymous_closure_local(foo_closure), type_variable_local(j:type_variable(call.S))) for j:closure_call(foo_closure.call).
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      LocalsHandler.readLocal (package:compiler/src/ssa/locals_handler.dart:326:11)
#2      TypeBuilder._buildEnvironmentForType (package:compiler/src/ssa/type_builder.dart:280:12)
#3      TypeBuilder.analyzeTypeArgumentNewRti (package:compiler/src/ssa/type_builder.dart:198:9)
#4      KernelSsaGraphBuilder._checkTypeBound (package:compiler/src/ssa/builder_kernel.dart:5258:50)
#5      KernelSsaGraphBuilder._checkTypeVariableBounds (package:compiler/src/ssa/builder_kernel.dart:1459:11)
#6      KernelSsaGraphBuilder._potentiallyAddFunctionParameterTypeChecks (package:compiler/src/ssa/builder_kernel.dart:1401:7)
#7      KernelSsaGraphBuilder._openFunction (package:compiler/src/ssa/builder_kernel.dart:1624:7)
#8      KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder_kernel.dart:1238:5)
#9      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:479:13)
#10     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#11     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:431:21)
#12     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:514:22)
#13     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#14     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:496:18)
#15     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:346:21)
#16     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:80:29)
#17     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:453:30)
#18     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:332:43)
#19     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:463:29)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:70)
#21     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:32)
#23     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#24     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:28)
#25     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#26     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:456:18)
#27     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:266:12)
#28     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:282:5)
#29     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:452:16)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#31     Compiler.emptyQueue (package:compiler/src/compiler.dart:451:14)
#32     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:477:7)
#33     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#34     Compiler.processQueue (package:compiler/src/compiler.dart:470:14)
#35     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:382:5)
#36     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:284:9)
#37     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:432:9)
#38     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#39     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#40     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#41     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#42     new Future.sync (dart:async/future.dart:223:31)
#43     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#44     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#45     Compiler.run (package:compiler/src/compiler.dart:209:41)
#46     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#47     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#50     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#51     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#52     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#53     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#54     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#55     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
