### ISSUE TITLE
Analyzer crashes on migrated language/null_aware/invocation_test

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#42385]
I'm seeing a crash on the bots for that migrated test:  https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8877296892435233808/+/steps/test_results/0/logs/new_test_failures__logs_/0

For posterity:

```
/============================================================================================================\
| analyzer-asserts-strong-linux:language/null_aware/invocation_test is new and failed (Crash, expected Pass) |
\============================================================================================================/

--- Command "dart2analyzer" (took 131ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartanalyzer --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --format=machine --no-hints /b/s/w/ir/cache/builder/sdk/tests/language/null_aware/invocation_test.dart

exit code:
253

stderr:
NoSuchMethodError: The getter 'isDynamic' was called on null.
Receiver: null
Tried calling: isDynamic
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      TypeSystem.isStrictlyNonNullable (package:analyzer/src/generated/type_system.dart:205:14)
#2      ErrorVerifier._checkForUnnecessaryNullAware (package:analyzer/src/generated/error_verifier.dart:4439:21)
#3      ErrorVerifier.visitMethodInvocation (package:analyzer/src/generated/error_verifier.dart:951:9)
#4      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7162:49)
#5      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3706:18)
#6      RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:833:10)
#7      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3702:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7602:20)
#9      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1083:17)
#10     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#11     ErrorVerifier.visitBlock (package:analyzer/src/generated/error_verifier.dart:418:13)
#12     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1079:49)
#13     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1038:13)
#14     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#15     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1034:49)
#16     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5013:12)
#17     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:923:10)
#18     ErrorVerifier.visitFunctionExpression (package:analyzer/src/generated/error_verifier.dart:751:13)
#19     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5007:49)
#20     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4870:26)
#21     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:911:10)
#22     ErrorVerifier.visitFunctionDeclaration.<anonymous closure> (package:analyzer/src/generated/error_verifier.dart:738:13)
#23     ErrorVerifier._withEnclosingExecutable (package:analyzer/src/generated/error_verifier.dart:5320:16)
#24     ErrorVerifier.visitFunctionDeclaration (package:analyzer/src/generated/error_verifier.dart:716:5)
#25     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4863:49)
#26     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7602:20)
#27     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2132:21)
#28     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#29     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:517:11)
#30     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2125:49)
#31     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:386:10)
#32     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:160:9)
#33     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#34     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:159:13)
#35     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#36     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:158:34)
#37     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:116:14)
#38     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#39     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:115:43)
#40     AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1311:63)
#41     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#42     AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1287:20)
#43     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1238:14)
#44     _rootRun (dart:async/zone.dart:1190:13)
#45     _CustomZone.run (dart:async/zone.dart:1093:19)
#46     _runZoned (dart:async/zone.dart:1630:10)
#47     runZoned (dart:async/zone.dart:1550:10)
#48     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#49     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1237:40)
#50     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:573:41)
#51     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:49)
<asynchronous suspension>
#52     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#53     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#54     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:627:21)
#55     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:352:30)
<asynchronous suspension>
#56     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:186:20)
<asynchronous suspension>
#57     Driver.start.<anonymous closure> (package:analyzer_cli/src/driver.dart:141:22)
<asynchronous suspension>
#58     Driver.start.<anonymous closure> (package:analyzer_cli/src/driver.dart)
#59     BatchRunner.runAsBatch.<anonymous closure> (package:analyzer_cli/src/batch_mode.dart:53:35)
<asynchronous suspension>
#60     BatchRunner.runAsBatch.<anonymous closure> (package:analyzer_cli/src/batch_mode.dart)
#61     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#64     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#65     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#66     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#67     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#68     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#69     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#70     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#71     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#72     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#73     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#74     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#75     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#76     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#77     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#78     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#79     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#80     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#81     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#82     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#83     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#84     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#85     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:811:19)
#86     _StreamController._add (dart:async/stream_controller.dart:682:7)
#87     _StreamController.add (dart:async/stream_controller.dart:624:5)
#88     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#89     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#90     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#91     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#92     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:811:19)
#93     _StreamController._add (dart:async/stream_controller.dart:682:7)
#94     _StreamController.add (dart:async/stream_controller.dart:624:5)
#95     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#96     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#97     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#98     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#99     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#100    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

#0      AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1347:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1287:20)
#3      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1238:14)
#4      _rootRun (dart:async/zone.dart:1190:13)
#5      _CustomZone.run (dart:async/zone.dart:1093:19)
#6      _runZoned (dart:async/zone.dart:1630:10)
#7      runZoned (dart:async/zone.dart:1550:10)
#8      NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#9      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1237:40)
#10     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:573:41)
#11     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:129:49)
<asynchronous suspension>
#12     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:168:11)
<asynchronous suspension>
#13     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:105:18)
<asynchronous suspension>
#14     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:627:21)
#15     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:352:30)
<asynchronous suspension>
#16     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:186:20)
<asynchronous suspension>
#17     Driver.start.<anonymous closure> (package:analyzer_cli/src/driver.dart:141:22)
<asynchronous suspension>
#18     Driver.start.<anonymous closure> (package:analyzer_cli/src/driver.dart)
#19     BatchRunner.runAsBatch.<anonymous closure> (package:analyzer_cli/src/batch_mode.dart:53:35)
<asynchronous suspension>
#20     BatchRunner.runAsBatch.<anonymous closure> (package:analyzer_cli/src/batch_mode.dart)
#21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#37     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#38     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#39     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#40     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:811:19)
#46     _StreamController._add (dart:async/stream_controller.dart:682:7)
#47     _StreamController.add (dart:async/stream_controller.dart:624:5)
#48     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#49     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:811:19)
#53     _StreamController._add (dart:async/stream_controller.dart:682:7)
#54     _StreamController.add (dart:async/stream_controller.dart:624:5)
#55     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#56     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#59     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

cc @scheglov @stereotype441

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/151628

**Comment by munificent** [comment]
That was fast! :)
