### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by BlankStardust98** [dart-lang/sdk#42399]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.8.2`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.8.2, server version 1.27.4, error: FormatException: Unexpected character (at character 1)
...
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1261:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:926:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:31:10)
#4      JsonDecoder.convert (dart:convert/json.dart:505:36)
#5      JsonCodec.decode (dart:convert/json.dart:153:41)
#6      _PackageConfigJsonParser.parse (package:analyzer/src/context/package_config_json.dart:113:30)
#7      parsePackageConfigJson (package:analyzer/src/context/package_config_json.dart:13:49)
#8      parsePackageConfigJsonFile (package:analyzer/src/context/packages.dart:73:20)
#9      parsePackagesFile (package:analyzer/src/context/packages.dart:128:14)
#10     ContextManagerImpl._computeFolderDisposition (package:analysis_server/src/context_manager.dart:949:24)
#11     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:990:9)
#12     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1081:16)
#13     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:644:9)
#14     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:481:22)
#15     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:357:14)
#16     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:296:16)
#17     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:319:40)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#19     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:315:50)
#20     _rootRun (dart:async/zone.dart:1184:13)
#21     _CustomZone.run (dart:async/zone.dart:1077:19)
#22     _runZoned (dart:async/zone.dart:1619:10)
#23     runZonedGuarded (dart:async/zone.dart:1608:12)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:314:5)
#25     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#28     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#29     _rootRunUnary (dart:async/zone.dart:1192:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#41     _rootRunUnary (dart:async/zone.dart:1192:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#46     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#47     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#48     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#49     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#50     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#51     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#52     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#53     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#54     _rootRunUnary (dart:async/zone.dart:1192:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#59...
```

For additional log information, please append the contents of
file://C:\Users\BLANK\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Apologies that we didn't get to investigating this issue; please re-open if you see it on a recent version of Dart.
