### ISSUE TITLE
 The member 'getTypeArgumentByIndex' was not found in library '_js_helper'.

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#42390]
I'm attempting to run kevmoo/slide_puzzle@a23d035e87e77b74dd18b832cf7def51b8250aed with a local build of flutter/engine@59987bf478d99da67f716e78c2aefaa1e674c9c1 (with a local change applied for https://github.com/flutter/flutter/issues/59720).  I'm on Windows 10, using MSVC 2019.

And third_party/dart dart-lang/sdk@7d7c1298e2caaace3db008415a91c46a789ec49b (manually moved ahead 1 commit from current engine roll).

It's very possible (likely) that this is local/user error.

This is my log.  I'm not really sure where to start debugging:

```
C:\Users\Study\Documents\GitHub\slide_puzzle [master ≡ +1 ~1 -0 !]> flutter run -d web --web-port 8080 --local-engine=host_debug_unopt --local-engine-src-path=C:\src\engine\src -v --profile
[ +158 ms] executing: [C:\Users\Study\Documents\GitHub\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[ +156 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 9c3f0faa6da061f4f69ee1988a1416be985360f0
[        ] executing: [C:\Users\Study\Documents\GitHub\flutter/] git tag --contains HEAD
[+2727 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] executing: [C:\Users\Study\Documents\GitHub\flutter/] git describe --match *.*.*-*.*.pre --first-parent
--long --tags
[ +640 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +12 ms] 1.20.0-0.0.pre-91-g9c3f0faa6d
[  +14 ms] executing: [C:\Users\Study\Documents\GitHub\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +82 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\Users\Study\Documents\GitHub\flutter/] git ls-remote --get-url origin
[  +92 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +130 ms] executing: [C:\Users\Study\Documents\GitHub\flutter/] git rev-parse --abbrev-ref HEAD
[ +232 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +27 ms] master
[  +97 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +90 ms] executing: C:\Users\Study\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +166 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +808 ms] Generating
C:\Users\Study\Documents\GitHub\slide_puzzle\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +295 ms] Launching lib\main.dart on Web Server in profile mode...
[ +174 ms] Generating
C:\Users\Study\Documents\GitHub\slide_puzzle\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +37 ms] Compiling lib\main.dart for the Web...
[  +14 ms] Initializing file store
[  +33 ms] Done initializing file store
[ +151 ms] Skipping target: gen_localizations
[  +78 ms] Skipping target: web_entrypoint
[+4882 ms] dart2js: Starting due to {}
[+39828 ms] Persisting file store
[  +21 ms] Done persisting file store
[  +19 ms] Target dart2js failed: Exception: org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart@93406+1:
           Internal Error: The member 'getTypeArgumentByIndex' was not found in library '_js_helper'.
           The compiler is broken.

           When compiling the above element, the compiler crashed. It is not
           possible to tell if this is caused by a problem in your program or
           not. Regardless, the compiler should not crash.

           The Dart team would greatly appreciate if you would take a moment to
           report this problem at http://dartbug.com/new.

           Please include the following information:

           * the name and version of your operating system,

           * the Dart SDK build number (2.9.0-edge.b'f043f9e5f6ea4194c0ff4114e30adc5380cbc932'), and

           * the entire message you see here (including the full stack trace
             below as well as the source location above).

           The compiler crashed: Assertion failure: The member 'getTypeArgumentByIndex' was not found in library
'_js_helper'.
           #0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
           #1      KernelElementEnvironment.lookupLibraryMember
(package:compiler/src/kernel/element_map_impl.dart:1840:7)
           #2      CommonElementsImpl._findLibraryMember (package:compiler/src/common_elements.dart:1045:17)
           #3      CommonElementsImpl._findHelperFunction (package:compiler/src/common_elements.dart:1569:7)
           #4      CommonElementsImpl.getTypeArgumentByIndex (package:compiler/src/common_elements.dart:1822:7)
           #5      BackendImpacts.listClasses (package:compiler/src/js_backend/backend_impact.dart:677:27)
           #6      ResolutionEnqueuerListener._processClass
(package:compiler/src/js_backend/resolution_listener.dart:368:54)
           #7      ResolutionEnqueuerListener.registerInstantiatedClass
           (package:compiler/src/js_backend/resolution_listener.dart:423:12)
           #8      ResolutionEnqueuer._applyClassUse (package:compiler/src/enqueue.dart:335:28)
           #9      ResolutionWorldBuilderImpl._processInstantiatedClass.processClass
           (package:compiler/src/universe/resolution_world_builder.dart:727:18)
           #10     ResolutionWorldBuilderImpl._processInstantiatedClass
           (package:compiler/src/universe/resolution_world_builder.dart:733:39)
           #11     ResolutionWorldBuilderImpl.registerTypeInstantiation
           (package:compiler/src/universe/resolution_world_builder.dart:451:7)
           #12     ResolutionEnqueuer._registerInstantiatedType.<anonymous closure>
(package:compiler/src/enqueue.dart:288:21)
           #13     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
           #14     ResolutionEnqueuer._registerInstantiatedType (package:compiler/src/enqueue.dart:287:10)
           #15     ResolutionEnqueuer.processTypeUse (package:compiler/src/enqueue.dart:389:9)
           #16     EnqueuerImplImpactVisitor.visitTypeUse (package:compiler/src/enqueue.dart:551:14)
           #17     TransformedWorldImpact.apply.<anonymous closure>
(package:compiler/src/universe/world_impact.dart:304:47)
           #18     Setlet.forEach (package:compiler/src/util/setlet.dart:246:15)
           #19     TransformedWorldImpact.apply (package:compiler/src/universe/world_impact.dart:304:14)
           #20     JavaScriptImpactStrategy.visitImpact (package:compiler/src/js_backend/backend.dart:284:16)
           #21     ResolutionEnqueuer.applyImpact (package:compiler/src/enqueue.dart:279:20)
           #22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>
           (package:compiler/src/compiler.dart:459:28)
           #23     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
           #24     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>
           (package:compiler/src/compiler.dart:458:28)
           #25     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
           #26     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>
(package:compiler/src/compiler.dart:456:18)
           #27     ResolutionEnqueuer._forEach (package:compiler/src/enqueue.dart:449:12)
           #28     ResolutionEnqueuer.forEach (package:compiler/src/enqueue.dart:465:5)
           #29     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:452:16)
           #30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
           #31     Compiler.emptyQueue (package:compiler/src/compiler.dart:451:14)
           #32     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:477:7)
           #33     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
           #34     Compiler.processQueue (package:compiler/src/compiler.dart:470:14)
           #35     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:339:5)
           #36     Compiler.compileFromKernel.<anonymous closure>.<anonymous closure>
(package:compiler/src/compiler.dart:407:17)
           #37     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
           #38     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:406:43)
           #39     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
           #40     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
           #41     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
           <asynchronous suspension>
           #42     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
           #43     new Future.sync (dart:async/future.dart:222:31)
           #44     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
           #45     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
           #46     Compiler.run (package:compiler/src/compiler.dart:209:41)
           #47     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
           #48     _RootZone.runUnary (dart:async/zone.dart:1450:54)
           #49     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #50     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #51     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #52     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #53     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[  +21 ms] Compiling lib\main.dart for the Web... (completed in 45.0s)
[   +2 ms] "flutter run" took 46,699ms.
[  +17 ms] Exception: Failed to compile application for the Web.
[  +14 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildWeb (package:flutter_tools/src/web/compile.dart:79:5)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
           #20     _rootRunUnary (dart:async/zone.dart:1198:47)
           #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #26     Future.wait.<anonymous closure> (dart:async/future.dart:409:22)
           #27     _rootRunUnary (dart:async/zone.dart:1198:47)
           #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #35     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
           #36     _rootRunUnary (dart:async/zone.dart:1198:47)
           #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #42     Future.wait.<anonymous closure> (dart:async/future.dart:409:22)
           #43     _rootRunUnary (dart:async/zone.dart:1198:47)
           #44     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #45     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #47     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #48     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #49     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #50     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #51     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
           #52     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
           #53     _rootRunBinary (dart:async/zone.dart:1214:47)
           #54     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
           #55     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
           #56     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
           #57     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
           #58     Future._completeError (dart:async/future_impl.dart:537:5)
           #59     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
           #60     Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart)
           #61     _rootRunUnary (dart:async/zone.dart:1198:47)
           #62     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #63     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #65     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #66     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #67     Future.wait.<anonymous closure> (dart:async/future.dart:409:22)
           #68     _rootRunUnary (dart:async/zone.dart:1198:47)
           #69     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #70     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #71     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #72     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #73     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #74     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #75     _rootRun (dart:async/zone.dart:1190:13)
           #76     _CustomZone.run (dart:async/zone.dart:1093:19)
           #77     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #78     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #79     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #80     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #81     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #82     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +115 ms] ensureAnalyticsSent: 98ms
[   +9 ms] Running shutdown hooks
[   +3 ms] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
C:\Users\Study\Documents\GitHub\slide_puzzle [master ≡ +1 ~1 -0 !]>
```

**Comment by eseidel** [comment]
Suspicious that it reports in that error-log a 7-day-old dart sdk.  But maybe that's the one used by the flutter/flutter repo?  Maybe it's incompatible with the outputs of my local engine build?

**Comment by eseidel** [comment]
Running from the hosted engine works fine.

I've tried removing the build directory and running `flutter upgrade` neither seem to have helped.

I've not yet tried clearing the build directory of my engine and rebuilding from scratch.  Nor have I tried to bisect where this might begin yet.

**Comment by rakudrama** [comment]
I have been deleting unused code (matching code in dart2js and the runtime libraries).
With these changes, the platform .dill file and dart2js snapshot can't be out of sync.
You would get the error you report if you were using a version of dart2js that is older than the libraries.

**Comment by eseidel** [comment]
Seems to be working now (after and attempted bisect). I suspect some of the dependency rules in the flutter/engine build.gn files aren't quite correct and thus the build was partially stale.
