### ISSUE TITLE
Analyzer feedback

### ISSUE THREAD

**Issue by GOSSII** [dart-lang/sdk#42405]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.4.0`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.2, screens 1920x1080, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: /Users/gossi/Desktop/InkMobile/flmobile/flutter/bin/cache/dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart context: exception_20200618_150354_733
Bad state: Element not contained in compilation unit: Never
#0      getUnitElement (package:analyzer/src/dart/analysis/index.dart:28:3)
#1      _IndexAssembler._getElementInfo.<anonymous closure> (package:analyzer/src/dart/analysis/index.dart:346:44)
#2      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#3      _IndexAssembler._getElementInfo (package:analyzer/src/dart/analysis/index.dart:345:23)
#4      _IndexAssembler.addElementRelation (package:analyzer/src/dart/analysis/index.dart:235:32)
#5      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:499:15)
#6      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:451:7)
#7      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:759:5)
#8      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8976:49)
#9      TypeNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10188:12)
#10     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#11     GeneralizingAstVisitor.visitTypeName (package:analyzer/dart/ast/visitor.dart:566:37)
#12     _IndexContributor.visitTypeName (package:analyzer/src/dart/analysis/index.dart:785:13)
#13     TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10184:49)
#14     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7112:18)
#15     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#16     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:137:47)
#17     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:230:43)
#18     GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:186:43)
#19     GeneralizingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:416:55)
#20     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7107:49)
#21     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#22     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1590:13)
#23     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#24     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:137:47)
#25     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:230:43)
#26     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:205:7)
#27     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:427:7)
#28     GeneralizingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:184:7)
#29     _IndexContributor.visitClassDeclaration (package:analyzer/src/dart/analysis/index.dart:565:11)
#30     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1560:49)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#32     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2167:21)
#33     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#34     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:51)
#35     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#36     _IndexAssembler.assemble (package:analyzer/src/dart/analysis/index.dart:262:10)
#37     indexUnit (package:analyzer/src/dart/analysis/index.dart:35:32)
#38     AnalysisDriver._serializeResolvedUnit (package:analyzer/src/dart/analysis/driver.dart:1783:11)
#39     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1425:15)
#40     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#41     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
#42     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1215:33)
<asynchronous suspension>
#43     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
<asynchronous suspension>
#44     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#45     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#46     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#47     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#48     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#49     _rootRun (dart:async/zone.dart:1124:13)
#50     _CustomZone.run (dart:async/zone.dart:1021:19)
#51...
```

For additional log information, please append the contents of
file:///private/var/folders/3h/fxyjhbs11sbgmdygs3fb0sl00000gn/T/report.txt.

**Comment by keertip** [comment]
@GOSSII , this is a very old version of the analyzer, current version is 2.8.4. It is most likely this has been fixed. Please update, try it out and reopen issue if you still run into this problem.
