### ISSUE TITLE
Dart2JS: analyzer fails when check the type of typedef function 

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42437]
[co19/Language/Generics/typedef_A04_t03](https://github.com/dart-lang/co19/blob/master/Language/Generics/typedef_A04_t03.dart) test fails when test analyzer with dart2js. 

This error is not reproducible in other testing modes.

Here is a [link](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8877064922335749312/+/steps/test_results/0/logs/new_test_failures__logs_/0) to the log file.

Here is a sample output:
```
--- Command "dart2js" (took 03.000758s):
DART_CONFIGURATION=ReleaseX64 sdk/bin/dart2js_developer --enable-experiment=non-nullable --enable-experiment=non-nullable --test-mode --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/Language/Generics/typedef_A04_t03.dart --no-sound-null-safety --libraries-spec=sdk/lib/libraries.json --platform-binaries=out/ReleaseX64/ --out=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js

exit code:
0

stdout:
Compiled 8,070,808 characters Dart to 95,643 characters JavaScript in 3.75 seconds
Dart file /b/s/w/ir/tests/co19/src/Language/Generics/typedef_A04_t03.dart compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js

--- Command "chrome" (took 120ms):
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:36661/root_build/generated_tests/dart2js-chrome/tests_co19_src_Language_Generics_typedef_A04_t03/test.html?crossOriginPort=34301

Runtime error:
Expect.isFalse(true) fails.
Expect.isFalse(true) fails.
    at Object.wrapException (http://127.0.0.1:36661/root_build/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js:292:17)
    at Object._fail (http://127.0.0.1:36661/root_build/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js:2180:15)
    at Object.Expect_isFalse (http://127.0.0.1:36661/root_build/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js:2190:9)
    at main (http://127.0.0.1:36661/root_build/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js:2214:9)
    at dartMainRunner (http://127.0.0.1:36661/root_dart/pkg/test_runner/lib/src/test_controller.js:315:5)
    at http://127.0.0.1:36661/root_build/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js:2567:7
    at http://127.0.0.1:36661/root_build/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js:2553:7
    at dartProgram (http://127.0.0.1:36661/root_build/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js:2564:5)
    at http://127.0.0.1:36661/root_build/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js:2571:3

Deobfuscated error and stack:
Expect.isFalse(true) fails.
Expect.isFalse(true) fails.
    at wrapException         org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 1230:37
    at _fail                 ../../../../../tests/co19/src/Utils/expect.dart 21:5
    at Expect.isFalse        ../../../../../tests/co19/src/Utils/expect_common.dart 48:5
    at main                  ../../../../../tests/co19/src/Language/Generics/typedef_A04_t03.dart 38:10
    at dartMainRunner        pkg/test_runner/lib/src/test_controller.js 315:5
    at <fn>                  out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js 2567:7
    at <fn>                  out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js 2553:7
    at dartProgram           out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js 2564:5
    at <fn>                  out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Generics_typedef_A04_t03/typedef_A04_t03.js 2571:3


exit code:
0

```

**Comment by sigmundch** [comment]
@fishythefish FYI - maybe related to https://github.com/dart-lang/sdk/issues/42408??

**Comment by fishythefish** [comment]
I don't think it's related to that issue since the expectations on lines 36-37 are fine.

`checkme3` has type `X? Function()` and after instantiation to bounds, `Func2` is `X Function()`. However, this test is being run in weak mode (note that `--no-sound-null-safety` is passed), so per the spec, I think dart2js is doing the right thing. This test should succeed as written when run in strong mode.
