### ISSUE TITLE
Dart migrate fails with an exception for extension

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/sdk#42455]
When trying to run `dart migrate` on my *Flutter* app (not sure if that is supported yet), `dart migrate --ignore-errors` fails with the following message:

<details>
<summary>

```
Bad state: No type computed for ExtensionOverrideImpl
```

</summary>

```
#0      EdgeBuilder._checkExpressionNotNull (package:nnbd_migration/src/edge_builder.dart:1860:7)
#1      EdgeBuilder._handleTarget (package:nnbd_migration/src/edge_builder.dart:2765:14)
#2      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:2704:20)
#3      EdgeBuilder.visitPropertyAccess (package:nnbd_migration/src/edge_builder.dart:1337:12)
#4      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8398:49)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2072:22)
#6      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2185:20)
#7      EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2658:7)
#8      EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:1059:5)
#9      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6073:15)
#10     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2072:22)
#11     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2185:20)
#12     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2658:7)
#13     EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:1059:5)
#14     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6073:15)
#15     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2072:22)
#16     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2185:20)
#17     EdgeBuilder._handleCollectionElement (package:nnbd_migration/src/edge_builder.dart:2264:14)
#18     ListMixin.forEach (dart:collection/list.dart:67:13)
#19     EdgeBuilder.visitListLiteral (package:nnbd_migration/src/edge_builder.dart:1126:21)
#20     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6693:49)
#21     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2072:22)
#22     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2185:20)
#23     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2658:7)
#24     EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:1059:5)
#25     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6073:15)
#26     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2072:22)
#27     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2185:20)
#28     EdgeBuilder.visitReturnStatement (package:nnbd_migration/src/edge_builder.dart:1384:7)
#29     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8567:49)
#30     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2072:22)
#31     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1226:9)
#32     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#33     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:162:31)
#34     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1076:49)
#35     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2072:22)
#36     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1226:9)
#37     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#38     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:165:55)
#39     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1031:49)
#40     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2072:22)
#41     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2313:7)
#42     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1145:5)
#43     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6968:49)
#44     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2072:22)
#45     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2086:7)
#46     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:577:7)
#47     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:544:5)
#48     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1528:49)
#49     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2072:22)
#50     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1226:9)
#51     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:199:51)
#52     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#53     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#54     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#55     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2122:49)
#56     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:190:12)
#57     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:157:15)
#58     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:990:19)
#59     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:934:30)
<asynchronous suspension>
#60     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:988:11)
#61     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:578:43)
<asynchronous suspension>
#62     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:202:72)
#63     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#64     DartdevRunner.runCommand (package:dartdev/dartdev.dart:195:24)
#65     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#66     new Future.sync (dart:async/future.dart:223:31)
#67     CommandRunner.run (package:args/command_runner.dart:112:14)
#68     runDartdev (package:dartdev/dartdev.dart:91:27)
```
</details>

Essentially, the mentioned (excluded) extension class extends a class from within the project.

---

The Dart version is `2.9.0-17.0.dev`.

**Comment by stereotype441** [comment]
@creativecreatorormaybenot is the error message associated with a stack trace?  If you could include the stack trace that would be really helpful to us in figuring out what's going wrong.

Alternatively, if your program is open source, and you can link to a github commit of it in the state where it fails, or you could narrow down the issue to a small repro that you would be willing to post online, that would be very helpful.  Thanks!

**Comment by creativecreatorormaybenot** [comment]
@stereotype441 I did post the stack trace (expand arrow above the `Bad state` 😃

**Comment by stereotype441** [comment]
> @stereotype441 I did post the stack trace (expand arrow above the `Bad state`) 😃

Aha, thank you!  I just learned about a new github feature :)

**Comment by stereotype441** [comment]
The crash seems to be associated with use of the explicit extension override syntax.  I was able to reproduce it with this test program:
```dart
extension E on int {
  int get plusOne => this + 1;
}
int f(int x) => E(x).plusOne; // crash trying to handle: E(x)
```
Working on a fix now.
