### ISSUE TITLE
ubsan failure due to signed integer overflow during dart2js snapshot generation

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#42454]
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-ubsan-linux-release-x64/317

```
python ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=/b/s/w/ir/cache/builder/sdk/.packages --snapshot=gen/kernel-service.dart.snapshot --snapshot-depfile=/b/s/w/ir/cache/builder/sdk/out/ReleaseUBSANX64/gen/kernel-service.dart.snapshot.d --snapshot-kind=app-jit /b/s/w/ir/cache/builder/sdk/out/ReleaseUBSANX64/gen/utils/kernel-service/kernel-service_snapshot.dart.dill --train file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/dart2js.dart
Command failed: ./dart --deterministic --packages=/b/s/w/ir/cache/builder/sdk/.packages --snapshot=gen/kernel-service.dart.snapshot --snapshot-depfile=/b/s/w/ir/cache/builder/sdk/out/ReleaseUBSANX64/gen/kernel-service.dart.snapshot.d --snapshot-kind=app-jit /b/s/w/ir/cache/builder/sdk/out/ReleaseUBSANX64/gen/utils/kernel-service/kernel-service_snapshot.dart.dill --train file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/dart2js.dart
output: ../../pkg/compiler/lib/src/dart2js.dart: Warning: Interpreting this as package URI, 'package:compiler/src/dart2js.dart'.
../../runtime/vm/compiler/backend/il.cc:872:26: runtime error: signed integer overflow: -2147483648 - 1 cannot be represented in type 'int'
    #0 0x5585b8cdb590 in dart::CheckClassInstr::ComputeCidMask() const ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/il.cc:872:26
    #1 0x5585b8d152a1 in dart::CheckClassInstr::EmitNativeCode(dart::FlowGraphCompiler*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/il.cc:5118:37
    #2 0x5585b8ca6487 in dart::FlowGraphCompiler::VisitBlocks() ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/flow_graph_compiler.cc:613:16
    #3 0x5585b8cc72f9 in dart::FlowGraphCompiler::CompileGraph() ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/flow_graph_compiler_x64.cc:939:3
    #4 0x5585b802b1a3 in dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/jit/compiler.cc:632:24
    #5 0x5585b802d2c5 in dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/jit/compiler.cc:755:46
    #6 0x5585b802e6fc in dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/jit/compiler.cc:946:10
    #7 0x5585b7f46d3d in dart::DRT_HelperOptimizeInvokedFunction(dart::Isolate*, dart::Thread*, dart::Zone*, dart::NativeArguments) ../../out/ReleaseUBSANX64/../../runtime/vm/runtime_entry.cc:2824:15
    #8 0x5585b7f46838 in dart::DRT_OptimizeInvokedFunction(dart::NativeArguments) ../../out/ReleaseUBSANX64/../../runtime/vm/runtime_entry.cc:2779:1

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../runtime/vm/compiler/backend/il.cc:872:26 in 
```

**Comment by aam** [comment]
Seemingly triggered by https://dart.googlesource.com/sdk/+/5a6c1e515849b453220939cff697c6397c5d3c70

cc @eernstg

**Comment by aam** [comment]
Not able to reproduce the failure locally:
```
╰─➤  tools/gn.py --mode release --sanitizer ubsan -ax64         
$ ~/p/d/dart-sdk1/sdk  ‹5a6c1e5158*› 
╰─➤  ninja -C out/ReleaseUBSANX64 gen/kernel-service.dart.snapshot
ninja: Entering directory `out/ReleaseUBSANX64'
[1034/1723] CXX obj/third_party/icu/source/i18n/icui18n.plurrule.o
../../third_party/icu/source/i18n/plurrule.cpp:1664:24: warning: implicit conversion from 'int64_t' (aka 'long') to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-int-float-conversion]
          if (scaled > U_INT64_MAX) {
                     ~ ^~~~~~~~~~~
../../third_party/icu/source/common/unicode/umachine.h:248:33: note: expanded from macro 'U_INT64_MAX'
#     define U_INT64_MAX       ((int64_t)(INT64_C(9223372036854775807)))
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
[1723/1723] ACTION //utils/kernel-serv...hot(//build/toolchain/linux:clang_x64)
$ ~/p/d/dart-sdk1/sdk  ‹5a6c1e5158*› 
```

cc @rmacnak-google any ideas why ubsan might produce different results when running locally vs on bot?

**Comment by aam** [comment]
Fixed by https://dart.googlesource.com/sdk/+/3852f767dbccbd9a8d5cc2ac6e0366d87bbc2689
