### ISSUE TITLE
dart2js has wrong order of superinitializer evaluation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42471]
The following co19 tests fails on dar2js (works in VM and Analyzer)
[https://github.com/dart-lang/co19/blob/master/Language/Classes/Constructors/Generative_Constructors/execution_of_a_superinitializer_t01.dart](https://github.com/dart-lang/co19/blob/master/Language/Classes/Constructors/Generative_Constructors/execution_of_a_superinitializer_t01.dart)

Failure is

```dart
/============================================================================================================================================================================================\
| dart2js-hostasserts-strong-linux-x64-chrome:co19/Language/Classes/Constructors/Generative_Constructors/execution_of_a_superinitializer_t01 is new and failed (RuntimeError, expected Pass) |
\============================================================================================================================================================================================/

--- Command "dart2js" (took 04.000180s):
DART_CONFIGURATION=ReleaseX64 sdk/bin/dart2js_developer --enable-experiment=non-nullable --enable-experiment=non-nullable --test-mode --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/Language/Classes/Constructors/Generative_Constructors/execution_of_a_superinitializer_t01.dart --sound-null-safety --libraries-spec=sdk/lib/libraries.json --platform-binaries=out/ReleaseX64/ --out=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js

exit code:
0

stdout:
Compiled 8,057,767 characters Dart to 134,056 characters JavaScript in 4.17 seconds
Dart file /b/s/w/ir/tests/co19/src/Language/Classes/Constructors/Generative_Constructors/execution_of_a_superinitializer_t01.dart compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js

--- Command "chrome" (took 115ms):
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:40339/root_build/generated_tests/dart2js-chrome/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/test.html?crossOriginPort=43049

Runtime error:
deepEquals([a1, a2, o, s1true, s2true, true, false, ok], [a1, a2, o, s1true, s2true, true, true, ok], , 'Wrong superinitializer evaluation order!') fails
   [cause: Expect.equals(expected: <false>, actual: <true>) fails.]
deepEquals([a1, a2, o, s1true, s2true, true, false, ok], [a1, a2, o, s1true, s2true, true, true, ok], , 'Wrong superinitializer evaluation order!') fails
   [cause: Expect.equals(expected: <false>, actual: <true>) fails.]
    at Object.wrapException (http://127.0.0.1:40339/root_build/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js:300:17)
    at Object._fail (http://127.0.0.1:40339/root_build/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js:2572:15)
    at Object.Expect_deepEquals (http://127.0.0.1:40339/root_build/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js:2621:11)
    at Object.Expect_listEquals (http://127.0.0.1:40339/root_build/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js:2591:9)
    at main (http://127.0.0.1:40339/root_build/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js:2659:9)
    at dartMainRunner (http://127.0.0.1:40339/root_dart/pkg/test_runner/lib/src/test_controller.js:315:5)
    at http://127.0.0.1:40339/root_build/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js:3575:7
    at http://127.0.0.1:40339/root_build/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js:3561:7
    at dartProgram (http://127.0.0.1:40339/root_build/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js:3572:5)
    at http://127.0.0.1:40339/root_build/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js:3579:3

Deobfuscated error and stack:
deepEquals([a1, a2, o, s1true, s2true, true, false, ok], [a1, a2, o, s1true, s2true, true, true, ok], , 'Wrong superinitializer evaluation order!') fails
   [cause: Expect.equals(expected: <false>, actual: <true>) fails.]
deepEquals([a1, a2, o, s1true, s2true, true, false, ok], [a1, a2, o, s1true, s2true, true, true, ok], , 'Wrong superinitializer evaluation order!') fails
   [cause: Expect.equals(expected: <false>, actual: <true>) fails.]
    at wrapException            org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 1129:37
    at _fail                    ../../../../../tests/co19/src/Utils/expect.dart 21:5
    at Expect.deepEquals        ../../../../../tests/co19/src/Utils/expect_common.dart 320:7
    at Expect.listEquals        ../../../../../tests/co19/src/Utils/expect_common.dart 248:5
    at main                     ../../../../../tests/co19/src/Language/Classes/Constructors/Generative_Constructors/execution_of_a_superinitializer_t01.dart 60:10
    at dartMainRunner           pkg/test_runner/lib/src/test_controller.js 315:5
    at <fn>                     out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js 3575:7
    at <fn>                     out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js 3561:7
    at dartProgram              out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js 3572:5
    at <fn>                     out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Classes_Constructors_Generative_Constructors_execution_of_a_superinitializer_t01/execution_of_a_superinitializer_t01.js 3579:3


exit code:
0

--- To debug locally, run:
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/pkg/test_runner/bin/http_server.dart -p 40339 -c 43049 --network 127.0.0.1 --build-directory=/b/s/w/ir/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/.packages

--- Re-run this test:
python tools/test.py -n dart2js-hostasserts-strong-linux-x64-chrome --dart2js-batch co19/Language/Classes/Constructors/Generative_Constructors/execution_of_a_superinitializer_t01

```

**Comment by sgrekhov** [comment]
I changed the test. Thank you. Closing this issue
