### ISSUE TITLE
Dart Analyzer Error 				Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by Asif42012** [dart-lang/sdk#42476]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5522156`
- `2.6.1`
- `AI-183.6156.11.34.5522156, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.9.0-14.1.beta, server version 1.27.4, FATAL error: UnimplementedError: Encoding "null"
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:719:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1076:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:999:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#9      _Closure.call (dart:core-patch/function.dart)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

For additional log information, please append the contents of
file://C:\Users\Digital\AppData\Local\Temp\report8.txt.

**Comment by srawlins** [comment]
This has been reported as recently as Dart 2.9.2.

**Comment by srawlins** [comment]
Apologies that we didn't get to reviewing this. I'm going to close this as stale, but please re-open if you see this on a recent version of Dart.
