### ISSUE TITLE
dartkp crashes if script contains getter main returning function

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42492]
The following test crashes on dartkp
```dart
import "../../../Utils/expect.dart";

var x = 1;
get main => () { Expect.equals(1, x); };
```
Output is
```
/==============================================================================================================================================\
| dartkp-strong-linux-release-x64:co19/Language/Libraries_and_Scripts/Scripts/top_level_main_t05 is new and failed (DartkCrash, expected Pass) |
\==============================================================================================================================================/

--- Command "vm_compile_to_kernel []" (took 977ms):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp/tests_co19_src_Language_Libraries_and_Scripts_Scripts_top_level_main_t05/out.dill /b/s/w/ir/tests/co19/src/Language/Libraries_and_Scripts/Scripts/top_level_main_t05.dart --enable-experiment=non-nullable --packages=/b/s/w/ir/.packages -Ddart.vm.product=false -Ddart.developer.causal_async_stacks=true --null-safety

exit code:
253

stderr:
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List._setIndexed (dart:core-patch/growable_array.dart:159:73)
#1      List.[]= (dart:core-patch/growable_array.dart:156:5)
#2      new Args.withReceiver (package:vm/transformations/type_flow/calls.dart:204:11)
#3      _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:289:17)
#4      _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:182:14)
#5      _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1279:32)
#6      _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1259:7)
#7      TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1421:14)
#8      transformComponent (package:vm/transformations/type_flow/transformer.dart:78:20)
#9      runGlobalTransformations (package:vm/kernel_front_end.dart:503:5)
#10     compileToKernel (package:vm/kernel_front_end.dart:394:11)
<asynchronous suspension>
#11     runCompiler (package:vm/kernel_front_end.dart:275:25)
<asynchronous suspension>
#12     compile (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:39:10)
#13     runBatchModeCompiler.<anonymous closure> (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:57:28)
#14     runBatch (package:kernel/src/tool/batch_util.dart:38:35)
<asynchronous suspension>
#15     runBatchModeCompiler (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:43:9)
#16     main (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:32:11)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartkp-strong-linux-release-x64 co19/Language/Libraries_and_Scripts/Scripts/top_level_main_t05
```

**Comment by alexmarkov** [comment]
TFA crashes as it can only handle `main` method and not getter/setter. This won't happen if front-end would report a compile-time error.

@leafpetersen @lrhn Could you confirm that malformed `main` should result in a compile-time error?

**Comment by lrhn** [comment]
A `main` only counts as an entry point if it's a function declaration callable with zero, one or two arguments.

> A \Index{script} is a library whose exported namespace (\ref{exports}) includes
> a top-level function declaration named \code{main}
> that has either zero, one or two required arguments.

(That should now be "required positional arguments").
You can only run a script.

**Comment by alexmarkov** [comment]
In such case I think front-end should not set `Component.mainMethod` to a getter/setter and keep `Component.mainMethod == null`.
Also, it might be useful to report a more detailed error about malformed `main` when compiling a script.
/cc @johnniwinther
