### ISSUE TITLE
[dart2js] Runtime error when calling null.runtimeType

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42512]
Calling `null.runtimeType` produces a runtime error on dart2js
```
Deobfuscated error and stack:
TypeError: C.JSNull_methods.get$runtimeType is not a function
```
In Dart class Null has `runtimeType` getter

**Comment by rakudrama** [comment]
Can you give more details how to reproduce the error?
I see:
```
$ dart2js 42512.dart
Compiled 8,027,548 characters Dart to 95,425 characters JavaScript in 0.67 seconds
$ d8 out.js
Null
Null
```
`42512.dart`:
```dart
main() {
  print(null.runtimeType);
  print(null.runtimeType);
}
```
`out.js`:
```js
    main: function() {
      P.print(C.JSNull_methods.get$runtimeType(null));
      P.print(C.JSNull_methods.get$runtimeType(null));
    }
...
  J.JSNull.prototype = {
    toString$0: function(receiver) {
      return "null";
    },
    get$runtimeType: function(receiver) {
      return C.Type_Null_Yyn;
    }
  };
...
    C.JSNull_methods = J.JSNull.prototype;
...
    C.Type_Null_Yyn = H.typeLiteral("Null");

```

**Comment by sgrekhov** [comment]
@rakudrama here is the test that fails https://github.com/dart-lang/co19/blob/master/Language/Overview/runtime_type_t02.dart
Tryjob output can be found [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8876438172205205632/+/steps/test_results/0/logs/new_test_failures__logs_/0)
```

/=====================================================================================================================================\
| dart2js-hostasserts-strong-linux-x64-chrome:co19/Language/Overview/runtime_type_t02 is new and failed (RuntimeError, expected Pass) |
\=====================================================================================================================================/

--- Command "dart2js" (took 03.000456s):
DART_CONFIGURATION=ReleaseX64 sdk/bin/dart2js_developer --enable-experiment=non-nullable --enable-experiment=non-nullable --test-mode --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/Language/Overview/runtime_type_t02.dart --sound-null-safety --libraries-spec=sdk/lib/libraries.json --platform-binaries=out/ReleaseX64/ --out=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Overview_runtime_type_t02/runtime_type_t02.js

exit code:
0

stdout:
Compiled 8,056,394 characters Dart to 94,129 characters JavaScript in 3.45 seconds
Dart file /b/s/w/ir/tests/co19/src/Language/Overview/runtime_type_t02.dart compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Overview_runtime_type_t02/runtime_type_t02.js

--- Command "chrome" (took 125ms):
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:33907/root_build/generated_tests/dart2js-chrome/tests_co19_src_Language_Overview_runtime_type_t02/test.html?crossOriginPort=35341

Runtime error:
TypeError: C.JSNull_methods.get$runtimeType is not a function
TypeError: C.JSNull_methods.get$runtimeType is not a function
    at main (http://127.0.0.1:33907/root_build/generated_compilations/dart2js/tests_co19_src_Language_Overview_runtime_type_t02/runtime_type_t02.js:2204:24)
    at dartMainRunner (http://127.0.0.1:33907/root_dart/pkg/test_runner/lib/src/test_controller.js:315:5)
    at http://127.0.0.1:33907/root_build/generated_compilations/dart2js/tests_co19_src_Language_Overview_runtime_type_t02/runtime_type_t02.js:2538:7
    at http://127.0.0.1:33907/root_build/generated_compilations/dart2js/tests_co19_src_Language_Overview_runtime_type_t02/runtime_type_t02.js:2524:7
    at dartProgram (http://127.0.0.1:33907/root_build/generated_compilations/dart2js/tests_co19_src_Language_Overview_runtime_type_t02/runtime_type_t02.js:2535:5)
    at http://127.0.0.1:33907/root_build/generated_compilations/dart2js/tests_co19_src_Language_Overview_runtime_type_t02/runtime_type_t02.js:2542:3

Deobfuscated error and stack:
TypeError: C.JSNull_methods.get$runtimeType is not a function
TypeError: C.JSNull_methods.get$runtimeType is not a function
    at main           ../../../../../tests/co19/src/Language/Overview/runtime_type_t02.dart 18:24
    at dartMainRunner pkg/test_runner/lib/src/test_controller.js 315:5
    at <fn>           out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Overview_runtime_type_t02/runtime_type_t02.js 2538:7
    at <fn>           out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Overview_runtime_type_t02/runtime_type_t02.js 2524:7
    at dartProgram    out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Overview_runtime_type_t02/runtime_type_t02.js 2535:5
    at <fn>           out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Overview_runtime_type_t02/runtime_type_t02.js 2542:3


exit code:
0

--- To debug locally, run:
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/pkg/test_runner/bin/http_server.dart -p 33907 -c 35341 --network 127.0.0.1 --build-directory=/b/s/w/ir/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/.packages

--- Re-run this test:
python tools/test.py -n dart2js-hostasserts-strong-linux-x64-chrome --dart2js-batch co19/Language/Overview/runtime_type_t02
```

**Comment by fishythefish** [comment]
Possibly related to #42219?

**Comment by rakudrama** [comment]
The test now passes.
