### ISSUE TITLE
NNBD. Future.microtask throws a strange error when computation throws

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42525]
The following programm works withhout NNBD and throw an exception with NNBD in VM

```dart
import "dart:async";

main() {
  var value = [1, 2, 3];
  new Future.microtask(() => throw value)
    .catchError((e) {
    });
}
```
With NNBD this produses no issues in analyzer but in VM
```
Unhandled exception:
type 'Null' is not a subtype of type 'Future<Never>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:160:7)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#3      Future._completeError (dart:async/future_impl.dart:537:5)
#4      _completeWithErrorCallback (dart:async/future.dart:935:10)
#5      new Future.microtask.<anonymous closure> (dart:async/future.dart:203:9)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

Process finished with exit code 255
```
According to the Future.microtask documentation 

> If executing [computation] throws, the returned future is completed with the thrown error

So there must be no error

`Dart VM version: 2.9.0-19.0.dev (dev) (Thu Jun 25 10:48:31 2020 +0200) on "windows_x64" `

**Comment by lrhn** [comment]
This is correct, although annoying, behavior.

You first create a future `Future.microtask(() => throw something);`.
The static type of `() => throw something` is `Never Function()`, so the resulting future gets type `Future<Never>`.

You then call `catchError` on that, but `catchError` must return something of the same type as the future's value type.
So, the `(e) {}` function (with inferred static type `Null Function(dynamic)` must be assignable to `FutureOr<Never> Function(Object)`. it isn't, because `Null` is not assignable to `FutureOr<Never>`.

This fails with Null Safety because `Null` is not assignable to `Never`, whereas it was in the legacy type system. The program is a null safety violation, but because the error handler type is hidden behind `Function`, it isn't detected until runtime.

**Comment by sgrekhov** [comment]
Thank you for the explanation. But, I believe, there is an issue anyway. There is no any diagnostic message pointing to the place in my code where I should search for the problem. How user should search for the solve of this problem if I place this code in a big file with dozens strings of the code? Diagnostic message and stack trace contains no any hints for that. No error in analyzer as well. This can be (and I'm sure will be) a problem for users

**Comment by lrhn** [comment]
ACK. We are optimistically assuming that the return type of the `Future` passed to `catchError` is correct, so we only get an error when trying to assign that type to the actual return type.

We might be able to intercept that assignment and check the type, and then give a better error message (something like "The value returned by 'handleError' passed to 'catchError' is not a $T as required'.
Then again, it might be doing that deep in the handling of the unwrapping of the potential `FutureOr` return type.

**Comment by mkustermann** [comment]
@lrhn Is this a feature request for CFE team? If so, could you label it with `area-frontend`?

**Comment by lrhn** [comment]
I think it's actually a library issue. The checking should happen in dart:async code.

**Comment by marcglasberg** [comment]
I am trying to migrate https://pub.dev/packages/async_redux to NNBD.

I have this code in a test:

```dart
    await storeTester.wait(Action2).then(
      (_) => throw AssertionError(),
      onError: expectAsync1(
        (Object error) {
          expect(error, const TypeMatcher<StoreException>());
          expect(
              error.toString(),
              'Got this unexpected action: Action1 INI.\n'
              'Was expecting: Action2 INI.\n'
              'obtainedIni: [Action1]\n'
              'ignoredIni: []');
        },),);});
```

The solution as:

```dart
    await storeTester.wait(Action2).then(
      (_) {
        throw AssertionError();
        return null;
      },
      onError: expectAsync1(
        (Object error) {
          expect(error, const TypeMatcher<StoreException>());
          expect(
              error.toString(),
              'Got this unexpected action: Action1 INI.\n'
              'Was expecting: Action2 INI.\n'
              'obtainedIni: [Action1]\n'
              'ignoredIni: []');
        },),);});
```

In other words, I have to add an unreachable code in order for this to work:

```dart
(_) {
     throw AssertionError();
     return null;
   },
```

Instead of:
 
```
(_) => throw AssertionError(),
```

I could never have solved this without finding this issue. And it's kind of scary to get an error without any stacktrace. This should never happen.

**Comment by lrhn** [comment]
The problem is type inference, combined with the type of the `onError` parameter being `Function`.

When you do `.then((_) => throw(...), (e, s) => ...)` then type inference tries to infer the type argument, `R`, to `Future<T>.then` invocation from the arguments. The first argument should have type `FutureOr<R> Function (T)`. The actual type is `Never Function(?)`. The `onError` should have type `Function`, with no relation to `R`, so it provides no hint.

So, from the single hint, type inference infers it to be `.then<Never>((_) => throw ..., (e, s) => ...)`. This type-checks statically, but at run-time the `onError` returns a value which is not `Never`.

The solution is to write `.then<void>(....)` so inference doesn't have to guess, because it's guessing based on partial information.

The `then` function is just not very well suited for type inference. I've added the `onError` extension method to help with the same problem for `catchError`, but there is no alternative for `then`. Sadly it's still hard to write `then(..., onError: ...)` in terms of `then` and `onError` when both of the functions change the type, you really do need the combined version for that.

**Comment by lrhn** [comment]
It's hard to show the "stack trace" leading to an asynchronous event because that stack has already been unwound in order to get back to the event loop. It's like debugging something which happened in an earlier iteration of a `for` loop, it's long over when you detect the problem.
So, to fix this, we need to err *early*, as soon as the `then`/`catchError` function is *called*. That's a potentially breaking change because we need to rely on the type of the function. Currently we allow any function, and only check the type of the *value* it returns. If we need an `int`, then a function returning `Object` is accepted, and called, and if it returns an `int`, all is well.
If we err early, then that function, *which works today*, is rejected. That's a breaking change.

Precisely because the type inference doesn't apply, and the `onError` argument is usually a function literal where you can't write a return type, people have sometimes needed to rely on this to make their code work. Which means that making it an error to pass a function which *potentially* returns something wrong, will disallow some functions which *actually* return the right thing.
(And there will still be no static warning, making it hard to figure out what to fix).
