### ISSUE TITLE
Analysis failure: 'thisOrAncestorOfType' was called on null

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#42556]
Error:
```
[Error - 7:52:12 PM] Request textDocument/codeAction failed.
Message: An error occurred while handling textDocument/codeAction request
Code: -32001 
[Error - 7:52:12 PM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The method 'thisOrAncestorOfType' was called on null.
Receiver: null
Tried calling: thisOrAncestorOfType<ClassDeclaration>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SurroundWithSetState.compute (package:analysis_server/src/services/correction/dart/surround_with.dart:244:40)
#2      AssistProcessor._addFromProducers (package:analysis_server/src/services/correction/assist_internal.dart:264:24)
<asynchronous suspension>
#3      AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:173:11)
#4      CodeActionHandler._getAssistActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:170:39)
#5      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:199:7)
#6      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:69:18)
#7      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#8      CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:66:26)
#9      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#10     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:65:26)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#12     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:62:17)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#28     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

Dart Version:
```
Dart SDK version: 2.9.0-19.0.dev.flutter-bec128612c (be) (Wed Jul 1 02:52:57 2020 +0000) on "windows_x64"
```

What I was doing:

 - Untangling a try / finally block

**Comment by DanTup** [comment]
@bwilkerson I just hit this too. I was editing a file that contained:

```dart
void main() {
  print('test');
  print('test');
  print('test');
  print('test');
}
```

I don't know exactly what the state of the file was when the request for code actions was sent to the server, but it failed with the same as above:

```
[Error - 2:42:18 PM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The method 'thisOrAncestorOfType' was called on null.
Receiver: null
Tried calling: thisOrAncestorOfType<ClassDeclaration>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SurroundWithSetState.compute (package:analysis_server/src/services/correction/dart/surround_with.dart:244:40)
#2      AssistProcessor._addFromProducers (package:analysis_server/src/services/correction/assist_internal.dart:264:24)
<asynchronous suspension>
#3      AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:170:11)
#4      CodeActionHandler._getAssistActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:177:39)
#5      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:207:7)
#6      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:77:18)
#7      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#8      CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:74:26)
#9      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#10     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:73:26)
```

The failing code looks like this:

```
var classDeclaration = node.parent.thisOrAncestorOfType<ClassDeclaration>();
if (classDeclaration != null &&
    flutter.isState(classDeclaration.declaredElement)) {
```

I can't reproduce it and I'm not sure what `node` I had for `node.parent` to be null, but is it reasonable to make it just do nothing when there's no parent by adding a `?`?:

```dart
var classDeclaration = node.parent?.thisOrAncestorOfType<ClassDeclaration>();
```

**Comment by DanTup** [comment]
Actually, I could repro with exactly this code and this selection:

![Screenshot 2020-09-29 at 14 49 05](https://user-images.githubusercontent.com/1078012/94567052-f6775b80-0262-11eb-8be9-c2b98c037386.png)

**Comment by bwilkerson** [comment]
Other than a bug in the way ASTs are created, the only node that should ever have a `null` parent is a `CompilationUnit`. That's consistent with the selection you had.

I believe that it's reasonable to not suggest any of the "surround" actions when the selected node is the compilation unit.
