### ISSUE TITLE
dartk failes on co19 async functions tests

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42587]
The following co19 tests fail on dartk (works on other platforms)

https://github.com/dart-lang/co19/blob/master/Language/Statements/Continue/async_loops_t04.dart
https://github.com/dart-lang/co19/blob/master/Language/Statements/Continue/async_loops_t05.dart
https://github.com/dart-lang/co19/blob/master/Language/Statements/Continue/async_loops_t06.dart
https://github.com/dart-lang/co19/blob/master/Language/Statements/Continue/async_loops_t09.dart
https://github.com/dart-lang/co19/blob/master/Language/Statements/Continue/async_loops_t10.dart

The following two test timeouts (works on other platforms)
https://github.com/dart-lang/co19/blob/master/Language/Statements/Continue/async_loops_t07.dart
https://github.com/dart-lang/co19/blob/master/Language/Statements/Continue/async_loops_t08.dart

Example of the failure
```
/========================================================================================================================================\
| dartdevk-strong-linux-release-chrome:co19/Language/Statements/Continue/async_loops_t04 is new and failed (RuntimeError, expected Pass) |
\========================================================================================================================================/

--- Command "dartdevk" (took 178ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartdevc --enable-experiment=non-nullable --enable-experiment=non-nullable --sound-null-safety --ignore-unrecognized-flags --no-summarize -o /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dartdevk-checked-sdk/tests_co19_src_Language_Statements_Continue_async_loops_t04/async_loops_t04.js /b/s/w/ir/cache/builder/sdk/tests/co19/src/Language/Statements/Continue/async_loops_t04.dart -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/async_helper.dill=async_helper -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/expect.dill=expect -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/js.dill=js -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/meta.dill=meta (working directory: /b/s/w/ir/cache/builder/sdk/tests/co19/src/Language/Statements/Continue)

exit code:
0

--- Command "chrome" (took 467ms):
/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:41329/root_build/generated_tests/dartdevk-chrome-checked-sdk/tests_co19_src_Language_Statements_Continue_async_loops_t04/test.html?crossOriginPort=36891

Runtime window.onerror:
window.onunhandledrejection called:

Error: deepEquals([0, 1], [a0, b0], ) fails
   [cause: Expect.equals(expected: <0>, actual: <a0>) fails.]
    at Object.throw_ [as throw] (http://127.0.0.1:41329/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:4028:11)
    at Object._fail (http://127.0.0.1:41329/root_dart/out/ReleaseX64/generated_compilations/dartdevk-checked-sdk/tests_co19_src_Language_Statements_Continue_async_loops_t04/async_loops_t04.js:909:15)
    at Function.deepEquals (http://127.0.0.1:41329/root_dart/out/ReleaseX64/generated_compilations/dartdevk-checked-sdk/tests_co19_src_Language_Statements_Continue_async_loops_t04/async_loops_t04.js:602:18)
    at Function.listEquals (http://127.0.0.1:41329/root_dart/out/ReleaseX64/generated_compilations/dartdevk-checked-sdk/tests_co19_src_Language_Statements_Continue_async_loops_t04/async_loops_t04.js:541:21)
    at test2 (http://127.0.0.1:41329/root_dart/out/ReleaseX64/generated_compilations/dartdevk-checked-sdk/tests_co19_src_Language_Statements_Continue_async_loops_t04/async_loops_t04.js:106:21)
    at test2.next (<anonymous>)
    at http://127.0.0.1:41329/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:34188:33
    at _RootZone.runUnary (http://127.0.0.1:41329/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:34042:58)
    at _FutureListener.thenAwait.handleValue (http://127.0.0.1:41329/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:29026:29)
    at handleValueCallback (http://127.0.0.1:41329/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:29573:49)
    at Function._propagateToListeners (http://127.0.0.1:41329/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:29611:17)
    at async._AsyncCallbackEntry.new.callback (http://127.0.0.1:41329/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:29337:27)
    at Object._microtaskLoop (http://127.0.0.1:41329/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:34303:13)
    at _startMicrotaskLoop (http://127.0.0.1:41329/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:34309:13)
    at http://127.0.0.1:41329/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:29828:9



Deobfuscated error and stack:
window.onunhandledrejection called:

Error: deepEquals([0, 1], [a0, b0], ) fails
   [cause: Expect.equals(expected: <0>, actual: <a0>) fails.]
    at Object.throw_                          out/ReleaseX64/gen/utils/dartdevc/kernel/amd/dart_sdk.js 4028:11
    at Object._fail                           ../../../../../tests/co19/src/Utils/expect.dart 21:5
    at Function.deepEquals                    ../../../../../tests/co19/src/Utils/expect_common.dart 320:7
    at Function.listEquals                    ../../../../../tests/co19/src/Utils/expect_common.dart 248:5
    at test2                                  ../../../../../tests/co19/src/Language/Statements/Continue/async_loops_t04.dart 54:10
    at     at test2.next (<anonymous>)        unparsed
    at <fn>                                   ../../../../lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50
    at _RootZone.runUnary                     ../../../../lib/async/zone.dart 1450:54
    at _FutureListener.thenAwait.handleValue  ../../../../lib/async/future_impl.dart 143:18
    at handleValueCallback                    ../../../../lib/async/future_impl.dart 696:44
    at Function._propagateToListeners         ../../../../lib/async/future_impl.dart 725:32
    at async._AsyncCallbackEntry.new.callback ../../../../lib/async/future_impl.dart 393:9
    at Object._microtaskLoop                  ../../../../lib/async/schedule_microtask.dart 41:11
    at _startMicrotaskLoop                    ../../../../lib/async/schedule_microtask.dart 50:5
    at <fn>                                   ../../../../lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15


exit code:
0

--- To debug locally, run:
/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/cache/builder/sdk/pkg/test_runner/bin/http_server.dart -p 41329 -c 36891 --network 127.0.0.1 --build-directory=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/cache/builder/sdk/.packages

--- Re-run this test:
python tools/test.py -n dartdevk-strong-linux-release-chrome co19/Language/Statements/Continue/async_loops_t04
```
The full log can be found [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8875557506756387040/+/steps/test_results/0/logs/new_test_failures__logs_/0)

**Comment by alexmarkov** [comment]
These failures are on `dartdevk-{strong,weak}-linux-release-chrome` configurations, not `dartk-*`.
So these tests are actually running on DDC and not Dart VM. /cc @nshahan
