### ISSUE TITLE
dart2js craches on co19 test

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42582]
The following code cannot be compiled by dart2js https://github.com/dart-lang/co19/blob/master/Language/Statements/Continue/async_loops_t09.dart

Output is
```
/========================================================================================================================================\
| dart2js-hostasserts-strong-linux-x64-chrome:co19/Language/Statements/Continue/async_loops_t09 is new and failed (Crash, expected Pass) |
\========================================================================================================================================/

--- Command "dart2js" (took 05.000396s):
DART_CONFIGURATION=ReleaseX64 sdk/bin/dart2js_developer --enable-experiment=non-nullable --enable-experiment=non-nullable --test-mode --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/Language/Statements/Continue/async_loops_t09.dart --sound-null-safety --libraries-spec=sdk/lib/libraries.json --platform-binaries=out/ReleaseX64/ --out=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_Language_Statements_Continue_async_loops_t09/async_loops_t09.js

exit code:
253

stdout:
tests/co19/src/Language/Statements/Continue/async_loops_t09.dart:93:8:
Internal Error: The compiler crashed when compiling this element.
Future test3() async {
       ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

stderr:
Unhandled exception:
'package:compiler/src/ssa/nodes.dart': Failed assertion: line 982 pos 16: 'block0 != null && block1 != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      HBasicBlock.assignCommonDominator (package:compiler/src/ssa/nodes.dart:982:16)
#3      HGraph.assignDominators (package:compiler/src/ssa/nodes.dart:359:17)
#4      HGraph.finalize (package:compiler/src/ssa/nodes.dart:345:5)
#5      KernelSsaGraphBuilder._closeFunction (package:compiler/src/ssa/builder_kernel.dart:1628:11)
#6      KernelSsaGraphBuilder._buildGenerator (package:compiler/src/ssa/builder_kernel.dart:1344:9)
#7      KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder_kernel.dart:1231:7)
#8      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:443:15)
#9      CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#10     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:428:21)
#11     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:500:22)
#12     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#13     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:483:18)
#14     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:346:21)
#15     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:80:29)
#16     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:454:30)
#17     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:319:43)
#18     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:450:29)
#19     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:70)
#20     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#21     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:32)
#22     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#23     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:28)
#24     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#25     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:456:18)
#26     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:266:12)
#27     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:282:5)
#28     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:452:16)
#29     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#30     Compiler.emptyQueue (package:compiler/src/compiler.dart:451:14)
#31     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:477:7)
#32     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#33     Compiler.processQueue (package:compiler/src/compiler.dart:470:14)
#34     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:382:5)
#35     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:284:9)
#36     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:432:9)
#37     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#38     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#39     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#40     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#41     new Future.sync (dart:async/future.dart:223:31)
#42     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#43     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#44     Compiler.run (package:compiler/src/compiler.dart:209:41)
#45     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#46     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#49     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#50     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#51     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#54     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

--- Re-run this test:
python tools/test.py -n dart2js-hostasserts-strong-linux-x64-chrome --dart2js-batch co19/Language/Statements/Continue/async_loops_t09
```

**Comment by rakudrama** [comment]
This reduced program crashes the same way:
```dart
void main() {
  int i = 0;

  L0:
  for (String s in  ['a', 'b']) {
    L1:
    do {
      continue L0;
      continue L1;
    } while (i++ < 10);
  }
}
```
I think it has something to do with code following the uncondition `continue`.
If `continue L0;` is made conditional in `test3` (i.e. `if (true) continue L0;`), it passes.

**Comment by sgrekhov** [comment]
The issue still exists on `dart2js` compiler.
```
--- Command "dart2js" (took 01.000343s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart compile js -Dtest_runner.configuration=dart2js-linux-chrome --test-mode --packages=/home/sgrekhov/Google/dart-sdk/sdk/.dart_tool/package_config.json /home/sgrekhov/Google/dart-sdk/sdk/tests/co19/src/Language/Statements/Continue/async_loops_t09.dart --out=/home/sgrekhov/Google/dart-sdk/sdk/out/ReleaseX64/generated_compilations/dart2js-linux-chrome/tests_co19_src_Language_Statements_Continue_async_loops_t09/async_loops_t09.js

exit code:
253

stdout:
file:///home/sgrekhov/Google/dart-sdk/sdk/tests/co19/src/Language/Statements/Continue/async_loops_t09.dart:93:8:
Internal Error: The compiler crashed when compiling this element.
Future test3() async {
       ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.12.0-edge.3177f01f5f492f3780d342dbce91cb21649cfeb8), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Null check operator used on a null value
#0      HBasicBlock.assignCommonDominator (package:compiler/src/ssa/nodes.dart:1041)
#1      HGraph.assignDominators (package:compiler/src/ssa/nodes.dart:402)
#2      HGraph.finalize (package:compiler/src/ssa/nodes.dart:388)
#3      KernelSsaGraphBuilder._closeFunction (package:compiler/src/ssa/builder.dart:2350)
#4      KernelSsaGraphBuilder._buildGenerator (package:compiler/src/ssa/builder.dart:1816)
#5      KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder.dart:1706)
#6      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder.dart:488)
#7      DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:195)
#8      KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder.dart:459)
#9      KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:642)
#10     CompilerTask.measure (package:compiler/src/common/tasks.dart:67)
#11     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:623)
#12     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:451)
#13     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:113)
#14     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:430)
#15     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:393)
#16     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:575)
#17     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:874)
#18     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:198)
#19     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:874)
#20     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:198)
#21     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:872)
#22     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:195)
#23     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:870)
#24     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:278)
#25     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:295)
#26     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:866)
#27     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:198)
#28     Compiler.emptyQueue (package:compiler/src/compiler.dart:865)
#29     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:896)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:198)
#31     Compiler.processQueue (package:compiler/src/compiler.dart:888)
#32     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:511)
#33     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:776)
<asynchronous suspension>
#34     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:329)
<asynchronous suspension>
#35     Compiler.runInternal (package:compiler/src/compiler.dart:328)
<asynchronous suspension>
#36     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:240)
<asynchronous suspension>
#37     compile.<anonymous closure> (package:compiler/compiler_api.dart:273)
<asynchronous suspension>
#38     compile.compilationDone (package:compiler/src/dart2js.dart:764)
<asynchronous suspension>
#39     batchMain.<anonymous closure>.<anonymous closure> (package:compiler/src/dart2js.dart:1439)
<asynchronous suspension>
#40     batchMain.<anonymous closure>.<anonymous closure> (package:compiler/src/dart2js.dart:1450)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dart2js-linux-chrome co19/Language/Statements/Continue/async_loops_t09
[00:02 | 100% | +    0 | -    1]

=== 0 tests passed, 1 failed ===
```
`Dart SDK version: 3.12.0-edge.6c2830d8478d937653b11d4bfff7e79ec70355a3 (main) (Fri Apr 3 17:05:12 2026 -0700) on "linux_x64"`
