### ISSUE TITLE
type 'ParserRecovery' is not a subtype of type 'Identifier'

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#42589]
Running `dart` on the following piece of gibberish:

```dart
main() => bar(<void>());
```

Produces the following error:

```
Crash when compiling file:///[...].dart,
at character offset 5:
type 'ParserRecovery' is not a subtype of type 'Identifier'
#0      BodyBuilder.beginTypeVariable (package:front_end/src/fasta/kernel/body_builder.dart:5618:16)
#1      ComplexTypeParamOrArgInfo.parseVariables (package:_fe_analyzer_shared/src/parser/type_info_impl.dart:1054:16)
#2      Parser.parseLiteralListSetMapOrFunction (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5193:30)
#3      Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4875:14)
#4      Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4732:12)
#5      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4464:13)
#6      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4405:13)
#7      Parser.parseArgumentsRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5603:15)
#8      Parser.parseArguments (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5575:12)
#9      Parser.parseArgumentsOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5556:14)
#10     Parser.parseSend (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5535:13)
#11     Parser.parseSendOrFunctionLiteral (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5262:12)
#12     Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4825:14)
#13     Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4732:12)
#14     Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4464:13)
#15     Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4405:13)
#16     Parser.parseExpressionFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4081:13)
#17     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4006:14)
#18     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:989:14)
#19     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:357:5)
#20     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2630:14)
#21     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2457:14)
#22     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:499:14)
#23     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:354:15)
#24     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:350:14)
<asynchronous suspension>
[...snip...]

#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:997:7)
#1      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:357:5)
#2      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2630:14)
#3      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2457:14)
#4      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:499:14)
#5      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:354:15)
#6      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:350:14)
<asynchronous suspension>
#7      Loader.buildBodies (package:front_end/src/fasta/loader.dart:242:15)
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:357:20)
[...snip...]
```

I believe this is an issue in the front-end?

**Comment by jensjoha** [comment]
This no longer crashes dart.
