### ISSUE TITLE
Suggested code from omit_local_variable_types linter fails at runtime

### ISSUE THREAD

**Issue by TheSpydog** [dart-lang/sdk#42590]
Take this example:

```dart
import 'dart:ffi';
import 'package:ffi/ffi.dart';

class MyStruct extends Struct {
  @Uint32()
  int blah;
}

void main(List<String> arguments) {
  Pointer<MyStruct> a = allocate();
  print("Allocated successfully!");
  free(a);
}
```

This code works as expected, but the `omit_local_variable_types` linter doesn't like it because `a` has an explicit type. In order to fix this, I used Visual Studio Code's "Quick Fix" tool, which changed the contents of `main` to the following:
```dart
  var a = allocate();
  print("Allocated successfully!");
  free(a);
```
Notice the loss of type information. The linter is happy with this change, but when I run the code, it throws the following exception:
```
Unhandled exception:
Invalid argument(s): NativeType does not have a predefined size (@unsized). Unsized NativeTypes do not support [sizeOf] because their size is unknown. Consequently, [allocate], [Pointer.load], [Pointer.store], and [Pointer.elementAt] are not available.
#0      _sizeOf (dart:ffi-patch/ffi_patch.dart:42:56)
#1      sizeOf (dart:ffi-patch/ffi_patch.dart:39:10)
#2      allocate (package:ffi/src/allocation.dart:47:33)
#3      main (file:///<snip>/test.dart:11:11)
```
Which makes complete sense, given that it's trying to allocate an unknown type of native object. My best guess of what it was supposed to have suggested is this: `var a = allocate<MyStruct>()`.

Dart VM version: 2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200) on "macos_x64"
Tested on macOS and Windows.

**Comment by osa1** [comment]
This also happens with functions like `List.filled`. Example:

```dart
void f() {
  List x = List.filled(10, null);
  print(x.runtimeType);
}
```

`dart lint` complains about `List x`, and `dart fix --apply` turns it into `var x`, but that also changes program semantics. Originally it prints `List<dynamic>`, with the fix it prints `List<Null>`. You can't add anything to `List<Null>` other than `null` (and maybe other values with bottom type(s)) so subsequent `add` calls start to fail.

```dart
void f() {
  var x = List.filled(10, null);
  print(x.runtimeType);
  x.add(123); // compile time type error
}
```

**Comment by eernstg** [comment]
I think this issue fits better as a linter issue, so I'm transferring it there.

The proposal would then be that `omit_local_variable_types` should stop flagging local variable declarations with a type annotation in the case where the type annotation changes the outcome of all language processing steps (like type inference, generic function instantiation, integer-literal-with-double-value coercion, etc.), or that the associated quick fix should transform additional parts of the declaration such that all properties (static and dynamic) are preserved.
