### ISSUE TITLE
dart2js crashes with NoSuchMethodError on JS-interop code

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#42612]
I'm getting the following error trying to compile a Flutter app with engine changes in https://github.com/flutter/engine/pull/19562/commits/4776107d0a7abe7328c505eda76750df22db6e56.

```
Target dart2js failed: Exception: Unhandled exception:                  
NoSuchMethodError: The getter 'isChecks' was called on null.
Receiver: null
Tried calling: isChecks
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ProgramBuilder._buildClass.<anonymous closure> (package:compiler/src/js_emitter/program_builder/program_builder.dart:754:14)
#2      TypeTestProperties.forEachProperty.handleTypeTest (package:compiler/src/js_emitter/runtime_type_generator.dart:73:8)
#3      TypeTestProperties.forEachProperty (package:compiler/src/js_emitter/runtime_type_generator.dart:78:21)
#4      ProgramBuilder._buildClass (package:compiler/src/js_emitter/program_builder/program_builder.dart:752:17)
#5      List.forEach (dart:core-patch/growable_array.dart:290:8)
#6      ProgramBuilder.buildProgram.<anonymous closure> (package:compiler/src/js_emitter/program_builder/program_builder.dart:197:15)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#8      ProgramBuilder.buildProgram (package:compiler/src/js_emitter/program_builder/program_builder.dart:196:10)
#9      EmitterImpl.emitProgram.<anonymous closure> (package:compiler/src/js_emitter/startup_emitter/emitter.dart:193:29)
#10     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#11     EmitterImpl.emitProgram (package:compiler/src/js_emitter/startup_emitter/emitter.dart:192:29)
#12     CodeEmitterTask.assembleProgram.<anonymous closure> (package:compiler/src/js_emitter/code_emitter_task.dart:147:26)
#13     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#14     CodeEmitterTask.assembleProgram (package:compiler/src/js_emitter/code_emitter_task.dart:117:12)
#15     JsBackendStrategy.assembleProgram (package:compiler/src/js_model/js_strategy.dart:359:35)
#16     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:390:39)
#17     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:284:9)
#18     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:432:9)
#19     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#20     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#21     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#22     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#23     new Future.sync (dart:async/future.dart:223:31)
#24     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#25     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#26     Compiler.run (package:compiler/src/compiler.dart:209:41)
#27     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#28     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#33     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

The pattern that seems to be triggering the error is the one we use to convert between Dart-side enums to an enum-like API in the CanvasKit JavaScript library. Here's an example:

```dart
@JS()
class SkFilterQualityEnum {
  external SkFilterQuality get None;
  external SkFilterQuality get Low;
  external SkFilterQuality get Medium;
  external SkFilterQuality get High;
}

@JS()
class SkFilterQuality {
  external int get value;
}

final List<SkFilterQuality> _skFilterQualitys = <SkFilterQuality>[
  canvasKitJs.FilterQuality.None,
  canvasKitJs.FilterQuality.Low,
  canvasKitJs.FilterQuality.Medium,
  canvasKitJs.FilterQuality.High,
];

SkFilterQuality toSkFilterQuality(ui.FilterQuality filterQuality) {
  return _skFilterQualitys[filterQuality.index];
}
```

If I comment out all usages of `toSkFilterQuality` (and similar functions) dart2js is happy.

/cc @rakudrama @fishythefish

**Comment by yjbanov** [comment]
I changed the line https://github.com/dart-lang/sdk/blob/34ad5a590836b9a2d679063b3f06d7a692578b31/pkg/compiler/lib/src/js_emitter/program_builder/program_builder.dart#L754 to the following:

```dart
        _classes[_commonElements.jsJavaScriptObjectClass]
            ?.isChecks
            ?.add(_buildStubMethod(name, code));
```

The code compiled and ran correctly, although I've no idea if this is a full fix.

**Comment by vsmenon** [comment]
@sigmundch - looks like this is blocking FW.  Is Yegor's fix a reasonable temporary workaround?

**Comment by yjbanov** [comment]
Is there an update for this issue? This is blocking https://github.com/flutter/engine/pull/19562 and other upcoming Flutter web engine work.

**Comment by sigmundch** [comment]
@yjbanov thanks for the ping, nothing to report, but we have one idea to try out. We'll reach out a bit later today with something to test on your end

**Comment by sigmundch** [comment]
@yjbanov - could you try patching https://dart-review.googlesource.com/c/sdk/+/153943 and see if that resolves the issue?

**Comment by yjbanov** [comment]
Thanks for fixing this, @sigmundch !
