### ISSUE TITLE
tools/run_abi_tests.py: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#42625]
The `vm-dartkb-linux-release-x64-abi` builder is currently crashing with:

```
Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/sdk/tools/run_abi_tests.py", line 215, in <module>
    sys.exit(main())
  File "/b/s/w/ir/cache/builder/sdk/tools/run_abi_tests.py", line 210, in main
    diffAllResults(tests, flags)
  File "/b/s/w/ir/cache/builder/sdk/tools/run_abi_tests.py", line 201, in diffAllResults
    makeLog(diffs, results, logRecords, flags.
  File "/b/s/w/ir/cache/builder/sdk/tools/run_abi_tests.py", line 168, in makeLog
    logs = ["%s: %s" % (str(v), l['log']) for v, l in logRecords.items()]
AttributeError: 'list' object has no attribute 'items'
```

This is caused by the use of `[]` as the fallback value for logRecords, when the expected type is in fact a `dict`.

**Comment by cskau-g** [comment]
I've made https://dart-review.googlesource.com/c/sdk/+/153600 to address this issue.
