### ISSUE TITLE
mixin_deduplication error with partial migration to NNBD in Flutter

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#42656]
In https://github.com/flutter/flutter/pull/61188 I migrated the _foundation_ library to NNBD but several CI jobs fails with the following error:

```
[+9569 ms] [+10229 ms] Unhandled exception:
[   +3 ms]             Bad state: No element
[        ]             #0      Iterable.single (dart:core/iterable.dart:558:25)
[        ]             #1      ReferenceUpdater._findMember (package:vm/transformations/mixin_deduplication.dart:220:12)
[        ]             #2      ReferenceUpdater._resolveNewInterfaceTarget (package:vm/transformations/mixin_deduplication.dart:208:16)
[        ]             #3      ReferenceUpdater.visitMethodInvocation (package:vm/transformations/mixin_deduplication.dart:180:28)
[        ]             #4      MethodInvocation.accept (package:kernel/ast.dart:3950:44)
[        ]             #5      ConditionalExpression.visitChildren (package:kernel/ast.dart:4360:16)
[        ]             #6      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:611:10)
[        ]             #7      Visitor.defaultTreeNode (package:kernel/visitor.dart:523:39)
[        ]             #8      TreeVisitor.defaultExpression (package:kernel/visitor.dart:144:43)
[        ]             #9      TreeVisitor.visitConditionalExpression (package:kernel/visitor.dart:169:7)
[        ]             #10     ConditionalExpression.accept (package:kernel/ast.dart:4355:44)
[        ]             #11     Let.visitChildren (package:kernel/ast.dart:5614:11)
[        ]             #12     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:611:10)
[        ]             #13     Visitor.defaultTreeNode (package:kernel/visitor.dart:523:39)
```

**Comment by alexmarkov** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/154164
