### ISSUE TITLE
the Dart compiler exited unexpectedly. serialization of generic DartType: UnknownType(?) (UnknownType)

### ISSUE THREAD

**Issue by ggichure** [dart-lang/sdk#42655]
I keep getting this error when i run one of my flutter projects.was working fine 

```
Launching lib/main.dart on Web Server in debug mode...
Unhandled exception:
Unsupported operation: serialization of generic DartType: UnknownType(?) (UnknownType)
[38;5;248m#0      BinaryPrinter.defaultDartType  (package:kernel/binary/ast_to_binary.dart:2229:5)[39;49m
[38;5;248m#1      UnknownType.accept  (package:front_end/src/fasta/type_inference/type_schema.dart:82:14)[39;49m
[38;5;248m#2      BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m

[38;5;248m#3      BinaryPrinter.writeNodeList  (package:kernel/binary/ast_to_binary.dart:291:7)[39;49m
[38;5;248m#4      BinaryPrinter.visitInterfaceType  (package:kernel/binary/ast_to_binary.dart:2067:7)[39;49m
[38;5;248m#5      InterfaceType.accept  (package:kernel/ast.dart:7504:42)[39;49m
[38;5;248m#6      BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#7      BinaryPrinter.visitFutureOrType  (package:kernel/binary/ast_to_binary.dart:2088:5)[39;49m
[38;5;248m#8      FutureOrType.accept  (package:kernel/ast.dart:7903:42)[39;49m
[38;5;248m#9      BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#10     BinaryPrinter.visitAsExpression  (package:kernel/binary/ast_to_binary.dart:1614:5)[39;49m
[38;5;248m#11     AsExpression.accept  (package:kernel/ast.dart:4913:44)[39;49m
[38;5;248m#12     BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#13     BinaryPrinter.writeOptionalNode  (package:kernel/binary/ast_to_binary.dart:474:7)[39;49m
[38;5;248m#14     BinaryPrinter.visitReturnStatement  (package:kernel/binary/ast_to_binary.dart:1942:5)[39;49m
[38;5;248m#15     ReturnStatement.accept  (package:kernel/ast.dart:6491:43)[39;49m
[38;5;248m#16     BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#17     BinaryPrinter.writeOptionalNode  (package:kernel/binary/ast_to_binary.dart:474:7)[39;49m
[38;5;248m#18     BinaryPrinter.visitFunctionNode  (package:kernel/binary/ast_to_binary.dart:1325:5)[39;49m
[38;5;248m#19     FunctionNode.accept  (package:kernel/ast.dart:2909:38)[39;49m
[38;5;248m#20     BinaryPrinter.writeFunctionNode  (package:kernel/binary/ast_to_binary.dart:388:10)[39;49m
[38;5;248m#21     BinaryPrinter.visitFunctionExpression  (package:kernel/binary/ast_to_binary.dart:1740:5)[39;49m
[38;5;248m#22     FunctionExpression.accept  (package:kernel/ast.dart:5535:44)[39;49m
[38;5;248m#23     BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#24     BinaryPrinter.visitNamedExpression  (package:kernel/binary/ast_to_binary.dart:1501:5)[39;49m
[38;5;248m#25     NamedExpression.accept  (package:kernel/ast.dart:3813:38)[39;49m
[38;5;248m#26     BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#27     BinaryPrinter.writeNodeList  (package:kernel/binary/ast_to_binary.dart:291:7)[39;49m
[38;5;248m#28     BinaryPrinter.visitArguments  (package:kernel/binary/ast_to_binary.dart:1495:5)[39;49m
[38;5;248m#29     Arguments.accept  (package:kernel/ast.dart:3753:38)[39;49m
[38;5;248m#30     BinaryPrinter.writeArgumentsNode  (package:kernel/binary/ast_to_binary.dart:395:10)[39;49m
[38;5;248m#31     BinaryPrinter.visitConstructorInvocation  (package:kernel/binary/ast_to_binary.dart:1487:5)[39;49m
[38;5;248m#32     ConstructorInvocation.accept  (package:kernel/ast.dart:4154:44)[39;49m
[38;5;248m#33     BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#34     BinaryPrinter.visitNamedExpression  (package:kernel/binary/ast_to_binary.dart:1501:5)[39;49m
[38;5;248m#35     NamedExpression.accept  (package:kernel/ast.dart:3813:38)[39;49m
[38;5;248m#36     BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#37     BinaryPrinter.writeNodeList  (package:kernel/binary/ast_to_binary.dart:291:7)[39;49m
[38;5;248m#38     BinaryPrinter.visitArguments  (package:kernel/binary/ast_to_binary.dart:1495:5)[39;49m
[38;5;248m#39     Arguments.accept  (package:kernel/ast.dart:3753:38)[39;49m
[38;5;248m#40     BinaryPrinter.writeArgumentsNode  (package:kernel/binary/ast_to_binary.dart:395:10)[39;49m
[38;5;248m#41     BinaryPrinter.visitStaticInvocation  (package:kernel/binary/ast_to_binary.dart:1477:5)[39;49m
[38;5;248m#42     StaticInvocation.accept  (package:kernel/ast.dart:4088:44)[39;49m
[38;5;248m#43     BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#44     BinaryPrinter.writeOptionalNode  (package:kernel/binary/ast_to_binary.dart:474:7)[39;49m
[38;5;248m#45     BinaryPrinter.visitReturnStatement  (package:kernel/binary/ast_to_binary.dart:1942:5)[39;49m
[38;5;248m#46     ReturnStatement.accept  (package:kernel/ast.dart:6491:43)[39;49m
[38;5;248m#47     BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#48     BinaryPrinter.writeNodeList  (package:kernel/binary/ast_to_binary.dart:291:7)[39;49m

[38;5;248m#49     BinaryPrinter.visitBlock  (package:kernel/binary/ast_to_binary.dart:1801:5)[39;49m
[38;5;248m#50     Block.accept  (package:kernel/ast.dart:5823:43)[39;49m
[38;5;248m#51     BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#52     BinaryPrinter.writeOptionalNode  (package:kernel/binary/ast_to_binary.dart:474:7)[39;49m
[38;5;248m#53     BinaryPrinter.visitFunctionNode  (package:kernel/binary/ast_to_binary.dart:1325:5)[39;49m
[38;5;248m#54     FunctionNode.accept  (package:kernel/ast.dart:2909:38)[39;49m
[38;5;248m#55     BinaryPrinter.writeFunctionNode  (package:kernel/binary/ast_to_binary.dart:388:10)[39;49m
[38;5;248m#56     BinaryPrinter.visitFunctionDeclaration  (package:kernel/binary/ast_to_binary.dart:2028:5)[39;49m
[38;5;248m#57     FunctionDeclaration.accept  (package:kernel/ast.dart:6988:43)[39;49m
[38;5;248m#58     BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#59     BinaryPrinter.writeNodeList  (package:kernel/binary/ast_to_binary.dart:291:7)[39;49m
[38;5;248m#60     BinaryPrinter.visitBlock  (package:kernel/binary/ast_to_binary.dart:1801:5)[39;49m
[38;5;248m#61     Block.accept  (package:kernel/ast.dart:5823:43)[39;49m
[38;5;248m#62     BinaryPrinter.writeNode  (package:kernel/binary/ast_to_binary.dart:381:10)[39;49m
[38;5;248m#63     BinaryPrinter.writeOptionalNode  (package:kernel/binary/ast_to_binary.dart:474:7)[39;49m
[38;5;248m#64     BinaryPrinter.visitFunctionNode  (package:kernel/binary/ast_to_binary.dart:1325:5)[39;49m
[38;5;248m#65     FunctionNode.accept  (package:kernel/ast.dart:2909:38)[39;49m
[38;5;248m#66     BinaryPrinter.writeFunctionNode  (package:kernel/binary/ast_to_binary.dart:388:10)[39;49m
[38;5;248m#67     BinaryPrinter.writeOptionalFunctionNode  (package:kernel/binary/ast_to_binary.dart:483:7)[39;49m
[38;5;248m#68     BinaryPrinter.visitProcedure  (package:kernel/binary/ast_to_binary.dart:1201:5)[39;49m
[38;5;248m#69     Procedure.accept  (package:kernel/ast.dart:2400:40)[39;49m
[38;5;248m#70     BinaryPrinter.writeProcedureNode  (package:kernel/binary/ast_to_binary.dart:409:10)[39;49m
[38;5;248m#71     BinaryPrinter.writeProcedureNodeList  (package:kernel/binary/ast_to_binary.dart:300:7)[39;49m
[38;5;248m#72     BinaryPrinter.visitClass  (package:kernel/binary/ast_to_binary.dart:1129:5)[39;49m
[38;5;248m#73     Class.accept  (package:kernel/ast.dart:1379:38)[39;49m
[38;5;248m#74     BinaryPrinter.writeClassNode  (package:kernel/binary/ast_to_binary.dart:423:10)[39;49m
[38;5;248m#75     BinaryPrinter.writeClassNodeList  (package:kernel/binary/ast_to_binary.dart:318:7)[39;49m
[38;5;248m#76     BinaryPrinter.visitLibrary  (package:kernel/binary/ast_to_binary.dart:959:5)[39;49m
[38;5;248m#77     Library.accept  (package:kernel/ast.dart:607:38)[39;49m
[38;5;248m#78     BinaryPrinter.writeLibraryNode  (package:kernel/binary/ast_to_binary.dart:402:10)[39;49m
[38;5;248m#79     BinaryPrinter.writeLibraries  (package:kernel/binary/ast_to_binary.dart:708:9)[39;49m
[38;5;248m#80     BinaryPrinter.writeComponentFile.<anonymous closure>  (package:kernel/binary/ast_to_binary.dart:551:7)[39;49m
[38;5;244m#81     Timeline.timeSync  (dart:developer/timeline.dart:163:22)[39;49m
[38;5;248m#82     BinaryPrinter.writeComponentFile  (package:kernel/binary/ast_to_binary.dart:535:14)[39;49m
[38;5;248m#83     IncrementalSerializer.serialize  (package:front_end/src/fasta/incremental_serializer.dart:308:13)[39;49m
[38;5;248m#84     IncrementalSerializer.writePackagesToSinkAndTrimComponent  (package:front_end/src/fasta/incremental_serializer.dart:159:24)[39;49m
[38;5;248m#85     FrontendCompiler.writeDillFile  (package:frontend_server/frontend_server.dart:747:31)[39;49m
[38;5;248m#86     FrontendCompiler.compile  (package:frontend_server/frontend_server.dart:564:13)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#87     _FlutterFrontendCompiler.compile  (package:flutter_frontend_server/server.dart:43:22)[39;49m
[38;5;248m#88     listenAndCompile.<anonymous closure>  (package:frontend_server/frontend_server.dart:1201:26)[39;49m
[38;5;244m#89     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1384:10)[39;49m
[38;5;244m#90     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:357:11)[39;49m
[38;5;244m#91     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:285:7)[39;49m
[38;5;244m#92     _SinkTransformerStreamSubscription._add  (dart:async/stream_transformers.dart:69:11)[39;49m
[38;5;244m#93     _EventSinkWrapper.add  (dart:async/stream_transformers.dart:15:11)[39;49m
[38;5;244m#94     _StringAdapterSink.add  (dart:convert/string_conversion.dart:238:11)[39;49m
[38;5;244m#95     _LineSplitterSink._addLines  (dart:convert/line_splitter.dart:155:13)[39;49m
[38;5;244m#96     _LineSplitterSink.addSlice  (dart:convert/line_splitter.dart:130:5)[39;49m
[38;5;244m#97     StringConversionSinkMixin.add  (dart:convert/string_conversion.dart:163:5)[39;49m
[38;5;244m#98     _SinkTransformerStreamSubscription._handleData  (dart:async/stream_transformers.dart:121:24)[39;49m
[38;5;244m#99     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1384:10)[39;49m
[38;5;244m#100    _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:357:11)[39;49m
[38;5;244m#101    _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:285:7)[39;49m
[38;5;244m#102    _SinkTransformerStreamSubscription._add  (dart:async/stream_transformers.dart:69:11)[39;49m
[38;5;244m#103    _EventSinkWrapper.add  (dart:async/stream_transformers.dart:15:11)[39;49m
[38;5;244m#104    _StringAdapterSink.add  (dart:convert/string_conversion.dart:238:11)[39;49m
[38;5;244m#105    _StringAdapterSink.addSlice  (dart:convert/string_conversion.dart:243:7)[39;49m
[38;5;244m#106    _Utf8ConversionSink.addSlice  (dart:convert/string_conversion.dart:317:20)[39;49m
[38;5;244m#107    _Utf8ConversionSink.add  (dart:convert/string_conversion.dart:310:5)[39;49m
[38;5;244m#108    _ConverterStreamEventSink.add  (dart:convert/chunked_conversion.dart:72:18)[39;49m
[38;5;244m#109    _SinkTransformerStreamSubscription._handleData  (dart:async/stream_transformers.dart:121:24)[39;49m
[38;5;244m#110    _RootZone.runUnaryGuarded  (dart:async/zone.dart:1384:10)[39;49m
[38;5;244m#111    _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:357:11)[39;49m
[38;5;244m#112    _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:285:7)[39;49m
[38;5;244m#113    _SyncStreamControllerDispatch._sendData  (dart:async/stream_controller.dart:808:19)[39;49m
[38;5;244m#114    _StreamController._add  (dart:async/stream_controller.dart:682:7)[39;49m
[38;5;244m#115    _StreamController.add  (dart:async/stream_controller.dart:624:5)[39;49m
[38;5;244m#116    _Socket._onData  (dart:io-patch/socket_patch.dart:2020:41)[39;49m
[38;5;244m#117    _RootZone.runUnaryGuarded  (dart:async/zone.dart:1384:10)[39;49m
[38;5;244m#118    _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:357:11)[39;49m
[38;5;244m#119    _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:285:7)[39;49m
[38;5;244m#120    _SyncStreamControllerDispatch._sendData  (dart:async/stream_controller.dart:808:19)[39;49m
[38;5;244m#121    _StreamController._add  (dart:async/stream_controller.dart:682:7)[39;49m
[38;5;244m#122    _StreamController.add  (dart:async/stream_controller.dart:624:5)[39;49m
[38;5;244m#123    new _RawSocket.<anonymous closure>  (dart:io-patch/socket_patch.dart:1556:33)[39;49m
[38;5;244m#124    _NativeSocket.issueReadEvent.issue  (dart:io-patch/socket_patch.dart:1052:14)[39;49m
[38;5;244m#125    _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)[39;49m
[38;5;244m#126    _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)[39;49m
[38;5;244m#127    _runPendingImmediateCallback  (dart:isolate-patch/isolate_patch.dart:118:13)[39;49m
[38;5;244m#128    _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:169:5)[39;49m

the Dart compiler exited unexpectedly.
Exited (sigterm)
Failed to compile application.



```

**Comment by ggichure** [comment]
switched to from master to stable and it worked fine

**Comment by ggichure** [comment]
switched from master to stable and it worked fine
