### ISSUE TITLE
flutter error

### ISSUE THREAD

**Issue by FASIL2526** [dart-lang/sdk#42659]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.8.4`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.8.4, server version 1.27.4, FATAL error: UnimplementedError: name is an instance of _OperatorName in endClassConstructor
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

For additional log information, please append the contents of
file://C:\Users\fasil\AppData\Local\Temp\report.txt.

**Comment by joaovirgili** [comment]
same here

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.8.4; please re-open if you see this in a recent version of Dart/Flutter.
