### ISSUE TITLE
The method 'addAll' was called on null for pkg/analysis_server/benchmark/benchmarks.dart benchmark

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#42677]
This is an ~intermittent~ failure in the analysis-server benchmark:

```
Problem: Command failed
When: 2020-07-12 18:00:38.162476
Host: z420-runner-05
Occurrences: 1
Run Identifier: BenchmarkRunIdentifier('dart-analysis-server', 'linux-x64', '86741', 'Intel Xeon', 'analysis-server')

Command:
out/ReleaseX64/dart pkg/analysis_server/benchmark/benchmarks.dart run analysis-server

stdout:
Running analysis-server 4 times...
0.342210136: <== {"event":"server.connected","params":{"version":"1.28.0","pid":12937}}
0.361236938: ==> {"id":"0","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
0.378536755: <== {"id":"0"}
0.382156629: ==> {"id":"1","method":"analysis.setAnalysisRoots","params":{"included":["/tmp/.runner/runDir/benchmark/pkg/analysis_server"],"excluded":[]}}
0.71291717: <== {"event":"analysis.errors","params":{"file":"/tmp/.runner/runDir/benchmark/pkg/analysis_server/analysis_options.yaml","errors":[]}}
0.716528314: <== {"event":"analysis.errors","params":{"file":"/tmp/.runner/runDir/benchmark/pkg/analysis_server/pubspec.yaml","errors":[]}}
1.101094136: <== {"id":"1"}
1.146289315: <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1.153867764: ERR: Unhandled exception:
1.156006002: ERR: NoSuchMethodError: The method 'addAll' was called on null.
1.156024534: ERR: Receiver: null
1.156036369: ERR: Tried calling: addAll(Instance(length:1) of '_GrowableList')
1.156051166: ERR: #0 Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:719:7)
1.156078401: ERR: #1 _CustomZone.handleUncaughtError (dart:async/zone.dart:1076:19)
1.156092403: ERR: #2 _CustomZone.runGuarded (dart:async/zone.dart:999:7)
1.156108013: ERR: #3 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
1.156124642: ERR: #4 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
1.156139386: ERR: #5 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
1.156154668: ERR: #6 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
1.156170514: ERR: #7 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

stderr:
Unhandled exception:
Bad state: expectAsync0() may only be called within a test.
#0 expectAsync0 (package:test_api/src/frontend/expect_async.dart:250:5)
#1 Server._badDataFromServer (file:///tmp/.runner/runDir/benchmark/pkg/analysis_server/test/integration/support/integration_tests.dart:655:42)
#2 Server.listenToOutput.<anonymous closure> (file:///tmp/.runner/runDir/benchmark/pkg/analysis_server/test/integration/support/integration_tests.dart:527:7)
#3 _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#4 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#5 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#6 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#7 _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#8 _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#9 _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#10 _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#11 StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#12 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#13 _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#14 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#15 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#16 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#17 _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#18 _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#19 _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#20 _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#21 _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#22 _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#23 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#24 _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#25 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#26 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#27 _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#28 _StreamController._add (dart:async/stream_controller.dart:682:7)
#29 _StreamController.add (dart:async/stream_controller.dart:624:5)
#30 _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#31 _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#32 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#33 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#34 _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#35 _StreamController._add (dart:async/stream_controller.dart:682:7)
#36 _StreamController.add (dart:async/stream_controller.dart:624:5)
#37 new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#38 _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#39 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#40 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#41 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#42 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
Command exited with non-zero status 255
real 8.11
user 8.95
sys 0.72
```

cc @sortie @scheglov

**Comment by devoncarew** [comment]
cc @MichaelRFairhurst

**Comment by bwilkerson** [comment]
I believe that this has been fixed by https://dart-review.googlesource.com/c/sdk/+/154261. Please let me know if that's not the case.
