### ISSUE TITLE
Dart VM. Crash report (Dart version=2.8.4 (stable))

### ISSUE THREAD

**Issue by rustkas** [dart-lang/sdk#42737]
I would like to share code example with crash report. I hope it help to do Dart VM better.

Code example:

```
import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

List<Isolate> isolates;

void main() async {
  await start();
  print('Press enter to exit');
  await stdin.first;
  stop();
  await stderr.flush();
  await stdout.flush();
  exit(0);
}

void start() async {
  isolates = [];
  isolates.add(await Isolate.spawn(runSomething, 'first'));
  isolates.add(await Isolate.spawn(runSomething, 'second'));
  isolates.add(await Isolate.spawn(runSomething, 'third'));
  // await stdout.flush();
  // await stderr.flush();
}

void runSomething(String arg) async {
  print('arg: $arg');

  var request =
      await HttpClient().getUrl(Uri.parse('https://swapi.co/api/people/1'));

  var response = await request.close();
  await stdin.first;
  await for (var contents in response.transform(Utf8Decoder())) {
    print(contents);
   
  }
}

void stop() {
  for (var i in isolates) {
    if (i != null) {
      i.kill(priority: Isolate.immediate);
      i = null;
      print('Killed');
    }
  }
}

```

Crash report:

```
ex_01_spawn_string>dart bin/main.dart
arg: first
arg: second
Press enter to exit
arg: third

===== CRASH =====
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=000000013FF074F0
Unhandled exception:
Bad state: No element
#0      Stream.first.<anonymous closure> (dart:async/stream.dart:1261:13)
#1      _RootZone.runGuarded (dart:async/zone.dart:1362:10)
#2      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#3      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:15)
#4      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:286:7)
#5      _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:787:19)
#6      _StreamController._closeUnchecked (dart:async/stream_controller.dart:644:7)
#7      _StreamController.close (dart:async/stream_controller.dart:637:5)
#8      _Socket._onData (dart:io-patch/socket_patch.dart:1989:21)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#13     _StreamController._add (dart:async/stream_controller.dart:655:7)
#14     _StreamController.add (dart:async/stream_controller.dart:597:5)
#15     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1534:35)
#16     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1012:18)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
version=2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200) on "windows_x64"
pid=163276, thread=161840, isolate=(null)(0000000000000000)
isolate_instructions=0, vm_instructions=13fba1010
Stack dump aborted because InitialRegisterCheck failed.
Unhandled exception:
FileSystemException: Error retrieving socket type, path = '' (OS Error: ╨Э╨╡╨▓╨╡╤А
╨╜╤Л╨╣ ╨┤╨╡╤Б╨║╤А╨╕╨┐╤В╨╛╤А.
, errno = 6)
#0      _StdIOUtils._nativeSocketType (dart:io-patch/stdio_patch.dart:48:7)
#1      new _RawSocket._readPipe (dart:io-patch/socket_patch.dart:1558:36)
#2      new _Socket._readPipe (dart:io-patch/socket_patch.dart:1839:28)
#3      _StdIOUtils._getStdioInputStream (dart:io-patch/stdio_patch.dart:23:32)
#4      stdin (dart:io/stdio.dart:410:26)
#5      runSomething (file:///E:/Users/tol_pc/Desktop/dart/%23src_projects/woolha/dart-spawn-kill-send-message-to-isolate/ex_01_spawn_string/bin/main.dart:33:9)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Unhandled exception:
FileSystemException: Error retrieving socket type, path = '' (OS Error: ╨Э╨╡╨▓╨╡╤А
╨╜╤Л╨╣ ╨┤╨╡╤Б╨║╤А╨╕╨┐╤В╨╛╤А.
, errno = 6)
#0      _StdIOUtils._nativeSocketType (dart:io-patch/stdio_patch.dart:48:7)
#1      new _RawSocket._readPipe (dart:io-patch/socket_patch.dart:1558:36)
#2      new _Socket._readPipe (dart:io-patch/socket_patch.dart:1839:28)
#3      _StdIOUtils._getStdioInputStream (dart:io-patch/stdio_patch.dart:23:32)
#4      stdin (dart:io/stdio.dart:410:26)
#5      runSomething (file:///E:/Users/tol_pc/Desktop/dart/%23src_projects/woolha/dart-spawn-kill-send-message-to-isolate/ex_01_spawn_string/bin/main.dart:33:9)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

**Comment by julemand101** [comment]
Your code seems to run without problems on my machine. Can you help me translate the error message you get?
```
FileSystemException: Error retrieving socket type, path = '' (OS Error: ╨Э╨╡╨▓╨╡╤А
╨╜╤Л╨╣ ╨┤╨╡╤Б╨║╤А╨╕╨┐╤В╨╛╤А.
```

Also, there are some problems in your code about `async` methods not returning `Future<T>`. I have cleaned your code but I don't think that is the problem you have (both your and my example works on my machine):
```
import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

List<Isolate> isolates;

Future<void> main() async {
  await start();
  print('Press enter to exit');
  await stdin.first;
  stop();
  await stderr.flush();
  await stdout.flush();
  exit(0);
}

Future<void> start() async {
  isolates = [];
  isolates.add(await Isolate.spawn(runSomething, 'first'));
  isolates.add(await Isolate.spawn(runSomething, 'second'));
  isolates.add(await Isolate.spawn(runSomething, 'third'));
  // await stdout.flush();
  // await stderr.flush();
}

Future<void> runSomething(String arg) async {
  print('arg: $arg');

  final request =
      await HttpClient().getUrl(Uri.parse('https://swapi.co/api/people/1'));

  final response = await request.close();
  await stdin.first;
  await response.transform(const Utf8Decoder()).forEach(print);
}

void stop() {
  for (var i in isolates) {
    if (i != null) {
      i.kill(priority: Isolate.immediate);
      i = null;
      print('Killed');
    }
  }
}
```

**Comment by mkustermann** [comment]
Before the actual crash in the reported issue, we see two exceptions of the form:
```
Unhandled exception:
FileSystemException: Error retrieving socket type, path = '' (OS Error: ╨Э╨╡╨▓╨╡╤А
╨╜╤Л╨╣ ╨┤╨╡╤Б╨║╤А╨╕╨┐╤В╨╛╤А.
, errno = 6)
#0      _StdIOUtils._nativeSocketType (dart:io-patch/stdio_patch.dart:48:7)
#1      new _RawSocket._readPipe (dart:io-patch/socket_patch.dart:1558:36)
#2      new _Socket._readPipe (dart:io-patch/socket_patch.dart:1839:28)
#3      _StdIOUtils._getStdioInputStream (dart:io-patch/stdio_patch.dart:23:32)
#4      stdin (dart:io/stdio.dart:410:26)
```

Looking at the code it seems that multiple isolates are trying to access the shared standard input to the process (`dart:io`s `stdin`). 

With a slightly reduced example
```dart
import 'dart:io';
import 'dart:isolate';

void main() async {
  final rp = ReceivePort();
  await Future.wait([
    Isolate.spawn(runSomething, 'first'),
    Isolate.spawn(runSomething, 'second'),
    Isolate.spawn(runSomething, 'third'),
    Isolate.spawn(runSomething, 'fourth'),
    Isolate.spawn(runSomething, 'sixth'),
  ]);
  print('Press enter to exit');
  await rp.first;
}

void runSomething(String arg) async {
  print('arg: $arg');
  final client = HttpClient();
  final request = await client.getUrl(Uri.parse('https://google.com'));
  final response = await request.close();
  response.drain();
  await stdin.first;
}
```
I can reproduce a similar type of exception on Linux:
```
% out/ReleaseX64/dart repro.dart << EOF
EOF
arg: second
arg: first
Press enter to exit
arg: fourth
arg: third
arg: sixth
Unhandled exception:
FileSystemException: Failed to get type of stdio handle (fd 0), path = '' (OS Error: Bad file descriptor, errno = 9)
#0      _StdIOUtils._getStdioInputStream (dart:io-patch/stdio_patch.dart:13:7)
#1      stdin (dart:io/stdio.dart:407:33)
#2      runSomething (file:///.../repro.dart:24:9)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Unhandled exception:
FileSystemException: Failed to get type of stdio handle (fd 0), path = '' (OS Error: Bad file descriptor, errno = 9)
#0      _StdIOUtils._getStdioInputStream (dart:io-patch/stdio_patch.dart:13:7)
#1      stdin (dart:io/stdio.dart:407:33)
#2      runSomething (file:///.../repro.dart:24:9)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Unhandled exception:
FileSystemException: Failed to get type of stdio handle (fd 0), path = '' (OS Error: Bad file descriptor, errno = 9)
#0      _StdIOUtils._getStdioInputStream (dart:io-patch/stdio_patch.dart:13:7)
#1      stdin (dart:io/stdio.dart:407:33)
#2      runSomething (file:///.../repro.dart:24:9)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
^C
```

I suspect this is a bug in `dart:io` where we use an invalid handle. On POSIX platforms the operating system might give back a bad error message, but on Windows it might be more severe to use a freed / invalid handle.

/cc @zichangg 
/cc @aam (who might have a windows machine)

**Comment by rustkas** [comment]
@mkustermann Yes, you are absolutely right. I am researching multithreading capability of Dart. Multiple isolates are trying to access the shared standard input to the process (dart:ios stdin) it.

I think if I can reproduce crash - it's very important to share this with the Dart developer community.

I wonder, is it possible isolate ` await stdin.first;` expression in the isolate (with try-catch for instance or something).

**Comment by rustkas** [comment]
@julemand101 
 I decode OS message: ╨Э╨╡╨▓╨╡╤А╨╜╤Л╨╣ ╨┤╨╡╤Б╨║╤А╨╕╨┐╤В╨╛╤А
The translation is "Invalid descriptor".

Without any outside requests this code runs fine in Dart 2.5.1 ([Dart Online IDE](https://www.jdoodle.com/execute-dart-online/))

Code:
```
import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

List<Isolate> isolates;

Future<void> main() async {
  await start();
  print('Press enter to exit');
  await stdin.first;
  stop();
  exit(0);
}

Future<void> start() async {
  isolates = [];
  isolates.add(await Isolate.spawn(runSomething, 'first'));
  isolates.add(await Isolate.spawn(runSomething, 'second'));
  isolates.add(await Isolate.spawn(runSomething, 'third'));
  // await stdout.flush();
  // await stderr.flush();
}

Future<void> runSomething(String arg) async {
  print('arg: $arg');

  //final request =
  //    await HttpClient().getUrl(Uri.parse('https://www.google.com/'));

  //final response = await request.close();
  await stdin.first;
  //await response.transform(const Utf8Decoder()).forEach(print);
}

void stop() {
  for (var i in isolates) {
    if (i != null) {
      i.kill(priority: Isolate.immediate);
      i = null;
      print('Killed');
    }
  }
}
```

**Comment by rustkas** [comment]
Dart VM 2.6.0 in online IDE [Repl.it](https://repl.it/languages/dart) also do not produce such exceptions and do not crash.
