### ISSUE TITLE
Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#42761]
While editing code, got multiple codeAction errors:

```
[Error - 12:34:25 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 12:34:25 PM] An error occurred while handling textDocument/codeAction request: type 'IfStatementImpl' is not a subtype of type 'Expression'
#0      AddExplicitCast.compute (package:analysis_server/src/services/correction/dart/add_explicit_cast.dart:20:16)
#1      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1519:22)
<asynchronous suspension>
#2      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart)
#3      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1536:24)
<asynchronous suspension>
#4      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1035:11)
<asynchronous suspension>
#5      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:184:35)
<asynchronous suspension>
#6      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:208:46)
<asynchronous suspension>
#7      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:172:7)
#8      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:67:18)
#9      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#10     CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:64:26)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#12     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:63:26)
#13     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#14     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:60:17)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#23     Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#24     _rootRunUnary (dart:async/zone.dart:1198:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#30     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#31     _rootRun (dart:async/zone.dart:1190:13)
#32     _CustomZone.run (dart:async/zone.dart:1093:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[Error - 12:40:32 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 12:40:32 PM] An error occurred while handling textDocument/codeAction request: type 'ArgumentListImpl' is not a subtype of type 'Expression'
#0      AddExplicitCast.compute (package:analysis_server/src/services/correction/dart/add_explicit_cast.dart:20:16)
#1      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1519:22)
<asynchronous suspension>
#2      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart)
#3      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1536:24)
<asynchronous suspension>
#4      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1035:11)
<asynchronous suspension>
#5      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:184:35)
<asynchronous suspension>
#6      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:208:46)
<asynchronous suspension>
#7      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:172:7)
#8      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:67:18)
#9      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#10     CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:64:26)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#12     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:63:26)
#13     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#14     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:60:17)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#23     Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#24     _rootRunUnary (dart:async/zone.dart:1198:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#30     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#31     _rootRun (dart:async/zone.dart:1190:13)
#32     _CustomZone.run (dart:async/zone.dart:1093:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[Error - 12:40:39 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 12:40:39 PM] An error occurred while handling textDocument/codeAction request: type 'ArgumentListImpl' is not a subtype of type 'Expression'
#0      AddExplicitCast.compute (package:analysis_server/src/services/correction/dart/add_explicit_cast.dart:20:16)
#1      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1519:22)
<asynchronous suspension>
#2      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart)
#3      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1536:24)
<asynchronous suspension>
#4      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1035:11)
<asynchronous suspension>
#5      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:184:35)
<asynchronous suspension>
#6      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:208:46)
<asynchronous suspension>
#7      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:172:7)
#8      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:67:18)
#9      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#10     CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:64:26)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#12     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:63:26)
#13     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#14     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:60:17)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#23     Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#24     _rootRunUnary (dart:async/zone.dart:1198:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#30     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#31     _rootRun (dart:async/zone.dart:1190:13)
#32     _CustomZone.run (dart:async/zone.dart:1093:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## Dart Version
```
Dart VM version: 2.9.0-14.1.beta (beta) (Tue Jun 9 10:52:57 2020 +0200) on "windows_x64"
```

**Comment by bwilkerson** [comment]
This appears to have been fixed on 6/4/20 by https://dart-review.googlesource.com/c/sdk/+/150163. My guess is that we cut the branch for 2.9.0-14.1.beta prior to that commit. Please let us know if you can reproduce this on a more recent build.

**Comment by timsneath** [comment]
Thanks. Yeah, possibly -- I switched to the beta because of another bug we
were trying to track down. Will let you know if it crops up again.

**Comment by timsneath** [comment]
Just hit something similar on today's master, which is from 7/17. Since the error is slightly different, I've filed it as https://github.com/dart-lang/sdk/issues/42786. Thanks, @bwilkerson!

**Comment by wondertalik** [comment]
Dart SDK version: 2.12.3 (stable) (Wed Apr 14 11:02:39 2021 +0200) on "macos_x64"

Got this error. Possible related to this issue.

```
[Error - 1:02:53 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 1:02:53 PM] An error occurred while handling textDocument/codeAction request: type 'double' is not a subtype of type 'int'
#0      toOffset (package:analysis_server/src/lsp/mapping.dart:1108:42)
#1      CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:75:25)
#2      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#3      CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:73:17)
<asynchronous suspension>
#4      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:183:22)
<asynchronous suspension>
#5      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:301:26)
<asynchronous suspension>
```
