### ISSUE TITLE
Dart2js crash when rolling null safe fake_async internally

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#42847]
See cl/323361672 and related tap ID OCL:323361672:BASE:323362254:1595865429409:6cc09134.

```
/tmp/dart2js-extract-archives-YIVHDR/third_party/dart/fake_async/lib/fake_async.dart:177:9:
Internal Error: No local for j:field(FakeAsync_run_closure._captured_T_2). Options: {Instance of 'ThisLocal': j:field(FakeAsync_run_closure._captured_this_0), local(FakeAsync.run#callback): j:field(FakeAsync_run_closure._captured_callback_1), type_variable_local(j:type_variable(run.T)): j:field(FakeAsync_run_closure._captured_T_3)}
  T run<T>(T Function(FakeAsync self) callback) =>
        ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.9.0-edge.9dca49e71e06f9ba3710d3c4d65619f30547f4ca), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Unhandled exception:
Assertion failure: No local for j:field(FakeAsync_run_closure._captured_T_2). Options: {Instance of 'ThisLocal': j:field(FakeAsync_run_closure._captured_this_0), local(FakeAsync.run#callback): j:field(FakeAsync_run_closure._captured_callback_1), type_variable_local(j:type_variable(run.T)): j:field(FakeAsync_run_closure._captured_T_3)}
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      KernelClosureClassInfo.getLocalForField (package:compiler/src/js_model/closure.dart:707:5)
#2      KernelSsaGraphBuilder.visitFunctionNode.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:4957:52)
#3      JsElementEnvironment.forEachInstanceField.<anonymous closure> (package:compiler/src/js_model/element_map_impl.dart:2506:10)
#4      JsKernelToElementMap._forEachClassMember.<anonymous closure> (package:compiler/src/js_model/element_map_impl.dart:1102:8)
#5      Iterable.forEach (dart:core/iterable.dart:283:30)
#6      RecordEnv.forEachMember (package:compiler/src/js_model/env.dart:362:23)
#7      JsKernelToElementMap._forEachClassMember (package:compiler/src/js_model/element_map_impl.dart:1101:9)
#8      JsElementEnvironment.forEachClassMember (package:compiler/src/js_model/element_map_impl.dart:2412:16)
#9      JsElementEnvironment.forEachInstanceField (package:compiler/src/js_model/element_map_impl.dart:2504:5)
#10     KernelSsaGraphBuilder.visitFunctionNode (package:compiler/src/ssa/builder_kernel.dart:4953:25)
#11     FunctionNode.accept (package:kernel/ast.dart:2909:38)
#12     KernelSsaGraphBuilder.visitFunctionExpression (package:compiler/src/ssa/builder_kernel.dart:4978:29)
#13     FunctionExpression.accept (package:kernel/ast.dart:5535:44)
#14     KernelSsaGraphBuilder._visitPositionalArguments (package:compiler/src/ssa/builder_kernel.dart:3540:16)
#15     KernelSsaGraphBuilder._visitArgumentsForStaticTarget (package:compiler/src/ssa/builder_kernel.dart:3667:33)
#16     KernelSsaGraphBuilder.visitStaticInvocation (package:compiler/src/ssa/builder_kernel.dart:3751:11)
#17     StaticInvocation.accept (package:kernel/ast.dart:4088:44)
#18     KernelSsaGraphBuilder.visitReturnStatement (package:compiler/src/ssa/builder_kernel.dart:1746:23)
#19     ReturnStatement.accept (package:kernel/ast.dart:6491:43)
#20     KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder_kernel.dart:1275:23)
#21     KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:443:15)
#22     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:745:15)
#23     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:428:21)
#24     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:500:22)
#25     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#26     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:483:18)
#27     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:346:21)
#28     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:80:29)
#29     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:454:30)
#30     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:319:43)
#31     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:450:29)
#32     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:462:70)
#33     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#34     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:462:32)
#35     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#36     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:28)
#37     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:745:15)
#38     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:18)
#39     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:266:12)
#40     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:282:5)
#41     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:454:16)
#42     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#43     Compiler.emptyQueue (package:compiler/src/compiler.dart:453:14)
#44     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:479:7)
#45     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#46     Compiler.processQueue (package:compiler/src/compiler.dart:472:14)
#47     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:384:5)
#48     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:286:9)
#49     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:434:9)
#50     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#51     Compiler.compileFromKernel (package:compiler/src/compiler.dart:407:14)
#52     Compiler.runInternal (package:compiler/src/compiler.dart:259:13)
<asynchronous suspension>
#53     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:214:38)
#54     new Future.sync (dart:async/future.dart:223:31)
#55     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:214:20)
#56     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#57     Compiler.run (package:compiler/src/compiler.dart:211:41)
#58     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#59     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#60     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#61     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#62     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#63     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#64     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#65     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#66     BazelInputProvider.readFromUri (package:compiler/src/source_file_provider.dart)
<asynchronous suspension>
#67     CompilerImpl.setupSdk.<anonymous closure> (package:compiler/src/apiimpl.dart:62:25)
#68     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#69     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#70     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#71     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#72     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#73     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#74     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#75     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#76     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#77     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by jakemac53** [comment]
Marked as a P1 because this package is necessary for flutter_test (and thus it is blocking the flutter tech preview)

**Comment by franklinyow** [comment]
@sigmundch  FYI

**Comment by sigmundch** [comment]
Thanks @jakemac53 

@fishythefish I wonder if this relates to a type-parameter optimization. @jakemac53 let us know if adding `--disable-rti-optimizations` circumvents this issue.

We may be able to reduce it to a smaller repro form the internal failure, let us get back to you on that.

**Comment by sigmundch** [comment]
FWIW - this minimal program seems to replicate the exception above when I run in the internal environment:

```dart
import 'package:fake_async/fake_async.dart';

main() {
    final FakeAsync fakeAsync = FakeAsync();
    fakeAsync.run((FakeAsync localFakeAsync) {
      print("this is the body, woowhoo!");
      assert(fakeAsync == localFakeAsync);
    }
}
```

However the same program with the external dependencies doesn't trip this issue at first.

**Comment by sigmundch** [comment]
I was able to narrow it down. This appears to be a bug related to mixed mode when the code is migrated but the dependency is not.

If I try the dependencies from the open source I cannot repro as you noticed, but if I switch `clock` to use the non migrated version and keep it at 2.8 (as it is internally), then this issue shows up.

I imagine you'll be able to work around this by rolling clock before fake_async.

**Comment by jakemac53** [comment]
Ah ok! Clock has already been migrated but at the time I was running the presubmits it had not (I was landing them in parallel). I will try re-running the presubmits now.

Still seems like a high priority issue though as mixed mode will be a very common thing :).

**Comment by fishythefish** [comment]
I'm currently investigating a weak mode failure on a language test that seems to exhibit the same issue. When I have a fix, I'll see if that closes this issue as well.

**Comment by fishythefish** [comment]
https://dart-review.googlesource.com/c/sdk/+/156445 landed, @jakemac53 would you be able to confirm if this fixes your issue?

**Comment by jakemac53** [comment]
I can't really check internal easily any more (all its deps are updated now), but I verified the failure in the current dev externally and that I cannot reproduce it with a custom build at HEAD, so I would call this fixed 👍

**Comment by sigmundch** [comment]
I still had a copy of the broken state locally. I verified that it was still crashed on the commit before the fix and no longer crashes in master. :fireworks:
