### ISSUE TITLE
dart2js crash compiling a constructor which may throw one of it's arguments

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#42883]
This showed up in `package:shelf`. Unless I'm mistaken this seems to need a few pretty specific pieces to reproduce:

- There needs to be a constructor argument which is used in an initializer list.
- That argument needs to be in a `throw` statement in the constructor body.
- That `throw` statement needs to be in a `catch` block.
- The constructor needs to be referenced through a forwarding generative constructor which is used in the program.

There might be some other way to arrive at this stack trace, but I haven't found it. This is the smallest repro I've found:

```dart
void main() {
  Crash('');
}

class Crash {
  final String s;

  Crash(String s) : this.named(s);

  Crash.named(String t) : s = t {
    try {} catch (_) {
      throw t;
    }
  }
}
```

The dart2js stack trace is:

```
Unhandled exception:
type 'HRef' is not a subtype of type 'HLocalValue'
#0      LocalsHandler.getLocal (package:compiler/src/ssa/locals_handler.dart:398:7)
#1      LocalsHandler.readLocal (package:compiler/src/ssa/locals_handler.dart:374:32)
#2      KernelSsaGraphBuilder.visitVariableGet (package:compiler/src/ssa/builder_kernel.dart:3389:29)
#3      VariableGet.accept (package:kernel/ast.dart:3103:44)
#4      KernelSsaGraphBuilder._buildInitializers (package:compiler/src/ssa/builder_kernel.dart:1022:29)
#5      KernelSsaGraphBuilder._inlineSuperOrRedirectCommon.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:1194:7)
#6      KernelSsaGraphBuilder._inlinedFrom.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:920:21)
#7      CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:745:15)
#8      KernelSsaGraphBuilder._inlinedFrom (package:compiler/src/ssa/builder_kernel.dart:918:14)
#9      KernelSsaGraphBuilder._inlineSuperOrRedirectCommon (package:compiler/src/ssa/builder_kernel.dart:1168:5)
#10     KernelSsaGraphBuilder._inlineRedirectingInitializer (package:compiler/src/ssa/builder_kernel.dart:1124:5)
#11     KernelSsaGraphBuilder._buildInitializers (package:compiler/src/ssa/builder_kernel.dart:1032:9)
#12     KernelSsaGraphBuilder._buildConstructor (package:compiler/src/ssa/builder_kernel.dart:748:5)
#13     KernelSsaGraphBuilder._visitInlinedFunction (package:compiler/src/ssa/builder_kernel.dart:5990:9)
#14     KernelSsaGraphBuilder._doInline (package:compiler/src/ssa/builder_kernel.dart:5980:5)
#15     KernelSsaGraphBuilder._tryInlineMethod.doInlining.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:5662:11)
#16     KernelSsaGraphBuilder._inlinedFrom.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:920:21)
#17     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:745:15)
#18     KernelSsaGraphBuilder._inlinedFrom (package:compiler/src/ssa/builder_kernel.dart:918:14)
#19     KernelSsaGraphBuilder._tryInlineMethod.doInlining (package:compiler/src/ssa/builder_kernel.dart:5657:7)
#20     KernelSsaGraphBuilder._tryInlineMethod (package:compiler/src/ssa/builder_kernel.dart:5669:17)
#21     KernelSsaGraphBuilder._pushStaticInvocation (package:compiler/src/ssa/builder_kernel.dart:4723:9)
#22     KernelSsaGraphBuilder.visitConstructorInvocation (package:compiler/src/ssa/builder_kernel.dart:5280:5)
#23     ConstructorInvocation.accept (package:kernel/ast.dart:4157:44)
#24     KernelSsaGraphBuilder.visitExpressionStatement (package:compiler/src/ssa/builder_kernel.dart:1714:18)
#25     ExpressionStatement.accept (package:kernel/ast.dart:5787:43)
#26     KernelSsaGraphBuilder.visitBlock (package:compiler/src/ssa/builder_kernel.dart:1680:17)
#27     Block.accept (package:kernel/ast.dart:5826:43)
#28     KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder_kernel.dart:1275:23)
#29     KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:443:15)
#30     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:745:15)
#31     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:428:21)
#32     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:500:22)
#33     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#34     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:483:18)
#35     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:346:21)
#36     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:80:29)
#37     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:454:30)
#38     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:319:43)
#39     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:450:29)
#40     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:462:70)
#41     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#42     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:462:32)
#43     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#44     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:28)
#45     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:745:15)
#46     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:18)
#47     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:266:12)
#48     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:282:5)
#49     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:454:16)
#50     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#51     Compiler.emptyQueue (package:compiler/src/compiler.dart:453:14)
#52     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:479:7)
#53     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#54     Compiler.processQueue (package:compiler/src/compiler.dart:472:14)
#55     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:384:5)
#56     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:286:9)
#57     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:434:9)
#58     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#59     Compiler.compileFromKernel (package:compiler/src/compiler.dart:407:14)
#60     Compiler.runInternal (package:compiler/src/compiler.dart:259:13)
<asynchronous suspension>
#61     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:214:38)
#62     new Future.sync (dart:async/future.dart:223:31)
#63     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:214:20)
#64     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#65     Compiler.run (package:compiler/src/compiler.dart:211:41)
#66     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#67     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#68     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#69     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#70     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#71     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#72     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#73     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#74     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#75     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#76     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by kevmoo** [comment]
Amazing repro, @natebosch – that's a doozie!
