### ISSUE TITLE
Process leak when the starting process throws

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#42918]
From how I read the documentation of `Process.start` I'd think that if I start a process it dies with my main thread (i.e. when my script dies, so do the launched process) (when launched in `ProcessStartMode.normal` mode).

This - at least on Linux - is not the case when my script throws an unhandled exception; take this script:

```
import "dart:io";

main(List<String> args) async {
  if (args.length > 0) {
    List<int> big = new List<int>(100000000);
    while(true) {
      await new Future.delayed(new Duration(milliseconds: 100));
    }
    return;
  }
  Process process = await Process.start(Platform.resolvedExecutable, [Platform.script.toString(), "--leak"]);
  await new Future.delayed(new Duration(milliseconds: 1000));
  print("If this process is killed with Ctrl-C the sub-process is killed too...");
  await new Future.delayed(new Duration(milliseconds: 3000));
  throw "But now that it throws instead, the sub-process lives!";
}
```

As the script states, if I "manually" exit the script with Ctrl-C the process is killed as I'd expect, but if I let it crash it lives on, e.g.:
```
$ ps aux | grep "leak"
jensj    1416017  0.0  0.0   6088   836 pts/11   S+   10:27   0:00 grep --color=auto leak

$ out/ReleaseX64/dart test.dart
If this process is killed with Ctrl-C the sub-process is killed too...
^C

$ ps aux | grep "leak"
jensj    1416070  0.0  0.0   6088   900 pts/11   S+   10:27   0:00 grep --color=auto leak

$ out/ReleaseX64/dart test.dart
If this process is killed with Ctrl-C the sub-process is killed too...
Unhandled exception:
But now that it throws instead, the sub-process lives!
#0      main (test.dart:15:3)
<asynchronous suspension>
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

$ ps aux | grep "leak"
jensj    1416095  9.8  1.3 946444 902992 pts/11  Sl   10:27   0:00 out/ReleaseX64/dart test.dart --leak
jensj    1416156  0.0  0.0   6088   908 pts/11   S+   10:28   0:00 grep --color=auto leak
```

Is this a bug or am I reading the documentation wrong?

/cc @lrhn

**Comment by lrhn** [comment]
The documentation is not crystal clear. There is nothing in the docs for using `ProcessStartMode.normal` which says that the child process is killed when the parent process dies. It's indirectly hinted by the `ProcessStartMode.detached` documentation, because in that mode the child process *can* live on without its parent process.
(The `ProcessStartMode.deatchedWithStdio` mode also suggests that the child should die if its stdin/stdout/stderr is closed, I don't know if that's actually true).

The child process *should* probably along with the parent process, though, so I consider it a bug.
Seems to be an issue on Windows as well.
