### ISSUE TITLE
Flow analysis assertion when trying to access `ClassName?.hashCode`.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42957]
The following code should cause a compile-time error:
```dart
class A {}
f() => A?.hashCode;
```
With null safety enabled, this causes an analyzer assertion:
```
  'package:_fe_analyzer_shared/src/flow_analysis/flow_analysis.dart': Failed assertion: line 2452 pos 12: '_stack.isEmpty': is not true.
  #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
  #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
  #2      _FlowAnalysisImpl.finish (package:_fe_analyzer_shared/src/flow_analysis/flow_analysis.dart:2452:12)
  #3      FlowAnalysisHelper.topLevelDeclaration_exit (package:analyzer/src/dart/resolver/flow_analysis_visitor.dart:250:10)
  #4      ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:1135:23)
  #5      FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4821:49)
  #6      ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:796:23)
  #7      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2119:49)
  #8      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:735:10)
  #9      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:136:7)
  #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
  #11     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:135:11)
  #12     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:107:14)
  #13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:216:15)
  #14     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:106:43)
  #15     AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1294:63)
  #16     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
  #17     AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1271:20)
  #18     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1222:14)
```

**Comment by stereotype441** [comment]
I can no longer reproduce this, even if I go back to code as of Aug 5.  I'm not sure what happend, but as the bug is not reproducible, I'm closing the issue.
