### ISSUE TITLE
dart2js crash: Runtime type information not available for type_variable_local(j:type_variable(combinedReducer.S)) in (local(combinedReducer#previousState), local(combinedReducer#reducer), j:anonymous_closure_local(combinedReducer__closure)) for j:closure_call(combinedReducer__closure.call).

### ISSUE THREAD

**Issue by nk2IsHere** [dart-lang/sdk#42959]
Dart SDK version: 2.9.0-21.10.beta (beta) (Tue Jul 21 10:46:30 2020 +0200) on "macos_x64"
macOS 11.0 beta 4 (20A5343i)
Chrome Stable Version 84.0.4147.105 (Official Build) (64-bit)

Code sample:
```
class Action {}
typedef Reducer<S> = Future<S> Function(Action action, S previousState);

Reducer<S> combinedReducer<S>(
  Iterable<Reducer<S>> reducers
) => (Action action, S previousState) async {
  return reducers.fold<Future<S>>(
    Future.sync(() => previousState),
    (previousState, reducer) async {
      return reducer(action, await previousState);
    }
  );
};

void main() {
  combinedReducer([
    (action, state) async {}
  ]);
}
```

While running `flutter build web` the compiler has crashed with following error:
(Please note that running code using `flutter run` causes no errors
Moreover, running dart2js with `-O2` won't cause any problems, but running with `-O3` will)

```
test.dart:4:12:
Internal Error: Runtime type information not available for type_variable_local(j:type_variable(combinedReducer.S)) in (local(combinedReducer#previousState), local(combinedReducer#reducer), j:anonymous_closure_local(combinedReducer__closure)) for j:closure_call(combinedReducer__closure.call).
Reducer<S> combinedReducer<S>(

...

Unhandled exception:
Assertion failure: Runtime type information not available for type_variable_local(j:type_variable(combinedReducer.S)) in (local(combinedReducer#previousState), local(combinedReducer#reducer), j:anonymous_closure_local(combinedReducer__closure)) for j:closure_call(combinedReducer__closure.call).
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      LocalsHandler.readLocal (package:compiler/src/ssa/locals_handler.dart:326:11)
#2      TypeBuilder._buildEnvironmentForType (package:compiler/src/ssa/type_builder.dart:280:12)
#3      TypeBuilder.analyzeTypeArgumentNewRti (package:compiler/src/ssa/type_builder.dart:198:9)
#4      KernelSsaGraphBuilder._buildGenerator (package:compiler/src/ssa/builder_kernel.dart:1332:31)
#5      KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder_kernel.dart:1231:7)
#6      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:476:13)
#7      CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#8      KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:428:21)
#9      KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:500:22)
#10     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#11     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:483:18)
#12     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:346:21)
#13     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:80:29)
#14     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:454:30)
#15     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:319:43)
#16     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:450:29)
#17     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:70)
#18     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#19     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:32)
#20     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#21     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:28)
#22     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#23     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:456:18)
#24     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:266:12)
#25     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:282:5)
#26     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:452:16)
#27     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#28     Compiler.emptyQueue (package:compiler/src/compiler.dart:451:14)
#29     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:477:7)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#31     Compiler.processQueue (package:compiler/src/compiler.dart:470:14)
#32     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:382:5)
#33     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:284:9)
#34     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:432:9)
#35     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#36     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#37     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#38     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#39     new Future.sync (dart:async/future.dart:223:31)
#40     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#41     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#42     Compiler.run (package:compiler/src/compiler.dart:209:41)
#43     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#44     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#45     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#47     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#48     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#49     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by sigmundch** [comment]
Thank you so much for the very small repro instructions! They make investigating and fixing issues like these a lot easier for our team.

Turns out that we recently fixed this in 7e8348f4ce87f89235154e974c799de57473c4f4. This is not part of the 2.9 SDK, but it is already part of the 2.10 dev channel.

I just verified that your example crashes in the older SDK, but now compiles successfully on recent dev releases, yay!

**Comment by nk2IsHere** [comment]
I have played with this issue and found more meaningful examples:

This code compiles fine with `-O4` and `-O3`
Please note, that the success does not depend on type variable naming, e.g.: _A can be changed to A 
```
typedef Reducer<A, S> = Future<S> Function(A action, S previousState);

Reducer<_A, _S> combinedReducer<_A, _S>(
  Iterable<Reducer<_A, _S>> reducers
) => (_A action, _S previousState) async {
  _S state = previousState;
  for (final Reducer<_A, _S> reducer in reducers)
    state = await reducer(action, state);

  return state;
};

void main() {
  combinedReducer<int, int>([
    (action, state) async {}
  ]);
}
```

This causes the same error:
Please note that 
```
class Action {}
typedef Reducer<S> = Future<S> Function(Action action, S previousState);

Reducer<M> combinedReducer<M>(
  Iterable<Reducer<M>> reducers
) => (Action action, M previousState) async {
  M state = previousState;
  for (final Reducer<M> reducer in reducers)
    state = await reducer(action, state);

  return state;
};

void main() {
  combinedReducer([
    (action, state) async {}
  ]);
}
```

**Comment by nk2IsHere** [comment]
Thanks a lot! I hope this patch will arrive to flutter beta soon

**Comment by sigmundch** [comment]
In the meantime, note that besides using `-O2` you can also workaround this by disabling the one optimization that had this bug by passing `--disable-rti-optimization` to dart2js.
