### ISSUE TITLE
Calling treemapFromJson from package:vm_snapshot_analysis occasionally fails.

### ISSUE THREAD

**Issue by peterdjlee** [dart-lang/sdk#42969]
Calling treemapFromJson results in a null pointer exception for some v8 snapshots.

## reproduction steps
1. `flutter create testing`
2. `cd testing/`
3. `flutter build apk --analyze-size`

## exception

NoSuchMethodError: NoSuchMethodError: The method 'putIfAbsent' was called on null.
Receiver: null
Tried calling: putIfAbsent("OneByteString", Closure: () => Map<String, dynamic>)

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _addChild (package:vm_snapshot_analysis/treemap.dart:211:27)
#2      _addSymbol (package:vm_snapshot_analysis/treemap.dart:236:10)
#3      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:178:7)
#4      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:84:5)
#5      SizeAnalyzer.analyzeApkSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:70:59)
<asynchronous suspension>
#6      buildGradleApp (package:flutter_tools/src/android/gradle.dart:512:59)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#15     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#22     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#23     _rootRun (dart:async/zone.dart:1190:13)
#24     _CustomZone.run (dart:async/zone.dart:1093:19)
#25     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by peterdjlee** [comment]
cc @mraleph
