### ISSUE TITLE
co19/Language/Functions/External_Functions/not_connected_to_a_body_t01 turned from DartkCrash to RuntimeError

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#42987]
Seemingly with https://dart-review.googlesource.com/c/sdk/+/157481 the test status changed from DartkCrash to RuntimeError:
- https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-nnbd-linux-release-simarm64/49
- https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-nnbd-linux-release-x64/1139
- https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-linux-release-x64/9186.

```
/======================================================================================================================================================================\
| dartkp-strong-linux-release-simarm64:co19/Language/Functions/External_Functions/not_connected_to_a_body_t01 failed again (DartkCrash -> RuntimeError, expected Pass) |
\======================================================================================================================================================================/

--- Command "vm_compile_to_kernel []" (took 03.000281s):
DART_CONFIGURATION=ReleaseSIMARM64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseSIMARM64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp/tests_co19_src_Language_Functions_External_Functions_not_connected_to_a_body_t01/out.dill /b/s/w/ir/tests/co19/src/Language/Functions/External_Functions/not_connected_to_a_body_t01.dart --enable-experiment=non-nullable --packages=/b/s/w/ir/.packages -Ddart.vm.product=false -Ddart.developer.causal_async_stacks=true --sound-null-safety

exit code:
0

--- Command "precompiler" (took 05.000093s):
DART_CONFIGURATION=ReleaseSIMARM64 out/ReleaseSIMARM64/gen_snapshot --enable-experiment=non-nullable --snapshot-kind=app-aot-elf --elf=/b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp/tests_co19_src_Language_Functions_External_Functions_not_connected_to_a_body_t01/out.aotsnapshot --sound-null-safety --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp/tests_co19_src_Language_Functions_External_Functions_not_connected_to_a_body_t01/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 25ms):
DART_CONFIGURATION=ReleaseSIMARM64 rm /b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp/tests_co19_src_Language_Functions_External_Functions_not_connected_to_a_body_t01/out.dill

exit code:
0

--- Command "vm" (took 93ms):
DART_CONFIGURATION=ReleaseSIMARM64 out/ReleaseSIMARM64/dart_precompiled_runtime --sound-null-safety --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseSIMARM64/generated_compilations/dartkp/tests_co19_src_Language_Functions_External_Functions_not_connected_to_a_body_t01/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.throws() fails
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:20)
#1      Expect.throws (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:235)
#2      main (file:///b/s/w/ir/tests/co19/src/Language/Functions/External_Functions/not_connected_to_a_body_t01.dart:29)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168)

--- Re-run this test:
python tools/test.py -n dartkp-strong-linux-release-simarm64 co19/Language/Functions/External_Functions/not_connected_to_a_body_t01
```

**Comment by johnniwinther** [comment]
This is a VM issue. See https://github.com/dart-lang/sdk/issues/42750

**Comment by alexmarkov** [comment]
Another related issue: https://github.com/dart-lang/sdk/issues/42182
