### ISSUE TITLE
gen_snapshot --loading_unit_manifest crash

### ISSUE THREAD

**Issue by chingjun** [dart-lang/sdk#42985]
Stack trace during crash:

```
dart::Serializer::WriteUnitSnapshot (this=this@entry=0x7fffffffce88, unit=unit@entry=0x7ffff74b50b8, program_hash=<optimized out>, program_hash@entry=951688299)
    at runtime/vm/clustered_snapshot.cc:5963
5963	  intptr_t num_base_objects = unit->parent()->num_objects();
(gdb) bt
#0  dart::Serializer::WriteUnitSnapshot (this=this@entry=0x7fffffffce88, unit=unit@entry=0x7ffff74b50b8, program_hash=<optimized out>, program_hash@entry=951688299)
    at runtime/vm/clustered_snapshot.cc:5963
#1  0x0000555556c8c428 in dart::FullSnapshotWriter::WriteUnitSnapshot (this=0x7fffffffd230, units=0x7fffffffd3b0, unit=0x7ffff74b50b8, program_hash=951688299)
    at runtime/vm/clustered_snapshot.cc:6855
#2  0x0000555556ab517f in dart::CreateAppAOTSnapshot (callback=<optimized out>, callback@entry=0x5555568a76e0 <dart::bin::StreamingWriteCallback(void*, unsigned char const*, long)>,
    callback_data=0xf85bfc75700, strip=true, as_elf=<optimized out>, debug_callback_data=<optimized out>, units=0x38b99c6b, units@entry=0x7fffffffd3b0, unit=0x7ffff74b50b8, program_hash=951688299)
    at runtime/vm/dart_api_impl.cc:6653
#3  0x0000555556ab5784 in dart::Split (next_callback=next_callback@entry=0x5555568a77f0 <dart::bin::NextElfCallback(void*, long, void**, void**)>,
    next_callback_data=next_callback_data@entry=0xf85bfc75340, strip=<optimized out>, as_elf=false,
    write_callback=write_callback@entry=0x5555568a76e0 <dart::bin::StreamingWriteCallback(void*, unsigned char const*, long)>, close_callback=0x5555568a77c0 <dart::bin::StreamingCloseCallback(void*)>)
    at runtime/vm/dart_api_impl.cc:6717
#4  0x0000555556ab5e02 in Dart_CreateAppAOTSnapshotAsElfs (next_callback=0x5555568a77f0 <dart::bin::NextElfCallback(void*, long, void**, void**)>, next_callback_data=0x38b99c6b, strip=false,
    write_callback=0x5555568a76e0 <dart::bin::StreamingWriteCallback(void*, unsigned char const*, long)>, close_callback=0x0) at runtime/vm/dart_api_impl.cc:6862
#5  0x00005555568a6f09 in dart::bin::CreateAndWritePrecompiledSnapshot () at runtime/bin/gen_snapshot.cc:730
#6  dart::bin::CreateIsolateAndSnapshot (inputs=...) at runtime/bin/gen_snapshot.cc:856
#7  dart::bin::main (argc=<optimized out>, argv=<optimized out>) at runtime/bin/gen_snapshot.cc:968
#8  0x00007ffff7d2dbbd in __libc_start_main () from /usr/grte/v4/lib64/libc.so.6
#9  0x00005555568a5029 in _start () at ../sysdeps/x86_64/start.S:108
quit)
```

Context: cl/323858212

cc @rmacnak-google 

Thanks.

**Comment by a-siva** [comment]
@chingjun could you give us a little bit more context on this crash, the command line that led to this crash would be helpful.

**Comment by chingjun** [comment]
I have posted the instructions to reproduce in the internal link.
