### ISSUE TITLE
Mirrors - newInstance does not properly represent sub-type constraints

### ISSUE THREAD

**Issue by nathanfranke** [dart-lang/sdk#42995]
```
$ dart --version
Dart SDK version: 2.9.0 (stable) (Unknown timestamp) on "linux_x64"
```

Hi all! I had an issue in my project and I'm not sure if it's a bug or there's another way to work around it.

Here is some code that demonstrates my problem.

```dart
import 'dart:mirrors';

class A<X> {
	X v;
	A();
	
	whatIsMyGeneric() {
		print(reflectClass(X).simpleName.toString());
	}
}

create<T>() {
	return reflectClass(T).newInstance(Symbol(""), []).reflectee;
}

main() {
	create<A<String>>().whatIsMyGeneric();
}
```

Unfortunately, the code provides a runtime error as seen here:
```
$ dart src/test.dart 
Unhandled exception:
Invalid argument(s): dynamic
#0      _Mirrors._makeLocalClassMirror (dart:mirrors-patch/mirrors_impl.dart:1456:44)
#1      _Mirrors.reflectClass (dart:mirrors-patch/mirrors_impl.dart:1468:21)
#2      reflectClass (dart:mirrors-patch/mirrors_patch.dart:49:19)
#3      A.whatIsMyGeneric (file:///home/nathanfranke/workspace/DartTest/src/test.dart:8:9)
#4      main (file:///home/nathanfranke/workspace/DartTest/src/test.dart:17:22)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

I want `whatIsMyGeneric` to print the value of `X` (which should be `String`)

Thanks everyone in advance for the help

**Comment by rmacnak-google** [comment]
`reflectClass` strips away type arguments. It behaves like `reflectType(T).originalDeclaration`. You want `reflectType`.

**Comment by nathanfranke** [comment]
Thanks, but `TypeMirror` doesn't have a method `newInstance`. How should I construct that type?
