### ISSUE TITLE
Memory leak on kernel file in memory

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#43015]
4fb4e0af2d43fecdb69be4eb121561047bb952d6 uncovered a memory leak in gen_kernel which make our ASAN bots fail.

```
[1884/1889] ACTION //utils/dartdev:generate_dartdev_kernel(//build/toolchain/linux:clang_x64)
FAILED: gen/dartdev.dill 
python ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=/b/s/w/ir/cache/builder/sdk/.packages --snapshot=gen/dartdev.dill --snapshot-depfile=/b/s/w/ir/cache/builder/sdk/out/ReleaseASANX64/gen/dartdev.dill.d --snapshot-kind=kernel --dfe=/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart /b/s/w/ir/cache/builder/sdk/out/ReleaseASANX64/gen/utils/dartdev/generate_dartdev_kernel.dart.dill
Command failed: ./dart --deterministic --packages=/b/s/w/ir/cache/builder/sdk/.packages --snapshot=gen/dartdev.dill --snapshot-depfile=/b/s/w/ir/cache/builder/sdk/out/ReleaseASANX64/gen/dartdev.dill.d --snapshot-kind=kernel --dfe=/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart /b/s/w/ir/cache/builder/sdk/out/ReleaseASANX64/gen/utils/dartdev/generate_dartdev_kernel.dart.dill
output: 
=================================================================
==23160==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 11423368 byte(s) in 1 object(s) allocated from:
    #0 0x557f88cd796d in malloc ../recipe_cleanup/clangshYTOG/llvm_build_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x557f88fd054b in dart::bin::DartUtils::ReadFile(unsigned char**, long*, void*) ../../out/ReleaseASANX64/../../runtime/bin/dartutils.cc:296:38
    #2 0x557f88d0e6b7 in dart::bin::TryReadFile(char const*, unsigned char**, long*) ../../out/ReleaseASANX64/../../runtime/bin/dfe.cc:280:3
    #3 0x557f88d0e6b7 in dart::bin::DFE::TryReadKernelFile(char const*, unsigned char**, long*) ../../out/ReleaseASANX64/../../runtime/bin/dfe.cc:428:8
    #4 0x557f88d0e49c in dart::bin::DFE::ReadScript(char const*, unsigned char**, long*) const ../../out/ReleaseASANX64/../../runtime/bin/dfe.cc:233:8
    #5 0x557f88d0a69b in dart::bin::Snapshot::GenerateKernel(char const*, char const*, char const*) ../../out/ReleaseASANX64/../../runtime/bin/snapshot_utils.cc:468:7
    #6 0x557f88d10e11 in dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*) ../../out/ReleaseASANX64/../../runtime/bin/main.cc:876:5
    #7 0x557f88d13b5a in dart::bin::main(int, char**) ../../out/ReleaseASANX64/../../runtime/bin/main.cc:1242:14
    #8 0x557f88d15e19 in main ../../out/ReleaseASANX64/../../runtime/bin/main.cc:1282:3
    #9 0x7f2aed27582f in __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:291

SUMMARY: AddressSanitizer: 11423368 byte(s) leaked in 1 allocation(s).

ninja: build stopped: subcommand failed.
ninja -C out/ReleaseASANX64 -j200 -l64 runtime done.
```

The caller is not freeing this memory:

https://github.com/dart-lang/sdk/blob/3059f6464735e9e3e2bf895a3e16d4eb5f606207/runtime/bin/dfe.cc#L256-L264

**Comment by dcharkes** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/158006
