### ISSUE TITLE
[vm/ffi] object.cc: 19461: error: expected: IsFinalized()

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#43016]
Changing sample Dart code uncovered hitting an assert. I'll investigate. (Approving failure)

```
/==========================================================================\
| samples/ffi/sqlite/test/sqlite_test broke (Pass -> Crash, expected Pass) |
\==========================================================================/

--- Command "vm" (took 12.000943s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/samples/ffi/sqlite/test/sqlite_test.dart

exit code:
-6

stdout:
00:00 [32m+0[0m: sqlite integration test[0m

1 Chocolade chip cookie Chocolade cookie foo

stderr:
../../runtime/vm/object.cc: 19461: error: expected: IsFinalized()
version=2.10.0-edge.730578ed2d1f60443baa329faf96cb042a1e234a (be) (Tue Aug 11 09:17:49 2020 +0000) on "linux_x64"
pid=20108, thread=20190, isolate_group=main(0x555b30310580), isolate=main(0x555b3031c900)
isolate_instructions=555b2d6774c0, vm_instructions=555b2d6774c0
  pc 0x0000555b2da682ac fp 0x00007f3a0a27bd40 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x0000555b2d6775f2 fp 0x00007f3a0a27be20 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x0000555b2d9a0e44 fp 0x00007f3a0a27bea0 dart::AbstractType::IsSubtypeOf(dart::AbstractType const&, dart::Heap::Space, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*) const+0x414
  pc 0x0000555b2defc109 fp 0x00007f3a0a27bef0 dart::CompileType::Union(dart::CompileType*)+0xc9
  pc 0x0000555b2defe9e0 fp 0x00007f3a0a27c3b0 dart::PhiInstr::RecomputeType()+0x70
  pc 0x0000555b2defa1dd fp 0x00007f3a0a27c820 dart::FlowGraphTypePropagator::Propagate()+0x24d
  pc 0x0000555b2def9ec8 fp 0x00007f3a0a27c930 dart::FlowGraphTypePropagator::Propagate(dart::FlowGraph*)+0x48
  pc 0x0000555b2df12990 fp 0x00007f3a0a27c940 out/DebugX64/dart+0x2355990
  pc 0x0000555b2df12145 fp 0x00007f3a0a27c9e0 dart::CompilerPass::Run(dart::CompilerPassState*) const+0x175
  pc 0x0000555b2df1265f fp 0x00007f3a0a27ca00 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)+0x17f
  pc 0x0000555b2db4ad7f fp 0x00007f3a0a27d0f0 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0x73f
  pc 0x0000555b2db4beab fp 0x00007f3a0a27d310 out/DebugX64/dart+0x1f8eeab
  pc 0x0000555b2db4ca34 fp 0x00007f3a0a27d3b0 dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)+0x134
  pc 0x0000555b2dadd9ba fp 0x00007f3a0a27d5a0 dart::DRT_StackOverflow(dart::NativeArguments)+0x92a
  pc 0x00007f3a16101502 fp 0x00007f3a0a27d5e0 Unknown symbol
  pc 0x00007f3a08d815d9 fp 0x00007f3a0a27d678 Unknown symbol
  pc 0x00007f3a08efbd8e fp 0x00007f3a0a27d710 Unknown symbol
  pc 0x00007f3a08ef4da3 fp 0x00007f3a0a27d770 Unknown symbol
  pc 0x00007f3a08ef414c fp 0x00007f3a0a27d818 Unknown symbol
  pc 0x00007f3a08ef4bd0 fp 0x00007f3a0a27d880 Unknown symbol
  pc 0x00007f3a08eb4b53 fp 0x00007f3a0a27d900 Unknown symbol
  pc 0x00007f3a08eb4981 fp 0x00007f3a0a27d978 Unknown symbol
  pc 0x00007f3a08eb4133 fp 0x00007f3a0a27da20 Unknown symbol
  pc 0x00007f3a08eb9daa fp 0x00007f3a0a27da70 Unknown symbol
  pc 0x00007f3a08eb99ce fp 0x00007f3a0a27dae8 Unknown symbol
  pc 0x00007f3a08eb1945 fp 0x00007f3a0a27db70 Unknown symbol
  pc 0x00007f3a08eb0692 fp 0x00007f3a0a27dbb8 Unknown symbol
  pc 0x00007f3a08eff2d1 fp 0x00007f3a0a27dc18 Unknown symbol
  pc 0x00007f3a08efece2 fp 0x00007f3a0a27dc50 Unknown symbol
  pc 0x00007f3a08efcb70 fp 0x00007f3a0a27dce8 Unknown symbol
  pc 0x00007f3a08ef4da3 fp 0x00007f3a0a27dd48 Unknown symbol
  pc 0x00007f3a08ef414c fp 0x00007f3a0a27ddf0 Unknown symbol
  pc 0x00007f3a08ef4bd0 fp 0x00007f3a0a27de58 Unknown symbol
  pc 0x00007f3a08eb4b53 fp 0x00007f3a0a27ded8 Unknown symbol
  pc 0x00007f3a08eb4981 fp 0x00007f3a0a27df50 Unknown symbol
  pc 0x00007f3a08eb4133 fp 0x00007f3a0a27dff8 Unknown symbol
  pc 0x00007f3a08eb9daa fp 0x00007f3a0a27e048 Unknown symbol
  pc 0x00007f3a08eb99ce fp 0x00007f3a0a27e0c0 Unknown symbol
  pc 0x00007f3a08eb1945 fp 0x00007f3a0a27e148 Unknown symbol
  pc 0x00007f3a08efebe4 fp 0x00007f3a0a27e198 Unknown symbol
  pc 0x00007f3a08ef414c fp 0x00007f3a0a27e240 Unknown symbol
  pc 0x00007f3a08ef3f35 fp 0x00007f3a0a27e2a8 Unknown symbol
  pc 0x00007f3a08ea7731 fp 0x00007f3a0a27e320 Unknown symbol
  pc 0x00007f3a08ea7431 fp 0x00007f3a0a27e390 Unknown symbol
  pc 0x00007f3a08ea6840 fp 0x00007f3a0a27e430 Unknown symbol
  pc 0x00007f3a08eb2482 fp 0x00007f3a0a27e4a0 Unknown symbol
  pc 0x00007f3a08eb2329 fp 0x00007f3a0a27e4f0 Unknown symbol
  pc 0x00007f3a155cc17d fp 0x00007f3a0a27e538 Unknown symbol
  pc 0x00007f3a155cbdd1 fp 0x00007f3a0a27e578 Unknown symbol
  pc 0x00007f3a155cbcd0 fp 0x00007f3a0a27e5b8 Unknown symbol
  pc 0x00007f3a155cbad0 fp 0x00007f3a0a27e5f8 Unknown symbol
  pc 0x00007f3a08ef2f62 fp 0x00007f3a0a27e678 Unknown symbol
  pc 0x00007f3a08ef068e fp 0x00007f3a0a27e6b0 Unknown symbol
  pc 0x00007f3a08ef0393 fp 0x00007f3a0a27e6f8 Unknown symbol
  pc 0x00007f3a155ac7b7 fp 0x00007f3a0a27e738 Unknown symbol
  pc 0x00007f3a155ac6bb fp 0x00007f3a0a27e770 Unknown symbol
  pc 0x00007f3a16101a3d fp 0x00007f3a0a27e7e8 Unknown symbol
  pc 0x0000555b2d8caaf3 fp 0x00007f3a0a27e880 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x113
  pc 0x0000555b2d8ca42f fp 0x00007f3a0a27e920 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x29f
  pc 0x0000555b2d8cddb3 fp 0x00007f3a0a27e990 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)+0x233
  pc 0x0000555b2d929832 fp 0x00007f3a0a27eb80 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x5f2
  pc 0x0000555b2d9708b1 fp 0x00007f3a0a27ec10 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x221
  pc 0x0000555b2d9717d9 fp 0x00007f3a0a27ec90 dart::MessageHandler::TaskCallback()+0x359
  pc 0x0000555b2db2ee3b fp 0x00007f3a0a27ed30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x1cb
  pc 0x0000555b2db2f879 fp 0x00007f3a0a27ed80 dart::ThreadPool::Worker::Main(unsigned long)+0x179
  pc 0x0000555b2da61259 fp 0x00007f3a0a27eed0 out/DebugX64/dart+0x1ea4259
-- End of DumpStackTrace
[exit     : sp(0) fp(0x7f3a0a27d5e0) pc(0)]
[dart     : sp(0x7f3a0a27d5f0) fp(0x7f3a0a27d678) pc(0x7f3a08d815d9) file:///b/s/w/ir/samples/ffi/sqlite/test/sqlite_test.dart_::_main_<anonymous closure> ]
[dart     : sp(0x7f3a0a27d688) fp(0x7f3a0a27d710) pc(0x7f3a08efbd8e) package:test_api/src/backend/declarer.dart_Declarer_test_<anonymous closure>__async_op_<anonymous closure>__async_op ]
[dart     : sp(0x7f3a0a27d720) fp(0x7f3a0a27d770) pc(0x7f3a08ef4da3) package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__registerUnaryCallback@211444339_<anonymous closure>_<anonymous closure> ]
[dart     : sp(0x7f3a0a27d780) fp(0x7f3a0a27d818) pc(0x7f3a08ef414c) package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__run@211444339 ]
[dart     : sp(0x7f3a0a27d828) fp(0x7f3a0a27d880) pc(0x7f3a08ef4bd0) package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__registerUnaryCallback@211444339_<anonymous closure> ]
[dart     : sp(0x7f3a0a27d890) fp(0x7f3a0a27d900) pc(0x7f3a08eb4b53) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x7f3a0a27d910) fp(0x7f3a0a27d978) pc(0x7f3a08eb4981) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x7f3a0a27d988) fp(0x7f3a0a27da20) pc(0x7f3a08eb4133) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x7f3a0a27da30) fp(0x7f3a0a27da70) pc(0x7f3a08eb9daa) dart:async__FutureListener@4048458_handleValue ]
[dart     : sp(0x7f3a0a27da80) fp(0x7f3a0a27dae8) pc(0x7f3a08eb99ce) dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]
[dart     : sp(0x7f3a0a27daf8) fp(0x7f3a0a27db70) pc(0x7f3a08eb1945) dart:async__Future@4048458__propagateToListeners@4048458 ]
[dart     : sp(0x7f3a0a27db80) fp(0x7f3a0a27dbb8) pc(0x7f3a08eb0692) dart:async__Future@4048458__completeWithValue@4048458 ]
[dart     : sp(0x7f3a0a27dbc8) fp(0x7f3a0a27dc18) pc(0x7f3a08eff2d1) dart:async__AsyncAwaitCompleter@4048458_complete ]
[dart     : sp(0x7f3a0a27dc28) fp(0x7f3a0a27dc50) pc(0x7f3a08efece2) dart:async_::__completeOnAsyncReturn@4048458 ]
[dart     : sp(0x7f3a0a27dc60) fp(0x7f3a0a27dce8) pc(0x7f3a08efcb70) package:test_api/src/backend/declarer.dart_Declarer__runSetUps@31455614__async_op ]
[dart     : sp(0x7f3a0a27dcf8) fp(0x7f3a0a27dd48) pc(0x7f3a08ef4da3) package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__registerUnaryCallback@211444339_<anonymous closure>_<anonymous closure> ]
[dart     : sp(0x7f3a0a27dd58) fp(0x7f3a0a27ddf0) pc(0x7f3a08ef414c) package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__run@211444339 ]
[dart     : sp(0x7f3a0a27de00) fp(0x7f3a0a27de58) pc(0x7f3a08ef4bd0) package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__registerUnaryCallback@211444339_<anonymous closure> ]
[dart     : sp(0x7f3a0a27de68) fp(0x7f3a0a27ded8) pc(0x7f3a08eb4b53) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x7f3a0a27dee8) fp(0x7f3a0a27df50) pc(0x7f3a08eb4981) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x7f3a0a27df60) fp(0x7f3a0a27dff8) pc(0x7f3a08eb4133) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x7f3a0a27e008) fp(0x7f3a0a27e048) pc(0x7f3a08eb9daa) dart:async__FutureListener@4048458_handleValue ]
[dart     : sp(0x7f3a0a27e058) fp(0x7f3a0a27e0c0) pc(0x7f3a08eb99ce) dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]
[dart     : sp(0x7f3a0a27e0d0) fp(0x7f3a0a27e148) pc(0x7f3a08eb1945) dart:async__Future@4048458__propagateToListeners@4048458 ]
[dart     : sp(0x7f3a0a27e158) fp(0x7f3a0a27e198) pc(0x7f3a08efebe4) dart:async__Future@4048458__addListener@4048458_<anonymous closure> ]
[dart     : sp(0x7f3a0a27e1a8) fp(0x7f3a0a27e240) pc(0x7f3a08ef414c) package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__run@211444339 ]
[dart     : sp(0x7f3a0a27e250) fp(0x7f3a0a27e2a8) pc(0x7f3a08ef3f35) package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__registerCallback@211444339_<anonymous closure> ]
[dart     : sp(0x7f3a0a27e2b8) fp(0x7f3a0a27e320) pc(0x7f3a08ea7731) dart:async_::__rootRun@4048458 ]
[dart     : sp(0x7f3a0a27e330) fp(0x7f3a0a27e390) pc(0x7f3a08ea7431) dart:async_::__rootRun@4048458__rootRun@4048458 ]
[dart     : sp(0x7f3a0a27e3a0) fp(0x7f3a0a27e430) pc(0x7f3a08ea6840) dart:async__CustomZone@4048458_run ]
[dart     : sp(0x7f3a0a27e440) fp(0x7f3a0a27e4a0) pc(0x7f3a08eb2482) dart:async__CustomZone@4048458_runGuarded ]
[dart     : sp(0x7f3a0a27e4b0) fp(0x7f3a0a27e4f0) pc(0x7f3a08eb2329) dart:async__CustomZone@4048458_bindCallbackGuarded_<anonymous closure> ]
[dart     : sp(0x7f3a0a27e500) fp(0x7f3a0a27e538) pc(0x7f3a155cc17d) dart:async_::__microtaskLoop@4048458 ]
[dart     : sp(0x7f3a0a27e548) fp(0x7f3a0a27e578) pc(0x7f3a155cbdd1) dart:async_::__startMicrotaskLoop@4048458 ]
[dart     : sp(0x7f3a0a27e588) fp(0x7f3a0a27e5b8) pc(0x7f3a155cbcd0) dart:async_::__startMicrotaskLoop@4048458__startMicrotaskLoop@4048458 ]
[dart     : sp(0x7f3a0a27e5c8) fp(0x7f3a0a27e5f8) pc(0x7f3a155cbad0) dart:isolate_::__runPendingImmediateCallback@1026248 ]
[dart     : sp(0x7f3a0a27e608) fp(0x7f3a0a27e678) pc(0x7f3a08ef2f62) dart:isolate__Timer@1026248__runTimers@1026248 ]
[dart     : sp(0x7f3a0a27e688) fp(0x7f3a0a27e6b0) pc(0x7f3a08ef068e) dart:isolate__Timer@1026248__handleMessage@1026248 ]
[dart     : sp(0x7f3a0a27e6c0) fp(0x7f3a0a27e6f8) pc(0x7f3a08ef0393) dart:isolate__Timer@1026248__handleMessage@1026248__handleMessage@1026248 ]
[dart     : sp(0x7f3a0a27e708) fp(0x7f3a0a27e738) pc(0x7f3a155ac7b7) dart:core__Closure@0150898_dyn_call ]
[dart     : sp(0x7f3a0a27e748) fp(0x7f3a0a27e770) pc(0x7f3a155ac6bb) dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]
[entry    : sp(0x7f3a0a27e780) fp(0x7f3a0a27e7e8) pc(0x7f3a16101a3d)]

--- Re-run this test:
python tools/test.py -n dartk-linux-debug-x64 samples/ffi/sqlite/test/sqlite_test
```

```
(gdb) p this->ToCString()
$1 = 0x7fffe98aedf0 "Function Type: (dynamic, Pointer<sqlite3_stmt*>*, int*) => int*"
(gdb) p other.ToCString()
$2 = 0x7fffe98aee88 "Type: _Closure@0150898"
(gdb) bt
#0  0x00007ffff7cb3761 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7c9d55b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000555557040f7c in dart::Assert::Fail (this=<optimized out>, format=<optimized out>) at ../../runtime/platform/assert.cc:44
#3  0x000055555736aa04 in dart::AbstractType::IsSubtypeOf (this=0x555558c47980, other=..., space=dart::Heap::kOld, trail=<optimized out>) at ../../runtime/vm/object.cc:19473
#4  0x00005555578c5e89 in dart::CompileType::Union (this=0x7fffeb07c310, other=0x7fffe98abac8) at ../../runtime/vm/compiler/backend/type_propagator.cc:554
#5  0x00005555578c8760 in dart::PhiInstr::RecomputeType (this=0x7fffe9883e90) at ../../runtime/vm/compiler/backend/type_propagator.cc:946
#6  0x00005555578c3f5d in dart::FlowGraphTypePropagator::Propagate (this=0x7fffeb07c810) at ../../runtime/vm/compiler/backend/type_propagator.cc:96
#7  0x00005555578c3c48 in dart::FlowGraphTypePropagator::Propagate (flow_graph=0x7ffff6e6df08) at ../../runtime/vm/compiler/backend/type_propagator.cc:45
#8  0x00005555578dc710 in dart::CompilerPass_TypePropagation::DoBody (this=<optimized out>, state=0x7fffeb07baa0) at ../../runtime/vm/compiler/compiler_pass.cc:397
#9  0x00005555578dbec5 in dart::CompilerPass::Run (this=<optimized out>, state=0x7fffeb07ccf8) at ../../runtime/vm/compiler/compiler_pass.cc:195
#10 0x00005555578dc3df in dart::CompilerPass::RunPipeline (mode=<optimized out>, pass_state=0x7fffeb07ccf8) at ../../runtime/vm/compiler/compiler_pass.cc:331
#11 0x00005555575148af in dart::CompileParsedFunctionHelper::Compile (this=<optimized out>, pipeline=0x55555865ad00) at ../../runtime/vm/compiler/jit/compiler.cc:618
#12 0x00005555575159db in dart::CompileFunctionHelper (pipeline=<optimized out>, function=..., optimized=true, osr_id=192) at ../../runtime/vm/compiler/jit/compiler.cc:754
#13 0x0000555557516564 in dart::Compiler::CompileOptimizedFunction (thread=<optimized out>, function=..., osr_id=192) at ../../runtime/vm/compiler/jit/compiler.cc:945
#14 0x00005555574a74ea in dart::HandleOSRRequest (thread=0x5555584bec00) at ../../runtime/vm/runtime_entry.cc:2611
#15 dart::DRT_HelperStackOverflow (isolate=<optimized out>, thread=0x5555584bec00, zone=<optimized out>, arguments=...) at ../../runtime/vm/runtime_entry.cc:2720
#16 dart::DRT_StackOverflow (arguments=...) at ../../runtime/vm/runtime_entry.cc:2633
#17 0x00007ffff7681502 in ?? ()
#18 0x00005555584bec00 in ?? ()
#19 0x0000000000000000 in ?? ()
```

```
(gdb) p function.ToCString()
$4 = 0x7fffe98aeea0 "Function '<anonymous closure>': static."
```

**Comment by dcharkes** [comment]
While trying to make a minimal example, I can get this to show up in other places as well. Involving the same type.

```
(gdb) bt
#0  0x00007ffff7cb3761 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7c9d55b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000555557040f7c in dart::Assert::Fail (this=<optimized out>, format=<optimized out>) at ../../runtime/platform/assert.cc:44
#3  0x000055555736aa04 in dart::AbstractType::IsSubtypeOf (this=0x5555595c28e0, other=..., space=dart::Heap::kOld, trail=<optimized out>) at ../../runtime/vm/object.cc:19473
#4  0x00005555578c5e89 in dart::CompileType::Union (this=0x7ffff68fcb40, other=0x7ffff704b7f8) at ../../runtime/vm/compiler/backend/type_propagator.cc:554
#5  0x00005555578c8760 in dart::PhiInstr::RecomputeType (this=0x7ffff70697a8) at ../../runtime/vm/compiler/backend/type_propagator.cc:946
#6  0x00005555578c3f5d in dart::FlowGraphTypePropagator::Propagate (this=0x7ffff68fd040) at ../../runtime/vm/compiler/backend/type_propagator.cc:96
#7  0x00005555578c3c48 in dart::FlowGraphTypePropagator::Propagate (flow_graph=0x7ffff78066c8) at ../../runtime/vm/compiler/backend/type_propagator.cc:45
#8  0x00005555578dc710 in dart::CompilerPass_TypePropagation::DoBody (this=<optimized out>, state=0x7ffff68fc2d0) at ../../runtime/vm/compiler/compiler_pass.cc:397
#9  0x00005555578dbec5 in dart::CompilerPass::Run (this=<optimized out>, state=0x7ffff68fd528) at ../../runtime/vm/compiler/compiler_pass.cc:195
#10 0x00005555578dc3df in dart::CompilerPass::RunPipeline (mode=<optimized out>, pass_state=0x7ffff68fd528) at ../../runtime/vm/compiler/compiler_pass.cc:331
#11 0x00005555575148af in dart::CompileParsedFunctionHelper::Compile (this=<optimized out>, pipeline=0x7ffff7020cc0) at ../../runtime/vm/compiler/jit/compiler.cc:618
#12 0x00005555575159db in dart::CompileFunctionHelper (pipeline=<optimized out>, function=..., optimized=true, osr_id=-1) at ../../runtime/vm/compiler/jit/compiler.cc:754
#13 0x0000555557516564 in dart::Compiler::CompileOptimizedFunction (thread=<optimized out>, function=..., osr_id=-1) at ../../runtime/vm/compiler/jit/compiler.cc:945
#14 0x000055555751788c in dart::BackgroundCompiler::Run (this=0x5555584bc0e0) at ../../runtime/vm/compiler/jit/compiler.cc:1207
#15 0x00005555574f896b in dart::ThreadPool::WorkerLoop (this=0x55555847a140, worker=0x55555848e900) at ../../runtime/vm/thread_pool.cc:158
#16 0x00005555574f93a9 in dart::ThreadPool::Worker::Main (args=93825041754368) at ../../runtime/vm/thread_pool.cc:323
#17 0x000055555742ad89 in dart::ThreadStart (data_ptr=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:153
#18 0x00007ffff7f88f27 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#19 0x00007ffff7d752ef in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

```
(gdb) p this->ToCString()
$1 = 0x7ffff704b9d8 "Function Type: (dynamic, Pointer<sqlite3_stmt*>*) => int*"
(gdb) p function.ToCString()
$2 = 0x7ffff704ba18 "Function 'execute':."
```
