### ISSUE TITLE
Failures on [co19] LibTest/convert tests enabled...[front-end] fix bug in BodyBuilder

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#43019]
There are new test failures on [[co19] LibTest/convert tests enabled...[front-end] fix bug in BodyBuilder](https://github.com/dart-lang/sdk/compare/9a2a3aae14fe0e058c8fb5fb844cf9c53059148b~...855acf60b7b6e23f278814fdc46208b1ae24f986).

The tests
```
vm/dart/regress_42656_test DartkCrash (expected Pass)
```
are failing on configurations
```
dartkp-weak-asserts-linux-release-simarm64
dartkp-weak-asserts-linux-release-x64
```

```
/============================================================================================================\
| dartkp-weak-asserts-linux-release-x64:vm/dart/regress_42656_test broke (Pass -> DartkCrash, expected Pass) |
\============================================================================================================/

--- Command "vm_compile_to_kernel" (took 03.000388s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --enable-experiment=non-nullable --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp/runtime_tests_vm_dart_regress_42656_test/out.dill /b/s/w/ir/runtime/tests/vm/dart/regress_42656_test.dart --enable-experiment=non-nullable --packages=/b/s/w/ir/.packages -Ddart.vm.product=false -Ddart.developer.causal_async_stacks=true --enable-asserts --no-sound-null-safety

exit code:
253

stderr:
Invalid argument(s): Missing canonical name for Reference to MixinA.x
#0      BinaryPrinter.writeNullAllowedReference (package:kernel/binary/ast_to_binary.dart:849:9)
#1      BinaryPrinter.writeNullAllowedInstanceMemberReference (package:kernel/binary/ast_to_binary.dart:840:5)
#2      BinaryPrinter.visitPropertyGet (package:kernel/binary/ast_to_binary.dart:1402:5)
#3      PropertyGet.accept (package:kernel/ast.dart:3240:44)
#4      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#5      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:292:7)
#6      BinaryPrinter.visitArguments (package:kernel/binary/ast_to_binary.dart:1514:5)
#7      Arguments.accept (package:kernel/ast.dart:3779:38)
#8      BinaryPrinter.writeArgumentsNode (package:kernel/binary/ast_to_binary.dart:396:10)
#9      BinaryPrinter.visitStaticInvocation (package:kernel/binary/ast_to_binary.dart:1497:5)
#10     StaticInvocation.accept (package:kernel/ast.dart:4114:44)
#11     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#12     BinaryPrinter.visitExpressionStatement (package:kernel/binary/ast_to_binary.dart:1813:5)
#13     ExpressionStatement.accept (package:kernel/ast.dart:5810:43)
#14     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#15     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:292:7)
#16     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1821:5)
#17     Block.accept (package:kernel/ast.dart:5849:43)
#18     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#19     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:475:7)
#20     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1345:5)
#21     FunctionNode.accept (package:kernel/ast.dart:2932:38)
#22     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:389:10)
#23     BinaryPrinter.writeOptionalFunctionNode (package:kernel/binary/ast_to_binary.dart:484:7)
#24     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1221:5)
#25     Procedure.accept (package:kernel/ast.dart:2423:40)
#26     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:410:10)
#27     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:301:7)
#28     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:978:5)
#29     Library.accept (package:kernel/ast.dart:607:38)
#30     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:403:10)
#31     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:710:9)
#32     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:553:7)
#33     Timeline.timeSync (dart:developer/timeline.dart:163:22)
#34     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:536:14)
#35     runCompiler (package:vm/kernel_front_end.dart:301:11)
<asynchronous suspension>
#36     compile (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:39:10)
#37     runBatchModeCompiler.<anonymous closure> (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:57:28)
#38     runBatch (package:kernel/src/tool/batch_util.dart:38:35)
<asynchronous suspension>
#39     runBatchModeCompiler (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:43:9)
#40     main (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:32:11)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartkp-weak-asserts-linux-release-x64 vm/dart/regress_42656_test
```

This might be related to new member signature origins introduced in 65e48e423a1b049c8e3ec924674118771e9f1c06.
/cc @johnniwinther

**Comment by alexmarkov** [comment]
AOT compilation of Flutter apps on Flutter HHH also fails for the same reason:

```
[        ] [  +45 ms] /b/s/w/ir/cache/builder/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /b/s/w/ir/cache/builder/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /b/s/w/ir/cache/builder/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter -Ddart.developer.causal_async_stacks=false -Ddart.vm.profile=false -Ddart.vm.product=true --bytecode-options=source-positions --aot --tfa --packages /b/s/w/ir/cache/builder/flutter/examples/platform_channel/.packages --output-dill /b/s/w/ir/cache/builder/flutter/examples/platform_channel/.dart_tool/flutter_build/80a698f819ec0896bf49bd0fd0e45ab3/app.dill --depfile /b/s/w/ir/cache/builder/flutter/examples/platform_channel/.dart_tool/flutter_build/80a698f819ec0896bf49bd0fd0e45ab3/kernel_snapshot.d package:platform_channel/main.dart
[+15058 ms] [+15982 ms] Unhandled exception:
[   +2 ms]             Invalid argument(s): Missing canonical name for Reference to GestureBinding.pointerRouter
[        ]             #0      BinaryPrinter.writeNullAllowedReference (package:kernel/binary/ast_to_binary.dart:849:9)
[        ]             #1      BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1220:5)
[        ]             #2      Procedure.accept (package:kernel/ast.dart:2423:40)
[        ]             #3      BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:410:10)
[        ]             #4      BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:301:7)
[        ]             #5      BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1143:5)
[        ]             #6      Class.accept (package:kernel/ast.dart:1379:38)
[        ]             #7      BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:424:10)
[        ]             #8      BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:319:7)
[        ]             #9      BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:973:5)
[        ]             #10     Library.accept (package:kernel/ast.dart:607:38)
[        ]             #11     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:403:10)
[        ]             #12     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:710:9)
[        ]             #13     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:553:7)
[        ]             #14     Timeline.timeSync (dart:developer/timeline.dart:163:22)
[        ]             #15     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:536:14)
[        ]             #16     FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:751:15)
[        ]             #17     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:562:13)
[        ]             <asynchronous suspension>
[        ]             #18     _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:43:22)
[        ]             #19     starter (package:flutter_frontend_server/server.dart:182:27)
[        ]             #20     main (file:///b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:9:30)
[        ]             #21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
[        ]             #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
[ +189 ms] [ +133 ms] Persisting file store
[        ] [   +2 ms] Done persisting file store
[        ] [   +2 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:262:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
[        ]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[        ]            #9      _rootRun (dart:async/zone.dart:1190:13)
[        ]            #10     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ]            #13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ]            #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ]            #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[        ] [   +6 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:238:7)
```

**Comment by alexmarkov** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/158147
