### ISSUE TITLE
[dart2js] Failure on  kernel/unsorted/super_mixin_test

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#43044]
There are new test failures on [[gardening] Mark regression test slow](https://github.com/dart-lang/sdk/commit/3ebe4c534aca67cfbf09366761040711281d9d98).

The tests
```
kernel/unsorted/super_mixin_test Crash (expected Pass)
```
are failing on configurations
```
dart2js-hostasserts-linux-ia32-d8
```

This test uses `super` calls in a mixin. These are supposed to be rewritten by cloning by the CFE.

```
--- Command "dart2js" (took 03.000965s):
DART_CONFIGURATION=ReleaseIA32 sdk/bin/dart2js_developer --test-mode --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/kernel/unsorted/super_mixin_test.dart --out=/b/s/w/ir/out/ReleaseIA32/generated_compilations/dart2js/tests_kernel_unsorted_super_mixin_test/super_mixin_test.js

exit code:
253

stderr:
Unhandled exception:
Assertion failure: No Class for has been created for superclass j:class(BaseMixin) of Class(name=Mixin,element=j:class(Mixin)).
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      ProgramBuilder.buildProgram.<anonymous closure> (package:compiler/src/js_emitter/program_builder/program_builder.dart:220:13)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#3      ProgramBuilder.buildProgram (package:compiler/src/js_emitter/program_builder/program_builder.dart:214:14)
#4      EmitterImpl.emitProgram.<anonymous closure> (package:compiler/src/js_emitter/startup_emitter/emitter.dart:193:29)
#5      CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#6      EmitterImpl.emitProgram (package:compiler/src/js_emitter/startup_emitter/emitter.dart:192:29)
#7      CodeEmitterTask.assembleProgram.<anonymous closure> (package:compiler/src/js_emitter/code_emitter_task.dart:147:26)
#8      CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#9      CodeEmitterTask.assembleProgram (package:compiler/src/js_emitter/code_emitter_task.dart:117:12)
#10     JsBackendStrategy.assembleProgram (package:compiler/src/js_model/js_strategy.dart:359:35)
#11     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:396:39)
#12     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:290:9)
#13     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:438:9)
#14     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#15     Compiler.compileFromKernel (package:compiler/src/compiler.dart:411:14)
#16     Compiler.runInternal (package:compiler/src/compiler.dart:263:13)
<asynchronous suspension>
#17     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:218:38)
#18     new Future.sync (dart:async/future.dart:223:31)
#19     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:218:20)
#20     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#21     Compiler.run (package:compiler/src/compiler.dart:215:41)
#22     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#23     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#28     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

--- Re-run this test:
python tools/test.py -n dart2js-hostasserts-linux-ia32-d8 --dart2js-batch kernel/unsorted/super_mixin_test
```

**Comment by fishythefish** [comment]
Closed by 9206b6cabbc56e4c0861d7641c6bdc68542368bb.
