### ISSUE TITLE
Hot reload crash "Internal problem: Unimplemented typeVariables."

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#43084]
```
Unhandled exception:                                                    
Crash when compiling file:///home/ianh/dev/plexiglass/lib/themes/beveled.dart,
at character offset 4099:                                               
Internal problem: Unimplemented typeVariables.                          
#0      internalProblem (package:front_end/src/fasta/problems.dart:46:3)
#1      unimplemented (package:front_end/src/fasta/problems.dart:52:10) 
#2      DillTypeAliasBuilder.typeVariables (package:front_end/src/fasta/dill/dill_type_alias_builder.dart:30:12)
#3      BodyBuilder.buildConstructorInvocation (package:front_end/src/fasta/kernel/body_builder.dart:4303:49)
#4      TypeUseGenerator.doInvocation (package:front_end/src/fasta/kernel/expression_generator.dart:3157:22)
#5      BodyBuilder.finishSend (package:front_end/src/fasta/kernel/body_builder.dart:1641:23)
#6      BodyBuilder.handleSend (package:front_end/src/fasta/kernel/body_builder.dart:1623:12)
#7      Parser.parseSend (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5611:14)
#8      Parser.parseSendOrFunctionLiteral (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5337:12)
#9      Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4902:14)
#10     Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4809:12)
#11     Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4543:13)
#12     Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4484:13)
#13     Parser.parseReturnStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4391:13)
#14     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4258:14)
#15     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4235:20)
#16     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4140:15)
#17     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:990:14)
#18     DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:714:5)
#19     DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:665:5)
#20     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3744:20)
#21     Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3485:15)
#22     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3159:15)
#23     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1852:13)
#24     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1810:14)
#25     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:578:14)
#26     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:474:14)
#27     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:354:15)
#28     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:425:14)
<asynchronous suspension>                                               
#29     Loader.buildBodies (package:front_end/src/fasta/loader.dart:242:15)
<asynchronous suspension>                                               
#30     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:358:20)
#31     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#32     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:356:12)
#33     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:274:28)
<asynchronous suspension>                                               
#34     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
#35     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#36     new Future.sync (dart:async/future.dart:223:31)                 
#37     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#38     _rootRun (dart:async/zone.dart:1190:13)                         
#39     _CustomZone.run (dart:async/zone.dart:1093:19)                  
#40     _runZoned (dart:async/zone.dart:1630:10)                        
#41     runZoned (dart:async/zone.dart:1550:10)                         
#42     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#43     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:206:20)
#44     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:46)
#45     FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:888:47)
<asynchronous suspension>                                               
#46     _FlutterFrontendCompiler.recompileDelta (package:flutter_frontend_server/server.dart:48:22)
#47     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1261:20)
#48     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#51     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#52     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#53     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#54     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#55     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#56     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#57     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#58     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#61     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#62     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#63     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#64     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#65     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#66     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#67     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#68     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#69     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#70     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#71     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#72     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#73     _StreamController._add (dart:async/stream_controller.dart:682:7)
#74     _StreamController.add (dart:async/stream_controller.dart:624:5) 
#75     _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)       
#76     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#77     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#78     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#79     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#80     _StreamController._add (dart:async/stream_controller.dart:682:7)
#81     _StreamController.add (dart:async/stream_controller.dart:624:5) 
#82     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#83     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
#84     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)       
#85     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)   
#86     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#87     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
                                                                        
                                                                        
#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:998:7)
#1      DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:714:5)
#2      DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:665:5)
#3      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3744:20)
#4      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3485:15)
#5      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3159:15)
#6      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1852:13)
#7      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1810:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:578:14)
#9      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:474:14)
#10     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:354:15)
#11     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:425:14)
<asynchronous suspension>                                               
#12     Loader.buildBodies (package:front_end/src/fasta/loader.dart:242:15)
<asynchronous suspension>                                               
#13     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:358:20)
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#15     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:356:12)
#16     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:274:28)
<asynchronous suspension>                                               
#17     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
#18     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#19     new Future.sync (dart:async/future.dart:223:31)                 
#20     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#21     _rootRun (dart:async/zone.dart:1190:13)                         
#22     _CustomZone.run (dart:async/zone.dart:1093:19)                  
#23     _runZoned (dart:async/zone.dart:1630:10)                        
#24     runZoned (dart:async/zone.dart:1550:10)                         
#25     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#26     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:206:20)
#27     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:46)
#28     FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:888:47)
<asynchronous suspension>                                               
#29     _FlutterFrontendCompiler.recompileDelta (package:flutter_frontend_server/server.dart:48:22)
#30     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1261:20)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#41     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#44     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#45     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#46     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#47     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#48     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#49     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#50     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#51     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#52     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#56     _StreamController._add (dart:async/stream_controller.dart:682:7)
#57     _StreamController.add (dart:async/stream_controller.dart:624:5) 
#58     _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)       
#59     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#62     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#63     _StreamController._add (dart:async/stream_controller.dart:682:7)
#64     _StreamController.add (dart:async/stream_controller.dart:624:5) 
#65     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#66     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
#67     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)       
#68     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)   
#69     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
the Dart compiler exited unexpectedly.                                  
Performing hot reload...                                                
Try again after fixing the above error(s).
the Dart compiler exited unexpectedly.
```

Offset 4099 was the end of the arguments of a method in a class that hadn't changed for a while.

**Comment by Hixie** [comment]
(Code was analyzer-clean at that point, FWIW, and a subsequent "flutter run" ran fine.)

**Comment by alexmarkov** [comment]
This looks like a crash in the front-end. /cc @johnniwinther @jensjoha

**Comment by johnniwinther** [comment]
I assume it is fixed by https://dart-review.googlesource.com/c/sdk/+/159440. 

@Hixie Do reopen if the issue persists.
