### ISSUE TITLE
Crash when making typedef generic

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#43090]
I can reliably crash analysis_server when writing a typedef:

1. In an editor using analysis_server like VS Code, create a new file.
2. Declare a typedef, like `typedef A = void Function();`
3. Start to make `A` generic by writing a `<` character after `A`.
4. Crash:

   ```none
   [9:23:45 AM] [Analyzer] [Error] Unhandled exception:
   type 'KeywordToken' is not a subtype of type 'List<Annotation>'
   #0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
   #1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
   #2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
   #3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
   #4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
   #5      _startMicrotaskL…
   ```

**Comment by srawlins** [comment]
Continues to crash at HEAD.

**Comment by scheglov** [comment]
When parsing `typedef A< = void Function();`
![image](https://user-images.githubusercontent.com/384794/105927789-8d79d780-5ff9-11eb-8b2c-8d749de2595d.png)
Looks like a parser issue @jensjoha 
```dart
  /// Handle the end of a typedef declaration.
  ///
  /// If [equals] is null, then we have the following substructures:
  /// - Metadata
  /// - Return type
  /// - Name (identifier)
  /// - Alias type variables
  /// - Formal parameters
  ///
  /// If [equals] is not null, then the have the following substructures:
  /// - Metadata
  /// - Name (identifier)
  /// - Alias type variables
  /// - Type (FunctionTypeAnnotation)
  void endFunctionTypeAlias(
      Token typedefKeyword, Token? equals, Token endToken) {
    logEvent("FunctionTypeAlias");
  }
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/181340 will change DAS to catch parser exceptions in available declarations, so prevent DAS from dying.
