### ISSUE TITLE
Failures on Add definite assignment tests.

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#43102]
There are new test failures on [Add definite assignment tests.](https://github.com/dart-lang/sdk/commit/9cae6aa746e413c6c707812bde114a6f71a544da).

The tests
```
co19_2/LibTest/isolate/Isolate/spawn_A04_t04 RuntimeError (expected Pass)
```
are failing on configurations
```
dartkb-mixed-linux-release-x64
```

Test went from flaky to RuntimeError. See [log](https://dart-ci.appspot.com/log/vm-dartkb-linux-release-x64/dartkb-mixed-linux-release-x64/8522/co19_2/LibTest/isolate/Isolate/spawn_A04_t04):

```
--- Command "vm" (took 06.000294s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --enable_interpreter --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/isolate/Isolate/spawn_A04_t04.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <ping>, actual: <timeout>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.equals (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:30:5)
#2      test (file:///b/s/w/ir/tests/co19_2/src/LibTest/isolate/Isolate/spawn_A04_t04.dart:64:12)
<asynchronous suspension>
#3      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/isolate/Isolate/spawn_A04_t04.dart:75:3)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartkb-mixed-linux-release-x64 co19_2/LibTest/isolate/Isolate/spawn_A04_t04
```

**Comment by alexmarkov** [comment]
Bytecode mode is removed from Dart VM.
