### ISSUE TITLE
FileSystemMoveEvent isDirectory_A01_t01 and type_A01_t02 tests fail on mac

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#43117]
```
╰─➤  python tools/test.py -n dartk-mac-release-x64 co19_2/LibTest/io/FileSystemMoveEvent/isDirectory_A01_t01
Test configuration:
    dartk-mac-release-x64(architecture: x64, compiler: dartk, mode: release, runtime: vm, system: mac)
Suites tested: co19_2

FAILED: dartk-vm release_x64 co19_2/LibTest/io/FileSystemMoveEvent/isDirectory_A01_t01
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 45.000309s):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --ignore-unrecognized-flags --packages=dart-sdk/sdk/.packages dart-sdk/sdk/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/isDirectory_A01_t01.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
NoSuchMethodError: The getter 'isDirectory' was called on null.
Receiver: null
Tried calling: isDirectory
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _main.<anonymous closure> (file:///dart-sdk/sdk/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/isDirectory_A01_t01.dart:31:30)
#2      testFileSystemEvent (file:///dart-sdk/sdk/tests/co19_2/src/LibTest/io/file_utils.dart:56:7)
<asynchronous suspension>
#3      _main (file://dart-sdk/sdk/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/isDirectory_A01_t01.dart:27:9)
#4      inSandbox (file://dart-sdk/sdk/tests/co19_2/src/LibTest/io/file_utils.dart:24:22)
#5      main (file://dart-sdk/sdk/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/isDirectory_A01_t01.dart:19:9)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartk-mac-release-x64 co19_2/LibTest/io/FileSystemMoveEvent/isDirectory_A01_t01
[00:45 | 100% | +    0 | -    1]

=== 0 tests passed, 1 failed ===

╰─➤  python tools/test.py -n dartk-mac-release-x64 co19_2/LibTest/io/FileSystemMoveEvent/type_A01_t02                                       1 ↵
Test configuration:
    dartk-mac-release-x64(architecture: x64, compiler: dartk, mode: release, runtime: vm, system: mac)
Suites tested: co19_2

FAILED: dartk-vm release_x64 co19_2/LibTest/io/FileSystemMoveEvent/type_A01_t02
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 45.000284s):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --ignore-unrecognized-flags --packages=dart-sdk/sdk/.packages dart-sdk/sdk/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/type_A01_t02.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _main.<anonymous closure> (file://dart-sdk/sdk/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/type_A01_t02.dart:29:51)
#2      testFileSystemEvent (file://dart-sdk/sdk/tests/co19_2/src/LibTest/io/file_utils.dart:56:7)
<asynchronous suspension>
#3      _main (file://dart-sdk/sdk/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/type_A01_t02.dart:25:9)
#4      inSandbox (file://dart-sdk/sdk/tests/co19_2/src/LibTest/io/file_utils.dart:24:22)
#5      main (file://dart-sdk/sdk/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/type_A01_t02.dart:18:9)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartk-mac-release-x64 co19_2/LibTest/io/FileSystemMoveEvent/type_A01_t02
[00:45 | 100% | +    0 | -    1]

=== 0 tests passed, 1 failed ===

```

**Comment by aam** [comment]
tests fail on mac seemingly because for renameSync operation(file or directory) we generate pair of delete/create events, rather than single move event(what test expects).

I don't think there are guarantees that move events are generated - there are might be OS(mac os in this particular case) limitations that prevent move events to be generated. @sgrekhov , what do you think?

**Comment by sgrekhov** [comment]
@aam sorry for the late reply. This is simply tests issue. These tests have `failIfNoEvent: false` but don't check `event` to be not null. Fixed by https://github.com/dart-lang/co19/commit/f18552517d0fcda78195cbdd9910e5ddaa641320 and https://github.com/dart-lang/co19/commit/09362e210c8f9b8f8be90347ad41f96c315bfe63.
Please wait for the next co19_2 roll and then retest. The issue must be fixed

**Comment by aam** [comment]
awesome, thanks!
