### ISSUE TITLE
	Dart Analyzer Error

### ISSUE THREAD

**Issue by Bikuta-victor1** [dart-lang/sdk#43130]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.9.1`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.9.1, server version 1.28.0, error: FormatException: No ':' on line (at offset 5528)
#0      parse (package:package_config/packages_file.dart:64:7)
#1      parseDotPackagesFile (package:analyzer/src/context/packages.dart:48:16)
#2      parsePackagesFile (package:analyzer/src/context/packages.dart:130:12)
#3      ContextManagerImpl._computeFolderDisposition (package:analysis_server/src/context_manager.dart:874:22)
#4      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:914:9)
#5      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1004:16)
#6      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:610:9)
#7      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:409:22)
#8      AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:351:14)
#9      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:290:16)
#10     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:241:40)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:215:15)
#12     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:237:50)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZonedGuarded (dart:async/zone.dart:1618:12)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:236:5)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169:16)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:215:15)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:159:47)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:104:26)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#34     _rootRunUnary (dart:async/zone.dart:1198:47)
#35     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#47     _rootRunUnary (dart:async/zone.dart:1198:47)
#48     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#53     _StreamController._add (dart:async/stream_controller.dart:682:7)
#54     _StreamController.add (dart:async/stream_controller.dart:624:5)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#56     _rootRunUnary (dart:async/zone.dart:1206:13)
#57     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#61     _SyncS...
```

For additional log information, please append the contents of
file://C:\Users\USER\AppData\Local\Temp\report2.txt.

**Comment by devoncarew** [comment]
Thanks for the report! It looks like we may need to be defensive when we parse the `.packages` file.

**Comment by bwilkerson** [comment]
I'm going to close this because the `.packages` file has been replaced by the `package_config.json` file.
