### ISSUE TITLE
Bad state: No element from dartdev when run with -h

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#43238]
```
dart pkg/dartdev/bin/dartdev.dart -h  
Bad state: No element
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      PubUtils.shouldModifyArgs (package:dartdev/src/utils.dart:59:12)
#2      runDartdev (package:dartdev/dartdev.dart:127:18)
#3      main (file:///Users/devoncarew/projects/dart-lang/sdk/pkg/dartdev/bin/dartdev.dart:12:9)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by kwalrath** [comment]
I'm seeing the same thing when I forget the `pub` in `dart pub <whatever>`. Is my problem fixed, too?

```
$ dart get
Bad state: No element
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      PubUtils.shouldModifyArgs (package:dartdev/src/utils.dart:46:12)
#2      runDartdev (package:dartdev/dartdev.dart:127:18)
#3      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:12:9)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
$ dart --version
Dart SDK version: 2.10.0-59.0.dev (dev) (Tue Aug 25 18:05:44 2020 -0700) on "macos_x64"
```

**Comment by devoncarew** [comment]
Yes, this is the same issue (and will be fixed in the next dev release).
