### ISSUE TITLE
'dart analyze -v' throws an NPE when we don't have context messages

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#43239]
```
dart analyze -v
Analyzing planets...                   10.2s

   info • The value of the local variable 'foo' isn't used at lib/main.dart:128:11 • (unused_local_variable)
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<DiagnosticMessage>(Closure: (dynamic) => DiagnosticMessage)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AnalysisError.contextMessages (package:dartdev/src/commands/analyze_impl.dart:242:21)
#2      AnalyzeCommand.run (package:dartdev/src/commands/analyze.dart:108:37)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#4      DartdevRunner.runCommand (package:dartdev/dartdev.dart:250:24)
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#6      new Future.sync (dart:async/future.dart:223:31)
#7      CommandRunner.run (package:args/command_runner.dart:112:14)
#8      runDartdev (package:dartdev/dartdev.dart:117:27)
#9      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:12:9)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by bwilkerson** [comment]
https://github.com/dart-lang/sdk/issues/43239
