### ISSUE TITLE
gen_snapshot crash with AOT split

### ISSUE THREAD

**Issue by chingjun** [dart-lang/sdk#43245]
Error message: 
```
Unexpected object (Class with illegal cid, full-aot): 0x7ffff4725301 Library:'package:.../....dart' Class: ::
```

Stack trace:
```
#0  0x00007ffff7d41602 in raise () from libc.so.6
#1  0x00007ffff7d43320 in abort () from libc.so.6
#2  0x0000555556d8b129 in dart::OS::Abort () at runtime/vm/os_linux.cc:653
#3  0x0000555556ca51e9 in dart::Serializer::UnexpectedObject (this=<optimized out>, raw_object=..., message=<optimized out>) at runtime/vm/clustered_snapshot.cc:5906
#4  dart::ClassSerializationCluster::Trace (this=<optimized out>, s=<optimized out>, object=...) at runtime/vm/clustered_snapshot.cc:160
#5  0x0000555556c9f178 in dart::Serializer::Serialize (this=this@entry=0x7fffffffce98, roots=roots@entry=0x7fffffffd030) at runtime/vm/clustered_snapshot.cc:5955
#6  0x0000555556ca12a3 in dart::FullSnapshotWriter::WriteProgramSnapshot (this=this@entry=0x7fffffffd240, num_base_objects=1011, units=<optimized out>, units@entry=0x7fffffffd3d0)
    at runtime/vm/clustered_snapshot.cc:6880
#7  0x0000555556ca1645 in dart::FullSnapshotWriter::WriteFullSnapshot (this=0x7fffffffd240, data=0x7fffffffd3d0) at runtime/vm/clustered_snapshot.cc:6950
#8  0x0000555556ad4813 in dart::CreateAppAOTSnapshot (callback=<optimized out>, callback@entry=0x5555568c7550 <dart::bin::StreamingWriteCallback(void*, unsigned char const*, long)>,
    callback_data=0xf85bfc84080, strip=true, as_elf=<optimized out>, debug_callback_data=<optimized out>, units=0x230c10, units@entry=0x7fffffffd3d0, unit=0x7ffff77af040, program_hash=855514176)
    at runtime/vm/dart_api_impl.cc:6695
#9  0x0000555556ad4f12 in dart::Split (next_callback=next_callback@entry=0x5555568c7660 <dart::bin::NextElfCallback(void*, long, void**, void**)>,
    next_callback_data=next_callback_data@entry=0xf85bfc84140, strip=<optimized out>, as_elf=<optimized out>,
    write_callback=0x5555568c7550 <dart::bin::StreamingWriteCallback(void*, unsigned char const*, long)>, close_callback=<optimized out>) at runtime/vm/dart_api_impl.cc:6764
#10 0x0000555556ad552b in Dart_CreateAppAOTSnapshotAsElfs (next_callback=0x5555568c7660 <dart::bin::NextElfCallback(void*, long, void**, void**)>, next_callback_data=0xf85bfc84140, strip=true,
    write_callback=0x5555568c7550 <dart::bin::StreamingWriteCallback(void*, unsigned char const*, long)>, close_callback=0x5555568c7630 <dart::bin::StreamingCloseCallback(void*)>)
    at runtime/vm/dart_api_impl.cc:6902
#11 0x00005555568c6d77 in dart::bin::CreateAndWritePrecompiledSnapshot () at runtime/bin/gen_snapshot.cc:745
#12 dart::bin::CreateIsolateAndSnapshot (inputs=...) at runtime/bin/gen_snapshot.cc:871
#13 dart::bin::main (argc=<optimized out>, argv=<optimized out>) at runtime/bin/gen_snapshot.cc:983
#14 0x00007ffff7d2dbbd in __libc_start_main () from libc.so.6
#15 0x00005555568c5029 in _start () at ../sysdeps/x86_64/start.S:108
```

Repro: cl/323858212

**Comment by chingjun** [comment]
cc @rmacnak-google

**Comment by rmacnak-google** [comment]
Looks like a tree-shaking bug
