### ISSUE TITLE
gen_snapshot crash when both `--loading_unit_manifest` and `--print-instructions-sizes-to` are passed

### ISSUE THREAD

**Issue by chingjun** [dart-lang/sdk#43246]
Stack trace:

```
#0  0x00007ffff7d41602 in raise () from libc.so.6
#1  0x00007ffff7d43320 in abort () from libc.so.6
#2  0x0000555556c6d71c in dart::Assert::Fail (this=<optimized out>, format=<optimized out>) at runtime/platform/assert.cc:44
#3  0x0000555556d08ff6 in dart::JSONWriter::AddDartString (this=<optimized out>, this@entry=0x7fffffffcd50, s=..., offset=offset@entry=0, count=<optimized out>, count@entry=-1)
    at runtime/vm/json_writer.cc:399
#4  0x0000555556d095bf in dart::JSONWriter::PrintValueStr (this=0x7fffffffcd50, s=..., offset=<optimized out>, count=<optimized out>) at runtime/vm/json_writer.cc:176
#5  dart::JSONWriter::PrintPropertyStr (this=0x7fffffffcd50, name=<optimized out>, s=..., offset=0, count=-1) at runtime/vm/json_writer.cc:252
#6  0x0000555556cf02ca in dart::ImageWriter::DumpInstructionsSizes (this=0x7fffffffd028) at runtime/vm/object.h:1090
#7  0x0000555556ca1324 in dart::FullSnapshotWriter::WriteProgramSnapshot (this=this@entry=0x7fffffffd1c0, num_base_objects=1011, units=<optimized out>, units@entry=0x7fffffffd350)
    at runtime/vm/clustered_snapshot.cc:6888
#8  0x0000555556ca1645 in dart::FullSnapshotWriter::WriteFullSnapshot (this=0x7fffffffd1c0, data=0x7fffffffd350) at runtime/vm/clustered_snapshot.cc:6950
#9  0x0000555556ad4813 in dart::CreateAppAOTSnapshot (callback=<optimized out>, callback@entry=0x5555568c7550 <dart::bin::StreamingWriteCallback(void*, unsigned char const*, long)>,
    callback_data=0xf85bfc84080, strip=true, as_elf=<optimized out>, debug_callback_data=<optimized out>, units=0x22e951, units@entry=0x7fffffffd350, unit=0x7ffff786e940, program_hash=842629723)
    at runtime/vm/dart_api_impl.cc:6695
#10 0x0000555556ad4f12 in dart::Split (next_callback=next_callback@entry=0x5555568c7660 <dart::bin::NextElfCallback(void*, long, void**, void**)>,
    next_callback_data=next_callback_data@entry=0xf85bfc84380, strip=<optimized out>, as_elf=<optimized out>,
    write_callback=0x5555568c7550 <dart::bin::StreamingWriteCallback(void*, unsigned char const*, long)>, close_callback=<optimized out>) at runtime/vm/dart_api_impl.cc:6764
#11 0x0000555556ad552b in Dart_CreateAppAOTSnapshotAsElfs (next_callback=0x5555568c7660 <dart::bin::NextElfCallback(void*, long, void**, void**)>, next_callback_data=0xf85bfc84380, strip=true,
    write_callback=0x5555568c7550 <dart::bin::StreamingWriteCallback(void*, unsigned char const*, long)>, close_callback=0x5555568c7630 <dart::bin::StreamingCloseCallback(void*)>)
    at runtime/vm/dart_api_impl.cc:6902
#12 0x00005555568c6d77 in dart::bin::CreateAndWritePrecompiledSnapshot () at runtime/bin/gen_snapshot.cc:745
#13 dart::bin::CreateIsolateAndSnapshot (inputs=...) at runtime/bin/gen_snapshot.cc:871
#14 dart::bin::main (argc=<optimized out>, argv=<optimized out>) at runtime/bin/gen_snapshot.cc:983
#15 0x00007ffff7d2dbbd in __libc_start_main () from libc.so.6
#16 0x00005555568c5029 in _start () at ../sysdeps/x86_64/start.S:108
```

Repro: cl/323858212

**Comment by chingjun** [comment]
cc @rmacnak-google
