### ISSUE TITLE
Crash when a duplicate class, and checking for subtype, or inference

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#43272]
The code below crashes because `ClassElementImpl` for `class A {}` is equal to `class A<T> {}`, because their `ElementLocation` are equal, because it is just a sequence of names. But inside `class A<T> {}` we have `this` that has one type argument, but `A` in `foo` has zero type arguments. This is not expected, because we rely on the fact that every `ClassElement` instantiation in form of `InterfaceType` has the number of type arguments that is equal to the number of type parameters in the element. This is still true, kind of, it is just that elements are different.

```dart
void foo(A a) {}

class A {}

class A<T> {
  void bar() {
    foo(this);
  }
}
```

The exception:
```
  'package:analyzer/src/dart/element/subtype.dart': Failed assertion: line 311 pos 12: 'subArguments.length == superArguments.length': is not true.
  #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
  #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
  #2      SubtypeHelper._interfaceArguments (package:analyzer/src/dart/element/subtype.dart:311:12)
  #3      SubtypeHelper._isInterfaceSubtypeOf (package:analyzer/src/dart/element/subtype.dart:463:14)
  #4      SubtypeHelper.isSubtypeOf (package:analyzer/src/dart/element/subtype.dart:267:14)
  #5      SubtypeHelper.isSubtypeOf (package:analyzer/src/dart/element/subtype.dart:240:11)
  #6      SubtypeHelper.isSubtypeOf (package:analyzer/src/dart/element/subtype.dart:155:14)
  #7      SubtypeHelper.isSubtypeOf (package:analyzer/src/dart/element/subtype.dart:145:14)
  #8      TypeSystemImpl.isSubtypeOf2 (package:analyzer/src/dart/element/type_system.dart:1291:27)
  #9      CodeChecker._needsImplicitCast (package:analyzer/src/task/strong/checker.dart:875:15)
  #10     CodeChecker._checkImplicitCast (package:analyzer/src/task/strong/checker.dart:709:9)
  #11     CodeChecker.checkForCast (package:analyzer/src/task/strong/checker.dart:192:7)
  #12     CodeChecker.checkAssignment (package:analyzer/src/task/strong/checker.dart:152:5)
  #13     CodeChecker.checkArgument (package:analyzer/src/task/strong/checker.dart:133:5)
  #14     CodeChecker.checkArgumentList (package:analyzer/src/task/strong/checker.dart:147:7)
  #15     CodeChecker._checkFunctionApplication (package:analyzer/src/task/strong/checker.dart:655:7)
  #16     CodeChecker.visitMethodInvocation (package:analyzer/src/task/strong/checker.dart:450:7)
  #17     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7112:49)
```

And similar issue for inference:
```dart
void foo<U>(A<U> a) {}

class A {}

class A<T> {
  void bar() {
    foo(this);
  }
}
```

Results in:
```
  RangeError (index): Invalid value: Valid value range is empty: 0
  #0      List.[] (dart:core-patch/growable_array.dart:177:60)
  #1      TypeConstraintGatherer._interfaceType_arguments (package:analyzer/src/dart/element/type_constraint_gatherer.dart:565:30)
  #2      TypeConstraintGatherer._interfaceType (package:analyzer/src/dart/element/type_constraint_gatherer.dart:525:12)
  #3      TypeConstraintGatherer.trySubtypeMatch (package:analyzer/src/dart/element/type_constraint_gatherer.dart:297:14)
  #4      TypeConstraintGatherer.trySubtypeMatch (package:analyzer/src/dart/element/type_constraint_gatherer.dart:206:26)
  #5      TypeConstraintGatherer.trySubtypeMatch (package:analyzer/src/dart/element/type_constraint_gatherer.dart:145:14)
  #6      TypeConstraintGatherer.trySubtypeMatch (package:analyzer/src/dart/element/type_constraint_gatherer.dart:137:14)
  #7      GenericInferrer.tryMatchSubtypeOf (package:analyzer/src/dart/element/generic_inferrer.dart:287:28)
  #8      GenericInferrer.constrainArgument (package:analyzer/src/dart/element/generic_inferrer.dart:78:5)
  #9      TypeSystemImpl.inferGenericFunctionOrType (package:analyzer/src/dart/element/type_system.dart:755:16)
  #10     InvocationInferenceHelper._inferUpwards (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:319:32)
  #11     InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:392:28)
  #12     InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:351:7)
  #13     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:256:5)
  #14     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:799:24)
  #15     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:502:16)
  #16     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:93:7)
```

**Comment by srawlins** [comment]
This may be fixed. I cannot reproduce a crash with standalone `dart analyze`, nor in the IDE...

**Comment by scheglov** [comment]
Both still fail for me when run them as a unit test.
