### ISSUE TITLE
[Gardening] il_round_trip_deserialization_test started crashing on dartkp-linux-debug-x64

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#43359]
There are new test failures on [[vm/locks] Allow SafepointRwLocks reentrance, nesting read lock in write lock....[Analyzer] Handle directive comments that are split between directives](https://github.com/dart-lang/sdk/compare/725d3e4498c596e77edbb851861f59b649df3884~...3e0243fb16ddfed28d41eb303fff1e8b013114de).

The author of the CL does not think the failure is related to the CL. The tests were already flaky prior to the CL.

The tests
```
vm/dart_2/il_round_trip_deserialization_test/5 Crash (expected Pass)
vm/dart_2/il_round_trip_deserialization_test/7 Crash (expected Pass)
```
are failing on configurations
```
dartkp-linux-debug-x64
```

Here are the logs:
```
/====================================================================================\
| vm/dart_2/il_round_trip_deserialization_test/1 failed again (Crash, expected Pass) |
\====================================================================================/

--- Command "vm_compile_to_kernel" (took 22.000218s):
DART_CONFIGURATION=DebugX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/DebugX64/vm_platform_strong.dill -o /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.dill /b/s/w/ir/runtime/tests/vm/dart_2/il_round_trip_deserialization_test.dart --packages=/b/s/w/ir/.packages -Ddart.vm.product=false -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "precompiler" (took 17.000693s):
DART_CONFIGURATION=DebugX64 out/DebugX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.S --early-round-trip-serialization --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 5ms):
DART_CONFIGURATION=DebugX64 rm /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.dill

exit code:
0

--- Command "assemble" (took 01.000396s):
DART_CONFIGURATION=DebugX64 gcc -m64 -shared -nostdlib -o /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.aotsnapshot /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.S

exit code:
0

--- Command "remove_assembly" (took 30ms):
DART_CONFIGURATION=DebugX64 rm /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.S

exit code:
0

--- Command "vm" (took 120ms):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart_precompiled_runtime --early-round-trip-serialization --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.aotsnapshot

exit code:
-6

stderr:
../../runtime/vm/service_isolate.cc: 624: error: expected: !r.IsError()
version=2.10.0-edge.3e0243fb16ddfed28d41eb303fff1e8b013114de (be) (Tue Sep 8 16:26:43 2020 +0000) on "linux_x64"
pid=30786, thread=30788, isolate_group=vm-service(0x5610dcf8d080), isolate=vm-service(0x5610dcfb3600)
isolate_instructions=7f9bce3b3000, vm_instructions=7f9bce3b0000
  pc 0x00005610da36868c fp 0x00007f9bcdffe4f0 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x00005610da035672 fp 0x00007f9bcdffe5d0 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x00005610da3d2594 fp 0x00007f9bcdffe630 out/DebugX64/dart_precompiled_runtime+0x98f594
  pc 0x00005610da27cf7b fp 0x00007f9bcdffe6a0 dart::IsolateGroup::ForEachIsolate(std::__2::function<void (dart::Isolate*)>, bool)+0x1db
  pc 0x00005610da283386 fp 0x00007f9bcdffe6d0 out/DebugX64/dart_precompiled_runtime+0x840386
  pc 0x00005610da279f69 fp 0x00007f9bcdffe740 dart::Isolate::VisitIsolates(dart::IsolateVisitor*)+0x99
  pc 0x00005610da201445 fp 0x00007f9bcdffe780 dart::BootstrapNatives::DN_VMService_OnStart(dart::Thread*, dart::Zone*, dart::NativeArguments*)+0x105
  pc 0x00005610da290545 fp 0x00007f9bcdffe7f0 dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*))+0xc5
  pc 0x00005610da290bba fp 0x00007f9bcdffe980 dart::NativeEntry::LinkNativeCall(_Dart_NativeArguments*)+0x43a
  pc 0x00007f9bce3b1b2f fp 0x00007f9bcdffe9b0 /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.aotsnapshot+0x2b2f
  pc 0x00007f9bce466655 fp 0x00007f9bcdffe9c8 /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.aotsnapshot+0xb7655
  pc 0x00007f9bce466610 fp 0x00007f9bcdffe9e0 /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.aotsnapshot+0xb7610
  pc 0x00007f9bce463072 fp 0x00007f9bcdffea00 /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.aotsnapshot+0xb4072
  pc 0x00007f9bce3b18a9 fp 0x00007f9bcdffea68 /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_1/out.aotsnapshot+0x28a9
  pc 0x00005610da2482ab fp 0x00007f9bcdffeb00 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x10b
  pc 0x00005610da247f16 fp 0x00007f9bcdffeb60 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x166
  pc 0x00005610da3d296d fp 0x00007f9bcdffebf0 out/DebugX64/dart_precompiled_runtime+0x98f96d
  pc 0x00005610da3d270c fp 0x00007f9bcdffec90 out/DebugX64/dart_precompiled_runtime+0x98f70c
  pc 0x00005610da3fb79b fp 0x00007f9bcdffed30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x1cb
  pc 0x00005610da3fc1d9 fp 0x00007f9bcdffed80 dart::ThreadPool::Worker::Main(unsigned long)+0x179
  pc 0x00005610da3632a9 fp 0x00007f9bcdffeed0 out/DebugX64/dart_precompiled_runtime+0x9202a9
-- End of DumpStackTrace
[exit     : sp(0) fp(0x7f9bcdffe9b0) pc(0)]
[bare-dart : sp(0x7f9bcdffe9c0) fp(0x7f9bcdffe9c8) pc(0x7f9bce466655) *dart:_vmservice_::__onStart@13168694 ]
[bare-dart : sp(0x7f9bcdffe9d8) fp(0x7f9bcdffe9e0) pc(0x7f9bce466610) *dart:_vmservice_VMService_VMService. ]
[bare-dart : sp(0x7f9bcdffe9f0) fp(0x7f9bcdffea00) pc(0x7f9bce463072) *dart:vmservice_io_::_main ]
[entry    : sp(0x7f9bcdffea10) fp(0x7f9bcdffea68) pc(0x7f9bce3b18a9)]

--- Re-run this test:
python tools/test.py -n dartkp-linux-debug-x64 vm/dart_2/il_round_trip_deserialization_test/1


/====================================================================================\
| vm/dart_2/il_round_trip_deserialization_test/3 failed again (Crash, expected Pass) |
\====================================================================================/

--- Command "vm_compile_to_kernel" (took 22.000355s):
DART_CONFIGURATION=DebugX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/DebugX64/vm_platform_strong.dill -o /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.dill /b/s/w/ir/runtime/tests/vm/dart_2/il_round_trip_deserialization_test.dart --packages=/b/s/w/ir/.packages -Ddart.vm.product=false -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "precompiler" (took 17.000907s):
DART_CONFIGURATION=DebugX64 out/DebugX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.S --early-round-trip-serialization --late-round-trip-serialization --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 5ms):
DART_CONFIGURATION=DebugX64 rm /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.dill

exit code:
0

--- Command "assemble" (took 01.000138s):
DART_CONFIGURATION=DebugX64 gcc -m64 -shared -nostdlib -o /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.aotsnapshot /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.S

exit code:
0

--- Command "remove_assembly" (took 49ms):
DART_CONFIGURATION=DebugX64 rm /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.S

exit code:
0

--- Command "vm" (took 127ms):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart_precompiled_runtime --early-round-trip-serialization --late-round-trip-serialization --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.aotsnapshot

exit code:
-6

stdout:
Hello, world!

stderr:
../../runtime/vm/service_isolate.cc: 624: error: expected: !r.IsError()
version=2.10.0-edge.3e0243fb16ddfed28d41eb303fff1e8b013114de (be) (Tue Sep 8 16:26:43 2020 +0000) on "linux_x64"
pid=30802, thread=30804, isolate_group=vm-service(0x564894a67080), isolate=vm-service(0x564894a8d600)
isolate_instructions=7f6f1de59000, vm_instructions=7f6f1de56000
  pc 0x0000564892fb968c fp 0x00007f6f1da7e4f0 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x0000564892c86672 fp 0x00007f6f1da7e5d0 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x0000564893023594 fp 0x00007f6f1da7e630 out/DebugX64/dart_precompiled_runtime+0x98f594
  pc 0x0000564892ecdf7b fp 0x00007f6f1da7e6a0 dart::IsolateGroup::ForEachIsolate(std::__2::function<void (dart::Isolate*)>, bool)+0x1db
  pc 0x0000564892ed4386 fp 0x00007f6f1da7e6d0 out/DebugX64/dart_precompiled_runtime+0x840386
  pc 0x0000564892ecaf69 fp 0x00007f6f1da7e740 dart::Isolate::VisitIsolates(dart::IsolateVisitor*)+0x99
  pc 0x0000564892e52445 fp 0x00007f6f1da7e780 dart::BootstrapNatives::DN_VMService_OnStart(dart::Thread*, dart::Zone*, dart::NativeArguments*)+0x105
  pc 0x0000564892ee1545 fp 0x00007f6f1da7e7f0 dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*))+0xc5
  pc 0x0000564892ee1bba fp 0x00007f6f1da7e980 dart::NativeEntry::LinkNativeCall(_Dart_NativeArguments*)+0x43a
  pc 0x00007f6f1de57b2f fp 0x00007f6f1da7e9b0 /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.aotsnapshot+0x2b2f
  pc 0x00007f6f1df0c5f1 fp 0x00007f6f1da7e9c8 /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.aotsnapshot+0xb75f1
  pc 0x00007f6f1df0c5ac fp 0x00007f6f1da7e9e0 /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.aotsnapshot+0xb75ac
  pc 0x00007f6f1df0900e fp 0x00007f6f1da7ea00 /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.aotsnapshot+0xb400e
  pc 0x00007f6f1de578a9 fp 0x00007f6f1da7ea68 /b/s/w/ir/out/DebugX64/generated_compilations/dartkp/runtime_tests_vm_dart_2_il_round_trip_deserialization_test.dart_3/out.aotsnapshot+0x28a9
  pc 0x0000564892e992ab fp 0x00007f6f1da7eb00 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x10b
  pc 0x0000564892e98f16 fp 0x00007f6f1da7eb60 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x166
  pc 0x000056489302396d fp 0x00007f6f1da7ebf0 out/DebugX64/dart_precompiled_runtime+0x98f96d
  pc 0x000056489302370c fp 0x00007f6f1da7ec90 out/DebugX64/dart_precompiled_runtime+0x98f70c
  pc 0x000056489304c79b fp 0x00007f6f1da7ed30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x1cb
  pc 0x000056489304d1d9 fp 0x00007f6f1da7ed80 dart::ThreadPool::Worker::Main(unsigned long)+0x179
  pc 0x0000564892fb42a9 fp 0x00007f6f1da7eed0 out/DebugX64/dart_precompiled_runtime+0x9202a9
-- End of DumpStackTrace
[exit     : sp(0) fp(0x7f6f1da7e9b0) pc(0)]
[bare-dart : sp(0x7f6f1da7e9c0) fp(0x7f6f1da7e9c8) pc(0x7f6f1df0c5f1) *dart:_vmservice_::__onStart@13168694 ]
[bare-dart : sp(0x7f6f1da7e9d8) fp(0x7f6f1da7e9e0) pc(0x7f6f1df0c5ac) *dart:_vmservice_VMService_VMService. ]
[bare-dart : sp(0x7f6f1da7e9f0) fp(0x7f6f1da7ea00) pc(0x7f6f1df0900e) *dart:vmservice_io_::_main ]
[entry    : sp(0x7f6f1da7ea10) fp(0x7f6f1da7ea68) pc(0x7f6f1de578a9)]

--- Re-run this test:
python tools/test.py -n dartkp-linux-debug-x64 vm/dart_2/il_round_trip_deserialization_test/3

```

Instrumenting the code to print the error shows:
```
stderr:
**** Unhandled exception:
RangeError (length): Invalid value: Not in inclusive range 0..15: 18
#0      _LinkedHashMapMixin._insert (dart:collection-patch/compact_hash.dart)
#1      _LinkedHashMapMixin.[]= (dart:collection-patch/compact_hash.dart:276)
#2      RunningIsolates.isolateStartup (dart:_vmservice/running_isolates.dart:18)
#3      _registerIsolate (dart:_vmservice:700)
#4      _onStart (dart:_vmservice:703)
#5      new VMService (dart:_vmservice:458)
#6      main (dart:vmservice_io:281)

```

**Comment by dcharkes** [comment]
cc @sstrickl

**Comment by bkonyi** [comment]
Saw this again today: https://ci.chromium.org/p/dart/builders/try/vm-kernel-precomp-linux-debug-x64-try/3251?

**Comment by sstrickl** [comment]
Yep, have added to https://github.com/dart-lang/sdk/issues/43617, I've approved for now and do plan to look into after the other failures from today. /1 has been flaky in the past, but seeing  /3, /5, and /7 failing also is interesting.
