### ISSUE TITLE
The Fuchsia tests on Dart SDK don't seem to work.

### ISSUE THREAD

**Issue by filmil** [dart-lang/sdk#43386]
This is FYI, I was trying out the Dart SDK tests on Fuchsia, and hit a dead end like so. I had to kill my own qemu and package server for the test to begin producing output. But even then, it seems to get stuck in a loop and crash after an hour.  See below.

```
$ tools/build.py --os=fuchsia fuchsia_test_package
# ... output snipped ...
$ tools/test.py -j 1 -n dartk-fuchsia-debug-x64
Test configurations:
    dartk-fuchsia-debug-x64(architecture: x64, compiler: dartk, mode: debug, runtime: vm, system: fuchsia)
Suites tested: samples, standalone_2, corelib_2, language_2, vm, benchmark_smoke, utils, lib_2, analyze_library, service, kernel, ffi_2
    dartk-fuchsia-debug-x64(architecture: x64, compiler: dartk, mode: debug, runtime: vm, system: fuchsia)
Suites tested: observatory_ui
2020-09-10 12:01:17.512074 Info: Starting Fuchsia emulator
2020-09-10 12:01:26.575590 Info: Fuchsia emulator ready: step-atom-yard-juicy
2020-09-10 12:01:26.575696 Info: Starting Fuchsia package server
2020-09-10 12:01:27.775428 Info: Fuchsia package server ready
2020-09-10 12:01:27.777576 Info: Publishing package: out/DebugFuchsiaX64/gen/dart_test_debug/dart_test_debug.far
2020-09-10 12:01:28.353634 Info: Verifying publication
2020-09-10 12:35:40.810781 Info: Publication successful
2020-09-10 12:35:40.811344 Info: Publishing package: out/DebugFuchsiaX64/gen/dart_test_debug/dart_test_debug.far
2020-09-10 12:35:41.145933 Info: Verifying publication
2020-09-10 13:09:06.374811 Info: Publication successful
Fatal error occurred: ProcessException: No such file or directory
  Command: out/DebugFuchsiaX64/run_vm_tests --list
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:473:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:616:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      VMTestSuite._listTests (package:test_runner/src/test_suite.dart:343:26)
#4      VMTestSuite.findTestCases (package:test_runner/src/test_suite.dart:290:24)
#5      TestCaseEnqueuer.enqueueTestSuites (package:test_runner/src/process_queue.dart:239:13)
#6      new ProcessQueue (package:test_runner/src/process_queue.dart:177:22)
#7      testConfigurations (package:test_runner/src/test_configurations.dart:263:3)
<asynchronous suspension>
#8      main (file:///disk2/fmil/code/dart-sdk/sdk/pkg/test_runner/bin/test_runner.dart:39:5)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by liamappelbe** [comment]
Sorry, I forgot to mention on the other thread that you can only run standalone_2 integration tests at the moment.

The command that failed to run was listing the VM unit tests, which is not supported. We could build run_vm_tests under --os=fuchsia, but it would be a fuchsia binary, and the test infra is trying to run it on the host machine. This is a limitation of the test infra. It's fixable, but not on my todo list right now, because we don't expect unit tests to be an issue on Fuchsia.

We're only really interested in the IO integration tests, so those are the only ones bundled with the test package. The goal is to get all of standalone_2 passing. Last time I checked, about 2/3rds were passing. The remaining failures are mostly caused by some sort of socket issue that I don't have the expertise to debug, so I was planning to wait until we have a bot running and file bugs about the failures.

I've been using standalone_2/io/http_basic_test as my quick simple test:

```
tools/build.py --os=fuchsia fuchsia_test_package && tools/test.py -j 1 -n dartk-fuchsia-debug-x64 standalone_2/io/http_basic_test
```

If you want to try running all the standalone_2 tests:

```
tools/build.py --os=fuchsia fuchsia_test_package && tools/test.py -j 1 -n dartk-fuchsia-debug-x64 standalone_2
```
