### ISSUE TITLE
Failures on [dart/sendandexit] Fix validation of the sendAndExit messages and the test.

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#43385]
There are new test failures on [[dart/sendandexit] Fix validation of the sendAndExit messages and the test.](https://github.com/dart-lang/sdk/commit/a9ed5d1d1e9703a740640a2d8e11bf569b69dfc0).

The tests
```
vm/dart_2/sendandexit_test Crash (expected Pass)
```
are failing on configurations
```
app_jitk-linux-product-x64
```

```
$ out/ProductX64/dart --snapshot=$DH/sdk/out/ProductX64/generated_compilations/app_jitk/runtime_tests_vm_dart_2_sendandexit_test/out.jitsnapshot --snapshot-kind=app-jit --enable-isolate-groups --ignore-unrecognized-flags --packages=$DH/sdk/.packages $DH/sdk/runtime/tests/vm/dart/sendandexit_test.dart
```
fails with "No serialization cluster defined" for cid=1(FreeListElement)

```
#0  0x0000555556c37b97 in dart::Serializer::UnexpectedObject (this=<optimized out>, raw_object=..., message=<optimized out>) at ../../runtime/vm/clustered_snapshot.cc:5951
#1  dart::Serializer::Trace (this=<optimized out>, object=...) at ../../runtime/vm/clustered_snapshot.cc:5924
#2  0x0000555556c37dbc in dart::Serializer::Serialize (this=0x7fffffffd0a0, roots=0x7fffffffd080) at ../../runtime/vm/clustered_snapshot.cc:6008
#3  0x0000555556c396df in dart::FullSnapshotWriter::WriteProgramSnapshot (this=0x7fffffffd388, num_base_objects=0, units=<optimized out>) at ../../runtime/vm/clustered_snapshot.cc:6933
#4  0x0000555556c39822 in dart::FullSnapshotWriter::WriteFullSnapshot (this=0x7fffffffd388, data=0x0) at ../../runtime/vm/clustered_snapshot.cc:7003
#5  0x0000555556f42bd8 in Dart_CreateAppJITSnapshotAsBlobs (isolate_snapshot_data_buffer=<optimized out>, isolate_snapshot_data_size=0x7fffffffd448, 
    isolate_snapshot_instructions_buffer=<optimized out>, isolate_snapshot_instructions_size=0x7fffffffd438) at ../../runtime/vm/dart_api_impl.cc:7116
#6  0x0000555556abe557 in dart::bin::Snapshot::GenerateAppJIT (
    snapshot_filename=0x7fffffffdb7b "$DH/sdk/out/ProductX64/generated_compilations/app_jitk/runtime_tests_vm_dart_2_sendandexit_test/out.jitsnapshot")
    at ../../runtime/bin/snapshot_utils.cc:505
#7  0x0000555556ac0532 in dart::bin::RunMainIsolate (script_name=0x5555579c0180 "$DH/sdk/runtime/tests/vm/dart/sendandexit_test.dart", 
    dart_options=0x7fffffffd528) at ../../runtime/bin/main.cc:1019
#8  0x0000555556ac14ae in dart::bin::main (argc=7, argv=0x7fffffffd718) at ../../runtime/bin/main.cc:1321
#9  0x0000555556ac1eb9 in main (argc=1470288512, argv=0x0) at ../../runtime/bin/main.cc:1361
```

**Comment by aam** [comment]
obsolete
