### ISSUE TITLE
Crasher in parser

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#43401]
The analyzer gives errors on:

```dart
extension Test<S, T> on S {
  T operator >>(T Function(S s) f) => f(this);
}

void main() {
  Object o = Object() Test<Object,Object>.>> ((Object o) => o);
  print(o);
}
```

but the front end crashes with:
<details> 
<summary>type 'ParserRecovery' is not a subtype of type 'Identifier'</summary>

```
type 'ParserRecovery' is not a subtype of type 'Identifier'
#0      BodyBuilder.pushQualifiedReference (package:front_end/src/fasta/kernel/body_builder.dart:3919:16)
#1      BodyBuilder.endConstructorReference (package:front_end/src/fasta/kernel/body_builder.dart:3872:5)
#2      Parser.parseConstructorReference (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4051:14)
#3      Parser.parseImplicitCreationExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5452:13)
#4      Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4864:22)
#5      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4604:13)
#6      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4545:13)
#7      Parser.parseExpressionStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4510:13)
#8      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6064:16)
#9      Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4306:14)
#10     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4296:20)
#11     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4201:15)
#12     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:990:14)
#13     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:358:5)
#14     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2743:14)
#15     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2534:14)
#16     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:501:14)
#17     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
#18     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:427:14)
<asynchronous suspension>
#19     Loader.buildBodies (package:front_end/src/fasta/loader.dart:242:15)
#20     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:382:20)
#21     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#22     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:380:12)
#23     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:177:38)
<asynchronous suspension>
#24     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#25     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#26     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#27     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#28     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#29     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#30     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#31     new Future.sync (dart:async/future.dart:223:31)
#32     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#33     _rootRun (dart:async/zone.dart:1190:13)
#34     _CustomZone.run (dart:async/zone.dart:1093:19)
#35     _runZoned (dart:async/zone.dart:1630:10)
#36     runZoned (dart:async/zone.dart:1550:10)
#37     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#38     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#39     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#40     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#41     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:441:17)
#42     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:208:45)
#43     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#44     _rootRun (dart:async/zone.dart:1182:47)
#45     _CustomZone.run (dart:async/zone.dart:1093:19)
#46     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#47     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#48     _rootRun (dart:async/zone.dart:1190:13)
#49     _CustomZone.run (dart:async/zone.dart:1093:19)
#50     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#51     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#52     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#53     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

</details>

@johnniwinther @jensjoha

**Comment by asashour** [comment]
This seems to be fixed.

**Comment by johnniwinther** [comment]
@asashour Thank for checking.
