### ISSUE TITLE
Analysis server terminates with "Cannot resolve symbolic links" when analyzing Flutter project with standard Dart SDK

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#43497]
I accidentally found this crash. It's not a typical setup, but I don't think it should crash.

- Create a Flutter project with `flutter create` (including allowing it to fetch packages)
- Open it in an IDE using a standard Dart SDK (the latest nightly) without Flutter

During analysis, it throws this error and terminates:

```
[11:39:15 AM] [Analyzer] [Info] <== {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":622,"uri":"dart:js","items":[{"label":"JsArray","declaringLibraryUri":"dart:js","element":{"kind":"CLASS","name":"JsArray","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":7140,"length":0,"startLine":175,"startColumn":7},"flags":0},"relevanceTags":["ElementKind.CLASS","dart:js::JsArray","JsArray"]},{"label":"JsArray","declaringLibraryUri":"dart:js","element":{"kind":"CONSTRUCTOR","name":"","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":7248,"length":0,"startLine":177,"startColumn":20},"flags":0,"parameters":"()","returnType":"JsArray"},"parameterNames":[],"parameterTypes":[],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:js::JsArray",""],"requiredParameterCount":0},{"label":"JsArray.from","declaringLibraryUri":"dart:js","element":{"kind":"CONSTRUCTOR","name":"from","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":7377,"length":0,"startLine":181,"startColumn":28},"flags":0,"parameters":"(Iterable<E> other)","returnType":"JsArray"},"defaultArgumentListString":"other","defaultArgumentListTextRanges":[0,5],"parameterNames":["other"],"parameterTypes":["Iterable<E>"],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:js::JsArray","from"],"requiredParameterCount":1},{"label":"allowInteropCaptureThis","declaringLibraryUri":"dart:js","element":{"kind":"FUNCTION","name":"allowInteropCaptureThis","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":8986,"length":0,"startLine":233,"startColumn":19},"flags":0,"parameters":"(Function f)","returnType":"Function"},"defaultArgumentListString":"f","defaultArgumentListTextRanges":[0,1],"parameterNames":["f"],"parameterTypes":["Function"],"relevanceTags":["ElementKind.FUNCTION","allowInteropCaptureThis"],"requiredParameterCount":1},{"label":"JsFunction","declaringLibraryUri":"dart:js","element":{"kind":"CLASS","name":"JsFunction","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":6668,"length":0,"startLine":164,"startColumn":7},"flags":0},"relevanceTags":["ElementKind.CLASS","dart:js::JsFunction","JsFunction"]},{"label":"JsFunction.withThis","declaringLibraryUri":"dart:js","element":{"kind":"CONSTRUCTOR","name":"withThis","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":6876,"length":0,"startLine":167,"startColumn":31},"flags":0,"parameters":"(Function f)","returnType":"JsFunction"},"defaultArgumentListString":"f","defaultArgumentListTextRanges":[0,1],"parameterNames":["f"],"parameterTypes":["Function"],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:js::JsFunction","withThis"],"requiredParameterCount":1},{"label":"JsObject","declaringLibraryUri":"dart:js","element":{"kind":"CLASS","name":"JsObject","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":3991,"length":0,"startLine":96,"startColumn":7},"flags":0},"relevanceTags":["ElementKind.CLASS","dart:js::JsObject","JsObject"]},{"label":"JsObject","declaringLibraryUri":"dart:js","element":{"kind":"CONSTRUCTOR","name":"","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":4121,"length":0,"startLine":99,"startColumn":20},"flags":0,"parameters":"(JsFunction constructor, [List? arguments])","returnType":"JsObject"},"defaultArgumentListString":"constructor","defaultArgumentListTextRanges":[0,11],"parameterNames":["constructor","arguments"],"parameterTypes":["JsFunction","List?"],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:js::JsObject",""],"requiredParameterCount":1},{"label":"JsObject.fromBrowserObject","declaringLibraryUri":"dart:js","element":{"kind":"CONSTRUCTOR","name":"fromBrowserObject","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":4624,"length":0,"startLine":110,"startColumn":29},"flags":0,"parameters":"(Object object)","returnType":"JsObject"},"defaultArgumentListString":"object","defaultArgumentListTextRanges":[0,6],"parameterNames":["object"],"parameterTypes":["Object"],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:js::JsObject","fromBrowserObject"],"requiredParameterCount":1},{"label":"JsObject.jsify","declaringLibraryUri":"dart:js","element":{"kind":"CONSTRUCTOR","name":"jsify","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":5130,"length":0,"startLine":119,"startColumn":29},"flags":0,"parameters":"(Object object)","returnType":"JsObject"},"defaultArgumentListString":"object","defaultArgumentListTextRanges":[0,6],"parameterNames":["object"],"parameterTypes":["Object"],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:js::JsObject","jsify"],"requiredParameterCount":1},{"label":"context","declaringLibraryUri":"dart:js","element":{"kind":"GETTER","name":"context","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":3799,"length":0,"startLine":90,"startColumn":23},"flags":0,"returnType":"JsObject"},"relevanceTags":["ElementKind.FUNCTION","context"]},{"label":"allowInterop","declaringLibraryUri":"dart:js","element":{"kind":"FUNCTION","name":"allowInterop","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/js/js.dart","offset":8651,"length":0,"startLine":224,"startColumn":12},"flags":0,"parameters":"(F f)","returnType":"F","typeParameters":"<F extends Function>"},"defaultArgumentListString":"f","defaultArgumentListTextRanges":[0,1],"parameterNames":["f"],"parameterTypes":["F"],"relevanceTags":["ElementKind.FUNCTION","allowInterop"],"requiredParameterCount":1}]}],"removedLibraries":[]}}
[11:39:15 AM] [Analyzer] [Info] <== {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":623,"uri":"dart:isolate","items":[{"label":"Capability","declaringLibraryUri":"dart:isolate","element":{"kind":"CLASS","name":"Capability","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/capability.dart","offset":1148,"length":0,"startLine":29,"startColumn":7},"flags":0},"relevanceTags":["dart:isolate::Capability","Capability"]},{"label":"Capability","declaringLibraryUri":"dart:isolate","element":{"kind":"CONSTRUCTOR","name":"","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/capability.dart","offset":1241,"length":0,"startLine":33,"startColumn":20},"flags":0,"parameters":"()","returnType":"Capability"},"parameterNames":[],"parameterTypes":[],"relevanceTags":["dart:isolate::Capability",""],"requiredParameterCount":0},{"label":"Isolate","declaringLibraryUri":"dart:isolate","element":{"kind":"CLASS","name":"Isolate","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":2669,"length":0,"startLine":73,"startColumn":7},"flags":0},"relevanceTags":["ElementKind.CLASS","dart:isolate::Isolate","Isolate"]},{"label":"Isolate.immediate","declaringLibraryUri":"dart:isolate","element":{"kind":"FIELD","name":"immediate","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":2764,"length":0,"startLine":75,"startColumn":20},"flags":10,"returnType":"int"},"relevanceTags":["ElementKind.FIELD","ElementKind.FIELD+const","dart:core::int","immediate"]},{"label":"Isolate.beforeNextEvent","declaringLibraryUri":"dart:isolate","element":{"kind":"FIELD","name":"beforeNextEvent","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":2876,"length":0,"startLine":77,"startColumn":20},"flags":10,"returnType":"int"},"relevanceTags":["ElementKind.FIELD","ElementKind.FIELD+const","dart:core::int","beforeNextEvent"]},{"label":"Isolate","declaringLibraryUri":"dart:isolate","element":{"kind":"CONSTRUCTOR","name":"","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":5799,"length":0,"startLine":156,"startColumn":3},"flags":0,"parameters":"(this.controlPort, {this.pauseCapability, this.terminateCapability})","returnType":"Isolate"},"defaultArgumentListString":"controlPort","defaultArgumentListTextRanges":[0,11],"parameterNames":["controlPort","pauseCapability","terminateCapability"],"parameterTypes":["","",""],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:isolate::Isolate",""],"requiredParameterCount":1},{"label":"Isolate.current","declaringLibraryUri":"dart:isolate","element":{"kind":"GETTER","name":"current","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":6430,"length":0,"startLine":172,"startColumn":31},"flags":8,"returnType":"Isolate"},"relevanceTags":["ElementKind.FIELD","current"]},{"label":"Isolate.packageRoot","declaringLibraryUri":"dart:isolate","element":{"kind":"GETTER","name":"packageRoot","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":6742,"length":0,"startLine":181,"startColumn":36},"flags":40,"returnType":"Future<Uri?>"},"relevanceTags":["ElementKind.FIELD","packageRoot"]},{"label":"Isolate.packageConfig","declaringLibraryUri":"dart:isolate","element":{"kind":"GETTER","name":"packageConfig","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":7048,"length":0,"startLine":190,"startColumn":36},"flags":8,"returnType":"Future<Uri?>"},"relevanceTags":["ElementKind.FIELD","packageConfig"]},{"label":"RawReceivePort","declaringLibraryUri":"dart:isolate","element":{"kind":"CLASS","name":"RawReceivePort","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":28247,"length":0,"startLine":714,"startColumn":16},"flags":1},"relevanceTags":["ElementKind.CLASS","dart:isolate::RawReceivePort","RawReceivePort"]},{"label":"RawReceivePort","declaringLibraryUri":"dart:isolate","element":{"kind":"CONSTRUCTOR","name":"","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":28519,"length":0,"startLine":722,"startColumn":20},"flags":0,"parameters":"([Function? handler])","returnType":"RawReceivePort"},"parameterNames":["handler"],"parameterTypes":["Function?"],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:isolate::RawReceivePort",""],"requiredParameterCount":0},{"label":"ReceivePort","declaringLibraryUri":"dart:isolate","element":{"kind":"CLASS","name":"ReceivePort","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":26746,"length":0,"startLine":665,"startColumn":16},"flags":1},"relevanceTags":["ElementKind.CLASS","dart:isolate::ReceivePort","ReceivePort"]},{"label":"ReceivePort","declaringLibraryUri":"dart:isolate","element":{"kind":"CONSTRUCTOR","name":"","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":27202,"length":0,"startLine":676,"startColumn":20},"flags":0,"parameters":"()","returnType":"ReceivePort"},"parameterNames":[],"parameterTypes":[],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:isolate::ReceivePort",""],"requiredParameterCount":0},{"label":"ReceivePort.fromRawReceivePort","declaringLibraryUri":"dart:isolate","element":{"kind":"CONSTRUCTOR","name":"fromRawReceivePort","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":27419,"length":0,"startLine":684,"startColumn":32},"flags":0,"parameters":"(RawReceivePort rawPort)","returnType":"ReceivePort"},"defaultArgumentListString":"rawPort","defaultArgumentListTextRanges":[0,7],"parameterNames":["rawPort"],"parameterTypes":["RawReceivePort"],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:isolate::ReceivePort","fromRawReceivePort"],"requiredParameterCount":1},{"label":"IsolateSpawnException","declaringLibraryUri":"dart:isolate","element":{"kind":"CLASS","name":"IsolateSpawnException","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":706,"length":0,"startLine":28,"startColumn":7},"flags":0},"relevanceTags":["ElementKind.CLASS","dart:isolate::IsolateSpawnException","IsolateSpawnException"]},{"label":"IsolateSpawnException","declaringLibraryUri":"dart:isolate","element":{"kind":"CONSTRUCTOR","name":"","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":861,"length":0,"startLine":32,"startColumn":3},"flags":0,"parameters":"(this.message)","returnType":"IsolateSpawnException"},"defaultArgumentListString":"message","defaultArgumentListTextRanges":[0,7],"parameterNames":["message"],"parameterTypes":[""],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:isolate::IsolateSpawnException",""],"requiredParameterCount":1},{"label":"RemoteError","declaringLibraryUri":"dart:isolate","element":{"kind":"CLASS","name":"RemoteError","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":29195,"length":0,"startLine":750,"startColumn":7},"flags":0},"relevanceTags":["ElementKind.CLASS","dart:isolate::RemoteError","RemoteError"]},{"label":"RemoteError","declaringLibraryUri":"dart:isolate","element":{"kind":"CONSTRUCTOR","name":"","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":29288,"length":0,"startLine":753,"startColumn":3},"flags":0,"parameters":"(String description, String stackDescription)","returnType":"RemoteError"},"defaultArgumentListString":"description, stackDescription","defaultArgumentListTextRanges":[0,11,13,16],"parameterNames":["description","stackDescription"],"parameterTypes":["String","String"],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:isolate::RemoteError",""],"requiredParameterCount":2},{"label":"SendPort","declaringLibraryUri":"dart:isolate","element":{"kind":"CLASS","name":"SendPort","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":24778,"length":0,"startLine":615,"startColumn":16},"flags":1},"relevanceTags":["ElementKind.CLASS","dart:isolate::SendPort","SendPort"]},{"label":"SendPort","declaringLibraryUri":"dart:isolate","element":{"kind":"CONSTRUCTOR","name":"","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":4294967295,"length":0,"startLine":0,"startColumn":0},"flags":0,"parameters":"()","returnType":"SendPort"},"parameterNames":[],"parameterTypes":[],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:isolate::SendPort",""],"requiredParameterCount":0},{"label":"TransferableTypedData","declaringLibraryUri":"dart:isolate","element":{"kind":"CLASS","name":"TransferableTypedData","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":29993,"length":0,"startLine":772,"startColumn":16},"flags":1},"relevanceTags":["ElementKind.CLASS","dart:isolate::TransferableTypedData","TransferableTypedData"]},{"label":"TransferableTypedData.fromList","declaringLibraryUri":"dart:isolate","element":{"kind":"CONSTRUCTOR","name":"fromList","location":{"file":"/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart","offset":30341,"length":0,"startLine":780,"startColumn":42},"flags":0,"parameters":"(List<TypedData> list)","returnType":"TransferableTypedData"},"defaultArgumentListString":"list","defaultArgumentListTextRanges":[0,4],"parameterNames":["list"],"parameterTypes":["List<TypedData>"],"relevanceTags":["ElementKind.CONSTRUCTOR","dart:isolate::TransferableTypedData","fromList"],"requiredParameterCount":1}]}],"removedLibraries":[]}}
[11:39:15 AM] [Analyzer] [Error] Unhandled exception:
FileSystemException(path=/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/io/network_policy.dart; message=Cannot resolve symbolic links)
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:732:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1076:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:999:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
[11:39:15 AM] [Analyzer] [Info] Process terminated! 255, null
```

As far as I can tell, there are no symbolic links at all in the path that's included in the error. My Flutter SDK is current latest master (as of a few hours ago). I was unable to reproduce this by opening the project (correctly) with a Flutter SDK though.

@bwilkerson

**Comment by DanTup** [comment]
Here's the original stack:

```
[12:23:55 PM] [Analyzer] [Error] Unhandled exception:
FileSystemException(path=/Users/danny/Dev/Google/flutter/bin/cache/pkg/sky_engine/lib/io/network_policy.dart; message=Cannot resolve symbolic links)
#0      _PhysicalFile.resolveSymbolicLinksSync (package:analyzer/file_system/physical_file_system.dart:211:7)
#1      _OverlayResource.resolveSymbolicLinksSync (package:analyzer/file_system/overlay_file_system.dart:390:50)
#2      DeclarationsTracker._resolveLinks (package:analyzer/src/services/available_declarations.dart:809:25)
#3      DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:716:12)
#4      _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1756:20)
#5      _File.refresh (package:analyzer/src/services/available_declarations.dart:1231:19)
#6      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:699:14)
#7      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:601:18)
#8      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:302:13)
#9      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1939:35)
```

Turns out, the file in the path actually does not exist - I had misread the filenames.

The file *does* exist in the real Dart SDK at `/Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/lib/io/network_policy.dart` but it's not in the "sky_engine" package where it's being looked for.§

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/163720

**Comment by DanTup** [comment]
Works now, thanks!
