### ISSUE TITLE
Dart Analyzer Error 。Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by zlssy** [dart-lang/sdk#43531]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.8.4`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.6, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.4, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

For additional log information, please append the contents of
file:///private/var/folders/9f/9bnj44dx22d5z95j591x7z2r0000gn/T/report.txt.

**Comment by srawlins** [comment]
This has not been reported again since Dart 2.8.4; please re-open if you see this in a recent version of Dart/Flutter.
