### ISSUE TITLE
Exception throwing machinery must not allocate on the Dart heap

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#43543]
Allocation during exception throwing can lead to divergence when out of memory:

```
#0  dart::Exceptions::Throw (thread=0x55555812d800, exception=...) at ../../runtime/vm/exceptions.cc:1016
#1  0x0000555557104f6e in dart::Object::Allocate (cls_id=79, size=80, space=<optimized out>) at ../../runtime/vm/object.cc:2655
#2  0x00005555571061b2 in dart::Array::New (class_id=79, len=6, space=<optimized out>) at ../../runtime/vm/object.cc:23291
#3  dart::Array::New (len=6, space=(dart::Heap::kCode | unknown: 240)) at ../../runtime/vm/object.cc:23263
#4  0x00005555570b32fd in dart::ExceptionHandlerFinder::ExecuteCatchEntryMoves (this=0x7ffff69fd3b0, moves=...) at ../../runtime/vm/exceptions.cc:255
#5  0x00005555570b2fa1 in dart::ExceptionHandlerFinder::PrepareFrameForCatchEntry (this=0x7ffff69fd3b0) at ../../runtime/vm/exceptions.cc:249
#6  0x00005555570b205d in dart::ThrowExceptionHelper (thread=0x55555812d800, incoming_exception=..., existing_stacktrace=..., is_rethrow=<optimized out>) at ../../runtime/vm/exceptions.cc:876
#7  0x00005555570b1824 in dart::Exceptions::Throw (thread=0x55555812d800, exception=...) at ../../runtime/vm/exceptions.cc:1016
#8  0x0000555557104f6e in dart::Object::Allocate (cls_id=56, size=32, space=<optimized out>) at ../../runtime/vm/object.cc:2655
#9  0x000055555713e8ca in dart::GrowableObjectArray::New (array=..., space=(dart::Heap::kCode | unknown: 240)) at ../../runtime/vm/object.cc:23528
#10 0x000055555702e621 in dart::DN_HelperGrowableList_allocate (isolate=<optimized out>, thread=<optimized out>, zone=0x555558614d00, arguments=<optimized out>) at ../../runtime/lib/growable_array.cc:25
#11 dart::BootstrapNatives::DN_GrowableList_allocate (thread=<optimized out>, zone=0x555558614d00, arguments=<optimized out>) at ../../runtime/lib/growable_array.cc:14
#12 0x00005555570fd3b0 in dart::NativeEntry::BootstrapNativeCallWrapper (args=0x7ffff69fd610, func=0x55555702e590 <dart::BootstrapNatives::DN_GrowableList_allocate(dart::Thread*, dart::Zone*, dart::NativeArguments*)>) at ../../runtime/vm/native_entry.cc:140
```

**Comment by mkustermann** [comment]
Something I wanted to change for a long time (I modified that code last time to fix a bug).

**Comment by mkustermann** [comment]
This particular issue reported above I've addressed - though there can be other cases. e.g. @rmacnak-google identified that a try/catch handler can cause allocation of ICData when catching a OOM exception.

**Comment by cskau-g** [comment]
The test introduced in [164540](https://dart-review.googlesource.com/c/sdk/+/164540) is unfortunately failing across multiple bots (as also tracked on several other related issues), but since this issue is still open I'll tag that onto here and approve the failures for now.

**Comment by rmacnak-google** [comment]
c8dea19836d95c0cc548def26a20b9e6a79d3ba2
