### ISSUE TITLE
Exception  after applying bulk-fixes

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#43568]
Once parts are properly handled, (#43564), a new exception occurs after fixes are applied.

```
Done.
Unhandled exception:
FormatException: Unterminated string (at character 1337)
...e":"Name non-constant identifiers using lowerCamelCase.","code":"non_consta
                                                                              ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:515:9)
#2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
#3      JsonDecoder.convert (dart:convert/json.dart:505:36)
#4      JsonCodec.decode (dart:convert/json.dart:156:41)
#5      AnalysisServer._handleServerResponse (package:dartdev/src/commands/analyze_impl.dart:112:35)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#9      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#10     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#11     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#12     _LineSplitterSink.close (dart:convert/line_splitter.dart:136:13)
#13     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
#14     _RootZone.runGuarded (dart:async/zone.dart:1372:10)
#15     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#16     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#17     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#18     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
#19     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#20     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#21     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
#22     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#23     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
#24     _RootZone.runGuarded (dart:async/zone.dart:1372:10)
#25     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#28     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
#29     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
#30     _StreamController.close (dart:async/stream_controller.dart:664:5)
#31     _Socket._onData (dart:io-patch/socket_patch.dart:1976:21)
#32     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#35     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#36     _StreamController._add (dart:async/stream_controller.dart:682:7)
#37     _StreamController.add (dart:async/stream_controller.dart:624:5)
#38     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1512:35)
#39     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1010:18)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

To reproduce.

Enable the following lints in `analyzer/analysis_options.yaml`:

```
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_redundant_argument_values
    - avoid_return_types_on_setters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    - await_only_futures
    - curly_braces_in_flow_control_structures
    - diagnostic_describe_all_properties
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_int_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_spread_collections
    - slash_for_doc_comments
    - sort_child_properties_last
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_overrides
    - unnecessary_this
    - use_rethrow_when_possible
```

then run `dart fix`:

```
[~/src/repos/dart/sdk/pkg/analyzer] $ dart ../dartdev/bin/dartdev.dart fix
```

/cc @bwilkerson

**Comment by pq** [comment]
Adding a catch and printing the full line provides some more context:

```
{"event":"analysis.errors","params":{"file":"/Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/test/src/diagnostics/not_initialized_non_nullable_instance_field_test.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file":"/Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/test/src/diagnostics/not_initialized_non_nullable_instance_field_test.dart","offset":2815,"length":27,"startLine":161,"startColumn":3},"message":"Name non-constant identifiers using lowerCamelCase.","code":"non_constant_identifier_names","url":"https://dart-lang.github.io/linter/lints/non_constant_identifier_names.html","hasFix":true},{"severity":"INFO","type":"LINT","location":{"file":"/Users/pquitslund/src/repos/dart/sdk/pkg/analyzer/test/src/diagnostics/not_initialized_non_nullable_instance_field_test.dart","offset":3578,"length":17,"startLine":211,"startColumn":3},"message":"Name non-constant identifiers using lowerCamelCase.","code":"non_constant_identifier_names","ur
```

It looks like server is not done sending error results back when we kill it's process.

The open question is why we're calling process kill and not sending server a shutdown request:

https://github.com/dart-lang/sdk/blob/dbff41c62ccf0182a411d5cad5b4382779a2984b/pkg/dartdev/lib/src/commands/analyze_impl.dart#L183

/fyi @devoncarew

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/166120
