### ISSUE TITLE
Exception while getting bulk fixes: Bad state: Not in a context root

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#43694]
```
[~/src/repos/surveyor] (master) $  dart ../dart/sdk/pkg/dartdev/bin/dartdev.dart fix

*** The `fix` command is provisional and subject to change or removal in future releases. ***

Computing fixes in surveyor...          
Error from the analysis server: Exception while getting bulk fixes: Bad state: Not in a context root: /Users/pq/src/repos/surveyor/test/data/route_app/lib/main.dart
#0      DartChangeWorkspace.getSession (package:analysis_server/src/services/correction/change_workspace.dart:31:5)
#1      BulkFixProcessor.fixErrorsInLibraries (package:analysis_server/src/services/correction/bulk_fix_processor.dart:346:31)
#2      EditDomainHandler.bulkFixes (package:analysis_server/src/edit/edit_domain.dart:116:43)
#3      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:397:9)
#4      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:239:38)
#5      _rootRun (dart:async/zone.dart:1190:13)
#6      _CustomZone.run (dart:async/zone.dart:1093:19)
#7      _runZoned (dart:async/zone.dart:1630:10)
#8      runZonedGuarded (dart:async/zone.dart:1618:12)
#9      AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:235:5)
#10     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163:14)
#11     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:103:26)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#17     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#18     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#19     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#20     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#21     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#22     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#23     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#24     _rootRunUnary (dart:async/zone.dart:1198:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#32     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#33     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#34     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#35     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#37     _rootRunUnary (dart:async/zone.dart:1198:47)
#38     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#43     _StreamController._add (dart:async/stream_controller.dart:682:7)
#44     _StreamController.add (dart:async/stream_controller.dart:624:5)
#45     _Socket._onData (dart:io-patch/socket_patch.dart:1969:41)
#46     _rootRunUnary (dart:async/zone.dart:1206:13)
#47     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#51     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#52     _StreamController._add (dart:async/stream_controller.dart:682:7)
#53     _StreamController.add (dart:async/stream_controller.dart:624:5)
#54     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1505:33)
#55     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1017:14)
#56     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#57     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#58     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


#0      DartChangeWorkspace.getSession (package:analysis_server/src/services/correction/change_workspace.dart:31:5)
#1      BulkFixProcessor.fixErrorsInLibraries (package:analysis_server/src/services/correction/bulk_fix_processor.dart:346:31)
#2      EditDomainHandler.bulkFixes (package:analysis_server/src/edit/edit_domain.dart:116:43)
#3      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:397:9)
#4      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:239:38)
#5      _rootRun (dart:async/zone.dart:1190:13)
#6      _CustomZone.run (dart:async/zone.dart:1093:19)
#7      _runZoned (dart:async/zone.dart:1630:10)
#8      runZonedGuarded (dart:async/zone.dart:1618:12)
#9      AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:235:5)
#10     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163:14)
#11     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:103:26)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#17     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#18     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#19     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#20     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#21     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#22     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#23     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#24     _rootRunUnary (dart:async/zone.dart:1198:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#32     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#33     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#34     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#35     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#37     _rootRunUnary (dart:async/zone.dart:1198:47)
#38     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#43     _StreamController._add (dart:async/stream_controller.dart:682:7)
#44     _StreamController.add (dart:async/stream_controller.dart:624:5)
#45     _Socket._onData (dart:io-patch/socket_patch.dart:1969:41)
#46     _rootRunUnary (dart:async/zone.dart:1206:13)
#47     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#51     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#52     _StreamController._add (dart:async/stream_controller.dart:682:7)
#53     _StreamController.add (dart:async/stream_controller.dart:624:5)
#54     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1505:33)
#55     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1017:14)
#56     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#57     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#58     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

/fyi @bwilkerson

**Comment by bwilkerson** [comment]
I would guess that that's because the `test/data` directory is excluded from analysis.

The better way for `EditDomainHandler.bulkFixes` to work would probably be to get the context associated with the root directory and ask the context for `contextRoot.analyzedFiles`. This will return the files that are not excluded. (I'm assuming that we shouldn't fix files that are excluded from analysis.)
