### ISSUE TITLE
VM crash: The getter 'topologicalIndex' was called on null

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#43796]
Getting the error below fairly frequently while coding my Flutter app in debug mode and hot reloading.  When the error happens, the VM terminates.

```
Unhandled exception:
NoSuchMethodError: The getter 'topologicalIndex' was called on null.
Receiver: null
Tried calling: topologicalIndex
#0      _intervalListContains (package:kernel/class_hierarchy.dart:1622:39)
#1      _ClassInfo.isSubclassOf (package:kernel/class_hierarchy.dart:1621:12)
#2      ClosedWorldClassHierarchy.isSubclassOf (package:kernel/class_hierarchy.dart:536:30)
#3      WidgetCache.checkSingleWidgetTypeModified (package:front_end/widget_cache.dart:129:24)
#4      FrontendCompiler._updateWidgetCache (package:frontend_server/frontend_server.dart:1161:22)
#5      FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:918:5)
<asynchronous suspension>
#6      _FlutterFrontendCompiler.recompileDelta (package:flutter_frontend_server/server.dart:48:22)
#7      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1311:20)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#11     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#12     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#13     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#14     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#15     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#16     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#17     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#25     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#26     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#27     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#28     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#29     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#32     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#33     _StreamController._add (dart:async/stream_controller.dart:682:7)
#34     _StreamController.add (dart:async/stream_controller.dart:624:5)
#35     _Socket._onData (dart:io-patch/socket_patch.dart:1969:41)
#36     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#39     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#40     _StreamController._add (dart:async/stream_controller.dart:682:7)
#41     _StreamController.add (dart:async/stream_controller.dart:624:5)
#42     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1505:33)
#43     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1017:14)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
```

## Version info

```
[✓] Flutter (Channel master, 1.23.0-14.0.pre.93, on Mac OS X 10.15.3 19D76 x86_64, locale en-US)
    • Flutter version 1.23.0-14.0.pre.93 at /Users/tvolkert/project/flutter/flutter
    • Framework revision 24abe59f38 (5 days ago), 2020-10-09 22:07:05 +0200
    • Engine revision 36769af310
    • Dart version 2.11.0 (build 2.11.0-203.0.dev)
```

/cc @mraleph can you help route this?

**Comment by tvolkert** [comment]
Hmm.. actually the VM may not terminate, but the IDE's connection to it does.

**Comment by mraleph** [comment]
Duplicate of #43760
