### ISSUE TITLE
HttpException: Invalid response, unexpected 10 in reason phrase

### ISSUE THREAD

**Issue by talhabalaj** [dart-lang/sdk#43916]
I'm having an issue while making an HTTP request to my router using dart. I have used http module as well as the dio both throw the same error.

I already have a python module for doing the same thing and it works fine. It seems like an issue in dart SDK as every HTTP request library I tried, throw the same error. An interesting thing I found is that this is not the case with the router's login route, instead, with all the other routes (/goform/getQos, etc).

If you have any idea how to fix this do lemme know. Here's some code.
```non-lang
Unhandled exception:
DioError [DioErrorType.DEFAULT]: HttpException: Invalid response, unexpected 10 in reason phrase, uri = http://192.168.0.1/goform/getWifi
#0      DioMixin._dispatchRequest (package:dio/src/dio.dart:966:7)
<asynchronous suspension>
#1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
#2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1121:22)
#3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
#4      new Future.<anonymous closure> (dart:async/future.dart:175:37)
#5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

This tracker is for issues related to:
* Dart core libraries ("dart:async", "dart:io", etc.)

Dart SDK version: 2.10.2 (stable) (Tue Oct 13 15:50:27 2020 +0200) on "windows_x64"

**Comment by vsmenon** [comment]
Do you have a repro using a `dart:io` directly?  If not, you may want to file this on the `dio` package.

**Comment by talhabalaj** [comment]
> Do you have a repro using a `dart:io` directly?  If not, you may want to file this on the `dio` package.

With due respect sir, The error is not a problem with any http client on pub.dev. I strongly think that it's with http parser of dart that throw this error. My guess is it's somewhere in dart:io. I can be wrong!

**Comment by talhabalaj** [comment]
I tried using `dart:io` to show that's no the fault of any library. 
```dart
    final client = HttpClient();
    final request = await client.getUrl(Uri.parse(
        'http://${this._ipAddress}/goform/getQos?modules=onlineList'));
    print('cookie: ${this._cookie}');
     request.cookies.add(Cookie(cookieName, cookieValue));
    final response = await request.close();
    response.transform(utf8.decoder).listen((content) {
      print(content);
    });
```

**Comment by mraleph** [comment]
Your server seems to send malformed response: finishing Status-Line with LF rather than CRLF as described in the HTTP/1.1 spec.

FWIW HTTP/1.1 recommends to be tolerant and accept just LF as a line ending where CRLF is expected and there is no ambiguity - and we don't seem to be tolerant. 

But in any case I'd start by fixing your server @talhabalaj to be compliant.

**Comment by talhabalaj** [comment]
> Your server seems to send malformed response: finishing Status-Line with LF rather than CRLF as described in the HTTP/1.1 spec.
> 
> FWIW HTTP/1.1 recommends to be tolerant and accept just LF as a line ending where CRLF is expected and there is no ambiguity - and we don't seem to be tolerant.
> 
> But in any case I'd start by fixing your server @talhabalaj to be compliant.

I understand that but this isn't my server. This is just a WiFi router I have, I can't fix it. Is there any other way to resolve this issue? Like an alternative to the dart's HTTP parser?

**Comment by ermiry** [comment]
Indeed i was able to confirm the issue, it is related to the http response header format, flutter expects \r\n at the end of each line like this:
```
res->header = c_string_create (
	"HTTP/1.1 %d %s\r\nServer: Cerver/%s\r\nContent-Type: application/json\r\nContent-Length: %ld\n\n", 
	res->status, http_status_str (res->status),
	CERVER_VERSION,
	res->data_len
);
```

However, i can say that this is a recent change, because in older versions, you can get away by just using \n at the end of the lines. Currently using:

![image](https://user-images.githubusercontent.com/38005609/97786453-4fdbee80-1b71-11eb-90fd-ad7f9d5df28e.png)

With:
http: ^0.12.2
http_parser: ^3.1.4

My solution was to actually modify my custom server source code to return responses using the proper header format. Probably another solution is to downgrade flutter itself as i couldn't find any recent changes in http or http_parser Github repos relating to this issue.

**Comment by mraleph** [comment]
> However, i can say that this is a recent change, because in older versions, you can get away by just using \n at the end of the lines. Currently using:

I don't think this is a recent change. The code in SDK that throws this error have been there for 8 years or more. You can blame these lines: https://github.com/dart-lang/sdk/blob/master/sdk/lib/_http/http_parser.dart#L607-L617

**Comment by NiClassic** [comment]
I am facing a similar issue with connecting my Flutter App to a Express JS API. 
The code calling the API is: 
```dart
Map<String, String> headers = {
  "Content-type": "application/json",
  "Authorization": api_key};
final response = await http.get("http://x.xx.xxx.xx/employees", headers: headers);
print(response);
```

And the error is:
```
E/flutter (31095): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid response, unexpected 10 in reason phrase
E/flutter (31095): #0      IOClient.send (package:http/src/io_client.dart:62:7)
E/flutter (31095): <asynchronous suspension>
E/flutter (31095): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:91:38)
E/flutter (31095): #2      BaseClient.get (package:http/src/base_client.dart:27:7)
E/flutter (31095): #3      get.<anonymous closure> (package:http/http.dart:46:36)
E/flutter (31095): #4      _withClient (package:http/http.dart:166:20)
E/flutter (31095): #5      get (package:http/http.dart:46:5)
E/flutter (31095): #6      SignInForm.build.<anonymous closure>.<anonymous closure> (package:project/src/presentation/sign_in/widgets/sign_in_form.dart:132:44)
E/flutter (31095): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (31095): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (31095): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (31095): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (31095): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (31095): #12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter (31095): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (31095): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter (31095): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (31095): #16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (31095): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (31095): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (31095): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (31095): #20     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (31095): #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (31095): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (31095): #23     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (31095): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```

With an API-Tester, I can confirm that the endpoint returns some JSON data.

I am confused about the error. It seems to happen while parsing the response from the server, as it says "Invalid response". However when I look into the server console, no http request from the app has reached the server. how does one fit with the other? Why does the app throws a response parse error when according to my understanding no response could have been received?

**Comment by 1232209** [comment]
> > Your server seems to send malformed response: finishing Status-Line with LF rather than CRLF as described in the HTTP/1.1 spec.
> > FWIW HTTP/1.1 recommends to be tolerant and accept just LF as a line ending where CRLF is expected and there is no ambiguity - and we don't seem to be tolerant.
> > But in any case I'd start by fixing your server @talhabalaj to be compliant.
> 
> I understand that but this isn't my server. This is just a WiFi router I have, I can't fix it. Is there any other way to resolve this issue? Like an alternative to the dart's HTTP parser?

I also want to know

**Comment by talhabalaj** [comment]
> > > Your server seems to send malformed response: finishing Status-Line with LF rather than CRLF as described in the HTTP/1.1 spec.
> > > FWIW HTTP/1.1 recommends to be tolerant and accept just LF as a line ending where CRLF is expected and there is no ambiguity - and we don't seem to be tolerant.
> > > But in any case I'd start by fixing your server @talhabalaj to be compliant.
> > 
> > I understand that but this isn't my server. This is just a WiFi router I have, I can't fix it. Is there any other way to resolve this issue? Like an alternative to the dart's HTTP parser?
> 
> I also want to know

I'm thinking to creating a `native_http` that uses libraries already developed for Android and iOS which doesn't have this issue. 

I think it would be better than writing a http parser

**Comment by 1232209** [comment]
> > > > Your server seems to send malformed response: finishing Status-Line with LF rather than CRLF as described in the HTTP/1.1 spec.
> > > > FWIW HTTP/1.1 recommends to be tolerant and accept just LF as a line ending where CRLF is expected and there is no ambiguity - and we don't seem to be tolerant.
> > > > But in any case I'd start by fixing your server @talhabalaj to be compliant.
> > > 
> > > 
> > > I understand that but this isn't my server. This is just a WiFi router I have, I can't fix it. Is there any other way to resolve this issue? Like an alternative to the dart's HTTP parser?
> > 
> > 
> > I also want to know
> 
> I'm thinking to creating a `native_http` that uses libraries already developed for Android and iOS which doesn't have this issue.
> 
> I think it would be better than writing a http parser

which libaray?

**Comment by talhabalaj** [comment]
> > > > > Your server seems to send malformed response: finishing Status-Line with LF rather than CRLF as described in the HTTP/1.1 spec.
> > > > > FWIW HTTP/1.1 recommends to be tolerant and accept just LF as a line ending where CRLF is expected and there is no ambiguity - and we don't seem to be tolerant.
> > > > > But in any case I'd start by fixing your server @talhabalaj to be compliant.
> > > > 
> > > > 
> > > > I understand that but this isn't my server. This is just a WiFi router I have, I can't fix it. Is there any other way to resolve this issue? Like an alternative to the dart's HTTP parser?
> > > 
> > > 
> > > I also want to know
> > 
> > I'm thinking to creating a `native_http` that uses libraries already developed for Android and iOS which doesn't have this issue.
> > 
> > I think it would be better than writing a http parser
> 
> which libaray?
> 

Currently I don't know of any library that doesn't use dart's http parser

**Comment by 1232209** [comment]
> Indeed i was able to confirm the issue, it is related to the http response header format, flutter expects \r\n at the end of each line like this:
> 
> ```
> res->header = c_string_create (
> 	"HTTP/1.1 %d %s\r\nServer: Cerver/%s\r\nContent-Type: application/json\r\nContent-Length: %ld\n\n", 
> 	res->status, http_status_str (res->status),
> 	CERVER_VERSION,
> 	res->data_len
> );
> ```
> 
> However, i can say that this is a recent change, because in older versions, you can get away by just using \n at the end of the lines. Currently using:
> 
> ![image](https://user-images.githubusercontent.com/38005609/97786453-4fdbee80-1b71-11eb-90fd-ad7f9d5df28e.png)
> 
> With:
> http: ^0.12.2
> http_parser: ^3.1.4
> 
> My solution was to actually modify my custom server source code to return responses using the proper header format. Probably another solution is to downgrade flutter itself as i couldn't find any recent changes in http or http_parser Github repos relating to this issue.

how to modify the server?

**Comment by jeeinn** [comment]
I also used to connect to the WiFi Router

It took me 2 hours to find one that worked! 

https://pub.flutter-io.cn/packages/sync_http

**Comment by mraleph** [comment]
@aam this might be the next high profile dart:io issue to tackle (/cc @a-siva)

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/192120 with proposed fix

**Comment by gutisalex** [comment]
When will this be changed (relaxed) because I need that now... I already written own channel for ios and android but now I want to deply a windows desktop version which means I would have to write another channel in c++!

I am on http_parser: 4.0.0 and there it is still throwing this error

**Comment by aam** [comment]
@gutisalex the abovementioned fix landed in dart sdk should be available in dart version 2.13.0-155.0.dev and higher.
