### ISSUE TITLE
Exception when using CiderCompletionComputer

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#43925]
See the following exception sometimes during completions

```NoSuchMethodError: The method 'getField' was called on null.
Receiver: null
Tried calling: getField()
#0      ResolverVisitor.visitConstructorFieldInitializer (package:analyzer/src/generated/resolver.dart:1204)
#1      ConstructorFieldInitializerImpl.accept (package:analyzer/src/dart/ast/ast.dart:2629)
#2      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7553)
#3      ScopedVisitor.visitConstructorDeclaration (package:analyzer/src/generated/resolver.dart:2570)
#4      ResolverVisitor.visitConstructorDeclaration (package:analyzer/src/generated/resolver.dart:1161)
#5      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2544)
#6      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/micro/library_analyzer.dart:722)
#7      LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/library_analyzer.dart:148)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377)
#9      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/micro/library_analyzer.dart:147)
#10     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:137)
#11     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/micro/library_analyzer.dart:146)
#12     FileResolver.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:376)
#13     _rootRun (dart:async/zone.dart:1190)
#14     _CustomZone.run (dart:async/zone.dart:1093)
#15     _runZoned (dart:async/zone.dart:1630)
#16     runZoned (dart:async/zone.dart:1550)
#17     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42)
#18     FileResolver.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:375)
#19     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:137)
#20     FileResolver.resolve.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:374)
#21     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32)
#22     FileResolver.resolve.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:359)
#23     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32)
#24     FileResolver.resolve (package:analyzer/src/dart/micro/resolve_file.dart:330)
#25     CiderCompletionComputer.compute.<anonymous closure>.<anonymous closure> (package:analysis_server/src/cider/completion.dart:62)
#26     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:137)
#27     CiderCompletionComputer.compute.<anonymous closure> (package:analysis_server/src/cider/completion.dart:61)
#28     CiderCompletionComputer.compute.<anonymous closure> (package:analysis_server/src/cider/completion.dart:60)```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/169480
