### ISSUE TITLE
Migration throws exception with unexpected sdk constraint

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#43989]
I just rebuilt with the latest version of the SDK (2.12.0-edge.79ae138306e2a4ebc7de1fbe8ce21bfdaa616f38) and ran `dart migrate` on an old personal package of mine. It died with an exception. The stack trace is below.

It looks like it was probably trying to read the SDK constraints from the `pubspec.yaml` file, which have the form:
```yaml
environment:
  sdk: '<3.0.0'
```

When I updated the constraint to `'>=2.9.0'` the migration worked as expected.

Stack trace:

```
NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(Instance of 'Version')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      NonNullableFix._processPubspec (package:nnbd_migration/src/front_end/non_nullable_fix.dart:415:37)
#2      NonNullableFix.processPackage (package:nnbd_migration/src/front_end/non_nullable_fix.dart:152:19)
#3      _FixCodeProcessor.runFirstPhase (package:nnbd_migration/migration_cli.dart:1131:11)
#4      MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:743:52)
#5      MigrateCommand.run (package:nnbd_migration/migration_cli.dart:266:72)
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#7      DartdevRunner.runCommand (package:dartdev/dartdev.dart:280:36)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:223:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     runDartdev (package:dartdev/dartdev.dart:108:27)
#12     main (file:///Users/brianwilkerson/src/dart/sdk/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by franklinyow** [comment]
@stereotype441 Please reassign if you're not the right owner.

**Comment by leafpetersen** [comment]
@srawlins @stereotype441 has this been fixed?

**Comment by franklinyow** [comment]
@srawlins @stereotype441 @leafpetersen 
What's the status on this?

**Comment by srawlins** [comment]
Sorry I'll look into this right now.

**Comment by srawlins** [comment]
Note that `pub get` fails with this constraint of `<3.0.0`:

```
pubspec.yaml has no lower-bound SDK constraint.                                                                                                                     
You should edit pubspec.yaml to contain an SDK constraint:                                                                                                          
                                                                                                                                                                    
environment:                                                             
  sdk: '>=2.10.0 <3.0.0'                                                 
                                                                         
See https://dart.dev/go/sdk-constraint                                   
Running "flutter pub get" in dart-get_it_mixin...                       
pub get failed (65; See https://dart.dev/go/sdk-constraint)
```

**Comment by srawlins** [comment]
`dart migrate` still crashes on this, but simple fix. I'll mail today.
