### ISSUE TITLE
Exception in the migration tool

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#44071]
When I run the migration tool on pkg/test_runner in the SDK, it throws an exception. The UI loads with `--ignore-exceptions`.

```shell
$ tools/sdks/dart-sdk/bin/dart --version
Dart SDK version: 2.12.0-0.0.dev (dev) (Thu Oct 29 12:24:51 2020 -0700) on "macos_x64"

$ tools/sdks/dart-sdk/bin/dart migrate pkg/test_runner
Migrating /Users/user/src/sdk/pkg/test_runner

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[                                                                                                                                                                                                 ]Warning: Could not find the package configuration file.
  /Users/user/src/sdk/pkg/test_runner/.dart_tool/package_config.json
  

  Be sure to run `pub get` before examining the results of the migration.

[------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\]No analysis issues found.

Generating migration suggestions...
[--------------------------------------------------------------------------\                                                                                                                      ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

type '_IfContext<PromotableElement, DecoratedType>' is not a subtype of type '_FunctionExpressionContext<PromotableElement, DecoratedType>' in type cast

#0      _FlowAnalysisImpl.functionExpression_end (package:_fe_analyzer_shared/src/flow_analysis/flow_analysis.dart:2961:29)
#1      EdgeBuilder.visitFunctionExpression (package:nnbd_migration/src/edge_builder.dart:907:23)
#2      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4969:49)
#3      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2134:22)
#4      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2248:20)
#5      EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2842:7)
#6      EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1244:24)
#7      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7120:49)
#8      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2134:22)
#9      EdgeBuilder._checkExpressionNotNull (package:nnbd_migration/src/edge_builder.dart:1920:20)
#10     EdgeBuilder._handleTarget (package:nnbd_migration/src/edge_builder.dart:2949:14)
#11     EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1227:22)
#12     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7120:49)
#13     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2134:22)
#14     EdgeBuilder.visitExpressionStatement (package:nnbd_migration/src/edge_builder.dart:791:25)
#15     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3650:49)
#16     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2134:22)
#17     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1288:9)
#18     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#19     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#20     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1069:49)
#21     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2134:22)
#22     EdgeBuilder.visitIfStatement.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:1006:27)
#23     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#24     EdgeBuilder.visitIfStatement (package:nnbd_migration/src/edge_builder.dart:1005:30)
#25     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5646:49)
#26     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2134:22)
#27     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1288:9)
#28     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#29     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#30     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1069:49)
#31     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2134:22)
#32     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1288:9)
#33     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:324:45)
#34     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:55)
#35     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1024:49)
#36     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2134:22)
#37     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2398:7)
#38     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1202:5)
#39     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6967:49)
#40     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2134:22)
#41     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2148:7)
#42     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:601:7)
#43     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:568:5)
#44     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1521:49)
#45     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2134:22)
#46     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1288:9)
#47     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:51)
#48     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#49     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#50     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#51     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2112:49)
#52     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:222:12)
#53     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:165:15)
#54     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1160:19)
#55     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1102:30)
<asynchronous suspension>
#56     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1158:11)
#57     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:764:48)
<asynchronous suspension>
#58     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:266:72)
#59     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#60     DartdevRunner.runCommand (package:dartdev/dartdev.dart:280:36)
#61     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#62     new Future.sync (dart:async/future.dart:223:31)
#63     CommandRunner.run (package:args/command_runner.dart:112:14)
#64     runDartdev (package:dartdev/dartdev.dart:108:27)
#65     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#66     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:32)
#67     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by devoncarew** [comment]
cc @stereotype441; note that the `--ignore-exceptions` workaround does work here. This was from `2.12.0-0.0.dev`.

**Comment by stereotype441** [comment]
I can still reproduce this with the latest code as of 5af2d78e75a45042f97b50fa01beb59af1dacbae.  Investigating now.

**Comment by stereotype441** [comment]
The problem turned out to be that the code being migrated contained a for-each loop where the loop variable was not local.  This infrequently-used corner of the language wasn't properly handled by the migration tool.  Working on a fix here: https://dart-review.googlesource.com/c/sdk/+/174565
