### ISSUE TITLE
scavenger_abort_2_test runtime/vm/object.cc: 2575: error: expected: vtable() == builtin_vtables_[cid]

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#44134]
Test added in https://github.com/dart-lang/sdk/commit/711b625bca863741e46a31bce276856868fb19ba.

The tests
```
vm/dart_2/scavenger_abort_2_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-asan-linux-release-x64
dartk-reload-rollback-linux-debug-x64
dartk-reload-rollback-linux-release-x64
```

https://dart-ci.appspot.com/log/vm-kernel-reload-rollback-linux-debug-x64/dartk-reload-rollback-linux-debug-x64/9074/vm/dart_2/scavenger_abort_2_test

```
../../runtime/vm/object.cc: 2575: error: expected: vtable() == builtin_vtables_[cid]
version=2.12.0-edge.93d17845946478866415376903b5f340e3d0737c (be) (Mon Nov 9 23:03:24 2020 +0000) on "linux_x64"
pid=7750, thread=7757, isolate_group=main(0x55ff37501600), isolate=main(0x55ff3750e900)
isolate_instructions=55ff34642b20, vm_instructions=55ff34642b20
  pc 0x000055ff34a1867c fp 0x00007f56fb2fdcd0 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x000055ff34642c52 fp 0x00007f56fb2fddb0 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x000055ff34940952 fp 0x00007f56fb2fddf0 dart::Object::CheckHandle() const+0x1a2
  pc 0x000055ff348ec4a5 fp 0x00007f56fb2fde70 dart::IsolateReloadContext::CheckpointClasses()+0x585
  pc 0x000055ff348d968b fp 0x00007f56fb2fdee0 dart::IsolateGroup::ForEachIsolate(std::__2::function<void (dart::Isolate*)>, bool)+0x1db
  pc 0x000055ff348e4c6d fp 0x00007f56fb2fe1a0 dart::IsolateGroupReloadContext::Reload(bool, char const*, char const*, unsigned char const*, long)+0x82d
  pc 0x000055ff348d92da fp 0x00007f56fb2fe240 dart::IsolateGroup::ReloadSources(dart::JSONStream*, bool, char const*, char const*, bool)+0x1da
  pc 0x000055ff34a8c592 fp 0x00007f56fb2fe410 dart::DRT_StackOverflow(dart::NativeArguments)+0x482
  pc 0x00007f57020823e2 fp 0x00007f56fb2fe458 Unknown symbol
  pc 0x00007f56fca2bb38 fp 0x00007f56fb2fe480 Unknown symbol
  pc 0x00007f56fca2b662 fp 0x00007f56fb2fe4c8 Unknown symbol
  pc 0x00007f56fca2aa9a fp 0x00007f56fb2fe510 Unknown symbol
  pc 0x00007f56fca29cb7 fp 0x00007f56fb2fe598 Unknown symbol
  pc 0x00007f56fca20ee7 fp 0x00007f56fb2fe5f0 Unknown symbol
  pc 0x00007f56fca28f31 fp 0x00007f56fb2fe630 Unknown symbol
  pc 0x00007f56fca28b23 fp 0x00007f56fb2fe668 Unknown symbol
  pc 0x00007f56fca27b8a fp 0x00007f56fb2fe6c8 Unknown symbol
  pc 0x00007f56fca27e07 fp 0x00007f56fb2fe708 Unknown symbol
  pc 0x00007f56fca27b8a fp 0x00007f56fb2fe768 Unknown symbol
  pc 0x00007f56fca275c3 fp 0x00007f56fb2fe7a0 Unknown symbol
  pc 0x00007f570208286d fp 0x00007f56fb2fe818 Unknown symbol
  pc 0x000055ff34894af3 fp 0x00007f56fb2fe8b0 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x113
  pc 0x000055ff348946e5 fp 0x00007f56fb2fe920 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x135
  pc 0x000055ff34898483 fp 0x00007f56fb2fe990 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)+0x233
  pc 0x000055ff348d580a fp 0x00007f56fb2feb80 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x5da
  pc 0x000055ff3491be31 fp 0x00007f56fb2fec10 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x221
  pc 0x000055ff3491cd59 fp 0x00007f56fb2fec90 dart::MessageHandler::TaskCallback()+0x359
  pc 0x000055ff34ad78cb fp 0x00007f56fb2fed30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x1cb
  pc 0x000055ff34ad8309 fp 0x00007f56fb2fed80 dart::ThreadPool::Worker::Main(unsigned long)+0x179
  pc 0x000055ff34a114a9 fp 0x00007f56fb2feed0 out/DebugX64/dart+0x1f064a9
```

**Comment by alexmarkov** [comment]
On `vm-kernel-asan-linux-release-x64` this test is failing with `Out of Memory` and reporting a leak:
```
/==================================================================================\
| vm/dart_2/scavenger_abort_2_test is new and failed (RuntimeError, expected Pass) |
\==================================================================================/

--- Command "vm" (took 06.000066s):
DART_CONFIGURATION=ReleaseASANX64 out/ReleaseASANX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart_2/scavenger_abort_2_test.dart

exit code:
255

stdout:
+ out/ReleaseASANX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --new_gen_semi_max_size=4 --old_gen_heap_size=15 --verbose_gc --verify_store_buffer /b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart_2/scavenger_abort_2_test.dart --testee
Command stdout:
PHASE1
PHASE2

Command stderr:
[              |                      |     |       |      | new gen     | new gen     | new gen | old gen       | old gen       | old gen     | sweep | safe- | roots/| stbuf/| tospc/| weaks/|               ]
[ GC isolate   | space (reason)       | GC# | start | time | used (kB)   | capacity kB | external| used (kB)     | capacity (kB) | external kB | thread| point |marking| reset | sweep |swplrge| data          ]
[              |                      |     |  (s)  | (ms) |before| after|before| after| b4 |aftr| before| after | before| after |before| after| (ms)  | (ms)  | (ms)  | (ms)  | (ms)  | (ms)  |               ]
[ vm-service   ,  MarkSweep( finalize),    1,   0.17,  29.5,   512,   512,  2048,  2048,   0,   0,   3469,   3070,   4040,   3784,     0,     0,   0.00,   0.00,  28.82,   0.02,   0.56,   0.05, 83, 0, 2, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ vm-service   ,   Scavenge(     full),    2,   0.49,  21.2,   512,   512,  2048,  2048,   0,   0,   4335,   4335,   4808,   4808,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 489, 0, 0, 0, ]
[              |                      |     |       |      | new gen     | new gen     | new gen | old gen       | old gen       | old gen     | sweep | safe- | roots/| stbuf/| tospc/| weaks/|               ]
[ GC isolate   | space (reason)       | GC# | start | time | used (kB)   | capacity kB | external| used (kB)     | capacity (kB) | external kB | thread| point |marking| reset | sweep |swplrge| data          ]
[              |                      |     |  (s)  | (ms) |before| after|before| after| b4 |aftr| before| after | before| after |before| after| (ms)  | (ms)  | (ms)  | (ms)  | (ms)  | (ms)  |               ]
[ main         ,  MarkSweep( finalize),    1,   0.10,  16.5,   512,   512,  2048,  2048,   0,   0,   3492,   3099,   4040,   3784,     0,     0,   0.00,   0.00,  14.81,   0.00,   0.55,   1.11, 78, 0, 2, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[              |                      |     |       |      | new gen     | new gen     | new gen | old gen       | old gen       | old gen     | sweep | safe- | roots/| stbuf/| tospc/| weaks/|               ]
[ GC isolate   | space (reason)       | GC# | start | time | used (kB)   | capacity kB | external| used (kB)     | capacity (kB) | external kB | thread| point |marking| reset | sweep |swplrge| data          ]
[              |                      |     |  (s)  | (ms) |before| after|before| after| b4 |aftr| before| after | before| after |before| after| (ms)  | (ms)  | (ms)  | (ms)  | (ms)  | (ms)  |               ]
[ kernel-servic,   Scavenge(new space),    1,   0.69, 117.4,  2048,  1536,  2048,  2048, 6290, 6271,  33858,  33858,  34812,  34812,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 18, 0, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ kernel-servic,   Scavenge(new space),    2,   0.82, 127.6,  2048,  1024,  2048,  4096, 6271,   0,  33858,  35320,  34812,  36948,     0,  6271,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 18, 0, 0, 0, ]
[ kernel-servic,  MarkSweep(promotion),    3,   0.86,  41.2,  1024,  1024,  4096,  4096,   0,   0,  35320,  31550,  36948,  36948,  6271,  6271,  -0.00,   0.00,  40.64,   0.00,   0.49,   0.04, 46, 0, 56, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ kernel-servic,   Scavenge(new space),    4,   1.04, 178.7,  4096,     0,  4096,  4096,   0,   0,  31550,  35370,  33492,  37076,  6271,  6271,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 6, 0, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ kernel-servic,   Scavenge(new space),    5,   1.20, 148.2,  4096,     0,  4096,  4096,   0,   0,  35370,  39290,  37076,  41044,  6271,  6271,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 284, 0, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ kernel-servic,   Scavenge(new space),    6,   1.40, 180.4,  4096,     0,  4096,  4096,  50,   0,  39306,  42728,  41556,  44184,  6271,  6274,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 3142, 0, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ kernel-servic,   Scavenge(new space),    7,   1.58, 172.8,  4096,     0,  4096,  4096,   0,   0,  42728,  46477,  44184,  48280,  6274,  6274,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 5347, 0, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ kernel-servic,   Scavenge(new space),    8,   1.79, 187.9,  4096,     0,  4096,  4096,   0,   0,  46478,  49573,  48792,  51352,  6274,  6274,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 5322, 0, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ kernel-servic,   Scavenge(new space),    9,   2.00, 197.0,  4096,     0,  4096,  4096,   0,   0,  49574,  51233,  51864,  52888,  6274,  6274,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 395, 0, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ kernel-servic,   Scavenge(new space),   10,   2.22, 197.2,  4096,  1536,  4096,  4096,   0,   0,  51243,  51243,  53400,  53400,  6274,  6274,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 1143, 0, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ kernel-servic,   Scavenge(new space),   11,   2.43, 191.3,  4096,  2048,  4096,  4096,   0,   0,  51258,  52071,  53400,  53912,  6274,  6274,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 2610, 0, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(new space),    2,   2.17,  13.3,  2048,  2048,  2048,  2048,   0,   0,   4221,   4221,   4808,   4808,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 292, 0, 0, 0, ]
[ main         ,  MarkSweep( finalize),    3,   2.18,   1.4,  2048,  2048,  2048,  2048,   0,   0,   4343,   3926,   4808,   4740,     0,     0,   0.00,   0.00,   1.26,   0.00,   0.10,   0.06, 33, 0, 12, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(new space),    4,   2.20,  18.8,  2048,   512,  2048,  4096,   0,   0,   3926,   5871,   5252,   6788,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 750, 0, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(new space),    5,   2.24,  17.0,  4096,     0,  4096,  4096,   0,   0,   5954,  10045,   7300,  10884,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 119, 0, 0, 0, ]
[ main         ,  MarkSweep(promotion),    6,   2.25,  13.2,     0,     0,  4096,  4096,   0,   0,  10045,  10025,  10884,  10884,     0,     0,   0.00,   0.00,  13.10,   0.00,   0.11,   0.03, 0, 0, 280, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(new space),    7,   2.29,  42.9,  4096,     0,  4096,  4096,   0,   0,  10025,  14120,  10884,  14980,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 1680, 0, 0, 0, ]
[ main         ,  MarkSweep(promotion),    8,   2.30,   8.4,     0,     0,  4096,  4096,   0,   0,  14120,  14120,  14980,  14980,     0,     0,   0.00,   0.00,   8.23,   0.00,   0.10,   0.03, 0, 1, 280, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(new space),    9,   2.36,  56.1,  4096,  4096,  4096,  4096,   0,   0,  14120,  14204,  14980,  14980,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 1680, 0, 0, 0, ]
[ main         ,  MarkSweep( finalize),   10,   2.37,   2.0,  4096,  4096,  4096,  4096,   0,   0,  14204,  14204,  14980,  14980,     0,     0,  -0.00,   0.00,   1.83,   0.00,   0.10,   0.03, 0, 12, 280, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(     full),   11,   2.42,  46.8,  4096,  4096,  4096,  4096,   0,   0,  14204,  14312,  14980,  14980,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 1683, 0, 0, 0, ]
[ main         ,  MarkSweep(     full),   12,   2.43,   9.9,  4096,  4096,  4096,  4096,   0,   0,  14312,  14312,  14980,  14980,     0,     0,  -0.00,   0.00,   9.80,   0.00,   0.10,   0.02, 0, 11, 280, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(low memory),   13,   2.48,  46.0,  4096,  4096,  4096,  4096,   0,   0,  14312,  14312,  14980,  14980,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 1637, 0, 0, 0, ]
[ main         , MarkCompact(low memory),   14,   2.51,  31.2,  4096,  4096,  4096,  4096,   0,   0,  14312,  14312,  14980,  14980,     0,     0,   0.00,   0.00,  15.72,   0.00,   0.09,  15.38, 100, 20, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(new space),   15,   2.57,  54.6,  4096,  4096,  4096,  4096,   0,   0,  14312,  14372,  14980,  14980,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 1682, 0, 0, 0, ]
[ main         ,  MarkSweep( finalize),   16,   2.59,  10.8,  4096,  4096,  4096,  4096,   0,   0,  14372,  14372,  14980,  14980,     0,     0,   0.00,   0.00,  10.66,   0.00,   0.10,   0.02, 0, 23, 280, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(     full),   17,   2.64,  49.3,  4096,  4096,  4096,  4096,   0,   0,  14372,  14372,  14980,  14980,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 1681, 0, 0, 0, ]
[ main         ,  MarkSweep(     full),   18,   2.67,  26.2,  4096,  4096,  4096,  4096,   0,   0,  14372,  14372,  14980,  14980,     0,     0,  -0.00,   0.00,  26.00,   0.00,   0.11,   0.03, 100, 28, 0, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(low memory),   19,   2.72,  46.3,  4096,  4096,  4096,  4096,   0,   0,  14372,  14372,  14980,  14980,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 1681, 0, 0, 0, ]
[ main         , MarkCompact(low memory),   20,   2.77,  51.0,  4096,  4096,  4096,  4096,   0,   0,  14372,  14372,  14980,  14980,     0,     0,   0.00,   0.00,  29.39,   0.00,   0.11,  21.45, 100, 33, 0, 0, ]
Exhausted heap space, trying to allocate 160 bytes.
Verifying remembered set before Scavenge... done.
Aborting scavenge
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(new space),   21,   2.86,  91.0,  4096,  4096,  4096,  4096,   0,   0,  14374,  14405,  14980,  14980,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 0, 0, 0, 0, ]
[ main         ,  MarkSweep( finalize),   22,   2.89,  14.2,  4096,  4096,  4096,  4096,   0,   0,  14405,   3923,  14980,  11908,     0,     0,   0.00,   0.00,   8.54,   0.00,   0.11,   5.58, 100, 31, 8, 0, ]
Verifying remembered set before Scavenge... done.
Verifying remembered set after Scavenge... done.
[ main         ,   Scavenge(new space),   23,   2.92,  28.3,  4096,     0,  4096,  4096,   0,   0,   3924,   3924,  12420,  12420,     0,     0,   0.00,   0.00,   0.00,   0.00,   0.00,   0.00, 3, 0, 0, 0, ]
Unhandled exception:
Out of Memory
#0      fill (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart_2/scavenger_abort_2_test.dart:210:19)
#1      makeOld (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart_2/scavenger_abort_2_test.dart:243:5)
#2      main (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart_2/scavenger_abort_2_test.dart:256:11)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:309:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

=================================================================
==28921==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8208 byte(s) in 1 object(s) allocated from:
    #0 0x557853258efd in operator new(unsigned long) ../recipe_cleanup/clangshYTOG/llvm_build_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/asan/asan_new_delete.cpp:99:3
    #1 0x557853c1ad21 in dart::BlockStack<1024>::PopEmptyBlock() ../../out/ReleaseASANX64/../../runtime/vm/heap/pointer_block.cc:137:10
    #2 0x557853b7e9ce in dart::Thread::ReleaseStoreBuffer() ../../out/ReleaseASANX64/../../runtime/vm/thread.cc:399:58
    #3 0x557853b8e7a5 in dart::ThreadRegistry::ReleaseStoreBuffers() ../../out/ReleaseASANX64/../../runtime/vm/thread_registry.cc:67:15
    #4 0x557853c033d1 in dart::GCMarker::Prologue() ../../out/ReleaseASANX64/../../runtime/vm/heap/marker.cc:314:19
    #5 0x557853c033d1 in dart::GCMarker::MarkObjects(dart::PageSpace*) ../../out/ReleaseASANX64/../../runtime/vm/heap/marker.cc:768:3
    #6 0x557853c149d1 in dart::PageSpace::CollectGarbageHelper(bool, bool, long, long) ../../out/ReleaseASANX64/../../runtime/vm/heap/pages.cc:1182:12
    #7 0x557853c14258 in dart::PageSpace::CollectGarbage(bool, bool) ../../out/ReleaseASANX64/../../runtime/vm/heap/pages.cc:1118:5
    #8 0x557853bf7b04 in dart::Heap::CollectOldSpaceGarbage(dart::Thread*, dart::Heap::GCType, dart::Heap::GCReason) ../../out/ReleaseASANX64/../../runtime/vm/heap/heap.cc:516:16
    #9 0x557853c0df31 in dart::PageSpace::EvaluateConcurrentMarking(dart::PageSpace::GrowthPolicy) ../../out/ReleaseASANX64/../../runtime/vm/heap/pages.cc:461:16
    #10 0x557853c0df31 in dart::PageSpace::TryAllocateInFreshPage(long, dart::FreeList*, dart::OldPage::PageType, dart::PageSpace::GrowthPolicy, bool) ../../out/ReleaseASANX64/../../runtime/vm/heap/pages.cc:475:3
    #11 0x557853bf58c4 in dart::PageSpace::TryAllocate(long, dart::OldPage::PageType, dart::PageSpace::GrowthPolicy) ../../out/ReleaseASANX64/../../runtime/vm/heap/pages.h:306:12
    #12 0x557853bf58c4 in dart::Heap::AllocateOld(long, dart::OldPage::PageType) ../../out/ReleaseASANX64/../../runtime/vm/heap/heap.cc:118:29
    #13 0x5578537f2179 in dart::Heap::Allocate(long, dart::Heap::Space) ../../out/ReleaseASANX64/../../runtime/vm/heap/heap.h
    #14 0x5578537f2179 in dart::Object::Allocate(long, long, dart::Heap::Space) ../../out/ReleaseASANX64/../../runtime/vm/object.cc:2601:25
    #15 0x557853941c23 in dart::Array::New(long, long, dart::Heap::Space) ../../out/ReleaseASANX64/../../runtime/vm/object.cc:23029:9
    #16 0x557853941c23 in dart::Array::New(long, dart::Heap::Space) ../../out/ReleaseASANX64/../../runtime/vm/object.cc:23001:21
    #17 0x557853941c23 in dart::ArrayPtr dart::HashTables::New<dart::HashSet<dart::UnorderedHashTable<dart::ClassFunctionsTraits, 0l> > >(long, dart::Heap::Space) ../../out/ReleaseASANX64/../../runtime/vm/hash_table.h:448:9
    #18 0x55785394175f in void dart::HashTables::EnsureLoadFactor<dart::HashSet<dart::UnorderedHashTable<dart::ClassFunctionsTraits, 0l> > >(double, dart::HashSet<dart::UnorderedHashTable<dart::ClassFunctionsTraits, 0l> > const&) ../../out/ReleaseASANX64/../../runtime/vm/hash_table.h:506:21
    #19 0x557853803477 in dart::HashSet<dart::UnorderedHashTable<dart::ClassFunctionsTraits, 0l> >::EnsureCapacity() const ../../out/ReleaseASANX64/../../runtime/vm/hash_table.h:708:5
    #20 0x557853803477 in dart::HashSet<dart::UnorderedHashTable<dart::ClassFunctionsTraits, 0l> >::Insert(dart::Object const&) ../../out/ReleaseASANX64/../../runtime/vm/hash_table.h:646:5
    #21 0x557853803477 in dart::Class::SetFunctions(dart::Array const&) const ../../out/ReleaseASANX64/../../runtime/vm/object.cc:2957:11
    #22 0x5578537cfeef in dart::kernel::KernelLoader::FinishClassLoading(dart::Class const&, dart::Library const&, dart::Class const&, long, dart::kernel::ClassIndex const&, dart::kernel::ClassHelper*) ../../out/ReleaseASANX64/../../runtime/vm/kernel_loader.cc:1747:9
    #23 0x5578537d0fe0 in dart::kernel::KernelLoader::FinishLoading(dart::Class const&) ../../out/ReleaseASANX64/../../runtime/vm/kernel_loader.cc:1791:17
    #24 0x5578535d103c in dart::ClassFinalizer::FinalizeClass(dart::Class const&) ../../out/ReleaseASANX64/../../runtime/vm/class_finalizer.cc:1117:5
    #25 0x5578535d4e92 in dart::ClassFinalizer::LoadClassMembers(dart::Class const&) ../../out/ReleaseASANX64/../../runtime/vm/class_finalizer.cc:1211:5
    #26 0x55785384639f in dart::Class::EnsureIsFinalized(dart::Thread*) const ../../out/ReleaseASANX64/../../runtime/vm/object.cc:4308:37
    #27 0x55785485fe77 in dart::kernel::TranslationHelper::LookupMethodByMember(dart::kernel::NameIndex, dart::String const&) ../../out/ReleaseASANX64/../../runtime/vm/compiler/frontend/kernel_translation_helper.cc:680:13
    #28 0x5578547e00e1 in dart::kernel::StreamingFlowGraphBuilder::BuildMethodInvocation(dart::TokenPosition*) ../../out/ReleaseASANX64/../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:2812:14
    #29 0x5578547ca232 in dart::kernel::StreamingFlowGraphBuilder::BuildExpression(dart::TokenPosition*) ../../out/ReleaseASANX64/../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:1212:14
    #30 0x5578547d133f in dart::kernel::StreamingFlowGraphBuilder::BuildExpressionStatement() ../../out/ReleaseASANX64/../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:3920:27
    #31 0x5578547d133f in dart::kernel::StreamingFlowGraphBuilder::BuildStatement() ../../out/ReleaseASANX64/../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:1310:14
    #32 0x5578547ede78 in dart::kernel::StreamingFlowGraphBuilder::BuildBlock() ../../out/ReleaseASANX64/../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:3936:23
    #33 0x5578547d12b7 in dart::kernel::StreamingFlowGraphBuilder::BuildStatement() ../../out/ReleaseASANX64/../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:1312:14
    #34 0x5578547d6203 in dart::kernel::StreamingFlowGraphBuilder::BuildFunctionBody(dart::Function const&, dart::LocalVariable*, bool) ../../out/ReleaseASANX64/../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:809:13
    #35 0x5578547d813f in dart::kernel::StreamingFlowGraphBuilder::BuildGraphOfFunction(bool) ../../out/ReleaseASANX64/../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:962:7
    #36 0x5578547d9244 in dart::kernel::StreamingFlowGraphBuilder::BuildGraph() ../../out/ReleaseASANX64/../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:1069:14
    #37 0x557854821d9c in dart::kernel::FlowGraphBuilder::BuildGraph() ../../out/ReleaseASANX64/../../runtime/vm/compiler/frontend/kernel_to_il.cc:751:39
    #38 0x557853bc779b in dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*>*, long, bool) ../../out/ReleaseASANX64/../../runtime/vm/compiler/jit/compiler.cc:139:30

SUMMARY: AddressSanitizer: 8208 byte(s) leaked in 1 allocation(s).

stderr:
Unhandled exception:
Expect.equals(expected: <255>, actual: <-6>, 'Should see runtime exception error code, not SEGV') fails.
#0      Expect._fail (package:expect/expect.dart:704:5)
#1      Expect.equals (package:expect/expect.dart:132:5)
#2      main (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart_2/scavenger_abort_2_test.dart:278:10)
<asynchronous suspension>

--- Re-run this test:
python tools/test.py -n dartk-asan-linux-release-x64 vm/dart_2/scavenger_abort_2_test
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8864045545036903648/+/steps/test_results/0/logs/new_test_failures__logs_/0
