### ISSUE TITLE
Crash when running `dart migrate` from `out/Release.../dart` instead of `out/Release.../dart-sdk/bin/dart`

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#44133]
Running `out\ReleaseX64\dart.exe migrate` from the dart repo root on Windows results in

```
Migrating c:\src\dart-repo1b\sdk

See https://dart.dev/go/null-safety-migration for a migration guide.

FileSystemException(path=C:\src\dart-repo1b\sdk\out\version; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:193:7)
#1      FolderBasedDartSdk.languageVersion (package:analyzer/src/dart/sdk/sdk.dart:399:12)
#2      FeatureSetProvider.build (package:analyzer/src/dart/analysis/feature_set_provider.dart:142:31)
#3      AnalysisDriver._createFileTracker (package:analyzer/src/dart/analysis/driver.dart:1500:45)
#4      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:291:5)
#5      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:119:29)
#6      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:94:37)
#7      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:55:36)
#8      MigrationCliRunner.contextCollection (package:nnbd_migration/migration_cli.dart:560:28)
#9      MigrationCliRunner.hasMultipleAnalysisContext (package:nnbd_migration/migration_cli.dart:569:12)
#10     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:649:9)
#11     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:207:72)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     DartdevRunner.runCommand (package:dartdev/dartdev.dart:249:36)
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#15     new Future.sync (dart:async/future.dart:223:31)
#16     CommandRunner.run (package:args/command_runner.dart:112:14)
#17     runDartdev (package:dartdev/dartdev.dart:112:27)
#18     main (file:///c:/src/dart-repo1b/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:32)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

No crash, help about what was wrong and what I should do instead would be appreciated.

**Comment by johnniwinther** [comment]
Apparently the tool assume that the exe file is located in the `bin` folder of the sdk. Running `out\ReleaseX64\dart-sdk\bin\dart.exe` doesn't crash.

**Comment by srawlins** [comment]
Only a problem for people compiling their own SDK, right?

**Comment by johnniwinther** [comment]
I guess. I am at least.

**Comment by srawlins** [comment]
Haha, not downplaying that; just confirming the impact of this 😛

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
