### ISSUE TITLE
Null pointer error in convert_to_null_aware assist

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#44173]
Given the following code

```dart
foo() {
  var range = 1;
  var rangeStart = range != null ? toOffset() : null;
                                              ^ invoke code action after this colon
}
```

Invoking code actions with the cursor after the final colon produces this error:

```
NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ConvertToNullAware.compute (package:analysis_server/src/services/correction/dart/convert_to_null_aware.dart:89:20)
#2      AssistProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/assist_internal.dart:251:24)
#3      AssistProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/assist_internal.dart:246:25)
#4      AssistProcessor._addFromProducers (package:analysis_server/src/services/correction/assist_internal.dart:266:22)
<asynchronous suspension>
#5      AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:171:5)
<asynchronous suspension>
#6      CodeActionHandler._getAssistActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:178:23)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#8      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:205:21)
<asynchronous suspension>
#9      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:174:22)
<asynchronous suspension>
#10     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:303:26)
<asynchronous suspension>
```

@bwilkerson

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/171703
