### ISSUE TITLE
`dart test` failing – but only on certain dart-lang packages w/ latest dev release

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#44214]
Dart SDK version: 2.12.0-33.0.dev (dev) (Wed Nov 11 17:34:11 2020 -0800) on "macos_x64"

https://github.com/kevmoo/qr.dart – `dart test` works fine

pkg:path @ b55749c

```
dart test
Error: Could not resolve the package 'test' in 'package:test/src/executable.dart'.
../../.pub-cache/hosted/pub.dartlang.org/test-1.16.0-nullsafety.9/bin/test.dart:7:1: Error: Not found: 'package:test/src/executable.dart'
export 'package:test/src/executable.dart';
^
```

pkg:collection @ 94fa188

```
dart test
Error: Could not resolve the package 'test' in 'package:test/src/executable.dart'.
../../.pub-cache/hosted/pub.dartlang.org/test-1.16.0-nullsafety.9/bin/test.dart:7:1: Error: Not found: 'package:test/src/executable.dart'
export 'package:test/src/executable.dart';
^
```

In both cases `pub run test` works fine.

Maybe this is just for packages that pkg:test depends on?

**Comment by sigurdm** [comment]
> Maybe this is just for packages that pkg:test depends on?

I think that is the clue.

Usually `dart test` will precompile `package:test/bin/test.dart` to a snapshot using logic from pub.
But pub has logic to avoid the precompilation for packages that are not "immutable" (meaning not cached, or depending on not-cached packages): https://github.com/dart-lang/pub/blob/master/lib/src/package_graph.dart#L98

That means dartdev will ask the vm to run $PUB_CACHE/hosted/pub.dartlang.org/test-<version>/bin/test.dart. But that invocation will not pick up the `.dart_tools/package_config.json` from the current working dir.

**Comment by sigurdm** [comment]
Filed: https://dart-review.googlesource.com/c/sdk/+/172181 as an attempt to fix this.

**Comment by jakemac53** [comment]
I saw these failures for the `path` package and tried locally where I was getting all kinds of flaky behavior, I got the following different failure modes from different runs:

```
$ dart test -p vm
00:03 +114 -1: test/path_set_test.dart: .of() uses the first value in the case of duplicates [E]                                  
  Expected: an object with length of <1>
    Actual: Set:['foo', '/tmp/path_testDJZIIE/foo']
     Which: has length of <2>
  
  package:test_api              expect
  test/path_set_test.dart 75:7  main.<fn>.<fn>
  
00:04 +501 -1: Some tests failed.    
```

```
$ dart test -p vm
00:04 +437 -1: loading test/windows_test.dart [E]                                                                                 
  Failed to load "test/windows_test.dart":
  Unable to spawn isolate: data:application/dart;charset=utf-8,%20%20%20%20//%20@dart=2.12%0A%20%20%20%20import%20%22dart:isolate%22;%0A%0A%20%20%20%20import%20%22package:test_core/src/bootstrap/vm.dart%22;%0A%0A%20%20%20%20import%20%22file:///usr/local/google/home/jakemac/test/windows_test.dart%22%20as%20test;%0A%0A%20%20%20%20void%20main(_,%20SendPort%20sendPort)%20%7B%0A%20%20%20%20%20%20internalBootstrapVmTest(()%20=%3E%20test.main,%20sendPort);%0A%20%20%20%20%7D%0A%20%20:6:12: Error: Error when reading '../test/windows_test.dart': No such file or directory
      import "file:///usr/local/google/home/jakemac/test/windows_test.dart" as test;
             ^
  data:application/dart;charset=utf-8,%20%20%20%20//%20@dart=2.12%0A%20%20%20%20import%20%22dart:isolate%22;%0A%0A%20%20%20%20import%20%22package:test_core/src/bootstrap/vm.dart%22;%0A%0A%20%20%20%20import%20%22file:///usr/local/google/home/jakemac/test/windows_test.dart%22%20as%20test;%0A%0A%20%20%20%20void%20main(_,%20SendPort%20sendPort)%20%7B%0A%20%20%20%20%20%20internalBootstrapVmTest(()%20=%3E%20test.main,%20sendPort);%0A%20%20%20%20%7D%0A%20%20:9:42: Error: Getter not found: 'main'.
        internalBootstrapVmTest(() => test.main, sendPort);
                                           ^^^^
00:04 +437 -1: Some tests failed. 
```

```
$ dart test
00:04 +370 -1: loading test/url_test.dart [E]                                                                                     
  Failed to load "test/url_test.dart":
  Unable to spawn isolate: Crash when compiling package:boolean_selector/src/all.dart,
  at character offset null:
  FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)
  #0      _uriBaseClosure (dart:io-patch/directory_patch.dart:64:5)
  #1      Uri.base (dart:core-patch/uri_patch.dart:21:41)
  #2      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:28:42)
  #3      HttpAwareFileSystem.entityForUri (package:vm/http_filesystem.dart:16:23)
  #4      HybridFileSystemEntity.delegate (package:front_end/src/fasta/hybrid_file_system.dart:45:37)
  <asynchronous suspension>
  #5      HybridFileSystemEntity.readAsBytes (package:front_end/src/fasta/hybrid_file_system.dart:52:45)
  <asynchronous suspension>
  #6      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:234:20)
  <asynchronous suspension>
  #7      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:443:20)
  <asynchronous suspension>
  #8      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:252:7)
  <asynchronous suspension>
  #9      SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:340:5)
  <asynchronous suspension>
  #10     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:340:7)
  <asynchronous suspension>
  #11     withCrashReporting (package:front_end/src/fasta/crash.dart:120:12)
  <asynchronous suspension>
  #12     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:100:9)
  <asynchronous suspension>
  #13     withCrashReporting (package:front_end/src/fasta/crash.dart:120:12)
  <asynchronous suspension>
  #14     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:51:12)
  <asynchronous suspension>
  <asynchronous suspension>
  
  
  #0      _uriBaseClosure (dart:io-patch/directory_patch.dart:64:5)
  #1      Uri.base (dart:core-patch/uri_patch.dart:21:41)
  #2      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:28:42)
  #3      HttpAwareFileSystem.entityForUri (package:vm/http_filesystem.dart:16:23)
  #4      HybridFileSystemEntity.delegate (package:front_end/src/fasta/hybrid_file_system.dart:45:37)
  <asynchronous suspension>
  #5      HybridFileSystemEntity.readAsBytes (package:front_end/src/fasta/hybrid_file_system.dart:52:45)
  <asynchronous suspension>
  #6      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:234:20)
  <asynchronous suspension>
  #7      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:443:20)
  <asynchronous suspension>
  #8      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:252:7)
  <asynchronous suspension>
  #9      SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:340:5)
  <asynchronous suspension>
  #10     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:340:7)
  <asynchronous suspension>
  #11     withCrashReporting (package:front_end/src/fasta/crash.dart:120:12)
  <asynchronous suspension>
  #12     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:100:9)
  <asynchronous suspension>
  #13     withCrashReporting (package:front_end/src/fasta/crash.dart:120:12)
  <asynchronous suspension>
  #14     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:51:12)
  <asynchronous suspension>
  <asynchronous suspension>
  
00:04 +435 -1: Some tests failed.  
```

**Comment by bkonyi** [comment]
@sigurdm is this fixed now that your CL landed?

**Comment by sigurdm** [comment]
It should indeed be.

I am able to run `dart test` in package:test on master.
