### ISSUE TITLE
[gardening] Test standalone_2/check_for_aot_snapshot_jit_test cannot resolve pow_test.dart in generated directory

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#44227]
The test
```
standalone_2/check_for_aot_snapshot_jit_test RuntimeError (expected Pass)
```
are failing on configurations
```
app_jitk-linux-release-x64 and app_jitk-linux-debug-x64
```

The important line in the log is probably this one:
```
'out/ReleaseX64/generated_compilations/app_jitk/tests_standalone_2_check_for_aot_snapshot_jit_test/pow_test.dart': No such file or directory`
```

Here is my local log:

```
$ python tools/test.py -n app_jitk-linux-release-x64 standalone_2/check_for_aot_snapshot_jit_test
Test configuration:
    app_jitk-linux-release-x64(architecture: x64, compiler: app_jitk, mode: release, runtime: vm, system: linux)
Suites tested: standalone_2

FAILED: app_jitk-vm release_x64 standalone_2/check_for_aot_snapshot_jit_test
Expected: Pass
Actual: RuntimeError

--- Command "app_jit" (took 09.000234s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --snapshot=/usr/local/google/home/regis/dart3/sdk/out/ReleaseX64/generated_compilations/app_jitk/tests_standalone_2_check_for_aot_snapshot_jit_test/out.jitsnapshot --snapshot-kind=app-jit --ignore-unrecognized-flags --packages=/usr/local/google/home/regis/dart3/sdk/.packages /usr/local/google/home/regis/dart3/sdk/tests/standalone_2/check_for_aot_snapshot_jit_test.dart

exit code:
0

stdout:
Running pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /tmp/aot_tmpRTOAVN/pow_test.dill /usr/local/google/home/regis/dart3/sdk/tests/standalone_2/pow_test.dart...
Ran successfully.

Running out/ReleaseX64/gen_snapshot --snapshot_kind=app-aot-elf --elf=/tmp/aot_tmpRTOAVN/pow_test.aot /tmp/aot_tmpRTOAVN/pow_test.dill...
Ran successfully.

Running /usr/local/google/home/regis/dart3/sdk/out/ReleaseX64/dart run /tmp/aot_tmpRTOAVN/pow_test.aot...
stderr: 
../../../../../../../tmp/aot_tmpRTOAVN/pow_test.aot is an AOT snapshot and should be run with 'dartaotruntime'

Got expected error result.

--- Command "vm" (took 03.000957s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --ignore-unrecognized-flags --packages=/usr/local/google/home/regis/dart3/sdk/.packages /usr/local/google/home/regis/dart3/sdk/out/ReleaseX64/generated_compilations/app_jitk/tests_standalone_2_check_for_aot_snapshot_jit_test/out.jitsnapshot

exit code:
255

stdout:
Running pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /tmp/aot_tmpAMZUWQ/pow_test.dill /usr/local/google/home/regis/dart3/sdk/out/ReleaseX64/generated_compilations/app_jitk/tests_standalone_2_check_for_aot_snapshot_jit_test/pow_test.dart...
stdout: 
out/ReleaseX64/generated_compilations/app_jitk/tests_standalone_2_check_for_aot_snapshot_jit_test/pow_test.dart: Error: No 'main' method found.
Try adding a method named 'main' to your program.
Error: Error when reading 'out/ReleaseX64/generated_compilations/app_jitk/tests_standalone_2_check_for_aot_snapshot_jit_test/pow_test.dart': No such file or directory

stderr:
Unhandled exception:
Expect.equals(expected: <254>, actual: <0>) fails.
#0      Expect._fail (package:expect/expect.dart:691:5)
#1      Expect.equals (package:expect/expect.dart:132:5)
#2      main (file:///usr/local/google/home/regis/dart3/sdk/tests/standalone_2/check_for_aot_snapshot_jit_test.dart:33:10)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python tools/test.py -n app_jitk-linux-release-x64 standalone_2/check_for_aot_snapshot_jit_test
[00:13 | 100% | +    0 | -    1]

=== 0 tests passed, 1 failed ===

```

**Comment by crelier** [comment]
@bkonyi do you mind having a look? Thanks

**Comment by bkonyi** [comment]
We shouldn't be running AOT snapshots with `dart run`. Did something change in the test runner?
