### ISSUE TITLE
Dart Analyzer continuous crashes

### ISSUE THREAD

**Issue by kevan-mtl** [dart-lang/sdk#44299]
Hello everyone!

I ran into a couple issues with Dart Analyzer over the last 2 days: first it started flagging weird issues (with one very similar to this [one](https://github.com/flutter/flutter/issues/22302)) and after a VS Code restart, I simply started getting prompts like these:
![Screen Shot 2020-11-23 at 8 23 17 PM](https://user-images.githubusercontent.com/25143586/100034243-c3b49400-2dc9-11eb-823b-c322030b819e.png)

Here is a `flutter doctor` output just in case:
![Screen Shot 2020-11-23 at 8 25 22 PM](https://user-images.githubusercontent.com/25143586/100034363-0aa28980-2dca-11eb-96f9-76368f1d8bd1.png)

Also, below is the Log file of one of the Dart Analyzer crashes (they were all very similar). 
[log-a79e.txt](https://github.com/dart-lang/sdk/files/5586789/log-a79e.txt)

Thanks in advance for your help!

Kevan

**Comment by kevan-mtl** [comment]
I gave Android Studio a shot and I get exactly the same error, see log below:

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.12.0-62.0.dev`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.6, screens 1440x900, 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.12.0-62.0.dev, server version 1.32.0, FATAL error: NoSuchMethodError: The getter 'precedence' was called on null.
Receiver: null
Tried calling: precedence
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:469:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1073:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:996:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1034:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:402:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

For additional log information, please append the contents of
file:///private/var/folders/n8/jt9708hj7plbp_g3szhjn2740000gp/T/report.txt.

**Comment by kevan-mtl** [comment]
Alright, I seem to have fix the issue: I had an "and" that I replaced with the appropriate && logical operator in a BlocBuilder widget's buildWhen method to compare 2 states. When I rebooted VS Code, the Analyzer started working fine... Still not sure why the Analyzer didn't pick this one up.
