### ISSUE TITLE
Implicit variable typing leads to useless trace: Crash when compiling null 

### ISSUE THREAD

**Issue by gronka** [dart-lang/sdk#44336]
I have some `int` variables initialized such as
```
class ListingConstants {
    static const maxDescription = 1000;
}
```

I found that if I set the value (1000) outside of the range of `int`, dart comes to a hard and ambiguous crash:
```
class ListingConstants {
    static const maxDescription = 1000;
    static const maxPrice = 99999999999999999999;  // twenty 9s
}
```

The error is easy to fix/track/locate by specifying `int`, but without `int` the stack trace is entirely useless.

Entire output:
```
dev@pop-os ~/projects/lairdmobile (split) $ flutter run
Running "flutter pub get" in lairdmobile...                        496ms
Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Unhandled exception:                                                    
Crash when compiling null,                                              
at character offset null:                                               
NoSuchMethodError: The method 'buildProblem' was called on null.        
Receiver: null                                                          
Tried calling: buildProblem(Instance of 'Message', 5893, 19)            
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)    
#1      InferenceVisitor.visitShadowLargeIntLiteral (package:front_end/src/fasta/kernel/inference_visitor.dart:1263:48)
#2      ShadowLargeIntLiteral.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:956:20)
#3      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1737:27)
#4      _ImplicitFieldTypeRoot.computeType (package:front_end/src/fasta/kernel/implicit_field_type.dart:149:55)
#5      SourceFieldBuilder.inferType (package:front_end/src/fasta/builder/field_builder.dart:422:47)
#6      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:1188:35)
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:362:14)
<asynchronous suspension>                                               
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:120:12)
<asynchronous suspension>                                               
#9      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:281:37)
<asynchronous suspension>                                               
<asynchronous suspension>                                               
                                                                        
                                                                        
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)    
#1      InferenceVisitor.visitShadowLargeIntLiteral (package:front_end/src/fasta/kernel/inference_visitor.dart:1263:48)
#2      ShadowLargeIntLiteral.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:956:20)
#3      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1737:27)
#4      _ImplicitFieldTypeRoot.computeType (package:front_end/src/fasta/kernel/implicit_field_type.dart:149:55)
#5      SourceFieldBuilder.inferType (package:front_end/src/fasta/builder/field_builder.dart:422:47)
#6      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:1188:35)
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:362:14)
<asynchronous suspension>                                               
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:120:12)
<asynchronous suspension>                                               
#9      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:281:37)
<asynchronous suspension>                                               
<asynchronous suspension>                                               
the Dart compiler exited unexpectedly.                                  
the Dart compiler exited unexpectedly.  
```

$ dart --version
Dart SDK version: 2.12.0-29.10.beta (beta) (Tue Nov 17 10:50:22 2020 +0100) on "linux_x64"

I'm using android virtual device with android studio, but I'm quite sure the compiler isn't even making it to a part where this would matter.

**Comment by asashour** [comment]
This seems to be fixed (at least with `Dart SDK version: 3.0.0-76.0.dev (dev) (Fri Dec 30 09:07:04 2022 -0800) on "windows_x64"`)
