### ISSUE TITLE
VM gives bad URI to the frontend when given "double slash" path

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#44330]
We can give the VM paths in several ways, e.g. the package path and the actual input path. There might be more, I'm not sure.
If you give it an invalid path, though, at least on linux starting with a double slash, but otherwise looking OK, e.g.
`out/ReleaseX64/dart --packages=//usr/local/path/to/.packages t.dart` it crashes then auto-detecting nullability:

```
kernel-service: Error: Unhandled exception:
Invalid argument(s): Exception when reading 'file://usr/local/path/to/.dart_tool/package_config.json': Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:569:7)
<asynchronous suspension>
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:583:26)
<asynchronous suspension>
#2      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:648:11)
<asynchronous suspension>
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:517:26)
<asynchronous suspension>
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:471:32)
<asynchronous suspension>
#5      languageVersionForUri.<anonymous closure> (package:front_end/src/api_prototype/language_version.dart:58:35)
<asynchronous suspension>
#6      languageVersionForUri (package:front_end/src/api_prototype/language_version.dart:38:10)
<asynchronous suspension>
#7      uriUsesLegacyLanguageVersion (package:front_end/src/api_prototype/language_version.dart:147:7)
<asynchronous suspension>
#8      autoDetectNullSafetyMode (package:vm/kernel_front_end.dart:557:18)
[...]
```
Notice how `file://usr/local/path/to/.dart_tool/package_config.json` is invalid because it says `file://` instead of `file:///`.

That part is rather easily fixed though, by something like this:
```
diff --git a/pkg/vm/bin/kernel_service.dart b/pkg/vm/bin/kernel_service.dart
index fb5d3f15a69..d08b8efd438 100644
--- a/pkg/vm/bin/kernel_service.dart
+++ b/pkg/vm/bin/kernel_service.dart
@@ -169,7 +169,7 @@ abstract class Compiler {
       this.packageConfig: null}) {
     Uri packagesUri = null;
     if (packageConfig != null) {
-      packagesUri = Uri.parse(packageConfig);
+      packagesUri = resolveInputUri(packageConfig);
     } else if (Platform.packageConfig != null) {
       packagesUri = Uri.parse(Platform.packageConfig);
     }
```

which works because the autodetection is given the package path as the path given on the command line, in this example as `//usr/local/patrh/to/.packages` and that `resolveInputUri` can handle that (it ends up inserting several slashes at the front, but it works). It seems that the VM takes the input from the command line, passes it through `PathSanitizer` and passes it which doesn't - in this case - do much (which is good).

It now instead crashes a little later though - when trying to actually compile:
```
Invalid argument(s): Exception when reading 'file://usr/local/path/to/.dart_tool/package_config.json': Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:569:7)
<asynchronous suspension>
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:583:26)
<asynchronous suspension>
#2      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:648:11)
<asynchronous suspension>
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:517:26)
<asynchronous suspension>
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:471:32)
<asynchronous suspension>
#5      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:72:35)
<asynchronous suspension>
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:120:12)
<asynchronous suspension>
#7      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:51:12)
<asynchronous suspension>
#8      generateKernel (package:front_end/src/kernel_generator_impl.dart:50:10)
<asynchronous suspension>
#9      kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:97:11)
<asynchronous suspension>
#10     SingleShotCompilerWrapper.compileInternal (file:///[...]/pkg/vm/bin/kernel_service.dart:377:11)
<asynchronous suspension>
#11     Compiler.compile.<anonymous closure> (file:///[...]/pkg/vm/bin/kernel_service.dart:197:45)
<asynchronous suspension>
#12     _processLoadRequest (file:///[...]/pkg/vm/bin/kernel_service.dart:847:37)
<asynchronous suspension>
```

This time, though, the same trick doesn't work (i.e. replacing `Uri.parse` with `resolveInputUri` in line ~786) because the (string) path it's given is now `file://usr/local/path/to/.packages` because - it seems - in this instance the VM runs `dart:_builtin::_setPackagesMap` on the string (which - basically just internally does `Uri.parse`).

Also, if you try to run the VM on a file provided like that, e.g. `out/ReleaseX64/dart //usr/local/path/to/t.dart` it crashes like this:
```
kernel-service: Error: Unhandled exception:
Invalid argument(s): Exception when reading 'file://usr/local/google/home/jensj/code/dart-sdk/sdk/.dart_tool/package_config.json': Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      ProcessedOptions._findPackages.checkInDir (package:front_end/src/base/processed_options.dart:691:9)
<asynchronous suspension>
#1      ProcessedOptions._findPackages (package:front_end/src/base/processed_options.dart:696:21)
<asynchronous suspension>
#2      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:544:24)
<asynchronous suspension>
#3      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:471:32)
<asynchronous suspension>
#4      languageVersionForUri.<anonymous closure> (package:front_end/src/api_prototype/language_version.dart:58:35)
<asynchronous suspension>
#5      languageVersionForUri (package:front_end/src/api_prototype/language_version.dart:38:10)
<asynchronous suspension>
#6      uriUsesLegacyLanguageVersion (package:front_end/src/api_prototype/language_version.dart:147:7)
<asynchronous suspension>
#7      autoDetectNullSafetyMode (package:vm/kernel_front_end.dart:557:18)
<asynchronous suspension>
#8      _processLoadRequest (file:///[...]/pkg/vm/bin/kernel_service.dart:803:5)
<asynchronous suspension>
```

because it tries to find the `.packages` file relative to the input uri which is given with the wrong path. The path is - in package:vm - converted with `Uri.base.resolve`... replacing it with `resolveInputUri` seems to work though.

So one option might be to use `resolveInputUri` in package:vm and not do the call to `_setPackagesMap` in the VM, but I don't know the context of any of that, and e.g. flutters own embedding might need updating too..?
I'm sure other options can be found as well...

Related bugs:
https://github.com/flutter/flutter/issues/71274
https://github.com/flutter/flutter/issues/63579

/cc @mraleph

**Comment by lrhn** [comment]
See https://github.com/dart-lang/sdk/issues/44151

Our URI/path input validation/interpretation is highly inconsistent. We should figure out *what* we want to do, then do that consistently.

User inputs are *likely* to be local paths, not URIs. If they are paths, then they should be *path normalized* before being converted to URIs because URIs and paths disagree on which paths are "the same". (For example `foo//bar/baz.dart` is different from `foo/bar/baz.dart` as a URI, but means the same thing as a path).

If a user writes `//usr/local/path/to/t.dart` as a path, *they probably mean `/usr/local/path/to/t.dart`*. 
The are specifying a *file*, not a *path* (although obviously the two cannot be separated completely).
It's the same file, the latter is just the canonicalized version of the former. We should not create a URI directly from the former.

(And if they wrote `\\users\local\path\t.dart` on Windows, they probably meant it, since that means something different from `\users\local\path\t.dart`, so any normalization should be platform aware).

**Comment by jensjoha** [comment]
Worth noticing is that on flutter, users are running into the issue seemingly because they've somehow gotten the flutter path added to the `PATH` with the double-slash ---meaning that when they run into the error they haven't actually provided any path, making it even more confusing.

**Comment by barahijawi** [comment]
```
cd Users
cd USERNAME <= change with your username 
cd flutter
cd packages
cd flutter_tools
../../bin/flutter --version
```
credit to https://github.com/flutter/flutter/issues/63579#issuecomment-719480929
@izzyaf
