### ISSUE TITLE
[vm] assert object.cc: 4255 Unable to use class [...] which is not loaded yet.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#44419]
I hit an assert while building Flutter Engine.

Dart revision: 3a75dffd8a499fea8849436b70c22027ff81f9b8. (Minimal local Dart changes, none related to class loading.)

Triggering the build command again did not trigger this error, so it's flaky.

```
~/flt/engine/src/flutter$ ./tools/fuchsia/build_fuchsia_artifacts.py --no-lto  --arch x64 --runtime-mode=debug
Running gn for variant "fuchsia_debug_x64" with flags: --fuchsia,--fuchsia-cpu,x64,--runtime-mode,debug,--no-lto
Generating GN files in: out/fuchsia_debug_x64
Done. Made 1249 targets from 229 files in 538ms
ninja: Entering directory `/usr/local/google/home/dacoharkes/flt/engine/src/flutter/tools/fuchsia/../../../out/fuchsia_debug_x64'
[2173/4940] SOLINK ./libffi_foo_functions.so
llvm-nm: for the   --format option: Cannot find option named 'p'!
[3695/4940] ACTION //third_party/dart/utils/dartanalyzer:generate_summary_strong(//build/toolchain/fuchsia:fuchsia)
FAILED: gen/strong.sum 
python ../../third_party/dart/build/gn_run_binary.py compiled_action clang_x64/dart -Dsdk_hash=3a75dffd8a --packages=/usr/local/google/home/dacoharkes/flt/engine/src/third_party/dart/.packages /usr/local/google/home/dacoharkes/flt/engine/src/third_party/dart/pkg/analyzer/tool/summary/build_sdk_summaries.dart build /usr/local/google/home/dacoharkes/flt/engine/src/out/fuchsia_debug_x64/gen/strong.sum /usr/local/google/home/dacoharkes/flt/engine/src/out/fuchsia_debug_x64/dart-sdk
Command failed: ./clang_x64/dart -Dsdk_hash=3a75dffd8a --packages=/usr/local/google/home/dacoharkes/flt/engine/src/third_party/dart/.packages /usr/local/google/home/dacoharkes/flt/engine/src/third_party/dart/pkg/analyzer/tool/summary/build_sdk_summaries.dart build /usr/local/google/home/dacoharkes/flt/engine/src/out/fuchsia_debug_x64/gen/strong.sum /usr/local/google/home/dacoharkes/flt/engine/src/out/fuchsia_debug_x64/dart-sdk
output: ../../third_party/dart/runtime/vm/object.cc: 4255: error: Unable to use class 15187408 which is not loaded yet.
version=2.12.0-edge.3a75dffd8a499fea8849436b70c22027ff81f9b8 (be) (Thu Dec 3 21:48:11 2020 +0000) on "linux_x64"
pid=3298291, thread=3298302, isolate_group=kernel-service(0x7f18dc000f80), isolate=kernel-service(0x7f18dc005ce0)
isolate_instructions=7f18e4480000, vm_instructions=17ed7a0
  pc 0x0000000001a3b09c fp 0x00007f18e4fde300 ./clang_x64/dart+0x183b09c
-- End of DumpStackTrace
[exit     : sp(0) fp(0x7f18e4fde840) pc(0)]
[stub     : sp(0x7f18e4fde850) fp(0x7f18e4fde880) pc(0x7f18e50028f0)]

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x7f1900434628
Aborting re-entrant request for stack trace.

[4539/4940] CXX obj/third_party/skia/src/core/skia.SkRuntimeEffect.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./tools/fuchsia/build_fuchsia_artifacts.py", line 391, in <module>
    sys.exit(main())
  File "./tools/fuchsia/build_fuchsia_artifacts.py", line 380, in main
    args.targets.split(","))
  File "./tools/fuchsia/build_fuchsia_artifacts.py", line 283, in BuildTarget
    BuildNinjaTargets(out_dir, [ 'flutter' ] + additional_targets)
  File "./tools/fuchsia/build_fuchsia_artifacts.py", line 72, in BuildNinjaTargets
    os.path.join(_out_dir, variant_dir)] + targets)
  File "./tools/fuchsia/build_fuchsia_artifacts.py", line 55, in RunExecutable
    subprocess.check_call(command, cwd=_src_root_dir)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['autoninja', '-C', '/usr/local/google/home/dacoharkes/flt/engine/src/flutter/tools/fuchsia/../../../out/fuchsia_debug_x64', 'flutter', '']' returned non-zero exit status 1
```

**Comment by rajmaniar** [comment]
I just saw the same thing on dart-vm in a server application.

**Comment by alexlapa** [comment]
Encountered in CLI app. Its flaky, but running with `--enable-asserts` increases reproducibility.

I think i can make minimal reproducible example if that helps.
