### ISSUE TITLE
`expr[this] ??= ...` causes assertion failure

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44475]
The following code causes an assertion failure when built using dart2js with strong null safety:
```dart
class C {
  static final Expando<int> _debugIds = new Expando<int>();

  static int _nextDebugId = 0;

  @override
  String toString() {
    int id = _debugIds[this] ??= _nextDebugId++;
    return 'C$id';
  }
}

main() {
  print(C());
}
```
The stack trace looks like this:
```
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      createVariable (package:front_end/src/fasta/kernel/internal_ast.dart:3752:10)
#3      createVariableForResult (package:front_end/src/fasta/kernel/internal_ast.dart:3763:10)
#4      InferenceVisitor.visitIfNullIndexSet (package:front_end/src/fasta/kernel/inference_visitor.dart:3233:41)
#5      IfNullIndexSet.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:2518:20)
#6      TypeInferrerImpl._inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1755:27)
#7      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1790:40)
#8      InferenceVisitor.visitVariableDeclaration (package:front_end/src/fasta/kernel/inference_visitor.dart:6293:36)
#9      VariableDeclaration.accept (package:kernel/ast.dart:8264:43)
#10     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3516:24)
#11     InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:267:20)
#12     InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:288:30)
#13     Block.accept (package:kernel/ast.dart:7062:43)
#14     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3516:24)
#15     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:1833:39)
#16     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:991:28)
...
```
Based on the stacktrace I assume this is a CFE issue.

**Comment by stereotype441** [comment]
https://dart-review.googlesource.com/c/sdk/+/176280 contains a repro
