### ISSUE TITLE
vm/cc/DescriptorList_TokenPositions fails on dartk-ubsan-linux-release-x64

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#44508]
On https://dart.googlesource.com/sdk/+/e2df4d30a0b25bb550eeb9d96a21b3d3406e606d  this test started to fail on ubsan bot:

```
/=========================================================================\
| vm/cc/DescriptorList_TokenPositions broke (Pass -> Fail, expected Pass) |
\=========================================================================/

--- Command "run_vm_unittest" (took 02.000305s):
DART_CONFIGURATION=ReleaseUBSANX64 out/ReleaseUBSANX64/run_vm_tests --dfe=/b/s/w/ir/cache/builder/sdk/out/ReleaseUBSANX64/gen/kernel-service.dart.snapshot --ignore-unrecognized-flags DescriptorList_TokenPositions

exit code:
1

stdout:
Running test: DescriptorList_TokenPositions

stderr:
../../runtime/vm/code_descriptors.cc:45:46: runtime error: signed integer overflow: 5 - -2147483648 cannot be represented in type 'int'
    #0 0x55bb44867f91 in dart::DescriptorList::AddDescriptor(dart::PcDescriptorsLayout::Kind, long, long, dart::TokenPosition, long, long) ../../out/ReleaseUBSANX64/../../runtime/vm/code_descriptors.cc:45:46
    #1 0x55bb44177b47 in dart::Dart_TestHelperDescriptorList_TokenPositions(dart::Thread*) ../../out/ReleaseUBSANX64/../../runtime/vm/code_descriptors_test.cc:148:18
    #2 0x55bb441779a9 in dart::Dart_TestDescriptorList_TokenPositions() ../../out/ReleaseUBSANX64/../../runtime/vm/code_descriptors_test.cc:123:1
    #3 0x55bb4414b145 in dart::TestCase::Run() ../../out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:52:3
    #4 0x55bb4414b4a5 in dart::TestCaseBase::RunTest() ../../out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:64:11
    #5 0x55bb4432fcfc in dart::TestCaseBase::RunAll() ../../out/ReleaseUBSANX64/../../runtime/vm/unit_test.cc:86:13
    #6 0x55bb4414bfef in dart::Main(int, char const**) ../../out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:394:3
    #7 0x55bb4414bb80 in main ../../out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:425:29
    #8 0x7f78ec43083f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #9 0x55bb44131ce8 in _start (/b/s/w/ir/cache/builder/sdk/out/ReleaseUBSANX64/run_vm_tests+0x523fce8)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../runtime/vm/code_descriptors.cc:45:46 in

--- Re-run this test:
python tools/test.py -n dartk-ubsan-linux-release-x64 vm/cc/DescriptorList_TokenPositions
```

cc @sstrickl

**Comment by sstrickl** [comment]
Already fixed and submitted in [CL 176520](https://dart-review.googlesource.com/c/sdk/+/176520).
