### ISSUE TITLE
Missing canonical name reference error after CFE change

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#44560]
After https://github.com/dart-lang/sdk/commit/52db62dd65284192755906691baf66c47a43f47e landed my local HHH builder of a big application fails with:
```
stdout >> result 1aa29fb2-214a-4553-a496-913b28fc91ff
stdout >> ../../../xxx/third_party/dart/built_collection/lib/src/list_multimap/built_list_multimap.dart:125:51: Warning: Operand of null-aware operation '!' has type 'BuiltList<V>' which excludes null.
stdout >>  - 'BuiltList' is from 'package:built_collection/src/list.dart' ('../../../xxx/third_party/dart/built_collection/lib/src/list.dart').
stdout >>     return identical(result, null) ? _emptyList : result!;
stdout >>                                                   ^   
stderr >> Unhandled exception:
stderr >> Invalid argument(s): Missing canonical name for Reference to _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.child
stderr >> #0      BinaryPrinter.writeNullAllowedReference (package:kernel/binary/ast_to_binary.dart:874:9)
stderr >> #1      BinaryPrinter.writeNullAllowedInstanceMemberReference (package:kernel/binary/ast_to_binary.dart:864:5)
stderr >> #2      BinaryPrinter.visitPropertyGet (package:kernel/binary/ast_to_binary.dart:1462:5)
stderr >> #3      PropertyGet.accept (package:kernel/ast.dart:3734:44)
stderr >> #4      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:391:10)
stderr >> #5      BinaryPrinter.visitMethodInvocation (package:kernel/binary/ast_to_binary.dart:1604:5)
stderr >> #6      MethodInvocation.accept (package:kernel/ast.dart:5044:44)
stderr >> #7      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:391:10)
stderr >> #8      BinaryPrinter.visitNot (package:kernel/binary/ast_to_binary.dart:1654:5)
stderr >> #9      Not.accept (package:kernel/ast.dart:5373:44)
stderr >> #10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:391:10)
stderr >> #11     BinaryPrinter.visitIfStatement (package:kernel/binary/ast_to_binary.dart:2082:5)
stderr >> #12     IfStatement.accept (package:kernel/ast.dart:7750:43)
stderr >> #13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:391:10)
stderr >> #14     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:301:7)
stderr >> #15     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1950:5)
stderr >> #16     Block.accept (package:kernel/ast.dart:7062:43)
stderr >> #17     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:391:10)
stderr >> #18     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:484:7)
stderr >> #19     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1378:5)
stderr >> #20     FunctionNode.accept (package:kernel/ast.dart:3095:38)
stderr >> #21     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:398:10)
stderr >> #22     BinaryPrinter.writeOptionalFunctionNode (package:kernel/binary/ast_to_binary.dart:493:7)
stderr >> #23     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1251:5)
stderr >> #24     Procedure.accept (package:kernel/ast.dart:2574:40)
stderr >> #25     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:419:10)
stderr >> #26     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:310:7)
stderr >> #27     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1167:5)
stderr >> #28     Class.accept (package:kernel/ast.dart:1341:38)
stderr >> #29     BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:433:10)
stderr >> #30     BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:328:7)
stderr >> #31     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1005:5)
stderr >> #32     Library.accept (package:kernel/ast.dart:606:38)
stderr >> #33     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:412:10)
stderr >> #34     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:720:9)
stderr >> #35     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:563:7)
stderr >> #36     Timeline.timeSync (dart:developer/timeline.dart:163:22)
stderr >> #37     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:545:14)
stderr >> #38     FrontendCompiler.writeDillFile (file:///.../src/third_party/dart/pkg/frontend_server/lib/frontend_server.dart:665:13)
stderr >> #39     FrontendCompiler.compile (file:///.../src/third_party/dart/pkg/frontend_server/lib/frontend_server.dart:544:13)
stderr >> <asynchronous suspension>
stderr >> #40     starter (file:///.../src/third_party/dart/pkg/frontend_server/lib/frontend_server.dart:1330:12)
stderr >> <asynchronous suspension>
stderr >> #41     main (file:///.../src/third_party/dart/pkg/frontend_server/bin/frontend_server_starter.dart:9:14)
stderr >> <asynchronous suspension>
```

@johnniwinther Any ideas how your CL could cause this?

**Comment by johnniwinther** [comment]
I'll take a look.

**Comment by johnniwinther** [comment]
My suspicion is mixin deduplication. The error occurs when trying to write the member signature origin and the origin is pointing to a mixin application member that is missing.

The setup is
```
// opt-in lib
mixin M {
  int get property => 42;
}
class C extends Object with M {}
// opt-out
class D extends C {}
method(D d) => d.property;
```
Before the mixin super stubs we would generate (including VM mixin resolution):
```
// opt-in lib
mixin M {
  int get property => 42;
}
class _C&Object&M {
  int get property => 42; // clone of M.property
}
class C extends _C&Object&M {}
// opt-out
class D extends C {
  /*member-signature*/int* get property; /*with origin M.property*/
}
method(D d) => d.property; // Points to D.property
```
and after we generate (before VM transformations):
```
// opt-in lib
mixin M {
  int get property => 42;
}
class _C&Object&M {
  /*mixin super stub*/int get property => super.property ; // Points to M.property 
}
class C extends _C&Object&M {}
// opt-out
class D extends C {
  /*member-signature*/int* get property; /*with origin _C&Object&M.property*/
}
method(D d) => d.property; // Points to D.property 
```
and after VM tranformations
```
// opt-in lib
mixin M {
  int get property => 42;
}
class _C&Object&M {
  int get property => 42; // Clone of M.property replacing _C&Object&M.property
}
class C extends _C&Object&M {}
// opt-out
class D extends C {
  /*member-signature*/int* get property; /*with origin _C&Object&M.property*/
}
method(D d) => d.property; // Points to D.property 
```

When we try to serialize `d.property` which points to the member signature `D.property` we also serialize the origin `_C&Object&M.property`. If the `stubTarget` property of `D.property` has not been updated when `_C&Object&M` is removed due to mixin deduplication, we would have a dangling pointer.

**Comment by mkustermann** [comment]
@johnniwinther Do you think it's fixable by the time most people are back from vacation? If not, we might want to consider temporarily reverting the CL.

**Comment by johnniwinther** [comment]
I'll make a CL that fixes the mixin deduplication handling of this. Can you verify if it is actually the problem (can you turn off the deduplication?) ?

Also, when do we run the deduplication and do we have some unit tests for it?

**Comment by johnniwinther** [comment]
I've created the CL: https://dart-review.googlesource.com/c/sdk/+/177127 

You can use it to verify that it fixes the problem. We should add some test of it, though.

**Comment by mkustermann** [comment]
> You can use it to verify that it fixes the problem. We should add some test of it, though.

@johnniwinther Awesome! Yes, it fixes the problem.
