### ISSUE TITLE
Nullsafety migration, package sky_engine (js_dart2js.dart) is opting out of null safety

### ISSUE THREAD

**Issue by SandroMaglione** [dart-lang/sdk#44567]
When trying to migrate my package [`step_progress_indicator`](https://pub.dev/packages/step_progress_indicator) to nullsafety, launching the command `flutter pub publish --dry-run` returns a warning:

```
Package validation found the following potential issue:
* This package is opting into null-safety, but a dependency or file is not.

  package:sky_engine/js\js_dart2js.dart is opting out of null safety:
    ╷
  5 │ // @dart = 2.6
    │ ^^^^^^^^^^^^^^
    ╵

  Note that by publishing with non-migrated dependencies your package may be
  broken at any time if one of your dependencies migrates without a breaking
  change release.

  We highly recommend that you wait until all of your dependencies have been
  migrated before publishing.

  Run `pub outdated --mode=null-safety` for more information about the state of
  dependencies.

  See https://dart.dev/null-safety/migration-guide
  for more information about migrating.
```
Running then `flutter pub outdated --mode=null-safety` returns:
```
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

All your dependencies declare support for null-safety.
```
When I inspect the publish command the error is:
```
SLVR:         selecting vector_math 2.1.0-nullsafety.5
SLVR:         fact: typed_data >=1.3.0-nullsafety.4 depends on collection >=1.15.0-nullsafety <1.15.0
SLVR:           selecting typed_data 1.3.0-nullsafety.5
SLVR:             selecting sky_engine 0.0.99 from sdk
SLVR:               selecting meta 1.3.0-nullsafety.6
SLVR:                 selecting collection 1.15.0-nullsafety.5
SLVR:                   selecting characters 1.1.0-nullsafety.5
SLVR: Version solving took 0:00:00.723700 seconds.
    | Tried 1 solutions.
WARN: Package validation found the following potential issue:
WARN: * This package is opting into null-safety, but a dependency or file is not.
    |
    |   package:sky_engine/js\js_dart2js.dart is opting out of null safety:
    |     ╷
    |   5 │ // @dart = 2.6
    |     │ ^^^^^^^^^^^^^^
    |     ╵
    |
    |   Note that by publishing with non-migrated dependencies your package may be
    |   broken at any time if one of your dependencies migrates without a breaking
    |   change release.
    |
    |   We highly recommend that you wait until all of your dependencies have been
    |   migrated before publishing.
    |
    |   Run `pub outdated --mode=null-safety` for more information about the state of
    |   dependencies.
    |
    |   See https://dart.dev/null-safety/migration-guide
    |   for more information about migrating.
    |
WARN: Package validation found the following hint:
WARN: * You're about to publish a package that opts into null safety.
    |   The previous version (0.2.5+8) isn't opted in.
    |   See https://dart.dev/null-safety/migration-guide for best practices.
WARN: 
    | Package has 1 warning and 1 hint..
[+8745 ms] "flutter publish" took 8,985ms.
[  +11 ms] pub finished with exit code 65
[  +13 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:358:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:225:5)
           <asynchronous suspension>
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #13     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:88:3)


[ +305 ms] ensureAnalyticsSent: 100ms
[   +3 ms] Running shutdown hooks
[   +8 ms] Shutdown hooks complete
[   +2 ms] exiting with code 65
```
So it seems that sky_engine is not nullsafe yet. 
I am not sure how to deal with it. Is it safe to publish a nullsafe version even with this error or I should wait?
***
* Dart SDK Version (`dart --version`)
```
Dart SDK version: 2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "windows_x64"
```
* Flutter (`flutter doctor -v`)
```
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.25.0-8.1.pre at C:\Users\Sandro Maglione\flutter\flutter
    • Framework revision 8f89f6505b (2 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)
```

**Comment by srawlins** [comment]
I think the error has good advice:

> This package is opting into null-safety, but a dependency or file is not.

> package:sky_engine/js\js_dart2js.dart is opting out of null safety:

> We highly recommend that you wait until all of your dependencies have been migrated before publishing.

Broadly speaking, the sky_engine package has migrated, but a library which is imported into your app, `package:sky_engine/js\js_dart2js.dart`, is not migrated yet.

CC @leafpetersen in case there is canonical guidance in this situation.

**Comment by SandroMaglione** [comment]
The only direct dependencies in the package are:
```
package:flutter/material.dart
package:flutter_test/flutter_test.dart
dart:math
```

Does the issue have something to do with one of these? Is `sky_engine` and `sky_engine/js\js_dart2js.dart` included in any of these?

**Comment by udos86** [comment]
I can confirm this issue with my package [`flutter_fast_forms`](https://pub.dev/packages/flutter_fast_forms)

Oddly I was able to to publish a null safety pre-release without any warning yesterday, but after adding some Cupertino-specific code this message also appears when entering `flutter pub publish --dry-run`.

* `pubspec.yml`
```yml
environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.25.0-8.1.pre"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0-nullsafety.2
  mask_text_input_formatter: ^2.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.16.0-nullsafety.13
```

* Dart SDK Version (dart --version)
```shell
Dart SDK version: 2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "macos_x64"
```

* Flutter (`flutter --version`)
```shell
Flutter 1.25.0-8.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8f89f6505b (vor 2 Wochen) • 2020-12-15 15:07:52 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)
```

**Comment by leafpetersen** [comment]
cc @cbracken @yjbanov @jonahwilliams I know sky_engine is a little weird - is this expected?

**Comment by modulovalue** [comment]
NNBD is long over, this shouldn't be relevant anymore? Do you think we can close this @lrhn?

**Comment by lrhn** [comment]
Yes. Whatever the issue was, it's now moot.
