### ISSUE TITLE
Request textDocument/signatureHelp failed

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#44627]
```
[Error - 12:53:16 PM] Request textDocument/signatureHelp failed.
  Message: An error occurred while handling textDocument/signatureHelp request
  Code: -32001 
[Error - 12:53:16 PM] An error occurred while handling textDocument/signatureHelp request: type 'FunctionTypeAliasElementImpl' is not a subtype of type 'ExecutableElement' in type cast
#0      DartUnitSignatureComputer.compute (package:analysis_server/src/computer/computer_signature.dart:57:51)
#1      SignatureHelpHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_signature_help.dart:55:34)
#2      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#3      SignatureHelpHandler.handle (package:analysis_server/src/lsp/handlers/handler_signature_help.dart:47:19)
<asynchronous suspension>
#4      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:183:22)
<asynchronous suspension>
#5      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:302:26)
<asynchronous suspension>
```

What I was doing:
> Editing some code in Visual Studio Code with LSP enabled

Dart version:
Dart SDK version: 2.12.0-179.0.dev (dev) (Wed Dec 23 21:08:22 2020 -0800) on "windows_x64"

**Comment by DanTup** [comment]
I just hit this too, using v2.12.1. I could repro it there by importing two libraries that export a class with the same name, then trying to invoke signature help on the constructor:

## foo1.dart & foo2.dart

```dart
class Breakpoint {}
```

## foo.dart

```dart
import 'foo1.dart';
import 'foo2.dart';

void setBreakpoints() {
  Breakpoint(^); // Invoke sig help at ^
}

```

Results in:

```
[Error - 17:49:28] Request textDocument/signatureHelp failed.
  Message: An error occurred while handling textDocument/signatureHelp request
  Code: -32001 
[Error - 17:49:28] An error occurred while handling textDocument/signatureHelp request: type 'MultiplyDefinedElementImpl' is not a subtype of type 'ExecutableElement' in type cast
#0      DartUnitSignatureComputer.compute (package:analysis_server/src/computer/computer_signature.dart:55:51)
#1      SignatureHelpHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_signature_help.dart:55:34)
#2      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#3      SignatureHelpHandler.handle (package:analysis_server/src/lsp/handlers/handler_signature_help.dart:47:19)
<asynchronous suspension>
#4      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:183:22)
<asynchronous suspension>
#5      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:301:26)
<asynchronous suspension>
```

I can't repro on latest code though, it appears that 9f5f825d96d2c6d43a930e748209ed9cb5add015 was a fix for it.
