### ISSUE TITLE
[vm] ASAN failures on DRT_Throw

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#44708]
There are new test failures on [Reland "[VM] Adds Future.then and Future.catchError stack unwinding."](https://github.com/dart-lang/sdk/commit/9978a246c10c6c6297bc8ac52fd34d3423f6071c).

There are multiple ASAN failures on DRT_Throw:

```
==17655==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fc4625fd4a0 at pc 0x55b7944d80f8 bp 0x7fc4625fd3f0 sp 0x7fc4625fd3e8
READ of size 8 at 0x7fc4625fd4a0 thread T3 (DartWorker)
    #0 0x55b7944d80f7 in dart::StackFrame::fp() const ../../out/ReleaseASANX64/../../runtime/vm/stack_frame.h:40:29
    #1 0x55b7944d80f7 in dart::StackFrame::GetCallerSp() const ../../out/ReleaseASANX64/../../runtime/vm/stack_frame.h:115:38
    #2 0x55b7944d80f7 in dart::StackTraceUtils::ClosureFromFrameFunction(dart::Zone*, dart::CallerClosureFinder*, dart::DartFrameIterator const&, dart::StackFrame*, bool*, bool*) ../../out/ReleaseASANX64/../../runtime/vm/stack_trace.cc:389:62
    #3 0x55b7944d8dfd in dart::StackTraceUtils::CollectFramesLazy(dart::Thread*, dart::GrowableObjectArray const&, dart::GrowableObjectArray const&, int, std::__2::function<void (dart::StackFrame*)>*, bool*) ../../out/ReleaseASANX64/../../runtime/vm/stack_trace.cc:476:24
    #4 0x55b7940cd24e in dart::CurrentSyncStackTraceLazy(dart::Thread*, long) ../../out/ReleaseASANX64/../../runtime/lib/stacktrace.cc:31:3
    #5 0x55b7940cd24e in dart::CurrentStackTrace(dart::Thread*, bool, long) ../../out/ReleaseASANX64/../../runtime/lib/stacktrace.cc:76:12
    #6 0x55b7941e7f94 in dart::Exceptions::CurrentStackTrace() ../../out/ReleaseASANX64/../../runtime/vm/exceptions.cc:748:10
    #7 0x55b7941e7f94 in dart::ThrowExceptionHelper(dart::Thread*, dart::Instance const&, dart::Instance const&, bool) ../../out/ReleaseASANX64/../../runtime/vm/exceptions.cc:823:22
    #8 0x55b7941e6e37 in dart::Exceptions::Throw(dart::Thread*, dart::Instance const&) ../../out/ReleaseASANX64/../../runtime/vm/exceptions.cc:987:3
    #9 0x55b79447aa5d in dart::DRT_HelperThrow(dart::Isolate*, dart::Thread*, dart::Zone*, dart::NativeArguments) ../../out/ReleaseASANX64/../../runtime/vm/runtime_entry.cc:1010:3
    #10 0x55b79447aa5d in dart::DRT_Throw(dart::NativeArguments) ../../out/ReleaseASANX64/../../runtime/vm/runtime_entry.cc:1008:1
    #11 0x7fc463143e11  (/b/s/w/ir/cache/builder/sdk/out/ReleaseASANX64/generated_compilations/dartkp-asan-linux-release-x64/tests_standalone_2_io_directory_test/out.aotsnapshot+0x2e11)
```

Because it's only failing on ASAN, I have approved the failures and not reverted the CL.

The tests
```
language_2/await/exceptions_test Crash (expected Pass)
language_2/vm/optimized_guarded_field_isolates_test/0 Crash (expected Pass)
language_2/vm/optimized_guarded_field_isolates_test/1 Crash (expected Pass)
language_2/vm/optimized_guarded_field_isolates_test/2 Crash (expected Pass)
lib_2/async/future_constructor_test Crash (expected Pass)
lib_2/async/future_foreach_test Crash (expected Pass)
lib_2/async/future_test Crash (expected Pass)
lib_2/async/futures_test Crash (expected Pass)
lib_2/async/stack_trace07_test Crash (expected Pass)
lib_2/async/stack_trace17_test Crash (expected Pass)
lib_2/isolate/function_send_test/0 Crash (expected Pass)
lib_2/isolate/function_send_test/1 Crash (expected Pass)
lib_2/isolate/illegal_msg_function_test/0 Crash (expected Pass)
lib_2/isolate/illegal_msg_function_test/1 Crash (expected Pass)
lib_2/isolate/illegal_msg_mirror_test/0 Crash (expected Pass)
lib_2/isolate/illegal_msg_mirror_test/1 Crash (expected Pass)
lib_2/isolate/message3_test/byteBuffer/0 Crash (expected Pass)
lib_2/isolate/message3_test/byteBuffer/1 Crash (expected Pass)
lib_2/isolate/message3_test/byteBuffer/2 Crash (expected Pass)
lib_2/isolate/message3_test/constInstance/0 Crash (expected Pass)
lib_2/isolate/message3_test/constInstance/1 Crash (expected Pass)
lib_2/isolate/message3_test/constInstance/2 Crash (expected Pass)
lib_2/isolate/message3_test/constList/0 Crash (expected Pass)
lib_2/isolate/message3_test/constList/1 Crash (expected Pass)
lib_2/isolate/message3_test/constList/2 Crash (expected Pass)
lib_2/isolate/message3_test/constList_identical/0 Crash (expected Pass)
lib_2/isolate/message3_test/constList_identical/1 Crash (expected Pass)
lib_2/isolate/message3_test/constList_identical/2 Crash (expected Pass)
lib_2/isolate/message3_test/constMap/0 Crash (expected Pass)
lib_2/isolate/message3_test/constMap/1 Crash (expected Pass)
    and 119 more tests
```
are failing on configurations
```
dartk-asan-linux-release-x64
dartkp-asan-linux-release-x64
```

**Comment by a-siva** [comment]
The CL https://github.com/dart-lang/sdk/commit/9978a246c10c6c6297bc8ac52fd34d3423f6071c has been reverted.
