### ISSUE TITLE
Failures on [cfe] Refactor ClassHierarchyBuilder to use Tuple for computation...dart migrate: Do not attempt to edit migration status icons for external files

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44716]
There are new test failures on [[cfe] Refactor ClassHierarchyBuilder to use Tuple for computation...dart migrate: Do not attempt to edit migration status icons for external files](https://github.com/dart-lang/sdk/compare/d97be105f8a7bf38d51a5bde04c9b9dec49ee638~...fabf3efda497f1a65f93c7c6eb76d47615ad1c5c).

The tests
```
language/super/no_such_method4_runtime_test DartkCrash (expected Pass)
language/super/no_such_method4_runtime_test DartkCrash (expected Pass)
language/super/no_such_method5_runtime_test DartkCrash (expected Pass)
language/super/no_such_method5_runtime_test DartkCrash (expected Pass)
language_2/super/no_such_method4_runtime_test DartkCrash (expected Pass)
language_2/super/no_such_method5_runtime_test DartkCrash (expected Pass)
```
are failing on configurations
```
dartkp-android-release-arm64
dartkp-android-release-arm_x64
dartkp-linux-debug-simarm-crossword
dartkp-linux-debug-x64
dartkp-linux-product-x64
dartkp-linux-release-simarm
dartkp-linux-release-simarm-crossword
dartkp-linux-release-simarm64
dartkp-linux-release-x64
dartkp-mac-release-simarm64
dartkp-obfuscate-linux-release-x64
dartkp-strong-linux-release-x64
dartkp-weak-asserts-linux-release-x64
dartkp-win-release-x64
```

```
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_language_super_no_such_method4_runtime_test/out.dill /b/s/w/ir/tests/language/super/no_such_method4_runtime_test.dart --packages=/b/s/w/ir/.packages -Ddart.vm.product=false --sound-null-safety
 exit code:
 253
 stderr:
 Invalid argument(s): Missing canonical name for Reference to A.foo
 #0      BinaryPrinter.writeNullAllowedReference (package:kernel/binary/ast_to_binary.dart:877:9)
 #1      BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1252:5)
 #2      Procedure.accept (package:kernel/ast.dart:2555:40)
 #3      BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:422:10)
 #4      BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:313:7)
 #5      BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1170:5)
 #6      Class.accept (package:kernel/ast.dart:1347:38)
 #7      BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:436:10)
 #8      BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:331:7)
 #9      BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1008:5)
 #10     Library.accept (package:kernel/ast.dart:610:38)
 #11     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:415:10)
 #12     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:723:9)
 #13     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:566:7)
 #14     Timeline.timeSync (dart:developer/timeline.dart:163:22)
 #15     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:548:14)
 #16     runCompiler (package:vm/kernel_front_end.dart:272:11)
 <asynchronous suspension>
 #17     runBatchModeCompiler.<anonymous closure> (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:57:22)
 <asynchronous suspension>
 #18     runBatch (package:kernel/src/tool/batch_util.dart:40:33)
 <asynchronous suspension>
 #19     runBatchModeCompiler (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:43:3)
 <asynchronous suspension>
 #20     main (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:32:5)
 <asynchronous suspension>
```

**Comment by johnniwinther** [comment]
A fix in progress: https://dart-review.googlesource.com/c/sdk/+/180141
