### ISSUE TITLE
CFE crash compiling nonsense program

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#44733]
On current dart head (5569f10236f522e62adea480c1de4de244074359) the following nonsense program riddled with errors crashes the compiler:

```
abstract class B extends A with C {}

mixin C on D {}

B get x => super.x;
void f() {
  switch (x.y.z) {
  }
}

abstract class E {}

abstract class D {
  E get y {}
}

abstract class A {
  F get y => super.y as F;
}
```

```
Crash when compiling crashme.dart,
at character offset 82:
NoSuchMethodError: The getter 'isPotentiallyNullable' was called on null.
Receiver: null
Tried calling: isPotentiallyNullable
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      TypeInferrerImpl.findInterfaceMember (package:front_end/src/fasta/type_inference/type_inferrer.dart:1001:22)
#2      InferenceVisitor._computePropertyGet (package:front_end/src/fasta/kernel/inference_visitor.dart:4572:46)
#3      InferenceVisitor.visitPropertyGet (package:front_end/src/fasta/kernel/inference_visitor.dart:5706:44)
#4      PropertyGet.accept1 (package:kernel/ast.dart:3722:9)
#5      TypeInferrerImpl._inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1841:27)
#6      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1874:40)
#7      InferenceVisitor.visitSwitchStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:6012:59)
#8      SwitchStatement.accept (package:kernel/ast.dart:7577:43)
#9      TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3610:24)
#10     InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:256:20)
#11     InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:277:30)
#12     Block.accept (package:kernel/ast.dart:7048:43)
#13     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3610:24)
#14     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:1917:39)
#15     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:988:28)
#16     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:957:14)
#17     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:995:7)
#18     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:360:5)
#19     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2865:14)
#20     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2641:14)
#21     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:502:14)
#22     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#23     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:461:14)
<asynchronous suspension>
#24     Loader.buildBodies (package:front_end/src/fasta/loader.dart:242:9)
<asynchronous suspension>
#25     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:398:7)
<asynchronous suspension>
#26     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#27     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#28     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#29     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#30     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#31     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#32     SingleShotCompilerWrapper.compileInternal ([...]/pkg/vm/bin/kernel_service.dart:376:11)
<asynchronous suspension>
#33     Compiler.compile.<anonymous closure> ([...]/pkg/vm/bin/kernel_service.dart:196:45)
<asynchronous suspension>
#34     _processLoadRequest ([...]/pkg/vm/bin/kernel_service.dart:842:37)
<asynchronous suspension>


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1000:7)
#1      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:360:5)
#2      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2865:14)
#3      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2641:14)
#4      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:502:14)
#5      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#6      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:461:14)
<asynchronous suspension>
#7      Loader.buildBodies (package:front_end/src/fasta/loader.dart:242:9)
<asynchronous suspension>
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:398:7)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#13     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#14     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#15     SingleShotCompilerWrapper.compileInternal ([...]/pkg/vm/bin/kernel_service.dart:376:11)
<asynchronous suspension>
#16     Compiler.compile.<anonymous closure> ([...]/pkg/vm/bin/kernel_service.dart:196:45)
<asynchronous suspension>
#17     _processLoadRequest ([...]/pkg/vm/bin/kernel_service.dart:842:37)
<asynchronous suspension>
```

/cc @johnniwinther

**Comment by melekhove** [comment]
There is another path to crash. The following modification of the original test program:

abstract class B extends A with C {}

mixin C on D {}

B get x => super.x;

abstract class E {}

abstract class D {
  E get y {}
}

abstract class A {
  F get y => super.y as F;
}

produces the following:

NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<void>(Instance of 'BinaryPrinter')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:394:10)
#2      BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1386:5)
#3      FunctionNode.accept (package:kernel/ast.dart:3088:38)
#4      BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:401:10)
#5      BinaryPrinter.writeOptionalFunctionNode (package:kernel/binary/ast_to_binary.dart:496:7)
#6      BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1253:5)
#7      Procedure.accept (package:kernel/ast.dart:2553:40)
#8      BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:422:10)
#9      BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:313:7)
#10     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1170:5)
#11     Class.accept (package:kernel/ast.dart:1340:38)
#12     BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:436:10)
#13     BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:331:7)
#14     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1008:5)
#15     Library.accept (package:kernel/ast.dart:603:38)
#16     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:415:10)
#17     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:723:9)
#18     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:566:7)
#19     Timeline.timeSync (dart:developer/timeline.dart:163:22)
#20     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:548:14)
#21     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:69:11)
#22     _processLoadRequest ([...]/pkg/vm/bin/kernel_service.dart:880:13)

**Comment by melekhove** [comment]
It seems that problem is related to the null safety.
The assertion in the `CombinedMemberSignatureBase._ensureCombinedMemberSignatureType()` (combined_member_signature.dart:335) fails.
If code contains `// @dart=2.9` then compiler works as expected and outputs normal compilation errors

**Comment by kinex** [comment]
I get this exception often while debugging my app with VS Code if I move mouse cursor over a variable name trying to see its value in tooltip:
```
Unhandled exception:
NoSuchMethodError: The getter 'isPotentiallyNullable' was called on null.
Receiver: null
Tried calling: isPotentiallyNullable
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      TypeInferrerImpl.findInterfaceMember (package:front_end/src/fasta/type_inference/type_inferrer.dart:1091:22)
#2      InferenceVisitor._computePropertyGet (package:front_end/src/fasta/kernel/inference_visitor.dart:4707:46)
#3      InferenceVisitor.visitPropertyGet (package:front_end/src/fasta/kernel/inference_visitor.dart:5848:44)
#4      PropertyGet.accept1 (package:kernel/ast.dart:4157:9)
#5      TypeInferrerImpl._inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1936:27)
#6      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1969:40)
#7      InferenceVisitor.visitReturnStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:5901:61)
#8      ReturnStatement.accept (package:kernel/ast.dart:9497:43)
#9      TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3874:24)
#10     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:2012:39)
#11     BodyBuilder.parseSingleExpression (package:front_end/src/fasta/kernel/body_builder.dart:1480:63)
#12     SourceLoader.buildExpression (package:front_end/src/fasta/source/source_loader.dart:539:21)
<asynchronous suspension>
#13     IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:1946:39)
<asynchronous suspension>
#14     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:1844:12)
<asynchronous suspension>
#15     FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:799:27)
<asynchronous suspension>
3
the Dart compiler exited unexpectedly.
Exited (1)
```
This forces me to restart the debug session. I don't see anything special on the code where it crashes (a normal assignment statement).

Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (6 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
