### ISSUE TITLE
../../runtime/vm/object.cc: 5414: error: expected: is_finalized()

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#44740]
```
out/ReleaseX64/dart --observe hello.dart
```

Go to the observatory URL, click on `metrics` under the `main` isolate. VM crashes:

```
Observatory listening on http://127.0.0.1:8181/PJCawZa5e5c=/
Hello, Dart!
vm-service: isolate(3515171005422995)  'main' has no debugger attached and is paused at exit.  Connect to Observatory at http://127.0.0.1:8181/PJCawZa5e5c=/ to debug.
../../runtime/vm/object.cc: 5414: error: expected: is_finalized()
version=2.12.0-edge.9fa2a462c5725355a10d0da9976e80b37693246b (be) (Thu Jan 21 17:20:10 2021 +0000) on "linux_x64"
pid=48578, thread=48615, isolate_group=main(0x55bf257c1c00), isolate=main(0x55bf2579e800)
isolate_instructions=55bf231b9ea0, vm_instructions=55bf231b9ea0
  pc 0x000055bf23433f7c fp 0x00007f18900fd710 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x000055bf231ba052 fp 0x00007f18900fd7f0 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x000055bf233d064c fp 0x00007f18900fd880 out/ReleaseX64/dart+0x1c2164c
  pc 0x000055bf23492a32 fp 0x00007f18900fd8b0 out/ReleaseX64/dart+0x1ce3a32
  pc 0x000055bf2348d8c2 fp 0x00007f18900fda20 dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)+0x3a2
  pc 0x000055bf2348e071 fp 0x00007f18900fda40 dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)+0x11
  pc 0x000055bf2337def5 fp 0x00007f18900fdc30 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x745
  pc 0x000055bf233a9926 fp 0x00007f18900fdca0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x146
  pc 0x000055bf233a9f1d fp 0x00007f18900fdd00 dart::MessageHandler::TaskCallback()+0x11d
  pc 0x000055bf234b8138 fp 0x00007f18900fdd80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x148
  pc 0x000055bf234b860c fp 0x00007f18900fddb0 dart::ThreadPool::Worker::Main(unsigned long)+0x5c
  pc 0x000055bf2342fc1d fp 0x00007f18900fde70 out/ReleaseX64/dart+0x1c80c1d
-- End of DumpStackTrace
Aborted
```

Stack trace from gdb:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c87537 in __GI_abort () at abort.c:79
#2  0x0000555556f5f05c in dart::Assert::Fail (this=<optimized out>, format=<optimized out>) at ../../runtime/platform/assert.cc:44
#3  0x000055555717564c in dart::Class::LookupFunctionAllowPrivate (this=0x5555582924f0, name=..., kind=dart::Class::kStatic) at ../../runtime/vm/object.cc:5414
#4  0x0000555557237a32 in dart::HandleDartMetricsList (thread=0x555558834000, js=0x7ffff317d910) at ../../runtime/vm/service.cc:3591
#5  dart::GetIsolateMetricList (thread=0x555558834000, js=0x7ffff317d910) at ../../runtime/vm/service.cc:3651
#6  0x00005555572328c2 in dart::Service::InvokeMethod (I=0x55555813c800, msg=..., parameters_are_dart_objects=96) at ../../runtime/vm/service.cc:927
#7  0x0000555557233071 in dart::Service::HandleIsolateMessage (isolate=0x55555813c800, msg=...) at ../../runtime/vm/service.cc:975
#8  0x0000555557122ef5 in dart::IsolateMessageHandler::HandleMessage (this=0x55555815c870, message=...) at ../../runtime/vm/isolate.cc:1344
#9  0x000055555714e926 in dart::MessageHandler::HandleMessages (this=<optimized out>, ml=0x7ffff317dcb8, allow_normal_messages=false, allow_multiple_normal_messages=false)
    at ../../runtime/vm/message_handler.cc:233
#10 0x000055555714ef1d in dart::MessageHandler::TaskCallback (this=0x55555815c870) at ../../runtime/vm/message_handler.cc:415
#11 0x000055555725d138 in dart::ThreadPool::WorkerLoop (this=0x5555581623c0, worker=0x5555581b18f0) at ../../runtime/vm/thread_pool.cc:158
#12 0x000055555725d60c in dart::ThreadPool::Worker::Main (args=93825038751984) at ../../runtime/vm/thread_pool.cc:323
#13 0x00005555571d4c1d in dart::ThreadStart (data_ptr=<optimized out>) at ../../runtime/vm/os_thread_linux.cc:153
#14 0x00007ffff7f73ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007ffff7d5fdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

/cc @bkonyi @rmacnak-google

**Comment by uppet** [comment]
I have sent a patch with git-cl upload -s in
https://dart-review.googlesource.com/c/sdk/+/180300

**Comment by bkonyi** [comment]
Closed by https://github.com/dart-lang/sdk/issues/44859.
