### ISSUE TITLE
External field not equivalent to getter/setter pair for internal patch system.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#44748]
I changed `external bool get echoMode; external set echoMode(bool value);` in `dart:io` to be `external bool echoMode;`.

This should mean the same thing, because an external field declaration is equivalent to an external getter and setter declaration.
However, the Dart SDK *patch* system disagreed, and wouldn't allow me to patch the getter/setter implementation onto the declaration.
```
Crash when compiling dart:async/async_error.dart,                                                                                                              
at character offset null:                                                                                                                                      
../../tools/sdks/dart-sdk/lib/io/stdio.dart:131:17: Internal problem: Unsupported operation: 'SourceFieldBuilder.applyPatch'.                                  
  external bool lineMode;                                                                                                                                      
                ^                                                                                                                                              
#0      internalProblem (package:front_end/src/fasta/problems.dart:48:3)                                                                                       
#1      unsupported (package:front_end/src/fasta/problems.dart:75:10)                                                                                          
#2      BuilderImpl.applyPatch (package:front_end/src/fasta/builder/builder.dart:294:5)                                                                        
#3      ClassBuilderImpl.applyPatch.<anonymous closure> (package:front_end/src/fasta/builder/class_builder.dart:810:18)                       
```
(See: https://dart-review.googlesource.com/c/sdk/+/178985/4, all the errors!)

The one problem I can see is that the argument name of the setter might not match, but we should fix the patch system to allow that, otherwise `external type name;` won't really be equivalent to the getter and setter.

**Comment by johnniwinther** [comment]
The problem is that patching has never been supported for fields. This is a(nother) good reason to start supporting it.

Are you blocked on this or can you use external getter/setter for now?

**Comment by lrhn** [comment]
I'll just revert to a getter/setter pair for now.

Patching hasn't been supported for fields because only things defined by code can be declared external. If something is declared as a field (instance variable), then it also has a memory slot, which patching won't affect. And you couldn't declare a field as external ... until we allowed `external type name;` and `abstract type name;` as declarations, but those were explicitly *not* variable declarations, just shorthands for external/abstract getter/setter declarations.

Patching is an internal-only feature which isn't formally specified. We could allow an instance variable to be an implementation of an external getter and setter, but it's not particularly important. It just worries me that patching can distinguish external getter/setter declarations from the (by specification) equivalent external variable declaration.

**Comment by johnniwinther** [comment]
It's not that external/abstract fields declared in patches are recognized differently - just that `applyPatch` isn't supported on a `SourceFieldBuilder` which is the object responsible for doing the encoding of an external/abstract field as a getter/setter pair.

Note: We already have a use case in the VM for supporting patching on fields which is currently worked around by a hack.

**Comment by mkustermann** [comment]
I'm seeing a similar failure of "Internal problem: Unsupported operation: 'SourceFieldBuilder.applyAugmentation'." in a macro test today, see [log](https://dart-ci.appspot.com/log/vm-reload-rollback-linux-debug-x64/vm-reload-rollback-linux-debug-x64/339/language/macros/augment/class_definition_macro_test)
```
--- Command "vm" (took 07.000238s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --hot-reload-test-mode --sound-null-safety -Dtest_runner.configuration=vm-reload-linux-release-x64 --enable-experiment=macros --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/language/macros/augment/class_definition_macro_test.dart

exit code:
-6

stderr:
../../runtime/vm/dart_api_impl.cc: 6222: error: An error occurred in the CFE while acking the most recent compilation results: Crash when compiling:
tests/language/macros/augment/class_definition_macro_test.dart:31:22: Internal problem: Unsupported operation: 'SourceFieldBuilder.applyAugmentation'.
  abstract final int x;
                     ^

#0      internalProblem (package:front_end/src/fasta/problems.dart:52:5)
#1      unsupported (package:front_end/src/fasta/problems.dart:85:10)
#2      BuilderImpl.applyAugmentation (package:front_end/src/fasta/builder/builder.dart:350:5)
#3      MergedScope._addBuilderToMergedScope (package:front_end/src/fasta/scope.dart:1404:25)
#4      MergedScope._addAugmentationScope.<anonymous closure> (package:front_end/src/fasta/scope.dart:1521:7)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#6      Scope.forEachLocalMember (package:front_end/src/fasta/scope.dart:579:13)
#7      MergedScope._addAugmentationScope (package:front_end/src/fasta/scope.dart:1516:11)
#8      MergedClassMemberScope.addAugmentationScope (package:front_end/src/fasta/scope.dart:1675:5)
#9      SourceClassBuilder.applyAugmentation (package:front_end/src/fasta/source/source_class_builder.dart:579:19)
#10     MergedScope._addBuilderToMergedScope (package:front_end/src/fasta/scope.dart:1404:25)
#11     MergedScope._addAugmentationScope.<anonymous closure> (package:front_end/src/fasta/scope.dart:1521:7)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#13     Scope.forEachLocalMember (package:front_end/src/fasta/scope.dart:579:13)
#14     MergedScope._addAugmentationScope (package:front_end/src/fasta/scope.dart:1516:11)
#15     MergedLibraryScope.addAugmentationScope (package:front_end/src/fasta/scope.dart:1571:5)
#16     SourceLibraryBuilder.applyAugmentations (package:front_end/src/fasta/source/source_library_builder.dart:4648:17)
#17     KernelTarget._buildForPhase1 (package:front_end/src/fasta/kernel/kernel_target.dart:359:29)
<asynchronous suspension>
#18     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:606:9)
<asynchronous suspension>
#19     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#20     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:596:12)
<asynchronous suspension>
#21     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:371:23)
<asynchronous suspension>
#22     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139:3)
<asynchronous suspension>
#23     IncrementalCompiler.reject (package:vm/incremental_compiler.dart:194:5)
<asynchronous suspension>
#24     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:852:11)
<asynchronous suspension>

version=3.4.0-edge (main) (Unknown timestamp) on "linux_x64"
pid=1224122, thread=1224122, isolate_group=main(0x55de54eeb5f0), isolate=main(0x55de54eecf40)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=55de5343c140, vm_instructions=55de5343c140
fp=7ffdd3e5ced0, sp=7ffdd3e5cd98, pc=55de5364256c
  pc 0x000055de5364256c fp 0x00007ffdd3e5ced0 dart::Profiler::DumpStackTrace+0x7c
  pc 0x000055de5343c334 fp 0x00007ffdd3e5cfb0 dart::Assert::Fail+0x84
  pc 0x000055de538aed5c fp 0x00007ffdd3e5d0a0 Dart_CompileToKernel+0xfc
  pc 0x000055de5341c647 fp 0x00007ffdd3e5d110 dart::bin::DFE::CompileAndReadScript+0x57
  pc 0x000055de5341f9c4 fp 0x00007ffdd3e5d1b0 dart::bin::IsolateSetupHelper+0x1b4
  pc 0x000055de5341dfe8 fp 0x00007ffdd3e5d290 dart::bin::CreateIsolateGroupAndSetupHelper+0x358
  pc 0x000055de5341da07 fp 0x00007ffdd3e5d350 dart::bin::RunMainIsolate+0xd7
  pc 0x000055de5341e993 fp 0x00007ffdd3e5d490 dart::bin::main+0x6c3
  pc 0x000055de5341d8fd fp 0x00007ffdd3e5d4b0 main+0xd
-- End of DumpStackTrace

--- Re-run this test:
python3 tools/test.py -n vm-reload-linux-release-x64 language/macros/augment/class_definition_macro_test

```


Approving the tests
```
language/macros/augment/class_definition_macro_test Crash (expected Pass)
language/macros/json/json_serializable_test Crash (expected Pass)
```
on
```
vm-reload-linux-debug-x64
vm-reload-linux-release-x64
vm-reload-rollback-linux-debug-x64
vm-reload-rollback-linux-release-x64
```

**Comment by johnniwinther** [comment]
Augmentation (=patching) of fields is still not supported.
