### ISSUE TITLE
completionItem/resolve failed: staticType called on null

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#44763]
## Error

```
[Error - 11:42:39 PM] Request completionItem/resolve failed.
  Message: An error occurred while handling completionItem/resolve request
  Code: -32001 
[Error - 11:42:39 PM] An error occurred while handling completionItem/resolve request: NoSuchMethodError: The getter 'staticType' was called on null.
Receiver: null
Tried calling: staticType
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      FfiVerifier._validateRefPropertyAccess (package:analyzer/src/generated/ffi_verifier.dart:795:39)
#2      FfiVerifier.visitPropertyAccess (package:analyzer/src/generated/ffi_verifier.dart:226:11)
#3      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8448:49)
#4      PropertyAccessImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8452:14)
#5      RecursiveAstVisitor.visitPropertyAccess (package:analyzer/dart/ast/visitor.dart:1151:10)
#6      FfiVerifier.visitPropertyAccess (package:analyzer/src/generated/ffi_verifier.dart:230:11)
#7      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8448:49)
#8      AssignmentExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:719:20)
#9      RecursiveAstVisitor.visitAssignmentExpression (package:analyzer/dart/ast/visitor.dart:653:10)
#10     AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:715:49)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#12     CascadeExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1258:22)
#13     RecursiveAstVisitor.visitCascadeExpression (package:analyzer/dart/ast/visitor.dart:695:10)
#14     CascadeExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1253:49)
#15     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10561:19)
#16     RecursiveAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1308:10)
#17     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10555:49)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#19     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10661:16)
#20     RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1314:10)
#21     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10655:15)
#22     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10709:20)
#23     RecursiveAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:1320:10)
#24     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10705:15)
#25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#26     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#27     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:671:10)
#28     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#29     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1042:13)
#30     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:677:10)
#31     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#32     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5010:12)
#33     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:929:10)
#34     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5004:49)
#35     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4873:26)
#36     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:917:10)
#37     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4866:49)
#38     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#39     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2141:21)
#40     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:731:10)
#41     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#42     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:419:10)
#43     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:150:7)
#44     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#45     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:149:11)
#46     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:12)
#47     AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1319:63)
#48     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#49     AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1296:20)
#50     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1249:14)
#51     _rootRun (dart:async/zone.dart:1354:13)
#52     _CustomZone.run (dart:async/zone.dart:1258:19)
#53     _runZoned (dart:async/zone.dart:1788:10)
#54     runZoned (dart:async/zone.dart:1710:10)
#55     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#56     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1248:40)
#57     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:934:33)
#58     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2018:24)
<asynchronous suspension>

#0      AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1349:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#2      AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1296:20)
#3      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1249:14)
#4      _rootRun (dart:async/zone.dart:1354:13)
#5      _CustomZone.run (dart:async/zone.dart:1258:19)
#6      _runZoned (dart:async/zone.dart:1788:10)
#7      runZoned (dart:async/zone.dart:1710:10)
#8      NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#9      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1248:40)
#10     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:934:33)
#11     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2018:24)
<asynchronous suspension>

[Error - 11:42:39 PM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\example\bluetooth.dart
[Error - 11:42:39 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\example\bluetooth.dart
[Error - 11:42:39 PM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\example\bluetooth.dart
[Error - 11:42:39 PM] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\example\bluetooth.dart
[Error - 11:42:44 PM] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\example\bluetooth.dart
...
```

## Dart Version
```
[C:\Windows\System32] dart --version
Dart SDK version: 2.12.0-253.0.dev (dev) (Fri Jan 22 08:36:17 2021 -0800) on "windows_x64"
```

**Comment by mraleph** [comment]
This is most likely related to your most recent changes @dcharkes and might require cherry picks.

**Comment by dcharkes** [comment]
@timsneath what code snippet caused this?

I've created https://dart-review.googlesource.com/c/sdk/+/180821 to address this specific NPE and a bunch of other possible ones.
