### ISSUE TITLE
"NoSuchMethodError: The getter 'lexeme' was called on null" from analysis server for invalid code

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#44815]
Using latest Flutter master, given the following code:

```dart
class MusicLibrary extends StatelessWidget {
  @override
  Widget build(BuildContext context) => T ListView.builder( // Typing after the "T" here
      itemCount: files?.length ?? 0,
      itemBuilder: (context, index) {
        final file = files[index];
        return InkWell(
          onTap: () => onSelectFile(file),
          child: Container(
            color: file == selectedFile ? Colors.amber : null,
            child: Text(file),
          ),
        );
      });
}
```

I was typing after the "T" where the comment is (trying to wrap another widget around the `ListView.builder`) and received this error from the server. It occurred for multiple different types of requests that tried to call `_getParametersString()` (stacks below are for highlighting occurrences and completion).

## Occurrences highlighting

```
[Error - 12:47:13 PM] An error occurred while handling textDocument/documentHighlight request: NoSuchMethodError: The getter 'lexeme' was called on null.
Receiver: null
Tried calling: lexeme
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ToSourceVisitor.visitPropertyAccess (package:analyzer/src/dart/ast/to_source_visitor.dart:933:32)
#2      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8448:49)
#3      ToSourceVisitor._writeOperand (package:analyzer/src/dart/ast/to_source_visitor.dart:1178:15)
#4      ToSourceVisitor.visitBinaryExpression (package:analyzer/src/dart/ast/to_source_visitor.dart:207:5)
#5      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:967:49)
#6      AstNodeImpl.toSource (package:analyzer/src/dart/ast/ast.dart:837:5)
#7      ParameterElementImpl.defaultValueCode (package:analyzer/src/dart/element/element.dart:6042:39)
#8      ParameterElementMixin.appendToWithoutDelimiters (package:analyzer/src/dart/element/element.dart:6360:9)
#9      _getParametersString (package:analysis_server/plugin/protocol/protocol_dart.dart:170:15)
#10     convertElement (package:analysis_server/plugin/protocol/protocol_dart.dart:15:27)
#11     addDartOccurrences.<anonymous closure> (package:analysis_server/src/domains/analysis/occurrences_dart.dart:18:25)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#13     addDartOccurrences (package:analysis_server/src/domains/analysis/occurrences_dart.dart:16:27)
#14     DocumentHighlightsHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_document_highlights.dart:37:7)
#15     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#16     DocumentHighlightsHandler.handle (package:analysis_server/src/lsp/handlers/handler_document_highlights.dart:35:19)
<asynchronous suspension>
#17     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:183:22)
<asynchronous suspension>
#18     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:301:26)
<asynchronous suspension>
```

## Completion

```
[Error - 12:47:56 PM] An error occurred while handling textDocument/completion request: NoSuchMethodError: The getter 'lexeme' was called on null.
Receiver: null
Tried calling: lexeme
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ToSourceVisitor.visitPropertyAccess (package:analyzer/src/dart/ast/to_source_visitor.dart:933:32)
#2      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8448:49)
#3      ToSourceVisitor._writeOperand (package:analyzer/src/dart/ast/to_source_visitor.dart:1178:15)
#4      ToSourceVisitor.visitBinaryExpression (package:analyzer/src/dart/ast/to_source_visitor.dart:207:5)
#5      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:967:49)
#6      AstNodeImpl.toSource (package:analyzer/src/dart/ast/ast.dart:837:5)
#7      ParameterElementImpl.defaultValueCode (package:analyzer/src/dart/element/element.dart:6042:39)
#8      ParameterElementMixin.appendToWithoutDelimiters (package:analyzer/src/dart/element/element.dart:6360:9)
#9      _getParametersString (package:analysis_server/plugin/protocol/protocol_dart.dart:170:15)
#10     convertElement (package:analysis_server/plugin/protocol/protocol_dart.dart:15:27)
#11     SuggestionBuilder._createSuggestion (package:analysis_server/src/services/completion/dart/suggestion_builder.dart:1016:26)
#12     SuggestionBuilder.suggestConstructor (package:analysis_server/src/services/completion/dart/suggestion_builder.dart:365:10)
#13     _LocalVisitor.declaredClass (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:225:21)
#14     LocalDeclarationVisitor._visitCompilationUnit.<anonymous closure> (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:234:9)
#15     ListMixin.forEach (dart:collection/list.dart:86:13)
#16     LocalDeclarationVisitor._visitCompilationUnit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:232:23)
#17     LocalDeclarationVisitor.visitCompilationUnit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:102:5)
#18     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#19     LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:194:18)
#20     LocalDeclarationVisitor.visitClassDeclaration (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:97:5)
#21     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#22     LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:194:18)
#23     LocalDeclarationVisitor.visitMethodDeclaration (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:181:5)
#24     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#25     LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:194:18)
#26     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:324:45)
#27     GeneralizingAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:271:7)
#28     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3519:15)
#29     LocalDeclarationVisitor.visit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:68:12)
#30     LocalReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:70:24)
#31     DartCompletionManager.computeSuggestions.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_manager.dart:154:31)
#32     DartCompletionManager.computeSuggestions.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_manager.dart:153:11)
#33     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:157:29)
#34     DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:151:27)
<asynchronous suspension>
#35     CompletionHandler._getServerDartItems.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:250:35)
<asynchronous suspension>
#36     CompletionPerformance.runRequestOperation.<anonymous closure> (package:analysis_server/src/services/completion/completion_performance.dart:61:16)
<asynchronous suspension>
#37     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:157:14)
<asynchronous suspension>
#38     CompletionHandler._getServerDartItems (package:analysis_server/src/lsp/handlers/handler_completion.dart:225:12)
<asynchronous suspension>
#39     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#40     CompletionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:145:11)
<asynchronous suspension>
#41     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:183:22)
<asynchronous suspension>
#42     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:301:26)
<asynchronous suspension>
```

**Comment by bwilkerson** [comment]
I am able to reproduce the bug on master under the debugger. I'm not sure what the best solution is, but I can describe what's happening. The parser is recovering by building an AST for the following:
```
class MusicLibrary extends StatelessWidget {
  @override
  Widget build(BuildContext context) => T;

  ListView.builder(
      itemCount: files length ?? 0,
      itemBuilder: null);
}
```
That is, a class declaration with two members. The first member is a method declaration named `build` whose body consists of `T`. The second is a constructor declaration named `ListView.builder` and whose parameter list contains two named parameters. The first named parameter has a default value that's a binary expression with the operator `??` and a left operand that's a property access with no operator.

It's possible that we could recover better by synthesizing a binary operator after `T`, but we'd have to do a _lot_ of lookahead at that point to avoid making recovery much worse for other kinds of code. Basically we'd need to determine that the code starting with `ListView.builder(` is an expression rather than a declaration, and it isn't clear that that's even possible.

@scheglov Stepping through in the debugger, it looks like the property access node has an operator of `?.` when it's being built from `AstBuilder` (which happens 4 times, by the way) and `AstCloner`, but has a `null` operator when built by `AstBinaryReader._readPropertyAccess`. I'll note that the constructor declaration's parameter list, while containing two named parameters, has no `leftDelimiter` or `rightDelimiter`, and that might be what's causing the bug.

@jensjoha For ideas of possible ways to improve recovery.

**Comment by scheglov** [comment]
I can reproduce the issue on a slightly smaller and "more valid" code:
```dart
void f({a: foo?.bar}) {}
```

It looks like a bug in the AST writer / reader - we probably don't have support for `?.` operator.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/182002 should fix the exception.

At some point I'd like to use these binary ASTs wider - parse only once, write all tokens to be able to read the identical AST, read AST from binary for re-linking, etc. I have to balance this with heap consumption though - keeping all tokens means bigger binary size, and more unique Token instances. We might save some heap by other means, e.g. don't store documentation tokens for Cider.

**Comment by DanTup** [comment]
Yep, that fixed it. Thanks!
