### ISSUE TITLE
Directory.listSync does not return files

### ISSUE THREAD

**Issue by wim07101993** [dart-lang/sdk#44848]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Dart core libraries ("dart:async", "dart:io", etc.)

SDK:
Dart SDK version: 2.10.3 (stable) (Tue Oct 27 14:44:30 2020 +0100) on "windows_x64"

Running on Google Pixel 4a Android 11 (Flutter)

## Issue

While building an application which needs to be able to browse through local files. I think I stumped on a bug. The Direcotry.listSync (and also the Directory.list) methods do not return any files.

I have checked, there are files in the Download folder and I have tried in other directories as well.

Directories are listed, but files are not.

## Steps to Reproduce
```dart
import 'dart:io';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final files = Directory('/storage/emulated/0/Download').listSync();
    print(files);
    return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
          itemCount: files.length,
          itemBuilder: (context, i) => Text(files[i].path),
        ),
      ),
    );
  }
}
```

## Related issue on flutter github:
[https://github.com/flutter/flutter/issues/75268](https://github.com/flutter/flutter/issues/75268)

**Comment by 0htls** [comment]
Scoped storage enabled in Android 11

**Comment by sortie** [comment]
Are you able to open any of the files you know are in the directory by their absolute path?

**Comment by wim07101993** [comment]
No, I get a `FileSystemException`

Code:
```dart
import 'dart:io';

void main() {
  final file = File('/storage/emulated/0/Documents/test.txt');
  print(file.readAsStringSync());
}
```
Exception:
```
Unhandled exception:
FileSystemException: Cannot open file, path = '/storage/emulated/0/Documents/test.txt' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      main (file:///C:/Users/wvl/source/repos/FileX/tool/main.dart:11:14)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

The file does exist though:
<img src="https://user-images.githubusercontent.com/23017340/107244189-0af80b80-6a2e-11eb-855e-93ce5fac96e3.jpg" width="200">

PS: this does work when I try it in on windows in terminal:
```
➜  tool git:(master) ✗ dart .\main.dart ./main.dart
import 'dart:io';

void main(List<String> args) {
  File file;
  if (args?.isNotEmpty != true) {
    file = File('/storage/emulated/0/Documents/test.txt');
  } else {
    file = File(args[0]);
  }

  print(file.readAsStringSync());
}
```

**Comment by sortie** [comment]
You're getting a permission denied error for the file, not that it doesn't exist. It seems more probable that your app permissions are somehow wrong rather than Flutter/Dart being this broken? I don't know much about Flutter and Android permissions though, so I am not quite able to help you. Note that you may have a different set of app permissions if you're using a debug version of your app.

**Comment by wim07101993** [comment]
Well, as you can see in the image, all file permissions are accepted. I have added all storage permissions to the `AndroidManifest`:
```xml
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"
        tools:ignore="ScopedStorage" />
```

If this is not the place to ask this question and the flutter repo isn't either, where should I post it?

**Comment by sortie** [comment]
(Ah, not saying this is the wrong place to ask the question, just that I'm not the right person to triage this issue. I'm not currently responsible for the component in question, I was just dropping in with some drive by comments in case it's helpful.)

**Comment by mraleph** [comment]
I don't think you can read files in Download directory like this in recent versions of Android, this has been restricted. See warning at [Environment.getExternalStoragePublicDirectory](https://developer.android.com/reference/android/os/Environment#getExternalStoragePublicDirectory(java.lang.String)). You need to use one of the suggested alternatives (some of them have corresponding flutter plugins, e.g. https://pub.dev/packages/flutter_document_picker).

**Comment by spekary** [comment]
I had this problem too in Android 8 and Flutter 2.0. Was trying to enumerate the applications files directory as reported by `getExternalFilesDir`. Switching to Android 10, dir.listSync suddenly started working.

**Comment by dsdsharma** [comment]
Did you found any working solution? I am trying to access the storage for android 11 but cant access it. 
Thanks

**Comment by spekary** [comment]
I switched to getExternalStorageDirectory.

**Comment by piratkin** [comment]
I have the same problem, if I rename the file to png / jpeg / pdf / ... then it appears in the list.
[...](https://github.com/andyduke/filesystem_picker/issues/25)

**Comment by ANDRUXUIS** [comment]
in android 11 and above the permission to the storage is limited by default to read media files only 
in order to have access to all files you need to go to your device settings
**Settings > Privacy > Permission manager > Files and media**
and select your app and click 
**Allowed for all files**

don't forget to set permission tags in your AndroidManifest.xml file

**Comment by huynguyennovem** [comment]
Same error on Android 11  (Pixel 3a):

- Code implemented:
```dart
List<StorageInfo> storageInfo = await PathProviderEx.getStorageInfo();
    var root = storageInfo[0].rootDir;
    var fm = FileManager(root: Directory(root));
    final files = await fm.filesTree(excludedPaths: ["/storage/emulated/0/Android"], extensions: ["png"]);
```

- The error:
```
FileSystemException: Directory listing failed, path = '/storage/emulated/0/Android/obb' (OS Error: Permission denied, errno = 13
```

As I debugged, the checking `excludedPaths != null` is performed after `var contents = root.listSync(recursive: true, followLinks: followLinks);`:
```dart
Future<List<Directory>> dirsTree(
      {List<String> excludedPaths,
      bool followLinks: false,
      bool excludeHidden: false,
      FileManagerSorting sortedBy}) async {
    List<Directory> dirs = [];

    try {
      var contents = root.listSync(recursive: true, followLinks: followLinks);
      if (excludedPaths != null) {
....
```

**Comment by esagulto** [comment]
> in android 11 and above the permission to the storage is limited by default to read media files only in order to have access to all files you need to go to your device settings **Settings > Privacy > Permission manager > Files and media** and select your app and click **Allowed for all files**
> 
> don't forget to set permission tags in your AndroidManifest.xml file
> 
> for more info: https://developer.android.com/about/versions/11/privacy/storage

This one worked for me. Thanks @ABDERRAHMANE-OUALI .

**Comment by PatrickOjiambo** [comment]
For android 11 plus, there is a security update. If you are using flutter's permission_handler package and you want to access files in the android filesystem, then you have to use "manageExternalStorage" instead of "storage" type of the Permission class. It's all about security.
to be clear, do this:
`await Permission.manageExternalStorage.request()`
instead of:
`await Permission.storage.request()`.
Here is a code sample.
`var permission = await Permission.manageExternalStorage.status;
  List<String> files = [];
  if (permission.isDenied) {
    debugPrint("Permission is denied");
    await Permission.manageExternalStorage.request();
  }
  if (permission.isGranted) {
    Directory directory = Directory('/storage/emulated/0/Documents');
Do something
    }`.
Remember "manageExternalStorage" replaces "storage" if you want to access the filesystem.
If this helps you, remember to mark it as answer. Dart isn't the problem, you aren't asking the permissions correctly. I did it too.

**Comment by rohinton-collins** [comment]
@PatrickOjiambo 
I don't think this is the answer. Google restrict the use of MANAGE_EXTERNAL_STORAGE to apps like virus scanners, file managers etc. Apps that need broad access to all files without user interaction. I am building a cloud-based file storage app and they have questioned why I need it. They argue that I should be able to import/export files with user interaction and by using the existing Scoped Access APIs, so you may have problems getting your app approved if you try to use that permission. I am still looking for a solution however for Android 12 and above where I need to read access to the files in a chosen directory. Perhaps https://pub.dev/packages/flutter_document_picker is the answer.

**Comment by cyberalt1** [comment]
Please re-open, this is the single biggest issue in all of flutter and a dealbreaker for anyone who wants to write an app in it.

**Comment by rohinton-collins** [comment]
I found an answer - building a platform channel which uses the Scoped Storage API and gets the user to select a folder, which is necessary in order to be able to list the directory contents.

AndroidManifest.xml:
```
...
        <activity android:name=".DirectoryPickerActivity"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            />
...
```

Dart File code:
```
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:zcloud/platform/file_system/api/i_platform_file.dart';

/// Android-specific. uses a platform channel which calls Scoped Storage APIs
/// so that we can list directory contents and read files from a selected folder
class AndroidPlatformFile implements IPlatformFile {
  AndroidPlatformFile({required this.uri, required String name, required int size, required DateTime modifiedDate})
      : _name = name,
        _size = size,
        _modifiedDate = modifiedDate;

  final String uri;
  final String _name;
  final int _size;
  final DateTime _modifiedDate;
  static const methodChannel = MethodChannel('com.yourcompany.app/documents');

  @override
  String get name => _name;

  @override
  int size() => _size;

  @override
  DateTime modifiedDate() => _modifiedDate;

  @override
  Stream<List<int>> openRead({int? startByte}) async* {
    const int chunkSize = 1024 * 1024; // 1MB
    int offset = startByte ?? 0;
    bool moreData = true;

    while (moreData) {
      try {
        final Map<String, dynamic> arguments = {
          'uri': uri,
          'offset': offset,
          'chunkSize': chunkSize,
        };
        final List<int>? chunk = await methodChannel.invokeMethod('getFileChunk', arguments);
        if (chunk == null || chunk.isEmpty) {
          moreData = false;
        } else {
          yield Uint8List.fromList(chunk);
          offset += chunk.length;
        }
      } on PlatformException catch (e) {
        if (kDebugMode) print('Failed to get file chunk: ${e.message}');
        moreData = false;
      }
    }
  }
}
```

Dart Folder code:
```
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:zcloud/extensions/target_platform_extensions.dart';
import 'package:zcloud/platform/file_system/file/android_platform_file.dart';
import 'package:zcloud/platform/file_system/file/io_platform_file.dart';
import 'package:zcloud/platform/file_system/api/i_platform_file.dart';
import 'package:zcloud/platform/file_system/api/i_platform_folder.dart';
import 'package:path/path.dart' as p;

class IOPlatformFolder implements IPlatformFolder {
  const IOPlatformFolder({this.path, this.uri});
  final String? path;
  final String? uri; // Android
  static const methodChannel = MethodChannel('com.yourcompany.app/documents');

  @override
  void dispose() {
    if (TargetPlatformExtensions.isIOS) {
      methodChannel.invokeMethod('stopAccessingSecurityScopedResource');
    }
  }

  @override
  Future<List<IPlatformFile>> files() async {
    if (path != null) {
      final directory = Directory(path!);
      return (await directory.list().toList()).whereType<File>().map((file) => IOPlatformFile(file)).toList();
    } else {
      // Android
      return (await methodChannel.invokeMethod('listFiles', {'uri': uri!}))
          .map(
            (file) => AndroidPlatformFile(
              uri: file['uri'],
              name: file['name'],
              size: file['size'],
              modifiedDate: DateTime.fromMillisecondsSinceEpoch(file['modified']),
            ),
          )
          .cast<IPlatformFile>()
          .toList();
    }
  }

  @override
  Future<List<IPlatformFolder>> folders() async {
    if (path != null) {
      final directory = Directory(path!);
      return (await directory.list().toList()).whereType<Directory>().map((directory) => IOPlatformFolder(path: directory.path)).toList();
    } else {
      // Android
      return (await methodChannel.invokeMethod('listDirectories', {'uri': uri!}))
          .map((folder) => IOPlatformFolder(uri: folder))
          .cast<IPlatformFolder>()
          .toList();
    }
  }

  @override
  String get name {
    if (path != null) return p.basename(path!);
    return Uri.decodeFull(uri!).split(RegExp('[/:]')).last; // Android
  }
}
```

DirectoryPickerActivity.kt
```
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.result.ActivityResult
import androidx.activity.result.contract.ActivityResultContracts

class DirectoryPickerActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val intent = Intent(Intent.ACTION_OPEN_DOCUMENT_TREE)
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)
        resultLauncher.launch(intent)
    }

    private val resultLauncher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result: ActivityResult ->
        val returnIntent = Intent()
        if (result.resultCode == RESULT_OK) {
            val uri: Uri? = result.data?.data
            if (uri != null) {
                contentResolver.takePersistableUriPermission(uri, Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION)
                returnIntent.putExtra("getDirectoryUri", uri.toString())
            }
        }
        setResult(RESULT_OK, returnIntent)
        finish()
    }
}
```

MainActivity.kt
```
package com.yourcompany.app

import android.app.Activity
import android.content.Intent
import android.net.Uri
import androidx.documentfile.provider.DocumentFile
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

class MainActivity : FlutterActivity() {
    private val channel = "com.yourcompany.app/documents"
    private lateinit var result: MethodChannel.Result

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, channel)
            .setMethodCallHandler { call, result ->
                when (call.method) {
                    "getDirectoryPath" -> {
                        this.result = result
                        val intent = Intent(this, DirectoryPickerActivity::class.java)
                        startActivityForResult(intent, PICK_DIRECTORY_REQUEST_CODE)
                    }
                    "listDirectories" -> {
                        val uriString = call.argument<String>("uri")!!
                        val uri = Uri.parse(uriString)
                        val directories = listDirectories(uri)
                        result.success(directories)
                    }
                    "listFiles" -> {
                        val uriString = call.argument<String>("uri")!!
                        val uri = Uri.parse(uriString)
                        val files = listFiles(uri)
                        result.success(files)
                    }
                    "getFileChunk" -> {
                        val uriString = call.argument<String>("uri")!!
                        val offset = call.argument<Int>("offset")!!
                        val chunkSize = call.argument<Int>("chunkSize")!!
                        val uri = Uri.parse(uriString)
                        val chunk = readFileChunk(uri, offset, chunkSize)
                        if (chunk != null) {
                            result.success(chunk)
                        } else {
                            result.error("READ_ERROR", "Failed to read file chunk", null)
                        }
                    }
                    else -> result.notImplemented()
                }
            }
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == PICK_DIRECTORY_REQUEST_CODE && resultCode == Activity.RESULT_OK) {
            val pickedDirectoryUri = data?.getStringExtra("getDirectoryUri")
            if (pickedDirectoryUri != null) {
                result.success(pickedDirectoryUri)
            } else {
                result.error("NO_DIRECTORY_URI", "No directory URI found", null)
            }
        }
    }

    private fun listDirectories(uri: Uri): List<String> {
        val directory = DocumentFile.fromTreeUri(this, uri)
        val directories = mutableListOf<String>()

        if (directory != null && directory.isDirectory) {
            for (item in directory.listFiles()) {
                if (item.isDirectory) {
                    directories.add(item.uri.toString())
                }
            }
        }

        return directories
    }

    private fun listFiles(uri: Uri): List<Map<String, Any>> {
        val directory = DocumentFile.fromTreeUri(this, uri)
        val files = mutableListOf<Map<String, Any>>()

        if (directory != null && directory.isDirectory) {
            for (item in directory.listFiles()) {
                if (item.isFile) {
                    val fileInfo: Map<String, Any> = mapOf(
                        "uri" to item.uri.toString(),
                        "name" to (item.name ?: "Unknown"),
                        "size" to item.length(),
                        "modified" to item.lastModified()
                    )
                    files.add(fileInfo)
                }
            }
        }

        return files
    }

    private fun readFileChunk(uri: Uri, offset: Int, chunkSize: Int): ByteArray? {
        return try {
            contentResolver.openInputStream(uri)?.use { inputStream ->
                inputStream.skip(offset.toLong())
                val buffer = ByteArray(chunkSize)
                val bytesRead = inputStream.read(buffer, 0, chunkSize)
                if (bytesRead != -1) {
                    buffer.copyOf(bytesRead)
                } else {
                    null
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }

    companion object {
        const val PICK_DIRECTORY_REQUEST_CODE = 1
    }
}
```

**Comment by sheinin** [comment]
I'm experiencing this problem when:

- Android reads folder named "ABC" on SD card
- SD card is removed from Android and placed in a PC
- The folder "ABC" is deleted and folder "abc" is created
- SD card returned to Android and doesn't read files inside "abc"


Is there a workaround for this issue? Clear cache, reboot, reinstall app don't help. I can see the files in File Explorer

**Comment by mraleph** [comment]
@sheinin I would think that the app needs `MANAGE_EXTERNAL_STORAGE` if it wants to read data like that.
