### ISSUE TITLE
[Cider] NoSuchMethodError: The method 'readIndex' was called on null.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#44841]
```
NoSuchMethodError: The method 'readIndex' was called on null.
Receiver: null
Tried calling: readIndex()
#0      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:295)
#1      LinkedElementFactory.buildExportNamespace (package:analyzer/src/summary2/linked_element_factory.dart:55)
#2      LibraryElementImpl.exportNamespace (package:analyzer/src/dart/element/element.dart:4963)
#3      NamespaceBuilder._getExportMapping (package:analyzer/src/dart/resolver/scope.dart:315)
#4      NamespaceBuilder.getImportedElements (package:analyzer/src/dart/resolver/scope.dart:212)
#5      new PrefixScope (package:analyzer/src/dart/element/scope.dart:201)
#6      new _LibraryImportScope (package:analyzer/src/dart/element/scope.dart:314)
#7      new LibraryScope (package:analyzer/src/dart/element/scope.dart:107)
#8      LibraryElementImpl.scope (package:analyzer/src/dart/element/element.dart:5230)
#9      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/micro/library_analyzer.dart:694)
#10     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/library_analyzer.dart:148)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397)
#12     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/micro/library_analyzer.dart:147)
#13     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:137)
#14     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/micro/library_analyzer.dart:146)
#15     FileResolver.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:382)
#16     _rootRun (dart:async/zone.dart:1354)
#17     _CustomZone.run (dart:async/zone.dart:1258)
#18     _runZoned (dart:async/zone.dart:1788)
#19     runZoned (dart:async/zone.dart:1710)
#20     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42)
#21     FileResolver.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:381)
#22     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:137)
#23     FileResolver.resolve.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:380)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32)
#25     FileResolver.resolve.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:365)
#26     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32)
#27     FileResolver.resolve (package:analyzer/src/dart/micro/resolve_file.dart:336)
```

**Comment by scheglov** [comment]
Add debug information: https://dart-review.googlesource.com/c/sdk/+/182400

**Comment by srawlins** [comment]
Closing as stale; please re-open if you see this crash on a recent version of Dart.
