### ISSUE TITLE
Crash when CompilationUnit.declaredElement is null

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#44840]
```
NoSuchMethodError: The getter 'topLevelVariables' was called on null.
Receiver: null
Tried calling: topLevelVariables
#0      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/micro/library_analyzer.dart:683)
#1      LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/library_analyzer.dart:148)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397)
#3      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/micro/library_analyzer.dart:147)
#4      OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:137)
#5      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/micro/library_analyzer.dart:146)
#6      FileResolver.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:382)
#7      _rootRun (dart:async/zone.dart:1354)
#8      _CustomZone.run (dart:async/zone.dart:1258)
#9      _runZoned (dart:async/zone.dart:1788)
#10     runZoned (dart:async/zone.dart:1710)
#11     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42)
#12     FileResolver.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:381)
#13     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:137)
#14     FileResolver.resolve.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:380)
#15     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32)
#16     FileResolver.resolve.<anonymous closure> (package:analyzer/src/dart/micro/resolve_file.dart:365)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32)
#18     FileResolver.resolve (package:analyzer/src/dart/micro/resolve_file.dart:336)
#19     CiderCompletionComputer.compute.<anonymous closure>.<anonymous closure> (package:analysis_server/src/cider/completion.dart:61)
#20     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:137)
#21     CiderCompletionComputer.compute.<anonymous closure> (package:analysis_server/src/cider/completion.dart:60)
#22     CiderCompletionComputer.compute.<anonymous closure> (package:analysis_server/src/cider/completion.dart:59)
#23     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:157)
#24     CiderCompletionComputer.compute (package:analysis_server/src/cider/completion.dart:59)
#25     CiderCompletionComputer.warmUp (package:analysis_server/src/cider/completion.dart:176)
```

**Comment by scheglov** [comment]
A related fix https://dart-review.googlesource.com/c/sdk/+/182366

**Comment by scheglov** [comment]
Add debug information: https://dart-review.googlesource.com/c/sdk/+/182367

**Comment by srawlins** [comment]
Closing as stale; please re-open if you see this crash on a recent version of Dart.
