### ISSUE TITLE
Exception on call 'tools/test.py --help'

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#44855]
Tested on the edge version of the SDK. Try to call
```
tools/test.py --help
```
Result:
```
sgrekhov@SGREKHOV-HP:~/Google/dart-sdk/sdk$ tools/test.py --help
The Dart SDK's internal test runner.
...
    --enable-experiment=<string>
      Experiment flags to enable.

Pass "--verbose" to see more options.
Unhandled exception:
NoSuchMethodError: The getter 'isEmpty' was called on null.
Receiver: null
Tried calling: isEmpty
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      main (file:///home/sgrekhov/Google/dart-sdk/sdk/pkg/test_runner/bin/test_runner.dart:40:22)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by yanok** [comment]
Can't reproduce it. @sgrekhov Could you please check if it's still reproducible for you? And if it is, add some more info, like commit id you are using.

**Comment by sgrekhov** [comment]
@yanok it's not reproducible on the current SDK any longer. Closing this issue
