### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by mrcsh** [dart-lang/sdk#44882]
This is my first attempt to use the package:js/js.dart to call some native js code from a flutter web app.
I am building on Fedora 32 x86_64

```Target dart2js failed: Exception: ../common/lib/app_badger/favico.dart:31:7:
Internal Error: The compiler crashed when compiling this element.
class FavicoOptions {
      ^
```
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.12.0-259.8.beta), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).
```
Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      SsaLoadElimination.visitCreate.<anonymous closure> (package:compiler/src/ssa/optimize.dart:3452:54)
#2      JsElementEnvironment.forEachInstanceField.<anonymous closure> (package:compiler/src/js_model/element_map_impl.dart:2471:10)
#3      JsKernelToElementMap._forEachClassMember.<anonymous closure> (package:compiler/src/js_model/element_map_impl.dart:1076:8)
#4      JClassEnvImpl.forEachMember.<anonymous closure> (package:compiler/src/js_model/env.dart:290:8)
#5      List.forEach (dart:core-patch/growable_array.dart:403:8)
#6      JClassEnvImpl.forEachMember (package:compiler/src/js_model/env.dart:289:14)
#7      JsKernelToElementMap._forEachClassMember (package:compiler/src/js_model/element_map_impl.dart:1075:9)
#8      JsElementEnvironment.forEachClassMember (package:compiler/src/js_model/element_map_impl.dart:2377:16)
#9      JsElementEnvironment.forEachInstanceField (package:compiler/src/js_model/element_map_impl.dart:2469:5)
#10     SsaLoadElimination.visitCreate (package:compiler/src/ssa/optimize.dart:3441:39)
#11     HCreate.accept (package:compiler/src/ssa/nodes.dart:1678:39)
#12     SsaLoadElimination.visitBasicBlock (package:compiler/src/ssa/optimize.dart:3378:19)
#13     SsaLoadElimination.visitGraph (package:compiler/src/ssa/optimize.dart:3336:7)
#14     SsaOptimizerTask.optimize.runPhase.<anonymous closure> (package:compiler/src/ssa/optimize.dart:70:46)
#15     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#16     SsaOptimizerTask.optimize.runPhase (package:compiler/src/ssa/optimize.dart:70:7)
#17     List.forEach (dart:core-patch/growable_array.dart:403:8)
#18     SsaOptimizerTask.optimize.<anonymous closure> (package:compiler/src/ssa/optimize.dart:155:14)
#19     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#20     SsaOptimizerTask.optimize (package:compiler/src/ssa/optimize.dart:88:5)
#21     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:85:15)
#22     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:454:30)
#23     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:320:43)
#24     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:451:29)
#25     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:511:70)
#26     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#27     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:511:32)
#28     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#29     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:509:28)
#30     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:800:15)
#31     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:507:18)
#32     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:269:12)
#33     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:285:5)
#34     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:503:16)
#35     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#36     Compiler.emptyQueue (package:compiler/src/compiler.dart:502:14)
#37     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:528:7)
#38     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#39     Compiler.processQueue (package:compiler/src/compiler.dart:521:14)
#40     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:420:5)
#41     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:325:9)
#42     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:484:7)
#43     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#44     Compiler.compileFromKernel (package:compiler/src/compiler.dart:457:14)
#45     Compiler.runInternal (package:compiler/src/compiler.dart:298:13)
<asynchronous suspension>
```

Compiling lib/main.dart for the Web...                             37.5s

**Comment by mrcsh** [comment]
I found my issue, I did not pay enough attention to the the anonymous class declarations and did not declare the fields as external getters.

**Comment by sigmundch** [comment]
@mrcsh - thanks for reporting this issue! Could you include a snippet of the code that caused the crash? What does the full declaration of `class FavicoOptions {` look like?

Recently we have been adding validation of JS-interop declarations, so it would be great to provide a better error message in cases like these.

/cc @srujzs @rileyporter

**Comment by mrcsh** [comment]
I am fairly sure it was along the lines of 
`
@JS()
@anonymous
class FavicoOptions {
  final String type;
  final String animation;
  final String fontFamily;
  final bool elementId;
  final String element;
  final String bgColor;
  final String textColor;
  final String position;

  external factory FavicoOptions2({
    String type,
    String animation,
    String fontFamily,
    bool elementId,
    String element,
    String bgColor,
    String textColor,
    String position,
  });
}
`

**Comment by srujzs** [comment]
Might be worth adding some tests for fields (with the different keywords `final`, `const`, `late`, and `static`) in general for abstract and non-abstract `@JS` and `@anonymous` classes. There's potential for a lot of undefined behavior here, so it'd be useful to determine on what other usage of fields would lead to a crash.
