### ISSUE TITLE
Exception when running migration over flutter gallery

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#44996]
```
Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.13.0-21.0.dev) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

Bad state: A decorated type for Future<dynamic>* loadLibrary() should have been stored by the NodeBuilder via recordDecoratedElementType at offset 2511 in /Users/kevmoo/github/flutter_gallery/test/restoration_test.dart (loadLibrary)

#0      Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:382:7)
#1      Variables.decoratedElementType (package:nnbd_migration/src/variables.dart:100:9)
#2      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:301:38)
#3      EdgeBuilder.visitSimpleIdentifier (package:nnbd_migration/src/edge_builder.dart:1603:16)
#4      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8898:50)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#6      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:2976:14)
#7      EdgeBuilder.visitPrefixedIdentifier (package:nnbd_migration/src/edge_builder.dart:1405:14)
#8      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8190:50)
#9      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#10     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#11     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2936:7)
#12     EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1296:24)
#13     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7155:50)
#14     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#15     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#16     EdgeBuilder.visitExpressionFunctionBody (package:nnbd_migration/src/edge_builder.dart:793:5)
#17     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3477:15)
#18     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#19     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:937:25)
#20     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#21     EdgeBuilder.visitFunctionExpression (package:nnbd_migration/src/edge_builder.dart:935:28)
#22     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4977:50)
#23     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#24     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#25     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2936:7)
#26     EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1296:24)
#27     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7155:50)
#28     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#29     EdgeBuilder.visitAwaitExpression (package:nnbd_migration/src/edge_builder.dart:426:26)
#30     AwaitExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:883:50)
#31     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#32     EdgeBuilder.visitExpressionStatement (package:nnbd_migration/src/edge_builder.dart:801:25)
#33     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3637:50)
#34     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#35     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#36     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#37     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#38     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1065:50)
#39     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#40     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#41     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:326:46)
#42     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#43     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1020:50)
#44     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#45     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:937:25)
#46     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#47     EdgeBuilder.visitFunctionExpression (package:nnbd_migration/src/edge_builder.dart:935:28)
#48     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4977:50)
#49     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#50     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#51     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2936:7)
#52     EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1296:24)
#53     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7155:50)
#54     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#55     EdgeBuilder.visitExpressionStatement (package:nnbd_migration/src/edge_builder.dart:801:25)
#56     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3637:50)
#57     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#58     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#59     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#60     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#61     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1065:50)
#62     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#63     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#64     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:326:46)
#65     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#66     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1020:50)
#67     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#68     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:937:25)
#69     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#70     EdgeBuilder.visitFunctionExpression (package:nnbd_migration/src/edge_builder.dart:935:28)
#71     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4977:50)
#72     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#73     EdgeBuilder.visitFunctionDeclaration (package:nnbd_migration/src/edge_builder.dart:886:9)
#74     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4841:50)
#75     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#76     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#77     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#78     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#79     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#80     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#81     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2110:50)
#82     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#83     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#84     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1154:19)
#85     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:28)
#86     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#87     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1152:5)
<asynchronous suspension>
#88     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#89     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#90     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#91     DartdevRunner.runCommand (package:dartdev/dartdev.dart:190:18)
<asynchronous suspension>
#92     runDartdev (package:dartdev/dartdev.dart:52:16)
<asynchronous suspension>
#93     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by srawlins** [comment]
CC @stereotype441

**Comment by stereotype441** [comment]
Thanks for the report, @kevmoo!  Were you able to get a reasonable result by running with `--ignore-exceptions`?

**Comment by kevmoo** [comment]
Didn't try that yet!

**Comment by kevmoo** [comment]
It worked. It's slow (HUGE app). But it worked

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
