### ISSUE TITLE
the Dart compiler exited unexpectedly.

### ISSUE THREAD

**Issue by Aaron009** [dart-lang/sdk#45014]
```dart
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Unhandled exception:
Crash when compiling null,
at character offset null:
unreachable PropertyGet(t.directives)
#0      AsyncRewriterBase.defaultExpression (package:kernel/transformations/continuation.dart:1166:39)
#1      TreeVisitor.visitPropertyGet (package:kernel/visitor.dart:149:43)
#2      PropertyGet.accept (package:kernel/ast.dart:3264:44)
#3      ForInStatement.transformChildren (package:kernel/ast.dart:6293:27)
#4      Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#5      TreeVisitor.defaultStatement (package:kernel/visitor.dart:203:41)
#6      TreeVisitor.visitForInStatement (package:kernel/visitor.dart:215:49)
#7      RecursiveContinuationRewriter.visitForInStatement (package:kernel/transformations/continuation.dart:191:20)
#8      AsyncRewriterBase.visitForInStatement (package:kernel/transformations/continuation.dart:1085:13)
#9      ForInStatement.accept (package:kernel/ast.dart:6277:43)
#10     AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation.dart:667:17)
#11     Block.accept (package:kernel/ast.dart:5873:43)
#12     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:752:10)
#13     AsyncRewriterBase.visitLabeledStatement (package:kernel/transformations/continuation.dart:760:17)
#14     LabeledStatement.accept (package:kernel/ast.dart:6034:43)
#15     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:752:10)
#16     AsyncRewriterBase.visitForStatement (package:kernel/transformations/continuation.dart:845:22)
#17     ForStatement.accept (package:kernel/ast.dart:6208:43)
#18     AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation.dart:667:17)
#19     Block.accept (package:kernel/ast.dart:5873:43)
#20     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:752:10)
#21     AsyncRewriterBase.visitForStatement (package:kernel/transformations/continuation.dart:845:22)
#22     ForStatement.accept (package:kernel/ast.dart:6208:43)
#23     AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation.dart:667:17)
#24     Block.accept (package:kernel/ast.dart:5873:43)
#25     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:752:10)
#26     AsyncRewriterBase.buildWrappedBody (package:kernel/transformations/continuation.dart:626:24)
#27     AsyncRewriterBase.setupAsyncContinuations (package:kernel/transformations/continuation.dart:578:39)
#28     AsyncFunctionRewriter.rewrite (package:kernel/transformations/continuation.dart:1328:5)
#29     RecursiveContinuationRewriter.visitFunctionNode (package:kernel/transformations/continuation.dart:143:14)
#30     FunctionNode.accept (package:kernel/ast.dart:2932:38)
#31     Procedure.transformChildren (package:kernel/ast.dart:2436:27)
#32     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#33     TreeVisitor.defaultMember (package:kernel/visitor.dart:230:35)
#34     TreeVisitor.visitProcedure (package:kernel/visitor.dart:232:39)
#35     RecursiveContinuationRewriter.visitProcedure (package:kernel/transformations/continuation.dart:117:51)
#36     Procedure.accept (package:kernel/ast.dart:2423:40)
#37     transformList (package:kernel/ast.dart:9699:27)
#38     Class.transformChildren (package:kernel/ast.dart:1428:5)
#39     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#40     TreeVisitor.visitClass (package:kernel/visitor.dart:239:31)
#41     Class.accept (package:kernel/ast.dart:1379:38)
#42     transformList (package:kernel/ast.dart:9699:27)
#43     Library.transformChildren (package:kernel/ast.dart:625:5)
#44     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#45     TreeVisitor.visitLibrary (package:kernel/visitor.dart:254:35)
#46     RecursiveContinuationRewriter.visitLibrary (package:kernel/transformations/continuation.dart:125:28)
#47     Library.accept (package:kernel/ast.dart:607:38)
#48     RecursiveContinuationRewriter.rewriteLibrary (package:kernel/transformations/continuation.dart:97:17)
#49     transformLibraries (package:kernel/transformations/continuation.dart:55:14)
#50     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:171:5)
#51     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1126:19)
#52     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:390:7)
<asynchronous suspension>
#53     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#54     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#55     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:380:12)
#56     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:274:28)
<asynchronous suspension>
#57     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
#58     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#59     new Future.sync (dart:async/future.dart:223:31)
#60     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#61     _rootRun (dart:async/zone.dart:1190:13)
#62     _CustomZone.run (dart:async/zone.dart:1093:19)
#63     _runZoned (dart:async/zone.dart:1630:10)
#64     runZoned (dart:async/zone.dart:1550:10)
#65     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#66     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:206:20)
#67     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:46)
#68     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:524:59)
#69     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#70     _rootRun (dart:async/zone.dart:1182:47)
#71     _CustomZone.run (dart:async/zone.dart:1093:19)
#72     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#73     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#74     _rootRun (dart:async/zone.dart:1190:13)
#75     _CustomZone.run (dart:async/zone.dart:1093:19)
#76     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#77     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#78     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#79     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#80     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


#0      AsyncRewriterBase.defaultExpression (package:kernel/transformations/continuation.dart:1166:39)
#1      TreeVisitor.visitPropertyGet (package:kernel/visitor.dart:149:43)
#2      PropertyGet.accept (package:kernel/ast.dart:3264:44)
#3      ForInStatement.transformChildren (package:kernel/ast.dart:6293:27)
#4      Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#5      TreeVisitor.defaultStatement (package:kernel/visitor.dart:203:41)
#6      TreeVisitor.visitForInStatement (package:kernel/visitor.dart:215:49)
#7      RecursiveContinuationRewriter.visitForInStatement (package:kernel/transformations/continuation.dart:191:20)
#8      AsyncRewriterBase.visitForInStatement (package:kernel/transformations/continuation.dart:1085:13)
#9      ForInStatement.accept (package:kernel/ast.dart:6277:43)
#10     AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation.dart:667:17)
#11     Block.accept (package:kernel/ast.dart:5873:43)
#12     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:752:10)
#13     AsyncRewriterBase.visitLabeledStatement (package:kernel/transformations/continuation.dart:760:17)
#14     LabeledStatement.accept (package:kernel/ast.dart:6034:43)
#15     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:752:10)
#16     AsyncRewriterBase.visitForStatement (package:kernel/transformations/continuation.dart:845:22)
#17     ForStatement.accept (package:kernel/ast.dart:6208:43)
#18     AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation.dart:667:17)
#19     Block.accept (package:kernel/ast.dart:5873:43)
#20     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:752:10)
#21     AsyncRewriterBase.visitForStatement (package:kernel/transformations/continuation.dart:845:22)
#22     ForStatement.accept (package:kernel/ast.dart:6208:43)
#23     AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation.dart:667:17)
#24     Block.accept (package:kernel/ast.dart:5873:43)
#25     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:752:10)
#26     AsyncRewriterBase.buildWrappedBody (package:kernel/transformations/continuation.dart:626:24)
#27     AsyncRewriterBase.setupAsyncContinuations (package:kernel/transformations/continuation.dart:578:39)
#28     AsyncFunctionRewriter.rewrite (package:kernel/transformations/continuation.dart:1328:5)
#29     RecursiveContinuationRewriter.visitFunctionNode (package:kernel/transformations/continuation.dart:143:14)
#30     FunctionNode.accept (package:kernel/ast.dart:2932:38)
#31     Procedure.transformChildren (package:kernel/ast.dart:2436:27)
#32     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#33     TreeVisitor.defaultMember (package:kernel/visitor.dart:230:35)
#34     TreeVisitor.visitProcedure (package:kernel/visitor.dart:232:39)
#35     RecursiveContinuationRewriter.visitProcedure (package:kernel/transformations/continuation.dart:117:51)
#36     Procedure.accept (package:kernel/ast.dart:2423:40)
#37     transformList (package:kernel/ast.dart:9699:27)
#38     Class.transformChildren (package:kernel/ast.dart:1428:5)
#39     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#40     TreeVisitor.visitClass (package:kernel/visitor.dart:239:31)
#41     Class.accept (package:kernel/ast.dart:1379:38)
#42     transformList (package:kernel/ast.dart:9699:27)
#43     Library.transformChildren (package:kernel/ast.dart:625:5)
#44     Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#45     TreeVisitor.visitLibrary (package:kernel/visitor.dart:254:35)
#46     RecursiveContinuationRewriter.visitLibrary (package:kernel/transformations/continuation.dart:125:28)
#47     Library.accept (package:kernel/ast.dart:607:38)
#48     RecursiveContinuationRewriter.rewriteLibrary (package:kernel/transformations/continuation.dart:97:17)
#49     transformLibraries (package:kernel/transformations/continuation.dart:55:14)
#50     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:171:5)
#51     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1126:19)
#52     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:390:7)
<asynchronous suspension>
#53     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#54     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#55     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:380:12)
#56     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:274:28)
<asynchronous suspension>
#57     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
#58     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#59     new Future.sync (dart:async/future.dart:223:31)
#60     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#61     _rootRun (dart:async/zone.dart:1190:13)
#62     _CustomZone.run (dart:async/zone.dart:1093:19)
#63     _runZoned (dart:async/zone.dart:1630:10)
#64     runZoned (dart:async/zone.dart:1550:10)
#65     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#66     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:206:20)
#67     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:46)
#68     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:524:59)
#69     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#70     _rootRun (dart:async/zone.dart:1182:47)
#71     _CustomZone.run (dart:async/zone.dart:1093:19)
#72     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#73     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#74     _rootRun (dart:async/zone.dart:1190:13)
#75     _CustomZone.run (dart:async/zone.dart:1093:19)
#76     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#77     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#78     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#79     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#80     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
```

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H114 darwin-x64, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

```shel
Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "macos_x64"
```

**Comment by mkustermann** [comment]
It seems it stumbles on some async code

@Aaron009  Could you maybe provide us with some Dart code that reproduces the problem?

**Comment by Aaron009** [comment]
I solved it, but I don't understand the cause of the problem.
I found the code based on the error message.

var directives = t.directives;

Then I changed it to the following, no problem.

List<String> directives = t.directives;

**Comment by mraleph** [comment]
Repro:

```dart
broken(X x) async {
  return <X, X>{
    for (var y in x) ...y,
  };
}
```

causes a different exception on HEAD due to 8467186ca0aa1d2b716ed00cb9bc55f74d9ddda9 but the underlying problem is the same: we call super visitor when iterable is not a subtype of `Iterable` which does not work smoothly.

**Comment by mkustermann** [comment]
@johnniwinther Could we avoid calling modular kernel transformers on ASTs that have compile-time errors in them? That would avoid the need for backend transformers to handle such cases.

**Comment by johnniwinther** [comment]
I think the problem is that this part of the transformation is particularly brittle, relying to much on assumed patterns of the incoming AST. The `ForInStatement` is the most complex encoding so that doesn't surprise me.

I could also provoke a crash in a program without compile-time errors by using an iterable of type `Never`, like:
```Dart
loop(x) async {
  return <int, String>{
    for (var y in throw '') ...y,
  };
}
```
which leads to
```
Unhandled exception:
Crash when compiling null,
at character offset null:
unreachable Throw(throw "")
#0      AsyncRewriterBase.defaultExpression (package:kernel/transformations/continuation.dart:1155:39)
#1      TreeVisitor.visitThrow (package:kernel/visitor.dart:204:31)
#2      Throw.accept (package:kernel/ast.dart:6446:44)
#3      ForInStatement.transformChildren (package:kernel/ast.dart:7475:27)
#4      Transformer.defaultTreeNode (package:kernel/visitor.dart:788:10)
#5      TreeVisitor.defaultStatement (package:kernel/visitor.dart:224:41)
#6      TreeVisitor.visitForInStatement (package:kernel/visitor.dart:236:49)
#7      RecursiveContinuationRewriter.visitForInStatement (package:kernel/transformations/continuation.dart:195:20)
#8      AsyncRewriterBase.visitForInStatement (package:kernel/transformations/continuation.dart:1074:13)
#9      ForInStatement.accept (package:kernel/ast.dart:7459:43)
#10     ExpressionLifter.defaultStatement (package:kernel/transformations/async.dart:564:10)
#11     TreeVisitor.visitForInStatement (package:kernel/visitor.dart:236:49)
#12     ForInStatement.accept (package:kernel/ast.dart:7459:43)
#13     ExpressionLifter.visitBlockExpression.<anonymous closure> (package:kernel/transformations/async.dart:541:38)
#14     ExpressionLifter.transform (package:kernel/transformations/async.dart:194:11)
#15     ExpressionLifter.visitBlockExpression (package:kernel/transformations/async.dart:537:12)
#16     BlockExpression.accept (package:kernel/ast.dart:6873:44)
#17     ExpressionLifter.rewrite (package:kernel/transformations/async.dart:103:36)
#18     AsyncFunctionRewriter.visitReturnStatement (package:kernel/transformations/continuation.dart:1385:30)
#19     ReturnStatement.accept (package:kernel/ast.dart:7793:43)
#20     AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation.dart:667:17)
#21     Block.accept (package:kernel/ast.dart:7055:43)
#22     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:752:10)
#23     AsyncRewriterBase.buildWrappedBody (package:kernel/transformations/continuation.dart:626:24)
#24     AsyncRewriterBase.setupAsyncContinuations (package:kernel/transformations/continuation.dart:585:39)
#25     AsyncFunctionRewriter.rewrite (package:kernel/transformations/continuation.dart:1324:5)
#26     RecursiveContinuationRewriter.visitFunctionNode (package:kernel/transformations/continuation.dart:147:14)
#27     FunctionNode.accept (package:kernel/ast.dart:3088:38)
#28     Procedure.transformChildren (package:kernel/ast.dart:2566:27)
#29     Transformer.defaultTreeNode (package:kernel/visitor.dart:788:10)
#30     TreeVisitor.defaultMember (package:kernel/visitor.dart:251:35)
#31     TreeVisitor.visitProcedure (package:kernel/visitor.dart:253:39)
#32     RecursiveContinuationRewriter.visitProcedure (package:kernel/transformations/continuation.dart:121:51)
#33     Procedure.accept (package:kernel/ast.dart:2553:40)
#34     transformList (package:kernel/ast.dart:11064:32)
#35     Library.transformChildren (package:kernel/ast.dart:623:5)
#36     Transformer.defaultTreeNode (package:kernel/visitor.dart:788:10)
#37     TreeVisitor.visitLibrary (package:kernel/visitor.dart:275:35)
#38     RecursiveContinuationRewriter.visitLibrary (package:kernel/transformations/continuation.dart:129:28)
#39     Library.accept (package:kernel/ast.dart:603:38)
#40     RecursiveContinuationRewriter.rewriteLibrary (package:kernel/transformations/continuation.dart:101:17)
#41     transformLibraries (package:kernel/transformations/continuation.dart:59:14)
#42     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:170:5)
#43     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1257:19)
#44     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:400:7)
<asynchronous suspension>
#45     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#46     CompileTask.compile (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/entry_points.dart:368:9)
<asynchronous suspension>
#47     compile.<anonymous closure>.<anonymous closure> (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/entry_points.dart:247:14)
<asynchronous suspension>
#48     compile.<anonymous closure> (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/entry_points.dart:240:12)
<asynchronous suspension>
#49     runProtectedFromAbort (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/command_line.dart:498:12)
<asynchronous suspension>
#50     compile (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/entry_points.dart:239:10)
<asynchronous suspension>
#51     compileEntryPoint (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/entry_points.dart:75:5)
<asynchronous suspension>
``` 
or
```
Unhandled exception:
Crash when compiling null,
at character offset null:
'package:kernel/visitor.dart': Failed assertion: line 1003 pos 9: 'result != null': Attempting to remove VariableDeclarationImpl(dynamic y) (VariableDeclarationImpl) in transformer.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      Transformer.transform (package:kernel/visitor.dart:1003:9)
#3      ForInStatement.transformChildren (package:kernel/ast.dart:9019:20)
#4      Transformer.defaultTreeNode (package:kernel/visitor.dart:1057:10)
#5      TreeVisitor.defaultStatement (package:kernel/visitor.dart:256:41)
#6      TreeVisitor.visitForInStatement (package:kernel/visitor.dart:268:49)
#7      RecursiveContinuationRewriter.visitForInStatement (package:kernel/transformations/continuation.dart:195:20)
#8      AsyncRewriterBase.visitForInStatement (package:kernel/transformations/continuation.dart:1074:13)
#9      ForInStatement.accept (package:kernel/ast.dart:9002:43)
#10     ExpressionLifter.defaultStatement (package:kernel/transformations/async.dart:564:10)
#11     TreeVisitor.visitForInStatement (package:kernel/visitor.dart:268:49)
#12     ForInStatement.accept (package:kernel/ast.dart:9002:43)
#13     ExpressionLifter.visitBlockExpression.<anonymous closure> (package:kernel/transformations/async.dart:541:38)
#14     ExpressionLifter.transformTreeNode (package:kernel/transformations/async.dart:194:11)
#15     ExpressionLifter.visitBlockExpression (package:kernel/transformations/async.dart:537:12)
#16     BlockExpression.accept (package:kernel/ast.dart:8225:44)
#17     ExpressionLifter.rewrite (package:kernel/transformations/async.dart:103:36)
#18     AsyncFunctionRewriter.visitReturnStatement (package:kernel/transformations/continuation.dart:1385:30)
#19     ReturnStatement.accept (package:kernel/ast.dart:9430:43)
#20     AsyncRewriterBase.visitBlock (package:kernel/transformations/continuation.dart:667:17)
#21     Block.accept (package:kernel/ast.dart:8462:43)
#22     AsyncRewriterBase.visitDelimited (package:kernel/transformations/continuation.dart:752:10)
#23     AsyncRewriterBase.buildWrappedBody (package:kernel/transformations/continuation.dart:626:24)
#24     AsyncRewriterBase.setupAsyncContinuations (package:kernel/transformations/continuation.dart:585:39)
#25     AsyncFunctionRewriter.rewrite (package:kernel/transformations/continuation.dart:1324:5)
#26     RecursiveContinuationRewriter.visitFunctionNode (package:kernel/transformations/continuation.dart:147:14)
#27     FunctionNode.accept (package:kernel/ast.dart:3475:38)
#28     Transformer.transform (package:kernel/visitor.dart:1000:21)
#29     Procedure.transformChildren (package:kernel/ast.dart:2844:20)
#30     Transformer.defaultTreeNode (package:kernel/visitor.dart:1057:10)
#31     TreeVisitor.defaultMember (package:kernel/visitor.dart:283:35)
#32     TreeVisitor.visitProcedure (package:kernel/visitor.dart:285:39)
#33     RecursiveContinuationRewriter.visitProcedure (package:kernel/transformations/continuation.dart:121:51)
#34     Procedure.accept (package:kernel/ast.dart:2824:40)
#35     Transformer.transform (package:kernel/visitor.dart:1000:21)
#36     Transformer.transformList (package:kernel/visitor.dart:1035:18)
#37     Library.transformChildren (package:kernel/ast.dart:636:7)
#38     Transformer.defaultTreeNode (package:kernel/visitor.dart:1057:10)
#39     TreeVisitor.visitLibrary (package:kernel/visitor.dart:307:35)
#40     RecursiveContinuationRewriter.visitLibrary (package:kernel/transformations/continuation.dart:129:28)
#41     Library.accept (package:kernel/ast.dart:611:38)
#42     RecursiveContinuationRewriter.rewriteLibrary (package:kernel/transformations/continuation.dart:101:17)
#43     transformLibraries (package:kernel/transformations/continuation.dart:59:14)
#44     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:183:5)
#45     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1257:19)
#46     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:400:7)
<asynchronous suspension>
#47     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#48     CompileTask.compile (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/entry_points.dart:368:9)
<asynchronous suspension>
#49     compile.<anonymous closure>.<anonymous closure> (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/entry_points.dart:247:14)
<asynchronous suspension>
#50     compile.<anonymous closure> (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/entry_points.dart:240:12)
<asynchronous suspension>
#51     runProtectedFromAbort (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/command_line.dart:498:12)
<asynchronous suspension>
#52     compile (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/entry_points.dart:239:10)
<asynchronous suspension>
#53     compileEntryPoint (file:///C:/src/dart-repo3/sdk/pkg/front_end/tool/_fasta/entry_points.dart:75:5)
<asynchronous suspension>
```
depending on whether the newly migrated `package:kernel/ast.dart` is used.
