### ISSUE TITLE
Dart migrate (NNBD tool) when migrating public package: Bad state: Unrelated types.

### ISSUE THREAD

**Issue by marcglasberg** [dart-lang/sdk#45027]
This happened when migrating https://pub.dev/packages/fast_immutable_collections version: [1.1.0]

You can try it yourself if you run `dart migrate` in this specific commit:  https://github.com/marcglasberg/fast_immutable_collections/tree/a4f9031b2e245516c9b769e7fff6f2256826b9b1

Analyzing project...
[------------------------------------/]
No analysis issues found.

Generating migration suggestions...
[--/                                                                                                                                                                                 ]
Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.12.0-259.9.beta) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

Bad state: Unrelated types: abstract class ImmutableCollection<C> implements CanBeEmpty* and class IList<T> extends ImmutableCollection<IList<T*>*>* implements Iterable<T*>* at offse
t 6645 in fast_immutable_collections\lib\src\base\immutable_collection.dart (c1.equalItems(c2))

#0      DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:67:10)
#1      DecoratedClassHierarchy.asInstanceOf (package:nnbd_migration/src/decorated_class_hierarchy.dart:38:18)
#2      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:259:16)
#3      EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1284:20)
#4      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#6      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2329:20)
#7      EdgeBuilder.visitReturnStatement (package:nnbd_migration/src/edge_builder.dart:1498:7)
#8      ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8617:49)
#9      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#10     EdgeBuilder.visitIfStatement.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:1037:25)
#11     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#12     EdgeBuilder.visitIfStatement (package:nnbd_migration/src/edge_builder.dart:1036:28)
#13     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5705:49)
#14     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#15     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#16     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#17     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#18     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#19     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#20     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#21     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:324:45)
#22     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:55)
#23     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#24     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#25     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:937:25)
#26     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#27     EdgeBuilder.visitFunctionExpression (package:nnbd_migration/src/edge_builder.dart:935:28)
#28     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5004:49)
#29     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#30     EdgeBuilder.visitFunctionDeclaration (package:nnbd_migration/src/edge_builder.dart:886:9)
#31     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4866:49)
#32     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#33     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#34     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:51)
#35     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#36     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#37     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#38     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#39     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#40     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#41     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1154:19)
#42     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:28)
#43     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#44     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1152:5)
<asynchronous suspension>
#45     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#46     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#47     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#48     DartdevRunner.runCommand (package:dartdev/dartdev.dart:190:18)
<asynchronous suspension>
#49     runDartdev (package:dartdev/dartdev.dart:52:16)
<asynchronous suspension>
#50     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

**Comment by marcglasberg** [comment]
The exception is gone if I change this:

```
bool areImmutableCollectionsWithEqualItems<C extends ImmutableCollection<dynamic>>(C c1, C c2) {
  if (identical(c1, c2)) return true;
  if (c1 is IList && c2 is IList) return c1.equalItems(c2);
  if (c1 is ISet && c2 is ISet) return c1.equalItems(c2);
  if (c1 is IMap && c2 is IMap) return (c1).equalItemsToIMap(c2);
  if (c1 is IMapOfSets && c2 is IMapOfSets) return (c1).equalItemsToIMapOfSets(c2);
  return false;
}
```

Into this:

```
bool areImmutableCollectionsWithEqualItems<C extends ImmutableCollection<dynamic>>(C c1, C c2) {
  if (identical(c1, c2)) return true;
  if (c1 is IList && c2 is IList) return (c1 as IList).equalItems(c2 as IList);
  if (c1 is ISet && c2 is ISet) return (c1 as ISet).equalItems(c2 as ISet);
  if (c1 is IMap && c2 is IMap) return (c1 as IMap).equalItemsToIMap(c2 as IMap);
  if (c1 is IMapOfSets && c2 is IMapOfSets) return (c1 as IMapOfSets).equalItemsToIMapOfSets(c2 as IMapOfSets);
  return false;
}
```

However, then if fails in another file:

```
UnimplementedError: GLB with substitution in "compare ?? compareObject" on line 492 of "fast_immutable_collections\lib\src\imap\imap.dart" at offset 17612 in fast_immutable_collections\lib\src\imap\imap.dart (compare ?? compareObject)
```

**Comment by stereotype441** [comment]
Thanks for the bug report, @marcglasberg.  Did you try re-running the migration with the `--ignore-exceptions` option, and if so did it work?

**Comment by marcglasberg** [comment]
@stefantsov Yes, I did, and it managed to finish then. However, I assume the result it not quite as good as it would have been with no errors. In any case, I am just using this as a starting point anyway.

**Comment by agent3bood** [comment]
I had similar issue, when migrating at this point https://github.com/agent3bood/gql/tree/5f0e284468bb955660af7ed14509a6dea9a5ce47

```
Bad state: Unrelated types: class WebSocketChannel extends StreamChannelMixin<dynamic> and abstract class FutureOr<T> at offset 4974 in /Users/agent/work/open-source/gql/links/gql_websocket_link/lib/src/link.dart (channelGenerator ?? () => WebSocketChannel.connect(Uri.parse(_uri)))

#0      DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:67:10)
#1      DecoratedClassHierarchy.asInstanceOf (package:nnbd_migration/src/decorated_class_hierarchy.dart:38:18)
#2      EdgeBuilder._decorateUpperOrLowerBound (package:nnbd_migration/src/edge_builder.dart:2108:18)
#3      EdgeBuilder._decorateUpperOrLowerBound (package:nnbd_migration/src/edge_builder.dart:2154:26)
#4      EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:495:26)
#5      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:967:49)
#6      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#7      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2329:20)
#8      EdgeBuilder.visitAssignmentExpression (package:nnbd_migration/src/edge_builder.dart:409:26)
#9      AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:715:49)
#10     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#11     EdgeBuilder.visitExpressionStatement (package:nnbd_migration/src/edge_builder.dart:801:25)
#12     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3676:49)
#13     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#14     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#15     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#16     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#17     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#18     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#19     EdgeBuilder.visitIfStatement.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:1052:27)
#20     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#21     EdgeBuilder.visitIfStatement (package:nnbd_migration/src/edge_builder.dart:1051:30)
#22     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5705:49)
#23     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#24     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#25     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#26     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#27     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#28     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#29     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#30     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:324:45)
#31     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:55)
#32     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#33     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#34     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2488:7)
#35     EdgeBuilder.visitConstructorDeclaration (package:nnbd_migration/src/edge_builder.dart:712:5)
#36     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2566:15)
#37     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#38     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#39     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#40     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#41     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#42     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#43     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#44     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:51)
#45     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#46     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#47     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#48     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#49     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#50     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#51     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1154:19)
#52     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:28)
#53     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#54     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1152:5)
<asynchronous suspension>
#55     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#56     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#57     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#58     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#59     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#60     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by figengungor** [comment]
I get a similar Bad state: Unrelated Types error when I try to migrate this package: https://github.com/vdakalov/fff

```
dart migrate
Migrating /Users/figengungor/Documents/development/fff

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------/]No analysis issues found.

Generating migration suggestions...
[----------------------------------------------------------------------------------------------/                                                                                                ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.12.0) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

Bad state: Unrelated types: abstract class List<E> implements EfficientLengthIterable<E> and abstract class Map<K, V> at offset 5805 in /Users/figengungor/Documents/development/fff/lib/color.dart (target.keys)

#0      DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:67:10)
#1      DecoratedClassHierarchy.asInstanceOf (package:nnbd_migration/src/decorated_class_hierarchy.dart:38:18)
#2      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:259:16)
#3      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:2997:20)
#4      EdgeBuilder.visitPrefixedIdentifier (package:nnbd_migration/src/edge_builder.dart:1405:14)
#5      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8257:49)
#6      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#7      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2329:20)
#8      EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2934:7)
#9      EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:1154:5)
#10     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6130:15)
#11     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#12     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2329:20)
#13     EdgeBuilder.visitReturnStatement (package:nnbd_migration/src/edge_builder.dart:1498:7)
#14     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8617:49)
#15     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#16     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#17     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#18     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#19     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#20     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#21     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#22     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:324:45)
#23     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:55)
#24     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#25     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#26     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2488:7)
#27     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#28     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#29     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#30     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#31     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#32     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#33     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#34     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#35     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#36     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:51)
#37     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#38     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#39     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#40     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#41     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#42     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#43     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1154:19)
#44     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:28)
#45     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#46     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1152:5)
<asynchronous suspension>
#47     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#48     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#49     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#50     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#51     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#52     main (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by stereotype441** [comment]
Ok, with 2 additional reports of this problem coming in over the last 24 hours, I'm bumping the priority to P1.

**Comment by SuporteSysrs01** [comment]
```
Analyzing project...
[----------------------------------------------------------------------------------------------------------------------------------/]No analysis issues found.

Generating migration suggestions...
[--------------------------------------------------------/                                                                          ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.16.2) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

Bad state: Unrelated types: class bool and abstract class FutureOr<T> at offset 2381 in /Users/sysrs/Turbo/Flutter/mrmobile/lib/widgets/cl_code_input.dart (widget.onDone?.call(value) ?? true)

#0      DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:67:10)
#1      DecoratedClassHierarchy.asInstanceOf (package:nnbd_migration/src/decorated_class_hierarchy.dart:38:18)
#2      EdgeBuilder._decorateUpperOrLowerBound (package:nnbd_migration/src/edge_builder.dart:2213:18)
#3      EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:569:26)
#4      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:932:50)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#6      EdgeBuilder.visitParenthesizedExpression (package:nnbd_migration/src/edge_builder.dart:1526:18)
#7      ParenthesizedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:8137:15)
#8      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#9      EdgeBuilder.visitAwaitExpression (package:nnbd_migration/src/edge_builder.dart:496:26)
#10     AwaitExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:864:50)
#11     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#12     EdgeBuilder.visitParenthesizedExpression (package:nnbd_migration/src/edge_builder.dart:1526:18)
#13     ParenthesizedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:8137:15)
#14     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#15     EdgeBuilder._checkExpressionNotNull (package:nnbd_migration/src/edge_builder.dart:2067:20)
#16     EdgeBuilder.visitPrefixExpression (package:nnbd_migration/src/edge_builder.dart:1581:22)
#17     PrefixExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:8495:50)
#18     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#19     EdgeBuilder._checkExpressionNotNull (package:nnbd_migration/src/edge_builder.dart:2067:20)
#20     EdgeBuilder.visitIfStatement (package:nnbd_migration/src/edge_builder.dart:1111:5)
#21     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5823:50)
#22     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#23     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1508:9)
#24     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:547:40)
#25     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#26     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1047:50)
#27     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#28     EdgeBuilder.visitIfStatement.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:1127:25)
#29     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#30     EdgeBuilder.visitIfStatement (package:nnbd_migration/src/edge_builder.dart:1126:28)
#31     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5823:50)
#32     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#33     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1508:9)
#34     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:547:40)
#35     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#36     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1047:50)
#37     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#38     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1508:9)
#39     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:330:46)
#40     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#41     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1002:50)
#42     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#43     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2624:7)
#44     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1334:5)
#45     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7177:50)
#46     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#47     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2330:7)
#48     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:681:7)
#49     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:648:5)
#50     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1494:50)
#51     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#52     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1508:9)
#53     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#54     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#55     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#56     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#57     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2098:50)
#58     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:231:12)
#59     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:16)
#60     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1093:20)
#61     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1091:28)
#62     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1025:26)
<asynchronous suspension>
#63     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1091:5)
<asynchronous suspension>
#64     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:698:24)
<asynchronous suspension>
#65     MigrateCommand.run (package:dartdev/src/commands/migrate.dart:37:7)
<asynchronous suspension>
#66     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#67     DartdevRunner.runCommand (package:dartdev/dartdev.dart:232:18)
<asynchronous suspension>
#68     runDartdev (package:dartdev/dartdev.dart:67:16)
<asynchronous suspension>
#69     main (file:///opt/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

It breaks on the following line in my code:
```dart
if (!(await (widget.onDone?.call(value) ?? true))) {
   ...
}
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
