### ISSUE TITLE
NoSuchMethodError: The getter 'nullabilitySuffix' was called on null in package:analyzer/src/dart/element/subtype.dart:51:29

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#45052]
Was revealed by a failing pana run. Here is the related issue: https://github.com/dart-lang/pana/issues/827
```
dart --version
Dart SDK version: 2.12.0-259.14.beta (beta) (Wed Feb 17 10:18:35 2021 +0100) on "macos_x64"
```

Not sure what exactly goes wrong, but here is a smallish reproduction:

pubspec.yaml:
```
name: blah 

environment:
  sdk: '>=2.12.0-259.14.beta <3.0.0'
```

`lib/a.dart`:
```
class A {
  static void clamp(p) {
  }
  void t(p) {
    clamp(12);
  }
}
```
(The name `clamp` seems to be important)...

```sh
> dartanalyzer lib
Analyzing lib...
Unhandled exception:
NoSuchMethodError: The getter 'nullabilitySuffix' was called on null.
Receiver: null
Tried calling: nullabilitySuffix
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      SubtypeHelper.isSubtypeOf (package:analyzer/src/dart/element/subtype.dart:51:29)
#2      TypeSystemImpl.isSubtypeOf2 (package:analyzer/src/dart/element/type_system.dart:1162:27)
#3      TypeSystemImpl.isSubtypeOf (package:analyzer/src/dart/element/type_system.dart:1158:12)
#4      TypeSystemImpl._refineNumericInvocationContextNullSafe (package:analyzer/src/dart/element/type_system.dart:1713:11)
#5      TypeSystemImpl.refineNumericInvocationContext (package:analyzer/src/dart/element/type_system.dart:1402:14)
#6      ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:862:24)
#7      InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:326:15)
#8      InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:367:7)
#9      InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:345:7)
#10     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:239:5)
#11     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:811:24)
#12     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:514:16)
#13     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:93:7)
#14     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:394:31)
#15     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#16     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1706:10)
#17     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#18     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3680:18)
#19     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#20     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3229:59)
#21     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3676:49)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#23     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#24     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#25     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#26     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#27     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#28     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#29     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#30     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1042:13)
#31     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#32     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3146:55)
#33     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2489:13)
#34     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:957:13)
#35     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#36     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7042:12)
#37     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#38     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3351:55)
#39     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:2926:11)
#40     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:2919:7)
#41     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:1666:11)
#42     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#43     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#44     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:2550:18)
#45     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2531:7)
#46     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:1015:13)
#47     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#48     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:1091:23)
#49     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#50     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:709:10)
#51     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:139:7)
#52     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#53     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:138:11)
#54     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:12)
#55     AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1319:63)
#56     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#57     AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1296:20)
#58     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1249:14)
#59     _rootRun (dart:async/zone.dart:1354:13)
#60     _CustomZone.run (dart:async/zone.dart:1258:19)
#61     _runZoned (dart:async/zone.dart:1788:10)
#62     runZoned (dart:async/zone.dart:1710:10)
#63     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#64     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1248:40)
#65     AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1374:41)
#66     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:981:20)
#67     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2018:24)
<asynchronous suspension>

#0      AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1349:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#2      AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1296:20)
#3      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1249:14)
#4      _rootRun (dart:async/zone.dart:1354:13)
#5      _CustomZone.run (dart:async/zone.dart:1258:19)
#6      _runZoned (dart:async/zone.dart:1788:10)
#7      runZoned (dart:async/zone.dart:1710:10)
#8      NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#9      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1248:40)
#10     AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1374:41)
#11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:981:20)
#12     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2018:24)
<asynchronous suspension>
```

**Comment by parlough** [comment]
I can't seem to be reproduce this, looks to have perhaps been solved by https://github.com/dart-lang/sdk/commit/4c6f5f7 or just the transition to null safety in the analyzer(https://github.com/dart-lang/sdk/commits/9f986d2501f4a8294e8b34d593c0a6935e5fc773)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/191600 (based on origin/stable)
