### ISSUE TITLE
dartdoc 0.39.0 failed because it tries to invoke nullabilitySuffix on a null

### ISSUE THREAD

**Issue by hoylen** [dart-lang/sdk#45069]
The _dartdoc_ program throws a _NoSuchMethodError_ because it tries to invoke _nullabilitySuffix_ on a null.

This is from _dartdoc_ version **0.39.0** that comes with **dart-2.12.0-259.14.beta**.

```
% dartdoc
Documenting ssh_key...
-
dartdoc failed: NoSuchMethodError: The getter 'nullabilitySuffix' was called on null.
Receiver: null
Tried calling: nullabilitySuffix
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      SubtypeHelper.isSubtypeOf (package:analyzer/src/dart/element/subtype.dart:51:29)
#2      TypeSystemImpl.isSubtypeOf2 (package:analyzer/src/dart/element/type_system.dart:1162:27)
#3      TypeSystemImpl.isSubtypeOf (package:analyzer/src/dart/element/type_system.dart:1158:12)
#4      TypeSystemImpl._refineNumericInvocationContextNullSafe (package:analyzer/src/dart/element/type_system.dart:1713:11)
#5      TypeSystemImpl.refineNumericInvocationContext (package:analyzer/src/dart/element/type_system.dart:1402:14)
#6      ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:862:24)
#7      InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:326:15)
...
```

To reproduce the problem, clone the "null-safety" branch of the _ssh_key_ repository and run `dartdoc` on it:

https://github.com/hoylen/ssh_key/tree/fa4833d7dfe92e2873d0443c65802cba8eca06e6

```
git clone --single-branch --branch null-safety https://github.com/hoylen/ssh_key.git
cd ssh_key
pub get
dartdoc
```

Note: once this bug has been fixed and I can generate that documentation, that branch will be merged into _master_ and deleted. So if the branch is not present, it means the bug has been fixed.

I was using:

* Dart SDK Version (`dart --version`)
    * Dart SDK version: 2.12.0-259.14.beta (beta) (Wed Feb 17 10:18:35 2021 +0100) on "macos_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable)
    * macOS
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
    * N/A

**Comment by hoylen** [comment]
Moved issue to the _dartdoc_ repository:

https://github.com/dart-lang/dartdoc/issues/2531
