### ISSUE TITLE
vm_service.getObject() crash: type 'ContextRef' is not a subtype of type 'Context'

### ISSUE THREAD

**Issue by fayduan** [dart-lang/sdk#45083]
* Dart SDK version: 2.10.4 (stable)
* vm_service: 5.5.0

vm_service.getRetainingPath() returns some RetainingObject(includes ContextRef);
when I use getObject to get Context, it crash.
**crash maybe happened at the second contextRef, while the first contextRef is normal.**
**It is strange that this error cannot catch.**

```dart
// ... ...
final RetainingPath leakPath = await service.getRetainingPath(mainIsoId, objectId, 500);
// crash maybe happened at the second contextRef, while the first contextRef is normal.
leakPath.elements.forEach((retainingObject) async {
  if (retainingObject.value is ContextRef) {
    final ContextRef contextRef = retainingObject.value;
    try {
      final Obj obj = await service.getObject(_mainIsoId, contextRef.id);    // crashed this line, and cannot catch
    } catch (e) {

    }
  }
}

```
crash as follow (It seems that `getObject()` still return a ContextRef):
```
type 'ContextRef' is not a subtype of type 'Context'
    #0      new Context._fromJson (package:vm_service/src/vm_service.dart:3149:5)
    #1      Context.parse (package:vm_service/src/vm_service.dart:3128:37)
    #2      createServiceObject (package:vm_service/src/vm_service.dart:68:34)
    #3      VmService._processResponse (package:vm_service/src/vm_service.dart:2086:28)
    #4      VmService._processMessageStr (package:vm_service/src/vm_service.dart:2064:7)
    #5      VmService._processMessage (package:vm_service/src/vm_service.dart:2015:7)
    #6      _rootRunUnary (dart:async/zone.dart:1198:47)
    #7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #10     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
    #11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
    #12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
    #13     _rootRun (dart:async/zone.dart:1182:47)
    #14     _CustomZone.run (dart:async/zone.dart:1093:19)
    #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
    #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
    #17     _rootRun (dart:async/zone.dart:1190:13)
    #18     _CustomZone.run (dart:async/zone.dart:1093:19)
    #19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
    #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
    #21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by fayduan** [comment]
Hi @mit-mit @bkonyi,
I debugged this problem, the value of `Context`'s parent as below: 
```
{type: @Context, id: objects/531, length: 1}
```
So the reason of this problem is that the field `parent` of `Context` is `ContextRef` instead of `Context`.
I fixed this problem, please review.
https://dart-review.googlesource.com/c/sdk/+/192880

**Comment by bkonyi** [comment]
Thanks for the submission @fayduan! I'll take a look.

**Comment by fayduan** [comment]
Hi @bkonyi,
Since I have updated `service.md` before, nothing changed after I run `dart tool/generate.dart`.
```bash
~/lib/dart-sdk/sdk/pkg/vm_service [patch-vm-service-bugfix (068484aeba6)] ➜ dart tool/generate.dart
Parsed /Users/fd/proj/lib/dart-sdk/sdk/runtime/vm/service/service.md.
Service protocol version 3.44.0.

Wrote Dart to /Users/fd/proj/lib/dart-sdk/sdk/pkg/vm_service/lib/src/vm_service.dart.
Wrote Java to /Users/fd/proj/lib/dart-sdk/sdk/pkg/vm_service/java/src.
Wrote Dart to /Users/fd/proj/lib/dart-sdk/sdk/pkg/vm_service/example/vm_service_assert.dart.

~/lib/dart-sdk/sdk/pkg/vm_service [patch-vm-service-bugfix (068484aeba6)] ➜ git status
On branch patch-vm-service-bugfix
nothing to commit, working tree clean
```
In addition, `CHANGELOD.md` and `pubspec.yaml` have been updated to `7.0.0-dev`
