### ISSUE TITLE
Failures on Generic metadata test.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#45119]
There are new test failures on [Generic metadata test.](https://dart-review.googlesource.com/c/sdk/+/185583).

The tests
```
language/generic/generic_metadata_test Crash (expected Pass)
language/generic/generic_metadata_test CompileTimeError (expected Pass)
```
are failing on configurations
```
analyzer-asserts-strong-linux
analyzer-asserts-weak-linux
```

The crash is particularly interesting. It crashes with:
```
LateInitializationError: Field 'annotationAst' has not been initialized.
#0      ElementAnnotationImpl.annotationAst (package:analyzer/src/dart/element/element.dart)
#1      ConstantEvaluationEngine.computeDependencies (package:analyzer/src/dart/constant/evaluation.dart:336:39)
#2      _ConstantWalker._computeDependencies (package:analyzer/src/dart/constant/compute.dart:75:22)
#3      _ConstantNode.computeDependencies (package:analyzer/src/dart/constant/compute.dart:43:19)
#4      Node.getDependencies (package:analyzer/src/summary/link.dart:148:40)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:53:40)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:119:18)
#7      computeConstants (package:analyzer/src/dart/constant/compute.dart:26:14)
#8      LibraryAnalyzer._computeConstants (package:analyzer/src/dart/analysis/library_analyzer.dart:253:5)
#9      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:140:5)
#10     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:106:12)
#11     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1321:63)
#12     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#13     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1292:20)
#14     AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1375:26)
#15     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:992:20)
#16     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2012:24)
<asynchronous suspension>

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1350:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1292:20)
#3      AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1375:26)
#4      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:992:20)
#5      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2012:24)
<asynchronous suspension>
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/188980 will fix the crash.

**Comment by NaarGes** [comment]
I'm facing same issue
