### ISSUE TITLE
Syntax highlightning, navigation stops workin on webstorm / intellij

### ISSUE THREAD

**Issue by loisgomez** [dart-lang/sdk#45114]
* Dart SDK Version: 1.24.3
* OS: Linux
* Webstorm: 2020.3
* Dart plugin: 203.6912

After a few `Go to definition` navigation the syntax highlighting and the navigation stops working in both webstorm and intellij.

```
2021-02-25 22:26:18,733 [  11856]  ERROR - braryModifiableModelBridgeImpl - Setting properties with null kind is unsupported 
java.lang.Throwable: Setting properties with null kind is unsupported
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryModifiableModelBridgeImpl.setProperties(LibraryModifiableModelBridgeImpl.kt:259)
	at com.jetbrains.lang.dart.DartFileListener.lambda$updatePackagesLibraryRoots$2(DartFileListener.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1000)
	at com.jetbrains.lang.dart.DartFileListener.updatePackagesLibraryRoots(DartFileListener.java:220)
	at com.jetbrains.lang.dart.DartFileListener.actualizePackagesLibrary(DartFileListener.java:152)
	at com.jetbrains.lang.dart.DartFileListener.lambda$scheduleDartPackageRootsUpdate$0(DartFileListener.java:124)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-02-25 22:26:18,736 [  11859]  ERROR - braryModifiableModelBridgeImpl - WebStorm 2020.3.2  Build #WS-203.7148.54 
2021-02-25 22:26:18,736 [  11859]  ERROR - braryModifiableModelBridgeImpl - JDK: 11.0.9.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-02-25 22:26:18,736 [  11859]  ERROR - braryModifiableModelBridgeImpl - OS: Linux 
2021-02-25 22:26:18,737 [  11860]  ERROR - braryModifiableModelBridgeImpl - Plugin to blame: Dart version: 203.6912 
2021-02-25 22:26:18,737 [  11860]  ERROR - braryModifiableModelBridgeImpl - Last Action:  
2021-02-25 22:26:18,907 [  12030]   INFO - oudConfig.StatusBarInfoManager - === StatusBar.update another widget: null === 
2021-02-25 22:26:19,032 [  12155]   INFO - m.maddyhome.idea.vim.VimPlugin - ideavimrc file isn't found 
2021-02-25 22:26:19,432 [  12555]   INFO - oudConfig.StatusBarInfoManager - === StatusBar.start create === 
2021-02-25 22:26:19,444 [  12567]   INFO - r.local.NodeJsLocalInterpreter - /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js config get prefix=/usr (417 ms) 
2021-02-25 22:26:20,254 [  13377]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 9258 ms 
2021-02-25 22:26:20,354 [  13477]   WARN - .ExternalResourceManagerExImpl - Cannot find standard resource. filename:/standardSchemas/jspxml.dtd class=class com.intellij.jsp.impl.JspResourcesProvider, classLoader:null 
2021-02-25 22:26:21,603 [  14726]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 1083ms; general responsiveness: ok; EDT responsiveness: 1/1 sluggish 
2021-02-25 22:26:21,641 [  14764]   WARN - .ExternalResourceManagerExImpl - Cannot find standard resource. filename:/standardSchemas/jspxml.dtd class=class com.intellij.jsp.impl.JspResourcesProvider, classLoader:null 
2021-02-25 22:26:23,275 [  16398]   INFO - ion.PackageVersionRangeMatcher - Matching 8 done in 87 ms 
2021-02-25 22:26:23,317 [  16440]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 1714ms; general responsiveness: ok; EDT responsiveness: ok 
2021-02-25 22:26:23,326 [  16449]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 1 files to index 
2021-02-25 22:26:23,343 [  16466]   INFO - indexing.UnindexedFilesUpdater - Using 4 threads for indexing 
2021-02-25 22:26:23,417 [  16540]   INFO - yzer.DartAnalysisServerService - Error from unknown, SDK version = 1.24.3, server version = 1.18.0, error code = UNKNOWN_REQUEST: Unknown request 
2021-02-25 22:26:23,450 [  16573]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 124ms; general responsiveness: ok; EDT responsiveness: ok 
2021-02-25 22:26:23,885 [  17008]  ERROR - braryModifiableModelBridgeImpl - Setting properties with null kind is unsupported 
java.lang.Throwable: Setting properties with null kind is unsupported
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryModifiableModelBridgeImpl.setProperties(LibraryModifiableModelBridgeImpl.kt:259)
	at com.jetbrains.lang.dart.DartFileListener.lambda$updatePackagesLibraryRoots$2(DartFileListener.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1000)
	at com.jetbrains.lang.dart.DartFileListener.updatePackagesLibraryRoots(DartFileListener.java:220)
	at com.jetbrains.lang.dart.DartFileListener.actualizePackagesLibrary(DartFileListener.java:152)
	at com.jetbrains.lang.dart.DartFileListener.lambda$scheduleDartPackageRootsUpdate$0(DartFileListener.java:124)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-02-25 22:26:23,889 [  17012]  ERROR - braryModifiableModelBridgeImpl - WebStorm 2020.3.2  Build #WS-203.7148.54 
2021-02-25 22:26:23,889 [  17012]  ERROR - braryModifiableModelBridgeImpl - JDK: 11.0.9.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-02-25 22:26:23,890 [  17013]  ERROR - braryModifiableModelBridgeImpl - OS: Linux 
2021-02-25 22:26:23,891 [  17014]  ERROR - braryModifiableModelBridgeImpl - Plugin to blame: Dart version: 203.6912 
2021-02-25 22:26:23,891 [  17014]  ERROR - braryModifiableModelBridgeImpl - Last Action:  
2021-02-25 22:26:24,499 [  17622]   WARN - .ExternalResourceManagerExImpl - Cannot find standard resource. filename:/standardSchemas/jspxml.dtd class=class com.intellij.jsp.impl.JspResourcesProvider, classLoader:null 
2021-02-25 22:26:24,805 [  17928]   INFO - g.FileBasedIndexProjectHandler - Reindexing refreshed files: 426 to update, calculated in 171ms 
2021-02-25 22:26:24,805 [  17928]   INFO - g.FileBasedIndexProjectHandler - Using 4 threads for indexing 
2021-02-25 22:26:24,978 [  18101]  ERROR - braryModifiableModelBridgeImpl - Setting properties with null kind is unsupported 
java.lang.Throwable: Setting properties with null kind is unsupported
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryModifiableModelBridgeImpl.setProperties(LibraryModifiableModelBridgeImpl.kt:259)
	at com.jetbrains.lang.dart.DartFileListener.lambda$updatePackagesLibraryRoots$2(DartFileListener.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1000)
	at com.jetbrains.lang.dart.DartFileListener.updatePackagesLibraryRoots(DartFileListener.java:220)
	at com.jetbrains.lang.dart.DartFileListener.actualizePackagesLibrary(DartFileListener.java:152)
	at com.jetbrains.lang.dart.DartFileListener.lambda$scheduleDartPackageRootsUpdate$0(DartFileListener.java:124)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-02-25 22:26:24,979 [  18102]  ERROR - braryModifiableModelBridgeImpl - WebStorm 2020.3.2  Build #WS-203.7148.54 
2021-02-25 22:26:24,979 [  18102]  ERROR - braryModifiableModelBridgeImpl - JDK: 11.0.9.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-02-25 22:26:24,979 [  18102]  ERROR - braryModifiableModelBridgeImpl - OS: Linux 
2021-02-25 22:26:24,979 [  18102]  ERROR - braryModifiableModelBridgeImpl - Plugin to blame: Dart version: 203.6912 
2021-02-25 22:26:24,979 [  18102]  ERROR - braryModifiableModelBridgeImpl - Last Action:  
```

**Comment by scheglov** [comment]
@jwren to look at IntelliJ logs, but it seems to me that there is nothing in there.
When semantic highlighting and navigation stop working, this is usually a sign that Dart Analysis Server died.
Try to restart it.
![image](https://user-images.githubusercontent.com/384794/109876754-fc64d480-7c26-11eb-8478-503ebc34ccdb.png)

**Comment by loisgomez** [comment]
@scheglov That is the actual issue.
I can restart the dart analysis server to fix it but It crashes again shortly after. So its not really an option to keep having to restart every few seconds. Let me know if I can provide any further information in some way.

I am seeing the same behaviour in both Intellij and WebStorm.

**Comment by scheglov** [comment]
Maybe your analysis server gets into a cycle.
Do you see it using CPU in the process list?

Can you try to enable Observatory and look (creatively) on the CPU profile?
https://github.com/dart-lang/sdk/issues/44501#issuecomment-784484755

**Comment by loisgomez** [comment]
Enabled Observatory and played / looked around with the CPU profile looking for 100% usages, but I couldn't see anything that looked like a cycle.

Could the issue be in the Intellij Dart plugin code instead?

**Comment by jwren** [comment]
Possibly, of course.  The code that invokes the DAS hasn't been changed in a long time.  We are testing `2020.1` versions of the Dart plugin at this point, there were no big regressions such as the analysis server crashing for all users.

Is the version of your Dart SDK actually `1.24.3`?  This is a very old version at this point.  You can download newer versions here: https://dart.dev/tools/sdk/archive

**Comment by loisgomez** [comment]
> Is the version of your Dart SDK actually 1.24.3? This is a very old version at this point. You can download newer versions here: https://dart.dev/tools/sdk/archive

@jwren Yes, unfortunately the project I am working on at the moment has a big codebase that has not yet been migrated to dart2. So I still need to run dart 1.
Thanks for the help
