### ISSUE TITLE
co19_2/LibTest/io/FileSystemMoveEvent/destination_A01_t02 whent from flaky to RuntimeError on dartk-mac-release-x64

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#45121]
The test
```
co19_2/LibTest/io/FileSystemMoveEvent/destination_A01_t02 RuntimeError (expected Pass)
```
is failing on configurations
```
dartk-mac-release-x64
```

Log:
```
--- Command "vm" (took 45.000644s):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/destination_A01_t02.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
NoSuchMethodError: The getter 'destination' was called on null.
Receiver: null
Tried calling: destination
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _main.<anonymous closure> (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/destination_A01_t02.dart:32:44)
#2      testFileSystemEvent (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:56:7)
<asynchronous suspension>
#3      _main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/destination_A01_t02.dart:28:3)
<asynchronous suspension>
#4      inSandbox (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:24:12)
<asynchronous suspension>
#5      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/destination_A01_t02.dart:20:3)
<asynchronous suspension>

--- Re-run this test:
python tools/test.py -n dartk-mac-release-x64 co19_2/LibTest/io/FileSystemMoveEvent/destination_A01_t02
```

**Comment by alexmarkov** [comment]
This could be fixed by `co19_2` roll https://dart-review.googlesource.com/c/sdk/+/187460.

@whesse Please close this issue if the test starts passing after the roll.

**Comment by alexmarkov** [comment]
Indeed, this test started passing since co19_2 roll https://github.com/dart-lang/sdk/commit/137de39b7a72837a7851eb51389fd5811239f5a3.
