### ISSUE TITLE
out_of_memory_recovery_test fails with unhandled out of memory exception (in _StringBase._interpolate)

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#45145]
at 9876de6838f8e9dc29722141705786403ecc4510
 
```
╰─➤  cd $DH && while (out/DebugX64/dart --old_gen_heap_size=20 --ignore-unrecognized-flags --packages=$DH/sdk/.packages $DH/sdk/tests/standalone_2/out_of_memory_recovery_test.dart); do date; done

>> [SendPort, 1]
<< [1, Okay]
>> [SendPort, 2]
Exhausted heap space, trying to allocate 32 bytes.
Exhausted heap space, trying to allocate 144 bytes.
Unhandled exception:
Out of Memory
#0      _StringBase._interpolate (dart:core-patch/string_patch.dart:855:19)
#1      handleMessage (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/standalone_2/out_of_memory_recovery_test.dart:29:59)
```

**Comment by aam** [comment]
Similarly it fails at _StringBase._concatRangeNative

```
>> [SendPort, 1]
<< [1, Okay]
>> [SendPort, 2]
Exhausted heap space, trying to allocate 32 bytes.
<< [2, Failed: Out of Memory
#0      new _GrowableList._withData (dart:core-patch/growable_array.dart:207:77)
#1      handleRequest (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/standalone_2/out_of_memory_recovery_test.dart:16:14)
#2      handleMessage (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/standalone_2/out_of_memory_recovery_test.dart:27:42)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
]
>> [SendPort, 3]
<< [3, Okay]
>> [SendPort, 4]
Exhausted heap space, trying to allocate 32 bytes.
Exhausted heap space, trying to allocate 496 bytes.
Unhandled exception:
Out of Memory
#0      _StringBase._concatRangeNative (dart:core-patch/string_patch.dart:956:34)
#1      String._concatAll (dart:core-patch/string_patch.dart:1008:26)
#2      _StringBase._interpolate (dart:core-patch/string_patch.dart:876:27)
#3      handleMessage (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/standalone_2/out_of_memory_recovery_test.dart:29:59)
```
