### ISSUE TITLE
segfault at TryAllocateLargeLocked while running out_of_memory_recovery_test

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#45144]
at 9876de6838f8e9dc29722141705786403ecc4510

$ while (out/DebugX64/dart --old_gen_heap_size=20 --ignore-unrecognized-flags --packages=$DH/sdk/.packages $DH/sdk/tests/standalone_2/out_of_memory_recovery_test.dart); do date; done
....

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x7fbac3973068
version=2.13.0-edge.9876de6838f8e9dc29722141705786403ecc4510 (be) (Wed Feb 24 21:23:54 2021 +0000) on "linux_x64"
pid=718601, thread=718620, isolate_group=main(0x55df42d09000), isolate=(nil)((nil))
isolate_instructions=55df415bb5e0, vm_instructions=55df415bb5e0
  pc 0x000055df41a8c1e5 fp 0x00007fbabfafe8e0 dart::FreeList::TryAllocateLargeLocked(long)+0x45
  pc 0x000055df41a9d6c9 fp 0x00007fbabfafe930 dart::PageSpace::TryAllocateDataBumpLocked(dart::FreeList*, long)+0x89
  pc 0x000055df41aa8f7f fp 0x00007fbabfafe9a0 out/DebugX64/dart+0x2108f7f
  pc 0x000055df419bbbb8 fp 0x00007fbabfafe9d0 dart::UntaggedArray::VisitArrayPointers(dart::ArrayPtr, dart::ObjectPointerVisitor*)+0x78
  pc 0x000055df419b8aa1 fp 0x00007fbabfafea10 dart::UntaggedObject::VisitPointersPredefined(dart::ObjectPointerVisitor*, long)+0x151
  pc 0x000055df41aa99f9 fp 0x00007fbabfafea60 out/DebugX64/dart+0x21099f9
  pc 0x000055df41aa8440 fp 0x00007fbabfafeb90 out/DebugX64/dart+0x2108440
  pc 0x000055df41aa5e99 fp 0x00007fbabfafec00 out/DebugX64/dart+0x2105e99
  pc 0x000055df41aa810b fp 0x00007fbabfafec30 out/DebugX64/dart+0x210810b
  pc 0x000055df41a5d63b fp 0x00007fbabfafecd0 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x1cb
  pc 0x000055df41a5e079 fp 0x00007fbabfafed20 dart::ThreadPool::Worker::Main(unsigned long)+0x179
  pc 0x000055df419957b9 fp 0x00007fbabfafee70 out/DebugX64/dart+0x1ff57b9
```

**Comment by aam** [comment]
from flaky test runs: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8861568146158956352/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0
```
/===============================================================================\
| standalone_2/out_of_memory_recovery_test broke (Pass -> Crash, expected Pass) |
\===============================================================================/

--- Command "app_jit" (took 35.000116s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --snapshot=/b/s/w/ir/out/DebugX64/generated_compilations/app_jitk/tests_standalone_2_out_of_memory_recovery_test/out.jitsnapshot --snapshot-kind=app-jit --old_gen_heap_size=20 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/out_of_memory_recovery_test.dart

exit code:
-6

stdout:
>> [SendPort, 1]
<< [1, Okay]
>> [SendPort, 2]
<< [2, Failed: Out of Memory
#0      new _GrowableList._withData (dart:core-patch/growable_array.dart:207:77)
#1      handleRequest (file:///b/s/w/ir/tests/standalone_2/out_of_memory_recovery_test.dart:57:989)
#2      handleMessage (file:///b/s/w/ir/tests/standalone_2/out_of_memory_recovery_test.dart:27:42)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
]
>> [SendPort, 3]
<< [3, Okay]
>> [SendPort, 4]

stderr:
Exhausted heap space, trying to allocate 32 bytes.
Exhausted heap space, trying to allocate 176 bytes.

===== CRASH =====
si_signo=Segmentation fault(11), si_code=2, si_addr=0x7ff408e08061
version=2.12.0-edge.41381e95980577c5ed2008638edf4c5d73693397 (be) (Mon Dec 7 13:17:18 2020 +0000) on "linux_x64"
pid=20803, thread=20901, isolate_group=main(0x55e84b9ddc00), isolate=(nil)((nil))
isolate_instructions=55e84a3a1f80, vm_instructions=55e84a3a1f80
  pc 0x000055e84a861759 fp 0x00007ff3fedfe9a0 dart::PageSpace::TryAllocateDataBumpLocked(dart::FreeList*, long)+0x59
  pc 0x000055e84a86d50b fp 0x00007ff3fedfea10 out/DebugX64/dart+0x1ff050b
  pc 0x000055e84a781169 fp 0x00007ff3fedfea30 dart::GrowableObjectArrayLayout::VisitGrowableObjectArrayPointers(dart::GrowableObjectArrayPtr, dart::ObjectPointerVisitor*)+0x39
  pc 0x000055e84a77f007 fp 0x00007ff3fedfea70 dart::ObjectLayout::VisitPointersPredefined(dart::ObjectPointerVisitor*, long)+0x3c7
  pc 0x000055e84a86df19 fp 0x00007ff3fedfeac0 out/DebugX64/dart+0x1ff0f19
  pc 0x000055e84a86c970 fp 0x00007ff3fedfebf0 out/DebugX64/dart+0x1fef970
  pc 0x000055e84a86a729 fp 0x00007ff3fedfec60 out/DebugX64/dart+0x1fed729
  pc 0x000055e84a86c63b fp 0x00007ff3fedfec90 out/DebugX64/dart+0x1fef63b
  pc 0x000055e84a81fa0b fp 0x00007ff3fedfed30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x1cb
  pc 0x000055e84a820449 fp 0x00007ff3fedfed80 dart::ThreadPool::Worker::Main(unsigned long)+0x179
  pc 0x000055e84a75ba09 fp 0x00007ff3fedfeed0 out/DebugX64/dart+0x1edea09
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -n app_jitk-linux-debug-x64 standalone_2/out_of_memory_recovery_test
```
