### ISSUE TITLE
Failures on [dart2js] Create cycle-free trivial merge algorithm....[vm/compiler] Fix IntConverter canonicalization

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#45151]
```
/====================================================================================\
| standalone_2/io/process_non_ascii_test broke (Pass -> RuntimeError, expected Pass) |
\====================================================================================/

--- Command "vm" (took 12.000984s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --hot-reload-test-mode --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/process_non_ascii_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <-6>) fails.
#0      Expect._fail (package:expect/expect.dart:702:5)
#1      Expect.equals (package:expect/expect.dart:132:5)
#2      main.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/process_non_ascii_test.dart:38:12)
<asynchronous suspension>

--- Re-run this test:
python tools/test.py -n dartk-reload-linux-debug-x64 standalone_2/io/process_non_ascii_test
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8853898667423340592/+/steps/test_results/0/logs/new_test_failures__logs_/0

===========================================================================================

There are new test failures on [[dart2js] Create cycle-free trivial merge algorithm....[vm/compiler] Fix IntConverter canonicalization](https://github.com/dart-lang/sdk/compare/1f828c7cb2b005fe3a278a49433738946f3550fe~...dcd57353459f85beb7bbe415a452c54fd6e9833a).

The tests
```
standalone_2/io/process_non_ascii_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-reload-linux-debug-x64
```

I'll bisect to figure out which commit caused this.

@athomas It would be nice if these infrequent bots would bisect automatically.

**Comment by dcharkes** [comment]
```
tools/build.py -mdebug runtime_kernel && tools/test.py --repeat=100 -n dartk-reload-linux-debug-x64 standalone_2/io/process_non_ascii_test
```

Does not reproduce locally on dcd57353459f85beb7bbe415a452c54fd6e9833a for me.
