### ISSUE TITLE
??

### ISSUE THREAD

**Issue by youssefkhattab98** [dart-lang/sdk#45154]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.6183.87`
- `2.5.2`
- `IC-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.2, server version 1.27.2, error: Analysis failed: E:\Omniful-Inventory-app_y\test\widget_test.dart
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5568:5)
#1      TypeProviderForLink.futureType (package:analyzer/src/summary/link.dart:5484:23)
#2      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5400:35)
#3      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5230:7)
#4      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5666:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5215:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1642:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3870:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3570:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3510:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#17     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#18     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3543:42)
#19     Linker.link (package:analyzer/src/summary/link.dart:4075:35)
#20     _relink (package:analyzer/src/summary/link.dart:312:74)
#21     link (package:analyzer/src/summary/link.dart:126:3)
#22     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:220:25)
#23     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#24     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:219:12)
#25     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1444:23)
#26     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1245:30)
#27     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#28     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#41     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#42     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#43     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#45     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#46     new Future.sync (dart:async/future.dart:224:31)
#47     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _runZoned (dart:async/zone.dart:1516:10)
#51     runZoned (dart:async/zone.dart:1463:12)
#52     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#53     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#54     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#55     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#56     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#57     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#58     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\YOUSSE~1\AppData\Local\Temp\report1.txt.

**Comment by scheglov** [comment]
Please upgrade to a newer version of Dart.
We have just released `2.12.0` today :-)
