### ISSUE TITLE
Concurrent access to isolate flags bit field.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#45169]
```
/===========================================================================================================\
| vm/dart_2/isolates/reload_many_isolates_live_and_die_test is new and failed (RuntimeError, expected Pass) |
\===========================================================================================================/

--- Command "vm" (took 01:06.000011s):
DART_CONFIGURATION=ReleaseTSANX64 out/ReleaseTSANX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/runtime/tests/vm/dart_2/isolates/reload_many_isolates_live_and_die_test.dart

exit code:
255

stdout:
Launching out/ReleaseTSANX64/dart --packages=.packages --snapshot-kind=kernel --snapshot=/b/s/w/itiG3vEc/KQFWVF/test.dart.0.dill /b/s/w/itiG3vEc/KQFWVF/test.dart
stdout: Info: Compiling with sound null safety
Launching out/ReleaseTSANX64/dart --packages=.packages --snapshot-kind=kernel --snapshot=/b/s/w/itiG3vEc/KQFWVF/test.dart.1.dill /b/s/w/itiG3vEc/KQFWVF/test.dart
stdout: Info: Compiling with sound null safety
Launching out/ReleaseTSANX64/dart --enable-vm-service:0 --disable-dart-dev --disable-service-auth-codes --enable-isolate-groups --experimental-enable-isolate-groups-jit file:///b/s/w/itiG3vEc/KQFWVF/test.dart.0.dill
stdout: Observatory listening on http://127.0.0.1:46569/
stdout: Initial child isolates launched
stdout: Waiting for reload to happen ...
stdout:  -> Still waiting ...
stdout:  -> Still waiting ...
Reload file:///b/s/w/itiG3vEc/KQFWVF/test.dart.1.dill (version: 0)
stdout:  -> Still waiting ...
...
stderr: ==================
stderr: WARNING: ThreadSanitizer: data race (pid=27487)
stderr:   Read of size 4 at 0x7b6c001156d8 by thread T4:
stderr:     #0 dart::Isolate::is_system_isolate() const ../../out/ReleaseTSANX64/../../runtime/vm/isolate.h:1390 (dart+0x1e536b6)
stderr:     #1 dart::Isolate::PrintJSON(dart::JSONStream*, bool) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2979 (dart+0x1e536b6)
stderr:     #2 dart::JSONStream::PrintValue(dart::Isolate*, bool) ../../out/ReleaseTSANX64/../../runtime/vm/json_stream.cc:343 (dart+0x1e777e2)
stderr:     #3 dart::JSONArray::AddValue(dart::Isolate*, bool) const ../../out/ReleaseTSANX64/../../runtime/vm/json_stream.h:431 (dart+0x204b3f9)
stderr:     #4 dart::ServiceIsolateVisitor::VisitIsolate(dart::Isolate*) ../../out/ReleaseTSANX64/../../runtime/vm/service.cc:4652 (dart+0x204b3f9)
stderr:     #5 operator() ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:3444 (dart+0x1e579bf)
stderr:     #6 _ZNSt3__28__invokeIRZZN4dart7Isolate13VisitIsolatesEPNS1_14IsolateVisitorEENK3$_3clEPNS1_12IsolateGroupEEUlPS2_E_JS8_EEEDTclclsr3std3__2E7forwardIT_Efp_Espclsr3std3__2E7forwardIT0_Efp0_EEEOSB_DpOSC_ ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/type_traits:3519 (dart+0x1e579bf)
stderr:     #7 void std::__2::__invoke_void_return_wrapper<void>::__call<dart::Isolate::VisitIsolates(dart::IsolateVisitor*)::$_3::operator()(dart::IsolateGroup*) const::{lambda(dart::Isolate*)#1}&, dart::Isolate*>(dart::Isolate::VisitIsolates(dart::IsolateVisitor*)::$_3::operator()(dart::IsolateGroup*) const::{lambda(dart::Isolate*)#1}&, dart::Isolate*&&) ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/__functional_base:348 (dart+0x1e579bf)
stderr:     #8 std::__2::__function::__default_alloc_func<dart::Isolate::VisitIsolates(dart::IsolateVisitor*)::$_3::operator()(dart::IsolateGroup*) const::{lambda(dart::Isolate*)#1}, void (dart::Isolate*)>::operator()(dart::Isolate*&&) ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/functional:1590 (dart+0x1e579bf)
stderr:     #9 void std::__2::__function::__policy_invoker<void (dart::Isolate*)>::__call_impl<std::__2::__function::__default_alloc_func<dart::Isolate::VisitIsolates(dart::IsolateVisitor*)::$_3::operator()(dart::IsolateGroup*) const::{lambda(dart::Isolate*)#1}, void (dart::Isolate*)> >(std::__2::__function::__policy_storage const*, dart::Isolate*) ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/functional:2071 (dart+0x1e579bf)
stderr:     #10 std::__2::__function::__policy_func<void (dart::Isolate*)>::operator()(dart::Isolate*&&) const ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/functional:2203 (dart+0x1e57919)
stderr:     #11 std::__2::function<void (dart::Isolate*)>::operator()(dart::Isolate*) const ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/functional:2473 (dart+0x1e57919)
stderr:     #12 dart::IsolateGroup::ForEachIsolate(std::__2::function<void (dart::Isolate*)>, bool) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2738 (dart+0x1e57919)
stderr:     #13 operator() ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:3443 (dart+0x1e57919)
stderr:     #14 _ZNSt3__28__invokeIRZN4dart7Isolate13VisitIsolatesEPNS1_14IsolateVisitorEE3$_3JPNS1_12IsolateGroupEEEEDTclclsr3std3__2E7forwardIT_Efp_Espclsr3std3__2E7forwardIT0_Efp0_EEEOS9_DpOSA_ ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/type_traits:3519 (dart+0x1e57919)
stderr:     #15 void std::__2::__invoke_void_return_wrapper<void>::__call<dart::Isolate::VisitIsolates(dart::IsolateVisitor*)::$_3&, dart::IsolateGroup*>(dart::Isolate::VisitIsolates(dart::IsolateVisitor*)::$_3&, dart::IsolateGroup*&&) ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/__functional_base:348 (dart+0x1e57919)
stderr:     #16 std::__2::__function::__default_alloc_func<dart::Isolate::VisitIsolates(dart::IsolateVisitor*)::$_3, void (dart::IsolateGroup*)>::operator()(dart::IsolateGroup*&&) ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/functional:1590 (dart+0x1e57919)
stderr:     #17 void std::__2::__function::__policy_invoker<void (dart::IsolateGroup*)>::__call_impl<std::__2::__function::__default_alloc_func<dart::Isolate::VisitIsolates(dart::IsolateVisitor*)::$_3, void (dart::IsolateGroup*)> >(std::__2::__function::__policy_storage const*, dart::IsolateGroup*) ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/functional:2071 (dart+0x1e57919)
stderr:     #18 std::__2::__function::__policy_func<void (dart::IsolateGroup*)>::operator()(dart::IsolateGroup*&&) const ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/functional:2203 (dart+0x1e478f1)
stderr:     #19 std::__2::function<void (dart::IsolateGroup*)>::operator()(dart::IsolateGroup*) const ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/functional:2473 (dart+0x1e478f1)
stderr:     #20 dart::IsolateGroup::ForEach(std::__2::function<void (dart::IsolateGroup*)>) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:791 (dart+0x1e478f1)
stderr:     #21 dart::Isolate::VisitIsolates(dart::IsolateVisitor*) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:3442 (dart+0x1e54ede)
stderr:     #22 dart::Service::PrintJSONForVM(dart::JSONStream*, bool) ../../out/ReleaseTSANX64/../../runtime/vm/service.cc:4727 (dart+0x204a433)
stderr:     #23 dart::GetVM(dart::Thread*, dart::JSONStream*) ../../out/ReleaseTSANX64/../../runtime/vm/service.cc:4762 (dart+0x20522db)
stderr:     #24 dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool) ../../out/ReleaseTSANX64/../../runtime/vm/service.cc:927 (dart+0x2048205)
stderr:     #25 dart::Service::HandleRootMessage(dart::Array const&) ../../out/ReleaseTSANX64/../../runtime/vm/service.cc:965 (dart+0x2048bf5)
stderr:     #26 dart::DN_HelperVMService_SendRootServiceMessage(dart::Isolate*, dart::Thread*, dart::Zone*, dart::NativeArguments*) ../../out/ReleaseTSANX64/../../runtime/lib/vmservice.cc:75 (dart+0x1d80f33)
stderr:     #27 dart::BootstrapNatives::DN_VMService_SendRootServiceMessage(dart::Thread*, dart::Zone*, dart::NativeArguments*) ../../out/ReleaseTSANX64/../../runtime/lib/vmservice.cc:72 (dart+0x1d80f33)
stderr:     #28 dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) ../../out/ReleaseTSANX64/../../runtime/vm/native_entry.cc:140 (dart+0x1e9bec6)
stderr:     #29 <null> <null> (memfd:dart-codespace (deleted)+0x2243)
stderr:     #30 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:147 (dart+0x1dff21b)
stderr:     #31 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&) ../../out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:37 (dart+0x1e03532)
stderr:     #32 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&) ../../out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:792 (dart+0x1e03532)
stderr:     #33 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:1433 (dart+0x1e4c6d7)
stderr:     #34 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:233 (dart+0x1e991b0)
stderr:     #35 dart::MessageHandler::TaskCallback() ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:443 (dart+0x1e99bb4)
stderr:     #36 dart::MessageHandlerTask::Run() ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:31 (dart+0x1e9a653)
stderr:     #37 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158 (dart+0x209191c)
stderr:     #38 dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:323 (dart+0x2092305)
stderr:     #39 dart::ThreadStart(void*) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:153 (dart+0x1f98c22)
stderr:
stderr:   Previous write of size 4 at 0x7b6c001156d8 by thread T16 (mutexes: write M682712522311162000):
stderr:     #0 dart::Isolate::set_is_runnable(bool) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.h:1118 (dart+0x1e50bac)
stderr:     #1 dart::Isolate::MakeRunnableLocked() ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2129 (dart+0x1e50bac)
stderr:     #2 dart::Isolate::MakeRunnable() ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2118 (dart+0x1e50b45)
stderr:     #3 dart::SpawnIsolateTask::EnsureIsRunnable(dart::Isolate*) ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:712 (dart+0x1d60003)
stderr:     #4 dart::SpawnIsolateTask::Run(dart::Isolate*) ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:674 (dart+0x1d60003)
stderr:     #5 dart::SpawnIsolateTask::RunLightweight(char const*) ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:669 (dart+0x1d5fe95)
stderr:     #6 dart::SpawnIsolateTask::Run() ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:604 (dart+0x1d5fb39)
stderr:     #7 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158 (dart+0x209191c)
stderr:     #8 dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:323 (dart+0x2092305)
stderr:     #9 dart::ThreadStart(void*) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:153 (dart+0x1f98c22)
stderr:
stderr:   Location is heap block of size 1792 at 0x7b6c00115600 allocated by thread T16:
stderr:     #0 operator new(unsigned long) ../recipe_cleanup/clangshYTOG/llvm_build_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_new_delete.cpp:64 (dart+0x1b7f447)
stderr:     #1 dart::Isolate::InitIsolate(char const*, dart::IsolateGroup*, Dart_IsolateFlags const&, bool) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:1812 (dart+0x1e4ed5f)
stderr:     #2 dart::Dart::CreateIsolate(char const*, Dart_IsolateFlags const&, dart::IsolateGroup*) ../../out/ReleaseTSANX64/../../runtime/vm/dart.cc:685 (dart+0x1df588b)
stderr:     #3 dart::CreateIsolate(dart::IsolateGroup*, bool, char const*, void*, char**) ../../out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1236 (dart+0x275157b)
stderr:     #4 dart::CreateWithinExistingIsolateGroup(dart::IsolateGroup*, char const*, char**) ../../out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1315 (dart+0x27514a4)
stderr:     #5 dart::SpawnIsolateTask::RunLightweight(char const*) ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:649 (dart+0x1d5fe16)
stderr:     #6 dart::SpawnIsolateTask::Run() ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:604 (dart+0x1d5fb39)
stderr:     #7 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158 (dart+0x209191c)
stderr:     #8 dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:323 (dart+0x2092305)
stderr:     #9 dart::ThreadStart(void*) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:153 (dart+0x1f98c22)
stderr:
...

Unhandled exception:
Expect.equals(expected: <0>, actual: <-6>) fails.
#0      Expect._fail (package:expect/expect.dart:702:5)
#1      Expect.equals (package:expect/expect.dart:132:5)
#2      main.<anonymous closure> (file:///b/s/w/ir/runtime/tests/vm/dart_2/isolates/reload_many_isolates_live_and_die_test.dart:33:12)
<asynchronous suspension>
#3      withTempDir (file:///b/s/w/ir/runtime/tests/vm/dart_2/snapshot_test_helper.dart:123:5)
<asynchronous suspension>
#4      main (file:///b/s/w/ir/runtime/tests/vm/dart_2/isolates/reload_many_isolates_live_and_die_test.dart:17:3)
<asynchronous suspension>

--- Re-run this test:
python tools/test.py -n dartk-tsan-linux-release-x64 vm/dart_2/isolates/reload_many_isolates_live_and_die_test
```

**Comment by aam** [comment]
Sure, will take a look
