### ISSUE TITLE
Invalid analysis options file causes an exception that stops the analysis server

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#45161]
As of the shown version, a syntax error in an an analysis options file causes an exception to be thrown that breaks the analysis server. The stack trace is below.

## Version information

- Dart SDK 2.13.0-edge.5394b45decf90f0c2fe9dd0cbbaa7355b545426d
- Dart IntelliJ 203.7759
- IntelliJ IDEA 2020.3.2
- Mac OS X 10.16

## Details

OptionsFormatException: Duplicate mapping key., <_FileSpan: from <FileLocation: 105 unknown source:6:3> to <FileLocation: 110 unknown source:6:8> "rules">

```
#0      AnalysisOptionsProvider.getOptionsFromString (package:analyzer/src/analysis_options/analysis_options_provider.dart:94:7)
#1      AnalysisOptionsProvider.getOptionsFromSource (package:analyzer/src/analysis_options/analysis_options_provider.dart:64:23)
#2      AnalysisOptionsProvider.getOptionsFromFile (package:analyzer/src/analysis_options/analysis_options_provider.dart:56:12)
#3      ContextLocatorImpl._getExcludedGlobs (package:analyzer/src/dart/analysis/context_locator.dart:295:12)
#4      ContextLocatorImpl._createContextRoots (package:analyzer/src/dart/analysis/context_locator.dart:182:23)
#5      ContextLocatorImpl._createContextRootsIn (package:analyzer/src/dart/analysis/context_locator.dart:233:13)
#6      ContextLocatorImpl.locateRoots (package:analyzer/src/dart/analysis/context_locator.dart:104:7)
#7      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:50:32)
#8      ContextManagerImpl._createAnalysisContexts (package:analysis_server/src/context_manager.dart:388:19)
#9      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:240:5)
#10     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:384:22)
#11     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:348:14)
#12     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:287:16)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:228:38)
#14     _rootRun (dart:async/zone.dart:1354:13)
#15     _CustomZone.run (dart:async/zone.dart:1258:19)
#16     _runZoned (dart:async/zone.dart:1789:10)
#17     runZonedGuarded (dart:async/zone.dart:1777:12)
#18     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:224:5)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163:14)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:103:26)
#21     _rootRunUnary (dart:async/zone.dart:1362:47)
#22     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#33     _rootRunUnary (dart:async/zone.dart:1362:47)
#34     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#46     _rootRunUnary (dart:async/zone.dart:1362:47)
#47     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#51     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#52     _StreamController._add (dart:async/stream_controller.dart:607:7)
#53     _StreamController.add (dart:async/stream_controller.dart:554:5)
#54     _Socket._onData (dart:io-patch/socket_patch.dart:2144:41)
#55     _rootRunUnary (dart:async/zone.dart:1370:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#60     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#61     _StreamController._add (dart:async/stream_controller.dart:607:7)
#62     _StreamController.add (dart:async/stream_controller.dart:554:5)
#63     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1680:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1192:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/188960
