### ISSUE TITLE
`dart fix` crashes when applying prefer_function_declarations_over_variables to Flutter

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#45177]
I tried to enable `prefer_function_declarations_over_variables` in the flutter repository [1] and when running `dart fix` in the `packages/flutter` directory I encountered the following crash:

```
Error from the analysis server: Exception while getting bulk fixes: Exception generating fix for prefer_function_declarations_over_variables in /Users/goderbauer/dev/flutter/packages/flutter/test/animation/listener_helpers_test.dart
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      BulkFixProcessor._fixSingleError (package:analysis_server/src/services/correction/bulk_fix_processor.dart:370:25)
#2      BulkFixProcessor._fixErrorsInLibrary (package:analysis_server/src/services/correction/bulk_fix_processor.dart:305:17)
#3      BulkFixProcessor.fixErrors (package:analysis_server/src/services/correction/bulk_fix_processor.dart:189:15)
<asynchronous suspension>
#4      EditDomainHandler.bulkFixes (package:analysis_server/src/edit/edit_domain.dart:114:27)
<asynchronous suspension>


#0      BulkFixProcessor._fixSingleError (package:analysis_server/src/services/correction/bulk_fix_processor.dart:397:7)
#1      BulkFixProcessor._fixErrorsInLibrary (package:analysis_server/src/services/correction/bulk_fix_processor.dart:305:17)
#2      BulkFixProcessor.fixErrors (package:analysis_server/src/services/correction/bulk_fix_processor.dart:189:15)
<asynchronous suspension>
#3      EditDomainHandler.bulkFixes (package:analysis_server/src/edit/edit_domain.dart:114:27)
<asynchronous suspension>


#0      BulkFixProcessor._fixSingleError (package:analysis_server/src/services/correction/bulk_fix_processor.dart:397:7)
#1      BulkFixProcessor._fixErrorsInLibrary (package:analysis_server/src/services/correction/bulk_fix_processor.dart:305:17)
#2      BulkFixProcessor.fixErrors (package:analysis_server/src/services/correction/bulk_fix_processor.dart:189:15)
<asynchronous suspension>
#3      EditDomainHandler.bulkFixes (package:analysis_server/src/edit/edit_domain.dart:114:27)
<asynchronous suspension>
```

[1] https://github.com/flutter/flutter/blob/679b8c29829e7a58c1d0febb7a8dd24fc17abb80/analysis_options.yaml#L162

**Comment by goderbauer** [comment]
Similar crash happens when enabling `avoid_unnecessary_containers` and running `dart fix`:

```
Error from the analysis server: Exception while getting bulk fixes: Exception generating fix for avoid_unnecessary_containers in /Users/goderbauer/dev/flutter/packages/flutter/test/rendering/viewport_test.dart
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      BulkFixProcessor._fixSingleError (package:analysis_server/src/services/correction/bulk_fix_processor.dart:370:25)
#2      BulkFixProcessor._fixErrorsInLibrary (package:analysis_server/src/services/correction/bulk_fix_processor.dart:305:17)
#3      BulkFixProcessor.fixErrors (package:analysis_server/src/services/correction/bulk_fix_processor.dart:189:15)
<asynchronous suspension>
#4      EditDomainHandler.bulkFixes (package:analysis_server/src/edit/edit_domain.dart:114:27)
<asynchronous suspension>


#0      BulkFixProcessor._fixSingleError (package:analysis_server/src/services/correction/bulk_fix_processor.dart:397:7)
#1      BulkFixProcessor._fixErrorsInLibrary (package:analysis_server/src/services/correction/bulk_fix_processor.dart:305:17)
#2      BulkFixProcessor.fixErrors (package:analysis_server/src/services/correction/bulk_fix_processor.dart:189:15)
<asynchronous suspension>
#3      EditDomainHandler.bulkFixes (package:analysis_server/src/edit/edit_domain.dart:114:27)
<asynchronous suspension>


#0      BulkFixProcessor._fixSingleError (package:analysis_server/src/services/correction/bulk_fix_processor.dart:397:7)
#1      BulkFixProcessor._fixErrorsInLibrary (package:analysis_server/src/services/correction/bulk_fix_processor.dart:305:17)
#2      BulkFixProcessor.fixErrors (package:analysis_server/src/services/correction/bulk_fix_processor.dart:189:15)
<asynchronous suspension>
#3      EditDomainHandler.bulkFixes (package:analysis_server/src/edit/edit_domain.dart:114:27)
<asynchronous suspension>
```

**Comment by pq** [comment]
@goderbauer, is this applied to `HEAD`?  

https://github.com/flutter/flutter/blob/679b8c29829e7a58c1d0febb7a8dd24fc17abb80/packages/flutter/test/rendering/viewport_test.dart

**Comment by goderbauer** [comment]
Yeah, I am seeing this at HEAD at sha `679b8c29829e7a58c1d0febb7a8dd24fc17abb80`.

**Comment by pq** [comment]
Thanks!  That'll be useful to repro.

**Comment by pq** [comment]
PS: thanks a million for this catch.  Nasty bug but easy to fix once spotted!

(Aside: this is exactly the kind of bug that NNBD guards against 😬 .  It'll be great to get server migrated! 🎉 )

**Comment by goderbauer** [comment]
Thanks for the quick fix, @pq! 🚀
