### ISSUE TITLE
Dart executable segfaults when cross compiling 2.12.0 (for flutter 2.0) for arm32

### ISSUE THREAD

**Issue by ardera** [dart-lang/sdk#45185]
Hello,
flutter 2.0 was released today and right now I'm in the process of building the engine binaries for arm32 & arm64 on my linux x64 machine. That worked more or less fine in the past (there's always some things that break of course, nothing major though)

However, while building the arm64 binaries works fine, the arm32 binaries don't. It mostly works, but then it gets to the point where it builds the dart snapshots (for example `frontend_server.dart.snapshot`) using the dart executable inside `clang_x64/dart`, where it crashes with an error message. Tried executing the dart executable without any arguments, same crash.

Exact error message:
```
hannes@pop-os:~/devel/flutter_engine/engine_out/out/linux_debug_arm/clang_x64$ ./dart 
Failed to start the Dart CLI isolate
(null).

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x7fe4f84dd0fc
version=2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "linux_simarm"
pid=62859, thread=62861, isolate_group=vm-service(0x7fe508000e90), isolate=vm-service(0x7fe508006e70)
isolate_instructions=17f9180, vm_instructions=17f9180
Stack dump aborted because InitialRegisterCheck failed.
Abgebrochen (Speicherabzug geschrieben)
```

I modified the build file so it's compiled with `-O0 -ggdb`. Error still happens (of course), here's the backtrace:
```
hannes@pop-os:~/devel/flutter_engine/engine_out/out/linux_debug_arm/clang_x64/exe.unstripped$ gdb dart core
GNU gdb (Ubuntu 9.2-0ubuntu2) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from dart...
[New LWP 62880]
[New LWP 62878]
[New LWP 62879]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./dart'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
[Current thread is 1 (Thread 0x7f12cdb3f640 (LWP 62880))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007f12ce0e3864 in __GI_abort () at abort.c:79
#2  0x00000000017e963d in dart::bin::segv_handler (signal=<optimized out>, siginfo=0x7f12cdb3e430, context=<optimized out>) at ../../../engine/src/third_party/dart/runtime/bin/platform_linux.cc:36
#3  <signal handler called>
#4  0x00007f12b045d0fc in ?? ()
#5  0x00000000019752c8 in dart::DartEntry::InvokeCode (code=..., arguments_descriptor=..., arguments=..., thread=thread@entry=0x7f12c0007820) at ../../../engine/src/third_party/dart/runtime/vm/dart_entry.cc:181
#6  0x00000000019750ea in dart::DartEntry::InvokeFunction (function=..., arguments=..., arguments_descriptor=..., current_sp=<optimized out>) at ../../../engine/src/third_party/dart/runtime/vm/dart_entry.cc:147
#7  0x0000000001a04979 in dart::Library::Invoke (this=<optimized out>, function_name=..., args=..., arg_names=..., respect_reflectable=false, check_is_entrypoint=false) at ../../../engine/src/third_party/dart/runtime/vm/object.cc:13032
#8  0x0000000001cdee28 in Dart_Invoke (target=<optimized out>, name=<optimized out>, number_of_arguments=<optimized out>, arguments=<optimized out>) at ../../../engine/src/third_party/dart/runtime/vm/dart_api_impl.cc:4687
#9  0x00000000018fc9d8 in dart::bin::DartUtils::PrepareBuiltinLibrary (builtin_lib=builtin_lib@entry=0x7f12c0008e60, internal_lib=internal_lib@entry=0x7f12c0008e50, is_service_isolate=true, trace_loading=false)
    at ../../../engine/src/third_party/dart/runtime/bin/dartutils.cc:470
#10 0x00000000018fcf29 in dart::bin::DartUtils::PrepareForScriptLoading (is_service_isolate=<optimized out>, trace_loading=false) at ../../../engine/src/third_party/dart/runtime/bin/dartutils.cc:585
#11 0x00000000017d94f5 in dart::bin::VmService::Setup (server_ip=0x209aea "localhost", server_port=-1, dev_mode_server=false, auth_codes_disabled=false, write_service_info_filename=0x0, trace_loading=false, deterministic=false, 
    enable_service_port_fallback=<optimized out>, wait_for_dds_to_advertise_service=<optimized out>) at ../../../engine/src/third_party/dart/runtime/bin/vmservice_impl.cc:132
#12 0x00000000017dd192 in dart::bin::CreateAndSetupServiceIsolate (script_uri=0x21e60b "vm-service", packages_config=0x0, flags=0x7f12cdb3ec88, error=0x7f12cdb3ec80, exit_code=<optimized out>)
    at ../../../engine/src/third_party/dart/runtime/bin/main.cc:557
#13 dart::bin::CreateIsolateGroupAndSetup (script_uri=0x21e60b "vm-service", main=<optimized out>, package_root=package_root@entry=0x0, package_config=package_config@entry=0x0, flags=flags@entry=0x7f12cdb3ec88, callback_data=<optimized out>, 
    callback_data@entry=0x0, error=<optimized out>) at ../../../engine/src/third_party/dart/runtime/bin/main.cc:842
#14 0x0000000001ab7792 in dart::RunServiceTask::Run (this=0x29074b0) at ../../../engine/src/third_party/dart/runtime/vm/service_isolate.cc:356
#15 0x0000000001ad1579 in dart::ThreadPool::WorkerLoop (this=this@entry=0x28f8730, worker=worker@entry=0x29038c0) at ../../../engine/src/third_party/dart/runtime/vm/thread_pool.cc:158
#16 0x0000000001ad1807 in dart::ThreadPool::Worker::Main (args=43006144) at ../../../engine/src/third_party/dart/runtime/vm/thread_pool.cc:323
#17 0x0000000001a49ae1 in dart::ThreadStart (data_ptr=<optimized out>) at ../../../engine/src/third_party/dart/runtime/vm/os_thread_linux.cc:153
#18 0x00007f12ce3ff590 in start_thread (arg=0x7f12cdb3f640) at pthread_create.c:463
#19 0x00007f12ce1d6223 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Seems like a pretty generic backtrace to me... Just invokes some dart function and then segfaults. [Here's](https://1drv.ms/u/s!AsNHmDqMr-aVg5NUgYAmvoXNOulvyA?e=IxeVOd) the unstripped dart binary and core dump just in case. Btw the `gen_snapshot` executable that resides in the same directory as the `dart` exe works fine it seems.

**Comment by mraleph** [comment]
I'd make a guess that it tries to run mismatched snapshot (e.g. X64 app-jit snapshot on SIMARM_X64 binary). You should file a bug against Flutter so that they fix their build rules. I don't think it is necessarily Dart's problem, but rather a problem with Flutter Engine build rules.

**Comment by ardera** [comment]
Okay, thanks, I'll do that!

**Comment by mit-mit** [comment]
Closing as a duplicate for now. @ardera just let us know if we need to re-open it here on the Dart side.

**Comment by ardera** [comment]
Sure, yeah it looks like its a flutter problem.
