### ISSUE TITLE
dart migrate fails with an exception 

### ISSUE THREAD

**Issue by Sameerkash** [dart-lang/sdk#45203]
`dart migrate` is failing with an exception, this might be package-specific since I migrated a few other packages today and it worked fine.

The package I tried to migrate - https://github.com/Sameerkash/stacked/tree/master/packages/stacked 

<details>

```

 dart migrate
Migrating /Volumes/FAST/Projects/stacked/packages/stacked

See https://dart.dev/go/null-safety-migration for a migration guide.

Note: more than one project found; migrating the top-level project.

Analyzing project...
[-----------------------------------------------------------------------------------------------------------------------------------------------/]No analysis issues found.

Generating migration suggestions...
[-----------------------------------/                                                                                                            ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.12.0) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

Bad state: Unrelated types: class ChangeNotifier implements Listenable and class DynamicSourceViewModel<T> extends ReactiveViewModel* at offset 5557 in /Volumes/FAST/Projects/stacked/packages/stacked/lib/src/state_management/view_model_builder.dart (model.changeSource)

#0      DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:67:10)
#1      DecoratedClassHierarchy.asInstanceOf (package:nnbd_migration/src/decorated_class_hierarchy.dart:38:18)
#2      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:259:16)
#3      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:2997:20)
#4      EdgeBuilder.visitPrefixedIdentifier (package:nnbd_migration/src/edge_builder.dart:1405:14)
#5      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8257:49)
#6      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#7      EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:486:22)
#8      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:967:49)
#9      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#10     EdgeBuilder._checkExpressionNotNull (package:nnbd_migration/src/edge_builder.dart:1980:20)
#11     EdgeBuilder.visitIfStatement (package:nnbd_migration/src/edge_builder.dart:1021:5)
#12     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5705:49)
#13     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#14     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#15     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#16     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#17     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#18     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#19     EdgeBuilder.visitIfStatement.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:1037:25)
#20     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#21     EdgeBuilder.visitIfStatement (package:nnbd_migration/src/edge_builder.dart:1036:28)
#22     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5705:49)
#23     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#24     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#25     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#26     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#27     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#28     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#29     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#30     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:324:45)
#31     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:55)
#32     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#33     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#34     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2488:7)
#35     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#36     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#37     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#38     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#39     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#40     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#41     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#42     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#43     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#44     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:51)
#45     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#46     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#47     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#48     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#49     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#50     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#51     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1154:19)
#52     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:28)
#53     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#54     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1152:5)
<asynchronous suspension>
#55     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#56     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#57     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#58     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#59     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#60     main (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```
</details>

```
dart --version
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.0.0, on macOS 11.0.1 20B50 darwin-x64, locale en-US)
```

**Comment by Sameerkash** [comment]
@srawlins  Can I get any help with this as it is preventing migration of the package?

**Comment by srawlins** [comment]
I recommend a [migrating by hand](https://dart.dev/null-safety/migration-guide#migrating-by-hand).

**Comment by stereotype441** [comment]
> I recommend a [migrating by hand](https://dart.dev/null-safety/migration-guide#migrating-by-hand).

You can also try running the migration tool with the `--ignore-exceptions` option.  This may produce a less accurate migration, so you may have to fix some compile errors afterwards, but it's often still more convenient than a hand migration.

**Comment by Sameerkash** [comment]
> > I recommend a [migrating by hand](https://dart.dev/null-safety/migration-guide#migrating-by-hand).
> 
> You can also try running the migration tool with the `--ignore-exceptions` option. This may produce a less accurate migration, so you may have to fix some compile errors afterwards, but it's often still more convenient than a hand migration.

Yup did that, almost worked out fine.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
