### ISSUE TITLE
[CFE] Parser crash in code involving undefined type.

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#45251]
**Issue:**

Parser crash on an undefined type.

Dart version: Dart SDK version: 2.13.0-97.0.dev

**Repro:** 

compile following code:

```
class F {
  final Map<String, Undefined> bar = Map<String, List<int>>{};

  void main() {
    print(bar);
  }
}
```

**Expected:**

`Undefined` is not a type

**Result:**
```Crash when compiling file:///Users/annagrin/source/try/parserbug.dart,
at character offset null:
type 'ParserRecovery' is not a subtype of type 'TypeBuilder'
#0      OutlineBuilder._endClassMethod (package:front_end/src/fasta/source/outline_builder.dart:1066:17)
#1      OutlineBuilder.endClassMethod (package:front_end/src/fasta/source/outline_builder.dart:947:5)
#2      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3944:20)
#3      Parser.parseInvalidOperatorDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7371:19)
#4      Parser.recoverFromInvalidMember (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7417:14)
#5      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3629:16)
#6      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3345:15)
#7      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1966:13)
#8      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1924:14)
#9      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
#10     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
#11     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#12     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:451:37)
<asynchronous suspension>
#13     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:254:7)
<asynchronous suspension>
#14     SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:345:5)
<asynchronous suspension>
#15     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:340:7)
<asynchronous suspension>
#16     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#17     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:103:9)
<asynchronous suspension>
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#19     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#20     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#21     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#22     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#23     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#24     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>
#0      OutlineBuilder._endClassMethod (package:front_end/src/fasta/source/outline_builder.dart:1066:17)
#1      OutlineBuilder.endClassMethod (package:front_end/src/fasta/source/outline_builder.dart:947:5)
#2      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3944:20)
#3      Parser.parseInvalidOperatorDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7371:19)
#4      Parser.recoverFromInvalidMember (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7417:14)
#5      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3629:16)
#6      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3345:15)
#7      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1966:13)
#8      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1924:14)
#9      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
#10     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
#11     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#12     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:451:37)
<asynchronous suspension>
#13     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:254:7)
<asynchronous suspension>
#14     SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:345:5)
<asynchronous suspension>
#15     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:340:7)
<asynchronous suspension>
#16     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#17     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:103:9)
<asynchronous suspension>
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#19     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#20     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#21     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#22     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#23     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#24     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>

**Comment by johnniwinther** [comment]
With asserts enabled we hit an assertion error in the parser:
```
pkg/front_end/testcases/general/issue45251.dart:6:50: Error: Expected ';' after this.
  final Map<String, Undefined> bar = Map<String, List<int>>{};
                                                 ^^^^
pkg/front_end/testcases/general/issue45251.dart:6:54: Error: Operator declarations must be preceded by the keyword 'operator'.
Try adding the keyword 'operator'.
  final Map<String, Undefined> bar = Map<String, List<int>>{};
                                                     ^
pkg/front_end/testcases/general/issue45251.dart:6:54: Error: The built-in identifier '<' can't be used as a type.
  final Map<String, Undefined> bar = Map<String, List<int>>{};
                                                     ^
Unhandled exception:
Crash when compiling file:///c:/src/dart-repo2/sdk/pkg/front_end/testcases/general/issue45251.dart,
at character offset null:
'package:_fe_analyzer_shared/src/parser/parser_impl.dart': Failed assertion: line 3793 pos 12: 'token.next == (getOrSet ?? name)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3793:12)
#3      Parser.parseInvalidOperatorDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7371:19)
#4      Parser.recoverFromInvalidMember (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7417:14)
#5      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3629:16)
#6      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3345:15)
#7      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1966:13)
#8      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1924:14)
#9      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
#10     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
#11     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#12     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:451:37)
<asynchronous suspension>
#13     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:254:7)
<asynchronous suspension>
#14     SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:345:5)
<asynchronous suspension>
#15     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:340:7)
<asynchronous suspension>
#16     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#17     CompileTask.buildOutline (file:///C:/src/dart-repo2/sdk/pkg/front_end/tool/_fasta/entry_points.dart:334:19)
<asynchronous suspension>
#18     CompileTask.compile (file:///C:/src/dart-repo2/sdk/pkg/front_end/tool/_fasta/entry_points.dart:365:9)
<asynchronous suspension>
#19     compile.<anonymous closure>.<anonymous closure> (file:///C:/src/dart-repo2/sdk/pkg/front_end/tool/_fasta/entry_points.dart:247:14)
<asynchronous suspension>
#20     compile.<anonymous closure> (file:///C:/src/dart-repo2/sdk/pkg/front_end/tool/_fasta/entry_points.dart:240:12)
<asynchronous suspension>
#21     runProtectedFromAbort (file:///C:/src/dart-repo2/sdk/pkg/front_end/tool/_fasta/command_line.dart:508:12)
<asynchronous suspension>
#22     compile (file:///C:/src/dart-repo2/sdk/pkg/front_end/tool/_fasta/entry_points.dart:239:10)
<asynchronous suspension>
#23     compileEntryPoint (file:///C:/src/dart-repo2/sdk/pkg/front_end/tool/_fasta/entry_points.dart:75:5)
<asynchronous suspension>
```

@jensjoha Can you take a look at the parser error? - we seem to give very much of the rails on this one.

**Comment by jensjoha** [comment]
I agree we should do better here, but only expecting `Undefined is not a type` is wrong. The code says "final Map<String, Undefined> bar = Map<String, List<int>>**{}**;" --- replacing with the correct parenthesis instead and everything's fine. Clearly it should idealy say something along those lines instead. I'll look into that.

**Comment by jensjoha** [comment]
So this is what's happening:

- When it's about to parse `<String, List<int>>` as type parameters for `Map` it doesn't because it ends with `{}`. (It explicitly checks if it ends with `(` for it to parse as method type arguments (`computeMethodTypeArguments`) --- and it doesn't.)
- It thus concludes that there are no type parameters and parses it as (logically) `final Type fieldName1 = a < b, fieldName2` (at which point there's no new initializer (`=`) and no new field (`,`) so the field definition must be done. It recovers by inserting a semi-colon (`;`).
- Now it needs to parse `<int>>{};`. It finds that probably `operator` is missing. (etc)

I don't have any great ideas for recovering better here... `computeMethodTypeArguments` could catch `{` specifically and issue an error, but otherwise pretend like everything is fine, but I'm not sure if that would have unforeseen consequences... Thoughts, @johnniwinther and/or @bwilkerson ?

**Comment by jensjoha** [comment]
Oh, yeah, so ignoring `Map` (i.e. `final Map<String, Undefined> bar = <String, List<int>>{};` would also be fine. I've got a recovery for that currently testing in the CQ --- hopefully it will be send for review soon.
