### ISSUE TITLE
NoSuchMethodError: The getter 'flow' was called on null.

### ISSUE THREAD

**Issue by jeiea** [dart-lang/sdk#45292]
## What I did
I upgraded one of my flutter project dependency(swipeable_page_route) and `flutter pub run build_runner watch --delete-conflicting-outputs`

## Expected behavior
The build_runner task should complete. At least current exception message is hard to understand.

## Actual behavior
```
> Executing task: /Users/jeiea/.asdf/installs/flutter/2.0.0-stable/bin/flutter pub run build_runner watch --delete-conflicting-outputs <

[INFO] Generating build script...
[INFO] Generating build script completed, took 423ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 11.0s

[INFO] There was output on stdout while compiling the build script snapshot, run with `--verbose` to see it (you will need to run a `clean` first to re-snapshot).

[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 12ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 200ms

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 629ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] 1.0s elapsed, 15/31 actions completed.
[INFO] 2.1s elapsed, 105/120 actions completed.
[INFO] 3.1s elapsed, 186/201 actions completed.
[INFO] 4.2s elapsed, 192/208 actions completed.
[INFO] 5.2s elapsed, 192/208 actions completed.
[INFO] 6.2s elapsed, 206/222 actions completed.
[INFO] 7.4s elapsed, 210/224 actions completed.
[INFO] 8.4s elapsed, 211/227 actions completed.
[INFO] 14.7s elapsed, 211/227 actions completed.
[INFO] 17.2s elapsed, 212/228 actions completed.
[SEVERE] json_serializable:json_serializable on bin/build.dart:

NoSuchMethodError: The getter 'flow' was called on null.
Receiver: null
Tried calling: flow
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ResolverVisitor.startNullAwarePropertyAccess (package:analyzer/src/generated/resolver.dart:758:23)
#2      ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:1730:5)
#3      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8398:49)
#4      BinaryExpressionResolver._resolveIfNull (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:147:10)
#5      BinaryExpressionResolver.resolve (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:68:7)
#6      ResolverVisitor.visitBinaryExpression (package:analyzer/src/generated/resolver.dart:897:31)
#7      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:954:49)
#8      ParenthesizedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7918:18)
#9      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1694:10)
#10     UnifyingAstVisitor.visitParenthesizedExpression (package:analyzer/dart/ast/visitor.dart:3381:7)
#11     ResolverVisitor.visitParenthesizedExpression (package:analyzer/src/generated/resolver.dart:1708:11)
#12     ParenthesizedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7914:15)
#13     BinaryExpressionResolver._resolveUserDefinable (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:253:10)
#14     BinaryExpressionResolver.resolve (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:73:7)
#15     ResolverVisitor.visitBinaryExpression (package:analyzer/src/generated/resolver.dart:897:31)
#16     BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:954:49)
#17     ResolverVisitor.visitConstructorFieldInitializer (package:analyzer/src/generated/resolver.dart:1159:22)
#18     ConstructorFieldInitializerImpl.accept (package:analyzer/src/dart/ast/ast.dart:2629:15)
#19     AstResolver.resolve (package:analyzer/src/summary2/ast_resolver.dart:85:10)
#20     ConstructorInitializerResolver._initializers (package:analyzer/src/summary2/constructor_initializer_resolver.dart:68:20)
#21     ConstructorInitializerResolver._constructor (package:analyzer/src/summary2/constructor_initializer_resolver.dart:54:5)
#22     ConstructorInitializerResolver.resolve (package:analyzer/src/summary2/constructor_initializer_resolver.dart:31:11)
#23     LibraryBuilder.resolveConstructors (package:analyzer/src/summary2/library_builder.dart:240:53)
#24     Linker._resolveConstructors (package:analyzer/src/summary2/link.dart:210:15)
#25     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:95:5)
#26     Linker.link (package:analyzer/src/summary2/link.dart:76:5)
#27     link (package:analyzer/src/summary2/link.dart:32:10)
#28     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:215:24)
#29     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#30     SetMixin.forEach (dart:collection/set.dart:142:30)
#31     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#32     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#33     SetMixin.forEach (dart:collection/set.dart:142:30)
#34     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#35     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#36     SetMixin.forEach (dart:collection/set.dart:142:30)
#37     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#38     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#39     SetMixin.forEach (dart:collection/set.dart:142:30)
#40     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#41     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#42     SetMixin.forEach (dart:collection/set.dart:142:30)
#43     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#44     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#45     SetMixin.forEach (dart:collection/set.dart:142:30)
#46     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#47     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#48     SetMixin.forEach (dart:collection/set.dart:142:30)
#49     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#50     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:262:17)
#51     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#52     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:260:12)
#53     AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1550:25)
#54     _rootRun (dart:async/zone.dart:1354:13)
#55     _CustomZone.run (dart:async/zone.dart:1258:19)
#56     _runZoned (dart:async/zone.dart:1788:10)
#57     runZoned (dart:async/zone.dart:1710:10)
#58     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#59     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1536:33)
#60     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1464:28)
#61     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#62     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1462:20)
#63     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1020:34)
#64     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2013:24)
<asynchronous suspension>


[INFO] 19.0s elapsed, 214/230 actions completed.
[INFO] 20.1s elapsed, 214/230 actions completed.
[INFO] 21.2s elapsed, 214/230 actions completed.
[INFO] 22.3s elapsed, 214/230 actions completed.
[INFO] 23.4s elapsed, 214/230 actions completed.
[INFO] 24.4s elapsed, 214/230 actions completed.
[INFO] 25.4s elapsed, 214/230 actions completed.
(...never terminates)
```

## Additional context
**Dart SDK Version:**
```
➜ dart --version
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"
➜ flutter --version
Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (7 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```
**Whether you are using Windows, MacOSX, or Linux (if applicable)**: macOS, as the above.

<details>
<summary>pubspec.lock diff</summary>

```
git:(build-fail) git diff -U6 HEAD~1 pubspec.lock
diff --git a/pubspec.lock b/pubspec.lock
index cf70089..d647e08 100644
--- a/pubspec.lock
+++ b/pubspec.lock
@@ -46,13 +46,13 @@ packages:
   black_hole_flutter:
     dependency: transitive
     description:
       name: black_hole_flutter
       url: "https://pub.dartlang.org"
     source: hosted
-    version: "0.2.16"
+    version: "0.3.0"
   boolean_selector:
     dependency: transitive
     description:
       name: boolean_selector
       url: "https://pub.dartlang.org"
     source: hosted
@@ -229,19 +229,12 @@ packages:
     dependency: transitive
     description:
       name: dart_style
       url: "https://pub.dartlang.org"
     source: hosted
     version: "1.3.12"
-  dartx:
-    dependency: transitive
-    description:
-      name: dartx
-      url: "https://pub.dartlang.org"
-    source: hosted
-    version: "0.5.0"
   dio:
     dependency: "direct main"
     description:
       name: dio
       url: "https://pub.dartlang.org"
     source: hosted
@@ -542,13 +535,13 @@ packages:
   list_diff:
     dependency: transitive
     description:
       name: list_diff
       url: "https://pub.dartlang.org"
     source: hosted
-    version: "1.3.2"
+    version: "2.0.0"
   logger:
     dependency: "direct main"
     description:
       name: logger
       url: "https://pub.dartlang.org"
     source: hosted
@@ -926,19 +919,33 @@ packages:
     dependency: transitive
     description:
       name: string_scanner
       url: "https://pub.dartlang.org"
     source: hosted
     version: "1.1.0"
+  supercharged:
+    dependency: transitive
+    description:
+      name: supercharged
+      url: "https://pub.dartlang.org"
+    source: hosted
+    version: "2.0.0"
+  supercharged_dart:
+    dependency: transitive
+    description:
+      name: supercharged_dart
+      url: "https://pub.dartlang.org"
+    source: hosted
+    version: "2.0.0"
   swipeable_page_route:
     dependency: "direct main"
     description:
       name: swipeable_page_route
       url: "https://pub.dartlang.org"
     source: hosted
-    version: "0.1.6"
+    version: "0.2.1"
   synchronized:
     dependency: transitive
     description:
       name: synchronized
       url: "https://pub.dartlang.org"
     source: hosted
@@ -968,19 +975,12 @@ packages:
     dependency: transitive
     description:
       name: test_core
       url: "https://pub.dartlang.org"
     source: hosted
     version: "0.3.15"
-  time:
-    dependency: transitive
-    description:
-      name: time
-      url: "https://pub.dartlang.org"
-    source: hosted
-    version: "1.4.1"
   timing:
     dependency: transitive
     description:
       name: timing
       url: "https://pub.dartlang.org"
     source: hosted
```
</details>

**Comment by devoncarew** [comment]
Thanks for the report! Can you include the version of package:analyzer in use - the one that gets resolved by pub? You could be able to see that in your .packages file / pubspec.lock file / .dart_tool/package_config.json file.

**Comment by jeiea** [comment]
```
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.41.2"
```
The analyzer version was not changed during upgrade.

**Comment by devoncarew** [comment]
Gotcha, thanks for the info. You might try with a more recent version of the analyzer - that would help us know whether this is an issue in the current codebase. Both `1.0.0` and `1.1.0` are available.

**Comment by jeiea** [comment]
I can't use latest analyzer due to constraint solving failure. Several packages are wired and it seems it's not solvable simply at least by `dependency_overrides`. Maybe I need time the packages to be updated first. Close this for now.
