### ISSUE TITLE
dart2js compiler is crash 

### ISSUE THREAD

**Issue by renatoaugustofranca** [dart-lang/sdk#45305]
Running: `flutter build web` command line

This tracker is for issues related to:

* dart2js

* MacOS Big Sur 11.2.3

* Stack trace:

The compiler crashed: NoSuchMethodError: The getter 'classNode' was called on null.
Receiver: null
Tried calling: classNode
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      StaticTypeVisitor.visitForInStatement (package:compiler/src/ir/static_type.dart:1242:33)
#2      ForInStatement.accept (package:kernel/ast.dart:7452:43)
#3      StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:79:18)
#4      StaticTypeVisitor.visitBlock (package:compiler/src/ir/static_type.dart:978:22)
#5      Block.accept (package:kernel/ast.dart:7048:43)
#6      StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:79:18)
#7      StaticTypeVisitor.visitTryCatch (package:compiler/src/ir/static_type.dart:1312:5)
#8      TryCatch.accept (package:kernel/ast.dart:7827:43)
#9      StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:79:18)
#10     StaticTypeVisitor.visitBlock (package:compiler/src/ir/static_type.dart:978:22)
#11     Block.accept (package:kernel/ast.dart:7048:43)
#12     StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:79:18)
#13     StaticTypeVisitor.visitProcedure (package:compiler/src/ir/static_type.dart:1402:5)
#14     Procedure.accept (package:kernel/ast.dart:2560:40)
#15     KernelToElementMapImpl.computeWorldImpact (package:compiler/src/kernel/element_map_impl.dart:1412:12)
#16     KernelWorkItem.run.<anonymous closure>.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:395:47)
#17     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#18     KernelWorkItem.run.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:394:28)
#19     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#20     KernelWorkItem.run (package:compiler/src/kernel/kernel_strategy.dart:369:26)
#21     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:511:70)
#22     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#23     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:511:32)
#24     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#25     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:509:28)
#26     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:800:15)
#27     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:507:18)
#28     ResolutionEnqueuer._forEach (package:compiler/src/enqueue.dart:450:12)
#29     ResolutionEnqueuer.forEach (package:compiler/src/enqueue.dart:466:5)
#30     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:503:16)
#31     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#32     Compiler.emptyQueue (package:compiler/src/compiler.dart:502:14)
#33     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:528:7)
#34     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#35     Compiler.processQueue (package:compiler/src/compiler.dart:521:14)
#36     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:380:5)
#37     Compiler.compileFromKernel.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:459:17)
#38     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#39     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:458:44)
#40     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#41     Compiler.compileFromKernel (package:compiler/src/compiler.dart:457:14)
#42     Compiler.runInternal (package:compiler/src/compiler.dart:298:13)
<asynchronous suspension>

**Comment by sigmundch** [comment]
@renatoaugustofranca - thanks for reporting the issue!

Let us know if by chance you have a small example code snippet that causes this error. That may help us narrow down the problem.

/cc @fishythefish 

Maybe the stack above has enough context to diagnose this?

In either case, we may want to do what we do in other phases of the compiler and track the enclosing member every time we enter `compueWorldImpact`, so we can also report what is that member in our stack trace. That will hopefully help reduce the investigation time later in the future.

**Comment by fishythefish** [comment]
Yeah, I see where the NPE is coming from in the code, but without a repro, it's hard to debug.

I believe the error is being thrown when we hit the `classNode` getter here: https://github.com/dart-lang/sdk/blob/88c24ef66acf74fda1ca77d54bdb00277430cabb/pkg/compiler/lib/src/ir/static_type.dart#L1537-L1539

This means we're probably hitting the end of `getInterfaceTypeOf`: https://github.com/dart-lang/sdk/blob/88c24ef66acf74fda1ca77d54bdb00277430cabb/pkg/compiler/lib/src/ir/static_type.dart#L195-L205
but without knowing what `iterableType` is, it's hard to say why.
