### ISSUE TITLE
Dart crashes on the cyclic generic typedef declaration

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45317]
Dart SDK version: 2.13.0-114.0.dev (dev) (Sat Mar 6 18:27:50 2021 -0800) on "windows_x64"

Here is a code source example which causes Dart crash:
```
typedef void TEST<T extends void Function<TT extends T>()>();
main() {}
```
Sample output is:
```
$> dart --enable-experiment=generic-metadata test.dart
Crash when compiling null,
at character offset null:
NoSuchMethodError: The method 'add' was called on null.
Receiver: null
Tried calling: add(Instance of 'TypeVariableBuilder')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      substituteRange (package:front_end/src/fasta/kernel/type_algorithms.dart:321:32)
#2      calculateBounds (package:front_end/src/fasta/kernel/type_algorithms.dart:418:31)
#3      SourceLibraryBuilder.computeDefaultTypes.computeDefaultTypesForVariables (package:front_end/src/fasta/source/source_library_builder.dart:2940:48)
#4      SourceLibraryBuilder.computeDefaultTypes (package:front_end/src/fasta/source/source_library_builder.dart:3013:49)
#5      SourceLoader.computeDefaultTypes (package:front_end/src/fasta/source/source_loader.dart:711:26)
#6      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:348:14)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#8      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:103:9)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#10     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#11     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#12     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#13     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#14     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#15     _processLoadRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>


#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      substituteRange (package:front_end/src/fasta/kernel/type_algorithms.dart:321:32)
#2      calculateBounds (package:front_end/src/fasta/kernel/type_algorithms.dart:418:31)
#3      SourceLibraryBuilder.computeDefaultTypes.computeDefaultTypesForVariables (package:front_end/src/fasta/source/source_library_builder.dart:2940:48)
#4      SourceLibraryBuilder.computeDefaultTypes (package:front_end/src/fasta/source/source_library_builder.dart:3013:49)
#5      SourceLoader.computeDefaultTypes (package:front_end/src/fasta/source/source_loader.dart:711:26)
#6      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:348:14)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#8      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:103:9)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#10     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#11     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#12     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#13     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#14     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#15     _processLoadRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>

```

**Comment by iarkh** [comment]
Another testcase which causes another crash with the similar diagnostic:
``` dart
void testme<T>() {}

main() {
  testme<void Function<T extends T>()>();
}
```
Error message is:
```
Crash when compiling file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Generic-functions-as-type-args/test.dart,
at character offset 28:
NoSuchMethodError: The getter 'file' was called on null.
Receiver: null
Tried calling: file
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      TypeVariableBuilder.finishNullabilities (package:front_end/src/fasta/builder/type_variable_builder.dart:207:43)
...
```
Should I file another issue or this is the same case?
