### ISSUE TITLE
Crash during AOT compilation: type 'Procedure' is not a subtype of type 'Field' in type cast

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#45324]
Repro:

```dart
class A {
  final int targetPlatform;
  const A(this.targetPlatform);

  static const BAR = A(1);
}

class X implements A {
  int get targetPlatform => 2;
}

A a = X();

void main() {
  print(a.targetPlatform);
  print(A.BAR);
}
```

```
pkg/vm/tool/gen_kernel --aot --platform out/ReleaseX64/vm_platform_strong.dill -o foo.dill foo.dart
```
```
Unhandled exception:
type 'Procedure' is not a subtype of type 'Field' in type cast
#0      Reference.asField (package:kernel/ast.dart:321:17)
#1      _TreeShakerConstantVisitor.visitInstanceConstant.<anonymous closure> (package:vm/transformations/type_flow/transformer.dart:1518:37)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#3      _TreeShakerConstantVisitor.visitInstanceConstant (package:vm/transformations/type_flow/transformer.dart:1517:26)
#4      InstanceConstant.accept (package:kernel/ast.dart:12524:42)
#5      _TreeShakerConstantVisitor.analyzeConstant (package:vm/transformations/type_flow/transformer.dart:1471:16)
#6      _TreeShakerPass1.visitConstant (package:vm/transformations/type_flow/transformer.dart:1120:28)
#7      ConstantExpression.transformOrRemoveChildren (package:kernel/ast.dart:8319:18)
#8      RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1418:10)
#9      TreeVisitor1.defaultExpression (package:kernel/visitor.dart:337:50)
#10     TreeVisitor1.visitConstantExpression (package:kernel/visitor.dart:417:7)
#11     ConstantExpression.accept1 (package:kernel/ast.dart:8303:9)
#12     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1173:21)
#13     RemovingTransformer.transformList (package:kernel/visitor.dart:1396:19)
#14     RemovingTransformer.transformExpressionList (package:kernel/visitor.dart:1323:5)
#15     Arguments.transformOrRemoveChildren (package:kernel/ast.dart:4969:7)
#16     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1418:10)
#17     TreeVisitor1.visitArguments (package:kernel/visitor.dart:508:46)
#18     Arguments.accept1 (package:kernel/ast.dart:4950:53)
#19     RemovingTransformer.transform (package:kernel/visitor.dart:1137:17)
#20     StaticInvocation.transformOrRemoveChildren (package:kernel/ast.dart:6288:21)
#21     _TreeShakerPass1.visitStaticInvocation (package:vm/transformations/type_flow/transformer.dart:1091:10)
#22     StaticInvocation.accept1 (package:kernel/ast.dart:6267:9)
#23     RemovingTransformer.transform (package:kernel/visitor.dart:1137:17)
#24     ExpressionStatement.transformOrRemoveChildren (package:kernel/ast.dart:8629:22)
#25     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1418:10)
#26     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:435:48)
#27     TreeVisitor1.visitExpressionStatement (package:kernel/visitor.dart:437:7)
#28     ExpressionStatement.accept1 (package:kernel/ast.dart:8609:9)
#29     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1173:21)
#30     RemovingTransformer.transformList (package:kernel/visitor.dart:1396:19)
#31     RemovingTransformer.transformStatementList (package:kernel/visitor.dart:1350:5)
#32     Block.transformOrRemoveChildren (package:kernel/ast.dart:8678:7)
#33     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1418:10)
#34     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:435:48)
#35     TreeVisitor1.visitBlock (package:kernel/visitor.dart:438:38)
#36     Block.accept1 (package:kernel/ast.dart:8664:58)
#37     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1173:21)
#38     RemovingTransformer.transformOrRemoveStatement (package:kernel/visitor.dart:1155:12)
#39     FunctionNode.transformOrRemoveChildren (package:kernel/ast.dart:3569:16)
#40     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1418:10)
#41     TreeVisitor1.visitFunctionNode (package:kernel/visitor.dart:507:52)
#42     FunctionNode.accept1 (package:kernel/ast.dart:3539:9)
#43     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1173:21)
#44     Procedure.transformOrRemoveChildren (package:kernel/ast.dart:2913:20)
#45     _TreeShakerPass1.defaultMember (package:vm/transformations/type_flow/transformer.dart:950:12)
#46     TreeVisitor1.visitProcedure (package:kernel/visitor.dart:473:46)
#47     Procedure.accept1 (package:kernel/ast.dart:2887:55)
#48     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1173:21)
#49     RemovingTransformer.transformList (package:kernel/visitor.dart:1396:19)
#50     RemovingTransformer.transformProcedureList (package:kernel/visitor.dart:1279:5)
#51     Library.transformOrRemoveChildren (package:kernel/ast.dart:701:7)
#52     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1418:10)
#53     TreeVisitor1.visitLibrary (package:kernel/visitor.dart:500:42)
#54     Library.accept1 (package:kernel/ast.dart:667:53)
#55     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1173:21)
#56     RemovingTransformer.transformList (package:kernel/visitor.dart:1396:19)
#57     RemovingTransformer.transformLibraryList (package:kernel/visitor.dart:1216:5)
#58     Component.transformOrRemoveChildren (package:kernel/ast.dart:12865:7)
#59     _TreeShakerPass1.transformComponent (package:vm/transformations/type_flow/transformer.dart:834:15)
#60     TreeShaker.transformComponent (package:vm/transformations/type_flow/transformer.dart:526:12)
#61     transformComponent (package:vm/transformations/type_flow/transformer.dart:90:14)
#62     runGlobalTransformations (package:vm/kernel_front_end.dart:442:5)
#63     compileToKernel (package:vm/kernel_front_end.dart:359:11)
<asynchronous suspension>
#64     runCompiler (package:vm/kernel_front_end.dart:259:19)
<asynchronous suspension>
#65     main (file:///.../pkg/vm/bin/gen_kernel.dart:34:19)
<asynchronous suspension>
```

The crash is different if order of statements is swapped in the main:
```dart
void main() {
  print(A.BAR);
  print(a.targetPlatform);
}
```
```
Unhandled exception:
Invalid argument(s): Trying to serialize orphaned getter reference.
Orphaned getter A.targetPlatform (Field:9045)
Linked node A.targetPlatform (Procedure:278534)
#0      BinaryPrinter.visitField (package:kernel/binary/ast_to_binary.dart:1291:7)
#1      Field.accept (package:kernel/ast.dart:2058:40)
#2      BinaryPrinter.writeFieldNode (package:kernel/binary/ast_to_binary.dart:425:10)
#3      BinaryPrinter.writeFieldNodeList (package:kernel/binary/ast_to_binary.dart:318:7)
#4      BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1173:5)
#5      Class.accept (package:kernel/ast.dart:1475:38)
#6      BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:432:10)
#7      BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:327:7)
#8      BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1014:5)
#9      Library.accept (package:kernel/ast.dart:664:38)
#10     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:411:10)
#11     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:720:9)
#12     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:563:7)
#13     Timeline.timeSync (dart:developer/timeline.dart:163:22)
#14     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:545:14)
#15     runCompiler (package:vm/kernel_front_end.dart:279:11)
<asynchronous suspension>
#16     main (file:///.../pkg/vm/bin/gen_kernel.dart:34:19)
<asynchronous suspension>
```

fyi @johnniwinther

**Comment by alexmarkov** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/191280.

**Comment by alexmarkov** [comment]
Another similar crash can be reproduced on the following example:

```dart
class A {
  void doTest(Z a) {
    print(a.appName);
  }
}

class Z {
  final String? appName;
  Z({this.appName});
}

class X extends Base implements Z {
}

class Base {
  String get appName => 'x';
}

void main() {
  Z();
  A().doTest(X());
}
```

```
pkg/vm/tool/gen_kernel --aot --platform out/ReleaseX64/vm_platform_strong.dill -o foo.dill foo.dart
```
```
Unhandled exception:
type 'Procedure' is not a subtype of type 'Field' in type cast
#0      Reference.asField (package:kernel/canonical_name.dart:439:17)
#1      FieldInitializer.field (package:kernel/ast.dart:2856:37)
#2      _TreeShakerPass1.visitFieldInitializer (package:vm/transformations/type_flow/transformer.dart:1200:36)
#3      FieldInitializer.accept1 (package:kernel/ast.dart:2867:9)
#4      RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1187:21)
#5      RemovingTransformer.transformList (package:kernel/visitor.dart:1410:19)
#6      RemovingTransformer.transformInitializerList (package:kernel/visitor.dart:1328:5)
#7      Constructor.transformOrRemoveChildren (package:kernel/ast.dart:2078:7)
#8      _TreeShakerPass1.defaultMember (package:vm/transformations/type_flow/transformer.dart:951:12)
#9      TreeVisitor1.visitConstructor (package:kernel/visitor.dart:472:50)
#10     Constructor.accept1 (package:kernel/ast.dart:2051:9)
#11     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1187:21)
#12     RemovingTransformer.transformList (package:kernel/visitor.dart:1410:19)
#13     RemovingTransformer.transformConstructorList (package:kernel/visitor.dart:1284:5)
#14     _TreeShakerPass1.visitClass (package:vm/transformations/type_flow/transformer.dart:935:5)
#15     Class.accept1 (package:kernel/ast.dart:1320:53)
#16     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1187:21)
#17     RemovingTransformer.transformList (package:kernel/visitor.dart:1410:19)
#18     RemovingTransformer.transformClassList (package:kernel/visitor.dart:1266:5)
#19     Library.transformOrRemoveChildren (package:kernel/ast.dart:541:7)
#20     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1432:10)
#21     TreeVisitor1.visitLibrary (package:kernel/visitor.dart:500:42)
#22     Library.accept1 (package:kernel/ast.dart:509:53)
#23     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1187:21)
#24     RemovingTransformer.transformList (package:kernel/visitor.dart:1410:19)
#25     RemovingTransformer.transformLibraryList (package:kernel/visitor.dart:1230:5)
#26     Component.transformOrRemoveChildren (package:kernel/ast.dart:12818:7)
#27     _TreeShakerPass1.transformComponent (package:vm/transformations/type_flow/transformer.dart:835:15)
#28     TreeShaker.transformComponent (package:vm/transformations/type_flow/transformer.dart:526:12)
#29     transformComponent (package:vm/transformations/type_flow/transformer.dart:90:14)
#30     runGlobalTransformations (package:vm/kernel_front_end.dart:442:5)
#31     compileToKernel (package:vm/kernel_front_end.dart:359:11)
<asynchronous suspension>
#32     runCompiler (package:vm/kernel_front_end.dart:259:19)
<asynchronous suspension>
#33     main (file:///.../pkg/vm/bin/gen_kernel.dart:34:19)
<asynchronous suspension>
```

This time the problem is that when a field is replaced with a getter, a reference from `FieldInitializer` to the field becomes invalid and cannot be dereferenced.

**Comment by alexmarkov** [comment]
Another fix: https://dart-review.googlesource.com/c/sdk/+/191323.
