### ISSUE TITLE
Can cookie value contain space?

### ISSUE THREAD

**Issue by PiN73** [dart-lang/sdk#45350]
I'm trying to make http request to some service, and response contains the following header:
```
Set-Cookie: name=hello world; domain=.mysite.com; expires=Wed, 31-Mar-2021 12:00:00 GMT; path=/; HttpOnly
```

The library I'm using for http requests uses `Cookie` class from `dart:io`.

The request is failed because of the space in the cookie value.

This is the minimal example:
```dart
import 'dart:io';

void main() {
  final cookie = Cookie.fromSetCookieValue('name=hello world');
  print(cookie.value);
}
```

```
Unhandled exception:
FormatException: Invalid character in cookie value, code unit: '32' (at character 6)
hello world
     ^

#0      _Cookie._validateValue (dart:_http/http_headers.dart:1106:9)
#1      _Cookie._parseSetCookieValue (dart:_http/http_headers.dart:1024:14)
#2      new _Cookie.fromSetCookieValue (dart:_http/http_headers.dart:949:5)
#3      new Cookie.fromSetCookieValue (dart:_http:1058:16)
#4      main (file:///Users/pavel/tmp/test.dart:4:25)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

```
% dart --version
Dart SDK version: 2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "macos_x64"
```
also reproducible at least from Dart 2.0.0

https://github.com/dart-lang/sdk/blob/65376c07234d1df472662d21dff2498ab2d3cdda/sdk/lib/_http/http_headers.dart#L1101-L1110

**Comment by lrhn** [comment]
I think the code answers your question with a "no". 
That's also correct, the [specification](https://tools.ietf.org/html/rfc6265#:~:text=cookie-octet) does not allow spaces in `cookie-value`.
The service which is sending you the cookie is sending malformed cookies. Shame on it, but that doesn't help you.

If you can intercept the cookie before the code calls `Cookie.fromSetCookieValue`, you can replace spaces with `%20`, like the service should have done.
