### ISSUE TITLE
Cannot connect to IPv6 loopback in cloud environment

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#45365]
I'm hitting this error running a Flutter web app in a cloud IDE. The stack trace isn't particularly useful (it's from Flutter, not the original source of the error). It's not clear whether the error is occurring when trying to bind/listen, or connect to a socket. The address appears to be the IPv6 loopback address, though I don't know if that's related - I _have_ seen some IPv6 issues in Dart-Code and have resorted to replacing `[::]` with `localhost` in a few places to workaround it - although in a quick test I wasn't able to repro this error by just trying to bind to `::` (although it did fail with different errors using `[::]` - Failed host lookup).

```
DartDevelopmentServiceException: WebSocketChannelException: WebSocketChannelException: SocketException: Connection failed (OS Error: Cannot assign requested address, errno = 99), address = ::, port = 44595
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:560:9)
#2      FlutterCommand.run. (package:flutter_tools/src/runner/flutter_command.dart:1045:27)
#3      AppContext.run. (package:flutter_tools/src/base/context.dart:152:19)
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
#5      FlutterCommandRunner.runCommand. (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
#6      AppContext.run. (package:flutter_tools/src/base/context.dart:152:19)
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
#8      run.. (package:flutter_tools/runner.dart:62:9)
#9      AppContext.run. (package:flutter_tools/src/base/context.dart:152:19)
```

@bkonyi I'm struggling to debug this as without a real stack trace I can't see exactly what code is running (and because it's in the SDK, I can't just rig the code like I can inside Flutter/DWDS). If you have ideas to help track this down, give me a shout.

@jonahwilliams while trying to debug this, I noticed I can work around this by changing `spawnDds: true` to `spawnDds: false` here:

https://github.com/flutter/flutter/blob/e8c3ce6bd1254d90a942c5b5da35b5c160877f00/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L283

I noticed there's also a `--disable-dds` switch that is not used here. Would it be reasonable for me to change that `true` to use that switch, or is there a reason it needs to always be spawned (in my testing it worked set to false, but it was far from thorough). This would give me a workaround in the meantime (although it'll fail if at some point things start relying on DDS).

**Comment by DanTup** [comment]
My previous workaround for this issue was to use `--disabled-dds` (after passing that flag through to DWDS), however since https://github.com/flutter/flutter/pull/79479 landed, I now see the same error (although now it occurs in a loop) despite the flag:

```
[11:46:41 AM]: <== [{"method":"app.exposeUrl","params":{"url":"ws://[::]:46351/xc43AzMUHcI="},"id":"2"}]
[11:46:42 AM]: ==> [{"id":"2","result":{"url":"wss://46351-mytheiainstance.foo/xc43AzMUHcI%3D"}}]
[11:46:42 AM]: <== [+20706 ms] DevHandler: Debug service listening on wss://46351-mytheiainstance.foo/xc43AzMUHcI%3D
[11:46:42 AM]: <== [ +277 ms] Exception attempting to connect to the VM Service: SocketException: Connection failed (OS Error: Cannot assign requested address, errno = 99), address = ::, port = 46351
[11:46:42 AM]: <== [   +4 ms] This was attempt #1. Will retry in 0:00:00.100000.
[11:46:42 AM]: <== [   +6 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[11:46:42 AM]: <== [  +99 ms] Exception attempting to connect to the VM Service: SocketException: Connection failed (OS Error: Cannot assign requested address, errno = 99), address = ::, port = 46351
[11:46:42 AM]: <== [        ] This was attempt #2. Will retry in 0:00:00.200000.
[11:46:42 AM]: <== [ +201 ms] Exception attempting to connect to the VM Service: SocketException: Connection failed (OS Error: Cannot assign requested address, errno = 99), address = ::, port = 46351
[11:46:42 AM]: <== [        ] This was attempt #3. Will retry in 0:00:00.400000.
[11:46:43 AM]: <== [ +401 ms] Exception attempting to connect to the VM Service: SocketException: Connection failed (OS Error: Cannot assign requested address, errno = 99), address = ::, port = 46351
[11:46:43 AM]: <== [        ] This was attempt #4. Will retry in 0:00:00.800000.
[11:46:43 AM]: <== [ +801 ms] Exception attempting to connect to the VM Service: SocketException: Connection failed (OS Error: Cannot assign requested address, errno = 99), address = ::, port = 46351
[11:46:43 AM]: <== [        ] This was attempt #5. Will retry in 0:00:01.600000.
[11:46:45 AM]: <== [+1602 ms] Exception attempting to connect to the VM Service: SocketException: Connection failed (OS Error: Cannot assign requested address, errno = 99), address = ::, port = 46351
```

Unfortunately I can't reproduce this locally, so it's a little tricky to debug. Although I can run in the remote environment with a fork of Flutter/dwds, so if I adding additional prints around the code might help debug, I can do that.

**Comment by bkonyi** [comment]
So by the looks of things we're having issues making web socket connections from `flutter_tools`, which would explain why this wasn't working with DDS before and why it stopped working even with DDS disabled after flutter/flutter#79479. After that PR landed, we went from directly accessing the `VmService` instance provided by DWDS to connecting to DWDS via web socket.

Maybe the cloud environment has some restrictions on local network connections?

**Comment by bkonyi** [comment]
Updating [this URI](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L672) in Flutter tools to have a `localhost` host seems to allow for the connection to succeed.

**Comment by bkonyi** [comment]
Closing this issue in favor of flutter/flutter#80138 as this isn't an SDK issue.
