### ISSUE TITLE
Migration tool crashes on reference to `loadLibrary` for a deferred library

### ISSUE THREAD

**Issue by oligazar** [dart-lang/sdk#45396]
When running `dart migrate` got following exception report:

```
Bad state: A decorated type for Future<dynamic>* loadLibrary() should have been stored by the NodeBuilder via recordDecoratedElementType at offset 1113 in /Users/Admin/Development/flutter/AgForce/treckerflutter/lib/common/lang/l10n/messages_all.dart (loadLibrary)

#0      Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:382:7)
#1      Variables.decoratedElementType (package:nnbd_migration/src/variables.dart:100:9)
#2      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:301:38)
#3      EdgeBuilder.visitSimpleIdentifier (package:nnbd_migration/src/edge_builder.dart:1603:16)
#4      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8889:50)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#6      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:2976:14)
#7      EdgeBuilder.visitPrefixedIdentifier (package:nnbd_migration/src/edge_builder.dart:1405:14)
#8      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8179:50)
#9      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#10     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#11     EdgeBuilder.visitMapLiteralEntry (package:nnbd_migration/src/edge_builder.dart:1237:5)
#12     MapLiteralEntryImpl.accept (package:analyzer/src/dart/ast/ast.dart:6806:50)
#13     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#14     EdgeBuilder._handleCollectionElement (package:nnbd_migration/src/edge_builder.dart:2441:14)
#15     ListMixin.forEach (dart:collection/list.dart:86:13)
#16     EdgeBuilder.visitSetOrMapLiteral (package:nnbd_migration/src/edge_builder.dart:1568:23)
#17     SetOrMapLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:8644:50)
#18     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#19     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#20     EdgeBuilder.visitVariableDeclarationList (package:nnbd_migration/src/edge_builder.dart:1924:11)
#21     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10565:15)
#22     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#23     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#24     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:137:48)
#25     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:231:44)
#26     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:205:7)
#27     GeneralizingAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:558:7)
#28     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:9825:15)
#29     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#30     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#31     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#32     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#33     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#34     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#35     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2111:50)
#36     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#37     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#38     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:19)
#39     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1150:28)
#40     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
<asynchronous suspension>
#41     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1150:5)
<asynchronous suspension>
#42     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:747:24)
<asynchronous suspension>
#43     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:7)
<asynchronous suspension>
#44     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#45     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#46     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#47     main (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

```

`flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.1.0-13.0.pre.86, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2.3)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (4 available)

• No issues found!
```

**Comment by stereotype441** [comment]
@oligazar thanks for the bug report!  Are you able to make progress by running the tool with the command-line argument `--ignore-exceptions`?

**Comment by stereotype441** [comment]
I was able to reproduce this bug by trying to migrate the following code snippet:
```dart
// @dart=2.9                                                                                                                                                    

import 'test.dart' deferred as test;

f() => test.loadLibrary;
```
I'll get to work on a fix.
