### ISSUE TITLE
Dart2js crashes with RangeError on two co19 Generic-functions-as-type-args tests

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45415]
Dart2js crashes with the following co19 tests in the recent roll:

- [LanguageFeatures/Generic-functions-as-type-args/class_A01_t01](https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Generic-functions-as-type-args/class_A01_t01)
- [LanguageFeatures/Generic-functions-as-type-args/class_A01_t02](https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Generic-functions-as-type-args/class_A01_t01)

Both tests pass with analyzer and CFE.

Here is a link to the [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8852433874776101888/+/steps/test_results/0/logs/new_test_failures__logs_/0).

Here is a error message sample:
```
--- Command "dart2js" (took 01.000922s):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome sdk/bin/dart2js_developer --enable-experiment=generic-metadata --enable-experiment=generic-metadata --sound-null-safety --test-mode --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/LanguageFeatures/Generic-functions-as-type-args/class_A01_t01.dart --libraries-spec=sdk/lib/libraries.json --platform-binaries=out/ReleaseX64/ --sound-null-safety --out=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-hostasserts-strong-linux-x64-chrome/tests_co19_src_LanguageFeatures_Generic-functions-as-type-args_class_A01_t01/class_A01_t01.js

exit code:
253

stdout:
tests/co19/src/LanguageFeatures/Generic-functions-as-type-args/class_A01_t01.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      BinaryBuilder._readTypeParameterType (package:kernel/binary/ast_from_binary.dart:2945:52)
#2      BinaryBuilder.readDartType (package:kernel/binary/ast_from_binary.dart:2852:16)
#3      BinaryBuilder.readDartTypeList.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:2803:55)
#4      new List.generate (dart:core-patch/array_patch.dart:63:28)
#5      BinaryBuilder.readDartTypeList (package:kernel/binary/ast_from_binary.dart:2803:16)
#6      BinaryBuilder._readFunctionType (package:kernel/binary/ast_from_binary.dart:2919:33)
#7      BinaryBuilder.readDartType (package:kernel/binary/ast_from_binary.dart:2848:16)
#8      BinaryBuilder._readTypeLiteralConstant (package:kernel/binary/ast_from_binary.dart:450:27)
#9      BinaryBuilder.readConstantTableEntry (package:kernel/binary/ast_from_binary.dart:366:16)
#10     BinaryBuilder.readConstantTable (package:kernel/binary/ast_from_binary.dart:334:50)
#11     BinaryBuilder._readOneComponent (package:kernel/binary/ast_from_binary.dart:825:5)
#12     BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:633:34)
#13     Timeline.timeSync (dart:developer/timeline.dart:163:22)
#14     BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:603:21)
#15     SerializationStrategy.deserializeComponent (package:compiler/src/serialization/strategies.dart:42:29)
#16     Compiler.globalTypeInferenceResultsTestMode (package:compiler/src/compiler.dart:453:18)
#17     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:483:13)
#18     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#19     Compiler.compileFromKernel (package:compiler/src/compiler.dart:459:14)
#20     Compiler.runInternal (package:compiler/src/compiler.dart:298:13)
<asynchronous suspension>
```

**Comment by johnniwinther** [comment]
This is a CFE issue. We don't handle (de)serialization of type literals of generic typedefs with generic function type parameter bounds.

This only shows up on the dart2js bot because the other bots don't serialize and deserialize the AST which the dart2js bot does in `--test-mode`.
