### ISSUE TITLE
Remote debug code after reproduction and fix

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#45429]
We are looking for reproduction of:
```
Receiver: null
Tried calling: contextType : #0      _ContextTypeVisitor.visitExpressionFunctionBody (package:analysis_server/src/services/completion/dart/feature_computer.dart:672)
#1      ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3472)
#2      FeatureComputer.computeContextType (package:analysis_server/src/services/completion/dart/feature_computer.dart:168)
#3      DartCompletionRequestImpl.contextType (package:analysis_server/src/services/completion/dart/completion_manager.dart:323)
#4      DartCompletionManager._addIncludedSuggestionRelevanceTags (package:analysis_server/src/services/completion/dart/completion_manager.dart:223)
#5      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:148)
<asynchronous suspension>
#6      CiderCompletionComputer.compute.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/cider/completion.dart:99)
<asynchronous suspension>
#7      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50)
<asynchronous suspension>
#8      CiderCompletionComputer.compute.<anonymous closure>.<anonymous closure> (package:analysis_server/src/cider/completion.dart:86)
<asynchronous suspension>
#9      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:160)
<asynchronous suspension>
#10     CiderCompletionComputer.compute.<anonymous closure> (package:analysis_server/src/cider/completion.dart:83)
<asynchronous suspension>
#11     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:160)
<asynchronous suspension>
#12     handleCompletionRequest.<anonymous closure>.<anonymous closure> (package:devtools.cider.extensions.dartd/worker.dart:568)
<asynchronous suspension>
#13     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50)
<asynchronous suspension>
#14     handleCompletionRequest.<anonymous closure> (package:devtools.cider.extensions.dartd/worker.dart:561)
<asynchronous suspension>
#15     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50)

```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/192760

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/356922
