### ISSUE TITLE
Remove debug code in ResolvedLibraryResultImpl after reproduction and fix

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#45430]
We are looking for reproduction of:
```
#0      ResolvedLibraryResultImpl.getElementDeclaration.<anonymous closure> (package:analyzer/src/dart/analysis/results.dart:305)
#1      ListMixin.firstWhere (dart:collection/list.dart:166)
#2      ResolvedLibraryResultImpl.getElementDeclaration (package:analyzer/src/dart/analysis/results.dart:301)
#3      AnalysisSessionHelper.getElementDeclaration (package:analyzer/src/dart/analysis/session_helper.dart:48)
<asynchronous suspension>
#4      CreateField._proposeFromIdentifier (package:analysis_server/src/services/correction/dart/create_field.dart:99)
<asynchronous suspension>
#5      CreateField.compute (package:analysis_server/src/services/correction/dart/create_field.dart:29)
<asynchronous suspension>
#6      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1974)
<asynchronous suspension>
#7      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1996)
<asynchronous suspension>
#8      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1931)
<asynchronous suspension>
#9      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:182)
<asynchronous suspension>
#10     CiderFixesComputer.compute.<anonymous closure> (package:analysis_server/src/cider/fixes.dart:57)
<asynchronous suspension>
#11     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50)
<asynchronous suspension>
#12     CiderFixesComputer.compute (package:analysis_server/src/cider/fixes.dart:44)
```

**Comment by scheglov** [comment]
I believe this was fixed in ae8a2aac09e8d96f1e9a31df2b0ec16444a6cc1c.
