### ISSUE TITLE
Dart silently crashes with exit code -1073741571

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45443]
Dart SDK version: 2.13.0-161.0.dev (dev) (Mon Mar 22 19:57:50 2021 -0700) on "windows_x64"

Dart silently crashes with exit code -1073741571 when runs the following source code example:

**test.dart:**
``` dart
class C1<T extends void Function<TT extends T>()> {}
class C2<T extends TT Function<TT extends T>()> {}

main() {
  print("OK");
}
```
If I comment line #1 or #line #2, it prints "OK" and finishes with the exit code `0`.

To reproduce on Windows please run the following script:
```
@echo off
dart --enable-experiment=generic-metadata test.dart 
echo error is %errorlevel%
```
Sample output is:
`error is -1073741571`

**Comment by a-siva** [comment]
Seems to get into an infinite recursion
```
#16 0x000055555750b797 in dart::TypeParameter::IsEquivalent (
    this=0x555558db5cd0, other=..., kind=dart::TypeEquality::kCanonical, 
    trail=0x7ffff7305380) at ../../runtime/vm/object.cc:21156
#17 0x00005555574b5493 in dart::FunctionType::HasSameTypeParametersAndBounds (
    this=<optimized out>, other=..., kind=dart::TypeEquality::kCanonical)
    at ../../runtime/vm/object.cc:8572
#18 0x0000555557506463 in dart::FunctionType::IsEquivalent (
    this=0x555558db5c90, other=..., kind=dart::TypeEquality::kCanonical, 
    trail=0x7ffff7305338) at ../../runtime/vm/object.cc:20270
#19 0x000055555750b6fb in dart::TypeParameter::IsEquivalent (
    this=0x555558db5c70, other=..., kind=<optimized out>, 
    trail=0x555557bafa08 <FLAG__namespace_do_not_use_directly_use_DECLARE_int64_instead::FLAGS_tcmalloc_heap_limit_mb>) at ../../runtime/vm/object.cc:21206
#20 0x000055555750b797 in dart::TypeParameter::IsEquivalent (
    this=0x555558db5c50, other=..., kind=dart::TypeEquality::kCanonical, 
    trail=0x7ffff7305338) at ../../runtime/vm/object.cc:21156
#21 0x00005555574b5493 in dart::FunctionType::HasSameTypeParametersAndBounds (
    this=<optimized out>, other=..., kind=dart::TypeEquality::kCanonical)
    at ../../runtime/vm/object.cc:8572
#22 0x0000555557506463 in dart::FunctionType::IsEquivalent (
    this=0x555558db5c10, other=..., kind=dart::TypeEquality::kCanonical, 
    trail=0x7ffff73052f0) at ../../runtime/vm/object.cc:20270
#23 0x000055555750b6fb in dart::TypeParameter::IsEquivalent (
    this=0x555558db5bf0, other=..., kind=<optimized out>, 
    trail=0x555557bafa08 <FLAG__namespace_do_not_use_directly_use_DECLARE_int64_instead::FLAGS_tcmalloc_heap_limit_mb>) at ../../runtime/vm/object.cc:21206

```

**Comment by crelier** [comment]
Fix was sent for review: https://dart-review.googlesource.com/c/sdk/+/192947
Thanks for the report!
