### ISSUE TITLE
FFI Packed Alignment: An error occurred while handling `completionItem/resolve` request: Null check operator used on a null value

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#45498]
See detailed error log below.

## Dart Version

```
[C:\src\win32] dart --version
Dart SDK version: 2.13.0-162.0.dev (dev) (Tue Mar 23 08:10:12 2021 -0700) on "windows_x64"
```

## Error Log

```
[Error - 4:02:11 PM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:02:12 PM] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:02:12 PM] Request textDocument/signatureHelp failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:02:12 PM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:07 PM] Request completionItem/resolve failed.
  Message: An error occurred while handling completionItem/resolve request
  Code: -32001 
[Error - 4:05:07 PM] An error occurred while handling completionItem/resolve request: Null check operator used on a null value
#0      _extension#1.packedMemberAlignment (package:analyzer/src/generated/ffi_verifier.dart:859:17)
#1      FfiVerifier._validatePackedAnnotation (package:analyzer/src/generated/ffi_verifier.dart:700:49)
#2      FfiVerifier.visitClassDeclaration (package:analyzer/src/generated/ffi_verifier.dart:78:11)
#3      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1514:50)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
#5      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2112:21)
#6      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:735:10)
#7      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#8      LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:414:10)
#9      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:141:7)
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#11     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:140:11)
#12     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:104:12)
#13     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1315:63)
#14     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#15     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1286:20)
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:940:22)
#17     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2006:24)
<asynchronous suspension>

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1344:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1286:20)
#3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:940:22)
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2006:24)
<asynchronous suspension>

[Error - 4:05:07 PM] Request textDocument/signatureHelp failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:08 PM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:08 PM] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:09 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:11 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:12 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:12 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:13 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:13 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:14 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:14 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:14 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:15 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:15 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:15 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:16 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:16 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:17 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
[Error - 4:05:17 PM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
c:\src\win32\lib\src\structs.dart
```

**Comment by dcharkes** [comment]
@timsneath Can you provide the specific instructions to reproduce this?

I have a fix (changing some `!` into `?`), but I don't know how to reproduce the actual problem. 😃

**Comment by timsneath** [comment]
This seemed to trigger when I was adding the `Packed` attribute to an existing class in VSCode. Somewhere around opening paren and typing a number triggered it on my machine. I can try and get a more consistent repro if that's not sufficient?

**Comment by dcharkes** [comment]
I can repro it now:

```dart
@Packed()
class MyStruct extends Struct { ... }
```

The analyzer in the IDE does not update, and seems to swallow the ffi_verifier crash here locally.
