### ISSUE TITLE
[cfe] Crash on co19/Language/Generics/syntax_t29

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45490]
Cf. https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8851738599320124576/+/steps/test_results/0/logs/new_test_failures__logs_/0:

dartk-strong-linux-debug-x64, dartk-weak-asserts-linux-debug-x64, dart2js-hostasserts-{strong,weak}-linux-x64-chrome, dartdevk-{strong,weak}-linux-release-chrome crash on said test, e.g.:

```
Crash when compiling null,
at character offset null:
NoSuchMethodError: The method 'buildType' was called on null.
Receiver: null
Tried calling: buildType(Instance of 'SourceLibraryBuilder', Instance of 'NullabilityBuilder', null, null)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      NamedTypeBuilder.build (package:front_end/src/fasta/builder/named_type_builder.dart:249:40)
#2      TypeVariableBuilder.finish (package:front_end/src/fasta/builder/type_variable_builder.dart:157:32)
#3      SourceLibraryBuilder.finishTypeVariables (package:front_end/src/fasta/source/source_library_builder.dart:2904:15)
#4      SourceLoader.finishTypeVariables (package:front_end/src/fasta/source/source_loader.dart:693:26)
#5      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:352:14)
<asynchronous suspension>
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#7      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:103:9)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#9      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#10     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#11     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#12     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#13     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#14     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>
```

**Comment by eernstg** [comment]
The test `co19/Language/Generics/syntax_t30` gives rise to a very similar behavior, on the same configurations.

```
Crash when compiling null,
at character offset null:
NoSuchMethodError: The method 'buildType' was called on null.
Receiver: null
Tried calling: buildType(Instance of 'SourceLibraryBuilder', Instance of 'NullabilityBuilder', null, null)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      NamedTypeBuilder.build (package:front_end/src/fasta/builder/named_type_builder.dart:249:40)
#2      TypeVariableBuilder.finish (package:front_end/src/fasta/builder/type_variable_builder.dart:157:32)
#3      SourceLibraryBuilder.finishTypeVariables (package:front_end/src/fasta/source/source_library_builder.dart:2904:15)
#4      SourceLoader.finishTypeVariables (package:front_end/src/fasta/source/source_loader.dart:693:26)
#5      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:352:14)
<asynchronous suspension>
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#7      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:103:9)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#9      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#10     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#11     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#12     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#13     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#14     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>
```

**Comment by stefantsov** [comment]
I'm working on the fix here: https://dart-review.googlesource.com/c/sdk/+/193408.
