### ISSUE TITLE
New test failures after Reapply "[vm, compiler] Convert binary Smi ops to graph intrinsics."

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#45511]
There are new test failures on https://dart-review.googlesource.com/c/sdk/+/192044

The tests
```
language_2/vm/mult_int_test/0 Fail (expected Pass)
language_2/vm/mult_int_test/1 Fail (expected Pass)
```
are failing on configurations
```
dartk-ubsan-linux-release-x64
```

**Comment by a-siva** [comment]
```
--- Command "vm" (took 01.000761s):
DART_CONFIGURATION=ReleaseUBSANX64 out/ReleaseUBSANX64/dart --no_background_compilation --optimization_counter_threshold=10 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/language_2/vm/mult_int_test.dart

exit code:
1

stderr:
../../runtime/vm/compiler/backend/loops.cc:726:37: runtime error: signed integer overflow: 9223372036854775807 + 9223372036854775807 cannot be represented in type 'long'
    #0 0x56245504e974 in dart::InductionVarAnalysis::Add(dart::InductionVar*, dart::InductionVar*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/loops.cc:726:37
    #1 0x56245504dd25 in dart::InductionVarAnalysis::Add(dart::InductionVar*, dart::InductionVar*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/loops.cc:747:25
    #2 0x56245504910b in dart::InductionVarAnalysis::Classify(dart::LoopInfo*, dart::Definition*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/loops.cc:330:13
    #3 0x562455049858 in dart::InductionVarAnalysis::ClassifySCC(dart::LoopInfo*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/loops.cc:397:9
    #4 0x562455046a44 in dart::InductionVarAnalysis::Visit(dart::LoopInfo*, dart::Definition*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/loops.cc:290:7
    #5 0x562455045f2d in dart::InductionVarAnalysis::VisitLoop(dart::LoopInfo*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/loops.cc:234:9
    #6 0x562455045aea in dart::InductionVarAnalysis::VisitHierarchy(dart::LoopInfo*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/loops.cc:211:5
    #7 0x562455045b0b in dart::InductionVarAnalysis::VisitHierarchy(dart::LoopInfo*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/loops.cc:212:5
    #8 0x56245505979a in dart::LoopHierarchy::ComputeInduction() const ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/loops.cc:1197:35
    #9 0x56245508694a in dart::LICM::Optimize() ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/redundancy_elimination.cc:1471:18
    #10 0x5624551096a7 in dart::CompilerPass_LICM::DoBody(dart::CompilerPassState*) const ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/compiler_pass.cc:453:1
    #11 0x56245510596d in dart::CompilerPass::Run(dart::CompilerPassState*) const ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/compiler_pass.cc:210:16
    #12 0x5624551071ce in dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/compiler_pass.cc:335:3
    #13 0x5624541fc280 in dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/jit/compiler.cc:584:22
    #14 0x5624541fe133 in dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/jit/compiler.cc:732:46
    #15 0x5624541ff5ac in dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/jit/compiler.cc:915:10
    #16 0x56245412b0f3 in dart::HandleOSRRequest(dart::Thread*) ../../out/ReleaseUBSANX64/../../runtime/vm/runtime_entry.cc:2694:7
    #17 0x56245412049e in dart::DRT_StackOverflow(dart::NativeArguments) ../../out/ReleaseUBSANX64/../../runtime/vm/runtime_entry.cc:2716:1

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../runtime/vm/compiler/backend/loops.cc:726:37 in

--- Re-run this test:
python tools/test.py -n dartk-ubsan-linux-release-x64 language_2/vm/mult_int_test/0
```
