### ISSUE TITLE
Dart does not throw a compile error for variable of the type which is not well bounded.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45519]
Dart SDK version: 2.13.0-165.0.dev (dev) (Thu Mar 25 02:53:52 2021 -0700) on "windows_x64"

Here is a code source example which throws a runtime error with dart and a compile time error with analyzer:
``` dart
class C<X> {}
typedef G<X> = X Function(X);
typedef A<X extends G<C<X>>> = C<X>;

main() {
  A a = throw "Should not be here";
}
```
This case is described in [1050](https://github.com/dart-lang/co19/issues/1050) and seems like dart should throw a compile error here too.

Sample output is:
```
$> dartanalyzer --enable-experiment=nonfunction-type-aliases test.dart 
Analyzing test.dart...
  error - 'C<Never> Function(C<Never>)' doesn't conform to the bound 'C<C<Never> Function(C<Never>)> Function(C<C<Never> Function(C<Never>)>)' of the type parameter 'X'. - test.dart:6:3 - type_argument_not_matching_bounds
  hint - The value of the local variable 'a' isn't used. - test.dart:6:5 - unused_local_variable
1 error and 1 hint found.

$> dart --enable-experiment=nonfunction-type-aliases test.dart 
Unhandled exception:
Should not reach here
#0      main (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/test.dart:6:9)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
It's interesting that the following test case does not throw any error both with analyzer and dart:
``` dart
class C<X> {}
typedef G<X> = X Function(X);
typedef A<X extends G<C<X>>> = C<X>;

main() {
  A();
}
```
Still `A` is not well-bounded here, so should I file another bug regarding the analyzer?

**Comment by eernstg** [comment]
Yes, please report the missing errors for both tools!

**Comment by stefantsov** [comment]
I'm working on the fix here: https://dart-review.googlesource.com/c/sdk/+/193500.
