### ISSUE TITLE
unexpected null safety crash

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#45529]
_(Sorry for the non-descriptive title, didn't know how to better describe this.)_

While debugging https://github.com/flutter/flutter/issues/74389 in Flutter I ran into the following unexpected crash that reproduces when running the program listed below in the Dart VM:

```dart
import 'dart:async';

void main() {
  final FooRoute<String?> d = FooRoute<String?>();
  d.dispose();
}

class Bar<T> {
  Bar([this.value]);
  final T? value;
}

class FooRoute<T> extends BarRoute<Bar<T>> {

}

class BarRoute<T> {
  final Completer<T?> transitionCompleter = Completer<T?>();
  T? result;

  void dispose() {
    print('Generic: $T'); // Bar<String?>
    print('Value of "T? result": $result'); // null
    // Actual:   "_AsyncCompleter<Bar<String?>>"
    // Expected: "_AsyncCompleter<Bar<String?>?>"
    print('Type of "Completer<T?> completer": ${transitionCompleter.runtimeType}');
    transitionCompleter.complete(result);
  }
}
```

```
Unhandled exception:
type 'Null' is not a subtype of type 'FutureOr<Bar<String?>>'
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:46:41)
#1      BarRoute.dispose (file:///Users/goderbauer/Desktop/crash.dart:27:25)
#2      main (file:///Users/goderbauer/Desktop/crash.dart:5:5)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

This is surprising. I expected `transitionCompleter` to have the type `_AsyncCompleter<Bar<String?>?>`, which means completing it with null should be fine. However, for some reason its actual runtime type is `_AsyncCompleter<Bar<String?>>` (note the missing question mark) as can be seen by the prints produces by the program (see below). This completer of course cannot be completed with null, which leads to the crash.

```
Generic: Bar<String?>
Value of "T? result": null
Type of "Completer<T?> completer": _AsyncCompleter<Bar<String?>>
```

Running the same program in dartpad.dev does not reproduce crash and the program prints the expected types (see below) leading me to believe that this is a bug in the VM.

```
Generic: Bar<String?>
Value of "T? result": null
Type of "Completer<T?> completer": _AsyncCompleter<Bar<String?>?>
```

**Comment by Cyp** [comment]
Slightly reduced testcase without dart:async. Crashes on the `baz.v = baz.v;` line (also crashes with `baz.v = null;`), but works if compiling to js or exe.

```dart
void main() {
  final baz = Foo<Null>().baz;
  print('baz runtimeType ${baz.runtimeType}');
  print('baz.v value ${baz.v}');
  print('baz.v runtimeType ${baz.v.runtimeType}');
  baz.v = baz.v;
}

class Bar<T> {
}

class Foo<T> extends Quux<Bar<T>> {
}

class Baz<T> {
  Baz(this.v);

  T v;
}

class Quux<T> {
  final baz = Baz<T?>(null);
}
```

Expected:
```
baz runtimeType Baz<Bar<Null>?>
baz.v value null
baz.v runtimeType Null
```

Actual:
```
baz runtimeType Baz<Bar<Null>>
baz.v value null
baz.v runtimeType Null
Unhandled exception:
type 'Null' is not a subtype of type 'Bar<Null>' of 'value'
#0      Baz.v= (45529.dart)
#1      main (45529.dart:6:7)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by mraleph** [comment]
It seems instantiation of `T?` with `T=Bar<Null>` somehow yields `Bar<Null>` instead of `Bar<Null>?`. Assigning to @crelier

**Comment by crelier** [comment]
Fix is under review: https://dart-review.googlesource.com/c/sdk/+/193751
Thanks for the report!
