### ISSUE TITLE
dart2js doesn't perform argument type checks in production mode

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#45528]
dart2js in production mode fails on the regression test from https://github.com/dart-lang/sdk/issues/45428:

https://dart-review.googlesource.com/c/sdk/+/193524/2/tests/language_2/regress/regress45428_test.dart
```dart
// Copyright (c) 2021, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:expect/expect.dart';

void something(List<String> l) {
  String s = l.first;
}

void checkAndInvoke(Function f) {
  f(["foo"]);
  var l = <int>[1];
  Expect.throwsTypeError(() => f(l));
  if (f is Function(List<Never>)) {
    Expect.throwsTypeError(() => (f as Function)(l));
  }
}

void main() {
  checkAndInvoke(something);
}
```

```
/==================================================================================================================\
| dart2js-production-linux-d8:language_2/regress/regress45428_test is new and failed (RuntimeError, expected Pass) |
\==================================================================================================================/

--- Command "dart2js" (took 01.000912s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart2js --test-mode --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/language_2/regress/regress45428_test.dart -O3 --out=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_2_regress_regress45428_test/regress45428_test.js

exit code:
0

stdout:
Compiled 8,996,541 characters Dart to 41,548 characters JavaScript in 1.91 seconds
Dart file /b/s/w/ir/tests/language_2/regress/regress45428_test.dart compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_2_regress_regress45428_test/regress45428_test.js

--- Command "d8" (took 106ms):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/third_party/d8/linux/d8 out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_2_regress_regress45428_test/regress45428_test.js

exit code:
1

stdout:
out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: Expect.throws(TypeError) fails: Did not throw
          throw e;
          ^
Expect.throws(TypeError) fails: Did not throw
    at Object.a (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_2_regress_regress45428_test/regress45428_test.js:108:3)
    at Object.av (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_2_regress_regress45428_test/regress45428_test.js:1103:24)
    at Object.bv (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_2_regress_regress45428_test/regress45428_test.js:1101:76)
    at Object.aM (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_2_regress_regress45428_test/regress45428_test.js:1102:18)
    at Object.cc (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_2_regress_regress45428_test/regress45428_test.js:1111:3)
    at cn (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_2_regress_regress45428_test/regress45428_test.js:1113:17)
    at action (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_2_regress_regress45428_test/regress45428_test.js:1343:39

Deobfuscated error and stack:
Expect.throws(TypeError) fails: Did not throw
    at wrapException          org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 1130:37
    at Expect._fail           ../../../../../pkg/expect/lib/expect.dart 713:5
    at Expect.throws          ../../../../../pkg/expect/lib/expect.dart 615:5
    at Expect.throwsTypeError ../../../../../pkg/expect/lib/expect.dart 652:12
    at checkAndInvoke         ../../../../../tests/language_2/regress/regress45428_test.dart 14:10
    at main                   ../../../../../tests/language_2/regress/regress45428_test.dart 21:3
    at action                 out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js 275:31
    at eventLoop              out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js 258:9
    at self.dartMainRunner    out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js 276:5
    at <fn>                   out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_2_regress_regress45428_test/regress45428_test.js 1343:39


--- Re-run this test:
python tools/test.py -n dart2js-production-linux-d8 --dart2js-batch language_2/regress/regress45428_test
```

@sigmundch @rakudrama Is this expected behavior?

**Comment by rakudrama** [comment]
'production mode' removes type checking of arguments, so this is expected.

**Comment by alexmarkov** [comment]
What are we supposed to do with the failures which are related to the missing argument type checks in dart2js/production?
1. Approve the failures.
2. Skip the test in status file in order to leave bread-crumbs. In such case, what is the correct condition/section? Could you point me to the tests that are failing for the same reason?

**Comment by sigmundch** [comment]
So far we've done (1), but in the future my preference is to use (2) with "SkipByDesign", less for the breadcrumbs, and more to avoid wasting resources.

Because of that, we don't have examples today were we skip in this mode, but there is one crash that illustrates what the condition/section would look like:

https://github.com/dart-lang/sdk/blob/3ce196935ee16081cf4710436ad50aaae2b4adb8/tests/language/language_dart2js.status#L15
