### ISSUE TITLE
Dart null-safety migration tool stopped working

### ISSUE THREAD

**Issue by PiotrWpl** [dart-lang/sdk#45554]
Hi,

I started my project migration, and it was working quite good, but at some point, I started to receive an error that I'm not able to understand and fix. Due to this error, I'm not able to continue my migration. Please advise how I can solve it.

* Dart SDK Version (`dart --version`)
```
.fvm/flutter_sdk/bin/dart --version
Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "macos_x64"
```

* Whether you are using Windows, MacOSX, or Linux (if applicable)
`MacOS`

* This is the command line which I'm using and it was working fine before this error happen first time (I had to do --skip-import-check because flutter_remote_config is still not migrated to nullsafety)

```
% .fvm/flutter_sdk/bin/dart migrate --skip-import-check
Migrating melody-samssie-app

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\]Warning: package has unmigrated dependencies.

Continuing due to the presence of `--skip-import-check`.  To see a complete
list of the unmigrated dependencies, re-run without the `--skip-import-check`
flag.

No analysis issues found.

Generating migration suggestions...
[---------------------------------------------------------------------------------------------------------------------------------/                                                                
ConflictingEditException: {"offset":1336,"length":2,"replacement":""} conflicts with {"offset":1332,"length":9,"replacement":""}
#0      addEditForSource (package:analyzer_plugin/src/protocol/protocol_internal.dart:58:7)
#1      SourceFileEdit.add (package:analyzer_plugin/protocol/protocol_common.dart:5544:32)
#2      addEditToSourceChange (package:analyzer_plugin/src/protocol/protocol_internal.dart:73:12)
#3      SourceChange.addEdit (package:analyzer_plugin/protocol/protocol_common.dart:5240:7)
#4      DartFixListener.addEditWithoutSuggestion (package:nnbd_migration/src/front_end/dartfix_listener.dart:28:18)
#5      NullabilityMigrationAdapter.addEdit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:538:14)
#6      NullabilityMigrationImpl.finalizeInput (package:nnbd_migration/src/nullability_migration_impl.dart:189:16)
#7      NonNullableFix.finalizeUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:115:15)
#8      _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1159:21)
#9      _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1156:28)
#10     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#11     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1156:5)
<asynchronous suspension>
#12     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#13     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#15     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#16     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#17     main (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by PiotrWpl** [comment]
Hi, any tips? It's a real blocker for me. Doing manual migration is not an option in this project.

**Comment by PiotrWpl** [comment]
I was able to find the issue, I had something like this:
`final Dog dog = widget.dog ?? ModalRoute.of(context).settings.arguments as Dog /*!*/;`
and when I removed the comment on the end everything has start working again
`final Dog dog = widget.dog ?? ModalRoute.of(context).settings.arguments as Dog;`
