### ISSUE TITLE
Analysis/parse failure "type 'GenericFunctionTypeImpl' is not a subtype of type 'TypeName' in type cast" on invalid implements

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#45565]
Noted by @jeroen-meijer [on twitter](https://twitter.com/jfkdev/status/1378012304332181506). I simplified the repro a little to:

```dart
class A
implements C Function()
```

This causes "type 'GenericFunctionTypeImpl' is not a subtype of type 'TypeName' in type cast" during analysis/parsing:

<img width="1390" alt="Screenshot 2021-04-02 at 17 23 09" src="https://user-images.githubusercontent.com/1078012/113434001-251feb80-93d8-11eb-8402-29c8788975a6.png">

**Comment by DanTup** [comment]
Just tidying up some old issues so was testing if this still occurs. In case it's useful, it does on Flutter 3.3 / Dart 2.18:

```dart
class A implements C Function()
```

```
[16:21:04] [Analyzer] [Error] Unhandled exception:
type 'GenericFunctionTypeImpl' is not a subtype of type 'NamedType' in type cast
#0      AstBuilder.popTypedList2 (package:analyzer/src/fasta/ast_builder.dart:4181:37)
#1      AstBuilder.handleImplements (package:analyzer/src/fasta/ast_builder.dart:3281:24)
#2      Parser.parseClassOrMixinOrEnumImplementsOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2434:14)
#3      Parser.parseClassHeaderOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2280:13)
#4…
[16:21:04] [Analyzer] [Info] Spawning /Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.48.1"]
```
