### ISSUE TITLE
dart2js crash when using super mixins with private names

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45567]
When run on the program below, dart2js crashes with the stack trace also included below.  This is triggered by a new nonfunction type alias test out for review [here](https://dart-review.googlesource.com/c/sdk/+/193828), but seems to be unrelated to the new feature given the repro case below.

// lib1.dart
```
class PublicClass {
  int _privateInstanceMethod() => -1;
}

mixin PublicSuperMixin on PublicClass {
  int _privateMixinMethod() => super._privateInstanceMethod();
}
```

// main.dart
```
import "package:expect/expect.dart";

import "lib1.dart";

class Derived2 extends PublicClass with PublicSuperMixin {
  int _privateMixinMethod() => 1;
}

void test2() {
  // Test that the super-mixin methods resolve correctly.
  var p = Derived2();
  Expect.equals(1, p._privateMixinMethod());
}

void main() {
  test2();
}
```

cc @sigmundch @rakudrama @fishythefish

**Comment by rakudrama** [comment]
I can't repro with the given files. What stack did you see?

**Comment by leafpetersen** [comment]
Sorry forgot that part.  Interestingly, it seems to require the `--test-mode` flag to reproduce.  Enclosed below is a command line and the resulting stack trace.  If I remove the `--test-mode` then the error goes away.

```
leafp-macbookpro:sdk leafp$ sdk/bin/dart2js_developer --test-mode  /Users/leafp/tmp/test.dart --libraries-spec=sdk/lib/libraries.json --platform-binaries=xcodebuild/ReleaseX64/  --out=/Users/leafp/tmp.js
../../../tmp/test.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'node' was called on null.
Receiver: null
Tried calling: node
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      AbstractDataSource.readMemberNode (package:compiler/src/serialization/abstract_source.dart:309:30)
#2      DataSourceMixin.readStringMap (package:compiler/src/serialization/mixins.dart:245:18)
#3      new JClassEnvImpl.readFromDataSource (package:compiler/src/js_model/env.dart:254:16)
#4      new JClassEnv.readFromDataSource (package:compiler/src/js_model/env.dart:182:20)
#5      new JsKernelToElementMap.readFromDataSource.<anonymous closure> (package:compiler/src/js_model/element_map_impl.dart:359:27)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#7      _EntityLookup.forEachClass (package:compiler/src/js_model/element_map_impl.dart:2561:14)
#8      new JsKernelToElementMap.readFromDataSource (package:compiler/src/js_model/element_map_impl.dart:358:18)
#9      new JsClosedWorld.readFromDataSource (package:compiler/src/js_model/js_world.dart:135:13)
#10     deserializeClosedWorldFromSource (package:compiler/src/serialization/task.dart:104:14)
#11     BytesInMemorySerializationStrategy.deserializeGlobalTypeInferenceResults (package:compiler/src/serialization/strategies.dart:94:33)
#12     Compiler.globalTypeInferenceResultsTestMode (package:compiler/src/compiler.dart:457:21)
#13     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:500:13)
#14     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#15     Compiler.compileFromKernel (package:compiler/src/compiler.dart:469:14)
#16     Compiler.runInternal (package:compiler/src/compiler.dart:304:13)
<asynchronous suspension>
```

**Comment by fishythefish** [comment]
Yeah, `--test-mode` adds extra serialization/deserialization between the phases, which is where this NPE is coming from.

**Comment by fishythefish** [comment]
https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/serialization/member_data.dart#L37 seems to be responsible.

**Comment by leafpetersen** [comment]
To be clear, this isn't blocking me.  I'll approve the test with this issue and land it.
