### ISSUE TITLE
Dart Analyzer Terminated

### ISSUE THREAD

**Issue by krishnawijaya** [dart-lang/sdk#45585]
**Analyzer feedback from android studio**

## Dart analysis issue

NoSuchMethodError: The setter 'type=' was called on null.

## Version information

- Dart SDK 2.12.2
- Dart IntelliJ 201.9335
- Android Studio 4.1.3
- Windows 10 10.0

## Details

NoSuchMethodError: The setter 'type=' was called on null.
Receiver: null
Tried calling: type=Instance of 'InterfaceTypeImpl'

```lang-none
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      Null.type= (dart:core/null.dart:1:1)
#2      ApplyResolutionVisitor.visitVariableDeclaration (package:analyzer/src/summary2/apply_resolution.dart:1327:13)
#3      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10555:49)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#5      ApplyResolutionVisitor.visitVariableDeclarationList (package:analyzer/src/summary2/apply_resolution.dart:1345:20)
#6      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10655:15)
#7      ApplyResolutionVisitor.visitTopLevelVariableDeclaration (package:analyzer/src/summary2/apply_resolution.dart:1231:20)
#8      TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:9909:15)
#9      LinkedContext.applyResolution (package:analyzer/src/summary2/bundle_reader.dart:512:11)
#10     LinkedUnitContext.applyResolution (package:analyzer/src/summary2/linked_unit_context.dart:93:25)
#11     PropertyInducingElementImpl.typeInternal (package:analyzer/src/dart/element/element.dart:6731:21)
#12     ElementTypeProvider.getFieldType (package:analyzer/src/generated/element_type_provider.dart:62:15)
#13     PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:6724:52)
#14     PropertyAccessorElementImpl_ImplicitGetter.returnTypeInternal (package:analyzer/src/dart/element/element.dart:6579:47)
#15     ElementTypeProvider.getExecutableReturnType (package:analyzer/src/generated/element_type_provider.dart:49:15)
#16     PropertyAccessorElementImpl_ImplicitGetter.returnType (package:analyzer/src/dart/element/element.dart:6571:35)
#17     PropertyAccessorElementImpl_ImplicitGetter.typeInternal (package:analyzer/src/dart/element/element.dart:6596:19)
#18     ElementTypeProvider.getExecutableType (package:analyzer/src/generated/element_type_provider.dart:55:15)
#19     PropertyAccessorElementImpl_ImplicitGetter.type (package:analyzer/src/dart/element/element.dart:6582:56)
#20     SimpleIdentifierResolver._getTypeOfProperty (package:analyzer/src/dart/resolver/simple_identifier_resolver.dart:52:42)
#21     SimpleIdentifierResolver._resolve2 (package:analyzer/src/dart/resolver/simple_identifier_resolver.dart:257:20)
#22     SimpleIdentifierResolver.resolve (package:analyzer/src/dart/resolver/simple_identifier_resolver.dart:42:5)
#23     ResolverVisitor.visitSimpleIdentifier (package:analyzer/src/generated/resolver.dart:1863:51)
#24     SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8970:49)
#25     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:887:20)
#26     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:355:49)
#27     MethodInvocationResolver._resolveArguments (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:291:23)
#28     MethodInvocationResolver._resolveArguments_finishInference (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:295:5)
#29     MethodInvocationResolver._setDynamicResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:782:5)
#30     MethodInvocationResolver._resolveReceiverType (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:675:5)
#31     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:542:5)
#32     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:93:7)
#33     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:394:31)
#34     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#35     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1706:10)
#36     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#37     AwaitExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:902:18)
#38     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#39     UnifyingAstVisitor.visitAwaitExpression (package:analyzer/dart/ast/visitor.dart:3137:51)
#40     ResolverVisitor.visitAwaitExpression (package:analyzer/src/generated/resolver.dart:944:11)
#41     AwaitExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:898:49)
#42     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3680:18)
#43     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#44     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3229:59)
#45     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3676:49)
#46     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#47     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#48     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#49     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#50     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#51     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#52     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#53     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#54     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1042:13)
#55     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#56     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3146:55)
#57     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2489:13)
#58     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:957:13)
#59     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#60     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5010:12)
#61     FunctionExpressionResolver.resolve (package:analyzer/src/dart/resolver/function_expression_resolver.dart:65:10)
#62     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:1460:37)
#63     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5004:49)
#64     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7385:18)
#65     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#66     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3360:51)
#67     ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:1744:11)
#68     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7380:49)
#69     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:887:20)
#70     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:355:49)
#71     ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1621:24)
#72     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6130:15)
#73     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#74     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6762:15)
#75     TypedLiteralResolver.resolveListLiteral (package:analyzer/src/dart/resolver/typed_literal_resolver.dart:97:10)
#76     ResolverVisitor.visitListLiteral (package:analyzer/src/generated/resolver.dart:1648:27)
#77     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6757:49)
#78     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7385:18)
#79     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#80     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3360:51)
#81     ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:1744:11)
#82     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7380:49)
#83     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:887:20)
#84     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:355:49)
#85     ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1621:24)
#86     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6130:15)
#87     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#88     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6762:15)
#89     TypedLiteralResolver.resolveListLiteral (package:analyzer/src/dart/resolver/typed_literal_resolver.dart:97:10)
#90     ResolverVisitor.visitListLiteral (package:analyzer/src/generated/resolver.dart:1648:27)
#91     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6757:49)
#92     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7385:18)
#93     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#94     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3360:51)
#95     ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:1744:11)
#96     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7380:49)
#97     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:887:20)
#98     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:355:49)
#99     ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1621:24)
#100    InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6130:15)
#101    NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7385:18)
#102    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#103    UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3360:51)
#104    ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:1744:11)
#105    NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7380:49)
#106    ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:887:20)
#107    ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:355:49)
#108    ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1621:24)
#109    InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6130:15)
#110    NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7385:18)
#111    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#112    UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3360:51)
#113    ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:1744:11)
#114    NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7380:49)
#115    ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:887:20)
#116    ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:355:49)
#117    ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1621:24)
#118    InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6130:15)
#119    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#120    ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6762:15)
#121    TypedLiteralResolver.resolveListLiteral (package:analyzer/src/dart/resolver/typed_literal_resolver.dart:97:10)
#122    ResolverVisitor.visitListLiteral (package:analyzer/src/generated/resolver.dart:1648:27)
#123    ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6757:49)
#124    NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7385:18)
#125    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#126    UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3360:51)
#127    ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:1744:11)
#128    NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7380:49)
#129    ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:887:20)
#130    ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:355:49)
#131    ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1621:24)
#132    InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6130:15)
#133    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#134    ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6762:15)
#135    TypedLiteralResolver.resolveListLiteral (package:analyzer/src/dart/resolver/typed_literal_resolver.dart:97:10)
#136    ResolverVisitor.visitListLiteral (package:analyzer/src/generated/resolver.dart:1648:27)
#137    ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6757:49)
#138    NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7385:18)
#139    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#140    UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3360:51)
#141    ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:1744:11)
#142    NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7380:49)
#143    ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:887:20)
#144    ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:355:49)
#145    ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1621:24)
#146    InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6130:15)
#147    NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7385:18)
#148    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#149    UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3360:51)
#150    ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:1744:11)
#151    NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7380:49)
#152    ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:887:20)
#153    ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:355:49)
#154    ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1621:24)
#155    InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6130:15)
#156    ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8621:18)
#157    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#158    UnifyingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:3410:51)
#159    ResolverVisitor.visitReturnStatement (package:analyzer/src/generated/resolver.dart:1846:11)
#160    ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8617:49)
#161    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#162    BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#163    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#164    UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#165    ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#166    ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#167    ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#168    BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#169    BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1042:13)
#170    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#171    UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3146:55)
#172    ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2489:13)
#173    ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:957:13)
#174    BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#175    MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7042:12)
#176    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#177    UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3351:55)
#178    ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:2926:11)
#179    ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:2919:7)
#180    ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:1666:11)
#181    MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#182    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#183    ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:2550:18)
#184    ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2531:7)
#185    ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:1015:13)
#186    ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#187    ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:1091:23)
#188    CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#189    LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:709:10)
#190    LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:139:7)
#191    _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#192    LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:138:11)
#193    LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:12)
#194    AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1319:63)
#195    PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#196    AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1296:20)
#197    AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1249:14)
#198    _rootRun (dart:async/zone.dart:1354:13)
#199    _CustomZone.run (dart:async/zone.dart:1258:19)
#200    _runZoned (dart:async/zone.dart:1788:10)
#201    runZoned (dart:async/zone.dart:1710:10)
#202    NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#203    AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1248:40)
#204    AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1386:37)
#205    AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:995:39)
#206    AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2018:24)
<asynchronous suspension>

#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:480:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1241:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:1164:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:402:11)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

## Debug log

```lang-none
1617529296421 => {"id":"1198","method":"analysis.updateContent","params":{"files":{"C:\\Users\\krish\\AndroidStudioProjects\\smart_vendor\\lib\\screens\\detail_order_screen.dart":{"type":"add","conten...
1617529296421 <= {"id":"1198","result":{}}
1617529296421 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1617529296452 => {"id":"1199","method":"edit.getAssists","params":{"file":"C:\\Users\\krish\\AndroidStudioProjects\\smart_vendor\\lib\\screens\\detail_order_screen.dart","offset":124,"length":0},"clie...
1617529296608 <= {"id":"1199","result":{"assists":[]}}
1617529296608 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":982,"uri":"package:smart_vendor/screens/screens.dart","items":[{"label":"IllustrationPage","declaringLib...
1617529296608 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1617529297046 => {"id":"1200","method":"analysis.updateContent","params":{"files":{"C:\\Users\\krish\\AndroidStudioProjects\\smart_vendor\\lib\\screens\\detail_order_screen.dart":{"type":"add","conten...
1617529297046 <= {"id":"1200","result":{}}
1617529297046 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1617529297077 => {"id":"1201","method":"edit.getAssists","params":{"file":"C:\\Users\\krish\\AndroidStudioProjects\\smart_vendor\\lib\\screens\\detail_order_screen.dart","offset":123,"length":0},"clie...
1617529297216 <= {"id":"1201","result":{"assists":[]}}
1617529297232 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":982,"uri":"package:smart_vendor/screens/screens.dart","items":[{"label":"IllustrationPage","declaringLib...
1617529297232 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1617529299111 => {"id":"1202","method":"edit.getAssists","params":{"file":"C:\\Users\\krish\\AndroidStudioProjects\\smart_vendor\\lib\\screens\\detail_order_screen.dart","offset":261,"length":8},"clie...
1617529299173 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1617529299173 <= {"id":"1202","result":{"assists":[]}}
1617529299173 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1617529300705 => {"id":"1203","method":"analysis.setPriorityFiles","params":{"files":["C:\\Developments\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart"]},"clientRequestTime":1617529300...
1617529300705 => {"id":"1204","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["C:\\Developments\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart"],"CLOSING_L...
1617529300705 <= {"id":"1203"}
1617529300705 <= {"id":"1204"}
1617529300830 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1617529300845 <= {"event":"analysis.highlights","params":{"file":"C:\\Developments\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart","regions":[{"type":"DIRECTIVE","offset":169,"length":...
1617529300861 <= {"event":"analysis.navigation","params":{"file":"C:\\Developments\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart","regions":[{"offset":176,"length":12,"targets":[0]},{...
1617529300861 <= {"event":"analysis.closingLabels","params":{"file":"C:\\Developments\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart","labels":[{"offset":9145,"length":486,"label":"Flu...
1617529300876 <= {"event":"analysis.outline","params":{"file":"C:\\Developments\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATI...
1617529300876 <= {"event":"analysis.overrides","params":{"file":"C:\\Developments\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart","overrides":[{"offset":2033,"length":8,"superclassMemb...
1617529300892 <= {"event":"flutter.outline","params":{"file":"C:\\Developments\\flutter\\packages\\flutter\\lib\\src\\widgets\\framework.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":2660...
1617529300892 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
```

**This is one of some files that caused this exception:** 

    library screens;
    
    import 'package:flutter_bloc/flutter_bloc.dart';
    import 'package:get/get.dart';
    import 'package:flutter/material.dart';
    import 'package:smart_vendor/lang/lang.dart';
    import 'package:smart_vendor/cubit/cubit.dart';
    import 'package:smart_vendor/models/models.dart';
    import 'package:smart_vendor/shared/shared.dart';
    import 'package:smart_vendor/widgets/widgets.dart';
    
    part 'address_page.dart';
    part 'general_page.dart';
    part 'sign_in_page.dart';
    part 'sign_up_page.dart';
    part 'sign_up_agent_page.dart';
    part 'sign_up_personal_page.dart';
    part 'sign_up_business_page.dart';
    part 'main_page.dart';
    part 'profile_page.dart';
    part 'history_page.dart';
    part 'illustration_page.dart';
    part 'filter_page.dart';
    part 'success_page.dart';
    part 'success_sign_up_page.dart';
    part 'take_order_confirmation_page.dart';
    part 'detail_order_screen.dart';

**Comment by srawlins** [comment]
Closing as stale; please re-open if you see this crash on a recent version of Dart.
