### ISSUE TITLE
Timer.isActive is false while callback is ecuting

### ISSUE THREAD

**Issue by zathras** [dart-lang/sdk#45666]
While a non-periodic timer is executing, Timer.isActive gives false.  This is at odds with the documentation.

The current behavior isn't unreasonable, so this could be addressed either by fixing the documentation, or by changing the implementation to agree with the documentation.

Simple to reproduce:
```
import 'dart:async';

late final Timer t;

void main() {
  t = Timer(Duration(milliseconds: 0), () {
    print(t.isActive);
    assert(t.isActive);
    // See https://api.flutter.dev/flutter/dart-async/Timer/isActive.html
    // (as of 4/12/2021):
    //
    // "A non-periodic timer is active if the callback has not been
    // executed, and the timer has not been canceled."
    //
    // The callback is executING, so it clearly has not been executed.
  });
}
```

```
billf@zathras:~/tmp/tmp$ !da
dart --enable-asserts foo.dart 
false
Unhandled exception:
'file:///home/billf/tmp/tmp/foo.dart': Failed assertion: line 9 pos 12: 't.isActive': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
dart-lang/language#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
dart-lang/language#2      main.<anonymous closure> (file:///home/billf/tmp/tmp/foo.dart:9:12)
dart-lang/language#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
dart-lang/language#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
dart-lang/language#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
dart-lang/language#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by lrhn** [comment]
It's a documentation issue. It's not precisely wrong, it's just not precise. 
The `isActive` is `true` *until* the callback *is* executed, not until it *has* executed. It stops being active when the callback is invoked (or really, *right before*).

**Comment by zathras** [comment]
Right, that's clearly what's happening.

Being a bit pedantic, the documentation is, precisely speaking, wrong.  "Is executed" is not the same thing as "is submitted for execution to an internal queue;" the English language meaning of the black-letter text "is executed" does not allow an interpretation that includes adding code to a queue, but not actually executing it yet.  It's a language issue, not a technical issue (if this is the intended behavior, which is reasonable), but the language is incorrect.

Further, the documentation should note that isActive will be false during execution, since that's not obvious, even if the normative part of the language is fixed.

**Comment by lrhn** [comment]
I agree that the phrasing is undesirable. I may or may not agree on whether it's unambiguously wrong.
(We regularly say "when a function is called" to mean when the call *starts*. The "executed" used here about a function really means when the function is called.)

**Comment by zathras** [comment]
Fair point.  Whether or not it's "wrong" depends more or less on how
    much of a distinction one makes between formal, normative
    specification text, and more casual language.  That's essentially a
    cultural thing - different organizations take different stances on
    formal spec text vs. [reference] implementation.  
    
    I went through the evolution of JavaSoft's culture from the latter
    to the former, so I tend to view specification with a certain
    formality.
    
    Anyhoo, it'll be nice to fix up the text!
    
    On 4/14/21 12:55 AM, Lasse R.H. Nielsen
      wrote:
    
    
      
      I agree that the phrasing is undesirable. I may or may not
        agree on whether it's unambiguously wrong.
        (We regularly say "when a function is called" to mean when the
        call starts. The "executed" used here about a function
        really means when the function is called.)
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/dart-lang/sdk/issues/45666#issuecomment-819312823",
"url": "https://github.com/dart-lang/sdk/issues/45666#issuecomment-819312823",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
