### ISSUE TITLE
Error - Unhandled Exception: HttpException: Unexpected response (unsolicited response without request)

### ISSUE THREAD

**Issue by shashank-gb** [dart-lang/sdk#45668]
I'm having an issue while making an HTTP post request in order to send the data to My SQL via php as an API. `http` and `dio` packages both throws same error. Hence I think it's an error from `dart:async`.

**ERROR**
```
E/flutter (14533): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: HttpException: Unexpected response (unsolicited response without request).
E/flutter (14533): #0      new _HttpClientConnection.<anonymous closure> (dart:_http/http_impl.dart:1824:9)
E/flutter (14533): #1      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (14533): #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (14533): #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (14533): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (14533): #5      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (14533): #6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (14533): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (14533): #8      _rootRun (dart:async/zone.dart:1346:47)
E/flutter (14533): #9      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14533): #10     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14533): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (14533): #12     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (14533): #13     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14533): #14     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14533): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (14533): #16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (14533): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
* Using `Dart SDK version: 2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "windows_x64"`

**Note :** I am running this application in mobile device

**Comment by shashank-gb** [comment]
> This issue was moved by [keertip](https://github.com/keertip) to [flutter/flutter#80407](https://github.com/flutter/flutter/issues/80407).

Isn't it a `dart:async` issue. How to find issue belongs to which package? and there is no flutter package named in error hence asked...
