### ISSUE TITLE
Exception from migration tool: Unrelated types: class (redacted)<T> and abstract class FutureOr<T>

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#45663]
Filed internally as https://buganizer.corp.google.com/issues/185131819

Here is the stacktrace, with redactions to avoid exposing internal IP:
```
Bad state: Unrelated types: class (redacted)<T> and abstract class FutureOr<T> at (redacted)

#0 DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:67:10)
#1 DecoratedClassHierarchy.asInstanceOf (package:nnbd_migration/src/decorated_class_hierarchy.dart:38:18)
#2 EdgeBuilder._decorateUpperOrLowerBound (package:nnbd_migration/src/edge_builder.dart:2105:18)
#3 EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:495:26)
#4 BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:951:50)
#5 EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#6 EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#7 EdgeBuilder.visitVariableDeclarationList (package:nnbd_migration/src/edge_builder.dart:1924:11)
#8 VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10507:15)
#9 EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#10 EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#11 GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#12 GeneralizingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:593:7)
#13 VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10556:15)
#14 EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#15 EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#16 GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
