### ISSUE TITLE
exception when migrating pkg/vm_snapshot_analysis

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#45690]
```
$ cd pkg/vm_snapshot_analysis
$ dart pub upgrade
$ dart pub outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

All your dependencies declare support for null-safety.
$ dart migrate
Migrating /Users/vegorov/src/dart/sdk/pkg/vm_snapshot_analysis

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------/]No analysis issues found.

Generating migration suggestions...
[-------------------------------------------------------------------------------------------------------|                                                                                                                                                                              ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.12.0) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

Never.substitute(Never | {T: void?(type argument 0 of supertype of CompareCommand (compare.dart:21:38))}) at offset 2583 in /Users/vegorov/src/dart/sdk/pkg/vm_snapshot_analysis/lib/src/commands/compare.dart (usageException('Need to provide path to old.json and new.json reports.'))

#0      DecoratedType._substitute (package:nnbd_migration/src/decorated_type.dart:467:5)
#1      DecoratedType._substituteFunctionAfterFormals (package:nnbd_migration/src/decorated_type.dart:495:24)
#2      DecoratedType._substitute (package:nnbd_migration/src/decorated_type.dart:446:14)
#3      DecoratedType.substitute (package:nnbd_migration/src/decorated_type.dart:327:12)
#4      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:304:32)
#5      EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1284:20)
#6      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#7      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#8      EdgeBuilder.visitExpressionStatement (package:nnbd_migration/src/edge_builder.dart:801:25)
#9      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3676:49)
#10     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#11     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#12     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#13     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#14     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#15     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#16     EdgeBuilder.visitIfStatement.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:1037:25)
#17     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#18     EdgeBuilder.visitIfStatement (package:nnbd_migration/src/edge_builder.dart:1036:28)
#19     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5705:49)
#20     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#21     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#22     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#23     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#24     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#25     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#26     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#27     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:324:45)
#28     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:55)
#29     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#30     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#31     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2488:7)
#32     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#33     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#34     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#35     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#36     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#37     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#38     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#39     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#40     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#41     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:51)
#42     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#43     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#44     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#45     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#46     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#47     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#48     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1154:19)
#49     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:28)
#50     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#51     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1152:5)
<asynchronous suspension>
#52     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#53     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#54     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#55     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#56     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#57     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by stereotype441** [comment]
Thanks for the bug report @mraleph!  Were you able to make progress with the migration by re-running with `--ignore-exceptions`?

**Comment by mraleph** [comment]
I just migrated manually

**Comment by stereotype441** [comment]
> I just migrated manually

Ok, thanks.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
