### ISSUE TITLE
[cfe] Crash on function type as on-type of mixin

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45700]
Consider the following program:

```dart
mixin M on Function() {}
void main() {}
```

It is a [compile-time error](https://github.com/dart-lang/language/blob/ff957765b7dd4495bdb2a74157671a0d019ef48d/specification/dartLangSpec.tex#L5313) if a mixin has an on-type which is a function type, but the CFE crashes in this case:

```
Crash when compiling file:///usr/local/google/home/eernst/lang/dart/scratch/202104/n016.dart,
at character offset null:
type 'FunctionTypeBuilder' is not a subtype of type 'NamedTypeBuilder' in type cast
#0      StackImpl.popList (package:_fe_analyzer_shared/src/parser/stack_listener.dart:578:25)
#1      FixedNullableList.pop (package:_fe_analyzer_shared/src/parser/stack_listener.dart:662:18)
#2      OutlineBuilder.handleMixinOn (package:front_end/src/fasta/source/outline_builder.dart:558:54)
#3      Parser.parseMixinOn (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2298:14)
#4      Parser.parseMixinOnOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2283:12)
#5      Parser.parseMixinHeaderOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2195:13)
#6      Parser.parseMixin (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2182:19)
#7      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:620:18)
#8      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
#9      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#10     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:468:37)
<asynchronous suspension>
#11     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:289:7)
<asynchronous suspension>
#12     SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:362:5)
```

**Comment by lfkdsk** [comment]
Hi, try to solve: https://github.com/dart-lang/sdk/pull/45739
