### ISSUE TITLE
Dart loading error

### ISSUE THREAD

**Issue by Logic2019** [dart-lang/sdk#45743]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.12.2`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.12.2, server version 1.32.4, FATAL error: UnimplementedError: Encoding "null"
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:480:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1241:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:1164:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:402:11)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

For additional log information, please append the contents of
file://C:\Users\Logic\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Sorry we didn't get to this error. Closing as stale, but please re-open if you encounter this again.
