### ISSUE TITLE
Null check operator during textDocument completion

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#45742]
Received the following error when working on some Dart code:

```
[Error - 2:13:02 PM] Request textDocument/completion failed.
  Message: An error occurred while handling textDocument/completion request
  Code: -32001 
[Error - 2:13:02 PM] An error occurred while handling textDocument/completion request: Null check operator used on a null value
#0      DartCompletionRequestImpl.targetPrefix (package:analysis_server/src/services/completion/dart/completion_manager.dart:371:33)
#1      CompletionHandler._getServerDartItems.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:372:52)
<asynchronous suspension>
#2      CompletionPerformance.runRequestOperation.<anonymous closure> (package:analysis_server/src/services/completion/completion_performance.dart:62:16)
<asynchronous suspension>
#3      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:160:14)
<asynchronous suspension>
#4      CompletionHandler._getServerDartItems (package:analysis_server/src/lsp/handlers/handler_completion.dart:199:12)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#6      CompletionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:110:11)
<asynchronous suspension>
#7      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:187:22)
<asynchronous suspension>
#8      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:302:26)
<asynchronous suspension>
```

**Comment by robinjohn** [comment]
Steps to reproduce the issue always help. 😊

**Comment by bwilkerson** [comment]
I believe that this was fixed by https://dart-review.googlesource.com/c/sdk/+/195504.
