### ISSUE TITLE
Analyzer exception in convert_into_async_body fix for invalid code

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#45768]
Given the following code (with a missing `*` from `sync*`):

```
class Foo {
  Iterable<String> a() sync {}
}
```

Exceptions occur when fetching code fixes (these appear as failed LSP requests for LSP users):

**Invalid argument(s): The function must have a synchronous, non-generator body.**

```
[Error - 3:25:04 PM] An error occurred while handling textDocument/codeAction request: Invalid argument(s): The function must have a synchronous, non-generator body.
#0      DartFileEditBuilderImpl.convertFunctionFromSyncToAsync (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1308:7)
#1      ConvertIntoAsyncBody.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/convert_into_async_body.dart:42:15)
#2      ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:101:20)
<asynchronous suspension>
#3      ConvertIntoAsyncBody.compute (package:analysis_server/src/services/correction/dart/convert_into_async_body.dart:41:5)
<asynchronous suspension>
#4      AssistProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/assist_internal.dart:241:9)
<asynchronous suspension>
#5      AssistProcessor._addFromProducers (package:analysis_server/src/services/correction/assist_internal.dart:259:9)
<asynchronous suspension>
#6      AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:170:5)
<asynchronous suspension>
#7      CodeActionHandler._getAssistActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:237:23)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#9      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:266:21)
<asynchronous suspension>
#10     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:187:22)
<asynchronous suspension>
#11     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:310:26)
<asynchronous suspension>
```

**Comment by DanTup** [comment]
This was fixed by b81dedad12ba34f893fdd94c75a3dd224d21d65c.
