### ISSUE TITLE
[vm/ffi] Crach on CFE when compiling a struct with a wrong annotation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#45764]
The following code produces a crash on CFE
```dart
class S1 extends Struct {
  @Int8()
  external double x;
  @Int8()
  external int y;
}
```
Here we have `double` member annotated as `Int8` and there must be a compile error (and it is in analyzer) but on CFE we have

```
Crash when compiling null,
at character offset null:
Bad state: No element
#0      List.single (dart:core-patch/growable_array.dart:342:22)
#1      _FfiUseSiteTransformer._inlineSizeOf (package:vm/transformations/ffi_use_sites.dart:428:46)
#2      _FfiUseSiteTransformer.visitStaticInvocation (package:vm/transformations/ffi_use_sites.dart:364:34)
#3      StaticInvocation.accept (package:kernel/ast.dart:6122:44)
#4      Transformer.transform (package:kernel/visitor.dart:1025:21)
#5      VariableDeclaration.transformChildren (package:kernel/ast.dart:10078:23)
#6      Transformer.defaultTreeNode (package:kernel/visitor.dart:1082:10)
#7      TreeVisitor.defaultStatement (package:kernel/visitor.dart:260:41)
#8      TreeVisitor.visitVariableDeclaration (package:kernel/visitor.dart:282:7)
#9      VariableDeclaration.accept (package:kernel/ast.dart:10060:43)
#10     Transformer.transform (package:kernel/visitor.dart:1025:21)
#11     Transformer.transformList (package:kernel/visitor.dart:1060:18)
#12     Block.transformChildren (package:kernel/ast.dart:8532:7)
#13     Transformer.defaultTreeNode (package:kernel/visitor.dart:1082:10)
#14     TreeVisitor.defaultStatement (package:kernel/visitor.dart:260:41)
#15     TreeVisitor.visitBlock (package:kernel/visitor.dart:263:31)
#16     Block.accept (package:kernel/ast.dart:8520:43)
#17     Transformer.transform (package:kernel/visitor.dart:1025:21)
#18     FunctionNode.transformChildren (package:kernel/ast.dart:3416:16)
#19     Transformer.defaultTreeNode (package:kernel/visitor.dart:1082:10)
#20     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:317:45)
#21     FunctionNode.accept (package:kernel/ast.dart:3394:38)
#22     Transformer.transform (package:kernel/visitor.dart:1025:21)
#23     Procedure.transformChildren (package:kernel/ast.dart:2763:20)
#24     Transformer.defaultTreeNode (package:kernel/visitor.dart:1082:10)
#25     TreeVisitor.defaultMember (package:kernel/visitor.dart:287:35)
#26     TreeVisitor.visitProcedure (package:kernel/visitor.dart:289:39)
#27     _FfiUseSiteTransformer.visitProcedure (package:vm/transformations/ffi_use_sites.dart:143:26)
#28     Procedure.accept (package:kernel/ast.dart:2743:40)
#29     Transformer.transform (package:kernel/visitor.dart:1025:21)
#30     Transformer.transformList (package:kernel/visitor.dart:1060:18)
#31     Library.transformChildren (package:kernel/ast.dart:532:7)
#32     Transformer.defaultTreeNode (package:kernel/visitor.dart:1082:10)
#33     TreeVisitor.visitLibrary (package:kernel/visitor.dart:311:35)
#34     FfiTransformer.visitLibrary (package:vm/transformations/ffi.dart:438:26)
#35     _FfiUseSiteTransformer.visitLibrary (package:vm/transformations/ffi_use_sites.dart:99:18)
#36     List.forEach (dart:core-patch/growable_array.dart:403:8)
#37     transformLibraries (package:vm/transformations/ffi_use_sites.dart:68:13)
#38     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:170:7)
#39     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1234:19)
#40     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:372:7)
<asynchronous suspension>
#41     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#42     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#43     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#44     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#45     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#46     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#47     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#48     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#49     _processLoadRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>


#0      List.single (dart:core-patch/growable_array.dart:342:22)
#1      _FfiUseSiteTransformer._inlineSizeOf (package:vm/transformations/ffi_use_sites.dart:428:46)
#2      _FfiUseSiteTransformer.visitStaticInvocation (package:vm/transformations/ffi_use_sites.dart:364:34)
#3      StaticInvocation.accept (package:kernel/ast.dart:6122:44)
#4      Transformer.transform (package:kernel/visitor.dart:1025:21)
#5      VariableDeclaration.transformChildren (package:kernel/ast.dart:10078:23)
#6      Transformer.defaultTreeNode (package:kernel/visitor.dart:1082:10)
#7      TreeVisitor.defaultStatement (package:kernel/visitor.dart:260:41)
#8      TreeVisitor.visitVariableDeclaration (package:kernel/visitor.dart:282:7)
#9      VariableDeclaration.accept (package:kernel/ast.dart:10060:43)
#10     Transformer.transform (package:kernel/visitor.dart:1025:21)
#11     Transformer.transformList (package:kernel/visitor.dart:1060:18)
#12     Block.transformChildren (package:kernel/ast.dart:8532:7)
#13     Transformer.defaultTreeNode (package:kernel/visitor.dart:1082:10)
#14     TreeVisitor.defaultStatement (package:kernel/visitor.dart:260:41)
#15     TreeVisitor.visitBlock (package:kernel/visitor.dart:263:31)
#16     Block.accept (package:kernel/ast.dart:8520:43)
#17     Transformer.transform (package:kernel/visitor.dart:1025:21)
#18     FunctionNode.transformChildren (package:kernel/ast.dart:3416:16)
#19     Transformer.defaultTreeNode (package:kernel/visitor.dart:1082:10)
#20     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:317:45)
#21     FunctionNode.accept (package:kernel/ast.dart:3394:38)
#22     Transformer.transform (package:kernel/visitor.dart:1025:21)
#23     Procedure.transformChildren (package:kernel/ast.dart:2763:20)
#24     Transformer.defaultTreeNode (package:kernel/visitor.dart:1082:10)
#25     TreeVisitor.defaultMember (package:kernel/visitor.dart:287:35)
#26     TreeVisitor.visitProcedure (package:kernel/visitor.dart:289:39)
#27     _FfiUseSiteTransformer.visitProcedure (package:vm/transformations/ffi_use_sites.dart:143:26)
#28     Procedure.accept (package:kernel/ast.dart:2743:40)
#29     Transformer.transform (package:kernel/visitor.dart:1025:21)
#30     Transformer.transformList (package:kernel/visitor.dart:1060:18)
#31     Library.transformChildren (package:kernel/ast.dart:532:7)
#32     Transformer.defaultTreeNode (package:kernel/visitor.dart:1082:10)
#33     TreeVisitor.visitLibrary (package:kernel/visitor.dart:311:35)
#34     FfiTransformer.visitLibrary (package:vm/transformations/ffi.dart:438:26)
#35     _FfiUseSiteTransformer.visitLibrary (package:vm/transformations/ffi_use_sites.dart:99:18)
#36     List.forEach (dart:core-patch/growable_array.dart:403:8)
#37     transformLibraries (package:vm/transformations/ffi_use_sites.dart:68:13)
#38     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:170:7)
#39     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1234:19)
#40     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:372:7)
<asynchronous suspension>
#41     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#42     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#43     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#44     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#45     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#46     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#47     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#48     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#49     _processLoadRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>
```

`Dart SDK version: 2.14.0-3.0.dev (dev) (Tue Apr 13 22:57:19 2021 -0700) on "windows_x64" `

**Comment by sgrekhov** [comment]
cc @dcharkes

**Comment by sgrekhov** [comment]
No this issue on `Dart SDK version: 2.14.0-18.0.dev (dev) (Mon Apr 19 18:22:45 2021 -0700) on "windows_x64" `
