### ISSUE TITLE
[cfe] Assignment to variable with extension type crashes with "Unhandled type"

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#45775]
`dart --enable-experiment=extension-types <test_file>`

with the following as the test file:

```
class Foo {}

extension Bar on Foo {}

void main() {
  Bar bar = Foo();
}
```

fails with:

<details>
  <summary>Crash report</summary>

```
Unhandled type: ExtensionType
#0      Types.performNullabilityAwareSubtypeCheck (package:kernel/src/types.dart:254:7)
#1      TypeSchemaEnvironment.performNullabilityAwareSubtypeCheck (package:front_end/src/fasta/type_inference/type_schema_environment.dart:413:18)
#2      TypeInferrerImpl._computeAssignabilityKind (package:front_end/src/fasta/type_inference/type_inferrer.dart:804:10)
#3      TypeInferrerImpl.ensureAssignable (package:front_end/src/fasta/type_inference/type_inferrer.dart:529:47)
#4      TypeInferrerImpl.ensureAssignableResult (package:front_end/src/fasta/type_inference/type_inferrer.dart:449:12)
#5      InferenceVisitor.visitVariableDeclaration (package:front_end/src/fasta/kernel/inference_visitor.dart:6568:41)
#6      VariableDeclaration.accept (package:kernel/ast.dart:10065:43)
#7      TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3885:24)
#8      InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:339:20)
#9      InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:360:30)
#10     Block.accept (package:kernel/ast.dart:8525:43)
#11     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3885:24)
#12     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:2022:39)
#13     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1016:44)
#14     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:952:14)
#15     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:990:7)
#16     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:350:5)
#17     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2904:14)
#18     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2680:14)
#19     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:502:14)
#20     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#21     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:480:14)
<asynchronous suspension>
#22     Loader.buildBodies (package:front_end/src/fasta/loader.dart:277:9)
<asynchronous suspension>
#23     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:364:7)
<asynchronous suspension>
#24     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#25     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#26     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#27     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#28     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#29     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#30     SingleShotCompilerWrapper.compileInternal (file:///Users/srujzs/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#31     Compiler.compile.<anonymous closure> (file:///Users/srujzs/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#32     _processLoadRequest (file:///Users/srujzs/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:995:7)
#1      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:350:5)
#2      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2904:14)
#3      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2680:14)
#4      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:502:14)
#5      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#6      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:480:14)
<asynchronous suspension>
#7      Loader.buildBodies (package:front_end/src/fasta/loader.dart:277:9)
<asynchronous suspension>
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:364:7)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#13     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#14     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#15     SingleShotCompilerWrapper.compileInternal (file:///Users/srujzs/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#16     Compiler.compile.<anonymous closure> (file:///Users/srujzs/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#17     _processLoadRequest (file:///Users/srujzs/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>
```

</details>

Am I correct in assuming this applies to all instances where subtyping is involved for now as well?

cc @stefantsov @johnniwinther

**Comment by stefantsov** [comment]
That's an unfortunate bug with graduating ExtensionType from an internal implementation to the public API. I'm working on the fix [here](https://dart-review.googlesource.com/c/sdk/+/196120) and plan to land it soon.

**Comment by stefantsov** [comment]
One thing to note is that the subtype relation isn't fully implemented for ExtensionTypes. Currently, they are subtypes of themselves, of top types, and they are supertypes to bottom types. I'm currently working on extending the subtype relation for ExtensionTypes.
