### ISSUE TITLE
dart:socket issue on IOS

### ISSUE THREAD

**Issue by WizNeo6** [dart-lang/sdk#45824]
I have written a simple rawdatagram app to send data via UDP. 
The situation becomes weird when you pilot to the ip that is not listening to the port (that is the situation when some device disconnect while using the app)
The socket is working very well in android, as from the below code, the sendByte is always ~10, no error. However, when I build the app on IOS, the first few send is fine, but then I received an error and a `RawSocketEvent.closed` event. Then the socket is down.

```
flutter: send 10
flutter: send 10
flutter: send 0
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 0
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1134:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2293:15)
#2      UDPSample.sendData (package:udp_demo/fake_udp.dart:21:22)
#3      _TestPageState._sendData (package:udp_demo/test_page.dart:18:17)
flutter: RawSocketEvent.closed
flutter: send 0
```
After that the sendByte become 0, which means no byte is written and the socket is `died`

### What I have done or investigated:
I am not quite sure this issue is come from IOS or how dart implemented the socket. The problem is like the `sendto()` is blocking the socket to receive the message or even used up all the sendbuffer (but I have tried to increase the send buffer that doesn't make things different)

- I have tried to set the rawSocketOptions for IOS (SO_KEEPALIVE, SO_SNDBUF, SO_SNDTIMEO etc...) [ref](https://opensource.apple.com/source/xnu/xnu-4570.31.3/bsd/sys/socket.h.auto.html)
- I have looked into the code behind the dart runtime bins and found where the error may come from a `EWOULDBLOCK` error [ref](https://blog.weghos.com/flutter/engine/third_party/dart/runtime/bin/socket_base_linux.cc.html#134)

### The UI: 
``` dart
class TestPage extends StatefulWidget {
  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  void initState() {
    super.initState();
    UDPSample().initUDP();
  }

  _sendData(){
    UDPSample().sendData("10.10.100.237");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: OutlinedButton(onPressed: _sendData, child: Text("Send")),
      ),
    );
  }
}
```
### The UDP class: 
``` dart
import 'dart:convert';
import 'dart:io';

class UDPSample {
  // just a random port
  static const SEND_PORT = 3021;

  late RawDatagramSocket? _sendSocket;

  UDPSample._();

  static final UDPSample _udpContainer = UDPSample._();

  factory UDPSample() => _udpContainer;

  sendData(String ip) async {
    final message = {"data": 1};
    final codeUnits = json.encode(message).codeUnits;

    final sendByte =
        _sendSocket?.send(codeUnits, InternetAddress(ip), SEND_PORT);
    print("send $sendByte");
  }

  initUDP() async {
    _sendSocket = await RawDatagramSocket.bind(InternetAddress.anyIPv4, 0,
        reusePort: true);

    _sendSocket?.listen((event) async {
      print(event);
    });
  }

  closeSocket() {
    _sendSocket?.close();
  }
}
```

* Dart SDK Version (`2.13.0-211.6.beta (beta)`)
* Tested IOS Version (`14.4.2 && 13.3.1`)
```
[✓] Flutter (Channel beta, 2.2.0-10.1.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-HK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
[✓] VS Code (version 1.55.2)
```

**Comment by WizNeo6** [comment]
anyone can help check with this?

**Comment by mkulesh** [comment]
I have the same problem related to the stability of Socket on iOS. There is a regression between Flutter version 1.22.6 (Dart version 2.10.5) and Flutter version 2.2.1 (Dart version 2.13.1).

My app is a remote controller for Onkyo/Pioneer network players and AV receivers. The app communicates with players via TCP using so called "Integra Serial Communication Protocol". The Socket communication is implemented here: https://github.com/mkulesh/onpc/blob/onpc-flutter/lib/iscp/MessageChannel.dart

Up to Flutter version 1.22.6 the network communication was stable on all devices (iOS, Android, macOS). After upgrade to Flutter version 2.2.1, iOS app disconnects unexpectedly from the receiver, while Android, macOS, Windows and Linux versions still work stable. The problem observed on iPad 7 generation with iOS 14.x and 15.1. 

I experimented with the RawSocket as well:
```
class MessageChannel
{
  String _host = "";
  int _port = -1;
  MessageChannelState _state = MessageChannelState.IDLE;
  RawSocket _socket;
  final OnConnected _onConnected;

  MessageChannel(this._onConnected);

  String get getHostAndPort
  => _host + ":" + _port.toString();

  bool get isConnected
  => _state == MessageChannelState.RUNNING;

  void start(String host, int port)
  {
    _host = host;
    _port = port;
    if (_state != MessageChannelState.IDLE)
    {
      return;
    }
    _state = MessageChannelState.CONNECTING;

    RawSocket.connect(_host, _port, timeout: Duration(seconds: 10)).then((RawSocket sock)
    {
      _socket = sock;
      _socket.writeEventsEnabled = false;
      _socket.listen(_onEvent, onDone: () => _onDone(), cancelOnError: false);
      _state = MessageChannelState.RUNNING;
      print("Connected to " + getHostAndPort);
      _onConnected();
    }).catchError((dynamic e)
    {
      _state = MessageChannelState.IDLE;
      print("Disconnected from " + getHostAndPort + ": " + e.toString());
    });
  }

  void stop()
  {
    if (_socket != null)
    {
      _socket.close();
    }
  }

  void _onEvent(RawSocketEvent event)
  {
    switch (event) {
      case RawSocketEvent.read:
        if (_socket.available() > 0)
        {
          _onData(_socket.read());
        }
        break;
      case RawSocketEvent.write:
        print("RawSocketEvent.write");
        break;
      case RawSocketEvent.readClosed:
        print("RawSocketEvent.readClosed");
        break;
      case RawSocketEvent.closed:
        print("RawSocketEvent.closed");
        break;
      default:
        throw "Unexpected event $event";
    }
  }

  void _onDone()
  {
    _state = MessageChannelState.IDLE;
    _socket = null;
    print("Disconnected from " + getHostAndPort + ": done");
    _onConnected();
  }

  void _onData(Uint8List data)
  {
    String res = "";
    data.forEach((int f)
    {
        res += f.toRadixString(16);
        res += " ";
    });
    print("Data received: [" + res + "]");
  }
}
```
The problem is the same: RawSocketEvent.readClosed event is sometime called unexpectedly with the Flutter version 2.2.1 and later, but never called with Flutter 1.22.6.

Unfortunately, this problem is not reproducible using a 'synthetic' server written in Dart. The problem only appears when a real Onkyo device (in my case NS-6170 and NCP-302) are connected. The typical output in this case is:
```
[   +3 ms] Installing and launching... (completed in 11.6s)
[   +1 ms] Caching compiled dill
[  +37 ms] Connecting to service protocol: http://127.0.0.1:55318/
[  +28 ms] flutter: Connected to 192.168.1.81:60128
[ +101 ms] flutter: Data received: [49 53 43 50 0 0 0 10 0 0 0 2b 1 0 0 0 21 31 4e 4a 41 32 2d 68 74 74 70 3a 2f 2f 31 39 32 2e 31 36 38 2e 31 2e 38 31 2f 61 6c 62 75 6d 5f 61 72 74 2e 63 67 69 1a d a ]
[        ] flutter: RawSocketEvent.readClosed
``` 

The complete main.dart code is attached here: [main.dart.zip](https://github.com/dart-lang/sdk/files/7566388/main.dart.zip)

Any idea about such a strange behavior?

**Comment by whitmanlui** [comment]
I have the same problem too.

I am using RawDatagramSocket to send multicast on 239.255.255.250 with port 3702 And it return SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 2000 The problem is only with iOS physical Phone, iOS simulator and Android are fine My iPhone verions is iPhone SE and iOS version is 16.1.1

here's my code
```
try {
  List<int> dataToSend = codec.encode('some string here')
  udpSocket?.close();
  udpSocket = await RawDatagramSocket.bind(
    InternetAddress.anyIPv4,
    2000,
  );
  if (udpSocket != null) {
    udpSocket!.listen(
      (RawSocketEvent event) async {
        if (event == RawSocketEvent.read) {
          Datagram dg = udpSocket!.receive()!;
          String data = utf8.decode(dg.data);
          print(data);
        }
      },
    );

    udpSocket!.send(
      dataToSend,
      InternetAddress('239.255.255.250'),
      3702,
    );
  }
} catch (e) {
  print(e);
}
```

And I also enabled Multicast Networking entitlement [enter image description here](https://i.stack.imgur.com/aWS4g.png)

And here's my Info.plist
```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
</dict>
<key>NSBonjourServices</key>
<array>
  <string>_http._tcp.</string>
</array>
<key>NSLocalNetworkUsageDescription</key>
<string>Viper Cam will use this permission to discover the camera</string>
<key>UIBackgroundModes</key>
<array>
  <string>fetch</string>
  <string>remote-notification</string>
</array>
```

Flutter --version
```
Flutter 3.13.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e1e47221e8 (3 months ago) • 2023-08-22 21:43:18 -0700
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0
```

**Comment by wengxianxun** [comment]
我也有这个问题，在iOS17.3

**Comment by milomai** [comment]
The reason is RawDatagramSocket did not fire the iOS's local network alert, so your app can not gain the privilege to create connection. The workaround is to manually [trigger the local network alert](https://developer.apple.com/documentation/technotes/tn3179-understanding-local-network-privacy#Trigger-the-local-network-alert) using Swift or Objective-C.

Since iOS 14, because the [Local Network Privacy](https://developer.apple.com/documentation/technotes/tn3179-understanding-local-network-privacy), any network traffic not sent through a router requires explicit user permission. 
Normally, iOS should prompt the user with a dialog when the app first attempts a local network connection. However, when creating a socket in Dart, it fails directly without ask for user permission.

Also, you need to add [NSLocalNetworkUsageDescription](https://developer.apple.com/documentation/BundleResources/Information-Property-List/NSLocalNetworkUsageDescription) in your Info.plist to display text on the local network alert dialog. And request the [com.apple.developer.networking.multicast](https://developer.apple.com/documentation/BundleResources/Entitlements/com.apple.developer.networking.multicast) entitlement if you need to send/receive UDP boradcast/multicast.

**Comment by AbhayJadoun** [comment]
i am getting below logs anyone can help

#0 _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:821) 
#1 _RawSocket.startConnect (dart:io-patch/socket_patch.dart:2300) 
#2 RawSocket.startConnect (dart:io-patch/socket_patch.dart:41) 
#3 RawSecureSocket.startConnect (dart:io/secure_socket.dart:334) 
#4 SecureSocket.startConnect (dart:io/secure_socket.dart:85) 
#5 _ConnectionTarget.connect (dart:_http/http_impl.dart:2701) 
#6 _HttpClient._getConnection.connect (dart:_http/http_impl.dart:3223) 
#7 _HttpClient._getConnection (dart:_http/http_impl.dart:3228) 
#8 _HttpClient._openUrl (dart:_http/http_impl.dart:3051) 
#9 _HttpClient.openUrl (dart:_http/http_impl.dart:2872) 
#10 AWSHttpClientImpl._sendH1 (package:aws_common/src/http/aws_http_client_io.dart:69) 
#11 AWSHttpClientImpl.send.<anonymous closure> (package:aws_common/src/http/aws_http_client_io.dart:515) 
#12 new Future.<anonymous closure> (dart:async/future.dart:260) 
#13 _rootRun (dart:async/zone.dart:1517) 
#14 _CustomZone.run (dart:async/zone.dart:1422) 
#15 _CustomZone.runGuarded (dart:async/zone.dart:1321) 
#16 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1362) 
#17 _rootRun (dart:async/zone.dart:1525) 
#18 _CustomZone.run (dart:async/zone.dart:1422) 
#19 _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1345) 
#20 Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18) 
#21 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:423) 
#22 _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:454) 
#23 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193)
