### ISSUE TITLE
Consider supporting expression evaluation after failed hot reload

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#45846]
Currently, after hot reload fails with a compile-time error, expression evaluation is not able to access functions in a library with an error.

@aam wrote:

> Why failed reload results in inability to run expression evaluation?
> Program should still continue to run as expected.

> The test verifies that invalid reload request gets rejected and VM maintains it's state as if reload didn't happen(similar to how other invalid reload requests get rejected).
> VM should maintain frontend it uses for expression evaluation synchronized with its correct state which it has enough control over to do.

https://dart-review.googlesource.com/c/sdk/+/196984/3/runtime/observatory/tests/service/bad_reload_test.dart#85

If VM and CFE would support expression evaluation after failed hot reload, then the test `runtime/observatory/tests/service/bad_reload_test.dart` (and `runtime/observatory_2/tests/service_2/bad_reload_test.dart`) should be adjusted to use `invokeTest` instead of `invokeTestWithError`.

**Comment by aam** [comment]
Copying more details from other issue

"See also https://github.com/dart-lang/sdk/issues/49634#issuecomment-1218059213 for analysis of the current test expectations.

cc @jensjoha"

**Comment by jensjoha** [comment]
I *think* this is just a matter of the VM sending a "reject" when it fails --- and I think it should.

**Comment by aam** [comment]
> I _think_ this is just a matter of the VM sending a "reject" when it fails --- and I think it should.

I was experimenting with this on https://dart-review.googlesource.com/c/sdk/+/278664 but was getting some non-obvious errors from the compiler after `reject` call. You might have some insight into root cause for `Did not find dart:core when tried to initialize from component.` during 'reject' call:

```
╰─➤  python3 tools/test.py -n dartk-mac-release-arm64 service/bad_reload_test                                                                                                                   1 ↵

No build targets found.
Test configuration:
    dartk-mac-release-arm64(architecture: arm64, compiler: dartk, mode: release, runtime: vm, system: mac, gen-kernel-options: [--no-sound-null-safety], vm-options: [--no-sound-null-safety])
Suites tested: service

FAILED: dartk-vm release_arm64 service/bad_reload_test/service
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 06.000543s):
DART_CONFIGURATION=ReleaseARM64 xcodebuild/ReleaseARM64/dart --no-sound-null-safety -Dtest_runner.configuration=dartk-mac-release-arm64 --ignore-unrecognized-flags --packages=/Users/aam/p/d1/sdk/.dart_tool/package_config.json /Users/aam/p/d1/sdk/runtime/observatory/tests/service/bad_reload_test.dart

exit code:
255

stdout:
00:00 +0: bad_reload_test.dart (VM Service)

** Launching SERVICE_TEST_TESTEE=true xcodebuild/ReleaseARM64/dart --disable-dart-dev --write-service-info=file:///var/folders/pp/z7_v05dn3g71h9_3x3rlx8qr008dk8/T/dart_servicefcJoHO/service_info.json --profiler --no-sound-null-safety -Dtest_runner.configuration=dartk-mac-release-arm64 --ignore-unrecognized-flags --packages=/Users/aam/p/d1/sdk/.dart_tool/package_config.json --enable-vm-service:0 /Users/aam/p/d1/sdk/runtime/observatory/tests/service/bad_reload_test.dart

>testee>out> The Dart VM service is listening on http://127.0.0.1:51157/vHUwb8JSFnk=/

>testee>out> 

** Signaled to run test queries on http://127.0.0.1:51157/vHUwb8JSFnk= (VM Service)

Loading VM...

>testee>out> file:///Users/aam/p/d1/sdk/runtime/observatory/tests/service/

Done loading VM

Running bad_reload_test.dart [1/4]

Paused with PauseBreakpoint

Running bad_reload_test.dart [2/4]

Running bad_reload_test.dart [3/4]

>testee>out> Instance of 'Isolate'

>testee>out> spawned isolate running

Paused with PauseBreakpoint

Running bad_reload_test.dart [4/4]

>testee>err> kernel-service: Error: Unhandled exception:

>testee>err> Did not find dart:core when tried to initialize from component.

>testee>err> #0      _InitializationFromComponent.initialize (package:front_end/src/fasta/incremental_compiler.dart:2537:7)

>testee>err> #1      IncrementalCompiler._ensurePlatformAndInitialize (package:front_end/src/fasta/incremental_compiler.dart:1423:55)

>testee>err> #2      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:312:17)

>testee>err> <asynchronous suspension>

>testee>err> #3      IncrementalCompiler.reject (package:vm/incremental_compiler.dart:179:5)

>testee>err> <asynchronous suspension>

>testee>err> 
```

**Comment by aam** [comment]
"Massaged" https://dart-review.googlesource.com/c/sdk/+/278664 a little more so "reject" works(turns out it required `compileOptions.omitPlatform=false`), but that didn't fix expression evaluation error - after reject it still fails to find `test` method actually present in v1 version:
```
>testee>out> 0:00:00.017543: Loaded library file:///p/d/sdk/runtime/observatory/tests/service/bad_reload/v1/main.dart in 5ms.

>testee>out> 0:00:00.017631: Created debug library in 0ms.

>testee>out> 0:00:00.021324: Built debug library in 3ms.

>testee>out> 0:00:00.021499: Evaluated constants in 0ms.

>testee>out> 0:00:00.021700: Lowering transformations performed in 0ms.

resultOrError: DartError(org-dartlang-debug:synthetic_debug_expression:1:1: Error: Method not found: 'test'.
test()
^^^^)
```

@jensjoha any further thoughts or suggestions?

**Comment by jensjoha** [comment]
I think it's the last bullet-point in https://github.com/dart-lang/sdk/issues/49634#issuecomment-1218059213.

Fixing that seems to make it work (here I also added a similar test in `incremental_compiler_test.dart` because it's a lot faster to iterate when not having to compile the vm 😄):

```patch
diff --git a/pkg/vm/lib/incremental_compiler.dart b/pkg/vm/lib/incremental_compiler.dart
index 79a90443884..271447abe5d 100644
--- a/pkg/vm/lib/incremental_compiler.dart
+++ b/pkg/vm/lib/incremental_compiler.dart
@@ -29,29 +29,36 @@ class IncrementalCompiler {
   bool initialized = false;
   bool fullComponent = false;
   Uri? initializeFromDillUri;
-  List<Uri> _entryPoints;
+  List<Uri> _latestAcceptedEntryPoints;
+  List<Uri> _latestUsedEntryPoints;
   final bool forExpressionCompilationOnly;
 
-  List<Uri> get entryPoints => _entryPoints;
+  List<Uri> get entryPoints => _latestAcceptedEntryPoints;
   IncrementalKernelGenerator get generator => _generator;
   IncrementalCompilerResult? get lastKnownGoodResult => _lastKnownGood;
 
-  IncrementalCompiler(this._compilerOptions, this._entryPoints,
+  IncrementalCompiler(this._compilerOptions, this._latestAcceptedEntryPoints,
       {this.initializeFromDillUri, bool incrementalSerialization = true})
-      : forExpressionCompilationOnly = false {
+      : forExpressionCompilationOnly = false,
+        _latestUsedEntryPoints = _latestAcceptedEntryPoints {
     if (incrementalSerialization) {
       incrementalSerializer = new IncrementalSerializer();
     }
-    _generator = new IncrementalKernelGenerator(_compilerOptions, _entryPoints,
-        initializeFromDillUri, false, incrementalSerializer);
+    _generator = new IncrementalKernelGenerator(
+        _compilerOptions,
+        _latestAcceptedEntryPoints,
+        initializeFromDillUri,
+        false,
+        incrementalSerializer);
     _pendingDeltas = <IncrementalCompilerResult>[];
   }
 
-  IncrementalCompiler.forExpressionCompilationOnly(
-      Component component, this._compilerOptions, this._entryPoints)
-      : forExpressionCompilationOnly = true {
+  IncrementalCompiler.forExpressionCompilationOnly(Component component,
+      this._compilerOptions, this._latestAcceptedEntryPoints)
+      : forExpressionCompilationOnly = true,
+        _latestUsedEntryPoints = _latestAcceptedEntryPoints {
     _generator = new IncrementalKernelGenerator.forExpressionCompilationOnly(
-        _compilerOptions, _entryPoints, component);
+        _compilerOptions, _latestAcceptedEntryPoints, component);
     _pendingDeltas = <IncrementalCompilerResult>[];
   }
 
@@ -64,9 +71,9 @@ class IncrementalCompiler {
     final task = new TimelineTask();
     try {
       task.start("IncrementalCompiler.compile");
-      _entryPoints = entryPoints ?? _entryPoints;
+      _latestUsedEntryPoints = entryPoints ?? _latestAcceptedEntryPoints;
       IncrementalCompilerResult compilerResult = await _generator.computeDelta(
-          entryPoints: _entryPoints, fullComponent: fullComponent);
+          entryPoints: _latestUsedEntryPoints, fullComponent: fullComponent);
       initialized = true;
       fullComponent = false;
       _pendingDeltas.add(compilerResult);
@@ -150,6 +157,8 @@ class IncrementalCompiler {
       lastKnownGood.component.addMetadataRepository(repo);
     }
     _pendingDeltas.clear();
+
+    _latestAcceptedEntryPoints = _latestUsedEntryPoints;
   }
 
   /// This lets incremental compiler know that results of last [compile] call
@@ -174,9 +183,13 @@ class IncrementalCompiler {
     // loading from it below is basically nonsense, it will just start over).
     _lastKnownGood?.component.relink();
 
-    _generator = new IncrementalKernelGenerator.fromComponent(_compilerOptions,
-        _entryPoints, _lastKnownGood?.component, false, incrementalSerializer);
-    await _generator.computeDelta(entryPoints: _entryPoints);
+    _generator = new IncrementalKernelGenerator.fromComponent(
+        _compilerOptions,
+        _latestAcceptedEntryPoints,
+        _lastKnownGood?.component,
+        false,
+        incrementalSerializer);
+    await _generator.computeDelta(entryPoints: _latestAcceptedEntryPoints);
   }
 
   /// This tells incremental compiler that it needs rescan [uri] file during
diff --git a/pkg/vm/test/incremental_compiler_test.dart b/pkg/vm/test/incremental_compiler_test.dart
index 45052cd3ecf..0a6757fe8e4 100644
--- a/pkg/vm/test/incremental_compiler_test.dart
+++ b/pkg/vm/test/incremental_compiler_test.dart
@@ -1240,6 +1240,85 @@ main() {
         expect(lrc.librariesReferenced, equals(<Library>{barLib}));
       }
     });
+
+    test('compile, recompile with new entry, reject, expression compilation',
+        () async {
+      var v1Uri = Uri.file('${mytest.path}/v1.dart');
+      new File(v1Uri.toFilePath()).writeAsStringSync("""import 'dart:isolate';
+          test() => 'apple';
+          main() {
+            RawReceivePort keepAlive = new RawReceivePort();
+            print('spawned isolate running');
+          }
+          """);
+
+      var v2Uri = Uri.file('${mytest.path}/v2.dart');
+      new File(v2Uri.toFilePath()).writeAsStringSync("""import 'dart:isolate';
+          import 'library_isnt_here_man';
+
+          test() => 'apple';
+
+          main() {
+            RawReceivePort keepAlive = new RawReceivePort();
+            print('spawned isolate running');
+          }
+          """);
+
+      CompilerOptions optionsModified = getFreshOptions()
+        ..onDiagnostic = (DiagnosticMessage message) {
+          // sometimes expected on this one.
+          print(message.ansiFormatted);
+        };
+      IncrementalCompiler compiler =
+          new IncrementalCompiler(optionsModified, [v1Uri]);
+
+      print("Compiling v1 uri (should be ok)");
+      await compiler.compile(entryPoints: [v1Uri]);
+
+      print("Accepting.");
+      compiler.accept();
+      {
+        print("Compiling expression.");
+        Procedure? procedure = await compiler.compileExpression(
+            'test()',
+            <String>[],
+            <String>[],
+            <String>[],
+            <String>[],
+            <String>[],
+            v1Uri.toString(),
+            null,
+            null,
+            false);
+        expect(procedure, isNotNull);
+        ReturnStatement returnStmt =
+            procedure!.function.body as ReturnStatement;
+        expect(returnStmt.expression, isA<StaticInvocation>());
+      }
+
+      print("Compiling v2 uri (with error)");
+      await compiler.compile(entryPoints: [v2Uri]);
+      print("Rejecting.");
+      await compiler.reject();
+      {
+        print("Compiling expression.");
+        Procedure? procedure = await compiler.compileExpression(
+            'test()',
+            <String>[],
+            <String>[],
+            <String>[],
+            <String>[],
+            <String>[],
+            v1Uri.toString(),
+            null,
+            null,
+            false);
+        expect(procedure, isNotNull);
+        ReturnStatement returnStmt =
+            procedure!.function.body as ReturnStatement;
+        expect(returnStmt.expression, isA<StaticInvocation>());
+      }
+    });
   });
 
   group('expression evaluation', () {
```

Feel free to use as you see fit.

**Comment by aam** [comment]
> I think it's the last bullet-point in [#49634 (comment)](https://github.com/dart-lang/sdk/issues/49634#issuecomment-1218059213).
> 
> Fixing that seems to make it work

Aha, makes sense, thanks!
