### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by per-activote** [dart-lang/sdk#45875]
OS: Windows 10 Home 64-bit (10.0, Build 19042)
Dart SDK: 2.13.0-211.13.beta

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Compiling lib/main-app-test.dart for the Web...
Target dart2js failed: Exception: ../activotelib/lib/src/data/DataObject/ListFieldDefinition.dart:111:8:
Internal Error: The compiler crashed when compiling this element.
  void debug({
       ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.13.0-211.13.beta), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'classNode' was called on null.
Receiver: null
Tried calling: classNode
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      StaticTypeVisitor.visitForInStatement (package:compiler/src/ir/static_type.dart:1716:33)
#2      ForInStatement.accept (package:kernel/ast.dart:9058:43)
#3      StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:80:18)
#4      StaticTypeVisitor.visitBlock (package:compiler/src/ir/static_type.dart:1452:22)
#5      Block.accept (package:kernel/ast.dart:8518:43)
#6      StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:80:18)
#7      StaticTypeVisitor._handleConditional (package:compiler/src/ir/static_type.dart:1372:33)
#8      StaticTypeVisitor.visitIfStatement (package:compiler/src/ir/static_type.dart:1781:12)
#9      IfStatement.accept (package:kernel/ast.dart:9422:43)
#10     StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:80:18)
#11     StaticTypeVisitor.visitBlock (package:compiler/src/ir/static_type.dart:1452:22)
#12     Block.accept (package:kernel/ast.dart:8518:43)
#13     StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:80:18)
#14     StaticTypeVisitor.visitProcedure (package:compiler/src/ir/static_type.dart:1876:5)
#15     Procedure.accept (package:kernel/ast.dart:2741:40)
#16     KernelToElementMapImpl.computeWorldImpact (package:compiler/src/kernel/element_map_impl.dart:1440:12)
#17     KernelWorkItem.run.<anonymous closure>.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:395:47)
#18     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#19     KernelWorkItem.run.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:394:28)
#20     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#21     KernelWorkItem.run (package:compiler/src/kernel/kernel_strategy.dart:369:26)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:530:70)
#23     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#24     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:530:32)
#25     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#26     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:528:28)    
#27     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:819:15)
#28     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:526:18)
#29     ResolutionEnqueuer._forEach (package:compiler/src/enqueue.dart:450:12)
#30     ResolutionEnqueuer.forEach (package:compiler/src/enqueue.dart:466:5)
#31     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:522:16)
#32     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#33     Compiler.emptyQueue (package:compiler/src/compiler.dart:521:14)
#34     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:547:7)
#35     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#36     Compiler.processQueue (package:compiler/src/compiler.dart:540:14)
#37     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:386:5)
#38     Compiler.compileFromKernel.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:471:17)
#39     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#40     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:470:44)
#41     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#42     Compiler.compileFromKernel (package:compiler/src/compiler.dart:469:14)
#43     Compiler.runInternal (package:compiler/src/compiler.dart:304:13)
<asynchronous suspension>

Compiling lib/main-app-test.dart for the Web...                    11.4s
Exception: Failed to compile application for the Web.

The specific code that it breaks on is:

  @override
  void debug({
    required DataObject object,
    String? header,
    required String fieldName,
    int? indent,
  }) {
    final dynamic data = retrieve<dynamic>(object, fieldName);

    if (data == null) {
      showDebugNull(header);
    } else {
      if ((data as List<dynamic>).isEmpty) {
        logDebugInfo(
          '$header <0>[',
        );
      } else {
        logDebugInfo(
          '$header <${data.first.runtimeType}, ${data.length}>[',
        );
      }

      for (final dynamic e in data) {
        e.debug(indent: indent! + 4, showType: false, enclose: true);
      }
    }

    logDebugInfo(
      '${' ' * indent!}]',
    );
  }

Where ListFieldDefinition is a templated subclass of FieldDefinition.

**Comment by per-activote** [comment]
I've traced it back to specifically the line:
 if ((data as List<dynamic>).isEmpty) 

Changing it to:
  if (data is List and data.isEmpty)

will resolve the compiler crash
