### ISSUE TITLE
dart2js: assertion failure on inlining constructor body

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#45943]
I can currently only repro this on a 'modular dart2js' build of an old version of flutter gallery

```Internal Error: Only 3 of 4 arguments have been read from: [HCreate(j:class(_InspectorOverlayLayer), [_InspectorOverlayLayer]), parameter overlayRect, parameter selection, HCreateBox()] passed to j:constructor_body(_InspectorOverlayLayer.).
  _InspectorOverlayLayer({
  ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Unhandled exception:
Assertion failure: Only 3 of 4 arguments have been read from: [HCreate(j:class(_InspectorOverlayLayer), [_InspectorOverlayLayer]), parameter overlayRect, parameter selection, HCreateBox()] passed to j:constructor_body(_InspectorOverlayLayer.).
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      KernelSsaGraphBuilder._setupStateForInlining (package:compiler/src/ssa/builder_kernel.dart:6200:9)
#2      KernelSsaGraphBuilder._enterInlinedMethod (package:compiler/src/ssa/builder_kernel.dart:6096:5)
#3      KernelSsaGraphBuilder._tryInlineMethod.doInlining (package:compiler/src/ssa/builder_kernel.dart:5922:7)
#4      KernelSsaGraphBuilder._tryInlineMethod (package:compiler/src/ssa/builder_kernel.dart:5935:17)
#5      KernelSsaGraphBuilder._buildConstructor.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:885:13)
#6      KernelSsaGraphBuilder._inlinedFrom.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:925:21)
#7      CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:819:15)
#8      KernelSsaGraphBuilder._inlinedFrom (package:compiler/src/ssa/builder_kernel.dart:923:14)
#9      KernelSsaGraphBuilder._buildConstructor (package:compiler/src/ssa/builder_kernel.dart:842:7)
#10     KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:489:11)
#11     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:819:15)
```

**Comment by rakudrama** [comment]
Fixed via 90127334ea4aab5267135b959e361229dfac6bc9
