### ISSUE TITLE
tools/minidump.py crashes

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#46029]
`tools/minidump.py` is crashing on Windows bots:

```
Archiving coredumps for crash (if possible):
----> Crash(vm/dart_2/unboxed_param_test: 7964 binary.release_x64_dart_precompiled_runtime.exe, binary.release_x64_kernel-service.dart.snapshot)
----> Crash(ffi_2/vmspecific_object_gc_test: 7792 binary.release_x64_dart_precompiled_runtime.exe, binary.release_x64_kernel-service.dart.snapshot)
ERROR: Failed to archive crashes: 'dict' object has no attribute 'iteritems'
Traceback (most recent call last):
  File "tools/test.py", line 57, in <module>
    sys.exit(Main())
[...]
  File "C:\b\s\w\ir\tools\minidump.py", line 108, in <module>
    Enum(ctypes.c_uint32, MINIDUMP_STREAM_TYPE)),
  File "C:\b\s\w\ir\tools\minidump.py", line 17, in __init__
    self.value2name = {v: k for k, v in name2value.iteritems()}
AttributeError: 'dict' object has no attribute 'iteritems'
```
[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8847007902626339664/+/u/vm_tests_shard_1/task_stdout_stderr:_vm_tests_shard_1)

This is due to the python2 `dict.iteritems` method being removed in python3.

**Comment by cskau-g** [comment]
I have made https://dart-review.googlesource.com/c/sdk/+/200184 to fix the issue.
