### ISSUE TITLE
NoSuchMethodError: The getter 'nullabilitySuffix' was called on null.

### ISSUE THREAD

**Issue by UnluckyY1** [dart-lang/sdk#46058]
Analyzing project...
[----------------------------------------------------------------------------------------------------------------------------------------------------------]No analysis issues found.

Generating migration suggestions...
[--------------------------------------------------------------------------------------------------------------------------/                               ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.12.3) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

```
NoSuchMethodError: The getter 'nullabilitySuffix' was called on null.
Receiver: null
Tried calling: nullabilitySuffix at offset 0 in C:\Users\Siyou Mobile\Desktop\chat b2s2c\flutter_images_slider-master\lib\helpers.dart (class Helpers {static remainder<T>(T input, T source) {if (input is double && source is double) {final double result = input % source; return result < 0 ? source + result : result;} else if (input is int && source is int) {final int result = input % source; return result < 0 ? source + result : result;} else {return 0;}} static T 
getRealIndex<T>(T position, T base, T length) {if (position is double && base is double && length is double) {final double offset = position - base; return 
remainder(offset, length);} else if (position is int && base is int && length is int) {final int offset = position - base; return remainder(offset, length);} else {return 0 as T;}}})

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      SubtypeHelper.isSubtypeOf (package:analyzer/src/dart/element/subtype.dart:51:29)
#2      TypeSystemImpl.isSubtypeOf2 (package:analyzer/src/dart/element/type_system.dart:1162:27)
#3      TypeSystemImpl.isSubtypeOf (package:analyzer/src/dart/element/type_system.dart:1158:12)
#4      TypeSystemImpl._refineNumericInvocationContextNullSafe (package:analyzer/src/dart/element/type_system.dart:1669:11)
#5      TypeSystemImpl.refineNumericInvocationContext (package:analyzer/src/dart/element/type_system.dart:1402:14)
#6      ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:862:24)
#7      InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:326:15)
#8      InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:384:7)        
#9      InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:345:7)
#10     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:239:5)
#11     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:811:24)
#12     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:514:16)
#13     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:93:7)
#14     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:394:31)
#15     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#16     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1706:10)
#17     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#18     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8621:18)
#19     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#20     UnifyingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:3410:51)
#21     ResolverVisitor.visitReturnStatement (package:analyzer/src/generated/resolver.dart:1846:11)
#22     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8617:49)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#24     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#25     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#26     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#27     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#28     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#29     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#30     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2970:7)
#31     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:1561:7)
#32     ResolverVisitorForMigration.visitIfStatement (package:analyzer/src/generated/resolver.dart:2382:13)
#33     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5705:49)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#35     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#36     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#37     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#38     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#39     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#40     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#41     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#42     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1042:13)
#43     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#44     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3146:55)
#45     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2489:13)
#46     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:957:13)
#47     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#48     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7042:12)
#49     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#50     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3351:55)
#51     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:2926:11)
#52     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:2919:7)
#53     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:1666:11)
#54     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#55     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#56     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:2550:18)
#57     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2531:7)
#58     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:1015:13)
#59     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#60     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:1091:23)
#61     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#62     FixBuilder.visitAll.<anonymous closure> (package:nnbd_migration/src/fix_builder.dart:212:14)
#63     _rootRun (dart:async/zone.dart:1354:13)
#64     _CustomZone.run (dart:async/zone.dart:1258:19)
#65     _runZoned (dart:async/zone.dart:1788:10)
#66     runZoned (dart:async/zone.dart:1710:10)
#67     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#68     FixBuilder.visitAll (package:nnbd_migration/src/fix_builder.dart:209:35)
#69     NullabilityMigrationImpl.finalizeInput (package:nnbd_migration/src/nullability_migration_impl.dart:169:18)
#70     NonNullableFix.finalizeUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:115:15)
#71     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1159:21)
#72     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1156:28)
#73     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#74     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1156:5)
<asynchronous suspension>
#75     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#76     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#77     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#78     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#79     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#80     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by scheglov** [comment]
I believe this was fixed during migrating analyzer itself for null safety.
