### ISSUE TITLE
Spread collection tests fail with new invocation nodes

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#46076]
A few tests for spread collections started failing with new invocation nodes:

```
/===============================================================================================================\
| co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A01_t05 broke (Pass -> RuntimeError, expected Pass) |
\===============================================================================================================/

--- Command "vm" (took 461ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/co19_2/src/LanguageFeatures/Spread-collections/StaticSemantic_A01_t05.dart

exit code:
255

stderr:
Unhandled exception:
Expect.throws() fails
#0      _fail (file:///b/s/w/ir/cache/builder/sdk/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.throws (file:///b/s/w/ir/cache/builder/sdk/tests/co19_2/src/Utils/expect_common.dart:289:5)
#2      main (file:///b/s/w/ir/cache/builder/sdk/tests/co19_2/src/LanguageFeatures/Spread-collections/StaticSemantic_A01_t05.dart:33:10)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n dartk-linux-release-x64 co19_2/LanguageFeatures/Spread-collections/StaticSemantic_A01_t05


/==============================================================================================================\
| co19_2/LanguageFeatures/Spread-collections/TypeInference_A03_t01 broke (Pass -> RuntimeError, expected Pass) |
\==============================================================================================================/

--- Command "vm" (took 615ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LanguageFeatures/Spread-collections/TypeInference_A03_t01.dart

exit code:
255

stderr:
Unhandled exception:
Expect.throws() fails
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.throws (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:289:5)
#2      main (file:///b/s/w/ir/tests/co19_2/src/LanguageFeatures/Spread-collections/TypeInference_A03_t01.dart:61:10)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n dartk-linux-release-x64 co19_2/LanguageFeatures/Spread-collections/TypeInference_A03_t01


/==============================================================================================\
| language_2/spread_collections/runtime_error_test broke (Pass -> RuntimeError, expected Pass) |
\==============================================================================================/

--- Command "vm" (took 578ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/language_2/spread_collections/runtime_error_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.throws(TypeError) fails: Did not throw
#0      Expect._fail (package:expect/expect.dart:731:5)
#1      Expect.throws (package:expect/expect.dart:633:5)
#2      Expect.throwsTypeError (package:expect/expect.dart:670:12)
#3      main (file:///b/s/w/ir/tests/language_2/spread_collections/runtime_error_test.dart:28:10)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n dartk-linux-release-x64 language_2/spread_collections/runtime_error_test
```

Can be reproduced if `supportsNewMethodInvocationEncoding` is changed to return `true` in `pkg/vm/lib/target/vm.dart`.

**Comment by alexmarkov** [comment]
The failures started since https://dart-review.googlesource.com/c/sdk/+/200425.
/cc @askeksa-google

**Comment by alexmarkov** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/200704.
