### ISSUE TITLE
[Dart migration] The method 'nonNullAssert_end' was called on null.

### ISSUE THREAD

**Issue by Coronon** [dart-lang/sdk#46108]
While running the migration tool (for null-safety) I am encountering numerous errors. After the tool refused to help me because of a non null-safe dependency (an import of my own package that Im trying to migrate with it ^^) I now face a funny fatal exception, a method call on `null` <- In the null-safety migration tool O.o

```
NoSuchMethodError: The method 'nonNullAssert_end' was called on null.
Receiver: null
Tried calling: nonNullAssert_end(Instance of 'NullLiteralImpl') at offset 681 in R:\SOMEPATH\lib\redux\models\login\login_state.dart (null)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      MigrationResolutionHooksImpl._createNullCheckChange (package:nnbd_migration/src/fix_builder.dart:638:19)
#2      MigrationResolutionHooksImpl._createExpressionChange (package:nnbd_migration/src/fix_builder.dart:624:14)
#3      MigrationResolutionHooksImpl._addCastOrNullCheck (package:nnbd_migration/src/fix_builder.dart:590:18)
#4      MigrationResolutionHooksImpl._modifyRValueType (package:nnbd_migration/src/fix_builder.dart:726:14)
#5      MigrationResolutionHooksImpl.modifyExpressionType.<anonymous closure> (package:nnbd_migration/src/fix_builder.dart:540:16)
#6      MigrationResolutionHooksImpl._wrapExceptions (package:nnbd_migration/src/fix_builder.dart:826:21)
#7      MigrationResolutionHooksImpl.modifyExpressionType (package:nnbd_migration/src/fix_builder.dart:517:7)
#8      StaticTypeAnalyzer.recordStaticType (package:analyzer/src/generated/static_type_analyzer.dart:57:20)
#9      StaticTypeAnalyzer.visitNullLiteral (package:analyzer/src/generated/static_type_analyzer.dart:232:5)
#10     NullLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7708:50)
#11     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1882:10)
#12     UnifyingAstVisitor.visitNullLiteral (package:analyzer/dart/ast/visitor.dart:3382:44)
#13     ResolverVisitor.visitNullLiteral (package:analyzer/src/generated/resolver.dart:1888:11)
#14     NullLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:7708:50)
#15     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7289:17)
#16     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1880:10)
#17     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3368:52)
#18     ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:1870:11)
#19     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7284:50)
#20     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:975:20)
#21     AnnotationResolver._constructorInvocation (package:analyzer/src/dart/resolver/annotation_resolver.dart:156:17)
#22     AnnotationResolver._classConstructorInvocation (package:analyzer/src/dart/resolver/annotation_resolver.dart:67:5)
#23     AnnotationResolver._resolve (package:analyzer/src/dart/resolver/annotation_resolver.dart:334:9)
#24     AnnotationResolver.resolve (package:analyzer/src/dart/resolver/annotation_resolver.dart:39:5)
#25     ResolverVisitor.visitAnnotation (package:analyzer/src/generated/resolver.dart:899:30)
#26     AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:302:50)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
#28     AnnotatedNodeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:145:17)
#29     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3940:11)
#30     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1880:10)
#31     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:3248:54)
#32     ResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:1470:13)
#33     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3936:50)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
#35     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:2694:18)
#36     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2675:7)
#37     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:1108:13)
#38     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1514:50)
#39     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:1184:23)
#40     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#41     FixBuilder.visitAll (package:nnbd_migration/src/fix_builder.dart:210:12)
#42     NullabilityMigrationImpl.finalizeInput (package:nnbd_migration/src/nullability_migration_impl.dart:169:18)
#43     NonNullableFix.finalizeUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:115:15)
#44     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1157:21)
#45     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1154:28)
#46     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
#47     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1154:5)
<asynchronous suspension>
#48     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:747:24)
<asynchronous suspension>
#49     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:7)
<asynchronous suspension>
#50     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#51     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#52     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#53     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

I am running on Windows with the following versions:
```
Dart SDK version: 2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "windows_x64"

Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision b22742018b (8 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0
```

The file in question:
```dart
import 'package:json_annotation/json_annotation.dart';

import 'package:goapp/redux/models/login/login.dart';

part 'login_state.g.dart';

@JsonSerializable(explicitToJson: true)
class LoginState {
  DictLoginState loginDict;

  LoginState({
    this.loginDict,
  });

  factory LoginState.initial() => LoginState(
        loginDict: DictLoginState.initial(),
      );

  factory LoginState.fromJson(Map<String, dynamic> json) =>
      _$LoginStateFromJson(json);
  Map<String, dynamic> toJson() => _$LoginStateToJson(this);
}

@JsonSerializable(explicitToJson: true)
class DictLoginState {
  static getNull([_]) => null;

  @JsonKey(
    defaultValue: null,
    toJson: getNull,
    fromJson: getNull,
  )
  dynamic error;
  bool loading;
  Login data;

  DictLoginState({
    this.error,
    this.loading,
    this.data,
  });

  factory DictLoginState.initial() => DictLoginState(
        error: null,
        loading: false,
        data: Login.initial(),
      );

  factory DictLoginState.fromJson(Map<String, dynamic> json) =>
      _$DictLoginStateFromJson(json);
  Map<String, dynamic> toJson() => _$DictLoginStateToJson(this);
}
```
The problem seems to have something to do with the `@JsonKey(...` as it disappeares if I remove it. Specifically with `
defaultValue: null`.

The dart/flutter ecosystem is awesome and I am extremly grateful for all the work that went into it :)

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
