### ISSUE TITLE
Analyzer crashes on the `super.new` sduper constructor reference when runs in its default mode

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#46198]
Dart SDK version: 2.14.0-152.0.dev (dev) (Tue May 25 15:03:31 2021 -0700) on "windows_x64"

Analyzer crashes on the `super.new` super constructor reference when runs in its default mode.

If I add `--enable-experiment=constructor-tearoffs` option it crashes in the sane manner.

Here is a sample code example:
``` dart
class C {
  C.new();
}

class D extends C {
  D() : super.new();
}

void main() {}
```
Sample output is:
```
$> dartanalyzer test.dart
Unhandled exception:
Null check operator used on a null value
#0      AstBuilder.buildInitializerTargetExpressionRecovery (package:analyzer/src/fasta/ast_builder.dart:489:56)
#1      AstBuilder.buildInitializer (package:analyzer/src/fasta/ast_builder.dart:417:14)
#2      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:1712:25)
#3      Parser.parseInitializers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3046:14)
#4      Parser.parseInitializersOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2983:14)
#5      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3891:13)
#6      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3723:15)
#7      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3382:15)
#8      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1999:13)
#9      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1957:14)
#10     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
#11     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
#12     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#13     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:195:32)
#14     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:191:12)
#15     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:597:23)
#16     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:403:12)
#17     FileState._getUnlinkedBytes (package:analyzer/src/dart/analysis/file_state.dart:542:16)
#18     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:447:17)
#19     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:858:12)
#20     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:331:45)
#21     Driver.start (package:analyzer_cli/src/driver.dart:112:28)
#22     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analyzer_cli/bin/analyzer.dart:13:17)
#23     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
Please see [proposal](https://github.com/dart-lang/language/blob/master/working/0216%20-%20constructor%20tearoffs/proposal.md#unnamed-constructor-tear-off) for more details about the `new` syntax for unnamed constructors.

**Comment by srawlins** [comment]
Fixed at some point.
