### ISSUE TITLE
Dart migrate exception

### ISSUE THREAD

**Issue by Rodsevich** [dart-lang/sdk#46190]
While trying to migrate this [open source package](https://gitlab.com/Rodsevich/mustachex) the following output outcomes:
```
$ dart migrate
Migrating /home/nico/src/mustachex

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\]No analysis issues found.

Generating migration suggestions...
[---------------------------------------------------|                                                                                                                                                             ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.13.1) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

Bad state: Unrelated types: abstract class Iterable<E> and abstract class List<E> implements EfficientLengthIterable<E> at offset 16632 in /home/nico/src/mustachex/lib/src/mustachex_processor.dart (close.remove(e))

#0      DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:67:10)
#1      DecoratedClassHierarchy.asInstanceOf (package:nnbd_migration/src/decorated_class_hierarchy.dart:38:18)
#2      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:259:16)
#3      EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1284:20)
#4      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7091:50)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#6      EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:441:22)
#7      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:951:50)
#8      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#9      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#10     EdgeBuilder.visitExpressionFunctionBody (package:nnbd_migration/src/edge_builder.dart:793:5)
#11     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3458:15)
#12     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#13     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:937:25)
#14     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#15     EdgeBuilder.visitFunctionExpression (package:nnbd_migration/src/edge_builder.dart:935:28)
#16     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4919:50)
#17     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#18     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#19     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2937:7)
#20     EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1296:24)
#21     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7091:50)
#22     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#23     EdgeBuilder._checkExpressionNotNull (package:nnbd_migration/src/edge_builder.dart:1980:20)
#24     EdgeBuilder._handleTarget (package:nnbd_migration/src/edge_builder.dart:3059:14)
#25     EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1268:22)
#26     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7091:50)
#27     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#28     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#29     EdgeBuilder.visitVariableDeclarationList (package:nnbd_migration/src/edge_builder.dart:1924:11)
#30     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10507:15)
#31     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#32     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#33     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#34     GeneralizingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:593:7)
#35     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10556:15)
#36     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#37     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#38     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#39     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#40     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1065:50)
#41     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#42     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#43     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:326:46)
#44     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#45     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1020:50)
#46     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#47     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2490:7)
#48     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#49     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6942:50)
#50     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#51     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#52     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#53     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#54     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1514:50)
#55     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#56     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#57     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#58     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#59     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#60     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#61     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#62     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#63     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#64     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:19)
#65     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1150:28)
#66     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
<asynchronous suspension>
#67     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1150:5)
<asynchronous suspension>
#68     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:747:24)
<asynchronous suspension>
#69     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:7)
<asynchronous suspension>
#70     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#71     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#72     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#73     main (file:///tmp/tmpqgqAs3/dart-2.13.1/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

I overcome this by replacing the line that produces the exception:
```
List<String> _processParentMaps(String source) {
    var open = _beginToken.allMatches(source).map((m) => m.group(1)),
        close = _endToken.allMatches(source).map((m) => m.group(1)).toList();
    var ret = open.where((e) => !close.remove(e)).toList();
    return ret;
}
```
```
List<String> _processParentMaps(String source) {
    var open = _beginToken.allMatches(source).map((m) => m.group(1)),
        close = _endToken.allMatches(source).map((m) => m.group(1)).toList();
    var ret = [];
    // open.where((e) => !close.remove(e)).toList();
    return ret;
}
```

**Comment by Rodsevich** [comment]
It seems out that the missing .toList() of the open var could have saved me from the error. I will leave the case open in just case it's useful for you.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
