### ISSUE TITLE
[analyzer] Handle type in TypeArgumentList is Null

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#46201]
Adding the following two lines in `sdk/lib/ffi/ffi.dart`:
```
@FfiNative<IntPtr Function(Handle, Handle)>('_ffi_resolver')
external int _ffi_resolver(String library, String function_name);
```

I get:
```
[53/54] ACTION //utils/dartanalyzer:generate_summary_strong(//build/toolchain/linux:clang_x64)
...
type 'Null' is not a subtype of type 'ParameterElementImpl' in type cast
#0      AstBinaryWriter._storeFormalParameter (package:analyzer/src/summary2/ast_binary_writer.dart:780:40)
#1      AstBinaryWriter._storeNormalFormalParameter (package:analyzer/src/summary2/ast_binary_writer.dart:818:5)
#2      AstBinaryWriter.visitSimpleFormalParameter (package:analyzer/src/summary2/ast_binary_writer.dart:613:5)
...
#5      AstBinaryWriter.visitFormalParameterList (package:analyzer/src/summary2/ast_binary_writer.dart:276:5)
...
#8      AstBinaryWriter.visitGenericFunctionType (package:analyzer/src/summary2/ast_binary_writer.dart:333:5)
...
#11     AstBinaryWriter.visitTypeArgumentList (package:analyzer/src/summary2/ast_binary_writer.dart:698:5)
...
#15     AstBinaryWriter.visitAnnotation (package:analyzer/src/summary2/ast_binary_writer.dart:39:5)
...
#26     _Builder.build (package:analyzer/dart/sdk/build_sdk_summary.dart:109:22)
#27     buildSdkSummary (package:analyzer/dart/sdk/build_sdk_summary.dart:74:5)
...
```

The node it's dying on is `Handle`.

**Comment by cskau-g** [comment]
@scheglov, @bwilkerson Do you know if this is a bug, or if I'm just doing something crazy here that is expected to fail?

**Comment by cskau-g** [comment]
I've bisect'd my way back to e021d0c1714ccd22308e251a3978ef9880a128a1 which introduced this issue.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/201940
