### ISSUE TITLE
should tear-offs remember where they were created to provide better stack traces?

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#46216]
(this issue was [brought up](https://twitter.com/remi_rousselet/status/1399723193791811585) by @rrousselGit on Twitter)

Using explicit closures sometimes provides better stack traces than using tear-offs because with explicit closures you usually get the location which created the closure included into the stack trace, while with implicit tear-off you don't get the same information. 

Compare: 

```dart
import 'dart:async';

Future<void> foo({required bool useClosure}) async {
  final controller = StreamController<int>();
  final completer = Completer<int>();
  controller.stream.listen(
    (_) {},
    onDone: useClosure ? () => completer.complete()
                       : completer.complete,
  );
  controller.close();
  await completer.future;
}

void main(List<String> args) async {
  await foo(useClosure: args.contains('use-closure'));
}
```

```console
$ dart /tmp/test.dart 
Unhandled exception:
type 'Null' is not a subtype of type 'FutureOr<int>'
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:46:41)
#1      _RootZone.runGuarded (dart:async/zone.dart:1534:10)
#2      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
#3      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
#4      _DelayedDone.perform (dart:async/stream_impl.dart:610:14)
#5      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
$ dart /tmp/test.dart use-closure
Unhandled exception:
type 'Null' is not a subtype of type 'FutureOr<int>'
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:46:41)
#1      foo.<anonymous closure> (file:///tmp/test.dart:8:42)
#2      _RootZone.runGuarded (dart:async/zone.dart:1534:10)
#3      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
#4      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
#5      _DelayedDone.perform (dart:async/stream_impl.dart:610:14)
#6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

It is much easier to track the issue down in the second case - when closure is used. 

We could consider changing tear-off implementation to provide more informative stack traces - by attaching the location of the tear-off operation to the object produced by the tear-off at least for the case when receiver is non-`dynamic` (so it is statically known that we are performing a closurization). 

WDTY @leafpetersen @lrhn @eernstg?

**Comment by eernstg** [comment]
It is tempting to help developers in this particular way, but there is a conceptual discrepancy and a performance aspect:

Two instance method tearoffs are equal according to `==` if they are the same method (that is: same method name) torn off of the same receiver (according to `identical`), and it is unspecified whether those tearoffs are `identical`. (By the way, generic method instantiation is a different thing, but the rules are similar for them.)

This means that it is currently allowed for an implementation to cache and reuse an instance method tearoff whenever these conditions are satisfied, and that might be a significant optimization.

Maybe this kind of "debugging optimized" behaviors should be controlled by a compile-time option?

**Comment by lrhn** [comment]
The issue would be with non-instance method tear-offs, where we currently promise canonicalization. You can't *really* remember the tear-off point then, when tear-offs from different places are required to be the same object.
(You can, if you fiddle with `identical` and hide that you really have different objects, but you risk confusing everybody with that).

For instance methods, where each tear-off creates a new object, and all we care about is equality, I see no problem with platforms storing extra information, and using that when generating stack traces (perhaps adding an extra entry on the stack when calling the method, and recognizing it when tracing the stack). As Erik mentions, that can prevent other optimizations, but that's all implementation details, not something the language cares about.

**Comment by rakudrama** [comment]
I don't think this is a VM-only issue. Web apps are developed with DDC, and deployed web apps compiled with dart2js are debugged indirectly via captured stack traces that are sent back to the server. Anything we can do to improve stack traces in these cases is valuable.

If I understand the example stack trace, it does not contain the location of the code that _created_ the closure, but the location of _the call site_ within the closure.
To provide any record of the tear-off, the tear-off would also have to call the method and then return, rather than the faster tail-call into the method. Otherwise there is no stack frame to indicate the method was called from a tear-off.
The stack trace builder would need to recognize the new stack frame is from the tear-off closure and retrieve something stored in the stack-frame to access the source location information.

dart2js can't generate tail-calls, so the frame for the tear-off is already on the stack. It is not helpful, though, since in the example it is a general forwarding stub shared by many tear-offs. (If JavaScript had tail-calls we would probably have used it here.)
There is no good way in JavaScript of inspecting the receiver or arguments at call sites in the stack frame to 'decode' the forwarding stub.
