### ISSUE TITLE
Got an internal exception while accessing a iterator getter inside an extension

### ISSUE THREAD

**Issue by guo40020** [dart-lang/sdk#46258]
* Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "macos_x64"
* OS: Macos BigSur
* Browser: Chrome 90

Problem:
The list was not null and getting the iterator outside of the extension is fine but inside the extension threw this exception.   

The first exception:
```log
[ +698 ms] Error: Expected a value of type 'String', but got one of type 'Null'
               at Object.throw_ [as throw] (http://localhost:61387/dart_sdk.js:5041:11)
               at Object.castError (http://localhost:61387/dart_sdk.js:5014:15)
               at Object.cast [as as] (http://localhost:61387/dart_sdk.js:5323:17)
               at Function.as (http://localhost:61387/dart_sdk.js:42780:19)
               at ArrayIterator.new.get current [as current] (http://localhost:61387/dart_sdk.js:15947:18)
               at Object.GenericReduce$124genericReduce [as GenericReduce|genericReduce] 
               at Common.RecordedCodeSelectionRange.new.toSelection 
               at Open.RecordedCodeOpenAction.new.applyChanges 
               at WhereIterable.new.forEach (http://localhost:61387/dart_sdk.js:20094:11)
               at RecordedCodeActions.RecordedCodeActionRoot.fromJson.apply 
               at http://localhost:61387/packages/[package_name]/main.dart.lib.js:354:16
               at http://localhost:61387/dart_sdk.js:24284:9
```

Another exception:  
  Then I tried to get the iterator and see what happend, and it threw another exception.
```
this.iterator
[+15337 ms] Internal error: RangeError (offset): Invalid value: Not in inclusive range 0..14: 480:#0      RangeError.checkValueInInterval (dart:core/errors.dart:277:7)
[        ] #1      Source.getLocation (package:kernel/ast.dart:13082:16)
[        ] #2      getLocation (package:front_end/src/fasta/messages.dart:19:52)
[        ] #3      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:219:47)
[        ] #4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:227:31)
[        ] #5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:245:9)
[        ] #6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:69:13)
[        ] #7      Loader.addMessage (package:front_end/src/fasta/loader.dart:362:20)
[        ] #8      Loader.addProblem (package:front_end/src/fasta/loader.dart:322:12)
[        ] #9      LibraryBuilderImpl.addProblem (package:front_end/src/fasta/builder/library_builder.dart:253:19)
[        ] #10     SourceLibraryBuilder.addProblem (package:front_end/src/fasta/source/source_library_builder.dart:1500:47)
[        ] #11     BodyBuilder.addProblem (package:front_end/src/fasta/kernel/body_builder.dart:6477:20)
[        ] #12     BodyBuilder.reportDuplicatedDeclaration (package:front_end/src/fasta/kernel/body_builder.dart:6520:5)
[        ] #13     BodyBuilder.enterFunctionTypeScope (package:front_end/src/fasta/kernel/body_builder.dart:3433:11)
[        ] #14     BodyBuilder.parseSingleExpression (package:front_end/src/fasta/kernel/body_builder.dart:1443:5)
[        ] #15     SourceLoader.buildExpression (package:front_end/src/fasta/source/source_loader.dart:539:21)
[        ] <asynchronous suspension>
[        ] #16     IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:1946:39)
[        ] <asynchronous suspension>
[        ] #17     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:1844:12)
[        ] <asynchronous suspension>
[        ] #18     ExpressionCompiler._compileExpression (package:dev_compiler/src/kernel/expression_compiler.dart:441:21)
[        ] <asynchronous suspension>
[        ] #19     ExpressionCompiler.compileExpressionToJs (package:dev_compiler/src/kernel/expression_compiler.dart:349:26)
[        ] <asynchronous suspension>
[        ] #20     FrontendCompiler.compileExpressionToJs (package:frontend_server/frontend_server.dart:862:23)
[        ] <asynchronous suspension>
CompilationError: Internal error: RangeError (offset): Invalid value: Not in inclusive range 0..14: 480:#0      RangeError.checkValueInInterval (dart:core/errors.dart:277:7)
#1      Source.getLocation (package:kernel/ast.dart:13082:16)
#2      getLocation (package:front_end/src/fasta/messages.dart:19:52)
#3      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:219:47)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:227:31)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:245:9)
```

The code
```dart
extension GenericReduce<E> on List<E> {
  /// a reduce function that allows you to change type
  /// pass in a callback(T? value, E element, int index) => T?
  /// if a null value is returned, the function stops and
  /// return the last value you returned
  T? genericReduce<T>(T? Function(T?, E, int) callback) {
    if (this.isEmpty) {
      return null;
    }
    T? current;
    int index = 0;
    while (this.iterator.moveNext()) {
      var tmp = callback(current, this.iterator.current, index);
      if (tmp == null) {
        return current;
      } else {
        current = tmp;
      }
      index++;
    }
    return current;
 }
```

**Comment by lrhn** [comment]
The error occurs because you are using the iterator incorrectly.

You do `this.iterator.moveNext()` followed by `this.iterator.current`. However, each use of `this.iterator` creates a *new* iterator, so the `this.iterator.current` is asking for the current element of an iterator which hasn't moved to its first element yet.
It *tries* to return `null` (because that's what it would do pre null-safety), but with null safety the iterator element type doesn't allow `null`, and therefore it throws.

Instead do:
```dart
...
var iterator = this.iterator;
while (iterator.moveNext()) {
  var tmp = callback(current, iterator.current, index);
...
```

**Comment by guo40020** [comment]
Ohhhhhhhh
I see....
Sorry for my carelessness
Thanks a lot
