### ISSUE TITLE
[vm/ffi] Add support for MacOS arm64

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#46305]
There are new test failures on [[infra] Add xcodebuild/...XARM64 directories to the vm-kernel fileset](https://github.com/dart-lang/sdk/commit/1a0a1e1e8e88e11f207b832cc1b4e6fb3ab32275).

The tests
```
ffi_2/function_callbacks_structs_by_value_generated_test/0 RuntimeError (expected Pass)
ffi_2/function_callbacks_structs_by_value_generated_test/1 RuntimeError (expected Pass)
ffi_2/function_callbacks_structs_by_value_generated_test/2 RuntimeError (expected Pass)
ffi_2/function_callbacks_structs_by_value_generated_test/3 RuntimeError (expected Pass)
ffi_2/function_callbacks_test/0 RuntimeError (expected Pass)
ffi_2/function_callbacks_test/1 RuntimeError (expected Pass)
ffi_2/function_callbacks_test/2 RuntimeError (expected Pass)
ffi_2/function_callbacks_test/3 RuntimeError (expected Pass)
ffi_2/function_callbacks_test/4 RuntimeError (expected Pass)
ffi_2/function_callbacks_test/5 RuntimeError (expected Pass)
ffi_2/function_callbacks_test/6 RuntimeError (expected Pass)
ffi_2/function_callbacks_test/7 RuntimeError (expected Pass)
ffi_2/function_callbacks_test/8 RuntimeError (expected Pass)
ffi_2/function_callbacks_very_many_test/0 RuntimeError (expected Pass)
ffi_2/function_callbacks_very_many_test/1 RuntimeError (expected Pass)
ffi_2/function_callbacks_very_many_test/2 RuntimeError (expected Pass)
ffi_2/function_callbacks_very_many_test/3 RuntimeError (expected Pass)
ffi_2/function_callbacks_very_many_test/4 RuntimeError (expected Pass)
ffi_2/function_callbacks_very_many_test/5 RuntimeError (expected Pass)
ffi_2/function_callbacks_very_many_test/6 RuntimeError (expected Pass)
ffi_2/function_callbacks_very_many_test/7 RuntimeError (expected Pass)
ffi_2/function_structs_by_value_generated_test/0 RuntimeError (expected Pass)
ffi_2/function_structs_by_value_generated_test/1 RuntimeError (expected Pass)
ffi_2/function_structs_by_value_generated_test/2 RuntimeError (expected Pass)
ffi_2/function_structs_by_value_generated_test/3 RuntimeError (expected Pass)
ffi_2/function_test/0 RuntimeError (expected Pass)
ffi_2/function_test/1 RuntimeError (expected Pass)
ffi_2/function_test/2 RuntimeError (expected Pass)
    and 22 more tests
```
are failing on configurations
```
dartk-mac-release-arm64
```

The `vm_specific_function_callbacks` tests are failing due to symbol lookup failures. Not sure about the others, but guessing it's just needing to adjust stuff for the possibility of ARM64.

/cc  @dcharkes

**Comment by dcharkes** [comment]
Link to approved failures on bot: https://dart-ci.firebaseapp.com/#configurations=dartk-mac-release-arm64

Quick triage:

```
--- Command "vm" (took 794ms):
DART_CONFIGURATION=ReleaseXARM64 xcodebuild/ReleaseXARM64/dart --enable-isolate-groups --experimental-enable-isolate-groups-jit --ignore-unrecognized-flags --packages=/opt/s/w/ir/.packages /opt/s/w/ir/tests/ffi_2/vmspecific_function_callbacks_test.dart

exit code:
-6

stderr:
dyld: lazy symbol binding failed: Symbol not found: _ClobberAndCall
  Referenced from: /opt/s/w/ir/xcodebuild/ReleaseXARM64/./libffi_test_functions.dylib
  Expected in: flat namespace

dyld: Symbol not found: _ClobberAndCall
  Referenced from: /opt/s/w/ir/xcodebuild/ReleaseXARM64/./libffi_test_functions.dylib
  Expected in: flat namespace

--- Re-run this test:
python3 tools/test.py -n dartk-mac-release-arm64 ffi_2/vmspecific_function_callbacks_test/0
```

A linking error.

https://dart-ci.appspot.com/log/vm-kernel-mac-release-arm64/dartk-mac-release-arm64/2/ffi_2/vmspecific_function_callbacks_test/0

```
==== Running PassStruct12BytesHomogeneousFloatx6
Calling TestPassStruct12BytesHomogeneousFloatx6(((-1, 2, -3), (4, -5, 6), (-7, 8, -9), (10, -11, 12), (-13, 14, -15), (16, -17, 18)))
passStruct12BytesHomogeneousFloatx6((-1.0, 2.0, -3.0), (4.0, -5.0, 6.0), (-7.0, 8.0, -9.0), (-11.0, 12.0, -13.0), (-15.0, 16.0, -17.0), (0.0, 0.0, 0.0))
result = -33.0
result = -33

stderr:
Check failed: ((9.0 * 0.99) <= (result) && (9.0 * 1.01) >= (result)) || ((9.0 * 0.99) >= (result) && (9.0 * 1.01) <= (result))
Unhandled exception:
Expect.fail('Test PassStruct12BytesHomogeneousFloatx6 failed.')
#0      Expect._fail (package:expect/expect.dart:731:5)
#1      Expect.fail (package:expect/expect.dart:300:5)
#2      CallbackTest.run (file:///opt/s/w/ir/tests/ffi_2/callback_tests_utils.dart:39:14)
#3      main.<anonymous closure> (file:///opt/s/w/ir/tests/ffi_2/function_callbacks_structs_by_value_generated_test.dart:28:7)
#4      List.forEach (dart:core-patch/growable_array.dart:403:8)
#5      main (file:///opt/s/w/ir/tests/ffi_2/function_callbacks_structs_by_value_generated_test.dart:26:13)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n dartk-mac-release-arm64 ffi_2/function_callbacks_structs_by_value_generated_test/0
```

Mangled arguments in callbacks

10.0, 14.0, and 18.0 are passed "in between" the structs leaving the last struct 0.0, 0.0, 0.0.

https://dart-ci.appspot.com/log/vm-kernel-mac-release-arm64/dartk-mac-release-arm64/2/ffi_2/function_callbacks_test/5

```
PassStruct12BytesHomogeneousFloatx6((-1, 2, -3), (4, -5, 6), (-7, 8, -9), (0, 10, -11), (12, 0, -13), (14, -15, 0))
result = -8
result = -8.0

stderr:
Unhandled exception:
Expect.approxEquals(expected:<9.0>, actual:<-8.0>, tolerance:<0.0009>) fails
#0      Expect._fail (package:expect/expect.dart:731:5)
#1      Expect.approxEquals (package:expect/expect.dart:317:5)
#2      testPassStruct12BytesHomogeneousFloatx6 (file:///opt/s/w/ir/tests/ffi_2/function_structs_by_value_generated_test.dart:2636:10)
#3      main (file:///opt/s/w/ir/tests/ffi_2/function_structs_by_value_generated_test.dart:36:5)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n dartk-mac-release-arm64 ffi_2/function_structs_by_value_generated_test/0
```

Mangled arguments the other way around in calls.

Expected 11 where 10 is passed.

https://dart-ci.appspot.com/log/vm-kernel-mac-release-arm64/dartk-mac-release-arm64/2/ffi_2/function_structs_by_value_generated_test/0

**Comment by dcharkes** [comment]
Having the previous fix landed enables us to see further failure on the M1 devices.

Log of current results: https://dart-ci.firebaseapp.com/current_results/#/filter=dartk-mac-release-arm64,ffi&showAll

### ABI

Further triage:

```
PassStruct9BytesPackedMixedx10DoubleInt32((1, 2), (3, 4), (5, 6), (7, 8), (9, 10), (11, 12), (13, 14), (15, 16), (17, 18), (19, 20), -21, 392336737)
result = 3.92337e+08
result = 392336926.0

stderr:
Unhandled exception:
Expect.approxEquals(expected:<211.0>, actual:<392336926.0>, tolerance:<0.0211>) fails
#0      Expect._fail (package:expect/expect.dart:731:5)
#1      Expect.approxEquals (package:expect/expect.dart:317:5)
#2      testPassStruct9BytesPackedMixedx10DoubleInt32 (file:///opt/s/w/ir/tests/ffi_2/function_structs_by_value_generated_test.dart:5980:10)
#3      main (file:///opt/s/w/ir/tests/ffi_2/function_structs_by_value_generated_test.dart:77:5)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n dartk-mac-release-arm64 ffi_2/function_structs_by_value_generated_test/0
```

Mangled argument in FFI call again.

https://dart-ci.appspot.com/log/any/dartk-mac-release-arm64/32/ffi_2/function_structs_by_value_generated_test/0

```
==== Running PassStruct9BytesPackedMixedx10DoubleInt32
Calling TestPassStruct9BytesPackedMixedx10DoubleInt32(((1, 2), (3, 4), (5, 6), (7, 8), (9, 10), (11, 12), (13, 14), (15, 16), (17, 18), (19, 20), -21, 22))
passStruct9BytesPackedMixedx10DoubleInt32((1, 2.0), (3, 4.0), (5, 6.0), (7, 8.0), (9, 10.0), (11, 12.0), (13, 14.0), (15, 16.0), (17, 18.0), (19, 20.0), -21.0, 0)
result = 189.0
result = 189

stderr:
Check failed: ((211.0 * 0.99) <= (result) && (211.0 * 1.01) >= (result)) || ((211.0 * 0.99) >= (result) && (211.0 * 1.01) <= (result))
Unhandled exception:
Expect.fail('Test PassStruct9BytesPackedMixedx10DoubleInt32 failed.')
#0      Expect._fail (package:expect/expect.dart:731:5)
#1      Expect.fail (package:expect/expect.dart:300:5)
#2      CallbackTest.run (file:///opt/s/w/ir/tests/ffi_2/callback_tests_utils.dart:39:14)
#3      main.<anonymous closure> (file:///opt/s/w/ir/tests/ffi_2/function_callbacks_structs_by_value_generated_test.dart:28:7)
#4      List.forEach (dart:core-patch/growable_array.dart:403:8)
#5      main (file:///opt/s/w/ir/tests/ffi_2/function_callbacks_structs_by_value_generated_test.dart:26:13)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n dartk-mac-release-arm64 ffi_2/function_callbacks_structs_by_value_generated_test/0
```

Same mangled arguments in callbacks.

https://dart-ci.appspot.com/log/any/dartk-mac-release-arm64/32/ffi_2/function_structs_by_value_generated_test/0

```c++
double PassStruct9BytesPackedMixedx10DoubleInt32(
    Struct9BytesPackedMixed a0,
    Struct9BytesPackedMixed a1,
    Struct9BytesPackedMixed a2,
    Struct9BytesPackedMixed a3,
    Struct9BytesPackedMixed a4,
    Struct9BytesPackedMixed a5,
    Struct9BytesPackedMixed a6,
    Struct9BytesPackedMixed a7,
    Struct9BytesPackedMixed a8,
    Struct9BytesPackedMixed a9,
    double a10,
    int32_t a11) {
```

`a11` is not in the place where it is expected to be.

### Linking

`_ClobberAndCall` is also still not linked in.

https://dart-ci.appspot.com/log/any/dartk-mac-release-arm64/32/ffi_2/vmspecific_function_callbacks_test/0

**Comment by dcharkes** [comment]
After https://dart-review.googlesource.com/c/sdk/+/203305, we still have 2 tests failing which use `--use-slow-path`. I'm assuming they also fail on arm64 iOS at the moment. I've filed https://github.com/dart-lang/sdk/issues/46349 to track that failure.
