### ISSUE TITLE
'BinaryExpressionImpl' is not a subtype of type 'SuperExpression' in type cast

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#46302]
```dart
class A  {
  A() : super.
  List<int> values = <int>[];
}
```

This code causes the following crash.

```
  type 'BinaryExpressionImpl' is not a subtype of type 'SuperExpression' in type cast
  #0      AstBuilder.buildInitializer (package:analyzer/src/fasta/ast_builder.dart:442:36)
  #1      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:1712:25)
  #2      Parser.parseInitializers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3085:14)
  #3      Parser.parseInitializersOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3022:14)
  #4      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3936:13)
  #5      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3768:15)
  #6      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3427:15)
  #7      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2000:13)
  #8      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1958:14)
  #9      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
  #10     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
  #11     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
  #12     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:195:32)
  #13     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:191:12)
  #14     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:609:23)
```

**Comment by scheglov** [comment]
@jensjoha

**Comment by jensjoha** [comment]
Yup, this crashes the CFE too (/cc @johnniwinther).

**Comment by jcollins-g** [comment]
P2 for edge case crash, but if this is more widespread please elevate
