### ISSUE TITLE
[Bug]: Error while migrating to null-safety 

### ISSUE THREAD

**Issue by prajwal27** [dart-lang/sdk#46313]
* Dart SDK Version (`2.13.1`)
* Whether you are using Windows, MacOSX, or Linux -- Windows
* Whether you are using Chrome, Safari, Firefox, Edge -- Chrome

I tried migrating my codebase
```
E:\okDone\flutter-main\okdone>dart migrate
Migrating E:\okDone\flutter-main\okdone

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|]
No analysis issues found.

Generating migration suggestions...
[----------------------------------------------------------------------------                                                                                                                                    ]
Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.13.1) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

NoSuchMethodError: The getter 'node' was called on null.
Receiver: null
Tried calling: node at offset 13787 in E:\okDone\flutter-main\okdone\lib\views\chat\widget\thread_message_bubble.dart (MessageSendingStatus?.received)

#0      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:3017:47)
#1      EdgeBuilder.visitPropertyAccess (package:nnbd_migration/src/edge_builder.dart:1451:12)
#2      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8314:50)
#3      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#4      EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:444:23)
#5      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:951:50)
#6      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#7      EdgeBuilder._checkExpressionNotNull (package:nnbd_migration/src/edge_builder.dart:1980:20)
#8      EdgeBuilder.visitConditionalExpression (package:nnbd_migration/src/edge_builder.dart:651:5)
#9      ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:2232:15)
#10     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#11     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#12     EdgeBuilder.visitVariableDeclarationList (package:nnbd_migration/src/edge_builder.dart:1924:11)
#13     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10507:15)
#14     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#15     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#16     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#17     GeneralizingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:593:7)
#18     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10556:15)
#19     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#20     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#21     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#22     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#23     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1065:50)
#24     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#25     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#26     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:326:46)
#27     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#28     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1020:50)
#29     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#30     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:937:25)
#31     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#32     EdgeBuilder.visitFunctionExpression (package:nnbd_migration/src/edge_builder.dart:935:28)
#33     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4919:50)
#34     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#35     EdgeBuilder.visitFunctionDeclaration (package:nnbd_migration/src/edge_builder.dart:886:9)
#36     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4794:50)
#37     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#38     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#39     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#40     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#41     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#42     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#43     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#44     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#45     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#46     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:19)
#47     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1150:28)
#48     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
<asynchronous suspension>
#49     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1150:5)
<asynchronous suspension>
#50     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:747:24)
<asynchronous suspension>
#51     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:7)
<asynchronous suspension>
#52     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#53     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#54     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#55     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```
I'm not sure what the error is. The `node` variable which it's mentioning in the output is not there in my codebase.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
