### ISSUE TITLE
Dart migrate `Bad state` exception

### ISSUE THREAD

**Issue by happy-san** [dart-lang/sdk#46350]
* Dart SDK Version `2.13.1`
* Using Linux

<details>
  <summary>Bad state: Unrelated types: class Configuration extends Equatable* and abstract class BaseApiCall<R extends Object*> at offset 1299 in /typesense-dart/test/services/api_call_test.dart (apiCall.defaultHeaders)</summary>

```
#0      DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:67:10)
#1      DecoratedClassHierarchy.asInstanceOf (package:nnbd_migration/src/decorated_class_hierarchy.dart:38:18)
#2      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:259:16)
#3      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:3000:20)
#4      EdgeBuilder.visitPrefixedIdentifier (package:nnbd_migration/src/edge_builder.dart:1405:14)
#5      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8126:50)
#6      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#7      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#8      EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2937:7)
#9      EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1296:24)
#10     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7091:50)
#11     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#12     EdgeBuilder.visitExpressionStatement (package:nnbd_migration/src/edge_builder.dart:801:25)
#13     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3598:50)
#14     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#15     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#16     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#17     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#18     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1065:50)
#19     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#20     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#21     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:326:46)
#22     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#23     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1020:50)
#24     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#25     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:937:25)
#26     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#27     EdgeBuilder.visitFunctionExpression (package:nnbd_migration/src/edge_builder.dart:935:28)
#28     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4919:50)
#29     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#30     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#31     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2937:7)
#32     EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1296:24)
#33     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7091:50)
#34     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#35     EdgeBuilder.visitExpressionStatement (package:nnbd_migration/src/edge_builder.dart:801:25)
#36     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3598:50)
#37     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#38     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#39     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#40     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#41     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1065:50)
#42     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#43     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#44     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:326:46)
#45     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#46     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1020:50)
#47     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#48     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:937:25)
#49     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#50     EdgeBuilder.visitFunctionExpression (package:nnbd_migration/src/edge_builder.dart:935:28)
#51     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4919:50)
#52     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#53     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#54     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2937:7)
#55     EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1296:24)
#56     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7091:50)
#57     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#58     EdgeBuilder.visitExpressionStatement (package:nnbd_migration/src/edge_builder.dart:801:25)
#59     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3598:50)
#60     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#61     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#62     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#63     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#64     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1065:50)
#65     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#66     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#67     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:326:46)
#68     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#69     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1020:50)
#70     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#71     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:937:25)
#72     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#73     EdgeBuilder.visitFunctionExpression (package:nnbd_migration/src/edge_builder.dart:935:28)
#74     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4919:50)
#75     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#76     EdgeBuilder.visitFunctionDeclaration (package:nnbd_migration/src/edge_builder.dart:886:9)
#77     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4794:50)
#78     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#79     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#80     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#81     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#82     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#83     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#84     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#85     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#86     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#87     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:19)
#88     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1150:28)
#89     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
<asynchronous suspension>
#90     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1150:5)
<asynchronous suspension>
#91     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:747:24)
<asynchronous suspension>
#92     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:7)
<asynchronous suspension>
#93     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#94     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#95     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#96     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```
</details>

Here's the [Configuration](https://github.com/typesense/typesense-dart/blob/000ac111bae5124c7ecbbf25dedebcaca54d12b7/lib/src/configuration.dart) and [BaseApiCall](https://github.com/typesense/typesense-dart/blob/000ac111bae5124c7ecbbf25dedebcaca54d12b7/lib/src/services/base_api_call.dart) class. I think the message is pointing to [this](https://github.com/typesense/typesense-dart/blob/000ac111bae5124c7ecbbf25dedebcaca54d12b7/test/services/api_call_test.dart#L39) line in the `api_call_test.dart` file.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
