### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0 in `ElementWalker.getClass`

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#46392]
I suspect that it somehow related to parts.

```
Thread 0 main threadRangeError: RangeError (index): Invalid value: Valid value range is empty: 0
at List.[](dart:core)
at ElementWalker.getClass(declaration_resolver.dart:122)
at ResolutionVisitor.visitClassDeclaration(resolution_visitor.dart:215)
at ClassDeclarationImpl.accept(ast.dart:1504)
at NodeListImpl.accept(ast.dart:7590)
at CompilationUnitImpl.visitChildren(ast.dart:2100)
at RecursiveAstVisitor.visitCompilationUnit(visitor.dart:749)
at CompilationUnitImpl.accept(ast.dart:2093)
at LibraryAnalyzer._resolveFile(library_analyzer.dart:673)
at LibraryAnalyzer.analyzeSync.<fn>(library_analyzer.dart:129)
at _LinkedHashMapMixin.forEach(dart:collection)
at LibraryAnalyzer.analyzeSync(library_analyzer.dart:128)
at LibraryAnalyzer.analyze(library_analyzer.dart:103)
at AnalysisDriver._computeAnalysisResult.<fn>(driver.dart:1625)
at PerformanceLog.run(performance_logger.dart:32)
at AnalysisDriver._computeAnalysisResult(driver.dart:1601)
at AnalysisDriver.performWork(driver.dart:1244)
at AnalysisDriverScheduler._run(driver.dart:2317)
```

**Comment by meg4cyberc4t** [comment]
Hi. I catch this bug when researching macros.
Initially, I wanted to make a macro that would output not only a list of fields, but also a list of methods.
However, with the next code, the LSP crashes cyclically..

```[Error - 11:58:33] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 11:58:33] An error occurred while handling textDocument/codeAction request: Bad state: [_classIndex: 1][classes.length: 1][classes: [augment class AnyClass]][element.source: /Users/molchanovia/Work/Projects/macro_sandbox/lib/main.macro.dart][libraryFilePath: /Users/molchanovia/Work/Projects/macro_sandbox/lib/main.dart][unitFilePath: /Users/molchanovia/Work/Projects/macro_sandbox/lib/main.macro.dart]
#0      ElementWalker.getClass (package:analyzer/src/generated/element_walker.dart:164:7)
#1      ResolutionVisitor.visitClassDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:293:48)
#2      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2941:50)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12542:20)
#4      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3633:21)
#5      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:972:10)
#6      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:3626:50)
#7      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:843:10)
#8      LibraryAnalyzer._parseAndResolve (package:analyzer/src/dart/analysis/library_analyzer.dart:588:7)
#9      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:105:5)
#10     AnalysisDriver._analyzeFileImpl.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1386:11)
<asynchronous suspension>
#11     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#12     AnalysisDriver._analyzeFile.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1300:9)
<asynchronous suspension>
#13     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#14     AnalysisDriver._analyzeFile (package:analyzer/src/dart/analysis/driver.dart:1297:5)
<asynchronous suspension>
#15     AnalysisDriver._getResolvedLibrary (package:analyzer/src/dart/analysis/driver.dart:1825:5)
<asynchronous suspension>
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1193:7)
<asynchronous suspension>
#17     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2432:7)
<asynchronous suspension>
```

```main.dart
import 'package:macro_sandbox/stringable.dart';
import 'package:macro_sandbox/stringable2.dart';

@Stringable2()
@Stringable()
class AnyClass {
  const AnyClass({
    required this.field1,
    required this.field2,
  });

  final String field1;
  final String field2;
}
```

```stringable.dart
// Took this from https://github.com/felangel/data_class/blob/main/lib/src/stringable_macro.dart
import 'package:collection/collection.dart';
import 'package:macros/macros.dart';

macro class Stringable implements ClassDeclarationsMacro, ClassDefinitionMacro {
  const Stringable();

  @override
  Future<void> buildDeclarationsForClass(
    ClassDeclaration clazz,
    MemberDeclarationBuilder builder,
  ) {
    return _declareToString(clazz, builder);
  }

  @override
  Future<void> buildDefinitionForClass(
    ClassDeclaration clazz,
    TypeDefinitionBuilder builder,
  ) {
    return _buildToString(clazz, builder);
  }

  Future<void> _declareToString(
    ClassDeclaration clazz,
    MemberDeclarationBuilder builder,
  ) async {
    return builder.declareInType(
      DeclarationCode.fromString('external String toString();'),
    );
  }

  Future<void> _buildToString(
    ClassDeclaration clazz,
    TypeDefinitionBuilder builder,
  ) async {
    final methods = await builder.methodsOf(clazz);
    final toString = methods.firstWhereOrNull(
      (m) => m.identifier.name == 'toString',
    );
    if (toString == null) return;
    final toStringMethod = await builder.buildMethod(toString.identifier);
    final clazzName = clazz.identifier.name;
    final fieldDeclarations = await builder.fieldsOf(clazz);
    final fields = fieldDeclarations.map(
      (f) => '${f.identifier.name}: \${${f.identifier.name}.toString()}',
    );
        
    return toStringMethod.augment(
      FunctionBodyCode.fromParts(
        [
          '=> "',
          clazzName,
          '(',
          fields.join(', '),
          ')',
          '";',
        ],
      ),
    );
  }
}
```
 
```stringable2.dart
// My copy paste that crashes with an error.
import 'package:collection/collection.dart';
import 'package:macros/macros.dart';

macro class Stringable2 implements ClassDeclarationsMacro, ClassDefinitionMacro {
  /// {@macro stringable}
  const Stringable2();

  @override
  Future<void> buildDeclarationsForClass(
    ClassDeclaration clazz,
    MemberDeclarationBuilder builder,
  ) {
    return _declareToString(clazz, builder);
  }

  @override
  Future<void> buildDefinitionForClass(
    ClassDeclaration clazz,
    TypeDefinitionBuilder builder,
  ) {
    return _buildToString(clazz, builder);
  }

  Future<void> _declareToString(
    ClassDeclaration clazz,
    MemberDeclarationBuilder builder,
  ) async {
    return builder.declareInType(
      DeclarationCode.fromString('external String toString2();'),
    );
  }

  Future<void> _buildToString(
    ClassDeclaration clazz,
    TypeDefinitionBuilder builder,
  ) async {
    final toString = (await builder.methodsOf(clazz)).firstWhereOrNull(
      (m) => m.identifier.name == 'toString2',
    );
    if (toString == null) return;
    final toStringMethod = await builder.buildMethod(toString.identifier);
    final clazzName = clazz.identifier.name;
    final fieldDeclarations = await builder.fieldsOf(clazz);
    final fields = fieldDeclarations.map(
      (f) => '${f.identifier.name}: \${${f.identifier.name}.toString()}',
    );
    final methodsDeclarations = await builder.methodsOf(clazz);
    final methods = methodsDeclarations.map(
      (m) => '${m.identifier.name}: \${${m.identifier.name}.toString()}',
    );
        
    return toStringMethod.augment(
      FunctionBodyCode.fromParts(
        [
          '=> "',
          clazzName,
          '(',
          fields.join(', '),
          methods.join(', '),
          ')',
          '";',
        ],
      ),
    );
  }
}
```

My pub version is:
```Pub version: 3.5.0-154.0.dev```

I hope this will help in investigating :)

**Comment by meg4cyberc4t** [comment]
I tried to work with it again. The reason does not look in the macro (each macro works fine separately), but in the behavior if you put several of them on the class. At the same time, compilation takes place and dart works with them, but lsp server does not work

**Comment by scheglov** [comment]
I can reproduce the issue. It works if just one macro is used, but fails when both are applied.

<details>
<summary>Click to expand!</summary>

```dart
  solo_test_X() async {
    newFile('$testPackageLibPath/m1.dart', r'''
import 'package:macros/macros.dart';

macro class Stringable implements ClassDeclarationsMacro, ClassDefinitionMacro {
  const Stringable();

  @override
  Future<void> buildDeclarationsForClass(
    ClassDeclaration clazz,
    MemberDeclarationBuilder builder,
  ) {
    return _declareToString(clazz, builder);
  }

  @override
  Future<void> buildDefinitionForClass(
    ClassDeclaration clazz,
    TypeDefinitionBuilder builder,
  ) {
    return _buildToString(clazz, builder);
  }

  Future<void> _declareToString(
    ClassDeclaration clazz,
    MemberDeclarationBuilder builder,
  ) async {
    return builder.declareInType(
      DeclarationCode.fromString('external String toString();'),
    );
  }

  Future<void> _buildToString(
    ClassDeclaration clazz,
    TypeDefinitionBuilder builder,
  ) async {
    final methods = await builder.methodsOf(clazz);
    final toString = methods.firstWhereOrNull(
      (m) => m.identifier.name == 'toString',
    );
    if (toString == null) return;
    final toStringMethod = await builder.buildMethod(toString.identifier);
    final clazzName = clazz.identifier.name;
    final fieldDeclarations = await builder.fieldsOf(clazz);
    final fields = fieldDeclarations.map(
      (f) => '${f.identifier.name}: \${${f.identifier.name}.toString()}',
    );
        
    return toStringMethod.augment(
      FunctionBodyCode.fromParts(
        [
          '=> "',
          clazzName,
          '(',
          fields.join(', '),
          ')',
          '";',
        ],
      ),
    );
  }
}

extension _FirstWhereOrNull<T> on Iterable<T> {
  T? firstWhereOrNull(bool Function(T) compare) {
    for (final item in this) {
      if (compare(item)) return item;
    }
    return null;
  }
}
''');

    newFile('$testPackageLibPath/m2.dart', r'''
import 'package:macros/macros.dart';

macro class Stringable2 implements ClassDeclarationsMacro, ClassDefinitionMacro {
  /// {@macro stringable}
  const Stringable2();

  @override
  Future<void> buildDeclarationsForClass(
    ClassDeclaration clazz,
    MemberDeclarationBuilder builder,
  ) {
    return _declareToString(clazz, builder);
  }

  @override
  Future<void> buildDefinitionForClass(
    ClassDeclaration clazz,
    TypeDefinitionBuilder builder,
  ) {
    return _buildToString(clazz, builder);
  }

  Future<void> _declareToString(
    ClassDeclaration clazz,
    MemberDeclarationBuilder builder,
  ) async {
    return builder.declareInType(
      DeclarationCode.fromString('external String toString2();'),
    );
  }

  Future<void> _buildToString(
    ClassDeclaration clazz,
    TypeDefinitionBuilder builder,
  ) async {
    final toString = (await builder.methodsOf(clazz)).firstWhereOrNull(
      (m) => m.identifier.name == 'toString2',
    );
    if (toString == null) return;
    final toStringMethod = await builder.buildMethod(toString.identifier);
    final clazzName = clazz.identifier.name;
    final fieldDeclarations = await builder.fieldsOf(clazz);
    final fields = fieldDeclarations.map(
      (f) => '${f.identifier.name}: \${${f.identifier.name}.toString()}',
    );
    final methodsDeclarations = await builder.methodsOf(clazz);
    final methods = methodsDeclarations.map(
      (m) => '${m.identifier.name}: \${${m.identifier.name}.toString()}',
    );
        
    return toStringMethod.augment(
      FunctionBodyCode.fromParts(
        [
          '=> "',
          clazzName,
          '(',
          fields.join(', '),
          methods.join(', '),
          ')',
          '";',
        ],
      ),
    );
  }
}

extension _FirstWhereOrNull<T> on Iterable<T> {
  T? firstWhereOrNull(bool Function(T) compare) {
    for (final item in this) {
      if (compare(item)) return item;
    }
    return null;
  }
}
''');

    await assertNoErrorsInCode(r'''
import 'm1.dart';
import 'm2.dart';

@Stringable2()
@Stringable()
class AnyClass {
  const AnyClass({
    required this.field1,
    required this.field2,
  });

  final String field1;
  final String field2;
}
''');

    final node = findNode.singleListLiteral;
    assertResolvedNodeText(node, r'''
''');
  }
```

</details>

**Comment by scheglov** [comment]
And the reason is the difference between expectations in the analyzer (all augmentations of a class are merged), and reality of the merged code.
```dart
augment library 'package:test/test.dart';

import 'dart:core' as prefix0;

augment class AnyClass {
external String toString();
external String toString2();
  augment prefix0.String toString() => "AnyClass(field1: ${field1.toString()}, field2: ${field2.toString()})";
}
augment class AnyClass {
  augment prefix0.String toString2() => "AnyClass(field1: ${field1.toString()}, field2: ${field2.toString()}toString2: ${toString2.toString()}, toString: ${toString.toString()})";
}
```

@jakemac53 Can you guess why code was merged his way? Is this expected?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/367280
