### ISSUE TITLE
Dart analysis server, SDK version 2.12.3, FATAL error: NoSuchMethodError: The getter 'node' was called on null.

### ISSUE THREAD

**Issue by vietanhle97** [dart-lang/sdk#46406]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.12.3`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.16, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.12.3, server version 1.32.4, FATAL error: NoSuchMethodError: The getter 'node' was called on null.
Receiver: null
Tried calling: node
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:298:39)
#2      LinkedElementFactory.buildExportNamespace (package:analyzer/src/summary2/linked_element_factory.dart:55:21)
#3      LibraryElementImpl.exportNamespace (package:analyzer/src/dart/element/element.dart:4964:42)
#4      NamespaceBuilder._getExportMapping (package:analyzer/src/dart/resolver/scope.dart:315:17)
#5      NamespaceBuilder.getImportedElements (package:analyzer/src/dart/resolver/scope.dart:212:15)
#6      new PrefixScope (package:analyzer/src/dart/element/scope.dart:182:48)
#7      new _LibraryImportScope (package:analyzer/src/dart/element/scope.dart:295:28)
#8      new LibraryScope (package:analyzer/src/dart/element/scope.dart:107:15)
#9      LibraryElementImpl.scope (package:analyzer/src/dart/element/element.dart:5231:23)
#10     LibraryBuilder.buildScope (package:analyzer/src/summary2/library_builder.dart:287:21)
#11     Linker._computeLibraryScopes (package:analyzer/src/summary2/link.dart:170:15)
#12     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:90:5)
#13     Linker.link (package:analyzer/src/summary2/link.dart:76:5)
#14     link (package:analyzer/src/summary2/link.dart:33:10)
#15     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:221:24)
#16     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#17     SetMixin.forEach (dart:collection/set.dart:142:30)
#18     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#19     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#20     SetMixin.forEach (dart:collection/set.dart:142:30)
#21     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#22     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#23     SetMixin.forEach (dart:collection/set.dart:142:30)
#24     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#25     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:252:17)
#26     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#27     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:250:12)
#28     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:76:5)
#29     AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1540:27)
#30     _rootRun (dart:async/zone.dart:1354:13)
#31     _CustomZone.run (dart:async/zone.dart:1258:19)
#32     _runZoned (dart:async/zone.dart:1788:10)
#33     runZoned (dart:async/zone.dart:1710:10)
#34     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#35     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1538:33)
#36     AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1307:30)
#37     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#38     AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1296:20)
#39     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1249:14)
#40     _rootRun (dart:async/zone.dart:1354:13)
#41     _CustomZone.run (dart:async/zone.dart:1258:19)
#42     _runZoned (dart:async/zone.dart:1788:10)
#43     runZoned (dart:async/zone.dart:1710:10)
#44     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#45     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1248:40)
#46     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1386:37)
#47     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:995:39)
#48     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2018:24)
<asynchronous suspension>


#0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:323:5)
#1      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:226:11)
#2      LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#3      SetMixin.forEach (dart:collection/set.dart:142:30)
#4      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#5      Li...
```

For additional log information, please append the contents of
file:///private/var/folders/rf/wszxshvx7lz65pnsfbx3kdj00000gn/T/report.txt.

**Comment by bwilkerson** [comment]
I suspect that this has been fixed.
