### ISSUE TITLE
LateInitializationError: Field '_definingCompilationUnit@681486196' has not been initialized.

### ISSUE THREAD

**Issue by xarmatura** [dart-lang/sdk#46427]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* **Analyzer**
* Common Front End (CFE) and kernel
* Dart core libraries ("dart:async", "dart:io", etc.)
* Dart VM
* dart2js
* dev_compiler
```
LateInitializationError: Field '_definingCompilationUnit@681486196' has not been initialized.
#0      LibraryElementImpl.source (package:analyzer/src/dart/element/element.dart:5248:12)
#1      MigrationResolutionHooksImpl.isLibraryNonNullableByDefault (package:nnbd_migration/src/fix_builder.dart:485:55)
#2      LibraryElementImpl.isNonNullableByDefault (package:analyzer/src/dart/element/element.dart:5125:35)
#3      LinkedElementFactory._setLibraryTypeSystem (package:analyzer/src/summary2/linked_element_factory.dart:524:40)
#4      LinkedElementFactory.createLibraryElementForReading (package:analyzer/src/summary2/linked_element_factory.dart:187:5)
#5      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:258:14)
#6      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:262:25)
#7      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:262:25)
#8      LinkedResolutionReader._readRawElement (package:analyzer/src/summary2/bundle_reader.dart:820:27)
#9      LinkedResolutionReader.nextElement (package:analyzer/src/summary2/bundle_reader.dart:582:19)
#10     ApplyResolutionVisitor._nextElement (package:analyzer/src/summary2/apply_resolution.dart:1487:24)
#11     ApplyResolutionVisitor.visitSimpleIdentifier (package:analyzer/src/summary2/apply_resolution.dart:1172:26)
#12     SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8836:50)
#13     ApplyResolutionVisitor.visitTypeName (package:analyzer/src/summary2/apply_resolution.dart:1258:15)
#14     TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10068:50)
#15     ApplyResolutionVisitor.visitExtendsClause (package:analyzer/src/summary2/apply_resolution.dart:422:21)
#16     ExtendsClauseImpl.accept (package:analyzer/src/dart/ast/ast.dart:3642:50)
#17     ApplyResolutionVisitor.visitClassDeclaration (package:analyzer/src/summary2/apply_resolution.dart:197:27)
#18     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1514:50)
#19     LinkedContext.applyResolution (package:analyzer/src/summary2/bundle_reader.dart:498:11)
#20     LinkedUnitContext.applyResolution (package:analyzer/src/summary2/linked_unit_context.dart:93:25)
#21     TypeParameterizedElementMixin.typeParameters (package:analyzer/src/dart/element/element.dart:7375:22)
#22     AlreadyMigratedCodeDecorator.decorate (package:nnbd_migration/src/already_migrated_code_decorator.dart:82:41)
#23     Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:407:53)
#24     Variables.decoratedElementType (package:nnbd_migration/src/variables.dart:100:9)
#25     FixBuilder._computeMigratedType (package:nnbd_migration/src/fix_builder.dart:242:35)
#26     MigrationResolutionHooksImpl.getExecutableType.<anonymous closure> (package:nnbd_migration/src/fix_builder.dart:400:32)
#27     MigrationResolutionHooksImpl._wrapExceptions (package:nnbd_migration/src/fix_builder.dart:826:21)
#28     MigrationResolutionHooksImpl.getExecutableType (package:nnbd_migration/src/fix_builder.dart:399:7)
#29     MigrationResolutionHooksImpl.getExecutableParameters (package:nnbd_migration/src/fix_builder.dart:389:14)
#30     ExecutableElementImpl.parameters (package:analyzer/src/dart/element/element.dart:3579:35)
#31     CorrectOverrideHelper._computeThisTypeForSubtype (package:analyzer/src/error/correct_override.dart:72:34)
#32     new CorrectOverrideHelper (package:analyzer/src/error/correct_override.dart:32:5)
#33     InheritanceManager3.combineSignatures (package:analyzer/src/dart/element/inheritance_manager3.dart:82:28)
#34     InheritanceManager3._findMostSpecificFromNamedCandidates (package:analyzer/src/dart/element/inheritance_manager3.dart:446:31)
#35     InheritanceManager3._getInterfaceClass (package:analyzer/src/dart/element/inheritance_manager3.dart:559:9)
#36     InheritanceManager3.getInterface (package:analyzer/src/dart/element/inheritance_manager3.dart:219:18)
#37     InheritanceManager3.getMember2 (package:analyzer/src/dart/element/inheritance_manager3.dart:270:21)
#38     InheritanceManager3.getMember (package:analyzer/src/dart/element/inheritance_manager3.dart:237:22)
#39     TypePropertyResolver._lookupInterfaceType (package:analyzer/src/dart/resolver/type_property_resolver.dart:215:31)
#40     TypePropertyResolver.resolve (package:analyzer/src/dart/resolver/type_property_resolver.dart:160:9)
#41     PropertyElementResolver._resolve (package:analyzer/src/dart/resolver/property_element_resolver.dart:368:49)
#42     PropertyElementResolver.resolvePrefixedIdentifier (package:analyzer/src/dart/resolver/property_element_resolver.dart:145:12)
#43     PrefixedIdentifierResolver.resolve (package:analyzer/src/dart/resolver/prefixed_identifier_resolver.dart:30:27)
#44     ResolverVisitor.visitPrefixedIdentifier (package:analyzer/src/generated/resolver.dart:1905:33)
#45     PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8126:50)
#46     ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:1915:18)
#47     PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8314:50)
#48     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:975:20)
#49     InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:420:15)
#50     InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:468:7)
#51     InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:443:7)
#52     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:322:5)
#53     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:867:24)
#54     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:543:16)
#55     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:95:7)
#56     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:402:31)
#57     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1828:21)
#58     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7091:50)
#59     ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:1915:18)
#60     PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8314:50)
#61     ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:1915:18)
#62     PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8314:50)
#63     VariableDeclarationResolver.resolve (package:analyzer/src/dart/resolver/variable_declaration_resolver.dart:54:17)
#64     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:2156:34)
#65     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10412:50)
#66     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
#67     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10513:16)
#68     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1880:10)
#69     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3493:7)
#70     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:2188:11)
#71     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10507:15)
#72     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10560:19)
#73     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1880:10)
#74     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:3497:7)
#75     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10556:15)
#76     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
#77     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1069:17)
#78     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1880:10)
#79     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3147:32)
#80     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2624:13)
#81     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3220:8)
#82     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2623:5)
#83     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1065:50)
#84     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1024:12)
#85     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1880:10)
#86     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3150:56)
#87     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2633:13)
#88     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:1050:13)
#89     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1020:50)
#90     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6951:11)
#91     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1880:10)
#92     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3359:56)
#93     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:3070:11)
#94     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:3063:7)
#95     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:1787:11)
#96     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6942:50)
#97     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
#98     ScopedVisitor.visitExtensionMembersInScope (package:analyzer/src/generated/resolver.dart:2837:18)
#99     ScopedVisitor.visitExtensionDeclaration (package:analyzer/src/generated/resolver.dart:2821:7)
#100    ResolverVisitor.visitExtensionDeclaration (package:analyzer/src/generated/resolver.dart:1444:13)
#101    ExtensionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3757:15)
#102    ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:1184:23)
#103    CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#104    FixBuilder.visitAll (package:nnbd_migration/src/fix_builder.dart:210:12)
#105    NullabilityMigrationImpl.finalizeInput (package:nnbd_migration/src/nullability_migration_impl.dart:169:18)
#106    NonNullableFix.finalizeUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:115:15)
#107    _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1157:21)
#108    _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1154:28)
#109    _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
<asynchronous suspension>
#110    _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1154:5)
<asynchronous suspension>
#111    MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:747:24)
<asynchronous suspension>
#112    MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:7)
<asynchronous suspension>
#113    CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#114    DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#115    runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#116    main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by srawlins** [comment]
Sorry we did not get to addressing this issue in a timely manner. I'm closing it as stale, but if you reproduce it on a recent version of Dart, please re-open.
