### ISSUE TITLE
co19/Language/Expressions/Object_Identity/double_t02 is failing on dartk-(strong|weak-asserts)-mac-(debug|release)-arm64

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#46437]
from https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-kernel-nnbd-mac-debug-arm64/1/overview

```
--- Command "vm" (took 04.000069s):
DART_CONFIGURATION=DebugXARM64 xcodebuild/DebugXARM64/dart --sound-null-safety --ignore-unrecognized-flags --packages=/opt/s/w/ir/cache/builder/sdk/.packages /opt/s/w/ir/cache/builder/sdk/tests/co19/src/Language/Expressions/Object_Identity/double_t02.dart

exit code:
255

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      _fail (file:///opt/s/w/ir/cache/builder/sdk/tests/co19/src/Utils/expect.dart:19:5)
#1      Expect.isTrue (file:///opt/s/w/ir/cache/builder/sdk/tests/co19/src/Utils/expect_common.dart:38:5)
#2      main (file:///opt/s/w/ir/cache/builder/sdk/tests/co19/src/Language/Expressions/Object_Identity/double_t02.dart:30:10)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n dartk-strong-mac-debug-arm64 co19/Language/Expressions/Object_Identity/double_t02
```

**Comment by alexmarkov** [comment]
`co19/Language/Expressions/Object_Identity/double_t02` is currently passing on all VM configurations.
