### ISSUE TITLE
Lazy Deoptimization causes incorrect program behavior

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#46446]
When running this test:
```dart
import 'dart:collection';

main() {
  final entry = Entry();

  final list = LinkedList<Entry>();
  list.addFirst(entry);
  entry.unlink();
  list.addFirst(entry);
  entry.unlink();
}

class Entry extends LinkedListEntry<Entry> {}
```

via
```
% out/ReleaseX64/dart --use-slow-path --deoptimize-on-runtime-call-every=3 --optimization-counter-threshold=10 --deterministic repro.dart      
Unhandled exception:
Null check operator used on a null value
#0      LinkedList._unlink (dart:collection/linked_list.dart:169:16)
#1      LinkedListEntry.unlink (dart:collection/linked_list.dart:237:12)
#2      main (file:///usr/local/google/home/kustermann/repositories/sdk-gclient4/sdk/repro.dart:10:9)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
it can fail.

**Comment by mkustermann** [comment]
The cause of this is that the call specializer replaces an `InstanceCall(set:<name>)` of an implicit field setter function by inserting an `AssertAssignable` and a `StoreInstanceField`. If the `AssertAssignable` lazy-deopts it would continue after-call and the store wouldn't be performed.

This is another case - the first one was fixed in https://github.com/dart-lang/sdk/commit/a44d1eefe67fbe28e9c43e4dd7d8b679bc730ccf
