### ISSUE TITLE
dart2js is generating a phantom type and throwing bogus errors about it

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#46455]
I'm seeing a very bizarre issue where dart2js is generating two distinct JS classes for a single Dart class, and throwing type errors because an object of one of these classes isn't an instance of the other. I haven't been able to find a minimal reproduction for this, so unfortunately you'll need to check out Dart Sass as a whole:

```shellsession
$ git clone git://github.com/sass/dart-sass --branch dart2js-type-error-repro
$ cd dart-sass
$ pub get
$ pub run grinder pkg-npm-dev
$ node repro.js
```

This will produce the following error:

```
result is SassNull: true
{
  err: Error: TypeError: Instance of 'SassNull': type 'SassNull' is not a subtype of type 'FutureOr<SassNull0>?'
      at Object._newRenderError (/home/nweiz/goog/sass/dart/build/npm/sass.dart.js:13677:19)
      at _render_closure1.call$2 (/home/nweiz/goog/sass/dart/build/npm/sass.dart.js:84642:21)
      at _RootZone.runBinary$3$3 (/home/nweiz/goog/sass/dart/build/npm/sass.dart.js:28567:18)
      at _FutureListener.handleError$1 (/home/nweiz/goog/sass/dart/build/npm/sass.dart.js:26968:26)
      at _Future__propagateToListeners_handleError.call$0 (/home/nweiz/goog/sass/dart/build/npm/sass.dart.js:27288:49)
      at Object._Future__propagateToListeners (/home/nweiz/goog/sass/dart/build/npm/sass.dart.js:4638:77)
      at _Future._completeError$2 (/home/nweiz/goog/sass/dart/build/npm/sass.dart.js:27111:9)
      at _AsyncAwaitCompleter.completeError$2 (/home/nweiz/goog/sass/dart/build/npm/sass.dart.js:26733:12)
      at Object._asyncRethrow (/home/nweiz/goog/sass/dart/build/npm/sass.dart.js:4436:17)
      at /home/nweiz/goog/sass/dart/build/npm/sass.dart.js:13315:20 {
    formatted: "Error: TypeError: Instance of 'SassNull': type 'SassNull' is not a subtype of type 'FutureOr<SassNull0>?'",
    status: 3
  },
  result: null
}
```

This error is being thrown by [this code](https://github.com/sass/dart-sass/blob/5dc19ec9f18f404a2beb966aa396dca5d63f7911/lib/src/visitor/async_evaluate.dart#L2197-L2201). Note that:

* dart2js thinks there are two distinct types: `SassNull` and `SassNull0`.
* `result is SassNull` returns `true`, despite the fact that `SassNull` in that context should refer to the same type as the return type declaration.
* This only happens for the `SassNull` type. There are various other names (such as `SassNumber` and `SassString`) that actually do apply to multiple types, but they don't exhibit this behavior since one of the types extends the other.
* This only happens in Sass's asynchronous compilation mode, likely because the type check is being performed by the completer generated by the async/await transformation.

This is a fairly severe issue for us, since it means that we essentially can't run asynchronous JS compilations in development mode which makes it difficult to catch real type errors.

**Comment by rakudrama** [comment]
I was looking at occurences of `SassNull` and `SassNull0` and I noticed that this closure from `meta.dart` appears one in the source, but twice in the compiled output:

```
  _function("type-of", r"$value", (arguments) {
    var value = arguments[0];
    if (value is SassArgumentList) {
      return SassString("arglist", quotes: false);
    }
    if (value is SassBoolean) return SassString("bool", quotes: false);
    if (value is SassColor) return SassString("color", quotes: false);
    if (value is SassList) return SassString("list", quotes: false);
    if (value is SassMap) return SassString("map", quotes: false);
    if (value is SassNull) return SassString("null", quotes: false);
    if (value is SassNumber) return SassString("number", quotes: false);
    if (value is SassFunction) return SassString("function", quotes: false);
    assert(value is SassString);
    return SassString("string", quotes: false);
  }),
```
one occurrence has
```js
      if (value instanceof A.SassMap)
        return new D.SassString("map", false);
      if (value instanceof O.SassNull)
        return new D.SassString("null", false);
      if (value instanceof T.SassNumber)
```
the other:
```js
      if (value instanceof A.SassMap0)
        return new D.SassString0("map", false);
      if (value instanceof O.SassNull0)
        return new D.SassString0("null", false);
      if (value instanceof T.SassNumber0)
```
How is it that one closure appears twice in the output?
Could it be that some files are copied and imported from a different URI?

I also see the example code twice in an async function and twice in a regular function, for a total of four times:
```diff
./build/sass.dart.js\053971-              // Function start
./build/sass.dart.js\053972:              P.print("result is SassNull: true");
./build/sass.dart.js\053973-              $async$returnValue = C.C_SassNull0;
--
./build/sass.dart.js\059891-    visitNullExpression$1: function(node) {
./build/sass.dart.js\059892:      P.print("result is SassNull: true");
./build/sass.dart.js\059893-      return C.C_SassNull0;
--
./build/sass.dart.js\069042-              // Function start
./build/sass.dart.js\069043:              P.print("result is SassNull: true");
./build/sass.dart.js\069044-              $async$returnValue = C.C_SassNull;
--
./build/sass.dart.js\077697-    visitNullExpression$1: function(node) {
./build/sass.dart.js\077698:      P.print("result is SassNull: true");
./build/sass.dart.js\077699-      return C.C_SassNull;
```

I put a `print` in dart2js and the two `SassNull` classes have different canonical URIs.
This means that they are different classes in different libraries.
```
  Class j:class(SassNull)  package:sass/src/value/null.dart
  Class j:class(SassNull)  file:///usr/local/google/home/sra/dart-sass/lib/src/value/null.dart
```

As far as dart2js is concerned, anything to do with URIs happens in the common front end.

/cc @johnniwinther Do you have any ideas what might be happening here?

**Comment by johnniwinther** [comment]
The problem is that from the entrypoint, `package:sass` is imported through both a `file` URI and a `package` URI.

The (generated?) entrypoint has the lines
```Dart
import "../bin/sass.dart" as cli_pkg_main_0_;
import "../lib/src/node.dart" as module_main; 
```
where the former imports `package:sass` through a `package` import and the later is imported relative to the entry-point, which is a `file` URI. This means that Dart sees these as different sets of libraries, and therefore having to distinct types name `Sass`.

If the entrypoint is changed to import `src/node.dart` through a `package` import, this should fix the problem:
```Dart
import "../bin/sass.dart" as cli_pkg_main_0_;
import "package:sass/src/node.dart" as module_main;
```

**Comment by nex3** [comment]
That does seem like something we should fix, but I don't think it explains the problem here. None of the members of `cli_pkg_main_0_` are actually accessed in the code in question. What's more, the name `SassNull` in [`_EvaluateVisitor.visitNullExpression`](https://github.com/sass/dart-sass/blob/5dc19ec9f18f404a2beb966aa396dca5d63f7911/lib/src/visitor/async_evaluate.dart#L2197-L2201) *should* refer to the same class in every context, but `result is SassNull` is `true` whereas the automated type-check that `return result` matches `FutureOr<SassNull>` fails.
