### ISSUE TITLE
Internal problem: Unhandled Instantiation in InferenceVisitor.

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#46458]
A number of tests recently went from `CompileTimeError` to `DartkCrash`, triggered by [204700](https://dart-review.googlesource.com/c/sdk/+/204700).

The affected tests are:
```
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A01_t01
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A01_t02
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A01_t04
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t01
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t03
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t05
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t07
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t09
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t11
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t12
co19/LanguageFeatures/Constructor-tear-offs/type_literal_A01_t01
language/generic_methods/explicit_instantiated_tearoff_test
```

The errors look like:
```
Crash when compiling file:///C:/b/s/w/ir/tests/co19/src/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t01.dart,
at character offset 991:
tests/co19/src/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t01.dart:27:23: Internal problem: Unhandled Instantiation in InferenceVisitor.
    x = instanceMethod<int>;
                      ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:51:5)
#1      unhandled (package:front_end/src/fasta/problems.dart:70:10)
#2      InferenceVisitor._unhandledExpression (package:front_end/src/fasta/kernel/inference_visitor.dart:68:5)
[...]
```

The issue appears to affect the `dartk-weak-asserts-...` builds (though I've only tested `dartk-weak-asserts-linux-debug-x64`).

**Comment by cskau-g** [comment]
Looks like the failure was already approved yesterday by  @stefantsov:
"The constructor tear-offs feature is being implemented at the moment, hence the status change."

**Comment by stefantsov** [comment]
That's right, it's expected. The feature isn't yet implemented, and the crashes (which are internal problems reports) will go away gradually as more and more support for the feature is added.
