### ISSUE TITLE
analysis server exception - Bad state: No definition of type Enum

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#46475]
I'm seeing this when trying to do a jump to definition operation. The following exception is in the IntelliJ log, and, the analysis server process dies.

This is from an SDK build from head. Note that the dart:core `Enum` class was very recently added to the SDK (landing this AM).

I have tried deleting the analysis server's cache, but still see the issue.

```
Unhandled exception: 
Bad state: No definition of type Enum
#0      TypeProviderImpl._getClassElement (package:analyzer/src/dart/element/type_provider.dart:564:7) 
#1      TypeProviderImpl._getType (package:analyzer/src/dart/element/type_provider.dart:572:19) 
#2      TypeProviderImpl.enumType (package:analyzer/src/dart/element/type_provider.dart:232:26) 
#3      EnumElementImpl.interfaces (package:analyzer/src/dart/element/element.dart:2705:44) 
#4      InheritanceManager3._getInterfaceClass (package:analyzer/src/dart/element/inheritance_manager3.dart:587:35) 
#5      InheritanceManager3.getInterface (package:analyzer/src/dart/element/inheritance_manager3.dart:219:18) 
#6      InheritanceManager3.getMember2 (package:analyzer/src/dart/element/inheritance_manager3.dart:270:21) 
#7      InheritanceManager3.getMember (package:analyzer/src/dart/element/inheritance_manager3.dart:237:22) 
#8      TypePropertyResolver._lookupInterfaceType (package:analyzer/src/dart/resolver/type_property_resolver.dart:215:31) 
#9      TypePropertyResolver.resolve (package:analyzer/src/dart/resolver/type_property_resolver.dart:160:9) 
#10     BinaryExpressionResolver._resolveUserDefinableElement (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:312:53) 
#11     BinaryExpressionResolver._resolveEqual (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:122:5) 
#12     BinaryExpressionResolver.resolve (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:51:7) 
#13     ResolverVisitor.visitBinaryExpression (package:analyzer/src/generated/resolver.dart:1037:31) 
#14     BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:943:50) 
#15     ResolverVisitor.visitAssertInitializer (package:analyzer/src/generated/resolver.dart:994:20) 
#16     AssertInitializerImpl.accept (package:analyzer/src/dart/ast/ast.dart:535:50) 
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7595:20) 
#18     AstResolver.resolveConstructorNode.visit (package:analyzer/src/summary2/ast_resolver.dart:75:27) 
#19     AstResolver.resolveConstructorNode (package:analyzer/src/summary2/ast_resolver.dart:86:5) 
#20     ConstructorInitializerResolver._constructor (package:analyzer/src/summary2/constructor_initializer_resolver.dart:56:17) 
#21     ConstructorInitializerResolver.resolve (package:analyzer/src/summary2/constructor_initializer_resolver.dart:24:11) 
#22     LibraryBuilder.resolveConstructors (package:analyzer/src/summary2/library_builder.dart:156:53) 
#23     Linker._resolveConstructors (package:analyzer/src/summary2/link.dart:201:15) 
#24     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:105:5) 
#25     Linker.link (package:analyzer/src/summary2/link.dart:79:5) 
#26     link (package:analyzer/src/summary2/link.dart:38:10) 
#27     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:172:24) 
#28     SetMixin.forEach (dart:collection/set.dart:142:30) 
#29     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#30     SetMixin.forEach (dart:collection/set.dart:142:30) 
#31     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#32     SetMixin.forEach (dart:collection/set.dart:142:30) 
#33     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#34     SetMixin.forEach (dart:collection/set.dart:142:30) 
#35     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#36     SetMixin.forEach (dart:collection/set.dart:142:30) 
#37     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#38     SetMixin.forEach (dart:collection/set.dart:142:30) 
#39     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#40     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:205:7) 
#41     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) 
#42     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:203:12) 
#43     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1834:22) 
#44     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1615:30) 
#45     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) 
#46     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1602:20) 
#47     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1676:26) 
#48     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1306:39) 
#49     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2318:24) 
<asynchronous suspension>
#0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:275:5) 
#1      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:177:11) 
#2      SetMixin.forEach (dart:collection/set.dart:142:30) 
#3      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#4      SetMixin.forEach (dart:collection/set.dart:142:30) 
#5      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#6      SetMixin.forEach (dart:collection/set.dart:142:30) 
#7      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#8      SetMixin.forEach (dart:collection/set.dart:142:30) 
#9      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#10     SetMixin.forEach (dart:collection/set.dart:142:30) 
#11     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#12     SetMixin.forEach (dart:collection/set.dart:142:30) 
#13     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32) 
#14     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:205:7) 
#15     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) 
#16     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:203:12) 
#17     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1834:22) 
#18     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1615:30) 
#19     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) 
#20     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1602:20) 
#21     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1676:26) 
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1306:39) 
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2318:24) 
<asynchronous suspension>
#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1655:9) 
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) 
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1602:20) 
#3      AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1676:26) 
#4      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1306:39) 
#5      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2318:24) 
<asynchronous suspension> 
```

**Comment by jcollins-g** [comment]
might not just be the analysis server.  Traceback at https://github.com/dart-lang/dartdoc/pull/2703/checks?check_run_id=2923043672 looks very similar:

```
test-with-analyzer-sdk: dart2-model_test.dart: 00:18 +0 -1: (setUpAll) [E]
test-with-analyzer-sdk: dart2-model_test.dart:
test-with-analyzer-sdk: dart2-model_test.dart:   Bad state: No definition of type Enum
test-with-analyzer-sdk: dart2-model_test.dart:
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/element/type_provider.dart 564:7                    TypeProviderImpl._getClassElement
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/element/type_provider.dart 572:19                   TypeProviderImpl._getType
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/element/type_provider.dart 232:26                   TypeProviderImpl.enumType
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/element/element.dart 2705:44                        EnumElementImpl.interfaces
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/element/inheritance_manager3.dart 587:35            InheritanceManager3._getInterfaceClass
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/element/inheritance_manager3.dart 219:18            InheritanceManager3.getInterface
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/element/inheritance_manager3.dart 270:21            InheritanceManager3.getMember2
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/element/inheritance_manager3.dart 237:22            InheritanceManager3.getMember
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/resolver/type_property_resolver.dart 215:31         TypePropertyResolver._lookupInterfaceType
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/resolver/type_property_resolver.dart 160:9          TypePropertyResolver.resolve
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/resolver/method_invocation_resolver.dart 708:49     MethodInvocationResolver._resolveReceiverType
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/resolver/method_invocation_resolver.dart 171:5      MethodInvocationResolver.resolve
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/element_resolver.dart 398:31                   ElementResolver.visitMethodInvocation
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1763:21                          ResolverVisitor.visitMethodInvocation
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 7170:50                                MethodInvocationImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 6846:12                                MapLiteralEntryImpl.visitChildren
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1815:10                          ResolverVisitor.visitNode
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/dart/ast/visitor.dart 3436:52                                UnifyingAstVisitor.visitMapLiteralEntry
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 6841:50                                MapLiteralEntryImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 7595:20                                NodeListImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 8691:15                                SetOrMapLiteralImpl.visitChildren
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/resolver/typed_literal_resolver.dart 156:10         TypedLiteralResolver.resolveSetOrMapLiteral
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1924:27                          ResolverVisitor.visitSetOrMapLiteral
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 8670:50                                SetOrMapLiteralImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/resolver/assignment_expression_resolver.dart 86:11  AssignmentExpressionResolver.resolve
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1022:35                          ResolverVisitor.visitAssignmentExpression
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 711:15                                 AssignmentExpressionImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 3646:17                                ExpressionStatementImpl.visitChildren
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1815:10                          ResolverVisitor.visitNode
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/dart/ast/visitor.dart 3313:60                                UnifyingAstVisitor.visitExpressionStatement
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 3642:50                                ExpressionStatementImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 7595:20                                NodeListImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 1061:17                                BlockImpl.visitChildren
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1815:10                          ResolverVisitor.visitNode
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/dart/ast/visitor.dart 3221:32                                UnifyingAstVisitor.visitBlock
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 2535:13                          ScopedVisitor.visitBlock.<fn>
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 3131:8                           ScopedVisitor._withDeclaredLocals
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 2534:5                           ScopedVisitor.visitBlock
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 1057:50                                BlockImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 1016:12                                BlockFunctionBodyImpl.visitChildren
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1815:10                          ResolverVisitor.visitNode
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/dart/ast/visitor.dart 3224:56                                UnifyingAstVisitor.visitBlockFunctionBody
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 2544:13                          ScopedVisitor.visitBlockFunctionBody
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1045:13                          ResolverVisitor.visitBlockFunctionBody
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 1012:50                                BlockFunctionBodyImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 7030:11                                MethodDeclarationImpl.visitChildren
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1815:10                          ResolverVisitor.visitNode
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/dart/ast/visitor.dart 3439:56                                UnifyingAstVisitor.visitMethodDeclaration
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 2981:11                          ScopedVisitor.visitMethodDeclarationInScope
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 2974:7                           ScopedVisitor.visitMethodDeclaration
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1726:11                          ResolverVisitor.visitMethodDeclaration
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 7021:50                                MethodDeclarationImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 7595:20                                NodeListImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 2605:18                          ScopedVisitor.visitClassMembersInScope
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 2586:7                           ScopedVisitor.visitClassDeclaration
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1103:13                          ResolverVisitor.visitClassDeclaration
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 1505:50                                ClassDeclarationImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/generated/resolver.dart 1179:23                          ResolverVisitor.visitCompilationUnit
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/ast/ast.dart 2094:50                                CompilationUnitImpl.accept
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/analysis/library_analyzer.dart 700:10               LibraryAnalyzer._resolveFile
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/analysis/library_analyzer.dart 129:7                LibraryAnalyzer.analyzeSync.<fn>
test-with-analyzer-sdk: dart2-model_test.dart:   dart:collection-patch/compact_hash.dart 400:8                                 _LinkedHashMapMixin.forEach
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/analysis/library_analyzer.dart 128:11               LibraryAnalyzer.analyzeSync
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/analysis/library_analyzer.dart 103:12               LibraryAnalyzer.analyze
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/analysis/driver.dart 1699:65                        AnalysisDriver._computeResolvedLibrary.<fn>
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/analysis/performance_logger.dart 32:15              PerformanceLog.run
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/analysis/driver.dart 1686:20                        AnalysisDriver._computeResolvedLibrary
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/analysis/driver.dart 1275:22                        AnalysisDriver.performWork
test-with-analyzer-sdk: dart2-model_test.dart:   package:analyzer/src/dart/analysis/driver.dart 2318:24                        AnalysisDriverScheduler._run
test-with-analyzer-sdk: dart2-model_test.dart:
test-with-analyzer-sdk: dart2-model_test.dart:
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/205141
