### ISSUE TITLE
Parser crash on string in named argument.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#46473]
Example:
```
void main() {
  foo("x": "x");
}
void foo({required String x}) {}
```
This crashes at the `"x":`  with a stack trace ending in:
```
The compiler crashed: Crash when compiling file:///tmp/dartpadNJXNLG/lib/main.dart,
at character offset 5:
type 'ParserRecovery' is not a subtype of type 'Identifier'
#0      BodyBuilder.handleNamedArgument (package:front_end/src/fasta/kernel/body_builder.dart:4978:16)
#1      Parser.parseArgumentsRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6230:35)
#2      Parser.parseArguments (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6200:12)
#3      Parser.parseArgumentsOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6181:14)
#4      Parser.parseSend (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6160:13)
#5      Parser.parseSendOrFunctionLiteral (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5712:12)
#6      Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5277:14)
#7      Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5184:12)
#8      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4784:13)
#9      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4725:13)
#10     Parser.parseExpressionStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4690:13)
#11     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6568:16)
#12     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4486:14)
```

**Comment by asashour** [comment]
I think this is fixed.

**Comment by lrhn** [comment]
Seems fixed, agree.
