### ISSUE TITLE
dart migrate error

### ISSUE THREAD

**Issue by kristijorgji** [dart-lang/sdk#46490]
Flutter 2.2.2

```
Analyzing project...
[-----------------------------------------------------------------------------------------------------------------------------------------\]No analysis issues found.

Generating migration suggestions...
[------------------------/                                                                                                                 ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.13.1) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

NoSuchMethodError: The getter 'isDynamic' was called on null.
Receiver: null
Tried calling: isDynamic at offset 1905 in /flutter_app/lib/di/injector.dart (Register.factory)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      EdgeBuilder._makeEdgeOrigin (package:nnbd_migration/src/edge_builder.dart:3144:25)

```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
