### ISSUE TITLE
Analysis hangs after typing "Stream<List<>>"

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#46505]
This was raised by @kivocsa99 at https://github.com/Dart-Code/Dart-Code/issues/3436. The following code seems to hang the analyzer:

```dart
class A {
  Stream<List<>>
}
```

It's easy to end up with this code during typing if your editor inserts the `>` when you type a `<`. It seems similar to https://github.com/dart-lang/sdk/issues/44477 and if I try to parse it in a test I see the same assertion failure:

<img width="1055" alt="Screenshot 2021-06-29 at 14 15 01" src="https://user-images.githubusercontent.com/1078012/123803840-8dea0780-d8e4-11eb-8733-21628f9ad4e8.png">

The full stack looks like this:

```
CaughtExceptionWithFiles ('package:analyzer/src/fasta/ast_builder.dart': Failed assertion: line 2323 pos 12: 'optional('>', endToken)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      AstBuilder.endTypeVariables (package:analyzer/src/fasta/ast_builder.dart:2323:12)
#3      ComplexTypeParamOrArgInfo.parseVariables (package:_fe_analyzer_shared/src/parser/type_info_impl.dart:1161:14)
#4      Parser.parseMethodTypeVar (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2968:27)
#5      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3916:15)
#6      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3778:15)
#7      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3437:15)
#8      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2000:13)
#9      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1958:14)
#10     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
#11     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
#12     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#13     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:195:32)
#14     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:191:12)
#15     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:609:23)
#16     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:404:14)
#17     FileState._getUnlinkedBytes (package:analyzer/src/dart/analysis/file_state.dart:554:16)
#18     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:459:17)
#19     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:865:12)
#20     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1569:31)
#21     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1380:26)
#22     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2318:24)
<asynchronous suspension>
)
```

When this happens, analysis appears to never complete (so the IDE continues to show "Analyzing..." forever).

**Comment by DanTup** [comment]
It appears that this is causing an infinite loop and not just failing analysis:

<img width="414" alt="Screenshot 2021-06-29 at 14 22 54" src="https://user-images.githubusercontent.com/1078012/123804990-9c84ee80-d8e5-11eb-89b1-9b79a5a65950.png">

**Comment by kivocsa99** [comment]
@DanTup yes which causes a high CPU consumption 
Note : it is not just `Stream<List<>>` , when writing any complex code like it , for example with dartz package : `Future<Either<T1,T2>>`

**Comment by DanTup** [comment]
@kivocsa99 yep, understood. I believe it's the same issue - when typing `Future<Either<T1,T2>>` there will be a point where your code will be `Future<Either<>>` (as your editor may insert the closing `>` as you type the opening `<`).

**Comment by bwilkerson** [comment]
@jensjoha for the parser bug

@scheglov for the analyzer issue

**Comment by scheglov** [comment]
Ah, it is nice to have a repro for such nasty issues.

There is an unexpected cycle in tokens.
```
[id: 0][offset: 0][type: CLASS][lexeme: class]
[id: 1][offset: 6][type: IDENTIFIER][lexeme: A]
[id: 2][offset: 8][type: OPEN_CURLY_BRACKET][lexeme: {]
[id: 3][offset: 12][type: IDENTIFIER][lexeme: Stream]
[id: 4][offset: 18][type: LT][lexeme: <]
[id: 5][offset: 19][type: IDENTIFIER][lexeme: List]
[id: 6][offset: 23][type: LT][lexeme: <]
[id: 7][offset: 24][type: GT_GT][lexeme: >>]
[id: 8][offset: 27][type: IDENTIFIER][lexeme: ]
[id: 9][offset: 27][type: GT][lexeme: >]
[id: 10][offset: 27][type: CLOSE_CURLY_BRACKET][lexeme: }]
[id: 11][offset: 29][type: EOF][lexeme: ]
[id: 12][offset: 29][type: OPEN_PAREN][lexeme: (]
[id: 13][offset: 29][type: CLOSE_PAREN][lexeme: )]
[id: 14][offset: 29][type: OPEN_CURLY_BRACKET][lexeme: {]
[id: 15][offset: 29][type: CLOSE_CURLY_BRACKET][lexeme: }]
[id: 11][offset: 29][type: EOF][lexeme: ]
[id: 12][offset: 29][type: OPEN_PAREN][lexeme: (]
[id: 13][offset: 29][type: CLOSE_PAREN][lexeme: )]
[id: 14][offset: 29][type: OPEN_CURLY_BRACKET][lexeme: {]
[id: 15][offset: 29][type: CLOSE_CURLY_BRACKET][lexeme: }]
[id: 11][offset: 29][type: EOF][lexeme: ]
[id: 12][offset: 29][type: OPEN_PAREN][lexeme: (]
[id: 13][offset: 29][type: CLOSE_PAREN][lexeme: )]
[id: 14][offset: 29][type: OPEN_CURLY_BRACKET][lexeme: {]
[id: 15][offset: 29][type: CLOSE_CURLY_BRACKET][lexeme: }]
[id: 11][offset: 29][type: EOF][lexeme: ]
[id: 12][offset: 29][type: OPEN_PAREN][lexeme: (]
[id: 13][offset: 29][type: CLOSE_PAREN][lexeme: )]
[id: 14][offset: 29][type: OPEN_CURLY_BRACKET][lexeme: {]
[id: 15][offset: 29][type: CLOSE_CURLY_BRACKET][lexeme: }]
```

For code:
```dart
class A {
  Stream<List<>>
}
```

I don't think we should fix this in the analyzer.
There are some invariants that we expect from tokens and AST.
