### ISSUE TITLE
Failures on Revert "[vm] Prefix HOST_OS_* and TARGET_OS_* with DART_"...Adjust vm test about the Symbol constructor

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#46550]
There are new test failures on [Revert "[vm] Prefix HOST_OS_* and TARGET_OS_* with DART_"...Adjust vm test about the Symbol constructor](https://github.com/dart-lang/sdk/compare/9371fd9fc8057201a6862e4a2726c8fffcea3afa~...42164cc140f860500503ee052e2c72e97a01bd61).

The tests
```
co19_2/Language/Generics/typedef_A02_t01 RuntimeError (expected Pass)
co19_2/Language/Generics/typedef_A05_t02 RuntimeError (expected Pass)
co19_2/Language/Generics/typedef_A05_t03 RuntimeError (expected Pass)
co19_2/Language/Generics/typedef_A05_t04 RuntimeError (expected Pass)
co19_2/Language/Generics/typedef_A05_t05 RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-linux-release-x64
```

@eernstg @johnniwinther

**Comment by alexmarkov** [comment]
Corresponding `co19` tests
```
co19/Language/Generics/typedef_A02_t01
co19/Language/Generics/typedef_A05_t02
co19/Language/Generics/typedef_A05_t03
co19/Language/Generics/typedef_A05_t04
co19/Language/Generics/typedef_A05_t05
```

fail on configurations:
```
dartkp-strong-linux-release-x64
dartkp-weak-asserts-linux-release-x64
```

**Comment by johnniwinther** [comment]
@alexmarkov How do the `co19(_2)/Language/Generics/typedef_A02_t0x` tests fail? Do you have a link to the log? (I cannot run these configurations on Windows)

**Comment by alexmarkov** [comment]
```
/====================================================================================================================\
| dartkp-strong-linux-release-x64:co19/Language/Generics/typedef_A02_t01 broke (Pass -> RuntimeError, expected Pass) |
\====================================================================================================================/

--- Command "vm_compile_to_kernel" (took 03.000507s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_Language_Generics_typedef_A02_t01/out.dill /b/s/w/ir/tests/co19/src/Language/Generics/typedef_A02_t01.dart --packages=/b/s/w/ir/.packages -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 04.000738s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_Language_Generics_typedef_A02_t01/out.S --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_Language_Generics_typedef_A02_t01/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 4ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_Language_Generics_typedef_A02_t01/out.dill

exit code:
0

--- Command "assemble" (took 923ms):
DART_CONFIGURATION=ReleaseX64 gcc -m64 -shared -nostdlib -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_Language_Generics_typedef_A02_t01/out.aotsnapshot /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_Language_Generics_typedef_A02_t01/out.S

exit code:
0

--- Command "remove_assembly" (took 5ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_Language_Generics_typedef_A02_t01/out.S

exit code:
0

--- Command "vm" (took 01.000046s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart_precompiled_runtime --sound-null-safety --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_Language_Generics_typedef_A02_t01/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <int>, actual: <dynamic>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:19)
#1      Expect.equals (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:29)
#2      t1 (file:///b/s/w/ir/tests/co19/src/Language/Generics/typedef_A02_t01.dart:31)
#3      main (file:///b/s/w/ir/tests/co19/src/Language/Generics/typedef_A02_t01.dart)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

--- Re-run this test:
python3 tools/test.py -n dartkp-strong-linux-release-x64 co19/Language/Generics/typedef_A02_t01
```

```
/======================================================================================\
| co19_2/Language/Generics/typedef_A05_t04 broke (Pass -> RuntimeError, expected Pass) |
\======================================================================================/

--- Command "vm_compile_to_kernel" (took 02.000925s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t04/out.dill /b/s/w/ir/tests/co19_2/src/Language/Generics/typedef_A05_t04.dart --packages=/b/s/w/ir/.packages -Ddart.vm.product=false

exit code:
0

--- Command "precompiler" (took 04.000615s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t04/out.S --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t04/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 5ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t04/out.dill

exit code:
0

--- Command "assemble" (took 01.000076s):
DART_CONFIGURATION=ReleaseX64 gcc -m64 -shared -nostdlib -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t04/out.aotsnapshot /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t04/out.S

exit code:
0

--- Command "remove_assembly" (took 13ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t04/out.S

exit code:
0

--- Command "vm" (took 01.000067s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart_precompiled_runtime --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t04/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <X>, actual: <dynamic>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:22)
#1      Expect.equals (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:31)
#2      checkme2 (file:///b/s/w/ir/tests/co19_2/src/Language/Generics/typedef_A05_t04.dart:26)
#3      main (file:///b/s/w/ir/tests/co19_2/src/Language/Generics/typedef_A05_t04.dart)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

--- Re-run this test:
python3 tools/test.py -n dartkp-linux-release-x64 co19_2/Language/Generics/typedef_A05_t04


/======================================================================================\
| co19_2/Language/Generics/typedef_A05_t05 broke (Pass -> RuntimeError, expected Pass) |
\======================================================================================/

--- Command "vm_compile_to_kernel" (took 03.000789s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t05/out.dill /b/s/w/ir/tests/co19_2/src/Language/Generics/typedef_A05_t05.dart --packages=/b/s/w/ir/.packages -Ddart.vm.product=false

exit code:
0

--- Command "precompiler" (took 04.000944s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t05/out.S --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t05/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 26ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t05/out.dill

exit code:
0

--- Command "assemble" (took 01.000192s):
DART_CONFIGURATION=ReleaseX64 gcc -m64 -shared -nostdlib -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t05/out.aotsnapshot /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t05/out.S

exit code:
0

--- Command "remove_assembly" (took 7ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t05/out.S

exit code:
0

--- Command "vm" (took 01.000029s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart_precompiled_runtime --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_Language_Generics_typedef_A05_t05/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <X>, actual: <dynamic>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:22)
#1      Expect.equals (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:31)
#2      checkme2 (file:///b/s/w/ir/tests/co19_2/src/Language/Generics/typedef_A05_t05.dart:26)
#3      main (file:///b/s/w/ir/tests/co19_2/src/Language/Generics/typedef_A05_t05.dart)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

--- Re-run this test:
python3 tools/test.py -n dartkp-linux-release-x64 co19_2/Language/Generics/typedef_A05_t05
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8842806455462180112/+/u/test_results/new_test_failures__logs_

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8842810793175180432/+/u/test_results/new_test_failures__logs_

These tests started passing again after https://github.com/dart-lang/sdk/commit/926028460196ef367c6f9106e39d4f2a3bb2ec6a was reverted in https://github.com/dart-lang/sdk/commit/e94ae6cbf33fa695ec6feff2f6f2892736fec557.

**Comment by johnniwinther** [comment]
@alexmarkov It seems to be an existing problem. I can provoke the same error by changing the local to be const (mod of `co19/Language/Generics/typedef_A02_t01`):

```Dart
const i = 1;
class A { const A(); }

@i   typedef int test1<T extends num>();
@A() typedef T test2<T>(T x, int y);

int t1<T extends int>() {
  expect(int, T);
  return 0;
}

T t2<T>(T x, int y) {
  expect(dynamic, T);
  return 14 as T;
}

main() {
  const test1 res1 = t1; // With `const` here, this fails as with the reverted CL.
  res1();

  test2 res2 = t2;
  var x = res2("123", 14);
}

expect(expected, actual) {
  if (expected != actual) throw 'Expected $expected, actual $actual';
}
```
