### ISSUE TITLE
The following assertion was thrown building _BodyBuilder: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4324 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.

### ISSUE THREAD

**Issue by z7b** [dart-lang/sdk#46570]
```
The following assertion was thrown building _BodyBuilder:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4324 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Scaffold file:///D:/mjaaz%201/lib/view/control_view.dart:16:34
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4324:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4327:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4610:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4605:5)
#6      GetWidgetCacheElement.mount (package:get/get_state_manager/src/simple/get_widget_cache.dart:25:11)
...
```

**Comment by lrhn** [comment]
The stack trace suggests that this is an issue in the Flutter code, so you might want to post this in https://github.com/flutter/flutter instead.
