### ISSUE TITLE
[dart2js] Crash on unexpected occurrence of the type `void`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46589]
Consider the following program:

```dart
typedef MyVoid = void;

X? f<X>(X x) {
  if (X != MyVoid) return x;
}

void main() {
  var x1 = f<void>(10);
  print(x1 as dynamic);
}
```

This program causes `dart2js` from to crash as follows, possibly because the type `void` isn't expected in the given situation:
<details>

```
n021.dart:7:6:
Internal Error: The compiler crashed when compiling this element.
void main() {
     ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Unhandled exception:
type 'VoidType' is not a subtype of type 'InterfaceType'
#0      Namer.getTypeRepresentationForTypeConstant (package:compiler/src/js_backend/namer.dart:1475:19)
#1      ConstantNamingVisitor.visitType (package:compiler/src/js_backend/namer.dart:1744:21)
#2      TypeConstantValue.accept (package:compiler/src/constants/values.dart:555:56)
#3      ConstantNamingVisitor._visit (package:compiler/src/js_backend/namer.dart:1607:14)
#4      ConstantNamingVisitor.getName (package:compiler/src/js_backend/namer.dart:1558:5)
#5      Namer.constantLongName (package:compiler/src/js_backend/namer.dart:605:12)
#6      Namer.constantName (package:compiler/src/js_backend/namer.dart:592:25)
#7      ModelEmitter.generateConstantReference (package:compiler/src/js_emitter/startup_emitter/model_emitter.dart:221:56)
#8      EmitterImpl.constantReference (package:compiler/src/js_emitter/startup_emitter/emitter.dart:229:21)
#9      CodegenResult.applyModularState (package:compiler/src/common/codegen.dart:587:16)
#10     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:345:12)
#11     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:452:29)
#12     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:530:70)
#13     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#14     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:530:32)
#15     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#16     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:528:28)
#17     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:819:15)
#18     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:526:18)
#19     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:269:12)
#20     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:285:5)
#21     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:522:16)
#22     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#23     Compiler.emptyQueue (package:compiler/src/compiler.dart:521:14)
#24     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:547:7)
#25     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#26     Compiler.processQueue (package:compiler/src/compiler.dart:540:14)
#27     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:428:5)
#28     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:331:9)
#29     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:503:7)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#31     Compiler.compileFromKernel (package:compiler/src/compiler.dart:469:14)
#32     Compiler.runInternal (package:compiler/src/compiler.dart:304:13)
<asynchronous suspension>
```
</details>

**Comment by fishythefish** [comment]
Sending https://dart-review.googlesource.com/c/sdk/+/206943 out for review.
