### ISSUE TITLE
Error - Unhandled Exception: HttpException: Unexpected response (unsolicited response without request)

### ISSUE THREAD

**Issue by shashank-gb** [dart-lang/sdk#46633]
I'm having an issue while making an HTTP post request in order to send the data to My SQL via php as an API. 

**Small Piece of Code**

```
Future userRegistration() async {
    String name = nameController.text;
    String email = emailController.text;
    String password = passwordController.text;

    var url = Uri.parse('http://pro-connect.infinityfreeapp.com/register_user.php');

    var response = await http.post(url, body: {'name': name, 'email': email, 'password': password});

    var message = '${response.body}';

    print(message);
}
```

**ERROR**

```
E/flutter (14533): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: HttpException: Unexpected response (unsolicited response without request).
E/flutter (14533): #0      new _HttpClientConnection.<anonymous closure> (dart:_http/http_impl.dart:1824:9)
E/flutter (14533): dart-lang/http#1      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (14533): dart-lang/http#2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (14533): dart-lang/http#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (14533): dart-lang/http#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (14533): dart-lang/http#5      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (14533): dart-lang/http#6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (14533): dart-lang/http#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (14533): dart-lang/http#8      _rootRun (dart:async/zone.dart:1346:47)
E/flutter (14533): dart-lang/http#9      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14533): dart-lang/http#10     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14533): dart-lang/http#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (14533): dart-lang/http#12     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (14533): dart-lang/http#13     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14533): dart-lang/http#14     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14533): dart-lang/http#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (14533): dart-lang/http#16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (14533): dart-lang/http#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**flutter doctor log**
```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.746], locale en-IN)
    • Flutter version 2.0.5 at C:\src\flutter
    • Framework revision adc687823a (4 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\SHASHANKgb\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files (x86)\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\SHASHANKgb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • RMX1992 (mobile) • afc22e82 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 90.0.4430.72
    • Edge (web)       • edge     • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```

**Note** : I am running this application in mobile device

**Comment by mraleph** [comment]
You have some issue with your server. If you `tcpdump` the traffic you get the following: 

```
$ sudo tcpdump -i eno1 -ttttnnvvS host 185.27.134.103
tcpdump: listening on eno1, link-type EN10MB (Ethernet), snapshot length 262144 bytes
2021-07-16 09:59:25.136139 IP (tos 0x0, ttl 64, id 50961, offset 0, flags [DF], proto TCP (6), length 60)
    100.104.159.83.38788 > 185.27.134.103.80: Flags [S], cksum 0x436d (incorrect -> 0x8d40), seq 1207654990, win 64240, options [mss 1460,sackOK,TS val 1397944095 ecr 0,nop,wscale 7], length 0
2021-07-16 09:59:25.170824 IP (tos 0x20, ttl 52, id 0, offset 0, flags [DF], proto TCP (6), length 52)
    185.27.134.103.80 > 100.104.159.83.38788: Flags [S.], cksum 0xb652 (correct), seq 3672188896, ack 1207654991, win 14600, options [mss 1338,nop,nop,sackOK,nop,wscale 8], length 0
2021-07-16 09:59:25.170865 IP (tos 0x0, ttl 64, id 50962, offset 0, flags [DF], proto TCP (6), length 40)
    100.104.159.83.38788 > 185.27.134.103.80: Flags [.], cksum 0x4359 (incorrect -> 0x2dbe), seq 1207654991, ack 3672188897, win 502, length 0
2021-07-16 09:59:25.222393 IP (tos 0x0, ttl 64, id 50963, offset 0, flags [DF], proto TCP (6), length 255)
    100.104.159.83.38788 > 185.27.134.103.80: Flags [P.], cksum 0x4430 (incorrect -> 0xa682), seq 1207654991:1207655206, ack 3672188897, win 502, length 215: HTTP, length: 215
        POST /register_user.php HTTP/1.1
        user-agent: Dart/2.14 (dart:io)
        content-type: application/x-www-form-urlencoded; charset=utf-8
        accept-encoding: gzip
        content-length: 38
        host: pro-connect.infinityfreeapp.com

2021-07-16 09:59:25.224718 IP (tos 0x0, ttl 64, id 50964, offset 0, flags [DF], proto TCP (6), length 78)
    100.104.159.83.38788 > 185.27.134.103.80: Flags [P.], cksum 0x437f (incorrect -> 0xb84b), seq 1207655206:1207655244, ack 3672188897, win 502, length 38: HTTP
2021-07-16 09:59:25.256626 IP (tos 0x20, ttl 52, id 27844, offset 0, flags [DF], proto TCP (6), length 40)
    185.27.134.103.80 > 100.104.159.83.38788: Flags [.], cksum 0x2e9f (correct), seq 3672188897, ack 1207655206, win 62, length 0
2021-07-16 09:59:25.257020 IP (tos 0x20, ttl 52, id 27845, offset 0, flags [DF], proto TCP (6), length 887)
    185.27.134.103.80 > 100.104.159.83.38788: Flags [P.], cksum 0xe25d (correct), seq 3672188897:3672189744, ack 1207655206, win 62, length 847: HTTP, length: 847
        HTTP/1.1 200 OK
        Server: nginx
        Date: Fri, 16 Jul 2021 07:59:24 GMT
        Content-Type: text/html
        Transfer-Encoding: chunked
        Connection: keep-alive
        Vary: Accept-Encoding
        Expires: Thu, 01 Jan 1970 00:00:01 GMT
        Cache-Control: no-cache
        Content-Encoding: gzip

        23f
2021-07-16 09:59:25.257040 IP (tos 0x0, ttl 64, id 50965, offset 0, flags [DF], proto TCP (6), length 40)
    100.104.159.83.38788 > 185.27.134.103.80: Flags [.], cksum 0x4359 (incorrect -> 0x2973), seq 1207655244, ack 3672189744, win 501, length 0
2021-07-16 09:59:25.258918 IP (tos 0x20, ttl 52, id 27846, offset 0, flags [DF], proto TCP (6), length 335)
    185.27.134.103.80 > 100.104.159.83.38788: Flags [P.], cksum 0x59c4 (correct), seq 3672189744:3672190039, ack 1207655244, win 62, length 295: HTTP, length: 295
        HTTP/1.1 400 Bad Request
        Server: nginx
        Date: Fri, 16 Jul 2021 07:59:24 GMT
        Content-Type: text/html
        Content-Length: 150
        Connection: close

        <html>
        <head><title>400 Bad Request</title></head>
        <body>
        <center><h1>400 Bad Request</h1></center>
        <hr><center>nginx</center>
        </body>
        </html>
2021-07-16 09:59:25.258918 IP (tos 0x20, ttl 52, id 27847, offset 0, flags [DF], proto TCP (6), length 40)
    185.27.134.103.80 > 100.104.159.83.38788: Flags [F.], cksum 0x2a02 (correct), seq 3672190039, ack 1207655244, win 62, length 0
2021-07-16 09:59:25.258935 IP (tos 0x0, ttl 64, id 50966, offset 0, flags [DF], proto TCP (6), length 40)
    100.104.159.83.38788 > 185.27.134.103.80: Flags [.], cksum 0x4359 (incorrect -> 0x284c), seq 1207655244, ack 3672190039, win 501, length 0
2021-07-16 09:59:25.287148 IP (tos 0x0, ttl 64, id 50967, offset 0, flags [DF], proto TCP (6), length 40)
    100.104.159.83.38788 > 185.27.134.103.80: Flags [F.], cksum 0x4359 (incorrect -> 0x284a), seq 1207655244, ack 3672190040, win 501, length 0
2021-07-16 09:59:25.321421 IP (tos 0x20, ttl 52, id 27848, offset 0, flags [DF], proto TCP (6), length 40)
    185.27.134.103.80 > 100.104.159.83.38788: Flags [.], cksum 0x2a01 (correct), seq 3672190040, ack 1207655245, win 62, length 0
```

Notice how the server sends two responses to a single request. Check your PHP code.
