### ISSUE TITLE
Incremental compiler throws exceptions when nested structs are used by-value in different libraries

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#46666]
When a struct (StructA) with nested structs (NestedStruct) is used by-value in a struct declared in another library (StructB) the incremental compiler will crash when reloading because it can't find the nested struct. If you modify both libraries the reload succeeds.

My current workaround is to declare my wrapper struct (StructB) in a different file that won't get reloaded frequently.

Minimal reproduction:

Able to reproduce this on `2.14.0-322.0.dev` (Flutter master branch)

Run `dart --trace_kernel=true --trace_reload=true --trace_reload_verbose=true run --observe=8181/0.0.0.0 --no-serve-devtools b.dart`, then open Observatory and reload the main isolate after modifying `b.dart`

```dart
// file: a.dart
import 'dart:ffi';

class StructA extends Struct {
  external Pointer<Void> a1;
  external Pointer<Void> a2;
  external Pointer<Void> a3;
  external NestedStruct blah;
}

class NestedStruct extends Struct {
  external Pointer<Void> n1;
  external Pointer<Void> n2;
  external Pointer<Void> n3;
}

// file: b.dart
import 'dart:ffi';
import 'dart:isolate';
import 'dart:async';

import 'a.dart';

class StructB extends Struct {
  external StructA b1;
}

void periodic() {
  print(sizeOf<StructB>());
  // Uncomment/comment and reload:
  //print(nullptr.cast<StructB>());
}

void main() {
  Timer.periodic(const Duration(seconds: 1), (_) => periodic());
}
```

Results in:

```
---- LOAD FAILED, ABORTING RELOAD
ISO-RELOAD: Error: Crash when compiling null,
at character offset null:
Class 'Class(NestedStruct)' not found in compoundCache.
#0      new NativeTypeCfe (package:vm/transformations/ffi_definitions.dart:988:9)
#1      _FfiDefinitionTransformer._compoundAnnotatedNativeTypeCfe (package:vm/transformations/ffi_definitions.dart:734:21)
#2      _FfiDefinitionTransformer.manualVisitInTopologicalOrder.<anonymous closure> (package:vm/transformations/ffi_definitions.dart:212:34)
#3      List.forEach (dart:core-patch/growable_array.dart:403:8)
#4      _FfiDefinitionTransformer.manualVisitInTopologicalOrder (package:vm/transformations/ffi_definitions.dart:179:25)
#5      transformLibraries (package:vm/transformations/ffi_definitions.dart:89:15)
#6      VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:172:7)
#7      KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1255:19)
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:371:7)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
<asynchronous suspension>
#10     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:309:13)
<asynchronous suspension>
#11     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:29)
<asynchronous suspension>
#12     IncrementalCompilerWrapper.compileInternal (google3:///third_party/dart/vm/bin/kernel_service.dart:344:23)
<asynchronous suspension>
#13     Compiler.compile.<anonymous closure> (google3:///third_party/dart/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#14     _processLoadRequest (google3:///third_party/dart/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>


#0      new NativeTypeCfe (package:vm/transformations/ffi_definitions.dart:988:9)
#1      _FfiDefinitionTransformer._compoundAnnotatedNativeTypeCfe (package:vm/transformations/ffi_definitions.dart:734:21)
#2      _FfiDefinitionTransformer.manualVisitInTopologicalOrder.<anonymous closure> (package:vm/transformations/ffi_definitions.dart:212:34)
#3      List.forEach (dart:core-patch/growable_array.dart:403:8)
#4      _FfiDefinitionTransformer.manualVisitInTopologicalOrder (package:vm/transformations/ffi_definitions.dart:179:25)
#5      transformLibraries (package:vm/transformations/ffi_definitions.dart:89:15)
#6      VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:172:7)
#7      KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1255:19)
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:371:7)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
<asynchronous suspension>
#10     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:309:13)
<asynchronous suspension>
#11     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:29)
<asynchronous suspension>
#12     IncrementalCompilerWrapper.compileInternal (google3:///third_party/dart/vm/bin/kernel_service.dart:344:23)
<asynchronous suspension>
#13     Compiler.compile.<anonymous closure> (google3:///third_party/dart/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#14     _processLoadRequest (google3:///third_party/dart/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>
```

cc @dcharkes

**Comment by johnniwinther** [comment]
cc @dcharkes

**Comment by dcharkes** [comment]
Thanks for reporting Dwayne!

Fix underway: https://dart-review.googlesource.com/c/sdk/+/207761.
