### ISSUE TITLE
Error while migrating:  NoSuchMethodError during suggestion generation

### ISSUE THREAD

**Issue by andfaxle** [dart-lang/sdk#46695]
Hello together!

I am trying to migrate my Flutter project to sound null safety, unfortunately I get the following error  during the "Generating migration suggestions" phase: 
( I also tried it with dart v2.14.3)

```
Migrating C:\some\location\project

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[-----------------------------------------------------------------------------------------------------------------]
No analysis issues found.

Generating migration suggestions...
[--------------------/                                                                                            ]
Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.13.3) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

NoSuchMethodError: The getter 'node' was called on null.
Receiver: null
Tried calling: node at offset 718 in C:\Informatik\workspaces\flutter_workspace\socialize\lib\ui\app\app.dart (Them
eService?.instance)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:3017:47)
#2      EdgeBuilder.visitPropertyAccess (package:nnbd_migration/src/edge_builder.dart:1451:12)
#3      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8314:50)
#4      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#5      EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1266:22)
#6      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7091:50)
#7      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#8      EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:486:22)
#9      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:951:50)
#10     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#11     EdgeBuilder.visitParenthesizedExpression (package:nnbd_migration/src/edge_builder.dart:1358:18)
#12     ParenthesizedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7842:15)
#13     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#14     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#15     EdgeBuilder.visitReturnStatement (package:nnbd_migration/src/edge_builder.dart:1498:7)
#16     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8482:50)
#17     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#18     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#19     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#20     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#21     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1065:50)
#22     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#23     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#24     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:326:46)
#25     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1020:50)
#27     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#28     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2490:7)
#29     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#30     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6942:50)
#31     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#32     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#33     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#34     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#35     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1514:50)
#36     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#37     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#38     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#39     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/complete
ness_tracker.dart:52:24)
#40     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.da
rt:26:24)
#41     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43
:5)
#42     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#43     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#44     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#45     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:19)
#46     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1150:28)
#47     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
<asynchronous suspension>
#48     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1150:5)
<asynchronous suspension>
#49     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:747:24)
<asynchronous suspension>
#50     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:7)
<asynchronous suspension>
#51     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#52     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#53     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#54     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

```

Flutter doctor: 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1110], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] VS Code (version 1.58.2)
[√] VS Code, 64-bit edition (version 1.43.0)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

Thank you for your help!

**Comment by amirulabu** [comment]
I also get the same error as below. How i am fixing it, is by searching for `DeviceType?.isDevelopmentBoard` as mentioned in the log, and changing it to `DeviceType.isDevelopmentBoard` 

The code that needs changing will be different according to your codebase

```
✗ dart migrate                    
fvm: running Dart from Flutter "2.2.3"

Migrating /Users/amirulabu/workspace/flutter-project

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
No analysis issues found.

Generating migration suggestions...
Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.13.4) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

NoSuchMethodError: The getter 'node' was called on null.
Receiver: null
Tried calling: node at offset 994 in /Users/amirulabu/workspace/flutter-project/lib/core/service/device/device_type.dart (DeviceType?.isDevelopmentBoard)

#0      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:3017:47)
#1      EdgeBuilder.visitPropertyAccess (package:nnbd_migration/src/edge_builder.dart:1451:12)
#2      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8314:50)
#3      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#4      EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:444:23)
#5      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:951:50)
#6      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#7      EdgeBuilder._checkExpressionNotNull (package:nnbd_migration/src/edge_builder.dart:1980:20)
#8      EdgeBuilder.visitBinaryExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:481:25)
#9      ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#10     EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:480:28)
#11     BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:951:50)
#12     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#13     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#14     EdgeBuilder.visitExpressionFunctionBody (package:nnbd_migration/src/edge_builder.dart:793:5)
#15     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3458:15)
#16     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#17     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2490:7)
#18     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#19     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6942:50)
#20     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#21     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#22     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#23     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#24     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1514:50)
#25     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#26     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#27     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#28     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#29     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#30     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#31     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#32     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#33     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#34     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:19)
#35     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1150:28)
#36     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
<asynchronous suspension>
#37     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1150:5)
<asynchronous suspension>
#38     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:747:24)
<asynchronous suspension>
#39     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:7)
<asynchronous suspension>
#40     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#41     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#42     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#43     main (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
