### ISSUE TITLE
Exception for unresolved FunctionReference

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#46698]
We probably don't have full implementation yet, but users sometimes write code that triggers it.
@srawlins 

```dart
class A {
  void foo() {
    B<int>.bar;
  }
}
```
```
  Bad state: No type: B<int>
  #0      ExpressionExtension.typeOrThrow (package:analyzer/src/dart/ast/extensions.dart:88:7)
  #1      PropertyElementResolver._resolve (package:analyzer/src/dart/resolver/property_element_resolver.dart:348:29)
  #2      PropertyElementResolver.resolvePropertyAccess (package:analyzer/src/dart/resolver/property_element_resolver.dart:183:12)
  #3      ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:1857:27)
  #4      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8256:50)
  #5      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3586:17)
  #6      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1818:10)
  #7      UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3313:60)
  #8      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3582:50)
  #9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7470:20)
  #10     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1043:17)
```
![image](https://user-images.githubusercontent.com/384794/126725637-42a1ce69-c9b2-4113-a56a-911eb9a4b33f.png)

**Comment by srawlins** [comment]
Thanks for the report!

**Comment by srawlins** [comment]
Fixed with  https://dart-review.googlesource.com/c/sdk/+/207643
