### ISSUE TITLE
error: Unable to build APK

### ISSUE THREAD

**Issue by efengx** [dart-lang/sdk#46693]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.16, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.6, error: Analysis failed: /Users/ofengx/Desktop/Data/fx-pro/Android/demo_flutter_app/lib/main.dart context: exception_20210723_004404_616
NoSuchMethodError: Class 'DynamicElementImpl' has no instance getter 'isObject'.
Receiver: Instance of 'DynamicElementImpl'
Tried calling: isObject
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ConstConstructorNode.computeDependencies (package:analyzer/src/summary/link.dart:1634)
#2      Node.getDependencies (package:front_end/src/dependency_walker.dart:42)
#3      DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:102)
#4      DependencyWalker.walk (package:front_end/src/dependency_walker.dart:168)
#5      ConstructorElementForLink.isCycleFree (package:analyzer/src/summary/link.dart:1854)
#6      ConstructorElementForLink.link (package:analyzer/src/summary/link.dart:1869)
#7      ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:799)
#8      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1435)
#9      LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:4011)
#10     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3747)
#11     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3669)
#12     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:149)
#13     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:115)
#14     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:115)
#15     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:168)
#16     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3712)
#17     Linker.link (package:analyzer/src/summary/link.dart:4236)
#18     relink (package:analyzer/src/summary/link.dart:132)
#19     link (package:analyzer/src/summary/link.dart:113)
#20     new LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:119)
#21     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#22     new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:118)
#23     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#24     new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:56)
#25     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1375)
<asynchronous suspension>
#26     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1206)
<asynchronous suspension>
#27     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#28     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:989)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1889)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#35     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:442)
#36     _rootRun (dart:async/zone.dart:1126)
#37     _CustomZone.run (dart:async/zone.dart:1023)
#38     runZoned (dart:async/zone.dart:1501)
#39     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:482)
#40     Driver.start (package:analysis_server/src/server/driver.dart:441)
#41     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

For additional log information, please append the contents of
file:///private/var/folders/v7/9xn8x9997m3c8z9g65r32l400000gn/T/report.txt.

**Comment by devoncarew** [comment]
For triages, not that this is for sdk version `2.0.0-edge ...`.

**Comment by srawlins** [comment]
Closing as stale. If this is reproducible in a recent version of Dart, please re-open.
