### ISSUE TITLE
CFE crashes if running with sound null safety

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#46704]
When CFE code is running with sound null safety enabled, it crashes with various runtime errors.

In order to reproduce the failures, patch-in migration of pkg/vm: https://dart-review.googlesource.com/c/sdk/+/207864, https://dart-review.googlesource.com/c/sdk/+/208020 and https://dart-review.googlesource.com/c/sdk/+/208021 (if not landed yet).

After that CFE failures can be reproduced on the pkg/vm unit tests:

Crash 1:
```
tools/test.py -n unittest-asserts-release-linux pkg/vm/test/kernel_front_end_test
```
```
type 'List<TypeBuilder?>' is not a subtype of type 'List<TypeBuilder>?' in type cast
  #0      OutlineBuilder.handleType (package:front_end/src/fasta/source/outline_builder.dart:1401:42)
  #1      SimpleTypeWith1Argument.parseTypeRest (package:_fe_analyzer_shared/src/parser/type_info_impl.dart:259:21)
  #2      SimpleTypeWith1Argument.parseType (package:_fe_analyzer_shared/src/parser/type_info_impl.dart:255:12)
  #3      Parser.parseFormalParameter (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1668:24)
  #4      Parser.parseFormalParametersRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1388:15)
  #5      Parser.parseFormalParameters (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1352:12)
  #6      Parser.parseGetterOrFormalParameters (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1289:15)
  #7      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2922:13)
  #8      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2729:14)
  #9      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:502:14)
  #10     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
  #11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:483:37)
```

Crash 2:
```
tools/test.py -n unittest-asserts-release-linux pkg/vm/test/modular_kernel_plus_aot_test
```
```
type 'Null' is not a subtype of type 'Token' in type cast
#0      DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:702:28)
#1      DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:662:5)
#2      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4042:20)
#3      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3778:15)
#4      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3437:15)
#5      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2000:13)
#6      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1958:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
#8      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
#9      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#10     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:496:14)
<asynchronous suspension>
#11     Loader.buildBodies (package:front_end/src/fasta/loader.dart:287:9)
<asynchronous suspension>
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:366:7)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
<asynchronous suspension>
#14     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:19)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
<asynchronous suspension>
#16     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:51:12)
<asynchronous suspension>
#17     generateKernel (package:front_end/src/kernel_generator_impl.dart:50:10)
<asynchronous suspension>
#18     compileComponent (package:front_end/src/api_unstable/bazel_worker.dart:166:27)
<asynchronous suspension>
#19     compileToKernel (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/test/modular_kernel_plus_aot_test.dart:100:7)
<asynchronous suspension>
#20     main.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/test/modular_kernel_plus_aot_test.dart:38:5)
<asynchronous suspension>
#21     withTempDirectory (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/test/modular_kernel_plus_aot_test.dart:109:5)
<asynchronous suspension>
#22     main (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/test/modular_kernel_plus_aot_test.dart:33:3)
<asynchronous suspension>
```

Crash 3:
```
tools/test.py -n unittest-asserts-release-linux pkg/vm/test/transformations/deferred_loading_test
```
```
type 'Null' is not a subtype of type 'Token' in type cast
  #0      DietListener.endImport (package:front_end/src/fasta/source/diet_listener.dart:512:28)
  #1      Parser.parseImport (package:_fe_analyzer_shared/src/parser/parser_impl.dart:692:16)
  #2      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:611:18)
  #3      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
  #4      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
  #5      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:496:14)
  <asynchronous suspension>
  #6      Loader.buildBodies (package:front_end/src/fasta/loader.dart:287:9)
  <asynchronous suspension>
  #7      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:366:7)
  <asynchronous suspension>
  #8      withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
  <asynchronous suspension>
  #9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:19)
  <asynchronous suspension>
  #10     withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
  <asynchronous suspension>
  #11     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:59:29)
  <asynchronous suspension>
  #12     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:58:10)
  <asynchronous suspension>
  #13     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50:11)
  <asynchronous suspension>
  #14     compileTestCaseToKernelProgram (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/test/common_test_utils.dart:63:8)
  <asynchronous suspension>
  #15     runTestCase (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/test/transformations/deferred_loading_test.dart:21:7)
  <asynchronous suspension>
  #16     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:199:9)
  <asynchronous suspension>
  #17     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:197:7)
  <asynchronous suspension>
  #18     Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:257:7)
  <asynchronous suspension>
```

Full log:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8840879091594146304/+/u/test_results/new_test_failures__logs_

Also, crash 1 can be reproduced by removing `@dart=2.9` from pkg/vm/bin/gen_kernel.dart and building Dart SDK.

/cc @johnniwinther

**Comment by alexmarkov** [comment]
@johnniwinther Thank you for the quick fixes.

Unfortunately, CFE still crashes when running with sound null safety (after the fixes).

If `@dart=2.9` is removed from pkg/vm/bin/gen_kernel.dart and then Dart SDK is built with `tools/build.py -m release create_sdk`, then I still see the following crash in the front-end:
```
Command failed: /.../tools/sdks/dart-sdk/bin/dart -Dsdk_hash=0cddc3213f --dfe=/.../tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /.../out/ReleaseX64/gen/utils/gen_kernel/bootstrap_gen_kernel.dill --packages=/.../.packages --platform=/.../out/ReleaseX64/vm_platform_strong.dill --no-aot --no-embed-sources --no-link-platform --output=gen/utils/analysis_server/analysis_server.dart.dill --depfile=/.../out/ReleaseX64/gen/utils/analysis_server/analysis_server.dart.dill.d -Dsdk_hash=0cddc3213f /.../pkg/analysis_server/bin/server.dart
output: Unhandled exception:
Crash when compiling file:///.../pkg/analyzer/lib/src/generated/sdk.dart,
at character offset 3048:
type 'List<Expression?>' is not a subtype of type 'List<Expression>?' in type cast
#0      BodyBuilder.endFormalParameter (package:front_end/src/fasta/kernel/body_builder.dart:3676:43)
#1      Parser.parseFormalParameter (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1720:14)
#2      Parser.parseOptionalPositionalParameters (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1740:15)
#3      Parser.parseFormalParametersRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1374:17)
#4      Parser.parseFormalParameters (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1352:12)
#5      Parser.parseFormalParametersOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1312:15)
#6      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:979:22)
#7      DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:712:5)
#8      DietListener.endClassConstructor (package:front_end/src/fasta/source/diet_listener.dart:669:5)
#9      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4014:20)
#10     Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3778:15)
#11     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3437:15)
#12     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2000:13)
#13     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1958:14)
#14     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
#15     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
#16     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#17     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:496:14)
<asynchronous suspension>
#18     Loader.buildBodies (package:front_end/src/fasta/loader.dart:287:9)
<asynchronous suspension>
#19     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:366:7)
<asynchronous suspension>
#20     withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
<asynchronous suspension>
#21     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:19)
<asynchronous suspension>
#22     withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
<asynchronous suspension>
#23     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:59:29)
<asynchronous suspension>
#24     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:58:10)
<asynchronous suspension>
#25     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50:11)
<asynchronous suspension>
#26     compileToKernel (package:vm/kernel_front_end.dart:360:22)
<asynchronous suspension>
#27     runCompiler (package:vm/kernel_front_end.dart:267:19)
<asynchronous suspension>
#28     main (file:///.../pkg/vm/bin/gen_kernel.dart:34:19)
<asynchronous suspension>


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1001:7)
#1      DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:712:5)
#2      DietListener.endClassConstructor (package:front_end/src/fasta/source/diet_listener.dart:669:5)
#3      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4014:20)
#4      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3778:15)
#5      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3437:15)
#6      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2000:13)
#7      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1958:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
#9      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
#10     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#11     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:496:14)
<asynchronous suspension>
#12     Loader.buildBodies (package:front_end/src/fasta/loader.dart:287:9)
<asynchronous suspension>
#13     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:366:7)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
<asynchronous suspension>
#15     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:19)
<asynchronous suspension>
#16     withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
<asynchronous suspension>
#17     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:59:29)
<asynchronous suspension>
#18     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:58:10)
<asynchronous suspension>
#19     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50:11)
<asynchronous suspension>
#20     compileToKernel (package:vm/kernel_front_end.dart:360:22)
<asynchronous suspension>
#21     runCompiler (package:vm/kernel_front_end.dart:267:19)
<asynchronous suspension>
#22     main (file:///.../pkg/vm/bin/gen_kernel.dart:34:19)
<asynchronous suspension>
```

**Comment by alexmarkov** [comment]
Fresh pkg/vm unit test failures: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8840626990056197056/+/u/test_results/new_test_failures__logs_

More crashes happen on unit tests:
```
tools/test.py -n unittest-asserts-release-linux pkg/vm/test/transformations/type_flow/transformer_test
```
```
Crash when compiling file:///b/s/w/ir/cache/builder/sdk/pkg/vm//testcases/transformations/type_flow/transformer/annotation.dart,
  at character offset 942:
  type 'List<Expression?>' is not a subtype of type 'List<Expression>?' in type cast
  #0      BodyBuilder.endVariablesDeclaration (package:front_end/src/fasta/kernel/body_builder.dart:2712:45)
  #1      Parser.parseVariablesDeclarationRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6707:16)
  #2      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6693:11)
  #3      Parser.parseExpressionStatementOrDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6524:12)
  #4      Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4638:14)
  #5      Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4531:20)
  #6      Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4436:15)
  #7      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:993:14)
  #8      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:349:5)
  #9      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2953:14)
  #10     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2729:14)
  #11     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:502:14)
  #12     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
  #13     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:496:14)
```
```
Crash when compiling file:///b/s/w/ir/cache/builder/sdk/pkg/vm//testcases/transformations/type_flow/transformer/pragmas.dart,
  at character offset 446:
  type 'List<Expression?>' is not a subtype of type 'List<Expression>?' in type cast
  #0      BodyBuilder.pushNamedFunction (package:front_end/src/fasta/kernel/body_builder.dart:5124:27)
  #1      BodyBuilder.endLocalFunctionDeclaration (package:front_end/src/fasta/kernel/body_builder.dart:5203:5)
  #2      Parser.parseNamedFunctionRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4248:16)
  #3      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6586:16)
  #4      Parser.parseExpressionStatementOrDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6524:12)
  #5      Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4638:14)
  #6      Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4531:20)
  #7      Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4436:15)
  #8      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:993:14)
  #9      DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:712:5)
  #10     DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:662:5)
  #11     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4042:20)
  #12     Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3778:15)
  #13     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3437:15)
  #14     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2000:13)
  #15     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1958:14)
  #16     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
  #17     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
  #18     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
  #19     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:496:14)
```
