### ISSUE TITLE
dart2js ICE on Flutter Editable

### ISSUE THREAD

**Issue by Desdaemon** [dart-lang/sdk#46711]
OS: Linux 5.11 (Pop!_OS 21.04)
Dart SDK: 2.13.4

I got this error message when running `flutter build web` (stable channel). `flutter run` works normally, so I guess this is unrelated to dartdevc.
```
Target dart2js failed: Exception: ../../snap/flutter/common/flutter/packages/flutter/lib/src/rendering/editable.dart:724:14:
Internal Error: The compiler crashed when compiling this element.
  static int previousCharacter(int index, String string, [bool includeWhitespace = true]) {
             ^
The compiler is broken.
-- snip --
Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      KernelSsaGraphBuilder._setupStateForInlining.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:6206:48)
#2      forEachOrderedParameter.handleParameter (package:compiler/src/js_model/element_map.dart:563:6)
#3      forEachOrderedParameterByFunctionNode (package:compiler/src/js_model/element_map.dart:535:6)
#4      forEachOrderedParameter (package:compiler/src/js_model/element_map.dart:571:9)
#5      KernelSsaGraphBuilder._setupStateForInlining (package:compiler/src/ssa/builder_kernel.dart:6191:5)
#6      KernelSsaGraphBuilder._enterInlinedMethod (package:compiler/src/ssa/builder_kernel.dart:6152:5)
#7      KernelSsaGraphBuilder._tryInlineMethod.doInlining (package:compiler/src/ssa/builder_kernel.dart:5978:7)
#8      KernelSsaGraphBuilder._tryInlineMethod (package:compiler/src/ssa/builder_kernel.dart:5991:17)
#9      KernelSsaGraphBuilder._pushDynamicInvocation (package:compiler/src/ssa/builder_kernel.dart:5020:11)
#10     KernelSsaGraphBuilder._buildForInIterator.buildCondition (package:compiler/src/ssa/builder_kernel.dart:2060:7)
#11     LoopHandler.handleLoop (package:compiler/src/ssa/loop_handler.dart:68:50)
#12     KernelSsaGraphBuilder._buildForInIterator (package:compiler/src/ssa/builder_kernel.dart:2091:18)
#13     KernelSsaGraphBuilder.visitForInStatement (package:compiler/src/ssa/builder_kernel.dart:1882:7)
#14     ForInStatement.accept (package:kernel/ast.dart:9058:43)
#15     KernelSsaGraphBuilder.visitBlock (package:compiler/src/ssa/builder_kernel.dart:1731:17)
#16     Block.accept (package:kernel/ast.dart:8518:43)
#17     KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder_kernel.dart:1260:23)
#18     KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:444:15)
#19     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:819:15)
#20     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:429:21)
#21     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:502:22)
#22     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#23     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:485:18)
#24     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:346:21)
#25     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:80:29)
#26     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:454:30)
#27     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:318:43)
#28     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:452:29)
#29     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:530:70)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#31     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:530:32)
#32     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#33     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:528:28)
#34     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:819:15)
#35     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:526:18)
#36     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:269:12)
#37     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:285:5)
#38     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:522:16)
#39     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#40     Compiler.emptyQueue (package:compiler/src/compiler.dart:521:14)
#41     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:547:7)
#42     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#43     Compiler.processQueue (package:compiler/src/compiler.dart:540:14)
#44     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:428:5)
#45     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:331:9)
#46     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:503:7)
#47     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#48     Compiler.compileFromKernel (package:compiler/src/compiler.dart:469:14)
#49     Compiler.runInternal (package:compiler/src/compiler.dart:304:13)
<asynchronous suspension>
```

**Comment by sigmundch** [comment]
Here is the method mentioned in the error above: 

https://github.com/flutter/flutter/blob/184e5871beea4a9b1cbd65dcc57118a7d97285f3/packages/flutter/lib/src/rendering/editable.dart#L682
