### ISSUE TITLE
standalone/io/directory_list_sync_test flaky fails on iso-stress buildbot

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#46737]
from builder [logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8840522328178068736/+/u/Run_Isolate_Stress_Tests_shard_2/task_stdout_stderr:_Run_Isolate_Stress_Tests_shard_2)

```

------------------------------------------------------------
[/b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/../../../tests/standalone_2/io/directory_list_sync_test.dart] error: [FileSystemException: Directory listing failed, path = './a' (OS Error: No such file or directory, errno = 2), #0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      testList (file:///b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/directory_list_sync_test.dart:16:19)
#3      main (file:///b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/directory_list_sync_test.dart:32:3)
#4      wrapper3165.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/generated_stress_test.dart:41310:13)
#5      _rootRun (dart:async/zone.dart:1428:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _runZoned (dart:async/zone.dart:1863:10)
#8      runZoned (dart:async/zone.dart:1785:10)
#9      wrapper3165 (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/generated_stress_test.dart:41309:11)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
]
------------------------------------------------------------
-> Setting exitCode to 255```

**Comment by aam** [comment]
the test will fail if there is a process that creates/deletes "a" folder in checked out sdk directory.
Would be nice to figure out who/what test does that.

**Comment by aam** [comment]
file_fuzz_test is the test which created `a` file.

**Comment by alexmarkov** [comment]
This failure still appears on iso-stress-linux bot:
```
Spawning tests in isolates resulted in the following errors:
------------------------------------------------------------
[/b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/../../../tests/standalone_2/io/directory_list_sync_test.dart] error: [FileSystemException: Directory listing failed, path = './a' (OS Error: No such file or directory, errno = 2), #0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      testList (file:///b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/directory_list_sync_test.dart:16:19)
#3      main (file:///b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/directory_list_sync_test.dart:32:3)
#4      wrapper3164.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/generated_stress_test.dart:41297:13)
#5      _rootRun (dart:async/zone.dart:1428:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _runZoned (dart:async/zone.dart:1863:10)
#8      runZoned (dart:async/zone.dart:1785:10)
#9      wrapper3164 (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/generated_stress_test.dart:41296:11)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
]
------------------------------------------------------------
-> Setting exitCode to 255
```

Full log:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8839708239583306096/+/u/Run_Isolate_Stress_Tests_shard_2/task_stdout_stderr:_Run_Isolate_Stress_Tests_shard_2

**Comment by aam** [comment]
Looks like we have same problem with tests/standalone[_2]/io/directory_fuzz_test.dart.
