### ISSUE TITLE
Compiler crash, not sure what the problem is.

### ISSUE THREAD

**Issue by levifeldman** [dart-lang/sdk#46751]
Hi, I am working on a dart package like usuall, i finished a long re-factor of some code and when i try to run it its saying compiler crash when getting package:cbor/cbor.dart but i have used this package and this version many times before and never got this error on this package. i tried dart pub repair, got same error. Does someone know what this is? this is the error:

Crash when compiling package:cbor/cbor.dart,
at character offset null:
NoSuchMethodError: The getter 'first' was called on null.
Receiver: null
Tried calling: first
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ClassHierarchyNodeBuilder.inferSetterType (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:1036:63)
#2      ClassHierarchyBuilder.inferSetterType (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:583:31)
#3      SourceProcedureBuilder._ensureTypes (package:front_end/src/fasta/builder/procedure_builder.dart:275:19)
#4      SourceProcedureMember.inferType (package:front_end/src/fasta/builder/procedure_builder.dart:614:19)
#5      DelayedTypeComputation.compute (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:3719:20)
#6      ClassHierarchyBuilder.computeTypes (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:781:27)
#7      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:1215:22)
#8      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:334:14)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:103:9)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#13     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#14     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#15     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#16     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#17     _processLoadRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ClassHierarchyNodeBuilder.inferSetterType (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:1036:63)
#2      ClassHierarchyBuilder.inferSetterType (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:583:31)
#3      SourceProcedureBuilder._ensureTypes (package:front_end/src/fasta/builder/procedure_builder.dart:275:19)
#4      SourceProcedureMember.inferType (package:front_end/src/fasta/builder/procedure_builder.dart:614:19)
#5      DelayedTypeComputation.compute (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:3719:20)
#6      ClassHierarchyBuilder.computeTypes (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:781:27)
#7      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:1215:22)
#8      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:334:14)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:103:9)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#13     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#14     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#15     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#16     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#17     _processLoadRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>

**Comment by levifeldman** [comment]
The file i am working on is at https://github.com/levifeldman/ic_tools_dart/blob/code-work/lib/candid.dart

**Comment by levifeldman** [comment]
i tried to run it on a flutter app and then it started giving me normal compiler error messages.
