### ISSUE TITLE
HttpClient cannot resolve azurewebsites.net

### ISSUE THREAD

**Issue by alexrainman** [dart-lang/sdk#46755]
I am trying to connect to an API running on Azure App Service, but it seems the domain azurewebsites.net cannot be resolved.

With http i get:

```
Exception has occurred.
ClientException
```

With HttpClient i get:

```
Exception has occurred.
HttpException (HttpException: , uri = https://mmanow-sandbox.azurewebsites.net/news)
```

With Dio i get:

```
Exception has occurred.
DioError (DioError [DioErrorType.other]: HttpException: , uri = https://MYAPP.azurewebsites.net
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819:20)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678:13)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
<asynchronous suspension>
)
```

This is what i tried:

- Connect from Postman: works.
- Connect from another language (c#): works.
- Connecting to the same API running locally: works.
- Running the app on a real device instead of simulator: not working.
- Lowering TLS version on the backend API: not working.

The error message is empty, so it is very difficult to figure the problem out.

This is a hard stop and i cannot move forward with my app development.

If i need to open this issue on Flutter repo please let me know.

**Comment by a-siva** [comment]
I tried accessing the uri you have above 'https://mmanow-sandbox.azurewebsites.net/news' from a browser and I get 'HTTP ERROR 405'  - This page isn’t working If the problem continues, contact the site owner.
Is this expected ?

**Comment by alexrainman** [comment]
Just a random url.

**Comment by a-siva** [comment]
Can you post some sample code that demonstrates the problem.

**Comment by alexrainman** [comment]
I was able to drill down to the root cause of the issue, and i already commented this in another thread.

My backend requires a client certificate. The advice i got was this:

```
ByteData keystore = await rootBundle.load('assets/security/client.pfx');
final String passPhrase = "mypass";
SecurityContext ctx = new SecurityContext();
ctx.setTrustedCertificatesBytes(keystore.buffer.asUint8List(), password: passPhrase);
ctx.usePrivateKeyBytes(keystore.buffer.asUint8List(), password: passPhrase);
HttpClient client = HttpClient(context: ctx);
```

As soon as i do that, i get the previously mentioned error.

That .pfx file is in P12 format and includes both the client .crt and the private key.

I turned down the client certificate requirement i was able to connect.

This is how i did it in Android and iOS in my modernhttpclient for .Net:

Android: https://github.com/alexrainman/ModernHttpClient/blob/e902a400f7cdc788f14a982e6375d703159cb100/ModernHttpClient.Android/OkHttpNetworkHandler.cs#L142

iOS: https://github.com/alexrainman/ModernHttpClient/blob/e902a400f7cdc788f14a982e6375d703159cb100/ModernHttpClient.iOS/NSUrlSessionHandler.cs#L142

**Comment by alexrainman** [comment]
It is just frustrating.
I followed the documentation and provided the certificate in DER format and i get another error.
