### ISSUE TITLE
Field "exports" has not been initialized - Analyzer

### ISSUE THREAD

**Issue by Felcks** [dart-lang/sdk#46764]
### flutter pub run build_runner build

```
LateInitializationError: Field 'exports' has not been initialized.
#0      LibraryReader.exports (package:analyzer/src/summary2/bundle_reader.dart)
#1      LinkedElementFactory.exportsOfLibrary (package:analyzer/src/summary2/linked_element_factory.dart:157:20)
#2      LinkedElementFactory.buildExportNamespace (package:analyzer/src/summary2/linked_element_factory.dart:51:42)
#3      LibraryElementImpl.exportNamespace (package:analyzer/src/dart/element/element.dart:3628:42)
#4      NamespaceBuilder._getExportMapping (package:analyzer/src/dart/resolver/scope.dart:271:20)
#5      NamespaceBuilder.getImportedElements (package:analyzer/src/dart/resolver/scope.dart:211:15)
#6      new PrefixScope (package:analyzer/src/dart/element/scope.dart:181:48)
#7      new _LibraryImportScope (package:analyzer/src/dart/element/scope.dart:295:28)
#8      new LibraryScope (package:analyzer/src/dart/element/scope.dart:106:15)
#9      LibraryElementImpl.scope (package:analyzer/src/dart/element/element.dart:3840:23)
#10     LibraryBuilder.buildScope (package:analyzer/src/summary2/library_builder.dart:134:21)
#11     Linker._computeLibraryScopes (package:analyzer/src/summary2/link.dart:170:15)
#12     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:98:5)
#13     Linker.link (package:analyzer/src/summary2/link.dart:78:5)
#14     link (package:analyzer/src/summary2/link.dart:35:10)
#15     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:172:24)
#16     SetMixin.forEach (dart:collection/set.dart:142:30)
#17     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:110:32)
#18     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:203:17)
#19     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#20     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:201:12)
#21     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1848:22)
#22     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1760:28)
#23     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#24     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1758:20)
#25     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1342:35)
#26     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2334:24)
<asynchronous suspension>
```

### Version
Flutter version: [2.2.0]
Analyzer verson: [1.7.1]

### What did I do to solve this problem:
On bundle_reader.dart line 404:
`late List<Reference> exports;` to `List<Reference>? exports;` 

On linked_element_factory.dart line 157:
`return library.exports;` to `return library.exports ?? List<Reference>.empty();`

### Question
This problem was already detected and solved on analyzer 2.0.0? I can't upgrade to analyzer 2.0.0 because
of some other libs.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I don't remember fixing this. If there is a project on which this can be reproduced, I'd love to have it.

**Comment by Felcks** [comment]
I will figure out a way to share

**Comment by Felcks** [comment]
I'm sorry, i couldn't find a way to share the problem without sharing the whole company project. I tried to make a copy with just the data models but (un)fortunately it is working

**Comment by scheglov** [comment]
As an alternative, if I could ssh to a machine where it can be reproduced, I could make debug patches to the analyzer with re-runs when it reproduces and gather necessary information. But obviously this still gives me a way to potentially access to all the code. Plus setting this is probably quite time-consuming for you.

What I was going to do is to write some debug data in `LibraryReader`. My expectation is that `LibraryReader.exports` is always filled by `LibraryReader.readElement` because it is called by `LibraryElementImpl.exportNamespace` for its own `source.uri`, and the library must be loaded first by `LibraryReader.readElement`. So, this is puzzling. I'm like to see if there is something special about this library and its URI.

**Comment by alejoecoffee** [comment]
add this

```
dependency_overrides:
  analyzer: '1.5.0'
```

 on your pubspec.yml if you need solve this for now, this work for me
