### ISSUE TITLE
Failed assertion: line 4306 pos 12: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by tudoutiao** [dart-lang/sdk#46815]
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
'dart:ui/painting.dart': Failed assertion: line 4306 pos 12: '<optimized out>': is not true.

The relevant error-causing widget was: 
  CustomPaint file:///F:/demo/LeanDemo/lib/test/error_test.dart:92:14
When the exception was thrown, this was the stack: 
#2      Canvas.drawImage (dart:ui/painting.dart:4306:12)
#3      MyPaint.paint (package:flutter_app/test/error_test.dart:126:12)
#4      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:13)
#5      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#701ac relayoutBoundary=up15
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
...  size: Size(360.0, 50.0)
RenderObject: RenderCustomPaint#701ac relayoutBoundary=up15
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
  size: Size(360.0, 50.0)
===================================================================================

**In addition to the above exceptions, the network pictures in the list sometimes display disorderly**

import 'dart:async';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  List<String> imgList = [
    "http://dimg.chouti.com/CHOUTI_20191210/9846E3881397444D9A3557F0A15846BB_W300H300.png",
    "http://dimg.chouti.com/CHOUTI_20191210/9846E3881397444D9A3557F0A15846BB_W300H300.png",
    "http://dimg.chouti.com/CHOUTI_20191210/9846E3881397444D9A3557F0A15846BB_W300H300.png",
    "http://dimg.chouti.com/CHOUTI_20191210/9846E3881397444D9A3557F0A15846BB_W300H300.png",
    "http://dimg.chouti.com/CHOUTI_20191210/9846E3881397444D9A3557F0A15846BB_W300H300.png",
    "http://dimg.chouti.com/CHOUTI_20191210/9846E3881397444D9A3557F0A15846BB_W300H300.png",
    "http://dimg.chouti.com/CHOUTI_20191210/9846E3881397444D9A3557F0A15846BB_W300H300.png",
    "http://dimg.chouti.com/CHOUTI_20191210/9846E3881397444D9A3557F0A15846BB_W300H300.png",
  ];

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: ListView.builder(
            //高度自适应无需滚动
            shrinkWrap: true,
            physics: NeverScrollableScrollPhysics(),
            itemCount: widget.imgList.length,
            itemBuilder: (BuildContext context, int index) {
              return HeadViewWidget(url: widget.imgList[index]);
            }),
      ),
    );
  }
}

class HeadViewWidget extends StatefulWidget {
  String url;

  HeadViewWidget({this.url});

  @override
  State<StatefulWidget> createState() => _HeadViewWidgetState();
}

class _HeadViewWidgetState extends State<HeadViewWidget> {
  ui.Image _src;

  @override
  void initState() {
    super.initState();
    Future.wait([loadUrl("${widget.url}?imageView2/1/w/20/h/20/interlace/1")])
        .then((results) {
      _src = results[0];
      if (mounted) {
        setState(() {});
      }
    });
  }

  Future<ui.Image> loadImageFromAssets(String path) async {
    ByteData data = await rootBundle.load(path);
    List<int> bytes =
        data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    return decodeImageFromList(bytes);
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: CustomPaint(
        painter: MyPaint(_src),
        size: Size(50, 50),
      ),
    );
  }

  Future<ui.Image> loadUrl(String url) async {
    ImageStream stream =
        new NetworkImage(url).resolve(ImageConfiguration.empty);
    Completer<ui.Image> completer = new Completer<ui.Image>();
    void listener(ImageInfo frame, bool synchronousCall) {
      final ui.Image image = frame.image;
      completer.complete(image);
      stream.removeListener(new ImageStreamListener(listener));
    }

    stream.addListener(new ImageStreamListener(listener));
    return completer.future;
  }
}

class MyPaint extends CustomPainter {
  ui.Image src;

  MyPaint(this.src);

  @override
  void paint(Canvas canvas, Size size) {
    Paint _paint = Paint();
    canvas.saveLayer(Offset.zero & size, Paint()); 
    _paint.color = Colors.yellowAccent;
    canvas.drawCircle(Offset(10, 12), 10, _paint); 
    _paint.blendMode = BlendMode.srcIn; 
    canvas.drawImage(src, Offset(0, 2), _paint);

    canvas.restore();
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}

**Comment by vsmenon** [comment]
What Dart and Flutter versions are you using?  What platform / device?

And, just to clarify - this is debug mode, right?

**Comment by tudoutiao** [comment]
Yes,this is debug mode.
 
   • Flutter version 2.2.2 at D:\tool\dart\flutter
    • Framework revision d79295af24 (8 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
