### ISSUE TITLE
language/constructor/tear_off_test RuntimeError failure on dartk-strong-linux-debug-x64 and others

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#46812]
https://github.com/dart-lang/sdk/commit/32914654bd3a2a927347ab5019f3c7f20f49b337 seems to have improved test outcome from CompileTimeError to RuntimeError 

Example log https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-nnbd-linux-debug-x64/4472

```
--- Command "vm" (took 02.000069s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --sound-null-safety --enable-experiment=constructor-tearoffs --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/language/constructor/tear_off_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <Closure: (int) => GGen<int> from Function 'GGen.': static.>, actual: <Closure: (int) => GGen<int> from Function 'GGen.': static.>) fails.
#0      Expect._fail (package:expect/expect.dart:731:5)
#1      Expect.equals (package:expect/expect.dart:132:5)
#2      main.<anonymous closure> (file:///b/s/w/ir/tests/language/constructor/tear_off_test.dart:202:12)
#3      main (file:///b/s/w/ir/tests/language/constructor/tear_off_test.dart:224:9)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n dartk-strong-linux-debug-x64 language/constructor/tear_off_test
```

cc @alexmarkov

**Comment by alexmarkov** [comment]
Fixed in https://dart.googlesource.com/sdk/+/f9c8f3c920ecad0f982715966bc230630c500069.
