### ISSUE TITLE
[ddc] NaN error with int.parse

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/sdk#46852]
## Bug

For some reason, this snippet of code works on **every platform** (including `dart2js`), but it just **breaks in DDC**:

```dart
OpenSimplex2S(42);
```

The error thrown is:

```
Error: RangeError (index): Value not in range: NaN
    at Object.throw_ [as throw] (http://localhost:63481/dart_sdk.js:5061:11)
    at Object._checkValidIndex (http://localhost:63481/dart_sdk.js:31695:17)
    at Int16Array.[dartx._get] (http://localhost:63481/dart_sdk.js:30652:26)
    at new open_simplex_2s.OpenSimplex2S.new (http://localhost:63481/packages/open_simplex_2/src/open_simplex_2s.dart.lib.js:3207:42)
```

I was able to trace it down to this line:

https://github.com/creativecreatorormaybenot/funvas/blob/f5db955bf109c2eb9ff1cb5ccfea3bf8629ef6af/open_simplex_2/lib/src/open_simplex_2s.dart#L46

Now, assuming that `r` in this case is `NaN`, I would think that:

```dart
seed = 42 * int.parse('6364136223846793005') + int.parse('1442695040888963407');
```

Causes a `NaN` value. What confuses me about this (if my assumption is true) is that this works in `dart2js`.

## Reproduction

The steps to reproduce are stable:

1. Depend on `open_simplex_2: 0.1.0+1`.
2. Call the constructor of one of the two classes:

```dart
import 'package:open_simplex_2/open_simplex_2.dart';

void main() {
  OpenSimplex2S(42);
}
```

3. Run this on DDC → **`RangeError` is thrown**.
4. Run this on any other platform (e.g. compiling using `dart2js`) → works like a charm.

**Comment by vsmenon** [comment]
Any chance you can reduce this to a small standalone program (i.e., without the package)?  That would make it easier to triage / add a test.

**Comment by creativecreatorormaybenot** [comment]
@vsmenon Not sure what the benefit here is really because I posted both the permalink to the code and a perlink in the form of the package version and it directly shows the real world application.

But no worries, here it is extracted for you:

```dart
import 'dart:typed_data';

void main() {
  const _kSize = 2048;
  final _perm = Int16List(_kSize);
  final source = Int16List(_kSize);
  var seed = 42;
  for (var i = 0; i < _kSize; i++) {
    source[i] = i;
  }
  for (int i = _kSize - 1; i >= 0; i--) {
    seed = seed * int.parse('6364136223846793005') +
        int.parse('1442695040888963407');
    var r = (seed + 31) % (i + 1);
    if (r < 0) r += i + 1;
    _perm[i] = source[r];
    source[r] = source[i];
  }
}
```

Hope it helps.

**Comment by vsmenon** [comment]
Thanks!

On the smaller repro, if I print `r` before the access to `source[r]`, I see the same values in both dart2js and ddc - until the `NaN`.  

It appears that dart2js is optimizing incorrectly in the presence of `NaN` - the `_checkValidIndex` is replaced with `if (r >= 2048) ...`, which doesn't catch the `NaN` input.

fyi - @rakudrama

**Comment by creativecreatorormaybenot** [comment]
@vsmenon Yeah, I did the same debugging. I am wondering if my code is wrong to begin with, but that is somewhat off-topic.

So: why does `perm[NaN]` work on dart2js?

And then the next question would be: what about the code is wrong compared to the Java equivalent? The code is ported from Java, where `L` longs are used. However, `int`s in Dart should also be 64 bit, so I am confused.

**Comment by creativecreatorormaybenot** [comment]
So I am not sure if it is helpful for this issue, but this is the Java reference: https://github.com/KdotJPG/OpenSimplex2/blob/a186b9bb644747c936d7cba748d11f28b1cee66e/java/OpenSimplex2S.java#L33

**Comment by vsmenon** [comment]
> So: why does perm[NaN] work on dart2js?

I think that is a bug in a dart2js optimization, but we'll need to investigate more.

> However, ints in Dart should also be 64 bit, so I am confused.

Not exactly.  They are platform dependent due to JS / browser limitations:

https://dart.dev/guides/language/numbers

There are some suggestions at the end of that article (e.g., `fixnum`) that trade off some performance for exact 64-bit semantics.

**Comment by creativecreatorormaybenot** [comment]
@vsmenon Thanks you. I guess I missed that `int` is only:

> 64-bit signed two’s complement

On native but not on web it is floating point. That is unfortunate. There are two steps of follow-up for me here:

1. Confirm that my code really is working on desktop (without getting `Infinity` on the seed).
2. Find out if I can get a workaround for web by checking all long occurences in the Java code again.

**Comment by creativecreatorormaybenot** [comment]
@vsmenon I was able to confirm:

1. On native (desktop/mobile), the code never produces `Infinity`, so it is only a JS problem to begin with.


However, unfortunately `fixnum` **also does not work** on web. See the issue I created: https://github.com/dart-lang/fixnum/issues/84

So currently, there seems to be _no way_ in Dart that allows me to write that code and make it work on web :/  
The only potential solutions I can come up with are either trying to implement `Int64` correctly myself on web (which I will not be able to do) or come up with a different seeding algorithm (which I will not be able to do either).

**Comment by vsmenon** [comment]
Closing here.  I'll reply on the other.

**Comment by creativecreatorormaybenot** [comment]
Makes sense @vsmenon. Will the dart2js vs. DDC inconsistency regarding the list `[]`?

**Comment by vsmenon** [comment]
Oh, thanks for the reminder.  Let me reopen this issue to focus on thiat.

**Comment by vsmenon** [comment]
Per my comment above, it looks like dart2js is eliding the more thorough range check in this example and allowing `NaN` as an index.
