### ISSUE TITLE
CFE tool fails to generate-experimental-flags

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#46860]
```
$ pkg/front_end/tool/fasta generate-experimental-flags
Unhandled exception:
type 'Null' is not a subtype of type 'bool'
#0      generateCfeFile (file:///Users/athom/src/sdk/pkg/front_end/tool/_fasta/generate_experimental_flags.dart:167:10)
#1      main (file:///Users/athom/src/sdk/pkg/front_end/tool/_fasta/generate_experimental_flags.dart:21:26)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by athomas** [comment]
Attempted a fix in https://dart-review.googlesource.com/c/sdk/+/209561/.
