### ISSUE TITLE
dart migrate issue

### ISSUE THREAD

**Issue by centuryhopper** [dart-lang/sdk#46940]
Greetings! My issue is that I cannot migrate my project to null safety using dart migrate. I have already upgraded all my packages and got rid of all non null safe packages. Here's my error:

```
[exception: FileSystemException(path=C:\tools\dart-sdk\bin\lib\_internal\sdk_library_metadata\lib\libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:184:7)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:473:41)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:371:18)
#3      ContextBuilderImpl._createSdk (package:analyzer/src/dart/analysis/context_builder.dart:157:21)
#4      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:78:15)
#5      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:65:36)        
#6      MigrationCliRunner.contextCollection (package:nnbd_migration/migration_cli.dart:492:28)
#7      MigrationCliRunner.hasMultipleAnalysisContext (package:nnbd_migration/migration_cli.dart:501:12)
#8      MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:651:9)
#9      MigrateCommand.run (package:dartdev/src/commands/migrate.dart:37:72)
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#11     DartdevRunner.runCommand (package:dartdev/dartdev.dart:202:30)
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#13     new Future.sync (dart:async/future.dart:218:31)
#14     CommandRunner.run (package:args/command_runner.dart:119:14)
#15     runDartdev (package:dartdev/dartdev.dart:54:29)
#16     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#17     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:279:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
]
[exception: FileSystemException(path=C:\tools\dart-sdk\bin\lib\_internal\libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:184:7)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:473:41)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:371:18)
#3      ContextBuilderImpl._createSdk (package:analyzer/src/dart/analysis/context_builder.dart:157:21)
#4      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:78:15)
#5      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:65:36)        
#6      MigrationCliRunner.contextCollection (package:nnbd_migration/migration_cli.dart:492:28)
#7      MigrationCliRunner.hasMultipleAnalysisContext (package:nnbd_migration/migration_cli.dart:501:12)
#8      MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:651:9)
#9      MigrateCommand.run (package:dartdev/src/commands/migrate.dart:37:72)
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#11     DartdevRunner.runCommand (package:dartdev/dartdev.dart:202:30)
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#13     new Future.sync (dart:async/future.dart:218:31)
#14     CommandRunner.run (package:args/command_runner.dart:119:14)
#15     runDartdev (package:dartdev/dartdev.dart:54:29)
#16     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#17     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:279:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
]
FileSystemException(path=C:\tools\dart-sdk\bin\version; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:184:7)
#1      FolderBasedDartSdk.languageVersion (package:analyzer/src/dart/sdk/sdk.dart:395:12)
#2      ContextBuilderImpl._createSdk (package:analyzer/src/dart/analysis/context_builder.dart:177:40)
#3      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:78:15)
#4      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:65:36)        
#5      MigrationCliRunner.contextCollection (package:nnbd_migration/migration_cli.dart:492:28)
#6      MigrationCliRunner.hasMultipleAnalysisContext (package:nnbd_migration/migration_cli.dart:501:12)
#7      MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:651:9)
#8      MigrateCommand.run (package:dartdev/src/commands/migrate.dart:37:72)
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#10     DartdevRunner.runCommand (package:dartdev/dartdev.dart:202:30)
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#12     new Future.sync (dart:async/future.dart:218:31)
#13     CommandRunner.run (package:args/command_runner.dart:119:14)
#14     runDartdev (package:dartdev/dartdev.dart:54:29)
#15     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#16     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:279:32)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

My dart version is: ```Dart SDK version: 2.14.0-383.0.dev (dev)```
Brower and OS: ```Chrome, Windows```

When I ran ```flutter analyze```, I did get a lot of errors though. Maybe that's why? But these errors seem to be null-related, which the ```dart migrate``` should take care of anyways, right? I'm not sure, so please let me know. Any help is appreciated. I can paste the errors from flutter analyze, if it helps. It's just there's 157 issues found, so it's a lot.

Thank you.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
