### ISSUE TITLE
raw_datagram_read_all_test flakily fails on generated_stress_test on Linux

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#46982]
Running generated_stress_test on linux locally fails flakily:
```
╰─➤  out/ReleaseX64/dart runtime/tests/concurrency/generate_stress_test.dart && out/ReleaseX64/dart pkg/vm/bin/gen_kernel.dart --platform=out/ReleaseX64/vm_platform_strong.dill --no-aot --no-sound-null-safety -o runtime/tests/concurrency/generated_stress_test.dart.jit.dill runtime/tests/concurrency/generated_stress_test.dart && while (out/ReleaseTSANX64/dart --disable-dart-dev --no-sound-null-safety --enable-isolate-groups runtime/tests/concurrency/generated_stress_test.dart.jit.dill); do date; done
...
Spawning tests in isolates resulted in the following errors:
------------------------------------------------------------
[$DH/sdk/runtime/tests/concurrency/../../../tests/standalone_2/io/raw_datagram_read_all_test.dart] error: [Expect.isNull(actual: <Instance of 'Datagram'>) fails., #0      Expect._fail (package:expect/expect.dart:731:5)
#1      Expect.isNull (package:expect/expect.dart:159:5)
#2      main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/aam/p/d/dart-sdk1/sdk/tests/standalone_2/io/raw_datagram_read_all_test.dart:35:18)
#3      _rootRun (dart:async/zone.dart:1420:47)
#4      _CustomZone.run (dart:async/zone.dart:1328:19)
#5      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#7      _rootRun (dart:async/zone.dart:1428:13)
#8      _CustomZone.run (dart:async/zone.dart:1328:19)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:187:12)
]
```

It looks like current wait of 1 second(which was increased couple weeks ago) to ensure that all packets make from sender to the receiver still is not very reliable.

**Comment by aam** [comment]
happened again https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8699521494937214289/+/u/collect_shards/Run_Isolate_Stress_Tests_shard_1/task_stdout_stderr:_Run_Isolate_Stress_Tests_shard_1
