### ISSUE TITLE
Compiler and formatter bug - optional semicolons inside lambda following a nullable type

### ISSUE THREAD

**Issue by ZmanElete** [dart-lang/sdk#47020]
I ran into this issue while working in flutter. Basically what happens is if the left side argument type is nullable (and explicitly stated), then a lambda somewhere in the right side argument does not need semi-colons for the compiler to successfully compile it.

my use case was more complicated by a little, but I was able to boil it down to a super simple case, and a real use case that each demonstrate the problem.
```
void main() {
  //toggle the question mark to see the problem show up and leave.
  Function? simpleLambdaBug = () {
    print(1) // MISSING SEMI COLON
  };
  simpleLambdaBug();
  realUseCase();
}


Future<void> realUseCase() async {
  String? callbackOutput = await iDoThingsThenCallBack(
    () {
      print('Callback happening') // MISSING SEMI COLON
    },
  );
}

Future<String?> iDoThingsThenCallBack(Function callback) async {
  try {
    print('Doing things');
    await Future.delayed(Duration(milliseconds: 200));
    callback();
    return 'Happy accidents';
  } catch(e) {
    return null;
  }
}
```
This will run in Dart Pad or just calling 'dart <file>'.

I noticed this issue because in VSCode I was getting auto format errors. IDK if that is useful, but here was the output I was getting
```#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:176:7)
dart-lang/language#1      generateEditsForFormatting (package:analysis_server/src/lsp/source_edits.dart:96:33)
dart-lang/language#2      FormatOnTypeHandler.formatFile (package:analysis_server/src/lsp/handlers/handler_format_on_type.dart:37:12)
dart-lang/language#3      FormatOnTypeHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_format_on_type.dart:54:37)
dart-lang/language#4      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:257:12)
dart-lang/language#5      FormatOnTypeHandler.handle (package:analysis_server/src/lsp/handlers/handler_format_on_type.dart:54:17)
dart-lang/language#6      MessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:148:12)
dart-lang/language#7      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:187:36)
dart-lang/language#8      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:302:47)
dart-lang/language#9      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:297:21)
dart-lang/language#10     _rootRun (dart:async/zone.dart:1354:13)
dart-lang/language#11     _CustomZone.run (dart:async/zone.dart:1258:19)
dart-lang/language#12     _runZoned (dart:async/zone.dart:1789:10)
dart-lang/language#13     runZonedGuarded (dart:async/zone.dart:1777:12)
dart-lang/language#14     LspByteStreamServerChannel._readMessage (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:87:16)
dart-lang/language#15     LspByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:56:24)
dart-lang/language#16     _rootRunUnary (dart:async/zone.dart:1362:47)
dart-lang/language#17     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
dart-lang/language#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
dart-lang/language#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
dart-lang/language#20     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
dart-lang/language#21     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
dart-lang/language#22     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
dart-lang/language#23     _rootRun (dart:async/zone.dart:1346:47)
dart-lang/language#24     _CustomZone.run (dart:async/zone.dart:1258:19)
dart-lang/language#25     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
dart-lang/language#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
dart-lang/language#27     _rootRun (dart:async/zone.dart:1354:13)
dart-lang/language#28     _CustomZone.run (dart:async/zone.dart:1258:19)
dart-lang/language#29     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
dart-lang/language#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
dart-lang/language#31     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
dart-lang/language#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
dart-lang/language#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
dart-lang/language#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

**Comment by bwilkerson** [comment]
This appears to be a bug in the parser.

**Comment by juniorkibirige** [comment]
Any solutions to this
