### ISSUE TITLE
Customer-reported issue with NNBD migration tool: Failed to rerun migration

### ISSUE THREAD

**Issue by Robofolk** [dart-lang/sdk#47033]
Failed to rerun migration

Error: Instance of 'MigrationExit'

Please fill in the following:

**Name of package being migrated (if public)*: private - my our code*
**What I was doing when this issue occurred**: Click the "Rerun with changes" button
**Is it possible to work around this issue**: Not every time I try, I get this error
**Has this issue happened before, and if so, how often**: At one point started happening and since then I always get it
**Dart SDK version**: 2.13.4
**Additional details**: N/A

Thanks for filing!

Stacktrace: _auto populated by migration preview tool._

```
#0      MigrationCliRunner.onException (package:nnbd_migration/migration_cli.dart:635:9)
#1      NullabilityMigrationAdapter.reportException (package:nnbd_migration/src/front_end/non_nullable_fix.dart:550:21)
#2      PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:28:18)
#3      CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#4      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#5      NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#6      NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#7      _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:19)
#8      _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1150:28)
#9      _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
<asynchronous suspension>
#10     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1150:5)
<asynchronous suspension>
#11     MigrationCliRunner._rerunFunction (package:nnbd_migration/migration_cli.dart:975:14)
<asynchronous suspension>
#12     NonNullableFix.rerun (package:nnbd_migration/src/front_end/non_nullable_fix.dart:169:17)
<asynchronous suspension>
#13     PreviewSite.rerunMigration (package:nnbd_migration/src/preview/preview_site.dart:605:22)
<asynchronous suspension>
#14     PreviewSite.handlePostRequest (package:nnbd_migration/src/preview/preview_site.dart:454:9)
<asynchronous suspension>
#15     HttpPreviewServer._handlePostRequest (package:nnbd_migration/src/preview/http_preview_server.dart:109:5)
<asynchronous suspension>
#16     HttpPreviewServer._handleServer.<anonymous closure> (package:nnbd_migration/src/preview/http_preview_server.dart:119:9)
<asynchronous suspension>

```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
