### ISSUE TITLE
enums to implement Comparable

### ISSUE THREAD

**Issue by mleonhard** [dart-lang/sdk#47080]
When enums implement [`Comparable`](https://api.dart.dev/stable/dart-core/Comparable-class.html), we can sort them and use them in sorted collections without boilerplate.

```dart
// example.dart
import 'dart:collection' show SplayTreeMap, SplayTreeSet;

enum MyEnum { One, Two }

void main() {
  final items = [MyEnum.Two, MyEnum.One];
  // Unhandled exception:
  // type 'MyEnum' is not a subtype of type 'Comparable<dynamic>' in type cast
  // #0      ListMixin._compareAny (dart:collection/list.dart:360:33)
  // #1      Sort._insertionSort (dart:_internal/sort.dart:69:36)
  // #2      Sort._doSort (dart:_internal/sort.dart:58:7)
  // #3      Sort.sort (dart:_internal/sort.dart:33:5)
  // #4      ListMixin.sort (dart:collection/list.dart:356:10)
  // #5      main (file:///example.dart:5:9)
  // #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
  // #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
  items.sort();

  // This ugly boilerplate works.
  items.sort((a, b) => a.index.compareTo(b.index));

  // type 'MyEnum' is not a subtype of type 'Comparable<dynamic>'
  // #0      _dynamicCompare (dart:collection/splay_tree.dart:279:65)
  // #1      _SplayTree._splay (dart:collection/splay_tree.dart:86:15)
  // #2      SplayTreeSet._add (dart:collection/splay_tree.dart:884:19)
  // #3      SplayTreeSet.add (dart:collection/splay_tree.dart:881:26)
  // #4      main (file:///example.dart:24:14)
  // #5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
  // #6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
  final SplayTreeSet<MyEnum> orderedSet = SplayTreeSet();
  orderedSet.add(MyEnum.One);
  orderedSet.add(MyEnum.Two);

  // This ugly boilerplate works.
  final SplayTreeSet<MyEnum> orderedSet2 =
      SplayTreeSet((a, b) => a.index.compareTo(b.index));
  orderedSet2.add(MyEnum.One);
  orderedSet2.add(MyEnum.Two);

  // Unhandled exception:
  // type 'MyEnum' is not a subtype of type 'Comparable<dynamic>'
  // #0      _dynamicCompare (dart:collection/splay_tree.dart:279:65)
  // #1      _SplayTree._splay (dart:collection/splay_tree.dart:86:15)
  // #2      SplayTreeMap.[]= (dart:collection/splay_tree.dart:408:16)
  // #3      main (file:///example.dart:22:13)
  // #4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
  // #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
  final SplayTreeMap<MyEnum, String> orderedMap = SplayTreeMap();
  orderedMap[MyEnum.One] = 'one';
  orderedMap[MyEnum.Two] = 'two';

  // This ugly boilerplate works.
  final SplayTreeMap<MyEnum, String> orderedMap2 =
      SplayTreeMap((a, b) => a.index.compareTo(b.index));
  orderedMap2[MyEnum.One] = 'one';
  orderedMap2[MyEnum.Two] = 'two';
}
```

**Comment by kevmoo** [comment]
@lrhn @munificent @leafpetersen – should this be moved to the language repo?

**Comment by lrhn** [comment]
Technically yes, enums are a language feature.
