### ISSUE TITLE
[LSP] Vs code error in LSP panel

### ISSUE THREAD

**Issue by bounty1342** [dart-lang/sdk#47097]
Hi,

I encounter this issue on VS Code. All completion resulted in error after that.

```
dart --version
Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "macos_x64"
```

```
[Error - 6:37:34 PM] Socket error: FileSystemException(path=/Users/bounty1342/Documents/work/*****/build; message=Cannot resolve symbolic links): FileSystemException(path=/Users/bounty1342/Documents/work/****/build; message=Cannot resolve symbolic links)
#0      _PhysicalFolder.resolveSymbolicLinksSync (package:analyzer/file_system/physical_file_system.dart:332:7)
#1      _OverlayResource.resolveSymbolicLinksSync (package:analyzer/file_system/overlay_file_system.dart:400:32)
#2      ContextRootImpl._includedFilesInFolder (package:analyzer/src/dart/analysis/context_root.dart:105:40)
#3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:181:26)
#4      DeclarationsContext._scheduleContextFiles (package:analyzer/src/services/available_declarations.dart:417:22)
#5      DeclarationsTracker.addContext (package:analyzer/src/services/available_declarations.dart:546:25)
#6      LspServerContextManagerCallbacks.listenAnalysisDriver (package:analysis_server/src/lsp/lsp_analysis_server.dart:806:11)
#7      ContextManagerImpl._createAnalysisContexts (package:analysis_server/src/context_manager.dart:429:17)
#8      ContextManagerImpl._handleWatchEventImpl (package:analysis_server/src/context_manager.dart:544:7)
#9      _rootRunUnary (dart:async/zone.dart:1362:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#15     _rootRunUnary (dart:async/zone.dart:1362:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#20     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
#21     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#22     _rootRunUnary (dart:async/zone.dart:1362:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#26     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#27     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#28     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#29     _rootRun (dart:async/zone.dart:1346:47)
#30     _CustomZone.run (dart:async/zone.dart:1258:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#33     _rootRun (dart:async/zone.dart:1354:13)
#34     _CustomZone.run (dart:async/zone.dart:1258:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#40     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:402:11)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by bwilkerson** [comment]
@scheglov This looks to me like a condition that ought to be caught and handled in the analyzer.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/212483
