### ISSUE TITLE
analysis_server crash (extension autocomplete)

### ISSUE THREAD

**Issue by lesnitsky** [dart-lang/sdk#47125]
analysis_server crashes with the following error

```
[Error - 8:29:05 PM] Request textDocument/completion failed.
  Message: An error occurred while handling textDocument/completion request
  Code: -32001 
[Error - 8:29:05 PM] An error occurred while handling textDocument/completion request: type 'ExtensionElementImpl' is not a subtype of type 'ClassElement'
#0      SuggestionBuilder.suggestMethod (package:analysis_server/src/services/completion/dart/suggestion_builder.dart:594:39)
#1      MemberSuggestionBuilder.addSuggestionForMethod (package:analysis_server/src/services/completion/dart/suggestion_builder.dart:86:15)
#2      ExtensionMemberContributor._addInstanceMembers (package:analysis_server/src/services/completion/dart/extension_member_contributor.dart:117:23)
#3      ExtensionMemberContributor._addExtensionMembers (package:analysis_server/src/services/completion/dart/extension_member_contributor.dart:108:9)
#4      ExtensionMemberContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/extension_member_contributor.dart:89:7)
#5      DartCompletionManager.computeSuggestions.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_manager.dart:157:31)
#6      DartCompletionManager.computeSuggestions.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_manager.dart:156:11)
#7      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:160:29)
#8      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:154:27)
<asynchronous suspension>
#9      CompletionHandler._getServerDartItems.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:224:35)
<asynchronous suspension>
#10     CompletionPerformance.runRequestOperation.<anonymous closure> (package:analysis_server/src/services/completion/completion_performance.dart:63:16)
<asynchronous suspension>
#11     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:160:14)
<asynchronous suspension>
#12     CompletionHandler._getServerDartItems (package:analysis_server/src/lsp/handlers/handler_completion.dart:199:12)
<asynchronous suspension>
#13     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#14     CompletionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:110:11)
<asynchronous suspension>
#15     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:187:22)
<asynchronous suspension>
#16     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:302:26)
<asynchronous suspension>
```

## Steps to reproduce

* `git clone git@github.com:lesnitsky/microfrontends.git`
* install pub deps
* open `example/lib/main.dart`
* on line 22 type `context.`

analysis_server crashes after `.` is pressed

Unfortunately, I was not able to reproduce the same issue in a sandbox with as little code as possible, reproducing it in a repo mentioned above is very simple and shouldn't take much time

### Flutter version

```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (10 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

### DartCode version

`v3.26.0`

**Comment by bwilkerson** [comment]
The stack trace doesn't correspond to the current source code so it's a little hard to know for sure just by looking at the code,
but it appears that the fix for this issue was committed on 4/8 as part of https://dart-review.googlesource.com/c/sdk/+/194543. I don't know which version of the SDK first included that change, but it seems unlikely to me that it wouldn't be in a build from 7/1.

Unfortunately, I'm not able to clone your package. I get the following:
```
Cloning into 'microfrontends'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by lesnitsky** [comment]
do you have ssh key added to gh? you can try to clone the repo with `git clone https://github.com/lesnitsky/microfrontends.git`

**Comment by bwilkerson** [comment]
It appears that I don't have an ssh key, but I was able to clone the repo.

I was not able to reproduce the bug in either VS Code nor IntelliJ. Both correctly showed completions without crashing. I'm using a version of the SDK built from master a couple of workdays ago.

**Comment by lesnitsky** [comment]
Not reproducible on flutter v2.5 🎉
