### ISSUE TITLE
analyzer crashes on (const expression with) constructor call with function typed type arg with parameter with default

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#47134]
See example:

```dart
class C<T> {
  const C();
}

class D<T> {
  const D();

  m() {
    const z = C<void Function([int x = 111])>();
  }
}
```

crashes with:

```none
Unhandled exception:
Bad state: No type: 111
#0      ExpressionExtension.typeOrThrow (package:analyzer/src/dart/ast/extensions.dart:88:7)
#1      CodeChecker.checkAssignment (package:analyzer/src/task/strong/checker.dart:86:35)
#2      CodeChecker.visitDefaultFormalParameter (package:analyzer/src/task/strong/checker.dart:278:7)
#3      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:2945:15)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
#5      FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4435:17)
#6      RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:897:10)
#7      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4431:50)
#8      GenericFunctionTypeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5312:17)
#9      RecursiveAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:957:10)
#10     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5305:20)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
#12     TypeArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9954:16)
#13     RecursiveAstVisitor.visitTypeArgumentList (package:analyzer/dart/ast/visitor.dart:1288:10)
#14     TypeArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9950:50)
#15     TypeNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10073:21)
#16     RecursiveAstVisitor.visitTypeName (package:analyzer/dart/ast/visitor.dart:1294:10)
#17     TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10068:50)
#18     ConstructorNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2687:11)
#19     RecursiveAstVisitor.visitConstructorName (package:analyzer/dart/ast/visitor.dart:765:10)
#20     ConstructorNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:2683:50)
#21     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6058:22)
#22     CodeChecker.visitInstanceCreationExpression (package:analyzer/src/task/strong/checker.dart:362:10)
#23     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6054:15)
#24     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10418:19)
#25     CodeChecker.visitVariableDeclaration (package:analyzer/src/task/strong/checker.dart:510:10)
...
```

**Comment by srawlins** [comment]
This is quite rare, only marking as P1 because I encountered this while writing tests for const constructor tearoffs.

**Comment by srawlins** [comment]
Not legal syntax; knocking down to P2

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/212628
