### ISSUE TITLE
In non-null-safe mode, `print` crashes in some situations involving nulls returned from toString

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#47196]
Normally I wouldn't care (because non-null-safe mode is going away eventually) but in this case this is something that makes debugging code really hard since it happens in mysterious ways during `print`:

```dart
class NullToString {
  @override
  String toString() => null;
}
 
void main() {
  print(null); // prints "null"
  print(NullToString()); // prints "null" (which is interesting)
  print([NullToString()]); // crashes
}
```

The crash I got was:

```
Unhandled exception:
NoSuchMethodError: The getter 'isEmpty' was called on null.
Receiver: null
Tried calling: isEmpty
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68:5)
#1      StringBuffer.write (dart:core-patch/string_buffer_patch.dart:65:13)
#2      StringBuffer.writeAll (dart:core-patch/string_buffer_patch.dart:102:7)
#3      IterableBase.iterableToFullString (dart:collection/iterable.dart:268:14)
#4      ListBase.listToString (dart:collection/list.dart:43:20)
#5      List.toString (dart:core-patch/growable_array.dart:496:33)
#6      print (dart:core/print.dart:9:24)
#7      main (file:///home/ianh/dev/scratch/test.dart:9:3)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

You get something similar with `stdout.write`:

```dart
import 'dart:io';

class NullToString {
  @override
  String toString() => null;
}

void main() {
  stdout.write(NullToString()); // crash
}
```

...crashes with:

```
Invalid argument(s)
#0      _StringBase._interpolateSingle (dart:core-patch/string_patch.dart:833:7)
#1      _IOSinkImpl.write (dart:io/io_sink.dart:267:27)
#2      _StdSink.write (dart:io/stdio.dart:315:11)
#3      main (file:///home/ianh/dev/scratch/test.dart:9:10)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by lrhn** [comment]
Sounds reasonable. The `toString` method has never been allowed to return `null`. Some kind of error is expected, and since this is a null soundness error, any kind of error can happen in code which assumes soundness - which null safe code should.

The error message could be more on-point, but it's hard without adding otherwise unnecessary overhead.

In the first example, the code is failing in the code:
```dart
    String str = obj.toString();
    if (str.isEmpty) return;
```
I definitely don't want to add extra null checking in all code like that. We can, it would be:
```dart
  String str = checkNonNullable(obj.toString());
```
but we have generally chosen to not do that unless continuing with a `null` value might end up doing something *wrong*.
Throwing a different error is fine.

In the last example, the lines throwing it is:
```dart
    final s = o.toString();
    if (s is! String) {
      throw new ArgumentError(s);
    }
```
We could make the error `ArgumentError.value(o, null, "Returns null from toString");` instead.

(The `is! String` is overkill these days, `== null` is enough, and would even trigger an "unnecessary test" warning since this is null safe code).

The fact that `print(NullToString())` *works* is actually an argument for a missing check. It too should throw if the object's `toString` returns null. The initial call to `toString` in `print` is never checked again.

**Comment by lrhn** [comment]
I've added an extra null-safety check to `print`. It should now throw on `print(NullToString())`.

**Comment by rakudrama** [comment]
I program defensively around this problem and almost never call `e.toString()`.
I use the shorter interpolation `'$e'` instead.
Interpolation already throws if the result of calling `e.toString()` is not a String.

Instead of adding a check, I suggest
 - changing the `.toString()` to interpolation in `print` and `writeAll` (VM, web already does here).
 - making interpolation errors more descriptive to help identify _which_ `toString` method is to blame,

I have a [CL to test these changes](https://dart-review.googlesource.com/c/sdk/+/214741).

---
There are helper methods in the runtimes that do single-element interpolations (VM one is called `interpolateSingle`, dart2js `S`, and DDC `str`). These methods are understood by the compilers to some degree. With sound null-safety, the compilers should be able to tell trivially that `o.toString()` does not return `null`, and remove the check.

 **dart2js** will reduce a single interpolation to a call to `e.toString()` if it can determine that the `toString()` methods reachable by that interpolation site can not return `null`. Since there are many interpolation sites in a program, as a program becomes more migrated, this will happen in more places.

I generally dislike `checkNotNullable` since it is too big for dart2js to inline, and a call with three parameters (including the type) is much expensive than `(o as dynamic) == null`, which would be optimized if the compiler can tell `o` cannot be not `null`.
