### ISSUE TITLE
Using `??` on `Never` causes the compiler to crash

### ISSUE THREAD

**Issue by miDeb** [dart-lang/sdk#47223]
Consider this code:
```dart
void main() {
  (throw "some value") ?? "some other value";
}
```

Compiling it crashes with the following error:
<details>
<summary>
Error
</summary>

```plaintext
Null check operator used on a null value
#0      InferenceVisitor.visitIfNullExpression (package:front_end/src/fasta/kernel/inference_visitor.dart:1387:16)
#1      IfNullExpression.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:920:20)
#2      TypeInferrerImpl._inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1951:27)
#3      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1988:40)
#4      InferenceVisitor.visitExpressionStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:921:49)
#5      ExpressionStatement.accept (package:kernel/ast.dart:8485:43)
#6      TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3884:24)
#7      InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:487:20)
#8      InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:508:31)
#9      Block.accept (package:kernel/ast.dart:8541:43)
#10     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3884:24)
#11     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:2033:39)
#12     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1122:43)
#13     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:992:19)
#14     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:358:5)
#15     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3055:14)
#16     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2831:14)
#17     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:522:14)
#18     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#19     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:499:14)
<asynchronous suspension>
#20     Loader.buildBodies (package:front_end/src/fasta/loader.dart:296:9)
<asynchronous suspension>
#21     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:370:7)
<asynchronous suspension>
#22     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#23     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:19)
<asynchronous suspension>
#24     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#25     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:51:12)
<asynchronous suspension>
#26     generateKernel (package:front_end/src/kernel_generator_impl.dart:50:10)
<asynchronous suspension>
#27     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:97:11)
<asynchronous suspension>
#28     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:398:11)
<asynchronous suspension>
#29     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#30     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:879:37)
<asynchronous suspension>


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:996:7)
#1      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:358:5)
#2      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3055:14)
#3      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2831:14)
#4      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:522:14)
#5      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#6      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:499:14)
<asynchronous suspension>
#7      Loader.buildBodies (package:front_end/src/fasta/loader.dart:296:9)
<asynchronous suspension>
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:370:7)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:19)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:51:12)
<asynchronous suspension>
#13     generateKernel (package:front_end/src/kernel_generator_impl.dart:50:10)
<asynchronous suspension>
#14     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:97:11)
<asynchronous suspension>
#15     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:398:11)
<asynchronous suspension>
#16     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#17     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:879:37)
<asynchronous suspension>
```
</details>

Dart version:
`Dart SDK version: 2.15.0-96.0.dev (dev) (Fri Sep 10 02:32:22 2021 -0700) on "linux_x64"`

**Comment by miDeb** [comment]
The same error happens when using the `??=` operator:
```dart
void main() {
  (throw "some value").foo ??= "foo";
}
```
