### ISSUE TITLE
webdev serve broken with current dev build of Dart SDK on Linux

### ISSUE THREAD

**Issue by maks** [dart-lang/sdk#47238]
I have the current dev sdk installed via apt:
```
dart --version
Dart SDK version: 2.15.0-108.0.dev (dev) (Unknown timestamp) on "linux_x64"
```

Both before and after updating to latest version, I did:
```
dart pub global activate webdev
dart pub global activate devtools

dart create  -t web-simple dart_webdev
cd dart_webdev
webdev serve
```

But got this error output:
```
[SEVERE] Could not find a command named "/usr/lib/dart/bin/snapshots/pub.dart.snapshot".
[SEVERE] 
[SEVERE] Usage: dart <command|dart-file> [arguments]
[SEVERE] 
[SEVERE] Global options:
[SEVERE] -h, --help                 Print this usage information.
[SEVERE] -v, --verbose              Show additional command output.
[SEVERE]     --version              Print the Dart SDK version.
[SEVERE]     --enable-analytics     Enable analytics.
[SEVERE]     --disable-analytics    Disable analytics.
[SEVERE] 
[SEVERE] Available commands:
[SEVERE]   analyze   Analyze Dart code in a directory.
[SEVERE]   compile   Compile Dart to various formats.
[SEVERE]   create    Create a new Dart project.
[SEVERE]   fix       Apply automated fixes to Dart source code.
[SEVERE]   format    Idiomatically format Dart source code.
[SEVERE]   migrate   Perform null safety migration on a project.
[SEVERE]   pub       Work with packages.
[SEVERE]   run       Run a Dart program.
[SEVERE]   test      Run tests for a project.
[SEVERE] 
[SEVERE] Run "dart help <command>" for more information about a command.
[SEVERE] See https://dart.dev/tools/dart-tool for detailed documentation.
Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup.<anonymous closure> (package:build_daemon/client.dart:79:21)
#1      _runUserCode (dart:async/stream_pipe.dart:11:23)
#2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1338:9)
#3      _RootZone.runGuarded (dart:async/zone.dart:1608:10)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#7      _SyncBroadcastStreamController._sendDone.<anonymous closure> (dart:async/broadcast_stream_controller.dart:400:22)
#8      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:323:15)
#9      _SyncBroadcastStreamController._sendDone (dart:async/broadcast_stream_controller.dart:399:7)
#10     _BroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:269:5)
#11     _AsBroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:505:27)
#12     _RootZone.runGuarded (dart:async/zone.dart:1608:10)
#13     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
#14     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
#15     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#16     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#17     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#18     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#19     _LineSplitterSink.close (dart:convert/line_splitter.dart:135:11)
#20     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#21     _RootZone.runGuarded (dart:async/zone.dart:1608:10)
#22     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
#23     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
#24     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#25     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#26     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#27     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#28     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
#29     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
#30     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#31     _RootZone.runGuarded (dart:async/zone.dart:1608:10)
#32     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
#33     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
#34     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#35     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:741:19)
#36     _StreamController._closeUnchecked (dart:async/stream_controller.dart:596:7)
#37     _StreamController.close (dart:async/stream_controller.dart:589:5)
#38     _Socket._onData (dart:io-patch/socket_patch.dart:2197:21)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1620:10)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#43     _StreamController._add (dart:async/stream_controller.dart:607:7)
#44     _StreamController.add (dart:async/stream_controller.dart:554:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1733:35)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1210:18)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)

```

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/build/issues/3177. I am not totally sure on the status here, I think it hasn't been released yet. @annagrin can probably provide a status update?

**Comment by annagrin** [comment]
Thanks you @maks for reporting! Will be fixed after I publish this one: https://github.com/dart-lang/webdev/pull/1412

**Comment by annagrin** [comment]
published webdev 2.7.6 that solves the issue.

**Comment by annagrin** [comment]
@maks please let me know if this resolved your issue.

**Comment by maks** [comment]
@annagrin thank you for fixing this so quickly! 🙏🏻 
Yes can confirm that I updated to `2.7.6` and it does fix this problem.  👍🏻
