### ISSUE TITLE
package:analyzer type '_InvalidCollectionElement' is not a subtype of type 'Expression' in type cast

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#47242]
Original report in pana: https://github.com/dart-lang/pana/issues/914

This can occur in the latest `package:analyzer`'s parsing of the problematic file. One smaller example I've found is in the following repository: https://gitlab.com/goldenm-software/open-source-libraries/wialon-sdk-dart in the `lib/sdk.dart` file.

```
Error:
    type '_InvalidCollectionElement' is not a subtype of type 'Expression' in type cast

Stack:
    #0      StackImpl.popList (package:_fe_analyzer_shared/src/parser/stack_listener.dart:578:25)
    #1      AstBuilder.popTypedList (package:analyzer/src/fasta/ast_builder.dart:3686:11)
    #2      AstBuilder.handleLiteralList (package:analyzer/src/fasta/ast_builder.dart:3017:22)
    #3      Parser.parseLiteralListSuffix (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5524:14)
    #4      Parser.parseLiteralListSetMapOrFunction (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5675:12)
    #5      Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5338:14)
    #6      Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5195:12)
    #7      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4784:13)
    #8      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4725:13)
    #9      Parser.parseArgumentsRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6239:15)
    #10     Parser.parseArguments (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6211:12)
    #11     Parser.parseArgumentsOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6192:14)
    #12     Parser.parseSend (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6171:13)
    #13     Parser.parseSendOrFunctionLiteral (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5723:12)
    #14     Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5288:14)
    #15     Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5195:12)
    #16     Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4784:13)
    #17     Parser._parsePrecedenceExpressionLoop (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4833:17)
    #18     Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4802:12)
    #19     Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4725:13)
    #20     Parser.parseExpressionStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4690:13)
    #21     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6579:16)
    #22     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4486:14)
    #23     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4476:20)
    #24     Parser.parseBlock (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6972:15)
    #25     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4497:14)
    #26     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4476:20)
    #27     Parser.parseIfStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6670:13)
    #28     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4513:14)
    #29     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4476:20)
    #30     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4381:15)
    #31     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3910:15)
    #32     Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3723:15)
    #33     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3382:15)
    #34     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1999:13)
    #35     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1957:14)
    #36     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
    #37     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
    #38     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
    #39     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:195:32)
    #40     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:191:12)
    #41     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:597:23)
    #42     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:403:12)
    #43     FileState._getUnlinkedBytes (package:analyzer/src/dart/analysis/file_state.dart:542:16)
    #44     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:447:17)
    #45     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:858:12)
    #46     FileTracker.getFile (package:analyzer/src/dart/analysis/file_tracker.dart:151:21)
    #47     AnalysisDriver.parseFileSync2 (package:analyzer/src/dart/analysis/driver.dart:1237:35)
    #48     AnalysisSessionImpl.getParsedUnit2 (package:analyzer/src/dart/analysis/session.dart:147:20)
```

**Comment by srawlins** [comment]
CC @scheglov

**Comment by insertjokehere** [comment]
I've suddenly started seeing this today in one of the code bases I maintain - Analysis Server constantly crashes. Was there any indication of what type of malformed file triggers this?

**Comment by bwilkerson** [comment]
@jensjoha

**Comment by jensjoha** [comment]
`_InvalidCollectionElement` was deleted in 3f5a8893785ac665756c3d1cec05c4ea4a9c51c5 so I'm gussing theres nothing to do.
