### ISSUE TITLE
dart2js crash on co19 test

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#47281]
The following [co19 test](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Constructor-tear-offs/mixin_A01_t01.dart) produces CRASH on dart2js. Output is
```
stdout:
tests/co19/src/LanguageFeatures/Constructor-tear-offs/mixin_A01_t01.dart:42:1:
Internal Error: The compiler crashed when compiling this element.
main() {
^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Unsupported operation: Unexpected constant ConstructorTearOffConstant(C.named) (ConstructorTearOffConstant).
#0      ConstantImpactVisitor.defaultConstant (package:compiler/src/ir/impact.dart:759:5)
#1      VisitOnceConstantVisitor.visitConstructorTearOffConstant (package:kernel/visitor.dart:1041:7)
#2      _ConstantCallbackVisitor.visitConstructorTearOffConstant (package:kernel/visitor.dart:861:17)
#3      ConstructorTearOffConstant.accept (package:kernel/ast.dart:13103:42)
#4      VisitOnceConstantVisitor.visitConstant (package:kernel/visitor.dart:1006:12)
#5      ImpactBuilderBase.handleConstantExpression (package:compiler/src/ir/impact.dart:683:10)
#6      StaticTypeVisitor.visitConstantExpression (package:compiler/src/ir/static_type.dart:1799:5)
#7      ConstantExpression.accept (package:kernel/ast.dart:8188:44)
#8      StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:78:18)
#9      StaticTypeVisitor.visitFunctionInvocation (package:compiler/src/ir/static_type.dart:997:32)
#10     FunctionInvocation.accept (package:kernel/ast.dart:5678:44)
#11     StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:78:18)
#12     StaticTypeVisitor._processLocalVariable (package:compiler/src/ir/static_type.dart:1781:24)
#13     StaticTypeVisitor.visitVariableDeclaration (package:compiler/src/ir/static_type.dart:1791:5)
#14     VariableDeclaration.accept (package:kernel/ast.dart:10282:43)
#15     StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:78:18)
#16     StaticTypeVisitor.visitBlock (package:compiler/src/ir/static_type.dart:1311:22)
#17     Block.accept (package:kernel/ast.dart:8736:43)
#18     StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:78:18)
#19     StaticTypeVisitor.visitProcedure (package:compiler/src/ir/static_type.dart:1735:5)
#20     Procedure.accept (package:kernel/ast.dart:3036:40)
#21     KernelToElementMapImpl.computeWorldImpact (package:compiler/src/kernel/element_map_impl.dart:1437:12)
#22     KernelWorkItem.run.<anonymous closure>.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:403:47)
#23     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#24     KernelWorkItem.run.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:402:28)
#25     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#26     KernelWorkItem.run (package:compiler/src/kernel/kernel_strategy.dart:377:26)
#27     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:574:70)
#28     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#29     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:574:32)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#31     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:572:28)
#32     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:863:15)
#33     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:570:18)
#34     ResolutionEnqueuer._forEach (package:compiler/src/enqueue.dart:449:12)
#35     ResolutionEnqueuer.forEach (package:compiler/src/enqueue.dart:465:5)
#36     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:566:16)
#37     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#38     Compiler.emptyQueue (package:compiler/src/compiler.dart:565:14)
#39     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:591:7)
#40     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#41     Compiler.processQueue (package:compiler/src/compiler.dart:584:14)
#42     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:403:5)
#43     Compiler.compileFromKernel.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:516:17)
#44     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#45     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:515:44)
#46     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#47     Compiler.compileFromKernel (package:compiler/src/compiler.dart:514:14)
#48     Compiler.runInternal (package:compiler/src/compiler.dart:321:15)

<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dart2js-hostasserts-strong-linux-x64-chrome --dart2js-batch co19/LanguageFeatures/Constructor-tear-offs/mixin_A01_t01
```

**Comment by devoncarew** [comment]
@sigmundch - who's the right owner for this?

**Comment by rakudrama** [comment]
Fixed by 81839ddcc1b.
