### ISSUE TITLE
[vm][ffi] FfiNative failure on precomp

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#47301]
```
FAILED: dartkp-dart_precompiled debug_x64 ffi/vmspecific_ffi_native_test
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 02.000628s):
DART_CONFIGURATION=DebugX64 /usr/local/google/home/dacoharkes/master/sdk/pkg/vm/tool/gen_kernel --aot --platform=out/DebugX64/vm_platform_strong.dill -o /usr/local/google/home/dacoharkes/master/sdk/out/DebugX64/generated_compilations/custom-configuration-4/tests_ffi_vmspecific_ffi_native_test/out.dill /usr/local/google/home/dacoharkes/master/sdk/tests/ffi/vmspecific_ffi_native_test.dart --packages=/usr/local/google/home/dacoharkes/master/sdk/.packages -Ddart.vm.product=false

exit code:
0

--- Command "precompiler" (took 12.000884s):
DART_CONFIGURATION=DebugX64 out/DebugX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/usr/local/google/home/dacoharkes/master/sdk/out/DebugX64/generated_compilations/custom-configuration-4/tests_ffi_vmspecific_ffi_native_test/out.S --ignore-unrecognized-flags --packages=/usr/local/google/home/dacoharkes/master/sdk/.packages /usr/local/google/home/dacoharkes/master/sdk/out/DebugX64/generated_compilations/custom-configuration-4/tests_ffi_vmspecific_ffi_native_test/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 8ms):
DART_CONFIGURATION=DebugX64 rm /usr/local/google/home/dacoharkes/master/sdk/out/DebugX64/generated_compilations/custom-configuration-4/tests_ffi_vmspecific_ffi_native_test/out.dill

exit code:
0

--- Command "assemble" (took 891ms):
DART_CONFIGURATION=DebugX64 gcc -m64 -shared -nostdlib -o /usr/local/google/home/dacoharkes/master/sdk/out/DebugX64/generated_compilations/custom-configuration-4/tests_ffi_vmspecific_ffi_native_test/out.aotsnapshot /usr/local/google/home/dacoharkes/master/sdk/out/DebugX64/generated_compilations/custom-configuration-4/tests_ffi_vmspecific_ffi_native_test/out.S

exit code:
0

--- Command "remove_assembly" (took 7ms):
DART_CONFIGURATION=DebugX64 rm /usr/local/google/home/dacoharkes/master/sdk/out/DebugX64/generated_compilations/custom-configuration-4/tests_ffi_vmspecific_ffi_native_test/out.S

exit code:
0

--- Command "vm" (took 52ms):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart_precompiled_runtime --ignore-unrecognized-flags --packages=/usr/local/google/home/dacoharkes/master/sdk/.packages /usr/local/google/home/dacoharkes/master/sdk/out/DebugX64/generated_compilations/custom-configuration-4/tests_ffi_vmspecific_ffi_native_test/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <314159>, actual: <0>) fails.
#0      Expect._fail (package:expect/expect.dart:731)
#1      Expect.equals (package:expect/expect.dart:132)
#2      main (file:///usr/local/google/home/dacoharkes/master/sdk/tests/ffi/vmspecific_ffi_native_test.dart:126)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

--- Re-run this test:
python3 tools/test.py -m debug -c dartk,dartkp ffi/vmspecific_ffi_native_test
[03:17 | 100% | + 1149 | -    1]
```

On 091338d7a3359f60d0acff7b9972c839b90600ed.

Failing on all precompiled bots:
https://dart-ci.firebaseapp.com/current_results/#/filter=ffi
![image](https://user-images.githubusercontent.com/3601775/135061760-73c03146-122a-423a-915f-368f8f69fab1.png)
 
@cskau-g is this not supported in precomp mode yet? If so, can we status-file ignore these for now so that they don't show up in test.py runs?

**Comment by cskau-g** [comment]
I believe this is a dup. of https://github.com/dart-lang/sdk/issues/47224.
Should be fixed now.
