### ISSUE TITLE
Unable to load DynamicLibrary, No such file or directory

### ISSUE THREAD

**Issue by azan-n** [dart-lang/sdk#47328]
Hello there,
I'm following the pattern in the [hello_world sample](https://github.com/dart-lang/samples/blob/master/ffi/hello_world/hello.dart) in the ffi samples for a simple application. The hello_wrold application runs successfully.
```
dart --version
Dart SDK version: 2.15.0-116.0.dev (dev) (Thu Sep 16 09:47:01 2021 -0700) on "linux_x64"

```

My application is structured as follows:

> /bin
> ---c_ffi_first.dart
> /dylibs
> ---hellolib.so 
> /lib
> pubspec.yaml

I think it might be related to this [issue](https://github.com/dart-lang/sdk/issues/39954#issue-544143910) but I am relatively new to Dart and have found no convincing answers yet. I have yet to venture into mapping functions and calling them, I can't seem to get past loading my library.

```
//c_ffi_first.dart
import 'dart:ffi';
import 'dart:io';
import 'package:path/path.dart' as p;

void main() {
  var libPath = p.join(Directory.current.path, 'dylibs', 'mylib.so');
  //printing directory contents to make sure they are accessible by the VM
  print(Directory(libPath).parent.listSync());
  //loading dynamic library
  final dyLib = DynamicLibrary.open(libPath);
}
```
The following stdout is produced after I execute `dart run`:
```
Building package executable... 
Built c_ffi_first:c_ffi_first.
[File: '/home/zues/Desktop/c_ffi_first/dylibs/mylib.so']
Unhandled exception:
Invalid argument(s): Failed to load dynamic library '/home/zues/Desktop/c_ffi_first/dylibs/mylib.so': /home/zues/Desktop/c_ffi_first/dylibs/mylib.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      main (file:///home/zues/Desktop/c_ffi_first/bin/c_ffi_first.dart:9:32)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
So even though the file is accessible, the function throws an exception which is beyond me. It doesn't seem to be the issue of permissions as I've set adequate permissions on the file. I am following the same structure as the hello_world example **however**, I notice that in the hello_world sample, `libhello.so` is a Link to `libhello.so.1` which (also a link) then links to `libhello.so.1.0.0`. I am unaware of this pattern and find it rather cumbersome. Please help me proceed with linking my library.

Edit: In the hello_world sample, changing the libraryPath variable from 
`var libraryPath = path.join(Directory.current.path, 'hello_library', 'libhello.so');`
to
`var libraryPath = path.join(Directory.current.path, 'hello_library', 'libhello.so.1.0.0');`
produces the same results.

**Comment by azan-n** [comment]
I've solved the problem, it seems that I had accidentally copied the library I have cross-compiled for ARM64 into the folder leading to exception that I was thus facing. It might be of some use to give meaningful errors in this case but it is also understandable that an error of this level might not be easy to report by the system.
Thanks anyway.
