### ISSUE TITLE
Bug on dart migrate tool (typedef causing it?)

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#47371]
We have a large project here and we migrated every single module we have except the last module, the `app` module that contains our `main.dart` file. That main module also is the module that have the dependency from every other module.

Some of our already migrate modules are using the new feature, `typedefs for non function types` available in flutter >=2.13.
If you pay attention to the log, it mentions the `MoneyCents` wich is a `typedef MoneyCents = int;` inside our `core` module. 

After running `dart migrate --skip-import-check` this exception occurs:

```
Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.14.2) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

NoSuchMethodError: The getter 'library' was called on null.
Receiver: null
Tried calling: library at offset 572 in C:\path_to_the_project\lib\logic\home_bloc.dart (MoneyCents)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
#1      Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:375:40)
#2      Variables.decoratedElementType (package:nnbd_migration/src/variables.dart:97:9)
#3      EdgeBuilder.visitTypeName (package:nnbd_migration/src/edge_builder.dart:1869:41)
#4      TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10061:50)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2296:24)
#6      EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1418:9)
#7      GeneralizingAstVisitor.visitFormalParameter (package:analyzer/dart/ast/visitor.dart:312:52)
#8      GeneralizingAstVisitor.visitNormalFormalParameter (package:analyzer/dart/ast/visitor.dart:465:7)
#9      GeneralizingAstVisitor.visitSimpleFormalParameter (package:analyzer/dart/ast/visitor.dart:517:7)
#10     SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:8669:15)
#11     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2296:24)
#12     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1418:9)
#13     GeneralizingAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:315:60)
#14     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4406:50)
#15     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2296:24)
#16     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1418:9)
#17     GeneralizingAstVisitor.visitTypeAnnotation (package:analyzer/dart/ast/visitor.dart:576:50)
#18     GeneralizingAstVisitor.visitGenericFunctionType (package:analyzer/dart/ast/visitor.dart:363:7)
#19     GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5314:20)
#20     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2296:24)
#21     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1418:9)
#22     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:137:48)
#23     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:235:44)
#24     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:205:7)
#25     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:444:7)
#26     GeneralizingAstVisitor.visitTypeAlias (package:analyzer/dart/ast/visitor.dart:574:40)
#27     GeneralizingAstVisitor.visitGenericTypeAlias (package:analyzer/dart/ast/visitor.dart:366:54)
#28     GenericTypeAliasImpl.accept (package:analyzer/src/dart/ast/ast.dart:5403:20)
#29     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2296:24)
#30     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1418:9)
#31     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#32     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#33     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#34     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#35     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2060:50)
#36     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:231:12)
#37     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:16)
#38     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1092:20)
#39     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1090:28)
#40     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1024:26)
<asynchronous suspension>
#41     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1090:5)
<asynchronous suspension>
#42     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:697:24)
<asynchronous suspension>
#43     MigrateCommand.run (package:dartdev/src/commands/migrate.dart:37:7)
<asynchronous suspension>
#44     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#45     DartdevRunner.runCommand (package:dartdev/dartdev.dart:202:18)
<asynchronous suspension>
#46     runDartdev (package:dartdev/dartdev.dart:54:16)
<asynchronous suspension>
#47     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

And this is my flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [versÃ£o 10.0.19043.1237], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] Connected device (3 available)

• No issues found!
```

**Comment by novas1r1** [comment]
Hi @shinayser,
I ran into the same issue today. Did you find any way around this or better: a fix?

For me it's probably not related to typedefs, since I don't use them.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.17763.2686], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 4.2)
[√] Android Studio
[√] VS Code (version 1.65.2)
[√] Connected device (2 available)
[√] HTTP Host Availability
```

Best regards

**Comment by shinayser** [comment]
Yes. We removed our typedefs. Then we migrate the test of the app.

Only after the num safety was entirely migrated, we then added back our typedefs.

**Comment by stereotype441** [comment]
Unassigning myself because I'm not actively working on the migration tool right now.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
