### ISSUE TITLE
standalone/io/socket_source_address_test broke on Windows

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#47522]
Introduced with https://dart-review.googlesource.com/c/sdk/+/217448

```
 Unhandled exception:
 SocketException: Failed to create server socket (OS Error: Unix domain sockets are not available on this operating system.), address = C:\b\s\w\ityiiczzxf\unix_socket_testd22da337/sock, port = 0
 #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:988:7)
 <asynchronous suspension>
 #1      testArguments (file:///C:/b/s/w/ir/tests/standalone/io/socket_source_address_test.dart:23:29)
 <asynchronous suspension>
 #2      main.<anonymous closure>.<anonymous closure> (file:///C:/b/s/w/ir/tests/standalone/io/socket_source_address_test.dart:160:7)
 <asynchronous suspension>
 #3      withTempDir (file:///C:/b/s/w/ir/tests/standalone/io/test_utils.dart:45:5)
 <asynchronous suspension>
 #4      main.<anonymous closure> (file:///C:/b/s/w/ir/tests/standalone/io/socket_source_address_test.dart:159:5)
 <asynchronous suspension>
 #5      retry (file:///C:/b/s/w/ir/tests/standalone/io/test_utils.dart:18:14)
 <asynchronous suspension>
 #6      main (file:///C:/b/s/w/ir/tests/standalone/io/socket_source_address_test.dart:158:3)
 <asynchronous suspension>
```

**Comment by brianquinlan** [comment]
Fixed in d0e56020f347204e02c0eaa7012b2eb3fa820934
