### ISSUE TITLE
Length property of map return wrong number when used in isolate

### ISSUE THREAD

**Issue by rebaz94** [dart-lang/sdk#47598]
Hi
I have a function to convert object to JSON string using ```JsonEncoder.withIndent``` and when I remove a property from the map and send to the ```compute``` function to encode, it will failed because it return wrong size. ```map.length``` return length - 1.
According to the [doc](https://api.flutter.dev/flutter/dart-isolate/SendPort/send.html), Map and List can be transferred to isolate 

note// using normal function without isolate work

here the example code that cause the problem

```dart
Future<void> main() async {
  final nested = {
    "name": "Rebe",
    "age": 27,
    "data": null,
    "arr": [
      {
        "key": "data",
      },
      [1, 2, 3],
    ],
    "lastObj": {
      "any": "value",
    }
  };
  final model = {
    "key": "value1",
    "key2": "value2",
    "nested": nested,
  };

  nested.remove('arr');

  final withoutIsolate = convertToPrettyJson(model);
  print(withoutIsolate);
  final withIsolate = await compute(convertToPrettyJson, model);
  print(withIsolate);
}

String convertToPrettyJson(Object? model) {
  try {
    final map = model as Map;
    print('nested Keys: ${map['nested'].keys}');
    print('nested Length: ${map['nested'].length}');
    return const JsonEncoder.withIndent(' ').convert(model);
  } catch (e, stack) {
    print(e);
    print(stack);
    rethrow;
  }
}
```

```dart
// output - normal function works
nested Keys: (name, age, data, lastObj)
nested Length: 4
{
 "key": "value1",
 "key2": "value2",
 "nested": {
  "name": "Rebe",
  "age": 27,
  "data": null,
  "lastObj": {
   "any": "value"
  }
 }
}


// inside isolate keys return 4 items but length return 3!
Shell: nested Keys: (name, age, data, lastObj)
Shell: nested Length: 3
Shell: RangeError (index): Invalid value: Not in inclusive range 0..5: 6
Shell: #0      List._setIndexed (dart:core-patch/array.dart:118:64)
Shell: #1      List.[]= (dart:core-patch/array.dart:114:5)
Shell: #2      _JsonPrettyPrintMixin.writeMap.<anonymous closure> (dart:convert/json.dart:818:19)
Shell: #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
Shell: #4      _JsonPrettyPrintMixin.writeMap (dart:convert/json.dart:814:9)
Shell: #5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:724:21)
Shell: #6      _JsonStringifier.writeObject (dart:convert/json.dart:679:9)
Shell: #7      _JsonPrettyPrintMixin.writeMap (dart:convert/json.dart:832:7)
Shell: #8      _JsonStringifier.writeJsonValue (dart:convert/json.dart:724:21)
Shell: #9      _JsonStringifier.writeObject (dart:convert/json.dart:679:9)
Shell: #10     _JsonStringStringifier.printOn (dart:convert/json.dart:877:17)
Shell: #11     _JsonStringStringifier.stringify (dart:convert/json.dart:862:5)
Shell: #12     JsonEncoder.convert (dart:convert/json.dart:262:30)

```

does I am missing something or this is expected?

Thanks

**Comment by rebaz94** [comment]
Thank you for your quick response

**Comment by mkustermann** [comment]
The bug should be fixed on the `main` branch (formerly known as `master` branch). We'll try to cherry-pick this into coming branches to be released.

**Comment by mkustermann** [comment]
Asked for a cherry-pick in https://github.com/dart-lang/sdk/issues/47639
