### ISSUE TITLE
New failures on `Add extra tests for directory renames.`

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#47636]
After adding the new `standalone_2/io/directory_rename_test` (in b2d89165399cb9f122e4f6e53464edef58bf7b1c) it seems to fail on ARM64:

The tests
```
standalone_2/io/directory_rename_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-release-arm64
dartkp-linux-release-arm64
```

@brianquinlan Could you take a look?

**Comment by brianquinlan** [comment]
Maybe I'm misreading this, but didn't this pass in the next test run and not fail after that?
https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=standalone_2/io/directory_rename_test

Should I try to revoke the failure approval?

**Comment by mkustermann** [comment]
@brianquinlan If I click on the link you provided it will show the test passing in some configurations and failing in the two configurations mentioned above. The failure has been approved with a link to this issue.

By hovering over the test name you'll be able to find access to the logs, e.g. [this log](https://dart-ci.appspot.com/log/cross-vm-linux-release-arm64/dartk-linux-release-arm64/7874/standalone_2/io/directory_rename_test):
```
--- Command "vm" (took 20.000478s):
DART_CONFIGURATION=ReleaseXARM64 out/ReleaseXARM64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/io/directory_rename_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:731:5)
#1      Expect.isTrue (package:expect/expect.dart:141:5)
#2      testRenameToExistingNonEmptyDirectory.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/directory_rename_test.dart:127:16)
#3      testRenameToExistingNonEmptyDirectory.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/directory_rename_test.dart:105:7)
#4      withTempDir.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/test_utils.dart:47:37)
#5      _rootRun (dart:async/zone.dart:1428:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _runZoned (dart:async/zone.dart:1863:10)
#8      runZonedGuarded (dart:async/zone.dart:1851:12)
#9      withTempDir (file:///b/s/w/ir/tests/standalone_2/io/test_utils.dart:47:11)
#10     testRenameToExistingNonEmptyDirectory (file:///b/s/w/ir/tests/standalone_2/io/directory_rename_test.dart:104:9)
#11     main (file:///b/s/w/ir/tests/standalone_2/io/directory_rename_test.dart:139:9)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-linux-release-arm64 standalone_2/io/directory_rename_test
```

**Comment by dcharkes** [comment]
I reapproved the failures to turn the CI green.

@brianquinlan We keep the failure approved and land a fix. When a test starts working, the approval will be automatically revoked such that the CI will turn red if the test ever starts failing again.

**Comment by derekxu16** [comment]
happened again: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-linux-release-arm64/1/overview
