### ISSUE TITLE
flutter tool cache_test.dart: Check current DevTools version test failure on hhh buildbot 

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#47687]
from https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8830778834841354241/+/u/flutter_test_tool_tests/stdout

```
 01:13 +2041 ~3: test/general.shard/cache_test.dart: Check current DevTools version                                                                                                                     
 Exception: Could not find directory at bin/cache/dart-sdk/bin/resources/devtools
 #0      Cache.devToolsVersion (package:flutter_tools/src/cache.dart:369:9)
 #1      main.<anonymous closure> (file:///b/s/w/ir/cache/builder/flutter/packages/flutter_tools/test/general.shard/cache_test.dart:898:57)
 #2      main.<anonymous closure> (file:///b/s/w/ir/cache/builder/flutter/packages/flutter_tools/test/general.shard/cache_test.dart:897:54)
 #3      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/flutter/packages/flutter_tools/test/src/context.dart:143:42)
 #4      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/flutter/packages/flutter_tools/test/src/context.dart:137:23)
 #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
 #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:7)
 #7      _rootRun (dart:async/zone.dart:1426:13)
 #8      _CustomZone.run (dart:async/zone.dart:1328:19)
 #9      _runZoned (dart:async/zone.dart:1861:10)
 #10     runZoned (dart:async/zone.dart:1783:10)
 #11     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
 #12     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/flutter/packages/flutter_tools/test/src/context.dart:132:30)
 #13     _rootRun (dart:async/zone.dart:1426:13)
 #14     _CustomZone.run (dart:async/zone.dart:1328:19)
 #15     _runZoned (dart:async/zone.dart:1861:10)
 #16     runZonedGuarded (dart:async/zone.dart:1849:12)
 #17     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/flutter/packages/flutter_tools/test/src/context.dart:130:18)
 #18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
 #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:7)
 #20     _rootRun (dart:async/zone.dart:1426:13)
 #21     _CustomZone.run (dart:async/zone.dart:1328:19)
 #22     _runZoned (dart:async/zone.dart:1861:10)
 #23     runZoned (dart:async/zone.dart:1783:10)
 #24     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
 #25     testUsingContext.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/flutter/packages/flutter_tools/test/src/context.dart:105:22)
 #26     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:82:18)
 <asynchronous suspension>
 #27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
 <asynchronous suspension>
 #28     testUsingContext.<anonymous closure> (file:///b/s/w/ir/cache/builder/flutter/packages/flutter_tools/test/src/context.dart:104:5)
 <asynchronous suspension>
 #29     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:9)
 <asynchronous suspension>
 #30     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:213:7)
 <asynchronous suspension>
 #31     Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:257:7)
 <asynchronous suspension>
 01:13 +2041 ~3 -1: test/general.shard/cache_test.dart: Check current DevTools version [E]                                                                                                              
   Exception: Could not find directory at bin/cache/dart-sdk/bin/resources/devtools
   package:flutter_tools/src/cache.dart 369:9           Cache.devToolsVersion
   test/general.shard/cache_test.dart 898:57            main.<fn>
   test/general.shard/cache_test.dart 897:54            main.<fn>
   test/src/context.dart 143:42                         testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
   test/src/context.dart 137:23                         testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
   package:flutter_tools/src/base/context.dart 150:29   AppContext.run.<fn>
   package:flutter_tools/src/base/context.dart 150:7    AppContext.run.<fn>
   dart:async                                           runZoned
   package:flutter_tools/src/base/context.dart 149:12   AppContext.run
   test/src/context.dart 132:30                         testUsingContext.<fn>.<fn>.<fn>.<fn>
   dart:async                                           runZonedGuarded
   test/src/context.dart 130:18                         testUsingContext.<fn>.<fn>.<fn>
   package:flutter_tools/src/base/context.dart 150:29   AppContext.run.<fn>
   package:flutter_tools/src/base/context.dart 150:7    AppContext.run.<fn>
   dart:async                                           runZoned
   package:flutter_tools/src/base/context.dart 149:12   AppContext.run
   test/src/context.dart 105:22                         testUsingContext.<fn>.<fn>
   package:flutter_tools/src/context_runner.dart 82:18  runInContext.runnerWrapper
   ===== asynchronous gap ===========================
   package:flutter_tools/src/base/context.dart 150:19   AppContext.run.<fn>
   ===== asynchronous gap ===========================
   test/src/context.dart 104:5                          testUsingContext.<fn>
```

**Comment by aam** [comment]
Dup of https://github.com/flutter/flutter/issues/93553
