### ISSUE TITLE
Web compiler inconsistencies on @anonymous js-interop constructors and their tear-offs

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#47765]
An `@anonymous` class constructor when called directly and when called via a tear-off produce different results:

```dart
import 'package:js/js.dart';

@JS()
@anonymous
class Item {
  external factory Item({int x = 99, int? y1, int? y2 = null, int z});
}

final tearoff = Item.new;

@JS('Object.entries')
external List entries(Item item);

main() {
  print('\n(x: 100, y1: 101, y2: 102, z: 103)');
  describe('direct', Item(x: 100, y1: 101, y2: 102, z: 103));
  describe('tearoff', tearoff(x: 200, y1: 201, y2: 202, z: 203));

  print('\n(y1: 301, y2: 302, z: 303)');
  describe('direct', Item(y1: 301, y2: 302, z: 303));
  describe('tearoff', tearoff(y1: 301, y2: 302, z: 303));

  print('\n(z:403)');
  describe('direct', Item(z:403));
  describe('tearoff', tearoff(z:403));

  print('\n()');
  describe('direct', Item());
  describe('tearoff', tearoff());
}

describe(String kind, Item item) {
  final map = entries(item).map((e) => e.join(': ')).join(', ');
  print('${kind.padRight(10)}$map');
}
```
dart2js result:
```
(x: 100, y1: 101, y2: 102, z: 103)
direct    x: 100, y1: 101, y2: 102, z: 103
tearoff   x: 200, y1: 201, y2: 202, z: 203

(y1: 301, y2: 302, z: 303)
direct    y1: 301, y2: 302, z: 303
tearoff   x: 99, y1: 301, y2: 302, z: 303

(z:403)
direct    z: 403
tearoff   x: 99, y1: null, y2: null, z: 403

()
direct    
j1.js:1154: TypeError: null: type 'JSNull' is not a subtype of type 'int'
      throw A.wrapException(A._TypeError__TypeError$forType(object, "int"));
      ^
TypeError: null: type 'JSNull' is not a subtype of type 'int'
    at Object.wrapException (j1.js:336:17)
    at Object._asInt (j1.js:1154:15)
    at Object.Item___new_tearOff (j1.js:2296:42)
    at StaticClosure.call$0 (j1.js:3072:16)
    at main (j1.js:2312:63)
    at j1.js:3333:7
    at j1.js:3312:7
    at dartProgram (j1.js:3327:5)
    at j1.js:3335:3
```

The differences are a consequence of (1) lowering the constructor tear-off to a Dart static method and (2) the dart2js calling convention that the primary entry point for a method takes all arguments, and the defaulting of arguments is done elsewhere, either (a) at the call site, (b) in a stub that adds the default arguments or (c) via `Function.apply`. By the time we get to the body of the static method that is the constructor tear-off, there is no way to know which arguments were not provided, or the order of the provided arguments.

`@anonymous` constructors are a little different to other `@JS()` `external` methods. Since they are not a description of some existing JavaScript method, but a description of a desired synthesized object, we have more freedom to make optional argument default values mean something.

Questions:

- Should default values be allowed? It does seem like a nice feature for a default value to be interpreted as a directive to provide the property with a default value. A missing default value would then interpreted as constructing an object without that property. `y1` and `y2` are therefore different in the above example.

- Should we forbid tear-offs of `@anonymous` constructors? If tear-offs are illegal, then there is no possibility for inconsistency.

Related issues: #33395, #41375

/cc @srujzs

**Comment by srujzs** [comment]
I know this is a very late response...

To address the inconsistency between direct calls and tear-offs, forbidding tear-offs is probably worthwhile. The confusion around the inconsistency outweighs the need for an external `@anonymous` factory tear-off in my opinion.

That being said, the current semantics of external `@anonymous` factories isn't entirely intuitive either. Like your example illustrates, the front-end currently allows non-null named params with no default values in null-safety for external factories, but we don't really do anything special with that. I don't really want us to do anything with it either, as that should be a bug. For both JS compilers, if arguments are passed at the invocation, we put them in the literal, and otherwise we don't, regardless of nullability or default values.

I like your solution to say that without a default value, we will exclude it. The check would be something like "if the value is null and there is no written initializer for this parameter, exclude it". It is, however, a little confusing why `int? x` and `int? x = null` are treated differently. This also avoids the discrepancies between direct calls and tear-offs. It does require a fair bit more code, however, since we need to check what values have the default value versus which ones don't, but if we put it in a declaration, that's okay.

I think we have an opportunity to do something new before Dart 3, and this might be a candidate. I'd only make any new semantics here only impact `@staticInterop` and inline classes to avoid a big breaking change.

cc @joshualitt @rileyporter
