### ISSUE TITLE
flutter hhh framework test failure

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#47760]
flutter hhh buildbot smoke_test_failure test [started](https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-engine-linux/14853/overview) to fail turning hhh buildbot red.

[Before recent change](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8829765769232981681/+/u/flutter_test_framework_tests/stdout):
```
smoke_test_failure] [STDOUT] Executing: /b/s/w/ir/cache/builder/engine/src/third_party/android_tools/sdk/platform-tools/adb devices -l in /b/s/w/ir/cache/builder/flutter/dev/devicelab with environment {BOT: true, LANG: en_US.UTF-8}
[smoke_test_failure] [STDOUT] stderr: * daemon not running; starting now at tcp:5037
[smoke_test_failure] [STDOUT] stderr: * daemon started successfully
[smoke_test_failure] [STDOUT] stdout: List of devices attached
[smoke_test_failure] [STDOUT] stdout: 
```
[After](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8829765769232981681/+/u/flutter_test_framework_tests/stdout) https://dart.googlesource.com/linear_sdk_flutter_engine/+/4174d4544d37c952317e493b9d73db729b8439f3
```
[smoke_test_failure] [STDOUT] Executing: /b/s/w/ir/cache/builder/engine/src/third_party/android_tools/sdk/platform-tools/adb devices -l in /b/s/w/ir/cache/builder/flutter/dev/devicelab with environment {BOT: true, LANG: en_US.UTF-8}
[smoke_test_failure] [STDOUT] "/b/s/w/ir/cache/builder/engine/src/third_party/android_tools/sdk/platform-tools/adb" exit code: 2
[smoke_test_failure] [STDERR] Unhandled exception:
[smoke_test_failure] [STDERR] FormatException: Missing extension byte (at offset 174)
[smoke_test_failure] [STDERR] #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1893:7)
[smoke_test_failure] [STDERR] #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
[smoke_test_failure] [STDERR] #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
[smoke_test_failure] [STDERR] #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
[smoke_test_failure] [STDERR] #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
[smoke_test_failure] [STDERR] #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
[smoke_test_failure] [STDERR] #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
[smoke_test_failure] [STDERR] #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
[smoke_test_failure] [STDERR] #8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
[smoke_test_failure] [STDERR] #9      _StreamController._add (dart:async/stream_controller.dart:607:7)
[smoke_test_failure] [STDERR] #10     _StreamController.add (dart:async/stream_controller.dart:554:5)
[smoke_test_failure] [STDERR] #11     _Socket._onData (dart:io-patch/socket_patch.dart:2302:41)
[smoke_test_failure] [STDERR] #12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
[smoke_test_failure] [STDERR] #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
[smoke_test_failure] [STDERR] #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
[smoke_test_failure] [STDERR] #15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
[smoke_test_failure] [STDERR] #16     _StreamController._add (dart:async/stream_controller.dart:607:7)
[smoke_test_failure] [STDERR] #17     _StreamController.add (dart:async/stream_controller.dart:554:5)
[smoke_test_failure] [STDERR] #18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1830:33)
[smoke_test_failure] [STDERR] #19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1314:14)
[smoke_test_failure] [STDERR] #20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
[smoke_test_failure] [STDERR] #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
[smoke_test_failure] [STDERR] #22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
[smoke_test_failure] [STDERR] #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
"/b/s/w/ir/cache/builder/flutter/bin/cache/dart-sdk/bin/dart" exit code: 255
```

**Comment by aam** [comment]
cc @garyqian for possible ideas

**Comment by aam** [comment]
Fixed by https://github.com/flutter/engine/pull/30107
