### ISSUE TITLE
HHH failing `framework tests`

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#47789]
From [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8829523052505110753/+/u/flutter_test_framework_tests/stdout) - see [build](https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-engine-linux/14878/overview)
```
═════════════════╡ ••• Running task "smoke_test_success" ••• ╞══════════════════
Executing: /b/s/w/ir/cache/builder/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --enable-vm-service=0 --no-pause-isolates-on-exit bin/tasks/smoke_test_success.dart in /b/s/w/ir/cache/builder/flutter/dev/devicelab with environment {BOT: true, LANG: en_US.UTF-8}
[smoke_test_success] [STDOUT] Observatory listening on http://127.0.0.1:40335/_UbuwDjz1JM=/
[smoke_test_success] [STDOUT] Running task with a timeout of 0:01:00.000000.
[smoke_test_success] [STDOUT] 
[smoke_test_success] [STDOUT] 
[smoke_test_success] [STDOUT] ═══════════════╡ ••• Skipping check running Dart processes ••• ╞════════════════
[smoke_test_success] [STDOUT] 
[smoke_test_success] [STDOUT] Skipping enabling configs for macOS, Linux, Windows, and Web
[smoke_test_success] [STDOUT] 
[smoke_test_success] [STDOUT] Executing: /b/s/w/ir/cache/builder/engine/src/third_party/android_tools/sdk/platform-tools/adb devices -l in /b/s/w/ir/cache/builder/flutter/dev/devicelab with environment {BOT: true, LANG: en_US.UTF-8}
[smoke_test_success] [STDOUT] "/b/s/w/ir/cache/builder/engine/src/third_party/android_tools/sdk/platform-tools/adb" exit code: 2
[smoke_test_success] [STDERR] Unhandled exception:
[smoke_test_success] [STDERR] FormatException: Missing extension byte (at offset 174)
[smoke_test_success] [STDERR] #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1893:7)
[smoke_test_success] [STDERR] #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
[smoke_test_success] [STDERR] #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
[smoke_test_success] [STDERR] #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
[smoke_test_success] [STDERR] #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
[smoke_test_success] [STDERR] #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
[smoke_test_success] [STDERR] #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
[smoke_test_success] [STDERR] #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
[smoke_test_success] [STDERR] #8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
[smoke_test_success] [STDERR] #9      _StreamController._add (dart:async/stream_controller.dart:607:7)
[smoke_test_success] [STDERR] #10     _StreamController.add (dart:async/stream_controller.dart:554:5)
[smoke_test_success] [STDERR] #11     _Socket._onData (dart:io-patch/socket_patch.dart:2302:41)
[smoke_test_success] [STDERR] #12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
[smoke_test_success] [STDERR] #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
[smoke_test_success] [STDERR] #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
[smoke_test_success] [STDERR] #15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
[smoke_test_success] [STDERR] #16     _StreamController._add (dart:async/stream_controller.dart:607:7)
[smoke_test_success] [STDERR] #17     _StreamController.add (dart:async/stream_controller.dart:554:5)
[smoke_test_success] [STDERR] #18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1830:33)
[smoke_test_success] [STDERR] #19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1314:14)
[smoke_test_success] [STDERR] #20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
[smoke_test_success] [STDERR] #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
[smoke_test_success] [STDERR] #22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
[smoke_test_success] [STDERR] #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
"/b/s/w/ir/cache/builder/flutter/bin/cache/dart-sdk/bin/dart" exit code: 255

00:43 +16 -1: test/run_test.dart: run.dart script exits with code 1 when fails [E]                                                                                                                     
  Expected: <1>
    Actual: <0>
  [ stderr from test process ]
```

Seemingly started with 
https://github.com/flutter/engine/commit/2cc81657bca7ec9b19ab97b22c00c7cc7d4216c

@GaryQian Do you think this could be caused by your commit?

**Comment by aam** [comment]
dup of https://github.com/dart-lang/sdk/issues/47760
