### ISSUE TITLE
Mixin with field triggers assert in `MoveFieldInitializers`

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#47822]
Compiling this code:
```dart
mixin M {
  int x = (() => 7)();
}

class C with M {}

main() {
  print(C().x);
}
```
with
```
DART_VM_FLAGS=--enable-asserts ./pkg/vm/tool/precompiler2 mixin_with_field_test.dart m.snapshot
```
triggers this assert:
```
'package:vm/transformations/type_flow/transformer.dart': Failed assertion: line 163 pos 12: 'constructors.isNotEmpty': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      MoveFieldInitializers.transformClass (package:vm/transformations/type_flow/transformer.dart:163:12)
#3      MoveFieldInitializers.transformComponent (package:vm/transformations/type_flow/transformer.dart:137:9)
#4      transformComponent (package:vm/transformations/type_flow/transformer.dart:63:27)
#5      runGlobalTransformations (package:vm/kernel_front_end.dart:454:20)
#6      compileToKernel (package:vm/kernel_front_end.dart:376:11)
```
Removing the assert seems harmless. It's simply not the case for mixins.

**Comment by alexmarkov** [comment]
I can confirm that it is safe to remove this assertion. We can also change it to

```
assert(constructors.isNotEmpty || cls.isMixinDeclaration);
```

in order to make sure we know what kind of class doesn't have constructors, as this transformation erases field initializers without a trace for such classes.
