### ISSUE TITLE
Failures on [ CLI / Gardening ] Wait for process to exit before cleaning up test...[infra] Remove client directory

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#47933]
There are new test failures on [[ CLI / Gardening ] Wait for process to exit before cleaning up test...[infra] Remove client directory](https://github.com/dart-lang/sdk/compare/baf56df325b2f98067432591f4eeb5a43fb6724b~...78b7fc5ac19d6c6550438aa5ecdbd19983c69c91).

The tests
```
vm/cc/IsolateReload_PendingUnqualifiedCall_StaticToInstance Crash (expected Pass)
```
are failing on configurations
```
dartk-msan-linux-release-x64
```

[Log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8827806773640438369/+/u/test_results/new_test_failures__logs_):

```
/=========================================================================================================\
| vm/cc/IsolateReload_PendingUnqualifiedCall_StaticToInstance failed again (Fail -> Crash, expected Pass) |
\=========================================================================================================/

--- Command "run_vm_unittest" (took 04.000374s):
DART_CONFIGURATION=ReleaseMSANX64 out/ReleaseMSANX64/run_vm_tests --dfe=/b/s/w/ir/cache/builder/sdk/out/ReleaseMSANX64/gen/kernel-service.dart.snapshot --ignore-unrecognized-flags IsolateReload_PendingUnqualifiedCall_StaticToInstance

exit code:
-6

stdout:
Running test: IsolateReload_PendingUnqualifiedCall_StaticToInstance

stderr:
RELOAD REPORT:
{"type":"ReloadReport","success":true,"details":{"finalLibraryCount":20,"receivedLibraryCount":0,"receivedLibrariesBytes":0,"receivedClassesCount":0,"receivedProceduresCount":0,"savedLibraryCount":18,"loadedLibraryCount":2,"shapeChangeMappings":[]}}
==16988==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x56036213f853 in std::__2::basic_ostream<char, std::__2::char_traits<char> >& std::__2::__put_character_sequence<char, std::__2::char_traits<char> >(std::__2::basic_ostream<char, std::__2::char_traits<char> >&, char const*, unsigned long) ../../out/ReleaseMSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/ostream:724:13
    #1 0x56036213ec95 in dart::Escape(std::__2::basic_ostringstream<char, std::__2::char_traits<char>, std::__2::allocator<char> >&, char const*) ../../out/ReleaseMSANX64/../../runtime/platform/assert.h
    #2 0x56036213ec95 in dart::Expect::StringEquals(char const*, char const*) ../../out/ReleaseMSANX64/../../runtime/platform/assert.h:167:5
    #3 0x560362334b02 in dart::Dart_TestHelperIsolateReload_PendingUnqualifiedCall_StaticToInstance(dart::Thread*) ../../out/ReleaseMSANX64/../../runtime/vm/isolate_reload_test.cc:1324:3
    #4 0x560362334b02 in dart::Dart_TestIsolateReload_PendingUnqualifiedCall_StaticToInstance() ../../out/ReleaseMSANX64/../../runtime/vm/isolate_reload_test.cc:1290:1
    #5 0x560362129c86 in dart::TestCase::Run() ../../out/ReleaseMSANX64/../../runtime/bin/run_vm_tests.cc:52:3
    #6 0x56036212a069 in dart::TestCaseBase::RunTest() ../../out/ReleaseMSANX64/../../runtime/bin/run_vm_tests.cc:64:11
    #7 0x560362566016 in dart::TestCaseBase::RunAll() ../../out/ReleaseMSANX64/../../runtime/vm/unit_test.cc:86:13
    #8 0x56036212ac56 in dart::Main(int, char const**) ../../out/ReleaseMSANX64/../../runtime/bin/run_vm_tests.cc:396:3
    #9 0x56036212a3a0 in main ../../out/ReleaseMSANX64/../../runtime/bin/run_vm_tests.cc:427:29
    #10 0x7fdc700bfbf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #11 0x5603620adae8 in _start (/b/s/w/ir/cache/builder/sdk/out/ReleaseMSANX64/run_vm_tests+0x3e3dae8)

SUMMARY: MemorySanitizer: use-of-uninitialized-value ../../out/ReleaseMSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/ostream:724:13 in std::__2::basic_ostream<char, std::__2::char_traits<char> >& std::__2::__put_character_sequence<char, std::__2::char_traits<char> >(std::__2::basic_ostream<char, std::__2::char_traits<char> >&, char const*, unsigned long)
Exiting

--- Re-run this test:
python3 tools/test.py -n dartk-msan-linux-release-x64 vm/cc/IsolateReload_PendingUnqualifiedCall_StaticToInstance
```

Bisected to the `assert.h` changes in 98baaa0e. Looked at the place the MSAN failure occurs, but don't see anything wrong (it's failing on an implicit `bool` conversion, but the conversion method of the converted object just returns a field that, afaict, is always initialized. Even if there is a problem there, though, we're using `std::ostringstream` correctly here.

Changing to just append to `std::string` instances instead doesn't trigger any MSAN failures, and this is an expect failure case, only used in tests, so I think it's okay to perform the less efficient version.

**Comment by dcharkes** [comment]
For reference, we have more `std` issues:

* https://github.com/dart-lang/sdk/issues/43075
* https://github.com/dart-lang/sdk/issues/47835

Cross referencing them so that if we solve one of them, we check whether it also solves the others.
