### ISSUE TITLE
Devtools 2.9.2 fails to start with exit code 255

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#47984]
Apparently my installation of the Dart devtools does not want to start up.
Yesterday everything worked.
I quickly checked in my pub cache and the previous version I had of the devtools, version `2.8.0` does have the build folder as mentioned in the logs. I think something went wrong with 2.9.2. The latest commit was 13 hours ago. https://github.com/flutter/devtools/commit/e48dfc48279e2729c29b954e159cbefd5dc58d1e

Dart Captured logs:
```
Dart Code extension: 3.29.0
Flutter extension: 3.29.0 (activated)

App: Visual Studio Code
Version: 1.63.2
Platform: mac

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /Users/navaronbracke/Documents/flutter_dev/flutter/bin/cache/dart-sdk
    Ver: 2.14.4
Flutter SDK:
    Loc: /Users/navaronbracke/Documents/flutter_dev/flutter
    Ver: 2.5.3

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, Analyzer, CommandProcesses, DartTest, DAP, VmService, DevTools, FlutterDaemon, FlutterRun, FlutterTest, WebDaemon

Tue Dec 21 2021 [08:25:28 GMT+0100 (Central European Standard Time)] Log file started
[8:25:33 AM] [General] [Info] Spawning /Users/navaronbracke/Documents/flutter_dev/flutter/bin/cache/dart-sdk/bin/dart with args ["pub","global","activate","devtools"]
[8:25:33 AM] [CommandProcesses] [Info] (PROC 1094) Logging data for process...
[8:25:33 AM] [CommandProcesses] [Info] (PROC 1094) Package devtools is currently active at version 2.9.2.
[8:25:33 AM] [CommandProcesses] [Info] (PROC 1094)
[8:25:33 AM] [CommandProcesses] [Info] (PROC 1094) Resolving dependencies...
[8:25:35 AM] [CommandProcesses] [Info] (PROC 1094) The package devtools is already activated at newest available version.
[8:25:35 AM] [CommandProcesses] [Info] (PROC 1094) 
To recompile executables, first run `global deactivate devtools`.
[8:25:35 AM] [CommandProcesses] [Info] (PROC 1094) Installed executable devtools.
[8:25:35 AM] [CommandProcesses] [Info] (PROC 1094) Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
[8:25:35 AM] [CommandProcesses] [Info] (PROC 1094) You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"$HOME/.pub-cache/bin"
[8:25:35 AM] [CommandProcesses] [Info] (PROC 1094) Activated devtools 2.9.2.
[8:25:35 AM] [CommandProcesses] [Info] (PROC 1094) exited (0, null)
[8:25:35 AM] [CommandProcesses] [Info] (PROC 1094) closed (0, null)
[8:25:35 AM] [General] [Info] Spawning /Users/navaronbracke/Documents/flutter_dev/flutter/bin/cache/dart-sdk/bin/dart with args ["pub","global","run","devtools","--machine","--try-ports","10","--allow-embedding"]
[8:25:35 AM] [General] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[8:25:35 AM] [General] [Info]     PID: 808
[8:25:35 AM] [General] [Error] Unhandled exception:
Invalid argument(s): A directory corresponding to fileSystemPath "/Users/navaronbracke/.pub-cache/hosted/pub.dartlang.org/devtools-2.9.2/build" could not be found
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      defaultHandler (package:devtools_server/src/external_handlers.dart:38:23)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:215:15)
<asynchronous suspension>
#3      serveDevToolsWithArgs (package:devtools_server/src/server.dart:73:10)
<asynchronous suspension>
[8:25:35 AM] [General] [Info] Process terminated! 255, null
[8:25:35 AM] [General] [Error] Dart DevTools exited with code 255.
[8:25:35 AM] [General] [Error] Failed to background start DevTools
[8:25:35 AM] [General] [Error] Dart DevTools exited with code 255.
Tue Dec 21 2021 [08:25:46 GMT+0100 (Central European Standard Time)] Log file ended
```

Flutter Doctor
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale
    en-BE)
    • Flutter version 2.5.3 at
      /Users/navaronbracke/Documents/flutter_dev/flutter
    • Upstream repository git@github.com:navaronbracke/flutter.git
    • Framework revision 18116933e7 (10 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

**Comment by navaronbracke** [comment]
Closing this issue, as this is apparently a duplicate of https://github.com/flutter/devtools/issues/3549
