### ISSUE TITLE
print_object_layout_test.dart fails on xarm64 bot

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#47982]
The test `vm/dart_2/print_object_layout_test RuntimeError (expected Pass)` that was introduced in https://dart.googlesource.com/sdk/+/591b2bd7243cd29555378cf103035788908cab8f is failing on dartk-linux-release-arm64 configuration.

```
--- Command "vm" (took 03:29.000396s):
DART_CONFIGURATION=ReleaseXARM64 out/ReleaseXARM64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/runtime/tests/vm/dart_2/print_object_layout_test.dart

exit code:
255

stdout:
+ tools/sdks/dart-sdk/bin/dart pkg/vm/bin/gen_kernel.dart --platform out/ReleaseXARM64/vm_platform_strong.dill --aot --link-platform --output=/b/s/w/itckavmnhn/JMFDRV/app.dill /b/s/w/ir/runtime/tests/vm/dart_2/print_object_layout_script.dart
+ out/ReleaseXARM64/gen_snapshot --snapshot-kind=app-aot-elf --elf=/b/s/w/itckavmnhn/JMFDRV/aot.snapshot --print-object-layout-to=/b/s/w/itckavmnhn/JMFDRV/layout.json /b/s/w/itckavmnhn/JMFDRV/app.dill

stderr:
Unhandled exception:
ProcessException: No such file or directory
  Command: out/ReleaseXARM64/gen_snapshot --snapshot-kind=app-aot-elf --elf=/b/s/w/itckavmnhn/JMFDRV/aot.snapshot --print-object-layout-to=/b/s/w/itckavmnhn/JMFDRV/layout.json /b/s/w/itckavmnhn/JMFDRV/app.dill
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      runBinary (file:///b/s/w/ir/runtime/tests/vm/dart_2/snapshot_test_helper.dart:100:39)
#5      runGenSnapshot (file:///b/s/w/ir/runtime/tests/vm/dart_2/snapshot_test_helper.dart:92:10)
#6      main.<anonymous closure> (file:///b/s/w/ir/runtime/tests/vm/dart_2/print_object_layout_test.dart:85:11)
<asynchronous suspension>
#7      withTempDir (file:///b/s/w/ir/runtime/tests/vm/dart_2/snapshot_test_helper.dart:129:5)
<asynchronous suspension>
#8      main (file:///b/s/w/ir/runtime/tests/vm/dart_2/print_object_layout_test.dart:73:3)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-linux-release-arm64 vm/dart_2/print_object_layout_test
```

**Comment by aam** [comment]
also fails on [ia32](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8827263188427549969/+/u/test_results/new_test_failures__logs_)
```


/==================================================================================================================\
| dartk-strong-linux-release-ia32:vm/dart/print_object_layout_test is new and failed (RuntimeError, expected Pass) |
\==================================================================================================================/

--- Command "vm" (took 26.000287s):
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --sound-null-safety --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/runtime/tests/vm/dart/print_object_layout_test.dart

exit code:
255

stdout:
+ tools/sdks/dart-sdk/bin/dart pkg/vm/bin/gen_kernel.dart --platform out/ReleaseIA32/vm_platform_strong.dill --sound-null-safety --aot --link-platform --output=/b/s/w/itqt8lkf_r/BBXPJS/app.dill /b/s/w/ir/runtime/tests/vm/dart/print_object_layout_script.dart
+ out/ReleaseIA32/gen_snapshot --snapshot-kind=app-aot-elf --elf=/b/s/w/itqt8lkf_r/BBXPJS/aot.snapshot --print-object-layout-to=/b/s/w/itqt8lkf_r/BBXPJS/layout.json /b/s/w/itqt8lkf_r/BBXPJS/app.dill

Command stderr:
../../runtime/vm/compiler/jit/compiler.cc: 92: error: Precompilation not supported on IA32

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0xc
Aborting re-entrant request for stack trace.

running [GENERATE SNAPSHOT] out/ReleaseIA32/gen_snapshot --snapshot-kind=app-aot-elf --elf=/b/s/w/itqt8lkf_r/BBXPJS/aot.snapshot --print-object-layout-to=/b/s/w/itqt8lkf_r/BBXPJS/layout.json /b/s/w/itqt8lkf_r/BBXPJS/app.dill:

Command stderr:
../../runtime/vm/compiler/jit/compiler.cc: 92: error: Precompilation not supported on IA32

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0xc
Aborting re-entrant request for stack trace.

stderr:
Unhandled exception:
Expect.fail('[GENERATE SNAPSHOT] Process finished with non-zero exit code -6')
#0      Expect._fail (package:expect/expect.dart:731:5)
#1      Expect.fail (package:expect/expect.dart:300:5)
#2      reportError (file:///b/s/w/ir/runtime/tests/vm/dart/snapshot_test_helper.dart:37:10)
#3      runBinary (file:///b/s/w/ir/runtime/tests/vm/dart/snapshot_test_helper.dart:118:5)
<asynchronous suspension>
#4      main.<anonymous closure> (file:///b/s/w/ir/runtime/tests/vm/dart/print_object_layout_test.dart:83:5)
<asynchronous suspension>
#5      withTempDir (file:///b/s/w/ir/runtime/tests/vm/dart/snapshot_test_helper.dart:127:5)
<asynchronous suspension>
#6      main (file:///b/s/w/ir/runtime/tests/vm/dart/print_object_layout_test.dart:71:3)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-strong-linux-release-ia32 vm/dart/print_object_layout_test
```
