### ISSUE TITLE
Invalid argument(s): Unexpectedly not indexed: E

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#48096]
```dart
class A {
  const A(_);
}

class B<E> {
  void foo(E e) {}
}

@A(B.foo)
class C {}
```

Results in:
```
  Invalid argument(s): Unexpectedly not indexed: E
  #0      _LocalElementIndexer.[] (package:analyzer/src/summary2/bundle_writer.dart:917:10)
  #1      ResolutionSink._indexOfElement (package:analyzer/src/summary2/bundle_writer.dart:598:27)
  #2      ResolutionSink._writeElement (package:analyzer/src/summary2/bundle_writer.dart:633:24)
  #3      ResolutionSink.writeElement (package:analyzer/src/summary2/bundle_writer.dart:521:7)
  #4      ResolutionSink.writeType (package:analyzer/src/summary2/bundle_writer.dart:573:7)
  #5      ResolutionSink._writeFormalParameters.<anonymous closure> (package:analyzer/src/summary2/bundle_writer.dart:647:9)
  #6      ResolutionSink._writeTypeParameters.<anonymous closure> (package:analyzer/src/summary2/bundle_writer.dart:731:8)
  #7      _LocalElementIndexer.withElements (package:analyzer/src/summary2/bundle_writer.dart:925:6)
  #8      ResolutionSink._writeTypeParameters (package:analyzer/src/summary2/bundle_writer.dart:720:19)
  #9      ResolutionSink._writeFormalParameters (package:analyzer/src/summary2/bundle_writer.dart:646:7)
  #10     ResolutionSink._writeFunctionType.<anonymous closure> (package:analyzer/src/summary2/bundle_writer.dart:667:7)
  #11     ResolutionSink._writeTypeParameters.<anonymous closure> (package:analyzer/src/summary2/bundle_writer.dart:731:8)
  #12     _LocalElementIndexer.withElements (package:analyzer/src/summary2/bundle_writer.dart:925:6)
  #13     ResolutionSink._writeTypeParameters (package:analyzer/src/summary2/bundle_writer.dart:720:19)
  #14     ResolutionSink._writeFunctionType (package:analyzer/src/summary2/bundle_writer.dart:665:5)
  #15     ResolutionSink.writeType (package:analyzer/src/summary2/bundle_writer.dart:541:7)
  #16     AstBinaryWriter._storeExpression (package:analyzer/src/summary2/ast_binary_writer.dart:803:11)
  #17     AstBinaryWriter.visitSimpleIdentifier (package:analyzer/src/summary2/ast_binary_writer.dart:680:5)
  #18     SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9228:50)
  #19     AstBinaryWriter._writeNode (package:analyzer/src/summary2/ast_binary_writer.dart:887:10)
  #20     AstBinaryWriter.visitPrefixedIdentifier (package:analyzer/src/summary2/ast_binary_writer.dart:581:5)
  #21     PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8421:50)
  #22     AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:893:19)
  #23     AstBinaryWriter.visitArgumentList (package:analyzer/src/summary2/ast_binary_writer.dart:57:5)
  #24     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:372:50)
  #25     AstBinaryWriter._writeNode (package:analyzer/src/summary2/ast_binary_writer.dart:887:10)
  #26     AstBinaryWriter._writeOptionalNode (package:analyzer/src/summary2/ast_binary_writer.dart:909:7)
  #27     AstBinaryWriter.visitAnnotation (package:analyzer/src/summary2/ast_binary_writer.dart:49:5)
  #28     AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:297:50)
  #29     ResolutionSink._writeNode (package:analyzer/src/summary2/bundle_writer.dart:677:10)
  #30     ResolutionSink._writeAnnotationList (package:analyzer/src/summary2/bundle_writer.dart:627:7)
  #31     BundleWriter._writeClassElement (package:analyzer/src/summary2/bundle_writer.dart:132:21)
  #32     BundleWriter._writeList (package:analyzer/src/summary2/bundle_writer.dart:275:19)
  #33     BundleWriter._writeUnitElement (package:analyzer/src/summary2/bundle_writer.dart:437:5)
  #34     BundleWriter.writeLibraryElement (package:analyzer/src/summary2/bundle_writer.dart:112:7)
  #35     Linker._writeLibraries (package:analyzer/src/summary2/link.dart:220:20)
  #36     Linker.link (package:analyzer/src/summary2/link.dart:78:5)
  #37     link (package:analyzer/src/summary2/link.dart:34:10)
```

The reason is that we record `B.foo` element, and also its (uninstantiated) type `void Function(E)`, and `E` is not available outside of `B`. This is not right, the type is either instantiated, or even `dynamic` because it is not static.

**Comment by scheglov** [comment]
I cannot reproduce it anymore.
