### ISSUE TITLE
NPE in NonParameterVariableElementImpl.enclosingElement

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#48124]
I was working on `package:watcher` and pasted the following code into a temporary file (at `bin/test.dart`) for testing:

```dart
import 'package:watcher/watcher.dart';

main() async {
  // Ensure app doesn't quit for at least 30s
  Future.delayed(const Duration(seconds: 10));

  // Try to watch a folder that does not exist
  final watcher = PollingDirectoryWatcher('/tmp/foo');

  // Print any events/errors from the stream.
  final sub = watcher.events.listen(
    (event) => print(event.type),
    onError: (e) => print('ERROR ON STREAM: $e'),
  );

  // Wait for the watcher to become ready.
  print('waiting for ready...');
  try {
    await watcher.ready;
    print('watcher is ready!');
  } catch (e) {
    print('ERROR WAITING FOR READY: $e');
  }

  print('DONE!');
  sub.cancel();
}
```

After doing so, selecting text (which triggers highlighting) failed with this error:

```
[Error - 4:13:28 PM] An error occurred while handling textDocument/documentHighlight request: Null check operator used on a null value
#0      NonParameterVariableElementImpl.enclosingElement (package:analyzer/src/dart/element/element.dart:4639:57)
#1      new ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:2571:27)
#2      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2341:52)
#3      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2101:32)
#4      _OperatorEqualsAndHashCode._hashCode (dart:collection-patch/compact_hash.dart:191:25)
#5      _LinkedHashMapMixin._getValueOrData (dart:collection-patch/compact_hash.dart:497:26)
#6      _LinkedHashMapMixin.[] (dart:collection-patch/compact_hash.dart:520:13)
#7      _DartUnitOccurrencesComputerVisitor._addOccurrence (package:analysis_server/src/domains/analysis/occurrences_dart.dart:43:34)
#8      _DartUnitOccurrencesComputerVisitor.visitSimpleIdentifier (package:analysis_server/src/domains/analysis/occurrences_dart.dart:33:7)
#9      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9228:50)
#10     PrefixedIdentifierImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8426:17)
#11     RecursiveAstVisitor.visitPrefixedIdentifier (package:analyzer/dart/ast/visitor.dart:1203:10)
#12     PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8421:50)
#13     AwaitExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:868:17)
#14     RecursiveAstVisitor.visitAwaitExpression (package:analyzer/dart/ast/visitor.dart:693:10)
#15     AwaitExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:864:50)
#16     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3702:17)
#17     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:879:10)
#18     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3698:50)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#20     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1051:17)
#21     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:705:10)
#22     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1047:50)
#23     TryStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10400:11)
#24     RecursiveAstVisitor.visitTryStatement (package:analyzer/dart/ast/visitor.dart:1360:10)
#25     TryStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10396:50)
#26     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#27     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1051:17)
#28     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:705:10)
#29     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1047:50)
#30     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1006:12)
#31     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:711:10)
#32     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1002:50)
#33     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5041:11)
#34     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:969:10)
#35     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5035:50)
#36     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4919:25)
#37     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:957:10)
#38     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4912:50)
#39     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#40     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2105:21)
#41     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:765:10)
#42     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2098:50)
#43     addDartOccurrences (package:analysis_server/src/domains/analysis/occurrences_dart.dart:16:8)
#44     DocumentHighlightsHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_document_highlights.dart:37:7)
#45     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:249:12)
#46     DocumentHighlightsHandler.handle (package:analysis_server/src/lsp/handlers/handler_document_highlights.dart:35:19)
<asynchronous suspension>
#47     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:171:22)
<asynchronous suspension>
#48     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:341:26)
<asynchronous suspension>
```

**Comment by DanTup** [comment]
For reasons I don't understand, it seems to only occur when I have `PollingDirectoryWatcher` and not `DirectoryWatcher`.

I'm using:

```
Dart SDK version: 2.17.0-edge.27d3969eaedda668ac92a052469a9d7f0c92cff2 (be) (Mon Jan 10 14:45:05 2022 +0000) on "macos_x64"
```

**Comment by scheglov** [comment]
I can reproduce this with
```dart
import 'dart:io' as io;

import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/file_system/file_system.dart';
import 'package:analyzer/file_system/physical_file_system.dart';
import 'package:analyzer/src/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/src/dart/analysis/performance_logger.dart';

main() async {
  ResourceProvider resourceProvider = PhysicalResourceProvider.INSTANCE;

  var rootPath = '/Users/scheglov/dart/test/bin';
  var collection = AnalysisContextCollectionImpl(
    includedPaths: [rootPath],
    resourceProvider: resourceProvider,
    sdkPath: '/Users/scheglov/Applications/dart-sdk',
    performanceLog: PerformanceLog(io.stdout),
  );

  var analysisContext = collection.contextFor(
    '/Users/scheglov/dart/test/bin/test.dart',
  );
  var resultUnit = await analysisContext.currentSession.getResolvedUnit(
    '/Users/scheglov/dart/test/bin/test.dart',
  );
  resultUnit as ResolvedUnitResult;

  resultUnit.unit.accept(
    _Visitor(),
  );
}

class _Visitor extends RecursiveAstVisitor<void> {
  @override
  void visitSimpleIdentifier(SimpleIdentifier node) {
    var element = node.staticElement!;
    print('[element: $element][enclosing: ${element.enclosingElement}]');

    var canonicalElement = _canonicalizeElement(element)!;
    print('[canonicalElement: $canonicalElement][enclosing: ${canonicalElement.enclosingElement}]');
  }


  Element? _canonicalizeElement(Element element) {
    Element? canonicalElement = element;
    if (canonicalElement is FieldFormalParameterElement) {
      canonicalElement = canonicalElement.field;
    } else if (canonicalElement is PropertyAccessorElement) {
      canonicalElement = canonicalElement.variable;
    }
    return canonicalElement?.declaration;
  }
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/228723
