### ISSUE TITLE
[vm] List.insertAll can leave unsound null elements when interrupted

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#48132]
If `List.insertAll` is interrupted by an exception, it can leave the modified list in an inconsistent state where space has been made for the new elements, but they have not (all) been written yet. This can cause a list with a non-nullable type to contain `null` elements.

The situation can be triggered by inserting a list into itself:
```dart
main() {
  List<int> list = [1, 2];
  try {
    list.insertAll(1, list);
  } catch (_) {}
  print(list.length);
  print(list[2]);
}
```
or if the inserted list throws on access:
```dart
import 'dart:collection';

class BadList extends ListBase<int> {
  int get length => 2;
  int operator [](int index) => throw "BOOM";

  set length(int l) => throw "unimplemented";
  void operator []=(int index, int value) => throw "unimplemented";
  void add(int e) => throw "unimplemented";
}

main() {
  List<int> list = [1, 2];
  try {
    list.insertAll(1, BadList());
  } catch (_) {}
  print(list.length);
  print(list[2]);
}
```
Both of these print:
```
4
null
```
Producing a segfault is left as an exercise to the reader.

The offending code is:
https://github.com/dart-lang/sdk/blob/e4e7d31ec7e89c940dca88327638928fd5d20e1f/sdk/lib/_internal/vm/lib/growable_array.dart#L42-L65

Judging by the reference implementation in https://github.com/dart-lang/sdk/blob/e4e7d31ec7e89c940dca88327638928fd5d20e1f/sdk/lib/collection/list.dart, the first example is supposed to work as expected (it also works in `dart2js`). This can be fixed by also creating the temporary list (the `iterable = iterable.toList();`) when the inserted list is identical to `this`.

For fixing the second case of a throwing iterable, there are two approaches we could take:
1. Create the temporary list unless the iterable is of a known, non-throwing type. Use `_List.of(iterable)` instead of `iterable.toList()` to make sure that the new list is also non-throwing.
2. Keep the optimistic avoidance of the extra copy, but wrap the `setAll` in a `try` / `finally` which restores the original list on error.

**Comment by rakudrama** [comment]
I prefer option (1) since it is obviously atomic. In most cases the temporary array is ephemeral, and code following the copy is less polymorphic. I think for JavaScript we would copy everything that is not a JavaScript Array or typed array.

It is not clear that self-insertion is supposed to work. In the reference implementation, `a.insertAll(x, a.length)` [uses `addAll`](https://github.com/dart-lang/sdk/blob/e4e7d31ec7e89c940dca88327638928fd5d20e1f/sdk/lib/collection/list.dart#L546) and will fail because `list.addAll(list)` fails.
The documentation for `insertAll` is silent on the self-insertion issue.

- [ ] Test for the unsound case
- [ ] Decision on intended behaviour with self-insertion @lrhn 
- [ ] Test for self-insertion
- [ ] VM fix
- [ ] DDC fix
- [ ] dart2js fix - https://github.com/dart-lang/sdk/issues/48134

**Comment by lrhn** [comment]
Another option is to pre-fill the increased length with, say, the last value of the original list. (If there are not existing value, then just do an `addAll` instead.)

It seems we check for efficient length, then convert to `List` if there is none.

Yet another approach is to do:

```dart
void insertAll(int index, Iterable<E> iterable) {
  // check index valid
  var originalLength = this.length;
  this.addAll(iterable);
  var delta = this.length - originalLength;
  this
    ..reverseRange(index, oldLength)
    ..reverseRange(oldLength, this.length)
    ..reverseRange(index, this.length);
}
```
That's one store and two moves for each element in the iterable,
and two moves for every element from index to original length of the target,
and if `iterable` throws, the intermediate step is going to be completely weird.

Alternatively, catch the error and adjust the result to only contain the elements iterated so far:
```dart
   _setLength(newLength); 
   setRange(index + insertionLength, this.length, this, index); 
   var i = 0;
   try {
     for (var element in iterable) {
       i++;
       if (i >= insertionLength) throw ConcurrentModificationError(iterable);
       this[index + i] = element;
     }
  } catch e {
    if (i < insertionLength) {
      setRange(index + i, this.length - (index + insertionLength), this, index + insertionLength);
      _setLength(this.length - insertionLength + i);
    }
    rethrow;
  }
```
(This also handles a too-long iterator, one which has more elements than its `length` says.)

**Comment by rakudrama** [comment]
We have to change `insertAll` to fix soundness.
I think we should take this opportunity to make the implementations consistent, so programs developed on one platform work the same on another.

I would expect more consistency between dart2js and VM, and between the system `List` and `WrapList`.
```dart
import 'dart:collection';

main() {
  test([], 0);
  test([11], 0);
  test([11], 1);
  test([11, 22], 0);
  test([11, 22], 1);
  test([11, 22], 2);

  test(WrapList([]), 0);
  test(WrapList([11]), 0);
  test(WrapList([11]), 1);
  test(WrapList([11, 22]), 0);
  test(WrapList([11, 22]), 1);
  test(WrapList([11, 22]), 2);
}

test(List a, int index) {
  print('a: $a, index: $index');
  try {
    a.insertAll(index, a);
    print('a: $a');
  } catch (e, s) {
    print('$e');
    print('a: $a');
    print("$s".split('\n').take(5).join('\n'));
  }
  print('');
}


class WrapList<E> extends ListBase<E> {
  final _list;
  WrapList(this._list);

  int get length => _list.length;
  void set length(int len) => _list.length = len;
  E operator[](int i) => _list[i];
  void operator[]=(int i, E value) => _list[i] = value;
  void add(E value) => _list.add(value);

  String toString() => 'WrapList($_list)';
}

```

dart2js:
```
a: [], index: 0
a: []

a: [11], index: 0
a: [11, 11]

a: [11], index: 1
a: [11, 11]

a: [11, 22], index: 0
a: [11, 22, 11, 22]

a: [11, 22], index: 1
a: [11, 11, 22, 22]

a: [11, 22], index: 2
a: [11, 22, 11, 22]

a: WrapList([]), index: 0
a: WrapList([])

a: WrapList([11]), index: 0
a: WrapList([11, 11])

a: WrapList([11]), index: 1
Concurrent modification during iteration: Instance of 'WrapList<dynamic>'.
a: WrapList([11, 11])
Concurrent modification during iteration: Instance of 'WrapList<dynamic>'.
    at Object.wrapException (o2.js:361:17)
    at ListIterator.moveNext$0 (o2.js:3155:17)
    at WrapList.addAll$1 (o2.js:3330:71)
    at WrapList.insertAll$2 (o2.js:3375:15)

a: WrapList([11, 22]), index: 0
a: WrapList([11, 22, 11, 22])

a: WrapList([11, 22]), index: 1
a: WrapList([11, 11, 22, 22])

a: WrapList([11, 22]), index: 2
Concurrent modification during iteration: Instance of 'WrapList<dynamic>'.
a: WrapList([11, 22, 11])
Concurrent modification during iteration: Instance of 'WrapList<dynamic>'.
    at Object.wrapException (o2.js:361:17)
    at ListIterator.moveNext$0 (o2.js:3155:17)
    at WrapList.addAll$1 (o2.js:3330:71)
    at WrapList.insertAll$2 (o2.js:3375:15)
```

VM:
```
a: [], index: 0
a: []

a: [11], index: 0
a: [11, 11]

a: [11], index: 1
RangeError (end): Invalid value: Not in inclusive range 1..2: 3
a: [11, null]
#0      RangeError.checkValidRange (dart:core/errors.dart:356:9)
#1      ListMixin.setRange (dart:collection/list.dart:415:16)
#2      List.setAll (dart:core-patch/growable_array.dart:69:7)
#3      List.insertAll (dart:core-patch/growable_array.dart:64:5)
#4      test (file:///usr/local/google/home/sra/play1/bug1c3h.dart:22:7)

a: [11, 22], index: 0
a: [11, 22, 11, 22]

a: [11, 22], index: 1
RangeError (end): Invalid value: Not in inclusive range 1..4: 5
a: [11, 22, null, 22]
#0      RangeError.checkValidRange (dart:core/errors.dart:356:9)
#1      ListMixin.setRange (dart:collection/list.dart:415:16)
#2      List.setAll (dart:core-patch/growable_array.dart:69:7)
#3      List.insertAll (dart:core-patch/growable_array.dart:64:5)
#4      test (file:///usr/local/google/home/sra/play1/bug1c3h.dart:22:7)

a: [11, 22], index: 2
RangeError (end): Invalid value: Not in inclusive range 2..4: 6
a: [11, 22, null, null]
#0      RangeError.checkValidRange (dart:core/errors.dart:356:9)
#1      ListMixin.setRange (dart:collection/list.dart:415:16)
#2      List.setAll (dart:core-patch/growable_array.dart:69:7)
#3      List.insertAll (dart:core-patch/growable_array.dart:64:5)
#4      test (file:///usr/local/google/home/sra/play1/bug1c3h.dart:22:7)

a: WrapList([]), index: 0
a: WrapList([])

a: WrapList([11]), index: 0
a: WrapList([11, 11])

a: WrapList([11]), index: 1
Concurrent modification during iteration: Instance of 'WrapList<dynamic>'.
a: WrapList([11, 11])
#0      ListIterator.moveNext (dart:_internal/iterable.dart:336:7)
#1      ListMixin.addAll (dart:collection/list.dart:284:23)
#2      ListMixin.insertAll (dart:collection/list.dart:546:7)
#3      test (file:///usr/local/google/home/sra/play1/bug1c3h.dart:22:7)
#4      main (file:///usr/local/google/home/sra/play1/bug1c3h.dart:13:3)

a: WrapList([11, 22]), index: 0
a: WrapList([11, 22, 11, 22])

a: WrapList([11, 22]), index: 1
a: WrapList([11, 11, 22, 22])

a: WrapList([11, 22]), index: 2
Concurrent modification during iteration: Instance of 'WrapList<dynamic>'.
a: WrapList([11, 22, 11])
#0      ListIterator.moveNext (dart:_internal/iterable.dart:336:7)
#1      ListMixin.addAll (dart:collection/list.dart:284:23)
#2      ListMixin.insertAll (dart:collection/list.dart:546:7)
#3      test (file:///usr/local/google/home/sra/play1/bug1c3h.dart:22:7)
#4      main (file:///usr/local/google/home/sra/play1/bug1c3h.dart:16:3)
```

**Comment by lrhn** [comment]
I'm not sure I care whether error behavior is compatible between platforms. If your iterator throws, the result is unspecified.
It just has to be *sound*, there is no "correct". So, no leaving `null` values visible.

(Obviosuly, we can go the extra mile and make it consistent with inserting each element, one by one, and stopping when the iterator throws. As long as it doesn't cost us much, it's "nice to have".)

There are other errors which can occur if the iterable changes length (or if its `length` doesn't match the number of elements of its `iterator`, which requires some very bad, and likely deliberate, coding to happen).
I'm writing a test :grin:.

**Comment by askeksa-google** [comment]
> I prefer option (1) since it is obviously atomic. In most cases the temporary array is ephemeral, and code following the copy is less polymorphic. I think for JavaScript we would copy everything that is not a JavaScript Array or typed array.

These are very good arguments. I like the cleanness of giving `insertAll` the semantics that it (conceptually) first extracts all elements from the iterator, and then inserts them into the list. It's easy to understand and unambiguously defines all corner cases, such as self-insertion, length mismatches and exceptions.

Thus, the pre-copy code would look something like this:
```dart
if (!isInternalList(iterable) && iterable is! TypedData || identical(iterable, this)) {
  iterable = List.of(iterable, growable: false);
}
```
where `isInternalList` is a target-dependent check. We could opt to add such a function to `dart:_internal` to make this check also available to the target-independent reference implementation.

**Comment by lrhn** [comment]
You also wouldn't need to copy an internal `Set`, internal `Map`'s keys or values iterator or even an internal `Queue`, because we know accessing them cannot have side-effects, they have efficient length and consistent iteration.
Whether it's worth the effort is a different question. I don't know how often anyone inserts a set into a list (`addAll` is more likely).

**Comment by rakudrama** [comment]
> I'm not sure I care whether error behavior is compatible between platforms. If your iterator throws, the result is unspecified.
It just has to be sound, there is no "correct". So, no leaving `null` values visible.

@lrhn The point I am most concerned about is behaviour that is an error on one platform and succeeds on another. Hopefully that is included in your :smiling_imp: test.

**Comment by rakudrama** [comment]
> I'm writing a test :smiling_imp:.

Assigned to you to reflect this status.
