### ISSUE TITLE
Unsupported operation: Undetermined Nullability in web_dev_compiler

### ISSUE THREAD

**Issue by jacobsimionato** [dart-lang/sdk#48170]
I'm hitting this compiler issue while trying to migrate some complex rx code in google3 to null safety:

```
   [ Reproduction command deleted out of an abundance of caution by @leafpetersen ]
    dart --version: 2.17.422473333-edge+google3-v2 (google3) (google3) on "linux_x64"

Unsupported operation: Undetermined Nullability
#0      ProgramCompiler._emitInterfaceType (package:dev_compiler/src/kernel/compiler.dart:3022)
#1      ProgramCompiler.visitInterfaceType (package:dev_compiler/src/kernel/compiler.dart:2938)
#2      InterfaceType.accept (package:kernel/ast.dart:11127)
#3      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:2847)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:342)
#7      InstantiatorGeneratorVisitor.splayNodes (package:dev_compiler/src/js_ast/template.dart:224)
#8      InstantiatorGeneratorVisitor.handleCallOrNew.<anonymous closure> (package:dev_compiler/src/js_ast/template.dart:587)
#9      Template.instantiate (package:dev_compiler/src/js_ast/template.dart:113)
#10     JsBuilder.call (package:dev_compiler/src/js_ast/builder.dart:218)
#11     ProgramCompiler._emitGenericClassType (package:dev_compiler/src/kernel/compiler.dart:3105)
#12     ProgramCompiler._emitInterfaceType (package:dev_compiler/src/kernel/compiler.dart:2994)
#13     ProgramCompiler._emitList (package:dev_compiler/src/kernel/compiler.dart:6113)
#14     ProgramCompiler.visitListLiteral (package:dev_compiler/src/kernel/compiler.dart:6100)
#15     ListLiteral.accept (package:kernel/ast.dart:7967)
#16     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3870)
#17     ProgramCompiler.visitConditionalExpression (package:dev_compiler/src/kernel/compiler.dart:5902)
#18     ConditionalExpression.accept (package:kernel/ast.dart:6700)
#19     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3870)
#20     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:5614)
#21     ProgramCompiler._emitMethodCall (package:dev_compiler/src/kernel/compiler.dart:4888)
#22     ProgramCompiler.visitInstanceInvocation (package:dev_compiler/src/kernel/compiler.dart:4802)
#23     InstanceInvocation.accept (package:kernel/ast.dart:5521)
#24     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3870)
#25     ProgramCompiler.visitExpressionStatement (package:dev_compiler/src/kernel/compiler.dart:3951)
#26     ExpressionStatement.accept (package:kernel/ast.dart:8850)
#27     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3776)
#28     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#29     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#30     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:206)
#31     new _GrowableList.of (dart:core-patch/growable_array.dart:153)
#32     new List.of (dart:core-patch/array_patch.dart:51)
#33     ListIterable.toList (dart:_internal/iterable.dart:213)
#34     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3964)
#35     Block.accept (package:kernel/ast.dart:8906)
#36     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3776)
#37     ProgramCompiler._visitScope (package:dev_compiler/src/kernel/compiler.dart:4391)
#38     ProgramCompiler.visitIfStatement (package:dev_compiler/src/kernel/compiler.dart:4380)
#39     IfStatement.accept (package:kernel/ast.dart:9810)
#40     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3776)
#41     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#42     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#43     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:206)
#44     new _GrowableList.of (dart:core-patch/growable_array.dart:153)
#45     new List.of (dart:core-patch/array_patch.dart:51)
#46     ListIterable.toList (dart:_internal/iterable.dart:213)
#47     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3964)
#48     Block.accept (package:kernel/ast.dart:8906)
#49     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3776)
#50     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3809)
#51     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3578)
#52     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2376)
#53     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3612)
#54     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3574)
#55     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3391)
#56     ProgramCompiler.visitFunctionDeclaration (package:dev_compiler/src/kernel/compiler.dart:4538)
#57     FunctionDeclaration.accept (package:kernel/ast.dart:10523)
#58     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3776)
#59     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#60     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#61     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:206)
#62     new _GrowableList.of (dart:core-patch/growable_array.dart:153)
#63     new List.of (dart:core-patch/array_patch.dart:51)
#64     ListIterable.toList (dart:_internal/iterable.dart:213)
#65     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3964)
#66     Block.accept (package:kernel/ast.dart:8906)
#67     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3776)
#68     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3809)
#69     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3578)
#70     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2376)
#71     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3612)
#72     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3574)
#73     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3391)
#74     ProgramCompiler._emitArrowFunction (package:dev_compiler/src/kernel/compiler.dart:6191)
#75     ProgramCompiler.visitFunctionExpression (package:dev_compiler/src/kernel/compiler.dart:6184)
#76     FunctionExpression.accept (package:kernel/ast.dart:8300)
#77     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3870)
#78     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:5614)
#79     ProgramCompiler._emitFactoryInvocation (package:dev_compiler/src/kernel/compiler.dart:5819)
#80     ProgramCompiler.visitStaticInvocation (package:dev_compiler/src/kernel/compiler.dart:5465)
#81     StaticInvocation.accept (package:kernel/ast.dart:6310)
#82     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3870)
#83     ProgramCompiler.visitLet (package:dev_compiler/src/kernel/compiler.dart:6233)
#84     Let.accept (package:kernel/ast.dart:8411)
#85     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3870)
#86     ProgramCompiler.visitReturnStatement (package:dev_compiler/src/kernel/compiler.dart:4401)
#87     ReturnStatement.accept (package:kernel/ast.dart:9885)
#88     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3776)
#89     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#90     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#91     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:206)
#92     new _GrowableList.of (dart:core-patch/growable_array.dart:153)
#93     new List.of (dart:core-patch/array_patch.dart:51)
#94     ListIterable.toList (dart:_internal/iterable.dart:213)
#95     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3964)
#96     Block.accept (package:kernel/ast.dart:8906)
#97     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3776)
#98     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3809)
#99     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3578)
#100    ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2376)
#101    ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3612)
#102    ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3574)
#103    ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3391)
#104    ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:1970)
#105    ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:1911)
#106    ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:700)
#107    ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:622)
#108    List.forEach (dart:core-patch/growable_array.dart:433)
#109    ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:571)
#110    List.forEach (dart:core-patch/growable_array.dart:433)
#111    ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:431)
#112    _compile (package:dev_compiler/src/kernel/command.dart:442)
<asynchronous suspension>
#113    compile (package:dev_compiler/src/kernel/command.dart:51)
<asynchronous suspension>
#114    internalMain (package:dev_compiler/ddc.dart:38)
<asynchronous suspension>
#115    DevCompiler.compile (google3:///dart/build_defs/action/ddc/bin/main_ddc.dart:42)
<asynchronous suspension>
#116    LibraryRunner.run.<anonymous closure> (package:dart.build_defs.tool.common.snapshot_runner/library_runner.dart:60)
<asynchronous suspension>
#117    CachingActionWrapper.run (package:dart.build_defs.tool.common.cache/caching_action_wrapper.dart:40)
<asynchronous suspension>
#118    _Handler.run (package:dart.build_defs.tool.common.deps_pruning/unused_inputs_list_action_wrapper.dart:64)
<asynchronous suspension>
#119    LibraryRunner.run (package:dart.build_defs.tool.common.snapshot_runner/library_runner.dart:66)
<asynchronous suspension>
#120    main (google3:///dart/build_defs/action/ddc/bin/main_ddc.dart:14)
<asynchronous suspension>
```

Internal code reference: CL/422651272

**Comment by nshahan** [comment]
I'm responding on an internal bug b/215355347 to try and find the particular piece of code that was being compile when the exception occurred.

**Comment by nshahan** [comment]
No response on the internal issue and it has been closed. Can't reproduce.
