### ISSUE TITLE
[dart2wasm] compiler fails to run from outside the Dart SDK checkout directory

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#48209]
This is reproducible on Windows 10 on the wasm_prototype branch at https://github.com/askeksa-google/sdk/commit/77470d48352745dfa0891d82ecde663c82370dca.

## Steps to reproduce

Create the following Dart program and save it as `one_plus_one.dart` anywhere other than the Dart SDK checkout:

```dart
void main() {
  1 + 1;
}
```

Run the following from the directory where `one_plus_one.dart` is located:

```
dart --enable-asserts ..\..\dart-sdk\sdk\pkg\dart2wasm\bin\dart2wasm.dart --print-wasm .\one_plus_one.dart .\one_plus_one.wasm
```

Observe the following output:

```
PS C:\code\tmp\wasm> dart --enable-asserts ..\..\dart-sdk\sdk\pkg\dart2wasm\bin\dart2wasm.dart --print-wasm .\one_plus_one.dart .\one_plus_one.wasm
Error: SDK root directory not found: sdk/.
Error: SDK libraries specification not found: sdk/lib/libraries.json.
Normally, the specification is a file named 'libraries.json' in the Dart SDK install location.
one_plus_one.dart: Error: Not found: 'dart:core'
one_plus_one.dart: Error: Not found: 'dart:collection'
org-dartlang-untranslatable-uri:dart%3Acore:1:8: Error: Not found: 'dart:_internal'
import 'dart:_internal';
       ^
org-dartlang-untranslatable-uri:dart%3Acore:2:8: Error: Not found: 'dart:async'
import 'dart:async';
       ^
org-dartlang-untranslatable-uri:dart%3Acore:4:1: Error: Not found: 'dart:async'
export 'dart:async' show Future, Stream;
^
Unhandled exception:
Crash when compiling dart:core,
at character offset null:
Can't find dart:typed_data
#0      KernelTarget.computeCoreTypes (package:front_end/src/fasta/kernel/kernel_target.dart:991:11)
#1      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:408:7)
<asynchronous suspension>
#2      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#3      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:100:10)
<asynchronous suspension>
#4      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#5      kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:59:29)
<asynchronous suspension>
#6      kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:58:10)
<asynchronous suspension>
#7      kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50:11)
<asynchronous suspension>
#8      compileToModule (package:dart2wasm/compile.dart:50:7)
<asynchronous suspension>
#9      main (file:///C:/code/dart-sdk/sdk/pkg/dart2wasm/bin/dart2wasm.dart:82:23)
<asynchronous suspension>

#0      KernelTarget.computeCoreTypes (package:front_end/src/fasta/kernel/kernel_target.dart:991:11)
#1      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:408:7)
<asynchronous suspension>
#2      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#3      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:100:10)
<asynchronous suspension>
#4      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#5      kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:59:29)
<asynchronous suspension>
#6      kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:58:10)
<asynchronous suspension>
#7      kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50:11)
<asynchronous suspension>
#8      compileToModule (package:dart2wasm/compile.dart:50:7)
<asynchronous suspension>
#9      main (file:///C:/code/dart-sdk/sdk/pkg/dart2wasm/bin/dart2wasm.dart:82:23)
<asynchronous suspension>
```

cc @askeksa-google 

PS: Should we add a label for the wasm backend?

**Comment by mraleph** [comment]
Made `area-dart2wasm`

**Comment by askeksa-google** [comment]
Fixed in https://github.com/askeksa-google/sdk/commit/2580fa9928e62fc3a8fc588184507d365ec5b18e. It now locates the `sdk` directory relative to the `dart2wasm.dart` script. It can be overridden using the `--dart-sdk=` option.
