### ISSUE TITLE
Building devtools part of sdk requires administrative rights

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#48230]
Building the sdk on Windows fails with
```
c:/src/depot_tools/bootstrap-2@3_8_10_chromium_23_bin/python3/bin/python3.exe ../../tools/copy_tree.py --from C:/src/dart-repo2/sdk/third_party/devtools/web --to C:/src/dart-repo2/sdk/out/ReleaseX64/devtools
Traceback (most recent call last):
  File "../../tools/copy_tree.py", line 169, in <module>
    sys.exit(Main(sys.argv))
  File "../../tools/copy_tree.py", line 160, in Main
    CopyTree(args.copy_from, args.to)
  File "../../tools/copy_tree.py", line 107, in CopyTree
    raise RuntimeError(msg)
RuntimeError: Some file copies failed:
==============================================================================
From: C:/src/dart-repo2/sdk/third_party/devtools/web\canvaskit\canvaskit.js
To:   C:/src/dart-repo2/sdk/out/ReleaseX64/devtools\canvaskit\canvaskit.js
[Errno 13] Permission denied: 'C:/src/dart-repo2/sdk/out/ReleaseX64/devtools\\canvaskit\\canvaskit.js'

From: C:/src/dart-repo2/sdk/third_party/devtools/web\canvaskit\canvaskit.wasm
To:   C:/src/dart-repo2/sdk/out/ReleaseX64/devtools\canvaskit\canvaskit.wasm
[Errno 13] Permission denied: 'C:/src/dart-repo2/sdk/out/ReleaseX64/devtools\\canvaskit\\canvaskit.wasm'

From: C:/src/dart-repo2/sdk/third_party/devtools/web\canvaskit\profiling\canvaskit.js
To:   C:/src/dart-repo2/sdk/out/ReleaseX64/devtools\canvaskit\profiling\canvaskit.js
[Errno 13] Permission denied: 'C:/src/dart-repo2/sdk/out/ReleaseX64/devtools\\canvaskit\\profiling\\canvaskit.js'

From: C:/src/dart-repo2/sdk/third_party/devtools/web\canvaskit\profiling\canvaskit.wasm
To:   C:/src/dart-repo2/sdk/out/ReleaseX64/devtools\canvaskit\profiling\canvaskit.wasm
[Errno 13] Permission denied: 'C:/src/dart-repo2/sdk/out/ReleaseX64/devtools\\canvaskit\\profiling\\canvaskit.wasm'
[1750/1948] CXX obj/runtime/vm/libdart_vm_precompiler_product.object.obj
ninja: build stopped: subcommand failed.
BUILD FAILED
```

I (usually) fix this by rebuilding the sdk from scratch in a command prompt run as administrator.

**Comment by athomas** [comment]
I suspect that the cipd package for devtools needs to be created with `-preserve-writable`.

**Comment by athomas** [comment]
Reproduces on macOS as well.

**Comment by bkonyi** [comment]
This _should_ be a one time deal as the canvaskit binaries included with DevTools weren't uploaded to CIPD (note: not the DevTools upload itself) without `-preserve-writable`. This issue has been resolved (https://github.com/dart-lang/sdk/issues/48010) and the new copies of the canvaskit binaries should have the right permissions going forward.

The fix right now is to just blow away your build directory and rebuild from scratch. If you see it again going forward, then there's something else that needs to be looked at.
