### ISSUE TITLE
[frontend server, dartdevc] Flutter fails to compile for web but succeeds for mobile 

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#48242]
See original issue for a repro: https://github.com/flutter/flutter/issues/83104. DDC crashes during compilation initiated in the frontend server (see flutter logs in the issue).

**Comment by nshahan** [comment]
This minimal repro also triggers when trying to run on the VM so I'm going to change this to a CFE issue for now.
```dart
mixin Base {
  Object? methodWithDefaultImpl() {}
}

mixin TestFailure<A> on Base {
  @override
  methodWithDefaultImpl({A? nameParam});
}

void main() {}
```

Stacktrace:
```
$ dart test_05.dart    Crash when compiling null,
at character offset null:
Bad state: No element
#0      ListMixin.singleWhere (dart:collection/list.dart:202:5)
#1      ForwardingNode._createForwardingImplIfNeeded.<anonymous closure> (package:front_end/src/fasta/kernel/forwarding_node.dart:231:16)
#2      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#3      ForwardingNode._createForwardingImplIfNeeded (package:front_end/src/fasta/kernel/forwarding_node.dart:225:17)
#4      ForwardingNode._computeCovarianceFixes (package:front_end/src/fasta/kernel/forwarding_node.dart:139:9)
#5      ForwardingNode.finalize (package:front_end/src/fasta/kernel/forwarding_node.dart:34:28)
#6      SynthesizedInterfaceMember._ensureMemberAndCovariance (package:front_end/src/fasta/kernel/hierarchy/class_member.dart:381:12)
#7      SynthesizedInterfaceMember.getMember (package:front_end/src/fasta/kernel/hierarchy/class_member.dart:412:5)
#8      SourceLoader.checkAbstractMembers (package:front_end/src/fasta/source/source_loader.dart:1945:30)
#9      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:416:14)
<asynchronous suspension>
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#11     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:100:10)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#13     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:12)
<asynchronous suspension>
#14     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:10)
<asynchronous suspension>
#15     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:97:11)
<asynchronous suspension>
#16     SingleShotCompilerWrapper.compileInternal (file:///Users/nshahan/code/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:400:11)
<asynchronous suspension>
#17     Compiler.compile.<anonymous closure> (file:///Users/nshahan/code/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#18     _processLoadRequest (file:///Users/nshahan/code/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:888:37)
<asynchronous suspension>


#0      ListMixin.singleWhere (dart:collection/list.dart:202:5)
#1      ForwardingNode._createForwardingImplIfNeeded.<anonymous closure> (package:front_end/src/fasta/kernel/forwarding_node.dart:231:16)
#2      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#3      ForwardingNode._createForwardingImplIfNeeded (package:front_end/src/fasta/kernel/forwarding_node.dart:225:17)
#4      ForwardingNode._computeCovarianceFixes (package:front_end/src/fasta/kernel/forwarding_node.dart:139:9)
#5      ForwardingNode.finalize (package:front_end/src/fasta/kernel/forwarding_node.dart:34:28)
#6      SynthesizedInterfaceMember._ensureMemberAndCovariance (package:front_end/src/fasta/kernel/hierarchy/class_member.dart:381:12)
#7      SynthesizedInterfaceMember.getMember (package:front_end/src/fasta/kernel/hierarchy/class_member.dart:412:5)
#8      SourceLoader.checkAbstractMembers (package:front_end/src/fasta/source/source_loader.dart:1945:30)
#9      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:416:14)
<asynchronous suspension>
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#11     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:100:10)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#13     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:12)
<asynchronous suspension>
#14     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:10)
<asynchronous suspension>
#15     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:97:11)
<asynchronous suspension>
#16     SingleShotCompilerWrapper.compileInternal (file:///Users/nshahan/code/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:400:11)
<asynchronous suspension>
#17     Compiler.compile.<anonymous closure> (file:///Users/nshahan/code/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#18     _processLoadRequest (file:///Users/nshahan/code/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:888:37)
<asynchronous suspension>
```


@johnniwinther

**Comment by Naveenkant93** [comment]
Hi, I am also getting this same error after pub upgrade. Even for mobile also.
please let me know if you find any solution.

**Comment by johnniwinther** [comment]
A fix is in progress: https://dart-review.googlesource.com/c/sdk/+/230663
