### ISSUE TITLE
Flaky crashes in when compiling some named-arguments-anywhere tests

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#48276]
Some of the named-arguments-anywhere tests are flaking for DDC with compile time errors from the CFE:
```
co19/LanguageFeatures/Named-arguments-anywhere/constructor_t03
co19/LanguageFeatures/Named-arguments-anywhere/constructor_t04
co19/LanguageFeatures/Named-arguments-anywhere/constructor_t05
co19/LanguageFeatures/Named-arguments-anywhere/constructor_t06
co19/LanguageFeatures/Named-arguments-anywhere/constructor_t07
co19/LanguageFeatures/Named-arguments-anywhere/constructor_t08
```
https://dart-ci.firebaseapp.com/current_results/#/filter=dartdevk-strong-linux-release-chrome,co19/LanguageFeatures/Named-arguments-anywhere/constructor&flaky

It is a complete mystery why this crashes appears to be flaky. Here is a sample stack trace:
```
Crash when compiling org-dartlang-app:/tests/co19/src/LanguageFeatures/Named-arguments-anywhere/constructor_t03.dart,
at character offset 814:
Unsupported operation: Cannot add to a fixed-length list
#0      FixedLengthListMixin.insertAll (dart:_internal/list.dart:31:5)
#1      BodyBuilder.finishConstructor (package:front_end/src/fasta/kernel/body_builder.dart:1755:55)
#2      BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1119:7)
#3      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1078:19)
#4      DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:728:5)
#5      DietListener.endClassConstructor (package:front_end/src/fasta/source/diet_listener.dart:684:5)
#6      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4232:20)
#7      Parser.parseClassOrMixinOrExtensionOrEnumMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3981:15)
#8      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3636:15)
#9      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2126:13)
#10     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2084:14)
#11     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:611:14)
#12     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:497:14)
#13     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#14     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1101:12)
<asynchronous suspension>
#15     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:643:7)
<asynchronous suspension>
#16     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:471:7)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#18     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:21)
<asynchronous suspension>
#19     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#20     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:12)
<asynchronous suspension>
#21     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:10)
<asynchronous suspension>
#22     compile (package:front_end/src/api_unstable/ddc.dart:216:7)
<asynchronous suspension>
#23     _compile (package:dev_compiler/src/kernel/command.dart:338:14)
<asynchronous suspension>
#24     compile (package:dev_compiler/src/kernel/command.dart:51:12)
<asynchronous suspension>
#25     runBatch (package:dev_compiler/ddc.dart:98:16)
<asynchronous suspension>
#26     internalMain (package:dev_compiler/ddc.dart:33:5)
<asynchronous suspension>


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1082:7)
#1      DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:728:5)
#2      DietListener.endClassConstructor (package:front_end/src/fasta/source/diet_listener.dart:684:5)
#3      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4232:20)
#4      Parser.parseClassOrMixinOrExtensionOrEnumMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3981:15)
#5      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3636:15)
#6      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2126:13)
#7      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2084:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:611:14)
#9      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:497:14)
#10     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#11     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1101:12)
<asynchronous suspension>
#12     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:643:7)
<asynchronous suspension>
#13     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:471:7)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#15     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:163:21)
<asynchronous suspension>
#16     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#17     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:12)
<asynchronous suspension>
#18     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:10)
<asynchronous suspension>
#19     compile (package:front_end/src/api_unstable/ddc.dart:216:7)
<asynchronous suspension>
#20     _compile (package:dev_compiler/src/kernel/command.dart:338:14)
<asynchronous suspension>
#21     compile (package:dev_compiler/src/kernel/command.dart:51:12)
<asynchronous suspension>
#22     runBatch (package:dev_compiler/ddc.dart:98:16)
<asynchronous suspension>
#23     internalMain (package:dev_compiler/ddc.dart:33:5)
<asynchronous suspension>
```

cc @johnniwinther

**Comment by johnniwinther** [comment]
I'm working on a fix for the crash; a collision between named-arguments-anywhere and enhanced-enums.

The tests don't use the enhanced-enums flag themselves, so the flakiness could come from a leak of the experimental flags between tests.
