### ISSUE TITLE
[Enhanced Enums] co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t05 test fails on dartdevk-{strong,weak}-linux-release-chrome

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48299]
The following co19 test https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A10_t05.dart
fails with the following error
```
/============================================================================================================================================\
| dartdevk-strong-linux-release-chrome:co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t05 is new and failed (RuntimeError, expected Pass) |
\============================================================================================================================================/

--- Command "dartdevc" (took 163ms):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/cache/builder/sdk/third_party/browsers/chrome/chrome/google-chrome out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/dart-sdk/bin/snapshots/dartdevc.dart.snapshot -Dtest_runner.configuration=dartdevk-strong-linux-release-chrome --enable-experiment=enhanced-enums --sound-null-safety -Dtest_runner.configuration=dartdevk-strong-linux-release-chrome --ignore-unrecognized-flags --no-summarize -o /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Enhanced-Enum_semantics_A10_t05/semantics_A10_t05.js /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/Enhanced-Enum/semantics_A10_t05.dart -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/async_helper.dill=async_helper -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/expect.dill=expect -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/js.dill=js -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/meta.dill=meta

exit code:
0

stdout:
Experiment constructor-tearoffs is enabled by default. The use of the flag is deprecated.

--- Command "chrome" (took 638ms):
/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:33939/root_build/generated_tests/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Enhanced-Enum_semantics_A10_t05/test.html?crossOriginPort=39373

Runtime error:
Error: Expect.isTrue(false) fails.
    at Object.throw_ [as throw] (http://127.0.0.1:33939/root_build/gen/utils/dartdevc/sound/amd/dart_sdk.js:4648:11)
    at Object._fail (http://127.0.0.1:33939/root_dart/out/ReleaseX64/generated_compilations/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Enhanced-Enum_semantics_A10_t05/semantics_A10_t05.js:755:15)
    at Function.isTrue (http://127.0.0.1:33939/root_dart/out/ReleaseX64/generated_compilations/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Enhanced-Enum_semantics_A10_t05/semantics_A10_t05.js:232:16)
    at Object.main (http://127.0.0.1:33939/root_dart/out/ReleaseX64/generated_compilations/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Enhanced-Enum_semantics_A10_t05/semantics_A10_t05.js:208:19)
    at testMainWrapper (http://127.0.0.1:33939/root_build/generated_tests/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Enhanced-Enum_semantics_A10_t05/test.html?crossOriginPort=39373:86:105)

Deobfuscated error and stack:
Error: Expect.isTrue(false) fails.
    at Object.throw_   out/ReleaseX64/gen/utils/dartdevc/sound/amd/dart_sdk.js 4648:11
    at Object._fail    ../../../../../tests/co19/src/Utils/expect.dart 18:5
    at Function.isTrue ../../../../../tests/co19/src/Utils/expect_common.dart 24:7
    at Object.main     ../../../../../tests/co19/src/LanguageFeatures/Enhanced-Enum/semantics_A10_t05.dart 55:10
    at testMainWrapper out/ReleaseX64/generated_tests/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Enhanced-Enum_semantics_A10_t05/test.html 86:105


exit code:
0

--- To debug locally, run:
/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/cache/builder/sdk/pkg/test_runner/bin/http_server.dart -p 33939 -c 39373 --network 127.0.0.1 --build-directory=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/cache/builder/sdk/.packages

--- Re-run this test:
python3 tools/test.py -n dartdevk-strong-linux-release-chrome co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t05
```
This is a dartdevk issue.  Wrong semantics in evaluation of `operator==` of `E1`

**Comment by Markzipan** [comment]
As a heads up, the language team has decided to disallow overriding of `==` for enhanced enums (it's not in the spec yet though). Updating the test should resolve this failure.

**Comment by eernstg** [comment]
> the language team has decided to disallow overriding of `==` for enhanced enums

We did discuss operator `==` recently, but I'm not aware of a decision to make it an error to override it with enhanced enums.

One thing which is relevant to operator `==` (but which is not new) is that the enum does not 'have a primitive operator `==`' if there is a concrete declaration of operator `==` in the enum or a superclass that overrides the one which is inherited from `Object`. And if an enum (or a class) does not have a primitive operator `==` then its instances cannot be elements in a constant set, or keys in a constant map. So you can override operator `==`, but it carries a cost.

(And there's a separate discussion about `hashCode`, cf. https://github.com/dart-lang/language/issues/2108.)

**Comment by Markzipan** [comment]
Thanks for the clarification, @eernstg! I have a change out that resolves this bug, but I may let it sit until there's resolution here. Pinging @nshahan on this point as well.

**Comment by nshahan** [comment]
@eernstg I cc'd you in the doc comment thread where this topic came up. 

@rakudrama Do you recall the details about this? I thought we were asking to disallow overriding equality so that enums can still be used in native javascript switch statements.

**Comment by eernstg** [comment]
@nshahan wrote:
> disallow overriding equality so that enums can still be used in native javascript switch statements

I would assume that the ability to override operator `==` in an enum declaration, or in a superclass thereof, would make it an error for that particular enum's values to occur as `case` values in a switch, to be a member of a constant set, or to be a key of a constant map; but all other enum declarations would not be affected. This corresponds to the description I gave, a la "it is possible, but that particular enum is then less usable".

But we could of course make it an error, based on the assumption that this trade-off is never going to work well in practice.

**Comment by lrhn** [comment]
If your enum overrides `operator==`, you can't use that enum type in *Dart* switches, so there should be no need to use them in JavaScript switches either (at least not while worrying about matching any Dart equality semantics).

I'm not aware of any currently open issues on `operator==` of enhanced enums, so I'm not sure there is any resolution to wait for.

If we end up changing the rules about ["primitive `hashCode`"](https://github.com/dart-lang/language/issues/2108), or [constant equality](https://github.com/dart-lang/language/issues/1811), it will have effects beyond enhanced enums, and will likely require a dedicated change unrelated to enhanced enums.

**Comment by eernstg** [comment]
The language team just decided that it _is_ an error for an enum declaration to have an implementation of operator `==` or `hashCode` that overrides the one which is inherited from `Object`. The spec will be updated accordingly.

**Comment by eernstg** [comment]
The language team decided yesterday that it is an error for an enum declaration to have an implementation of `hashCode` or operator `==` which overrides the one in `Object` (so the error occurs when the declaration is in the enum declaration itself, and when it occurs in a mixin application of the enum).
