### ISSUE TITLE
Late variable error when disabling global type inference

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#48312]
While debugging another issue, I encountered this odd case. This simple program works fine when we run the global type inference, but not when it's disabled:

```dart
class A {
  late final _t;
  A() {
    _t = 1;
  }
}
main () {
  print(new A()._t);
}
```

Running with `--disable-type-inference` this program produces this error:
```
LateInitializationError: Field '_t' has already been initialized.
    at Object.wrapException (/tmp/out.js:336:17)
    at Object._lateWriteOnceCheck (/tmp/out.js:2205:15)
    at Object.A$ (/tmp/out.js:2170:9)
    at main (/tmp/out.js:2175:34)
    at action (/usr/local/google/home/sigmund/dart/git_all/sdk/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (/usr/local/google/home/sigmund/dart/git_all/sdk/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (/usr/local/google/home/sigmund/dart/git_all/sdk/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at /tmp/out.js:2687:7
    at /tmp/out.js:2672:7
    at dartProgram (/tmp/out.js:2683:5)
```

**Comment by fishythefish** [comment]
Ah, I hadn't even considered that we might run with global type inference disabled. This may be tricky and I'll have to think about how to handle this - type inference establishes some of the invariants related to late variables that we use later on.

/cc @rakudrama

**Comment by fishythefish** [comment]
Closing since this seems to be fixed with the improvements to inference and late lowering. Feel free to reopen if we run into this again.
