### ISSUE TITLE
Failures on [vm] Check for common case (_Future) before uncommon case (is! Future / 3rd party future)

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48338]
There are new test failures on [[vm] Check for common case (_Future) before uncommon case (is! Future / 3rd party future)](https://github.com/dart-lang/sdk/commit/68f502cc61cb75de3df3ffba7118926603fa16bf).

The tests
```
vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test RuntimeError (expected Pass)
vm/dart_2/causal_stacks/async_throws_stack_lazy_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-optcounter-linux-release-ia32
dartk-optcounter-linux-release-x64
```

```
--- Command "vm" (took 19.000684s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --dwarf-stack-traces --save-debugging-info=async_lazy_debug.so --lazy-async-stacks --optimization-counter-threshold=5 --random-seed=835916499 -Dtest_runner.configuration=dartk-optcounter-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test.dart

exit code:
255

stdout:
RegExps for expected stack:
"^#0      throwAsync \(.*/utils.dart:23(:3)?\)$"
"^<asynchronous suspension>$"
"^#1      mixedYields2 \(.*/utils.dart:68(:3)?\)$"
"^<asynchronous suspension>$"
"^#2      mixedYields \(.*/utils.dart:63(:3)?\)$"
"^<asynchronous suspension>$"
"^#3      doTestAwait "
"^<asynchronous suspension>$"
"^#4      doTestsLazy "
"^<asynchronous suspension>$"
"^#5      main "
"^<asynchronous suspension>$"

Actual stack:
#0      throwAsync (file:///b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/utils.dart:23:3)
<asynchronous suspension>
#1      mixedYields2 (file:///b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/utils.dart:68:3)
<asynchronous suspension>
#2      mixedYields (file:///b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/utils.dart:63:3)
<asynchronous suspension>
#3      Future._thenAwait (dart:async/future_impl.dart)
#4      _awaitHelper (dart:async-patch/async_patch.dart:88:17)
#5      doTestAwait (file:///b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/utils.dart:272:5)
<asynchronous suspension>
#6      doTestsLazy (file:///b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/utils.dart:619:5)
<asynchronous suspension>
#7      main (file:///b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test.dart:18:3)
<asynchronous suspension>

Expected line 7 to be `^#3      doTestAwait ` but was `#3      Future._thenAwait (dart:async/future_impl.dart)`

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:742:5)
#1      Expect.isTrue (package:expect/expect.dart:141:5)
#2      assertStack (file:///b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/utils.dart:249:14)
<asynchronous suspension>
#3      doTestsLazy (file:///b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/utils.dart:619:5)
<asynchronous suspension>
#4      main (file:///b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test.dart:18:3)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-optcounter-linux-release-x64 vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test
```

[logs](https://dart-ci.appspot.com/log/vm-kernel-optcounter-threshold-linux-release-x64/dartk-optcounter-linux-release-x64/13865/vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test)
[logs](https://dart-ci.appspot.com/log/vm-kernel-optcounter-threshold-linux-release-ia32/dartk-optcounter-linux-release-ia32/7832/vm/dart_2/causal_stacks/async_throws_stack_lazy_test)

**Comment by mkustermann** [comment]
This is most likely related to deoptimizations happening in a different place. There have been other issues filed about this in the past (e.g. https://github.com/dart-lang/sdk/issues/39926). 

Unassigned myself, since that is unrelated to my CL.

**Comment by brianquinlan** [comment]
Assigning to @cskau-g because rumor has it that he did recent work in this area.
