### ISSUE TITLE
[Enhanced enums] CFE crash on language/enum/enhanced_enums_basic_test

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#48370]
Part of https://github.com/dart-lang/sdk/issues/47453.

```
--- Command "vm" (took 393ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --sound-null-safety -Dtest_runner.configuration=dartk-strong-linux-release-x64 --enable-experiment=enhanced-enums --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/language/enum/enhanced_enums_basic_test.dart

exit code:
252

stderr:
Crash when compiling null,
at character offset null:
type 'SourceProcedureBuilder' is not a subtype of type 'SourceFieldBuilder' in type cast
#0      SourceEnumBuilder.build (package:front_end/src/fasta/source/source_enum_builder.dart:500:36)
#1      SourceLibraryBuilder.buildBuilder (package:front_end/src/fasta/source/source_library_builder.dart:3013:31)
#2      SourceLibraryBuilder.build (package:front_end/src/fasta/source/source_library_builder.dart:1063:7)
#3      SourceLoader.buildComponent (package:front_end/src/fasta/source/source_loader.dart:1951:32)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:478:14)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#6      _buildInternal (package:front_end/src/kernel_generator_impl.dart:134:7)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#8      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:42:12)
<asynchronous suspension>
#9      generateKernel (package:front_end/src/kernel_generator_impl.dart:41:10)
<asynchronous suspension>
#10     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#11     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:400:11)
<asynchronous suspension>
#12     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#13     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:894:37)
<asynchronous suspension>


#0      SourceEnumBuilder.build (package:front_end/src/fasta/source/source_enum_builder.dart:500:36)
#1      SourceLibraryBuilder.buildBuilder (package:front_end/src/fasta/source/source_library_builder.dart:3013:31)
#2      SourceLibraryBuilder.build (package:front_end/src/fasta/source/source_library_builder.dart:1063:7)
#3      SourceLoader.buildComponent (package:front_end/src/fasta/source/source_loader.dart:1951:32)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:478:14)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#6      _buildInternal (package:front_end/src/kernel_generator_impl.dart:134:7)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#8      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:42:12)
<asynchronous suspension>
#9      generateKernel (package:front_end/src/kernel_generator_impl.dart:41:10)
<asynchronous suspension>
#10     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#11     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:400:11)
<asynchronous suspension>
#12     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#13     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:894:37)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-strong-linux-release-x64 language/enum/enhanced_enums_basic_test
```

/cc @chloestefantsova @johnniwinther

**Comment by lrhn** [comment]
Also crashes on language/enum/enhanced_enums_error_test which is currently in a CL.
