### ISSUE TITLE
Odd treatment of `.call` tearoff in assignments, leading to unsoundness

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#48409]
Consider the following code:
```dart
Type staticType<T>(T t) => T;
class C {
  void call() {}
  void m() {}
}
test(C c) {
}
main() {
  void Function() f;
  var x = f = C();                                    // (1)
  print('The static type of f is ${staticType(f)}');
  print('The runtime type of f is ${f.runtimeType}');
  print('The static type of x is ${staticType(x)}');
  print('The runtime type of x is ${x.runtimeType}');
  x.m();                                              // (2)
}
```
This program is statically accepted by both the CFE and the analyzer.  This is surprising to me.  At (1), since `f = C()` requires `C()` to be assignable to `void Function()`, I would have expected an implicit `.call` tearoff to be inserted, rendering `C()` equivalent to `C().call`.  Therefore I would have expected the static type of `x` to be `void Function()`, so I would have expected a compile-time error at line (2).

If I change (2) to refer to some other method (e.g. `x.q();`), then both the CFE and analyzer issue a compile-time error, saying that the type `C` does not declare a method `q`.  So the CFE and analyzer seem to agree that the static type of `x` is `C`.

What's worse, when I run the program under the VM, it prints this:
```
The static type of f is () => void
The runtime type of f is () => void
The static type of x is C
The runtime type of x is () => void
Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function 'm'
Receiver: Closure: () => void from Function 'call':.
Tried calling: m()
Found: m() => void
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      main (file:///usr/local/google/home/paulberry/tmp/proj/test.dart:15:5)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
It looks like what is happening is that the CFE *is* inserting an implicit `.call` tearoff, but it's not adjusting the static type of the `f = C()` expression to account for it.  This results in unsoundness (`x` is being assigned a value whose runtime type is not a subtype of its static type).  As a result, there is a `NoSuchMethodError` at (2), which should be impossible under null safety.

I think the right fix here is to change the CFE and the analyzer so that when they insert an implicit `.call` on the RHS of an assignment, they adjust the static type of the assignment accordingly; this way the behavior of the code is the same as if the `.call` tearoff had been written explicitly.

I'm marking this bug as "area-front-end".  I'll submit a separate issue to track this problem from the analyzer's perspective.

**Comment by stereotype441** [comment]
I think I've found the cause of this bug in the CFE, so I'm going to work on a fix.
