### ISSUE TITLE
CFE crashes if initializing formals have 'const' modifier

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#48418]
The following program makes the CFE crash.

```dart
class A {
  int foo = 42;
  
  A(const int this.foo) {}
}
```

Here's the stack trace.

```
/tmp/asdf.dart:4:5: Error: Can't have modifier 'const' here.
Try removing 'const'.
  A(const int this.foo) {}
    ^^^^^
Unhandled exception:
Crash when compiling null,
at character offset null:
Null check operator used on a null value
#0      ConstantsTransformer.visitVariableGet (package:front_end/src/fasta/kernel/constant_evaluator.dart:759:73)
#1      VariableGet.accept1 (package:kernel/ast.dart:4162:9)
#2      RemovingTransformer.transform (package:kernel/visitor.dart:1671:17)
#3      FieldInitializer.transformOrRemoveChildren (package:kernel/ast.dart:3371:17)
#4      RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#5      TreeVisitor1.defaultInitializer (package:kernel/visitor.dart:671:52)
#6      TreeVisitor1.visitFieldInitializer (package:kernel/visitor.dart:677:7)
#7      FieldInitializer.accept1 (package:kernel/ast.dart:3350:9)
#8      RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1707:21)
#9      RemovingTransformer.transformList (package:kernel/visitor.dart:1931:19)
#10     RemovingTransformer.transformInitializerList (package:kernel/visitor.dart:1848:5)
#11     ConstantsTransformer.visitConstructor.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:470:7)
#12     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3684:18)
#13     ConstantsTransformer.visitConstructor (package:front_end/src/fasta/kernel/constant_evaluator.dart:468:23)
#14     Constructor.accept1 (package:kernel/ast.dart:2492:9)
#15     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1707:21)
#16     RemovingTransformer.transformList (package:kernel/visitor.dart:1931:19)
#17     RemovingTransformer.transformConstructorList (package:kernel/visitor.dart:1804:5)
#18     ConstantsTransformer.visitClass.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:431:7)
#19     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3684:18)
#20     ConstantsTransformer.visitClass (package:front_end/src/fasta/kernel/constant_evaluator.dart:427:23)
#21     Class.accept1 (package:kernel/ast.dart:1436:53)
#22     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1707:21)
#23     RemovingTransformer.transformList (package:kernel/visitor.dart:1931:19)
#24     RemovingTransformer.transformClassList (package:kernel/visitor.dart:1786:5)
#25     ConstantsTransformer.convertLibrary (package:front_end/src/fasta/kernel/constant_evaluator.dart:390:5)
#26     transformLibraries (package:front_end/src/fasta/kernel/constant_evaluator.dart:119:26)
#27     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1553:19)
#28     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:637:7)
<asynchronous suspension>
#29     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
...
```

**Comment by chloestefantsova** [comment]
Closing as a duplicate of https://github.com/dart-lang/sdk/issues/47922.
