### ISSUE TITLE
Platform.executable is null

### ISSUE THREAD

**Issue by knopp** [dart-lang/sdk#48427]
`resolvedExecutable` works as expected, but calling `Platform.executable` fails with exception

```
Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      _Platform.executable (dart:io/platform_impl.dart:36:30)
#1      _Platform.executable (dart:io/platform_impl.dart)
#2      Platform.executable (dart:io/platform.dart:177:45)
```

If `null` is indeed expected value perhaps the API should be changed to `String?`.

**Comment by lrhn** [comment]
That does look like a bad error message. It should either have a useful value, or probably throw if there is none.

Having a resolved executable, but no un-resolved one, sounds like a bug (if nothing else, it could provide the resolved executable as `executable` too).

How do you run the program?

**Comment by a-siva** [comment]
`resolvedExecutable` is implemented by finally calling the function below and this works the same both in command line VM and flutter engine
```
const char* Platform::ResolveExecutablePath() {
  return File::ReadLink("/proc/self/exe");
}
```
Whereas `Platform.executable ` is implemented as follows
```
const char* Platform::GetExecutableName() {
  return executable_name_;
}
```
the static variable ` executable_name_` is setup in the standalone command line VM by calling  `Platform::SetExecutableName(argv[0]);`, the flutter engine does not do this, as a result `executable_name_` is null leading to the above error.

I think we should fix the flutter engine to set the executable name correctly instead of changing the type to `String?`

**Comment by a-siva** [comment]
@jason-simmons @chinmaygarde can we pass in the executable name to `BootstrapDartIo` and have it set up the executable name ?

**Comment by chinmaygarde** [comment]
Sure, the engine should be able to set this up on most platforms. On some platforms like Android however, the engine never resolves the executable name. Presumably, a placeholder will be fine there?

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/83921

What is `Platform.executable` used for, and what value should it have on the various platforms that Flutter supports?

Should Flutter call `dart::bin::Platform::ResolveExecutablePath()` and then pass that to `SetExecutableName`?  Or would it make sense to always set the executable name to a generic string like "Flutter"?

**Comment by a-siva** [comment]
On the command line Dart VM this is what the following program outputs
```
import 'dart:io';

main() {
  print(Platform.executable);
  print(Platform.resolvedExecutable);
}
>out/DebugX64/dart-sdk/bin/dart ~/tmp/executable.dart 
out/DebugX64/dart-sdk/bin/dart
/usr/local/google/home/asiva/workspace/dart-tot/sdk/out/DebugX64/dart-sdk/bin/dart
>
```

**Comment by cbracken** [comment]
This is resolved for Flutter in https://github.com/flutter/engine/pull/33127 which sets this value to the first argument in `FlutterProjectArgs::command_line_argv` (if specified) or "Flutter" otherwise.

Further platform-specific patches will fix this up for embeddings that don't use the embedder API, as well as a minor fixup to the args that we pass in the macOS Flutter embedder.
