### ISSUE TITLE
Flaky failures on dartdev/test/commands/create_integration_test 

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#48489]
The tests
```
pkg/dartdev/test/commands/create_integration_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac-arm64

The attempt by the test to create an http server at port 8080 is failing because another server is active already.
This may be a race condition or concurrency problem, and perhaps adding retries could help.
Or the server could be created at an arbitrary port, and the port number could be passed to its clients in the test.

Log:
stdout: [2K
[INFO] Starting resource servers...

stderr: Unhandled exception:
SocketException: Failed to create server socket (OS Error: Address already in use, errno = 48), address = 127.0.0.1, port = 8080
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:996:7)
<asynchronous suspension>
#1      HttpMultiServer._loopback (package:http_multi_server/http_multi_server.dart:209:20)
<asynchronous suspension>
#2      WebDevServer.start (package:webdev/src/serve/webdev_server.dart:185:16)
<asynchronous suspension>
#3      ServerManager.start (package:webdev/src/serve/server_manager.dart:25:19)
<asynchronous suspension>
#4      _startServerManager (package:webdev/src/serve/dev_workflow.dart:105:7)
<asynchronous suspension>
#5      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:198:25)
<asynchronous suspension>
#6      ServeCommand.run (package:webdev/src/command/serve_command.dart:102:9)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#8      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:40:12)
<asynchronous suspension>
#9      main (file:///opt/s/w/ir/x/t/aSEA9EE/pub_cache/hosted/pub.dartlang.org/webdev-2.7.8/bin/webdev.dart:19:16)
<asynchronous suspension>



```

**Comment by aam** [comment]
cc @bkonyi

**Comment by alexmarkov** [comment]
This test started failing once again:

```
...

[INFO] Starting resource servers...

stderr: Unhandled exception:
SocketException: Failed to create server socket (OS Error: Address already in use, errno = 48), address = 127.0.0.1, port = 8080
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:996:7)
<asynchronous suspension>
#1      HttpMultiServer._loopback (package:http_multi_server/http_multi_server.dart:209:20)
<asynchronous suspension>
#2      WebDevServer.start (package:webdev/src/serve/webdev_server.dart:185:16)
<asynchronous suspension>
#3      ServerManager.start (package:webdev/src/serve/server_manager.dart:25:19)
<asynchronous suspension>
#4      _startServerManager (package:webdev/src/serve/dev_workflow.dart:105:7)
<asynchronous suspension>
#5      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:198:25)
<asynchronous suspension>
#6      ServeCommand.run (package:webdev/src/command/serve_command.dart:102:9)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#8      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:40:12)
<asynchronous suspension>
#9      main (file:///opt/s/w/ir/x/t/aVfXYex/pub_cache/hosted/pub.dartlang.org/webdev-2.7.8/bin/webdev.dart:19:16)
<asynchronous suspension>


06:27 [32m+6[0m[31m -1[0m: create integration web-simple [1m[31m[E][0m[0m

  TimeoutException after 0:05:00.000000: Test timed out after 5 minutes.

  package:test_api/src/backend/invoker.dart 333:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1418:47                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 331:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 287:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1426:13                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 286:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 192:12      _RawReceivePortImpl._handleMessage
  

Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

06:27 [32m+6[0m[31m -1[0m: create integration console-simple[0m

06:29 [32m+7[0m[31m -1[0m: [31mSome tests failed.[0m

stderr:
Unhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python3 tools/test.py -n unittest-asserts-release-mac-arm64 pkg/dartdev/test/commands/create_integration_test
```

https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/2463/pkg/dartdev/test/commands/create_integration_test
https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/2464/pkg/dartdev/test/commands/create_integration_test
