### ISSUE TITLE
Compiler crash for operators on `@JS` external methods

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#48515]
My Dart version is `Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "linux_x64"`, which crashes when compiling the following program.

```dart
import 'package:js/js.dart';

@JS('BigInt')
external JsBigInt _jsBigInt(String s);

@JS('BigInt')
class JsBigInt {
  factory JsBigInt.parse(String s) => _jsBigInt(s);

  external bool operator <(Object other);
}

void main() {
  final bigInt = JsBigInt.parse('123');

  print(bigInt < 200);
}

```

I know this is a bit hacky and probably not supposed to work, but still there could be a better error message than a crash. The crash when compiling it with `dart compile js` is:

```
Unhandled exception:
Error in MiniJsParser:
#.<(#)
   ^
   Expected alphanumeric identifier

#0      MiniJsParser.error (package:js_ast/src/builder.dart:793:5)
#1      MiniJsParser.getDotRhs (package:js_ast/src/builder.dart:1017:9)
#2      MiniJsParser.parseMember (package:js_ast/src/builder.dart:961:20)
#3      MiniJsParser.parseCall (package:js_ast/src/builder.dart:975:27)
#4      MiniJsParser.parsePostfix (package:js_ast/src/builder.dart:1026:29)
#5      MiniJsParser.parseUnaryHigh (package:js_ast/src/builder.dart:1049:12)
#6      MiniJsParser.parseUnaryLow (package:js_ast/src/builder.dart:1062:12)
#7      MiniJsParser.parseBinary (package:js_ast/src/builder.dart:1066:22)
#8      MiniJsParser.parseConditional (package:js_ast/src/builder.dart:1093:22)
#9      MiniJsParser.parseAssignment (package:js_ast/src/builder.dart:1102:22)
#10     MiniJsParser.parseExpression (package:js_ast/src/builder.dart:1119:29)
#11     MiniJsParser.parseVarDeclarationOrExpression (package:js_ast/src/builder.dart:1193:14)
#12     MiniJsParser.expression (package:js_ast/src/builder.dart:1198:29)
#13     JsBuilder.uncachedExpressionTemplate (package:js_ast/src/builder.dart:256:36)
#14     SsaCodeGenerator.visitInvokeExternal.invokeWithJavaScriptReceiver (package:compiler/src/ssa/codegen.dart:2358:12)
#15     SsaCodeGenerator.visitInvokeExternal (package:compiler/src/ssa/codegen.dart:2379:9)
#16     HInvokeExternal.accept (package:compiler/src/ssa/nodes.dart:2346:39)
#17     SsaCodeGenerator.visit (package:compiler/src/ssa/codegen.dart:791:10)
#18     SsaCodeGenerator.visitExpression (package:compiler/src/ssa/codegen.dart:797:5)
#19     SsaCodeGenerator.use (package:compiler/src/ssa/codegen.dart:767:7)
#20     SsaCodeGenerator.visitReturn (package:compiler/src/ssa/codegen.dart:2615:7)
#21     HReturn.accept (package:compiler/src/ssa/nodes.dart:3180:39)
#22     SsaCodeGenerator.visit (package:compiler/src/ssa/codegen.dart:791:10)
#23     SsaCodeGenerator.iterateBasicBlock (package:compiler/src/ssa/codegen.dart:1466:5)
#24     SsaCodeGenerator.enterSubGraph (package:compiler/src/ssa/codegen.dart:1332:7)
#25     SsaCodeGenerator.visitSubGraph (package:compiler/src/ssa/codegen.dart:494:5)
#26     SsaCodeGenerator.visitGraph (package:compiler/src/ssa/codegen.dart:485:5)
#27     SsaCodeGeneratorTask.generateMethod.<anonymous closure> (package:compiler/src/ssa/codegen.dart:165:21)
#28     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#29     SsaCodeGeneratorTask.generateMethod (package:compiler/src/ssa/codegen.dart:150:12)
#30     SsaCodeGeneratorTask.generateCode (package:compiler/src/ssa/codegen.dart:103:14)
#31     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:87:38)
#32     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:453:30)
#33     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:313:43)
#34     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:446:29)
#35     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:609:70)
#36     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#37     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:609:32)
#38     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#39     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:607:28)
#40     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:898:15)
#41     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:605:18)
#42     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:268:12)
#43     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:284:5)
#44     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:601:16)
#45     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#46     Compiler.emptyQueue (package:compiler/src/compiler.dart:600:14)
#47     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:626:7)
#48     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#49     Compiler.processQueue (package:compiler/src/compiler.dart:619:14)
#50     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:508:5)
#51     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:394:9)
#52     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:582:7)
#53     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#54     Compiler.compileFromKernel (package:compiler/src/compiler.dart:559:14)
#55     Compiler.runInternal (package:compiler/src/compiler.dart:363:17)
<asynchronous suspension>
#56     main (package:compiler/src/dart2js.dart:1373:3)
<asynchronous suspension>
```

**Comment by srujzs** [comment]
I think this is because we only check for indexing, and not all operators. We could probably do a simple fix for this by just using `procedure.kind == ProcedureKind.Operator`.

**Comment by rileyporter** [comment]
With the external extension members lowering, there was an open question of which operators we wanted to allow in extensions. That feels related to which operators we want to allow in JS interop classes in general, although I'm not sure if there are specific operators we want to disallow.

It might be worth considering an allowlist of operators instead of checking for any `ProcedureKind.Operator`?

**Comment by srujzs** [comment]
I think we should still disallow all operators being used in the class, but leave it as an open question for now on what to do for extensions. Operators in the `package:js` classes need to be implemented in both compilers in order to handle them correctly, whereas we might be able to do the lowering for specific operators in external extension members. I don't see us realistically extending support for operators in `package:js` classes, however.

**Comment by rileyporter** [comment]
Got it, you're planning on expanding the `package:js` class static check to disallow all operators? That sounds good to me. I'll keep thinking about operators for extension members, right now we don't lower them, but I could see adding support for a set of them.

**Comment by srujzs** [comment]
Yeah, just for the instance members.

I assume using external extension operators will lead to a crash currently, but we can handle that separately.

**Comment by simolus3** [comment]
Is there an issue to follow for support of operator methods in static interop extensions?

**Comment by rileyporter** [comment]
Great question, I just filed #48535 to track that work. If you have specific operators besides indexing that you want supported, feel free to comment there.
