### ISSUE TITLE
co19_2/LibTest/io/WebSocket tests flaking on Windows

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48525]
Multiple windows WebSocket tests started flaking since yesterday.

The tests
```
co19_2/LibTest/io/WebSocket/closeReason_A01_t02 RuntimeError (expected Pass)
co19_2/LibTest/io/WebSocket/close_A01_t02 RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-win-release-x64
```

[close test history](https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=co19_2/LibTest/io/WebSocket/close_A01_t02&configurations=dartk-win-release-x64)
[closeReason test history](https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=co19_2/LibTest/io/WebSocket/closeReason_A01_t02&configurations=dartk-win-release-x64)

Earliest commit flaking:

* https://github.com/dart-lang/sdk/commit/8b1b7cc0d93c0978c6c3282598f4cee44cd25a0c

The tests in question have not been touched for months.

**Comment by dcharkes** [comment]
`closeReason` failing again

```
Expect.equals(expected: <closed>, actual: <null>) fails.
#0      _fail (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect.dart:18)
#1      Expect.equals (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect_common.dart:16)
#2      main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/WebSocket/closeReason_A01_t02.dart:31)
```

[log](https://dart-ci.appspot.com/log/vm-aot-win-release-x64/vm-aot-win-release-x64/6/co19/LibTest/io/WebSocket/closeReason_A01_t02)

[test history](https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=co19/LibTest/io/WebSocket/closeReason_A01_t02&configurations=vm-aot-win-release-x64): Seems to be going back and forth on unrelated commits.

On the flakiness dashboard it is flaky as well: [flakiness dashboard](https://dashboards.corp.google.com/_0d7e1e34_2c58_4d29_bf12_cf7bed10396d?fh=eJytjj0KwzAMhe-i2ZPJ0tygs8eQQThqK_BPcOVCKbl7JFJo6dzx89P3nqcX8AIjFMwEDmJNPZcPy3MlpTsliqK8oGBYKZ7N8f40DN6sGzaxp2l2kHsSDocwSuukLSzJamBz77lYy4WvvaFwLd-7v8GfP-CgUa4P0lNLtnkHJXlTEw..&fb=name:in:co19%2FLibTest%2Fio%2FWebSocket%2FcloseReason_A01_t02)

**Comment by sstrickl** [comment]
`co19/LibTest/io/WebSocket/closeReason_A01_t01` now failing on `vm-aot-win-product-x64` similarly ([log](https://dart-ci.appspot.com/log/vm-aot-win-product-x64/vm-aot-win-product-x64/655/co19/LibTest/io/WebSocket/closeReason_A01_t01)):

```
Expect.equals(expected: <>, actual: <null>) fails.
#0      _fail (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect.dart:18)
#1      Expect.equals (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect_common.dart:15)
#2      main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/WebSocket/closeReason_A01_t01.dart:31)
```

The [test history](https://dart-ci.web.app/#showLatestFailures=false&test=co19/LibTest/io/WebSocket/closeReason_A01_t01&configurations=vm-aot-win-product-x64) shows that it's been going back and forth between Pass and flaky for a while and finally failed consistently enough to turn red instead. (Strangely enough it doesn't seem to show up as recent on the [flakiness dashboard](https://dashboards.corp.google.com/_0d7e1e34_2c58_4d29_bf12_cf7bed10396d?fh=eJytjrEKwzAMRP9FsyeTpfmDzhlDBuGorcCWjSsXSsm_x6KBls4dn0_vzvMLeIURBBOBg5BjS_JhfRbqdKdIQTuvqDgVCmdzvD8NgzfrhlXtaV4cpBaVp7cwam3UW1ij1cDmjrmQ5cLXVlE5y_fub3B8gKW0P-w7qJTyg_qpJduyA9MLUsM.&fb=name:in:co19%2FLibTest%2Fio%2FWebSocket%2FcloseReason_A01_t01) though, despite the more recent flakes seen in the test history...?)

**Comment by derekxu16** [comment]
happened again: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-win-debug-x64c/782/overview
