### ISSUE TITLE
`dart:html` mediaCapabilities.decodingInfo(config) Expected a value of type 'FutureOr<MediaCapabilitiesInfo>?', but got one of type 'LegacyJavaScriptObject'

### ISSUE THREAD

**Issue by dius00** [dart-lang/sdk#48533]
## Environment
* Dart SDK Version `Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_arm64"`
* Whether you are using Windows, MacOSX, or Linux (if applicable) `macOSX 12.2.1`
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) `chrome`, `edge` 

## Reproduction steps
1. Create a new dart application using the web-simple template using the dart cli.
2. Add the following to `void main()` 
```dart
window.navigator.mediaCapabilities!.decodingInfo({
    'type': 'media-source',
    'audio': {
      'contentType': 'audio/webm;codecs="opus"',
      'bitRate': 32000,
      'sampleRate': 44100,
    },
  }).then((value) => print(value));
```
3. `webdev serve`
4. Navigate to `127.0.0.1:8080` open the console in the devtools, the following will be there.
```
Uncaught (in promise) Error: Expected a value of type 'FutureOr<MediaCapabilitiesInfo>?', but got one of type 'LegacyJavaScriptObject'
    at Object.throw_ [as throw] (errors.dart:248:21)
    at Object.castError (errors.dart:84:3)
    at Object.cast [as as] (operations.dart:452:10)
    at dart.NullableType.new.as (types.dart:367:9)
    at js_util.dart:259:58
```

Possibly related to #48188 

Running the following js code in the console will print the result as intended.
```js
window.navigator.mediaCapabilities.decodingInfo({
  'type': 'media-source',
  'audio': {
    'contentType': 'audio/webm;codecs="opus"',
    'bitRate': 32000,
    'sampleRate': 44100,
  },
}).then((value) => {
  console.log(value);
});
```

Note:
Unable to reproduce in safari per [#47742](https://github.com/dart-lang/sdk/issues/47742)

**Comment by Markzipan** [comment]
@srujzs can you add any context here?

**Comment by srujzs** [comment]
It seems like this is an issue with a consistent typing for the return type of `decodingInfo` and `encodingInfo`. Presumably, at some point, this was consistently a `MediaCapabilitiesInfo` object for both methods. This seems to have changed, however, with Chrome returning object literals representing this information and Firefox returning `MediaCapabiltiesInfo`. This then presents a conflict in our `dart:html` bindings, since we need a singular type. We could choose `Object` and then do conversions as necessary, but it's unideal. I have a CL proposing this change, but I'm not sure if it makes to sense to go through with it. In the meantime, you can use interop to accomplish this:

`promiseToFuture(window.callMethod(window.navigator.mediaCapabilities!, 'decodingInfo', convertDartToNative_Dictionary(...)))`

**Comment by juliansteenbakker** [comment]
I've got a similar error when calling `await imageCapture.getPhotoCapabilities()` with the following code:
```dart
      _localStream = await html.window.navigator.getUserMedia(video: constraints);
      final track = _localStream?.getVideoTracks();
      if (track != null) {
        final imageCapture = html.ImageCapture(track.first);
        final photoCapabilities = await imageCapture.getPhotoCapabilities();
      }
```

> Error: Expected a value of type 'FutureOr\<PhotoCapabilities>\?', but got one of type 'LegacyJavaScriptObject'
>     at Object.throw_ [as throw] (http://localhost:56651/dart_sdk.js:5065:11)
>     at Object.castError (http://localhost:56651/dart_sdk.js:5024:15)
>     at Object.cast [as as] (http://localhost:56651/dart_sdk.js:5349:17)
>     at dart.NullableType.new.as (http://localhost:56651/dart_sdk.js:6909:60)
>     at http://localhost:56651/dart_sdk.js:62529:139

**Comment by srujzs** [comment]
@juliansteenbakker I suspect we have a similar issue here where `PhotoCapabilities` doesn't exist as a type, and we're getting back an object literal instead. https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture/getPhotoCapabilities I'd suggest creating a separate issue to track this, and to use interop/https://github.com/dart-lang/sdk/blob/main/sdk/lib/html/doc/WORKAROUNDS.md in the meantime.

> then reading it with dart:js when needed.

@dius00 I'd suggest using `package:js` or `dart:js_util` instead to do this part, as `dart:js` is (perhaps informally?) deprecated.
