### ISSUE TITLE
[analysis] Tried to format an error using NamedTypeImpl

### ISSUE THREAD

**Issue by MbIXjkee** [dart-lang/sdk#48549]
## Dart analysis issue

Invalid argument(s): Tried to format an error using NamedTypeImpl

## Version information

- Dart SDK 2.16.1
- Dart IntelliJ 213.5744.122
- IntelliJ IDEA 2021.3.1
- Mac OS X 11.5.2

## Details

Invalid argument(s): Tried to format an error using NamedTypeImpl

```
#0      ErrorReporter._convertElements (package:analyzer/error/listener.dart:158:9)
#1      ErrorReporter.reportErrorForOffset (package:analyzer/error/listener.dart:105:5)
#2      ErrorReporter.reportErrorForToken (package:analyzer/error/listener.dart:123:5)
#3      ErrorVerifier._checkMixinInference (package:analyzer/src/generated/error_verifier.dart:4714:31)
#4      ErrorVerifier._checkClassInheritance (package:analyzer/src/generated/error_verifier.dart:1291:7)
#5      ErrorVerifier.visitClassDeclaration (package:analyzer/src/generated/error_verifier.dart:447:9)
#6      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1494:50)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#8      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2105:21)
#9      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:765:10)
#10     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:496:11)
#11     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2098:50)
#12     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:485:10)
#13     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:149:7)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#15     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:148:11)
#16     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1455:63)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#18     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1431:20)
#19     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1504:26)
#20     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1116:39)
#21     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2137:24)
<asynchronous suspension>

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1484:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1431:20)
#3      AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1504:26)
#4      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1116:39)
#5      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2137:24)
<asynchronous suspension>
```

## Debug log

```
1647198746782 <= {"id":"888","result":{"hovers":[{"offset":102,"length":15,"containingLibraryPath":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart",...
1647198746782 <= {"id":"889","result":{"hovers":[{"offset":102,"length":15,"containingLibraryPath":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart",...
1647198746787 => {"id":"890","method":"analysis.getHover","params":{"file":"/Users/zotev/dev/project/mjkdev/lib/features/home/screens/home_screen/home_screen_model.dart","offset":102},"clientRequestTi...
1647198746787 => {"id":"891","method":"analysis.getHover","params":{"file":"/Users/zotev/dev/project/mjkdev/lib/features/home/screens/home_screen/home_screen_model.dart","offset":102},"clientRequestTi...
1647198746790 <= {"id":"890","result":{"hovers":[{"offset":102,"length":15,"containingLibraryPath":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart",...
1647198746790 <= {"id":"891","result":{"hovers":[{"offset":102,"length":15,"containingLibraryPath":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart",...
1647198746795 => {"id":"892","method":"analysis.getHover","params":{"file":"/Users/zotev/dev/project/mjkdev/lib/features/home/screens/home_screen/home_screen_model.dart","offset":102},"clientRequestTi...
1647198746798 <= {"id":"892","result":{"hovers":[{"offset":102,"length":15,"containingLibraryPath":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart",...
1647198746810 => {"id":"893","method":"analysis.getHover","params":{"file":"/Users/zotev/dev/project/mjkdev/lib/features/home/screens/home_screen/home_screen_model.dart","offset":102},"clientRequestTi...
1647198746810 => {"id":"894","method":"analysis.getHover","params":{"file":"/Users/zotev/dev/project/mjkdev/lib/features/home/screens/home_screen/home_screen_model.dart","offset":102},"clientRequestTi...
1647198746813 <= {"id":"893","result":{"hovers":[{"offset":102,"length":15,"containingLibraryPath":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart",...
1647198746813 <= {"id":"894","result":{"hovers":[{"offset":102,"length":15,"containingLibraryPath":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart",...
1647198747091 => {"id":"895","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":[]}}}
1647198747091 => {"id":"896","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":["/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.da...
1647198747091 => {"id":"897","method":"analysis.setPriorityFiles","params":{"files":["/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart"]},"clientReque...
1647198747091 => {"id":"898","method":"analysis.setSubscriptions","params":{"subscriptions":{"CLOSING_LABELS":["/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src...
1647198747095 <= {"id":"895"}
1647198747095 <= {"id":"896"}
1647198747096 <= {"id":"897"}
1647198747096 <= {"id":"898"}
1647198747442 => {"id":"899","method":"edit.getAssists","params":{"file":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart","offset":7214,"length":0},...
1647198747525 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1647198747536 <= {"event":"analysis.highlights","params":{"file":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart","regions":[{"type":"DIRECTIVE","of...
1647198747542 <= {"event":"analysis.navigation","params":{"file":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart","regions":[{"offset":7,"length":36...
1647198747544 <= {"event":"analysis.closingLabels","params":{"file":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart","labels":[]}}
1647198747550 <= {"event":"analysis.outline","params":{"file":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart","kind":"LIBRARY","outline":{"element"...
1647198747555 <= {"event":"analysis.overrides","params":{"file":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart","overrides":[{"offset":1021,"length...
1647198747558 <= {"event":"flutter.outline","params":{"file":"/Users/zotev/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/elementary-1.1.0/lib/src/core.dart","outline":{"kind":"DART_ELEMENT","offs...
1647198747562 <= {"id":"899","result":{"assists":[]}}
1647198747564 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
```

**Comment by MbIXjkee** [comment]
Some info about this case.
This happened when:
class A<B,C>
mixin M on A (without generic)
class D<B,C> extend A<B,C> with M.

This will not be compiled. But instead of show error, analyzer fall and repeat it again and again.

**Comment by eernstg** [comment]
Looks like this crash has been fixed since 2.16.1.

**Comment by srawlins** [comment]
Agreed. Fixed in upcoming dart release.
