### ISSUE TITLE
The analyzer does not understand `unmodifiable list`

### ISSUE THREAD

**Issue by adnanjpg** [dart-lang/sdk#48551]
This tracker is for issues related to:

* Analyzer

In your issue, please include:

* Dart SDK Version:
   * `Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"`
* MacOSX Intel

let's go over an example:

```
import 'dart:math';

void main(List<String> arguments) {
  const foo = [1, 2, 3];

  final ran = Random();
  foo.shuffle(ran);
}
```

here, as clearly it is that `foo` cannot be modified as it is constant, the analyzer does not understand that and does not warn, so this bug is only catchable on runtime. 

the output:
```
Unhandled exception:
Unsupported operation: Cannot modify an unmodifiable list
#0      UnmodifiableListMixin.shuffle (dart:_internal[/list.dart:154:5]())
#1      main
bin/bug.dart:7
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch[/isolate_patch.dart:295:32]())
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch[/isolate_patch.dart:192:12]())

Exited (255)
```

**Comment by eernstg** [comment]
It could be useful to track the type of a list literal in such a way that the constant variable in this example is known to be an unmodifiable list. However, we [do specify](https://github.com/dart-lang/language/blob/d16704ae6c9a5fd8f30b7ba9d33a5ab650c7447d/specification/dartLangSpec.tex#L10067) in the section 'List Literal Inference' that every list literal has a type of the form `List<T>` for some `T`:

```
In both cases, the static type of \metavar{list} is \code{List<$T$>}.
```

@lrhn, do you plan to introduce system classes that describe the behavior of an unmodifiable list, set, and map? Presumably, they would be superinterfaces of the current `List`, `Set`, and `Map` classes. We could then consider to make unmodifiable collections visible to the type system, starting with the static types of constant collection literals.

However, this does look like a topic that has been raised a number of times in the past, and it is not obvious how we'd do it, without causing hugely breaking changes...

**Comment by eernstg** [comment]
> All in all, the cost doesn't seem to match the benefit.

Thought so. ;-)

> If the analyzer wants to detect that you're calling modifying methods on a constant
> list created by a constant list literal, they should have all the information needed.

This was the part that I was worried about: Noting that we won't make 'unmodifiable' for collections a property of the static type itself, the analyzer would need to add some "unofficial extras" to `DartType` or similar static analysis classes, e.g., remembering that this particular `List<int>` is one of those special lists that aren't modifiable. How far do we want to go down that path?

**Comment by adnanjpg** [comment]
It is easy to know that the `const` lists cant be modified, and it is easy to detect when you put the code in the way I've provided above in the issue's body 

> ```
> import 'dart:math';
> 
> void main(List<String> arguments) {
>   const foo = [1, 2, 3];
> 
>   final ran = Random();
>   foo.shuffle(ran);
> }
> ```
however, it really gets out of track when you have some lines between the `list initializer` and the `list modifier`. and this issue gives the user one more thing to worry about and focus on

**Comment by eernstg** [comment]
@lrhn wrote:
> something the analyzer can always choose to warn about.

Sure, lints and hints can do whatever they want, and 'warnings' might be treated similarly at some point. However, I made the distinction between properties that rely on specified information (in particular, static types), and properties that rely on non-specified information. The fact that both kinds of information must be propagated between program locations implies that any "extra" information will make common objects consume more memory (e.g., a `DartType` needs an extra field), or time must be spent looking up the extra information in some data structure on the side each time it _might_ be needed.

Perhaps this is not a problem at all, but I thought it was at least a thing to keep in mind, which is the reason why I pushed a bit on the (impossible) idea that it could be maintained as a proper part of the static types.

In any case, we're just looking at this from the outside. @stereotype441, @scheglov, WDYT?

**Comment by stereotype441** [comment]
Writing a lint that can see the flaw in @adnanjpg's example would definitely be possible, and not too difficult.  But most real-world examples of this sort of problem require synthesizing information from multiple functions across the program.  Consider this example:
```dart
import 'dart:math';

class C {
  void foo() {
    var listOfInts = const [1, 2, 3];

    bar(listOfInts);
  }
  void bar(List<int> values) {
    print('$values');
  }
}
mixin M {
  void bar(List<int> values) {
    values.shuffle(Random());
  }
}
class D extends C with M {}
main() {
  D().foo();
}
```

This example has the same flaw, but in order to see that the flaw exists, you can't look at individual functions in isolation.  You have to see that `C.foo` and `M.bar` are incompatible (because the former produces a const `List` and the latter only works with a non-const `List`), and then you have to see that since `D` mixes `C` and `M` together, it produces a way for those two incompatible methods to talk to one another.

Automating this sort of analysis is definitely possible, but it's tricky.  I don't think we have any definitive plans to add this sort of functionality to the linter or the analyzer, though we have talked about things like this before.  IIRC I've discussed ideas like this with @pq and @bwilkerson in the past.  So they might want to weigh in with their thoughts.

**Comment by MelbourneDeveloper** [comment]
@adnanjpg big +1 on this one.

The basic problem with immutable lists and Dart is that we don't see any problems at compile time. There are two ways that Dart could deal with the problem:

1) Analysis errors, as you mention
2) Create a more basic `List<>` class that is Iterable<> and only has a `length` property

Meantime, check out this package: [fixed_collections](https://pub.dev/packages/fixed_collections)

It just deprecates the mutation members, so you get a warning when you try to use this. You can use `FixedList<>` to pass lists around, so nobody modifies them. But, the lists are still normal. No conversion is necessary.

![image](https://user-images.githubusercontent.com/16697547/192651842-1921c3e0-3f69-48a3-9c89-311aaec626ce.png)

**Comment by scheglov** [comment]
It does not look to me that `fixed_collections` solves this issue.
If you have a function that accepts `List`, you can give it `FixedList`, and there are no type based errors.

```dart
import 'package:fixed_collections/fixed_collections.dart';

main() {
  const items = [0, 1, 2];
  f(FixedList(items));
}

void f(List<int> items) {
  items.add(42);
}
```

**Comment by MelbourneDeveloper** [comment]
@scheglov, you have to use the `FixedList<>` type. `List<>` allows mutation at compile time, but `FixedList<>` does not

![image](https://user-images.githubusercontent.com/16697547/192683315-152e2e79-e774-4e57-a942-ba560e220e9a.png)

**Comment by srawlins** [comment]
We won't be implementing this as a warning or a lint rule in the Dart analyzer. We now have a high bar for implementing and maintaining built-in static analysis rules, as it is too complicated (bug farm, false positives/negatives) to follow the provenance and constness of Lists as they are passed around. As of Dart 3.10 (Flutter 3.38), a [new analyzer plugins system](https://dart.dev/tools/analyzer-plugins) is available, and the requested static analysis here could be implemented as an analyzer plugin.
