### ISSUE TITLE
Usibility issue with Isolate.run wrt to over-capturing

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#48566]
`Isolate.run` is difficult to use because of https://github.com/dart-lang/sdk/issues/36983. When the closure provided to `Isolate.run` captures unnecessary stuff (because of that bug) that can't be send to an isolate, the user only sees this cryptic message:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: (object extends NativeWrapper - Library:'dart:ui' Class: Path)
#0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:399:25)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:379:7)
#2      Isolate.run (dart:isolate:232:15)
#3      _MyHomePageState._applySepiaFilterInIsolate (package:isoimg/main.dart:100:45)
```

It is not at all obvious that this is because the closure provided was over-capturing.

IMO, this is a major usability problem for `Isolate.run` because it is easy to use in a way that triggers the problem and the solution is not clear from the error message.

Example where I ran into this: https://github.com/goderbauer/scratchpad/blob/8d82e738a4307c65651dc854ec6437002f69d6ed/isoimg/lib/main.dart#L90-L92

To make it work, one has to define a static method to avoid over-capturing: https://github.com/goderbauer/scratchpad/commit/e36c3117b7d30733a726b4dd4769dd58c045accf

**Comment by goderbauer** [comment]
@mit-mit Since this functionality is new, should we actually back this out and not ship it in 2.17 in its current state? 

If not, at a minimum the docs for the functionality probably deserve a disclaimer explaining this behavior.

**Comment by goderbauer** [comment]
Ideally, the error message would also be more informative...

**Comment by jellynoone** [comment]
I agree with  @goderbauer  that the current state is sub-optimal, but I believe a way to compute a single function in an `Isolate` should be provided by the core. 

Mostly, because of how difficult it is to handle all the edge cases and clean up the resources. Even the initial implementation here had one such problem, not to mention the solution Flutter's `compute` used before.

However, it might be worth considering changing the signature to that of `compute` i.e. accept a paramater. I see on [Gerrit in the initially feature addition](https://dart-review.googlesource.com/c/sdk/+/217008) the reason, not to do this in the first place was because a closure capturing the necessary parameters would suffice. 

But if a solutions like the one described above by @goderbauer will have to be written to avoid over-capturing, the ease of use really feels more like a trap than a feature.

**Comment by dnfield** [comment]
From offline conversation, it sounds like the direction will be to prioritize #36983 which should make this problem less serious and avoid a harder to use API.

**Comment by mkustermann** [comment]
From offline discussion between @lrhn @mit-mit @mraleph about this and related issues:

  * Fix over-capturing issue in the VM: [sdk/issues/36983](https://github.com/dart-lang/sdk/issues/36983)
  * Allow developers to see how much data gets transferred between isolates: [sdk/issues/48591](https://github.com/dart-lang/sdk/issues/48591) (possibly by capturing `this.<final-field>` values instead of `this`)
  * More precise error message why object cannot be sent: [sdk/issues/48592](https://github.com/dart-lang/sdk/issues/48592)

And for now we'll remove `Isolate.run()` so it won't be included in the next stable release.

**Comment by mit-mit** [comment]
@lrhn landed a new iteration of the `isolate.run` api:
https://github.com/dart-lang/sdk/commit/a5f25ee3ba5a7f2e22b7698590727b32c37204f9

It looks like the main usecase in https://github.com/dart-lang/sdk/issues/36983 was resolved.

@goderbauer can you take a look at this and see if you think we can move forward with alignment with Flutter APIs?

**Comment by goderbauer** [comment]
> can move forward with alignment with Flutter APIs?

Can you remind me what the alignment plan was for this?

**Comment by dnfield** [comment]
I think there was a patch at some point to make `compute` just use `Isolate.run`, right?

**Comment by mit-mit** [comment]
Shall we go ahead with that alignment, @goderbauer @dnfield ?

**Comment by goderbauer** [comment]
Yeah, that sounds good to me. Does one of you want to send a PR? :)

**Comment by mit-mit** [comment]
@dnfield any chance you're able to create that PR? Lasse is tied up with Dart 3 core lib changes we have to get done next week weeks.

**Comment by mit-mit** [comment]
@goderbauer can this issue be closed now?
