### ISSUE TITLE
co19/LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t11 failure

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#48576]
Said test fails on the following configurations, cf. https://github.com/dart-lang/co19/issues/1316:

```
dartkp-strong-linux-release-x64
dartkp-weak-asserts-linux-release-x64
dartkp-strong-linux-debug-x64
dartkp-weak-asserts-linux-debug-x64
dartk-strong-win-release-x64
dartk-weak-asserts-win-release-x64
dartk-strong-linux-release-x64
dartk-weak-asserts-linux-release-x64
dartk-strong-linux-debug-x64
dartk-weak-asserts-linux-debug-x64
```

Here is an example stack trace (dartkp-strong-linux-release-x64):

```
Unhandled exception:
Expect.setEquals() fails
Expected collection does not contain: Object1 Object2 
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:18)
#1      Expect.setEquals (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:172)
#2      main (file:///b/s/w/ir/tests/co19/src/LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t11.dart:39)
<asynchronous suspension>
```

@dcharkes, please take a look and see if this failure is caused by a fault in the test or in the implementation.

**Comment by dcharkes** [comment]
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t11.dart

`main` is not invoking `attachToFinalizer1`.

**Comment by eernstg** [comment]
@dcharkes, I'm just guessing, but take a look at https://github.com/dart-lang/co19/pull/1324. ;-)
