### ISSUE TITLE
[dev_compiler] Expression evaluation using deferred library causes expression compiler worker crash

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#48587]
Repro:

- code
  **Package:  package:test/deferred_library.dart**
  ```dart
  library test_deferred_library;
  
  void deferredPrintLocal() {
    print('hello from deferred library'); // Breakpoint: DeferredPrintLocal
  }
  
  ```
  **main.dart**
  ```dart
  import 'package:test/deferred_library.dart' deferred as d;
  
  void main() {
    print('hello'); // Breakpoint here
  }
  
  Future<void> printDeferred() async {
    d.deferredPrintLocal();
  }
  ```

- set a breakpoint in main
- debug
- when paused on the breakpoint, evaluate expression `d.deferredPrintLocal()`

**Expected**
Should work currently, and after deferred libraries are implemented, should return "ModuleLoadError"

**Actual**

DDC crashes with

```
Internal error: NoSuchMethodError: The getter 'importUri' was called on null.
Receiver: null
Tried calling: importUri:#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
  #1      ProgramCompiler.jsLibraryName (package:dev_compiler/src/kernel/compiler.dart:493:45)
  #2      ProgramCompiler.visitCheckLibraryIsLoaded (package:dev_compiler/src/kernel/compiler.dart:6306:19)
  #3      CheckLibraryIsLoaded.accept (package:kernel/ast.dart:8609:44)
  #4      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3869:20)
  #5      ProgramCompiler.visitLet (package:dev_compiler/src/kernel/compiler.dart:6241:16)
  #6      Let.accept (package:kernel/ast.dart:8411:44)
  #7      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3869:20)
  #8      ProgramCompiler.visitReturnStatement (package:dev_compiler/src/kernel/compiler.dart:4400:38)
  #9      ReturnStatement.accept (package:kernel/ast.dart:9885:43)
  #10     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3775:20)
  #11     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3808:18)
  #12     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3577:17)
  #13     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2382:25)
  #14     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3611:18)
  #15     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3573:17)
  #16     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3390:11)
  #17     ProgramCompiler.emitFunctionIncremental (package:dev_compiler/src/kernel/compiler.dart:3334:15)
  #18     ExpressionCompiler._compileExpression (package:dev_compiler/src/kernel/expression_compiler.dart:445:36)
  <asynchronous suspension>
  #19     ExpressionCompiler.compileExpressionToJs (package:dev_compiler/src/kernel/expression_compiler.dart:346:26)
  <asynchronous suspension>
  #20     ExpressionCompilerWorker._compileExpression (package:dev_compiler/src/kernel/expression_compiler_worker.dart:426:29)
  <asynchronous suspension>
  #21     ExpressionCompilerWorker.run (package:dev_compiler/src/kernel/expression_compiler_worker.dart:273:26)
  <asynchronous suspension>
  #22     ExpressionCompilerWorker.createAndStart (package:dev_compiler/src/kernel/expression_compiler_worker.dart:127:9)
  <asynchronous suspension>
  #23     internalMain (package:dev_compiler/ddc.dart:35:5)
<asynchronous suspension>
```

**Comment by nshahan** [comment]
Currently DDC doesn't actually defer libraries but it does verify that `.loadLibrary()` has been called before accessing a member of the deferred library. This ensures it produces the same error that would appear in the dart2js compiled app that does actually defer the loading of the library. The crash is happening while trying to compile the code that checks if the library has been loaded.

Since the deferred library was never loaded on the page before trying to access a member I expect the behavior right now should be an error like `Error: Deferred import d (from main) was not loaded.`

After DDC supports deferred loading my expectation is that we would still see `Error: Deferred import d (from main) was not loaded.` since the failure will happen before trying to access any member of the library.

I'm pretty confident that I see the issue that is causing the crash here. When compiling the expression to be evaluated there is an access to a member of a deferred library. That access causes a `CheckLibraryIsLoaded` node to be inserted by the CFE. When DDC compiles that node it needs to know which library contains the member access of the deferred library to produce the correct error. DDC gets this from the `CheckLibraryIsLoaded.import.enclosingLibrary` but in this case the value is `null` (I guess because the expression does not have an enclosing library). Do you know if in other cases we consider the expression being evaluated to be part of the library where the execution is stopped at a breakpoint?

**Comment by annagrin** [comment]
> (I guess because the expression does not have an enclosing library). Do you know if in other cases we consider the expression being evaluated to be part of the library where the execution is stopped at a breakpoint?

In kernel, the expression is currently wrapped in a function, which in turn is enclosed in a synthetic library. I tried modifying a flutter example in a similar way, tried to evaluate an expression, and encountered a frontend server (and flutter tool) crash:

@johnniwinther @jensjoha - Could this be an incremental compiler issue? 

```
[+7913 ms] Unhandled exception:
[   +2 ms] Invalid argument(s): Reference to library dependency LibraryDependency() out of scope
[        ] #0      BinaryPrinter.writeLibraryDependencyReference (package:kernel[/binary/ast_to_binary.dart:901:7]())
[        ] #1      BinaryPrinter.visitCheckLibraryIsLoaded (package:kernel[/binary/ast_to_binary.dart:2044:5]())
[        ] #2      CheckLibraryIsLoaded.accept (package:kernel[/ast.dart:8609:44]())
[        ] #3      BinaryPrinter.writeNode (package:kernel[/binary/ast_to_binary.dart:430:10]())
[        ] #4      BinaryPrinter.writeOptionalNode (package:kernel[/binary/ast_to_binary.dart:522:7]())
[        ] #5      BinaryPrinter.writeVariableDeclaration (package:kernel[/binary/ast_to_binary.dart:2272:5]())
[        ] #6      BinaryPrinter.visitLet (package:kernel[/binary/ast_to_binary.dart:2012:5]())
[        ] #7      Let.accept (package:kernel[/ast.dart:8411:44]())
[        ] #8      BinaryPrinter.writeNode (package:kernel[/binary/ast_to_binary.dart:430:10]())
[        ] #9      BinaryPrinter.writeOptionalNode (package:kernel[/binary/ast_to_binary.dart:522:7]())
[        ] #10     BinaryPrinter.visitReturnStatement (package:kernel[/binary/ast_to_binary.dart:2210:5]())
[        ] #11     ReturnStatement.accept (package:kernel[/ast.dart:9885:43]())
[        ] #12     BinaryPrinter.writeNode (package:kernel[/binary/ast_to_binary.dart:430:10]())
[        ] #13     BinaryPrinter.writeOptionalNode (package:kernel[/binary/ast_to_binary.dart:522:7]())
[        ] #14     BinaryPrinter.visitFunctionNode (package:kernel[/binary/ast_to_binary.dart:1487:5]())
[        ] #15     FunctionNode.accept (package:kernel[/ast.dart:3867:38]())
[        ] #16     BinaryPrinter.writeFunctionNode (package:kernel[/binary/ast_to_binary.dart:437:10]())
[        ] #17     BinaryPrinter.visitProcedure (package:kernel[/binary/ast_to_binary.dart:1318:5]())
[        ] #18     Procedure.accept (package:kernel[/ast.dart:3176:40]())
[        ] #19     BinaryPrinter.writeProcedureNode (package:kernel[/binary/ast_to_binary.dart:458:10]())
[        ] #20     BinaryPrinter.writeProcedureNodeList (package:kernel[/binary/ast_to_binary.dart:349:7]())
[        ] #21     BinaryPrinter.visitLibrary (package:kernel[/binary/ast_to_binary.dart:1063:5]())
[        ] #22     Library.accept (package:kernel[/ast.dart:565:38]())
[        ] #23     BinaryPrinter.writeLibraryNode (package:kernel[/binary/ast_to_binary.dart:451:10]())
[        ] #24     BinaryPrinter.writeLibraries (package:kernel[/binary/ast_to_binary.dart:756:9]())
[        ] #25     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:595:7)
[        ] #26     Timeline.timeSync (dart:developer/timeline.dart:157:22)
[        ] #27     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:577:14)
[        ] #28     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:93:11)
[        ] #29     FrontendCompiler.compileExpression (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:877:16)
[        ] <asynchronous suspension>
[  +43 ms] the Dart compiler exited unexpectedly.
[        ] 
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:798:13)
#2  
```

**Comment by jensjoha** [comment]
I can reproduce the crash on serialization. I'll take a look.

**Comment by jensjoha** [comment]
https://dart-review.googlesource.com/c/sdk/+/238043 should fix the vm-related crash.
Here the fix is to setup the "fake library" that's being created to be able to serialize correctly.

On the DDC side it seems that no fake library and/or component is created.
It crashes at
```
  @override
  js_ast.Expression visitCheckLibraryIsLoaded(CheckLibraryIsLoaded node) =>
      runtimeCall('checkDeferredIsLoaded(#, #)', [
        js.string(jsLibraryName(node.import.enclosingLibrary)),
        js.string(node.import.name)
      ]);
```
where `node.import.enclosingLibrary` returns `null` because (I'm guessing) `node.import.parent` is `null` because the `LibraryDependency` is created specifically for the expression compilation but not "setup correctly". Nor would it help if it had been as the `enclosingLibrary` would be an artificial library created for expression compilation.

I'm not sure what the wanted output is for this `checkDeferredIsLoaded` --- but by it being a deferred import, wouldn't the library have to be the `_currentLibrary` (i.e. the Library specified when calling `_kernel2jsCompiler.emitFunctionIncremental` from `_compileExpression`)?

**Comment by nshahan** [comment]
It seems to me that for the purpose of compiling the `CheckLibraryIsLoaded` node we really just need to construct a string that identifies the context that the check is being compiled inside. In a conventional compile this is the library where the member access takes place. For the purpose of the expression evaluation maybe it would be sufficient if DDC just defaulted this name to be something like "unknown library"?

If we actually need to visit a `LoadLibrary` node during expression evaluation we are likely to have a failure when we execute the compiled code since we can't download and evaluation new JavaScript files while execution is paused at a breakpoint.

**Comment by annagrin** [comment]
The expression evaluation is supposed to fail here with "library d is not loaded", where `d` is the deferred library. Am i right that the name of  the library where the evaluation happens does not matter? If that's true, we could make it anything - unknown or the synthetic library it is already enclosed in.

**Comment by annagrin** [comment]
@nshahan do you think porting the fix from `compileExpression` to `compileExpressionToJs` would help us there?

**Comment by nshahan** [comment]
@annagrin 
> Am i right that the name of the library where the evaluation happens does not matter? If that's true, we could make it anything - unknown or the synthetic library it is already enclosed in.

Yes, that is my understanding as well. The name is only needed to be displayed in the error message if the library is not loaded.

> do you think porting the fix from compileExpression to compileExpressionToJs would help us there?

I'm not exactly sure what fix you mean. Could you link to it?

**Comment by annagrin** [comment]
@nshahan apologies, lost track of this. I meant porting the fix by @jensjoha (https://dart-review.googlesource.com/c/sdk/+/238043 ) that only works for `IncrementalCompiler.compileExpression` to `IncrementalCompiler.compileExpressionToJs`. There is some extra work done in `compileExpression` that  I am not sure we need, so this might need an investigation.
