### ISSUE TITLE
Request textDocument/foldingRange failed.

### ISSUE THREAD

**Issue by tatsuyuki25** [dart-lang/sdk#48589]
When writing in VS Code, show LSP error.

### Error log

```
[Error - 9:18:48 AM] Request textDocument/foldingRange failed.
  Message: An error occurred while handling textDocument/foldingRange request
  Code: -32001 
[Error - 9:18:48 AM] An error occurred while handling textDocument/foldingRange request: InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:224:7)
#1      AnalysisSessionImpl.getParsedUnit2 (package:analyzer/src/dart/analysis/session.dart:169:7)
<asynchronous suspension>
#2      AbstractAnalysisServer.getParsedUnit (package:analysis_server/src/analysis_server_abstract.dart:420:18)
<asynchronous suspension>
#3      FoldingHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_folding.dart:33:20)
<asynchronous suspension>
#4      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:193:22)
<asynchronous suspension>
#5      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:341:26)
<asynchronous suspension>
```

### Dart version
```
Dart SDK version: 2.17.0-202.0.dev (dev) (Thu Mar 10 20:55:41 2022 -0800) on "macos_arm64"
```

**Comment by scheglov** [comment]
We reverted adding `AnalysisSession.getParsedUnit2()`, so I think this issue should not happen.
