### ISSUE TITLE
Lots of InconsistentAnalysisException errors in VsCode

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#48595]
The `output` panel in VsCode has recently been giving me a lot of analyzer errors. They all look like this:

```
[Error - 8:29:39 AM] Request textDocument/foldingRange failed.
  Message: An error occurred while handling textDocument/foldingRange request
  Code: -32001 
[Error - 8:29:39 AM] An error occurred while handling textDocument/foldingRange request: InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:224:7)
#1      AnalysisSessionImpl.getParsedUnit2 (package:analyzer/src/dart/analysis/session.dart:169:7)
<asynchronous suspension>
#2      AbstractAnalysisServer.getParsedUnit (package:analysis_server/src/analysis_server_abstract.dart:420:18)
<asynchronous suspension>
#3      FoldingHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_folding.dart:33:20)
<asynchronous suspension>
#4      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:193:22)
<asynchronous suspension>
#5      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:341:26)
<asynchronous suspension>
```

Let me know what other information might help in diagnosing, not sure what to include.

**Comment by jakemac53** [comment]
Sounds good, I haven't seen the error yet since restarting (and it was happening often) so I assume this is resolved. Will re-open if I see it again.
