### ISSUE TITLE
New UBSAN failures after upgrading clang/GN

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#48659]
```
 >testee>err> ../../runtime/vm/object.h:3937:3: runtime error: member call on misaligned address 0x04d500390137 for type 'dart::UntaggedClosureData', which requires 8 byte alignment
 >testee>err> 0x04d500390137: note: pointer points here
 >testee>err> <memory cannot be printed>
 >testee>err> #0 0x56032dc1cbf8 in dart::ClosureData::parent_function() const ../../out/ReleaseUBSANX64/../../runtime/vm/object.h:3937:3
 >testee>err> #1 0x56032dc1f35d in dart::Function::script() const ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/object.cc:9600:49
 >testee>err> #2 0x56032dc6dc37 in dart::PrintSymbolicStackFrame(dart::Zone*, dart::BaseTextBuffer*, dart::Function const&, dart::TokenPosition, long, bool) ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/object.cc:25600:54
 >testee>err> #3 0x56032dc6d5ad in dart::StackTrace::ToCString() const ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/object.cc:25803:7
 >testee>err> #4 0x56032dcbd77f in dart::StackTrace::PrintJSONImpl(dart::JSONStream*, bool) const ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/object_service.cc:1626:38
 >testee>err> #5 0x56032dcbd467 in dart::JSONObject::AddProperty(char const*, dart::Object const&, bool) const ../../out/ReleaseUBSANX64/../../runtime/vm/json_stream.h:417:14
 >testee>err> #6 0x56032dcbd467 in dart::ReceivePort::PrintJSONImpl(dart::JSONStream*, bool) const ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/object_service.cc:1602:7
 >testee>err> #7 0x56032db2e234 in dart::JSONObject::AddProperty(char const*, dart::Object const&, bool) const ../../out/ReleaseUBSANX64/../../runtime/vm/json_stream.h:417:14
 >testee>err> #8 0x56032db2e234 in dart::ActivationFrame::PrintToJSONObjectRegular(dart::JSONObject*) ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/debugger.cc:1446:15
 >testee>err> #9 0x56032dd7618f in dart::GetStack(dart::Thread*, dart::JSONStream*) ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/service.cc:1698:14
 >testee>err> #10 0x56032dd69f62 in dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool) ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/service.cc:1040:7
 >testee>err> #11 0x56032dd6b1e7 in dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&) ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/service.cc:1084:38
 >testee>err> #12 0x56032db6812b in dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >) ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/isolate.cc:1364:33
 >testee>err> #13 0x56032dbba012 in dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/message_handler.cc:240:16
 >testee>err> #14 0x56032dbba705 in dart::MessageHandler::HandleOOBMessages() ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/message_handler.cc:349:10
 >testee>err> #15 0x56032eb07e65 in Dart_HandleServiceMessages ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/dart_api_impl.cc:2136:29
 >testee>err> #16 0x56032db71713 in dart::Isolate::PauseEventHandler() ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/isolate.cc:3459:16
 >testee>err> #17 0x56032db27676 in dart::Debugger::Pause(dart::ServiceEvent*) ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/debugger.cc:3378:17
 >testee>err> #18 0x56032db38776 in dart::Debugger::SignalPausedEvent(dart::ActivationFrame*, dart::Breakpoint*) ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/debugger.cc:3878:3
 >testee>err> #19 0x56032db38e50 in dart::Debugger::PauseStepping() ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/debugger.cc:4031:3
 >testee>err> #20 0x56032dd57ff7 in dart::DRT_HelperSingleStepHandler(dart::Isolate*, dart::Thread*, dart::Zone*, dart::NativeArguments) ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/runtime_entry.cc:1298:48
 >testee>err> #21 0x56032dd57f62 in dart::DRT_SingleStepHandler(dart::NativeArguments) ../../out/ReleaseUBSANX64/../../out/ReleaseUBSANX64/../../runtime/vm/runtime_entry.cc:1293:1
 >testee>err> 
 >testee>err> SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../runtime/vm/object.h:3937:3 in
```
See: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8818837692507781201/+/u/test_results/new_test_failures__logs_

In local testing this appears to have started triggering after the update of clang (and gn) in b75c19e8a89

**Comment by mkustermann** [comment]
Approved the following failures
```
corelib_2/error_stack_trace1_test Fail (expected Pass)
corelib_2/error_throw_with_stacktrace_test Fail (expected Pass)
corelib_2/hidden_library2_test/01 Fail (expected RuntimeError)
corelib_2/stacktrace_current_test Fail (expected Pass)
corelib_2/stacktrace_fromstring_test Fail (expected Pass)
corelib_2/string_case_test/01 Fail (expected Pass)
corelib_2/symbol_operator_test/03 Fail (expected Pass)
corelib_2/symbol_reserved_word_test/06 Fail (expected Pass)
corelib_2/symbol_reserved_word_test/09 Fail (expected Pass)
corelib_2/symbol_reserved_word_test/12 Fail (expected Pass)
corelib_2/symbol_test/none Fail (expected Pass)
corelib_2/throw_half_surrogate_pair_test/01 Fail (expected RuntimeError)
corelib_2/throw_half_surrogate_pair_test/02 Fail (expected RuntimeError)
corelib_2/unicode_test Fail (expected Pass)
language_2/assert/assert_test Fail (expected Pass)
language_2/async/return_throw_test Fail (expected Pass)
language_2/async_star/async_star_await_for_test Fail (expected Pass)
language_2/async_star/async_star_cancel_test Fail (expected Pass)
language_2/async_star/async_star_invalid_test/03 Fail (expected RuntimeError)
language_2/async_star/async_star_test Fail (expected Pass)
language_2/async_star/cancel_while_paused_at_yield_test Fail (expected Pass)
language_2/async_star/cancel_while_paused_test Fail (expected Pass)
language_2/async_star/pause_test Fail (expected Pass)
language_2/bool/has_environment_not_new_test Fail (expected Pass)
language_2/call/method_must_not_be_field_test/03 Fail (expected Pass)
language_2/call/method_must_not_be_getter_test/03 Fail (expected Pass)
language_2/closure/partial_tearoff_instantiation_test/02 Fail (expected RuntimeError)
language_2/closure/partial_tearoff_instantiation_test/04 Fail (expected RuntimeError)
language_2/const/locals_test Fail (expected Pass)
language_2/const/nested_test Fail (expected Pass)
    and 360 more tests
```
are failing on configurations
```
dartk-ubsan-linux-release-x64
dartkp-ubsan-linux-release-x64
```
