### ISSUE TITLE
[vm/ffi] vmspecific_native_finalizer_isolate_groups_test fails on arm-qemu

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48674]
It looks like the finalizer didn't run.

Possibly the isolate `LowLevelShutdown` which runs the finalizer isn't finished before the `onExit` message arrives. I will double check this.

If it is not guaranteed  `LowLevelShutdown` including the finalizers is run, we need to update the test, and the documentation on `onExit`. Or alternatively, we need to post the `onExit` message later. 

cc @mkustermann @mraleph 

```
/=================================================================================================================================\
| dartkp-linux-release-arm-qemu:ffi_2/vmspecific_native_finalizer_isolate_groups_test broke (Pass -> RuntimeError, expected Pass) |
\=================================================================================================================================/

--- Command "vm_compile_to_kernel" (took 02.000885s):
DART_CONFIGURATION=ReleaseXARM /b/s/w/ir/cache/builder/sdk/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseXARM/vm_platform_strong.dill -o /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_vmspecific_native_finalizer_isolate_groups_test/out.dill /b/s/w/ir/cache/builder/sdk/tests/ffi_2/vmspecific_native_finalizer_isolate_groups_test.dart -Dtest_runner.configuration=dartkp-linux-release-arm-qemu --packages=/b/s/w/ir/cache/builder/sdk/.packages -Ddart.vm.product=false

exit code:
0

--- Command "precompiler" (took 05.000218s):
DART_CONFIGURATION=ReleaseXARM out/ReleaseSIMARM_X64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_vmspecific_native_finalizer_isolate_groups_test/out.S --no-use-integer-division --trace-finalizers -Dtest_runner.configuration=dartkp-linux-release-arm-qemu --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_vmspecific_native_finalizer_isolate_groups_test/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 4ms):
DART_CONFIGURATION=ReleaseXARM rm /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_vmspecific_native_finalizer_isolate_groups_test/out.dill

exit code:
0

--- Command "assemble" (took 01.000692s):
DART_CONFIGURATION=ReleaseXARM arm-linux-gnueabihf-gcc -shared -o /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_vmspecific_native_finalizer_isolate_groups_test/out.aotsnapshot /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_vmspecific_native_finalizer_isolate_groups_test/out.S

exit code:
0

--- Command "remove_assembly" (took 7ms):
DART_CONFIGURATION=ReleaseXARM rm /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_vmspecific_native_finalizer_isolate_groups_test/out.S

exit code:
0

--- Command "vm" (took 01.000562s):
DART_CONFIGURATION=ReleaseXARM qemu-arm -L /usr/arm-linux-gnueabihf/ out/ReleaseXARM/dart_precompiled_runtime --trace-finalizers -Dtest_runner.configuration=dartkp-linux-release-arm-qemu --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_vmspecific_native_finalizer_isolate_groups_test/out.aotsnapshot

exit code:
255

stdout:
Isolate done.
Helper isolate has exited.

stderr:
Unhandled exception:
Expect.equals(expected: <42>, actual: <0>) fails.
#0      Expect._fail (package:expect/expect.dart:742)
#1      Expect.equals (package:expect/expect.dart:132)
#2      testFinalizerRunsOnIsolateGroupShutdown.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/tests/ffi_2/vmspecific_native_finalizer_isolate_groups_test.dart:49)
<asynchronous suspension>
#3      testFinalizerRunsOnIsolateGroupShutdown (file:///b/s/w/ir/cache/builder/sdk/tests/ffi_2/vmspecific_native_finalizer_isolate_groups_test.dart:36)
<asynchronous suspension>
#4      main (file:///b/s/w/ir/cache/builder/sdk/tests/ffi_2/vmspecific_native_finalizer_isolate_groups_test.dart:25)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartkp-linux-release-arm-qemu ffi_2/vmspecific_native_finalizer_isolate_groups_test
```

[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8818629344968093249/+/u/test_results/new_test_failures__logs_) from https://dart-review.googlesource.com/c/sdk/+/239020 which is an unrelated CL.

**Comment by mkustermann** [comment]
The exist listeners are notified right before running through the finalizers atm. Though even those steps were reversed, there's no timing guarantee, since the on-exit messages are sent asynchronously and maybe processed much later.

**Comment by dcharkes** [comment]
> The exist listeners are notified right before running through the finalizers atm.

I think we can turn this order around.

Even if we support sending native finalizers in send and exit, we would:

1. Update the isolate of finalizers/native finalizers in the Isolate_exit RTE, and set the bequest
2. Run all finalizers of the shutting down isolate
3. send the bequest to the receiver

This way a user can rely on the fact that when the isolate has exited message is received in Dart

1. the isolate that exited will no longer run any Dart code
2. all the native finalizers belonging to the isolate that has exited have been run

> Though even if those steps were reversed, there's no timing guarantee, since the on-exit messages are sent asynchronously and maybe processed much later.

There's no guarantee of the timeliness of the on-exit message. But we would have a guarantee that the native finalizers have run (which is what this test tries to rely on).

Alternatively, we could opt to not provide such guarantee. But I don't see a good argument for not providing such guarantee.
