### ISSUE TITLE
Feature idea: detect when many file changes occur at once, and wipe state clean

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#48746]
This is a vague idea right now because I don't super know what state analysis server holds onto which is individually invalidated on a file change.

But we've received a good amount of feedback that analysis server crashes, eats CPU, eats memory, when many files change "at once". The two examples are (A) switching git branches which have a lot of changes between them, and (B) running build_runner which re-generates many files.

I haven't reproduced either of these states yet, so that's a good first step. But assuming it reproduces, my idea is that there is something expensive about _re-analyzing_ many files, when there is _not_ something expensive about analyzing the same files the first time. Perhaps resource leaks (file handles?), or multiple changes per file triggering the event loop more than once per file path.

Whatever the case, if we can detect that many files have changed "at once," can we switch to a new behavior, of wiping our slate clean and re-analyzing everything from scratch?

It might take some design work and experimentation to figure out the heuristic (% of files currently under analysis? minimum number?), but the feedback is clear that a good percentage of Flutter developers are very impacted by this issue.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I also see that when there are many changes at once, we get into the state when the state of the world as we think it is (in form of the element model) is not what it actually is. So, it is kind of a race condition, or missing a dependency. We probably start analyzing one file, and while doing this, a few more files change, and we read them without realizing that we need to invalidate some libraries. This causes crashes. It might get fixed when we switch `AnalysisDriver._applyFileChangesSynchronously` in the [breaking change](https://dart-review.googlesource.com/c/sdk/+/233681).

I don't remember reports of extra CPU or heap usage because of many files changed. It might be possible that invalidating analysis results for a changed file is expensive, so when there are many files changed, we spend too much on trying to being more precise, and it would be faster to restart. But I have not seen such situations while working on analyzer and analysis server. It is always analysis that is slow. And my expectation is that restarting will only make things slower - we will have to read again files, decode summaries into element models.

Heap usage might go down after restart. The reason is that as we analyze, we might require some libraries, so we resynthesize them from summaries, but if we don't need them anymore, we will keep them in memory anyway. This is probably not an issue for DAS, because we use element models of almost all libraries for many semantic features - completion, quick fixes, etc.

**Comment by srawlins** [comment]
OK let's defer until the breaking change. In the meantime, I would like to have a consistent reproduction of the issues that occur when many files change (user reports include stale Problems panel, hanging, high memory).

**Comment by FMorschel** [comment]
Sometimes when working on the SDK, when changing branches, the analyzer gets a bit lost. There is stale information about some specific file. Usually, the files it keeps old information are files that exist between multiple branches and this only makes some calls show that some argument is missing or exceding. But when opening those files, we fix the analysis. 

But sometimes, when developing new assists/fixes or something else that needs a new test file, I see that when I change branches, the file that now _doesn't exist_ keeps warning about missing things that exist only on the branch it was created. This can easily be solved by restarting the whole server but I was wondering if:

1. We could create some command for reavaluating a specific file (temporary workaround) like "analyze files in problems tab" or something
2. We could take a new look at this problem to fix it

---

This occured when from https://dart-review.googlesource.com/c/sdk/+/414800 patchset 3 (saved this at https://github.com/FMorschel/sdk/tree/stale-analysis for convenience and won't update this branch) I created and moved to a new local branch at https://github.com/dart-lang/sdk/commit/54c8719dfac436f395b4c4078085d5ed8f0dfc51.

![Image](https://github.com/user-attachments/assets/e1451120-d5de-46eb-a71e-52ff45923681)

> many files change "at once"

I'm not sure this is true but it may cause the problem more often. At the above, patchset 3 was based on https://github.com/dart-lang/sdk/commit/d0caf45cc080617af2d296cdf7251e3cd0015920 (two commits behind the above-mentioned one, with 4 different files changed in total between them) and messed with 5 files (two new).

CC @DanTup

**Comment by DanTup** [comment]
Putting aside whether we _should_ do this, I'm not actually sure that it would fix the issue shown in the screenshot above.

I believe the issue here is that the file exists in your editor, and therefore - even though it doesn't exist on disk - VS Code has created an overlay in the server for it. It may be odd, but it's actually valid to have a file that has valid Dart code in your editor, delete it from disk, and then send requests like Hover and they will work:

![Image](https://github.com/user-attachments/assets/d5b3c342-7fb3-466a-856a-4c032d8d3a9c)

So let's say we did something drastic like restart the server.. VS Code would tell us to create an overlay for the file again, and we would then analyze it and produce these errors. We could change the server to never analyze files that _only_ exist as overlays, but I'm not sure that's the right call.

There is a VS Code setting that allows you to control whether a file deleted outside of VS Code automatically closes (it will always automatically close if deleted from within VS Code):

```
"workbench.editor.closeOnFileDelete": true
```

While I think generally it might be better to have this on (and I've just turned it on myself), it's not something we could change the default of because it's workbench-wide and not language-specific (although even if it wasn't, I'm less sure it would be right for us to change it - I think it would be better for users to opt-in to).

**Comment by FMorschel** [comment]
> I believe the issue here is that the file exists in your editor

Only if there is a problem when changing branches. It is true I originally had that file opened when I changed branches but I've set this exact setting you suggested on some time ago already. And even after the file closes by itself when the branch changes and it doesn't exist yet, the problems tab then shows errors for this file. For the screenshot I opened from double-clicking on the first diagnostic in the problems tab. 

Sorry if I wasn't clear enough on my first comment.

**Comment by FMorschel** [comment]
I've done some more testing. With the project at https://github.com/dart-lang/sdk/commit/54c8719dfac436f395b4c4078085d5ed8f0dfc51 (as mentioned above) I opened the commit that triggers the problem above https://github.com/FMorschel/sdk/tree/stale-analysis. When swicthing between both, nothing gets stale. 

_Even with_ the above setting mentioned by @DanTup (`"workbench.editor.closeOnFileDelete": true`) if I open either of the two files that give out the errors in the video (e.g.: `pkg/analysis_server/test/src/services/correction/fix/merge_combinators_test.dart`) and go back to the main branch without it, the problems tab shows the error. 

I'm not sure if this is a problem on our side or what. If wou want to we can open a new issue to track this specifically.

**Comment by bwilkerson** [comment]
> If I leave the project open for some time (not sure if there is a log to the this time number from?) the diagnostics go away ...

The log to check is the one that captures the traffic between the client and the server. That will tell you when the server sent the empty list of diagnostics for the file.

It sounds like this is somewhat WAI. The analysis server is sending the new set of diagnostics for the file when it has finally computed them. The bug here is that it's taking so long for the server to re-analyze the file and send the empty list of diagnostics.

**Comment by FMorschel** [comment]
I've cleaned my log files (the ones from the video above were way too big and I couldn't find anything) and here are both the analyzer, extension and instrumentation logs:

[analyzer.txt](https://github.com/user-attachments/files/19216472/analyzer.txt)
[extension.txt](https://github.com/user-attachments/files/19216470/extension.txt)(maybe helpful with the error below? Not sure)
[InstrumentationLog.txt](https://github.com/user-attachments/files/19216471/InstrumentationLog.txt)

From the analyzer log, it seems there was an error. But this time once I double-clicked on the diagnostics at the problems tab, the diagnostics vanished. Maybe this was simply a slow server issue? Not sure now. 


```
[16:39:23] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"textDocument/didClose","params":{"textDocument":{"uri":"file:///D%3A/dev/clones/dart-sdk/sdk/pkg/analysis_server/test/src/services/correction/fix/merge_combinators_test.dart"}},"clientRequestTime":1741808363525}
[16:39:24] [Analyzer] [Info] <== Content-Length: 70464
Content-Type: application/vscode-jsonrpc; charset=utf-8
[16:39:24] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"extends_non_class","codeDescription":{"href":"https://dart.dev/diagnostics/extends_non_class"},"message":"Classes can only extend other classes.\nTry specifying a different superclass, or removing the extends clause.","range":{"end":{"character":69,"line":510},"start":{"character":44,"line":510}},"severity":1,"source":"dart"},{"code":"undefined_getter","codeDescription":{"href":"https://dart.dev/diagnostics/undefined_getter"},"message":"The getter 'MERGE_COMBINATORS_HIDE_HIDE' isn't defined for the type 'DartFixKind'.\nTry importing the library that defines 'MERGE_COMBINATORS_HIDE_HIDE', correcting the name to the name of an existing getter, or defining a getter or field named 'MERGE_COMBINATORS_HIDE_HIDE'.","range":{"end":{"character":61,"line":28},"start":{"character":34,"line":28}},"severity":1,"source":"dart"},{"code":"undefined_method","codeDescription":{"href":"https://dart.dev/diagnostics/undefined_method"},"message":"The method 'resolveTestCode' isn't defined for the type 'MergeHideUsingHideTest'.\nTry correcting the name to the name of an existing method, or defining a method named 'resolveTestCode'.","range":{"end":{"character":25,"line":31},"start":{"character":10,"line":31}},"severity":1,"source":"dart"},{"code":"undefined_method","codeDescription":{"href":"https://dart.dev/diagnostics/undefined_method"},"message":"The method 'assertHasFix' isn't defined for the type 'MergeHideUsingHideTest'.\nTry correcting the name to the name of an existing method, or defining a method named 'assertHasFix'.","range":{"end":{"character":22,"line":34},"start":{"character":10,"line":34}},"severity":1,"source":"dart"},{"code":"undefined_method","codeDescription":{"href":"https://dart.dev/diagnostics/undefined_method"},"message":"The method 'createAnalysisOptionsFile' isn't defined for the type 'MergeHideUsingHideTest'.\nTry correcting the name to the name of an existing metho…
[16:39:24] [Analyzer] [Info] <== Content-Length: 214
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"dart/textDocument/publishClosingLabels","params":{"labels":[],"uri":"file:///D:/dev/clones/dart-sdk/sdk/pkg/analysis_server/test/src/services/correction/fix/merge_combinators_test.dart"}}Content-Length: 23909
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"dart/textDocument/publishOutline","params":{"outline":{"children":[{"codeRange":{"end":{"character":1,"line":20},"start":{"character":0,"line":13}},"element":{"kind":"FUNCTION","name":"main","parameters":"()","range":{"end":{"character":9,"line":13},"start":{"character":5,"line":13}},"returnType":"void"},"range":{"end":{"character":1,"line":20},"start":{"character":0,"line":13}}},{"children":[{"codeRange":{"end":{"character":62,"line":25},"start":{"character":2,"line":25}},"element":{"kind":"GETTER","name":"errorCode","range":{"end":{"character":25,"line":25},"start":{"character":16,"line":25}},"returnType":"ErrorCode"},"range":{"end":{"character":62,"line":25},"start":{"character":2,"line":24}}},{"codeRange":{"end":{"character":62,"line":28},"start":{"character":2,"line":28}},"element":{"kind":"GETTER","name":"kind","range":{"end":{"character":18,"line":28},"start":{"character":14,"line":28}},"returnType":"FixKind"},"range":{"end":{"character":62,"line":28},"start":{"character":2,"line":27}}},{"codeRange":{"end":{"character":3,"line":37},"start":{"character":2,"line":30}},"element":{"kind":"METHOD","name":"test_export_hide_hide","parameters":"()","range":{"end":{"character":36,"line":30},"start":{"character":15,"line":30}},"returnType":"Future<void>"},"range":{"end":{"character":3,"line":37},"start":{"character":2,"line":30}}},{"codeRange":{"end":{"character":3,"line":47},"start":{"character":2,"line":39}},"element":{"kind":"METHOD","name":"test_export_hide_hide_lint","parameters":"()","range":{"end":{"character":41,"line":39},"start":{"character":15,"line":39}},"re…
[16:39:27] [General] [Error] Unexpected token '/', "/*error: e"... is not valid JSON
SyntaxError: Unexpected token '/', "/*error: e"... is not valid JSON
    at JSON.parse (<anonymous>)
    at PackageConfigJsonPackageMap.load (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13921:28)
    at new PackageConfigJsonPackageMap (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13914:14)
    at Function.load (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13826:24)
    at Function.loadForProject (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13816:20)
    at c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:28591:76
[16:39:27] [General] [Error] Unexpected token '/', "/*error: e"... is not valid JSON
SyntaxError: Unexpected token '/', "/*error: e"... is not valid JSON
    at JSON.parse (<anonymous>)
    at PackageConfigJsonPackageMap.load (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13921:28)
    at new PackageConfigJsonPackageMap (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13914:14)
    at Function.load (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13826:24)
    at Function.loadForProject (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13816:20)
    at c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:28591:76
[16:39:27] [General] [Error] Unexpected token '/', "/*error: e"... is not valid JSON
SyntaxError: Unexpected token '/', "/*error: e"... is not valid JSON
    at JSON.parse (<anonymous>)
    at PackageConfigJsonPackageMap.load (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13921:28)
    at new PackageConfigJsonPackageMap (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13914:14)
    at Function.load (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13826:24)
    at Function.loadForProject (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13816:20)
    at c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:28591:76
[16:39:27] [General] [Error] Unexpected token '/', "/*error: e"... is not valid JSON
SyntaxError: Unexpected token '/', "/*error: e"... is not valid JSON
    at JSON.parse (<anonymous>)
    at PackageConfigJsonPackageMap.load (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13921:28)
    at new PackageConfigJsonPackageMap (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13914:14)
    at Function.load (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13826:24)
    at Function.loadForProject (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13816:20)
    at c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:28591:76
[16:39:27] [General] [Error] Unexpected token '/', "/*error: e"... is not valid JSON
SyntaxError: Unexpected token '/', "/*error: e"... is not valid JSON
    at JSON.parse (<anonymous>)
    at PackageConfigJsonPackageMap.load (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13921:28)
    at new PackageConfigJsonPackageMap (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13914:14)
    at Function.load (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13826:24)
    at Function.loadForProject (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:13816:20)
    at c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.107.20250311\out\dist\extension.js:28591:76
[16:39:30] [Analyzer] [Info] <== Content-Length: 212
Content-Type: application/vscode-jsonrpc; charset=utf-8
[16:39:30] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///D:/dev/clones/dart-sdk/sdk/pkg/analysis_server/test/src/services/correction/fix/merge_combinators_test.dart"}}
[16:39:38] [Analyzer] [Info] <== Content-Length: 93
```

**Comment by DanTup** [comment]
> For the screenshot I opened from double-clicking on the first diagnostic in the problems tab.

Oh sorry, I didn't realise that. In that case I presume VS Code must be restoring this content from some hidden model that it has kept (I don't understand why it would do this, but it must be getting the content from somewhere, and it's obviously not the disk), which is then causing it to be sent to the server (and then it will stay there until you close the file again).

So I think the issue here is probably as Brian describes - the server is still catching up because the branch changed caused a lot of analysis, and VS Code (for reasons I don't understand) allows you to double-click on a problem for a deleted file and it restores the code it previously had(?).

I'm not sure there's a good fix for us here (besides analysis being faster). The file being deleted will already flush the diagnostics from the client, but that work is in the same queue as all of the other work happening as a result of the flood of file watcher events.

> From the analyzer log, it seems there was an error. 

This error looks unrelated. It's from the VS Code extension trying to parse `package_config.json`, although unfortunately the stack trace doesn't seem complete so I'm not sure exactly where. Could you file an issue in Dart-Code with that, and I'll see if I can figure it out from the minified source where that happened (probably it's not fatal).

**Comment by FMorschel** [comment]
> The file being deleted will already flush the diagnostics from the client, but that work is in the same queue as all of the other work happening as a result of the flood of file watcher events.

Not sure how this works, is there a way to "cut the line" here, for deleted files? Maybe this could help?

P.S.: About the error, I'll copy the relevant comments and post there so we centralize it all.

**Comment by DanTup** [comment]
> Not sure how this works, is there a way to "cut the line" here, for deleted files? Maybe this could help?

Re-ordering things could be a bit risky (if there is a creation and then a delete and the delete gets pulled forwards, the end state would be that the file exists but it should not), but like most things, it depends a bit on the specifics. When you change branch, you might just change a lot of files that trigger analysis, but you might also change something that causes the analysis roots to be changed/rebuild (which has a fair bit of synchronous work which will block anything else from happening). Depending on the timing, some of these things might get batched together, and some might result in multiple rounds of analysis/rebuilding.

Are you able to reliably repro the issue above? Do you have exact steps/commit hashes I could use to see if it reproduces here?

**Comment by FMorschel** [comment]
> Are you able to reliably repro the issue above? Do you have exact steps/commit hashes I could use to see if it reproduces here?

Yes;

1. Clone https://github.com/FMorschel/sdk/tree/stale-analysis (I'll never mess with this specific branch)
2. Open `pkg/analysis_server/test/src/services/correction/fix/merge_combinators_test.dart` and
3. Run `git checkout 54c8719dfac436f395b4c4078085d5ed8f0dfc51` (https://github.com/dart-lang/sdk/commit/54c8719dfac436f395b4c4078085d5ed8f0dfc51) 

Even with that setting for closing deleted files the error still happens. I'm using Dart `3.8.0-edge.d469271ad95b43cf48ba02f74fb85ada8df6aa1f` if that makes any difference (I don't suspect it will).

**Comment by DanTup** [comment]
@FMorschel thanks - unfortunately I can't repro.. When I change to that hash, it takes almost no time for any analysis, and no diagnostics appear. Can you confirm which folder(s) you have open though, as I only had analysis_server open (I assumed you didn't have the whole SDK folder open, but I'm less sure you don't have things like analyzer open).

https://github.com/user-attachments/assets/9d19bdd7-253d-4439-9b39-80fdab97f77c

**Comment by FMorschel** [comment]
Here is my workspace file (with `.txt` at the end because GitHub doesn't accept that extension) [sdk.code-workspace.txt](https://github.com/user-attachments/files/19290664/sdk.code-workspace.txt). I do have some other folders opened for convenience since I've worked on them already.

Under `pkg`:

- analysis_server
- analyzer
- analyzer_plugin
- analysis_server_client
- analysis_server_plugin
- analyzer_utilities
- dartdev
- linter
- analyzer_cli
- _fe_analyzer_shared
- vm
- vm_service
- front_end

Under `third_party/pkg`:

` language_server_protocol

**Comment by DanTup** [comment]
> The only thing similar is that I'm still able to double-click the diagnostic there (at the problems tab) to see the file content even in the branch that doesn't contain it. 

That definitely seems odd to me and may be worth filing with VS Code. I can't imagine why this would be deliberate, and it may indicate something getting out of sync in their internal model (which could well be the cause of the problem). If the file is closed and deleted, pulling an old version of it from somewhere seems unexpected.

(If you file this, please CC me on it)
