### ISSUE TITLE
Defining two nameless extensions in differnt part files causes a compilation error

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#48765]
`Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "macos_x64"`

Consider the following example files:
```dart
/// file bug.dart

part 'bug.part.dart';
part 'bug.part.2.dart';

void main() {
  print(_Ac().runtimeType);
  print(_Bc().runtimeType);
}
```

```dart
/// file bug.part.dart
part of 'bug.dart';

abstract class _A {}

class _Ac implements _A {}

extension on _A {}
```

```dart
/// file bug.part.2.dart
part of 'bug.dart';

abstract class _B {}

class _Bc implements _B {}

extension on _B {}
```

run `dart bug.dart` and observe crash:

```
Crash when compiling /**/bug.dart,
at character offset null:
bug.part.dart:7:1: Internal problem: Couldn't find '_extension#1'.
extension on _A {}
^
#0      internalProblem (package:front_end/src/fasta/problems.dart:52:5)
#1      DietListener.checkBuilder (package:front_end/src/fasta/source/diet_listener.dart:1204:7)
#2      DietListener.lookupBuilder (package:front_end/src/fasta/source/diet_listener.dart:1149:5)
#3      DietListener.beginClassOrMixinOrExtensionBody (package:front_end/src/fasta/source/diet_listener.dart:907:9)
#4      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3633:14)
#5      Parser.parseExtension (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2559:13)
#6      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:654:18)
#7      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:497:14)
#8      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#9      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1065:16)
<asynchronous suspension>
#10     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:604:7)
<asynchronous suspension>
#11     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:441:7)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#13     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:162:19)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#15     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:12)
<asynchronous suspension>
#16     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:10)
<asynchronous suspension>
#17     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:97:11)
<asynchronous suspension>
#18     SingleShotCompilerWrapper.compileInternal (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:400:11)
<asynchronous suspension>
#19     Compiler.compile.<anonymous closure> (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#20     _processLoadRequest (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:888:37)
<asynchronous suspension>


#0      internalProblem (package:front_end/src/fasta/problems.dart:52:5)
#1      DietListener.checkBuilder (package:front_end/src/fasta/source/diet_listener.dart:1204:7)
#2      DietListener.lookupBuilder (package:front_end/src/fasta/source/diet_listener.dart:1149:5)
#3      DietListener.beginClassOrMixinOrExtensionBody (package:front_end/src/fasta/source/diet_listener.dart:907:9)
#4      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3633:14)
#5      Parser.parseExtension (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2559:13)
#6      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:654:18)
#7      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:497:14)
#8      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#9      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1065:16)
<asynchronous suspension>
#10     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:604:7)
<asynchronous suspension>
#11     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:441:7)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#13     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:162:19)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#15     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:12)
<asynchronous suspension>
#16     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:10)
<asynchronous suspension>
#17     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:97:11)
<asynchronous suspension>
#18     SingleShotCompilerWrapper.compileInternal (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:400:11)
<asynchronous suspension>
#19     Compiler.compile.<anonymous closure> (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#20     _processLoadRequest (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:888:37)
<asynchronous suspension>
```

Putting all the definitions in the same file works as expected.

**Comment by lrhn** [comment]
Unique names should be library-wide unique, not just file-wide.
