### ISSUE TITLE
The analyzer_plugin mechanism seems to assume that `pub` command still exists

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#48786]
Trying to start an analyzer_plugin on recent Flutter channels leads to the following error:

```
ProcessException: No such file or directory
  Command: /Users/remirousselet/dev/flutter/bin/cache/dart-sdk/bin/pub get
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      PluginManager._computeFiles (package:analysis_server/src/plugin/plugin_manager.dart:641:28)
#4      PluginManager.filesFor (package:analysis_server/src/plugin/plugin_manager.dart:465:12)
#5      PluginManager.addPluginToContextRoot (package:analysis_server/src/plugin/plugin_manager.dart:328:23)
#6      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:68:19)
#7      AnalysisDriver.configure (package:analyzer/src/dart/analysis/driver.dart:544:33)
#8      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:137:12)
#9      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:67:36)
#10     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded.performContextRebuild (package:analysis_server/src/context_manager.dart:449:40)
#11     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded.performContextRebuild (package:analysis_server/src/context_manager.dart:444:41)
#12     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded (package:analysis_server/src/context_manager.dart:562:17)

#13     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:280:5)

#14     LspAnalysisServer._refreshAnalysisRoots (package:analysis_server/src/lsp/lsp_analysis_server.dart:792:5)

#15     LspAnalysisServer.fetchClientConfigurationAndPerformDynamicRegistration (package:analysis_server/src/lsp/lsp_analysis_server.dart:259:11)

#16     LspAnalysisServer.updateWorkspaceFolders (package:analysis_server/src/lsp/lsp_analysis_server.dart:723:5)

#17     IntializedMessageHandler.handle (package:analysis_server/src/lsp/handlers/handler_initialized.dart:36:7)

#18     LspAnalysisServer.handleMessage. (package:analysis_server/src/lsp/lsp_analysis_server.dart:356:26)

```

As per the error, the problem seems to be that instead of executing `dart pub get`, the SDK's `PluginManager._computeFile` (https://github.com/dart-lang/sdk/blob/b2044efef713881eca55065dc7f4b3488ed356d9/pkg/analysis_server/lib/src/plugin/plugin_manager.dart#L622) is executing `pub get` instead

Which fails because `pub` is no-longer a global command

**Comment by devoncarew** [comment]
Thanks - closing as a dup of https://github.com/dart-lang/sdk/issues/48682.
