### ISSUE TITLE
Crash migrating dart2js

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#48794]
Non-blocking as I am able to proceed by adding `--ignore-exceptions`.

In the SDK development directory:
```
cd $SDK
tools/build -mrelease
cd pkg/compiler
$SDK/out/ReleaseX64/dart-sdk/bin/dart migrate --skip-import-check
```
This is what I see
```
No analysis issues found.

Generating migration suggestions...
[-------------------------/                                                                                                        ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.18.0-edge.ff84166410c7e109ccc030a6584f77cadff037b2) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

IndexedMember*.substitute(IndexedMember* | {E extends _Indexed*: E*?(type argument 0 of register expression (indexed.dart:168:12)), D: D*?(type argument 1 of register expression (indexed.dart:168:12)), E0 extends E*: E0*, D0 extends D*: D0*}) at offset 5142 in /usr/local/google/home/sra/Dart/sdk/pkg/compiler/lib/src/elements/indexed.dart (register(entity, data))

#0      DecoratedType._substitute (package:nnbd_migration/src/decorated_type.dart:472:5)
#1      DecoratedType._substitute (package:nnbd_migration/src/decorated_type.dart:442:34)
#2      DecoratedType.substitute (package:nnbd_migration/src/decorated_type.dart:332:12)
#3      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:378:32)
#4      EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1404:20)
#5      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7712:50)
#6      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2341:24)
#7      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2470:20)
#8      EdgeBuilder.visitReturnStatement (package:nnbd_migration/src/edge_builder.dart:1696:7)
#9      ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:9218:50)
#10     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2341:24)
#11     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1537:9)
#12     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:551:40)
#13     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:163:32)
#14     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1091:50)
#15     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2341:24)
#16     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1537:9)
#17     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:334:46)
#18     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:166:56)
#19     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1042:50)
#20     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2341:24)
#21     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2637:7)
#22     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1363:5)
#23     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7564:50)
#24     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2341:24)
#25     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2359:7)
#26     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:690:7)
#27     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:657:5)
#28     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1606:50)
#29     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2341:24)
#30     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1537:9)
#31     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:200:52)
#32     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#33     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#34     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#35     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2220:50)
#36     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:223:12)
#37     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:162:16)
#38     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1088:20)
#39     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1086:28)
#40     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1020:26)
<asynchronous suspension>
#41     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1086:5)
<asynchronous suspension>
#42     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:695:24)
<asynchronous suspension>
#43     MigrateCommand.run (package:dartdev/src/commands/migrate.dart:37:7)
<asynchronous suspension>
#44     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#45     DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:18)
<asynchronous suspension>
#46     runDartdev (package:dartdev/dartdev.dart:66:16)
<asynchronous suspension>
#47     main (file:///usr/local/google/home/sra/Dart/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
