### ISSUE TITLE
Crash when compiling range based for loop with const variable

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#48808]
Front end crashes when I try to compile this:

```dart
void main() {
  for (const x in [1, 2, 3]) print(x);
}
```

It's a fairly easy typo for me, coming from C++ land where const means something else.

Stack trace:
```
The compiler crashed: Crash when compiling null,
at character offset null:
Null check operator used on a null value
#0      ConstantsTransformer.visitVariableGet (package:front_end/src/fasta/kernel/constant_evaluator.dart:748:73)
#1      VariableGet.accept1 (package:kernel/ast.dart:4154:9)
#2      RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1707:21)
#3      RemovingTransformer.transformList (package:kernel/visitor.dart:1931:19)
#4      RemovingTransformer.transformExpressionList (package:kernel/visitor.dart:1857:5)
#5      Arguments.transformOrRemoveChildren (package:kernel/ast.dart:5154:7)
#6      RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#7      TreeVisitor1.visitArguments (package:kernel/visitor.dart:700:46)
#8      Arguments.accept1 (package:kernel/ast.dart:5135:53)
#9      RemovingTransformer.transform (package:kernel/visitor.dart:1671:17)
#10     StaticInvocation.transformOrRemoveChildren (package:kernel/ast.dart:6327:21)
#11     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#12     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:434:50)
#13     TreeVisitor1.visitStaticInvocation (package:kernel/visitor.dart:496:7)
#14     ConstantsTransformer.visitStaticInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:822:18)
#15     StaticInvocation.accept1 (package:kernel/ast.dart:6306:9)
#16     RemovingTransformer.transform (package:kernel/visitor.dart:1671:17)
#17     ExpressionStatement.transformOrRemoveChildren (package:kernel/ast.dart:8866:22)
#18     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#19     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:596:48)
#20     TreeVisitor1.visitExpressionStatement (package:kernel/visitor.dart:599:7)
#21     ExpressionStatement.accept1 (package:kernel/ast.dart:8846:9)
#22     RemovingTransformer.transform (package:kernel/visitor.dart:1671:17)
#23     ForInStatement.transformOrRemoveChildren (package:kernel/ast.dart:9484:16)
#24     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#25     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:596:48)
#26     TreeVisitor1.visitForInStatement (package:kernel/visitor.dart:625:7)
#27     ForInStatement.accept1 (package:kernel/ast.dart:9442:9)
#28     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1707:21)
#29     RemovingTransformer.transformList (package:kernel/visitor.dart:1931:19)
#30     RemovingTransformer.transformStatementList (package:kernel/visitor.dart:1885:5)
#31     Block.transformOrRemoveChildren (package:kernel/ast.dart:8915:7)
#32     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#33     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:596:48)
#34     TreeVisitor1.visitBlock (package:kernel/visitor.dart:601:38)
#35     Block.accept1 (package:kernel/ast.dart:8901:58)
#36     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1707:21)
#37     RemovingTransformer.transformList (package:kernel/visitor.dart:1931:19)
#38     RemovingTransformer.transformStatementList (package:kernel/visitor.dart:1885:5)
#39     Block.transformOrRemoveChildren (package:kernel/ast.dart:8915:7)
#40     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#41     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:596:48)
#42     TreeVisitor1.visitBlock (package:kernel/visitor.dart:601:38)
#43     Block.accept1 (package:kernel/ast.dart:8901:58)
#44     RemovingTransformer.transform (package:kernel/visitor.dart:1671:17)
#45     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:541:19)
#46     FunctionNode.accept1 (package:kernel/ast.dart:3863:9)
#47     RemovingTransformer.transform (package:kernel/visitor.dart:1671:17)
#48     ConstantsTransformer.visitProcedure.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:447:23)
#49     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3636:18)
#50     ConstantsTransformer.visitProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:445:23)
#51     Procedure.accept1 (package:kernel/ast.dart:3171:55)
#52     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1707:21)
#53     RemovingTransformer.transformList (package:kernel/visitor.dart:1931:19)
#54     RemovingTransformer.transformProcedureList (package:kernel/visitor.dart:1813:5)
#55     ConstantsTransformer.convertLibrary (package:front_end/src/fasta/kernel/constant_evaluator.dart:381:5)
#56     transformLibraries (package:front_end/src/fasta/kernel/constant_evaluator.dart:117:26)
#57     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1338:19)
#58     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:449:7)
<asynchronous suspension>
#59     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#60     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:162:19)
<asynchronous suspension>
#61     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#62     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:202:37)
<asynchronous suspension>
#63     compile (package:front_end/src/api_unstable/dart2js.dart:200:36)
<asynchronous suspension>
#64     KernelLoaderTask.load.<anonymous closure> (package:compiler/src/kernel/loader.dart:217:21)
<asynchronous suspension>
#65     Compiler.runInternal (package:compiler/src/compiler.dart:325:29)
<asynchronous suspension>
#66     main (package:compiler/src/dart2js.dart:1373:3)
<asynchronous suspension>


#0      ConstantsTransformer.visitVariableGet (package:front_end/src/fasta/kernel/constant_evaluator.dart:748:73)
#1      VariableGet.accept1 (package:kernel/ast.dart:4154:9)
#2      RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1707:21)
#3      RemovingTransformer.transformList (package:kernel/visitor.dart:1931:19)
#4      RemovingTransformer.transformExpressionList (package:kernel/visitor.dart:1857:5)
#5      Arguments.transformOrRemoveChildren (package:kernel/ast.dart:5154:7)
#6      RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#7      TreeVisitor1.visitArguments (package:kernel/visitor.dart:700:46)
#8      Arguments.accept1 (package:kernel/ast.dart:5135:53)
#9      RemovingTransformer.transform (package:kernel/visitor.dart:1671:17)
#10     StaticInvocation.transformOrRemoveChildren (package:kernel/ast.dart:6327:21)
#11     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#12     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:434:50)
#13     TreeVisitor1.visitStaticInvocation (package:kernel/visitor.dart:496:7)
#14     ConstantsTransformer.visitStaticInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:822:18)
#15     StaticInvocation.accept1 (package:kernel/ast.dart:6306:9)
#16     RemovingTransformer.transform (package:kernel/visitor.dart:1671:17)
#17     ExpressionStatement.transformOrRemoveChildren (package:kernel/ast.dart:8866:22)
#18     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#19     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:596:48)
#20     TreeVisitor1.visitExpressionStatement (package:kernel/visitor.dart:599:7)
#21     ExpressionStatement.accept1 (package:kernel/ast.dart:8846:9)
#22     RemovingTransformer.transform (package:kernel/visitor.dart:1671:17)
#23     ForInStatement.transformOrRemoveChildren (package:kernel/ast.dart:9484:16)
#24     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#25     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:596:48)
#26     TreeVisitor1.visitForInStatement (package:kernel/visitor.dart:625:7)
#27     ForInStatement.accept1 (package:kernel/ast.dart:9442:9)
#28     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1707:21)
#29     RemovingTransformer.transformList (package:kernel/visitor.dart:1931:19)
#30     RemovingTransformer.transformStatementList (package:kernel/visitor.dart:1885:5)
#31     Block.transformOrRemoveChildren (package:kernel/ast.dart:8915:7)
#32     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#33     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:596:48)
#34     TreeVisitor1.visitBlock (package:kernel/visitor.dart:601:38)
#35     Block.accept1 (package:kernel/ast.dart:8901:58)
#36     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1707:21)
#37     RemovingTransformer.transformList (package:kernel/visitor.dart:1931:19)
#38     RemovingTransformer.transformStatementList (package:kernel/visitor.dart:1885:5)
#39     Block.transformOrRemoveChildren (package:kernel/ast.dart:8915:7)
#40     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:1954:10)
#41     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:596:48)
#42     TreeVisitor1.visitBlock (package:kernel/visitor.dart:601:38)
#43     Block.accept1 (package:kernel/ast.dart:8901:58)
#44     RemovingTransformer.transform (package:kernel/visitor.dart:1671:17)
#45     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:541:19)
#46     FunctionNode.accept1 (package:kernel/ast.dart:3863:9)
#47     RemovingTransformer.transform (package:kernel/visitor.dart:1671:17)
#48     ConstantsTransformer.visitProcedure.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:447:23)
#49     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3636:18)
#50     ConstantsTransformer.visitProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:445:23)
#51     Procedure.accept1 (package:kernel/ast.dart:3171:55)
#52     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1707:21)
#53     RemovingTransformer.transformList (package:kernel/visitor.dart:1931:19)
#54     RemovingTransformer.transformProcedureList (package:kernel/visitor.dart:1813:5)
#55     ConstantsTransformer.convertLibrary (package:front_end/src/fasta/kernel/constant_evaluator.dart:381:5)
#56     transformLibraries (package:front_end/src/fasta/kernel/constant_evaluator.dart:117:26)
#57     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1338:19)
#58     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:449:7)
<asynchronous suspension>
#59     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#60     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:162:19)
<asynchronous suspension>
#61     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#62     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:202:37)
<asynchronous suspension>
#63     compile (package:front_end/src/api_unstable/dart2js.dart:200:36)
<asynchronous suspension>
#64     KernelLoaderTask.load.<anonymous closure> (package:compiler/src/kernel/loader.dart:217:21)
<asynchronous suspension>
#65     Compiler.runInternal (package:compiler/src/compiler.dart:325:29)
<asynchronous suspension>
#66     main (package:compiler/src/dart2js.dart:1373:3)
<asynchronous suspension>
```

**Comment by chloestefantsova** [comment]
I'm working on a fix at https://dart-review.googlesource.com/c/sdk/+/241604.
