### ISSUE TITLE
`dart analyze` reads more than it should for a single file analysis

### ISSUE THREAD

**Issue by akbiggs** [dart-lang/sdk#48832]
Using [fsatrace](https://github.com/jacereda/fsatrace):

```
flutter create test_app
fsatrace r /dev/stdout -- dart analyze test_app/lib/main.dart
```

We see a lot of folders being read that `dart analyze` should not need to read. It looks like `dart analyze` is reading every folder under test_app. Sample:

```
r|~/test_app/test
r|~/test_app/android
r|~/test_app/android/gradle
r|~/test_app/android/gradle/wrapper
r|~/test_app/android/app
```

`dart --version`

```
akbiggs@akbiggs ~ % dart --version
Dart SDK version: 2.17.0-edge.8fec4e03e5761c487809720904bf810c3faac61f (be) (Mon Apr 18 17:22:05 2022 +0000) on "linux_x64"
```

**Comment by scheglov** [comment]
What is `fsatrace`?

**Comment by srawlins** [comment]
@scheglov you've been helping with this for the last few days, correct? Should this stay assigned to you?

I think this is a P1 for Fuchsia's developers, for their workflow.

@akbiggs the example you provide makes it look like you've reproduced this outside of a GN workspace? Perhaps in a pub package? Is this easy to repro outside a GN workspace?

**Comment by scheglov** [comment]
I can reproduce this on Linux with the instructions provided.

Interestingly, this happens for `dart analyze <file>`, but not with `dartanalyzer <file>`. Also, if I do `fsatrace r /dev/stdout -- dart analyze test_app/lib/`, it does not go into `test_app/android` and other. It seems as if the server reverts to analysis of the whole package if a single file is requested. But if a directory - then it will analyze this directory.

**Comment by scheglov** [comment]
OK, I found a reason - we start watching the whole package directory.
```
[ByteStreamServerChannel][outputLine][{"event":"server.connected","params":{"version":"1.33.0","pid":2612012}}]
[listSync][path: /usr/local/google/home/scheglov/.dartServer/.analysis-driver]
[ByteStreamServerChannel][_readRequest][{"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}]
[ByteStreamServerChannel][_readRequest][{"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["/usr/local/google/home/scheglov/dart/test_app/lib/main.dart"],"excluded":[]}}]
[ByteStreamServerChannel][outputLine][{"id":"1"}]
[ContextManager][includedPaths: [/usr/local/google/home/scheglov/dart/test_app/lib/main.dart]]
[AnalysisContextCollectionImpl][includedPaths: [/usr/local/google/home/scheglov/dart/test_app/lib/main.dart]]
[AnalysisContextCollectionImpl][root: /usr/local/google/home/scheglov/dart/test_app][files: [/usr/local/google/home/scheglov/dart/test_app/lib/main.dart]]
[ContextManager][rootFolder: /usr/local/google/home/scheglov/dart/test_app]
[list][path: /usr/local/google/home/scheglov/dart/test_app][#0      _Directory.list (dart:io/directory_impl.dart:228:41)
#1      new _LinuxDirectoryWatcher (package:watcher/src/directory_watcher/linux.dart:95:23)
#2      new LinuxDirectoryWatcher.<anonymous closure> (package:watcher/src/directory_watcher/linux.dart:32:32)
#3      new ResubscribableWatcher.<anonymous closure> (package:watcher/src/resubscribable.dart:48:29)
#4      new ResubscribableWatcher.<anonymous closure> (package:watcher/src/resubscribable.dart:47:19)
#5      _runGuarded (dart:async/stream_controller.dart:814:24)
#6      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
#7      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
#8      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
#9      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#10     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#11     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#12     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded.performContextRebuild (package:analysis_server/src/context_manager.dart:480:16)
#13     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded.performContextRebuild (package:analysis_server/src/context_manager.dart:447:41)
#14     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded (package:analysis_server/src/context_manager.dart:568:17)
<asynchronous suspension>
#15     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:283:5)
<asynchronous suspension>
#16     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:503:7)
<asynchronous suspension>
#17     AnalysisSetAnalysisRootsHandler.handle (package:analysis_server/src/handler/legacy/analysis_set_analysis_roots.dart:47:7)
<asynchronous suspension>
]
[ByteStreamServerChannel][outputLine][{"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}]
[ByteStreamServerChannel][outputLine][{"id":"2"}]
[ByteStreamServerChannel][outputLine][{"event":"analysis.errors","params":{"file":"/usr/local/google/home/scheglov/dart/test_app/lib/main.dart","errors":[]}}]
[ByteStreamServerChannel][outputLine][{"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}]
[ByteStreamServerChannel][_readRequest][{"id":"3","method":"server.shutdown","params":null}]
[ByteStreamServerChannel][outputLine][{"id":"3"}]
```

**Comment by scheglov** [comment]
And the reason we watch the whole directory is that we decide that the root directory of a `ContextRoot` is the directory that contains `pubspec.yaml` or `analysis_options.yaml` (whichever is deeper). Which is not wrong by itself. What is wrong is watching the whole root directory. We should watch only effectively included resources (i.e. included and not excluded). We have `ContextRoot.included`, which is close semantically, although maybe not ideally - I have doubts about it excluding resources.

**Comment by scheglov** [comment]
In general, the way we do watching currently might be dangerous. We started watching complete *initial* included paths while building analysis roots, so that we don't miss changes to configuration files that happen between we read them the first time (while creating analysis contexts) and start watching analysis roots. But this means that we might watch much more than the user intended.

Imagine that we have the following directory structure.
```
/home/test
/home/test/really-big-directory
/home/test/lib/... a few files
/home/test/analysis_options.yaml - it excludes "really-big-directory" 
```

The user expectation would be that we never look into `really-big-directory`. Not only we should not analyze its files, we should never include it into watching, because this requires listing its files, which might be prohibitively expensive.

@DanTup @bwilkerson

**Comment by scheglov** [comment]
A possible partial solution: https://dart-review.googlesource.com/c/sdk/+/241983

**Comment by bwilkerson** [comment]
> ... so that we don't miss changes to configuration files ...

That's part of it, but there's at least one additional reason. The legacy protocol says that if you include a file or directory that doesn't exist when setting analysis roots, it will be ignored but remembered. If that file or directory is created later, server will notice and start analyzing it.

**Comment by scheglov** [comment]
As far as I know, this does not work today. One way to solve this without watching is to probe for periodically for such included resources that did not exist last time.

And for configuration files, as we build context roots, and read configuration files, we could remember the state of these files - the existence and the content. After we are done, and start watching, we check again if these configuration files are still in the same state. Maybe even all files, including `*.dart` files - I can imagine that we will miss a change while rebuilding context roots. Just never go into excluded directories.

This "not going into excluded directories" should also cover not watching them. AFAIK `dart:io` does not support exclude filters in `watch()`. So, if there is an excluded directory `foo` in the root of the `ContextRoot`, then the `List<Resource> included` must be rewritten to be the list of all children except `foo`, and we should non-recursively check the root directory for any new children to include. Which almost feels as re-implementing the watcher, as periodical recursive probing.

**Comment by DanTup** [comment]
@scheglov (in response to https://dart-review.googlesource.com/c/sdk/+/238640)

> If you can reproduce the watcher exception issue, this is a good news. It represents a significant portion of the current crashes internally. Fixing it would be very nice.

Well it turns out I may have been confused. Although I was quite certain I saw the same error, after rebasing the main CL and being distracted by the other issues, I came back and was completely unable to reproduce the same error in the container. There was a failing test, but it was a timeout and not the reported error.

Although... is it possible your change above (which I didn't include in my testing because of other issues I had after rebasing) will fix this because the non-existant folder will not be included in the `.included` set that's now used to create watchers?

**Comment by scheglov** [comment]
Unfortunately it still happens internally quite often, maybe 50% of all crashes are `FileSystemException: FileSystemException: Failed to watch path, path = '/Users/xxx/StudioProjects/yyy' (OS Error: No such file or directory, errno = 2)`. This directory actually almost never exists, because the path is local (on Mac), but the server runs remotely on Linux, where the home directory is different.

**Comment by DanTup** [comment]
> This directory actually almost never exists, because the path is local (on Mac), but the server runs remotely on Linux, where the home directory is different.

Oh, interesting. How does this work? Can that setup be reproduced externally? Is there some special IDE work to make it work?

VS Code supports running on remote machines, but with that setup I wouldn't expect local paths to ever reach the server because it pushes the extension host onto the remote machine too (this is how I was testing in a container earlier, the analysis server + extension host ran inside the container while VS Code's UI was running outside it on my Mac).

Something that's not clear to me is whether this error can only occur in the setup described above, or can also be triggered externally. Although I can reproduce an error creating a watcher for a folder that doesn't exist in isolation, I can't reproduce it through the server (I think because there are error handlers on the watcher streams).

**Comment by scheglov** [comment]
I think (but I have not looked into the details of the implementation) it works by opening ssh tunnel to the remote machine, and running DAS there. Not sure how IntelliJ does this - probably there are hooks in IntelliJ Dart plugin, that the internal plugin fills. Either way, we forward requests / responses to the remotely running DAS.

Yes, I also don't understand why it happens. Theoretically if we catch errors on the watcher stream, this should cover all errors.

**Comment by DanTup** [comment]
Ah, now you mention that, I'm reminded of something similar in the VS Code plugin:

https://github.com/Dart-Code/Dart-Code/pull/1049

It's not the way I'd recommend running on a remote machine (given VS Code has its own remoting support now), but perhaps it's worth testing to see if it can trigger this (since it seems like it'd be easy to have mismatched paths in the way you described between local/remote). I'll have a go.
