### ISSUE TITLE
[analyzer] Analysis server crashes for specific code snippet

### ISSUE THREAD

**Issue by schultek** [dart-lang/sdk#48867]
Analysis server version: `1.32.8`
Dart SDK: `2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "macos_x64"`

The analysis server has an exception when analyzing my code. I could break it down to the following snippet:

```dart
typedef FA = int Function();
typedef FB = double Function();

class A {
  const A(FB builder) : fn = _B(builder);

  final FA fn;
}

class _B {
  const _B(this._fn);

  final FB _fn;

  int call() {
    return _fn().round();
  }
}
```

With this the analysis server seemingly stops for this file and when I visit the diagnostics page where I would normally see the ast tree, it shows:

```
Exception: Missing implementation of visitImplicitCallReferenceImpl 
#0 ThrowingAstVisitor._throw (package:analyzer/dart/ast/visitor.dart:2241:5) 
#1 ThrowingAstVisitor.visitImplicitCallReference (package:analyzer/dart/ast/visitor.dart:2043:64) 
#2 ImplicitCallReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:5927:20) 
#3 AstBinaryWriter._writeNode (package:analyzer/src/summary2/ast_binary_writer.dart:875:10) 
#4 AstBinaryWriter.visitConstructorFieldInitializer (package:analyzer/src/summary2/ast_binary_writer.dart:156:5) 
#5 ConstructorFieldInitializerImpl.accept (package:analyzer/src/dart/ast/ast.dart:2595:15) 
#6 ResolutionSink._writeNode (package:analyzer/src/summary2/bundle_writer.dart:677:10) 
#7 ResolutionSink._writeNodeList (package:analyzer/src/summary2/bundle_writer.dart:683:7) 
#8 BundleWriter._writeConstructorElement.<anonymous closure> (package:analyzer/src/summary2/bundle_writer.dart:167:23) 
#9 _LocalElementIndexer.withElements (package:analyzer/src/summary2/bundle_writer.dart:925:6) 
#10 BundleWriter._writeConstructorElement (package:analyzer/src/summary2/bundle_writer.dart:163:35) 
#11 BundleWriter._writeList (package:analyzer/src/summary2/bundle_writer.dart:275:19) 
#12 BundleWriter._writeClassElement.<anonymous closure> (package:analyzer/src/summary2/bundle_writer.dart:149:9) 
#13 BundleWriter._writeTypeParameters.<anonymous closure> (package:analyzer/src/summary2/bundle_writer.dart:425:8) 
#14 _LocalElementIndexer.withElements (package:analyzer/src/summary2/bundle_writer.dart:925:6) 
#15 BundleWriter._writeTypeParameters (package:analyzer/src/summary2/bundle_writer.dart:423:35) 
#16 BundleWriter._writeClassElement (package:analyzer/src/summary2/bundle_writer.dart:134:5) 
#17 BundleWriter._writeList (package:analyzer/src/summary2/bundle_writer.dart:275:19) 
#18 BundleWriter._writeUnitElement (package:analyzer/src/summary2/bundle_writer.dart:437:5) 
#19 BundleWriter.writeLibraryElement (package:analyzer/src/summary2/bundle_writer.dart:112:7) 
#20 Linker._writeLibraries (package:analyzer/src/summary2/link.dart:220:20) 
#21 Linker.link (package:analyzer/src/summary2/link.dart:78:5) #22 link (package:analyzer/src/summary2/link.dart:34:10) 
#23 LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:176:30) 
#24 LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:206:7) 
#25 PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) 
#26 LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:204:12) 
#27 AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1444:24) 
#28 PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) 
#29 AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1431:20) 
#30 AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1055:22) 
#31 AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2137:24) <asynchronous suspension> 
#0 LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:267:5) 
#1 LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:181:11) 
#2 LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:206:7) 
#3 PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) 
#4 LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:204:12) 
#5 AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1444:24) 
#6 PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) 
#7 AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1431:20) 
#8 AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1055:22) 
#9 AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2137:24) <asynchronous suspension>

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1484:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1431:20)
#3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1055:22)
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2137:24)
<asynchronous suspension>
```

The error does not occur when I remove the `const` before `A`s constructor.  

I know the code is not correct and does not comile (the compiler shows a `Constant evaulation error`), but either way the analysis server should not crash.

**Comment by asashour** [comment]
I am unable to reproduce with:

```
Dart SDK version: 2.18.0-43.0.dev (dev) (Thu Apr 21 10:35:29 2022 -0700) on "windows_x64"
```

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/47963
