### ISSUE TITLE
[M1] test.py setting ulimit -n fails if already set

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48912]
After doing `ulimit -n 2048` on an M1 to make `tools/build.py` work with opening many files, `tools/test.py` fails:

```
Traceback (most recent call last):
  File "tools/test.py", line 57, in <module>
    sys.exit(Main())
  File "tools/test.py", line 38, in Main
    with utils.FileDescriptorLimitIncreaser():
  File "/Users/dacoharkes/dart-sdk/sdk/tools/utils.py", line 1094, in __enter__
    resource.setrlimit(resource.RLIMIT_NOFILE, self._limits)
ValueError: not allowed to raise maximum limit
```

If the `ulimit -n` is left to 256 (in a new Terminal), `test.py` succeeds.

**Comment by whesse** [comment]
Now only the superuser is allowed to raise the ulimits, and normal users can only decrease them.

The limits are started at the values given in "launchctl limit", so you need to increase the values given by that, not set them using ulimit -n.  Or else set the ulimit -n to 10000 or greater when you do it manually.

My launchctl limit on my M1 mac is set at 200000.  It does look like "sudo launchctl limit maxfiles 100000" works, and affects the system globally. But after rebooting, the value is set at 200000 again.

Have you verified that your ulimit -n is actually at 256 upon rebooting, or is it at 200000 by default?
