### ISSUE TITLE
lib_2/typed_data/float64x2_clamp_test is failing on simarm bot

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#48988]
from [logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8814579860922383761/+/u/test_results/new_test_failures__logs_)

```

/=======================================================================================\
| lib_2/typed_data/float64x2_clamp_test is new and failed (RuntimeError, expected Pass) |
\=======================================================================================/

--- Command "vm_compile_to_kernel" (took 584ms):
DART_CONFIGURATION=ReleaseSIMARM /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=out/ReleaseSIMARM/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseSIMARM/generated_compilations/dartk-linux-release-simarm/tests_lib_2_typed_data_float64x2_clamp_test/out.dill /b/s/w/ir/tests/lib_2/typed_data/float64x2_clamp_test.dart -Dtest_runner.configuration=dartk-linux-release-simarm --packages=/b/s/w/ir/.dart_tool/package_config.json -Ddart.vm.product=false

exit code:
0

--- Command "vm" (took 300ms):
DART_CONFIGURATION=ReleaseSIMARM out/ReleaseSIMARM/dart --optimization-counter-threshold=10 --no-background-compilation -Dtest_runner.configuration=dartk-linux-release-simarm --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseSIMARM/generated_compilations/dartk-linux-release-simarm/tests_lib_2_typed_data_float64x2_clamp_test/out.dill

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <-1>, actual: <0>) fails.
#0      Expect._fail (package:expect/expect.dart:742:5)
#1      Expect.equals (package:expect/expect.dart:132:5)
#2      testZeroClamp (file:///b/s/w/ir/tests/lib_2/typed_data/float64x2_clamp_test.dart:61:10)
#3      main (file:///b/s/w/ir/tests/lib_2/typed_data/float64x2_clamp_test.dart:73:5)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

--- Re-run this test:
python3 tools/test.py -n dartk-linux-release-simarm lib_2/typed_data/float64x2_clamp_test
```

**Comment by alexmarkov** [comment]
This test also fails on `vm-kernel-nnbd-linux-release-simarm` bot.

Logs: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8814579640137965729/+/u/test_results/new_test_failures__logs_

It started failing since it was added in 2a12dd3315421458b9818578f6ac996ceb6c1939. @aam Could you please take a look?
