### ISSUE TITLE
Map.entries crashes for non-self-similar keys

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#49033]
If you create a map whose keys aren't equal to themselves (such as `NaN`), `Map.entries` will crash with a type error:

```dart
void main() {
  print(({(0/0): 0}).entries);
}
```

```
Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      MapMixin.entries.<anonymous closure> (dart:collection/maps.dart:164:62)
#1      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#2      _iterablePartsToStrings (dart:collection/iterable.dart:319:13)
#3      IterableBase.iterableToShortString (dart:collection/iterable.dart:239:7)
#4      Iterable.toString (dart:core/iterable.dart:798:37)
#5      _StringBase._interpolateSingle (dart:core-patch/string_patch.dart:831:17)
#6      print (dart:core/print.dart:9:26)
#7      main (file:///home/nweiz/goog/sass/dart/test.dart:4:3)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

I believe the same is true for `Map.forEach()`.

**Comment by lrhn** [comment]
Interesting that `Infinity` breaks things too, because that is equal to itself. Will investigate.

**Comment by lrhn** [comment]
The code in question is:
```dart
    return keys.map((K key) => MapEntry<K, V>(key, this[key] as V));
```
which assumes that the lookup succeeds.
This is default `MapMixin` code which does not assume anything about the underlying representation.
It has no way to access the value of a key other than `operator[]`, which doesn't work for this key.
(In another map, I'd use the `values` iterator, but it has the exact same problem.)

In short, I cannot prevent this code from throwing. I can only make it throw something more useful.

I *can* make sure our hash-map implementations do not use the default code, so you won't hit the error using `{}`, and warn other uses of `MapMixin` that it won't work if `map[key]` doesn't actually gives the value associated with the key (aka, when `.containsKey(key)` gives false, even if the key is in the map, which in practice means it's NaN).
