### ISSUE TITLE
Analyzer FileResult.isPart returns false when it should return true

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#49031]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`) latest
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`) build_runner latest
  * _If you are not sure, try checking your `pubspec.lock` file._ see github repo
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do. freezed. https://github.com/rrousselGit/freezed/issues/668
* Whether you are using Windows, MacOSX, or Linux (if applicable) mac
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) na
* Any other packages or constraints we should know about na

Missing some or all of the above might make the issue take longer or be impossible to act on.

---

Hi thanks for the build runner! However I cannot run it. Although it looks like a `freezed` problem, but the error stack trace solely lies in `source_gen`, so I raise issue here.

Steps: Download https://github.com/fzyzcjy/freezed_build_runner_bug. Run `flutter pub get`. Run `flutter pub run build_runner build --delete-conflicting-outputs --verbose`.

Output:

```shell
...
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +82 ms] executing: /Users/tom/fvm/versions/3.0.0/bin/cache/dart-sdk/bin/dart __deprecated_pub run build_runner build
--delete-conflicting-outputs --verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 497ms

[WARNING] ApplyBuilders:
Configuring `mobx_codegen:mobx_generator` in target `freezed_build_runner_bug:freezed_build_runner_bug` but this is not a known Builder
[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 54ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 556ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 23ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 29ms

[SEVERE] source_gen:combining_builder on lib/src/model/a.freezed.dart (cached):

Asset [freezed_build_runner_bug|lib/src/model/a.freezed.dart] is not a Dart library. It may be a part file or a file without Dart source code.
package:build_resolvers/src/resolver.dart 222:7   AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 123:26  PerActionResolver.libraryFor.<fn>
package:source_gen/builder.dart 115:26            CombiningBuilder.build

[SEVERE] Build:
Failed after 89ms
[+2957 ms] "flutter run" took 3,124ms.
[   +5 ms] pub finished with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           dart-lang/build#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:416:7)
           <asynchronous suspension>
           dart-lang/build#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:251:5)
           <asynchronous suspension>
           dart-lang/build#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           dart-lang/build#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           dart-lang/build#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           dart-lang/build#6      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           dart-lang/build#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           dart-lang/build#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           dart-lang/build#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           dart-lang/build#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           dart-lang/build#11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +261 ms] ensureAnalyticsSent: 258ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by fzyzcjy** [comment]
🎉  You guys are great!

**Comment by bwilkerson** [comment]
Does this need to be cherry picked?

**Comment by jakemac53** [comment]
As far as build_runner is concerned we can just pick up the next pub release. Not sure if it causes other general issues with `dart analyze` though.

**Comment by scheglov** [comment]
I'm not sure. We use `AnalysisSession.getParsedUnit()` in DAS, so interactive DAS users could experience similar race conditions.

**Comment by fzyzcjy** [comment]
Hi, is it released to pub.dev now? https://pub.dev/packages/build_runner/changelog does have a new release but seems changelog does not mention this issue. Looking forward to the new release!

**Comment by natebosch** [comment]
The fix and changelog entry are in the `analyzer` package.

https://pub.dev/packages/analyzer/changelog

**Comment by fzyzcjy** [comment]
I see. Thank you!
