### ISSUE TITLE
causal_stacks/async_throws_stack_lazy_non_symbolic_test fails on Windows precomp product

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#49093]
The windows precompiled product bot was baselined from the windows precompiled release bot ([CL changing the bots](https://dart-review.googlesource.com/c/sdk/+/244321)).

The other issue with regard to the baseline also has to do with stack matching: https://github.com/dart-lang/sdk/issues/49092

cc @rmacnak-google 

```
stdout:
RegExps for expected stack:
"^#0      throwSync \(.*/utils.dart:18(:3)?\)$"
"^#1      allYield3 \(.*/utils.dart:41(:3)?\)$"
"^<asynchronous suspension>$"
"^#2      allYield2 \(.*/utils.dart:36(:3)?\)$"
"^<asynchronous suspension>$"
"^#3      allYield \(.*/utils.dart:31(:3)?\)$"
"^<asynchronous suspension>$"
"^#4      doTestAwait "
"^<asynchronous suspension>$"
"^#5      doTestsLazy "
"^<asynchronous suspension>$"
"^#6      main "
"^<asynchronous suspension>$"

Non-symbolic actual stack:
Warning: This VM has been configured to produce stack traces that violate the Dart standard.
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 9824, tid: 15208, name DartWorker
build_id: 'f62610a4d4fd44de0e1529b0d5427a21'
isolate_dso_base: 1c315d80000, vm_dso_base: 1c315d80000
isolate_instructions: 1c315dcc0f0, vm_instructions: 1c315dc8000
    #00 abs 000001c315e3f0bc virt 00000000000bf0bc _kDartIsolateSnapshotInstructions+0x72fcc
    #01 abs 000001c315e11fa8 virt 0000000000091fa8 _kDartIsolateSnapshotInstructions+0x45eb8
    #02 abs 000001c315e030ed virt 00000000000830ed _kDartIsolateSnapshotInstructions+0x36ffd
    #03 abs 000001c315dd00aa virt 00000000000500aa _kDartIsolateSnapshotInstructions+0x3fba
    #04 abs 000001c315e2cd18 virt 00000000000acd18 _kDartIsolateSnapshotInstructions+0x60c28
    #05 abs 000001c315dce23c virt 000000000004e23c _kDartIsolateSnapshotInstructions+0x214c
    #06 abs 000001c315dcf52c virt 000000000004f52c _kDartIsolateSnapshotInstructions+0x343c
    #07 abs 000001c315dcecc2 virt 000000000004ecc2 _kDartIsolateSnapshotInstructions+0x2bd2
    #08 abs 000001c315e2c56c virt 00000000000ac56c _kDartIsolateSnapshotInstructions+0x6047c
    #09 abs 000001c315dcec1e virt 000000000004ec1e _kDartIsolateSnapshotInstructions+0x2b2e
    #10 abs 000001c315dd0ca6 virt 0000000000050ca6 _kDartIsolateSnapshotInstructions+0x4bb6
    #11 abs 000001c315dd0c3c virt 0000000000050c3c _kDartIsolateSnapshotInstructions+0x4b4c

Actual stack:
#0      throwSync (file:///C:/b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/utils.dart:18:3)
#1      allYield3 (file:///C:/b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/utils.dart:41:3)
#2      _RootZone.runUnary (dart:async/zone.dart:1653:54)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:147:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:766:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:795:13)
#6      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:430:9)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)

Expected line 3 to be `^<asynchronous suspension>$` but was `#2      _RootZone.runUnary (dart:async/zone.dart:1653:54)`
```

[full log](https://dart-ci.appspot.com/log/vm-kernel-precomp-win-product-x64/dartkp-win-product-x64/1/vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test)

Test is also failing on other precomp product modes:

![image](https://user-images.githubusercontent.com/3601775/169961128-80f374f6-0e4f-4ce9-b5d5-0dc860f069e9.png)

**Comment by mkustermann** [comment]
Merging into https://github.com/dart-lang/sdk/issues/51468
