### ISSUE TITLE
vm/dart_2/invisible_function_pragma_test fails on Windows precomp product

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#49092]
The windows precompiled product bot was baselined from the windows precompiled release bot ([CL changing the bots](https://dart-review.googlesource.com/c/sdk/+/244321)).

cc @rmacnak-google 

```
exit code:
255

stdout:
RegExps for expected stack:
"^#0      main.<anonymous closure>"
"^#1      main"
"#@ IGNORE_REMAINING_STACK #@"

Actual stack:
#0      main.<anonymous closure> (file:///C:/b/s/w/ir/runtime/tests/vm/dart_2/invisible_function_pragma_test.dart:27)
#1      visible (file:///C:/b/s/w/ir/runtime/tests/vm/dart_2/invisible_function_pragma_test.dart:71)
#2      main (file:///C:/b/s/w/ir/runtime/tests/vm/dart_2/invisible_function_pragma_test.dart:35)
<asynchronous suspension>

Expected line 2 to be `^#1      main` but was `#1      visible (file:///C:/b/s/w/ir/runtime/tests/vm/dart_2/invisible_function_pragma_test.dart:71)`

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:742)
#1      Expect.isTrue (package:expect/expect.dart:141)
#2      assertStack (file:///C:/b/s/w/ir/runtime/tests/vm/dart_2/causal_stacks/utils.dart:249)
<asynchronous suspension>
#3      main (file:///C:/b/s/w/ir/runtime/tests/vm/dart_2/invisible_function_pragma_test.dart:36)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartkp-win-product-x64 vm/dart_2/invisible_function_pragma_test
```

[full log](https://dart-ci.appspot.com/log/vm-kernel-precomp-win-product-x64/dartkp-win-product-x64/1/vm/dart_2/invisible_function_pragma_test)

The test is currently failing on:

![image](https://user-images.githubusercontent.com/3601775/169960439-df3a63d4-dcff-4768-bb4c-f74bfb39bac4.png)

**Comment by mkustermann** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/51468
