### ISSUE TITLE
The result of RegExp comparison can be different

### ISSUE THREAD

**Issue by nikitadol** [dart-lang/sdk#49126]
Need to mention somewhere in the documentation or fix the comparison for the `RegExp` class

```
Dart SDK version: 2.17.0 (stable) (Mon May 9 10:36:47 2022 +0200) on "macos_arm64"
```

```dart
void main() {
  final firstRegexp = _createFirstRegExp();

  assert(firstRegexp == _createFirstRegExp());

  for (var i = 0; i < 300; i++) {
    RegExp('$i');
  }

  assert(firstRegexp == _createFirstRegExp());
}

RegExp _createFirstRegExp() => RegExp(r'0');
```

```
dart --enable-asserts lib/main.dart
Unhandled exception:
'package:bug/main.dart': Failed assertion: line 10 pos 10: 'firstRegexp == _createFirstRegExp()': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      main (package:bug/main.dart:10:10)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by lrhn** [comment]
There is no special equality for `RegExp` objects, the probably do not even override `opertor==` or `hashCode`.
The result would be the same if you used `identical` instead of `==`.
What you are seeing is the effect of caching.

The `RegExp` constructor is a factory constructor, so it doesn't have to create a new object on each invocation.
And in some implementations it sometimes doesn't. If you create multiple equivalent `RegExp` objects (same pattern string and flags) quickly after each other, the VM reuses the previously created object instead of creating a new one.

We can document this. We probably should, since the constructor documentation right now say
> Constructs a regular expression.

and it doesn't always construct a new one.

The documentation can be as simple as.

> This constructor is allowed, but not required, to return a previously created \[RegExp\] object
> instead of creating a new one. 

Maybe add:

> Since \`RegExp\` objects are defined entirely in terms of their
> pattern and flags, multiple invocations with the same pattern and flags
> can safely return the same object.
