### ISSUE TITLE
Could not find a file named "pubspec.yaml" in .pub-cache

### ISSUE THREAD

**Issue by probablykasper** [dart-lang/sdk#49167]
I'm trying to run a Dart file, but ​I'm getting this error:
```
Could not find a file named "pubspec.yaml" in "/Users/k/.pub-cache/git/plus_plugins-57973884a6c715b556f5853019cd8946e8db9dc4/packages/android_alarm_manager_plus".
#0      new Pubspec.load (package:pub/src/pubspec.dart:307:7)
#1      new Package.load (package:pub/src/package.dart:128:29)
#2      SystemCache.load (package:pub/src/system_cache.dart:105:20)
#3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:119:63)
#4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:114:54)
#5      getExecutableForCommand (package:pub/src/executable.dart:338:19)
#6      RunCommand.run (package:dartdev/src/commands/run.dart:250:32)
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:30)
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#10     new Future.sync (dart:async/future.dart:301:31)
#11     CommandRunner.run (package:args/command_runner.dart:119:14)
#12     runDartdev (package:dartdev/dartdev.dart:66:29)
#13     main (file:///opt/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

For some reason it seems to be looking for `.pub-cache` in the wrong folder. The `.pub-cache` is in `/usr/local/Caskroom/flutter/3.0.1/flutter/.pub-cache` for me

**Comment by lrhn** [comment]
It might be a case of `flutter` and `dart` using separate cache directories. Are you using the `dart` installed with the Flutter SDK, or a separate installation of the Dart SDK?

**Comment by probablykasper** [comment]
I'm using `dart` from the Flutter SDK, yes.

`dart` path: `/usr/local/Caskroom/flutter/3.0.1/flutter/bin/dart`
`flutter` path: `/usr/local/Caskroom/flutter/3.0.1/flutter/bin/flutter`

**Comment by bkonyi** [comment]
cc @jonasfj @sigurdm

**Comment by jonasfj** [comment]
Looks more like a possible cache corruption, try `dart pub cache repair` or `dart pub cache clean` (warning this will clear your pub-cache, so you'll need to download everything again).

It could also be more confusion over:
https://github.com/flutter/flutter/issues/53833

But you probably have a folder named `/Users/k/.pub-cache/git/plus_plugins-57973884a6c715b556f5853019cd8946e8db9dc4/`.

**Comment by probablykasper** [comment]
I don't have `/Users/k/.pub-cache` folder, it's at `/usr/local/Caskroom/flutter/3.0.1/flutter/.pub-cache`. The reason would indeed be that Flutter for some reason uses a different `.pub-cache` location.

If I want to run a Dart file in a Flutter project, am I expected to install the dependencies twice in two different locations, or is there a different way that I'm missing?

Is this error message what you're supposed to get whenever you have dependencies that aren't installed? In that case, there should probably be a more helpful error message

**Comment by jonasfj** [comment]
> If I want to run a Dart file in a Flutter project, am I expected to install the dependencies twice in two different locations

No, this should just work. If it needs to fetch it again, it should do so automatically in most cases.
