### ISSUE TITLE
The compiler crashed: Null check operator used on a null value: dart2js

### ISSUE THREAD

**Issue by ChamplainLeCode** [dart-lang/sdk#49192]
Hello I faced some issue when I built my Flutter app for web

**NOTE THAT MY APP RUNS WELL IN DEBUG MODE**

## The full stack trace
```
The compiler crashed: Null check operator used on a null value
#0      BinaryPrinter.visitExtension (package:kernel/binary/ast_to_binary.dart:2501:73)
#1      Extension.accept (package:kernel/ast.dart:1601:38)
#2      BinaryPrinter.writeExtensionNode (package:kernel/binary/ast_to_binary.dart:479:10)
#3      BinaryPrinter.writeExtensionNodeList (package:kernel/binary/ast_to_binary.dart:376:7)
#4      BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1060:5)
#5      Library.accept (package:kernel/ast.dart:557:38)
#6      BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:451:10)
#7      BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:756:9)
#8      BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:595:7)
#9      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#10     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:577:14)
#11     KernelLoaderTask.load.<anonymous closure>.<anonymous closure> (package:compiler/src/kernel/loader.dart:242:19)
#12     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#13     KernelLoaderTask.load.<anonymous closure> (package:compiler/src/kernel/loader.dart:236:9)
<asynchronous suspension>
#14     Compiler.runInternal (package:compiler/src/compiler.dart:311:29)
<asynchronous suspension>
```

## Here is the Log as image

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/26502711/172291803-d869730c-7de6-4794-9693-1b527bec5120.png">

[@Karee](https://github.com/ChamplainLeCode/karee) @Bixterprise

**Comment by chloestefantsova** [comment]
The Dart SDK version in this issue is 2.15.1. I found a very similar and potentially same issue discovered in the Dart SDK version 2.16.0 that was addressed some time ago: https://github.com/flutter/flutter/issues/94561. @ChamplainLeCode could you update the Dart SDK and tell if you can still observe the crash after that?

**Comment by chloestefantsova** [comment]
I'm closing this issue for now. Please reopen if needed.
