### ISSUE TITLE
Missing compile time error or crash bug with type argument embedded in a constant

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#49206]
The CFE will crash running the following program. There is no analysis error but it seems strange to have a type parameter appear in a const expression. Is this a missing error or a crash bug?

```dart
class A<T> {}

fn<T>() {
  return const <A<T>>[];
}

main() {}
```

```
Invalid argument(s): Type parameter TypeParameter(T) is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:2921:8)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2426:38)
#2      TypeParameterType.accept (package:kernel/ast.dart:11890:42)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
#4      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:340:7)
#5      BinaryPrinter.visitInterfaceType (package:kernel/binary/ast_to_binary.dart:2324:7)
#6      InterfaceType.accept (package:kernel/ast.dart:11106:42)
#7      BinaryPrinter.writeDartType (package:kernel/binary/ast_to_binary.dart:309:10)
#8      BinaryPrinter.writeConstantTableEntry (package:kernel/binary/ast_to_binary.dart:246:7)
#9      BinaryPrinter.writeConstantTable (package:kernel/binary/ast_to_binary.dart:198:7)
#10     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:598:7)
#11     Timeline.timeSync (dart:developer/timeline.dart:157:22)
#12     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:577:14)
#13     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:94:11)
#14     _processLoadRequest (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:920:41)
<asynchronous suspension>
```

@johnniwinther @eernstg

**Comment by eernstg** [comment]
There a missing error problem in any case, because `A<T>` is not a [constant type expression](https://github.com/dart-lang/language/blob/812f939ec0130da119ad2cbe5f9a4121e31b0831/specification/dartLangSpec.tex#L8371).
