### ISSUE TITLE
Analyzer crashes accessing the superConstructorParameter of a SuperFormalParameterElement

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#49225]
I haven't been able to make a minimal reproduction of this. :/ The only one I have takes more than 10 minutes, running dartdoc over flutter.

1. get dartdoc
2. bump analyzer dep to `^4.1.0`, or use `dependency_overrides` to use main branch at HEAD (which also lets you do print debugging)
3. run `DARTDOC_BOT=flutter ./tool/ci.sh`

You get a crash like

```none
flutter-docs: dartdoc 5.1.3-dev (/Users/srawlins/code/dart-dartdoc/.dart_tool/pub/bin/dartdoc/dartdoc.dart-2.18.0-170.0.dev.snapshot) failed: Bad state: Members must be created from a declaration, but is "{Key key}" (SuperFormalParameterMember) (parent: PopupMenuEntry<T> PopupMenuEntry({Key? key})).
flutter-docs: #0      new Member (package:analyzer/src/dart/element/member.dart:463:7)
flutter-docs: #1      new ParameterMember._ (package:analyzer/src/dart/element/member.dart)
flutter-docs: #2      new ParameterMember (package:analyzer/src/dart/element/member.dart:824:28)
flutter-docs: #3      SuperFormalParameterMember.superConstructorParameter (package:analyzer/src/dart/element/member.dart:1088:12)
flutter-docs: #4      Constructor.referenceChildren.<anonymous closure>.dereferenceParameter (package:dartdoc/src/model/constructor.dart:107:47)
flutter-docs: #5      Constructor.referenceChildren.<anonymous closure>.dereferenceParameter (package:dartdoc/src/model/constructor.dart:107:16)
flutter-docs: #6      Constructor.referenceChildren.<anonymous closure>.<anonymous closure> (package:dartdoc/src/model/constructor.dart:114:26)
...
```

I've tried to minimally reproduce the PopupMenuEntry hierarchy:

```dart
class Key {}

class Widget {
  const Widget({Key? key});
}

class StatefulWidget extends Widget {
  const StatefulWidget({super.key});
}

abstract class PopupMenuEntry<T> extends StatefulWidget {
  const PopupMenuEntry({super.key});
}

class PopupMenuDivider extends PopupMenuEntry<Never> {
  final int height;
  const PopupMenuDivider({super.key, this.height = 0});
}

class PopupMenuItem<T> extends PopupMenuEntry<T> {
  const PopupMenuItem({super.key});
}

class CheckedPopupMenuItem<T> extends PopupMenuItem<T> {
  const CheckedPopupMenuItem({super.key});
}
```

but resolving this does not throw an error, and I can't seem to get the error by calling `superConstructorParameter` on a SuperFormalParameterElement, like dartdoc does. I've tried using the resolution test finders like so:

```dart
var entryKeySP = findElement
    .unnamedConstructor('PopupMenuEntry')
    .superFormalParameter('key');
entryKeySP.superConstructorParameter;
```

CC @scheglov for tips

**Comment by scheglov** [comment]
I was able to reproduce it with
```dart
  solo_test_XXX() async {
    await assertNoErrorsInCode(r'''
class A<T> {
  const A({int? key});
}

class B<T> extends A<T> {
  const B({super.key});
}

class C<T> extends B<T> {
  const C({super.key});
}
''');

    final C_key =
        findElement.unnamedConstructor('C').superFormalParameter('key');
    final B_key =
        C_key.superConstructorParameter as SuperFormalParameterElement;
    print(B_key);
    print(B_key.superConstructorParameter);
  }
```

**Comment by srawlins** [comment]
@scheglov Are you able to look into this crash? This issue is preventing dartdoc from depending on analyzer 4.0.0 or 4.1.0.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/249550
