### ISSUE TITLE
Incorrectly non-nullable typed `_CastError` fields

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#49279]
Running
```dart
main() {
  try {
    null!;
  } on TypeError {
    // _CastError implements TypeError
  }
}
```
should result in a swallowed exception, but actually results in:
```
% out/ReleaseX64/dart --null-assertions --no-sound-null-safety --enable-asserts test.dart
Unhandled exception:
'dart:core-patch/errors_patch.dart': Failed assertion: line 117 pos 27: '_url != null': is not true.
#0      _AssertionError._doThrowNewSource (dart:core-patch/errors_patch.dart:54:69)
#1      _AssertionError._throwNewNullAssertion (dart:core-patch/errors_patch.dart:46:5)
#2      new _CastError._create (dart:core-patch/errors_patch.dart:117:27)
#3      main
```

**Comment by dcharkes** [comment]
This issue resurfaces with replacing the `CastError` with `TypeError`. I will address this in the migration CL.

Thanks for the regression test @mkustermann!
