### ISSUE TITLE
dartdevc/static_interop_erasure/main Crashes on fuzzing

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#49301]
This will fail (possibly the status entry in `pkg/front_end/testcases/strong.status` has to be removed):
`out/ReleaseX64/dart --enable-asserts pkg/front_end/test/fasta/strong_suite.dart -DsemiFuzz=true -- strong/dartdevc/static_interop_erasure/main`

A "normal compile" doesn't fail, but on fuzzing it does. The reason seems to be the ordering of libraries (and what's included) -- and that `visitStaticInvocation` calls `_findOrCreateFactoryStub` on the target, where if `stubs.isEmpty` it assumes that the parent class of the target is in the same class as we're currently visiting

```
      // We should only create the stub if we're processing the library in which
      // the stub should exist. Any static invocation of the factory that
      // doesn't exist in the same library as the factory should be processed
      // after the library in which the factory exists. In modular compilation,
      // the outline of that library should already contain the needed stub.
      assert(factoryClass.enclosingLibrary == currLibrary);
```

From the comment maybe this is expected because it's not in a "proper modular setting" (though it does seem dangerous that the target of a static invocation is either in the same library or already processed).

The crash:

```
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      StaticInteropClassEraser._findOrCreateFactoryStub (package:_js_interop_checks/src/transformations/static_interop_class_eraser.dart:62:14)
#3      StaticInteropClassEraser.visitStaticInvocation (package:_js_interop_checks/src/transformations/static_interop_class_eraser.dart:175:20)
#4      StaticInvocation.accept (package:kernel/ast.dart:6627:44)
#5      Transformer.transform (package:kernel/visitor.dart:1564:21)
#6      VariableDeclaration.transformChildren (package:kernel/ast.dart:10821:23)
#7      Transformer.defaultTreeNode (package:kernel/visitor.dart:1622:10)
#8      TreeVisitor.defaultStatement (package:kernel/visitor.dart:339:41)
#9      TreeVisitor.visitVariableDeclaration (package:kernel/visitor.dart:380:7)
#10     VariableDeclaration.accept (package:kernel/ast.dart:10803:43)
#11     Transformer.transform (package:kernel/visitor.dart:1564:21)
#12     Transformer.transformList (package:kernel/visitor.dart:1599:18)
#13     Block.transformChildren (package:kernel/ast.dart:9235:7)
#14     Transformer.defaultTreeNode (package:kernel/visitor.dart:1622:10)
#15     TreeVisitor.defaultStatement (package:kernel/visitor.dart:339:41)
#16     TreeVisitor.visitBlock (package:kernel/visitor.dart:344:31)
#17     Block.accept (package:kernel/ast.dart:9223:43)
#18     Transformer.transform (package:kernel/visitor.dart:1564:21)
#19     FunctionNode.transformChildren (package:kernel/ast.dart:3894:16)
#20     Transformer.defaultTreeNode (package:kernel/visitor.dart:1622:10)
#21     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:428:45)
#22     FunctionNode.accept (package:kernel/ast.dart:3868:38)
#23     Transformer.transform (package:kernel/visitor.dart:1564:21)
#24     Procedure.transformChildren (package:kernel/ast.dart:3194:20)
#25     Transformer.defaultTreeNode (package:kernel/visitor.dart:1622:10)
#26     TreeVisitor.defaultMember (package:kernel/visitor.dart:387:35)
#27     TreeVisitor.visitProcedure (package:kernel/visitor.dart:391:39)
#28     StaticInteropClassEraser.visitProcedure (package:_js_interop_checks/src/transformations/static_interop_class_eraser.dart:142:18)
#29     Procedure.accept (package:kernel/ast.dart:3173:40)
#30     Transformer.transform (package:kernel/visitor.dart:1564:21)
#31     Transformer.transformList (package:kernel/visitor.dart:1599:18)
#32     Library.transformChildren (package:kernel/ast.dart:586:7)
#33     Transformer.defaultTreeNode (package:kernel/visitor.dart:1622:10)
#34     TreeVisitor.visitLibrary (package:kernel/visitor.dart:422:35)
#35     StaticInteropClassEraser.visitLibrary (package:_js_interop_checks/src/transformations/static_interop_class_eraser.dart:82:18)
#36     DevCompilerTarget.performModularTransformationsOnLibraries (package:dev_compiler/src/kernel/target.dart:183:32)
#37     TestTarget.performModularTransformationsOnLibraries ([...]/pkg/front_end/test/fasta/testing/suite.dart:2510:13)
#38     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1628:19)
#39     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:643:7)
<asynchronous suspension>
#40     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#41     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:412:23)
<asynchronous suspension>
#42     FuzzCompiles.performFileInvalidation ([...]/pkg/front_end/test/fasta/testing/suite.dart:1283:9)
<asynchronous suspension>
#43     FuzzCompiles.run ([...]/pkg/front_end/test/fasta/testing/suite.dart:1213:45)
<asynchronous suspension>
#44     ChainContext.run.doStep.<anonymous closure> (package:testing/src/chain.dart:188:22)
<asynchronous suspension>
```

/cc @srujzs

**Comment by srujzs** [comment]
Thanks for catching this and filing!

> From the comment maybe this is expected because it's not in a "proper modular setting" (though it does seem dangerous that the target of a static invocation is either in the same library or already processed).

I'm unfamiliar with how the fuzzing works here - why is this possible? More specifically, my question is what's being fuzzed and how does modular compilation work differently? I had assumed that the invariant of any modular compile should process the library's dependencies first, so those dependencies should already contain the necessary method/stub. Clearly, that invariant doesn't seem to hold here. From a brief debugging, it looks like the stub creator is never called to write that stub to the outline.

If this is intentional on the fuzzing part, I have two follow-up questions:

1. Is this difference in modular compilation unique to fuzzing? i.e. should we expect the above invariant to hold for all other applications?
2. How useful is this test case for the fuzzer?

I ask 1, because if it's not unique to the fuzzer, this invariant needs to be removed and we should reconsider how this eraser works.

I ask 2, because if it isn't useful, I'm tempted to leave the status file as it is, as the invariant is a useful sanity check. If the test is useful, I'm okay with removing the invariant.

**Comment by jensjoha** [comment]
The fuzzing - in this case - just tries to compile the whole thing at once (I think). So it's not "modular".

What about something like this --- is that outside the realms of possibility?

`lib1.dart`:

```
@JS()
library static_interop1;

import 'package:js/js.dart';
import 'lib2.dart' as lib2;

@JS()
external void eval(String code);

@JS('JSClass')
@staticInterop
class StaticJSClass {
  external StaticJSClass();
  factory StaticJSClass.factory() {
    return StaticJSClass();
  }
}

void foo() {
  lib2.setUp();
  print(lib2.StaticJSClass2.factory());
}

void setUp() {
  eval('''function JSClass() {}''');
}
```

`lib2.dart`:

```
@JS()
library static_interop2;

import 'package:js/js.dart';
import 'lib1.dart' as lib1;

@JS()
external void eval(String code);

@JS('JSClass2')
@staticInterop
class StaticJSClass2 {
  external StaticJSClass2();
  factory StaticJSClass2.factory() {
    return StaticJSClass2();
  }
}

void foo() {
  lib1.setUp();
  print(lib1.StaticJSClass.factory());
}

void setUp() {
  eval('''function JSClass2() {}''');
}
```

**Comment by srujzs** [comment]
@johnniwinther 

I think I have this somewhat narrowed down, and was wondering if you could help see where things are going wrong. You can patch the above CL and run the fuzz test suite to repro.

When `main_lib` gets invalidated and recompiled, the serialization tries to compute canonical names. Since we recompile, we add the new stub again, except the canonical name is now no longer prefixed the same. For example, `StaticJSClass.factory`'s reference points to `file:///Users/srujzs/dart-sdk/sdk/pkg/front_end/testcases/dartdevc/static_interop_erasure/main_lib.dart::StaticJSClass::@factories::factory` while the new stub I created points to `StaticJSClass.factory|staticInteropFactoryStub`. This leads to the above mismatch error. It seems like we (correctly) create _a_ canonical name, but do not prefix it correctly when we do create that canonical name for that stub.

**Comment by srujzs** [comment]
(reposting because my previous comment was incorrect)

@johnniwinther

I think I have this somewhat narrowed down, and was wondering if you could help see where things are going wrong. You can patch the above CL and run the fuzz test suite to repro.

When main_lib gets invalidated and recompiled, the serialization tries to compute canonical names. Since we recompile, we add the new stub again, but with no provided reference, so the canonical name is null. The canonical name for the stub still exists, but is bound to the old invalidated reference. When we try to bind it to the new reference, we see the collision. Should we be `unbind`ing that canonical name somewhere?

**Comment by jensjoha** [comment]
This is caused by not providing a reference. Something like this (which is otherwise untested) seems to work:

```
diff --git a/pkg/_js_interop_checks/lib/src/transformations/static_interop_class_eraser.dart b/pkg/_js_interop_checks/lib/src/transformations/static_interop_class_eraser.dart
index 163fe49d662..94bd026d6e3 100644
--- a/pkg/_js_interop_checks/lib/src/transformations/static_interop_class_eraser.dart
+++ b/pkg/_js_interop_checks/lib/src/transformations/static_interop_class_eraser.dart
@@ -6,6 +6,7 @@ import 'package:kernel/ast.dart';
 import 'package:kernel/clone.dart';
 import 'package:kernel/core_types.dart';
 import 'package:kernel/kernel.dart';
+import 'package:kernel/reference_from_index.dart';
 import 'package:kernel/src/replacement_visitor.dart';
 import 'package:_js_interop_checks/src/js_interop.dart';
 
@@ -29,8 +30,9 @@ class StaticInteropClassEraser extends Transformer {
   final CloneVisitorNotMembers _cloner = CloneVisitorNotMembers();
   late final _TypeSubstitutor _typeSubstitutor;
   Component? currentComponent;
+  ReferenceFromIndex? referenceFromIndex;
 
-  StaticInteropClassEraser(CoreTypes coreTypes,
+  StaticInteropClassEraser(CoreTypes coreTypes, this.referenceFromIndex,
       {String libraryForJavaScriptObject = 'dart:_interceptors',
       String classNameOfJavaScriptObject = 'JavaScriptObject'})
       : _javaScriptObject = coreTypes.index
@@ -63,9 +65,16 @@ class StaticInteropClassEraser extends Transformer {
       if (currentComponent != null) {
         assert(factoryTarget.enclosingComponent == currentComponent);
       }
+      Name name = Name(stubName);
+      IndexedLibrary? indexedLibrary =
+          referenceFromIndex?.lookupLibrary(factoryClass.enclosingLibrary);
+      IndexedClass? indexedClass =
+          indexedLibrary?.lookupIndexedClass(factoryClass.name);
       var staticMethod = Procedure(
-          Name(stubName), ProcedureKind.Method, FunctionNode(null),
-          isStatic: true, fileUri: factoryTarget.fileUri)
+          name, ProcedureKind.Method, FunctionNode(null),
+          isStatic: true,
+          fileUri: factoryTarget.fileUri,
+          reference: indexedClass?.lookupGetterReference(name))
         ..fileOffset = factoryTarget.fileOffset;
       factoryClass.addProcedure(staticMethod);
       // Clone function node after processing the stub in case of mutually
diff --git a/pkg/compiler/lib/src/kernel/dart2js_target.dart b/pkg/compiler/lib/src/kernel/dart2js_target.dart
index df7624c5f39..e5f72f558ef 100644
--- a/pkg/compiler/lib/src/kernel/dart2js_target.dart
+++ b/pkg/compiler/lib/src/kernel/dart2js_target.dart
@@ -139,9 +139,9 @@ class Dart2jsTarget extends Target {
 
   @override
   void performOutlineTransformations(
-      ir.Component component, CoreTypes coreTypes) {
+      ir.Component component, CoreTypes coreTypes, ReferenceFromIndex? referenceFromIndex) {
     component
-        .accept(StaticInteropStubCreator(StaticInteropClassEraser(coreTypes)));
+        .accept(StaticInteropStubCreator(StaticInteropClassEraser(coreTypes, referenceFromIndex)));
   }
 
   @override
@@ -157,7 +157,7 @@ class Dart2jsTarget extends Target {
       ChangedStructureNotifier? changedStructureNotifier}) {
     var nativeClasses = JsInteropChecks.getNativeClasses(component);
     var jsUtilOptimizer = JsUtilOptimizer(coreTypes, hierarchy);
-    var staticInteropClassEraser = StaticInteropClassEraser(coreTypes);
+    var staticInteropClassEraser = StaticInteropClassEraser(coreTypes, referenceFromIndex);
     for (var library in libraries) {
       JsInteropChecks(
               coreTypes,
diff --git a/pkg/dev_compiler/lib/src/kernel/target.dart b/pkg/dev_compiler/lib/src/kernel/target.dart
index fa648bb5da7..795d503165c 100644
--- a/pkg/dev_compiler/lib/src/kernel/target.dart
+++ b/pkg/dev_compiler/lib/src/kernel/target.dart
@@ -153,9 +153,10 @@ class DevCompilerTarget extends Target {
   bool get enableNoSuchMethodForwarders => true;
 
   @override
-  void performOutlineTransformations(Component component, CoreTypes coreTypes) {
-    component
-        .accept(StaticInteropStubCreator(StaticInteropClassEraser(coreTypes)));
+  void performOutlineTransformations(Component component, CoreTypes coreTypes,
+      ReferenceFromIndex? referenceFromIndex) {
+    component.accept(StaticInteropStubCreator(
+        StaticInteropClassEraser(coreTypes, referenceFromIndex)));
   }
 
   @override
@@ -171,7 +172,8 @@ class DevCompilerTarget extends Target {
       ChangedStructureNotifier? changedStructureNotifier}) {
     _nativeClasses ??= JsInteropChecks.getNativeClasses(component);
     var jsUtilOptimizer = JsUtilOptimizer(coreTypes, hierarchy);
-    var staticInteropClassEraser = StaticInteropClassEraser(coreTypes);
+    var staticInteropClassEraser =
+        StaticInteropClassEraser(coreTypes, referenceFromIndex);
     for (var library in libraries) {
       _CovarianceTransformer(library).transform();
       JsInteropChecks(
diff --git a/pkg/front_end/lib/src/api_prototype/incremental_kernel_generator.dart b/pkg/front_end/lib/src/api_prototype/incremental_kernel_generator.dart
index 880d7647fbe..85bdd745d37 100644
--- a/pkg/front_end/lib/src/api_prototype/incremental_kernel_generator.dart
+++ b/pkg/front_end/lib/src/api_prototype/incremental_kernel_generator.dart
@@ -11,6 +11,7 @@ import 'package:kernel/core_types.dart' show CoreTypes;
 
 import 'package:kernel/kernel.dart'
     show Component, Library, Procedure, DartType, TypeParameter;
+import 'package:kernel/reference_from_index.dart';
 
 import '../base/processed_options.dart' show ProcessedOptions;
 
@@ -152,7 +153,11 @@ class IncrementalCompilerResult {
   final ClassHierarchy? classHierarchy;
   final CoreTypes? coreTypes;
   final Set<Library>? neededDillLibraries;
+  final ReferenceFromIndex? referenceFromIndex;
 
   IncrementalCompilerResult(this.component,
-      {this.classHierarchy, this.coreTypes, this.neededDillLibraries});
+      {this.classHierarchy,
+      this.coreTypes,
+      this.neededDillLibraries,
+      this.referenceFromIndex});
 }
diff --git a/pkg/front_end/lib/src/fasta/incremental_compiler.dart b/pkg/front_end/lib/src/fasta/incremental_compiler.dart
index 58d6b732f2c..be3c4cf8dae 100644
--- a/pkg/front_end/lib/src/fasta/incremental_compiler.dart
+++ b/pkg/front_end/lib/src/fasta/incremental_compiler.dart
@@ -529,7 +529,8 @@ class IncrementalCompiler implements IncrementalKernelGenerator {
       return new IncrementalCompilerResult(result,
           classHierarchy: currentKernelTarget.loader.hierarchy,
           coreTypes: currentKernelTarget.loader.coreTypes,
-          neededDillLibraries: neededDillLibraries);
+          neededDillLibraries: neededDillLibraries,
+          referenceFromIndex: currentKernelTarget.loader.referenceFromIndex);
     });
   }
 
diff --git a/pkg/front_end/lib/src/kernel_generator_impl.dart b/pkg/front_end/lib/src/kernel_generator_impl.dart
index 0a41e53deca..1d35c50910f 100644
--- a/pkg/front_end/lib/src/kernel_generator_impl.dart
+++ b/pkg/front_end/lib/src/kernel_generator_impl.dart
@@ -189,7 +189,9 @@ Future<CompilerResult> _buildInternal(
     // the only need we have for these transformations).
     if (!buildComponent) {
       options.target.performOutlineTransformations(
-          trimmedSummaryComponent, kernelTarget.loader.coreTypes);
+          trimmedSummaryComponent,
+          kernelTarget.loader.coreTypes,
+          kernelTarget.loader.referenceFromIndex);
       options.ticker.logMs("Transformed outline");
     }
     // Don't include source (but do add it above to include importUris).
diff --git a/pkg/frontend_server/lib/compute_kernel.dart b/pkg/frontend_server/lib/compute_kernel.dart
index d9334e38f01..eaa4a02fdf9 100644
--- a/pkg/frontend_server/lib/compute_kernel.dart
+++ b/pkg/frontend_server/lib/compute_kernel.dart
@@ -397,7 +397,7 @@ Future<ComputeKernelResult> computeKernel(List<String> args,
         incrementalComponent.setMainMethodAndMode(
             null, true, incrementalComponent.mode);
         target.performOutlineTransformations(
-            incrementalComponent, incrementalCompilerResult.coreTypes!);
+            incrementalComponent, incrementalCompilerResult.coreTypes!, incrementalCompilerResult.referenceFromIndex);
         makeStable(incrementalComponent);
         return Future.value(fe.serializeComponent(incrementalComponent,
             includeSources: false, includeOffsets: false));
diff --git a/pkg/kernel/lib/ast.dart b/pkg/kernel/lib/ast.dart
index 4c79f853e14..5c6705f043a 100644
--- a/pkg/kernel/lib/ast.dart
+++ b/pkg/kernel/lib/ast.dart
@@ -138,6 +138,7 @@ abstract class Node {
 ///
 /// This is anything other than [Name] and [DartType] nodes.
 abstract class TreeNode extends Node {
+  StackTrace st = StackTrace.current;
   static int _hashCounter = 0;
   @override
   final int hashCode = _hashCounter = (_hashCounter + 1) & 0x3fffffff;
diff --git a/pkg/kernel/lib/canonical_name.dart b/pkg/kernel/lib/canonical_name.dart
index 0549ea4b98e..a46e3ddab59 100644
--- a/pkg/kernel/lib/canonical_name.dart
+++ b/pkg/kernel/lib/canonical_name.dart
@@ -227,12 +227,14 @@ class CanonicalName {
         sb.write(' with node ${_reference?._node}'
             ' (${_reference?._node.runtimeType}'
             ':${_reference?._node.hashCode})');
+            sb.write("created at ${_reference!._node!.st}");
       }
       sb.write(', trying to bind to ${target}');
       if (target._node != null) {
         sb.write(' with node ${target._node}'
             ' (${target._node.runtimeType}'
             ':${target._node.hashCode})');
+        sb.write("created at ${target._node!.st}");
       }
       throw sb.toString();
     }
diff --git a/pkg/kernel/lib/target/targets.dart b/pkg/kernel/lib/target/targets.dart
index ced147d512f..41663f13542 100644
--- a/pkg/kernel/lib/target/targets.dart
+++ b/pkg/kernel/lib/target/targets.dart
@@ -318,8 +318,8 @@ abstract class Target {
   /// transformation is not applied when compiling full kernel programs to
   /// prevent affecting the internal invariants of the compiler and accidentally
   /// slowing down compilation.
-  void performOutlineTransformations(
-      Component component, CoreTypes coreTypes) {}
+  void performOutlineTransformations(Component component, CoreTypes coreTypes,
+      ReferenceFromIndex? referenceFromIndex) {}
 
   /// Perform target-specific transformations on the given libraries that must
   /// run before constant evaluation.
@@ -1011,8 +1011,10 @@ class TargetWrapper extends Target {
   }
 
   @override
-  void performOutlineTransformations(Component component, CoreTypes coreTypes) {
-    _target.performOutlineTransformations(component, coreTypes);
+  void performOutlineTransformations(Component component, CoreTypes coreTypes,
+      ReferenceFromIndex? referenceFromIndex) {
+    _target.performOutlineTransformations(
+        component, coreTypes, referenceFromIndex);
   }
 
   @override
@@ -1077,8 +1079,10 @@ mixin SummaryMixin on Target {
   bool get excludeNonSources;
 
   @override
-  void performOutlineTransformations(Component component, CoreTypes coreTypes) {
-    super.performOutlineTransformations(component, coreTypes);
+  void performOutlineTransformations(Component component, CoreTypes coreTypes,
+      ReferenceFromIndex? referenceFromIndex) {
+    super.performOutlineTransformations(
+        component, coreTypes, referenceFromIndex);
     if (!excludeNonSources) return;
 
     List<Library> libraries = new List.of(component.libraries);
```

**Comment by srujzs** [comment]
Ah, I didn't know there was any exposed mechanism to lookup references - I was thinking maybe `CanonicalName` should handle this internally, but providing the reference directly is more consistent with how the rest of the members in the class are loaded. This is fantastic, thanks for the help! I've uploaded the above patch % some small cleanup here: https://dart-review.googlesource.com/c/sdk/+/249729. Obviously feel free to take ownership of that (your) CL. With this and the previous CL, the fuzzer test is passing, so this should be resolved once those CLs land.
