### ISSUE TITLE
`vm/dart/run_appended_aot_snapshot_test` failing on arm64-macos

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#49326]
There are new test failures on [these commits](https://github.com/dart-lang/sdk/compare/14796fafa867d6db4bf3bc8307c82e02fcb0d45f~...413f60a8b6b2898a5b77a527408f4620ef22b549).

The tests
```
vm/dart/run_appended_aot_snapshot_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-strong-mac-release-arm64
dartkp-weak-asserts-mac-release-arm64
```

From [log](https://dart-ci.appspot.com/log/vm-kernel-precomp-nnbd-mac-release-arm64/dartkp-weak-asserts-mac-release-arm64/1636/vm/dart/run_appended_aot_snapshot_test):
```

stdout:
Failed to add a linker signed signature, adding a regular signature instead.
Failed to replace the dartaotruntime signature, 
subcommand terminated with exit code 1.
Subcommand stderr:
/opt/s/w/ir/x/t/qQw243/test.exe: replacing existing signature
/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /opt/s/w/ir/x/t/qQw243/test.exe malformed object (offset field of section 0 in LC_SEGMENT command 1 not past the headers of the file)
/opt/s/w/ir/x/t/qQw243/test.exe: the codesign_allocate helper tool cannot be found or used

stderr:
Unhandled exception:
Could not sign the new executable
#0      writeAppendedMachOExecutable (package:dart2native/dart2native_macho.dart:382)
<asynchronous suspension>
#1      writeAppendedExecutable (package:dart2native/dart2native.dart:21)
<asynchronous suspension>
#2      main.<anonymous closure> (file:///opt/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart/run_appended_aot_snapshot_test.dart:53)
<asynchronous suspension>
#3      withTempDir (file:///opt/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart/snapshot_test_helper.dart:127)
<asynchronous suspension>
#4      main (file:///opt/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart/run_appended_aot_snapshot_test.dart:24)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartkp-weak-asserts-mac-release-arm64 vm/dart/run_appended_aot_snapshot_test
```

/cc @sstrickl could you take a look?

**Comment by mkustermann** [comment]
There were only null safety migration CLs in that range, except for a clang roll in https://github.com/dart-lang/sdk/commit/413f60a8b6b2898a5b77a527408f4620ef22b549. Could that have caused this?

**Comment by mkustermann** [comment]
There is seemingly also another test that exercises this, see [log]():
```
...

  Expected: <0>
    Actual: <64>
  stdout: Info: Compiling with sound null safety
  Failed to add a linker signed signature, adding a regular signature instead.
  Failed to replace the dartaotruntime signature, 
  subcommand terminated with exit code 1.
  Subcommand stderr:
  /opt/s/w/ir/x/t/executor_testF7gZY4/main.dart.dill: replacing existing signature
  /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /opt/s/w/ir/x/t/executor_testF7gZY4/main.dart.dill malformed object (offset field of section 0 in LC_SEGMENT command 1 not past the headers of the file)
  /opt/s/w/ir/x/t/executor_testF7gZY4/main.dart.dill: the codesign_allocate helper tool cannot be found or used
  
...
--- Re-run this test:
python3 tools/test.py -n unittest-asserts-release-mac-arm64 pkg/_fe_analyzer_shared/test/macros/executor/executor_test

```

**Comment by mkustermann** [comment]
Closing this in favor of https://github.com/dart-lang/sdk/issues/49275. Root cause is the clang roll indeed.
