### ISSUE TITLE
[analysis_server] workspace/didChangeWorkspaceFolders: Only absolute normalized paths are supported

### ISSUE THREAD

**Issue by sebthom** [dart-lang/sdk#49338]
**Dart SDK version: 2.17.5 (stable) (Tue Jun 21 11:05:10 2022 +0200) on "windows_x64"**

I am trying to integrate Dart Analysis Server with Eclipse utilizing the Eclipse [LSP4E](https://github.com/eclipse/lsp4e) project.

When opening a Dart file I am getting the following exception from the Dart LS:
```python
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: File is not being analyzed
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$3(LanguageServerWrapper.java:276)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: File is not being analyzed
	... 11 more
```
with root cause:
```dart
[Error]	An error occurred while handling workspace/didChangeWorkspaceFolders notification: Invalid argument(s): Only absolute normalized paths are supported: D:\dev\wks\dart-testproject\
#0      AnalysisContextCollectionImpl._throwIfNotAbsoluteNormalizedPath (package:analyzer/src/dart/analysis/analysis_context_collection.dart:124:7)
#1      AnalysisContextCollectionImpl._throwIfAnyNotAbsoluteNormalizedPath (package:analyzer/src/dart/analysis/analysis_context_collection.dart:115:7)
#2      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:51:5)
#3      ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded.performContextRebuild (package:analysis_server/src/context_manager.dart:449:40)
#4      ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded.performContextRebuild (package:analysis_server/src/context_manager.dart:444:41)
#5      ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded (package:analysis_server/src/context_manager.dart:562:17)
<asynchronous suspension>
#6      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:280:5)
<asynchronous suspension>
#7      LspAnalysisServer._refreshAnalysisRoots (package:analysis_server/src/lsp/lsp_analysis_server.dart:758:5)
<asynchronous suspension>
#8      LspAnalysisServer.updateWorkspaceFolders (package:analysis_server/src/lsp/lsp_analysis_server.dart:691:5)
<asynchronous suspension>
#9      WorkspaceFoldersHandler.handle (package:analysis_server/src/lsp/handlers/handler_change_workspace_folders.dart:40:5)
<asynchronous suspension>
#10     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:352:26)
<asynchronous suspension>
```

I think this issue is similar to https://github.com/dart-lang/sdk/issues/48234 where the same exception occured during `textDocument/didOpen` notifications which was fixed by https://github.com/dart-lang/sdk/commit/7a4c3c1c46b9d066b2a8051d349b91caf7d49c1b along with this comment:
```dart
// Normalise all potential workspace folder paths as these may contain
// trailing slashes (the LSP spec does not specific if folders
// should/should not have them) and the analysis roots must be normalized.
```

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
@sebthom thanks for the investigation! You were exactly right, that fix was only applying to workspace folders in the original initialize request. I've moved the normalisation to apply to all changes to workspace folders (during `initialize` or `didChangeWorkspaceFolders`):

https://dart-review.googlesource.com/c/sdk/+/250041/

**Comment by DanTup** [comment]
@sebthom I'm not involved in releases so can't say for certain, but my understanding is that the "patch" versions are used for hotfixes (which this won't make the bar for), so I would expect it to be in a 2.18 rather than a 2.17.x.

However if you just want a version for testing, you could get a dev build from https://dart.dev/get-dart/archive#dev-channel

Based on the tags at https://github.com/dart-lang/sdk/tags, v2.18.0-235.0.dev was tagged 5 hours ago so should include the fix. I wouldn't recommend using a dev build for production work, but it may be useful for your testing of the LSP integration.

**Comment by sebthom** [comment]
@DanTup thank you!!
