### ISSUE TITLE
Cannot access '$arguments' before initialization

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#49346]
This questionable code causes an exception when compiled with `dartdevc`:

```dart
void main() {
  printArguments(['a']);
}

void printArguments(List<String> arguments) {
  for (final arguments in arguments) {
    print(arguments);
  }
}
```

```
main.dart:6 Uncaught ReferenceError: Cannot access '$arguments' before initialization
    at Object.printArguments (main.dart:6:27)
    at main$ (main.dart:2:3)
    at main.dart.bootstrap.js:267:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (main.dart.bootstrap.js:266:32)
    at <anonymous>:1:8
    at Object.runMain (client.js:8817:21)
    at client.js:24565:19
    at _wrapJsFunctionForAsync_closure.$protected (client.js:3475:15)
    at _wrapJsFunctionForAsync_closure.call$2 (client.js:11585:12)
    at Object._asyncStartSync (client.js:3439:20)
    at main__closure4.$call$body$main__closure (client.js:24578:16)
    at main__closure4.call$1 (client.js:24504:19)
    at StaticClosure._rootRunUnary (client.js:3843:16)
    at _CustomZone.runUnary$2$2 (client.js:12991:39)
    at _CustomZone.runUnaryGuarded$1$2 (client.js:12938:14)
    at _ControllerSubscription._sendData$1 (client.js:12525:19)
    at _DelayedData.perform$1 (client.js:12707:59)
    at _PendingEvents_schedule_closure.call$0 (client.js:12756:14)
    at Object._microtaskLoop (client.js:3681:24)
    at StaticClosure._startMicrotaskLoop (client.js:3687:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (client.js:11461:9)
    at invokeClosure (client.js:1274:26)
    at MutationObserver.<anonymous> (client.js:1293:18)
```

I don't see this exception with `dart2js`.

```
Dart SDK version: 2.17.5 (stable) (Tue Jun 21 11:05:10 2022 +0200) on "macos_arm64"
```

**Comment by gustav3d** [comment]
I can replicate this on Flutter git master(Dart 2.18.0 (build 2.18.0-261.0.dev)) for dart2js but not the Linux desktop target.
