### ISSUE TITLE
The compiler crashed: NoSuchMethodError: The method 'dominates' was called on null.

### ISSUE THREAD

**Issue by Skyost** [dart-lang/sdk#49387]
Hey,

I'm trying to compile my project for web using `flutter build web`, but I encounter the following error.

```
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
../EscapeGameKit/lib/src/widgets/padlocks/dialogs.dart:29:16:
Internal Error: The compiler crashed when compiling this element.
  Future<void> tryUnlockViaDialog(BuildContext context, EscapeGame escapeGame) async {
               ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.17.5), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The method 'dominates' was called on null.
Receiver: null
Tried calling: dominates(Instance of 'HBasicBlock')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      HInstruction.dominates (package:compiler/src/ssa/nodes.dart:1382:44)
#2      SsaDeadCodeEliminator.cleanPhis.<anonymous closure> (package:compiler/src/ssa/optimize.dart:2694:25)
#3      HBasicBlock.forEachPhi (package:compiler/src/ssa/nodes.dart:998:8)
#4      SsaDeadCodeEliminator.cleanPhis (package:compiler/src/ssa/optimize.dart:2691:13)
#5      SsaDeadCodeEliminator.visitGraph (package:compiler/src/ssa/optimize.dart:2524:5)
#6      SsaOptimizerTask.optimize.runPhase.<anonymous closure> (package:compiler/src/ssa/optimize.dart:72:46)
#7      CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#8      SsaOptimizerTask.optimize.runPhase (package:compiler/src/ssa/optimize.dart:72:7)
#9      List.forEach (dart:core-patch/growable_array.dart:416:8)
#10     SsaOptimizerTask.optimize.<anonymous closure> (package:compiler/src/ssa/optimize.dart:135:14)
#11     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#12     SsaOptimizerTask.optimize (package:compiler/src/ssa/optimize.dart:92:5)
#13     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:85:15)
#14     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:453:30)
#15     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:317:43)
#16     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:457:29)
#17     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:699:70)
#18     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#19     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:699:32)
#20     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#21     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:697:28)
#22     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:143:15)
#23     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:695:18)
#24     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:256:12)
#25     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:272:5)
#26     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:691:16)
#27     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#28     Compiler.emptyQueue (package:compiler/src/compiler.dart:690:14)
#29     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:714:7)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#31     Compiler.processQueue (package:compiler/src/compiler.dart:708:14)
#32     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:484:5)
#33     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:648:23)
<asynchronous suspension>
#34     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:305:7)
<asynchronous suspension>
#35     Compiler.runInternal (package:compiler/src/compiler.dart:304:5)
<asynchronous suspension>
#36     main (package:compiler/src/dart2js.dart:1407:3)
<asynchronous suspension>



Compiling lib\main.dart for the Web...                             29,1s
Exception: Failed to compile application for the Web.
```

I don't understand because it compiles fine on Windows. Also, the app runs fine using `flutter run web` (only in debug mode, not in profile mode).

The error refers to the [following line](https://github.com/Skyost/EscapeGameKit/blob/master/lib/src/widgets/padlocks/dialogs.dart#L29) from my library `EscapeGameKit`. It occurs while compiling [this project](https://github.com/Skyost/VoyageAPastlard). 

<details>
<summary>Flutter doctor</summary>

```
Microsoft Windows [version 10.0.22000.778]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\Hugo>flutter doctor -v
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [version 10.0.22000.778], locale fr-FR)
    • Flutter version 3.0.4 at C:\Users\Hugo\AppData\Roaming\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (3 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Hugo\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: D:\Projets\Jetbrains IDEs\apps\AndroidStudio\ch-0\212.5712.43.2112.8609683\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Projets\Jetbrains IDEs\apps\AndroidStudio\ch-0\212.5712.43.2112.8609683
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.22000.778]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

Thanks for your help !

**Comment by fishythefish** [comment]
Thanks for filing an issue, @Skyost. I recently made a change to our SSA dead code elimination which fixes another bug: https://github.com/dart-lang/sdk/commit/edb0389996b5e64434560fa141b234588d2b44eb. Since you're running into an unexpected `null` on the code path I cleaned up, this might fix your issue as well. However, I don't think this change has rolled into Flutter yet.

**Comment by Skyost** [comment]
Thanks @fishythefish. I'll wait for Flutter to release a new version and will come back here to close the issue if it worked 😄👍

**Comment by rakudrama** [comment]
@Skyost FYI Flutter 3.3.2 was released just last week, 9/14/2022.
