### ISSUE TITLE
dartdev confused by non-existent flags prefixed with a single hypen

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#49437]
`dart -no-load-cse hello.dart` produces just `.` as its output with exit code 255.

This may have the same underlying cause as https://github.com/dart-lang/pub/issues/3458

With 
```
--- a/pkg/dartdev/lib/dartdev.dart
+++ b/pkg/dartdev/lib/dartdev.dart
@@ -69,6 +69,10 @@ Future<void> runDartdev(List<String> args, SendPort? port) async {
     // when it is in DartdevRunner.runCommand.
     io.stderr.writeln('$e');
     exitCode = 64;
+  } on dynamic catch (e, st) {
+    io.stderr.writeln('$e');
+    io.stderr.writeln('$st');
+    exitCode = 2;
```

I get a bit more informative trace,

```
LateInitializationError: Field 'log' has not been initialized.
#0      log (package:dartdev/src/core.dart)
#1      FixCommand.description (package:dartdev/src/commands/fix.dart:57:9)
#2      Command.summary (package:args/command_runner.dart:263:25)
#3      _getCommandUsage (package:args/command_runner.dart:484:43)
#4      CommandRunner._usageWithoutDescription (package:args/command_runner.dart:59:12)
#5      CommandRunner.usageException (package:args/command_runner.dart:102:37)
#6      CommandRunner.parse (package:args/command_runner.dart:130:35)
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:36)
#8      new Future.sync (dart:async/future.dart:302:31)
#9      CommandRunner.run (package:args/command_runner.dart:119:14)
#10     runDartdev (package:dartdev/dartdev.dart:66:29)
#11     main (file:///usr/local/google/home/rmacnak/dart2/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
but I don't understand when the log is supposed to be created.

@bkonyi

**Comment by bkonyi** [comment]
Ah, we're trying to use `log` as a receiver when creating the description for the `fix` command. We should just initialize this to a default at startup and then replace it with a verbose logger later once we parse the flags.
