### ISSUE TITLE
Can't catch SocketException from RawDatagramSocket

### ISSUE THREAD

**Issue by JosefWN** [dart-lang/sdk#49454]
When the internet connection is flaky/temporarily lost, the `RawDatagramSocket` throws a `SocketException` that can't be caught. I'm emulating this by binding the socket, then disconnecting my WiFi and finally sending something on the socket.

Of note:
- I'm not debugging using VS Code or such, just using the Dart CLI.
- The issue appears both with `dart run` and `dart compile`.
- I have only tested on macOS (desktop), not sure about other supported platforms.

Target OS: macOS Monterey (M1)
Dart SDK version: 2.17.5 (stable) (Tue Jun 21 11:05:10 2022 +0200) on "macos_arm64"

Complete example reproducing the issue:
```dart
import 'dart:async';
import 'dart:io';

Future<void> main() async {
  try {
    final socket = await RawDatagramSocket.bind(InternetAddress.anyIPv4, 12345);
    socket.handleError((e) => print('Handled error: $e'));
    receive(socket);

    final sendAddr = await InternetAddress.lookup('coap.me');
    print(
      'Socket bound on ${socket.address}, '
      'waiting 5 seconds for you to disconnect WiFi',
    );
    await Future.delayed(const Duration(seconds: 5));

    socket.send('Test'.codeUnits, sendAddr.first, 5683);
  } on SocketException catch (e) {
    print('Caught SocketException: $e');
  }
}

void receive(final RawDatagramSocket socket) {
  socket.listen((final e) {
    switch (e) {
      case RawSocketEvent.read:
        final d = socket.receive();
        if (d != null) {
          print(d);
        }
        break;
      case RawSocketEvent.closed:
      case RawSocketEvent.readClosed:
        socket.close();
        break;
      case RawSocketEvent.write:
        break;
    }
  });
}
```

Program output:
``` 
Socket bound on InternetAddress('0.0.0.0', IPv4), waiting 5 seconds for you to disconnect WiFi
Unhandled exception:
SocketException: Send failed (OS Error: Network is unreachable, errno = 51), address = 0.0.0.0, port = 12345
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1213:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2450:15)
#2      main (file:///Users/jn/Desktop/coap/example/sync_vs_async.dart:17:12)
<asynchronous suspension>
```

**Comment by lrhn** [comment]
The `socket.handleError((e) => print('Handled error: $e'));` creates a new stream which, when listened to, will listen to the `socket` stream.
It's never listened to, so effectively this line does nothing.

Try doing:
```dart
var errorSafeSocket = socket.handleError((e) => print('Handled error: $e'));
receive(errorSafeSocket); // which must expect a Stream, not a RawDatagramSocket.
```

Alternatively attach the error handler in the `listen` call of `receive`:
```dart
socket.listen((...) { ... },
  onError: (e, s) {
     print('Handled error in receive $e');
  });
```
