### ISSUE TITLE
Customer-reported issue with null safety migration tool: Couldn't apply migration

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#49500]
```
Couldn't apply migration
Error: {success: false, exception: Bad state: Cannot apply migration. Files on disk do not match the expected pre-migration state. Press the "rerun from sources" button and then try again. (Changed file path is /.../third_party/dart_src/angular/_tests/test/core/mock_like_directive_test.dart), stackTrace: #0      PreviewSite.performApply (package:nnbd_migration/src/preview/preview_site.dart:510:9)
#1      PreviewSite.handlePostRequest (package:nnbd_migration/src/preview/preview_site.dart:449:9)
<asynchronous suspension>
#2      HttpPreviewServer._handlePostRequest (package:nnbd_migration/src/preview/http_preview_server.dart:109:5)
<asynchronous suspension>
#3      HttpPreviewServer._handleServer.<anonymous closure> (package:nnbd_migration/src/preview/http_preview_server.dart:119:9)
<asynchronous suspension>
}
```

**What I was doing when this issue occurred**: I unselected this file to indicate that I did not want it migrated and made some local edits. Attempting to apply the migration to the remaining files fails because I edited this file, despite the fact I'm asking the tool not to touch it.

**Is it possible to work around this issue**: Yes, I can rerun the tool without this file listed as an input.

**Dart SDK version**: 2.19.462329229-edge+google3-v2

Stacktrace: _auto populated by migration preview tool._

```
{success: false, exception: Bad state: Cannot apply migration. Files on disk do not match the expected pre-migration state. Press the "rerun from sources" button and then try again. (Changed file path is /.../third_party/dart_src/angular/_tests/test/core/mock_like_directive_test.dart), stackTrace: #0      PreviewSite.performApply (package:nnbd_migration/src/preview/preview_site.dart:510:9)
#1      PreviewSite.handlePostRequest (package:nnbd_migration/src/preview/preview_site.dart:449:9)
<asynchronous suspension>
#2      HttpPreviewServer._handlePostRequest (package:nnbd_migration/src/preview/http_preview_server.dart:109:5)
<asynchronous suspension>
#3      HttpPreviewServer._handleServer.<anonymous closure> (package:nnbd_migration/src/preview/http_preview_server.dart:119:9)
<asynchronous suspension>
}
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
