### ISSUE TITLE
Rethrow expression missing determinitic nature?

### ISSUE THREAD

**Issue by kamal-github** [dart-lang/sdk#49593]
I am running the below code and the output order is not deterministic, Is there anything I should be aware of or is this a bug?

```dart
void main() {
  try {
    throw CustomException();
  } on CustomException catch (e) {
    print(e.toString());
    rethrow;
  } finally {
    print ('finally!');
  }
}

class CustomException implements Exception {}
```

#### Outputs

1) 
```
Instance of 'CustomException'
finally!
Unhandled exception:
Instance of 'CustomException'
#0      main (file:///redacted/main.dart:4:5)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

2) 
```
Unhandled exception:
Instance of 'CustomException'
#0      main (file:///redacted/main.dart:4:5)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
Instance of 'CustomException'
finally!
```

**Comment by mraleph** [comment]
Unhandled exception is printed into stderr and the rest into stdout hence the nondeterminism in how you see these two streams intermixed in the end.
