### ISSUE TITLE
Migration tool crashes when a library uses a non-function typedef from a migrated import

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#49690]
If there is a non-function type `typedef` in a migrated library, usage of the typedef in another library causes the migration tool to crash attempting to migrate the library.

If you checkout https://github.com/natebosch/dart_repro/tree/migration-tool-crash-typedef and attempt to `dart migrate` it will crash with

```
Migrating /usr/local/google/home/nbosch/repos/dart_repro

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[---------------------------------------------------------------------------------------------------------------------------------------\]
No analysis issues found.

Generating migration suggestions...
[----------------------------------                                                                                                      ]
Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.19.0-36.0.dev) in your bug report.

To attempt to perform migration anyway, you may re-run with --ignore-exceptions.

Exception details:

type 'Null' is not a subtype of type 'GenericFunctionTypeElement' in type cast at offset 34 in /usr/local/google/home/nbosch/repos/dart_repro/lib/bar.dart (D)

#0      EdgeBuilder.visitNamedType (package:nnbd_migration/src/edge_builder.dart:1458:36)
#1      NamedTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:8208:50)
#2      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2341:24)
#3      EdgeBuilder.visitVariableDeclarationList (package:nnbd_migration/src/edge_builder.dart:1985:5)
#4      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11702:15)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2341:24)
#6      EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1537:9)
#7      GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:135:48)
#8      GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:240:44)
#9      GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:207:7)
#10     GeneralizingAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:601:7)
#11     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11016:15)
#12     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2341:24)
#13     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1537:9)
#14     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:204:52)
#15     CompletenessTracker.visitCompilationUnit.<anonymous closure (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#16     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#17     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#18     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2317:50)
#19     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:223:12)
#20     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:162:16)
#21     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1088:20)
#22     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1020:26)
<asynchronous suspension>
#23     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1086:5)
<asynchronous suspension>
#24     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:695:24)
<asynchronous suspension>
#25     MigrateCommand.run (package:dartdev/src/commands/migrate.dart:37:7)
<asynchronous suspension>
#26     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#27     DartdevRunner.runCommand (package:dartdev/dartdev.dart:239:18)
<asynchronous suspension>
#28     runDartdev (package:dartdev/dartdev.dart:63:18)
<asynchronous suspension>
#29     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

**Comment by natebosch** [comment]
cc @stereotype441

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
