### ISSUE TITLE
Cannot use `@FfiNative` on both a setter and a getter.

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#49770]
e.g.

```dart
class Paint extends NativeFieldWrapperClass1 {
  @FfiNative<Bool Function(Pointer<Void>)>('Paint::getIsAntiAlias', isLeaf: true)
  external bool get isAntiAlias;
  @FfiNative<Void Function(Pointer<Void>, Bool)>('Paint::setIsAntiAlias', isLeaf: true)
  external set isAntiAlias(bool value);
}
```

results in 

```
Unhandled exception:
root::dart:ui::Paint::@fields::dart:ui::__isAntiAlias$FfiNative$Ptr is already bound to Reference to dart:ui::Paint::@fields::dart:ui::__isAntiAlias$FfiNative$Ptr with node Paint.__isAntiAlias$FfiNative$Ptr (Field:472664), trying to bind to Reference to Paint.__isAntiAlias$FfiNative$Ptr with node Paint.__isAntiAlias$FfiNative$Ptr (Field:472711)
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:237:7)
#1      Field.bindCanonicalNames (package:kernel/ast.dart:2208:36)
#2      Class.ensureCanonicalNames (package:kernel/ast.dart:1267:17)
#3      Library.ensureCanonicalNames (package:kernel/ast.dart:514:18)
#4      Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:13981:13)
#5      BinaryPrinter._computeCanonicalNames (package:kernel/binary/ast_to_binary.dart:557:19)
#6      BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:576:7)
#7      Timeline.timeSync (dart:developer/timeline.dart:160:22)
#8      BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:574:14)
#9      writeComponentToFile (package:front_end/src/fasta/kernel/utils.dart:95:13)
#10     compilePlatformInternal (file:///Users/dnfield/src/flutter/engine/src/third_party/dart/pkg/front_end/tool/_fasta/entry_points.dart:539:9)
<asynchronous suspension>
#11     compilePlatform (file:///Users/dnfield/src/flutter/engine/src/third_party/dart/pkg/front_end/tool/_fasta/entry_points.dart:510:3)
<asynchronous suspension>
#12     runProtectedFromAbort (file:///Users/dnfield/src/flutter/engine/src/third_party/dart/pkg/front_end/tool/_fasta/command_line.dart:412:12)
<asynchronous suspension>
#13     compilePlatformEntr
```

During compilation. I can work around this for now but it would be nice to be able to do this.

**Comment by dnfield** [comment]
@dcharkes fyi

**Comment by dcharkes** [comment]
Fix underway: https://dart-review.googlesource.com/c/sdk/+/255995

**Comment by dcharkes** [comment]
d099086c39f6b146f92312a484d56caf79c015fb
