### ISSUE TITLE
NoSuchMethodError: The getter 'iterator' was called on null.

### ISSUE THREAD

**Issue by shigomany** [dart-lang/sdk#49851]
When I run my project in **Debug** mode, all works fine, but in **Release** mode I getting error: 
```
NoSuchMethodError: The getter 'iterator' was called on null.
```

This tracker is for issues related to:

* Analyzer
* Dart VM
* dart2js
* Dart version: 2.18
* Flutter: 3.3.0

`flutter build web` logs:
```
💪 Building with sound null safety 💪

Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
The compiler crashed: NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      reportLocatedMessage (package:compiler/src/kernel/element_map_impl.dart:2135:37)
#2      KernelToElementMap.constantEvaluator.<anonymous closure> (package:compiler/src/kernel/element_map_impl.dart:850:7)
#3      ErrorReporter.report (package:compiler/src/ir/constants.dart:108:19)
#4      ConstantEvaluator.evaluate (package:front_end/src/fasta/kernel/constant_evaluator.dart:1084:25)
#5      Dart2jsConstantEvaluator.evaluate (package:compiler/src/ir/constants.dart:76:20)
#6      KernelToElementMap.getConstantValue (package:compiler/src/kernel/element_map_impl.dart:1136:46)
#7      ConstantCollector.add (package:compiler/src/deferred_load/entity_data_info.dart:469:10)
#8      ConstantCollector.visitTypeLiteral (package:compiler/src/deferred_load/entity_data_info.dart:546:45)
#9      TypeLiteral.accept (package:kernel/ast.dart:7760:44)
#10     visitList (package:kernel/ast.dart:13868:14)
#11     StringConcatenation.visitChildren (package:kernel/ast.dart:6793:5)
#12     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1492:10)
#13     Visitor.defaultTreeNode (package:kernel/visitor.dart:1092:39)
#14     TreeVisitor.defaultExpression (package:kernel/visitor.dart:190:43)
#15     TreeVisitor.visitStringConcatenation (package:kernel/visitor.dart:256:7)
#16     StringConcatenation.accept (package:kernel/ast.dart:6785:44)
#17     visitList (package:kernel/ast.dart:13868:14)
#18     Arguments.visitChildren (package:kernel/ast.dart:5127:5)
#19     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1492:10)
#20     Visitor.defaultTreeNode (package:kernel/visitor.dart:1092:39)
#21     TreeVisitor.visitArguments (package:kernel/visitor.dart:414:39)
#22     Arguments.accept (package:kernel/ast.dart:5119:38)
#23     ConstructorInvocation.visitChildren (package:kernel/ast.dart:6388:15)
#24     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1492:10)
#25     Visitor.defaultTreeNode (package:kernel/visitor.dart:1092:39)
#26     TreeVisitor.defaultExpression (package:kernel/visitor.dart:190:43)
#27     TreeVisitor.visitConstructorInvocation (package:kernel/visitor.dart:244:7)
#28     ConstantCollector.visitConstructorInvocation (package:compiler/src/deferred_load/entity_data_info.dart:526:13)
#29     ConstructorInvocation.accept (package:kernel/ast.dart:6379:44)
#30     Throw.visitChildren (package:kernel/ast.dart:7891:16)
#31     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1492:10)
#32     Visitor.defaultTreeNode (package:kernel/visitor.dart:1092:39)
#33     TreeVisitor.defaultExpression (package:kernel/visitor.dart:190:43)
#34     TreeVisitor.visitThrow (package:kernel/visitor.dart:280:31)
#35     Throw.accept (package:kernel/ast.dart:7884:44)
#36     ExpressionStatement.visitChildren (package:kernel/ast.dart:8837:16)
#37     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1492:10)
#38     Visitor.defaultTreeNode (package:kernel/visitor.dart:1092:39)
#39     TreeVisitor.defaultStatement (package:kernel/visitor.dart:324:41)
#40     TreeVisitor.visitExpressionStatement (package:kernel/visitor.dart:327:7)
#41     ExpressionStatement.accept (package:kernel/ast.dart:8829:43)
#42     visitList (package:kernel/ast.dart:13868:14)
#43     Block.visitChildren (package:kernel/ast.dart:8892:5)
#44     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1492:10)
#45     Visitor.defaultTreeNode (package:kernel/visitor.dart:1092:39)
#46     TreeVisitor.defaultStatement (package:kernel/visitor.dart:324:41)
#47     TreeVisitor.visitBlock (package:kernel/visitor.dart:329:31)
#48     Block.accept (package:kernel/ast.dart:8885:43)
#49     IfStatement.visitChildren (package:kernel/ast.dart:9798:10)
#50     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1492:10)
#51     Visitor.defaultTreeNode (package:kernel/visitor.dart:1092:39)
#52     TreeVisitor.defaultStatement (package:kernel/visitor.dart:324:41)
#53     TreeVisitor.visitIfStatement (package:kernel/visitor.dart:354:43)
#54     IfStatement.accept (package:kernel/ast.dart:9789:43)
#55     visitList (package:kernel/ast.dart:13868:14)
#56     Block.visitChildren (package:kernel/ast.dart:8892:5)
#57     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1492:10)
#58     Visitor.defaultTreeNode (package:kernel/visitor.dart:1092:39)
#59     TreeVisitor.defaultStatement (package:kernel/visitor.dart:324:41)
#60     TreeVisitor.visitBlock (package:kernel/visitor.dart:329:31)
#61     Block.accept (package:kernel/ast.dart:8885:43)
#62     FunctionNode.visitChildren (package:kernel/ast.dart:3858:11)
#63     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1492:10)
#64     Visitor.defaultTreeNode (package:kernel/visitor.dart:1092:39)
#65     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:413:45)
#66     FunctionNode.accept (package:kernel/ast.dart:3846:38)
#67     ConstantCollector.collect (package:compiler/src/deferred_load/entity_data_info.dart:464:20)
#68     EntityDataInfoBuilder.addDirectMemberDependencies (package:compiler/src/deferred_load/entity_data_info.dart:119:23)
#69     EntityDataInfoVisitor.visitClassEntityData.addLiveInstanceMember (package:compiler/src/deferred_load/entity_data_info.dart:278:19)
#70     KernelToElementMap._forEachLocalClassMember.<anonymous closure> (package:compiler/src/kernel/element_map_impl.dart:742:8)
#71     KClassEnvImpl.forEachMember.<anonymous closure> (package:compiler/src/kernel/env.dart:449:8)
#72     List.forEach (dart:core-patch/growable_array.dart:416:8)
#73     KClassEnvImpl.forEachMember (package:compiler/src/kernel/env.dart:448:14)
#74     KernelToElementMap._forEachLocalClassMember (package:compiler/src/kernel/element_map_impl.dart:741:9)
#75     KernelElementEnvironment.forEachLocalClassMember (package:compiler/src/kernel/element_map_impl.dart:1842:16)
#76     EntityDataInfoVisitor.visitClassEntityData (package:compiler/src/deferred_load/entity_data_info.dart:289:24)
#77     EntityDataInfoVisitor.visitMemberEntityData (package:compiler/src/deferred_load/entity_data_info.dart:325:7)
#78     MemberEntityData.accept (package:compiler/src/deferred_load/entity_data.dart:44:13)
#79     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:90:16)
#80     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#81     SetMixin.forEach (dart:collection/set.dart:142:39)
#82     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:102:29)
#83     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#84     SetMixin.forEach (dart:collection/set.dart:142:39)
#85     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:102:29)
#86     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#87     SetMixin.forEach (dart:collection/set.dart:142:39)
#88     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:102:29)
#89     SetMixin.forEach (dart:collection/set.dart:142:30)
#90     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:102:29)
#91     WorkQueue.processNextItem (package:compiler/src/deferred_load/work_queue.dart:67:11)
#92     AlgorithmState.initialize (package:compiler/src/deferred_load/algorithm_state.dart:139:13)
#93     new AlgorithmState.create (package:compiler/src/deferred_load/algorithm_state.dart:42:21)
#94     DeferredLoadTask._run.work (package:compiler/src/deferred_load/deferred_load.dart:440:39)
#95     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#96     DeferredLoadTask._run.<anonymous closure> (package:compiler/src/deferred_load/deferred_load.dart:444:53)
#97     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:143:15)
#98     DeferredLoadTask._run (package:compiler/src/deferred_load/deferred_load.dart:444:14)
#99     DeferredLoadTask.run.<anonymous closure> (package:compiler/src/deferred_load/deferred_load.dart:431:39)
#100    DurationMetric.measure (package:compiler/src/common/metrics.dart:74:22)
#101    DeferredLoadTask.run (package:compiler/src/deferred_load/deferred_load.dart:431:25)
#102    Compiler.closeResolution (package:compiler/src/compiler.dart:677:46)
#103    Compiler.computeClosedWorld (package:compiler/src/compiler.dart:377:9)
#104    Compiler.produceClosedWorld (package:compiler/src/compiler.dart:537:11)
#105    Compiler.runSequentialPhases (package:compiler/src/compiler.dart:634:15)
<asynchronous suspension>
#106    Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:305:7)
<asynchronous suspension>
#107    Compiler.runInternal (package:compiler/src/compiler.dart:304:5)
<asynchronous suspension>
#108    main (package:compiler/src/dart2js.dart:1407:3)
<asynchronous suspension>



Compiling lib/main.dart for the Web...                             14,3s
Exception: Failed to compile application for the Web.
```

If you aren't sure, file the issue here and we'll find the right home for it.
In your issue, please include:

* Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "macos_arm64"
* macOS Monterey: 12.5.1 (21G83), Apple M1 Pro

**Comment by shigomany** [comment]
`flutter build web --verbose` logs:
[log.txt](https://github.com/dart-lang/sdk/files/9444389/log.txt)

**Comment by paviln** [comment]
+1

**Comment by ragingsquirrel3** [comment]
+1

**Comment by HuiSF** [comment]
+1

**Comment by dnys1** [comment]
Some more context, although I haven't been able to reproduce it yet outside of my build environment. The output below uses flutter `master`. The same error occurs on `stable`, although the source location is not printed (as seen in OP) and the stack trace is a bit different.

```
$ fvm flutter build web

Compiling lib/main.dart for the Web...                          
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
../../../smithy/smithy/lib/src/serialization/stream_serializer.dart:50:31:
Error: Type variables can't be used as constants.
  Iterable<Type> get types => [Stream<T>];
                              ^
```

The error points to a line which is creating a type variable at runtime (not a constant). What's interesting is that the same issue is not reproducible with any `dart compile` commands _unless_ I change the body to `const [Stream<T>]` where I get the expected error.

The error occurs running `flutter build` for any target platform; however `flutter run` commands work fine. 

<details>
<summary>Full Error (master)</summary>

```
Compiling lib/main.dart for the Web...                          
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
../../../smithy/smithy/lib/src/serialization/stream_serializer.dart:50:31:
Error: Type variables can't be used as constants.
  Iterable<Type> get types => [Stream<T>];
                                                       ^
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.19.0-291.0.dev), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Unsupported operation: Unexpected unevaluated constant UnevaluatedConstant(unevaluated{<invalid:Type variables can't be used as constants.>}).
#0      ConstantValuefier.visitUnevaluatedConstant (package:compiler/src/ir/visitors.dart:238:5)
#1      _ConstantCallbackVisitor.visitUnevaluatedConstant (package:kernel/visitor.dart:903:17)
#2      UnevaluatedConstant.accept (package:kernel/ast.dart:14266:42)
#3      ComputeOnceConstantVisitor.visitConstant (package:kernel/visitor.dart:991:52)
#4      KernelToElementMap.getConstantValue (package:compiler/src/kernel/element_map_impl.dart:1210:48)
#5      ConstantCollector.add (package:compiler/src/deferred_load/entity_data_info.dart:476:42)
#6      ConstantCollector.visitTypeLiteral (package:compiler/src/deferred_load/entity_data_info.dart:555:45)
#7      TypeLiteral.accept (package:kernel/ast.dart:8133:44)
#8      visitList (package:kernel/ast.dart:14607:14)
#9      ListLiteral.visitChildren (package:kernel/ast.dart:8328:5)
#10     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560:10)
#11     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150:39)
#12     TreeVisitor.defaultExpression (package:kernel/visitor.dart:199:43)
#13     TreeVisitor.visitListLiteral (package:kernel/visitor.dart:300:43)
#14     ConstantCollector.visitListLiteral (package:compiler/src/deferred_load/entity_data_info.dart:508:13)
#15     ListLiteral.accept (package:kernel/ast.dart:8319:44)
#16     ConstantCollector.visitVariableDeclaration (package:compiler/src/deferred_load/entity_data_info.dart:550:23)
#17     VariableDeclaration.accept (package:kernel/ast.dart:10943:43)
#18     visitList (package:kernel/ast.dart:14607:14)
#19     Block.visitChildren (package:kernel/ast.dart:9362:5)
#20     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560:10)
#21     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150:39)
#22     TreeVisitor.defaultStatement (package:kernel/visitor.dart:348:41)
#23     TreeVisitor.visitBlock (package:kernel/visitor.dart:353:31)
#24     Block.accept (package:kernel/ast.dart:9355:43)
#25     IfStatement.visitChildren (package:kernel/ast.dart:10302:10)
#26     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560:10)
#27     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150:39)
#28     TreeVisitor.defaultStatement (package:kernel/visitor.dart:348:41)
#29     TreeVisitor.visitIfStatement (package:kernel/visitor.dart:378:43)
#30     IfStatement.accept (package:kernel/ast.dart:10293:43)
#31     visitList (package:kernel/ast.dart:14607:14)
#32     Block.visitChildren (package:kernel/ast.dart:9362:5)
#33     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560:10)
#34     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150:39)
#35     TreeVisitor.defaultStatement (package:kernel/visitor.dart:348:41)
#36     TreeVisitor.visitBlock (package:kernel/visitor.dart:353:31)
#37     Block.accept (package:kernel/ast.dart:9355:43)
#38     FunctionNode.visitChildren (package:kernel/ast.dart:3852:11)
#39     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560:10)
#40     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150:39)
#41     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:437:45)
#42     FunctionNode.accept (package:kernel/ast.dart:3839:38)
#43     ConstantCollector.collect (package:compiler/src/deferred_load/entity_data_info.dart:472:20)
#44     EntityDataInfoBuilder.addDirectMemberDependencies (package:compiler/src/deferred_load/entity_data_info.dart:124:23)
#45     EntityDataInfoVisitor.visitClassEntityData.addLiveInstanceMember (package:compiler/src/deferred_load/entity_data_info.dart:278:19)
#46     KernelToElementMap._forEachLocalClassMember.<anonymous closure> (package:compiler/src/kernel/element_map_impl.dart:792:8)
#47     KClassEnvImpl.forEachMember.<anonymous closure> (package:compiler/src/kernel/env.dart:412:8)
#48     List.forEach (dart:core-patch/growable_array.dart:416:8)
#49     KClassEnvImpl.forEachMember (package:compiler/src/kernel/env.dart:411:15)
#50     KernelToElementMap._forEachLocalClassMember (package:compiler/src/kernel/element_map_impl.dart:791:9)
#51     KernelElementEnvironment.forEachLocalClassMember (package:compiler/src/kernel/element_map_impl.dart:1959:16)
#52     EntityDataInfoVisitor.visitClassEntityData (package:compiler/src/deferred_load/entity_data_info.dart:289:24)
#53     EntityDataInfoVisitor.visitMemberEntityData (package:compiler/src/deferred_load/entity_data_info.dart:325:7)
#54     MemberEntityData.accept (package:compiler/src/deferred_load/entity_data.dart:44:13)
#55     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:95:16)
#56     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#57     SetMixin.forEach (dart:collection/set.dart:142:39)
#58     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#59     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#60     SetMixin.forEach (dart:collection/set.dart:142:39)
#61     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#62     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#63     SetMixin.forEach (dart:collection/set.dart:142:39)
#64     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#65     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#66     SetMixin.forEach (dart:collection/set.dart:142:39)
#67     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#68     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#69     SetMixin.forEach (dart:collection/set.dart:142:39)
#70     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#71     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#72     SetMixin.forEach (dart:collection/set.dart:142:39)
#73     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#74     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#75     SetMixin.forEach (dart:collection/set.dart:142:39)
#76     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#77     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#78     SetMixin.forEach (dart:collection/set.dart:142:39)
#79     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#80     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#81     SetMixin.forEach (dart:collection/set.dart:142:39)
#82     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#83     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#84     SetMixin.forEach (dart:collection/set.dart:142:39)
#85     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#86     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#87     SetMixin.forEach (dart:collection/set.dart:142:39)
#88     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#89     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#90     SetMixin.forEach (dart:collection/set.dart:142:39)
#91     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#92     SetMixin.forEach (dart:collection/set.dart:142:30)
#93     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:107:29)
#94     WorkQueue.processNextItem (package:compiler/src/deferred_load/work_queue.dart:67:11)
#95     AlgorithmState.initialize (package:compiler/src/deferred_load/algorithm_state.dart:144:13)
#96     new AlgorithmState.create (package:compiler/src/deferred_load/algorithm_state.dart:47:21)
#97     DeferredLoadTask._run.work (package:compiler/src/deferred_load/deferred_load.dart:448:39)
#98     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#99     DeferredLoadTask._run.<anonymous closure> (package:compiler/src/deferred_load/deferred_load.dart:452:53)
#100    DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#101    DeferredLoadTask._run (package:compiler/src/deferred_load/deferred_load.dart:452:14)
#102    DeferredLoadTask.run.<anonymous closure> (package:compiler/src/deferred_load/deferred_load.dart:439:39)
#103    DurationMetric.measure (package:compiler/src/common/metrics.dart:74:22)
#104    DeferredLoadTask.run (package:compiler/src/deferred_load/deferred_load.dart:439:25)
#105    Compiler.closeResolution (package:compiler/src/compiler.dart:767:46)
#106    Compiler.computeClosedWorld (package:compiler/src/compiler.dart:405:9)
#107    Compiler.produceClosedWorld (package:compiler/src/compiler.dart:592:11)
#108    Compiler.runSequentialPhases (package:compiler/src/compiler.dart:714:15)
<asynchronous suspension>
#109    Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:336:7)
<asynchronous suspension>
#110    Compiler.runInternal (package:compiler/src/compiler.dart:335:5)
<asynchronous suspension>
#111    Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:256:11)
<asynchronous suspension>
#112    main (package:compiler/src/dart2js.dart:1424:3)
<asynchronous suspension>


   41.3s
Exception: Failed to compile application for the Web.
```

</details>

<details>
<summary>Full Error (stable)</summary>

```
💪 Building with sound null safety 💪

Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.18.2), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      reportLocatedMessage (package:compiler/src/kernel/element_map_impl.dart:2225:37)
#2      KernelToElementMap.constantEvaluator.<anonymous closure> (package:compiler/src/kernel/element_map_impl.dart:883:7)
#3      ErrorReporter.report (package:compiler/src/ir/constants.dart:118:19)
#4      ConstantEvaluator.evaluate (package:front_end/src/fasta/kernel/constant_evaluator.dart:1082:25)
#5      Dart2jsConstantEvaluator.evaluateOrNull (package:compiler/src/ir/constants.dart:86:20)
#6      KernelToElementMap.getConstantValue (package:compiler/src/kernel/element_map_impl.dart:1169:46)
#7      ConstantCollector.add (package:compiler/src/deferred_load/entity_data_info.dart:468:10)
#8      ConstantCollector.visitTypeLiteral (package:compiler/src/deferred_load/entity_data_info.dart:545:45)
#9      TypeLiteral.accept (package:kernel/ast.dart:8120:44)
#10     visitList (package:kernel/ast.dart:14229:14)
#11     ListLiteral.visitChildren (package:kernel/ast.dart:8315:5)
#12     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1519:10)
#13     Visitor.defaultTreeNode (package:kernel/visitor.dart:1119:39)
#14     TreeVisitor.defaultExpression (package:kernel/visitor.dart:196:43)
#15     TreeVisitor.visitListLiteral (package:kernel/visitor.dart:297:43)
#16     ConstantCollector.visitListLiteral (package:compiler/src/deferred_load/entity_data_info.dart:498:13)
#17     ListLiteral.accept (package:kernel/ast.dart:8306:44)
#18     ReturnStatement.visitChildren (package:kernel/ast.dart:10246:17)
#19     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1519:10)
#20     Visitor.defaultTreeNode (package:kernel/visitor.dart:1119:39)
#21     TreeVisitor.defaultStatement (package:kernel/visitor.dart:339:41)
#22     TreeVisitor.visitReturnStatement (package:kernel/visitor.dart:371:51)
#23     ReturnStatement.accept (package:kernel/ast.dart:10238:43)
#24     FunctionNode.visitChildren (package:kernel/ast.dart:3909:11)
#25     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1519:10)
#26     Visitor.defaultTreeNode (package:kernel/visitor.dart:1119:39)
#27     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:428:45)
#28     FunctionNode.accept (package:kernel/ast.dart:3896:38)
#29     ConstantCollector.collect (package:compiler/src/deferred_load/entity_data_info.dart:463:20)
#30     EntityDataInfoBuilder.addDirectMemberDependencies (package:compiler/src/deferred_load/entity_data_info.dart:121:23)
#31     EntityDataInfoVisitor.visitClassEntityData.addLiveInstanceMember (package:compiler/src/deferred_load/entity_data_info.dart:277:19)
#32     KernelToElementMap._forEachLocalClassMember.<anonymous closure> (package:compiler/src/kernel/element_map_impl.dart:772:8)
#33     KClassEnvImpl.forEachMember.<anonymous closure> (package:compiler/src/kernel/env.dart:452:8)
#34     List.forEach (dart:core-patch/growable_array.dart:416:8)
#35     KClassEnvImpl.forEachMember (package:compiler/src/kernel/env.dart:451:14)
#36     KernelToElementMap._forEachLocalClassMember (package:compiler/src/kernel/element_map_impl.dart:771:9)
#37     KernelElementEnvironment.forEachLocalClassMember (package:compiler/src/kernel/element_map_impl.dart:1918:16)
#38     EntityDataInfoVisitor.visitClassEntityData (package:compiler/src/deferred_load/entity_data_info.dart:288:24)
#39     EntityDataInfoVisitor.visitMemberEntityData (package:compiler/src/deferred_load/entity_data_info.dart:324:7)
#40     MemberEntityData.accept (package:compiler/src/deferred_load/entity_data.dart:44:13)
#41     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:92:16)
#42     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#43     SetMixin.forEach (dart:collection/set.dart:142:39)
#44     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#45     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#46     SetMixin.forEach (dart:collection/set.dart:142:39)
#47     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#48     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#49     SetMixin.forEach (dart:collection/set.dart:142:39)
#50     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#51     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#52     SetMixin.forEach (dart:collection/set.dart:142:39)
#53     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#54     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#55     SetMixin.forEach (dart:collection/set.dart:142:39)
#56     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#57     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#58     SetMixin.forEach (dart:collection/set.dart:142:39)
#59     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#60     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#61     SetMixin.forEach (dart:collection/set.dart:142:39)
#62     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#63     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#64     SetMixin.forEach (dart:collection/set.dart:142:39)
#65     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#66     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#67     SetMixin.forEach (dart:collection/set.dart:142:39)
#68     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#69     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#70     SetMixin.forEach (dart:collection/set.dart:142:39)
#71     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#72     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#73     SetMixin.forEach (dart:collection/set.dart:142:39)
#74     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#75     _CompactIterator.current (dart:collection-patch/compact_hash.dart)
#76     SetMixin.forEach (dart:collection/set.dart:142:39)
#77     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#78     SetMixin.forEach (dart:collection/set.dart:142:30)
#79     AlgorithmState.processEntity (package:compiler/src/deferred_load/algorithm_state.dart:104:29)
#80     WorkQueue.processNextItem (package:compiler/src/deferred_load/work_queue.dart:69:11)
#81     AlgorithmState.initialize (package:compiler/src/deferred_load/algorithm_state.dart:141:13)
#82     new AlgorithmState.create (package:compiler/src/deferred_load/algorithm_state.dart:44:21)
#83     DeferredLoadTask._run.work (package:compiler/src/deferred_load/deferred_load.dart:443:39)
#84     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#85     DeferredLoadTask._run.<anonymous closure> (package:compiler/src/deferred_load/deferred_load.dart:447:53)
#86     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#87     DeferredLoadTask._run (package:compiler/src/deferred_load/deferred_load.dart:447:14)
#88     DeferredLoadTask.run.<anonymous closure> (package:compiler/src/deferred_load/deferred_load.dart:434:39)
#89     DurationMetric.measure (package:compiler/src/common/metrics.dart:74:22)
#90     DeferredLoadTask.run (package:compiler/src/deferred_load/deferred_load.dart:434:25)
#91     Compiler.closeResolution (package:compiler/src/compiler.dart:718:46)
#92     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:378:9)
#93     Compiler.produceClosedWorld (package:compiler/src/compiler.dart:553:11)
#94     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:670:15)
<asynchronous suspension>
#95     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:309:7)
<asynchronous suspension>
#96     Compiler.runInternal (package:compiler/src/compiler.dart:308:5)
<asynchronous suspension>
#97     main (package:compiler/src/dart2js.dart:1424:3)
<asynchronous suspension>



Compiling lib/main.dart for the Web...                             25.0s
Exception: Failed to compile application for the Web.
```

</details>

**Comment by sigmundch** [comment]
Thank you all for the bug report, and thanks @dnys1 for the example repro scenario, that made it much easier to investigate.

Fix underway in https://dart-review.googlesource.com/c/sdk/+/264884
