### ISSUE TITLE
MV3 Chrome Extension has a runtime error with DDC but not dart2js

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#49869]
If I compile a Chrome extension using [Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/) with DDC, the extension fails to load in Chrome with a runtime error (see below). If I compile it with Dart2Js, it loads successfully. Similarly, if I switch it to using Manifest V2, it loads successfully for both dart2js and DDC. 

```
Uncaught Error: importScripts failed for chrome-extension://pebbhcjfokadbgbnlmogdkkaahmamnap/background.dart.bootstrap.js at chrome-extension://pebbhcjfokadbgbnlmogdkkaahmamnap/background.dart.bootstrap.js
http://requirejs.org/docs/errors.html#importscripts
    at makeError (require.js:168:17)
    at Function.load (require.js:1984:33)
    at Object.load (require.js:1685:21)
    at Module.load (require.js:834:29)
    at Module.fetch (require.js:824:66)
    at Module.check (require.js:856:30)
    at Module.enable (require.js:1176:22)
    at Object.enable (require.js:1557:39)
    at Module.<anonymous> (require.js:1161:33)
    at require.js:134:23
```

Please see this minimal example: https://github.com/elliette/dart-example-extension. Instructions on how to reproduce are in the README.

**Comment by elliette** [comment]
@nshahan helped me figure this one out. Requires adding the bootstrap file to the manifest's `web_accessible_resources`:

```
        "web_accessible_resources": [
            {
                "matches": [
                    "<all_urls>"
                ],
                "resources": [
                    "background.dart.bootstrap.js"
                ]
            }
        ]
```
