### ISSUE TITLE
DFE pollutes stdout

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#49881]
```
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --snapshot=/b/s/w/ir/out/DebugX64/generated_compilations/app_jitk-linux-debug-x64/tests_standalone_2_io_unix_socket_test/out.jitsnapshot --snapshot-kind=app-jit -Dtest_runner.configuration=app_jitk-linux-debug-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/standalone_2/io/unix_socket_test.dart

exit code:
255

stdout:
Info: Compiling without sound null safety
server started a socket Instance of '_RawSocket'
client sent a message
client sent a message without control data
server received message Instance of 'SocketMessage'
server received messageData Hello
server has written to the Instance of '_RandomAccessFile' file
server received message Instance of 'SocketMessage'
server received messageData EmptyMessage
server socket got readClosed
server started a socket Instance of '_RawSocket'
client sent a message
server received message Instance of 'SocketMessage'
messageData: H
server received message Instance of 'SocketMessage'
messageData: i
server socket got readClosed
server started a socket Instance of '_RawSocket'
stdout:>Info: Compiling without sound null safety
<
stdout:>client sent a message<
stdout:>
<
stderr:>client wrote to stderr<
stderr:>
<
stdout:>Hello, server!
<
stderr:>Hello, server too!
<

stderr:
Unhandled exception:
Expect.fail('Unexpected exception Expect.equals(at index 0: Expected <client sent a message\x0AHello, server!\x0A...>, Found: <Info: Compiling without sound null safety\x0Aclient sent a message\x0AHello, server!\x0A...>) fails. is thrown')
#0      Expect._fail (package:expect/expect.dart:698:5)
#1      Expect.fail (package:expect/expect.dart:280:5)
#2      main.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/unix_socket_test.dart:972:14)
#3      _RootZone.runBinary (dart:async/zone.dart:1665:54)
#4      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1775:18)
#5      _Zone._processUncaughtError (dart:async/zone.dart:1080:14)
#6      _ZoneDelegate.handleUncaughtError (dart:async/zone.dart:944:23)
#7      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1778:16)
#8      _Zone._processUncaughtError (dart:async/zone.dart:1080:14)
#9      _CustomZone.handleUncaughtError (dart:async/zone.dart:1284:5)
#10     Future._propagateToListeners (dart:async/future_impl.dart:717:16)
#11     Future._completeError (dart:async/future_impl.dart:575:5)
#12     _rootRunBinary (dart:async/zone.dart:1422:47)
#13     _CustomZone.runBinary (dart:async/zone.dart:1314:19)
#14     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
#15     Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#16     Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#17     Future._completeError (dart:async/future_impl.dart:575:5)
#18     _rootRunUnary (dart:async/zone.dart:1406:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n app_jitk-linux-debug-x64 standalone_2/io/unix_socket_test
```

Diagnostic output should go to stderr, not stdout, so that program used in pipelining can enable diagnostics without breaking. Cf. https://github.com/dart-lang/sdk/issues/32134

**Comment by johnniwinther** [comment]
I think the diagnostics output is sent to stdout in the kernel service.

**Comment by a-siva** [comment]
CL in progress https://dart-review.googlesource.com/c/sdk/+/268102

**Comment by a-siva** [comment]
Landed https://dart-review.googlesource.com/c/sdk/+/268102
