### ISSUE TITLE
I use `Process.start` to run a python exe from `pyinstaller`, when the python exe print Chinese string, cause `UnicodeEncodeError: \'charmap\' codec can't encode characters in position 0-1: character maps to <undefined>`

### ISSUE THREAD

**Issue by KuiyuanFu** [dart-lang/sdk#49890]
I use `Process.start` to run a python exe from `pyinstaller`, when the python exe print Chinese string, cause `UnicodeEncodeError: \'charmap\' codec can't encode characters in position 0-1: character maps to <undefined>`

I have tried to run `python p.py` and `p.exe` in the command line, and the output is right. 

But in dart vm, `p.exe` is crashed.

`Dart SDK version: 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "windows_x64"`

The test python exe :
```
# pyinstaller p.py -F -n p
# mv dist/p.exe .-force
import sys
if __name__ == '__main__':
    print('English')
    print(r'中文')
    sys.exit(0)
```

The dart project:
```
import 'dart:convert';
import 'dart:io';

void main(List<String> arguments) async {
  final process = await Process.start(
    'p',
    [],
  );

  process.stderr.transform(utf8.decoder).forEach((output) {
    print(output.trim());
  });

  process.stdout.transform(utf8.decoder).forEach((output) {
    print(output.trim());
  });

  await process.exitCode;
}

```

output:
```
[34800] Failed to execute script 'p' due to unhandled exception!

Traceback (most recent call last):

  File "p.py", line 6, in <module>

    print(r'\u4e2d\u6587')

  File "encodings\cp1252.py", line 19, in encode

UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>
English
Exited

```

```
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.1889], locale zh-CN)
    • Flutter version 3.3.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\fukui\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.71.0)
    • VS Code at C:\Users\fukui\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.70

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by KuiyuanFu** [comment]
I found the solution in more than 24 hours, the python `sys.stdout.encoding` is `utf-8` in powershell and cmd.
But it is `cp1252` when I use `Process.start` to start a python program.
Using `sys.stdout.reconfigure(encoding='utf-8')` to set python output encoding to 'utf-8' will solve this problem.

**Comment by ismanong** [comment]
> I found the solution in more than 24 hours, the python `sys.stdout.encoding` is `utf-8` in powershell and cmd. But it is `cp1252` when I use `Process.start` to start a python program. Using `sys.stdout.reconfigure(encoding='utf-8')` to set python output encoding to 'utf-8' will solve this problem.

A perfect solution to the problem of Python outputting Chinese language.
Thanks for your patience in finding a solution.

**Comment by ZiangGithub** [comment]
> > I found the solution in more than 24 hours, the python `sys.stdout.encoding` is `utf-8` in powershell and cmd. But it is `cp1252` when I use `Process.start` to start a python program. Using `sys.stdout.reconfigure(encoding='utf-8')` to set python output encoding to 'utf-8' will solve this problem.
> 
> A perfect solution to the problem of Python outputting Chinese language. Thanks for your patience in finding a solution.

thanks a lot ! Solved my problem:  I use pyinstaller to package python script where I print a string which is encoded by GBK, but the console gives me wrong display.
