### ISSUE TITLE
[dart2wasm] SDK benchmark failures

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#49891]
<details>

<summary>Script to build and run benchmarks</summary>

```bash
#!/bin/bash

BENCHMARKS=(
    "benchmarks/AsyncLiveVars/dart/AsyncLiveVars.dart"
    "benchmarks/BigIntParsePrint/dart/BigIntParsePrint.dart"
    "benchmarks/Calls/dart/Calls.dart"
    "benchmarks/Dynamic/dart/Dynamic.dart"
    "benchmarks/Example/dart/Example.dart"
    "benchmarks/InstantiateTypeArgs/dart/InstantiateTypeArgs.dart"
    "benchmarks/Iterators/dart/Iterators.dart"
    "benchmarks/ListCopy/dart/ListCopy.dart"
    "benchmarks/MapCopy/dart/MapCopy.dart"
    "benchmarks/MapLookup/dart/MapLookup.dart"
    "benchmarks/MD5/dart/md5.dart"
    "benchmarks/ObjectHash/dart/ObjectHash.dart"
    "benchmarks/Omnibus/dart/Omnibus.dart"
    "benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart"
    "benchmarks/Richards/dart/Richards.dart"
    "benchmarks/RuntimeType/dart/RuntimeType.dart"
    "benchmarks/SHA1/dart/sha1.dart"
    "benchmarks/SHA256/dart/sha256.dart"
    "benchmarks/SkeletalAnimation/dart/SkeletalAnimation.dart"
    "benchmarks/SkeletalAnimationSIMD/dart/SkeletalAnimationSIMD.dart"
    "benchmarks/SoundSplayTreeSieve/dart/SoundSplayTreeSieve.dart"
    "benchmarks/StringPool/dart/StringPool.dart"
    "benchmarks/StringPool/dart/StringPool100.dart"
    "benchmarks/TypedDataDuplicate/dart/TypedDataDuplicate.dart"
    "benchmarks/TypeLiteral/dart/TypeLiteral.dart"
    "benchmarks/Utf8Decode/dart/Utf8Decode.dart"
    "benchmarks/Utf8Encode/dart/Utf8Encode.dart"
)

COMPILE_FAILURES=()

for file in ${BENCHMARKS[*]}; do
    echo "Compiling $file ..."
    basename="$(basename -- $file)"
    if ! (sdk/bin/dart2wasm $file $basename.wasm >/dev/null 2>&1); then
        COMPILE_FAILURES+=($file)
        # echo "Failed to compile $basename"
    fi
done

echo ''
echo 'Compile failures:'
echo ''

for file in ${COMPILE_FAILURES[*]}; do
    echo $file
done

echo ''
echo ''
echo ''

RUN_FAILURES=()

for file in *.wasm; do
    echo "Running $file ..."
    if ! (./third_party/d8/linux/d8 --experimental-wasm-gc --wasm-gc-js-interop --experimental-wasm-stack-switching --experimental-wasm-type-reflection pkg/dart2wasm/bin/run_wasm.js -- $file); then
        RUN_FAILURES+=($file)
    fi
done

echo ''
echo 'Run failures:'
echo ''

for file in ${RUN_FAILURES[*]}; do
    echo $file
done
```

</details>

(I will be adding error messages)

## Compile time dart2wasm crashes

- <details>

  <summary>benchmarks/Dynamic/dart/Dynamic.dart</summary>

  ```
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:306:19
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:307:19
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:161:23
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:166:25
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:898:20
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:902:20
  Unhandled exception:
  Not supported: Optional parameters for function expression or local function at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/Dynamic/dart/Dynamic.dart:87:23
  #0      CaptureFinder._visitLambda (package:dart2wasm/closures.dart:265)
  #1      CaptureFinder.visitFunctionExpression (package:dart2wasm/closures.dart:284)
  #2      FunctionExpression.accept (package:kernel/ast.dart:8831)
  #3      Field.visitChildren (package:kernel/ast.dart:2363)
  #4      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560)
  #5      Visitor.defaultTreeNode (package:kernel/visitor.dart:1150)
  #6      TreeVisitor.defaultMember (package:kernel/visitor.dart:396)
  #7      TreeVisitor.visitField (package:kernel/visitor.dart:402)
  #8      Field.accept (package:kernel/ast.dart:2349)
  #9      Closures.findCaptures (package:dart2wasm/closures.dart:120)
  #10     CodeGenerator.generateStaticFieldInitializer (package:dart2wasm/code_generator.dart:196)
  #11     CodeGenerator.generate (package:dart2wasm/code_generator.dart:154)
  #12     Translator.translate (package:dart2wasm/translator.dart:434)
  #13     compileToModule (package:dart2wasm/compile.dart:85)
  <asynchronous suspension>
  #14     main (file:///usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/dart2wasm.dart:114)
  <asynchronous suspension>
  ```

  </details>

- ~benchmarks/EventLoopLatencyJson/dart/EventLoopLatencyJson.dart~
- ~benchmarks/EventLoopLatencyJson350KB/dart/EventLoopLatencyJson350KB.dart~
- ~benchmarks/EventLoopLatencyRegexp/dart/EventLoopLatencyRegexp.dart~
- ~benchmarks/FfiAsTypedList/dart/FfiAsTypedList.dart~
- ~benchmarks/FfiBoringssl/dart/FfiBoringssl.dart~
- ~benchmarks/FfiCall/dart/FfiCall.dart~
- ~benchmarks/FfiMemory/dart/FfiMemory.dart~
- ~benchmarks/FfiStruct/dart/FfiStruct.dart~
- ~benchmarks/IsolateSendExitLatency/dart/IsolateSendExitLatency.dart~
- ~benchmarks/IsolateSpawn/dart/IsolateSpawn.dart~
- ~benchmarks/IsolateSpawnMemory/dart/IsolateSpawnMemory.dart~

- <details>

  <summary>benchmarks/MapCopy/dart/MapCopy.dart</summary>

  ```
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:306:19
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:307:19
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:161:23
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:166:25
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:898:20
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:902:20
  Unhandled exception:
  Not supported: Type parameters for function expression or local function at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/MapCopy/dart/MapCopy.dart:310:36
  #0      CaptureFinder._visitLambda (package:dart2wasm/closures.dart:269)
  #1      CaptureFinder.visitFunctionDeclaration (package:dart2wasm/closures.dart:291)
  #2      FunctionDeclaration.accept (package:kernel/ast.dart:11077)
  #3      visitList (package:kernel/ast.dart:14626)
  #4      Block.visitChildren (package:kernel/ast.dart:9443)
  #5      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560)
  #6      Visitor.defaultTreeNode (package:kernel/visitor.dart:1150)
  #7      TreeVisitor.defaultStatement (package:kernel/visitor.dart:348)
  #8      TreeVisitor.visitBlock (package:kernel/visitor.dart:353)
  #9      Block.accept (package:kernel/ast.dart:9436)
  #10     FunctionNode.visitChildren (package:kernel/ast.dart:3928)
  #11     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560)
  #12     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150)
  #13     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:437)
  #14     FunctionNode.accept (package:kernel/ast.dart:3915)
  #15     Procedure.visitChildren (package:kernel/ast.dart:3233)
  #16     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560)
  #17     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150)
  #18     TreeVisitor.defaultMember (package:kernel/visitor.dart:396)
  #19     TreeVisitor.visitProcedure (package:kernel/visitor.dart:400)
  #20     Procedure.accept (package:kernel/ast.dart:3220)
  #21     Closures.findCaptures (package:dart2wasm/closures.dart:120)
  #22     CodeGenerator.generateBody (package:dart2wasm/code_generator.dart:336)
  #23     CodeGenerator.generate (package:dart2wasm/code_generator.dart:172)
  #24     Translator.translate (package:dart2wasm/translator.dart:434)
  #25     compileToModule (package:dart2wasm/compile.dart:85)
  <asynchronous suspension>
  #26     main (file:///usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/dart2wasm.dart:114)
  <asynchronous suspension>
  ```

  </details>

- ~benchmarks/NativeCall/dart/NativeCall.dart~

- <details>

  <summary>benchmarks/ObjectHash/dart/ObjectHash.dart</summary>

  ```
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:306:19
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:307:19
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:161:23
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:166:25
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:898:20
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:902:20
  Unhandled exception:
  Not supported: Tear-off with optional parameters at org-dartlang-sdk:///lib/core/object.dart:183:14
  #0      Translator.getTearOffFunction.<anonymous closure> (package:dart2wasm/translator.dart:695)
  #1      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527)
  #2      Translator.getTearOffFunction (package:dart2wasm/translator.dart:689)
  #3      ConstantCreator.visitStaticTearOffConstant (package:dart2wasm/constants.dart:686)
  #4      StaticTearOffConstant.accept (package:kernel/ast.dart:13969)
  #5      ConstantCreator.ensureConstant (package:dart2wasm/constants.dart:405)
  #6      ConstantInstantiator.defaultConstant (package:dart2wasm/constants.dart:314)
  #7      ConstantVisitor.visitStaticTearOffConstant (package:kernel/visitor.dart:824)
  #8      StaticTearOffConstant.accept (package:kernel/ast.dart:13969)
  #9      ConstantInstantiator.instantiate (package:dart2wasm/constants.dart:307)
  #10     Constants.instantiateConstant (package:dart2wasm/constants.dart:290)
  #11     CodeGenerator.visitConstantExpression (package:dart2wasm/code_generator.dart:2043)
  #12     ConstantExpression.accept1 (package:kernel/ast.dart:8892)
  #13     CodeGenerator.wrap (package:dart2wasm/code_generator.dart:535)
  #14     CodeGenerator.visitArgumentsLists (package:dart2wasm/code_generator.dart:1967)
  #15     CodeGenerator._visitArguments (package:dart2wasm/code_generator.dart:2001)
  #16     CodeGenerator.visitStaticInvocation (package:dart2wasm/code_generator.dart:1255)
  #17     StaticInvocation.accept1 (package:kernel/ast.dart:6751)
  #18     CodeGenerator.wrap (package:dart2wasm/code_generator.dart:535)
  #19     CodeGenerator.visitAsExpression (package:dart2wasm/code_generator.dart:2208)
  #20     AsExpression.accept1 (package:kernel/ast.dart:7864)
  #21     CodeGenerator.wrap (package:dart2wasm/code_generator.dart:535)
  #22     CodeGenerator.visitLocalFunctionInvocation (package:dart2wasm/code_generator.dart:1902)
  #23     LocalFunctionInvocation.accept1 (package:kernel/ast.dart:6281)
  #24     CodeGenerator.wrap (package:dart2wasm/code_generator.dart:535)
  #25     CodeGenerator.visitExpressionStatement (package:dart2wasm/code_generator.dart:801)
  #26     ExpressionStatement.accept (package:kernel/ast.dart:9380)
  #27     CodeGenerator.visitBlock (package:dart2wasm/code_generator.dart:616)
  #28     Block.accept (package:kernel/ast.dart:9436)
  #29     CodeGenerator.generateBody (package:dart2wasm/code_generator.dart:396)
  #30     CodeGenerator.generate (package:dart2wasm/code_generator.dart:172)
  #31     Translator.translate (package:dart2wasm/translator.dart:434)
  #32     compileToModule (package:dart2wasm/compile.dart:85)
  <asynchronous suspension>
  #33     main (file:///usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/dart2wasm.dart:114)
  <asynchronous suspension>
  ```

  </details>

- <details>

  <summary>benchmarks/Omnibus/dart/Omnibus.dart</summary>

  ```
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:306:19
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:307:19
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:161:23
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:166:25
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:898:20
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:902:20
  Unhandled exception:
  Not supported: Type parameters for function expression or local function at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/MapCopy/dart/MapCopy.dart:310:36
  #0      CaptureFinder._visitLambda (package:dart2wasm/closures.dart:269)
  #1      CaptureFinder.visitFunctionDeclaration (package:dart2wasm/closures.dart:291)
  #2      FunctionDeclaration.accept (package:kernel/ast.dart:11077)
  #3      visitList (package:kernel/ast.dart:14626)
  #4      Block.visitChildren (package:kernel/ast.dart:9443)
  #5      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560)
  #6      Visitor.defaultTreeNode (package:kernel/visitor.dart:1150)
  #7      TreeVisitor.defaultStatement (package:kernel/visitor.dart:348)
  #8      TreeVisitor.visitBlock (package:kernel/visitor.dart:353)
  #9      Block.accept (package:kernel/ast.dart:9436)
  #10     FunctionNode.visitChildren (package:kernel/ast.dart:3928)
  #11     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560)
  #12     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150)
  #13     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:437)
  #14     FunctionNode.accept (package:kernel/ast.dart:3915)
  #15     Procedure.visitChildren (package:kernel/ast.dart:3233)
  #16     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560)
  #17     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150)
  #18     TreeVisitor.defaultMember (package:kernel/visitor.dart:396)
  #19     TreeVisitor.visitProcedure (package:kernel/visitor.dart:400)
  #20     Procedure.accept (package:kernel/ast.dart:3220)
  #21     Closures.findCaptures (package:dart2wasm/closures.dart:120)
  #22     CodeGenerator.generateBody (package:dart2wasm/code_generator.dart:336)
  #23     CodeGenerator.generate (package:dart2wasm/code_generator.dart:172)
  #24     Translator.translate (package:dart2wasm/translator.dart:434)
  #25     compileToModule (package:dart2wasm/compile.dart:85)
  <asynchronous suspension>
  #26     main (file:///usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/dart2wasm.dart:114)
  <asynchronous suspension>
  ```

  </details>

- <details>

  <summary>benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart</summary>

  ```
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:306:19
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:307:19
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:161:23
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:166:25
  Not implemented: Type test with function type FunctionType(dynamic Function(Object, StackTrace)) at org-dartlang-sdk:///lib/async/future_impl.dart:898:20
  Not implemented: Type test with function type FunctionType(dynamic Function(Object)) at org-dartlang-sdk:///lib/async/future_impl.dart:902:20
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:40:32
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:44:24
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:48:23
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:52:19
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:56:27
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:60:20
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:64:22
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:68:33
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:72:37
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:76:34
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:80:26
  Not implemented: CheckLibraryIsLoaded at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart:84:26
  Unimplemented external member Float32x4List. at org-dartlang-sdk:///lib/_internal/vm/lib/typed_data_patch.dart:2846:20
  Unhandled exception:
  Not supported: Type parameters for function expression or local function at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/MapCopy/dart/MapCopy.dart:310:36
  #0      CaptureFinder._visitLambda (package:dart2wasm/closures.dart:269)
  #1      CaptureFinder.visitFunctionDeclaration (package:dart2wasm/closures.dart:291)
  #2      FunctionDeclaration.accept (package:kernel/ast.dart:11077)
  #3      visitList (package:kernel/ast.dart:14626)
  #4      Block.visitChildren (package:kernel/ast.dart:9443)
  #5      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560)
  #6      Visitor.defaultTreeNode (package:kernel/visitor.dart:1150)
  #7      TreeVisitor.defaultStatement (package:kernel/visitor.dart:348)
  #8      TreeVisitor.visitBlock (package:kernel/visitor.dart:353)
  #9      Block.accept (package:kernel/ast.dart:9436)
  #10     FunctionNode.visitChildren (package:kernel/ast.dart:3928)
  #11     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560)
  #12     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150)
  #13     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:437)
  #14     FunctionNode.accept (package:kernel/ast.dart:3915)
  #15     Procedure.visitChildren (package:kernel/ast.dart:3233)
  #16     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560)
  #17     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150)
  #18     TreeVisitor.defaultMember (package:kernel/visitor.dart:396)
  #19     TreeVisitor.visitProcedure (package:kernel/visitor.dart:400)
  #20     Procedure.accept (package:kernel/ast.dart:3220)
  #21     Closures.findCaptures (package:dart2wasm/closures.dart:120)
  #22     CodeGenerator.generateBody (package:dart2wasm/code_generator.dart:336)
  #23     CodeGenerator.generate (package:dart2wasm/code_generator.dart:172)
  #24     Translator.translate (package:dart2wasm/translator.dart:434)
  #25     compileToModule (package:dart2wasm/compile.dart:85)
  <asynchronous suspension>
  #26     main (file:///usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/dart2wasm.dart:114)
  <asynchronous suspension>
  ```

  </details>

- benchmarks/SoundSplayTreeSieve/dart/SoundSplayTreeSieve.dart: SDK constraint error
- ~benchmarks/Startup/dart/Startup.dart~

## Runtime crashes

- <details>

  <summary>BigIntParsePrint.dart.wasm</summary>

  ```
  undefined:1: ReferenceError: self is not defined
  self.bigint_parse = function parse(s) { return BigInt(s); }
  ^
  ReferenceError: self is not defined
      at eval (eval at callMethodVarArgs (pkg/dart2wasm/bin/run_wasm.js:274:29), <anonymous>:1:1)
      at eval (<anonymous>)
      at callMethodVarArgs (pkg/dart2wasm/bin/run_wasm.js:274:29)
      at callMethod (wasm://wasm/000c1432:wasm-function[897]:0x29f95)
      at _eval (wasm://wasm/000c1432:wasm-function[909]:0x2a1b0)
      at _setup (wasm://wasm/000c1432:wasm-function[908]:0x2a13c)
      at _Methods._initialize (wasm://wasm/000c1432:wasm-function[907]:0x2a105)
      at _Methods.enabled (wasm://wasm/000c1432:wasm-function[883]:0x2949b)
      at selectParseNativeBigIntBenchmark (wasm://wasm/000c1432:wasm-function[647]:0x22924)
      at main (wasm://wasm/000c1432:wasm-function[57]:0x15d3f)
  ```

  </details>

- <details>

  <summary>Calls.dart.wasm</summary>

  Compilation prints lots of lines like

  ```
  Not implemented: YieldStatement at file:///usr/local/google/home/omersa/dart/sdk/sdk/benchmarks/Calls/dart/Calls.dart:726:5
  ```

  Runtime error:

  ```
  wasm-function[658]:0x22432: RuntimeError: unreachable
  RuntimeError: unreachable
      at generateNumbersAsyncStar (wasm://wasm/000b669a:wasm-function[658]:0x22432)
      at generateNumbersAsyncStar (tear-off) (wasm://wasm/000b669a:wasm-function[659]:0x22451)
      at performAwaitForIterationPolymorphic (inner) (wasm://wasm/000b669a:wasm-function[836]:0x25349)
      at wasm://wasm/000b669a:wasm-function[837]:0x253bd
      at _asyncBridge2 (wasm://wasm/000b669a:wasm-function[606]:0x21896)
      at _asyncBridge (wasm://wasm/000b669a:wasm-function[57]:0x1577f)
  
  1 pending unhandled Promise rejection(s) detected.
  ```

  </details>

- ~DartCLIStartup.dart.wasm~
- ~IsolateBaseOverhead.dart.wasm~
- ~Isolate.dart.wasm~
- ~IsolateFibonacci.dart.wasm~
- ~IsolateJson.dart.wasm~
- ~SDKArtifactSizes.dart.wasm~
- ~SendPort.dart.wasm~

- <details>

  <summary>SkeletalAnimationSIMD.dart.wasm</summary>

  Compilation prints

  ```
  Unimplemented external member Float32x4List. at org-dartlang-sdk:///lib/_internal/vm/lib/typed_data_patch.dart:2846:20
  ```

  which I think is the reason for the runtime error:

  ```
  wasm-function[620]:0x1d62f: RuntimeError: unreachable
  RuntimeError: unreachable
      at Float32x4List. (wasm://wasm/000894da:wasm-function[620]:0x1d62f)
      at SkeletalAnimationSIMD. (wasm://wasm/000894da:wasm-function[619]:0x1d5de)
      at main (wasm://wasm/000894da:wasm-function[55]:0x12232)
      at $main (wasm://wasm/000894da:wasm-function[56]:0x1223d)
      at pkg/dart2wasm/bin/run_wasm.js:388:22
  ```

  </details>

- TypeLiteral.dart.wasm: causes segfault in the v8 version used in SDK, works fine with v8 10.7.92.

## Summary

Out of 47 benchmarks, we can compile 28 (19 fail to compile), and run 16 benchmarks (12 fail to run).

**Comment by askeksa-google** [comment]
I crossed out a few benchmarks that are irrelevant because they use features that we don't plan to support any time soon (ffi, io, isolates) or measure properties of the SDK that are not dependent on the target platform of the benchmark.

**Comment by osa1** [comment]
With https://dart-review.googlesource.com/c/sdk/+/257362 the only benchmark we can't build (ignoring the ones we don't want to run) is SoundSplayTreeSieve.dart, which fails with a SDK constraint error as before.

Runtime crashes:

- <details>

  <summary>BigIntParsePrint.dart.wasm</summary>

  ```
  undefined:1: ReferenceError: self is not defined
  self.bigint_parse = function parse(s) { return BigInt(s); }
  ^
  ReferenceError: self is not defined
      at eval (eval at callMethodVarArgs (pkg/dart2wasm/bin/run_wasm.js:274:29), <anonymous>:1:1)
      at eval (<anonymous>)
      at callMethodVarArgs (pkg/dart2wasm/bin/run_wasm.js:274:29)
      at callMethod (wasm://wasm/000ce206:wasm-function[956]:0x2a495)
      at _eval (wasm://wasm/000ce206:wasm-function[968]:0x2a6b0)
      at _setup (wasm://wasm/000ce206:wasm-function[967]:0x2a63c)
      at _Methods._initialize (wasm://wasm/000ce206:wasm-function[966]:0x2a605)
      at _Methods.enabled (wasm://wasm/000ce206:wasm-function[940]:0x2998b)
      at selectParseNativeBigIntBenchmark (wasm://wasm/000ce206:wasm-function[690]:0x22e31)
      at main (wasm://wasm/000ce206:wasm-function[57]:0x16016)
  ```

  </details>

- <details>

  <summary>Calls.dart.wasm</summary>

  ```
  wasm-function[689]:0x22b8c: RuntimeError: unreachable
  RuntimeError: unreachable
      at generateNumbersAsyncStar (wasm://wasm/000c1002:wasm-function[689]:0x22b8c)
      at generateNumbersAsyncStar (tear-off) (wasm://wasm/000c1002:wasm-function[690]:0x22bab)
      at performAwaitForIterationPolymorphic (inner) (wasm://wasm/000c1002:wasm-function[889]:0x25bf1)
      at wasm://wasm/000c1002:wasm-function[890]:0x25c65
      at _asyncBridge2 (wasm://wasm/000c1002:wasm-function[634]:0x21fea)
      at _asyncBridge (wasm://wasm/000c1002:wasm-function[57]:0x15ceb)
  ```

  </details>

- <details>

  <summary>ObjectHash.dart.wasm</summary>

  ```
  wasm-function[769]:0x24eef: RuntimeError: unreachable
  RuntimeError: unreachable
      at Function.apply (wasm://wasm/000b632a:wasm-function[769]:0x24eef)
      at generalUses (wasm://wasm/000b632a:wasm-function[654]:0x21210)
      at main (wasm://wasm/000b632a:wasm-function[55]:0x14048)
      at $main (wasm://wasm/000b632a:wasm-function[56]:0x1413b)
      at pkg/dart2wasm/bin/run_wasm.js:388:22
  
  ```

  </details>

- <details>

  <summary>Omnibus.dart.wasm</summary>

  ```
  undefined:1: ReferenceError: self is not defined
  self.bigint_parse = function parse(s) { return BigInt(s); }
  ^
  ReferenceError: self is not defined
      at eval (eval at callMethodVarArgs (pkg/dart2wasm/bin/run_wasm.js:274:29), <anonymous>:1:1)
      at eval (<anonymous>)
      at callMethodVarArgs (pkg/dart2wasm/bin/run_wasm.js:274:29)
      at callMethod (wasm://wasm/0020b286:wasm-function[1750]:0x70854)
      at _eval (wasm://wasm/0020b286:wasm-function[1763]:0x70a88)
      at _setup (wasm://wasm/0020b286:wasm-function[1762]:0x70a13)
      at _Methods._initialize (wasm://wasm/0020b286:wasm-function[1761]:0x709dc)
      at _Methods.enabled (wasm://wasm/0020b286:wasm-function[1732]:0x6f8d9)
      at selectParseNativeBigIntBenchmark (wasm://wasm/0020b286:wasm-function[1544]:0x69e55)
      at main (wasm://wasm/0020b286:wasm-function[680]:0x56aaf)
  ```

  </details>

- <details>

  <summary>OmnibusDeferred.dart.wasm</summary>

  ```
  wasm-function[700]:0x57087: RuntimeError: unreachable
  RuntimeError: unreachable
      at _#loadLibrary_lib_BigIntParsePrint (wasm://wasm/00210616:wasm-function[700]:0x57087)
      at _#loadLibrary_lib_BigIntParsePrint (tear-off) (wasm://wasm/00210616:wasm-function[701]:0x57092)
      at main (inner) (wasm://wasm/00210616:wasm-function[656]:0x562a9)
      at wasm://wasm/00210616:wasm-function[657]:0x562f6
      at _asyncBridge2 (wasm://wasm/00210616:wasm-function[640]:0x55cb2)
      at _asyncBridge (wasm://wasm/00210616:wasm-function[59]:0x3e12f)
  ```

  </details>

- <details>

  <summary>SkeletalAnimationSIMD.dart.wasm</summary>

  ```
  wasm-function[651]:0x1d9b4: RuntimeError: unreachable
  RuntimeError: unreachable
      at Float32x4List. (wasm://wasm/0008e5fa:wasm-function[651]:0x1d9b4)
      at SkeletalAnimationSIMD. (wasm://wasm/0008e5fa:wasm-function[650]:0x1d963)
      at main (wasm://wasm/0008e5fa:wasm-function[55]:0x12422)
      at $main (wasm://wasm/0008e5fa:wasm-function[56]:0x1242d)
      at pkg/dart2wasm/bin/run_wasm.js:388:22
  ```

  </details>

- TypeLiteral.dart.wasm segfauls as before

**Comment by osa1** [comment]
Results as of 2932261f835: same as above, except `TypeLiteral.dart` no longer segfaults.

**Comment by osa1** [comment]
Results as of 8ef5104d05e: all works!
