### ISSUE TITLE
build_web_compilers:ddc - compilation error on extension function

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/sdk#49908]
The following extension triggers a dev compiler error (webdev):

```dart


extension _ListExtension<T> on List<T> {
  List<Object?> mergeWithOther<E>(List<E> other) {
    return List<Object?>.generate(length, (i) {
      var e = this[i] ?? other[i];
      return e; // Line that triggers the error
      /*
      return e as Object?; // Won't trigger the error
      */
    });
  }
}

```

Error:
```
Unsupported operation: Undetermined Nullability encountered while compiling packages/XXXXXXXX.dart, which contains the type: InterfaceType(Object%).
#0      ProgramCompiler._undeterminedNullabilityError (package:dev_compiler/src/kernel/compiler.dart:3044:7)
#1      ProgramCompiler._emitInterfaceType (package:dev_compiler/src/kernel/compiler.dart:2994:7)
#2      ProgramCompiler.visitInterfaceType (package:dev_compiler/src/kernel/compiler.dart:2917:7)
#3      InterfaceType.accept (package:kernel/ast.dart:11499:42)
#4      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:2884:54)
#5      ProgramCompiler.visitFunctionType (package:dev_compiler/src/kernel/compiler.dart:3107:22)
#6      ProgramCompiler._emitFunctionTagged (package:dev_compiler/src/kernel/compiler.dart:2840:19)
#7      ProgramCompiler.visitFunctionExpression (package:dev_compiler/src/kernel/compiler.dart:6320:12)
#8      FunctionExpression.accept (package:kernel/ast.dart:8639:44)
#9      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3838:20)
#10     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:5675:11)
#11     ProgramCompiler._emitFactoryInvocation (package:dev_compiler/src/kernel/compiler.dart:5935:9)
#12     ProgramCompiler.visitStaticInvocation (package:dev_compiler/src/kernel/compiler.dart:5486:34)
#13     StaticInvocation.accept (package:kernel/ast.dart:6648:44)
#14     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3838:20)
#15     ProgramCompiler.visitReturnStatement (package:dev_compiler/src/kernel/compiler.dart:4400:45)
#16     ReturnStatement.accept (package:kernel/ast.dart:10238:43)
#17     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3747:20)
#18     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#19     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#20     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#21     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#22     new List.of (dart:core-patch/array_patch.dart:51:28)
#23     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#24     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3932:62)
#25     Block.accept (package:kernel/ast.dart:9244:43)
#26     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3747:20)
#27     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3780:18)
#28     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3549:17)
#29     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2411:25)
#30     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3583:18)
#31     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3545:17)
#32     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3359:11)
#33     ProgramCompiler._emitLibraryFunction (package:dev_compiler/src/kernel/compiler.dart:2795:14)
#34     MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#35     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#36     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#37     new List.of (dart:core-patch/array_patch.dart:51:28)
#38     Iterable.toList (dart:core/iterable.dart:470:12)
#39     ProgramCompiler._emitLibraryProcedures (package:dev_compiler/src/kernel/compiler.dart:2760:10)
#40     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:604:7)
#41     List.forEach (dart:core-patch/growable_array.dart:416:8)
#42     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:442:15)
#43     _compile (package:dev_compiler/src/kernel/command.dart:442:27)
<asynchronous suspension>
#44     _CompilerWorker.performRequest (package:dev_compiler/ddc.dart:69:18)
<asynchronous suspension>
#45     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:35:20)
<asynchronous suspension>
#46     internalMain (package:dev_compiler/ddc.dart:32:5)
<asynchronous suspension>

```

Dart version:
```
Dart SDK version: 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "macos_x64"
```

webdev:
```
Activated webdev 2.7.11.
```

**Comment by gmpassos** [comment]
See the issue for the `dart2js` compiler:
https://github.com/dart-lang/sdk/issues/49909
