### ISSUE TITLE
dart2js - compilation error on extension function

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/sdk#49909]
The function bellow triggers a `dart2js` compilation error:

```dart

extension _ListExtension<T> on List<T> {
  List<Object?> mergeWithOther<E>(List<E> other) {
    return List.generate(length, (i) {
      Object? e = this[i] ?? other[i];
      return e;
    });
  }
}

```

Workaround to avoid the compiler error:

```dart

extension _ListExtension<T> on List<T> {
  List<Object?> mergeWithOther<E>(List<E> other) {
    return List.generate(length, (i) {
      Object? a = this[i];
      Object? b = other[i];
      Object? e = a ?? b;
      return e;
    });
  }
}

```

Compiler error:

```
Internal Error: The compiler crashed when compiling this element.
  List<Object?> mergeWithOther<E>(List<E> other) {
                ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.18.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Unsupported operation: Undetermined nullability on InterfaceType(Object%)
#0      DartTypeConverter._convertNullability (package:compiler/src/ir/visitors.dart:81:9)
#1      DartTypeConverter.visitInterfaceType (package:compiler/src/ir/visitors.dart:159:12)
#2      InterfaceType.accept (package:kernel/ast.dart:11499:42)
#3      DartTypeConverter.visitType (package:compiler/src/ir/visitors.dart:87:17)
#4      JsKernelToElementMap.getDartType (package:compiler/src/js_model/element_map_impl.dart:858:60)
#5      LocalData.getDartType (package:compiler/src/js_model/locals.dart:631:33)
#6      KernelToLocalsMapImpl.getLocalType (package:compiler/src/js_model/locals.dart:292:35)
#7      KernelTypeGraphBuilder.visitVariableDeclaration (package:compiler/src/inferrer/builder.dart:825:32)
#8      VariableDeclaration.accept (package:kernel/ast.dart:10824:43)
#9      KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder.dart:267:24)
#10     KernelTypeGraphBuilder.visitBlock (package:compiler/src/inferrer/builder.dart:486:7)
#11     Block.accept (package:kernel/ast.dart:9244:43)
#12     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder.dart:267:24)
#13     KernelTypeGraphBuilder.visitFunctionNode (package:compiler/src/inferrer/builder.dart:410:5)
#14     FunctionNode.accept (package:kernel/ast.dart:3896:38)
#15     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder.dart:267:24)
#16     KernelTypeGraphBuilder.run (package:compiler/src/inferrer/builder.dart:234:12)
#17     KernelTypeGraphBuilder.handleLocalFunction (package:compiler/src/inferrer/builder.dart:1955:13)
#18     KernelTypeGraphBuilder.visitFunctionExpression (package:compiler/src/inferrer/builder.dart:1968:12)
#19     FunctionExpression.accept (package:kernel/ast.dart:8639:44)
#20     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder.dart:267:24)
#21     KernelTypeGraphBuilder.analyzeArguments (package:compiler/src/inferrer/builder.dart:869:22)
#22     KernelTypeGraphBuilder.visitStaticInvocation (package:compiler/src/inferrer/builder.dart:1547:32)
#23     StaticInvocation.accept (package:kernel/ast.dart:6648:44)
#24     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder.dart:267:24)
#25     KernelTypeGraphBuilder.visitReturnStatement (package:compiler/src/inferrer/builder.dart:736:61)
#26     ReturnStatement.accept (package:kernel/ast.dart:10238:43)
#27     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder.dart:267:24)
#28     KernelTypeGraphBuilder.visitBlock (package:compiler/src/inferrer/builder.dart:486:7)
#29     Block.accept (package:kernel/ast.dart:9244:43)
#30     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder.dart:267:24)
#31     KernelTypeGraphBuilder.visitFunctionNode (package:compiler/src/inferrer/builder.dart:410:5)
#32     FunctionNode.accept (package:kernel/ast.dart:3896:38)
#33     KernelTypeGraphBuilder.visit (package:compiler/src/inferrer/builder.dart:267:24)
#34     KernelTypeGraphBuilder.run (package:compiler/src/inferrer/builder.dart:234:12)
#35     InferrerEngine._computeMemberTypeInformation (package:compiler/src/inferrer/engine.dart:635:20)
#36     InferrerEngine.analyze.<anonymous closure> (package:compiler/src/inferrer/engine.dart:569:14)
#37     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#38     InferrerEngine.analyze (package:compiler/src/inferrer/engine.dart:568:15)
#39     InferrerEngine._analyzeAllElements.<anonymous closure>.<anonymous closure> (package:compiler/src/inferrer/engine.dart:508:38)
#40     TypeSystem.withMember (package:compiler/src/inferrer/type_system.dart:132:11)
#41     InferrerEngine._analyzeAllElements.<anonymous closure> (package:compiler/src/inferrer/engine.dart:508:13)
#42     Iterable.forEach (dart:core/iterable.dart:325:35)
#43     InferrerEngine._analyzeAllElements (package:compiler/src/inferrer/engine.dart:503:22)
#44     DurationMetric.measure (package:compiler/src/common/metrics.dart:74:22)
#45     InferrerEngine._runOverAllElements (package:compiler/src/inferrer/engine.dart:317:21)
#46     DurationMetric.measure (package:compiler/src/common/metrics.dart:74:22)
#47     InferrerEngine.runOverAllElements (package:compiler/src/inferrer/engine.dart:313:18)
#48     TypeGraphInferrer.analyzeMain (package:compiler/src/inferrer/type_graph_inferrer.dart:76:14)
#49     GlobalTypeInferenceTask.runGlobalTypeInference.<anonymous closure> (package:compiler/src/inferrer/types.dart:196:41)
#50     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#51     GlobalTypeInferenceTask.runGlobalTypeInference (package:compiler/src/inferrer/types.dart:187:12)
#52     Compiler.performGlobalTypeInference (package:compiler/src/compiler.dart:477:28)
#53     Compiler.produceGlobalTypeInferenceResults (package:compiler/src/compiler.dart:592:26)
#54     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:675:15)
<asynchronous suspension>
#55     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:309:7)
<asynchronous suspension>
#56     Compiler.runInternal (package:compiler/src/compiler.dart:308:5)
<asynchronous suspension>
#57     main (package:compiler/src/dart2js.dart:1424:3)
<asynchronous suspension>

```

**Comment by gmpassos** [comment]
See the error for the DDC compiler:

https://github.com/dart-lang/sdk/issues/49908
