### ISSUE TITLE
[frontend] Compiler crashes when building local SDK

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#49910]
Looks like commit 

[pkg:compiler - enable and fix use_super_parameters lint](https://github.com/dart-lang/sdk/commit/460075336b52d37176de9e052b583ee240abc0d1) 

causes local compilation of the SDK to fail with a crash on arm64 (see stack trace below).

Compilation works with previous commit:

[Eliminate more dynamic invocations in pkg/compiler](https://github.com/dart-lang/sdk/commit/677cb7fb3ea8e922c3a33566c3e3685ea5c70fea)

**Repro**

``` ./tools/build.py --mode release create_sdk create_full_sdk

sdk git:(main) ./tools/build.py --mode release create_sdk create_full_sdk
Generating Xcode projects took 24ms
Done. Made 319 targets from 89 files in 925ms
using /var/folders/v9/232dwc2x0t113h5qhxkkgcjm00p2zc/T/goma_annagrin as tmpdir
# login as annagrin@google.com
override GOMA_PROVIDE_INFO=true
override GOMA_SEND_USER_INFO=true
override GOMA_COMPILER_PROXY_ENABLE_CRASH_DUMP=true
override GOMACTL_USE_PROXY=true
Enable http_proxy
override GOMA_SERVER_HOST=127.0.0.1
override GOMA_SERVER_PORT=19080
override GOMA_USE_SSL=false
GOMA version 07a4e71760fa04f271c55755211d8e4eb15e52e5@1657759893

server: goma.chromium.org:443 (via http_proxy)
goma is already running.

ninja -C xcodebuild/ReleaseARM64 -j1000 -l64 create_sdk create_full_sdk
ninja: Entering directory `xcodebuild/ReleaseARM64'
[1112/1234] ACTION //utils/dartdevc:stack_trace_mapper(//build/toolchain/mac:clang_arm64)
FAILED: dev_compiler/build/web/dart_stack_trace_mapper.js
python3 ../../build/gn_run_binary.py compiled_action /Users/annagrin/source/dart-sdk/sdk/tools/sdks/dart-sdk/bin/dart -Dsdk_hash=460075336b --packages=/Users/annagrin/source/dart-sdk/sdk/.dart_tool/package_config.json --dfe=/Users/annagrin/source/dart-sdk/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /Users/annagrin/source/dart-sdk/sdk/pkg/compiler/lib/src/dart2js.dart /Users/annagrin/source/dart-sdk/sdk/pkg/dev_compiler/web/stack_trace_mapper.dart -m -o/Users/annagrin/source/dart-sdk/sdk/xcodebuild/ReleaseARM64/dev_compiler/build/web/dart_stack_trace_mapper.js --no-source-maps --platform-binaries=/Users/annagrin/source/dart-sdk/sdk/xcodebuild/ReleaseARM64
Command failed: /Users/annagrin/source/dart-sdk/sdk/tools/sdks/dart-sdk/bin/dart -Dsdk_hash=460075336b --packages=/Users/annagrin/source/dart-sdk/sdk/.dart_tool/package_config.json --dfe=/Users/annagrin/source/dart-sdk/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /Users/annagrin/source/dart-sdk/sdk/pkg/compiler/lib/src/dart2js.dart /Users/annagrin/source/dart-sdk/sdk/pkg/dev_compiler/web/stack_trace_mapper.dart -m -o/Users/annagrin/source/dart-sdk/sdk/xcodebuild/ReleaseARM64/dev_compiler/build/web/dart_stack_trace_mapper.js --no-source-maps --platform-binaries=/Users/annagrin/source/dart-sdk/sdk/xcodebuild/ReleaseARM64
output: Crash when compiling null,
at character offset null:
Null check operator used on a null value
#0      InferableTypeBuilderMixin.type (package:front_end/src/fasta/builder/type_builder.dart:392:29)
#1      InferableTypeBuilder.inferType (package:front_end/src/fasta/builder/omitted_type_builder.dart:155:12)
#2      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:2358:19)
#3      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:532:14)
<asynchronous suspension>
#4      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#5      _buildInternal (package:front_end/src/kernel_generator_impl.dart:139:7)
<asynchronous suspension>
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#7      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:47:12)
<asynchronous suspension>
#8      generateKernel (package:front_end/src/kernel_generator_impl.dart:46:10)
<asynchronous suspension>
#9      kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#10     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:412:11)
<asynchronous suspension>
#11     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:221:45)
<asynchronous suspension>
#12     _processLoadRequest (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:914:37)
<asynchronous suspension>
```

**Comment by kevmoo** [comment]
🤷  Oh no! This feel like a "deeper" bug, though. Although I'm not smart enough to read the tea leaves.

@lrhn ?

**Comment by kevmoo** [comment]
My commit landed over a week ago. Has the build been broken that long @annagrin ?

**Comment by annagrin** [comment]
@kevmoo all commits including this one cause the crash (including the current master). I haven't built the SDK for a while so I haven't noticed the break. Could be that the new code is executed in the frontend that  have not been executing before? @johnniwinther @chloestefantsova FIY

**Comment by annagrin** [comment]
Update: it might be the state on my machine since @nshahan can build the current master. Cleaning the build and rebuilding now.

**Comment by annagrin** [comment]
Update: removing the output directory and rebuilding fixed the problem, closing the issue. Thanks @kevmoo & @nshahan !

**Comment by kevmoo** [comment]
What's the "yay, I didn't break it – it wasn't my fault" emoticon? 😀
