### ISSUE TITLE
Get a LateInitializationError

### ISSUE THREAD

**Issue by KyoheiG3** [dart-lang/sdk#49922]
Unintended errors in apps created with `dart compile exe`.

The code I wrote in `late.dart` is below.
```dart
main() {
  late final Object object;
  try {
    throw UnimplementedError();
  } catch (e) {
    object = Object();
  }
}
```

Then, executed compiled file.
```
$ dart compile exe late.dart
$ ./late.exe
```

The result is below.
```
Unhandled exception:
LateInitializationError: Local 'object' has already been initialized.
#0      LateError._throwLocalAlreadyInitialized (dart:_internal-patch/internal_patch.dart:204)
#1      main (file:///Users/me/late.dart:6)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

Dart SDK Version
```
$ dart --version             
Dart SDK version: 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "macos_x64"
```

**Comment by mraleph** [comment]
This is fixed by 6ad380575159ba81cb836d7c3256e507ff9fd323
