### ISSUE TITLE
pkg/dds/test/dap/integration/debug_test flakey?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#50058]
It looks like the `pkg/dds/test/dap/integration/debug_test` test may now be flakey? I'm seeing several failures related to it on some of my CLs, for work that's unrelated. This is always on the pkg-linux-release-try bot - not on other platforms.

This seems like the most recent work on that test: https://github.com/dart-lang/sdk/commit/fe8c22cc69d826606d706eb9e21bb44c8b5aff9c, though I don't know if its related to the failure or not. cc @DanTup 

Here's the test failure stack trace:

```
<== [DAP] {"seq":32,"type":"event","body":{"message":"<== [VM] {\"jsonrpc\":\"2.0\",\"result\":{\"type\":\"Success\"},\"id\":\"10\"}"},"event":"dart.log"}

00:36 [32m+11[0m[33m ~1[0m[31m -1[0m: debug mode can shutdown during startup [1m[31m[E][0m[0m

  Unhandled exception:
  lookupResolvedPackageUris: (-32000) Bad state: The client closed with pending request "lookupResolvedPackageUris"..

  pkg/dds/test/dap/integration/test_server.dart 97:9  new OutOfProcessDapTestServer._.<fn>
  dart:async/zone.dart 1406:47                        _rootRunUnary
  dart:async/zone.dart 1307:19                        _CustomZone.runUnary
  dart:async/zone.dart 1216:7                         _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 339:11                  _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 271:7                   _BufferingStreamSubscription._add
  dart:async/stream_transformers.dart 63:11           _SinkTransformerStreamSubscription._add
  dart:async/stream_transformers.dart 13:11           _EventSinkWrapper.add
  dart:convert/string_conversion.dart 238:11          _StringAdapterSink.add
  dart:convert/string_conversion.dart 243:7           _StringAdapterSink.addSlice
  dart:convert/string_conversion.dart 317:20          _Utf8ConversionSink.addSlice
  dart:convert/string_conversion.dart 310:5           _Utf8ConversionSink.add
  dart:convert/chunked_conversion.dart 72:18          _ConverterStreamEventSink.add
  dart:async/stream_transformers.dart 111:24          _SinkTransformerStreamSubscription._handleData
  dart:async/zone.dart 1406:47                        _rootRunUnary
  dart:async/zone.dart 1307:19                        _CustomZone.runUnary
  dart:async/zone.dart 1216:7                         _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 339:11                  _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 271:7                   _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 774:19            _SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 648:7             _StreamController._add
  dart:async/stream_controller.dart 596:5             _StreamController.add
  dart:io-patch/socket_patch.dart 2331:41             _Socket._onData
  dart:async/zone.dart 1414:13                        _rootRunUnary
  dart:async/zone.dart 1307:19                        _CustomZone.runUnary
  dart:async/zone.dart 1216:7                         _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 339:11                  _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 271:7                   _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 774:19            _SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 648:7             _StreamController._add
  dart:async/stream_controller.dart 596:5             _StreamController.add
  dart:io-patch/socket_patch.dart 1856:33             new _RawSocket.<fn>
  dart:io-patch/socket_patch.dart 1329:14             _NativeSocket.issueReadEvent.issue
  dart:async/schedule_microtask.dart 40:21            _microtaskLoop
  dart:async/schedule_microtask.dart 49:5             _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 122:13        _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 193:5         _RawReceivePortImpl._handleMessage
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8801934298677862321/+/u/test_results/new_test_failures__logs_

**Comment by devoncarew** [comment]
cc @bkonyi

**Comment by bkonyi** [comment]
cc @DanTup

**Comment by DanTup** [comment]
Thanks, I can reproduce this intermittently running inside an Ubuntu container but only when running the test with the out-of-process DAP (which unfortunately makes it difficult to debug).

With some additional try/catches I was able to get a full stack. Oddly, it contains `_withErrorHandling` and even after updating that to handle this type of error (-32000), the error still seems to go unhandled.

I'll keep digging. I don't think the issue was caused by the _change_ above, but rather an "improvement" to this test I snuck in because I noticed the test wasn't waiting for the process to end correctly (which likely meant it was missing this bug - which occurs if you try to terminate during debugger initialization - previously).

```
00:17 +0 -1: debug mode can shutdown during startup [E]
  STDERR output from DAP process: Unhandled exception:
  DANNYDANNY lookupResolvedPackageUris: (-32000) Bad state: The client closed with pending request "lookupResolvedPackageUris".:
  #0      IsolateManager._lookupResolvedPackageUris (package:dds/src/dap/isolate_manager.dart:547:27)
  #1      ThreadInfo.resolveUrisToPathsBatch (package:dds/src/dap/isolate_manager.dart:918:22)
  #2      ThreadInfo.resolveUrisToPackageLibPathsBatch (package:dds/src/dap/isolate_manager.dart:885:27)
  #3      IsolateManager._sendLibraryDebuggables (package:dds/src/dap/isolate_manager.dart:728:18)
  <asynchronous suspension>
  #4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
  <asynchronous suspension>
  #5      IsolateManager._configureIsolate (package:dds/src/dap/isolate_manager.dart:361:5)
  <asynchronous suspension>
  #6      IsolateManager.registerIsolate (package:dds/src/dap/isolate_manager.dart:215:7)
  <asynchronous suspension>
  #7      DartDebugAdapter._configureExistingIsolates.<anonymous closure> (package:dds/src/dap/adapters/dart.dart:690:11)
  <asynchronous suspension>
  #8      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
  <asynchronous suspension>
  #9      DartDebugAdapter._configureExistingIsolates (package:dds/src/dap/adapters/dart.dart:683:5)
  <asynchronous suspension>
  #10     DartDebugAdapter._withErrorHandling (package:dds/src/dap/adapters/dart.dart:2103:16)
  <asynchronous suspension>
  #11     DartDebugAdapter.connectDebugger (package:dds/src/dap/adapters/dart.dart:631:5)
  <asynchronous suspension>
  #12     DartCliDebugAdapter.launchImpl.<anonymous closure> (package:dds/src/dap/adapters/dart_cli_adapter.dart:105:11)
```

**Comment by DanTup** [comment]
I _think_ I have a fix here:

https://dart-review.googlesource.com/c/sdk/+/261401/

I believe the issue is that we were using `rethrow` to propagate an error even though it was also being handled via completers. When we rethrow, code that would use `Future.wait()` on the completers futures would be bypasses, so those futures looked like they had "uncaught" errors and would go unhandled.

I've removed `rethrow` so they're instead handled via the Completers/Futures, and I've also added an exception for this type of error code that wasn't handled before in `_withErrorHandling`.

Another fix could be changing `_withErrorHandling` to use `runZoneGuarded` (and perhaps that makes sense too), but probably shouldn't be a substitute for ensuring there aren't dangling failing futures.

**Comment by devoncarew** [comment]
Fantastic, thanks for the investigation (and, cleaning up the test behavior)!

**Comment by DanTup** [comment]
@devoncarew is https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=pkg/dds/test/dap/integration/debug_test the best place for me to check this isn't still flaky after the change lands? I presume there will be a "flaky -> pass" entry (and then hopefully no more entries added after that)?

**Comment by devoncarew** [comment]
> @devoncarew is https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=pkg/dds/test/dap/integration/debug_test the best place for me to check this isn't still flaky after the change lands? I presume there will be a "flaky -> pass" entry (and then hopefully no more entries added after that)?

Hmm, probably? I mostly just follow links from the CI failures page until I see the test results.

**Comment by DanTup** [comment]
Well apparently that page still doesn't show any updated results since the last time I looked. I checked a few results from changes since the fix landed, and I can't see it failing in the flaky test log (where I do see it on the commit before my fix), so I _think_ it's fixed - but let me know if you see it again. Thanks!

**Comment by srujzs** [comment]
It looks like this started flaking enough again that it's being treated as a `RuntimeError` on the `pkg-win-release{-arm64}` bots: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8734641885770892977/+/u/test_results/stdout

**Comment by DanTup** [comment]
This looks like a new issue being tracked in https://github.com/dart-lang/sdk/issues/56557
