### ISSUE TITLE
[dart2wasm] Incorrect re-throw compilation with nested try-finally blocks

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#50062]
Discovered this while working on #50026.

```dart
class Ex1 implements Exception {}

void main() {
  try {
    try {
      return;
    } finally {
      print('Finally 1');
      throw Ex1();
    }
  } finally {
    print('Finally 2');
  }
  print('Outside of try-catch-finally');
}
```

Output with JIT:

```
Finally 1
Finally 2
Unhandled exception:
Instance of 'Ex1'
#0      main (file:///usr/local/google/home/omersa/dart/test.dart:20:9)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

Output with dart2wasm:

```
Finally 1
Finally 2
```

The exception is lost. Expected output should be something like:

```
Finally 1
Finally 2
undefined:0: [object WebAssembly.Exception]
```

**Comment by osa1** [comment]
I wonder if this has to do with something we do specially for `main` functions, because compilation of try-finally blocks seems to be correct. This works as expected:

```dart
class Ex1 implements Exception {}

void main() {
  try {
    f();
  } catch (_) {
    print('Exception caught');
  } finally {
    print('Finally 3');
  }
}

void f() {
  try {
    try {
      return;
    } finally {
      print('Finally 1');
      throw Ex1();
    }
  } finally {
    print('Finally 2');
  }
}
```

But if I remove the try-catch in `main`, the exception thrown by `f` is lost:

```dart
class Ex1 implements Exception {}

void main() {
  f(); // does not throw
}

void f() {
  try {
    try {
      return;
    } finally {
      print('Finally 1');
      throw Ex1();
    }
  } finally {
    print('Finally 2');
  }
}
```

**Comment by askeksa-google** [comment]
With https://dart-review.googlesource.com/c/sdk/+/267740 the exception is correctly printed.
