### ISSUE TITLE
Unexpected type InvalidType InvalidType(<invalid>)

### ISSUE THREAD

**Issue by hamatoma** [dart-lang/sdk#50112]
Dart SDK version: 2.19.0-265.0.dev (dev) (Sun Oct 2 14:25:42 2022 -0700) on "linux_x64"

* Compiling the source crashes the linux compiler:
* Source: https://public.hamatoma.de/dl/darterror.tgz
* Unpack the tar file, call "dart pub get" and "dart compile exe bin/pollsam.dart"
* The source code was reduced until the error just occurred: 2 files, 1374+2289 bytes
More info from issue@hamatoma.de
```
Unexpected type InvalidType InvalidType(<invalid>)
#0      TypesBuilder.fromStaticType (package:vm/transformations/type_flow/types.dart:113:7)
#1      SummaryCollector._staticType (package:vm/transformations/type_flow/summary_collector.dart:1211:21)
#2      SummaryCollector._makeCall (package:vm/transformations/type_flow/summary_collector.dart:1118:26)
#3      SummaryCollector._handlePropertyGet (package:vm/transformations/type_flow/summary_collector.dart:1760:16)
#4      SummaryCollector.visitInstanceGet (package:vm/transformations/type_flow/summary_collector.dart:1773:12)
#5      InstanceGet.accept (package:kernel/ast.dart:4476:44)
#6      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:880:44)
#7      SummaryCollector.visitVariableDeclaration (package:vm/transformations/type_flow/summary_collector.dart:2226:43)
#8      VariableDeclaration.accept (package:kernel/ast.dart:10952:43)
#9      List.forEach (dart:core-patch/growable_array.dart:416:8)
#10     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:2009:21)
#11     Block.accept (package:kernel/ast.dart:9365:43)
#12     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:883:10)
#13     SummaryCollector.visitForStatement (package:vm/transformations/type_flow/summary_collector.dart:2095:5)
#14     ForStatement.accept (package:kernel/ast.dart:9833:43)
#15     List.forEach (dart:core-patch/growable_array.dart:416:8)
#16     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:2009:21)
#17     Block.accept (package:kernel/ast.dart:9365:43)
#18     List.forEach (dart:core-patch/growable_array.dart:416:8)
#19     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:2009:21)
#20     Block.accept (package:kernel/ast.dart:9365:43)
#21     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:883:10)
#22     SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:757:9)
#23     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1579:55)
#24     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:298:42)
#25     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#26     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1473:27)
#27     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:449:44)
#28     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#29     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:423:12)
#30     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1473:27)
#31     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1724:23)
#32     Call.apply (package:vm/transformations/type_flow/summary.dart:268:31)
#33     Summary.apply (package:vm/transformations/type_flow/summary.dart:724:33)
#34     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:307:24)
#35     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#36     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1473:27)
#37     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1415:7)
#38     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1605:14)
#39     transformComponent (package:vm/transformations/type_flow/transformer.dart:112:20)
#40     runGlobalTransformations (package:vm/kernel_front_end.dart:489:20)
#41     compileToKernel (package:vm/kernel_front_end.dart:408:11)
<asynchronous suspension>
#42     runCompiler (package:vm/kernel_front_end.dart:294:19)
<asynchronous suspension>
#43     main (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/gen_kernel.dart:34:19)
<asynchronous suspension>
Error: AOT compilation failed
Generating AOT kernel dill failed!
```

**Comment by alexmarkov** [comment]
@hamatoma For legal reasons, we cannot debug problems that require looking at proprietary code. Could you share the source code on github and add a permissive license such as [BSD](https://github.com/dart-lang/sdk/blob/main/LICENSE)?

@johnniwinther From the stack trace, it looks like `InstanceGet.getStaticType` returned `InvalidType`. How is this possible?

**Comment by johnniwinther** [comment]
@alexmarkov That seems odd. `InstanceGet.getStaticType` just returns `InstanceGet.resultType` which is set on construction, and `InvalidType` should only be the result of a compile error.

**Comment by alexmarkov** [comment]
@johnniwinther This happened because we hit the following case in `ForInStatement.getElementTypeInternal`:
https://github.com/dart-lang/sdk/blob/fcc9473dab13869858863a4ae77a5ec362db32dd/pkg/kernel/lib/ast.dart#L10038-L10040

**Comment by hamatoma** [comment]
Workaround for other people with that error: 

Delete pubspec.lock, execute "dart pub get" and be happy.
