### ISSUE TITLE
Create an issue

### ISSUE THREAD

**Issue by 337240552** [dart-lang/sdk#50183]
* Dart SDK Version (`dart --version`)
`Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "macos_x64"`

* Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOSX

Run vm_snapshot_analysis:analyse crashed with stack as below.
cmd: `vm_snapshot_analysis:analyse summary apk-code-size-analysis_11.json`

apk-code-size-analysis_11.json was produced by follow command.
`flutter build apk --release --analyze-size --target-platform android-arm64`

crash stack
```
Unhandled exception:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast
#0      loadProgramInfoFromJson (package:vm_snapshot_analysis/utils.dart:20:51)
#1      outputSummary (package:vm_snapshot_analysis/src/commands/summary.dart:179:16)
<asynchronous suspension>
#2      SummaryCommand.run (package:vm_snapshot_analysis/src/commands/summary.dart:143:5)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#4      main (file:///Users/mingchunhu/.pub-cache/hosted/pub.dartlang.org/vm_snapshot_analysis-0.7.2/bin/analyse.dart:43:5)
<asynchronous suspension>

```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[!] Android Studio
    ✗ Unable to find bundled Java version.
[!] Android Studio (version 2021.2)
    ✗ Failed to run Java: ProcessException: Bad CPU type in executable
        Command: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java -version
    ✗ Unable to determine bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
[✓] VS Code (version 1.70.2)
[!] Proxy Configuration
    ! NO_PROXY does not contain ::1
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 3 categories.
```

**Comment by 337240552** [comment]
This is not an issue. What a shame, I use the run snapshot json. I am so Sorry!
