### ISSUE TITLE
Compilation issues with records experiment using records in generic types.

### ISSUE THREAD

**Issue by TimWhiting** [dart-lang/sdk#50182]
First off thank you all for all your hard work on dart & the new features coming out!

I'm aware that records is not out. But also I'm assuming you want the bugs worked out before releasing it. 

While playing with records, I've noticed a lot of simple use cases work, but there are a few compilation issues with more complex usages (mainly with generics)

* Analyzer
* Common Front End (CFE) and kernel
* Dart VM

* Dart SDK version: 2.19.0-299.0.dev (dev) (Tue Oct 11 06:13:18 2022 -0700) on "linux_x64"

```dart
void main() {
  final c = MyClass(() => Value((1, name: 1)));
  final value = c.myField()?.value.name;
  print(c);
}

class MyClass<T> {
  MyClass(this.myField);

  final Value<Hello<T>>? Function() myField;
}

class Value<T> {
  Value(this.value);

  final T value;
}

typedef Hello<T> = (T, {T name});
```

<details>
<summary>
Error when running via `dart --enable-experiment=records hello.dart`:
</summary>

```
Null check operator used on a null value
#0      BinaryPrinter._getVariableIndex (package:kernel/binary/ast_to_binary.dart:83:17)
#1      BinaryPrinter.visitVariableGet (package:kernel/binary/ast_to_binary.dart:1558:17)
#2      VariableGet.accept (package:kernel/ast.dart:4096:44)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:437:10)
#4      BinaryPrinter.visitInstanceGet (package:kernel/binary/ast_to_binary.dart:1604:5)
#5      InstanceGet.accept (package:kernel/ast.dart:4466:44)
#6      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:437:10)
#7      BinaryPrinter.visitRecordNameGet (package:kernel/binary/ast_to_binary.dart:1623:5)
#8      RecordNameGet.accept (package:kernel/ast.dart:4285:44)
#9      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:437:10)
#10     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:529:7)
#11     BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:2382:5)
#12     BinaryPrinter.visitVariableDeclaration (package:kernel/binary/ast_to_binary.dart:2368:5)
#13     VariableDeclaration.accept (package:kernel/ast.dart:10943:43)
#14     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:437:10)
#15     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#16     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2178:5)
#17     Block.accept (package:kernel/ast.dart:9355:43)
#18     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:437:10)
#19     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:529:7)
#20     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1542:5)
#21     FunctionNode.accept (package:kernel/ast.dart:3839:38)
#22     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:444:10)
#23     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1371:5)
#24     Procedure.accept (package:kernel/ast.dart:3231:40)
#25     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:465:10)
#26     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:356:7)
#27     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1115:5)
#28     Library.accept (package:kernel/ast.dart:561:38)
#29     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:458:10)
#30     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:764:9)
#31     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:603:7)
#32     Timeline.timeSync (dart:developer/timeline.dart:166:22)
#33     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:584:14)
#34     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:112:11)
#35     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:940:41)
```
</details>

<details>
<summary>
Error when compiling to an executable `dart compile exe --enable-experiment=records  hello.dart`:
</summary>

```
Unhandled exception:
Null check operator used on a null value
#0      _VariablesInfoCollector._useVariable (package:vm/transformations/type_flow/summary_collector.dart:379:37)
#1      _VariablesInfoCollector.visitVariableGet (package:vm/transformations/type_flow/summary_collector.dart:438:5)
#2      VariableGet.accept (package:kernel/ast.dart:4096:44)
#3      InstanceGet.visitChildren (package:kernel/ast.dart:4474:14)
#4      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560:10)
#5      Visitor.defaultTreeNode (package:kernel/visitor.dart:1150:39)
#6      TreeVisitor.defaultExpression (package:kernel/visitor.dart:199:43)
#7      TreeVisitor.visitInstanceGet (package:kernel/visitor.dart:215:43)
#8      InstanceGet.accept (package:kernel/ast.dart:4466:44)
#9      RecordNameGet.visitChildren (package:kernel/ast.dart:4293:14)
#10     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560:10)
#11     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150:39)
#12     TreeVisitor.defaultExpression (package:kernel/visitor.dart:199:43)
#13     TreeVisitor.visitRecordNameGet (package:kernel/visitor.dart:344:47)
#14     RecordNameGet.accept (package:kernel/ast.dart:4285:44)
#15     VariableDeclaration.visitChildren (package:kernel/ast.dart:10953:18)
#16     _VariablesInfoCollector.visitVariableDeclaration (package:vm/transformations/type_flow/summary_collector.dart:432:10)
#17     VariableDeclaration.accept (package:kernel/ast.dart:10943:43)
#18     visitList (package:kernel/ast.dart:14607:14)
#19     Block.visitChildren (package:kernel/ast.dart:9362:5)
#20     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560:10)
#21     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150:39)
#22     TreeVisitor.defaultStatement (package:kernel/visitor.dart:348:41)
#23     TreeVisitor.visitBlock (package:kernel/visitor.dart:353:31)
#24     Block.accept (package:kernel/ast.dart:9355:43)
#25     FunctionNode.visitChildren (package:kernel/ast.dart:3852:11)
#26     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560:10)
#27     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150:39)
#28     TreeVisitor.visitFunctionNode (package:kernel/visitor.dart:437:45)
#29     FunctionNode.accept (package:kernel/ast.dart:3839:38)
#30     Procedure.visitChildren (package:kernel/ast.dart:3244:14)
#31     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1560:10)
#32     Visitor.defaultTreeNode (package:kernel/visitor.dart:1150:39)
#33     TreeVisitor.defaultMember (package:kernel/visitor.dart:396:35)
#34     TreeVisitor.visitProcedure (package:kernel/visitor.dart:400:39)
#35     Procedure.accept (package:kernel/ast.dart:3231:40)
#36     new _VariablesInfoCollector (package:vm/transformations/type_flow/summary_collector.dart:341:12)
#37     SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:604:26)
#38     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1579:55)
#39     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:298:42)
#40     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#41     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1473:27)
#42     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1415:7)
#43     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1605:14)
#44     transformComponent (package:vm/transformations/type_flow/transformer.dart:112:20)
#45     runGlobalTransformations (package:vm/kernel_front_end.dart:489:20)
#46     compileToKernel (package:vm/kernel_front_end.dart:408:11)
<asynchronous suspension>
#47     runCompiler (package:vm/kernel_front_end.dart:294:19)
<asynchronous suspension>
#48     main (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/gen_kernel.dart:34:19)
<asynchronous suspension>
Error: AOT compilation failed
Generating AOT kernel dill failed!
```
</details>

And this piece of code: (with the dependency on `package:riverpod` - I can't seem to create a simpler test case)
```dart
import 'package:riverpod/riverpod.dart';

typedef Hello<T> = ({T name});

final gameType = Provider.autoDispose<String>(
  (ref) {
    final type = ref.watch(gameProvider).asData?.value.name;
    if (type == null) {
      return '';
    }
    return 'other';
  },
);

final gameProvider = FutureProvider<Hello>((ref) => (name: 1));
```
<details>
<summary>
results in the following error:
</summary>

```
Crash when compiling package:game_scaffold_dart/src/core/clients/providers.dart:
type '_NullAwareAccessContext<DartType>' is not a subtype of type '_FunctionExpressionContext<DartType>' in type cast

#0      _FlowAnalysisImpl.functionExpression_end (package:_fe_analyzer_shared/src/flow_analysis/flow_analysis.dart:3442:29)
#1      InferenceVisitorImpl.visitFunctionExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:1648:18)
#2      FunctionExpression.accept1 (package:kernel/ast.dart:8754:9)
#3      InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:137:27)
#4      InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:172:40)
#5      InferenceVisitorBase._inferInvocation.inferArgument (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1755:22)
#6      InferenceVisitorBase._inferInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1867:46)
#7      InferenceVisitorBase.inferInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1495:12)
#8      InferenceVisitorBase._inferInstanceMethodInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:2676:40)
#9      InferenceVisitorBase.inferMethodInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:3221:20)
#10     InferenceVisitorImpl.visitExpressionInvocation (package:front_end/src/fasta/type_inference/inference_visitor.dart:3184:12)
#11     ExpressionInvocation.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:1151:20)
#12     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:135:27)
#13     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:172:40)
#14     TypeInferrerImpl.inferFieldInitializer (package:front_end/src/fasta/type_inference/type_inferrer.dart:169:10)
#15     BodyBuilder.finishFields (package:front_end/src/fasta/kernel/body_builder.dart:1012:16)
#16     DietListener._parseFields (package:front_end/src/fasta/source/diet_listener.dart:1126:17)
#17     DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:863:5)
#18     DietListener.endClassFields (package:front_end/src/fasta/source/diet_listener.dart:354:5)
#19     Parser.parseFields (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3403:18)
#20     Parser.parseClassOrMixinOrExtensionOrEnumMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4380:15)
#21     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4004:15)
#22     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2468:13)
#23     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2426:14)
#24     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
#25     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:510:14)
#26     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:390:15)
#27     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1184:12)
<asynchronous suspension>
#28     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:675:7)
<asynchronous suspension>
#29     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:620:7)
<asynchronous suspension>
#30     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#31     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#32     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#33     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#34     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#35     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#36     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:412:11)
<asynchronous suspension>
#37     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:221:45)
<asynchronous suspension>
#38     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:914:37)
```
</details>

Finally I get an analyzer error here: (the dynamic nature is intentional, however I'm not sure if this is intended to be supported)
```dart

final map = <String, Hello>{};

void register<T>(Hello<T> hi) {
  map['hi'] = hi;
  //         ^^^
  // A value of type '({void Function(T) name})' can't be assigned to a variable of type '({void Function(dynamic) name})'.
}

typedef Hello<T> = ({void Function(T) name});

Hello<T> fun<T>(T i) => (name: print);

**Comment by lrhn** [comment]
The last example, wiuth the analyzer error, looks like it's behaving as expected.

Subtyping of records is pointwise covariant, and your `Hello` type alias in the last example is *contravariant* in `T`.

The type `Hello<T>` is `({void Function(T)})` which is a *supertype* of `({void Function(dynamic)})` - because that's how the function types are subtyped.

Try making your map be `final map = <String, Hello<Never>>{};`. Then you can assign any unary function to it (it's calling them which becomes hard).


The other crashes should not happen.

**Comment by johnniwinther** [comment]
This now work in the CFE.

@alexmarkov Can you verify that this works in the VM?

**Comment by alexmarkov** [comment]
I do not see any crashes on the tip of the tree.

However,
<details>
  <summary>example</summary>

```dart
import 'package:riverpod/riverpod.dart';

typedef Hello<T> = ({T name});

final gameType = Provider.autoDispose<String>(
  (ref) {
    final type = ref.watch(gameProvider).asData?.value.name;
    if (type == null) {
      return '';
    }
    return 'other';
  },
);

final gameProvider = FutureProvider<Hello>((ref) => (name: 1));
```
</details>

with `package:riverpod` doesn't compile with a strange error

```
bin/foo.dart:15:53: Error: A value of type '({int name})' can't be returned from a function with return type 'FutureOr<({dynamic name})>'.
final gameProvider = FutureProvider<Hello>((ref) => (name: 1));
```

This error looks incorrect, as `({int name})` is assignable to `({dynamic name})` and `FutureOr<({dynamic name})>`.

@johnniwinther Could you take a look?
