### ISSUE TITLE
secure method of SecureSocket uses private methods of Socket

### ISSUE THREAD

**Issue by LacticWhale** [dart-lang/sdk#50199]
* Dart SDK Version 2.18.1
* Windows
* Issue related to dart core library "dart:io"

This might be a skill issue but I believe what using private methods outside of their class is forbidden. 

Code:
```dart
// main.dart:main
// Create HttpClient object
final client = HttpClient()

// Assign connection factory
..connectionFactory =
      (uri, proxyHost, proxyPort) async {
        // Returns instance of SocksSocket which implements Socket
        final client = SocksTCPClient.connect(
          [ProxySettings(InternetAddress.loopbackIPv4, 1080)],
          InternetAddress(uri.host, type: InternetAddressType.unix),
          uri.port,
        );
        
        // Secure connection after establishing Socks connection
        if(uri.scheme == 'https')
          await SecureSocket.secure(await client, host: uri.host); // <-- Error here

        // SocketConnectionTask implements ConnectionTask<Socket>
        return SocketConnectionTask(client);
  };

// GET request
final request = await client.getUrl(Uri.parse('https://example.com/'));
final response = await request.close();
// Print response
print(await utf8.decodeStream(response));
// Close client
client.close();
```
Error message:
```
Unhandled exception:
NoSuchMethodError: Class 'SocksSocket' has no instance method '_detachRaw'.
Receiver: Instance of 'SocksSocket'
Tried calling: _detachRaw()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      SecureSocket.secure (dart:io/secure_socket.dart:147:45)
#2      main.<anonymous closure> example\client\main.dart:22
<asynchronous suspension>
#3      _ConnectionTarget.connect.<anonymous closure> (dart:_http/http_impl.dart:2456:32)
<asynchronous suspension>
```

`SocksClient` and `SocketConnectionTask` class:
```dart
class SocketConnectionTask implements ConnectionTask<Socket> {
  SocketConnectionTask(this.socket);
  @override
  final Future<Socket> socket;

  @override
  void cancel() => socket.ignore();
}

class SocksSocket with StreamMixin<Uint8List>, SocketMixin, ByteReader {
  /// Internal constructor
  @protected
  SocksSocket.protected(this.socket, this.type);

  final SocksConnectionType type;

  @override
  final Socket socket;

  /// Multi-subscription socket stream.
  Stream<Uint8List>? _broadcast;

  @override
  Stream<Uint8List> get stream => _broadcast ??= socket.asBroadcastStream();
  
  // ...
}
```

**Comment by brianquinlan** [comment]
This pattern is very common in the SDK but it is confusing and we should at least document when we need an exact instance type or any subclass will work.
