### ISSUE TITLE
use_dwarf_stack_traces_flag_test failing on dartkp-weak-asserts-linux-debug-simriscv64

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#50207]
```
...
Unhandled exception:
Expect.equals(at index 0: Expected <_kDartIsolateSnapshotInstructions...>, Found: <stub _iso_stub_AllocateObjectStub...>) fails.
#0      Expect._fail (package:expect/expect.dart:698)
#1      Expect.equals (package:expect/expect.dart:117)
#2      compareTraces (file:///b/s/w/ir/runtime/tests/vm/dart/use_dwarf_stack_traces_flag_test.dart:300)
<asynchronous suspension>
#3      main.<anonymous closure> (file:///b/s/w/ir/runtime/tests/vm/dart/use_dwarf_stack_traces_flag_test.dart:110)
<asynchronous suspension>
#4      withTempDir (file:///b/s/w/ir/runtime/tests/vm/dart/use_flag_test_helper.dart:193)
<asynchronous suspension>
#5      main (file:///b/s/w/ir/runtime/tests/vm/dart/use_dwarf_stack_traces_flag_test.dart:40)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartkp-weak-asserts-linux-debug-simriscv64 vm/dart/use_dwarf_stack_traces_flag_test
```

The bot was offline recently when switching to nnbd. Possibly related to 3b2c41d789aa7aa122c7ff6a33f63b8073717b88. @sstrickl

**Comment by sstrickl** [comment]
Running it locally it seems to be passing, and looking at the current results it seems to be passing. Not sure when that changed, but seems to have been fixed somehow in the meantime.
