### ISSUE TITLE
[dart2wasm] Truncating integer division does not handle dividing by zero

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#50228]
Repro:

```dart
void main() {
  try {
    print(1 ~/ 0);
  } catch (e) {
    print('Division failed');
  }
}
```

JIT output:

```
Division failed
```

dart2wasm output fails with a trap:

```
wasm-function[51]:0x12241: RuntimeError: divide by zero
RuntimeError: divide by zero
    at main (wasm://wasm/000a6576:wasm-function[51]:0x12241)
    at $main (wasm://wasm/000a6576:wasm-function[52]:0x1226c)
    at Module.invoke (/usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/dart2wasm_runtime.mjs:400:28)
    at main (/usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/run_wasm.js:46:21)

1 pending unhandled Promise rejection(s) detected.
```

We may want to fix this as a part of https://dart-review.googlesource.com/c/sdk/+/264460 which refactors truncating div compilation.

**Comment by osa1** [comment]
https://dart-review.googlesource.com/c/sdk/+/264820

**Comment by osa1** [comment]
CL merged.
