### ISSUE TITLE
requestHeapSnapshot causes app-crash if app is in debug mode

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#50226]
Steps:

1. Connect [DevTools](https://github.com/flutter/devtools) on macos to a counter app on macos, in debug mode
2. On Memory > Analysis tap 'Take Snapshot'
3. Observe the application crash and the error in the DevTools console

Version:
```
Flutter 3.5.0-5.0.pre • channel unknown • unknown source
Framework • revision 883c1fe68c (6 days ago) • 2022-10-10 20:07:24 -0400
Engine • revision 623d2d9180
Tools • Dart 2.19.0 (build 2.19.0-297.0.dev) • DevTools 2.18.0
```

Error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: requestHeapSnapshot: (112) Service has disappeared
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1746:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2262:21)
#2      VmService.requestHeapSnapshot (package:vm_service/src/vm_service.dart:2132:7)
#3      HeapSnapshotGraph.getSnapshot (package:vm_service/src/snapshot_graph.dart:336:19)
<asynchronous suspension>
#4      VmServiceWrapper.getHeapSnapshotGraph (package:devtools_app/src/service/vm_service_wrapper.dart:432:12)
<asynchronous suspension>
#5      snapshotMemory (package:devtools_app/src/screens/memory/primitives/memory_utils.dart:12:10)
<asynchronous suspension>
#6      SnapshotTaker.take (package:devtools_app/src/screens/memory/shared/heap/model.dart:210:22)
<asynchronous suspension>
#7      DiffPaneController.takeSnapshot (package:devtools_app/src/screens/memory/panes/diff/controller/diff_pane_controller.dart:55:22)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      AllocationProfileTableViewController.refresh (package:devtools_app/src/screens/memory/panes/allocation_profile/allocation_profile_table_view_controller.dart:61:43)
#1      AllocationProfileTableViewController.initialize.<anonymous closure> (package:devtools_app/src/screens/memory/panes/allocation_profile/allocation_profile_table_view_controller.dart:42:7)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:375:24)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:489:5)
#4      IsolateManager.handleVmServiceClosed (package:devtools_app/src/service/isolate_manager.dart:222:22)
#5      ServiceConnectionManager.vmServiceClosed (package:devtools_app/src/service/service_manager.dart:338:20)
#6      ServiceConnectionManager.vmServiceOpened.<anonymous closure> (package:devtools_app/src/service/service_manager.dart:223:36)
<asynchronous suspension>

flutter: [ERROR]: WebSocketChannelException: WebSocketChannelException: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 60790
```

**Comment by polina-c** [comment]
Got it again:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: requestHeapSnapshot: (112) Service has disappeared
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1746:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2262:21)
#2      VmService.requestHeapSnapshot (package:vm_service/src/vm_service.dart:2132:7)
#3      HeapSnapshotGraph.getSnapshot (package:vm_service/src/snapshot_graph.dart:336:19)
<asynchronous suspension>
#4      VmServiceWrapper.getHeapSnapshotGraph (package:devtools_app/src/service/vm_service_wrapper.dart:432:12)
<asynchronous suspension>
#5      snapshotMemory (package:devtools_app/src/screens/memory/primitives/memory_utils.dart:12:10)
<asynchronous suspension>
#6      _HeapTreeViewState._takeHeapSnapshot (package:devtools_app/src/screens/memory/memory_heap_tree_view.dart:872:19)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      AllocationProfileTableViewController.refresh (package:devtools_app/src/screens/memory/panes/allocation_profile/allocation_profile_table_view_controller.dart:61:43)
#1      AllocationProfileTableViewController.initialize.<anonymous closure> (package:devtools_app/src/screens/memory/panes/allocation_profile/allocation_profile_table_view_controller.dart:42:7)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:375:24)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:489:5)
#4      IsolateManager.handleVmServiceClosed (package:devtools_app/src/service/isolate_manager.dart:222:22)
#5      ServiceConnectionManager.vmServiceClosed (package:devtools_app/src/service/service_manager.dart:338:20)
#6      ServiceConnectionManager.vmServiceOpened.<anonymous closure> (package:devtools_app/src/service/service_manager.dart:223:36)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      AllocationProfileTracingViewController.initialize.<anonymous closure> (package:devtools_app/src/screens/memory/panes/allocation_tracing/allocation_profile_tracing_view_controller.dart:266:74)
#1      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:375:24)
#2      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:489:5)
#3      IsolateManager.handleVmServiceClosed (package:devtools_app/src/service/isolate_manager.dart:222:22)
#4      ServiceConnectionManager.vmServiceClosed (package:devtools_app/src/service/service_manager.dart:338:20)
#5      ServiceConnectionManager.vmServiceOpened.<anonymous closure> (package:devtools_app/src/service/service_manager.dart:223:36)
<asynchronous suspension>

flutter: [ERROR]: WebSocketChannelException: WebSocketChannelException: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 57058
```

**Comment by polina-c** [comment]
Found that snapshot works well for profile mode and fails for debug mode.

**Comment by polina-c** [comment]
When the crash happens, the app console gets message `Lost connection to device.` and disconnects.

**Comment by bkonyi** [comment]
My local engine builds finally finished. Here's the crash:

```
Process 54029 stopped
* thread #3, name = 'io.flutter.ui', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x000000011a35bafe FlutterMacOS`dart::BaseGrowableArray<dart::ObjectSlot, dart::ZoneAllocated, dart::Zone>::begin(this=0x0000000000000000) const at growable_array.h:207:36
   204 	  }
   205 	
   206 	  T* begin() { return &data_[0]; }
-> 207 	  const T* begin() const { return &data_[0]; }
   208 	
   209 	  T* end() { return &data_[length_]; }
   210 	  const T* end() const { return &data_[length_]; }
Target 0: (counter) stopped.
(lldb) bt
* thread #3, name = 'io.flutter.ui', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x000000011a35bafe FlutterMacOS`dart::BaseGrowableArray<dart::ObjectSlot, dart::ZoneAllocated, dart::Zone>::begin(this=0x0000000000000000) const at growable_array.h:207:36
    frame #1: 0x000000011a35b371 FlutterMacOS`dart::Pass1Visitor::VisitObject(this=0x0000700005ac0b88, obj=(tagged_pointer_ = 4513999441)) at object_graph.cc:951:23
    frame #2: 0x000000011a5b9fad FlutterMacOS`dart::Page::VisitObjects(this=0x000000010d080000, visitor=0x0000700005ac0b88) const at page.cc:169:14
    frame #3: 0x000000011a5bdda1 FlutterMacOS`dart::PageSpace::VisitObjects(this=0x00007fd77f8e5cc0, visitor=0x0000700005ac0b88) const at pages.cc:603:16
    frame #4: 0x000000011a5994f7 FlutterMacOS`dart::Heap::VisitObjects(this=0x00007fd77f8e5a00, visitor=0x0000700005ac0b88) at heap.cc:233:14
    frame #5: 0x000000011a59a0ff FlutterMacOS`dart::HeapIterationScope::IterateObjects(this=0x0000700005ac0d00, visitor=0x0000700005ac0b88) const at heap.cc:308:10
    frame #6: 0x000000011a353730 FlutterMacOS`dart::HeapSnapshotWriter::Write(this=0x0000700005ac0e10) at object_graph.cc:1586:15
    frame #7: 0x000000011a4c1de9 FlutterMacOS`dart::RequestHeapSnapshot(thread=0x00007fd77f855400, js=0x0000700005ac10e8) at service.cc:4584:12
    frame #8: 0x000000011a4b1c8a FlutterMacOS`dart::Service::InvokeMethod(I=0x00007fd77f8e7000, msg=0x00007fd76f08f050, parameters_are_dart_objects=false) at service.cc:1040:7
    frame #9: 0x000000011a4b2abf FlutterMacOS`dart::Service::HandleIsolateMessage(isolate=0x00007fd77f8e7000, msg=0x00007fd76f08f050) at service.cc:1084:38
    frame #10: 0x000000011a147b5a FlutterMacOS`dart::IsolateMessageHandler::HandleMessage(this=0x00007fd77f02de50, message=unique_ptr<dart::Message, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::Message> > @ 0x0000700005ac1e70) at isolate.cc:1380:33
    frame #11: 0x000000011a1ecaa2 FlutterMacOS`dart::MessageHandler::HandleMessages(this=0x00007fd77f02de50, ml=0x0000700005ac1f00, allow_normal_messages=false, allow_multiple_normal_messages=false) at message_handler.cc:240:16
    frame #12: 0x000000011a1ed259 FlutterMacOS`dart::MessageHandler::HandleOOBMessages(this=0x00007fd77f02de50) at message_handler.cc:349:10
    frame #13: 0x000000011a521429 FlutterMacOS`dart::Thread::HandleInterrupts(this=0x00007fd77f855400) at thread.cc:471:39
    frame #14: 0x000000011a4967ec FlutterMacOS`dart::DRT_HelperInterruptOrStackOverflow(isolate=0x00007fd77f8e7000, thread=0x00007fd77f855400, zone=0x0000700005ac21e8, arguments=NativeArguments @ 0x0000700005ac20d0) at runtime_entry.cc:3039:46
    frame #15: 0x000000011a49655c FlutterMacOS`dart::DRT_InterruptOrStackOverflow(arguments=NativeArguments @ 0x0000700005ac26c0) at runtime_entry.cc:2984:1
```

@rmacnak-google is more familiar with this code than I am, so I'll see if he can take a closer look.

**Comment by rmacnak-google** [comment]
The kernel constant loader creates instances of _ImmutableLinkedHashMap/Set without ensuring the class is finalized
