### ISSUE TITLE
[dart2wasm] Incorrect compilation of dynamic invocation of `call`

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#50307]
```dart
class A {
  Function get call => () {
        print('hi');
      };
}

void main() {
  try {
    (A() as dynamic).call();
  } catch (e) {
    print(e);
  }
}
```

AOT output:

```
hi
```

dar2wasm output:

```
wasm-function[51]:0x158d5: RuntimeError: illegal cast
RuntimeError: illegal cast
    at main (wasm://wasm/000b1c12:wasm-function[51]:0x158d5)
    at $main (wasm://wasm/000b1c12:wasm-function[52]:0x15907)
    at Module.invoke (/usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/dart2wasm_runtime.mjs:400:28)
    at main (/usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/run_wasm.js:46:21)
```

The problem starts at these lines which assume receiver of a dynamic invocation is always a closure: https://github.com/dart-lang/sdk/blob/142bf6944001ddb68a3fe079ad20523df57f347a/pkg/dart2wasm/lib/code_generator.dart#L1482-L1485

I think that block of code is wrong and should just be removed. Removing that block of code fixes compilation of this:

```dart
class A {
  void call() {
    print('hi');
  }
}

void main() {
  try {
    (A() as dynamic).call();
  } catch (e) {
    print(e);
  }
}
```

However original repro is still miscompiled and it prints this:

```
NoSuchMethodError: method not found: 'call'
Receiver: Instance of 'A'
Arguments: []
```

So a second problem seems to be in `emitDynamicCall` when searching for a matching member. In addition to a member method we should look for member getters and fields. We should also add a getter to [`_Function`][1]: `_Function get call => this;` so that the member search won't have to special-case functions.

[1]: https://github.com/dart-lang/sdk/blob/main/sdk/lib/_internal/wasm/lib/function.dart#L8

**Comment by osa1** [comment]
Now that implementation of dynamic invocations is complete (with https://dart-review.googlesource.com/c/sdk/+/278505) and we added a `call` member to `Function` we can finally remove the special case shown above.

(I can't figure out how to create a dependent CL so can't test this yet)

After the special case removed, the last missing piece is in a dynamic invocation of a member (`x.f(...)` when `x` is `dynamic`) we to implicitly use the `call` member of value of `x.f` if it exists. This is already broken today so I think we can remove the special case after CL 278505 is merged and close this issue.

**Comment by osa1** [comment]
> After the special case removed, the last missing piece is in a dynamic invocation of a member (`x.f(...)` when `x` is dynamic) is to implicitly use the call member of value of `x.f` if it exists. This is already broken today so I think we can remove the special case after CL 278505 is merged and close this issue.

To elaborate, the front-end adds a `call` when an expression needs to have a function type but it doesn't. For example, with this definition:

```dart
class A {
  void call() {}
}
```

RHS of an assignment like `void Function() x = A();` becomes `A().call`. Similarly, `A()()` becomes `A().call()`.

This also happens when the expression has type `dynamic`: `x()` becomes `x.call()` when `x : dynamic`.

As far as I can see, the only case where a `call` is not introduced by the front-end is in a dynamic invocation of a member: `x.a()` when `x : dynamic`.

So in a forwarder for an invocation, when the member is found to be a getter or field, we need to get the field/getter value, and then use the value's `call` member for the invocation.

*Why does the front-end not add a `call` in dynamic invocations of members?* In Dart/kernel level, these two evaluate `a`, `a.b`, and `x` differently:

- `a.b(x)`: `a`, `x`, `a.b`
- `a.b.call(x)`: `a`, `a.b`, `x`

When there is no member access, adding a `call` does not change evaluation order of the function relative to its args:

- `a(x)`: `a`, `x`
- `a.call(x)`: `a`, `x`

So it's OK to add a `call` in direct invocations, but doing the same in member invocations changes evaluation order.

<details>

<summary>Repro</summary>

```dart
class A {
  A() {
    print('A constructed');
  }

  void Function(int) get b {
    print('A.b called');
    return (int i) {
      print('Return value of a.b called');
    };
  }

  void call(int i) {
    print('A called');
  }
}

int arg() {
  print('Arg evaluated');
  return 123;
}

void main() {
  print('----- a.b(x) -----');
  (A() as dynamic).b(arg());

  print('----- a.b.c(x) -----');
  (A() as dynamic).b.call(arg());

  print('----- a(x) -----');
  A()(arg());

  print('----- a.call(x) -----');
  A().call(arg());
}
```

</details>

**Comment by osa1** [comment]
> Now that implementation of dynamic invocations is complete (with https://dart-review.googlesource.com/c/sdk/+/278505) and we added a call member to Function we can finally remove the special case shown above.
> 
> (I can't figure out how to create a dependent CL so can't test this yet)

I managed to create a dependent CL and test removing the special case.

- In main branch, removing the special case fixes 34 tests, breaks 128 tests.
- With CL 278505, it fixes 44 tests, breaks 65 tests.

Those 65 failures all seem to be one bug, which causes runtime cast to fail when casting return value of `call` when the receiver is a lambda to the context struct of the closure. Minimal repro:

```dart
void main() {
  var i = 123;
  dynamic f = () { print("i = $i"); };
  f();
}
```

Output:

```
wasm-function[785]:0x2263b: RuntimeError: illegal cast
RuntimeError: illegal cast
    at main closure at file:///usr/local/google/home/omersa/dart/sdk_wasm/test/test.dart:3:15 (wasm://wasm/000b18a6:wasm-function[785]:0x2263b)
    at dynamic call entry (wasm://wasm/000b18a6:wasm-function[786]:0x22676)
    at method forwarder for 'call' (wasm://wasm/000b18a6:wasm-function[788]:0x226d2)
    at main (wasm://wasm/000b18a6:wasm-function[53]:0x15b62)
    at main tear-off (wasm://wasm/000b18a6:wasm-function[55]:0x15b74)
    at _invokeMain (wasm://wasm/000b18a6:wasm-function[65]:0x15e51)
    at Module.invoke (/usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/dart2wasm_runtime.mjs:416:28)
    at main (/usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/run_wasm.js:50:21)
```

The failing cast is generated here: https://github.com/dart-lang/sdk/blob/77b5d635a7963633dfc2242575ffb71422de2908/pkg/dart2wasm/lib/code_generator.dart#L533-L566

If I could see the runtime Wasm type of the object passed to this cast that would be really helpful..

**Comment by osa1** [comment]
With the bug above fixed, removing the special case fixes ~60 tests and breaks 3: https://dart-ci.firebaseapp.com/cl/278514/4.

The last issue is we fail to distinguish the cases where (1) a named parameter is not passed (2) a named parameter is passed `null`. I knew about this issue CL 278505 so I will fix this now.

Repro:

```dart
dynamic test({value = 100}) => value;

void main() {
  print((test as dynamic)(value: null));
}
```

Prints `100` instead of `null`.

**Comment by osa1** [comment]
The bug above fixed, but we also need to implement the two missing pieces in CL 278505 which are dynamic call vtable entries for (1) instantiation constant closures (2) normal instantiation (not constant) closures.

Repro for non-constant instantiation closures:

```dart
void main() {
  T f<T>(T a) => a;

  dynamic Function(dynamic) dd2d = f; // instantiates f with dynamic
  (dd2d as dynamic)(40);
}
```

For generating an instantiation constant we just move the generic function to the top-level:

```dart
T f<T>(T a) => a;

void main() {
  dynamic Function(dynamic) dd2d = f; // instantiates f with dynamic
  (dd2d as dynamic)(40);
}
```

I tried to implement the instantiation constant entries in https://github.com/osa1/sdk/commit/93e8aa1d2a20542e65f79ac81c7507984ace36e5, but it broke a few things: https://dart-ci.firebaseapp.com/cl/278505/36.

**Comment by osa1** [comment]
Non-constant instantiation closure entry points implemented in https://dart-review.googlesource.com/c/sdk/+/278505.

**Comment by osa1** [comment]
All done.

- https://dart-review.googlesource.com/c/sdk/+/278505 implements dynamic invocations of fields/getters. This fixes 6 tests.
- https://dart-review.googlesource.com/c/sdk/+/278514 depends on the CL above and removes the special case for `.call`. This fixes ~50 tests.
