### ISSUE TITLE
Crash while compiling app with dart2js and platform dill

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#50313]
I am attempting to pre-compile platform kernels with the flutter web engine, see https://github.com/flutter/flutter/issues/99161

After building the platform dill files in the engine, when attempting to pass them into dart2js via the `--platform-binaries` flag causes dart2js to crash. The flutter tool actually does the compilation in two phases, compiling the app with to an `app.dill` (via the `--cfe-only` flag) and then compiling an `app.dill` to `main.dart.js`. The second compilation crashes when I attempt it. 

The first command looks like the following on my machine (which is an arm64 Mac):

```
/Users/jacksongardner/Source/flutter/engine/src/flutter/prebuilts/macos-x64/dart-sdk/bin/dart --disable-dart-dev /Users/jacksongardner/Source/flutter/engine/src/flutter/prebuilts/macos-x64/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/Users/jacksongardner/Source/flutter/engine/src/out/wasm_release/flutter_web_sdk/kernel --native-null-assertions -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true --no-source-maps -o /Users/jacksongardner/Source/sample/.dart_tool/flutter_build/1f22e0100de7e09c584c46dd5596b7c6/app.dill --packages=.dart_tool/package_config.json --cfe-only /Users/jacksongardner/Source/sample/.dart_tool/flutter_build/1f22e0100de7e09c584c46dd5596b7c6/main.dart
```

The second command looks like this:

```
/Users/jacksongardner/Source/flutter/engine/src/flutter/prebuilts/macos-x64/dart-sdk/bin/dart --disable-dart-dev /Users/jacksongardner/Source/flutter/engine/src/flutter/prebuilts/macos-x64/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/Users/jacksongardner/Source/flutter/engine/src/out/wasm_release/flutter_web_sdk/kernel --native-null-assertions -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true --no-source-maps -O4 -o /Users/jacksongardner/Source/sample/.dart_tool/flutter_build/1f22e0100de7e09c584c46dd5596b7c6/main.dart.js /Users/jacksongardner/Source/sample/.dart_tool/flutter_build/1f22e0100de7e09c584c46dd5596b7c6/app.dill
```

The second invocation results in a compiler crash, with the following dumped to stderr:

```
Uncaught exception in diagnostic handler: FormatException: Unexpected extension byte (at offset 0)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      Utf8BytesSourceFile.slowText (package:compiler/src/io/source_file.dart:201:10)
#3      CachingUtf8BytesSourceFile.slowText (package:compiler/src/io/source_file.dart:241:34)
#4      SourceFile.lineStarts (package:compiler/src/io/source_file.dart:66:55)
#5      SourceFile.kernelSource (package:compiler/src/io/source_file.dart:32:9)
#6      SourceFile.getLocationMessage (package:compiler/src/io/source_file.dart:113:37)
#7      FormattingDiagnosticHandler.report (package:compiler/src/source_file_provider.dart:251:14)
#8      Compiler.callUserHandler.<anonymous closure> (package:compiler/src/compiler.dart:867:17)
#9      CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#10     Compiler.callUserHandler (package:compiler/src/compiler.dart:866:23)
#11     Compiler._reportDiagnosticMessage (package:compiler/src/compiler.dart:858:7)
#12     Compiler.reportDiagnostic (package:compiler/src/compiler.dart:845:5)
#13     DiagnosticReporter._reportDiagnostic (package:compiler/src/diagnostics/diagnostic_listener.dart:122:15)
#14     DiagnosticReporter.onError (package:compiler/src/diagnostics/diagnostic_listener.dart:266:11)
#15     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:270:27)
<asynchronous suspension>
#16     main (package:compiler/src/dart2js.dart:1424:3)
<asynchronous suspension>

The compiler crashed: Null check operator used on a null value
#0      orderByFileOffset (package:compiler/src/kernel/env.dart:268:24)
#1      insertionSort (package:collection/src/algorithms.dart:173:31)
#2      mergeSort (package:collection/src/algorithms.dart:222:5)
#3      KClassEnvImpl._ensureMaps (package:compiler/src/kernel/env.dart:396:5)
#4      KClassEnvImpl.forEachMember (package:compiler/src/kernel/env.dart:410:5)
#5      KernelToElementMap._forEachClassMember (package:compiler/src/kernel/element_map_impl.dart:807:9)
#6      KernelElementEnvironment.forEachClassMember (package:compiler/src/kernel/element_map_impl.dart:1965:16)
#7      KernelFrontendStrategy._validateInterceptorImplementsAllObjectMethods (package:compiler/src/kernel/kernel_strategy.dart:122:24)
#8      KernelFrontendStrategy.onResolutionStart (package:compiler/src/kernel/kernel_strategy.dart:113:5)
#9      Compiler.computeClosedWorld (package:compiler/src/compiler.dart:379:22)
#10     Compiler.produceClosedWorld (package:compiler/src/compiler.dart:604:11)
#11     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:726:15)
<asynchronous suspension>
#12     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:348:7)
<asynchronous suspension>
#13     Compiler.runInternal (package:compiler/src/compiler.dart:347:5)
<asynchronous suspension>
#14     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:268:11)
<asynchronous suspension>
#15     main (package:compiler/src/dart2js.dart:1424:3)
<asynchronous suspension>
```

I attached the dart debugger and did a little bit of inspection of what was going on. It appears `KClassEnvImpl` is attempting to sort its members (fields and procedures) by their location. The comparator `orderByFileOffset` assumes the location of the member nodes is non-null, but they are in fact null. I'm assuming this is because they are coming from a kernel file rather than source.

**Comment by sigmundch** [comment]
@eyebrowsoffire - can you also share the command to produce the platform.dill?

Typically with compile_platform, the source information as well as the full contents of the body of each element is preserved. The kernel-worker defaults to produce summaries, if I recall correctly, so you may need to pass extra flags to avoid trimming the .dill file.

**Comment by sigmundch** [comment]
Unrelated: you may be able to use `dart-sdk/bin/dartaotruntime` instead of `dart-sdk/bin/dart --disable-dart-dev`

**Comment by eyebrowsoffire** [comment]
Ahh, passing `--no-summary-only` to `kernel_worker` fixed the issue, I can compile just fine now. Thank you! If that is a hard requirement of `dart2js`, it would be nice if it had a more elegant and descriptive failure than a crash.
