### ISSUE TITLE
Stack traces on web aren't async stack traces

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#50336]
Stack traces on web don't do the nice async logic that they do on the VM.

For example:

```dart
void main() async {
  await Future.delayed(const Duration(seconds: 1));
  await test1();
}

Future<void> test1() async {
  await Future.delayed(const Duration(seconds: 1));
  await test2();
}

Future<void> test2() async {
  await Future.delayed(const Duration(seconds: 1));
  throw 'oh no';
}
```

On web, I get:

```
ianh-macbookpro:webassert ianh$ flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             341ms
This app is linked to the debug service: ws://127.0.0.1:49704/IjRCCsaT0wY=/ws
Debug service listening on ws://127.0.0.1:49704/IjRCCsaT0wY=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:49704/IjRCCsaT0wY=
Flutter Web Bootstrap: Programmatic
Error: oh no
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/webassert/main.dart 13:3                                             test2
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1660:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 767:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 796:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 558:7                                     [_complete]
dart-sdk/lib/async/future.dart 421:15                                         <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19       internalCallback
```

...which doesn't tell me that test2 was called from test1. Contrast to what we get on VM:

```
ianh-macbookpro:webassert ianh$ flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-000C60981432801E }
{ platform:macOS, arch:x86_64, id:00006000-000C60981432801E }
Building macOS application...                                           
Syncing files to device macOS...                                     3ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:49757/kX6Y3l6Dmb8=/
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: oh no
#0      test2 (package:webassert/main.dart:13:3)
<asynchronous suspension>
#1      test1 (package:webassert/main.dart:8:3)
<asynchronous suspension>
#2      main (package:webassert/main.dart:3:3)
<asynchronous suspension>
```

**Comment by lrhn** [comment]
The stack traces are delivered by the browser.

The V8 engine does have some ability to capture async stack traces (https://v8.dev/docs/stack-trace-api), but that probably requires use to use the JavaScript `await` on a JavaScript `Promise` for it to work.

**Comment by mnordine** [comment]
I thought the plan was to use `Promise` after support for IE 11 was dropped?

**Comment by yjbanov** [comment]
Many async operations preserve the zone when they hop from one microtask to the next, which I think can be used to track async stack traces without any assistance from the VM.

**Comment by nshahan** [comment]
Looks related to or a duplicate of https://github.com/dart-lang/sdk/issues/40117.
