### ISSUE TITLE
ast_to_text fails on not-fully-linked kernel

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#50368]
```dart
...
Reference to dart:core::DateTime::@constructors::utc is not bound to an AST node. A member was expected
#0      Reference.asMember (package:kernel/canonical_name.dart:517:7)
#1      ConstructorTearOffConstant.target (package:kernel/ast.dart:14004:40)
#2      ConstructorTearOffConstant.visitChildren (package:kernel/ast.dart:14011:5)
#3      ConstantNamer.getName (package:kernel/text/ast_to_text.dart:61:18)
#4      NameSystem.nameConstant (package:kernel/text/ast_to_text.dart:213:51)
#5      Printer.writeConstantReference (package:kernel/text/ast_to_text.dart:2765:30)
#6      Printer.visitConstantExpression (package:kernel/text/ast_to_text.dart:2770:5)
#7      ConstantExpression.accept (package:kernel/ast.dart:8811:44)
#8      Printer.writeNode (package:kernel/text/ast_to_text.dart:673:12)
#9      Printer.writeExpression (package:kernel/text/ast_to_text.dart:1064:5)
#10     Printer.visitConditionalExpression (package:kernel/text/ast_to_text.dart:1663:5)
#11     ConditionalExpression.accept (package:kernel/ast.dart:7056:44)
#12     Printer.writeNode (package:kernel/text/ast_to_text.dart:673:12)
#13     Printer.writeExpression (package:kernel/text/ast_to_text.dart:1064:5)
#14     Printer.visitFunctionInvocation (package:kernel/text/ast_to_text.dart:1521:5)
#15     FunctionInvocation.accept (package:kernel/ast.dart:6090:44)
#16     Printer.writeNode (package:kernel/text/ast_to_text.dart:673:12)
#17     Printer.writeExpression (package:kernel/text/ast_to_text.dart:1064:5)
#18     Printer.visitReturnStatement (package:kernel/text/ast_to_text.dart:2404:7)
#19     ReturnStatement.accept (package:kernel/ast.dart:10372:43)
#20     Printer.writeNode (package:kernel/text/ast_to_text.dart:673:12)
#21     List.forEach (dart:core-patch/growable_array.dart)
#22     Printer.writeFunctionBody (package:kernel/text/ast_to_text.dart:838:23)
#23     Printer.writeFunction (package:kernel/text/ast_to_text.dart:803:7)
#24     Printer.visitProcedure (package:kernel/text/ast_to_text.dart:1204:9)
#25     Procedure.accept (package:kernel/ast.dart:3231:40)
#26     Printer.writeNode (package:kernel/text/ast_to_text.dart:673:12)
#27     List.forEach (dart:core-patch/growable_array.dart:416:8)
#28     Printer.writeStandardLibraryContent (package:kernel/text/ast_to_text.dart:508:24)
#29     Printer.writeComponentFile (package:kernel/text/ast_to_text.dart:584:13)
#30     writeComponentToText (package:kernel/kernel.dart:86:8)
#31     main (google3:///third_party/dart/vm/bin/dump_kernel.dart:56:3)
#32     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:12)
```

I think that in general `ast_to_text.dart` takes precautions against unwrapping possibly unlinked references, but it seems that the `ConstructorTearOffConstant.visitChildren` (and other similar methods) don't take similar precautions. 

/cc @johnniwinther @chloestefantsova @jensjoha

**Comment by johnniwinther** [comment]
The problem is that `acceptReference` calls are done on the node and not on the reference itself, which doesn't preclude dereference of unbound references.
