### ISSUE TITLE
Analyzer throws/terminates on invalid constructor redirect

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#50384]
Given this invalid code:

```dart
class A {
  A.fromJsonString(String json):this.fromJson()
  A.fromJson(Map<String, Object?> json) {}
}
```

The server terminates with an unhandled error:

```
[12:14:08 PM] [Analyzer] [Error] Unhandled exception:
UnimplementedError: (RedirectingConstructorInvocationImpl) this.fromJson()
#0      ResolverVisitor._reportNotEnoughPositionalArguments (package:analyzer/src/generated/resolver.dart:3424:7)
#1      ResolverVisitor.resolveArgumentsToParameters (package:analyzer/src/generated/resolver.dart:3349:9)
#2      ElementResolver._resolveArgumentsToFunction (package:analyzer/src/generated/element_resolver.dart:446:28)
#3      ElementResolver.visitRedirectingConstructorInvocation (packag…
```

The error looks to be coming from https://github.com/dart-lang/sdk/blob/d27d20610833e20d262c3d6f94139583b0f9c76f/pkg/analyzer/lib/src/generated/resolver.dart#L3424

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
The method was added in 0b5d9082210da3c4e588348dfe23b3d495384ffa.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/268060

**Comment by DanTup** [comment]
Thanks!
