### ISSUE TITLE
Failed to memory map snapshot in Flutter

### ISSUE THREAD

**Issue by iSWATxJOKERi** [dart-lang/sdk#50451]
Hi, how's it going, I posted this issue in the flutter repo but posting here just in case also. I had been using flutter 2.x.x for a while now and started getting build errors when trying to `flutter run`. So I decided to upgrade but came across some issues doing so and decide to just remove the flutter sdk and install a new one and now coming up against these errors for the past two days now where it keeps saying `Failed to memory map snapshot` :( .
No matter how many times I remove the `/bin/cache` directory and re run `flutter doctor` still get the same thing.

## Steps to Reproduce

1. Install `wsl` distro: `ubuntu20.04`
2. `git clone https://github.com/flutter/flutter.git -b stable`
3. `flutter precache`

## Logs

<details>
<summary>Logs</summary>

```
flutter precache
Downloading Linux x64 Dart SDK from Flutter engine 857bd6b74c5eb56151bfafe91e7fa6a82b6fee25...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  204M  100  204M    0     0  23.8M      0  0:00:08  0:00:08 --:--:-- 48.2M
Building flutter tool...
../../runtime/bin/snapshot_utils.cc: 153: error: Failed to memory map snapshot: /home/iswatxjokeri/Flutter/Sdk/bin/cache/dart-sdk/bin/snapshots/kernel-service.dart.snapshot

version=2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "linux_x64"
pid=25905, thread=25908, isolate_group=(nil)((nil)), isolate=(nil)((nil))
isolate_instructions=0, vm_instructions=7f2d9214d100
  pc 0x00007f2d923b20fc fp 0x00007f2d8f66fa50 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x00007f2d9214d2b4 fp 0x00007f2d8f66fb30 dart::Assert::Fail(char const*, ...) const+0x84
  pc 0x00007f2d9212450d fp 0x00007f2d8f66fbd0 dart::bin::Snapshot::TryReadAppSnapshot(char const*, bool, bool)+0x28d
  pc 0x00007f2d92128561 fp 0x00007f2d8f66fc70 /home/iswatxjokeri/Flutter/Sdk/bin/cache/dart-sdk/bin/dart+0x1eab561
  pc 0x00007f2d9230cc46 fp 0x00007f2d8f66fd00 /home/iswatxjokeri/Flutter/Sdk/bin/cache/dart-sdk/bin/dart+0x208fc46
  pc 0x00007f2d9243b238 fp 0x00007f2d8f66fd80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x148
  pc 0x00007f2d9243b68d fp 0x00007f2d8f66fdb0 dart::ThreadPool::Worker::Main(unsigned long)+0x6d
  pc 0x00007f2d923ae2d8 fp 0x00007f2d8f66fe70 /home/iswatxjokeri/Flutter/Sdk/bin/cache/dart-sdk/bin/dart+0x21312d8
-- End of DumpStackTrace
/home/iswatxjokeri/Flutter/Sdk/bin/internal/shared.sh: line 165: 25905 Aborted                 (core dumped) "$DART" --verbosity=error --disable-dart-dev $FLUTTER_TOOL_ARGS --snapshot="$SNAPSHOT_PATH" --packages="$FLUTTER_TOOLS_DIR/.dart_tool/package_config.json" --no-enable-mirrors "$SCRIPT_PATH"
```

```
iswatxjokeri@DESKTOP-5SM2V4Q:~/Flutter/Sdk$ flutter doctor -v
Building flutter tool...
../../runtime/bin/snapshot_utils.cc: 153: error: Failed to memory map snapshot: /home/iswatxjokeri/Flutter/Sdk/bin/cache/dart-sdk/bin/snapshots/kernel-service.dart.snapshot

version=2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "linux_x64"
pid=26126, thread=26129, isolate_group=(nil)((nil)), isolate=(nil)((nil))
isolate_instructions=0, vm_instructions=7fa05a173100
  pc 0x00007fa05a3d80fc fp 0x00007fa05766fa50 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x00007fa05a1732b4 fp 0x00007fa05766fb30 dart::Assert::Fail(char const*, ...) const+0x84
  pc 0x00007fa05a14a50d fp 0x00007fa05766fbd0 dart::bin::Snapshot::TryReadAppSnapshot(char const*, bool, bool)+0x28d
  pc 0x00007fa05a14e561 fp 0x00007fa05766fc70 /home/iswatxjokeri/Flutter/Sdk/bin/cache/dart-sdk/bin/dart+0x1eab561
  pc 0x00007fa05a332c46 fp 0x00007fa05766fd00 /home/iswatxjokeri/Flutter/Sdk/bin/cache/dart-sdk/bin/dart+0x208fc46
  pc 0x00007fa05a461238 fp 0x00007fa05766fd80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x148
  pc 0x00007fa05a46168d fp 0x00007fa05766fdb0 dart::ThreadPool::Worker::Main(unsigned long)+0x6d
  pc 0x00007fa05a3d42d8 fp 0x00007fa05766fe70 /home/iswatxjokeri/Flutter/Sdk/bin/cache/dart-sdk/bin/dart+0x21312d8
-- End of DumpStackTrace
/home/iswatxjokeri/Flutter/Sdk/bin/internal/shared.sh: line 165: 26126 Aborted                 (core dumped) "$DART" --verbosity=error --disable-dart-dev $FLUTTER_TOOL_ARGS --snapshot="$SNAPSHOT_PATH" --packages="$FLUTTER_TOOLS_DIR/.dart_tool/package_config.json" --no-enable-mirrors "$SCRIPT_PATH"
```

</details>

**Comment by iSWATxJOKERi** [comment]
I reinstalled my Ubuntu 20.04 distro but still getting the snapshot error. I can run `flutter doctor -v` though:

```
iswatxjokeri@DESKTOP-5SM2V4Q:/mnt/c/Projects/lfg/frontend$ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.8, on Ubuntu 20.04.5 LTS 4.4.0-19041-Microsoft, locale C.UTF-8)
    • Flutter version 3.3.8 on channel stable at /home/iswatxjokeri/Flutter/Sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (4 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/iswatxjokeri/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /home/iswatxjokeri/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_352-8u352-ga-1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /mnt/c/Program Files/Google/Chrome/Application/chrome.exe

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 20.04.5 LTS 4.4.0-19041-Microsoft
    • Chrome (web)                 • chrome        • web-javascript • 

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

<details>
<summary> Logs </summary>

```
[  +86 ms] ../../runtime/bin/snapshot_utils.cc: 153: error: Failed to memory map snapshot: /home/iswatxjokeri/Flutter/Sdk/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot
[   +3 ms] ===== CRASH =====
[        ] si_signo=Segmentation fault(11), si_code=1, si_addr=0x10
[        ] Aborting re-entrant request for stack trace.
[   +8 ms] the Dart compiler exited unexpectedly.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:817:13)
           #2      _rootRun (dart:async/zone.dart:1383:47)
           #3      _CustomZone.run (dart:async/zone.dart:1293:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:154:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1383:47)
           #14     _CustomZone.run (dart:async/zone.dart:1293:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1383:47)
           #26     _CustomZone.run (dart:async/zone.dart:1293:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:630:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2331:21)
           #35     _rootRunUnary (dart:async/zone.dart:1407:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:648:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:596:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1856:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1315:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
           #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
           
           
[   +6 ms] the Dart compiler exited unexpectedly.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:817:13)
           #2      _rootRun (dart:async/zone.dart:1383:47)
           #3      _CustomZone.run (dart:async/zone.dart:1293:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:154:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1383:47)
           #14     _CustomZone.run (dart:async/zone.dart:1293:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1383:47)
           #26     _CustomZone.run (dart:async/zone.dart:1293:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:630:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2331:21)
           #35     _rootRunUnary (dart:async/zone.dart:1407:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:648:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:596:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1856:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1315:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
           #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
           
           
[  +11 ms] --------- beginning of main
           11-13 08:41:31.647 I/SmartDevice( 1446): [CleanBufferedLogsService] Task upload_buffered_logs scheduled!
[  +49 ms] executing: /home/iswatxjokeri/Android/Sdk/platform-tools/adb version
[  +87 ms] Android Debug Bridge version 1.0.41
           Version 33.0.3-8952118
           Installed as /home/iswatxjokeri/Android/Sdk/platform-tools/adb
[   +6 ms] executing: /home/iswatxjokeri/Android/Sdk/platform-tools/adb start-server
[ +114 ms] ensureAnalyticsSent: 271ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] ensureAnalyticsSent: 272ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[   +2 ms] Building APK
[  +46 ms] Running Gradle task 'assembleDebug'...
[   +9 ms] Using gradle from /mnt/c/Projects/lfg/frontend/android/gradlew.
[  +75 ms] executing: [/mnt/c/Projects/lfg/frontend/android/] /mnt/c/Projects/lfg/frontend/android/gradlew --full-stacktrace --info -Pverbose=true -Ptarget-platform=android-x64
-Ptarget=/mnt/c/Projects/lfg/frontend/lib/main.dart -Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[   +7 ms] exiting with code 1
```
</details>

**Comment by vsmenon** [comment]
This is the Flutter dup: https://github.com/flutter/flutter/issues/115207

**Comment by aam** [comment]
I am able to create sample flutter app (`flutter create t`) and build it for linux without any issues:
```
$ ~/flutter/bin/flutter build linux
💪 Building with sound null safety 💪
Building Linux application...
$ ~/flutter/bin/flutter build linux --release
💪 Building with sound null safety 💪
Building Linux application...
$
```

```
PS C:\Windows\System32> wsl --status
Default Distribution: Ubuntu-20.04
Default Version: 2

Windows Subsystem for Linux was last updated on 11/16/2022
WSL automatic updates are on.

Kernel version: 5.10.16
PS C:\Windows\System32>
```

This is on Win 10 version 21H2

**Comment by iSWATxJOKERi** [comment]
I decided to go to Windows development and scratched the wsl life and it's fine there so will let you decide if this issue should stay open or not?

**Comment by aam** [comment]
thanks for the information, will close the issue until there are more details available for us to reproduce it.
