### ISSUE TITLE
Analysis server crash unexpectedly (v2.18.4)

### ISSUE THREAD

**Issue by westito** [dart-lang/sdk#50471]
This simple code can crash the analysis server:
```dart
class PathFactory = Path Function();
```

To test, run:
```bash
echo 'class PathFactory = Path Function();' > main.dart && dart analyze main.dart
```

```
Analyzing main.dart...                  
Unhandled exception:
type 'GenericFunctionTypeImpl' is not a subtype of type 'NamedType' in type cast
#0      AstBuilder.endNamedMixinApplication (package:analyzer/src/fasta/ast_builder.dart:2177:28)
#1      Parser.parseNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2246:14)
#2      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2225:14)
#3      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:564:14)
#4      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:497:14)
#5      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#6      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:108:32)
#7      Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:104:12)
#8      FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:788:23)
#9      FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:563:14)
#10     FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:734:16)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:600:27)
#12     FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1502:10)
#13     FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1334:14)
#14     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1318:12)
#15     AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1533:16)
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1024:5)
#17     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2105:24)
<asynchronous suspension>


#0      FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:565:7)
#1      FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:734:16)
#2      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:600:27)
#3      FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1502:10)
#4      FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1334:14)
#5      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1318:12)
#6      AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1533:16)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1024:5)
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2105:24)
<asynchronous suspension>
Bad state: The analysis server crashed unexpectedly
```

```bash
$ dart --version                                                                   
Dart SDK version: 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "macos_arm64"
```

**Comment by vsmenon** [comment]
fyi @srawlins @bwilkerson - raising visibility as this is a crasher

**Comment by srawlins** [comment]
Whoa. Great catch!

**Comment by bwilkerson** [comment]
@jensjoha Is this something that we should be catching in the parser, or should we catch this in the `AstBuilder`? Seems like the parser would be better so that there's only one place where we need the check, but I don't know whether we have enough information. Either way it needs to be an error.

**Comment by westito** [comment]
> Whoa. Great catch!

Yeah. I started to rewrite a typedef to a class definition and voila... 😄

**Comment by jensjoha** [comment]
Catching this in the parser, I think, would entail the parser having try-catch blocks around all listener events. My vote on that would be no.

As a bit more information it's recovered as

```
class PathFactory = Path Function()with*synthetic*;
```

CFE gives these errors:
```
t.dart:1:36: Error: Expected 'with' before this.
class PathFactory = Path Function();
                                   ^
t.dart:1:21: Error: Type 'Path' not found.
class PathFactory = Path Function();
                    ^^^^
```

If giving this source instead:
```
class Path {}
class Foo {}
class PathFactory = Path Function() with Foo;
```
i.e. basically give it what it recovered to anyway and a few classes to point to, the CFE gives this:

```
t.dart:3:26: Error: Can't use a function type as supertype.
class PathFactory = Path Function() with Foo;
                         ^
```

**Comment by bwilkerson** [comment]
Ok, we'll address it on the analyzer side. Thanks.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/270225
