### ISSUE TITLE
Migration from Flutter 1.25.0-8.3.pre • channel beta (Dart 2.12.0-133.7.beta) to Flutter 2.10.5 • channel stable  (Dart 2.16.2)

### ISSUE THREAD

**Issue by maxmoridev** [dart-lang/sdk#50547]
Hi,
 i've a problem when starting migration tool and run command `$ dart migrate`,
in detail the cli output this:
```
" ...
]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.16.2) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

NoSuchMethodError: The getter 'library' was called on null.
Receiver: null
Tried calling: library at offset 91 in /Users/xxxxxx/Progetti/TEST/to_flutter2/test_app/test_app/lib/domain/entities/flt_database_tables.dart (TextColumn)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:375:40)
#2      Variables.decoratedElementType (package:nnbd_migration/src/variables.dart:97:9)
#3      EdgeBuilder.visitNamedType (package:nnbd_migration/src/edge_builder.dart:1430:41)
#4      NamedTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:7579:50)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#6      EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2604:5)
#7      EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1334:5)
#8      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7177:50)
#9      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#10     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2330:7)
#11     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:681:7)
#12     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:648:5)
#13     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1494:50)
#14     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#15     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1508:9)
#16     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#17     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#18     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#19     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#20     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2098:50)
#21     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:231:12)
#22     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:16)
#23     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1093:20)
#24     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1091:28)
#25     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1025:26)
<asynchronous suspension>
#26     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1091:5)
<asynchronous suspension>
#27     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:698:24)
<asynchronous suspension>
#28     MigrateCommand.run (package:dartdev/src/commands/migrate.dart:37:7)
<asynchronous suspension>
#29     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#30     DartdevRunner.runCommand (package:dartdev/dartdev.dart:232:18)
<asynchronous suspension>
#31     runDartdev (package:dartdev/dartdev.dart:67:16)
<asynchronous suspension>
#32     main (file:///opt/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>"
```

To work around this error i ran the tool again with the command:
`$ dart migrate --ignore-exceptions `
It seems to work, but I don't know if it works well...

I've attached the file that causes this tool to throw an exception.
[flt_database_tables.dart.txt](https://github.com/dart-lang/sdk/files/10083735/flt_database_tables.dart.txt)

Thanks
Max

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
