### ISSUE TITLE
[Patterns] Crash when attempting to parse patterns-like code

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#50563]
```dart
main() {
  int var = 0;
```
Attempt to run this code with "--enable-experiment=patterns" flag  produces a Crash
```
Crash when compiling file:///C:/Users/sgrek/Work/Google/sgrekhov/co19/LanguageFeatures/Patterns/list_A04_t01.dart at character offset 1757:
UnimplementedError: TODO(paulberry)

#0      Parser.skipOuterPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9806:5)
#1      Parser.looksLikePatternVariableDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9762:32)
#2      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7459:9)
#3      Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5248:16)
#4      Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5221:20)
#5      Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5126:15)
#6      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1109:14)
#7      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:374:5)
#8      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3588:14)
#9      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3330:14)
#10     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:586:14)
#11     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:404:15)
#12     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1260:12)
<asynchronous suspension>
#13     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:673:7)
<asynchronous suspension>
#14     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:612:7)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#16     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#18     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#19     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#20     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#21     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:414:11)
<asynchronous suspension>
#22     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:223:45)
<asynchronous suspension>
#23     _processLoadRequest (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:916:37)
<asynchronous suspension>


Process finished with exit code 252
```
Tested on the edge SDK versions on Windows ansd Linux

cc @stereotype441

**Comment by stereotype441** [comment]
I see the problem.  I'll take this.

@sgrekhov am I correct in surmising that this only happens if the experimental `patterns` feature is enabled?  (If it happens in normal execution then I'll want to investigate when the bug arose to make sure it doesn't slip into a stable release)

**Comment by sgrekhov** [comment]
@stereotype441 sorry, the description was wrong. The differense was in using `enable-experiment=pattern` flag, not in Win/Linux. I've updated the issue description. 

Yes, I can confirm that the crash occurs on both Linux and Windows if the code from the description is run with `--enable-experiment=patterns` flag. No crash without this flag

**Comment by stereotype441** [comment]
> @stereotype441 sorry, the description was wrong. The differense was in using `enable-experiment=pattern` flag, not in Win/Linux. I've updated the issue description.
> 
> Yes, I can confirm that the crash occurs on both Linux and Windows if the code from the description is run with `--enable-experiment=patterns` flag. No crash without this flag

Great, thanks!  That confirms what I saw in the code.  Fix is out for review.
