### ISSUE TITLE
[vm/ffi] Make including native code with Dart packages seamless

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50565]
The current way of _bundling_ native code with Dart packages is far from ideal.

As of right now, one can do one (or more) of the following:

1. ship sources in a Dart standalone package and let users run a build by calling `dart run <your-package>/setup.dart` [see webcrypto](https://github.com/google/webcrypto.dart/blob/master/bin/setup.dart), or
2. make your `bin/setup.dart` download the native library, or
3. ship sources a flutter plugins with `flutter create --template=plugin_ffi --platform=...`, or
4. ship a script that downloads the native library during flutter build [see realm_flutter](https://github.com/realm/realm-dart/blob/81c8b913b5c9d639fd5d4f09b069eb4fc87de706/flutter/realm_flutter/android/build.gradle#L85).

This leads to pain for both package developers (options 1-4) and package users (option 1-2). Moreover, there is currently no way to make a package with native code that works both for flutter _and_ Dart standalone.

Tackling this problem requires tackling some sub-problems:

1. A transparent way to find native symbols in Dart.
2. A standardized way to build or download native libraries.
3. Integration with all the `dart` and `flutter` tooling to link the above two together.

This is a high level "feature" issue that we can refer to from various places.

**Comment by dcharkes** [comment]
Related issues:

* https://github.com/dart-lang/sdk/issues/49803
* https://github.com/dart-lang/sdk/issues/50097
* https://github.com/dart-lang/sdk/issues/50551
* https://github.com/dart-lang/sdk/issues/50552
* https://github.com/dart-lang/sdk/issues/49418

**Comment by GregoryConrad** [comment]
Hi, as a current user of option number 4 above, this sounds really enticing. Right now I am using CMake for Linux/Windows/Android and Ruby (with inline bash) for macOS/iOS to download & extract binaries and it is a _big_ pain point. A few question:

1. Would this allow for static linking, dynamic linking, and dynamic loading? Or only a subset of these? It also might be nice to allow users to choose what to do per platform (e.g., static link on iOS/macOS and dynamic link/load on other platforms).
2. Do you envision this being available as a part of Dart 3.0? My guess is no (at least for the initial release), but wanted to ask regardless.
3. It will not always be possible to build native assets on the client-side unfortunately (e.g. Rust, Go, etc.). Will we be able to upload native assets directly to pub.dev, or at least reference the native assets from there (through some artifact repo or GitHub releases for example)?
4. How will web/wasm be handled? It would be good to have some integration to ease development/release, but not too too much, so things like [wasmer-js](https://github.com/wasmerio/wasmer-js) can be supported to use WASM with WASI on web.

**Comment by dcharkes** [comment]
Hi @GregoryConrad, nice to meet you!

> Hi, as a current user of option number 4 above, this sounds really enticing. Right now I am using CMake for Linux/Windows/Android and Ruby (with inline bash) for macOS/iOS to download & extract binaries and it is a significant pain point.

Thanks for bearing with us in the mean time! 🙃 

> A few questions:
> 
> 1. Would this allow for static linking, dynamic linking, and dynamic loading? Or only a subset of these? It also might be nice to allow users to choose what to do per platform (e.g., static link on iOS/macOS and dynamic link/load on other platforms).

We will start with dynamic loading: `@FfiNative` doing `dlopen` under the hood with the dynamic libraries. In JIT mode (`dart ...`, `flutter test`) we will always use dynamic loading.

In AOT (`dart compile ...`, `flutter build`) we can think about invoking the native linker and static linking the Dart AOT snapshot with the static libraries, this is tracked in:

* https://github.com/dart-lang/sdk/issues/49418

I have not explored using the native linker to do dynamic loading. I'm not sure if that will be of any benefit in any Dart or Flutter usage scenario. @GregoryConrad do you have a scenario in mind where you would prefer using dynamic loading?

> 2. Do you envision this being available as a part of Dart 3.0? My guess is no (at least for the initial release), but wanted to ask regardless.

I cannot comment on that. We'd want to ship the feature when it's ready, not earlier.

> 3. It will not always be possible to build native assets on the client-side unfortunately (e.g. Rust, Go, etc.). Will we be able to upload native assets directly to pub.dev, or at least reference the native assets from there (through some artifact repo or GitHub releases for example)?

We're in discussions about that, but likely yes. We have two options, and might want to support both:

1. The package author precompiles for all targets and uploads the binaries to pub, the package users then download the binaries needed for the architectures they're targetting. (Requirements here is that "A standardized way to build or download native assets. This will be done by a CLI." must have the assets in a standardized location on disk or that the CLI takes an output folder so that pub and the CLI can cooperate on getting binaries in the right place.) Uploading to pub is tracked in:

* https://github.com/dart-lang/pub/issues/3693

2. A package author can have a `build_dependency` on `package:rust_compiler` which is a dart package that downloads a rust compiler. (Requirements here are that we should probably have some kind of "This will install X GB of tools on your computer. Continue: Y/N" in our CLI.)

> 4. How will web/wasm be handled? It would be good to have some integration to ease development/release, but not too too much, so things like [wasmer-js](https://github.com/wasmerio/wasmer-js) can be supported to use WASM with WASI on web.

Best case scenario we could have a unified API for interacting with the C library on native platforms and a to WASM compiled library on the web:

* https://github.com/dart-lang/sdk/issues/46690

Further discussion can be on that issue.

**Comment by GregoryConrad** [comment]
> I have not explored using the native linker to do dynamic loading. I'm not sure if that will be of any benefit in any Dart or Flutter usage scenario. @GregoryConrad do you have a scenario in mind where you would prefer using dynamic loading?

I don't actually have a case for using dynamic linking over dynamic loading, or vice versa. When I said:

> It also might be nice to allow users to choose what to do per platform

I was more concerned with making sure we would be able to choose between static linking and dynamic linking/loading per platform. If someone else has a use case, however, I would be happy to hear it.

> 2. A package author can have a build_dependency on package:rust_compiler which is a dart package that downloads a rust compiler. (Requirements here are that we should probably have some kind of "This will install X GB of tools on your computer. Continue: Y/N" in our CLI.)

Although I like the idea here a lot, I foresee some issues with this approach. Especially in my project, some custom build steps and quite a few other package dependencies (besides just `rustup`) are needed to handle cross compilation, especially for android (due to linking with the NDK). I currently have these all done in CI and I think I would just prefer to ship the binaries in a native assets bundle directly. Perhaps having a `rust_compiler` dependency would work great for many projects, but for some projects with more complex dependencies/needs, this may not be as feasible.

And thanks for the rest of your input! Much appreciated.

**Comment by stuartmorgan** [comment]
@eladmaimoni Plugins are a Flutter-specific concept, as is the template you are referring to.

**Comment by dcharkes** [comment]
> * User should be able to customize the cmake arguments passed by dart / flutter tools.

The build for native assets would be disconnected from the Flutter native build. Flutter would only receive a list of static and dynamic libraries that need to be bundle.

> * Ideally, when generating the template for a plugin, there should be a single root CMakeLists.txt and not several.

Even using CMake would be an abstraction in this approach. We haven't settled yet on whether we mandate compilers, but with trying to support Go and Rust as well, constraining C/C++ to a single build system would also be constraining. How various compilers would be supported (for example with Dart packages that wrap them) is still up for discussion.

The way that this is achieved is that we interact through a CLI (likely `bin/native.dart` or `bin/_build.dart`) that can run any compiler it wants. It has to output a list of compiled native static and dynamic libraries for Flutter and Dart to bundle in apps. (You don't have have to build from source. You can download precompiled binaries from a CDN or pub.dev as well.)

> * Also, there should be a place to put source files that are common to all platforms. If i am not mistaken, the plugin template now generates separate files to all platforms. It is very confusing not to have a single 'entry' point for the plugin.

This is trivial once the build is an arbitrary Dart script. One of my examples is a completely cross platform CMake build.

> One way this could be achieved is to use CMakePresets.json to configure cmake for each platform.

Native assets is a completely different approach. Zero Flutter template "boilerplate" will be included. These will be Dart standalone packages that will have their compiled dynamic libraries properly build and bundled with Flutter apps.

**Comment by stuartmorgan** [comment]
> How various compilers would be supported (for example with Dart packages that wrap them) is still up for discussion.
> 
> The way that this is achieved is that we interact through a CLI (likely `bin/native.dart` or `bin/_build.dart`) that can run any compiler it wants.

I know I've mentioned this in other contexts, but we'll need to be very careful about getting this right; the ecosystem effects if we don't have a robust way to manage the toolchain dependencies automatically could be very unpleasant.

**Comment by GregoryConrad** [comment]
> The way that this is achieved is that we interact through a CLI (likely bin/native.dart or bin/_build.dart) that can run any compiler it wants. It has to output a list of compiled native static and dynamic libraries for Flutter and Dart to bundle in apps. (You don't have have to build from source. You can download precompiled binaries from a CDN or pub.dev as well.)

If you are familiar with Rust, is what you are describing here similar to `build.rs` in some capacity (in that package authors can create their own build scripts)? That sounds very exciting as:
1. On package development machines, we could throw in some compilation steps to automate compilation and remove the need to manually trigger compilations and sling binaries around everywhere. This is super handy when doing something like `dart test` so that the build script would handle that compilation step for us to ensure everything is up to date.
2. On users' machines, we simply download or point to precompiled native assets.
3. We can switch between options 1 & 2 based on whether the necessary dev dependencies are installed locally (e.g., running a `which cargo` fails or not). We will probably want Dart APIs to figure out the build platform (already supported thru `Abi.current()`) and the target platform, while also supporting cross compilation.

I almost wonder if there should be a standard way to package native assets at all then (other than being able to upload to pub.dev, which would be great); if we have build scripts then we can decide which way works best for our projects based on our own build systems (i.e., `target/` could be used for binary locations when using Rust).

However, one obvious drawback is that the build script could access anything on the system. I am not too worried about this issue though, as any Flutter package today can do the same without any warning to the user and other ecosystems such as Rust haven't had many troubles with this--you just simply need to trust the packages you use.

**Comment by GregoryConrad** [comment]
Hi again! Just came across an issue where dynamic loading *will be a hard requirement* (even for AOT builds), due to duplicate symbols.

For background, see https://github.com/fzyzcjy/flutter_rust_bridge/issues/947#issuecomment-1437697037, although I will summarize here:

Say packages `abc` and `xyz` using native assets both export some C symbol `foobar`. I have experimented with iOS and it actually just strips the duplicate symbols without throwing an error during linking. This is bad, because one package will consequently be broken at runtime (possibly even silently) without an error emitted during the build.

Since duplicate symbols will definitely happen, dynamic loading across a user's dependent packages would be extremely helpful. With dynamic loading, we won't have to worry about symbol conflicts because they are resolved with `dlopen`, `dlsym`, etc. With static linking, we can run into weird issues like the iOS one described above.

This exact scenario is possible when using `flutter_rust_bridge`, perhaps when a user depends on two different packages using `flutter_rust_bridge`. Different versions of `flutter_rust_bridge` have different implementations of its Rust support library, which can introduce breaking changes between versions.

Since iOS 8, Apple allows apps to use dynamic loading. See related:
- https://developer.apple.com/library/archive/technotes/tn2435/_index.html
- https://developer.apple.com/forums/thread/15507

**Comment by dcharkes** [comment]
> Just came across an issue where dynamic loading will be a hard requirement (even for AOT builds), due to duplicate symbols.

Interesting, thanks for sharing.

Let me think if there's other solutions. If developers using your libraries care about code size of deployed Flutter apps, static linking would be preferential. So if there is a way to use static linking that would be good.

> Say packages `abc` and `xyz` using native assets both export some C symbol foobar. 

Packages with C could should prefix their own symbols with their own package. This is standard practise in C libraries as far as I know. For example:

* `sqlite3_xxx` https://github.com/LuaDist/libsqlite3/blob/master/sqlite3.h
* `OPENSSL_xxx` https://commondatastorage.googleapis.com/chromium-boringssl-docs/mem.h.html

> have experimented with iOS and it actually just strips the duplicate symbols without throwing an error during linking. This is bad, because one package will consequently be broken at runtime (possibly even silently) without an error emitted during the build.

Aw, no errors 😢 

Any idea in which scenarios this happens? Do the functions need the same signature? In that case I presume it strips the second symbol it finds on the import path because all call sites will be linked to the first symbol so the second one is dead code.

> This exact scenario is possible when using `flutter_rust_bridge`, perhaps when a user depends on two different packages using `flutter_rust_bridge` internally. Different versions of `flutter_rust_bridge` have different implementations of its Rust support library, which can introduce breaking changes between versions.

How exactly does one end up with two versions of the support library?  Is the support library compiled into the dynamic libraries?

In `package:jnigen` we have a different approach. The support library is in `package:jni`. If you JNIgen is used in more than one package, they all have a dependency on `package:jni` and `dart pub get` resolves that package to a single version, or it fails. This means you'll always only have one copy of the support library. (FYI @HosseinYousefi) Would such an approach work for the flutter_rust_bridge?

If it's not possible to set it up like that, would it be possible to add a macro to your support library that prefixes all your function and type names with `FRB_<semantic-version>_`, and make the generator generate code that interacts with the versioned symbols/types of your support library?

**Comment by GregoryConrad** [comment]
> Any idea in which scenarios this happens? Do the functions need the same signature?

As tested, it was for functions with the same signature. If you're interested, I can modify the test and see what happens for a slightly different signature.

> How exactly does one end up with two versions of the support library? Is the support library compiled into the dynamic libraries?

`flutter_rust_bridge` (FRB) requires two support libraries when using it; one on the Dart side, and one on the Rust side. Both essentially dumb down the respective language's datatypes into C compatible equivalents for use with `dart:ffi` so they can be passed between each other. Thus, one instance of the support library is compiled into the Rust side, and one instance is left on the Dart side. 

> `dart pub get` resolves that package to a single version, or it fails. This means you'll always only have one copy of the support library. Would such an approach work for the flutter_rust_bridge?

Unfortunately, no. When creating an FRB package, the Dart & Rust FRB support library versions have to match up *exactly*, because slight (internal) breaking changes can be released between versions to correct bugs or support some new feature. In fact, on the Dart side, packages must specify an exact FRB version to prevent being broken (no `^` versioning syntax). Hopefully, we can remove the pinned version on the dart side by copying necessary parts of the support library into generated Dart code instead of requiring an exact version, but that issue is still in early stages (https://github.com/fzyzcjy/flutter_rust_bridge/issues/947)

> would it be possible to add a macro to your support library that prefixes all your function and type names with `FRB_<semantic-version>_`, and make the generator generate code that interacts with the versioned symbols/types of your support library?

That sounds like a very good idea. CC @fzyzcjy this would probably be pretty trivial to add into the Rust code gen today? Also, perhaps we could add some other prefix for the resulting package name (like in Cargo.toml) so that two different packages with the same FRB version don't have colliding symbols.

As a separate question, would it be possible on the Dart end to resolve any duplicate symbols by simply adding some unique prefix to the symbols exposed in every dart package's native assets? Or would that be considered a bad idea? I don't know of any language that does this for FFI, and perhaps there is a reason for that, or perhaps nobody thought to do it (which seems unlikely). Or, if not, would it be at least possible to error out when duplicate symbols are present (instead of iOS' approach 😅)?

**Comment by dcharkes** [comment]
> Unfortunately, no. When creating an FRB package, the Dart & Rust FRB support library versions have to match up exactly, because slight (internal) breaking changes can be released between versions to correct bugs or support some new feature.

I believe this to be the case for the supporting `package:jni` as well. Every breaking change will lead to a semantic-version bump in `package:jnigen` (since we're 0.x now, it's bumping the x, but when we get 1.0 it would always have to bump the major version).

> Hopefully, we can remove the pinned version on the dart side by copying necessary parts of the support library into generated Dart code instead of requiring an exact version

That is indeed a workaround, however, this will increase code-size when you have two packages using the exact same version of FRB (and requires you to ensure the symbols don't have the same name if it's not the same version of FRB).

> As a separate question, would it be possible on the Dart end to resolve any duplicate symbols by simply adding some unique prefix to the symbols exposed in every dart package's native assets?

As the native libraries might be prebuilt and downloaded from a CDN, I don't think we can modify the native libraries themselves. That would break signing. (Also, it's complicated to modify compiled native code.)

> Or, if not, would it be at least possible to error out when duplicate symbols are present

The question is when to give that error. The `@Native<>() external` functions don't specify whether they are dynamically loaded, dynamically linked, or statically linked. It is only when later in the pipeline we happen to dynamically or statically link a symbol with the same signature with two different native libraries that we know that this is an error.
And it is the embedder (Flutter or `dart run/compile`) that makes the decision on how to prefer to bundle native libraries (after each dart package has reported on whether it's able to do dynamic and/or static libraries). So the error would have to be from the embedder, not from the Dart source code.
This is a good suggestion, let me think about where it would fit best.

**Comment by fzyzcjy** [comment]
> FRB_<semantic-version>_ ...
> ... CC @fzyzcjy  ... adding some unique prefix to the symbols exposed in every dart package's ...

Yes I think so! We may just add prefix `FRB_<version>_<packagename>_` to every symbol generated.

**Comment by GregoryConrad** [comment]
Just thought of another idea: it would be really nice for build scripts written in Dart to be able to read a consumer's pubspec.yaml, say for adding custom build flags. This would prevent the need for "magic" files or environmental variables by  simply adding a few extra parameters to a user's `pubspec.yaml`.

Example from a user's `pubspec.yaml`:
```yaml
# all your other Dart/Flutter entries

my_native_asset_dependency:
  some_build_flag: true
  some_other_setting: foobar

some_other_dependency:
  foo: bar
```

**Comment by dcharkes** [comment]
We're indeed thinking of adding user-defines.

Using a config file would indeed help not having to set environment variables or passing arguments to `flutter build/run` every time. But we would need to think about what to do about the situation where you want a different config for a different OS/architecture or even release vs debug, putting it in `pubspec.yaml` makes it a single config.

Maybe it would be better to have a `native_assets_config.yaml` that you can pass in to `--native-assets-config`, then one can vary the config per build if needed.

**Comment by GregoryConrad** [comment]
> what to do about the situation where you want a different config for a different OS/architecture or even release vs debug

Why not do that per package (i.e., let a package chose how to handle it)? Build processes might change per native asset (like choosing to compile to static or dynamic lib for instance). I think it would be nice to give package authors that flexibility. Take this `pubspec.yaml` snippet for instance:

```yaml
# other entries

some_native_asset_package:
  some_global_flag: foobar
  release:
    optimize: true
  debug:
    optimize: false
```

Or, alternatively:

```yaml
dependencies:
  my_native_asset_dep:
    version: ^1.0.0
    foo: bar
    release:
      optimize: true
    debug:
      optimize: false
```

Thinking more about this now, I believe I may actually prefer this second option, and it would be great if our build scripts could just be given a `Map<String, dynamic>` of these configurations under the package itself.

I think keeping it as a single config, or allowing package authors to chose where to read from, would be nice. Otherwise there might be a ton of files in a repo to keep track of, and I would imagine most Dart developers think of `pubspec.yaml` when they think of dependencies and their configuration. A similar statement is true for Rust, where you often configure features and settings alongside your dependencies.

**Comment by TimWhiting** [comment]
Linking to https://github.com/flutter/flutter/issues/116191

It seems like bazel could be useful here as well.

> We're in discussions about that, but likely yes. We have two options, and might want to support both:
>
> 1. The package author precompiles for all targets and uploads the binaries to pub, the package users then download the binaries needed for the architectures they're targetting. (Requirements here is that "A standardized way to build or download native assets. This will be done by a CLI." must have the assets in a standardized location on disk or that the CLI takes an output folder so that pub and the CLI can cooperate on getting binaries in the right place.)
> 2. A package author can have a build_dependency on package:rust_compiler which is a dart package that downloads a rust compiler. (Requirements here are that we should probably have some kind of "This will install X GB of tools on your computer. Continue: Y/N" in our CLI.)

I believe it could solve both of these issues by providing a way to (1) provide a standard way of downloading / caching artifacts from pub for the architectures you need, and (2) define reproducible builds from source with the correct toolchains for a variety of languages.

Otherwise, to really support (2) you basically have to replicate bazel for getting the whole toolchain story so that it works on all platforms. The fact that it has support for C++ / Rust / Java-JVM/JNI / Swift / Node / etc means that the library authors and the dart sdk team don't have to create the build_dependency packages that download the correct toolchains - probably with incomplete support, because that is already done by the bazel packages. https://registry.bazel.build/all-modules

**Comment by dcharkes** [comment]
We've had some discussions about using Bazel. cc @mraleph. It's a promising idea, but there are a lot of questions to answer. We might go there in the future, but it's much further out than the "native assets" feature tracked in this thread. (Here are some more old links with Bazel and Dart: https://github.com/cbracken/rules_dart, https://github.com/dart-archive/bazel/tree/master/dazel, https://groups.google.com/a/dartlang.org/g/misc/c/KshWeq5kuzI.)

> Currently CMake is a dependency (which also sometimes has version issues) which bazel would replace

This should go away with the Native Assets work. One just needs a C/C++ compiler, and Flutter should pass the path to the C/C++ compiler it uses to the native assets builder. In Dart, we will either (1) also bundle a small C compiler or (2) introduce a `dart doctor` or something similar to find the native compiler on your system. You can see an example [here](https://github.com/dart-lang/native/tree/main/pkgs/native_assets_cli/example/native_add).

And correct, we do not have a story yet for Rust. Indeed a package `rust_compiler` would need to replicate the toolchain story.

**Comment by dcharkes** [comment]
In e1ae1b48aeae4c7a0e5439322c9c61fe52a98f77, we have landed support for this in Dart behind an experimental flag. On the main branch (and dev releases) this feature is available via `--enable-experiment=native-assets`.

Please note that we will probably do breaking changes to how this feature works before we go out of stable. But please give it a spin and give us feedback.

An example usage can be found here: https://github.com/dart-lang/native/tree/main/pkgs/native_assets_cli/example/native_add.

**Comment by CicadaCinema** [comment]
> In [e1ae1b4](https://github.com/dart-lang/sdk/commit/e1ae1b48aeae4c7a0e5439322c9c61fe52a98f77), we have landed support for this in Dart behind an experimental flag. On the main branch (and dev releases) this feature is available via `--enable-experiment=native-assets`.
> 
> Please note that we will probably do breaking changes to how this feature works before we go to non-experimental. But please give it a spin and give us feedback.
> 
> An example usage can be found here: https://github.com/dart-lang/native/tree/main/pkgs/native_assets_cli/example/native_add.

Great news! Which platforms does this experiment currently support? I take it, anything with a C compiler?

Does it support linking with shared libraries?

**Comment by dcharkes** [comment]
> Great news! Which platforms does this experiment currently support? I take it, anything that can be targeted by a C compiler?

Everywhere where Dart standalone native currently runs (a subset of Windows/Linux/MacOS x arm64/x64/ia32/riscv).

> Does it support linking with shared libraries?

It does dynamic loading of shared libraries (not dynamic linking), and static linking for static libraries is also still in the works.

**Comment by blaugold** [comment]
In `pkgs/native_assets_cli/example/native_add` I created `bin/add.dart` with the following contents:

```dart
import 'package:native_add/native_add.dart';

void main() => print(add(1, 2));
```

Then I executed the following commands:

```
dart --enable-experiment=native-assets build bin/add.dart
cd bin/add
./add.exe
```

Executing `./add.exe` aborts with an exception:

```
Unhandled exception:
Invalid argument(s): Couldn't resolve native function 'add' in 'package:native_add/src/native_add_bindings_generated.dart' : Failed to load dynamic library 'libnative_add.dylib': Failed to resolve 'libnative_add.dylib' relative to './add.exe'..

#0      FfiTrampoline__ffi_resolver (dart:ffi)
#1      _add$Method$FfiNative$Ptr (package:native_add/src/native_add_bindings_generated.dart:12)
#2      add (package:native_add/src/native_add_bindings_generated.dart)
#3      add (package:native_add/src/native_add.dart:9)
#4      main (file:///Users/terwesten/dev/dart/native-1/pkgs/native_assets_cli/example/native_add/bin/add.dart:3)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

@dcharkes Am I doing something wrong or is this not supposed to work yet?

**Comment by TimWhiting** [comment]
I get the same behavior, even when specifying LD_LIBRARY_PATH: `LD_LIBRARY_PATH=$pwd ./add.exe`. Replacing build with run works however.

**Comment by dnys1** [comment]
Are there plans to extend support for `build.dart` to Web as well? The use case I'd be interested in is building external JS artifacts or compiling Web Worker entrypoints which currently requires a manual copy/paste or `build_runner` step.

**Comment by dcharkes** [comment]
> Are there plans to extend support for `build.dart` to Web as well? The use case I'd be interested in is bundling external JS artifacts or compiling Web Worker entrypoints which currently requires a manual copy/paste or `build_runner` step.

We did decide to name it `build.dart` as a generic name in order for it to be extensible and Dart/Flutter SDK be able to communicate with packages about other things than native assets. Whether this will be adopted with dart2js/ddc is up to the responsible people, and should likely be discussed in a new thread. (Other use cases for `build.dart` could include assets such as icons that Flutter has an asset system for but Dart has not yet.)

**Comment by simolus3** [comment]
> We're indeed thinking of adding user-defines.

Has any work on this happened already? I see that I can take options from environment variables thanks to `package:cli_config`, but that's not exactly ergonomic and the used variables aren't saved to `build_output.yaml` so it feels like breaking the build system. I couldn't find any reference to this in any example and from a quick look into the tooling, is there an open issue for this or some other place where this is being documented?

**Comment by dcharkes** [comment]
> > We're indeed thinking of adding user-defines.
> 
> Has any work on this happened already?

No, the work is tracked in https://github.com/dart-lang/native/issues/39.

> I see that I can take options from environment variables thanks to `package:cli_config`, but that's not exactly ergonomic and the used variables aren't saved to `build_output.yaml` so it feels like breaking the build system.

Correct, the right way to do it if we allow passing through the environment is that `dart run`, `dart build`, `flutter run`, etc. would take these environment variables and put it inside `config.yaml` that's being passed to the `build.dart`

> I couldn't find any reference to this in any example and from a quick look into the tooling, is there an open issue for this or some other place where this is being documented?

https://github.com/dart-lang/native/issues/39. Let's continue the discussion there.

**Comment by halildurmus** [comment]
I have a use case where I need to obtain a `Pointer<NativeFunction<...>>` that references the native function itself, rather than the Dart function using the Native assets. However, it appears that this is not supported in its current form.

For example, instead of this:

```dart
@Native<Int64 Function(Int64, Int64)>()
external int sum(int a, int b);
```

I require something akin to the following:

```dart
@Native<Pointer<NativeFunction<Int64 Function(Int64, Int64)>>()
external Pointer<NativeFunction<Int64 Function(Int64, Int64)>> sum(int a, int b);
```

Or, even better:

```dart
@Native()
external Pointer<NativeFunction<Int64 Function(Int64, Int64)>> sum(int a, int b);
```

Are there any plans for this?

**Comment by simolus3** [comment]
> Are there any plans for this?

I think this would be covered by the `addressOf` suggestion in https://github.com/dart-lang/sdk/issues/50552.

**Comment by Levi-Lesches** [comment]
> (Side note: We're trying to get the native assets feature merged in Flutter first, and then next we'd like to make the native assets feature have feature parity with the DynamicLibrary approach.

Great to hear! I'm trying to develop an FFI _Flutter_ plugin based on an FFI package but also want to allow people to use the underlying FFI package standalone. This is making an awkward split between "put your DLLs here" vs trying to fiddle with CMake on the Flutter side. Having both regular Dart and Flutter apps go through the same build process will _massively_ help here.

Is there an issue/progress tracker for native assets on the Flutter side?

**Comment by dcharkes** [comment]
> Is there an issue/progress tracker for native assets on the Flutter side?

Native assets support in Flutter is in development. Progress can be tracked in https://github.com/flutter/flutter/issues/129757.

**Comment by yvs2014** [comment]
> I don't actually have a case for using dynamic linking over dynamic loading, or vice versa. When I said:
> 
>> It also might be nice to allow users to choose what to do per platform
> 
> I was more concerned with making sure we would be able to choose between static linking and dynamic linking/loading per platform. If someone else has a use case, however, I would be happy to hear it.

Speaking about Linux on case "using dynamic linking over dynamic loading":
in many cases .so files (all the files that necessary to compile code against a given library) are presented by GNU linker scripts rather than a native library. So that , if one uses dlopen() with a versioned shared lib (libname.so.N, the proper way of dynamic loading), there's a good chance to miss some resolving that done by that linker

**Comment by fzyzcjy** [comment]
Hi, I am curious what is the performance of the new approach? I guess it can be faster because there can be more compile-time optimizations.

**Comment by dcharkes** [comment]
> Hi, I am curious what is the performance of the new approach? I guess it can be faster because there can be more compile-time optimizations.

Most important for performance is to use `isLeaf: true`.
And yes, leaf `@Native external` function calls are faster than the ones created by `asFunction` or `lookupFunction`.
And after addressing https://github.com/dart-lang/sdk/issues/47625, the `@Native external` function calls are optimized even further.

If you're interested in playing around with the performance, we track FFI call performance with https://github.com/dart-lang/sdk/blob/main/benchmarks/FfiCall/dart/FfiCall.dart. Be sure to run in AOT (`dart compile exe`), which is how most apps are deployed.

**Comment by dcharkes** [comment]
> By the way, may I know where is the benchmark continuously evaluated? (I only know https://flutter-flutter-perf.skia.org/e/ for Flutter and a quick google search does not reveal links for Dart)

The Dart benchmarking infra is not visible outside Google atm. cc @mit-mit @sortie (Ignoring technical difficulties in doing so) should we consider having some benchmark results public? Or should we at least add some doc why our benchmark results are not public, because Flutter's are.

> As a side question, I wonder whether the Dart-to-C call is now as fast as Flutter-framework-to-Flutter-engine call? (They seem to use the same annotation now).

The old Framework-to-engine calls were using the "old native"s mechanism before https://github.com/flutter/engine/pull/34700. That mechanism was using reflection to access parameters in an array which was slow, but did not require closure calls, which `@Native external`s do use before https://github.com/dart-lang/sdk/issues/47625 lands. So some calls were faster and some slower. After https://github.com/dart-lang/sdk/issues/47625 lands, all `@Native external` calls are faster than using the old natives.

> And, is Dart-to-C call using native assets and enable isLeaf the fastest possible way to talk to other languages?

Yes, that is the `dart:ffi` mission statement. If you run into performance bottlenecks, please file issues. (We've recently also been addressing other performance aspects besides calls. For example optimizing memory copy between Dart and C memory. https://dart-review.googlesource.com/q/memorycopy)

**Comment by fzyzcjy** [comment]
Thank you for the information and excited to see those improvements!

> The Dart benchmarking infra is not visible outside Google atm.

I see, then I may run it on my own machine (at the same time it would be great to see google's numbers to check whether I did something wrong).

> If you run into performance bottlenecks, please file issues.

Not yet, but I am planning to do some benchmarking after finishing most of the WIP flutter_rust_bridge 2.0 ;)

**Comment by fzyzcjy** [comment]
When running `dart compile exe`, it seems that even if I add `--enable-experiment=native-assets`, it still complains that the flag should be enabled.

P.S. I am (currently) using `build.dart` (in flutter_rust_bridge's pure-dart example) to build a dynamic library, and has not used `@Native` yet, so it is not related to static linking issue (if any).

Shell output:

```
(base) ➜  native git:(main) ✗ cd pkgs/native_assets_cli/example/native_add_app 

(base) ➜  native_add_app git:(main) ✗ dart compile exe bin/native_add_app.dart 
Package(s) native_add_library require the native assets feature to be enabled. Enable native assets with `--enable-experiment=native-assets`.
(base) ➜  native_add_app git:(main) ✗ dart --enable-experiment=native-assets compile exe bin/native_add_app.dart 
Package(s) native_add_library require the native assets feature to be enabled. Enable native assets with `--enable-experiment=native-assets`.

(base) ➜  native_add_app git:(main) ✗ dart run  bin/native_add_app.dart         
Package(s) native_add_library require the native assets feature to be enabled. Enable native assets with `--enable-experiment=native-assets`.
(base) ➜  native_add_app git:(main) ✗ dart  --enable-experiment=native-assets run bin/native_add_app.dart 
Invoking a native function to calculate 1 + 2.
Invocation success: 1 + 2 = 3.
```

**Comment by dcharkes** [comment]
Lets keep this thread as the umbrella issue and discuss specifics in specific issues.

**Comment by amrgetment** [comment]
Native assets renamed to Build hooks and code assets
I wonder why? And what is the difference between build hook and code assets?

**Comment by mkustermann** [comment]
> Native assets renamed to Build hooks and code assets
> I wonder why? And what is the difference between build hook and code assets?

Because we have generalized the concept.

The underlying general mechanism is Dart build hooks (writing `hook/build.dart` scripts in Dart packages). Writing such build hooks will not only allow packages to contain (native) code assets but also other assets (data assets are in development atm)

**Comment by iapicca** [comment]
> The intention is to make this general mechanism be used across all target platforms (also web)

this is fantastic, thank you!

**Comment by dcharkes** [comment]
**Build hooks and code assets support in Dart standalone is available since Dart 3.10.** 

Ongoing work for tree-shaking and other features related to hooks can be tracked in: https://github.com/orgs/dart-lang/projects/99
