### ISSUE TITLE
Different handling of abstract method with noSuchMethod in AOT/JIT and JS

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#50584]
```dart
class A {
  void f() {
    print('A.f called');
  }
}

class B implements A {
  void f({int test}); // optional non-nullable with no default value, also not a valid override

  // `f` above is not valid without a `noSuchMethod`
  noSuchMethod(Invocation invocation) {
    print('B.noSuchMethod');
  }
}

void main() {
  B().f();
}
```

AOT and JIT output:

```
B.noSuchMethod
```

JS output: (not optimized, compiled with `dart compile js main.dart`)

```
d8.js:263: TypeError: null: type 'JSNull' is not a subtype of type 'int'
          throw e;
          ^
TypeError: null: type 'JSNull' is not a subtype of type 'int'
    at Object.wrapException (out.js:328:17)
    at Object._asInt (out.js:1034:15)
    at main (out.js:2243:92)
    at action (d8.js:275:31)
    at eventLoop (d8.js:258:9)
    at self.dartMainRunner (d8.js:276:5)
    at out.js:3016:7
    at out.js:3001:7
    at dartProgram (out.js:3012:5)
    at out.js:3020:3
```

**Comment by sigmundch** [comment]
Notes:
* DDC matches the VM results
* dart2js -O3 also matches the VM results.
