### ISSUE TITLE
Implement dynamic function calls in dart2wasm

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#50661]
```
NoSuchMethodError: method not found: 'bar'
Receiver: Instance of 'Foo'
Arguments: [2]
    at Object.noSuchMethod (wasm://wasm/000a93de:wasm-function[746]:0x2246c)
    at doCallThroughGetter (wasm://wasm/000a93de:wasm-function[741]:0x223e2)
    at main (wasm://wasm/000a93de:wasm-function[53]:0x16355)
    at main tear-off (wasm://wasm/000a93de:wasm-function[54]:0x16368)
    at _invokeMain (wasm://wasm/000a93de:wasm-function[64]:0x1663a)
    at Module.invoke (/b/s/w/ir/pkg/dart2wasm/bin/dart2wasm_runtime.mjs:410:28)
    at main (pkg/dart2wasm/bin/run_wasm.js:50:21)
```

**Comment by osa1** [comment]
Smaller repro:

```dart
class A {
  void Function() get x => () {
        print('hi');
      };
}

void main() {
  (A() as dynamic).x();
}
```

This made me realize that the current dynamic invocation code generation is not quite right.

Currently, when we find a member with a matching name, we assume that the static type of the member will give us the shape of the member so that we can check number of passed args etc. match the expected number of parameters.

But that's not always the case, for example:

```dart
class A {
  dynamic get x => () {
        print('hi');
      };
}

void main() {
  (A() as dynamic).x(123);
}
```

In this example, we can't generate the shape checks in the forwarder because the forwarder type of the field is `dynamic`. The closure itself (the function expression `() { ... }`) needs an entry point that checks the passed arguments against the expected parameters (and also the types). This will also be used by `Function.apply`.

Since a getter that returns a function needs to return a closure or a tear-off, we can implement these shape checking entry points for tear-offs and closures, but a more uniform way of handling this would be to generate those entry points for all methods that can be dynamically invoked, and simply call those shape-checking methods in forwarders. When target of a dynamic invocation is a method we know in compile time which method to call for shape checking. When it's a getter, the closure needs a vtable entry for shape-checking function.

Any thoughts on this @askeksa-google?

**Comment by osa1** [comment]
I think it makes sense to implement `Function.apply` first. For `Function.apply`, closures will need a vtable entry (a Wasm function) for checking number of arguments, names of named arguments etc. For this bug we will use the same shape-checking functions when the member in a dynamic invocation is a getter or field.

**Comment by askeksa-google** [comment]
As you say, such a call consists of a dynamic getter call followed by a dynamic function call.

The first step is to dispatch to the getter. This can be done with a separate loop in `_generateInvocationCode` as discussed here: https://dart-review.googlesource.com/c/sdk/+/272261/48/pkg/dart2wasm/lib/dynamic_dispatch.dart#214

I agree that it makes sense to implement dynamic function calls first. But `Function.apply` is a completely different beast, since the number and names of the arguments is not known statically. Let's leave that for later.

The runtime type of the called closure should contain all information necessary to perform the shape and type checks. AFAICS, we don't need to add anything to the vtables for this.

It could make sense, for the dynamic function calls that are not in the context of calling a getter (i.e. the `_functionCall` method in the code generator with a `dynamic` or `Function` receiver) to bundle up all of the arguments (type, positional and named) into lists in the same way as dynamic calls do and then have a one-size-fits-all type checking trampoline that calls a closure with a given set of arguments. That trampoline can then be reused by the dynamic-call-of-getter case, where the arguments are already in that form.

The code for the actual closure call still needs to be generated specifically for each call, since it needs to fetch and call the right entry in the vtable. The `_functionCall` method already does this. Each case in the dynamic forwarder will need to generate a call similarly.

**Comment by askeksa-google** [comment]
Maybe the type checker function should not be a trampoline after all, due to the requirement for specialized code generation for the call itself. It could just check the argument types and then return. Given that all of the arguments are in Dart lists, the type checker function could be implemented in Dart.

**Comment by osa1** [comment]
I started implementing this.

One of the things that we need to do both in `Function.apply` and in dynamic invocations of gets (`f.x()` when `x` is a getter or a field with type `dynamic`) is checking the type and shape of the function being applied with the arguments, and it seems like runtime types of functions currently have everything we need for type and shape checking:

```dart
class _FunctionType extends _Type {
  final int typeParameterOffset;
  final List<_Type> typeParameterBounds;
  final _Type returnType;
  final List<_Type> positionalParameters;
  final int requiredParameterCount;
  final List<_NamedParameter> namedParameters;

  ...
}

class _NamedParameter {
  final String name;
  final _Type type;
  final bool isRequired;

  ...
}
```

Given a value of `_FunctionType`, and lists for passed type, positional, and named arguments (as we do in dynamic forwarders), it's easy to check in a library function that:

- No type arguments passed, or passed type arguments match the number of type parameters
- At least required number of positional arguments passed, and no more than `positionalParameters.length` positional arguments passed
- Required named parameters are passed, and no extra named parameters are passed

(I implemented this below)

Type checking can also be done in a library function (implementation below), because the `_FunctionType` for the closure will have all the type parameters resolved already. We can just call `_isSubtype` a parameter type and the value passed for it. However it needs substituting type parameters in the function type with the passed type arguments. For example, if closure's type is

```
<X>(X a) -> T
```

when type checking the argument, we need to substitute the passed type argument for `X` (or with the default bound).

Once the shape and type checks are done, the final and tricky part seems to be calling the actual vtable entry for the closure. As far as I understand, vtable for a closure will have an entry (a Wasm function) for all valid call shapes of the closure. Because we know the call shapes in dynamic invocations of gets we can get the vtable entry for the call. With `Function.apply` we don't know the shape in compile-time though: as far as I can see `ClosureRepresentation` (the type used to get vtable entry for a call shape) does not exist in runtime.

For this part I think we will need a vtable entry that takes the arguments as lists (same as forwarders), and call the right vtable entry. This vtable entry should have a known index (probably 0) so that it can be called in `Function.apply`.

After these, `Function.apply` and dynamic invocations of gets will both call the same shape and type checking functions. For calling the actual function, `Function.apply` will call the special vtable entry mentioned above. In dynamic invocations of gets we don't need that, we know the call shape, so we can get the vtable index (`ClosureRepresentation.fieldIndexForSignature`) and call it directly.

<details>

<summary>Shape checking library function (not tested)</summary>

```dart
@pragma("wasm:entry-point")
// NB. Named args are (Symbol, Object?) pairs
bool _checkShapes(_FunctionType funTy, List<_Type> typeArgs,
    List<Object?> posArgs, List<dynamic> namedArgs) {
  // Check type args
  if (typeArgs.isNotEmpty &&
      typeArgs.length != funTy.typeParameterBounds.length) {
    return false;
  }

  // Check positional args
  if (posArgs.length < funTy.requiredParameterCount ||
      posArgs.length > funTy.positionalParameters.length) {
    return false;
  }

  // Check named args. Both parameters and args are sorted, so we can iterate them in parallel.
  int namedParamIdx = 0;
  int namedArgIdx = 0;
  while (namedParamIdx < funTy.namedParameters.length) {
    _NamedParameter param = funTy.namedParameters[namedParamIdx];

    if (namedArgIdx * 2 >= namedArgs.length) {
      if (param.isRequired) {
        return false;
      }
      namedParamIdx += 1;
      continue;
    }

    Object? argName = namedArgs[namedArgIdx * 2]; // symbol
    Object? argValue = namedArgs[namedArgIdx * 2 + 1];

    // TODO: param.name is String, not Symbol, but it should be Symbol?
    if (identical(argName, param.name)) {
      namedParamIdx += 1;
      namedArgIdx += 1;
    } else {
      // TODO: toString() will be expensive as it will demangle?
      if (argName.toString().compareTo(param.name.toString()) < 0) {
        // Passed arg not expected
        return false;
      } else if (param.isRequired) {
        // Required param not passed
        return false;
      } else {
        // Optional param not passed
        namedParamIdx += 1;
      }
    }
  }

  // All named parameters checked, any extra arguments are unexpected
  if (namedArgIdx < namedArgs.length) {
    return false;
  }

  return true;
}
```

</details>


<details>

<summary>Type checking library function (not tested)</summary>

```dart
@pragma("wasm:entry-point")
// NB. Named args are (Symbol, Object?) pairs
bool _checkTypes(_FunctionType funTy, List<_Type> typeArgs,
    List<Object?> posArgs, List<dynamic> namedArgs) {
  bool isSubtype(_Type t1, _Type t2) =>
      _typeUniverse.isSubtype(t1, null, t2, null);

  List<_Type> substitutions = funTy.typeParameterBounds;

  if (!typeArgs.isEmpty) {
    for (int i = 0; i < typeArgs.length; i += 1) {
      if (!(_isSubtype(typeArgs[i], funTy.typeParameterBounds[i]))) {
        return false;
      }
    }
    substitutions = typeArgs;
  }

  funTy = _TypeUniverse.substituteFunctionTypeArgument(funTy, substitutions);

  // Check positional arguments
  for (int i = 0; i < typeArgs.length; i += 1) {
    final Object? arg = typeArgs[i];
    final _Type paramTy = funTy.positionalParameters[i];
    if (!(isSubtype(arg._runtimeType, paramTy))) {
      return false;
    }
  }

  // Check named arguments. Since the shape check passed we know that passed
  // names exist in named parameters of the function.
  int namedParamIdx = 0;
  int namedArgIdx = 0;
  while (namedArgIdx * 2 < namedArgs.length) {
    final Symbol argName = namedArgs[namedArgIdx * 2];
    if (identical(argName, funTy.namedParameters[namedParamIdx].name)) {
      if (!isSubtype(namedArgs[namedArgIdx * 2 + 1]._runtimeType,
          funTy.namedParameters[namedParamIdx].type)) {
        return false;
      }
      namedParamIdx += 1;
      namedArgIdx += 1;
    } else {
      namedParamIdx += 1;
    }
  }

  return true;
}
```

</details>

**Comment by osa1** [comment]
> Function.apply and dynamic invocations of gets will both call the same shape and type checking functions. For calling the actual function, Function.apply will call the special vtable entry mentioned above. In dynamic invocations of gets we don't need that, we know the call shape, so we can get the vtable index (ClosureRepresentation.fieldIndexForSignature) and call it directly.

I just realized that even in dynamic invocations of gets we currently cannot use the known compile-time shape of the call to get the vtable index, because the shape and type checks will be done in a dynamic forwarder, which gets the arguments in lists. So we don't have that information in the call site.

We could pass one extra argument to invocation forwarders for the vtable index, to be used when the member is a getter or field.

Or we call the same sequence of code as `Function.apply` and calculate the vtable index in runtime.

**Comment by osa1** [comment]
> We could pass one extra argument to invocation forwarders for the vtable index, to be used when the member is a getter or field.

I started implementing this. It works fine, until I try to actually call the vtable entry. The problem is in the call site we have arguments in lists, but the vtable entry is a Wasm function with some number of arguments. The Wasm block that will push the arguments in lists to the stack needs to have return type list known in compile time.

So it seems like we can't use a single forwarder for all invocations of a member name, we need separate forwarders based on number of arguments. Also, the forwarders need to be specialized on number of type, positional, and named args. A forwarder for member "m" with 1 pos and 1 named arg cannot be reused for dynamic invocation of the same member, but with 2 pos args. The forwarder code for the first case will look like:

```
push(positionalArgs[0]);
push(namedArgs[0]);
call(vtableEntry)
```

In the second case it will look like:

```
push(positionalArgs[0]);
push(positionalArgs[1]);
call(vtableEntry)
```

We can't use loops to push args as Wasm block return values need to be known in compile time.

Same problem exists in `Function.apply` as well. We can't have a single call site to the actual function that unpacks lists of arguments and calls the actual function. There needs to be different Wasm functions  for pushing a specific (known in compile time) number of arguments to the stack, and those Wasm functions should be in the vtable so that we can call them in `Function.apply`.

**Comment by osa1** [comment]
I think for the problem of passing variable number of arguments to a Wasm function we need pre-generated "apply" functions. For example, "apply_1_2_3" takes lists of type, positional, and named arguments, and a Wasm function index, unpacks 1 type arg, 2 positional args, 3 named arguments, and calls the Wasm function.

Alternatively we could combine all kinds of arguments into a single list and have "apply_N". I don't know if we need separate lists, single list would probably simpler.

We could then put all of these "apply" functions in a static array/list, and do `APPLY_FNS[num_args](arg_list, target_function)`.

**Comment by askeksa-google** [comment]
> For this part I think we will need a vtable entry that takes the arguments as lists (same as forwarders), and call the right vtable entry. This vtable entry should have a known index (probably 0) so that it can be called in `Function.apply`.

There are two approaches we can take here:
1. Call the right vtable entry
2. Call the inner function directly

For option 1 we can use a single dispatcher for all functions, since it can switch on the shape of the call and then cast the vtable to the appropriate type and call the vtable entry. So we don't even need an extra vtable entry. On the other hand, it has more call overhead, is probably more complex to generate, and it only works if the vtable actually contains an entry for the call shape, which means it won't work for `Function.apply`. It could also hinder later tree shaking of closure trampolines.

Option 2 is more general and more efficient, but requires generating a separate trampoline for every function, which results in larger code size overhead.

> I just realized that even in dynamic invocations of gets we currently cannot use the known compile-time shape of the call to get the vtable index, because the shape and type checks will be done in a dynamic forwarder, which gets the arguments in lists. So we don't have that information in the call site.

True. It could still make sense to call the right vtable entry directly for dynamic function calls, since this will allow us to omit some of the dynamic call trampolines. If `Function.apply` is not used, we only need to generate the trampoline for functions whose signature is compatible with some dynamic method call that might hit a getter. If `Function.apply` is used, we just generate all of them.

> We could then put all of these "apply" functions in a static array/list, and do `APPLY_FNS[num_args](arg_list, target_function)`.

I think it makes more sense to either put them as dynamic call entries in the vtables or as a single dispatch function as discussed earlier.

> ```dart
> // TODO: param.name is String, not Symbol, but it should be Symbol?
> ```

Indeed it makes sense to use symbols in the type representation and canonicalize them to constants such that they can be compared more efficiently to the incoming constant symbols.

This will require a canonicalization step in `Function.apply` where each symbol in the map is mapped to the constant symbol with the same name.

**Comment by osa1** [comment]
> There are two approaches we can take here:
> 
> - Call the right vtable entry
> - Call the inner function directly
> 
> ...
>
> Option 2 is more general and more efficient, but requires generating a separate trampoline for every function, which results in larger code size overhead.

How would option 2 handle filling in default values for missing optional arguments?

**Comment by askeksa-google** [comment]
> How would option 2 handle filling in default values for missing optional arguments?

Since in option 2 the trampoline is specific to the function, it knows the default values. So for each of the parameters, if it is optional, it needs to check if it is passed, and if not, use the default value. Due to the preceding shape check, it doesn't need to handle named parameters that the function does not accept, nor missing required named parameters.

**Comment by osa1** [comment]
"to fix #50661" part in the commit message caused confusion. Opening again.

**Comment by osa1** [comment]
We discussed this in chat, here's my summary of the ideas discussed and how we want to implement this:

- Re: `apply_N` functions: `apply_N` for applying N arguments to a function does not work, because type and other arguments have different Wasm types: type of type arguments is `ref _Type`, term arguments is `ref null #Top`. So we would need `apply_N_M` for some number of type and term arguments.

- So what we want instead is, for every vtable entry, we generate one function for that entry that takes arguments in lists, pushes the values in lists to the stack, and calls the vtable entry.

  Since a vtable entry is for a specific number of types, positionals, and names, we know how many values to push to the stack in these new vtable entries for dynamic calls. 

When calling a dynamic invocation forwarder we pass the index to the vtable entry (or some kind of reference) so that if in the dynamic forwarder we find that the member is a getter or a field, we check its type and shape (using the functions shown above), and then call its vtable entry (the variant that takes list arguments) using the extra vtable index argument.

(Commit referenced above refactors dynamic forwader types so that we can pass extra stuff to invocation forwarders)

## vtable entries with list arguments

For now I'm calling those "vtable entry wrappers" or just "wrappers".

Wrappers take list arguments, and each wrapper calls a specific vtable entry with the right number of arguments pushed to the stack, from the lists.

To be able to call the actual vtable entry, we need to also pass either the vtable struct, or Wasm function index, or Wasm function reference to the vtable entry function. It doesn't matter which one of these we pass.

In a dynamic invocation site we calculate the vtable index. We need to pass that index (an `i32`) to the forwarder as we don't have the closure being called at this point, so we can't get the vtable and index it there.

The forwarder will have to get the wrapper from the index. Since vtable entries at the same index will have the same signature, we can have a list of wrappers, and do `WRAPPERS[vtableIndex](typeArgs, posArgs, namedArgs, vtable)` or also index the vtable in the call site: `WRAPPERS[vtableIndex](typeArgs, posArgs, namedArgs, vtable[vtableIndex])`.

## Using wrappers in `Function.apply`

The only difference between `Function.apply` and dynamic invocations of gets is how we calculate the vtable index.

With dynamic invocations, vtable index is known in compile time and passed to the forwarder to be used if the invoked member turns out to be a field or getter.

With `Function.apply`, we need to somehow calculate the vtable index using the runtime values of arugment list lengths. I have some ideas on how to do this (we may want to refactor how we map arg numbers to vtable indices).

Once we compute the vtable index, we can use the same wrapper functions to call the actual vtable entry.

Shape and type checking functions will also be reused.

**Comment by osa1** [comment]
Unfortunately the "wrapper" functions described above cannot be used in `Function.apply`. This is because we generate vtable entries for named argument combinations that appear in the code, but with `Function.apply` we can have named argument combinations that are valid, but not known to be used in compile time.

We could generate vtable entries for all valid combinations of named arguments, but that will lead to exponential number of vtable entries.

So for `Function.apply` we want a separate vtable entry, that will take positional and named arguments in lists. It will push arguments in lists to the stack, with default values for missing default parameters (which is done by vtable entries), and call the actual closure function.

(Type arguments are not passed to this vtable entry because application of type arguments is a separate step and needs to be done before `Function.apply`)

So `Function.apply` will work like this:

1. Shape and type check arguments, using a version of the shape and type checking functions given above that assume no type arguments. When type checking, the function type parameters should be substituted with default bounds.

2. If we use a different list type for arguments in the vtable entry, convert the Dart list for positional arguments and the Dart map for the named arguments to the expected list types.

   This step will also canonicalize/intern the symbols in the named argument map so that the vtable entry can use reference equality when comparing passed names with parameter names. This also needs to be done in dynamic invocations, when generating the named argument lists to be passed to the forwarder.

3. Call the new vtable entry that takes positional and named argument as lists.

4. The vtable entry knows about the number of positional and named parameters, and which parameters are optional, in compile time. So it pushes values in lists to the stack without using loops, with default values of missing optional parameters, and calls the actual closure function.

The code generated per closure implementation is minimal: they just push values from lists to the stack and call the actual closure functions.

Once this is implemented, we can use the same idea (with some tweaks) for dynamic invocations of gets. Since dynamic invocations can have type arguments, step 1 needs different type checking and will instantiate the closure when type arguments are passed. Step (2) will also be a bit different since named arguments are passed to forwarders as lists, rather than maps, but the idea is the same. Steps (3) and (4) are the same in both cases.

**Comment by osa1** [comment]
An update needed to the design above to handle the case when the closure being invoked (both in `Function.apply`, and dynamic invocations of fields/gets) has type parameters.

We have two ways of calling a closure with type parameters:

- We instantiate it, then call it without type arguments. This is expensive, so we want to avoid this when possible.
- We call it with the right number of type arguments passed. This is more efficient.

To pass the right number of type arguments in `Function.apply` and dynamic invocations of gets, the shape checking needs to be slightly different:

- In `Function.apply`: because it's not possible to pass type arguments in `Function.apply`, the shape checker will return a `List<_Type>` with default type bounds. As an optimization, it can return a nullable list for the cases when the closure does not have type parameters.

- In dynamic invocations of gets: we can pass type arguments in dynamic invocations, so the shape checker will take a `List<_Type>` as argument. For the shape check to pass, it needs to be empty, or have the right number of types. If it's empty, the shape checker will update the list with default bounds. If not, the list is not modified.

The list adjusted or returned by the shape checker will then be passed to the dynamic call vtable entry, which pushes the type arguments to the stack the same way it pushes positional and named arguments to the stack.

**Comment by askeksa-google** [comment]
A slight variation:

- The shape checker takes a list of type arguments. If it has the right length, it returns it. If not (i.e. if it's empty but the function is generic) it returns a newly constructed list with the default types for the type parameters.
- `Function.apply` always supplies an empty list of type arguments to the shape checker.

I think this is better than modifying the input list, as it enables callers to pass a constant empty list.

**Comment by askeksa-google** [comment]
I'd suggest implementing this in (at least) three steps:
1. Change the function type representation to use constant symbols instead of strings (a meaningful optimization in its own right).
2. Implement dynamic function call and dynamic getter-as-method call via a general shape/type checking function and a dynamic call vtable entry.
3. Implement `Function.apply` on top of the dynamic call mechanism.

**Comment by osa1** [comment]
> Change the function type representation to use constant symbols instead of strings (a meaningful optimization in its own right).

I filed #50915 for this. It's not a blocker for this issue so we can discuss and implement it separately.

**Comment by osa1** [comment]
I implemented dynamic invocations of gets (not `Function.apply`) in https://dart-review.googlesource.com/c/sdk/+/278505.

The code will need some refactoring and documentation, for now I'm just trying to get it working, and there's one issue left.

After shape and type checks pass, I have a closure as `ref null #Top`, and I need to convert it to a struct ref with the vtable field, get the vtable, then index the vtable to get the dynamic call entry (which is the first entry in the vtable).

For that I defined these struct types:

```dart

class Translator {
  ...
  /// Type of vtable struct with just the dynamic call entry.
  late final w.StructType vtableWithDynamicEntryStructType =
      m.addStructType("#VtableBase", fields: [
    w.FieldType(
        w.RefType.def(dynamicCallVtableEntryFunctionType, nullable: false),
        mutable: false)
  ]);

  /// Type of closure structs with just the vtable field
  late final w.StructType closureWithVtableStructType =
      m.addStructType("#ClosureWithVtable", fields: [
    // Class ID
    w.FieldType(w.NumType.i32),
    // Hash code
    w.FieldType(w.NumType.i32),
    // Receiver or context
    w.FieldType(w.RefType.data(nullable: false)),
    // Vtable with just the dynamic call entry
    w.FieldType(
        w.RefType.def(vtableWithDynamicEntryStructType, nullable: false),
        mutable: false),
  ]);
  ...
}
```

The idea is that a all closure structs should have a struct type that is a subtype of `closureWithVtableStructType`, so I should be able to downcast the `ref null #Top` after type and shape checks to the type in `closureWithVtableStructType`.

However that currently fails with "illegal cast" in runtime. That's the whole error message so I don't know what exactly is going wrong.

@askeksa-google this cast should work, right? Maybe I'm doing something else wrong.

**Comment by osa1** [comment]
I wonder if this is a V8 bug. When I print the types I see this:

- Type of closure being casted: `[ var i32, var i32, var ref data, const ref #Vtable-0-0, const ref _FunctionType ]`
- `#Vtable-0-0` fields: `[ <dynamic entry function type>, <another function type> ]`
- Closure struct the object being cast to: `[ var i32, var i32, var ref data, const ref #VtableBase ]`
- `#VtableBase` fields: `[ <dynamic entry function type> ]`

The target type has less fields. First 3 fields have same types. The last field of the target struct is a supertype of the object's field. This cast should be an upcast.

**Comment by askeksa-google** [comment]
Subtype relations in WasmGC are explicit. The `closureWithVtableStructType` struct is not on the explicit supertype chain of the struct of the actual struct of the closure, therefore the cast fails.

To add the extra vtable entry, just add it at the beginning of every vtable struct, including `vtableBaseStruct`, rather than defining any new structs. The closure structs stay the same. And then adjust all vtable indices accordingly.

To match the added field, the initialization of the vtable in `Translator.getClosure` should add a reference to the concrete dynamic entry point for the closure before all other entries in the vtable.

**Comment by osa1** [comment]
https://dart-review.googlesource.com/c/sdk/+/278505 is ready for reviews. It does not fix `dynamic_call_through_getter_test.dart` because that also requires using the `call` member of the dynamic object, which we currently don't implement. I will implement it separately.
