### ISSUE TITLE
Analyzer hangs on records in a Map made const

### ISSUE THREAD

**Issue by jr1221** [dart-lang/sdk#50673]
The analyzer mysteriously hangs when a certain line is sent to it.  This may just be half-baked records as I am on the dev release, yet I wanted to make an issue  here just in case this wasn't known.
```
> /usr/bin/dart --version
Dart SDK version: 3.0.0-0.0.dev (dev) (Mon Dec 5 21:23:45 2022 -0800) on "linux_x64"
```

Code at which the analyzer silently (at least as far as I could tell) stops:
```
const test =  <int,(int a,)> {0: (1,),};
```
In the analyzer code completion logs its last input was `cons test =  <int,(int a,)> {0: (1,),};` as I typed `const` and the next thing I type to remove the word `const`.  The analyzer does not parse any other part of the project while the `const` is present.

This also seems to happen if a record appears as a key, or the record is in any way different (multiple fields, named, etc.).

Sorry If this is already a known side effect of the new records experiment.

**Comment by bwilkerson** [comment]
@scheglov 

This appears to be a problem with serializing constants that contain record type annotations. Using the following test case (in a subclass of `PubPackageResolutionTest`):
```
@soloTest
void test_issue() async {
  await assertNoErrorsInCode('const test =  <int,(int a,)> {0: (1,),};');
}
```
I was able to produce the following stack trace:
```
Exception: Missing implementation of visitRecordTypeAnnotationImpl
  #0      ThrowingAstVisitor._throw (package:analyzer/dart/ast/visitor.dart:2794:5)
  #1      ThrowingAstVisitor.visitRecordTypeAnnotation (package:analyzer/dart/ast/visitor.dart:2658:62)
  #2      RecordTypeAnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10958:20)
  #3      AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:905:19)
  #4      AstBinaryWriter.visitTypeArgumentList (package:analyzer/src/summary2/ast_binary_writer.dart:766:5)
  #5      TypeArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:13272:50)
  #6      AstBinaryWriter._writeNode (package:analyzer/src/summary2/ast_binary_writer.dart:899:10)
  #7      AstBinaryWriter._writeOptionalNode (package:analyzer/src/summary2/ast_binary_writer.dart:921:7)
  #8      AstBinaryWriter.visitSetOrMapLiteral (package:analyzer/src/summary2/ast_binary_writer.dart:667:5)
  #9      SetOrMapLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:11443:50)
  #10     ResolutionSink._writeNode (package:analyzer/src/summary2/bundle_writer.dart:776:10)
  #11     ResolutionSink._writeOptionalNode (package:analyzer/src/summary2/bundle_writer.dart:793:7)
  #12     BundleWriter._writeTopLevelVariableElement (package:analyzer/src/summary2/bundle_writer.dart:487:21)
  #13     BundleWriter._writeList (package:analyzer/src/summary2/bundle_writer.dart:382:19)
  #14     BundleWriter._writeUnitElement (package:analyzer/src/summary2/bundle_writer.dart:538:5)
  #15     BundleWriter.writeLibraryElement (package:analyzer/src/summary2/bundle_writer.dart:111:5)
  #16     Linker._writeLibraries (package:analyzer/src/summary2/link.dart:297:20)
  #17     Linker.link (package:analyzer/src/summary2/link.dart:98:5)
  <asynchronous suspension>
  #18     link (package:analyzer/src/summary2/link.dart:37:3)
  <asynchronous suspension>
  #19     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:180:24)
  <asynchronous suspension>
  #20     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:246:7)
  <asynchronous suspension>
  #21     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
  <asynchronous suspension>
  #22     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:244:5)
  <asynchronous suspension>
  #23     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1327:9)
  <asynchronous suspension>
  #24     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
  <asynchronous suspension>
  #25     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1047:24)
  <asynchronous suspension>
  #26     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2130:7)
  <asynchronous suspension>
```

**Comment by scheglov** [comment]
This was fixed in 3802bc7e32d831cea9e559e17404943e9f8600d2.
