### ISSUE TITLE
developer::postEvent breaks if second argument is a const

### ISSUE THREAD

**Issue by sma** [dart-lang/sdk#50713]
Looks like that

```
import 'dart:developer';
void main() {
  postEvent('foo', const {'bar': 32});
}
```

throws an exception:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Cannot modify unmodifiable map
#0      _UnmodifiableMapMixin.[]= (dart:collection/maps.dart:269:5)
#1      postEvent (dart:developer/extension.dart:183:12)
#2      main (package:app_jam_tellorium/main.dart:11:3)
#3      _runMain.<anonymous closure> (dart:ui/hooks.dart:131:23)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

Here's my configuration:

```
[✓] Flutter (Channel master, 3.7.0-8.0.pre.6, on macOS 13.1 22C65 darwin-arm64, locale de-DE)
    • Flutter version 3.7.0-8.0.pre.6 on channel master at /Users/sma/Work/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 028c6e29e0 (6 hours ago), 2022-12-13 21:18:21 -0800
    • Engine revision 14194c40ec
    • Dart version 3.0.0 (build 3.0.0-19.0.dev)
    • DevTools version 2.20.0
```

I'm on macOS 13.2.

I think, the problem is [this line](https://github.com/dart-lang/sdk/blob/main/sdk/lib/developer/extension.dart#L183)  which was changed yesterday.

**Comment by lrhn** [comment]
The error looks like it comes from the new line 184, which was 183 before the new lines was added.
That's where someone tries to modify a map, which is what the error message says cannot be done.

**Comment by Zekfad** [comment]
The related change and line is here: https://github.com/dart-lang/sdk/commit/fd6fa010ec2f9eafcb2355662e0850b36ef5ba74#diff-97999b1ff40a2f1ff496ce005191b4b52d6beaed0259a02933d545f4f88c3e0aR183
