### ISSUE TITLE
The CFE crashes on attempting to report an error

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#50781]
The crash is discovered in the following test.

* co19/LanguageFeatures/Patterns/record_A01_t08

The top of the stacktrace is as follows:

```
Unhandled exception:
  Crash when compiling file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/record_A01_t08.dart at character offset 1718:
No name provided

#0      _withArgumentsDuplicatedDeclarationCause (package:_fe_analyzer_shared/src/messages/codes_generated.dart:2509:21)
#1      BodyBuilder.declareVariable (package:front_end/src/fasta/kernel/body_builder.dart:775:27)
#2      BodyBuilder.beginSwitchCase (package:front_end/src/fasta/kernel/body_builder.dart:7253:13)
#3      Parser.parseStatementsInSwitchCase (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8452:14)
#4      Parser.parseSwitchBlock (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8423:15)
#5      Parser.parseSwitchStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8344:13)
#6      Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5292:14)
```

The error was encountered during work on https://dart-review.googlesource.com/c/sdk/+/276524.

This issue is assigned label `area-front-end` tentatively, and it needs further investigation, and possibly reassignment of the tags.

**Comment by chloestefantsova** [comment]
The issue appears to be fixed by now.
