### ISSUE TITLE
Type information isn't fully available in patterns

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#50780]
The following tests fail on the bots, and the root of the issue is some uninferred types left after the analysis procedure worked on the patterns.

* co19/LanguageFeatures/Patterns/map_A01_t02
* co19/LanguageFeatures/Patterns/map_A01_t03

Example of a stack trace.

```
stderr:
Unhandled exception:
  Crash when compiling file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/map_A01_t02.dart at character offset 1987:
Internal problem: Unhandled ImplicitTypeArgument in _IsKnownVisitor.

#0      internalProblem (package:front_end/src/fasta/problems.dart:57:5)
#1      unhandled (package:front_end/src/fasta/problems.dart:71:10)
#2      ImplicitTypeArgument.accept (package:front_end/src/fasta/kernel/implicit_type_argument.dart:36:11)
#3      _IsKnownVisitor.visitInterfaceType (package:front_end/src/fasta/type_inference/type_schema.dart:151:25)
#4      InterfaceType.accept (package:kernel/ast.dart:11979:42)
#5      isKnown (package:front_end/src/fasta/type_inference/type_schema.dart:15:41)
#6      InferenceVisitorBase.findInterfaceMember (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1095:36)
#7      ListPattern.transform (package:front_end/src/fasta/kernel/internal_ast.dart:4379:56)
#8      MapPattern.transform (package:front_end/src/fasta/kernel/internal_ast.dart:4996:12)
#9      InferenceVisitorImpl.visitPatternSwitchStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:7795:68)
#10     PatternSwitchStatement.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:452:20)
#11     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:156:26)
#12     InferenceVisitorImpl._visitStatements (package:front_end/src/fasta/type_inference/inference_visitor.dart:740:50)
#13     InferenceVisitorImpl.visitBlock (package:front_end/src/fasta/type_inference/inference_visitor.dart:761:31)
#14     Block.accept (package:kernel/ast.dart:9694:43)
#15     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:158:26)
#16     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:187:17)
#17     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1307:43)
```

The error was encountered during work on https://dart-review.googlesource.com/c/sdk/+/276524.

This issue is assigned label `area-front-end` tentatively, and it needs further investigation, and possibly reassignment of the tags.

**Comment by chloestefantsova** [comment]
More potential inference issues, similar to those failures mentioned above.

* co19/LanguageFeatures/Patterns/object_A04_t01
* co19/LanguageFeatures/Patterns/list_A01_t02
* co19/LanguageFeatures/Patterns/list_A01_t03
* co19/LanguageFeatures/Patterns/object_A02_t05
* co19/LanguageFeatures/Patterns/object_A02_t06

**Comment by chloestefantsova** [comment]
More potential inference issues:

* co19/LanguageFeatures/Patterns/object_A02_t07
* co19/LanguageFeatures/Patterns/record_A02_t06
* co19/LanguageFeatures/Patterns/record_A04_t02

**Comment by chloestefantsova** [comment]
More of the potential inference issues:

* co19/LanguageFeatures/Patterns/list_A01_t01
* co19/LanguageFeatures/Patterns/map_A01_t01
* co19/LanguageFeatures/Patterns/object_A02_t04
* co19/LanguageFeatures/Patterns/record_A01_t01
* co19/LanguageFeatures/Patterns/record_A01_t04
