### ISSUE TITLE
Riverpod error when running devtool

### ISSUE THREAD

**Issue by chunhtai** [dart-lang/sdk#50804]
It seems like a change in dart may have break the code in riverpod. This is the error message when running the devtool, which in turn uses riverpod.

```
flutter: [ERROR]: Unsupported operation: Cannot modify unmodifiable map

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building View-[GlobalObjectKey
SingletonFlutterWindow#f9f57]:
Unsupported operation: Cannot modify unmodifiable map

When the exception was thrown, this was the stack:
#0      _UnmodifiableMapMixin.[]= (dart:collection/maps.dart:269:5)
#1      postEvent (dart:developer/extension.dart:184:12)
#2      debugPostEvent (package:riverpod/src/devtool.dart:22:15)
#3      RiverpodBinding.containers= (package:riverpod/src/devtool.dart:84:5)
#4      new ProviderContainer.<anonymous closure> (package:riverpod/src/framework/container.dart:124:39)
#5      new ProviderContainer (package:riverpod/src/framework/container.dart:129:8)
#6      ProviderScopeState.initState (package:flutter_riverpod/src/framework.dart:179:17)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5128:55)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4971:5)
...     Normal element mounting (7 frames)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3977:16)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3706:18)
#17     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1194:16)
#18     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1163:5)
#19     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1110:18)
#20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2706:19)
#21     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1109:13)
#22     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:943:7)
#23     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:923:7)
#34     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 10 frames from class _Timer, dart:async, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by kenzieschmoll** [comment]
@CoderDake is this related to the recent changes you made to dart developer postEvent? also CC @rrousselGit this error is originating from flutter_riverpod

**Comment by rrousselGit** [comment]
It's being fixed.

**Comment by DanTup** [comment]
I don't know if it's exactly the same, but there's a similar issue at https://github.com/dart-lang/sdk/issues/50713 (and CL at https://dart-review.googlesource.com/c/sdk/+/275984).

**Comment by nakqeeb** [comment]
I'm facing the same issue. I spent a lot of time trying to figure out the problem but I'm not able to resolve it.

**Comment by CoderDake** [comment]
I merged the fix about a week ago. It is into flutter master now :)
Let me know if you continue to see this issue anywhere :)
