### ISSUE TITLE
Some of the tests fail on UnimplementedError in shared_type_analyzer.dart

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#50812]
The following tests fail throwing an `UnimplementedError`.

* co19/LanguageFeatures/Patterns/logical_and_A05_t01
* co19/LanguageFeatures/Patterns/logical_or_A04_t01
* co19/LanguageFeatures/Patterns/logical_or_A04_t03

An example of the stack trace is as follows:

```
Unhandled exception:
  Crash when compiling file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/logical_and_A05_t01.dart at character offset 1029:
UnimplementedError: TODO(scheglov)

#0      SharedTypeAnalyzerErrors.duplicateRecordPatternField (package:front_end/src/fasta/type_inference/shared_type_analyzer.dart:66:5)
#1      TypeAnalyzer._reportDuplicateRecordPatternFields (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:1857:19)
#2      TypeAnalyzer.analyzeObjectPattern (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:934:5)
#3      InferenceVisitorImpl.visitObjectPattern (package:front_end/src/fasta/type_inference/inference_visitor.dart:9126:5)
#4      ObjectPattern.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:4559:20)
#5      InferenceVisitorImpl.visitAndPattern (package:front_end/src/fasta/type_inference/inference_visitor.dart:9052:19)
#6      AndPattern.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:3843:20)
#7      InferenceVisitorImpl.dispatchPattern (package:front_end/src/fasta/type_inference/inference_visitor.dart:8790:12)
#8      TypeAnalyzer.analyzeSwitchStatement (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:1307:11)
#9      InferenceVisitorImpl.visitPatternSwitchStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:7736:9)
#10     PatternSwitchStatement.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:452:20)
```

The failures are discovered during the work on https://dart-review.googlesource.com/c/sdk/+/275923. The issue is created to track the approved test status changes. The label `area-front-end` is applied tentatively, and after an investigation the labels may need to be changed.

**Comment by chloestefantsova** [comment]
More of the failing tests:

* co19/LanguageFeatures/Patterns/list_A01_t04
* co19/LanguageFeatures/Patterns/record_A02_t02
* co19/LanguageFeatures/Patterns/record_A02_t03
* co19/LanguageFeatures/Patterns/record_A02_t04
* co19/LanguageFeatures/Patterns/record_A03_t01
* co19/LanguageFeatures/Patterns/record_A04_t01
* co19/LanguageFeatures/Patterns/record_A02_t08
* co19/LanguageFeatures/Patterns/map_A05_t01

An example of the stack trace is as follows:

```
Unhandled exception:
  Crash when compiling file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/list_A01_t04.dart at character offset 1070:
UnimplementedError: TODO(paulberry)

#0      SharedTypeAnalyzerErrors.patternTypeMismatchInIrrefutableContext (package:front_end/src/fasta/type_inference/shared_type_analyzer.dart:94:5)
#1      TypeAnalyzer.analyzeDeclaredVariablePattern (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:386:15)
#2      InferenceVisitorImpl.visitVariablePattern (package:front_end/src/fasta/type_inference/inference_visitor.dart:9102:29)
#3      VariablePattern.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:5547:20)
#4      InferenceVisitorImpl.visitListPattern (package:front_end/src/fasta/type_inference/inference_visitor.dart:9201:15)
#5      ListPattern.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:4371:20)
#6      InferenceVisitorImpl.dispatchPattern (package:front_end/src/fasta/type_inference/inference_visitor.dart:8873:12)
#7      TypeAnalyzer.analyzePatternVariableDeclarationStatement (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:1042:5)
#8      InferenceVisitorImpl.visitPatternVariableDeclaration (package:front_end/src/fasta/type_inference/inference_visitor.dart:8268:5)
#9      PatternVariableDeclaration.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:5029:20)
#10     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:157:26)
#11     InferenceVisitorImpl._visitStatements (package:front_end/src/fasta/type_inference/inference_visitor.dart:741:50)
#12     InferenceVisitorImpl.visitBlock (package:front_end/src/fasta/type_inference/inference_visitor.dart:762:31)
#13     Block.accept (package:kernel/ast.dart:9694:43)
```

/cc @stereotype441

**Comment by chloestefantsova** [comment]
More of the related cases

* co19/LanguageFeatures/Patterns/logical_or_A04_t02
* co19/LanguageFeatures/Patterns/variable_A03_t01
* co19/LanguageFeatures/Patterns/wildcards_A01_t01

**Comment by scheglov** [comment]
I think it behaves as intended, for now.
Clients - CFE and analyzer have to implement this method, and report the problem in a client specific way.

**Comment by chloestefantsova** [comment]
Thanks @scheglov! I guess I was confused by the error originating in the file `shared_type_analyzer.dart`. I'll implement the missing members then.

**Comment by stereotype441** [comment]
Yeah, I guess the name of that file is kind of confusing, since it doesn't contain the shared type analyzer, but instead the front end code that interfaces with it.  I'm open to suggestions for better names (or @chloestefantsova feel free to just rename that file if you'd like).
