### ISSUE TITLE
Can't use `Process.run` with default Dockerfile using `FROM SCRATCH`

### ISSUE THREAD

**Issue by ltOgt** [dart-lang/sdk#50837]
# Problem
When using the default recommended `Dockerfile`
(generated e.g. via `dart create -t server-shelf docker_process_issue`)
the resulting container throws on `Process.run` and `Process.start`

```
Unhandled exception:
ProcessException: No such file or directory
  Command: <command> <arguments>
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578)
#3      Process.run (dart:io-patch/process_patch.dart:49)
#4      main (file:///app/bin/server.dart:33)
<asynchronous suspension>
```

# Steps to reproduce
1) run `dart create -t server-shelf docker_process_issue`
   - note this is not related to the `shelf` package, its just that this template gives the `Dockerfile`
2) add the following code to the end of `bin/server.dart`
   ```dart
   final result = await Process.run("echo", ["hello"]);
   stdout.write(result.stdout);
   stderr.write(result.stderr);
   ```
   - Note that instead of `echo`, e.g. mounting any script  (`docker -v <path_to_script>:<path_inside_container>`) leads to the same exception
3) Follow the docker instructions in `README.md`
   ```
   $ docker build . -t myserver
   $ docker run -it -p 8080:8080 myserver
   ```
4) Observe the exception mentioned above

# Works when not using `FROM SCRATCH`
5) Now comment out the following lines in the `Dockerfile`
   ```
   # FROM scratch
   # COPY --from=build /runtime/ /
   # COPY --from=build /app/bin/server /app/bin/
   ```
6) Rebuild as in step (3)
7) Observe that the issue no longer occurs, and `Process.run` can be used

# Tried on
* Dart SDK Version (`dart --version`)
  - Dart SDK version: 3.0.0-61.0.dev (dev) (Thu Dec 22 13:45:21 2022 -0800) on "macos_arm64"
  - Dart SDK version: 2.18.6 (stable) (Unknown timestamp) on "linux_x64"
* Whether you are using Windows, MacOSX, or Linux
  - tested both on MacOS and Linux

____
Im not that familiar with docker, in fact I was using this template to get started.

If this is not actually a bug, this limitation should at least be mentioned in the `README.md`,
as it took me quite a while to figure this out

**Comment by ltOgt** [comment]
It seems this is mainly my lack of understanding of docker.

as far as i understand it now `FROM SCRATCH` does not include a shell, which is why `Process.run` does not work.

so i guess this issue is mainly about adding that to the `README.md` since spawning sub processes from a server is not too unusual

**Comment by sortie** [comment]
cc @athomas in case you have thoughts

**Comment by brianquinlan** [comment]
The current generated code looks like:
```
# Build minimal serving image from AOT-compiled `/server`
# and the pre-built AOT-runtime in the `/runtime/` directory of the base image.
FROM scratch
COPY --from=build /runtime/ /
COPY --from=build /app/bin/server /app/bin/
```

I think that adding a note would be reasonable e.g.
```
# and the pre-built AOT-runtime in the `/runtime/` directory of the base image.
# A different Base Image can be used if additional functionality is required e.g. a shell.
```
