### ISSUE TITLE
[records] dart2js encounters unhandled exception with a program using a potentially constant record

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#50903]
Consider the following program:

```dart
class A {
  final (int, int) r;
  const A(int i): r = (1, i);
}

void main() {
  print('const A(2): ${const A(2)}');
}
```

This program causes `dart compile js --enable-experiment=records` to crash with the following output:

```
Info: Compiling with sound null safety.
n002.dart:6:6:
Internal Error: The compiler crashed when compiling this element.
void main() {
     ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.19.0-421.0.dev), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Unsupported operation: Unexpected constant RecordConstant(const (1.0, 2.0)) (RecordConstant).
#0      ConstantValuefier.defaultConstant (package:compiler/src/ir/visitors.dart:233:5)
#1      ConstantValuefier.visitRecordConstant (package:compiler/src/ir/visitors.dart:318:12)
#2      _ConstantCallbackVisitor.visitRecordConstant (package:kernel/visitor.dart:949:17)
#3      RecordConstant.accept (package:kernel/ast.dart:14165:42)
#4      ComputeOnceConstantVisitor.visitConstant (package:kernel/visitor.dart:995:52)
#5      KernelImpactConverter.registerFieldConstantInitialization (package:compiler/src/kernel/kernel_impact.dart:808:28)
#6      ImpactData.apply.<anonymous closure> (package:compiler/src/ir/impact_data.dart:1418:20)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#8      ImpactData.apply (package:compiler/src/ir/impact_data.dart:1416:12)
#9      KernelImpactConverter.convert (package:compiler/src/kernel/kernel_impact.dart:880:16)
#10     KernelToElementMap.computeWorldImpact (package:compiler/src/kernel/element_map_impl.dart:1524:22)
#11     KernelWorkItem.run.<anonymous closure>.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:403:47)
#12     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#13     KernelWorkItem.run.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:402:28)
#14     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#15     KernelWorkItem.run (package:compiler/src/kernel/kernel_strategy.dart:374:26)
#16     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:809:70)
#17     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#18     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:809:32)
#19     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:807:28)
#21     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:805:18)
#23     ResolutionEnqueuer._forEach (package:compiler/src/resolution/enqueuer.dart:236:12)
#24     ResolutionEnqueuer.forEach (package:compiler/src/resolution/enqueuer.dart:252:5)
#25     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:801:16)
#26     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#27     Compiler.emptyQueue (package:compiler/src/compiler.dart:800:14)
#28     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:824:7)
#29     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#30     Compiler.processQueue (package:compiler/src/compiler.dart:818:14)
#31     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:406:5)
#32     Compiler.produceClosedWorld (package:compiler/src/compiler.dart:608:11)
#33     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:734:15)
<asynchronous suspension>
#34     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:352:7)
<asynchronous suspension>
#35     Compiler.runInternal (package:compiler/src/compiler.dart:351:5)
<asynchronous suspension>
#36     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:272:11)
<asynchronous suspension>
#37     main (package:compiler/src/dart2js.dart:1435:3)
<asynchronous suspension>
```

Presumably this is just because records haven't been fully implemented at this point, but I thought it might be helpful to report it anyway, just in case this kind of program was already expected to work.

**Comment by rakudrama** [comment]
This now compiles.
