### ISSUE TITLE
Compiler Unhandled exception: RangeError (index): Invalid value: Only valid value is 0: 1

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/sdk#50910]
Compiler crashes with unhandled exception if you **mix order** of **named** and **positional** arguments when calling **static method** of an **extension**.

<details>
<summary>Sample code</summary>

```dart
void main(List<String> arguments) {
}

void test(int positional, {int named1 = 0, int named2 = 0}) {}
class Sueta {
  static void test(int positional, {int named1 = 0, int named2 = 0}) {}
}
extension SuetaExtension on Sueta {
  static void test(int pos, {int named1 = 0, int named2 = 0}) {}
}

void test1() {
  test(named1: 0, 1, named2: 0);
}

void test2() {
  Sueta.test(named1: 0, 1, named2: 0);
}

/// cannot compile
void test3() {
  SuetaExtension.test(named1: 0, 1, named2: 0);
}
```
</details>

Reproducible on dart.pad: https://dartpad.dev/?id=f30e144153e7e21f9d61bc97f025846c

DartPad cannot compile this code with sdk 2.18.6
Here's flutter version from my workstation:
```
Flutter 3.7.0-14.0.pre.45 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0a2e0a4730 (73 minutes ago) • 2023-01-05 09:04:15 -0800
Engine • revision bb4015269d
Tools • Dart 3.0.0 (build 3.0.0-85.0.dev) • DevTools 2.20.0
```

**Comment by mit-mit** [comment]
This appears to be a front-end issue:

```
mit-macbookpro6:tmp mit$ dart run args.dart
Crash when compiling file:///Users/mit/tmp/args.dart at character offset 432:
RangeError (index): Invalid value: Only valid value is 0: 1

#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      InferenceVisitorBase._inferInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1774:50)
#2      InferenceVisitorBase.inferInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1497:12)
#3      InferenceVisitorImpl.visitStaticInvocation (package:front_end/src/fasta/type_inference/inference_visitor.dart:7570:40)
#4      StaticInvocation.accept1 (package:kernel/ast.dart:6969:9)
#5      InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:184:27)
#6      InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:219:40)
#7      InferenceVisitorImpl.visitExpressionStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:1165:40)
#8      ExpressionStatement.accept (package:kernel/ast.dart:9638:43)
#9      InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:162:26)
#10     InferenceVisitorImpl._visitStatements (package:front_end/src/fasta/type_inference/inference_visitor.dart:746:50)
#11     InferenceVisitorImpl.visitBlock (package:front_end/src/fasta/type_inference/inference_visitor.dart:767:31)
#12     Block.accept (package:kernel/ast.dart:9694:43)
#13     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:162:26)
#14     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:190:17)
#15     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1315:43)
#16     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1114:19)
#17     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:376:5)
#18     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3608:14)
#19     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3350:14)
#20     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:585:14)
#21     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:403:15)
#22     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1266:12)
<asynchronous suspension>
#23     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:675:7)
<asynchronous suspension>
#24     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:608:7)
<asynchronous suspension>
#25     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#26     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#27     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#28     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#29     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#30     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#31     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:398:11)
<asynchronous suspension>
#32     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:207:45)
<asynchronous suspension>
#33     _processLoadRequest (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:866:37)
<asynchronous suspension>

```
