### ISSUE TITLE
Implement Function.apply in dart2wasm

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#50925]
There are new test failures on [[vm] Update number of parent function type arguments](https://dart-review.googlesource.com/c/sdk/+/278525).

The tests
```
language/regress/regress50905_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2wasm-hostasserts-linux-x64-d8
```

Log:
```
/====================================================================================\
| language/regress/regress50905_test is new and failed (RuntimeError, expected Pass) |
\====================================================================================/

--- Command "dart2wasm" (took 695ms):
DART_CONFIGURATION=ReleaseX64 sdk/bin/dart2wasm_developer -Dtest_runner.configuration=dart2wasm-hostasserts-linux-x64-d8 /b/s/w/ir/tests/language/regress/regress50905_test.dart /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2wasm-hostasserts-linux-x64-d8/tests_language_regress_regress50905_test/regress50905_test.wasm

exit code:
0

stdout:
Unimplemented external member Function.apply at org-dartlang-sdk:///lib/core/function.dart:143:19

--- Command "d8" (took 34ms):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/third_party/d8/linux/d8 --experimental-wasm-gc --experimental-wasm-stack-switching --experimental-wasm-type-reflection pkg/dart2wasm/bin/run_wasm.js -- /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2wasm-hostasserts-linux-x64-d8/tests_language_regress_regress50905_test/regress50905_test.wasm

exit code:
1

stdout:
wasm-function[765]:0x22bb6: RuntimeError: unreachable
RuntimeError: unreachable
    at Function.apply (wasm://wasm/000a99a2:wasm-function[765]:0x22bb6)
    at main (wasm://wasm/000a99a2:wasm-function[54]:0x15f06)
    at main tear-off (wasm://wasm/000a99a2:wasm-function[55]:0x16024)
    at _invokeMain (wasm://wasm/000a99a2:wasm-function[65]:0x16305)
    at Module.invoke (/b/s/w/ir/pkg/dart2wasm/bin/dart2wasm_runtime.mjs:416:28)
    at main (pkg/dart2wasm/bin/run_wasm.js:50:21)

1 pending unhandled Promise rejection(s) detected.

Deobfuscated error and stack:
wasm-function[765]:0x22bb6: RuntimeError: unreachable
RuntimeError: unreachable
    at     at Function.apply (wasm://wasm/000a99a2:wasm-function[765]:0x22bb6) unparsed
    at     at main (wasm://wasm/000a99a2:wasm-function[54]:0x15f06)            unparsed
    at     at main tear-off (wasm://wasm/000a99a2:wasm-function[55]:0x16024)   unparsed
    at     at _invokeMain (wasm://wasm/000a99a2:wasm-function[65]:0x16305)     unparsed
    at Module.invoke                                                           pkg/dart2wasm/bin/dart2wasm_runtime.mjs 416:28
    at main                                                                    pkg/dart2wasm/bin/run_wasm.js 50:21
    at                                                                         unparsed
    at 1 pending unhandled Promise rejection(s) detected.                      unparsed


--- Re-run this test:
python3 tools/test.py -n dart2wasm-hostasserts-linux-x64-d8 language/regress/regress50905_test
```

**Comment by osa1** [comment]
We've been working on this and we have a design in #50925. I will be implementing it soon.

**Comment by osa1** [comment]
`Function.apply` is being implemented in https://dart-review.googlesource.com/c/sdk/+/278749. (WIP, not ready for reviews)

The CL is huge because it includes a few other CLs needed to make `Function.apply` work. I will rebase it as we merge other CLs. The final CL should be small.
