### ISSUE TITLE
[dart:io] Dart cannot open a socket on localhost

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#50941]
When running the following code in `main()` of a Flutter application (i.e. before the UI has started up):

```
  final socket = await Socket.connect('localhost', 8080);
```

I get the following error. Notice that the port number is wrongly reported as `port = 50730` (this is the first problem).

```
E/flutter (30451): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 50730
E/flutter (30451): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
E/flutter (30451): #1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:948:12)
E/flutter (30451): #2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1815:26)
E/flutter (30451): #3      RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)
E/flutter (30451): #4      Socket._connect (dart:io-patch/socket_patch.dart:2038:22)
E/flutter (30451): #5      Socket.connect (dart:io/socket.dart:743:21)
E/flutter (30451): #6      main
```

However, connecting to the server using `telnet localhost 8080` works fine (this is the second problem: using any other method to open the socket does not result in a connection refused error).

Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "linux_x64"
Server: ServerPod on Linux (Fedora)
Client: running the above `Socket.connect` code in Android emulator

**Comment by lukehutch** [comment]
Closing -- the problem was that on the Android emulator, `10.0.2.2` is the address of the host machine, not `localhost`.

https://developer.android.com/studio/run/emulator-networking
