### ISSUE TITLE
Crash when compiling switch on record literal

### ISSUE THREAD

**Issue by Mike278** [dart-lang/sdk#50963]
I was playing around with some of the WIP new language features and came across this crash. 

Version: `3.0.0-edge.0a05e3f9994d58f3c8c83bc5721cc3bdf6ec5779`
Experiments: `--enable-experiment=records,patterns`

This prints 1 as expected:
```dart
final x = (1,2);
print(switch (x) { var _ => 1 });
```

but this crashes:
```dart
print(switch ((1,2)) { var _ => 1});
// Crash when compiling:
// Internal problem: Unsupported operation: 'InternalRecordLiteral.accept1 on ConstantsTransformer'.
```

<details><summary>Full stack trace</summary>

```
Crash when compiling:
Internal problem: Unsupported operation: 'InternalRecordLiteral.accept1 on ConstantsTransformer'.

#0      internalProblem (package:front_end/src/fasta/problems.dart:57:5)
#1      unsupported (package:front_end/src/fasta/problems.dart:85:10)
#2      InternalExpression.accept1 (package:front_end/src/fasta/kernel/internal_ast.dart:624:12)
#3      RemovingTransformer.transform (package:kernel/visitor.dart:1766:17)
#4      ConstantsTransformer.visitVariableDeclaration (package:front_end/src/fasta/kernel/constant_evaluator.dart:622:28)
#5      VariableDeclaration.accept1 (package:kernel/ast.dart:11315:9)
#6      RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1802:21)
#7      RemovingTransformer.transformList (package:kernel/visitor.dart:2035:19)
#8      RemovingTransformer.transformStatementList (package:kernel/visitor.dart:1989:5)
#9      Block.transformOrRemoveChildren (package:kernel/ast.dart:9739:7)
#10     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2058:10)
#11     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:640:48)
#12     TreeVisitor1.visitBlock (package:kernel/visitor.dart:645:38)
#13     Block.accept1 (package:kernel/ast.dart:9725:58)
#14     RemovingTransformer.transform (package:kernel/visitor.dart:1766:17)
#15     BlockExpression.transformOrRemoveChildren (package:kernel/ast.dart:9329:16)
#16     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2058:10)
#17     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:459:50)
#18     TreeVisitor1.visitBlockExpression (package:kernel/visitor.dart:613:7)
#19     BlockExpression.accept1 (package:kernel/ast.dart:9303:9)
#20     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1802:21)
#21     RemovingTransformer.transformList (package:kernel/visitor.dart:2035:19)
#22     RemovingTransformer.transformExpressionList (package:kernel/visitor.dart:1961:5)
#23     Arguments.transformOrRemoveChildren (package:kernel/ast.dart:5719:7)
#24     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2058:10)
#25     TreeVisitor1.visitArguments (package:kernel/visitor.dart:745:46)
#26     Arguments.accept1 (package:kernel/ast.dart:5700:53)
#27     RemovingTransformer.transform (package:kernel/visitor.dart:1766:17)
#28     StaticInvocation.transformOrRemoveChildren (package:kernel/ast.dart:7005:21)
#29     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2058:10)
#30     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:459:50)
#31     TreeVisitor1.visitStaticInvocation (package:kernel/visitor.dart:531:7)
#32     ConstantsTransformer.visitStaticInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:901:18)
#33     StaticInvocation.accept1 (package:kernel/ast.dart:6984:9)
#34     RemovingTransformer.transform (package:kernel/visitor.dart:1766:17)
#35     ExpressionStatement.transformOrRemoveChildren (package:kernel/ast.dart:9690:22)
#36     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2058:10)
#37     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:640:48)
#38     TreeVisitor1.visitExpressionStatement (package:kernel/visitor.dart:643:7)
#39     ExpressionStatement.accept1 (package:kernel/ast.dart:9670:9)
#40     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1802:21)
#41     RemovingTransformer.transformList (package:kernel/visitor.dart:2035:19)
#42     RemovingTransformer.transformStatementList (package:kernel/visitor.dart:1989:5)
#43     Block.transformOrRemoveChildren (package:kernel/ast.dart:9739:7)
#44     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2058:10)
#45     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:640:48)
#46     TreeVisitor1.visitBlock (package:kernel/visitor.dart:645:38)
#47     Block.accept1 (package:kernel/ast.dart:9725:58)
#48     RemovingTransformer.transform (package:kernel/visitor.dart:1766:17)
#49     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:578:19)
#50     FunctionNode.accept1 (package:kernel/ast.dart:4158:9)
#51     RemovingTransformer.transform (package:kernel/visitor.dart:1766:17)
#52     ConstantsTransformer.visitProcedure.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:487:23)
#53     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3871:18)
#54     ConstantsTransformer.visitProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:485:23)
#55     Procedure.accept1 (package:kernel/ast.dart:3549:55)
#56     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1802:21)
#57     RemovingTransformer.transformList (package:kernel/visitor.dart:2035:19)
#58     RemovingTransformer.transformProcedureList (package:kernel/visitor.dart:1917:5)
#59     ConstantsTransformer.convertLibrary (package:front_end/src/fasta/kernel/constant_evaluator.dart:421:5)
#60     transformLibraries (package:front_end/src/fasta/kernel/constant_evaluator.dart:119:26)
#61     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1531:19)
#62     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:638:7)
<asynchronous suspension>
#63     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#64     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#65     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#66     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#67     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#68     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#69     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:398:11)
<asynchronous suspension>
#70     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:207:45)
<asynchronous suspension>
#71     _processLoadRequest (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:866:37)
<asynchronous suspension>
```
</details>

**Comment by johnniwinther** [comment]
@Mike278, thanks for reporting this. A fix is on the way.
