### ISSUE TITLE
StackTrace broken when using Future.timeout()

### ISSUE THREAD

**Issue by andyduke** [dart-lang/sdk#51005]
When using `Future.timeout()`, `_StringStackTrace` is passed in `catchError` instead of `StackTrace`.

### Code
```dart
void main() async {

  var f1 = Future<dynamic>.delayed(
    const Duration(milliseconds: 2),
    () {
      throw Exception('Future1 Exception');
    }
  );
  
  f1.catchError(
    (error, stackTrace) {
      print('Future1 error: $error (${stackTrace.runtimeType})\n$stackTrace');
      return Future<dynamic>.error('Future1 error', stackTrace);
    }
  );
  
  // ---
  
  var f2 = Future<dynamic>.delayed(
    const Duration(milliseconds: 3),
    () {
      throw Exception('Future2 Exception');
    }
  ).timeout(const Duration(milliseconds: 2));
  
  f2.catchError(
    (error, stackTrace) {
      print('\nFuture2 error: $error (${stackTrace.runtimeType})\n$stackTrace');
      return Future<dynamic>.error('Future2 error', stackTrace);
    }
  );
}
```

### Output
```
Future1 error: Exception: Future1 Exception (_StackTrace)
Exception: Future1 Exception
    at Object.wrapException (<anonymous>:334:17)
    at main_closure.call$0 (<anonymous>:4395:15)
    at Future_Future$delayed_closure.call$0 (<anonymous>:3696:39)
    at _TimerImpl_internalCallback.call$0 (<anonymous>:3655:21)
    at invokeClosure (<anonymous>:518:26)
    at <anonymous>:536:18
Uncaught Error: Future1 error

Future2 error: TimeoutException after 0:00:00.002000: Future not completed (_StringStackTrace)

Uncaught Error: Future2 error
```

### Explanation
In the first case, `Future.timeout()` is not used and a `StackTrace` object is passed to the `stackTrace` parameter in `catchError`.

In the second case, when using the `timeout()` method on the `Future`, the `_StringStackTrace` object is passed to the `stackTrace` parameter in `catchError`, and the call stack is lost.

### Dart SDK version
* dartpad.dev - Flutter 3.3.10 Dart SDK 2.18.6
* dev pc - Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.17134.1], locale ru-RU)
    • Flutter version 3.3.9 on channel stable at D:\Flutter2Live\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (7 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

**Comment by lrhn** [comment]
This is intended behavior.

If the timer times out, the returned future is completed with a `TimeoutException` object.
This happens inside a `Timer` callback, because that's how we know the timerout timed out.
There is no call stack to preserve at the time when a timer callback triggers.
The actual stack trace will be nothing but the event loop, and then an internal `dart:async` function. 

The code in question is:
```dart
      timer = new Timer(timeLimit, () {
        _future._completeError(
            new TimeoutException("Future not completed", timeLimit),
            StackTrace.empty);
      });
```

It *could* use `StackTrace.current` instead of `StackTrace.empty` at that point, but that would *always* give precisely:
```
#0      _Future.timeout.<anonymous closure> (dart:async/future_impl.dart::856:13)
#1      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#2      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#3      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```
which is not an improvement over just an empty stack trace, it just takes longer to create.

**Comment by andyduke** [comment]
I ran into this issue when calling an HTTP API. After the timeout, I would like to send an error to the analytics service, but I need to know where it occurs, when using `Future.timeout()` - an empty stack is sent to the analytics. The problem is that the stack is empty and does not show the place in the code where exactly this is called from.

In general, the fact that an exception occurs when the timeout is triggered, but with an empty stack is unexpected and not obvious, I did not find anything about this in the documentation.

**Comment by andyduke** [comment]
Maybe it makes sense to save the stack before the timer and pass it to the exception? Then it will be more clear what caused the timeout.

**Comment by lrhn** [comment]
Saving a stack eagerly is an expensive and unnecessary overhead in most situations.
It's not what we do in other asynchronous functions because errors should be rare, but creating the stack trace costs whether you need it or not.

We can document that the default timeout exception has an empty stack trace, then it's up to the user to decide whether they want to do:
```dart
var stack = StackTrace.current;
var f2 = future.timeout(duration, onTimeout: () => 
    Future.error(TimeoutException("Future not completed", duration), stack));
```
if they *want* to capture an extra stack-trace 

Alternatively you can use `package:stack_trace` to [run the code in a zone](https://pub.dev/documentation/stack_trace/latest/stack_trace/Chain/capture.html) which does capture stack traces at every asynchronous gap. It obviously has a cost, but you might be able to limit it to where it's most useful.

**Comment by andyduke** [comment]
> We can document that the default timeout exception has an empty stack trace, then it's up to the user to decide whether they want to do

This would clarify the situation.
