### ISSUE TITLE
[dart2wasm] Incorrect vtable or vtable index generation in call with named args

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#51008]
```dart
void foo({bool z = false, required double w}) {}

void main() {
  (foo)(w: 3.14);
}
```

Output:

```
RuntimeError: unreachable
    at #dummy function (ref struct, ref null #Top) -> (ref null #Top) (wasm://wasm/000b24ca:wasm-function[354]:0x1c21a)
    at main (wasm://wasm/000b24ca:wasm-function[53]:0x15eeb)
    at main tear-off (wasm://wasm/000b24ca:wasm-function[55]:0x15efd)
    at _invokeMain (wasm://wasm/000b24ca:wasm-function[65]:0x16227)
    at Module.invoke (/home/omer/dart/sdk/test/test.mjs:412:28)
    at main (/home/omer/dart/sdk/sdk/pkg/dart2wasm/bin/run_wasm.js:61:21)
```

We're calling a vtable entry that is not supposed to be used. Either the vtable index we calculate at the call site is incorrect, or the vtable is missing some entries.

**Comment by osa1** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/279019.
