### ISSUE TITLE
Analysis-server snapshot failed on ventura arm

### ISSUE THREAD

**Issue by chenrui333** [dart-lang/sdk#51017]
it is bit weird that analysis-server snapshot built out successfully in my local, but failed in the homebrew CI (and it only failed on one os, ventura arm), below is the error message:

```
  output: Analyzing with an empty driver cache:
  Analyzing /private/tmp/dart-sdk-20230113-6098-ylqmfp/sdk-2.18.7/sdk/pkg/compiler/lib...
  Completed in 35.4s.
  
  Analyzing with a populated driver cache:
  Analyzing /private/tmp/dart-sdk-20230113-6098-ylqmfp/sdk-2.18.7/sdk/pkg/compiler/lib...
  Completed in 0.0s.
  Completed in 0.0s.
  Unhandled exception:
  Bad state: Future already completed
  #0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
  #1      DevAnalysisServer.processDirectories.handleStatusNotification (package:analysis_server/src/server/dev_server.dart:62:24)
  #2      DevAnalysisServer.processDirectories.<anonymous closure> (package:analysis_server/src/server/dev_server.dart:124:9)
  #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
  #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
  #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
  #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
  #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
  #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
  #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
  #10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
  #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
  #12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

relates to https://github.com/Homebrew/homebrew-core/pull/120454

**Comment by chenrui333** [comment]
Anyone can help this thread?

**Comment by chenrui333** [comment]
Actually [dart-sdk 2.19.0](https://github.com/Homebrew/homebrew-core/pull/121521) builds out fine now.

**Comment by chenrui333** [comment]
seeing issue again in [2.19.1 release build](https://github.com/Homebrew/homebrew-core/pull/122052)

**Comment by chenrui333** [comment]
Seems good again with [dart-sdk 2.19.2 build](https://github.com/Homebrew/homebrew-core/pull/122777)

**Comment by chenrui333** [comment]
Still need some help on this, https://github.com/Homebrew/homebrew-core/pull/125103

**Comment by chenrui333** [comment]
@parlough even with pulling this commit, https://github.com/dart-lang/sdk/commit/597d7e4d824da0f5f7dcd8f0573e0b50ac039e5d

I can still see the same issue in the homebrew build

```
  FAILED: gen/analysis_server.dart.snapshot 
  python3 ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=../../.dart_tool/package_config.json --snapshot=gen/analysis_server.dart.snapshot --snapshot-depfile=gen/analysis_server.dart.snapshot.d --snapshot-kind=app-jit --dfe=../../utils/analysis_server/NEVER_LOADED gen/utils/analysis_server/analysis_server.dart.dill --sdk=/private/tmp/dart-sdk-20231201-5519-kt7o4f/sdk-3.2.2/sdk/sdk/ --train-using=/private/tmp/dart-sdk-20231201-5519-kt7o4f/sdk-3.2.2/sdk/pkg/compiler/lib
  Command failed: /private/tmp/dart-sdk-20231201-5519-kt7o4f/sdk-3.2.2/sdk/xcodebuild/ReleaseARM64/dart --deterministic --packages=../../.dart_tool/package_config.json --snapshot=gen/analysis_server.dart.snapshot --snapshot-depfile=gen/analysis_server.dart.snapshot.d --snapshot-kind=app-jit --dfe=../../utils/analysis_server/NEVER_LOADED gen/utils/analysis_server/analysis_server.dart.dill --sdk=/private/tmp/dart-sdk-20231201-5519-kt7o4f/sdk-3.2.2/sdk/sdk/ --train-using=/private/tmp/dart-sdk-20231201-5519-kt7o4f/sdk-3.2.2/sdk/pkg/compiler/lib
  output: Analyzing with an empty driver cache:
  Analyzing /private/tmp/dart-sdk-20231201-5519-kt7o4f/sdk-3.2.2/sdk/pkg/compiler/lib...
  Completed in 29.9s.
  
  Analyzing with a populated driver cache:
  Analyzing /private/tmp/dart-sdk-20231201-5519-kt7o4f/sdk-3.2.2/sdk/pkg/compiler/lib...
  Completed in 0.0s.
  Completed in 0.0s.
  Unhandled exception:
  Bad state: Future already completed
  #0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
  #1      DevAnalysisServer.processDirectories.handleStatusNotification (package:analysis_server/src/server/dev_server.dart:62:24)
  #2      DevAnalysisServer.processDirectories.<anonymous closure> (package:analysis_server/src/server/dev_server.dart:124:9)
  #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
  #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
  #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
  #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
  #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
  #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
  #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
  #10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
  #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
  #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
  #13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
  
  [3759/3773] ACTION //utils/kernel-service:kernel-service_snapshot(//build/toolchain/mac:clang_arm64)
  [3760/3773] ACTION //utils/compiler:dart2js(//build/toolchain/mac:clang_arm64)
  ninja: build stopped: subcommand failed.
  buildtools/ninja/ninja -C xcodebuild/ReleaseARM64 create_sdk
  BUILD FAILED
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/7064359241/job/19232347778?pr=156057

**Comment by parlough** [comment]
Hmm, thanks for the heads up. I'm not sure the patch is applying to the code running since the stack trace:

```
#1      DevAnalysisServer.processDirectories.handleStatusNotification (package:analysis_server/src/server/dev_server.dart:62:24)
```

Suggests the future is being completed on line 62, which is where it's completed before my fix. After the commit, it's completed on [line 66](https://github.com/dart-lang/sdk/blob/6db741440d226704633d1534df006fb22cf9d477/pkg/analysis_server/lib/src/server/dev_server.dart#L66).

**Comment by chenrui333** [comment]
yeah, looks like more of a build issue sequence issue on the brew side. :)

@parlough Any timeline that we can cut off a new release to include this change? Thanks!

**Comment by parlough** [comment]
Since this affects builds from the source tree, not the built releases, I don't think this change would be cherry-picked to a 3.2 stable release. As a result, for stable releases, Dart 3.3.0 should be the first include the fix if nothing changes before then.

**Comment by chenrui333** [comment]
Do we have timeline for the 3.3.0 release? (side note, this is kind of recurring issue for the build process)
