### ISSUE TITLE
[dart2wasm] Null deref in runtime type checks

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#51018]
```dart
void main() {
  f<T extends num, U extends T>() => U;
  print((f as dynamic)());
}
```

Fails with this in runtime:

```
Null check operator used on a null value
    at _TypeUniverse.isSubtype (wasm://wasm/000b4496:wasm-function[223]:0x19723)
    at _checkClosureType (wasm://wasm/000b4496:wasm-function[461]:0x1e4ed)
    at method forwarder for 'call' (wasm://wasm/000b4496:wasm-function[458]:0x1e1d5)
    at main (wasm://wasm/000b4496:wasm-function[53]:0x1618f)
    at main tear-off (wasm://wasm/000b4496:wasm-function[55]:0x161a4)
    at _invokeMain (wasm://wasm/000b4496:wasm-function[65]:0x164d3)
    at Module.invoke (/home/omer/dart/sdk/test/test.mjs:414:28)
    at main (/home/omer/dart/sdk/sdk/pkg/dart2wasm/bin/run_wasm.js:61:21)
```

The problem is in this line when checking the second type parameter: https://github.com/dart-lang/sdk/blob/fed2e8b59fa3f4168bd82f354f00e05a673d00b0/sdk/lib/_internal/wasm/lib/type.dart#L1004

Here the `null` env arguments are used because `T` in `U extends T` need to be resolved during the check.

Test failures caused by this bug:

- language/generic/function_bounds_test/01
- language/generic/function_bounds_test/03

**Comment by osa1** [comment]
It turns out the issue here was the missing type parameter defaults, which was implemented in f9abd48ae5f. The smaller repro and `function_bounds_test` both work as expected now.
