### ISSUE TITLE
Improve the stacktrace of the error thrown by Stream.first

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#51025]
Hello!

I recently hit an issue where a `Stream.first` usage in my codebase threw with the following stacktrace:

![image](https://user-images.githubusercontent.com/20165741/212767479-f1396fe8-3fef-4f49-81cb-0ef1c75de08c.png)

As you can see, that stacktrace contains no valuable information besides saying that `Stream.first` is the issue.
In a codebase that uses `Stream.first` multiple times, this isn't enough information to determine which `Stream.first` is throwing, as it could be any of them.

Would it be possible to have `Stream.first`'s stacktrace include the trace from where `.first()` was invoked?

In my situation, I ended-up replacing all usages of `Stream.first` with the following custom implementation:

```dart
extension X<T> on Stream<T> {
  Future<T> get firstX {
    final fromStack = StackTrace.current;
    return firstWhere(
      (element) => true,
      orElse: () => throw StateError(
        'No element found for $T'
        'created at \n $fromStack',
      ),
    );
  }
}
```

This gave the following error report:

![image](https://user-images.githubusercontent.com/20165741/212767978-19d9a78c-82e1-4c73-8d05-8dc222b00f80.png)

As you can see, the error is much more helpful this time. It now points to the `.first()` invocation, helping me determine which Stream was the problem out of potentially many streams

**Comment by rrousselGit** [comment]
This probably could be applied to all stream transformers that might throw.

There are other similar issues with different transformers. Such as when doing `stream.map(Class.new)` where `Class.new` throws

**Comment by mraleph** [comment]
Capturing stack traces is expensive (at least in the way it is currently implemented) that why, for example, we moved away from doing that on every async function entry.

That being said we certainly need to improve our async causal stack traces to also cover more cases, e.g. I am surprised that the code like this:

```dart
import 'dart:async';

void main() async {
  final stream = Stream<int>.fromIterable(<int>[]);
  await stream.first;
}
```

does not produce a causal stack trace portion as opposed to the code like this:

```
void main() async {
  final future = Future(() async {
    await null;
    throw 'error';
  });
  await future;
}
```

which produces:

```
$ dart /tmp/test.dart
Unhandled exception:
error
#0      main.<anonymous closure> (file:///tmp/test.dart:10:5)
<asynchronous suspension>
#1      main (file:///tmp/test.dart:12:3)
<asynchronous suspension>
```

I would expect `await stream.first` to have similar causal portion which shows the code awaiting on `stream.first` future.

**Comment by christerswahn** [comment]
Upvoting this issue.

We've had this happen intermittently in production and that in combination with the stack trace being empty has made it really hard to track down exactly where it is happening.

Looking at the `stream.first` implementation:

```dart
      onDone: () {
        var stack = StackTrace.empty;
        var error = IterableElementError.noElement();
        _trySetStackTrace(error, stack);
        _completeWithErrorCallback(future, error, stack);
      },
```

It explicitly sets the stack trace to empty!

I see two issues with the rationale that stack traces are expensive to capture:

1. This is throwing an exception, i.e. an error path as opposed to the normal successful path. It is _very rarely_ that fast error handling should take priority of adequate error information. In addition, the non-stream .first throws this error with stack trace so this case should not behave differently.

2. If stack trace capture is so expensive as to making us avoid doing it, then that should be a high priority in itself to fix.

**Comment by mraleph** [comment]
@lrhn do you know why `Stream.first` discards stack trace like that? It does not even give the awaiter stack unwinding a chance to provide a better stack trace by simply setting it to `empty`.

> I see two issues with the rationale that stack traces are expensive to capture:
> 
> 1. This is throwing an exception, i.e. an error path as opposed to the normal successful path. It is _very rarely_ that fast error handling should take priority of adequate error information. In addition, the non-stream .first throws this error with stack trace so this case should not behave differently.

The problem is that with async code you need to capture stack trace _when you start async operation_. At that point you don't yet know whether or not you are going to hit an error. This means you have to eagerly capture stack traces in a many points of the program and that _is_ in fact very expensive. 

I think we can make it much-much cheaper (at least for synchronous portion of the stack trace), but it is never going to be extremely cheap.

**Comment by lrhn** [comment]
It doesn't discard any stack trace. I just doesn't *create* one. (Or it does, the empty trace.)

(The implementation has no idea what an "awaiter stack" is. I also don't have much idea what the awaiter stack is, or how you interact with it, so I also wouldn't write code with that in mind. Any documentation I should read? Should the created `_Future` be associated with something when it's created?)

The error is created when a stream closing without any prior event.
No error has been thrown and no stack trace created. The on-done callback creates a new error object to report the lack of an event. It creates a stack trace because it needs a stack trace to complete the future, to eventually call `_Future.completeWithError`, so it uses the default stack trace, which is the empty one.


That error didn't happen at any particular point, rather the problem is that _nothing_ happened, so there is no relevant stack trace. Using the position of the _done_ handler isn't any more meaningful than having no stack trace at all, it's just that at some point after the stream has closed, the `first` completes saying that it never got an event, which it does using an error result.

So the stack trace is empty because there is no relevant code position to associate with the error, not to save allocating a stack trace. Using the "current stack trace" would give *exactly the same* stack trace every time an error is created here, first the event loop, then the `Stream.first.<anonymous closure>` that receives the _done_ event (although possibly wrapped by zones).

**Comment by rrousselGit** [comment]
At minimum for this specific example I'd expect the stacktrace to be that of the "close" call or whatever Stacktrace.current is, instead of empty

**Comment by christerswahn** [comment]
I recognize there can be implementation challenges. But please consider regular user code of this API. Somewhere in the codebase there will be a line something like this example:

```dart
  record = await myStream.first.timeout(Duration(seconds: 2));
```

Perhaps sometimes it will unexpectedly fail with StateError due to missing content, rather than producing the record or timing out. By the time the top-level exception barrier catches this and reports it to Sentry we have very little information where it happened. This is not good.

Note that List().first throws StateError with normal stack trace on missing element. This one is documented to throw the same exception under the same condition.

**Comment by mraleph** [comment]
I have done a simple test:

```dart
import 'dart:async';

extension MyFirst1<T> on Stream<T> {
  Future<T> get myFirst1 async {
    await for (var v in this) {
      return v;
    }
    throw StateError('no elements');
  }
}

extension MyFirst2<T> on Stream<T> {
  Future<T> get myFirst2 {
    @pragma('vm:awaiter-link')
    final c = Completer<T>();
    late final StreamSubscription sub;
    sub = this.listen(
      (v) {
        c.complete(v);
        sub.cancel();
      },
      onDone: () {
        if (!c.isCompleted) {
          c.completeError(StateError('no elements'), StackTrace.current);
        }
      },
    );
    return c.future;
  }
}

void main() async {
  print('async form');
  try {
    final stream = Stream<int>.fromIterable(<int>[]);
    await stream.myFirst1;
  } catch (e, st) {
    print(e);
    print(st);
  }

  print('closure based form');
  try {
    final stream = Stream<int>.fromIterable(<int>[]);
    await stream.myFirst2;
  } catch (e, st) {
    print(e);
    print(st);
  }
}
```

Yields

```
async form
Bad state: no elements
#0      MyFirst1.myFirst1 (file:///tmp/x.dart:8:5)
<asynchronous suspension>
#1      main (file:///tmp/x.dart:36:5)
<asynchronous suspension>

closure based form
Bad state: no elements
#0      MyFirst2.myFirst2.<anonymous closure> (file:///tmp/x.dart:24:65)
#1      _RootZone.runGuarded (dart:async/zone.dart:1766:10)
#2      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:434:13)
#3      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:444:7)
#4      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:333:7)
#5      _MultiStreamController.closeSync (dart:async/stream_impl.dart:1209:36)
#6      new Stream.fromIterable.<anonymous closure>.next (dart:async/stream.dart:396:24)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:35)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:127:13)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:5)
```

I am surprised the `myFirst2` does not work, need to look at the code. Maybe we don't handle `onDone` callbacks properly.

**Comment by mraleph** [comment]
Ah, it's because the code in the unwinder only detects `_Future` objects to start the chain. Anyway, I think we can make stack trace much better now. I have sent a CL to @lrhn: https://dart-review.googlesource.com/c/sdk/+/453940

**Comment by christerswahn** [comment]
@mraleph and colleagues, awesomely speedy response!
