### ISSUE TITLE
CFE hits unhandled exception on wrong inline class constructor name

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#51069]
This might simply be because patterns haven't been fully implemented, but I'm reporting it just in case it's helpful. Consider the following program:

```dart
inline class A {
  val value;
  A.name1(this.value);
}

void main() => A.name2(1);
```

This program causes the CFE to terminate with an unhandled exception:

```
Crash when compiling file:///usr/local/google/home/eernst/lang/dart/scratch/202301/n017.dart at character offset 66:
Null check operator used on a null value

#0      BodyBuilder.buildConstructorInvocation (package:front_end/src/fasta/kernel/body_builder.dart:6290:42)
#1      TypeUseGenerator.buildSelectorAccess (package:front_end/src/fasta/kernel/expression_generator.dart:3351:26)
#2      InvocationSelector.withReceiver (package:front_end/src/fasta/kernel/expression_generator.dart:4912:23)
#3      BodyBuilder.doDotOrCascadeExpression (package:front_end/src/fasta/kernel/body_builder.dart:2830:17)
#4      BodyBuilder.endBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:2596:7)
#5      Listener.handleEndingBinaryExpression (package:_fe_analyzer_shared/src/parser/listener.dart:1632:5)
#6      Parser._parsePrecedenceExpressionLoop (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5701:22)
#7      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5639:12)
#8      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5561:15)
#9      Parser.parseExpressionFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5234:13)
#10     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5161:14)
#11     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1113:14)
#12     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:376:5)
#13     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3676:14)
#14     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3418:14)
#15     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:602:14)
#16     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:403:15)
#17     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1266:12)
<asynchronous suspension>
#18     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:675:7)
<asynchronous suspension>
#19     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:608:7)
<asynchronous suspension>
#20     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#21     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#22     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#23     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#24     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#25     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#26     SingleShotCompilerWrapper.compileInternal (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/vm/bin/kernel_service.dart:402:11)
<asynchronous suspension>
#27     Compiler.compile.<anonymous closure> (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/vm/bin/kernel_service.dart:211:45)
<asynchronous suspension>
#28     _processLoadRequest (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/vm/bin/kernel_service.dart:872:37)
<asynchronous suspension>
```

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/280097
