### ISSUE TITLE
CFE hits unhandled exception with switch expression

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#51076]
This might simply be because patterns haven't been fully implemented, but I'm reporting it just in case it is helpful. Consider the following program:

```dart
enum AppButtonType {
  outlined,
  filled;
}

enum Colors {
  redAccent,
  greenAccent;
}

dynamic widget = 0;

final color = switch (widget.type) {
  AppButtonType.outlined => Colors.redAccent,
  AppButtonType.filled => Colors.greenAccent,
};

void main() {}
```

Apparently there are no compile-time errors in this program (and the analyzer accepts it), but with the CFE it causes an unhandled exception:

```
Crash when compiling:
Internal problem: Unsupported operation: 'PropertyGet.accept1 on ConstantsTransformer'.

#0      internalProblem (package:front_end/src/fasta/problems.dart:57:5)
#1      unsupported (package:front_end/src/fasta/problems.dart:85:10)
#2      InternalExpression.accept1 (package:front_end/src/fasta/kernel/internal_ast.dart:624:12)
#3      RemovingTransformer.transform (package:kernel/visitor.dart:1766:17)
#4      ConstantsTransformer.visitVariableDeclaration (package:front_end/src/fasta/kernel/constant_evaluator.dart:622:28)
#5      VariableDeclaration.accept1 (package:kernel/ast.dart:11315:9)
#6      RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1802:21)
#7      RemovingTransformer.transformList (package:kernel/visitor.dart:2035:19)
#8      RemovingTransformer.transformStatementList (package:kernel/visitor.dart:1989:5)
#9      Block.transformOrRemoveChildren (package:kernel/ast.dart:9739:7)
#10     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2058:10)
#11     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:640:48)
#12     TreeVisitor1.visitBlock (package:kernel/visitor.dart:645:38)
#13     Block.accept1 (package:kernel/ast.dart:9725:58)
#14     RemovingTransformer.transform (package:kernel/visitor.dart:1766:17)
#15     BlockExpression.transformOrRemoveChildren (package:kernel/ast.dart:9329:16)
#16     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2058:10)
#17     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:459:50)
#18     TreeVisitor1.visitBlockExpression (package:kernel/visitor.dart:613:7)
#19     BlockExpression.accept1 (package:kernel/ast.dart:9303:9)
#20     RemovingTransformer.transform (package:kernel/visitor.dart:1766:17)
#21     ConstantsTransformer.visitField.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:646:30)
#22     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3871:18)
#23     ConstantsTransformer.visitField (package:front_end/src/fasta/kernel/constant_evaluator.dart:632:41)
#24     Field.accept1 (package:kernel/ast.dart:2650:55)
#25     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1802:21)
#26     RemovingTransformer.transformList (package:kernel/visitor.dart:2035:19)
#27     RemovingTransformer.transformFieldList (package:kernel/visitor.dart:1925:5)
#28     ConstantsTransformer.convertLibrary (package:front_end/src/fasta/kernel/constant_evaluator.dart:422:5)
#29     transformLibraries (package:front_end/src/fasta/kernel/constant_evaluator.dart:119:26)
#30     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1520:19)
#31     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:638:7)
<asynchronous suspension>
#32     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#33     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#34     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#35     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#36     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#37     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#38     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:398:11)
<asynchronous suspension>
#39     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:207:45)
<asynchronous suspension>
#40     _processLoadRequest (file:///b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:866:37)
<asynchronous suspension>
```

**Comment by asashour** [comment]
I think this is fixed. Tested with `Dart SDK version: 3.0.0-179.0.dev (dev) (Fri Jan 27 21:59:59 2023 -0800) on "windows_x64"`

**Comment by eernstg** [comment]
Right, I don't see any unhandled exceptions with a fresh CFE (9fe2529b216e36b5ff8cf03277c70509666f8aa8). Thanks!
