### ISSUE TITLE
[analyzer] Unhandled exception occurs with explicit_instantiation_syntax_test.dart/59

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#51072]
The analyzer encounters an unhandled exception when the following command is executed:

```
> tools/test.py -n analyzer-asserts-linux language/constructor/explicit_instantiation_syntax_test/59
```

<details>
<summary>Here is the stack trace</summary>

```
No build targets found.
Test configuration:
    analyzer-asserts-linux(architecture: x64, compiler: dart2analyzer, mode: release, runtime: none, system: linux, enable-asserts, use-sdk)
Suites tested: language

FAILED: dart2analyzer-none release_x64 language/constructor/explicit_instantiation_syntax_test/59
Expected: Pass
Actual: Crash
Missing expected compile error.

--- Command "dart2analyzer" (took 03.000892s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/gen/dartanalyzer.dart.snapshot -Dtest_runner.configuration=analyzer-asserts-linux --enable-experiment=patterns,records --ignore-unrecognized-flags --packages=/usr/local/google/home/eernst/devel/dart/work/sdk/.dart_tool/package_config.json --format=json /usr/local/google/home/eernst/devel/dart/work/sdk/out/ReleaseX64/generated_tests/language/constructor/explicit_instantiation_syntax_test_59.dart

analyzer json parse result:
- parse failed

exit code:
253

stderr:
Unhandled exception:
Null check operator used on a null value
#0      TypeAnalyzer.analyzeSwitchExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:1378:60)
#1      SwitchExpressionImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:12754:10)
#2      ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:778:16)
#3      TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:442:9)
#4      BinaryExpressionResolver._resolveUserDefinable (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:260:15)
#5      BinaryExpressionResolver.resolve (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:67:7)
#6      ResolverVisitor.visitBinaryExpression (package:analyzer/src/generated/resolver.dart:1927:31)
#7      BinaryExpressionImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:1124:14)
#8      ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:778:16)
#9      TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:442:9)
#10     InvocationInferrer._visitArguments (package:analyzer/src/dart/resolver/invocation_inferrer.dart:523:18)
#11     FullInvocationInferrer.resolveInvocation (package:analyzer/src/dart/resolver/invocation_inferrer.dart:209:36)
#12     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:179:7)
#13     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:971:24)
#14     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:572:16)
#15     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:95:7)
#16     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:285:31)
#17     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:2911:21)
#18     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8999:50)
#19     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4576:17)
#20     ResolverVisitor.visitExpressionStatement (package:analyzer/src/generated/resolver.dart:2403:10)
#21     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4572:50)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9551:20)
#23     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1256:17)
#24     ResolverVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:1937:10)
#25     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1252:50)
#26     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1207:12)
#27     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:1947:12)
#28     BlockFunctionBodyImpl.resolve (package:analyzer/src/dart/ast/ast.dart:1203:16)
#29     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:2869:17)
#30     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8847:50)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9551:20)
#32     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2027:13)
#33     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2016:12)
#34     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2017:50)
#35     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:2055:23)
#36     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2544:50)
#37     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:759:10)
#38     LibraryAnalyzer._parseAndResolve.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:566:7)
#39     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#40     LibraryAnalyzer._parseAndResolve (package:analyzer/src/dart/analysis/library_analyzer.dart:565:11)
#41     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:91:17)
#42     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1346:11)
<asynchronous suspension>
#43     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#44     AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1383:26)
<asynchronous suspension>
#45     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1091:20)
<asynchronous suspension>
#46     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2138:7)
<asynchronous suspension>

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1375:9)
<asynchronous suspension>
#1      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#2      AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1383:26)
<asynchronous suspension>
#3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1091:20)
<asynchronous suspension>
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2138:7)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n analyzer-asserts-linux language/constructor/explicit_instantiation_syntax_test/59
[00:04 | 100% | +    0 | -    1]

=== 0 tests passed, 1 failed ===
```
</details>

[Edit: removed reference to the CL, it has now landed and the correct version of the test is in the SDK.]

**Comment by scheglov** [comment]
We don't have any crashing `language/` tests currently.
So, I think this was fixed.
