### ISSUE TITLE
[cfe] 'Illegal argument' when compiling instance creation on typedef

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#51089]
Consider the following program:

```dart
class A<X, Y> { A(X x, Y y); }
typedef F<X> = A<X, X Function()>;

void main() => F<int>(0, () => 1);
```

This program is accepted by the analyzer, but the CFE static analysis (commit 4a63c9e76fcced6e2023f591e7e8c8253f8f7212) encounters an unhandled exception ('Invalid argument(s)'):

<details><summary>Stack trace</summary>

```
Invalid argument(s): Type parameter TypeParameter(X) is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:3125:8)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2575:38)
#2      TypeParameterType.accept (package:kernel/ast.dart:13178:42)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#4      BinaryPrinter.visitFunctionType (package:kernel/binary/ast_to_binary.dart:2539:7)
#5      FunctionType.accept (package:kernel/ast.dart:12127:42)
#6      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#7      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#8      BinaryPrinter.visitArguments (package:kernel/binary/ast_to_binary.dart:1872:5)
#9      Arguments.accept (package:kernel/ast.dart:5721:38)
#10     BinaryPrinter.writeArgumentsNode (package:kernel/binary/ast_to_binary.dart:460:10)
#11     BinaryPrinter.visitConstructorInvocation (package:kernel/binary/ast_to_binary.dart:1866:5)
#12     ConstructorInvocation.accept (package:kernel/ast.dart:7094:44)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#14     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:545:7)
#15     BinaryPrinter.visitReturnStatement (package:kernel/binary/ast_to_binary.dart:2338:5)
#16     ReturnStatement.accept (package:kernel/ast.dart:10761:43)
#17     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#18     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:545:7)
#19     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1559:5)
#20     FunctionNode.accept (package:kernel/ast.dart:4178:38)
#21     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:453:10)
#22     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1388:5)
#23     Procedure.accept (package:kernel/ast.dart:3570:40)
#24     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:474:10)
#25     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:356:7)
#26     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1132:5)
#27     Library.accept (package:kernel/ast.dart:585:38)
#28     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:467:10)
#29     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:780:9)
#30     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:619:7)
#31     Timeline.timeSync (dart:developer/timeline.dart:166:22)
#32     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:600:14)
#33     serializeComponent (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/vm/bin/kernel_service.dart:1019:11)
#34     _processLoadRequest (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/vm/bin/kernel_service.dart:919:13)
<asynchronous suspension>
```

</details>

**Comment by chloestefantsova** [comment]
I'm working on a fix at https://dart-review.googlesource.com/c/sdk/+/279700
