### ISSUE TITLE
Unable to capture error message?

### ISSUE THREAD

**Issue by Aaron009** [dart-lang/sdk#51081]
```dart
try {
  // throw 'x';
  chatLogic.sendMessage2(v);
}catch(e, s) {
  print('xdfsafas');
}

void sendMessage2(String textContent) async {
  throw 'asas';
}
```

This code is very simple, logically it will definitely go to the catch branch, but I don’t know why it is strange that it doesn’t go to the catch branch in my project. But when I did the minimal example alone, I couldn't reproduce it. So I can only record first.

I don't know why, the output is as follows:
```shell
E/flutter ( 1162): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: asas
E/flutter ( 1162): #0      ChatLogic.sendMessage2 (package:c/chat_logic.dart:714:5)
E/flutter ( 1162): #1      d.c.<anonymous closure> (package:c/message_screen_new.dart:598:39)
E/flutter ( 1162): #2      EditableTextState._finalizeEditing (package:flutter/src/widgets/editable_text.dart:2288:18)
E/flutter ( 1162): #3      EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:2138:9)
E/flutter ( 1162): #4      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1817:37)
E/flutter ( 1162): #5      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1701:20)
E/flutter ( 1162): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:536:55)
E/flutter ( 1162): #7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:529:34)
E/flutter ( 1162): #8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
E/flutter ( 1162): #9      _invoke2 (dart:ui/hooks.dart:186:13)
E/flutter ( 1162): #10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
E/flutter ( 1162): #11     _Channel.push (dart:ui/channel_buffers.dart:132:31)
E/flutter ( 1162): #12     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
E/flutter ( 1162): #13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
E/flutter ( 1162): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
```

**Comment by asashour** [comment]
`sendMessage2` should return `Future`, and it should be `await`ed, e.g.

```dart
Future<void> main() async {
  try {
    await sendMessage2('');
  } catch (e) {
    print('xdfsafas');
  }
}

Future<void> sendMessage2(String textContent) async {
  throw 'asas';
}
```

**Comment by Aaron009** [comment]
> `sendMessage2` should return `Future`, and it should be `await`ed, e.g.
> 
> ```dart
> Future<void> main() async {
>   try {
>     await sendMessage2('');
>   } catch (e) {
>     print('xdfsafas');
>   }
> }
> 
> Future<void> sendMessage2(String textContent) async {
>   throw 'asas';
> }
> ```

Can I catch errors from functions like this globally?

**Comment by asashour** [comment]
There is [discarded_futures](https://dart-lang.github.io/linter/lints/discarded_futures.html) lint which helps on the caller side.

I am searching for a lint (or even a hint) for something like `avoid_null_asynchrouns`.
