### ISSUE TITLE
language_2/async_star/async_star_await_for_test fails on vm platforms

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#51097]
See e.g. [this log](https://dart-ci.appspot.com/log/vm-kernel-win-debug-x64c/dartk-win-debug-x64c/487/language_2/async_star/async_star_await_for_test):
```
--- Command "vm" (took 03.000210s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\cache\builder\sdk\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\dart.exe --no-sound-null-safety -Dtest_runner.configuration=dartk-win-debug-x64c --ignore-unrecognized-flags --packages=C:\b\s\w\ir\cache\builder\sdk\.dart_tool\package_config.json C:\b\s\w\ir\cache\builder\sdk\tests\language_2\async_star\async_star_await_for_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
FAILURE:
Expect.equals(expected: <(^?1!1y1[e1B1$)>, actual: <(^?1!1y1[e1B1$>, 'yield at 1, break at yield') fails.
#0      Expects.equals (file:///C:/b/s/w/ir/cache/builder/sdk/tests/language_2/async_star/async_star_await_for_test.dart:374:30)
#1      main (file:///C:/b/s/w/ir/cache/builder/sdk/tests/language_2/async_star/async_star_await_for_test.dart:220:13)
<asynchronous suspension>

FAILURE:
Expect.equals(expected: <(^?1!1Y1[e1B1$)>, actual: <(^?1!1Y1[e1B1$>, 'yield* then break at 1') fails.
#0      Expects.equals (file:///C:/b/s/w/ir/cache/builder/sdk/tests/language_2/async_star/async_star_await_for_test.dart:374:30)
#1      main (file:///C:/b/s/w/ir/cache/builder/sdk/tests/language_2/async_star/async_star_await_for_test.dart:324:13)
<asynchronous suspension>

FAILURE:
Expect.equals(expected: <(^?1!1Y1[e1<>B1$)>, actual: <(^?1!1Y1[e1<>B1$>, 'yield* then pause then break at 1') fails.
#0      Expects.equals (file:///C:/b/s/w/ir/cache/builder/sdk/tests/language_2/async_star/async_star_await_for_test.dart:374:30)
#1      main (file:///C:/b/s/w/ir/cache/builder/sdk/tests/language_2/async_star/async_star_await_for_test.dart:344:13)
<asynchronous suspension>

Expectations failed: 3, succeeded: 10

#0      Expects.summarize (file:///C:/b/s/w/ir/cache/builder/sdk/tests/language_2/async_star/async_star_await_for_test.dart:365:7)
#1      main (file:///C:/b/s/w/ir/cache/builder/sdk/tests/language_2/async_star/async_star_await_for_test.dart:347:11)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-win-debug-x64c language_2/async_star/async_star_await_for_test
```

it seems this test fails on all VM configurations (and even dart2js).

The one quoted above is from a `flaky -> RuntimeError` change.

/cc @alexmarkov

**Comment by alexmarkov** [comment]
It looks like this test has been failing on the VM since it was added in https://dart-review.googlesource.com/c/sdk/+/86181.
