### ISSUE TITLE
Error writing .dill file for co19/src/LanguageFeatures/Patterns/constant_A02_t17.dart

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#51117]
I ran into this with my typical development workflow when working on DDC. 

Repro:
1) Build the `dartdevc_test` target
2) From the sdk repo root run the "ddb" script `sdk/bin/dart pkg/dev_compiler/tool/ddb tests/co19/src/LanguageFeatures/Patterns/constant_A02_t17.dart -d -r chrome --enable-experiment=patterns,records`
3) This runs DDC from source with assertions enabled. You can see an assertion firing. 

```
Unhandled exception:
'package:kernel/binary/ast_to_binary.dart': Failed assertion: line 82 pos 12: 'index != null': No index found for VariableDeclaration(final const Color #0)
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      BinaryPrinter._getVariableIndex (package:kernel/binary/ast_to_binary.dart:82:12)
#3      BinaryPrinter.visitVariableGet (package:kernel/binary/ast_to_binary.dart:1575:17)
#4      VariableGet.accept (package:kernel/ast.dart:4435:44)
#5      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#6      BinaryPrinter.visitEqualsCall (package:kernel/binary/ast_to_binary.dart:1772:5)
#7      EqualsCall.accept (package:kernel/ast.dart:6692:44)
#8      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#9      BinaryPrinter.visitIfStatement (package:kernel/binary/ast_to_binary.dart:2329:5)
#10     IfStatement.accept (package:kernel/ast.dart:10686:43)
#11     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#12     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#13     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#14     Block.accept (package:kernel/ast.dart:9746:43)
#15     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#16     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:545:7)
#17     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1559:5)
#18     FunctionNode.accept (package:kernel/ast.dart:4178:38)
#19     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:453:10)
#20     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1388:5)
#21     Procedure.accept (package:kernel/ast.dart:3570:40)
#22     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:474:10)
#23     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:356:7)
#24     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1132:5)
#25     Library.accept (package:kernel/ast.dart:585:38)
#26     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:467:10)
#27     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:780:9)
#28     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:619:7)
#29     Timeline.timeSync (dart:developer/timeline.dart:166:22)
#30     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:600:14)
#31     _compile (package:dev_compiler/src/kernel/command.dart:370:32)
<asynchronous suspension>
#32     internalMain (package:dev_compiler/ddc.dart:37:18)
<asynchronous suspension>
```
This points to the assertion here: 
https://github.com/dart-lang/sdk/blob/25fb2d6cb698261ea6952c2d5c61d9e2aaaf5f44/pkg/kernel/lib/binary/ast_to_binary.dart#L82-L83

With assertions disabled, the next line fails throws because `index` is null.

cc @johnniwinther

**Comment by johnniwinther** [comment]
This seem to have been fixed.
