### ISSUE TITLE
Dill file missing when serving web project in Dart 3

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#51129]
I am trying to make [js_bindings](https://pub.dev/packages/js_bindings) example work but I am having this error when trying to serve using DDC. It works OK when using dart2js compiler.

Dart SDK version: 3.0.0-151.0.dev (dev) (Fri Jan 20 22:45:17 2023 -0800) on "macos_x64"

```
webdev serve example

[INFO] Reading cached asset graph completed, took 672ms
[INFO] Checking for updates since last build completed, took 1.2s
[INFO] Serving `example` on http://127.0.0.1:8080
[INFO] Running build completed, took 338ms
[INFO] Caching finalized dependency graph completed, took 504ms
[SEVERE] build_web_compilers:entrypoint on example/main.dart (cached): Bad state: Unable to locate required sdk resource build_web_compilers|lib/src/dev_compiler/dart_sdk.sound.js

[SEVERE] build_web_compilers:sdk_js on asset:build_web_compilers/$package$ (cached): Error compiling dartdevc module:build_web_compilers|lib/src/dev_compiler/dart_sdk.sound.js

Unhandled exception:
PathNotFoundException: Cannot open file, path = '/Users/jonathanrezende/Dart/current/lib/_internal/ddc_platform_sound.dill' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:618:7)
#1      _File.openSync (dart:io/file_impl.dart:473:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:533:18)
#3      loadComponentFromBinary (package:kernel/kernel.dart:27:36)
#4      compileSdkFromDill (package:dev_compiler/src/kernel/command.dart:544:19)
#5      _compile (package:dev_compiler/src/kernel/command.dart:210:12)
#6      compile (package:dev_compiler/src/kernel/command.dart:52:12)
#7      internalMain (package:dev_compiler/ddc.dart:37:24)
#8      main (file:///opt/s/w/ir/x/w/sdk/pkg/dev_compiler/bin/dartdevc.dart:18:14)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:33)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

**Comment by parlough** [comment]
`webdev` needs to make a new release to be compatible with the latest DDC changes (https://github.com/dart-lang/sdk/issues/50700). See https://github.com/dart-lang/sdk/issues/51106#issuecomment-1404208094 for a plan and more context.

**Comment by annagrin** [comment]
@jodinathan and @parlough for reporting this. We are working on releasing a new webdev version that will support current SDK layout changes for dart 3.0 that exist in dev SDK channel. I am moving this issue to webdev repo.
