### ISSUE TITLE
Analyzer error parsing a pattern

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#51172]
Using current bleeding edge code (as of a few hours ago), if I put this code in the top level of a file:

```dart
final a = switch (Object()) {
  Square(length: var l) => l * l,
  Circle(radius: var r) => math.pi * r * r
};
```

The server terminates with the following:

```
  type 'LibraryOrAugmentationScope' is not a subtype of type 'LocalScope' of ' in type cast'
  #0      ResolutionVisitor._define (package:analyzer/src/dart/resolver/resolution_visitor.dart:1441:17)
  #1      ResolutionVisitor.visitDeclaredVariablePattern (package:analyzer/src/dart/resolver/resolution_visitor.dart:406:5)
  #2      DeclaredVariablePatternImpl.accept (package:analyzer/src/dart/ast/ast.dart:3629:15)
  #3      RecordPatternFieldImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10979:13)
  #4      RecursiveAstVisitor.visitRecordPatternField (package:analyzer/dart/ast/visitor.dart:1509:10)
  #5      RecordPatternFieldImpl.accept (package:analyzer/src/dart/ast/ast.dart:10974:50)
  #6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9589:20)
  #7      ObjectPatternImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9994:12)
  #8      RecursiveAstVisitor.visitObjectPattern (package:analyzer/dart/ast/visitor.dart:1418:10)
  #9      ObjectPatternImpl.accept (package:analyzer/src/dart/ast/ast.dart:9972:50)
  #10     ResolutionVisitor._resolveGuardedPattern (package:analyzer/src/dart/resolver/resolution_visitor.dart:1481:28)
  #11     ResolutionVisitor.visitSwitchExpression (package:analyzer/src/dart/resolver/resolution_visitor.dart:1214:7)
  #12     SwitchExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:12850:50)
  #13     AstResolver.resolveExpression (package:analyzer/src/summary2/ast_resolver.dart:109:10)
  #14     _PropertyInducingElementTypeInference.perform (package:analyzer/src/summary2/top_level_inference.dart:256:17)
  #15     PropertyInducingElementImpl.typeInternal (package:analyzer/src/dart/element/element.dart:6002:35)
  #16     ElementTypeProvider.getFieldType (package:analyzer/src/generated/element_type_provider.dart:62:15)
  #17     PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:5964:52)
  #18     _InitializerInference.perform (package:analyzer/src/summary2/top_level_inference.dart:153:15)
  #19     TopLevelInference.infer (package:analyzer/src/summary2/top_level_inference.dart:107:26)
  #20     Linker._performTopLevelInference (package:analyzer/src/summary2/link.dart:256:29)
  #21     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:135:5)
  <asynchronous suspension>
  #22     Linker.link (package:analyzer/src/summary2/link.dart:95:5)
  <asynchronous suspension>
  #23     link (package:analyzer/src/summary2/link.dart:38:3)
  <asynchronous suspension>
  #24     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:180:24)
  <asynchronous suspension>
  #25     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:246:7)
  <asynchronous suspension>
  #26     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
  <asynchronous suspension>
  #27     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:244:5)
  <asynchronous suspension>
  #28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1335:9)
  <asynchronous suspension>
  #29     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
  <asynchronous suspension>
  #30     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1055:24)
  <asynchronous suspension>
  #31     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2139:7)
  <asynchronous suspension>
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/280079

**Comment by DanTup** [comment]
Thanks!
