### ISSUE TITLE
[dart2wasm] Null deref in dynamic call vtable entry

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#51186]
```dart
test0<T extends num>(T i, T j, {required T a}) => i + j + a;

void main() {
  print(Function.apply(test0, [10, 15], {#a: 17}));
  print(Function.apply(test0, [10, 15], {Symbol("a"): 17}));
}
```

First line works fine, second line fails with:

```
wasm-function[803]:0x2543e: RuntimeError: dereferencing a null pointer
RuntimeError: dereferencing a null pointer
    at dynamic call entry (wasm://wasm/000d160e:wasm-function[803]:0x2543e)
    at Function.apply (wasm://wasm/000d160e:wasm-function[796]:0x25278)
    at main (wasm://wasm/000d160e:wasm-function[53]:0x16877)
    at main tear-off (wasm://wasm/000d160e:wasm-function[55]:0x1688b)
    at _invokeMain (wasm://wasm/000d160e:wasm-function[66]:0x16fba)
    at Module.invoke (/usr/local/google/home/omersa/dart/sdk_wasm/test/test.mjs:171:28)
    at main (/usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/run_wasm.js:61:21)
```

Given that the only difference between the two lines is how the named argument symbol is constructed I'm guessing the issue is actually related to symbols, and the dynamic call code is fine.

**Comment by osa1** [comment]
The problem is `_getNamedParameterIndex` is using `identical` to compare the expected parameter name (a const symbol) with the argument names passed in the named argument list.

We have two options for this to work:

1. Canonicalize symbols passed to `Function.apply` named argument map
2. Use string comparison in `_getNamedParameterIndex`

`_getNamedParameterIndex` is used in all dynamic invocations so I think it makes sense to go with (1) instead of making all dynamic invocations slower.

**Comment by mkustermann** [comment]
This issue seem to be fixed in `--no-minify` mode. 
In `--minify` mode we now mangle the names, making `new Symbol()` not match and we'll throw a NSM error.
