### ISSUE TITLE
Memory leak in coverage tests

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51209]
The tests
```
vm/cc/SourceReport_Coverage_Filters_empty
vm/cc/SourceReport_Coverage_Filters_single
```

are failing on configurations
```
vm-asan-linux-release-x64
```

```
--- Command "run_vm_unittest" (took 02.000065s):
DART_CONFIGURATION=ReleaseASANX64 out/ReleaseASANX64/run_vm_tests --dfe=/b/s/w/ir/cache/builder/sdk/out/ReleaseASANX64/gen/kernel-service.dart.snapshot --enable-experiment=records --sound-null-safety --ignore-unrecognized-flags SourceReport_Coverage_Filters_empty

exit code:
-6

stdout:
Running test: SourceReport_Coverage_Filters_empty
Done: SourceReport_Coverage_Filters_empty

stderr:
=================================================================
==12955==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3984 byte(s) in 166 object(s) allocated from:
    #0 0x55881435ab9d in operator new(unsigned long) ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x558815569482 in dart::SourceReport::GetScriptIndex(dart::Script const&) ../../out/ReleaseASANX64/../../runtime/vm/source_report.cc:225:27
    #2 0x55881556e4a8 in dart::SourceReport::VisitLibrary(dart::JSONArray*, dart::Library const&) ../../out/ReleaseASANX64/../../runtime/vm/source_report.cc:643:39
    #3 0x55881556eff9 in dart::SourceReport::PrintJSON(dart::JSONStream*, dart::Script const&, dart::TokenPosition, dart::TokenPosition) ../../out/ReleaseASANX64/../../runtime/vm/source_report.cc:703:9
    #4 0x5588148f198e in dart::Dart_TestHelperSourceReport_Coverage_Filters_empty(dart::Thread*) ../../out/ReleaseASANX64/../../runtime/vm/source_report_test.cc:112:10
    #5 0x5588148f198e in dart::Dart_TestSourceReport_Coverage_Filters_empty() ../../out/ReleaseASANX64/../../runtime/vm/source_report_test.cc:95:1
    #6 0x5588143611ba in dart::TestCase::Run() ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:52:3
    #7 0x5588143614bf in dart::TestCaseBase::RunTest() ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:64:11
    #8 0x558814965502 in dart::TestCaseBase::RunAll() ../../out/ReleaseASANX64/../../runtime/vm/unit_test.cc:86:13
    #9 0x558814361dc1 in dart::Main(int, char const**) ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:397:3
    #10 0x5588143616ca in main ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:428:29
    #11 0x7f34450c0c86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86) (BuildId: f7307432a8b162377e77a182b6cc2e53d771ec4b)

Direct leak of 1224 byte(s) in 51 object(s) allocated from:
    #0 0x55881435ab9d in operator new(unsigned long) ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x558815569482 in dart::SourceReport::GetScriptIndex(dart::Script const&) ../../out/ReleaseASANX64/../../runtime/vm/source_report.cc:225:27
    #2 0x55881556ce44 in dart::SourceReport::VisitFunction(dart::JSONArray*, dart::Function const&) ../../out/ReleaseASANX64/../../runtime/vm/source_report.cc:544:33
    #3 0x55881556dfdf in dart::SourceReport::VisitLibrary(dart::JSONArray*, dart::Library const&) ../../out/ReleaseASANX64/../../runtime/vm/source_report.cc:666:7
    #4 0x55881556eff9 in dart::SourceReport::PrintJSON(dart::JSONStream*, dart::Script const&, dart::TokenPosition, dart::TokenPosition) ../../out/ReleaseASANX64/../../runtime/vm/source_report.cc:703:9
    #5 0x5588148f198e in dart::Dart_TestHelperSourceReport_Coverage_Filters_empty(dart::Thread*) ../../out/ReleaseASANX64/../../runtime/vm/source_report_test.cc:112:10
    #6 0x5588148f198e in dart::Dart_TestSourceReport_Coverage_Filters_empty() ../../out/ReleaseASANX64/../../runtime/vm/source_report_test.cc:95:1
    #7 0x5588143611ba in dart::TestCase::Run() ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:52:3
    #8 0x5588143614bf in dart::TestCaseBase::RunTest() ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:64:11
    #9 0x558814965502 in dart::TestCaseBase::RunAll() ../../out/ReleaseASANX64/../../runtime/vm/unit_test.cc:86:13
    #10 0x558814361dc1 in dart::Main(int, char const**) ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:397:3
    #11 0x5588143616ca in main ../../out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:428:29
    #12 0x7f34450c0c86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86) (BuildId: f7307432a8b162377e77a182b6cc2e53d771ec4b)

SUMMARY: AddressSanitizer: 5208 byte(s) leaked in 217 allocation(s).

--- Re-run this test:
python3 tools/test.py -n vm-asan-linux-release-x64 vm/cc/SourceReport_Coverage_Filters_empty
```

The sanitizer bots have recently switched to NNBD.

@liamappelbe

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/280600
