### ISSUE TITLE
Overflow in vm/cc/PCRelativeCallPatterns

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51211]
The tests
```
vm/cc/PCRelativeCallPatterns
```

are failing on configurations
```
vm-ubsan-linux-release-x64
```

```
--- Command "run_vm_unittest" (took 01.000196s):
DART_CONFIGURATION=ReleaseUBSANX64 out/ReleaseUBSANX64/run_vm_tests --dfe=/b/s/w/ir/cache/builder/sdk/out/ReleaseUBSANX64/gen/kernel-service.dart.snapshot --enable-experiment=records --sound-null-safety --ignore-unrecognized-flags PCRelativeCallPatterns

exit code:
1

stdout:
Running raw test: PCRelativeCallPatterns

stderr:
../../runtime/vm/instructions_x64.h:127:29: runtime error: signed integer overflow: -2147483648 - 5 cannot be represented in type 'int'
    #0 0x55857017c832 in dart::PcRelativeCallPattern::set_distance(int) ../../out/ReleaseUBSANX64/../../runtime/vm/instructions_x64.h:127:29
    #1 0x55857017c648 in dart::Dart_TestPCRelativeCallPatterns() ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/relocation_test.cc:449:13
    #2 0x55856fedec6f in dart::RawTestCase::Run() ../../out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:58:3
    #3 0x55856feded18 in dart::TestCaseBase::RunTest() ../../out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:64:11
    #4 0x5585700a56cc in dart::TestCaseBase::RunAllRaw() ../../out/ReleaseUBSANX64/../../runtime/vm/unit_test.cc:75:13
    #5 0x55856fedf6d3 in dart::Main(int, char const**) ../../out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:409:3
    #6 0x55856fedf210 in main ../../out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:428:29
    #7 0x7f0ed6bd8c86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86) (BuildId: f7307432a8b162377e77a182b6cc2e53d771ec4b)
    #8 0x55856fec4229 in _start (/b/s/w/ir/cache/builder/sdk/out/ReleaseUBSANX64/run_vm_tests+0x30ec229)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../runtime/vm/instructions_x64.h:127:29 in

--- Re-run this test:
python3 tools/test.py -n vm-ubsan-linux-release-x64 vm/cc/PCRelativeCallPatterns
```

@mkustermann

**Comment by mkustermann** [comment]
Thanks, @rmacnak-google. Uploaded [cl/280322](https://dart-review.googlesource.com/c/sdk/+/280322)
