### ISSUE TITLE
Memory leak of kernel service response

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51210]
The tests
```
lib/mirrors/dynamic_load_test
```
are failing on configurations
```
vm-asan-linux-release-x64
```

```
stderr:
=================================================================
==21617==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 920 byte(s) in 1 object(s) allocated from:
    #0 0x558f6ce8d08e in malloc ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x558f6cf48d6f in dart::malloc(unsigned long) ../../out/ReleaseASANX64/../../runtime/platform/allocation.cc:20:18
    #2 0x558f6d40d493 in dart::KernelCompilationRequest::LoadKernelFromResponse(_Dart_CObject*) ../../out/ReleaseASANX64/../../runtime/vm/kernel_isolate.cc:1006:44
    #3 0x558f6d40d493 in dart::KernelCompilationRequest::HandleResponseImpl(_Dart_CObject*) ../../out/ReleaseASANX64/../../runtime/vm/kernel_isolate.cc:1030:7
    #4 0x558f6d40d26e in dart::KernelCompilationRequest::HandleResponse(long, _Dart_CObject*) ../../out/ReleaseASANX64/../../runtime/vm/kernel_isolate.cc:1048:9
    #5 0x558f6d466fa2 in dart::NativeMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message>>) ../../out/ReleaseASANX64/../../runtime/vm/native_message_handler.cc:42:3
    #6 0x558f6d43290f in dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) ../../out/ReleaseASANX64/../../runtime/vm/message_handler.cc:239:16
    #7 0x558f6d433ec3 in dart::MessageHandler::TaskCallback() ../../out/ReleaseASANX64/../../runtime/vm/message_handler.cc:448:18
    #8 0x558f6d829f65 in dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseASANX64/../../runtime/vm/thread_pool.cc:158:15
    #9 0x558f6d82b38a in dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseASANX64/../../runtime/vm/thread_pool.cc:330:9
    #10 0x558f6d64ef0f in dart::ThreadStart(void*) ../../out/ReleaseASANX64/../../runtime/vm/os_thread_linux.cc:154:5
    #11 0x7fd7e827e6da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da) (BuildId: 1f06001733b9be9478b105faf0dac6bdf36c85de)

SUMMARY: AddressSanitizer: 920 byte(s) leaked in 1 allocation(s).

--- Re-run this test:
python3 tools/test.py -n vm-asan-linux-release-x64 lib/mirrors/dynamic_load_test
```

**Comment by a-siva** [comment]
This is a duplicate of http://dartbug.com/37030
