### ISSUE TITLE
Overflow in FFI tests

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51212]
The tests
```
ffi/vmspecific_regress_37511_test
```
are failing on configurations
```
vm-ubsan-linux-release-x64
```

```
--- Command "vm" (took 03.000112s):
DART_CONFIGURATION=ReleaseUBSANX64 out/ReleaseUBSANX64/dart --deterministic --sound-null-safety -Dtest_runner.configuration=vm-ubsan-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json /b/s/w/ir/cache/builder/sdk/tests/ffi/vmspecific_regress_37511_test.dart

exit code:
1

stderr:
../../runtime/bin/ffi_test/ffi_test_functions.cc:455:65: runtime error: signed integer overflow: 55 + 9223372036854775792 cannot be represented in type 'intptr_t' (aka 'long')
LLVMSymbolizer: error reading file: No such file or directory
    #0 0x7fccf3e351e1 in SumManyIntsOdd ../../out/ReleaseUBSANX64/../../runtime/bin/ffi_test/ffi_test_functions.cc:455:65
    #1 0x7fcd1410620a  (/memfd:dart-code (deleted)+0x620a)
    #2 0x7fcd0f629a17  (/memfd:dart-code (deleted)+0x29a17)
    #3 0x7fcd0f62967b  (/memfd:dart-code (deleted)+0x2967b)
    #4 0x7fcd0f624107  (/memfd:dart-code (deleted)+0x24107)
    #5 0x7fcd0f623f95  (/memfd:dart-code (deleted)+0x23f95)
    #6 0x7fcd0f623ecb  (/memfd:dart-code (deleted)+0x23ecb)
    #7 0x7fcd0f622dc6  (/memfd:dart-code (deleted)+0x22dc6)
    #8 0x7fcd0f622b1e  (/memfd:dart-code (deleted)+0x22b1e)
    #9 0x7fcd0f622395  (/memfd:dart-code (deleted)+0x22395)
    #10 0x7fcd14102f0b  (/memfd:dart-code (deleted)+0x2f0b)
    #11 0x5611fca14e5e in dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*) ../../out/ReleaseUBSANX64/../../runtime/vm/dart_entry.cc
    #12 0x5611fca14bf8 in dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) ../../out/ReleaseUBSANX64/../../runtime/vm/dart_entry.cc:145:10
    #13 0x5611fca18091 in dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&) ../../out/ReleaseUBSANX64/../../runtime/vm/dart_entry.cc:732:28
    #14 0x5611fca5acb5 in dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message>>) ../../out/ReleaseUBSANX64/../../runtime/vm/isolate.cc:1437:15
    #15 0x5611fcaa8972 in dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) ../../out/ReleaseUBSANX64/../../runtime/vm/message_handler.cc:239:16
    #16 0x5611fcaa9646 in dart::MessageHandler::TaskCallback() ../../out/ReleaseUBSANX64/../../runtime/vm/message_handler.cc:448:18
    #17 0x5611fcca9442 in dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseUBSANX64/../../runtime/vm/thread_pool.cc:158:15
    #18 0x5611fcca9df5 in dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseUBSANX64/../../runtime/vm/thread_pool.cc:330:9
    #19 0x5611fcbc0a38 in dart::ThreadStart(void*) ../../out/ReleaseUBSANX64/../../runtime/vm/os_thread_linux.cc:154:5
    #20 0x7fcd151e96da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da) (BuildId: 1f06001733b9be9478b105faf0dac6bdf36c85de)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../runtime/bin/ffi_test/ffi_test_functions.cc:455:65 in

--- Re-run this test:
python3 tools/test.py -n vm-ubsan-linux-release-x64 ffi/vmspecific_regress_37511_test
```

@dcharkes

**Comment by rmacnak-google** [comment]
Passing at ToT.
