### ISSUE TITLE
Exception thrown by the migration tool

### ISSUE THREAD

**Issue by abigotado** [dart-lang/sdk#51239]
When running `dart migrate` tool, the exception is thrown: `type 'MixinElementImpl' is not a subtype of type 'ClassElement' in type cast.`

Full log:
```
Analyzing project...
[------------------------------------------------------------------------------------------------------------------------------------------------------------]No analysis issues found.

Generating migration suggestions...
[-----------------------------------------------------\                                                                                                      ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.19.1) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

type 'MixinElementImpl' is not a subtype of type 'ClassElement' in type cast at offset 943 in /Users/Abigotado/StudioProjects/cargo-mobile/lib/screens/map/map_filters_dialog/map_filters_dialog.dart (@override void dispose() {_controller.dispose(); super.dispose();})

#0      EdgeBuilder._handleExecutableOverriddenDeclaration (package:nnbd_migration/src/edge_builder.dart:2774:62)
#1      EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2694:13)
#2      EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1393:5)
#3      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8533:50)
#4      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2375:24)
#5      EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2393:7)
#6      EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:717:7)
#7      EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:676:5)
#8      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2000:50)
#9      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2375:24)
#10     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1567:9)
#11     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:216:52)
#12     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#13     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#14     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#15     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2501:50)
#16     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:224:12)
#17     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:162:16)
#18     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1088:19)
#19     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1020:26)
<asynchronous suspension>
#20     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1086:5)
<asynchronous suspension>
#21     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:695:24)
<asynchronous suspension>
#22     MigrateCommand.run (package:dartdev/src/commands/migrate.dart:37:7)
<asynchronous suspension>
#23     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#24     DartdevRunner.runCommand (package:dartdev/dartdev.dart:241:18)
<asynchronous suspension>
#25     runDartdev (package:dartdev/dartdev.dart:65:18)
<asynchronous suspension>
#26     main (file:///opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by ferdiangunawan** [comment]
I was running the same issue, is there an update on this issue?

**Comment by georgerappel** [comment]
The error mentions a class on the top and some code in the exception details. In my case, like yours, my class was overriding the dispose method like this:

```
  @override
   void dispose() {
     _controller.dispose();
     super.dispose();
   }
```

Simply commenting out this code solved my issue, and the tool ran with success. Now I'll see what happens after I uncomment it.

**Comment by abigotado** [comment]
Well, yes, it will run with commented Mixin or dispose method override and in error ignoring mode as well. I had to use that workarounds to finish my migration. But I don't think it's a supposed behaviour.

@ferdiangunawan @georgerappel  Thanks for help, guys!

**Comment by KopiasCsaba** [comment]
Indeed it does!

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.

**Comment by ristiisa** [comment]
@stereotype441 

> As of [1c7fe71](https://github.com/dart-lang/sdk/commit/1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c), the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

well what are these people supposed to do that are migrating the code right now?

**Comment by stereotype441** [comment]
> @stereotype441
> 
> > As of [1c7fe71](https://github.com/dart-lang/sdk/commit/1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c), the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.
> 
> well what are these people supposed to do that are migrating the code right now?

Your best bet at this point is probably to re-run the migration tool with the `--ignore-exceptions` flag.
