### ISSUE TITLE
Dart analyzer server crash with sdk 2.19.1 (mixin and classes)

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/sdk#51231]
Dart SDK 2.19.1 on Ubuntu 2022-04

I manage to reproduce a simple example that makes the dart analyzer server crash here:

https://github.com/alextekartik/analysis_server_crash.dart

`dart analyze .` works fine on it however when opened in an IDE (I use intellij but I reproduced the issue in vscode), the analysys server keeps crashing.

Sorry I don't have much log but the intellij logs:
```txt
 <asynchronous suspension>
2023-02-02 12:34:37,430 [13115334]   INFO - #c.j.l.d.a.DartAnalysisServerService - analysis_getImportedElements() took longer than 100ms, for file /home/alex/tekartik/devx/git/github.com/tekartik/cv.dart/packages/cv/lib/src/cv_model.dart, Dart SDK version: 2.19.1
2023-02-02 12:34:37,551 [13115455]   INFO - #c.j.l.d.a.DartAnalysisServerService - Error from unknown, SDK version = 2.19.1, server version = 1.33.4, error code = GET_IMPORTED_ELEMENTS_INVALID_FILE: Error during `analysis.getImportedElements`: invalid file.
2023-02-02 12:34:38,225 [13116129]   INFO - STDERR - Unhandled exception:
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - Instance of '_TopMergeStateError'
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #0      TopMergeHelper._functionTypes (package:analyzer/src/dart/element/top_merge.dart:198:9)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #1      TopMergeHelper.topMerge (package:analyzer/src/dart/element/top_merge.dart:159:14)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #2      TypeSystemImpl.topMerge (package:analyzer/src/dart/element/type_system.dart:1587:33)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #3      InheritanceManager3._topMerge.<anonymous closure> (package:analyzer/src/dart/element/inheritance_manager3.dart:838:25)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #4      ListIterable.reduce (dart:_internal/iterable.dart:184:22)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #5      InheritanceManager3._topMerge (package:analyzer/src/dart/element/inheritance_manager3.dart:837:8)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #6      InheritanceManager3.combineSignatures (package:analyzer/src/dart/element/inheritance_manager3.dart:110:14)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #7      InheritanceManager3._findMostSpecificFromNamedCandidates (package:analyzer/src/dart/element/inheritance_manager3.dart:432:31)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #8      InheritanceManager3._getInterfaceClass (package:analyzer/src/dart/element/inheritance_manager3.dart:547:9)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #9      InheritanceManager3.getInterface (package:analyzer/src/dart/element/inheritance_manager3.dart:221:18)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #10     _ClassVerifier.verify (package:analyzer/src/error/inheritance_override.dart:188:33)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #11     InheritanceOverrideVerifier.verifyUnit (package:analyzer/src/error/inheritance_override.dart:101:20)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #12     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:465:33)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #13     LibraryAnalyzer._computeDiagnostics.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:254:7)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #15     LibraryAnalyzer._computeDiagnostics (package:analyzer/src/dart/analysis/library_analyzer.dart:253:11)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #16     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:92:5)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #17     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1349:11)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #18     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #19     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1391:26)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #20     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1106:21)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #21     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2140:7)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - 
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1378:9)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #1      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #2      AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1391:26)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1106:21)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - #4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2140:7)
2023-02-02 12:34:38,226 [13116130]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - Unhandled exception:
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - Instance of '_TopMergeStateError'
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #0      TopMergeHelper._functionTypes (package:analyzer/src/dart/element/top_merge.dart:198:9)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #1      TopMergeHelper.topMerge (package:analyzer/src/dart/element/top_merge.dart:159:14)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #2      TypeSystemImpl.topMerge (package:analyzer/src/dart/element/type_system.dart:1587:33)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #3      InheritanceManager3._topMerge.<anonymous closure> (package:analyzer/src/dart/element/inheritance_manager3.dart:838:25)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #4      ListIterable.reduce (dart:_internal/iterable.dart:184:22)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #5      InheritanceManager3._topMerge (package:analyzer/src/dart/element/inheritance_manager3.dart:837:8)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #6      InheritanceManager3.combineSignatures (package:analyzer/src/dart/element/inheritance_manager3.dart:110:14)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #7      InheritanceManager3._findMostSpecificFromNamedCandidates (package:analyzer/src/dart/element/inheritance_manager3.dart:432:31)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #8      InheritanceManager3._getInterfaceClass (package:analyzer/src/dart/element/inheritance_manager3.dart:547:9)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #9      InheritanceManager3.getInterface (package:analyzer/src/dart/element/inheritance_manager3.dart:221:18)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #10     _ClassVerifier.verify (package:analyzer/src/error/inheritance_override.dart:188:33)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #11     InheritanceOverrideVerifier.verifyUnit (package:analyzer/src/error/inheritance_override.dart:101:20)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #12     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:465:33)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #13     LibraryAnalyzer._computeDiagnostics.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:254:7)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #15     LibraryAnalyzer._computeDiagnostics (package:analyzer/src/dart/analysis/library_analyzer.dart:253:11)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #16     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:92:5)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #17     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1349:11)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #18     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #19     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1391:26)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #20     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1106:21)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #21     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2140:7)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - 
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1378:9)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #1      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #2      AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1391:26)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1106:21)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - <asynchronous suspension>
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - #4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2140:7)
2023-02-02 12:34:40,586 [13118490]   INFO - STDERR - <asynchronous suspension>
```

I have narrowed it to a single line in `analysis_server_crash_test.dart':

```dart
// This makes dart analyzer crashes, if you comment it, it is ok
abstract class MyModelBase extends CvModelBase
    with MyModelMixin
    implements MyModel {}
```

(it is a test file but no need to run it, just having the IDE open is enough to reproduce the issue)

It uses an external dependency (https://pub.dev/packages/cv - I'm the author but the project reports no errors), I cannot figure out why it hangs as this was working on dart 2.18. Also it makes any project importing such a file hangs as well. I have tried to reproduced the complex usage of mixin and classes in a simpler example without success yet.

Maybe there is a standalone way to launch the server to get extra logs, let me know if I can help

**Comment by alextekartik** [comment]
So I managed to remove what was crashing in the cv package by adding some missing `<T extends Object?>` instead of `<T>`. Not sure if I make the best choices here but too late. I keep the test repository I mentioned with a failing version if you still want to reproduce the crash. Otherwise let me know if I should close the bug. Also I want to mention that this is also occuring with 2.18 so it is not a 2.19 specific issue.

**Comment by asashour** [comment]
A crash is something which should be handled. I am able to reproduce the issue also with `master`.

It would be helpful, if you can isolate the case to minimal lines without using external library, so it can be quickly tackled.

**Comment by srawlins** [comment]
CC @scheglov I think you have context for TopMergeHelper.

**Comment by srawlins** [comment]
I got it down to a pretty minimal repro:

```dart
mixin CvModelMixin implements CvModel {
  @override
  CvField<T>? field<T>(String name) {
    return null;
  }
}

class CvField<T> {}

abstract class CvModel {
  CvField<T>? field<T extends Object?>(String name);
}

abstract class CvModelBase with CvModelMixin {}

abstract class MyModel implements CvModel {}

mixin MyModelMixin implements MyModel {}

abstract class MyModelBase extends CvModelBase
    with MyModelMixin
    implements MyModel {}
```

**Comment by srawlins** [comment]
@scheglov I'd be happy to drive this, but I have a few questions:

* The _TopMergeStateError is being thrown with `CvField<U>? Function<U>(String)` for `T` and, `CvField<U>? Function<U extends Object?>(String)` for `S` (I've renamed the inner type parameters to `U`). So the only difference is that `T` has no bound on it's `U`, and `S` has a bound of `Object?` on its `U`. The analyzer's TOP_MERGE code seems unable to handle this situation (line ~350).
* The code seems to run in the VM without error (given a class `class MyModelImpl extends MyModelBase {}` and a main method `void main() => print(MyModelImpl().field<int>(''));`).
* TOP_MERGE, for null safe libraries, seems to [be defined](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#classes-defined-in-opted-in-libraries) only for types, but we're trying to do a TOP_MERGE of uninstantiated types ("type schemas"?). The algorithm specifies "And for all other types, recursively applying the transformation over the structure of the type" but it's not clear how we'd apply that to the _type parameters_ `U` and `U extends Object?`.
* In any case, maybe it's all moot. I think the algorithm would be fine to treat an unbounded type parameter as bounded to `dynamic`, right? And then use `NNBD_TOP_MERGE(Object?, dynamic)  = Object?`. I believe we handle all cases where the explicit bound is something other than `Object?` and `void` (I tried `int?`, `Object`, `Never`, `int Function()`).
* As far as "when was this bug introduced in Dart 2.19?", there was not much activity in `top_merge.dart` over the last year, but [this commit](https://github.com/dart-lang/sdk/commit/cbfad8f802c1786cd2576452a50f44e7cf6dea2d) had some impl changes in `element.dart`, could be a culprit.

**Comment by alextekartik** [comment]
> As far as "when was this bug introduced in Dart 2.19?"

As I mentioned in a later comment, I was able to reproduce in dart 2.18 so I don't think (not sure) that this was introduced in 2.19. I did not notice it before because the issue started to happen after I introduced these `T extends Object?` (and after moving to 2.19).

**Comment by srawlins** [comment]
Oh thanks, sorry I missed that.

FWIW, I applaud your explicit `T extends Object?` everywhere, and wish it was the default. Maybe some day `T extends Object?` can be the implicit default instead of `T extends dynamic`.
