### ISSUE TITLE
The compiler crashed: RangeError (index): Invalid value: Only valid value is 0: 1

### ISSUE THREAD

**Issue by Aqua-Ye** [dart-lang/sdk#51246]
When compiling my project for web, I got a compiler error.

OS: macOS 13.1
Dart SDK: 2.18.6

```
Compiling lib/main.dart for the Web...
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
../../.pub-cache/hosted/pub.dartlang.org/lottie-2.2.0/lib/src/model/layer/text_layer.dart:291:8:
Internal Error: The compiler crashed when compiling this element.
  void _drawFontTextLine(Characters text, TextStyle textStyle,
```

```
The compiler crashed: RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      KernelSsaGraphBuilder._setupStateForInlining.<anonymous closure> (package:compiler/src/ssa/builder.dart:6263:48)
#2      forEachOrderedParameter.handleParameter (package:compiler/src/js_model/element_map_migrated.dart:308:6)
#3      forEachOrderedParameterByFunctionNode (package:compiler/src/js_model/element_map_migrated.dart:280:6)
#4      forEachOrderedParameter (package:compiler/src/js_model/element_map_migrated.dart:316:9)
#5      KernelSsaGraphBuilder._setupStateForInlining (package:compiler/src/ssa/builder.dart:6249:5)
#6      KernelSsaGraphBuilder._enterInlinedMethod (package:compiler/src/ssa/builder.dart:6211:5)
#7      KernelSsaGraphBuilder._tryInlineMethod.doInlining (package:compiler/src/ssa/builder.dart:6037:7)
#8      KernelSsaGraphBuilder._tryInlineMethod (package:compiler/src/ssa/builder.dart:6050:7)
#9      KernelSsaGraphBuilder._pushDynamicInvocation (package:compiler/src/ssa/builder.dart:5104:11)
#10     KernelSsaGraphBuilder._buildForInIterator.buildCondition (package:compiler/src/ssa/builder.dart:2052:7)
#11     LoopHandler.handleLoop (package:compiler/src/ssa/loop_handler.dart:70:50)
#12     KernelSsaGraphBuilder._buildForInIterator (package:compiler/src/ssa/builder.dart:2083:18)
#13     KernelSsaGraphBuilder.visitForInStatement (package:compiler/src/ssa/builder.dart:1875:7)
#14     ForInStatement.accept (package:kernel/ast.dart:9784:43)
#15     KernelSsaGraphBuilder.visitBlock (package:compiler/src/ssa/builder.dart:1725:17)
#16     Block.accept (package:kernel/ast.dart:9244:43)
#17     KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder.dart:1241:23)
#18     KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder.dart:447:15)
#19     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#20     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder.dart:432:21)
#21     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:513:22)
#22     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#23     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:496:18)
#24     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:350:21)
#25     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:82:29)
#26     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:442:30)
#27     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:320:43)
#28     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:463:29)
#29     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:740:70)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#31     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:740:32)
#32     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#33     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:738:28)
#34     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#35     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:736:18)
#36     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:252:12)
#37     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:268:5)
#38     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:732:16)
#39     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#40     Compiler.emptyQueue (package:compiler/src/compiler.dart:731:14)
#41     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:755:7)
#42     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#43     Compiler.processQueue (package:compiler/src/compiler.dart:749:14)
#44     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:500:5)
#45     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:684:23)
<asynchronous suspension>
#46     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:309:7)
<asynchronous suspension>
#47     Compiler.runInternal (package:compiler/src/compiler.dart:308:5)
<asynchronous suspension>
#48     main (package:compiler/src/dart2js.dart:1424:3)
<asynchronous suspension>
```

**Comment by Markzipan** [comment]
Pinging @rakudrama for more context on this dart2js failure.

**Comment by sigmundch** [comment]
For context, this is the code triggering the issue:

https://github.com/xvrh/lottie-flutter/blob/v2.2.0/lib/src/model/layer/text_layer.dart#L291

**Comment by xvrh** [comment]
This issue is still present for latest stable (3.3.4) and latest master (3.5.0-82.0.dev).

It doesn't reproduce on simple projects so I can't provide a reproducible example.

But if someone from the dart2js compiler team is interested I can share a project privately.
