### ISSUE TITLE
Process.run and Process.runSync flakily produce different exitCodes for the same invocation

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51271]
The tests
```
standalone/io/process_sync_test
```
are failing on configurations
```
vm-msan-linux-release-x64
```

```
--- Command "vm" (took 33.000194s):
DART_CONFIGURATION=ReleaseMSANX64 out/ReleaseMSANX64/dart --sound-null-safety -Dtest_runner.configuration=vm-msan-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json /b/s/w/ir/cache/builder/sdk/tests/standalone/io/process_sync_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <1>) fails.
#0      Expect._fail (package:expect/expect.dart:697:5)
#1      Expect.equals (package:expect/expect.dart:120:5)
#2      test.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/tests/standalone/io/process_sync_test.dart:41:12)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-msan-linux-release-x64 standalone/io/process_sync_test
```

**Comment by dcharkes** [comment]
https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=standalone/io/process_sync_test&configurations=vm-msan-linux-release-x64

This one is jumping back and forth.

**Comment by alexmarkov** [comment]
Failed once again: https://dart-ci.appspot.com/log/vm-msan-linux-release-x64/vm-msan-linux-release-x64/43/standalone/io/process_sync_test

**Comment by dcharkes** [comment]
```
--- Command "vm" (took 27.000167s):
DART_CONFIGURATION=ReleaseMSANX64 out/ReleaseMSANX64/dart --sound-null-safety -Dtest_runner.configuration=vm-msan-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/standalone/io/signals_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <1>) fails.
#0      Expect._fail (package:expect/expect.dart:696:5)
#1      Expect.equals (package:expect/expect.dart:120:5)
#2      testMultipleSignals.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/signals_test.dart:109:16)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-msan-linux-release-x64 standalone/io/signals_test
```

This test is affected by the same issue.

**Comment by sstrickl** [comment]
[Failed again](https://dart-ci.appspot.com/log/vm-msan-linux-release-x64/vm-msan-linux-release-x64/131/standalone/io/process_sync_test):

```
--- Command "vm" (took 09.000261s):
DART_CONFIGURATION=ReleaseMSANX64 out/ReleaseMSANX64/dart --sound-null-safety -Dtest_runner.configuration=vm-msan-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/standalone/io/process_sync_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <1>) fails.
#0      Expect._fail (package:expect/expect.dart:696:5)
#1      Expect.equals (package:expect/expect.dart:120:5)
#2      test (file:///b/s/w/ir/tests/standalone/io/process_sync_test.dart:33:14)
#3      main (file:///b/s/w/ir/tests/standalone/io/process_sync_test.dart:50:3)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

--- Re-run this test:
python3 tools/test.py -n vm-msan-linux-release-x64 standalone/io/process_sync_test
```

**Comment by mkustermann** [comment]
The reason it produces a different exit-code sometimes is because the subprocess it runs flakily produces MSAN warnings. Though those warnings cannot be printed due to the subprocess closing stdout/stderr.

One can avoid this by using `MSAN_OPTIONS=log_path=msan.log`, though the only thing one can find there is this
```
MemorySanitizer: 1 warnings reported.
```

It is very strange that MSAN doesn't actually print more information about the issue.

**Comment by rmacnak-google** [comment]
Setting a breakpoint on MSAN's ReportAtExitStatistics, I observe this is the same issue in #51560 where the Dart compiler in one thread is racing with global destructors run on the thread calling exit. (In particular, CompilerPass::flags_.) The fact that this is an at-exit issue triggered in another thread is probably why the MSAN log doesn't contain much.

```
Thread 8 (Thread 0x7fffeb87b6c0 (LWP 3902218) "DartWorker"):
#0  ReportAtExitStatistics () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/msan/msan_report.cpp:142
#1  0x0000555557574a49 in __msan::MsanAtExit() () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/msan/msan_linux.cpp:164
#2  0x00007ffff7cfc435 in __run_exit_handlers (status=0, listp=0x7ffff7e90820 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:113
#3  0x00007ffff7cfc5aa in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:143
#4  0x00005555575b8ff9 in dart::bin::Platform::Exit (exit_code=0) at out/ReleaseMSANX64/../../runtime/bin/platform_linux.cc:172
#5  0x00005555575ba1e0 in dart::bin::Builtin_Process_Exit (args=<optimized out>) at out/ReleaseMSANX64/../../runtime/bin/process.cc:266
#6  0x0000555557aac836 in dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck (args=0x7fffeb878dd0, func=0x5555575ba160 <dart::bin::Builtin_Process_Exit(_Dart_NativeArguments*)>) at out/ReleaseMSANX64/../../runtime/vm/native_entry.cc:217
...

Thread 5 (Thread 0x7ffff41f66c0 (LWP 3902215) "DartWorker"):
#0  internal_munmap () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:219
#1  0x0000555557502eec in __sanitizer::UnmapOrDie(void*, unsigned long) () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/sanitizer_common/sanitizer_posix.cpp:59
#2  0x0000555557506e77 in dl_iterate_phdr_cb () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/sanitizer_common/sanitizer_linux_libcdep.cpp:703
#3  0x00007ffff7e0d06d in __GI___dl_iterate_phdr (callback=0x55555755ef70 <msan_dl_iterate_phdr_cb()>, data=0x7ffff41f2a40) at ./elf/dl-iteratephdr.c:74
#4  0x000055555755ef54 in __interceptor_dl_iterate_phdr () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/msan/msan_interceptors.cpp:1572
#5  0x0000555557506d33 in init () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/sanitizer_common/sanitizer_linux_libcdep.cpp:737
#6  0x000055555750d7f3 in RefreshModules () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp:185
#7  FindModuleForAddress () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp:204
#8  0x000055555750d683 in SymbolizePC () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp:88
#9  0x000055555750c157 in ProcessAddressFrames () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_libcdep.cpp:36
#10 0x000055555750c087 in PrintTo () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_libcdep.cpp:109
#11 0x000055555750c2f5 in Print () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_libcdep.cpp:132
#12 0x0000555557574c3c in ReportUMR () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/msan/msan_report.cpp:109
#13 0x0000555557516c7b in PrintWarningWithOrigin () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/msan/msan.cpp:242
#14 0x00005555575174c2 in __msan_warning_noreturn () at ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/msan/msan.cpp:393
#15 0x000055555815e973 in dart::CompilerPass::PrintGraph (this=0x7ffff7fab000, this@entry=0x555559dd9a60 <dart::compiler_pass_CSE>, state=0x1000, state@entry=0x7ffff41f3a50, mask=104, mask@entry=dart::CompilerPass::kTraceAfter, round=140737126597808, round@entry=1) at out/ReleaseMSANX64/../../runtime/vm/compiler/compiler_pass.cc:250
#16 0x000055555815e626 in dart::CompilerPass::Run (this=0x555559dd9a60 <dart::compiler_pass_CSE>, state=state@entry=0x7ffff41f3a50) at out/ReleaseMSANX64/../../runtime/vm/compiler/compiler_pass.cc:233
#17 0x000055555815f11f in dart::CompilerPass::RunPipeline (mode=<optimized out>, pass_state=0x7ffff41f3a50) at out/ReleaseMSANX64/../../runtime/vm/compiler/compiler_pass.cc:362
#18 0x0000555557daa71b in dart::CompileParsedFunctionHelper::Compile (this=this@entry=0x7ffff41f4550, pipeline=pipeline@entry=0x7ffff41f4b90) at out/ReleaseMSANX64/../../runtime/vm/compiler/jit/compiler.cc:583
#19 0x0000555557dac191 in dart::CompileFunctionHelper (pipeline=0x7ffff41f4b90, function=..., optimized=true, osr_id=osr_id@entry=-1) at out/ReleaseMSANX64/../../runtime/vm/compiler/jit/compiler.cc:729
#20 0x0000555557dad135 in dart::Compiler::CompileOptimizedFunction (thread=thread@entry=0x71f000012600, function=..., osr_id=osr_id@entry=-1) at out/ReleaseMSANX64/../../runtime/vm/compiler/jit/compiler.cc:914
#21 0x0000555557dae312 in dart::BackgroundCompiler::Run (this=0x708000008280) at out/ReleaseMSANX64/../../runtime/vm/compiler/jit/compiler.cc:1154
#22 0x0000555557d7d007 in dart::ThreadPool::WorkerLoop (this=this@entry=0x711000000140, worker=worker@entry=0x703000005490) at out/ReleaseMSANX64/../../runtime/vm/thread_pool.cc:158
#23 0x0000555557d7db62 in dart::ThreadPool::Worker::Main (args=123351460762768) at out/ReleaseMSANX64/../../runtime/vm/thread_pool.cc:330
#24 0x0000555557c340d8 in dart::ThreadStart (data_ptr=<optimized out>) at out/ReleaseMSANX64/../../runtime/vm/os_thread_linux.cc:154
#25 0x00007ffff7d46fd4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#26 0x00007ffff7dc75bc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
