### ISSUE TITLE
[CFE] Inline class constructors with named or optional parameters crash when compiled

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#51277]
Dart version: 3.0.0-edge.21f02f3b9de41b764628e7700e3aaee4eaf2e242
Platform: Linux

Using test.py with `--enable-experiment=inline-class` and with DDC.

Compiling

```dart
inline class I {
  final int i = 0;
  I([int? x]);
}
```

results in:

```
stdout:
Unhandled exception:
Crash when compiling <test_name> at character offset 316:
RangeError (index): Invalid value: Only valid value is 0: 1

#0      _Array.[] (dart:core-patch/array.dart:10:36)
#1      SourceFunctionBuilderImpl.getFormalParameter (package:front_end/src/fasta/source/source_function_builder.dart:425:22)
#2      BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1290:59)
#3      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1123:19)
#4      DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:751:5)
#5      DietListener.endClassConstructor (package:front_end/src/fasta/source/diet_listener.dart:698:5)
#6      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4780:20)
#7      Parser.parseClassOrMixinOrExtensionOrEnumMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4529:15)
#8      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4174:15)
#9      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2624:13)
#10     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2582:14)
#11     Parser._handleModifiersForClassDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:771:12)
#12     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:645:14)
#13     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:593:14)
#14     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:403:15)
#15     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1267:12)
<asynchronous suspension>
#16     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:676:7)
<asynchronous suspension>
#17     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:611:7)
<asynchronous suspension>
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#19     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#20     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#21     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#22     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#23     compile (package:front_end/src/api_unstable/ddc.dart:217:7)
<asynchronous suspension>
#24     _compile (package:dev_compiler/src/kernel/command.dart:290:14)
<asynchronous suspension>
#25     runBatch (package:dev_compiler/ddc.dart:97:16)
<asynchronous suspension>
#26     internalMain (package:dev_compiler/ddc.dart:32:5)
<asynchronous suspension>
```

cc @johnniwinther

**Comment by asashour** [comment]
[sdk/281682](https://dart-review.googlesource.com/c/sdk/+/281682)

inline classes constructors do not have the additional 0 index of `this`.
