### ISSUE TITLE
vm/dart/reachability_test is flaky

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/sdk#51304]
This test most recently went from Pass -> RuntimeError on [vm-appjit-linux-product-x64](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-appjit-linux-product-x64), but it has a history of being flaky on other configurations (https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=vm/dart/reachability_test)

**Comment by mkustermann** [comment]
This happened again today.

See [log](https://dart-ci.appspot.com/log/vm-aot-linux-product-x64/vm-aot-linux-product-x64/1/vm/dart/reachability_test):
```
--- Command "vm_compile_to_kernel" (took 02.000207s):
DART_CONFIGURATION=ProductX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ProductX64/vm_platform_strong.dill -o /b/s/w/ir/out/ProductX64/generated_compilations/vm-aot-linux-product-x64/runtime_tests_vm_dart_reachability_test/out.dill /b/s/w/ir/runtime/tests/vm/dart/reachability_test.dart -Dtest_runner.configuration=vm-aot-linux-product-x64 --packages=/b/s/w/ir/.dart_tool/package_config.json -Ddart.vm.product=true --sound-null-safety

exit code:
0

--- Command "precompiler" (took 01.000611s):
DART_CONFIGURATION=ProductX64 out/ProductX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/ProductX64/generated_compilations/vm-aot-linux-product-x64/runtime_tests_vm_dart_reachability_test/out.S --sound-null-safety --new_gen_semi_max_size=1 -Dtest_runner.configuration=vm-aot-linux-product-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ProductX64/generated_compilations/vm-aot-linux-product-x64/runtime_tests_vm_dart_reachability_test/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 7ms):
DART_CONFIGURATION=ProductX64 rm /b/s/w/ir/out/ProductX64/generated_compilations/vm-aot-linux-product-x64/runtime_tests_vm_dart_reachability_test/out.dill

exit code:
0

--- Command "assemble" (took 298ms):
DART_CONFIGURATION=ProductX64 gcc -Wl,--no-undefined -shared -o /b/s/w/ir/out/ProductX64/generated_compilations/vm-aot-linux-product-x64/runtime_tests_vm_dart_reachability_test/out.aotsnapshot /b/s/w/ir/out/ProductX64/generated_compilations/vm-aot-linux-product-x64/runtime_tests_vm_dart_reachability_test/out.S

exit code:
0

--- Command "remove_assembly" (took 22ms):
DART_CONFIGURATION=ProductX64 rm /b/s/w/ir/out/ProductX64/generated_compilations/vm-aot-linux-product-x64/runtime_tests_vm_dart_reachability_test/out.S

exit code:
0

--- Command "vm" (took 02.000646s):
DART_CONFIGURATION=ProductX64 out/ProductX64/dart_precompiled_runtime --new_gen_semi_max_size=1 --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-product-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ProductX64/generated_compilations/vm-aot-linux-product-x64/runtime_tests_vm_dart_reachability_test/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:696)
#1      Expect.isTrue (package:expect/expect.dart:127)
#2      main (file:///b/s/w/ir/runtime/tests/vm/dart/reachability_test.dart:36)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

--- Re-run this test:
python3 tools/test.py -n vm-aot-linux-product-x64 vm/dart/reachability_test
```

/cc @a-siva could you have a look?

**Comment by a-siva** [comment]
In product mode the reachability barrier is implemented to always return 0 and so this test should be marked as SkipByDesign in this mode. When I look at the current results page for this test I notices that apart from the RuntimeError in the product modes there is also some flaky failures in the reload bots and a simarm64 bot, need to investigate these.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/285421

**Comment by a-siva** [comment]
I have noticed that most of the recent failures in this test has been time outs in simarm64 configuration, the test has fairly large number of iterations and two full garbage collections. I expect on a simulator architecture it could be fairly slow and explains the timeouts. Probably makes sense to Skip it in the sim architectures.

**Comment by a-siva** [comment]
Status file adjustment is here https://dart-review.googlesource.com/c/sdk/+/312888
