### ISSUE TITLE
Internal problem: Unhandled handleForInitializerPatternVariableAssignment in BodyBuilder

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51311]
I tried to run the fibonacci generator in the patterns spec.
```dart
void fibonacciTheHardWay() {
  var fns = <Function>[];
  for (var (a, b) = (0, 1); a <= 13; (a, b) = (b, a + b)) {
    fns.add(() {
      print(a);
    });
  }
  for (var fn in fns) {
    fn();
  }
}
```
It crashed with the error in the title. I'm running from IntelliJ using a Dart project, although the problem occurs when run from the command line, too. 

My Dart version is:
Dart SDK version: 3.0.0-edge.3d01b0aac3b5f143a2ccbefa8f9339272e1591a4 (be) (Tue Feb 7 18:24:54 2023 +0000) on "macos_x64"
```
.../src/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dart --enable-experiment=records,patterns --enable-asserts --pause_isolates_on_start --enable-vm-service:54298 .../IdeaProjects/plain_dart/bin/plain_dart.dart
The Dart VM service is listening on http://127.0.0.1:54298/Djq9jdydoIY=/

The Dart DevTools debugger and profiler is available at: http://127.0.0.1:54298/Djq9jdydoIY=/devtools?uri=ws://127.0.0.1:54298/Djq9jdydoIY=/ws

------------------
  Scope(<library>, (main, fibonacciTheHardWay, plain_dart))
  VariableDeclarationImpl(dynamic fns)
  NullValues.BreakTarget
  NullValues.ContinueTarget
  Scope(block function body, (fns))
  NullValues.Metadata
  RecordPattern((var a, var b))
  InternalRecordLiteral((0, 1))
  >> handleForInitializerPatternVariableAssignment
../../runtime/vm/dart_api_impl.cc: 6170: error: An error occurred in the CFE while acking the most recent compilation results: Crash when compiling .../IdeaProjects/plain_dart/bin/plain_dart.dart at character offset 348:
bin/plain_dart.dart: Internal problem: Unhandled handleForInitializerPatternVariableAssignment in BodyBuilder.

#0      internalProblem (package:front_end/src/fasta/problems.dart:52:5)
#1      StackListenerImpl.internalProblem (package:front_end/src/fasta/source/stack_listener_impl.dart:81:21)
#2      StackListener.logEvent (package:_fe_analyzer_shared/src/parser/stack_listener.dart:184:5)
#3      Listener.handleForInitializerPatternVariableAssignment (package:_fe_analyzer_shared/src/parser/listener.dart:609:5)
#4      Parser.parseForStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7841:18)
#5      Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5356:14)
#6      Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5315:20)
#7      Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5220:15)
#8      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1120:14)
#9      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:376:5)
#10     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3682:14)
#11     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3424:14)
#12     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:606:14)
#13     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:403:15)
#14     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1267:12)
<asynchronous suspension>
#15     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:676:7)
<asynchronous suspension>
#16     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:611:7)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#18     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:413:23)
<asynchronous suspension>
#19     IncrementalCompiler.reject (package:vm/incremental_compiler.dart:192:5)
<asynchronous suspension>
#20     _processLoadRequest (.../src/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:836:11)
<asynchronous suspension>

version=3.0.0-edge.3d01b0aac3b5f143a2ccbefa8f9339272e1591a4 (be) (Tue Feb 7 18:24:54 2023 +0000) on "macos_x64"
pid=40936, thread=259, isolate_group=main(0x7f92d5813600), isolate=main(0x7f92d5820200)
os=macos, arch=x64, comp=no, sim=no
isolate_instructions=101941700, vm_instructions=101941700
fp=7ff7be611e40, sp=7ff7be611e08, pc=101b95774
  pc 0x0000000101b95774 fp 0x00007ff7be611e40 dart::Profiler::DumpStackTrace(void*)+0x64
  pc 0x0000000101941922 fp 0x00007ff7be611f20 dart::Assert::Fail(char const*, ...) const+0x92
  pc 0x0000000102092e03 fp 0x00007ff7be612010 Dart_CompileToKernel+0xf3
  pc 0x000000010191a4f8 fp 0x00007ff7be612070 dart::bin::DFE::CompileAndReadScript(char const*, unsigned char**, long*, char**, int*, char const*, bool)+0x48
  pc 0x000000010191d88a fp 0x00007ff7be612100 dart::bin::main(int, char**)+0x16ca
  pc 0x000000010191bf86 fp 0x00007ff7be6121d0 dart::bin::RunMainIsolate(char const*, char const*, bool, dart::bin::CommandLineOptions*)+0x776
  pc 0x000000010191b8f5 fp 0x00007ff7be612290 dart::bin::RunMainIsolate(char const*, char const*, bool, dart::bin::CommandLineOptions*)+0xe5
  pc 0x000000010191c820 fp 0x00007ff7be6123d0 dart::bin::main(int, char**)+0x660
  pc 0x000000010191b7dd fp 0x00007ff7be6123f0 main+0xd
  pc 0x00007ff81a2db310 fp 0x00007ff7be612690 start+0x980
-- End of DumpStackTrace

------------------
  Scope(<library>, (main, fibonacciTheHardWay, plain_dart))
  VariableDeclarationImpl(dynamic fns)
  NullValues.BreakTarget
  NullValues.ContinueTarget
  Scope(block function body, (fns))
  NullValues.Metadata
  RecordPattern((var a, var b))
  InternalRecordLiteral((0, 1))
  >> handleForInitializerPatternVariableAssignment

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by asashour** [comment]
I think this is fixed in `edge`.

**Comment by chloestefantsova** [comment]
Yes, this one was fixed some time ago.
