### ISSUE TITLE
Front-end generates invalid type in co19/LanguageFeatures/Patterns/pattern_variable_sets_A01_t02

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51325]
Part of https://github.com/dart-lang/sdk/issues/49749.

For the following pattern in `co19/LanguageFeatures/Patterns/pattern_variable_sets_A01_t02`
```
    case {"key1": var v7} || var v7 when v7 == 7:
      return "map";
```

Front-end generates the following kernel AST:
```
static method test2(core::Object? x) → core::String {
...
invalid-type v7;
...

                  if((#0#0 is{ForNonNullableByDefault} core::Map<dynamic, dynamic> && (#0#4#isSet ?{core::bool} #0#4{core::bool} : let final dynamic #t45 = #0#4#isSet = true in #0#4 = #0#0{core::List<dynamic>}.{core::List::length}{core::int} =={core::num::==}{(core::Object) → core::bool} #C2) && #0#0{core::Map<dynamic, dynamic>}.{core::Map::containsKey}(#C1){(core::Object?) → core::bool} && (let final dynamic #t46 = v7 = #0#0{core::Map<dynamic, dynamic>}.{core::Map::[]}(#C1){(core::Object?) → dynamic} as{ForNonNullableByDefault} invalid-type in true) || (let final dynamic #t47 = v7 = #0#0 in true)) && v7 =={core::Object::==}{(core::Object) → core::bool} 7) {
                    {
                      return "map";
                    }
                  }
```

Note that invalid-type is used in the type of `v7` and in `... as{ForNonNullableByDefault} invalid-type` expression.

Because of this invalid type, AOT compiler crashes with the following stack trace:
```
Unexpected type InvalidType InvalidType(<invalid>)
#0      TypesBuilder.fromStaticType (package:vm/transformations/type_flow/types.dart:118:7)
#1      SummaryCollector._typeCheck (package:vm/transformations/type_flow/summary_collector.dart:1097:23)
#2      SummaryCollector.visitAsExpression (package:vm/transformations/type_flow/summary_collector.dart:1461:30)
#3      AsExpression.accept (package:kernel/ast.dart:8135:44)
...
```

Can be reproduced with
```
tools/test.py -n dartkp-strong-linux-release-x64 co19/LanguageFeatures/Patterns/pattern_variable_sets_A01_t02
```

@johnniwinther @chloestefantsova

**Comment by alexmarkov** [comment]
The test passes on AOT, so it looks like invalid type was fixed.
