### ISSUE TITLE
patterns: Unrecognized for loop parts

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51332]
This code causes an exception:
```dart
// For-loop parts
void fibonacciTheHardWay() {
  var fns = <Function()>[];
  for (var (a, b) = (0, 1); a <= 13; (a, b) = (b, a + b)) {
    fns.add(() {
      print(a);
    });
  }
  for (var fn in fns) {
    fn();
  }
}
```
The code is almost the same as in #51311, but this is actually correct.
Stack trace from IntelliJ log:
```
2023-02-08 15:41:55,602 [1121850]   INFO - #c.i.w.i.i.j.s.DelayedProjectSynchronizer$Companion - Workspace model loaded from cache. Syncing real project state into workspace model in 14 ms. Thread[DefaultDispatcher-worker-8,5,main]
2023-02-08 15:42:05,255 [1131503] SEVERE - #c.j.l.d.a.DartAnalysisServerService - Error from edit_getAssists(), file = /Users/messick/IdeaProjects/plain_dart/bin/plain_dart.dart, SDK version = 3.0.0-edge.ec6712542c1eb71fde152f8aba1eeca1e309cc03, server version = 1.33.4, error code = SERVER_ERROR: Bad state: Unrecognized for loop parts
#0      StatementAnalyzer.visitForStatement (package:analysis_server/src/services/correction/statement_analyzer.dart:114:9)
#1      ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5789:50)
#2      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9594:20)
#3      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1257:17)
#4      SelectionAnalyzer.visitNode (package:analysis_server/src/services/correction/selection_analyzer.dart:87:12)
#5      GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:663:40)
#6      GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:171:32)
#7      BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1253:50)
#8      BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1208:12)
#9      SelectionAnalyzer.visitNode (package:analysis_server/src/services/correction/selection_analyzer.dart:87:12)
#10     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:367:46)
#11     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:174:56)
#12     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1200:50)
#13     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6103:11)
#14     SelectionAnalyzer.visitNode (package:analysis_server/src/services/correction/selection_analyzer.dart:87:12)
#15     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:206:56)
#16     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:303:42)
#17     GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:382:58)
#18     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6092:50)
#19     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5964:25)
#20     SelectionAnalyzer.visitNode (package:analysis_server/src/services/correction/selection_analyzer.dart:87:12)
#21     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:135:48)
#22     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:258:44)
#23     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:220:7)
#24     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:507:7)
#25     GeneralizingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:374:12)
#26     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5958:50)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9594:20)
#28     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2578:21)
#29     SelectionAnalyzer.visitNode (package:analysis_server/src/services/correction/selection_analyzer.dart:87:12)
#30     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:217:52)
#31     StatementAnalyzer.visitCompilationUnit (package:analysis_server/src/services/correction/statement_analyzer.dart:68:11)
#32     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2571:50)
#33     StatementAnalyzer.analyze (package:analysis_server/src/services/correction/statement_analyzer.dart:55:24)
#34     SurroundWith.producers (package:analysis_server/src/services/correction/dart/surround_with.dart:25:23)
#35     AssistProcessor._addFromProducers (package:analysis_server/src/services/correction/assist_internal.dart:228:48)
<asynchronous suspension>
#36     AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:173:5)
<asynchronous suspension>
#37     EditGetAssistsHandler._computeServerAssists (package:analysis_server/src/handler/legacy/edit_get_assists.dart:98:23)
<asynchronous suspension>
#38     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#39     EditGetAssistsHandler.handle (package:analysis_server/src/handler/legacy/edit_get_assists.dart:51:19)
<asynchronous suspension>
#40     LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:479:11)
<asynchronous suspension>
#41     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#42     LegacyAnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:464:7)
<asynchronous suspension>


#0      EditGetAssistsHandler._computeServerAssists (package:analysis_server/src/handler/legacy/edit_get_assists.dart:110:9)
<asynchronous suspension>
#1      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#2      EditGetAssistsHandler.handle (package:analysis_server/src/handler/legacy/edit_get_assists.dart:51:19)
<asynchronous suspension>
#3      LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:479:11)
<asynchronous suspension>
#4      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#5      LegacyAnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:464:7)
<asynchronous suspension>
...
java.lang.Throwable: Error from edit_getAssists(), file = /Users/messick/IdeaProjects/plain_dart/bin/plain_dart.dart, SDK version = 3.0.0-edge.ec6712542c1eb71fde152f8aba1eeca1e309cc03, server version = 1.33.4, error code = SERVER_ERROR: Bad state: Unrecognized for loop parts
#0      StatementAnalyzer.visitForStatement (package:analysis_server/src/services/correction/statement_analyzer.dart:114:9)
#1      ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5789:50)
#2      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9594:20)
#3      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1257:17)
#4      SelectionAnalyzer.visitNode (package:analysis_server/src/services/correction/selection_analyzer.dart:87:12)
#5      GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:663:40)
#6      GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:171:32)
#7      BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1253:50)
#8      BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1208:12)
#9      SelectionAnalyzer.visitNode (package:analysis_server/src/services/correction/selection_analyzer.dart:87:12)
#10     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:367:46)
#11     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:174:56)
#12     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1200:50)
#13     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6103:11)
#14     SelectionAnalyzer.visitNode (package:analysis_server/src/services/correction/selection_analyzer.dart:87:12)
#15     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:206:56)
#16     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:303:42)
#17     GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:382:58)
#18     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6092:50)
#19     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5964:25)
#20     SelectionAnalyzer.visitNode (package:analysis_server/src/services/correction/selection_analyzer.dart:87:12)
#21     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:135:48)
#22     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:258:44)
#23     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:220:7)
#24     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:507:7)
#25     GeneralizingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:374:12)
#26     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5958:50)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9594:20)
#28     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2578:21)
#29     SelectionAnalyzer.visitNode (package:analysis_server/src/services/correction/selection_analyzer.dart:87:12)
#30     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:217:52)
#31     StatementAnalyzer.visitCompilationUnit (package:analysis_server/src/services/correction/statement_analyzer.dart:68:11)
#32     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2571:50)
#33     StatementAnalyzer.analyze (package:analysis_server/src/services/correction/statement_analyzer.dart:55:24)
#34     SurroundWith.producers (package:analysis_server/src/services/correction/dart/surround_with.dart:25:23)
#35     AssistProcessor._addFromProducers (package:analysis_server/src/services/correction/assist_internal.dart:228:48)
<asynchronous suspension>
#36     AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:173:5)
<asynchronous suspension>
#37     EditGetAssistsHandler._computeServerAssists (package:analysis_server/src/handler/legacy/edit_get_assists.dart:98:23)
<asynchronous suspension>
#38     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#39     EditGetAssistsHandler.handle (package:analysis_server/src/handler/legacy/edit_get_assists.dart:51:19)
<asynchronous suspension>
#40     LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:479:11)
<asynchronous suspension>
#41     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#42     LegacyAnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:464:7)
<asynchronous suspension>


#0      EditGetAssistsHandler._computeServerAssists (package:analysis_server/src/handler/legacy/edit_get_assists.dart:110:9)
<asynchronous suspension>
#1      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#2      EditGetAssistsHandler.handle (package:analysis_server/src/handler/legacy/edit_get_assists.dart:51:19)
<asynchronous suspension>
#3      LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:479:11)
<asynchronous suspension>
#4      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#5      LegacyAnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:464:7)
<asynchronous suspension>
...
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.logError(DartAnalysisServerService.java:2350)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$8.onError(DartAnalysisServerService.java:1160)
	at com.google.dart.server.internal.remote.processor.AssistsProcessor.process(AssistsProcessor.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:798)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:1147)
```
cc @scheglov

**Comment by srawlins** [comment]
CC @bwilkerson

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/281947
