### ISSUE TITLE
[CFE] Inline class method tear-offs are labeled as extension members

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#51338]
Dart version: 3.0.0-edge.70344d7fc69924ea0d65818c3c40a28786b5c04f
Platform: macOS

Using test.py with `--enable-experiment=inline-class` and dart2js.

A simple repro is just any inline class with a method e.g.:

```dart
inline class A {
  final int i = 0;
  A();
  void method() {}
}
```
The generated `Procedure` node for the tear-off for `method` (`A|get#method`) has `isExtensionMember` set to true.

**Comment by asashour** [comment]
Is there a possibility to test this with the bleeding edge, and provide the full command to reproduce?

I have tried to check the flags of the class members at the `front-end`, and they are all `0`, so `isExtensionMember` is `false`.

**Comment by srujzs** [comment]
Can repro using version `Dart SDK version: 3.0.0-edge.232ed497eab5f45d0affdf835edaa1fc94ed480e (be) (Mon Feb 13 09:52:14 2023 -0800) on "macos_x64"`.

The command I'm using is `python3 tools/test.py -r chrome -c dart2js --enable-experiment=inline-class <location_of_test_in_tests_folder>`.


You can repro the issue by just using the member `method`:

```
inline class A {
  final int i = 0;
  A();
  void method() {}
}

void main() {
  (A().method)();
}
```

The resulting error might not be very useful, though. dart2js assumes that because the tear-off is an extension member, there must exists an extension:

```
Internal Error: The compiler crashed when compiling this element.
  void method() {}
       ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Bad state: No original name found for extension member A|get#method.
#0      _findExtensionMemberName (package:compiler/src/io/kernel_source_information.dart:99:3)
#1      computeKernelElementNameForSourceMaps (package:compiler/src/io/kernel_source_information.dart:45:42)
#2      new KernelSourceInformationBuilder (package:compiler/src/io/kernel_source_information.dart:117:17)
#3      KernelSourceInformationStrategy.createBuilderForContext (package:compiler/src/io/kernel_source_information.dart:28:12)
#4      KernelSsaGraphBuilder._enterFrame (package:compiler/src/ssa/builder.dart:443:42)
#5      new KernelSsaGraphBuilder (package:compiler/src/ssa/builder.dart:189:5)
#6      KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:528:39)
#7      CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#8      KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:527:18)
#9      SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:361:21)
#10     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:87:28)
#11     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:420:30)
#12     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:334:43)
#13     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:486:29)
#14     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:787:70)
#15     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#16     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:787:32)
#17     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#18     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:785:28)
#19     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:783:18)
#21     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:252:12)
#22     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:268:5)
#23     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:779:16)
#24     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#25     Compiler.emptyQueue (package:compiler/src/compiler.dart:778:14)
#26     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:802:7)
#27     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#28     Compiler.processQueue (package:compiler/src/compiler.dart:796:14)
#29     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:531:5)
#30     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:728:23)
<asynchronous suspension>
#31     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:316:7)
<asynchronous suspension>
#32     Compiler.runInternal (package:compiler/src/compiler.dart:315:5)
<asynchronous suspension>
#33     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:236:11)
<asynchronous suspension>
```

It might be easier to inspect the resulting kernel using the DebugPrinter, maybe? My guess is that the entry-point for DDC and dart2js go through a slightly different code path to produce the kernel that might be resulting in the discrepancy. Let me know if you need further help to repro. Thanks!

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/283864

has a fix, in which CFE should create the `Procedure` with a newly added parameter `isInlineClassMember`.

I am not sure how best to test this behavior.

**Comment by srujzs** [comment]
I'm not sure either, but FWIW, this fixes the above repro for me (where dart2js assertions fail)! Maybe @johnniwinther has an idea on why we're seeing different behavior for the web backends versus the front-end tests?

**Comment by johnniwinther** [comment]
It seems that the other backends to rely on the being able to find the name of an extension through `Library.extensions` when `isExtensionMember` is set.

For the testing of it. The `ast_to_text.dart` should probably print when `isExtensionMember` and `isInlineClassMember` is set. It currently doesn't so the fix doesn't show up in our tests.
