### ISSUE TITLE
Failures on [vm] Allow sharing of deeply immutable lists across isolates

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#51345]
There are new test failures on [[vm] Allow sharing of deeply immutable lists across isolates](https://github.com/dart-lang/sdk/commit/896e535fe92e96e0b78f64f1587a58b3411c3680).

The tests
```
vm/dart/isolates/fast_object_copy2_test/0 Crash (expected Pass)
vm/dart/isolates/fast_object_copy2_test/1 Crash (expected Pass)
vm/dart/isolates/fast_object_copy2_test/2 Crash (expected Pass)
vm/dart/isolates/fast_object_copy2_test/3 Crash (expected Pass)
```
are failing on configurations
```
vm-aot-msan-linux-release-x64
vm-msan-linux-release-x64
```

@mkustermann

**Comment by mkustermann** [comment]
For reference:
```
Uninitialized bytes in __msan_check_mem_is_initialized at offset 0 inside [0x701000002540, 10)
==18012==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55b0a226d141 in dart::ExternalTypedData::New(long, unsigned char*, long, dart::Heap::Space, bool) ../../out/ReleaseMSANX64/../../runtime/vm/object.cc:26224:5
    #1 0x55b0a2a92378 in dart::NewExternalTypedData(dart::Thread*, long, void*, long, void*, long, void (*)(void*, void*), bool) ../../out/ReleaseMSANX64/../../runtime/vm/dart_api_impl.cc:3851:7
    #2 0x55b0a2a6a178 in dart::NewExternalTypedDataWithFinalizer(Dart_TypedData_Type, void*, long, void*, long, void (*)(void*, void*), bool) ../../out/ReleaseMSANX64/../../runtime/vm/dart_api_impl.cc
    #3 0x55b0a2a6a303 in Dart_NewUnmodifiableExternalTypedDataWithFinalizer ../../out/ReleaseMSANX64/../../runtime/vm/dart_api_impl.cc:4044:10
    #4 0x7f65e47172d0 in FfiTrampoline__createUnmodifiableTypedData$Method$FfiNative$Ptr dart:ffi
    #5 0x7f65e4717273 in FfiTrampoline__createUnmodifiableTypedData$Method$FfiNative$Ptr dart:ffi
    #6 0x7f65e4719f7f in createUnmodifiableTypedData file:///b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart/isolates/fast_object_copy2_test.dart:218
    #7 0x7f65e47191af in SendReceiveTest.testSharableTypedData file:///b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart/isolates/fast_object_copy2_test.dart:168
    #8 0x7f65e471ab07 in SendReceiveTest.runTests file:///b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart/isolates/fast_object_copy2_test.dart:113
python3 tools/test.py -n vm-aot-msan-linux-release-x64 vm/dart/isolates/fast_object_copy2_test/0
```
