### ISSUE TITLE
Compiler crashing when using pattern in collection-for

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/sdk#51376]
Likely just due to not being implemented yet, but I am trying out the patterns and records features and came across a compiler crash. 

Using `Dart SDK version: 3.0.0-229.0.dev (dev) (Fri Feb 10 20:38:38 2023 -0800) on "windows_x64"`.

Take this example

```dart
void main() {
  print(left([(1,2), (3, 4)])); // expecting [1, 3]
}

List<A> left<A, B>(List<(A, B)> pairs) => [for (var (a, _) in pairs) a];
```

compiled with `dart --enable-experiment=records,patterns bin/example.dart`

```
Crash when compiling file:///C:/Users/mmcdo/Documents/projects/project/bin/example.dart at character offset 110:
Null check operator used on a null value

#0      InferenceVisitorImpl.inferElement (package:front_end/src/fasta/type_inference/inference_visitor.dart:2262:40)       
#1      InferenceVisitorImpl.visitListLiteral (package:front_end/src/fasta/type_inference/inference_visitor.dart:2382:42)   
#2      ListLiteral.accept1 (package:kernel/ast.dart:8684:9)
#3      InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:263:27)    
#4      InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:298:40)     
#5      InferenceVisitorImpl.visitReturnStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:7281:11)
#6      ReturnStatement.accept (package:kernel/ast.dart:10766:43)
#7      InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:241:26)      
#8      TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:196:17)
#9      BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1344:43)
#10     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1123:19)
#11     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:376:5)
#12     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3682:14)
#13     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3424:14)
#14     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:606:14)
#15     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:403:15)
#16     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1267:12)
<asynchronous suspension>
#17     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:676:7)
<asynchronous suspension>
#18     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:611:7)       
<asynchronous suspension>
#19     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#20     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#21     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#22     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#23     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#24     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#25     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:407:11)       
<asynchronous suspension>
#26     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:215:45)
<asynchronous suspension>
#27     _processLoadRequest (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:889:37)
<asynchronous suspension>
```

**Comment by mmcdon20** [comment]
Crashes also with collection-if pattern.

**Comment by mmcdon20** [comment]
Discovered another weird issue with for patterns, although this one is unrelated to collection-for.

In the example program below, the only difference between `split1` and `split2` is that `split1` has `{}` around the body of the for loop, and `split2` does not.

```dart
void main() {
  print(split1([1,2,3]));
  print(split2([1,2,3]));
}

Iterable<(Iterable<A>, Iterable<A>)> split1<A>(Iterable<A> iterable) => switch (iterable) {
  Iterable<A>(isEmpty: true) => [(Iterable<A>.empty(), Iterable<A>.empty())],
  Iterable<A>(first: var x) => () sync* {
      yield (Iterable<A>.empty(), iterable); 
      for (var (ls, rs) in split1(iterable.skip(1))) {
        yield ([x, ...ls], rs);
      }
    }(),
};

Iterable<(Iterable<A>, Iterable<A>)> split2<A>(Iterable<A> iterable) => switch (iterable) {
  Iterable<A>(isEmpty: true) => [(Iterable<A>.empty(), Iterable<A>.empty())],
  Iterable<A>(first: var x) => () sync* {
      yield (Iterable<A>.empty(), iterable); 
      for (var (ls, rs) in split2(iterable.skip(1))) 
        yield ([x, ...ls], rs);
    }(),
};
```

When running the program, `split1` compiles and runs successfully, but `split2` produces a concurrent modification exception at runtime.

```
(((), [1, 2, 3]), ([1], (2, 3)), ([1, 2], (3)), ([1, 2, 3], ()))
Unhandled exception:
Concurrent modification during iteration: Instance(length:1) of '_GrowableList'.
#0      List.addAll (dart:core-patch/growable_array.dart:308:11)
#1      split2.<anonymous closure> (package:countdown_core/solvers/split.dart:21:23)
#2      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554:14)
#3      _iterablePartsToStrings (dart:collection/iterable.dart:320:13)
#4      IterableBase.iterableToShortString (dart:collection/iterable.dart:240:7)
#5      Iterable.toString (dart:core/iterable.dart:799:37)
#6      _StringBase._interpolateSingle (dart:core-patch/string_patch.dart:829:17)
#7      print (dart:core/print.dart:9:26)
#8      main (package:countdown_core/solvers/split.dart:3:3)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

**Comment by asashour** [comment]
-  [sdk/282602](https://dart-review.googlesource.com/c/sdk/+/282602) for the OP crash
- Please provide a test case for the crash of `collection-if pattern`, in a separate issue if the stacktrace is different.
- I guess the last point should also be better in a separate issue.
