### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by lianchao157** [dart-lang/sdk#51381]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

# Exception

Please append the contents of:
file://C:\Users\廉超\AppData\Local\Temp\report739.txt

```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: D:\AndroidStudioworkitem\lctest\flutter_app\flutter_app_progrom1130\lib\login.dart
Bad state: Too many elements
#0      List.single (dart:core/runtime/libgrowable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2526:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5121:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1640:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)

**Comment by asashour** [comment]
This SDK version is more than 4 years old. Please use a more recent version.
