### ISSUE TITLE
for patterns without `{}` around body sometimes cause concurrent modification exception

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/sdk#51380]
Creating this as a separate issue at the request of @asashour.

Discovered another weird issue with for patterns, although this one is unrelated to collection-for.

In the example program below, the only difference between `split1` and `split2` is that `split1` has `{}` around the body of the for loop, and `split2` does not.

```dart
void main() {
  print(split1([1,2,3]));
  print(split2([1,2,3]));
}

Iterable<(Iterable<A>, Iterable<A>)> split1<A>(Iterable<A> iterable) => switch (iterable) {
  Iterable<A>(isEmpty: true) => [(Iterable<A>.empty(), Iterable<A>.empty())],
  Iterable<A>(first: var x) => () sync* {
      yield (Iterable<A>.empty(), iterable); 
      for (var (ls, rs) in split1(iterable.skip(1))) {
        yield ([x, ...ls], rs);
      }
    }(),
};

Iterable<(Iterable<A>, Iterable<A>)> split2<A>(Iterable<A> iterable) => switch (iterable) {
  Iterable<A>(isEmpty: true) => [(Iterable<A>.empty(), Iterable<A>.empty())],
  Iterable<A>(first: var x) => () sync* {
      yield (Iterable<A>.empty(), iterable); 
      for (var (ls, rs) in split2(iterable.skip(1))) 
        yield ([x, ...ls], rs);
    }(),
};
```

When running the program, `split1` compiles and runs successfully, but `split2` produces a concurrent modification exception at runtime.

```
(((), [1, 2, 3]), ([1], (2, 3)), ([1, 2], (3)), ([1, 2, 3], ()))
Unhandled exception:
Concurrent modification during iteration: Instance(length:1) of '_GrowableList'.
#0      List.addAll (dart:core-patch/growable_array.dart:308:11)
#1      split2.<anonymous closure> (package:countdown_core/solvers/split.dart:21:23)
#2      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554:14)
#3      _iterablePartsToStrings (dart:collection/iterable.dart:320:13)
#4      IterableBase.iterableToShortString (dart:collection/iterable.dart:240:7)
#5      Iterable.toString (dart:core/iterable.dart:799:37)
#6      _StringBase._interpolateSingle (dart:core-patch/string_patch.dart:829:17)
#7      print (dart:core/print.dart:9:26)
#8      main (package:countdown_core/solvers/split.dart:3:3)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

_Originally posted by @mmcdon20 in https://github.com/dart-lang/sdk/issues/51376#issuecomment-1427119202_

**Comment by mraleph** [comment]
Something either is wrong in the CFE desugaring or VM's Kernel-to-IL 

/cc @alexmarkov @chloestefantsova

**Comment by asashour** [comment]
[sdk/282680](https://dart-review.googlesource.com/c/sdk/+/282680)
