### ISSUE TITLE
TimelineEventFileRecorder deletion races with the Draining thread

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#51438]
```
WARNING: ThreadSanitizer: data race on vptr (ctor/dtor vs virtual call) (pid=2868828)
  Write of size 8 at 0x7b4400000280 by main thread:
    #0 ~TimelineEventFileRecorderBase ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:1586 (dart_precompiled_runtime+0xa89d21)
    #1 ~TimelineEventFileRecorder ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:1687 (dart_precompiled_runtime+0xa89d21)
    #2 ~TimelineEventFileRecorder ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:1684 (dart_precompiled_runtime+0xa89e39)
    #3 dart::Timeline::Cleanup() ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:284 (dart_precompiled_runtime+0xa8369a)
    #4 dart::Dart::Cleanup() ../../out/ReleaseTSANX64/../../runtime/vm/dart.cc:785 (dart_precompiled_runtime+0x887d8a)
    #5 Dart_Cleanup ../../out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1217 (dart_precompiled_runtime+0xeb4de4)
    #6 dart::bin::main(int, char**) ../../out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:1415 (dart_precompiled_runtime+0x68bb77)
    #7 main ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:9 (dart_precompiled_runtime+0x68a9f4)

  Previous read of size 8 at 0x7b4400000280 by thread T2:
    #0 dart::TimelineEventFileRecorderBase::Drain() ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:1628 (dart_precompiled_runtime+0xa89983)
    #1 dart::TimelineEventFileRecorderBaseStart(unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:1558 (dart_precompiled_runtime+0xa89c59)
    #2 dart::ThreadStart(void*) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154 (dart_precompiled_runtime+0x9d859b)

  Location is heap block of size 280 at 0x7b4400000280 allocated by main thread:
    #0 malloc ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:691 (dart_precompiled_runtime+0x5faddc)
    #1 dart::malloc(unsigned long) ../../out/ReleaseTSANX64/../../runtime/platform/allocation.cc:20 (dart_precompiled_runtime+0x6c3a0c)
    #2 dart::MallocAllocated::operator new(unsigned long) ../../out/ReleaseTSANX64/../../runtime/platform/allocation.h:48 (dart_precompiled_runtime+0xa8252c)
    #3 dart::CreateTimelineRecorder() ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:157 (dart_precompiled_runtime+0xa8252c)
    #4 dart::Timeline::Init() ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:239 (dart_precompiled_runtime+0xa8252c)
    #5 dart::Dart::DartInit(Dart_InitializeParams const*) ../../out/ReleaseTSANX64/../../runtime/vm/dart.cc:318 (dart_precompiled_runtime+0x8869ea)
    #6 dart::Dart::Init(Dart_InitializeParams const*) ../../out/ReleaseTSANX64/../../runtime/vm/dart.cc:532 (dart_precompiled_runtime+0x8871eb)
    #7 Dart_Initialize ../../out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1212 (dart_precompiled_runtime+0xeb4d6b)
    #8 dart::bin::main(int, char**) ../../out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:1356 (dart_precompiled_runtime+0x68b9f0)
    #9 main ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:9 (dart_precompiled_runtime+0x68a9f4)

  Thread T2 'TimelineEventFi' (tid=2869290, running) created by main thread at:
    #0 pthread_create ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1047 (dart_precompiled_runtime+0x5fcacb)
    #1 dart::OSThread::Start(char const*, void (*)(unsigned long), unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:173 (dart_precompiled_runtime+0x9d8453)
    #2 TimelineEventFileRecorder ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:1679 (dart_precompiled_runtime+0xa89c26)
    #3 dart::CreateTimelineRecorder() ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:157 (dart_precompiled_runtime+0xa8253a)
    #4 dart::Timeline::Init() ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:239 (dart_precompiled_runtime+0xa8253a)
    #5 dart::Dart::DartInit(Dart_InitializeParams const*) ../../out/ReleaseTSANX64/../../runtime/vm/dart.cc:318 (dart_precompiled_runtime+0x8869ea)
    #6 dart::Dart::Init(Dart_InitializeParams const*) ../../out/ReleaseTSANX64/../../runtime/vm/dart.cc:532 (dart_precompiled_runtime+0x8871eb)
    #7 Dart_Initialize ../../out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1212 (dart_precompiled_runtime+0xeb4d6b)
    #8 dart::bin::main(int, char**) ../../out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:1356 (dart_precompiled_runtime+0x68b9f0)
    #9 main ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:9 (dart_precompiled_runtime+0x68a9f4)

SUMMARY: ThreadSanitizer: data race on vptr (ctor/dtor vs virtual call) ../../out/ReleaseTSANX64/../../runtime/vm/timeline.cc:1586 in ~TimelineEventFileRecorderBase
==================
ThreadSanitizer: reported 1 warnings

Unhandled exception:
Child process failed: 66
#0      runAndCollectTimeline.<anonymous closure> (file:///usr/local/google/home/asiva/workspace/dart-nnbd/sdk/runtime/tests/vm/dart/timeline_utils.dart:27)
<asynchronous suspension>
#1      withTempDir (file:///usr/local/google/home/asiva/workspace/dart-nnbd/sdk/runtime/tests/vm/dart/snapshot_test_helper.dart:127)
<asynchronous suspension>
#2      runAndCollectTimeline (file:///usr/local/google/home/asiva/workspace/dart-nnbd/sdk/runtime/tests/vm/dart/timeline_utils.dart:14)
<asynchronous suspension>
#3      main (file:///usr/local/google/home/asiva/workspace/dart-nnbd/sdk/runtime/tests/vm/dart/timeline_recorder_file_test.dart:21)
<asynchronous suspension>

```

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/283705
