### ISSUE TITLE
Pattern matching causes compiler crash

### ISSUE THREAD

**Issue by jrmooring** [dart-lang/sdk#51450]
3.0.0-204.0.dev, --enable-experiment=records,patterns

```dart
void main() {
  final _ = switch (0) {
      (_: int y) => 0,
  };
}
```

```
Error compiling to JavaScript:
Info: Compiling with sound null safety.
lib/main.dart:1:6:
Internal Error: The compiler crashed when compiling this element.
void main() {
     ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.0.0-204.0.dev), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Bad state: representationForShape RecordShape(0, {_})
#0      RecordData.representationForShape (package:compiler/src/js_model/records.dart:88:10)
#1      RecordData.pathForAccess (package:compiler/src/js_model/records.dart:110:28)
#2      KernelSsaGraphBuilder._handleRecordFieldGet (package:compiler/src/ssa/builder.dart:3472:30)
#3      KernelSsaGraphBuilder.visitRecordNameGet (package:compiler/src/ssa/builder.dart:3452:12)
#4      RecordNameGet.accept (package:kernel/ast.dart:4631:44)
#5      KernelSsaGraphBuilder.visitReturnStatement (package:compiler/src/ssa/builder.dart:1860:24)
#6      ReturnStatement.accept (package:kernel/ast.dart:10766:43)
#7      KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder.dart:1259:24)
#8      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder.dart:494:13)
#9      DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#10     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder.dart:439:21)
#11     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:545:22)
#12     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#13     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:527:18)
#14     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:361:21)
#15     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:87:28)
#16     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:420:30)
#17     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:334:43)
#18     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:486:29)
#19     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:771:70)
#20     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#21     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:771:32)
#22     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#23     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:769:28)
#24     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#25     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:767:18)
#26     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:252:12)
#27     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:268:5)
#28     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:763:16)
#29     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#30     Compiler.emptyQueue (package:compiler/src/compiler.dart:762:14)
#31     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:786:7)
#32     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#33     Compiler.processQueue (package:compiler/src/compiler.dart:780:14)
#34     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:517:5)
#35     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:712:23)
<asynchronous suspension>
#36     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:315:7)
<asynchronous suspension>
#37     Compiler.runInternal (package:compiler/src/compiler.dart:314:5)
<asynchronous suspension>
#38     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:235:11)
<asynchronous suspension>
#39     main (package:compiler/src/dart2js.dart:1449:3)
<asynchronous suspension>
```

**Comment by asashour** [comment]
Would you mind testing with `3.0.0-204.0.dev`? I have a different error, but not a crash.

```
Error: Expected an identifier, but got 'switch'.
  final _ = switch (0) {
            ^^^^^^
abc.dart:3:11:
Error: Expected ';' after this.
  final _ = switch (0) {
          ^
abc.dart:4:3:
Error: Expected to find 'case'.
  (_: int y) => 0,
  ^
Error: Compilation failed.
```

**Comment by jrmooring** [comment]
Note that this is run with `--enable-experiment=records,patterns`

**Comment by asashour** [comment]
Yes, now there is the below, which is not a crash.

```dart
lib/a.dart:4:21: Error: The type 'int' is not exhaustively matched by the switch cases.
Try adding a default case or cases that match int.
  final _ = switch (0) {
```

`Dart SDK version: 3.0.0-259.0.dev (dev) (Mon Feb 20 13:25:07 2023 -0800) on "windows_x64"`

**Comment by sigmundch** [comment]
Closing as @asashour noted, this no longer crashes and now provides a static error message from the compiler.
