### ISSUE TITLE
Build sdk failed

### ISSUE THREAD

**Issue by arcticfox1919** [dart-lang/sdk#51458]
I follow the steps in https://github.com/dart-lang/sdk/wiki/Building#source and the build fails on Windows10:

```
Generating Visual Studio projects took 426ms
Done. Made 345 targets from 86 files in 9301ms
buildtools/ninja/ninja -C out\DebugX64 runtime
ninja: Entering directory `out\DebugX64'
[200/2544] ACTION //runtime/observatory:build_observatory(//build/toolchain/win:clang_x64)
FAILED: gen/runtime/observatory/observatory/web/main.dart.js gen/runtime/observatory/observatory/web/main.dart.js.map
D:/develop2/depot_tools/bootstrap-2@3_8_10_chromium_26_bin/python3/bin/python3.exe ../../build/gn_run_binary.py compiled_action G:/Repository/git_code/c++/dart-sdk/sdk/tools/sdks/dart-sdk/bin/dart.exe --dfe=G:/Repository/git_code/c++/dart-sdk/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot compile js -o G:/Repository/git_code/c++/dart-sdk/sdk/out/DebugX64/gen/runtime/observatory/observatory/web/main.dart.js --packages=G:/Repository/git_code/c++/dart-sdk/sdk/.dart_tool/package_config.json --no-sound-null-safety G:/Repository/git_code/c++/dart-sdk/sdk/runtime/observatory/web/main.dart --enable-asserts
Command failed: G:\Repository\git_code\c++\dart-sdk\sdk\tools\sdks\dart-sdk\bin\dart.exe --dfe=G:/Repository/git_code/c++/dart-sdk/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot compile js -o G:/Repository/git_code/c++/dart-sdk/sdk/out/DebugX64/gen/runtime/observatory/observatory/web/main.dart.js --packages=G:/Repository/git_code/c++/dart-sdk/sdk/.dart_tool/package_config.json --no-sound-null-safety G:/Repository/git_code/c++/dart-sdk/sdk/runtime/observatory/web/main.dart --enable-asserts
output: Error: Error when reading '../../.dart_tool/package_config.json': Error reading '../../.dart_tool/package_config.json'  (The system can not find the file specified.)
Info: Compiling without sound null safety!
Dart 3 will only support sound null safety, see https://dart.dev/null-safety
Error: Error when reading '../../.dart_tool/package_config.json': Error reading '../../.dart_tool/package_config.json'  (The system can not find the file specified.)
Error: Couldn't resolve the package 'logging' in 'package:logging/logging.dart'.
Error: Couldn't resolve the package 'observatory' in 'package:observatory/elements.dart'.
Error: Couldn't resolve the package 'stack_trace' in 'package:stack_trace/stack_trace.dart'.
../../runtime/observatory/web/main.dart:6:8:
Error: Not found: 'package:logging/logging.dart'
import 'package:logging/logging.dart';
       ^
../../runtime/observatory/web/main.dart:7:8:
Error: Not found: 'package:observatory/elements.dart'
import 'package:observatory/elements.dart';
       ^
../../runtime/observatory/web/main.dart:8:8:
Error: Not found: 'package:stack_trace/stack_trace.dart'
import 'package:stack_trace/stack_trace.dart';
       ^
../../runtime/observatory/web/main.dart:12:5:
Error: Undefined name 'Logger'.
    Logger.root.level = Level.INFO;
    ^^^^^^
../../runtime/observatory/web/main.dart:12:25:
Error: Undefined name 'Level'.
    Logger.root.level = Level.INFO;
                        ^^^^^
../../runtime/observatory/web/main.dart:13:5:
Error: Undefined name 'Logger'.
    Logger.root.onRecord.listen((LogRecord rec) {
    ^^^^^^
../../runtime/observatory/web/main.dart:13:34:
Error: 'LogRecord' isn't a type.
    Logger.root.onRecord.listen((LogRecord rec) {
                                 ^^^^^^^^^
../../runtime/observatory/web/main.dart:16:5:
Error: Undefined name 'Logger'.
    Logger.root.info('Starting Observatory');
    ^^^^^^
../../runtime/observatory/web/main.dart:18:24:
Error: Couldn't find constructor 'ObservatoryApplicationElement.created'.
        .insert(0, new ObservatoryApplicationElement.created().element);
                       ^^^^^^^
../../runtime/observatory/web/main.dart:11:3:
Error: Undefined name 'Chain'.
  Chain.capture(() async {
  ^^^^^
Error: Compilation failed.

[225/2544] CXX obj/runtime/platform/libdart_platform_precompiled_runtime.hashmap.obj
ninja: build stopped: subcommand failed.
BUILD FAILED
```

It seems that the error caused by the `../../.dart_tool/package_config.json` file is not found. I do not have this file on my machine. Is there a step missing in the [build documentation](https://github.com/dart-lang/sdk/wiki/Building#source)? How should I solve this problem?

**Comment by mraleph** [comment]
Did you do `gclient sync`? Did it complete without errors? Try `gclient runhooks` then. 

Let me know if this does not help.

**Comment by arcticfox1919** [comment]
@mraleph 

Yes, I executed `gclient sync` and here is the output, but I still report the same error when I execute `python tools/build.py --no-goma --mode release --arch x64 create_sdk` to compile.

I'm using version 2.19.2: ` git checkout 2.19.2`. Do you have any other suggestions for me? I'd appreciate it!

```
G:\Repository\git_code\c++\dart-sdk\sdk>gclient sync
Updating depot_tools...
using C:\Users\ARCTIC~1\AppData\Local\Temp\goma as tmpdir
compiler_proxy is not running
Syncing projects: 100% (97/97), done.

WARNING: 'sdk\third_party\pkg\charcode' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg\oauth2' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg\pedantic' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg\platform' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg\process' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg\shelf_packages_handler' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg\shelf_proxy' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg\shelf_static' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg\shelf_web_socket' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg_tested\dart_style' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg_tested\http_io' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg_tested\package_config' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\perfetto' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\pkg\tools' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'sdk\third_party\protobuf' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

________ running 'python3 sdk/tools/generate_package_config.py' in 'G:\Repository\git_code\c++\dart-sdk'
Duplicates found for package:shelf_packages_handler
  third_party\pkg\shelf\pkgs\shelf_packages_handler
  third_party\pkg\shelf_packages_handler
Duplicates found for package:shelf_proxy
  third_party\pkg\shelf_proxy
  third_party\pkg\shelf\pkgs\shelf_proxy
Duplicates found for package:shelf_static
  third_party\pkg\shelf\pkgs\shelf_static
  third_party\pkg\shelf_static
Duplicates found for package:shelf_web_socket
  third_party\pkg\shelf_web_socket
  third_party\pkg\shelf\pkgs\shelf_web_socket
Error: Command 'python3 sdk/tools/generate_package_config.py' returned non-zero exit status 1 in G:\Repository\git_code\c++\dart-sdk
Duplicates found for package:shelf_packages_handler
  third_party\pkg\shelf\pkgs\shelf_packages_handler
  third_party\pkg\shelf_packages_handler
Duplicates found for package:shelf_proxy
  third_party\pkg\shelf_proxy
  third_party\pkg\shelf\pkgs\shelf_proxy
Duplicates found for package:shelf_static
  third_party\pkg\shelf\pkgs\shelf_static
  third_party\pkg\shelf_static
Duplicates found for package:shelf_web_socket
  third_party\pkg\shelf_web_socket
  third_party\pkg\shelf\pkgs\shelf_web_socket
```
------

```
G:\Repository\git_code\c++\dart-sdk\sdk>gclient runhooks
Updating depot_tools...
using C:\Users\ARCTIC~1\AppData\Local\Temp\goma as tmpdir
compiler_proxy is not running

________ running 'python3 sdk/tools/generate_package_config.py' in 'G:\Repository\git_code\c++\dart-sdk'
Duplicates found for package:shelf_packages_handler
  third_party\pkg\shelf\pkgs\shelf_packages_handler
  third_party\pkg\shelf_packages_handler
Duplicates found for package:shelf_proxy
  third_party\pkg\shelf_proxy
  third_party\pkg\shelf\pkgs\shelf_proxy
Duplicates found for package:shelf_static
  third_party\pkg\shelf\pkgs\shelf_static
  third_party\pkg\shelf_static
Duplicates found for package:shelf_web_socket
  third_party\pkg\shelf_web_socket
  third_party\pkg\shelf\pkgs\shelf_web_socket
Error: Command 'python3 sdk/tools/generate_package_config.py' returned non-zero exit status 1 in G:\Repository\git_code\c++\dart-sdk
Duplicates found for package:shelf_packages_handler
  third_party\pkg\shelf\pkgs\shelf_packages_handler
  third_party\pkg\shelf_packages_handler
Duplicates found for package:shelf_proxy
  third_party\pkg\shelf_proxy
  third_party\pkg\shelf\pkgs\shelf_proxy
Duplicates found for package:shelf_static
  third_party\pkg\shelf\pkgs\shelf_static
  third_party\pkg\shelf_static
Duplicates found for package:shelf_web_socket
  third_party\pkg\shelf_web_socket
  third_party\pkg\shelf\pkgs\shelf_web_socket

```

**Comment by lrhn** [comment]
Did you try running `gclient sync -D` as suggested?

**Comment by arcticfox1919** [comment]
Executing the `gclient sync -D` command seems to have solved the previous problem, but it still cannot be compiled successfully, and a new error is generated:


```
Generating Visual Studio projects took 143ms
Done. Made 345 targets from 86 files in 3842ms
buildtools/ninja/ninja -C out\ReleaseX64 create_sdk
ninja: Entering directory `out\ReleaseX64'
[587/3242] ACTION //runtime/observatory:build_observatory(//build/toolchain/win:clang_x64)
FAILED: gen/runtime/observatory/observatory/web/main.dart.js
D:/develop2/depot_tools/bootstrap-2@3_8_10_chromium_26_bin/python3/bin/python3.exe ../../build/gn_run_binary.py compiled_action G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/tools/sdks/dart-sdk/bin/dart.exe --dfe=G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot compile js -o G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/out/ReleaseX64/gen/runtime/observatory/observatory/web/main.dart.js --packages=G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/.dart_tool/package_config.json --no-sound-null-safety G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/runtime/observatory/web/main.dart --minify
Command failed: G:\Repository\git_code\c++\dart_shared_libray\dart-sdk\sdk\tools\sdks\dart-sdk\bin\dart.exe --dfe=G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot compile js -o G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/out/ReleaseX64/gen/runtime/observatory/observatory/web/main.dart.js --packages=G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/.dart_tool/package_config.json --no-sound-null-safety G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/runtime/observatory/web/main.dart --minify
output: Info: Compiling without sound null safety!
Dart 3 will only support sound null safety, see https://dart.dev/null-safety
../../runtime/observatory/lib/src/service/object.dart:2139:3:
Hint: This 'noSuchMethod' implementation is guaranteed to throw an exception. The generated code will be smaller if it is rewritten.
Rewrite to 'noSuchMethod(Invocation i) => super.noSuchMethod(i);'.
  noSuchMethod(_) => throw "Unimplemented ServiceMap method";
  ^
The compiler crashed: WebSocketException: Connection to 'http://127.0.0.1:64235/EhRSbYjpDQk=/ws#' was not upgraded to websocket
#0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
#1      WebSocket.connect (dart:_http/websocket.dart:320:22)
#2      vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
#3      _currentHeapCapacity (package:compiler/src/common/ram_usage.dart:27:41)
<asynchronous suspension>
#4      currentHeapCapacityInMb (package:compiler/src/common/ram_usage.dart:38:20)
<asynchronous suspension>
#5      compile.compilationDone (package:compiler/src/dart2js.dart:1067:12)
<asynchronous suspension>
#6      main (package:compiler/src/dart2js.dart:1424:3)
<asynchronous suspension>


[612/3242] CXX obj/runtime/vm/compiler/backend/libdart_compiler_precompiler.il_serializer.obj
ninja: build stopped: subcommand failed.
BUILD FAILED
```

**Comment by mraleph** [comment]
Do you have some kind of firewall or security software on your Windows box? It looks like it is messing up with socket connectivity. 

As a temporary workaround you can just edit [this function](https://github.com/dart-lang/sdk/blob/main/pkg/compiler/lib/src/common/ram_usage.dart#L21) to return `0` instead of whatever it is doing now.

**Comment by arcticfox1919** [comment]
@mraleph 
I tried your suggestion, but it didn't work.

I think this may be a BUG of the build environment! The error is caused by executing a command. It fails to generate `runtime/observatory/observatory/web/main.dart.js` file. The reason may be `Info: Compiling without sound null safety!`. But after I `git checkout main`, compile again and repeat the compilation steps, it succeeds. I checked, the difference between `main` branch and `2.19.2` is the version of `dart-sdk\sdk\tools\sdks\dart-sdk\bin\dart.exe`,  and the current `dart.exe` under `main` branch is `3.0.0-187.0.dev`.

```
Command failed: G:\Repository\git_code\c++\dart_shared_libray\dart-sdk\sdk\tools\sdks\dart-sdk\bin\dart.exe 
--dfe=G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot compile js 
-o G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/out/ReleaseX64/gen/runtime/observatory/observatory/web/main.dart.js 
--packages=G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/.dart_tool/package_config.json 
--no-sound-null-safety G:/Repository/git_code/c++/dart_shared_libray/dart-sdk/sdk/runtime/observatory/web/main.dart 
--minify
```

**Comment by mraleph** [comment]
> I tried your suggestion, but it didn't work.

Ah, right. Build processes uses dart2js from the checked-in SDK (one in `tools`) to compile the observatory, so changing that file will not help. 

> The reason may be Info: Compiling without sound null 

No this is just an informational message. The actual crash is clearly this one:

> The compiler crashed: WebSocketException: Connection to 'http://127.0.0.1:64235/EhRSbYjpDQk=/ws#' was not upgraded to websocket
> #0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)

What happens on your machine if you try running this code:

```dart
import 'dart:developer';
import 'package:vm_service/vm_service_io.dart' as vm_service_io;

void main() async {
  final info =
      await Service.controlWebServer(enable: true, silenceOutput: true);
  final observatoryUri = info.serverUri;
  if (observatoryUri == null) return null;
  final wsUri = 'ws://${observatoryUri.authority}${observatoryUri.path}ws';
  final vmService = await vm_service_io.vmServiceConnectUri(wsUri);
  int sum = 0;
  for (final group in (await vmService.getVM()).isolateGroups!) {
    final usage = await vmService.getIsolateGroupMemoryUsage(group.id!);
    sum += usage.heapCapacity!;
  }
  vmService.dispose();
  print('OK: $sum');
}
```

Save it to the root of the SDK checkout and then run:

```
tools\sdks\dart-sdk\bin\dart.exe test.dart
```

**Comment by arcticfox1919** [comment]
@mraleph 
After I checkout from the `main` branch to `2.19.2`, the problem seems to be solved, and I can compile successfully! I tested your code and everything works, thanks for your reply anyway.

```
OK: 14954496
```

**Comment by Krysl** [comment]
Same error about `WebSocketException: Invalid WebSocket upgrade request`

In my case, it's because I set env (I'm from china, I need to set these proxy up for the  `gclient sync`  to run successfully):
```
HTTP_PROXY= 127.0.0.1:8066
HTTPS_PROXY= 127.0.0.1:8066
```

Just clear these env var, problems gone;

<details>
<summary>Some logs</summary>

## 1
```
D:\flutter\dart-sdk\sdk (main) 
# get_proxy
HTTP_PROXY = 127.0.0.1:8066
HTTPS_PROXY = 127.0.0.1:8066
ALL_PROXY =

D:\flutter\dart-sdk\sdk (main) 
# tools\sdks\dart-sdk\bin\dart.exe test.dart
vm-service: Error: Unhandled exception:
WebSocketException: Invalid WebSocket upgrade request

Unhandled exception:
WebSocketException: Invalid WebSocket upgrade request
Unhandled exception:
WebSocketException: Connection to 'http://127.0.0.1:5055/jxbN9E26rrg=/ws#' was not upgraded to websocket
#0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
#1      WebSocket.connect (dart:_http/websocket.dart:320:22)
#2      vmServiceConnectUriWithFactory (package:vm_service/vm_service_io.dart:26:44)
#3      vmServiceConnectUri (package:vm_service/vm_service_io.dart:12:10)
#4      main (file:///D:/flutter/dart-sdk/sdk/test.dart:10:41)
<asynchronous suspension>

D:\flutter\dart-sdk\sdk (main) 
#
```

logs in proxy v2rayN:
```
2024/04/24 12:04:22 127.0.0.1:5056 accepted http://127.0.0.1:5055/jxbN9E26rrg=/ws [http -> direct]
```

## 2. shutdown v2rayN
```
D:\flutter\dart-sdk\sdk (main) 
# tools\sdks\dart-sdk\bin\dart.exe test.dart
Unhandled exception:
SocketException: 远程计算机拒绝网络连接。
 (OS Error: 远程计算机拒绝网络连接。
, errno = 1225), address = 127.0.0.1, port = 5275
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1914:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2138:22)
#4      Socket.startConnect (dart:io/socket.dart:805:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2484:20)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2923:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2928:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2783:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2620:7)
#10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021:42)
#11     WebSocket.connect (dart:_http/websocket.dart:320:22)
#12     vmServiceConnectUriWithFactory (package:vm_service/vm_service_io.dart:26:44)
#13     vmServiceConnectUri (package:vm_service/vm_service_io.dart:12:10)
#14     main (file:///D:/flutter/dart-sdk/sdk/test.dart:10:41)
<asynchronous suspension>

D:\flutter\dart-sdk\sdk (main) 
#
```

## 3. clear env var `HTTP_PROXY `&`HTTPS_PROXY `, ans problems gone
```
D:\flutter\dart-sdk\sdk (main) 
# set_proxy_off
====== Close Proxy... ======
====== envs before set ======
HTTP_PROXY = 127.0.0.1:8066
HTTPS_PROXY = 127.0.0.1:8066

====== set envs ======

====== envs now ======
HTTP_PROXY = 
HTTPS_PROXY =
ALL_PROXY =

D:\flutter\dart-sdk\sdk (main) 
# tools\sdks\dart-sdk\bin\dart.exe test.dart
OK: 14209024

D:\flutter\dart-sdk\sdk (main) 
#
```

</details>
