### ISSUE TITLE
memmove from null in CodeSourceMapBuilder breaks UBSan build

### ISSUE THREAD

**Issue by gnprice** [dart-lang/sdk#51465]
When I try building the SDK with UBSan enabled, the build fails because undefined behavior is detected in gen_snapshot:

```
$ tools/build.py --no-goma --mode=release --arch x64 --sanitizer ubsan
…
Command failed: /home/greg/n/dart-sdk/sdk/out/ReleaseUBSANX64/gen_snapshot_product --deterministic --snapshot-kind=app-aot-elf --elf=/home/greg/n/dart-sdk/sdk/out/ReleaseUBSANX64/dart2wasm_product.snapshot /home/greg/n/dart-sdk/sdk/out/ReleaseUBSANX64/gen/utils/dart2wasm/dart2wasm_product.dart.dill
output: ../../runtime/vm/code_descriptors.cc:512:23: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:47:14: note: nonnull attribute specified here
    #0 0x55ed594eede5 in dart::CodeSourceMapBuilder::Finalize() ../../out/ReleaseUBSANX64/../../runtime/vm/code_descriptors.cc:512:3
…
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../runtime/vm/code_descriptors.cc:512:23 in 

[7622/7690] ACTION //utils/compiler:dart2js(//build/toolchain/linux:clang_x64)
ninja: build stopped: subcommand failed.
BUILD FAILED
```

That's at commit 0c05e33836662da52b963158ccd6b9c211208429 from main, on Linux. Full command output below.

### Diagnosis

The crashing function looks like this:
```c++
CodeSourceMapPtr CodeSourceMapBuilder::Finalize() {
  // …
  intptr_t length = stream_.bytes_written();
  // …
  memmove(map.Data(), stream_.buffer(), length); // error here
```

So `memmove` is being called with a null pointer for the source, which is undefined behavior.

Inspecting in a debugger, `length` is zero. So the stream `stream_` contains no data, and it's normal that `stream_.buffer()` is null.

But although that's normal for the stream, passing that null pointer to `memmove` is UB. So `CodeSourceMapBuilder::Finalize` should avoid calling `memmove` in that case.

Pragmatically, when the UBSan build fails because of this case of UB, it makes it difficult to run tests on that build.

### Full command output

<details><summary>Full command output</summary>

```
$ time tools/build.py --no-goma --mode=release --arch x64 --sanitizer ubsan
Done. Made 341 targets from 89 files in 150ms
buildtools/ninja/ninja -C out/ReleaseUBSANX64 all
ninja: Entering directory `out/ReleaseUBSANX64'
[7611/7690] ACTION //utils/dart2wasm:dart2wasm...ct_snapshot(//build/toolchain/linux:clang_x64)
FAILED: dart2wasm_product.snapshot 
python3 ../../build/gn_run_binary.py compiled_action gen_snapshot_product --deterministic --snapshot-kind=app-aot-elf --elf=/home/greg/n/dart-sdk/sdk/out/ReleaseUBSANX64/dart2wasm_product.snapshot /home/greg/n/dart-sdk/sdk/out/ReleaseUBSANX64/gen/utils/dart2wasm/dart2wasm_product.dart.dill
Command failed: /home/greg/n/dart-sdk/sdk/out/ReleaseUBSANX64/gen_snapshot_product --deterministic --snapshot-kind=app-aot-elf --elf=/home/greg/n/dart-sdk/sdk/out/ReleaseUBSANX64/dart2wasm_product.snapshot /home/greg/n/dart-sdk/sdk/out/ReleaseUBSANX64/gen/utils/dart2wasm/dart2wasm_product.dart.dill
output: ../../runtime/vm/code_descriptors.cc:512:23: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:47:14: note: nonnull attribute specified here
    #0 0x55ed594eede5 in dart::CodeSourceMapBuilder::Finalize() ../../out/ReleaseUBSANX64/../../runtime/vm/code_descriptors.cc:512:3
    #1 0x55ed5995e5ec in dart::FlowGraphCompiler::FinalizeCodeSourceMap(dart::Code const&) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/backend/flow_graph_compiler.cc:1385:55
    #2 0x55ed598e0390 in dart::PrecompileParsedFunctionHelper::FinalizeCompilation(dart::compiler::Assembler*, dart::FlowGraphCompiler*, dart::FlowGraph*, dart::CodeStatistics*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/aot/precompiler.cc:3426:19
    #3 0x55ed598e0fba in dart::PrecompileParsedFunctionHelper::Compile(dart::CompilationPipeline*) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/aot/precompiler.cc:3576:9
    #4 0x55ed598e19fd in dart::PrecompileFunctionHelper(dart::Precompiler*, dart::CompilationPipeline*, dart::Function const&, bool) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/aot/precompiler.cc:3700:33
    #5 0x55ed598da5cc in dart::Precompiler::CompileFunction(dart::Precompiler*, dart::Thread*, dart::Zone*, dart::Function const&) ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/aot/precompiler.cc:3759:10
    #6 0x55ed5965aafa in dart::ProgramWalker::VisitFunction(dart::Function const&) ../../out/ReleaseUBSANX64/../../runtime/vm/program_visitor.cc:171:36
    #7 0x55ed5965778b in dart::ProgramWalker::VisitWorklist() ../../out/ReleaseUBSANX64/../../runtime/vm/program_visitor.cc:120:9
    #8 0x55ed59656f52 in dart::ProgramVisitor::WalkProgram(dart::Zone*, dart::IsolateGroup*, dart::ClassVisitor*) ../../out/ReleaseUBSANX64/../../runtime/vm/program_visitor.cc:287:10
    #9 0x55ed598d16cc in dart::Precompiler::PrecompileConstructors() ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/aot/precompiler.cc:734:3
    #10 0x55ed598cb9b1 in dart::Precompiler::DoCompileAll() ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/aot/precompiler.cc:505:9
    #11 0x55ed598cb78a in dart::Precompiler::CompileAll() ../../out/ReleaseUBSANX64/../../runtime/vm/compiler/aot/precompiler.cc:371:17
    #12 0x55ed59bcec43 in Dart_Precompile ../../out/ReleaseUBSANX64/../../runtime/vm/dart_api_impl.cc:6524:3
    #13 0x55ed593b7e14 in dart::bin::CreateAndWritePrecompiledSnapshot() ../../out/ReleaseUBSANX64/../../runtime/bin/gen_snapshot.cc:657:12
    #14 0x55ed593b7e14 in dart::bin::CreateIsolateAndSnapshot(dart::bin::CommandLineOptions const&) ../../out/ReleaseUBSANX64/../../runtime/bin/gen_snapshot.cc:832:7
    #15 0x55ed593b7e14 in dart::bin::main(int, char**) ../../out/ReleaseUBSANX64/../../runtime/bin/gen_snapshot.cc:947:16
    #16 0x7f8ca7e0a09a in __libc_start_main /build/glibc-6iIyft/glibc-2.28/csu/../csu/libc-start.c:308:16
    #17 0x55ed5939f419 in _start (/home/greg/n/dart-sdk/sdk/out/ReleaseUBSANX64/gen_snapshot_product+0x8db419)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../runtime/vm/code_descriptors.cc:512:23 in 

[7622/7690] ACTION //utils/compiler:dart2js(//build/toolchain/linux:clang_x64)
ninja: build stopped: subcommand failed.
BUILD FAILED

time: 1584.492s wall (15948.887s u, 508.849s s)
```

</details>

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/285345

**Comment by gnprice** [comment]
Great, thanks! And it looks like that was just merged: https://github.com/dart-lang/sdk/commit/a346af7b7a376fa22e4582d8db28916b16e8ebea
