### ISSUE TITLE
[CFE, Patterns] Front-end generates a use of a local variable without declaration in co19/LanguageFeatures/Patterns/scope_A02_t06

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51479]
For the following code from `co19/LanguageFeatures/Patterns/scope_A02_t06`:

```dart
  var list = [1, for (var [c] = [2]; c < 3; Expect.equals(3, c)) c++, 3];
  Expect.listEquals([1, 2, 3], list);

  var map = {
      "k1": 1,
      for (var [c] = [2]; c < 3; Expect.equals(3, c)) "k2": c++,
      "k3": 3
    };
  Expect.mapEquals({"k1": 1, "k2": 2, "k2": 3}, map);
```

front-end generates the following kernel AST:

```
  static method main() → dynamic {
    core::List<dynamic> list = block {
      final core::List<dynamic> #t1 = <dynamic>[1];
      core::int c;
      {
        final dynamic #0#0 = <core::int>[2];
        if(!(#0#0{core::List<core::int>}.{core::List::length}{core::int} =={core::num::==}{(core::Object) → core::bool} #C1 && (let final dynamic #t2 = c = #0#0{core::List<core::int>}.{core::List::[]}(0){(core::int) → core::int} in true)))
          throw new _in::ReachabilityError::•();
      }
      for (dynamic c = c; c{dynamic}.<(3); exp::Expect::equals(3, c))
        #t1.{core::List::add}{Invariant}(let final dynamic #t3 = c in let final dynamic #t4 = c = #t3{dynamic}.+(1) in #t3){(dynamic) → void};
      #t1.{core::List::add}{Invariant}(3){(dynamic) → void};
    } =>#t1;
    exp::Expect::listEquals(<core::int>[1, 2, 3], list);
    core::Map<core::String, dynamic> map = block {
      final core::Map<core::String, dynamic> #t5 = <core::String, dynamic>{};
      #t5.{core::Map::[]=}{Invariant}("k1", 1){(core::String, dynamic) → void};
      for (dynamic c = c; c{dynamic}.<(3) as{TypeError,ForDynamic,ForNonNullableByDefault} core::bool; exp::Expect::equals(3, c))
        #t5.{core::Map::[]=}{Invariant}("k2", let final dynamic #t6 = c in let final dynamic #t7 = c = #t6{dynamic}.+(1) in #t6){(core::String, dynamic) → void};
      #t5.{core::Map::[]=}{Invariant}("k3", 3){(core::String, dynamic) → void};
    } =>#t5;
    exp::Expect::mapEquals(<core::String, core::int>{"k1": 1, "k2": 2, "k2": 3}, map);
```

Note that `core::Map<core::String, dynamic> map = block {` block references variable `c` (in `for (dynamic c = c; ...`) but it is not declared (or maybe it references variable `c` which was declared in the previous block and went out of scope).

This kernel AST cannot be serialized and results in the following crash:
```
--- Command "vm" (took 01.000009s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --sound-null-safety -Dtest_runner.configuration=dartk-strong-linux-release-x64 --enable-experiment=patterns --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/scope_A02_t06.dart

exit code:
252

stderr:
Null check operator used on a null value
#0      BinaryPrinter._getVariableIndex (package:kernel/binary/ast_to_binary.dart:83:17)
#1      BinaryPrinter.visitVariableGet (package:kernel/binary/ast_to_binary.dart:1575:17)
#2      VariableGet.accept (package:kernel/ast.dart:4435:44)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#4      BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:545:7)
#5      BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:2400:5)
#6      BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:338:16)
#7      BinaryPrinter.writeVariableDeclarationList (package:kernel/binary/ast_to_binary.dart:2407:5)
#8      BinaryPrinter.visitForStatement (package:kernel/binary/ast_to_binary.dart:2271:5)
#9      ForStatement.accept (package:kernel/ast.dart:10219:43)
#10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#11     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#12     BinaryPrinter.visitBlockExpression (package:kernel/binary/ast_to_binary.dart:2150:5)
#13     BlockExpression.accept (package:kernel/ast.dart:9328:44)
#14     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#15     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:545:7)
#16     BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:2400:5)
#17     BinaryPrinter.visitVariableDeclaration (package:kernel/binary/ast_to_binary.dart:2386:5)
#18     VariableDeclaration.accept (package:kernel/ast.dart:11338:43)
#19     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#20     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#21     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#22     Block.accept (package:kernel/ast.dart:9751:43)
#23     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#24     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:545:7)
#25     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1559:5)
#26     FunctionNode.accept (package:kernel/ast.dart:4178:38)
#27     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:453:10)
#28     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1388:5)
#29     Procedure.accept (package:kernel/ast.dart:3570:40)
#30     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:474:10)
#31     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:356:7)
#32     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1132:5)
#33     Library.accept (package:kernel/ast.dart:585:38)
#34     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:467:10)
#35     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:780:9)
#36     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:619:7)
#37     Timeline.timeSync (dart:developer/timeline.dart:166:22)
#38     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:600:14)
#39     serializeComponent (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:1036:11)
#40     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:947:41)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-strong-linux-release-x64 co19/LanguageFeatures/Patterns/scope_A02_t06
```

@johnniwinther @chloestefantsova

**Comment by chloestefantsova** [comment]
I'm working on a fix at https://dart-review.googlesource.com/c/sdk/+/284683.
