### ISSUE TITLE
Failures on Support external typed data in heapsnapshot analysis tool

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51477]
There are new test failures on [Support external typed data in heapsnapshot analysis tool](https://github.com/dart-lang/sdk/commit/d71a37af18751e6086d66d868521e31b0126e0a5).

The tests
```
standalone/io/socket_local_port_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-strong-win-debug-x64
```

```
--- Command "vm" (took 03.000642s):
set DART_CONFIGURATION=DebugX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64\crashpad_handler.exe & out\DebugX64\dart.exe --sound-null-safety -Dtest_runner.configuration=dartk-strong-win-debug-x64 --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\tests\standalone\io\socket_local_port_test.dart

exit code:
255

stderr:
Unhandled exception:
SocketException: Connection failed (OS Error: An attempt was made to access a socket in a way forbidden by its access permissions.

, errno = 10013), address = 127.0.0.1, port = 50989
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:689:35)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:954:12)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1837:26)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)
#4      Socket._connect (dart:io-patch/socket_patch.dart:2062:22)
#5      Socket.connect (dart:io/socket.dart:749:21)
#6      testCustomPort (file:///C:/b/s/w/ir/tests/standalone/io/socket_local_port_test.dart:89:27)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-strong-win-debug-x64 standalone/io/socket_local_port_test
```

This test started failing on a seemingly unrelated commit.

@athomas @whesse Was there any change in the Windows bot configuration?

/cc @brianquinlan @aam

**Comment by dcharkes** [comment]
Happened again: https://dart-ci.appspot.com/log/vm-aot-win-release-arm64/vm-aot-win-release-arm64/2429/standalone/io/socket_local_port_test

Same error.

**Comment by aam** [comment]
[still failing ](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8711248157415017025/+/u/test_results/new_test_failures__logs_)

```

/==================================================================================\
| standalone/io/socket_local_port_test broke (Pass -> RuntimeError, expected Pass) |
\==================================================================================/

--- Command "vm" (took 695ms):
DART_CONFIGURATION=ReleaseARM64 xcodebuild/ReleaseARM64/dart --enable_asserts -Dtest_runner.configuration=vm-checked-mac-release-arm64 --ignore-unrecognized-flags --packages=/Volumes/Work/s/w/ir/.dart_tool/package_config.json /Volumes/Work/s/w/ir/tests/standalone/io/socket_local_port_test.dart

exit code:
255

stderr:
Unhandled exception:
SocketException: Bind failed (OS Error: Address already in use, errno = 48), address = ::1
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:821:35)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:1146:12)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:2268:26)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:31:23)
#4      Socket._connect (dart:io-patch/socket_patch.dart:2557:22)
#5      Socket.connect (dart:io/socket.dart:869:21)
#6      testCustomPort (file:///Volumes/Work/s/w/ir/tests/standalone/io/socket_local_port_test.dart:103:27)
<asynchronous suspension>
#7      main (file:///Volumes/Work/s/w/ir/tests/standalone/io/socket_local_port_test.dart:185:3)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-checked-mac-release-arm64 standalone/io/socket_local_port_test
```

**Comment by mkustermann** [comment]
This happened again today.

The test is written horribly, used fixed numbers for server socket ports, has dead code in it, is inconsistent, ...

But I think the root cause is that the client-side address/port binding code doesn't use `SO_REUSEADDR` when it binds, which means that if there's another closed socket in `TIME_WAIT` it will prevent the client from binding. I've uploaded [cl/436902](https://dart-review.googlesource.com/c/sdk/+/436902)

**Comment by alexmarkov** [comment]
Still failing:

```
SocketException: Bind failed (OS Error: Address already in use, errno = 98), address = 127.0.0.1
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:821)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:1146)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:2275)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:31)
#4      Socket._connect (dart:io-patch/socket_patch.dart:2564)
#5      Socket.connect (dart:io/socket.dart:869)
#6      testCustomPort (file:///b/s/w/ir/tests/standalone/io/socket_local_port_test.dart:89)
<asynchronous suspension>
#7      main (file:///b/s/w/ir/tests/standalone/io/socket_local_port_test.dart:159)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-aot-linux-debug-x64c standalone/io/socket_local_port_test
```
[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8710211935700862929/+/u/test_results/new_test_failures__logs_)

**Comment by aam** [comment]
[failed again](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8709631696891593249/+/u/test_results/new_test_failures__logs_)

**Comment by aam** [comment]
[again failed](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8693139139189167777/+/u/test_results/new_test_failures__logs_)

**Comment by alexmarkov** [comment]
Started failing again:
```
Unhandled exception:
SocketException: Bind failed (OS Error: Address already in use, errno = 98), address = 127.0.0.1
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:817:35)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:1142:12)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:2256:26)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:31:23)
#4      Socket._connect (dart:io-patch/socket_patch.dart:2526:22)
#5      Socket.connect (dart:io/socket.dart:869:21)
#6      testCustomPort (file:///b/s/w/ir/tests/standalone/io/socket_local_port_test.dart:89:31)
<asynchronous suspension>
#7      main (file:///b/s/w/ir/tests/standalone/io/socket_local_port_test.dart:159:3)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-appjit-linux-debug-x64 standalone/io/socket_local_port_test
```
[log](https://dart-ci.appspot.com/log/vm-appjit-linux-debug-x64/vm-appjit-linux-debug-x64/5891/standalone/io/socket_local_port_test)

**Comment by aam** [comment]
https://dart-ci.appspot.com/log/vm-ubsan-linux-release-arm64/vm-aot-ubsan-linux-release-arm64/578/standalone/io/socket_local_port_test

```
--- Command "vm_compile_to_kernel" (took 01.000216s):
DART_CONFIGURATION=ReleaseUBSANARM64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseUBSANARM64/vm_platform.dill -o /b/s/w/ir/out/ReleaseUBSANARM64/generated_compilations/vm-aot-ubsan-linux-release-arm64/tests_standalone_io_socket_local_port_test/out.dill /b/s/w/ir/tests/standalone/io/socket_local_port_test.dart -Dtest_runner.configuration=vm-aot-ubsan-linux-release-arm64 --packages=/b/s/w/ir/.dart_tool/package_config.json -Ddart.vm.product=false -Ddart.vm.asan=false -Ddart.vm.msan=false -Ddart.vm.tsan=false

exit code:
0

--- Command "precompiler" (took 01.000854s):
DART_CONFIGURATION=ReleaseUBSANARM64 out/ReleaseUBSANARM64/gen_snapshot --snapshot-kind=app-aot-elf --elf=/b/s/w/ir/out/ReleaseUBSANARM64/generated_compilations/vm-aot-ubsan-linux-release-arm64/tests_standalone_io_socket_local_port_test/libout.so --loading-unit-manifest=/b/s/w/ir/out/ReleaseUBSANARM64/generated_compilations/vm-aot-ubsan-linux-release-arm64/tests_standalone_io_socket_local_port_test/ignored.json -Dtest_runner.configuration=vm-aot-ubsan-linux-release-arm64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseUBSANARM64/generated_compilations/vm-aot-ubsan-linux-release-arm64/tests_standalone_io_socket_local_port_test/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 31ms):
DART_CONFIGURATION=ReleaseUBSANARM64 rm /b/s/w/ir/out/ReleaseUBSANARM64/generated_compilations/vm-aot-ubsan-linux-release-arm64/tests_standalone_io_socket_local_port_test/out.dill

exit code:
0

--- Command "vm" (took 37ms):
DART_CONFIGURATION=ReleaseUBSANARM64 TEST_COMPILATION_DIR=/b/s/w/ir/out/ReleaseUBSANARM64/generated_compilations/vm-aot-ubsan-linux-release-arm64/tests_standalone_io_socket_local_port_test out/ReleaseUBSANARM64/dartaotruntime -Dtest_runner.configuration=vm-aot-ubsan-linux-release-arm64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseUBSANARM64/generated_compilations/vm-aot-ubsan-linux-release-arm64/tests_standalone_io_socket_local_port_test/libout.so

exit code:
255

stderr:
Unhandled exception:
SocketException: Bind failed (OS Error: Address already in use, errno = 98), address = 127.0.0.1
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:817)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:1142)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:2256)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:31)
#4      Socket._connect (dart:io-patch/socket_patch.dart:2526)
#5      Socket.connect (dart:io/socket.dart:869)
#6      testCustomPort (file:///b/s/w/ir/tests/standalone/io/socket_local_port_test.dart:89)
<asynchronous suspension>
#7      main (file:///b/s/w/ir/tests/standalone/io/socket_local_port_test.dart:159)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-aot-ubsan-linux-release-arm64 standalone/io/socket_local_port_test
```
