### ISSUE TITLE
[inline class]  Internal problem: Unhandled member in exportScope

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#51516]
See https://github.com/kevmoo/dart_frog/tree/inline_class_hacks

* in `packages/dart_frog`
* Run either
  * `dart --enable-experiment=inline-class example/main.dart`
  * `dart --enable-experiment=inline-class test`

```
Crash when compiling:
lib/src/pipeline.dart:7:14: Internal problem: Unhandled member in exportScope.
inline class Pipeline {
             ^

#0      internalProblem (package:front_end/src/fasta/problems.dart:52:5)
#1      unhandled (package:front_end/src/fasta/problems.dart:71:10)
#2      SourceLibraryBuilder.addImportsToScope (package:front_end/src/fasta/source/source_library_builder.dart:1483:15)
#3      SourceLoader.computeLibraryScopes (package:front_end/src/fasta/source/source_loader.dart:1476:23)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:426:14)
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:136:24)
#6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:409:12)
#7      _buildInternal (package:front_end/src/kernel_generator_impl.dart:143:26)
#8      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:111:14)
<asynchronous suspension>
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#10     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#11     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#12     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#13     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:407:11)
<asynchronous suspension>
#14     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:215:45)
<asynchronous suspension>
#15     _processLoadRequest (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:889:37)
<asynchronous suspension>
```

Dart SDK version: 3.0.0-263.0.dev (dev) (Tue Feb 21 17:59:38 2023 -0800) on "macos_arm64"

**Comment by asashour** [comment]
A minimal case:

a.dart:
```dart
export 'b.dart';

void main() {}
```

b.dart:
```dart
part 'c.dart';
```

c.dart:
```dart
inline class C {

  final int i;

  C(this.i);
}
```

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/285262

**Comment by kevmoo** [comment]
@asashour – FYI – I patched in that fix and see

```
 ~/github/dart/sdk/xcodebuild/ReleaseARM64/dart-sdk/bin/dart --enable-experiment=inline-class example/main.dart
Crash when compiling file:///Users/kevmoo/github/dart_frog/packages/dart_frog/lib/src/pipeline.dart at character offset 222:
Null check operator used on a null value

#0      BodyBuilder.lookupConstructor (package:front_end/src/fasta/kernel/body_builder.dart:3137:30)
#1      ThisAccessGenerator.buildConstructorInitializer (package:front_end/src/fasta/kernel/expression_generator.dart:4597:17)
#2      ThisAccessGenerator.buildSelectorAccess (package:front_end/src/fasta/kernel/expression_generator.dart:4495:14)
#3      InvocationSelector.withReceiver (package:front_end/src/fasta/kernel/expression_generator.dart:4912:23)
#4      BodyBuilder.doDotOrCascadeExpression (package:front_end/src/fasta/kernel/body_builder.dart:2937:17)
#5      BodyBuilder.endBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:2689:7)
#6      Listener.handleEndingBinaryExpression (package:_fe_analyzer_shared/src/parser/listener.dart:1635:5)
#7      Parser._parsePrecedenceExpressionLoop (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5784:22)
#8      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5673:12)
#9      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5589:15)
#10     Parser.parseInitializerExpressionRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3997:13)
#11     Parser.parseInitializer (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3891:17)
#12     Parser.parseInitializers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3805:15)
#13     Parser.parseInitializersOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3784:14)
#14     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1109:22)
#15     DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:751:5)
#16     DietListener.endClassConstructor (package:front_end/src/fasta/source/diet_listener.dart:698:5)
#17     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4802:20)
#18     Parser.parseClassOrMixinOrExtensionOrEnumMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4551:15)
#19     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4196:15)
#20     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2646:13)
#21     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2604:14)
#22     Parser._handleModifiersForClassDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:784:12)
#23     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:647:14)
#24     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:595:14)
#25     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:405:15)
#26     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1278:16)
<asynchronous suspension>
#27     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:676:7)
<asynchronous suspension>
#28     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:611:7)
<asynchronous suspension>
#29     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#30     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#31     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#32     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#33     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#34     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#35     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:407:11)
<asynchronous suspension>
#36     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:215:45)
<asynchronous suspension>
#37     _processLoadRequest (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:889:37)
<asynchronous suspension>
```

**Comment by asashour** [comment]
Thanks for your feedback.

The proposed CL currently contains a fix for the first issue, but you are right, there are more things needed.

The current reason is because `InlineClass` doesn't yet handle constructors.

https://github.com/dart-lang/sdk/blob/ba1d8bdbc0e15c46af258345b4440c0953045904/pkg/front_end/lib/src/fasta/source/source_inline_class_builder.dart#L270

**Comment by johnniwinther** [comment]
@kevmoo I think this have been fixed now. Please file a new issue if you still see problems.

**Comment by kevmoo** [comment]
Still crashing. You want a new issue, right?

3.1.0-146.0.dev (dev) (Thu May 25 03:04:23 2023 -0700) on "macos_arm64"

```
Crash when formatting: [InternalProblemUnhandled] Unhandled InlineClassMemberKind.Constructor in _findDirectInlineClassMember.
RangeError (offset): Invalid value: Not in inclusive range 0..560: 2773
#0      RangeError.checkValueInInterval (dart:core/errors.dart:313:7)
#1      Source.getLocation (package:kernel/ast.dart:15346:16)
#2      getLocation (package:front_end/src/fasta/messages.dart:17:52)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:91:43)
#4      CompilerContext.format (package:front_end/src/fasta/compiler_context.dart:79:35)
#5      internalProblem (package:front_end/src/fasta/problems.dart:53:10)
#6      unhandled (package:front_end/src/fasta/problems.dart:71:10)
#7      InferenceVisitorBase._findDirectInlineTypeMember (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1062:13)
#8      _ObjectAccessDescriptor._findNonExtensionTargetInternal (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:4818:44)
#9      _ObjectAccessDescriptor.findNonExtensionTarget (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:4763:12)
#10     InferenceVisitorBase.findInterfaceMember (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1367:32)
#11     InferenceVisitorImpl._computePropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:6702:20)
#12     InferenceVisitorImpl.visitPropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:7716:61)
#13     PropertyGet.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:3252:20)
#14     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:258:27)
#15     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:295:40)
#16     InferenceVisitorBase._inferInvocation.inferArgument (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1904:22)
#17     InferenceVisitorBase._inferInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1968:44)
#18     InferenceVisitorBase.inferInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1658:12)
#19     InferenceVisitorImpl.visitStaticInvocation (package:front_end/src/fasta/type_inference/inference_visitor.dart:8111:40)
#20     StaticInvocation.accept1 (package:kernel/ast.dart:7050:9)
#21     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:260:27)
#22     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:295:40)
#23     InferenceVisitorImpl.visitReturnStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:7938:11)
#24     ReturnStatement.accept (package:kernel/ast.dart:10829:43)
#25     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:238:26)
#26     InferenceVisitorImpl._visitStatements (package:front_end/src/fasta/type_inference/inference_visitor.dart:848:50)
#27     InferenceVisitorImpl.visitBlock (package:front_end/src/fasta/type_inference/inference_visitor.dart:869:31)
#28     Block.accept (package:kernel/ast.dart:9788:43)
#29     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:238:26)
#30     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:202:17)
#31     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1263:43)
#32     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1137:19)
#33     DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:765:5)
#34     DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:705:5)
#35     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4915:20)
#36     Parser.parseClassOrMixinOrExtensionOrEnumMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4632:15)
#37     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4249:15)
#38     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2685:13)
#39     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2643:14)
#40     Parser._handleModifiersForClassDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:823:12)
#41     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:663:14)
#42     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:611:14)
#43     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:414:15)
#44     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1277:16)
<asynchronous suspension>
#45     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:672:7)
<asynchronous suspension>
#46     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:609:7)
<asynchronous suspension>
#47     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#48     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:590:12)
<asynchronous suspension>
#49     _buildInternal (package:front_end/src/kernel_generator_impl.dart:208:19)
<asynchronous suspension>
#50     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#51     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:49:12)
<asynchronous suspension>
#52     generateKernel (package:front_end/src/kernel_generator_impl.dart:48:10)
<asynchronous suspension>
#53     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#54     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:407:11)
<asynchronous suspension>
#55     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:215:45)
<asynchronous suspension>
#56     _processLoadRequest (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:889:37)
<asynchronous suspension>

Crash when compiling file:///Users/kevmoo/github/dart_frog/packages/dart_frog/lib/src/response.dart at character offset 2707:
Crash when compiling file:///Users/kevmoo/github/dart_frog/packages/dart_frog/lib/src/_internal.dart at character offset 2773:
RangeError (offset): Invalid value: Not in inclusive range 0..560: 2773


#0      format (package:front_end/src/fasta/command_line_reporting.dart:113:5)
#1      CompilerContext.format (package:front_end/src/fasta/compiler_context.dart:79:35)
#2      internalProblem (package:front_end/src/fasta/problems.dart:53:10)
#3      unhandled (package:front_end/src/fasta/problems.dart:71:10)
#4      InferenceVisitorBase._findDirectInlineTypeMember (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1062:13)
#5      _ObjectAccessDescriptor._findNonExtensionTargetInternal (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:4818:44)
#6      _ObjectAccessDescriptor.findNonExtensionTarget (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:4763:12)
#7      InferenceVisitorBase.findInterfaceMember (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1367:32)
#8      InferenceVisitorImpl._computePropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:6702:20)
#9      InferenceVisitorImpl.visitPropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:7716:61)
#10     PropertyGet.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:3252:20)
#11     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:258:27)
#12     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:295:40)
#13     InferenceVisitorBase._inferInvocation.inferArgument (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1904:22)
#14     InferenceVisitorBase._inferInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1968:44)
#15     InferenceVisitorBase.inferInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1658:12)
#16     InferenceVisitorImpl.visitStaticInvocation (package:front_end/src/fasta/type_inference/inference_visitor.dart:8111:40)
#17     StaticInvocation.accept1 (package:kernel/ast.dart:7050:9)
#18     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:260:27)
#19     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:295:40)
#20     InferenceVisitorImpl.visitReturnStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:7938:11)
#21     ReturnStatement.accept (package:kernel/ast.dart:10829:43)
#22     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:238:26)
#23     InferenceVisitorImpl._visitStatements (package:front_end/src/fasta/type_inference/inference_visitor.dart:848:50)
#24     InferenceVisitorImpl.visitBlock (package:front_end/src/fasta/type_inference/inference_visitor.dart:869:31)
#25     Block.accept (package:kernel/ast.dart:9788:43)
#26     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:238:26)
#27     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:202:17)
#28     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1263:43)
#29     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1137:19)
#30     DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:765:5)
#31     DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:705:5)
#32     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4915:20)
#33     Parser.parseClassOrMixinOrExtensionOrEnumMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4632:15)
#34     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4249:15)
#35     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2685:13)
#36     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2643:14)
#37     Parser._handleModifiersForClassDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:823:12)
#38     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:663:14)
#39     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:611:14)
#40     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:414:15)
#41     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1277:16)
<asynchronous suspension>
#42     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:672:7)
<asynchronous suspension>
#43     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:609:7)
<asynchronous suspension>
#44     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#45     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:590:12)
<asynchronous suspension>
#46     _buildInternal (package:front_end/src/kernel_generator_impl.dart:208:19)
<asynchronous suspension>
#47     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#48     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:49:12)
<asynchronous suspension>
#49     generateKernel (package:front_end/src/kernel_generator_impl.dart:48:10)
<asynchronous suspension>
#50     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#51     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:407:11)
<asynchronous suspension>
#52     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:215:45)
<asynchronous suspension>
#53     _processLoadRequest (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:889:37)
<asynchronous suspension>
```

**Comment by johnniwinther** [comment]
@kevmoo It is new failure, so yes, create a new issue.
