### ISSUE TITLE
CL 285761 exposes crash in vm/dart/isolates/concurrency_stress_sanity_test

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51553]
I'm working on enabling the patterns and records experiments. [This CL](https://dart-review.googlesource.com/c/sdk/+/285761) changes a few tests that assumed switch cases are constant contexts (which is no longer true with patterns) into valid tests of the new parenthesized constant pattern syntax.

That test is also being run by the concurrency_stress_sanity_test. It fails because when it compiles all of the tests, it doesn't enable the patterns and records experiments. If I add those flags like:

```dart
    // Compile stress test to kernel.
    final args = [
      '--enable-experiment=patterns,records', // <-- Added.
      '--packages=$packageConfig',
      '--snapshot-kind=kernel',
      '--sound-null-safety',
      '--snapshot=$stressTestDill',
      stressTest
    ];
```

Then the compiler crashes:

```
Null check operator used on a null value
#0      BinaryPrinter.visitContinueSwitchStatement (package:kernel/binary/ast_to_binary.dart:2322:35)
#1      ContinueSwitchStatement.accept (package:kernel/ast.dart:10659:43)
#2      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#3      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#4      BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#5      Block.accept (package:kernel/ast.dart:9759:43)
#6      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#7      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#8      BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#9      Block.accept (package:kernel/ast.dart:9759:43)
#10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#11     BinaryPrinter.visitIfStatement (package:kernel/binary/ast_to_binary.dart:2330:5)
#12     IfStatement.accept (package:kernel/ast.dart:10699:43)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#14     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#15     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#16     Block.accept (package:kernel/ast.dart:9759:43)
#17     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#18     BinaryPrinter.visitLabeledStatement (package:kernel/binary/ast_to_binary.dart:2229:5)
#19     LabeledStatement.accept (package:kernel/ast.dart:9969:43)
#20     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#21     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#22     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#23     Block.accept (package:kernel/ast.dart:9759:43)
#24     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#25     BinaryPrinter.visitIfStatement (package:kernel/binary/ast_to_binary.dart:2330:5)
#26     IfStatement.accept (package:kernel/ast.dart:10699:43)
#27     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#28     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#29     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#30     Block.accept (package:kernel/ast.dart:9759:43)
#31     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#32     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:545:7)
#33     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1559:5)
#34     FunctionNode.accept (package:kernel/ast.dart:4186:38)
#35     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:453:10)
#36     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1388:5)
#37     Procedure.accept (package:kernel/ast.dart:3578:40)
#38     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:474:10)
#39     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:356:7)
#40     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1132:5)
#41     Library.accept (package:kernel/ast.dart:585:38)
#42     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:467:10)
#43     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:780:9)
#44     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:619:7)
#45     Timeline.timeSync (dart:developer/timeline.dart:166:22)
#46     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:600:14)
#47     serializeComponent (file:///Users/rnystrom/dev/dart/sdk/pkg/vm/bin/kernel_service.dart:1036:11)
#48     _processLoadRequest (file:///Users/rnystrom/dev/dart/sdk/pkg/vm/bin/kernel_service.dart:936:13)
```

I'm going to mark this one test as failing so I can land the fixes to the other tests.

**Comment by a-siva** [comment]
//cc @alexmarkov

**Comment by alexmarkov** [comment]
Simpler repro (this test is included into the stress test):
```
out/ReleaseX64/dart --enable-experiment=patterns,records tests/language/nnbd/flow_analysis/write_promoted_value_in_switch_test.dart
```

Reduced example:
```dart
main() {
  switch (0) {
    case 1:
      continue L;
    L:
    default:
  }
}
```

**Comment by alexmarkov** [comment]
For the small example above, front-end produces the following kernel AST:

```
  static method main() → dynamic {
    #L1:
    {
      final core::int #0#0 = 0;
      if(#C1 =={core::num::==}{(core::Object) → core::bool} #0#0) {
        {
          continue #L2;
        }
      }
      else {
      }
    }
  }
```

It looks like label `#L2` is not properly declared.

@johnniwinther

**Comment by aam** [comment]
(should undo https://dart.googlesource.com/sdk/+/1dfe2d889ba3aa5d202f7027c4480a45b81a7ec9 once this is fixed)
