### ISSUE TITLE
[inline class] Crash with `is` check under some circumstances.

### ISSUE THREAD

**Issue by joshualitt** [dart-lang/sdk#51556]
Repro case:
```
import 'dart:js_interop';

void main() {
  JSArray arr = [1.0.toJS, 'foo'.toJS].toJS;
  print(arr is JSArray);
}
```

Instructions:

1. Patch https://dart-review.googlesource.com/c/sdk/+/283742
2. run `dart compile js` on the repro.

Stack:
```
Info: Compiling with sound null safety.
repro.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.0.0-edge.c9f3fcd09eb205734d5a4716d00647237114b0d1), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Crash when compiling file:///usr/local/google/home/joshualitt/a/sdk/repro.dart at character offset 37:
type 'InlineType' is not a subtype of type 'InterfaceType' in type cast

#0      StandardBounds.getNullabilityAwareStandardUpperBoundInternal (package:kernel/src/standard_bounds.dart:880:61)
#1      TypeSchemaStandardBounds.getNullabilityAwareStandardUpperBoundInternal (package:front_end/src/fasta/type_inference/standard_bounds.dart:59:18)
#2      StandardBounds._getNullabilityAwareStandardUpperBound (package:kernel/src/standard_bounds.dart:642:12)
#3      StandardBounds.getStandardUpperBound (package:kernel/src/standard_bounds.dart:629:14)
#4      TypeSchemaEnvironment.addLowerBound (package:front_end/src/fasta/type_inference/type_schema_environment.dart:117:24)
#5      TypeSchemaConstraintGatherer.addLowerBound (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:1113:17)
#6      TypeConstraintGatherer.computeConstraints (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:85:9)
#7      TypeSchemaEnvironment._chooseTypes (package:front_end/src/fasta/type_inference/type_schema_environment.dart:517:18)
#8      TypeSchemaEnvironment.upwardsInfer (package:front_end/src/fasta/type_inference/type_schema_environment.dart:505:7)
#9      InferenceVisitorImpl.visitListLiteral (package:front_end/src/fasta/type_inference/inference_visitor.dart:2578:45)
#10     ListLiteral.accept1 (package:kernel/ast.dart:8692:9)
#11     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:266:27)
#12     InferenceVisitorImpl.inferNullAwareExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:320:40)
#13     InferenceVisitorImpl.visitPropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:7582:9)
#14     PropertyGet.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:3448:20)
#15     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:264:27)
#16     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:301:40)
#17     InferenceVisitorImpl.visitVariableDeclaration (package:front_end/src/fasta/type_inference/inference_visitor.dart:8820:11)
#18     VariableDeclaration.accept (package:kernel/ast.dart:11346:43)
#19     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:244:26)
#20     InferenceVisitorImpl._visitStatements (package:front_end/src/fasta/type_inference/inference_visitor.dart:854:50)
#21     InferenceVisitorImpl.visitBlock (package:front_end/src/fasta/type_inference/inference_visitor.dart:875:31)
#22     Block.accept (package:kernel/ast.dart:9759:43)
#23     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:244:26)
#24     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:196:17)
#25     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1344:43)
#26     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1123:19)
#27     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:376:5)
#28     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3704:14)
#29     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3446:14)
#30     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:608:14)
#31     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:405:15)
#32     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1267:12)
<asynchronous suspension>
#33     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:676:7)
<asynchronous suspension>
#34     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:611:7)
<asynchronous suspension>
#35     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#36     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#37     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#38     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:201:37)
<asynchronous suspension>
#39     compile (package:front_end/src/api_unstable/dart2js.dart:199:36)
<asynchronous suspension>
#40     _loadFromSource (package:compiler/src/phase/load_kernel.dart:299:29)
<asynchronous suspension>
#41     run (package:compiler/src/phase/load_kernel.dart:400:36)
<asynchronous suspension>
#42     Compiler.loadKernel (package:compiler/src/compiler.dart:394:9)
<asynchronous suspension>
#43     Compiler.produceKernel (package:compiler/src/compiler.dart:401:36)
<asynchronous suspension>
#44     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:724:20)
<asynchronous suspension>
#45     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:318:7)
<asynchronous suspension>
#46     Compiler.runInternal (package:compiler/src/compiler.dart:317:5)
<asynchronous suspension>
#47     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:238:11)
<asynchronous suspension>
#48     main (package:compiler/src/dart2js.dart:1449:3)
<asynchronous suspension>
```

**Comment by joshualitt** [comment]
@johnniwinther , I think, but am not positive, that this is somehow related to enabling inline classes in the SDK. I tried to create a more minimal repro of this issue, but I can't seem to repro the issue if I move the JS type hierarchy outside of the SDK. Thoughts?

**Comment by sigmundch** [comment]
@johnniwinther - you mentioned running into trouble reproing this issue in isolation. I was bale to repro it using `fasta` with a standalone file:

**repro.dart**:
```dart
inline class JSAny {
  final Object value;
  JSAny(this.value);
}

inline class JSObject implements JSAny {
  final Object value;
  JSObject(this.value);
}

inline class JSArray implements JSObject {
  final List<JSAny?> value;
  JSArray(this.value);
}

inline class JSExportedDartObject implements JSObject {
  final Object value;
  JSExportedDartObject(this.value);
}

inline class JSNumber implements JSAny {
  final double value;
  JSNumber(this.value);
}


extension ObjectToJSExportedDartObject on Object {
  JSExportedDartObject get toJS => JSExportedDartObject(this);
}
extension ListToJSArray on List<JSAny?> {
  JSArray get toJS => JSArray(this);
}
extension DoubleToJSNumber on double {
  JSNumber get toJS => JSNumber(this);
}


void main() {
  JSArray arr = [1.0.toJS, 'foo'.toJS].toJS;
}
```

The fasta tool shows this error:
```
> fasta compile --dump-ir --enable-experiment=inline-class repro.dart
Unhandled exception:
Crash when compiling file:///path/to/repro.dart at character offset 751:
'package:kernel/src/standard_bounds.dart': Failed assertion: line 869 pos 12: 'type1 is InterfaceType': Expected type1 to be an interface type, got 'InlineType'.

#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      StandardBounds.getNullabilityAwareStandardUpperBoundInternal (package:kernel/src/standard_bounds.dart:869:12)
#3      TypeSchemaStandardBounds.getNullabilityAwareStandardUpperBoundInternal (package:front_end/src/fasta/type_inference/standard_bounds.dart:59:18)
#4      StandardBounds._getNullabilityAwareStandardUpperBound (package:kernel/src/standard_bounds.dart:642:12)
#5      StandardBounds.getStandardUpperBound (package:kernel/src/standard_bounds.dart:629:14)
#6      TypeSchemaEnvironment.addLowerBound (package:front_end/src/fasta/type_inference/type_schema_environment.dart:117:24)
#7      TypeSchemaConstraintGatherer.addLowerBound (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:1113:17)
#8      TypeConstraintGatherer.computeConstraints (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:85:9)
#9      TypeSchemaEnvironment._chooseTypes (package:front_end/src/fasta/type_inference/type_schema_environment.dart:517:18)
#10     TypeSchemaEnvironment.upwardsInfer (package:front_end/src/fasta/type_inference/type_schema_environment.dart:505:7)
#11     InferenceVisitorImpl.visitListLiteral (package:front_end/src/fasta/type_inference/inference_visitor.dart:2519:45)
#12     ListLiteral.accept1 (package:kernel/ast.dart:8704:9)
#13     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:262:27)
#14     InferenceVisitorImpl.inferNullAwareExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:316:40)
#15     InferenceVisitorImpl.visitPropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:7598:9)
#16     PropertyGet.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:3210:20)
#17     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:260:27)
#18     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:297:40)
#19     InferenceVisitorImpl.visitVariableDeclaration (package:front_end/src/fasta/type_inference/inference_visitor.dart:8515:11)
#20     VariableDeclaration.accept (package:kernel/ast.dart:11389:43)
#21     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:240:26)
#22     InferenceVisitorImpl._visitStatements (package:front_end/src/fasta/type_inference/inference_visitor.dart:850:50)
#23     InferenceVisitorImpl.visitBlock (package:front_end/src/fasta/type_inference/inference_visitor.dart:871:31)
#24     Block.accept (package:kernel/ast.dart:9771:43)
#25     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:240:26)
#26     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:196:17)
#27     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1344:43)
#28     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1123:19)
#29     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:376:5)
#30     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3704:14)
#31     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3446:14)
#32     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:608:14)
#33     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:405:15)
#34     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1268:12)
<asynchronous suspension>
#35     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:677:7)
<asynchronous suspension>
#36     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:608:7)
<asynchronous suspension>
#37     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#38     CompileTask.compile (file:///path/to/sdk/pkg/front_end/tool/_fasta/entry_points.dart:455:19)
<asynchronous suspension>
#39     compile.<anonymous closure>.<anonymous closure> (file:///path to/sdk/pkg/front_end/tool/_fasta/entry_points.dart:299:14)
<asynchronous suspension>
#40     compile.<anonymous closure> (file:///path/to/sdk/pkg/front_end/tool/_fasta/entry_points.dart:292:12)
<asynchronous suspension>
#41     runProtectedFromAbort (file:///path/to/sdk/pkg/front_end/tool/_fasta/command_line.dart:412:12)
<asynchronous suspension>
#42     compile (file:///path/to/sdk/pkg/front_end/tool/_fasta/entry_points.dart:291:10)
<asynchronous suspension>
#43     compileEntryPoint (file:///path/to/sdk/pkg/front_end/tool/_fasta/entry_points.dart:96:5)
<asynchronous suspension>

```

I noticed some interesting details here:
* If you remove the elements in the array, it no longer crashes, but the CFE reports an error:
```
repro.dart:39:20: Error: A value of type 'JSExportedDartObject' can't be assigned to a variable of type 'JSArray'.
  JSArray arr = [].toJS;
```

* This leads me to believe the inferred type of the List is `List<Object>` instead of List<JSAny?>. As a result, the CFE matches the `toJS` from Object instead of the one from List<JSAny?>. Adding `<JSAny?>` when creating the array fixes this error, but also fixes the crash on the original example.

@joshualitt - aside from the CFE bug, I wonder if this is a good indicator that trying to match `List<JSAny?>` could be too brittle, as it relies on inference rules doing the right thing. An alterantive would be to match any List. Another option is removing the extension on `Object`, which  may give the illusion that things are working, but you end up with a conversion you didn't expect.

@johnniwinther - also note that removing the toJS from Object in this example still produces a crash.

**Comment by johnniwinther** [comment]
Thanks for the repro @sigmundch !
