### ISSUE TITLE
CFE with records and patterns enabled crashes on language/nnbd/flow_analysis/write_promoted_value_in_switch_error_test

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51623]
With the records and patterns experiments enabled, this test [is crashing the front end](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8787699418492648273/+/u/test_results/new_test_failures__logs_):

```
tests/language/nnbd/flow_analysis/write_promoted_value_in_switch_error_test.dart:20:17: Error: The getter 'isEven' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isEven'.
        print(x.isEven);
                ^^^^^^
tests/language/nnbd/flow_analysis/write_promoted_value_in_switch_error_test.dart:41:17: Error: The getter 'isEven' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isEven'.
        print(x.isEven);
                ^^^^^^

stderr:
Unhandled exception:
  Null check operator used on a null value
#0      BinaryPrinter.visitContinueSwitchStatement (package:kernel/binary/ast_to_binary.dart:2322:35)
#1      ContinueSwitchStatement.accept (package:kernel/ast.dart:10669:43)
#2      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#3      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#4      BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#5      Block.accept (package:kernel/ast.dart:9769:43)
#6      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#7      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#8      BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#9      Block.accept (package:kernel/ast.dart:9769:43)
#10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#11     BinaryPrinter.visitIfStatement (package:kernel/binary/ast_to_binary.dart:2330:5)
#12     IfStatement.accept (package:kernel/ast.dart:10709:43)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#14     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#15     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#16     Block.accept (package:kernel/ast.dart:9769:43)
#17     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#18     BinaryPrinter.visitLabeledStatement (package:kernel/binary/ast_to_binary.dart:2229:5)
#19     LabeledStatement.accept (package:kernel/ast.dart:9979:43)
#20     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#21     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#22     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#23     Block.accept (package:kernel/ast.dart:9769:43)
#24     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#25     BinaryPrinter.visitIfStatement (package:kernel/binary/ast_to_binary.dart:2330:5)
#26     IfStatement.accept (package:kernel/ast.dart:10709:43)
#27     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#28     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#29     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:2196:5)
#30     Block.accept (package:kernel/ast.dart:9769:43)
#31     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#32     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:545:7)
#33     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1559:5)
#34     FunctionNode.accept (package:kernel/ast.dart:4196:38)
#35     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:453:10)
#36     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1388:5)
#37     Procedure.accept (package:kernel/ast.dart:3588:40)
#38     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:474:10)
#39     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:356:7)
#40     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1132:5)
#41     Library.accept (package:kernel/ast.dart:585:38)
#42     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:467:10)
#43     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:780:9)
#44     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:619:7)
#45     Timeline.timeSync (dart:developer/timeline.dart:166:22)
#46     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:600:14)
#47     writeComponentToFile (package:front_end/src/fasta/kernel/utils.dart:96:13)
#48     CompileTask.compile (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:482:13)
<asynchronous suspension>
#49     BatchCompiler.batchCompileImpl (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:241:5)
<asynchronous suspension>
#50     runProtectedFromAbort (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/command_line.dart:412:12)
<asynchronous suspension>
#51     BatchCompiler.run (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:193:13)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n cfe-strong-linux language/nnbd/flow_analysis/write_promoted_value_in_switch_error_test
```

Test language/nnbd/flow_analysis/write_promoted_value_in_switch_test is also crashing in a similar way.

**Comment by johnniwinther** [comment]
Probably related to #51553

**Comment by johnniwinther** [comment]
Fixed
