### ISSUE TITLE
Failures on [vm] Remove tcmalloc and malloc profiler.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#51639]
There are new test failures on [[vm] Remove tcmalloc and malloc profiler.](https://github.com/dart-lang/sdk/commit/c67fac9cb44c2262487728ba4b7874fd5a63614e).

The tests
```
standalone/io/large_file_read_small_file_test RuntimeError (expected Pass)
standalone/io/large_file_read_small_file_test Crash (expected Pass)
standalone_2/io/large_file_read_small_file_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-strong-linux-release-ia32
dartk-strong-linux-release-simarm
dartk-weak-asserts-linux-release-ia32
dartkp-linux-release-simarm
vm-linux-release-arm64
```

It looks like switching allocators caused this.

```
--- Command "vm" (took 11.000410s):
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --sound-null-safety -Dtest_runner.configuration=dartk-strong-linux-release-ia32 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/standalone/io/large_file_read_small_file_test.dart

exit code:
255

stdout:
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000

stderr:
Unhandled exception:
FileSystemException: read failed, path = '/b/s/w/it4ii0w4w8/large_file_readBXEXHS/hello_world.txt' (OS Error: Cannot allocate memory, errno = 12)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _RandomAccessFile.read.<anonymous closure> (dart:io/file_impl.dart:786:7)
<asynchronous suspension>
#2      main.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/large_file_read_small_file_test.dart:41:21)
<asynchronous suspension>
#3      runWithTempDir (file:///b/s/w/ir/tests/standalone/io/large_file_read_small_file_test.dart:13:5)
<asynchronous suspension>
#4      main (file:///b/s/w/ir/tests/standalone/io/large_file_read_small_file_test.dart:25:3)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-strong-linux-release-ia32 standalone/io/large_file_read_small_file_test
```

https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-release-ia32/dartk-strong-linux-release-ia32/807/standalone/io/large_file_read_small_file_test

**Comment by mraleph** [comment]
There is also some amount of Golem benchmarks which got broken and some IO benchmarks which are seeing significant regressions (probably because `dart:io` needs a fast malloc/free for IO buffers).

**Comment by rmacnak-google** [comment]
IOBuffer::Reallocate assumes that `realloc(smaller)` releases the extra backing store, which apparently does not happen here.

**Comment by mkustermann** [comment]
Seems like the tests mentioned here are passing with the re-land of removing tcmalloc.
