### ISSUE TITLE
Dartk crashing when records and patterns are enabled

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51647]
In my [in-progress CL to enable records and patterns](https://dart-review.googlesource.com/c/sdk/+/286344?tab=checks), I'm seeing [a few related crashes on the bots](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8787346541573253121/+/u/test_results/new_test_failures__logs_).

The failing tests are:

```
co19_2/LanguageFeatures/Extension-methods/syntax_t05/05
co19_2/LanguageFeatures/Extension-methods/syntax_t05/06
co19_2/LanguageFeatures/Extension-methods/syntax_t05/07
co19_2/LanguageFeatures/Extension-methods/syntax_t05/08
language_2/syntax/syntax_test/65
```

Skimming the tests, the thing they seem to have in common is an assignment LHS that looks like a function call, as in:

```dart
Ext1("testme") += 14;
```

Here's an example of one of the crashing stack traces:

```
Crash when compiling file:///b/s/w/ir/out/ReleaseX64/generated_tests/co19_2/LanguageFeatures/Extension-methods/syntax_t05_05.dart at character offset 1214:
Bad state: No element

#0      List.last (dart:core-patch/growable_array.dart:348:5)
#1      _LegacyTypePromotion.getMatchedValueType (package:_fe_analyzer_shared/src/flow_analysis/flow_analysis.dart:5649:38)
#2      InferenceVisitorImpl.visitObjectPattern (package:front_end/src/fasta/type_inference/inference_visitor.dart:10399:29)
#3      ObjectPattern.acceptPattern1 (package:front_end/src/fasta/kernel/internal_ast.dart:4054:15)
#4      InferenceVisitorImpl.dispatchPattern (package:front_end/src/fasta/type_inference/inference_visitor.dart:9600:12)
#5      TypeAnalyzer.analyzePatternAssignment (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:1229:5)
#6      InferenceVisitorImpl.visitPatternAssignment (package:front_end/src/fasta/type_inference/inference_visitor.dart:10871:9)
#7      PatternAssignment.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:4249:20)
#8      InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:264:27)
#9      InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:301:40)
#10     InferenceVisitorImpl.visitExpressionStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:1273:40)
#11     ExpressionStatement.accept (package:kernel/ast.dart:9713:43)
#12     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:244:26)
#13     InferenceVisitorImpl._visitStatements (package:front_end/src/fasta/type_inference/inference_visitor.dart:854:50)
#14     InferenceVisitorImpl.visitBlock (package:front_end/src/fasta/type_inference/inference_visitor.dart:875:31)
#15     Block.accept (package:kernel/ast.dart:9769:43)
#16     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:244:26)
#17     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:196:17)
#18     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1344:43)
#19     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1123:19)
#20     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:376:5)
#21     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3704:14)
#22     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3446:14)
#23     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:608:14)
#24     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:405:15)
#25     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1268:12)
<asynchronous suspension>
#26     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:677:7)
<asynchronous suspension>
#27     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:611:7)
<asynchronous suspension>
#28     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#29     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#30     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#31     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#32     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#33     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#34     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:407:11)
<asynchronous suspension>
#35     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:215:45)
<asynchronous suspension>
#36     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:889:37)
<asynchronous suspension>
```

cc @stereotype441

**Comment by johnniwinther** [comment]
These have all been fixed now.
