### ISSUE TITLE
dart ffi: error code 126

### ISSUE THREAD

**Issue by brizaldi** [dart-lang/sdk#51659]
Hi, I got an error like this when trying to use ffi to load the librdkafka library.
```
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'C:\Projects\Dart\ffi_demo\library\librdkafka.dll': error code 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      main (file:///C:/Projects/Dart/ffi_demo\/bin/main.dart:26:36)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

I obtained the librdkafka.dll file from NuGet.
https://www.nuget.org/packages/librdkafka.redist/

and here's my code:
```dart
import 'dart:ffi' as ffi;
import 'dart:io' show Platform, Directory;

import 'package:path/path.dart' as path;

void main() {
  final libraryPath = path.join(Directory.current.path, 'library', 'librdkafka.dll');
  final dylib = ffi.DynamicLibrary.open(libraryPath);
}
```

Dart SDK version: 2.19.3
OS: Windows 11 22H2 build 22621.1344

**Comment by brizaldi** [comment]
I have checked some of the dependencies required by librdkafka.dll using [this tool](https://github.com/lucasg/Dependencies):
- KERNEL32.dll
- libcrypto-3-x64.dll
- libcurl.dll
- libssl-3-x64.dll
- zlib1.dll
- zstd.dll
- Secur32.dll
- WS2_32.dll
- CRYPT32.dll

And I have put all of them into one folder along with librdkafka.dll. However, I am still getting the same error.

**Comment by dcharkes** [comment]
Similar issue:

* https://github.com/flutter/flutter/issues/58079

Can you check whether the file exists with `File.existsSync()` just to be sure the path-handling (separators etc) is correct?

> I have checked some of the dependencies required by librdkafka.dll using [this tool](https://github.com/lucasg/Dependencies):
> 
> * KERNEL32.dll
> * libcrypto-3-x64.dll
> * libcurl.dll
> * libssl-3-x64.dll
> * zlib1.dll
> * zstd.dll
> * Secur32.dll
> * WS2_32.dll
> * CRYPT32.dll
> 
> And I have put all of them into one folder along with librdkafka.dll. However, I am still getting the same error.

And this would indeed my second suggestion.

Did you get it to work?

**Comment by brizaldi** [comment]
> Can you check whether the file exists with `File.existsSync()` just to be sure the path-handling (separators etc) is correct?

The path is correct since `File.existsSync()` returns `true`

> Did you get it to work?

No, currently still stuck at loading the librdkafka library

**Comment by dcharkes** [comment]
You could try running `dart.exe` with the right arguments in the visual studio debugger.

**Comment by brizaldi** [comment]
I can load other DLLs fine, for example like the hello.dll from the official example or the libcurl.dll from above. However, when I try to load this librdkafka.dll, an error occurs.

**Comment by Levi-Lesches** [comment]
I'm having the same issue when compiling `OpenCV`. 

I'm able to use `WSL` to compile OpenCV to a `.so` library, run `dart run ffigen` to generate bindings and everything works in Dart. This however, isn't ideal since WSL cannot access USB devices or webcams, which means I can't actually stream any video.

So I tried the process again on Windows. I used Visual Studio to generate a whole bunch of `.dll`s with `cmake .` in `opencv\build\bin\Debug`, but when I load one, Dart gives an error 126. This error does not occur when building other, simpler C projects on Windows.

**Comment by rinith** [comment]
You had to add the folder which contain all dll's to system environment variables path??

**Comment by rinith** [comment]
> I'm having the same issue when compiling `OpenCV`.
> 
> I can use `WSL` to compile OpenCV to a `.so` library, run `dart run ffigen` to generate bindings and everything works in Dart. This, however, isn't ideal since WSL cannot access USB devices or webcams, which means I can't actually stream any video.
> 
> So I tried the process again on Windows. I used Visual Studio to generate a whole bunch of `.dll`s with `cmake .` in `opencv\build\bin\Debug`, but Dart gives an error 126 when I load one. This error does not occur when building other, simpler C projects on Windows.
> 
> I'm happy to provide more details if needed.
> 
> **EDIT**: I seemed to have fixed it by adding the folder with all the DLL's to my system path. I thought that wouldn't be needed since they were in the same folder together but since my terminal isn't in that folder, it didn't matter.

You had to add the folder which contain all dll's to system environment variables path??

**Comment by Levi-Lesches** [comment]
I believe so.

In Linux, there is an environment variable called [`LD_LIBRARY_PATH`](https://stackoverflow.com/questions/7148036/what-is-ld-library-path-and-how-to-use-it), which allows Linux to find `.so` files when they are linked at runtime. It's like the normal `PATH` variable on Windows, but exclusively for linked libraries. 

Windows doesn't have another path variable like this (or at least, I didn't try one), so adding it to the system/user `PATH` is good enough. Of course, if your terminal is already in this folder, you don't need to add it, but in some cases you do: 
```
myProject/
- bin/
  - project.exe
  - library.dll
```
If your terminal is in `myProject`, and you run `bin\project.exe`, then `library.dll` is not in your `PATH` _or_ the current working directory (that would be `myProject`), so you need to add it to your `PATH`. 

The way I get around it is by assuming my terminal is in `myProject` and making the code reference the `.dll` from there, so `DynamicLibrary.open("bin/library.dll")`. I also generate my `.dll`s in the root folder sometimes, when that's more convenient.

**Comment by 724898928** [comment]
我也遇到了同样的问题,package:media_kit_libs_windows_video registered.
flutter: The Dart VM service is listening on http://127.0.0.1:64215/L7pBwHnMVho=/
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'rust_lib_pv_player_new.dll': The specified module could not be found.
 (error code: 126)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      new ExternalLibrary.open (package:flutter_rust_bridge/src/platform_types/_io.dart:42:47)
#3      loadExternalLibraryRaw.<anonymous closure> (package:flutter_rust_bridge/src/loader/_io.dart:62:46)
#4      loadExternalLibraryRaw.tryAssumingNonPackaged (package:flutter_rust_bridge/src/loader/_io.dart:49:22)
#5      loadExternalLibraryRaw (package:flutter_rust_bridge/src/loader/_io.dart:61:12)
#6      loadExternalLibrary (package:flutter_rust_bridge/src/loader/_io.dart:14:10)
#7      BaseEntrypoint._loadDefaultExternalLibrary (package:flutter_rust_bridge/src/main_components/entrypoint.dart:141:13)
#8      BaseEntrypoint.initImpl (package:flutter_rust_bridge/src/main_components/entrypoint.dart:48:31)
#9      RustLib.init (package:pv_player_new/src/rust/frb_generated.dart:28:20)
#10     main (package:pv_player_new/main.dart:15:17)
<asynchronous suspension>

**Comment by 724898928** [comment]
> 我也遇到了同样的问题,package:media_kit_libs_windows_video registered. flutter: The Dart VM service is listening on http://127.0.0.1:64215/L7pBwHnMVho=/ [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'rust_lib_pv_player_new.dll': The specified module could not be found.  (error code: 126) #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43) #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12) #2      new ExternalLibrary.open (package:flutter_rust_bridge/src/platform_types/_io.dart:42:47) #3      loadExternalLibraryRaw. (package:flutter_rust_bridge/src/loader/_io.dart:62:46) #4      loadExternalLibraryRaw.tryAssumingNonPackaged (package:flutter_rust_bridge/src/loader/_io.dart:49:22) #5      loadExternalLibraryRaw (package:flutter_rust_bridge/src/loader/_io.dart:61:12) #6      loadExternalLibrary (package:flutter_rust_bridge/src/loader/_io.dart:14:10) #7      BaseEntrypoint._loadDefaultExternalLibrary (package:flutter_rust_bridge/src/main_components/entrypoint.dart:141:13) #8      BaseEntrypoint.initImpl (package:flutter_rust_bridge/src/main_components/entrypoint.dart:48:31) #9      RustLib.init (package:pv_player_new/src/rust/frb_generated.dart:28:20) #10     main (package:pv_player_new/main.dart:15:17)

I have solved the problem that flutter compiles without copying dependency packages in the environment to its own directory

**Comment by lihe6666** [comment]
same problem!
