### ISSUE TITLE
Crash compiling web/regress/issue/230108748_test

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51676]
This test has syntax (a conditional expression inside a switch case) that is invalid in Dart 3.

I'm not sure what the intent is, but we'll either want to pin it to 2.19 and keep it as-is, or fix it to be a valid pattern (or both).

But right now, it's [*crashing* the compiler](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8787157786924699569/+/u/test_results/new_test_failures__logs_):

```
/=======================================================================\
| web/regress/issue/230108748_test broke (Pass -> Crash, expected Pass) |
\=======================================================================/

--- Command "ddc" (took 215ms):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/dart-sdk/bin/snapshots/dartdevc.dart.snapshot -Da=true -Db=false -Dtest_runner.configuration=ddc-linux-chrome --sound-null-safety -Dtest_runner.configuration=ddc-linux-chrome --ignore-unrecognized-flags --no-summarize -o /b/s/w/ir/out/ReleaseX64/generated_compilations/ddc-linux-chrome/tests_web_regress_issue_230108748_test/230108748_test.js /b/s/w/ir/tests/web/regress/issue/230108748_test.dart -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/async_helper.dill=async_helper -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/expect.dill=expect -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/js.dill=js -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/meta.dill=meta

exit code:
253

stdout:
org-dartlang-app:/tests/web/regress/issue/230108748_test.dart:53:46: Error: Expected ',' before this.
    case B(const bool.fromEnvironment('x') ? 0 : 1):
                                             ^
org-dartlang-app:/tests/web/regress/issue/230108748_test.dart:53:46: Error: Expected an identifier, but got '0'.
Try inserting an identifier before '0'.
    case B(const bool.fromEnvironment('x') ? 0 : 1):
                                             ^
Unhandled exception:
Crash when compiling org-dartlang-app:/tests/web/regress/issue/230108748_test.dart at character offset 1020:
type 'ParserRecovery' is not a subtype of type 'Identifier?' in type cast

#0      BodyBuilder.handlePatternField (package:front_end/src/fasta/kernel/body_builder.dart:9332:38)
#1      Parser.parseObjectPatternRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:10123:16)
#2      Parser.parsePrimaryPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9796:17)
#3      Parser.parsePattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9594:13)
#4      Parser.parseSwitchBlock (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8721:21)
#5      Parser.parseSwitchStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8670:13)
#6      Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5388:14)
#7      Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5337:20)
#8      Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5242:15)
#9      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1120:14)
#10     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:376:5)
#11     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3704:14)
#12     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3446:14)
#13     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:608:14)
#14     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:405:15)
#15     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1268:12)
<asynchronous suspension>
#16     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:677:7)
<asynchronous suspension>
#17     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:611:7)
<asynchronous suspension>
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#19     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#20     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#21     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#22     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#23     compile (package:front_end/src/api_unstable/ddc.dart:217:7)
<asynchronous suspension>
#24     _compile (package:dev_compiler/src/kernel/command.dart:292:14)
<asynchronous suspension>
#25     _BatchHelper._doIteration (package:dev_compiler/ddc.dart:134:16)
<asynchronous suspension>
#26     _BatchHelper._runBatch (package:dev_compiler/ddc.dart:120:7)
<asynchronous suspension>
#27     internalMain (package:dev_compiler/ddc.dart:36:5)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n ddc-linux-chrome web/regress/issue/230108748_test
```

**Comment by sigmundch** [comment]
I believe this is likely same root cause as #51625 - cc @johnniwinther

**Comment by sigmundch** [comment]
Sorry - to be clear - there is a parsing issue here overall, I'm not familiarized enough with all the pattern changes to know whether this is an error in Dart 3 or not. That said, using language version to opt-out the library doesn't revert to the old behavior. The latter is what I believe to be due to the same cause.

**Comment by itsjustkevin** [comment]
@sigmundch and @johnniwinther are we still seeing this issue?
