### ISSUE TITLE
error code 193

### ISSUE THREAD

**Issue by sychen12345** [dart-lang/sdk#51736]
Invalid argument(s): Failed to load dynamic library "ffigen\example\c_json\build\Debug\libcurl.dll"  error code 193

#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      main (file:///C:/Users/chensy/Desktop/new/ffigen/example/c_json/main.dart:20:36)      
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

dart --version 
Dart SDK version: 2.19.3 (stable) (Tue Feb 28 15:52:19 2023 +0000) on "windows_x64"

libcurl 64

**Comment by sychen12345** [comment]
// my code

void main(List<String> args) {
  var libraryPath = path.join(Directory.current.path, 'build', 'example.so');

  if (Platform.isMacOS) {
    libraryPath = path.join(Directory.current.path, 'build', 'example.dylib');
  }

  if (Platform.isWindows) {
    libraryPath =
        path.join(Directory.current.path, 'build', 'Debug', 'libcurl.dll');
  }
  final dylib = ffi.DynamicLibrary.open(libraryPath);
  



  
}

**Comment by sychen12345** [comment]
C:\Users\chensy\Desktop\new\ffigen\example\c_json> dart run .\main.dart
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'C:\Users\chensy\Desktop\new\ffigen\example\c_json\build\Debug\libcurl.dll': error code 193
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      main (file:///C:/Users/chensy/Desktop/new/ffigen/example/c_json/main.dart:20:36)      
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
PS C:\Users\chensy\Desktop\new\ffigen\example\c_json>

**Comment by sychen12345** [comment]
Oh my God! My problem has been found, it may be that I downloaded libcurl-64 from the Internet is not compatible with the problem, I manually compile the line
