### ISSUE TITLE
[front-end] Error in `front-end-linux-release-try-x64` when trying to add inline classes to the SDK.

### ISSUE THREAD

**Issue by joshualitt** [dart-lang/sdk#51743]
When trying to add inline classes to the SDK(https://dart-review.googlesource.com/c/sdk/+/283742), we see an error in the try bots:

```
Invalid argument(s): Unexpected named node InlineClass(JSAny) (InlineClass)
#0      new ReferenceName.fromNamedNode (package:kernel/src/equivalence_helpers.dart:324:7)
#1      EquivalenceVisitor.matchNamedNodes (package:kernel/src/equivalence.dart:1184:13)
#2      EquivalenceStrategy.checkInlineClass (package:kernel/src/equivalence.dart:1870:18)
#3      EquivalenceVisitor.visitInlineClass (package:kernel/src/equivalence.dart:60:21)
#4      InlineClass.accept1 (package:kernel/ast.dart:2083:53)
#5      EquivalenceVisitor._checkNodes (package:kernel/src/equivalence.dart:1143:16)
#6      EquivalenceVisitor.checkNodes (package:kernel/src/equivalence.dart:1151:19)
#7      EquivalenceVisitor.checkLists (package:kernel/src/equivalence.dart:1331:28)
#8      EquivalenceStrategy.checkLibrary_inlineClasses (package:kernel/src/equivalence.dart:5820:20)
#9      EquivalenceStrategy.checkLibrary (package:kernel/src/equivalence.dart:1622:10)
#10     EquivalenceVisitor.visitLibrary (package:kernel/src/equivalence.dart:40:21)
#11     Library.accept1 (package:kernel/ast.dart:590:53)
#12     EquivalenceVisitor._checkNodes (package:kernel/src/equivalence.dart:1143:16)
#13     EquivalenceVisitor.checkNodes (package:kernel/src/equivalence.dart:1151:19)
#14     EquivalenceVisitor.checkLists (package:kernel/src/equivalence.dart:1331:28)
#15     EquivalenceStrategy.checkComponent_libraries (package:kernel/src/equivalence.dart:8617:20)
#16     EquivalenceStrategy.checkComponent (package:kernel/src/equivalence.dart:4515:10)
#17     EquivalenceVisitor.visitComponent (package:kernel/src/equivalence.dart:651:21)
#18     Component.accept1 (package:kernel/ast.dart:15047:53)
#19     EquivalenceVisitor._checkNodes (package:kernel/src/equivalence.dart:1143:16)
#20     EquivalenceVisitor.checkNodes (package:kernel/src/equivalence.dart:1151:19)
#21     checkEquivalence (package:kernel/src/equivalence.dart:1557:11)
#22     canRead (file:///b/s/w/ir/pkg/kernel/test/equivalent_dill_test.dart:96:32)
#23     main (file:///b/s/w/ir/pkg/kernel/test/equivalent_dill_test.dart:70:10)
#24     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#25     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

FYI @johnniwinther

**Comment by johnniwinther** [comment]
This seems to be working now (see https://dart-review.googlesource.com/c/sdk/+/305260)
