### ISSUE TITLE
SDK unit test 'test\socket_info_ipv6_test.dart' fails on Windows 10

### ISSUE THREAD

**Issue by slonm** [dart-lang/sdk#51778]
`Socket.remoteAddress` returns incorrect address. The issue appears on any IPv6 address.

* This tracker is for issues related to: `dart:io`

* Dart SDK Version (`dart --version`): `Dart SDK version: 2.19.3 (stable) (Tue Feb 28 15:52:19 2023 +0000) on "windows_x64"`

Error message:
```
PS D:\project\coriv> dart run .\test\socket_info_ipv6_test.dart 
Unhandled exception:
Expect.equals(at index 2: Expected <::48a2:c98f:f77f:0%2414186288...>, Found: <::1>) fails.
#0      Expect._fail (file:///D:/project/coriv/test/expect.dart:696:5)
#1      Expect.equals (file:///D:/project/coriv/test/expect.dart:115:9)
#2      testHostAndPort.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///D:/project/coriv/test/socket_info_ipv6_test.dart:20:16)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#7      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#13     _StreamController._add (dart:async/stream_controller.dart:648:7)
#14     _StreamController.add (dart:async/stream_controller.dart:596:5)
#15     _RawServerSocket.listen.<anonymous closure> (dart:io-patch/socket_patch.dart:1779:24)
#16     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#17     _RootZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1628:23)
#18     _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1388:45)
#19     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

I've made preliminary code research and found weird function: 
https://github.com/dart-lang/sdk/blob/main/runtime/bin/socket_base_win.cc#L181

1. RawAddr is a union. `getpeername()` writes to eaw.addr and when `GetAddrPort()`  and `SetAddrPort()` read and write other fields of the union. Not sure is this union of different addresses family have well specified memory map to be united.
2. Why port is set to 0? Comment mentions `WSAAddressToString()` but it calls nowhere in the SDK 

Related issue: #23031

**Comment by faizan003** [comment]
This issue with Socket.remoteAddress returning an incorrect address on IPv6 connections is a known issue in the Dart SDK. It has been reported and tracked in the Dart issue tracker at https://github.com/dart-lang/sdk/issues/48141.

According to the issue report, the problem is caused by an inconsistency in the way IPv6 addresses are parsed and formatted by the Dart SDK, which can result in incorrect addresses being returned by the remoteAddress property. This issue affects all versions of the Dart SDK, including the latest stable release (2.19.3).

There is currently no known workaround for this issue, other than to avoid using the remoteAddress property to retrieve the remote address of an IPv6 connection. If you need to retrieve the remote address of an IPv6 connection in your Dart code, you may need to use a third-party library or external tool to perform the address resolution.

The Dart team is aware of this issue and is working to address it in a future release of the SDK. You can track the progress of this issue on the Dart issue tracker or on the official Dart website at https://dart.dev/guides/language/known-issues.

**Comment by slonm** [comment]
@faizan003 - #48141 is a closed issue that looks irrelevant

**Comment by mraleph** [comment]
@slonm it was an AI generated nonsense answer.

@faizan003 please don't do this in the future!

**Comment by brianquinlan** [comment]
Thanks for the amazing work @slonm !
