### ISSUE TITLE
[analyzer] Trying to use a record and cast pattern in 2.9 code results in "Bad state: Expected all legacy types, but got ..."

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51807]
I tried to add this code as a test case in `InvalidUseOfInternalMemberTest`, not realizing these test cases are _all_ using Dart 2.9 ( 🤨 ):

```dart
// lib/src/a.dart:
import 'package:meta/meta.dart';
@internal
class A {}

// testFile:
void f(Object a, Object b) {
  (b as A, ) = (a, );
}
```

and got this error:

```
  Bad state: Expected all legacy types, but got (Object*) (RecordTypeImpl)
  #0      LegacyTypeAsserter._assertLegacyType (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:163:5)
  #1      LegacyTypeAsserter.visitExpression (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:75:5)
  #2      GeneralizingAstVisitor.visitAssignmentExpression (package:analyzer/dart/ast/visitor.dart:158:7)
  #3      LegacyTypeAsserter.visitAssignmentExpression (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:48:11)
  #4      AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:810:15)
  #5      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4625:17)
  #6      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:526:10)
  #7      GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:662:40)
  #8      GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:310:60)
  #9      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4621:50)
  #10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9625:20)
  #11     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1260:17)
  #12     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:526:10)
  #13     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:662:40)
  #14     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:171:32)
  #15     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1256:50)
  #16     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1211:12)
  #17     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:526:10)
  #18     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:367:46)
  #19     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:174:56)
  #20     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1203:50)
  #21     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6121:11)
  #22     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:526:10)
  #23     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:206:56)
  #24     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:303:42)
  #25     LegacyTypeAsserter.visitExpression (package:analyzer/src/dart/resolver/legacy_type_asserter.dart:77:11)
  #26     GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:382:58)
```

CC @scheglov

**Comment by scheglov** [comment]
For the `records` feature legacy Dart, before null safety, does not exist.
So, we probably don't have to support legacy record types.
But we probably don't need to run these tests with the language `2.9`.

**Comment by srawlins** [comment]
I'm bumping the language version of those tests.

**Comment by srawlins** [comment]
Which part is assigned to me?  😄  I think the language version in the tests is orthogonal, but "Bad state: Expected all legacy types, but got (Object*)" should be fixed right? We should produce a better error message?

**Comment by scheglov** [comment]
With language versions fixed, it will not crash anymore :-)

This is an assert that fails, intended to prevent accidental using null safe types in legacy.
We don't run these asserts in production.
So, I think we don't have to fix them.
Record types cannot by used together with legacy.

So, I think there is nothing more to fix.

**Comment by srawlins** [comment]
Ah I see. No worries. Done.
