### ISSUE TITLE
Failing `co19/LibTest/ffi/Array/IntPtrArray_A01_t01` on `vm-linux-debug-ia32`

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#51841]
From [this log](https://dart-ci.appspot.com/log/vm-linux-debug-ia32/vm-linux-debug-ia32/8/co19/LibTest/ffi/Array/IntPtrArray_A01_t01):
```
--- Command "vm" (took 10.000771s):
DART_CONFIGURATION=DebugIA32 out/DebugIA32/dart --sound-null-safety -Dtest_runner.configuration=vm-linux-debug-ia32 --enable-experiment=class-modifiers --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/co19/src/LibTest/ffi/Array/IntPtrArray_A01_t01.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <-32768>, actual: <32768>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:18:5)
#1      Expect.equals (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:16:7)
#2      main (file:///b/s/w/ir/tests/co19/src/LibTest/ffi/Array/IntPtrArray_A01_t01.dart:54:16)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

--- Re-run this test:
python3 tools/test.py -n vm-linux-debug-ia32 co19/LibTest/ffi/Array/IntPtrArray_A01_t01
```

**Comment by dcharkes** [comment]
Fails on all ia32 bots, https://dart-ci.firebaseapp.com/current_results/#/filter=co19/LibTest/ffi/Array/IntPtrArray_A01_t01
It's not run on any arm (32 bit) bots.

The test is broken, it is testing integers around 16 bit integers:

```dart
      if (sizeOf<IntPtr>() == 4) {
        array[i] = 32768;
        Expect.equals(-32768, array[i]);
        array[i] = -32768;
        Expect.equals(-32768, array[i]);
        array[i] = -32769;
        Expect.equals(32767, array[i]);
```

but the array under test is 32 bit (on 32 bit platforms)

```dart
final class MyStruct extends Struct {
  @Array(2)
  external Array<IntPtr> a0;
}
```

@sgrekhov

**Comment by sgrekhov** [comment]
Fixed by https://github.com/dart-lang/co19/commit/10710b0fbea88ad50cc70cb27ec7e8c1272e2627
