### ISSUE TITLE
"fatal: detected dubious ownership in repository" on Debian package builder

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51865]
With https://dart-review.googlesource.com/c/sdk/+/291050, a Git error was no longer ignored and turned the Debian package builder red:

```
++ which fetch
+ fetch=/b/s/w/ir/kitchen-checkout/depot_tools/fetch
++ dirname /b/s/w/ir/kitchen-checkout/depot_tools/fetch
+ depot_tools=/b/s/w/ir/kitchen-checkout/depot_tools
+ image=debian-package:0.1
+ dockerfile=tools/linux_dist_support/Debian.dockerfile
+ docker build --build-arg depot_tools=/b/s/w/ir/kitchen-checkout/depot_tools -t debian-package:0.1 -
#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.1s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 534B done
#2 DONE 0.1s

#3 [internal] load metadata for launcher.gcr.io/google/debian11:latest
#3 DONE 0.3s

#4 [1/2] FROM launcher.gcr.io/google/debian11:latest@sha256:5379cc9c6604575e7d7b2272dfb2390bfe63fc116524d26b0afc9901d07ce1d3
#4 DONE 0.0s

#5 [2/2] RUN apt-get update   && apt-get install -y build-essential debhelper git python3   && rm -rf /var/lib/apt/lists/*
#5 CACHED

#6 exporting to image
#6 exporting layers done
#6 writing image sha256:99313e64921ab29e0af17a1d98345f030bcbee3d9aa956c4cea96b6015683cee done
#6 naming to docker.io/library/debian-package:0.1 done
#6 DONE 0.0s
++ pwd
+ checkout=/b/s/w/ir/cache/builder/sdk
+ docker run -e BUILDBOT_BUILDERNAME -v /b/s/w/ir/kitchen-checkout/depot_tools:/b/s/w/ir/kitchen-checkout/depot_tools -v /b/s/w/ir/cache/builder/sdk:/b/s/w/ir/cache/builder/sdk -w /b/s/w/ir/cache/builder/sdk -i --rm debian-package:0.1
Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/sdk/tools/linux_dist_support/linux_distribution_support.py", line 131, in <module>
    SrcSteps()
  File "/b/s/w/ir/cache/builder/sdk/tools/linux_dist_support/linux_distribution_support.py", line 68, in SrcSteps
    version = utils.GetVersion()
  File "/b/s/w/ir/cache/builder/sdk/tools/utils.py", line 408, in GetVersion
    return GetSemanticSDKVersion(no_git_hash, version_file, git_revision_file)
  File "/b/s/w/ir/cache/builder/sdk/tools/utils.py", line 396, in GetSemanticSDKVersion
    GetGitRevision(git_revision_file))
  File "/b/s/w/ir/cache/builder/sdk/tools/utils.py", line 508, in GetGitRevision
    raise Exception('git rev-parse failed: ' + str(err))
Exception: git rev-parse failed: b"fatal: detected dubious ownership in repository at '/b/s/w/ir/cache/builder/sdk'\nTo add an exception for this directory, call:\n\n\tgit config --global --add safe.directory /b/s/w/ir/cache/builder/sdk\n"
```

**Comment by rmacnak-google** [comment]
The Debian package building process was re-written.
