### ISSUE TITLE
Failures on Add `nonNulls` and `indexed` extensions on iterables.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#51904]
There are failures on [Add `nonNulls` and `indexed` extensions on iterables.](https://dart-review.googlesource.com/c/sdk/+/290760) when running smoke-tests on the monorepo-roller-try bot.

It gave the following error:
```
Unhandled exception:
Unsupported operation: Unknown DartType: RecordType((Object?, Object?)) Encountered while compiling lib/internal/internal.dart, which contains the type: RecordType((Object?, Object?)).
#0      ProgramCompiler._typeCompilationError (package:[dev_compiler/src/kernel/compiler.dart:3355
#1      ProgramCompiler._newEmitType (package:[dev_compiler/src/kernel/compiler.dart:3156
#2      ProgramCompiler._emitType (package:[dev_compiler/src/kernel/compiler.dart:3076
#3      ProgramCompiler._emitIsExpression (package:[dev_compiler/src/kernel/compiler.dart:6693
#4      ProgramCompiler.visitIsExpression (package:[dev_compiler/src/kernel/compiler.dart:6671
#5      IsExpression.accept (package:[kernel/ast.dart:8012
#6      ProgramCompiler._visitExpression (package:[dev_compiler/src/kernel/compiler.dart:4232
#7      ProgramCompiler._visitTest (package:[dev_compiler/src/kernel/compiler.dart:4223
#8      ProgramCompiler._visitTest.shortCircuit (package:[dev_compiler/src/kernel/compiler.dart:4209
#9      ProgramCompiler._visitTest (package:[dev_compiler/src/kernel/compiler.dart:4213
#10     ProgramCompiler._visitTest.shortCircuit (package:[dev_compiler/src/kernel/compiler.dart:4209
#11     ProgramCompiler._visitTest (package:[dev_compiler/src/kernel/compiler.dart:4213
#12     ProgramCompiler._visitTest.shortCircuit (package:[dev_compiler/src/kernel/compiler.dart:4209
#13     ProgramCompiler._visitTest (package:[dev_compiler/src/kernel/compiler.dart:4213
#14     ProgramCompiler.visitIfStatement (package:[dev_compiler/src/kernel/compiler.dart:4747
#15     IfStatement.accept (package:[kernel/ast.dart:10711
#16     ProgramCompiler._visitStatement (package:[dev_compiler/src/kernel/compiler.dart:4141
#17     MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#18     ListIterator.moveNext (dart:_internal/iterable.dart:344)
#19     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#20     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#21     new List.of (dart:core-patch/array_patch.dart:47)
#22     ListIterable.toList (dart:_internal/iterable.dart:214)
#23     ProgramCompiler.visitBlock (package:[dev_compiler/src/kernel/compiler.dart:4326
#24     Block.accept (package:[kernel/ast.dart:9771
#25     ProgramCompiler._visitStatement (package:[dev_compiler/src/kernel/compiler.dart:4141
#26     MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#27     ListIterator.moveNext (dart:_internal/iterable.dart:344)
#28     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#29     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#30     new List.of (dart:core-patch/array_patch.dart:47)
#31     ListIterable.toList (dart:_internal/iterable.dart:214)
#32     ProgramCompiler.visitBlock (package:[dev_compiler/src/kernel/compiler.dart:4326
#33     Block.accept (package:[kernel/ast.dart:9771
#34     ProgramCompiler._visitStatement (package:[dev_compiler/src/kernel/compiler.dart:4141
#35     ProgramCompiler._emitFunctionScopedBody (package:[dev_compiler/src/kernel/compiler.dart:4174
#36     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:[dev_compiler/src/kernel/compiler.dart:3909
#37     ProgramCompiler._withLetScope (package:[dev_compiler/src/kernel/compiler.dart:2593
#38     ProgramCompiler._withCurrentFunction (package:[dev_compiler/src/kernel/compiler.dart:3943
#39     ProgramCompiler._emitSyncFunctionBody (package:[dev_compiler/src/kernel/compiler.dart:3905
#40     ProgramCompiler._emitFunction (package:[dev_compiler/src/kernel/compiler.dart:3718
#41     ProgramCompiler._emitMethodDeclaration.<anonymous closure> (package:[dev_compiler/src/kernel/compiler.dart:2156
#42     ProgramCompiler._withMethodDeclarationContext (package:[dev_compiler/src/kernel/compiler.dart:3969
#43     ProgramCompiler._emitMethodDeclaration (package:[dev_compiler/src/kernel/compiler.dart:2155
#44     ProgramCompiler._emitClassMethods (package:[dev_compiler/src/kernel/compiler.dart:2096
#45     ProgramCompiler._emitClassDeclaration (package:[dev_compiler/src/kernel/compiler.dart:818
#46     ProgramCompiler._emitClass (package:[dev_compiler/src/kernel/compiler.dart:732
#47     List.forEach (dart:core-patch/growable_array.dart:416)
#48     ProgramCompiler._emitLibrary (package:[dev_compiler/src/kernel/compiler.dart:670
#49     List.forEach (dart:core-patch/growable_array.dart:416)
#50     ProgramCompiler.emitModule (package:[dev_compiler/src/kernel/compiler.dart:479
#51     compileSdkFromDill (package:[dev_compiler/src/kernel/command.dart:570
#52     _compile (package:[dev_compiler/src/kernel/command.dart:163
#53     compile (package:[dev_compiler/src/kernel/command.dart:52
#54     internalMain (package:[dev_compiler/ddc.dart:41
#55     main (google3:///[third_party/dart/dev_compiler/bin/dartdevc.dart:18
#56     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:292)
#57     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

This is blocking the CL from landing.

**Comment by nshahan** [comment]
@lrhn 
I would only expect the code path referenced in the stack trace to be used when running DDC compiles with the `--canary` flag. Can you link to the actual trybot run that shows this failure? 

AFAIK the only trybots that run DDC with the canary flag are `ddc-canary-linux-chrome` and `ddc-canary-linux-chrome-unsound`. I neither of those should be blocking as they are only run on post submit currently.

**Comment by lrhn** [comment]
It's the "monorepo-roller" try bot, so the logs are in internal systems. I'll mail you a link.

**Comment by lrhn** [comment]
Seems same bug blocks https://dart-review.googlesource.com/c/sdk/+/288903

**Comment by nshahan** [comment]
Thanks for the links. I see what is happening now. We have a test in the internal repo that validates you can run a DDC compile in canary mode. This must be the first use of a record type in the SDK or else we would have seen this before. I'll either temporarily disable the test or find a quick fix in DDC to unblock you.

**Comment by lrhn** [comment]
It is the first use of a record type in the platform libraries. (Canary worked successfully!)

**Comment by lrhn** [comment]
There are still errors when running the code, but that should only affect the actual tests (for now), and can be pre-approved. I've done that.
```
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:45565/root_build/generated_tests/ddc-canary-linux-chrome-unsound/tests_lib_async_future_record_extension_test/test.html?crossOriginPort=39081

Runtime window.onerror:
window.onunhandledrejection called: 

TypeError: Right-hand side of 'instanceof' is not callable
    at Object.dload (http://127.0.0.1:45565/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:4415:15)
    at Object.FutureRecord2$124get$35wait [as FutureRecord2|get#wait] (http://127.0.0.1:45565/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:40665:54)
    at main (http://127.0.0.1:45565/root_dart/out/ReleaseX64/generated_compilations/ddc-canary-linux-chrome-unsound/tests_lib_async_future_record_extension_test/future_record_extension_test.js:44:55)
    at main.next (<anonymous>)
    at runBody (http://127.0.0.1:45565/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:40514:34)
    at Object._async [as async] (http://127.0.0.1:45565/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:40546:7)
    at Object.main (http://127.0.0.1:45565/root_dart/out/ReleaseX64/generated_compilations/ddc-canary-linux-chrome-unsound/tests_lib_async_future_record_extension_test/future_record_extension_test.js:24:18)
    at testMainWrapper (http://127.0.0.1:45565/root_build/generated_tests/ddc-canary-linux-chrome-unsound/tests_lib_async_future_record_extension_test/test.html?crossOriginPort=39081:84:95)
    at dartMainRunner (http://127.0.0.1:45565/root_dart/pkg/test_runner/lib/src/test_controller.js:315:5)
    at http://127.0.0.1:45565/root_build/generated_tests/ddc-canary-linux-chrome-unsound/tests_lib_async_future_record_extension_test/test.html?crossOriginPort=39081:80:3
    at Object.execCb (http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:1696:33)
    at Module.check (http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:883:51)
    at Module.<anonymous> (http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:1139:34)
    at http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:134:23
    at http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:1189:21
    at each (http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:59:31)
    at Module.emit (http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:1188:17)
    at Module.check (http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:938:30)
    at Module.enable (http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:1176:22)
    at Module.init (http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:788:26)
    at callGetModule (http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:1203:63)
    at Object.completeLoad (http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:1590:21)
    at HTMLScriptElement.onScriptLoad (http://127.0.0.1:45565/root_dart/third_party/requirejs/require.js:1717:29)



Deobfuscated error and stack:
window.onunhandledrejection called: 

TypeError: Right-hand side of 'instanceof' is not callable
    at Object.dload                       ../../../../../dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 125:44
    at Object.FutureRecord2$124get$35wait ../../../../../dart-sdk/lib/async/future_extensions.dart 74:34
    at main                               ../../../../../tests/lib/async/future_record_extension_test.dart 25:28
    at     at main.next (<anonymous>)     unparsed
    at runBody                            ../../../../../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54
    at Object._async                      ../../../../../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5
    at Object.main                        ../../../../../tests/lib/async/future_record_extension_test.dart 11:10
    at testMainWrapper                    out/ReleaseX64/generated_tests/ddc-canary-linux-chrome-unsound/tests_lib_async_future_record_extension_test/test.html 84:95
    at dartMainRunner                     pkg/test_runner/lib/src/test_controller.js 315:5
    at <fn>                               out/ReleaseX64/generated_tests/ddc-canary-linux-chrome-unsound/tests_lib_async_future_record_extension_test/test.html 80:3
    at Object.execCb                      third_party/requirejs/require.js 1696:33
    at Module.check                       third_party/requirejs/require.js 883:51
    at Module.<fn>                        third_party/requirejs/require.js 1139:34
    at <fn>                               third_party/requirejs/require.js 134:23
    at <fn>                               third_party/requirejs/require.js 1189:21
    at each                               third_party/requirejs/require.js 59:31
    at Module.emit                        third_party/requirejs/require.js 1188:17
    at Module.check                       third_party/requirejs/require.js 938:30
    at Module.enable                      third_party/requirejs/require.js 1176:22
    at Module.init                        third_party/requirejs/require.js 788:26
    at callGetModule                      third_party/requirejs/require.js 1203:63
    at Object.completeLoad                third_party/requirejs/require.js 1590:21
    at HTMLScriptElement.onScriptLoad     third_party/requirejs/require.js 1717:29

```

**Comment by nshahan** [comment]
LGTM, the change I made in this mode updated the compiler from crashing to producing an incorrect output so runtime failures are to be expected.
