### ISSUE TITLE
[ffi] missing type argument in `@Native` crashes the compiler

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#51913]
```dart
@Native() // should have been @Native<Void Function()>
external void foo();
```

crashes the compiler

```
type 'DynamicType' is not a subtype of type 'FunctionType' in type cast

#0      FfiNativeTransformer.visitProcedure (package:vm/transformations/ffi/native.dart:671:58)
#1      Procedure.accept (package:kernel/ast.dart:3590:40)
#2      Transformer.transform (package:kernel/visitor.dart:1801:21)
#3      Transformer.transformList (package:kernel/visitor.dart:1836:18)
#4      Library.transformChildren (package:kernel/ast.dart:614:7)
#5      Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#6      TreeVisitor.visitLibrary (package:kernel/visitor.dart:513:35)
#7      FfiTransformer.visitLibrary (package:vm/transformations/ffi/common.dart:530:26)
#8      FfiNativeTransformer.visitLibrary (package:vm/transformations/ffi/native.dart:95:26)
#9      List.forEach (dart:core-patch/growable_array.dart:416:8)
#10     transformLibraries (package:vm/transformations/ffi/native.dart:41:13)
#11     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:179:26)
#12     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1568:19)
#13     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:638:7)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:413:23)
<asynchronous suspension>
#16     computeKernel (package:frontend_server/compute_kernel.dart:434:9)
<asynchronous suspension>
#17     main (file:///b/s/w/ir/x/w/sdk/utils/bazel/kernel_worker.dart:32:18)
<asynchronous suspension>
Target //experimental/users/iinozemtsev/flutter_ffi/java/com/google/android/apps/flutterffi:flutterffi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.323s, Forge stats: 0/1 actions cached, 0.8s CPU used, 0.0s queue time, 0.0 MB ObjFS output (novel bytes: 0.0 MB), 0.0 MB local output, Critical Path: 2.07s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
ERROR: Build did NOT complete successfully
INFO: Streaming build results to: [http://sponge2/61bf32f9-abf1-4f5c-ac21-ffc11828d43b](https://sponge2.corp.google.com/61bf32f9-abf1-4f5c-ac21-ffc11828d43b)
iblaze ERROR 12:35:48 blaze build failed: exit status 1
```

**Comment by faizan003** [comment]
i want to work on this

**Comment by faizan003** [comment]
If you omit the type argument, the Kotlin compiler tries to infer it based on the return type and parameter types of the function. However, if the compiler is unable to infer the type, it will raise a compile-time error.

If your compiler is crashing when you omit the type argument, it's likely that there's a bug in the compiler. You should try updating to the latest version of the Kotlin Native compiler and see if the issue has been fixed. If not, you can report the issue to the Kotlin team. In the meantime, you can work around the issue by specifying the type argument explicitly

**Comment by mraleph** [comment]
@faizan003 be warned that next time you will go across the repo posting meaningless ChatGPT (or similar) generated answers you will get banned from organization.
