### ISSUE TITLE
new ffi/vmspecific_regress_51794_test is failing on vm-aot-win-release-x64 

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#51966]
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8784646494527433841/+/u/test_results/new_test_failures__logs_

```

/===================================================================================\
| ffi/vmspecific_regress_51794_test is new and failed (RuntimeError, expected Pass) |
\===================================================================================/

--- Command "vm_compile_to_kernel" (took 03.000083s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & C:\b\s\w\ir\pkg\vm\tool\gen_kernel.bat --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o C:\b\s\w\ir\out\ReleaseX64\generated_compilations\vm-aot-win-release-x64\tests_ffi_vmspecific_regress_51794_test\out.dill C:\b\s\w\ir\tests\ffi\vmspecific_regress_51794_test.dart -Dtest_runner.configuration=vm-aot-win-release-x64 --packages=C:\b\s\w\ir\.dart_tool\package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 04.000494s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & out\ReleaseX64\gen_snapshot --snapshot-kind=app-aot-elf --elf=C:/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-win-release-x64/tests_ffi_vmspecific_regress_51794_test/out.aotsnapshot --loading-unit-manifest=C:/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-win-release-x64/tests_ffi_vmspecific_regress_51794_test/ignored.json --sound-null-safety -Dtest_runner.configuration=vm-aot-win-release-x64 --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\out\ReleaseX64\generated_compilations\vm-aot-win-release-x64\tests_ffi_vmspecific_regress_51794_test\out.dill

exit code:
0

--- Command "remove_kernel_file" (took 202ms):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & cmd.exe /c del C:\b\s\w\ir\out\ReleaseX64\generated_compilations\vm-aot-win-release-x64\tests_ffi_vmspecific_regress_51794_test\out.dill

exit code:
0

--- Command "vm" (took 192ms):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & out\ReleaseX64\dart_precompiled_runtime.exe --sound-null-safety -Dtest_runner.configuration=vm-aot-win-release-x64 --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-win-release-x64/tests_ffi_vmspecific_regress_51794_test/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:696)
#1      Expect.equals (package:expect/expect.dart:120)
#2      main (file:///C:/b/s/w/ir/tests/ffi/vmspecific_regress_51794_test.dart:16)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)

--- Re-run this test:
python3 tools/test.py -n vm-aot-win-release-x64 ffi/vmspecific_regress_51794_test
```

@dcharkes

**Comment by dcharkes** [comment]
Thanks @aam 

This test should be skipped in AOT on Windows due to linking issues: https://dart-review.googlesource.com/c/sdk/+/293685
