### ISSUE TITLE
Auto-bisect builders feature is broken

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51978]
```
Unhandled exception:
HTTP request failed. Client is already closed.
#0      IOClient.send (package:http/src/io_client.dart:56:7)
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
#2      BaseClient.post (package:http/src/base_client.dart:32:7)
#3      FirestoreDatabase.runQuery (file:///b/s/w/ir/cache/builder/sdk/tools/bots/lib/src/firestore.dart:62:34)
#4      updateBlameLists (file:///b/s/w/ir/cache/builder/sdk/tools/bots/update_blamelists.dart:106:37)
<asynchronous suspension>
```

from https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-ubsan-linux-release-x64/60

**Comment by athomas** [comment]
I don't have any additional context.

**Comment by whesse** [comment]
The logs don't give much information, except claiming the authenticated client connection used for Firestore API calls is closed.  It could be explicitly closed by the time the code hits this point, or closed by an earlier error.

This builder has never run bisection successfully since it started.  It may be a configuration problem.
The scripts that update the blamelist in Firestore are failing. I'm not sure if any configuration has been running them successfully. 

The problem is obvious.  The async work of making Firestore calls is not awaited, and the Http connection is closed immediately after it is created.  I'll fix that obvious problem first.

**Comment by whesse** [comment]
After this fix, the upload script hits a different failure.  We should be able to debug this by running locally, using the data from the last failing bisection build. Failing build with new failure: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-asan-linux-release-x64/97/overview

**Comment by whesse** [comment]
The same builder is now running bisections correctly, without failures in this upload script. The problem seems to be fixed.

**Comment by whesse** [comment]
After enabling bisection on all nightly builders, we observe failures in this script in 5 out of 26 runs. The failures seem to be flaky requests to Firestore, that aren't retried.  The solution may be to add retries to these requests.  Failing runs:

1. https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-eager-optimization-linux-release-x64/1557
2. https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-asan-linux-release-x64/264
3. https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-msan-linux-release-x64/280
4. https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-ubsan-linux-release-x64/255
5. https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-linux-release-x64/23110

**Comment by whesse** [comment]
The update_blamelists script doesn't seem to be doing what it should be doing, and is failing about 20% of the time.
I am working on a rewrite that should make it stop failing, and make it easier to diagnose if it is working correctly:

https://dart-review.googlesource.com/c/sdk/+/334221
