### ISSUE TITLE
Flaky co19/LibTest/io/WebSocket/closeCode_A01_t02 test

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#52011]
See [this log](https://dart-ci.appspot.com/log/vm-aot-win-product-x64/vm-aot-win-product-x64/49/co19/LibTest/io/WebSocket/closeCode_A01_t02):
```
exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <1000>, actual: <null>) fails.
#0      _fail (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect.dart:18)
#1      Expect.equals (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect_common.dart:16)
#2      main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/WebSocket/closeCode_A01_t02.dart:31)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-aot-win-product-x64 co19/LibTest/io/WebSocket/closeCode_A01_t02
```

@brianquinlan Could you look into whether the test is testing the right thing here?

**Comment by dcharkes** [comment]
Just flipped to consistently failing: https://dart-ci.web.app/#showLatestFailures=false&test=co19/LibTest/io/WebSocket/closeCode_A01_t02&configurations=vm-aot-win-debug-x64c

Same error: https://dart-ci.appspot.com/log/vm-aot-win-debug-x64c/vm-aot-win-debug-x64c/96/co19/LibTest/io/WebSocket/closeCode_A01_t02

**Comment by sstrickl** [comment]
Consistently failing on both [`vm-aot-win-debug-x64c`](https://dart-ci.appspot.com/log/vm-win-debug-x64c/vm-win-debug-x64c/98/co19/LibTest/io/WebSocket/closeCode_A01_t02), which went to flaky and then back since Daco re-reported it, and now [`vm-win-release-ia32`](https://dart-ci.appspot.com/log/vm-win-release-ia32/vm-win-release-ia32/81/co19/LibTest/io/WebSocket/closeCode_A01_t02), same error (logs in links).

**Comment by dcharkes** [comment]
https://dart-ci.appspot.com/log/vm-aot-win-debug-x64c/vm-aot-win-debug-x64c/103/co19/LibTest/io/WebSocket/closeCode_A01_t02 from pass -> consistently failing. Still the same error message.

**Comment by sstrickl** [comment]
[Same error](https://dart-ci.appspot.com/log/vm-win-release-ia32/vm-win-release-ia32/87/co19/LibTest/io/WebSocket/closeCode_A01_t02) again today.

**Comment by sstrickl** [comment]
Also flaky on [`vm-aot-win-release-x64`](https://dart-ci.appspot.com/log/vm-aot-win-release-x64/vm-aot-win-release-x64/668/co19/LibTest/io/WebSocket/closeCode_A01_t02).

**Comment by alexmarkov** [comment]
Failed once again on `vm-win-release-ia32`: https://dart-ci.appspot.com/log/vm-win-release-ia32/vm-win-release-ia32/89/co19/LibTest/io/WebSocket/closeCode_A01_t02

**Comment by dcharkes** [comment]
vm-aot-win-release-x64

Pass -> RuntimeError (expected Pass)
co19/LibTest/io/WebSocket/closeCode_A01_t02

Same error: https://dart-ci.appspot.com/log/vm-aot-win-release-x64/vm-aot-win-release-x64/692/co19/LibTest/io/WebSocket/closeCode_A01_t02

**Comment by alexmarkov** [comment]
Failed once again on `vm-win-release-ia32`: https://dart-ci.appspot.com/log/vm-win-release-ia32/vm-win-release-ia32/108/co19/LibTest/io/WebSocket/closeCode_A01_t02

**Comment by derekxu16** [comment]
happened again:

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-aot-win-release-x64/903/overview
https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-win-release-ia32/116/overview

**Comment by mkustermann** [comment]
Happened again today.

**Comment by derekxu16** [comment]
happened again:

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-aot-win-release-x64/1064/overview

**Comment by aam** [comment]
https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-aot-win-release-x64/1211/overview

**Comment by aam** [comment]
Raised https://github.com/dart-lang/co19/issues/2268 with proposed fix to the test
