### ISSUE TITLE
Flutter records aren't working for release builds

### ISSUE THREAD

**Issue by MainTobias** [dart-lang/sdk#52034]
* Windows 11 Version 10.0.22621 Build 22621
* Dart SDK build number (2.19.6)

When I tried building for the web flutter crashed. When running the code in a browser it would compile and work. Building an apk would also work.
I have included the whole error message and my code below

[Repo](https://github.com/MainTobias/topshop)
```bash
flutter build web --release --enable-experiment=records

💪 Building with sound null safety 💪

Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js'
instead.
lib/manage_products_screen.dart:19:10:
Internal Error: The compiler crashed when compiling this element.
  Widget build(BuildContext context) {
         ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.19.6), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Unsupported operation: Unhandled node RecordNameGet(products.{List.[]}(index).product)
(RecordNameGet)
#0      ScopeModelBuilder.defaultNode (package:compiler/src/ir/scope_visitor.dart:133:7)
#1      Visitor.defaultTreeNode (package:kernel/visitor.dart:1154:39)
#2      TreeVisitor.defaultExpression (package:kernel/visitor.dart:199:43)
#3      TreeVisitor.visitRecordNameGet (package:kernel/visitor.dart:344:47)
#4      RecordNameGet.accept (package:kernel/ast.dart:4531:44)
#5      ScopeModelBuilder.visitNode (package:compiler/src/ir/scope_visitor.dart:136:17)
#6      ScopeModelBuilder._handleExpression (package:compiler/src/ir/scope_visitor.dart:190:33)
#7      ScopeModelBuilder._handleVariableDeclaration (package:compiler/src/ir/scope_visitor.dart:365:26)
#8      ScopeModelBuilder.visitVariableDeclaration (package:compiler/src/ir/scope_visitor.dart:371:5)
#9      VariableDeclaration.accept (package:kernel/ast.dart:11226:43)
#10     ScopeModelBuilder.visitNode (package:compiler/src/ir/scope_visitor.dart:136:17)
#11     ScopeModelBuilder.visitNodes (package:compiler/src/ir/scope_visitor.dart:204:39)
#12     ScopeModelBuilder.visitBlock (package:compiler/src/ir/scope_visitor.dart:1346:5)
#13     Block.accept (package:kernel/ast.dart:9638:43)
#14     ScopeModelBuilder.visitNode (package:compiler/src/ir/scope_visitor.dart:136:17)
#15     ScopeModelBuilder.visitFunctionNode (package:compiler/src/ir/scope_visitor.dart:877:7)
#16     FunctionNode.accept (package:kernel/ast.dart:4083:38)
#17     ScopeModelBuilder.visitNode (package:compiler/src/ir/scope_visitor.dart:136:17)
#18     ScopeModelBuilder.visitFunctionExpression.<anonymous closure>.<anonymous closure>
(package:compiler/src/ir/scope_visitor.dart:703:9)
#19     VariableCollectorMixin.visitInVariableScope (package:compiler/src/ir/scope.dart:112:6)
#20     ScopeModelBuilder.visitFunctionExpression.<anonymous closure> (package:compiler/src/ir/scope_visitor.dart:702:7)
#21     ScopeModelBuilder.enterNewScope (package:compiler/src/ir/scope_visitor.dart:304:18)
#22     ScopeModelBuilder.visitInvokable (package:compiler/src/ir/scope_visitor.dart:620:5)
#23     ScopeModelBuilder.visitFunctionExpression (package:compiler/src/ir/scope_visitor.dart:701:5)
#24     FunctionExpression.accept (package:kernel/ast.dart:9033:44)
#25     ScopeModelBuilder.visitNode (package:compiler/src/ir/scope_visitor.dart:136:17)
#26     ScopeModelBuilder._handleExpression (package:compiler/src/ir/scope_visitor.dart:190:33)
#27     ScopeModelBuilder.visitNamedExpressions (package:compiler/src/ir/scope_visitor.dart:227:24)
#28     ScopeModelBuilder.visitArguments (package:compiler/src/ir/scope_visitor.dart:1056:26)
#29     ScopeModelBuilder.visitConstructorInvocation (package:compiler/src/ir/scope_visitor.dart:1078:5)
#30     ConstructorInvocation.accept (package:kernel/ast.dart:6999:44)
#31     ScopeModelBuilder.visitNode (package:compiler/src/ir/scope_visitor.dart:136:17)
#32     ScopeModelBuilder._handleExpression (package:compiler/src/ir/scope_visitor.dart:190:33)
#33     ScopeModelBuilder.visitNamedExpressions (package:compiler/src/ir/scope_visitor.dart:227:24)
#34     ScopeModelBuilder.visitArguments (package:compiler/src/ir/scope_visitor.dart:1056:26)
#35     ScopeModelBuilder.visitConstructorInvocation (package:compiler/src/ir/scope_visitor.dart:1078:5)
#36     ConstructorInvocation.accept (package:kernel/ast.dart:6999:44)
#37     ScopeModelBuilder.visitNode (package:compiler/src/ir/scope_visitor.dart:136:17)
#38     ScopeModelBuilder._handleExpression (package:compiler/src/ir/scope_visitor.dart:190:33)
#39     ScopeModelBuilder.visitReturnStatement (package:compiler/src/ir/scope_visitor.dart:1364:25)
#40     ReturnStatement.accept (package:kernel/ast.dart:10651:43)
#41     ScopeModelBuilder.visitNode (package:compiler/src/ir/scope_visitor.dart:136:17)
#42     ScopeModelBuilder.visitNodes (package:compiler/src/ir/scope_visitor.dart:204:39)
#43     ScopeModelBuilder.visitBlock (package:compiler/src/ir/scope_visitor.dart:1346:5)
#44     Block.accept (package:kernel/ast.dart:9638:43)
#45     ScopeModelBuilder.visitNode (package:compiler/src/ir/scope_visitor.dart:136:17)
#46     ScopeModelBuilder.visitFunctionNode (package:compiler/src/ir/scope_visitor.dart:877:7)
#47     FunctionNode.accept (package:kernel/ast.dart:4083:38)
#48     ScopeModelBuilder.visitNode (package:compiler/src/ir/scope_visitor.dart:136:17)
#49     ScopeModelBuilder.visitProcedure.<anonymous closure> (package:compiler/src/ir/scope_visitor.dart:694:7)
#50     ScopeModelBuilder.enterNewScope (package:compiler/src/ir/scope_visitor.dart:304:18)
#51     ScopeModelBuilder.visitInvokable (package:compiler/src/ir/scope_visitor.dart:620:5)
#52     ScopeModelBuilder.visitProcedure (package:compiler/src/ir/scope_visitor.dart:693:5)
#53     Procedure.accept (package:kernel/ast.dart:3475:40)
#54     ScopeModelBuilder.computeModel (package:compiler/src/ir/scope_visitor.dart:122:14)
#55     new ScopeModel.from (package:compiler/src/ir/scope.dart:27:20)
#56     KernelModularStrategy.getModularMemberData.<anonymous closure>
(package:compiler/src/kernel/kernel_strategy.dart:437:38)
#57     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#58     KernelModularStrategy.getModularMemberData (package:compiler/src/kernel/kernel_strategy.dart:436:43)
#59     KernelWorkItem.run.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:392:28)
#60     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#61     KernelWorkItem.run (package:compiler/src/kernel/kernel_strategy.dart:374:26)
#62     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous
closure> (package:compiler/src/compiler.dart:809:70)
#63     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#64     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>
(package:compiler/src/compiler.dart:809:32)
#65     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#66     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>
(package:compiler/src/compiler.dart:807:28)
#67     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#68     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:805:18)
#69     ResolutionEnqueuer._forEach (package:compiler/src/resolution/enqueuer.dart:236:12)
#70     ResolutionEnqueuer.forEach (package:compiler/src/resolution/enqueuer.dart:252:5)
#71     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:801:16)
#72     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#73     Compiler.emptyQueue (package:compiler/src/compiler.dart:800:14)
#74     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:824:7)
#75     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#76     Compiler.processQueue (package:compiler/src/compiler.dart:818:14)
#77     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:406:5)
#78     Compiler.produceClosedWorld (package:compiler/src/compiler.dart:608:11)
#79     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:734:15)
<asynchronous suspension>
#80     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:352:7)
<asynchronous suspension>
#81     Compiler.runInternal (package:compiler/src/compiler.dart:351:5)
<asynchronous suspension>
#82     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:272:11)
<asynchronous suspension>
#83     main (package:compiler/src/dart2js.dart:1435:3)
<asynchronous suspension>



#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:246:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#7      buildWeb (package:flutter_tools/src/web/compile.dart:53:32)
<asynchronous suspension>
#8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:135:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

Compiling lib\main.dart for the Web...                             19.3s
Exception: Failed to compile application for the Web.
```
and the code.

[Line the compiler starts having a problem](https://github.com/MainTobias/topshop/blob/c06bde08b98a674a44d26bf05627c26d9c26ee4e/lib/manage_products_screen.dart#L41)

PS I've tried using
```dart
products.getRange(index, index+1).first.product
```
which would not compile either.

**Comment by vsmenon** [comment]
Hi, thanks for trying this out!  We are fixing records issues in tip-of-tree (flutter's master channel) - stable is really far behind.  It's graduated from experiment to feature there - you won't need to pass an experiment flag.

If you try this there and still see the bug, please let us know.

**Comment by vsmenon** [comment]
Closing this.  If you do see the issue on tip-of-tree (master channel), please reopen a new bug.

**Comment by MainTobias** [comment]
Well now I can't run the build_runner anymore.
```bash
dart run --enable-experiment=records build_runner build
'records' is now enabled by default; this flag is no longer required.
[INFO] Generating build script completed, took 324ms
[INFO] Reading cached asset graph completed, took 112ms
[INFO] Checking for updates since last build completed, took 831ms
[INFO] Running build completed, took 17ms
[INFO] Caching finalized dependency graph completed, took 55ms
[SEVERE] json_serializable on lib/main.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:topshop/main.dart (or an existing part) contains the following errors.
main.dart:63:8: This requires the 'records' language feature to be enabled.
main.dart:65:28: This requires the 'records' language feature to be enabled.

Try fixing the errors and re-running the build.

[SEVERE] freezed on lib/shop_screen.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:topshop/shop_screen.dart (or an existing part) contains the following errors.
shop_screen.dart:25:10: This requires the 'records' language feature to be enabled.

Try fixing the errors and re-running the build.

[SEVERE] json_serializable on lib/current_order_screen.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:topshop/current_order_screen.dart (or an existing part) contains the following errors.
current_order_screen.dart:47:23: This requires the 'records' language feature to be enabled.

Try fixing the errors and re-running the build.

[SEVERE] freezed on lib/global.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:topshop/global.dart (or an existing part) contains the following errors.
global.dart:17:32: This requires the 'records' language feature to be enabled.
global.dart:22:8: This requires the 'records' language feature to be enabled.
global.dart:28:22: This requires the 'records' language feature to be enabled.
And 11 more...

Try fixing the errors and re-running the build.

[SEVERE] freezed on lib/current_order_screen.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:topshop/current_order_screen.dart (or an existing part) contains the following errors.
current_order_screen.dart:47:23: This requires the 'records' language feature to be enabled.

Try fixing the errors and re-running the build.

[SEVERE] json_serializable on lib/shop_screen.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:topshop/shop_screen.dart (or an existing part) contains the following errors.
shop_screen.dart:25:10: This requires the 'records' language feature to be enabled.

Try fixing the errors and re-running the build.

[SEVERE] json_serializable on lib/global.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:topshop/global.dart (or an existing part) contains the following errors.
global.dart:17:32: This requires the 'records' language feature to be enabled.
global.dart:22:8: This requires the 'records' language feature to be enabled.
global.dart:28:22: This requires the 'records' language feature to be enabled.
And 11 more...

Try fixing the errors and re-running the build.

[SEVERE] freezed on lib/main.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:topshop/main.dart (or an existing part) contains the following errors.
main.dart:63:8: This requires the 'records' language feature to be enabled.
main.dart:65:28: This requires the 'records' language feature to be enabled.

Try fixing the errors and re-running the build.

[SEVERE] Failed after 93ms
```

**Comment by vsmenon** [comment]
Can you please open a new bug and include the version of Dart you are on?  

Note, if you're on tip of tree:
- You should not need to pass in an experiment to use records.
- You will need to set the lower bound sdk constraint in your `pubspec.yaml` to `>=3.0.0-0`.
