### ISSUE TITLE
dart2js-production-linux-d8: language/no_such_method/mock_test failure

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#52036]
Failure:
```
dart2js-production-linux-d8:language/no_such_method/mock_test broke (Pass -> RuntimeError, expected Pass)
```

Logs:
```
/===========================================================================================================\
| dart2js-production-linux-d8:language/no_such_method/mock_test broke (Pass -> RuntimeError, expected Pass) |
\===========================================================================================================/

--- Command "dart2js" (took 03.000061s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart compile js -Dtest_runner.configuration=dart2js-production-linux-d8 --sound-null-safety --test-mode --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/language/no_such_method/mock_test.dart -O3 --sound-null-safety --out=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js

exit code:
0

stdout:
Info: Compiling with sound null safety.
tests/language/no_such_method/mock_test.dart:15:11:
Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing some optimizations.
Consider removing this 'noSuchMethod' implementation.
  dynamic noSuchMethod(Invocation invocation) {
          ^
tests/language/no_such_method/mock_test.dart:30:11:
Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing some optimizations.
Consider removing this 'noSuchMethod' implementation.
  dynamic noSuchMethod(Invocation invocation) {
          ^
tests/language/no_such_method/mock_test.dart:43:3:
Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing some optimizations.
Consider removing this 'noSuchMethod' implementation.
  noSuchMethod(i) => (i as dynamic).typeArguments;
  ^
tests/language/no_such_method/mock_test.dart:51:3:
Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing some optimizations.
Consider removing this 'noSuchMethod' implementation.
  noSuchMethod(i) {
  ^
tests/language/no_such_method/mock_test.dart:62:3:
Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing some optimizations.
Consider removing this 'noSuchMethod' implementation.
  noSuchMethod(i) => i.memberName == #call ? 42 : 0;
  ^
Compiled 9,768,509 characters Dart to 53,601 characters JavaScript in 3.02 seconds using 479.711 MB of memory
Dart file tests/language/no_such_method/mock_test.dart compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js

--- Command "d8" (took 52ms):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/third_party/d8/linux/d8 out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js

exit code:
1

stdout:
out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: Expect.throws(TypeError) fails: Did not throw
          throw e;
          ^
Expect.throws(TypeError) fails: Did not throw
    at Object.a (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js:114:3)
    at Object.y (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js:1236:14)
    at Object.bA (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js:1235:75)
    at ds (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js:1245:3)
    at action (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js:1898:39
    at /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js:1893:55
    at dartProgram (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js:1896:84)

Deobfuscated error and stack:
Expect.throws(TypeError) fails: Did not throw
    at wrapException            org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 1195:37
    at Expect._fail             ../../../../../pkg/expect/lib/expect.dart 696:5
    at Expect.throws            ../../../../../pkg/expect/lib/expect.dart 604:5
    at throwsTypeError(inlined) ../../../../../pkg/expect/lib/expect.dart 638:14
    at main                     ../../../../../tests/language/no_such_method/mock_test.dart 71:10
    at action                   out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js 275:31
    at eventLoop                out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js 258:9
    at self.dartMainRunner      out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js 276:5
    at <fn>                     out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js 1898:39
    at <fn>                     out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js 1893:55
    at dartProgram              out/ReleaseX64/generated_compilations/dart2js-production-linux-d8/tests_language_no_such_method_mock_test/mock_test.js 1896:84
```

**Comment by fishythefish** [comment]
Tests that check for implicit type errors generally fail on production dart2js due to the (intentional) behavior of `--omit-implicit-checks`.

The core issue in this test is
```dart
class Foo {
  String s = '';
}

void main() {
  final foo = Foo();
  (foo as dynamic).s = 42; // does not throw with --omit-implicit-checks
  print(foo.s);
}
```
