### ISSUE TITLE
`ffi/function_varargs_test` RuntimeError (expected Pass)

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#52112]
The tests
```
ffi/function_varargs_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-android-{debug,release}-arm
```

**Logs:**

```
/=======================================================================\
| ffi/function_varargs_test broke (Pass -> RuntimeError, expected Pass) |
\=======================================================================/

--- Command "vm_compile_to_kernel" (took 530ms):
DART_CONFIGURATION=DebugAndroidARM /b/swarming/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=out/DebugAndroidARM/vm_platform_strong.dill -o /b/swarming/w/ir/out/DebugAndroidARM/generated_compilations/vm-android-debug-arm/tests_ffi_function_varargs_test/out.dill /b/swarming/w/ir/tests/ffi/function_varargs_test.dart -Dtest_runner.configuration=vm-android-debug-arm --enable-experiment=records --packages=/b/swarming/w/ir/.dart_tool/package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "adb_precompilation" (took 02.000404s):
Steps to push Dart VM and Dill file to an attached device. Uses (and requires) adb.

exit code:
255

stdout:
Executing adb -s 06ad9c24003b6ca5 shell rm -Rf /data/local/tmp/testing/test ; echo AdbShellExitCode:  $?
Stdout:
AdbShellExitCode: 0
ExitCode: 0
Time: 0:00:00.018159

Executing adb -s 06ad9c24003b6ca5 shell mkdir -p /data/local/tmp/testing/test ; echo AdbShellExitCode:  $?
Stdout:
AdbShellExitCode: 0
ExitCode: 0
Time: 0:00:00.010633

Executing Skipped cached push
ExitCode: 0
Time: 0:00:00.000032

Executing adb -s 06ad9c24003b6ca5 push /b/swarming/w/ir/out/DebugAndroidARM/generated_compilations/vm-android-debug-arm/tests_ffi_function_varargs_test/out.dill /data/local/tmp/testing/test/out.dill
Stdout:
/b/swarming/w/ir/out/DebugAndroidARM/generated_compilations/vm-android-debug-arm/tests_ffi_function_varargs_test/out.dill: 1 file pushed. 5.7 MB/s (7585800 bytes in 1.278s)
ExitCode: 0
Time: 0:00:01.284402

Executing adb -s 06ad9c24003b6ca5 shell export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/data/local/tmp/testing/test;/data/local/tmp/testing/dart --android-log-to-stderr --enable-experiment=records --sound-null-safety -Dtest_runner.configuration=vm-android-debug-arm --ignore-unrecognized-flags --packages=/b/swarming/w/ir/.dart_tool/package_config.json /data/local/tmp/testing/test/out.dill ; echo AdbShellExitCode:  $?
Stdout:
Unhandled exception:
Invalid argument(s): Failed to lookup symbol 'printf': undefined symbol: printf
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      printf (file:///b/swarming/w/ir/tests/ffi/function_varargs_test.dart)
#2      printf (file:///b/swarming/w/ir/tests/ffi/function_varargs_test.dart)
#3      main.<anonymous closure> (file:///b/swarming/w/ir/tests/ffi/function_varargs_test.dart:18:5)
#4      using (package:ffi/src/arena.dart:124:31)
#5      main (file:///b/swarming/w/ir/tests/ffi/function_varargs_test.dart:17:3)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
AdbShellExitCode: 255
ExitCode: 255
Time: 0:00:01.076069

--- Re-run this test:
python3 tools/test.py -n vm-android-debug-arm **ffi/function_varargs_test**
```

**Comment by dcharkes** [comment]
Looks like `printf` is not available in the process.

I had likely approved this and the approval got lost because of the bot rename.

The varargs calling convention is extensively covered in the generated tests, which are passing for this bot: https://dart-ci.firebaseapp.com/current_results/#/filter=ffi/function_varargs,vm-android-debug-arm&showAll
