### ISSUE TITLE
Compiler crash with `inline class`

### ISSUE THREAD

**Issue by haberman** [dart-lang/sdk#52119]
Repro:

```dart
inline class Foo {
  Foo() : this._();
}
```

Output:

```
$ dart --version
Dart SDK version: 3.1.0-15.0.dev (dev) (None) on "linux_x64"
$ dart --enable-experiment=inline-class  test.dart
Crash when compiling file:///tmp/test.dart at character offset 25:
Null check operator used on a null value

#0      BodyBuilder.lookupConstructor (package:front_end/src/fasta/kernel/body_builder.dart:3146:30)
#1      ThisAccessGenerator.buildConstructorInitializer (package:front_end/src/fasta/kernel/expression_generator.dart:4601:17)
#2      ThisAccessGenerator.buildSelectorAccess (package:front_end/src/fasta/kernel/expression_generator.dart:4499:14)
#3      InvocationSelector.withReceiver (package:front_end/src/fasta/kernel/expression_generator.dart:4916:23)
#4      BodyBuilder.doDotOrCascadeExpression (package:front_end/src/fasta/kernel/body_builder.dart:2946:17)
#5      BodyBuilder.endBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:2698:7)
#6      Listener.handleEndingBinaryExpression (package:_fe_analyzer_shared/src/parser/listener.dart:1660:5)
#7      Parser._parsePrecedenceExpressionLoop (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5864:22)
#8      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5753:12)
#9      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5669:15)
#10     Parser.parseInitializerExpressionRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4049:13)
#11     Parser.parseInitializer (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3943:17)
#12     Parser.parseInitializers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3857:15)
#13     Parser.parseInitializersOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3836:14)
#14     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1108:22)
#15     DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:756:5)
#16     DietListener.endClassConstructor (package:front_end/src/fasta/source/diet_listener.dart:703:5)
#17     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4882:20)
#18     Parser.parseClassOrMixinOrExtensionOrEnumMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4631:15)
#19     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4248:15)
#20     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2684:13)
#21     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2642:14)
#22     Parser._handleModifiersForClassDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:822:12)
#23     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:662:14)
#24     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:610:14)
#25     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:413:15)
#26     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1267:12)
<asynchronous suspension>
#27     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:676:7)
<asynchronous suspension>
#28     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:608:7)
<asynchronous suspension>
#29     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#30     _buildInternal (package:front_end/src/kernel_generator_impl.dart:207:19)
<asynchronous suspension>
#31     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#32     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#33     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#34     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#35     SingleShotCompilerWrapper.compileInternal (file:///tmp/tmpis_lij6s/dart-3.1.0-15.0.dev/dart/pkg/vm/bin/kernel_service.dart:407:11)
<asynchronous suspension>
#36     Compiler.compile.<anonymous closure> (file:///tmp/tmpis_lij6s/dart-3.1.0-15.0.dev/dart/pkg/vm/bin/kernel_service.dart:215:45)
<asynchronous suspension>
#37     _processLoadRequest (file:///tmp/tmpis_lij6s/dart-3.1.0-15.0.dev/dart/pkg/vm/bin/kernel_service.dart:889:37)
<asynchronous suspension>

```

cc @mraleph

**Comment by mraleph** [comment]
This inline class is invalid, but the compiler should report compile time error and not crash. /cc @johnniwinther

**Comment by haberman** [comment]
This (presumably valid) inline class also triggers a crash, but a different crash:

```dart
inline class Foo {
  final int foo_;
  factory Foo() { return Foo._(0); }
  Foo._(this.foo_);
}

void main() {
  var foo = Foo();
}
```

Crash is:

```
Crash when compiling:
test.dart:3:11: Internal problem: Unhandled Procedure:BuiltMemberKind.Method in buildMembers.
  factory Foo() { return Foo._(0); }
          ^

#0      internalProblem (package:front_end/src/fasta/problems.dart:52:5)
#1      unhandled (package:front_end/src/fasta/problems.dart:71:10)
#2      SourceInlineClassBuilder.addMemberDescriptorInternal (package:front_end/src/fasta/source/source_inline_class_builder.dart:165:9)
#3      SourceDeclarationBuilderMixin._buildMember (package:front_end/src/fasta/source/source_builder_mixins.dart:179:7)
#4      SourceDeclarationBuilderMixin.buildInternal.buildBuilders.<anonymous closure> (package:front_end/src/fasta/source/source_builder_mixins.dart:83:11)
#5      SourceFactoryBuilder.buildOutlineNodes (package:front_end/src/fasta/source/source_factory_builder.dart:149:6)
#6      SourceDeclarationBuilderMixin.buildInternal.buildBuilders (package:front_end/src/fasta/source/source_builder_mixins.dart:82:14)
#7      NameIteratorExtension.forEach (package:front_end/src/fasta/scope.dart:1327:8)
#8      SourceDeclarationBuilderMixin.buildInternal (package:front_end/src/fasta/source/source_builder_mixins.dart:93:45)
#9      SourceInlineClassBuilder.build (package:front_end/src/fasta/source/source_inline_class_builder.dart:129:5)
#10     SourceLibraryBuilder._buildOutlineNodes (package:front_end/src/fasta/source/source_library_builder.dart:3354:45)
#11     SourceLibraryBuilder.buildOutlineNodes (package:front_end/src/fasta/source/source_library_builder.dart:1121:7)
#12     SourceLoader.buildOutlineNodes (package:front_end/src/fasta/source/source_loader.dart:2496:32)
#13     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:464:14)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#15     _buildInternal (package:front_end/src/kernel_generator_impl.dart:143:7)
<asynchronous suspension>
#16     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#17     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#18     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#19     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#20     SingleShotCompilerWrapper.compileInternal (file:///tmp/tmpis_lij6s/dart-3.1.0-15.0.dev/dart/pkg/vm/bin/kernel_service.dart:407:11)
<asynchronous suspension>
#21     Compiler.compile.<anonymous closure> (file:///tmp/tmpis_lij6s/dart-3.1.0-15.0.dev/dart/pkg/vm/bin/kernel_service.dart:215:45)
<asynchronous suspension>
#22     _processLoadRequest (file:///tmp/tmpis_lij6s/dart-3.1.0-15.0.dev/dart/pkg/vm/bin/kernel_service.dart:889:37)
<asynchronous suspension>
```
```
