### ISSUE TITLE
[dart2wasm] Lists of Ffi pointers fail with a weird exception

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#52142]
Steps to reproduce:
Compiling the following code in dart2wasm:
```
import 'dart:ffi';

void main() {
  final List<Pointer<Void>> voidPointers = <Pointer<Void>>[];
  final Pointer<Void> ptr = Pointer<Void>.fromAddress(1234);
  voidPointers.add(ptr);
}
```
Running with d8 + `run_wasm.js` produces this odd exception:
```
type 'bool' is not a subtype of type 'Pointer<Void>' of 'value'
    at _GrowableList.add (wasm://wasm/000aa9a2:wasm-function[189]:0x18b27)
    at main (wasm://wasm/000aa9a2:wasm-function[54]:0x1543e)
    at main tear-off (wasm://wasm/000aa9a2:wasm-function[56]:0x1544f)
    at _invokeMain (wasm://wasm/000aa9a2:wasm-function[67]:0x15b3f)
    at Module.invoke (/Users/jacksongardner/Desktop/scratch/test_pointer_list.mjs:184:28)
    at main (pkg/dart2wasm/bin/run_wasm.js:72:21)
pkg/dart2wasm/bin/run_wasm.js:73: [object WebAssembly.Exception]
```

**Comment by askeksa-google** [comment]
We don't support boxing of pointers, which is necessary to put them in lists. The current boxing infrastructure can't support it easily, since it distinguishes types based on their Wasm representation, so it can't tell a pointer from a `bool`, both of which are represented as `i32`.

A workaround when needing a list of pointers would be to store the addresses instead and reconstruct the pointers when retrieving them.

**Comment by eyebrowsoffire** [comment]
Storing the addresses is how I've worked around the situation in the meantime. If lists of ffi pointers are not supported, though, it should be a static compile time error, not a runtime one. However... maybe we can actually support this by doing a frontend transformation that changes the list of pointers to a list of addresses automatically.

**Comment by askeksa-google** [comment]
I imagine we'll eventually have a more elaborate boxing infrastructure which will allow this. We'll need that for other features as well, such as (un)boxing of SIMD values and records.
