### ISSUE TITLE
newly introduced regexp_regress_52182_test fails on ddc/dar2js-linux-chrome bots

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#52187]
The test that confirms that the bug https://github.com/dart-lang/sdk/issues/52182 is fixed, fails in browsers

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8782733023548991841/+/u/test_results/new_test_failures__logs_

```

/==========================================================================================\
| corelib/regexp/regexp_regress_52182_test is new and failed (RuntimeError, expected Pass) |
\==========================================================================================/

--- Command "ddc" (took 148ms):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/dart-sdk/bin/snapshots/dartdevc.dart.snapshot --dart-sdk-summary /b/s/w/ir/out/ReleaseX64/ddc_outline_unsound.dill -Dtest_runner.configuration=ddc-linux-chrome-unsound --no-sound-null-safety -Dtest_runner.configuration=ddc-linux-chrome-unsound --ignore-unrecognized-flags --no-summarize -o /b/s/w/ir/out/ReleaseX64/generated_compilations/ddc-linux-chrome-unsound/tests_corelib_regexp_regexp_regress_52182_test/regexp_regress_52182_test.js /b/s/w/ir/tests/corelib/regexp/regexp_regress_52182_test.dart -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/async_helper.dill=async_helper -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/expect.dill=expect -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/js.dill=js -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/meta.dill=meta

exit code:
0

--- Command "chrome" (took 905ms):
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:36235/root_build/generated_tests/ddc-linux-chrome-unsound/tests_corelib_regexp_regexp_regress_52182_test/test.html?crossOriginPort=44049

Runtime error:
Error: Expect.isTrue(false) fails.
    at Object.throw_ [as throw] (http://127.0.0.1:36235/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:5026:11)
    at Function._fail (http://127.0.0.1:36235/root_build/gen/utils/dartdevc/pkg_kernel/async_helper.js:732:17)
    at Function.isTrue (http://127.0.0.1:36235/root_build/gen/utils/dartdevc/pkg_kernel/async_helper.js:247:21)
    at Object.main (http://127.0.0.1:36235/root_dart/out/ReleaseX64/generated_compilations/ddc-linux-chrome-unsound/tests_corelib_regexp_regexp_regress_52182_test/regexp_regress_52182_test.js:18:19)
    at testMainWrapper (http://127.0.0.1:36235/root_build/generated_tests/ddc-linux-chrome-unsound/tests_corelib_regexp_regexp_regress_52182_test/test.html?crossOriginPort=44049:84:94)

Deobfuscated error and stack:
Error: Expect.isTrue(false) fails.
    at Object.throw_   out/ReleaseX64/gen/utils/dartdevc/kernel/amd/dart_sdk.js 5026:11
    at Function._fail  ../../../../../../pkg/expect/lib/expect.dart 696:5
    at Function.isTrue ../../../../../../pkg/expect/lib/expect.dart 127:5
    at Object.main     ../../../../../tests/corelib/regexp/regexp_regress_52182_test.dart 11:10
    at testMainWrapper out/ReleaseX64/generated_tests/ddc-linux-chrome-unsound/tests_corelib_regexp_regexp_regress_52182_test/test.html 84:94


exit code:
0

--- To debug locally, run:
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/pkg/test_runner/bin/http_server.dart -p 36235 -c 44049 --network 127.0.0.1 --build-directory=/b/s/w/ir/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/.dart_tool/package_config.json

--- Re-run this test:
python3 tools/test.py -n ddc-linux-chrome-unsound corelib/regexp/regexp_regress_52182_test


/=======================================================================================================================\
| ddc-linux-chrome-unsound_2:corelib_2/regexp/regexp_regress_52182_test is new and failed (RuntimeError, expected Pass) |
\=======================================================================================================================/

--- Command "ddc" (took 36ms):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/dart-sdk/bin/snapshots/dartdevc.dart.snapshot --dart-sdk-summary /b/s/w/ir/out/ReleaseX64/ddc_outline_unsound.dill -Dtest_runner.configuration=ddc-linux-chrome-unsound_2 --no-sound-null-safety -Dtest_runner.configuration=ddc-linux-chrome-unsound_2 --ignore-unrecognized-flags --no-summarize -o /b/s/w/ir/out/ReleaseX64/generated_compilations/ddc-linux-chrome-unsound_2/tests_corelib_2_regexp_regexp_regress_52182_test/regexp_regress_52182_test.js /b/s/w/ir/tests/corelib_2/regexp/regexp_regress_52182_test.dart -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/async_helper.dill=async_helper -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/expect.dill=expect -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/js.dill=js -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/meta.dill=meta

exit code:
0

--- Command "chrome" (took 01.000835s):
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:42449/root_build/generated_tests/ddc-linux-chrome-unsound_2/tests_corelib_2_regexp_regexp_regress_52182_test/test.html?crossOriginPort=34543

Runtime error:
Error: Expect.isTrue(false) fails.
    at Object.throw_ [as throw] (http://127.0.0.1:42449/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:5026:11)
    at Function._fail (http://127.0.0.1:42449/root_build/gen/utils/dartdevc/pkg_kernel/async_helper.js:732:17)
    at Function.isTrue (http://127.0.0.1:42449/root_build/gen/utils/dartdevc/pkg_kernel/async_helper.js:247:21)
    at Object.main (http://127.0.0.1:42449/root_dart/out/ReleaseX64/generated_compilations/ddc-linux-chrome-unsound_2/tests_corelib_2_regexp_regexp_regress_52182_test/regexp_regress_52182_test.js:18:19)
    at testMainWrapper (http://127.0.0.1:42449/root_build/generated_tests/ddc-linux-chrome-unsound_2/tests_corelib_2_regexp_regexp_regress_52182_test/test.html?crossOriginPort=34543:84:96)

Deobfuscated error and stack:
Error: Expect.isTrue(false) fails.
    at Object.throw_   out/ReleaseX64/gen/utils/dartdevc/kernel/amd/dart_sdk.js 5026:11
    at Function._fail  ../../../../../../pkg/expect/lib/expect.dart 696:5
    at Function.isTrue ../../../../../../pkg/expect/lib/expect.dart 127:5
    at Object.main     ../../../../../tests/corelib_2/regexp/regexp_regress_52182_test.dart 13:10
    at testMainWrapper out/ReleaseX64/generated_tests/ddc-linux-chrome-unsound_2/tests_corelib_2_regexp_regexp_regress_52182_test/test.html 84:96


exit code:
0

--- To debug locally, run:
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/pkg/test_runner/bin/http_server.dart -p 42449 -c 34543 --network 127.0.0.1 --build-directory=/b/s/w/ir/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/.dart_tool/package_config.json

--- Re-run this test:
python3 tools/test.py -n ddc-linux-chrome-unsound_2 corelib_2/regexp/regexp_regress_52182_test

```

**Comment by nshahan** [comment]
This is a little confusing because the linked issue describes the same code as working on the JS compilers but not the VM. I can't repro this locally so I think the failures will probably be resolved if we update chrome on the test infra. Right now it is pinned to version 101.0.4951.41.

@rakudrama Any reason not to update chrome to the latest stable? (112.0.5615.165 as I am writing this)

**Comment by lrhn** [comment]
The old version explains the issue. Chrome 101 was released around April 2022, the bugfix was done in August 2022.

We should probably always be testing on the newest stable Chrome release, otherwise we won't know if our code works in the browsers our users actually use.

**Comment by nshahan** [comment]
The chrome failures were fixed via a version update https://dart-review.googlesource.com/c/sdk/+/301520.

@athomas Can we update the version of firefox on the bots to the latest stable as well? I'm seeing the same scenario where the test passes locally with the latest version and is failing on the bots where the release is a little over a year old.
