### ISSUE TITLE
Improve Isolate.spawnUri documentation with relation to isolate group

### ISSUE THREAD

**Issue by julemand101** [dart-lang/sdk#52186]
Currently, the documentation of isolates on https://api.dart.dev are rather vague of the existence of isolate groups. E.g. documentation of `Isolate` does not mention the concept and neither do `Isolate.spawn` or `Isolate.spawnUri`.

We find a clue in `Isolate.exit` with the following:
> It also throws if a finalMessagePort is associated with an isolate spawned outside of current isolate group, spawned via [spawnUri](https://api.dart.dev/dev/3.1.0-47.0.dev/dart-isolate/Isolate/spawnUri.html).

But I am not really sure a person without any idea about isolate groups are going to understand fully what that description even means. Especially if they don't read the documentation and are just seeing the exception being thrown in case of trying to use `Isolate.exit` with `Isolate.spawnUri`:
```
Invalid argument(s): exit with final message is only allowed for isolates in one isolate group.
#0      Isolate._exit (dart:isolate-patch/isolate_patch.dart:654:75)
#1      Isolate.exit (dart:isolate-patch/isolate_patch.dart:657:5)
```

I suggest mention the isolate group in the `Isolate.spawnUri` documentation with a link to:
https://dart.dev/language/concurrency#performance-and-isolate-groups

Another suggestion would be to remove the mention of isolate groups from the error message and api.dart.dev, and instead simplify the explanation by just stating that you cannot use `Isolate.exit` together with an isolate spawned with `Isolate.spawnUri` (mention this both in `Isolate.exit` and `Isolate.spawnUri`) and then link to the previous mention page for further details.

(Bonus: Should `Isolate.spawnUri` still have the following now we are getting ready for Dart 3.0?)
> In Dart2 strong mode, the checked parameter only controls asserts, but not type checks.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/374202 should address this.

> Another suggestion would be to remove the mention of isolate groups from the error message and api.dart.dev, and instead simplify the explanation by just stating that you cannot use Isolate.exit together with an isolate spawned with Isolate.spawnUri (mention this both in Isolate.exit and Isolate.spawnUri) and then link to the previous mention page for further details.

It is ok to call isolate.exit from an isolate spawned with isolate.spawnUri, it is an error only when the optional parameter `finalMessagePort` is provided and the the port belongs to an isolate in a different group.
