### ISSUE TITLE
vm/test/unlinked_ast_to_text_test.dart fails when adding Uri.directory call to Dart2JS

### ISSUE THREAD

**Issue by biggs0125** [dart-lang/sdk#52264]
After adding a call to the `Uri.directory` factory in Dart2JS, I start to see the test in question failing. Dart2JS already calls `Uri.parse` in many places but this is the first invocation of `Uri.directory` in Dart2JS.

Test failure:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8782048224955982097/+/u/test_results/new_test_failures__logs_

Based on the test failure it seems like the `Uri.directory` factory is not found but it's unclear why this is different than `Uri.parse`.

**Comment by a-siva** [comment]
Tried the test locally on linux 64 builds and it doesn't appear to fail.

@biggs0125 the link you have pasted above doesn't seem to have the logs, do you still have a log of the failure?

**Comment by biggs0125** [comment]
The trailing underscore is not being included in the link so you have to copy-paste for that link to work. Here's the error though:

```
Unhandled exception:
Reference to dart:core::Uri::@factories::directory is not bound to an AST node. A procedure was expected
#0      Reference.asProcedure (package:kernel/canonical_name.dart:547:7)
#1      RedirectingFactoryTearOffConstant.target (package:kernel/ast.dart:14688:43)
#2      RedirectingFactoryTearOffConstant.visitChildren (package:kernel/ast.dart:14695:5)
#3      ConstantNamer.getName (package:kernel/text/ast_to_text.dart:61:18)
#4      NameSystem.nameConstant (package:kernel/text/ast_to_text.dart:213:51)
#5      Printer.writeConstantReference (package:kernel/text/ast_to_text.dart:2889:30)
#6      Printer.visitConstantExpression (package:kernel/text/ast_to_text.dart:2894:5)
#7      ConstantExpression.accept (package:kernel/ast.dart:9235:44)
#8      Printer.writeNode (package:kernel/text/ast_to_text.dart:690:12)
#9      Printer.writeExpression (package:kernel/text/ast_to_text.dart:1097:5)
#10     Printer.visitConditionalExpression (package:kernel/text/ast_to_text.dart:1769:5)
#11     ConditionalExpression.accept (package:kernel/ast.dart:7432:44)
#12     Printer.writeNode (package:kernel/text/ast_to_text.dart:690:12)
#13     Printer.writeExpression (package:kernel/text/ast_to_text.dart:1097:5)
#14     Printer.visitFunctionInvocation (package:kernel/text/ast_to_text.dart:1627:5)
#15     FunctionInvocation.accept (package:kernel/ast.dart:6466:44)
#16     Printer.writeNode (package:kernel/text/ast_to_text.dart:690:12)
#17     Printer.writeExpression (package:kernel/text/ast_to_text.dart:1097:5)
#18     Printer.visitConditionalExpression (package:kernel/text/ast_to_text.dart:1771:5)
#19     ConditionalExpression.accept (package:kernel/ast.dart:7432:44)
#20     Printer.writeNode (package:kernel/text/ast_to_text.dart:690:12)
#21     Printer.writeExpression (package:kernel/text/ast_to_text.dart:1097:5)
#22     Printer.visitAsExpression (package:kernel/text/ast_to_text.dart:1881:5)
#23     AsExpression.accept (package:kernel/ast.dart:8167:44)
#24     Printer.writeNode (package:kernel/text/ast_to_text.dart:690:12)
#25     Printer.writeExpression (package:kernel/text/ast_to_text.dart:1097:5)
#26     Printer.visitReturnStatement (package:kernel/text/ast_to_text.dart:2515:7)
#27     ReturnStatement.accept (package:kernel/ast.dart:10798:43)
#28     Printer.writeNode (package:kernel/text/ast_to_text.dart:690:12)
#29     List.forEach (dart:core-patch/growable_array.dart:416:8)
#30     Printer.writeFunctionBody (package:kernel/text/ast_to_text.dart:855:23)
#31     Printer.writeFunction (package:kernel/text/ast_to_text.dart:820:7)
#32     Printer.visitProcedure (package:kernel/text/ast_to_text.dart:1237:9)
#33     Procedure.accept (package:kernel/ast.dart:3590:40)
#34     Printer.writeNode (package:kernel/text/ast_to_text.dart:690:12)
#35     List.forEach (dart:core-patch/growable_array.dart:416:8)
#36     Printer.writeStandardLibraryContent (package:kernel/text/ast_to_text.dart:521:24)
#37     Printer.writeComponentFile (package:kernel/text/ast_to_text.dart:601:13)
#38     writeComponentToText (package:kernel/kernel.dart:86:8)
#39     main (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/test/unlinked_ast_to_text_test.dart:69:5)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n unittest-asserts-release-linux pkg/vm/test/unlinked_ast_to_text_test
```
