### ISSUE TITLE
[Patterns] No error on Mac arm64 if runtime type of the Stream is not assignable to pattern's type in async for-in

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52265]
The following code produces no expected runtime error on `Mac arm64`
```dart
main() async {
  String log = "";
  Expect.throws(() {
    await for (var (int v1)
        in Stream<num>.fromIterable([1, 2, 3.14]) as dynamic) {
      log += "$v1;";
    }
  });
  Expect.equals("", log);
```
This produces the following [error](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8782022931412223297/+/u/test_results/new_test_failures__logs_)
```
--- Command "vm" (took 03.000586s):
DART_CONFIGURATION=DebugARM64 xcodebuild/DebugARM64/dart --sound-null-safety -Dtest_runner.configuration=vm-mac-debug-arm64 --enable-experiment=patterns,records --ignore-unrecognized-flags --packages=/opt/s/w/ir/.dart_tool/package_config.json /opt/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/execution_pattern_await_for_in_statement_A02_t03.dart

exit code:
255

stderr:
Unhandled exception:
Expect.throws() fails
#0      _fail (file:///opt/s/w/ir/tests/co19/src/Utils/expect.dart:18:5)
#1      Expect.throws (file:///opt/s/w/ir/tests/co19/src/Utils/expect_common.dart:194:5)
#2      main (file:///opt/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/execution_pattern_await_for_in_statement_A02_t03.dart:41:10)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

--- Re-run this test:
python3 tools/test.py -n vm-mac-debug-arm64 co19/LanguageFeatures/Patterns/execution_pattern_await_for_in_statement_A02_t03
```
No this issue on VM on other platforms

**Comment by chloestefantsova** [comment]
Seems to be the same as https://github.com/dart-lang/sdk/issues/52267
