### ISSUE TITLE
recognize armv8l host as arm

### ISSUE THREAD

**Issue by selfisekai** [dart-lang/sdk#52290]
currently the gn wrapper fails with this on an armv8l host
```
Traceback (most recent call last):
  File "/builds/selfisekai/aports/testing/dart3/src/dart-sdk-3.0.0-417.4.beta/./tools/build.py", line 16, in <module>
    import gn as gn_py
  File "/builds/selfisekai/aports/testing/dart3/src/dart-sdk-3.0.0-417.4.beta/tools/gn.py", line 15, in <module>
    HOST_ARCH = utils.GuessArchitecture()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/selfisekai/aports/testing/dart3/src/dart-sdk-3.0.0-417.4.beta/tools/utils.py", line 268, in GuessArchitecture
    return HostArchitectures()[0]
           ^^^^^^^^^^^^^^^^^^^
  File "/builds/selfisekai/aports/testing/dart3/src/dart-sdk-3.0.0-417.4.beta/tools/utils.py", line 262, in HostArchitectures
    raise Exception('Failed to determine host architectures for %s %s',
Exception: ('Failed to determine host architectures for %s %s', 'armv8l', 'Linux')
```

**Comment by selfisekai** [comment]
CL submitted: https://dart-review.googlesource.com/c/sdk/+/301900

**Comment by sortie** [comment]
Thanks for your contribution :)

**Comment by selfisekai** [comment]
merged
