### ISSUE TITLE
Failures on Add tests for behavior of class modifiers through legacy libraries.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#52302]
There are new test failures on [Add tests for behavior of class modifiers through legacy libraries.](https://dart-review.googlesource.com/c/sdk/+/301442).

The tests
```
language/class_modifiers/trans_legacy/legacy_superdeclaration_test CompileTimeError (expected Pass)
language/class_modifiers/trans_legacy/legacy_superdeclaration_test Crash (expected Pass)
language/class_modifiers/trans_legacy/legacy_superdeclaration_test DartkCrash (expected Pass)
```
are failing on configurations
```
cfe-strong-linux
cfe-weak-linux
vm-mac-debug-arm64
vm-mac-release-arm64
```

The front end *crashes* on the non-error test, because a type parameter of a generic interface is ["not indexed"](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8781680896648415457/+/u/test_results/new_test_failures__logs_):
```
/==================================================================================================================\
| language/class_modifiers/trans_legacy/legacy_superdeclaration_test is new and failed (DartkCrash, expected Pass) |
\==================================================================================================================/

--- Command "vm" (took 02.000492s):
DART_CONFIGURATION=DebugARM64 xcodebuild/DebugARM64/dart --sound-null-safety -Dtest_runner.configuration=vm-mac-debug-arm64 --enable-experiment=class-modifiers --ignore-unrecognized-flags --packages=/opt/s/w/ir/.dart_tool/package_config.json /opt/s/w/ir/tests/language/class_modifiers/trans_legacy/legacy_superdeclaration_test.dart

exit code:
252

stderr:
Invalid argument(s): Type parameter TypeParameter(Sink.T) is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:3425:8)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2576:38)
...
```
or is [referenced out of scope](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8781680896648415489/+/u/test_results/new_test_failures__logs_)
```
/============================================================================================================================\
| cfe-weak-linux:language/class_modifiers/trans_legacy/legacy_superdeclaration_test is new and failed (Crash, expected Pass) |
\============================================================================================================================/

--- Command "fasta" (took 173ms):
(cd /b/s/w/ir/cache/builder/sdk/ ; DART_CONFIGURATION=ReleaseX64 ./out/ReleaseX64/dart ./pkg/front_end/tool/_fasta/compile.dart --verify --skip-platform-verification -o ./out/ReleaseX64/generated_compilations/cfe-weak-linux/tests_language_class_modifiers_trans_legacy_legacy_superdeclaration_test/out.dill --platform ./out/ReleaseX64/vm_platform_strong.dill -Dtest_runner.configuration=cfe-weak-linux --enable-experiment=class-modifiers --packages=./.dart_tool/package_config.json ./tests/language/class_modifiers/trans_legacy/legacy_superdeclaration_test.dart )

exit code:
253

stdout:
sdk/lib/core/sink.dart:17:14: Error: Verification of the generated program failed:
Target=vm, VerificationStage.afterModularTransformations: Type parameter 'TypeParameter(Sink.T)' referenced out of scope, owner is: 'Class(Sink)'.
  void add(T data);
             ^
sdk/lib/core/sink.dart:17:14: Error: Verification of the generated program failed:
Target=vm, VerificationStage.afterModularTransformations: Type parameter 'TypeParameter(Sink.T)' referenced out of scope, owner is: 'Class(Sink)'.
  void add(T data);
             ^
sdk/lib/async/stream.dart:2225:30: Error: Verification of the generated program failed:
Target=vm, VerificationStage.afterModularTransformations: Type parameter 'TypeParameter(StreamConsumer.S)' referenced out of scope, owner is: 'Class(StreamConsumer)'.
  Future addStream(Stream<S> stream);
                             ^
sdk/lib/async/stream.dart:2225:30: Error: Verification of the generated program failed:
Target=vm, VerificationStage.afterModularTransformations: Type parameter 'TypeParameter(StreamConsumer.S)' referenced out of scope, owner is: 'Class(StreamConsumer)'.
  Future addStream(Stream<S> stream);
                             ^

stderr:
Unhandled exception:
  Invalid argument(s): Type parameter TypeParameter(Sink.T) is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:3425:8)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2576:38)
...
```

Smaller reproduction found. Does not appear to be related to class modifiers at all.
```dart
// lib1.dart
abstract mixin class MixesInMixin = Object with Iterable<int>;
```
and
```dart
// lib2.dart
import "lib1.dart";

abstract base class MixesInMixesInMixin extends Object with MixesInMixin {}

void main() {}
```
Run `dart lib2.dart` and it crashes with
```
Invalid argument(s): Type parameter TypeParameter(Iterable.E) is not indexed                                                                                                  
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:3425:8)                                                                                             
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2576:38)           
```

Run `pkg/front_end/tool/_fasta/compile.dart` and it gives a much longer error:
```
sdk/lib/core/iterable.dart:169:27: Error: Verification of the generated program failed:
Target=vm, VerificationStage.afterModularTransformations: Type parameter 'TypeParameter(Iterable.E)' referenced out of scope, owner is: 'Class(Iterable)'.
  Iterator<E> get iterator;
                          ^
sdk/lib/core/iterable.dart: Error: Verification of the generated program failed:
Target=vm, VerificationStage.afterModularTransformations: Type parameter 'TypeParameter(Iterable.E)' referenced out of scope, owner is: 'Class(Iterable)'.
sdk/lib/core/iterable.dart:193:38: Error: Verification of the generated program failed:
Target=vm, VerificationStage.afterModularTransformations: Type parameter 'TypeParameter(Iterable.E)' referenced out of scope, owner is: 'Class(Iterable)'.
  Iterable<E> followedBy(Iterable<E> other) {
                                     ^
...
```
and so on for every `Iterable` member.

Switching both libraries to `//@dart=2.19` and removing the `base` and `mixin` keywords yields the same errors.

Putting both classes in the same library removes the error.

**Comment by chloestefantsova** [comment]
> Putting both classes in the same library removes the error.

Thank you for the analysis, @lrhn! That observation was especially helpful. Turned out, the full mixin resolution transformation in the VM didn't account for the potential dependency of one mixin application to another, as it did so for a mixin application and its supertype. I added the missing bit in this CL: https://dart-review.googlesource.com/c/sdk/+/305320
