### ISSUE TITLE
Hot reloads crashes with FFI code

### ISSUE THREAD

**Issue by stevenosse** [dart-lang/sdk#52312]
I'm using https://pub.dev/packages/realm on a flutter app and i have issues with hot reload. Seems the Dart compiler has issues with ffi code

**Flutter doctor**
```shell
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [version 10.0.22621.1555], locale fr-FR)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[√] Android Studio (version 2022.2)
[√] IntelliJ IDEA Community Edition (version 2022.3)
[√] VS Code (version 1.78.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "windows_x64"**

**Stack trace**
```shell
Unhandled exception:
Crash when compiling:
type 'Block' is not a subtype of type 'ReturnStatement' in type cast

#0      RedirectingFactoryBody.restoreFromDill (package:front_end/src/fasta/kernel/redirecting_factory_body.dart:121:39)
#1      DillLibraryBuilder._addClass (package:front_end/src/fasta/dill/dill_library_builder.dart:202:34)

#2      List.forEach (dart:core-patch/growable_array.dart)
#3      DillLibraryBuilder.ensureLoaded (package:front_end/src/fasta/dill/dill_library_builder.dart:108:21)
#4      LazyLibraryScope.ensureScope (package:front_end/src/fasta/dill/dill_library_builder.dart:57:21)
#5      LazyScope._local (package:front_end/src/fasta/scope.dart:722:5)
#6      new ScopeNameIterator (package:front_end/src/fasta/scope.dart:1017:28)
#7      Scope.unfilteredNameIterator (package:front_end/src/fasta/scope.dart:146:16)
#8      Scope.filteredNameIterator (package:front_end/src/fasta/scope.dart:182:40)
#9      Import.finalizeImports (package:front_end/src/fasta/import.dart:78:60)

#10     SourceLibraryBuilder.addImportsToScope (package:front_end/src/fasta/source/source_library_builder.dart:1423:14)
#11     SourceLoader.computeLibraryScopes (package:front_end/src/fasta/source/source_loader.dart:1471:23)
#12     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:423:14)
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:136:24)
#14     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:406:12)
#15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:408:59)
<asynchronous suspension>
#16     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:68:50)
<asynchronous suspension>
#17     FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:847:52)
<asynchronous suspension>

the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Exited (1)

```

**Comment by stevenosse** [comment]
The problem was first encountered on a project using [realm](https://pub.dev/packages/realm) & [freezed](https://pub.dev/packages/freezed).

Issue created here: https://github.com/realm/realm-dart/issues/1268

I continued the analysis and the results have been documented here: https://github.com/realm/realm-dart/issues/1268#issuecomment-1540949242
