### ISSUE TITLE
Using a generic mixin with a record type does not run.

### ISSUE THREAD

**Issue by water-mizuu** [dart-lang/sdk#52339]
I discovered this while autogenerating code with regards to my personal library, which is a parsing library. Basically, the compiler goes haywire about `Invalid argument(s): Type parameter TypeParameter(Implementation.V1) is not indexed. ` I honestly have no idea if this is meant to happen.

Minimal reproducible example:
```dart
mixin GenericMixin<R> {}

class Implementation<V1> with GenericMixin<(V1,)> {}

void main() {
  Implementation<void> impl = new Implementation<void>();
}
```

The whole stdout log is:
```
Invalid argument(s): Type parameter TypeParameter(Implementation.V1) is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:3422:8)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2573:38)
#2      TypeParameterType.accept (package:kernel/ast.dart:13247:42)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#4      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#5      BinaryPrinter.visitRecordType (package:kernel/binary/ast_to_binary.dart:2557:5)
#6      RecordType.accept (package:kernel/ast.dart:13400:14)
#7      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#8      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#9      BinaryPrinter.visitSupertype (package:kernel/binary/ast_to_binary.dart:2525:7)
#10     Supertype.accept (package:kernel/ast.dart:13752:34)
#11     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#12     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#13     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1286:5)
#14     Class.accept (package:kernel/ast.dart:1481:38)
#15     BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:488:10)
#16     BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:374:7)
#17     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1126:5)
#18     Library.accept (package:kernel/ast.dart:587:38)
#19     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:467:10)
#20     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:780:9)
#21     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:619:7)
#22     Timeline.timeSync (dart:developer/timeline.dart:166:22)
#23     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:600:14)
#24     serializeComponent (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:1036:11)
#25     _processLoadRequest (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:947:41)
```

**Comment by mit-mit** [comment]
cc @lrhn @leafpetersen
