### ISSUE TITLE
RangeError on switch list pattern

### ISSUE THREAD

**Issue by TimWhiting** [dart-lang/sdk#52345]
* Dart SDK Version (`dart --version`)
Dart SDK version: 3.1.0-94.0.dev (dev) (Tue May 9 15:04:08 2023 -0700) on "linux_x64"

```dart
void main() {
  final works = ['b', 'l'];
  final fails = ['c'];

  for (final test in [works, fails]) {
    final _ = switch (test) {
      [final b, final d, ...final x] => print('$b $d $x'),
      [final f, ...final args] => print('$f $args'),
      _ => throw UnimplementedError(),
    };
  }
}

```

```sh
b l []
Unhandled exception:
RangeError (start): Invalid value: Not in inclusive range 0..1: 2
#0      RangeError.checkValidRange (dart:core/errors.dart:360:7)
#1      List.sublist (dart:core-patch/growable_array.dart:84:38)
#2      main.##0#6#initializer (file:///home/tim/tim_analysis/dart/syntax/example/test.dart:7:7)
#3      main (file:///home/tim/tim_analysis/dart/syntax/example/test.dart)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

A rest argument works in some cases, but not when preceded by another case with rest args but more positional arguments.

**Comment by lrhn** [comment]
Definitely a bug. For some reason the non-matching first case confuses the second case about how many elements there are.
Something is being cached incorrectly.
