### ISSUE TITLE
[vm] debug build MSAN fails

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52351]
```
$ tools/build.py --sanitizer=msan create_platform_sdk libdart_precompiler run_vm_tests

[...]

buildtools/ninja/ninja -C out/DebugMSANX64 -j1000 -l64 create_platform_sdk libdart_precompiler run_vm_tests
ninja: Entering directory `out/DebugMSANX64'
[5/227] ACTION //runtime/bin:generate_snapshot_bin(//build/toolchain/linux:clang_x64)
FAILED: gen/runtime/bin/vm_snapshot_data.bin gen/runtime/bin/vm_snapshot_instructions.bin gen/runtime/bin/isolate_snapshot_data.bin gen/runtime/bin/isolate_snapshot_instructions.bin 
python3 ../../build/gn_run_binary.py compiled_action gen_snapshot --sound-null-safety --deterministic --snapshot_kind=core --vm_snapshot_data=gen/runtime/bin/vm_snapshot_data.bin --vm_snapshot_instructions=gen/runtime/bin/vm_snapshot_instructions.bin --isolate_snapshot_data=gen/runtime/bin/isolate_snapshot_data.bin --isolate_snapshot_instructions=gen/runtime/bin/isolate_snapshot_instructions.bin vm_platform_strong_stripped.dill
Command failed: /usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugMSANX64/gen_snapshot --sound-null-safety --deterministic --snapshot_kind=core --vm_snapshot_data=gen/runtime/bin/vm_snapshot_data.bin --vm_snapshot_instructions=gen/runtime/bin/vm_snapshot_instructions.bin --isolate_snapshot_data=gen/runtime/bin/isolate_snapshot_data.bin --isolate_snapshot_instructions=gen/runtime/bin/isolate_snapshot_instructions.bin vm_platform_strong_stripped.dill
output: ==3990467==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55b3b75245e5 in dart::VMHandles::IsZoneHandle(unsigned long) ../../out/DebugMSANX64/../../runtime/vm/handles.cc:54:3
    #1 0x55b3b76a3e8d in dart::Object::IsZoneHandle() const ../../out/DebugMSANX64/../../runtime/vm/object.cc:2917:10
    #2 0x55b3b76a3e8d in dart::Object::IsNotTemporaryScopedHandle() const ../../out/DebugMSANX64/../../runtime/vm/object.cc:2925:11
    #3 0x55b3b82f03fc in dart::compiler::ObjectPoolBuilder::AddObject(dart::compiler::ObjectPoolBuilderEntry) ../../out/DebugMSANX64/../../runtime/vm/compiler/assembler/assembler_base.cc:406:3
    #4 0x55b3b82f1146 in dart::compiler::ObjectPoolBuilder::FindObject(dart::Object const&, dart::compiler::ObjectPoolBuilderEntry::Patchability) ../../out/DebugMSANX64/../../runtime/vm/compiler/assembler/assembler_base.cc:487:10
    #5 0x55b3b82f3f28 in dart::compiler::Assembler::Call(dart::Code const&) ../../out/DebugMSANX64/../../runtime/vm/compiler/assembler/assembler_x64.cc:85:46
    #6 0x55b3b87b8dc8 in dart::compiler::PushArrayOfArguments(dart::compiler::Assembler*) ../../out/DebugMSANX64/../../runtime/vm/compiler/stub_code_compiler_x64.cc:912:6
    #7 0x55b3b87b8b73 in dart::compiler::StubCodeCompiler::GenerateCallClosureNoSuchMethodStub() ../../out/DebugMSANX64/../../runtime/vm/compiler/stub_code_compiler_x64.cc:2200:3
    #8 0x55b3b7b5f52e in dart::StubCode::Generate(char const*, dart::compiler::ObjectPoolBuilder*, void (dart::compiler::StubCodeCompiler::*)()) ../../out/DebugMSANX64/../../runtime/vm/stub_code.cc:102:3
    #9 0x55b3b7b5ea87 in dart::StubCode::Init() ../../out/DebugMSANX64/../../runtime/vm/stub_code.cc:54:9
    #10 0x55b3b746d1a6 in dart::Dart::DartInit(Dart_InitializeParams const*) ../../out/DebugMSANX64/../../runtime/vm/dart.cc:458:7
    #11 0x55b3b746e009 in dart::Dart::Init(Dart_InitializeParams const*) ../../out/DebugMSANX64/../../runtime/vm/dart.cc:526:18
    #12 0x55b3b715bee8 in dart::bin::main(int, char**) ../../out/DebugMSANX64/../../runtime/bin/gen_snapshot.cc:934:11
    #13 0x7f0d38347189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #14 0x7f0d38347244 in __libc_start_main csu/../csu/libc-start.c:381:3
    #15 0x55b3b70cc419 in _start (/usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugMSANX64/gen_snapshot+0x6cb419)

SUMMARY: MemorySanitizer: use-of-uninitialized-value ../../out/DebugMSANX64/../../runtime/vm/handles.cc:54:3 in dart::VMHandles::IsZoneHandle(unsigned long)
Exiting

[6/227] LINK ./gen_snapshot_product
ninja: build stopped: subcommand failed.
```

**Comment by rmacnak-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/303145
