### ISSUE TITLE
Kernel verification error with sealed class constructor.

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#52359]
If `FileSystemEvent` is made `sealed` (see [#302452](https://dart-review.googlesource.com/c/sdk/+/302452) then the dart2js build fails with:

```
output: Unhandled exception:
org-dartlang-sdk:///lib/io/file_system_entity.dart:916:3: Verification error: Target=dart2js, VerificationStage.afterModularTransformations: ConstructorInvocation of abstract class.
#0      VerificationErrorListener.reportError (package:kernel/verifier.dart:82:5)
#1      VerifyingVisitor.problem (package:kernel/verifier.dart:219:14)
#2      VerifyingVisitor.visitConstructorInvocation (package:kernel/verifier.dart:928:7)
#3      ConstructorInvocation.accept (package:kernel/ast.dart:7131:44)
#4      ReturnStatement.visitChildren (package:kernel/ast.dart:10832:17)
#5      VerifyingVisitor.visitChildren (package:kernel/verifier.dart:256:10)
#6      VerifyingVisitor.defaultTreeNode (package:kernel/verifier.dart:193:5)
#7      TreeVisitor.defaultStatement (package:kernel/visitor.dart:421:41)
#8      TreeVisitor.visitReturnStatement (package:kernel/visitor.dart:458:51)
#9      VerifyingVisitor.visitReturnStatement (package:kernel/verifier.dart:737:11)
#10     ReturnStatement.accept (package:kernel/ast.dart:10824:43)
#11     FunctionNode.visitChildren (package:kernel/ast.dart:4223:11)
#12     VerifyingVisitor.visitChildren (package:kernel/verifier.dart:256:10)
#13     VerifyingVisitor.visitWithLocalScope (package:kernel/verifier.dart:263:5)
#14     VerifyingVisitor.visitFunctionNode (package:kernel/verifier.dart:629:5)
#15     FunctionNode.accept (package:kernel/ast.dart:4210:38)
#16     VerifyingVisitor.visitProcedure (package:kernel/verifier.dart:535:19)
#17     Procedure.accept (package:kernel/ast.dart:3590:40)
#18     visitList (package:kernel/ast.dart:15263:14)
#19     VerifyingVisitor.visitClass (package:kernel/verifier.dart:608:5)
#20     Class.accept (package:kernel/ast.dart:1481:38)
#21     visitList (package:kernel/ast.dart:15263:14)
#22     Library.visitChildren (package:kernel/ast.dart:598:5)
#23     VerifyingVisitor.visitChildren (package:kernel/verifier.dart:256:10)
#24     VerifyingVisitor.defaultTreeNode (package:kernel/verifier.dart:193:5)
#25     TreeVisitor.visitLibrary (package:kernel/visitor.dart:513:35)
#26     VerifyingVisitor.visitLibrary (package:kernel/verifier.dart:364:11)
#27     Library.accept (package:kernel/ast.dart:587:38)
#28     visitList (package:kernel/ast.dart:15263:14)
#29     Component.visitChildren (package:kernel/ast.dart:15095:5)
#30     VerifyingVisitor.visitChildren (package:kernel/verifier.dart:256:10)
#31     VerifyingVisitor.visitComponent (package:kernel/verifier.dart:339:7)
#32     Component.accept (package:kernel/ast.dart:15088:38)
#33     VerifyingVisitor.check (package:kernel/verifier.dart:168:15)
#34     verifyComponent (package:kernel/verifier.dart:70:20)
#35     compilePlatformInternal (file:///Users/bquinlan/dart/dart-sdk1/sdk/pkg/front_end/tool/_fasta/entry_points.dart:521:3)
<asynchronous suspension>
#36     compilePlatform (file:///Users/bquinlan/dart/dart-sdk1/sdk/pkg/front_end/tool/_fasta/entry_points.dart:492:3)
<asynchronous suspension>
#37     runProtectedFromAbort (file:///Users/bquinlan/dart/dart-sdk1/sdk/pkg/front_end/tool/_fasta/command_line.dart:416:12)
<asynchronous suspension>
#38     compilePlatformEntryPoint (file:///Users/bquinlan/dart/dart-sdk1/sdk/pkg/front_end/tool/_fasta/entry_points.dart:148:5)
<asynchronous suspension>
```

This is not correct behavior - subclasses can invoke the constructor of their `sealed` parent.

I'm trying to make it sealed as part of https://github.com/dart-lang/sdk/issues/51912 and this is blocking me.

**Comment by brianquinlan** [comment]
@kallentu since you seem to be active in this area (I'm not familiar with the front end). Feel free to reassign.

**Comment by aam** [comment]
Looking at dill files I see tearoff generated for `sealed` class. Not sure whether that is what triggers verification failure
`**final** class FileSystemEvent {`` results in
```
abstract class FileSystemEvent extends core::Object { // from org-dartlang-sdk:///lib/io/file_system_entity.dart
    static const field core::int create = #C2;
    static const field core::int modify = #C3;
    static const field core::int delete = #C103;
    static const field core::int move = #C106;
    static const field core::int all = #C185;
    static const field core::int _modifyAttributes = #C181;
    static const field core::int _deleteSelf = #C231;
    static const field core::int _isDir = #C382;
    final field core::int type;
    final field core::String path;
    final field core::bool isDirectory;
    constructor foo(core::int type, core::String path, core::bool isDirectory) → io::FileSystemEvent
      : io::FileSystemEvent::type = type, io::FileSystemEvent::path = path, io::FileSystemEvent::isDirectory = isDirectory, super core::Object::•()
      ;
  }
  
while `**sealed** class FileSystemEvent {`  results in 
  
```
  abstract sealed class FileSystemEvent extends core::Object { // from org-dartlang-sdk:///lib/io/file_system_entity.dart
    static const field core::int create = #C2;
    static const field core::int modify = #C3;
    static const field core::int delete = #C103;
    static const field core::int move = #C106;
    static const field core::int all = #C185;
    static const field core::int _modifyAttributes = #C181;
    static const field core::int _deleteSelf = #C231;
    static const field core::int _isDir = #C382;
    final field core::int type;
    final field core::String path;
    final field core::bool isDirectory;
    constructor foo(core::int type, core::String path, core::bool isDirectory) → io::FileSystemEvent
      : io::FileSystemEvent::type = type, io::FileSystemEvent::path = path, io::FileSystemEvent::isDirectory = isDirectory, super core::Object::•()
      ;
    **static method _#foo#tearOff(core::int type, core::String path, core::bool isDirectory) → io::FileSystemEvent
      return new io::FileSystemEvent::foo(type, path, isDirectory);
  }**
```

**Comment by kallentu** [comment]
@johnniwinther Do you have a better idea of what's happening here, why this could potentially be generating this error?
