### ISSUE TITLE
Missing implementation of visitPatternAssignment during linking

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#52360]
```
Exception: Missing implementation of visitPatternAssignment
#0      ThrowingAstVisitor._throw (package:analyzer/dart/ast/visitor.dart:2842:5)
#1      ThrowingAstVisitor.visitPatternAssignment (package:analyzer/dart/ast/visitor.dart:2663:56)
#2      PatternAssignmentImpl.accept (package:analyzer/src/dart/ast/ast.dart:10421:50)
#3      AstBinaryWriter._writeNode (package:analyzer/src/summary2/ast_binary_writer.dart:933:10)
#4      AstBinaryWriter.visitNamedExpression (package:analyzer/src/summary2/ast_binary_writer.dart:512:5)
#5      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:9311:50)
#6      AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:939:19)
#7      AstBinaryWriter.visitArgumentList (package:analyzer/src/summary2/ast_binary_writer.dart:55:5)
#8      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:398:50)
#9      AstBinaryWriter._writeNode (package:analyzer/src/summary2/ast_binary_writer.dart:933:10)
#10     AstBinaryWriter._writeOptionalNode (package:analyzer/src/summary2/ast_binary_writer.dart:948:7)
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/302882
