### ISSUE TITLE
type 'InterfaceScope' is not a subtype of type 'LocalScope' in type cast

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#52363]
```
type 'InterfaceScope' is not a subtype of type 'LocalScope' in type cast
#0      ResolutionVisitor._define (package:analyzer/src/dart/resolver/resolution_visitor.dart:1469:17)
#1      ResolutionVisitor.visitDeclaredVariablePattern (package:analyzer/src/dart/resolver/resolution_visitor.dart:409:5)
#2      DeclaredVariablePatternImpl.accept (package:analyzer/src/dart/ast/ast.dart:3662:15)
#3      ParenthesizedPatternImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10231:13)
#4      RecursiveAstVisitor.visitParenthesizedPattern (package:analyzer/dart/ast/visitor.dart:1435:10)
#5      ParenthesizedPatternImpl.accept (package:analyzer/src/dart/ast/ast.dart:10214:15)
#6      PatternAssignmentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10430:13)
#7      RecursiveAstVisitor.visitPatternAssignment (package:analyzer/dart/ast/visitor.dart:1453:10)
#8      ResolutionVisitor.visitPatternAssignment (package:analyzer/src/dart/resolver/resolution_visitor.dart:1074:11)
#9      PatternAssignmentImpl.accept (package:analyzer/src/dart/ast/ast.dart:10421:50)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9616:20)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:402:16)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:793:10)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:398:50)
#14     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9088:19)
#15     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1363:10)
#16     ResolutionVisitor.visitMethodInvocation (package:analyzer/src/dart/resolver/resolution_visitor.dart:1011:11)
#17     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:9076:50)
#18     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9321:17)
#19     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1375:10)
#20     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:9311:50)
#21     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9616:20)
#22     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:402:16)
#23     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:793:10)
#24     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:398:50)
#25     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7602:19)
#26     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:1255:10)
#27     ResolutionVisitor.visitInstanceCreationExpression (package:analyzer/src/dart/resolver/resolution_visitor.dart:912:11)
#28     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7591:15)
#29     ResolutionVisitor.visitMethodInvocation (package:analyzer/src/dart/resolver/resolution_visitor.dart:1008:22)
#30     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:9076:50)
#31     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9321:17)
#32     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1375:10)
#33     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:9311:50)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9616:20)
#35     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:402:16)
#36     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:793:10)
#37     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:398:50)
#38     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7602:19)
#39     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:1255:10)
#40     ResolutionVisitor.visitInstanceCreationExpression (package:analyzer/src/dart/resolver/resolution_visitor.dart:912:11)
#41     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7591:15)
#42     ResolutionVisitor.visitMethodInvocation (package:analyzer/src/dart/resolver/resolution_visitor.dart:1008:22)
#43     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:9076:50)
#44     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9321:17)
#45     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1375:10)
#46     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:9311:50)
#47     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9616:20)
#48     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:402:16)
#49     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:793:10)
#50     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:398:50)
#51     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7602:19)
#52     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:1255:10)
#53     ResolutionVisitor.visitInstanceCreationExpression (package:analyzer/src/dart/resolver/resolution_visitor.dart:912:11)
#54     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7591:15)
#55     ResolutionVisitor.visitMethodInvocation (package:analyzer/src/dart/resolver/resolution_visitor.dart:1008:22)
#56     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:9076:50)
#57     AstResolver.resolveExpression (package:analyzer/src/summary2/ast_resolver.dart:96:10)
#58     _PropertyInducingElementTypeInference.perform (package:analyzer/src/summary2/top_level_inference.dart:251:17)
#59     PropertyInducingElementImpl.typeInternal (package:analyzer/src/dart/element/element.dart:6146:28)
#60     ElementTypeProvider.getFieldType (package:analyzer/src/generated/element_type_provider.dart:62:15)
#61     PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:6108:52)
#62     _InitializerInference.perform (package:analyzer/src/summary2/top_level_inference.dart:148:15)
#63     TopLevelInference.infer (package:analyzer/src/summary2/top_level_inference.dart:102:26)
#64     Linker._performTopLevelInference (package:analyzer/src/summary2/link.dart:256:29)
#65     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:135:5)
<asynchronous suspension>
#66     Linker.link (package:analyzer/src/summary2/link.dart:95:5)
<asynchronous suspension>
#67     link (package:analyzer/src/summary2/link.dart:38:3)
<asynchronous suspension>
#68     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:180:24)
<asynchronous suspension>
#69     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:246:7)
<asynchronous suspension>
#70     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#71     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:244:5)
<asynchronous suspension>
#72     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1335:9)
<asynchronous suspension>
#73     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#74     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1055:24)
<asynchronous suspension>
#75     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:7)
<asynchronous suspension>


#0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:321:5)
#1      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:188:11)
<asynchronous suspension>
#2      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:246:7)
<asynchronous suspension>
#3      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#4      LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:244:5)
<asynchronous suspension>
#5      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1335:9)
<asynchronous suspension>
#6      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1055:24)
<asynchronous suspension>
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:7)
```

**Comment by scheglov** [comment]
```dart
class A {
  const a = (var b,) = (0,);
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/369505
