### ISSUE TITLE
Compiler crashed when building flutter app

### ISSUE THREAD

**Issue by Mufaddal1125** [dart-lang/sdk#52382]
Dart version -> Dart SDK version: 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "windows_x64"
OS -> Windows x64
Using -> Edge

Logs:-
```
Target dart2js failed: Exception: ../../AppData/Local/Pub/Cache/git/searchable_dropdown-62915c21b3814d9b050ba3fd3adf88a0eabe1338/lib/dropdown_search.dart:668:27:
Warning: Operand of null-aware operation '!' has type 'OverlayState' which excludes null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/overlay.dart').
    var overlay = Overlay.of(context)!.context.findRenderObject() as RenderBox;
                          ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/carousel_slider-4.2.1/lib/carousel_slider.dart:358:33:
Warning: Operand of null-aware operation '?.' has type 'PageStorageBucket' which excludes null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
                    PageStorage.of(storageContext)?.readState(storageContext)
                                ^
../../AppData/Local/Pub/Cache/git/zefyrka-11663d07bcc690a9ca2e86b3507bec81ab80aa56/lib/src/widgets/editor.dart:1067:47:
Warning: Operand of null-aware operation '!' has type 'RenderAbstractViewport' which excludes null.
 - 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('/C:/flutter/packages/flutter/lib/src/rendering/viewport.dart').
      final viewport = RenderAbstractViewport.of(renderEditor)!;
                                              ^
../../AppData/Local/Pub/Cache/git/data_table_2-49320e147b0c4beb3ae482cf0b34339975bc370b/lib/src/paginated_data_table_2.dart:498:34:
Warning: Operand of null-aware operation '?.' has type 'PageStorageBucket' which excludes null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
    _firstRowIndex = PageStorage.of(context)?.readState(context) as int? ??
                                 ^
../../AppData/Local/Pub/Cache/git/html-editor-enhanced-98d6f18f3d12f61dc8078e7e44fd1625e5bcd231/lib/src/widgets/html_editor_widget_web.dart:518:26:
Warning: Operand of null-aware operation '!' has type 'ScrollableState' which excludes null.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/scrollable.dart').
              Scrollable.of(context)!.position.ensureVisible(
                         ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/emoji_picker_flutter-1.5.4/lib/src/skin_tone_overlay.dart:72:15:
Warning: Operand of null-aware operation '?.' has type 'OverlayState' which excludes null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/overlay.dart').
      Overlay.of(context)?.insert(_overlay!);
              ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/infinite_listview-1.1.0/lib/infinite_listview.dart:162:36:
Warning: Operand of null-aware operation '!' has type 'ScrollableState' which excludes null.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/scrollable.dart').
          final state = Scrollable.of(context)!;
                                   ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/flex_color_picker-2.6.1/lib/src/universal_widgets/context_popup_menu.dart:136:17:
Warning: Operand of null-aware operation '?.' has type 'OverlayState' which excludes null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/overlay.dart').
        Overlay.of(context)?.context.findRenderObject() as RenderBox?;
                ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/drag_and_drop_lists-0.3.3/lib/programmatic_expansion_tile.dart:131:31:
Warning: Operand of null-aware operation '?.' has type 'PageStorageBucket' which excludes null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
    _isExpanded = PageStorage.of(context)
                              ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/drag_and_drop_lists-0.3.3/lib/programmatic_expansion_tile.dart:178:21:
Warning: Operand of null-aware operation '?.' has type 'PageStorageBucket' which excludes null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
        PageStorage.of(context)
                    ^
.dart_tool/flutter_build/308b6816ae28c43222f95f97f433225f/main.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.0.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Crash when compiling:
type 'Null' is not a subtype of type 'FunctionType' in type cast

#0      CloneVisitorNotMembers.visitInstanceGetterInvocation (package:kernel/clone.dart:834:60)
#1      InstanceGetterInvocation.accept (package:kernel/ast.dart:6302:44)
#2      CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#3      CloneVisitorNotMembers.visitLet (package:kernel/clone.dart:426:33)
#4      Let.accept (package:kernel/ast.dart:9277:44)
#5      CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#6      CloneVisitorNotMembers.visitLet (package:kernel/clone.dart:426:33)
#7      Let.accept (package:kernel/ast.dart:9277:44)
#8      CloneVisitorNotMembers.cloneOptional (package:kernel/clone.dart:128:29)
#9      CloneVisitorNotMembers.visitReturnStatement (package:kernel/clone.dart:548:32)
#10     ListGenerateLoopBodyInliner.visitReturnStatement (package:compiler/src/kernel/transformations/list_factory_specializer.dart:308:48)
#11     ReturnStatement.accept (package:kernel/ast.dart:10786:43)
#12     CloneVisitorNotMembers.cloneOptional (package:kernel/clone.dart:128:29)
#13     CloneVisitorNotMembers.cloneFunctionNodeBody (package:kernel/clone.dart:632:14)
#14     CloneVisitorNotMembers.visitFunctionNode (package:kernel/clone.dart:648:29)
#15     ListGenerateLoopBodyInliner.visitFunctionNode (package:compiler/src/kernel/transformations/list_factory_specializer.dart:353:26)
#16     FunctionNode.accept (package:kernel/ast.dart:4198:38)
#17     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#18     CloneVisitorNotMembers.visitFunctionExpression (package:kernel/clone.dart:389:35)
#19     FunctionExpression.accept (package:kernel/ast.dart:9166:44)
#20     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#21     CloneVisitorNotMembers.visitNamedExpression (package:kernel/clone.dart:669:43)
#22     NamedExpression.accept (package:kernel/ast.dart:5821:38)
#23     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#24     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#25     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#26     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#27     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#28     new List.of (dart:core-patch/array_patch.dart:47:28)
#29     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#30     CloneVisitorNotMembers.visitArguments (package:kernel/clone.dart:664:38)
#31     Arguments.accept (package:kernel/ast.dart:5746:38)
#32     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#33     CloneVisitorNotMembers.visitConstructorInvocation (package:kernel/clone.dart:240:31)
#34     ConstructorInvocation.accept (package:kernel/ast.dart:7119:44)
#35     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#36     CloneVisitorNotMembers.visitNamedExpression (package:kernel/clone.dart:669:43)
#37     NamedExpression.accept (package:kernel/ast.dart:5821:38)
#38     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#39     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#40     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#41     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#42     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#43     new List.of (dart:core-patch/array_patch.dart:47:28)
#44     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#45     CloneVisitorNotMembers.visitArguments (package:kernel/clone.dart:664:38)
#46     Arguments.accept (package:kernel/ast.dart:5746:38)
#47     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#48     CloneVisitorNotMembers.visitConstructorInvocation (package:kernel/clone.dart:240:31)
#49     ConstructorInvocation.accept (package:kernel/ast.dart:7119:44)
#50     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#51     CloneVisitorNotMembers.visitNamedExpression (package:kernel/clone.dart:669:43)
#52     NamedExpression.accept (package:kernel/ast.dart:5821:38)
#53     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#54     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#55     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#56     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#57     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#58     new List.of (dart:core-patch/array_patch.dart:47:28)
#59     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#60     CloneVisitorNotMembers.visitArguments (package:kernel/clone.dart:664:38)
#61     Arguments.accept (package:kernel/ast.dart:5746:38)
#62     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#63     CloneVisitorNotMembers.visitConstructorInvocation (package:kernel/clone.dart:240:31)
#64     ConstructorInvocation.accept (package:kernel/ast.dart:7119:44)
#65     CloneVisitorNotMembers.cloneOptional (package:kernel/clone.dart:128:29)
#66     CloneVisitorNotMembers.visitReturnStatement (package:kernel/clone.dart:548:32)
#67     ListGenerateLoopBodyInliner.visitReturnStatement (package:compiler/src/kernel/transformations/list_factory_specializer.dart:308:48)
#68     ReturnStatement.accept (package:kernel/ast.dart:10786:43)
#69     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#70     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#71     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#72     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#73     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#74     new List.of (dart:core-patch/array_patch.dart:47:28)
#75     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#76     CloneVisitorNotMembers.visitBlock (package:kernel/clone.dart:453:49)
#77     Block.accept (package:kernel/ast.dart:9771:43)
#78     CloneVisitorNotMembers.cloneOptional (package:kernel/clone.dart:128:29)
#79     CloneVisitorNotMembers.cloneFunctionNodeBody (package:kernel/clone.dart:632:14)
#80     CloneVisitorNotMembers.visitFunctionNode (package:kernel/clone.dart:648:29)
#81     ListGenerateLoopBodyInliner.visitFunctionNode (package:compiler/src/kernel/transformations/list_factory_specializer.dart:353:26)
#82     FunctionNode.accept (package:kernel/ast.dart:4198:38)
#83     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#84     CloneVisitorNotMembers.visitFunctionExpression (package:kernel/clone.dart:389:35)
#85     FunctionExpression.accept (package:kernel/ast.dart:9166:44)
#86     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#87     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#88     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#89     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#90     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#91     new List.of (dart:core-patch/array_patch.dart:47:28)
#92     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#93     CloneVisitorNotMembers.visitArguments (package:kernel/clone.dart:662:53)
#94     Arguments.accept (package:kernel/ast.dart:5746:38)
#95     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#96     CloneVisitorNotMembers.visitStaticInvocation (package:kernel/clone.dart:233:31)
#97     StaticInvocation.accept (package:kernel/ast.dart:7029:44)
#98     CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#99     CloneVisitorNotMembers.visitInstanceInvocation (package:kernel/clone.dart:824:20)
#100    InstanceInvocation.accept (package:kernel/ast.dart:6128:44)
#101    CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#102    CloneVisitorNotMembers.visitNamedExpression (package:kernel/clone.dart:669:43)
#103    NamedExpression.accept (package:kernel/ast.dart:5821:38)
#104    CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#105    MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#106    ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#107    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#108    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#109    new List.of (dart:core-patch/array_patch.dart:47:28)
#110    ListIterable.toList (dart:_internal/iterable.dart:214:7)
#111    CloneVisitorNotMembers.visitArguments (package:kernel/clone.dart:664:38)
#112    Arguments.accept (package:kernel/ast.dart:5746:38)
#113    CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#114    CloneVisitorNotMembers.visitConstructorInvocation (package:kernel/clone.dart:240:31)
#115    ConstructorInvocation.accept (package:kernel/ast.dart:7119:44)
#116    CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#117    ListGenerateLoopBodyInliner.visitReturnStatement (package:compiler/src/kernel/transformations/list_factory_specializer.dart:326:56)
#118    ReturnStatement.accept (package:kernel/ast.dart:10786:43)
#119    CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#120    MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#121    ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#122    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#123    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#124    new List.of (dart:core-patch/array_patch.dart:47:28)
#125    ListIterable.toList (dart:_internal/iterable.dart:214:7)
#126    CloneVisitorNotMembers.visitBlock (package:kernel/clone.dart:453:49)
#127    Block.accept (package:kernel/ast.dart:9771:43)
#128    CloneVisitorNotMembers.clone (package:kernel/clone.dart:116:34)
#129    CloneVisitorNotMembers.cloneInContext (package:kernel/clone.dart:139:29)
#130    ListGenerateLoopBodyInliner.run (package:compiler/src/kernel/transformations/list_factory_specializer.dart:301:22)
#131    ListFactorySpecializer._loopBody (package:compiler/src/kernel/transformations/list_factory_specializer.dart:182:20)
#132    ListFactorySpecializer.transformListGenerateFactory (package:compiler/src/kernel/transformations/list_factory_specializer.dart:161:7)
#133    FactorySpecializer.transformStaticInvocation (package:compiler/src/kernel/transformations/factory_specializer.dart:31:25)
#134    _Lowering.visitStaticInvocation (package:compiler/src/kernel/transformations/lowering.dart:57:31)
#135    StaticInvocation.accept (package:kernel/ast.dart:7029:44)
#136    Transformer.transform (package:kernel/visitor.dart:1801:21)
#137    InstanceInvocation.transformChildren (package:kernel/ast.dart:6147:20)
#138    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#139    TreeVisitor.defaultExpression (package:kernel/visitor.dart:229:43)
#140    TreeVisitor.visitInstanceInvocation (package:kernel/visitor.dart:274:57)
#141    InstanceInvocation.accept (package:kernel/ast.dart:6128:44)
#142    Transformer.transform (package:kernel/visitor.dart:1801:21)
#143    Transformer.transformList (package:kernel/visitor.dart:1836:18)
#144    Arguments.transformChildren (package:kernel/ast.dart:5761:7)
#145    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#146    TreeVisitor.visitArguments (package:kernel/visitor.dart:520:39)
#147    Arguments.accept (package:kernel/ast.dart:5746:38)
#148    Transformer.transform (package:kernel/visitor.dart:1801:21)
#149    StaticInvocation.transformChildren (package:kernel/ast.dart:7045:21)
#150    _Lowering.visitStaticInvocation (package:compiler/src/kernel/transformations/lowering.dart:56:10)
#151    StaticInvocation.accept (package:kernel/ast.dart:7029:44)
#152    Transformer.transform (package:kernel/visitor.dart:1801:21)
#153    VariableDeclaration.transformChildren (package:kernel/ast.dart:11422:23)
#154    _Lowering.visitVariableDeclaration (package:compiler/src/kernel/transformations/lowering.dart:72:10)
#155    VariableDeclaration.accept (package:kernel/ast.dart:11404:43)
#156    Transformer.transform (package:kernel/visitor.dart:1801:21)
#157    Transformer.transformList (package:kernel/visitor.dart:1836:18)
#158    Block.transformChildren (package:kernel/ast.dart:9783:7)
#159    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#160    TreeVisitor.defaultStatement (package:kernel/visitor.dart:421:41)
#161    TreeVisitor.visitBlock (package:kernel/visitor.dart:426:31)
#162    Block.accept (package:kernel/ast.dart:9771:43)
#163    Transformer.transform (package:kernel/visitor.dart:1801:21)
#164    BlockExpression.transformChildren (package:kernel/ast.dart:9364:16)
#165    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#166    TreeVisitor.defaultExpression (package:kernel/visitor.dart:229:43)
#167    TreeVisitor.visitBlockExpression (package:kernel/visitor.dart:356:51)
#168    BlockExpression.accept (package:kernel/ast.dart:9348:44)
#169    Transformer.transform (package:kernel/visitor.dart:1801:21)
#170    NamedExpression.transformChildren (package:kernel/ast.dart:5836:17)
#171    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#172    TreeVisitor.visitNamedExpression (package:kernel/visitor.dart:521:51)
#173    NamedExpression.accept (package:kernel/ast.dart:5821:38)
#174    Transformer.transform (package:kernel/visitor.dart:1801:21)
#175    Transformer.transformList (package:kernel/visitor.dart:1836:18)
#176    Arguments.transformChildren (package:kernel/ast.dart:5762:7)
#177    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#178    TreeVisitor.visitArguments (package:kernel/visitor.dart:520:39)
#179    Arguments.accept (package:kernel/ast.dart:5746:38)
#180    Transformer.transform (package:kernel/visitor.dart:1801:21)
#181    ConstructorInvocation.transformChildren (package:kernel/ast.dart:7135:21)
#182    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#183    TreeVisitor.defaultExpression (package:kernel/visitor.dart:229:43)
#184    TreeVisitor.visitConstructorInvocation (package:kernel/visitor.dart:292:7)
#185    ConstructorInvocation.accept (package:kernel/ast.dart:7119:44)
#186    Transformer.transform (package:kernel/visitor.dart:1801:21)
#187    NamedExpression.transformChildren (package:kernel/ast.dart:5836:17)
#188    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#189    TreeVisitor.visitNamedExpression (package:kernel/visitor.dart:521:51)
#190    NamedExpression.accept (package:kernel/ast.dart:5821:38)
#191    Transformer.transform (package:kernel/visitor.dart:1801:21)
#192    Transformer.transformList (package:kernel/visitor.dart:1836:18)
#193    Arguments.transformChildren (package:kernel/ast.dart:5762:7)
#194    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#195    TreeVisitor.visitArguments (package:kernel/visitor.dart:520:39)
#196    Arguments.accept (package:kernel/ast.dart:5746:38)
#197    Transformer.transform (package:kernel/visitor.dart:1801:21)
#198    ConstructorInvocation.transformChildren (package:kernel/ast.dart:7135:21)
#199    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#200    TreeVisitor.defaultExpression (package:kernel/visitor.dart:229:43)
#201    TreeVisitor.visitConstructorInvocation (package:kernel/visitor.dart:292:7)
#202    ConstructorInvocation.accept (package:kernel/ast.dart:7119:44)
#203    Transformer.transform (package:kernel/visitor.dart:1801:21)
#204    ReturnStatement.transformChildren (package:kernel/ast.dart:10800:22)
#205    _Lowering.visitReturnStatement (package:compiler/src/kernel/transformations/lowering.dart:105:15)
#206    ReturnStatement.accept (package:kernel/ast.dart:10786:43)
#207    Transformer.transform (package:kernel/visitor.dart:1801:21)
#208    Transformer.transformList (package:kernel/visitor.dart:1836:18)
#209    Block.transformChildren (package:kernel/ast.dart:9783:7)
#210    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#211    TreeVisitor.defaultStatement (package:kernel/visitor.dart:421:41)
#212    TreeVisitor.visitBlock (package:kernel/visitor.dart:426:31)
#213    Block.accept (package:kernel/ast.dart:9771:43)
#214    Transformer.transform (package:kernel/visitor.dart:1801:21)
#215    FunctionNode.transformChildren (package:kernel/ast.dart:4224:16)
#216    _Lowering.visitFunctionNode (package:compiler/src/kernel/transformations/lowering.dart:64:10)
#217    FunctionNode.accept (package:kernel/ast.dart:4198:38)
#218    Transformer.transform (package:kernel/visitor.dart:1801:21)
#219    Procedure.transformChildren (package:kernel/ast.dart:3611:20)
#220    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#221    TreeVisitor.defaultMember (package:kernel/visitor.dart:477:35)
#222    _Lowering.defaultMember (package:compiler/src/kernel/transformations/lowering.dart:44:18)
#223    TreeVisitor.visitProcedure (package:kernel/visitor.dart:481:39)
#224    Procedure.accept (package:kernel/ast.dart:3590:40)
#225    Transformer.transform (package:kernel/visitor.dart:1801:21)
#226    Transformer.transformList (package:kernel/visitor.dart:1836:18)
#227    Class.transformChildren (package:kernel/ast.dart:1536:7)
#228    Transformer.defaultTreeNode (package:kernel/visitor.dart:1858:10)
#229    TreeVisitor.visitClass (package:kernel/visitor.dart:490:31)
#230    Class.accept (package:kernel/ast.dart:1481:38)
#231    Transformer.transform (package:kernel/visitor.dart:1801:21)
#232    Transformer.transformList (package:kernel/visitor.dart:1836:18)
#233    Library.transformChildren (package:kernel/ast.dart:611:7)
#234    _Lowering.visitLibrary (package:compiler/src/kernel/transformations/lowering.dart:49:10)
#235    List.forEach (dart:core-patch/growable_array.dart:416:8)
#236    transformLibraries (package:compiler/src/kernel/transformations/lowering.dart:22:13)
#237    Dart2jsTarget.performModularTransformationsOnLibraries (package:compiler/src/kernel/dart2js_target.dart:173:14)
#238    KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1568:19)
#239    KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:638:7)
<asynchronous suspension>
#240    withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#241    _buildInternal (package:front_end/src/kernel_generator_impl.dart:207:19)
<asynchronous suspension>
#242    withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#243    compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:201:37)
<asynchronous suspension>
#244    compile (package:front_end/src/api_unstable/dart2js.dart:199:36)
<asynchronous suspension>
#245    _loadFromSource (package:compiler/src/phase/load_kernel.dart:299:29)
<asynchronous suspension>
#246    run (package:compiler/src/phase/load_kernel.dart:400:36)
<asynchronous suspension>
#247    Compiler.loadKernel (package:compiler/src/compiler.dart:395:9)
<asynchronous suspension>
#248    Compiler.produceKernel (package:compiler/src/compiler.dart:402:36)
<asynchronous suspension>
#249    Compiler.runSequentialPhases (package:compiler/src/compiler.dart:743:20)
<asynchronous suspension>
#250    Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:319:7)
<asynchronous suspension>
#251    Compiler.runInternal (package:compiler/src/compiler.dart:318:5)
<asynchronous suspension>
#252    Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:239:11)
<asynchronous suspension>
#253    main (package:compiler/src/dart2js.dart:1473:3)
<asynchronous suspension>



#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:212:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#7      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:81:34)
<asynchronous suspension>
#8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:191:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

Compiling lib\main.dart for the Web...                             26.8s
Exception: Failed to compile application for the Web.
```

**Comment by Mufaddal1125** [comment]
seems like crash is happening in kernel package
`#0      CloneVisitorNotMembers.visitInstanceGetterInvocation (package:kernel/clone.dart:834:60)`

**Comment by sigmundch** [comment]
Thanks for the report - it appears to also be the same issue as #52403 

Seems @fishythefish has a fix underway in https://dart-review.googlesource.com/c/sdk/+/303420.

I'll close this issue and keep the other one to track progress.
