### ISSUE TITLE
Records do not not work with parameterized constant class

### ISSUE THREAD

**Issue by Pante** [dart-lang/sdk#52385]
Dart: 3.0.0

Generic records currently do not work with constant constructors. If it's intended, the error should also be emitted at the constructor rather than only at the call-site.

```dart
class Foo<T> {
  final T a;

  const Foo(T a): a = a;
}

class Generic<T> {
  final (T a, T b) record;

  const Generic(T a): record = (a, a);
}

class NotGeneric {
  final (int a, int b) record;

  const NotGeneric(int a): record = (a, a);
}

void main() {
  const Foo(1); // Works
  const Generic(1); // Errors with: 'In a const constructor, a value of type '(T, T)' can't be assigned to the field 'record', which has type '(int, int)'.'
  const Generic<int>(1);  // Same error
  const NotGeneric(1); // Works
}
```

**Comment by eernstg** [comment]
Looks like an analyzer bug.

**Comment by scheglov** [comment]
IIRC @bwilkerson implemented records support for constant evaluation.

**Comment by scheglov** [comment]
Ah, it looks simple enough, I can fix it.

**Comment by scheglov** [comment]
Hm... Interestingly, CFE also has an issue with this code. @johnniwinther 
```
Invalid argument(s): Type parameter TypeParameter(Generic.T) is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:3425:8)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2576:38)
#2      TypeParameterType.accept (package:kernel/ast.dart:13285:42)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:448:10)
#4      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:349:7)
#5      BinaryPrinter.visitRecordType (package:kernel/binary/ast_to_binary.dart:2560:5)
#6      RecordType.accept (package:kernel/ast.dart:13438:14)
#7      BinaryPrinter.writeDartType (package:kernel/binary/ast_to_binary.dart:318:10)
#8      BinaryPrinter.writeConstantTableEntry (package:kernel/binary/ast_to_binary.dart:309:7)
#9      BinaryPrinter.writeConstantTable (package:kernel/binary/ast_to_binary.dart:200:7)
#10     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:624:7)
#11     Timeline.timeSync (dart:developer/timeline.dart:171:22)
#12     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:602:14)
#13     serializeComponent (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:1036:11)
#14     _processLoadRequest (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:947:41)
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/303445
