### ISSUE TITLE
corelib tests flakey in vm on arm64 Mac?

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#52412]
I'm on 85d09eb89f2ee94d8edacaa3d427294f29ceb0c9.

corelib/string_case_test/01 I've seen fail twice in two runs.
corelib/bool_from_environment_test I've only seen fail once in two runs (presumably flakey?)

```
eseidel@erics-mbp sdk % ./tools/test.py -mrelease --arch=arm64 --runtime=vm corelib

No build targets found.
Test configuration:
    custom-configuration-1(architecture: arm64, compiler: dartk, mode: release, runtime: vm, system: mac)
Suites tested: corelib
[00:13 |  22% | +  149 | -    0]

FAILED: dartk-vm release_arm64 corelib/unicode_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 970ms):
DART_CONFIGURATION=ReleaseARM64 xcodebuild/ReleaseARM64/dart -Dtest_runner.configuration=custom-configuration-1 --ignore-unrecognized-flags --packages=/Users/eseidel/Documents/GitHub/dart-sdk/sdk/.dart_tool/package_config.json /Users/eseidel/Documents/GitHub/dart-sdk/sdk/tests/corelib/unicode_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <STRASSE>, actual: <STRA\xDFE>) fails.
#0      Expect._fail (package:expect/expect.dart:696:5)
#1      Expect.equals (package:expect/expect.dart:117:7)
#2      UnicodeTest.testMain (file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/tests/corelib/unicode_test.dart:10:12)
#3      main (file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/tests/corelib/unicode_test.dart:15:15)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

--- Re-run this test:
python3 tools/test.py -m release -r vm -a arm64 corelib/unicode_test
[00:44 |  76% | +  504 | -    1]

FAILED: dartk-vm release_arm64 corelib/bool_from_environment_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 01.000283s):
DART_CONFIGURATION=ReleaseARM64 xcodebuild/ReleaseARM64/dart -Da=true -Db=false -Dc=NOTBOOL -Dd=True -Dtest_runner.configuration=custom-configuration-1 --ignore-unrecognized-flags --packages=/Users/eseidel/Documents/GitHub/dart-sdk/sdk/.dart_tool/package_config.json /Users/eseidel/Documents/GitHub/dart-sdk/sdk/tests/corelib/bool_from_environment_test.dart

exit code:
255

stderr:
Unhandled exception:
FormatException: Must specify at least one of compiler or runtime in options or configuration name.
#0      Configuration.parse (package:smith/configuration.dart:239:9)
#1      _configuration (package:expect/config.dart:18:52)
#2      _configuration (package:expect/config.dart)
#3      isVmJitConfiguration (package:expect/config.dart:29:34)
#4      isVmConfiguration (package:expect/config.dart:33:31)
#5      main (file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/tests/corelib/bool_from_environment_test.dart:15:58)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

--- Re-run this test:
python3 tools/test.py -m release -r vm -a arm64 corelib/bool_from_environment_test
[00:51 |  87% | +  579 | -    2]

FAILED: dartk-vm release_arm64 corelib/string_case_test/01
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 957ms):
DART_CONFIGURATION=ReleaseARM64 xcodebuild/ReleaseARM64/dart -Dtest_runner.configuration=custom-configuration-1 --ignore-unrecognized-flags --packages=/Users/eseidel/Documents/GitHub/dart-sdk/sdk/.dart_tool/package_config.json /Users/eseidel/Documents/GitHub/dart-sdk/sdk/xcodebuild/ReleaseARM64/generated_tests/corelib/string_case_test_01.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <SS>, actual: <\xDF>) fails.
#0      Expect._fail (package:expect/expect.dart:696:5)
#1      Expect.equals (package:expect/expect.dart:117:7)
#2      testSpecialCases (file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/xcodebuild/ReleaseARM64/generated_tests/corelib/string_case_test_01.dart:24:10)
#3      main (file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/xcodebuild/ReleaseARM64/generated_tests/corelib/string_case_test_01.dart:9:3)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

--- Re-run this test:
python3 tools/test.py -m release -r vm -a arm64 corelib/string_case_test/01
[00:57 | 100% | +  660 | -    3]

=== 660 tests passed, 3 failed ===
```

**Comment by lrhn** [comment]
The Unicode tests are probably an intentional discrepancy between Dart native and web.

The result of `\xDF`, aka, "&#x00df;", rather of "SS", comes from `"ß".toUpperCase()` being `"ß"` on native and `"SS"` on the web (most likely because of the Unicode-wizard working on the early V8 implementation of `toUpperCase`).

The test should fail, every time, on every non-web configuration. The SDK tests runners use a configuration to remember that it's expected to fail. I don't know if you have the same configuration available locally (or where it's even stored).
