### ISSUE TITLE
Expression evaluation error in VM service protocol with extension method

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#52522]
To reproduce:
- create a sample Flutter project
- add an extension method
- call the method from the sample
- add a watch on a variable defined in the extension method
- run it

```Dart
extension on String {
  parseInt() {
    var temp = 'temp';
    return int.parse(this);
  }
}
```
In `_incrementCounter()`:
```Dart
      _counter++;
      '42'.parseInt();
```
I had watches on `_counter` and `temp`.
The request was `evaluateInFrame`.
The stack trace returned with the error JSON (think it was the same for both):
```
#0      HotRunner._compileExpressionService (package:flutter_tools/src/run_hot.dart:210:5)
<asynchronous suspension>
#1      setUpVmService.<anonymous closure> (package:flutter_tools/src/vmservice.dart:264:40)
<asynchronous suspension>
#2      VmService._routeRequest (package:vm_service/src/vm_service.dart:2548:14)
<asynchronous suspension>
#3      VmService._processRequest (package:vm_service/src/vm_service.dart:2518:19)
<asynchronous suspension>
```
Context: https://github.com/flutter/flutter-intellij/issues/6736

**Comment by aam** [comment]
cc @johnniwinther

**Comment by aam** [comment]
Keep opened until it lands in flutter
