### ISSUE TITLE
co19/LibTest/io/RandomAccessFile/writeByte_A01_t01 went from Pass to RTE

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#52553]
There are new test failures on [Revert "[VM/Timeline] Make timestamp1_or_id variables more understandable"...[VM/Timeline] Make timestamp1_or_id variables more understandable](https://github.com/dart-lang/sdk/compare/354e1d22cb1cd4cc6b8f7beb60d690b5351a169d~...2e29ed3874cfecf7f506ebc05dbe52d903c3b38d).

The tests
```
co19/LibTest/io/RandomAccessFile/writeByte_A01_t01 RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-weak-asserts-linux-release-x64
```

[Log](https://dart-ci.appspot.com/log/vm-kernel-precomp-linux-release-x64/dartkp-weak-asserts-linux-release-x64/15691/co19/LibTest/io/RandomAccessFile/writeByte_A01_t01):

```
--- Command "vm" (took 41ms):
DART_CONFIGURATION=ReleaseX64 TEST_COMPILATION_DIR=/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-weak-asserts-linux-release-x64/tests_co19_src_LibTest_io_RandomAccessFile_writeByte_A01_t01 out/ReleaseX64/dart_precompiled_runtime --enable_asserts --no-sound-null-safety -Dtest_runner.configuration=dartkp-weak-asserts-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-weak-asserts-linux-release-x64/tests_co19_src_LibTest_io_RandomAccessFile_writeByte_A01_t01/out.aotsnapshot

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <1>, actual: <0>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:18)
#1      Expect.equals (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:15)
#2      check.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/co19/src/LibTest/io/RandomAccessFile/writeByte_A01_t01.dart:35)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartkp-weak-asserts-linux-release-x64 co19/LibTest/io/RandomAccessFile/writeByte_A01_t01
```

**Comment by dcharkes** [comment]
This test is meta-flaking: https://dart-ci.web.app/#showLatestFailures=false&test=co19/LibTest/io/RandomAccessFile/writeByte_A01_t01&configurations=dartkp-weak-asserts-linux-release-x64

Log today: identical

https://dart-ci.appspot.com/log/vm-kernel-precomp-linux-release-x64/dartkp-weak-asserts-linux-release-x64/15779/co19/LibTest/io/RandomAccessFile/writeByte_A01_t01

**Comment by alexmarkov** [comment]
Still failing: https://dart-ci.appspot.com/log/vm-mac-release-arm64/vm-mac-release-arm64/2367/co19/LibTest/io/RandomAccessFile/writeByte_A01_t01

**Comment by aam** [comment]
flaky turned RuntimeError https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8754242059975880641/+/u/test_results/stdout

**Comment by dcharkes** [comment]
https://dart-ci.web.app/#showLatestFailures=false&test=co19/LibTest/io/RandomAccessFile/writeByte_A01_t01

```
--- Command "vm_compile_to_kernel" (took 03.000719s):
DART_CONFIGURATION=DebugX64C /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/DebugX64C/vm_platform_strong.dill -o /b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-linux-debug-x64c/tests_co19_src_LibTest_io_RandomAccessFile_writeByte_A01_t01/out.dill /b/s/w/ir/tests/co19/src/LibTest/io/RandomAccessFile/writeByte_A01_t01.dart -Dtest_runner.configuration=vm-aot-linux-debug-x64c --packages=/b/s/w/ir/.dart_tool/package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 15.000536s):
DART_CONFIGURATION=DebugX64C out/DebugX64C/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-linux-debug-x64c/tests_co19_src_LibTest_io_RandomAccessFile_writeByte_A01_t01/out.S --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-debug-x64c --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-linux-debug-x64c/tests_co19_src_LibTest_io_RandomAccessFile_writeByte_A01_t01/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 52ms):
DART_CONFIGURATION=DebugX64C rm /b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-linux-debug-x64c/tests_co19_src_LibTest_io_RandomAccessFile_writeByte_A01_t01/out.dill

exit code:
0

--- Command "assemble" (took 950ms):
DART_CONFIGURATION=DebugX64C gcc -Wl,--no-undefined -shared -o /b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-linux-debug-x64c/tests_co19_src_LibTest_io_RandomAccessFile_writeByte_A01_t01/out.aotsnapshot /b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-linux-debug-x64c/tests_co19_src_LibTest_io_RandomAccessFile_writeByte_A01_t01/out.S

exit code:
0

--- Command "remove_assembly" (took 25ms):
DART_CONFIGURATION=DebugX64C rm /b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-linux-debug-x64c/tests_co19_src_LibTest_io_RandomAccessFile_writeByte_A01_t01/out.S

exit code:
0

--- Command "vm" (took 112ms):
DART_CONFIGURATION=DebugX64C TEST_COMPILATION_DIR=/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-linux-debug-x64c/tests_co19_src_LibTest_io_RandomAccessFile_writeByte_A01_t01 out/DebugX64C/dart_precompiled_runtime --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-debug-x64c --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-linux-debug-x64c/tests_co19_src_LibTest_io_RandomAccessFile_writeByte_A01_t01/out.aotsnapshot

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <5>, actual: <0>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:18)
#1      Expect.equals (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:15)
#2      check.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/co19/src/LibTest/io/RandomAccessFile/writeByte_A01_t01.dart:35)
<asynchronous suspension>
#3      check.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/co19/src/LibTest/io/RandomAccessFile/writeByte_A01_t01.dart:41)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-aot-linux-debug-x64c co19/LibTest/io/RandomAccessFile/writeByte_A01_t01
```

The number is 5 instead of 1 on this weeks episode.

https://dart-ci.appspot.com/log/vm-aot-linux-debug-x64c/vm-aot-linux-debug-x64c/348/co19/LibTest/io/RandomAccessFile/writeByte_A01_t01

**Comment by derekxu16** [comment]
happened again: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-aot-win-debug-x64/102/overview

**Comment by alexmarkov** [comment]
Again: https://dart-ci.appspot.com/log/vm-aot-win-debug-x64/vm-aot-win-debug-x64/153/co19/LibTest/io/RandomAccessFile/writeByte_A01_t01

**Comment by liamappelbe** [comment]
Again: https://dart-ci.appspot.com/log/vm-aot-win-debug-x64/vm-aot-win-debug-x64/196/co19/LibTest/io/RandomAccessFile/writeByte_A01_t01
