### ISSUE TITLE
No error if a type parameter of a. class occurs in a non-covariant position

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52573]
The following code produces no expected error in both CFE and analyzer
```dart
class V<T extends num> {
  final void Function(T) f;
//                    ^
// [analyzer] unspecified
// [cfe] unspecified
  V(this.f);
}

main() {
  print(V);
}
```
cc @eernstg to confirm

**Comment by eernstg** [comment]
Thanks!

@johnniwinther, @scheglov, @stereotype441, is this a property of shared code, or should we have one issue for the analyzer and another one for the CFE?

**Comment by stereotype441** [comment]
I don't think this is a bug. My understanding is that we've always intended to allow code like this statically, and check it at runtime.

E.g. this code:
```dart
class V<T extends num> {
  final void Function(T) f;
  V(this.f);
}

void f1(int i) {}

main() {
  V<int> v1 = V<int>(f1);
  V<num> v2 = v1;
  print(v2.f);
}
```
Does this at runtime:
```
Unhandled exception:
type '(int) => void' is not a subtype of type '(num) => void'
#0      main (file:///usr/local/google/home/paulberry/tmp/proj/test.dart:11:12)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#2      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```
IIRC, the way this is implemented is that the CFE notices that the getter invocation`v2.f` isn't guaranteed to produce a result that's compatible with its static type, so to restore soundness, it inserts a cast, effectively interpreting `v2.f` as `v2.f as void Function(num)`. Since the actual type of `v2.f` at runtime is `void Function(int)`, the cast fails.

**Comment by eernstg** [comment]
The feature specification actually says that [it is an error](https://github.com/dart-lang/language/blob/main/accepted/future-releases/inline-classes/feature-specification.md#:~:text=on%20V.-,A%20compile%2Dtime%20error%20occurs,-if%20a%20type). The reason why we _can_ make it an error is that there is no existing code. If we assume that we allow it anyway then we would presumably need to perform caller-side checks during an upcast (which is not likely to be acceptable):

```dart
inline class I<X>(void Function(X) value) {}

X f<X, Y extends X>(Y y) => y; // Caller-side check on the upcast to `X`.

void main() {
  I<num> iNum = f<I<num>, I<int>>(I((int i) {}));
}
```

**Comment by eernstg** [comment]
I've created https://github.com/dart-lang/sdk/issues/52576 to illustrate that the current approach allows for a soundness violation.

**Comment by stereotype441** [comment]
> The feature specification actually says that [it is an error](https://github.com/dart-lang/language/blob/main/accepted/future-releases/inline-classes/feature-specification.md#:~:text=on%20V.-,A%20compile%2Dtime%20error%20occurs,-if%20a%20type). The reason why we _can_ make it an error is that there is no existing code. If we assume that we allow it anyway then we would presumably need to perform caller-side checks during an upcast (which is not likely to be acceptable):

To clarify, @sgrekhov's example does not involve inline classes, so I continue to believe that it should not be an error.

I'm fine with the error for inline classes though.

**Comment by sgrekhov** [comment]
There are no error for both inline and not-inline classes

**Comment by eernstg** [comment]
Oh, I misread the example --- we're just working on inline tests, so I assumed that the example was obviously about inline classes, and missed the fact that there was no `inline` keyword. Sorry about that! ;-)

For regular classes we should of course keep generating the caller-side checks.
