### ISSUE TITLE
Debugging Tools: Timeline Events error doesnt work

### ISSUE THREAD

**Issue by cyberpwnn** [dart-lang/sdk#52588]
<img width="1113" alt="Screenshot 2023-06-01 at 1 13 39 PM" src="https://github.com/dart-lang/sdk/assets/10619135/656fd219-6e52-4160-a448-4a0bff1407fb">

```
Uncaught FormatException: Unexpected extension byte (at offset 23)
    at Object.i (http://127.0.0.1:9102/main.dart.js:3049:3)
    at bsV.aZ5 (http://127.0.0.1:9102/main.dart.js:57408:9)
    at Wv.dE (http://127.0.0.1:9102/main.dart.js:57396:21)
    at Ks.agn (http://127.0.0.1:9102/main.dart.js:57337:49)
    at Ks.cK (http://127.0.0.1:9102/main.dart.js:57338:21)
    at http://127.0.0.1:9102/main.dart.js:90982:10
    at bwA.a (http://127.0.0.1:9102/main.dart.js:4411:62)
    at bwA.$2 (http://127.0.0.1:9102/main.dart.js:54430:14)
    at bub.$1 (http://127.0.0.1:9102/main.dart.js:54424:21)
    at Object.bwd (http://127.0.0.1:9102/main.dart.js:4699:19)
```

```
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3 22E252 darwin-arm64, locale en-US)
    • Flutter version 3.10.2 on channel stable at /Users/danielmills/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (9 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/danielmills/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: /Users/danielmills/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/danielmills/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/danielmills/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/danielmills/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/danielmills/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA 2022.1 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/danielmills/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA 2022.1 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • IN2017 (mobile) • 2e01d742 • android-arm64  • Android 13 (API 33)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 110.0.5481.177

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

**Comment by fishythefish** [comment]
Hey, @cyberpwnn, can you provide some additional details to repro the issue? It's hard to tell if there's an underlying Dart SDK bug, but this looks like an issue with Flutter DevTools. Have you filed an issue at https://github.com/flutter/flutter/?
