### ISSUE TITLE
Failures on Reland "[VM/Timeline] Make timestamp1_or_id variables more understandable"

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52598]
There are new test failures on [Reland "[VM/Timeline] Make timestamp1_or_id variables more understandable"](https://github.com/dart-lang/sdk/commit/475240d2346aa2716567397cf9afc36b48e88637).

The tests
```
vm/cc/DartAPI_TimelineEvents_Serialization Crash (expected Pass)
```
are failing on configurations
```
vm-ubsan-linux-release-x64
```

https://dart-ci.appspot.com/log/vm-ubsan-linux-release-x64/vm-ubsan-linux-release-x64/114/vm/cc/DartAPI_TimelineEvents_Serialization

```
--- Command "run_vm_unittest" (took 982ms):
DART_CONFIGURATION=ReleaseUBSANX64 out/ReleaseUBSANX64/run_vm_tests --dfe=/b/s/w/ir/out/ReleaseUBSANX64/gen/kernel-service.dart.snapshot --enable-experiment=records --sound-null-safety --ignore-unrecognized-flags DartAPI_TimelineEvents_Serialization

exit code:
-6

stdout:
Running test: DartAPI_TimelineEvents_Serialization

stderr:
../../third_party/perfetto/include/perfetto/protozero/scattered_stream_writer.h:89:37: runtime error: applying non-zero offset 2 to null pointer
    #0 0x5595d2d1c5b0 in protozero::ScatteredStreamWriter::WriteBytes(unsigned char const*, unsigned long) out/ReleaseUBSANX64/../../third_party/perfetto/include/perfetto/protozero/scattered_stream_writer.h:89:37
    #1 0x5595d2d1c5b0 in protozero::Message::WriteToStream(unsigned char const*, unsigned char const*) out/ReleaseUBSANX64/../../third_party/perfetto/include/perfetto/protozero/message.h:201:21
    #2 0x5595d3041554 in void protozero::Message::AppendVarInt<unsigned int>(unsigned int, unsigned int) out/ReleaseUBSANX64/../../third_party/perfetto/include/perfetto/protozero/message.h:103:5
    #3 0x5595d3041554 in protozero::internal::FieldWriter<(protozero::proto_utils::ProtoSchemaType)13>::Append(protozero::Message&, unsigned int, unsigned int) out/ReleaseUBSANX64/../../third_party/perfetto/include/perfetto/protozero/field_writer.h:76:13
    #4 0x5595d3041554 in perfetto::protos::pbzero::TracePacket::set_trusted_packet_sequence_id(unsigned int) out/ReleaseUBSANX64/../../runtime/vm/protos/perfetto/trace/trace_packet.pbzero.h:287:5
    #5 0x5595d3041554 in dart::perfetto_utils::SetTrustedPacketSequenceId(perfetto::protos::pbzero::TracePacket*) out/ReleaseUBSANX64/../../runtime/vm/perfetto_utils.h:33:11
    #6 0x5595d3041554 in dart::perfetto_utils::PopulateClockSnapshotPacket(perfetto::protos::pbzero::TracePacket*) out/ReleaseUBSANX64/../../runtime/vm/perfetto_utils.h:50:3
    #7 0x5595d314bc7c in dart::TimelineEventRecorder::PrintPerfettoMeta(dart::JSONBase64String*) out/ReleaseUBSANX64/../../runtime/vm/timeline.cc:1334:3
    #8 0x5595d314d789 in dart::TimelineEventFixedBufferRecorder::PrintPerfettoTimeline(dart::JSONStream*, dart::TimelineEventFilter const&) out/ReleaseUBSANX64/../../runtime/vm/timeline.cc:1761:3
    #9 0x5595d2711886 in dart::Dart_TestHelperDartAPI_TimelineEvents_Serialization(dart::Thread*) out/ReleaseUBSANX64/../../runtime/vm/dart_api_impl_test.cc:10444:13
    #10 0x5595d2711886 in dart::Dart_TestDartAPI_TimelineEvents_Serialization() out/ReleaseUBSANX64/../../runtime/vm/dart_api_impl_test.cc:10425:1
    #11 0x5595d2683e2f in dart::TestCase::Run() out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:52:3
    #12 0x5595d2683fe8 in dart::TestCaseBase::RunTest() out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:64:11
    #13 0x5595d28b882c in dart::TestCaseBase::RunAll() out/ReleaseUBSANX64/../../runtime/vm/unit_test.cc:86:13
    #14 0x5595d2684969 in dart::Main(int, char const**) out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:397:3
    #15 0x5595d26844e0 in main out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:428:29
    #16 0x7ff8de08a082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #17 0x5595d2669b2d in _start (/b/s/w/ir/out/ReleaseUBSANX64/run_vm_tests+0x31f6b2d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../third_party/perfetto/include/perfetto/protozero/scattered_stream_writer.h:89:37 in

--- Re-run this test:
python3 tools/test.py -n vm-ubsan-linux-release-x64 vm/cc/DartAPI_TimelineEvents_Serialization
```

cc @derekxu16 @bkonyi

**Comment by derekxu16** [comment]
This test is now passing with UBSAN because the Perfetto revision in DEPS was updated.
