### ISSUE TITLE
unable to install dart while building from source

### ISSUE THREAD

**Issue by habray-99** [dart-lang/sdk#52608]
hello, i tried to install dart on arch by reading wiki and building form the source but i ran into python error. here are the error 
`➜  sdk ./tools/build.py --no-goma --mode release --arch x64 create_sdk
Traceback (most recent call last):
  File "/home/bwanso/Docs/dart-sdk/sdk/./tools/build.py", line 319, in <module>
    sys.exit(Main())
             ^^^^^^
  File "/home/bwanso/Docs/dart-sdk/sdk/./tools/build.py", line 268, in Main
    gn_py.RunGnOnConfiguredConfigurations(options)
  File "/home/bwanso/Docs/dart-sdk/sdk/tools/gn.py", line 608, in RunGnOnConfiguredConfigurations
    BuildGnCommand(args, mode, arch, target_os, sanitizer,
  File "/home/bwanso/Docs/dart-sdk/sdk/tools/gn.py", line 582, in BuildGnCommand
    raise Exception("Couldn't find the gn binary at path: " + gn)
Exception: Couldn't find the gn binary at path: /home/bwanso/Docs/dart-sdk/sdk/buildtools/gn
`
`➜  sdk ./tools/build.py --no-goma --mode release --arch ia32 create_sdk
Traceback (most recent call last):
  File "/home/bwanso/Docs/dart-sdk/sdk/./tools/build.py", line 319, in <module>
    sys.exit(Main())
             ^^^^^^
  File "/home/bwanso/Docs/dart-sdk/sdk/./tools/build.py", line 268, in Main
    gn_py.RunGnOnConfiguredConfigurations(options)
  File "/home/bwanso/Docs/dart-sdk/sdk/tools/gn.py", line 608, in RunGnOnConfiguredConfigurations
    BuildGnCommand(args, mode, arch, target_os, sanitizer,
  File "/home/bwanso/Docs/dart-sdk/sdk/tools/gn.py", line 582, in BuildGnCommand
    raise Exception("Couldn't find the gn binary at path: " + gn)
Exception: Couldn't find the gn binary at path: /home/bwanso/Docs/dart-sdk/sdk/buildtools/gn
`

my python is 3.11.3

**Comment by athomas** [comment]
The only supported way to build Dart is https://github.com/dart-lang/sdk/wiki/Building.

Building purely from sources is tricky and not a currently supported use case. In your case, you'd need to get a version of `depot_tools` into your `PATH` and get the sources with `fetch dart` (`depot_tools` will provide `fetch` which will prepare a gclient solution and sync it which will provide the missing `buildtools/gn`).

Some related issues to bootstrapping from source (though this is probably easier because Arch is glibc-based):
https://github.com/dart-lang/sdk/issues/51788
https://github.com/dart-lang/sdk/issues/51642

**Comment by habray-99** [comment]
thank you for reaching out
