### ISSUE TITLE
NPE in AstNodeExtension.nodeCovering.containsOffset()

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52606]
Spotted this in my logs while setting up the server on Windows:

```
#0      AstNodeExtension.nodeCovering.containsOffset (package:analyzer/src/utilities/extensions/ast.dart:29:63)
#1      AstNodeExtension.nodeCovering.childContainingRange (package:analyzer/src/utilities/extensions/ast.dart:41:34)
#2      AstNodeExtension.nodeCovering (package:analyzer/src/utilities/extensions/ast.dart:59:21)
#3      CompilationUnitExtension.select (package:analysis_server/src/utilities/selection.dart:449:24)
#4      RefactoringContext.selection (package:analysis_server/src/services/refactoring/framework/refactoring_context.dart:42:8)
#5      RefactoringContext.selection (package:analysis_server/src/services/refactoring/framework/refactoring_context.dart)
#6      RefactoringProducer.selection (package:analysis_server/src/services/refactoring/framework/refactoring_producer.dart:51:40)
#7      MoveTopLevelToFile._selectedNodes (package:analysis_server/src/services/refactoring/move_top_level_to_file.dart:310:26)
#8      MoveTopLevelToFile._membersToMove (package:analysis_server/src/services/refactoring/move_top_level_to_file.dart:214:25)
#9      MoveTopLevelToFile.isAvailable (package:analysis_server/src/services/refactoring/move_top_level_to_file.dart:171:21)
#10     RefactoringProcessor.compute (package:analysis_server/src/services/refactoring/framework/refactoring_processor.dart:36:21)
#11     DartCodeActionsProducer.getRefactorActions (package:analysis_server/src/lsp/handlers/code_actions/dart.dart:203:39)
#12     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:216:31)
#13     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:29)
#14     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:215:32)
<asynchronous suspension>
#15     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:274:22)
<asynchronous suspension>
#16     LspAnalysisServer._handleRequestMessage (package:analysis_server/src/lsp/lsp_analysis_server.dart:987:20)
<asynchronous suspension>
#17     LspAnalysisServer.handleMessage.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:464:15)
<asynchronous suspension>
#18     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#19     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:447:11)
<asynchronous suspension>
```

```
1685823954881:Req:{"jsonrpc"::"2.0","id"::43,"method"::"textDocument/codeAction","params"::{"textDocument"::{"uri"::"file::///C%3A/Dev/Google/dart-sdk/sdk/pkg/analysis_server/lib/src/lsp/client_capabilities.dart"},"range"::{"start"::{"line"::35,"character"::61},"end"::{"line"::35,"character"::61}},"context"::{"diagnostics"::[],"triggerKind"::2}},"clientRequestTime"::1685823954882}
1685823954881:Res:{"id"::43,"jsonrpc"::"2.0","error"::{"code"::-32001,"message"::"An error occurred while handling textDocument/codeAction request"}}
```

It looks very similar to https://github.com/dart-lang/sdk/issues/52362, but it seems to be a few lines lower than where the fix for that was made.

**Comment by bwilkerson** [comment]
@scheglov (for the similarity to another issue that you previously fixed)

**Comment by scheglov** [comment]
I was not able to reproduce this, and don't want to fix without a test.
It might be something wrong happened before, e.g. during parsing, and we did not set tokens property, so that there is no `next` (normally I expect it only for comments).

**Comment by scheglov** [comment]
I can reproduce it, thank you.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/307504
