### ISSUE TITLE
Unable to start analysis server on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52616]
I'm seeing this error when trying to start the analysis server today with my DDS workspace open. The workspace contains `dds`, `dartdev`, `vm_service`, `dap`. (Edit: Happens with just `dds` folder open, and also only `dap`...).

```
[4:05:42 PM] [Analyzer] [Error] Unhandled exception:
LateInitializationError: Field 'period' has not been initialized.
#0      MemoryUsageEvent.period (package:leak_tracker/src/usage_tracking/model.dart)
#1      AnalyticsManager.sendMemoryUsage (package:analysis_server/src/analytics/analytics_manager.dart:203:25)
#2      Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:363:46)
#3      UsageEventCreator._triggerEvent (package:leak_tracker/src/usage_tracking/_usage_event.dart:42:24)
#4      …
```

It doesn't happen with other workspaces (for example with `analyzer`, `analysis_server`) so I suspect something specific about this workspace is triggering it.

(FYI @bwilkerson @polina-c because it involves analytics and leak tracker in case you've seen it before, but I am still debugging and will post back when I figure out what's triggering it)

**Comment by DanTup** [comment]
So, I think there are two different issues here that I assumed were the same, and one of them is my own doing.

The issue above has actually been fixed in https://github.com/dart-lang/leak_tracker/pull/62, but I had a bogus `.dart_tool/package_config` that was pulling `leak_tracker` from Pub that doesn't have the fix.

The reason I was running from source was because the server wasn't responding from the snapshot, but it seems like that's likely a different issue now (since the snapshot is prebuilt and won't be using this).

Closing this.. whatever my original issue was, this was not it.
