### ISSUE TITLE
Crash when compiling files that contain # symbols in their path

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52623]
I was scanning through old issues I'd filed to see if I could close any, and while testing if #32532 was an issue I found that having `#` isn't just a problem for the analysis server, it now doesn't work for running Dart scripts.

I created a file (on Windows) named `test#.dart` and if I try to run it with `dart test#.dart` I get the error below. I can't reproduce it with `print(Uri.file('test#.dart').toFilePath());` because the URI ends up being `test%23.dart` so I suspect something somewhere is converting the input filename to a `file:///` URI without encoding properly.

```
PS C:\Dev\Test Projects\dart_application_2> dart .\bin\test#.dart
Crash when compiling file:///C:/Dev/Test%20Projects/dart_application_2/bin/test#.dart:
Unsupported operation: Cannot extract a file path from a URI with a fragment component

#0      _Uri.toFilePath (dart:core/uri.dart:2855:7)
#1      new File.fromUri (dart:io/file.dart:204:49)
#2      _IoFileSystemEntity.readAsBytes (package:front_end/src/api_prototype/standard_file_system.dart:82:35)
#3      HybridFileSystemEntity.readAsBytes (package:front_end/src/fasta/hybrid_file_system.dart:57:61)
<asynchronous suspension>
#4      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:877:20)
<asynchronous suspension>
#5      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:1207:20)
<asynchronous suspension>
#6      SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:1032:7)
<asynchronous suspension>
#7      KernelTarget.computeNeededPrecompilations.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:354:7)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#9      KernelTarget.computeNeededPrecompilations (package:front_end/src/fasta/kernel/kernel_target.dart:352:12)
<asynchronous suspension>
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:101:11)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:49:12)
<asynchronous suspension>
#13     generateKernel (package:front_end/src/kernel_generator_impl.dart:48:10)
<asynchronous suspension>
#14     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#15     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:407:11)
<asynchronous suspension>
#16     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:215:45)
<asynchronous suspension>
#17     _processLoadRequest (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:889:37)
<asynchronous suspension>
```

**Comment by lrhn** [comment]
Most likely a correct guess, the command line argument is passed into `Uri.parse`, which means that a `#` becomes a fragment delimiter. Then it becomes impossible to do `.toFilePath()` on it, because it has a fragment.

We still need to decide on a strategy to decide whether a command line argument is a URI or a file path, and treat both of those correctly. Currently it's (apparently) assumed to be a URI, which is wrong in some cases. At that point, just doing `toFilePath` on the URI is *not* the same as starting out assuming that the command line argument was a file path.

**Comment by DanTup** [comment]
> Currently it's (apparently) assumed to be a URI, which is wrong in some cases

Are there cases where parsing it as a filename wouldn't work (eg. always using `Uri.file` instead of `Uri.parse`)? (is it purely to allow forward slashes on Windows? terminal tab completion always puts in backslashes).
