### ISSUE TITLE
standalone/io/client_socket_add_destroy_no_error_test failing after write until EAGAIN on POSIX change

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#52654]
There are new test failures on [[vm/io] Make sure to write until EAGAIN on POSIX](https://github.com/dart-lang/sdk/commit/0b62bb66ed17546e4aea6547f8604175ead8f45d).

The tests
```
standalone/io/client_socket_add_destroy_no_error_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-appjit-linux-debug-x64
vm-appjit-linux-product-x64
vm-reload-linux-debug-x64
vm-reload-rollback-linux-debug-x64
vm-reload-rollback-linux-release-x64
```

Example [log](https://dart-ci.appspot.com/log/vm-appjit-linux-debug-x64/vm-appjit-linux-debug-x64/867/standalone/io/client_socket_add_destroy_no_error_test):
```
--- Command "app_jit" (took 08.000379s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --snapshot=/b/s/w/ir/out/DebugX64/generated_compilations/vm-appjit-linux-debug-x64/tests_standalone_io_client_socket_add_destroy_no_error_test/out.jitsnapshot --snapshot-kind=app-jit --sound-null-safety -Dtest_runner.configuration=vm-appjit-linux-debug-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/standalone/io/client_socket_add_destroy_no_error_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done
unittest-suite-success

stderr:
Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 127.0.0.1, port = 37294
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1244:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:2002:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2477:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2212:28)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2166:11)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#9      _StreamController._add (dart:async/stream_controller.dart:658:7)
#10     _StreamController.add (dart:async/stream_controller.dart:606:5)
#11     _StreamSinkImpl.add (dart:io/io_sink.dart:138:17)
#12     _Socket.add (dart:io-patch/socket_patch.dart:2319:38)
#13     clientSocketAddDestroyNoErrorTest.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/client_socket_add_destroy_no_error_test.dart:20:14)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-appjit-linux-debug-x64 standalone/io/client_socket_add_destroy_no_error_test
```

Looks like the writing is continuing to be attempted even after `.destroy()`?

/cc @mraleph

**Comment by mraleph** [comment]
> Looks like the writing is continuing to be attempted even after `.destroy()`?

The destroy should not even happened yet at this point (at least in the normal flow of test):

```dart
      client.add(new List.filled(1024 * 1024, 0));  // <- this is where it throws.
      client.destroy();
```
