### ISSUE TITLE
[dart2js] Failed type test but only in deferred-loaded code

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#52668]
The `Omnibus` and `OmnibusDeferred` benchmarks both import the `Iterators` benchmark, the first as a direct import and the second as a deferred import.

The direct case runs as expected:
```
$ out/ReleaseX64/dart-sdk/bin/dart compile js --out=om2a/o.js benchmarks/Omnibus/dart/Omnibus.dart 
Compiled 10,420,660 input bytes (5,607,601 characters source) to 607,647 characters JavaScript in 3.12 seconds using 262.594 MB of memory

$ ~/.jsvu/v8 sdk/lib/_internal/js_runtime/lib/preambles/d8.js om2a/o.js -- Iterators
Iterators.mono.const.Map.int.keys.1(RunTimeRaw): 94.1 ns.
Iterators.mono.const.Map.int.keys.100(RunTimeRaw): 28.354231974921632 ns.
^C
```

The deferred case the benchmark crashes with a type error that should be impossible:
```
$ out/ReleaseX64/dart-sdk/bin/dart compile js --out=om2b/o.js benchmarks/OmnibusDeferred/dart/OmnibusDeferred.dart Hint: When run on the command-line, the compiled output might require a preamble file located in:
  <sdk>/lib/_internal/js_runtime/lib/preambles.
Compiled 10,421,765 input bytes (5,608,706 characters source) to 719,598 characters JavaScript in 3.92 seconds using 262.992 MB of memory

$ ~/.jsvu/v8 sdk/lib/_internal/js_runtime/lib/preambles/d8.js om2b/o.js -- Iterators
sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: TypeError: Instance of 'Thing0<Set<BigInt>>': type 'Thing0<Set<BigInt>>' is not a subtype of type 'Thing0<Iterable<Comparable<dynamic>>>'
          throw e;
          ^
TypeError: Instance of 'Thing0<Set<BigInt>>': type 'Thing0<Set<BigInt>>' is not a subtype of type 'Thing0<Iterable<Comparable<dynamic>>>'
    at Object.wrapException (om2b/o.js:539:43)
    at Object._failedAsCheck (om2b/o.js:1948:15)
    at Rti._generalAsCheckImplementation [as _as] (om2b/o.js:1937:9)
    at Object.List_List$from (om2b/o.js:3828:42)
    at StaticClosure.generateThingList (om2b/o.js_12.part.js:88:16)
    at PolyBenchmark.setup$0 (om2b/o.js_12.part.js:474:40)
    at Object.main12 (om2b/o.js_12.part.js:161:19)
    at benchmarks_closure0.call$0 (om2b/o.js:7518:16)
    at Lib.main$0 (om2b/o.js:7505:24)
    at om2b/o.js:4336:21
```

I suspect that there is a bug in the partitioned type rules - some rule is not in the required partition(s) or has been overwritten.

This problem exists at c0c6ff4754b31be441e0a28671819d5b04a062f2 where `Iterators` was added to the Omnibus benchmarks.

**Comment by sigmundch** [comment]
@rakudrama - wondering if we still consider this P1, and we are actively working on it. If not, we could update the priority label.
