### ISSUE TITLE
dart2js crashes when using a `fromEnvironment` constant in a constant record

### ISSUE THREAD

**Issue by mitryp** [dart-lang/sdk#52708]
This issue occurs when compiling Dart to JavaScript.

I use the following environment:
* Dart SDK Version: __3.0.3__
* Operating System: __Windows 11 22H2__

<details><summary>The minimal reproducible example of the issue</summary>

```dart
const int someConstantFromEnv = int.fromEnvironment(
  'someConstantFromEnv',
  defaultValue: 1,
);

const constRecord = (someConstantFromEnv, 1);

void main() => print(constRecord);
```

</details>

<details><summary>The complete crash message</summary>

```console
> dart compile js .\main.dart
Info: Compiling with sound null safety.
main.dart:8:6:
Internal Error: The compiler crashed when compiling this element.
void main() => print(constRecord);
     ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.0.3), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Unsupported operation: Unexpected unevaluated constant UnevaluatedConstant(unevaluated{int.fromEnvironment("someConstantFromEnv", defaultValue: 1.0)}).
#0      ConstantValuefier.visitUnevaluatedConstant (package:compiler/src/ir/visitors.dart:237:5)
#1      _ConstantCallbackVisitor.visitUnevaluatedConstant (package:kernel/visitor.dart:1065:17)
#2      UnevaluatedConstant.accept (package:kernel/ast.dart:14882:42)
#3      ComputeOnceConstantVisitor.visitConstant (package:kernel/visitor.dart:1153:52)
#4      ConstantValuefier.visitRecordConstant (package:compiler/src/ir/visitors.dart:319:44)
#5      _ConstantCallbackVisitor.visitRecordConstant (package:kernel/visitor.dart:1107:17)
#6      RecordConstant.accept (package:kernel/ast.dart:14348:42)
#7      ComputeOnceConstantVisitor.visitConstant (package:kernel/visitor.dart:1153:52)
#8      JsKernelToElementMap.getConstantValue (package:compiler/src/js_model/element_map_impl.dart:1500:33)
#9      KernelSsaGraphBuilder.visitConstantExpression (package:compiler/src/ssa/builder.dart:1929:21)
#10     ConstantExpression.accept (package:kernel/ast.dart:9223:44)
#11     KernelSsaGraphBuilder._visitPositionalArguments (package:compiler/src/ssa/builder.dart:3906:16)
#12     KernelSsaGraphBuilder._visitArgumentsForStaticTarget (package:compiler/src/ssa/builder.dart:4041:33)
#13     KernelSsaGraphBuilder.visitStaticInvocation (package:compiler/src/ssa/builder.dart:4162:25)
#14     StaticInvocation.accept (package:kernel/ast.dart:7029:44)
#15     KernelSsaGraphBuilder.visitReturnStatement (package:compiler/src/ssa/builder.dart:1950:24)
#16     ReturnStatement.accept (package:kernel/ast.dart:10786:43)
#17     KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder.dart:1347:24)
#18     KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder.dart:471:15)
#19     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#20     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder.dart:456:21)
#21     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:563:22)
#22     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#23     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:545:18)
#24     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:361:21)
#25     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:87:28)
#26     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:421:30)
#27     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:337:43)
#28     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:504:29)
#29     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:830:70)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#31     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:830:32)
#32     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#33     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:828:28)
#34     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#35     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:826:18)
#36     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:252:12)
#37     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:268:5)
#38     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:822:16)
#39     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#40     Compiler.emptyQueue (package:compiler/src/compiler.dart:821:14)
#41     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:845:7)
#42     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#43     Compiler.processQueue (package:compiler/src/compiler.dart:839:14)
#44     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:557:5)
#45     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:771:23)
<asynchronous suspension>
#46     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:319:7)
<asynchronous suspension>
#47     Compiler.runInternal (package:compiler/src/compiler.dart:318:5)
<asynchronous suspension>
#48     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:239:11)
<asynchronous suspension>
#49     main (package:compiler/src/dart2js.dart:1473:3)
<asynchronous suspension>
```

</details>

**Comment by mitryp** [comment]
I apologize, this is a duplicate of #52468
