### ISSUE TITLE
vm/dart/awaiter_stacks/zone_callback_stack_traces fails on AOT

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#52797]
The new `vm/dart/awaiter_stacks/zone_callback_stack_traces` tests fail on AOT, because there are additional frames in AOT that aren't expected by the matcher.

Example logs from [`vm-aot-linux-release-x64`](https://dart-ci.appspot.com/log/vm-aot-linux-release-x64/vm-aot-linux-release-x64/632/vm/dart/awaiter_stacks/zone_callback_stack_traces_test/0):
```
stdout:
registerUnaryCallback got stack trace:
#0      _registerUnaryCallback (file:///b/s/w/ir/runtime/tests/vm/dart/awaiter_stacks/zone_callback_stack_traces_test.dart:43)
#1      bar (file:///b/s/w/ir/runtime/tests/vm/dart/awaiter_stacks/zone_callback_stack_traces_test.dart:24)
#2      _rootRun (dart:async/zone.dart:1399)
#3      _CustomZone.run (dart:async/zone.dart:1301)
#4      runTest (file:///b/s/w/ir/runtime/tests/vm/dart/awaiter_stacks/zone_callback_stack_traces_test.dart:35)
#5      main (file:///b/s/w/ir/runtime/tests/vm/dart/awaiter_stacks/zone_callback_stack_traces_test.dart:72)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)

registerBinaryCallback got stack trace:
#0      _registerBinaryCallback (file:///b/s/w/ir/runtime/tests/vm/dart/awaiter_stacks/zone_callback_stack_traces_test.dart:55)
#1      bar (file:///b/s/w/ir/runtime/tests/vm/dart/awaiter_stacks/zone_callback_stack_traces_test.dart:24)
#2      _rootRun (dart:async/zone.dart:1399)
#3      _CustomZone.run (dart:async/zone.dart:1301)
#4      runTest (file:///b/s/w/ir/runtime/tests/vm/dart/awaiter_stacks/zone_callback_stack_traces_test.dart:35)
#5      main (file:///b/s/w/ir/runtime/tests/vm/dart/awaiter_stacks/zone_callback_stack_traces_test.dart:72)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)

STACK TRACE MISMATCH -----------------
GOT:
#0    _registerUnaryCallback (%test%)
#1    bar (%test%)
#2    _rootRun (zone.dart)
#3    _CustomZone.run (zone.dart)
#4    runTest (%test%)
#5    main (%test%)
#6    _delayEntrypointInvocation.<anonymous closure> (isolate_patch.dart)
#7    _RawReceivePort._handleMessage (isolate_patch.dart)
EXPECTED:
#0    _registerUnaryCallback (%test%)
#1    _CustomZone.registerUnaryCallback (zone.dart)
#2    bar (%test%)
#3    _rootRun (zone.dart)
#4    _CustomZone.run (zone.dart)
#5    runTest (%test%)
#6    main (%test%)
#7    _delayEntrypointInvocation.<anonymous closure> (isolate_patch.dart)
#8    _RawReceivePort._handleMessage (isolate_patch.dart)
--------------------------------------
To regenate expectations run:
$ out/ReleaseX64/dart_precompiled_runtime -Dupdate.expectations=true file:///b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/runtime_tests_vm_dart_awaiter_stacks_zone_callback_stack_traces_test/out.aotsnapshot
--------------------------------------

stderr:
Unhandled exception:
Expect.equals(expected: <9>, actual: <8>, 'wrong number of frames') fails.
#0      Expect._fail (package:expect/expect.dart:696)
#1      Expect.equals (package:expect/expect.dart:120)
#2      checkExpectedStack (file:///b/s/w/ir/runtime/tests/vm/dart/awaiter_stacks/harness.dart:179)
<asynchronous suspension>
#3      main (file:///b/s/w/ir/runtime/tests/vm/dart/awaiter_stacks/zone_callback_stack_traces_test.dart:73)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-aot-linux-release-x64 vm/dart/awaiter_stacks/zone_callback_stack_traces_test/0
```

Assigning to @mraleph to be marked fixed when the AOT changes land.

**Comment by mkustermann** [comment]
Some more approvals:
```
vm/dart/awaiter_stacks/async_stacks_test/0 RuntimeError (expected Pass)
vm/dart/awaiter_stacks/async_stacks_test/1 RuntimeError (expected Pass)
vm/dart/awaiter_stacks/flutter_regress_100441_test/1 RuntimeError (expected Pass)
vm/dart/awaiter_stacks/sync_async_start_pkg_test_test/1 RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-dwarf-linux-product-x64
vm-aot-linux-product-x64
vm-aot-mac-product-arm64
vm-aot-win-product-x64
vm-aot-win-release-x64
vm-win-debug-x64
vm-win-release-x64
```
