### ISSUE TITLE
New ASAN crash for standalone/regress_52715_test/none

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#52834]
There are new test failures on [Support the dart:developer timeline APIs in dart2js and DDC....[dart2js] Temporarily undo valid refines change.](https://github.com/dart-lang/sdk/compare/73160bc40d5bdb222d9f1def8b67cb22a6d99765~...af8fb2cd73c3b5ec96a39c59e85f470efe78d8a4).

The tests
```
standalone/regress_52715_test/none Crash (expected Pass)
```
are failing on configurations
```
vm-aot-asan-linux-release-x64
```

[Example from log](https://dart-ci.appspot.com/log/vm-aot-asan-linux-release-x64/vm-aot-asan-linux-release-x64/136/standalone/regress_52715_test/none):
```
--- Command "vm" (took 01.000687s):
DART_CONFIGURATION=ReleaseASANX64 TEST_COMPILATION_DIR=/b/s/w/ir/out/ReleaseASANX64/generated_compilations/vm-aot-asan-linux-release-x64/multitest_standalone_regress_52715_test_none out/ReleaseASANX64/dart_precompiled_runtime --sound-null-safety -Dtest_runner.configuration=vm-aot-asan-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseASANX64/generated_compilations/vm-aot-asan-linux-release-x64/multitest_standalone_regress_52715_test_none/out.aotsnapshot

exit code:
-6

stderr:
=================================================================
==66143==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 80 byte(s) in 4 object(s) allocated from:
    #0 0x56103076525d in strdup ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/asan/asan_interceptors.cpp:475:3
    #1 0x561030abdb5b in dart::bin::OSError::SetMessage(char const*) out/ReleaseASANX64/../../runtime/bin/utils.h:47:18
    #2 0x561030abdb5b in dart::bin::OSError::SetCodeAndMessage(dart::bin::OSError::SubSystem, int) out/ReleaseASANX64/../../runtime/bin/utils_linux.cc:34:5
    #3 0x561030abdb5b in dart::bin::OSError::Reload() out/ReleaseASANX64/../../runtime/bin/utils_linux.cc:25:3
    #4 0x561030abdb5b in dart::bin::OSError::OSError() out/ReleaseASANX64/../../runtime/bin/utils_linux.cc:21:3
    #5 0x5610307f83b3 in dart::bin::Builtin_FileSystemWatcher_InitWatcher(_Dart_NativeArguments*) out/ReleaseASANX64/../../runtime/bin/file_system_watcher.cc:28:13
    #6 0x561030c7cb5e in dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) out/ReleaseASANX64/../../runtime/vm/native_entry.cc:217:7
    #7 0x7f0c2405d70a  (<unknown module>)
    #8 0x7f0c240c5995  (<unknown module>)
    #9 0x7f0c240c305e  (<unknown module>)
    #10 0x7f0c240c301a  (<unknown module>)
    #11 0x7f0c2407d3b0  (<unknown module>)
    #12 0x7f0c240e5f19  (<unknown module>)
    #13 0x7f0c2409478d  (<unknown module>)
    #14 0x7f0c2411684f  (<unknown module>)
    #15 0x7f0c240cd771  (<unknown module>)
    #16 0x7f0c240612bf  (<unknown module>)
    #17 0x7f0c24116024  (<unknown module>)
    #18 0x7f0c240c770a  (<unknown module>)
    #19 0x7f0c240c75c9  (<unknown module>)
    #20 0x7f0c240c7592  (<unknown module>)
    #21 0x7f0c2406ffd1  (<unknown module>)
    #22 0x7f0c2406ff70  (<unknown module>)
    #23 0x7f0c2405d5a0  (<unknown module>)
    #24 0x561030bc4e8d in dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&) out/ReleaseASANX64/../../runtime/vm/dart_entry.cc:125:33
    #25 0x561030bc9a51 in dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&) out/ReleaseASANX64/../../runtime/vm/dart_entry.cc:37:10
    #26 0x561030bc9a51 in dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&) out/ReleaseASANX64/../../runtime/vm/dart_entry.cc:718:28
    #27 0x561030c25561 in dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message>>) out/ReleaseASANX64/../../runtime/vm/isolate.cc:1308:15
    #28 0x561030c4969f in dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) out/ReleaseASANX64/../../runtime/vm/message_handler.cc:239:16
    #29 0x561030c4acfc in dart::MessageHandler::TaskCallback() out/ReleaseASANX64/../../runtime/vm/message_handler.cc:458:18
    #30 0x561030f8d365 in dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseASANX64/../../runtime/vm/thread_pool.cc:158:15
    #31 0x561030f8e77a in dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseASANX64/../../runtime/vm/thread_pool.cc:330:9
    #32 0x561030e3a7f2 in dart::ThreadStart(void*) out/ReleaseASANX64/../../runtime/vm/os_thread_linux.cc:154:5
    #33 0x7f0c27478608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8

SUMMARY: AddressSanitizer: 80 byte(s) leaked in 4 allocation(s).

--- Re-run this test:
python3 tools/test.py -n vm-aot-asan-linux-release-x64 standalone/regress_52715_test/none
```

**Comment by mkustermann** [comment]
I think this is already tracked at https://github.com/dart-lang/sdk/issues/52834

**Comment by sstrickl** [comment]
Note: tracked at #52816.
