### ISSUE TITLE
Some co19 tests crashes on dart2wasm

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52873]
The following co19 tests crashes on dart2wasm
[co19/Language/Generics/scope_t05](https://github.com/dart-lang/co19/blob/master/Language/Generics/scope_t05.dart)
[co19/Language/Interfaces/Combined_Member_Signature/combined_member_signature_A03_t05](https://github.com/dart-lang/co19/blob/master/Language/Interfaces/Combined_Member_Signature/combined_member_signature_A03_t05.dart)
[co19/Language/Interfaces/Combined_Member_Signature/combined_member_signature_A03_t06](https://github.com/dart-lang/co19/blob/master/Language/Interfaces/Combined_Member_Signature/combined_member_signature_A03_t06.dart)

Output is:
```
stdout:
Exception in InstanceTearOff at file:///b/s/w/ir/tests/co19/src/Language/Generics/scope_t05.dart:25:6

stderr:
Unhandled exception:
Null check operator used on a null value
#0      DispatchTable.selectorForTarget (package:dart2wasm/dispatch_table.dart:262)
#1      CodeGenerator._virtualCall (package:dart2wasm/code_generator.dart:1771)
#2      CodeGenerator.visitInstanceTearOff (package:dart2wasm/code_generator.dart:2205)
#3      InstanceTearOff.accept1 (package:kernel/ast.dart:4716)
#4      CodeGenerator.wrap (package:dart2wasm/code_generator.dart:633)
#5      CodeGenerator.visitExpressionStatement (package:dart2wasm/code_generator.dart:1093)
#6      ExpressionStatement.accept (package:kernel/ast.dart:9123)
#7      CodeGenerator.visitStatement (package:dart2wasm/code_generator.dart:644)
#8      CodeGenerator.visitBlock (package:dart2wasm/code_generator.dart:748)
#9      Block.accept (package:kernel/ast.dart:9173)
#10     CodeGenerator.visitStatement (package:dart2wasm/code_generator.dart:644)
#11     CodeGenerator.visitBlockExpression (package:dart2wasm/code_generator.dart:1440)
#12     BlockExpression.accept1 (package:kernel/ast.dart:8778)
#13     CodeGenerator.wrap (package:dart2wasm/code_generator.dart:633)
#14     CodeGenerator.visitExpressionStatement (package:dart2wasm/code_generator.dart:1093)
#15     ExpressionStatement.accept (package:kernel/ast.dart:9123)
#16     CodeGenerator.visitStatement (package:dart2wasm/code_generator.dart:644)
#17     CodeGenerator.visitBlock (package:dart2wasm/code_generator.dart:748)
#18     Block.accept (package:kernel/ast.dart:9173)
#19     CodeGenerator.visitStatement (package:dart2wasm/code_generator.dart:644)
#20     CodeGenerator.generateBody (package:dart2wasm/code_generator.dart:452)
#21     CodeGenerator.generate (package:dart2wasm/code_generator.dart:224)
#22     Translator.translate (package:dart2wasm/translator.dart:345)
#23     compileToModule (package:dart2wasm/compile.dart:120)
<asynchronous suspension>
#24     main (package:dart2wasm/dart2wasm.dart:131)
<asynchronous suspension>
#25     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dart2wasm/bin/dart2wasm.dart:7)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dart2wasm-linux-chrome co19/Language/Generics/scope_t05
```
The same error for the other crashes
These tests works well on othe platforms

**Comment by osa1** [comment]
Full post-TFA kernel for the program:

```
 [@vm.table-selector.metadata=Instance of 'TableSelectorMetadata']library from "file:///usr/local/google/home/omersa/dart/sdk_wasm/test/test.dart" as test {

  abstract interface class I<T extends core::Object? = dynamic> extends core::Object {
[@vm.procedure-attributes.metadata=methodOrSetterCalledDynamically:false,getterCalledDynamically:false,hasThisUses:false,hasNonThisUses:false,hasTearOffUses:false,methodOrSetterSelectorId:1,getterSelectorId:2]    abstract method mi<T extends core::Object? = dynamic>() → void;
  }
  abstract class C1 extends test::I<core::double> {
  }
  abstract class C2 extends core::Object implements test::I<core::double> {
  }
  static method checkStaticType(test::C1 c1, test::C2 c2) → void {
    block {
      [@vm.inferred-type.metadata=!] c1.{test::I::mi}{<T extends core::Object? = dynamic>() → void};
    } =>throw "Attempt to execute code removed by Dart AOT compiler (TFA)";
  }
  static method main() → void {
    core::print(#C1);
  }
}
```

The problem occurs in this part:

```
  static method checkStaticType(test::C1 c1, test::C2 c2) → void {
    block {
      [@vm.inferred-type.metadata=!] c1.{test::I::mi}{<T extends core::Object? = dynamic>() → void};
    } =>throw "Attempt to execute code removed by Dart AOT compiler (TFA)";
  }
```

Here `c1.mi` is an instance tear-off, but there are no implementations of `mi` in the program so we don't generate a selector for it.

I'm not sure why this instance tear-off expression exists. @alexmarkov would it be possible to get rid of it so that the function body will just be a `throw`?

**Comment by alexmarkov** [comment]
Yes, I think we can improve TFA in this case to eliminate the call. I'll look into it.
