### ISSUE TITLE
Null check operator used on a null value thrown in ConstantsTransformer._checkExhaustiveness on Dart 3.0.5 while debugging

### ISSUE THREAD

**Issue by jonas-zebari** [dart-lang/sdk#52905]
**Common Front End (CFE) and kernel**

Dart version: 3.0.5
MacOS
Browser N/A

I run into this error a lot lately while debugging my Flutter application. I believe it has something to do with combing the `??` operator with a `switch expression`, but I'm not 100% sure. I only started getting this crash after I added a new file and started using the above.

For example, a slightly modified version of my code looks like this:

```dart
final backgroundColor = this.backgroundColor ??
        switch (_type) {
          _Type.primary => theme.primary,
          _Type.background => theme.white,
          _Type.outline || _Type.text => theme.transparent,
        };
```

The error is not caught and the app crashes entirely when this happens. Here is the stack trace printed out in the console when it happens:

<details><summary>Stack trace</summary>

```
Unhandled exception:
Null check operator used on a null value
#0      ConstantsTransformer._checkExhaustiveness (package:front_end/src/fasta/kernel/constant_evaluator.dart:1542:43)
#1      ConstantsTransformer.visitSwitchExpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:2045:5)
#2      SwitchExpression.accept1 (package:kernel/src/ast/patterns.dart:1926:14)
#3      RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#4      ConditionalExpression.transformOrRemoveChildren (package:kernel/ast.dart:7466:16)
#5      RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#6      TreeVisitor1.defaultExpression (package:kernel/visitor.dart:547:50)
#7      TreeVisitor1.visitConditionalExpression (package:kernel/visitor.dart:632:7)
#8      ConditionalExpression.accept1 (package:kernel/ast.dart:7424:9)
#9      RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#10     Let.transformOrRemoveChildren (package:kernel/ast.dart:9311:16)
#11     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#12     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:547:50)
#13     TreeVisitor1.visitLet (package:kernel/visitor.dart:698:34)
#14     Let.accept1 (package:kernel/ast.dart:9280:59)
#15     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1970:21)
#16     RemovingTransformer.transformOrRemoveExpression (package:kernel/visitor.dart:1943:12)
#17     ReturnStatement.transformOrRemoveChildren (package:kernel/ast.dart:10808:22)
#18     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#19     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:780:48)
#20     TreeVisitor1.visitReturnStatement (package:kernel/visitor.dart:826:7)
#21     ReturnStatement.accept1 (package:kernel/ast.dart:10790:9)
#22     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#23     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:651:19)
#24     FunctionNode.accept1 (package:kernel/ast.dart:4202:9)
#25     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#26     ConstantsTransformer.visitProcedure.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:552:23)
#27     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:5259:18)
#28     ConstantsTransformer.visitProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:550:23)
#29     transformProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:176:24)
#30     KernelTarget.runProcedureTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1587:15)
#31     IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:2062:28)
<asynchronous suspension>
#32     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:1855:12)
<asynchronous suspension>
#33     FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:973:28)
<asynchronous suspension>
#34     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1409:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
```
</details>

**Comment by jonas-zebari** [comment]
I should add that it's easiest to reproduce by editing a file that contains the sample code and hot reloading.
