### ISSUE TITLE
Dart VM crash on analyzer tests on Mac

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#52907]
With https://dart-review.googlesource.com/c/sdk/+/313221, analyzer tests crash on my Mac.

```
22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64
```

```
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (aa-augment-subtype)$ /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseARM64/dart-sdk/bin/dart --version
Dart SDK version: 3.1.0-edge.f3867e3125771871c99637ed6281ca1242b062b0 (be) (Tue Jul 11 12:22:16 2023 -0700) on "macos_arm64"
```

```
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (aa-augment-subtype)$ d-rta
00:31 +14382: analyzer | src | dart | resolution | AssignmentExpressionResolutionTest | test_simpleIdentifier_thisGetter_thisSetter_fromMixins_compound
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=2, si_addr=0x11
version=3.1.0-edge.3e80d29fd6fec56187d651ce22ea81f1e8732214 (be) (Tue Jul 11 16:19:09 2023 +0000) on "macos_arm64"
pid=96413, thread=11779, isolate_group=main(0x12d814800), isolate=main(0x12d80d600)
os=macos, arch=arm64, comp=no, sim=no
isolate_instructions=1049de500, vm_instructions=1049de500
fp=2a7dfbf58, sp=2a7d1b000, pc=2b7a6505c
  pc 0x00000002b7a6505c fp 0x00000002a7dfbf58 Unknown symbol
-- End of DumpStackTrace
/Users/scheglov/bin/d-rta: line 16: 96413 Abort trap: 6           /Users/scheglov/Applications/dart-sdk/bin/dart --old_gen_growth_rate=10000 --enable_asserts=true -DskipCancelableFutureTests=false -DskipPhysicalResourceProviderTests=true /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/test/test_all.dart

real	0m37.756s
user	0m43.080s
sys	0m3.185s
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (aa-augment-subtype)$ /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseARM64/dart-sdk/bin/dart /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/test/test_all.dart
00:49 +14482 -1: analyzer | src | dart | resolution | AssignmentExpressionResolutionTest | test_simpleIdentifier_thisGetter_thisSetter_fromMixins_compound [E]
  NoSuchMethodError: Class 'bool' has no instance getter 'length'.
  Receiver: false
  Tried calling: length
  #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
  #1      ListIterator.moveNext (dart:_internal/iterable.dart:336:28)
  #2      ClassHierarchy._getHierarchy (package:analyzer/src/dart/element/class_hierarchy.dart:71:42)
  #3      ClassHierarchy.implementedInterfaces (package:analyzer/src/dart/element/class_hierarchy.dart:20:12)
  #4      InterfaceElementImpl.allSupertypes (package:analyzer/src/dart/element/element.dart:3672:43)
  #5      InterfaceTypeImpl.allSupertypes (package:analyzer/src/dart/element/type.dart:508:20)
  #6      InterfacesMerger.addWithSupertypes (package:analyzer/src/dart/element/class_hierarchy.dart:140:34)
  #7      _MixinInference.perform (package:analyzer/src/summary2/types_builder.dart:489:24)
  #8      _MixinsInference._infer (package:analyzer/src/summary2/types_builder.dart:668:46)
  #9      _MixinsInference._inferDeclaration (package:analyzer/src/summary2/types_builder.dart:681:9)
  #10     _MixinsInference.perform (package:analyzer/src/summary2/types_builder.dart:633:7)
  #11     TypesBuilder.build (package:analyzer/src/summary2/types_builder.dart:99:31)
  #12     Linker._resolveTypes (package:analyzer/src/summary2/link.dart:298:24)
  #13     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:131:5)
  <asynchronous suspension>
  #14     Linker.link (package:analyzer/src/summary2/link.dart:96:5)
  <asynchronous suspension>
  #15     link (package:analyzer/src/summary2/link.dart:39:3)
  <asynchronous suspension>
  #16     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:180:24)
  <asynchronous suspension>
  #17     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:246:7)
  <asynchronous suspension>
  #18     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
  <asynchronous suspension>
  #19     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:244:5)
  <asynchronous suspension>
  #20     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1348:9)
  <asynchronous suspension>
  #21     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
  <asynchronous suspension>
  #22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1067:24)
  <asynchronous suspension>
  #23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2249:7)
  <asynchronous suspension>


  #0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:321:5)
  #1      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:188:11)
  <asynchronous suspension>
  #2      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:246:7)
  <asynchronous suspension>
  #3      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
  <asynchronous suspension>
  #4      LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:244:5)
  <asynchronous suspension>
  #5      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1348:9)
  <asynchronous suspension>
  #6      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
  <asynchronous suspension>
  #7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1067:24)
  <asynchronous suspension>
  #8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2249:7)
  <asynchronous suspension>

  package:analyzer/src/dart/analysis/driver.dart 1427:9             AnalysisDriver._computeAnalysisResult.<fn>
  ===== asynchronous gap ===========================
  package:analyzer/src/dart/analysis/performance_logger.dart 50:14  PerformanceLog.runAsync
  ===== asynchronous gap ===========================
  package:analyzer/src/dart/analysis/driver.dart 1067:24            AnalysisDriver.performWork
  ===== asynchronous gap ===========================
  package:analyzer/src/dart/analysis/driver.dart 2249:7             AnalysisDriverScheduler._run


To run this test again: /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseARM64/dart-sdk/bin/dart test . -p vm --plain-name 'analyzer | src | dart | resolution | AssignmentExpressionResolutionTest | test_simpleIdentifier_thisGetter_thisSetter_fromMixins_compound'
00:49 +14627 -1: analyzer | src | dart | resolution | ClassTypeAliasResolutionTest | test_implicitConstructors_const
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=2, si_addr=0x7
version=3.1.0-edge.3e80d29fd6fec56187d651ce22ea81f1e8732214 (be) (Tue Jul 11 16:19:09 2023 +0000) on "macos_arm64"
pid=96594, thread=13595, isolate_group=main(0x147008c00), isolate=main(0x14700f200)
os=macos, arch=arm64, comp=no, sim=no
isolate_instructions=10238e500, vm_instructions=10238e500
fp=2b75fc220, sp=2b751b000, pc=28764884c
  pc 0x000000028764884c fp 0x00000002b75fc220 Unknown symbol
-- End of DumpStackTrace
Abort trap: 6
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (aa-augment-subtype)$ /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseARM64/dart-sdk/bin/dart /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/test/test_all.dart
00:50 +14482: analyzer | src | dart | resolution | AssignmentExpressionResolutionTest | test_simpleIdentifier_thisGetter_thisSetter_fromMixins_compound
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=2, si_addr=0xb3
version=3.1.0-edge.842d109a772daed484ca74367cb832b59d831135 (be) (Tue Jul 11 11:49:45 2023 -0700) on "macos_arm64"
pid=2791, thread=16135, isolate_group=main(0x135034c00), isolate=main(0x135012000)
os=macos, arch=arm64, comp=no, sim=no
isolate_instructions=104c4a500, vm_instructions=104c4a500
fp=16bb77980, sp=16bb77940, pc=104df3c8c
  pc 0x0000000104df3c8c fp 0x000000016bb77980 dart::Class::EnsureIsFinalized(dart::Thread*) const+0x1c
  pc 0x0000000104ebc61c fp 0x000000016bb779e0 dart::PatchableCallHandler::ResolveTargetFunction(dart::Object const&)+0x160
  pc 0x0000000104ebc730 fp 0x000000016bb77a50 dart::PatchableCallHandler::ResolveSwitchAndReturn(dart::Object const&)+0x28
  pc 0x0000000104ebcfc8 fp 0x000000016bb78130 dart::DRT_SwitchableCallMiss(dart::NativeArguments)+0x20c
  pc 0x0000000107882e7c fp 0x000000016bb78170 Unknown symbol
  pc 0x000000010788373c fp 0x000000016bb781b0 Unknown symbol
  pc 0x00000002ba7b4e98 fp 0x000000016bb78278 Unknown symbol
  pc 0x00000002a6eab8a8 fp 0x000000016bb782a8 Unknown symbol
  pc 0x000000017494b8cc fp 0x000000016bb782e8 Unknown symbol
  pc 0x00000002a0c6bc5c fp 0x000000016bb78328 Unknown symbol
  pc 0x00000002a0c6b8f0 fp 0x000000016bb78370 Unknown symbol
  pc 0x00000002a0c6c12c fp 0x000000016bb783c8 Unknown symbol
  pc 0x00000001748c7a30 fp 0x000000016bb78428 Unknown symbol
  pc 0x00000002a3d9db68 fp 0x000000016bb78468 Unknown symbol
  pc 0x00000002a3de54e8 fp 0x000000016bb784d8 Unknown symbol
  pc 0x00000002bab4f7e0 fp 0x000000016bb78570 Unknown symbol
  pc 0x000000017fb1fc94 fp 0x000000016bb785c0 Unknown symbol
  pc 0x00000002ba79b83c fp 0x000000016bb78670 Unknown symbol
  pc 0x0000000170bb90f8 fp 0x000000016bb786b8 Unknown symbol
  pc 0x0000000170bb1d50 fp 0x000000016bb78750 Unknown symbol
  pc 0x0000000170bb3550 fp 0x000000016bb787a8 Unknown symbol
  pc 0x0000000170bb2f80 fp 0x000000016bb78838 Unknown symbol
  pc 0x0000000170bc0e64 fp 0x000000016bb788b8 Unknown symbol
  pc 0x000000017d16ed38 fp 0x000000016bb78930 Unknown symbol
  pc 0x000000017e1aa058 fp 0x000000016bb78970 Unknown symbol
  pc 0x000000010788ca50 fp 0x000000016bb789a0 Unknown symbol
  pc 0x0000000170bb90f8 fp 0x000000016bb789e8 Unknown symbol
  pc 0x0000000170bb1d50 fp 0x000000016bb78a80 Unknown symbol
  pc 0x0000000170bb3550 fp 0x000000016bb78ad8 Unknown symbol
  pc 0x0000000170bb2f80 fp 0x000000016bb78b68 Unknown symbol
  pc 0x0000000170bc0e64 fp 0x000000016bb78be8 Unknown symbol
  pc 0x000000017d16ed38 fp 0x000000016bb78c60 Unknown symbol
  pc 0x000000017e1aa058 fp 0x000000016bb78ca0 Unknown symbol
  pc 0x000000010788ca50 fp 0x000000016bb78cd0 Unknown symbol
  pc 0x0000000170bb90f8 fp 0x000000016bb78d18 Unknown symbol
  pc 0x0000000170bb1d50 fp 0x000000016bb78db0 Unknown symbol
  pc 0x0000000170bb3550 fp 0x000000016bb78e08 Unknown symbol
  pc 0x0000000170bb2f80 fp 0x000000016bb78e98 Unknown symbol
  pc 0x0000000170bc0e64 fp 0x000000016bb78f18 Unknown symbol
  pc 0x000000017d16ed38 fp 0x000000016bb78f90 Unknown symbol
  pc 0x0000000173d2a4b4 fp 0x000000016bb78fd0 Unknown symbol
  pc 0x000000010788cad0 fp 0x000000016bb79000 Unknown symbol
  pc 0x0000000170bb90f8 fp 0x000000016bb79048 Unknown symbol
  pc 0x0000000170bb1d50 fp 0x000000016bb790e0 Unknown symbol
  pc 0x0000000170bb3550 fp 0x000000016bb79138 Unknown symbol
  pc 0x0000000170bb2f80 fp 0x000000016bb791c8 Unknown symbol
  pc 0x0000000170bc0e64 fp 0x000000016bb79248 Unknown symbol
  pc 0x000000017d16ed38 fp 0x000000016bb792c0 Unknown symbol
  pc 0x000000017e1aa058 fp 0x000000016bb79300 Unknown symbol
  pc 0x000000010788ca50 fp 0x000000016bb79330 Unknown symbol
  pc 0x0000000170bb90f8 fp 0x000000016bb79378 Unknown symbol
  pc 0x0000000170bb1d50 fp 0x000000016bb79410 Unknown symbol
  pc 0x0000000170bb3550 fp 0x000000016bb79468 Unknown symbol
  pc 0x0000000170bb2f80 fp 0x000000016bb794f8 Unknown symbol
  pc 0x0000000170bc0e64 fp 0x000000016bb79578 Unknown symbol
  pc 0x000000017d16ed38 fp 0x000000016bb795f0 Unknown symbol
  pc 0x000000017e1aa058 fp 0x000000016bb79630 Unknown symbol
  pc 0x000000010788ca50 fp 0x000000016bb79660 Unknown symbol
  pc 0x0000000170bb90f8 fp 0x000000016bb796a8 Unknown symbol
  pc 0x0000000170bb1d50 fp 0x000000016bb79740 Unknown symbol
  pc 0x0000000170bb3550 fp 0x000000016bb79798 Unknown symbol
  pc 0x0000000170bb2f80 fp 0x000000016bb79828 Unknown symbol
  pc 0x0000000170bc0e64 fp 0x000000016bb798a8 Unknown symbol
  pc 0x000000017d16ed38 fp 0x000000016bb79920 Unknown symbol
  pc 0x000000017e1aa058 fp 0x000000016bb79960 Unknown symbol
  pc 0x000000010788ca50 fp 0x000000016bb79990 Unknown symbol
  pc 0x0000000170bb90f8 fp 0x000000016bb799d8 Unknown symbol
  pc 0x0000000170bb1d50 fp 0x000000016bb79a70 Unknown symbol
  pc 0x0000000170bb3550 fp 0x000000016bb79ac8 Unknown symbol
  pc 0x0000000170bb2f80 fp 0x000000016bb79b58 Unknown symbol
  pc 0x0000000170bc0e64 fp 0x000000016bb79bd8 Unknown symbol
  pc 0x000000017d16ed38 fp 0x000000016bb79c50 Unknown symbol
  pc 0x000000017e1aa058 fp 0x000000016bb79c90 Unknown symbol
  pc 0x000000010788ca50 fp 0x000000016bb79cc0 Unknown symbol
  pc 0x0000000170bb90f8 fp 0x000000016bb79d08 Unknown symbol
  pc 0x0000000170bb1d50 fp 0x000000016bb79da0 Unknown symbol
  pc 0x0000000170bb3550 fp 0x000000016bb79df8 Unknown symbol
  pc 0x0000000170bb2f80 fp 0x000000016bb79e88 Unknown symbol
  pc 0x0000000170bc0e64 fp 0x000000016bb79f08 Unknown symbol
  pc 0x000000017d16ed38 fp 0x000000016bb79f80 Unknown symbol
  pc 0x000000017e1aa058 fp 0x000000016bb79fc0 Unknown symbol
  pc 0x000000010788ca50 fp 0x000000016bb79ff0 Unknown symbol
  pc 0x0000000170bb90f8 fp 0x000000016bb7a038 Unknown symbol
  pc 0x0000000170bb1d50 fp 0x000000016bb7a0d0 Unknown symbol
  pc 0x0000000170bb3550 fp 0x000000016bb7a128 Unknown symbol
  pc 0x0000000171ee58a8 fp 0x000000016bb7a1b8 Unknown symbol
  pc 0x000000016b5b50bc fp 0x000000016bb7a248 Unknown symbol
  pc 0x0000000170bb346c fp 0x000000016bb7a298 Unknown symbol
  pc 0x0000000170bb69fc fp 0x000000016bb7a348 Unknown symbol
  pc 0x0000000170bbb934 fp 0x000000016bb7a380 Unknown symbol
  pc 0x000000017eebcdf8 fp 0x000000016bb7a3e8 Unknown symbol
  pc 0x0000000171ef7dc4 fp 0x000000016bb7a410 Unknown symbol
  pc 0x0000000175a468e0 fp 0x000000016bb7a4f8 Unknown symbol
  pc 0x000000017d196218 fp 0x000000016bb7a528 Unknown symbol
  pc 0x000000017e53bab8 fp 0x000000016bb7a610 Unknown symbol
  pc 0x00000001731a7c0c fp 0x000000016bb7a658 Unknown symbol
  pc 0x0000000107883404 fp 0x000000016bb7a730 Unknown symbol
  pc 0x0000000104d86494 fp 0x000000016bb7a7a0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&)+0x18c
  pc 0x0000000104d880c4 fp 0x000000016bb7a7e0 dart::DartLibraryCalls::HandleMessage(long long, dart::Instance const&)+0x130
  pc 0x0000000104da9cf4 fp 0x000000016bb7ad90 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message>>)+0x2b4
  pc 0x0000000104dcef64 fp 0x000000016bb7ae00 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x134
  pc 0x0000000104dcf650 fp 0x000000016bb7ae60 dart::MessageHandler::TaskCallback()+0x208
  pc 0x0000000104eedbcc fp 0x000000016bb7af20 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x14c
  pc 0x0000000104eedfa4 fp 0x000000016bb7af50 dart::ThreadPool::Worker::Main(unsigned long)+0x84
  pc 0x0000000104e6ecb4 fp 0x000000016bb7afc0 dart::OSThread::GetMaxStackSize()+0xd4
  pc 0x0000000187e77fa8 fp 0x000000016bb7afe0 _pthread_start+0x94
-- End of DumpStackTrace
  pc 0x0000000000000000 fp 0x000000016bb78170 sp 0x0000000000000000 [Stub] CallToRuntime
  pc 0x000000010788373c fp 0x000000016bb781b0 sp 0x000000016bb78180 [Stub] SwitchableCallMiss
  pc 0x00000002ba7b4e98 fp 0x000000016bb78278 sp 0x000000016bb781c0 [Optimized] ClassHierarchy._getHierarchy@1314481440
  pc 0x00000002a6eab8a8 fp 0x000000016bb782a8 sp 0x000000016bb78288 [Optimized] ClassHierarchy.implementedInterfaces
  pc 0x000000017494b8cc fp 0x000000016bb782e8 sp 0x000000016bb782b8 [Unoptimized] InterfaceElementImpl.get:allSupertypes
  pc 0x00000002a0c6bc5c fp 0x000000016bb78328 sp 0x000000016bb782f8 [Unoptimized] InterfaceTypeImpl.get:allSupertypes
  pc 0x00000002a0c6b8f0 fp 0x000000016bb78370 sp 0x000000016bb78338 [Unoptimized] InterfacesMerger.addWithSupertypes
  pc 0x00000002a0c6c12c fp 0x000000016bb783c8 sp 0x000000016bb78380 [Unoptimized] _MixinInference@1953044424.perform
  pc 0x00000001748c7a30 fp 0x000000016bb78428 sp 0x000000016bb783d8 [Unoptimized] _MixinsInference@1953044424._infer@1953044424
  pc 0x00000002a3d9db68 fp 0x000000016bb78468 sp 0x000000016bb78438 [Optimized] _MixinsInference@1953044424._inferDeclaration@1953044424
  pc 0x00000002a3de54e8 fp 0x000000016bb784d8 sp 0x000000016bb78478 [Optimized] _MixinsInference@1953044424.perform
  pc 0x00000002bab4f7e0 fp 0x000000016bb78570 sp 0x000000016bb784e8 [Optimized] TypesBuilder.build
  pc 0x000000017fb1fc94 fp 0x000000016bb785c0 sp 0x000000016bb78580 [Optimized] Linker._resolveTypes@1908299033
  pc 0x00000002ba79b83c fp 0x000000016bb78670 sp 0x000000016bb785d0 [Optimized] Linker._buildOutlines@1908299033
  pc 0x0000000170bb90f8 fp 0x000000016bb786b8 sp 0x000000016bb78680 [Optimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x0000000170bb1d50 fp 0x000000016bb78750 sp 0x000000016bb786c8 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb3550 fp 0x000000016bb787a8 sp 0x000000016bb78760 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb2f80 fp 0x000000016bb78838 sp 0x000000016bb787b8 [Optimized] _FutureListener@4048458.handleValue
  pc 0x0000000170bc0e64 fp 0x000000016bb788b8 sp 0x000000016bb78848 [Optimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000017d16ed38 fp 0x000000016bb78930 sp 0x000000016bb788c8 [Optimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000017e1aa058 fp 0x000000016bb78970 sp 0x000000016bb78940 [Optimized] _SuspendState@4048458._returnAsync@4048458
  pc 0x000000010788ca50 fp 0x000000016bb789a0 sp 0x000000016bb78980 [Stub] ReturnAsync
  pc 0x0000000170bb90f8 fp 0x000000016bb789e8 sp 0x000000016bb789b0 [Optimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x0000000170bb1d50 fp 0x000000016bb78a80 sp 0x000000016bb789f8 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb3550 fp 0x000000016bb78ad8 sp 0x000000016bb78a90 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb2f80 fp 0x000000016bb78b68 sp 0x000000016bb78ae8 [Optimized] _FutureListener@4048458.handleValue
  pc 0x0000000170bc0e64 fp 0x000000016bb78be8 sp 0x000000016bb78b78 [Optimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000017d16ed38 fp 0x000000016bb78c60 sp 0x000000016bb78bf8 [Optimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000017e1aa058 fp 0x000000016bb78ca0 sp 0x000000016bb78c70 [Optimized] _SuspendState@4048458._returnAsync@4048458
  pc 0x000000010788ca50 fp 0x000000016bb78cd0 sp 0x000000016bb78cb0 [Stub] ReturnAsync
  pc 0x0000000170bb90f8 fp 0x000000016bb78d18 sp 0x000000016bb78ce0 [Optimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x0000000170bb1d50 fp 0x000000016bb78db0 sp 0x000000016bb78d28 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb3550 fp 0x000000016bb78e08 sp 0x000000016bb78dc0 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb2f80 fp 0x000000016bb78e98 sp 0x000000016bb78e18 [Optimized] _FutureListener@4048458.handleValue
  pc 0x0000000170bc0e64 fp 0x000000016bb78f18 sp 0x000000016bb78ea8 [Optimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000017d16ed38 fp 0x000000016bb78f90 sp 0x000000016bb78f28 [Optimized] _Future@4048458._propagateToListeners@4048458
  pc 0x0000000173d2a4b4 fp 0x000000016bb78fd0 sp 0x000000016bb78fa0 [Optimized] _SuspendState@4048458._returnAsyncNotFuture@4048458
  pc 0x000000010788cad0 fp 0x000000016bb79000 sp 0x000000016bb78fe0 [Stub] ReturnAsyncNotFuture
  pc 0x0000000170bb90f8 fp 0x000000016bb79048 sp 0x000000016bb79010 [Optimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x0000000170bb1d50 fp 0x000000016bb790e0 sp 0x000000016bb79058 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb3550 fp 0x000000016bb79138 sp 0x000000016bb790f0 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb2f80 fp 0x000000016bb791c8 sp 0x000000016bb79148 [Optimized] _FutureListener@4048458.handleValue
  pc 0x0000000170bc0e64 fp 0x000000016bb79248 sp 0x000000016bb791d8 [Optimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000017d16ed38 fp 0x000000016bb792c0 sp 0x000000016bb79258 [Optimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000017e1aa058 fp 0x000000016bb79300 sp 0x000000016bb792d0 [Optimized] _SuspendState@4048458._returnAsync@4048458
  pc 0x000000010788ca50 fp 0x000000016bb79330 sp 0x000000016bb79310 [Stub] ReturnAsync
  pc 0x0000000170bb90f8 fp 0x000000016bb79378 sp 0x000000016bb79340 [Optimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x0000000170bb1d50 fp 0x000000016bb79410 sp 0x000000016bb79388 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb3550 fp 0x000000016bb79468 sp 0x000000016bb79420 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb2f80 fp 0x000000016bb794f8 sp 0x000000016bb79478 [Optimized] _FutureListener@4048458.handleValue
  pc 0x0000000170bc0e64 fp 0x000000016bb79578 sp 0x000000016bb79508 [Optimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000017d16ed38 fp 0x000000016bb795f0 sp 0x000000016bb79588 [Optimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000017e1aa058 fp 0x000000016bb79630 sp 0x000000016bb79600 [Optimized] _SuspendState@4048458._returnAsync@4048458
  pc 0x000000010788ca50 fp 0x000000016bb79660 sp 0x000000016bb79640 [Stub] ReturnAsync
  pc 0x0000000170bb90f8 fp 0x000000016bb796a8 sp 0x000000016bb79670 [Optimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x0000000170bb1d50 fp 0x000000016bb79740 sp 0x000000016bb796b8 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb3550 fp 0x000000016bb79798 sp 0x000000016bb79750 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb2f80 fp 0x000000016bb79828 sp 0x000000016bb797a8 [Optimized] _FutureListener@4048458.handleValue
  pc 0x0000000170bc0e64 fp 0x000000016bb798a8 sp 0x000000016bb79838 [Optimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000017d16ed38 fp 0x000000016bb79920 sp 0x000000016bb798b8 [Optimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000017e1aa058 fp 0x000000016bb79960 sp 0x000000016bb79930 [Optimized] _SuspendState@4048458._returnAsync@4048458
  pc 0x000000010788ca50 fp 0x000000016bb79990 sp 0x000000016bb79970 [Stub] ReturnAsync
  pc 0x0000000170bb90f8 fp 0x000000016bb799d8 sp 0x000000016bb799a0 [Optimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x0000000170bb1d50 fp 0x000000016bb79a70 sp 0x000000016bb799e8 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb3550 fp 0x000000016bb79ac8 sp 0x000000016bb79a80 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb2f80 fp 0x000000016bb79b58 sp 0x000000016bb79ad8 [Optimized] _FutureListener@4048458.handleValue
  pc 0x0000000170bc0e64 fp 0x000000016bb79bd8 sp 0x000000016bb79b68 [Optimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000017d16ed38 fp 0x000000016bb79c50 sp 0x000000016bb79be8 [Optimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000017e1aa058 fp 0x000000016bb79c90 sp 0x000000016bb79c60 [Optimized] _SuspendState@4048458._returnAsync@4048458
  pc 0x000000010788ca50 fp 0x000000016bb79cc0 sp 0x000000016bb79ca0 [Stub] ReturnAsync
  pc 0x0000000170bb90f8 fp 0x000000016bb79d08 sp 0x000000016bb79cd0 [Optimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x0000000170bb1d50 fp 0x000000016bb79da0 sp 0x000000016bb79d18 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb3550 fp 0x000000016bb79df8 sp 0x000000016bb79db0 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb2f80 fp 0x000000016bb79e88 sp 0x000000016bb79e08 [Optimized] _FutureListener@4048458.handleValue
  pc 0x0000000170bc0e64 fp 0x000000016bb79f08 sp 0x000000016bb79e98 [Optimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000017d16ed38 fp 0x000000016bb79f80 sp 0x000000016bb79f18 [Optimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000017e1aa058 fp 0x000000016bb79fc0 sp 0x000000016bb79f90 [Optimized] _SuspendState@4048458._returnAsync@4048458
  pc 0x000000010788ca50 fp 0x000000016bb79ff0 sp 0x000000016bb79fd0 [Stub] ReturnAsync
  pc 0x0000000170bb90f8 fp 0x000000016bb7a038 sp 0x000000016bb7a000 [Optimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x0000000170bb1d50 fp 0x000000016bb7a0d0 sp 0x000000016bb7a048 [Optimized] _rootRunUnary@4048458
  pc 0x0000000170bb3550 fp 0x000000016bb7a128 sp 0x000000016bb7a0e0 [Optimized] _rootRunUnary@4048458
  pc 0x0000000171ee58a8 fp 0x000000016bb7a1b8 sp 0x000000016bb7a138 [Optimized] _SuspendState@4048458._awaitCompletedFuture@4048458.run
  pc 0x000000016b5b50bc fp 0x000000016bb7a248 sp 0x000000016bb7a1c8 [Optimized] _rootRun@4048458
  pc 0x0000000170bb346c fp 0x000000016bb7a298 sp 0x000000016bb7a258 [Optimized] _rootRun@4048458
  pc 0x0000000170bb69fc fp 0x000000016bb7a348 sp 0x000000016bb7a2a8 [Optimized] _CustomZone@4048458.runGuarded
  pc 0x0000000170bbb934 fp 0x000000016bb7a380 sp 0x000000016bb7a358 [Optimized] _CustomZone@4048458.bindCallbackGuarded.<anonymous closure>
  pc 0x000000017eebcdf8 fp 0x000000016bb7a3e8 sp 0x000000016bb7a390 [Optimized] _startMicrotaskLoop@4048458
  pc 0x0000000171ef7dc4 fp 0x000000016bb7a410 sp 0x000000016bb7a3f8 [Optimized] _startMicrotaskLoop@4048458
  pc 0x0000000175a468e0 fp 0x000000016bb7a4f8 sp 0x000000016bb7a420 [Optimized] _Timer@1026248._runTimers@1026248
  pc 0x000000017d196218 fp 0x000000016bb7a528 sp 0x000000016bb7a508 [Optimized] _Timer@1026248._handleMessage@1026248
  pc 0x000000017e53bab8 fp 0x000000016bb7a610 sp 0x000000016bb7a538 [Optimized] _Closure@0150898.dyn:call
  pc 0x00000001731a7c0c fp 0x000000016bb7a658 sp 0x000000016bb7a620 [Optimized] _RawReceivePort@1026248._handleMessage@1026248
  pc 0x0000000107883404 fp 0x000000016bb7a730 sp 0x000000016bb7a668 [Stub] InvokeDartCode
Abort trap: 6
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (aa-augment-subtype)$
```

**Comment by a-siva** [comment]
@scheglov is this a one off kind of crash or are you able to reproduce it consistently?

**Comment by a-siva** [comment]
Ok, I am going to mark this issue as fixed. If you run into a crash again please reopen the issue.
