### ISSUE TITLE
[gardening] Flaky standalone/io/http_response_deadline_test/

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52916]
There are new test failures on [[vm] Clean up New() methods of Dart classes....Bump linter to 655de5d0dc30cdd1df9ce4cd16bd7489106d987f](https://github.com/dart-lang/sdk/compare/23f414520647df3719da1a94f19237955a0f5fc2~...86d1261dff279acf84bc699c6c116189955b0076).

The tests
```
standalone/io/http_response_deadline_test/2 RuntimeError (expected Pass)
```
are failing on configurations
```
vm-linux-release-arm64
```

Meta flake history: https://dart-ci.web.app/#showLatestFailures=false&test=standalone/io/http_response_deadline_test/2&configurations=vm-linux-release-arm64

However, this seems to be a new failure:

```
/=========================================================================================\
| standalone/io/http_response_deadline_test/1 broke (Pass -> RuntimeError, expected Pass) |
\=========================================================================================/

--- Command "vm" (took 22.000826s):
DART_CONFIGURATION=ReleaseXARM64 out/ReleaseXARM64/dart --short_socket_read --sound-null-safety -Dtest_runner.configuration=vm-linux-release-arm64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/standalone/io/http_response_deadline_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(at index 0: Expected <stuff>, Found: <missing or invalid authentication code...>) fails.
#0      Expect._fail (package:expect/expect.dart:696:5)
#1      Expect.equals (package:expect/expect.dart:115:9)
#2      testDeadlineAndDetach.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/http_response_deadline_test.dart:84:18)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#4      testDeadlineAndDetach.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/http_response_deadline_test.dart:88:31)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-linux-release-arm64 standalone/io/http_response_deadline_test/1
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8775967008881223121/+/u/test_results/ignored_flaky_test_failure_logs

The flaky failures look like:

```
/=========================================================================================\
| standalone/io/http_response_deadline_test/3 broke (Pass -> RuntimeError, expected Pass) |
\=========================================================================================/

--- Command "vm" (took 19.000220s):
DART_CONFIGURATION=ReleaseXARM64 out/ReleaseXARM64/dart --short_socket_read --short_socket_write --sound-null-safety -Dtest_runner.configuration=vm-linux-release-arm64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/standalone/io/http_response_deadline_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.fail('Expected error')
#0      Expect._fail (package:expect/expect.dart:696:5)
#1      Expect.fail (package:expect/expect.dart:280:5)
#2      testExceedDeadline.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/http_response_deadline_test.dart:50:16)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#4      testExceedDeadline.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/http_response_deadline_test.dart:55:31)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-linux-release-arm64 standalone/io/http_response_deadline_test/3
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8776194953081260753/+/u/test_results/ignored_flaky_test_failure_logs

**Comment by dcharkes** [comment]
@brianquinlan you're in charge of `dart:io` now right? I don't think I've ever seen such error before in a test locally setting up an HTTP connection.
