### ISSUE TITLE
Analyzer crashes when files like `allowed_experiments.json` are manipulated by other (Dart) processes

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#52930]
I was running `flutter analyze --watch --write /tmp/analysis --flutter-repo` in one window and running tests in another when the analyzer window suddenly died (well, hung, it didn't return to the command line but also didn't do anything anymore) after dumping this error:

```
Error response from the server:
SERVER_ERROR
PathNotFoundException(path=/home/ianh/dev/flutter/bin/cache/dart-sdk/lib/_internal/allowed_experiments.json; message=Cannot open file)
#0 _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:159:7)
#1 _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:196:18)
#2 FolderBasedDartSdk.allowedExperimentsJson (package:analyzer/src/dart/sdk/sdk.dart:407:10)
#3 FeatureSetProvider._experimentsForSdk (package:analyzer/src/dart/analysis/feature_set_provider.dart:152:34)
#4 FeatureSetProvider.build(package:analyzer/src/dart/analysis/feature_set_provider.dart:139:30)
#5 AnalysisDriver._createFileTracker (package:analyzer/src/dart/analysis/driver.dart:1549:45)
#6 new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:308:5)
#7 ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:136:18)
#8 newAnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:97:36)
#9 ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded.performContextRebuild (package:analysis_server/src/context_manager.dart:552:40)
<asynchronous suspension>
#10 ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded (package:analysis_server/src/context_manager.dart:704:11)
<asynchronous suspension>
#11 _CancellingTaskQueue.queue.<anonymous closure> (package:analysis_server/src/context_manager.dart:991:15)
<asynchronous suspension>
#12 ContextManagerImpl._handleWatchEventImpl.<anonymous closure> package:analysis_server/src/context_manager.dart:812:38)
<asynchronous suspension>
```

In general the analyzer seems to be brittle around other processes modifying files it assumes will be available, I've seen other similar crashes in the past talking about different files missing.

**Comment by srawlins** [comment]
CC @scheglov

**Comment by Hixie** [comment]
Actually it doesn't seem to hang permanently, eventually it comes back and reports `Required library 'dart:core' is missing` for zillions of files (but not all of them). In any case though, it gets in a bad state and I have to restart it.

**Comment by Hixie** [comment]
I get this basically all the time now when switching branches while developing on Flutter, it's probably the biggest factor impacting my engineering productivity (because restarting the analyzer takes so long).

**Comment by srawlins** [comment]
It's been a while since we tried to collect data on this, and I think I've only tried with synthetic data.

Can you give a consistent repro? Like if you have two open PRs and you `git checkout` between the two branches? Or maybe it's important to have one branch a few days out-of-date?

**Comment by Hixie** [comment]
It doesn't seem to matter much how different the branches are.

In window A I run: `(cd ~/dev/flutter; flutter update-packages; flutter analyze --watch --write /tmp/analysis.flutter --flutter-repo)`

I wait for this to be done analyzing.

In window B I run: `git checkout main; git fetch origin; git rebase origin/main`

I wait for window A to be done analyzing.

Then I run: `git checkout another-branch; git fetch origin; git rebase origin/main`

...where 'another-branch' is some branch I'm working on, that has minimal changes.

But actually I found that if you just delete `flutter/bin/cache/dart-sdk/lib/_internal/allowed_experiments.js` and then start the analyzer, you get the same crash reliably, so maybe that's a place to start.

**Comment by scheglov** [comment]
I'm not sure that [this](https://dart-review.googlesource.com/c/sdk/+/339220) is the path to the solution of the issue.
`allowed_experiments.json` might be just the first place where it fails.
What about other files?
How will it work when we don't have `dart:core`?

**Comment by scheglov** [comment]
@bwilkerson said in [CL](https://dart-review.googlesource.com/c/sdk/+/339220) "possibly a reasonable step forward."

I don't agree. Dart SDK has `allowed_experiments.json` file. If it does not, it is not a valid Dart SDK, and pretending that it is by ignoring the error is just hiding the issue. SDK is either fully valid, or not. If it is not valid, we should refuse using it.

It is normal for the command line analyzer to crash, or report a friendlier error, if Dart SDK is not valid.

I think DAS should not proceed with analysis if Dart SDK, and wait until there is one. Maybe report this to the user somehow.

**Comment by srawlins** [comment]
> I think DAS should not proceed with analysis if Dart SDK, and wait until there is one. Maybe report this to the user somehow.

Sounds good.

**Comment by srawlins** [comment]
I didn't understand the problem fully earlier, but now that I see that it is only a problem if:

* using `flutter analyze --watch`
* while analyzing the Flutter and Dart SDKs in use

I'm downgrading the priority.
