### ISSUE TITLE
weak_cache fails to build -- Invalid argument(s): Type parameter TypeParameter(CacheStrongSnapshot.K) is not indexed

### ISSUE THREAD

**Issue by dannydulai** [dart-lang/sdk#52966]
The weak_cache package fails to build on 3.10.6. All you have to do is import it.

I put in an issue [on that project](https://github.com/Zekfad/weak_cache/issues/1) and they asked me to put it here.

```
% flutter --version
Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (5 days ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1
```
```
% flutter run
Launching lib/main.dart on Pixel 6 Pro in debug mode...
Unhandled exception:
Invalid argument(s): Type parameter TypeParameter(CacheStrongSnapshot.K) is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:3422:8)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2573:38)
#2      TypeParameterType.accept (package:kernel/ast.dart:13247:42)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#4      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#5      BinaryPrinter.visitRecordType (package:kernel/binary/ast_to_binary.dart:2557:5)
#6      RecordType.accept (package:kernel/ast.dart:13400:14)
#7      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#8      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#9      BinaryPrinter.visitSupertype (package:kernel/binary/ast_to_binary.dart:2525:7)
#10     Supertype.accept (package:kernel/ast.dart:13752:34)
#11     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:446:10)
#12     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:347:7)
#13     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1286:5)
#14     Class.accept (package:kernel/ast.dart:1481:38)
#15     BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:488:10)
#16     BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:374:7)
#17     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1126:5)
#18     Library.accept (package:kernel/ast.dart:587:38)
#19     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:467:10)
#20     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:780:9)
#21     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:619:7)
#22     Timeline.timeSync (dart:developer/timeline.dart:166:22)
#23     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:600:14)
#24     IncrementalSerializer.serialize (package:front_end/src/fasta/incremental_serializer.dart:308:13)
#25     IncrementalSerializer.writePackagesToSinkAndTrimComponent (package:front_end/src/fasta/incremental_serializer.dart:158:24)
#26     FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:827:29)
#27     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:645:13)
<asynchronous suspension>
#28     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1308:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Running Gradle task 'assembleDebug'...                                 
```

**Comment by johnniwinther** [comment]
Judging by the stack trace, this seems to have been fixed https://dart-review.googlesource.com/c/sdk/+/304001 which is available in `3.1.0-163.1.beta`.
