### ISSUE TITLE
Dart compiler fatal exception on flutter hot-reload.

### ISSUE THREAD

**Issue by mrcsh** [dart-lang/sdk#53008]
I am not 100% sure this is the correct spot to file this, but I am pretty sure the issue I am seeing is the compiler.

When working on my flutter app, I randomly but often see the following crash during a hot-reload.
The app continues to operate, but no further interaction with the debugger is possible.

```
flutter: DEBUG 05:37:59.769:RemoteStatusBloc.reload/90:already loading...
Unhandled exception:
Null check operator used on a null value
#0      ConstantsTransformer._checkExhaustiveness (package:front_end/src/fasta/kernel/constant_evaluator.dart:1542:43)
#1      ConstantsTransformer.visitSwitchExpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:2045:5)
#2      SwitchExpression.accept1 (package:kernel/src/ast/patterns.dart:1926:14)
#3      RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1970:21)
#4      RemovingTransformer.transformOrRemoveExpression (package:kernel/visitor.dart:1943:12)
#5      ReturnStatement.transformOrRemoveChildren (package:kernel/ast.dart:10808:22)
#6      RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#7      TreeVisitor1.defaultStatement (package:kernel/visitor.dart:780:48)
#8      TreeVisitor1.visitReturnStatement (package:kernel/visitor.dart:826:7)
#9      ReturnStatement.accept1 (package:kernel/ast.dart:10790:9)
#10     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1970:21)
#11     ConstantsTransformer.visitBlock (package:front_end/src/fasta/kernel/constant_evaluator.dart:831:27)
#12     Block.accept1 (package:kernel/ast.dart:9774:58)
#13     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#14     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:651:19)
#15     FunctionNode.accept1 (package:kernel/ast.dart:4202:9)
#16     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#17     FunctionExpression.transformOrRemoveChildren (package:kernel/ast.dart:9190:20)
#18     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#19     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:547:50)
#20     TreeVisitor1.visitFunctionExpression (package:kernel/visitor.dart:681:7)
#21     FunctionExpression.accept1 (package:kernel/ast.dart:9170:9)
#22     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#23     NamedExpression.transformOrRemoveChildren (package:kernel/ast.dart:5845:17)
#24     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#25     TreeVisitor1.visitNamedExpression (package:kernel/visitor.dart:896:7)
#26     NamedExpression.accept1 (package:kernel/ast.dart:5825:9)
#27     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1970:21)
#28     RemovingTransformer.transformList (package:kernel/visitor.dart:2203:19)
#29     RemovingTransformer.transformNamedExpressionList (package:kernel/visitor.dart:2139:5)
#30     Arguments.transformOrRemoveChildren (package:kernel/ast.dart:5769:7)
#31     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#32     TreeVisitor1.visitArguments (package:kernel/visitor.dart:894:46)
#33     Arguments.accept1 (package:kernel/ast.dart:5749:53)
#34     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#35     ConstructorInvocation.transformOrRemoveChildren (package:kernel/ast.dart:7144:21)
#36     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#37     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:547:50)
#38     TreeVisitor1.visitConstructorInvocation (package:kernel/visitor.dart:622:7)
#39     ConstantsTransformer.visitConstructorInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:2171:18)
#40     ConstructorInvocation.accept1 (package:kernel/ast.dart:7123:9)
#41     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1970:21)
#42     RemovingTransformer.transformList (package:kernel/visitor.dart:2203:19)
#43     RemovingTransformer.transformExpressionList (package:kernel/visitor.dart:2129:5)
#44     ListLiteral.transformOrRemoveChildren (package:kernel/ast.dart:8721:7)
#45     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#46     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:547:50)
#47     TreeVisitor1.visitListLiteral (package:kernel/visitor.dart:668:50)
#48     ConstantsTransformer.visitListLiteral (package:front_end/src/fasta/kernel/constant_evaluator.dart:2078:18)
#49     ListLiteral.accept1 (package:kernel/ast.dart:8704:9)
#50     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1970:21)
#51     RemovingTransformer.transformOrRemoveExpression (package:kernel/visitor.dart:1943:12)
#52     ReturnStatement.transformOrRemoveChildren (package:kernel/ast.dart:10808:22)
#53     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#54     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:780:48)
#55     TreeVisitor1.visitReturnStatement (package:kernel/visitor.dart:826:7)
#56     ReturnStatement.accept1 (package:kernel/ast.dart:10790:9)
#57     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#58     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:651:19)
#59     FunctionNode.accept1 (package:kernel/ast.dart:4202:9)
#60     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#61     ConstantsTransformer.visitProcedure.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:552:23)
#62     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:5259:18)
#63     ConstantsTransformer.visitProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:550:23)
#64     transformProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:176:24)
#65     KernelTarget.runProcedureTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1587:15)
#66     IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:2062:28)
<asynchronous suspension>
#67     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:1855:12)
<asynchronous suspension>
#68     FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:973:28)
<asynchronous suspension>
#69     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1409:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.

```

here's the flutter doctor output 
```
flutter doctor -v                        
[✓] Flutter (Channel stable, 3.10.6, on Fedora Linux 38 (Thirty Eight)
    6.3.12-200.fc38.x86_64, locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at /server/home/csh/lib/flutter3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (9 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/csh/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /server/home/csh/lib/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-2.fc38)
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /server/home/csh/lib/android-studio
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13
      (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux
      38 (Thirty Eight) 6.3.12-200.fc38.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google
      Chrome 115.0.5790.98

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
and dart version

```
dart --version      
Dart SDK version: 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "linux_x64"
```

**Comment by mrcsh** [comment]
Maybe a clue? (Since I have seen this happen before today but much less frequently)
This is some fairly new code that was added to what I was working on when the crash became quite frequent.

```
errorText: (final s) => switch (0) {
              0 when s.restorePassword.value.length >= 8 && s.restoreData == null =>
                'decrypt.failed'.xlate,
              _ => null,
            },
```
It did not happen after I replaced it with the equivalent ternary 
but did crash twice (on hot-reload) when I had the more or less final code of

```
errorText: (final s) => switch (s.restorePassword.value.length) {
              0 => null,
              < 8 => 'invalid.password'.xlate,
              >= 8 when s.restoreData == null => 'decrypt.failed'.xlate,
              _ => null,
            },
```

Again I don't know if this is even relevant, but I saw the crash much more often with the first code sample.

**Comment by johnniwinther** [comment]
It looks like the problem fixed in https://dart-review.googlesource.com/c/sdk/+/314060
