### ISSUE TITLE
pkg/dartdev/test/native_assets/build_test flaky -> RuntimeError

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#53060]
There are new test failures on [[vm/ffi] Closure callbacks for async callbacks](https://github.com/dart-lang/sdk/commit/edeac698c242e06cc5e961001a4209cbc9ab050b).

The tests
```
pkg/dartdev/test/native_assets/build_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-linux
unittest-asserts-release-mac
unittest-asserts-release-win
```

Log:
```
--- Command "vm" (took 28.000269s):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome out/ReleaseX64/dart-sdk/bin/dart --enable_asserts --sound-null-safety -Dtest_runner.configuration=unittest-asserts-release-linux --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/pkg/dartdev/test/native_assets/build_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: dart build verbose[0m

00:12 [32m+0[0m[31m -1[0m: dart build verbose [1m[31m[E][0m[0m

  Expected: <0>
    Actual: <1>
  

  package:matcher/src/expect/expect.dart 149:31         fail
  package:matcher/src/expect/expect.dart 144:3          _expect
  package:matcher/src/expect/expect.dart 56:3           expect
  pkg/dartdev/test/native_assets/helpers.dart 181:5     runDart
  ===== asynchronous gap ===========================
  pkg/dartdev/test/native_assets/build_test.dart 20:24  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  pkg/dartdev/test/native_assets/helpers.dart 164:12    nativeAssetsTest.<fn>
  ===== asynchronous gap ===========================
  pkg/dartdev/test/native_assets/helpers.dart 28:5      inTempDir
  ===== asynchronous gap ===========================
  pkg/dartdev/test/native_assets/helpers.dart 160:10    nativeAssetsTest
  ===== asynchronous gap ===========================
  pkg/dartdev/test/native_assets/build_test.dart 19:7   main.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9      Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7      Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9       Invoker._waitForOutstandingCallbacks.<fn>
  

INFO: 2023-07-26 17:36:02.323036: Running `(cd /b/s/w/itma7gy3c3/SRVNAQ/dart_app/; /b/s/w/ir/out/ReleaseX64/dart-sdk/bin/dart pub get )`.

FINE: 2023-07-26 17:36:02.918994: Resolving dependencies...

FINE: 2023-07-26 17:36:05.615581: + args 2.4.2

FINE: 2023-07-26 17:36:05.615886: + async 2.11.0

FINE: 2023-07-26 17:36:05.616012: + cli_config 0.1.1

FINE: 2023-07-26 17:36:05.616052: + collection 1.18.0

FINE: 2023-07-26 17:36:05.616089: + crypto 3.0.3

FINE: 2023-07-26 17:36:05.616124: + file 7.0.0

FINE: 2023-07-26 17:36:05.616157: + glob 2.1.2

FINE: 2023-07-26 17:36:05.616189: + logging 1.2.0

FINE: 2023-07-26 17:36:05.616225: + meta 1.9.1

FINE: 2023-07-26 17:36:05.616259: + native_add 0.1.0 from path ../native_add

FINE: 2023-07-26 17:36:05.616293: + native_assets_cli 0.1.0

FINE: 2023-07-26 17:36:05.616332: + native_subtract 0.1.0 from path ../native_subtract

FINE: 2023-07-26 17:36:05.616383: + native_toolchain_c 0.1.0

FINE: 2023-07-26 17:36:05.616419: + path 1.8.3

FINE: 2023-07-26 17:36:05.616452: + pub_semver 2.1.4

FINE: 2023-07-26 17:36:05.616502: + source_span 1.10.0

FINE: 2023-07-26 17:36:05.616536: + string_scanner 1.2.0

FINE: 2023-07-26 17:36:05.616569: + term_glyph 1.2.1

FINE: 2023-07-26 17:36:05.616599: + typed_data 1.3.2

FINE: 2023-07-26 17:36:05.616630: + yaml 3.1.2

FINE: 2023-07-26 17:36:05.616662: + yaml_edit 2.1.1

FINE: 2023-07-26 17:36:05.628319: Changed 21 dependencies!

INFO: 2023-07-26 17:36:05.758196: Running `(cd /b/s/w/itma7gy3c3/SRVNAQ/dart_app/; /b/s/w/ir/out/ReleaseX64/dart-sdk/bin/dart --enable-experiment=native-assets build -v bin/dart_app.dart )`.

FINE: 2023-07-26 17:36:06.061341: Building native assets.

FINE: 2023-07-26 17:36:07.683759: config.yaml contents: build_mode: release

FINE: 2023-07-26 17:36:07.683920: link_mode_preference: dynamic

FINE: 2023-07-26 17:36:07.684006: out_dir: /b/s/w/itma7gy3c3/SRVNAQ/dart_app/.dart_tool/native_assets_builder/1397e1b887565784da364fddc021491a/out/

FINE: 2023-07-26 17:36:07.684042: package_root: /b/s/w/itma7gy3c3/SRVNAQ/native_add/

FINE: 2023-07-26 17:36:07.684068: target_architecture: x64

FINE: 2023-07-26 17:36:07.684108: target_os: linux

FINE: 2023-07-26 17:36:07.684146: version: 1.0.0

FINE: 2023-07-26 17:36:07.698611: Running `/b/s/w/ir/out/ReleaseX64/dart-sdk/bin/dart --packages=/b/s/w/itma7gy3c3/SRVNAQ/dart_app/.dart_tool/package_config.json /b/s/w/itma7gy3c3/SRVNAQ/native_add/build.dart --config=/b/s/w/itma7gy3c3/SRVNAQ/dart_app/.dart_tool/native_assets_builder/1397e1b887565784da364fddc021491a/config.yaml`.

SEVERE: 2023-07-26 17:36:14.142334: Unhandled exception:

SEVERE: 2023-07-26 17:36:14.142528: FormatException: Configuration is not in the right format. FormatExceptions: [FormatException: Path 'file:///b/s/w/ir/buildtools/linux-x64/clang/bin/llvm-ar' for key 'c_compiler.ar' doesn't exist., #0      Config._throwIfNotExists (package:cli_config/src/config.dart:598:7)

SEVERE: 2023-07-26 17:36:14.143042: #1      Config.optionalPath (package:cli_config/src/config.dart:467:11)

SEVERE: 2023-07-26 17:36:14.143115: #2      BuildConfig._readFieldsFromConfig.<anonymous closure> (package:native_assets_cli/src/model/build_config.dart:375:34)

SEVERE: 2023-07-26 17:36:14.143154: #3      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:235:10)

SEVERE: 2023-07-26 17:36:14.143191: #4      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:272:24)

SEVERE: 2023-07-26 17:36:14.143227: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.143263: #5      main (file:///b/s/w/itma7gy3c3/SRVNAQ/native_add/build.dart:12:23)

SEVERE: 2023-07-26 17:36:14.143293: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.143330: , FormatException: Path 'file:///b/s/w/ir/buildtools/linux-x64/clang/bin/clang' for key 'c_compiler.cc' doesn't exist., #0      Config._throwIfNotExists (package:cli_config/src/config.dart:598:7)

SEVERE: 2023-07-26 17:36:14.143365: #1      Config.optionalPath (package:cli_config/src/config.dart:467:11)

SEVERE: 2023-07-26 17:36:14.143399: #2      BuildConfig._readFieldsFromConfig.<anonymous closure> (package:native_assets_cli/src/model/build_config.dart:385:34)

SEVERE: 2023-07-26 17:36:14.143456: #3      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:235:10)

SEVERE: 2023-07-26 17:36:14.143494: #4      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:272:24)

SEVERE: 2023-07-26 17:36:14.143524: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.143555: #5      main (file:///b/s/w/itma7gy3c3/SRVNAQ/native_add/build.dart:12:23)

SEVERE: 2023-07-26 17:36:14.143587: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.143622: , FormatException: Path 'file:///b/s/w/ir/buildtools/linux-x64/clang/bin/ld.lld' for key 'c_compiler.ld' doesn't exist., #0      Config._throwIfNotExists (package:cli_config/src/config.dart:598:7)

SEVERE: 2023-07-26 17:36:14.143652: #1      Config.optionalPath (package:cli_config/src/config.dart:467:11)

SEVERE: 2023-07-26 17:36:14.143687: #2      BuildConfig._readFieldsFromConfig.<anonymous closure> (package:native_assets_cli/src/model/build_config.dart:396:34)

SEVERE: 2023-07-26 17:36:14.143723: #3      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:235:10)

SEVERE: 2023-07-26 17:36:14.144130: #4      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:272:24)

SEVERE: 2023-07-26 17:36:14.144185: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.144216: #5      main (file:///b/s/w/itma7gy3c3/SRVNAQ/native_add/build.dart:12:23)

SEVERE: 2023-07-26 17:36:14.144249: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.144277: ]

SEVERE: 2023-07-26 17:36:14.144307: #0      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:243:7)

SEVERE: 2023-07-26 17:36:14.144338: #1      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:272:24)

SEVERE: 2023-07-26 17:36:14.144364: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.144394: #2      main (file:///b/s/w/itma7gy3c3/SRVNAQ/native_add/build.dart:12:23)

SEVERE: 2023-07-26 17:36:14.144435: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.218955: ProcessException: Full command string: '/b/s/w/ir/out/ReleaseX64/dart-sdk/bin/dart --packages=/b/s/w/itma7gy3c3/SRVNAQ/dart_app/.dart_tool/package_config.json /b/s/w/itma7gy3c3/SRVNAQ/native_add/build.dart --config=/b/s/w/itma7gy3c3/SRVNAQ/dart_app/.dart_tool/native_assets_builder/1397e1b887565784da364fddc021491a/config.yaml'.

SEVERE: 2023-07-26 17:36:14.219075: Exit code: '255'.

SEVERE: 2023-07-26 17:36:14.219118: For the output of the process check the logger output.

SEVERE: 2023-07-26 17:36:14.219162:   Command: /b/s/w/ir/out/ReleaseX64/dart-sdk/bin/dart --packages=/b/s/w/itma7gy3c3/SRVNAQ/dart_app/.dart_tool/package_config.json /b/s/w/itma7gy3c3/SRVNAQ/native_add/build.dart --config=/b/s/w/itma7gy3c3/SRVNAQ/dart_app/.dart_tool/native_assets_builder/1397e1b887565784da364fddc021491a/config.yaml

SEVERE: 2023-07-26 17:36:14.219198: #0      runProcess (package:native_assets_builder/src/utils/run_process.dart:94:5)

SEVERE: 2023-07-26 17:36:14.219228: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.219266: #1      NativeAssetsBuildRunner._buildPackage (package:native_assets_builder/src/build_runner/build_runner.dart:188:5)

SEVERE: 2023-07-26 17:36:14.219296: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.219328: #2      NativeAssetsBuildRunner.build (package:native_assets_builder/src/build_runner/build_runner.dart:77:22)

SEVERE: 2023-07-26 17:36:14.219356: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.219390: #3      BuildCommand.run (package:dartdev/src/commands/build.dart:106:26)

SEVERE: 2023-07-26 17:36:14.219433: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.219465: #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)

SEVERE: 2023-07-26 17:36:14.219492: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.219520: #5      DartdevRunner.runCommand (package:dartdev/dartdev.dart:240:18)

SEVERE: 2023-07-26 17:36:14.219545: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.219567: #6      runDartdev (package:dartdev/dartdev.dart:59:16)

SEVERE: 2023-07-26 17:36:14.219599: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.219624: #7      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)

SEVERE: 2023-07-26 17:36:14.219645: <asynchronous suspension>

SEVERE: 2023-07-26 17:36:14.219669:

00:12 [32m+0[0m[31m -1[0m: dart build[0m

00:12 [32m+0[0m[31m -1[0m: dart build verbose[0m


INFO: 2023-07-26 17:36:14.481847: Running `(cd /b/s/w/itma7gy3c3/EPKWVC/dart_app/; /b/s/w/ir/out/ReleaseX64/dart-sdk/bin/dart pub get )`.


FINE: 2023-07-26 17:36:14.883415: Resolving dependencies...


FINE: 2023-07-26 17:36:16.707437: + args 2.4.2


FINE: 2023-07-26 17:36:16.707662: + async 2.11.0


FINE: 2023-07-26 17:36:16.707746: + cli_config 0.1.1


FINE: 2023-07-26 17:36:16.707794: + collection 1.18.0


FINE: 2023-07-26 17:36:16.707841: + crypto 3.0.3


FINE: 2023-07-26 17:36:16.707895: + file 7.0.0


FINE: 2023-07-26 17:36:16.708124: + glob 2.1.2


FINE: 2023-07-26 17:36:16.708218: + logging 1.2.0


FINE: 2023-07-26 17:36:16.708268: + meta 1.9.1


FINE: 2023-07-26 17:36:16.708313: + native_add 0.1.0 from path ../native_add


FINE: 2023-07-26 17:36:16.708360: + native_assets_cli 0.1.0


FINE: 2023-07-26 17:36:16.708407: + native_subtract 0.1.0 from path ../native_subtract


FINE: 2023-07-26 17:36:16.708457: + native_toolchain_c 0.1.0


FINE: 2023-07-26 17:36:16.708499: + path 1.8.3


FINE: 2023-07-26 17:36:16.708555: + pub_semver 2.1.4


FINE: 2023-07-26 17:36:16.708601: + source_span 1.10.0


FINE: 2023-07-26 17:36:16.708645: + string_scanner 1.2.0


FINE: 2023-07-26 17:36:16.708685: + term_glyph 1.2.1


FINE: 2023-07-26 17:36:16.708728: + typed_data 1.3.2


FINE: 2023-07-26 17:36:16.708766: + yaml 3.1.2


FINE: 2023-07-26 17:36:16.708809: + yaml_edit 2.1.1


FINE: 2023-07-26 17:36:16.711399: Changed 21 dependencies!


INFO: 2023-07-26 17:36:16.848090: Running `(cd /b/s/w/itma7gy3c3/EPKWVC/dart_app/; /b/s/w/ir/out/ReleaseX64/dart-sdk/bin/dart --enable-experiment=native-assets build bin/dart_app.dart )`.


FINE: 2023-07-26 17:36:17.157406: Building native assets.


SEVERE: 2023-07-26 17:36:23.797221: Unhandled exception:


SEVERE: 2023-07-26 17:36:23.797445: FormatException: Configuration is not in the right format. FormatExceptions: [FormatException: Path 'file:///b/s/w/ir/buildtools/linux-x64/clang/bin/llvm-ar' for key 'c_compiler.ar' doesn't exist., #0      Config._throwIfNotExists (package:cli_config/src/config.dart:598:7)


SEVERE: 2023-07-26 17:36:23.797517: #1      Config.optionalPath (package:cli_config/src/config.dart:467:11)


SEVERE: 2023-07-26 17:36:23.797570: #2      BuildConfig._readFieldsFromConfig.<anonymous closure> (package:native_assets_cli/src/model/build_config.dart:375:34)


SEVERE: 2023-07-26 17:36:23.797617: #3      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:235:10)


SEVERE: 2023-07-26 17:36:23.797673: #4      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:272:24)


SEVERE: 2023-07-26 17:36:23.797724: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.797775: #5      main (file:///b/s/w/itma7gy3c3/EPKWVC/native_add/build.dart:12:23)


SEVERE: 2023-07-26 17:36:23.797815: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.797868: , FormatException: Path 'file:///b/s/w/ir/buildtools/linux-x64/clang/bin/clang' for key 'c_compiler.cc' doesn't exist., #0      Config._throwIfNotExists (package:cli_config/src/config.dart:598:7)


SEVERE: 2023-07-26 17:36:23.798171: #1      Config.optionalPath (package:cli_config/src/config.dart:467:11)


SEVERE: 2023-07-26 17:36:23.798286: #2      BuildConfig._readFieldsFromConfig.<anonymous closure> (package:native_assets_cli/src/model/build_config.dart:385:34)


SEVERE: 2023-07-26 17:36:23.798352: #3      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:235:10)


SEVERE: 2023-07-26 17:36:23.798404: #4      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:272:24)


SEVERE: 2023-07-26 17:36:23.798452: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.798502: #5      main (file:///b/s/w/itma7gy3c3/EPKWVC/native_add/build.dart:12:23)


SEVERE: 2023-07-26 17:36:23.798558: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.798614: , FormatException: Path 'file:///b/s/w/ir/buildtools/linux-x64/clang/bin/ld.lld' for key 'c_compiler.ld' doesn't exist., #0      Config._throwIfNotExists (package:cli_config/src/config.dart:598:7)


SEVERE: 2023-07-26 17:36:23.798670: #1      Config.optionalPath (package:cli_config/src/config.dart:467:11)


SEVERE: 2023-07-26 17:36:23.798723: #2      BuildConfig._readFieldsFromConfig.<anonymous closure> (package:native_assets_cli/src/model/build_config.dart:396:34)


SEVERE: 2023-07-26 17:36:23.798777: #3      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:235:10)


SEVERE: 2023-07-26 17:36:23.798832: #4      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:272:24)


SEVERE: 2023-07-26 17:36:23.798888: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.798947: #5      main (file:///b/s/w/itma7gy3c3/EPKWVC/native_add/build.dart:12:23)


SEVERE: 2023-07-26 17:36:23.798998: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.799042: ]


SEVERE: 2023-07-26 17:36:23.799100: #0      new BuildConfig.fromConfig (package:native_assets_cli/src/model/build_config.dart:243:7)


SEVERE: 2023-07-26 17:36:23.799161: #1      BuildConfig.fromArgs (package:native_assets_cli/src/model/build_config.dart:272:24)


SEVERE: 2023-07-26 17:36:23.802631: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.802827: #2      main (file:///b/s/w/itma7gy3c3/EPKWVC/native_add/build.dart:12:23)


SEVERE: 2023-07-26 17:36:23.802900: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.873328: ProcessException: Full command string: '/b/s/w/ir/out/ReleaseX64/dart-sdk/bin/dart --packages=/b/s/w/itma7gy3c3/EPKWVC/dart_app/.dart_tool/package_config.json /b/s/w/itma7gy3c3/EPKWVC/native_add/build.dart --config=/b/s/w/itma7gy3c3/EPKWVC/dart_app/.dart_tool/native_assets_builder/1397e1b887565784da364fddc021491a/config.yaml'.


SEVERE: 2023-07-26 17:36:23.873528: Exit code: '255'.


SEVERE: 2023-07-26 17:36:23.873587: For the output of the process check the logger output.


SEVERE: 2023-07-26 17:36:23.874253:   Command: /b/s/w/ir/out/ReleaseX64/dart-sdk/bin/dart --packages=/b/s/w/itma7gy3c3/EPKWVC/dart_app/.dart_tool/package_config.json /b/s/w/itma7gy3c3/EPKWVC/native_add/build.dart --config=/b/s/w/itma7gy3c3/EPKWVC/dart_app/.dart_tool/native_assets_builder/1397e1b887565784da364fddc021491a/config.yaml


SEVERE: 2023-07-26 17:36:23.875675: #0      runProcess (package:native_assets_builder/src/utils/run_process.dart:94:5)


SEVERE: 2023-07-26 17:36:23.875814: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.875884: #1      NativeAssetsBuildRunner._buildPackage (package:native_assets_builder/src/build_runner/build_runner.dart:188:5)


SEVERE: 2023-07-26 17:36:23.875974: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.876023: #2      NativeAssetsBuildRunner.build (package:native_assets_builder/src/build_runner/build_runner.dart:77:22)


SEVERE: 2023-07-26 17:36:23.876067: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.876105: #3      BuildCommand.run (package:dartdev/src/commands/build.dart:106:26)


SEVERE: 2023-07-26 17:36:23.876145: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.876183: #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)


SEVERE: 2023-07-26 17:36:23.876223: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.876260: #5      DartdevRunner.runCommand (package:dartdev/dartdev.dart:240:18)


SEVERE: 2023-07-26 17:36:23.876302: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.876343: #6      runDartdev (package:dartdev/dartdev.dart:59:16)


SEVERE: 2023-07-26 17:36:23.876392: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.876436: #7      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)


SEVERE: 2023-07-26 17:36:23.876482: <asynchronous suspension>


SEVERE: 2023-07-26 17:36:23.877052:

00:21 [32m+0[0m[31m -2[0m: dart build [1m[31m[E][0m[0m

  Expected: <0>
    Actual: <1>
  

  package:matcher/src/expect/expect.dart 149:31         fail
  package:matcher/src/expect/expect.dart 144:3          _expect
  package:matcher/src/expect/expect.dart 56:3           expect
  pkg/dartdev/test/native_assets/helpers.dart 181:5     runDart
  ===== asynchronous gap ===========================
  pkg/dartdev/test/native_assets/build_test.dart 20:24  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  pkg/dartdev/test/native_assets/helpers.dart 164:12    nativeAssetsTest.<fn>
  ===== asynchronous gap ===========================
  pkg/dartdev/test/native_assets/helpers.dart 28:5      inTempDir
  ===== asynchronous gap ===========================
  pkg/dartdev/test/native_assets/helpers.dart 160:10    nativeAssetsTest
  ===== asynchronous gap ===========================
  pkg/dartdev/test/native_assets/build_test.dart 19:7   main.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9      Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7      Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9       Invoker._waitForOutstandingCallbacks.<fn>
  

00:21 [32m+0[0m[31m -2[0m: [31mSome tests failed.[0m



Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

stderr:
Unhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python3 tools/test.py -n unittest-asserts-release-linux pkg/dartdev/test/native_assets/build_test
```

/cc @bkonyi

**Comment by bkonyi** [comment]
FYI @dcharkes

**Comment by dcharkes** [comment]
@athomas @whesse

* Any idea why the environment vars could be different on those 3 bots for that single test?
* Also, how do I get the logs from a test that has already been approved failing? Now I can only see the env vars in the two bots that I made from green to red. (I guess add a new test and make it fail...)

**Comment by dcharkes** [comment]
From the chat, this is caused by https://dart-review.googlesource.com/c/sdk/+/312482, we started sharding the pkg bots.
