### ISSUE TITLE
Target dart2wasm failed: ProcessException: Process exited abnormally:

### ISSUE THREAD

**Issue by hpelitebook745G2** [dart-lang/sdk#53073]
I'm trying to integrate WebAssembly to the Flutter Web and I'm following this article: https://blog.logrocket.com/getting-started-webassembly-flutter-web/

I understand that as of this writing, WebAssembly is still experimental:

> Warning: Development of WebAssembly support for Dart and Flutter remains ongoing.
> 
> You can preview Wasm and WebAssembly garbage collection (WasmGC) in the [master channel](https://github.com/flutter/flutter/wiki/flutter-build-release-channels#master). As Flutter provides these features as previews, ongoing development might result in frequent changes. Revisit this page for the latest updates.
> 
> Last updated May 23, 2023

I only have 1 dependency: [wasm_interop](https://pub.dev/packages/wasm_interop) so I'd be able to interact with my methods from WebAssembly in Flutter or Dart.

Though, I am able to run it in debug mode but when I run `flutter build web --wasm` I got this error:
```console
┌─ Experimental feature ───────────────────────────────┐
│   WebAssembly compilation is experimental.           │
│   See https://flutter.dev/wasm for more information. │
└──────────────────────────────────────────────────────┘
Target dart2wasm failed: ProcessException: Process exited abnormally:
Unhandled exception:
type 'InterfaceType' is not a subtype of type 'FunctionType' in type cast
#0      CallbackSpecializer.allowInterop (package:dart2wasm/js/callback_specializer.dart:207)
#1      InteropTransformer.visitStaticInvocation (package:dart2wasm/js/interop_transformer.dart:75)
#2      StaticInvocation.accept (package:kernel/ast.dart:6388)
#3      Transformer.transform (package:kernel/visitor.dart:1768)
#4      Transformer.transformList (package:kernel/visitor.dart:1785)
#5      Arguments.transformChildren (package:kernel/ast.dart:5235)
#6      Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#7      TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#8      Arguments.accept (package:kernel/ast.dart:5220)
#9      Transformer.transform (package:kernel/visitor.dart:1768)
#10     ConstructorInvocation.transformChildren (package:kernel/ast.dart:6486)
#11     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#12     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#13     TreeVisitor.visitStaticInvocation (package:kernel/visitor.dart:283)
#14     InteropTransformer.visitStaticInvocation (package:dart2wasm/js/interop_transformer.dart:72)
#15     StaticInvocation.accept (package:kernel/ast.dart:6388)
#16     Transformer.transform (package:kernel/visitor.dart:1768)
#17     SpreadMapEntry.transformChildren (package:front_end/src/fasta/kernel/collections.dart:449)
#18     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#19     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#20     TreeVisitor.visitLabeledStatement (package:kernel/visitor.dart:428)
#21     ExpressionStatement.accept (package:kernel/ast.dart:8933)
#22     Transformer.transform (package:kernel/visitor.dart:1768)
#23     Transformer.transformList (package:kernel/visitor.dart:1785)
#24     AssertBlock.transformChildren (package:kernel/ast.dart:9042)
#25     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#26     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#27     TreeVisitor.visitLabeledStatement (package:kernel/visitor.dart:428)
#28     Block.accept (package:kernel/ast.dart:8983)
#29     Transformer.transform (package:kernel/visitor.dart:1768)
#30     IfStatement.transformChildren (package:kernel/ast.dart:9891)
#31     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#32     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#33     TreeVisitor.visitLabeledStatement (package:kernel/visitor.dart:428)
#34     IfStatement.accept (package:kernel/ast.dart:9874)
#35     Transformer.transform (package:kernel/visitor.dart:1768)
#36     Transformer.transformList (package:kernel/visitor.dart:1785)
#37     AssertBlock.transformChildren (package:kernel/ast.dart:9042)
#38     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#39     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#40     TreeVisitor.visitLabeledStatement (package:kernel/visitor.dart:428)
#41     Block.accept (package:kernel/ast.dart:8983)
#42     Transformer.transform (package:kernel/visitor.dart:1768)
#43     FunctionNode.transformChildren (package:kernel/ast.dart:3751)
#44     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#45     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#46     FunctionNode.accept (package:kernel/ast.dart:3718)
#47     Transformer.transform (package:kernel/visitor.dart:1768)
#48     FunctionExpression.transformChildren (package:kernel/ast.dart:8426)
#49     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#50     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#51     TreeVisitor.visitNullCheck (package:kernel/visitor.dart:290)
#52     FunctionExpression.accept (package:kernel/ast.dart:8413)
#53     Transformer.transform (package:kernel/visitor.dart:1768)
#54     Transformer.transformList (package:kernel/visitor.dart:1785)
#55     Arguments.transformChildren (package:kernel/ast.dart:5235)
#56     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#57     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#58     Arguments.accept (package:kernel/ast.dart:5220)
#59     Transformer.transform (package:kernel/visitor.dart:1768)
#60     InstanceInvocation.transformChildren (package:kernel/ast.dart:5599)
#61     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#62     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#63     TreeVisitor.visitNullCheck (package:kernel/visitor.dart:290)
#64     InstanceInvocation.accept (package:kernel/ast.dart:5580)
#65     Transformer.transform (package:kernel/visitor.dart:1768)
#66     SpreadMapEntry.transformChildren (package:front_end/src/fasta/kernel/collections.dart:449)
#67     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#68     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#69     TreeVisitor.visitLabeledStatement (package:kernel/visitor.dart:428)
#70     ExpressionStatement.accept (package:kernel/ast.dart:8933)
#71     Transformer.transform (package:kernel/visitor.dart:1768)
#72     Transformer.transformList (package:kernel/visitor.dart:1785)
#73     AssertBlock.transformChildren (package:kernel/ast.dart:9042)
#74     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#75     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#76     TreeVisitor.visitLabeledStatement (package:kernel/visitor.dart:428)
#77     Block.accept (package:kernel/ast.dart:8983)
#78     Transformer.transform (package:kernel/visitor.dart:1768)
#79     FunctionNode.transformChildren (package:kernel/ast.dart:3751)
#80     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#81     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#82     FunctionNode.accept (package:kernel/ast.dart:3718)
#83     Transformer.transform (package:kernel/visitor.dart:1768)
#84     FunctionExpression.transformChildren (package:kernel/ast.dart:8426)
#85     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#86     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#87     TreeVisitor.visitNullCheck (package:kernel/visitor.dart:290)
#88     FunctionExpression.accept (package:kernel/ast.dart:8413)
#89     Transformer.transform (package:kernel/visitor.dart:1768)
#90     Transformer.transformList (package:kernel/visitor.dart:1785)
#91     Arguments.transformChildren (package:kernel/ast.dart:5235)
#92     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#93     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#94     Arguments.accept (package:kernel/ast.dart:5220)
#95     Transformer.transform (package:kernel/visitor.dart:1768)
#96     InstanceInvocation.transformChildren (package:kernel/ast.dart:5599)
#97     Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#98     TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#99     TreeVisitor.visitNullCheck (package:kernel/visitor.dart:290)
#100    InstanceInvocation.accept (package:kernel/ast.dart:5580)
#101    Transformer.transform (package:kernel/visitor.dart:1768)
#102    SpreadMapEntry.transformChildren (package:front_end/src/fasta/kernel/collections.dart:449)
#103    Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#104    TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#105    TreeVisitor.visitLabeledStatement (package:kernel/visitor.dart:428)
#106    ExpressionStatement.accept (package:kernel/ast.dart:8933)
#107    Transformer.transform (package:kernel/visitor.dart:1768)
#108    Transformer.transformList (package:kernel/visitor.dart:1785)
#109    AssertBlock.transformChildren (package:kernel/ast.dart:9042)
#110    Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#111    TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#112    TreeVisitor.visitLabeledStatement (package:kernel/visitor.dart:428)
#113    Block.accept (package:kernel/ast.dart:8983)
#114    Transformer.transform (package:kernel/visitor.dart:1768)
#115    IfStatement.transformChildren (package:kernel/ast.dart:9891)
#116    Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#117    TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#118    TreeVisitor.visitLabeledStatement (package:kernel/visitor.dart:428)
#119    IfStatement.accept (package:kernel/ast.dart:9874)
#120    Transformer.transform (package:kernel/visitor.dart:1768)
#121    Transformer.transformList (package:kernel/visitor.dart:1785)
#122    AssertBlock.transformChildren (package:kernel/ast.dart:9042)
#123    Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#124    TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#125    TreeVisitor.visitLabeledStatement (package:kernel/visitor.dart:428)
#126    Block.accept (package:kernel/ast.dart:8983)
#127    Transformer.transform (package:kernel/visitor.dart:1768)
#128    FunctionNode.transformChildren (package:kernel/ast.dart:3751)
#129    Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#130    TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#131    FunctionNode.accept (package:kernel/ast.dart:3718)
#132    Transformer.transform (package:kernel/visitor.dart:1768)
#133    Procedure.transformChildren (package:kernel/ast.dart:3140)
#134    InteropTransformer.visitProcedure (package:dart2wasm/js/interop_transformer.dart:92)
#135    Procedure.accept (package:kernel/ast.dart:3121)
#136    Transformer.transform (package:kernel/visitor.dart:1768)
#137    Transformer.transformList (package:kernel/visitor.dart:1785)
#138    Class.transformChildren (package:kernel/ast.dart:1475)
#139    Transformer.defaultTreeNode (package:kernel/visitor.dart:1802)
#140    TreeVisitor.defaultExpression (package:kernel/visitor.dart:223)
#141    Class.accept (package:kernel/ast.dart:1421)
#142    Transformer.transform (package:kernel/visitor.dart:1768)
#143    Transformer.transformList (package:kernel/visitor.dart:1785)
#144    Library.transformChildren (package:kernel/ast.dart:600)
#145    InteropTransformer.visitLibrary (package:dart2wasm/js/interop_transformer.dart:57)
#146    _performJSInteropTransformations (package:dart2wasm/js/runtime_generator.dart:23)
#147    createRuntimeFinalizer (package:dart2wasm/js/runtime_generator.dart:78)
#148    compileToModule (package:dart2wasm/compile.dart:103)
<asynchronous suspension>
#149    main (package:dart2wasm/dart2wasm.dart:134)
<asynchronous suspension>
#150    main (file:///opt/s/w/ir/x/w/sdk/pkg/dart2wasm/bin/dart2wasm.dart:7)
<asynchronous suspension>
  Command: /Users/<user>/tools/flutter/bin/cache/dart-sdk/bin/dartaotruntime --disable-dart-dev /Users/<user>/tools/flutter/bin/cache/dart-sdk/bin/snapshots/dart2wasm_product.snapshot --packages=.dart_tool/package_config.json
  --dart-sdk=/Users/<user>/tools/flutter/bin/cache/dart-sdk --multi-root-scheme org-dartlang-sdk --multi-root /Users/<user>/tools/flutter/bin/cache/flutter_web_sdk --multi-root /Users/<user>/tools/flutter/bin/cache
  --libraries-spec /Users/<user>/tools/flutter/bin/cache/flutter_web_sdk/libraries.json -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/b84c936016846c25475dab2befa10b47798d80d6/
  --depfile=/Users/<user>/Desktop/test_projects/flutter_web_wasm/.dart_tool/flutter_build/a91fbb749dae1d55d6e3b057c4602e25/dart2wasm.d
  /Users/<user>/Desktop/test_projects/flutter_web_wasm/.dart_tool/flutter_build/a91fbb749dae1d55d6e3b057c4602e25/main.dart
  /Users/<user>/Desktop/test_projects/flutter_web_wasm/.dart_tool/flutter_build/a91fbb749dae1d55d6e3b057c4602e25/main.dart.unopt.wasm
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:278:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:281:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:89:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:198:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1322:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                              4.7s
Exception: Failed to compile application for the Web.
```

Flutter doctor result:
```
[✓] Flutter (Channel master, 3.13.0-12.0.pre.40, on macOS 13.5 22G74 darwin-arm64, locale en-SG)
    • Flutter version 3.13.0-12.0.pre.40 on channel master at /Users/<user>/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46f83ce636 (3 hours ago), 2023-07-30 22:31:35 -0400
    • Engine revision b84c936016
    • Dart version 3.2.0 (build 3.2.0-15.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/<user>/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/<user>/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by askeksa-google** [comment]
@joshualitt

**Comment by joshualitt** [comment]
I'm not too familiar with `package:wasm_interop` so I'm not sure if it should work on Dart2Wasm or not.

However, you can try `package:web` which I think has some WebAssembly JS APIs, but `package:web` is very much still under development. We're hoping `package:web` will start stabilizing very soon though, and assuming it meets your needs then it might be the best path forward in the future.

That said, you're best bet for now is to build your own DOM shims like what we did in the Flutter web engine: https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/dom.dart

**Comment by AndromedaX7** [comment]
<details open><summary>flutter build web --release --wasm</summary>

```console
console
┌─ New feature ────────────────────────────────────────────────────────────────────────────┐
│   WebAssembly compilation is new. Understand the details before deploying to production. │
│   See https://flutter.dev/wasm for more information.                                     │
└──────────────────────────────────────────────────────────────────────────────────────────┘

Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
Error: Wasm compilation failed while optimizing output
[wasm-validator error in function NumberFormat._round] break type must be a subtype of the target block type, on 
(block $label$2 (result i64)
 (br_on_non_null $label$2
  (global.get $global$22226)
 )
 (call $NumberFormat._maxInt)
)
[wasm-validator error in function NumberFormat._integerDigits] break type must be a subtype of the target block type, on 
(block $label$4 (result i64)
 (br_on_non_null $label$4
  (global.get $global$22226)
 )
 (call $NumberFormat._maxInt)
)
[wasm-validator error in function NumberFormat._maxDigits] break type must be a subtype of the target block type, on 
(block $label$1 (result i64)
 (br_on_non_null $label$1
  (global.get $global$22226)
 )
 (call $NumberFormat._maxInt)
)
Fatal: error validating input
  Command: /home/miliy/flutter/bin/cache/dart-sdk/bin/dart compile wasm --packages=.dart_tool/package_config.json --extra-compiler-option=--dart-sdk=/home/miliy/flutter/bin/cache/dart-sdk
  --extra-compiler-option=--platform=/home/miliy/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill --extra-compiler-option=--delete-tostring-package-uri=dart:ui
  --extra-compiler-option=--delete-tostring-package-uri=package:flutter --extra-compiler-option=--import-shared-memory --extra-compiler-option=--shared-memory-max-pages=32768 -Ddart.vm.product=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/fad88cb16d038d7819aa567d1bd3a0455fcb3f82/ -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_USE_SKWASM=true
  --extra-compiler-option=--depfile=/home/miliy/workspaces/backend_manager_webpage/.dart_tool/flutter_build/a90e37fd1e2d4be642b7f49877bf9c6b/dart2wasm.d -O4 --no-name-section -o
  /home/miliy/workspaces/backend_manager_webpage/.dart_tool/flutter_build/a90e37fd1e2d4be642b7f49877bf9c6b/main.dart.wasm
  /home/miliy/workspaces/backend_manager_webpage/.dart_tool/flutter_build/a90e37fd1e2d4be642b7f49877bf9c6b/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:318:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:329:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:867:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:805:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:805:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:634:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1393:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             33.1s
Error: Failed to compile application for the Web.
```

</details>


<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.22.0-31.0.pre.16, on Fedora Linux 40 (Workstation Edition) 6.8.9-300.fc40.x86_64, locale zh_CN.UTF-8)
    • Flutter version 3.22.0-31.0.pre.16 on channel master at /home/miliy/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 839ba6b3e3 (4 小时前), 2024-05-10 23:01:23 -0400
    • Engine revision fad88cb16d
    • Dart version 3.5.0 (build 3.5.0-143.0.dev)
    • DevTools version 2.36.0-dev.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/miliy/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/miliy/Android/Sdk
    • Java binary at: /home/miliy/jetbrains/android-studio-5/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.1 (Fedora 18.1.1-1.fc40)
    • cmake version 3.28.2
    • ninja version 1.11.1
    • pkg-config version 2.1.0

[✓] Android Studio (version 2023.3)
    • Android Studio at /home/miliy/jetbrains/android-studio-4
    • Flutter plugin version 79.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Android Studio (version 2024.1)
    • Android Studio at /home/miliy/jetbrains/android-studio-5
    • Flutter plugin version 79.0.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at /home/miliy/jetbrains/intellij-idea-ultimate
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 40 (Workstation Edition) 6.8.9-300.fc40.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.201

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by AndromedaX7** [comment]
> ```
> https://flutter.dev/wasm
> ```

I've consulted the documentation and solved the problem.

**Comment by mkustermann** [comment]
> I only have 1 dependency: [wasm_interop](https://pub.dev/packages/wasm_interop) so I'd be able to interact with my methods from WebAssembly in Flutter or Dart.

The `package:wasm_interop` package depends on `package:js` which depends on `dart:js`, which isn't supported in the new JS interop mechanism - see [dart.dev/interop/js-interop](https://dart.dev/interop/js-interop) for more information.

That being said the compiler shouldn't crash but instead produce a nice error. With today's flutter it says:
```
% flutter build web --wasm
Downloading Web SDK...                                           2,435ms

┌─ New feature ────────────────────────────────────────────────────────────────────────────┐
│   WebAssembly compilation is new. Understand the details before deploying to production. │
│   See https://flutter.dev/to/wasm for more information.                                  │
└──────────────────────────────────────────────────────────────────────────────────────────┘
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 254:
../../.pub-cache/hosted/pub.dev/js-0.6.7/lib/js.dart:10:1: Error: Dart library 'dart:js' is not available on this platform.
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
Context: The unavailable library 'dart:js' is imported through these packages:

    main.dart => package:rep => package:wasm_interop => package:js => dart:js

Detailed import paths for (some of) the these imports:

    main.dart => package:rep/main.dart => package:wasm_interop/wasm_interop.dart => package:js/js.dart => dart:js

../../.pub-cache/hosted/pub.dev/wasm_interop-2.0.1/lib/wasm_interop.dart:8:1: Error: JS interop library 'package:js/js.dart' can't be imported when compiling to Wasm.
Try using 'dart:js_interop' or 'dart:js_interop_unsafe' instead.
import 'package:js/js.dart';
^
../../.pub-cache/hosted/pub.dev/wasm_interop-2.0.1/lib/wasm_interop.dart:9:1: Error: JS interop library 'package:js/js_util.dart' can't be imported when compiling to Wasm.
Try using 'dart:js_interop' or 'dart:js_interop_unsafe' instead.
import 'package:js/js_util.dart';
^
```

So the compiler crash seems to be fixed and it now shows a nice error explaining the problem. Marking this as closed.
