### ISSUE TITLE
Error "Unhandled Exception: ProcessException: No such file or directory"

### ISSUE THREAD

**Issue by joec05** [dart-lang/sdk#53127]
So I'm trying to integrate an external files  (an exe one) with Flutter. I've added all those in a custom folder in the root of my project, and even declared it in assets.  And I'm currently using Process.run() for that external command. However, it kept returning this error, 

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ProcessException: No such file or directory
E/flutter ( 8249):   Command: ffmpeg.exe
E/flutter ( 8249): #0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
E/flutter ( 8249): #1      Process.start (dart:io-patch/process_patch.dart:38:20)
E/flutter ( 8249): #2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578:18)
E/flutter ( 8249): #3      Process.run (dart:io-patch/process_patch.dart:49:12)
E/flutter ( 8249): <asynchronous suspension>
```

I tried playing a bit with the executioner string, and I found out that the error disappeared (either they changed to another error or they succeeded) if I used internal commands like 'sort' or 'find', but when i used exe files from the system32 folder (which didn't return an error in the command prompt either), it repeated this error. 

Maybe my deduction can be wrong, but I'm a bit clueless as of now because the discussion surrounding this Process.run has been extremely minimal which is why my last resort is to ask in a public forum.

**Comment by mkustermann** [comment]
If you're on linux you can `strace -f <normal command to launch app>` the app and it will show you all system calls the app performs. If you filter by `ffmpeg` you'll find all the places where the binary is searched for in the file system. You can then compare where the `ffmpeg` file is actually on your file system.

Could it be as simple as your `PATH` variable not containing the folder where the `ffmpeg` is in?
