### ISSUE TITLE
Extension type without body causes parser crash

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#53194]
```dart
extension type ET(int id);
```

from `co19/LanguageFeatures/Extension-types/syntax_A07_t01` results in
```
  'package:_fe_analyzer_shared/src/parser/parser_impl.dart': Failed assertion: line 4243 pos 12: 'optional('{', token)': is not true.
  #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
  #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
  #2      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4243:12)
  #3      Parser.parseExtensionTypeDeclarationRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3120:13)
  #4      Parser.parseExtension (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3036:16)
  #5      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:769:18)
  #6      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:531:14)
  #7      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:411:15)
  #8      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:106:32)
  #9      Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:102:12)
  #10     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:726:23)
```
when run with asserts enabled.

**Comment by johnniwinther** [comment]
Fixed
