### ISSUE TITLE
[dart2wasm] co19/LanguageFeatures/Extension-types/static_analysis_member_invocation_A05_t03 crashes compiler

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53239]
Test https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-types/dynamic_semantics_extension_type_A05_t03.dart crashes the compiler

Failure [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8772601863604507393/+/u/test_results/new_test_failures__logs_):
```

/==========================================================================================================================\
| co19/LanguageFeatures/Extension-types/static_analysis_member_invocation_A05_t03 is new and failed (Crash, expected Pass) |
\==========================================================================================================================/

--- Command "dart2wasm" (took 01.000383s):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome sdk/bin/dart2wasm_developer -Dtest_runner.configuration=dart2wasm-linux-chrome --enable-experiment=inline-class /b/s/w/ir/tests/co19/src/LanguageFeatures/Extension-types/static_analysis_member_invocation_A05_t03.dart /b/s/w/ir/out/ReleaseX64/generated_tests/dart2wasm-linux-chrome/tests_co19_src_LanguageFeatures_Extension-types_static_analysis_member_invocation_A05_t03/static_analysis_member_invocation_A05_t03.wasm

exit code:
255

stderr:
Unhandled exception:
Null check operator used on a null value
#0      _ClosureTrampolineGenerator.generate (package:dart2wasm/translator.dart:1052)
#1      Translator.translate (package:dart2wasm/translator.dart:360)
#2      compileToModule (package:dart2wasm/compile.dart:138)
<asynchronous suspension>
#3      main (package:dart2wasm/dart2wasm.dart:134)
<asynchronous suspension>
#4      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dart2wasm/bin/dart2wasm.dart:7)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dart2wasm-linux-chrome co19/LanguageFeatures/Extension-types/static_analysis_member_invocation_A05_t03

```

**Comment by osa1** [comment]
I think this is a CFE bug, the tear-off member generated by CFE is missing the optional parameter's default value. Smaller repro:

```dart
extension type ET1(int id) {
  ET1.n1(this.id, [String s = ""]);
}

main() {
  var x = ET1.n1;
}
```

Kernel before TFA for `ET1.n1` tear-off member is missing the default value:

```
  static extension-type-member method ET1|constructor#_#n1#tearOff(core::int id, [has-declared-initializer core::String s]) → test::ET1 /* = core::int */
    return test::ET1|constructor#n1(id, s);

```

`s` is missing the default value, it should looks like `[core::String s = #C1]`.

@johnniwinther could you take a look?

**Comment by johnniwinther** [comment]
This looks like a CFE bug. I'll take a look.
