### ISSUE TITLE
PathNotFoundException when trying to open a block device on macOS or Linux

### ISSUE THREAD

**Issue by cbenhagen** [dart-lang/sdk#53251]
Dart throws a `PathNotFoundException` when trying to open a block device on macOS or Linux as normal user as well as root:

```dart
import 'dart:io';

void main() {
  var file = File('/dev/sda');
  if (file.existsSync()) {
    var raf = file.openSync(mode: FileMode.read);
  }
}
```

```bash
Unhandled exception:
PathNotFoundException: Cannot open file, path = '/dev/sda' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      main (file:///home/ben/block.dart:6:20)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

`Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "linux_x64"`

Trying to do the same in Python throws a `PermissionError` as normal user which is expected and works with sudo:
```python
f = open('/dev/sda', 'r')
```

Similar C code also just works as expected.

**Comment by mraleph** [comment]
I think this is due to this particular check https://github.com/dart-lang/sdk/blob/6dcbc9fc14a0347f91fe4cce3cc3549d38d3b919/runtime/bin/file_linux.cc#L221-L225

I honestly not sure why we would allow character devices but not block devices? 

This might be because `epoll` does not support block devices, but I am not sure and an error is utterly confusing. 

/cc @brianquinlan
