### ISSUE TITLE
allowInvalid on Latin1Codec not work

### ISSUE THREAD

**Issue by insinfo** [dart-lang/sdk#53299]
allowInvalid on Latin1Codec not work

```dart

void main(List<String> args) async {
 final string = '➢ Isaque';
  print('Before: $string');
  print('After: ${removeNonLatin1(string)}');
}
String removeNonLatin1(String input) {
  return Latin1Codec(allowInvalid: true).decode(Latin1Codec(allowInvalid: true).encode(input));
}
```
```console

PS C:\MyDartProjects\new_sali\backend> dart .\bin\teste_charset.dart
Before: ➢ Isaque
Unhandled exception:
Invalid argument (string): Contains invalid characters.: "➢ Isaque"
#0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:85:9)
#1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
#2      removeNonLatin1 (file:///C:/MyDartProjects/new_sali/backend/bin/teste_charset.dart:40:81)
#3      main (file:///C:/MyDartProjects/new_sali/backend/bin/teste_charset.dart:14:19)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
As documented on the [constructor](https://api.dart.dev/stable/3.1.0/dart-convert/Latin1Codec/Latin1Codec.html), the `allowInvalid` only applies to the decoder. The encoder never accepts invalid inputs, since it doesn't know what to do with them. The decoder can convert to the Unicode replacement character U+FFFD, but the encoder can only output bytes.

The invalid bytes for deciding are 0x80..0xA0, which are not defined for Latin-1.

So this is working as intended.
