### ISSUE TITLE
Failed to acquire `SafepointRwLock` when compiling code after setting a breakpoint

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#53342]
We're seeing the following assertion failure on `pkg-linux-debug` after porting `runtime/observatory/tests/service/break_on_function_child_isolate_test.dart` and `runtime/observatory/tests/service/break_on_function_many_child_isolates_test.dart`:

```
// truncated logs... 

break_on_function_child_isolate_test.dart [9/16]

break_on_function_child_isolate_test.dart [10/16]

>testee>err> Registering pending breakpoint for uncompiled function 'file:///b/s/w/ir/cache/builder/sdk/pkg/vm_service/test/break_on_function_many_child_isolates_test.dart_::_foo' at line 24 col 14
>testee>err> Resolved breakpoint 1 to pos 708, function 'file:///b/s/w/ir/cache/builder/sdk/pkg/vm_service/test/break_on_function_many_child_isolates_test.dart_::_foo' (requested range 699-699, requested col -1)
>testee>err> Setting breakpoint 1 for function 'file:///b/s/w/ir/cache/builder/sdk/pkg/vm_service/test/break_on_function_many_child_isolates_test.dart_::_foo'
>testee>err> ../../runtime/vm/lockers.cc: 182: error: expected: thread == nullptr || thread->CanAcquireSafepointLocks() || IsCurrentThreadWriter()
>testee>err> version=3.2.0-edge.772dbf7fb5e6787195b029e053a2217dabc59e43 (be) (Thu Aug 24 16:03:30 2023 +0000) on "linux_x64"
>testee>err> pid=404523, thread=404610, isolate_group=main(0x559c4cbb1130), isolate=foo0(0x7fc1b4000cd0)
>testee>err> os=linux, arch=x64, comp=no, sim=no
>testee>err> isolate_instructions=559c4a5e97c0, vm_instructions=559c4a5e97c0
>testee>err> fp=7fc1c20fb510, sp=7fc1c20fb3d8, pc=559c4a9d88cc
>testee>err>   pc 0x0000559c4a9d88cc fp 0x00007fc1c20fb510 dart::Profiler::DumpStackTrace(void*)+0x7c
>testee>err>   pc 0x0000559c4a5e99b4 fp 0x00007fc1c20fb5f0 dart::Assert::Fail(char const*, ...) const+0x84
>testee>err>   pc 0x0000559c4a8a18d3 fp 0x00007fc1c20fb640 out/DebugX64/dart-sdk/bin/dart+0x25d98d3
>testee>err>   pc 0x0000559c4a83d262 fp 0x00007fc1c20fb700 dart::GroupDebugger::MakeCodeBreakpointAt(dart::Function const&, dart::BreakpointLocation*)+0x1c2
>testee>err>   pc 0x0000559c4a840687 fp 0x00007fc1c20fb7a0 dart::GroupDebugger::NotifyCompilation(dart::Function const&)+0x1a7
>testee>err>   pc 0x0000559c4a86b66b fp 0x00007fc1c20fb830 dart::IsolateGroup::RunWithStoppedMutatorsCallable(dart::Callable*, dart::Callable*, bool)+0x16b
>testee>err>   pc 0x0000559c4aabc5b1 fp 0x00007fc1c20fbf60 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0x821
>testee>err>   pc 0x0000559c4aabd232 fp 0x00007fc1c20fc880 out/DebugX64/dart-sdk/bin/dart+0x27f5232
>testee>err>   pc 0x0000559c4aabcd3d fp 0x00007fc1c20fc910 dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)+0xfd
>testee>err>   pc 0x0000559c4a914963 fp 0x00007fc1c20fc950 dart::Function::EnsureHasCode() const+0x53
>testee>err>   pc 0x0000559c4aabafea fp 0x00007fc1c20fd0c0 dart::DRT_CompileFunction(dart::NativeArguments)+0x1ea
>testee>err>   pc 0x00007fc1f9082e62 fp 0x00007fc1c20fd108 Unknown symbol
>testee>err>   pc 0x00007fc1f9082ec4 fp 0x00007fc1c20fd138 Unknown symbol
>testee>err>   pc 0x00007fc1f82bd261 fp 0x00007fc1c20fd168 Unknown symbol
>testee>err>   pc 0x00007fc1f82a5c96 fp 0x00007fc1c20fd1d0 Unknown symbol
>testee>err>   pc 0x00007fc1f82a5fb4 fp 0x00007fc1c20fd218 Unknown symbol
>testee>err>   pc 0x00007fc1f82a5c96 fp 0x00007fc1c20fd280 Unknown symbol
>testee>err>   pc 0x00007fc1f82a4cc9 fp 0x00007fc1c20fd2d8 Unknown symbol
>testee>err>   pc 0x00007fc1f90832e4 fp 0x00007fc1c20fd350 Unknown symbol
>testee>err>   pc 0x0000559c4a82f05f fp 0x00007fc1c20fd3c0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&)+0x12f
>testee>err>   pc 0x0000559c4a831c35 fp 0x00007fc1c20fd420 dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&)+0xf5
>testee>err>   pc 0x0000559c4a86662d fp 0x00007fc1c20fdbb0 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message>>)+0x37d
>testee>err>   pc 0x0000559c4a8a4685 fp 0x00007fc1c20fdc40 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x1d5
>testee>err>   pc 0x0000559c4a8a5327 fp 0x00007fc1c20fdcc0 dart::MessageHandler::TaskCallback()+0x307
>testee>err>   pc 0x0000559c4aa9f340 fp 0x00007fc1c20fdd50 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x180
>testee>err>   pc 0x0000559c4aa9fc6b fp 0x00007fc1c20fdda0 dart::ThreadPool::Worker::Main(unsigned long)+0x12b
>testee>err>   pc 0x0000559c4a9d1cb3 fp 0x00007fc1c20fdef0 out/DebugX64/dart-sdk/bin/dart+0x2709cb3
>testee>err> -- End of DumpStackTrace
>testee>err>   pc 0x0000000000000000 fp 0x00007fc1c20fd108 sp 0x0000000000000000 [Stub] CallToRuntime
>testee>err>   pc 0x00007fc1f9082ec4 fp 0x00007fc1c20fd138 sp 0x00007fc1c20fd118 [Stub] LazyCompile
>testee>err>   pc 0x00007fc1f82bd261 fp 0x00007fc1c20fd168 sp 0x00007fc1c20fd148 [Unoptimized] foo
>testee>err>   pc 0x00007fc1f82a5c96 fp 0x00007fc1c20fd1d0 sp 0x00007fc1c20fd178 [Unoptimized] _Closure@0150898.dyn:call
>testee>err>   pc 0x00007fc1f82a5fb4 fp 0x00007fc1c20fd218 sp 0x00007fc1c20fd1e0 [Unoptimized] _delayEntrypointInvocation@1026248.<anonymous closure>
>testee>err>   pc 0x00007fc1f82a5c96 fp 0x00007fc1c20fd280 sp 0x00007fc1c20fd228 [Unoptimized] _Closure@0150898.dyn:call
>testee>err>   pc 0x00007fc1f82a4cc9 fp 0x00007fc1c20fd2d8 sp 0x00007fc1c20fd290 [Unoptimized] _RawReceivePort@1026248._handleMessage@1026248
>testee>err>   pc 0x00007fc1f90832e4 fp 0x00007fc1c20fd350 sp 0x00007fc1c20fd2e8 [Stub] InvokeDartCode
>testee>err> === Crash occurred when compiling file:///b/s/w/ir/cache/builder/sdk/pkg/vm_service/test/break_on_function_many_child_isolates_test.dart_::_foo in unoptimized JIT mode in unknown pass
>testee>err> === Flow Graph not available

stderr:
Unhandled exception:
Testee exited with unexpected exitCode: -6
#0      _ServiceTesterRunner.run (file:///b/s/w/ir/cache/builder/sdk/pkg/vm_service/test/common/test_helper.dart:326:9)
<asynchronous suspension>
#1      runIsolateTests (file:///b/s/w/ir/cache/builder/sdk/pkg/vm_service/test/common/test_helper.dart:393:5)
<asynchronous suspension>
#2      main (file:///b/s/w/ir/cache/builder/sdk/pkg/vm_service/test/break_on_function_child_isolate_test.dart:9:3)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n unittest-asserts-debug-linux pkg/vm_service/test/break_on_function_child_isolate_test

```

FYI @rmacnak-google @aam

**Comment by aam** [comment]
@bkonyi are these tests being run on some bot?

**Comment by bkonyi** [comment]
Yeah, this assertion failed on the pkg-linux debug bot. I marked the test
as failing for now.
