### ISSUE TITLE
[gardening] disassemble_test started failing on vm-linux-debug-ia32

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#53348]
There are new test failures on [[vm/ffi] Closure callbacks for sync callbacks...[test] Improve dependency checking in package_deps.dart test](https://github.com/dart-lang/sdk/compare/db8f386c77f05f35e96d5d873a5b6d52557a5acc~...e8d7425c4ea8765c1e349db9197563dcb45b9638).

The tests
```
language/unsorted/disassemble_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-linux-debug-ia32
```

```
DART_CONFIGURATION=DebugIA32 out/DebugIA32/dart --suppress-core-dump --sound-null-safety -Dtest_runner.configuration=vm-linux-debug-ia32 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/language/unsorted/disassemble_test.dart

exit code:
255

stdout:
+ out/DebugIA32/dart --disassemble /b/s/w/ir/tests/language/unsorted/disassemble_test.dart --child

stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <-6>) fails.
#0      Expect._fail (package:expect/expect.dart:721:5)
#1      Expect.equals (package:expect/expect.dart:145:5)
#2      main (file:///b/s/w/ir/tests/language/unsorted/disassemble_test.dart:31:10)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-linux-debug-ia32 language/unsorted/disassemble_test
```

Log: https://dart-ci.appspot.com/log/vm-linux-debug-ia32/vm-linux-debug-ia32/145/language/unsorted/disassemble_test

Starting bisection locally:

```
tools/bisect.dart \
-Dend=db8f386c77f05f35e96d5d873a5b6d52557a5acc \
-Dstart=e8d7425c4ea8765c1e349db9197563dcb45b9638 \
-Dsdk_path="/usr/local/google/home/dacoharkes/master-dart-sdk/sdk/" \
-Dtest_command="python3 tools/test.py --build -n vm-linux-debug-ia32 language/unsorted/disassemble_test" \
-Dfailure_string="<-6>) fails."
```

Ensuring SDK repo in /usr/local/google/home/dacoharkes/master-dart-sdk/sdk/.
Ensuring failure reproduces on e8d7425c4ea8765c1e349db9197563dcb45b9638.
Commit e8d7425c4ea8765c1e349db9197563dcb45b9638, reproduces failure.
Ensuring failure does not reproduce on d3eb747f45f.
Commit d3eb747f45f, does not reproduce failure.
Bisecting e8d7425c4ea...b6aa6dbcaeb (27 commits). Trying 7040faf81f3.
Commit 7040faf81f3, reproduces failure.
Bisecting 7040faf81f3...b6aa6dbcaeb (14 commits). Trying 55a105851c5.
Commit 55a105851c5, reproduces failure.
Bisecting 55a105851c5...b6aa6dbcaeb (7 commits). Trying 30e8ed84107.
Bisecting 55a105851c5...b1594fa1309 (6 commits). Trying 30e8ed84107.
Commit 30e8ed84107, reproduces failure.
Bisecting 30e8ed84107...b1594fa1309 (3 commits). Trying 9f9da91b846.
Commit 9f9da91b846, does not reproduce failure.
Bisected to 30e8ed84107.

**Comment by dcharkes** [comment]
30e8ed841079aa89e1284dd78e271dbe332d5b3a is a CFE commit, so this probably uncovered an existing issue in the disassembler, investigating.

**Comment by dcharkes** [comment]
Local repro:

```
$ out/DebugIA32/dart --disassemble /usr/local/google/home/dacoharkes/dart-sdk/sdk/tests/language/unsorted/disassemble_test.dart --child
[...]
Code for function 'dart:developer_::__registerExtension@5383715' (RegularFunction) {
        ;; B0
        ;; B1
        ;; Enter frame
        ;; PrologueOffset = 0
0xf678d370    55                     push ebp
0xf678d371    89e5                   mov ebp,esp
0xf678d373    68991b1cf6             push 0xf61c1b99   Code([Unoptimized] _registerExtension)
0xf678d378    83ec04                 sub esp,4
        ;; Initialize spill slots
0xf678d37b    b84180c8f7             mov eax,0xf7c88041
0xf678d380    8945f8                 mov [ebp-0x8],eax
        ;; Edge counter
0xf678d383    b8011a1cf6             mov eax,0xf61c1a01   _List len:2
0xf678d388    83400f02               add [eax+0xf],2
        ;; t0 <- LoadLocal(method @2)
0xf678d38c    ff750c                 push [ebp+0xc]
        ;; t1 <- LoadLocal(handler @1)
0xf678d38f    ff7508                 push [ebp+0x8]
        ;; t2 <- Constant(#null)
0xf678d392    684180c8f7             push 0xf7c88041
        ;; t0 <- NativeCall(Developer_registerExtension)
0xf678d397    8d442408               lea eax,[esp+0x8]
0xf678d39b    ba02000000             mov edx,2
0xf678d3a0    b9e0598f58             mov ecx,0x588f59e0
0xf678d3a5    ff15c4cbc8f7           call [0xf7c8cbc4]
0xf678d3ab    8b0424                 mov eax,[esp]
0xf678d3ae    83c40c                 add esp,0xc
0xf678d3b1    50                     push eax
        ;; Return:8(t0)
0xf678d3b2    58                     pop eax
        ;; Stack Check
0xf678d3b3    89e7                   mov edi,esp
0xf678d3b5    2bfd                   sub edi,ebp
0xf678d3b7    83fff8                 cmp edi,-8
0xf678d3ba    7401                   jz 0xf678d3bd
0xf678d3bc    cc                     int3
0xf678d3bd    89ec                   mov esp,ebp
0xf678d3bf    5d                     pop ebp
0xf678d3c0    c3                     ret
0xf678d3c1    cc                     int3
}
Pointer offsets for function: {
 4 : 0xf678d374 'Code([Unoptimized] _registerExtension)'
 20 : 0xf678d384 '_List len:2'
}
ObjectPool len:0 {
}
Source positions for function 'dart:developer_::__registerExtension@5383715' {
f678d370-f678d382: Function '_registerExtension@5383715': static.@DartCodePrologue
f678d383-f678d38b: Function '_registerExtension@5383715': static.@ControlFlow
f678d38c-f678d391: Function '_registerExtension@5383715': static.@NoSource
f678d392-f678d3aa: Function '_registerExtension@5383715': static.@2356
f678d3ab-f678d3b1: Function '_registerExtension@5383715': static.@2356
f678d3b2-f678d3c0: Function '_registerExtension@5383715': static.@NoSource
}
PC Descriptors for function 'dart:developer_::__registerExtension@5383715' {
pc              kind            deopt-id        tok-ix  try-ix  yield-idx
0x1c            deopt           2               NoSource        -1      -1
0x3b            other           -1              2356    -1      -1
0x42            deopt           8               NoSource        -1      -1
}
StackMaps for function 'dart:developer_::__registerExtension@5383715' {
}
Exception Handlers for function 'dart:developer_::__registerExtension@5383715' {
empty ExceptionHandlers
}
Entry points for function 'dart:developer_::__registerExtension@5383715' {
  [code+0x03] f678d370 kNormal
  [code+0x07] f678d370 kMonomorphic
  [code+0x0b] f678d370 kUnchecked
  [code+0x0f] f678d370 kMonomorphicUnchecked
}
Static call target functions {
  0xf678d3ab: [Stub] CallBootstrapNative, (call-via-code)
}
../../runtime/vm/token_position.h: 174: error: expected: IsReal()
version=3.2.0-edge.e8d7425c4ea8765c1e349db9197563dcb45b9638 (be) (Fri Aug 25 03:35:44 2023 +0000) on "linux_ia32"
pid=2123053, thread=2123066, isolate_group=kernel-service(0xf6204500), isolate=(nil)((nil))
os=linux, arch=ia32, comp=no, sim=no
isolate_instructions=0, vm_instructions=587780e0
fp=f58fb7d8, sp=f58fb744, pc=58b933cb
  pc 0x58b933cb fp 0xf58fb7d8 dart::Profiler::DumpStackTrace(void*)+0x9b
  pc 0x591912c1 fp 0xf58fb7f8 Dart_DumpNativeStackTrace+0x21
  pc 0x587782d6 fp 0xf58fb828 dart::Assert::Fail(char const*, ...) const+0x36
  pc 0x58abcd5e fp 0xf58fb878 out/DebugIA32/dart+0x2530d5e
  pc 0x58afd9d2 fp 0xf58fb8c8 dart::Code::QualifiedName(dart::NameFormattingParams const&) const+0x112
  pc 0x58afd896 fp 0xf58fb8f8 dart::Code::ToCString() const+0x46
  pc 0x58c7ffcd fp 0xf58fb938 dart::DisassembleToStdout::ConsumeInstruction(char*, int, char*, int, dart::Object*, unsigned int)+0x9d
  pc 0x58c80387 fp 0xf58fca98 dart::Disassembler::Disassemble(unsigned int, unsigned int, dart::DisassemblyFormatter*, dart::Code const&, dart::CodeComments const*)+0x177
  pc 0x58afaef9 fp 0xf58fcaf8 out/DebugIA32/dart+0x256eef9
  pc 0x58afae1a fp 0xf58fcb38 dart::Code::Disassemble(dart::DisassemblyFormatter*) const+0x8a
  pc 0x58c80731 fp 0xf58fcc08 dart::Disassembler::DisassembleCodeHelper(char const*, char const*, dart::Code const&, bool)+0xb1
  pc 0x58c81a56 fp 0xf58fcc68 dart::Disassembler::DisassembleCode(dart::Function const&, dart::Code const&, bool)+0x196
  pc 0x58c76ffd fp 0xf58fd068 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0xa4d
  pc 0x58c77c81 fp 0xf58fd618 out/DebugIA32/dart+0x26ebc81
  pc 0x58c77711 fp 0xf58fd688 dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)+0x101
  pc 0x58abee09 fp 0xf58fd6c8 dart::Function::EnsureHasCode() const+0x79
  pc 0x58c75813 fp 0xf58fdaf8 dart::DRT_CompileFunction(dart::NativeArguments)+0x233
  pc 0xf7981dd1 fp 0xf58fdb1c Unknown symbol
  pc 0xf7981e1b fp 0xf58fdb30 Unknown symbol
  pc 0xf0ff3bc5 fp 0xf58fdb88 Unknown symbol
  pc 0xf156538f fp 0xf58fdbc4 Unknown symbol
  pc 0xf1563a3c fp 0xf58fdc00 Unknown symbol
  pc 0xf156228d fp 0xf58fdc4c Unknown symbol
  pc 0xf1561af1 fp 0xf58fdc74 Unknown symbol
  pc 0xf1e77fdd fp 0xf58fdcc0 Unknown symbol
  pc 0xf1e77c09 fp 0xf58fdd08 Unknown symbol
  pc 0xf15618a5 fp 0xf58fdd38 Unknown symbol
  pc 0xf15615c1 fp 0xf58fdd60 Unknown symbol
  pc 0xf1e77fdd fp 0xf58fddac Unknown symbol
  pc 0xf1e77c09 fp 0xf58fddf4 Unknown symbol
  pc 0xf150129e fp 0xf58fde30 Unknown symbol
  pc 0xf1e7c4ad fp 0xf58fdf3c Unknown symbol
  pc 0xf1e79f06 fp 0xf58fdfdc Unknown symbol
  pc 0xf1560c41 fp 0xf58fe018 Unknown symbol
  pc 0xf1560881 fp 0xf58fe040 Unknown symbol
  pc 0xf1e77fdd fp 0xf58fe08c Unknown symbol
  pc 0xf1e77c09 fp 0xf58fe0d4 Unknown symbol
  pc 0xf1560723 fp 0xf58fe104 Unknown symbol
  pc 0xf1560636 fp 0xf58fe128 Unknown symbol
  pc 0xf155fb61 fp 0xf58fe164 Unknown symbol
  pc 0xf15602f8 fp 0xf58fe198 Unknown symbol
  pc 0xf155ff91 fp 0xf58fe1c8 Unknown symbol
  pc 0xf155fdfe fp 0xf58fe1ec Unknown symbol
  pc 0xf155fb61 fp 0xf58fe228 Unknown symbol
  pc 0xf0f92983 fp 0xf58fe25c Unknown symbol
  pc 0xf0f9271e fp 0xf58fe280 Unknown symbol
  pc 0xf155fb61 fp 0xf58fe2bc Unknown symbol
  pc 0xf15602f8 fp 0xf58fe2f0 Unknown symbol
  pc 0xf155ff91 fp 0xf58fe320 Unknown symbol
  pc 0xf155fdfe fp 0xf58fe344 Unknown symbol
  pc 0xf155fb61 fp 0xf58fe380 Unknown symbol
  pc 0xf155de9f fp 0xf58fe3b4 Unknown symbol
  pc 0xf155a87f fp 0xf58fe410 Unknown symbol
  pc 0xf1542f27 fp 0xf58fe464 Unknown symbol
  pc 0xf0fc3f77 fp 0xf58fe4a4 Unknown symbol
  pc 0xf0fc37bb fp 0xf58fe4d4 Unknown symbol
  pc 0xf366f893 fp 0xf58fe534 Unknown symbol
  pc 0xf366d1f4 fp 0xf58fe5d4 Unknown symbol
  pc 0xf366a6fc fp 0xf58fe600 Unknown symbol
  pc 0xf3669536 fp 0xf58fe628 Unknown symbol
  pc 0xf3667d7a fp 0xf58fe680 Unknown symbol
  pc 0xf366748c fp 0xf58fe6c8 Unknown symbol
  pc 0xf3614467 fp 0xf58fe71c Unknown symbol
  pc 0xf36114dc fp 0xf58fe770 Unknown symbol
  pc 0xf3610680 fp 0xf58fe7a0 Unknown symbol
  pc 0xf153ca77 fp 0xf58fe7e8 Unknown symbol
  pc 0xf54d437e fp 0xf58fe80c Unknown symbol
  pc 0xf54d413d fp 0xf58fe848 Unknown symbol
  pc 0xf54d3fef fp 0xf58fe878 Unknown symbol
  pc 0xf54d3eab fp 0xf58fe8c0 Unknown symbol
  pc 0xf54d913c fp 0xf58fe8e4 Unknown symbol
  pc 0xf54be9ec fp 0xf58fe91c Unknown symbol
  pc 0xf54be7a4 fp 0xf58fe948 Unknown symbol
  pc 0xf54be120 fp 0xf58fe98c Unknown symbol
  pc 0xf54c4ab7 fp 0xf58fe9b0 Unknown symbol
  pc 0xf54d16e8 fp 0xf58fe9d0 Unknown symbol
  pc 0xf54d13c5 fp 0xf58fe9ec Unknown symbol
  pc 0xf54d130b fp 0xf58fe9fc Unknown symbol
  pc 0xf54c2a5c fp 0xf58fea18 Unknown symbol
  pc 0xf54c4243 fp 0xf58fea54 Unknown symbol
  pc 0xf54c2c57 fp 0xf58fea6c Unknown symbol
  pc 0xf54c2b2e fp 0xf58fea80 Unknown symbol
  pc 0xf54a3904 fp 0xf58feab0 Unknown symbol
  pc 0xf54a2821 fp 0xf58fead8 Unknown symbol
  pc 0xf7982122 fp 0xf58feb08 Unknown symbol
  pc 0x589c6d4a fp 0xf58feb68 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&)+0x15a
  pc 0x589c6b98 fp 0xf58feba8 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)+0x88
  pc 0x589c9d5f fp 0xf58fec08 dart::DartLibraryCalls::HandleMessage(long long, dart::Instance const&)+0x10f
  pc 0x58a01b04 fp 0xf58ff068 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message>>)+0x3c4
  pc 0x58a43fc6 fp 0xf58ff0e8 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x216
  pc 0x58a44d19 fp 0xf58ff158 dart::MessageHandler::TaskCallback()+0x309
  pc 0x58a45de9 fp 0xf58ff198 out/DebugIA32/dart+0x24b9de9
  pc 0x58c5e779 fp 0xf58ff208 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x1b9
  pc 0x58c5f090 fp 0xf58ff258 dart::ThreadPool::Worker::Main(unsigned int)+0x140
  pc 0x58b8c32b fp 0xf58ff3b8 out/DebugIA32/dart+0x260032b
  pc 0xf7a8793d fp 0xf58ff428 /lib/i386-linux-gnu/libc.so.6+0x8793d
-- End of DumpStackTrace
  pc 0x00000000 fp 0xf58fdb1c sp 0x00000000 [Stub] CallToRuntime
  pc 0xf7981e1b fp 0xf58fdb30 sp 0xf58fdb24 [Stub] LazyCompile
  pc 0xf0ff3bc5 fp 0xf58fdb88 sp 0xf58fdb38 [Unoptimized] FlowModel.rebaseForward
  pc 0xf156538f fp 0xf58fdbc4 sp 0xf58fdb90 [Unoptimized] TrivialVariableReference.addPreviousInfo
  pc 0xf1563a3c fp 0xf58fdc00 sp 0xf58fdbcc [Unoptimized] _FlowAnalysisImpl@400436592.variableRead
  pc 0xf156228d fp 0xf58fdc4c sp 0xf58fdc08 [Unoptimized] InferenceVisitorImpl.visitVariableGet
  pc 0xf1561af1 fp 0xf58fdc74 sp 0xf58fdc54 [Unoptimized] VariableGet.accept1
  pc 0xf1e77fdd fp 0xf58fdcc0 sp 0xf58fdc7c [Unoptimized] InferenceVisitorImpl._inferExpression@376144522
  pc 0xf1e77c09 fp 0xf58fdd08 sp 0xf58fdcc8 [Unoptimized] InferenceVisitorImpl.inferExpression
  pc 0xf15618a5 fp 0xf58fdd38 sp 0xf58fdd10 [Unoptimized] InferenceVisitorImpl.visitStringConcatenation
  pc 0xf15615c1 fp 0xf58fdd60 sp 0xf58fdd40 [Unoptimized] StringConcatenation.accept1
  pc 0xf1e77fdd fp 0xf58fddac sp 0xf58fdd68 [Unoptimized] InferenceVisitorImpl._inferExpression@376144522
  pc 0xf1e77c09 fp 0xf58fddf4 sp 0xf58fddb4 [Unoptimized] InferenceVisitorImpl.inferExpression
  pc 0xf150129e fp 0xf58fde30 sp 0xf58fddfc [Unoptimized] InferenceVisitorBase._inferInvocation@399229695.inferArgument
  pc 0xf1e7c4ad fp 0xf58fdf3c sp 0xf58fde38 [Unoptimized] InferenceVisitorBase._inferInvocation@399229695
  pc 0xf1e79f06 fp 0xf58fdfdc sp 0xf58fdf44 [Unoptimized] InferenceVisitorBase.inferInvocation
  pc 0xf1560c41 fp 0xf58fe018 sp 0xf58fdfe4 [Unoptimized] InferenceVisitorImpl.visitStaticInvocation
  pc 0xf1560881 fp 0xf58fe040 sp 0xf58fe020 [Unoptimized] StaticInvocation.accept1
  pc 0xf1e77fdd fp 0xf58fe08c sp 0xf58fe048 [Unoptimized] InferenceVisitorImpl._inferExpression@376144522
  pc 0xf1e77c09 fp 0xf58fe0d4 sp 0xf58fe094 [Unoptimized] InferenceVisitorImpl.inferExpression
  pc 0xf1560723 fp 0xf58fe104 sp 0xf58fe0dc [Unoptimized] InferenceVisitorImpl.visitExpressionStatement
  pc 0xf1560636 fp 0xf58fe128 sp 0xf58fe10c [Unoptimized] ExpressionStatement.accept
  pc 0xf155fb61 fp 0xf58fe164 sp 0xf58fe130 [Unoptimized] InferenceVisitorImpl.inferStatement
  pc 0xf15602f8 fp 0xf58fe198 sp 0xf58fe16c [Unoptimized] InferenceVisitorImpl._visitStatements@376144522
  pc 0xf155ff91 fp 0xf58fe1c8 sp 0xf58fe1a0 [Unoptimized] InferenceVisitorImpl.visitBlock
  pc 0xf155fdfe fp 0xf58fe1ec sp 0xf58fe1d0 [Unoptimized] Block.accept
  pc 0xf155fb61 fp 0xf58fe228 sp 0xf58fe1f4 [Unoptimized] InferenceVisitorImpl.inferStatement
  pc 0xf0f92983 fp 0xf58fe25c sp 0xf58fe230 [Unoptimized] InferenceVisitorImpl.visitIfStatement
  pc 0xf0f9271e fp 0xf58fe280 sp 0xf58fe264 [Unoptimized] IfStatement.accept
  pc 0xf155fb61 fp 0xf58fe2bc sp 0xf58fe288 [Unoptimized] InferenceVisitorImpl.inferStatement
  pc 0xf15602f8 fp 0xf58fe2f0 sp 0xf58fe2c4 [Unoptimized] InferenceVisitorImpl._visitStatements@376144522
  pc 0xf155ff91 fp 0xf58fe320 sp 0xf58fe2f8 [Unoptimized] InferenceVisitorImpl.visitBlock
  pc 0xf155fdfe fp 0xf58fe344 sp 0xf58fe328 [Unoptimized] Block.accept
  pc 0xf155fb61 fp 0xf58fe380 sp 0xf58fe34c [Unoptimized] InferenceVisitorImpl.inferStatement
  pc 0xf155de9f fp 0xf58fe3b4 sp 0xf58fe388 [Unoptimized] TypeInferrerImpl.inferFunctionBody
  pc 0xf155a87f fp 0xf58fe410 sp 0xf58fe3bc [Unoptimized] BodyBuilder.finishFunction
  pc 0xf1542f27 fp 0xf58fe464 sp 0xf58fe418 [Unoptimized] DietListener.buildFunctionBody
  pc 0xf0fc3f77 fp 0xf58fe4a4 sp 0xf58fe46c [Unoptimized] DietListener._endClassMethod@364262754
  pc 0xf0fc37bb fp 0xf58fe4d4 sp 0xf58fe4ac [Unoptimized] DietListener.endClassMethod
  pc 0xf366f893 fp 0xf58fe534 sp 0xf58fe4dc [Unoptimized] Parser.parseMethod
  pc 0xf366d1f4 fp 0xf58fe5d4 sp 0xf58fe53c [Unoptimized] Parser.parseClassOrMixinOrExtensionOrEnumMemberImpl
  pc 0xf366a6fc fp 0xf58fe600 sp 0xf58fe5dc [Unoptimized] Parser.parseClassOrMixinOrExtensionBody
  pc 0xf3669536 fp 0xf58fe628 sp 0xf58fe608 [Unoptimized] Parser.parseClass
  pc 0xf3667d7a fp 0xf58fe680 sp 0xf58fe630 [Unoptimized] Parser.parseClassOrNamedMixinApplication
  pc 0xf366748c fp 0xf58fe6c8 sp 0xf58fe688 [Unoptimized] Parser._handleModifiersForClassDeclaration@384022801
  pc 0xf3614467 fp 0xf58fe71c sp 0xf58fe6d0 [Unoptimized] Parser.parseTopLevelKeywordDeclaration
  pc 0xf36114dc fp 0xf58fe770 sp 0xf58fe724 [Unoptimized] Parser.parseTopLevelDeclarationImpl
  pc 0xf3610680 fp 0xf58fe7a0 sp 0xf58fe778 [Unoptimized] Parser.parseUnit
  pc 0xf153ca77 fp 0xf58fe7e8 sp 0xf58fe7a8 [Unoptimized] SourceLoader.buildBody
  pc 0xf54d437e fp 0xf58fe80c sp 0xf58fe7f0 [Unoptimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0xf54d413d fp 0xf58fe848 sp 0xf58fe814 [Unoptimized] _rootRunUnary@4048458
  pc 0xf54d3fef fp 0xf58fe878 sp 0xf58fe850 [Unoptimized] _rootRunUnary@4048458
  pc 0xf54d3eab fp 0xf58fe8c0 sp 0xf58fe880 [Unoptimized] _CustomZone@4048458.runUnary
  pc 0xf54d913c fp 0xf58fe8e4 sp 0xf58fe8c8 [Unoptimized] _SuspendState@4048458._awaitCompletedFuture@4048458.run
  pc 0xf54be9ec fp 0xf58fe91c sp 0xf58fe8ec [Unoptimized] _rootRun@4048458
  pc 0xf54be7a4 fp 0xf58fe948 sp 0xf58fe924 [Unoptimized] _rootRun@4048458
  pc 0xf54be120 fp 0xf58fe98c sp 0xf58fe950 [Unoptimized] _CustomZone@4048458.run
  pc 0xf54c4ab7 fp 0xf58fe9b0 sp 0xf58fe994 [Unoptimized] _CustomZone@4048458.bindCallback.<anonymous closure>
  pc 0xf54d16e8 fp 0xf58fe9d0 sp 0xf58fe9b8 [Unoptimized] _microtaskLoop@4048458
  pc 0xf54d13c5 fp 0xf58fe9ec sp 0xf58fe9d8 [Unoptimized] _startMicrotaskLoop@4048458
  pc 0xf54d130b fp 0xf58fe9fc sp 0xf58fe9f4 [Unoptimized] _startMicrotaskLoop@4048458
  pc 0xf54c2a5c fp 0xf58fea18 sp 0xf58fea04 [Unoptimized] _runPendingImmediateCallback@1026248
  pc 0xf54c4243 fp 0xf58fea54 sp 0xf58fea20 [Unoptimized] _Timer@1026248._runTimers@1026248
  pc 0xf54c2c57 fp 0xf58fea6c sp 0xf58fea5c [Unoptimized] _Timer@1026248._handleMessage@1026248
  pc 0xf54c2b2e fp 0xf58fea80 sp 0xf58fea74 [Unoptimized] _Timer@1026248._handleMessage@1026248
  pc 0xf54a3904 fp 0xf58feab0 sp 0xf58fea88 [Unoptimized] _Closure@0150898.dyn:call
  pc 0xf54a2821 fp 0xf58fead8 sp 0xf58feab8 [Unoptimized] _RawReceivePort@1026248._handleMessage@1026248
  pc 0xf7982122 fp 0xf58feb08 sp 0xf58feae0 [Stub] InvokeDartCode
=== Crash occurred when compiling package:_fe_analyzer_shared/src/flow_analysis/flow_analysis.dart_FlowModel_rebaseForward_##0#1#initializer in unoptimized JIT mode in unknown pass
=== Flow Graph not available
Aborted
```

**Comment by dcharkes** [comment]
The function it's trying to compile: `0xf7b52820 "Function '##0#1#initializer':."`.

However, we don't actually print this with --disassemble, the next function printed if the crash is avoided:

```
Code for function 'dart:_builtin_::__resolveScriptUri@15225868' (RegularFunction) {
        ;; B0
        ;; B1
        ;; Invocation Count Check
0xf668d3d0    bb31aac8f6             mov ebx,0xf6c8aa31   Function '_resolveScriptUri@15225868': static.
0xf668d3d5    ff4347                 inc [ebx+0x47]
0xf668d3d8    817b4730750000         cmp [ebx+0x47],0x7530
0xf668d3df    7c06                   jl 0xf668d3e7
0xf668d3e1    ffa620010000           jmp [esi+0x120]
[...]
```

**Comment by dcharkes** [comment]
Fix that prevents the disassembler from crashing: https://dart-review.googlesource.com/c/sdk/+/322663

cc @stereotype441 Any idea if your field promotion might have influenced the way initializers are being emitted?
cc @johnniwinther Should these functions be the field-initializer functions? Any chance we're missing position information somewhere?

**Comment by dcharkes** [comment]
pkg/vm/lib/transformations/late_var_init_transformer.dart

```dart
  List<Statement> _transformVariableDeclaration(VariableDeclaration node) {
    final fnNode =
        FunctionNode(ReturnStatement(node.initializer), returnType: node.type);
    final functionType =
        fnNode.computeThisFunctionType(Nullability.nonNullable);
    final fn = FunctionDeclaration(
        VariableDeclaration("#${node.name}#initializer",
            type: functionType, isSynthesized: true),
        fnNode);
    node.initializer = LocalFunctionInvocation(fn.variable, Arguments([]),
        functionType: functionType)
      ..parent = node;

    return [fn, node];
  }
```

@johnniwinther Should the nodes created here have a fileOffset?

**Comment by johnniwinther** [comment]
cc @alexmarkov

**Comment by alexmarkov** [comment]
Disassembler should not crash when source position is missing, so the fix https://dart-review.googlesource.com/c/sdk/+/322663 lgtm.

Generally speaking, kernel AST which is synthesized by the front-end or lowering kernel transformations may miss source positions for the things which are not present in the original Dart source code (and not directly related to a certain source code). VM should not crash when some of the source positions are missing. Debugger skips code without source positions when single stepping, which avoids extra unnecessary stops and jumps back and forth.

`##0#1#initializer` is likely a desugaring of the pattern matching code. It is an additional synthetic code inserted by the front-end out of line - hoisted up to the statement level, so assigning source positions to this code would cause undesired jumps in the debugger.

**Comment by dcharkes** [comment]
Thanks for the analysis @alexmarkov! ❤️ 

Then this issue can be closed.
