### ISSUE TITLE
Switch expression make compiler crash if case not defined properly

### ISSUE THREAD

**Issue by rebaz94** [dart-lang/sdk#53408]
I tried to run the following code: 

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:freezed_annotation/freezed_annotation.dart';

part 'main.freezed.dart';

@freezed
class Result<T> with _$Result<T> {
  const Result._();

  const factory Result(T data) = ResultData<T>;

  const factory Result.error([
    String? message,
    Object? error,
    StackTrace? stackTrace,
  ]) = ResultError<T>;
}

@freezed
class TestModel with _$TestModel {
  const factory TestModel({
    required String data,
  }) = _TestModel;
}

void main() {
  runApp(
    ProviderScope(
      child: const MyApp(),
    ),
  );
}

final testDataProvider = FutureProvider.autoDispose<Result<TestModel>>((ref) async {
  await Future.delayed(const Duration(seconds: 1));
  return const Result(
    TestModel(data: 'hi'),
  );
});

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    var testData = ref.watch(testDataProvider);
    print(testData);

    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              switch (testData) {
                AsyncError() || AsyncData<ResultError>() => Text('Error'),
                AsyncData<ResultData<TestModel>>(
                  isLoading: false,
                  :final value,
                ) =>
                  switch (value) {
                    ResultData(:final data) => Text(data.data),
                  },
                _ => CircularProgressIndicator(),
              }
            ],
          ),
        ),
      ),
    );
  }
}

```

it run successfully but after ~70 seconds the compiler crash and app exit.

here the error:
```
Unhandled exception:
Null check operator used on a null value
#0      ConstantsTransformer._checkExhaustiveness (package:front_end/src/fasta/kernel/constant_evaluator.dart:1542:43)
dart-lang/language#1      ConstantsTransformer.visitSwitchExpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:2045:5)
dart-lang/language#2      SwitchExpression.accept1 (package:kernel/src/ast/patterns.dart:1926:14)
dart-lang/language#3      RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1970:21)
dart-lang/language#4      RemovingTransformer.transformList (package:kernel/visitor.dart:2203:19)
dart-lang/language#5      RemovingTransformer.transformExpressionList (package:kernel/visitor.dart:2129:5)
dart-lang/language#6      Arguments.transformOrRemoveChildren (package:kernel/ast.dart:5768:7)
dart-lang/language#7      RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
dart-lang/language#8      TreeVisitor1.visitArguments (package:kernel/visitor.dart:894:46)
dart-lang/language#9      Arguments.accept1 (package:kernel/ast.dart:5749:53)
dart-lang/language#10     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
dart-lang/language#11     StaticInvocation.transformOrRemoveChildren (package:kernel/ast.dart:7054:21)
dart-lang/language#12     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
dart-lang/language#13     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:547:50)
dart-lang/language#14     TreeVisitor1.visitStaticInvocation (package:kernel/visitor.dart:619:7)
dart-lang/language#15     ConstantsTransformer.visitStaticInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:2180:35)
dart-lang/language#16     StaticInvocation.accept1 (package:kernel/ast.dart:7033:9)
dart-lang/language#17     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
dart-lang/language#18     ConstantsTransformer.visitVariableDeclaration (package:front_end/src/fasta/kernel/constant_evaluator.dart:695:28)
dart-lang/language#19     VariableDeclaration.accept1 (package:kernel/ast.dart:11408:9)
dart-lang/language#20     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1970:21)
dart-lang/language#21     ConstantsTransformer.visitBlock (package:front_end/src/fasta/kernel/constant_evaluator.dart:831:27)
dart-lang/language#22     Block.accept1 (package:kernel/ast.dart:9774:58)
dart-lang/language#23     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
dart-lang/language#24     BlockExpression.transformOrRemoveChildren (package:kernel/ast.dart:9378:16)
dart-lang/language#25     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
dart-lang/language#26     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:547:50)
dart-lang/language#27     TreeVisitor1.visitBlockExpression (package:kernel/visitor.dart:701:7)
dart-lang/language#28     BlockExpression.accept1 (package:kernel/ast.dart:9352:9)
dart-lang/language#29     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1970:21)
dart-lang/language#30     RemovingTransformer.transformOrRemoveExpression (package:kernel/visitor.dart:1943:12)
dart-lang/language#31     ReturnStatement.transformOrRemoveChildren (package:kernel/ast.dart:10808:22)
dart-lang/language#32     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
dart-lang/language#33     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:780:48)
dart-lang/language#34     TreeVisitor1.visitReturnStatement (package:kernel/visitor.dart:826:7)
dart-lang/language#35     ReturnStatement.accept1 (package:kernel/ast.dart:10790:9)
dart-lang/language#36     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
dart-lang/language#37     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:651:19)
dart-lang/language#38     FunctionNode.accept1 (package:kernel/ast.dart:4202:9)
dart-lang/language#39     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
dart-lang/language#40     ConstantsTransformer.visitProcedure.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:552:23)
dart-lang/language#41     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:5259:18)
dart-lang/language#42     ConstantsTransformer.visitProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:550:23)
dart-lang/language#43     transformProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:176:24)
dart-lang/language#44     KernelTarget.runProcedureTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1587:15)
dart-lang/language#45     IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:2062:28)
<asynchronous suspension>
dart-lang/language#46     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:1855:12)
<asynchronous suspension>
dart-lang/language#47     FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:973:28)
<asynchronous suspension>
dart-lang/language#48     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1409:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.

```

also the switch expression does not match when the `Result` is an error of type `ResultError`.
for example returning error inside the provider
```dart
final testDataProvider = FutureProvider.autoDispose<Result<TestModel>>((ref) async {
  await Future.delayed(const Duration(seconds: 1));
  return Result.error('error');

  // return const Result(
  //   TestModel(data: 'hi'),
  // );
});
```

inside the build I can verify that by checking type like below:
```
    var testData = ref.watch(testDataProvider);
    if (testData is AsyncData && testData.value is ResultError) {
      print('value is ResultError');
    }
```

but switch expression like 
```dart
switch (testData) {
     AsyncError() || AsyncData<ResultError>() => Text('Error'),
     _ => Text('unmatched'),
}
```

**Comment by munificent** [comment]
cc @johnniwinther

**Comment by rebaz94** [comment]
@johnniwinther I'm using ```Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_arm64"```

The issue occurs specifically when the app is launched with debugging enabled.

**Comment by johnniwinther** [comment]
@parlough I was mistaken. It is only part of 3.2.

**Comment by johnniwinther** [comment]
The fix is in `3.2.0-42.2.beta`. @rebaz94 can you try this beta version and see if the problem persists?

**Comment by rebaz94** [comment]
@johnniwinther Thank you, it's working fine on the beta version.

**Comment by johnniwinther** [comment]
Thanks. I'll close this issue then.
