### ISSUE TITLE
IL test failures on [vm/compiler] Fix InferredTypeMetadata::IsTrivial

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#53511]
There are new test failures on [[vm/compiler] Fix InferredTypeMetadata::IsTrivial](https://github.com/dart-lang/sdk/commit/7ff975c2e5c405b97cb0bcff11461e72a408aa84).

The tests
```
vm/dart/load_indexed_trivial_type_il_test Crash (expected Pass)
vm/dart/regress_48764_il_test Crash (expected Pass)
vm/dart/regress_51790_il_test Crash (expected Pass)
```
are failing on configurations
```
dartkp-weak-asserts-linux-release-x64
```

Example [log](https://dart-ci.appspot.com/log/vm-kernel-precomp-linux-release-x64/dartkp-weak-asserts-linux-release-x64/15784/vm/dart/load_indexed_trivial_type_il_test) for `vm/dart/load_indexed_trivial_type_il_test`:
```
--- Command "compare_il" (took 01.000832s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/compare_il /b/s/w/ir/runtime/tests/vm/dart/load_indexed_trivial_type_il_test.dart /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-weak-asserts-linux-release-x64/runtime_tests_vm_dart_load_indexed_trivial_type_il_test/out.il

exit code:
255

stdout:
matching IL (After AllocateRegisters) for forInListOfInt
Failed to match: Unmatched instruction: unbox(e) <- UnboxInt64({i: [e]}) in block B3
B0[GraphEntry]
  v0 <- Constant[value: null]()
  v25 <- Constant[value: Instance of _TypeParameter]()
  v152 <- UnboxedConstant[value: 0]()
  v153 <- UnboxedConstant[value: 1]()
B1[FunctionEntry]
  v2 <- Parameter[index: 0]()
  ParallelMove()
  v63 <- LoadField[slot: :type_arguments](v2)
  ParallelMove()
  v106 <- LoadField[slot: GrowableObjectArray.length](v2)
  ParallelMove()
  v137 <- UnboxInt64(v106)
  ParallelMove()
  v121 <- LoadField[slot: GrowableObjectArray.data](v2)
  ParallelMove()
  Goto() goto [14]
B14[JoinEntry]
  v5 <- Phi(v152, v9)
  v148 <- Phi(v152, v42)
  ParallelMove()
  CheckStackOverflow()
  Branch if RelationalOp[kind: >=](v148, v137) then  goto [4, 3]
B4[TargetEntry]
  ParallelMove()
  Return(v5)
B3[TargetEntry]
  ParallelMove()
  GenericCheckBound(v137, v148)
  v179 <- LoadIndexed(v121, v148)
  ParallelMove()
  ParallelMove()
  v42 <- BinaryInt64Op(v148, v153)
  ParallelMove()
  Branch if StrictCompare[kind: ===](v179, v0) then  goto [8, 9]
B8[TargetEntry]
  ParallelMove()
  AssertAssignable(v179, v25, v63, v0)
  Goto() goto [10]
B9[TargetEntry]
  Goto() goto [10]
B10[JoinEntry]
  CheckNull(v179)
  v143 <- UnboxInt64(v179)
  ParallelMove()
  v9 <- BinaryInt64Op(v5, v143)
  Goto() goto [14]

stderr:
Unhandled exception:
Failed to match
#0      FlowGraph.match (package:vm/testing/il_matchers.dart:45:9)
#1      matchIL$forInListOfInt (file:///b/s/w/ir/runtime/tests/vm/dart/load_indexed_trivial_type_il_test.dart:21:9)
#2      _LibraryMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:999:68)
#3      _ObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:248:25)
#4      TestCase.run (file:///b/s/w/ir/pkg/vm/bin/compare_il.dart:65:13)
#5      main (file:///b/s/w/ir/pkg/vm/bin/compare_il.dart:39:10)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartkp-weak-asserts-linux-release-x64 vm/dart/load_indexed_trivial_type_il_test
```

It looks like the tests are written assuming sound null safety.

/cc @mraleph

**Comment by mraleph** [comment]
I think we can ignore these failures given that unsound null-safety is on its way out and these tests are just testing whether specific optimizations based on static types succeed or fail.
