### ISSUE TITLE
Analyzer's `resolveFile2` now crashes with `PathNotFoundException`, failing to find the Dart SDK

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#53530]
Running `resolveFile2` in a test file with a valid absolute path throws PathNotFoundException.

There are a few variants of the same error thrown:

```
[exception: PathNotFoundException(path=/Users/remirousselet/dev/flutter/bin/cache/artifacts/engine/lib/_internal/sdk_library_metadata/lib/libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:159:7)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:521:41)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:420:18)
#3      ContextBuilderImpl._createSdk (package:analyzer/src/dart/analysis/context_builder.dart:192:21)
#4      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:104:15)
#5      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:95:36)
#6      _createAnalysisContext (package:analyzer/dart/analysis/utilities.dart:127:42)
#7      resolveFile2 (package:analyzer/dart/analysis/utilities.dart:117:7)
#8      _runGoldenTest.<anonymous closure> (file:///Users/remirousselet/dev/rrousselGit/riverpod/packages/riverpod_lint_flutter_test/test/assists/convert_to_widget_test.dart:161:28)
#9      testGolden.<anonymous closure> (file:///Users/remirousselet/dev/rrousselGit/riverpod/packages/riverpod_lint_flutter_test/test/golden.dart:29:31)
#10     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
<asynchronous suspension>
#11     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
```

```
[exception: PathNotFoundException(path=/Users/remirousselet/dev/flutter/bin/cache/artifacts/engine/lib/_internal/libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:159:7)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:521:41)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:420:18)
#3      ContextBuilderImpl._createSdk (package:analyzer/src/dart/analysis/context_builder.dart:192:21)
#4      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:104:15)
#5      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:95:36)
#6      _createAnalysisContext (package:analyzer/dart/analysis/utilities.dart:127:42)
#7      resolveFile2 (package:analyzer/dart/analysis/utilities.dart:117:7)
#8      _runGoldenTest.<anonymous closure> (file:///Users/remirousselet/dev/rrousselGit/riverpod/packages/riverpod_lint_flutter_test/test/assists/convert_to_widget_test.dart:161:28)
#9      testGolden.<anonymous closure> (file:///Users/remirousselet/dev/rrousselGit/riverpod/packages/riverpod_lint_flutter_test/test/golden.dart:29:31)
#10     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
<asynchronous suspension>
#11     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
```

```
  PathNotFoundException(path=/Users/remirousselet/dev/flutter/bin/cache/artifacts/engine/version; message=Cannot open file)
  package:analyzer/file_system/physical_file_system.dart 159:7               _PhysicalFile.readAsStringSync
  package:analyzer/src/dart/sdk/sdk.dart 444:12                              FolderBasedDartSdk.languageVersion
  package:analyzer/src/dart/analysis/context_builder.dart 212:40             ContextBuilderImpl._createSdk
  package:analyzer/src/dart/analysis/context_builder.dart 104:15             ContextBuilderImpl.createContext
  package:analyzer/src/dart/analysis/analysis_context_collection.dart 95:36  new AnalysisContextCollectionImpl
  package:analyzer/dart/analysis/utilities.dart 127:42                       _createAnalysisContext
  package:analyzer/dart/analysis/utilities.dart 117:7                        resolveFile2
  test/assists/convert_to_widget_test.dart 161:28                            _runGoldenTest.<fn>
  test/golden.dart 29:31    
```

It appears that while `flutter/bin/cache/artifacts/engine` exists, the folder contains neither a `lib` nor a `version` file/folder inside it.

Tried on both Flutter's stable channel and master channel.
I also tried `pub downgrade` and `pub upgrade` (against analyzer 5.12.0 and 6.2.0 respectively)

```
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5 22G74 darwin-arm64, locale en-FR)
    • Flutter version 3.13.4 on channel stable at /Users/remirousselet/dev/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 367f9ea16b (31 hours ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/remirousselet/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/remirousselet/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.73.20230904

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.
```

**Comment by rrousselGit** [comment]
It appears that this is a property of `flutter test`.
I tried running my test suite with `dart test` instead of `flutter test` and it passed, with resolveFile2 working fine.

Maybe there's something in the Flutter SDK not properly set.

**Comment by scheglov** [comment]
When `sdkPath` is not provided, `AnalysisContextCollectionImpl` uses
```
String getSdkPath() => path.dirname(path.dirname(Platform.resolvedExecutable));
```
Which means that the SDK must be enclose the whatever executable is run. It seems that the executable is now different, not `dart-sdk/bin/dart`.

I have no idea how it is packaged in Flutter. Maybe @devoncarew knows who to ask.

**Comment by devoncarew** [comment]
Hmm, perhaps this can be bisected to a dart sdk change, or a flutter sdk change?

@a-siva or @christopherfujino may know if there were any changes wrt what `resolvedExecutable` returns, or, the layout or behavior of the dart sdk vended in the flutter sdk.

**Comment by christopherfujino** [comment]
Hmm, we didn't change anything about where the dart binary is. Not sure exactly what `Platform.resolvedExecutable` is doing, though.

**Comment by rrousselGit** [comment]
It's worth nothing that as of late, when switching Flutter channel I've had to use --force.
Flutter somehow thinks that there are uncommitted local changes and rejects the channel switch, even though that isn't the case.

Since the path listed here seems to point to cache, maybe that's related, with some cache going in the wrong dir?

**Comment by christopherfujino** [comment]
> It's worth nothing that as of late, when switching Flutter channel I've had to use --force. Flutter somehow thinks that there are uncommitted local changes and rejects the channel switch, even though that isn't the case.
> 
> Since the path listed here seems to point to cache, maybe that's related, with some cache going in the wrong dir?

That is this issue: https://github.com/flutter/flutter/issues/133441, which I'm **pretty** sure is unrelated...

**Comment by elliotPopina** [comment]
Hello, i have the same problem when i'm running a dart compiled cli. in debug no problem, but if i compile my dart CLI (`dart compile exe bin/pragma_generator.dart -o release `) i have the exactly the same error when i run it

```dart
[exception: PathNotFoundException(path=/Users/elliot/workspace/pragma_pos/applications/lib/_internal/sdk_library_metadata/lib/libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:159)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:499)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:398)
#3      ContextBuilderImpl._createSdk (package:analyzer/src/dart/analysis/context_builder.dart:200)
#4      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:110)
#5      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:99)
#6      BuilderTest.build (file:///Users/elliotcunningham/workspace/pragma_pos/applications/pragma_generator/bin/src/builder/builder.dart:28)
#7      main (file:///Users/elliotcunningham/workspace/pragma_pos/applications/pragma_generator/bin/pragma_generator.dart:80)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
]
```

**Comment by bwilkerson** [comment]
First, please do not use `AnalysisContextCollectionImpl`. It's an internal class, so we make to guarantees concerning breaking changes. The public class is `AnalysisContextCollection`. If that class isn't sufficient for your use case, please open a new issue where we can discuss how best to support your use case. Thanks.

Second, the analyzer defaults to finding the SDK based on the assumption that it's being run from the SDK. When using the analyzer package in a non-sdk application you need to pass the path to the root of the Dart SDK to the `AnalysisContextCollection` constructor using the `sdkPath` parameter.

**Comment by dickermoshe** [comment]
I'm trying to work around this bug.
Is there a way to detect at runtime if I'm running from a `flutter run ...` command.
I would like to print a message for them to use `dart run ...` instead.

**Comment by huunam1108** [comment]
@rrousselGit 
I created my own Flutter custom lint and followed your `riverpod_lint` test setup (much simpler, just creating a `lint_code_test.dart` file and running `lint.testRun()`). Of course, I encountered the same issue with `resolvedFile2` in `flutter test`.

Have you found a solution or workaround for this?
