### ISSUE TITLE
dart package not able to open file inside src folder

### ISSUE THREAD

**Issue by git-elliot** [dart-lang/sdk#53562]
* Dart core libraries (`dart:async`, `dart:io`, etc.)
import 'dart:io';
* Dart version and tooling diagnostic info (`dart info`)

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_arm64"
- on macos / Version 14.0 (Build 23A339)
- locale is en-IN

#### Project info

- sdk constraint: '>=3.1.0 <4.0.0'
- dependencies: cupertino_icons, flutter
- dev_dependencies: flutter_lints, flutter_test
- elided dependencies: 1

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                    |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------- |
|  52 MB | 0.0% |        05:17 | dart devtools --machine --try-ports 10 --allow-embedding                        |
| 264 MB | 0.0% |        05:17 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.72.2 |
|  60 MB | 0.0% |        05:17 | flutter_tools.snapshot daemon                                                   |

I'm developing a package that uses csv file to load data into memory/db. This file resides in this package itself inside say (lib/src/assets/data/xyz.csv). Everything works as expected and I publish the package.
`final input = File('assets/data/xyz.csv').openRead();`
Now the problem starts when I use this package in some other project and now it throws me the error. 

```
ERROR:flutter/runtime/dart_isolate.cc(1097)] Unhandled exception:
PathNotFoundException: Cannot open file, path = 'assets/data/xyz.csv' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
<asynchronous suspension>
#2      _FileStream._start.onOpenFile (dart:io/file_impl.dart:153:5)
<asynchronous suspension>
Lost connection to device.
```
What is the issue now?
 CSV is packaged and available inside pub-cache folder but my code is trying to find this file in the other project. Relative path breaks here.

**Comment by brianquinlan** [comment]
@dcharkes I think that native assets might eventually fix this problem.

The workaround that people use currently is to embed the data in dart source. For example, you could have a Dart file like:

**`xyz.csv.dart`:**
```dart
final csv_data = r"""
<CSV data goes here>
"""
```

You then import that file and

**Comment by dcharkes** [comment]
@mosuem and I have been scheming of bringing the `AssetBundle` concept to the "native assets" feature. Our plan is to also support transforming (for example minifying or tree shaking) these assets in the `build.dart` or a `link.dart` step.
