### ISSUE TITLE
[cfe] Member access on type aliased extension type crashes the CFE

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#53564]
Consider the following program:

```dart
typedef A<X> = B<X>;
extension type const B<E>(List<E> it) implements List<E> {}

void main() => A<int>([1]).add(2);
```

This program is accepted by the analyzer, but it causes the CFE to encounter a dynamic error:

```
Invalid argument(s): Type parameter TypeParameter(List.E) is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:3321:8)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2524:38)
#2      TypeParameterType.accept (package:kernel/ast.dart:12314:42)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:440:10)
#4      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:349:7)
#5      BinaryPrinter.visitFunctionType (package:kernel/binary/ast_to_binary.dart:2487:7)
#6      FunctionType.accept (package:kernel/ast.dart:11378:42)
#7      BinaryPrinter.writeDartType (package:kernel/binary/ast_to_binary.dart:318:10)
#8      BinaryPrinter.visitInstanceInvocation (package:kernel/binary/ast_to_binary.dart:1776:5)
#9      InstanceInvocation.accept (package:kernel/ast.dart:5654:44)
#10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:440:10)
#11     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:532:7)
#12     BinaryPrinter.visitReturnStatement (package:kernel/binary/ast_to_binary.dart:2317:5)
#13     ReturnStatement.accept (package:kernel/ast.dart:10026:43)
#14     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:440:10)
#15     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:532:7)
#16     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1531:5)
#17     FunctionNode.accept (package:kernel/ast.dart:3773:38)
#18     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:447:10)
#19     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1358:5)
#20     Procedure.accept (package:kernel/ast.dart:3167:40)
#21     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:468:10)
#22     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:358:7)
#23     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1103:5)
#24     Library.accept (package:kernel/ast.dart:581:38)
#25     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:461:10)
#26     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:767:9)
#27     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:606:7)
#28     Timeline.timeSync (dart:developer/timeline.dart:173:22)
#29     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:587:14)
#30     serializeComponent (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/vm/bin/kernel_service.dart:1044:11)
#31     _processLoadRequest (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/vm/bin/kernel_service.dart:944:13)
<asynchronous suspension>
```

**Comment by chloestefantsova** [comment]
This appears to be fixed. Please reopen if needed.
