### ISSUE TITLE
Analysis server crashes in presence of augmentation libraries

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#53628]
I am getting started on writing some language tests, but presently opening them up will crash the entire analysis server :).

```
[4:45:44 PM] [Analyzer] [Error] Unhandled exception:
UnimplementedError
#0      AugmentationFileKind.asLibrary (package:analyzer/src/dart/analysis/file_state.dart:58:5)
#1      AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1516:42)
#2      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1137:29)
#3      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2262:24)
<asynchronous suspension>
```

**Comment by jakemac53** [comment]
Fwiw, the test I am trying to write has these two files:

**new_declaration_test.dart**:
```dart
// Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// SharedOptions=--enable-experiment=augmentation-libraries

import augment "new_declaration.dart";

main() {
  assert(foo == 'abc');
}
```
**new_declaration_test.dart**:
```dart
// Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

library augment 'new_declaration_test.dart';

String get foo => 'a';

augment int get foo => '${augment super} + b';

augment int get foo => '${augment super} + c';
```

**Comment by scheglov** [comment]
When I try to work with this code in tests, it fails slightly before:
```
  UnimplementedError: AstBuilder.handleAugmentSuperExpression
  #0      AstBuilder.handleAugmentSuperExpression (package:analyzer/src/fasta/ast_builder.dart:3647:5)
  #1      Parser.parseAugmentSuperExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6780:14)
  #2      Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6511:16)
  #3      Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6341:12)
  #4      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5784:13)
  #5      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5724:15)
  #6      Parser.parseSingleLiteralString (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7408:17)
```

So, I had to remove `augment super` for now.

But indeed, without `import augment` in the library, I get the exception that you see:
```
  UnimplementedError
  package:analyzer/src/dart/analysis/file_state.dart 60:5  AugmentationFileKind.asLibrary
  package:analyzer/src/dart/analysis/driver.dart 1322:42   AnalysisDriver._computeAnalysisResult
```

With `import augment` in place, there compile-time errors (because we don't support augmentations well enough, I switched to macros prototype), but no crash.

I will look how to find `AugmentationFileKind.asLibrary`.
