### ISSUE TITLE
[dart2wasm]  co19/Language/Classes/Instance_Methods/Method_noSuchMethod/forwarder_A01_t01 crashes the compiler

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53647]
[ co19/Language/Classes/Instance_Methods/Method_noSuchMethod/forwarder_A01_t01](https://github.com/dart-lang/co19/blob/master/Language/Classes/Instance_Methods/Method_noSuchMethod/definition_A01_t01.dart) crashes dart2wasm
[Log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8768717568051087185/+/u/test_results/new_test_failures__logs_)
```

/=======================================================================================================================\
| co19/Language/Classes/Instance_Methods/Method_noSuchMethod/forwarder_A01_t01 is new and failed (Crash, expected Pass) |
\=======================================================================================================================/

--- Command "dart2wasm" (took 01.000109s):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome sdk/bin/dart2wasm_developer -Dtest_runner.configuration=dart2wasm-linux-chrome /b/s/w/ir/tests/co19/src/Language/Classes/Instance_Methods/Method_noSuchMethod/forwarder_A01_t01.dart /b/s/w/ir/out/ReleaseX64/generated_tests/dart2wasm-linux-chrome/tests_co19_src_Language_Classes_Instance_Methods_Method_noSuchMethod_forwarder_A01_t01/forwarder_A01_t01.wasm

exit code:
255

stderr:
Unhandled exception:
'dart:collection-patch/compact_hash.dart': Failed assertion: line -1: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40)
#2      _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:429)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#4      _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:423)
#5      _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1539)
#6      TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1798)
#7      Call.apply (package:vm/transformations/type_flow/summary.dart:359)
#8      Summary.apply (package:vm/transformations/type_flow/summary.dart:1075)
#9      _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:307)
#10     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226)
#11     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1539)
#12     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1481)
#13     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1676)
#14     transformComponent (package:vm/transformations/type_flow/transformer.dart:114)
#15     compileToModule (package:dart2wasm/compile.dart:128)
<asynchronous suspension>
#16     main (package:dart2wasm/dart2wasm.dart:143)
<asynchronous suspension>
#17     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dart2wasm/bin/dart2wasm.dart:7)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dart2wasm-linux-chrome co19/Language/Classes/Instance_Methods/Method_noSuchMethod/forwarder_A01_t01
```

**Comment by osa1** [comment]
This test now passes: https://dart-current-results.web.app/#/filter=co19/Language/Classes/Instance_Methods/Method_noSuchMethod.
