### ISSUE TITLE
The compiler crashed when compiling an element.

### ISSUE THREAD

**Issue by manandhar-aarya** [dart-lang/sdk#53704]
I am trying to use JavaScript interop library to call a js function of  [stripe](https://stripe.com/en-gb-it). it says that the compiler crashed on this line: 

    Internal Error: The compiler crashed when compiling this element.
  
    external (dynamic paymentIntent, dynamic error) confirmCardPayment(String clientSecret, [Map paymentMethod, Map handleError]);
                                                    ^
    The compiler is broken.`

**Here are my environment details:**
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.10.4 on channel stable at /Users/aaryamanandhar/Libraries/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (4 months ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

**Here is the stack trace:**
The compiler crashed: UnimplementedError: isNonNullableIfSound (dynamic,dynamic)
#0      DartTypes.isNonNullableIfSound (package:compiler/src/elements/types.dart:2423:5)
#1      KernelSsaGraphBuilder._buildExternalNativeFunctionNode (package:compiler/src/ssa/builder.dart:1701:23)
#2      KernelSsaGraphBuilder._buildExternalFunctionNode (package:compiler/src/ssa/builder.dart:1587:7)
#3      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder.dart:468:15)
#4      DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#5      KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder.dart:456:21)
#6      KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:563:22)
#7      CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#8      KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:545:18)
#9      SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:361:21)
#10     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:87:28)
#11     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:421:30)
#12     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:337:43)
#13     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:504:29)
#14     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:830:70)
#15     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#16     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:830:32)
#17     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#18     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:828:28)
#19     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:826:18)
#21     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:252:12)
#22     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:268:5)
#23     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:822:16)
#24     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#25     Compiler.emptyQueue (package:compiler/src/compiler.dart:821:14)
#26     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:845:7)
#27     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#28     Compiler.processQueue (package:compiler/src/compiler.dart:839:14)
#29     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:557:5)
#30     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:771:23)
<asynchronous suspension>
#31     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:319:7)
<asynchronous suspension>
#32     Compiler.runInternal (package:compiler/src/compiler.dart:318:5)
<asynchronous suspension>
#33     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:239:11)
<asynchronous suspension>
#34     main (package:compiler/src/dart2js.dart:1473:3)
<asynchronous suspension>

#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:226:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#7      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:81:34)
<asynchronous suspension>
#8      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:324:11)
<asynchronous suspension>
#9      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>

Finished with error: Exception: Failed to compile application for the Web.

**Comment by sigmundch** [comment]
One quick note in terms of the original example and Dart/JS interop: please note that records are not supported as parameters and return values of interop APIs. 

We are in the process of improving interop and making it easier to know when an API is supported or not. The reason you didn't see an error is because these improvements are being done in the new `dart:js_interop` library which will replace `package:js` in the long run. The new `dart:js_interop` will report an error if you try to use records in an external API. You can get a taste of the new APIs in the upcoming Dart 3.2 sdk.
