### ISSUE TITLE
Bad parser recovery with misshapen extension type, analyzer crash.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#53736]
Not sure if parser deliberately lets the invalid code through, and front-ends fail to give useful error messages,
or the parser should just have rejected earlier.
Example:
```dart
extension type F._<X>(X _) {}
```
where the `._` is before the `<X>`, not after where it belongs.
That gives the error:
```
Analyzing acr.dart...
Unhandled exception:
type 'Null' is not a subtype of type 'FormalParameterListImpl' in type cast
#0      AstBuilder.endPrimaryConstructor (package:analyzer/src/fasta/ast_builder.dart:2776:39)
#1      Parser.parseExtensionTypeDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3157:16)
#2      Parser.parseExtension (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3024:14)
...
```
suggesting that the parsing was considered "successful".

There is no crash in the CFE, which instead reports this cascade of badly recovered errors.
```
acr.dart:1:18: Error: A primary constructor declaration must have formal parameters.
Try adding formal parameters after the primary constructor name.
extension type F._<X>(X _){}
                 ^
acr.dart:1:18: Error: An extension type declaration must have a body, even if it is empty.
Try adding an empty body.
extension type F._<X>(X _){}
                 ^
acr.dart:1:19: Error: Expected a declaration, but got '<'.
extension type F._<X>(X _){}
                  ^
acr.dart:1:20: Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
Try adding the name of the type of the variable or the keyword 'var'.
extension type F._<X>(X _){}
                   ^
acr.dart:1:20: Error: Expected ';' after this.
extension type F._<X>(X _){}
                   ^
acr.dart:1:21: Error: Operators must be declared within a class.
Try removing the operator, moving it to a class, or converting it to be a function.
extension type F._<X>(X _){}
                    ^
acr.dart:1:23: Error: 'X' isn't a type.
extension type F._<X>(X _){}
                      ^
acr.dart:1:20: Context: This isn't a type.
extension type F._<X>(X _){}
                   ^
```

Possibly, just have the parser recognize type arguments before and after the primary constructor name, then fail parsing if there are any after. (That also leaves us room to add generic constructors eventually.)

(@scheglov Even with bad recovery, the analyzer probably shouldn't crash.)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/330242
