### ISSUE TITLE
Crash in GC marking

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#53761]
I get a segmentation fault in the Dart VM when I try to build my Flutter app in profile mode (debug mode works fine). Reproducibility is 100%.

```console
Launching lib/main.dart on Pixel 7 Pro in profile mode...
Building with Flutter multidex support enabled.

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x7fcee9b88080
version=3.1.3 (stable) (Tue Sep 26 14:25:13 2023 +0000) on "linux_x64"
pid=561051, thread=561058, isolate_group=main(0x5649f364a6d0), isolate=(nil)((nil))
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=7fcee10e0000, vm_instructions=5649f2031d20
fp=7fcec71feca0, sp=7fcec71fec70, pc=5649f22ce527
  pc 0x00005649f22ce527 fp 0x00007fcec71feca0 dart::MarkingVisitorBase<true>::VisitPointers+0x67
  pc 0x00005649f22ce913 fp 0x00007fcec71fece0 dart::MarkingVisitorBase<true>::DrainMarkingStackWithPauseChecks+0x193

  pc 0x00005649f22ce6bf fp 0x00007fcec71fed50 dart::ConcurrentMarkTask::Run+0x5f
  pc 0x00005649f22abc7b fp 0x00007fcec71fedd0 dart::ThreadPool::WorkerLoop+0x14b
  pc 0x00005649f22abf18 fp 0x00007fcec71fee00 dart::ThreadPool::Worker::Main+0x78
  pc 0x00005649f2235956 fp 0x00007fcec71feec0 dart::ThreadStart+0xd6

  pc 0x00007fcee3f92947 fp 0x00007fcec71fef70 /lib64/libc.so.6+0x8c947
-- End of DumpStackTrace
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/opt/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1297
* What went wrong:
Execution failed for task ':app:compileFlutterBuildProfile'.
> Process 'command '/opt/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleProfile failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:512:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:242:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:578:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:534:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
<asynchronous suspension>
#6      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:649:9)
<asynchronous suspension>
#7      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:647:5)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:641:15)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Exited
```

`flutter doctor -v` output:

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.7, on Fedora Linux 38 (Workstation Edition) 6.5.6-200.fc38.x86_64, locale en_US.utf8)
    • Flutter version 3.13.7 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (6 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.83.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • Pixel 7 Pro (mobile)       • 29161FDH300BLP • android-arm64  • Android 13 (API 33)
    • sdk gphone x86 64 (mobile) • emulator-5554  • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux          • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.5.6-200.fc38.x86_64
    • Chrome (web)               • chrome         • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by lukehutch** [comment]
This only happens in the stable channel, it doesn't happen with the beta channel. (I didn't check main or master.)

**Comment by rmacnak-google** [comment]
GC crashes are not debuggable from stack traces. Please provide a reproduction.
