### ISSUE TITLE
DevFs tests involving unusual characters in paths fail on Windows

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#53773]
There are new test failures on [[ package:vm_service ] Additional Observatory test migrations](https://github.com/dart-lang/sdk/commit/b68f533639ea0cb38fd09b8b7243bad1aa830e0c).

The tests
```
pkg/vm_service/test/private_rpcs/dev_fs_http_put_test RuntimeError (expected Pass)
pkg/vm_service/test/private_rpcs/dev_fs_http_put_weird_char_test RuntimeError (expected Pass)
pkg/vm_service/test/private_rpcs/dev_fs_weird_char_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win
```

Example logs:
[`pkg/vm_service/test/private_rpcs/dev_fs_http_put_test`](https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/26297/pkg/vm_service/test/private_rpcs/dev_fs_http_put_test):
```
stdout:
00:00 [32m+0[0m: dev_fs_http_put_test.dart[0m

** Launching SERVICE_TEST_TESTEE=true out\ReleaseX64\dart-sdk\bin\dart.exe --disable-dart-dev --disable-service-auth-codes --profiler --enable_asserts --sound-null-safety -Dtest_runner.configuration=unittest-asserts-release-win --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json --enable-vm-service:0 C:\b\s\w\ir\pkg\vm_service\test\private_rpcs\dev_fs_http_put_test.dart

>testee>out> The Dart VM service is listening on http://127.0.0.1:57393/
** Signaled to run test queries on http://127.0.0.1:57393/

>testee>out> 
Done loading VM

dev_fs_http_put_test.dart [1/1]

00:05 [32m+0[0m[31m -1[0m: dev_fs_http_put_test.dart [1m[31m[E][0m[0m

  FormatException: Unexpected character (at character 1)
  Invalid argument(s): Illegal character in path
  ^
  

  dart:convert-patch/convert_patch.dart 1383:5                      _ChunkedJsonParser.fail
  dart:convert-patch/convert_patch.dart 1250:9                      _ChunkedJsonParser.parseNumber
  dart:convert-patch/convert_patch.dart 915:22                      _ChunkedJsonParser.parse
  dart:convert-patch/convert_patch.dart 35:10                       _parseJson
  dart:convert/json.dart 610:36                                     JsonDecoder.convert
  dart:convert/json.dart 216:41                                     JsonCodec.decode
  dart:convert/json.dart 155:10                                     jsonDecode
  pkg\vm_service\test\private_rpcs\dev_fs_http_put_test.dart 47:14  tests.<fn>.postToDevFS
  ===== asynchronous gap ===========================
  pkg\vm_service\test\private_rpcs\dev_fs_http_put_test.dart 64:14  tests.<fn>
  ...
```
[`pkg/vm_service/test/private_rpcs/dev_fs_http_put_weird_char_test`](https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/26297/pkg/vm_service/test/private_rpcs/dev_fs_http_put_weird_char_test):
```
stdout:
00:00 [32m+0[0m: dev_fs_http_put_weird_char_test.dart[0m

** Launching SERVICE_TEST_TESTEE=true out\ReleaseX64\dart-sdk\bin\dart.exe --disable-dart-dev --disable-service-auth-codes --profiler --enable_asserts --sound-null-safety -Dtest_runner.configuration=unittest-asserts-release-win --ignore-unrecognized-flags --packages=C:\b\s\w\ir\cache\builder\sdk\.dart_tool\package_config.json --enable-vm-service:0 C:\b\s\w\ir\cache\builder\sdk\pkg\vm_service\test\private_rpcs\dev_fs_http_put_weird_char_test.dart

>testee>out> The Dart VM service is listening on http://127.0.0.1:60731/
** Signaled to run test queries on http://127.0.0.1:60731/

>testee>out> 
Done loading VM

dev_fs_http_put_weird_char_test.dart [1/1]

00:03 [32m+0[0m[31m -1[0m: dev_fs_http_put_weird_char_test.dart [1m[31m[E][0m[0m

  FormatException: Unexpected character (at character 1)
  FileSystemException: Cannot open file, path = 'C:\b\s\w\ir\x\t\test9ff626b\...
  ^
  

  dart:convert-patch/convert_patch.dart 1383:5                                 _ChunkedJsonParser.fail
  dart:convert-patch/convert_patch.dart 1250:9                                 _ChunkedJsonParser.parseNumber
  dart:convert-patch/convert_patch.dart 915:22                                 _ChunkedJsonParser.parse
  dart:convert-patch/convert_patch.dart 35:10                                  _parseJson
  dart:convert/json.dart 610:36                                                JsonDecoder.convert
  dart:convert/json.dart 216:41                                                JsonCodec.decode
  dart:convert/json.dart 155:10                                                jsonDecode
  pkg\vm_service\test\private_rpcs\dev_fs_http_put_weird_char_test.dart 47:14  tests.<fn>.postToDevFS
  ===== asynchronous gap ===========================
  pkg\vm_service\test\private_rpcs\dev_fs_http_put_weird_char_test.dart 64:14  tests.<fn>
  ...
```
[`pkg/vm_service/test/private_rpcs/dev_fs_weird_char_test`](https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/26297/pkg/vm_service/test/private_rpcs/dev_fs_weird_char_test):
```
stdout:
00:00 [32m+0[0m: dev_fs_weird_char_test.dart[0m

** Launching SERVICE_TEST_TESTEE=true out\ReleaseX64\dart-sdk\bin\dart.exe --disable-dart-dev --disable-service-auth-codes --profiler --enable_asserts --sound-null-safety -Dtest_runner.configuration=unittest-asserts-release-win --ignore-unrecognized-flags --packages=C:\b\s\w\ir\cache\builder\sdk\.dart_tool\package_config.json --enable-vm-service:0 C:\b\s\w\ir\cache\builder\sdk\pkg\vm_service\test\private_rpcs\dev_fs_weird_char_test.dart

>testee>out> The Dart VM service is listening on http://127.0.0.1:60538/
** Signaled to run test queries on http://127.0.0.1:60538/

>testee>out> 
Done loading VM

dev_fs_weird_char_test.dart [1/1]

00:05 [32m+0[0m[31m -1[0m: dev_fs_weird_char_test.dart [1m[31m[E][0m[0m

  _writeDevFSFile: (-32603) Internal error
  _writeDevFSFile: Unexpected exception:Invalid argument(s): Illegal character in path
  #0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1838:11)
  #1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1932:7)
  #2      new _Uri.file (dart:core/uri.dart:1805:11)
  #3      _FileSystem.resolvePath (dart:_vmservice/devfs.dart:34:21)
  #4      DevFS._writeDevFSFile (dart:_vmservice/devfs.dart:301:16)
  #5      DevFS.handleMessage (dart:_vmservice/devfs.dart:108:16)
  #6      VMService._routeRequestImpl (dart:_vmservice:811:28)
  #7      VMService.routeRequest (dart:_vmservice:774:28)
  #8      Client.onRequest (dart:_vmservice/client.dart:54:15)
  #9      WebSocketClient.onWebSocketMessage (dart:vmservice_io/vmservice_server.dart:50:11)
  #10     new WebSocketClient.<anonymous closure> (dart:vmservice_io/vmservice_server.dart:27:32)
  ...
```

/cc @bkonyi

**Comment by Suyash0852** [comment]
assign me this issue
