### ISSUE TITLE
[cfe] Unhandled exception during compilation of extension type with record

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#53780]
Consider the following program:

```dart
extension type E<T>(({T t}) it) {
  T get t => it.t;
}

T run<T>(E<T> e) => switch (e) { E(:var t) => t };

void main() {}
```

This program causes the current front end (commit 4d1bdaaca9f600545e8517349714f6bf683ebbe3) to encounter an unhandled exception:

```
Crash when compiling:
type 'Null' is not a subtype of type 'Procedure' in type cast

#0      MatchingExpressionVisitor.visitObjectPattern (package:front_end/src/fasta/type_inference/matching_expressions.dart:414:68)
#1      ObjectPattern.accept1 (package:kernel/src/ast/patterns.dart:622:15)
#2      MatchingExpressionVisitor.visitPattern (package:front_end/src/fasta/type_inference/matching_expressions.dart:27:17)
#3      ConstantsTransformer.visitSwitchExpression.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:2017:14)
#4      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#5      ConstantsTransformer.visitSwitchExpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:2014:15)
#6      SwitchExpression.accept1 (package:kernel/src/ast/patterns.dart:1978:14)
#7      RemovingTransformer.transform (package:kernel/visitor.dart:1883:17)
#8      AsExpression.transformOrRemoveChildren (package:kernel/ast.dart:7596:17)
#9      RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2166:10)
#10     TreeVisitor1Default.defaultExpression (package:kernel/visitor.dart:739:50)
#11     ExpressionVisitor1DefaultMixin.visitAsExpression (package:kernel/visitor.dart:2359:52)
#12     AsExpression.accept1 (package:kernel/ast.dart:7579:9)
#13     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1919:21)
#14     RemovingTransformer.transformOrRemoveExpression (package:kernel/visitor.dart:1892:12)
#15     ReturnStatement.transformOrRemoveChildren (package:kernel/ast.dart:10108:22)
#16     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2166:10)
#17     TreeVisitor1Default.defaultStatement (package:kernel/visitor.dart:743:48)
#18     StatementVisitor1DefaultMixin.visitReturnStatement (package:kernel/visitor.dart:2589:7)
#19     ReturnStatement.accept1 (package:kernel/ast.dart:10090:9)
#20     RemovingTransformer.transform (package:kernel/visitor.dart:1883:17)
#21     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:643:19)
#22     FunctionNode.accept1 (package:kernel/ast.dart:3831:9)
#23     RemovingTransformer.transform (package:kernel/visitor.dart:1883:17)
#24     ConstantsTransformer.visitProcedure.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:560:23)
#25     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:5351:18)
#26     ConstantsTransformer.visitProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:558:23)
#27     Procedure.accept1 (package:kernel/ast.dart:3201:55)
#28     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1919:21)
#29     RemovingTransformer.transformList (package:kernel/visitor.dart:2143:19)
#30     RemovingTransformer.transformProcedureList (package:kernel/visitor.dart:2035:5)
#31     ConstantsTransformer.convertLibrary (package:front_end/src/fasta/kernel/constant_evaluator.dart:464:5)
#32     transformLibraries (package:front_end/src/fasta/kernel/constant_evaluator.dart:112:26)
#33     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1533:19)
#34     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:625:7)
<asynchronous suspension>
#35     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#36     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:575:12)
<asynchronous suspension>
#37     _buildInternal (package:front_end/src/kernel_generator_impl.dart:210:19)
<asynchronous suspension>
#38     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#39     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:49:12)
<asynchronous suspension>
#40     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139:3)
<asynchronous suspension>
#41     generateKernel (package:front_end/src/kernel_generator_impl.dart:48:10)
<asynchronous suspension>
#42     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#43     SingleShotCompilerWrapper.compileInternal (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/vm/bin/kernel_service.dart:415:11)
<asynchronous suspension>
```

**Comment by eernstg** [comment]
The same kind of unhandled exception occurs with a variant of the example where the record type is positional:

```dart
extension type E<T>((T}) it) {
  T get t => it.t;
}

T run<T>(E<T> e) => switch (e) { E(:var t) => t };

void main() {}
```
