### ISSUE TITLE
[analysis_server] An error occurred while handling textDocument/codeAction request: Bad state: No element

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#53786]
Unfortunately I don't have the exact steps, but I've noticed 4 of these issues in the output log with the same stack trace.
Here is the stack:

```text
[Error - 21:56:44] An error occurred while handling textDocument/codeAction request: Bad state: No element
#0      Iterable.first (dart:core/iterable.dart:643:7)
#1      SplitMultipleDeclarations.compute (package:analysis_server/src/services/correction/dart/split_multiple_declarations.dart:52:51)
#2      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1826:24)
#3      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1839:15)
#4      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1781:11)
#5      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:260:35)
#6      DartCodeActionsProducer.getFixActions (package:analysis_server/src/lsp/handlers/code_actions/dart.dart:172:44)
<asynchronous suspension>
#7      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#8      CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:206:16)
<asynchronous suspension>
#9      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:352:22)
<asynchronous suspension>
#10     LspAnalysisServer._handleRequestMessage (package:analysis_server/src/lsp/lsp_analysis_server.dart:1005:20)
<asynchronous suspension>
#11     LspAnalysisServer.handleMessage.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:471:15)
<asynchronous suspension>
#12     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#13     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:454:11)
<asynchronous suspension>
```

**Comment by pq** [comment]
I'm not sure how to reproduce this but there's an easy guard against the unsafe call to `first`. Will put together a fix.

**Comment by pq** [comment]
Fxied w/ a19c07ffd46307485ffe7cbcca175941067e4994
