### ISSUE TITLE
co19/LibTest/io/Link/createSync_A06_t0{1,3} Pass -> RuntimeError on vm win bots

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#53848]
https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-win-debug-x64/2517/overview

```
--- Command "vm" (took 03.000845s):
set DART_CONFIGURATION=DebugX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64\crashpad_handler.exe & out\DebugX64\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-x64 --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\tests\co19\src\LibTest\io\Link\createSync_A06_t01.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <directory>, actual: <link>) fails.
#0      _fail (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect.dart:18:5)
#1      Expect.equals (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect_common.dart:15:7)
#2      _main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/createSync_A06_t01.dart:54:10)
#3      inSandbox (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/file_utils.dart:23:22)
#4      main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/createSync_A06_t01.dart:42:3)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-x64 co19/LibTest/io/Link/createSync_A06_t01
```

```
--- Command "vm" (took 03.000996s):
set DART_CONFIGURATION=DebugX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64\crashpad_handler.exe & out\DebugX64\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-x64 --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\tests\co19\src\LibTest\io\Link\createSync_A06_t03.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <directory>, actual: <link>) fails.
#0      _fail (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect.dart:18:5)
#1      Expect.equals (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect_common.dart:15:7)
#2      _main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/createSync_A06_t03.dart:54:10)
#3      inSandbox (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/file_utils.dart:23:22)
#4      main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/createSync_A06_t03.dart:42:3)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-x64 co19/LibTest/io/Link/createSync_A06_t03
```

cc @sgrekhov @brianquinlan 

Started with https://dart.googlesource.com/sdk/+/5315b1dc6b0518e99e458a59e1ef084767fb2b39

**Comment by sgrekhov** [comment]
This issue was reported as https://github.com/dart-lang/sdk/issues/53689
Something is wrong with relative links to directories on Windows

**Comment by mkustermann** [comment]
There's more tests like this that are failing, possibly due to same root cause, e.g. this flaky failure [see log](https://dart-ci.appspot.com/log/vm-aot-win-debug-x64c/vm-aot-win-debug-x64c/217/co19/LibTest/io/Link/createSync_A06_t06)

```
--- Command "vm_compile_to_kernel" (took 03.000344s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & C:\b\s\w\ir\pkg\vm\tool\gen_kernel.bat --aot --platform=out/DebugX64C/vm_platform_strong.dill -o C:\b\s\w\ir\out\DebugX64C\generated_compilations\vm-aot-win-debug-x64c\tests_co19_src_LibTest_io_Link_createSync_A06_t06\out.dill C:\b\s\w\ir\tests\co19\src\LibTest\io\Link\createSync_A06_t06.dart -Dtest_runner.configuration=vm-aot-win-debug-x64c --packages=C:\b\s\w\ir\.dart_tool\package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 21.000153s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\gen_snapshot --snapshot-kind=app-aot-elf --elf=C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_co19_src_LibTest_io_Link_createSync_A06_t06/out.aotsnapshot --loading-unit-manifest=C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_co19_src_LibTest_io_Link_createSync_A06_t06/ignored.json --sound-null-safety -Dtest_runner.configuration=vm-aot-win-debug-x64c --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\out\DebugX64C\generated_compilations\vm-aot-win-debug-x64c\tests_co19_src_LibTest_io_Link_createSync_A06_t06\out.dill

exit code:
0

--- Command "remove_kernel_file" (took 50ms):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & cmd.exe /c del C:\b\s\w\ir\out\DebugX64C\generated_compilations\vm-aot-win-debug-x64c\tests_co19_src_LibTest_io_Link_createSync_A06_t06\out.dill

exit code:
0

--- Command "vm" (took 264ms):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & set TEST_COMPILATION_DIR=C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_co19_src_LibTest_io_Link_createSync_A06_t06 & out\DebugX64C\dart_precompiled_runtime.exe --sound-null-safety -Dtest_runner.configuration=vm-aot-win-debug-x64c --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_co19_src_LibTest_io_Link_createSync_A06_t06/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <notFound>, actual: <link>) fails.
#0      _fail (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect.dart:18)
#1      Expect.equals (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect_common.dart:15)
#2      _main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/createSync_A06_t06.dart:66)
#3      inSandbox (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/file_utils.dart:23)
#4      main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/createSync_A06_t06.dart:41)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

--- Re-run this test:
python3 tools/test.py -n vm-aot-win-debug-x64c co19/LibTest/io/Link/createSync_A06_t06
```

**Comment by dcharkes** [comment]
The test is flaking, but now mentions directory instead of notFound:

```
--- Command "vm" (took 03.000840s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-x64c --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\tests\co19\src\LibTest\io\Link\createSync_A06_t01.dart

exit code:
255

stdout:
unittest-suite-wait-for-done
unittest-suite-success

stderr:
Unhandled exception:
Expect.equals(expected: <directory>, actual: <link>) fails.
#0      _fail (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect.dart:18:5)
#1      Expect.equals (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect_common.dart:15:7)
#2      _main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/createSync_A06_t01.dart:54:10)
#3      inSandbox (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/file_utils.dart:24:22)
#4      main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/createSync_A06_t01.dart:42:3)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-x64c co19/LibTest/io/Link/createSync_A06_t01
```

It's failing on all windows configurations: https://dart-current-results.web.app/#/filter=co19/LibTest/io/Link/createSync_A06_t01&showAll

**Comment by sgrekhov** [comment]
Both of the failures above are #53911

**Comment by a-siva** [comment]
@brianquinlan any updates on this issue ?

**Comment by brianquinlan** [comment]
I think that this is implementable now that we can drop Windows 7 support. I have a PR in progress.
