### ISSUE TITLE
co19/LibTest/io/Link/createSync tests fail on windows bots

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#53872]
windows buildbots are broken by failing co19 tests after https://dart-review.googlesource.com/c/sdk/+/331841

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-win-debug-x64/2551/overview

```
-- Command "vm_compile_to_kernel" (took 02.000811s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & C:\b\s\w\ir\pkg\vm\tool\gen_kernel.bat --aot --platform=out/DebugX64C/vm_platform_strong.dill -o C:\b\s\w\ir\out\DebugX64C\generated_compilations\vm-aot-win-debug-x64c\tests_co19_src_LibTest_io_Link_createSync_A04_t05\out.dill C:\b\s\w\ir\tests\co19\src\LibTest\io\Link\createSync_A04_t05.dart -Dtest_runner.configuration=vm-aot-win-debug-x64c --packages=C:\b\s\w\ir\.dart_tool\package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 20.000514s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\gen_snapshot --snapshot-kind=app-aot-elf --elf=C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_co19_src_LibTest_io_Link_createSync_A04_t05/out.aotsnapshot --loading-unit-manifest=C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_co19_src_LibTest_io_Link_createSync_A04_t05/ignored.json --sound-null-safety -Dtest_runner.configuration=vm-aot-win-debug-x64c --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\out\DebugX64C\generated_compilations\vm-aot-win-debug-x64c\tests_co19_src_LibTest_io_Link_createSync_A04_t05\out.dill

exit code:
0

--- Command "remove_kernel_file" (took 53ms):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & cmd.exe /c del C:\b\s\w\ir\out\DebugX64C\generated_compilations\vm-aot-win-debug-x64c\tests_co19_src_LibTest_io_Link_createSync_A04_t05\out.dill

exit code:
0

--- Command "vm" (took 241ms):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & set TEST_COMPILATION_DIR=C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_co19_src_LibTest_io_Link_createSync_A04_t05 & out\DebugX64C\dart_precompiled_runtime.exe --sound-null-safety -Dtest_runner.configuration=vm-aot-win-debug-x64c --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_co19_src_LibTest_io_Link_createSync_A04_t05/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <link>, actual: <notFound>) fails.
#0      _fail (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect.dart:18)
#1      Expect.equals (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect_common.dart:15)
#2      _main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/createSync_A04_t05.dart:50)
#3      inSandbox (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/file_utils.dart:23)
#4      main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/createSync_A04_t05.dart:41)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

--- Re-run this test:
python3 tools/test.py -n vm-aot-win-debug-x64c co19/LibTest/io/Link/createSync_A04_t05

```

cc @brianquinlan @sgrekhov

**Comment by sgrekhov** [comment]
This must be fixed by https://dart-review.googlesource.com/c/sdk/+/332206

**Comment by brianquinlan** [comment]
@sgrekhov What's the plan for the broken nullability tests?

**Comment by sgrekhov** [comment]
https://dart-review.googlesource.com/c/sdk/+/332206 will fix them. Waiting for landing of this CL

**Comment by sgrekhov** [comment]
@brianquinlan some tests are still failing. Let's see https://github.com/dart-lang/co19/blob/master/LibTest/io/Link/createSync_A04_t08.dart

It creates link to a directory. Then deletes the target. Link type became `notFound`. Then test creates a `File` with the same path. On non-Windows platforms the type of the `Link` became a `File`, on Windows tests still expects `notFound` (because the link is broken) but actual type is `link`. I can update the test but may be this is an issue?

**Comment by brianquinlan** [comment]
@sgrekhov This is probably a real issue. Could you file a new issue with a backtrace?

**Comment by sgrekhov** [comment]
https://github.com/dart-lang/sdk/issues/53911
