### ISSUE TITLE
native_assets test failures due to attempts to add to Unmodifiable lists

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#53881]
There are new test failures on [[vm/tests] Fix using clause in vm/dart/regress_306327173_il_test.](https://github.com/dart-lang/sdk/commit/437223150c87f64abb258a5f77ee488efb0a80ac).

The tests
```
native_assets_builder/test/build_runner/build_dependencies_test RuntimeError (expected Pass)
native_assets_builder/test/build_runner/build_runner_asset_id_test RuntimeError (expected Pass)
native_assets_builder/test/build_runner/build_runner_caching_test RuntimeError (expected Pass)
native_assets_builder/test/build_runner/build_runner_dry_run_test RuntimeError (expected Pass)
native_assets_builder/test/build_runner/build_runner_failure_test RuntimeError (expected Pass)
native_assets_builder/test/build_runner/build_runner_run_in_isolation_test RuntimeError (expected Pass)
native_assets_builder/test/build_runner/build_runner_test RuntimeError (expected Pass)
native_assets_builder/test/build_runner/packaging_preference_test RuntimeError (expected Pass)
pkg/dartdev/test/native_assets/build_test RuntimeError (expected Pass)
pkg/dartdev/test/native_assets/run_test RuntimeError (expected Pass)
pkg/dartdev/test/native_assets/test_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-linux
unittest-asserts-release-mac-arm64
```

Due to:

```
Unhandled exception:
Unsupported operation: Cannot add to an unmodifiable list
#0      UnmodifiableListMixin.addAll (dart:_internal/list.dart:129:5)
#1      CBuilder.run (package:native_toolchain_c/src/cbuilder/cbuilder.dart:276:45)
...
```

**Comment by dcharkes** [comment]
We need to revert the dart-lang/native in DEPS.

* https://github.com/dart-lang/native/issues/168

**Comment by dcharkes** [comment]
Oh, actually it didn't roll into Dart yet via DEPS, it's the resolution via pub because we have a published version, let me retract the published version on pub.

**Comment by dcharkes** [comment]
I think this should cycle green again with the bad version retracted.

Thanks for reporting @sstrickl !
