### ISSUE TITLE
[analysis_server] An error occurred while handling textDocument/codeAction request: Null check operator used on a null value

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#53888]
Noticed 3 of these with the same stack, unfortunately without steps.

```text
[Error - 11:59:43] An error occurred while handling textDocument/codeAction request: Null check operator used on a null value
#0      MoveTopLevelToFile._membersToMove (package:analysis_server/src/services/refactoring/move_top_level_to_file.dart:241:25)
#1      MoveTopLevelToFile.isAvailable (package:analysis_server/src/services/refactoring/move_top_level_to_file.dart:174:21)
#2      RefactoringProcessor.compute (package:analysis_server/src/services/refactoring/framework/refactoring_processor.dart:46:36)
#3      DartCodeActionsProducer.getRefactorActions (package:analysis_server/src/lsp/handlers/code_actions/dart.dart:223:39)
<asynchronous suspension>
#4      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#5      CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:219:14)
<asynchronous suspension>
#6      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:352:22)
<asynchronous suspension>
#7      LspAnalysisServer._handleRequestMessage (package:analysis_server/src/lsp/lsp_analysis_server.dart:1005:20)
<asynchronous suspension>
#8      LspAnalysisServer.handleMessage.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:471:15)
<asynchronous suspension>
#9      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#10     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:454:11)
<asynchronous suspension>
```

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
Happened when computing the "Move Top Level" changes if it was a multi-selection that included an unnamed extension (due to a non-null-assertion). Got a fix here:

https://dart-review.googlesource.com/c/sdk/+/332428
