### ISSUE TITLE
Analysis server crash(Code: -32013)

### ISSUE THREAD

**Issue by radomir9720** [dart-lang/sdk#53924]
Hi. Analysis server crahes on the following code:

```dart
class A {
  const A({required this.someEnum})
      : assert(
          someEnum.when(
            first: () => true,
            second: () => false,
          ),
        );

  final SomeEnum someEnum;
}

enum SomeEnum {
  firstOption('First'),
  secondOption('Second');

  final String id;

  const SomeEnum(this.id);

  R when<R>({
    required R Function() first,
    required R Function() second,
  }) {
    return switch (this) {
      SomeEnum.firstOption => first(),
      SomeEnum.secondOption => second(),
    };
  }
}

```

More precisely: it happens when there is a combintaion of `const` constructor and monad-like method in the assert

<details>
<summary>dart info</summary>

```
- Dart 3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "macos_x64"
- on macos / Version 13.3.1 (a) (Build 22E772610a)
- locale is ru-MD
```
</details>

<details>
<summary>"Extension host" logs</summary>

```
2023-11-01 19:03:34.171 [error] [Dart-Code.dart-code] provider FAILED
2023-11-01 19:03:34.171 [error] Error: File is not being analyzed
    at handleResponse (/Users/radom/.vscode/extensions/dart-code.dart-code-3.76.0/out/dist/extension.js:30091:48)
    at handleMessage (/Users/radom/.vscode/extensions/dart-code.dart-code-3.76.0/out/dist/extension.js:29871:13)
    at processMessageQueue (/Users/radom/.vscode/extensions/dart-code.dart-code-3.76.0/out/dist/extension.js:29888:17)
    at Immediate.<anonymous> (/Users/radom/.vscode/extensions/dart-code.dart-code-3.76.0/out/dist/extension.js:29860:13)
    at processImmediate (node:internal/timers:476:21)
```
</details>
<details>
<summary>LSP outputs</summary>

```
...
/Users/radom/StudioProjects/flutter 2.0 env/some.dart
[Error - 19:03:51] Request textDocument/documentHighlight failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/radom/StudioProjects/flutter 2.0 env/some.dart
[Error - 19:03:51] The Dart Analysis Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
</details>

<details>
<summary>Dart Analysis Server Logs</summary>

```
Dart Code extension: 3.76.0
Flutter extension: 3.76.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.83.1

Workspace type: Dart (LSP)

Dart (3.1.2): /Users/radom/development/flutter/bin/cache/dart-sdk
Flutter (3.13.4): /Users/radom/development/flutter (No device)


Logging Categories:
    General, Analyzer, CommandProcesses

Wed Nov 01 2023 [19:33:09 GMT+0200 (Восточная Европа, стандартное время)] Log file started

<DELETED INFO LOGS BECAUSE OF THE CHARACTERS LIMIT>
...

[19:33:13] [Analyzer] [Error] Unhandled exception:
Exception: Missing implementation of visitFunctionExpression
#0      ThrowingAstVisitor._throw (package:analyzer/dart/ast/visitor.dart:2859:5)
#1      ThrowingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:2528:58)
#2      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:8680:50)
#3      AstBinaryWriter._writeNode (package:analyzer/src/summary2/ast_binary_writer.dart:944:10)
#4      AstBinaryWriter.visitNamedExpression (package:analyzer/src/summary2/ast_binary_writer.dart:521:5)
#5      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:12984:50)
#6      AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:950:19)
#7      AstBinaryWriter.visitArgumentList (package:analyzer/src/summary2/ast_binary_writer.dart:55:5)
#8      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:514:50)
#9      AstBinaryWriter._writeNode (package:analyzer/src/summary2/ast_binary_writer.dart:944:10)
#10     AstBinaryWriter._storeInvocationExpression (package:analyzer/src/summary2/ast_binary_writer.dart:883:5)
#11     AstBinaryWriter.visitMethodInvocation (package:analyzer/src/summary2/ast_binary_writer.dart:511:5)
#12     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:12625:50)
#13     AstBinaryWriter._writeNode (package:analyzer/src/summary2/ast_binary_writer.dart:944:10)
#14     AstBinaryWriter.visitAssertInitializer (package:analyzer/src/summary2/ast_binary_writer.dart:72:5)
#15     AssertInitializerImpl.accept (package:analyzer/src/dart/ast/ast.dart:712:50)
#16     ResolutionSink._writeNode (package:analyzer/src/summary2/bundle_writer.dart:784:10)
#17     ResolutionSink._writeNodeList (package:analyzer/src/summary2/bundle_writer.dart:790:7)
#18     BundleWriter._writeConstructorElement.<anonymous closure> (package:analyzer/src/summary2/bundle_writer.dart:185:23)
#19     _LocalElementIndexer.withElements (package:analyzer/src/summary2/bundle_writer.dart:1051:6)
#20     BundleWriter._writeConstructorElement (package:analyzer/src/summary2/bundle_writer.dart:181:35)
#21     BundleWriter._writeList (package:analyzer/src/summary2/bundle_writer.dart:384:19)
#22     BundleWriter._writeClassElement.<anonymous closure> (package:analyzer/src/summary2/bundle_writer.dart:168:9)
#23     BundleWriter._writeTypeParameters.<anonymous closure> (package:analyzer/src/summary2/bundle_writer.dart:526:8)
#24     _LocalElementIndexer.withElements (package:analyzer/src/summary2/bundle_writer.dart:1051:6)
#25     BundleWriter._writeTypeParameters (package:analyzer/src/summary2/bundle_writer.dart:524:35)
#26     BundleWriter._writeClassElement (package:analyzer/src/summary2/bundle_writer.dart:153:5)
#27     BundleWriter._writeList (package:analyzer/src/summary2/bundle_writer.dart:384:19)
#28     BundleWriter._writeUnitElement (package:analyzer/src/summary2/bundle_writer.dart:535:5)
#29     BundleWriter.writeLibraryElement (package:analyzer/src/summary2/bundle_writer.dart:111:5)
#30     Linker._writeLibraries (package:analyzer/src/summary2/link.dart:307:20)
#31     Linker.link (package:analyzer/src/summary2/link.dart:100:5)
<asynchronous suspension>
#32     link (package:analyzer/src/summary2/link.dart:39:3)
<asynchronous suspension>
#33     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:180:24)
<asynchronous suspension>
#34     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:246:7)
<asynchronous suspension>
#35     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#36     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:244:5)
<asynchronous suspension>
#37     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1508:7)
<asynchronous suspension>
#38     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#39     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1127:22)
<asynchronous suspension>
#40     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2249:7)
<asynchronous suspension>


#0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:321:5)
#1      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:188:11)
<asynchronous suspension>
#2      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:246:7)
<asynchronous suspension>
#3      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#4      LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:244:5)
<asynchronous suspension>
#5      AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1508:7)
<asynchronous suspension>
#6      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1127:22)
<asynchronous suspension>
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2249:7)
<asynchronous suspension>
```
</details>

**Comment by lrhn** [comment]
Shouldn't crash.

Code is not valid, though, since asserts of const constructors cannot call methods.

**Comment by radomir9720** [comment]
> Shouldn't crash.
> 
> Code is not valid, though, since asserts of const constructors cannot call methods.

I know. I filled this issue not because i need help writing code, but because analysis server crashes.

**Comment by DanTup** [comment]
This is the same as https://github.com/dart-lang/sdk/issues/53075 and has been fixed by https://github.com/dart-lang/sdk/commit/ba1988e0d3acb340402a9d549db484eae933b65e for a future release.
