### ISSUE TITLE
[Analysis_server] Refactoring a named parameter in a function which is assigned to a variable throws a SERVER_ERROR (edit.getRefactoring)

### ISSUE THREAD

**Issue by dvigara-medallia** [dart-lang/sdk#53947]
Trying to refactor 'theNamedParameter' on **line 5** with 'edit.getRefactoring':
```
class TestingAnalyzer {
  final Function({int theNamedParameter}) functionWithNamedParameters;
  TestingAnalyzer({required this.functionWithNamedParameters});
  void testmethod() {
    functionWithNamedParameters(theNamedParameter: 3);
  }
}
```
throws this error:
```
SERVER_ERROR
Null check operator used on a null value
#0      RefactoringWorkspace.containsElement (package:analysis_server/src/services/refactoring/legacy/refactoring.dart:369:39)
#1      RenameRefactoringImpl.checkInitialConditions (package:analysis_server/src/services/refactoring/legacy/rename.dart:99:20)
#2      RefactoringManager._init (package:analysis_server/src/services/refactoring/legacy/refactoring_manager.dart:318:36)
<asynchronous suspension>
#3      RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/services/refactoring/legacy/refactoring_manager.dart:111:7)
<asynchronous suspension>
```

This is the request made:
```
request: {
  "id": String
  "method": "edit.getRefactoring"
  "params": {
    "kind": "RENAME"
    "file": "/Users/**/development/projects/flutter projects/analyzer_test/testing.dart"
    "offset": 213
    "length": 17
    "validateOnly": true
  }
}
```

The reason I'm trying to refactor the named parameter in line 5 is because **refactoring 'theNamedParameter in line 2 doesn't return any change to line 5.** It will return only this edit: 
`edits: [[SourceEdit offset: 46, length: 17, replacement: newNameForNamedParameter]
`
* Dart version and tooling diagnostic info (`dart info`):
#### General info

- Dart 3.1.4 (stable) (Tue Oct 17 14:55:53 2023 +0000) on "macos_arm64"
- on macos / Version 13.4.1 (Build 22F82)
- locale is en-IE

**Comment by bwilkerson** [comment]
@scheglov
