### ISSUE TITLE
Invalid code crashes the analyzer

### ISSUE THREAD

**Issue by fabiancrx** [dart-lang/sdk#53970]
## Dart info
```
#### General info

- Dart 3.1.4 (stable) (Tue Oct 17 14:55:53 2023 +0000) on "macos_arm64"
- on macos / Version 14.1 (Build 23B74)
- locale is en-US
```

## Code

If I remove the const in the constructor the analyzer no longer crashes

```dart
class NumberPool {
  final int capacity;
  final List<num> _values;

  const NumberPool(this.capacity, {List<num>? values})
      : _values = [...?values],
        assert(() {
          if (values != null && values.length > capacity) return false;
          return true;
        }(), 'The list provided to populate NumberPool has more elements(${values?.length}) than max($capacity}) allows');

  num get last => _values.last;

  void add(num value) {
    if (_values.length == capacity) _values.removeAt(0);
    _values.add(value);
  }

  bool get isEmpty => _values.isEmpty;

  bool get isFull => _values.length == capacity;

  List<num> get values => UnmodifiableListView(_values);

  num average() {
    double avg = 0;
    int t = 1;
    for (var x in _values) {
      avg += (x - avg) / t;
      ++t;
    }
    return avg;
  }
}
```
## Logs
```
/Users/myuser/Developer/diagram_playground/lib/number_pool.dart
[Info  - 6:33:21 PM] Connection to server got closed. Server will restart.
true
[Error - 6:33:23 PM] The Dart Analysis Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

```
App: Visual Studio Code
App Host: desktop
Version: mac 1.83.1

Workspace type: Flutter (LSP)

Dart (3.1.4): /Users/myuser/fvm/versions/stable/bin/cache/dart-sdk
Flutter (3.13.8): /Users/myuser/fvm/versions/stable (No device)
[6:33:16 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.connected","params":{"version":"0.6.1","pid":21971}}]
[6:33:16 PM] [FlutterDaemon] [Info] ==> [{"id":"1","method":"device.enable"}]
[6:33:16 PM] [FlutterDaemon] [Info] ==> [{"id":"2","method":"emulator.getEmulators"}]
[6:33:16 PM] [Analyzer] [Info] <== Content-Length: 641
Content-Type: application/vscode-jsonrpc; charset=utf-8
[6:33:16 PM] [Analyzer] [Info] <== {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"executeCommandProvider":{"commands":["edit.sortMembers","edit.organizeImports","edit.fixAll","edit.sendWorkspaceEdit","refactor.perform","refactor.validate","dart.logAction","dart.refactor.convert_all_formal_parameters_to_named","dart.refactor.convert_selected_formal_parameters_to_named","dart.refactor.move_selected_formal_parameters_left","dart.refactor.move_top_level_to_file"],"workDoneProgress":true},"workspace":{"workspaceFolders":{"chan…
[6:33:16 PM] [Analyzer] [Info] ==> Content-Length: 86
[6:33:16 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"initialized","params":{},"clientRequestTime":1699313596501}
[6:33:16 PM] [Analyzer] [Info] <== Content-Length: 180
Content-Type: application/vscode-jsonrpc; charset=utf-8
[6:33:16 PM] [Analyzer] [Info] <== {"id":1,"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///Users/myuser/Developer/diagram_playground","section":"dart"},{"section":"dart"}]}}
[6:33:16 PM] [Analyzer] [Info] ==> Content-Length: 7241
[6:33:16 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":1,"result":[{"additionalAnalyzerFileExtensions":[],"analysisExcludedFolders":[],"analyzeAngularTemplates":true,"analyzerAdditionalArgs":[],"analyzerVmAdditionalArgs":[],"analyzerDiagnosticsPort":null,"analyzerPath":null,"analyzerSshHost":null,"analyzerVmServicePort":null,"includeDependenciesInWorkspaceSymbols":true,"notifyAnalyzerErrors":true,"onlyAnalyzeProjectsWithOpenFiles":false,"showTodos":true,"useLegacyAnalyzerProtocol":false,"updateDevTools":true,"devToolsBrowse…
[6:33:16 PM] [Analyzer] [Info] <== Content-Length: 5158
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":2,"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"0","method":"textDocument/didOpen","registerOptions":{"documentSelector":[{"language":"dart","scheme":"file"},{"language":"yaml","pattern":"**/pubspec.yaml","scheme":"file"},{"language":"yaml","pattern":"**/analysis_options.yaml","scheme":"file"},{"language":"yaml","pattern":"**/lib/{fix_data.yaml,fix_data/**.yaml}","s…
[6:33:16 PM] [Analyzer] [Info] ==> Content-Length: 98
[6:33:16 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"$/setTrace","params":{"value":"off"},"clientRequestTime":1699313596615}
[6:33:16 PM] [Analyzer] [Info] ==> Content-Length: 98
[6:33:16 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"$/setTrace","params":{"value":"off"},"clientRequestTime":1699313596637}
[6:33:16 PM] [Analyzer] [Info] ==> Content-Length: 72
[6:33:16 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":2,"result":null,"clientRequestTime":1699313596643}
[6:33:16 PM] [Analyzer] [Info] ==> Content-Length: 1098
[6:33:16 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///Users/myuser/Developer/diagram_playground/lib/number_pool.dart","languageId":"dart","version":1,"text":"class NumberPool {\n  final int capacity;\n  final List<num> _values;\n\n  const NumberPool(this.capacity, {List<num>? values})\n      : _values = [...?values],\n        assert(() {\n          if (values != null && values.length > capacity) return false;\n          return true;\n        }(), 'The list …
[6:33:16 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
[6:33:16 PM] [Analyzer] [Info] ==> Content-Length: 98
[6:33:16 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"$/setTrace","params":{"value":"off"},"clientRequestTime":1699313596743}
[6:33:16 PM] [Analyzer] [Info] ==> Content-Length: 122
[6:33:16 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":null},"clientRequestTime":1699313596743}
[6:33:16 PM] [Analyzer] [Info] <== Content-Length: 180
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":3,"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///Users/myuser/Developer/diagram_playground","section":"dart"},{"section":"dart"}]}}
[6:33:17 PM] [Analyzer] [Info] <== Content-Length: 189
Content-Type: application/vscode-jsonrpc; charset=utf-8
[6:33:17 PM] [FlutterDaemon] [Info] <== [{"id":"1"}]
[6:33:17 PM] [FlutterDaemon] [Info] <== [{"id":"2","result":[{"id":"apple_ios_simulator","name":"iOS Simulator","category":"mobile","platformType":"ios"},{"id":"Pixel_3a_API_34_extension_level_7_arm64-v8a","name":"Pixel_3a_API_34_extension_level_7_arm64-v8a","category":"mobile","platformType":"android"}]}]
[6:33:17 PM] [Analyzer] [Info] ==> Content-Length: 202
[6:33:17 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":1,"method":"textDocument/documentColor","params":{"textDocument":{"uri":"file:///Users/myuser/Developer/diagram_playground/lib/number_pool.dart"}},"clientRequestTime":1699313597034}
[6:33:17 PM] [Analyzer] [Info] ==> Content-Length: 322
[6:33:17 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":2,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/myuser/Developer/diagram_playground/lib/number_pool.dart"},"range":{"start":{"line":24,"character":17},"end":{"line":24,"character":17}},"context":{"diagnostics":[],"triggerKind":2}},"clientRequestTime":1699313597034}
[6:33:17 PM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/myuser/Developer/diagram_playground/android/app/src/profile/AndroidManifest.xml"}}Content-Length: 186
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/myuser/Developer/diagram_playground/android/app/src/main/AndroidManifest.xml"}}
[6:33:17 PM] [Analyzer] [Info] ==> Content-Length: 7241
[6:33:17 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":3,"result":[{"additionalAnalyzerFileExtensions":[],"analysisExcludedFolders":[],"analyzeAngularTemplates":true,"analyzerAdditionalArgs":[],"analyzerVmAdditionalArgs":[],"analyzerDiagnosticsPort":null,"analyzerPath":null,"analyzerSshHost":null,"analyzerVmServicePort":null,"includeDependenciesInWorkspaceSymbols":true,"notifyAnalyzerErrors":true,"onlyAnalyzeProjectsWithOpenFiles":false,"showTodos":true,"useLegacyAnalyzerProtocol":false,"updateDevTools":true,"devToolsBrowse…
[6:33:17 PM] [Analyzer] [Info] ==> Content-Length: 273
[6:33:17 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":3,"method":"textDocument/inlayHint","params":{"textDocument":{"uri":"file:///Users/myuser/Developer/diagram_playground/lib/number_pool.dart"},"range":{"start":{"line":0,"character":0},"end":{"line":33,"character":1}}},"clientRequestTime":1699313597075}
[6:33:17 PM] [Analyzer] [Info] ==> Content-Length: 284
[6:33:17 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":4,"method":"textDocument/semanticTokens/range","params":{"textDocument":{"uri":"file:///Users/myuser/Developer/diagram_playground/lib/number_pool.dart"},"range":{"start":{"line":0,"character":0},"end":{"line":33,"character":1}}},"clientRequestTime":1699313597075}
[6:33:17 PM] [Analyzer] [Info] <== Content-Length: 187
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/myuser/Developer/diagram_playground/android/app/src/debug/AndroidManifest.xml"}}Content-Length: 167
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/myuser/Developer/diagram_playground/analys…
[6:33:17 PM] [Analyzer] [Info] ==> Content-Length: 201
[6:33:17 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":5,"method":"textDocument/foldingRange","params":{"textDocument":{"uri":"file:///Users/myuser/Developer/diagram_playground/lib/number_pool.dart"}},"clientRequestTime":1699313597142}
[6:33:17 PM] [Analyzer] [Info] <== {"id":1,"jsonrpc":"2.0","error":{"code":-32013,"data":"/Users/myuser/Developer/diagram_playground/lib/number_pool.dart","message":"Analysis failed for file"}}Content-Length: 157
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":3,"jsonrpc":"2.0","error":{"code":-32013,"data":"/Users/myuser/Developer/diagram_playground/lib/number_pool.dart","message":"Analysis failed for file"}}Content-Length: 180
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":5,"jsonrpc":"2.0…
[6:33:17 PM] [Analyzer] [Error] Unhandled exception:
Exception: Missing implementation of visitFunctionExpression
#0      ThrowingAstVisitor._throw (package:analyzer/dart/ast/visitor.dart:2859:5)
#1      ThrowingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:2528:58)
#2      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:8680:50)
#3      AstBinaryWriter._writeNode (package:analyzer/src/summary2/ast_binary_writer.dart:944:10)
#4      AstBinaryWriter.visitFunctionExpressionInvoc…
[6:33:17 PM] [Analyzer] [Info] ==> Content-Length: 72
[6:33:17 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":4,"result":null,"clientRequestTime":1699313597204}
[6:33:17 PM] [Analyzer] [Info] ==> Content-Length: 208
[6:33:17 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":6,"method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///Users/myuser/Developer/diagram_playground/lib/number_pool.dart"}},"clientRequestTime":1699313597486}
[6:33:17 PM] [Analyzer] [Info] Spawning /Users/myuser/fvm/versions/stable/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.76.1"]
[6:33:17 PM] [Analyzer] [Info]     PID: 22052
[6:33:17 PM] [Analyzer] [Info] ==> Content-Length: 6452
[6:33:17 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":21970,"clientInfo":{"name":"Visual Studio Code","version":"1.83.1"},"locale":"en","rootPath":"/Users/myuser/Developer/diagram_playground","rootUri":"file:///Users/myuser/Developer/diagram_playground","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"changeAnnotationSuppor…
```

when building it does errors, but the analyzer should not crash.
```
Error: Constant expression expected.
      : _values = [...?values],
                  ^
lib/main.dart:7:16:
Error: Not a constant expression.
        assert(() {
               ^^
```

**Comment by srawlins** [comment]
CC @kallentu

**Comment by kallentu** [comment]
As far as I can see, this is the same issue as https://github.com/dart-lang/sdk/issues/53075.
This has been fixed as of https://github.com/dart-lang/sdk/commit/ba1988e0d3acb340402a9d549db484eae933b65e.
