### ISSUE TITLE
Analyzer crashing with `library augment` statements

### ISSUE THREAD

**Issue by HrX03** [dart-lang/sdk#54019]
While trying augmentations, the analyzer seems to crash when adding the `library augment` statement to a file. To be specific, it seems to crash when writing the file uri in quotes or when opening the file/hovering the statement when in VSCode.

This is the error log:
```
[11:50:46 AM] [Analyzer] [Error] Unhandled exception:
Bad state: Expected existing element: root::package:augment_example/base.dart::@unit::package:augment_example/augment.dart
#0      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:231:7)
#1      LibraryContext.computeUnitElement (package:analyzer/src/dart/analysis/library_context.dart:100:34)
#2      AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1529:36)
<asynchron…
```

This is an example project with the minimum files to reproduce: [augment_example.zip](https://github.com/dart-lang/sdk/files/13327774/augment_example.zip)

Info returned from `dart info`:
```
#### General info

- Dart 3.3.0-120.0.dev (dev) (Fri Nov 10 12:02:15 2023 -0800) on "windows_x64"
- on windows / "Windows 10 Home" 10.0 (Build 25987)
- locale is it-IT

#### Project info

- sdk constraint: '^3.3.0-120.0.dev'
- dependencies:
- dev_dependencies: lints, test

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
```

**Comment by bwilkerson** [comment]
Thank you for reporting the exception, and especially for the reproduction case.

The analyzer's implementation of augmentation libraries is still under development, so exceptions like this are to be expected at this point. Still, it's useful to hear about them.

@scheglov

**Comment by scheglov** [comment]
OK, I can reproduce it.
```dart
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/src/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/src/dart/analysis/byte_store.dart';

void main() async {
  final byteStore = MemoryByteStore();

  {
    final collection = AnalysisContextCollectionImpl(
      includedPaths: [
        '/Users/scheglov/dart/20231112/augment_example',
      ],
      byteStore: byteStore,
    );

    final timer = Stopwatch()..start();
    for (final analysisContext in collection.contexts) {
      print(analysisContext.contextRoot.root.path);
      final analysisSession = analysisContext.currentSession;
      for (final path in analysisContext.contextRoot.analyzedFiles()) {
        if (path.endsWith('.dart')) {
          print('  $path');
          final unitResult = await analysisSession.getUnitElement(path);
          if (unitResult is UnitElementResult) {
            unitResult.element.classes;
            unitResult.element.mixins;
          }
        }
      }
    }
    print('[time: ${timer.elapsedMilliseconds} ms]');
  }
}
```
The reason is that `computeUnitElement` has `@unit` hardcoded.
https://github.com/dart-lang/sdk/blob/63118a139d460f3f13fa9cc5dc47c194faab92eb/pkg/analyzer/lib/src/dart/analysis/library_context.dart#L92-L102
But for augmentations we need `@augmentation`.

I will make fixes and write tests for various valid and invalid cases tomorrow.
