### ISSUE TITLE
Failures on [pkg/vm] Handle switch statements in unreachable code eliminator

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54029]
There are new test failures on [[tests][web-fixit] Fix date_time_extremes_test....Reland "[pkg/vm] Handle switch statements in unreachable code eliminator."](https://github.com/dart-lang/sdk/compare/262311772b2128ef778d0a1d189f0c6c51780132~...751a47f942268c3c61561f4ee77466f1e5066930).

The tests
```
language/nnbd/boolean_conversion/boolean_conversion_weak_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-weak-asserts-linux-release-x64
```

Log: https://dart-ci.appspot.com/log/vm-kernel-precomp-linux-release-x64/dartkp-weak-asserts-linux-release-x64/15831/language/nnbd/boolean_conversion/boolean_conversion_weak_test

```
exit code:
255

stderr:
Unhandled exception:
Expect.throws(AssertionError) fails: Did not throw
#0      Expect._fail (package:expect/expect.dart:721)
#1      Expect.throws (package:expect/expect.dart:629)
#2      Expect.throwsAssertionError (package:expect/expect.dart:638)
#3      check (file:///b/s/w/ir/tests/language/nnbd/boolean_conversion/boolean_conversion_lib1.dart:27)
#4      main (file:///b/s/w/ir/tests/language/nnbd/boolean_conversion/boolean_conversion_weak_test.dart:18)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

--- Re-run this test:
python3 tools/test.py -n dartkp-weak-asserts-linux-release-x64 language/nnbd/boolean_conversion/boolean_conversion_weak_test
```

Will bisect locally.

```
tools/bisect.dart \
-Dend=262311772b2128ef778d0a1d189f0c6c51780132 \
-Dstart=751a47f942268c3c61561f4ee77466f1e5066930 \
-Dtest_command="python3 tools/test.py --build -n dartkp-weak-asserts-linux-release-x64 language/nnbd/boolean_conversion/boolean_conversion_weak_test" \
-Dfailure_string="Expect.throws(AssertionError) fails: Did not throw"
```

**Comment by dcharkes** [comment]
It's likely that the following regressions were caused by the same change. These are also all related to bools and nulls in legacy mode.

There are new test failures on [[tests][web-fixit] Fix date_time_extremes_test....[cfe] Update ast-to-text](https://github.com/dart-lang/sdk/compare/446881d53fc7305c3518684af2d5ece950c901a2~...751a47f942268c3c61561f4ee77466f1e5066930).

The tests
```
co19/Language/Expressions/Logical_Boolean_Expressions/syntax_t01 RuntimeError (expected Pass)
co19_2/Language/Expressions/Logical_Boolean_Expressions/syntax_t01 RuntimeError (expected Pass)
language/regress/regress34147_test RuntimeError (expected Pass)
language_2/if_null/precedence_runtime_test RuntimeError (expected Pass)
language_2/regress/regress34147_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-linux-debug-x64
dartkp-linux-release-x64
dartkp-weak-asserts-linux-release-x64
```
