### ISSUE TITLE
[dart2wasm] Compiler crash when when compiling lazy statics that returns `externref`

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#54023]
I added a test for this in https://dart-review.googlesource.com/c/sdk/+/335447 which current fails with a compiler crash:

```
stdout:
Exception in FunctionInvocation at file:///usr/local/google/home/omersa/dart/sdk/sdk/tests/web/wasm/wasm_types_test.dart:33:2

stderr:
Unhandled exception:
   i32.const 4                                    i32
   i32.const 0                                    i32, i32
   global.get null                                i32, i32, ref struct
   global.get null                                i32, i32, ref struct, ref #Vtable-0-0
   global.get null                                i32, i32, ref struct, ref #Vtable-0-0, ref _FunctionType
   struct.new #Closure-0-0                        ref #Closure-0-0
   local.tee 0                                    ref #Closure-0-0
   struct.get #Closure-0-0 2                      ref struct
   local.get 0                                    ref struct, ref #Closure-0-0
   struct.get #Closure-0-0 3                      ref struct, ref #Vtable-0-0
   struct.get #Vtable-0-0 1                       ref struct, ref (ref struct) -> (ref null #Top)
   call_ref (ref struct) -> (ref null #Top)       ref null #Top

Expected [externref], but stack contained [ref null #Top]
#0      InstructionsBuilder._reportError (package:wasm_builder/src/builder/instructions.dart:235)
#1      InstructionsBuilder._checkStackTypes (package:wasm_builder/src/builder/instructions.dart:267)
#2      InstructionsBuilder._verifyTypesFun (package:wasm_builder/src/builder/instructions.dart:292)
#3      InstructionsBuilder._verifyTypes (package:wasm_builder/src/builder/instructions.dart:274)
#4      InstructionsBuilder._verifyCast (package:wasm_builder/src/builder/instructions.dart:1138)
#5      InstructionsBuilder.ref_cast (package:wasm_builder/src/builder/instructions.dart:1159)
#6      Translator.convertType (package:dart2wasm/translator.dart:842)
#7      CodeGenerator.wrap (package:dart2wasm/code_generator.dart:879)
#8      CodeGenerator.generateStaticFieldInitializer (package:dart2wasm/code_generator.dart:265)
#9      CodeGenerator.generate (package:dart2wasm/code_generator.dart:224)
#10     Translator.translate (package:dart2wasm/translator.dart:351)
#11     compileToModule (package:dart2wasm/compile.dart:151)
<asynchronous suspension>
#12     main (package:dart2wasm/dart2wasm.dart:141)
<asynchronous suspension>
#13     main (file:///usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/dart2wasm.dart:7)
<asynchronous suspension>
```

This is blocking allocating text decoders lazily in `dart:convert`:
```dart
class Utf8Decoder {
  ...

  // `TextDecoder` is not defined on some browsers and on the standalone d8 and
  // jsshell engines. Use a lazy initializer to do feature detection once.
  static final WasmExternRef? _decoder = () {
    try {
      return js
          .JS<WasmExternRef?>('() => new TextDecoder("utf-8", {fatal: true})');
    } catch (e) {}
    return WasmExternRef.nullRef;
  }();

  ...
}
```

**Comment by askeksa** [comment]
The raw Wasm types (such as `WasmExternRef?` here) don't represent Dart values (they don't have boxed representations), which means that can't be mixed with Dart types in places where they might be assigned to e.g. `Object?` or boxed for other reasons.

The desugaring transformation of global initializers seems to produce such a situation, so we can't use raw Wasm types as the types of global variables. Furthermore, we always box parameters and returns of function objects, so we can't use raw Wasm types here either.

The appropriate solution here is to use a JS type (e.g. `JSAny`) instead of `WasmExternRef?`. That has exactly the purpose of boxing a JS value as a Dart value.

**Comment by osa1** [comment]
Thanks, closing this as non-issue.

Updated code to use `JSAny` is here: https://dart-review.googlesource.com/c/sdk/+/336020.
