### ISSUE TITLE
[CFE] incremental compiler crashes when trying to debug code

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#54037]
**Repro**

- create a dart project with any code (I used `https://github.com/dart-lang/webdev/tree/master/fixtures/_webdevSoundSmoke`)
- run `code .`
- put a breakpoint somewhere (on the line `// Breakpoint: printCounter` in my case)
- start debugging

**Expected**

Starts a browser, pauses on the breakpoint, expression evaluation works

**Actual**

Crash below

This happens for me on the current dev channel (but works fine on `be` or `stable` channels):

```
Internal problem: Compiler cannot run without a compiler context.
Tip: Are calls to the compiler wrapped in CompilerContext.runInContext?

#0      CompilerContext.current (package:front_end/src/fasta/compiler_context.dart:107:7)
#1      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:243:23)
#2      ProcessedOptions._readAsBytes (package:front_end/src/base/processed_options.dart:797:7)
<asynchronous suspension>
#3      ProcessedOptions.loadSdkSummaryBytes (package:front_end/src/base/processed_options.dart:151:26)
<asynchronous suspension>
#4      ProcessedOptions.loadSdkSummary (package:front_end/src/base/processed_options.dart:419:26)
<asynchronous suspension>
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:115:27)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:310:21)
<asynchronous suspension>
#7      _CompilerWorker.performRequest (package:dev_compiler/ddc.dart:72:18)
```

**Comment by annagrin** [comment]
Looks like this was caused by something in my environment, cannot repro anymore!
