### ISSUE TITLE
co19/LibTest/typed_data/Float32x4List/setAll_A04_t01 failing on web

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#54078]
[co19/LibTest/typed_data/Float32x4List/setAll_A04_t01](https://github.com/dart-lang/co19/blob/master/LibTest/typed_data/Float32x4List/setAll_A04_t01.dart) fails on dart2js and ddc, but works well on VM
```
/======================================================================================================\
| co19/LibTest/typed_data/Float32x4List/setAll_A04_t01 is new and failed (RuntimeError, expected Pass) |
\======================================================================================================/

--- Command "dart2js" (took 02.000595s):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome out/ReleaseX64/dart-sdk/bin/dart compile js -Dtest_runner.configuration=dart2js-linux-chrome --sound-null-safety --test-mode --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/co19/src/LibTest/typed_data/Float32x4List/setAll_A04_t01.dart --sound-null-safety --out=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-linux-chrome/tests_co19_src_LibTest_typed_data_Float32x4List_setAll_A04_t01/setAll_A04_t01.js

exit code:
0

stdout:
Compiled 10,053,657 input bytes (5,086,726 characters source) to 142,103 characters JavaScript in 2.55 seconds using 466.926 MB of memory

--- Command "chrome" (took 125ms):
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:36929/root_build/generated_tests/dart2js-linux-chrome/tests_co19_src_LibTest_typed_data_Float32x4List_setAll_A04_t01/test.html?crossOriginPort=40845

Runtime error:
Expect.equals(expected: <4.099999904632568>, actual: <6.099999904632568>) fails.
Expect.equals(expected: <4.099999904632568>, actual: <6.099999904632568>) fails.
    at Object.wrapException (http://127.0.0.1:36929/root_build/generated_compilations/dart2js-linux-chrome/tests_co19_src_LibTest_typed_data_Float32x4List_setAll_A04_t01/setAll_A04_t01.js:541:43)
    at Object._fail (http://127.0.0.1:36929/root_build/generated_compilations/dart2js-linux-chrome/tests_co19_src_LibTest_typed_data_Float32x4List_setAll_A04_t01/setAll_A04_t01.js:2830:15)
    at Object.Expect_equals (http://127.0.0.1:36929/root_build/generated_compilations/dart2js-linux-chrome/tests_co19_src_LibTest_typed_data_Float32x4List_setAll_A04_t01/setAll_A04_t01.js:2839:11)
    at Object.listEquals (http://127.0.0.1:36929/root_build/generated_compilations/dart2js-linux-chrome/tests_co19_src_LibTest_typed_data_Float32x4List_setAll_A04_t01/setAll_A04_t01.js:2851:11)
    at main (http://127.0.0.1:36929/root_build/generated_compilations/dart2js-linux-chrome/tests_co19_src_LibTest_typed_data_Float32x4List_setAll_A04_t01/setAll_A04_t01.js:2870:9)
    at dartMainRunner (http://127.0.0.1:36929/root_dart/pkg/test_runner/lib/src/test_controller.js:319:5)
    at http://127.0.0.1:36929/root_build/generated_compilations/dart2js-linux-chrome/tests_co19_src_LibTest_typed_data_Float32x4List_setAll_A04_t01/setAll_A04_t01.js:3808:7
    at http://127.0.0.1:36929/root_build/generated_compilations/dart2js-linux-chrome/tests_co19_src_LibTest_typed_data_Float32x4List_setAll_A04_t01/setAll_A04_t01.js:3793:7
    at dartProgram (http://127.0.0.1:36929/root_build/generated_compilations/dart2js-linux-chrome/tests_co19_src_LibTest_typed_data_Float32x4List_setAll_A04_t01/setAll_A04_t01.js:3804:5)
    at http://127.0.0.1:36929/root_build/generated_compilations/dart2js-linux-chrome/tests_co19_src_LibTest_typed_data_Float32x4List_setAll_A04_t01/setAll_A04_t01.js:3812:3

Deobfuscated error and stack:
Expect.equals(expected: <4.099999904632568>, actual: <6.099999904632568>) fails.
Expect.equals(expected: <4.099999904632568>, actual: <6.099999904632568>) fails.
    at wrapException                           org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 1196:37
    at _fail                                   ../../../../../tests/co19/src/Utils/expect.dart 18:5
    at Expect.equals                           ../../../../../tests/co19/src/Utils/expect_common.dart 15:7
    at listEquals                              ../../../../../tests/co19/src/LibTest/typed_data/Float32x4List/setAll_A04_t01.dart 22:12
    at main                                    ../../../../../tests/co19/src/LibTest/typed_data/Float32x4List/setAll_A04_t01.dart 42:3
    at dartMainRunner                          pkg/test_runner/lib/src/test_controller.js 319:5
    at getIsolateAffinityTag(inlined)          org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2826:31
    at JS_INTEROP_INTERCEPTOR_TAG(inlined)     org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 197:42
    at lookupInterceptorByConstructor(inlined) org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 203:37
    at getIsolateAffinityTag                   org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 157:21
    at getIsolateAffinityTag(inlined)          org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2826:31
    at JS_INTEROP_INTERCEPTOR_TAG(inlined)     org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 197:42
    at lookupInterceptorByConstructor(inlined) org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 203:37
    at getIsolateAffinityTag                   org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 157:21
    at getIsolateAffinityTag(inlined)          org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2826:31
    at JS_INTEROP_INTERCEPTOR_TAG(inlined)     org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 197:42
    at lookupInterceptorByConstructor(inlined) org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 203:37
    at getIsolateAffinityTag                   org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 157:21
    at getIsolateAffinityTag(inlined)          org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 2826:31
    at JS_INTEROP_INTERCEPTOR_TAG(inlined)     org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 197:42
    at lookupInterceptorByConstructor(inlined) org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 203:37
    at getIsolateAffinityTag                   org-dartlang-sdk:///lib/_internal/js_runtime/lib/interceptors.dart 157:21


exit code:
0

--- To debug locally, run:
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/pkg/test_runner/bin/http_server.dart -p 36929 -c 40845 --network 127.0.0.1 --build-directory=/b/s/w/ir/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/.dart_tool/package_config.json

--- Re-run this test:
python3 tools/test.py -n dart2js-linux-chrome co19/LibTest/typed_data/Float32x4List/setAll_A04_t01
```

**Comment by fishythefish** [comment]
cc @rakudrama

**Comment by rakudrama** [comment]
The inherited implementation of `setAll` (from from `ListBase`), calls `setRange`, also from `ListBase`.
The inherited version of `setRange` does not understand that the 'two' lists are views of a common buffer.

The typed_data classes that are implemented on the web as wrappers over more basic typed data (`Float32x4List`, `Float64x2List`, `Int43x4List`) should implement their `setRange` in terms of the wrapped `_storage`'s `setRange`.
As to priority, I generally expect these classes are not used much on the web as they are quite inefficient.
