### ISSUE TITLE
Analyzer crash when pasting TS code in Dart files

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#54099]
Hello!

To reproduce the issue, paste the following code in a Dart file:

```
/**
   * A notification that can be included in {@link Message}.
   */
export interface Notification {
  /**
   * The title of the notification.
   */
  title?: string;
  /**
   * The notification body
   */
  body?: string;
  /**
   * URL of an image to be displayed in the notification.
   */
  imageUrl?: string;
}
```

This causes analyzer to crash with the following error:

```
[15:27:27] [Analyzer] [Error] Unhandled exception:
Null check operator used on a null value
#0      MetadataResolver.visitExportDirective (package:analyzer/src/summary2/metadata_resolver.dart:103:17)
#1      ExportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:6027:50)
#2      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:13033:20)
#3      MetadataResolver.visitCompilationUnit (package:analyzer/src/summary2/metadata_resolver.dart:63:21)
#4      CompilationUnitImpl.accept (package:analyzer/src/dart…
```

Dart version:

Dart SDK version: 3.3.0-107.0.dev (dev) (Wed Nov 8 04:03:03 2023 -0800) on "macos_arm64"

**Comment by scheglov** [comment]
Cannot reproduce.
The unit test below report a few errors, but does not crash.

```dart
  solo_test_X() async {
    await assertNoErrorsInCode(r'''
/**
   * A notification that can be included in {@link Message}.
   */
export interface Notification {
  /**
   * The title of the notification.
   */
  title?: string;
  /**
   * The notification body
   */
  body?: string;
  /**
   * URL of an image to be displayed in the notification.
   */
  imageUrl?: string;
}
''');
  }
```
