### ISSUE TITLE
Future already completed in analysis_server/src/server/dev_server.dart

### ISSUE THREAD

**Issue by sortie** [dart-lang/sdk#54161]
I saw the macOS arm64 build flake due to a race condition in `package:analysis_server/src/server/dev_server.dart`:

```
 FAILED: gen/analysis_server.dart.snapshot 
 python3 ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=../../.dart_tool/package_config.json --snapshot=gen/analysis_server.dart.snapshot --snapshot-depfile=gen/analysis_server.dart.snapshot.d --snapshot-kind=app-jit --dfe=../../utils/analysis_server/NEVER_LOADED gen/utils/analysis_server/analysis_server.dart.dill --sdk=/Volumes/Work/s/w/ir/x/w/sdk/sdk/ --train-using=/Volumes/Work/s/w/ir/x/w/sdk/pkg/compiler/lib
 Command failed: /Volumes/Work/s/w/ir/x/w/sdk/xcodebuild/ReleaseARM64/dart --deterministic --packages=../../.dart_tool/package_config.json --snapshot=gen/analysis_server.dart.snapshot --snapshot-depfile=gen/analysis_server.dart.snapshot.d --snapshot-kind=app-jit --dfe=../../utils/analysis_server/NEVER_LOADED gen/utils/analysis_server/analysis_server.dart.dill --sdk=/Volumes/Work/s/w/ir/x/w/sdk/sdk/ --train-using=/Volumes/Work/s/w/ir/x/w/sdk/pkg/compiler/lib
 output: Analyzing with an empty driver cache:
 Analyzing /Volumes/Work/s/w/ir/x/w/sdk/pkg/compiler/lib...
 Completed in 34.3s.
 Analyzing with a populated driver cache:
 Analyzing /Volumes/Work/s/w/ir/x/w/sdk/pkg/compiler/lib...
 Completed in 0.0s.
 Completed in 0.0s.
 Unhandled exception:
 Bad state: Future already completed
 #0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
 #1      DevAnalysisServer.processDirectories.handleStatusNotification (package:analysis_server/src/server/dev_server.dart:62:24)
 #2      DevAnalysisServer.processDirectories.<anonymous closure> (package:analysis_server/src/server/dev_server.dart:124:9)
 #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
 #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
 #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
 #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
 #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
 #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
 #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
 #10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
 #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
 #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
 #13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

https://logs.chromium.org/logs/dart-internal/buildbucket/cr-buildbucket/8763275016516170017/+/u/build_dart/stdout

This happened on `3.3.0-167.0.dev` aka 8eaeb87500b2ae9a127be915b073cf0a3de44c51 on main.

**Comment by parlough** [comment]
I'm not able to build the SDK locally because of this. I'm not sure if it's the right or best fix, but https://dart-review.googlesource.com/c/sdk/+/337882 worked for me.
