### ISSUE TITLE
When `--enable-experiment=native-assets`, `dart test` cannot automatically do `pub get`

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#54160]
Hi thanks for the language! When a package has not run `pub get` at all, we can still run `dart test` because it is smart enough to auto do `pub get`.

However, if we do `--enable-experiment=native-assets`, this no longer holds, and the errors below happen.

As for the fix, I guess we should do pub get before reading the native_assets.yaml.

Experiments:

```
dart create bug && cd bug

(base) ➜  bug rm -rf .dart_tool 
(base) ➜  bug dart test
Resolving dependencies in /Users/tom/temp/bug... 
Got dependencies in /Users/tom/temp/bug.
Building package executable... (7.0s)
Built test:test.
00:01 +1: All tests passed!             
                                                        
(base) ➜  bug rm -rf .dart_tool 
(base) ➜  bug dart --enable-experiment=native-assets  test
PathNotFoundException: Cannot open file, path = '/Users/tom/temp/bug/.dart_tool/native_assets.yaml' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
<asynchronous suspension>
#2      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634:34)
<asynchronous suspension>
#3      compileNativeAssetsJitYamlFile (package:dartdev/src/native_assets.dart:60:3)
<asynchronous suspension>
#4      TestCommand.run (package:dartdev/src/commands/test.dart:55:11)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      DartdevRunner.runCommand (package:dartdev/dartdev.dart:240:18)
<asynchronous suspension>
#7      runDartdev (package:dartdev/dartdev.dart:59:16)
<asynchronous suspension>
#8      main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

**Comment by devoncarew** [comment]
cc @dcharkes and @bkonyi ; perhaps the native assets check should be run after the call to pub get?
