### ISSUE TITLE
[parser] "No name provided" crash

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#54178]
Consider:

```dart
void main() {
  final b = (final g, final ) = 55;
}
```

That program appears to crash the analyzer and compiler:

```
Dart SDK version: 3.2.0-edge.88b07ba64e07fb0eef9c777769917c65fdf1832e (be) (Tue Sep 19 21:57:39 2023 +0000) on "macos_arm64"

> dart foo.dart

Crash when compiling file:///Users/modulovalue/Downloads/foo.dart at character offset 10:
No name provided

#0      _withArgumentsPatternAssignmentDeclaresVariable (package:_fe_analyzer_shared/src/messages/codes_generated.dart:11763:21)
#1      Parser.parseVariablePattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9768:33)
#2      Parser.parsePrimaryPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9576:16)
#3      Parser.parsePattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9451:13)
#4      Parser.parseParenthesizedPatternOrRecordPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:10002:15)
#5      Parser.parsePrimaryPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9605:15)
#6      Parser.parsePattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9451:13)
#7      Parser.parsePatternAssignment (package:_fe_analyzer_shared/src/parser/parser_impl.dart:10185:13)
#8      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5720:17)
#9      Parser.parseVariableInitializerOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3879:15)
#10     Parser.parseOptionallyInitializedIdentifier (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8133:13)
#11     Parser.parseVariablesDeclarationRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8114:13)
#12     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8107:11)
#13     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5507:16)
#14     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5476:20)
#15     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5381:15)
#16     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1227:14)
#17     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:385:5)
#18     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3809:14)
#19     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3553:14)
#20     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:616:14)
#21     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:411:15)
#22     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1244:12)
<asynchronous suspension>
#23     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:666:7)
<asynchronous suspension>
#24     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:593:7)
<asynchronous suspension>
#25     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#26     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:574:12)
<asynchronous suspension>
#27     _buildInternal (package:front_end/src/kernel_generator_impl.dart:210:19)
<asynchronous suspension>
#28     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#29     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:49:12)
<asynchronous suspension>
#30     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139:3)
<asynchronous suspension>
#31     generateKernel (package:front_end/src/kernel_generator_impl.dart:48:10)
<asynchronous suspension>
#32     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#33     SingleShotCompilerWrapper.compileInternal (file:///opt/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:414:11)
<asynchronous suspension>
#34     Compiler.compile.<anonymous closure> (file:///opt/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:220:45)
<asynchronous suspension>
#35     _processLoadRequest (file:///opt/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:897:37)
<asynchronous suspension>

> dart analyze foo.dart

No name provided
#0      _withArgumentsPatternAssignmentDeclaresVariable (package:_fe_analyzer_shared/src/messages/codes_generated.dart:11763:21)
#1      Parser.parseVariablePattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9768:33)
#2      Parser.parsePrimaryPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9576:16)
#3      Parser.parsePattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9451:13)
#4      Parser.parseParenthesizedPatternOrRecordPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:10002:15)
#5      Parser.parsePrimaryPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9605:15)
#6      Parser.parsePattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9451:13)
#7      Parser.parsePatternAssignment (package:_fe_analyzer_shared/src/parser/parser_impl.dart:10185:13)
#8      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5720:17)
#9      Parser.parseVariableInitializerOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3879:15)
#10     Parser.parseOptionallyInitializedIdentifier (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8133:13)
#11     Parser.parseVariablesDeclarationRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8114:13)
#12     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8107:11)
#13     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5507:16)
#14     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5476:20)
#15     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5381:15)
#16     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3806:13)
#17     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3553:14)
#18     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:616:14)
#19     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:411:15)
#20     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:97:32)
#21     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:93:12)
#22     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:725:23)
#23     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:488:14)
#24     FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:671:16)
#25     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:526:27)
#26     FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1456:10)
#27     FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1286:14)
#28     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1270:12)
#29     AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1653:16)
#30     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1056:5)
#31     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2262:24)
<asynchronous suspension>


#0      FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:490:7)
#1      FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:671:16)
#2      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:526:27)
#3      FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1456:10)
#4      FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1286:14)
#5      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1270:12)
#6      AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1653:16)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1056:5)
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2262:24)
<asynchronous suspension>
Bad state: The analysis server crashed unexpectedly
```

**Comment by stereotype441** [comment]
I'm looking into this now.

**Comment by stereotype441** [comment]
Fix is out for review: https://dart-review.googlesource.com/c/sdk/+/339661
