### ISSUE TITLE
Unaligned load in vm/cc/SerializeString

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#54170]
There are new test failures on [analyzer: Remove pre-NNBD strong_mode and non_error tests...[gardening] Remove gc tests, clean up failing tests in stress test suite.](https://github.com/dart-lang/sdk/compare/4418b626944232a3bcc4418be24275547340ca0a~...2bc46e980767b3d6862363688c0333288bc6c63c).

The tests
```
vm/cc/SerializeString Crash (expected Pass)
```
are failing on configurations
```
vm-ubsan-linux-release-x64
```

Log:
```
--- Command "run_vm_unittest" (took 01.000175s):
DART_CONFIGURATION=ReleaseUBSANX64 out/ReleaseUBSANX64/run_vm_tests --dfe=/b/s/w/ir/out/ReleaseUBSANX64/gen/kernel-service.dart.snapshot --sound-null-safety --ignore-unrecognized-flags SerializeString

exit code:
-6

stdout:
Running test: SerializeString

stderr:
../../runtime/vm/object.cc:24827:32: runtime error: load of misaligned address 0x55de48614977 for type 'const uint16_t *' (aka 'const unsigned short *'), which requires 2 byte alignment
0x55de48614977: note: pointer points here
 3c 81 81 86 01  00 7f 00 80 00 ff 07 00  08 ff ff 80 80 80 8a 00  00 00 00 00 00 00 00 00  01 00 00
             ^ 
    #0 0x55de45fa77ff in dart::TwoByteString::New(unsigned short const*, long, dart::Heap::Space) /b/f/w/out/ReleaseUBSANX64/../../runtime/vm/object.cc:24827:5
    #1 0x55de45ef641c in dart::TwoByteStringMessageDeserializationCluster::ReadNodes(dart::MessageDeserializer*) /b/f/w/out/ReleaseUBSANX64/../../runtime/vm/message_snapshot.cc:2648:26
    #2 0x55de45eda060 in dart::MessageDeserializationCluster::ReadNodesWrapped(dart::MessageDeserializer*) /b/f/w/out/ReleaseUBSANX64/../../runtime/vm/message_snapshot.cc:459:9
    #3 0x55de45eda060 in dart::MessageDeserializer::Deserialize() /b/f/w/out/ReleaseUBSANX64/../../runtime/vm/message_snapshot.cc:3363:20
    #4 0x55de45edba0f in dart::ReadMessage(dart::Thread*, dart::Message*) /b/f/w/out/ReleaseUBSANX64/../../runtime/vm/message_snapshot.cc:3494:27
    #5 0x55de4589ed93 in dart::TestString(char const*) /b/f/w/out/ReleaseUBSANX64/../../runtime/vm/snapshot_test.cc:384:21
    #6 0x55de45885bd0 in dart::Dart_TestHelperSerializeString(dart::Thread*) /b/f/w/out/ReleaseUBSANX64/../../runtime/vm/snapshot_test.cc:406:3
    #7 0x55de45885bd0 in dart::Dart_TestSerializeString() /b/f/w/out/ReleaseUBSANX64/../../runtime/vm/snapshot_test.cc:395:1
    #8 0x55de4568d6c6 in dart::TestCase::Run() /b/f/w/out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:53:3
    #9 0x55de4568d862 in dart::TestCaseBase::RunTest() /b/f/w/out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:65:11
    #10 0x55de458d3b6c in dart::TestCaseBase::RunAll() /b/f/w/out/ReleaseUBSANX64/../../runtime/vm/unit_test.cc:86:13
    #11 0x55de4568e251 in dart::Main(int, char const**) /b/f/w/out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:414:3
    #12 0x55de4568dde0 in main /b/f/w/out/ReleaseUBSANX64/../../runtime/bin/run_vm_tests.cc:445:29
    #13 0x7f765dede082 in __libc_start_main /build/glibc-BHL3KM/glibc-2.31/csu/../csu/libc-start.c:308:16
    #14 0x55de456741a8 in _start (/b/s/w/ir/out/ReleaseUBSANX64/run_vm_tests+0x28ba1a8)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../runtime/vm/object.cc:24827:32 in

--- Re-run this test:
python3 tools/test.py -n vm-ubsan-linux-release-x64 vm/cc/SerializeString
```

**Comment by rmacnak-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/338644
