### ISSUE TITLE
analysis server crashes while parsing code

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#54189]
This sample code:

```
void main() {
  List<int> c = [var j] = [var j] = [var j] = [12];
  print(c);
  print(j);
  final a = (final f) => 33;
  final b = (final g, final ) = 55;
  final c = (final h) async => 77;
  final d = throw 99;
}
```

will crash the analysis server at head. See the original bug report at https://github.com/dart-lang/dart-pad/issues/2731.

```
No name provided
#0      _withArgumentsPatternAssignmentDeclaresVariable (package:_fe_analyzer_shared/src/messages/codes_generated.dart:11992:21)
#1      Parser.parseVariablePattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9768:33)
#2      Parser.parsePrimaryPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9576:16)
#3      Parser.parsePattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9451:13)
#4      Parser.parseParenthesizedPatternOrRecordPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:10002:15)
#5      Parser.parsePrimaryPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9605:15)
#6      Parser.parsePattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9451:13)
#7      Parser.parsePatternAssignment (package:_fe_analyzer_shared/src/parser/parser_impl.dart:10185:13)
#8      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5720:17)
#9      Parser.parseVariableInitializerOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3879:15)
#10     Parser.parseOptionallyInitializedIdentifier (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8133:13)
...
```

**Comment by devoncarew** [comment]
cc @scheglov

**Comment by parlough** [comment]
This is due to the empty synthetic token introduced in place of the empty variable declaration in the record.

Duplicate of https://github.com/dart-lang/sdk/issues/54178

**Comment by scheglov** [comment]
Cannot reproduce, does not crash.

**Comment by srawlins** [comment]
Marking P3 for the remaining issue Devon notes above:

> Even assuming we resolve https://github.com/dart-lang/sdk/issues/54178, I think it's worth hardening the analysis server so that future parse exceptions can't crash the analysis server process.
