### ISSUE TITLE
[dartpad] Compiler crashs

### ISSUE THREAD

**Issue by woprandi** [dart-lang/sdk#54236]
Try to run this block on [dartpad.dev](https://dartpad.dev)

```dart
void main() {
  var a = 5;
  
  var b = switch (a) {
      1 => 2
      > 1 => 1
      < 1 => 0
  };
  
  print(b);
}
```

And the message is : 

```
Error compiling to JavaScript:
compile: lib/main.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.2.1), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Crash when compiling file:///tmp/dartpadOOUTQT/lib/main.dart at character offset 10:
Null check operator used on a null value

#0      Parser.findNextCommaOrSemicolon (package:_fe_analyzer_shared/src/parser/parser_impl.dart:10315:31)
#1      Parser.parseSwitchExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:10279:21)
#2      Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6529:16)
#3      Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6341:12)
#4      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5784:13)
#5      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5724:15)
#6      Parser.parseVariableInitializerOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3879:15)
#7      Parser.parseOptionallyInitializedIdentifier (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8133:13)
#8      Parser.parseVariablesDeclarationRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8114:13)
#9      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8107:11)
#10     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5507:16)
#11     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5476:20)
#12     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5381:15)
#13     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1267:14)
#14     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:399:5)
#15     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3809:14)
#16     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3553:14)
#17     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:616:14)
#18     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:411:15)
#19     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1244:12)
<asynchronous suspension>
#20     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:666:7)
<asynchronous suspension>
#21     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:593:7)
<asynchronous suspension>
#22     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#23     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:574:12)
<asynchronous suspension>
#24     _buildInternal (package:front_end/src/kernel_generator_impl.dart:210:19)
<asynchronous suspension>
#25     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#26     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:198:37)
<asynchronous suspension>
#27     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139:3)
<asynchronous suspension>
#28     compile (package:front_end/src/api_unstable/dart2js.dart:196:36)
<asynchronous suspension>
#29     _loadFromSource (package:compiler/src/phase/load_kernel.dart:304:29)
<asynchronous suspension>
#30     run (package:compiler/src/phase/load_kernel.dart:414:36)
<asynchronous suspension>
#31     Compiler.loadKernel (package:compiler/src/compiler.dart:395:9)
<asynchronous suspension>
#32     Compiler.produceKernel (package:compiler/src/compiler.dart:402:36)
<asynchronous suspension>
#33     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:718:20)
<asynchronous suspension>
#34     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:318:7)
<asynchronous suspension>
#35     Compiler.runInternal (package:compiler/src/compiler.dart:317:5)
<asynchronous suspension>
#36     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:238:11)
<asynchronous suspension>
#37     compile.<anonymous closure> (package:compiler/compiler_api.dart:252:30)
<asynchronous suspension>
#38     compile.compilationDone (package:compiler/src/dart2js.dart:745:3)
<asynchronous suspension>
#39     main (package:compiler/src/dart2js.dart:1265:3)
<asynchronous suspension>
```

**Comment by lrhn** [comment]
Crashing on a missing comma between expression switch cases.
