### ISSUE TITLE
[vm][aot] co19/LibTest/typed_data/Float32List/setRange_A06_t01 failing

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54304]
We got some new co19 tests with typed data. I presume as a result of our request a couple of weeks ago.

The test is failing on all tested AOT configurations. (But succeeding on JIT, and non-VM configurations.)

So I presume we misoptimize in the VM in AOT.

@sstrickl Could you please take a look?

There are new test failures on [[co19] Roll co19 to ea5e476b3af94f74f6996e4b4319bf03f9248c1c](https://github.com/dart-lang/sdk/commit/8763ece3bec826247d5d880c39e9285a28ede6a5).

The tests
```
co19/LibTest/typed_data/Float32List/setRange_A06_t01 RuntimeError (expected Pass)
co19/LibTest/typed_data/Float64List/setRange_A06_t01 RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-linux-release-x64
vm-aot-win-release-x64
```

```
--- Command "vm_compile_to_kernel" (took 03.000537s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_co19_src_LibTest_typed_data_Float32List_setRange_A06_t01/out.dill /b/s/w/ir/tests/co19/src/LibTest/typed_data/Float32List/setRange_A06_t01.dart -Dtest_runner.configuration=vm-aot-linux-release-x64 --packages=/b/s/w/ir/.dart_tool/package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 04.000720s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_co19_src_LibTest_typed_data_Float32List_setRange_A06_t01/out.S --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_co19_src_LibTest_typed_data_Float32List_setRange_A06_t01/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 45ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_co19_src_LibTest_typed_data_Float32List_setRange_A06_t01/out.dill

exit code:
0

--- Command "assemble" (took 01.000324s):
DART_CONFIGURATION=ReleaseX64 gcc -Wl,--no-undefined -shared -o /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_co19_src_LibTest_typed_data_Float32List_setRange_A06_t01/out.aotsnapshot /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_co19_src_LibTest_typed_data_Float32List_setRange_A06_t01/out.S

exit code:
0

--- Command "remove_assembly" (took 54ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_co19_src_LibTest_typed_data_Float32List_setRange_A06_t01/out.S

exit code:
0

--- Command "vm" (took 79ms):
DART_CONFIGURATION=ReleaseX64 TEST_COMPILATION_DIR=/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_co19_src_LibTest_typed_data_Float32List_setRange_A06_t01 out/ReleaseX64/dart_precompiled_runtime --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_co19_src_LibTest_typed_data_Float32List_setRange_A06_t01/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.throws() fails
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:18)
#1      Expect.throws (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:193)
#2      main (file:///b/s/w/ir/tests/co19/src/LibTest/typed_data/Float32List/setRange_A06_t01.dart:23)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

--- Re-run this test:
python3 tools/test.py -n vm-aot-linux-release-x64 co19/LibTest/typed_data/Float32List/setRange_A06_t01
```

**Comment by alexmarkov** [comment]
The tests `co19/LibTest/typed_data/Float32List/setRange_A06_t01` and `co19/LibTest/typed_data/Float64List/setRange_A06_t01` are currently passing on all VM configurations (including all AOT configurations).
