### ISSUE TITLE
Analyzer not reporting compile-time error when removing generic type definition from class

### ISSUE THREAD

**Issue by fgaudo** [dart-lang/sdk#54388]
I'm not sure if the following issue is similar to #54011, but i'll report it anyway.

Given the following dart file content:

```dart
sealed class Option<A> {}

final class None<A> implements Option<A> {
  const None();
}

final class Some<A> implements Option<A> {
  const Some(this.value);

  final A value;
}

final class _EvalException implements Exception {
  const _EvalException();
}

Option<A> doOption<A>(
  A Function(
    B Function<B>(Option<B>),
  ) eval,
) {
  try {
    return Some(
      eval(
        <B>(option) => switch (option) {
          None() => throw _EvalException(),
          Some(value: final value) => value
        },
      ),
    );
  } on _EvalException {
    return None();
  }
}

void main() {
  final option = doOption((eval) {
    final five = eval(Some(5));

    print(five);

    return five;
  });
}
```

This code runs fine and the analyzer does not return any issues. 

But if i now introduce a compile-time error by removing the generic type to `None` like this:
```dart
final class None implements Option<A> {
  const None();
}
```

and then try to run the code, i get:
```console
$ dart lib/bug.dart 
lib/bug.dart:3:36: Error: Type 'A' not found.
final class None implements Option<A> {
                                   ^
```

But the analyzer does not report the error at all.
```console
$ dart analyze lib/bug.dart 
Analyzing bug.dart...                  0.6s
No issues found!
```

If i remove the `doOption` and the `main` functions, then the analyzer starts working again and reports the error.
So apparently the `doOption` is giving the analyzer a hard time when introducing that specific compile-time error.

This strangely seems to happen only if i remove the generic type from `None`. If i do the same on `Some`, the analyzer works and reports the error.

This problem also makes the vscode dart extension stop giving hints while returning the following error.
```console
2023-12-16 21:10:10.334 [error] Error: Analysis failed for file
	at handleResponse (/home/gaudo/.vscode/extensions/dart-code.dart-code-3.78.2/out/dist/extension.js:30278:48)
	at handleMessage (/home/gaudo/.vscode/extensions/dart-code.dart-code-3.78.2/out/dist/extension.js:30058:13)
	at processMessageQueue (/home/gaudo/.vscode/extensions/dart-code.dart-code-3.78.2/out/dist/extension.js:30075:17)
	at Immediate.<anonymous> (/home/gaudo/.vscode/extensions/dart-code.dart-code-3.78.2/out/dist/extension.js:30047:13)
	at process.processImmediate (node:internal/timers:476:21)
```

```console
$ dart info

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "linux_x64"
- on linux / Linux 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12)
- locale is en_GB.UTF-8

#### Project info

- sdk constraint: '^3.2.2'
- dependencies: rxdart
- dev_dependencies: coverage, lints, test

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                    |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------- |
| 433 MB | 0.8% |        53:11 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.78.2 |
```

**Comment by eernstg** [comment]
Clearly, the analyzer should report that `A` does not resolve to a type (or indeed anything).

**Comment by srawlins** [comment]
Analyzer now crashes on this input (without the type variable):

```none
Internal error: Null check operator used on a null value
#0      TypeParameterReplacer.visitTypeParameterType (package:analyzer/src/generated/exhaustiveness.dart:780:44)
#1      TypeParameterTypeImpl.accept (package:analyzer/src/dart/element/type.dart:1678:20)
#2      ReplacementVisitor.visitTypeArgument (package:analyzer/src/dart/element/replacement_visitor.dart:523:21)
#3      ReplacementVisitor._typeArguments (package:analyzer/src/dart/element/replacement_visitor.dart:570:26)
#4      ReplacementVisitor.visitInterfaceType (package:analyzer/src/dart/element/replacement_visitor.dart:375:28)
#5      InterfaceTypeImpl.accept (package:analyzer/src/dart/element/type.dart:836:20)
#6      TypeParameterReplacer._replaceTypeParameterTypes (package:analyzer/src/generated/exhaustiveness.dart:786:17)
#7      TypeParameterReplacer.replaceTypeVariables (package:analyzer/src/generated/exhaustiveness.dart:791:46)
#8      AnalyzerTypeOperations.overapproximate (package:analyzer/src/generated/exhaustiveness.dart:393:34)
#9      SealedClassStaticType._createSubtypes (package:_fe_analyzer_shared/src/exhaustiveness/types/sealed.dart:94:40)
#10     SealedClassStaticType.getSubtypes (package:_fe_analyzer_shared/src/exhaustiveness/types/sealed.dart:68:21)
#11     _Checker._unmatched (package:_fe_analyzer_shared/src/exhaustiveness/exhaustive.dart:158:31)
#12     computeExhaustiveness (package:_fe_analyzer_shared/src/exhaustiveness/exhaustive.dart:63:38)
#13     ConstantVerifier._validateSwitchExhaustiveness (package:analyzer/src/dart/constant/constant_verifier.dart:935:27)
#14     ConstantVerifier.visitSwitchExpression.<anonymous closure> (package:analyzer/src/dart/constant/constant_verifier.dart:440:7)
#15     ConstantVerifier._withConstantPatternValues (package:analyzer/src/dart/constant/constant_verifier.dart:1058:6)
#16     ConstantVerifier.visitSwitchExpression (package:analyzer/src/dart/constant/constant_verifier.dart:438:5)
#17     SwitchExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:17110:50)
#18     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6086:17)
#19     RecursiveAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:1088:10)
#20     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:6078:15)
#21     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8529:11)
#22     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:1208:10)
#23     ConstantVerifier.visitFunctionExpression (package:analyzer/src/dart/constant/constant_verifier.dart:221:11)
...
```
