### ISSUE TITLE
vm-aot-win-debug-x64c fails because `globalInt` cant be resolved

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#54382]
```
stderr     : Unhandled exception:

Invalid argument(s): Couldn't resolve native function 'globalInt' in 'file:///C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_ffi_native_assets_asset_absolute_test/asset_absolute_test.dart' : Failed to lookup symbol 'globalInt': error code 127.



#0      Native._ffi_resolver.#ffiClosure0 (dart:ffi-patch/ffi_patch.dart)

#1      Native._ffi_resolver_function (dart:ffi-patch/ffi_patch.dart:1386:20)

#2      globalInt (file:///C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_ffi_native_assets_asset_absolute_test/asset_absolute_test.dart)

#3      testFfiTestFieldsDll (file:///C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_ffi_native_assets_asset_absolute_test/asset_absolute_test.dart:122:17)

#4      runTests (file:///C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_ffi_native_assets_asset_absolute_test/asset_absolute_test.dart:69:3)

#5      main.<anonymous closure> (file:///C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_ffi_native_assets_asset_absolute_test/asset_absolute_test.dart:33:13)

#6      selfInvokingTest.<anonymous closure> (file:///C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_ffi_native_assets_asset_absolute_test/helpers.dart:388:36)

#7      main (file:///C:/b/s/w/ir/out/DebugX64C/generated_compilations/vm-aot-win-debug-x64c/tests_ffi_native_assets_asset_absolute_test/asset_absolute_test.dart:41:4)

#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:33)

#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by dcharkes** [comment]
Thanks @brianquinlan !

https://dart-review.googlesource.com/c/sdk/+/342260
